### ISSUE TITLE
Image Hosting

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/yolov5#1]
![Screen Shot 2022-08-06 at 2 30 51 PM](https://user-images.githubusercontent.com/26833433/183249047-68577230-44f5-422c-8fe1-b000d2b11d4b.jpg)

## 🚀 Feature
Image Placeholder

<img width="948" alt="Screenshot 2021-04-11 at 16 22 47" src="https://user-images.githubusercontent.com/26833433/114307955-5c7e4e80-9ae2-11eb-9f50-a90e39bee53f.png">

![study_P6](https://user-images.githubusercontent.com/26833433/114313216-f0a5e100-9af5-11eb-8445-c682b60da2e3.png)
![study_P5](https://user-images.githubusercontent.com/26833433/114313219-f1d70e00-9af5-11eb-9973-52b1f98d321a.png)

### v6.1

![study_P6_v61](https://user-images.githubusercontent.com/26833433/155040763-93c22a27-347c-4e3c-847a-8094621d3f4e.png)

![study_P5_v61](https://user-images.githubusercontent.com/26833433/155040757-ce0934a3-06a6-43dc-a979-2edbbd69ea0e.png)

**Comment by glenn-jocher** [comment]
![splash](https://user-images.githubusercontent.com/26833433/121094150-72607500-c7ee-11eb-9f39-1d9e4ce89a9e.jpg)

![splash2](https://user-images.githubusercontent.com/26833433/98699617-a1595a00-2377-11eb-8145-fc674eb9b1a7.jpg)

![mockup-of-three-iphones-xs-max-lying-on-a-customizable-background-253-el](https://user-images.githubusercontent.com/26833433/85940594-2d3f7d80-b8d2-11ea-809a-87b3bf6d968b.jpg)

![82943967-43fb5900-9f4f-11ea-8a0b-70d73a709a49](https://user-images.githubusercontent.com/26833433/82944393-f7644d80-9f4f-11ea-8b87-1a5b04f555f1.jpg)

![Screenshot 2020-11-05 at 00 55 04](https://user-images.githubusercontent.com/26833433/98180594-a21a6800-1f01-11eb-9524-7d83d9db3593.jpg)

![Screenshot 2020-11-05 at 01 06 10](https://user-images.githubusercontent.com/26833433/98181326-3b964980-1f03-11eb-8bb3-bf2a085831fd.jpg)

![Screen Shot 2022-08-03 at 12 15 15 AM](https://user-images.githubusercontent.com/26833433/182482859-288a9622-4661-48db-99de-650d1dead5c6.jpg)

![image-local_logging](https://user-images.githubusercontent.com/26833433/183222430-e1abd1b7-782c-4cde-b04d-ad52926bf818.jpg)

**Comment by glenn-jocher** [comment]
![download](https://user-images.githubusercontent.com/26833433/97107365-685a8d80-16c7-11eb-8c2e-83aac701d8b9.jpeg)

<img src="https://user-images.githubusercontent.com/26833433/114868289-08cb7800-9df6-11eb-85ca-58545cf45a83.png" width="500"> 

<img src="https://user-images.githubusercontent.com/26833433/114868505-47613280-9df6-11eb-9cb0-c383358d37d2.png" width="300">

![download](https://user-images.githubusercontent.com/26833433/127574988-6a558aa1-d268-44b9-bf6b-62d4c605cc72.jpg)

**Comment by glenn-jocher** [comment]
fpn with FP32
![study_mAP_latency](https://user-images.githubusercontent.com/26833433/84200349-729f2680-aa5b-11ea-8f9a-604c9e01a658.png)

panet with FP16
![study_mAP_latency2](https://user-images.githubusercontent.com/26833433/85340570-30360a80-b49b-11ea-87cf-bdf33d53ae15.png)

v3.0
![study_mAP_latency2](https://user-images.githubusercontent.com/26833433/90187293-6773ba00-dd6e-11ea-8f90-cd94afc0427f.png)

v4.0
![test_study2](https://user-images.githubusercontent.com/26833433/103594689-455e0e00-4eae-11eb-9cdf-7d753e2ceeeb.png)
<img width="1147" alt="models" src="https://user-images.githubusercontent.com/26833433/103595982-ab986000-4eb1-11eb-8c57-4726261b0a88.png">


v3.1
<img width="1127" alt="YOLOv5_models" src="https://user-images.githubusercontent.com/26833433/97808084-edfcb100-1c64-11eb-83eb-ffed43a0859f.png">
![download](https://user-images.githubusercontent.com/26833433/97808309-8182b180-1c66-11eb-8461-bffe1a79511d.png)

**Comment by glenn-jocher** [comment]
![results](https://user-images.githubusercontent.com/26833433/84186698-c4d54d00-aa45-11ea-9bde-c632c1230ccd.png)

v3.0, start=0, stop=299
![results](https://user-images.githubusercontent.com/26833433/90222759-949d8800-ddc1-11ea-9fa1-1c97eed2b963.png)

**Comment by glenn-jocher** [comment]
<p align="center"><img width="800" src="https://user-images.githubusercontent.com/26833433/112548245-35264280-8dbc-11eb-990e-2aa89cd999ba.jpg"></p>

<img width="1191" alt="GCP terminal" src="https://user-images.githubusercontent.com/26833433/105813160-47266900-5f64-11eb-9fa7-c43f45635de0.png">


![inference_sources](https://user-images.githubusercontent.com/26833433/98274798-2b7a7a80-1f94-11eb-91a4-70c73593e26b.jpg)

<img width="1101" alt="GCP" src="https://user-images.githubusercontent.com/26833433/105811495-95863880-5f61-11eb-841d-c2f2a5aa0ffe.png">

**Comment by glenn-jocher** [comment]
AWS Tutorial image hosting

<img width="800" alt="Console" src="https://user-images.githubusercontent.com/26833433/106323804-debddd00-622c-11eb-997f-b8217dc0e975.png">

<img width="800" alt="Launch" src="https://user-images.githubusercontent.com/26833433/106323950-204e8800-622d-11eb-915d-5c90406973ea.png">

<img width="800" alt="Choose AMI" src="https://user-images.githubusercontent.com/26833433/106326107-c9e34880-6230-11eb-97c9-3b5fc2f4e2ff.png">

<img width="800" alt="Choose Type" src="https://user-images.githubusercontent.com/26833433/106324624-52141e80-622e-11eb-9662-1a376d9c887d.png">

<img width="800" alt="Spot Request" src="https://user-images.githubusercontent.com/26833433/106324835-ac14e400-622e-11eb-8853-df5ec9b16dfc.png">

<img width="800" alt="Connect" src="https://user-images.githubusercontent.com/26833433/106325530-cf8c5e80-622f-11eb-9f64-5b313a9d57a1.png">

**Comment by glenn-jocher** [comment]
<p align="center">centered content</p>

## Integrations

<table>
<tbody>
<tr>
<td align="center"><b>Weights & Biases</b><br>Experiment Logging<br><br><p align="center"><a href="https://wandb.ai/site"><img src="https://raw.githubusercontent.com/wandb/assets/main/wandb-dots-logo.svg" width="150" /></a></p></td>
<td align="center"><b>Supervise.ly</b><br>Training Platform<br><br><p align="center"><a href="https://ecosystem.supervise.ly/yolov5"><img src="https://miro.medium.com/max/3150/1*gZtiGa312HWzzkW1t3qL7A.png" width="150" /></a></p></td>
</tr>
</tbody>
</table>

## Environments

<table>
<tbody>
<tr>
<td align="center" width=200><b>Google Colab</b><br>Notebook<br><sup>with free GPU<br><p align="center"><a href="https://www.facebook.com/ultralytics"><img src="https://storage.googleapis.com/ultralytics/web/colab.png" width=50 /></a></p></td>
<td align="center"><b>Kaggle</b><br>Notebook<br><sup>with free GPU<br><p align="center"><a href="https://www.facebook.com/ultralytics"><img src="https://storage.googleapis.com/ultralytics/web/kaggle.png" width="100" /></a></p></td>
<td align="center"><b>Google Cloud</b><br>Deep Learning VM<br><br><p align="center"><a href="https://www.facebook.com/ultralytics"><img src="https://storage.googleapis.com/ultralytics/web/gcp.png" width="100" /></a></p></td>
<td align="center"><b>Amazon</b><br>Deep Learning AMI<br><br><p align="center"><a href="https://www.facebook.com/ultralytics"><img src="https://storage.googleapis.com/ultralytics/web/ec2.png" width="100" /></a></p></td>
<td align="center"><b>Docker</b><br>Image<br><br><p align="center"><a 
href="https://www.facebook.com/ultralytics"><img src="https://storage.googleapis.com/ultralytics/web/docker.png" width="100" /></a></p></td>
</tr>
</tbody>
</table>

## Environments Centered


<table>
<tbody>
<tr>
<td align="center"><b>Google Colab</b><br>Notebook<br><sup>with free GPU<br><a href="https://www.facebook.com/ultralytics"><img src="https://storage.googleapis.com/ultralytics/web/colab.png" width="100" /></a></td>
<td align="center"><b>Kaggle</b><br>Notebook<br><sup>with free GPU<br><p align="center"><a href="https://www.facebook.com/ultralytics"><img src="https://storage.googleapis.com/ultralytics/web/kaggle.png" width="100" /></a></p></td>
<td align="center"><b>Google Cloud</b><br>Deep Learning VM<br><br><p align="center"><a href="https://www.facebook.com/ultralytics"><img src="https://storage.googleapis.com/ultralytics/web/gcp.png" width="100" /></a></p></td>
<td align="center"><b>Amazon</b><br>Deep Learning AMI<br><br><p align="center"><a href="https://www.facebook.com/ultralytics"><img src="https://storage.googleapis.com/ultralytics/web/ec2.png" width="100" /></a></p></td>
<td align="center"><b>Docker</b><br>Image<br><br><p align="center"><a 
href="https://www.facebook.com/ultralytics"><img src="https://storage.googleapis.com/ultralytics/web/docker.png" width="100" /></a></p></td>
</tr>
</tbody>
</table>

**Comment by jeannotes** [comment]
@glenn-jocher I asm wondering that in the above pics, eg: https://user-images.githubusercontent.com/26833433/84200349-729f2680-aa5b-11ea-8f9a-604c9e01a658.png

for one single model: yolov5s.yaml, and the x coordinate is inference speed, for one pic, the inference time should be different in different machine, am I mis-understanding, or did you mean that with the same overall-architecture, like yolov5s.yaml, the are still miner differences between them?
hope that you give a hint. thanks

btw, how to reproduce the full results like this picsture?
I know that "python test.py --task study --data coco.yaml --iou 0.7 --weights yolov5s6.pt yolov5m6.pt yolov5l6.pt yolov5x6.pt " may give the results, but how about the difference inference time coordinate, feel confused.

**Comment by glenn-jocher** [comment]
@jeannotes commands to reproduce chart are shown in comments directly below chart. See README.
