### ISSUE TITLE
Detecting objects from Coco dataset outside of Coco128

### ISSUE THREAD

**Issue by maelfabien** [ultralytics/yolov5#100]
Hi, 

Thanks for making this open-source. I'm looking for a way to detect a door using the pre-trained weights provided in yolov5s.pt. Is the pre-trained version trained on coco128 subset of classes? I did not find the answer on the Wiki, and if it's the case, I need to re-train yolov5 on the new subset of classes I'm interested in, I have seen the article related to that on the Wiki.

Thanks !

**Comment by glenn-jocher** [comment]
@maelfabien all of the models are trained on coco2017:
http://cocodataset.org/#home

To train on custom data follow instructions in wiki.

**Comment by maelfabien** [comment]
My bad, I thought that you constrained the classes compared to the full Coco2017. Thanks for the quick reply !
