### ISSUE TITLE
YOLOv4

### ISSUE THREAD

**Issue by Jubbuuliiing** [ultralytics/yolov5#10008]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I see you put the YOLOv3 project into the YOLOv5v6.0, can you consider putting the YOLOv4 model into the current project?

**Comment by glenn-jocher** [comment]
Thank you for your feature suggestion on how to improve YOLOv5 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
