### ISSUE TITLE
background FP value is 1 in confusion_matrix after training

### ISSUE THREAD

**Issue by tinly00** [ultralytics/yolov5#10007]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When i after training, I got a 1 value of background FP in confusion matrix, but i can not find the reason. How can i solve this ? Thank you!

The mAP_0.5 is 0.9, but why the value of background FP is 1 in confusion matrix? Background FP means target is false, but predicted positive, this is an error detection, if this value is 1, why the map can reach 0.9? 
If anyone can give me a hand, i will very appreciate!

@glenn-jocher 

### Additional

Some traning results as following:
![confusion_matrix](https://user-images.githubusercontent.com/93133444/199371402-0624d0a4-e943-4900-b9f4-e6a38e11b278.png)
![F1_curve](https://user-images.githubusercontent.com/93133444/199371434-54017038-095a-48fd-944e-4dfda1535ca1.png)
![labels_correlogram](https://user-images.githubusercontent.com/93133444/199371449-7715efe0-f2d3-4974-8ad3-0a8369396191.jpg)
![labels_xyls](https://user-images.githubusercontent.com/93133444/199371458-597afae0-b045-4621-9dde-e76055d0c971.jpg)
![PR_curve](https://user-images.githubusercontent.com/93133444/199371477-e36766f6-140e-4002-8d00-9165c830a810.png)
![results](https://user-images.githubusercontent.com/93133444/199371489-b282b098-78ad-47b5-80d6-ef340cb55613.png)

train_batch0:
![train_batch0](https://user-images.githubusercontent.com/93133444/199371583-dee81e5c-465c-4619-8d0e-87023887f0d4.jpg)
train_batch1:
![train_batch1](https://user-images.githubusercontent.com/93133444/199371597-93a64bf5-9a4b-4a1a-b723-cb8cd0610a30.jpg)
val_batch0_pred:
![val_batch0_pred](https://user-images.githubusercontent.com/93133444/199371619-bdb08a83-8d47-4c2d-860b-5cd4eba32348.jpg)

hyp:
```
lr0: 0.01
lrf: 0.2
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 250
warmup_momentum: 0.8
warmup_bias_lr: 0.1
box: 0.05
cls: 0.5
cls_pw: 1.0
theta: 0.5
theta_pw: 1.0
obj: 1.0
obj_pw: 1.0
iou_t: 0.2
anchor_t: 4.0
fl_gamma: 0.0
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 180.0
translate: 0.1
scale: 0.25
shear: 0.0
perspective: 0.0
flipud: 0.5
fliplr: 0.5
mosaic: 0.75
mixup: 0.1
copy_paste: 0.0
cls_theta: 180
csl_radius: 2.0
```

**Comment by tinly00** [comment]
Is this background FP correct?
![深度截图_选择区域_20221102093917](https://user-images.githubusercontent.com/93133444/199374655-57adcbd0-ab5b-4509-8d2a-0cc71a76a47a.png)

**Comment by glenn-jocher** [comment]
@tinly00 Confusion matrix columns are normalized to sum to 1. To see actual values in matrix instead of normalized set normalized=False here:
https://github.com/ultralytics/yolov5/blob/fde77584687041aa62795bb2c27e895cf73686bf/utils/metrics.py#L190
