### ISSUE TITLE
Stream videos are saved too quickly.

### ISSUE THREAD

**Issue by sinae-noh** [ultralytics/yolov5#10009]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

For example, if the stream video is 60 seconds, the saved video is 20 seconds long. Saved too quickly.
The rtsp fps is 20 and the save fps is also 20. What's wrong? I want to save it properly.

**Comment by glenn-jocher** [comment]
@sinae-noh you can adjust frame skipping in the streamloader in utils/dataloaders.

**Comment by sinae-noh** [comment]
@glenn-jocher what line of code??

**Comment by glenn-jocher** [comment]
@sinae-noh vid-stride here should control this:
https://github.com/ultralytics/yolov5/blob/e00d02d78b772d7848689d8947238e4b05986a54/detect.py#L244

Default 1 means read very frame.

**Comment by sinae-noh** [comment]
@glenn-jocher I've controlled the vid-stride, but it's not saving correctly in real time.

**Comment by sinae-noh** [comment]
@glenn-jocher Saving one stream works fine, but saving multiple streams seems to cause problems... I couldn't fix it, but thanks for the reply

**Comment by glenn-jocher** [comment]
@sinae-noh You're welcome! Handling multiple streams can be complex due to asynchronous loading and hardware limitations. I appreciate your understanding, and please feel free to reach out if you have any further questions.
