### ISSUE TITLE
tensorboard with gcp

### ISSUE THREAD

**Issue by mbenami** [ultralytics/yolov5#10015]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

When you have URL in `--project` the `Path` function removes the double slashes in the start 
for example `Path("gs://yolov5")`
will be `PosixPath('gs:/yolov5')`

that cause tensorboard writing summary to fail
https://github.com/ultralytics/yolov5/blob/82a558557a825d380178527f4b0ff175f33457fe/utils/loggers/__init__.py#L104

we convert the `save_dir` with Path on the start 
https://github.com/ultralytics/yolov5/blob/82a558557a825d380178527f4b0ff175f33457fe/train.py#L69 

can we have another variable for tensorboard  (`opt.tensorboard`)
that if exist tensorboard will lunch on that path as is?

or dirty fix will be before launching the SummaryWriter check if start with `http:/` or `gs:/` and add `/`

### Use case

`python train.py --project gs://yolo...`

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@mbenami hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by mbenami** [comment]
Hi @glenn-jocher  
thanks for the response I hop ill have some time to work on this week 
I thought of 2 ways to solve this 

1. add a new variable for tensorboard path in the main train  (as there are already many variables not sure adding more just for this case is what you want..) 

2. before launching the tensorboard :https://github.com/ultralytics/yolov5/blob/78ed31c95a3b01c98a39a5b2edceb48ab630c95d/utils/loggers/__init__.py#L100
check if `s` start with `gs:/` and as we know Path will remove the double slash add in the start 
`s.replace("gs:/", "gs://")` 

the second seems to me more like a "dirty fix" just for this case 
any suggestion on which approach to go with?

**Comment by glenn-jocher** [comment]
@mbenami sorry, fell behind on this convo. I'm not sure logging directly to a bucket is a good idea, you might be better off using remote logging tools like ClearML or Comet that do this automatically. 

For a TensorBoard update, whatever is the simplest with the least parameters that facilitates the highest adoption is probably the best solution/compromise.

**Comment by mbenami** [comment]
@glenn-jocher thanks for the replay 
we already start looking on clearml 
Thanks

**Comment by glenn-jocher** [comment]
@mbenami you're welcome! ClearML is an excellent choice, it provides a lot of useful features. Good luck with your project!
