### ISSUE TITLE
Why do I detect a live video stream of a flv, but yolo shows WARNING: Video stream unresponsive, please check your IP camera connection, and shows no frame!

### ISSUE THREAD

**Issue by hahahelloword** [ultralytics/yolov5#10016]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Why do I detect a live video stream of a flv, but yolo shows WARNING: Video stream unresponsive, please check your IP camera connection, and shows no frame!
my video stream is in this format：http://xxx.xxx.xxx.xxx:9999/flv?port=1935&app=rtmplive1&stream=lcx1
![image](https://user-images.githubusercontent.com/46193975/199641226-b620fa18-f69d-4bbb-b99f-113409a112d7.png)

**Comment by glenn-jocher** [comment]
@hahahelloword YOLOv5 uses cv2 for streaming, so first make sure that your streaming source reads correctly with cv2.
