### ISSUE TITLE
Predicted bounding boxes are too small

### ISSUE THREAD

**Issue by JesusSilvaUtrera** [ultralytics/yolov5#10013]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I'm trying to train with my own dataset, but when I look at the val_batch images, the bounding boxes predicted are too small, so IoU is close to 0. Also, as IoU is very small, when the training computes the metrics all the predicted objects are marked as False predictions, so mAP is null.
![val_batch0_pred](https://user-images.githubusercontent.com/79662866/199472109-9f5318d0-3308-487d-8c1c-3cb63363a88f.jpg)
![results](https://user-images.githubusercontent.com/79662866/199472329-da12f0f5-31a6-4ea7-8a30-ac8f9ab92d3b.png)
I have debugged and found out that the labels are being read well, as you can see in the train_batch images
![train_batch0](https://user-images.githubusercontent.com/79662866/199472587-3c7cfda7-442e-4421-802c-766e96fda647.jpg)
I don't know if this problem has to be with some parameters of my training or some bug in the code, I would really appreciate any help.

**Comment by JesusSilvaUtrera** [comment]
UPDATE: I have discovered that the problems are that auto-generated anchors are a poor fit to dataset (~0.4 BPR), anyone who knows why is this happening?

**Comment by glenn-jocher** [comment]
@JesusSilvaUtrera if AutoAnchor finds lower BPR with new anchors than with existing anchors it should default to existing anchors, i.e. the ones in your model.yaml file:
https://github.com/ultralytics/yolov5/blob/fde77584687041aa62795bb2c27e895cf73686bf/models/yolov5s.yaml#L7-L11
