### ISSUE TITLE
yolov5 cancel the classes_filter? how to train some classes rather than all classes

### ISSUE THREAD

**Issue by O2andsAnoxia** [ultralytics/yolov5#10012]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, i have been not found the classes_filter that exist in previous version
so, how to train or val the some class in dataset rather than all classees 

the capture below is previous code of yolov3
dataset.py
![image](https://user-images.githubusercontent.com/47912423/199460303-bb72eef7-7999-4a30-afa8-ddc96198e483.png)

train.py
![image](https://user-images.githubusercontent.com/47912423/199460641-9e409a80-3b27-4596-9955-df89968abf79.png)

**Comment by hardikdava** [comment]
Hi @O2andsAnoxia, you can include class index [here ](https://github.com/ultralytics/yolov5/blob/82a558557a825d380178527f4b0ff175f33457fe/utils/dataloaders.py#L529l)which you want to include during training.

**Comment by krolaper** [comment]
I understand this learning individual classes, not all, without losing the data of the other classes trained? And how to cause it through the theremenal?

**Comment by krolaper** [comment]
> Привет @O2andsAnoxia индекс класса [, вы можете включить сюда ](https://github.com/ultralytics/yolov5/blob/82a558557a825d380178527f4b0ff175f33457fe/utils/dataloaders.py#L529l) , который вы хотите включить во время обучения.

I understand this learning individual classes, not all, without losing the data of the other classes trained? And how to cause it through the theremenal?

**Comment by O2andsAnoxia** [comment]
@hardikdava yes，thanks your advice，i do it as previous set using the filter above pic.
@krolaper you can add this code in my first pic in dataset.py, and add the parameter 'classes filter' to train the specific class you choice

**Comment by krolaper** [comment]
> @hardikdava yes，thanks your advice，i do it as previous set using the filter above pic. @krolaper you can add this code in my first pic in dataset.py, and add the parameter 'classes filter' to train the specific class you choice

where to find this file in yolov5?
