### ISSUE TITLE
clearml variables as environments 

### ISSUE THREAD

**Issue by mbenami** [ultralytics/yolov5#10019]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

when you lunch yolo training with clearml you cannot control the clearml task variable from the train.py `hyp.opt` 
like `project_name` `task_name` .. 
https://github.com/ultralytics/yolov5/blob/82a558557a825d380178527f4b0ff175f33457fe/utils/loggers/clearml/clearml_utils.py#L87
it will be nice if you could change them in the training input so you can lunch several training  each with different names. 

### Use case

lunch different training with different clearml `project_name` or `task_name` without editing the code

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@mbenami that's a good suggestion!

@thepycoder is there a way for ClearML to use the --project and --name arguments for YOLOv5 training, i.e. if I do 
```
python train.py --project PROJECT --name NAME
```
Then it would be nice to see this in ClearML as i.e. experiments/PROJECT/NAME. Currently all trainings go into a YOLOv5/ project.

**Comment by thepycoder** [comment]
Hi @glenn-jocher

Yeah your suggestion would work :)

I didn't include it in v1 integration as to not adjust the global parameters too much. But with your blessing I'll make a PR for it as soon as I'm back at a computer!

Thanks @mbenami for reporting!

**Comment by glenn-jocher** [comment]
@thepycoder awesome, that would be great, thanks :)

**Comment by mbenami** [comment]
Hi @thepycoder  
is there an option also to add also tags? 
I thought to change https://github.com/ultralytics/yolov5/blob/454dae1301abb3fbf4fd1f54d5dc706cc69f8e7e/utils/loggers/clearml/clearml_utils.py#L90 

`tags=getattr(opt, 'tags', ['YOLOv5'])` 
If we don't want to add input args   
(you can use it with  `run(kwargs**)`

**Comment by thepycoder** [comment]
Hi @mbenami 

Sound like a good plan to me! We'd have to document it somewhere, so people know they can use it, but apart from that I see no reason why not!

@glenn-jocher Do you think it makes sense to just use kwargs, or is this a large enough feature to warrant its own argument [here](https://github.com/ultralytics/yolov5/blob/454dae1301abb3fbf4fd1f54d5dc706cc69f8e7e/train.py#L470)?

**Comment by glenn-jocher** [comment]
@AyushExel what do you think about adding a `tags` argument? Is this available in other loggers?
