### ISSUE TITLE
How I can use cutout data augmentation in a different way?

### ISSUE THREAD

**Issue by ampelmannn** [ultralytics/yolov5#10010]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Thanks to your github as you commented, i used YOLOv5s with cutout data augmentation. but i would like to put 'cutout box' in the ground truth bounding box. How can I do?

**Comment by glenn-jocher** [comment]
@ampelmannn hey there! Thanks for reaching out. To apply the "cutout box" directly within the ground truth bounding box for your data augmentation, you can modify the `mosaic.py` augmentor to suit your specific requirements. This file is located in the `yolov5/data` directory of the YOLOv5 repository. You can customize the logic within this file to implement the desired behavior for your cutout data augmentation.

Let me know if you need further assistance!
