### ISSUE TITLE
How can i see what epoch is responsible for the best.pt result

### ISSUE THREAD

**Issue by maxPrakken** [ultralytics/yolov5#10021]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am training yolov5 in a docker container on custom data and i want to know what epoch corresponds to the best.pt weights that are saved in the /usr/src/results folder when the training is complete. In the results.csv that contains all the metrics of the training session I can't seem to be able to extract what the epoch number belongs to the top result accomplished during the training. Does anyone know if that information is included in the results folder of the training session?

**Comment by glenn-jocher** [comment]
best.pt should be saved on every max fitness epoch, which is a weighted combination of metrics mostly tilted towards mAP50-95

**Comment by maxPrakken** [comment]
> best.pt should be saved on every max fitness epoch, which is a weighted combination of metrics mostly tilted towards mAP50-95

Thank you for the time to respond, yes I was aware of that, to phrase it better: how do I know on which epoch the best.pt weights are responsible for? I am building a pipeline that does continues training on a model while new data comes in and I want to be able to display the saved metrics as a way to compare the pervious weights with the ones continuesly trained on the new network

**Comment by glenn-jocher** [comment]
@maxPrakken best.pt is saved on every max fitness epoch, so just find the latest max fitness epoch from results.csv

**Comment by maxPrakken** [comment]
thank you

**Comment by glenn-jocher** [comment]
@maxPrakken you're welcome! If you have any more questions, feel free to ask. Good luck with your continued training!
