### ISSUE TITLE
The reproducing results is differnt from your table

### ISSUE THREAD

**Issue by RainbowSun11Q2H** [ultralytics/yolov5#1002]
Thank you for your excellent work.

## ❔Question
I ran the reproducing code as your readme. However, the mAP of TTA is just 48.5 for yolo5x.pt and the mAP without TTA is 47.0. Do I miss something? Or what happened for this phenomenon?

## Additional context
![image](https://user-images.githubusercontent.com/63624265/93739267-7de91d00-fc1a-11ea-82f6-776d0fa6f968.png)

Thank you for your time and help.

**Comment by RainbowSun11Q2H** [comment]
I notice my reproducing results is same as results in #303. Therefore, how to improve the results to the readme results?

Thank you for your help.

**Comment by glenn-jocher** [comment]
README results are obtained with pycocotools and are correctly reproducible, see notebook.
https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb

<img width="1192" alt="Screen Shot 2020-09-21 at 2 17 15 PM" src="https://user-images.githubusercontent.com/26833433/93822609-55aaef80-fc15-11ea-9377-1c1bf63836bf.png">

**Comment by RainbowSun11Q2H** [comment]
Got it. Thanks for your help and time.
