### ISSUE TITLE
When will tag6.3 be released？

### ISSUE THREAD

**Issue by pychans** [ultralytics/yolov5#10020]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

"Our next release, v6.3 is scheduled for September and will bring official instance segmentation support to YOLOv5, with a major v7.0 release later this year updating architectures across all 3 tasks - classification, detection and segmentation."
Hello, It's been more than a month, When will it be released?

**Comment by glenn-jocher** [comment]
@icsos thanks for asking! We have v7.0 release due soon with the major update being Segmentation

**Comment by icsos** [comment]
OK, thanks, and look forward to the release as soon as possible.

**Comment by guishilike** [comment]
when to update architectures?

**Comment by glenn-jocher** [comment]
@guishilike we plan to update architectures with the upcoming v7.0 release on 22 November. Keep an eye out for the new changes!
