### ISSUE TITLE
Is there a way to export/see false negatives?

### ISSUE THREAD

**Issue by Rikk010** [ultralytics/yolov5#10034]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

As the title says, I am wondering if it is possible to see the false negatives on the validation/test data.
This way I can on which kind of images the model performs poorly

**Comment by glenn-jocher** [comment]
@Rikk010 you can export false negatives using yolo-v5 labeled video, which creates JSON/CSV outputs with detections annotations. Afterwards, compare these against your ground truth using a script to identify false negatives. This enables you to pinpoint images where the model underperforms. More details can be found in the Ultralytics Docs at https://docs.ultralytics.com/yolov5/.
