### ISSUE TITLE
when training, try to connect github?

### ISSUE THREAD

**Issue by yangboz** [ultralytics/yolov5#10032]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
        0/4      3.55G     0.1117     0.0386     0.0531         37        960:  96%|█████████▌| 22/23 [00:36<00:01,  1.23s/it]                                               fatal: unable to access 'https://github.com/ultralytics/yolov5.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.

 Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
  0%|          | 0/23 [00:00<?, ?it/s]                                                                                                                                       fatal: unable to access 'https://github.com/ultralytics/yolov5.git/': Failed to connect to github.com port 443: timeout 连接超时

### Additional

python38yolov5 ,ubuntu18.04

**Comment by glenn-jocher** [comment]
@yangboz hi there! It looks like you are experiencing issues with connecting to GitHub during training. This error seems to be related to the network or connection settings. You might want to check your internet connection and firewall settings to ensure that you can access GitHub during training. Additionally, make sure that the GitHub repository is accessible from your current environment. If the issue persists, feel free to provide more details for further assistance.

You can also refer to the YOLOv5 documentation for more information on training and troubleshooting: https://docs.ultralytics.com/yolov5/

Let me know if you need any further help!
