### ISSUE TITLE
validate dataset issue in classify 

### ISSUE THREAD

**Issue by achel-x** [ultralytics/yolov5#10035]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I try to validate YOLOv5s-cls accuracy on ImageNet-1k dataset as the guidance of homepage. My device isn't equipped with gpu. I download the val dataset locally and place them in the folder like this 

![image](https://user-images.githubusercontent.com/67953243/199988361-b10906ed-f307-4b09-bfb4-7e3b87c05af8.png)
Then the command was typed as example, but the problem comes out.
![image](https://user-images.githubusercontent.com/67953243/199988713-1ff49591-41e0-416e-8368-38da878877dd.png)

I thought maybe it was the suffix of images. So, I choose one image of them and change its suffix to '.jpg' to test.
![image](https://user-images.githubusercontent.com/67953243/199989310-14f9c197-e5d9-4abe-a3b0-445e5b00b72d.png)

But it doesn't work. The problem is the same as the 2nd image. I am confused. Thanks in advance.

**Comment by glenn-jocher** [comment]
@achel-x ImageNet validation is shown in classify/val.py Usage:
https://github.com/ultralytics/yolov5/blob/fde77584687041aa62795bb2c27e895cf73686bf/classify/val.py#L3-L8

**Comment by glenn-jocher** [comment]
YOLOv5s-cls ImageNet validation works correctly
<img width="921" alt="Screenshot 2022-11-05 at 00 56 36" src="https://user-images.githubusercontent.com/26833433/200090840-6e9610c6-f4db-494f-9253-7388695d5a54.png">
