### ISSUE TITLE
feature fusion

### ISSUE THREAD

**Issue by LiYan0306** [ultralytics/yolov5#10030]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

In the course of my research on yolo, I found a problem:
 for example, in the yolov5 network, why is the feature map used for feature fusion output from the backbone part of these positions, but not the other positions?  Would it be better if the feature maps were output at other locations for feature fusion. 
Or can you explain why the feature maps from those positions were chosen for feature fusion?

**Comment by glenn-jocher** [comment]
hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
