### ISSUE TITLE
Train from stop but performance in val test drop about 25%

### ISSUE THREAD

**Issue by zhaiyutong** [ultralytics/yolov5#1003]
## ❔Question
Hi, when I train from my stop point, the result of first epoch will drop about 25% score compared to the stop's performance.

## Additional context
And I test the loaded model before training which has the same performance with the stop one, but after one epoch of training, it drops, which takes about 8 epochs to have the similar performance of stop one.
Could you help me solve it?
Thanks a lot!

**Comment by srqj** [comment]
Same here, I reloaded the model's state_dict, ema.ema's state_dict(averaged), ema.updates, LR, and optimizer.state_dict, are there any intermediate training states missing? Also I'm using ddp. Thanks!
