### ISSUE TITLE
FLOP Calculation

### ISSUE THREAD

**Issue by UnglvKitDe** [ultralytics/yolov5#10042]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,

I have a question about FLOP calculation in YOLOv5. In the method `model_info(...)` you use the library thop to get the mac operations.
https://github.com/ultralytics/yolov5/blob/436ffc417ac2312de18287ddc4f87bdc2f7f5734/utils/torch_utils.py#L217-L239

Then you calculate the returned MACs * 1E9 * 2.
https://github.com/ultralytics/yolov5/blob/436ffc417ac2312de18287ddc4f87bdc2f7f5734/utils/torch_utils.py#L232

But according to the documentation [here](https://github.com/Lyken17/pytorch-OpCounter/blob/43c064afb71383501e41eaef9e8c8407265cf77f/benchmark/evaluate_famous_models.py#L26-L29), you should calculate only * 1E9 or (1000 ** 3). Why do you multiply a 2 to it?

Thank you :)

**Comment by glenn-jocher** [comment]
One MACC contains one multiplication and one addition. One multiplication or one addition can be seen as one FLOP. So one MACC has two FLOPS.
