### ISSUE TITLE
Script for iterative inference of JPG

### ISSUE THREAD

**Issue by cleverpal-ai** [ultralytics/yolov5#10041]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have a simple script for analysis of IP cam (based on JPG stream):

```
import torch
import requests

model = torch.hub.load('ultralytics/yolov5', 'yolov5x6')
model.conf = 0.5

img = 'http://192.168.0.4/jpg/1/image.jpg'

results = model(img)
count_person = 0
pred = results.pandas().xyxy[0]
for index, row in pred.iterrows():
#print(row['class'], row['confidence'])
  if str(row['class']) == "0":
    count_person = count_person + 1
if count_person > 0:
  requests.get('http://192.168.0.3:1880/endpoint/send-camfront')
  results.save(save_dir="front/", exist_ok="jpg.jpg")
```

I need to run inference every 5 seconds on the img source (http://192.168.0.4/jpg/1/image.jpg) of my camera.
I am counting persons and in case of any person detected, I am sending an HTTP GET request & saving the detected object.

What I need to modify & kindly asking for help is:
1) How can I run inference iteratively every 5 seconds without relaunching script itself? I need to envisage some king of "for" cycle here. I need some kind of iterative inference as in case of RTSP, but on JPG source. 
2) Is there a possibility to terminate script by sending some command (e.g. HTTP GET request to a server where the script is running)

**Comment by glenn-jocher** [comment]
@SuperMaximus1984 hi there! 👋 Your use case sounds interesting! To iteratively run inference every 5 seconds, you can use a loop such as `while True` and incorporate a time delay with `time.sleep(5)` to effectively run the inference every 5 seconds.

For terminating the script remotely, you can have the script listen for a specific HTTP GET request by utilizing a lightweight HTTP server such as Flask or FastAPI. When the termination request is received, you can gracefully exit the script using `sys.exit()`.

Let me know if you need further guidance or code examples! Happy coding!
