### ISSUE TITLE
aboute open QFocalLoss/FocalLoss

### ISSUE THREAD

**Issue by FYM1209** [ultralytics/yolov5#10043]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

about open QFocalLoss/FocalLoss,i want to open QFocalLoss/FocalLoss,umm the .reduction use sum or mean or none?
thx

![image](https://user-images.githubusercontent.com/93715148/200107744-e8c83cb7-2fe2-4631-94cc-d40683e57d85.png)

**Comment by glenn-jocher** [comment]
inherits from first argument

**Comment by glenn-jocher** [comment]
Well the first argument is a loss function that has it's won reduction attribute defined.
