### ISSUE TITLE
Custom model architecture

### ISSUE THREAD

**Issue by GulerEnes** [ultralytics/yolov5#10044]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have 2 questions.

1) I'm trying to make my model faster. For this, I want to reduce the number of layers. When I change depth_multiple and width_multiple, the number of layers and params are changing.

When I start training model summary is printed. In yaml file, there are a few layers but the summary for the nano model says 214 layers. I couldn't understand what is happening here. How can I see all 214 layers and change them?
<img width="840" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/58073016/200113928-267a4f0a-af43-4a69-8430-b88c731d4995.png">

2) There are some layer names that are not in Yolov3. What do C3 and SPPF layers? Is there any documentation for these to understand what they are?

Thanks in advance for your answer.

**Comment by glenn-jocher** [comment]
@GulerEnes yes compound scaling factors modify model size and depth. You can see all modules used in models/common.py
