### ISSUE TITLE
Number of Classes

### ISSUE THREAD

**Issue by mathur01** [ultralytics/yolov5#10054]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When i am running 
`model = torch.hub.load('ultralytics/yolov5', 'yolov5s', classes=10) `

Getting this error 
```
Traceback (most recent call last):
  File "c:/Users/nirbhay.mathur/Desktop/Yolov5Test/python/HMtest.py", line 18, in <module>
    results= model(im1)
  File "C:\Users\nirbhay.mathur\Anaconda3\envs\YOLOV5\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\nirbhay.mathur/.cache\torch\hub\ultralytics_yolov5_master\models\yolo.py", line 209, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "C:\Users\nirbhay.mathur/.cache\torch\hub\ultralytics_yolov5_master\models\yolo.py", line 121, in _forward_once
    x = m(x)  # run
  File "C:\Users\nirbhay.mathur\Anaconda3\envs\YOLOV5\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\nirbhay.mathur/.cache\torch\hub\ultralytics_yolov5_master\models\common.py", line 57, in forward
    return self.act(self.bn(self.conv(x)))
  File "C:\Users\nirbhay.mathur\Anaconda3\envs\YOLOV5\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\nirbhay.mathur\Anaconda3\envs\YOLOV5\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\nirbhay.mathur\Anaconda3\envs\YOLOV5\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
TypeError: conv2d() received an invalid combination of arguments - got (JpegImageFile, Parameter, NoneType, tuple, tuple, tuple, int), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (JpegImageFile, Parameter, NoneType, tuple, tuple, tuple, int)
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (JpegImageFile, Parameter, NoneType, tuple, tuple, tuple, int) 
```

Main idea is to use only 1 class instead of all 80 classes. I need only one class should be predicted.

**Comment by glenn-jocher** [comment]
@mathur01 load a model normally and then follow the usage examples in the PyTorch Hub tutorial to filter the classes you want:

## Tutorials

- [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)  🚀 RECOMMENDED
- [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)  ☘️ RECOMMENDED
- [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
- [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) 🌟 NEW
- [TFLite, ONNX, CoreML, TensorRT Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
- [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
- [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
- [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
- [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
- [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)
- [Architecture Summary](https://docs.ultralytics.com/yolov5/tutorials/architecture_description) 🌟 NEW
- [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)
- [Roboflow for Datasets, Labeling, and Active Learning](https://docs.ultralytics.com/yolov5/tutorials/roboflow_datasets_integration)  🌟 NEW
- [ClearML Logging](https://docs.ultralytics.com/yolov5/tutorials/clearml_logging_integration) 🌟 NEW
- [Deci Platform](https://github.com/ultralytics/yolov5/wiki/Deci-Platform) 🌟 NEW
- [Comet Logging](https://docs.ultralytics.com/yolov5/tutorials/comet_logging_integration) 🌟 NEW

Good luck 🍀 and let us know if you have any other questions!

**Comment by mathur01** [comment]
Thanks for quick help. It worked.

**Comment by glenn-jocher** [comment]
@mathur01 you're welcome! I'm glad to hear it worked for you. If you have any other questions or need further assistance, feel free to ask. Good luck with your project!
