### ISSUE TITLE
Bounding boxes that exceed image dimensions

### ISSUE THREAD

**Issue by jgoo9410** [ultralytics/yolov5#10058]
I don't see any documentation on this particular potential issue. 

Say a rounding error occurs during labelling, and a bounding box is created that exceeds the dimensions of the image; what behaviour will result in a training run? Does YOLOv5 clip the box when processing it? Or will it scale the image to include the box (seems unlikely)?

Just want to know how careful I need to be about avoiding this from occurring!

**Comment by glenn-jocher** [comment]
@jgoo9410 non-normalized or out of bound labels result in image rejection for training and a notice is displayed in the console:
https://github.com/ultralytics/yolov5/blob/6ae3dff7d48bd914a5ab5d20e277b8222cd547c7/utils/dataloaders.py#L1020

**Comment by jgoo9410** [comment]
@glenn-jocher So very careful then!

**Comment by glenn-jocher** [comment]
@jgoo9410 Yes, it's important to ensure bounding boxes are within image boundaries for successful training. If you have any more questions, feel free to ask!
