### ISSUE TITLE
Does not display webcam result

### ISSUE THREAD

**Issue by krolaper** [ultralytics/yolov5#10050]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

I’m trying to: `detect.py --source 0`
Hangs in the stage:
```
YOLOv5 🚀 2022-11-6 Python-3.10.6 torch-1.12.1+cu102 CUDA:0 (NVIDIA GeForce MX130, 2004MiB)

Fusing layers... 
YOLOv5m summary: 290 layers, 22323858 parameters, 0 gradients
```
All started after the correction in the topic: [https://github.com/ultralytics/yolov5/issues/9844](url)
Before fixing, just as the error in the topic by reference, did not display the result of the webcam on the screen, but only saved.
It’s not even running now, it’s hanging, as it says at the beginning of this topic.

### Environment

YOLOv5 🚀 2022-11-6 Python-3.10.6 torch-1.12.1+cu102 CUDA:0 (NVIDIA GeForce MX130, 2004MiB)
- Desktop: Xfce 4.16.0 Distro: Linux Mint 21 Vanessa base: Ubuntu 22.04 jammy
- Python 3.10

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by krolaper** [comment]
tried the link with the YouTube video. also hangs on this moment.

**Comment by glenn-jocher** [comment]
@krolaper I'm unable to reproduce any issues with `python detect.py --source 0`

<img width="1470" alt="Screenshot 2022-11-06 at 17 26 34" src="https://user-images.githubusercontent.com/26833433/200182456-5e751a5a-8df9-48f8-9bd3-3463d6993c44.png">

**Comment by krolaper** [comment]
I went further down the playback path. If you are trying to open a YouTube link, go to detect ->
```
    if webcam:
        view_img = check_imshow(warn=True)
```
then I will move on to general ->
```
def check_imshow(warn=False):
	    # Check if environment supports image displays
	    try:
	        assert not is_notebook()
	        assert not is_docker()
	        cv2.imshow('test', np.zeros(((1, 1, 3)))
```
and on this line of code I have a hang and then the solution does not move. Numpy ver: 1.23.4, opencv-python ver: last

**Comment by elanchezhiyan-official** [comment]
Am facing the same problem, am not able to run the live detection through webcam,
it just gets struck here,


<YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients>

**Comment by glenn-jocher** [comment]
@Mr-Elan hello,

Thank you for reaching out and sharing your issue.

To better assist you, could you please provide additional information about your setup, such as your operating system, Python version, and the versions of numpy and opencv-python that you have installed? This will help us understand the context and potentially identify any compatibility issues.

In the meantime, please make sure you have followed the installation instructions and have all the required dependencies installed.

Looking forward to your response.

Kind regards.
