### ISSUE TITLE
Adding viewable images for each batch

### ISSUE THREAD

**Issue by nanometer34688** [ultralytics/yolov5#1006]
I have noticed that at runtime, the first 3 training batches are viewable in runs/expXX/train_batch0.jpg.

It would be useful to see each at each batch what images are used.

Is this something you would be able to add?

**Comment by asw-v4** [comment]
https://github.com/ultralytics/yolov5/blob/4fce0096fa2f2dc7db12b422200009362de9a056/train.py#L292-L300

Line 292 in train.py allows you to change this, simply remove the ` if ni < 3:`, or change the 3 to a number larger than the total batches in an epoch, and you will generate an image for each batch :)

**Comment by nanometer34688** [comment]
Thank you very much! Worked a charm
