### ISSUE TITLE
Difference between Average Precision and mAP?

### ISSUE THREAD

**Issue by pavilion12** [ultralytics/yolov5#10065]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi there, just wanted to understand the difference between the Precision metric we get and the Mean Average Precision. Is the precision metric simply based on whether or not the model just correctly identified the object, and the mAP taking into account IOU?

Additionally, if my mAP0.50 is 0.85, and my mAP0.50:0.95 is 0.7, does that mean that my model is extremely confident in the bounding boxes it creates compared to a lower mAP0.50:0.95 of like 0.5?

Sorry for the barrage of questions, I'm super new to Computer Vision and this is my first object detection project, but I am extremely interested in it and so far have been enjoying learning about it thoroughly. 

Thanks!

**Comment by glenn-jocher** [comment]
@pavilion12 AP is for a single class. mAP is the mean of all class APs.

**Comment by pavilion12** [comment]
Hi Glenn, thanks for your quick reply!  Just for some more clarification, in the picture below, are you meaning to say that the precision is for a single class? In my training and validation dataset I have 7 classes for inference, and looking at metrics.py, it seems that the precision is calculated as tpc / (tpc + fpc). So, therefore, does the true positives and false positives come from only one random class or is it overall among all inferences from all classes? 

Sorry for the confusion, I suspect I used 'Average Precision' and 'Precision' interchangeably which was the wrong use of terms for the specific question I was asking. 

![image](https://user-images.githubusercontent.com/17904216/200448668-fbae7eff-a07f-4f0c-8309-514abcf25a56.png)

**Comment by glenn-jocher** [comment]
@pavilion12 Precision is for all classes. See https://en.wikipedia.org/wiki/Precision_and_recall

**Comment by Stormyend** [comment]
Hi @pavilion12,
I was struggeling with this too so maybe I can help you: it is best to look it up in the code. mAP is mean average precision which I am sure you know uses the average on the precision-recall curve. The precision shown in the plot is called "mp" (for mean precision) in the code which means it doesn't use an average over the precision-recall curve but a **fixed confidence threshold and iou threshold**.
The value for the iou threshold can be set to a fixed value. The confidence threshold is set by determing the confidence score where the F1-score is maximal, [see here](https://github.com/ultralytics/yolov5/blob/7398d2d77cbac9f66259926d49c26bfa3c257a9b/utils/metrics.py#L91).
