### ISSUE TITLE
No module named 'psutil'

### ISSUE THREAD

**Issue by YYingH** [ultralytics/yolov5#10067]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection, PyTorch Hub

### Bug

After the YOLOv5 AutoCache Update, got an issue when doing model inferencing on detection, details are list in below:  

Downloading: "[https://github.com/ultralytics/yolov5/zipball/master"](https://github.com/ultralytics/yolov5/zipball/master%22) to /root/.cache/torch/hub/master.zip
Traceback (most recent call last):
  File "/app/app.py", line 45, in <module>
    yolo_model = torch.hub.load('ultralytics/yolov5', 'custom',
  File "/usr/local/lib/python3.10/dist-packages/torch/hub.py", line 542, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/hub.py", line 572, in _load_local
    model = entry(*args, **kwargs)
  File "/root/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 83, in custom
    return _create(path, autoshape=autoshape, verbose=_verbose, device=device)
  File "/root/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 33, in _create
    from models.common import AutoShape, DetectMultiBackend
  File "/root/.cache/torch/hub/ultralytics_yolov5_master/models/common.py", line 29, in <module>
    from utils.dataloaders import exif_transpose, letterbox
  File "/root/.cache/torch/hub/ultralytics_yolov5_master/utils/dataloaders.py", line 22, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@YYingH psutil has been in requirements.txt for a while. Try `pip install -r requirements.txt`

https://github.com/ultralytics/yolov5/blob/master/requirements.txt

**Comment by darubiano** [comment]
Hi, something similar is happening to me, when I try to load the model in a cloud function of Google cloud
```python 
Traceback (most recent call last):
  File "/layers/google.python.pip/pip/bin/functions-framework", line 8, in <module>
    sys.exit(_cli())
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/functions_framework/_cli.py", line 37, in _cli
    app = create_app(target, source, signature_type)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/functions_framework/__init__.py", line 288, in create_app
    spec.loader.exec_module(source_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/workspace/main.py", line 7, in <module>
    model = torch.hub.load('ultralytics/yolov5', 'custom', path="best.pt")
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/torch/hub.py", line 399, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/torch/hub.py", line 428, in _load_local
    model = entry(*args, **kwargs)
  File "/root/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 83, in custom
    return _create(path, autoshape=autoshape, verbose=_verbose, device=device)
  File "/root/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 33, in _create
    from models.common import AutoShape, DetectMultiBackend
  File "/root/.cache/torch/hub/ultralytics_yolov5_master/models/common.py", line 29, in <module>
    from utils.dataloaders import exif_transpose, letterbox
  File "/root/.cache/torch/hub/ultralytics_yolov5_master/utils/dataloaders.py", line 22, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
```
CODE:
```python 
import cv2
import torch
model = torch.hub.load('ultralytics/yolov5', 'custom', path="best.pt", device='cpu')
cap = cv2.VideoCapture("video.mp4")
while cap.isOpened():
    success, frame = cap.read()
    if success:
        detect = model(frame)
        info = detect.pandas().xyxy[0]
        confidence_max = info['confidence'].max()
        print(confidence_max)
        if confidence_max >= COINFIDENCE:
            cv2.imwrite(f'IMAGES/fallavial_{COUNT}_{int(confidence_max*100)}.jpg',np.squeeze(detect.render()))
            COUNT+=1
    else:
        break
cap.release()
```
The requirements I use are:
```python
asttokens==2.1.0
backcall==0.2.0
certifi==2022.9.24
charset-normalizer==2.1.1
colorama==0.4.6
contourpy==1.0.6
cycler==0.11.0
decorator==5.1.1
executing==1.2.0
fonttools==4.38.0
idna==3.4
ipython==8.6.0
jedi==0.18.1
kiwisolver==1.4.4
matplotlib==3.6.2
matplotlib-inline==0.1.6
numpy==1.23.4
opencv-python==4.6.0.66
packaging==21.3
pandas==1.5.1
parso==0.8.3
pickleshare==0.7.5
Pillow==9.3.0
prompt-toolkit==3.0.32
psutil==5.9.4
pure-eval==0.2.2
Pygments==2.13.0
pyparsing==3.0.9
python-dateutil==2.8.2
pytz==2022.6
PyYAML==6.0
requests==2.28.1
scipy==1.9.3
seaborn==0.12.1
six==1.16.0
stack-data==0.6.1
https://download.pytorch.org/whl/cpu/torch-1.10.2%2Bcpu-cp39-cp39-linux_x86_64.whl
#torch==1.13.0
torchvision==0.14.0
tqdm==4.64.1
traitlets==5.5.0
typing_extensions==4.4.0
urllib3==1.26.12
wcwidth==0.2.5
```
I install psutil but it doesn't recognize it, 😪

**Comment by glenn-jocher** [comment]
@YYingH that's really strange, psutil is just a package you can install with `pip install psutil`. Alternatively you could try to remove it from the YOLOv5 code, it's mostly use to check available resources like system RAM.

**Comment by wuzuowuyou** [comment]
Solve this problem by run “conda install psutil ”

“pip install psutil ”this command of no avail

**Comment by Madd-G** [comment]
> hi, did you manage to deploy YOLOv5 to GCP?

**Comment by glenn-jocher** [comment]
@Madd-G yes, YOLOv5 can be deployed to Google Cloud Platform (GCP). You can use Google Cloud Functions or other services like Google Cloud Run or Google Kubernetes Engine (GKE) to deploy YOLOv5 on GCP. There are several methods available, depending on your specific requirements and preferences. Feel free to ask if you have any specific questions or need guidance on deploying YOLOv5 to GCP.

**Comment by Madd-G** [comment]
yes, is there an example code to deploy it to GCP? because I always get the error "No module named psutil" when deploying to Google Cloud Run. Please give me a guidance on deploying YOLOv5 to GCP

**Comment by glenn-jocher** [comment]
@Madd-G you can deploy YOLOv5 to Google Cloud Platform (GCP) using Google Cloud Run. Here's a high-level overview of the steps involved:

1. Create a Dockerfile: Create a Dockerfile that specifies the base image, installs the necessary dependencies, and copies your YOLOv5 code into the container.

2. Build the Docker image: Build the Docker image using the Cloud Build service. This will package your YOLOv5 code and its dependencies into a container.

3. Push the Docker image to Container Registry: Push the built Docker image to Google Container Registry to make it accessible to Cloud Run.

4. Deploy to Cloud Run: Use the Google Cloud Console or the `gcloud` command-line tool to deploy your Docker image to Cloud Run. Provide the necessary configuration, such as the service name, region, and resources.

5. Test the deployment: Once deployed, you can test the deployment by sending requests to the Cloud Run service and verify that it's running YOLOv5 correctly.

Regarding the "No module named psutil" error, make sure that the `psutil` package is installed in your Docker image. You can add the necessary installation step in your Dockerfile using either `RUN pip install psutil` or `RUN conda install psutil`, depending on your package manager.

These are the general steps involved in deploying YOLOv5 to GCP. You might need to adjust them based on your specific code and requirements. Let me know if you have any further questions or if you need more detailed guidance.

**Comment by 9Mercury** [comment]
First try to install the psutil (uv pip install psutil) and then your other package that is throwing this issue but don't forget to clear the cache(uv cache clean) before installing the package(uv pip install your_package)

**Comment by pderrenger** [comment]
@9Mercury thanks for sharing your solution! For users encountering the "No module named 'psutil'" error, the most straightforward fix is simply `pip install psutil` since psutil is a standard dependency. If you're still having issues after installation, try clearing your pip cache with `pip cache purge` before reinstalling, or use `conda install psutil` if you're in a conda environment.
