### ISSUE TITLE
image output

### ISSUE THREAD

**Issue by krolaper** [ultralytics/yolov5#10064]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

Found the true reason for the hanging process on the topic: https://github.com/ultralytics/yolov5/discussions/10025
I use the "imageio" library for my other tasks concurrently. I need the "av" library to work properly. But after it is installed, the same conflict begins, which causes the process to hang up and does not display the result.

### Environment

YOLOv5 🚀 2022-11-7 Python-3.10.6 torch-1.13.0+cu117 CUDA:0 (NVIDIA GeForce MX130, 2004MiB)
Desktop: Xfce 4.16.0 Distro: Linux Mint 21 Vanessa base: Ubuntu 22.04 jammy
Python 3.10

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@krolaper hey, thanks for bringing this to our attention! Happy to help. 🚀

Interesting find with the "imageio" and "av" libraries conflict causing the process to hang. We'll look into it and investigate further on our end. Do take a peek at the [Ultralytics Docs](https://docs.ultralytics.com/yolov5/) in the meantime, where you might find useful information. 

Props to the YOLO community and the Ultralytics team for their contributions which enable these discussions to happen. Appreciate your support, and we'll keep you posted as we progress on this.
