### ISSUE TITLE
Get confusion matrix to specific classes

### ISSUE THREAD

**Issue by danik7** [ultralytics/yolov5#10066]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I’m trying to run “val” function and get a confusion matrix. 
is there a way by any chance that I can choose which classes I want the model predict and create a confusion matrix which based on them?

for example - I have a model which trained on 30 classes, and now I want to run val.py just on 25 classes (and get CM on those 25 classes). Is that possible?

**Comment by glenn-jocher** [comment]
No, this is not possible.
