### ISSUE TITLE
Error when inferencing using the trained model directly

### ISSUE THREAD

**Issue by Avishka-Perera** [ultralytics/yolov5#10061]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

I have already trained the model and imported it to my Jupyter Notebook. But when using it to inference an PIL image, I get the following error.

![image](https://user-images.githubusercontent.com/74392492/200219458-b8dc405a-23c2-4525-b9c2-0954ddfcf4b6.png)

A similar error is received also when using a tensor/numpy array

A similar thing happens when testing with an untrained model with custom number of classes.

### Environment

Default environment in google colab. 
Have installed required libraries by !pip install -r https://raw.githubusercontent.com/ultralytics/yolov5/master/requirements.txt

### Minimal Reproducible Example

```
import torch
from PIL import Image

data_path = f"{base_path}/train-lpd/data/artificial-mercosur-license-plates"

model = untrained_model = torch.hub.load('ultralytics/yolov5', 'yolov5s', classes=1, _verbose=False)
img0 = Image.open(f"{data_path}/images/test/monitoring_system_2895.JPG")
results = model(img0)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Avishka-Perera** [comment]
My bad. Found the way to import the model correctly.

**Comment by glenn-jocher** [comment]
👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # yolov5n - yolov5x6 official model
#                                            'custom', 'path/to/best.pt')  # custom model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
results.xyxy[0]  # im predictions (tensor)

results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie

results.pandas().xyxy[0].value_counts('name')  # class counts (pandas)
# person    2
# tie       1
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!
