### ISSUE TITLE
classify/val.py not saving results

### ISSUE THREAD

**Issue by muru-raj10** [ultralytics/yolov5#10073]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Validation

### Bug

running classify/val.py gives the console output but results not saved in val-cls/exp 

Could we add a confusion matrix as well?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@muru-raj10 hi, thank you for your feature suggestion on how to improve YOLOv5 🚀! There's nothing to save right now in classify/val, but we welcome contributions :)

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by Nuralill** [comment]
I have same problem，after running classfy/val.py, nothing generate in runs/val-cls/exp

**Comment by glenn-jocher** [comment]
@Nuralill hi, thank you for your feature suggestion on how to improve YOLOv5 🚀! There's nothing to save right now in classify/val, but we welcome contributions :)

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
