### ISSUE TITLE
yolov5 TFlite model in Android studio 

### ISSUE THREAD

**Issue by ily-R** [ultralytics/yolov5#10085]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,

was anyone able to convert the trained yolov5 model and use it in Android studio without any metadata issues ? 

I am still having issues related to this **https://github.com/ultralytics/yolov5/issues/5784** 

Thank you

**Comment by glenn-jocher** [comment]
@ily-R hi there,

We appreciate your interest in using YOLOv5 for Android development. The issue you've linked regarding metadata compatibility within the TFLite model has been noted, and the team is actively working on resolving it.

Thank you for your patience and understanding as we continue to improve the YOLOv5 experience for all users.

Best regards

**Comment by DifferentLee** [comment]
> @ily-R hi there,
> 
> We appreciate your interest in using YOLOv5 for Android development. The issue you've linked regarding metadata compatibility within the TFLite model has been noted, and the team is actively working on resolving it.
> 
> Thank you for your patience and understanding as we continue to improve the YOLOv5 experience for all users.
> 
> Best regards

@glenn-jocher  Hi there. Is there a solution now for the issue you've linked regarding metadata compatibility within the TFLite model for Android Studio?

**Comment by glenn-jocher** [comment]
Hi @DifferentLee,

As of now, there hasn't been an official update resolving the metadata compatibility issue with the TFLite model in Android Studio. We recommend keeping an eye on the repository for any updates or fixes that may address this issue.

Thank you for your continued patience! 😊

Best regards.
