### ISSUE TITLE
Yolov5 performance 

### ISSUE THREAD

**Issue by danik7** [ultralytics/yolov5#10081]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is there anywhere the confusion matrix of yolov5 on COCO dataset?
In addition, how can I take the confusion matrix of *all* classes and compute based on that the confusion matrix on few specific classes?

**Comment by glenn-jocher** [comment]
Generate one yourself, i.e. `python val.py --data coco.yaml`

![media_images_Results_301_1ec66e26f1c60129923e](https://user-images.githubusercontent.com/26833433/200651136-b7fc7489-5f62-406e-abfd-c73e2826b5b5.png)
