### ISSUE TITLE
How to get the value of the total frame detected?

### ISSUE THREAD

**Issue by qayyumnazir** [ultralytics/yolov5#10098]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to get the value of the total frame detected from detect.py?

"video 1/1 (300/302) C:\Users\qayyu\Desktop\yolov5\streamlityv5\YOLOv5-Streamlit-Deployment\data\uploads\videoplayback_Trim (online-video-cutter.com).mp4: 384x640 1 DIDI, Done. (0.121s)"

I need to get where the value "302" was stored in the detect.py

**Comment by qayyumnazir** [comment]
dataset.frame on detect.py

**Comment by glenn-jocher** [comment]
@qayyumnazir the total number of frames detected can be accessed using `dataset.n` in the `detect.py` script. This attribute holds the total number of frames processed during detection. You can find more details in the Ultralytics YOLOv5 documentation here: https://docs.ultralytics.com/yolov5/. If you have any further questions, feel free to ask!
