### ISSUE TITLE
last.pt epoch

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#10094]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

how to get the last.pt epoch?

**Comment by glenn-jocher** [comment]
last.pt pertains to the last epoch you trained. If it is not finalized it will contain an epoch number in the top level dict.
