### ISSUE TITLE
Val Batches 

### ISSUE THREAD

**Issue by myasser63** [ultralytics/yolov5#10097]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Validation

### Bug

I am using YOLOv5 on my custom dataset after training I only can find 2 batches of validation dataset when batch size is 16 knowing that I have 60 images for validation. When batch size is set to 1 and I ran the `--val `command I only find 3 images for the val run. 

`val: Scanning '/content/DataA/valid/labels.cache' images and labels... 60 found, 0 missing, 0 empty, 0 corrupt: 100% 60/60 [00:00<?, ?it/s]
`
`!python val.py --batch-size 1 --img 640 --data "/content/DataA/data.yaml" --weights '/content/best.pt'  --task val`
![image](https://user-images.githubusercontent.com/49511207/200784797-d43a77f8-dd64-4c24-a7cb-377cfc88c8ea.png)

### Environment

YOLOv5 🚀 v6.2-231-g0039870 Python-3.7.15 torch-1.12.1+cu113 CUDA:0 (Tesla T4, 15110MiB)
Google colab using T4 GPU

### Minimal Reproducible Example

`!python val.py --batch-size 1 --img 640 --data "data.yaml" --weights 'best.pt'  --task val`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@myasser63 only the first 3 batches are saved by default. You can save more batches here:
https://github.com/ultralytics/yolov5/blob/86decb3c49f91547975d7b7399290eb247888f6f/val.py#L265-L269
