### ISSUE TITLE
what is the pre processing time , and why it take much long time when using hub

### ISSUE THREAD

**Issue by VYRION-Ai** [ultralytics/yolov5#10109]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

i am sorry for my question .
what is the pre processing time , and why it take much long time when using hub, 
and can i reduce it 
![145574149-21855c8b-1ad8-49a0-b609-9e8a36d75a91](https://user-images.githubusercontent.com/23275255/200948983-b009ec3d-c0d5-4c31-82c2-756f176a1563.png)

**Comment by glenn-jocher** [comment]
@totoadel detect.py pre-processing times do not include image loading, i.e. the dataloader is separate, whereas the dataloader is built-in to pytorch hub models and they show the actual time to load the images.

**Comment by totoadel** [comment]
@glenn-jocher thank you

**Comment by glenn-jocher** [comment]
@VYRION-Ai you're welcome! If you have any more questions, feel free to ask. Your feedback is always appreciated.
