### ISSUE TITLE
ask for help！copy paste technique is implemented in bbox？

### ISSUE THREAD

**Issue by Mengyao-Zhang** [ultralytics/yolov5#10101]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Hello！
Since my dataset has no segment, I am going to implement copy-paste with bbox instead of segment.
how to modify copy_paste()？ thank you very much！
#7290 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@18846169373 copy-paste is only implemented for segment labels as box labels would copy and paste all the object background along with the object itself. If you'd like to modify then that is the correct code, but this is outside the scope of Ultralytics support, so perhaps you can get community help from other users.
