### ISSUE TITLE
I used the trained weights to verify that the COCO effect was poor

### ISSUE THREAD

**Issue by LUO77123** [ultralytics/yolov5#10105]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I used the small model in Version 6.1 of YOLOv5 to train the COCO dataset. After training, Map0.5 can reach 42.167%, but the effect is very poor when it is verified alone. Map0.5 is only 0.001. I don't know why. The following is the configuration file.
model:
![image](https://user-images.githubusercontent.com/87272337/200855773-b94e89c4-18da-44e5-9f3e-44fb0f05453d.png)
result:
![image](https://user-images.githubusercontent.com/87272337/200855989-faaf75ae-932a-48b9-8922-3f6b59551372.png)
val.py result
![image](https://user-images.githubusercontent.com/87272337/200856267-386e763b-110c-4d01-857a-27cb13050b77.png)
How can I make the individual verification consistent with the results given by the network training.

### Additional

How can I make the individual verification consistent with the results given by the network training.

**Comment by LUO77123** [comment]
> @LUO77123 you have environment problems, i.e. your torchvision is not meeting requirements. I'd address that first before anything else since torchvision supplies NMS.

Thank you for your reply, but I can achieve normal Map by using yolov5s.pt.
![image](https://user-images.githubusercontent.com/87272337/200858502-a08d7728-620a-4a04-812a-4f27bfa1a1f5.png)
torchvision have no problem, It is DCU environment.
![image](https://user-images.githubusercontent.com/87272337/200858893-155f364d-bafd-47d4-833e-45ea3f6cf313.png)

**Comment by glenn-jocher** [comment]
@LUO77123 hmm something strange is going on then. Maybe you selected the wrong checkpoint, or perhaps there's a CUDA issue. 

If you run your model against coco128.yaml with --device 0 and --device cpu do you get the same results? You should get a high mAP, i.e. 0.50 maybe. If CUDA is the issue then CPU will return high mAP but --device 0 no.
