### ISSUE TITLE
How to get the memory cost of YOLOv5s model or other models

### ISSUE THREAD

**Issue by XUMTJames** [ultralytics/yolov5#10115]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,I want to know that gpu_men in the picture is the memory cost of the model or the memory cost of the gpu？If it is not the memory cost of the model, how can I get it.

![p1](https://user-images.githubusercontent.com/94879687/201040836-ddb6a8f7-f356-4ddb-93bb-f9f22aa6f258.png)

**Comment by ExtReMLapin** [comment]
It's total gpu mem usage

**Comment by XUMTJames** [comment]
Thank you for your reply.But how can I get the memory cost of the model？

**Comment by JesusSilvaUtrera** [comment]
@XUMTJames I have the same question, I want to know how much memory is being used during my training (i'm training with cpu) to be able to set the limit resources that the training should have. If anybody knows, it would be helpful.

**Comment by glenn-jocher** [comment]
You can htop during training to see resource utilization if you are on linux.

**Comment by JesusSilvaUtrera** [comment]
@glenn-jocher I'm using macos to test it locally, can I also do that in mac? And how does it work? Sorry, I have never heard of htop

**Comment by glenn-jocher** [comment]
@JesusSilvaUtrera no I don't think htop is supported on macOS, you can use the Activity Monitor there instead:

<img width="1072" alt="Screenshot 2022-11-17 at 15 58 57" src="https://user-images.githubusercontent.com/26833433/202480629-7be4bcb4-95b3-49c5-abbe-d79990a63e66.png">

**Comment by JesusSilvaUtrera** [comment]
@glenn-jocher okay, I will do that, thank you for your reply!

**Comment by glenn-jocher** [comment]
@JesusSilvaUtrera you're welcome! If you have any more questions or need further assistance, feel free to ask. Good luck with your testing!
