### ISSUE TITLE
Train over the saved experiment weights?

### ISSUE THREAD

**Issue by phvpavankumar** [ultralytics/yolov5#10111]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have trained the yolov5 model with custom data and now I want to train these weights over a few more extra data, can someone please help me with this please?

What I have right now,
* A yolov5x trained weights on my custom data.
* What I need is I want to retrain or resume the same model using the best.pt weights.

**Comment by maja1001** [comment]
Hi @phvpavankumar
simply use the `best.pt ` weights in your next training session. For example:

`python train.py --img 640 --batch 16 --epochs 50 --cfg /path/to/model.yaml --data /path/to/data.yaml --weights /path/to/weights/best.pt --cache ram`
