### ISSUE TITLE
Ha ha ha! Please add Colossal AI to yolov5!

### ISSUE THREAD

**Issue by guohuanguohuan** [ultralytics/yolov5#10119]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Ha ha ha! Please add Colossal AI to yolov5! Thank you.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
What's Colossal AI?

**Comment by helloyizhengjun** [comment]
https://github.com/hpcaitech/ColossalAI
ColossalAI can accelerate the network more than 100 times.

**Comment by glenn-jocher** [comment]
@helloyizhengjun got it, thanks for the suggestion! We're always looking to improve YOLOv5 and appreciate your feedback. I'll share this with the team for consideration. If you have any other ideas or feedback, feel free to let us know. Thanks for reaching out!
