### ISSUE TITLE
Problems with deploying on Tinkerboard 2S

### ISSUE THREAD

**Issue by shubham190398** [ultralytics/yolov5#10117]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

I've recently tried to deploy a model on a Tinkerboard 2S. After doing the usual prerequisite installation and running detect, I run into an unexpected error. 
![image](https://user-images.githubusercontent.com/104817428/201046996-ec9cb7af-922e-4084-816e-13b21f12b452.png)
What could be causing this issue?

### Environment

OS: Debian 10
Device: ASUS Tinkerboard 2S

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@shubham190398 hi there! Thanks for reaching out. It looks like you're encountering an error when deploying on your ASUS Tinkerboard 2S. This issue could stem from various factors, including compatibility, configuration, or dependencies.

To better assist you, could you provide the specific steps you followed before encountering the error? Additionally, sharing the command you used to run the detect, plus any relevant logs, would help us pinpoint the issue more accurately.

Your contribution in submitting a PR is much appreciated! We're committed to ensuring a seamless YOLOv5 experience across various devices. Let's work together to resolve this.
