### ISSUE TITLE
F1 Scores in result.txt

### ISSUE THREAD

**Issue by jerryWTMH** [ultralytics/yolov5#1011]
## ❔Question
Hi, I'm new to object detection and yolov5 and I very much appreciate your amazing work.
I used the yolov5x to train my model. However, I found that the F1 scores in result.txt were a little bit weird.
And It looks like this(I just select 1 epoch as an example):

299/299     7.78G  0.006219  0.002016 0.0001303  0.008365        34       640    **0.8074    0.8779    0.8698    0.5825**    0.0165   0.00466  0.001658

I know that the value in result.txt respectively represents :
Precision | Recall | mAP | F1 | test_loss(GIoU) | test_loss(obj) | test_loss(cls)
And the general.py shows that the formula of F1 is : f1 = 2 * p * r / (p + r + 1e-16).
Therefore, I think the F1 score should be like (2 * 0.8074 * 0.8779) / (0.8074 + 0.8779 + 1e-16) = 0.8411 (not 0.5825)
I am wondering whether I'm wrong or not?
Thank you very much!

**Comment by glenn-jocher** [comment]
F1 scores are not contained anywhere in results.txt. The metrics saved are the same metrics printed to screen during training at the end of each epoch.

**Comment by jerryWTMH** [comment]
> F1 scores are not contained anywhere in results.txt. The metrics saved are the same metrics printed to screen during training at the end of each epoch.

Thank you very much!
Sorry, I asked a stupid question.
