### ISSUE TITLE
Mosaic9

### ISSUE THREAD

**Issue by myasser63** [ultralytics/yolov5#10116]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to activate mosaic9 instead of mosaic4. I have replaced `load_mosaic` to `load_mosaic9` in `get_item` function in `dataloader.py` but still getting mosaic4. How can I use mosaic9?

I also want to use cutout from `augementations.py` how to activate it?

**Comment by glenn-jocher** [comment]
@myasser63 you do just as you said, replace load_mosaic() with load_mosaic9() in dataloaders.py, nothing else needed.
