### ISSUE TITLE
YOLO models on object classification datasets

### ISSUE THREAD

**Issue by marko-polo-cheno** [ultralytics/yolov5#10114]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi there :)
Thanks for providing an amazing repo + community.

How might YOLO models behave in terms of getting bounding boxes if it was trained on a dataset where each image was a single class and the "bounding box" is the whole image? Are there any issues with that?

The reason I ask is because certain kaggle datasets do not have bounding boxes given, but do have subjectively tight images that are okay bounding boxes themselves.

Thanks in advance for your insight.

**Comment by marko-polo-cheno** [comment]
> Then, your task is image classification, not object detection. And there are yolo classification models for that https://github.com/ultralytics/yolov5/tree/master/classify

Sorry, I might not have expressed what I had intended to express - or I am too noob to understand if there is a trivial issue.
What I mean is, using a classification dataset, with bounding boxes being entire images, could I make an object detector?
ie every row in the files will be [<class> 0.5 0.5 1.0 1.0]

**Comment by glenn-jocher** [comment]
@marko-polo-cheno hi there,

Thanks for reaching out and for your kind words! 🙏

If your dataset consists of single-class images with the bounding box encompassing the entire image, you can still utilize YOLOv5 for object detection. Simply set up your data with a single class and the bounding box coordinates corresponding to the entire image. YOLOv5 will still be able to train on and infer bounding boxes effectively, assuming the aspect ratio of your bounding box is consistent with the network's requirements.

Feel free to refer to the official YOLOv5 documentation for further details and comprehensive information on how to structure your data accordingly. If you have any more questions or need assistance, the community and I are here to help! 🚀
