### ISSUE TITLE
Test images Detected issue 

### ISSUE THREAD

**Issue by Swimlim** [ultralytics/yolov5#10126]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

![image](https://user-images.githubusercontent.com/105340288/201292462-d9524f20-e52b-482f-891b-c7ff186e69fc.png)
When tested with the full image, only one type was detected, but when tested partially, both types were detected. What's the reason?

### Additional

![image](https://user-images.githubusercontent.com/105340288/201292797-7b9abc4d-6a66-43f2-8e50-db1d4118885c.png)

**Comment by glenn-jocher** [comment]
@Swimlim different resolutions? Also see --max-det argument in detect.py:
https://github.com/ultralytics/yolov5/blob/f33718f36f756301b91da6207f1d02f30b3916e1/detect.py#L224
