### ISSUE TITLE
How to replace the Concat module with the appropriate to sum 

### ISSUE THREAD

**Issue by Cicc1** [ultralytics/yolov5#10129]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi! How is it possible to sum two layers instead of using the concatenation module? I would substitute the module Concat contained in the head of the file. YAML with a module to actually sum the same layers. Thank you!

**Comment by glenn-jocher** [comment]
@Cicc1 yes of course. You can modify virtually all parts of the model. Summation results in smaller and faster models which are less accurate.

**Comment by glenn-jocher** [comment]
@Cicc1 oh you may need to replace it strategically to be careful about modules expecting certain input sizes. You can also modify it instead inside modules like inside C3 which will probably have a bigger impact model-wide.
