### ISSUE TITLE
ModuleNotFoundError: No module named 'models' error, after running in ROS2 node

### ISSUE THREAD

**Issue by tgrmev** [ultralytics/yolov5#10121]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I am working with YOLOV5 and trained model from Colab and downloaded the best.pt file to run on my local. I run the simple code that you can see below, with **python3** and **ros2 run** commands seperately. It runs correctly with python3 <FileName> but it does not work with ros2 run <FileName>. What is the problem? To remind, when it is run in both case, the direction of the best.pt is the same.
```

import torch
import torch.nn as nn
import os
import subprocess
import sys

print(os.getcwd())
os.chdir("./")
print(os.getcwd())

print(torch.load('./best.pt'))
model = torch.load('./best.pt') 

```

>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/mev/dev_ws/install/cv_basics/lib/python3.8/site-packages/cv_basics/webcam_sub_YOLOV7.py", line 12, in <module>
    print(torch.load('./best.pt'))
  File "/home/mev/.local/lib/python3.8/site-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/mev/.local/lib/python3.8/site-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/home/mev/.local/lib/python3.8/site-packages/torch/serialization.py", line 1124, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'models'

**Comment by hcdiekmann** [comment]
I am getting the same error. Have you found a solution to this? @tgrmev

**Comment by LeeeSe** [comment]
same error

**Comment by tgrmev** [comment]
You should call your model with this line: 
`self.model = torch.hub.load("./yolov5", 'custom', path="./yolov5/best.pt", source='local') `

**Comment by glenn-jocher** [comment]
@arkdaniel, thank you for the suggestion.

@tgrmev, try loading the YOLOv5 model using the `torch.hub.load()` function like this:

```python
import torch

model = torch.hub.load("./yolov5", 'custom', path="./yolov5/best.pt", source='local')

print(model)
```

This should load your trained `best.pt` model using the correct relative path from the `./yolov5` directory instead of just referencing it directly. Let me know if this works for you!
