### ISSUE TITLE
Is it possible to put other types of data into the model?

### ISSUE THREAD

**Issue by administer03** [ultralytics/yolov5#10128]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I would like to add numeric data to YOLO in a fully connected (flattened) process, is it possible to do?

**Comment by bdytx5** [comment]
Probably would want to concat this with one of the hidden state vectors of the model.

**Comment by administer03** [comment]
> Probably would want to concat this with one of the hidden state vectors of the model.

Great! So, Do you have any examples or tutorials to follow those things?

**Comment by administer03** [comment]
ok, thanks you for advising.

**Comment by glenn-jocher** [comment]
@administer03 you're welcome! If you have any other questions or need further assistance, feel free to ask. We're here to help!
