### ISSUE TITLE
Feature thought, read from zipfile as a filesystem, with regex pattern support

### ISSUE THREAD

**Issue by apiszcz** [ultralytics/yolov5#10127]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Managing and moving files to inference can be tedious due to the number of I/O's needed top move/copy files. Has anyone considered reading from a zip file for inference, regex search support would be useful in this case.
(perhaps https://docs.pyfilesystem.org/en/latest/reference/zipfs.html)

* Thank you for adding --vid-stride!

### Use case

Use in place of a directory to scan for input inferencing.

### Additional

https://docs.pyfilesystem.org/en/latest/reference/zipfs.html

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@apiszcz I'm not super experienced in zip, but we use ZipFile to scan zip contents, and you can unzip item-by-item based on a search. There's an example here:
https://github.com/ultralytics/yolov5/blob/f33718f36f756301b91da6207f1d02f30b3916e1/utils/general.py#L574-L582
