### ISSUE TITLE
YOLO format

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#1013]
## ❔Question
Do you have the method that convert the COCO format to  the YOLO format?

**Comment by glenn-jocher** [comment]
See https://github.com/ultralytics/JSON2YOLO

**Comment by alicera** [comment]
Thanks you .
How to produce the images path of the train2017.txt in the coco2017labels.zip？

**Comment by alicera** [comment]
how about the relation position for image—path.txt  ,  image—info.txt and images file


WARNING: No labels found in /dataset/JPEGImages/. See https://docs.ultralytics.com/yolov5/tutorials/train_custom_data
Traceback (most recent call last):
  File "train.py", line 456, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 169, in train
    rank=rank, world_size=opt.world_size, workers=opt.workers)
  File "/work/YOLOv5/yolov5/utils/datasets.py", line 61, in create_dataloader
    rank=rank)
