### ISSUE TITLE
Model training not considering one of the classes

### ISSUE THREAD

**Issue by AnshKetchum** [ultralytics/yolov5#10136]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

Our dataset consists of three classes - head, helmet, and person. 

We ran `train.py` and were able successfully train a model. But the training report (screenshot attached below) only lists results for two of the classes - the last class, person, was not being displayed at all.

![Screen Shot 2022-11-12 at 1 04 10 AM](https://user-images.githubusercontent.com/26364616/201467120-553bea89-32c3-4836-bb24-a98f3426d961.png)
]

We checked the confusion matrix (attached below) to see if there was further evidence - and we noticed that the person was there, but completely blank. There are multiple images with this label in the dataset, but it looks like none of them are being considered.  

![confusion_matrix](https://user-images.githubusercontent.com/26364616/201467366-19f955e9-e851-462f-aa66-c61ca15c655a.png)

For reference, we are also attaching the contents of our data.yaml file

```
names:
  0: head
  1: helmet
  2: person
train: raw_dataset/train/images
val: raw_dataset/valid/images
```

### Environment

- Python 3.8.13
- Latest version of Yolo (as of publishing this post, Nov 11th) 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@AnshKetchum your validation set contains zero instances of the class you are asking about.

With zero instances of the class in your validation set there's naturally no metrics that can be computed.

**Comment by AnshKetchum** [comment]
Can confirm that this happened, thanks a lot! I've updated my datasets and now am able to see the last class!

**Comment by glenn-jocher** [comment]
@AnshKetchum glad to hear that updating your datasets resolved the issue! If you have any further questions or need assistance, feel free to ask!
