### ISSUE TITLE
how to deploy the top1 and top5 in yolov5 5.0

### ISSUE THREAD

**Issue by yuan-kai-design** [ultralytics/yolov5#10130]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am using yolov5 5.0,I want to depoly top1 and top5 in yolov5 5.0,but I don't kown how to do it

**Comment by glenn-jocher** [comment]
@yuan-kai-design top1 and top5 accuracy are used by default when training classification models with master. See classify/train.py
