### ISSUE TITLE
How to handle data drift?

### ISSUE THREAD

**Issue by pathikg** [ultralytics/yolov5#10138]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Sometime back I trained a yolov5x6 model on images of documents to detect some portions in the documents e.g. detecting the "company name". It was working fine in the production but now there seems to be a small [data drift](https://en.wikipedia.org/wiki/Drift_(data_science)) in some of the data i.e. classes which model is detecting are the same but there's a change in the positioning of the interested regions as compared to the data present in train set on which the model was trained. 
e.g. company name was present in top left corner in train set but now I am receiving some documents having company name on right side or somewhere else in the documents.

I was wondering if there's any way through which I can finetune the model on this new data without forgetting previous data? since the documents that are similar to train data are still encountered by the model

I read some similar issues but they were focused on adding new classes for detection whereas in my case, classes are same but the positioning of the objects has changed.

**Comment by glenn-jocher** [comment]
@pathikg yes of course. Production models should not be static but should continuously be retrained with edge cases and underperming regions of the image space as in our graphic below. You simply add new labelled images to your dataset and retrain, starting from your existing model:
```
python train.py --data DATA.yaml --weights previous_best.pt
```

![integrations-loop](https://user-images.githubusercontent.com/26833433/201474575-ed9d92f8-0608-4695-b4b3-2aea02e7d526.png)

**Comment by pathikg** [comment]
Thanks for the response @glenn-jocher 
Will try out the same :)

**Comment by glenn-jocher** [comment]
You're welcome, @pathikg! 👍 If you have any other questions or run into any issues, feel free to ask. Good luck with the finetuning!
