### ISSUE TITLE
Is it possible to get hidden layers predictions with Python API?

### ISSUE THREAD

**Issue by victorsevero** [ultralytics/yolov5#10135]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm currently loading yolov5 with Pytorch Hub and I'd also like to get data from (some) hidden states when doing a prediction. Would that be possible? For clarification, this is the way I'm loading the pre-trained model:

```python
yolo = torch.hub.load(
    repo_or_dir="ultralytics/yolov5",
    model="yolov5x",
    pretrained=True,
)
# im: PIL.Image
detections = yolo(im)
```

Thanks in advance!

**Comment by glenn-jocher** [comment]
@victorsevero what data exactly are you looking for?

**Comment by victorsevero** [comment]
> @victorsevero what data exactly are you looking for?

neurons outputs (values after their activation functions) for a single prediction

**Comment by glenn-jocher** [comment]
@victorsevero hmm ok. You could do this perhaps by adding some hooks or manually modifying the model/modules you are interested in, but by default this is not available.

**Comment by victorsevero** [comment]
@glenn-jocher right, thanks for your response!

**Comment by glenn-jocher** [comment]
@victorsevero you're welcome! If you have any more questions, feel free to ask.
