### ISSUE TITLE
100 epoch get better?

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#10148]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

https://github.com/ultralytics/yolov5/pull/10024

why does the default epoch set 100 ?

**Comment by glenn-jocher** [comment]
@alicera it seems like for the most common use case (starting custom datasets from COCO-pretrained weights) 100 epochs may be enough to get started. README results on COCO are still trained to 300 epochs though.

**Comment by alicera** [comment]
Do you have the method to check it overfitting ?

**Comment by glenn-jocher** [comment]
@alicera overfitting just means your validation losses are increasing. You can observe this manually by looking at results.png val curves.
