### ISSUE TITLE
Questions about inference time?

### ISSUE THREAD

**Issue by marziyemahmoudifar** [ultralytics/yolov5#10144]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I used yolov5s.yaml configuration for two experiments where only the dataset is different, although the number of layers, parameters and GFLOPs are the same in both experiments, but the inference time in the evaluation phase is very different. What is the reason for this difference?

**Comment by glenn-jocher** [comment]
@marziyemahmoudifar if GFLOPs are identical then class counts should also be identical, leading to identical inference times. If you have a reproducible example of identical models showing different inference times please help us to reproduce it so we can get started debugging it. If we can't reproduce there is no action for us to take.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by marziyemahmoudifar** [comment]
> @glenn-jocher  if GFLOPs are identical then class counts should also be identical, leading to identical inference times. If you have a reproducible example of identical models showing different inference times please help us to reproduce it so we can get started debugging it. If we can't reproduce there is no action for us to take.
> 
> ## How to create a Minimal, Reproducible Example
> When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:
> 
> * ✅ **Minimal** – Use as little code as possible to produce the problem
> * ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
> * ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem
> 
> For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:
> 
> * ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
> * ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.
> 
> If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem.
> 
> Thank you! 😃

Yes, Flops, the number of classes and models used on all three datasets is the same, but the inference time is different in all three experiments, and this difference is huge. I have included the test section of these three tests below.
The result of the first test:
python val.py --task test --data test.yaml --weights runs/train/exp/weights/[best.pt](http://best.pt/)
val: data=test.yaml, weights=['runs/train/exp/weights/[best.pt](http://best.pt/)'], batch_size=8, imgsz=640, conf_thres=0.001, iou_thres=0.6, task=test, device=, workers=8, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=runs/val, name=exp, exist_ok=False, half=False, dnn=False
YOLOv5 🚀 v6.1-207-g5774a151 Python-3.8.10 torch-1.9.0+cu111 CUDA:0 (NVIDIA GeForce RTX 3090, 24268MiB)

Fusing layers...
YOLOv5s summary: 213 layers, 7012822 parameters, 0 gradients, 15.8 GFLOPs
test: Scanning '/home/gadmin/Desktop/MarziyeMahmoudifar/yolov5_1/Kf/test/labels.
               Class     Images     Labels          P          R     mAP@.5 mAP@
                 all         97       1326      0.892      0.841      0.926      0.623
Speed: 0.1ms pre-process, 2.4ms inference, 1.2ms NMS per image at shape (8, 3, 640, 640)
Results saved to runs/val/exp2
The result of the second test:
python val.py --task test --data test.yaml --weights runs/train/exp/weights/[best.pt](http://best.pt/)
val: data=test.yaml, weights=['runs/train/exp/weights/[best.pt](http://best.pt/)'], batch_size=8, imgsz=640, conf_thres=0.001, iou_thres=0.6, task=test, device=, workers=8, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=runs/val, name=exp, exist_ok=False, half=False, dnn=False
YOLOv5 🚀 v6.1-207-g5774a151 Python-3.8.10 torch-1.9.0+cu111 CUDA:0 (NVIDIA GeForce RTX 3090, 24268MiB)

Fusing layers...
YOLOv5s summary: 213 layers, 7012822 parameters, 0 gradients, 15.8 GFLOPs
test: Scanning '/home/gadmin/Desktop/MarziyeMahmoudifar/yolov5_1/MA/test/labels.
               Class     Images     Labels          P          R     mAP@.5 mAP@
                 all         66        901      0.604      0.216      0.435       0.21
Speed: 0.5ms pre-process, 38.5ms inference, 9.2ms NMS per image at shape (8, 3, 640, 640)
Results saved to runs/val/exp3
The result of the third test:
python val.py --task test --data test.yaml --weights runs/train/exp/weights/[best.pt](http://best.pt/)
val: data=test.yaml, weights=['runs/train/exp/weights/[best.pt](http://best.pt/)'], batch_size=8, imgsz=640, conf_thres=0.001, iou_thres=0.6, task=test, device=, workers=8, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=runs/val, name=exp, exist_ok=False, half=False, dnn=False
YOLOv5 🚀 v6.1-207-g5774a151 Python-3.8.10 torch-1.9.0+cu111 CUDA:0 (NVIDIA GeForce RTX 3090, 24268MiB)

Fusing layers...
YOLOv5s summary: 213 layers, 7012822 parameters, 0 gradients, 15.8 GFLOPs
test: Scanning '/home/gadmin/Desktop/MarziyeMahmoudifar/yolov5_1/Ac/test/labels.
               Class     Images     Labels          P          R     mAP@.5 mAP@
                 all        112        260      0.663       0.25      0.348      0.166
Speed: 1.2ms pre-process, 14.6ms inference, 1.0ms NMS per image at shape (8, 3, 640, 640)
Results saved to runs/val/exp4

**Comment by marziyemahmoudifar** [comment]
> @glenn-jocher  if GFLOPs are identical then class counts should also be identical, leading to identical inference times. If you have a reproducible example of identical models showing different inference times please help us to reproduce it so we can get started debugging it. If we can't reproduce there is no action for us to take.
> 
> ## How to create a Minimal, Reproducible Example
> When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:
> 
> * ✅ **Minimal** – Use as little code as possible to produce the problem
> * ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
> * ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem
> 
> For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:
> 
> * ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
> * ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.
> 
> If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem.
> 
> Thank you! 😃

I changed plots=True in line 124 in val.py to False, then inference time was the same. I guess the time to plot the results in the output folder is added to the inference time.

**Comment by glenn-jocher** [comment]
Great observation, @marziyemahmoudifar! The difference in inference times you observed is likely due to the additional time required for plotting the results in the output folder when `plots=True`. By setting `plots=False`, the time spent on plotting is eliminated, resulting in consistent inference times across your experiments. Thank you for bringing this to our attention! If you have any further questions or need assistance with anything else, feel free to ask. 😊
