### ISSUE TITLE
About the inconsistency of the data set test output results in the val.py file of yolov5

### ISSUE THREAD

**Issue by zidaman** [ultralytics/yolov5#10140]
> @zidaman yes that is correct. mAP is the area under the PR curve. To fully evaluate the curve and get a valid mAP you must set --conf near zero.

However, when I set conf=0.2 for verification, its mAP value changed compared with that when conf=0.001, while P and R values were the same as those when conf=0.001. In theory, mAP is the area under PR curve, shouldn't it not change? As this link: https://github.com/ultralytics/yolov3/issues/898, in theory should be P and R value needs to change now, but my experimental results on the contrary, is this why?
![image](https://user-images.githubusercontent.com/89052697/202060273-1b8dbfa1-c96c-40da-bd9c-2acc6fec595a.png)

**Comment by glenn-jocher** [comment]
@zidaman yes that is correct. mAP is the area under the PR curve. To fully evaluate the curve and get a valid mAP you must set --conf near zero.

**Comment by zidaman** [comment]
However, when I set conf=0.2 for verification, its mAP value changed compared with that when conf=0.001, while P and R values were the same as those when conf=0.001. In theory, mAP is the area under PR curve, shouldn't it not change? As this link: https://github.com/ultralytics/yolov3/issues/898, in theory should be P and R value needs to change now, but my experimental results on the contrary, is this why?
![image](https://user-images.githubusercontent.com/89052697/202060465-e93b0d51-dad3-4f0b-9388-b2be88f08295.png)

**Comment by glenn-jocher** [comment]
@zidaman usage of any confidence threshold above 0.001 is invalid as val.py already shows you in the console:
https://github.com/ultralytics/yolov5/blob/e40662ffdd80a6f108a62cf0d53d06085d943223/val.py#L375-L376
