### ISSUE TITLE
Strange output after custom model export

### ISSUE THREAD

**Issue by drachu** [ultralytics/yolov5#10143]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I trained yolov5s on custom dataset. When using pt model everything is fine and output is good as expected.
When I am using let's say exported quantized tflite model all boxes predictions part seems reasonably but class and confidence not really.

pt model output put on image
![obraz_2022-11-13_165749461](https://user-images.githubusercontent.com/95628848/201531255-99d8bf69-2aab-48a4-8ea9-b55d7922066c.png)

How export went:
`!python export.py --weights /kaggle/working/base/kaist_camel_own_v5.pt --include edgetpu --img-size 384 512 --int8`
kaggle notebook: [https://www.kaggle.com/code/adamdradrach/yolov5](url)
TensorFlow Lite: export success ✅ 133.1s, saved as /kaggle/working/base/kaist_camel_own_v5-int8.tflite (7.0 MB)

tflite output input details
INPUT
`[{'name': 'serving_default_input_1:0', 'index': 0, 'shape': array([  1, 384, 512,   3], dtype=int32), 'shape_signature': array([  1, 384, 512,   3], dtype=int32), 'dtype': <class 'numpy.uint8'>, 'quantization': (0.003921568859368563, 0), 'quantization_parameters': {'scales': array([0.00392157], dtype=float32), 'zero_points': array([0], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]`
OUTPUT
`[{'name': 'StatefulPartitionedCall:0', 'index': 408, 'shape': array([    1, 12096,     6], dtype=int32), 'shape_signature': array([    1, 12096,     6], dtype=int32), 'dtype': <class 'numpy.uint8'>, 'quantization': (0.003986298572272062, 3), 'quantization_parameters': {'scales': array([0.0039863], dtype=float32), 'zero_points': array([3], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]`

part of invoked tensor output on the same image as show above
`[220   7  10  15   3 253]
[224   7   9  15   3 253]
[224   8  11  15   3 253]
[224   7  10  15   3 253]
[229   7   9  15   3 253]
[229   7  11  15   3 253]
[229   7  10  15   3 253]
[232   7   9  14   3 253]
[232   7  11  15   3 253]
[233   7  10  15   3 253]
[236   7   9  14   3 253]
[236   7  11  15   3 253]
[237   7  10  15   3 253]
[240   7  10  11   3 253]
[240   7  11  12   3 253]
[240   7  13  12   3 253]
[243   6  11  11   3 253]
[243   7  13  12   3 253]`

In all outputs first four values I assume are box coordinates and these are changing what is all right I think. But last two values - class and confidence - "3" is a little suprising because I have only one class named 'pedestrian' and I thought that value will be "0" or "1". Now with that "253". If thats confidence its all the same in all outputs. I don't think that's how it is supposed to be. Am I doing something wrong?

Models used:
[custom_dataset_models.zip](https://github.com/ultralytics/yolov5/files/9997734/custom_dataset_models.zip)

**Comment by drachu** [comment]
Sorry for trouble... I figured it out - i missed all of nms part and wrongy preprocess image before detection - my fault... Thanks anyway for such a great tool!

**Comment by mhaghighat** [comment]
> Sorry for trouble... I figured it out - i missed all of nms part and wrongy preprocess image before detection - my fault... Thanks anyway for such a great tool!

@drachu Can you please share what you did here and how you interpreted the invoked tensor output to get the boxes, classes and scores? Thanks!

**Comment by drachu** [comment]
@mhaghighat Sure! [Here](https://github.com/drachu/rec_app/blob/processes/DetectionEdgeTPU.py) is my code which I used. Hope it helps!
