### ISSUE TITLE
Combine these two images into a six-channel graph as a sample training

### ISSUE THREAD

**Issue by Allen-Sheard** [ultralytics/yolov5#10147]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I am a sophomore who has just started deep learning and python, and I am completing the first big assignment assigned by the teacher, how to read two 3-channel pictures consecutively from the dataset and merge them into one 6-channel picture as a training sample? How to modify the dataloader?
![image](https://user-images.githubusercontent.com/56833292/201624292-f7c667db-f7f5-4c4b-baac-dd3c432d304f.png)
Combining these two images into a six-channel graph as a sample training, how do I modify my code?

**Comment by glenn-jocher** [comment]
@Allen-Sheard just stack these in the channel dimension, i.e. `np.concatenate((im1, im2), axis=2)`
