### ISSUE TITLE
torch.hub for classification models

### ISSUE THREAD

**Issue by isspid** [ultralytics/yolov5#10151]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have loaded a classification model in a Python script using torch.hub.load() and after transforming the image in a (BCHW) shape I ran it through the model receiving "tensor([[ 2.96037, -2.68692]], device='cuda:0')" as an output. This is a classifying model so I wanted to know if we are supposed to run this result through a softmax activation function ourselves or am I doing something wrong and probabilities can be retrieved by calling a function on the result.

Thanks a lot for your effort.

**Comment by isspid** [comment]
Thank you.

**Comment by glenn-jocher** [comment]
@isspid you're welcome! If you have any other questions, feel free to ask. Keep up the good work!
