### ISSUE TITLE
new 6.3 version release

### ISSUE THREAD

**Issue by gabides** [ultralytics/yolov5#10154]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, when do you plan to release a new version?
We are using the latest tag from docker hub but the latest keeps changing on every commit. It would be helpful if you could release a new stable version because we are using several new useful features that were added after 6.2, so we can't fix the yolov5 image to 6.2 but we would still want to have a reproducible build.

The 6.2 release note mentions a 6.3 release in September (https://github.com/ultralytics/yolov5/releases/tag/v6.2), is that coming soon? :)

Thanks a lot!

**Comment by Denizzje** [comment]
https://github.com/ultralytics/yolov5/issues/10020

It seems 6.3 will be skipped in favour of a full 7.0 release, and by the looks of it shall be a nice upgrade from the 6.1 we have been on for the same reason ;).

**Comment by gabides** [comment]
@Denizzje thanks for the quick reply, I hadn't seen issue 10020!

do you have any timeline on 7.0 release?

**Comment by glenn-jocher** [comment]
@gabides @Denizzje release v7.0 with segmentation support scheduled for Tuesday 22 November 2022.
