### ISSUE TITLE
Tensor shape of the model output

### ISSUE THREAD

**Issue by sclc713** [ultralytics/yolov5#1015]
## ❔Question
Hello, 
I am trying to convert a pytorch model to onnx format. After the conversion, I found that the tensor shape of the model output (prediction) was [1,25200,17]. However, I also found that the shape of output tensor (prediction) was [1, 15120, 17], when I printed out the shape of pred variable in detect.py. Since 25200!=15120, I am wondering if the conversion has somehow failed ? 

Does anyone know why this is happening?

Thanks

## Additional context
I trained the model with a customed dataset, and started from using parameters in yolov5x. And I didn't use "--augment" when I called detect.py.

**Comment by glenn-jocher** [comment]
@CharLi713 output sizes are determined by your input size, thus there is no 'correct' output shape.

Also note the 3 output layers (of different strides and sizes each) are concatenated into a single output during inference.

**Comment by sclc713** [comment]
@glenn-jocher, thanks for the answer. I got it. The image size in export.py is 640x640, while it is 384x640 in the case of detect.py. Therefore, the shape of outputs are [1, 25200, 17] and [1, 15120, 17].

I have a furture question. When using export.py to convert the pytorch model to the onnx format model, the input image size is explicitly decided in export.py, for instance 640x640. Does it mean I have to feed the model with inputs of image sizes of 640x640, when I try to use the converted onnx model to do the inference ? Will the inference fail if I feed the onnx model with inputs of image sizes of 384x640.

**Comment by glenn-jocher** [comment]
@CharLi713 yes, models are exported with fixed input sizes.

**Comment by sclc713** [comment]
@glenn-jocher, I got it. Thank you very much !

**Comment by Svetlana-art** [comment]
Hi, my input image shape is (16, 3, 512, 512) my output image shape is (torch.Size([16, 16128, 85]). I use only one class for detection. Please help me to understand how can I interpreted my output shape?

**Comment by glenn-jocher** [comment]
@Svetlana-art see https://github.com/ultralytics/yolov5/issues/1277#issuecomment-810458576
