### ISSUE TITLE
Training YOLOv5 on portion of COCO database

### ISSUE THREAD

**Issue by Syrupy22** [ultralytics/yolov5#10169]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How do we train YOLOv5 on certain sections of the COCO datasets?
I want to find out about how to only do inference on Humans, Suitcases, Handbags and Backpacks, and ignore other objects
Do I have to find myself a custom dataset, or is there a way to train it based of the COCO datasets?
Is there a way maybe to configure test.py and val.py to do so? 
If possible, I would also like to be able to just label Suitcases Handbags and Backpacks as under the same class of "Bag"

**Comment by Syrupy22** [comment]
Alternatively, how to we filter the specific classes such that only the bounding boxes of a few select classes are written onto the output

**Comment by glenn-jocher** [comment]
@Syrupy22 you can filter dataset labels to only include classes you are interested in using the YOLOv5 dataloader here, but this will not remove images that don't contain those classes. To train on only persons, bicycles and cars for example you would put `include_class=[0, 1, 2]`
https://github.com/ultralytics/yolov5/blob/e40662ffdd80a6f108a62cf0d53d06085d943223/utils/dataloaders.py#L530


@kalenmike @AyushExel this is an example use-case we'd like to support with single-image saving in HUB datasets. Rather than train all COCO, we select the classes we are interested in, then only download images containing those classes. Even more advanced would be combining datasets like this, i.e. train COCO and VOC on persons and cars classes, though this opens risk if the dataset classes are not all in common.

**Comment by Syrupy22** [comment]
@glenn-jocher how do I update the model after changing the include_class list? I tried retraining the model on coco128.yaml but after testing the detect.py afterwards I still see labels that are not inside the include_class list?

**Comment by Syrupy22** [comment]
I found somewhat of a work around for what I was doing, although I am met with another error.
For context, what I was trying to achieve was a detection system for unattended bags, with the loose definition of the center of the bag being about 3x the width of the bag away from all people.

By slightly tweaking the code for the "#Write results" section in detect.py, it should be able to form a list for unattended bags

                people = []
                bags = []
                for i in reversed(det):
                    if i[-1] == 0: 
                        people.append(i)
                    elif i[-1] == 24 or i[-1] == 26 or i[-1] == 28:
                        bags.append(i)
                for *xyxy, conf, cls in bags:
                    xywh = (xyxy2xywh(torch.tensor(xyxy).view(1, 4)) / gn).view(-1).tolist()  # normalized xywh
                    unattended = True
                    for *xyxy2, conf2, cls2 in people:
                        xywh2 = (xyxy2xywh(torch.tensor(xyxy2).view(1, 4)) / gn).view(-1).tolist()  # normalized xywh
                        D = dist.euclidean((xywh[0], xywh[1]), (xywh2[0], xywh2[1]))
                        if D < (3 * xywh[2]):
                            unattended = False
                            break
                        
                
                    if unattended:
                        if save_txt:  # Write to file   
                            line = (cls, *xywh, conf) if save_conf else (cls, *xywh)  # label format
                            with open(f'{txt_path}.txt', 'a') as f:
                                f.write(('%g ' * len(line)).rstrip() % line + '\n')

                        if save_img or save_crop or view_img:  # Add bbox to image
                            c = int(cls)  # integer class
                            label = "Unattended"
                            annotator.box_label(xyxy, label, color="Red")
                        if save_crop:
                            save_one_box(xyxy, imc, file=save_dir / 'crops' / names[c] / f'{p.stem}.jpg', BGR=True)


However, I seem to be getting an error when actually runnning the code


Fusing layers...
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients
Traceback (most recent call last):
  File "D:\YOLOv5\yolov5-master\detect1.py", line 277, in <module>
    main(opt)
  File "D:\YOLOv5\yolov5-master\detect1.py", line 272, in main
    run(**vars(opt))
  File "C:\.....\Python\Python310\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\YOLOv5\yolov5-master\detect1.py", line 208, in run
    if vid_path[i] != save_path:  # new video
TypeError: only integer tensors of a single element can be converted to an index


I don't quite understand how to fix the problem, but it may also have arised from when i was trying to tweak around with the "save_txt" variable because i wasnt sure of the format of the det array

**Comment by Syrupy22** [comment]
Oh I missed out that i used:
pip install imutils
and added "import imutils" at the front of the code

I am currently testing in on a video with the ".avi" extension
And another possibility is that xywh[i] doesnt work due to something related to tensors?

**Comment by Syrupy22** [comment]
I found the issue is that I used the variable i in the for loop, and also i needed to edit the code because i was under the impression that det was an array and not tensors

**Comment by glenn-jocher** [comment]
@Syrupy22 Great to hear you found the issue! 🎉 It's important to ensure that the variable names used in your loops don't conflict with any existing variables. Regarding the tensors, you may need to convert them to numpy arrays before performing operations that may not be supported directly on tensors. Additionally, be cautious when adjusting the code for the det variable, as it contains the detections and it's crucial to handle it properly for the code to function as expected. Let me know if you need any further assistance!
