### ISSUE TITLE
I want to add attention mechanism

### ISSUE THREAD

**Issue by angel-yi** [ultralytics/yolov5#10167]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Can the classification model be extracted separately? I want to add attention mechanism

**Comment by glenn-jocher** [comment]
@angel-yi 👋 Hello! Thanks for asking about **downloading weights**. YOLOv5 🚀 official weights are available to download 3 ways:

## Download Script

Run bash script: `python data\download_weights.sh`

## Release Asssets

Download weights manually from the latest release assets at https://github.com/ultralytics/yolov5/releases
<img width="1047" alt="Screen Shot 2022-07-08 at 12 52 48 PM" src="https://user-images.githubusercontent.com/26833433/177978806-adc3dfd1-5ec2-473c-aaea-bbe29c08841b.png">

## Ultralytics HUB

Download weights in any format from Ultralytics HUB (https://hub.ultralytics.com)
<img width="1277" alt="Screen Shot 2022-07-08 at 12 55 05 PM" src="https://user-images.githubusercontent.com/26833433/177979124-cc4bffc4-6dea-43d2-97b8-5f7742c98eb0.png">

Good luck 🍀 and let us know if you have any other questions!
