### ISSUE TITLE
How do train and export the custom model suitable for Object Detection Pytorch App ?

### ISSUE THREAD

**Issue by aravinthk00** [ultralytics/yolov5#10168]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

**I am working on [android-demo-apps](https://github.com/pytorch/android-demo-app)/ObjectDetection/). I follow given steps only to train and export pt to ptl, after I get [best.torchscript.ptl](https://drive.google.com/file/d/1-0DShA5DI2nfopDq18Tuo8Pazms-UZqf/view?usp=share_link) but import in android app facing issue on model version above mentioned, then model version issue resolve refer that  [solution](https://github.com/pytorch/android-demo-app/issues), till now I am struggling in error so please give step by step instruction about that how to train and export the custom compatible model for Object Detection Pytorch App. It is very important to my career.

 I can't get idea about that, anyone assist me, please give me clear solution ... 

### Environment

- YOLOv5 🚀 v6.2-240-gabbfd69 Python-3.7.15 torch-1.12.1+cu113 CUDA:0 (Tesla T4, 15110MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 22.6/78.2 GB disk)
- OS : Windows 11
- Python : 3.7

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@aravinthk00 seems like you might want to raise this issue directly on the repo you are following directions in.

**Comment by aravinthk00** [comment]
Already I raised but still no reply. it is pretrained model [yolov5s.torchscript.ptl](https://drive.google.com/file/d/1UGdwiSkoew6CEgRMk6DhZtY0nuNmuNjC/view?usp=share_link), I also fellow that repo instructions to use export comment to get custom model [best.torchscript.ptl](https://drive.google.com/file/d/1VX6LW3WDpgCOddibvyp-xSNWcy97zo1K/view?usp=share_link), in this case both models architecture different, How do resolve this issue, please help me...

**Comment by glenn-jocher** [comment]
@aravinthk00 third party repositories are outside the scope of our support. I'd contact the authors of the work you are using directly.

**Comment by aravinthk00** [comment]
Sure. Thankyou 👍

**Comment by glenn-jocher** [comment]
@aravinthk00 you're welcome! If you have any other questions or need further assistance, feel free to ask. Good luck with your project! 👍
