### ISSUE TITLE
How to set parameters to be saved as fixed input 416 * 416 during training and testing？

### ISSUE THREAD

**Issue by APeiZou** [ultralytics/yolov5#10160]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

@ultralytics Hello,   how to set parameters to be saved as fixed input 416 * 416 during training and testing？

**Comment by glenn-jocher** [comment]
@APeiZou to use 416 image sizes:
```
python train.py --imgsz 416
python val.py --imgsz 416
```
