### ISSUE TITLE
Stream output without original image

### ISSUE THREAD

**Issue by Syrupy22** [ultralytics/yolov5#10170]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is it possible to take in a RTSP stream and output the inference results in a RTSP stream as well, but with a transparent background? (PNG transparency / Alpha Layer)

**Comment by glenn-jocher** [comment]
@Syrupy22 hey there! Thanks for reaching out. Yes, you can accomplish this by using the YOLOv5 real-time object detection on an RTSP stream, and then output the inference results with a transparent background using the `--webcam` argument in combination with a custom rendering function. You can find more details on customizing the rendering in the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/. Let me know if you need further assistance with this!
