### ISSUE TITLE
Conversion of Yolov5x to yolov5s weights

### ISSUE THREAD

**Issue by sriramk146** [ultralytics/yolov5#10174]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

I have Memory issue in prediction code, due to model got trained with larger weight (Yolov5x.pt). Could it be possible for converting Larger (yolov5x) to Smaller (yolov5s) weights for same trained checkpoint?

### Use case

Decrease memory consumption.

### Additional

Faster prediction.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@sriramk146 I'd train a smaller model.

**Comment by sriramk146** [comment]
ofcourse, I accept re-training of model with smaller weights. I have checkpoint of my model which was trained for 10 hours using larger pre-trained weights ( i.e. Yolov5x.pt). Now, I need to convert this trained checkpoint to a smaller weight file (which will be as like trained model with YoloV5s.pt), Since, I don't want to spend few more hours of training a model again. Could it be possible?

**Comment by glenn-jocher** [comment]
@sriramk146 got it. Currently, there's no built-in method for converting a model checkpoint from YOLOv5x to YOLOv5s directly. A retraining with the smaller model is recommended for optimal results.
