### ISSUE TITLE
convert segmentation cordinate to 8 points polygon cordinate

### ISSUE THREAD

**Issue by WongVi** [ultralytics/yolov5#10179]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How can i convert the segmentation coordinate to 8 points polygon coordinate?I

**Comment by mughal41** [comment]
@WongVi Hi have you solved this issue?? im also facing a similar problem 
![Screenshot from 2023-02-16 10-42-25](https://user-images.githubusercontent.com/74859743/219278683-0e90c0f2-747f-4c00-8f10-0b7959f32c0e.png)
