### ISSUE TITLE
Export classification model to pb/tensorflow ?

### ISSUE THREAD

**Issue by juliandewit** [ultralytics/yolov5#10187]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Hello I was using the classification solution and was very happy with it. 
Not as feature complete as for object detection but still it was all looking very user friendly and good.
However in the last step (export) it notified that Tensorflow export was not supported.

Is this very hard to accomplish and will it take a while or is this feature very near ?
It looks difficult because of yaml parsing to TF model.. However it already works for your detectors..
I don't know if I would be up to the task.. 

### Use case

Tensorflow runtime users.

### Additional

Great work

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@juliandewit TF export requires TF versions of each PyTorch module used in the model defined in tf.py. 
https://github.com/ultralytics/yolov5/blob/master/models/tf.py

What classification model are you trying to export?

**Comment by juliandewit** [comment]
So far only the default.
yolov5s-cls.pt which is already great.
Perhaps later a bigger net but I do not have plans to go "exotic"

**Comment by glenn-jocher** [comment]
@juliandewit then we're probably just missing an equivalent Classify() module, i.e. we need a TFClassify() in models/tf.py. If you're good at TF you could create a PR for one, if not I can add a TODO to add this to the list.

https://github.com/ultralytics/yolov5/blob/a9f895d304aea5920e694606927fa9208aa7f0ed/models/common.py#L847-L860

**Comment by zldrobit** [comment]
@glenn-jocher Sure. glad to help. 
I guess that the network structure in yaml config file is not embedded in the classification model. Below is the output when I ran `export.py`,
![image](https://user-images.githubusercontent.com/3896992/202667060-b802293e-e20c-4a90-aa35-323e795a439a.png)
Maybe some code has to be added in `classify/train.py` for adding the yaml.

**Comment by juliandewit** [comment]
I will also try to look at the code but is all pretty new for me so do not expect quick results. :)

**Comment by glenn-jocher** [comment]
@zldrobit oh of course, you're right. We aren't constructing cls models from YAMLs but rather from detection model backbones. Ok I'll have to think about this some more, thanks for pointing that out.
