### ISSUE TITLE
Result inference 

### ISSUE THREAD

**Issue by HeyImAlice** [ultralytics/yolov5#10188]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi !

My question is simple : 
When I use your inference methode (results = model(im)), i want to take all the box and draw it with opencv, but when I don't find the solution...
I use the results.pandas().xyxy[0] to take the xmax, ymxa, etc ... and put it in a cv2.rectangle function, but it dosen't work
So if someone can help me to call the good function/parameter, I appreciate ;D 

You can see my code below.
Thanks !

Ps : I use this page to build the code : https://github.com/ultralytics/yolov5/issues/36

### Additional

```PYTHON
import torch
import cv2


def set_Camera(source):
    vid = cv2.VideoCapture(source)

    if not vid.isOpened():
        raise IOError("Cannot open webcam")

    vid.set(cv2.CAP_PROP_FOURCC, cv2.VideoWriter_fourcc(*'MJPG'))
    vid.set(cv2.CAP_PROP_FRAME_WIDTH, 1280)
    vid.set(cv2.CAP_PROP_FRAME_HEIGHT, 720)
    vid.set(cv2.CAP_PROP_FPS, 120)

    return vid


if __name__ == '__main__':
    # Model
    # model = torch.hub.load('ultralytics/yolov5', 'custom', path='best.pt')
    model = torch.hub.load('C:/yolov5-master', 'custom', path='nid.pt', source='local')

    camera = set_Camera(0)

    while True:
        # Images
        _, im = camera.read()

        # Inference
        results = model(im)

        # Results
        results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

        p1 = (results.pandas().xyxy[0].xmin, results.pandas().xyxy[0].ymin)
        p2 = (results.pandas().xyxy[0].xmax, results.pandas().xyxy[0].ymax)
        print(p1)
        print(p2)
        cv2.rectangle(im, p1, p2, (255,255,255), -1, cv2.LINE_AA)
        cv2.imshow("test", im)

        if cv2.waitKey(1) & 0xFF == ord('q'):
            print("finished by user")
            break

```

**Comment by glenn-jocher** [comment]
@HeyImAlice just use results.render() to render predictions on images and then results.show() or results.save()

**Comment by HeyImAlice** [comment]
> @HeyImAlice just use results.render() to render predictions on images and then results.show() or results.save()

Well, result.show() open a windows image, not a windows with my webcam..

I think I forget to tell you I use a webcam for video detection :p
