### ISSUE TITLE
为什么Yolov5s-p34比Yolov5s的精度提高了那么多？

### ISSUE THREAD

**Issue by Hehezcr** [ultralytics/yolov5#10199]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

因为我的数据集都是单目标的小目标，且锚框大小差不多，所以我是用YOLOv5s-p34.yaml进行训练，最终结果发现YOLOv5s-p34比YOLOv5s的Recall 、Precision、Map高了接近4%，可是我不知道为什么会高。因为YOLOv5s只去掉P5，不是应该只是降低了模型大小而已吗？怎么会提高这么多精度。我的训练集是2600张，标签是40000多个，验证集是300多张，标签6000个。希望能得到解释。

**Comment by Hehezcr** [comment]
因为我的数据集都是单目标的小目标，且锚框大小差不多，所以我是用YOLOv5s-p34.yaml进行训练，最终结果发现YOLOv5s-p34比YOLOv5s的Recall 、Precision、Map高了接近4%，可是我不知道为什么会高。因为YOLOv5s只去掉P5，不是应该只是降低了模型大小而已吗？怎么会提高这么多精度。我的训练集是2600张，标签是40000多个，验证集是300多张，标签6000个。希望能得到解释。

**Comment by Hehezcr** [comment]
是的，我的数据集都是小对象，而且基本P3和P4就可以完成所有的识别任务，但是为什么没有P5后Recall值也上升了？

**Comment by Hehezcr** [comment]
> @Hehezcr note that p34.yaml uses the same scaling constants as YOLOv5s, so the two models are identical other than the P5 output grids. If the model works better it's likely because your dataset is all small objects.
> 
> https://github.com/ultralytics/yolov5/blob/467a57f01b393989867426261d3e9a95566e3e24/models/hub/yolov5-p34.yaml#L5-L6

是因为我都是小目标，加入P5的话会导致Neck部分的特征融合有特征干扰？

**Comment by Sornets** [comment]
> > @Hehezcr note that p34.yaml uses the same scaling constants as YOLOv5s, so the two models are identical other than the P5 output grids. If the model works better it's likely because your dataset is all small objects.
> > https://github.com/ultralytics/yolov5/blob/467a57f01b393989867426261d3e9a95566e3e24/models/hub/yolov5-p34.yaml#L5-L6
> 
> 是因为我都是小目标，加入P5的话会导致Neck部分的特征融合有特征干扰？

Neck层将P5与P34进行了特征融合，P5层特征分辨率低，适合大目标识别，但是小目标识别需要高分辨率，因此P5实际上不利于小目标识别。
