### ISSUE TITLE
train with --image-weights got error: Tensors must be CUDA and dense

### ISSUE THREAD

**Issue by Edwardmark** [ultralytics/yolov5#1019]
## ❔Question
Any guide about how to set the option in train.py?
When I set --image-weights, I got the error: Tensors must be CUDA and dense

## Additional context
So how to train with image-weights.

Thanks.

**Comment by glenn-jocher** [comment]
@Edwardmark I haven't used this feature in a while, may require some debugging. Sounds like you just need to send your tensors to device.

**Comment by Edwardmark** [comment]
@glenn-jocher OK, thanks.
