### ISSUE TITLE
pycocotools mAP inconsistent

### ISSUE THREAD

**Issue by XiaopinWang** [ultralytics/yolov5#10191]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

val: Scanning '/home/yolov5/yolov5-master/my_yolo_dataset/test/labels.cache' images and labels... 722 found, 0 missing, 0
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 46/46 [02:31<00:00,
                   all        722       6289       0.99       0.99      0.991      0.874
                 stand        722       2913      0.999      0.997      0.994      0.862
              sideways        722        966      0.983      0.983       0.99      0.891
                 creep        722       2410      0.988       0.99      0.989      0.868
##########################################################
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.438
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.514
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.509
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.438
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.087
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.890
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.891
#####################################
python val.py --save_json (default=True)
How do you solve this problem? Thank you!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@XiaopinWang pycocotools eval is really only intended for the COCO dataset. It's possible to run it with other datasets if you have val results in coco JSON format, but we don't officially provide support for this.

**Comment by XiaopinWang** [comment]
Hello, I have converted the real annotation file to coco format, --save_jaon to generate the forecast file, but this problem still occurs .

**Comment by XiaopinWang** [comment]
# Predict the partial files generated
[{"image_id": 2, "category_id": 0, "bbox": [1422.365, 791.003, 384.285, 563.891], "score": 0.95585}, {"image_id": 2, "category_id": 1, "bbox": [1376.479, 58.438, 525.028, 510.389], "score": 0.95157}, {"image_id": 2, "category_id": 0, "bbox": [280.724, 320.207, 432.961, 441.76], "score": 0.94828}, {"image_id": 2, "category_id": 1, "bbox": [1694.428, 882.403, 398.724, 400.852], "score": 0.9481}, {"image_id": 2, "category_id": 2, "bbox": [1234.205, 564.634, 598.976, 255.11], "score": 0.93899}, {"image_id": 2, "category_id": 2, "bbox": [81.978, 635.245, 263.511, 597.086], "score": 0.93565}, {"image_id": 2, "category_id": 2, "bbox": [35.116, 237.069, 296.345, 602.157], "score": 0.93437}, {"image_id": 2, "category_id": 0, "bbox": [1618.826, 660.108, 517.151, 290.871], "score": 0.93399}, {"image_id": 2, "category_id": 2, "bbox": [2058.797, 580.991, 332.943, 212.409], "score": 0.93058}, {"image_id": 2, "category_id": 1, "bbox": [1420.483, 793.118, 388.819, 564.043], "score": 0.00741}, {"image_id": 2, "category_id": 2, "bbox": [1421.096, 790.779, 388.059, 564.592], "score": 0.0056}, {"image_id": 2, "category_id": 2, "bbox": [1696.534, 883.919, 396.385, 398.155], "score": 0.00544}, {"image_id": 2, "category_id": 0, "bbox": [1697.061, 881.937, 395.952, 398.259], "score": 0.00521}
# convert coco 
{"images": [{"id": 2, "file_name": "000000000002.jpg", "width": 2560, "height": 1440}, {"id": 19, "file_name": "000000000019.jpg", "width": 2560, "height": 1440}, {"id": 23, "file_name": "000000000023.jpg", "width": 2560, "height": 1440}, {"id": 24, "file_name": "000000000024.jpg", "width": 2560, "height": 1440}, {"id": 27, "file_name": "000000000027.jpg", "width": 2560, "height": 1440}, {"id": 30, "file_name": "000000000030.jpg", "width": 2560, "height": 1440}

[{"segmentation": [[285.25157232704413, 322.9245283018869, 285.25157232704413, 759.7169811320754, 706.3207547169811, 759.7169811320754, 706.3207547169811, 322.9245283018869]], "area": 183919.8409873026, "iscrowd": 0, "ignore": 0, "image_id": 2, "bbox": [285.25157232704413, 322.9245283018869, 421.069182389937, 436.7924528301885], "category_id": 0, "id": 0}, {"segmentation": [[1628.3333333333335, 681.6666666666667, 1628.3333333333335, 930.0, 2133.3333333333335, 930.0, 2133.3333333333335, 681.6666666666667]], "area": 125408.3333333333, "iscrowd": 0, "ignore": 0, "image_id": 2, "bbox": [1628.3333333333335, 681.6666666666667, 505.0, 248.33333333333326], "category_id": 0, "id": 1}, {"segmentation": [[1436.6666666666667, 820.0, 1436.6666666666667, 1370.0, 1786.6666666666667, 1370.0, 1786.6666666666667, 820.0]], "area": 192500.0, "iscrowd": 0, "ignore": 0, "image_id": 2, "bbox": [1436.6666666666667, 820.0, 350.0, 550.0], "category_id": 0, "id": 2}, {"segmentation": [[49.71698113207547, 250.2830188679245, 49.71698113207547, 821.9811320754717, 347.8301886792453, 821.9811320754717, 347.8301886792453, 250.2830188679245]], "area": 170430.7582769669, "iscrowd": 0, "ignore": 0, "image_id": 2, "bbox": [49.71698113207547, 250.2830188679245, 298.1132075471698, 571.6981132075472], "category_id": 1, "id": 3}, {"segmentation": [[81.79245283018868, 661.6037735849056, 81.79245283018868, 1220.0943396226414, 340.2830188679245, 1220.0943396226414, 340.2830188679245, 661.6037735849056]], "area": 144364.5425418298, "iscrowd": 0, "ignore": 0, "image_id": 2, "bbox": [81.79245283018868, 661.6037735849056, 258.49056603773585, 558.4905660377358], "category_id": 1, "id": 4}, {"segmentation": [[2038.3333333333335, 573.3333333333334, 2038.3333333333335, 785.0, 2400.0, 785.0, 2400.0, 573.3333333333334]], "area": 76552.77777777774, "iscrowd": 0, "ignore": 0, "image_id": 2, "bbox": [2038.3333333333335, 573.3333333333334, 361.6666666666665, 211.66666666666663], "category_id": 1, "id": 5}, {"segmentation": [[1251.6666666666667, 543.3333333333334, 1251.6666666666667, 835.0, 1825.0, 835.0, 1825.0, 543.3333333333334]], "area": 167222.2222222222, "iscrowd": 0, "ignore": 0, "image_id": 2, "bbox": [1251.6666666666667, 543.3333333333334, 573.3333333333333, 291.66666666666663], "category_id": 1, "id": 6}, {"segmentation": [[1371.3584905660377, 52.16981132075472, 1371.3584905660377, 571.0377358490566, 1890.2264150943395, 571.0377358490566, 1890.2264150943395, 52.16981132075472]], "area": 269223.92310430756, "iscrowd": 0, "ignore": 0, "image_id": 2, "bbox": [1371.3584905660377, 52.16981132075472, 518.8679245283017, 518.867924528302], "category_id": 2, "id": 7}, {"segmentation": [[1688.3396226415093, 882.3584905660377, 1688.3396226415093, 1269.1509433962262, 2077.0188679245284, 1269.1509433962262, 2077.0188679245284, 882.3584905660377]], "area": 150338.19864720543, "iscrowd": 0, "ignore": 0, "image_id": 2, "bbox": [1688.3396226415093, 882.3584905660377, 388.6792452830191, 386.7924528301885], "category_id": 2, "id": 8}, {"segmentation": [[250.60377358490564, 137.07547169811318, 250.60377358490564, 848.3962264150944, 499.66037735849056, 848.3962264150944, 499.66037735849056, 137.07547169811318]], "area": 177159.13136347456, "iscrowd": 0, "ignore": 0, "image_id": 19, "bbox": [250.60377358490564, 137.07547169811318, 249.05660377358492, 711.3207547169811], "category_id": 0, "id": 9}, {"segmentation": [[1446.830188679245, 412.5471698113207, 1446.830188679245, 1054.0566037735848, 1837.3962264150941, 1054.0566037735848, 1837.3962264150941, 412.5471698113207]], "area": 250551.7977928088, "iscrowd": 0, "ignore": 0, "image_id": 19, "bbox": [1446.830188679245, 412.5471698113207, 390.566037735849, 641.5094339622641], "category_id": 0, "id": 10}, {"segmentation": [[2043.0566037735848, 338.9622641509434, 2043.0566037735848, 500.0, 2361.666666666667, 500.0, 2361.666666666667, 338.9622641509434]], "area": 51308.24314702748, "iscrowd": 0, "ignore": 0, "image_id": 19, "bbox": [2043.0566037735848, 338.9622641509434, 318.61006289308216, 161.03773584905662], "category_id": 0, "id": 11}, {"segmentation": [[2046.666666666667, 575.0, 2046.666666666667, 784.2452830188679, 2386.452830188679, 784.2452830188679, 2386.452830188679, 575.0]], "area": 71098.65195205872, "iscrowd": 0, "ignore": 0, "image_id": 19, "bbox": [2046.666666666667, 575.0, 339.786163522012, 209.2452830188679], "category_id": 1, "id": 12}, {"segmentation": [[518.5283018867924, 1016.3207547169811, 518.5283018867924, 1333.3018867924527, 1177.0188679245282, 1333.3018867924527, 1177.0188679245282, 1016.3207547169811]], "area": 208729.08508365956, "iscrowd": 0, "ignore": 0, "image_id": 19, "bbox": [518.5283018867924, 1016.3207547169811, 658.4905660377358, 316.9811320754716], "category_id": 1, "id": 13}, {"segmentation": [[929.8490566037735, 1.2264150943396146, 929.8490566037735, 242.73584905660374, 1548.7169811320755, 242.73584905660374, 1548.7169811320755, 1.2264150943396146]], "area": 149462.4421502314, "iscrowd": 0, "ignore": 0, "image_id": 19, "bbox": [929.8490566037735, 1.2264150943396146, 618.867924528302, 241.50943396226413], "category_id": 1, "id": 14}, {"segmentation": [[273.99371069182394, 1.4465408805031643, 273.99371069182394, 401.2264150943396, 748.7169811320755, 401.2264150943396, 748.7169811320755, 1.4465408805031643]], "area": 189784.8093429848, "iscrowd": 0, "ignore": 0, "image_id": 19, "bbox": [273.99371069182394, 1.4465408805031643, 474.72327044025155, 399.7798742138364], "category_id": 1, "id": 15}, {"segmentation": [[1609.0943396226414, 1120.0943396226414, 1609.0943396226414, 1301.2264150943395, 2118.528301886792, 1301.2264150943395, 2118.528301886792, 1120.0943396226414]], "area": 92274.83090067633, "iscrowd": 0, "ignore": 0, "image_id": 19, "bbox": [1609.0943396226414, 1120.0943396226414, 509.43396226415075, 181.13207547169804], "category_id": 0, "id": 16}, {"segmentation": [[15.754716981132074, 269.1509433962264, 15.754716981132074, 850.2830188679245, 283.6792452830189, 850.2830188679245, 283.6792452830189, 269.1509433962264]], "area": 155699.5372018512, "iscrowd": 0, "ignore": 0, "image_id": 19, "bbox": [15.754716981132074, 269.1509433962264, 267.9245283018868, 581.132075471698], "category_id": 2, "id": 17}, {"segmentation": [[1594.0, 288.01886792452825, 1594.0, 797.4528301886792, 2043.0566037735848, 797.4528301886792, 2043.0566037735848, 288.01886792452825]], "area": 228764.68494126017, "iscrowd": 0, "ignore": 0, "image_id": 23, "bbox": [1594.0, 288.01886792452825, 449.0566037735848, 509.4339622641509], "category_id": 0, "id": 18},

**Comment by glenn-jocher** [comment]
@XiaopinWang it seems you are attempting to convert the annotation file to COCO format and then run evaluation using pycocotools. Just to clarify, the issue you are experiencing is with the mAP calculation using pycocotools, is that correct? If you need assistance with converting the results to COCO format or any other related task, please let me know.
