### ISSUE TITLE
how to save segmentation predict mask result?

### ISSUE THREAD

**Issue by ke-dev** [ultralytics/yolov5#10194]
### Search before asking

- [ ] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hi, developers, 
    how to save segmentation predict mask result? This puzzled me.
looking forward to your reply.

**Comment by glenn-jocher** [comment]
@ke-dev `python segment/predict.py --save-txt`
