### ISSUE TITLE
c2.imshow() not showing window in Docker

### ISSUE THREAD

**Issue by edehino** [ultralytics/yolov5#10197]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi I am trying to use docker to run yolov5 but the pop up window for the frame with detections is not working. Anyone who knows how to fix this?

**Comment by glenn-jocher** [comment]
@edehino docker environments are not capable of showing results. You can do this in a local environment via PyCharm for example.
