### ISSUE TITLE
Which model used in training phase

### ISSUE THREAD

**Issue by CesareDavidePace** [ultralytics/yolov5#10206]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

how can i check which model was used from the experiments in the train folder?

**Comment by theoholl** [comment]
In the file *runs/train/exp/opt.yaml* you can find the initial weights used, e.g. `weights: yolov5s.pt`. It might be easier to name the experiment folder to something more meaningful than *exp* by using the name parameter for *train.py*: `python train.py --name 'some better name'`.

**Comment by glenn-jocher** [comment]
@theoholl thanks for reaching out! To check which model was used from the experiments in the train folder, you can find the initial weights used in the file *runs/train/exp/opt.yaml*. For example, you'll see `weights: yolov5s.pt` indicating the model used. It's also a good idea to name the experiment folder meaningfully using the `--name` parameter in *train.py* for easier reference. Let me know if you need further assistance!
