### ISSUE TITLE
How to get unnormalized tensor of detected objects?

### ISSUE THREAD

**Issue by tgrmev** [ultralytics/yolov5#10200]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I downloaded yolov5 model with torch.hub.load(). I see the detection is doing very well but I need to receive unnormalized tensor of the detected objects. I add the sample code snippet about what I am doing. 
```
img_fdr="./video.mp4"
cap = cv2.VideoCapture(img_fdr)
while(1):
   ret, frame = cap.read()
   results = model(frame)
   print(results.xyxy[0]) # im predictions (tensor)
```
When I run the code, I am receiving :

> tensor([[3.73146e+02, 1.76545e+02, 4.48503e+02, 3.62936e+02, 9.06312e-01, 0.00000e+00],
        [1.27470e+02, 1.09120e+02, 2.72081e+02, 4.01167e+02, 7.10027e-01, 0.00000e+00],
        [1.25912e+02, 1.50532e+02, 1.63620e+02, 2.37710e+02, 6.50817e-01, 2.40000e+01]])

But I need a tensor in unnormalized form like this :

> tensor([[374.00000, 176.00000, 449.00000, 363.00000,   0.91127,   0.00000],
        [128.00000, 110.00000, 268.00000, 400.00000,   0.69647,   0.00000],
        [128.00000, 150.00000, 161.00000, 236.00000,   0.55866,  24.00000]])

How can I do it?

**Comment by glenn-jocher** [comment]
@tgrmev these are both un-normalized. Normalized means expressing a value between 0 and 1.

**Comment by glenn-jocher** [comment]
@tgrmev viewing values in different formats is outside the scope of YOLOv5 and more a question for a PyTorch forum or stackoverflow
