### ISSUE TITLE
ONXX inference

### ISSUE THREAD

**Issue by liuxianyi** [ultralytics/yolov5#10208]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

  ```
         im = im.cpu().numpy()  # torch to numpy
           y = self.session.run(self.output_names, {self.session.get_inputs()[0].name: im})
```
bro, i found that the onnx inference process will calculate the gpu data copy on the cpu, so what if the onnx in the gpu accelerated computation?

**Comment by glenn-jocher** [comment]
@liuxianyi as far as I understand it, ONNX models require numpy inputs, and numpy arrays can only exist on CPU.

**Comment by liuxianyi** [comment]
> 

I understand, thanks. but I have another question.  I remember onxxruntime provides onxxruntime-gpu version, so how can i use it for GPU acceleration.

**Comment by glenn-jocher** [comment]
@liuxianyi YOLOv5 will automatically install onnxruntime-gpu if your system has CUDA devices available. You can always install it manually also if you want.

https://github.com/ultralytics/yolov5/blob/6992dde4bd628f6bffe7d4c5025afadf79ed679b/models/common.py#L364-L367
