### ISSUE TITLE
There seems to be a bug in the Mosaic data augmentation?

### ISSUE THREAD

**Issue by haoyuefan** [ultralytics/yolov5#1020]
I visualized the Mosaic data augmentation and found that some of the labels wrong shifted after the data augmentation. After debugging, I find there seems to be a problem with this line of the load_mosaic function:
`x1b, y1b, x2b, y2b = w - (x2a - x1a), 0, max(xc, w), min(y2a - y1a, h)`
the line 664 of dataset.py, I want to ask if this line should be changed:
`x1b, y1b, x2b, y2b = w - (x2a - x1a), 0, w, min(y2a - y1a, h)`
because in the bottom left patch of mosaic image, the xmax point of source image shouldn't be changed. 
Hope you can reply me soon, thank you.

**Comment by gengyanlei** [comment]
@yuefanhao 
I also found this problem, but it has no effect.

**Comment by haoyuefan** [comment]
> @yuefanhao
> I also found this problem, but it has no effect.

But it will create wrong label shift when I visualized the mosaic image with my own datasets, have you visualized the mosaic image?

**Comment by gengyanlei** [comment]
I used yolov5 to train my own data set and found no abnormalities. But when I studied mosaic code, I found this error by reasoning, but it didn't affect the image.
For example: a=np.ones([10,10,3]), a[:10] and a[:14] are equivalent.

**Comment by haoyuefan** [comment]
> I used yolov5 to train my own data set and found no abnormalities. But when I studied mosaic code, I found this error by reasoning, but it didn't affect the image.
> For example: a=np.ones([10,10,3]), a[:10] and a[:14] are equivalent.

ok, I understand that, thank you.

**Comment by glenn-jocher** [comment]
@gengyanlei @yuefanhao thanks for the bug report! Can you show an image of the mislabelled instances?

Would you like to submit a PR for this change?

**Comment by glenn-jocher** [comment]
@gengyanlei @yuefanhao I'm removing the TODO label and closing this issue, as this has been resolved in PR https://github.com/ultralytics/yolov5/pull/1021 submitted by @yuefanhao and merged a few weeks ago. Thank you for your contributions!
