### ISSUE TITLE
Approximately how small of an object  we do not need to label?

### ISSUE THREAD

**Issue by chakloong883** [ultralytics/yolov5#10227]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Some small objects that we can identify as categories in the global image, but when zoomed in they cannot be identified by pixels alone, do such objects need to be labelled. How small an object we do not need to label, take 640*640 image size as an example.

**Comment by bit-scientist** [comment]
you should label an object which you want your model to detect when you inference/deploy for your use case. In perfect scenario, you should label all the objects in an image. But in training, your model may not be able to detect very small objects in which case should consider some other techniques like [SAHI](https://github.com/obss/sahi)

**Comment by glenn-jocher** [comment]
@bit-scientist you should label any object that you want your model to detect during inference. While it's ideal to label all objects in an image, very small objects may not be detected during training. In such cases, consider using other techniques like SAHI for better results.
