### ISSUE TITLE
ConfusionMatrix doesn't use the iou_thres we pass to the validation script.

### ISSUE THREAD

**Issue by manikandakrishnan** [ultralytics/yolov5#10238]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Validation

### Bug

Line 185: in val.py has the following form : confusion_matrix = ConfusionMatrix(nc=nc)
but confusion matrix class also requires a iou_thres parameter whose default value as specified in utils.metrics is 0.45. 

So when we pass a new iou_thres parameter it doesnt reflect in the confusion matrix generated.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@manikandakrishnan confusion matrix is initialized with the same default deployment thresholds used in detect.py, i.e. 0.25 conf 0.45 iou thresh. This is a deployment indicator, there is no such thing as a confusion matrix generated at val.py values of 0.001 and 0.60, it would be all FPs.

**Comment by manikandakrishnan** [comment]
understood

**Comment by glenn-jocher** [comment]
@manikandakrishnan great! Let me know if there's anything else I can help with.
