### ISSUE TITLE
Ultralytics Android Application Compatibility with Samsung Galaxy S20 (FE 5G) 

### ISSUE THREAD

**Issue by ConorHackett98** [ultralytics/yolov5#10235]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Integrations

### Bug

Hi,

When I try and run the Ultralytics Android Application (https://play.google.com/store/apps/details?id=com.ultralytics.ultralytics_app&hl=en_IE&gl=US) on a Samsung Galaxy S20 FE 5G, the application is unable to open as it gets stuck on the logo screen (see attached image).

I've tried uninstalling and reinstalling the application and rebooting the mobile device, but nothing seems to work.  I've also tried the applications on other Android devices, but it has worked perfect for every other device.

I was wondering if anyone might know a quick fix for this issue.  

Thank you!

(Image of the application stuck while opening.)  
![Screenshot_20221121-101321](https://user-images.githubusercontent.com/56347543/203026307-72ab432f-c7f9-4176-b52f-e03d4fc74844.jpg)

### Environment

- Device:  Samsung Galaxy S20 FE 55
- OS: Android

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by sergiossm** [comment]
Hi @ConorHackett98, thank you for reporting the issue. As @glenn-jocher mentioned, we, unfortunately, don't have a Samsung Galaxy S20 to test the app on and haven't received any issues in our crash reporting tool.

We'll try to track the bug and let you know if we find a solution!

**Comment by ConorHackett98** [comment]
I managed to fix this issue in the most recent version of Ultralytics on Android 12 by going into:
Settings -> Apps ->Ultralytics -> Storage -> Clear Data.  

I was then able to open the app again and log in.

**Please note this will delete any data associated with the Ultralytics Android Application.**  Data from the Ultralytics Hub account will still be intact though.  Uninstalling and reinstalling the Android app may not work as modern phones tend to keep backups of Android app data when an app is uninstalled.

**Comment by glenn-jocher** [comment]
@ConorHackett98 oh wow, thanks for debugging this and letting us know the solution!

@sergiossm I wonder if it's possible to flag this data for deletion on app deletion or if there's anything we can do to handle this automatically?

**Comment by sergiossm** [comment]
@glenn-jocher we've included a similar feature some updates ago. 

> @ConorHackett98 oh wow, thanks for debugging this and letting us know the solution!
> 
> 
> 
> @sergiossm I wonder if it's possible to flag this data for deletion on app deletion or if there's anything we can do to handle this automatically?

**Comment by glenn-jocher** [comment]
@sergiossm awesome!!
