### ISSUE TITLE
a fine distinction at metric.py between yolov5 5.0 and yolov5 6.0, I don't undertand why

### ISSUE THREAD

**Issue by yuan-kai-design** [ultralytics/yolov5#10234]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Validation

### Bug

     yolov5 6.0 metric.py  
        n = matches.shape[0] > 0
        m0, m1, _ = matches.transpose().astype(int)
        for i, gc in enumerate(gt_classes):
            j = m0 == i
            if n and sum(j) == 1:
                self.matrix[**detection_classes[m1[j]], gc**] += 1  # correct
            else:
                self.matrix[self.nc, gc] += 1  # true background

yolov5 5.0 metric.py
        n = matches.shape[0] > 0
        m0, m1, _ = matches.transpose().astype(np.int16)
        for i, gc in enumerate(gt_classes):
            j = m0 == i
            if n and sum(j) == 1:
                self.matrix[**gc, detection_classes[m1[j]]**] += 1  # correct
            else:
                self.matrix[self.nc, gc] += 1  # background FP
I find a fine distinction at metric.py between yolov5 5.0 and yolov5 6.0, I don't unstand it

### Environment

Windows 10
Python 3.8

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@yuan-kai-design later code will have more bugs fixed and features added, so yes you should expect differences in code, otherwise there'd be no new releases.
