### ISSUE TITLE
accumulating test result in different folders, yolov5 detect.py

### ISSUE THREAD

**Issue by bugrahanismailoglu** [ultralytics/yolov5#10237]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,

I have 2 classes and I did the train process. But instead of saving the images I exported in different files one by one, I want to save them in two different folders. I think I need to add to detect.py for this. Can you help with this?

```
# Save results (image with detections)
if save_img:
     if dataset.mode == 'image':
    
     # my part
     if str(names[c]) == 'x':
          i = 0
          cv2.imwrite('runs/x/' + str(i), im0)
          i += 1
     else:
          ii = 0
          cv2.imwrite('runs/xx' + str(ii), im0)
          ii += 1

          #cv2.imwrite(save_path, im0)
```
Here I added the code I wrote to the registration part. Very simply I have two different classes. x and xx. When I examine the code, 'names[c]' outputs the name of my class. I want to sync this to what I want and then save it there by giving the path I want directly. Where is my mistake?

Or where can I add something? How can I classify according to the result of the image I gave for the test?

**Comment by glenn-jocher** [comment]
@bugrahanismailoglu hi there,

To save your detections in different folders based on the class, you can modify the `detect.py` script as follows:

```python
# Save results (image with detections)
if save_img:
    for i, det in enumerate(pred):  # detections per image
        if dataset.mode == 'image':
            save_path = Path('runs') / 'classes' / names[int(det[5])] / f'{save_dir}{imgsz}'
            save_path.mkdir(parents=True, exist_ok=True)  # makes dir if it doesn't exist
            cv2.imwrite(str(save_path / f'{img0}{i}.jpg'), im0)
```

This modification will save the images in separate folders based on the detected class. Please replace `'classes'` with your desired output directory.

For further details, you can refer to the documentation at https://docs.ultralytics.com/yolov5/. Let me know if you need any more help!
