### ISSUE TITLE
Overfitted F1 score

### ISSUE THREAD

**Issue by Malitha123** [ultralytics/yolov5#10233]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When the model is overfitting and when calculating the F1 score does it give the overfitted F1 score or F1 score from best weight?

**Comment by glenn-jocher** [comment]
@Malitha123 val.py produces final metrics on best.pt during training.
