### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by Mrinh212375** [ultralytics/yolov5#10232]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have already trained the yolov5 model with the dataset having 33K images (31 classes), got the best.pt and last.pt. Now I want to train the model on some images that I have clicked by my phone, Now I have two queries - 

1. I'll have to train from best.pt rather than yolov5s.pt, right?
2. if I need that after this training also my model will have the capability to detect 31 classes + some classes from my images, then I have to use the .yaml file that was used previously with some classes added, isn't it?  but then during this training I may not have sufficient images which justify 31+some more classes.

actually, I need to augment the learning from my real images. Am I going right ??

**Comment by MartinPedersenpp** [comment]
Hello @Mrinh212375 
Your best and last.pt files are the results of the transfer learning process which has shifted the layer weights of the model towards recognizing your N classes.
If you want to continue training with more images/classes you need to keep the dataset which was used to achieve the best/last.pt files and add your new data to the dataset.
So if you add new classes, you must modify your dataset.yaml file to reflect your classes.
If you only add new images of the same classes, you only need to add the images with their labels.

I hope this helps

**Comment by Mrinh212375** [comment]
@MartinPedersenpp so , you mean if I'll give the dataset.yaml with some more added class and only the images of my own as dataset, then the model will get shifted to my new data, means it may not detect the images from the first dataset, right ??

**Comment by Mrinh212375** [comment]
@MartinPedersenpp , actually my guide was saying that it'll augment the learning, and is there any freeze mechanism so that I can freeze some layers which incurs some normalization(if any :-(

**Comment by MartinPedersenpp** [comment]
> @MartinPedersenpp , actually my guide was saying that it'll augment the learning, and is there any freeze mechanism so that I can freeze some layers which incurs some normalization(if any :-(

Quick google:
https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers

I can't say that I have tested it, but if you have trained on dataset1 and then train on dataset2 which misses some of the classes then it can't validate if the weights fit those classes.
I found this: https://github.com/ultralytics/yolov5/issues/3258

Hope it helps
