### ISSUE TITLE
Create Executable application for YOLO detection 

### ISSUE THREAD

**Issue by DoSquared** [ultralytics/yolov5#10239]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Good day everybody. 

I want to ask if there is any available tutorial on how to build an executable detection program from my YOLO detection notebook?

**Comment by glenn-jocher** [comment]
@DaliaMahdy sorry not sure what you mean by executable. There are some C/C++ inference examples if that helps in https://docs.ultralytics.com/yolov5/tutorials/model_export
