### ISSUE TITLE
How can i constantly feed yolo with images?

### ISSUE THREAD

**Issue by YeetMasterYeet** [ultralytics/yolov5#10236]
Hello, is there any way i can keep yolo loaded and keep on feeding new data to the model?
I want to be able to load the yolov5 model only once and be able to constantly feed yolov5 with new pictures to detect.
The context is that i am running ffmpeg (plugin in) parallel to yolov5 in order to cut a video into frames and i want yolo to detect objects in those frames but once the yolov5 model loads, it will not register new data being saved int the folder, so i would have to re-load the yolov5 again.
is there any way i can constantly feed yolo with new pictures?.

**Comment by glenn-jocher** [comment]
@YeetMasterYeet 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # yolov5n - yolov5x6 official model
#                                            'custom', 'path/to/best.pt')  # custom model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
results.xyxy[0]  # im predictions (tensor)

results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie

results.pandas().xyxy[0].value_counts('name')  # class counts (pandas)
# person    2
# tie       1
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by YeetMasterYeet** [comment]
Hello @glenn-jocher , it worked just as expected, thank you!
on last question, when i load my custom trained model, i still get object names associated to coco dataset i guess.
how do i include my own dataset name list associated to my custom model?

**Comment by glenn-jocher** [comment]
@YeetMasterYeet names are attributes of PyTorch Hub models, so you can define new names, i.e.

`model.names = ['a', 'b', 'c']` etc.

**Comment by YeetMasterYeet** [comment]
Thanks @glenn-jocher !

**Comment by glenn-jocher** [comment]
You're welcome, @YeetMasterYeet! If you need further assistance, feel free to ask!
