### ISSUE TITLE
--single-cls throws an error

### ISSUE THREAD

**Issue by bit-scientist** [ultralytics/yolov5#10230]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to train my custom dataset which has 3 classes as a single class. Therefore I used an argument `--single-cls`
However, it throws the following TypeError:

 `Traceback (most recent call last):
  File "train.py", line 637, in <module>
    main(opt)
  File "train.py", line 532, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 183, in train
    train_loader, dataset = create_dataloader(train_path,
  File "/home/user/yolov5/utils/dataloaders.py", line 119, in create_dataloader
    dataset = LoadImagesAndLabels(
  File "/home/user/yolov5/utils/dataloaders.py", line 503, in __init__
    self.segments[i][:, 0] = 0
TypeError: list indices must be integers or slices, not tuple
`
Initiallay, I thought that it was because I cashed the labels as multi-class (from previous trainings) `segments` was extracted from the that cache values and removed the cache files. But it didn't help. Could that be a bug of some kind?

**Comment by JustasBart** [comment]
I believe that the --single-cls is meant to indicate that you only (already) have a single class - and therefore it should make it easier/faster to train... Or at least that's my impression as per what it is and what it does...

**Comment by glenn-jocher** [comment]
@bit-scientist 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀.  I'm able to reproduce this after some experimenting, but in the future you're required to provide **code to reproduce** your issue. 

I'll add a TODO to investigate.

@JustasBart --single-cls trains any multi-class dataset in single-class mode.

**Comment by glenn-jocher** [comment]
@bit-scientist good news 😃! Your original issue may now be fixed ✅ in PR #10260. 

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://bit.ly/yolov5-paperspace-notebook"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
