### ISSUE TITLE
How to do AP calculation based on off-line prediction results and real results?

### ISSUE THREAD

**Issue by tensorflowt** [ultralytics/yolov5#1024]
## ❔Question
At present, I have the predicted value and the real value stored independently in the TXT file according to each image, that is to say, I have two TXT files for an image, one is the result of the real value and the other is the result of the predicted value. The content of TXT is as follows, based on these two results, how do I do AP calculation? How do I modify the text.py code?

## Additional context
![c45c41e554b71cc7a19682557248986](https://user-images.githubusercontent.com/37217594/94012580-92284800-fddb-11ea-9afc-1a625cf912d3.png)

**Comment by glenn-jocher** [comment]
@tensorflowt see test.py for AP computation.
