### ISSUE TITLE
Substitute Background causing corrupted save file

### ISSUE THREAD

**Issue by Syrupy22** [ultralytics/yolov5#10248]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I tried to substitute the background on which to write the inference, i.e. instead of the original video to have a empty/white background.

After importing PIL,

sub_bg = True
if sub_bg:
                im0 = PIL.Image.open('Empty.png')
                im0 = numpy.ascontiguousarray(im0)
            annotator = Annotator(im0, line_width=line_thickness, example=str(names))

By adding the above code before the initializing the annotator, I wanted the output to be an transparent background with just the bounding boxes and labels. I've also tested using a pure white png instead and it still doesn't work, so it doesnt seem to be an issue with png transparency. (Both pngs are already of the same size as the video/stream)

What confuses me is that there is no error message at all, just that the save file appears to be corrupted. I actually tested out the code on a rtsp stream as well, and the opencv seems to be showing the desired output, yet it just is unable to save the file properly. Is this because of some issue with the video writer when it comes to pngs? If so, what kinda of file should i be replacing im0 with?

**Comment by glenn-jocher** [comment]
@Syrupy22 I'm not sure if transparency channel is supported for videwriting. I would simply use a solid white or black background and see if that works.

**Comment by Syrupy22** [comment]
I actually already tried using a pure white png, but the same corrupted video was produced, similarly there was also no error message, so i thought there might be some issues with the png itself, maybe it needs to be a jpeg or some other file extension

**Comment by glenn-jocher** [comment]
@Syrupy22 It seems like there may be an issue with the way the video writer is handling the background substitution. I would recommend experimenting with different formats and sizes for the background image, such as using a larger resolution or a different file format like TIFF, to see if that resolves the issue. If the problem persists, it may be worth opening an issue on the YOLOv5 GitHub repository so that the developers can investigate further.
