### ISSUE TITLE
.flv video format suffix?

### ISSUE THREAD

**Issue by apiszcz** [ultralytics/yolov5#10259]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

utils/dataloaders.py
Line 41

Tested adding 'flv', detection processing operating correctly.
VID_FORMATS = 'asf', 'avi', 'flv', 'gif', 'm4v', 'mkv', 'mov', 'mp4', 'mpeg', 'mpg', 'ts', 'wmv'  # include video suffixes

BTW: thanks for adding vid-stride

### Use case

Handle flv files.

### Additional

Thank you for the hard work and yolov5 v7

I am wondering if the weight files have a version control description (date of generation, etc.?)

Thank you

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@apiszcz great, please add a PR for *.flv format videos then.

Training checkpoints have timestamps and git informations (remote, branch, commit), but we just added the second one, so this info will only be in newly trained models.

https://github.com/ultralytics/yolov5/blob/915bbf294bb74c859f0b41f1c23bc395014ea679/train.py#L370-L382
