### ISSUE TITLE
Why is yolov5 training slow? 

### ISSUE THREAD

**Issue by daigang896** [ultralytics/yolov5#10254]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Why is yolov5 training slow?  Use the yolov5m6 pretraining model. Does anyone have the same problem?

**Comment by glenn-jocher** [comment]
👋 Hello! Thanks for asking about **training speed issues**. YOLOv5 🚀 can be trained on CPU (slowest), [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) (fastest). If you would like to increase your training speed some options are:

- Increase `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s
- Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) DDP at larger `--batch-size`
- Train on cached data: `python train.py --cache` (RAM caching) or `--cache disk` (disk caching)
- Train on faster GPUs, i.e.: P100 -> V100 -> A100
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

Good luck 🍀 and let us know if you have any other questions!

**Comment by daigang896** [comment]
Hello.
Train on a NVIDIA RTX A6000 48G  card. When the batchsize is increased, the speed of each iteration becomes slow. But the GPU memory is sufficient, but the speed can not be improved. What is the bottleneck?

**Comment by Laughing-q** [comment]
@daigang896 It seems the bottleneck is data-loading as you've increased batch-size, maybe using more `workers` will help you.
[https://github.com/ultralytics/yolov5/blob/7398d2d77cbac9f66259926d49c26bfa3c257a9b/train.py#L457](https://github.com/ultralytics/yolov5/blob/7398d2d77cbac9f66259926d49c26bfa3c257a9b/train.py#L457)

**Comment by glenn-jocher** [comment]
@daigang896 also try --cache ram or --cache disk to reduce dataloading bottlenecks.

**Comment by daigang896** [comment]
Thanks, I'll try it.

**Comment by daigang896** [comment]
@glenn-jocher @Laughing-q 
Hello，
More --workers values did not work. The set --workers==--batchsize=16 did not find that the training speed of each iteration was faster. The CPU utilization is low. I don't know what the problem is.

**Comment by daigang896** [comment]
@glenn-jocher 
Try -- cache ram found insufficient memory, try -- cache disk found no improvement in training speed.

**Comment by David-19940718** [comment]
> @glenn-jocher Try -- cache ram found insufficient memory, try -- cache disk found no improvement in training speed.

For the most situation, follow the instructions by the author advise will be tackled.

**Comment by daigang896** [comment]
Hello.
At present, the training speed has been significantly improved and the problem has been solved by updating the card driver, cuda, cudnn and pytorch, and using yolov5 6.2 code.

**Comment by glenn-jocher** [comment]
@daigang896 great!!

**Comment by Robotatron** [comment]
I saw no difference in training time with --cache or without when using a SSD, interesting. 
Also using a smaller image size (e.g. 160 with batch size of 960) was training SLOWER then using a bigger image size (e.g. 240 with bs of 221)

**Comment by bartlomiejgadzicki-digica** [comment]
Hi there @glenn-jocher, do symlinks affect training speed? I keep multiple versions of my datasets and this way I can avoid storing the same images multiple times. Do you think it can be harmful in any way?

**Comment by glenn-jocher** [comment]
@bartlomiejgadzicki-digica symlinks generally do not affect training speed significantly, as they are simply pointers to the original data. However, they can introduce a slight overhead during data loading, so their impact on training speed might be negligible. Maintaining multiple dataset versions through symlinking is a smart storage solution. As long as your data loading and training procedures are not impacted, feel free to continue using symlinks to efficiently manage your datasets.
