### ISSUE TITLE
The organization of detector output tensor

### ISSUE THREAD

**Issue by Whisht** [ultralytics/yolov5#10250]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Does yolov5 follow the same output organization with yolov3? Just Like this:
![image](https://user-images.githubusercontent.com/16497652/203207038-5cc9aa31-f2f3-4551-abf0-15ab35fbddd9.png)
> This figure refers to https://towardsdatascience.com/yolo-v3-explained-ff5b850390f.

Take coco 80 classes with yolov5 as example. The outputs after the 3 different scale conv in [detect ](https://github.com/ultralytics/yolov5/blob/master/models/yolo.py#L59) are in different shape: `[20 * 20 * 255], [40 * 40 * 255], [80 * 80 * 255]`. Where the `255` is organized by `3 * (5+80)` as shown in front figure. `3` is corresponding to `3` anchors for each grid cell. `5` is consistent with `[x, y ,w ,h , c]`. `80` is coco 80 classes.

Am I understanding this correctly?

**Comment by glenn-jocher** [comment]
No. YOLOv5 outputs are 85 long and are [xywh obj cls(80)]

**Comment by glenn-jocher** [comment]
@Whisht 255 is just 3x85, where 85 is explained above and each output layer has 3 anchors.

**Comment by Whisht** [comment]
Thanks for you reply. In conclusion, `255 = 3 * 85 = 3 * (5 + 80)`.

> @Whisht 255 is just 3x85, where 85 is explained above and each output layer has 3 anchors.
