### ISSUE TITLE
testing Accuracy

### ISSUE THREAD

**Issue by Mrinh212375** [ultralytics/yolov5#10261]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have trained yolov5 with the custom dataset FOD_A and some of the images that I've clicked(combined), Now I'm testing on both test set of FOD_A and test set of real images by me.
P.S - Test set is nothing but from train-Val-test split.

1. Is there any accuracy metrics that we can measure while detecting on test dataset?
2. My main objective is detection, not the classification as of now, so is there any possibility to measure the detection accuracy, e.g - Out of 3378 images (from FOD_A), only 3361 images are being detected, So can I say my detection accuracy is 3361/3378 * 100. 

All images have only one object, as of now I want this experiment to be on single classification.

**Comment by glenn-jocher** [comment]
@Mrinh212375 if your data.yaml provides a test set you can run with:
```
python val.py --task test  # default --task val
```

**Comment by absmahi01** [comment]
!python val.py --data data.yaml --task test

I found this error
val: data=/content/drive/MyDrive/wrong-way-vehicle-detection-main/yolov5/data/data.yaml, weights=yolov5s.pt, batch_size=32, imgsz=640, conf_thres=0.001, iou_thres=0.6, task=test, device=, workers=8, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=runs/val, name=exp, exist_ok=False, half=False, dnn=False
YOLOv5 🚀 2023-4-9 Python-3.9.16 torch-2.0.0+cu118 CUDA:0 (Tesla T4, 15102MiB)

Fusing layers... 
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients
Traceback (most recent call last):
  File "/content/drive/MyDrive/wrong-way-vehicle-detection-main/yolov5/val.py", line 394, in <module>
    main(opt)
  File "/content/drive/MyDrive/wrong-way-vehicle-detection-main/yolov5/val.py", line 367, in main
    run(**vars(opt))
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/drive/MyDrive/wrong-way-vehicle-detection-main/yolov5/val.py", line 167, in run
    assert ncm == nc, f'{weights[0]} ({ncm} classes) trained on different --data than what you passed ({nc} ' \
TypeError: 'PosixPath' object is not subscriptable

**Comment by glenn-jocher** [comment]
@absmahi01 it looks like there may be a configuration error with the `--data` argument. Could you please ensure that `data.yaml` is providing the correct configuration for your test set and ensure that the paths are correct?
