### ISSUE TITLE
About data augmentation

### ISSUE THREAD

**Issue by ampelmannn** [ultralytics/yolov5#10265]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Thanks to your github as you commented, i used YOLOv5s with cutout data augmentation. but i would like to put 'cutout box' in the ground truth bounding box by using cutout or (object-aware) random erase. How can I do?

**Comment by glenn-jocher** [comment]
@ampelmannn just uncomment this section in the trainloader to use cutout augmentation:
https://github.com/ultralytics/yolov5/blob/7398d2d77cbac9f66259926d49c26bfa3c257a9b/utils/dataloaders.py#L710-L713

You can import cutout() from utils.augmentation

**Comment by ampelmannn** [comment]
@glenn-jocher so, how can I use cutout augmentation inside bounding box?

**Comment by glenn-jocher** [comment]
@ampelmannn already explained in https://github.com/ultralytics/yolov5/issues/10265#issuecomment-1325025903

**Comment by glenn-jocher** [comment]
@ampelmannn you can customize the cutout function to suit your needs in utils/augmentations.py

**Comment by ampelmannn** [comment]
@glenn-jocher I don't know how to approach the utils/augmentations.py. Could you give me an advice about it..!?

**Comment by glenn-jocher** [comment]
@ampelmannn see https://github.com/ultralytics/yolov5/blob/master/utils/augmentations.py
