### ISSUE TITLE
/yolov5/detect.py", line 158, in run     s += f"{n} {names[int(c)]}{'s' * (n > 1)}, "  # add to string KeyError: 94

### ISSUE THREAD

**Issue by lucasjinreal** [ultralytics/yolov5#10277]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

python detect.py --weights ~/Downloads/yolov5s-seg.pt

got

### Environment

YOLOv5 🚀 v7.0-4-g7398d2d Python-3.10.6 torch-1.14.0.dev20221107 CPU

### Additional

yolov5/detect.py", line 158, in run
    s += f"{n} {names[int(c)]}{'s' * (n > 1)}, "  # add to string
KeyError: 94

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@jinfagang see README for Segmentation Usage examples. In your case instead of python detect.py you want to run python segment/predict.py:

```bash
python segment/predict.py --weights yolov5s-seg.pt
```

**Comment by jinfagang** [comment]
@glenn-jocher  thank u.

I exported yolov5-seg to onnx, do u know why there is a Mul op here?

<img width="261" alt="image" src="https://user-images.githubusercontent.com/21303438/203979849-632afec6-d2cf-4e75-b221-4b7fe11e7ccc.png">

**Comment by glenn-jocher** [comment]
Yes these are multiplications that are part of the activations.
