### ISSUE TITLE
“--cache” couldn't allcates enough RAM sometimes 

### ISSUE THREAD

**Issue by colchicinewf** [ultralytics/yolov5#10276]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

my data ： 431K images
my RAM：421.5/503.5GB available

1. When I train my dataset using

`
python train.py --img 416 --batch 64 --epochs 1 --data mydata.yaml --weights yolov5n.pt --cache --evolve
`
it require 208.7GB RAM,but it can only use about 35GB RAM,then
`cv2.error: OpenCV(4.6.0) /io/opencv/modules/core/src/alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 4672512 bytes in function 'OutOfMemoryError'
`  
so i debug the code, I could't allocate a little ram using the command ` numpy.zeros((1000,1000)) ` just before it break off。
2.  I try to use the by the commond

`python train.py --img 640 --batch 128 --epochs 1 --data bdd100k.yaml --weights yolov5s.pt --cache --evolve`
it can load the images successful.

3. I train my data using different image size ,and the situation is
<html>
<body>
<!DOCTYPE html>

img_size | RAM used | require | RAM free | RAM all
-- | -- | -- | -- | --
320 | OK | 123.5 |   |  
352 | 25.4 | 149.4 |   |  
384 | OK | 177.8 |   |  
416 | 35 | 208.7 | 417 | 503.5
448 | 40 | 242 |   |  
480 | 46.1 | 277.8 |   |  
512 | 53.9 | 316.1 |   |  
544 | OK | 356.8 |   |  

</body>
</html>
some can load succussful,but some couldn't，and used/require is about 17% in all aborted situations 。
I couldn't find the reason。

### Environment

- YOLO: YOLOv5 🚀 v6.0-67-[7398d2d] torch 1.12.1+cu102 CUDA Version: 11.2 (Tesla V100 PCIe 32GB)
- OS: Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-42-generic x86_64)
- Python: Python 3.8.13 (default, Mar 28 2022, 11:38:47)
                [GCC 7.5.0] :: Anaconda, Inc. on linux

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@colchicinewf yes larger --imgsz arguments will use more RAM for caching. The caching code is here, if you see any improvements we could make please submit a PR, thank you!

https://github.com/ultralytics/yolov5/blob/7398d2d77cbac9f66259926d49c26bfa3c257a9b/utils/dataloaders.py#L566-L585

**Comment by colchicinewf** [comment]
@glenn-jocher what i confused is that why some --imgsz couldn't load images successful even though the ram is enough.

**Comment by glenn-jocher** [comment]
@colchicinewf I'm not sure, but for very large datasets perhaps disk caching is more suitable with --cache disk. This also allows multiple GPUs to train from the same disk cached dataset.

**Comment by glenn-jocher** [comment]
@colchicinewf also as I said previously, I've pointed you to the code, take a look yourself.
