### ISSUE TITLE
how do I constrain the instance segmentation to a bounding box and not the whole image

### ISSUE THREAD

**Issue by nikky4D** [ultralytics/yolov5#10270]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want ot do inference with the yolo segmentation model, yolov5 v7. How would I send in crops of an image, rather than a whole image with the dataloader in segment/predict.py? The crops are not of the same shape.

### Additional

I want to constrain the segmentation model to not look everywhere on the image but only in the places of the bounding box

**Comment by glenn-jocher** [comment]
@nikky4D you can crop a region using a tool like cv2/numpy and then simply pass that crop to your model for inference.

**Comment by nikky4D** [comment]
Thanks. I do this already. But I still get box predictions back. Is it possible to turn off box predictions and just get mask since I already know where the human is in the image? This would save processing time on my prediction

> @nikky4D you can crop a region using a tool like cv2/numpy and then simply pass that crop to your model for inference.

**Comment by glenn-jocher** [comment]
@nikky4D no, as the boxes are used to constrain the mask construction to exist only within the box.

**Comment by nikky4D** [comment]
Thanks

**Comment by glenn-jocher** [comment]
@nikky4D you're welcome! If you have any more questions or need further assistance, feel free to ask.
