### ISSUE TITLE
Do the segmentation masks have to undergo the same augmentation as the image and bounding box?

### ISSUE THREAD

**Issue by Tlx2208** [ultralytics/yolov5#10273]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

In the file utils/segment/dataloaders.py, the comment says the augmentation that won't change boxes and masks. However there are RandomResizedCrop in the Albumentations class. Will the masks still be projected correctly onto the images in this case?

Code snippet from utils/segment/dataloaders.py
`

        if self.augment:
            # Albumentations
            # there are some augmentation that won't change boxes and masks,
            # so just be it for now.
            img, labels = self.albumentations(img, labels)
            nl = len(labels)  # update after albumentations
`

Code snippet from utils/augmentations.py
`

            T = [
                A.RandomResizedCrop(height=size, width=size, scale=(0.8, 1.0), ratio=(0.9, 1.11), p=0.0),
                A.Blur(p=0.01),
                A.MedianBlur(p=0.01),
                A.ToGray(p=0.01),
                A.CLAHE(p=0.01),
                A.RandomBrightnessContrast(p=0.0),
                A.RandomGamma(p=0.0),
                A.ImageCompression(quality_lower=75, p=0.0)]  # transforms

`

**Comment by glenn-jocher** [comment]
@Tlx2208 yes masks and boxes undergo the same augmentations. You can visualize your augmented masks in your mosaic jpgs. If you see any issues with your mosaic jps please let us know.

![image](https://user-images.githubusercontent.com/26833433/204073450-9a8331a4-6781-4f37-a512-242e843cf872.png)

**Comment by quocnhat** [comment]
![image](https://user-images.githubusercontent.com/19263564/209274231-8ebcd573-e368-4b67-b8b0-8d61e935eb4d.png)
Hi, thanks for your work.
 It seems scale augmentation for mask is not working properly, If augment=False, the mask fits with the object correctly. Does anyone have any idea?

**Comment by Tlx2208** [comment]
@quocnhat Hi, I realised that I have misunderstood the code when I raised this issue. If you take a look at the code snippet that I have posted, the p (probability) for A.RandomResizedCrop was actually set to 0 by default and thus should not affect the mask or bounding box alignment with the images. Can you try to check this section of your code whether the p has been set to 0 as well? Thank you.
