### ISSUE TITLE
How to handle with the object with a fixed ratio?

### ISSUE THREAD

**Issue by youyuge34** [ultralytics/yolov5#10271]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

In my dataset, there is a class of objects  which always have the same ratio (e.g., size ratio of football is always 1:1). But I found the predicted result are not satisfied.  How to limit the object ratio into a fixed value during training?  Should I add another loss and how to modify the `ComputeLoss` easily?

**Comment by glenn-jocher** [comment]
@youyuge34 you can customize loss in utils/loss.py if you'd like.
