### ISSUE TITLE
How do I get Dice and MIOU in the semantic segmentation task

### ISSUE THREAD

**Issue by JoeNan1** [ultralytics/yolov5#10278]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Dice and MIOU are very important indicators in semantic segmentation tasks. But yolov5 does not show these indicators.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@JoeNan1 could this be because we are only doing instance segmentation? If not can you please take a look at segment/val.py to see if you could add those there in a PR?
