### ISSUE TITLE
how to crop images after detection in yolov5s 

### ISSUE THREAD

**Issue by harshmgoyal** [ultralytics/yolov5#1028]
## ❔Question
how to take out coordinates of bounding box image after detection ? or is there any other method to crop ?

**Comment by cjsLindquist** [comment]
Setting the '--save-txt' argument on detect.py will output the bounding box locations and classes into /inference/output/ with one file per image.
You can simply read in these files and crop the bboxes out of the appropriate images or video frames using OpenCV etc.

**Comment by shiv-acharii** [comment]
https://github.com/ultralytics/yolov5/issues/2608#issuecomment-809094537

U can refer to my reply in the above link.

**Comment by burhr2** [comment]
Hi! have added the saving option of the detected objects which will be in project/name/cropped when using detect.py. I have made a PR to this repo but you can check the changes in my folk [yolov5](https://github.com/Ab-Abdurrahman/yolov5)

**Comment by glenn-jocher** [comment]
@harshmgoyal @cjsLindquist Prediction box cropping is now available in YOLOv5 via PR https://github.com/ultralytics/yolov5/pull/2827! PyTorch Hub models can use `results.crop()` or detect.py can be called with the `--save-crop` argument. Example usage:
```
python detect.py --save-crop
```
<img width="1121" alt="Screenshot 2021-04-20 at 23 50 51" src="https://user-images.githubusercontent.com/26833433/115468484-70892500-a233-11eb-89e8-717bef0fa45b.png">

**Comment by Kyohei-Yoshihara** [comment]
I have a question. When I run that code `python detect.py --save-crop`
on Google Colab, it only saves a maximum of two images per class per image. I would like to get all the cropped images detected, is there any way to do that?

**Comment by bachimanchiajay** [comment]
How to extract text from the --save-crop images having multiple classes will be saving the images in a crop folder i need the text as well for that specific cropped image can anyone help me how we can do that.

**Comment by glenn-jocher** [comment]
@bachimanchiajay 👋 Hello! Thanks for asking about **cropping results** with YOLOv5 🚀.  Cropping bounding box detections can be useful for training classification models on box contents for example. This feature was added in PR https://github.com/ultralytics/yolov5/pull/2827. You can crop detections using either detect.py or YOLOv5 PyTorch Hub:

## detect.py
Crops will be saved under `runs/detect/exp/crops`, with a directory for each class detected.
```bash
python detect.py --save-crop
```
<img width="450" alt="Original" src="https://user-images.githubusercontent.com/26833433/139577918-65cc8f5d-741d-4a88-8753-0154013c624d.jpg">

<img width="1067" alt="Crop" src="https://user-images.githubusercontent.com/26833433/139577896-aa26b07c-466d-4057-9bfe-b01b56007587.png">

## YOLOv5 PyTorch Hub
Crops will be saved under `runs/detect/exp/crops` if `save=True`, and also returned as a dictionary with crops as numpy arrays.
```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, custom

# Images
img = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, PIL, OpenCV, numpy, list

# Inference
results = model(img)

# Results
crops = results.crop(save=True) 
# -- or --
crops = results.crop(save=True, save_dir='runs/detect/exp')  # specify save dir
```

Good luck 🍀 and let us know if you have any other questions!

**Comment by bachimanchiajay** [comment]
I can able to see the cropped results but i have to extract text from the
cropped images before cropping i have to pass these predicted coordina To
the textract for ocr.

**Comment by gobspn** [comment]
Can I change the file extension from .jpg to .png before used '--save-crop'.

**Comment by glenn-jocher** [comment]
@gobspn hello! Yes, you can change the file extension from .jpg to .png before using '--save-crop' in detect.py or `results.crop(save=True)` in YOLOv5 PyTorch Hub. The saved cropped images will also have the same file extension as the input images.
