### ISSUE TITLE
t = tuple(x / seen * 1E3 for x in dt)  # speeds per image ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by IAGirl-dev** [ultralytics/yolov5#10282]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

Hello, am trying to run the detection on a bunch of images on a model that I pretriend on the YOLOV5 coco dataset, and for that I use a text file where i put all my images path, this method use to work , and I already used it with the model that i created but for some reason i can't seem to work right know, however when i run the detection on a single image it works.
I receive this warrning so I tried to changed my Connection, tried to run it on the cmd as an administrator but nothing changed.
the images are all of the same size and the same type( all of them a .jpg)
I also tried passing a list using glob but it didn't workout.

detect: weights=..\..\yolov5-master\yolov5s.pt, source=H:/Dataset_img/TEST/imagesFinales.txt, data=..\..\yolov5-master\data\coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=True, save_conf=False, save_crop=False, nosave=True, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=H:/Dataset_img_floues/TEST, name=flou_imgs, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False
YOLOv5  2022-10-21 Python-3.9.8 torch-1.12.0+cu116 CUDA:0 (NVIDIA GeForce GTX 1070, 8192MiB)

Fusing layers...
Model summary: 213 layers, 7012822 parameters, 0 gradients, 15.8 GFLOPs
1/1: H:/Dataset_img_floues/TEST/20181207123001.jpg...  Success (1 frames 4260x1534 at 25.00 FPS)

WARNING: Video stream unresponsive, please check your IP camera connection. 

t = tuple(x / seen * 1E3 for x in dt)  # speeds per image
  File "......\yolov5-master\detect.py", line 207, in <genexpr>
    t = tuple(x / seen * 1E3 for x in dt)  # speeds per image
ZeroDivisionError: float division by zero

### Minimal Reproducible Example

python C:\yolov5-master\detect.py --source H:/Dataset/images.txt --save-txt --nosave --project H:/Dataset/TEST --name imgsDet

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@IAGirl-dev the issue is with your stream addresses. The error simply appears because it can not connect to your streams. There is no bug and no action for us to take.
