### ISSUE TITLE
Passing --img-size [train_size, test_size]

### ISSUE THREAD

**Issue by klock18** [ultralytics/yolov5#1029]
Hi!

I have tried every variation of passing --img-size [train_size, test_size] but get:

train.py: error: argument --img-size: invalid int value: "['640', '640']"

I want to train on one sized image and test on another to compare this to training on full sized images.

**Comment by NanoCode012** [comment]
Hi @klock18 , I think you pass like this `--img-size 640 640`  You separate by space.

**Comment by klock18** [comment]
Ah awesome thanks a lot! The only one I didn't try
