### ISSUE TITLE
30 classes only 18 are shown on the model summary 

### ISSUE THREAD

**Issue by K4elthaz** [ultralytics/yolov5#10295]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How can I fix this type of problem its not that big an issue but in summary, only 18 classes are displayed also in the runs folder only 18 of them are in the picture of the graph. Is there a way that I can get more batches.jpg on the output which is in "runs/exp" because every time I train i only get trainbatch.jpg 0-2 and valbatch.jpg (0,0,1,1,2,2) and when I view it some pictures of the train image are only shown or is it just normal?

**Comment by glenn-jocher** [comment]
@K4elthaz if val.py is missing metrics for certain classes it's because you have no labelled data for those classes.

**Comment by K4elthaz** [comment]
Mr.Glenn-jocher is it possible to incorporate google text to speech into this project? for me to get a voice output in every detection or when run on --source 0

**Comment by K4elthaz** [comment]
@glenn-jocher 
what must be the problem with this, when i deleted those data that have values and re train those data with 0 val then all of them have values its just that I have 30 classes and only 18 are being read but when i remove those 18 classes that are trained, those classes that retained gains value. is there a limit when it comes to training of data? i tried 3000 epochs --patience 0 still the same. Also there are errors in the prediction its like the train image with labels is read with different class name. do i need to create folders in the labels folder for every specific class name?
![image](https://user-images.githubusercontent.com/93974468/204404280-617151ed-26f5-4d2b-a0f2-8ee84ede4da0.png)
![image](https://user-images.githubusercontent.com/93974468/204404412-e5418ff2-d424-4e48-b451-55fbd04f3c3e.png)
![image](https://user-images.githubusercontent.com/93974468/204405217-4de3abc4-2dd8-4636-a975-1498b3ecd88b.png)

**Comment by glenn-jocher** [comment]
@K4elthaz the classes missing from the val results and confusion matrix have no labels in your val set. Without labels there can be no metrics.
