### ISSUE TITLE
Comet Bug: Unable to train on Window 11

### ISSUE THREAD

**Issue by telemac73** [ultralytics/yolov5#10301]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am unable to train alway the same error:

python train.py --img 640 --batch 16 --epochs 5 --data dataset.yaml --weights yolov5s.pt
train: weights=yolov5s.pt, cfg=, data=dataset.yaml, hyp=data\hyps\hyp.scratch-low.yaml, epochs=5, batch_size=16, imgsz=640, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, noplots=False, evolve=None, bucket=, cache=None, image_weights=False, device=, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=8, project=runs\train, name=exp, exist_ok=False, quad=False, cos_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, seed=0, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest
github: skipping check (not a git repository), for updates see https://github.com/ultralytics/yolov5
YOLOv5  2022-11-26 Python-3.9.13 torch-1.13.0+cpu CPU

hyperparameters: lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0
ClearML: run 'pip install clearml' to automatically track, visualize and remotely train YOLOv5  in ClearML
TensorBoard: Start with 'tensorboard --logdir runs\train', view at http://localhost:6006/
COMET WARNING: Comet credentials have not been set. Comet will default to offline logging. Please set your credentials to enable online logging.
COMET WARNING: Comet has disabled auto-logging functionality as it has been imported after the following ML modules: tensorboard, torch. Metrics and hyperparameters can still be logged using comet_ml.log_metrics() and comet_ml.log_parameters()
COMET INFO: Using 'C:\\Users\\telem\\Desktop\\Yolo\\.cometml-runs' path as offline directory. Pass 'offline_directory' parameter into constructor or set the 'COMET_OFFLINE_DIRECTORY' environment variable to manually choose where to store offline experiment archives.
COMET WARNING: Native output logging mode is not available, falling back to basic output logging
Traceback (most recent call last):
  File "C:\Users\telem\Desktop\Yolo\train.py", line 633, in <module>
    main(opt)
  File "C:\Users\telem\Desktop\Yolo\train.py", line 527, in main
    train(opt.hyp, opt, device, callbacks)
  File "C:\Users\telem\Desktop\Yolo\train.py", line 95, in train
    loggers = Loggers(save_dir, weights, opt, hyp, LOGGER)  # loggers instance
  File "C:\Users\telem\Desktop\Yolo\utils\loggers\__init__.py", line 132, in __init__
    self.comet_logger = CometLogger(self.opt, self.hyp)
  File "C:\Users\telem\Desktop\Yolo\utils\loggers\comet\__init__.py", line 97, in __init__
    self.data_dict = self.check_dataset(self.opt.data)
  File "C:\Users\telem\Desktop\Yolo\utils\loggers\comet\__init__.py", line 234, in check_dataset
    if data_config['path'].startswith(COMET_PREFIX):
KeyError: 'path'
COMET INFO: ----------------------------------
COMET INFO: Comet.ml OfflineExperiment Summary
COMET INFO: ----------------------------------
COMET INFO:   Data:
COMET INFO:     display_summary_level : 1
COMET INFO:     url                   : [OfflineExperiment will get URL after upload]
COMET INFO:   Others:
COMET INFO:     offline_experiment : True
COMET INFO:   Uploads:
COMET INFO:     environment details : 1
COMET INFO:     installed packages  : 1
COMET INFO: ----------------------------------
COMET WARNING: Experiment Name is generated at upload time for Offline Experiments unless set explicitly with Experiment.set_name
COMET WARNING: Comet has disabled auto-logging functionality as it has been imported after the following ML modules: tensorboard, torch. Metrics and hyperparameters can still be logged using comet_ml.log_metrics() and comet_ml.log_parameters()
COMET INFO: Still saving offline stats to messages file before program termination (may take up to 120 seconds)
COMET INFO: Starting saving the offline archive
COMET INFO: To upload this offline experiment, run:
    comet upload C:\Users\telem\Desktop\Yolo\.cometml-runs\5f05924ec89f489db0356c7c3201ce0f.zip

I have tested many dataset and alway the same error any advice ?

**Comment by glenn-jocher** [comment]
@telemac73 seems to be Comet related. Try pip uninstall comet and rerun your command.

@DN6 can you take a look at this Comet-related bug above? Thanks!!

**Comment by telemac73** [comment]
pip uninstall comet-ml

have been fixed my issue Thanks )

**Comment by HanBinGer** [comment]
same problem with comet_ml,but then how to properly link to comet

**Comment by glenn-jocher** [comment]
@DN6 can you take a look at this error that users are seeing with Comet?

**Comment by glenn-jocher** [comment]
@HanBinGer can you help us by providing a minimum reproducible example of your error? Thanks!

**Comment by HanBinGer** [comment]
@glenn-jocher 
So, I tried both on my personal PC and in the example of the Collab. The same problem is everywhere. 
Comet initialization is successful.

Collab steps:
![image](https://user-images.githubusercontent.com/35628064/205402752-c0761a83-f209-4c31-b87f-ecfe190be1f0.png)
![image](https://user-images.githubusercontent.com/35628064/205402794-edb50abb-ac55-43a6-8a4e-2629e2526347.png)
![image](https://user-images.githubusercontent.com/35628064/205402885-8f7cc433-3b0b-441c-a13f-ac937f05d45c.png)

and when I try to start a train:
![image](https://user-images.githubusercontent.com/35628064/205403011-f82c1995-783e-486c-bc36-248c8fb18186.png)

Then I get this:

train: weights=/content/yolov5/best.pt, cfg=, data=/content/yolov5/FirstTry-1/data.yaml, hyp=data/hyps/hyp.scratch-low.yaml, epochs=3, batch_size=16, imgsz=640, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, noplots=False, evolve=None, bucket=, cache=ram, image_weights=False, device=, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=8, project=runs/train, name=exp, exist_ok=False, quad=False, cos_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, seed=0, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest
github: up to date with https://github.com/ultralytics/yolov5 ✅
YOLOv5 🚀 v7.0-21-ga1b6e79 Python-3.8.15 torch-1.12.1+cu113 CUDA:0 (Tesla T4, 15110MiB)

hyperparameters: lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0
ClearML: run 'pip install clearml' to automatically track, visualize and remotely train YOLOv5 🚀 in ClearML
TensorBoard: Start with 'tensorboard --logdir runs/train', view at http://localhost:6006/
COMET WARNING: Comet has disabled auto-logging functionality as it has been imported after the following ML modules: torch, tensorboard. Metrics and hyperparameters can still be logged using comet_ml.log_metrics() and comet_ml.log_parameters()
COMET ERROR: Failed to calculate active processors count. Fall back to default CPU count 1
COMET INFO: Experiment is live on comet.com https://www.comet.com/...

Traceback (most recent call last):
  File "train.py", line 633, in <module>
    main(opt)
  File "train.py", line 527, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 95, in train
    loggers = Loggers(save_dir, weights, opt, hyp, LOGGER)  # loggers instance
  File "/content/yolov5/utils/loggers/__init__.py", line 139, in __init__
    self.comet_logger = CometLogger(self.opt, self.hyp)
  File "/content/yolov5/utils/loggers/comet/__init__.py", line 97, in __init__
    self.data_dict = self.check_dataset(self.opt.data)
  File "/content/yolov5/utils/loggers/comet/__init__.py", line 234, in check_dataset
    if data_config['path'].startswith(COMET_PREFIX):
KeyError: 'path'
COMET INFO: ---------------------------
COMET INFO: Comet.ml Experiment Summary
COMET INFO: ---------------------------
COMET INFO:   Data:
COMET INFO:     display_summary_level : 1
COMET INFO:     url                   : https://www.comet.com/...
COMET INFO:   Uploads:
COMET INFO:     environment details : 1
COMET INFO:     installed packages  : 1
COMET INFO:     os packages         : 1
COMET INFO: ---------------------------
COMET WARNING: Comet has disabled auto-logging functionality as it has been imported after the following ML modules: torch, tensorboard. Metrics and hyperparameters can still be logged using comet_ml.log_metrics() and comet_ml.log_parameters()
COMET INFO: Uploading metrics, params, and assets to Comet before program termination (may take several seconds)
COMET INFO: The Python SDK has 3600 seconds to finish before aborting...
COMET INFO: Uploading 1 metrics, params and output messages

**Comment by DN6** [comment]
Hi @HanBinGer. Would you be able to share the contents of your `data.yml` file here?

**Comment by HanBinGer** [comment]
Hi @DN6. This file was automatically generated by Roboflow. Do you think that the problem may be in the paths specified in it?

data.yaml:


`names:`
`- I`
`- cursor`
`- enemymark`
`- mark`
`- scale`
`- squad`
`- trash`
`nc: 7`
`roboflow:`
`  license: Public Domain`
`  project: firsttry-ra06x`
`  url: https://universe.roboflow.com/...`
` version: 1`
`  workspace: wtrecognition`
`test: FirstTry-1/test/images`
`train: FirstTry-1/train/images`
`val: FirstTry-1/valid/images`

**Comment by glenn-jocher** [comment]
@DN6 thanks for taking a look!

**Comment by DN6** [comment]
Hi @HanBinGer, the Comet integration expects the `data.yml` file to have a path variable defined that points to the root directory of your dataset. This is following the [dataset formatting guidelines from the YOLOv5 docs](https://docs.ultralytics.com/tutorials/train-custom-datasets/). 

Would it be possible to structure your `data.yml` file in the following way? 

```
# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list:[path/to/imgs1, path/to/imgs2, ..]

path: ../datasets/coco128  # dataset root dir
train: images/train2017  # train images (relative to 'path') 128 images
val: images/train2017  # val images (relative to 'path') 128 images
test:  # test images (optional)

# Classes (80 COCO classes)
names:
  0: person
  1: bicycle
  2: car
  ...
  77: teddy bear
  78: hair drier
  79: toothbrush
```

**Comment by DN6** [comment]
I'll make a PR next week to update the guide @glenn-jocher @HanBinGer

**Comment by glenn-jocher** [comment]
@DN6 great, yes please do!
