### ISSUE TITLE
Can the detection run on multiple cores?

### ISSUE THREAD

**Issue by MasIgor** [ultralytics/yolov5#10319]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello all!

My pc has 4 cores, and I noticed that during inference the CPU load is around 35%.. 10% is base load, and 25% get added by YoloV5.
Is there a way to speed up detection by splitting the load over multiple cores? I searched around here but was not able to find any parameter to set.

Thank you!

Best regards

Igor

**Comment by Zephyr69** [comment]
You can. But in most cases, without modifying hardware, you will get a significant slow down; this is mainly due to limitations of python and pytorch.

**Comment by tanzerlana** [comment]
@Zephyr69 very clear, thank you
another quick question. I noticed that if I reduce the core count from 4 to 2 on my machine, then the detection slows down by 30% approx. any idea why, if it only uses 1 core anyway?
