### ISSUE TITLE
what does  pred = model(im, augment=False, visualize=False) do?

### ISSUE THREAD

**Issue by MasIgor** [ultralytics/yolov5#10318]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello all!

I am trying to understand what this line of code does:

  pred = model(im, augment=False, visualize=False)

i THINK it actually does the inference. but I am not sure about that.

reason for this is that in my code I pre-load two networks, and then run them both on the same image one after the other by passing the appropriate model to the run function that is inside the detect.py file.. (the load network part has been extracted and runs once at startup of the program, and then passes the correct model() to the run function so I do not have to load the model each time. this all works and I am more than happy with it.
 
The first model has 50 classes, the seocnd one just 2. 

the first one executes above row in about 70 ms, the second one takes about 130 ms to run this line. all the rest of the code is quite constant and ok, only this line is having these huge time jumps from the first to the second model.
given that it is the same image, and same network type/size, and the second network has much less classes, shouldn't the second one run at least as fast as the first one?

any help on understanding what this line is doing and what might be taking so long is very welcome.

Best regards

Igor

**Comment by glenn-jocher** [comment]
@tanzerlana CUDA inference will be slow on a first pass, so I'd profile after a few warmup images.
