### ISSUE TITLE
How to just change the weight values in yolov5.pt and keep the original structure of the pt file.

### ISSUE THREAD

**Issue by 1ofvc** [ultralytics/yolov5#10311]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to just change the weight values in yolov5.pt and guarantee that the updated pt file (yolov'.pt) has the same structure as yolov5.pt to ensure that the new yolov'.pt can be used for detect.py.
![image](https://user-images.githubusercontent.com/80811136/204138857-b56cb32f-0bcd-4f5a-842d-e93fbd6db1d8.png)

For example, the weights of a layer of the network can be adjusted to the following weight values and saved to the new pt file.

**Comment by 1ofvc** [comment]
![image](https://user-images.githubusercontent.com/80811136/205849566-e0f25787-67c1-4e48-9269-cf655cbd5d68.png)
![image](https://user-images.githubusercontent.com/80811136/205849699-047285a2-f923-4182-abf9-846961ac3aed.png)
![image](https://user-images.githubusercontent.com/80811136/205849851-392a93b2-9b93-46fd-b058-917ff44447c5.png)
getModelState method is used to getModel from exist pytorch-yolo-weight file(.pt). And then I add noise to the yolo model parameter value, finally save the new yolo weight file. 
But the problem is that even though I don't add noise and just take out the content of the original pt file and save it to a new pt file, when I run detect.py, the result can be very, very bad. 
The problem should be in the network reading part, but I am referring to the method in train.py. Please help me out, thank you!

**Comment by glenn-jocher** [comment]
@1ofvc it seems like the issue might be related to the process of saving and loading the modified YOLOv5 weights. Without more information about the exact steps and code used, it's a bit difficult to provide a precise solution.

In general, when modifying weights in a PyTorch model, it's important to ensure that the structure of the model remains unchanged. This includes the architecture of the neural network, as well as the shape and arrangement of the weights and biases.

One way to approach this would be to load the original YOLOv5 weights using `torch.load()`, make the necessary modifications to the specific weight tensors, and then save the modified state dictionary using `torch.save()`. It's important to maintain the same structure and arrangement of the state dictionary to ensure compatibility with the YOLOv5 codebase.

If the issue persists, double-checking the specific steps taken to modify and save the weights, along with any relevant code snippets, would be helpful in diagnosing the problem.

Additionally, the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/ provides extensive information on working with the YOLOv5 model and may be useful for troubleshooting.

Feel free to share more details or code snippets if you need further assistance!
