### ISSUE TITLE
YOLOv5 lazy loading technology

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#10328]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

@glenn-jocher 
I recently saw a technique called "lazy loading". I don't know if YOLOv5 uses this technique. If so, please give a few examples, thank you.

**Comment by glenn-jocher** [comment]
@Zengyf-CVer no we don't because not all torch modules support it yet. See torch docs, i.e. https://pytorch.org/docs/stable/generated/torch.nn.LazyConv2d.html?highlight=lazy#torch.nn.LazyConv2d

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
Thank you very much.

**Comment by glenn-jocher** [comment]
@Zengyf-CVer you're welcome! If you have any more questions, feel free to ask. Our team is here to help.
