### ISSUE TITLE
I want to use cuda with yolov5.

### ISSUE THREAD

**Issue by Heartful-echo** [ultralytics/yolov5#10329]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi

How would I use cuda in this example?
If cuda is available, will it automatically be used?

![2](https://user-images.githubusercontent.com/56055010/204427302-540ca9e4-d595-46b8-b1cb-fe43eb211c12.PNG)

**Comment by glenn-jocher** [comment]
@kazuya-uchida yes CUDA device 0 is automatically used if available. 

You can force a device manually as well, i.e. model.cuda() or model.cpu() etc.
