### ISSUE TITLE
Is there any plan to support RegNet?

### ISSUE THREAD

**Issue by AlphaGoMK** [ultralytics/yolov5#1032]
## ❔Question  
Are you going to support training RegNet as backbone?

**Comment by lucasjinreal** [comment]
@AlphaGoMK Does there any benifits for Regnet ?

**Comment by AlphaGoMK** [comment]
> @AlphaGoMK Does there any benifits for Regnet ?

As mentioned in the [paper](https://arxiv.org/abs/2003.13678), regnet outperform efficientnet on both top1 error and FLOPS.  
But Im not sure whether it will work on object detection task or not.

**Comment by Aktcob** [comment]
outperform on top1 does not mean outperform on Detection task

**Comment by AlphaGoMK** [comment]
> outperform on top1 does not mean outperform on Detection task

Agree.  
Im not sure about its effectiveness on detection task cuz the paper did not contain any results on coco dataset, that's why I opened this issue :)

**Comment by glenn-jocher** [comment]
It can be a long journey from a classification to detection, as you can see in the differences (and time elapsed) between the releases of efficientnet and efficientdet.
