### ISSUE TITLE
Annotation offline tool for yolov5 seg

### ISSUE THREAD

**Issue by rohitdileep** [ultralytics/yolov5#10320]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi , can anyone recommend offline annotation tools for yolov5 instance segmentation.

**Comment by ryouchinsa** [comment]
Hi, RectLabel is an offline image annotation tool for object detection and segmentation.
You can draw polygons and read/write/export in YOLO text format for YOLOv5 Instance Segmentation.
We have a free trial version, and although the trial is untimed.
https://rectlabel.com

Please give us your feedback about the combination of YOLOv5 and RectLabel.

**Comment by olibartfast** [comment]
Hi I'm using
https://github.com/wkentaro/labelme
However then you must implement a (python) script to convert from [Labelme json ](https://github.com/wkentaro/labelme/blob/main/examples/instance_segmentation/data_annotated/2011_000003.json) to Yolov5 segmentation txt format

**Comment by ryouchinsa** [comment]
How about combining 2 scripts?

1. Labelme JSON files to a COCO JSON file using labelme2coco.py
https://github.com/wkentaro/labelme/blob/main/examples/instance_segmentation/labelme2coco.py

2. A COCO JSON file to YOLO text files using general_json2yolo.py
https://github.com/ultralytics/JSON2YOLO/blob/master/general_json2yolo.py

[RectLabel](https://rectlabel.com) is an offline image annotation tool for object detection and segmentation.
Although this is not an open source program, with RectLabel you can read/write/export the YOLO segmentation format.
```
class_index x1 y1 x2 y2 x3 y3 ...
0 0.180027 0.287930 0.181324 0.280698 0.183726 0.270573 ...
```

![yolo_polygon](https://user-images.githubusercontent.com/1954306/209942647-fa9565e0-d4cf-42c2-a382-a8043465765b.jpg)

**Comment by mughal41** [comment]
@ryouchinsa  did u find the script for offline annotation?
@olibartfast  can u please specify which script you use? did u convert lableme annotations to coco and then to yolov5 format?

**Comment by olibartfast** [comment]
I did write  myself a script to convert from txt yolo coordinates to json labelme format  and backwards

**Comment by Addoxx** [comment]
Hi @olibartfast, I am trying to convert Yolo txt format to labelme JSON format but all the polygon values are normalized in Yolo txt format, and my segmentation masks end up as a small bunch of dots. How did you manage to invert the normalization? 

Looking forward to your reply.

Regards,
Adhok

**Comment by glenn-jocher** [comment]
Hi @Addoxx, when converting YOLO txt format to Labelme JSON format, you need to de-normalize the polygon coordinates to match the original image size. 

To invert the normalization, you can multiply the normalized polygon coordinates by the width and height of the image. This will bring the coordinates back to the original scale. 

Here's some sample code on how to de-normalize the polygon coordinates:

```python
# Assuming you have the normalized polygon coordinates in the variable 'polygon'
width, height = image_width, image_height  # Replace with the actual image width and height

denormalized_polygon = []
for x, y in polygon:
    denormalized_x = x * width
    denormalized_y = y * height
    denormalized_polygon.append([denormalized_x, denormalized_y])

# Use 'denormalized_polygon' in your conversion from YOLO to Labelme format
```

Make sure to replace 'image_width' and 'image_height' with the actual width and height of your image.

I hope this helps! Let me know if you have any further questions.

Regards,
Glenn Jocher

**Comment by Addoxx** [comment]
Glenn,

I was able to invert the normalization and project the coordinates on the original scale. Thanks a lot for your input! 

Cheers

**Comment by glenn-jocher** [comment]
@Addoxx glad to hear that you were able to successfully invert the normalization and project the coordinates on the original scale! You're welcome and I'm happy that I could assist you. 

If you have any more questions or need further assistance, feel free to ask. Cheers and happy coding!
