### ISSUE TITLE
How to convert Yolo Darknet txt to yolo v7 pytorch txt

### ISSUE THREAD

**Issue by Awader28** [ultralytics/yolov5#10321]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How do I convert Yolo Darknet Txt format to Yolo V7 Pytorch txt format

**Comment by glenn-jocher** [comment]
@Awader28 hi there! Converting YOLO Darknet txt to YOLO v7 PyTorch txt format is simple. You can use the `export.py` script in the YOLOv5 repo to achieve this. Simply follow the instructions in the [YOLOv5 documentation](https://docs.ultralytics.com/yolov5/) for exporting your YOLO Darknet labels to the desired YOLO v7 PyTorch txt format. Let me know if you need further assistance!
