### ISSUE TITLE
Second stage classifier

### ISSUE THREAD

**Issue by diego0718** [ultralytics/yolov5#1033]
Good morning for everyone i am new on object detection... In detect.py module i saw a second stage classifier but is set to false. Anyone has probe it? it has better inference results?

   # Second-stage classifier
    classify = False
    if classify:
        modelc = load_classifier(name='resnet101', n=2)  # initialize
        modelc.load_state_dict(torch.load('weights/resnet101.pt', map_location=device)['model'])  # load weights
        modelc.to(device).eval()

I am wondering if it is  "transfer learning" or something like that

**Comment by hcakmak7** [comment]
It's for using cropped image with any weight file you choose. Its something like you have photos with cars with plates, you first cropped plate and send it to second stage classifier to detect characters in it.

**Comment by diego0718** [comment]
Thank you  @hcakmak7 for the fast reply

**Comment by gizemtanriver** [comment]
I want to classify cropped images with a second stage classifier so this is actually very handy for me. But when I try to use this, I get the following error - though it is just for displaying model properties, so I can comment that bit. Also, where is the preprocessing (i.e. resizing of the cropped image etc) done for the second stage classifier?

```
def load_classifier(name='resnet101', n=2):
    # Loads a pretrained model reshaped to n-class output
    model = models.__dict__[name](pretrained=True)

    # Display model properties
    input_size = [3, 224, 224]
    input_space = 'RGB'
    input_range = [0, 1]
    mean = [0.485, 0.456, 0.406]
    std = [0.229, 0.224, 0.225]
    for x in [input_size, input_space, input_range, mean, std]:
        print(x + ' =', eval(x))
```

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-21-6a024289f80d> in <module>()
      5 std = [0.229, 0.224, 0.225]
      6 for x in [input_size, input_space, input_range, mean, std]:
----> 7     print(x + ' =', eval(x))

TypeError: can only concatenate list (not "str") to list

**Comment by hcakmak7** [comment]
Hello Gizem @gizemtanriver , the error is not related to the second stage classifier, it is because you tried to combine the string object with the list object.

**Comment by gizemtanriver** [comment]
Hi @hcakmak7, this is the load_classifier function from utils/torch_utils in the repo, so looks like it just needs a minor change to display model properties without throwing an error.

**Comment by glenn-jocher** [comment]
@gizemtanriver your code does not match master, suggest you update. 

In any case, second stage classification will take some work on your part, not least because you need to train and supply your own classifier.

**Comment by glenn-jocher** [comment]
@gizemtanriver to answer your other question, all padding and reshaping operations to classifier inputs are handled in the apply_classifier() function in utils/general.py.


```python
def apply_classifier(x, model, img, im0):
    # applies a second stage classifier to yolo outputs
    im0 = [im0] if isinstance(im0, np.ndarray) else im0
    for i, d in enumerate(x):  # per image
        if d is not None and len(d):
            d = d.clone()

            # Reshape and pad cutouts
            b = xyxy2xywh(d[:, :4])  # boxes
            b[:, 2:] = b[:, 2:].max(1)[0].unsqueeze(1)  # rectangle to square
            b[:, 2:] = b[:, 2:] * 1.3 + 30  # pad
            d[:, :4] = xywh2xyxy(b).long()

            # Rescale boxes from img_size to im0 size
            scale_coords(img.shape[2:], d[:, :4], im0[i].shape)

            # Classes
            pred_cls1 = d[:, 5].long()
            ims = []
            for j, a in enumerate(d):  # per item
                cutout = im0[i][int(a[1]):int(a[3]), int(a[0]):int(a[2])]
                im = cv2.resize(cutout, (224, 224))  # BGR
                # cv2.imwrite('test%i.jpg' % j, cutout)

                im = im[:, :, ::-1].transpose(2, 0, 1)  # BGR to RGB, to 3x416x416
                im = np.ascontiguousarray(im, dtype=np.float32)  # uint8 to float32
                im /= 255.0  # 0 - 255 to 0.0 - 1.0
                ims.append(im)

            pred_cls2 = model(torch.Tensor(ims).to(d.device)).argmax(1)  # classifier prediction
            x[i] = x[i][pred_cls1 == pred_cls2]  # retain matching class detections

    return x
```
