### ISSUE TITLE
Does Yolov5 automatically shuffle the dataset ? 

### ISSUE THREAD

**Issue by arconym1** [ultralytics/yolov5#10338]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Does Yolov5 randomly use a images for each epoch automatically ? 
Thanks for the answers !

**Comment by glenn-jocher** [comment]
@arconym1 dataset is shuffled by default, yes.
