### ISSUE TITLE
Can different data sets be used to train detection and segmentation tasks separately?

### ISSUE THREAD

**Issue by dky233** [ultralytics/yolov5#10339]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Can different data sets be used to train detection and segmentation tasks separately?If so, will the detection and segmentation prediction results be output on one image at the same time?

**Comment by dky233** [comment]
@glenn-jocher Thank you for your reply!

**Comment by glenn-jocher** [comment]
@dky233 you're welcome! Feel free to explore the Ultralytics Docs for more detailed information on using different datasets for training and how to output detection and segmentation prediction results on the same image. If you have any more questions, don't hesitate to ask. The YOLOv5 community is here to help!
