### ISSUE TITLE
Can we hide confidence levels on predicted image using model=torch.hub.load()?

### ISSUE THREAD

**Issue by chiragp012** [ultralytics/yolov5#10336]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

while using "python detect.py", we can hide the confidence level using flag --hide-conf

My question is, Can we do the same while using model=torch.hub.load() and then results=model(img). Once we write results.show(), I want only boxes with name of the classes on the image and want to hide confidence scores.

I have tried using,
model_damage_annot.conf=0.4
model_damage_annot.iou=0.15
model_damage_annot.max_det=20

This works but "model_damage_annot.hide_conf=True" doesn't work. What is the correct way to do it?

The resulting pictures are showing confidence scores and I want to hide them. Please guide me

Thankyou!

**Comment by chiragp012** [comment]
> @chiragp012
> 
> ```python
> results.render(labels=False)
> images = results.ims  # list of annotated images with boxes and no labels
> ```

Thanks for the reply. By using results.render(labels=False), Confidence level as well as labels are getting hide but I want labels to be shown on image and only want to hide **confidence level**. Please help

**Comment by glenn-jocher** [comment]
@chiragp012 The `results.print()` method can be used to print human-readable results, while `results.render()` offers visual rendering to display your results. You can hide only the confidence levels using the `results.render()` function by passing the `conf=0.0` argument.

```python
results.render(conf=0.0)
images = results.ims  # list of annotated images with boxes and labels
```

This will render the images with class labels but without displaying the confidence scores.
