### ISSUE TITLE
how about the yolov5 pose?

### ISSUE THREAD

**Issue by xinsuinizhuan** [ultralytics/yolov5#10332]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

need a pose

### Use case

need a pose

### Additional

need a pose

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@xinsuinizhuan If you'd like to submit PR, then please go ahead. Usually, adding a new task will be a complicated process. We'll need to benchmark, optimize and have other such discussions so it might take time to actually get it merged. But your PR could be the starting point.
