### ISSUE TITLE
reducing the model size using YOLOv5 

### ISSUE THREAD

**Issue by saeedadeeb103** [ultralytics/yolov5#10337]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I trained my custom dataset on yolov5 and used export.py to create the tflite model with --int8 but the file size reduced from 27 to 7.3 and i want to reduce the model size even more but i dont know how, i even tried to reduce the number of images in the dataset to half but the model size always at 27mb i still dont know why. if someone have any experience and can help i will be grateful.

**Comment by glenn-jocher** [comment]
@saeedadeeb103 model size is not correlated to dataset size. Smallest model is YOLOv5n, I'd train this size, i.e. `python train.py --weights yolov5n.pt`

**Comment by saeedadeeb103** [comment]
> @saeedadeeb103 model size is not correlated to dataset size. Smallest model is YOLOv5n, I'd train this size, i.e. `python train.py --weights yolov5n.pt`

i already trained the model using yolov5n but my model is size now is 1.9mb after --int8 quantization, is there any way i can get it smaller than this ?
