### ISSUE TITLE
How can I check the mAP and other metrics from the weight file?

### ISSUE THREAD

**Issue by blackShine-2** [ultralytics/yolov5#10346]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have a YOLOv5 weight file. I want to see the mAP, and other metrics of that file. What command should I run?

**Comment by JustasBart** [comment]
Hi, I can't really help much with this, but I suspect that it has something to do with the **val.py** I think you need to run your weights on your validation data with it but I'm not 100% sure in terms of what would it actually spit back out...

Perhaps give that a try until someone wiser gives you a more accurate answer?

**Comment by glenn-jocher** [comment]
@blackShine-2 see val.py Usage examples as @JustasBart mentioned:
https://github.com/ultralytics/yolov5/blob/7f5724ba4b3e421d4c9162742810c52248d06ecd/val.py#L3-L19
