### ISSUE TITLE
yolov5 does not implement an empty-labeled image reading training network.

### ISSUE THREAD

**Issue by gengyanlei** [ultralytics/yolov5#1034]

**Comment by haoyuefan** [comment]
> ## Question
> ## Additional context
I generate an empty txt file for each empty-labeled image. It works.

**Comment by glenn-jocher** [comment]
Empty text files or no text file both work for images without labels.

**Comment by gengyanlei** [comment]
Thank you for the answer, but when I trained the data, I added an image with an empty label.txt and reported an error. I tried it twice and thought it could not solve the problem of empty labels. I will try again.
