### ISSUE TITLE
Segmentation data format - relative to image width and height?

### ISSUE THREAD

**Issue by rusvagzur** [ultralytics/yolov5#10349]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi there,

I haven't quite clearly found in this repo whether the format for segmentation dataset:

`cls x1 y1 x2 y2 ...`

Do xy coordinates have to be relative to image size (float between 0 and 1) or absolute coordinate number?

Many thanks in advance!

**Comment by JustasBart** [comment]
Hi, YOLO formatting is based on relative coordinates within the range of (0.0 -> 1.0).

Example: 25 0.475759 0.414523 0.951518 0.672422

Hope that helps!

**Comment by rusvagzur** [comment]
Hi @JustasBart, thanks for stepping in, but as I mention in the question, I mean for segmentation (cls,x1,y1,x2,y2,...) and not bounding boxes (cls,x,y,w,h).

**Comment by glenn-jocher** [comment]
@rusvagzur all label coordinates are normalized, whether boxes or segments. See coco128-seg.yaml for an example segmentation dataset:

https://github.com/ultralytics/yolov5/blob/7f5724ba4b3e421d4c9162742810c52248d06ecd/segment/train.py#L3-L15

**Comment by fppccc** [comment]
45 0.782016 0.986521 0.937078 0.874167 0.957297 0.782021 0.950562 0.739333 0.825844 0.561792 0.714609 0.420229 0.657297 0.391021 0.608422 0.4 0.0303438 0.750562 0.0016875 0.811229 0.003375 0.889896 0.0320156 0.986521
45 0.557859 0.143813 0.487078 0.0314583 0.859547 0.00897917 0.985953 0.130333 0.984266 0.184271 0.930344 0.386521 0.80225 0.480896 0.763484 0.485396 0.684266 0.39775 0.670781 0.3955 0.679219 0.310104 0.642141 0.253937 0.561234 0.155063 0.559547 0.137083
Hi,One example like this.I guess it‘s C x1 y1 x2 y2...
I saw coco128-seg.yaml  and found:
# Download script/URL (optional)
download: https://ultralytics.com/assets/coco128-seg.zip

In coco128-seg.zip,I found the format for segmentation is different from it for object detection.

**Comment by JustasBart** [comment]
@rusvagzur My apologies, I didn't realise that the particular example that I gave you just so happened to have 4 points making it look like either a possible segmentation label or a bounding box...

Should have made it more obvious, I'm glad you've solved your problem though!
