### ISSUE TITLE
clearml logs defaults args when use run function 

### ISSUE THREAD

**Issue by mbenami** [ultralytics/yolov5#10341]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

when you want to run training with the `run` function as described here https://github.com/ultralytics/yolov5/blob/10c025d794ca395a2ca0b2a00aff65f3a92ecd8d/train.py#L622 
the clearml args logging 
https://github.com/allegroai/clearml/blob/7016138c849a4f8d0b4d296b319e0b23a1b7bd9e/clearml/binding/args.py#L231 
skip the modification of the parameters 
in the end, when you look in the clearml server on configurations Args you see the default args parameters and not the one you trained with 
(Training is still with the good parameters you pass )

### Environment

doker 
`from ultralytics/yolov5:latest`

### Minimal Reproducible Example

python
```
import train; train.run(data='coco128.yaml', imgsz=320, weights='yolov5m.pt')
```
in clearml server configurations Args you will see `weights='yolov5s.pt'` `imgsz=640`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@mbenami thanks for the bug report!

@thepycoder could you take a look at this? Thanks!
