### ISSUE TITLE
How many decimals are supported in label file?

### ISSUE THREAD

**Issue by MasIgor** [ultralytics/yolov5#10351]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi all!

Please excuse me for not testing this myself, but my training pc is busy for the next 5 days.

I was wondering, how many decimals are supported in the label file? is this for example a valid label file?

```
8 0.6101973684210527 0.6450497989766082 0.1889619883040935 0.24232456140350878
195 0.7898391812865497 0.3979737755847953 0.19590643274853814 0.2496345029239766
313 0.7989766081871343 0.6437705592105263 0.1842105263157895 0.24195906432748537
313 0.42269736842105265 0.6432223135964912 0.18676900584795325 0.24232456140350878
313 0.23793859649122803 0.6413948282163742 0.18494152046783624 0.24159356725146208
314 0.5771198830409356 0.3974255299707602 0.23830409356725152 0.2514619883040936
314 0.346125730994152 0.39468430190058473 0.2375730994152047 0.2510964912280701
314 0.11567982456140351 0.3928568165204679 0.23135964912280702 0.2510964912280702
```

Thank you for your support!

Best regards

**Comment by JustasBart** [comment]
Hi, looking at the coco dataset (https://www.kaggle.com/datasets/ultralytics/coco128) it appears to be **6 decimal places**.

Although I don't think that it really matters... Someone correct me if I'm wrong but I imagine that it just parses it into like a double or a float type and just uses it to map the rect coordinates onto the image...

Hope that helps!

**Comment by glenn-jocher** [comment]
@JustasBart hi there!

Thanks for reaching out. The label file format supports **up to 16 decimal places**. The detections are parsed as floats, so the level of precision shouldn't impact the mapping of coordinates onto the image.

Let me know if you need further assistance!
