### ISSUE TITLE
Extract just features of detected objet in image 

### ISSUE THREAD

**Issue by mboukir** [ultralytics/yolov5#10352]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to extract just the features that contributed to the detection of an object in an image?

I know that we can extract the features in all the layers of yolo, but my need is to have just the features of the detected object.

**Comment by glenn-jocher** [comment]
@boukir you'd have to customize Detect() to do this.
