### ISSUE TITLE
evolve crash when NaN value encountered 

### ISSUE THREAD

**Issue by mbenami** [ultralytics/yolov5#10357]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

error 
```
  File "/home/ubuntu/yolov5/utils/general.py", line 1045, in <genexpr>
    '\n' + '# ' + ', '.join(f'{x:>20.5g}' for x in data.values[i, :7]) + '\n\n')
ValueError: Unknown format code 'g' for object of type 'str'
```
in https://github.com/ultralytics/yolov5/blob/7f5724ba4b3e421d4c9162742810c52248d06ecd/utils/general.py#L1045
When running train.py with `--evolve` and one of the metrics in `evolve.csv` is nan 
you got an error when trying to write the info to `hyp_evolve.yaml`  
the reason is that there is space before the nan in the `evolve.csv`  so pandas dose not recognize it as float but as string 
adding `data = pd.read_csv(evolve_csv, skipinitialspace=True)` in 
https://github.com/ultralytics/yolov5/blob/7f5724ba4b3e421d4c9162742810c52248d06ecd/utils/general.py#L1039 
solve that 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by mbenami** [comment]
# Minimal Reproducible Example
edit `data/hyps/hyp.scratch-low.yaml` 
```
lr0: 11
lrf: 11
warmup_epochs: 0.0
```
and run 
```
python train.py --cfg models/yolov5n.yaml --evolve 2 --weights "" --epochs 2 --optimizer AdamW
```

**Comment by glenn-jocher** [comment]
@mbenami PR is merged! Thanks for the fix :)
