### ISSUE TITLE
object bbounding box in input image size

### ISSUE THREAD

**Issue by aeskandari68** [ultralytics/yolov5#10355]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How can I extract the bounding box coordinates based on the input image size, not on the original image size? As far as I understand, when you use torchHub the results will be on the original image size, like the following code:
`results = model(img, size=640)`
`results.pandas().xywh[0]`
`Speed: 224.8ms pre-process, 922.6ms inference, 1.0ms NMS per image at shape (1, 3, 576, 640)`
```
       xcenter      ycenter      width     height  confidence  class    name
0   1670.882935  2743.473145  55.419922  53.899658    0.873570      0  ClassA
1   1390.083984  2463.385742  48.288452  47.576416    0.869927      0  ClassA
2   1329.759277  1657.791382  50.100342  46.406738    0.867296      0  ClassA
3   2275.893555  2895.994629  51.204102  50.406738    0.859514      0  ClassA
4   1533.598145   758.518921  45.244263  40.970215    0.857991      0  ClassA
```
As you can see, the results are not based on the input size, which is 640. 

**Is there a way to get the coordinates in 640?**

I tried `results.pandas().xywhn[0]` as well, which is the normalized one, and assumed that if I multiply the results by 640, I can have the input size coordinates. 
```
     xcenter   ycenter     width    height  confidence  class    name
0   0.443558  0.842849  0.014712  0.016559    0.873570      0  ClassA
1   0.369016  0.756801  0.012819  0.014616    0.869927      0  ClassA
2   0.353002  0.509306  0.013300  0.014257    0.867296      0  ClassA
3   0.604166  0.889706  0.013593  0.015486    0.859514      0  ClassA
4   0.407114  0.233032  0.012011  0.012587    0.857991      0  ClassA
```
However, I noticed that when you fed an image size like 640, the yolov5 will keep the aspect ratio and just change the width (or height, not sure which one) of the image to 640. If my understanding is correct, multiplying the normalized bbxes by 640 will not be equal to the input image size because I need to have the aspect ratio as well. 

Even I tried `results = model(img, size=[640,640])` and checked the results in normalized coordinates, and the results were the same. It means when you feed the width and height of the image to the model, it will not resize that to [640,640], and I am totally confused.

`Speed: 223.6ms pre-process, 892.9ms inference, 2.0ms NMS per image at shape (1, 3, 576, 640)`
```
     xcenter   ycenter     width    height  confidence  class    name
0   0.443558  0.842849  0.014712  0.016559    0.873570      0  ClassA
1   0.369016  0.756801  0.012819  0.014616    0.869927      0  ClassA
2   0.353002  0.509306  0.013300  0.014257    0.867296      0  ClassA
3   0.604166  0.889706  0.013593  0.015486    0.859514      0  ClassA
4   0.407114  0.233032  0.012011  0.012587    0.857991      0  ClassA
```
You can see the shape of the results is the same when I just fed 640 as the input size and when I fed 640,640.
This means that if I want to have the width and height in 640, I need to multiply them by 576,640, not 640,640.
I would appreciate it if you could clarify that. Thanks

**Comment by glenn-jocher** [comment]
@aeskandari68 hi there! Thanks for reaching out. When you use YOLOv5 to process images with a specific input size, the output bounding box coordinates are indeed relative to the original image size, not the input size. To obtain bounding box coordinates based on the input image size, you can multiply the x, y, width, and height values of each box by the input image size. Since the YOLOv5 model maintains the aspect ratio during inference, directly using the input size won't match the output bounding box on the resized image. Instead, you may need to multiply the normalized bbxes by the input image's actual width and height, preserving the aspect ratio.

I hope this helps clarify the situation! If you have any further questions or need more assistance, feel free to ask.
