### ISSUE TITLE
Batch Inferencing 

### ISSUE THREAD

**Issue by Sanath1998** [ultralytics/yolov5#10362]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi @glenn-jocher,

How can I do batch inferencing instead of sequential inferencing using repository. Any solid documentation or any useful findings will be helpful for me.

There are two scripts for inferencing one is detect.py (Qualitative Inference) and val.py (Quantitative Inference).
Could you please explain me on how to do batch inference on any of the above mentioned scripts.

**Comment by glenn-jocher** [comment]
👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # yolov5n - yolov5x6 official model
#                                            'custom', 'path/to/best.pt')  # custom model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
results.xyxy[0]  # im predictions (tensor)

results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie

results.pandas().xyxy[0].value_counts('name')  # class counts (pandas)
# person    2
# tie       1
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by Sanath1998** [comment]
Hi @glenn-jocher ,

 I was able to do sequential inference using detect.py script and batch inferencing using val.py script.
One strange thing observed is that, in batch inferencing the time taken to complete inference per batch at the initial stage is less compared to in the middle batch as well as last batch. Theoretically explained as below.
 
If x is the initial time, 5 is the batch size for 20 images. So there will be 4 batches to complete inference on 20 images.
Please refer to table below. 
 Time Taken Per Batch Size                          Batch Size
 -------------------------------               ------------------ 
                   x                                               1st Batch
                   x+2                                           2nd Batch
                   x+3                                           3rd Batch
                   x                                               4th Batch
                   
Observation here is that, in the middle batches the time taken is quite more that initial and final batches.

@glenn-jocher  Could you please explain on this so that it would be very beneficial. Thankss : )

**Comment by glenn-jocher** [comment]
@Sanath1998 val.py sorts a dataset by aspect ratio and runs rectangular inference. The initial and final batches will have low/high aspect ratios while the middle of the dataset is more square (more FLOPs).

**Comment by glenn-jocher** [comment]
@Sanath1998 TRT exports with --dynamic allow for any batch size up to --batch-size

**Comment by chunduri11** [comment]
@glenn-jocher Is it possible to use single TRT exported model to perform Batch inference of any Batch size(Dynamic batch size)?

This is possible with Pytorch model in val.py, looks like it is not possible in TRT models.
