### ISSUE TITLE
Output format

### ISSUE THREAD

**Issue by NemioLipi** [ultralytics/yolov5#10361]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,
I'm feeding a 3 640 640 input to my yolov5 coreml model and I'm getting a 1 25200 8 as output. I don't get what that 25200 is and how I can convert this output to bounding boxes. Would you explain the output dimensions to me?

Thanks

**Comment by glenn-jocher** [comment]
👋 Hello! Thanks for asking about YOLOv5 🚀 **architecture visualization**. We've made visualizing YOLOv5 🚀 architectures super easy. There are 3 main ways:

## `model.yaml`

Each model has a corresponding yaml file that displays the model architecture. Here is YOLOv5s, defined by `yolov5s.yaml`:
https://github.com/ultralytics/yolov5/blob/1a3ecb8b386115fd22129eaf0760157b161efac7/models/yolov5s.yaml#L12-L48

## TensorBoard Graph

Simply start training a model, and then view the TensorBoard Graph for an interactive view of the model architecture. This example shows YOLOv5s viewed in our [Notebook](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb) –  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

```python
# Tensorboard
%load_ext tensorboard
%tensorboard --logdir runs/train

# Train YOLOv5s on COCO128 for 3 epochs
python train.py --weights yolov5s.pt --epochs 3
```

<img width="893" alt="Screenshot 2021-04-11 at 01 10 09" src="https://user-images.githubusercontent.com/26833433/114286928-349bd600-9a63-11eb-941f-7139ee6cd602.png">

## Netron viewer

Use [https://netron.app](https://netron.app/) to view exported ONNX models:

```
python export.py --weights yolov5s.pt --include onnx --simplify
```

<img width="890" alt="Screen Shot 2022-04-29 at 11 09 23 AM" src="https://user-images.githubusercontent.com/26833433/165999628-0d6095ce-58dd-49b7-a04e-25d0995e5493.png">


Good luck 🍀 and let us know if you have any other questions!

**Comment by ryouchinsa** [comment]
This comment is answering to your question.
https://github.com/ultralytics/yolov5/issues/7011#issuecomment-1077570756

`"decoding" of the YOLOv5 output (VNCoreMLFeatureValueObservation), which is essentially a huge array of shape 1 x 25200 x 6. The code converts that output to bounding box dimensions, confidence scores, and class indices.`

**Comment by glenn-jocher** [comment]
@ryouchinsa thanks for the follow-up! The output you mentioned, 1 x 25200 x 6, represents the bounding box dimensions, confidence scores, and class indices for the detected objects. Each bounding box has 6 values: (x, y, w, h, confidence, class). You can use these values to decode the output and visualize the detections. Feel free to consult the Ultralytics YOLOv5 documentation for further guidance on post-processing the model's output. Let me know if you need more help with anything else!
