### ISSUE TITLE
Is it possible to show segmentation and object detection at the same time?

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#10372]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

some object used segmentation detection ,some object use bbox detection.

For example, the scene is on the road. 
I want to use segmentation to detect potholes, but the road markings which use object detection (BBOX)
I don't know if it is possible to show both models at the same time?

I want to achieve both segmentation and object detection in one task.
I don't want to separate the two model training.

very thanks.

**Comment by glenn-jocher** [comment]
@stphtan94117 segmentation models are also detection models, but not vice versa. i.e.:

<img width="775" alt="Screenshot 2022-12-03 at 12 16 44" src="https://user-images.githubusercontent.com/26833433/205460226-f6a0ed6c-81ac-4b60-858e-297418bcf391.png">

**Comment by glenn-jocher** [comment]
@stphtan94117 sure, you can customize segment/predict.py to suit your needs here:
https://github.com/ultralytics/yolov5/blob/master/segment/predict.py

**Comment by stphtan94117** [comment]
@glenn-jocher 
Can you give me a hint on how to add detection BBOX in predict.py?

**Comment by glenn-jocher** [comment]
@stphtan94117 To display both segmentation and bounding boxes in the same image, you can modify the `predict.py` file by adding logic to draw bounding boxes based on the detected objects in addition to the existing segmentation visualization logic. For saving labels, by default `--save-txt` saves in YOLO format (x_center, y_center, width, height) for bounding boxes, and xyxy for segments. You can customize the output format if needed.

**Comment by lililibin2022** [comment]
Hiiii Glenn Jocher, It's an honour to connect with you!
I have a question related to mold detection in corn. In scenarios where I aim to segment the mold-affected and unaffected parts of the corn, is it feasible to simultaneously detect the entire corn (including both moldy and non-moldy regions)?

**Comment by pderrenger** [comment]
Hello! It's great to see your interest in using YOLOv5 for mold detection in corn. Yes, you can achieve simultaneous detection and segmentation by using a segmentation model like YOLOv8, which supports both object detection and segmentation tasks. This approach would allow you to detect the entire corn and segment the mold-affected areas within it. For more detailed guidance, you might want to explore the YOLOv5 or YOLOv8 documentation and experiment with pre-trained models or custom datasets. If you have further questions, feel free to ask!

**Comment by lililibin2022** [comment]
Hi! Really thank you for your reply! Yes, I am currently building the dataset and testing this. I’m just wondering if the mold levels in corn vary significantly—look, how a healthy kernel looks different from one completely affected by mold. How might the model differentiate between them...

**Comment by pderrenger** [comment]
Hi! You're welcome! The model can differentiate between healthy and mold-affected kernels if your dataset contains diverse, well-labeled examples for each class (e.g., healthy, partially affected, completely affected). To improve performance, ensure balanced class representation and use data augmentation during training to account for variability. Let me know if you need further assistance!
