### ISSUE TITLE
How to convert .pt to .mlmodel?

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#10377]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to convert .pt to .mlmodel?

**Comment by heyapps** [comment]
Thanks! But, can I change yolov5s.pt to my trained model.pt?

**Comment by JustasBart** [comment]
@heyapps Hey, yes of course you can! Good luck! :rocket:
