### ISSUE TITLE
xywh normalized to pixels for tflite

### ISSUE THREAD

**Issue by triptec** [ultralytics/yolov5#10373]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I'm wondering about this line https://github.com/ultralytics/yolov5/blob/master/models/common.py#L581. I wonder if this is only done for tflite and if so why?

The reason I ask is because when I convert a yolov7 model into tflite and run it with the detect in this repo I have to comment that line out. But if I run detect with yolov7 models in either pt or onnx formats I don't need to change anything.

Would it be possible to add a fast check on the output to determine if that normalization should be run? Would a correct assumption be that if one or any of `y[0][..., :4]` is bigger than 1 it should not be normalized?

**Comment by glenn-jocher** [comment]
@triptec hi there! The line you mentioned in common.py normalizes "xywh" predictions to pixel coordinates specifically for the TFLite model. Our inference flow involves tensor manipulations like this to ensure consistent outputs across all supported frameworks, but leave the original outputs unaltered. Regarding your request, we appreciate the input and continue to iterate on YOLOv5. Your feedback will be shared with the team. If you are using YOLOv7 or a modified version, examining the model output and deciding on suitable postprocessing may be beneficial. For further details, refer to our documentation at https://docs.ultralytics.com/yolov5/. Cheers!
