### ISSUE TITLE
Fitness Function problem

### ISSUE THREAD

**Issue by zaghdoud2019** [ultralytics/yolov5#10376]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Thanks a lot for this work, please can you help me to display the result of fitness function after test

**Comment by glenn-jocher** [comment]
@zaghdoud2019 fitness is mostly just mAP@50-95:
https://github.com/ultralytics/yolov5/blob/a1b6e79ccf0b66f201720d82d79da14bc44bad6d/utils/metrics.py#L17-L21
