### ISSUE TITLE
Differen map value in train.py and val.py

### ISSUE THREAD

**Issue by WayneCho** [ultralytics/yolov5#10375]
I train a model on my own dataset, and in training process, the best map is 96.0 while 94.0 when loading the saved model and running val.py. I then saved all the epochs and re-do the same experiments, the map seems all 2% lower in val.py than val in the training process, all the settings are default in these experiments, is there any possible reason?
Thanks~

**Comment by glenn-jocher** [comment]
@WayneCho may be slightly different val arguments. Check what train.py is using when calling val and compare against val argparser.
