### ISSUE TITLE
problem resuming training

### ISSUE THREAD

**Issue by KeCHEN0207** [ultralytics/yolov5#1037]
I used the command `python train.py --img 640 --batch 16 --epochs 20 --data ./data/my_data.yaml --cfg ./models/yolov5s.yaml --resume ./runs/exp1/weights/last.pt` to resume training from last saved checkpoint. However, it shows 

>  Transferred 370/370 items from yolov5s.pt

and starting training from epoch 0.

The yolov5 version used is v3.0 and downloaded full zip on 2020-09-24

```
    # Resume
    if opt.resume:
        last = get_latest_run() if opt.resume == 'get_last' else opt.resume  # resume from most recent run
        if last and not opt.weights:
            logger.info(f'Resuming training from {last}')
        opt.weights = last if opt.resume and not opt.weights else opt.weights
```

Checked on this snippet, the variable _last_ is the expected path, however, the opt.weights not changed to the specified path.

Tried to simply delete `and not opt.weights`, the opt.weights is then changed and the resume process running normally.

Since opt.weight is set to 'yolov5s.pt' as default according to `parser.add_argument('--weights', type=str, default='yolov5s.pt', help='initial weights path')` , `not opt.weights` should be always false. Therefore, I don't understand why do we need  `and not opt.weights` this judgement here for resuming.

**Comment by NanoCode012** [comment]
Hi @KeCHEN0207 , maybe you could update your repo. I just did a quick run on coco128 for resume and it works. 
Training: `python train.py --data coco128.yaml --cfg yolov5s.yaml`

Resume: `python train.py --resume `

This is all you need now. It should find the latest training. You can also pass a path after `resume` if you want to resume a specific training.

Current code:
https://github.com/ultralytics/yolov5/blob/7220cee1d1dc1f14003dbf8d633bbb76c547000c/train.py#L418-L425
