### ISSUE TITLE
Training on an IPU

### ISSUE THREAD

**Issue by awetzel-lionpower** [ultralytics/yolov5#10386]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

I have recently been working on training the models using GPUs from Paperspace. They have added an IPU from Graphcore for training neural models and it appears to be able to do a lot quickly. Unfortunately, when I attempt to train a yolov5 model on it, the IPU is treated as a CPU and I don't see any progress. Is there any way to add the IPU functionality? Or, is there a way to make is massively multithreaded so it will behave more similarly to a GPU?

I may misunderstand the functionality of the IPU and apologies if that obfuscates my feature request.

### Use case

This feature could be used by anyone with access to an IPU and could be used to train huge data sets very quickly. 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@awetzel-lionpower I met with Graphcore at the Cannes AI festival this year, but have not had a chance to try their hardware. If you get this working please let us know, and feel free to submit a PR with any changes required. Thank you!
