### ISSUE TITLE
resume local training causes multiple duplicated wandb runs instead of continue the existing one

### ISSUE THREAD

**Issue by bszymik** [ultralytics/yolov5#10380]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

In wandb it shows a resumed training as it was a new training - it should be a continuation of the existing one
![image](https://user-images.githubusercontent.com/10119183/205319469-bce2b0a1-09a6-4ff3-b290-35c70eba09d2.png)

it should be a continuation of existing training

### Environment

Using basic Google Colab (but it happend also on Colab Pro and Gradient notebooks)

### Minimal Reproducible Example

In basic google Colab:

```
!git clone https://github.com/ultralytics/yolov5  # clone
%cd yolov5
%pip install -r requirements.txt  # install

%pip install wandb
!wandb login XXXX___AUTH_TOKEN___XXXX

!python train.py --img 640 --batch 16 --epochs 100 --data coco128.yaml --weights yolov5s.pt --project wandb_run_duplication --name coco128_100epochs
```
than after couple epochs just stop the execution and resume:

```
%pip install wandb
!wandb login XXXX___AUTH_TOKEN___XXXX

!python train.py --resume
```

as a result you will get multiple runs with the same name in wandb 

### Additional

I had a break with using yolov5 for something like 6 months, and before it was working fine without problems, recently (using recent yolov5) I've got above results

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@bszymik thanks for reporting this! This behavior indicates that the resumed training is being treated as a new run in Weights & Biases (wandb). To address this, please ensure that the `--project` and `--name` arguments in your resumed training command match the project and run name of the original training. 

For comprehensive documentation on wandb integration, feel free to refer to our Ultralytics Docs at https://docs.ultralytics.com/yolov5/.

Thanks for your support and for reaching out!
