### ISSUE TITLE
Feature extraction

### ISSUE THREAD

**Issue by glennford49** [ultralytics/yolov5#10398]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is there any feature extraction on yolov5, ? i want to calculate the cosine distance in every person detected, but couldnt find the feature extraction function.
As of now im just using feature extraction using the intel model.

**Comment by glenn-jocher** [comment]
👋 Hello! Thanks for asking about **feature visualization**. YOLOv5 🚀 features can be visualized through all stages of the model from input to output. To visualize features from a given source run `detect.py` with the `--visualize` flag:
```bash
python detect.py --weights yolov5s.pt --source data/images/bus.jpg --visualize
```

An example [Notebook](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb) visualizing [bus.jpg](https://github.com/ultralytics/yolov5/blob/master/data/images/bus.jpg) features with YOLOv5s is shown below:

<a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
<img width="1811" alt="Screenshot 2021-08-30 at 16 44 04" src="https://user-images.githubusercontent.com/26833433/131357928-663a120a-3133-4e1a-8995-c812bd732e8a.png">

All stages are visualized by default, each with its own PNG showing the first 32 feature maps **output** from that stage. You can open any PNG for a closer look. For example the first 32 feature maps of the Focus() layer output are shown in `stage0_Focus_features.png`:

![stage0_Focus_features](https://user-images.githubusercontent.com/26833433/131359874-ecc9aef8-1c9b-44f5-ac17-d6b987093554.png)

Feature maps may be customized by updating the `feature_visualization()` function in `utils/plots.py`:
https://github.com/ultralytics/yolov5/blob/bb5ebc290e5d630a081d7cbc5a9725ed8cea0a24/utils/plots.py#L403-L427

Good luck 🍀 and let us know if you have any other questions!

**Comment by hariouat** [comment]
Hello, 
The visualisation works on detect but not in training..

**Comment by Rich2020** [comment]
What if we want to just extract the features, e.g., to a list, rather than visualize them?

**Comment by glenn-jocher** [comment]
@Rich2020 👋 Hello! If you want to extract the features produced by the YOLOv5 model, you can do so by modifying the YOLOv5 class in `models/yolo.py`, to include a forward pass returning the features dictionary. Here's an example:

```python
class YOLOv5(nn.Module):
    def __init__(self, cfg='', nc=None):  # model, input channels, number of classes
        super(YOLOv5, self).__init__()
        self.model, self.save = parse_model(deepcopy(cfg))  # model
        self.nc = nc  # number of classes

    def forward(self, x, augment=False, profile=False, visualize=False):
        # Forward for YOLOv5 classification and regression heads
        y, self.features = [], []
        for i in range(self.model.nl):
            x = self.model.forward[i](x)  # forward
            self.features.append(x.clone())  # save features
            y.append(self.model.head[i](x))  # head
            if i == self.model.i[-1]:  # detect
                return y
            x = self.model.up[i](x) if i in self.model.iup else None  # upsample
            if x is not None:  # concat
                j = self.model.i.index(i)  # index
                if j > 0:
                    y[j] = self.model.lat[j](y[j], x)
                else:
                    y[j] = self.model.anchors.to(x).repeat(y[j].shape[0], 1, 1, 1).sigmoid()
        return y
```

This modified forward pass returns a features dictionary object containing the feature tensors from each stage of the model. Here's an example of how this dictionary can be used to get the features from the first stage:

```python
from models.yolo import YOLOv5

# Load the YOLOv5 model
model = YOLOv5('yolov5s.yaml', nc=80).cuda()

# Get an example input tensor
input_tensor = torch.randn(1, 3, 640, 640).cuda()

# Pass the input tensor through the model, and get the features dictionary
features_dict = model(input_tensor)

# Get the features from the first stage, i.e. the "Focus" layer
features
