### ISSUE TITLE
Please how I can call the function val (task test)from yolov5 in order to obtain map only

### ISSUE THREAD

**Issue by zaghdoud2019** [ultralytics/yolov5#10393]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

how I can get the map from val function like this:
def yolomap():
best = !python content/yolov5/train.py --epochs 2 --data '/content/data.yaml' --weights /content/model/best_o_temrproy.pt --cache
map = !python /content/yolov5/val.py --weights best --save-txt --data '/content/data.yaml' --task test
return map

**Comment by glenn-jocher** [comment]
@zaghdoud2019 see val.py Usage examples:

https://github.com/ultralytics/yolov5/blob/a1b6e79ccf0b66f201720d82d79da14bc44bad6d/val.py#L3-L19

**Comment by zaghdoud2019** [comment]
> @zaghdoud2019 see val.py Usage examples:
> 
> https://github.com/ultralytics/yolov5/blob/a1b6e79ccf0b66f201720d82d79da14bc44bad6d/val.py#L3-L19

thanks for replying but I want to make train and val like function to call them in order to return only map like this :
**def yolomap():**
best = !python content/yolov5/train.py --epochs 2 --data '/content/data.yaml' --weights /content/model/best_o_temrproy.pt --cache
map = !python /content/yolov5/val.py --weights best --save-txt --data '/content/data.yaml' --task test
return map
