### ISSUE TITLE
yolov5-p2.yaml with m model

### ISSUE THREAD

**Issue by CesareDavidePace** [ultralytics/yolov5#10406]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I saw that model p2 is implemented starting from model l so with #depth_multiple: 1.00 # model depth multiple
#width_multiple: 1.00 # multiple channel layers.
My question is, since I'm limited gpu-wise is it possible to use depth_multiple and width_multiple of m so equal to 0.67 and 0.75, respectively, and have benefits for small objects?

**Comment by glenn-jocher** [comment]
@CesareDavidePace yes of course, you can apply the `m` scaling constants you have there to yolov5-p2.yaml without any problems.
