### ISSUE TITLE
How to improve the MAP ?

### ISSUE THREAD

**Issue by devendraswamy** [ultralytics/yolov5#10407]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I had trained the model with single class with YOLOV5n and I completed the model with MAP of 

val: Scanning D:\raghavi\28_11_2022\yolov5\dataset\V7\val\labels... 56 images, 0 backgrounds, 0 corrupt: 100%|██████████| 56/56 00:05
val: New cache created: D:\raghavi\28_11_2022\yolov5\dataset\V7\val\labels.cache
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 56/56 00:06
                   all             56        600      0.306       0.327     0.241       0.0768
       foreignparticle     56        600      0.306      0.327      0.241       0.0768
Speed: 1.1ms pre-process, 30.7ms inference, 4.6ms NMS per image at shape (1, 3, 640, 640)

Please help me to analyse the MAP and let me know is it the model given MAP 0.0768 its mean 76% . please let me know am i right or not ? and if i am wrong how to improve the MAP.

**Comment by devendraswamy** [comment]
![confusion_matrix](https://user-images.githubusercontent.com/47595310/205659483-0a8e0c21-dfe7-4489-a27b-00ece26065fc.png)
![results](https://user-images.githubusercontent.com/47595310/205659504-1f03bf2f-6015-45da-a8cb-514a8d57ae45.png)
![image](https://user-images.githubusercontent.com/47595310/205659993-e652e6b9-ec9c-4a26-97fa-b51177c9500a.png)

Please refer above images for results and MAP values of model . kindly review it and if any files required please let me know. thanking you in advance.

**Comment by cool112624** [comment]
for your answer about map
Yolov5 result are normalized, so it is 0 to 1 
so your map 0.0768 should be 7.68%
#Correct me if I am wrong

So far I can know from your result is that your have 4 classes which is not single class and the result is very poor 

Can I know your total number of train images, and how many for each class
and some example of your labelled datasets of each classes if is it ok for you to show your datasets

**Comment by cool112624** [comment]
I see, so what is your batch size, epoch and other paramter that you use for training

**Comment by devendraswamy** [comment]
--batch size : 64
--epochs : 1000
--patience :100 

[hyp.txt](https://github.com/ultralytics/yolov5/files/10163398/hyp.txt)

Please refer the hyp file and above parameters , Thank you for support.

**Comment by cool112624** [comment]
Maybe you can try 
--batch size 32
--epoch 300
--patience 300
and see the result again

Do you label your picture as tight as possible?
below are guide to good labelling
![crowdsourcing-labeling-example-bad-good](https://user-images.githubusercontent.com/51593747/205847320-e3de887e-ac80-474f-b371-eaa68f2056fb.png)

**Comment by cool112624** [comment]
@devendraswamy  Do you got any improvement?
