### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by LokedSher** [ultralytics/yolov5#1040]
## ❔Question
Hey guys, I am a green hand and it is my first time to run yolov5. I read README and  did exactly as the 'tutorial-Train custom data' tells  and I encountered this problem. I don't known is my GPU occupied too much or something else is wrong ?

## Additional context
![image](https://user-images.githubusercontent.com/27689360/94237656-c4ec5080-ff41-11ea-8860-aab7ff85b1c7.png)
![image](https://user-images.githubusercontent.com/27689360/94237706-d5043000-ff41-11ea-8820-173a227dfd48.png)

**Comment by NanoCode012** [comment]
@LokedSher , It means that you don’t have enough available GPU memory.

Also, check out the Multi-GPU Training on ReadMe to properly utilize multi-gpus.

**Comment by Frank1126lin** [comment]
Yeah，just use small batch-size to aviod Mem problem.

**Comment by meizano** [comment]
Your GPU doesn't have enough memory. Change your batch size to lower number by giving parameter such as:  `--batch 8`
