### ISSUE TITLE
Exporting model to tflite including edgetpu shows some strange behavior with certain resolutions

### ISSUE THREAD

**Issue by mexxBf** [ultralytics/yolov5#10405]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi all,
currently I'm training a yolo5s model for my Coral Edge TPU. While experimenting with the resolution in the training part, I found that I can not convert the models properly, if I choose e.g. 512px in training and export. The result is:
 
`
Number of operations that will run on Edge TPU: 123
Number of operations that will run on CPU: 139

Operator                       Count      Status

STRIDED_SLICE                  9          More than one subgraph is not supported
MAX_POOL_2D                    3          Mapped to Edge TPU
ADD                            3          More than one subgraph is not supported
ADD                            7          Mapped to Edge TPU
PAD                            5          Mapped to Edge TPU
PAD                            2          More than one subgraph is not supported
CONCATENATION                  12         More than one subgraph is not supported
CONCATENATION                  5          Mapped to Edge TPU
RESHAPE                        6          More than one subgraph is not supported
RESIZE_NEAREST_NEIGHBOR        2          More than one subgraph is not supported
CONV_2D                        34         Mapped to Edge TPU
CONV_2D                        26         More than one subgraph is not supported
LOGISTIC                       32         More than one subgraph is not supported
LOGISTIC                       34         Mapped to Edge TPU
MUL                            34         Mapped to Edge TPU
MUL                            41         More than one subgraph is not supported
QUANTIZE                       5          More than one subgraph is not supported
QUANTIZE                       1          Operation is otherwise supported, but not mapped due to some unspecified limitation
QUANTIZE                       1          Mapped to Edge TPU
Compilation child process completed within timeout period.
Compilation succeeded! 
Edge TPU: export success ✅ 26.8s, saved as runs/train/exp84/weights/best-int8_edgetpu.tflite (7.3 MB)
`
But if I choose 416px or 672px and up as resolution for training and export its says "Number of operations that will run on CPU: 3".

It works up to 800px with an 32px increment. If I remember correctly, even 1024px works.

My model only has two classes, if that is interesting to you.

The command I use for export:
python export.py --weights runs/train/exp83/weights/best.pt --include edgetpu --img 544

Maybe someone knows why this happens, or how I can make it work.

Thank you

**Comment by glenn-jocher** [comment]
@mexxBf Edge TPU exports support a variety of options if I remember correctly, you may need to experiment with the arguments to see what works best for your use case. See https://coral.ai/docs/edgetpu/faq/ and view the export code at:
https://github.com/ultralytics/yolov5/blob/5dc1ce4e865960f5b5dfe4e4f5148a4731433bca/export.py#L403-L426

**Comment by mexxBf** [comment]
@glenn-jocher Thank you for your response. 

Maybe you can explain to me, what the consequences in yolo are if changing the --img argument. I changed nothing but this option and get completely different results on export. My guess would be, that something internal changes and becomes kind of incompatible with the export of the edgetpu. Its kind of strange, that the resolutions 416, 448, 672,704 and 800 are okay, but 480, 512, 544, 576,608,640 are incompatible with export.

Thank you,
best regards
