### ISSUE TITLE
ERROR In YAML FILE

### ISSUE THREAD

**Issue by Awader28** [ultralytics/yolov5#10401]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

yaml.parser.ParserError: while parsing a block node
expected the node content, but found '?'
  in "data/universal.yaml", line 50, column 3

**Comment by glenn-jocher** [comment]
@samilarinc thanks for reaching out! The error message you're encountering usually occurs when there's a syntax issue in the YAML file. Without seeing the contents of "data/universal.yaml", it's hard to pinpoint the exact problem. However, based on the error message, it seems that there might be an unexpected character at line 50, column 3.

Double-check that all the indentation, spacing, and syntax are correct at that location in the YAML file. If you're still having trouble, feel free to share the relevant portion of the YAML file, and we'll do our best to assist you further.
