### ISSUE TITLE
print custom header like yolo segment/predict.py

### ISSUE THREAD

**Issue by nikky4D** [ultralytics/yolov5#10411]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How do I print out a header similar to the rocket like what you have in  segment/predict.py

### Additional

Just looking for code to create a similar effect in my run

**Comment by glenn-jocher** [comment]
@nikky4D the custom header in `segment/predict.py` is achieved using the `clear_terminal` and `rocket` functions in the source code. You can find the implementation in the YOLOv5 repository. If you'd like to create a similar effect in your own code, you can study the functions used in `segment/predict.py` and adapt them to your requirements. Good luck!
