### ISSUE TITLE
what happens with a high resolution image?

### ISSUE THREAD

**Issue by MasIgor** [ultralytics/yolov5#10417]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello!

What happens if I send a 30mpx image through my 640x640 network?

will the image be resized down, and recognition be made on the small resized image, or will it be made on the large image?

Background: I have an application where I have to detect some objects. hese objects always fill the entire image and its working great so far.  For a new application, there is a high resolution camera, that has to recognize the same objects on a table.  but compared to the first application, there are multiple objects and they are smaller in proportion to the image itself.. (they do not fill the image..) they are about the same size: if the 30 mpx image is not scaled down, then each object is about 600 px in size. but if the 30 mpx image gets scaled, then the objects become way smaller too, and cant be recognized anymore. I would like to keep the original resolution and detect the objects on that image. (inference time is not a problem)

can this be done?

thank you

Best regards

Igor

**Comment by glenn-jocher** [comment]
@tanzerlana inference is run at --imgsz regardless of input image size.

**Comment by tanzerlana** [comment]
@glenn-jocher thank you for your answer! This means that I could simply increase the imgsz parameter to the camera resolution (square crop) as long as the pc has enough resources to compute the calculation?

**Comment by JustasBart** [comment]
@tanzerlana Yes, you can just increase the --imgsz to something bigger like 1024 or even 2048 or whatever your machine can handle, but you're also not stuck with a square input shape, you can train it with --rect flag and export it as say 1920x1088 (Depending on your model stride and your actual chosen size).

Good luck! :rocket:
