### ISSUE TITLE
about cutout augmentation

### ISSUE THREAD

**Issue by ampelmannn** [ultralytics/yolov5#10413]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I would like to apply cutout augmentation to bbox only(not entire input image). 
The figure below is the original code shown. So, which part and how do I fix it?

![그림1](https://user-images.githubusercontent.com/117254041/205846903-d8e705b3-e12c-4ae7-8a04-5a24cb78c0cf.png)

**Comment by glenn-jocher** [comment]
@ampelmannn code customizations are up to you, we only provide support for reproducible bugs and commonly requested features, which this falls outside of.
