### ISSUE TITLE
`val.py` fails silently when `opt.task` is misspelled

### ISSUE THREAD

**Issue by leandervaneekelen** [ultralytics/yolov5#10419]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Validation

### Bug

https://github.com/ultralytics/yolov5/blob/f8539a680041a9f4fbcc4fcdd8f540724da453af/val.py#L371

The `main` function of `val.py` checks the specified tasks with a bunch of if-statements, but there's no final `else` at the end in the case of a misspelled task, thus causing it to fail silently. Anecdote: I sadly lost 20 minutes on debugging this :cry: .

### Minimal Reproducible Example

```
# Inside a YOLOv5 docker
python3.9 val.py --task 'vall' # should be 'val'

# val.py will just echo input args but not do anything else
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@leandervaneekelen oh of course, that's an oversight of ours. Can you please submit a PR for all 3 val files (in classify/ and segment/ also)? Actually classify may not have tasks, but segment does.

**Comment by glenn-jocher** [comment]
Thanks, @leandervaneekelen! Your contribution is much appreciated. If you need any help with your PR, feel free to ask!
