### ISSUE TITLE
How to freeze backbone and unfreeze it after a specific epoch?

### ISSUE THREAD

**Issue by Mr-ind1fferent** [ultralytics/yolov5#10416]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to freeze backbone and unfreeze it after a specific epoch?Now i can only freeze backbone all the training time.

**Comment by glenn-jocher** [comment]
@Mr-ind1fferent see Transfer Learning with Frozen Layers tutorial below:

## Tutorials

- [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)  🚀 RECOMMENDED
- [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)  ☘️ RECOMMENDED
- [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
- [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) 🌟 NEW
- [TFLite, ONNX, CoreML, TensorRT Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
- [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
- [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
- [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
- [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
- [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)
- [Architecture Summary](https://docs.ultralytics.com/yolov5/tutorials/architecture_description) 🌟 NEW
- [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)
- [Roboflow for Datasets, Labeling, and Active Learning](https://docs.ultralytics.com/yolov5/tutorials/roboflow_datasets_integration)  🌟 NEW
- [ClearML Logging](https://docs.ultralytics.com/yolov5/tutorials/clearml_logging_integration) 🌟 NEW
- [Deci Platform](https://github.com/ultralytics/yolov5/wiki/Deci-Platform) 🌟 NEW
- [Comet Logging](https://docs.ultralytics.com/yolov5/tutorials/comet_logging_integration) 🌟 NEW

Good luck 🍀 and let us know if you have any other questions!

**Comment by Enverrrr** [comment]
> ### Search before asking
> 
>     * [x]  I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.
> 
> 
> ### Question
> 
> How to freeze backbone and unfreeze it after a specific epoch?Now i can only freeze backbone all the training time.
> ### Additional
> 
> _No response_

Brother could you find the solution

**Comment by Mr-ind1fferent** [comment]
> > ### Search before asking
> > ```
> > * [x]  I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Question
> > How to freeze backbone and unfreeze it after a specific epoch?Now i can only freeze backbone all the training time.
> > ### Additional
> > _No response_
> 
> Brother could you find the solution

it can only work on manual pause on the epoch you want

**Comment by Enverrrr** [comment]
> 


Alright I have a question how to execute train.py in another file do you know that

**Comment by Mr-ind1fferent** [comment]
> > ### Search before asking
> > ```
> > * [x]  I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Question
> > How to freeze backbone and unfreeze it after a specific epoch?Now i can only freeze backbone all the training time.
> > ### Additional
> > _No response_
> 
> Brother could you find the solution

Just adjust the path

**Comment by glenn-jocher** [comment]
@Mr-ind1fferent Thanks for the tip! We can dynamically freeze and unfreeze layers with the `--freeze` argument and the `freeze` attribute in the YAML file. Could you clarify which path you're referring to?
