### ISSUE TITLE
Split one class to multiple and train classifier with detectors weights freezed

### ISSUE THREAD

**Issue by stakanich** [ultralytics/yolov5#10427]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi! Thanks for your project at first.
I need to split one class from list of pretrained models(for example, splitting dogs class to their breeds). So, the detector already knows how to find objects of these classes(because it knows how to detect parent class) and I want to train only classifier head.
Is it possible? Do you have tools for that or I will need to write it?
Thanks in advance.

**Comment by glenn-jocher** [comment]
@stakanich this appears to be a custom project which you'll need to develop yourself, there's no built-in functionality like this.
