### ISSUE TITLE
Export to saved_model keras raises NotImplementedError when trying to use the model

### ISSUE THREAD

**Issue by MatoFD** [ultralytics/yolov5#10429]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Export

### Bug

Hi, I am trying to export the yolov5s model to Keras.

I have followed the [guide on export](https://github.com/ultralytics/yolov5/issues/251). First I tried copying the command as it is suggested (python export.py --weights yolov5s.pt --include saved_model), but when trying to use it, it says the model is a '_UserObject' and doesn't have the attributes I expect from a keras model.

I [found this issue ](https://github.com/ultralytics/yolov5/issues/7911) that talks about it, and the solution was to add the --keras flag to the export command. Now the model, which was loaded with type <class 'keras.engine.functional.Functional'>, raises a "NotImplementedError" when trying to do model.to_json or saving the model.

I don't understand what is wrong with the model.

The model summary looks like this:
Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
==================================================================================================
 input_1 (InputLayer)           [(1, 640, 640, 3)]   0           []                               
                                                                                                  
 tf_conv (TFConv)               (1, 320, 320, 32)    3488        ['input_1[0][0]']                
                                                                                                  
 tf_conv_1 (TFConv)             (1, 160, 160, 64)    18496       ['tf_conv[0][0]']                
                                                                                                  
 tfc3 (TFC3)                    (1, 160, 160, 64)    18624       ['tf_conv_1[0][0]']              
                                                                                                  
 tf_conv_7 (TFConv)             (1, 80, 80, 128)     73856       ['tfc3[0][0]']                   
                                                                                                  
 tfc3_1 (TFC3)                  (1, 80, 80, 128)     115200      ['tf_conv_7[0][0]']              
                                                                                                  
 tf_conv_15 (TFConv)            (1, 40, 40, 256)     295168      ['tfc3_1[0][0]']                 
                                                                                                  
 tfc3_2 (TFC3)                  (1, 40, 40, 256)     623872      ['tf_conv_15[0][0]']             
                                                                                                  
 tf_conv_25 (TFConv)            (1, 20, 20, 512)     1180160     ['tfc3_2[0][0]']                 
                                                                                                  
 tfc3_3 (TFC3)                  (1, 20, 20, 512)     1181184     ['tf_conv_25[0][0]']             
                                                                                                  
 tfsppf (TFSPPF)                (1, 20, 20, 512)     656128      ['tfc3_3[0][0]']                 
                                                                                                  
 tf_conv_33 (TFConv)            (1, 20, 20, 256)     131328      ['tfsppf[0][0]']                 
                                                                                                  
 tf_upsample (TFUpsample)       (1, 40, 40, 256)     0           ['tf_conv_33[0][0]']             
                                                                                                  
 tf_concat (TFConcat)           (1, 40, 40, 512)     0           ['tf_upsample[0][0]',            
                                                                  'tfc3_2[0][0]']                 
                                                                                                  
 tfc3_4 (TFC3)                  (1, 40, 40, 256)     361216      ['tf_concat[0][0]']              
                                                                                                  
 tf_conv_39 (TFConv)            (1, 40, 40, 128)     32896       ['tfc3_4[0][0]']                 
                                                                                                  
 tf_upsample_1 (TFUpsample)     (1, 80, 80, 128)     0           ['tf_conv_39[0][0]']             
                                                                                                  
 tf_concat_1 (TFConcat)         (1, 80, 80, 256)     0           ['tf_upsample_1[0][0]',          
                                                                  'tfc3_1[0][0]']                 
                                                                                                  
 tfc3_5 (TFC3)                  (1, 80, 80, 128)     90496       ['tf_concat_1[0][0]']            
                                                                                                  
 tf_conv_45 (TFConv)            (1, 40, 40, 128)     147584      ['tfc3_5[0][0]']                 
                                                                                                  
 tf_concat_2 (TFConcat)         (1, 40, 40, 256)     0           ['tf_conv_45[0][0]',             
                                                                  'tf_conv_39[0][0]']             
                                                                                                  
 tfc3_6 (TFC3)                  (1, 40, 40, 256)     295680      ['tf_concat_2[0][0]']            
                                                                                                  
 tf_conv_51 (TFConv)            (1, 20, 20, 256)     590080      ['tfc3_6[0][0]']                 
                                                                                                  
 tf_concat_3 (TFConcat)         (1, 20, 20, 512)     0           ['tf_conv_51[0][0]',             
                                                                  'tf_conv_33[0][0]']             
                                                                                                  
 tfc3_7 (TFC3)                  (1, 20, 20, 512)     1181184     ['tf_concat_3[0][0]']            
                                                                                                  
 tf_detect (TFDetect)           ((1, 25200, 85),     229245      ['tfc3_5[0][0]',                 
                                )                                 'tfc3_6[0][0]',                 
                                                                  'tfc3_7[0][0]']                 
                                                                                                  
==================================================================================================
Total params: 7,225,885
Trainable params: 0
Non-trainable params: 7,225,885
__________________________________________________________________________________________________

### Environment

OS - Ubuntu 18.04.6 LTS
Yolov - 

Conda environment:
Python - 3.7.15
Tensorflow - 2.11.0

### Minimal Reproducible Example

python export.py --weights yolov5s.pt --include saved_model --keras

import tensorflow as tf
k_model = tf.keras.models.load_model("./yolov5s_saved_model")
print(k_model.summary())

tf.keras.models.save_model(k_model, "my_h5_model.h5")

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@MatoFD hi, thanks for raising this bug report! I'm not a TF export and don't use Keras models myself, so I'm not sure what to say. We do CI on export and inference every 24 hours on every export format including saved_model, but not with the --keras flag. The --keras flag was added to maintain backwards compatibility after moving away from it as the default due to file size limitations on keras exports. I believe all TF exports now utilize TF1 and are free of file-size constraints imposed by TF2.
