### ISSUE TITLE
error when run segment/train with 1280 imgsz in DDP mode

### ISSUE THREAD

**Issue by TurboPlus** [ultralytics/yolov5#10421]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, There is a error when I run segment/train with 1280 or 1600 imgsz in DDP mode, It happenes around 20% of the first epoch. I am confused, because it is ok when the imgsz is 640 or 960. The error is as fellows:

RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your training graph has changed in this iteration, e.g., one parameter is used in first iteration, but then got unused in the second iteration. this is not compatible with static_graph set to True.

I tried to set static_graph to True, but it is useless. Looking forward to your reply! Thanks!

INFO: 
environment:
T4 * 7 

usage:
python -m torch.distributed.run --nproc_per_node 7 --master_port 1 segment/train.py --weights segment/yolov5x-seg.pt --data data/my_seg_data.yaml --batch-size 14 --epochs 300 --img 1280 --device 1,2,3,4,5,6,7

**Comment by TurboPlus** [comment]
There are some other method  I have tried which is useless.

--> `static_graph=False, find_unused_parameters=False`

**Comment by glenn-jocher** [comment]
@TurboPlus all DDP trainings should be in our docker image for max compatibility. If you can reproduce this error in Docker with coco128 please let us know, if we can't reproduce ourselves there is no action for us to take.

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Notebooks** with free GPU: <a href="https://bit.ly/yolov5-paperspace-notebook"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

**Comment by TurboPlus** [comment]
@glenn-jocher Everything works fine when training with the coco128 dataset(imgsz=1280)

**Comment by Robotatron** [comment]
@TurboPlus  did you found the issue?
