### ISSUE TITLE
Strange output even with high precision, recall and MAP

### ISSUE THREAD

**Issue by Sagar1094** [ultralytics/yolov5#1042]
Hi,
I have been experiencing a very strange situation, I have used yolov5 for similar data with annotations which were leaving out half of leading and trailing character and the yolov5 results were amazing but needs to  be corrected as all the characters were important. So, I annotated new data with a bit bigger bounding boxes and the resulting model is acting very weird all of a sudden.
Kindly guide me through this, have tried by turning off moasic  and increasing training threshold to 0.8. No changes have been made to the model architecture and model used is M. Few images are perfect as well but the ratio is 75:25 bad:perfect

Attaching screenshots of training_batch images, a few resultant images and training progress :- 
Model Progress :-
![Model_progress](https://user-images.githubusercontent.com/54572031/94261791-10a5f680-ff50-11ea-995c-1f8c84cd1fcb.png

**Comment by glenn-jocher** [comment]
@Sagar1094 you're going to need to experiment with the best training settings and hyperparameters for your custom dataset. I'd recommend evolving hyperparameters and defining anchors offline to fit your data. You can start from the available hyps in data/ and use the one that works best as your evolution starting point. See https://docs.ultralytics.com/yolov5

**Comment by Sagar1094** [comment]
@glenn-jocher Thanks for the suggestion, I would try the same and see if it makes any difference.
