### ISSUE TITLE
Deploy with OpenCV DNN module

### ISSUE THREAD

**Issue by MohamedAliRashad** [ultralytics/yolov5#1043]
## 🚀 Feature
The ability to deploy yolov5 with the dnn module in opencv

## Motivation
Consistency with the previous yolo models and ease of deployment with opencv

## Pitch
We need a script that can produce the `cfg` file and the `weights` file of a trained yolo model

## Alternatives
ONNX can be used but its is still very buggy on opencv and yolov5

**Comment by XiaoLaoDi** [comment]
@MohamedAliRashad have you found a way to deploy the yolov5 in opencv dnn module ? would you mind to share ?

**Comment by hzitoun** [comment]
Did anyone convert YOLOV5 to cfg and weights files we can use with opencv dnn module please?

**Comment by OlivierLDff** [comment]
We managed to load yolov5 onnx file with https://github.com/opencv/opencv/pull/19546
Result is ok with cpu backend, but cuda backend doesn't work as expected.
(Output is scaled x2, and not exactly matching cpu results)
