### ISSUE TITLE
When two categories overlap, only one category mask is displayed

### ISSUE THREAD

**Issue by jiaqizhang123-stack** [ultralytics/yolov5#10433]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, when I use yolov5-seg to segment images of two categories, when the two categories overlap, the mask obtained shows only one category.Is this caused by post-processing mask? How to make the masks of two categories overlap?
![33cb61710b05518cfa7274aa1ee07bd](https://user-images.githubusercontent.com/55009436/206346006-9eae11cd-194e-472a-8910-0685e7bcf043.png)

**Comment by jiaqizhang123-stack** [comment]
And how to distinguish the examples with intersection in the two boxes? Can we improve them by adding training sets?
Such as:
![image](https://user-images.githubusercontent.com/55009436/206432214-564e6693-8f96-4c43-b146-63bf68c05fd4.png)

**Comment by glenn-jocher** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.
> 
> ### Question
> Hello, when I use yolov5-seg to segment images of two categories, when the two categories overlap, the mask obtained shows only one category.Is this caused by post-processing mask? How to make the masks of two categories overlap? ![33cb61710b05518cfa7274aa1ee07bd](https://user-images.githubusercontent.com/55009436/206346006-9eae11cd-194e-472a-8910-0685e7bcf043.png)
> 
> ### Additional
> _No response_

Your images appear to show correct predictions. This is how instance segmentation works, and I'm sure how your images were annotated. If you want the model to learn differently then it's up to you to adjust your annotations.

**Comment by jiaqizhang123-stack** [comment]
![image](https://user-images.githubusercontent.com/55009436/206617999-83b643fc-58b1-403e-b13e-c40052c74c4c.png)
My label is overlapping

**Comment by glenn-jocher** [comment]
@jiaqizhang123-stack oh interesting. We I'm not sure a pixel can belong to two different objects. Our own examples show people in front of a bus and the foreground pixels are assigned to the people:

![image](https://user-images.githubusercontent.com/26833433/206628509-73c01b59-1f83-4d73-9a17-b8ff2d2d6349.png)

**Comment by jiaqizhang123-stack** [comment]
> And how to distinguish the examples with intersection in the two boxes? Can we improve them by adding training sets?
> Such as:
> ![image](https://user-images.githubusercontent.com/55009436/206432214-564e6693-8f96-4c43-b146-63bf68c05fd4.png)

Ok，thank you！
For a box containing two objects, how to correctly sketch an instance? Can this be changed by adding training sets

**Comment by glenn-jocher** [comment]
@jiaqizhang123-stack I'm sorry I'm not sure what you mean by sketch an instance. Annotated results are shown in your runs/predict-seg/exp directory.

**Comment by jiaqizhang123-stack** [comment]
The instance has spread to another target, and the mask prediction of the instance is not accurate. Can we improve this by increasing the training set
![Uploading F4E5CB3D-F090-4540-8109-68C1B2AC7965.jpeg…]()

**Comment by jiaqizhang123-stack** [comment]
The instance has spread to another target, and the mask prediction of the instance is not accurate. Can we improve this by increasing the training set
![32F2A47F-A6E6-4683-8C13-436F64AA18C5](https://user-images.githubusercontent.com/55009436/206822300-bc227973-b219-4823-ae71-06d07d2d4011.jpeg)

**Comment by glenn-jocher** [comment]
@jiaqizhang123-stack not sure. We've only been working with segmentation for a few months here so I'm not a super expert. I see the same results in zidane.jpg though on smaller models, so I'd recommend using a larger model and improving your dataset.

![image](https://user-images.githubusercontent.com/26833433/206875208-54f99ef5-664c-41cd-a161-0b299a73023b.png)

**Comment by jiaqizhang123-stack** [comment]
> > And how to distinguish the examples with intersection in the two boxes? Can we improve them by adding training sets?
> > Such as:
> > ![image](https://user-images.githubusercontent.com/55009436/206432214-564e6693-8f96-4c43-b146-63bf68c05fd4.png)
> 
> Ok，thank you！ For a box containing two objects, how to correctly sketch an instance? Can this be changed by adding training sets

Hello, I have tried to add datasets and use large models. This problem has not been solved yet. Is this network similar to the idea of yolact? The effect of yolact will be relatively good. What should I do to solve this problem?

**Comment by jiaqizhang123-stack** [comment]
> 

Hello, I have tried to add datasets and use large models. This problem has not been solved yet. Is this network similar to the idea of yolact? The effect of yolact will be relatively good. What should I do to solve this problem?

**Comment by jiaqizhang123-stack** [comment]
> @jiaqizhang123-stack not sure. We've only been working with segmentation for a few months here so I'm not a super expert. I see the same results in zidane.jpg though on smaller models, so I'd recommend using a larger model and improving your dataset.
> 
> ![image](https://user-images.githubusercontent.com/26833433/206875208-54f99ef5-664c-41cd-a161-0b299a73023b.png)

Hello, I have tried to add datasets and use large models. This problem has not been solved yet. Is this network similar to the idea of yolact? The effect of yolact will be relatively good. What should I do to solve this problem?

**Comment by joda01** [comment]
> > And how to distinguish the examples with intersection in the two boxes? Can we improve them by adding training sets?
> > Such as:
> > ![image](https://user-images.githubusercontent.com/55009436/206432214-564e6693-8f96-4c43-b146-63bf68c05fd4.png)
> 
> Ok，thank you！ For a box containing two objects, how to correctly sketch an instance? Can this be changed by adding training sets

Hello @jiaqizhang123-stack I found your issue. It's a while but did you found a solution? I have the same problem in my application as you described.

Thank's a lot!
