### ISSUE TITLE
The training always stuck in "Model summary"

### ISSUE THREAD

**Issue by Aspirinkb** [ultralytics/yolov5#10437]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Training command:
```
python3 -m torch.distributed.run --nproc_per_node 2 train.py --batch 64 --data coco128.yaml --weights yolov5s.pt --device 2,3
```   
The training is ok, but stuck in final model summary phrase after following outputs in the terminal:
```
Validating runs/train/exp15/weights/best.pt...
Fusing layers...
Model summary: 157 layers, 7225885 parameters, 0 gradients, 16.4 GFLOPs
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 2/2 [00:07<00:00,  3.64s/it]
                   all        128        929      0.923      0.893      0.941      0.768
                person        128        254      0.985      0.862      0.952      0.747
...
            toothbrush        128          5       0.93          1      0.995      0.864
```

So I have to kill the training processes by `sudo kill pid`.

The ClearML webUI shows the experiment is running status and I have to abort it.
![截屏2022-12-08 17 11 14](https://user-images.githubusercontent.com/5260197/206405864-4ec832e2-1541-4fe2-b800-71cdaf48d4f6.png)

**Comment by glenn-jocher** [comment]
@Aspirinkb hi, thanks for the bug report! Does this occur when training normally without ClearML?

**Comment by glenn-jocher** [comment]
@Aspirinkb our ClearML expert @thepycoder may be able to assist you

**Comment by Aspirinkb** [comment]
> @Aspirinkb hi, thanks for the bug report! Does this occur when training normally without ClearML?

If I close clearml logger, the training runs normally with outputs:
```
...
Results saved to runs/train/expX
```

**Comment by Aspirinkb** [comment]
And No models are logged into the model tab of ClearML webUI.

**Comment by glenn-jocher** [comment]
@Aspirinkb thanks for the info!

@thepycoder it looks like ClearML is hanging on Multi-GPU DDP trainings.

**Comment by thepycoder** [comment]
Hi @glenn-jocher, @Aspirinkb I'll take a look!

**Comment by thepycoder** [comment]
Hi @Aspirinkb!

Sorry for the long wait, took me a while to get a machine with multiple GPUs.
I can't seem to be able to reproduce the issue though, I just ran the exact same command as you on an AWS 4xT4 machine and everything seems to work just fine. Bear in mind you have to wait a little at the end for ClearML to finish uploading all the plots/debug samples/model files etc. They are uploaded asynchronously, so they might not be done yet by the time training is finished.

How long did you wait before killing the task? Are you running in a special environment (e.g. where ClearML call might be blocked for example?) Or are you running in docker?

It's hard to solve the issue if I can't recreate it, if you can help me narrow down, that would be a big help!
