### ISSUE TITLE
What's the behavior for segment "overlap" is true, but the dataset annotation exists some overlapping objects?

### ISSUE THREAD

**Issue by p890040** [ultralytics/yolov5#10438]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

For my understanding. Training the segment model we have a option "--no-overlap".

- If overlap is true, then mask groundtruth will be like this:
0 0 0 0 1 1
0 1 1 0 1 1
0 1 1 0 2 2
0 0 0 2 2 2
0 0 0 0 2 0
0 0 0 0 0 0
This is for 2 classes and 3 objects in one array(1,H,W).

- In the same case, if overlap is false, then mask ground truth will be like this:
Total binary array (3,H,W)
First
0 0 0 0 1 1
0 0 0 0 1 1
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
Second
0 0 0 0 0 0
0 1 1 0 0 0
0 1 1 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
Third
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 1 1
0 0 0 1 1 1
0 0 0 0 1 0
0 0 0 0 0 0

So, my question is if we have indeed overlapping annotations, what will it go if overlap setting is true?

**Comment by xjsxujingsong** [comment]
@p890040 Thanks for your hint. I have a dataset in which one class will always cover the other class. I have to set --no-overlap=True to make it work.
