### ISSUE TITLE
Learnable resizer

### ISSUE THREAD

**Issue by Sumered** [ultralytics/yolov5#10430]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi!

Recently I wondered which interpolation in resize functions is the best for model final mAP and its capability to generalize well. After searching web for some time I stumbled across article which was promoting using small neural networks as Resizer for bigger neural networks which showed improvement compared to standard methods.

It should be possible to somehow use this idea in Yolo repository, despite the fact that when training custom datasets there are often multiple aspect ratios and image sizes in dataset which would complicate this whole thing to higher level than plug in additional network.

So is there any additional reason (apart from the fact that this is probably hard), to not use this solution?

Best regards

**Comment by glenn-jocher** [comment]
Sure, try it out!
