### ISSUE TITLE
How export to onnx with rectangular input shape?

### ISSUE THREAD

**Issue by tomyelrond** [ultralytics/yolov5#10444]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have a image dataset where each image has 1920x1080. My goal is to export trained model to ONNX with minimal padding. 

Do I understand correctly that the right way is to:
- train model with `--rect`argument and with `--img-size` for example 832 (the long side)
- export the trained model with similar aspect ratio as images 1920x1080. For example 832x480: `python export.py --weights model.pt --batch 1 --include onnx --img 480 832`

Is it right?

**Comment by JustasBart** [comment]
Hi, that looks good, this is how I would normally export my .onnx models to be used via OpenCV C++:

```
python3 export.py \
--weights runs/train/exp/weights/best.pt \
--imgsz 736 1280 \ # Height Width
--simplify \
--optimize \
--include onnx
```

**Comment by tomyelrond** [comment]
@JustasBart and you train with `--img 1280`? Do you use  `--rect` parameter for the training?

**Comment by JustasBart** [comment]
@tomyelrond Hi, I'm training my models via:

```
python3 train.py \
--data *PATH*/data.yaml \
--weights yolov5m6.pt \
--img 1280 \
--rect \
--batch -1 \
--epochs 300 \
--cache ram \
--device 0
```
etc...

**Comment by tomyelrond** [comment]
Do you use any alternative to mosaic augmentation when you train with `--rect` option?

I am still thinking how the exporting to ONNX works. Is it possible to export model trained with `--img 640x640` (without `--rect` ) to ONNX with input shape for example 832x480 (--img 480 832)? Are there any restrictions for exporting to ONNX? I can guess that aspect ratio of the trained model and exported model should be similar for good results.

**Comment by JustasBart** [comment]
@tomyelrond Sorry but I wouldn't be in a position to answer that, I'm nowhere near good enough with Python to investigate these sort of questions...

**Comment by bartlomiejgadzicki-digica** [comment]
@JustasBart hi, a quick question: for inference with your ONNX export, how do you handle input img pre-processing? Do you just resize it to the input size, or do you use letterbox and keep the original aspecr ratio with padding?

**Comment by glenn-jocher** [comment]
@bartlomiejgadzicki-digica, I can jump in here. For the sake of maintaining compatibility with the original YOLOv5 implementation, you should aim to replicate the letterbox resizing with padding exactly how it is done in the original implementation. That means adding padding in such a way that the aspect ratio of the input image is preserved and the aspect ratio of the output dimensions is the same as the input dimensions.

Here is an example of how you could resize your input image to the detection model's input size:

```python
import cv2

img_path = "/path/to/image.jpg"
img = cv2.imread(img_path)
img_width, img_height = img.shape[:2]

# Resize height and maintain aspect ratio
new_height = 640  # Model input size
new_width = int((new_height / img_height) * img_width)

# Resize
resized_img = cv2.resize(img, (new_width, new_height))

# Create padded image
max_dimension = max(new_width, new_height)
padded_img = np.zeros((max_dimension, max_dimension, 3), dtype=np.uint8)
padded_img[:new_height, :new_width, :] = resized_img

# BGR to RGB and normalize
padded_img = padded_img[..., ::-1].astype(np.float32) / 255.0

# Add required batch dimension (model expects batches of images)
input_batch = np.expand_dims(padded_img, axis=0)
```

This code will resize an image to 640xthe corresponding height while preserving the original aspect ratio. It then pads the image to make the width and height equal and in the same aspect ratio as the input. The image is then BGR-to-RGB swapped and normalized by dividing by 255. Finally, a batch dimension is added to the image to create a batch of size 1. You can then pass this image through the ONNX model for inference.

**Comment by bartlomiejgadzicki-digica** [comment]
@glenn-jocher thank you! I also made a separate more complex issue that's linked to this one, #11350. Could take a look into it as well?

**Comment by glenn-jocher** [comment]
@bartlomiejgadzicki-digica, I'd be happy to take a look at your `#11350` issue. However, please keep in mind that I can only provide general guidance and support via GitHub issues, and not actual debugging or coding work. Let me know if you have any questions or issues that I can help with!

**Comment by JustasBart** [comment]
@bartlomiejgadzicki-digica Just to answer your question, you can train a model and run inference directly on 544x320 without having to do any padding etc... (That's what I would do).

To train a model like so use something like:
```
python3 train.py \
--data YOUR_DATASET.yaml \
--weights yolov5s.pt \ # Choose your model
--img 544 \ # Give it the longest dimension, it will calculate the other dimension itself
--epochs 600 \ # Choose the number of Epochs
--batch -1 \ # This means to automatically calculate the maximum Batch Size
--device 0 \ # Run on GPU (Single GPU setup)
--rect # Non-Square model
```

To then export the model:
```
python3 export.py \
--weights YOUR_TRAINED_MODEL.pt \
--img 320 544 \ # Note that it's {H W] and NOT [W H] as you might expect
--include onnx \
--opset 12 # This is very important for the CPP example
```

Now your ONNX network will expect an image size of (544x320) so this is where on my C++ example I would capture a cv::Mat and pass it directly to:
```
cv::dnn::blobFromImage(YOUR_NETWORK, blob, 1.0/255.0, cv::Size(544, 320), cv::Scalar(), true, false);
net.setInput(blob);
```

Where the 'true' flag is to swap RB (BGR -> RGB) and the 'false' flag is not to crop (That is it will simply resize your input image of say for example 1080x1920 to 544x320). And just like that your inference would work.

However, if you don't want to train a --rect model you can just train a 544x544 model through the regular pipeline but then this is where your image would end up being stretched and squeezed and so that is where and why you would then use your padding etc... To essentially fill in the borders with no information as opposed to modifying (Stretching) your data.

Be aware that the 544x544 model would take longer to train/run inference and also the padding would also take time to implement/test etc... I have it implemented on my yolov8 CPP example [here](https://github.com/JustasBart/yolov8_CPP_Inference_OpenCV_ONNX.git) if you'd like to use that as a reference.

**Comment by glenn-jocher** [comment]
@JustasBart, JustasBart has provided an excellent explanation of how to train and export your model with input sizes of your choice. He recommends training a rectangular model with a longer edge of 544 and ensuring that your input image has the same aspect ratio at inference time. You can resize your input image to 544x320 (or any other rectangular aspect ratio) and the model will be able to handle it. Alternatively, you can train a square model with 544x544 and use letterbox padding to ensure that the aspect ratio of the input image is preserved at inference time. 

In terms of the ONNX model output, the input shape of the exported YOLOv5 ONNX model can be any size as long as it meets the requirements of the model architecture (e.g., number of input channels, input size, etc.). However, note that the expected input size of the model at inference time must match the model's input size or be scaled proportionally. If the input aspect ratio is not the same as the trained model, then it is necessary to pad or resize the input image accordingly.

**Comment by tomyelrond** [comment]
In my experience, rectangular training (argument `--rect`) gives poor results because there is no implementation of mosaic augmentation for rectangular training. It may be better to train with a default square input size and then export to onnx with a rectangular input size.

**Comment by bartlomiejgadzicki-digica** [comment]
I had the same idea, but in the end, I managed to get square inference for deployment, instead of a rectangular one.

**Comment by glenn-jocher** [comment]
@tomyelrond That's great to hear that you were able to get square inference for deployment! Square models tend to perform better, and they also typically require less complicated pre-processing in the inference pipeline since there is no need for padding or letterboxing. Also, note that for YOLOv5, the model's input shape affects the grid cell structure of the output predictions, so it's important to use the same input shape for training and inference. However, as we discussed earlier, you can still train with a square default input shape and then export the model to ONNX with a different rectangular input shape, but you would have to resize the input image to match the exported model's input shape for inference.

**Comment by JustasBart** [comment]
@glenn-jocher Well that just taught me something new... What's the point of --rect at all then? Should I ever use it then considering that I'm missing out on a whole augmentation?

**Comment by glenn-jocher** [comment]
@JustasBart `--rect` can be useful when training on images of varying aspect ratios. By using rectangular images, you can improve the ability of the model to generalize across different aspect ratios, as long as the aspect ratios are representative of the distribution of aspect ratios in your test data. However, as you mentioned, there is a downside to training with rectangular images: it is not as well-supported as square image training in some frameworks. Rectangular training can still be useful, but it requires more care and attention compared to square training. Similarly, if you plan to deploy your model with a square image input size, it may be beneficial to train with square images as well to avoid the need for additional processing during inference. Ultimately, the choice between square and rectangular training will depend on your specific use case and the distribution of aspect ratios in your training and test data.

**Comment by JustasBart** [comment]
@glenn-jocher That makes sense, and is there support for the **--rect** based mosaic augmentations in the future at all or not really?

**Comment by glenn-jocher** [comment]
@JustasBart I'm not sure about the specific plans for implementing support for mosaic augmentations in rectangular training with YOLOv5. However, it's worth noting that there are potential workarounds that you can explore if you decide to use rectangular training despite this limitation. For example, you could try using padding to make your images square during training, then crop them back to their original rectangular shape during training. Alternatively, you could try training with square images first to get a good initial model, then retrain the model with rectangular images using transfer learning. You could also try modifying the existing augmentations for square training to work with rectangular images.

**Comment by JustasBart** [comment]
@glenn-jocher Thank you very much for taking your time to reply, this is some rather valuable insight for me, all the best! :rocket:

**Comment by glenn-jocher** [comment]
@bartlomiejgadzicki-digica You're welcome! I'm glad that I could help. If you have any more questions or run into any issues with YOLOv5, feel free to reach out to the community or me for assistance. Good luck with your project!

**Comment by badziyoussef** [comment]
some models are made to work on a specific input format, like parsing id document, so in this case the model should have being trained with rect option to avoid unnecessary padding at inference time

**Comment by pderrenger** [comment]
@badziyoussef Thanks for sharing that perspective! You're right, for applications with consistent, non-square input shapes like ID documents, training with `--rect` can indeed be beneficial to match the inference input shape closely and potentially reduce padding. This aligns with the earlier discussion about choosing the training strategy based on the specific use case and data characteristics.
