### ISSUE TITLE
mAP_0.5:0.95 to mAP_0.5:0.90

### ISSUE THREAD

**Issue by uysalfurkan** [ultralytics/yolov5#10455]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to get mAP_0.5:0.90 rather than mAP_0.5:0.95. How can I change the source code ?

**Comment by developer0hye** [comment]
@uysalfurkan 

Try to set this variable, https://github.com/ultralytics/yolov5/blob/master/val.py#L162
