### ISSUE TITLE
\labels\train.cache' images and labels... 1416 found, 0 missing, 3 empty, 0 corrupt:

### ISSUE THREAD

**Issue by Overtrued** [ultralytics/yolov5#10458]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

train: Scanning 'datasets\NEU_1800\labels\train' images and labels... 1416 found, 0 missing, 3 empty, 0 corrupted: 100%|██████████| 1416/1416 [00:00<00:00, 1642.67it/s]
train: New cache created: datasets\NEU_1800\labels\train.cache
val: Scanning 'datasets\NEU_1800\labels\val' images and labels... 384 found, 0 missing, 1 empty, 0 corrupted: 100%|██████████| 384/384 [00:00<00:00, 1735.00it/s]
val: New cache created: datasets\NEU_1800\labels\val.cache

I used the customized dataset to train and found that there seems to be something wrong here. Is there a problem with my dataset,? Although I can still train normally.

**Comment by glenn-jocher** [comment]
@Overtrued your code is out of date. empty labels are treated as backgrounds.
