### ISSUE TITLE
Detections per class

### ISSUE THREAD

**Issue by jomdolalas** [ultralytics/yolov5#1046]
## ❔Question
Hi! You have this line of code in detect.py 
# Print results
                for c in det[:, -1].unique():
                    n = (det[:, -1] == c).sum()  # detections per class
                    s += '%g %ss, ' % (n, names[int(c)])  # add to string

How do I only print out detections of only one class like class[0] or detections of class[1]?

**Comment by NanoCode012** [comment]
Hi @jomdolalas , see the below.

https://github.com/ultralytics/yolov5/blob/7220cee1d1dc1f14003dbf8d633bbb76c547000c/detect.py#L160

**Comment by jomdolalas** [comment]
Thanks for the reply @NanoCode012 
but how do I get the sum of detections made by class 0? Or class 2? or 3?

**Comment by NanoCode012** [comment]
@jomdolalas , what do you mean sum? As seen in the `help` section above, you can pass multiple classes.

**Comment by jomdolalas** [comment]
@NanoCode012 sum of how many detections each class makes. 
For example, class 0 = 5 detections, class 2 = 2 detections, class 3 = 0 detections.
What variable in the code do I get it from?

**Comment by NanoCode012** [comment]
@jomdolalas 
https://github.com/ultralytics/yolov5/blob/7220cee1d1dc1f14003dbf8d633bbb76c547000c/detect.py#L101

I don't think there is an array saying `count = [5,2,0]` as you expect, but you can take the code above and store it in array or dictionary.

**Comment by jomdolalas** [comment]
@NanoCode012 I'm using this code currently, 

cv2.putText(im0, "Number of detections: {}".format(n),(30,30),   
cv2.FONT_HERSHEY_SIMPLEX, 1, (0,0,255),2)

and it counts bounding boxes for a specific class but I am unsure how to pin-point an exact class. I want it to show the detections only for class 0.

**Comment by NanoCode012** [comment]
@jomdolalas , couldn't you just pass `--class 0` then use the variable `n`?

**Comment by jomdolalas** [comment]
@NanoCode012 I can but the output will only show detections made by class 0. I wanted to know if there is a way to detect all classes but count only the detections of a specific class.

**Comment by NanoCode012** [comment]
@jomdolalas , I suggest you look at the `detect.py` code.

> cv2.putText(im0, "Number of detections: {}".format(n),(30,30),

If you want total number of detections, you could sum the variable `n`. If you want detections of a certain class, you can simple save `n` to a variable `temp` if `c == 0`, then use it.

https://github.com/ultralytics/yolov5/blob/7220cee1d1dc1f14003dbf8d633bbb76c547000c/detect.py#L100-L102

**Comment by jomdolalas** [comment]
@NanoCode012 What does c == 0 mean? Or what does this indicate? 
Sorry if stupid question, new to this coding thing.

**Comment by NanoCode012** [comment]
@jomdolalas 

`c` stands for class number, which in your case is 0. `c==0` would check if the you're doing detections for class 0. Another way would be to simply `count = (det[:, -1] == 0).sum()`

**Comment by jomdolalas** [comment]
@NanoCode012 Thank you very much! count = (det[:, -1] == 0).sum() seems to do the job! Thank you again!

**Comment by PraveenGit3** [comment]
Hi jomdolalas  does your count per class show detections on video ?  Should I give 

!python3 detect.py  --weights best.pt --source s.jpeg --classes 0 

where should I pass argument "n" or "count"

**Comment by jomdolalas** [comment]
@PraveenGit3 you can explore the function cv2.putText()

this adds text to the output video

**Comment by PraveenGit3** [comment]
Thanks for reply I'm new to opencv. I m able to generate individual id to each bounding box by writing function at 'plot_box' in predict.py . Now I want to count number of boxes by class like
Count of class A: 10
Count of class B : 15

Like this ?

**Comment by jomdolalas** [comment]
This is what i added

`cv2.putText(img, "Number of people inside: {}".format(n), (10, 20),
cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 2)`

the only class i used was persons, i havent tried it with multiple classes

**Comment by PraveenGit3** [comment]
I have written same line in plots.py in plot_one_box function despite that its not working ? 
<img width="976" alt="Screenshot 2021-07-13 at 23 22 56" src="https://user-images.githubusercontent.com/26325343/125532851-54084d4b-ae5d-4dcf-84dc-b0d869bb14ae.png">

**Comment by Sukh87** [comment]
On prediction i want to fetch the class name in variable. Can you please help me regarding this.
if class_name== ' anything' 
temp = class_name
something like that. My purpose is to fetch the predicted class in variable so I could use that variable with if statement

**Comment by glenn-jocher** [comment]
@Sukh87 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, etc.
# model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')  # custom trained model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!
