### ISSUE TITLE
Epochs. Start with 300 epochs. If this overfits early then you can reduce epochs. If overfitting does not occur after 300 epochs, train longer, i.e. 600, 1200 etc epochs.

### ISSUE THREAD

**Issue by Calviansyah** [ultralytics/yolov5#10464]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How we can know baout overfits or overfitting doesnt occur

**Comment by glenn-jocher** [comment]
@Calviansyah overfitting occurs when your validation losses stop decreasing and start to increase. At this point your model is memorizing the training data and no longer generalizing well.

**Comment by Calviansyah** [comment]
> 

oohh i see so the model is true cause it memorize the train not learn right? and where i can see or where i can know the validation stop decreasing? is it any graph or what?

**Comment by Alberto1404** [comment]
@Calviansyah check the graphs in runs/train. You can also check them during training via Tensorboard
