### ISSUE TITLE
Detection for small faces

### ISSUE THREAD

**Issue by Raymon360** [ultralytics/yolov5#10475]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

In this paper https://www.mdpi.com/1424-8220/22/15/5817 it mentions that it tries to cancel the default layer C5 (fifth convolution down sampling operation), and make appropriate adjustments in the feature fusion section, only leave C3 and C4 feature map for feature fusion to produce a lightweight algorithm. Then also add the sppf between the neck and head.

But I don't know how? can anyone help what i need to add/change?

### image
![image](https://user-images.githubusercontent.com/77184835/207012011-9922a4b7-18f0-4e7b-90e7-a8cd8a9be73e.png)
![image](https://user-images.githubusercontent.com/77184835/207011293-7e56820b-878e-4722-8182-c9ec1863f33b.png)
![image](https://user-images.githubusercontent.com/77184835/207011390-30ec1f7c-409b-4d8c-bed1-d9c9c3feaccc.png)

**Comment by glenn-jocher** [comment]
@Raymon360 we have a default P34 model here that lacks P5 outputs:
https://github.com/ultralytics/yolov5/blob/master/models/hub/yolov5-p34.yaml

**Comment by Raymon360** [comment]
> @Raymon360kami memiliki model P34 default di sini yang tidak memiliki keluaran P5: https://github.com/ultralytics/yolov5/blob/master/models/hub/yolov5-p34.yaml

if you want the SPPF to be added at the junction of the fusion network and the prediction head, does it need to be adjusted to P3(256) and P4(512) because SPPF says 1024?

![image](https://user-images.githubusercontent.com/77184835/208159697-ca23b42d-296d-4edb-9e27-e9d7143ff79a.png)
![image](https://user-images.githubusercontent.com/77184835/208170787-7a4e516a-7059-40c4-9f69-8d47a2b917dc.png)

**Comment by glenn-jocher** [comment]
Maxpool ops in SPPF at P3 will be redundant with downsampled P4 layer, but you can try anyway.

**Comment by Raymon360** [comment]
> Maxpool ops in SPPF at P3 will be redundant with downsampled P4 layer, but you can try anyway.

Am i doing this right?
Here I am trying to delete modules on layers 7 and 8 on the backbone because these layers represent the C5 sampling layer in feature extraction. Just like I changed the PAN fusion layer to BiFPN and added SPPF between the feature fusion network and the model prediction head
![image](https://user-images.githubusercontent.com/77184835/208294341-314f0902-8376-40b6-9aad-e73c9495b782.png)

**Comment by glenn-jocher** [comment]
@Raymon360 seems ok, but you have to try to actually run the yaml first and debug any issues. You can do this with:

```
python models/yolo.py --cfg YOUR_MODEL.yaml
```

**Comment by Raymon360** [comment]
> @Raymon360 seems ok, but you have to try to actually run the yaml first and debug any issues. You can do this with:
> 
> ```
> python models/yolo.py --cfg YOUR_MODEL.yaml
> ```
After I debugged, this is what I got.
Do you know why this tensor error appears?
![image](https://user-images.githubusercontent.com/77184835/208394154-f8fbc8d1-fdbc-4188-bf5b-f1d7e1caa55b.png)

**Comment by glenn-jocher** [comment]
input and output channel counts are not aligning. The input channel count of one module needs to be equal to the output of the previous. You need to debug to see where this error happens and match channels.

**Comment by Raymon360** [comment]
> input and output channel counts are not aligning. The input channel count of one module needs to be equal to the output of the previous. You need to debug to see where this error happens and match channels.

Can you tell me how to debug it? i don't know how

**Comment by Raymon360** [comment]
> input and output channel counts are not aligning. The input channel count of one module needs to be equal to the output of the previous. You need to debug to see where this error happens and match channels.

I want to ask, if I delete p5 on the backbone, is it necessary to change the input/output values of the other convolutions that pass through the SPPF?
For example: the output generated by SPPF becomes 512 because from p4 then the conv module afterwards becomes 256.

**Comment by Raymon360** [comment]
> > input and output channel counts are not aligning. The input channel count of one module needs to be equal to the output of the previous. You need to debug to see where this error happens and match channels.
> 
> I want to ask, if I delete p5 on the backbone, is it necessary to change the input/output values of the other convolutions that pass through the SPPF? For example: the output generated by SPPF becomes 512 because from p4 then the conv module afterwards becomes 256.

There are 2 pictures below. The top image is the default bifpn fusion feature, if I want a fusion feature like the image below which I circled in red, then I only need to add the convolution, upsampling and c3 modules. Am I right?
![image](https://user-images.githubusercontent.com/77184835/208833180-9419c3e3-8486-4eb2-a24f-2f037974a583.png)
<img width="121" alt="image" src="https://user-images.githubusercontent.com/77184835/208833519-03891cce-cc5d-4a3e-b48e-73291895666b.png">

**Comment by Raymon360** [comment]
@glenn-jocher

**Comment by glenn-jocher** [comment]
@Raymon360 I'm sorry, I don't have bandwidth to assist with custom model development. Perhaps another community member can be of use here.

**Comment by CesareDavidePace** [comment]
@Raymon360 I had the same problem, were you able to solve it? if yes, how?
