### ISSUE TITLE
when to update architectures?

### ISSUE THREAD

**Issue by guishilike** [ultralytics/yolov5#10472]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

"Our next release, v6.3 is scheduled for September and will bring official instance segmentation support to YOLOv5, with a major v7.0 release later this year updating architectures across all 3 tasks - classification, detection and segmentation."
It was said that the architecture would be updated.

**Comment by glenn-jocher** [comment]
@guishilike thanks for asking! We have a big architecture update coming early next year :)
