### ISSUE TITLE
Training a model again by adding more data using pretrained weights best.pt

### ISSUE THREAD

**Issue by bhupendramourya** [ultralytics/yolov5#10478]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How can I train my model again by adding more data and by using pretrained weights best.pt in yolov5.

**Comment by karantai** [comment]
check [this](https://github.com/ultralytics/yolov5/issues/10111)

**Comment by bhupendramourya** [comment]
> check [this](https://github.com/ultralytics/yolov5/issues/10111)

Thank you @karantai
