### ISSUE TITLE
SECOND STAGE CLASSIFIER 

### ISSUE THREAD

**Issue by Firqu3211** [ultralytics/yolov5#10481]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

when i set the classifier =True i keep getting errors like : 

modelc.load_state_dict(torch.load('resnet101.pth', map_location=device)['model']).to(device).eval()
KeyError: 'model'

and 
untimeError: Error(s) in loading state_dict for ResNet:
	size mismatch for fc.weight: copying a param with shape torch.Size([1000, 2048]) from checkpoint, the shape in current model is torch.Size([2, 2048]).
	size mismatch for fc.bias: copying a param with shape torch.Size([1000]) from checkpoint, the shape in current model is torch.Size([2])

could you please show me how to implement it because i've looked through the threads

**Comment by Firqu3211** [comment]
after going round all of that it runs but no inference output

**Comment by glenn-jocher** [comment]
@Firqu3211 second stage classifiers are advanced workflows that require significant user customization. For starters you need a separate classification model that **you have trained** on the same exact classes as your detection model.
