### ISSUE TITLE
CoreML: export failure. No module named 'coremltools.libmilstoragepython'

### ISSUE THREAD

**Issue by dokluch** [ultralytics/yolov5#10482]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Export

### Bug

Trying to export to CoreML on macOs under docker image yields the following results. Reinstalling coremltools does not help. 

```
PyTorch: starting from /mnt/prj/weights/12-12-2022/best.pt with output shape (1, 25200, 7) (14.4 MB)
TensorFlow version 2.11.0 has not been tested with coremltools. You may run into unexpected errors. TensorFlow 2.10.0 is the most recent version that has been tested.
Torch version 1.13.0 has not been tested with coremltools. You may run into unexpected errors. Torch 1.12.1 is the most recent version that has been tested.
CoreML: export failure ❌ 1.1s: No module named 'coremltools.libmilstoragepython'
```

### Environment

- Macbook M1 Max
- Docker with ultralytics/yolov5:latest-arm64 image

### Minimal Reproducible Example

```
 python3 export.py --weights "/mnt/prj/weights/12-12-2022/best.pt" --half --include coreml
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@dokluch hi! We run daily CI on all export formats but not in our Docker images unfortunately. A quick fix might be to try your export in our CPU image or maybe Colab.
