### ISSUE TITLE
How to export to CoreML with proper model metadata?

### ISSUE THREAD

**Issue by dokluch** [ultralytics/yolov5#10483]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi! I'm trying to export the custom-trained model with just two classes to use with CoreML in a Vision app.
Is it possible to provide the required metadata like class names, model descriptions, etc., so XCode recognizes that, like with other models?

**Comment by glenn-jocher** [comment]
@dokluch you could customize the code to add this. If you do so please consider submitting a PR to help other users, thanks!

**Comment by ryouchinsa** [comment]
To add metadata to the Core ML model file, you can use this code.

```
import coremltools

coreml_model = coremltools.models.MLModel('yolov5s.mlmodel')
coreml_model.short_description = "This is the yolov5s model."
labels = [
    "person", "bicycle", "car", "motorbike", "aeroplane", "bus", "train", "truck", "boat", "traffic light",
    "fire hydrant", "stop sign", "parking meter", "bench", "bird", "cat", "dog", "horse", "sheep", "cow",
    "elephant", "bear", "zebra", "giraffe", "backpack", "umbrella", "handbag", "tie", "suitcase", "frisbee",
    "skis", "snowboard", "sports ball", "kite", "baseball bat", "baseball glove", "skateboard", "surfboard", "tennis racket", "bottle",
    "wine glass", "cup", "fork", "knife", "spoon", "bowl", "banana", "apple", "sandwich", "orange",
    "broccoli", "carrot", "hot dog", "pizza", "donut", "cake", "chair", "sofa", "pottedplant", "bed",
    "diningtable", "toilet", "tvmonitor", "laptop", "mouse", "remote", "keyboard", "cell phone", "microwave", "oven",
    "toaster", "sink", "refrigerator", "book", "clock", "vase", "scissors", "teddy bear", "hair drier", "toothbrush"
]
coreml_model.user_defined_metadata['classes'] = ",".join(labels)
coreml_model.save('yolov5s.mlmodel')
```

**Comment by ryouchinsa** [comment]
We read this comment and implemented the export_coreml function onto the current YOLOv5 version.
https://github.com/ultralytics/yolov5/issues/7011#issuecomment-1086632697

Usage:
`python export.py --weights yolov5s.pt --include coreml`

When double clicking the .mlmodel, Xcode shows the metadata and preview tab.
We attached the export.py.txt, when you use, please rename to export.py.

![スクリーンショット 2022-12-21 19 43 13](https://user-images.githubusercontent.com/1954306/208886636-388998c2-840e-46b1-b00e-3dd581e14bcf.png)

[export.py.txt](https://github.com/ultralytics/yolov5/files/10276955/export.py.txt)

**Comment by jj0hns0n** [comment]
☝️ this one right here works!! After much frustration on this issue and trying many variations of proposed fixes, this one from @ryouchinsa works. Thank you! 

As others have mentioned the confidence numbers do seem high especially for false positives. 
<img width="1063" alt="Screenshot 2023-01-16 at 11 20 02 AM" src="https://user-images.githubusercontent.com/506078/212753344-635ee4a1-0c64-4941-bd44-d3ccc9371ec4.png">
