### ISSUE TITLE
What metric define which detection will be true positive or not

### ISSUE THREAD

**Issue by karantai** [ultralytics/yolov5#10480]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

In a validation batch, I observed that some of my detections had 0.3 confidence, so I suppose the model took them as true positive. In other cases, some labelled objects could not be detected by the model, so no bounding boxes were created around them in val_batch (not even with a low confidence).
So my question is which is the metric that defines the threshold above which the bounding boxes will be plotted, that is the model would consider them as true positives?

**Comment by glenn-jocher** [comment]
@karantai I think you're asking about --conf-thresh argument. This sets the threshold for declaring a detection:
https://github.com/ultralytics/yolov5/blob/357cde9ee7da13ba3095995488c5a23631467f1a/detect.py#L225

**Comment by karantai** [comment]
I mean, these results occured during train.py and val.py, the conf-thres you mentioned above regards detect.py. Is this the same thing?

**Comment by karantai** [comment]
![val_batch1_pred](https://user-images.githubusercontent.com/82314287/207277184-9f40b5f4-03d2-435e-9419-5b5ec37367cd.jpg)

While training, I have also a validation set so mAP and other metrics can be computed.
Please check the second row, last column. A vessel with confidence 0.3 has been computed, but why though? Which is the confidence threshold in val.py? I do not want detections with this low confidence to be considered as true positives.
No detect.py has been used.

**Comment by glenn-jocher** [comment]
@karantai 0.25 is used as the visualization threshold, but --conf 0.001 is used for mAP
