### ISSUE TITLE
How to convert yolov5s.pt model to yolov5s.torchscript.ptl  ?

### ISSUE THREAD

**Issue by HripsimeS** [ultralytics/yolov5#10490]
Hello. I used your export.py file https://github.com/ultralytics/yolov5/blob/master/export.py to convert **pt** to **torchscript**
python export.py --weights yolov5s.pt --include torchscript

But in fact I need to convert my model to **.torchscript.pt** or preferably to **.torchscript.ptl** format. 

UPDATE: I did the following modifications in your  https://github.com/ultralytics/yolov5/blob/master/export.py and it works!!

LOGGER.info(f'\n{prefix} starting export with torch {torch.__version__}...')
fl = file.with_suffix('.torchscript.ptl')
ts = torch.jit.trace(model, im, strict=False)
d = {"shape": im.shape, "stride": int(max(model.stride)), "names": model.names}
extra_files = {'config.txt': json.dumps(d)}  # torch._C.ExtraFilesMap()
if optimize:  
      optimize_for_mobile(ts)._save_for_lite_interpreter(str(fl), _extra_files=extra_files)
else:
      ts.save(str(fl), _extra_files=extra_files)
return fl, None

**Comment by smreo3839** [comment]
I have the same problem. How did you solve the problem?

**Comment by glenn-jocher** [comment]
@smreo3839 hello, 

I see that you are also looking to convert your YOLOv5 model to either .torchscript.pt or preferably to .torchscript.ptl format. Glad to hear that you found a solution to the problem. 

Your modification of the export.py script seems to be working for you. Thank you for sharing this with the community. If you have any further questions or concerns, feel free to ask. We are always happy to help.

Best regards, 
Glenn Jocher

**Comment by nitec427** [comment]
@glenn-jocher Please could you add also an option for ptl just like he described.

**Comment by glenn-jocher** [comment]
@nitec427 absolutely, I appreciate the feedback! I'll discuss the addition of .ptl support with the team. Your input is valuable in enhancing our tools. Thank you for reaching out and feel free to share any further suggestions or questions.

Cheers!

**Comment by Sh1-Zu3** [comment]
tks you so much

**Comment by glenn-jocher** [comment]
You're welcome! I'm glad to hear that the information was helpful. If you have any further questions or run into any issues, feel free to ask. The YOLOv5 community and the Ultralytics team are here to help!

If you haven't already, make sure to check out our [documentation](https://docs.ultralytics.com/yolov5/tutorials/model_export/) for more detailed guides and examples on model export and other functionalities.

Happy coding! 🚀
