### ISSUE TITLE
Illegal Instruction (core dumped) - on Detect_pcap.py program 

### ISSUE THREAD

**Issue by a0ramk03** [ultralytics/yolov5#10492]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am following the Ouster Object detection with YOLOv5 documentation on my Jetson-TX2. In order for the YOLOv5 to read the pcap packets created by the Ouster LiDAR, it needs to run a conversion program called detect_pcap.py on it. I have updated all dependencies to the correct versions as I've seen on other forum posts. I am no longer receiving any pre-execution errors. However it returns an Illegal Instruction (core dumped) error when it runs the DetectMutliBackend class. I have not changed any syntax from the original repository. What is the issue? Thanks.

![Screenshot from 2022-12-13 16-01-33](https://user-images.githubusercontent.com/117603790/207442762-4052b211-c849-4ec9-9201-f9fea85b1d78.png)

**Comment by AyushExel** [comment]
@a0ramk03 can't really say too much about the custom script you're trying to run but if you're not facing any problems while running detect.py from official yolov5 repo, then the problem is with that custom script

**Comment by a0ramk03** [comment]
Thank you for replying so quickly, I was on break so I didn't respond back as quick as I would have liked to. 
I just tried running detect.py after installing the correct repositories, and I am getting the same error as I did before. So the issue isn't related to the custom script.  

![Screenshot from 2023-01-09 16-25-15](https://user-images.githubusercontent.com/117603790/211411573-10712dd5-3bc8-4db1-b307-ae3bc774232a.png)

**Comment by glenn-jocher** [comment]
@a0ramk03 no worries! I understand. The 'Illegal Instruction (core dumped)' message often indicates a mismatch between the processor architecture the software was compiled for and the one running it. Are you sure your Jetson-TX2's architecture is compatible with the YOLOv5 binaries you're using? It may be worth checking the architecture compatibility and recompiling or obtaining the correct binaries if necessary.
