### ISSUE TITLE
Detection for source with multiple streams is failing

### ISSUE THREAD

**Issue by hdnh2006** [ultralytics/yolov5#10498]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

Hello, it seems something is broken with detection in multiple streams (`streams.txt`)

When I try with old versions of yolov5, it works, so, maybe some change has affected the detection of rtsp cameras.

```
python detect.py --source streams_all.txt --device cpu
detect: weights=yolov5s.pt, source=streams_all.txt, data=data/coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=cpu, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
YOLOv5 🚀 v7.0-33-g1752768 Python-3.8.10 torch-1.10.0+cu102 CPU

Fusing layers... 
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients, 16.4 GFLOPs
Traceback (most recent call last):
  File "detect.py", line 261, in <module>
    main(opt)
  File "detect.py", line 256, in main
    run(**vars(opt))
  File "/home/ubuntu/.local/bin/.virtualenvs/yolov5/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 111, in run
    dataset = LoadImages(source, img_size=imgsz, stride=stride, auto=pt, vid_stride=vid_stride)
  File "/home/ubuntu/yolov5/utils/dataloaders.py", line 253, in __init__
    raise FileNotFoundError(f'{p} does not exist')
FileNotFoundError: /home/ubuntu/yolov5/rtsp:/user:pass@url.net:554/h264/ch1/main/av_stream does not exist

```

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by hdnh2006** [comment]
Ok, false alarm. It seems from this ( https://github.com/ultralytics/yolov5/commit/5dc1ce4e865960f5b5dfe4e4f5148a4731433bca) commit several things has changed.

I loved the way to call them "`streams.txt`" ☹

**Comment by glenn-jocher** [comment]
@hdnh2006 for streaming sources just change `--source streams.txt` to `--source your_file.streams` and everything should work as before. If this doesn't work then please submit a bug report.

The new *.streams suffix will identify it as a streaming source file now. *.txt is now used for a list of (local) general images and videos.
