### ISSUE TITLE
segment predict ， How to use --save txt

### ISSUE THREAD

**Issue by ziyeibin** [ultralytics/yolov5#10497]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, how can I use the txt generated by segment predict -- save txt? I want to use the labelme-json-to-dataset method like labelme to generate a label image。I just learned python and yolo, and I don't know much about this. thank you

**Comment by glenn-jocher** [comment]
@ziyeibin segment/predict.py --save-txt creates txt file predictions that you can use to train new models as they are in the same format as segmentation annotations. See COCO128-seg for an example segmentation dataset, i.e. to download automatically:

```
python segment/train.py --data coco128-seg.yaml
```
