### ISSUE TITLE
AttributeError: 'float' object has no attribute 'round'

### ISSUE THREAD

**Issue by universewill** [ultralytics/yolov5#1049]
get error when training on custom data:

```  
File "train.py", line 459, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 250, in train
    accumulate = max(1, np.interp(ni, xi, [1, nbs / total_batch_size]).round())
AttributeError: 'float' object has no attribute 'round'
```

**Comment by universewill** [comment]
updata numpy version according to requirement

**Comment by amir-athari** [comment]
Same problem here. Get this error when using numpy 1.19.4 in vscode
AttributeError: 'float' object has no attribute 'round'

**Comment by xieyj17** [comment]
I got a similar problem. My numpy version is 1.19.4

`a = 1.23`

`round(a,1) # this one would work`

`
a.round(1) # this one gives me error message "AttributeError: 'float' object has no attribute 'round'"
`

**Comment by glenn-jocher** [comment]
@xieyj17 round() by itself is a python op which will be slower on numpy arrays.

@xieyj17 @seedergy where exactly in the code are you seeing this error? Can you provide a reproducible example, i.e. in our colab notebook please?

**Comment by glenn-jocher** [comment]
@seedergy @universewill @xieyj17 I am not able to reproduce this issue. I installed `numpy==1.19.4` in the colab notebook and trained correctly without issue.
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

<img width="1609" alt="Screen Shot 2020-12-24 at 11 47 38 AM" src="https://user-images.githubusercontent.com/26833433/103104759-0098c400-45de-11eb-96a9-dec953c457dd.png">
