### ISSUE TITLE
About training image size

### ISSUE THREAD

**Issue by Heartful-echo** [ultralytics/yolov5#10493]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi

I collected penguin images from google search.
want to learn to detect penguins using YOLOv5.
The images of penguins I got from a google search are of different sizes.
Is it okay to run annotation using images with this different size?
Or will it be resized to 640x640 and then annotated?

**Comment by JustasBart** [comment]
Hi, the YOLO annotations are normalised to the range of 0.0 to 1.0 when you label your dataset, this means that ultimately it shouldn't really matter that your images are of different sizes/formats etc... It'll depend on you on what the model size you'd like to end up with in the end.

I'm like 98% sure on this, but if anyone wants to reinforce this answer that would be great, in the mean time though have fun detecting penguins!

Hope that helps!

**Comment by Heartful-echo** [comment]
@JustasBart 

Thank you!!
your explanation is very good!
I agreed.
