### ISSUE TITLE
What is the project python code format?

### ISSUE THREAD

**Issue by erquren** [ultralytics/yolov5#10495]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When i use vscode yapf format this project,so many line code format is change，when i use autopep8 , the same problem .Can you  give a format file or other thing?

**Comment by glenn-jocher** [comment]
@dongqianzhuan YOLOv5 uses YAPF formatter:

https://github.com/ultralytics/yolov5/blob/b2f94e8c356083bb85d76a60ea2b54d5ad9fbe36/setup.cfg#L45-L54
