### ISSUE TITLE
How to train classifier and use flip and jitter on training image

### ISSUE THREAD

**Issue by xjohnxjohn** [ultralytics/yolov5#105]
1. How to train classifier like the original of yolov3.
2. How to use flip to enable or disable on image and jitter also.

**Comment by glenn-jocher** [comment]
@xjohnxjohn a classifier can be easily constructed by joining an existing backbone from any of the model *.yaml files with a nn.AdaptiveAvgPool2d(1) layer followed by a Flatten() layer.
https://github.com/ultralytics/yolov5/blob/a557b7d924c605d573f4f0e64c1bc3702276d9e8/models/common.py#L73-L77

You'd have to built the training infrastructure as well, including a classifier-focused dataloader.

Augmentation is set by the hyperparameters in train.py and in the dataloader.
https://github.com/ultralytics/yolov5/blob/a557b7d924c605d573f4f0e64c1bc3702276d9e8/utils/datasets.py#L258

**Comment by ZeKunZhang1998** [comment]
> @xjohnxjohn a classifier can be easily constructed by joining an existing backbone from any of the model *.yaml files with a nn.AdaptiveAvgPool2d(1) layer followed by a Flatten() layer.
> 
> https://github.com/ultralytics/yolov5/blob/a557b7d924c605d573f4f0e64c1bc3702276d9e8/models/common.py#L73-L77
> 
> You'd have to built the training infrastructure as well, including a classifier-focused dataloader.
> 
> Augmentation is set by the hyperparameters in train.py and in the dataloader.
> 
> https://github.com/ultralytics/yolov5/blob/a557b7d924c605d573f4f0e64c1bc3702276d9e8/utils/datasets.py#L258

But when I use my dataset,should I train the classifier independently?
