### ISSUE TITLE
How to custom activation function

### ISSUE THREAD

**Issue by yusnisyahmi93** [ultralytics/yolov5#10509]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

![Screenshot_20221216-024309_WPS Office](https://user-images.githubusercontent.com/45413568/207941903-274dbfcb-2fcf-4301-a139-d3cfdb3ebec2.jpg)

how can i custom and add this activation function? since i edit activation.py file and common.py still cannot run this activation function, error still come out. i need your help please

### Additional
AttributeError: module 'torch.nn' has no attribute 'Sigmoid_Tanh'

_No response_

**Comment by glenn-jocher** [comment]
@yusnisyahmi you can define any activation and then use it common.py, but if you define it in an external file like activations.py you'll need to import it in common.py first.

**Comment by yusnisyahmi93** [comment]
@glenn-jocher 
![image](https://user-images.githubusercontent.com/45413568/208241911-eb368fc8-0ef2-4402-9fba-84838ae07258.png)
![image](https://user-images.githubusercontent.com/45413568/208241944-d14b842d-67bd-4f81-a46b-98d0e2879d4c.png)
![image](https://user-images.githubusercontent.com/45413568/208241970-4f34a2cb-28f2-4760-83d2-456936f4c20f.png)


hi i still got same error  AttributeError: module 'torch.nn' has no attribute 'Sigmoid_Tanh'. i dont get it where is the part i missing? kindly need your help. thank you.
https://www.scirp.org/journal/paperinformation.aspx?paperid=114024

and this is paper i refer to

**Comment by yusnisyahmi** [comment]
> @yusnisyahmi you can define any activation and then use it common.py, but if you define it in an external file like activations.py you'll need to import it in common.py first.

https://www.scirp.org/journal/paperinformation.aspx?paperid=114024 

and this is paper i refer to

**Comment by yusnisyahmi93** [comment]
@glenn-jocher hi please help me

**Comment by yusnisyahmi93** [comment]
@glenn-jocher hi kindly need your feedbacks. thank you

**Comment by glenn-jocher** [comment]
@yusnisyahmi you're trying to import a module that doesn't exist. See torch docs for more info. https://pytorch.org/docs/stable/index.html
