### ISSUE TITLE
map

### ISSUE THREAD

**Issue by HuLu65** [ultralytics/yolov5#10507]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

After the training was over, the detection metrics of the model were printed, and I wanted to know the difference between best/map and mtrics/map

### Additional

![image](https://user-images.githubusercontent.com/82073527/207933856-b0acc66d-256d-4898-857c-12839ce68ec5.png)

**Comment by HuLu65** [comment]
> 
After each training of all epochs, there will be a training summary, there are some indicators in the training summary, I want to know what best/map50 and metrics/map50 represent, are these two calculated with two different models (maybe: best.pt and last.pt)

**Comment by HuLu65** [comment]
> luhu65
I also want to know the code piece that does the training summary I didn't find it

**Comment by glenn-jocher** [comment]
Hey luhu65 👋,

The "best/map50" refers to the highest mAP @HuLu65.5 value achieved during training, while "metrics/map" represents the mAP@0.5 value of the final model. These numbers help in evaluating the model's detection performance during and after training.

The training summary is located in the `train.py` script within the `utils` subdirectory of the YOLOv5 repository. You can find more detailed information about training outputs and how they are calculated in the documentation at https://docs.ultralytics.com/yolov5/.

Let me know if you need any further assistance!
