### ISSUE TITLE
YOLOV detecting and cropping

### ISSUE THREAD

**Issue by Mansurjons** [ultralytics/yolov5#10506]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

my YOLOV detecting CAT, DOG, Chikken and Horse Labels Now I need crop just DOG label
when I use save crop Yolov saving all 4 labels 
YOLOV need to detect all 4 labels and need crop just one 

That's possible???

**Comment by barney2074** [comment]
I'd start by looking at https://github.com/ultralytics/yolov5/blob/master/detect.py and how the --classes and --save-crop arguments work.

If you just want a quick & dirty solution (with hardcoded classes), you could probably modify a couple of lines such as https://github.com/ultralytics/yolov5/blob/master/detect.py#L151

**Comment by glenn-jocher** [comment]
@Mansurjons i.e. for dogs (class 16):
```
python detect.py --classes 16 --save-crop
```

**Comment by Mansurjons** [comment]
@glenn-jocher Thank you

but if I made classes 16 it will only detect dog and crop, it doesn't detect 15-14-13-12 classes 


I need detect 12-13-14-15-16 classes and crop just 16 class

**Comment by barney2074** [comment]
that's what I meant- combination of both not possible with standard Yv5, but should be an easy modification of detect.py.
The other obvious alternative is to run inferencing twice (assuming input like mp4 or jpg) with different settings and merge the results

**Comment by Mansurjons** [comment]
@barney2074 yes I got you bro Thanks

**Comment by glenn-jocher** [comment]
@Mansurjons pass whatever you want to --classes:

```
python detect.py --classes 12 13 14 15 16
```
