### ISSUE TITLE
classify/val.py results are not saved

### ISSUE THREAD

**Issue by maxsitt** [ultralytics/yolov5#10518]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Validation

### Bug

Even though printed to the console, the validation results from classify/val.py are currently not saved to file. Only a empty folder is created.

### Environment

YOLO: YOLOv5 v7.0-34-g1ae9194 torch-1.13.0+cu116 CUDA:0 (Tesla T4, 15110MiB)
Python:  Python-3.8.16
OS: Ubuntu 18.04.6 LTS

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@maxsitt yes you are correct, there are simply no plots or images to save with classification currently, though you can pass --save-txt to save classification results in *.txt file format.
