### ISSUE TITLE
Class Activation Map Re-check

### ISSUE THREAD

**Issue by bzha5848** [ultralytics/yolov5#10519]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Hi there,

I'm wondering if the lastest version has the feature of Class Activation Map? As I'm currently forced by my supervisor to do this job but found that the old grad-cam https://github.com/pooya-mohammadi/yolov5-gradcam is not working anymore?

Any advice for that?

Thanks so much!!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
I don't know what Class Activation Map is.
