### ISSUE TITLE
Outputs of TF classification models in DetectMultiBackend should not be normalized to pixels

### ISSUE THREAD

**Issue by lzrvch** [ultralytics/yolov5#10512]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

[This operation](https://github.com/ultralytics/yolov5/blob/1ae91940abe9ca3e064784bb18c12271ab3157b4/models/common.py#L581)
in DetectMultiBackend's forward should be skipped for classification models

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@lzrvch hi there! Thank you for bringing this to our attention. Your willingness to submit a PR is greatly appreciated. We'll review your proposed changes thoroughly to ensure they align with YOLOv5's design principles. If you have any further questions or need assistance with the PR, feel free to ask. Your contributions are valuable to the YOLO community.
