### ISSUE TITLE
Give an easy option to visualize neurons for explainability

### ISSUE THREAD

**Issue by NormanTUD** [ultralytics/yolov5#10525]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

It would be a great addition to have a simply-working script that you give a model file and that goes through each neuron in the output category and create an image for it, showing what it most reacts too.

I do *not* mean these images, that are, afaik, the only ones Yolo can currently generate:

![](https://user-images.githubusercontent.com/26833433/131359874-ecc9aef8-1c9b-44f5-ac17-d6b987093554.png)

But images like these:

![](https://github.com/keisen/tf-keras-vis/raw/master/docs/examples/images/visualize-dense-layer.png)

(From https://github.com/keisen/tf-keras-vis )

I have not found a version that can simply do these graphs from YoloV5 models, but I would greatly appreciate this.

### Use case

By everyone who want's to see what the network has really learnt.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@NormanTUD hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
