### ISSUE TITLE
How to change Font style of LABEL ???

### ISSUE THREAD

**Issue by Mansurjons** [ultralytics/yolov5#10521]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

 want to make BOLD with other STYLE

**Comment by barney2074** [comment]
the Yolov5 code is well structured & logical- in this case, refer to the annotator class in utils/plot.py or the settings in utils/general.py
In case you can't find what you are looking for, a quick search in Github/Yolov5 for 'font' will help you
https://github.com/ultralytics/yolov5/search?q=font
![image](https://user-images.githubusercontent.com/25944617/208236900-3886e7a4-5d31-4f16-bf4a-0ebc68050502.png)

**Comment by Mansurjons** [comment]
thank you friend

**Comment by glenn-jocher** [comment]
@Mansurjons you're welcome! If you have any more questions, feel free to ask. Good luck with your customization!
