### ISSUE TITLE
Shuffle validation when training

### ISSUE THREAD

**Issue by kevinconka** [ultralytics/yolov5#10520]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello!

I am using clearML to visualise the training, everything works fine but my "DEBUG_SAMPLES" are sorted based on the image filename. My dataset consists of sequences of images therefore the "DEBUG_SAMPLES" all look very similar.

<img width="970" alt="image" src="https://user-images.githubusercontent.com/35779409/208142539-2038cd21-914b-42aa-a55a-4c98c1ec62ef.png">

I have reached out to clearML and they suggested to add `shuffle=True` in `val.py`. However this did not work.
<img width="991" alt="image" src="https://user-images.githubusercontent.com/35779409/208143519-d10f941c-cd2b-4204-ab90-0fe28d0654db.png">

Am I missing something?

**Comment by glenn-jocher** [comment]
@kevinconka validation dataset is sorted by aspect ratio for minimum validation FLOPs using rectangular inference. If you try to pass `shuffle=True` with `rect=True` you will see a warning:
https://github.com/ultralytics/yolov5/blob/b2f94e8c356083bb85d76a60ea2b54d5ad9fbe36/utils/dataloaders.py#L119-L121

**Comment by kevinconka** [comment]
Hi @glenn-jocher 

Thanks for your reply! I have just tried setting `rect=False` but I still get the same DEBUG_SAMPLES. Any other ideas I might try?

<img width="986" alt="image" src="https://user-images.githubusercontent.com/35779409/208634277-c46e06f7-d2a4-4129-9f05-b553469e1a57.png">

**Comment by glenn-jocher** [comment]
@kevinconka Try setting the `--aspect-ratio-group-factor` flag in `val.py` to a larger value, like 3 or 4. This will group images by aspect ratio, which may help diversify your `DEBUG_SAMPLES`. You can find more details in the Ultralytics Docs: https://docs.ultralytics.com/yolov5/
