### ISSUE TITLE
What to do with the operations not supported by the Edge TPU?

### ISSUE THREAD

**Issue by mhaghighat** [ultralytics/yolov5#10527]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am exporting the model to edgetpu using:
`python export.py --weights yolov5n.pt --include edgetpu --optimize --simplify
`

The report says:

```
Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 242
Number of operations that will run on CPU: 20

Operator                       Count      Status

RESHAPE                        3          Mapped to Edge TPU
RESHAPE                        3          Operation is otherwise supported, but not mapped due to some unspecified limitation
RESIZE_NEAREST_NEIGHBOR        2          Mapped to Edge TPU
CONV_2D                        60         Mapped to Edge TPU
LOGISTIC                       63         Mapped to Edge TPU
LOGISTIC                       3          More than one subgraph is not supported
MUL                            6          More than one subgraph is not supported
MUL                            69         Mapped to Edge TPU
QUANTIZE                       1          More than one subgraph is not supported
QUANTIZE                       1          Operation is otherwise supported, but not mapped due to some unspecified limitation
QUANTIZE                       5          Mapped to Edge TPU
STRIDED_SLICE                  3          More than one subgraph is not supported
STRIDED_SLICE                  6          Mapped to Edge TPU
MAX_POOL_2D                    3          Mapped to Edge TPU
ADD                            1          More than one subgraph is not supported
ADD                            9          Mapped to Edge TPU
PAD                            7          Mapped to Edge TPU
CONCATENATION                  1          Operation is otherwise supported, but not mapped due to some unspecified limitation
CONCATENATION                  15         Mapped to Edge TPU
CONCATENATION                  1          More than one subgraph is not supported

```

If possible, **consider updating your model to use only operations supported by the Edge TPU**. I wonder if anyone has done this and what operations should be changed in the model. 

Thank you!

**Comment by glenn-jocher** [comment]
@mhaghighat don't know, ask this on the TF or Edge TPU forums.

**Comment by hardikdava** [comment]
@mhaghighat `optimize` and `simplify` options do not support for edgetpu export. Use following command with image size which is very important for compiling model correctly. Even if some of the operation is not compiled correctly then they will run on CPU but you will not have any issue with inference.

```
python export.py --weights yolov5n.pt --include edgetpu --imgsz 320
```

if you train custom models then it is fully optimized for edgetpu. See following output for model trained on custom dataset. 


```
Operator                       Count      Status

LOGISTIC                       57         Mapped to Edge TPU
CONCATENATION                  14         Mapped to Edge TPU
PAD                            6          Mapped to Edge TPU
MAX_POOL_2D                    3          Mapped to Edge TPU
RESHAPE                        4          Mapped to Edge TPU
ADD                            9          Mapped to Edge TPU
CONV_2D                        53         Mapped to Edge TPU
QUANTIZE                       5          Mapped to Edge TPU
STRIDED_SLICE                  6          Mapped to Edge TPU
MUL                            63         Mapped to Edge TPU
RESIZE_NEAREST_NEIGHBOR        2          Mapped to Edge TPU
Compilation child process completed within timeout period.

```
May be @glenn-jocher can answer why coco trained model is not fully compiled for edgetpu.

**Comment by glenn-jocher** [comment]
@hardikdava must have to do with the higher output channel count, as the COCO trained models have 80 classes which may be higher than your custom model.

**Comment by mhaghighat** [comment]
@hardikdava What changes have you made to the model architecture in your custom model? Is it only the last layer that has less number of classes? Or have you changed any operations not supported by edge-tpu?

**Comment by hardikdava** [comment]
@mhaghighat I have only changed the number of classes. All other layers and model is same as default. Please also consider the actual size of the model.

**Comment by mhaghighat** [comment]
Thank you, @hardikdava! May I ask what you mean by considering the actual size of the model?

**Comment by hardikdava** [comment]
@mhaghighat Pleas read this carefully and understand it. EdgeTPU has limitations in terms of data format and memory. https://coral.ai/docs/edgetpu/compiler/#performance-considerations
