### ISSUE TITLE
What is the reason for ".permute" in the detect layer?

### ISSUE THREAD

**Issue by AlessandroMondin** [ultralytics/yolov5#10524]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I was studying carefully the Detect layer and I noticed that [h (https://github.com/ultralytics/yolov5/blob/master/models/yolo.py#L61)ere you opted to shape the output this way to then permute it back to shape (bs, n_scale_pred, grid_y, grid_x, 5+num_classes. Why you've pursued that way instead of 

`x[i] = x[i].view(bs, self.na, ny, nx,  self.no)` 
?

Thanks in advance!

**Comment by glenn-jocher** [comment]
@AlessandroMondin this is legacy from YOLOv3, but also an area that will be optimized in a future release in January 2023.

**Comment by AlessandroMondin** [comment]
Thanks a lot :-)

**Comment by glenn-jocher** [comment]
@AlessandroMondin you're welcome! If you have any more questions, feel free to ask. Your feedback is valuable to us.
