### ISSUE TITLE
CUDA error: no kernal image is available for execution

### ISSUE THREAD

**Issue by jaydeshpande** [ultralytics/yolov5#1053]
## 🐛 Bug
CUDA not working on docker image. GPU training fails. 

## To Reproduce (REQUIRED)

Input:
get latest docker image: https://hub.docker.com/r/ultralytics/yolov5

Follow steps per to run container: https://github.com/ultralytics/yolov5/wiki/Docker-Quickstart

python train.py --batch 4 --epochs 5 --data ./data/training.yaml --cfg ./models/yolov5s.yaml --weights ''

Output:

![image](https://user-images.githubusercontent.com/10604676/94373195-c3ea2900-00d1-11eb-9e71-f7a8ba137f05.png)

## Expected behavior
Training does not work on GPU. When container is created without --gpus all -- training works fine on CPUs.

**Comment by glenn-jocher** [comment]
@jaydeshpande thanks for the bug report. I am not able to reproduce your issue with the latest image today. You should verify your CUDA and nvidia driver installation, as the image appears to working correctly.

To pull and run image:
```bash
t=ultralytics/yolov5:latest && sudo docker pull $t && sudo docker run -it --ipc=host --gpus all $t
```

To train:
```bash
python train.py
```

Result:
<img width="1419" alt="Screen Shot 2020-10-04 at 7 03 03 PM" src="https://user-images.githubusercontent.com/26833433/95021932-4182db80-0674-11eb-923c-10093869433e.png">
