### ISSUE TITLE
Inference on GPU-images

### ISSUE THREAD

**Issue by andreas-roennestad** [ultralytics/yolov5#10530]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am working on an application that requires high performance. As part of the image processing I am doing I need to run inference on images that are already on the GPU as part of a pipeline of image processing where I cannot afford an additional transfer back and forth to the CPU. Is there a way to run inference without requiring the input images to be on the CPU?

**Comment by glenn-jocher** [comment]
Not sure what you mean by input images are required to be on CPU.

**Comment by andreas-roennestad** [comment]
> Not sure what you mean by input images are required to be on CPU.

To my understanding, the image to run inference on is memcopied to the device internally in the model() function. I wonder if there is a way to run inference on arrays that have been copied to device before running inference

**Comment by glenn-jocher** [comment]
@andreas-roennestad see https://github.com/ultralytics/yolov5/pull/10139

**Comment by Zephyr69** [comment]
Aren't images sent to the device explicitly here? https://github.com/ultralytics/yolov5/blob/5545ff3545d886417b4eff12203d1af4d758cc10/detect.py#L119

Is it not "running inference on arrays that have been copied to device"? You can just call the model() wherever you want after that.

**Comment by andreas-roennestad** [comment]
> Aren't images sent to the device explicitly here?
> 
> https://github.com/ultralytics/yolov5/blob/5545ff3545d886417b4eff12203d1af4d758cc10/detect.py#L119
> 
> Is it not "running inference on arrays that have been copied to device"? You can just call the model() wherever you want after that.

I am referring to running inference on arrays that are present on the array before running the function so as to have more control over time consuming memcopys

**Comment by andreas-roennestad** [comment]
> @andreas-roennestad see #10139

Thank you, but I cant see what you are referring to. Could you explain?
