### ISSUE TITLE
Running multiple streams at once, getting error in stream.txt for rtsp\.. and https\... links 

### ISSUE THREAD

**Issue by utkarsh-iitbhu** [ultralytics/yolov5#10538]
@glenn-jocher 
I want to run my yolov5 model on various CCTV footage simultaneously; I have created my stream.txt file where I have given IP addresses of different webcams. But it is showing me this error.

![image](https://user-images.githubusercontent.com/84759422/208626154-21a5f3ea-c10a-47e6-a393-a016b66f8fec.png)

It works fine for any video or image but shows an error for rtsp:\..... It is considering the entire path of stream.txt instead of the webcam link. I want to pass the webcam address only to my model.

![image](https://user-images.githubusercontent.com/84759422/208627001-0540b313-8414-498b-8563-21f73577bbb1.png)

This is my stream.txt; how can I access these links? Do let me know.

_Originally posted by @utkarsh-iitbhu in https://github.com/ultralytics/yolov5/issues/1100#issuecomment-1359041431_

**Comment by glenn-jocher** [comment]
@utkarsh-iitbhu file must be named *.streams

**Comment by utkarsh-iitbhu** [comment]
Thank you sir !!!

**Comment by snds83** [comment]
I 'd like to view multi camera in on window using yolov5 test, but there is just one camera from my 4 cctv cameras are viewing. how could i do that? please some help. this site of yolov5 that I have used.https://github.com/ultralytics/yolov5

**Comment by glenn-jocher** [comment]
@snds83 to view multiple cameras in one window, you can create a file `streams.txt` listing the paths/URLs of your cameras, e.g. 

```
https://cam1.com/stream.m3u8
https://cam2.com/stream.m3u8
rtsp://cam3.com/stream
rtsp://cam4.com/stream
```

Then run `python detect.py --source streams.txt`. For more information, please refer to our documentation at https://docs.ultralytics.com/yolov5/.

**Comment by JonSnow4243** [comment]
Hello YOLOv5 community,

I hope this message finds you well. I'm new to YOLOv5 and currently working on a project that involves multistreaming with YOLOv5. My goal is to run the YOLOv5 model on both my webcam and an IP camera simultaneously.

To achieve this, I created a streams.txt file and specified '0' for my webcam and 'rtsp://example' for my IP camera. However, I'm encountering the following error:

FileNotFoundError: /Users/Desktop/yolov5/0 does not exist

I also attempted to access only my IP camera through the streams.txt file, but encountered the same error:

FileNotFoundError: /Users/Desktop/yolov5/rtsp:/admin:Admin@example@sample does not exist

I've ensured that the paths are correct, but I'm still facing this issue. Could anyone please provide guidance on how to resolve this error and successfully implement multistreaming with YOLOv5?

Your assistance would be greatly appreciated.

Thank you.

**Comment by snds83** [comment]
hi JonSnow4243,
I faced the same error and still get just one camera work. then, I found this solution below which made that happened
(in the  ../utils/dataloaders.py in loadstreams made changes  as follow)
   425    if s == 60:  # TODO bypass source CAM 0 check

that worked for me. please check it hope it will work for you too.
regards,

**Comment by snds83** [comment]
hi JonSnow4243,
I faced the same error and still get just one camera work. then, I found this solution below which made that happened
(in the ../utils/dataloaders.py in loadstreams made changes as follow)
line 425     if s == 60: # TODO bypass source CAM 0 check

that worked for me. please check it hope it will work for you too.
regards,

**Comment by glenn-jocher** [comment]
Hello @snds83 and @snds83,

It's great to see the community helping each other out! Just to clarify, when specifying multiple streams, including a webcam, you should indeed create a `streams.txt` file with each stream source on a new line. For a webcam, typically you would use '0' for the default webcam, and for IP cameras, you would use the appropriate RTSP URL.

The `FileNotFoundError` suggests that the program is interpreting the stream source as a file path. This can happen if the format of the `streams.txt` is not recognized correctly. Make sure your `streams.txt` looks like this:

```
0
rtsp://example.com/stream
```

Regarding the modification in `dataloaders.py`, while it's great to see community-driven solutions, I would caution against making changes to the codebase unless you're comfortable with potential side effects. The line mentioned is part of a check to ensure the source is valid.

If you continue to experience issues, please ensure you're using the latest version of YOLOv5, as updates may contain fixes for such issues. If problems persist, you can raise an issue on the GitHub repository with detailed information about your setup and the exact error messages you're encountering.

Keep up the collaborative spirit! 🚀
