### ISSUE TITLE
How to incorporate different weights in training loss to compensate for class imbalance 

### ISSUE THREAD

**Issue by Aya-S** [ultralytics/yolov5#1054]
## ❔Question

How to incorporate different weights in training loss to compensate for class imbalance 
I'm on the v2.0 tag version and edited the pos_weight in the compute_loss function but am getting an error.
I'm unable to trace the function to debug the flow. can you please provide some pointers?

**Comment by glenn-jocher** [comment]
@Aya-S this is up to you to experiment with. I would recommend using latest code from master:
`git clone https://github.com/ultralytics/yolov5`
