### ISSUE TITLE
Environment does not support cv2.imshow() or PIL Image.show()

### ISSUE THREAD

**Issue by June-Joon** [ultralytics/yolov5#10540]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm a beginner who just started programming.

As a trial, while running the basic code provided by ULOV5, I found that when I tried to run webcam, it did not run with the following statement.

Just in case, I tried the basic colab tutorial, segment tutorial, classification tutorial, docker (cpu7.0), but only the same warning message came out and the webcam did not run.

I can't solve it by referring to other questions/answers similar to mine, so can I get some help?
I didn't change the code. I just run it.

```
!python detect.py --source 0  # webcam


detect: weights=yolov5s.pt, source=0, data=data/coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
YOLOv5 🚀 v7.0-42-g5545ff3 Python-3.8.16 torch-1.13.0+cu116 CUDA:0 (Tesla T4, 15110MiB)

Downloading https://github.com/ultralytics/yolov5/releases/download/v7.0/yolov5s.pt to yolov5s.pt...
100% 14.1M/14.1M [00:00<00:00, 238MB/s]

Fusing layers... 
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients
**WARNING ⚠️ Environment does not support cv2.imshow() or PIL Image.show()**

[ WARN:0@14.066] global /io/opencv/modules/videoio/src/cap_v4l.cpp (902) open VIDEOIO(V4L2:/dev/video0): can't open camera by index
Traceback (most recent call last):
  File "detect.py", line 261, in <module>
    main(opt)
  File "detect.py", line 256, in main
    run(**vars(opt))
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 106, in run
    dataset = LoadStreams(source, img_size=imgsz, stride=stride, auto=pt, vid_stride=vid_stride)
  File "/content/yolov5/utils/dataloaders.py", line 367, in __init__
    assert cap.isOpened(), f'{st}Failed to open {s}'
AssertionError: 1/1: 0... Failed to open 0
```

**Comment by glenn-jocher** [comment]
@June-Joon webcam inference only works for local webcams, i.e. running YOLOv5 in a local python environment on a laptop webcam.

**Comment by June-Joon** [comment]
@glenn-jocher 
The same error message comes out when running on docker.
Isn't the docker image a local python environment?

**Comment by glenn-jocher** [comment]
@June-Joon since Docker is a standalone terminal environment it does not have access to create popup windows in your base environment.

**Comment by sbowers865** [comment]
Its most definitely possible to render a gui window on the host machine from a routine that lives in a docker container. Has anyone else managed to do this for the ultralytics yolo? it should be as simple as running with priviliges, mounting $DISPLAY, including an X11 or wayland volumne, and then mounting the video source. It seems like something about the yolov5 repo in particular does not agree with these conventions...

**Comment by pderrenger** [comment]
For Docker webcam access with YOLOv5, ensure you're passing both device access and display permissions. Try this minimal working example:

```bash
docker run -it --rm --device /dev/video0 -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix ultralytics/yolov5:latest python detect.py --source 0
```

This combines device passthrough with X11 forwarding. The [Ultralytics Docker Quickstart Guide](https://docs.ultralytics.com/guides/docker-quickstart/) shows additional configuration options. For headless environments or advanced use cases, consider using `xvfb` or switching to file saving instead of display.
