### ISSUE TITLE
Change the optimizer

### ISSUE THREAD

**Issue by tavomx45** [ultralytics/yolov5#10544]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How can I configure a different optimizer?

**Comment by glenn-jocher** [comment]
@tavomx45 you can set one using the argparser here:
https://github.com/ultralytics/yolov5/blob/f72f0fec980b35d7f9575d15b326f529b5a9ac0d/train.py#L456

Options are here, and you can add any additional ones not shown:
https://github.com/ultralytics/yolov5/blob/f72f0fec980b35d7f9575d15b326f529b5a9ac0d/utils/torch_utils.py#L331-L341

**Comment by tavomx45** [comment]
@glenn-jocher thanks for your help 😀

**Comment by glenn-jocher** [comment]
@tavomx45 you're welcome! Happy to help. If you have any more questions, feel free to ask. 😊 Keep up the great work!

**Comment by GeoSnap-design** [comment]
There seems to be a slight change now，no such passage：parser.add_argument('--optimizer', type=str, choices=['SGD', 'Adam', 'AdamW'], default='SGD', help='optimizer') ,Is the default optimizer SGD？How to change it to Adam or AdamW

**Comment by glenn-jocher** [comment]
Hello! Yes, the default optimizer is still SGD. To change it to Adam or AdamW, you can modify the `train.py` file. Specifically, add or update the optimizer argument in the `parser` like this:

```python
parser.add_argument('--optimizer', type=str, choices=['SGD', 'Adam', 'AdamW'], default='SGD', help='optimizer')
```

When running your training command, specify the optimizer by adding `--optimizer Adam` or `--optimizer AdamW` to use a different one. 😊

**Comment by GeoSnap-design** [comment]
Thank you for your answer，I am using YOLOv5-6.0，It seems that only YOLOv5-6.1 and above versions have this passage：parser.add_argument('--optimizer', type=str, choices=['SGD', 'Adam', 'AdamW'], default='SGD', help='optimizer')，In yolov5-6.0's train.py, there are only this passage：parser.add_argument('--adam', action='store_true', help='use torch.optim.Adam() optimizer'). But I don't know how to change the optimizer in this situation, so I changed the version.

**Comment by glenn-jocher** [comment]
Great decision on upgrading to a newer version! For YOLOv5 version 6.0, if you wanted to switch to the Adam optimizer, you would typically add the `--adam` flag to your training command like so:

```bash
python train.py --adam
```

This flag sets the optimizer to Adam instead of the default SGD. However, since you've already upgraded, using the `--optimizer` argument as you now have is indeed the cleaner way to switch between different optimizers. Happy training! 😊 If you need further assistance, just let me know!
