### ISSUE TITLE
Early evaluation of `default_act` in Conv nn.Module

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [ultralytics/yolov5#10542]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hey guys,

I hope you are doing great :) Python evaluate immediately the ["class" property](https://github.com/ultralytics/yolov5/blob/5545ff3545d886417b4eff12203d1af4d758cc10/models/common.py#L48), `models.common.Conv` you have the following code

```python
class Conv(nn.Module):
    # Standard convolution with args(ch_in, ch_out, kernel, stride, padding, groups, dilation, activation)
    default_act = nn.SiLU(()  # default activation
```

Notice that you will always have the same instance of `default_act` for every instance of `nn.Conv`. See the following example

```python
from torch import nn
import torch

class MyModule(nn.Module):
    def __init__(self):
        super().__init__()
        print("heyyyy")

    def forward(self, x):
        print(id(self))
        return x

class Conv(nn.Module):
    # Standard convolution with args(ch_in, ch_out, kernel, stride, padding, groups, dilation, activation)
    default_act = MyModule()  # default activation

    def __init__(self, c1, c2, k=1, s=1, p=None, g=1, d=1, act=True):
        super().__init__()
        self.conv = nn.Conv2d(c1, c2, k, s, groups=g, dilation=d, bias=False)
        self.bn = nn.BatchNorm2d(c2)
        self.act = self.default_act if act is True else act if isinstance(act, nn.Module) else nn.Identity()

    def forward(self, x):
        return self.act(self.bn(self.conv(x)))

    def forward_fuse(self, x):
        return self.act(self.conv(x))

x = torch.randn((1, 4, 8, 8))
# same id will be printed, you only have one `MyModule` instance
conv = Conv(4, 8)(x)
conv1 = Conv(4, 8)(x)
```

If you run it, `hey` is printed before you create `conv`, and the same object id (aka pointer ref) is printed meaning we have the same instance of `default_act` even if we have two instances of `Conv`.

This may cause issues so idk I felt like it was worth pointing it :smile: 

A more "correct" way is to make `act` optional

```python
class Conv(nn.Module):
    # Standard convolution with args(ch_in, ch_out, kernel, stride, padding, groups, dilation, activation)

    def __init__(self, c1, c2, k=1, s=1, p=None, g=1, d=1, act=None):
        super().__init__()
        self.conv = nn.Conv2d(c1, c2, k, s, groups=g, dilation=d, bias=False)
        self.bn = nn.BatchNorm2d(c2)
        self.act = nn.SiLU() if act is None else nn.Identity()

    def forward(self, x):
        return self.act(self.bn(self.conv(x)))

    def forward_fuse(self, x):
        return self.act(self.conv(x))
```

Notice that early evaluation will happen also for function parameters

```python
class Conv(nn.Module):
    # Standard convolution with args(ch_in, ch_out, kernel, stride, padding, groups, dilation, activation)

    def __init__(self, c1, c2, k=1, s=1, p=None, g=1, d=1, act=nn.SiLU()):
```

`act` will always be the same instance for all `Conv` instances

Cheers,

Fra

**Comment by glenn-jocher** [comment]
@FrancescoSaverioZuppichini we used to hard code a default activation as in your example, but we've updated so allow model yamls to define a custom activation instead of SiLU, i.e. in a model yaml you can now do:

```yaml
activation: nn.LeakyReLU(0.1)
```

The current implementation may be causing some unintended side effects as you mention though. If you have a better solution that retains custom-activation definition please let us know. Thank you!

**Comment by glenn-jocher** [comment]
@FrancescoSaverioZuppichini see L304 here:

https://github.com/ultralytics/yolov5/blob/5545ff3545d886417b4eff12203d1af4d758cc10/models/yolo.py#L299-L305

**Comment by FrancescoSaverioZuppichini** [comment]
oh that's a nice hack :smiley: 

well in general people prefer to serialize stuff, e.g. 

```yaml
activation:
    type: nn.LeakyReLU
    params:
        bla: foo
```

To avoid injecting malicious code from the config. However I think considering yolov5 is an ML model, if the current approach works why change it hahaha

Some frameworks, e.g. `transformers` pass string, that is "dumb" imho since it forces you to keep an up to date dictionary of string -> activations (e.g. `activation: "relu"`, then somewhere `{ "relu" : partial(nn.LeakyReLU, 0.1) }`)

**Comment by glenn-jocher** [comment]
@FrancescoSaverioZuppichini yeah these are good points. In general the use case seems to be replacing SiLU with ReLU or ReLU6 for QAT/Pruning optimizations, but I just introduced this a few months ago so it may need some refactoring.
