### ISSUE TITLE
Multi-Headed Classification

### ISSUE THREAD

**Issue by HassanBerry** [ultralytics/yolov5#10547]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

We're trying to use a single backbone with multiple heads to training different objects with a lot fewer examples than the main class. A graphical example would be as follows:[](url)
![181301444-5e5549de-675d-4037-b1f2-5438771d4ac3](https://user-images.githubusercontent.com/33604213/208844916-cd31eb26-b9d1-4f71-ac33-218fc2b55833.jpg)

I checked the existing issues and discussions and found this reply. #2001 

Specifically, this branch and model were referenced by Glenn. Can I get access to this?
[https://github.com/ultralytics/yolov5/issues/2001#issuecomment-776514367](url)

**Comment by iou84** [comment]
Good evening guys!!
Did you find an aswer regarding using multiple heads with yolov bacbone?

**Comment by glenn-jocher** [comment]
@iou84 good evening! 🔦 Our YOLOv5 model can indeed support multiple heads for training different objects with fewer examples. You may refer to this issue #2001 for more details on the branch and model discussed. You can explore the Ultralytics documentation for further information on model configurations and training setups. Let me know if you need anything else!
