### ISSUE TITLE
What is the relation between model strides (8, 16, 32) and the size of anchor-boxes?

### ISSUE THREAD

**Issue by AlessandroMondin** [ultralytics/yolov5#10541]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I understood that a default YOLOv5 v6.0 architecture outputs three grids of cells which are respectively 1/8, 1/16 and 1/32 of the input size. In other words each grids cell represents respectively 8, 16 and 32 pixels of _w_ and _h_ of the input image.
[Here](https://github.com/ultralytics/yolov5/issues/6695#issuecomment-1044462282) you said that increasing the stride provides larger observability toward objects.
But wouldn't the same purpose (detecting larger objects) by obtained by adopting larger anchors? Is there a trade-off or am I missing something?
Thanks a lot in advance

**Comment by glenn-jocher** [comment]
@AlessandroMondin anchors simply serve to normalize outputs. Strides determine the spatial window of information contained in each output.

**Comment by AlessandroMondin** [comment]
I am not sure I'm following you. 
I have always believed that the autoanchor algorithm checks which are the best anchors for our dataset and if the objects present in the custom dataset are larger, then autoanchor would suggest larger anchors.
I don't understand how changing the stride would benefit at detecting larger objects and I don't get how we can modify the strides without modifying the architecture

Always thanks a lot for being available!

**Comment by glenn-jocher** [comment]
Yes strides are defined by the downsampling of the architecture. 

i.e. stride 8 mostly contains information from an 8x8 pixel grid. Not much use in detecting objects at 640x640.

**Comment by AlessandroMondin** [comment]
I get what you mean on strides: i.e. to detect larger objects we could add a C3 at the end of the neck to get a 10x10 grid 
But still is not clear to me we use larger strides to detect larger objects instead of using larger anchors. 
I.e. instead of [373,326] we would use [567, 455], some larger targets could be assigned to this anchor,  no?

If my understanding is **that** wrong could you link some resources?

**Comment by glenn-jocher** [comment]
@AlessandroMondin you make a good point. The choice between larger strides and larger anchors isn't necessarily exclusive. Both can be employed to enhance the model's ability to detect larger objects, depending on your specific use case and dataset. For additional resources, you may refer to the Ultralytics Docs at https://docs.ultralytics.com/yolov5/.
