### ISSUE TITLE
Confusion matrix is not save after training ? 

### ISSUE THREAD

**Issue by qasim7520** [ultralytics/yolov5#10549]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Confusion matrix is not save after training ? 

 # Save last, best and delete
                torch.save(ckpt, last)
                if best_fitness == fi:
                    **_torch.save(ckpt, str(best)+str(epoch))_**
                if opt.save_period > 0 and epoch % opt.save_period == 0:
                    torch.save(ckpt, w / f'epoch{epoch}.pt')
                del ckpt
                callbacks.run('on_model_save', last, epoch, final_epoch, best_fitness, fi)
       
I change the code to store best.pt as its update and its store like 
best.pt0
best.pt1
best.pt15
best.pt25
here 0,1,15,25 are the epoch number on which best.pt is update 
but as I chnage the code my confusion matrix is not saved after training why?

### Additional

?

**Comment by glenn-jocher** [comment]
@Qasim7520 confusion matrices are created by val.py on training completion or when called directly. If this is not the case for you please submit a reproducible bug report. Thank you.

**Comment by qasim7520** [comment]
Thanks its solved

**Comment by glenn-jocher** [comment]
@Qasim7520 you're welcome! If you have any more questions or need further assistance, feel free to ask. Glad to hear the issue is resolved!
