### ISSUE TITLE
Training on a partially labelled dataset. How to disable the loss for specific labels in specific images?

### ISSUE THREAD

**Issue by Robotatron** [ultralytics/yolov5#10543]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Let's say I have dataset A with images only containing an apple. I have a dataset B with images containing both apples and bananas in the same image, but only bananas are labelled. Now I would like to train on a mixture of both datasets A and B.
The problem will be, of course, the unlabelled apples in dataset B.
However if we disable the loss for apples from the dataset B during training, we can use both datasets together.

Is there an easy way achieving this with YOLO5 codebase? 

ps. Another example. Dataset A has labels [1, 2 , 3], Dataset B has labels [1,2,3,4,5]. I'd like to train on both datasets together, but disable the loss for labels 4 and 5 if an image is from the Dataset A

**Comment by glenn-jocher** [comment]
@Robotatron all instances of all classes must be labelled in all datasets you train. For a guide on training multiple datasets simultaneously see https://community.ultralytics.com/t/how-to-combine-weights-to-detect-from-multiple-datasets
