### ISSUE TITLE
Colab train command on TPU

### ISSUE THREAD

**Issue by semihahishali** [ultralytics/yolov5#10555]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I use Google Colab for training models with cpu and gpu (with --device 0 parameter for gpu training). I have colab pro+ license and I do want to train on TPU but I don't know how to use train command to run on TPU, I've tried somethnig but could not manage. Thanks for your help in advance.

**Comment by maghili** [comment]
Any news on this question?

**Comment by semih-ahishali** [comment]
This is an important issue, there are many TPU machines out there for ML but we don't know how to use these TPUs for training. Ultralycs any update about this?

**Comment by jabbasj** [comment]
Bump - much needed feature since TPU is x10 performance but only +50% the cost

**Comment by glenn-jocher** [comment]
@jabbasj hi there! YOLOv5 currently doesn't support training directly on TPU. As of now, it's optimized for CPU and GPU, with Colab Pro being a great option for GPU training.

Yours is an excellent feature request, and something we could consider for future releases.

For models trained on GPU, new classes can be added to an already-trained model on TPU via transfer learning. Unfortunately, new training on TPU isn't directly supported at the moment.

For any further questions on YOLOv5, feel free to visit our Ultralytics Docs at https://docs.ultralytics.com/yolov5/.

All the best with your project!
