### ISSUE TITLE
How to run Yolov5 on Jetson Nano

### ISSUE THREAD

**Issue by lgeuder** [ultralytics/yolov5#10551]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,
I am switching from a Raspberry Pi to a Jetson Nano and I was hoping to "just" take the code to another computer, install requirements.txt and run detection...
After trying and retrying a week with different errors I started questioning my abilities.
1. Thing I tried: Clone repo and install requirements.txt --> Did not work that well because Torch and Torchvision needs to be installed manually (as well as OpenCV, if you need GStreamer support)
2. Thing: Flashed an Img File on which Pytorch & OpenCV is already installed. Commented this in requirements.txt and install requirements. Error: Segmentation fault
3. Convert my .pt Model to onnx and try TensorRT (Did not work, something with inputs channels, cannot remember tbh)

I know that Yolov5 is >= Python 3.7 but Jetson is on 3.6.9. I did not try another python version but I have never seen this in any tutorial.

I am now completely clueless what to try next.
Maybe someone is already running yolov5 on the jetson and can give me some information what I might be doing wrong.
Thanks

**Comment by Zephyr69** [comment]
The easiest way is to upgrade jetson to 5.0.x with python3.8, follow nvidia docs to install the correct pytorch and torchvision, and then you can pip install -r requirements.txt and run yolov5.

You can still run it with python3.6.9 but you need to manually find/build the correct pytorch and torchvision.

**Comment by AT9991** [comment]
@lgeuder, I am facing the same issue. Were you able to solve it?

**Comment by glenn-jocher** [comment]
Hello @AT9991, thank you for reaching out. If you are encountering the same issue, here are a few suggestions you can try:

- Upgrade the Jetson Nano to version 5.0.x with Python 3.8 and follow the NVIDIA documentation to install the correct versions of PyTorch and torchvision. Then, you can use `pip` to install the requirements and run YOLOv5.

- If you prefer to stick with Python 3.6.9, you will need to manually find or build the correct versions of PyTorch and torchvision.

I hope this helps. Let me know if you have any further questions!

**Comment by AT9991** [comment]
Hi Glenn, thanks for writing back. The issue here is Jetson Nano doesn't
support Jetpack 5.0 and higher.

**Comment by glenn-jocher** [comment]
@AT9991 the Jetson Nano does not support Jetpack 5.0 and higher, which is causing the issue. You have a couple of options to consider. One option is to upgrade the Jetson Nano to version 5.0.x with Python 3.8 and follow the NVIDIA documentation to install the correct versions of PyTorch and torchvision. Alternatively, if you prefer to stick with Python 3.6.9, you will need to manually find or build the correct versions of PyTorch and torchvision. Let me know if you have any further questions or need more assistance.

**Comment by AT9991** [comment]
I have installed python 3.8 on my Jetson nano including torch and
torchvision but CUDA is not available. So, the inferences are occuring on
the Nano's CPU. How do I make it run on its GPU? The FPS is very low 3-4

**Comment by lgeuder** [comment]
Hi @AT9991,
I solved this by downloading a prebuilt ISO and flashing that with already installed torchvision with cuda support. I am not at home atm so I cannot help with that link. But when I remember I will post it here

**Comment by lgeuder** [comment]
Quick google got me this: https://github.com/Qengineering/Jetson-Nano-image

**Comment by glenn-jocher** [comment]
@lgeuder hello, 

Thank you for sharing your solution! It's great to hear that you were able to solve the issue by downloading a prebuilt ISO with torchvision and CUDA support already installed. We appreciate your contribution to the discussion. If you have any further questions or need assistance in the future, feel free to reach out. 

Have a great day!

**Comment by lgeuder** [comment]
@glenn-jocher Nothing compared to what you have helped me within the last years, cheers to your work ;)

**Comment by glenn-jocher** [comment]
@lgeuder thank you for your kind words! I really appreciate your support and I'm glad I could be of help. However, all credit goes to the YOLO community and the amazing team at Ultralytics who have put in a lot of effort to make YOLOv5 what it is today. If you have any further questions or need any assistance, please don't hesitate to reach out.

**Comment by vicradon** [comment]
Okay, so I have been able to build pytorch and torchvision for Python3.6.9, but I see that ultralytics is not supported on Python3.6. Is there an old version of ultralytics that used to be supported on Python3.6.9 that I can use?

**Comment by glenn-jocher** [comment]
@vicradon Thanks for the update! YOLOv5's oldest supported Python version is 3.7. But if you're trying to get it running on Python 3.6.9, you could try looking at older releases of YOLOv5 for compatibility. You can find the release history on the GitHub repository under the "Releases" section to find an older version that may be compatible with Python 3.6.9. Let me know if you need further assistance!

**Comment by TechArcanist** [comment]
here is the solution https://github.com/TechArcanist/Jetson-Nano-Yolo-v5

**Comment by glenn-jocher** [comment]
Thank you for sharing the solution link. If you have any further questions or need assistance, feel free to ask!
