### ISSUE TITLE
Training on pretrained model with torchhub not possible

### ISSUE THREAD

**Issue by hamishc** [ultralytics/yolov5#10557]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

PyTorch Hub

### Bug

The model cannot be trained using torchhub when `pretrained=True` and `autoshape=False`, as it cannot be used to compute gradients. This is counter to what is said in the [torchhub tutorial](https://github.com/ultralytics/yolov5/issues/36).

When run with `pretrained=False` and `autoshape=False`, gradients can be computed. 

### Environment

- YOLOv5 🚀 2022-3-16 torch 1.10.2+cu113 CUDA:0 (NVIDIA GeForce RTX 2080 Ti, 11019MiB)

### Minimal Reproducible Example

```
import torch
model = torch.hub.load('ultralytics/yolov5:master', 'yolov5l', autoshape=False).train()
rand_input = torch.rand((1,3,640,640)).cuda()
output = model(rand_input)
print(output.requires_grad)

# Test computing gradients
output[0].sum().backward()
```
outputs `False` for requires grad, and returns the error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hamish/.local/lib/python3.6/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/hamish/.local/lib/python3.6/site-packages/torch/autograd/__init__.py", line 156, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@hamishc see train.py Usage examples for training YOLOv5 models:

https://github.com/ultralytics/yolov5/blob/96a71b17a276fa0a0b6fbdf68d579ce0603bfa2f/train.py#L3-L15

**Comment by hamishc** [comment]
I know how to run `train.py`. Did you read my question? Is the tutorial I linked to above out of date, or is there a mistake in how the torchhub models are set up?

**Comment by glenn-jocher** [comment]
@hamishc if tensors have requires_grad attribute set to False you can set this to True by looping through them. See an example here:
https://github.com/ultralytics/yolov5/blob/96a71b17a276fa0a0b6fbdf68d579ce0603bfa2f/train.py#L136-L137

**Comment by hamishc** [comment]
@glenn-jocher The end-user manually setting the model to trainable is a workaround for this, sure - but is the pretrained model untrainable by design? Why is it that the from-scratch model outputs both train/eval outputs when in eval mode, but the pretrained model doesn't? Are there two completely different models being built for each?

**Comment by eruditus-vir** [comment]
> @glenn-jocher The end-user manually setting the model to trainable is a workaround for this, sure - but is the pretrained model untrainable by design? Why is it that the from-scratch model outputs both train/eval outputs when in eval mode, but the pretrained model doesn't? Are there two completely different models being built for each?

Did you manage to understand the issue? currently i'm trying to get the gradient after running an inference and is facing no gradient fn issue.

**Comment by glenn-jocher** [comment]
@eruditus-vir The issue you're facing is due to how the pretrained model is loaded. When a model is loaded with `pretrained=True`, it may be frozen and set to evaluation mode by default, which is why you are unable to compute gradients. A workaround is to manually set the model to train mode using `model.train()`. We are continuously looking for ways to improve the user experience, and your feedback is valuable. Thank you for bringing this to our attention.
