### ISSUE TITLE
Detecting 2 class in one object WHAT TO DO 

### ISSUE THREAD

**Issue by Mansurjons** [ultralytics/yolov5#10566]
<img width="471" alt="2121212" src="https://user-images.githubusercontent.com/102349512/209143240-7878338c-cc34-45dc-ae38-4ef1637a1171.png">
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

where is the problem? thanks for answers

### Additional

<img width="912" alt="jojo" src="https://user-images.githubusercontent.com/102349512/209142883-da225802-ca74-4bdd-80e1-e8f83a945c90.png">

**Comment by glenn-jocher** [comment]
@Mansurjons very cool. It looks like your prediction is using multi-label. You can update NMS settings like agnostic and multi-label when calling the NMS function:

https://github.com/ultralytics/yolov5/blob/96a71b17a276fa0a0b6fbdf68d579ce0603bfa2f/utils/general.py#L884-L894

**Comment by Mansurjons** [comment]
@glenn-jocher I got you THANKS

**Comment by glenn-jocher** [comment]
@Mansurjons you're welcome! Happy to help. If you have more questions, feel free to ask.
