### ISSUE TITLE
--visualize feature visualize  argument is not working

### ISSUE THREAD

**Issue by devendraswamy** [ultralytics/yolov5#10564]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

I have tried --visualize  argument to visualize the classification features from the detected image but image features are not saved in while running the predict.py

!python classify/predict.py --weights yolov5s-cls.pt --img 224 --source /content/yolov5/data/images/bus.jpg --visualize

I tried above command to execute the program in the colab  

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@devendraswamy hi there! Thank you for reaching out. It looks like you are experiencing an issue with the `--visualize` argument in the `predict.py` script. Currently, the visualization of classification features is not supported in the YOLOv5 repository. 

If you have any other questions or need further assistance, feel free to ask. We appreciate your interest and input in using YOLOv5!
