### ISSUE TITLE
Why is my number of dataloader workers 0， when I've set defualt=8

### ISSUE THREAD

**Issue by bbqdsha** [ultralytics/yolov5#10567]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Why is my number of dataloader workers 0， when I've set defualt=8

**Comment by glenn-jocher** [comment]
@bbqdsha workers are updated per your system resources, i.e. if you have only 1 cpu workers are limited to 1 even if you request 8.

https://github.com/ultralytics/yolov5/blob/96a71b17a276fa0a0b6fbdf68d579ce0603bfa2f/utils/dataloaders.py#L138-L140

**Comment by bbqdsha** [comment]
> 



> @bbqdsha workers are updated per your system resources, i.e. if you have only 1 cpu workers are limited to 1 even if you request 8.
> 
> https://github.com/ultralytics/yolov5/blob/96a71b17a276fa0a0b6fbdf68d579ce0603bfa2f/utils/dataloaders.py#L138-L140

But I have 6.
![image](https://user-images.githubusercontent.com/53439276/209148741-d42ec10b-b6f2-4411-8a4b-871fa5121b1a.png)

**Comment by glenn-jocher** [comment]
@bbqdsha I'd put a breakpoint on L140 there to see what's happening.

**Comment by bbqdsha** [comment]
> @bbqdsha I'd put a breakpoint on L140 there to see what's happening.

thanks, I'll have a try
