### ISSUE TITLE
Get bad detect result

### ISSUE THREAD

**Issue by universewill** [ultralytics/yolov5#1056]
I trained yolov5 on a custom dataset. The targets are some road lines in map images.
The short ones can be well detected by yolov5. However, the long and thick roads are missed.

Is there any mechanism in yolov5 to discard or suppress these kinds of targets? How to improve the result?
Will increase anchor number do?

**Comment by Aktcob** [comment]
change anchors

**Comment by glenn-jocher** [comment]
@universewill you should update your anchors as @Aktcob mentioned, but you also should update the label aspect ratio threshold constraints here. The current default value `ar_thr=20` limits aspect ratios to to between 1/20 and 20.

https://github.com/ultralytics/yolov5/blob/2d2371d2d11221f1f4324bd6a1fcb03769d7d52c/utils/datasets.py#L838-L844

**Comment by glenn-jocher** [comment]
@universewill also be advised extreme aspect ratios like 5x200 may never detect well without fundamental changes to the convolution kernels in YOLOv5, which are all square shaped currently, and not intended for very long and thin objects.

**Comment by universewill** [comment]
> change anchors

i think the yolov5 has already calculated new anchors for my custom data.

**Comment by universewill** [comment]
> @universewill also be advised extreme aspect ratios like 5x200 may never detect well without fundamental changes to the convolution kernels in YOLOv5, which are all square shaped currently, and not intended for very long and thin objects.

Yeah, i will try to change the ar_thr and see what will happen
