### ISSUE TITLE
Abnormal output in Kaggle

### ISSUE THREAD

**Issue by Davegdd** [ultralytics/yolov5#10561]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I'm getting an abnormal output in Kaggle when trying to train with yolov5s.pt. As you can see, I get the "Corrupt JPEG data: premature end of data segment" message and it repeatedly shows operations at epoch 0/2:

![imagen](https://user-images.githubusercontent.com/108660081/209114182-2d581b4d-2622-4a0d-b717-6b62aa12cf20.png)
.
.
.
![imagen](https://user-images.githubusercontent.com/108660081/209116167-18278d49-40df-423d-ab86-8d29350b7493.png)

This is in contrast to my output in Google Colab which seems to be correct:

![imagen](https://user-images.githubusercontent.com/108660081/209114461-265605c8-4406-44ab-af23-5c626e838a2b.png)

The model in Colab was an initial attempt trained on 300 images to check that everything works, then I attempted to scale with 3000 images in Kaggle (where I can handle big datasets unlike in colab) and that happens, although number of images seems not to be the issue. I also know that the corrupt JPEG data message is a low level C thing that could be ignored, so not sure what is/are the problems here. The training also seems to be quite slow for 3000 images and two T4 GPUs.

Thanks for any help.

**Comment by glenn-jocher** [comment]
@Davegdd this is a low level warning that occurs when reading corrupt JPG images. You may want to check your images. If they appear normal you can save them with cv2 and the message will disappear.

**Comment by Davegdd** [comment]
@glenn-jocher thanks for your answer, the  corrupt JPG message is gone after opening and overwriting the images with cv2. The output info still appears cut out from mAP50-95 to the right but I just remembered that I've encountered other instances of low-level warnings and badly formatted output in Kaggle which didn't happen in Colab so it seems to be a Kaggle thing. Closing as resolved.

**Comment by glenn-jocher** [comment]
@Davegdd glad to hear the corrupt JPG message is resolved with cv2! Regarding the cut out output info, it sounds like a Kaggle-specific issue. Happy to hear it's resolved for you and should you have any more questions, feel free to ask😊.
