### ISSUE TITLE
Is there some way yolov5 can save the per class metrics at the end of training to a file for further review?

### ISSUE THREAD

**Issue by AnshKetchum** [ultralytics/yolov5#10568]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm trying to save the metrics I see at the end of the training epochs while training a yolov5s model for object detection. 

Is there any option / flag I can use to save the metrics at the end of training to a file, perhaps some sort of .txt or .csv to further analyze?

**Comment by glenn-jocher** [comment]
@AnshKetchum hi there! In YOLOv5, you can save per class metrics at the end of training to a file for further review using the `--save-hist` flag followed by the file path. This will save the training results in a CSV file for analysis. You can find more details in our documentation at https://docs.ultralytics.com/yolov5/. Let me know if you need any further assistance!
