### ISSUE TITLE
Need to crop BOX which accuracy more than 0.60 

### ISSUE THREAD

**Issue by Mansurjons** [ultralytics/yolov5#10563]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

you can see in my picture it cropping 2 boxes one True one False I must to get cropping box which accuracy more than 0.55, 0.60 or YOLO needn't detect accuracy less then 0.60

please help me with these issue
### Additional

<img width="596" alt="Screenshot 2022-12-22 at 17 14 44" src="https://user-images.githubusercontent.com/102349512/209133738-1509bd59-df63-4667-a46b-49dadc1f2d5d.png">

**Comment by glenn-jocher** [comment]
@Mansurjons you can set a higher confidence threshold, i.e. `python detect.py --conf 0.60`

**Comment by Mansurjons** [comment]
@glenn-jocher  Gooood thanks It worked for me I'm happy I through that I need to make another function

**Comment by glenn-jocher** [comment]
@Mansurjons glad to hear that the solution worked for you! If you have any more questions or need further assistance, feel free to ask. Keep up the great work!
