### ISSUE TITLE
Onnx inference not working for image instance segmentation, maybe a bug in ONNX model?

### ISSUE THREAD

**Issue by V4A001** [ultralytics/yolov5#10578]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have trained my model with Yolov7 at github, but cannot run the inherence (predict.py) without issues when exported to ONNX. At Yolov5 the inference is also not working with my Pytorch .pt file however. Strange enough the .onnx given there runs with this Yolov5 version of segmentation.

I see in the onnx presented here, the input image is a fixed mask and not dynamic, where the other is dynamic with different batch size. What input and outputs to be used ? My own has various slides although the others are more dense. Is this caused by reparameterization ?

I get errors like: 
For my own .pt model:
`PS D:\yolov5> python segment/predict.py --weights best.pt --source "d:\testimage.jpg"
segment\predict: weights=['best.pt'], source=d:\testimage.jpg, data=data\coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs\predict-seg, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1, retina_masks=False
YOLOv5  v7.0-47-g2370a55 Python-3.10.8 torch-1.13.0+cpu CPU

Traceback (most recent call last):
  File "D:\yolov5\segment\predict.py", line 284, in <module>
    main(opt)
  File "D:\yolov5\segment\predict.py", line 279, in main
    run(**vars(opt))
  File "C:\Users\..\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\yolov5\segment\predict.py", line 101, in run
    model = DetectMultiBackend(weights, device=device, dnn=dnn, data=data, fp16=half)
  File "D:\yolov5\models\common.py", line 345, in __init__
    model = attempt_load(weights if isinstance(weights, list) else w, device=device, inplace=True, fuse=fuse)
  File "D:\yolov5\models\experimental.py", line 79, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location='cpu')  # load
  File "C:\..\lib\site-packages\torch\serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\..\lib\site-packages\torch\serialization.py", line 1131, in _load
    result = unpickler.load()
  File "C:\..\lib\site-packages\torch\serialization.py", line 1124, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'MP' on <module 'models.common' from 'D:\\yolov5\\models\\common.py'>`
My the .pt model in ONNX model:
`   c, mh, mw = protos.shape  # CHW
ValueError: too many values to unpack (expected 3)`
The same happens for the ONNX model in this github:
`PS D:\..yolov5> python segment/predict.py --weights yolov5s.onnx --source "D:\..myimage.jpg"
segment\predict: weights=['yolov5s.onnx'], source=D:\..myimage.jpg, data=data\coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs\predict-seg, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1, retina_masks=False
YOLOv5  v7.0-47-g2370a55 Python-3.10.8 torch-1.13.0+cpu CPU

Loading yolov5s.onnx for ONNX Runtime inference...
Traceback (most recent call last):
  File "D:\..yolov5\segment\predict.py", line 285, in <module>
    main(opt)
  File "D:\..yolov5\segment\predict.py", line 280, in main
    run(**vars(opt))
  File "C:\..\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\..yolov5\segment\predict.py", line 131, in run
    pred, proto = model(im, augment=augment, visualize=visualize)[:2]
ValueError: not enough values to unpack (expected 2, got 1)
PS D:\..yolov5> `

I would suspect there is a error in the ONNX model in this project as well. But not 100% sure as my own is not working either, and the one of the other YoloV7 project runs here perfectly.

![image](https://user-images.githubusercontent.com/9630343/209357684-55da0860-e788-4765-b861-ed4c116dc7dd.png)

![image](https://user-images.githubusercontent.com/9630343/209357764-82730cc1-9441-4fa6-b55c-6a2fc99d4920.png)

![image](https://user-images.githubusercontent.com/9630343/209357862-b2a2f8f3-7008-430d-b3d0-cb1834703e6c.png)

**Comment by AyushExel** [comment]
@V4A001 This repo only supports yolov5. Are you seeing this error on a yolov5 trained model?

**Comment by V4A001** [comment]
@AyushExel , yes, I see my code snippets above are glued together. I would suspect there is a error in the ONNX model in this project as well. But not 100% sure as my own is not working either, and the one of the other YoloV7 project runs here perfectly.

The same happens for the ONNX model in this github:
`PS D:..yolov5> python segment/predict.py --weights yolov5s.onnx --source "D:..myimage.jpg"`
The error is:

`
ValueError: not enough values to unpack (expected 2, got 1)
PS D:..yolov5> ``

**Comment by UNeedCryDear** [comment]
you can try this pr https://github.com/ultralytics/yolov5/pull/9645
![image](https://user-images.githubusercontent.com/52729998/210528143-523c751d-6507-4c17-8e33-f84831f36bf0.png)

**Comment by yiliu-coding** [comment]
Hi, I encountered similar problems. After conversion, the input and output parts of the model are not complete, thus not usable. Have you found a solution?

**Comment by glenn-jocher** [comment]
@yiliu-coding have you verified the model conversion process and checked if the input and output parts of the model are correct? Double-checking these steps might help in resolving the issue. If you have any further information or specific errors/messages, please provide them so that we can assist you better.
