### ISSUE TITLE
`detect.py` `--source` with a glob fails with an `OSError`

### ISSUE THREAD

**Issue by vavanade** [ultralytics/yolov5#10577]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

Running `python detect.py --source "C:\path\to\data\*.png" --weights "C:\path\to\weights\last.pt"` fails with an `OSError` on Windows 10.

Relevant info from the Traceback:

```
  File "C:\path\to\yolov5\utils\dataloaders.py", line 246, in __init__
    p = str(Path(p).resolve())

OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\path\\to\\data\\*.png'
```

### Environment

- OS: Windows 10
- YOLOv5 - `master` branch

### Minimal Reproducible Example

.

### Additional

Relevant code in `utils/dataloaders.py`:

```python3
        files = []
        for p in sorted(path) if isinstance(path, (list, tuple)) else [path]:
            p = str(Path(p).resolve())
            if '*' in p:
                files.extend(sorted(glob.glob(p, recursive=True)))  # glob
            elif os.path.isdir(p):
                files.extend(sorted(glob.glob(os.path.join(p, '*.*'))))  # dir
            elif os.path.isfile(p):
                files.append(p)  # files
            else:
                raise FileNotFoundError(f'{p} does not exist')
```

Resolving `pathlib.Path`s with globs does not work. Maybe the `glob.glob` could be applied first if there is a `*` in the path but then it risks being expanded incorrectly.

The answer to [this](https://stackoverflow.com/questions/51108256/how-to-take-a-pathname-string-with-wildcards-and-resolve-the-glob-with-pathlib) question on StackOverflow could be a solution ([https://stackoverflow.com/questions/51108256/how-to-take-a-pathname-string-with-wildcards-and-resolve-the-glob-with-pathlib](https://stackoverflow.com/questions/51108256/how-to-take-a-pathname-string-with-wildcards-and-resolve-the-glob-with-pathlib)).

Any ideas for another good solution?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@vavanade hi there! Thanks for bringing this to our attention. The issue appears to be related to resolving `pathlib.Path` objects with globs. Currently, the code in `utils/dataloaders.py` uses `pathlib.Path(p).resolve()` which doesn't work with wildcards.

You mentioned a potential solution from StackOverflow which suggests using `glob.glob` on the path with wildcards. We'll explore this approach and see if it can be integrated effectively.

We appreciate your willingness to contribute! If you're up for it, a pull request to address this issue would be fantastic. Your help is invaluable to the YOLO community.

Thank you for your understanding and patience! If you have any further insights or questions, feel free to ask.
