### ISSUE TITLE
Source Input from PyQt5.QtGui.QImage

### ISSUE THREAD

**Issue by StaringTheWorldAtMyRearView123** [ultralytics/yolov5#10583]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Long Story Short, below is my Code. I am trying to get a screenshot from a speicifc window, So I use QApplication to do the screenshot work for me. But This is the error I get.  Please tell me how to fix this problem or can you provide me another method to get a screenshot from a speicific window? I did not do the default screencapture method yolo provided is because I don't want a fullscreen screenshot. That's why I am doing the QT method to screenshot.

![图片](https://user-images.githubusercontent.com/76271191/209421302-525e5362-7611-421a-be66-d49cbcd99df0.png)

![图片](https://user-images.githubusercontent.com/76271191/209421202-34975f8f-dcdf-4ea6-bf8d-e5ed1feaec36.png)

**Comment by AyushExel** [comment]
@qiningonline the model accepts img files or torch tensors. It doesn't accept `QImage` type. You'll need to first convert `QImage` to tensor and then pass it in model. I think there must be some ways to do it. You'll probably need to go from `QImage` to numpy to tensor.
