### ISSUE TITLE
pytorch torch.jit.save()  实现保存路径为中文出错

### ISSUE THREAD

**Issue by bswli** [ultralytics/yolov5#10587]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

torch.jit.save() 保存模型    保存地址路径存在中文，出现异常报错，
如何实现torch.jit.save()  保存地址可以存在中文？？？

**Comment by bswli** [comment]
![image](https://user-images.githubusercontent.com/105101984/209487234-0cac2b51-63aa-47ca-b418-ba026c14fdce.png)
![image](https://user-images.githubusercontent.com/105101984/209487258-701a88e4-3235-44c6-8061-3f399fdde581.png)

**Comment by bswli** [comment]
![image](https://user-images.githubusercontent.com/105101984/209487745-c10f4e0c-0580-44d5-98ab-00d9d8ba68f6.png)
上述str(f)字符串路径  中存在中文 就会报错

**Comment by glenn-jocher** [comment]
@bswli hi, the issue you're experiencing with saving a model to a path containing Chinese characters can be resolved by using Unicode strings for the file path. For example, you can use `torch.jit.save(model, u'模型.pt')` to save the model to a file path containing Chinese characters.

Let me know if this resolves your issue!

**Comment by wen-monster** [comment]
大概是torch的字符解码问题，让python去打开文件，save或load函数接收文件指针
```
with open(sPath, 'wb') as f:  
    torch.jit.save(model, f)
```
```
with open(sPath, 'rb') as f:  
    model = torch.jit.load(f)
```

**Comment by pderrenger** [comment]
你好，您是对的，使用 `open()` 方法处理文件路径时，可以避免中文路径编码问题。以下代码应该有效解决问题：

```python
with open(sPath, 'wb') as f:
    torch.jit.save(model, f)

with open(sPath, 'rb') as f:
    model = torch.jit.load(f)
```

通过这种方式，确保 Python 以二进制模式打开文件，避免因路径中包含中文字符而导致的错误。

如果还有其他问题，请随时联系！感谢您对 YOLO 和 PyTorch 的支持。
