### ISSUE TITLE
Segmentation mask (configurable) transparancy

### ISSUE THREAD

**Issue by Denizzje** [ultralytics/yolov5#10592]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Hello all,

I have finally gotten to converting my custom dataset for Yolo segmentation and now doing some experimenting running it on videos. I have not optimised things very well but the results are very good already! Almost no cropped / cut off masks etc.

I do notice an issue in my case. The masks are transparant, but just somewhat. I took a glance in the segment/predict.py code but I did not see something to configure the amount of transparancy of the masks. In my case the detected object really gets hard to see what is behind the mask and I could use some more transparancy. This is mainly due to the contrast in my videos not being too great.

I have no idea how much work this is, but could perhaps a parameter for mask transparancy be added like you can configure the line thickness already for bounding boxes? And could I get some pointers on how to adjust the transparancy for now?

Thanks in advance and keep up the good work!

### Use case

The relatively not transparant masks "overshadow" the detected objects in less optimal conditions, configurable masks transparancy could help by making the detected object more visible through the mask.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Rm1n90** [comment]
There is an alpha value in masks method of Annotator class which let you to adjust the transparency of the masks!

**Comment by glenn-jocher** [comment]
@Rm1n90 thanks for reaching out! 😊 I appreciate your interest in improving mask visibility. You can adjust the transparency of the masks by modifying the `alpha` value in the `masks` method of the `Annotator` class. This will allow you to make the detected object more visible through the mask. Keep up the good work, and feel free to reach out if you need any further assistance!
