### ISSUE TITLE
Yolov5 concentrated documantation

### ISSUE THREAD

**Issue by IgorGoldberg** [ultralytics/yolov5#10599]
Hello, I am pretty new here, so I am sorry in advance if this is something obvious which i have missed.
1)Please tell me where can I find **in one place** like documentation,  all available arguments for CLI training train.py (for example --cache, --hyp, --weights, --evolve, etc...) , up until now I discovered them in some separate places here in different tutorials or here in different issues, or just googled them, but all the way I did not find any place where they appear as a list with discription.
2)Same about all available arguments for CLI detecting detect.py
Thank you very much

**Comment by AyushExel** [comment]
@IgorGoldberg we hear you. Currently, you'll find all official guides in the `tutorials` section of our readme. But very soon we'll release dedicated docs which will be interactive and well-maintained with all the tutorials in one place. Stay tuned!

**Comment by YeopSeung04** [comment]
욜로 프로젝트를 클론 받았다면
당신의 디렉토리에서 utils 파일이 있다.

detect.py 에서 from 시작하는 파일들을 전부 보면 당신의 궁금증은 해결될 것이라고 생각한다..

하지만 이것을 추천하지 않는다. 이것을 분석하는데 2주가 지났다. 

```
def run(
        weights=ROOT / 'yolov5s.pt',  # Learned Weight (Model)
        source=ROOT / 'data/images',  # prediction image or video or webcam
        data=ROOT / 'data/coco128.yaml',  # dataset.yaml -> the names of things
        imgsz=(640, 640),  # inference size (height, width)
        conf_thres=0.25,  # confidence threshold
        iou_thres=0.45,  # NMS IOU threshold
        max_det=1000,  # maximum detections per image
        device='',  # cuda device, i.e. 0 or 0,1,2,3 or cpu
        view_img=False,  # show results
        save_txt=False,  # save results to *.txt
        save_conf=False,  # save confidences in --save-txt labels
        save_crop=False,  # save cropped prediction boxes
        nosave=False,  # do not save images/videos
        classes=None,  # filter by class: --class 0, or --class 0 2 3
        agnostic_nms=False,  # class-agnostic NMS
        augment=False,  # augmented inference
        visualize=False,  # visualize features
        update=False,  # update all models
        project=ROOT / 'runs/detect',  # save results to project/name
        name='exp',  # save results to project/name
        exist_ok=False,  # existing project/name ok, do not increment
        line_thickness=3,  # bounding box thickness (pixels)
        hide_labels=False,  # hide labels
        hide_conf=False,  # hide confidences
        half=False,  # use FP16 half-precision inference
        dnn=False,  # use OpenCV DNN for ONNX inference
        vid_stride=1,  # video frame-rate stride
):
```

**Comment by turinaf** [comment]
@AyushExel YOLOv5 documentation suddenly disappeared from Ultralytics docs, what happened? 
for example [this page](https://docs.ultralytics.com/tutorials/training-tips-best-results/) had training tips for best result. Now it says 404 Not found.
Please let me know if it's moved to new page (the whole YOLOv5 documentation). 
Thank you!

**Comment by glenn-jocher** [comment]
@AI-Expert-04 안녕하세요! 감사합니다 for sharing the details. We're constantly working on improving the documentation and your feedback is invaluable. Stay tuned for updates on the comprehensive documentation which will address these concerns. For now, please feel free to refer to the script files directly for any specific argument details. Cheers!
