### ISSUE TITLE
How to improve speed detection object (about 200 FPS)

### ISSUE THREAD

**Issue by taroo225** [ultralytics/yolov5#1059]
I trained yolov5 on a custom dataset. I detect video and the result is about 150 FPS. I want to increase it to around 200 FPS. What should I do? Is there any way? Please just let me know.

**Comment by wudashuo** [comment]
1. use yolov5s/yolov5m instead of larger models.
2. don't use `--augment` in detection.
3. the default image size is 640, adjust it by using `--img 608` or `--img 576` or even lower.
All of these three ways will reduce mAP to varying degrees.

**Comment by taroo225** [comment]
>     1. use yolov5s/yolov5m instead of larger models.
> 
>     2. don't use `--augment` in detection.
> 
>     3. the default image size is 640, adjust it by using `--img 608` or `--img 576` or even lower.
>        All of these three ways will reduce mAP to varying degrees.

Thank you. I will try it.

**Comment by glenn-jocher** [comment]
Good suggestions spongebob!

Also, increase batch size.

**Comment by govindamagrawal** [comment]
@wudashuo  how to calculate the possible image size, like as you suggested 608 and 576, how to find even lower image sizes?

**Comment by wudashuo** [comment]
> @wudashuo how to calculate the possible image size, like as you suggested 608 and 576, how to find even lower image sizes?

Any size that multiples of 32.  640, 608, 576, 544, 512...
however once I typed a wrong number by mistake, but the actual inputs still were multiples of 32...

**Comment by vukien199x** [comment]
>     1. use yolov5s/yolov5m instead of larger models.
> 
>     2. don't use `--augment` in detection.
> 
>     3. the default image size is 640, adjust it by using `--img 608` or `--img 576` or even lower.
>        All of these three ways will reduce mAP to varying degrees.

**Comment by Zegorax** [comment]
> * use yolov5s/yolov5m instead of larger models.
> * don't use `--augment` in detection.
> * the default image size is 640, adjust it by using `--img 608` or `--img 576` or even lower.
>   All of these three ways will reduce mAP to varying degrees.

For step 3, are you talking about training or when detecting ?

**Comment by govindamagrawal** [comment]
@Zegorax I was taking about inference only and its model is working fine if the image size is multiple of 32. Thanks for clarifying.

**Comment by lorispodevyn** [comment]
Decrease the image size by a multiple of 32

**Comment by glenn-jocher** [comment]
👋 Hello! Thanks for asking about **inference speed issues**. YOLOv5 🚀 can be run on CPU (i.e. `--device cpu`, slow) or GPU if available (i.e. `--device 0`, faster). You can determine your inference device by viewing the YOLOv5 line printed to screen:

If you would like to increase your inference speed some options are:

- Increase `--batch-size` ([YOLOv5 PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) and `val.py` only)
- Reduce `--img-size`, i.e. 1280 -> 640 -> 320
- Reduce model size, i.e. YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s -> YOLOv5n
- Use a faster GPUs, i.e.: P100 -> V100 -> A100
- Use a free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

### detect.py inference
```bash
python detect.py --weights yolov5s.pt --img 640 --conf 0.25 --source data/images/
```
<img width="944" alt="detect.py" src="https://user-images.githubusercontent.com/26833433/140100842-e130b5f7-64cb-46c9-9386-72abadd19828.png">

### YOLOv5 PyTorch [Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) inference
```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Images
dir = 'https://ultralytics.com/images/'
imgs = [dir + f for f in ('zidane.jpg', 'bus.jpg')]  # batch of images

# Inference
results = model(imgs)
results.print()  # or .show(), .save()
# Speed: 631.5ms pre-process, 19.2ms inference, 1.6ms NMS per image at shape (2, 3, 640, 640)
```
