### ISSUE TITLE
Where is the trained model  and save a model ?

### ISSUE THREAD

**Issue by china56321** [ultralytics/yolov5#106]
Hi , I am training my own datasets , I want to know :
1.how to save a model  when training every 10 epoch ?
2.Where  the well trained model saved?

**Comment by glenn-jocher** [comment]
@china56321 best and last checkpoints are saved to /weights folder at the end of every epoch. To save every x epochs you'd need to add some code to train.py.

**Comment by navidroo** [comment]
@china56321 you can use --save-period 10 in your training command:
Example:
!python train.py --hyp 'hyp-custom-1.yaml' --img 720 --batch 36 --epochs 200 --data costum_data.yaml --weights 'last.pt' --cache **--save-period 10**

**Comment by zhou-huan-1** [comment]
@china56321 best and last checkpoints are saved to /weights folder at the end of every epoch. To save every x epochs you'd need to add some code to train.py.

**Comment by zhou-huan-1** [comment]
@china56321 best and last checkpoints are saved to /weights folder at the end of every epoch. To save every x epochs you'd need to add some code to train.py.
