### ISSUE TITLE
Not able to load YOLOv5m6 using PyTorch hub while the same code works while loading YOLOv5m

### ISSUE THREAD

**Issue by roshansinghbisht** [ultralytics/yolov5#10616]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,

I am using torch hub to load yolov5m6 model. 
Few days ago i trained a single yolov5m model, and I got pretty decent results. Thanks!

And after that, i then trained a yolov5m6 model hoping for a better accuracy. But I am unable to get the inference results since I am getting error while loading the yolov5m6 model.
I am loading the model using pytorch hub. Below is the line of code which i use to load the simple yolov5m model:
`model = torch.hub.load('/path/to/hubconf.py/directory', 'custom', '/path/to/yolov5m_best.pt', source='local')`
And yolov5m loads without any issues. 
But when I am trying to load the yolov5m6 model using the same line of code:
`model = torch.hub.load('/path/to/hubconf.py/directory', 'custom', '/path/to/yolov5m6_best.pt', source='local')`
I am getting the following error:

YOLOv5 🚀 2022-11-30 Python-3.8.10 torch-1.11.0a0+git8d365ae CPU

Traceback (most recent call last):
  File "/home/load_yolo/hubconf.py", line 49, in _create
    model = DetectMultiBackend(path, device=device, fuse=autoshape)  # detection model
  File "/home/load_yolo/models/common.py", line 345, in __init__
    model = attempt_load(weights if isinstance(weights, list) else w, device=device, inplace=True, fuse=fuse)
  File "/home/load_yolo/models/experimental.py", line 79, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location='cpu')  # load
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 1046, in _load
    result = unpickler.load()
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 1039, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute '_rebuild_parameter_v2' on <module 'torch._utils' from '/usr/local/lib/python3.8/dist-packages/torch/_utils.py'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/load_yolo/hubconf.py", line 60, in _create
    model = attempt_load(path, device=device, fuse=False)  # arbitrary model
  File "/home/load_yolo/models/experimental.py", line 79, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location='cpu')  # load
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 1046, in _load
    result = unpickler.load()
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 1039, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute '_rebuild_parameter_v2' on <module 'torch._utils' from '/usr/local/lib/python3.8/dist-packages/torch/_utils.py'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "load_yolo/load_yolo.py", line 8, in <module>
    model = torch.hub.load('/home/load_yolo', 'custom', '/home/load_yolo/new_yolov5m_CR.pt', source='local')
  File "/usr/local/lib/python3.8/dist-packages/torch/hub.py", line 404, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/hub.py", line 433, in _load_local
    model = entry(*args, **kwargs)
  File "/home/load_yolo/hubconf.py", line 83, in custom
    return _create(path, autoshape=autoshape, verbose=_verbose, device=device)
  File "/home/load_yolo/hubconf.py", line 78, in _create
    raise Exception(s) from e
Exception: Can't get attribute '_rebuild_parameter_v2' on <module 'torch._utils' from '/usr/local/lib/python3.8/dist-packages/torch/_utils.py'>. Cache may be out of date, try `force_reload=True` or see https://github.com/ultralytics/yolov5/issues/36 for help.

Is there anything that I am missing in here? Please let me know if you know about the issue

### Additional

My local is Ubuntu 20.04.5 LTS. And i have tried this inside the yolov5 docker container.

**Comment by roshansinghbisht** [comment]
Just to update more:
In the above error it mentions to set 'force_reload=True', I have tried that already but no use. It got much clearer after seeing the Pytorch's torch.hub documentation where it says that: _force_reload_ does not have any effect if source = 'local'_
And in my case i am setting source= 'local' since mine is a custom trained model.

At this moment, I can't find any workaround on this

**Comment by anjineyulutv** [comment]
I am also facing thwe same issue.I think in the repo pipeline it works fine @glenn-jocher .But as we take these code being in the same docker but a diffrent pipeline,it fails.If the errors happens inside packages of python,it is becoming difficult to debug

**Comment by roshansinghbisht** [comment]
I downgraded the version of PyTorch to 1.11, then trained the model again, and did the inference successfully.
Seems i was training the model on a higher torch version and doing inference on a lower torch version.
Seems PyTorch forward compatibility but not backward i guess.

**Comment by glenn-jocher** [comment]
@roshansinghbisht hey there! Thanks for reaching out. It's great to hear that you were able to resolve the issue and successfully perform the inference after downgrading PyTorch to version 1.11. It's indeed important to ensure compatibility between the training and inference environments. Your finding about PyTorch's forward compatibility is spot on. If you have any more questions or need further assistance, feel free to ask!
