### ISSUE TITLE
--conf-thres set 0.25 and 0.65 with strange results.

### ISSUE THREAD

**Issue by kevin0756-debug** [ultralytics/yolov5#10618]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When I identify the position of the license plate, I set --conf-thres 0.25 and the result is not identified.
![112419](https://user-images.githubusercontent.com/85444943/209826545-02103f5b-3039-49fc-a383-b6694ce77318.jpg)
![113755](https://user-images.githubusercontent.com/85444943/209828044-427268c9-77b3-40e3-96a6-25f2031d5b45.jpg)

Later set --conf-thres 0.65 and the result was recognized.
![112419](https://user-images.githubusercontent.com/85444943/209826588-a137e040-0ece-4f8d-8dbe-1609414b6e8f.jpg)
![113755](https://user-images.githubusercontent.com/85444943/209827389-89970c60-3fd1-4f17-8890-6620c4b9b812.jpg)

This result confuses me?????
                                                                                                                                                                    2022/12/28 Tang,Ren Kai

**Comment by YeopSeung04** [comment]
`
assert 0 <= conf_thres <= 1, f'Invalid Confidence threshold {conf_thres}, valid values are between 0.0 and 1.0'
`
It is our duty to find a threshold between 0 and 1.
There is an inconvenience of having to find an appropriate threshold to prevent NMS.

**Comment by kevin0756-debug** [comment]
Sorry I'm still a newbie. As far as I know, using the same weight, it cannot be recognized when the threshold is low, but I can recognize it when the threshold is increased. This part makes me not understand.
In addition, when experimenting with other pictures, sometimes the results will be opposite.
It's amazing and I still have a lot to learn.

**Comment by YeopSeung04** [comment]
To perform object detection correctly, set the confidence threshold to remove the boundary box less than a specific score value. If you set the confidence threshold and then start the NMS, you can remove bboxes that are lower than that confidence threshold. If the confidence threshold is high enough, you can remove many bounding boxes and improve speed significantly. Then, calculate the maximum value from the vector and draw the corresponding class with the box on the image.

**Comment by glenn-jocher** [comment]
@AI-Expert-04 thank you for sharing your experience. Indeed, setting a confidence threshold is integral to refining object detection. Lower thresholds may lead to more detections, but also increase the likelihood of false positives. Conversely, a higher threshold helps filter out low-confidence predictions. The optimal threshold value can vary based on the specific use case and dataset. Keep up the great work, and don't hesitate to reach out if you need further assistance!
