### ISSUE TITLE
Non default paths to save experiments

### ISSUE THREAD

**Issue by IgorGoldberg** [ultralytics/yolov5#10612]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,  I do evolove only for some of my training experiments.
lets say I have already  training experiments 1,2,3,4 and I get relevant folders called exp,exp1,exp2,exp3,exp4
and **I have done no evolve experiments yet** thus my evolve folder is empty.

Now I plan to do 5th **training** experiment but before I want to evolve the hyperparameters. If I do it, I will get in evolve folder exp1, but I want to call it exp5, for it to correspond with its name to  the upcumming **training** exp5
How can I change the output folder name for the evolve session to be exp5?
Thank you

**Comment by YeopSeung04** [comment]
There is a way to rename that directory. Right-click and click rename to change

**Comment by IgorGoldberg** [comment]
> There is a way to rename that directory. Right-click and click rename to change

Gotcha cap

**Comment by glenn-jocher** [comment]
@IgorGoldberg you got it! If you face any more questions or issues, feel free to ask. We're here to help!
