### ISSUE TITLE
 raise ModuleAttributeError("'{}' object has no attribute '{}'".format( torch.nn.modules.module.ModuleAttributeError: 'Conv' object has no attribute '_non_persistent_buffers_set'

### ISSUE THREAD

**Issue by 172624346** [ultralytics/yolov5#1061]
## ❔Question
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.4, device='', img_size=640, iou_thres=0.5, output='inference/output', save_txt=False, source='inference/images', update=False, view_img=False, weights='yolov5s.
pt')
Using CUDA device0 _CudaDeviceProperties(name='GeForce GTX 750 Ti', total_memory=2048MB)

Fusing layers... Traceback (most recent call last):
  File "detect.py", line 161, in <module>
    detect()
  File "detect.py", line 23, in detect
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "D:\pyProject\yolov5-3.0\yolov5-3.0\models\experimental.py", line 133, in attempt_load
    model.append(torch.load(w, map_location=map_location)['model'].float().fuse().eval())  # load FP32 model
  File "D:\pyProject\yolov5-3.0\yolov5-3.0\models\yolo.py", line 149, in fuse
    m.conv = torch_utils.fuse_conv_and_bn(m.conv, m.bn)  # update conv
  File "E:\Anaconda3\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 802, in __setattr__
    remove_from(self.__dict__, self._parameters, self._buffers, self._non_persistent_buffers_set)
  File "E:\Anaconda3\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 771, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'Conv' object has no attribute '_non_persistent_buffers_set'

## Additional context
Can anyone help me answer this question
I am very thankful  T.T

**Comment by NanoCode012** [comment]
See https://github.com/ultralytics/yolov5/issues/561#issuecomment-666610696

**Comment by 172624346** [comment]
> 参见[＃561（评论）](https://github.com/ultralytics/yolov5/issues/561#issuecomment-666610696)

Problem sloved, thanks!
