### ISSUE TITLE
ONNX benchmark error 

### ISSUE THREAD

**Issue by mwitiderrick** [ultralytics/yolov5#10629]
```%%bash
cd yolov5
python benchmarks.py --weights yolov5s.onnx --img 640
```
I have this error benchmarking onnx
```
benchmarks: weights=yolov5s.onnx, imgsz=640, batch_size=1, data=/content/yolov5/data/coco128.yaml, device=, half=False, test=False, pt_only=False, hard_fail=False
YOLOv5 🚀 v7.0-53-g65071da Python-3.8.16 torch-1.13.0+cu116 CPU

Traceback (most recent call last):
  File "benchmarks.py", line 169, in <module>
    main(opt)
  File "benchmarks.py", line 164, in main
    test(**vars(opt)) if opt.test else run(**vars(opt))
  File "benchmarks.py", line 65, in run
    model_type = type(attempt_load(weights, fuse=False))  # DetectionModel, SegmentationModel, etc.
  File "/content/yolov5/models/experimental.py", line 79, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location='cpu')  # load
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x08'.
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
<ipython-input-12-d8bb9c5b22bb> in <module>
----> 1 get_ipython().run_cell_magic('bash', '', 'cd yolov5\npython benchmarks.py --weights yolov5s.onnx --img 640\n')

3 frames
<decorator-gen-103> in shebang(self, line, cell)

/usr/local/lib/python3.8/dist-packages/IPython/core/magics/script.py in shebang(self, line, cell)
    243             sys.stderr.flush()
    244         if args.raise_error and p.returncode!=0:
--> 245             raise CalledProcessError(p.returncode, cell, output=out, stderr=err)
    246 
    247     def _run_script(self, p, cell, to_close):

CalledProcessError: Command 'b'cd yolov5\npython benchmarks.py --weights yolov5s.onnx --img 640\n'' returned non-zero exit status 1.
white_check_mark
eyes
raised_hands
```

But this one works
```
%%bash
cd yolov5
python benchmarks.py --weights yolov5s.pt --img 640
```

**Comment by YeopSeung04** [comment]
Onnx is not available for benchmarking.

python benchmarks.py --weights yolov5s.pt --img 640

`
benchmarks: weights=/content/yolov5/yolov5s.pt, imgsz=640, batch_size=1, data=/content/yolov5/data/coco128.yaml, device=cpu, half=False, test=False
Checking setup...
YOLOv5 🚀 v6.1-135-g7926afc torch 1.10.0+cu111 CPU
Setup complete ✅ (8 CPUs, 51.0 GB RAM, 41.5/166.8 GB disk)

Benchmarks complete (241.20s)
                   Format  mAP@0.5:0.95  Inference time (ms)
0                 PyTorch        0.4623               127.61
1             TorchScript        0.4623               131.23
2                    ONNX        0.4623                69.34
3                OpenVINO        0.4623                66.52
4                TensorRT           NaN                  NaN
5                  CoreML           NaN                  NaN
6   TensorFlow SavedModel        0.4623               123.79
7     TensorFlow GraphDef        0.4623               121.57
8         TensorFlow Lite        0.4623               316.61
9     TensorFlow Edge TPU           NaN                  NaN
10          TensorFlow.js           NaN                  NaN
`
Looking at the results above, you can see that onnx was used in Benchmarks complete.

Export ONNX for up to 3x CPU speed

**Comment by mwitiderrick** [comment]
Thanks

**Comment by glenn-jocher** [comment]
@mwitiderrick you're welcome! If you need any further assistance or have more questions, feel free to ask. Your feedback and contributions help improve the YOLOv5 experience for the entire community. Happy coding!
