### ISSUE TITLE
how do i can yolov5 webcam socket communication

### ISSUE THREAD

**Issue by oes5756** [ultralytics/yolov5#10622]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

It operates real-time object recognition through YOLO5 and the webcam camera.
I want to send the camera screen to another server through socket communication.
But if you use the code below, the bounding box will be displayed
The screen stops and only the normal camera screen is transmitted.
How do I transfer the object recognition camera screen to the socket?

yolov5 code add my socket code 
----------------------------------------------
import socket
import pickle
import struct

ip = '0.0.0.0'
port = 9999

capture = cv2.VideoCapture(0)

capture.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
capture.set(cv2.CAP_PROP_FRAME_GEIGHT, 480)

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as client_socket:
                client_socket.connect((ip, port))

                while True:
                    retval, frame = capture.read()
                    retval, frame = cv2.imencode('.jpg', frame, [cv2.IMWRITE_JPEG_QUALITY, 90])
                    frame = pickle.dumps(frame)
                    client_socket.sendall(struct.pack(">L", len(frame)) + frame)

**Comment by YeopSeung04** [comment]
It's a really simple problem.

capture = cv2.VideoCapture(0)

0 is the built-in camera.
1 is an external camera.

capture = cv2.VideoCapture(1)

If you want to use Stream CCTV,

stream = 'rtsp://[cctvURL]'
capture = cv2.VideoCapture(stream)

**Comment by oes5756** [comment]
@AI-Expert-04 

my yolov5 code 
https://github.com/ultralytics/yolov5

I operated the object recognition movement through the webcam through "python detect.py --source 0."
I want to show the camera screen on another platform through the socket Help me

**Comment by YeopSeung04** [comment]
"python detect.py --source stream" or "python detect.py --source list of streams"

**Comment by oes5756** [comment]
@AI-Expert-04 
What I want to do is share the camera screen executed through "python detect.py --source 0" through socket

"python detect.py --source stream" is not work

**Comment by oes5756** [comment]
@AI-Expert-04 
my Socket code added to yolov5 code

ip = 127.0.0.1
port = 9999

stream = 'rtsp://127.0.0.1'
capture = cv2.VideoCapture(stream)

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as client_socket:
       client_socket.connect((ip, port))

        while True:
              retval, frame = capture.read()
              retval, frame = cv2.imencode('.png', frame, [cv2.IMWRITE_JPEG_QUALITY, 90])
              frame = pickle.dumps(frame)
              client_socket.sendall(struct.pack(">L", len(frame)) + frame)

**Comment by YeopSeung04** [comment]
I understand what you are trying to do.
But it's impossible.

Because you write the webcam in the detect code
Find the VideoCapture(0) that uses that webcam
 You have to put your code at that point.

```
import cv2
import socket
import pickle
import struct


cap = cv2.VideoCapture(0) # -> python detect.py --source 0 (webcam)
ip = 'rtsp://127.0.0.1'
port = 9999


with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as client_socket:
    client_socket.connect((ip, port))

while cap.isOpened():
    ret, cam = cap.read()
    if not ret:
        break

    # cam ->

    cv2.imshow('video', cam)

    retval, frame = cam.read()
    retval, frame = cv2.imencode('.png', frame, [cv2.IMWRITE_JPEG_QUALITY, 90])
    frame = pickle.dumps(frame)
    client_socket.sendall(struct.pack(">L", len(frame)) + frame)

    if cv2.waitKey(1) == ord('q'):
        break

cap.release()
```
I tried, but there is no way to transmit the real-time video of object recognition to the web.

**Comment by oes5756** [comment]
@AI-Expert-04 
In another way, I saved every frame of the webcam video as a png file within a second.

Is it possible to send a picture of the saved ".png" frame continuously through socket communication so that it looks like an video?
I need your help.

**Comment by YeopSeung04** [comment]
```

pathIn= 'your Image path'
pathOut = 'name.mp4'
fps = 30
import cv2
frame_array = []
for idx , path in enumerate(paths) : 
    if (idx % 2 == 0) | (idx % 5 == 0) :
        continue
    img = cv2.imread(path)
    height, width, layers = img.shape
    size = (width,height)
    frame_array.append(img)
out = cv2.VideoWriter(pathOut,cv2.VideoWriter_fourcc(*'DIVX'), fps, size)
for i in range(len(frame_array)):
    # writing to a image array
    out.write(frame_array[i])
out.release()
```

**Comment by oes5756** [comment]
@AI-Expert-04 
Thank you for your help.
However, instead of converting the png file into an video,
I want to send "0.png"~"09.png" files continuously through the socket

Convert to video and transfer to socket
There seems to be a problem that the ".png" file cannot be transferred after the converted video.
