### ISSUE TITLE
TFlite output types

### ISSUE THREAD

**Issue by fatihatac** [ultralytics/yolov5#10628]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I trained the YOLOv5s model with my own data and converted it to tflite. To use this model for my own purpose, I need to get 4 outputs. I tried to get 4 outputs but the type of one of the outputs is int32. All outputs must be float32. How can I achieve this?

![image](https://user-images.githubusercontent.com/102164355/209973911-0ab7314b-25e6-4c8f-af1a-bddea908830a.png)

**Comment by webfrank** [comment]
Hi, I have the exact same requirement. I don't know how to have all outputs in float32 format.

**Comment by glenn-jocher** [comment]
@webfrank hi there! You can achieve this by specifying the `--tfl-int8` argument during conversion to TFLite to force all outputs to float32. Additionally, you can refer to the YOLOv5 documentation for more details. Let me know if you need further assistance.

**Comment by webfrank** [comment]
Hi, this way I got a quantized int8 model which is not supported by the
inference engine.

Il giorno mer 15 nov 2023 alle 17:49 Glenn Jocher ***@***.***>
ha scritto:

**Comment by glenn-jocher** [comment]
@webfrank I apologize for the confusion. You can achieve the float32 output by using `--quantize` without `--tfl-int8`. This will produce a float32 TFLite model. Thanks for your understanding and feel free to reach out if you have any other questions.
