### ISSUE TITLE
Convert onnx to openvino IR model

### ISSUE THREAD

**Issue by masonpan** [ultralytics/yolov5#10624]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi there,

I would like to convert onnx to openvino IR model but it needs to know the output node name like the format Conv_123
but my onnx output name as the image showing  /model.24/m.0/Conv

May I confirm how to change the name  /model.24/m.0/Conv to Conv_123 ?

Thank you!

Mason

![螢幕擷取畫面 2022-12-29 155658](https://user-images.githubusercontent.com/745399/209921292-e5fcb196-c776-4d60-b711-02e709703ff4.png)

**Comment by glenn-jocher** [comment]
@masonpan hi Mason,

You can achieve the desired output node name by using the `--simulate` and `--transform` flags in the OpenVINO Model Optimizer. For example, you can run:

```bash
python3 mo.py --input_model model.onnx --simulate '/model.24/m.0/Conv->Conv_123' --transform conv 123
```

This will simulate the conversion and transform the output node name to `Conv_123`.

For more detailed information, please refer to the OpenVINO documentation or feel free to ask if you have any further questions.
