### ISSUE TITLE
Warning - ignoring corrupt image/label: non-normalized or out of bounds coordinates

### ISSUE THREAD

**Issue by Robotatron** [ultralytics/yolov5#10632]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

During training for the instance segmentation (`yolov5/models/segment/yolov5l-seg.yaml`) of my custom dataset that I annotated with polygons myself, I am getting this warning for some of the images:
`train: WARNING ⚠️ /home/..../837.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0021]`

![image](https://user-images.githubusercontent.com/95919873/210022515-ad802852-c71e-40bc-9bbe-e3bda599b4bd.png)

**Comment by YeopSeung04** [comment]
Yolo's label scheme must be x1, x2, y1, y2 right-angled squares or squares. It should never be polygonal.

The label of the image needs to be recreated.
[Tools that allow you to label images to
](https://www.makesense.ai/)
Recommend.

**Comment by Robotatron** [comment]
@AI-Expert-04 Forgot to mention I am doing instance segmentation with YOLO5, so using config from `yolov5/models/segment/yolov5l-seg.yaml`

**Comment by mdhosen** [comment]
I have polygon coordinates like 132 5 132 23 133 23 134 24 134 26 137 29 137 37 ..... (x1 y1 x2 y2  x3 y3....), when I run yolov5 segment model, I get the error like @Robotatron [train: WARNING ⚠️ /home/..../837.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates ]. How will I normalize this polygon coordinates? Thanks in advance.

**Comment by Robotatron** [comment]
> I have polygon coordinates like 132 5 132 23 133 23 134 24 134 26 137 29 137 37 ..... (x1 y1 x2 y2 x3 y3....), when I run yolov5 segment model, I get the error like @Robotatron [train: WARNING ⚠️ /home/..../837.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates ]. How will I normalize this polygon coordinates? Thanks in advance.

I fixed that issue by manually going through all my annotations and making sure the x and y coordinates of my annos are > 0 and lie within the image (not outside of the image). I had to write custom code and fixing my annos in COCO format before exporting to YOLO

**Comment by ultimus11** [comment]
@Robotatron can you share the codebase which you created to fix annotations. That will save some time for me. Thanks in advance.

**Comment by ErfanAlaeii** [comment]
import os

def read_files(directory):
    """Read all files in the specified directory."""
    files_data = {}
    for filename in os.listdir(directory):
        filepath = os.path.join(directory, filename)
        if os.path.isfile(filepath):
            with open(filepath, 'r') as file:
                files_data[filepath] = file.readlines()
                print(f"Read {len(files_data[filepath])} lines from {filepath}")
    return files_data

def normalize_coordinates(data, image_width, image_height):
    """Normalize coordinates and ensure they are within bounds."""
    normalized_lines = []
    for line in data:
        numbers = [float(num) for num in line.split()]
        normalized_numbers = []
        for i, num in enumerate(numbers):
            if i % 2 == 0:  # x coordinate
                normalized_num = num / image_width
            else:  # y coordinate
                normalized_num = num / image_height

            # Ensure coordinates are within [0, 1]
            if normalized_num < 0:
                normalized_num = 0.0
            elif normalized_num > 1:
                normalized_num = 1.0

            normalized_numbers.append(normalized_num)

        normalized_lines.append(" ".join(map(str, normalized_numbers)) + "\n")
    print(f"Normalized {len(normalized_lines)} lines")
    return normalized_lines

def write_files(files_data):
    """Write the normalized data back to the files."""
    for filepath, data in files_data.items():
        with open(filepath, 'w') as file:
            file.writelines(data)
            print(f"Wrote {len(data)} lines to {filepath}")

def main(directory, image_width, image_height):
    files_data = read_files(directory)
    for filepath, data in files_data.items():
        files_data[filepath] = normalize_coordinates(data, image_width, image_height)
    write_files(files_data)

if __name__ == "__main__":
    directory = '/content/yolov5/Potato___Late_blight-1/train/labels'  # Replace with the path to your directory
    image_width = 640  # Replace with your image width
    image_height = 480  # Replace with your image height
    main(directory, image_width, image_height)

**Comment by glenn-jocher** [comment]
Hey there! It looks like you're trying to normalize and ensure your annotation coordinates are within bounds. Here's a Python script that should help you with that. This script reads the annotation files, normalizes the coordinates based on the image dimensions, and ensures all values are clamped between 0 and 1. Finally, it writes the normalized data back to the files.

```python
import os

def read_files(directory):
    """Read all files in the specified directory."""
    files_data = {}
    for filename in os.listdir(directory):
        filepath = os.path.join(directory, filename)
        if os.path.isfile(filepath):
            with open(filepath, 'r') as file:
                files_data[filepath] = file.readlines()
    return files_data

def normalize_coordinates(data, image_width, image_height):
    """Normalize coordinates and ensure they are within bounds."""
    normalized_lines = []
    for line in data:
        numbers = [float(num) for num in line.split()]
        normalized_numbers = []
        for i, num in enumerate(numbers):
            if i % 2 == 0:  # x coordinate
                normalized_num = num / image_width
            else:  # y coordinate
                normalized_num = num / image_height

            # Ensure coordinates are within [0, 1]
            normalized_num = max(0.0, min(1.0, normalized_num))
            normalized_numbers.append(normalized_num)

        normalized_lines.append(" ".join(map(str, normalized_numbers)) + "\n")
    return normalized_lines

def write_files(files_data):
    """Write the normalized data back to the files."""
    for filepath, data in files_data.items():
        with open(filepath, 'w') as file:
            file.writelines(data)

def main(directory, image_width, image_height):
    files_data = read_files(directory)
    for filepath, data in files_data.items():
        files_data[filepath] = normalize_coordinates(data, image_width, image_height)
    write_files(files_data)

if __name__ == "__main__":
    directory = '/path/to/your/labels'  # Replace with the path to your directory
    image_width = 640  # Replace with your image width
    image_height = 480  # Replace with your image height
    main(directory, image_width, image_height)
```

Make sure to replace the `directory`, `image_width`, and `image_height` with your actual values. This should help you get your annotations ready for training with YOLOv5! 😊
