### ISSUE TITLE
Can I convert VisDrone annotations using VisDrone.yaml using multiprocessing?

### ISSUE THREAD

**Issue by NoamLA** [ultralytics/yolov5#10631]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I noticed the conversion process was highly time consuming and I tried to improve it using multiprocessing. I keep getting this error
![image](https://user-images.githubusercontent.com/87585100/209995205-1e64b18e-dc41-402d-b2d3-45791f945679.png)
 
**running**

 !python  yolov5/train.py --batch 32 --epochs 300 --data 'yolov5/data/VisDrone-Copy1.yaml'  --img 1280 --weights 'yolov5m6.pt' --project 'drone_291222' --name 'Initial' --cache 

**Modified yaml**

# YOLOv5 🚀 by Ultralytics, GPL-3.0 license
# VisDrone2019-DET dataset https://github.com/VisDrone/VisDrone-Dataset by Tianjin University
# Example usage: python train.py --data VisDrone.yaml
# parent
# ├── yolov5
# └── datasets
#     └── VisDrone  ← downloads here (2.3 GB)

# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: ../datasets/VisDrone  # dataset root dir
train: VisDrone2019-DET-train/images  # train images (relative to 'path')  6471 images
val: VisDrone2019-DET-val/images  # val images (relative to 'path')  548 images
test: VisDrone2019-DET-test-dev/images  # test images (optional)  1610 images

# Classes
names:
  0: pedestrian
  1: people
  2: bicycle
  3: car
  4: van
  5: truck
  6: tricycle
  7: awning-tricycle
  8: bus
  9: motor

# Download script/URL (optional) ---------------------------------------------------------------------------------------
download: |
  from utils.general import download, os, Path
  import multiprocessing
  from PIL import Image
  from tqdm import tqdm
  from multiprocessing import Pool

  def visdrone2yolo_worker(f):

      def convert_box(size, box):
          # Convert VisDrone box to YOLO xywh box
          dw = 1. / size[0]
          dh = 1. / size[1]
          return (box[0] + box[2] / 2) * dw, (box[1] + box[3] / 2) * dh, box[2] * dw, box[3] * dh

      for f in pbar:
          img_size = Image.open((dir / 'images' / f.name).with_suffix('.jpg')).size
          lines = []
          with open(f, 'r') as file:  # read annotation.txt
              for row in [x.split(',') for x in file.read().strip().splitlines()]:
                  if row[4] == '0':  # VisDrone 'ignored regions' class 0
                      continue
                  cls = int(row[5]) - 1
                  box = convert_box(img_size, tuple(map(int, row[:4])))
                  lines.append(f"{cls} {' '.join(f'{x:.6f}' for x in box)}\n")
                  with open(str(f).replace(os.sep + 'annotations' + os.sep, os.sep + 'labels' + os.sep), 'w') as fl:
                      fl.writelines(lines)  # write label.txt

  def visdrone2yolo(dir):
      (dir / 'labels').mkdir(parents=True, exist_ok=True)  # make labels directory
      pbar = tqdm((dir / 'annotations').glob('*.txt'), desc=f'Converting {dir}')
      with Pool(50) as p:  # create a pool of 50 worker processes
          p.map(visdrone2yolo_worker, pbar)  # apply visdrone2yolo_worker to each file in pbar in parallel

  

  # Download
  dir = Path(yaml['path'])  # dataset root dir
  urls = ['https://github.com/ultralytics/yolov5/releases/download/v1.0/VisDrone2019-DET-train.zip',
          'https://github.com/ultralytics/yolov5/releases/download/v1.0/VisDrone2019-DET-val.zip',
          'https://github.com/ultralytics/yolov5/releases/download/v1.0/VisDrone2019-DET-test-dev.zip',
          'https://github.com/ultralytics/yolov5/releases/download/v1.0/VisDrone2019-DET-test-challenge.zip']
  download(urls, dir=dir, curl=True, threads=4)

  # Convert
  for d in  'VisDrone2019-DET-train', 'VisDrone2019-DET-val', 'VisDrone2019-DET-test-dev': 
      visdrone2yolo(dir / d)  # convert VisDrone annotations to YOLO labels

### Additional

If there are any other ideas on how to convert it faster I'll be happy to try

Many thanks!

**Comment by YeopSeung04** [comment]
You only receive jpg for image extension
But there might be a png for this image
We need to change it to *.jpg

**Comment by NoamLA** [comment]
It wasn't the problem I encountered but thanks for the response

**Comment by glenn-jocher** [comment]
@NoamLA hi there! Thanks for reaching out with your question. I'm glad you were able to identify the issue. If you have any other questions or need further assistance, feel free to ask. Good luck with your project!
