### ISSUE TITLE
Multi-GPU DistributedDataParallel training speed with 2x GPUs roughly same as 1x GPU

### ISSUE THREAD

**Issue by Robotatron** [ultralytics/yolov5#10645]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

GPU: V100, dataset of ~30_000 images used for instance segmentation training (`seg/train.py`). 

Times for 1 epoch depending on the command line arguments:

### Multi-GPU [DistributedDataParallel](https://pytorch.org/docs/stable/nn.html#torch.nn.parallel.DistributedDataParallel) Mode (✅ recommended)
* #### 1x GPU: [09:12, 08:50, 08:44, 08:43] = approx. 9 min per epoch
`python -m torch.distributed.run --nproc_per_node 1 segment/train.py --img 800 --epochs 300 --data data/parts_only_split.yaml --weights '' --cfg yolov5l-seg.yaml --hyp hyp.scratch-high.yaml --batch 10`

* #### 2x GPUs: [08:00, 07:55, 07:37, 07:28] = approx. 8 min per epoch
`python -m torch.distributed.run --nproc_per_node 2 segment/train.py --img 800 --epochs 300 --data data/parts_only_split.yaml --weights '' --cfg yolov5l-seg.yaml --hyp hyp.scratch-high.yaml --batch 20`

### Multi-GPU [DataParallel](https://pytorch.org/docs/stable/nn.html#torch.nn.DataParallel) Mode (⚠️ not recommended)
* #### 2x GPU: [08:44, 08:20] = approx. 8:30 per epoch
`python segment/train.py --img 800 --epochs 300 --data data/parts_only_split.yaml --weights '' --cfg yolov5l-seg.yaml --hyp hyp.scratch-high.yaml --batch 10`

Could it be due to high CPU usage when using `hyp.scratch-high` and having a slower CPU with 2 Ghz Xeon as the bottleneck?
![image](https://user-images.githubusercontent.com/95919873/210187630-cb8a1fb4-964f-48da-a5f1-90603429bb0a.png)

**Comment by wolfpack12** [comment]
You doubled the batch size with 2 GPUs. Wouldn’t you need to keep them the same as 1 GPU for an apples-to-apples comparison?

**Comment by Robotatron** [comment]
> You doubled the batch size with 2 GPUs. Wouldn’t you need to keep them the same as 1 GPU for an apples-to-apples comparison?

Double the batch size because of 2x GPUs, so that each GPU gets 50% of the total batch size. In other words the provided batch size is automatically split between all the GPUs

**Comment by wolfpack12** [comment]
It doesn’t look like you specified the devices you want to use for training. Did you try using the —device argument?

**Comment by Robotatron** [comment]
> It doesn’t look like you specified the devices you want to use for training. Did you try using the —device argument?

"`--nproc_per_node"` specifies the number of GPUs to use. `"--device"` is only needed if you want to specify concrete GPUs, its not needed if I want to use all of them.

**Comment by Robotatron** [comment]
I solved the issue. When using 2x GPU one needs a machine with 2x the CPU power, so from 8 core 1 gpus one needs 16 cores with 2 gpus, then I was able to cut the training time in half.
Image augmentation maxes out 8 cores per GPU
