### ISSUE TITLE
TypeError when running "segment/predict.py" with --augment flag

### ISSUE THREAD

**Issue by Robotatron** [ultralytics/yolov5#10642]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Neither image nor video segmentation is working with "`segment/predict.py`" when using the `--augment` flag for TTA. 
Which is really a shame since it improves the predictions. Was it never supported or is it a bug?

![image](https://user-images.githubusercontent.com/95919873/210161338-cc561c4f-a498-419c-84fa-fbb37c2650a0.png)

### Environment

YOLOv5 🚀 v7.0-53-g65071da Python-3.8.15 torch-1.10.1

### Minimal Reproducible Example

!python segment/predict.py --source "{source}" --weights $weights --imgsz $imgsz --device $device --name "{name}-aug" --line-thickness 2 --conf-thres 0.5 --augment

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by rezmal** [comment]
any update on this one? having the same issue with --augment with segment/predict.py

**Comment by glenn-jocher** [comment]
@rezmal no worries! I've replicated the issue and will look into it. Thanks for flagging this, and I appreciate your patience. I'll keep you posted on any progress regarding this matter.
