### ISSUE TITLE
Which tools do I use to build an automatic drift detection system around the YOLOv5 model?

### ISSUE THREAD

**Issue by FnSK4R17s** [ultralytics/yolov5#10647]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am trying to run the YOLOv5 model on live Youtube Streams and save images for annotation only when I detect something unusual in the image. How do I automate this process? Any help and / or suggestion would be valuable. I am trying to set up drift detection but I'm not sure how to do it or if it would solve my problem.

Thanks

**Comment by Robotatron** [comment]
drift detection? Drift of a car? Inference data distribution drift?

**Comment by FnSK4R17s** [comment]
@Robotatron inference data distribution drift
