### ISSUE TITLE
Question regarding yolov5 results

### ISSUE THREAD

**Issue by vsumm** [ultralytics/yolov5#10648]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Run `detect.py`  using the below command 

`python detect.py --weight yolov5 --source video1.mp4`

Now how can I compress videos and save videos as results or how to reduce frames per sec in `detect.py`

**Comment by YeopSeung04** [comment]
```
 yolov5
 |---- .github
 |---- classify
 |---- data
 |---- models
 |---- sagment
 |---- utlis
 |---- runs
 |    |---- detect
 |    |    |---- exp 
 |    |    |    |---- video.mp4
```


if you haven't modified the code
You will be on the path above. exp increases exp1, exp2 when you run it.
yolov5 detects frame by frame. However, since the video is saved at 15 fps, the speed of the detected video will look fast.

**Comment by glenn-jocher** [comment]
@AI-Expert-04 hello!

To modify the output video fps, you can add `--fps 30` to `detect.py` to change the output framerate. To compress the video, use `cv2.VideoWriter_fourcc` in the code.

```python
import cv2

# Initialize the video writer
out = cv2.VideoWriter('path_to_output_video.mp4', 
                      cv2.VideoWriter_fourcc(*'mp4v'),
                      30, 
                      (width, height))

# Loop through frames and write them to the output video
for _ in range(num_frames):
    # ... (detect and draw bounding boxes)
    out.write(frame)

# Release the video writer
out.release()
```

Kindly refer to our documentation for detailed information.

Best regards!
