### ISSUE TITLE
Inferences time

### ISSUE THREAD

**Issue by alazka8** [ultralytics/yolov5#10650]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I have question about inferences time.
You paste that the [YOLOv5x6](https://github.com/ultralytics/yolov5/releases/download/v6.2/yolov5x6.pt) model on V100 GPU inferences time is 19-26ms. I try this same model on my V100 GPU and the time is creepy.

I do inferences like that
```
        model = torch.hub.load('yolov5', 'custom', path = f'src/models/{model_filename}', source = 'local', device = f'cuda:{gpu_id}')
        model.conf = 0.2
        model.classes = [0]
        device = torch.device(f'cuda:{gpu_id}')
        model.to(device)

       model(IMAGE) #FIRST 
       model(IMAGE, size=1280) #SECOND
```

On first method time is about 50ms
On Seconds method time is about 100ms

I cant decrease time to this ~20ms, is it normal time ?

**Comment by Robotatron** [comment]
Did you figure it out?
