### ISSUE TITLE
NMS without PyTorch for exported models

### ISSUE THREAD

**Issue by ianhco** [ultralytics/yolov5#10652]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Greetings, I want to execute NMS for an exported ONNX model, however the the NMS algorithm is dependant of PyTorch, would like to know if there is an alternative that does not use PyTorch, preferably with only Numpy, would like the dependencies of the model to be as lightweight as possible to fit in an AWS lambda (<250MB).

Or peraphs there is a lighter version of PyTorch that only includes the minimum components for NMS only ?

**Comment by wolfpack12** [comment]
This is being discussed here: https://github.com/ultralytics/yolov5/pull/7736

**Comment by glenn-jocher** [comment]
@wolfpack12 thanks for your question! We're currently discussing this topic in detail at https://github.com/ultralytics/yolov5/pull/7736. Feel free to join the conversation or stay tuned for updates. Our priority is to keep YOLOv5 dependencies lightweight and user-friendly. For further information, you can also refer to the Ultralytics Docs at https://docs.ultralytics.com/yolov5/.
