### ISSUE TITLE
Problem with ClearML and ClearML ID for datasets

### ISSUE THREAD

**Issue by bzisl** [ultralytics/yolov5#10662]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm trying to execute the train:

 train.py --img 512 --rect --batch 250 --epochs 300 --workers 64 --data clearml://ed2799825c964a6fa75157e9a0111cbc

I assume that we can use the clearml ID, but I getting too many troubles:

github: up to date with https://github.com/ultralytics/yolov5 ✅
YOLOv5 🚀 v7.0-57-gbd69370e Python-3.8.10 torch-1.13.0+cu117 CUDA:0 (NVIDIA GeForce RTX 3090, 24268MiB)

hyperparameters: lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0
Comet: run 'pip install comet_ml' to automatically track and visualize YOLOv5 🚀 runs in Comet
TensorBoard: Start with 'tensorboard --logdir xxxx', view at http://localhost:6006/
ClearML Task: created new task id=d9af9b6ee25c429bb9ee87dc24c33b52
ClearML results page: http://172.16.30.136:8080/projects/d3abf85a756b4413b7f3b7ecf754a47a/experiments/d9af9b6ee25c429bb9ee87dc24c33b52/output/log
2023-01-03 17:27:38,106 - clearml - INFO - Dataset.get() did not specify alias. Dataset information will not be automatically logged in ClearML Server.
ClearML: WARNING ⚠️ ClearML is installed but not configured, skipping ClearML logging. See https://github.com/ultralytics/yolov5/tree/master/utils/loggers/clearml#readme
Traceback (most recent call last):
  File "train.py", line 635, in <module>
    main(opt)
  File "train.py", line 529, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 112, in train
    data_dict = data_dict or check_dataset(data)  # check if None
  File "/home/paco/AI/aistage3/yolov5/utils/general.py", line 503, in check_dataset
    if isinstance(data, (str, Path)) and (is_zipfile(data) or is_tarfile(data)):
  File "/usr/lib/python3.8/tarfile.py", line 2471, in is_tarfile
    t = open(name)
  File "/usr/lib/python3.8/tarfile.py", line 1603, in open
    return func(name, "r", fileobj, **kwargs)
  File "/usr/lib/python3.8/tarfile.py", line 1667, in gzopen
    fileobj = GzipFile(name, mode + "b", compresslevel, fileobj)
  File "/usr/lib/python3.8/gzip.py", line 173, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'clearml://ed2799825c964a6fa75157e9a0111cbc'

**Comment by thepycoder** [comment]
This is a duplicate of #10686 and I'm handling the issue there.

**Comment by glenn-jocher** [comment]
@thepycoder this issue seems to be a duplicate of #10686, and I'm already addressing the problem over there. Thank you for reaching out, and I'll make sure to provide a comprehensive answer in the original thread. If you have any additional questions or concerns, feel free to ask.
