### ISSUE TITLE
How do I run ONNXRUNTIME inferencing?

### ISSUE THREAD

**Issue by jaydeshpande** [ultralytics/yolov5#1066]
## ❔Question
Hi team, 

Is there a convenient script I can use for inferencing on ONNX export?

**Comment by glenn-jocher** [comment]
https://microsoft.github.io/onnxruntime/python/auto_examples/plot_load_and_predict.html

**Comment by jaydeshpande** [comment]
Solved here: 
https://github.com/ultralytics/yolov5/issues/343
