### ISSUE TITLE
Exception when using "segment/predict.py" with Model Ensembling

### ISSUE THREAD

**Issue by Robotatron** [ultralytics/yolov5#10668]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Using model ensembling with `segment/predict.py` errors out.

Was this ever supported for segmentation or is it a bug? If it was never supported, do you plan to add support of this similar to object detection?

![image](https://user-images.githubusercontent.com/95919873/210470527-03ebd2d1-01ce-4740-a4c0-a3f55eaf8255.png)

### Environment

YOLOv5 🚀 v7.0-53-g65071da Python-3.8.15 torch-1.10.1 CUDA:0 (Tesla V100-SXM2-16GB, 16160MiB)

### Minimal Reproducible Example

python segment/predict.py (...) --weights weight1.pt weight2.pt

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Robotatron** [comment]
Still a bug

**Comment by minazamani7** [comment]
>  same question, could we use  model ensembling with segment/predict.py ?

**Comment by glenn-jocher** [comment]
@minazamani7 hello! Thank you for your question. Currently, the ensembling functionality is not supported with the `segment/predict.py` script. However, it has been requested by the community, and our team is considering adding it in a future release. In the meantime, please feel free to keep an eye on the YOLOv5 repository for updates. Let us know if you have any other questions or concerns, and we'll be happy to help.
