### ISSUE TITLE
Command to count the detected objects in jpg pictures and download list of results 

### ISSUE THREAD

**Issue by aqi147** [ultralytics/yolov5#10675]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I can see the number of detected objects ion the model.summary as shown in the picture but don,t know how to download summary or which command to use for counting the objects in jpg. files. 
Please help me with this simple question
![ww](https://user-images.githubusercontent.com/121790948/210571836-4a782444-2def-4636-a4b9-e44a02a87011.JPG)

**Comment by FnSK4R17s** [comment]
Have you tried editing the detect.py file to print out the length of the list of detected objects in each image?

**Comment by aqi147** [comment]
> Have you tried editing the detect.py file to print out the length of the list of detected objects in each image?

Hi,
 I tried but not successful, can you please share me the relavent code to generate the list of detected objects

**Comment by glenn-jocher** [comment]
@aqi147 certainly! You can use the following code snippet to print the count of detected objects in each image:

```python
import torch
from PIL import Image
from yolov5.models.experimental import attempt_load
from yolov5.utils.datasets import letterbox
from yolov5.utils.general import non_max_suppression, scale_coords
from yolov5.utils.plots import colors

# Load YOLOv5 model
model = attempt_load(weights='yolov5s.pt', map_location=torch.device('cpu'))

# Load image
img_path = 'path_to_image.jpg'
img = Image.open(img_path)

# Preprocess image
img_size = 640
img = letterbox(img, img_size)[0]
img = torch.from_numpy(img).to('cpu')
img = img.float()  # uint8 to fp16/32
img /= 255.0  # 0 - 255 to 0.0 - 1.0
if img.ndimension() == 3:
    img = img.unsqueeze(0)

# Inference
pred = model(img)[0]
pred = non_max_suppression(pred, conf_thres=0.4, iou_thres=0.45)

# Count and print detected objects
for i, det in enumerate(pred):  # detections per image
    if det is not None and len(det):
        det[:, :4] = scale_coords(img.shape[2:], det[:, :4], img.size).round()
        print(f"Image {i+1}: {len(det)} objects detected")
```

Replace `'path_to_image.jpg'` with the actual path to your image. This code will load the YOLOv5 model, perform inference on the image, and print the count of detected objects.

Remember to install the required dependencies and modify the paths as necessary.

For more details, refer to the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/.
