### ISSUE TITLE
How to view the classes of a trained model?

### ISSUE THREAD

**Issue by HiaHong** [ultralytics/yolov5#10672]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Sometimes too much time passes and I forget the labels used by the previous model, and I want to see which labels were used by the previous model

**Comment by glenn-jocher** [comment]
@HiaHong to view the classes of a trained model, you can find the class labels in the `*.names` file in the `yolov5/data` directory. Alternatively, you can use the `python train.py --data path-to-data.yaml --cache --weights last.pt --cfg models/yolov5s.yaml --evolve` command to display the classes in the terminal. Further details can be found in the [Ultralytics Docs](https://docs.ultralytics.com/yolov5/). Let me know if you need any further assistance!
