### ISSUE TITLE
Question about the batch_size of yolov8x

### ISSUE THREAD

**Issue by RangeKing** [ultralytics/yolov5#10674]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Why the batch_size of yolov8x is 129 not 128?
![image](https://user-images.githubusercontent.com/27466624/210562085-55dcdfd5-c920-49d4-8571-2b929df00696.png)

**Comment by glenn-jocher** [comment]
@RangeKing the batch size of YOLOv5 is often set to a multiple of the number of GPUs for efficient distributed training. The batch size of 129 likely reflects this optimization, which may have been introduced through experimentation for better performance. Please refer to our documentation for more detailed information on configuration and training strategies.
