### ISSUE TITLE
How are the output coordinates sorted for yolov5. I'm talking about the output of results.xyxy[0]

### ISSUE THREAD

**Issue by Hisan-007** [ultralytics/yolov5#10679]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How are the output coordinates sorted for yolov5. I'm talking about the output of results.xyxy[0]

**Comment by glenn-jocher** [comment]
@HissaanAli the `results.xyxy` output coordinates in YOLOv5 are sorted by descending objectness confidence and then ascending class confidence. This means that the highest confidence objects come first. For further details, you can refer to the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/. Let me know if you have any other questions!
