### ISSUE TITLE
How can I get the area of each bounding-box in prediction?

### ISSUE THREAD

**Issue by LokedSher** [ultralytics/yolov5#1068]
## ❔Question
How can I get the area of each bounding-box in prediction?

**Comment by Aktcob** [comment]
area = W*H

https://github.com/ultralytics/yolov5/blob/master/utils/general.py#L620

area = x[:, 2]*x[:, 3]

**Comment by LokedSher** [comment]
> area = W*H
> 
> https://github.com/ultralytics/yolov5/blob/master/utils/general.py#L620
> 
> area = x[:, 2]*x[:, 3]

Thank you very much!
