### ISSUE TITLE
could not convert string to float

### ISSUE THREAD

**Issue by xuweidongkobe** [ultralytics/yolov5#10685]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

when I train the model,  I put the label info in the txt file as usual , but happened the warning this time , can I ask how to change the code to solve the problem?
<img width="656" alt="屏幕截图 2023-01-05 175004" src="https://user-images.githubusercontent.com/25764883/210751498-5d7099de-c626-4506-810c-49d93dd5e879.png">

**Comment by thnak** [comment]
the labels should be 0 0.498408 0.509804 0.990446 0.980392
but you have 0,0.498408,0.509804,0.990446,0.980392
just replace "," with " "

**Comment by xuweidongkobe** [comment]
> the labels should be 0 0.498408 0.509804 0.990446 0.980392 but you have 0,0.498408,0.509804,0.990446,0.980392 just replace "," with " "

thanks

**Comment by xuweidongkobe** [comment]
solved

**Comment by glenn-jocher** [comment]
@xuweidongkobe glad to hear it's resolved! 👍 If you need further assistance, feel free to ask.
