### ISSUE TITLE
Tflite GPU compatibility

### ISSUE THREAD

**Issue by ily-R** [ultralytics/yolov5#10697]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Export

### Bug

Hello,

it's compatibility with Android environment problem. The capture below shows the warning I received from trying to run the exported tflite model on my Android mobile using the GPU delegate. Not only this, but the model is quite slow ~700ms. I tested on different android phones.

if I use the mobilenetv2 tflite for example I dont get this warning and the model is much faster.

My thoughts is maybe we should rethink tf.py implementation to get more ops supported by tflite on GPU following mobileNet implementation.

Even inference on my computer (M1 Mac Pro) using tflite exported model is slow ~140ms compared to pytorch model and onnx.

If you run into the same problem please share your thoughts/solutions

Thank you

![gpu](https://user-images.githubusercontent.com/22728018/211002795-bbeb9474-601f-4f97-855d-94ef8ffe89e3.png)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ily-R thanks for reaching out. The tflite model's performance on Android devices is indeed an area where we can make improvements. The warning you received is related to unsupported TensorFlow Lite GPU ops, and we are actively working on making YOLOv5 more compatible with tflite on GPU. For now, you might try deploying the model with the CPU delegate as it generally has better compatibility.

As for the slow inference times, it's a known issue, and we are continuously optimizing our tflite export process for mobile devices. In the meantime, you may want to consider using the ONNX export for faster performance on both mobile and desktop.

Your feedback is greatly appreciated as we work to enhance YOLOv5 compatibility across all platforms. Thank you for your patience and understanding.
