### ISSUE TITLE
Is it possible to extend to 3D YOLO detection?

### ISSUE THREAD

**Issue by frabob2017** [ultralytics/yolov5#10693]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Hello YOLOV5 team, is it possible in the future that YOLOv5 implement conv3d kernel for object detection?  Since I want to process medical imaging, the lesions are usually continuous several slices, if use conv3d kernel for object detection, it would be more suitable for my study? 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@frabob2017 hi there! Thanks for reaching out. Implementing a 3D detection capability with conv3d kernels is an interesting idea for medical imaging. At the moment, YOLOv5 specifically supports 2D object detection. While the project doesn't currently support 3D detection, we're always open to new ideas and community contributions. 
If you're interested in customizing YOLOv5 for your study, you might consider extending the framework to support 3D detection or exploring other similar projects that could better fit your needs. Let me know if there's anything else I can help with!
