### ISSUE TITLE
How to load the model in torch 0.4.1 ?

### ISSUE THREAD

**Issue by MayLelele** [ultralytics/yolov5#1069]
## 🐛 Bug
I train my model on the code (yolov5s) with torch 1.4 ,but now I  wanna detect my pics in  torc h0.4 , when I load my model ,it raises a big bug! 

I load my model in the ways:

        state_dict = model['model'].float().state_dict()
        torch.save(state_dict, './oil_09333.pt')

But it didn't work, so what should I do to use the model in torch 0.4.1 ?

**Comment by glenn-jocher** [comment]
@Honsia this is not a bug. The requirements clearly state torch 1.6 or higher, suggest you follow them.
