### ISSUE TITLE
Same size ROIs

### ISSUE THREAD

**Issue by wcab1** [ultralytics/yolov5#10691]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am working on behavioral analysis scripts that iterate through video frames and identify a target in each frame and then save that selection as a cropped image. I was wondering if it were possible to set the detection ROIs to all be the same size? Thanks!

**Comment by glenn-jocher** [comment]
@wcab1 hey there! 👋 You can certainly achieve this by resizing the input images to a consistent size before running the YOLOv5 inference. This can be done using standard image processing libraries such as OpenCV or Pillow. Feel free to refer to the YOLOv5 documentation for more detailed guidance on preprocessing inputs. Let me know if you need any further assistance!
