### ISSUE TITLE
Why my model export into TensorRT engine but response with an OS Error?

### ISSUE THREAD

**Issue by ElinLiu0** [ultralytics/yolov5#10706]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,i want export my self trained model into TensorRT engine on my PC and deploy it on to a Jetson Nano.
I using below command to export my model:
```shell
python export.py --weights ./runs/train/exp/weights/best.pt --include engine --device 0
```
But the `export,py` returns an OS Error with error code 127 like this:
```shell
PyTorch: starting from runs\train\exp\weights\best.pt with output shape (1, 25200, 10) (13.8 MB)
TensorRT: export failure  0.1s: [WinError 127]
```

But the weired thing is my TensorRT has successfully install on Python env,this is my ipython terminal returns
```python
In [1]: import tensorrt as trt

In [2]: trt.__version__
Out[2]: '8.4.2.4'
```

So how should i fix this problem,really need a rush since is pretty close to my deadline of project,plz  T_T

**Comment by ManuApril** [comment]
me too,u should check cuda/v11.4/bin cublas64_11.dll is same with anaconda/envs/lib/site-packages,u should check it

**Comment by chaohuichen1024** [comment]
@RosterMouch 
I also encountered the same problem. The solution is to use E:\Anaconda\envs\YOLOV5\Lib\site-packages\torch\lib\cublas64_11.dll in the annconda virtual environment  replace E:\CUDA\NVIDIA GPU Computing Toolkit\CUDA11.1\bin\cublas64_11.dll in cuda environment

**Comment by ElinLiu0** [comment]
> @RosterMouch I also encountered the same problem. The solution is to use E:\Anaconda\envs\YOLOV5\Lib\site-packages\torch\lib\cublas64_11.dll in the annconda virtual environment replace E:\CUDA\NVIDIA GPU Computing Toolkit\CUDA11.1\bin\cublas64_11.dll in cuda environment

并不是，我换了一种比较笨的思路：那就是让Pytorch、cuDNN还有TRT都运行同一个CUDA依赖
比如我说我现在的conda环境里就是：
- Pytorch 1.13.1+cu117
- cuDNN 8.6.x
- TensorRT 8.5.x
这样他们三个都须要依赖CUDA11.7驱动进行工作，我于是先卸载掉了我的CUDA11.8，更换了为了11.7.1
然后将上述三个软件包更换了上述版本。
使用yolov5自带的export.py指定--include engine就可以成功导出了。

**Comment by ElinLiu0** [comment]
> me too,u should check cuda/v11.4/bin cublas64_11.dll is same with anaconda/envs/lib/site-packages,u should check it

Yeah i using a way that kind been nut,but it`s really working:
Let cuDNN,TensorRT and Pytorch running on all same CUDA Driver.
Here is my conda env example
- Pytorch 1.13.1+cu117
- cuDNN 8.6.x
- TensorRT 8.5.x
In this way,this three components are all rely on CUDA11.7,so i uninstall my 11.8 and install 11.7.1
all working fine right now.With intergrated export.py in yolov5 repo,to export model with args `--include engine` working fine in whether fp32 model or int8.

**Comment by fatinghenji** [comment]
I noticed in the discussion above that it was prompted to have the same CUDA version, but I had the same issue with the same CUDA version.
```
(apex) PS H:\YOLO_PER_2.1> nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_19:00:59_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0
```
pip list
```
……
nvidia-cublas-cu12       12.2.5.6
nvidia-cuda-nvrtc-cu12   12.2.140
nvidia-cuda-runtime-cu12 12.2.140
nvidia-cudnn-cu12        8.9.4.25
……
tensorrt-libs            9.0.0.post12.dev1
torch                    2.0.1+cu117
torchaudio               2.0.2+cu117
torchvision              0.15.2+cu117
……
```
An error is reported:
```python
(apex) PS H:\YOLO_PER_2.1> python export.py --device 0 --weights "H:\YOLO_PER_2.1\敌我.pt" --batch-size 10 --imgsz 640 --include engine --simplify
export: data=H:\YOLO_PER_2.1\data\coco128.yaml, weights=['H:\\YOLO_PER_2.1\\.pt'], imgsz=[640], batch_size=10, device=0, half=False, inplace=False, keras=False, optimize=False, int8=False, dynamic=False, simplify=True, opset=12, verbose=False, workspace=4, nms=False, agnostic_nms=False, topk_per_class=100, topk_all=100, iou_thres=0.45, conf_thres=0.25, include=['engine']
YOLOv5  2022-11-22 Python-3.8.18 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 4070 Ti, 12282MiB)

Fusing layers...
Model summary: 157 layers, 1763224 parameters, 0 gradients

PyTorch: starting from H:\YOLO_PER_2.1\.pt with output shape (10, 25200, 8) (3.6 MB)
TensorRT: export failure  3.6s: [WinError 127]
```

**Comment by ElinLiu0** [comment]
> I noticed in the discussion above that it was prompted to have the same CUDA version, but I had the same issue with the same CUDA version.
> 
> ```
> (apex) PS H:\YOLO_PER_2.1> nvcc -V
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2022 NVIDIA Corporation
> Built on Tue_May__3_19:00:59_Pacific_Daylight_Time_2022
> Cuda compilation tools, release 11.7, V11.7.64
> Build cuda_11.7.r11.7/compiler.31294372_0
> ```
> 
> pip list
> 
> ```
> ……
> nvidia-cublas-cu12       12.2.5.6
> nvidia-cuda-nvrtc-cu12   12.2.140
> nvidia-cuda-runtime-cu12 12.2.140
> nvidia-cudnn-cu12        8.9.4.25
> ……
> tensorrt-libs            9.0.0.post12.dev1
> torch                    2.0.1+cu117
> torchaudio               2.0.2+cu117
> torchvision              0.15.2+cu117
> ……
> ```
> 
> An error is reported:
> 
> ```python
> (apex) PS H:\YOLO_PER_2.1> python export.py --device 0 --weights "H:\YOLO_PER_2.1\敌我.pt" --batch-size 10 --imgsz 640 --include engine --simplify
> export: data=H:\YOLO_PER_2.1\data\coco128.yaml, weights=['H:\\YOLO_PER_2.1\\.pt'], imgsz=[640], batch_size=10, device=0, half=False, inplace=False, keras=False, optimize=False, int8=False, dynamic=False, simplify=True, opset=12, verbose=False, workspace=4, nms=False, agnostic_nms=False, topk_per_class=100, topk_all=100, iou_thres=0.45, conf_thres=0.25, include=['engine']
> YOLOv5  2022-11-22 Python-3.8.18 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 4070 Ti, 12282MiB)
> 
> Fusing layers...
> Model summary: 157 layers, 1763224 parameters, 0 gradients
> 
> PyTorch: starting from H:\YOLO_PER_2.1\.pt with output shape (10, 25200, 8) (3.6 MB)
> TensorRT: export failure  3.6s: [WinError 127]
> ```

你的cublas,runtime,以及cudnn的python轮子版本是12的，而你的CUDA驱动和Pytorch是11.7的

**Comment by glenn-jocher** [comment]
@ElinLiu0 it seems that there is a version mismatch between your CUDA driver and the Python wheels for cublas, runtime, and cuDNN. While your CUDA driver version is 11.7, the Python wheels for cublas, runtime, and cuDNN are version 12.

To resolve this issue, you need to ensure that all components have matching versions. You can either update your CUDA driver to version 12 to match the Python wheels, or downgrade the Python wheels to version 11.7 to match your current CUDA driver.

Please make sure that all components, including the CUDA driver, cublas, runtime, and cuDNN, have compatible versions, and then try running the export script again.

Let me know if you need any further assistance!

**Comment by fatinghenji** [comment]
I made some changes to my cuda version, but it seems that the issue is not resolved, here is the log:
```python
(apex) PS H:\YOLO_PER_2.1> python export.py --device 0 --weights "H:\YOLO_PER_2.1\敌我.pt" --batch-size 10 --imgsz 640 --include engine --simplify
export: data=H:\YOLO_PER_2.1\data\coco128.yaml, weights=['H:\\YOLO_PER_2.1\\.pt'], imgsz=[640], batch_size=10, device=0, half=False, inplace=False, keras=False, optimize=False, int8=False, dynamic=False, simplify=True, opset=12, verbose=False, workspace=4, nms=False, agnostic_nms=False, topk_per_class=100, topk_all=100, iou_thres=0.45, conf_thres=0.25, include=['engine']
YOLOv5  2022-11-22 Python-3.8.18 torch-2.2.0.dev20230925+cu121 CUDA:0 (NVIDIA GeForce RTX 4070 Ti, 12282MiB)

Fusing layers...
Model summary: 157 layers, 1763224 parameters, 0 gradients

PyTorch: starting from H:\YOLO_PER_2.1\.pt with output shape (10, 25200, 8) (3.6 MB)
TensorRT: export failure  0.2s: [WinError 127]
```
Here is the  informations about CUDA version  and pip packages:
```
(apex) PS H:\YOLO_PER_2.1> nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:36:15_Pacific_Daylight_Time_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0
```

```
torch                    2.2.0.dev20230925+cu121
torchaudio               2.2.0.dev20230926+cu121
torchvision              0.17.0.dev20230926+cu121
……
nvidia-cublas-cu12       12.2.5.6
nvidia-cuda-nvrtc-cu12   12.2.140
nvidia-cuda-runtime-cu12 12.2.140
nvidia-cudnn-cu12        8.9.4.25
nvidia-pyindex           1.0.9
```

I noticed that some of NVIDIA's pip packages are version 12.2.x, should I install them as version 12.1.x?

**Comment by glenn-jocher** [comment]
@fatinghenji it appears that you are still encountering the same issue even after making changes to your CUDA version. The error message indicates a failure during the export process, specifically related to TensorRT.

Looking at the information provided, it seems that you have CUDA version 12.1 installed on your system. However, some of the NVIDIA pip packages, such as `nvidia-cublas-cu12`, `nvidia-cuda-nvrtc-cu12`, `nvidia-cuda-runtime-cu12`, and `nvidia-cudnn-cu12`, are at version 12.2.x.

To resolve this issue, it is recommended to have consistent versions for all NVIDIA-related packages. You can either downgrade the NVIDIA pip packages to version 12.1.x or update your CUDA installation to version 12.2.x to match the package versions.

Please note that if you choose to update your CUDA installation, you will also need to ensure that all other components, such as PyTorch and torchvision, are compatible with the new CUDA version.

Once you have made the necessary changes and have consistent versions for all components, please try running the export script again.

Let me know if you need any further assistance!

**Comment by fatinghenji** [comment]
@glenn-jocher Can you tell me the version of CUDNN correspondence? I could find several other pip packages on Pypi, but CUDNN confused me.It is not named after 12.1.x.
```
nvidia-cublas-cu12       12.2.1.16
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        8.9.4.25
nvidia-pyindex           1.0.9
```
![image](https://github.com/ultralytics/yolov5/assets/37131177/09defe77-6c2f-4745-85b3-c0cca94766e7)

**Comment by glenn-jocher** [comment]
@fatinghenji the version of cuDNN that corresponds to your NVIDIA pip packages can be found by checking the cuDNN version compatibility table provided by NVIDIA. In your case, you have installed the following NVIDIA pip packages:

- `nvidia-cublas-cu12` version 12.2.1.16
- `nvidia-cuda-nvrtc-cu12` version 12.1.105
- `nvidia-cuda-runtime-cu12` version 12.1.105
- `nvidia-cudnn-cu12` version 8.9.4.25
- `nvidia-pyindex` version 1.0.9

Based on this information, the corresponding cuDNN version would be 8.9.4 for CUDA 12.1.

Please note that it is always recommended to refer to the official documentation or compatibility tables provided by NVIDIA to ensure that you have the correct version of cuDNN for your specific CUDA version.

Let me know if you have any further questions!
