### ISSUE TITLE
Model not uploading: unhandled server error

### ISSUE THREAD

**Issue by y-arrow** [ultralytics/yolov5#10705]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

I trained a model, but UL crashed when uploading it:
```

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
      99/99      73.7G   0.009337   0.004801          0        621        640: 100%|██████████| 37/37 00:31
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 3/3 00:06
                   all       1556       1860      0.867       0.76       0.82      0.387
Ultralytics: Uploading checkpoint Xr7RjMjjuMXh2Vto2x9q

24 epochs completed in 0.251 hours.
Optimizer stripped from yolov5/runs/train/exp/weights/last.pt, 14.4MB
Ultralytics: Training completed successfully ✅
Ultralytics: Uploading final Xr7RjMjjuMXh2Vto2x9q
Ultralytics: View model at https://hub.ultralytics.com/models/Xr7RjMjjuMXh2Vto2x9q 🚀
Ultralytics: Unhandled server error. Retrying 10x for 3600s. If this issue persists please visit https://github.com/ultralytics/hub/issues for assistance. (500 #4)
Results saved to yolov5/runs/train/exp

```
The contents of yolov5/runs/train/exp:

![image](https://user-images.githubusercontent.com/2550277/211115363-3575eb60-f95c-49f7-a9f1-79957ae64b3c.png)

Please advise how can I upload the model?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@y-arrow hi there! Thanks for reaching out. This seems to be a case of an unhandled server error during model uploading. Our apologies for the inconvenience. The YOLOv5 model training looks successful, and it appears the issue arises during the upload procedure.

We are continuously improving our services, and your feedback is invaluable. We'll investigate this error further to ensure a smooth user experience. As for a workaround, you can manually upload the model to your preferred destination, whether it be a cloud storage service or elsewhere.

If you encounter any further issues, feel free to visit the Ultralytics support repo (https://github.com/ultralytics/hub/issues) for assistance.

Thank you for your understanding and patience! We truly appreciate your support.
