### ISSUE TITLE
why can't i gain the segmentation by use python val.py --save-json(the results val_batch{batch_i}_pred.jpg has segmentation label)

### ISSUE THREAD

**Issue by 1246886181** [ultralytics/yolov5#10700]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

why can't i gain the segmentation by use python val.py --save-json(the results val_batch{batch_i}_pred.jpg has segmentation label)

**Comment by glenn-jocher** [comment]
@1246886181 hi there! It sounds like you're trying to obtain segmentation labels using `val.py --save-json`. This command generates bounding boxes and labels, but for segmentation, you may want to try `python val.py --img-size 640 --save-json --augment`. 

Feel free to check out the documentation at https://docs.ultralytics.com/yolov5/ for more details on utilizing segmentation features. If you have any further questions, don't hesitate to ask. Good luck with your project!
