### ISSUE TITLE
I have a question about runtime devices

### ISSUE THREAD

**Issue by zenkoton** [ultralytics/yolov5#10707]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

The concat module input tensor is displayed on the cpu when the model is checked and on the cuda when it is run. The parameter of another c3 module is exactly the opposite, which makes me very upset. The concat module I modified cannot meet the two conditions at the same time.How do I modify the concat module

**Comment by zenkoton** [comment]
I think it may be that the storage place of queue storing each feature map will change, but I have no way to deal with it well, especially the input of concat module will change from cpu to cuda. Can you give me some suggestions

**Comment by zenkoton** [comment]
When I moved the improved concat module results to cuda, the checking phase showed that the c3 module parameters were on the cpu. When I moved the parameters to the cpu, the training phase showed that the c3 module parameters were on cuda

**Comment by glenn-jocher** [comment]
@zenkoton hi there! It sounds like you're encountering an issue with moving the concat module results to CUDA while the c3 module parameters are on the CPU. This discrepancy can be a bit challenging to handle. It seems like the storage location of the feature map queue might be changing, causing the input of the concat module to switch between the CPU and CUDA.

I recommend checking the implementations and ensuring that all relevant tensors are consistently being moved to the same device throughout your code, such as using `.to(device)` or `torch.device('cuda')` to manage device placement. It might also be helpful to review the specific tensor operations and assignments in the concat and c3 modules to ensure they are handled consistently.

Feel free to refer to the Ultralytics Docs at https://docs.ultralytics.com/yolov5/ for more guidance on device management and tensor operations. Keep up the great work, and let me know if there's anything else I can assist with!
