### ISSUE TITLE
yoloV5 detects to much classes

### ISSUE THREAD

**Issue by niklashcs** [ultralytics/yolov5#10708]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hey, I trained yoloV5 on a custom dataset and everything works fine. But I just want to detect one class but when I run the detect.py file, it detects not only my custom objects but also for example "humans". I don't understand how this is even possible, because I think he should not know the old classes from the pretrained dataset anymore. 
Thank you!
Best regards,
Niklas

**Comment by glenn-jocher** [comment]
@niklashcs hi Niklas 🌟,

You can specify the classes you want to detect by adjusting the `--conf-thres`, `--iou-thres`, and `--img-size` arguments in the `detect.py` script. Additionally, make sure that in your custom YOLOv5 model's `data.yaml` file, you have correctly set the `names` parameter to include only the classes you want to detect. 

Remember to always refer to the [Ultralytics Docs](https://docs.ultralytics.com/yolov5/) for detailed guidance.
