### ISSUE TITLE
What is the total size of four 640x480 images in mosaic augmentation

### ISSUE THREAD

**Issue by foodeveloperbar17** [ultralytics/yolov5#1070]
## ❔Question
Hello. I want to know. If I have dataset with 640x480 images and i run training with --img 640, what will be the mosaic image size? 1280x1280? 1280x960? 640x640? 640x480 or something else? do the images scale up or down if they are turned off in hyperparameters, but mosaic augmentation prbability is 1?

**Comment by glenn-jocher** [comment]
@foodeveloperbar17 python train.py --img 640 will train with 640x640 mosaics. Augmentation policy including scale jitter is defined in hyperparameter yaml you specify under --hyp.

**Comment by HaolyShiit** [comment]
> @foodeveloperbar17 python train.py --img 640 will train with 640x640 mosaics. Augmentation policy including scale jitter is defined in hyperparameter yaml you specify under --hyp.

@glenn-jocher Thanks for your great work!  Do I need to resize my image to 640x640 (the original image size is 640x480) when do testing ?

**Comment by foodeveloperbar17** [comment]
@HaolyShiit No you don't need to. It can zero pad on the smaller side without you needing to resize
