### ISSUE TITLE
how to get probability for each pixel in segmentation

### ISSUE THREAD

**Issue by nanfei666** [ultralytics/yolov5#10719]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, im trying to calculate the entropy for the segmentation result, not the whole image or the object box, which means during infer, i need the probability for each pixel in the object box, but i can't find a way to get that, could you please help me, much appreciate

**Comment by glenn-jocher** [comment]
@nanfei666 hi there! To calculate the entropy for the segmentation result, you can obtain the probability for each pixel within the object box by using the 'segmentation' output. Utilize the confidence scores within the object's segmentation mask to achieve this. You can find more information on utilizing segmentation output in the YOLOv5 documentation here: https://docs.ultralytics.com/yolov5/ 

Wishing you success with your project!
