### ISSUE TITLE
How to get get single image and it's label before training? 

### ISSUE THREAD

**Issue by tejaskhare99** [ultralytics/yolov5#10715]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, 
I am trying to get a single image and it's label that is passed for training. I am aware that yolov5 creates a mosaic for training, but how can I access the single image and the corresponding label that is fed to the mosaic for training?
I might be missing something but I was looking in the class LoadImagesAndLabels(Dataset) in utils/dataloader.py script, but couldn't find it. 

Can you help me please? Thank you for your time

**Comment by glenn-jocher** [comment]
@tejaskhare99 hey there! You can easily access the single image and its corresponding label that is fed to the mosaic for training using the YOLOv5 dataset object. The images and labels are loaded and preprocessed in the `__getitem__` method of the dataset class. You can find more detailed information in the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/. Let me know if you need further assistance. Cheers!
