### ISSUE TITLE
OpenCV(4.1.1) Blob  not found in const blobs in function 'cv::dnn::dnn4_v20190621::ONNXImporter::getBlob' 

### ISSUE THREAD

**Issue by hedeya1980** [ultralytics/yolov5#10712]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to use YOLOv5 for object detection Using C++ and OpenCV's DNN. I'm using Windows 10, and VS 2019.

However, the following line of code:
```
#include <opencv2/opencv.hpp>

int main(int, char **)
{
    auto net = cv::dnn::readNet("C:/Users/hedey/source/repos/Road_Defects_Detector/yolov5s.onnx");

    return 0;
}
```

causes the following error:
```
OpenCV(4.1.1) C:\opencv-4.1.1\modules\dnn\src\onnx\onnx_importer.cpp:320: error: (-204:Requested object was not found) Blob  not found in const blobs in function 'cv::dnn::dnn4_v20190621::ONNXImporter::getBlob'

Press any key to continue . . .
```
[This is a link](https://drive.google.com/file/d/1wk6rGEX6p3E197TbtDYAp7mlB9TfhCef/view?usp=share_link) to the original .pt file that I downloaded from the Yolov5 repository, and [this is a link](https://drive.google.com/file/d/1sF8K7237WmYMRr7P6txP3ZYnbgvm_RzD/view?usp=share_link) to the .onnx file that I obtained from the .pt file as per the conversion instructions (using `!python export.py --weights YOLOv5s.pt --include onnx`).

**Comment by glenn-jocher** [comment]
@hedeya1980 hi there! It looks like you're facing an issue with using YOLOv5 in C++ with OpenCV's DNN module. The error you're encountering seems related to the blob not being found in the const blobs. It's possible that the .onnx file may not have been generated correctly during the conversion or there could be an issue with the C++ code. I'd recommend checking the generated .onnx file by opening it with a text editor and ensuring that the conversion process was successful.

Additionally, you could also try using the provided `.pt` file directly in your C++ code as the YOLOv5 models can be loaded in OpenCV using their `.pt` versions without the need for conversion.

In case you need further assistance, feel free to refer to the Ultralytics Docs at https://docs.ultralytics.com/yolov5/ for detailed usage instructions.

Cheers!
