### ISSUE TITLE
CITATION.cff

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#10717]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

@glenn-jocher 
What is the purpose of this file?

![QQ截图20230109090442](https://user-images.githubusercontent.com/41098760/211227913-a7a2ec8c-1a89-448e-8ebe-0c5891e1f638.png)

**Comment by Robotatron** [comment]
To cite the work of YOLO if you use it in your academic work

**Comment by Zengyf-CVer** [comment]
@Robotatron Thank you very much.
