### ISSUE TITLE
Inflexibility to Folder Name Changes. How to Save and Load using "state_dict(torch.load(...))" Methods. 

### ISSUE THREAD

**Issue by jitaxis** [ultralytics/yolov5#10726]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Other

### Bug

I require my "models" folder to be a different name; therefore, I run into the issue when running attempt_load() 
"models" is not found. I am using a custom model and require my GitHub repo to be private, so the torch.hub method won't work.

I have looked at other issues, to see what I can do. The links below a few of the ones I have gone through:
[https://github.com/ultralytics/yolov5/issues/6396](url)
[https://github.com/ultralytics/yolov5/issues/353](url)
[https://github.com/ultralytics/yolov5/issues/6610](url)

I assume on line [https://github.com/ultralytics/yolov5/blob/master/train.py#:~:text=torch.save(ckpt%2C%20best)](url) in train.py I need to change it to something like `torch.save(model.state_dict(), 'model.pt')`.
And something along the lines of the following to load it.
` # Load model
    model = Ensemble()
    model.load_state_dict(torch.load('/ssd/Downloads/161222-best_49e-pose.pt', map_location="cuda:0"),strict=True)
    model.to(device)
    model.eval()`

I have also tried to convert my prior trained model by reloading it, saving it and loading it with the above code and get the following results.
This loading method fails with the following:
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Ensemble:

If I run it with strict=False, I get the error:
AttributeError: 'Ensemble' object has no attribute 'stride'
I also used the 'Model' object instead of 'Ensemble'.
But this also fails with strict=True. It works with strict=False but the model performs very poorly compared to the default loading method during testing.

If anyone is able to help/shed some light on what I need to look at.

### Environment

Python 3.8.13
Ubuntu 20.04

### Minimal Reproducible Example

Change the name of the Models directory and the imports that require this module. Once done run an inference with a  local model.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@jitaxis hello! It seems like you are encountering trouble with renaming the "models" folder and saving/loading your custom model state dict. This isn't a bug, but a customization request. 

To rename the "models" folder, you'd need to update references throughout the code. Also, for custom model saving/loading, it may require modifying your model.py script. While this isn't officially supported, others have done similar customizations successfully, and I recommend browsing related discussions on our [Docs](https://docs.ultralytics.com/yolov5/) and GitHub issues for guidance.

Regarding your loading issues, using `torch.save(model.state_dict(), 'model.pt')` and `model.load_state_dict(torch.load('model.pt'))` gets my vote. Ensure strict=False if encountering attribute errors, and review model architecture compatibility. 

Finally, have you considered deriving from YOLOv5's train.py to ensure consistent performance? It could simplify model handling. 

Let us know your progress – the YOLO community and our team are here to assist you!
