### ISSUE TITLE
Error with pytorch requirement

### ISSUE THREAD

**Issue by robin-maillot** [ultralytics/yolov5#1072]
## 🐛 Bug
When trying to install locally by running `pip install -r requirements.txt` the following error can occur depending on the CUDA version installed:

```
ERROR: Could not find a version that satisfies the requirement torch>=1.6.0 (from -r requirements.txt (line 12)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch>=1.6.0 (from -r requirements.txt (line 12))
```

Running `pip install torch==1.6.0+cu101 torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html` then `pip install -r requirements.txt` (as specified by pytorch [here](https://pytorch.org/get-started/locally/)) solved this for me.
## To Reproduce (REQUIRED)
Trying to install in a fresh environment in Windows with CUDA 10.1

## Expected behavior
Update readme to remove previous CUDA versions or give info on this error.
I think this is an issue with pytorch which requires specifique commands to install depending on environment so I'm not sure there is much you can do.

It would be nice to be able to run `pip install -r requirements.txt` without having preinstalled pytorch if possible.

## Environment

 - OS: Windows
 - GPU RTX 2060
- CUDA: 10.1

**Comment by robin-maillot** [comment]
For me adding `--find-links https://download.pytorch.org/whl/torch_stable.html` to the requirements file also worked but I am not sure o the unexpected consequences...

**Comment by glenn-jocher** [comment]
@robin-maillot yes, torch installation specifics may vary depending on your OS and cuda version. For exact instructions see https://pytorch.org/get-started/locally/

**Comment by robin-maillot** [comment]
@glenn-jocher I think adding the following to the top of the requirements.txt would solve this issue and make it easier for people to install the requirements for yolov5? 
`--find-links https://download.pytorch.org/whl/torch_stable.html`

Right now the error is kind of confusing and there is nothing in the readme about pytorch installation. Maybe adding the pytorch installation link to the readme would be good for people who have never installed pytorch, I know I wasted an hour or so researching the error.

**Comment by glenn-jocher** [comment]
@robin-maillot torch installations may always need a bit of finetuning to specific scenarios. In our CI tests for example, which run on a CPU-only instance, we specify a CPU-only installation of torch:

https://github.com/ultralytics/yolov5/actions/runs/288465315/workflow#L44-L51
```yaml
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -qr requirements.txt -f https://download.pytorch.org/whl/cpu/torch_stable.html
          pip install -q onnx
          python --version
          pip --version
          pip list
```

Also if you have legacy CUDA installations those need to be specified as shown in linux install commands, i.e.
https://pytorch.org/get-started/locally/
`pip install torch==1.6.0+cu92 torchvision==0.7.0+cu92 -f https://download.pytorch.org/whl/torch_stable.html`

Windows commands will also differ, so there's really no one size fits all solution. The presented solutions are mainly directed to linux users with the latest version of cuda, which can simply use the default `pip install torch` commands.

We could consider adding this link if it was robust to installations across all operating systems (linux, macos, windows) and all hardware configurations (CUDA, CPU only). Would it be possible for you to test these cases and and then submit a PR with what you find to work best?

**Comment by robin-maillot** [comment]
@glenn-jocher I will have a look this week but can you give me a bit more information about the installation conditions:

- Do you need the user to be able to install a CPU version when running on a machine with a gpu available? Or is the CPU only needed when no GPU is available?

For me (with outdated CUDA versions due to tensorflow requirements) I did not have to run the command recommended by pytorch simply running `pip install torch -f https://download.pytorch.org/whl/torch_stable.html` worked. I have not tested this with CUDA<10.1 but I can try this weekend.

A quick fix could be just to add the pytorch link (https://pytorch.org/get-started/locally/) in the readme and warn the user that there might can be issues with previous cuda versions.
