### ISSUE TITLE
How to select the detected objects class with torch.hub?

### ISSUE THREAD

**Issue by tgrmev** [ultralytics/yolov5#10724]
### Discussed in https://github.com/ultralytics/yolov5/discussions/10654

<div type='discussions-op-text'>

<sup>Originally posted by **tgrmev** January  2, 2023</sup>
I am calling yolo yolov5m.pt model with this code. I only want to detect the people from my environment. For this aim what should I add to this line ?
`model = torch.hub.load("./yolov5", 'custom', path="./yolov5/yolov5m.pt", source='local')`

I tried with this :  `model = torch.hub.load("./yolov5", 'custom', path="./yolov5/yolov5m.pt", source='local' , classes = 0 )` and then I got **_TypeError: custom() got an unexpected keyword argument 'classes'_** error. Is it not possible to select the detected class, if we work with custom model?</div>

**Comment by aminrabinia** [comment]
See this: https://github.com/ultralytics/yolov5/issues/5257

**Comment by nkbk1431** [comment]
model = torch.hub.load("./yolov5", 'custom', path="./yolov5/yolov5m.pt").eval()
model.classes = [0]

**Comment by glenn-jocher** [comment]
@nkbk1431 you can set the classes attribute directly on the model to filter for specific object classes. For detecting people only, try assigning `model.classes = [0]` after loading the model. Let me know if you need further assistance!
