### ISSUE TITLE
Rectangular Input-sized Models Validation and Performance

### ISSUE THREAD

**Issue by sebos123** [ultralytics/yolov5#10722]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,

I was wondering if it is possible to validate tflite models of rectangular input size. When I try to do that, it always forces square inference in the val.py for non-pytorch models.
Also, would you expect a performance difference for the following case:
I have a 172x224 sized image. In the training, I use squared 224x224 images, to make use of mosaic augmentation. In the validation, I only use 192x224 images, as this is the lowest possible size, devidable by 32. 
Would it make a performance difference if I validate/inference rectangular, but train squared? As it only pads the original image, the actual image should be the same, meaning the performance of sqaured vs. rectangular should be the same, right?

**Comment by sebos123** [comment]
No updates?

**Comment by glenn-jocher** [comment]
@sebos123 hello,

Thanks for reaching out! Currently, rectangular input sizes are not supported when validating TFLite models with YOLOv5. However, as for the performance difference between training with squared images and validating with rectangular images, in theory, there should be no significant performance difference as long as the actual content of the images remains consistent.

Hope this helps! Let me know if you have any other questions.
