### ISSUE TITLE
Question about model summary printing

### ISSUE THREAD

**Issue by marziyemahmoudifar** [ultralytics/yolov5#10729]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

In which file is it defined to be printed when training the model summary?
Thank you in advance

**Comment by harshdhamecha** [comment]
Model description has been defined in `parse_model` of `yolo.py`https://github.com/ultralytics/yolov5/blob/37d1e5e5df33f4a9bef75661e5a075927b058540/models/yolo.py#L299)

**Comment by glenn-jocher** [comment]
@harshdhamecha thanks for reaching out! The model summary is printed during training in the `train.py` script. You can find the function call for printing the model summary in the `train.py` script in the `train(hyp, opt, device, tb_writer)` function. 

Let me know if you have any other questions or need further assistance!
