### ISSUE TITLE
hi where is yolov8 metrics?

### ISSUE THREAD

**Issue by lucasjinreal** [ultralytics/yolov5#10728]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hi where is yolov8 metrics?

**Comment by glenn-jocher** [comment]
@lucasjinreal hi there! YOLOv8 is an unofficial version, and its metrics may not be available through the Ultralytics YOLOv5 repository. You may want to reach out to the developer or community maintaining YOLOv8 for specific metrics. If you have any other questions about YOLOv5, feel free to ask!
