### ISSUE TITLE
Intermediate Layer output Yolov5 for each single bounding box result

### ISSUE THREAD

**Issue by thegendolz** [ultralytics/yolov5#10734]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

For a research project I am trying to compare different bounding boxes with each other. By default I can only use confidence, but this is very inaccurate. Then I thought it was a good idea to compare these by their activated neurons. If similar neurons are activated the likelihood of bounding boxes being similar is probably higher. Therefore, I require to gather intermediate layer information, preferably one before the output layer. I've searched for some possibilities but most answers are vague or have a solution that does not work for yolov5.

Therefore, I was wondering the following:
A: Does yolov5 have a separate result for each single bounding box (x amount of neurons are activated for bounding box Y, therefore this must be class Z)? Or is it a single layer output over the entire image?
B: Is it possible to retrieve these intermediate neuron results? If so, how?

To give an example I want the following output:

Bounding Box X = {"class" : "ball", "confidence":0.99, "intermediate_output": Tensor[-x, -y, -z, .......]}

**Comment by glenn-jocher** [comment]
@thegendolz hi there!

Great to hear about your research project! 🌟 Regarding your questions:
A: YOLOv5 does indeed produce separate results for each single bounding box, considering x amount of neurons activated for bounding box Y, therefore estimating the class Z.
B: You can retrieve the intermediate neuron results from the model. For further details, please refer to the docs at https://docs.ultralytics.com/yolov5/.

Best of luck with your research, and feel free to reach out if you have any more queries!
