### ISSUE TITLE
torch.hub not working for yolov5-classification custom models?

### ISSUE THREAD

**Issue by akashAD98** [ultralytics/yolov5#10732]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

i trainied my custom model , now i want to build api for my deployment , so what should I do? pytorch.hub not working ?

also suggest other way to use .pt in deployment

<img width="571" alt="image" src="https://user-images.githubusercontent.com/62583018/211540486-355bc094-474e-4c22-9c0f-ab9409e64d50.png">

**Comment by akashAD98** [comment]
https://github.com/gradio-app/gradio/issues/2978

**Comment by glenn-jocher** [comment]
@akashAD98 thanks for reaching out! It looks like you are encountering an issue while trying to use the custom YOLOv5 model with torch.hub. We recommend checking the discussion on the Gradio repository as they can provide more specific assistance with integrating YOLOv5 models into their platform. Additionally, for deploying your custom model, you can refer to the Ultralytics Docs for guidance on using .pt files in deployment. If you encounter any specific issues related to the YOLOv5 model itself, please feel free to ask here. Good luck with your deployment!
