### ISSUE TITLE
About explanation of Yolov5

### ISSUE THREAD

**Issue by jaqub-manuel** [ultralytics/yolov5#1073]
Hello Dear Glenn,

This work you've done has been really great. We have had successful results for crack detection with Yolov5 and we aim to write an article for it. Could you please share a paper to explain Yolov5's work or a paper or document that can give a general explanation? We could not find a document explaining these anywhere.
Thank you so much.

**Comment by glenn-jocher** [comment]
@jaqub-manuel hi there, I'm glad you find it useful! We are aiming to publish a short paper to arxiv towards the end of the year. In the meantime you can cite the Zenodo DOI to point to the current release:
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3983579.svg)](https://doi.org/10.5281/zenodo.3983579)

Though you probably want to use this link instead, which will always point to the latest release. You can get the reference in bibtex and other formats at this link as well:
https://doi.org/10.5281/zenodo.3908559

**Comment by jaqub-manuel** [comment]
Thanks @glenn-jocher. In fact, our work is ready, we are just waiting for yolov5's working mechanism. I wish you could publish it in less time. Or a small post to explain how yolov5 works would be great. Thanks anyway.
