### ISSUE TITLE
How to know if training was interrupted and resume if necessary

### ISSUE THREAD

**Issue by kraster010** [ultralytics/yolov5#10736]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Currently we are automating yolov5 training using ansible. We have external factors that could cause training to be interrupted. 
There is a way to check programmatically if the last training job is finished or not in order to resume it if necessary?

Thanks 

### Additional

repository version: v7.0

**Comment by Air000** [comment]
To check the training job is finished or not, you can check on the generated log file, results.csv, located on runs/train/your_prj/results.csv. The last index on `epoch` column indicates the last trained epoch. If the index equals to your epoch setting - 1, that means the training is completed.

**Comment by kraster010** [comment]
thanks

**Comment by glenn-jocher** [comment]
@kraster010 you're welcome! If you have any more questions or need further assistance, feel free to ask. Good luck with your YOLOv5 automation!
