### ISSUE TITLE
Feeding the model rectangle image (without resizing to square one)

### ISSUE THREAD

**Issue by AlonZolfi** [ultralytics/yolov5#1074]
## ❔Question
Hey,
Is it possible to feed into the model a non-square tensor? of course, I'm not referring to the detect.py, where the streams are resized to the --imgsize parameter.
for instance, I'm trying to feed a single image (represented as a tensor of shape (1,3, 720,1280)) and I'm getting the next error:
![image](https://user-images.githubusercontent.com/44315174/94844473-f627bd80-0426-11eb-8ca1-3132ed95f94d.png)
It's important that I do not resize before entering the net to a square image, and then resizing back to non-square.
Thanks!

**Comment by glenn-jocher** [comment]
@AlonZolfi input images must conform to the minimum grid multiple constraint. 

You can pass any shape image as long as the width and height are evenly divisible by the maximum grid size, which for YOLOv5 is 32 pixels.
