### ISSUE TITLE
YOLOv5 Study: Speed vs Batch-Size - By Hardware

### ISSUE THREAD

**Issue by SWillSZ** [ultralytics/yolov5#10740]
Hello, quick check in from a user of the older GTX 1060 6GB (1280 CUDA cores). I've been following Glenn's work on timing inference with image batches. I do not think that batch inference is significantly faster than regular inference on a per-image basis for those with older GPUS, especially when running larger neural networks. My uneducated guess is that the root cause of this is likely the number of CUDA cores on a particular GPU. When running a proportionally larger neural network, all cores can simultaneously be employed in the processing of a single image, and therefore batching provides minimal additional benefits.

For instance, when running inference on 640 by 480 images on a GTX 1060 6GB with YOLOv5m, no speedup is obtained

```
# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Load two identical images
for f in ['bus.jpg', 'bus.jpg']:
    torch.hub.download_url_to_file('https://ultralytics.com/images/' + f, f)  # download 2 images
img1 = cv2.imread('bus.jpg')[..., ::-1]  # OpenCV image (BGR to RGB)
img2 = cv2.imread('bus.jpg')[..., ::-1]  # OpenCV image (BGR to RGB)
imgs = [img1]  # batch of a single image
imgs_2 = [img1, img2] # batch of multiple images

# Run inference on a batch with one image, timing
start_time = datetime.datetime.now()
for i in range(0, 1000):
	results = model(imgs, size=640)
end_time = datetime.datetime.now()
elapsed_time = end_time - start_time
print("For a batch of 1 images, ran 1000 times, elapsed time is:")
print(elapsed_time)


# Run inference on a batch with two images, timing
start_time = datetime.datetime.now()
for i in range(0, 1000):
	results = model(imgs_2, size=640)
end_time = datetime.datetime.now()
elapsed_time = end_time - start_time
print("For a batch of 2 images, ran 1000 times, elapsed time is:")
print(elapsed_time)
```
Output (on a GTX 1060 - your mileage will vary)

```
For a batch of 1 images, ran 1000 times, elapsed time is:
0:00:15.943667
For a batch of 2 images, ran 1000 times, elapsed time is:
0:00:30.491301
```

@glenn-jocher - you mention that it is interesting that smaller models benefit disproprotionally from batching. My guess is that this is because your CUDA cores are saturated at a certain stage when running larger models. In particular, the A100 you used while testing has 6912 CUDA cores (about 3 times as many as a 1060 GB 6GB)

### Discussed in https://github.com/ultralytics/yolov5/discussions/6649

<div type='discussions-op-text'>

<sup>Originally posted by **glenn-jocher** February 15, 2022</sup>
Batch Size study here. Larger batches contribute to improved per-image inference speeds. Study run on Colab Pro+ with A100 40GB GPU. I used `val.py --data coco.yaml --task study`, and just updated the code a bit to run the study over batch size instead of image size.

```
YOLOv5 🚀 v6.0-255-gca0a007 torch 1.10.0+cu111 CUDA:0 (Tesla A100-SXM-40GB)
```

Google sheet with complete results.
https://docs.google.com/spreadsheets/d/1Nm3jofjdgKja0AZHV8Jk_m8TgcF7jenCSA06DuEG2C0

### Inference Time vs Batch Size
<img width="877" alt="Screenshot 2022-02-15 at 15 40 43" src="https://user-images.githubusercontent.com/26833433/154084481-a2c2d37e-abf6-4221-a139-4b9190082d30.png">

### FPS vs Batch Size
<img width="875" alt="Screenshot 2022-02-15 at 15 39 52" src="https://user-images.githubusercontent.com/26833433/154084375-1e596a27-13cd-4ef1-8369-f73d6439c861.png">

### Speed gains vs `batch-size 1`
Interesting takeaway is that smaller models benefit disproportionately from large batch sizes. These are the FPS gains vs batch-size 1 from the study:

Batch Size | YOLOv5n | YOLOv5s | YOLOv5m | YOLOv5l | YOLOv5x
-- | -- | -- | -- | -- | --
1 | 1.0 | 1.0 | 1.0 | 1.0 | 1.0
2 | 1.8 | 1.8 | 1.9 | 1.9 | 1.9
4 | 3.4 | 3.4 | 3.5 | 3.5 | 3.8
8 | 7.0 | 7.0 | 7.0 | 6.4 | 5.6
16 | 13.1 | 10.5 | 8.5 | 7.6 | 6.0
32 | 17.1 | 11.7 | 9.2 | 7.8 | 6.4
64 | 20.0 | 14.1 | 10.5 | 8.4 | 6.8
128 | 23.1 | 15.2 | 10.7 | 8.4 | 6.7

<img width="875" alt="Screenshot 2022-02-15 at 15 39 58" src="https://user-images.githubusercontent.com/26833433/154084412-b59000bb-f527-4691-8130-5a71901f4a6e.png">

</div>

**Comment by glenn-jocher** [comment]
@SWillSZ thanks for sharing your insights and testing results! Your observations are indeed very interesting and provide valuable context for users with older GPUs. It's true that the performance gains from batching can vary depending on the hardware, as you've demonstrated with the GTX 1060 6GB and YOLOv5m.

The comprehensive study you referenced in the discussion does a great job illustrating the impact of batch size on inference speed and FPS across various YOLOv5 model sizes. It's a fascinating exploration of how hardware and model architecture interact.

Thanks for contributing to the discussion and providing valuable insights for the community! If you'd like to dive deeper into optimizing performance for your specific hardware, do check out the [Ultralytics YOLOv5 documentation](https://docs.ultralytics.com/yolov5/) for more guidance.

Your contributions are greatly appreciated, and I'm sure they'll be helpful to others exploring similar performance considerations.
