### ISSUE TITLE
How to add multiple image angles in degrees hyperparameter?

### ISSUE THREAD

**Issue by dsbyprateekg** [ultralytics/yolov5#10741]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,

Can we add multiple angles in the `degrees` option of the hyperparameter configuration file?
I want to rotate images 0,90,180 and 270 degrees during the training.

Please suggest if possible then what will the format? Like `degrees:90.0` or `degrees:[0,90,180,270]`

**Comment by Robotatron** [comment]
YOLO supports albumentaiton so that you can implement every augmentation imaginable.
