### ISSUE TITLE
Barracuda support for YOLOv5

### ISSUE THREAD

**Issue by mnbrshd** [ultralytics/yolov5#10748]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am trying to load the YOLOv5s onnx model into Unity Barracuda but I am getting the following error:

OnnxImportException: Unexpected error while parsing layer /model.24/Split_output_0 of type Split.
Unsupported default attribute `split` for node /model.24/Split_output_0 of type Split. Value is required.

Json: { "input": [ "/model.24/Sigmoid_output_0", "onnx::Split_349" ], "output": [ "/model.24/Split_output_0", "/model.24/Split_output_1", "/model.24/Split_output_2" ], "name": "/model.24/Split", "opType": "Split", "attribute": [ { "name": "axis", "i": "4", "type": "INT" } ] }
  at Unity.Barracuda.ONNX.ONNXModelConverter+<>c.<UseStandardImporter>b__27_10 (Unity.Barracuda.ModelBuilder net, Unity.Barracuda.ONNX.ONNXNodeWrapper node) [0x00017] in C:\Users\Muneeb\Desktop\Shader Course\AI Verification Tool\Library\PackageCache\com.unity.barracuda@80909e3320\Barracuda\Runtime\ONNX\ONNXModelConverter.cs:389 
  at Unity.Barracuda.ONNX.ONNXModelConverter.ConvertOnnxModel (Onnx.ModelProto onnxModel) [0x00409] in C:\Users\Muneeb\Desktop\Shader Course\AI Verification Tool\Library\PackageCache\com.unity.barracuda@80909e3320\Barracuda\Runtime\ONNX\ONNXModelConverter.cs:2934 

Unity.Barracuda.ONNX.ONNXModelConverter.Err (Unity.Barracuda.Model model, System.String layerName, System.String message, System.String extendedMessage, System.String debugMessage) (at Library/PackageCache/com.unity.barracuda@80909e3320/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:3434)
Unity.Barracuda.ONNX.ONNXModelConverter.ConvertOnnxModel (Onnx.ModelProto onnxModel) (at Library/PackageCache/com.unity.barracuda@80909e3320/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:2943)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (Google.Protobuf.CodedInputStream inputStream) (at Library/PackageCache/com.unity.barracuda@80909e3320/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:170)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (System.String filePath) (at Library/PackageCache/com.unity.barracuda@80909e3320/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:98)
Unity.Barracuda.ONNXModelImporter.OnImportAsset (UnityEditor.AssetImporters.AssetImportContext ctx) (at Library/PackageCache/com.unity.barracuda@80909e3320/Barracuda/Editor/ONNXModelImporter.cs:65)
UnityEditor.AssetImporters.ScriptedImporter.GenerateAssetData (UnityEditor.AssetImporters.AssetImportContext ctx) (at <11d97693183d4a6bb35c29ae7882c66b>:0)
UnityEditor.AssetImporters.AssetImporterEditor:OnDisable()

I thought of modifying the onnx model but I cannot dig deeper into the model. Can anyone help me on how to make this model run with Barracuda?

**Comment by mnbrshd** [comment]
This issue got resolved after exporting the onnx model with opset_version 9

**Comment by glenn-jocher** [comment]
@mnbrshd great to hear that you were able to resolve the issue by exporting the ONNX model with opset_version 9! Wishing you smooth sailing with YOLOv5 and Unity Barracuda 🚀. If you have any further questions or need assistance, feel free to reach out.

**Comment by AbderrazakBenarous** [comment]
can you please tell how did you convert the yolov5 model to onnx with opsetversion 9 , the functions used , i am relly stuck in it . thank you

**Comment by glenn-jocher** [comment]
@AbderrazakBenarous to export the YOLOv5 model to ONNX with opset_version 9, you can use the `export.py` script provided in the YOLOv5 repository. Here's a concise guide on how to do it:

1. Navigate to your local YOLOv5 repository directory.
2. Run the `export.py` script with the `--opset-version` flag set to 9.

Here's an example command:

```bash
python export.py --weights yolov5s.pt --img 640 --batch 1 --device 0 --opset-version 9
```

This command will export the `yolov5s.pt` model to ONNX format with opset_version 9, assuming an input image size of 640 and a batch size of 1. Adjust the `--weights` argument to point to your specific YOLOv5 weights file.

Make sure you have the necessary dependencies installed, and you are using a compatible version of PyTorch that supports exporting to the desired ONNX opset version.

If you encounter any issues or have further questions, please check the documentation or open an issue in the YOLOv5 repository. Good luck! 🌟
