### ISSUE TITLE
Segmentation model 1280 size version

### ISSUE THREAD

**Issue by NicholasIrving** [ultralytics/yolov5#10755]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Now, the Segmentation pre-trained models are size 640. Are there any models like v5n6 for the segmentation version?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Robotatron** [comment]
+1 would like to know as well

**Comment by Robotatron** [comment]
bump

**Comment by Robotatron** [comment]
@AyushExel could you help? Any ETA for the 1280 segm model?

**Comment by AyushExel** [comment]
No not yet. We need to tune some hyps which takes a lot of time for p6 models. We intend to release something with 8.1
