### ISSUE TITLE
Region of interest ROI

### ISSUE THREAD

**Issue by Mansurjons** [ultralytics/yolov5#10761]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi There!!!

Know I learn yolov5 and using it That's good now but I need to add ROI

I don't know how to start 

could you tell me where do I begin

Thanks

**Comment by Mekcyed** [comment]
Maybe have a look here https://stackoverflow.com/questions/68841724/how-to-do-detections-in-yolov5-only-in-a-region-of-interest

**Comment by glenn-jocher** [comment]
@Mekcyed hi there!

Thanks for reaching out! Utilizing a region of interest (ROI) with YOLOv5 is a popular requirement. Check out the "Detect in your own COCO-format dataset" tutorial on our documentation at https://docs.ultralytics.com/yolov5/. It includes examples of specifying custom region coordinates.

Let me know if you need any further assistance!

**Comment by Mekcyed** [comment]
Hey @glenn-jocher, I think you pinged the wrong username :D
