### ISSUE TITLE
Deleted Label is counted as empty

### ISSUE THREAD

**Issue by Rollson** [ultralytics/yolov5#1076]
## ❔Question
Thanks for your nice work. I did a clone of the repo to train my custom data. When I run train.py, I realised that a missing label file was counted as empty  in the console output >> Scanning labels ../custom/labels/train.cache(...)

I decided to clone the repo and run python train.py to ensure the folder setup is exactly as expected and I also noticed the same issue

output before deleting label file
Scanning labels ../coco128/labels/train2017.cache (126 found, 0 missing, 2 empty, 0 duplicate, for 128 images): 128it [00:00, 15832.70it/s]
Scanning labels ../coco128/labels/train2017.cache (126 found, 0 missing, 2 empty, 0 duplicate, for 128 images): 128it [00:00, 5065.73it/s]

output after deleting 2 label files: 
Scanning labels ../coco128/labels/train2017.cache (124 found, 0 missing, 4 empty, 0 duplicate, for 128 images): 128it [00:00, 15494.56it/s]
Scanning labels ../coco128/labels/train2017.cache (124 found, 0 missing, 4 empty, 0 duplicate, for 128 images): 128it [00:00, 5979.72it/s]

As you can see the deleted label file is counted as empty and not as missing. Is it supposed to work this way? Thanks for your respose

**Comment by glenn-jocher** [comment]
@Rollson this is normal. On the first use of a dataset YOLOv5 will cache all labels into a single file for faster access in the future. The labels will show as missing the first time, but will be shown as empty for any subsequent trainings which read the labels.cache rather than the label text files directly.

**Comment by Rollson** [comment]
@glenn-jocher thank you for the explanation
