### ISSUE TITLE
Bounding box customisation

### ISSUE THREAD

**Issue by Mansurjons** [ultralytics/yolov5#10765]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

need do add 1 cm width and height for bounding box when it cropping or detecting

### Additional

<img width="612" alt="Screenshot 2023-01-14 at 11 49 26" src="https://user-images.githubusercontent.com/102349512/212460065-4b54be6c-fa01-4832-a3d8-2d869af6e053.png">
![IMG_9113](https://user-images.githubusercontent.com/102349512/212460131-48e7b56e-a394-4ee4-bce7-519f38b6117a.jpg)

**Comment by Mansurjons** [comment]
![IMG_9113](https://user-images.githubusercontent.com/102349512/212460190-0aa10345-f55a-4c01-b3ec-71bfc09265cc.jpg)

**Comment by Mansurjons** [comment]
need to be like these

**Comment by Rm1n90** [comment]
Just add padding as much as you want on the corrdinates of bbox!!!

**Comment by glenn-jocher** [comment]
@Rm1n90 you can easily customize the bounding box dimensions by adding padding to the coordinates of the bounding box. Check out our [YOLOv5 documentation](https://docs.ultralytics.com/yolov5/) for more details.
