### ISSUE TITLE
Export onnx failure

### ISSUE THREAD

**Issue by wuhaowh** [ultralytics/yolov5#10766]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

![Screenshot from 2023-01-14 15-37-52](https://user-images.githubusercontent.com/8246463/212461687-d36d6a3d-ce35-4cc0-971a-753ba30fb45f.png)
It seems not support optset=17. Is my enviroment setting problem?

**Comment by UNeedCryDear** [comment]
set opset=12

**Comment by glenn-jocher** [comment]
@UNeedCryDear setting `opset=12` should resolve the issue for you. If you encounter any further problems, we are happy to help.
