### ISSUE TITLE
yolo segmentation

### ISSUE THREAD

**Issue by mahilaMoghadami** [ultralytics/yolov5#10762]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to validate my segmentation model on detection dataset (with only bbox annotations and no segmentation annotations) 
how I can do this?

**Comment by glenn-jocher** [comment]
@mahilaMoghadami hey there! To validate your segmentation model on a detection dataset without segmentation annotations, you can convert the bbox annotations into segmentation masks using the `YOLOv5 detect` command with the `--save-txt` option. Once you have the bounding box annotations, you can convert them into segmentation masks using the `ultralytics/yolov5` repo. Check out the "Testing" section in our [Ultralytics Docs](https://docs.ultralytics.com/yolov5/) for more detailed instructions. Good luck with your validation!
