### ISSUE TITLE
Is it possible to add distance to the labels?

### ISSUE THREAD

**Issue by assafkeller** [ultralytics/yolov5#10763]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have kitti dataset and labels.
I want to add distance info so my labels will look like that class [1] bbox[4] distance[1]
e.g 3 0.622 0.609 0.080 0.446 8.41

in yolov3 the architecture can be modified. 
is it possible to adjust the architecture of yolov5 so I can add distance to the training?

Thanks

**Comment by glenn-jocher** [comment]
@assafkeller hi there!

Yes, it's possible to add additional parameters to the labels in YOLOv5. You can modify the dataset labels to include distance information in the format you mentioned. 

To do this, you can customize the data loading and handling in your dataset preparation code, and adjust the model's input to accept the additional distance information.

If you need more detailed help on this, please refer to the YOLOv5 documentation here: https://docs.ultralytics.com/yolov5/

Feel free to reach out with any further questions or if you need assistance with the implementation!

Best regards
