### ISSUE TITLE
How can I use Multi-camera, Object Tracking

### ISSUE THREAD

**Issue by eldirh9194** [ultralytics/yolov5#10771]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I just practice object tracking by using Yolov5. It works so well, but I have one problem.
Then how can I use multi-camera? I want to make a program by using multi-camera(about 4).
Now I can use only 1 camera, and if I add another one, it doesn't work.
What should I modify or add in the code? Or what should I do?

**Comment by santiram** [comment]
Hi @eldirh9194  you can use the deepsort or strong sort in with the yolo detections images and make sure you make only one object and pass all cameras detected bounding boxes to the same object .
