### ISSUE TITLE
Diagram for YOLO Instance Segmentation

### ISSUE THREAD

**Issue by sarmientoj24** [ultralytics/yolov5#10777]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is there a diagram for how architecture of Instance Segmentation?

**Comment by glenn-jocher** [comment]
@sarmientoj24 hi there!

We currently don't have a specific diagram for the instance segmentation architecture in YOLOv5, but you can find detailed explanations and visual representations of the detector architecture and training procedures in the Ultralytics documentation at https://docs.ultralytics.com/yolov5/. If you have any other questions or need further assistance, feel free to ask!

Best regards
