### ISSUE TITLE
having trouble converting model into tflite

### ISSUE THREAD

**Issue by Raymon360** [ultralytics/yolov5#10774]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

When I want to export my model from pytorch to tflite I have this problem. I think I should add the bifpn method to the tf file as well as the common file in the models folder. But I don't understand how to change the code into the tensorflow version. 
Anyone can help me solve this problem? @glenn-jocher
![image](https://user-images.githubusercontent.com/77184835/212524088-bc118e83-3237-40cf-8c06-47bfd6162bd6.png)
![image](https://user-images.githubusercontent.com/77184835/212524111-ae5cbd3d-4ff6-4476-a116-408753a68544.png)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Raymon360 hi there! Thanks for reaching out. To export a YOLOv5 model from PyTorch to TFLite, you can use the `export.py` script in the YOLOv5 repository. This script includes an option to export the model to TFLite format. You'll find detailed instructions in the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/. Let me know if you run into any further issues! 😊
