### ISSUE TITLE
val.py shows different mAP then Tensorboard during training

### ISSUE THREAD

**Issue by Robotatron** [ultralytics/yolov5#10776]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

During training, Tensorboard shows mAP50-95 of 0.76 (and 0.557 for mAP@50)
![image](https://user-images.githubusercontent.com/95919873/212678038-b4e36ae9-8ea0-42c1-87fb-3d2d4c168c77.png)

I then use `segment/val.py` with the weights (best.pt) of the same run  with the same dataset (same val dataset defined in data yaml) and get a much worse mAP (0.73 and 0.47 instead of 0.76 and 0.557)
![image](https://user-images.githubusercontent.com/95919873/212678120-927c8e33-26b0-4bbc-ad79-14fd14f538f9.png)

What is going on?

**Comment by FreemanTang** [comment]
@Robotatron Excuse me,have you found the cause of this problem?

**Comment by glenn-jocher** [comment]
Hello @FreemanTang, it looks like there hasn't been any further activity on this issue in a while. If you're still experiencing the problem, please provide us with some additional information such as the versions of YOLOv5 and PyTorch you're using, relevant code snippets, and any error messages you may be receiving. This will help us better understand the issue and provide you with a more accurate solution. Thank you!
