### ISSUE TITLE
YOLOv5 on testing to new dataset labelling wrong and prediction correct.

### ISSUE THREAD

**Issue by EngrNaeemRaza** [ultralytics/yolov5#10780]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am testing YOLOv5 on new dataset. Its working corrects on test.py. but labelling the objects in images wrong and predicting the objects correctly. Hence, All the performance matrices results are very low.

**Comment by EngrNaeemRaza** [comment]
here are example images after running test.py
![test_batch0_labels (1)](https://user-images.githubusercontent.com/58253235/212826279-1eb3904b-30ce-43f2-a42a-1ff4e2ba0917.jpg)
![test_batch0_pred (1)](https://user-images.githubusercontent.com/58253235/212826305-53fa510e-c951-45c1-ac0c-66cba696a728.jpg)

**Comment by glenn-jocher** [comment]
@EngrNaeemRaza thanks for reaching out! It looks like the object labeling in the images is not aligning with the predictions. As the test.py results show correct predictions, the issue might be related to the labeling process of your dataset. Double-check the labels to ensure they match the objects in the images. Also, verify that the dataset is formatted correctly for YOLOv5. For further guidance, refer to the YOLOv5 documentation which covers dataset preparation and labeling. Let me know if you need further assistance!
