### ISSUE TITLE
detect.py `--half` flag not working for `TritonRemoteModel`

### ISSUE THREAD

**Issue by fabito** [ultralytics/yolov5#10786]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

I deployed a Yolov5 model exported with `--half` (fp16) into Triton Inference Server  - therefore it expects FP16 inputs.
I am trying to use `detect.py`'s  `TritonRemoteModel` model type by passing the Triton server uri via `--weights` and `--half` for fp16 conversion:

```bash
python detect.py \ 
 --weights grpc://localhost:8001 \
 --source /workspace/yolov5/samples/ \
 --project /workspace/yolov5/output \
 --half
```
The following is raised by the `tritonclient` module:

```
detect: weights=['grpc://localhost:8001'], source=/workspace/yolov5/samples/, data=data/coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=/workspace/yolov5/output, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=True, dnn=False, vid_stride=1
YOLOv5 🚀 v7.0-4-g7398d2d Python-3.8.13 torch-1.13.0a0+d0d6b1f CUDA:0 (Quadro RTX 5000, 16125MiB)

Using grpc://localhost:8001 as Triton Inference Server...
Traceback (most recent call last):
  File "detect.py", line 259, in <module>
    main(opt)
  File "detect.py", line 254, in main
    run(**vars(opt))
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 126, in run
    pred = model(im, augment=augment, visualize=visualize)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/src/app/models/common.py", line 558, in forward
    y = self.model(im)
  File "/usr/src/app/utils/triton.py", line 60, in __call__
    inputs = self._create_inputs(*args, **kwargs)
  File "/usr/src/app/utils/triton.py", line 80, in _create_inputs
    input.set_data_from_numpy(value.cpu().numpy())
  File "/opt/conda/lib/python3.8/site-packages/tritonclient/grpc/__init__.py", line 1821, in set_data_from_numpy
    raise_error(
  File "/opt/conda/lib/python3.8/site-packages/tritonclient/utils/__init__.py", line 35, in raise_error
    raise InferenceServerException(msg=msg) from None
tritonclient.utils.InferenceServerException: got unexpected datatype FP32 from numpy array, expected FP16
```

### Environment

YOLOv5 🚀 v7.0-4-g7398d2d Python-3.8.13 torch-1.13.0a0+d0d6b1f CUDA:0 (Quadro RTX 5000, 16125MiB)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@fabito hi there! Thanks for reaching out and providing all the detailed information. The `--half` flag currently does not work with TritonRemoteModel as expected. This is a limitation of the current implementation and we appreciate your patience as we work to address this in a future release.

For the time being, you may consider converting your inputs to FP16 manually before passing them to the Triton Inference Server. You can refer to the Ultralytics Docs for more information on manual conversion.

We appreciate your willingness to submit a PR! Your contributions are valuable to the YOLOv5 community and the Ultralytics team. If you have any further questions or need assistance with anything else, feel free to ask.
