### ISSUE TITLE
Tflite export on Yolov5 Clsasifiaction

### ISSUE THREAD

**Issue by Mayuresh999** [ultralytics/yolov5#10792]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When will export of tflite be available for yolov5 classification? @glenn-jocher @AyushExel

**Comment by glenn-jocher** [comment]
@Mayuresh999 hi there! Thanks for reaching out. Currently, YOLOv5 does not support tflite export for classification tasks. However, the development of this feature is constantly ongoing, so stay tuned for future updates. If you have any other questions or need further assistance, feel free to ask!
