### ISSUE TITLE
Persistent Ram Catching During Evolve

### ISSUE THREAD

**Issue by awetzel-lionpower** [ultralytics/yolov5#10796]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

When running evolve on a model, currently Yolov5 caches the data in between every cycle. It seems like the data should be needed to be cached once during an entire evolution training.

### Use case

This would be used to speed up evolution times.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@awetzel-lionpower hi there! Thanks for sharing your feedback on the evolution training process. Caching data once for the entire evolution does sound like a great idea to speed up the process. I'll take note of this and discuss it with the team. If you have any other suggestions or questions, feel free to share. Your input is valuable to the YOLO community!
