### ISSUE TITLE
Evaluate full-integer-quantized model

### ISSUE THREAD

**Issue by emi-wada** [ultralytics/yolov5#10799]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,
I have created an [integer only quantized ](https://www.tensorflow.org/lite/performance/post_training_integer_quant#convert_using_integer-only_quantization)model of tflite in [export.py](https://github.com/ultralytics/yolov5/blob/master/export.py).
I used [val.py](https://github.com/ultralytics/yolov5/blob/master/val.py) to evaluate the accuracy of the model, but I get the following error:
`ValueError: Cannot set tensor: Got value of type FLOAT32 but expected type INT8 for input 0, name: serving_default_input_1:0`

This means that the input type of the image must be int8. How can I cast the input type of the data?

**Comment by glenn-jocher** [comment]
@emi-wada hi there,

Great to hear that you've created an integer-only quantized TFLite model! To cast the input type of the data to int8, you can use the `img_float32_to_uint8` function in [this section of the documentation](https://docs.ultralytics.com/yolov5/quantization/#int8-inference). It provides details on processing input images to int8 format for inference.

Hope this helps! Let us know if you have any other questions.
