### ISSUE TITLE
Convert YOLO segmentation to original unnormalized points

### ISSUE THREAD

**Issue by sarmientoj24** [ultralytics/yolov5#10794]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

YOLO segmentation vertices have normalized coordinates from model results. Is there a way to convert it to original pixel coordinates.

**Comment by ryouchinsa** [comment]
The x values are normalized by the image width and the y values are normalized by image height.
If you need the x in the range [0, width] and the y in the range [0, height].
```
x1 = x1 * width
y1 = y1 * height
```

**Comment by glenn-jocher** [comment]
@ryouchinsa thanks for the tip! To convert the YOLO segmentation vertices from normalized coordinates to original pixel coordinates, you can simply multiply the x values by the image width and the y values by the image height. For example, x1 = x1 * width and y1 = y1 * height. This will give you the x in the range [0, width] and the y in the range [0, height]. 
If you need further assistance, feel free to visit the [Ultralytics YOLOv5 documentation](https://docs.ultralytics.com/yolov5/).
