### ISSUE TITLE
have you trained on the imagenet vid dataset？

### ISSUE THREAD

**Issue by xiaowk5516** [ultralytics/yolov5#10806]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am curious about the performace of yolov5 in imagenet vid dataset(datasets for video object detection). Have you trained on this dataset?

**Comment by glenn-jocher** [comment]
@xiaowk5516 thanks for reaching out! YOLOv5 doesn't natively support the ImageNet VID dataset, but many users have trained it successfully on custom datasets similar to VID. Community contributions have enabled widespread testing on various datasets, and our docs contain comprehensive instructions for custom training. Let me know if you need help with anything else!
