### ISSUE TITLE
Multiple predictions for one box

### ISSUE THREAD

**Issue by Evgl1** [ultralytics/yolov5#10808]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Can you please tell me how to get several predictions for one box? model.multi_label = True doesn't work

**Comment by glenn-jocher** [comment]
@Evgl1 hi there! To get multiple predictions for a single box, you can enable `model.multi_label` in the YOLOv5 model config. This should allow for multiple labels to be predicted for a single box. If you're still encountering issues with this, please double-check that you've enabled this parameter correctly in the config. Let me know if you need further assistance!
