### ISSUE TITLE
yolov5 image /label corrupt pair

### ISSUE THREAD

**Issue by sivaji123256** [ultralytics/yolov5#10807]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello @glenn-jocher ,
I was trying to train yolov5 instance segmentation model on our custom data .I  have converted the labels into the required format as follows:

0 0.2598958333333333 0.21944444444444444 0.26875 0.21944444444444444 0.26875 0.22037037037037038 0.26979166666666665 0.22037037037037038 0.26979166666666665 0.2212962962962963 0.275 0.2222222222222222 0.275 0.22314814814814815 0.2765625 0.22314814814814815 0.2765625 0.22407407407407406 0.27760416666666665 0.22407407407407406 0.27760416666666665 0.225 0.2796875 0.225 0.28020833333333334 0.22685185185185186 0.28229166666666666 0.22685185185185186 0.28229166666666666 0.22777777777777777 0.28489583333333335 0.22777777777777777 0.28489583333333335 0.22870370370370371 0.2942708333333333 0.22870370370370371 0.2942708333333333 0.22962962962962963 0.2953125 0.22962962962962963 0.2953125 0.23055555555555557 0.29739583333333336 0.23055555555555557 0.29791666666666666 0.2324074074074074 0.30104166666666665 0.23333333333333334 0.30104166666666665 0.23425925925925925 0.3020833333333333 0.23425925925925925 0.303125 0.23703703703703705 0.30520833333333336 0.23796296296296296 0.30520833333333336 0.2388888888888889 0.3078125 0.24259259259259258 0.3078125 0.24444444444444444 0.3098958333333333 0.24444444444444444 0.3098958333333333 0.24537037037037038 0.3109375 0.24537037037037038 0.3109375 0.2462962962962963 0.3125 0.2462962962962963 0.3125 0.24722222222222223 0.3145833333333333 0.24814814814814815 0.3145833333333333 0.2490740740740741 0.3151041666666667 0.2490740740740741 0.31614583333333335 0.2518518518518518 0.3171875 0.2518518518518518 0.3171875 0.25277777777777777 0.31875 0.2518518518518518 0.31927083333333334 0.25 0.3203125 0.25 0.32083333333333336 0.24814814814814815 0.3223958333333333 0.24814814814814815 0.3223958333333333 0.24722222222222223 0.3255208333333333 0.24537037037037038 0.3255208333333333 0.2462962962962963 0.3265625 0.24722222222222223 0.3265625 0.2490740740740741 0.32708333333333334 0.2490740740740741 0.32760416666666664 0.2574074074074074 0.32708333333333334 0.2574074074074074 0.32708333333333334 0.25925925925925924 0.3260416666666667 0.2601851851851852 0.3260416666666667 0.262037037037037 0.3255208333333333 0.262037037037037 0.3255208333333333 0.2638888888888889 0.325 0.2638888888888889 0.325 0.2657407407407407 0.32395833333333335 0.26666666666666666 0.3234375 0.26944444444444443 0.32395833333333335 0.26944444444444443 0.32447916666666665 0.2722222222222222 0.32916666666666666 0.2796296296296296 0.32916666666666666 0.2814814814814815 0.3296875 0.2814814814814815 0.3307291666666667 0.28425925925925927 0.3328125 0.2851851851851852 0.3328125 0.2861111111111111 0.3338541666666667 0.28703703703703703 0.3338541666666667 0.28888888888888886 0.3359375 0.2898148148148148 0.3359375 0.29074074074074074 0.3390625 0.2953703703703704 0.3390625 0.29814814814814816 0.33958333333333335 0.29814814814814816 0.33958333333333335 0.30462962962962964 0.3390625 0.30462962962962964 0.3390625 0.30833333333333335 0.3385416666666667 0.30833333333333335 0.3385416666666667 0.30925925925925923 0.3375 0.30925925925925923 0.3375 0.3101851851851852 0.33645833333333336 0.3101851851851852 0.33645833333333336 0.3111111111111111 0.3328125 0.3101851851851852 0.3328125 0.30833333333333335 0.3307291666666667 0.30833333333333335 0.3307291666666667 0.30925925925925923 0.33177083333333335 0.30925925925925923 0.33177083333333335 0.3101851851851852 0.3328125 0.3101851851851852 0.3328125 0.3111111111111111 0.334375 0.3111111111111111 0.334375 0.31203703703703706 0.33541666666666664 0.31203703703703706 0.33541666666666664 0.31296296296296294 0.33697916666666666 0.31296296296296294 0.3375 0.3148148148148148 0.3385416666666667 0.3148148148148148 0.3390625 0.31666666666666665 0.34010416666666665 0.31666666666666665 0.34010416666666665 0.31851851851851853 0.3359375 0.3194444444444444 0.33541666666666664 0.3212962962962963 0.3375 0.32222222222222224 0.3380208333333333 0.325 0.33541666666666664 0.325 0.33541666666666664 0.32407407407407407 0.32916666666666666 0.32407407407407407 0.32916666666666666 0.32314814814814813 0.32760416666666664 0.32314814814814813 0.32760416666666664 0.32222222222222224 0.3260416666666667 0.3212962962962963 0.325 0.31851851851851853 0.3223958333333333 0.3175925925925926 0.3223958333333333 0.31666666666666665 0.3203125 0.31666666666666665 0.3203125 0.31574074074074077 0.3177083333333333 0.3148148148148148 0.3177083333333333 0.3138888888888889 0.31666666666666665 0.3138888888888889 0.31666666666666665 0.31296296296296294 0.315625 0.31296296296296294 0.315625 0.31203703703703706 0.3145833333333333 0.31296296296296294 0.3140625 0.31666666666666665 0.31302083333333336 0.31666666666666665 0.3125 0.31851851851851853 0.3109375 0.31851851851851853 0.3109375 0.3194444444444444 0.3072916666666667 0.31851851851851853 0.3072916666666667 0.3175925925925926 0.30625 0.3175925925925926 0.30625 0.31666666666666665 0.3026041666666667 0.31666666666666665 0.303125 0.3148148148148148 0.30416666666666664 0.3148148148148148 0.30416666666666664 0.30925925925925923 0.30104166666666665 0.30925925925925923 0.30104166666666665 0.30833333333333335 0.2989583333333333 0.30833333333333335 0.2989583333333333 0.3074074074074074 0.29791666666666666 0.3074074074074074 0.29791666666666666 0.30648148148148147 0.2947916666666667 0.3055555555555556 0.2947916666666667 0.30462962962962964 0.29375 0.30462962962962964 0.29375 0.3037037037037037 0.2916666666666667 0.3037037037037037 0.2916666666666667 0.30277777777777776 0.28854166666666664 0.30092592592592593 0.28802083333333334 0.29907407407407405 0.2869791666666667 0.29907407407407405 0.2859375 0.2962962962962963 0.28489583333333335 0.2962962962962963 0.2838541666666667 0.29259259259259257 0.28072916666666664 0.29259259259259257 0.28072916666666664 0.2935185185185185 0.27760416666666665 0.29444444444444445 0.27760416666666665 0.2953703703703704 0.2765625 0.2953703703703704 0.2765625 0.2962962962962963 0.27395833333333336 0.2962962962962963 0.27395833333333336 0.2972222222222222 0.2713541666666667 0.2972222222222222 0.2713541666666667 0.29814814814814816 0.26875 0.29814814814814816 0.26875 0.29907407407407405 0.2640625 0.29907407407407405 0.2640625 0.3 0.25416666666666665 0.29907407407407405 0.25416666666666665 0.29814814814814816 0.24635416666666668 0.2972222222222222 0.24635416666666668 0.2962962962962963 0.2453125 0.2962962962962963 0.2453125 0.2953703703703704 0.24375 0.2953703703703704 0.24375 0.3 0.24322916666666666 0.3 0.24322916666666666 0.30185185185185187 0.24270833333333333 0.30185185185185187 0.24270833333333333 0.31296296296296294 0.24322916666666666 0.31296296296296294 0.24375 0.31666666666666665 0.24479166666666666 0.3175925925925926 0.24479166666666666 0.3194444444444444 0.2453125 0.3194444444444444 0.24583333333333332 0.3212962962962963 0.246875 0.3212962962962963 0.246875 0.32222222222222224 0.24791666666666667 0.32222222222222224 0.24791666666666667 0.32314814814814813 0.24895833333333334 0.32314814814814813 0.24895833333333334 0.32407407407407407 0.25 0.32407407407407407 0.25 0.325 0.25104166666666666 0.325 0.25104166666666666 0.32592592592592595 0.2520833333333333 0.32592592592592595 0.2526041666666667 0.3277777777777778 0.25416666666666665 0.3287037037037037 0.2546875 0.33425925925925926 0.2552083333333333 0.33425925925925926 0.2552083333333333 0.3416666666666667 0.2557291666666667 0.3416666666666667 0.2557291666666667 0.3435185185185185 0.25625 0.3435185185185185 0.25625 0.3453703703703704 0.25677083333333334 0.3453703703703704 0.25677083333333334 0.34814814814814815 0.25625 0.34814814814814815 0.25625 0.3490740740740741 0.2546875 0.34814814814814815 0.25416666666666665 0.34629629629629627 0.253125 0.34629629629629627 0.2526041666666667 0.34444444444444444 0.2515625 0.34444444444444444 0.25104166666666666 0.3425925925925926 0.25 0.3425925925925926 0.24947916666666667 0.34074074074074073 0.2484375 0.34074074074074073 0.24791666666666667 0.3388888888888889 0.246875 0.3388888888888889 0.24583333333333332 0.33611111111111114 0.24479166666666666 0.33611111111111114 0.24427083333333333 0.33425925925925926 0.24322916666666666 0.33425925925925926 0.24270833333333333 0.33240740740740743 0.24166666666666667 0.33240740740740743 0.24166666666666667 0.3314814814814815 0.24010416666666667 0.33055555555555555 0.23958333333333334 0.3287037037037037 0.23854166666666668 0.3287037037037037 0.23854166666666668 0.3277777777777778 0.2375 0.3277777777777778 0.2375 0.32685185185185184 0.234375 0.325 0.23385416666666667 0.32314814814814813 0.2328125 0.32314814814814813 0.23229166666666667 0.34074074074074073 0.23072916666666668 0.3425925925925926 0.23072916666666668 0.34629629629629627 0.23020833333333332 0.34629629629629627 0.23020833333333332 0.34814814814814815 0.2296875 0.34814814814814815 0.2296875 0.35 0.22916666666666666 0.35 0.22916666666666666 0.3527777777777778 0.22760416666666666 0.3527777777777778 0.22760416666666666 0.35185185185185186 0.22552083333333334 0.3490740740740741 0.22552083333333334 0.3398148148148148 0.225 0.3398148148148148 0.225 0.325 0.22552083333333334 0.325 0.22552083333333334 0.3194444444444444 0.225 0.3194444444444444 0.22447916666666667 0.30648148148148147 0.22395833333333334 0.30648148148148147 0.22395833333333334 0.30462962962962964 0.2234375 0.30462962962962964 0.2234375 0.30185185185185187 0.22291666666666668 0.30185185185185187 0.221875 0.29907407407407405 0.22083333333333333 0.29907407407407405 0.22083333333333333 0.29814814814814816 0.21770833333333334 0.2935185185185185 0.21770833333333334 0.2916666666666667 0.2171875 0.2916666666666667 0.2171875 0.2898148148148148 0.21666666666666667 0.2898148148148148 0.21666666666666667 0.287962962962963 0.21614583333333334 0.287962962962963 0.21614583333333334 0.2861111111111111 0.215625 0.2861111111111111 0.215625 0.28425925925925927 0.21510416666666668 0.28425925925925927 0.21510416666666668 0.27037037037037037 0.215625 0.27037037037037037 0.215625 0.2657407407407407 0.2125 0.26666666666666666 0.21197916666666666 0.2638888888888889 0.2125 0.2638888888888889 0.2125 0.262037037037037 0.21458333333333332 0.25925925925925924 0.21458333333333332 0.2574074074074074 0.215625 0.2574074074074074 0.21614583333333334 0.25555555555555554 0.2171875 0.25555555555555554 0.21770833333333334 0.2537037037037037 0.21875 0.2537037037037037 0.21979166666666666 0.25092592592592594 0.22083333333333333 0.25092592592592594 0.22135416666666666 0.2490740740740741 0.22239583333333332 0.2490740740740741 0.228125 0.23796296296296296 0.22916666666666666 0.23796296296296296 0.22916666666666666 0.23703703703703705 0.23020833333333332 0.23703703703703705 0.23020833333333332 0.2361111111111111 0.23177083333333334 0.2361111111111111 0.23177083333333334 0.2351851851851852 0.2328125 0.2351851851851852 0.2328125 0.23425925925925925 0.23385416666666667 0.23425925925925925 0.23385416666666667 0.23333333333333334 0.23541666666666666 0.23333333333333334 0.23541666666666666 0.2324074074074074 0.23645833333333333 0.2324074074074074 0.23645833333333333 0.23148148148148148 0.2375 0.23148148148148148 0.2375 0.23055555555555557 0.23854166666666668 0.23055555555555557 0.23854166666666668 0.22962962962962963 0.23958333333333334 0.22962962962962963 0.23958333333333334 0.22870370370370371 0.240625 0.22870370370370371 0.240625 0.22777777777777777 0.24166666666666667 0.22777777777777777 0.24166666666666667 0.22685185185185186 0.24322916666666666 0.22685185185185186 0.24322916666666666 0.22592592592592592 0.24739583333333334 0.225 0.24739583333333334 0.22407407407407406 0.25104166666666666 0.22314814814814815 0.25104166666666666 0.2222222222222222 0.25833333333333336 0.2212962962962963 0.25833333333333336 0.22037037037037038 0.2598958333333333 0.22037037037037038 
0 0.6953125 0.1824074074074074 0.7052083333333333 0.1824074074074074 0.7052083333333333 0.18333333333333332 0.709375 0.18333333333333332 0.709375 0.18425925925925926 0.715625 0.18518518518518517 0.715625 0.18611111111111112 0.7177083333333333 0.18611111111111112 0.7177083333333333 0.18703703703703703 0.7213541666666666 0.18796296296296297 0.7213541666666666 0.18888888888888888 0.7229166666666667 0.18888888888888888 0.7229166666666667 0.18981481481481483 0.7270833333333333 0.19074074074074074 0.7270833333333333 0.19166666666666668 0.7317708333333334 0.1935185185185185 0.7317708333333334 0.19444444444444445 0.7328125 0.19444444444444445 0.7328125 0.19537037037037036 0.7375 0.19722222222222222 0.7375 0.19814814814814816 0.7385416666666667 0.19814814814814816 0.7385416666666667 0.19907407407407407 0.74375 0.20092592592592592 0.74375 0.20185185185185187 0.7447916666666666 0.20185185185185187 0.7447916666666666 0.20277777777777778 0.7479166666666667 0.20277777777777778 0.7479166666666667 0.2037037037037037 0.7494791666666667 0.2037037037037037 0.7494791666666667 0.20462962962962963 0.7510416666666667 0.20462962962962963 0.7510416666666667 0.20555555555555555 0.7526041666666666 0.20555555555555555 0.7526041666666666 0.2064814814814815 0.7552083333333334 0.2064814814814815 0.7557291666666667 0.20833333333333334 0.7578125 0.20925925925925926 0.7583333333333333 0.2111111111111111 0.7598958333333333 0.2111111111111111 0.7598958333333333 0.21203703703703702 0.7614583333333333 0.21296296296296297 0.7614583333333333 0.21388888888888888 0.7604166666666666 0.21388888888888888 0.7604166666666666 0.21481481481481482 0.759375 0.21481481481481482 0.759375 0.21574074074074073 0.7583333333333333 0.21574074074074073 0.7583333333333333 0.21666666666666667 0.7572916666666667 0.21666666666666667 0.7572916666666667 0.2175925925925926 0.7557291666666667 0.2175925925925926 0.7557291666666667 0.21851851851851853 0.7541666666666667 0.21851851851851853 0.7536458333333333 0.22037037037037038 0.7526041666666666 0.22037037037037038 0.7526041666666666 0.2222222222222222 0.7520833333333333 0.2222222222222222 0.7515625 0.22407407407407406 0.7505208333333333 0.22407407407407406 0.7479166666666667 0.22962962962962963 0.746875 0.22962962962962963 0.7442708333333333 0.2351851851851852 0.7432291666666667 0.2351851851851852 0.7385416666666667 0.24444444444444444 0.7375 0.24444444444444444 0.7338541666666667 0.2518518518518518 0.7328125 0.2518518518518518 0.7296875 0.25833333333333336 0.7286458333333333 0.25833333333333336 0.725 0.2657407407407407 0.7177083333333333 0.26666666666666666 0.7177083333333333 0.2657407407407407 0.7161458333333334 0.2657407407407407 0.7161458333333334 0.26481481481481484 0.7151041666666667 0.26481481481481484 0.7145833333333333 0.26296296296296295 0.7135416666666666 0.26296296296296295 0.7130208333333333 0.2611111111111111 0.7114583333333333 0.2601851851851852 0.7114583333333333 0.2611111111111111 0.7135416666666666 0.2638888888888889 0.7135416666666666 0.27037037037037037 0.7072916666666667 0.27037037037037037 0.7072916666666667 0.26944444444444443 0.70625 0.26944444444444443 0.70625 0.26851851851851855 0.7052083333333333 0.26851851851851855 0.7052083333333333 0.2675925925925926 0.7020833333333333 0.2657407407407407 0.7015625 0.2638888888888889 0.6963541666666667 0.26296296296296295 0.6963541666666667 0.262037037037037 0.6953125 0.262037037037037 0.6953125 0.2601851851851852 0.6921875 0.25925925925925924 0.6911458333333333 0.2564814814814815 0.6890625 0.2564814814814815 0.6885416666666667 0.2490740740740741 0.6901041666666666 0.24722222222222223 0.6901041666666666 0.24351851851851852 0.6885416666666667 0.24259259259259258 0.6885416666666667 0.24166666666666667 0.6869791666666667 0.23981481481481481 0.6864583333333333 0.23703703703703705 0.6854166666666667 0.23703703703703705 0.6848958333333334 0.2351851851851852 0.6838541666666667 0.2351851851851852 0.6828125 0.2324074074074074 0.6817708333333333 0.2324074074074074 0.6817708333333333 0.23148148148148148 0.6807291666666667 0.23055555555555557 0.6802083333333333 0.2212962962962963 0.6796875 0.2212962962962963 0.6796875 0.21296296296296297 0.6802083333333333 0.21296296296296297 0.6802083333333333 0.20833333333333334 0.6807291666666667 0.20833333333333334 0.6807291666666667 0.2074074074074074 0.6796875 0.2074074074074074 0.6791666666666667 0.20462962962962963 0.6807291666666667 0.2037037037037037 0.68125 0.19814814814814816 0.6817708333333333 0.19814814814814816 0.6833333333333333 0.19444444444444445 0.6864583333333333 0.1935185185185185 0.6864583333333333 0.19166666666666668 0.6869791666666667 0.19166666666666668 0.6869791666666667 0.18981481481481483 0.6875 0.18981481481481483 0.6880208333333333 0.18703703703703703 0.6890625 0.18703703703703703 0.6890625 0.18611111111111112 0.6901041666666666 0.18611111111111112 0.6901041666666666 0.18518518518518517 0.6911458333333333 0.18518518518518517 0.6911458333333333 0.18425925925925926 0.6921875 0.18425925925925926 0.6921875 0.18333333333333332 0.6953125 0.18333333333333332 

where the first element "0" is the label and the rest of the values are polygon x,y coordinates normalized to their width and height .
I was facing the following issue:
 /home/ubuntu/yolov5_final/data/images/train/_frame676.jpg: ignoring corrupt image/label: zero-size array to reduction operation minimum which has no identity
Clearly , all the images and labels were being ignored as it fails to verify. Can you help me in resolving this issue?

**Comment by sivaji123256** [comment]
@glenn-jocher and @AyushExel ,both the images and labels are not corrupted. I can access both of them. But the issue was still persisting.

**Comment by glenn-jocher** [comment]
Hello @sivaji123256,
The error message "ignoring corrupt image/label: zero-size array to reduction operation minimum which has no identity" typically means there's an issue with the data format or file structure. The coordinates format looks correct, so it might be worth double-checking that the file paths in your dataset are accurate and that the images and labels are properly aligned. Also, ensure the images are not damaged or empty. Let me know if you need any further assistance with this.
