### ISSUE TITLE
Why dropout layer with p=0.0?

### ISSUE THREAD

**Issue by HEGAB7** [ultralytics/yolov5#10804]
https://github.com/ultralytics/yolov5/blob/c442a2e99321ebd72b242bc961824f82d46e4fd3/models/common.py#L854

There is a dropout layer with p = 0.0 that seems not useful

**Comment by HEGAB7** [comment]
Solved here: https://github.com/ultralytics/yolov5/pull/10805#issue-1551554284

**Comment by glenn-jocher** [comment]
@HEGAB7 thanks for your contribution to the YOLOv5 codebase! The dropout layer with p=0.0 is a no-op and has no effect on the outputs. This code has now been updated to remove the dropout layer completely. Your interest and feedback are appreciated – feel free to reach out if you have any further questions!
