### ISSUE TITLE
Error running multi-gpu evolve 

### ISSUE THREAD

**Issue by silvada95** [ultralytics/yolov5#10800]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am trying to perform a hyperparameter evolution with multi-gpu, following the instructions of the site. However, the following problem is appearing:

AssertionError: Invalid CUDA '--device 0' requested, use '--device cpu' or pass valid CUDA device(s)

I tried to create new environments, re-install the requirements.txt, but nothing is working.

I also tried the solution from here https://github.com/ultralytics/yolov5/issues/8848, but nothing happen.

Specs: torch 1.9.0, cu11.1, torchaudio 0.9.0, and torchvision 0.10.0, python 3.9.16

**Comment by glenn-jocher** [comment]
@silvada95 hi there! It seems like the issue you are encountering is related to the CUDA device configuration. To address this, please ensure that you have the correct CUDA version installed and that it is compatible with your GPU setup. Additionally, you can try specifying the CUDA device using the '--device' flag.

For further guidance, you can refer to the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/ for detailed information on multi-GPU training and CUDA device configuration.

Feel free to reach out if you have further questions or need additional assistance. Good luck with your hyperparameter evolution!
