### ISSUE TITLE
Error when getting started with PyTorch 1.7

### ISSUE THREAD

**Issue by bhaktatejas922** [ultralytics/yolov5#1080]
## Additional context
Using Pytorch 1.7, python 3.7, 32 bit arm[]

(url)
![image](https://user-images.githubusercontent.com/26863466/95006813-230dd900-05bd-11eb-8945-9034fd6b1a3b.png)

**Comment by glenn-jocher** [comment]
@bhaktatejas922 recommend you use the latest stable torch release, which is 1.6 as of this writing.
