### ISSUE TITLE
Add support fo data loading with tensorclasses

### ISSUE THREAD

**Issue by abhiksark** [ultralytics/yolov5#10819]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Tensorclasses and memory-mapped tensors can be used together to efficiently load data from disk inside a model training pipeline.

This means that not only do we avoid performing repeated computation each time we iterate through the data, we also are able to efficiently load data from the memory-mapped tensor in batches, rather than sequentially from the raw image files.

Using the combination of pre-processing, loading on a contiguous physical-memory storage and on-device batched transformation, we obtain a 10x speedup in data-loading over regular torch + torchvision pipelines.

### Additional

Compared to traditional data loading on ImageNet, people are posting  > 10x faster data loading for a similar computational budget!

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@abhiksark that sounds like a fantastic performance improvement for data loading! We greatly appreciate your willingness to submit a PR to add support for data loading with tensorclasses. Your contribution will undoubtedly benefit the YOLOv5 community. We look forward to reviewing your pull request and thank you for your dedication to enhancing YOLOv5. If you have any questions while working on the PR, feel free to consult the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/ for guidance.
