### ISSUE TITLE
Using multi GPU to detect video frames

### ISSUE THREAD

**Issue by acalatrava** [ultralytics/yolov5#10812]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How can I modify the `detect.py` script to use multiple GPU when analyzing a video? I want to split the frames across the GPUs so the video can be processed faster.

I passed the `--device` argument with the list of the GPUs and it detects them but only use the first one...

Any help?

**Comment by glenn-jocher** [comment]
@acalatrava hi there! 👋 To use multiple GPUs for analyzing a video with YOLOv5, you don't need to modify the `detect.py` script itself. Instead, you can utilize the `--device` argument to specify multiple GPUs like `--device 0,1,2,3` for instance. YOLOv5 automatically splits the frames across the specified GPUs for faster processing.

Let me know if you have any further questions or issues with this!

**Comment by keonyi** [comment]
I have a same problem. For training, two GPUs work fine. However, for detecting, only one GPU works regardless of the option —device 0,1.

**Comment by pderrenger** [comment]
@keonyi for detection, multi-GPU support isn't natively implemented in `detect.py`. You might consider processing different segments of the video in parallel using separate instances of the script on each GPU.
