### ISSUE TITLE
Model metrics omit false positives in empty/background images

### ISSUE THREAD

**Issue by adamhrv** [ultralytics/yolov5#10817]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Validation

### Bug

False positive detections in images without a label (background images) seem to be omitted from the model metrics when running `val.py`. This would affect F1 scores for any model tested with background images in the validation dataset that generated false positives on those images.

A simplified test can be run with 2 images and 2 labels from the coco128 dataset by omitting one label (make it a background image). The calculated precision will be 1.0 but should be 0.5 (one correct and one incorrect detection = 50% precision). 

### Environment

`YOLOv5 🚀 v7.0-108-g5c7bafb9 Python-3.8.11`

### Minimal Reproducible Example

Step 1: Download the coco128 dataset
Step 2: remove all images except `000000000034.jpg` and `000000000502.jpg` 
Step 3: remove all labels except  `000000000034.txt` and `000000000502.txt` 
Step 4: run `python val.py --weights yolov5s.pt --data coco128.yaml --img 640` --> Precision = 1 (correct)
Step 5: open `000000000502.txt`  and delete the annotation (make it an empty file)
Step 6: now run `python val.py --weights yolov5s.pt --data coco128.yaml --img 640` --> Precision = 1 (should be 0.5)

In step 4 both images have correct labels:
![val_batch0_labels_montage](https://user-images.githubusercontent.com/199849/214170868-0e8a79b2-a3d4-4c61-8b22-aeca5fd84f1f.jpg)

In step 8 the bear detection label was remove and now becomes a false positive:

![val_batch0_labels_montage](https://user-images.githubusercontent.com/199849/214170803-02f3caa4-d63a-4192-8717-3c60e2371e1f.jpg)

Assets linked below:

![000000000034](https://user-images.githubusercontent.com/199849/214170447-9a6b79b2-9fa2-4b38-89c0-dd762a922660.jpg)
![000000000502](https://user-images.githubusercontent.com/199849/214170451-a8d44e93-0b85-4a88-be63-6a9d15a2a7be.jpg)
[000000000034.txt](https://github.com/ultralytics/yolov5/files/10484282/000000000034.txt)
[000000000502.txt](https://github.com/ultralytics/yolov5/files/10484262/000000000502.txt)

- Edited to remove an uncertainty due to stale .cache.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by adamhrv** [comment]
Adding this to `metrics.py` below [line 178](https://github.com/ultralytics/yolov5/blob/master/utils/metrics.py#L178)  seems to include false positives on background image in the confusion matrix, but not yet in the actual metrics:
```
elif len(detections):
            for d in detections:
                self.matrix[d[5].int(), self.nc] += 1  # false positive
```
And editing [line 250](https://github.com/ultralytics/yolov5/blob/master/val.py#L249) in `val.py` to:
```
if nl or npr:
```

**Comment by glenn-jocher** [comment]
@adamhrv thanks for your input! We appreciate your contribution. The YOLOv5 repo is always looking for ways to enhance its functionality, and we value your input in this matter. Your code appears to be a step in the right direction towards including false positives on background images in the confusion matrix. We will review this and consider its potential inclusion for future updates.

Thanks again for your contribution! Keep sharing your thoughts and ideas. We are stronger together as a community.
