### ISSUE TITLE
Cannot use custom trained model for local inference or integration to local project.

### ISSUE THREAD

**Issue by devashish-bhake** [ultralytics/yolov5#10810]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Other

### Bug

I trained a custom yolov5 model using the yolov5l and was trying to perform some inference using standard code to integrate it with my project using the following piece of code:
```
import torch
model = torch.hub.load('D:\kaggle_practice\yolov5', 'custom', path=r'D:\kaggle_practice\yolov5\runs\train\exp3\weights\best.pt', source='local')
image = r"D:\kaggle_practice\Knee_OA_RP\knee_OA_dataset_2\images\9000099L.png"
results = model(image)
results.show()
```

After running the above code it does not give any errors but it also doesn't give any detections whatsoever. 
I tried to run the same model using the detect.py command on command prompt and there I was getting all the detections correctly.
Can anyone point-out what I have done wrong?

### Environment

-YOLOv5  v7.0-74-gd1d04f9 Python-3.9.15 torch-1.13.1+cu116 CUDA:0 (NVIDIA GeForce GTX 1650 Ti, 4096MiB)
-OS: Windows

### Minimal Reproducible Example

```
import torch
model = torch.hub.load('D:\kaggle_practice\yolov5', 'custom', path=r'D:\kaggle_practice\yolov5\runs\train\exp3\weights\best.pt', source='local')
image = r"D:\kaggle_practice\Knee_OA_RP\knee_OA_dataset_2\images\9000099L.png"
results = model(image)
results.show()
```

### Additional

Nothing other than this but I think that integrating the model on local projects becomes almost Impossible.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by devashish-bhake** [comment]
After a lot of trial and error I guess we cannot use the custom trained models in our projects after all...if there is any progress please let me know man..

**Comment by devashish-bhake** [comment]
After carefully searching through the documentation I found that in order to get the output we have to specify the size of the image in order to get the output correctly so everyone who was stuck on this issue have to call the model as:
`
result = model("image.png", size=size_of_your_image)
`

**Comment by glenn-jocher** [comment]
@devashish-bhake thanks for sharing that information! Specifying the size of the image is indeed crucial for obtaining correct outputs. Integrating the model with local projects should be feasible by calling the model as you specified. Your contribution will surely benefit others facing a similar issue. To further enhance local integration, you can refer to the Ultralytics Docs for additional guidance and best practices. Let us know if you have any other questions!
