### ISSUE TITLE
Unable to run epochs 

### ISSUE THREAD

**Issue by prabjotbali** [ultralytics/yolov5#10811]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

While running the !python /content/yolov5/train.py --img 320 --batch -1 --epochs 100 --data {dataset.location}/data.yaml --weights yolov5s-seg.pt --name custom-dataset
changing here batch size to -1 for default 
and if i the batch size should be any different the error for the epochs will remain same
![image](https://user-images.githubusercontent.com/123187816/213941752-642d6e60-2296-42a6-a66b-abd821f52de4.png)
The error will be that the training will not do any epochs and show an error of 
Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
  0% 0/17 [00:03<?, ?it/s]

Traceback (most recent call last):
  File "/content/yolov5/train.py", line 634, in <module>
    main(opt)
  File "/content/yolov5/train.py", line 528, in main
    train(opt.hyp, opt, device, callbacks)
  File "/content/yolov5/train.py", line 310, in train
    loss, loss_items = compute_loss(pred, targets.to(device))  # loss scaled by batch_size
  File "/content/yolov5/utils/loss.py", line 125, in __call__
    tcls, tbox, indices, anchors = self.build_targets(p, targets)  # targets
  File "/content/yolov5/utils/loss.py", line 198, in build_targets
    anchors, shape = self.anchors[i], p[i].shape
AttributeError: 'list' object has no attribute 'shape'
![image](https://user-images.githubusercontent.com/123187816/213941856-de9a41d8-6791-4052-a149-3091097e7b51.png)

Can you help me with this?

**Comment by jean-victor** [comment]
I'm having the same issue and I didn't find the solution yet..

**Comment by wang-10086** [comment]
I have the same problem and I haven't found a solution yet. I didn't experience this problem in v5.0, but it appears in v7.0. Is this a bug in the latest version?

```
AutoAnchor: 4.27 anchors/target, 0.994 Best Possible Recall (BPR). Current anchors are a good fit to dataset
Plotting labels to runs\train\exp6\labels.jpg... 
Image sizes 640 train, 640 val
  File "train.py", line 528, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 310, in train
    loss, loss_items = compute_loss(pred, targets.to(device))  # loss scaled by batch_size
  File "D:\python_project\object_detection\yolov5-v7\utils\loss.py", line 125, in __call__
    tcls, tbox, indices, anchors = self.build_targets(p, targets)  # targets
  File "D:\python_project\object_detection\yolov5-v7\utils\loss.py", line 198, in build_targets
    anchors, shape = self.anchors[i], p[i].shape
AttributeError: 'list' object has no attribute 'shape'
```

**Comment by jean-victor** [comment]
If it can helps, i solved my problem in running train.py directly and add my arguments inside the main as follow:
```
if __name__ == "__main__":
    opt = parse_opt()
    opt.data="Path\to\yaml_file"
    main(opt)
```

**Comment by wang-10086** [comment]
@jean-victor Thank you, I tried the method you mentioned, running train.py directly, but the problem wasn't solved, it still reported the following error:
```
AttributeError: 'list' object has no attribute 'shape'
```
I think there may still be other reasons, I would like to know your python version and pytorch version.

**Comment by jean-victor** [comment]
I found out that it doesn't depends on what i wrote earlier. I have the error when I use the yolov5x-seg.pt and not when I do not specify the weights (it takes as default yolov5s.pt as I understand)

**Comment by wang-10086** [comment]
> I found out that it doesn't depends on what i wrote earlier. I have the error when I use the yolov5x-seg.pt and not when I do not specify the weights (it takes as default yolov5s.pt as I understand)

Yes, you are right, this is the reason for the weight. I tried to change the weights to yolov5s.pt and then I can train normally. Maybe the latest yolov5s-seg.pt uses a different network structure than the one we use, but of course this is just my guess. Thank you very much for solving my problem.

**Comment by glenn-jocher** [comment]
@wang-10086 hi there! I'm glad you were able to find a workaround for the issue. You're correct, the problem seems to be associated with the specific weight file yolov5x-seg.pt. Using yolov5s.pt as the default weight should allow training to proceed normally. Your input greatly helped us identify a potential compatibility issue with the yolov5x-seg.pt weight file. Thank you for sharing your findings! Please don't hesitate to reach out if you encounter any other issues or have further questions. Good luck with your training!
