### ISSUE TITLE
What are detection values when the AI is not detecting anything anymore

### ISSUE THREAD

**Issue by JorgTV** [ultralytics/yolov5#10815]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hey! This question might be a bit confusing, so let me explain: I'm using mss and cv2 to display the detection on a 640 x 640 window like this: https://i.imgur.com/sZ49UQn.png. When it's detecting something it outputs the position on this window just fine like this: https://i.imgur.com/NyuX1G5.png. The problem now is, that when I'm not looking at anything it could detect anymore it's not updating the values anymore. The values also are neither 0, nor -1, nor None, nor the same value as before. Now comes my question: What's the actual value the detection gets stored in if there's nothing to be seen? If you have further questions about my problem feel free to ask. English is not my main language and that's why my grammar might be a bit off / might be that I explain in a bit strange. Thanks in advance!

**Comment by JorgTV** [comment]
Just dug deeper, it seems like current_x == current_x only when it's detecting something. When it doesnt detect something current_x is acutally not equal to current_x which seems very strange to me.

**Comment by glenn-jocher** [comment]
@JorgTV if the detection values are not updating when there's nothing to be seen, it's possible that the model is returning NaN (not a number) for the coordinates. This can happen when no objects are detected, and it's not uncommon in some computer vision libraries. You can check for NaN values in the coordinates and handle them accordingly. Remember to consult the Ultralytics YOLOv5 documentation for detailed usage and troubleshooting. If you have further questions, feel free to ask!
