### ISSUE TITLE
Silence .save() print statement in Pytorch implementation ("Saved X image to y")

### ISSUE THREAD

**Issue by jeannotdamoiseaux** [ultralytics/yolov5#10816]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is there an argument to silence the .save() function in the Pytorch implementation?

**Comment by glenn-jocher** [comment]
@jeannot-github hi there! The print statement can be silenced by setting the `verbose` argument to `False` when calling the `.save()` function in the PyTorch implementation. This will prevent the "Saved X image to y" message from being displayed. For more details, you can refer to the documentation at https://docs.ultralytics.com/yolov5/.

Let me know if you need further assistance!
