### ISSUE TITLE
Training errors on ECS

### ISSUE THREAD

**Issue by Nigysty** [ultralytics/yolov5#1081]
Hi! sir, Sorry to waste your time。 I got a problem.
# Environment
 - OS: [e.g. Ubuntu]
 - GPU [e.g. 2080 Ti]

When i training my datasets on ECS,
my training cimmond:
python train.py --img 640 --batch 16 --epochs 300 --data ../mask/data.yaml --cfg models/yolov5s.yaml --weights '' 

i got errors:
Traceback (most recent call last):
  File "train.py", line 456, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 186, in train
    plot_labels(labels, save_dir=log_dir)
  File "/home/yolov5/utils/general.py", line 1179, in plot_labels
    fig, ax = plt.subplots(2, 2, figsize=(8, 8), tight_layout=True)
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/matplotlib/pyplot.py", line 1177, in subplots
    fig = figure(**fig_kw)
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/matplotlib/pyplot.py", line 546, in figure
    **kwargs)
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 3358, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 888, in new_figure_manager_given_figure
    window = tk.Tk(className="matplotlib")
  File "/root/miniconda3/envs/myconda/lib/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display ":1"

**Comment by glenn-jocher** [comment]
@Nigysty it appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below. 


## Requirements

**Python 3.8** or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including **`torch>=1.6`**. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by AaronMaYue** [comment]
You can solve this problem by adding 'matplotlib.use('Agg')' to general.py

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

**Comment by glenn-jocher** [comment]
@AaronMaYue is this something that should be considered for general use, i.e. suitable for a PR?

**Comment by AaronMaYue** [comment]
@glenn-jocher 
I run a service on Linux that doesn't require display, and I've had the same error, which I think is a matplotlib backend problem.
Setting matplotlib.use('agg') forces you not to interactively view the displayed images, but to save them to disk for later viewing.

**Comment by glenn-jocher** [comment]
@AaronMaYue ah I see. For the most part the intention is always to save them to disk for later viewing rather than for realtime matplotlib views. 

Would there be any other negative impacts to setting `matplotlib.use('agg')` as default?

**Comment by glenn-jocher** [comment]
@AaronMaYue @Nigysty I believe PR #1413 should resolve this issue. Let me know if this works and if you have any other issues. Thanks again for the feedback!
