### ISSUE TITLE
Do category labels have to be indexed from 0 to n before training? 

### ISSUE THREAD

**Issue by b0nl** [ultralytics/yolov5#10814]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm training a model in which I merged a couple of class labels into one and also removed a few other class labels. Now my COCO-formatted JSON file contains categories that have unique ids however they are not ordered strictly from 0 to n. For example:

```
{class: ape, id: 1}
{class: bird, id: 4}
{class: dog, id: 11}
...
{class: cat, id: 35}
```

There are now 32 classes in total because some have been merged or omitted. Originally there were 40 classes. Should I reindex the ids from 1 to 32, or can I leave them like this? The model seems to train just fine still if I don't do anything.

**Comment by bit-scientist** [comment]
@mesllo you need to reiterate the indeces to make them start from `0` to `n-1` (inclusive) where `n` is # object categories.

**Comment by JustasBart** [comment]
@mesllo Yes, what @bit-scientist said. That's usually your golden standard for any AI or even any generic Software thing.

Good luck! :rocket:

**Comment by b0nl** [comment]
I'm aware of this ideal way but from what I can see on the tensorboard results, the training still worked without reordering the index.

**Comment by JustasBart** [comment]
@mesllo Maybe there's already something in place to automatically rearrange it to what it has to be or something else altogether that I'm not aware of, but that's good to know, thanks and good luck!

**Comment by b0nl** [comment]
Can confirm that there is an automatic re-ordering going on. Thank you!

**Comment by glenn-jocher** [comment]
@mesllo you're welcome! It's great to hear that it's working for you. If you have any more questions or need further assistance, feel free to ask. Good luck with your training!
