### ISSUE TITLE
How to use ConfusionMatrix

### ISSUE THREAD

**Issue by lfangyu09** [ultralytics/yolov5#10826]
#Hi

I want to use [ConfusionMatrix function](https://github.com/ultralytics/yolov5/blob/3a059125dd7b01c76b7a02b59814ed5bc32d9ac4/utils/metrics.py) to get the confusion matrix map based on the ground truth json file and prediction json file. How to process the data?

I used to do this but the results are significantly different from the saved confusion matrix results:

```
annFile = '/test_truth.json'
cocoGt=COCO(annFile)

resFile = '/best_predictions.json'
cocoDt=cocoGt.loadRes(resFile)

C_M = ConfusionMatrix(nc=5)
img_ids = cocoGt.getImgIds()
stats = []
for i in range(len(cocoGt.imgs)):
    bbox_gt = torch.Tensor([y['bbox'] for y in cocoGt.imgToAnns[img_ids[i]]])
    class_gt = torch.Tensor([[y['category_id']-1] for y in cocoGt.imgToAnns[img_ids[i]]])
    labels = torch.hstack((class_gt,bbox_gt))

    bbox_dt = torch.Tensor([y['bbox'] for y in cocoDt.imgToAnns[img_ids[i]]])
    conf_dt = torch.Tensor([[y['score']] for y in cocoDt.imgToAnns[img_ids[i]]])
    class_dt = torch.Tensor([[y['category_id']-1] for y in cocoDt.imgToAnns[img_ids[i]]])
    predictions = torch.hstack((torch.hstack((bbox_dt,conf_dt)),class_dt))

    C_M.process_batch(predictions, labels)

C_M.print()
C_M.plot(save_dir='...',names=['...'])
```

How to fix it? Thanks a lot.

**Comment by glenn-jocher** [comment]
@lfangyu09 hi there!

To use the ConfusionMatrix in YOLOv5, you should process dataset labels and predictions into a suitable format prior to passing them to `C_M.process_batch(predictions, labels)`. Ensure that the data being used for the ConfusionMatrix follows the required format.

For a detailed guide on using ConfusionMatrix function, you can refer to our documentation at https://docs.ultralytics.com/yolov5/. If you have further inquiries, feel free to ask!
