### ISSUE TITLE
Output of Yolov5 Custom Trained Model Tensor Only

### ISSUE THREAD

**Issue by kmcgrathgenerate** [ultralytics/yolov5#10825]
I have a custom trained Yolov5n model that I am loading:

```
self.model = torch.hub.load('ultralytics/yolov5', 'yolov5n', classes=2, pretrained=False) 
self.model.load_state_dict(torch.load('/path/to/weights.pt')['model'].state_dict(), strict=False)
self.model = self.model.fuse() 
```

and predicting an output:

```
imt = torch.from_numpy(image)
pred = self.model(imt)
print(pred.print())
```

'list' object does not have attribute 'print'

I keep seeing on examples from other posts that you are then able to call functions on 'pred' like "pandas()", "print()", "xyxy", "results.pandas().xyxy[0].value_counts('name')", etc but my output of my prediction is just a tensor. I see online about what each chunk of data means but why am I not able to use these QoL functions? Is there something I am doing wrong?

**Comment by kmcgrathgenerate** [comment]
I found that the reason I was not getting any discernable output was because of my input handling. Instead of putting through a HxW image frame, I was doing pre-processing such as:

```
        image = cv2.resize(frame, (640,640))
        image = cv2.cvtColor(image, cv2.COLOR_GRAY2RGB)
        image = np.einsum('ijk->kij', image)
        image = np.expand_dims(image, axis=0)
        image  = np.array(image, dtype=np.float32)
        imt = torch.from_numpy(image)
```

I don't think this is necessary for YOLOv5 and it was messing up my output

**Comment by glenn-jocher** [comment]
@kmcgrathgenerate great to hear that you found the issue! 

You are correct - for YOLOv5, you can directly use OpenCV to load the image and then convert it to a torch tensor without any additional pre-processing. Here's a simplified example:

```python
# Load image using OpenCV
image = cv2.imread('path_to_image.jpg')

# Convert to torch tensor
imt = torch.from_numpy(image).float()
```

This should give you a proper output from the YOLOv5 model without unnecessary pre-processing. If you have any more questions or encounter further issues, feel free to ask!
