### ISSUE TITLE
Build_targets clarification

### ISSUE THREAD

**Issue by ckyrkou** [ultralytics/yolov5#10821]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

In the build_target function is a target assigned to a single grid cell or multiple? Also is assigned to a grid cell in each layer? In the original YOLO target assignment the target is assigned to the anchor box with the highest IoU, which is I understand not the case here. Is there a documentation describing the assignment process in detail?

**Comment by glenn-jocher** [comment]
@ckyrkou hi there! In the YOLOv5 `build_targets` function, a target is assigned to a single grid cell within each layer. We've diverged from the original YOLO target assignment as you noted, and detailed documentation on the assignment process can be found in the Ultralytics Docs at https://docs.ultralytics.com/yolov5/. Let me know if you need any further assistance!
