### ISSUE TITLE
YOLO auto pip-installing requirements

### ISSUE THREAD

**Issue by aschmiri** [ultralytics/yolov5#10833]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I just realized that YOLO starts silently to auto pip-install stuff into my (conda!) environment on import. I am fine with errors/warnings but find this very "intrusive". Beside this being bad practice, this screwed up my whole environment. Please be aware that people are using yolo in conjunction with other libraries.

On a related note, I would recommend creating a yolov5 package hierarchy, such that you can `import yolov5.train` instead of a very generic `import train`.

**Comment by glenn-jocher** [comment]
@aschmiri hi there! Thanks for your feedback. 🙌 The automatic pip-install behavior is intended to make YOLOv5 as user-friendly as possible, but I understand that it might not be suitable for all users or setups. 

I appreciate the suggestion regarding the package hierarchy, and I've forwarded it to the Ultralytics team for further consideration. 

Regarding the environment issues, I'd recommend creating a dedicated Conda environment for YOLOv5 to avoid any conflicts with other libraries. You can find more information on setting up environments in our [documentation](https://docs.ultralytics.com/yolov5/).

If you have any other questions or need further assistance, feel free to ask!
