### ISSUE TITLE
about dataset distribution

### ISSUE THREAD

**Issue by ampelmannn** [ultralytics/yolov5#10838]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

The number of images/objects for each train/val was confirmed through the data file for the two data sets (COCO, VisDrone).
How can I check the distribution of the number of instances by category (class)?

**Comment by glenn-jocher** [comment]
@ampelmannn you can visualize the distribution of the number of instances by category using the `datasets.py` script provided in the YOLOv5 repository. Check out the `create_charts` method in the script for an example of how to do this. You can find more information on working with custom datasets in the Ultralytics Docs at https://docs.ultralytics.com/yolov5/. Let me know if you need further assistance!
