### ISSUE TITLE
ONNX export failure  0.1s unsupported ONNX opset version :17

### ISSUE THREAD

**Issue by synersignart** [ultralytics/yolov5#10831]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Export

### Bug

ONNX export failure  0.1s unsupported ONNX opset version :17 

### Environment

yolov5 v7 
Windows 10
python 3.9.0

has anyone encounter this error?
id want to know what is it and how can it be resolve

I have install all the requirement .txt

when I try exporting .pt as .onnx

![onnx error](https://user-images.githubusercontent.com/22503442/214589070-5c4da842-46d7-4f88-bb53-af0837aed8bb.png)

Also the Train.py keeps crashing

### Minimal Reproducible Example

python yolov5/export.py --weights yolov5n.pt --include torchscript onnx

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by synersignart** [comment]
Train.py also not working as in the documentation and produces this error
Windows 10
Python 3.9.0
Yolov5 v7

python yolov5/train.py --data coco128.yaml --weights '' --cfg yolov5s.yaml --img 640

![train error](https://user-images.githubusercontent.com/22503442/214591171-d9b29386-c91d-4f49-9eb9-810f139f73ed.png)

**Comment by xylieong** [comment]
Same here @glenn-jocher

**Comment by xylieong** [comment]
I faced the same problem. Using torch version 1.13.1 and torch-vision version 1.13.1 solves the problem. @synersignart

**Comment by xylieong** [comment]
I faced the same problem. Using torch version 1.13.1 and torch-vision version 0.14.1 solves the problem. @synersignart

**Comment by Andulka97** [comment]
>

**Comment by JustasBart** [comment]
Hi, this is what my ONNX export looks like for C++ via OpenCV::dnn:

```
python3 export.py \
--weights runs/train/exp/weights/best.pt \
--img 704 1280 \
--include onnx \
--optimize \
--simplify \
--opset 12
```

Try that **opset 12** flag on your end and see if that helps, good luck! :rocket:

**Comment by synersignart** [comment]
any solution to this?

**Comment by xylieong** [comment]
@JustasBart Good tip!
@synersignart As @JustasBart mentioned, you can use `--opset 12` to solve the problem.

**Comment by xylieong** [comment]
@synersignart See [Update to ONNX opset 17](https://github.com/ultralytics/yolov5/pull/10522) You can either update torch and torchvision version or use a lower `opset` as mentioned by @JustasBart

**Comment by keepgoing365** [comment]
> Hi, this is what my ONNX export looks like for C++ via OpenCV::dnn:
> 
> ```
> python3 export.py \
> --weights runs/train/exp/weights/best.pt \
> --img 704 1280 \
> --include onnx \
> --optimize \
> --simplify \
> --opset 12
> ```
> 
> Try that **opset 12** flag on your end and see if that helps, good luck! rocket

I'm facing the same problem,fixing opset==12,it woeks

**Comment by keepgoing365** [comment]
> Hi, this is what my ONNX export looks like for C++ via OpenCV::dnn:
> 
> ```
> python3 export.py \
> --weights runs/train/exp/weights/best.pt \
> --img 704 1280 \
> --include onnx \
> --optimize \
> --simplify \
> --opset 12
> ```
> 
> Try that **opset 12** flag on your end and see if that helps, good luck! rocket


I'm facing the same problem,setting opset==12,it woeks. Thank you @JustasBart

**Comment by JustasBart** [comment]
@keepgoing365 Good luck and all the best! :rocket:

**Comment by HXB-1997** [comment]
python export.py --weights yolov5n-seg.pt --include  onnx --opset 12 解决问题

**Comment by glenn-jocher** [comment]
@HXB-1997 hi there! It seems like you're encountering an issue with exporting your YOLOv5 model to ONNX format. Setting the `--opset` flag to `12` can often help resolve this problem. Please try running the export command again with `--opset 12` and see if that works for you. Good luck!
