### ISSUE TITLE
urllib3.connectionpool warning during training

### ISSUE THREAD

**Issue by camillebobsin** [ultralytics/yolov5#10834]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training, Integrations

#### Context

I'm using ClearML as a logger for Experiment Tracking. For that, I set the environment variables like this:
```
%env CLEARML_WEB_HOST=https://app.clear.ml
%env CLEARML_API_HOST=https://api.clear.ml
%env CLEARML_FILES_HOST=https://files.clear.ml
%env CLEARML_API_ACCESS_KEY=<my_key>
%env CLEARML_API_SECRET_KEY=<my_key>
```
And then for training I use the following script:
```
!python train.py --img {img_size} --batch 96 --epochs {epochs} --data {dataset.location}/data.yaml --weights {model} --cache --project project_name
``` 
The `--project` tag refers to the folder name I have in ClearML for that project, as suggested [here](https://github.com/ultralytics/yolov5/tree/master/utils/loggers/clearml#-training-yolov5-with-clearml).

I've always run the model that way and never had any problems, until today.

I started taking this warning before starting the training:

```
WARNING:urllib3.connectionpool:Retrying (Retry(total=239, connect=239, read=240, redirect=240, status=240)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f98c83f8250>: Failed to establish a new connection: [Errno -2] Name or service not known')': /auth.login
```

I believe it has something to do with ClearML because of this message:
`Failed to establish a new connection: [Errno -2] Name or service not known`

#### Screenshot

This warning is repeated several times in descending order as seen in the last 4 lines below
![image](https://user-images.githubusercontent.com/87498292/214641712-2698daad-5c9b-40c0-a5da-d033ed0de66b.png)
Can someone help me? The time between one warning and another is long, and only after finishing all the warnings does the training begin. I don't have that time.

### Environment

- Google Colab Pro +

### Minimal Reproducible Example

```
!python train.py --img {img_size} --batch 96 --epochs {epochs} --data {dataset.location}/data.yaml --weights {model} --cache --project project_name
```
I also had this problem running ClearML Hyperparameters Optimization:
```
!python utils/loggers/clearml/hpo.py
```

### Additional
I already tried this solution:
```
import urllib3
urllib3.disable_warnings()
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Selbyl** [comment]
I'm having this same issue using the yolo CLI and train.py for ultrakytucs and yolov5.

**Comment by glenn-jocher** [comment]
Hello @Selbyl, sorry to hear that you're encountering a similar issue using the YOLO CLI and train.py for Ultralytics YOLOv5. Have you tried the suggested solution provided in the original issue? If not, you may consider using the `urllib3.disable_warnings()` function to suppress the warning messages during training.

Let me know if you need further assistance with this or if you have any other questions or concerns.

**Comment by KairosSun** [comment]
I also encountered such a problem, but the IP address connected in the error was the local address, so I suspected that it was the cache effect caused by the use of Clearml before, so I uninstalled all the components of Clearml. As a result, I successfully solved the problem.

pip uninstall clearml

**Comment by glenn-jocher** [comment]
Hello @KairosSun,

Thank you for sharing your experience and solution! It's great to hear that uninstalling ClearML resolved the issue for you. This information could be very helpful for others facing similar problems.

For those who might still want to use ClearML for experiment tracking, it might be worth checking if the issue persists with the latest versions of both YOLOv5 and ClearML. Sometimes, updates can resolve compatibility issues.

To ensure you have the latest versions, you can update YOLOv5 and ClearML using the following commands:

```bash
pip install --upgrade yolov5
pip install --upgrade clearml
```

If the problem continues, another approach could be to clear any cached configurations or data that might be causing the issue. You can try resetting ClearML's configuration:

```bash
clearml-init --reset
```

This will prompt you to reconfigure ClearML, which might help in resolving any lingering configuration issues.

If anyone else has additional insights or solutions, feel free to share them here. The collaborative effort of the community is invaluable! 😊
