### ISSUE TITLE
Can I so resuming training twice 

### ISSUE THREAD

**Issue by VYRION-Ai** [ultralytics/yolov5#10837]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I do training and save project to drive while training. And session end before finishing so second day I do resume and it runs and session also finished before training ends, so next day I do resuming but it doesn't work.
So did twice resuming didn't work?
Sorry,  this is public question, I am not asking for Yolo v5 only,

**Comment by JustasBart** [comment]
Hi, no you should be able to resume as many times as you wish... Is there any sort of output that you could provide with (Such as what the error is) or the steps to reproduce it in any way?

Thanks!

**Comment by glenn-jocher** [comment]
@JustasBart hi there! Yes, you should be able to resume training as many times as needed. Could you provide any specific error message or steps to reproduce the issue? This would help in finding a solution. Thank you!
