### ISSUE TITLE
albumentation RandomRotate90 + segmentation = incorrectly applied augmentation ?

### ISSUE THREAD

**Issue by ExtReMLapin** [ultralytics/yolov5#10841]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

related to #10273 and especially https://github.com/ultralytics/yolov5/issues/10273#issuecomment-1363621395

I usualy use `RandomRotate90` in util augmentations, because i work with detection, but it seems to be broken with segmentation;
Please see image attached, **especially the second one**.

![image](https://user-images.githubusercontent.com/3909752/214868366-2b48498e-0faf-4cb4-b1af-44652550e979.png)

No need to give code to reproduce as it's just one line in [augmentations.py](https://github.com/ultralytics/yolov5/blob/master/utils/augmentations.py)

### Environment

YOLOv5 on HEAD

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by ExtReMLapin** [comment]
So far no issues with hyp augmentations, only albumentation ones.

**Comment by JustasBart** [comment]
@ExtReMLapin I can confirm that there does seem to be a major issue with the Rotate parameter of the Augmentations.
Have you seen #10639?

**Comment by ExtReMLapin** [comment]
@JustasBart Are your 360° dons in the hyp files ? Or in albumentation ?

I use +/- 180° aug rotation un hyp file (as you can see in my first screenshot as the images are not straight) but I don't see any label messed up.


I wouldn't not be surprised to learn that on your problem, it's because the bbox of the original segmentation is rotated instead of the segmentation itself and the new bbox is calculated on old bbox rotated instead of new segmentation rotated.

**Comment by JustasBart** [comment]
@ExtReMLapin If I do it on the hyp file it seems to break it for me...

**Comment by ExtReMLapin** [comment]
You're using the latest yolo version ? Because see it for yourself, no issue on my end. 

![image](https://user-images.githubusercontent.com/3909752/215081041-f256778b-b274-498f-8a9c-beb5cbfe704c.png)

**Comment by JustasBart** [comment]
@ExtReMLapin If I do it on my Object Detection labels:

![train_batch0](https://user-images.githubusercontent.com/40023722/215081657-76dace7f-0f99-4fe4-89b0-bf35d19ef59b.jpg)
![train_batch1](https://user-images.githubusercontent.com/40023722/215081659-0a6931c6-e67f-4c3e-9512-cf806d89b48c.jpg)
![train_batch2](https://user-images.githubusercontent.com/40023722/215081661-b374963a-de4f-4e20-b760-97a0247e1719.jpg)

Note how the labels just expand by a huge margin...

Hyps:
![image](https://user-images.githubusercontent.com/40023722/215081839-09ac6c45-4024-4366-9c7c-33f755176dfd.png)

**Comment by ExtReMLapin** [comment]
I doubt it's a bug, but I set it to 180, not 360 as +180 or -180 already equals 360.

I'm not at the office so I can't really compare the hyps but I also had to disable mosaic as it was causing a numpy error; Weird to see it works on your end. But my hyp was based on hyp high with just rotate to 180 and mosaic to zero (from memory)


Are you sure you didn't edit your augmentations.py file ? And you're up to date with the repo code (`git pull`) ?

**Comment by JustasBart** [comment]
@ExtReMLapin This is what it looks like on 180:

![train_batch0](https://user-images.githubusercontent.com/40023722/215083836-c4209990-4ab1-4ace-97b1-2d07c5d72a14.jpg)
![train_batch1](https://user-images.githubusercontent.com/40023722/215083838-6681b9db-7c9d-405a-9054-57c68e83e8dc.jpg)
![train_batch2](https://user-images.githubusercontent.com/40023722/215083839-f1dc0541-1ddd-4d1e-b4e2-1533bb1a9636.jpg)

I've tried different values in the past such as 45 etc... None have worked for me thus far.

**Comment by JustasBart** [comment]
@ExtReMLapin Sorry, yes, I'm on the latest, but I'm also on **--rect** mode whenever I train, that could very well be my issue as well...

**Comment by ExtReMLapin** [comment]
> @ExtReMLapin Sorry, yes, I'm on the latest, but I'm also on **--rect** mode whenever I train, that could very well be my issue as well...

https://www.youtube.com/watch?v=gyZDZCGQJf8

**Comment by JustasBart** [comment]
@ExtReMLapin No, the labels are still broken even with **--rect** disabled so it's not it either...

![train_batch0](https://user-images.githubusercontent.com/40023722/215085544-f6b626ec-9d6d-4919-be0a-7eeab1ced9ef.jpg)
![train_batch1](https://user-images.githubusercontent.com/40023722/215085552-62e06079-2ce0-4ec6-adf2-089ed3ae629f.jpg)
![train_batch2](https://user-images.githubusercontent.com/40023722/215085554-727af500-98db-4740-9789-d1640e3baf52.jpg)

**Comment by ExtReMLapin** [comment]
Show me your command line

**Comment by JustasBart** [comment]
@ExtReMLapin Here's the example with the **--rect** enabled again:

```
python3 train.py \
--data /home/ash/10_Class_dataset/10Class.yaml \
--hyp data/hyps/hyp.scratch-custom.yaml \
--weights yolov5s6.pt \
--img 1280 \
--batch -1 \
--epochs 600 \
--device 0 \
--rect
```

**Comment by ExtReMLapin** [comment]
When you claim to "disable" rect, you simply strip it straight from the command line,right, you don't do something like "`--rect false`", right ?

**Comment by JustasBart** [comment]
> When you claim to "disable" rect, you simply strip it straight from the command line,right, you don't do something like "`--rect false`", right ?

Yes, that's right, I just don't mention it which defaults to a square input.

**Comment by ExtReMLapin** [comment]
I have no idea then, for reference, here is my commandline, straight from wandb.

`train.py --img 2048 --batch 11 --epochs 1250 --data diatomees_seg.yaml --weights " " --cfg yolov5n6-seg.yaml --hyp hyp.scratch-high.yaml --patience 0 --cache disk`

**Comment by JustasBart** [comment]
@ExtReMLapin It could even be just the fact that you're doing Segmentation whereas I'm doing Object Detection, but yeah, I haven't been able to figure this out just yet...

**Comment by ExtReMLapin** [comment]
Well here if you're doing detection, yes obviously it's not really surprising but it should still recalc the bbox on the rotated segmentation, not out of the old bbox

**Comment by JustasBart** [comment]
@ExtReMLapin Yeah, that's what I would think as well I mean it should still fundamentally just do it if it were working the way that it should... This augmentation makes perfect sense for Object Detection.

**Comment by ExtReMLapin** [comment]
Stale, yes, fixed, no !

**Comment by JustasBart** [comment]
Hi @ExtReMLapin I've actually recently enough realized that the rotation Augmentation makes absolutely no sense at all for Object Detection so I'm personally done with talking about it :laughing: 

All the best to you! :rocket:

**Comment by ExtReMLapin** [comment]
Sure, no issue on that but there is still issues (bugs) with albumentation and segmentation

**Comment by glenn-jocher** [comment]
Hi @ExtReMLapin! Absolutely, there may be some issues with albumentation and segmentation. Your report is invaluable for improving the YOLOv5 experience for everyone. Our team appreciates your feedback, and we're actively addressing these concerns. Thanks for your understanding and patience! If you need further assistance, feel free to reach out. All the best!
