### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '.\\hubconf.py', while loading custom model, how can I load the model without Yolov5 folder?

### ISSUE THREAD

**Issue by akashlinux10may** [ultralytics/yolov5#10845]
File "C:\Users\anaconda3\envs\pytorch-gpu\lib\site-packages\torch\hub.py", line 540, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "C:\Users\anaconda3\envs\pytorch-gpu\lib\site-packages\torch\hub.py", line 566, in _load_local
    hub_module = _import_module(MODULE_HUBCONF, hubconf_path)
  File "C:\Users\anaconda3\envs\pytorch-gpu\lib\site-packages\torch\hub.py", line 89, in _import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 915, in get_code
  File "<frozen importlib._bootstrap_external>", line 972, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '.\\hubconf.py'

above is the error I am getting. 

I tried 

model =  torch.hub.load('.', 'custom', source ='local', path='last.pt',force_reload=True)

but didnt worked, is there any alternative for 

model =  torch.hub.load('yolov5', 'custom', source ='local', path='last.pt',force_reload=True)

as I am getting checkmarx scan severity warning for hubconf.py of the file in yolov5.

Suggest solution.

**Comment by Jarye0612** [comment]
execute:
model = torch.hub.load('**/yolov5-master/train_model/yolov5', 'custom', path='**/yolov5-master/train_model/yolov5m.pt', source='local')  # local repo
error:
FileNotFoundError: [Errno 2] No such file or directory: '**/yolov5-master/train_model/yolov5\\hubconf.py'

I download yolov5m.pt in **/yolov5-master/train_model/yolov5m.pt,  I meet the same question,Do you find solution, Could you give an example?

**Comment by az-oolloow** [comment]
Same issue, anybody found a soluion?

**Comment by umang299** [comment]
Same issue, can someone help fix this ?

**Comment by SergheiDinu** [comment]
Same issue in pyinstaller utilization. Any solution?

**Comment by Rich2020** [comment]
same issue...

**Comment by havever** [comment]
Solved this problem by giving absolute address like '/opt/ml/model/code/'. 
'.' leads to /pythonx.x/site-packages/torch/

write the function as:
torch.hub.load('/opt/ml/model/code/', 'custom', source ='local', path='last.pt',force_reload=True)

**Comment by svk-man** [comment]
First argument is path to yolov5 repository. For example: '../yolov5'. It`s works for me

**Comment by glenn-jocher** [comment]
@svk-man thank you for sharing your solution. It is always helpful to have multiple solutions available since different users may experience different issues. We appreciate the time you took to provide this information and hope it helps other users who might encounter this issue. Please let us know if you have any other questions or concerns.

**Comment by mondalanindya** [comment]
It doesn't work with yolov8.

**Comment by glenn-jocher** [comment]
@mondalanindya hello,

YOLOv5 is a specific object detection model architecture. As such, it is not compatible with YOLOv8 as that is not a recognized version of YOLO.

If you are having issues with YOLOv8, we suggest checking the documentation or support channels for that specific version.

If you have any other questions or concerns, please feel free to let us know.

Best regards.

**Comment by Yuri-Njathi** [comment]
In my code I have a folder structure:
folder
├── main.py
├── model.pt
├── yolov5/

this line in main.py works 
`model = torch.hub.load(r'yolov5', 'custom', path=r'model.pt', source='local')`

**Comment by glenn-jocher** [comment]
@Yuri-Njathi It's great to hear that the issue has been resolved using the relative path `r'yolov5'` in your main.py file. This allows you to load the custom model using the local path to model.pt without explicitly specifying the path to the yolov5 folder. If you have any further questions or need additional assistance, feel free to ask!

**Comment by zc-alexfan** [comment]
I think the issue is source is expected to be local. Changing to online source from hub works for me.

**Comment by pderrenger** [comment]
Correct—using the GitHub source avoids the local hubconf.py; for fully offline or packaged use, export your YOLOv5 weights and load them directly instead of torch.hub: python export.py --weights last.pt --include onnx,torchscript; see the Ultralytics Docs for details.
