### ISSUE TITLE
YOLOv8 on NVIDIA DeepStream

### ISSUE THREAD

**Issue by marcoslucianops** [ultralytics/yolov5#10848]
https://github.com/ultralytics/ultralytics/issues/676

**Comment by glenn-jocher** [comment]
@marcoslucianops hey there! Thanks for reaching out. YOLOv8 isn't maintained by Ultralytics, and if you're using DeepStream, I'd recommend checking out the official NVIDIA DeepStream documentation for the most up-to-date information. Feel free to browse our YOLOv5 documentation at https://docs.ultralytics.com/yolov5/ for more details on using YOLOv5 with DeepStream. If you have any YOLOv5-related questions, feel free to ask!
