### ISSUE TITLE
How do I enable debug logging during training?

### ISSUE THREAD

**Issue by sstainba** [ultralytics/yolov5#10856]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am re-training a model on a dataset I have used many times before.  However, lately, with both Yolov5 and v8, the training freezes at seemingly random epochs.  All GPU resources are released and the docker engine has to be restarted.  I'd like to enable logging so I can see what's happening.

### Additional

Using official docker images on Windows/WSL2

**Comment by glenn-jocher** [comment]
@sstainba hi there! To enable debug logging during training, you can use the `--debug` flag with the `train.py` script. This will provide detailed information during training, which can help diagnose the freezing issue you're experiencing.

Hope this helps! Let me know if you have further questions.
