### ISSUE TITLE
can i use qualcommGPU for yolov5 instead of nvidia cuda?? 

### ISSUE THREAD

**Issue by wofvh** [ultralytics/yolov5#10857]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hi i rly appreciate for using yolo v5 and im trying to use yolo v5 for the RB5(robot system) but is it possible use qualcomm GPU process instead of nvidia cuda ?? thanks

**Comment by glenn-jocher** [comment]
@wofvh hi there! Thanks for reaching out and for your interest in using YOLOv5. The YOLOv5 codebase primarily relies on NVIDIA CUDA for GPU acceleration. While it's not directly compatible with Qualcomm GPUs, I recommend exploring potential alternatives and optimizations for your RB5 system. If you have any further questions or need assistance with YOLOv5, feel free to ask. Good luck with your project!
