### ISSUE TITLE
saving the title headings for the output from the YOLOV5 detect.py results

### ISSUE THREAD

**Issue by Symbadian** [ultralytics/yolov5#10859]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi @glenn-jocher/ all technical experts,

is there anyway to get the heading of the result type saved as well in the output files?

for example:

epoch | loss | acc | val_loss | val_acc
| | | |

Currently, in the save files the data is presented as the example below without headings in .txt format
0 1.64137483 0.27450982 0.8043378 0.46153846

I tried --save-txt with save --save-conf but none is presenting the headings for the processing results...

I am trying to do a basic decision process but these bits are not available!

Thanx for responding and acknowledging my digital presence, really appreciate this!

**Comment by glenn-jocher** [comment]
@Symbadian hi there! 👋 You can specify the `save-txt` flag in `detect.py` to save results to `.txt` files where each row contains `[class, x_center, y_center, width, height, confidence]`. Unfortunately, headings are not saved with the results. You could manually add headings during processing or use the JSON format which includes class labels. For more details, please check the [Ultralytics Docs](https://docs.ultralytics.com/yolov5/). Thank you for your understanding and contribution!
