### ISSUE TITLE
Modify Model

### ISSUE THREAD

**Issue by Rongkangqi** [ultralytics/yolov5#10852]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to modify the output of the model. Keep only one layer of output and delete the last fusion part, that is, delete the red box and output it in blue output. What part of the program do I need to modify?
![image](https://user-images.githubusercontent.com/52807195/215313189-10d2ba59-dbd0-4fe8-92f1-5fb0560f0a8d.png)

**Comment by Rongkangqi** [comment]
This network visualization is an onnx file exported by yolov5s.

**Comment by glenn-jocher** [comment]
@Rongkangqi hi there! To modify the output of the YOLOv5 model, you can navigate to the `models/yolov5s.yaml` file. You can adjust the `nc` (number of classes) and `nl` (number of detection layers) parameters to modify the output layers. Feel free to visit the [Ultralytics Docs](https://docs.ultralytics.com/yolov5/) for more detailed information. Good luck!
