### ISSUE TITLE
About adding a new class to yolo_v5 model

### ISSUE THREAD

**Issue by estheroratemstet** [ultralytics/yolov5#10850]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I add a new class to yolo_v5 model , 
I created new data as needed with my new category,
It's just that the pictures that include my new category, include in their content categories that already exist in Yolo, and they have no labels.
I have only labels from my category on the images.
for examples: 
In my dataset , images includes people and my category , and in the label only the position of my category
Could it be problematic to train the model again on this my dataset and the original dataset?
thanks for a reply

**Comment by glenn-jocher** [comment]
@estheroratemstet hi there! You can certainly train the model with your new dataset and the original dataset. However, it's important to ensure that your new category is properly labeled in the dataset. Also, be mindful of class imbalance and make sure to have enough annotated images for your new category. Good luck with your training! For more details, you can check out the Ultralytics Docs.
