### ISSUE TITLE
how to predict on same data from two models of different category

### ISSUE THREAD

**Issue by sm2607** [ultralytics/yolov5#10869]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Suppose I have 1 model_1 which has class A and Class B, model_2 has class C
One test dataset of images, which has object from all 3 class(i.e. A,B,C) . How I can predict all 3 class in dataset using knowledge of both models( model_1 and model_2)

**Comment by scientificCommunity** [comment]
same question

**Comment by glenn-jocher** [comment]
@scientificCommunity hi there! To predict all classes A, B, and C in your dataset using both model_1 and model_2, you can simply run inference on each image using both models and then combine the results. You can refer to the Ultralytics Docs for more in-depth information on how to run inference using YOLOv5. Let me know if you need further assistance!

**Comment by scientificCommunity** [comment]
> @scientificCommunity hi there! To predict all classes A, B, and C in your dataset using both model_1 and model_2, you can simply run inference on each image using both models and then combine the results. You can refer to the Ultralytics Docs for more in-depth information on how to run inference using YOLOv5. Let me know if you need further assistance!

thank you for helping me！ @glenn-jocher

**Comment by glenn-jocher** [comment]
@scientificCommunity you're welcome! Feel free to reach out if you have any other questions. Happy to help! 😊
