### ISSUE TITLE
Extracting Yolo cords and classes from a prediction model

### ISSUE THREAD

**Issue by kappa1996** [ultralytics/yolov5#10863]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

I hope I'm in the right place, I trained my model, now I want to predict its operation on some photos, I save the photos in exp 13 etc. but I would need the cords yolo label as I could do to save them thank you very much

### Environment

yolo v5- master 
windosw 10 
 python 3.90

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@kappa1996 hi there! To extract bounding box coordinates and class labels from your YOLOv5 model predictions, you can use the `model`'s `predict` method and then access the `xyxy` attribute of the resultant `results` object for the coordinates, and the `pred` attribute for the class labels. Here's an example:
```python
results = model(img)  # Replace img with your input data
boxes = results.xyxy  # Bounding box coordinates
labels = results.pred  # Class labels
```
For more details on using the YOLOv5 model for inference, you can refer to the [Ultralytics Docs](https://docs.ultralytics.com/yolov5/). Let me know if you have any other questions!
