### ISSUE TITLE
Can't change the activation function in classify mode

### ISSUE THREAD

**Issue by elenabettella** [ultralytics/yolov5#10861]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

I changed the activation function in the file models/common.py but when I print the model it still shows the SiLU function.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@elenabettella hi there! Thanks for reaching out. It sounds like you're trying to change the activation function in classify mode but are encountering issues. Have you tried specifying the desired activation function directly in your config or YAML file? This might help override the default setting in models/common.py. If you have any specific details on your configuration and reproduction steps, that would be very helpful. Let me know if you need further assistance!
