### ISSUE TITLE
How do deal with large but thin objects?

### ISSUE THREAD

**Issue by haimat** [ultralytics/yolov5#10864]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

What is the general approach / best practice when it comes to detect large but very thin objects with YOLOv5?
See for example the following image:

![image](https://user-images.githubusercontent.com/6633976/215556980-2a148b33-888f-4f67-a2e4-7f247165c672.png)

Is it better for the model to label these objects with one large rectangle, as in the screenshot above, or rather with some small rectangles in a row?

**Comment by halskov** [comment]
Have you looked into the ability to annotate with polygons and use the segment training/detection? 

Here is a research paper for inspiration: https://www.researchgate.net/figure/The-overall-architecture-of-the-detection-network-based-on-YOLOv5_fig2_358999764

**Comment by haimat** [comment]
@halskov Thanks for the link to that paper, which is indeed quite a similar use case as ours. However, as far as I can tell that paper does not answer my question whether YOLOv5 performs better with training images based on large rectangles for each object or rather small rectangles in a row for each object. Or have I missed that part?

**Comment by JustasBart** [comment]
Hi @haimat I've recently teased the idea of [#624](https://github.com/ultralytics/ultralytics/issues/624) which would very likely benefit you a lot in this case...

However, currently I don't think that there is much that you could do to specifically deal with this issue other than perhaps mess about with specific augmentations etc...
But I don't think that there is like a flag or anything that might directly help you out, I would recommend using the Rectangular input (**--rect**) flag for this to avoid horizontal squishing but that's as far as I can help you.

Good luck! :rocket:

**Comment by haimat** [comment]
@JustasBart Thanks for your input - your feature request would really by a nice additon to the YOLO repo.
From your experience, do you now whether it would be better to use one large vs. some small rectangle(s)?

**Comment by JustasBart** [comment]
@haimat I would definitely use big bounding boxes in that case opposed to using a lot of small ones.
The reason for that is that the smaller bounding boxes would in my experience be a lot easier to get false positives on as they'd carry very little information about your actual object that you are trying to detect. That is if you break your object down into small pieces for one it's not really your object anymore but for two it's way easier to mistake the small segments now with just random (non-scratch like) things.

However, in addition to this I would also look for a way to augment the images to have a random +-180 degree rotation augmentation for maybe 5 to 10 images of your data (That is 5 images are now worth either 25 or 50 images but with random rotation applied). Be aware that the yolov5 .hyp rotation augmentation will likely do you no good #10841...

And perhaps don't go too crazy on your regular augmentations, I would use something similar to this:
```
fl_gamma: 0.0  # focal loss gamma (efficientDet default gamma=1.5)
hsv_h: 0.015  # image HSV-Hue augmentation (fraction)
hsv_s: 0.5  # image HSV-Saturation augmentation (fraction)
hsv_v: 0.3  # image HSV-Value augmentation (fraction)
degrees: 0.0  # image rotation (+/- deg)
translate: 0.1  # image translation (+/- fraction)
scale: 0.2  # image scale (+/- gain)
shear: 1.0  # image shear (+/- deg)
perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
flipud: 0.5  # image flip up-down (probability)
fliplr: 0.5  # image flip left-right (probability)
mosaic: 1.0  # image mosaic (probability)
mixup: 0.0  # image mixup (probability)
copy_paste: 0.0  # segment copy-paste (probability)
```
Ultimately though you'll just have to play around and see what works best for your data (It also depends on how much data you have in the first place) but one of the things that you can do is to set aside a relatively small testing dataset ~(100 train / 30 val) to quickly iterate through some of the options first and then once you find a suitable setup do the full training run. Definitely try out the small versus the medium models (p5) (That is the 640x640 ones) and I would highly recommend using the **--rect** setup as mentioned before.

I hope any of this is of any use to you, good luck! :rocket:

**Comment by haimat** [comment]
@JustasBart Thank you very much for your detailed answer. Your point regarding large vs. smaller bounding boxes sounds reasonable and makes sense. One question on that though: When you look at my screenshot above then you can see that in such a caes much more of the rectangle is actually background, not the object. Wouldn't the model get quite "confused" during training, if it sees so many similar areas within both the background and as part of the object rectangles?

**Comment by JustasBart** [comment]
@haimat Yes, the data isn't ideal for the bounding boxes, but I'm fairly certain that it would work just fine. I've been a part of multiple projects that had similar-looking data and the models performed just fine on the data. But again I would recommend manually augmenting in some rotated images to help it out on generalising on your scratch data from 'any' angle.

And once again you can always set aside a small enough dataset and perform a few quick tests to make sure that you're happy.

Best of luck! :rocket:

**Comment by haimat** [comment]
@JustasBart Thanks you very much!
