### ISSUE TITLE
Support for YOLOv5 Albumentations on Segmentation for Crops, etc.

### ISSUE THREAD

**Issue by sarmientoj24** [ultralytics/yolov5#10860]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

It seems like augmentations such as rotation (`RandomRotate90`, crops (`RandomSizedBBoxSafeCrop`), etc. are not "supported" yet by the segmentation. When I tried adding these augmentations in `utils > augmentations.py > Albumentations`

```
A.RandomResizedCrop(height=size, width=size, scale=(0.8, 1.0), ratio=(0.9, 1.11), p=0.1),
A.RandomRotate90(p=0.05),
```

the metrics are getting worse on the masks but the boxes are okay. Will there be a support for this soon?

Screenshot  
- gray/white: no augs
- blue: with rotate90
- red: randomresizedcrop
- blue-green: randomsizedbboxsafecrop
![image](https://user-images.githubusercontent.com/8830319/215494076-965d7910-f095-4ac4-9c3b-16290943d67a.png)

**Comment by glenn-jocher** [comment]
@sarmientoj24 hi there! Thanks for reaching out. Currently, YOLOv5 supports augmentations for bounding boxes, but not yet for masks in the segmentation task. Our team is continuously working on improvements, so stay tuned for updates. Let me know if you need help with anything else!
