### ISSUE TITLE
Is possible use 60FPS camera?

### ISSUE THREAD

**Issue by Yolobeginner** [ultralytics/yolov5#10865]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, Everyone , I use Logitech BRIO 4K HD webcam with yolov5s model.
And found that detect time around 5ms, but felt blurred when webcam moving.
Is possible adjust to 60FPS for this yolov5s model?

**Comment by glenn-jocher** [comment]
@Yolobeginner hello! YOLOv5 itself doesn't handle frame rate adjustments, but you can modify the frame rate of your input video feed or camera outside of YOLOv5. This will involve your camera settings or a video processing library like OpenCV. Keep in mind that higher frame rates can impact detection accuracy if the model is not optimized for it. Good luck!
