### ISSUE TITLE
yolo take about 2 GB of RAM

### ISSUE THREAD

**Issue by sdimantsd** [ultralytics/yolov5#10872]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,
I try to run yolo on jetson nano.
When I load the model it take about 2GB of RAM. Is it normal?
I used to use Yolov4 and it's take less RAM

**Comment by glenn-jocher** [comment]
@sdimantsd hi there,

Thanks for reaching out. YOLOv5 typically uses around 2GB of RAM during model loading, which is normal for our network architecture. It's worth noting that the memory usage can vary based on the specific environment and model configuration.

If you have any further questions or need assistance with YOLOv5 on Jetson Nano, feel free to ask. We're here to help.

Best regards
