### ISSUE TITLE
onnxruntime-gpu TensorrtExecutionProvider

### ISSUE THREAD

**Issue by inuaimi** [ultralytics/yolov5#10876]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, 

I'm running yolov5 in onnxruntime with "TensorrtExecutionProvider" as backend and onnx needs to downcast all int64 to int32 each time the model is loaded. I'm getting the following warning and the operation takes a couple of minutes. 

"Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32."

Is it possible to export yolov5 directly with int32 instead of int64? 

Thanks!

**Comment by glenn-jocher** [comment]
@inuaimi hi there,

Thank you for your question. YOLOv5 uses int64 data type to store weights during training for precision, which requires downcasting to int32 during deployment when using TensorRT. This is a known behavior and currently, there's no direct option to export YOLOv5 with int32 weights. However, the YOLO community and the Ultralytics team are continuously working to enhance the model's compatibility with various deployment frameworks. 

For more information on YOLOv5 deployment and TensorRT, you can refer to the Ultralytics Docs at https://docs.ultralytics.com/yolov5/.

Let me know if there's anything else I can help with.
