### ISSUE TITLE
Visualization using TorchView

### ISSUE THREAD

**Issue by mert-kurttutan** [ultralytics/yolov5#10871]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Extra improved python only visualization tool with [torchview](https://github.com/mert-kurttutan/torchview).

Hi,
I have been experimenting on visualizing models of yolov5 family. It provides customizable visualization of pytorch models.
Features include showing nested modules with dashed lines, or depth limit, and it is very close to plot_model of keras.

One example of `yolovl6` is at the `additional` section.

You can see, for instance, dashed lines representing nested modules,

I saw in other issues that you promoted other visualization tools, e.g. netron. But, these might not be favorable when
* you want python only tool with customization option.

The customization option becomes really useful too manage network that are too large to view.

I guess if you are convinced by the tool, either you can 
* promote it as another tool in addition to the existing ones
* integrate as an optional visualization feature. This might be too much to ask :)

### Use case

It would be really beneficial when debugging yolov5 related codes using different customization options provided in torchview.

### Additional

![model gv (3)](https://user-images.githubusercontent.com/88637659/212528839-389b27be-55fc-4a36-bce3-ed49551c780d.png)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@mert-kurttutan hi there, thanks for sharing this visualization tool! It's great to see the community experimenting with new ways to visualize YOLOv5 models. Your example with the customizable features looks promising.

We're always open to exploring new tools and features that can benefit the YOLO community. I'll review the torchview tool and see how it can complement our existing visualization options.

If you have specific suggestions or examples of how torchview can enhance YOLOv5 model visualization, feel free to share them. Your contribution will definitely help us improve the YOLOv5 experience.

Thanks again for your support and willingness to submit a PR! Your efforts are truly appreciated.
