### ISSUE TITLE
Ultralytics hub ios deploy creates mlmodel just with input 320x192 portrait, whatever I trained.

### ISSUE THREAD

**Issue by Banhalmi** [ultralytics/yolov5#10873]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Ultralytics hub ios deploy creates mlmodel just with input 320x192 portrait, whatever I trained ( trained allready 640x640, 1280x1280).

Is there any step by step description if I can export Yolov5 (or YoloV8 :)) can be used in IOS (IPhone) Vision, and that has input dimesions greater than 320x192, or it is for not portrait, but landscape?
I think, recent IPhones could work on larger images too.
Or if there is not, then I should rather train my model on 320x320 images for faster training, if I would like to use on IPhones?

**Comment by glenn-jocher** [comment]
@Banhalmi hi there! To deploy YOLOv5 on iOS with custom input dimensions, you can find detailed step-by-step instructions in our Ultralytics Docs at https://docs.ultralytics.com/yolov5/. The current default input dimensions for iOS portrait mode are 320x192. However, with custom deployment, you can work with larger image dimensions suitable for recent iPhones. Feel free to retrain your model using larger images for optimal performance on iPhones. If you have any further questions, don't hesitate to ask! 📱
