### ISSUE TITLE
"The _imagingft C module is not installed") error.

### ISSUE THREAD

**Issue by danielsoy** [ultralytics/yolov5#10874]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

File "C:\Users\libro\anaconda3\lib\site-packages\PIL\ImageFont.py", line 44, in __getattr__
    raise ImportError("The _imagingft C module is not installed")

### Environment

YOLOV5
windows 10.
CPU device: Intel Core i3-9100F-16GB ram
Python 3.9.7

### Minimal Reproducible Example

python predict.py --weights yolov5s-cls.pt --source pic_to_infer.PNG

### Additional

Running predict.py from Google Colab, no errors.
Running predict.py from Python 3.9.7 via VSCode, got: The _imagingft C module is not installed.
PIL is already installed from CMD.
No luck trying to install it, from anaconda prompt.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by danielsoy** [comment]
my mistake, sorry.

**Comment by glenn-jocher** [comment]
@danielsoy no worries at all! If you need any further assistance, feel free to ask anytime. Your understanding is much appreciated.
