### ISSUE TITLE
Why is there a problem with my bounding box?

### ISSUE THREAD

**Issue by Henryplay** [ultralytics/yolov5#10878]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi~ ,please help me.
this is my original data
![0](https://user-images.githubusercontent.com/50266021/215995534-097b9128-4f97-43e6-8cb6-0a47ef046659.jpg)

![1](https://user-images.githubusercontent.com/50266021/215995583-da512ff6-e5fd-4e4b-bc0a-c1d765eee640.jpg)
![2](https://user-images.githubusercontent.com/50266021/215995590-f5eb2c60-4050-4f65-8346-172bfd502dde.jpg)
And use the following script to convert it to the format we need
```
def convert2yolo(size, box):
    dw = 1./size[0]
    dh = 1./size[1]
    x = (box[0] + box[1])/2.0
    y = (box[2] + box[3])/2.0
    w = box[1] - box[0]
    h = box[3] - box[2]

    x = x*dw
    w = w*dw
    y = y*dh
    h = h*dh
    return (x,y,w,h)
```

But when I started training，in the `run/train/{folder}`, the bounding box is not suitable for the object, like this
![train_batch0](https://user-images.githubusercontent.com/50266021/215998350-2012bd8e-a131-4b14-a38b-5df6ab160af5.jpg)
![train_batch1](https://user-images.githubusercontent.com/50266021/215998407-70cc3a6a-c676-41fb-b0e8-876e9dda51eb.jpg)
![train_batch2](https://user-images.githubusercontent.com/50266021/215998420-972b067f-8b49-4455-a809-5ed19091e99b.jpg)
Can't completely surround objects

**Comment by ExtReMLapin** [comment]
With no data (raw annotation files) we can't help you

**Comment by Henryplay** [comment]
@ExtReMLapin Sorry, it's my negligence.
