### ISSUE TITLE
Confusion Matrix  logged in cometml has different values compared to confusion matrix logged in run/train/exp?

### ISSUE THREAD

**Issue by nsriniva03** [ultralytics/yolov5#10877]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Confusion Matrix  logged in cometml has different values compared to confusion matrix logged in run/train/exp?

CM logged in comet 
![Screen Shot 2023-01-31 at 7 56 18 PM](https://user-images.githubusercontent.com/83607477/215926132-d5ffa5ce-9f23-4122-9ce6-95543afef13b.png)

CM logged in run/train/exp folder 
![Screen Shot 2023-01-31 at 7 47 00 PM](https://user-images.githubusercontent.com/83607477/215925923-035be1cf-6dbb-4028-8899-ba3d83e5dba7.png)

Ignoring the fact that the CM logged in comet is expressed as percentages. The two confusion matrices are very different. Any insights on it?

Thank you

**Comment by glenn-jocher** [comment]
@nsriniva03 hi there,

Thanks for reaching out! 🌟 It sounds like you're encountering differences in the confusion matrices logged in cometml and run/train/exp. The Ultralytics team is always working to improve the YOLOv5 experience, and we appreciate your feedback.

One potential cause for differing confusion matrices could be the specific configurations or data used when logging each experiment. If you haven't already, you may want to double-check that the input data and settings are consistent between the two environments.

If you need further assistance, please refer to the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/ for detailed information on logging and visualizing metrics. If you have further questions, feel free to ask! 😊
