### ISSUE TITLE
Correct way to set up group convolutions

### ISSUE THREAD

**Issue by Corallo** [ultralytics/yolov5#10883]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, 

I wanted to ask help to replace standard convolutions with group convolution.
I see in the [common.py](https://github.com/ultralytics/yolov5/blob/master/models/common.py#L52) implementation of the Conv class that it is possible to provide the "g" parameter, that I think it is what I am attempting to change.
Is there a way to modify that parameter from the yaml configuration file?

**Comment by glenn-jocher** [comment]
@Corallo hi there,

Thanks for reaching out! Sure, you can configure the group parameter directly from the YAML config file by adding the 'g' parameter to the Conv layer in the 'layers' section. Simply include 'g: X' (where X is the desired number of groups) to achieve group convolutions.

Let me know if you need further assistance with this, and good luck with your implementation!

**Comment by Corallo** [comment]
Do you mean this way?
```
backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [64, 6, 2, 2, g:12]],  # 0-P1/2
```

**Comment by glenn-jocher** [comment]
@Corallo Almost there! The correct way to add the 'g' parameter for group convolutions in the YAML configuration file is as follows:

```yaml
backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [64, 6, 2, 2, g=12]],  # 0-P1/2
```

Feel free to reach out if you have any more questions or need further clarification!
