### ISSUE TITLE
cache dataset every time

### ISSUE THREAD

**Issue by Mahdi-Maaref** [ultralytics/yolov5#10889]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

first of all i truly admire your great work!

when trying to evolve hyperparameters i use --cache 

in training all dataset cache once and yolo start training until the end

but

in --evolve mode for every cycle almost 300 times all dataset cache in ram ? and it waste lots of time

**Comment by alicera** [comment]
Can the --cache speed up your training time without --evolve?

**Comment by Mahdi-Maaref** [comment]
> Can the --cache speed up your training time without --evolve?

definitely

**Comment by glenn-jocher** [comment]
@2022Mahdi thank you for your kind words! 🙏 Yes, using the '--cache' flag can accelerate training time without '--evolve' by caching the entire dataset once. Just run your training command with '--cache' to benefit from this optimization. Let me know if you have any more questions!
