### ISSUE TITLE
YOLOv5 Segmentation - Calculate area of detected objects 

### ISSUE THREAD

**Issue by DoSquared** [ultralytics/yolov5#10882]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I trained YOLOv5 for instance segmentation and ran interference on an output directory. 

The output is a set of images with bounding boxes and detected objects + txt files.

This is an example of the content of txt files:  
0 0.51875 0.443951 0.5125 0.451424 0.50625 0.451424 0.503125 0.455161 0.453125 0.455161 0.428125 0.485054 0.425 0.485054 0.41875 0.492527 0.415625 0.492527 0.415625 0.496263 0.409375 0.503737 0.409375 0.541103 0.4125 0.544839 0.4125 0.563522 0.425 0.578469 0.425 0.585942 0.428125 0.589679 0.428125 0.604625 0.43125 0.608362 0.43125 0.612098 0.434375 0.615835 0.434375 0.619572 0.4375 0.623308 0.4375 0.627045 0.440625 0.630781 0.45 0.630781 0.453125 0.634518 0.45625 0.634518 0.459375 0.630781 0.4625 0.630781 0.465625 0.627045 0.46875 0.627045 0.478125 0.615835 0.503125 0.615835 0.515625 0.600888 0.528125 0.600888 0.53125 0.597152 0.534375 0.597152 0.54375 0.585942 0.55 0.585942 0.553125 0.582205 0.55625 0.582205 0.55625 0.574732 0.559375 0.570996 0.559375 0.556049 0.5625 0.552313 0.5625 0.548576 0.565625 0.544839 0.565625 0.541103 0.56875 0.537366 0.56875 0.53363 0.5625 0.526156 0.5625 0.518683 0.559375 0.514946 0.559375 0.503737 0.55625 0.5 0.55625 0.496263 0.546875 0.485054 0.546875 0.47758 0.54375 0.473844 0.54375 0.470107 0.540625 0.46637 0.540625 0.462634 0.5375 0.458897 0.5375 0.455161 0.534375 0.451424 0.534375 0.447687 0.53125 0.443951 0.782973

I understand the first zero is the name of the class.

1) What are the rest of the numbers? 

2) How can I retrieve the area or coordinates of the detected instance? 

3) if it is not possible to retrieve the area, how can I remove the bounding box from inference and keep only the colored area drawn over the object? 

Thank you very much in advance. 

![image](https://user-images.githubusercontent.com/4492013/216062900-bdaf6561-6b94-4ad4-ab21-0578a5a612de.png)

**Comment by john-tseng-710** [comment]
Hi,

There are many ways to get the size of an enclosed area formed by a bunch of points.
Personally, I prefer using opencv function [cv2.contourArea](https://docs.opencv.org/3.4/d3/dc0/group__imgproc__shape.html#ga2c759ed9f497d4a618048a2f56dc97f1)

```
import numpy as np
import cv2

txt = "0 0.51875 0.443951 0.5125 0.451424 0.50625 0.451424 0.503125 0.455161 0.453125 0.455161 0.428125 0.485054 0.425 0.485054 0.41875 0.492527 0.415625 0.492527 0.415625 0.496263 0.409375 0.503737 0.409375 0.541103 0.4125 0.544839 0.4125 0.563522 0.425 0.578469 0.425 0.585942 0.428125 0.589679 0.428125 0.604625 0.43125 0.608362 0.43125 0.612098 0.434375 0.615835 0.434375 0.619572 0.4375 0.623308 0.4375 0.627045 0.440625 0.630781 0.45 0.630781 0.453125 0.634518 0.45625 0.634518 0.459375 0.630781 0.4625 0.630781 0.465625 0.627045 0.46875 0.627045 0.478125 0.615835 0.503125 0.615835 0.515625 0.600888 0.528125 0.600888 0.53125 0.597152 0.534375 0.597152 0.54375 0.585942 0.55 0.585942 0.553125 0.582205 0.55625 0.582205 0.55625 0.574732 0.559375 0.570996 0.559375 0.556049 0.5625 0.552313 0.5625 0.548576 0.565625 0.544839 0.565625 0.541103 0.56875 0.537366 0.56875 0.53363 0.5625 0.526156 0.5625 0.518683 0.559375 0.514946 0.559375 0.503737 0.55625 0.5 0.55625 0.496263 0.546875 0.485054 0.546875 0.47758 0.54375 0.473844 0.54375 0.470107 0.540625 0.46637 0.540625 0.462634 0.5375 0.458897 0.5375 0.455161 0.534375 0.451424 0.534375 0.447687 0.53125 0.443951 0.782973"
cls, *points, conf = txt.split(" ")
contour = np.array(points, dtype=np.float32).reshape(-1, 2)
area = cv2.contourArea(contour)
print(f"area size: {area}")
```

**Comment by DoSquared** [comment]
> Hi,
> 
> There are many ways to get the size of an enclosed area formed by a bunch of points. Personally, I prefer using opencv function [cv2.contourArea](https://docs.opencv.org/3.4/d3/dc0/group__imgproc__shape.html#ga2c759ed9f497d4a618048a2f56dc97f1)
> 
> ```
> import numpy as np
> import cv2
> 
> txt = "0 0.51875 0.443951 0.5125 0.451424 0.50625 0.451424 0.503125 0.455161 0.453125 0.455161 0.428125 0.485054 0.425 0.485054 0.41875 0.492527 0.415625 0.492527 0.415625 0.496263 0.409375 0.503737 0.409375 0.541103 0.4125 0.544839 0.4125 0.563522 0.425 0.578469 0.425 0.585942 0.428125 0.589679 0.428125 0.604625 0.43125 0.608362 0.43125 0.612098 0.434375 0.615835 0.434375 0.619572 0.4375 0.623308 0.4375 0.627045 0.440625 0.630781 0.45 0.630781 0.453125 0.634518 0.45625 0.634518 0.459375 0.630781 0.4625 0.630781 0.465625 0.627045 0.46875 0.627045 0.478125 0.615835 0.503125 0.615835 0.515625 0.600888 0.528125 0.600888 0.53125 0.597152 0.534375 0.597152 0.54375 0.585942 0.55 0.585942 0.553125 0.582205 0.55625 0.582205 0.55625 0.574732 0.559375 0.570996 0.559375 0.556049 0.5625 0.552313 0.5625 0.548576 0.565625 0.544839 0.565625 0.541103 0.56875 0.537366 0.56875 0.53363 0.5625 0.526156 0.5625 0.518683 0.559375 0.514946 0.559375 0.503737 0.55625 0.5 0.55625 0.496263 0.546875 0.485054 0.546875 0.47758 0.54375 0.473844 0.54375 0.470107 0.540625 0.46637 0.540625 0.462634 0.5375 0.458897 0.5375 0.455161 0.534375 0.451424 0.534375 0.447687 0.53125 0.443951 0.782973"
> cls, *points, conf = txt.split(" ")
> contour = np.array(points, dtype=np.float32).reshape(-1, 2)
> area = cv2.contourArea(contour)
> print(f"area size: {area}")
> ```

Thank you for the reply! I ran the code but got a result of 0.02

I think we need to understand what the output txt from YOLO represents

**Comment by john-tseng-710** [comment]
> > Hi,
> > There are many ways to get the size of an enclosed area formed by a bunch of points. Personally, I prefer using opencv function [cv2.contourArea](https://docs.opencv.org/3.4/d3/dc0/group__imgproc__shape.html#ga2c759ed9f497d4a618048a2f56dc97f1)
> > ```
> > import numpy as np
> > import cv2
> > 
> > txt = "0 0.51875 0.443951 0.5125 0.451424 0.50625 0.451424 0.503125 0.455161 0.453125 0.455161 0.428125 0.485054 0.425 0.485054 0.41875 0.492527 0.415625 0.492527 0.415625 0.496263 0.409375 0.503737 0.409375 0.541103 0.4125 0.544839 0.4125 0.563522 0.425 0.578469 0.425 0.585942 0.428125 0.589679 0.428125 0.604625 0.43125 0.608362 0.43125 0.612098 0.434375 0.615835 0.434375 0.619572 0.4375 0.623308 0.4375 0.627045 0.440625 0.630781 0.45 0.630781 0.453125 0.634518 0.45625 0.634518 0.459375 0.630781 0.4625 0.630781 0.465625 0.627045 0.46875 0.627045 0.478125 0.615835 0.503125 0.615835 0.515625 0.600888 0.528125 0.600888 0.53125 0.597152 0.534375 0.597152 0.54375 0.585942 0.55 0.585942 0.553125 0.582205 0.55625 0.582205 0.55625 0.574732 0.559375 0.570996 0.559375 0.556049 0.5625 0.552313 0.5625 0.548576 0.565625 0.544839 0.565625 0.541103 0.56875 0.537366 0.56875 0.53363 0.5625 0.526156 0.5625 0.518683 0.559375 0.514946 0.559375 0.503737 0.55625 0.5 0.55625 0.496263 0.546875 0.485054 0.546875 0.47758 0.54375 0.473844 0.54375 0.470107 0.540625 0.46637 0.540625 0.462634 0.5375 0.458897 0.5375 0.455161 0.534375 0.451424 0.534375 0.447687 0.53125 0.443951 0.782973"
> > cls, *points, conf = txt.split(" ")
> > contour = np.array(points, dtype=np.float32).reshape(-1, 2)
> > area = cv2.contourArea(contour)
> > print(f"area size: {area}")
> > ```
> 
> Thank you for the reply! I ran the code but got a result of 0.02
> 
> I think we need to understand what the output txt from YOLO represents

From my understanding:
As the output unit of x, y is ratio to image width, height respectively. (Range: 0~1)
Accordingly, the calculated result stands for the area percentage of whole image, which is 0.02(2%).
Now you can convert the unit to pixel square by H\*W\*0.02 if necessary.

**Comment by VimalaKoduru** [comment]
Hi, I have used above script for getting area.
import numpy as np
import cv2

txt = "73 0.795139 0.120312 0.791667 0.121875 0.784722 0.121875 0.774306 0.126563 0.774306 0.128125 0.770833 0.129688 0.770833 0.13125 0.767361 0.132812 0.767361 0.135937 0.763889 0.1375 0.763889 0.146875 0.760417 0.148438 0.760417 0.1625 0.756944 0.164062 0.756944 0.173438 0.753472 0.175 0.753472 0.215625 0.75 0.217187 0.75 0.220313 0.746528 0.221875 0.746528 0.223438 0.743056 0.225 0.739583 0.225 0.732639 0.221875 0.732639 0.220313 0.729167 0.220313 0.715278 0.214062 0.715278 0.210938 0.711806 0.209375 0.704861 0.209375 0.701389 0.207813 0.701389 0.23125 0.697917 0.232812 0.697917 0.60625 0.701389 0.607813 0.701389 0.640625 0.715278 0.646875 0.715278 0.648438 0.71875 0.65 0.71875 0.651563 0.729167 0.65625 0.729167 0.657812 0.739583 0.6625 0.743056 0.6625 0.753472 0.667188 0.760417 0.667188 0.763889 0.66875 0.826389 0.66875 0.829861 0.670313 0.840278 0.670313 0.84375 0.671875 0.84375 0.673437 0.840278 0.675 0.840278 0.676562 0.833333 0.679688 0.833333 0.68125 0.829861 0.682813 0.881944 0.682813 0.885417 0.684375 0.979167 0.684375 0.979167 0.123438 0.975694 0.121875 0.930556 0.121875 0.927083 0.120312"

cls, *points, conf = txt.split(" ")
contour = np.array(points, dtype=np.float32).reshape(-1, 2)
area = cv2.contourArea(contour)
area = area * 1600 * 720
print(f"area size: {area}")

But end up with below issue:
ValueError: cannot reshape array of size 127 into shape (2)

Can anyone please let me know, how to overcome this. Thanks in advance.

**Comment by glenn-jocher** [comment]
@VimalaKoduru the error you are encountering is due to the mismatch between the size of the input array and the target shape in the `np.reshape` function. The input file has 127 numbers, which cannot be reshaped to fit a 2-dimensional array.

To calculate the area of the detected instance, we can parse the text to separate the x, y coordinates and then use OpenCV's `cv2.contourArea` function. However, since the provided input array doesn't seem to be directly interpretable as a valid polygon for contour area calculation, you might need to preprocess or reformat the input data.

Once we have the properly formatted polygon coordinates, we can calculate the area using `cv2.contourArea` and then convert the output to the desired units using the image dimensions.

If you still encounter issues, please provide more context or detail about the input data or how it's obtained. This will help to better understand the issue and provide an appropriate solution.
