### ISSUE TITLE
Convert the results of segment/predict.py to COCO Format 

### ISSUE THREAD

**Issue by MElHuseyni** [ultralytics/yolov5#10881]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am building an API for instance segmentation model, currently `segment/predict.py` can give a lables in text format, how can I can interpret these labels to COCO format or an integratable json with flask like this sample: 

`[{'class': 0,
  'confidence': 0.8197850585,
  'name': 'person',
  'xmax': 1159.1403808594,
  'xmin': 750.912902832,
  'ymax': 711.2583007812,
  'ymin': 44.0350036621},
 {'class': 0,
  'confidence': 0.5667674541,
  'name': 'person',
  'xmax': 1065.5523681641,
  'xmin': 116.0448303223,
  'ymax': 713.8904418945,
  'ymin': 198.4603881836},
 {'class': 27,
  'confidence': 0.5661227107,
  'name': 'tie',
  'xmax': 516.7975463867,
  'xmin': 416.6880187988,
  'ymax': 717.0524902344,
  'ymin': 429.2020568848}]`

**Comment by glenn-jocher** [comment]
@MElHuseyni to convert the output of `segment/predict.py` to COCO format, you can use the `xyxy` output to generate the required JSON output. You may refer to the `--save-txt` command-line option or simply modify the `detect.py` script to output results in the desired JSON format. You can also refer to the Ultralytics Docs for information about formats at https://docs.ultralytics.com/yolov5/. Let us know if you need further assistance with this integration.
