### ISSUE TITLE
Is there a way to change model output according to the user's input text

### ISSUE THREAD

**Issue by ThiwankiDias** [ultralytics/yolov5#10886]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi I am begginer to YOLOv5 algorithm. I just want to know is there a way to change the output name of bounding box accoding to the user's input for only one class in my model. like an example

**my dataset config file :** 

train: /dataset/images/train 
val:  /dataset/images/validation
nc: 2
names: ['elephant', 'lion'] 

then I need to change only the elephant class if the user input as 'big' then the elephant class name should change in to 'high risk' in dataset configuration file and also if the user input as 'small' then the elephant class name should change in to 'low risk' in dataset configuration file. and according to that, model output also should change. If you can please help me with a coding example. 

Thank you so much.

**Comment by glenn-jocher** [comment]
@ThiwankiDias hi there, 

Great to hear you're exploring YOLOv5! 🚀 This kind of dynamic class renaming can indeed be implemented with a few tweaks in the code. You can use a simple conditional statement in the post-processing steps of your inference script to change the class name based on the user input.

You can refer to the documentation for more information on how to customize post-processing to modify the class names in the model output. Additionally, you may also find it helpful to look into Python's `input()` function for taking user input and using it to change the class names dynamically.

I hope this helps get you started! If you have further questions or need more specific guidance, feel free to ask. Good luck with your project!
