### ISSUE TITLE
Understanding Focal Loss Gamma

### ISSUE THREAD

**Issue by gd1925** [ultralytics/yolov5#10887]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi everyone!
I wish to improve the performance of my yolov5 model on custom dataset. 
I am trying to understand and use Focal loss for my custom dataset case with multiclass detection and imbalanced dataset. 
I started increasing the parameter : fl_gamma in hyp.scratch-low.yaml with increments of 0.5. so gamma 0 (default), 0.5, 1.0, 1.5 and 2.0. The overall mAP(50:95) for each of these values I observed are as follows: 

- 0 : 0.3
- 0.5 : 0.00159
- 1.0 : 0.28
- 1.5 : 0.27
- 2 : 0.191

My question is, why does the performance suddenly drop (mAP) for fl_gamma 0.5? It increases thereafter but never reaching the fl_gamma mAP. I thought this was an interesting behavior so I wanted to understand this behaviour and basically how to analyse and improve this performance more. 

Looking forward to tips and insights from you all! Thank you in advance!!

**Comment by Andulka97** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.
> 
> ### Question
> Hi everyone! I wish to improve the performance of my yolov5 model on custom dataset. I am trying to understand and use Focal loss for my custom dataset case with multiclass detection and imbalanced dataset. I started increasing the parameter : fl_gamma in hyp.scratch-low.yaml with increments of 0.5. so gamma 0 (default), 0.5, 1.0, 1.5 and 2.0. The overall mAP(50:95) for each of these values I observed are as follows:
> 
> * 0 : 0.3
> * 0.5 : 0.00159
> * 1.0 : 0.28
> * 1.5 : 0.27
> * 2 : 0.191
> 
> My question is, why does the performance suddenly drop (mAP) for fl_gamma 0.5? It increases thereafter but never reaching the fl_gamma mAP. I thought this was an interesting behavior so I wanted to understand this behaviour and basically how to analyse and improve this performance more.
> 
> Looking forward to tips and insights from you all! Thank you in advance!!
> 
> ### Additional
> _No response_

**Comment by michael-mayo** [comment]
Are you keeping everything identical except for the focal loss gamma when running these experiments? Are these the results of a single run or an average of a few runs with different global seeds fixed each time?

**Comment by glenn-jocher** [comment]
@michael-mayo the observed irregularity could stem from myriad factors, for instance, random initialization, recurrent training, class imbalance, label noise, or simply noise in the evaluation procedure. It is generally a good practice to perform multiple runs and average the results to gain a stable estimate of performance. Regarding class imbalance, the gamma value controls the rate at which easy examples are down-weighted, demonstrating complex interactions with class imbalance. Studying focal loss and its effects in detail can be beneficial and possibly invaluable in this scenario, as the specifics of your dataset and model can greatly influence the focal loss performance.

**Comment by MartijnPeterVanLeeuwen** [comment]
Gamma values between 0 and 1 can lead to training instability due to division by 0 in the Focal loss derivative. This could be a potential explanation for the difference in model behavior. 

You can find more info on this instability in this paper : https://openreview.net/forum?id=eCYActnGbu

**Comment by pderrenger** [comment]
Suggested reply: “Thanks for sharing the paper. In YOLOv5, though, focal loss is implemented as BCEWithLogitsLoss scaled by the modulating factor `(1 - p_t)^gamma`, so `fl_gamma` values between 0 and 1 do not by themselves introduce a divide-by-zero in this repo; the sharp drop at `0.5` is more likely run-to-run variance or dataset sensitivity, so if you revisit it, please retest on the latest YOLOv5, average a few fixed-seed runs per gamma, and compare per-class metrics as well as mAP. See the [Ultralytics Focal Loss glossary](https://www.ultralytics.com/glossary/focal-loss) for background.” ([raw.githubusercontent.com](https://raw.githubusercontent.com/ultralytics/yolov5/master/utils/loss.py))

**Comment by MartijnPeterVanLeeuwen** [comment]
Hi, just for clarification, division by zero does not occur within the Focal loss itself, but in its derivative whenever the model output is approximately equal to the ground truth.  In this paper, the BCEWithLogitsLoss was also used to demonstrate this instability. It's of course possible that something else is contributing to the difference in model behavior, but I just wanted to state that it should not be ruled out too quickly.

**Comment by pderrenger** [comment]
Thanks for clarifying — that’s a fair distinction, and it shouldn’t be dismissed outright; in YOLOv5 the best way to verify whether that edge-case gradient behavior is the driver here is to retest on the latest code, keep seeds fixed, and compare the train/val cls and obj loss curves over several runs, since a repeatable collapse only at `fl_gamma=0.5` would point to dataset-specific optimization sensitivity rather than a general focal-loss effect.
