### ISSUE TITLE
Tutorial about pretrained weights

### ISSUE THREAD

**Issue by saitarslanboun** [ultralytics/yolov5#1089]
## ❔Question
Hi!

Thanks for your brilliant work!

I would like to reproduce your work from scratch. Do you have any tutorial somewhere, where you explain about pretraining backbones?

**Comment by glenn-jocher** [comment]
@saitarslanboun all tutorials are available at https://docs.ultralytics.com/yolov5

**Comment by saitarslanboun** [comment]
Thank you @glenn-jocher! But unfortunately I could not see how you train the backbone. There are tutorials about training object detection part. That is right. But you keep retrained weights of backbones in Google Drive. I am curious about how you pretrain the backbones, not object detection itself.

**Comment by glenn-jocher** [comment]
@saitarslanboun we don't train 'backbones', we train object detection and classification models.

**Comment by saitarslanboun** [comment]
I mean, you do not pretrain your model backbones with ImageNet first, and continue with object detection?

**Comment by glenn-jocher** [comment]
@saitarslanboun no. All of the official YOLOv5 models are trained on COCO starting from scratch. No pretrained weights are used.

**Comment by saitarslanboun** [comment]
Great! Thanks,
