### ISSUE TITLE
Trainig data distribution colormaps 

### ISSUE THREAD

**Issue by SetarehMed** [ultralytics/yolov5#10895]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How can I find the number of the most frequent and least frequent number of the data , shown in the trainig data distribution map ? I mean what is the quantity rcorreponding to the most red points in the data distribution [maps?]()
![labels](https://user-images.githubusercontent.com/54040415/216409464-c73f91f4-a43a-4bbc-8214-a6e4db0b25b1.png)

**Comment by glenn-jocher** [comment]
@SetarehMed hi there! 👋 To find the most and least frequent classes in your training data distribution map, you can utilize the class distribution and respective counts available as text within your training stats. You can find out more about the class distribution in the [Ultralytics Docs](https://docs.ultralytics.com/yolov5/). Cheers!
