### ISSUE TITLE
Results saved to runs\detect\exp6 

### ISSUE THREAD

**Issue by ssharmak** [ultralytics/yolov5#10891]
Where to serach for this result "Results saved to runs\detect\exp6"

**Comment by glenn-jocher** [comment]
@ssharmak you can find the detection results in the runs/detect/exp6 folder. You can navigate to this folder in your file explorer or access it programmatically using the file path in your code. For more detailed information on using YOLOv5, you can refer to the Ultralytics Docs at https://docs.ultralytics.com/yolov5/. Let me know if you need further assistance!

**Comment by SweetyXt** [comment]
Have you solved this problem? I've had this issue recently as well·

**Comment by glenn-jocher** [comment]
@SweetyXt yes, if you're encountering similar issues, a common solution is to ensure your environment is correctly set up and your dataset is properly formatted. Could you provide more details on the issue you're facing? This will help us offer a more specific solution. 😊
