### ISSUE TITLE
Interpreting rotate in the hyperparameters file?

### ISSUE THREAD

**Issue by sarmientoj24** [ultralytics/yolov5#10896]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How do you set to limit a rotation of say, 90 degrees? It seems like a float of +/- rotation but does not indicate whether it's radians, degrees, etc.

**Comment by JustasBart** [comment]
Hi @sarmientoj24 looking at the default hyp file **/data/hyps/hyp.scratch-low.yaml** it says:

`degrees: 0.0  # image rotation (+/- deg)`

However, if you've seen issues such as #10841 and #10639 and a few others, I'm not convinced that the rotation augmentation works at all (At least not for Object Detection) but feel free to give it a try and see what you can come up with!

Good luck :rocket:

**Comment by sarmientoj24** [comment]
@JustasBart so if I need a [-90, 90] degree rotation, it should be 90?

**Comment by JustasBart** [comment]
@sarmientoj24 I think so. At least that's what that comment **# image rotation (+/- deg)** seems to indicate. But I would highly advice if you were to then preview your training batch images to see if the labels seem ok.
