### ISSUE TITLE
Multiplication between two tensors coming from differents levels

### ISSUE THREAD

**Issue by hariouat** [ultralytics/yolov5#10892]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

![20230201_105653(1)](https://user-images.githubusercontent.com/117453280/216291416-2993503f-b20d-4510-867d-fa6e12eaa613.jpg)
Hello, 

I'm trying to add a new block in yolov7. i want to multiply the output of this block with the previous layer coming from other layer.

I used mul(previous and output), but how can modify in order to precise this two layers in yaml file.

Thanks in advance.

**Comment by glenn-jocher** [comment]
@hariouat hello,

To perform multiplication between tensors from different levels, you can explicitly reference the layers in the `yaml` file using the `from` attribute. For instance, you can specify the previous layer using `from: -2` to refer to the layer at index -2 in the model architecture.

Here is an example of how you might modify the `yaml` file to achieve this:
```yaml
- mul:
    from: -2  # Reference to the layer from a specific index
```

I hope this helps! If you have any further questions, feel free to ask.
