### ISSUE TITLE
tf.CombinedNonMaxSuppression with float32 valid_detections

### ISSUE THREAD

**Issue by webfrank** [ultralytics/yolov5#10897]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Export tflite model using float32 for all outputs

### Use case

I need to use the trained model inside a Meraki camera which accept only tflite with NMS with all outputs as float32.

I changed the export.py script to output float32 instead of float16 but the valid_detections remains int.

Is it possible to convert it to float32?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@webfrank hi there! Thanks for reaching out. While YOLOv5 currently supports exporting to float32 for most outputs, the valid_detections output remains as int for compatibility with the TF framework and associated ops. You can still use the model with the Meraki camera as TF Lite automatically converts between int and float as needed. If you have any other questions, feel free to ask or refer to our [Ultralytics Docs](https://docs.ultralytics.com/yolov5/). Good luck with your project!

**Comment by webfrank** [comment]
Hi, although TFLite makes the conversion, the camera checks the output
types and if not all float32 it doesn’t load the model.

Il giorno mer 15 nov 2023 alle 15:19 Glenn Jocher ***@***.***>
ha scritto:

**Comment by glenn-jocher** [comment]
Understood, @webfrank. Thanks for the clarification. I apologize for any inconvenience. At the moment, YOLOv5 does not natively support exporting valid_detections as float32. If this feature becomes a priority, the Ultralytics team will consider implementing it in the future. Thank you for your understanding, and please feel free to reach out if you have any other questions or concerns. Good luck with your project!
