### ISSUE TITLE
Jetson nano (on Jetpack 4.4) - freeze

### ISSUE THREAD

**Issue by gkomix88** [ultralytics/yolov5#109]
Hi, 
I had configured fixed all the output errors from Jetson nano running Jetpack 4.4
However, when I tried to run the following command:

python3 detect.py --source ./inference/images/ --weights ./weights/yolov5s.pt --conf 0.4

The jetson nano output the following and freezed.
---
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.4, device='', fourcc='mp4v', half=False, img_size=640, iou_thres=0.5, output='inference/output', save_txt=False, source='./inference/images/', view_img=False, weights='./weights/yolov5s.pt')
Using CUDA device0 _CudaDeviceProperties(name='NVIDIA Tegra X1', total_memory=3956MB)
---

Additional installations required to fix Jetson errors are below:
# for OSError: libmpi_cxx.so.20
sudo apt-get install openmpi-bin
# ImportError: libopenblas.so.0
sudo apt-get install libopenblas-dev

pip3 install Pillow==2.2.2
sudo apt install libfreetype6-dev
pip3 install matplotlib
pip3 install torchvision

-----

Is there is anything wrong on the configuration? Can anyone able to run Yolov5 on Jetson Nano (with Jetpack 4.4) successfully? Hope can shared the additional installation and configuration here.

Thanks.

**Comment by glenn-jocher** [comment]
@gkomix88 see https://github.com/ultralytics/yolov5/issues/53 perhaps.

**Comment by 123456789mojtaba** [comment]
> Hi,
> I had configured fixed all the output errors from Jetson nano running Jetpack 4.4
> However, when I tried to run the following command:
> 
> python3 detect.py --source ./inference/images/ --weights ./weights/yolov5s.pt --conf 0.4
> 
> ## The jetson nano output the following and freezed.
> ## Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.4, device='', fourcc='mp4v', half=False, img_size=640, iou_thres=0.5, output='inference/output', save_txt=False, source='./inference/images/', view_img=False, weights='./weights/yolov5s.pt')
> Using CUDA device0 _CudaDeviceProperties(name='NVIDIA Tegra X1', total_memory=3956MB)
> Additional installations required to fix Jetson errors are below:
> 
> # for OSError: libmpi_cxx.so.20
> sudo apt-get install openmpi-bin
> 
> # ImportError: libopenblas.so.0
> sudo apt-get install libopenblas-dev
> 
> pip3 install Pillow==2.2.2
> sudo apt install libfreetype6-dev
> pip3 install matplotlib
> pip3 install torchvision
> 
> Is there is anything wrong on the configuration? Can anyone able to run Yolov5 on Jetson Nano (with Jetpack 4.4) successfully? Hope can shared the additional installation and configuration here.
> 
> Thanks.

Hi.I implement it in jetson nano but I don't have your problem. I have another.
pip3 install matplotlib doesn't work for me.

**Comment by gkomix88** [comment]
> > Hi,
> > I had configured fixed all the output errors from Jetson nano running Jetpack 4.4
> > However, when I tried to run the following command:
> > python3 detect.py --source ./inference/images/ --weights ./weights/yolov5s.pt --conf 0.4
> > ## The jetson nano output the following and freezed.
> > ## Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.4, device='', fourcc='mp4v', half=False, img_size=640, iou_thres=0.5, output='inference/output', save_txt=False, source='./inference/images/', view_img=False, weights='./weights/yolov5s.pt')
> > Using CUDA device0 _CudaDeviceProperties(name='NVIDIA Tegra X1', total_memory=3956MB)
> > Additional installations required to fix Jetson errors are below:
> > # for OSError: libmpi_cxx.so.20
> > sudo apt-get install openmpi-bin
> > # ImportError: libopenblas.so.0
> > sudo apt-get install libopenblas-dev
> > pip3 install Pillow==2.2.2
> > sudo apt install libfreetype6-dev
> > pip3 install matplotlib
> > pip3 install torchvision
> > Is there is anything wrong on the configuration? Can anyone able to run Yolov5 on Jetson Nano (with Jetpack 4.4) successfully? Hope can shared the additional installation and configuration here.
> > Thanks.
> 
> Hi.I implement it in jetson nano but I don't have your problem. I have another.
> pip3 install matplotlib doesn't work for me.

@123456789mojtaba - You can refer to https://forums.developer.nvidia.com/t/jetson-nano-how-can-install-matplotlib/75132

**Comment by 123456789mojtaba** [comment]
hi.
how did you install libraries? did you install all of them?

**Comment by muhk01** [comment]
i was sucessfully run on jetson nano, i got around 4-10fps depending on how many bounding boxes present in the frame, setup i just did only build pytorch 1.5 manually from sources and install its prerequisites.

**Comment by seanavery** [comment]
@gkomix88 I am working on a lightweight TensorRT and Numpy implementation for inference on Jetson Nano. If useful, you can find the repo here: https://github.com/SeanAvery/yolov5-tensorrt.

**Comment by gkomix88** [comment]
@SeanAvery Hi, thanks for sharing, will try to contribute too.
