### ISSUE TITLE
Convert .pt to .onnx

### ISSUE THREAD

**Issue by VYRION-Ai** [ultralytics/yolov5#10901]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

for old yolov5 (may be 5 month ago) i convert best.pt to best.onnx 
and it works well and then i update my best (week ago) and convert it to best.onnx
the old best.onnx  was running on onnxruntime 1.7.0
but when i use the new best.onnx  onnruntime i got error
`WinRT information: Failed to load model with error: Unknown model file format version`
but if i use latest onnxruntime it works . the problem is i work on code depend on old onnxruntime (1.7.0) becuse i hade to convert work to exe and for latest onnxruntime it gives me error when using GPU
so what should i do . i must use (onnx +GPU )

**Comment by VYRION-Ai** [comment]
i solve the problem 
new yolo default --opset is  17 but i work in 12 so i just use --opset 12 in export

**Comment by glenn-jocher** [comment]
@VYRION-Ai great to hear that you were able to solve the issue by specifying the `--opset 12` option during export. This is a good workaround to maintain compatibility with your specific environment. If you have any further questions or need assistance, feel free to ask. Keep up the great work!
