### ISSUE TITLE
detect -> COM

### ISSUE THREAD

**Issue by chuquyet171** [ultralytics/yolov5#10900]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

tôi muốn gửi tên của đối tượng khi detect bằng webcam tới cổng COM thì làm như thế nào?

**Comment by glenn-jocher** [comment]
@chuquyet171 xin chào! Để gửi tên của đối tượng khi detect bằng webcam tới cổng COM, bạn có thể sử dụng Python để gửi dữ liệu qua cổng COM sau khi nhận diện được đối tượng. Bạn có thể tham khảo thêm trong tài liệu Ultralytics tại đây: https://docs.ultralytics.com/yolov5/.

Nếu bạn có thêm bất kỳ câu hỏi nào khác, đừng ngần ngại hỏi tôi. Chúc bạn thành công!
