### ISSUE TITLE
Training my custom dataset with unfrozen the last e.g. 3layers 

### ISSUE THREAD

**Issue by georgekasa** [ultralytics/yolov5#10909]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,
I want to train this model based on my custom data set ( to detect lanes in a road), I saw your example with mushrooms, but i Have 2 questions in your example with training your model on your custom dataset all layers are frozen?
if I want to unfreeze the last e.g. 3 layers ( to train better for my dataset) how I can do that?

thank you in advance

### Additional

no

**Comment by glenn-jocher** [comment]
@georgekasa hi there,

To unfreeze the last 3 layers for better training on your custom dataset, you can modify the `yolov5s.yaml` file in the `models` directory, setting `nc: 1` for one class and commenting out the `pretrained: true` line. Then you can train using the `--weights` parameter with your custom model weights to begin training from there.

Feel free to refer to our documentation for more details on custom training. If you have any further questions or need assistance, don't hesitate to ask.

Good luck with your custom dataset training!
