### ISSUE TITLE
Custom Models using  PyTorch Hub

### ISSUE THREAD

**Issue by Ser1011** [ultralytics/yolov5#10910]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I've been fiddling with PyTorch Hub and wanted to use all custom data including the detect.py file, in your guide on using YOLOv5 from PyTorch Hub I found the code below.

model = torch.hub.load('path/to/yolov5', 'custom', path='path/to/best.pt', source='local')  # local repo

This should use the detect.py in my pc, but it still uses the default detect.py, I even used force reload and get the same outcome.

Am I missing something? 

And yes I added the correct paths, the code above I pulled from the guide.

**Comment by jonghyeonjung** [comment]
```
#ModuleNotFoundError: No module named 'models' error prevention
import sys
sys.path.insert(0,'./yolov5')

# model import
pt_file_path = "./best.pt"
model = torch.hub.load(os.getcwd(), 'custom', source='local', path = pt_file_path, force_reload = True)
```

I succeeded in this way.

**Comment by Ser1011** [comment]
> ```
> #ModuleNotFoundError: No module named 'models' error prevention
> import sys
> sys.path.insert(0,'./yolov5')
> 
> # model import
> pt_file_path = "./best.pt"
> model = torch.hub.load(os.getcwd(), 'custom', source='local', path = pt_file_path, force_reload = True)
> ```
> 
> I succeeded in this way.

Thanks for the reply, I've tried this and it's still the same outcome, I wonder if it's because I'm using Anaconda for the environments, but that shouldn't be the issue, the only thing I can think of is torch hub local doesn't really work or there's something missing from hubconf.py.

I've tried without my pc connected to the internet and still won't use the detect.py that I've edited.

**Comment by 459737087** [comment]
thank you ,you're right @jonghyeonjung

**Comment by glenn-jocher** [comment]
@459737087 hello! I'm glad to hear that you've found a solution that works for you. It's important to note that when using PyTorch Hub with a local repository, the `hubconf.py` file in your local YOLOv5 directory is the entry point for the model loading process. If you're making changes to `detect.py` or any other files, ensure that they are correctly referenced within your local YOLOv5 directory.

If you're still facing issues with using a custom `detect.py`, double-check that your local repository structure is intact and that you're pointing to the correct file paths. Remember that the local environment, including the use of Anaconda, should not affect the functionality of PyTorch Hub as long as the paths are correctly specified.

If you continue to experience issues, please refer to our documentation or consider opening an issue on the YOLOv5 GitHub repository with detailed information about your setup and the steps you've taken. This will help us understand the problem better and provide you with more targeted assistance.

Thank you for being part of the YOLOv5 community! 🚀
