### ISSUE TITLE
img_size

### ISSUE THREAD

**Issue by LiGithubYu** [ultralytics/yolov5#1091]
## ❔Question
My dataset has some different resolutions,  all of which are 4:3 or 16:9. The biggest one is 2000x1500 and the smallest one is 480x360. What img_size should I use? Should I use --rect?
Thank you.

**Comment by glenn-jocher** [comment]
@LiGithubYu train with all default settings, including image size. Defaults are located in argparser section of trian.py.

**Comment by LiGithubYu** [comment]
> @LiGithubYu train with all default settings, including image size. Defaults are located in argparser section of trian.py.

Thank you, I will try it.
