### ISSUE TITLE
Some brief guidance on migration to v7.0

### ISSUE THREAD

**Issue by davesargrad** [ultralytics/yolov5#10921]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

We've been using v6.2 for some time now. We are interested in the segmentation features that we think are in v7.0, but honestly its not quite clear what is there yet.

The following features are of distinct interest to us.

- Train on labeled objects bounded using polygons (rather than rectangles)
- Train on labeled objects that are bounded via polygons, but that have also been bounded to ignore "holes in those objects" (such a hole, for example, might be drawn to avoid corrupting training by an object in the foreground that overlaps the object of interest)
- Inferencing should generate  a bounding polygon along with a possible set of labels (for each detected and classified object)

I also see that there is only 1 tagged release of v7.0  so far. The master has a number of changes since then (46 files, 1177 insertsion, 1785 deletions). So Its not clear to me if v7.0 is yet mature in the released tag, and if I should wait for the next tag in order to get some of the features that I mention above.

Is there a concise list somewhere of the actual set of segmentation features in 7.0? I've looked at documentation, release notes, etc, and have not found a clear and concise list. 

Can you please provide me a brief summary of what to expect with 7.0, relative to 6.2? I would think this can also be useful on your release notes page for 7.0, and so it might be worth taking 10 to 15 minutes to capture that detail.

Also is there a clear roadmap that highlights some of the segmentation work that is your top focus, and that I might expect in an upcoming release?

**Comment by glenn-jocher** [comment]
@davesargrad thanks for your interest in YOLOv5 v7.0! The new version introduces enhanced segmentation features, including the ability to train on labeled objects bounded using polygons and inferencing to generate a bounding polygon with possible labels. 

As for your concerns about the maturity of v7.0, rest assured, the current tagged release is stable. However, improvements and bug fixes are ongoing, with the team striving to enhance the user experience continuously.

For a detailed list of segmentation features in v7.0, please refer to our documentation at https://docs.ultralytics.com/yolov5/. You'll find comprehensive release notes and roadmap highlights there as well.

We're excited about the evolving possibilities in YOLOv5, and your input is valuable to us. Let me know if you have any other questions!
