### ISSUE TITLE
original size to validation

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#10924]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

how can I validation with original size?

**Comment by glenn-jocher** [comment]
@alicera to perform validation with the original image size, you can use the `--augment` flag for testing, or set `img_size` to 640 or -1 in `test.yaml`. For more details, you can refer to the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/. Let me know if you need further assistance!
