### ISSUE TITLE
How does prediction aggregation work in YoloV5 ensembles, and how can this be replicated if the models are exported?

### ISSUE THREAD

**Issue by michael-mayo** [ultralytics/yolov5#10929]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I'd like to know more about how predictions are aggregated when an ensemble is used for detection in detect.py. Currently we are exporting models for tensorflow serving, but the export.py program produces one model for each ensemble member. This probably means that we need to reproduce the prediction aggregation in a tensorflow serving environment to make the ensemble work. Could you please explain where this is done in the YoloV5 code?

**Comment by Zephyr69** [comment]
I think exporting the ensembled model to onnx first will save you this trouble.

**Comment by michael-mayo** [comment]
> I think exporting the ensembled model to onnx first will save you this trouble.

Any idea what the command line switch is to export the ensemble into a single onnx model? I tried an export to onnx and still get three separate onnx files. Or were you suggesting to fuse them at the onnx level?

**Comment by glenn-jocher** [comment]
@michael-mayo you can achieve ensemble aggregation prior to export, using the `--optimize` flag in the export.py script to create a single ONNX model. This command automatically combines ensemble models before exporting to ONNX. For more information on the `--optimize` flag and other export options, you can refer to the [Ultralytics YOLOv5 documentation](https://docs.ultralytics.com/yolov5/). Let me know if you need further assistance!

**Comment by abhi0928** [comment]
@glenn-jocher I tried by including --optimize flag in export.py, but still I am getting different onnx models for each .pt model

**Comment by glenn-jocher** [comment]
Apologies for the confusion, @abhi0928. The `--optimize` flag is used for optimizing individual models, not for ensembling them into a single ONNX file. Currently, YOLOv5 does not support exporting an ensemble of models as a single ONNX file directly.

Ensemble predictions are aggregated in the inference stage within the YOLOv5 codebase, specifically in the `detect.py` script. If you're looking to replicate this behavior in TensorFlow Serving, you would need to manually implement the logic to aggregate the outputs of the individual models after inference.

The aggregation process involves combining the predictions from each model and applying Non-Maximum Suppression (NMS) across all predictions to remove duplicates and keep the best bounding boxes. You can find the relevant code for this process in the `ensemble_predictions` function within the YOLOv5 codebase.

For TensorFlow Serving, you would need to serve each model separately, run inference on each, and then write a custom aggregation function that takes all the individual predictions and applies NMS. This is not a trivial task and requires a good understanding of both the YOLOv5 prediction format and the TensorFlow Serving framework.

If you have further questions or need more detailed guidance, feel free to ask!

**Comment by abhi0928** [comment]
@glenn-jocher Thanks for the clarification, I have one more thing to ask, I want to get the bounding boxes, conf, and classes which we plot at last after applying ensemble on an image. right now when I run my data on ensemble I get the output image in the exp folder, but I want final predictions of ensemble in bbox, conf and classes. from where in the script I can see that?

**Comment by glenn-jocher** [comment]
@abhi0928, to obtain the bounding boxes, confidences, and class predictions after running an ensemble on an image, you can look at the output of the `run()` function in `detect.py`. The predictions are processed and stored in the variable that holds the results after non-maximum suppression (NMS) is applied.

To access these values, you can modify the `detect.py` script to save or print the results before the script completes. The results are typically in the form of a tensor or a list of tensors with each tensor corresponding to detections on one image, with each detection formatted as `[x1, y1, x2, y2, confidence, class]`.

Look for the part of the code where the `run()` function returns or where the predictions are drawn on the images. This is usually after the NMS step. You can then extract the required information from the tensor and save it in the desired format (e.g., to a text file, JSON, etc.).

Remember to handle the results carefully, as they may be on the GPU if you're using CUDA. You might need to transfer them to the CPU before converting them to a numpy array or another Python data structure.

If you're not familiar with modifying the script, you can start by printing the shape and content of the predictions tensor to understand its structure. Once you're comfortable with that, you can write the code to extract and save the bounding boxes, confidences, and classes as needed.

**Comment by shreyydesai** [comment]
Hi,
To add to the discussion, I have made some changes in detect.py to give me the required output . However, I want to deploy my ensemble model to azure and need its input to be in a base64 format which currently detect.py does not accept. Is there a way I could fix that ?

**Comment by glenn-jocher** [comment]
@shreyydesai to adapt your ensemble model in `detect.py` for Azure deployment with base64 input, you'll need to modify the script to decode base64-encoded images into a format that the model can process. Here's a concise guide on how to achieve this:

1. **Decode Base64 to Image**: You'll need to add a step in `detect.py` to decode the base64 string into an image. Python's base64 library and PIL (Pillow) or OpenCV can be used for this purpose.

2. **Modify Input Handling**: Locate the section in `detect.py` where input images are loaded and preprocessed. Before this step, insert your base64 decoding logic.

Here's a simplified example using PIL:

```python
import base64
from PIL import Image
from io import BytesIO

# Function to decode base64 to an image
def base64_to_image(base64_str):
    image_data = base64.b64decode(base64_str)
    image = Image.open(BytesIO(image_data))
    return image

# Example usage
base64_str = "your_base64_string_here"
image = base64_to_image(base64_str)

# Now, you can process 'image' as you would with any image file loaded in detect.py
```

3. **Adjust for Batch Processing**: If your deployment scenario involves processing multiple images at once, ensure your base64 decoding logic supports batch operations. This might involve decoding multiple base64 strings in a loop or vectorized operations.

4. **Test Thoroughly**: Before deploying, test the modified `detect.py` script locally with several base64-encoded images to ensure the decoding and detection pipeline works as expected.

5. **Deployment**: Once you've confirmed the modifications work locally, you can proceed with your Azure deployment. Ensure that the environment in Azure has all the necessary libraries installed (e.g., PIL or OpenCV for image processing).

Remember, when deploying models that accept base64-encoded images, it's crucial to handle errors gracefully. This includes invalid base64 strings, images that cannot be decoded, or images that are not in the expected format.

By following these steps, you should be able to modify `detect.py` to accept base64-encoded images as input, making it compatible with your Azure deployment requirements.

**Comment by shreyydesai** [comment]
Hi @glenn-jocher,
I have been trying to deploy the model on Azure and I cannot deploy the entire yolov5 folder. As mentioned before it accepts image in the form of an array for inference. I have made changes to detect.py for the ensemble model. I do get outputs for the two models separately. However, It gives me nothing after NMS. Is there a way I could use some script that does the NMS after I get the results from the models (load the model from torch hub) and then deploy it to Azure. Thanks.

**Comment by glenn-jocher** [comment]
Hi @shreyydesai,

It sounds like you're close to having your ensemble model deployment-ready on Azure. For applying Non-Maximum Suppression (NMS) after obtaining outputs from your models, you can use PyTorch's `torchvision.ops.nms` function directly on the predictions. 

Here’s a basic snippet demonstrating how to apply NMS to your detections:

```python
import torch
from torchvision.ops import nms

# Assuming 'detections' is a tensor [num_detections, 6] in the format [x1, y1, x2, y2, conf, class]
# Convert class + conf to a single score if necessary, or use conf directly for NMS

scores = detections[:, 4]  # Example using confidences as scores

# NMS Threshold
nms_thresh = 0.5

# Apply NMS, keep only indices of kept boxes
keep = nms(detections[:, :4], scores, nms_thresh)

# Select detections that are kept
final_detections = detections[keep]

# Now, final_detections holds your results post-NMS
```

This code snippet assumes your outputs are in the expected format and on the CPU. If your detections or model are on a GPU, ensure to move them to the CPU before applying NMS if needed.

Deploying this to Azure, you could wrap this functionality into a stand-alone script or integrate it within your existing `detect.py` adjustments. Make sure to test this thoroughly locally before deploying.

Good luck with your deployment! If you have more questions or run into issues, feel free to ask.
