### ISSUE TITLE
Multiclass Classification on Custom Dataset

### ISSUE THREAD

**Issue by ZahraAnam** [ultralytics/yolov5#10922]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to design a counter using multiclass classification and want to use classify/train.py for this purpose. There are several instances of different classes in each image. I was wondering if you can guide me how can I fine-tune on custom data with labels in .txt file for each image.

**Comment by glenn-jocher** [comment]
@ZahraAnam hi there! To train YOLOv5 for multiclass classification on custom data, you can use the `--data` and `--cfg` flags in `train.py` to specify the path to your dataset and the model configuration file, respectively. Your labels should be in a .txt file with one row per object, in the format: `class x_center y_center width height`. For more detailed guidance, please refer to our documentation at https://docs.ultralytics.com/yolov5/. Let me know if you need further assistance!
