### ISSUE TITLE
How to use yolov5 for instance segmentation?

### ISSUE THREAD

**Issue by 1a2cjitenfei** [ultralytics/yolov5#10923]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Requirement: only separate objects without background

**Comment by glenn-jocher** [comment]
@1a2cjitenfei hey there! YOLOv5 is primarily designed for object detection, but for instance segmentation without background, you might want to explore other frameworks specialized in this area such as Mask R-CNN and FCN. They are great for pixel-level segmentation and might better suit your specific needs. If you're interested in how YOLOv5 can assist with object detection, our documentation at https://docs.ultralytics.com/yolov5/ is a great resource to get started. Let me know if you have any other questions!
