### ISSUE TITLE
TensorRT GPU inference to support multi-model inference needs to push CUDA context before inference and pop it after

### ISSUE THREAD

**Issue by renowator** [ultralytics/yolov5#10935]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

I recently tried to run multiple TensorRT models' inference on NVIDIA Xavier NX one of which was yolov5 from this repository.

To support multiple TensorRT inference engines sequentially running on the same CUDA device, CUDA context needs to be changed to the context of current inference model. Without it I get a `CUDA Runtime error code 1: invalid resource handle.` 

To solve this issue I modified the file `ultralytics/yolov5/models/common.py`
1. **DetectMultiBackend.__init__(...) @ line 389+**
```
  elif engine:
    import pycuda.driver as cuda
    self.cuda_ctx = cuda.Device(0).make_context()
```
2. **DetectMultiBackend.forward(...) @ line 530 - 544**
```
  elif self.engine:
    self.cuda_ctx.push()
    ...
    y = [..]
    self.cuda_ctx.pop()

```
doing the same for both yolov5 and my second custom TensorRT model solved all the issues for me

### Use case

If running multiple TensorRT engines with different model architectures this will eliminate CUDA errors, but I am not sure how this affects single model performance

### Additional

Please let me know if I should submit a PR for this and if solving this problem like that makes sense to you.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by alib022** [comment]
Hi,

I've been doing the same thing and I managed to perform the same task by leveraging the triton inference server. Right now I have 5 different models (including yolo) all working next to each other on the same device. 

I am working on a medium blog to describe how it can be done and I will share the link here once published.

**Comment by glenn-jocher** [comment]
@alib022 that's awesome! It's great to hear that you were able to achieve multi-model inference using the Triton Inference Server. Your upcoming blog sounds like it will be extremely helpful to the community. We'd love to read it once it's published. Thank you for your contribution!
