### ISSUE TITLE
Predicted values and ground truth

### ISSUE THREAD

**Issue by juliacv** [ultralytics/yolov5#10939]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I'm trying to get the predicted values and the ground truth values for my validation out. I want to make my own evaluation method to be able to compare different networks, and need to compute the metrics the same way for multiple networks.

How can I get these values out? I've looked through the metrics and validation code but having a hard time.

**Comment by Guttappa1238** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.
> 
> ### Question
> Hi, I'm trying to get the predicted values and the ground truth values for my validation out. I want to make my own evaluation method to be able to compare different networks, and need to compute the metrics the same way for multiple networks.
> 
> How can I get these values out? I've looked through the metrics and validation code but having a hard time.
> 
> ### Additional
> _No response_

I need the same!

**Comment by glenn-jocher** [comment]
@Guttappa1238 you can obtain the predicted and ground truth values during validation using the YOLOv5 inference function. The `--save-txt` argument saves predicted bounding boxes to .txt files, and ground truth values are loaded from the same directory structure as your dataset. You can then create your own evaluation method using these outputs. You can refer to the `--save-txt` functionality \[here\](https://docs.ultralytics.com/yolov5/) for more details and examples.
