### ISSUE TITLE
train yolov5 model on cpu instead of gpu

### ISSUE THREAD

**Issue by sidh1603** [ultralytics/yolov5#10930]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Actually i have trained a model on gpu , but now i wanted to train yolov5 model on cpu, is there any way or any changes in code so that i can train my model on cpu

**Comment by DeepKnowledge1** [comment]
You just want to change device as follows:

`parser.add_argument('--device', default='cpu', help='cuda device, i.e. 0 or 0,1,2,3 or cpu')
`


But why you want to retrain while you already have trained  the model on gpu, you just can use this model to do inference on cpu

**Comment by glenn-jocher** [comment]
@DeepKnowledge1 you can train YOLOv5 on CPU by simply changing the device to 'cpu' in the command line argument or config file. However, if you have already trained the model on GPU, it can still be used for inference on CPU without the need to retrain.
