### ISSUE TITLE
 How to improve the accuracy of some of the 80 classes for YoloV5?

### ISSUE THREAD

**Issue by MarcoPrassel** [ultralytics/yolov5#10938]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I would like to have better accuracy for the bus and person classes of the COCO Dataset. I am using yolov5m network, I would not like to use other types of network like yolovx because they are not good for performance.
Can samples be added to improve accuracy without doing retraining from scratch ?
What’s the best way to do it?
p.s: I collected a lot of new images with persons and bus.

**Comment by sunling583** [comment]
I am in a smilar situation where I am trying to obtain better accuracy for the 'sports ball' class. Are there any technques for custom training that could probably make use of the pretrained knowledge of 'sports ball', rather than train a new detection class from scratch? Thanks for any advice.

**Comment by glenn-jocher** [comment]
@sunling583 you can improve accuracy for specific classes via transfer learning. You can initiate training from a pretrained model such as YOLOv3 or YOLOv4 before continuing with your custom dataset. Additionally, you can further optimize your model using the COCO pretraining by adding your labeled sports ball images to the preexisting COCO dataset. This could help refine 'sports ball' detection without training from scratch. For more specifics, check out the Ultralytics documentation. Good luck!
