### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 600.00 MiB (GPU 0; 2.00 GiB total capacity; 917.58 MiB already allocated; 424.44 MiB free; 932.00 MiB reserved in total by PyTorch)

### ISSUE THREAD

**Issue by S-mishina** [ultralytics/yolov5#1094]
## ❔Question

I initialized the environment once, created a new virtual environment, and executed the following command.
python train.py --img 640 --epochs 5 --data data.yaml --cfg ./models/yolov5m.yaml --batch-size 6
If you do so, you will get the following error:
RuntimeError: CUDA out of memory. Tried to allocate 600.00 MiB (GPU 0; 2.00 GiB total capacity; 917.58 MiB already allocated; 424.44 MiB free; 932.00 MiB reserved in total by PyTorch)
Please let me know if there is a solution.

environment
windows10
GTX960

**Comment by bingiflash** [comment]
Try lesser batch-size

**Comment by NanoCode012** [comment]
@S-mishina , If it's possible, I would recommend using Google Colab to run it for free unless you have some requirements to run it on your device as you will get a better GPU with more memory.

https://github.com/ultralytics/yolov5#environments

**Comment by S-mishina** [comment]
I found the following solution as a solution. The command is shown below.
python train.py --img 640  --epochs 50 --data data.yaml --cfg ./models/yolov5m.yaml --batch-size 2
