### ISSUE TITLE
No predictions using Cuda v12

### ISSUE THREAD

**Issue by 9joshua** [ultralytics/yolov5#10947]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Environment:

- Ubuntu 22.04
- Nvidia Driver Version: 525.78.01
- CUDA Version: 12.0

command:
```
python train.py --img 640 --device 0 --batch 8 --epochs 3 --data ../training-test/dataset.yaml --weights yolov5l.pt
```

I read [a previous issue](https://github.com/ultralytics/yolov5/issues/7196#issuecomment-1087466397) (for Yolov3) in which no prediction results were obtained when using Cuda v11. The suggestion was to downgrade to Cuda v10 due to a bug in v11. I seem to have a similar problem with Yolov5 and Cuda v12. Using `--device cpu` works as expected with fairly accurate and consistent predictions.

I have tried changing...
`scaler = torch.cuda.amp.GradScaler(enabled=amp)`
to:
`scaler = torch.cuda.amp.GradScaler(enabled=False)`
but with no success.

**Comment by glenn-jocher** [comment]
@9joshua hi there!

Thanks for reaching out. The issue with predictions using CUDA v12 is indeed a known bug, and it's currently being addressed. In the meantime, using `--device cpu` should provide accurate and consistent predictions. We appreciate your patience as we work to resolve this. Your understanding and feedback are greatly appreciated, and it truly contributes to the YOLO community! If you need further assistance, please refer to our documentation at https://docs.ultralytics.com/yolov5/.

All the best!
