### ISSUE TITLE
COCO format Instance Segmentation labels conversion to YOLOv5 format

### ISSUE THREAD

**Issue by m-ali-awan** [ultralytics/yolov5#10954]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Hi all,
Last week, I was struggling to convert instance segmentation labels to YOLOv5 format, to train the YOLOv5-seg models. To my knowledge, only Roboflow provides the functionality, and even for that, we have to upload our data, and if we can't pay to Upgrade, we have to make it public.
So, I have tried to write this functionality here:
https://github.com/m-ali-awan/yolov5-seg-labels-conversion.git
Using this, we can convert instance segmentation labels in COCO 1.0 format to Yolov5 format. If it can be of use to someone, that would be amazing.
Also, do let me know, in case of any mistake, as I am not that much expert :slightly_smiling_face:
thanks

### Use case

Right now popular labeling tools like CVAT, are not having Instance Segmentation labels export option in YOLOv5. We can do so, only using Roboflow, and for that, we have to make our dataset public. Using this, we can handle this conversion on our own.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by ryouchinsa** [comment]
Using this script, you can convert the COCO segmentation format to the YOLO segmentation format.
https://github.com/ultralytics/JSON2YOLO

Read this related issue.
https://github.com/ultralytics/yolov5/issues/10621

**Comment by almazgimaev** [comment]
Hi, @m-ali-awan, 
You can do it in just a couple of clicks using apps from [Supervisely ecosystem](https://ecosystem.supervisely.com/):

1. Firstly, you need to upload your COCO format data to the Supervisely using [Import COCO](https://ecosystem.supervisely.com/apps/import-coco) app.
You can also upload data in another format [one of the import applications](https://ecosystem.supervisely.com/import+images)

2. Next, you can export the data from Supervisely in the YOLO v5/v8 format:
    - For polygons and masks (without internal cutouts), use the "[Export to YOLOv8](https://ecosystem.supervisely.com/apps/export-to-yolov8)" app;
    
    ```
    class x1 y1 x2 y2 x3 y3 ...
    0 0.100417 0.654604 0.089646 0.662646 0.087561 0.666667 ...
    ```

    - For exporting as bounding boxes, use the "[Convert Supervisely to YOLO v5 format](https://ecosystem.supervisely.com/apps/convert-supervisely-to-yolov5-format)" app.  But if not all labels in your project are rectangles, use [this app](https://ecosystem.supervisely.com/apps/convert-class-shape) to convert them to rectangles).

    ```
    class x_center y_center width height
    0 0.16713 0.787696 0.207783 0.287495
    ```

I'm sure there are many apps in the Supervisely ecosystem that can help solve your tasks.

**Comment by glenn-jocher** [comment]
Hi @almazgimaev-awan,

Thanks for letting us know your struggle in converting the instance segmentation labels to YOLOv5 format. Alessio is right; with Supervisely, you can easily convert your COCO format data to the YOLOv5 format using one of the plug-and-play solutions from their ecosystem. 

If you have any questions or run into any issues, please feel free to ask for further support from our team or Supervisely's customer support team.

Best, 
Glenn
