### ISSUE TITLE
How to load weight files with low version of torch

### ISSUE THREAD

**Issue by BridgeLee** [ultralytics/yolov5#1095]
Since the lab server cannot change the version of cuda at will, the higher version of torch cannot be used, so I want to know how to use the lower version of torch (1.2.0) to load the weight file, or how can I do it

**Comment by NanoCode012** [comment]
@BridgeLee , could you try Docker or any other environment? 

https://github.com/ultralytics/yolov5#environments

**Comment by BridgeLee** [comment]
I'm not familiar with docker, so I haven't tried this approach yet, so I want to ask if there are other ways. Can I load the weight file through torch1.6 and save it in a format acceptable to torch1.2?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ultralytics/yolov5"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月8日(星期四) 中午1:19
收件人:&nbsp;"ultralytics/yolov5"<yolov5@noreply.github.com&gt;;
抄送:&nbsp;"4 88907 92 "<384073386@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ultralytics/yolov5] How to load weight files with low version of torch (#1095)





 
@BridgeLee , could you try Docker or any other environment?
 
https://github.com/ultralytics/yolov5#environments

**Comment by glenn-jocher** [comment]
@BridgeLee requirements are stated in https://github.com/ultralytics/yolov5#requirements. We don't support problems outside of these.
