### ISSUE TITLE
How to print the classes without appending

### ISSUE THREAD

**Issue by m3005** [ultralytics/yolov5#10959]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi! I'm using yolov5 for character recognition in a number plate. So I want to display the characters which is recognized. 
Any kind of help would be highly appreciated

**Comment by glenn-jocher** [comment]
@m3005 hi there! To print the classes without appending, you can specify the `--save-txt` flag when you run `detect.py`. This saves the class indices and localization data to a text file without appending. You can find more details in the Ultralytics YOLOv5 documentation at https://docs.ultralytics.com/yolov5/. Good luck with your character recognition task!
