### ISSUE TITLE
AttributeError: 'list' object has no attribute 'shape'

### ISSUE THREAD

**Issue by XL634663985** [ultralytics/yolov5#10967]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

![image](https://user-images.githubusercontent.com/73512234/218402750-632a84d8-6310-49a2-956d-0d7381582320.png)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@XL634663985 seems related to anchor generation. You might want to try training your dataset with https://github.com/ultralytics/ultralytics which offers anchor-free YOLOv8 models.

**Comment by Goooyi** [comment]
I have also encouted this error when I tried to train yolov5-seg.yaml model with my own custome dataset.

**Comment by Goooyi** [comment]
> I have also encouted this error when I tried to train yolov5-seg.yaml model with my own custome dataset.

Ok, simply using `python segment/train.py ...` solve the problem for me. In the docs of yolov5 homepage it says using `train.py`, but in the [yolov5-v7.0](https://github.com/ultralytics/yolov5/discussions/10258) docs it says using `segment/train.py`.  So two `train.py` are not merged yet for segmentation task and detection task.

**Comment by glenn-jocher** [comment]
@Goooyi glad to hear you were able to resolve the issue using `python segment/train.py`. As for the discrepancy in the documentation, the Ultralytics team continuously updates and improves the YOLOv5 repo and documentation, and your feedback will certainly help in ensuring its accuracy. Thank you for your understanding and contributions to the YOLO community!

**Comment by 82lilsak** [comment]
tyty

**Comment by glenn-jocher** [comment]
@82lilsak you're welcome! If you have any more questions or need further assistance in the future, don't hesitate to reach out. Happy training! 😊🚀
