### ISSUE TITLE
How to get classes available from a video?

### ISSUE THREAD

**Issue by nostalgicnarc1024** [ultralytics/yolov5#10960]
In case of an image, I can view the classes available in the frame using the argument --save-txt, Is there any way that I can get real time data of classes available in a live feed video?

**Comment by glenn-jocher** [comment]
@nostalgicnarc1024 you can use YOLOv5 for real-time object detection on a live video feed. Check out the --source argument in the detect.py script to specify a video source. The detected classes will be displayed in the live feed output. For more details, refer to our documentation at https://docs.ultralytics.com/yolov5/ under the "Real-time Detection" section. If you have any further questions, feel free to ask!
