### ISSUE TITLE
Comparison between version yolov8 and yolov7.

### ISSUE THREAD

**Issue by sarpx** [ultralytics/yolov5#10965]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I trained the same two data with versions 8 and 7 with very different results. I wasn't expecting that much difference. Is there a setting missing?

v7
---
python segment/train.py --batch 14 --epochs 300 --data ./girdi/v5001_1675781502310.yaml --cfg ./models/segment/yolov5x-seg.yaml --weights ./weights/yolov5x-seg.pt --img 640 --device 0 --exist-ok --name ./faz030123/v5001_1675781502310

v8
----
yolo segment train model=./ek/yolov8x-seg.pt data=../yolov5-7.0/girdi/v5001_1675781502310.yaml device=0 batch=14 epochs=300  imgsz=640 name=./faz030123/v5001_8_1675781502310

### Additional
results v7
[v7.txt](https://github.com/ultralytics/yolov5/files/10719314/v7.txt)
-----
results v8
[v8.txt](https://github.com/ultralytics/yolov5/files/10719315/v8.txt)
-----
![results_V8](https://user-images.githubusercontent.com/73984193/218387176-5c62cbe9-22cc-4bd1-809b-9d610cabd511.png)
![results_v7](https://user-images.githubusercontent.com/73984193/218387300-18a689c9-d5aa-47f3-932e-ff6df9efc5f1.png)

**Comment by sarpx** [comment]
@glenn-jocher I know it's very busy but I'm very excited about yolov8 too.
Training data and parameters are the same but I get very bad results in yolov8. I don't think there should be that much difference. Is there something overlooked?

**Comment by glenn-jocher** [comment]
@sarpx hi there! Thanks for your interest in YOLOv8! The YOLOv8 model architecture actually doesn't exist under the YOLOv5 repository. If you are referring to YOLOv5, it's normal to see differences between versions as they have distinct architectures and training procedures. Be sure to review any changes in the architecture and/or training strategy when comparing results. If you have any specific questions related to YOLOv5, feel free to ask! If you're working with a different model, I'd recommend reaching out to the respective authors for assistance. Good luck with your training!
