### ISSUE TITLE
How to modify the Confusion Matrix?

### ISSUE THREAD

**Issue by Shahood-Sajid** [ultralytics/yolov5#10961]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

The confusion matrix which is being generated is like this, which is quite confusing for me.
![confusion_matrix](https://user-images.githubusercontent.com/91459176/218318661-09c33c51-c6b6-4893-8659-9311660ff8e1.png)

I wanted my matrix like this. What should I do?

![sphx_glr_plot_confusion_matrix_002](https://user-images.githubusercontent.com/91459176/218318698-4cbab442-700a-4554-a2df-ac97221cfdb0.png)

**Comment by tejaskhare99** [comment]
Hi, 
So I also wanted to get the plot of confusion matrix for subclasses of the dataset.
You can do one simple thing in utils/metrics.py

In def plot(self, normalize=True, save_dir='', names=()),
change the size of the array of the confusion matrix according to the number of classes you want.

So for example, I just needed the first 5 classes from the 80 classes of coco. I just reduced the size of the array after the line 190 that defines the variable 'array'. 
I used np.delete twice for deleting multiple dimensions at once.
Something like this - 
```
array = np.delete(np.delete(array, slice(5,81), 0), slice(5,81), 1)
```
The slice(5, 81) is nothing but deleting multiple rows or columns at once.

Hope this helps!

**Comment by glenn-jocher** [comment]
@tejaskhare99 hi there!👋

Thanks for sharing this helpful tip! Customizing the confusion matrix plot by adjusting the size of the array in `utils/metrics.py` is indeed a great way to visualize subclasses of the dataset. Your example using `np.delete` is a neat approach for achieving this.😊

Feel free to explore and experiment with the code as needed to tailor the visualization to your specific use case.

If you have any more questions or ideas, please don't hesitate to reach out!
