### ISSUE TITLE
Interpreting Testing and Validation Results

### ISSUE THREAD

**Issue by ceforfinski** [ultralytics/yolov5#10962]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am new to training custom YOLO models and am having a difficult time interpreting the metrics outputted after using train.py on my custom dataset. My images are split into 80/10/10. I understand that the mAP values are calculated from the validation set after each epoch.  My question is which metrics are outputted from the testing data at the end of training? If none, how can I quantify the model's accuracy on my testing images?

**Comment by Ellohiye** [comment]
> ### 询问前搜索
> * [x] 我搜索了YOLOv5的[issues](https://github.com/ultralytics/yolov5/issues)和[discussion](https://github.com/ultralytics/yolov5/discussions)，没有发现类似的问题。
> 
> ### 问题
> 我是训练自定义 YOLO 模型的新手，很难解释在我的自定义数据集上使用 train.py 后输出的指标。我的图像分为 80/10/10。我知道 mAP 值是根据每个纪元后的验证集计算得出的。我的问题是在培训结束时从测试数据中输出了哪些指标？如果没有，我如何量化模型在我的测试图像上的准确性？
> 
> ### 额外的
> _没有反应_

你好，请问你解决了这个问题吗？

**Comment by glenn-jocher** [comment]
@Ellohiye 你好！确实，在训练结束时，没有来自测试数据的输出指标。不过，你可以使用`val.py`来对测试图像进行推理，并获得模型在测试集上的准确性。你还可以查看[我们的文档](https://docs.ultralytics.com/yolov5/)，了解更多关于如何解释这些输出指标的信息。祝您训练顺利！
