### ISSUE TITLE
Train on Google Collab and Detect with Local Camera/Webcam

### ISSUE THREAD

**Issue by smalik89** [ultralytics/yolov5#10978]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello! I am currently using the YOLOV5 notebook! I am able to train on Google Cloud through Google Collab. Since the webcam connection doesn't work with Google Collab with the detect code block, _how do I run the trained model locally for detection with live webcam_? I want to use the weights and trained model for the live detection and not have to run the training locally. 

Many thanks!!

![image](https://user-images.githubusercontent.com/53238240/218571486-11ff74b1-f0d4-41f1-ac53-5566991301c3.png)

**Comment by glenn-jocher** [comment]
@smalik89 yes, this is fine. Just download your trained model and then run it locally.

**Comment by smalik89** [comment]
Thank you @glenn-jocher for your message! How can I download the trained model and run it on Webcam? Is there a code you can recommend?

**Comment by rudro12356** [comment]
> Thank you @glenn-jocher for your message! How can I download the trained model and run it on Webcam? Is there a code you can recommend?
Check this issue: https://github.com/ultralytics/yolov5/discussions/5872

You can try this: 
import torch
model = torch.hub.load('.', 'custom', path='/path/to/yolov5/runs/train/exp5/weights/best.pt', source='local') 
# Image
img = '/path/to/test/image/25.jpg'
# Inference
results = model(img)
# Results, change the flowing to: results.show()
results.show()  # or .show(), .save(), .crop(), .pandas(), etc

**Comment by smalik89** [comment]
Thank you @rudro12356 ! This is great for images! How can the downloaded model be used for webcam/video stream type input? Is there any code in this repos or elsewhere recommended for that?

**Comment by rudro12356** [comment]
@smalik89 Please check this video : https://www.youtube.com/watch?v=NevTDh9srSo, and check out the readme for the YOLOv5 on Github.

**Comment by smalik89** [comment]
Thank you @rudro12356 ! Is there a script recommended by Ultralytics  that would read a downloaded model (.pt file) and allow a connection with webcam which can show the bounding boxes live? @glenn-jocher

**Comment by smalik89** [comment]
Hi! I saw this code from an earlier post by @glenn-jocher [https://github.com/ultralytics/yolov5/issues/7207]( https://github.com/ultralytics/yolov5/issues/7207 ). How can this be adjusted for Webcam?
```

import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, etc.
# model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')  # custom trained model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```

**Comment by glenn-jocher** [comment]
@smalik89 Yes, this code can be adjusted to work with a webcam by capturing video frames instead of loading an image. Here's a modified version of the code that demonstrates how to perform live inference with a webcam:

```python
import torch
from PIL import Image
import cv2

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, etc.
# model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')  # custom trained model

# Webcam
cap = cv2.VideoCapture(0)  # Use the default webcam (change the argument to switch to a different camera)

while True:
    ret, frame = cap.read()  # Read a frame from the webcam
    im = Image.fromarray(frame)  # Convert the frame to PIL Image
    results = model(im)  # Inference

    # Bounding box display
    for *xyxy, conf, cls in results.xyxy[0]:
        cv2.rectangle(frame, (int(xyxy[0]), int(xyxy[1])), (int(xyxy[2]), int(xyxy[3])), (255, 0, 0), 2)
        cv2.putText(frame, f'{model.names[int(cls)]} {conf:.2f}', (int(xyxy[0]), int(xyxy[1])), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2, cv2.LINE_AA)

    cv2.imshow('YOLOv5', frame)  # Display the frame with bounding boxes

    if cv2.waitKey(1) == ord('q'):  # Press 'q' to exit
        break

cap.release()  # Release the webcam
cv2.destroyAllWindows()  # Close all windows
```

This code uses OpenCV to capture frames from the webcam and perform live inference with the YOLOv5 model, displaying the resulting bounding boxes on the video stream. Press 'q' to exit the program.
