### ISSUE TITLE
How to use an .onnx segmentation model on C#?

### ISSUE THREAD

**Issue by alessiopierdominici** [ultralytics/yolov5#10989]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello guys, I would like to use YOLOV5 Segmentation inference on a C# application, I have trained and tested a custom segmentation model and I would like to use it with OnnxRuntime.
I was able to create the image array in C# and perform an Inference using the OnnxRuntime, but I am not able to retrieve the outputs coordinates from the output array received by the inference.
Do you know if there are any libraries to use Yolov5 Segmentation in C#, for Object Detection I used https://github.com/mentalstack/yolov5-net library, can you help me? 
Thanks in advance.

**Comment by UNeedCryDear** [comment]
I'm not very familiar with C#, so I recommend using cpp implementation and then exporting dll to C# for use. . In this way, C# only needs to transfer images to the C++ , and then obtain the result data from C++.

**Comment by alessiopierdominici** [comment]
Are there any library to use, written in C++?

**Comment by UNeedCryDear** [comment]
I only have the cpp part, and other parts (dll-exporting and C++/CLI) need to be completed by yourself.
https://github.com/UNeedCryDear/yolov5-seg-opencv-onnxruntime-cpp
Or you can change the post-processing part into C# code and get the results directly on your c# code.
https://github.com/UNeedCryDear/yolov5-seg-opencv-onnxruntime-cpp/blob/73ddf09bb446b6ba9a185d4ed5321ea0ac83465b/yolov5_seg_onnx.cpp#L202

**Comment by alessiopierdominici** [comment]
I tried to look at the C++ code and I don't have any idea how it works, I will try to figure it out and code that function in C#.
Sorry, but I don't have almost any experiences with tensors and neural networks.

**Comment by UNeedCryDear** [comment]
So you may need to encapsulate the cpp code as a dll.

**Comment by glenn-jocher** [comment]
@UNeedCryDear i understand that working with C++ code and neural networks might be challenging if it's not your usual area of expertise. Here at Ultralytics, we strive to help our users succeed. Have you considered reaching out to a C++ or machine learning community for assistance with wrapping the C++ code into a DLL for use in your C# application? They might be able to provide valuable guidance and support.
