### ISSUE TITLE
Training with images of a single object. Detected multiple objects in a single image

### ISSUE THREAD

**Issue by trasmar** [ultralytics/yolov5#10983]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi. I have been working with CNNs for the classification of images with a single object in them. For a certain application, some objects in these images usually come together. So I have trained YOLO algorithms for detection using these images of a single object. However, when presenting an image with several of these objects, it only detects one of them, not the rest. YOLOs use mosaic mixup and in fact, in the training results, the combination of 4 images (with one object) into one (image with 4 objects) is observed. I really appreciate some guidance. Thank you.

**Comment by bryanbocao** [comment]
Could you check and post your object before and after combining?

One reason could be due to the change of scale of the object between your training and testing datasets, as what you model learned is only for a certain scale.

**Comment by glenn-jocher** [comment]
@bryanbocao hi there! It's great that you're training YOLO for single-object images. 🚀 To help with your question, could you share your object before and after combining, if possible? Differences in scale between training and testing images can lead to detection issues, as the model might only have learned to detect objects at a specific scale. You can adjust for this by training with a diverse set of scales or using data augmentation. Let me know if you need any assistance setting that up!
