### ISSUE TITLE
Hi i would like to add an output and train my model to detect image x,y,w,h and distance of the object. So how can i change the model to take one more output.

### ISSUE THREAD

**Issue by rakesh1ndivar** [ultralytics/yolov5#10980]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi i would like to add an output and train my model to detect image x,y,w,h and distance of the object. So how can i change the model to take one more output.

### Additional

Hi i would like to add an output and train my model to detect image x,y,w,h and distance of the object. So how can i change the model to take one more output.

**Comment by glenn-jocher** [comment]
@rakesh1ndivar hi there! You can modify the model to include an additional output by editing the model definition in the `models/yolov5.yaml` file. You'll need to update the number of classes, labels, and anchor parameters, and add a corresponding configuration for the new output. Make sure to also modify the model architecture accordingly. After making these changes, you can train your model using the new output information as part of the training data. Check out the Ultralytics Docs for more details on customizing the YOLOv5 model. Let us know if you need further assistance! 👍
