### ISSUE TITLE
YOLOv5 augmentation details

### ISSUE THREAD

**Issue by 25benjaminli** [ultralytics/yolov5#10994]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, does internal yolov5 augmentation increase the sample size of the dataset, or how does it work? Thanks.

**Comment by 25benjaminli** [comment]
Nevermind, I found that the model just sees different versions of images at each epoch.

**Comment by glenn-jocher** [comment]
@25benjaminli great to hear that you found the answer! 😊 Indeed, the YOLOv5 model uses data augmentation to present different versions of images to the model in each epoch, which helps improve its generalization and performance. If you have more questions, feel free to ask!
