### ISSUE TITLE
AssertionError: data.yaml 'images:' field missing 

### ISSUE THREAD

**Issue by Chanpoe** [ultralytics/yolov5#10996]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I'm a beginner of yolov5. My computer system is Windows 11. The following error will be reported whether creating a new dataset or using a dataset of coco128:
![image](https://user-images.githubusercontent.com/84487466/219444156-f6b6f20a-7f54-4002-9758-36f937c1afac.png)
My graphics card is NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB. How can I set parameters or modify the code there to fix this error?

### Additional

Traceback (most recent call last):
  File "E:\Coding\PycharmProjects\项目\口罩识别\yolov5\train.py", line 640, in <module>
    main(opt)
  File "E:\Coding\PycharmProjects\项目\口罩识别\yolov5\train.py", line 529, in main
    train(opt.hyp, opt, device, callbacks)
  File "E:\Coding\PycharmProjects\项目\口罩识别\yolov5\train.py", line 112, in train
    data_dict = data_dict or check_dataset(data)  # check if None
  File "E:\Coding\PycharmProjects\项目\口罩识别\yolov5\utils\general.py", line 515, in check_dataset
    assert k in data, emojis(f"data.yaml '{k}:' field missing ❌")
AssertionError: data.yaml 'images:' field missing

**Comment by bryanbocao** [comment]
@Chanpoe Can you post ```data.yaml``` here?

According to https://github.com/ultralytics/yolov5/blob/master/data/coco128.yaml
you need to specify your images path in your ```data.yaml``` file:
```
# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: ../datasets/coco128  # dataset root dir
train: images/train2017  # train images (relative to 'path') 128 images
val: images/train2017  # val images (relative to 'path') 128 images
```

**Comment by Chanpoe** [comment]
This is the `coco128. yaml` file, and the project directory is on the left. How does this path need to be changed in order to run the program correctly?
![image](https://user-images.githubusercontent.com/84487466/219551246-c1c60a9c-114e-42b9-9032-7a4978927bdc.png)
This is `train.py` file. The `--data` parameter is filled with `data/coco128.yaml`:
![image](https://user-images.githubusercontent.com/84487466/219552095-f5db09b9-ca48-413f-a75f-0842d57754b0.png)
It is still the result of this error report when I run 'train.py':
![image](https://user-images.githubusercontent.com/84487466/219552280-fc671d5f-4506-4091-89a9-2521678c8a0e.png)

**Comment by bryanbocao** [comment]
The error message suggests that you are using ```data.yaml``` Did you specify ```--data``` when running ```train.py``` like
```
python train.py --data data/coco128.yaml
```
?

**Comment by bryanbocao** [comment]
Maybe put ```datasets``` in the same folder as ```yolov5```.

**Comment by dust-removal** [comment]
你解决这个问题了吗 我也遇到了 啥情况

**Comment by Chanpoe** [comment]
> 你解决这个问题了吗 我也遇到了 啥情况

我怀疑是环境问题，但是我还没有解决qaq

**Comment by bryanbocao** [comment]
@Chanpoe @dust-removal 你们跑的具体command是什么呀?

**Comment by Chanpoe** [comment]
> @Chanpoe @dust-removal 你们跑的具体command是什么呀?

我的运行时候的参数是`--data data/coco128.yaml`
项目目录下面的是有这个文件的：
![image](https://github.com/ultralytics/yolov5/assets/84487466/f81df9e0-2c94-4b14-8572-a9be5eb3bc10)
报错的截图：
![image](https://github.com/ultralytics/yolov5/assets/84487466/e16f203c-6cb4-4fb0-b735-06949acf5849)

**Comment by bryanbocao** [comment]
我想看具体的command比如 ```python3 train.py ...```
你发的是目录结构和报错信息。

**Comment by Chanpoe** [comment]
> 我想看具体的command比如 `python3 train.py ...` 你发的是目录结构和报错信息。

具体的command是这个：
`python train.py --data data/coco128.yaml`

**Comment by bryanbocao** [comment]
https://stackoverflow.com/questions/62697400/assertionerror-file-not-found-yolov5 说或许跟Windows路径有关
![image](https://github.com/ultralytics/yolov5/assets/14010288/8cbbc077-4707-4ebc-8d82-59e31b4e9087)
这里吧single quote '去掉不知道能不能解决
```
... default=ROOT/data/coco128.yaml, help='dataset.yaml path')
```

**Comment by glenn-jocher** [comment]
@bryanbocao hi,

It seems that the issue might be related to Windows path. One suggestion is to remove the single quote mark and run `python train.py` directly. Alternatively, you might try using `python train.py --data data\coco128.yaml`.

Best,

**Comment by bryanbocao** [comment]
@glenn-jocher Thanks for the help! These are exactly what I said in the previous comment but in Chinese. Sorry, I did not translate them in English yet :)

**Comment by bryanbocao** [comment]
@glenn-jocher Not sure why but your comments look like generated by a bot :) Hope I am wrong.

**Comment by dust-removal** [comment]
@glenn-jocher @bryanbocao Hello,i have tried both two way,but none work. If remove the single quote,it suggested me that the data don't defined,and if using python train.py, it suggested the same error  field missing.

**Comment by bryanbocao** [comment]
@dust-removal 
```
python train.py --data=C:\Users\<YOUR_coco128.yaml_path>
```
had the same issue?

**Comment by Chanpoe** [comment]
> @glenn-jocher @bryanbocao Hello,i have tried both two way,but none work. If remove the single quote,it suggested me that the data don't defined,and if using python train.py, it suggested the same error field missing.

我已经成功解决了，解决方法是下载最新版yolov5
`git clone https://github.com/ultralytics/yolov5`
然后使用anaconda创建新环境使用python10版本
`conda create -n yolov5 python=3.10`
之后进入目录安装一下requirements.txt
`pip install -r requirements.txt`
（安装不了的包可以更换旧版本安装）
然后再次运行就可以了：
![image](https://github.com/ultralytics/yolov5/assets/84487466/28c2d485-a3b8-4e88-b618-6a7dccc50f75)

**Comment by glenn-jocher** [comment]
Hi @dust-removal,

I'm glad to hear that you were able to resolve the issue. Thank you for sharing your solution with us. It seems that downloading and using the latest version of YOLOv5, creating a new environment with Python 3.10, and installing the requirements.txt file fixed the problem. Thank you for sharing the screenshot of the successful run with us.

If you have any other questions or concerns regarding YOLOv5, please do not hesitate to ask.

Best,
