### ISSUE TITLE
"Is there an option in YOLOv5 inference results to not draw bounding boxes?"

### ISSUE THREAD

**Issue by leeyunhome** [ultralytics/yolov5#10999]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, Everyone.

Is there an option in YOLOv5 inference results to not draw bounding boxes?
If the option doesn't exist, where should I modify to not draw bounding boxes in inference results? I tried using line-thickness = 0 but it doesn't work.

Thank you.

**Comment by glenn-jocher** [comment]
@leeyunhome hello,

You can achieve that by replacing `plot_one_box` in `utils/plots.py` with a version that doesn't draw the bounding box. Keep in mind that modifying the source code directly will affect all uses of the function, so a more flexible approach might involve creating a custom visualization function outside of the YOLOv5 codebase. Let me know if you need any more details.

Best regards.
