### ISSUE TITLE
ImportError: The _imagingft C module is not installed

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#11007]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

```
cd yolov5
pip install -r requirement.txt
python train.py
```

```  
  return ImageFont.truetype(str(font) if font.exists() else font.name, size)
  File "/opt/conda/lib/python3.8/site-packages/PIL/ImageFont.py", line 844, in truetype
    return freetype(font)
  File "/opt/conda/lib/python3.8/site-packages/PIL/ImageFont.py", line 841, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/opt/conda/lib/python3.8/site-packages/PIL/ImageFont.py", line 169, in __init__
    if core.HAVE_RAQM:
  File "/opt/conda/lib/python3.8/site-packages/PIL/ImageFont.py", line 43, in __getattr__
    raise ImportError("The _imagingft C module is not installed")
ImportError: The _imagingft C module is not installed

During handling of the above exception, another exception occurred:

```

**Comment by Jack-Willder** [comment]
I'm having the same issue.

**Comment by glenn-jocher** [comment]
@Jack-Willder hey there! 👋 The `_imagingft` module is related to the Pillow library, which YOLOv5 uses for image processing. To resolve this, you can try reinstalling Pillow by running `pip install -U --force-reinstall Pillow`. If you still encounter issues, please check the installation troubleshooting section in our [Ultralytics Docs](https://docs.ultralytics.com/yolov5/) for further guidance. Let me know if you need any more help!
