### ISSUE TITLE
Quick deployment onto Raspberry PI for PoCs

### ISSUE THREAD

**Issue by u1353279** [ultralytics/yolov5#11006]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

It would be amazing if you can provide simply documentation on how to deploy onto a PI after training a ultralytics model, this would truly provide an end to end pipeline for businesses, that are wanting to quickly test the trained model on pi.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by JustasBart** [comment]
Hi @u1353279 you can find a C++ based example [here](https://github.com/JustasBart/yolov8_CPP_Inference_OpenCV_ONNX) or I'm pretty sure you can just clone the repository on your Raspberry pi and run **detect.py** directly on it (Haven't tried it myself).

You could also set it up with something like [NCS2](https://www.intel.com/content/www/us/en/developer/articles/tool/neural-compute-stick.html).

Hope this helps :rocket:
