### ISSUE TITLE
data.yaml relative path to train.txt/val.txt

### ISSUE THREAD

**Issue by JfranekAC** [ultralytics/yolov5#11008]
I have a dataset with structure
- *path_to_dataset*
  - files
    - images
    - labels
    - train.txt
    - val.txt
  - data.yaml

If I want to use relative paths and write the paths as :
``` yaml
train: train.txt
val: val.txt
path: ./files/
```
I'd expect YOLOv5 to interpret the paths as `*path_to_dataset*/files/train.txt`. Instead it interprets it as relative to *YOLOv5 folder* .i.e.  `*yolov5_folder*/files/train.txt`

Is that the intended behaviour?

**Comment by glenn-jocher** [comment]
@JfranekAC this behavior is expected due to how YOLOv5 interprets relative paths. To point to `*path_to_dataset*/files/train.txt`, utilize the `path` attribute in `data.yaml`:

```yaml
train: files/train.txt
val: files/val.txt
path: *path_to_dataset*/
```

For more information, consult the Ultralytics Docs. If you have further questions, feel free to ask!

**Comment by JfranekAC** [comment]
@glenn-jocher Thanks for the reply. If I remember correctly `*path_to_dataset*` has to be an absolute path, no?

The issue I was having was that I had datasets in a mounted volume. So if the mountpoint was `/path/to/first/mountpoint`, then the yaml attributes would look like this:
```
train: files/train.txt
val: files/val.txt
path: /path/to/first/mountpoint/dataset/
```

If I then had to use a differnent mountpoint f.ex.: `/second/mountpoint/`, the path attribute would be incorrect. Which made the dataset essentially non-portable.

My quick and dirty solution was to rewrite the `check_dataset` function to interpret paths relative to *path_to_dataset* instead of relative to *yolov5_folder*. That obviously broke existing dataset .yaml files so not a general solution.

**Comment by glenn-jocher** [comment]
@JfranekAC You're absolutely correct! The `*path_to_dataset*` in `data.yaml` does require an absolute path. 

To address your portability concern, I suggest using environment variables or symbolic links. You can set an environment variable for the dataset path, or create a symbolic link inside each mountpoint pointing to the dataset.

If you need further assistance with your datasets' portability, don't hesitate to reach out. I'm here to help!

**Comment by JfranekAC** [comment]
@glenn-jocher
OK, so I could create a symlink `/path/to/first/mountpoint/dataset_folder` -> `*yolov5_folder*/datasets/dataset_folder`. Then the yaml would be:
```
train: files/train.txt
val: files/val.txt
path: ./datasets/dataset_folder
```
I could then change the symlink to `/second/mountpoint/dataset_folder` -> `*yolov5_folder*/datasets/dataset_folder` and it would still work.

I don't understand how an environment variable would be used.

**Comment by glenn-jocher** [comment]
@JfranekAC Your symlink approach looks like a good solution for achieving dataset portability across different mountpoints.

Regarding using environment variables, it involves setting a variable in your environment that points to the dataset location, and then referencing that variable in the `data.yaml` file. For example:
```yaml
train: files/train.txt
val: files/val.txt
path: ${DATASET_PATH}
```
You would then set the `DATASET_PATH` environment variable to the appropriate dataset location for each mountpoint.

If you have any more questions or need further assistance, feel free to ask. I'm here to help!

**Comment by JfranekAC** [comment]
@glenn-jocher
Thank you. For now I'll stick to my quick and dirty solution, but maybe it will be useful to others.

**Comment by glenn-jocher** [comment]
@JfranekAC you're welcome! Your quick and dirty solution seems pragmatic for now. It's possible that others may find it helpful as well. If you ever need further assistance or decide to explore alternative approaches, feel free to reach out. Best of luck with your YOLOv5 project!
