### ISSUE TITLE
To get only 1 box per class label, with the higest confidence, basically what NMS does.

### ISSUE THREAD

**Issue by sairam2807** [ultralytics/yolov5#11002]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

While running the detect.py after cloning the YoLov5 repository, I am trying to get inferences. What I want to do is output only those boxes for each class that have the highest confidences. There is an option for class agnostic NMS, but this doesnt do the task required. Also how to crop only those boxes with the highest confidence for each class.

**Comment by glenn-jocher** [comment]
@sairam2807 hi there! To output only the highest confidence box per class, you can use the `--agnostic-nms` flag set to `false` (default value) in detect.py. This performs NMS independently for each class, keeping only the box with the highest confidence for each class label. To crop only those boxes with the highest confidence for each class, you can use the `--save-cropped` flag in combination with the `--conf-thres` option to specify the confidence threshold. 

For more details, you can refer to the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/. Let me know if you need further assistance!
