### ISSUE TITLE
questions about YOLOv5 source code

### ISSUE THREAD

**Issue by frabob2017** [ultralytics/yolov5#11019]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I am studying YOLOv5 source code in hope to figure out how to replace nn.conv2d to nn.conv3d.  In the yolo.py file, function def parse_model(d, ch):    line 317, I saw
  if m in {
                Conv, GhostConv, Bottleneck, GhostBottleneck, SPP, SPPF, DWConv, MixConv2d, Focus, CrossConv,
                BottleneckCSP, C3, C3TR, C3SPP, C3Ghost, nn.ConvTranspose2d, DWConvTranspose2d, C3x}:

But from yolo5l.yaml file, I only found module has Conv,C3,SPPF,  nn.Upsample, Concat, Detect. May I ask the other modules defined in common.py are actually not used in YOLOV5 such as C3SPP, C3TRC3Ghost, Focus, am I correct? 

I also saw  see a lot of module classes are not defined forward method. Does it further prove that these modules are not used in YOLOV5?   I want to understand your code and hope to I can do some modification for my application. 

![image](https://user-images.githubusercontent.com/57141860/219977386-7a7076d7-bd9d-4e73-935d-3fbe84074f8f.png)

**Comment by frabob2017** [comment]
No one answer this question?

**Comment by glenn-jocher** [comment]
@frabob2017 hi there! Thanks for taking an interest in the YOLOv5 source code. The modules mentioned such as C3, SPPF, and others are indeed in-use in YOLOv5 for different architecture variations and model sizes. 

As for the modules without a defined forward method, they are likely auxiliary components that are invoked indirectly. For implementing modifications, I recommend checking out the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/ for detailed insights into the codebase.

Feel free to reach out if you have further questions! Keep up the great work!
