### ISSUE TITLE
Do we need augmentation when using YOLOv5 as our benchmark?

### ISSUE THREAD

**Issue by yaoshanliang** [ultralytics/yolov5#11013]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have a question that when using YOLOv5 as the benchmark, do we use default hyperparameters or close all augmentations, like hsv, translate, mosaic?

**Comment by glenn-jocher** [comment]
@yaoshanliang yes, data augmentation can improve model performance, especially when training on limited or imbalanced datasets. YOLOv5 includes several built-in augmentations, such as HSV color space transformations, scaling, and mosaic data augmentation, to enhance model generalization. For further details on YOLOv5's default augmentations and configuration, please refer to the [Ultralytics YOLOv5 documentation](https://docs.ultralytics.com/yolov5/). If you have any additional questions, feel free to ask!
