### ISSUE TITLE
Train yolov5 classification on custom dataset without roboflow

### ISSUE THREAD

**Issue by SimonePietrogiacomi** [ultralytics/yolov5#11018]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to train a Yolov5 classification model. I have a 6gb dataset but, right now, my connection speed is really bad. Is there a way to prepare a custom dataset without using my (really bad) internet connection to upload files to roboflow?

### Additional

I've used the following folder structure but I don't know how to say to classify/train.py to use this folder. It keep saying "FileNotFoundError: Found no valid file for the classes .ipynb_checkpoints. Supported extensions are: .jpg, .jpeg, .png, .ppm, .bmp, .pgm, .tif, .tiff, .webp". On "data" I put the correct path to "dataset" and that's the command I use into jupyter: 
`!python3 classify/train.py --model yolov5s-cls.pt --data "/absolute/path/to/dataset" --epochs 300 --img 416`

dataset
├── train
│   ├── 0
│   │   ├── random_number.jpg
│   ├── 5
│    |    ├── random_number.jpg
│   └── 10
│          ├── random_number.jpg
├── valid
│   ├── 0
│   │   ├── random_number.jpg
│   ├── 5
│    |   ├── random_number.jpg
│   └── 10
│         ├── random_number.jpg
├── test
│   ├── 0
│   │   ├── random_number.jpg
│   ├── 5
│    |   ├── random_number.jpg
│   └── 10
│         ├── random_number.jpg

**Comment by ryouchinsa** [comment]
All images should be exported into object-named subfolders.

![スクリーンショット 2023-05-07 12 19 50](https://user-images.githubusercontent.com/1954306/236655946-f9f13a1a-d83d-49bb-ae4d-c84e0b538cdc.png)

Then, you can train the classification model.
python classify/train.py --model yolov5s-cls.pt --data ../datasets/cat-dog --epochs 5 --img 224 --batch 128

On this page, there are some examples how to train classification models.
https://github.com/ultralytics/yolov5

**Comment by glenn-jocher** [comment]
@ryouchinsa thank you for reaching out. To prepare a custom dataset, you can follow the suggested structure in the image you provided, where each image is exported into object-named subfolders. 
Regarding the error you are experiencing, the issue might be related to the ".ipynb_checkpoints" directory that Jupyter Notebook generates. You can try removing it from your dataset folder and see if the error persists.

Also, make sure you are using the correct path to the dataset folder as input for --data argument. 

If the issue still persists, please provide more details about the error message and the environment you are using so we can better assist you. 

Furthermore, there are some examples on how to train classification models on the following page:
https://github.com/ultralytics/yolov5

Please feel free to follow up if you have any other questions or concerns.
