### ISSUE TITLE
How can I detect a license plate along with a car and perform OCR in it?

### ISSUE THREAD

**Issue by sanchaykasturey** [ultralytics/yolov5#11012]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

So, I want to perform license plate recognition but also I want it to save the image of the car along with the license plate. 

Example
If there are 4 cars I want to save the images of 4 vehicles, which is possible quickly with yolo based detection, but I want to also detect license plates in the same frame, and save those images (detected license plates and cars). And then proceed further for OCR. 

Please help me with how can I save both the detections because I don't want one license plate and a car to be saved separately.

Thanks for all your time and answers.

**Comment by glenn-jocher** [comment]
@sanchaykasturey hi there! To achieve this, you can use YOLOv5 to simultaneously detect both cars and license plates in an image. Once both are identified, you can save the detected region of the car and the license plate together as separate images for further processing. You'll then have the option to perform OCR on the saved license plate images. 

For detailed guidance on performing object detection and OCR with YOLOv5, you can refer to the Ultralytics YOLOv5 documentation at https://docs.ultralytics.com/yolov5/.

Happy detecting and OCR-ing!
