### ISSUE TITLE
how do add darts(NAS searched) backbone to yolov5？

### ISSUE THREAD

**Issue by Haidong-Kang** [ultralytics/yolov5#11016]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, how do add darts (NAS searched) backbone to yolov5? Thanks

**Comment by Haidong-Kang** [comment]
Hello, https://github.com/ultralytics/yolov5/tree/darts is exsit?

**Comment by glenn-jocher** [comment]
@NEUdeep hello! We currently do not have a DARTS (Differentiable Architecture Search) backbone in the official YOLOv5 repository. However, you can customize your own backbone by modifying the model architecture definition in the YOLOv5 codebase. For guidance on creating custom models, you can refer to the "Custom Model" section in the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/. Let me know if you need further assistance.
