### ISSUE TITLE
RTSP Streaming gives Black Screen at any instant (But initiallay stream starts all Good)

### ISSUE THREAD

**Issue by hassan-mushtaq** [ultralytics/yolov5#11029]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi Everyone;
I  have found only issues that were opened uptill now on **both yolov7 and yolov5** git repositories but No solution seen 

I used source as rtsp:\local.ip + rtsp:\public.ip for yolov7 and I get black screen after few seconds of normal run. (as seen in images below)
Sometimes blackscreen comes early (in few seconds)..sometime it takes 1-2 mins
![image](https://user-images.githubusercontent.com/98469501/220158206-d1a48033-e7af-46ed-9e41-e527f2bf6943.png)
![image](https://user-images.githubusercontent.com/98469501/220158236-30fbac5f-d2bf-44a5-a167-99c6b41e1d79.png)
![image](https://user-images.githubusercontent.com/98469501/220158263-0c34e135-fda4-4d9d-a08a-4055a471fb5f.png)

Here is the link to that v7 issue posted but no response from there >>  https://github.com/WongKinYiu/yolov7/issues/1492

After researching i just found that > This part in **yolov5/utils/datasets.py** cause black screen issue when network issue is there but it does not recovers back and is stuck in black screen forever and detect.py keeps on running

```
def update(self, i, cap): 
     # Read stream `i` frames in daemon thread 
     n, f = 0, self.frames[i] 
     while cap.isOpened() and n < f: 
         n += 1 
         # _, self.imgs[index] = cap.read() 
         cap.grab() 
         if n % 4:  # read every 4th frame 
             success, im = cap.retrieve() 
             self.imgs[i] = im if success else self.imgs[i] * 0 
         time.sleep(1 / self.fps[i])  # wait time
```

The above code is as follow in **yolov7/utils)/datasets.py**
```

    def update(self, index, cap):
        # Read next stream frame in a daemon thread
        n = 0
        while cap.isOpened():
            n += 1
            # _, self.imgs[index] = cap.read()
            cap.grab()
            if n == 4:  # read every 4th frame
                success, im = cap.retrieve()
                self.imgs[index] = im if success else self.imgs[index] * 0
                n = 0
            time.sleep(1 / self.fps)  # wait time
```

**Comment by BORUIH** [comment]
I have also encountered this problem. Have you resolved it？

**Comment by glenn-jocher** [comment]
@BORUIH hi there! Thanks for reporting this issue. We've recognized this behavior and are working on a fix. In the meantime, I recommend checking your network connection quality and stability, as intermittent network issues can cause RTSP streaming to fail.

We appreciate your patience and understanding while we address this. If you need further assistance, feel free to ask!

**Comment by moralesja560** [comment]
Hi. This is my first contribution. I am not very experienced in Python, but I wanted to collaborate. I discovered this thread while investigating the issue discussed here.

I am working with YOLOv7 and found two issues, the first one is the black screen when RTSP fails, and the second one is that the RTSP stream does not recover after a network issue.

On utils>datasets.py I replaced the default update function:

``` Shell
    def update(self, index, cap):
        # Read next stream frame in a daemon thread
        n = 0
        while cap.isOpened():
            n += 1
            # _, self.imgs[index] = cap.read()
            cap.grab()
            if n == 4:  # read every 4th frame
                success, im = cap.retrieve()
                self.imgs[index] = im if success else self.imgs[index] * 0
                n = 0
            time.sleep(1 / self.fps)  # wait time
```
I made the following changes:

### Loadstream class:

Around line 288
``` Shell
cap = cv2.VideoCapture(url,apiPreference=cv2.CAP_ANY,params=[cv2.CAP_PROP_READ_TIMEOUT_MSEC, 1000])
```
around line 295
``` Shell
thread = Thread(target=self.update100, args=([i, cap,url]), daemon=True)
```
### The rewritten update function:

``` Shell
    def update100(self, index, cap,url):
        #initialize the var that keep the frame count
        n=0
        #loop start
        while True:
            try:
                exito = cap.grab()
               print(f"grab output is {exito}")
                n +=1
            except:
                print("cap.grab failed")
                time.sleep(2)
                cap = self.cap_restart(url)
                continue

            if n==5:
                #the lucky frame that is going to be processed, is stored in im
                success, im = cap.retrieve()
                #print(f"forma {np.shape(im)} y suma: {np.sum(im)} y exito {success}")
                if success:
                    self.imgs[index] = im
                else:
                    # time to restart the loop
                    print("something went wrong")
                    self.imgs[index] * 0
                    cap = self.cap_restart(url)
                n=0
            time.sleep(1 / self.fps) 
```

and the auxiliary function cap_restart
``` Shell
    def cap_restart(self,url):
        print("trying to recover cap")
        while True:
            cap2 = cv2.VideoCapture(url,apiPreference=cv2.CAP_ANY,params=[cv2.CAP_PROP_READ_TIMEOUT_MSEC, 1000])
            try:
                assert cap2.isOpened()
            except:
                print("Cannot open RTSP stream")
            else:
                print("success")
                return cap2
```

I have tested this code with my AXIS M1125 camera inside a corporate network and so far, it is doing great. When the camera gets disconnected, the thread waits 1000ms and then timeouts, calling the cap_restart indefinitely until the camera comes back online. You can modify the cap_restart function to try 10 or 20 times before raise the StopIteration error.


I share the output for these functions:
``` shell
grab output is True
grab output is True
grab output is False
grab output is False
something went wrong
trying to recover cap
[ERROR:0@58.496] global cap.cpp:166 cv::VideoCapture::open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.8.1) D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): rtsp://user:user@10.65.68.47/axis-media/media.amp in function 'cv::icvExtractPattern'


Cannot open RTSP stream
[ERROR:0@88.776] global cap.cpp:166 cv::VideoCapture::open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.8.1) D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): rtsp://user:user@10.65.68.47/axis-media/media.amp in function 'cv::icvExtractPattern'


Cannot open RTSP stream
success
grab output is True
```
After this, the stream recovers successfully.

**Comment by BORUIH** [comment]
Thank you very much！

**Comment by glenn-jocher** [comment]
@BORUIH Thank you for sharing your solution! It's great to see the YOLO community coming together to find workarounds. We appreciate your efforts and contribution. If you have any further insights or need assistance, feel free to reach out. Your input is valuable to us!
