### ISSUE TITLE
Training with --evolve argument

### ISSUE THREAD

**Issue by saitarslanboun** [ultralytics/yolov5#1102]
## ❔Question
Hi!

I am curious. I am planning to use --evolve argument for training.

Do you still keep number of epochs for 300 epochs when you use evolve? Since there are 300 generations to evolve, it means if we have 300 epochs for training, for each generation we train for 300 epochs, at total with all generations we train 300x300 epochs.

Or, you keep number of epochs 1? So if there are 300 generations to evolve, at total we still keep number of epochs 300.

**Comment by glenn-jocher** [comment]
@saitarslanboun you evolve a baseline scenario (epochs, dataset, model etc). This baseline scenario is up to you.
