### ISSUE TITLE
How to strip .pt file?

### ISSUE THREAD

**Issue by MasIgor** [ultralytics/yolov5#11027]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello!

I have seen it somewhere a few months ago, but was not able to find it anymore. How can i strip a pt file if my previous training did not reach the final epoch where the stripping is automatic?

thank you!

**Comment by adeel-learner** [comment]
https://github.com/ultralytics/yolov5/issues/7582#issuecomment-1109226922

**Comment by glenn-jocher** [comment]
@adeel-maker hi! To strip a .pt file manually, you can use the following command:
```bash
python -c "import torch; model = torch.hub.load('ultralytics/yolov5', 'custom', path='path/to/your.pt') ['model'].yaml; model.save('path/to/save_stripped_model')"
```
This will strip the .pt file and save the stripped model to the specified path.
Let me know if you need further assistance!
