### ISSUE TITLE
How to run YoloV5 python project on iOS devices without converting to swift

### ISSUE THREAD

**Issue by Razamalik4497** [ultralytics/yolov5#11025]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

https://user-images.githubusercontent.com/49755089/220068075-66df8a8c-a3e7-45c1-ad0d-1ed4ef2538f8.mp4

### Additional

Hi developers & authors, 
I have built my badminton application based on yolov5 detector & I used the tracking & pose estimation model in my project & which runs on python. 

I want to know how can I use my python project to run on iOS devices without converting code python to swift.
for example, I have made many changes in the yolov5 code in every file now It's hard to convert the whole code into swift. Is there any way to run a python project on iOS without converting to swift?
Thanks,
Raza

**Comment by glenn-jocher** [comment]
@Razamalik4497 you can export to CoreML for use in iOS apps. Most of the model/code is self-contained inside the CoreML model.

**Comment by Razamalik4497** [comment]
Hi glenn, thanks for your reply.
Actually its hard to explain. I have successfully convert to coreml & its running well on iOS too. but I also want to get my output from python which is written in yolov5 detect.py. thanks

**Comment by glenn-jocher** [comment]
@Razamalik4497 you can run your YOLOv5 detection script as a separate Python process, communicate the results to your iOS app via an API, and then display the results in your app.
