### ISSUE TITLE
ModuleNotFoundError: No module named 'models.experimental

### ISSUE THREAD

**Issue by dreamitpossible1** [ultralytics/yolov5#1103]
## ❔Question
I am try to run :
!python models/export.py --weights yolov5s.pt --img 640 --batch 1 # export

and got an error:

Traceback (most recent call last):
  File "models/export.py", line 16, in <module>
    from models.experimental import attempt_load
ModuleNotFoundError: No module named 'models.experimental'
## Additional context
Everything else is normal. It feels strange

**Comment by glenn-jocher** [comment]
@dreamitpossible1 your code is likely out of date. Reclone and try again.
