### ISSUE TITLE
How can i use yolov5s-cls to train a pretrained model from the library Lightly ? 

### ISSUE THREAD

**Issue by arkerman** [ultralytics/yolov5#11039]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I wanna use a library called Lightly to achieve a pretrained model for yolovv5s-cls to use . Does yolov5 support this ? Any replies will be appreciated . 

### Additional

The link of Lightly : https://github.com/lightly-ai/lightly

**Comment by glenn-jocher** [comment]
@arkerman hi there! YOLOv5 does not currently support using Lightly for training a pretrained model with yolov5s-cls. However, you can train yolov5s-cls with your custom dataset using the instructions provided in the documentation at https://docs.ultralytics.com/yolov5/. Should you have any further questions, feel free to ask. Good luck with your project!
