### ISSUE TITLE
Images values after augmentation

### ISSUE THREAD

**Issue by Tautvydas-byte** [ultralytics/yolov5#11036]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to print or get the number of generated images after each epoch. Because it is interesting how bigger dataset become after augmentation and or albumentation.

**Comment by glenn-jocher** [comment]
@Tautvydas-byte hey there! It's great to hear that you're interested in monitoring the number of generated images after each augmentation epoch. You can achieve this by customizing your training loop to print or log the number of augmented images. You may also consider exploring the data loaders and augmentations provided by libraries such as Albumentations to monitor the transformation of your dataset. Feel free to check out the YOLOv5 documentation for further guidance on customizing your training pipeline. Happy training!
