### ISSUE TITLE
Yolo v5 Matches Positive Samples

### ISSUE THREAD

**Issue by GENERjia** [ultralytics/yolov5#11030]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When Yolo v5 matches positive samples, it will assign groundtruth to multiple anchors as positive samples. Does this mean that there are more anchors responsible for predicting objects, which will increase the workload of non-maximum suppression

**Comment by glenn-jocher** [comment]
@GENERjia hi there! Thanks for reaching out.

When YOLOv5 matches positive samples, it assigns ground truth to multiple anchors as positive samples. This indeed means that there are more anchors responsible for predicting objects, which can potentially increase the workload of non-maximum suppression. However, this approach also contributes to better detection accuracy.

For more details on this and other YOLOv5 functionalities, you can visit the Ultralytics Docs at https://docs.ultralytics.com/yolov5/.

Let me know if you have any more questions!
