### ISSUE TITLE
Combine "head" of two different with same "backbone"

### ISSUE THREAD

**Issue by vardanagarwal** [ultralytics/yolov5#11038]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have two models. The second model is trained on different classes by freezing the backbone of the first model. Is it possible to combine the two models such that the input passes through the common backbone and divulges into two head layers followed by their respective detect layers? 

The goal of this is to reduce inference times. I have created a sample model yaml file on how the architecture could look like.

```
# YOLOv5 🚀 by Ultralytics, GPL-3.0 license

# Parameters
nc: 80  # number of classes
depth_multiple: 0.33  # model depth multiple
width_multiple: 0.50  # layer channel multiple
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

# YOLOv5 v6.0 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [64, 6, 2, 2]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C3, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 6, C3, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, C3, [512]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 3, C3, [1024]],
   [-1, 1, SPPF, [1024, 5]],  # 9
  ]

# YOLOv5 v6.0 head
head:
  [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, C3, [512, False]],  # 13

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, C3, [256, False]],  # 17 (P3/8-small)

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 14], 1, Concat, [1]],  # cat head P4
   [-1, 3, C3, [512, False]],  # 20 (P4/16-medium)

   [-1, 1, Conv, [512, 3, 2]],
   [[-1, 10], 1, Concat, [1]],  # cat head P5
   [-1, 3, C3, [1024, False]],  # 23 (P5/32-large)

  #  [[17, 20, 23], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)

   [9, 1, Conv, [512, 1, 1]], # 24
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, C3, [512, False]],  # 27

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, C3, [256, False]],  # 31 (P3/8-small)

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 28], 1, Concat, [1]],  # cat head P4
   [-1, 3, C3, [512, False]],  # 34 (P4/16-medium)

   [-1, 1, Conv, [512, 3, 2]],
   [[-1, 24], 1, Concat, [1]],  # cat head P5
   [-1, 3, C3, [1024, False]],  # 37 (P5/32-large)

   [[17, 20, 23], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
   [[31, 34, 37], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
  ]
```

**Comment by glenn-jocher** [comment]
@vardanagarwal sure, this is possible with "YOLOv5" ! Your proposed architecture seems suitable for the task. The YOLOv5 framework is designed to easily combine different model components like backbones and heads. Your description aligns with the YOLOv5 capabilities, enabling efficient inference by sharing a common backbone while applying separate head layers for different tasks. If you encounter any issues during implementation, feel free to consult the YOLOv5 documentation for guidance: https://docs.ultralytics.com/yolov5/. Good luck with your project!

**Comment by jain-abhay** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.
> 
> ### Question
> I have two models. The second model is trained on different classes by freezing the backbone of the first model. Is it possible to combine the two models such that the input passes through the common backbone and divulges into two head layers followed by their respective detect layers?
> 
> The goal of this is to reduce inference times. I have created a sample model yaml file on how the architecture could look like.
> 
> ```
> # YOLOv5 🚀 by Ultralytics, GPL-3.0 license
> 
> # Parameters
> nc: 80  # number of classes
> depth_multiple: 0.33  # model depth multiple
> width_multiple: 0.50  # layer channel multiple
> anchors:
>   - [10,13, 16,30, 33,23]  # P3/8
>   - [30,61, 62,45, 59,119]  # P4/16
>   - [116,90, 156,198, 373,326]  # P5/32
> 
> # YOLOv5 v6.0 backbone
> backbone:
>   # [from, number, module, args]
>   [[-1, 1, Conv, [64, 6, 2, 2]],  # 0-P1/2
>    [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
>    [-1, 3, C3, [128]],
>    [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
>    [-1, 6, C3, [256]],
>    [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
>    [-1, 9, C3, [512]],
>    [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
>    [-1, 3, C3, [1024]],
>    [-1, 1, SPPF, [1024, 5]],  # 9
>   ]
> 
> # YOLOv5 v6.0 head
> head:
>   [[-1, 1, Conv, [512, 1, 1]],
>    [-1, 1, nn.Upsample, [None, 2, 'nearest']],
>    [[-1, 6], 1, Concat, [1]],  # cat backbone P4
>    [-1, 3, C3, [512, False]],  # 13
> 
>    [-1, 1, Conv, [256, 1, 1]],
>    [-1, 1, nn.Upsample, [None, 2, 'nearest']],
>    [[-1, 4], 1, Concat, [1]],  # cat backbone P3
>    [-1, 3, C3, [256, False]],  # 17 (P3/8-small)
> 
>    [-1, 1, Conv, [256, 3, 2]],
>    [[-1, 14], 1, Concat, [1]],  # cat head P4
>    [-1, 3, C3, [512, False]],  # 20 (P4/16-medium)
> 
>    [-1, 1, Conv, [512, 3, 2]],
>    [[-1, 10], 1, Concat, [1]],  # cat head P5
>    [-1, 3, C3, [1024, False]],  # 23 (P5/32-large)
> 
>   #  [[17, 20, 23], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
> 
>    [9, 1, Conv, [512, 1, 1]], # 24
>    [-1, 1, nn.Upsample, [None, 2, 'nearest']],
>    [[-1, 6], 1, Concat, [1]],  # cat backbone P4
>    [-1, 3, C3, [512, False]],  # 27
> 
>    [-1, 1, Conv, [256, 1, 1]],
>    [-1, 1, nn.Upsample, [None, 2, 'nearest']],
>    [[-1, 4], 1, Concat, [1]],  # cat backbone P3
>    [-1, 3, C3, [256, False]],  # 31 (P3/8-small)
> 
>    [-1, 1, Conv, [256, 3, 2]],
>    [[-1, 28], 1, Concat, [1]],  # cat head P4
>    [-1, 3, C3, [512, False]],  # 34 (P4/16-medium)
> 
>    [-1, 1, Conv, [512, 3, 2]],
>    [[-1, 24], 1, Concat, [1]],  # cat head P5
>    [-1, 3, C3, [1024, False]],  # 37 (P5/32-large)
> 
>    [[17, 20, 23], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
>    [[31, 34, 37], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
>   ]
> ```
> 
> ### Additional
> _No response_

Hi @vardanagarwal , were you able to successfully build a model with a common backbone and 2 different heads? I am currently researching on a similar problem, it would be really helpful if you could share some inputs. Thanks in advance

**Comment by vardanagarwal** [comment]
@jain-abhay no i wasn't able to achieve it completely, and as I was doing it during my job, I don't have the progress that I had made in it. 

However, if you are able to do it, and can open source it let me know, would love to know what worked.

**Comment by jain-abhay** [comment]
Sure @vardanagarwal , is it possible if you can just share me some thoughts/methods on how to proceed this. Actually, I am currently researching on Face Detection and Person Detection Models using YOLOv5. The current model has a single backbone and single head but I was experimenting if we can have a model that has a common backbone with 2 different heads (one for only Face Detection and the other for Person Detection).
It would be really helpful if you kindly guide. Thanks
