### ISSUE TITLE
Export TensorRT with --half and --dynamic flags

### ISSUE THREAD

**Issue by nicoacevedor** [ultralytics/yolov5#11033]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm trying to export a custom model to TensorRT. At first I tried using --half flag and --batch-size 32, but if I try the inference with a batch of less than 32, let's say 11, I have this error:
**AssertionError: input size torch.Size([11, 3, 640, 640]) not equal to max model size (32, 3, 640, 640)**

After that, I tried exporting it using the --dynamic flag, but it is incompatible with the --half flag:
**AssertionError: --half not compatible with --dynamic, i.e. use either --half or --dynamic but not both**

Is there a way to export the model using --half and that it accepts a dynamic batch size?

**Comment by nicoacevedor** [comment]
Hi! I looked into all the documentation and I still cannot find a solution to this.

**Comment by atomrun39** [comment]
`AssertionError: input size torch.Size([8, 3, 640, 640]) not equal to max model size (16, 3, 640, 640)`
I convert onnx to the engine of batch-size 16 and run val.py，then I also met the same problem. How can i solve it?

**Comment by glenn-jocher** [comment]
@atomrun39 yes, to use a dynamic batch size with --half in TensorRT, you can enable TRT dynamic batching with the command flag --dynamic to allow variable batch sizes. However, please ensure to not use --half and --dynamic flags together, as they are not compatible. Instead, you should choose either --half or --dynamic, but not both. This should help resolve the issue you are encountering.
