### ISSUE TITLE
If my classes of interest are a subset of the 80 classes in COCO, should I retrain on a subset, or configure detect.py with a subset

### ISSUE THREAD

**Issue by davesargrad** [ultralytics/yolov5#11031]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to ensure that detect.py only reports detections (bounding boxes and labels) on a subset of the 80 classes in COCO. Currently we are training on the full set of 80 classes. Yet in our domain most of the classes will never show up in our imagery.

Yet sometimes detect.py will detect and assign the "blacklisted labels" that should never show up. 

Of the following three approaches, which is likely to give us the best detection and classification performance on a subset of classes:

1. Training (from random starting point) on a subset of classes
2. Training the last layer on a subset of classes
3. Running detect.py with a "blacklist" of the classes that are not of interest, so that it can then eliminate them.

**Comment by hassan-mushtaq** [comment]
Use **'--classes'** argument in your CLI 
Example 
**python detect.py --weights yolov5s.pt --source 0 _--classes 0 1 6 24 80_**

Thus you can filter out only those class number that you want

**Comment by davesargrad** [comment]
@hassan-mushtaq  Thats useful for sure. Thanks. I was trying to get a sense of how that would compare to retraining using the same subset of interest. At this point we've decided to try out the option that you highlight, along with the option of retraining the entire model from scratch, using just the subset of interest. 

We will compare and contrast the performance that we see.
