### ISSUE TITLE
please, how can I evaluate yolov5 for just 20 classes instead of 80 classes ?

### ISSUE THREAD

**Issue by abdelkader30000** [ultralytics/yolov5#11044]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

please, how can I evaluate yolov5 for just 20 classes instead of 80 classes ?

**Comment by smalik89** [comment]
Hi @abdelkader30000 ! You can update the 'nc' parameter in the .yaml file for your desired number of classes. Here is a video as well: https://www.youtube.com/watch?v=GRtgLlwxpc4

**Comment by abdelkader30000** [comment]
thank you for your responce, but I want to evaluate the model without training with new classes, I want to evaluate it with my own dataset, my images are labelled only with 20 classes: person, car, chair, dining table ..., the classes that yolov5 is trained with, I tried to evaluate it directly but the recall value was very low

**Comment by abdelkader30000** [comment]
@smalik89  I hope my question was clear, thanks
