### ISSUE TITLE
How to specify image size when training yolov5 on a custom dataset with varying image sizes?

### ISSUE THREAD

**Issue by RuthKassahun** [ultralytics/yolov5#11040]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am currently working on training a yolov5 detector on a custom dataset with each image having a different size. While reading through the yolov5 documentation and various tutorials, I am not sure how to specify the image size during training.

I have tried looking for answers on StackOverflow and GitHub discussions, but I am still unsure how to proceed. Does anyone have experience training yolov5 on a custom dataset with varying image sizes and can offer guidance on how to specify the image size during training?

Any help or suggestions would be greatly appreciated!

**Comment by glenn-jocher** [comment]
@RuthKassahun hi there! When training YOLOv5 on a custom dataset with varying image sizes, you can specify the image size using the `--img-size` flag in the training command. For example, to set the image size to 640x640, you can use `--img-size 640`.

The Ultralytics Docs at https://docs.ultralytics.com/yolov5/ provide detailed information on training configurations, including how to handle varying image sizes.

I hope this helps! If you have any more questions, feel free to ask. Good luck with your YOLOv5 training!

**Comment by RuthKassahun** [comment]
Hi Glenn, thank you very much for the explanation. I've trained on different versions on yolo and yolov8 works really well. Keep up the good work.

**Comment by glenn-jocher** [comment]
@RuthKassahun thank you for the kind words! I'm glad to hear that YOLOv8 is working well for you. The YOLO community and the Ultralytics team have put in a lot of effort to make these models successful. If you have any more questions or need further assistance, feel free to reach out. Good luck with your YOLO projects!
