### ISSUE TITLE
No results.csv or results.png outputted

### ISSUE THREAD

**Issue by gabriel-lipkowitz** [ultralytics/yolov5#11057]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

After training yolov5s on my custom dataset, I'm given the usual F1_curve, P_curve, PR_curve, and R_curve graphs (as png files), but am not given a results.csv or results.png file. Am I missing a parameter or argument that needs to be set to output this file too? Thank you.

**Comment by glenn-jocher** [comment]
@gabriel-lipkowitz hi there! The `results.csv` and `results.png` files are actually not generated by default. To output these files, run `python train.py --save-txt --save-conf --save-hybrid --save-plot`, which will save the per-class confusion matrices in a results .csv file and PR and P-R curves in a results .png file. For more details, please refer to the [Ultralytics Docs](https://docs.ultralytics.com/yolov5/). Happy training!

**Comment by jimuIee** [comment]
> @gabriel-lipkowitz hi there! The `results.csv` and `results.png` files are actually not generated by default. To output these files, run `python train.py --save-txt --save-conf --save-hybrid --save-plot`, which will save the per-class confusion matrices in a results .csv file and PR and P-R curves in a results .png file. For more details, please refer to the [Ultralytics Docs](https://docs.ultralytics.com/yolov5/). Happy training!

usage: train.py [-h] [--weights WEIGHTS] [--cfg CFG] [--data DATA] [--hyp HYP] [--epochs EPOCHS] [--batch-size BATCH_SIZE] [--imgsz IMGSZ] [--rect] [--resume [RESUME]]
                [--nosave] [--noval] [--noautoanchor] [--evolve [EVOLVE]] [--bucket BUCKET] [--cache [CACHE]] [--image-weights] [--device DEVICE] [--multi-scale] [--single-cls]
                [--adam] [--sync-bn] [--workers WORKERS] [--project PROJECT] [--name NAME] [--exist-ok] [--quad] [--linear-lr] [--label-smoothing LABEL_SMOOTHING]
                [--patience PATIENCE] [--freeze FREEZE [FREEZE ...]] [--save-period SAVE_PERIOD] [--local_rank LOCAL_RANK] [--entity ENTITY] [--upload_dataset [UPLOAD_DATASET]]
                [--bbox_interval BBOX_INTERVAL] [--artifact_alias ARTIFACT_ALIAS]
train.py: error: unrecognized arguments: --save-txt --save-conf --save-hybrid --save-plot
could u help me how to solve this error
