### ISSUE TITLE
 How to find the AP，Precision and  recall of each class ?

### ISSUE THREAD

**Issue by xingguang12** [ultralytics/yolov5#11053]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When I am training, I want to know the AP, P and R of each detection category, how can I modify the code to automatically display them every training epoch?

**Comment by dmddmd** [comment]
can't you answer this, please?

**Comment by glenn-jocher** [comment]
@dmddmd hello, I apologize, but I cannot see the previous question as it has already been marked as stale. Please provide the question again, and I will do my best to provide a helpful response. Alternatively, you could refer to the resources provided in the message above to find answers to common YOLOv5 questions.

**Comment by zehranrgi** [comment]
> can't you answer this, please?

maybe something like... 

```
from utils.metrics import ap_per_class, precision_recall
from utils.general import plot_results
```


at the epoch part in train.py:  for epoch in range(start_epoch, epochs):

```
ap_class = []
p_class = []
r_class = []


if RANK in {-1, 0}:
    mloss = (mloss * i + loss_items) / (i + 1)  # mean losses
    mem = f'{torch.cuda.memory_reserved() / 1E9 if torch.cuda.is_available() else 0:.3g}G'  
    pbar.set_description(('%11s' * 2 + '%11.4g' * 5) %
                         (f'{epoch}/{epochs - 1}', mem, *mloss, targets.shape[0], imgs.shape[-1]))
    callbacks.run('on_train_batch_end', model, ni, imgs, targets, paths, list(mloss))
    if callbacks.stop_training:
        return
    
    # Compute AP, P, and R. 
    if ni == nb * epoch + len(train_loader) - 1:
        with torch.no_grad():
            stats, ap, p, r = ap_per_class(model, train_loader.dataset, imgsz=imgsz)
            ap_class.append(ap)
            p_class.append(p)
            r_class.append(r)
            LOGGER.info(stats)

```
and, then you may plot the results with plot_results and save them as jpg. 

But as you can see, they import the val to calculate the mAP, it generally goes on the validation dataset, not the train set.

**Comment by zehranrgi** [comment]
> When I am training, I want to know the AP, P and R of each detection category, how can I modify the code to automatically display them every training epoch?

the question was: 
''When I am training, I want to know the AP, P and R of each detection category, how can I modify the code to automatically display them every training epoch?''

**Comment by glenn-jocher** [comment]
Hello @zehranrgi,

To display the AP, P, and R of each detection category for every training epoch, you can make use of the `ap_per_class` function from `utils.metrics` module. You can include this function inside the for loop which is used to loop through each epoch in the `train.py` file and then display these metrics in the command line. Here is a sample code snippet:

```
from utils.metrics import ap_per_class

#Inside the train function
for epoch in range(epochs):
    for i, (imgs, targets, paths, _) in enumerate(train_loader):
        # your code for training the model
        # ...
        # ...
        #Calculate AP, P, and R for each class at the end of the epoch
        if i == len(train_loader) - 1:
            # Calculate AP, P, and R for each class
            with torch.no_grad():
                stats, ap, precision, recall = ap_per_class(model, train_loader.dataset, img_size=imgsz)

            #Format and display AP, P, and R values for each class
            for idx, category_name in enumerate(train_loader.dataset.categories):
                print(f"Epoch: {epoch}, Class: {category_name}, AP: {ap[idx]:.4f}, P: {precision[idx]:.4f}, R: {recall[idx]:.4f}")
```

The above code calculates the AP, P, and R for each class and displays them in the command line. I hope this helps. 

Let me know if you have any further queries.
