### ISSUE TITLE
 Problems with installation on Win10

### ISSUE THREAD

**Issue by TDVL** [ultralytics/yolov5#11054]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello Glenn,
I have tried to install yolov5 on Win10 using Command Prompt.
The git operation was OK, however after I have started the installation with "pip install -r requirements.txt" I have got an error.
The image is attached.
How can I fix this.
Thank you.
![image](https://user-images.githubusercontent.com/47524135/220935292-31cc7cc6-9fec-4bb5-9e57-cade85852d8e.png)

**Comment by harisbuilds** [comment]
Hey @TDVL. Have you tried upgrading your pip version?

**Comment by TDVL** [comment]
Hello,
Yes, I have. However that was not the problem.
The latest Python version was the problem, the installation of an earlier version of Python solved the problem.

**Comment by glenn-jocher** [comment]
@TDVL that's great to hear! I'm glad you were able to resolve the issue by installing an earlier version of Python. If you have any more questions or need further assistance, feel free to ask. Thank you for your understanding, and we appreciate your support!
