### ISSUE TITLE
Yolo 5 out of date 

### ISSUE THREAD

**Issue by AmirAzz** [ultralytics/yolov5#11060]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

Hi , I use yolo 5 for object detection and when I want to start Train this error comes:  

github: ⚠️ YOLOv5 is out of date by 36 commits. Use `git pull` or `git clone [https://github.com/ultralytics/yolov5`](https://github.com/ultralytics/yolov5%60) to update.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@AmirAzz removed bug label as there is no bug. 

Update your code following the instructions or use out of date code, up to you.
