### ISSUE TITLE
Unable to load mjpeg stream

### ISSUE THREAD

**Issue by sharkyenergy** [ultralytics/yolov5#11063]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

I have a IP camera, that outputs a mjpeg stream. it can be accessed via browser like this:

http://192.168.0.125/640x480.mjpeg

this will load a page with the stream in it. 

but if I try to send it to yolov5 with this comand:

python f:/python/sentry/yolov5/detect.py --weights yolov5s.pt --source http://192.168.0.125/640x480.mjpeg

it fails. Is there a way to load this stream? (see screenshot below, it just hangs there..)
alternatively, it would be an option to download the jpg, so same source as above but jpg at the end instead of mjpeg. that contains the proper current image on every refresh.. currently tough, if i pass that as source, it save a single image to the runs folder and that was it. would need it to be like a stream..

any help appreciated on this.. thank you!

![image](https://user-images.githubusercontent.com/24428068/221359025-8c63ed60-8f4b-4e54-acfe-660e0ea59477.png)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@sharkyenergy hi there! Thanks for reaching out. The `--source` argument currently supports file, image, directory, and webcam inputs, but not MJPEG streams directly. 

To work with an MJPEG stream, you can try using a package like `opencv-python` to read the MJPEG stream from the IP camera and then feed the frames to YOLOv5 for detection. Alternatively, you can use software like VLC to transcode the MJPEG stream into images, and then use those images as the input source for YOLOv5.

As for the option to download a JPG, you can continuously download and process the JPG images from the IP camera by running a loop to fetch the images at regular intervals using `requests` or a similar library.

Hope this helps! If you have further questions, feel free to ask!
