### ISSUE TITLE
Data sharing requests

### ISSUE THREAD

**Issue by 13604828410** [ultralytics/yolov5#11076]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello author, can you share the data table file in the indicator panel of the YOLOv5s model in the YOLOv5_v61_official project on wandb, thank you, I need to write a paper comparison, thank you！ @glenn-jocher

### Additional

![image](https://user-images.githubusercontent.com/51470903/221564082-8a566194-d00d-44d3-acde-8c50d5dcd29c.png)

It is the performance index file in CSV format in the circle panel on the figure     @glenn-jocher

**Comment by 13604828410** [comment]
In the following link, all 4 metric profiles in the performance panel are required, thank you   @glenn-jocher
https://wandb.ai/glenn-jocher/YOLOv5_v61_official/runs/zbp9q48q?workspace=user-zwh0

**Comment by glenn-jocher** [comment]
@13604828410 hi there! Thanks for your interest in YOLOv5. 🚀 The data you are looking for can be found in the Ultralytics Docs at https://docs.ultralytics.com/yolov5/. If you have any further questions, feel free to ask. Good luck with your paper comparison! 📝
