### ISSUE TITLE
Get train information from existing model

### ISSUE THREAD

**Issue by PetervanLunteren** [ultralytics/yolov5#11075]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi Yolov5 team, thanks for all the great work you've done so far!

I was wondering whether there is a way of getting information about how an existing custom yolov5 model was trained. For example, I would like to know the model version / release, on which image size the model was trained, and the hyperparameters used.

I was hoping for something like this:

```
# load model
model = torch.hub.load('./yolov5', 'custom', path='./custom_model.pt', source='local')

# get train specifications
model.get_train_specs()

# Output:
#    Model version: 6.1
#    Trained on image size: 1280
#    Hyperparameters used during training:
#        lr0: 0.01
#        lrf: 0.2
#        momentum: 0.937
#        […]
```
Thanks!

**Comment by glenn-jocher** [comment]
@PetervanLunteren hi there! Thanks for reaching out and your kind words! 😊 

Currently, there isn't a method like `get_train_specs()` available in the YOLOv5 repo. However, you can find detailed information regarding training specifications and hyperparameters used in the training process in the training command history and the `*.yaml` file used for training, typically located in the `runs/train/exp` directory.

For more details on the model training process and specifications, please refer to the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/. Let me know if you have any further questions!
