### ISSUE TITLE
I need a answer

### ISSUE THREAD

**Issue by Thunderboltn** [ultralytics/yolov5#11071]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When I enter: py lunar.py (Lunar softaim, which uses Yolov5) it comes with an error saying: Exception: [Errno 22] Invalid argument: 'lib\x08est.pt'. Cache may be out of date, try `force_reload=True` or see https://github.com/ultralytics/yolov5/issues/36 for help.

I wanted to ask this because it said come here for help.

**Comment by ExtReMLapin** [comment]
>I wanted to ask this because it said come here for help.

they lied

**Comment by glenn-jocher** [comment]
@ExtReMLapin hi there! Sorry to hear about the trouble. The error message you're seeing seems related to a cache issue. If you haven't already, trying using the `force_reload=True` flag as suggested, or check our documentation for further guidance. Let me know if that helps!
