### ISSUE TITLE
 xyxy_to_bbox,plot_one_box 

### ISSUE THREAD

**Issue by Manavmahilang** [ultralytics/yolov5#11072]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

what happened to these functions i have ben trying to find them i previously used them in a program which i tried to run today but in another device these. i just  cannot find them

**Comment by SheeppLi** [comment]
Hey have you find them? Maybe they are replaced after updating but I can't find where they are.

**Comment by glenn-jocher** [comment]
@SheeppLi hello! Can you please provide more details about the functions you're referring to and where you saw them before? With that information, I can try to help you locate them in the YOLOv8 repo. It's possible they might have been removed, renamed or moved to a different file or directory. In the meantime, feel free to explore the YOLOv8 codebase or check out the documentation to learn more about the different functions and their use cases.

**Comment by SheeppLi** [comment]
@glenn-jocher Sure! I want to use YOLOv8 in mmDetection and I find the plot_one_box function in CSDN, and the code is: plot_one_box(xyxy, img0, label=label, color=(0, 255, 0), line_thickness=2). I think it aims to draw bounding boxes on output image with labels, and I also find another function used in the program such as scale_coords (scale_boxes in YOLOv8) and there are comments saying that these functions are renamed after updating.

**Comment by glenn-jocher** [comment]
Hi @SheeppLi, thanks for letting us know about your concerns regarding using YOLOv8 with mmDetection.  We're happy to help you locate these functions in the codebase. The `plot_one_box` function is a custom function, not from YOLOv5 nor YOLOv8. It is possible that the original code you came across was written for YOLOv5 and you are now trying to use it with YOLOv8 which may have slight code differences. For YOLOv8, we offer the  `plot_boxes()` function which works similarly to `plot_one_box`. Similarly, `scale_coords()` has been renamed to `scale_coords()` in YOLOv8. Please refer to the updated YOLOv8 documentation for more information and examples on how to use these functions. Let me know if there is anything further I can help you with!

**Comment by SheeppLi** [comment]
@glenn-jocher Hum I didn't find the plot_boxes() function, would you please let me know which file it actually locates?

**Comment by glenn-jocher** [comment]
@SheeppLi, thank you for trying to use YOLOv8! The `plot_boxes` function in YOLOv8 is located in the `utils\general.py` file. Here's a sample code that shows how to use the `plot_boxes` function:

```
from utils.general import plot_boxes

# Coordinates of bounding box
xyxy = [10, 10, 20, 20]
img_file = "path/to/image/file.jpg"

# Plot bounding box on image
plot_boxes(img_file, [xyxy], color=(0, 255, 0), line_thickness=2)
```
Make sure that you have installed all the required dependencies listed in the README before running the code. I hope that helps!

**Comment by SheeppLi** [comment]
![1682661774940](https://user-images.githubusercontent.com/94896151/235067075-a9ac4444-f86c-4920-8053-9bd8d8eea7c1.png)
@glenn-jocher Sorry I can't find the general.py in utils folder, neither in previous version nor in the latest version.

**Comment by glenn-jocher** [comment]
Hello @SheeppLi, I'm sorry to hear that you are still having trouble finding the `general.py` file in the `utils` folder of the YOLOv5 repository. 

Please make sure that you have cloned the latest version of YOLOv5, which is available on our GitHub repository. You can find it at https://github.com/ultralytics/yolov5/. 

If you are still unable to find the `general.py` file, you can try searching the entire repository for the file using the search functionality on GitHub. To do this, simply navigate to the YOLOv5 repository and type "general.py" into the search bar. 

If you are still unable to locate the `general.py` file, please let me know and I will do my best to help you find it.

**Comment by SheeppLi** [comment]
@glenn-jocher, ah my fault, I search it in YOLOv8. Thank you very much for your help!

**Comment by glenn-jocher** [comment]
You're welcome, @SheeppLi! I'm glad I could help you locate the `plot_boxes` function in YOLOv5. If you have any more questions please don't hesitate to ask. Have a great day!
