### ISSUE TITLE
Disabling check_pip_update() in an offline environment

### ISSUE THREAD

**Issue by limwenyao** [ultralytics/yolov5#11083]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am running yolov8 installed within a container. I am running the container in a non-internet environment. It is installed with the requirements.txt and ultralytics pip library, and a local copy of yolov8m.pt. I have a simple train.py file:

‘’’
from ultralytics import YOLO
model = YOLO(“yolov8m.pt”)
model.train(data=“coco.yaml”, imgsz=640)
‘’’

In the training logs, I can see that initialization of ultralytics/yolo/engine/model.py includes self._check_pip_update() and the code fails here as I do not have access to pip repo in this environment.  Is there arguments we can use rather than commenting out the line in the source code?

**Comment by limwenyao** [comment]
I just realized this is YOLOv5 repo. Will be closing and posting in the right repo.

**Comment by glenn-jocher** [comment]
@limwenyao no worries! Feel free to reach out if you have any questions related to YOLOv5 in the future. Good luck with your project!
