### ISSUE TITLE
Train + inference at 4K

### ISSUE THREAD

**Issue by Pedro-Leitek** [ultralytics/yolov5#11086]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I was wondering, is it possible to train yolov5m6 with 4K images? I mean without resizing?
If not, can I still do inference with a full 4K image?

Thanks

**Comment by bryanbocao** [comment]
I had a similar question https://github.com/ultralytics/yolov5/issues/10998

**Comment by glenn-jocher** [comment]
@bryanbocao thanks for reaching out! Yes, YOLOv5 supports training with 4K images without resizing. Additionally, it also allows inference with full 4K images. You can find more details in the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/. Let me know if there's anything else I can help you with!
