### ISSUE TITLE
No labels found in /home/wlixill/datasets/armor/labels/train2017.cache, can not start training.

### ISSUE THREAD

**Issue by wlixill** [ultralytics/yolov5#11085]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

数据集格式完全正确，已经生成imges的cache但是不能生成lables的cache 从而找不到

### Environment

yoloV5
ubuntu 20.04

### Minimal Reproducible Example

WARNING ⚠️ No labels found in /home/wlixill/datasets/armor/labels/train2017.cache. See https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data
train: WARNING ⚠️ Cache directory /home/wlixill/datasets/armor/labels is not writeable: [Errno 2] No such file or directory: '/home/wlixill/datasets/armor/labels/train2017.cache.npy'
AssertionError: train: No labels found in /home/wlixill/datasets/armor/labels/train2017.cache, can not start training. See https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by wlixill** [comment]
python=3.10.9

**Comment by bryanbocao** [comment]
It would be more clear if you post your <data.yaml> and dataset structure here.

**Comment by Grula** [comment]
I had same issue, in train/test/val.txt make sure you name images with current dir included
./images/img0.jpg
./images/img1.jpg
...
That resolved issue for me

**Comment by glenn-jocher** [comment]
@Grula thanks for sharing your solution! Including the current directory in the image paths in the train/test/val.txt file is indeed an important step, and it's great to hear that it resolved the issue for you. If you have any more questions or need further assistance, feel free to ask. Good luck with your YOLOv5 training!
