### ISSUE TITLE
How to crop and save the detected target image in detect.py

### ISSUE THREAD

**Issue by Serendipit2024** [ultralytics/yolov5#11089]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to crop and save the detected target image in detect.py

**Comment by glenn-jocher** [comment]
@Serendipit2024 hi there! You can crop and save the detected target image in `detect.py` by adjusting the code to extract the bounding box coordinates from the detected results using `pred.xyxy`. Then, use the coordinates to crop the image and save it using standard Python image processing libraries like OpenCV or PIL. For more details and code examples, you can refer to the documentation at https://docs.ultralytics.com/yolov5/. Hope this helps!
