### ISSUE TITLE
Finding out the regression box loss on running val.py with the task --test

### ISSUE THREAD

**Issue by shivekchhabra** [ultralytics/yolov5#11096]
Hey!
In addition to finding the right number of detections, one of the thing I want to also ensure is that the box length is same as the ground truth. I believe that the regression box loss is probably the best metric for that. Please correct me if I am wrong.

We do get the box_loss at every epoch in training but we dont get it when we run the "val.py" with the task of test on labelled data.

Any reasons? Is there a way to add it?

Thanks.

**Comment by glenn-jocher** [comment]
@shivekchhabra hey there!

You're absolutely right that the regression box loss is a crucial metric for ensuring accurate bounding box dimensions. Currently, as of YOLOv5 v5.0, the validation process with 'val.py' doesn't output the box loss directly.

However, you can easily calculate the box loss using the validation results obtained from 'val.py'. The necessary information, such as predicted bounding box dimensions (x, y, width, height) and ground truth dimensions, is available in the results. You can calculate the regression loss using this data in a simple script or notebook.

Our documentation at https://docs.ultralytics.com/yolov5/ provides further insights on how to interpret and evaluate model performance during validation.

Let me know if you need further assistance!
