### ISSUE TITLE
cache speed up your training

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#11095]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I try to use the --cache to speed up .
But it show the  [1.01it / it] for the two command.
what did I miss

```
python -m torch.distributed.run --nproc_per_node 4 train.py --batch 16 --weights yolov5m6.pt --device 0,1,2,3 --img-size 1280
```

```
python -m torch.distributed.run --nproc_per_node 4 train.py --batch 16 --weights yolov5m6.pt --device 0,1,2,3 --img-size 1280 --cache ram
```

**Comment by glenn-jocher** [comment]
@alicera hey there! 👋 The `--cache ram` flag loads your dataset into RAM to speed up data loading. However, the `--cache` option currently doesn't speed up training, it's for data loading only. You can find more info on **data loading** optimization in the [Ultralytics YOLOv5 documentation](https://docs.ultralytics.com/yolov5/). Let me know if you need further assistance!
