### ISSUE TITLE
export to torchscript without Detection fa 

### ISSUE THREAD

**Issue by Joevaen** [ultralytics/yolov5#11091]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Hi, someone!
I tried to export yolov5 model from pytorch to torchscript, so I checked the export.py. 
I found the code near 549 line: `m.export = True`. 
I think this quote control the export of DETECTION module, right? 
So I switch it to `false`.
However, when I checked the new-born model in Netron, I found the Detection still there!
Is this normal? Is the switch broken?
Hope for the answer, thx!

### Environment

- YOLOv5
- torch 1.13
- ubuntu 18.04

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Joevaen hi there! Thanks for reaching out. The `m.export = True` line in export.py actually refers to exporting the model for use in other frameworks, not to controlling the export of the detection module. To exclude the detection layer from torchscript export, you can call `model = model.forward` before `torch.jit.trace`. We appreciate your keen interest in YOLOv5 and hope this helps! Let us know if you have any other questions.
