### ISSUE TITLE
How to convert YOLOv3 .py model to YOLOv5.

### ISSUE THREAD

**Issue by krolaper** [ultralytics/yolov5#11099]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am trying to run yolov3 .py model in yolov5 and am getting the error:
```
File "/path/models/yolo.py", line 65, in forward
    self.grid[i], self.anchor_grid[i] = self._make_grid(nx, ny, i)
RuntimeError: The expanded size of the tensor (1) must match the existing size (80) at non-singleton dimension 3.  Target sizes: [1, 3, 1, 1, 2].  Tensor sizes: [3, 80, 80, 2]
```
Is it possible to convert a .py model so as not to overfit? After all, datasets are large and training is long.

**Comment by krolaper** [comment]
The question can be closed, I found an error in my code. I'm sorry.

**Comment by glenn-jocher** [comment]
@krolaper no problem at all! Glad to hear you found the issue. If you have any other questions or need further assistance, feel free to ask. Good luck with your project!
