### ISSUE TITLE
Show result of inference over all classes

### ISSUE THREAD

**Issue by MasIgor** [ultralytics/yolov5#11098]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,

at the end of a training, this table is displayed:

![image](https://user-images.githubusercontent.com/67956327/222345759-ff9e275d-6d96-4a69-8889-edc6e3411af8.png)

If I interupt the training early, is there a way to get this table printed out? 

Thank you

**Comment by MasIgor** [comment]
found it.. with val.py and teh flag --verbose.

**Comment by glenn-jocher** [comment]
@MasIgor glad you found a solution! Indeed, running `val.py` with the `--verbose` flag will display the results table after inference. Awesome job, and feel free to reach out if you have any more questions!
