### ISSUE TITLE
about  training and testing image size?

### ISSUE THREAD

**Issue by dmuqlzhang** [ultralytics/yolov5#111]
can I change input size 640 to 416 or othor? for example, in yolov4 darknet， I used light backbone like mobilenet-v2， input size 416×416， now I want to compare the performance(inferrence time and GPU memory size) about yolov4 and yolov5, I want to know it's fair to compare about the response(https://blog.roboflow.ai/yolov4-versus-yolov5/)?

**Comment by glenn-jocher** [comment]
@dmuqlzhang you can pass the `--img-size` argument to any of the 3 main files: train.py, detect.py, test.py to train, test and run inference at any size.
