### ISSUE TITLE
How to save images from a video feed only when yolo model detects something?

### ISSUE THREAD

**Issue by sanchaykasturey** [ultralytics/yolov5#11102]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to save all the images I am taking from a video source such as a webcam, and then when the model detects any classes then it should save the frame as an image. I am very confused about this so please help me. I couldn't find any help.

Please help me

Thanks

### Additional

`import torch
from PIL import Image
import cv2 

CKPT_PATH = '/Capstone/yolov5/licensePlateNEw.pt'
yolov5 = torch.hub.load('/Capstone/yolov5',
                        'custom',
                        path=CKPT_PATH,
                        source='local',
                        force_reload=True)

conf='confidence: ' + str(yolov5.conf)
print(conf)
vidcap = cv2.VideoCapture(0)
success,image = vidcap.read()
while success:
    if `     <-------Here I want to add a condition that if the model detects I don't know how to do it.

**Comment by vikrrantshah** [comment]
@sanchaykasturey Did you find a solution to this? I have been working on something similar and would very much like to achieve exactly what your requirements are.

**Comment by glenn-jocher** [comment]
Hi @vikrant0526! If you are looking to save images from a video feed only when the YOLO model detects something, you can achieve this by integrating the YOLOv5 model into your code.

First, make sure you have the YOLOv5 model loaded and ready for inference. You can do this using the `torch.hub.load` function as you have shown in your code snippet.

Next, you can use a loop to read frames from the video feed using `cv2.VideoCapture` and pass each frame to the YOLOv5 model for inference. You can then check if any detections are made by checking if the returned list of detections is not empty.

If the model detects something, you can save the frame as an image using `cv2.imwrite` function. The image file name can be generated based on the current timestamp for uniqueness.

Here's an example of how you can modify your code to achieve this:

```python
import torch
from PIL import Image
import cv2 
import datetime

CKPT_PATH = '/Capstone/yolov5/licensePlateNEw.pt'
yolov5 = torch.hub.load('/Capstone/yolov5',
                        'custom',
                        path=CKPT_PATH,
                        source='local',
                        force_reload=True)

vidcap = cv2.VideoCapture(0)
success, image = vidcap.read()

while success:
    # Convert image to PIL format
    img_pil = Image.fromarray(image)

    # Perform YOLOv5 inference
    results = yolov5(img_pil)

    # Check if any detections are made
    if len(results.pred) > 0:
        # Save the frame as an image
        timestamp = datetime.datetime.now().strftime("%Y%m%d%H%M%S")
        image_name = f"image_{timestamp}.jpg"
        cv2.imwrite(image_name, image)

    # Read the next frame
    success, image = vidcap.read()

# Release the video capture
vidcap.release()
```

Note: You may need to modify the code based on your specific requirements and ensure that the YOLOv5 model is correctly loaded and configured.

I hope this helps! Let me know if you have any further questions.

**Comment by donghyck** [comment]
@glenn-jocher hi, where i should add that code? detect.py? i use gopro camera for the source.

**Comment by glenn-jocher** [comment]
Hi @donghyck! You can incorporate the code I provided in the `detect.py` script. You would need to make adjustments to capture frames from the GoPro camera instead of the webcam. You can use the OpenCV library with the camera's IP address and appropriate credentials if required to access the camera feed.

You can integrate the code snippet within a function or the main loop of the `detect.py` script, which performs inference using the YOLOv5 model. Make sure to handle any necessary imports and adjustments to the script as needed for your specific setup.

I recommend referring to the official OpenCV documentation for capturing video from an IP camera and integrating YOLOv5 model into the `detect.py` script.

Feel free to reach out if you need further assistance with integration or facing any issues. Good luck!
