### ISSUE TITLE
conversion from pytorch to onx

### ISSUE THREAD

**Issue by prarthanasigedar** [ultralytics/yolov5#11106]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am trying to convert py-torch yolo model to onx format so as  to use it on opencv. Is pytorch 1.13 compatible with onx format as I am facing issues after conversion in onx format?

**Comment by knoppmyth** [comment]
I had no issue converting to ONNX. Perhaps you should report the issues/errors you're having.

**Comment by glenn-jocher** [comment]
@knoppmyth thanks for reaching out! It's great to hear that you had no issues converting to ONNX. Can you please provide more details about the issues or errors you encountered during the conversion? This would help us better understand and assist with resolving the problem.

**Comment by knoppmyth** [comment]
@glenn-jocher you and the team made the conversation process easy! Thanks! But, I think you should be asking @prarthanasigedar what issues they encountered.

**Comment by glenn-jocher** [comment]
Thanks for your kind words, @knoppmyth! 😊 I appreciate your suggestion, and I'll make sure to loop in @prarthanasigedar to get further details about the issues they encountered during the conversion process. Your proactive contribution to the discussion is greatly valued!
