### ISSUE TITLE
 im using the yolov5m6.pt checkpoint, and i modified the input resoluation to 1280, id like to ask  number of output branch?

### ISSUE THREAD

**Issue by hatecodes** [ultralytics/yolov5#11103]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hello, im curious about after i changed the resoluation of the input. and in the yolov5m6.yaml , icould see four C3 modules in backbone, so, id  like to ask how many output branch will have? will the downsampling factor  change from 32 to 64?

thx for answering~~~~~

**Comment by glenn-jocher** [comment]
@hatecodes hi there! The YOLOv5m6 model has a stride of 32, so regardless of the input resolution, the downsampling factor remains the same at 32. The YOLOv5 architecture produces 3 detection scales as outputs, each corresponding to different anchor box sizes. Let me know if there's anything else I can help you with! 😊
