### ISSUE TITLE
I have a question for python3.6.9.

### ISSUE THREAD

**Issue by Heartful-echo** [ultralytics/yolov5#11107]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi

My device is python3.6.9.
I think YOLOv5 requires python3.8 or higher. Is there a way to make YOLOv5 work with python3.6?

**Comment by glenn-jocher** [comment]
@Heartful-echo hi there,

Thanks for reaching out. YOLOv5 relies on features and functionalities introduced in Python 3.8, so using it with Python 3.6 may not be feasible. I'd recommend considering an upgrade to Python 3.8 or higher to ensure compatibility and access to the complete feature set.

Feel free to refer to the Ultralytics YOLOv5 documentation for additional details on system requirements and compatibility.

Let me know if there's anything else I can assist you with. 👍
