### ISSUE TITLE
How can I using PyTorch Hub to load the model that only detects one specific class, e.g. person? 

### ISSUE THREAD

**Issue by 7icky** [ultralytics/yolov5#11104]
I have tried to use the following code to load the model that I need but it seems that the model is still for all the classes:
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', classes=0)

Is it possible to load a model with pytorch hub that only detects one specific class, like person or car?

**Comment by glenn-jocher** [comment]
@7icky hey there! 👋

To load a YOLOv5 model that detects only a specific class, such as "person" or "car", you can utilize the `--cfg` and `--weights` flags with the `model` argument. Here's an example:

```python
import torch

model = torch.hub.load('ultralytics/yolov5', 'custom', path='yolov5m.pt', source='local', force_reload=True, classes=1) 
```

Make sure that you've trained a custom YOLOv5 model using the Ultralytics Train Custom YOLOv5 Model guide in the Ultralytics Docs: https://docs.ultralytics.com/yolov5/

Let me know if you need further assistance!
