### ISSUE TITLE
Could you please simplipied the model definition code?

### ISSUE THREAD

**Issue by Edwardmark** [ultralytics/yolov5#1111]
## ❔Question

Could you please simplipied the model definition code?
## Additional context
Now the code in folder models is complicated to understand and to change the structure, could you rewrite it to normal pytorch way such as https://github.com/amdegroot/ssd.pytorch/blob/master/ssd.py, so we can change the model easily, and the code could be more readable.

Thanks.

**Comment by glenn-jocher** [comment]
@Edwardmark please submit PRs for any changes you are interested in.
