### ISSUE TITLE
Error: Yolov5 Openvino model run on Raspberry Pi 4 with NCS2

### ISSUE THREAD

**Issue by lrongchuan** [ultralytics/yolov5#11118]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi all,

I wish to run my best_openvino_model on my Raspberry Pi 4 with NCS2. I exported the openvino model using the official way, and facing error: "requirements: YOLOv5 requirement "openvino" not found" and "No module named "openvino"" as captured in the figure below. 

After installing openvino==2021.4.582, I tried the face-detection-adas-0001.xml, and it ran smoothly without error. 

Anyone has any idea on this error?  Thank you.

![1 ](https://user-images.githubusercontent.com/109837717/222909918-e9044143-d04e-434b-9f04-ebca66d3aa57.jpg)
![2 ](https://user-images.githubusercontent.com/109837717/222909940-fb853532-ae8b-4fd0-bc68-3954b4877732.jpg)

**Comment by glenn-jocher** [comment]
@lrongchuan hi there,

It seems like you're encountering a "No module named 'openvino'" error when trying to run the YOLOv5 OpenVINO model on your Raspberry Pi 4 with NCS2. This may be related to the required "openvino" not being found. Have you checked that the "openvino" module is installed and available in your Python environment?

It's great that you were able to run the "face-detection-adas-0001.xml" smoothly, but the error you're encountering might be specific to the YOLOv5 OpenVINO model. You may want to investigate whether the OpenVINO setup for YOLOv5 differs from the face detection model.

If you haven't already, please refer to the YOLOv5 documentation for specific installation and usage instructions. If you continue to encounter issues, feel free to provide additional details for further assistance.

Hope this helps!
