### ISSUE TITLE
Path resolution in the dataloader

### ISSUE THREAD

**Issue by jerome-white** [ultralytics/yolov5#11110]
How important is this line?

https://github.com/ultralytics/yolov5/blob/5c91daeaecaeca709b8b6d13bd571d068fdbd003/utils/dataloaders.py#L246

Because my images are symlinks, it's making result writing difficult to manage. I've removed the line in my clone of the repository, and things _seem_ to work. I'm hoping to get some assurance that there won't be unintended consequences.

#### Background

During detection, the file names I pass to the CLI are symlinks (that is, the paths inside of `--source test.txt`). This line is resolving those names to their real locations. I work with symlinks because my images live across my filesystem, at varying depths, and with no guarantees of unique basename's. Symlinks allow me expose that structure in a way that the codebase likes, and alleviates the need for making redundant copies of my dataset.

However, because they are symlinks this line is resolving them back to their actual names. This is an issue when I detect `--save-txt`, which writes results to TXT files corresponding image basename's.

**Comment by jerome-white** [comment]
Using the standard question interface (#11115)

**Comment by glenn-jocher** [comment]
@jerome-white thanks for reaching out! The line you mentioned resolves symbolic links, potentially affecting your result writing when using `--save-txt`. Your approach of removing the line is valid given your specific requirements. While it's unlikely to cause unintended consequences, I recommend thorough testing to ensure compatibility with your symlink-based setup. Should you encounter any issues, feel free to reach out for further assistance. Keep up the great work, and thanks for your support!
