### ISSUE TITLE
Is there any drop-down option in Dataloader?

### ISSUE THREAD

**Issue by yellowjs0304** [ultralytics/yolov5#11128]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, i'm using a custom [repo ](https://github.com/XinzeLee/PolygonObjectDetection)that related with your yolov5.

I found some of my labels are dropped in training process. I wondered is there any option to control the number of loaded data? (like max_object_NUM) or Is there an option to drop some label data?

Below images are sample.
As you can see, there's some of row label is dropped.
![image](https://user-images.githubusercontent.com/30281608/223664886-c4b67f26-eee6-4bae-b4f0-3481c8c012a1.png)
![image](https://user-images.githubusercontent.com/30281608/223665022-48101906-7898-43d1-b018-f70c3ae1dcb7.png)

If anyone know about this, please help me.

**Comment by yellowjs0304** [comment]
I found the solution, There's a filtering function in [utils/augmentations.py](https://github.com/ultralytics/yolov5/blob/cec1b9bc923cdd235baa3b9b5c80e3700bc9b1dc/utils/augmentations.py#L233)

It help to delete unnecessary(or something uncorrect) augmented labels. But in my case, I wanted to use whole labeled data.

I modified as below. and, now the dropped labels are restored.

### Before
        i = box_candidates(box1=targets[:, 1:5].T * s, box2=new.T, area_thr=0.01 if use_segments else 0.10)
        targets = targets[i]
        targets[:, 1:5] = new[i]

### Modified
        # i = box_candidates(box1=targets[:, 1:5].T * s, box2=new.T, area_thr=0.01 if use_segments else 0.10)
        i = np.full(i.shape, True)
        targets = targets[i]
        targets[:, 1:5] = new[i]
I don't know it maybe affected with mAP but, i have only a few, so all of data are important.
I didn't apply much of augments, I just looking forward the mAP is not that affected.

**Comment by glenn-jocher** [comment]
@yellowjs0304 nice job finding and modifying the solution! Your modification will indeed use the whole labeled data, restoring the dropped labels. Regarding mAP, as you have only made a few adjustments and the data is important, your mAP may not be significantly affected. 🚀
