### ISSUE TITLE
How to load the customized configuration file for the classification model

### ISSUE THREAD

**Issue by dky233** [ultralytics/yolov5#11126]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to load the customized configuration file for the classification model？

### Additional

I want to use the customized configuration file to build the model, but I don't know how to load it.

**Comment by glenn-jocher** [comment]
@dky233 to load a customized configuration file for the classification model, you can use the '--cfg' argument followed by the path to your custom .yaml file. This will apply your custom configuration when building the model. For more details, you can refer to the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/. If you encounter any issues, feel free to ask for further assistance.
