### ISSUE TITLE
Ensembling Technique

### ISSUE THREAD

**Issue by HunterMorera** [ultralytics/yolov5#11122]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I read a previous discussion about ensembling multiple trained networks by simply passing more than 1 weight file during inference. My question is what technique is being used for fusing the predictions? Is it majority voting on the bounding boxes? Some weighted averaging? I would like to be able to explain how the ensembling is happening in any publications.

Thanks!

**Comment by glenn-jocher** [comment]
@HunterMorera hello! Great question. When ensembling with YOLOv5, predictions are merged using weighted ensemble method. The confidence scores of each detection from different models are multiplied by the model's individual weights, and then combined together. Feel free to check out the [Ultralytics Docs](https://docs.ultralytics.com/yolov5/) for more detailed information. Happy ensembling!
