### ISSUE TITLE
How can I get confidence_score for the boxes in output .txt files?

### ISSUE THREAD

**Issue by redwankarimsony** [ultralytics/yolov5#1112]
## ❔How can I get confidence_score for the boxes in output .txt files?
The general output format of yolov5 the output text files containing the object location in the format `<class_id> <x_center> <y_center> <width> <height>` for each of the objects located. However, if I want to store the **confidence_score** of these bounding boxes to be also written in the format  `<class_id> <confidence_score> <x_center> <y_center> <width> <height>`  then what should I do? For example have a look at the image below. I want to store these score values 0.53, 0.83, 0.58,  0.42 in their corresponding lines in the 83082816-59e54880-a039-11ea-8abe-ab90cc1ec4b0.txt file

Thank you!

![](https://user-images.githubusercontent.com/26833433/83082816-59e54880-a039-11ea-8abe-ab90cc1ec4b0.jpeg)

**Comment by NanoCode012** [comment]
@redwankarimsony , I guess you're in luck. There's an open PR on this. https://github.com/ultralytics/yolov5/pull/994

Just change the below,
https://github.com/ultralytics/yolov5/blob/5fac5ad1657200c11151758ac2f5ad2e60e8aae4/detect.py#L109

to this,
https://github.com/ultralytics/yolov5/blob/bc16152fccf7860f68c1b822cbfdb3e1e74c0e6e/detect.py#L110

**Comment by redwankarimsony** [comment]
OMG, Thank you very much @NanoCode012 !!!
You really saved my  day..

**Comment by redwankarimsony** [comment]
hi @NanoCode012 changing that I have another error
```
  File "detect.py", line 171, in <module>
    detect()
  File "detect.py", line 109, in detect
    f.write(('%g ' * 6 + '\n') % (cls, *xywh))  # label format
TypeError: not enough arguments for format string
```

**Comment by redwankarimsony** [comment]
Thanks a lot @NanoCode012 
You really saved my day !
