### ISSUE TITLE
Understanding Format of Segmentation Mask Output

### ISSUE THREAD

**Issue by jeremiahgivens** [ultralytics/yolov5#11132]
Hello,

I am currently working on a project where I am taking an onnx exported yolov5 instance segmentation model, and using it inside Unity game engine using the Barracuda library. The model seems to be working well, and I have already written the code to perform nms in c#. However, I am currently trying to add segmentation masks, and I am having a hard time understanding the format of the masks. I've been looking at /segement/predict.py, but the code is difficult for me to follow, as I am not much of an expert in all of the concise pythonic commands that are used. Also, I've looked at this issue: [issue 9496](https://github.com/ultralytics/yolov5/issues/9496), but it looks like the format might have changed since that issue.

Currently, for testing, I am using a yolov5s-seg model, trained on the COCO dataset, and I am targeting images of size 1024x1024. Below is an image of the bottom of the model in netron: 
<img width="1098" alt="Screen Shot 2023-03-08 at 1 14 29 PM" src="https://user-images.githubusercontent.com/61922725/223817734-0a65c33a-8ce6-4b77-a5c4-9857294d7a77.png">

For each detection, the format I am getting our of Barracuda is:
{box_x, box_y, box_w, box_h, confidence, class 1, ..., class 80, mask 1, mask2, ..., mask 32}.

Can you please tell me what exactly these numbers for mask 1, ..., mask 32, represent? Any additional information on the general process for mapping this to a bounding polygon is much appreciated.

Thanks

**Comment by superbayes** [comment]
same question with you

**Comment by jeremiahgivens** [comment]
@AyushExel,  Additional question to help clarify: Is the Proto model included in the export to ONNX? It seems I am only getting half of the required output.

**Comment by xiaohai10** [comment]
How can I get the mask or contour of a single object when yolov5.7's predict.py detects multiple objects at the same time

**Comment by glenn-jocher** [comment]
@xiaohai10 hello,

When YOLOv5 predicts multiple objects in the same image, each object's mask is generated independently and saved in the `.png` format with the same name as the corresponding original image but adding `_classes.png` and `_masks.png` at the end.

To isolate the mask of a specific object, you can convert the mask image to a binary image and use contour detection to find the outline of the object. Here's a sample code that can help you get started:

```python
import cv2
import numpy as np

# Load the mask image
mask_img = cv2.imread('/path/to/your/mask.png', cv2.IMREAD_GRAYSCALE)

# Convert to binary image
_, binary = cv2.threshold(mask_img, 50, 255, cv2.THRESH_BINARY)

# Find contours
contours, _ = cv2.findContours(binary, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

# Draw contour on original image
img = cv2.imread('/path/to/your/image.jpg')
cv2.drawContours(img, contours, -1, (0, 255, 0), 2)

# Display image
cv2.imshow('Image', img)
cv2.waitKey(0)
```

This will draw the contour of the object specified by its mask on the original image. You can modify the threshold value to adjust the sensitivity of the contour detection algorithm.

I hope this helps! Let me know if you have any further questions.

**Comment by ziyuuuuuu** [comment]
Hi can i raise hand at here? if you have multiple class which presents at the same image, after prediction, how can we know which mask belongs to which class after binary process since it will be present as rather 0 or 1

**Comment by glenn-jocher** [comment]
@ziyuuuuuu sure! After the binary process, each pixel in the mask image will indeed be represented as either 0 or 1. To associate the masks with their corresponding classes, you can perform the following steps:

1. Retrieve the class labels and their corresponding confidence scores for the predicted objects using YOLOv5.
2. Apply the binary process to obtain the mask image.
3. Compute the mask for each class by multiplying the mask image with the confidence score for that class.
4. Apply a threshold to each masked image to obtain the binary mask for each class.
5. Use contour detection or other techniques to identify and separate the individual objects in each binary mask.
6. Finally, you can associate each object with its corresponding class based on the highest confidence score or any other criteria you choose.

Please let me know if there's anything else I can assist you with!

**Comment by aravindchakravarti** [comment]
@jeremiahgivens hope this below is helpful for you
https://github.com/ultralytics/yolov5/discussions/12834

**Comment by glenn-jocher** [comment]
Hello @aravindchakravarti,

I'm glad you found the discussion helpful! If you have any more questions or need further clarification on anything, feel free to ask. Happy coding! 😊
