### ISSUE TITLE
visualization bug in plot_images_and_masks()

### ISSUE THREAD

**Issue by husheng12345** [ultralytics/yolov5#11133]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Validation

### Bug

Validate the instance segmentation model by simply running: 
`python segment/val.py --task val --weights yolov5s-seg.pt --data coco128-seg.yaml --img 640`

The visualization results will be like:
![val_batch0_pred_before](https://user-images.githubusercontent.com/8972584/223901598-a2c755f3-6898-4549-af06-d9e3eff9db30.jpg)
**It can be found that the image names of the first row are missing.**

This bug is caused the code here:
https://github.com/ultralytics/yolov5/blob/85f6019e5af2641e33139e97415b7bd1dc72d779/utils/segment/plots.py#L57

The correct code should be:
`annotator.text((x + 5, y + 5), text=Path(paths[i]).name[:40], txt_color=(220, 220, 220))  # filenames`

After fixing that, the visualization results will be ok:
![val_batch0_pred_after](https://user-images.githubusercontent.com/8972584/223904755-85211991-386b-4e01-bed5-50ba9686c623.jpg)

### Environment

- YOLO: YOLOv5 🚀 v7.0-117-g85f6019 Python-3.8.16 torch-1.13.1+cu117 CUDA:0 (NVIDIA A100-SXM4-80GB, 81251MiB)
- OS: Ubuntu 20.04.4 LTS
- Python: 3.8.16

### Minimal Reproducible Example

Validate the instance segmentation model by running: 
`python segment/val.py --task val --weights yolov5s-seg.pt --data coco128-seg.yaml --img 640`

Then check the visualization results.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@husheng12345 hi there, thanks for the detailed report! You've accurately identified the bug and provided a clear fix. Your help is much appreciated. I'll ensure the suggested code correction is reviewed and integrated into the next release. For further information on YOLOv5 or its components, please refer to the [Ultralytics Docs](https://docs.ultralytics.com/yolov5/). Cheers!
