### ISSUE TITLE
Some Questions about default Regression Loss Implementations

### ISSUE THREAD

**Issue by cydiachen** [ultralytics/yolov5#1113]
## ❔Question
Thank you for the excellent job of yolov5. I have read your code and inspired a lot. However, I found that it is confusing that the regression loss in your code. In ./utils/general.py, you kindly provided three types of iou loss for us. But i Find that inside compute_loss function, you use bbox_iou() with CIoU= True, but you annotated this line as giou. It is really confusing for us to understand. Would you mind telling me the real configurations or the reason you choose CIoU mode of bbox_iou() for giou? THX a lot.

**Comment by glenn-jocher** [comment]
@cydiachen yes you are correct. See https://github.com/ultralytics/yolov5/issues/762 for a TODO on this.

In terms of box regression metrics CIoU may perform slightly better on custom datasets per user feedback.

**Comment by cydiachen** [comment]
> @cydiachen yes you are correct. See #762 for a TODO on this.
> 
> In terms of box regression metrics CIoU may perform slightly better on custom datasets per user feedback.

Thx, Your reply cleared up my doubt. Thank you for your reply.

**Comment by glenn-jocher** [comment]
@cydiachen I've opened PR #1120 to address this. Please review and comment there.
