### ISSUE TITLE
Val Verbose Option when Training

### ISSUE THREAD

**Issue by awetzel-lionpower** [ultralytics/yolov5#11141]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Currently, in the Val function, a "verbose" flag prints the mAP for all classes. I think the ability to do that during training would be trivial to add and would be helpful for sighting how a training is going.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@awetzel-lionpower thanks for reaching out! You can achieve a similar effect during training by setting the `verbose` flag to `True` in train or test mode, which outputs detailed and per-class results. You can refer to our [Ultralytics Docs](https://docs.ultralytics.com/yolov5/) for more information on using this feature effectively. If you have any more questions or need further assistance, feel free to ask!
