### ISSUE TITLE
Can a module be added to visualize the prediction box for positive and negative samples?

### ISSUE THREAD

**Issue by hongpengxu779** [ultralytics/yolov5#11143]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

The prediction box of positive and negative samples can be seen in the prediction image, which is helpful to understand and improve the problem of imbalance of positive and negative samples. Thank you.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@hongpengxu779 hi there! Thanks for reaching out with your suggestion. Adding a module to visualize the prediction box for positive and negative samples sounds like a valuable addition for understanding sample imbalance. It's great to see your willingness to contribute through a PR! 😊 We will take a look at your proposal and evaluate its feasibility. In the meantime, feel free to refer to our [Ultralytics Docs](https://docs.ultralytics.com/yolov5/) for any further information. Thanks again for your thoughtful input!
