### ISSUE TITLE
train.py文件训练报错

### ISSUE THREAD

**Issue by zhangzhuobin** [ultralytics/yolov5#11149]
"Couldn't load custom C++ ops. This can happen if your PyTorch and "
RuntimeError: Couldn't load custom C++ ops. This can happen if your PyTorch and torchvision versions are incompatible, or if you had errors while compiling torchvision from source. For further information on the compatible versions, check https://github.com/pytorch/vision#installation for the compatibility matrix. Please check your PyTorch version with torch.__version__ and your torchvision version with torchvision.__version__ and verify if they are compatible, and if not please reinstall torchvision so that it matches your PyTorch install.

**Comment by glenn-jocher** [comment]
@zhangzhuobin hi there! This error usually indicates a version incompatibility between PyTorch and torchvision. Please verify that your PyTorch version is compatible with torchvision and reinstall torchvision if necessary to ensure they match. You can verify your PyTorch version with `torch.__version__` and your torchvision version with `torchvision.__version__`.

For further information on compatible versions, you can check the compatibility matrix at https://github.com/pytorch/vision#installation.

If you encounter any further issues, feel free to reach out. We're here to help!
