### ISSUE TITLE
How  can i change  output

### ISSUE THREAD

**Issue by ozicmoi** [ultralytics/yolov5#11140]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I'm trying to detect all images in a directory and overwrite an existing .txt file. After tagging data in my .txt files, the outputs are as follows:

1 0.15325 0.21912037037037038 0.06483333333333334 0.12712962962962965
1 0.7574166666666666 0.49187962962962967 0.14191666666666666 0.343018518518518561 0.15325 0.21912037037037038 0.06483333333333334 0.12712962962962965
1 0.7574166666666666 0.49187962962962967 0.14191666666666666 0.34301851851851856

Since I don't want to tag them all over again, I will detect all the images with the default yolov5s.pt and overwrite the outputs in the .txt files. But the data returned to me is as follows.

0      357     264     678     798
0       3       250     195     608
0       1394    264     1670    840

How do I get this conversion???

YOLOv5  2023-2-27 Python-3.8.10 torch-1.13.1+cpu CPU

My Code:

`all_files = os.listdir("train/images/")
for img in glob.glob("train/images/*.jpg"):

    cv2.imread(img)
    results = model(img)

    for index, row in results.pandas().xyxy[0].iterrows():
        class_name, x1, y1, x2, y2 = row['name'],int(row['xmin']), int(row['ymin']), int(row['xmax']), int(row['ymax'])

        if class_name == "person":
            print("{}\t{}\t{}\t{}\t{}".format(class_name,x1,y1,x2,y2))`

@glenn-jocher

**Comment by TCherici** [comment]
Seems to me that the values in your .txt file are ratios of the img width and height. Dividing the model results by width and height should do the trick. Also, the class_id seems to not match in your example

**Comment by glenn-jocher** [comment]
@TCherici hi there! It looks like the values in your .txt file are ratios of the image width and height. You can divide the model results by the width and height to adjust them accordingly. Additionally, the class_id doesn't seem to match in your example. Make sure to account for that as well. Let me know if you need further assistance with this!
