### ISSUE TITLE
How to add SE module or CBAM module in Yolov5

### ISSUE THREAD

**Issue by sakurasakura1996** [ultralytics/yolov5#1114]
## ❔Question
Thank you for your works.It's very nice on my custom dataset.I want to add attention module in yolov5,can you give me some advice and instruction.Thank you very much.

**Comment by glenn-jocher** [comment]
@sakurasakura1996 attention is not my specialty, but there are a few existing examples you may be able to adopt from, such as pytorch efficientdet modules with SE from https://github.com/rwightman/efficientdet-pytorch. 

Part of our challenge is ensuring viable pathways for export to all destinations (CoreML, TFLite, ONNX), which constrains some of our design choices and research pathways, which is another reason for not investigating SE further.

If you may any progress on this please feel free to submit a PR! Good luck.
