### ISSUE TITLE
Any plan for adding oversampling function for imbalanced dataset?

### ISSUE THREAD

**Issue by luvwinnie** [ultralytics/yolov5#1115]
## ❔Question
I think it is often have a imbalanced dataset in real scenario, does this repo tested on the technique of resampling such as oversampling, undersampling or SMOTE etc?

**Comment by glenn-jocher** [comment]
@luvwinnie I'm not familiar with SMOTE. We tested a few adaptions to class imbalances that helped in early training, but these overfit faster as well and resulted in lower final maps, so our current implementation has no specific class imbalance adaptations in place when using default settings.

In any case, COCO and VOC suffer from severe class imbalances, and these train very well with the default settings.

**Comment by glenn-jocher** [comment]
@luvwinnie ah, BTW, one technique to address custom datasets, including class imabalances, is simply to evolve hyperparameters, which include loss balancers and BCE positive weights for class and conf. See https://docs.ultralytics.com/yolov5

**Comment by luvwinnie** [comment]
@glenn-jocher Thank you for reply! I would like to test the evolve hyperparameters and SMOTE later. Just one thing is that seems like the evolve hyperparameters take very long , is the evolve hyperparameters training can be resume later with any options?

**Comment by glenn-jocher** [comment]
@luvwinnie yes, evolution is an expensive habit, as you basically want to train 300 times or so. It can be stopped and resumed from the same evolve.txt, and you can also deploy multiple gpus (to evolve in parallel to a single evolve.txt) and multiple nodes/VMs (to evolve from a central cloud based evolve.txt).

**Comment by luvwinnie** [comment]
@glenn-jocher Thank you! i try with python -m torch.distributed.launch --nproc_per_node 2 train.py seems like it show the following errors. ```AssertionError: DDP mode not implemented for --evolve``` the multiple GPU cannot be use for --evolve?

**Comment by glenn-jocher** [comment]
@luvwinnie evolving multi-GPU is done with one GPU per process. I've updated the hyperparameter evolution tutorial https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution with an example.

```bash
# Single-GPU
python train.py --epochs 10 --data coco128.yaml --weights yolov5s.pt --cache --evolve

# Multi-GPU
for i in 0 1 2 3; do
  python train.py --epochs 10 --data coco128.yaml --weights yolov5s.pt --cache --evolve --device $i
done
```

EDIT: this shows a bash for loop, but in practice you'd want to run these in detached screens or simply in new terminal windows, one screen/window per cuda device, with --device 0, --device 1, etc.

**Comment by luvwinnie** [comment]
@glenn-jocher thank you for reply! I think suppose better with the following with nohup and background task?

```bash
#!/bin/bash
### EDITIED ###
for i in 0 1 2 3; do
  nohup python train.py --epochs 10 --data coco128.yaml --weights yolov5s.pt --cache --evolve --device $i > evolve_gpu_$i.log &
done
```

**Comment by glenn-jocher** [comment]
@luvwinnie ah, yes that's the effect I was going for. When running docker images in detached -d mode you can use a simple for loop as I had initially, but for running directly you need to detach the command somehow. In the past I used screens for this: https://superuser.com/questions/454907/how-to-execute-a-command-in-screen-and-detach

Does this nohup command do the same? Is the `&` character at the end required to complete the nohup command?

**Comment by luvwinnie** [comment]
@glenn-jocher yes. For my environment, I didn't use docker to detach the session. To run as background process we need the ```&``` character, ```nohup``` command is use to make sure the process keeps running even the terminal session closed.

EDIT: I have updated the code to log out the print in order to use the tail -f command to check the progress

**Comment by glenn-jocher** [comment]
@luvwinnie very cool! I've updated the tutorial with your nohup command. 

How would you check in on a thread to see it's logging (to make sure it hasn't crashed etc.)?

**Comment by luvwinnie** [comment]
@glenn-jocher Thank you! Normally I will just redirect the stdout to some log file, as I edited the command I redirected all the stdout in a separate log file, which names as evolve_gpu_$i.log. Let say I have 2 GPU, I will just use the following command to check the progress. Although it is not clean @@;

```bash
terminal 1:$ tail -f evolve_gpu_0.log
terminal 2:$ tail -f evolve_gpu_1.log
```

**Comment by Samjith888** [comment]
> @luvwinnie yes, evolution is an expensive habit, as you basically want to train 300 times or so. It can be stopped and resumed from the same evolve.txt, and you can also deploy multiple gpus (to evolve in parallel to a single evolve.txt) and multiple nodes/VMs (to evolve from a central cloud based evolve.txt).

 Hyperparameter evolution stopped at 30th step , how to  resume this from the 30th step ?

**Comment by glenn-jocher** [comment]
@Samjith888 you just rerun your same --evolve command (don't use --resume, that's only for normal training). 

If an evolve.txt file already exists in your yolov5 directory, it resumes from there.

**Comment by luvwinnie** [comment]
@glenn-jocher I have ran the evolve and currently 287 generation, it shows the below results. Does this means it doesn't help much with evolve? From my understanding I think `data/hyp.finetune.yaml` is one of the yolov5m evolved results. which means the metrics shows as same as `data/hyp.finetune.yaml` am I wrong?Or the `data/hyp.finetune.yaml` is the final result of trained with evolve config?


Hyperparameter Evolution Results
Generations: 287
Metrics:      0.421     0.681     0.604     0.366    0.0192    0.0101   0.00248

**Comment by glenn-jocher** [comment]
@luvwinnie ok great. These are your evolved metrics. You can paste the labels from finetune.yaml, i.e.
```python
#                   P         R     mAP.5 mAP.5:.95       box       obj       cls
```

You should compare these to your baseline results you had before you started evolving.

**Comment by luvwinnie** [comment]
@glenn-jocher Thank you for reply. I have a baseline trained without evolve from pretrained yolov5s.pt, Do you mean I should compare the baseline with the result that train with this command? 
```
python -u train.py --img=640 --batch=16 --epochs=300  --data=dataset/custom.yaml --cfg=models/yolov5s.yaml --weights=weights/yolov5s.pt --hyp hyp_evolved.yaml
```

**Comment by glenn-jocher** [comment]
@luvwinnie sure. All you do is point the same baseline command to your new hyp_evolved.yaml to get your updated results. You compare 3 to 1 obviously.

1. train.py ...
2. train.py ... --evolve
3. train.py ... --hyp hyp_evolved.yaml
