### ISSUE TITLE
How to convert the TXT saved by split reasoning to the Json format of labelme ？

### ISSUE THREAD

**Issue by KroitAax** [ultralytics/yolov5#11158]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to convert the TXT saved by split reasoning to the Json format of labelme ？

**Comment by glenn-jocher** [comment]
@KroitAax you can use the `labelme` package to convert YOLOv5 TXT output to the JSON format. See the 'API' section of our documentation for its usage. Let us know if you need further assistance!
