### ISSUE TITLE
Error exporting engine file

### ISSUE THREAD

**Issue by lsj147896325** [ultralytics/yolov5#11152]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

![image](https://user-images.githubusercontent.com/95969668/224470161-76d137e5-d65d-4872-895a-95db9fa7feb2.png)
I have downloaded tensorrt and configured the environment variables according to the Nvidia website, but I still have this problem(Versions are matched).   Thank you for your help

**Comment by glenn-jocher** [comment]
@lsj147896325 hi there! Thanks for reaching out. For TensorRT related issues, the best place to start is by referring to the official documentation and making sure all the software versions are compatible. If the problem persists, feel free to ask for further assistance in the YOLOv5 discussions or refer to our documentation at https://docs.ultralytics.com/yolov5/ for additional troubleshooting steps. Your feedback and questions help strengthen the YOLOv5 community, and we're all here to support each other.
