### ISSUE TITLE
Inconsistent Predictions After Onnx & TRT Conversion

### ISSUE THREAD

**Issue by imjohsep** [ultralytics/yolov5#11150]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Export

### Bug

The error that is occurring is a difference in predictions and confidences after converting to onnx. At first I believed this to be an error caused by my own custom trained mode or usage of the export file, but a difference in predictions can be generated simply by exporting the default torch model to onnx and running detect.py. 

This is best visualized with the following prediction results; the first being the result of the default torch model and the second being onnx. 

## Pytorch
![download](https://user-images.githubusercontent.com/4111198/224397858-1de79450-88de-4a3b-a772-7e6e021fa605.jpeg)

## Onnx
![download (1)](https://user-images.githubusercontent.com/4111198/224397869-9d083785-2e3c-4810-9b86-94c87fa4cb4b.jpeg)

In my own custom trained model I seeing a 10% difference in confidence and mAP of 81.83% @ 0.95. Should we expect such difference between the torch and onnx models? 

### Environment

Environment: using ultralytics/yolov5 docker image

## Using docker
```
docker pull ultralytics/yolov5
docker run --gpus all -it --rm --ipc=host ultralytics/yolov5:latest bash
python export.py --device 0 --workspace 10 --include engine
python detect.py --weights yolov5s.onnx
--or--
python detect.py --weights yolov5s.engine
```

## Manual conversion to onnx
```
from yolov5.models.experimental import attempt_load
import torch
import torch.onnx
from utils.torch_utils import select_device
from utils.general import check_img_size

if __name__ == "__main__":
    # device = "cuda"
    device = select_device("0")
    
    model = attempt_load("model.pt",  device=device, inplace=True, fuse=True)
    model.eval()

    BATCH_SIZE = 1
    
    gs = int(max(model.stride))  # grid size (max stride)

    # Here I'm setting my own image size
    imgsz = [check_img_size(x, gs) for x in [1640, 1232]]
    
    dummy_input = torch.zeros(BATCH_SIZE, 3, *imgsz).to(device)
    
    o = model(dummy_input)
    
    torch.onnx.export(model, dummy_input, "model.onnx", verbose=False)
```

### Additional

Onnx and TRT models seem to produce consistent results, so I've determined the issue resides in the conversion from pt to onnx. 

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by TimotheeWrightFicha** [comment]
@imjohsep could you give information on why you closed this. What was in fact your problem and how you solved it ?
