### ISSUE TITLE
Duplicate Hyperparameters

### ISSUE THREAD

**Issue by myasser63** [ultralytics/yolov5#11153]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

This code ensure no duplicate hyperparameters if I understand correctly then why in my evolve.csv, I have many hyperparameters having the same values in different generations.

```
  while all(v == 1):  # mutate until a change occurs (prevent duplicates)
                    v = (g * (npr.random(ng) < mp) * npr.randn(ng) * npr.random() * s + 1).clip(0.3, 3.0)
```

**Comment by glenn-jocher** [comment]
@myasser63 thanks for reaching out! The code snippet is an evolutionary hyperparameter optimizer that ensures uniqueness with `(g * (npr.random(ng) < mp) * npr.randn(ng) * npr.random() * s + 1).clip(0.3, 3.0)`. Repeated values in `evolve.csv` are expected as the optimizer may rediscover the same optimal hyperparameters across different generations. This repetition reflects convergence towards optimal solutions. For further details on YOLOv5, do refer our [Ultralytics Docs](https://docs.ultralytics.com/yolov5/). Let me know if you have any more questions!
