### ISSUE TITLE
Conver Model    to   TF_Lite

### ISSUE THREAD

**Issue by Mansurjons** [ultralytics/yolov5#11156]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I converted pt model to tflite and save 
But Classification not working 
after convert to tflite Label of classes was changed

before label was been AKCHAEV INC

and After Converting to tflite Label is:  

I must to get true LABEL
Please help if any ways 

<img width="984" alt="Screenshot 2023-03-12 at 14 58 57" src="https://user-images.githubusercontent.com/102349512/224537590-b37482ee-5ed1-4503-81e0-48a2b30eab48.png">

**Comment by s4ki3f** [comment]
@Mansurjons, Sir did u solve this problem?
I am facing the same issue too. In .pt it was predicting an orange as orange but in .tflite model, it is charged to something that does not belong to the class file or in .yaml file
