### ISSUE TITLE
동영상에서 바운딩 박스가 표시되는 시간 표시

### ISSUE THREAD

**Issue by dlrjsgh367** [ultralytics/yolov5#11167]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

동영상에서 바운딩 박스가 표시되는 시간을 표시하는 방법이 있습니까?

detect.py --source 'youtube link'

**Comment by glenn-jocher** [comment]
@dlrjsgh367 안녕하세요! 동영상에서 바운딩 박스를 표시하는 데 시간을 표시하는 방법은 우리 문서의 "인식 결과 시간 추가" 섹션을 확인하시면 됩니다. 거기에 언급된 커맨드 라인 인수를 사용하면 됩니다. 추가적인 도움이 필요하시면 언제든지 물어주세요! 🕵️‍♂️
