### ISSUE TITLE
detect.py --source 'youtube_link' 을 실행했을 때 프레임이 몇시, 몇분에 등장하는지 알 수 있나요?

### ISSUE THREAD

**Issue by dlrjsgh367** [ultralytics/yolov5#11163]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question
detect.py --source 'youtube_link' 을 실행했을 때 프레임이 몇시, 몇분에 등장하는지 알 수 있나요?

example
0: 384x640 3 persons, 9.0ms
0: 384x640 3 persons, 8.9ms
0: 384x640 3 persons, 8.9ms
↓
0: 384x640 3 persons, 9.0ms mp4 timestamp
0: 384x640 3 persons, 8.9ms mp4 timestamp
0: 384x640 3 persons, 8.9ms mp4 timestamp

**Comment by glenn-jocher** [comment]
@dlrjsgh367 안녕하세요! detect.py는 프레임의 시간 또는 분을 직접 제공하지 않지만, 아래 예제처럼 코딩하여 프레임이 몇시, 몇분에 등장하는지 알 수 있습니다:

```python
import cv2
cap = cv2.VideoCapture('youtube_link')
fps = cap.get(cv2.CAP_PROP_FPS)

while True:
   ret, frame = cap.read()
   if not ret:
      break
   # 여기서 감지 코드 실행
   print(cap.get(cv2.CAP_PROP_POS_MSEC) // 1000)
   cv2.imshow('frame', frame)
   if cv2.waitKey(1) & 0xFF == ord('q'):
      break
cap.release()
cv2.destroyAllWindows()
```

이 코드는 OpenCV를 사용하여 감지 코드를 실행하고, 감지된 프레임의 시간을 초 단위로 출력합니다. 감지에 적합한 코드를 여기에 통합하면 될 것 같습니다. 이것이 도움이 되기를 바랍니다!
