### ISSUE TITLE
How to use the weights trained with torch 1.5 in the new version?

### ISSUE THREAD

**Issue by hdnh2006** [ultralytics/yolov5#1116]
## ❔Question
Hi, I have trained my model with a past version of YOLOV5 who used torch 1.5. The output was a plain text ".pt" file model which was great. Now, it seems the output is also a "pt" file but it is a folder, so how can I use my old weights in this new version, is there a way to "transform" my weights to the new torch and torchvision version (1.6, 0.7)?

## Additional context
I don't want to retrain my model, any suggestion?

Thanks in advance.

**Comment by glenn-jocher** [comment]
@hdnh2006 reclone and retrain, or checkout the older version you used before.

**Comment by hdnh2006** [comment]
Hi again @glenn-jocher and thanks for the quick answer, It seems the model doesn't converge to the same point, the model fitted with torch 1.5 is better, despite it has been trained with the same data, I insist, is there a way to convert the weights from the previous version?

**Comment by glenn-jocher** [comment]
@hdnh2006 no sorry. We are extremely resource constrained, so it is not possible for us to support legacy torch versions. In any case, the most performant models you can train (as judged by COCO and VOC metrics) will always be with the most recent YOLOv5 code and the latest torch stable release.
