### ISSUE TITLE
Video Data Benchmark

### ISSUE THREAD

**Issue by b3r-prog** [ultralytics/yolov5#11162]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,

Has anyone evaluated any standard public video dataset with yolo (asides visdrone) and compared the benchmarks to others? I can't find any readily integratabtle video data with benchmarks for yolov5. I am trying to see how the models do with blurry and other video types issues.

@glenn-jocher

**Comment by glenn-jocher** [comment]
@b3r-prog YOLOv8 models are validated on COCO and ImageNet. We don't have video dataset results.
