### ISSUE TITLE
images and labels...0 found, 1905 missing, 0 empty, 0 corrupt: 100%，....... Can not train without labels.

### ISSUE THREAD

**Issue by cena001plus** [ultralytics/yolov5#11165]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I use the data storage format of list, which has been processed as required, but there is an error during training, what does corrupt100% mean, and it indicates that data without labels cannot be trained? Before, I had no mistakes under Linux, and now I have errors in the same data processing method, whether it is my own data or VOC dataset

windows, cpu-training,

![image](https://user-images.githubusercontent.com/37894345/224907935-de94d9b2-dca5-46be-8090-9b3ccc8032ec.png)

![image](https://user-images.githubusercontent.com/37894345/224908002-620bfa26-e0a5-4e21-8ed5-8acc3034081c.png)

list data:
![image](https://user-images.githubusercontent.com/37894345/224908562-e49d4695-92dc-42f0-8d5f-be312530c361.png)

original data:
![image](https://user-images.githubusercontent.com/37894345/224927170-1cf779be-3299-4ea3-aa0f-1c937a396c82.png)

list cotent:

![image](https://user-images.githubusercontent.com/37894345/224908670-b8e5f944-b069-4f3f-aea3-51452b81bc21.png)

**Comment by JustasBart** [comment]
Hi @cena001plus I'm not sure how much I can help you out here, but, as far as I'm aware you're meant to use a **.yaml** file of your dataset like so:

**custom.yaml**
```
path: /home/.../custom_dataset/
train: train/images/
val: val/images/
test:

# Classes
names:
  0: red_led
  1: green_led
  2: blue_led
  3: etc...
```
Such so that when you train you would call something like:
```
python3 train.py \
--data /home/.../custom.yaml \
--weights yolov5s.pt \
--img 1280 \
--epochs 600 \
--batch -1 \
--device 0
```
I'm not saying that what you're doing is necessarily wrong, I just haven't seen it done that way, but hopefully you can figure this out before long!

All the best! :rocket:

**Comment by cena001plus** [comment]
solved！
two problems: the first is the error of VOC to YOLO format, which produces a lot of empty TXT files, and the second is that an empty TXT file with too much proportion will go wrong, that is, under normal circumstances, your negative sample data cannot be too much.

![image](https://user-images.githubusercontent.com/37894345/224997042-8b29b53f-23dd-49cf-9d0a-01101c5d0085.png)

**Comment by JustasBart** [comment]
@cena001plus Well done!

All the best! :rocket:
