### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 296: character maps to <undefined>

### ISSUE THREAD

**Issue by dnshshkr** [ultralytics/yolov5#11177]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

I'm trying to log my training progress with comet_ml and have followed every instruction provided including setting the comet api_key and project_name. This somehow worked on google colab but when I tried training locally on my PC it returned this error.
![image](https://user-images.githubusercontent.com/74976069/225405944-e2d1aeb1-694a-4e67-bd7f-117a47beea59.png)

### Environment

- YOLO : latest
-  OS: Windows
- Python: 3.9.16

### Minimal Reproducible Example

python train.py --data coco128.yaml --weights yolov5s.pt --epochs 10 --save-period 1 --bbox_interval 1 --upload_dataset "train"

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by tjboise** [comment]
I solved it by uninstall the comet_ml.

**Comment by glenn-jocher** [comment]
@tjboise great to hear that you were able to resolve the issue! Uninstalling `comet_ml` seems to have done the trick for you. If you have any other questions or need further assistance, feel free to ask. The YOLOv5 community and the Ultralytics team are always here to help.

**Comment by dnshshkr** [comment]
@tjboise @glenn-jocher I installed comet_ml because I wanted to use it in the first place. What's the point of installing comet_ml if it returns error and the solution is by uninstalling it back then?

**Comment by glenn-jocher** [comment]
@dnshshkr i understand your frustration, and I apologize for the inconvenience caused. The issue you encountered is likely specific to the interaction between `comet_ml` and YOLOv5. While `comet_ml` is a popular tool for experiment tracking and logging, sometimes compatibility issues can arise with different frameworks and libraries.

In this case, it seems that uninstalling `comet_ml` resolved the error you were experiencing. It's possible that there may be some conflicts or incompatibilities between `comet_ml` and YOLOv5 in your specific setup.

If you still want to use `comet_ml` for experiment tracking, I would recommend checking the documentation and GitHub repository of `comet_ml` for any known compatibility issues with YOLOv5. Additionally, you can try reaching out to the maintainers of `comet_ml` for further assistance.

Please keep in mind that YOLOv5 is an open-source project, and compatibility with third-party libraries and tools may vary. The YOLO community and the Ultralytics team are constantly working to improve compatibility and provide the best experience possible. Thank you for your understanding, and we appreciate your interest in using YOLOv5.
