### ISSUE TITLE
how to properly train a model using yolov5 

### ISSUE THREAD

**Issue by RaheemTariq480** [ultralytics/yolov5#11175]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am training using yolov5, the objects i have are:
['wheelchair','walker','television','table','sofa','sink','mug','clock','fan','door','chair','cane_stick','cabinet','waterbottle','glasses','basket_bin','bed','glass','spoon','bowl']
i the training command i use is:
!python train.py --img 640 --batch 16 --epochs 3 --data data.yaml --weights '' --cfg yolov5s.yaml --nosave
i want to train the model on the objects mentioned above, i want to use the model in an android application that when i take a photo from the camera, the object is detected in the photograph
I am relatively new to model training, since i am trying to do a custom training therefore i kept the weights ''
are there any tips for the starter, on how to properly train the model

**Comment by glenn-jocher** [comment]
@RaheemTariq480 hi there! 🌟 To properly train a YOLOv5 model for your custom objects, you're on the right track using the `train.py` script and specifying your custom objects in the `data.yaml` file.

A few tips for starters:
1. Ensure your dataset is well-labeled with bounding boxes around your custom objects.
2. Experiment with different architectures (`yolov5s`, `yolov5m`, `yolov5l`, `yolov5x`) to find the best trade-off between speed and accuracy.

When using `-weights ''`, the model will start from scratch, which is fine for a custom dataset. Once trained, you can deploy the model on Android using the YOLOv5 inference code. Check the Ultralytics Docs for details.

Happy training! 🚀
