### ISSUE TITLE
Best graphic card for training yolov5 models with 4K images

### ISSUE THREAD

**Issue by Pedro-Leitek** [ultralytics/yolov5#11176]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I found out that it is possible to train and make inference with 4K images, thanks to a previous post I made. But now I'm facing a new challenge. My graphic card (RTX 3600 12 GB VRAM) is not enough for training at 4K resolution. I get a cuda out of memory error. Taking this into account, what is the recommended graphic card for the training? And for inference?

Thanks

**Comment by Burhan-Q** [comment]
Instead of using full 4k images, could try cropping to smaller sizes to reduce your vRAM needs. You could also try to reduce your batch sizes to lower vRAM requirements too.
