### ISSUE TITLE
Class filtering does not work in segmentation code

### ISSUE THREAD

**Issue by Hyrtsi** [ultralytics/yolov5#11170]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

I tried to filter classes that I train with as explained [here](https://github.com/ultralytics/yolov5/issues/1978). I found out that it works with `train.py` but not with `segment/train.py`.

I expect that if I change the following line:

```python
include_class = [1]  # filter labels to include only these classes (optional)
```

in `utils/dataloaders.py` line `533`, then in `train.py` and `segment/train.py`
- the code does not crash
- the code trains with only class `1` (if such class exists in the `.yaml` file)

What I get:
- `train.py` -> works as expected
- `segment/train.py` -> crashes:

```
Traceback (most recent call last):
  File "segment/train.py", line 664, in <module>
    main(opt)
  File "segment/train.py", line 555, in main
    train(opt.hyp, opt, device, callbacks)
  File "segment/train.py", line 180, in train
    train_loader, dataset = create_dataloader(
  File "yolov5/utils/segment/dataloaders.py", line 46, in create_dataloader
    dataset = LoadImagesAndLabelsAndMasks(
  File "yolov5/utils/segment/dataloaders.py", line 102, in __init__
    super().__init__(path, img_size, batch_size, augment, hyp, rect, image_weights, cache_images, single_cls,
  File "yolov5/utils/dataloaders.py", line 540, in __init__
    self.segments[i] = segment[j]
TypeError: only integer scalar arrays can be converted to a scalar index
```

### Environment

- YOLO: yolov5 `3e55763d45f9c5f8217e4dad5ba1e6c1f42e3bf8`
- OS: Ubuntu 20.04
- Python 3.8

### Minimal Reproducible Example

- clone yolov5 repo
- install dependencies with pip
- edit the lines as explained in the `Bug` section

```
python3 segment/train.py
```

### Additional

There will be a PR showing the fix for this

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Hyrtsi** [comment]
PR: https://github.com/ultralytics/yolov5/pull/11171

**Comment by glenn-jocher** [comment]
@Hyrtsi thank you for the detailed report and the initiative to submit a PR! We appreciate your effort in helping to improve YOLOv5. I will review the PR carefully and provide any necessary feedback. Your contribution to the YOLO community and the Ultralytics team is much appreciated! If you have any further questions or need assistance, please feel free to reach out.
