### ISSUE TITLE
在yolov5中添加了自定义的模块，训练结果始终为0

### ISSUE THREAD

**Issue by tapiohuang** [ultralytics/yolov5#11184]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

我在yolov5l.yaml中添加了自定义的模块<SplitModule><MergeModule>
```
# YOLOv5 🚀 by Ultralytics, GPL-3.0 license

# Parameters
nc: 80  # number of classes
depth_multiple: 1.0  # model depth multiple
width_multiple: 1.0  # layer channel multiple
anchors:
  - [ 10,13, 16,30, 33,23 ]  # P3/8
  - [ 30,61, 62,45, 59,119 ]  # P4/16
  - [ 116,90, 156,198, 373,326 ]  # P5/32

# YOLOv5 v6.0 backbone
backbone:
  # [from, number, module, args]
  [ [ -1, 1, Conv, [ 64, 6, 2, 2 ] ],  # 0-P1/2
    [ -1, 1, SplitModule,[ 'test' ] ],
    [ -1, 1, Conv, [ 128, 3, 2 ] ],  # 2-P2/4
    [ -1, 3, C3, [ 128 ] ],
    [ -1, 1, Conv, [ 256, 3, 2 ] ],  # 4-P3/8
    [ -1, 6, C3, [ 256 ] ],
    [ -1, 1, Conv, [ 512, 3, 2 ] ],  # 6-P4/16
    [ -1, 9, C3, [ 512 ] ],
    [ -1, 1, Conv, [ 1024, 3, 2 ] ],  # 8-P5/32
    [ -1, 3, C3, [ 1024 ] ],
    [ -1, 1, MergeModule,[ 'test' ] ],
    [ -1, 1, SPPF, [ 1024, 5 ] ],  # 11
  ]

# YOLOv5 v6.0 head
head:
  [ [ -1, 1, Conv, [ 512, 1, 1 ] ],
    [ -1, 1, nn.Upsample, [ None, 2, 'nearest' ] ],
    [ [ -1, 7 ], 1, Concat, [ 1 ] ],  # cat backbone P4
    [ -1, 3, C3, [ 512, False ] ],  # 15

    [ -1, 1, Conv, [ 256, 1, 1 ] ],
    [ -1, 1, nn.Upsample, [ None, 2, 'nearest' ] ],
    [ [ -1, 5 ], 1, Concat, [ 1 ] ],  # cat backbone P3
    [ -1, 3, C3, [ 256, False ] ],  # 19 (P3/8-small)

    [ -1, 1, Conv, [ 256, 3, 2 ] ],
    [ [ -1, 16 ], 1, Concat, [ 1 ] ],  # cat head P4
    [ -1, 3, C3, [ 512, False ] ],  # 22 (P4/16-medium)

    [ -1, 1, Conv, [ 512, 3, 2 ] ],
    [ [ -1, 12 ], 1, Concat, [ 1 ] ],  # cat head P5
    [ -1, 3, C3, [ 1024, False ] ],  # 25 (P5/32-large)

    [ [ 19, 22, 25 ], 1, Detect, [ nc, anchors ] ],  # Detect(P3, P4, P5)
]
```
为了验证可行性，这两个模块中都没有做操作，在forward函数中直接返回输入的Tensor
```
class SplitModule(nn.Module):
    # Split a module into a list of modules
    def __init__(self, arg1):
        super(SplitModule, self).__init__()
        print("SplitModule: ", arg1)

    def forward(self, x):
        # print("call SplitModule forward")
        return x


class MergeModule(nn.Module):
    def __init__(self, arg1):
        super(MergeModule, self).__init__()
        print("MergeModule: ", arg1)

    def forward(self, x):
        # print("call MergeModule forward")
        return x
```
相应的我在yolo.py的parser_model中也做了修改，将这两个模块的通道数和他们的上一层保持了一致
```
elif m is SplitModule:
            c2 = ch[-1]
        elif m is MergeModule:
            c2 = ch[-1]
        else:
            c2 = ch[f]
```
但是，当我使用修改过的框架训练coco128数据集时我发现，同样使用yolov5l.pt的预训练权重，修改后的训练结果惨不忍睹。
all        128        929    0.00368     0.0421     0.0142    0.00567
请问在yolo中正确的添加模块的方法是什么？为什么我添加了这个“透明”的模块，对结果的影响这么大？

**Comment by Zephyr69** [comment]
Did you train from scratch? You said you used the pretrained model, but the keys won't match if you modified the config?

**Comment by frabob2017** [comment]
我也在学习YOLO源代码， 希望能扩展成3D的功能。 根据我一知半解的对YOLO的理解， 你中间插入2个MODULE以后，把直接权重读进来，权重对于各层的匹配就全错了。这是我对 这句话的理解 “but the keys won't match if you modified the config” 。 估计你需要做个LAYER 的循环， 一层一层的把权重弄对。

**Comment by frabob2017** [comment]
I am also studying the source code of YOLO, hoping to expand its functionality into 3D. Based on my limited understanding of YOLO, if you insert two modules and directly load the weights, the matching of weights for each layer will be completely wrong. This is what I understand from the sentence "but the keys won't match if you modified the config". I think you may need to do a loop of the layers to match the weights layer by layer

**Comment by frabob2017** [comment]
I am not sure if each layer has its own name or ID, I think they still can assign their weights correctly.

**Comment by Zephyr69** [comment]
I double checked. I think currently you need matching keys for weight transfer. If you modified and passed a yaml that implies different number of blocks compared to .pt, the block index, which is part of the key, won't match at all after the first inserted block.

I think to achieve what you want, you need to replace the default transfering mechanism with something that will correctly assign the weights.

**Comment by frabob2017** [comment]
I also want to know what is meaning "from"  [from, number, module, args],  most of them are -1, some are [ -1, 16 ], what does  it mean?

**Comment by Zephyr69** [comment]
> I also want to know what is meaning "from" [from, number, module, args], most of them are -1, some are [ -1, 16 ], what does it mean?

It indicates where the input(s) of that block is coming from. '-1' is the previous block. [] takes multiple block outputs as an input.

**Comment by frabob2017** [comment]
what is [-1 5]  [-1 16] meaning? 5 means layer 5, 16 means layer 16, [-1 5] make me confused.

**Comment by tapiohuang** [comment]
> Did you train from scratch? You said you used the pretrained model, but the keys won't match if you modified the config?

I found out the question,so I have tried to train new one without the pretrained model,and then I got correct result.

**Comment by glenn-jocher** [comment]
@tapiohuang great to hear that training from scratch brought the correct result! Training with a modified configuration can lead to incorrect weight matching, so training a new model without using the pretrained weights is the right approach. If you have any further questions or need assistance, feel free to ask. Keep up the good work!
