### ISSUE TITLE
how to get Hyper parameter values after training.

### ISSUE THREAD

**Issue by Praveen207001** [ultralytics/yolov5#11187]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question
@glenn-jocher ....Sir please anser this....
The YOLOv5 model is trained with default hyperparameter on custom dataset to get xxx mAP etc. How to get the values of hyperparameters that are chaged during the runtime,and where to find the changes in hyperparameter that happened during training. Pls suggest

**Comment by Haniaaliii** [comment]
if i'm not mistaken, if you use --evolve the new hyper parameters will be displayed at the end of training :  
 Plot results 
 plot_evolution(yaml_file) 
check this too : https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution

**Comment by glenn-jocher** [comment]
@Haniaaliii, you are correct! When using the `--evolve` option, the new hyperparameters will be displayed at the end of training. You can also manually plot the results by calling `plot_evolution(yaml_file)`.

Additionally, please note that any hyperparameters that were changed during training can be found in the configuration (`.yaml`) file that was used to train the model.

For more information on using `--evolve` and hyperparameter evolution in YOLOv5, you can check out this [GitHub issue](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution).

Let me know if you have any further questions!

**Comment by Haniaaliii** [comment]
@glenn-jocher Yesterday I tried using the --evolve parameter on my 2000 images dataset, and chose 10 epochs. However it's been running for 23h now, is this normal ? I'm using g3.8xlarge (gpu instance)
Thank you

**Comment by glenn-jocher** [comment]
@Haniaaliii  Thanks for reaching out! The training duration can vary depending on numerous factors such as the size and complexity of the dataset, the hardware used, and the specific hyperparameters chosen.

Using a g3.8xlarge GPU instance for training should typically lead to faster training times. However, training over a large number of epochs, especially when using the `--evolve` option, can result in longer training times.

If the training exceeds an unexpectedly long duration, I recommend monitoring the GPU utilization to ensure it is being fully utilized. Also, double-check the number of worker processes and data loading pipelines to ensure efficient GPU usage.

Feel free to review the YOLOv5 documentation for tips on optimizing training times and GPU usage. If you have additional questions or concerns, please don't hesitate to ask.
