### ISSUE TITLE
RuntimeError: Inplace update to inference tensor outside InferenceMode is not allowed.You can make a clone to get a normal tensor before doing inplace update.See https://github.com/pytorch/rfcs/pull/17 for more details.

### ISSUE THREAD

**Issue by MarioCiranni** [ultralytics/yolov5#11186]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Starting training for 300 epochs...

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
      0/299         0G     0.1116    0.07286     0.1056        101        640: 100%|██████████| 16/16 [00:34<00:00,  2.14s/it]
                 Class     Images  Instances          P          R      mAP50   mAP50-95:   0%|          | 0/8 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 640, in <module>
    main(opt)
  File "train.py", line 529, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 352, in train
    results, maps, _ = validate.run(data_dict,
  File "/home/onair/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/onair/Desktop/LFE/portofino/yolov5/val.py", line 214, in run
    loss += compute_loss(train_out, targets)[1]  # box, obj, cls
  File "/home/onair/Desktop/LFE/portofino/yolov5/utils/loss.py", line 157, in __call__
    lcls += self.BCEcls(pcls, t)  # BCE
  File "/home/onair/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/onair/.local/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 713, in forward
    return F.binary_cross_entropy_with_logits(input, target,
  File "/home/onair/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 2960, in binary_cross_entropy_with_logits
    return torch.binary_cross_entropy_with_logits(input, target, weight, pos_weight, reduction_enum)
RuntimeError: Inplace update to inference tensor outside InferenceMode is not allowed.You can make a clone to get a normal tensor before doing inplace update.See https://github.com/pytorch/rfcs/pull/17 for more details.

### Environment

I am using the latest yolov5 available release in master and running on ubuntu 20.04.
This is my environment:
apturl==0.5.2
bcrypt==3.1.7
blinker==1.4
brlapi==0.7.0
bs4==0.0.1
cartopy==0.19.0.post1
catkin-pkg==0.4.24
catkin-pkg-modules==0.4.24
chardet==3.0.4
click==7.0
colorama==0.4.3
command-not-found==0.3
cryptography==2.8
cupshelpers==1.0
dbus-python==1.2.16
defer==1.0.6
distro==1.4.0
distro-info==0.23ubuntu1
django==3.2.9
docutils==0.16
drawsvg==1.8.3
duplicity==0.8.12.0
empy==3.3.2
entrypoints==0.3
fasteners==0.14.1
gdal==3.2.1
gitpython==3.1.31
jinja2==3.1.2
language-selector==0.1
launchpadlib==1.10.13
librosa==0.8.1
linecache2==1.0.0
lockfile==0.12.2
louis==3.12.0
macaroonbakery==1.3.1
mako==1.1.0
monotonic==1.5
netifaces==0.10.4
nose==1.3.7
olefile==0.46
opencv-python==4.5.3.56
openpyxl==3.0.10
paramiko==2.6.0
pbr==5.4.5
pexpect==4.6.0
pip-chill==1.0.1
psutil==5.5.1
pycryptodomex==3.6.1
pycups==1.9.73
pydot==1.4.1
pyftpdlib==1.5.6
pygments==2.3.1
pygobject==3.36.0
pyjwt==1.7.1
pymacaroons==0.13.0
pynacl==1.3.0
pyopengl==3.1.0
pypdf2==1.26.0
pyqt5==5.14.1
pyqubo==1.2.0
pyrfc3339==1.1
pytesseract==0.3.9
python-apt==2.0.0+ubuntu0.20.4.6
python-debian==0.1.36ubuntu1
python-gnupg==0.4.5
pyxdg==0.26
rawpy==0.17.1
reportlab==3.5.34
requests-unixsocket==0.2.0
roman==2.0.0
rosdep-modules==0.21.0
rosdistro==0.8.3
rosdistro-modules==0.8.3
rospkg==1.3.0
rospkg-modules==1.3.0
scikit-image==0.18.3
seaborn==0.11.2
serial==0.0.97
simplejson==3.16.0
sip==4.19.21
sklearn==0.0
systemd-python==234
tensorboard==2.6.0
tesserocr==2.5.2
thop==0.1.1.post2209072238
torchaudio==0.9.1
torchvision==0.10.1+cpu
tqdm==4.65.0
traceback2==1.4.0
ubuntu-advantage-tools==27.3
ubuntu-drivers-common==0.0.0
ufw==0.36
unattended-upgrades==0.1
unittest2==1.1.0
usb-creator==0.3.7
xkit==0.0.0
xlsxwriter==3.0.3

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by MarioCiranni** [comment]
If I launche the training even on coco128 example the script crush with the above message.
Here is what I type in from terminal:
python3 train.py --data coco128.yaml --epochs 300 --weights '' --cfg yolov5n.yaml  --batch-size 8

**Comment by huanhuan-xiao** [comment]
I got the same error. Could you solve this
![2023-03-21 11-33-04屏幕截图](https://user-images.githubusercontent.com/82137867/226517166-5ea636d4-0af3-4c91-9851-de2a495121b2.png)

**Comment by RogZWorld** [comment]
how to deal with this problem？

**Comment by glenn-jocher** [comment]
@RogZWorld the error message suggests that an inplace update was made to an inference tensor outside of the inference mode. You can make a clone to get a normal tensor before doing inplace update. 

In this case, you can try adding a clone() to overwrite pcls before computing the binary cross-entropy loss. Modify line 157 in '/utils/loss.py' to the following code:

```
lcls += self.BCEcls(pcls.clone(), t)  # BCE
```

If the issue persists, please let me know and provide more details about your setup, such as the environment, the version of pytorch and yolov5, etc.

**Comment by zhaoqier** [comment]
> @RogZWorld the error message suggests that an inplace update was made to an inference tensor outside of the inference mode. You can make a clone to get a normal tensor before doing inplace update.
> 
> In this case, you can try adding a clone() to overwrite pcls before computing the binary cross-entropy loss. Modify line 157 in '/utils/loss.py' to the following code:
> 
> ```
> lcls += self.BCEcls(pcls.clone(), t)  # BCE
> ```
> 
> If the issue persists, please let me know and provide more details about your setup, such as the environment, the version of pytorch and yolov5, etc.

Hi @glenn-jocher, I met the same problem and the modification of the line 157 does not solve it.

Here is my setup:

YOLOv5  v7.0-120-g3e55763 
Python-3.9.6 
torch-1.9.0+cpu CPU

I have made this version of setup to complete a training last month, but suddenly get this error today.

Thanks,

Qier

**Comment by zhaoqier** [comment]
> > @RogZWorld the error message suggests that an inplace update was made to an inference tensor outside of the inference mode. You can make a clone to get a normal tensor before doing inplace update.
> > In this case, you can try adding a clone() to overwrite pcls before computing the binary cross-entropy loss. Modify line 157 in '/utils/loss.py' to the following code:
> > ```
> > lcls += self.BCEcls(pcls.clone(), t)  # BCE
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If the issue persists, please let me know and provide more details about your setup, such as the environment, the version of pytorch and yolov5, etc.
> 
> Hi @glenn-jocher, I met the same problem and the modification of the line 157 does not solve it.
> 
> Here is my setup:
> 
> YOLOv5 v7.0-120-g3e55763 Python-3.9.6 torch-1.9.0+cpu CPU
> 
> I have made this version of setup to complete a training last month, but suddenly get this error today.
> 
> Thanks,
> 
> Qier

@glenn-jocher I think I found the reason that caused this error. I used a wrong conda env with is setup to match with YOLOv5  v5.0-370-gdbc06ce2 torch 1.9.0+cpu CPU. Which may caused the conflict when I run the YOLOv5 v7.0 on it.

Thanks,

Qier

**Comment by glenn-jocher** [comment]
Thank you for sharing your solution, @zhaoqier. It's great to hear that you found the root cause of the problem. Indeed, having different environment setups can sometimes cause unexpected issues. It's always a good idea to double-check your setup before starting any training or inference. If you have any further questions or concerns, don't hesitate to let me know.

**Comment by RogZWorld** [comment]
Thanks for your answers. I solved this problem. I found that using val's test task can change the model into an inference model when passing in model parameters in val. run(). Just deepcopy() the model can solve it.

**Comment by glenn-jocher** [comment]
@RogZWorld glad to hear that you were able to solve the problem! Yes, using `deepcopy()` to create a copy of the model can certainly help avoid inplace operations. It's also best practice to explicitly put the model in evaluation mode using `model.eval()` before running inference. If you have any further questions or concerns, feel free to reach out.

**Comment by shubhamjanu** [comment]
@zhaoqier could you please tell me how exactly you solved your issue for inplace updation. I am also facing the same issue.

**Comment by glenn-jocher** [comment]
Hello! To resolve the inplace update issue, you can create a deep copy of the model before running validation. This prevents any changes to the original model during inference. Here’s how you can do it:

```python
from copy import deepcopy

# Assuming 'model' is your original model
model_copy = deepcopy(model)
```

Then use `model_copy` for your validation or inference tasks. This should help avoid the inplace update error. Let me know if you need further assistance! 😊
