### ISSUE TITLE
Retrain the model

### ISSUE THREAD

**Issue by dhl961123** [ultralytics/yolov5#11180]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When I finish a training session (get best/last.pt). The next time the training model chooses one of the two (when a new picture needs to be added), but the best/last.pt after this training cannot successfully detect the last picture

### Additional

thanks

**Comment by glenn-jocher** [comment]
@dhl961123 thanks for reaching out! It sounds like you are experiencing issues with retraining the YOLOv5 model. Could you provide more details about your training process, such as the command you are using to retrain the model and any specific changes you have made to the default configuration?

The best/last.pt files should contain the weights of the best and last models obtained during training, so it's important to ensure that they are being loaded correctly for inference. Make sure to use the --weights flag to specify the path to the desired .pt file when running detection.

For more guidance on retraining the model and using the trained weights for detection, you can refer to the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/. Feel free to provide more details so we can assist you further.
