### ISSUE TITLE
Instance Segmentation  anchor Set 

### ISSUE THREAD

**Issue by huangqi111** [ultralytics/yolov5#11189]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

yolov5 v6.2,Instance segmentation train my own dataset .How to set anchor value in yolov5s-seg.yaml.

**Comment by glenn-jocher** [comment]
@huangqi111 hi there! For YOLOv5 instance segmentation with your own dataset, please use the `anchors` parameter in the `yolov5s-seg.yaml` file to set your anchor values. You can find more details about this in our documentation at https://docs.ultralytics.com/yolov5/. If you have any more questions, feel free to ask!
