### ISSUE TITLE
YOLOV5-7.0  detect.py--hide-conf:   TypeError: Can't convert object to 'str' for 'text'

### ISSUE THREAD

**Issue by tonycc521** [ultralytics/yolov5#11188]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

Hi, I used my trained model to predict the image, and the following error occurred when I used the hide-conf parameter:
python detect.py --hide-conf

Traceback (most recent call last):
  File "E:\yolov5\yolov5-7.0\detect.py", line 262, in <module>
    main(opt)
  File "E:\yolov5\yolov5-7.0\detect.py", line 257, in main
    run(**vars(opt))
  File "E:\yolov5-train\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "E:\yolov5\yolov5-7.0\detect.py", line 171, in run
    annotator.box_label(xyxy, label, color=colors(c, True))
  File "E:\yolov5\yolov5-7.0\utils\plots.py", line 105, in box_label
    w, h = cv2.getTextSize(label, 0, fontScale=self.lw / 3, thickness=tf)[0]  # text width, height
TypeError: Can't convert object to 'str' for 'text'

### Environment

-YOLO:Yolov5-7.0
-OS: Windows10
-Python:python-3.9

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@tonycc521 hi there! Thanks for reaching out. It looks like there's an issue with the hide-conf parameter in the detect.py script. To assist you better, could you please provide the minimal reproducible example or specific commands used to train the model? This will help us identify and address the issue more effectively. Thank you for your patience!

**Comment by ghost** [comment]
@glenn-jocher This error also happens to me from time to time while testing my custom model. I think it has nothing to do with how the model was trained, i think it is related with the text renderer module on the image since it almost always happens to me on vertical shot photographs on smartphones (images with width < height)

**Comment by glenn-jocher** [comment]
@k00r Thanks for sharing your insights. The scenario you described can indeed affect the text rendering on non-standard image orientations. We'll investigate and address this issue to improve the compatibility of text rendering in such cases. Your feedback is valuable, and your input contributes to the robustness of YOLOv5. Thank you for your understanding and patience!
