### ISSUE TITLE
Why doesn't the C3 use shortcuts in the neck

### ISSUE THREAD

**Issue by Squ1rrels** [ultralytics/yolov5#11197]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, glenn, I want to know why c3’s shortcut in neck are all False？
In this [issue ](https://github.com/ultralytics/yolov5/issues/4445#issue-972362320),you have replied that this is the design of Yolov5.
I tried many structures. It is true that the mAP without using shortcuts in the neck is always slightly higher than when using shortcuts.
Do you have any specific explanations or guesses? This has been bothering me for a long time.

**Comment by yang-0201** [comment]
Hello,I ask the same question in YOLOv8
https://github.com/ultralytics/ultralytics/issues/1200#issuecomment-1454873251

**Comment by Squ1rrels** [comment]
> Hello,I ask the same question in YOLOv8 [ultralytics/ultralytics#1200 (comment)](https://github.com/ultralytics/ultralytics/issues/1200#issuecomment-1454873251)

Thank you for your response. I have experimented with some different structures. Both mAP0.5 and mAP0.95 without using shortcuts are 0.3 to 0.5 percent higher than when using shortcuts. I have checked many issues on Yolov5 and Yolov8, and read many related papers, but I have found no reasonable explanation for this. It seems that this is only an empirical conclusion.

**Comment by yeshanliu** [comment]
My idea is that the residual connection is to create a deeper network to extract semantic features that are more relevant to the task, while the main role of C3 in Neck is to fuse deep semantic features with shallow localization features, when there is no need for a "deeper network" and "higher level semantic features".

**Comment by glenn-jocher** [comment]
@yeshanliu thank you for sharing your thorough experimentation and analysis! You make a good point about the role of the C3 layer in the neck and the trade-off between deep semantic and shallow localization features. Indeed, in the context of YOLOv5, the decision to use or not use shortcuts in the neck was made based on specific task-related requirements to achieve optimal performance. Your insights add valuable context to this ongoing discussion. While the YOLOv5 model design does not incorporate shortcuts in the neck, your findings could provide a basis for exploring potential optimizations in future iterations. Your active contribution is appreciated by the entire YOLO community and the Ultralytics team. If you have further feedback or observations, please feel free to share them.
