### ISSUE TITLE
xy in Annotator.text should be list instead of tuple

### ISSUE THREAD

**Issue by SashiRin** [ultralytics/yolov5#11196]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

In https://github.com/ultralytics/yolov5/blob/master/utils/plots.py#L268 (x + 5, y + 5) is a tuple, but in https://github.com/ultralytics/yolov5/blob/master/utils/plots.py#L156 there is a reassignment to tuple which is not allowed in python. Change (x + 5, y + 5) to [x + 5, y + 5] works fine in my environment.

### Environment

- OS: Ubuntu 22.04
- Python 3.10.6

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@SashiRin hi there, thanks for taking the time to report this! You're absolutely right, and we appreciate your willingness to submit a PR. We enjoy receiving contributions from the YOLO community. Your proposed change from tuple to list in `Annotator.text` looks good. Please go ahead and submit the PR when you're ready! If you have any questions or need assistance along the way, feel free to ask.

**Comment by SashiRin** [comment]
@glenn-jocher Thanks for your reply! The code seems to have been fixed.

```py
if paths:
            annotator.text([x + 5, y + 5], text=Path(paths[i]).name[:40], txt_color=(220, 220, 220))  # filenames
```

**Comment by glenn-jocher** [comment]
@SashiRin You're welcome! I'm glad to hear that the issue has been resolved. If you encounter any more issues or have further suggestions, please don't hesitate to let us know. Your feedback is valuable to us.
