### ISSUE TITLE
Change classes number of pretrained model

### ISSUE THREAD

**Issue by dani3l125** [ultralytics/yolov5#11191]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,

I am trying to train a model on manual dataset according to the tutorials. As my dataset is pretty small, I want to fine-ture weights that was trained on COCO dataset. However, I have only one class in my data.

So how can I both load the pretrained weights and reshape the head in order to return only one class?

BTW, the class is windows, which is one of the 10 classes with missing labels.

Thanks!

**Comment by jorgegonzalezv** [comment]
I think that setting 'nc' (number of categories) inside de data yaml of your custom dataset should work. Something like:

data.yaml:

path: <path-to-base-dir>
train: images/train  
val: images/val
test: images/tests
nc: 2

names:
  0: cat
  1: dog

I am now trying to figure out how does this affect the pretained weights, as not sure how much is the detection head being changed after reducing the number of classes. In terms of anchor boxes for example.

**Comment by dani3l125** [comment]
Thanks for the reply.
When running the configuration you suggested, a massage about overriding the model.yaml's nc is printed.
Even though the configuration is running, I will not close the issue in order to get more information about the behavior of the weights and head in that circumstances.

**Comment by glenn-jocher** [comment]
@dani3l125 the `nc` (number of classes) parameter in `data.yaml` does indeed control the number of classes for your custom trained dataset, as you correctly mentioned. When modifying the number of classes, YOLOv5 adjusts the final detection layer accordingly. If the issue persists even after you've set the `nc` parameter, please let me know. I'd be glad to help further.
