### ISSUE TITLE
How to extract bounding box coordinates from a YolovV5 object detection model that has been converted to a CoreML model for use in an iOS app

### ISSUE THREAD

**Issue by dhiman10** [ultralytics/yolov5#11207]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have tried it for export !python export.py --weights /content/drive/MyDrive/best.pt --include "coreml"

Could anyone know how can I convert correctly and get the bounding box, score, and other things?

**Comment by junmcenroe** [comment]
@dhiman10

I put exporter on following referencing #10483

https://github.com/junmcenroe/YOLOv5-CoreML-Export-with-NMS.git
