### ISSUE TITLE
Customization of YOLOv5 dataloader

### ISSUE THREAD

**Issue by 25benjaminli** [ultralytics/yolov5#11212]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Hi, I was researching several techniques for selecting augmentations/hyperparameters involving algorithms such as reinforcement learning - e.g. https://github.com/DeepVoltaire/AutoAugment. They work fine with pytorch's dataloader, but I was wondering if you could build integration for allowing users to modify the default dataloader to include custom hyperparameters and such.

### Use case

Would be very helpful for implementing custom augmentations. I do not want to run offline augmentation because it can be unreliable and hard to quantify the performance of.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@25benjaminli hi there! Thank you for reaching out. Customizing the dataloader to include custom hyperparameters and augmentations is an interesting idea. While we don't have built-in integration for this specific use case, you can achieve custom augmentations by leveraging the power of the torchvision.transforms and albumentations libraries directly within your dataset classes. This allows for a wide range of customization options.

Offline augmentation is also a viable option, but I understand the concern about reliability and performance quantification. By incorporating augmentation directly into the dataloader, you can ensure a more streamlined and controlled process.

Feel free to check out our documentation at https://docs.ultralytics.com/yolov5/ for further guidance on customizing augmentations. If you have any other questions or need additional assistance, don't hesitate to ask. Your feedback is greatly appreciated!
