### ISSUE TITLE
YOLO5 Accuracy

### ISSUE THREAD

**Issue by saiphyozinko** [ultralytics/yolov5#11219]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question 

Hello, I want to get the accuracy of the custom YOLOv5s model. Is there any ways to get it? For example, my custom dataset has 83.88% accuracy. Please note: I don't want model accuracy mAP score, I just want the custom trained model accuracy. Moreover, do YOLO v5 has any references paper to learn its architecture. Can you kindly help me?

**Comment by glenn-jocher** [comment]
@saiphyozinko hi there! 🌟 YOLOv5 doesn't provide a direct accuracy metric like traditional classifiers. In object detection, we typically use mAP for performance evaluation. Regarding the architecture, you can find that in our [Ultralytics Docs](https://docs.ultralytics.com/yolov5/). As always, feel free to ask if you have further questions. Good luck with your custom model!
