### ISSUE TITLE
Where is YOLOv5 docs?

### ISSUE THREAD

**Issue by kimwonj77** [ultralytics/yolov5#11211]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

The https://docs.ultralytics.com/ which is linked to YOLOv5 docs in README, and Github links. is YOLOv8 docs now. Where is the `v5` docs?

**Comment by glenn-jocher** [comment]
@kimwonj77 thanks for bringing this to our attention! The YOLOv5 documentation is available at https://docs.ultralytics.com/yolov5/. If you have any other questions or need further assistance, feel free to ask!
