### ISSUE TITLE
AssertionError: File not found: crack_data.yaml

### ISSUE THREAD

**Issue by farhanqamar031** [ultralytics/yolov5#11228]
# Train YOLOv5s on COCO128 for 3 epochs
!python segment/train.py --img 640 --batch 16 --epochs 3 --data crack_data.yaml --weights yolov5s-seg.pt --cache
i have train this code and have crack_data.yaml file but i got the below error every time i run the code
segment/train: weights=yolov5s-seg.pt, cfg=, data=crack_data.yaml, hyp=data/hyps/hyp.scratch-low.yaml, epochs=3, batch_size=16, imgsz=640, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, noplots=False, evolve=None, bucket=, cache=ram, image_weights=False, device=, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=8, project=runs/train-seg, name=exp, exist_ok=False, quad=False, cos_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, seed=0, local_rank=-1, mask_ratio=4, no_overlap=False
github: up to date with https://github.com/ultralytics/yolov5 ✅
Traceback (most recent call last):
  File "/content/yolov5/yolov5/yolov5/yolov5/segment/train.py", line 664, in <module>
    main(opt)
  File "/content/yolov5/yolov5/yolov5/yolov5/segment/train.py", line 530, in main
    check_file(opt.data), check_yaml(opt.cfg), check_yaml(opt.hyp), str(opt.weights), str(opt.project)  # checks
  File "/content/yolov5/yolov5/yolov5/yolov5/utils/general.py", line 491, in check_file
    assert len(files), f'File not found: {file}'  # assert file was found
AssertionError: File not found: crack_data.yaml

**Comment by glenn-jocher** [comment]
@farhanqamar031 it seems that there might be an issue with the path to your crack_data.yaml file. Ensure that the file is present in the correct location and that the path provided is accurate. Additionally, you can double-check the file name for any typos.

You can also refer to the YOLOv5 documentation for more information on setting up custom datasets and training: https://docs.ultralytics.com/yolov5/

If the issue persists, feel free to provide more details about your directory structure or the steps you followed for creating and referencing the crack_data.yaml file, so I can assist you further.
