### ISSUE TITLE
Cannot run distributed or data parallel training in the YOLOv5 docker container

### ISSUE THREAD

**Issue by h-fernand** [ultralytics/yolov5#11225]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training, Multi-GPU

### Bug

I've been trying to use DDP training to take advantage of the dual A5500 GPUs on an ML workstation. The GPUs are connected with an NVLink bridge. For some reason whenever I try to run the distributed training environment the logger info spits out all of my parameters, github info, hyperparameters, and the notice about TensorBoard before immediately coming to a halt. I've let it sit for about ten minutes max and no changes have been noticed. Looking at my GPU performance monitor I notice a small but apparent rise in GPU memory usage upon startup of the training, so clearly SOMETHING is happening under the hood but I have no idea what. 

When trying to run data parallel training instead there is a crash immediately upon starting the first training epoch that produces the following error message:

```
Using 2 dataloader workers
Logging results to runs/train-seg/exp3
Starting training for 300 epochs...

      Epoch    GPU_mem   box_loss   seg_loss   obj_loss   cls_loss  Instances       Size
  0%|          | 0/800 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/usr/src/app/segment/train.py", line 664, in <module>
    main(opt)
  File "/usr/src/app/segment/train.py", line 555, in main
    train(opt.hyp, opt, device, callbacks)
  File "/usr/src/app/segment/train.py", line 324, in train
    scaler.step(optimizer)  # optimizer.step
  File "/opt/conda/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 341, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 287, in _maybe_opt_step
    if not sum(v.item() for v in optimizer_state["found_inf_per_device"].values()):
  File "/opt/conda/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 287, in <genexpr>
    if not sum(v.item() for v in optimizer_state["found_inf_per_device"].values()):
RuntimeError: CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Aborted
```

Additionally, sometimes the system will hang in the middle of downloading the COCO dataset and fail to proceed.

Running training with the flag --device 0 to force YOLO to only use one GPU works, but crashes almost instantly due to unavailable memory.

I've been able to get DataParallel training working outside of the container so I'm really not sure what's happening here. I followed all of the instructions in the docker quickstart guide and the multi-gpu training pages. 

### Environment

I'm running the YOLOv5 Docker container on a Windows machine in WSL2 with Ubuntu 20.04. 

### Minimal Reproducible Example

The following command will result in no output after the message about TensorBoard is displayed
```
python -m torch.distributed.run --nproc_per_node 2 train.py --batch 2 --data coco.yaml --weights yolov5n.pt
```

The following command immediately crashes upon training start due to an unknown CUDA error
```
python train.py --batch 2 --data coco.yaml --weights yolov5n.pt
```

### Additional

The fact that I can get DataParallel training to work outside of the docker environment makes me think something is either wrong with the container itself, or with my Nvidia installation. I know that windows support is considered untested and unverified, but should that affect this since I'm running everything through WSL? I'd really like to find a way to get this to work so I can use the larger versions of YOLO with my dataset by taking advantage of NVLink's memory pooling. 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@h-fernand sorry you're experiencing issues with distributed and data parallel training. The described behavior seems to indicate a CUDA error, which could be due to various causes. Regarding the Docker container, WSL2, and GPU support on Windows, it's indeed an area under continuous development and testing. Some considerations include ensuring proper CUDA and NVIDIA driver versions and permissions configurations for Docker and WSL2. For DDP training, if there's an NVLink bridge, the necessary setup instructions were followed correctly?

Regarding the fast DataParallel, training seems to work outside the container but not inside; this could indicate an environment-specific issue.

For more detailed troubleshooting and assistance, fee1 free to check the Ultralytics Docs or, for specific issues, initiate a GitHub discussion or Pull Request as the Ultralytics YOLOv5 community always benefits from new insights.

Your feedback will also help improve and streamline the YOLOv5 ecosystem experience for all users.
