### ISSUE TITLE
Can I display the class probability in one detection

### ISSUE THREAD

**Issue by K4elthaz** [ultralytics/yolov5#11221]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Example 
trained 3 classes then

then i use detect.py to scan a dog then the detect image output will have 

bounding box of a dog 
Class detected = dog then beside the class detected is the other 2 class with low confidence level or no confidence level at all something like that.

Dog 0.7%
Cat 0.1%
Bird 0.2% 
Something like this beside the bounding boxes
Thank you so much

**Comment by glenn-jocher** [comment]
@K4elthaz yes, you can display the class probabilities alongside the detections. The default behavior of YOLOv5 is to display the most confident class, but you can visualize additional classes with `--verbose` flag in `detect.py` as documented [here](https://docs.ultralytics.com/yolov5/detection). Happy to help!
