### ISSUE TITLE
CBAM attention in YOLOv5 

### ISSUE THREAD

**Issue by Kushgupta1121** [ultralytics/yolov5#11236]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,

Thank you for the amazing work with yolov5. I'm trying to insert the CBAM- attention module after the backbone and before the detection head for all three (small/medium/large) scales for my project. When I'm running the detect.py the code is running fine and giving some weird output maybe because the CBAM module is not trained with YOLOv5. The problem appears when I'm trying to train YOLOv5 along with the CBAM attention module. I'm attaching the cbam module (.py file that I wrote), and the modified yolo.py file in the models folder. 
I have inserted CBAM here: 
![image](https://user-images.githubusercontent.com/101636931/227591702-eaa163f4-94ac-426b-9325-4bdf7de1ed24.png)

When I'm running the training the first error I got is:
![image](https://user-images.githubusercontent.com/101636931/227594411-a913e918-1743-4c2b-b3da-a42a9818ab30.png)

Then I set the warn_only flag to true in general.py (torch.use_deterministic_algorithms(True,warn_only=True)).
However, later I got the below two errors 
![image](https://user-images.githubusercontent.com/101636931/227592834-cb803d82-b173-4965-977d-cd44838ecb63.png)
![image](https://user-images.githubusercontent.com/101636931/227592955-0e245a22-6611-473f-b86b-6f3e9a6209e2.png)

I'm stuck here and I tried to debug a lot but wasn't able to figure it out. Can you please suggest how can i solve this error. Also please let me know if you need more inputs to reproduce the error.

**Comment by Kushgupta1121** [comment]
Solution found here https://github.com/ultralytics/yolov5/pull/9750

**Comment by glenn-jocher** [comment]
@Kushgupta1121, glad to hear that you found the solution to the problem you were facing in YOLOv5, could you provide additional context for others searching for similar issues? Thank you for using YOLOv5 🚀!

**Comment by Kushgupta1121** [comment]
I was trying to implement a model to plugin the CBAM- attention module after the backbone and before the detection head for all different three (small/medium/large) scales for my project. To achieve this I modified the model YAML file a bit such that the model architecture looks like this:
![yolo_cbam_model](https://user-images.githubusercontent.com/101636931/231763632-44b08ba6-3306-42a9-be1d-54c8db7713e2.png)

**Comment by glenn-jocher** [comment]
@Kushgupta1121, thank you for providing more context to your issue. In general, modifying YOLOv5's architecture can be complex and requires a good understanding of the codebase. It's recommended to make small changes and test them thoroughly to ensure they integrate well with the rest of the code. It's also recommended to create a new model YAML file and use it to configure your training script if you make significant changes.

For your specific issue, it looks like you were able to fix the error by registering the CBAM classes with PyTorch's `nn.ModuleDict()` and adding them to the `forward()` method of `CSPBlock` in `models/common.py`. This is a good solution and a nice workaround. Thank you for sharing the solution with the community!

**Comment by Kushgupta1121** [comment]
@glenn-jocher Thank you for your fantastic work with YOLO and for your kind words. Yes, I registered the CBAM class in models/common.py and modified the parse_model() method in model/yolo.py at lines 329 and 335 as shown below.
![Screenshot 2023-04-13 at 11 48 05 PM](https://user-images.githubusercontent.com/101636931/231890287-bacdb855-c995-4dfe-a7bc-f5c69e4ea7aa.png)

Also, this is how I modified the YAML file for YOLOv5m to include the CBAM module. (If someone wants to refer). :)
![Screenshot 2023-04-13 at 11 49 17 PM](https://user-images.githubusercontent.com/101636931/231890442-d8143475-266f-4a35-9b00-4057b0a7ed93.png)

**Comment by dhrubapuc23** [comment]
> @glenn-jocher Thank you for your fantastic work with YOLO and for your kind words. Yes, I registered the CBAM class in models/common.py and modified the parse_model() method in model/yolo.py at lines 329 and 335 as shown below. ![Screenshot 2023-04-13 at 11 48 05 PM](https://user-images.githubusercontent.com/101636931/231890287-bacdb855-c995-4dfe-a7bc-f5c69e4ea7aa.png)
> 
> Also, this is how I modified the YAML file for YOLOv5m to include the CBAM module. (If someone wants to refer). :) ![Screenshot 2023-04-13 at 11 49 17 PM](https://user-images.githubusercontent.com/101636931/231890442-d8143475-266f-4a35-9b00-4057b0a7ed93.png


I did it with yolov5s but got stuck with other variations like yolov5x. Any hints?

**Comment by Kushgupta1121** [comment]
@dhrubapuc23 If you mean, it works for YOLOv5s and not for higher versions then you should check the YAML file because I'm using it for yolov5m and yolov5x6 and it's working fine for me.

**Comment by glenn-jocher** [comment]
@dhrubapuc23 Thanks for your reply! You may want to double-check the YAML file to ensure it's matching your desired model architecture. Additionally, it's important to register the CBAM classes properly in `models/common.py` and modify the `parse_model()` method in `model/yolo.py` as needed. If you're still having issues, please provide more details about the specific issue you're facing and any error messages you're seeing.

**Comment by dhrubapuc23** [comment]
@Kushgupta1121 Thanks for your reply. I have tried to include it in my YAML files but got the following errors
yolov5/models/common.py", line 111, in forward
    out = self.spatial_attention(out) * out
RuntimeError: The size of tensor a (31) must match the size of tensor b (32) at non-singleton dimension 3

**Comment by dhrubapuc23** [comment]
> @dhrubapuc23 Thanks for your reply! You may want to double-check the YAML file to ensure it's matching your desired model architecture. Additionally, it's important to register the CBAM classes properly in `models/common.py` and modify the `parse_model()` method in `model/yolo.py` as needed. If you're still having issues, please provide more details about the specific issue you're facing and any error messages you're seeing.

Thanks for your response. I mentioned the errors in my previous comment.

**Comment by glenn-jocher** [comment]
@dhrubapuc23 thanks for providing more information about the error you are facing.

The error message you received suggests that there is a size mismatch between tensors when passing through the spatial attention module. This could be due to a variety of reasons, such as incorrect dimensions in the input tensor or incorrect weights in the CBAM module.

To further investigate this issue, I recommend checking the input tensor size and shape before passing it through the CBAM module. Additionally, you may want to verify that the weights of the CBAM module were properly initialized and loaded.

If you continue to face this issue, please provide more information about the input tensor size and the CBAM module's architecture and configuration so we can help you better.

Best regards.

**Comment by lchunleo** [comment]
> I was trying to implement a model to plugin the CBAM- attention module after the backbone and before the detection head for all different three (small/medium/large) scales for my project. To achieve this I modified the model YAML file a bit such that the model architecture looks like this: ![yolo_cbam_model](https://user-images.githubusercontent.com/101636931/231763632-44b08ba6-3306-42a9-be1d-54c8db7713e2.png)

@Kushgupta1121 can I check with this design , do you find issues on the model training performance? I replicated it but on my dataset the model training performance is bad. Any advice ?

**Comment by lchunleo** [comment]
> @glenn-jocher Thank you for your fantastic work with YOLO and for your kind words. Yes, I registered the CBAM class in models/common.py and modified the parse_model() method in model/yolo.py at lines 329 and 335 as shown below. ![Screenshot 2023-04-13 at 11 48 05 PM](https://user-images.githubusercontent.com/101636931/231890287-bacdb855-c995-4dfe-a7bc-f5c69e4ea7aa.png)
> 
> Also, this is how I modified the YAML file for YOLOv5m to include the CBAM module. (If someone wants to refer). :) ![Screenshot 2023-04-13 at 11 49 17 PM](https://user-images.githubusercontent.com/101636931/231890442-d8143475-266f-4a35-9b00-4057b0a7ed93.png)

@dhrubapuc23  I had replicated the design but the model training performance seem very poor. The map is almost 0.  I wonder what else can be wrong.

**Comment by Blessing988** [comment]
@glenn-jocher Does the classification models of YOLOv5 support the attachment of custom modules like CBAM. I tried doing that but couldn't implement it.

**Comment by glenn-jocher** [comment]
@Blessing988 hello! Yes, YOLOv5's architecture is flexible, allowing the integration of custom modules like CBAM. However, integrating such modules requires careful adjustments. You must ensure the dimensions match and that the module is correctly registered in the network. Please review the dimensions of your inputs and outputs within the CBAM and where it's being inserted in the YOLOv5 model. If you hit a specific error or need further assistance, feel free to share more details on the error or the part of the code where you're facing issues. Happy coding! 😊

**Comment by Blessing988** [comment]
When I checked the codebase for YOLOv5-cls for model loading, I realized the model imports the weights of YOLOv5 detection models from torch.hub,  removes the neck and head and attaches a new classification head. Changing the contents of the `common.py` file has no effect.

**Comment by glenn-jocher** [comment]
@Blessing988 hey there! 😊 You're right about how YOLOv5-cls operates by modifying the YOLOv5 model from torch.hub for classification purposes. Modifications in `common.py` won't impact this directly since the model's architecture is fetched from torch.hub, not from your local changes. To incorporate custom changes like a new module, you'd need to manually adjust the model after it's loaded or work on a locally modified version of YOLOv5 where you have your changes, then load it accordingly. Hope this helps clarify things!

**Comment by AmirAliEmami99** [comment]
> @dhrubapuc23 If you mean, it works for YOLOv5s and not for higher versions then you should check the YAML file because I'm using it for yolov5m and yolov5x6 and it's working fine for me.

Dear Kush Gupta, Could you please direct me to where I might find the implementation details for attention modules classes such as CBAM? 

Additionally, besides adding these implementations in the common.py file, modifying the parse_model() method in model/yolo.py, and updating the YAML file for YOLOv5m, are there any other modifications that I should consider?
