### ISSUE TITLE
How to save Time of the object when it detected in Video using YoloV5

### ISSUE THREAD

**Issue by hammad2008** [ultralytics/yolov5#11233]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I hope you are doing well. The yolov5 save the output text file with the Class label and bounding box value. 

1. I want to save time when the object is detected in Video 
2.  The class name will be saved not the label.

**Comment by hammad2008** [comment]
@glenn-jocher  Can you please Help me with this.

**Comment by glenn-jocher** [comment]
@hammad2008 you can handle results however you need to, see https://docs.ultralytics.com/modes/predict for details

**Comment by hammad2008** [comment]
@glenn-jocher  i have gone through that link, but it does not help. Can you please modified the code and share

**Comment by hammad2008** [comment]
@glenn-jocher 

I have changed the Code in the following Section 

![Capture](https://user-images.githubusercontent.com/75312856/227702668-9d6d294e-7519-4f83-910e-b98a22687bd8.PNG)


But it save the output Like this one.

14 0.0183594 0.0378338 0.0367187 0.0667656, 2023-03-25 07:06:24

**Comment by glenn-jocher** [comment]
See https://docs.ultralytics.com/modes/predict for handling Results
