### ISSUE TITLE
WARNING  SegmentationModel not yet supported for PyTorch Hub AutoShape inference

### ISSUE THREAD

**Issue by z13228604287** [ultralytics/yolov5#11234]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

PyTorch Hub:     model = torch.hub.load('ultralytics/yolov5', 'custom', 'yolov5s-seg.onnx')  # WARNING  SegmentationModel not yet supported for PyTorch Hub AutoShape inference
How to solve

**Comment by glenn-jocher** [comment]
@z13228604287 segmentation inference is fully supported in YOLOv8 at https://github.com/ultralytics/ultralytics
