### ISSUE TITLE
How to save Timestamp in text file of the object detected in video 

### ISSUE THREAD

**Issue by hammad2008** [ultralytics/yolov5#11231]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I hope you are doing well. I want to save time when the object is detected in Video. 
The --save--text option saves only the label and Bounding box coordinates.

**Comment by glenn-jocher** [comment]
@hammad2008 hello! Thanks for reaching out. To save the timestamp along with the detected objects in a video, you can modify the source code to include the timestamp in the text file. You can access the timestamp using the video capture object or frame array index and append it to the text file along with the label and bounding box coordinates. 

Let me know if you need further assistance with the implementation. Good luck with your project!
