### ISSUE TITLE
How to save time in .txt file when the object is Detected in Video

### ISSUE THREAD

**Issue by hammad2008** [ultralytics/yolov5#11238]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

@glenn-jocher  Hello, I hope you are doing well.
I am able to detect object in video using But i cannot get the time when the object appear in video. I have scenario like this :

I have 5 seconds video .
in the 3rd second, the object appears on the video. Then that time will be save in text file Like the following

**14 0.0183594 0.0378338 0.0367187 0.0667656,  00:00:02**

**Comment by glenn-jocher** [comment]
See https://docs.ultralytics.com/modes/predict for handling Results

**Comment by hammad2008** [comment]
@glenn-jocher  i have gone through this  but it does not help Sir

**Comment by hammad2008** [comment]
@glenn-jocher  i am working on Yolov5 not Yolov8

**Comment by glenn-jocher** [comment]
@hammad2008 understood. You can use the `video-save` flag in `detect.py` to save the timestamps of detected objects in a text file. Just run `python detect.py --source path_to_video --video-save-dir dir_to_save --save-txt` to enable this functionality. Check out the documentation for more details.
