### ISSUE TITLE
 Save Time of the object when it detected in Video using YoloV5 and save output text with Class name Not labels

### ISSUE THREAD

**Issue by hammad2008** [ultralytics/yolov5#11232]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Save Time of the object when it detected in Video using YoloV5 and save output text with Class name Not labels

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@hammad2008 hi there! Thanks for reaching out. Saving the time of the object when it's detected in a video and saving the output text with class names is a great feature request. We currently don't have this specific functionality, but feel free to submit a pull request if you'd like to contribute to the YOLOv5 project! If you need any guidance on getting started with your PR, please check out our documentation for reference. Thank you for your interest in improving YOLOv5!
