### ISSUE TITLE
[Segmentation] MPS Crash on training start. error: subRange.start (3) is not less than length of dimension[1] (3)

### ISSUE THREAD

**Issue by masc-it** [ultralytics/yolov5#11235]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

I'm trying to train a S-segmentation model on my mac m1 pro, but as soon as I set mps as device, I get this:
```
Logging results to runs/train-seg/exp4
Starting training for 3 epochs...

      Epoch    GPU_mem   box_loss   seg_loss   obj_loss   cls_loss  Instances       Size
  0%|          | 0/8 [00:00<?, ?it/s]/AppleInternal/Library/BuildRoots/f0468ab4-4115-11ed-8edc-7ef33c48bc85/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSCore/Types/MPSNDArray.mm:82: failed assertion `[MPSNDArrayDescriptor sliceDimension:withSubrange:] error: subRange.start (3) is not less than length of dimension[1] (3)'
[1]    47124 abort      python segment/train.py --img 640 --batch 8 --epochs 3 --data  --weights
```

With cpu runs just fine though.

### Environment

- YOLOv5 🚀 v7.0-128-gb96f35c Python-3.10.10 torch-2.0.0 MPS

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by yiluoegit** [comment]
I'm also having this issue。

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/76962284/227851959-240f8f20-d2a9-430a-b3d9-fa9e7d768cc8.png">

**Comment by InsuPK** [comment]
<img width="842" alt="image" src="https://user-images.githubusercontent.com/107782364/228712995-959e2d66-4028-494e-97f6-2ffd9d012dfb.png">

I got the same error with M1 pro 14.

**Comment by glenn-jocher** [comment]
👋 Hello @jhm2012 and @Suhyeon-Lee, this error appears to be associated with Metal Performance Shaders (MPS), which are required to enable GPU acceleration on Apple devices. 

First, please try upgrading PyTorch via `pip install --upgrade torch torchvision torchaudio` as newer PyTorch versions may include MPS improvements that address this issue.

If that doesn't work, try specifying `mp` as device in `segment/train.py` rather than `mps`, e.g. `--device mp`.

If that also does not work, please try installing the [latest version of PyTorch specifically for M1 chips](https://developer.nvidia.com/cuda-downloads/mac-osx-arm64), then try `--device cuda:0`. 

If that also doesn't work, I would recommend training on CPU until a solution is found.

**Comment by xiong111** [comment]
I got the same error too, in my M1 Max Pro 14, "--device mp" got "AssertionError: Invalid CUDA '--device mp' requested, use '--device cpu' or pass valid CUDA device(s)",and the link of "latest version of PyTorch specifically for M1 chilps" is an invalid url.

**Comment by glenn-jocher** [comment]
@xiong111, I apologize for the mistake in the previous message. It seems the latest version of PyTorch for ARM Macs can be found on the official PyTorch website: https://pytorch.org/get-started/locally/. Make sure to select "macOS" and the correct `pip` install command for your version of Python (e.g., `pip install torch torchvision torchaudio -f https://download.pytorch.org/whl/torch_stable/macosx-10.15-arm64/`).

Regarding the MPS error, you might also try updating the version of Metal Performance Shaders (MPS) you have installed on your system, which can be done through your Mac's App Store or by installing the latest version of Xcode Command Line Tools.

If none of these steps solve the issue, it is possible that the error is related to a compatibility issue between PyTorch and the M1 chip. In that case, you may have to wait for an update from Apple or PyTorch to fix the issue. In the meantime, I would recommend training on CPU, as mentioned before.

**Comment by xiong111** [comment]
I found that YOLOv8 work with mps rightly,thanks @glenn-jocher a lot!
The code is:

```
from ultralytics import YOLO

if __name__ == '__main__':
    model = YOLO("yolov8l.pt") 
   model.train(data="coco128.yaml", epochs=3,device="mps") 

```

**Comment by masc-it** [comment]
> @xiong111, I apologize for the mistake in the previous message. It seems the latest version of PyTorch for ARM Macs can be found on the official PyTorch website: https://pytorch.org/get-started/locally/. Make sure to select "macOS" and the correct `pip` install command for your version of Python (e.g., `pip install torch torchvision torchaudio -f https://download.pytorch.org/whl/torch_stable/macosx-10.15-arm64/`).
> 
> Regarding the MPS error, you might also try updating the version of Metal Performance Shaders (MPS) you have installed on your system, which can be done through your Mac's App Store or by installing the latest version of Xcode Command Line Tools.
> 
> If none of these steps solve the issue, it is possible that the error is related to a compatibility issue between PyTorch and the M1 chip. In that case, you may have to wait for an update from Apple or PyTorch to fix the issue. In the meantime, I would recommend training on CPU, as mentioned before.

pytorch and MPS are just fine. YoloV5 training w/ MPS seems broken, while YoloV8 run smoothly.. that's weird, isn't it? :/

**Comment by glenn-jocher** [comment]
@masc-it, it is certainly possible that this is a bug or compatibility issue specific to YOLOv5 training with MPS on M1 chips. YOLOv8, on the other hand, may have been specifically designed with optimizations for M1 chips and therefore does not experience the same issue. 

Nonetheless, it would be helpful to submit a bug report to the YOLOv5 GitHub repo at https://github.com/ultralytics/yolov5/issues to inform the developers of this issue and to see if they can work to fix it. In the meantime, training on CPU or using YOLOv8 are viable options.

**Comment by laclouis5** [comment]
I got a related but different issue. Training with MPS works fine but takes enormous quantities of RAM compared to CPU on my MacBook Pro 14" 16GB and is quite slow.

My environment:

* Python 3.10.9
* PyTorch 2.0.0
* Ultralytics 8.0.83
* MacBook Pro 14" 16GB with M1 Pro

I installed it through:

```
python3 -m venv env
source env/bin/activate
pip install ultralytics
```

I launched training with:

```
yolo detect train model=yolov8n.pt data=coco128.yaml device=mps
```

And I tried to manually decrease the memory used:

```
yolo detect train model=yolov8n.pt data=coco128.yaml device=mps batch=8 workers=4
```

**The RAM used quickly reaches >10GB** and seems to increase over time compared to 300-800MB when training is done on the CPU. Training speed is fast the first epoch (12 IPS with batch size of 8) but it slows down as training progresses (4 IPS).

**Comment by pbreuss** [comment]
In my case the training images and labels were corrupted - after I got a new dataset, training with yolov5 and device=mps worked very well.

**Comment by glenn-jocher** [comment]
That's great to hear! Thank you for updating us. It's good to know that the issue was related to the dataset, and I'm glad to hear that training with YOLOv5 and `device=mps` is now working well for you with the new dataset.

If you have any more questions or run into any other issues, please feel free to reach out. We're here to help!

**Comment by glenn-jocher** [comment]
Thank you for sharing your findings, @masc-it! It's great to hear that the issue was resolved by updating the dataset. Maintaining high-quality datasets is crucial for successful training. If you encounter any more issues or have further questions, feel free to reach out. Best of luck with your future training endeavors with YOLOv5!

**Comment by glenn-jocher** [comment]
That's great to hear! I'm glad to know that the issue has been resolved and that training with YOLOv5 and device=mps is now working well for you. If you encounter any further issues or have any questions in the future, please don't hesitate to reach out. Thank you for sharing your solution, and happy training with YOLOv5!

**Comment by glenn-jocher** [comment]
Thank you for updating us on your progress. It's great to hear that after acquiring a new dataset, training with YOLOv5 and using the device=mps setting has been successful for you. If you encounter any further issues or have additional feedback, please feel free to reach out!

**Comment by liyonghao0618** [comment]
> > @xiong111, I apologize for the mistake in the previous message. It seems the latest version of PyTorch for ARM Macs can be found on the official PyTorch website: https://pytorch.org/get-started/locally/. Make sure to select "macOS" and the correct `pip` install command for your version of Python (e.g., `pip install torch torchvision torchaudio -f https://download.pytorch.org/whl/torch_stable/macosx-10.15-arm64/`).
> > Regarding the MPS error, you might also try updating the version of Metal Performance Shaders (MPS) you have installed on your system, which can be done through your Mac's App Store or by installing the latest version of Xcode Command Line Tools.
> > If none of these steps solve the issue, it is possible that the error is related to a compatibility issue between PyTorch and the M1 chip. In that case, you may have to wait for an update from Apple or PyTorch to fix the issue. In the meantime, I would recommend training on CPU, as mentioned before.
> 
> pytorch and MPS are just fine. YoloV5 training w/ MPS seems broken, while YoloV8 run smoothly.. that's weird, isn't it? :/

Yes,MPS works fine with YoloV8!

**Comment by anik055** [comment]
@xiong111 , have you got the solution for yolov5?

**Comment by masc-it** [comment]
nop but I suggest you to just go ahead. They have personally stopped supporting YoloV5 for this sort of issues. (imo Understandable since they work on V8)

**Comment by glenn-jocher** [comment]
@masc-it it's understandable that the focus might shift towards newer versions like YOLOv8, which could offer improved compatibility and performance, especially on newer hardware like the M1 chips. However, for those still working with YOLOv5 and encountering issues, we continue to recommend referring to the [Ultralytics Docs](https://docs.ultralytics.com/yolov5/) for troubleshooting, optimization tips, and updates. Your feedback and reports on GitHub are invaluable for improving the models and supporting a wider range of devices. Thank you for your understanding and contributions to the community! 🙏

**Comment by Jckwind** [comment]
i belive this is due to a bug in pytorch. here's a fix: https://github.com/pytorch/pytorch/pull/121645

**Comment by glenn-jocher** [comment]
@Jckwind i'm unable to confirm or discuss specifics about ongoing developments in PyTorch or other projects. However, if you've identified a potential fix in PyTorch that could address your issue, it's great that the community is actively working on improvements and bug fixes. For those experiencing similar issues, keeping PyTorch updated to the latest version is always a good practice, as it can include important fixes and performance enhancements. 

Remember, for any issues directly related to YOLOv5, our GitHub issues page is the best place to seek help. Your contributions and feedback help us make YOLOv5 better for everyone. Thank you for being a part of our community! 🌟
