### ISSUE TITLE
Can't load custom weights 

### ISSUE THREAD

**Issue by qweqweq1222** [ultralytics/yolov5#11239]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Integrations, Other

### Bug

HTTP Error 404: Not Found

### Minimal Reproducible Example

model = torch.hub.load('ultralytics/yolov8', 'yolov8m',path='/content/best.pt', force_reload=True)

### Additional

Can someone explain to me what I'm doing wrong and give me an example of how to do it right? I just need to load the weights from best.pt into the model 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@qweqweq1222 hi there! It looks like you're trying to load custom weights into an YOLO model, but there seems to be an issue with the path. You should be able to load custom weights using `model = torch.hub.load('ultralytics/yolov5', 'custom', path='/path/to/best.pt')`. Make sure to replace `/path/to/best.pt` with the actual path to your weights file. 

Also, don't forget to check out the documentation at https://docs.ultralytics.com/yolov5/ for more detailed instructions on using custom weights. Let me know if you need further assistance!
