### ISSUE TITLE
How to save class Name instead of Label in .Text file

### ISSUE THREAD

**Issue by hammad2008** [ultralytics/yolov5#11237]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

@glenn-jocher  Hello, I hope you are doing well. I want to save Class Name Instead of label for example: The text file is saving in the following format
2 0.408203 0.95549 0.105469 0.0860534

But i want to save it as 
Cat 0.408203 0.95549 0.105469 0.0860534

**Comment by glenn-jocher** [comment]
See https://docs.ultralytics.com/modes/predict for handling Results

**Comment by hammad2008** [comment]
@glenn-jocher  Sir it does not help thats why i am posting again and again

**Comment by glenn-jocher** [comment]
@hammad2008 class names are in the Results objects that predict returns. The above docs show how to run prediction in Python so you can get Results and then handle them however you'd like to, i.e.

```python
results = model(source)

# do anything with 'results'
```
