### ISSUE TITLE
convert weights from .pt to .onnx

### ISSUE THREAD

**Issue by OptimusFaber** [ultralytics/yolov5#11247]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm using yolov5 6.1 and while working with the custom dataset i got the error.
The steps with train.py and detect.py best.pt works good. But when I start to convert weights into onnx file, I'm getting the error. 
And the most funny thing is that if I'm using the default coco dataset, everything is fine.

Here are my command which im using:
```python train.py --img 416 --batch 2 --epochs 30 --data ../dataset/data.yaml --weights yolov5s.pt --cfg models/custom_yolov5s.yaml && python export.py --weights runs/train/exp/weights/best.pt --include onnx --img 416 --data ../dataset/data.yaml && python detect.py --weights runs/train/exp/weights/best.onnx --source ../dataset/test/images/0b47311f426ff926578c9d738d683e76_jpg.rf.40183eae584a653181bbd795ba3c353f.jpg --data ../dataset/data.yaml```

And here is an errors which I'm getting:
![image](https://user-images.githubusercontent.com/72241649/227805345-465efd77-3453-4c0c-9244-a5aa7385b3c5.png)
It seems to me that he still thinks that there are 80 classes, how ever I changed it to my num of classes. I made an experiment - in each file (i think so) I changed 80 to 13 and tried it, but nothing happened. 

Than I tried different version (don't remember which on) and got this error :
![image](https://user-images.githubusercontent.com/72241649/227805738-ddbb3aa6-ac5e-4073-8d90-29eedd6648bd.png)

Looking ahead for some help)

**Comment by glenn-jocher** [comment]
@rodion02 hello! It seems like you're encountering issues converting custom YOLOv5 weights to ONNX format. The problem might be related to the number of classes in your custom dataset. Have you checked that the `nc` parameter in your `data.yaml` file matches the number of classes in your dataset? Also, could you confirm that your custom YOLOv5 config file matches the changes you made in `data.yaml`? Additionally, ensure that your model's architecture and hyperparameters are appropriate for your custom dataset.

You may find more detailed guidance on the YOLOv5 model conversion process in our [Ultralytics Docs](https://docs.ultralytics.com/yolov5/). If the issue persists, feel free to share additional details about your custom dataset and any modifications you made to the YOLOv5 codebase. We'll do our best to assist you further.
