### ISSUE TITLE
Interpreting training results

### ISSUE THREAD

**Issue by jgroll97** [ultralytics/yolov5#1125]
I started recently with the yolov5 training on custom data. But I am a little bit confused with the results I am receiving.  I do not know how to deal with the results or how to interpret them.  In the beginning the mAP values are great, but they drop during training. Could somebody please explain to me what is happening there, and how I can fix the issue?
I am very thankful for any advice I can get!
![results](https://user-images.githubusercontent.com/67149158/95755100-4400b900-0ca4-11eb-9e44-5350685db773.png)
![results](https://user-images.githubusercontent.com/67149158/95755124-4e22b780-0ca4-11eb-8fa1-6c5e9b24f916.png)

**Comment by glenn-jocher** [comment]
@jgroll97 there seems to be a disconnect between your train and val data. check your runs/exp/*.jpgs as recommended in the custom data tutorial: https://docs.ultralytics.com/yolov5/tutorials/train_custom_data

Also perhaps try 
python train.py --noautoanchor

**Comment by jgroll97** [comment]
@glenn-jocher Thank you for your quick help!

![test_batch0_pred](https://user-images.githubusercontent.com/67149158/95767368-ef196e80-0cb4-11eb-9e5c-927148bbb5ec.jpg)
![train_batch1](https://user-images.githubusercontent.com/67149158/95767383-f476b900-0cb4-11eb-99df-2483064a4d46.jpg)

I don't know if that helps: My training data are synthetic rendered images and Validation images are normal images. 
Would it make a difference if I use for validation synthetic images as well and test it later on normal images?

My goal is to evaluate how good synthetic training data can perform object detection. Due to that, I thought I would need the difference in validation- and trainings-set.

**Comment by glenn-jocher** [comment]
@jgroll97 if your validation and training images are completely different, then yes, you should expect completely different performance.

**Comment by dongjuns** [comment]
I have the same idea as glenn-jocher.
Just use only your rendered images for training and validation, and maybe it looks okay. But you don't need it.
We need to break the reality gap, and in my case, I used domain randomization with rendered images by Blender.
