### ISSUE TITLE
How to export the model as keras h5 file？

### ISSUE THREAD

**Issue by lebron8dong** [ultralytics/yolov5#11257]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

"""
TensorFlow, **Keras** and TFLite versions of YOLOv5
Authored by https://github.com/zldrobit in PR https://github.com/ultralytics/yolov5/pull/1127

Usage:
    $ python models/tf.py --weights yolov5s.pt

Export:
    $ python export.py --weights yolov5s.pt --include saved_model pb tflite tfjs
"""

There is no h5 file after I execute the command

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@lebron8dong to export the YOLOv5 model as a Keras h5 file, you can use the provided export script with the `--include keras` option. After executing the command, the h5 file should be generated accordingly.

For more details on model export, refer to the Ultralytics Docs at https://docs.ultralytics.com/yolov5/.

Let me know if you need further assistance!
