### ISSUE TITLE
Export a YOLOv5 PyTorch model to keras h5 format？

### ISSUE THREAD

**Issue by lebron8dong** [ultralytics/yolov5#11252]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Export a YOLOv5 PyTorch model to other formats. TensorFlow exports authored by https://github.com/zldrobit

Format                      | `export.py --include`         | Model
---                         | ---                           | ---
PyTorch                     | -                             | yolov5s.pt
TorchScript                 | `torchscript`                 | yolov5s.torchscript
ONNX                        | `onnx`                        | yolov5s.onnx
OpenVINO                    | `openvino`                    | yolov5s_openvino_model/
TensorRT                    | `engine`                      | yolov5s.engine
CoreML                      | `coreml`                      | yolov5s.mlmodel
TensorFlow SavedModel       | `saved_model`                 | yolov5s_saved_model/
TensorFlow GraphDef         | `pb`                          | yolov5s.pb
TensorFlow Lite             | `tflite`                      | yolov5s.tflite
TensorFlow Edge TPU         | `edgetpu`                     | yolov5s_edgetpu.tflite
TensorFlow.js               | `tfjs`                        | yolov5s_web_model/
PaddlePaddle                | `paddle`                      | yolov5s_paddle_model/

There is no format for keras.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by lebron8dong** [comment]
There are only pt, onnx, and tf formats in the tutorial, and there is no keras h5

**Comment by glenn-jocher** [comment]
@lebron8dong you are correct, there is currently no direct export to Keras h5 format in YOLOv5. If you'd like to help add this feature, your contribution would be greatly appreciated! You can find more information about contributing to YOLOv5 in the Ultralytics Docs. Thank you for your interest in improving the YOLOv5 project!
