### ISSUE TITLE
How to get output as(1,25200,85)?

### ISSUE THREAD

**Issue by Cats-eat-peppercorns** [ultralytics/yolov5#11260]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I see that many models output four, where the first one is the product sum of the remaining three, but the yolov5 model I trained outputs only the last three and not the combined one (1,25200,85), what can I do to get such four outputs? Is there an off-the-shelf model to get such output?

**Comment by osamasaeed** [comment]
HI, Have you found any solution?

**Comment by glenn-jocher** [comment]
Hi @osamasaeed-peppercorns, YOLOv5 generally outputs predictions in the format of `(x_center, y_center, width, height, confidence, class)`. I am not sure about the output format you mentioned, `(1,25200,85)`. It is possible that the output format you are expecting is specific to another object detection framework or model. 

However, if you are training the YOLOv5 model and want to change the output format, you can modify the model configuration file. Specifically, in the .yaml configuration file for your model, you can change the `nc` parameter to adjust the number of output classes, as well as the `anchors` list, to adjust the output bounding box coordinates.

If you have any further questions or concerns, please don't hesitate to ask.

**Comment by Cats-eat-peppercorns** [comment]
> 

oh yes,you can watch **https://blog.csdn.net/qq_69194611/article/details/129902114** this is my blog,but it is write in chinese,you can translate it ,i have solve it by using https://github.com/ultralytics/yolov5  to translate the moudle.

**Comment by glenn-jocher** [comment]
Hi @Cats-eat-peppercorns, thank you for reaching out to us. We're happy to hear that you were able to solve the issue you were having by using our YOLOv5 framework. 

Thank you for sharing your experience with other users in your blog post. While we don't have the ability to read Chinese, we're sure it will be helpful for those who can read it. 

If you have any more questions or concerns, please feel free to ask. We're always here to help.
