### ISSUE TITLE
rendered YoloV5 results lead to different picture

### ISSUE THREAD

**Issue by grumpyp** [ultralytics/yolov5#11265]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I basically trained a custom model to detect [peg-solitaire][1] games.

In my example I use the results of the detection to render a board with `matplotlib`

```
    def visualize_board(self, interpolated_board: List[List[float]] = None):
        pins = []
        nopins = []
        field = []
        
        if interpolated_board is not None:
            self.board = interpolated_board
        else:
            self.board = [row for row in open(self.board_representation, 'r').read().splitlines()]

        for row in self.sort_board_min_x(self.board):
            classes = row.split(' ')
            if classes[0] == '0':
                pins.append(classes[1:])
            elif classes[0] == '1':
                nopins.append(classes[1:])
            elif classes[0] == '2':
                field.append(classes[1:])
            else:
                raise Exception('Error in board class')
                exit(1)

        fig, ax = plt.subplots()

        # draw pins
        for pin in pins:
            x, y, w, h = [float(c) for c in pin]
            rect = plt.Rectangle((x, y), w, h, fill=False)
            ax.add_artist(rect)
        # draw nopins
        for nopin in nopins:
            x, y, w, h = [float(c) for c in nopin]
            rect = plt.Rectangle((x, y), w, h, fill=False, color='red')
            ax.add_artist(rect)

        # draw field
        if len(field) > 0:
            x, y, w, h = [float(c) for c in field[0]]
            rect = plt.Rectangle((x, y), w, h, fill=False, color='green')
            ax.add_artist(rect)


        ax.set_xlim([0, 2])
        ax.set_ylim([0, 2])

        plt.show()
```

Somehow the results look different then the predicted picture with the bounding-boxes. The pins are the interesting part for me and those two seem to be reflected to the top.

[![enter image description here][2]][2]
Can someone elaborate or see my error?

  [1]: https://en.wikipedia.org/wiki/Peg_solitaire
  [2]: https://i.stack.imgur.com/RLpLI.png

### Additional

I like the support of the maintainer directly on Github! Keep it going :)

**Comment by grumpyp** [comment]
Anyone?

**Comment by glenn-jocher** [comment]
@grumpyp, apologies for the delay, it looks like your `visualize_board()` function isn't quite matching the coordinate system of your `board_representation` file. Based on your bounding boxes, I would guess that your `matplotlib` plot's x axis is likely flipped horizontally. One way to fix this could be to set `ax.invert_xaxis()`. 

For example:

```
fig, ax = plt.subplots()

# draw pins
for pin in pins:
    x, y, w, h = [float(c) for c in pin]
    rect = plt.Rectangle((x, y), w, h, fill=False)
    ax.add_artist(rect)
# draw nopins
for nopin in nopins:
    x, y, w, h = [float(c) for c in nopin]
    rect = plt.Rectangle((x, y), w, h, fill=False, color='red')
    ax.add_artist(rect)

# draw field
if len(field) > 0:
    x, y, w, h = [float(c) for c in field[0]]
    rect = plt.Rectangle((x, y), w, h, fill=False, color='green')
    ax.add_artist(rect)

ax.set_xlim([0, 2])
ax.set_ylim([0, 2])
ax.invert_xaxis()  # Optional: flip x-axis

plt.show()
```

Please let me know if that resolves the issue or if you have any further questions.

**Comment by grumpyp** [comment]
Hi, unfortunatly it didn't solve the problem.

My new plot looks like this:

![image](https://user-images.githubusercontent.com/75830792/230719867-41ae4842-9c64-44c7-8a96-a92cb5ed2de2.png)

**Comment by glenn-jocher** [comment]
@grumpyp, apologies for the misunderstanding, and thank you for testing my suggestion. From the new image, it appears that there is a vertical flip as well as a horizontal flip. You can add `ax.invert_yaxis()` in addition to `ax.invert_xaxis()` to fix the vertical flip. 

For example:

```
fig, ax = plt.subplots()

# draw pins
for pin in pins:
    x, y, w, h = [float(c) for c in pin]
    rect = plt.Rectangle((x, y), w, h, fill=False)
    ax.add_artist(rect)
# draw nopins
for nopin in nopins:
    x, y, w, h = [float(c) for c in nopin]
    rect = plt.Rectangle((x, y), w, h, fill=False, color='red')
    ax.add_artist(rect)

# draw field
if len(field) > 0:
    x, y, w, h = [float(c) for c in field[0]]
    rect = plt.Rectangle((x, y), w, h, fill=False, color='green')
    ax.add_artist(rect)

ax.set_xlim([0, 2])
ax.set_ylim([0, 2])
ax.invert_xaxis()  # Optional: flip x-axis
ax.invert_yaxis()  # Optional: flip y-axis

plt.show()
```

Please let me know if that resolves the issue, or if you have any further questions.

**Comment by grumpyp** [comment]
Hey, I guess it would be only the flip of the y-axis. Thanks for your hints.
Now I am trying to understand the connection of the need of the flip and the raw outcome of the boxes themselves.
Do you have any idea or maybe a source to dig into?

Thanks and happy easter 🐇

**Comment by glenn-jocher** [comment]
@grumpyp, glad to hear the fix worked! As for why the vertical flip is needed, it may have to do with differences in the coordinate systems of your input image and Matplotlib's coordinate system. 

In computer vision, images often use a coordinate system where the origin (0, 0) is at the top-left corner, and the x axis increases to the right while the y axis increases downwards. However, in some plotting libraries like Matplotlib, the y axis increases upwards instead.

When you draw a rectangle using `(x, y)` as the bottom-left corner, Matplotlib may interpret it as placing the rectangle at the top-left corner instead (since the origin is at the top-left in its coordinate system). By flipping the y axis, you can match the coordinate system of your input image with that of Matplotlib, so the rectangles are displayed correctly.

I hope this explanation helps!

Happy Easter to you as well! 🐰

**Comment by grumpyp** [comment]
couldn't be better! thanks for that @glenn-jocher

**Comment by glenn-jocher** [comment]
You're welcome, @grumpyp! I'm glad I could help. If you have any further questions, don't hesitate to ask. Have a great day!
