### ISSUE TITLE
Why does the generated video have no sound？

### ISSUE THREAD

**Issue by lemon1022** [ultralytics/yolov5#11269]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I detected a video using yolov5-7.0, and the generated video has no sound.

**Comment by glenn-jocher** [comment]
When using YOLOv5 for object detection on videos, the output video typically doesn't contain audio. This is because the focus of YOLOv5 is on object detection in images, and audio processing is not included in the framework. However, you can easily add the audio from the original video to the generated video using external tools such as moviepy or FFmpeg.

Can you please provide more details about the software and tools you are using, as well as the steps you followed to generate the video?

**Comment by lemon1022** [comment]
> 

Thank you for your reply, I imported and run the project directly with pycharm, do you mean that I need to use other ways to synthesize the audio into the video?

**Comment by lemon1022** [comment]
> When using YOLOv5 for object detection on videos, the output video typically doesn't contain audio. This is because the focus of YOLOv5 is on object detection in images, and audio processing is not included in the framework. However, you can easily add the audio from the original video to the generated video using external tools such as moviepy or FFmpeg.
> 
> Can you please provide more details about the software and tools you are using, as well as the steps you followed to generate the video?

Thank you for your reply, I imported and run the project directly with pycharm, do you mean that I need to use other ways to synthesize the audio into the video?

**Comment by glenn-jocher** [comment]
@lemon1022 it depends on what you're trying to achieve. If you want to add audio to the video output of YOLOv5, you can use a video editing software like Adobe Premiere or Final Cut Pro to combine the YOLOv5 output video with an audio track. Alternatively, you can use a Python library like moviepy to programmatically add audio to the video output. Here's an example of how to add audio to a video using moviepy:

```python
import moviepy.editor as mp

video = mp.VideoFileClip("yolov5_output.mp4")
audio = mp.AudioFileClip("audio.wav")
final_clip = video.set_audio(audio)
final_clip.write_videofile("yolov5_output_with_audio.mp4")
```

I hope that helps! Let me know if you have any other questions.

**Comment by glenn-jocher** [comment]
@lemon1022 @lemon1022 yes, that's correct. YOLOv5 is primarily an object detection framework and does not include audio processing capabilities. To add audio to the output video, you would need to use external tools like `moviepy` or `FFmpeg`. 

I recommend using `moviepy`, a Python module for video editing. You can install `moviepy` using pip with the command `pip install moviepy`. After installing it, you would need to import `AudioFileClip` and `VideoFileClip` classes from the `moviepy.editor` module, like this:

```
from moviepy.editor import AudioFileClip, VideoFileClip
```

Then, you can use the `AudioFileClip` and `VideoFileClip` classes to load the original video and its audio track, and then use the `set_audio` method of the video clip object to add the audio track to the output video. Here's an example code snippet:

```
# Load original video and audio
video_clip = VideoFileClip('original.mp4')
audio_clip = AudioFileClip('original.mp4')

# Set audio of the video clip to the audio clip
video_clip = video_clip.set_audio(audio_clip)

# Write the output video with audio
video_clip.write_videofile('output_with_audio.mp4')
```

I hope this helps! Let me know if you have any other questions.

**Comment by lemon1022** [comment]
> 



> I hope that helps! Let me know if you have any other questions.

It helps, thanks!

**Comment by glenn-jocher** [comment]
@lemon1022 @lemon1022 you're welcome! If you have any other questions or concerns, please don't hesitate to ask. I am always happy to help.

**Comment by dandandan1983** [comment]
Hi. Is it possible to save audio in video without FFmpeg?
My input video has audio by default. After Yolo 8 it leaves audio. Is there any parameters to save audio? Thanks.

**Comment by glenn-jocher** [comment]
Hi there! 👋 Unfortunately, YOLOv5 does not natively support saving audio in the output video directly within its processing flow, as its main focus is on image and video frame analysis for object detection. Audio handling is not part of its functionality. Thus, there aren't any parameters within YOLOv5 to retain or manipulate audio tracks in videos.

To include audio in your output video after processing with YOLOv5, you'll need to use an external tool or library to merge the audio from your original video with the processed video. Libraries like `moviepy` can be very handy for this purpose:

```python
from moviepy.editor import VideoFileClip

original_video = VideoFileClip("input_video_with_audio.mp4")
processed_video = VideoFileClip("processed_video.mp4").set_audio(original_video.audio)
processed_video.write_videofile("final_output_with_audio.mp4")
```
This snippet takes the audio from your original video and adds it to your YOLOv5 processed video output, saving it as a new file.

I hope this helps! If you have more questions, feel free to ask.
