### ISSUE TITLE
Two targets combined to one by yolov5, which is not expected

### ISSUE THREAD

**Issue by universewill** [ultralytics/yolov5#1126]
Two targets animals combined to one by yolov5, which is not expected

**Comment by glenn-jocher** [comment]
larger model, larger image size, more training data, more epochs

**Comment by universewill** [comment]
> larger model, larger image size, more training data, more epochs

Is editing .yaml file enough to change into a larger model? @glenn-jocher

**Comment by glenn-jocher** [comment]
@universewill you can experiment with yaml modifications if you are an expert user, but the easiest is simply to select a larger model, up to yolov5x. If you specify --weights you don't need to specify a --cfg:

`python train.py --data custom.yaml --weights yolov5x.pt`
