### ISSUE TITLE
Using another file to open the camera and stream each frame into detect.py.

### ISSUE THREAD

**Issue by oakleychen0707** [ultralytics/yolov5#11267]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

我想寫一個名為“main.py”的Python檔案，負責開啟相機。titement.py捕獲從“main.py”傳入的“幀”變數，執行物件檢測，並將其顯示在螢幕上。

Here is my "main.py" code

`
import cv2
import detect2
import subprocess

cap = cv2.VideoCapture(0)

subprocess.call(["python3", "detect2.py"])

while True:

    ret, frame = cap.read()

  
    cv2.imshow('frame', frame)

    detect2.parse_opt(frame) 
    print("ok")

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()

cv2.destroyAllWindows()
`

I don't know how to modify in detect.py

**Comment by glenn-jocher** [comment]
@oakleychen0707 to achieve your goal, you can modify detect.py to create a function that takes a frame as input, performs object detection, and returns the processed frame with detections. Then, you can call this function in main.py to display the processed frame. First, create a new function in detect.py, and inside this function, perform object detection on the input frame. Next, make sure to import this new function in main.py and call it with the captured frame. Finally, display the returned processed frame with object detections using cv2.imshow.

**Comment by glenn-jocher** [comment]
@oakleychen0707 let me know if this answers your question!

**Comment by glenn-jocher** [comment]
@oakleychen0707 let me know if this answers your question!
