### ISSUE TITLE
select_device

### ISSUE THREAD

**Issue by d710055071** [ultralytics/yolov5#11268]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

   `
    detection_device            = select_device("1")

    det_model                   = get_detection_model("yolov5x_1280_c15_v1.pt",detection_device)
`
the mode run  in cuda:0,not cuda:1
this is bug?

**Comment by glenn-jocher** [comment]
@d710055071 hey there!

It looks like you may be encountering an issue with selecting the desired CUDA device. By default, `select_device` sets the device according to your CUDA visible devices environment variable or falls back to the first available CUDA device (cuda:0). You can ensure that the correct CUDA device is being used by setting the `CUDA_VISIBLE_DEVICES` environment variable before running your code.

If you need further assistance, feel free to check out the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/ for more detailed information on device selection and utilization.

Let me know if you need any more help!
