### ISSUE TITLE
abort segment error

### ISSUE THREAD

**Issue by ylc2580** [ultralytics/yolov5#11273]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hi,
run segment,and this error,can you help me.

AutoAnchor: 3.81 anchors/target, 1.000 Best Possible Recall (BPR). Current anchors are a good fit to dataset ✅
Plotting labels to runs/train-seg/exp10/labels.jpg...
Traceback (most recent call last):
  File "segment/train.py", line 658, in <module>
    main(opt)
  File "segment/train.py", line 554, in main
    train(opt.hyp, opt, device, callbacks)
  File "segment/train.py", line 254, in train
    compute_loss = ComputeLoss(model, overlap=overlap)  # init loss class
  File "/data/ylc/yolov5-v7.0/utils/segment/loss.py", line 40, in __init__
    self.nm = m.nm  # number of masks
  File "/root/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 778, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'Detect' object has no attribute 'nm'

**Comment by glenn-jocher** [comment]
@ylc2580 based on the error message you provided, it looks like there is no attribute "nm" in the "Detect" object of your model. Can you please check if you have defined this attribute in your model's code? It seems like this error is occurring when the "ComputeLoss" class is being initialized on line 254 of the "train.py" file. If you are still having trouble, please provide more information about your model's code or share your code and I can take a closer look.
