### ISSUE TITLE
How to add a new category to the model?

### ISSUE THREAD

**Issue by lemon1022** [ultralytics/yolov5#11275]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I used yolov5 to train a custom data set with two categories and got a model. Now I want this model to recognize a new category. I now have data of this category. How should I do it?

**Comment by glenn-jocher** [comment]
@lemon1022 to add a new category to an existing YOLOv5 model, you will need to perform a process called transfer learning. The basic idea is to take the pre-trained weights and fine-tune them on the new task. 
You will need to add the new category to the training data and update the number of categories accordingly in the model configuration file. 
Then, you can train the model using the updated data and configuration. You can also check out the documentation on transfer learning in YOLOv5 at docs.ultralytics.com for more information.

**Comment by lemon1022** [comment]
> @lemon1022 to add a new category to an existing YOLOv5 model, you will need to perform a process called transfer learning. The basic idea is to take the pre-trained weights and fine-tune them on the new task. You will need to add the new category to the training data and update the number of categories accordingly in the model configuration file. Then, you can train the model using the updated data and configuration. You can also check out the documentation on transfer learning in YOLOv5 at docs.ultralytics.com for more information.

I understand, thanks !

**Comment by glenn-jocher** [comment]
@lemon1022 you're welcome, happy to help! If you have any further questions or run into any issues, feel free to ask.
