### ISSUE TITLE
how to use the param '--single-cls = True' ?

### ISSUE THREAD

**Issue by ohjunee** [ultralytics/yolov5#11274]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm trying to learn yolov5 as a single class detection model that detects buildings, and I wonder if I could use the single_cls factor as 'True'. What happens with yolov5 when single_cls=True?

**Comment by glenn-jocher** [comment]
@ohjunee setting `single_cls=True` in YOLOv5 means that the model is trained on a single class detection task, where it tries to detect objects within a single class. So if you are trying to train the model to detect only buildings, then you should set `single_cls=True` during training. This will help the model to focus on detecting one class of objects without getting confused by others. Additionally, it will simplify the class prediction head and improve the detection accuracy.
