### ISSUE TITLE
AttributeError: module 'cv2' has no attribute 'CAP_PROP_ORIENTATION_META'

### ISSUE THREAD

**Issue by bryanbocao** [ultralytics/yolov5#11272]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

detect.py

### Environment

python3 -c 'import torch; print(torch.__version__)'
1.9.0+cu111

nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89

python3 -c 'import cv2; print(cv2.__version__)'
3.2.0

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by bryanbocao** [comment]
Solved by
```
pip install opencv-python==4.5.1.48
```

https://stackoverflow.com/questions/64682485/attributeerror-module-cv2-cv2-has-no-attribute-cap-prop-orientation-meta

https://github.com/opencv/opencv-python/issues/441

**Comment by glenn-jocher** [comment]
@bryanbocao glad to hear that you were able to solve the problem. It looks like the issue was related to the version of OpenCV you had installed. If you come across any other issues, please don't hesitate to ask. Thanks for using YOLOv5!

**Comment by bryanbocao** [comment]
@glenn-jocher Thanks for your help! I do have another issue https://github.com/ultralytics/yolov5/issues/10998 regarding the shape of input if you have time :)

**Comment by glenn-jocher** [comment]
@bryanbocao You're welcome! Regarding your new issue, it looks like you have a problem with the input shape of your images. 

Please ensure that all of your images have the same dimensions, i.e., width and height, and that they are of the same shape as specified in the `--img-size` argument.

If that doesn't solve the issue, please provide more information about your error message and the shape of your image inputs.

**Comment by bryanbocao** [comment]
@glenn-jocher The script can run successfully without any issues. It's mainly about whether ```--img``` doesn't actually change the direct input of yolov5 model which looks to be fixed at ```640x640```.

**Comment by glenn-jocher** [comment]
@bryanbocao Got it! The `--img` argument is used for inference resizing and visualization, and it doesn't directly affect the input size of the YOLOv5 model during training or inference. 

If you need to change the input size of the YOLOv5 model, you should modify the model architecture directly or retrain the model with a different input size. 

For further details, please refer to the [Ultralytics Docs](https://docs.ultralytics.com/yolov5/). If you have any more questions, feel free to ask!
