### ISSUE TITLE
ClearML logging does not work at multi-gpu training

### ISSUE THREAD

**Issue by nameCDI** [ultralytics/yolov5#11278]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

ClearML works well with `python segment/python.py --weights ...`, 
but it doesn’t show up at all with 
`python -m torch.distributed.run --nproc_per_node 2 segment/train.py --weights --device 0, 1 ...`

![image](https://user-images.githubusercontent.com/128284613/228958035-21a63a4b-cfbc-4aa7-becb-6398d686b6a5.png)

Is it normal for comet or clear info not to be displayed in this script?

**Comment by glenn-jocher** [comment]
Hi @NameCDI! It should still be possible to use Comet (or Clear) with `train.py` when run with `torch.distributed.run`. Instead of calling `comet_ml.Experiment()`, you will need to start the experiment with `comet_ml.init()` first. Then, you can pass your Comet API key and the experiment name to `train.py` using the `--name` command line argument in the same way as `--weights`. For example:
```
python -m torch.distributed.run --nproc_per_node 2 segment/train.py --weights --name YOUR_EXPERIMENT_NAME --device 0, 1 ...
```
Please let me know if this works for you.

**Comment by nameCDI** [comment]
@glenn-jocher 
`python train.py --weights yolov5n.pt --device 0 --project t2 --name t2 --epochs 3`
![image](https://user-images.githubusercontent.com/128284613/228970548-0f0d2ea4-1113-473d-9c3b-442efbf4f7cd.png)

`python segment/train.py --weights yolov5n-seg.pt --project t1 --name t1 --device 0 --epochs 3`
![image](https://user-images.githubusercontent.com/128284613/228970619-d3e6f20d-e2ac-4018-8fa8-868e5f13262b.png)


I created a new virtual environment, installed it, and ran it without modifying any code. 
'train.py' works well with comet and clearml, 
but the script is omitted in 'segment/train.py'.
It’s really strange. I don’t know why.

**Comment by nameCDI** [comment]
@glenn-jocher 

![ 2023-03-31 065222](https://user-images.githubusercontent.com/128284613/228973198-ffb2a067-e8a4-4559-a1b5-6f6617a6307e.png)

![image](https://user-images.githubusercontent.com/128284613/228972711-6f2e8e19-8929-4031-bc77-61287ac88cb5.png)

And it’s the same in my other environment. train.py works well and segment/train.py doesn’t. I also checked with my app.clear.ml

**Comment by glenn-jocher** [comment]
@NameCDI Based on the error message you shared, it appears that the `comet_ml` package is missing or not installed in your environment. To resolve this error, you should try running `pip install comet_ml` in your terminal to install Comet. Alternatively, if you are using ClearML, try running `pip install clearml` to install the required package. 

If you have already installed `comet_ml` or `clearml`, try running `pip show comet_ml` or `pip show clearml` to check the installation path and to make sure it has really been installed. 

Let me know if this resolves your issue.

**Comment by nameCDI** [comment]
@glenn-jocher 
Actually, when this strange thing happened, while debugging, I added
` from clearml import Task` 
`task = Task.init(project_name="my project", task_name="my task")`
to segment/train.py and a clearml script was created and the project was created. 
But when I called clearml, two experiments were created in my app.clear.ml and one became a zombie state. 

In my environment's capture image with a black background, not a white background, clearml logging seems to work normally, so it seems that there is a problem with the segment/train.py file. 

Of course, I will try as soon as possible as you said.

**Comment by glenn-jocher** [comment]
@NameCDI It's possible that the creation of two experiments in ClearML is due to the `Task.init()` method being called twice, which could cause multiple experiments to be created. Regarding the black background in your environment, that could be due to your terminal emulator or a configuration issue. 

In any case, please try installing Comet or ClearML via pip as I suggested and make sure the package is installed correctly. Then, follow the steps I outlined previously in order to integrate the package into `segment/train.py`. If you continue to experience issues, please feel free to share more information or code snippets so I can assist you further.

**Comment by nameCDI** [comment]
@glenn-jocher 

`pip show clearml`

Name: clearml
Version: 1.9.0
Summary: ClearML - Auto-Magical Experiment Manager, Version Control, and MLOps for AI
Home-page: https://github.com/allegroai/clearml
Author: ClearML
Author-email: support@clear.ml
License: Apache License 2.0
Location: /home/mgt/anaconda3/envs/cdi_v5/lib/python3.10/site-packages
Requires: attrs, furl, jsonschema, numpy, pathlib2, Pillow, psutil, pyjwt, pyparsing, python-dateutil, PyYAML, requests, six, urllib3
Required-by: 

**clearml package check Complete**

`clearml-iniit`

ClearML SDK setup process
Configuration file already exists: /home/mgt/clearml.conf
Leaving setup, feel free to edit the configuration file.

**clearml-init && api register check Complete**

My yolo project folder route ' /home/mgt/YOLOV5' 

I have checked everything you mentioned, and 'python train.py' works fine with ClearML, and the script appears. 
However, when I run 'python segment/train.py', neither ClearML's nor Comet's script is visible, and the script doesn't run either.
 Can you tell me where ClearML's logger is called exactly? 
I'm trying to add the suggested code directly from ClearML

```
from clearml import Task
task = Task.init(project_name="my project", task_name="my task")
```

**Comment by glenn-jocher** [comment]
@nameCDI The `Task.init()` call should be added at the beginning of your script, before any other operations, to initialize the ClearML task. By adding these lines at the start of `segment/train.py`, you can ensure that the task is properly initialized and that the metrics are logged correctly throughout the execution of the script. If the script still does not log to ClearML after adding these lines, it is possible that there may be other issues within the `segment/train.py` file that are preventing the ClearML logging from functioning properly. I would recommend carefully reviewing the ClearML integration guidelines and ensuring that the integration is properly set up within the `segment/train.py` script.

Let me know if adding the `Task.init()` call resolves the issue, or if you encounter any further difficulties.
