### ISSUE TITLE
RuntimeError: xnnpack::convolution not available! Reason: The provided (weight, bias, padding, stride, dilation, groups, transposed, output_min, output_max) parameters are either invalid individually or their combination is not supported by XNNPACK.

### ISSUE THREAD

**Issue by KennyTC** [ultralytics/yolov5#11270]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

RuntimeError: xnnpack::convolution not available! Reason: The provided (weight, bias, padding, stride, dilation, groups, transposed, output_min, output_max) parameters are either invalid individually or their combination is not supported by XNNPACK.

### Environment

- YOLO v5
- Ubuntu 20.04
- Pytorch 2.0
- Cuda 11.7

### Minimal Reproducible Example

- train model
- export models to torchscript 
`python export.py --weights runs/train/exp/best.pt --include torchscript --img 640 --optimize`
- Run detect on torchscript model
` python detect.py --weights runs/train/exp/best.torchscript --source /images/`

The error was
```
detect: weights=['runs/train/exp/best.torchscript'], source=/home/kenny/labelme_json_dir/YOLODataset_labelimg/images/, data=data/coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
YOLOv5 🚀 v7.0-120-g3e55763 Python-3.8.12 torch-2.0.0+cu117 CUDA:0 (NVIDIA GeForce GTX 1080 Ti, 11175MiB)

Loading runs/train/exp/best.torchscript for TorchScript inference...
Traceback (most recent call last):
  File "detect.py", line 261, in <module>
    main(opt)
  File "detect.py", line 256, in main
    run(**vars(opt))
  File "/home/kenny/.local/share/virtualenvs/yolov5-R3Lurzqu/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 98, in run
    model = DetectMultiBackend(weights, device=device, dnn=dnn, data=data, fp16=half)
  File "/home/kenny/StudioProjects/yolov5/models/common.py", line 352, in __init__
    model = torch.jit.load(w, _extra_files=extra_files, map_location=device)
  File "/home/kenny/.local/share/virtualenvs/yolov5-R3Lurzqu/lib/python3.8/site-packages/torch/jit/_serialization.py", line 162, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files, _restore_shapes)  # type: ignore[call-arg]
RuntimeError: xnnpack::convolution not available! Reason: The provided (weight, bias, padding, stride, dilation, groups, transposed, output_min, output_max) parameters are either invalid individually or their combination is not supported by XNNPACK.
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@KennyTC it seems you are encountering an issue with PyTorch's XNNPACK backend when loading the TorchScript model. The error might be due to an unsupported combination of parameters for the convolution operation in the XNNPACK backend.

To address this issue, you can try disabling XNNPACK when exporting the model. Modify export.py and add torch.backends.xnnpack.enabled = False at the beginning of the script:

```python
import torch
torch.backends.xnnpack.enabled = False
# ... rest of the code
```

This will disable XNNPACK when running the export script. After doing this, export the model again and try running detect.py with the new TorchScript model.

Note that disabling XNNPACK might affect the performance of the model on mobile devices or low-power hardware, so only do this if the first approach doesn't work.

**Comment by KennyTC** [comment]
thanks for your quick reply. Unfortunately, it did not work. It said that 
`'torch' has no attribute 'backends'`. Are you mentioning about the older version of pytorch?

**Comment by glenn-jocher** [comment]
@KennyTC i apologize for the confusion. It appears the `torch.backends` attribute was removed starting from PyTorch version 1.9.0. In that case, you can try setting the environment variable `TORCH_XNNPACK_DISABLE=1` before running `detect.py` like this:

```bash
TORCH_XNNPACK_DISABLE=1 python detect.py --weights runs/train/exp/best.torchscript -- source /images/
```

This should also disable the XNNPACK backend when running the inference script. Let me know if this helps!
