### ISSUE TITLE
Changes in GFLOPS

### ISSUE THREAD

**Issue by wangtao0219** [ultralytics/yolov5#11284]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Last year I trained v6.0 of yolov5n and it showed 4.5GFLOPS at that time, which is also the value shown on github.
Why now when I retrain this project, it shows 4.6GFLOPS, can you tell me what's wrong?

**Comment by wangtao0219** [comment]
This has no effect on training, but I'm just too confused and still want to know what caused it, since my code, configuration environment, and dataset have not changed.

**Comment by glenn-jocher** [comment]
@wangtao0219 architecture changes in different major releases
