### ISSUE TITLE
How to interpret model.yaml (eg. yolov5s.yaml)

### ISSUE THREAD

**Issue by lokeshfallen** [ultralytics/yolov5#11282]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When I was going through the backbone architecture yaml file i.e. yolov5s.yaml I can across - 

[[-1, 1, Conv, [64, 6, 2, 2],
 [-1, 1, Conv, [128, 3,2]],
  …
]

I understood that the layer are in the form - [from, number of module, Module name, Module arguments]

But I could interpret the model arguments i.e. [64, 3, 2, 2] and [128, 3, 2].

What is the meaning of each argument and is there any relation between them since they are consecutive. If yes what is the relation they hold ?

Thank You

**Comment by supriamir** [comment]
@lokeshfallen 
[64, 3, 2, 2] and [128, 3, 2]
64 -> output channel
3 -> kernel size
2 -> stride
2 -> padding

 [128, 3, 2]
128 -> output channel
3 -> kernel size
2 -> stride
with zero padding

**Comment by glenn-jocher** [comment]
@supriamir, to expand on the answer provided by @glennjocher, the meaning of each argument in the YAML file is as follows:

- The first argument is the number of output channels of the convolutional layer. 
- The second argument is the kernel size (i.e., the spatial dimension of the filters to be convolved over the input data).
- The third argument is the stride (i.e., the number of pixels the convolutional kernel is slid on the input feature map).
- The fourth argument is the padding size.

For example, the notation [64, 3, 2, 2] indicates that the layer has 64 output channels, a kernel size of 3x3, a stride of 2, and a padding of 2. The notation [128, 3, 2] indicates that the layer has 128 output channels, a kernel size of 3x3, a stride of 2, and zero padding. I hope this helps clarify!
