### ISSUE TITLE
怎么使用

### ISSUE THREAD

**Issue by HappyJayLiu** [ultralytics/yolov5#11298]
请问怎么使用啊

**Comment by glenn-jocher** [comment]
为了更好地帮助您，请提供一些关于您希望了解的问题的详细信息。如果您是在询问如何使用 YOLOv5 进行训练和测试，请参考以下简要指南：

克隆 YOLOv5 仓库：

```
git clone https://github.com/ultralytics/yolov5.git
cd yolov5
```
安装依赖：

`pip install -r requirements.txt`
准备数据集：您需要一个带有图像和相应标签的数据集。YOLOv5 期望数据集的格式类似于 COCO 数据集，具体可以查看这个链接：https://docs.ultralytics.com/yolov5/tutorials/train_custom_data
创建或修改 YAML 文件：您需要一个描述数据集、类别及其数量的 YAML 文件。可以参考 YOLOv5 仓库中的示例文件。确保您的 YAML 文件正确指向训练和验证图像的目录。
