### ISSUE TITLE
Can we add non-max-suppression as a layer in the model

### ISSUE THREAD

**Issue by sourabhburnwal** [ultralytics/yolov5#11296]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

In my experiments, nms is taking significant amount of time (~80% of preprocess+postprocess time). Is it possible to add non-max-suppression operations as layers in the model itself? Since I use TensorRT model, it will save a lot of time in inference. Does anyone have any resources/ref for the same?

Thanks!

**Comment by glenn-jocher** [comment]
Hi! Thank you for sharing this query with us.

We believe adding non-maximum suppression (NMS) to the model itself won't be a good idea, as the primary purpose of NMS is to remove duplicates in overlapping bounding boxes of already detected class instances per frame, and this is usually done in postprocessing. Placing it inside the model would mean setting a fixed threshold that is likely to vary between frames and scenarios, thus risking reduced accuracy.

Instead, it might be helpful to explore other optimization techniques to help speed up your inference time, such as TensorRT's dynamic tensor memory allocation or CUDA's hybridization. You can refer to [TensorRT's optimization guide](https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-720/developer-guide/index.html#optimization) for more information and other optimization tips.
