### ISSUE TITLE
Can I change the label's name in videos after the time has passed?

### ISSUE THREAD

**Issue by Howard18474** [ultralytics/yolov5#11301]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have a problem on observing stationary things, if one object is OK when it show for a short while, but not good for long time, how can I change the code to solve the problem?

For example, an object shows for one second, the label will show "save" on it, but after one hour, it's still right there, than change the label to "danger", how can I do to accomplish this?

**Comment by glenn-jocher** [comment]
@Howard18474 to address this issue, you can consider implementing object tracking to track the object's movement over time. This can be achieved using deep learning-based trackers like CentroidTracker or KalmanFilterTracker. By tracking the object, you can determine whether the object has moved or not and update the label accordingly. 

I hope this helps! Let me know if you have any other questions or concerns.
