### ISSUE TITLE
Running Yolov5 on Specified Region of Interest

### ISSUE THREAD

**Issue by Jeetkarsh** [ultralytics/yolov5#1131]
How can we use Yolov5 to run on a specific User selected area of interest?

**Comment by glenn-jocher** [comment]
@Jeetkarsh you can crop images with cv2 or PIL, or even numpy, but none those operations are really related to YOLOv5.

The only constraint on inputs is that they must be multiples of the largest model stride, 32.

**Comment by Jeetkarsh** [comment]
Thank Glenn, In Yolov5 do we have a functionality to run multiple detectors in a different area of interest at the same time?

Don't want to run yolov5 on my entire image.

**Comment by glenn-jocher** [comment]
@Jeetkarsh again this is fully up to you, you supply whatever pixels you want for inference.

**Comment by DeepDGojariya** [comment]
@glenn-jocher  where I have to make changes if I need to pass a cropped image or pre-defined ROI?

**Comment by ysfmani** [comment]
@DeepDGojariya  hello my friend did you found out how to select a ROI ?

**Comment by DeepDGojariya** [comment]
> @DeepDGojariya hello my friend did you found out how to select a ROI ?

Yes actually I found out how to do it when I am using yolov5 with Deep-sort tracking.
In the track.py file you need to make changes.
There are majorly 2 changes you need to make.
First is to draw an ROI using openCV and 
second is to write a range of that ROI while detecting.
You can refer my code at : [https://we.tl/t-a4FmGWVGBi]

**Comment by ysfmani** [comment]
@DeepDGojariya  Thank you very much please if you dont mind can you give me your project repo or mean of communication to ask you some things if you have time .

**Comment by DeepDGojariya** [comment]
Actually it was an internship project so I cannot give you the repo. But we can surely have a discussion about it on Google meet today evening.

**Comment by DeepDGojariya** [comment]
> @DeepDGojariya Thank you very much please if you dont mind can you give me your project repo or mean of communication to ask you some things if you have time .

Actually it was an internship project so I cannot give you the repo. But we can surely have a discussion about it on Google meet today evening.

**Comment by ysfmani** [comment]
@DeepDGojariya  add me discord Youssef Mani#5403

**Comment by gericoaron** [comment]
@DeepDGojariya Bro I had the same problem How can I draw and apply ROI

**Comment by jettang** [comment]
> 

hello, @DeepDGojariya would you please paste the code here, the file already expires from [https://we.tl/t-a4FmGWVGBi].

**Comment by DeepDGojariya** [comment]
Actually the code currently is with my internship company and I'm not
allowed to share it.

**Comment by jettang** [comment]
> 

oh, ok. thank you all the same. :)
