### ISSUE TITLE
Training procedure

### ISSUE THREAD

**Issue by ShAmoNiA** [ultralytics/yolov5#11319]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi guys,
I encountered an annoying issue while running some code in the "evolve" section of my train.py script. Here's the relevant code snippet:
```
for _ in range(opt.evolve):
    #Some Code
    results = train(hyp.copy(), opt, device, callbacks)
    callbacks = Callbacks()
    #Some Code
```
During training, it's important to update the "callbacks" value each time we want to train again. Without updating it, our training procedure gets stuck in the third training iteration, resulting in repeated plotting of labels.
```
Plotting labels to runs/evolve/exp11/labels.jpg... 
Plotting labels to runs/evolve/exp11/labels.jpg... 
Plotting labels to runs/evolve/exp11/labels.jpg... 
```
I tried to solve this problem by modifying the code as follows:
```
random_function(hyp, opt, device, callbacks):
    results = train(hyp.copy(), opt, device, callbacks)
    callbacks = Callbacks()
    return callbacks 

for _ in range(opt.evolve):
    #Some Code
    callbacks = random_function(hyp.copy(), opt, device, callbacks)
    #Some Code
```
In the modified code, I created a new function "random_function" that calls the "train" function with updated "callbacks" each time it is run. However, I still encountered the same error as before, even though I verified that the "callbacks" value was changing each time I ran the function.

Could you please suggest a solution to this problem using more advanced vocabulary?

How should I fix it?

**Comment by glenn-jocher** [comment]
@ShAmoNiA based on the information provided, it appears that the issue might be related to the use of the Callbacks() function, and possibly its interaction with the train() function. Without access to the full code, it's difficult to provide an accurate solution to the problem. However, I recommend checking the documentation for Callbacks() to see if there are any specific guidelines for its usage, and also reviewing the implementation of the train() function to ensure that it is properly handling the Callbacks() object. Additionally, you may want to consider posting a more detailed question on the YOLOv5 GitHub Issues page, including the full code and error message, to see if the Ultralytics team or other community members can provide further assistance.
