### ISSUE TITLE
How to run Yolo5 TF Saved_model without using torch library ?

### ISSUE THREAD

**Issue by MustafaAlahmid** [ultralytics/yolov5#11315]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have trained a Yolo5 model and then i have converted it to tf saved_model format 
I m trying to run the model  on tensorflow using this [Tutorial](https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/auto_examples/plot_object_detection_saved_model.html) but it doesn't work and 
I have kept the shape and d-type similar but still getting this error
signture error

> shape=(640, 640, 3), dtype=float32))
  input_signature: (
    TensorSpec(shape=(1, 640, 640, 3), dtype=tf.float32, name=None)).

what is the wrong here ?

**Comment by glenn-jocher** [comment]
Hi @Firas-Ali, it sounds like there may be an issue with the input signature of your saved model.  The input signature for `yolov5s.tflite` should be `(1, 3, 640, 640)` and `(1, 640, 640, 3)` for the TensorFlow version.  In addition, you can try loading the saved model directly in TensorFlow using `tf.saved_model.load` and check the input signatures by running `print(model.signatures['serving_default'])`. 

If you continue to have issues, please provide additional details about how you converted your YOLOv5 model to the TFLite and TensorFlow formats, and the exact error message you are seeing. Thanks!

**Comment by wpNZC** [comment]
try image_data = torch.unsqueeze(image_data, dim=0)

**Comment by glenn-jocher** [comment]
@wpNZC hi there! 👋

To create a batch dimension in your input tensor, you can use `torch.unsqueeze` function like this:

```python
image_data = torch.unsqueeze(image_data, dim=0)
```

This will add a batch dimension to your `image_data` tensor.

Let me know if you have any further questions. Happy coding!

**Comment by Glatzen95** [comment]
Hello @glenn-jocher 

i have the same issue here.

This is how i export my model: 
`
python export.py --weights best.pt --include saved_model --img 1280
`

Now i want to make inference on my image:

`
import torch

image_path = "test.png"

model = torch.hub.load("ultralytics/yolov5", "custom", "best_saved_model")

results = model(image_path)
`

But i get the same error like the issueopener

`
File "F:\\test.py", line 9, in <module>
   results = model(image_path)
File "F:\python310\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\python310\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\.../.cache\torch\hub\ultralytics_yolov5_master\models\common.py", line 717, in forward
    y = self.model(x, augment=augment)  # forward
  File "F:\python310\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\.../.cache\torch\hub\ultralytics_yolov5_master\models\common.py", line 574, in forward
    y = self.model(im, training=False) if self.keras else self.model(im)
  File "F:\python310\lib\site-packages\tensorflow\python\saved_model\load.py", line 704, in _call_attribute
    return instance.__call__(*args, **kwargs)
  File "F:\python310\lib\site-packages\tensorflow\python\util\traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "F:\python310\lib\site-packages\tensorflow\python\eager\function_spec.py", line 531, in _convert_inputs_to_signature
    raise ValueError("Python inputs incompatible with input_signature:\n"
ValueError: Python inputs incompatible with input_signature:
  inputs: (
    [[[[    0.44706     0.44706     0.44706]
   [    0.44706     0.44706     0.44706]
   [    0.44706     0.44706     0.44706]
   ... 
input_signature: (
TensorSpec(shape=(1, 1280, 1280, 3), dtype=tf.float32, name=None)).
`

Can you tell me what is wrong here?
