### ISSUE TITLE
yolov5-7.0 train.py error

### ISSUE THREAD

**Issue by tuzi-maker** [ultralytics/yolov5#11327]
I want to run yolov5-7.0 demo "python train.py --data coco.yaml --epochs 300 --weights '' --cfg yolov5n.yaml  --batch-size 128 " and I get the following error:SHA could not be resolved, git returned:b'',but 5.0 normal operation.

configuration environment 
ubuntu:22.04
python:3.10
pytorch:1.13+cu117
GitPython:3.1.31

**Comment by glenn-jocher** [comment]
@tuzi-maker based on the error message you've provided, it looks like GitPython is unable to resolve the SHA of a Git commit that the YOLOv5 repository depends on. 

To fix this issue, try running the following command to update the Git submodules of the YOLOv5 repository: 

```
git submodule update --init --recursive
```

This should ensure that all the necessary Git submodules are correctly initialized and up-to-date. After that, you can try running your YOLOv5 demo again. 

If you're still having issues, try cloning the YOLOv5 repository again and repeating the `git submodule update` command. Additionally, make sure that you have the latest version of Git installed on your system.

**Comment by tuzi-maker** [comment]
> @tuzi-maker根据您提供的错误消息，GitPython 似乎无法解析 YOLOv5 存储库所依赖的 Git 提交的 SHA。
> 
> 要解决此问题，请尝试运行以下命令来更新 YOLOv5 存储库的 Git 子模块：
> 
> ```
> git submodule update --init --recursive
> ```
> 
> 这应该确保所有必要的 Git 子模块都正确初始化并保持最新。之后，您可以尝试再次运行您的 YOLOv5 演示。
> 
> 如果仍有问题，请尝试再次克隆 YOLOv5 存储库并重复该`git submodule update`命令。此外，请确保您的系统上安装了最新版本的 Git。

That's it. Thank you very much. Have a nice day!

**Comment by tuzi-maker** [comment]
That's it. Thank you very much. Have a nice day!

**Comment by glenn-jocher** [comment]
You're welcome, @tuzi-maker! I'm glad I could help. If you have any more questions or run into any more issues with YOLOv5, don't hesitate to ask. Have a great day!
