### ISSUE TITLE
ONNX opset version 9 is not supported

### ISSUE THREAD

**Issue by chacoff** [ultralytics/yolov5#11329]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I keep getting an error while exporting to onnx: opset version is not supported. I tried with the default 17, and other values, but nothing will do it

```
export: data=00_Datasets/seams.yaml, weights=runs\train\exp2\weights\best.pt, imgsz=[640, 640], batch_size=1, device=cpu, half=False, inplace=False, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=17, verbose=False, workspace=4, nms=False, agnostic_nms=False, topk_per_class=100, topk_all=100, iou_thres=0.15, conf_thres=0.15, include=['onnx']
YOLOv5  v7.0-140-g1db9533 Python-3.7.9 torch-1.7.0 CPU

Fusing layers... 
Model summary: 157 layers, 1761871 parameters, 0 gradients, 4.1 GFLOPs

PyTorch: starting from D:\Projects\201_SeamsModel_v2\runs\train\exp2\weights\best.pt with output shape (1, 25200, 7) (3.7 MB)

ONNX: starting export with onnx 1.13.1...
ONNX: export failure  0.1s: Unsupported ONNX opset version: 17

Process finished with exit code 0
```

i appreciate any advice

**Comment by glenn-jocher** [comment]
@chacoff, it looks like you are trying to export the YOLOv5 PyTorch model to ONNX format with an unsupported opset version. The error message `"Unsupported ONNX opset version: 17"` indicates that the `17` version is not supported for the ONNX target platform. 

You can try using a supported version by checking your ONNX and PyTorch versions against their supported opset versions e.g. ONNX version `1.7.0` supports opset versions up to `13`. You could also try specifying a lower opset version as follows `--opset-version <opset_version>`.

For more help with ONNX, please refer to the official ONNX documentation https://github.com/onnx/onnx.

**Comment by chacoff** [comment]
> 

UPDATE:
i found the issue:, i just updated pytorch to 1.13.1 and worked perfectly.
thanks!

------------------
_thank you very much for your answer!, i appreciate it.
As a matter of fact, i tried all opsets from 1 to 17, sometimes the error is this one:

```
ONNX: starting export with onnx 1.13.1...
ONNX: export failure  0.5s: Exporting the operator silu to ONNX opset version 12 is not supported. Please open a bug to request ONNX export support for the missing operator.
```

i am using onnx 1.13.1, onnxruntime 1.14.1 and torch 1.7.0 (cuda 10.2). 
I am exporting a nano model in cpu

thank you in advance!
J._

**Comment by glenn-jocher** [comment]
@chacoff, glad to hear your issue is resolved! If you have additional questions or issues, don't hesitate to ask. We're here to help!
