### ISSUE TITLE
Inference with mps | torch 2.1.0

### ISSUE THREAD

**Issue by DP1701** [ultralytics/yolov5#11320]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

@glenn-jocher
Hi, have you tried the new nighlty build from pytorch for inference with mps?

Inference with torch 2.0.0, torchvision 0.15.1

<img width="1282" alt="2" src="https://user-images.githubusercontent.com/68444979/230744703-0583fdef-9ced-49f8-8ecf-76e8b18e889f.png">

It just didn't work with a custom yolov5m detector

Inference with torch 2.1.0.dev20230408, torchvision 0.16.0.dev20230408
<img width="1210" alt=" 1" src="https://user-images.githubusercontent.com/68444979/230744707-8568be2c-0d5f-484a-873f-f11c63e89d9d.png">

But now yes. At first glance, the detection fields seem to be all correct for me as well.

**Comment by glenn-jocher** [comment]
@DP1701 hi there! We have not yet tested the new nightly build from PyTorch for inference with MPS. However, we'll take note of your findings and consider it for testing in the future. Thank you for sharing your experience! If you have any further questions or issues with Ultralytics YOLOv5, don't hesitate to ask. You might also find additional information in our YOLOv5 documentation at https://docs.ultralytics.com/yolov5/.
