### ISSUE TITLE
Help regarding dataset

### ISSUE THREAD

**Issue by devendraswamy** [ultralytics/yolov5#11335]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi , I am unable to collect the damaged traffic sign dataset from opensource , could anyone please share the damaged traffic sign dataset links or files here. sorry I know this is not relevant question to yolov5 but I need some help , so please share the information here   , Thanking you in advance.

**Comment by glenn-jocher** [comment]
@devendraswamy hello, I understand that you are looking for a dataset of damaged traffic signs. Although this request is not directly related to YOLOv5, I can suggest a few places where you can search for such datasets. 

- One of the sources you could try is the [German Traffic Sign Recognition Benchmark](http://benchmark.ini.rub.de/?section=gtsrb&subsection=news). They have a large dataset of traffic signs, and they might have some images of damaged traffic signs. 
- Alternatively, you could search for publicly available datasets on platforms like [Kaggle](https://www.kaggle.com/), [UCI Machine Learning Repository](https://archive.ics.uci.edu/ml/index.php), or [ImageNet](http://www.image-net.org/). 

I hope this helps. If you have any further questions related to YOLOv5, please feel free to ask.

**Comment by devendraswamy** [comment]
Thank you @glenn-jocher  , I tried with kaggle and UCI ,ImageNet but unable to find the damaged traffic sign images , if you any other alternate to get the dataset please share here. Thanking you in advance.

**Comment by glenn-jocher** [comment]
@devendraswamy I'm sorry to hear that your search didn't yield any results. One other option you could try is to create your own dataset. Here are a few ideas on how you could do that:

- Visit a local area with damaged traffic signs and take pictures of them.
- Contact the city or municipality you live in and ask if they have any damaged traffic signs you can take pictures of.
- Scour social media, news articles, or accident reports for pictures of damaged traffic signs.

Creating your own dataset might take some time and effort, but it can also be a great learning experience. If you have any other questions, please let me know.

**Comment by devendraswamy** [comment]
Thank you for your support@glenn-jocher  , I will try to create my own dataset  and working on training the model on it, in future if i have any queries i will ping you.

**Comment by glenn-jocher** [comment]
@devendraswamy you're welcome! I'm glad that I could be of help. Good luck with creating your dataset and training your model. If you have any further questions in the future, don't hesitate to reach out to me. Have a great day!
