### ISSUE TITLE
Convert YOLO segmentation format to bbox

### ISSUE THREAD

**Issue by sarmientoj24** [ultralytics/yolov5#11337]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is there a builtin function in the repo, or suggested code how to do this?

**Comment by glenn-jocher** [comment]
@sarmientoj24 it would be helpful if you could provide more context about what you are trying to accomplish so that I can provide a more specific answer. However, there are many built-in functions in the YOLOv5 repository for various tasks such as detection, training, and testing. You can find more information about these functions, as well as example code, in the official YOLOv5 documentation at https://docs.ultralytics.com/yolov5.

**Comment by sarmientoj24** [comment]
@glenn-jocher Thank you.
I am referring to converting this segmentation format
```
2 0.207031 0.558594 0.208984 0.527344 0.210938 0.488281 0.214844 0.445312 0.21875 0.412109 0.222656 0.382812 
```

to the bbox format
```
2 xxxx xxxx xxxx xxxx
```

**Comment by glenn-jocher** [comment]
@sarmientoj24 I see, it looks like you want to convert a segmentation format to a bounding box format for object detection. Here's an example Python code snippet:

```python
def seg_to_bbox(seg_info):
    # Example input: 2 0.207031 0.558594 0.208984 0.527344 0.210938 0.488281 0.214844 0.445312 0.21875 0.412109 0.222656 0.382812
    class_id, *points = seg_info.split()
    points = [float(p) for p in points]
    x_min, y_min, x_max, y_max = min(points[0::2]), min(points[1::2]), max(points[0::2]), max(points[1::2])
    bbox_info = f"{class_id} {x_min} {y_min} {x_max} {y_max}"
    return bbox_info
```

You can call this function with the segmentation format as an input to get the corresponding bounding box format. For example:

```python
seg_info = "2 0.207031 0.558594 0.208984 0.527344 0.210938 0.488281 0.214844 0.445312 0.21875 0.412109 0.222656 0.382812"
bbox_info = seg_to_bbox(seg_info)
print(bbox_info)  # Output: "2 0.207031 0.382812 0.21875 0.558594"
```

I hope this helps!

**Comment by sarmientoj24** [comment]
Thank you.

**Comment by glenn-jocher** [comment]
@sarmientoj24 you're welcome! Don't hesitate to ask if you have any further questions.

**Comment by sarmientoj24** [comment]
@glenn-jocher it seems like it is wrong?
This is the image for this segmentation format
```
0 0.046875 0.369141 0.0644531 0.384766 0.0800781 0.402344 0.0898438 0.433594 0.0996094 0.460938 0.113281 0.484375 0.136719 0.507812 0.169922 0.509766 0.191406 0.494141 0.199219 0.470703 0.212891 0.447266 0.228516 0.425781 0.25 0.402344 0.267578 0.380859 0.277344 0.359375 0.285156 0.337891 0.285156 0.316406 0.269531 0.28125 0.263672 0.248047 0.265625 0.222656 0.261719 0.197266 0.255859 0.175781 0.248047 0.152344 0.234375 0.132812 0.210938 0.121094 0.191406 0.113281 0.175781 0.111328 0.158203 0.103516 0.136719 0.103516 0.117188 0.111328 0.105469 0.115234 0.0859375 0.119141 0.0703125 0.126953 0.0566406 0.134766 0.046875 0.144531 0.0371094 0.154297 0.0273438 0.169922 0.0234375 0.1875 0.0195312 0.205078 0.0195312 0.228516 0.0195312 0.242188 0.0195312 0.263672 0.0195312 0.285156 0.0214844 0.300781 0.0273438 0.316406 0.03125 0.332031 0.0332031 0.347656 0.0371094 0.359375
```
![image](https://user-images.githubusercontent.com/8830319/231968540-2233b0c0-60cc-4d27-9723-d00108f01483.png)

However, this is the converted box
```
0 0.0195312 0.103516 0.285156 0.509766
```
with this
![image](https://user-images.githubusercontent.com/8830319/231968785-c75ed7af-68b7-45e6-89da-e0fafb545d24.png)

**Comment by glenn-jocher** [comment]
@sarmientoj24 I apologize for my mistake. You are correct that the bounding box format I provided earlier is not correct for the given segmentation format. Here is a corrected version of the `seg_to_bbox` function that should work correctly:

```python
def seg_to_bbox(seg_info):
    # Example input: 5 0.046875 0.369141 0.0644531 0.384766 0.0800781 0.402344 ...
    class_id, *points = seg_info.split()
    points = [float(p) for p in points]
    x_min, y_min, x_max, y_max = min(points[0::2]), min(points[1::2]), max(points[0::2]), max(points[1::2])
    bbox_info = f"{int(class_id)-1} {x_min} {y_min} {x_max} {y_max}"
    return bbox_info
```

The changes from my previous version are simply that we subtract 1 from the class ID (since YOLOv5 uses 0-based indexing), and we use `min` and `max` to find the bounding box coordinates from the segmentation coordinates. With this corrected version, calling `seg_to_bbox` with your example segmentation format should produce the following bounding box format: 

```
4 0.0195312 0.103516 0.359375 0.509766
```

I apologize again for my mistake, and I hope this corrected function gives you the results you were looking for.

**Comment by sarmientoj24** [comment]
Oh sorry. I think the class is correct. I made a typo. it's the coordinates that is wrong earlier.

**Comment by sarmientoj24** [comment]
It also seems that the function is basically the same as the previous one except the class?

```
# Previous
x_min, y_min, x_max, y_max = min(points[0::2]), min(points[1::2]), max(points[0::2]), max(points[1::2])

# Now
x_min, y_min, x_max, y_max = min(points[0::2]), min(points[1::2]), max(points[0::2]), max(points[1::2])
```

**Comment by sarmientoj24** [comment]
![image](https://user-images.githubusercontent.com/8830319/232021538-a4bc28f9-1211-4764-a999-cc6e1e276443.png)

**Comment by sarmientoj24** [comment]
The bounding box format is the same as the YOLOv5 bbox format, right?

**Comment by sarmientoj24** [comment]
I am under the impression that the format for YOLOv5 bbox is
```
class x_center y_center width height
```

**Comment by sarmientoj24** [comment]
i already kinda fixed it, but it needs width and height for the original YOLOv5 bbox formatting

**Comment by glenn-jocher** [comment]
@sarmientoj24 yes, the bounding box format for YOLOv5 is indeed `class x_center y_center width height`. 

To calculate the width and height from the `x_min`, `y_min`, `x_max`, and `y_max` coordinates, you can simply subtract `x_min` from `x_max` to get the width, and subtract `y_min` from `y_max` to get the height. So the updated `seg_to_bbox` function with the YOLOv5 format should look like this:

```python
def seg_to_bbox(seg_info):
    # Example input: 5 0.046875 0.369141 0.0644531 0.384766 0.0800781 0.402344 ...
    class_id, *points = seg_info.split()
    points = [float(p) for p in points]
    x_min, y_min, x_max, y_max = min(points[0::2]), min(points[1::2]), max(points[0::2]), max(points[1::2])
    width, height = x_max - x_min, y_max - y_min
    x_center, y_center = (x_min + x_max) / 2, (y_min + y_max) / 2
    bbox_info = f"{int(class_id)-1} {x_center} {y_center} {width} {height}"
    return bbox_info
```

This should give you the correct YOLOv5 bounding box format with class, x_center, y_center, width, and height. Let me know if you have any further questions!

**Comment by grandonblake** [comment]
> @sarmientoj24 yes, the bounding box format for YOLOv5 is indeed `class x_center y_center width height`.
> 
> To calculate the width and height from the `x_min`, `y_min`, `x_max`, and `y_max` coordinates, you can simply subtract `x_min` from `x_max` to get the width, and subtract `y_min` from `y_max` to get the height. So the updated `seg_to_bbox` function with the YOLOv5 format should look like this:
> 
> ```python
> def seg_to_bbox(seg_info):
>     # Example input: 5 0.046875 0.369141 0.0644531 0.384766 0.0800781 0.402344 ...
>     class_id, *points = seg_info.split()
>     points = [float(p) for p in points]
>     x_min, y_min, x_max, y_max = min(points[0::2]), min(points[1::2]), max(points[0::2]), max(points[1::2])
>     width, height = x_max - x_min, y_max - y_min
>     x_center, y_center = (x_min + x_max) / 2, (y_min + y_max) / 2
>     bbox_info = f"{int(class_id)-1} {x_center} {y_center} {width} {height}"
>     return bbox_info
> ```
> 
> This should give you the correct YOLOv5 bounding box format with class, x_center, y_center, width, and height. Let me know if you have any further questions!

I tried applying this code but I don't think it works if there's multiple annotations in the image?
