### ISSUE TITLE
Area extraction from masks output of instance segmentation model

### ISSUE THREAD

**Issue by vimala-ds** [ultralytics/yolov5#11331]
Hi, I want to get area of the mask obtained from the YOLOV5 instance segmentation model. Tried with cv2.contourArea, but end up with the below issue:
File "segment/predict.py", line 204, in run
    area = cv2.contourArea(masks.numpy())
cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\shapedescr.cpp:315: error: (-215:Assertion failed) npoints >= 0 && (depth == CV_32F || depth == CV_32S) in function 'cv::contourArea'

Can anyone please let me know, where I'm going wrong.

**Comment by glenn-jocher** [comment]
@vimala-ds the error message suggests that there is a problem with the input arguments to the `cv2.contourArea()` function. The `masks.numpy()` function likely returns a numpy array of masks, but `cv2.contourArea()` expects a single mask as input, so you may need to loop through the masks and calculate the area of each one individually.

Here is one example of how you could modify your code to calculate the area of each mask:

```
masks_np = masks.numpy()
areas = []
for mask in masks_np:
    contours, hierarchy = cv2.findContours(mask.astype(np.uint8), cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
    area = cv2.contourArea(contours[0])
    areas.append(area)
```

This code loops through each mask in the array `masks_np` and calculates the area using `cv2.findContours()` to extract the contours of the mask, and then `cv2.contourArea()` to calculate the area of the contours. It stores the area of each mask in a list called `areas`.

I hope this helps! Let me know if you have any further questions.

**Comment by vimala-ds** [comment]
> @vimala-ds the error message suggests that there is a problem with the input arguments to the `cv2.contourArea()` function. The `masks.numpy()` function likely returns a numpy array of masks, but `cv2.contourArea()` expects a single mask as input, so you may need to loop through the masks and calculate the area of each one individually.
> 
> Here is one example of how you could modify your code to calculate the area of each mask:
> 
> ```
> masks_np = masks.numpy()
> areas = []
> for mask in masks_np:
>     contours, hierarchy = cv2.findContours(mask.astype(np.uint8), cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
>     area = cv2.contourArea(contours[0])
>     areas.append(area)
> ```
> 
> This code loops through each mask in the array `masks_np` and calculates the area using `cv2.findContours()` to extract the contours of the mask, and then `cv2.contourArea()` to calculate the area of the contours. It stores the area of each mask in a list called `areas`.
> 
> I hope this helps! Let me know if you have any further questions.

It worked. Thanks a lot Glenn!!

**Comment by glenn-jocher** [comment]
You're welcome, @vimala-ds! I'm glad to hear that the solution worked for you. If you have any more questions or need further assistance as you continue working with YOLOv5, don't hesitate to reach out. Happy coding! 😊👍

**Comment by kmanjari** [comment]
> > @vimala-ds the error message suggests that there is a problem with the input arguments to the `cv2.contourArea()` function. The `masks.numpy()` function likely returns a numpy array of masks, but `cv2.contourArea()` expects a single mask as input, so you may need to loop through the masks and calculate the area of each one individually.
> > Here is one example of how you could modify your code to calculate the area of each mask:
> > ```
> > masks_np = masks.numpy()
> > areas = []
> > for mask in masks_np:
> >     contours, hierarchy = cv2.findContours(mask.astype(np.uint8), cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
> >     area = cv2.contourArea(contours[0])
> >     areas.append(area)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This code loops through each mask in the array `masks_np` and calculates the area using `cv2.findContours()` to extract the contours of the mask, and then `cv2.contourArea()` to calculate the area of the contours. It stores the area of each mask in a list called `areas`.
> > I hope this helps! Let me know if you have any further questions.
> 
> It worked. Thanks a lot Glenn!!

Hello @glenn-jocher I used your example code to calculate the area of segmented mask but getting this error
<img width="1301" alt="Screenshot 2024-02-02 at 4 57 13 PM" src="https://github.com/ultralytics/yolov5/assets/16285204/16c72509-7405-4fa4-96b5-9c29e04a2848">
Basically, I want to calculate the area of black and white pixels inside the segmented area and knoww the difference

**Comment by glenn-jocher** [comment]
@kmanjari i'm glad to hear you've made progress! The error in the screenshot you're referring to seems to be missing, but if you're looking to calculate the area of black and white pixels within a segmented mask, you can do so by counting the number of pixels that correspond to each category.

Here's a simple way to calculate the areas:

```python
import numpy as np

# Assuming 'mask' is a binary mask with white pixels for the object (value 255) and black pixels for the background (value 0)
white_area = np.sum(mask == 255)
black_area = np.sum(mask == 0)

# If you need the area in terms of the number of pixels
print(f"White area (in pixels): {white_area}")
print(f"Black area (in pixels): {black_area}")

# If you need to calculate the difference
area_difference = abs(white_area - black_area)
print(f"Area difference (in pixels): {area_difference}")
```

Make sure that your mask is a binary image where the object is represented by white pixels (255) and the background is black (0). If your mask uses different values, you'll need to adjust the comparison in `np.sum()` accordingly.

If you encounter any specific errors, please provide the error message text, and I'll be happy to help you troubleshoot further.
