### ISSUE TITLE
NotImplementedError: cannot instantiate 'PosixPath' on your system

### ISSUE THREAD

**Issue by chelsea456** [ultralytics/yolov5#11330]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

i train classification and when i test it i got this error

raise NotImplementedError("cannot instantiate %r on your system" NotImplementedError: cannot instantiate 'PosixPath' on your system

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@chelsea456 thank you for your interest in contributing to the YOLOv5 project! Regarding the error you are experiencing, it seems to be related to a path issue. For more information, please check the following [similar issue](https://github.com/ultralytics/yolov5/issues/335). 

If you need further assistance, feel free to provide more details about your environment and your reproducible example. We are looking forward to your Pull Request!

**Comment by chelsea456** [comment]
> @chelsea456 thank you for your interest in contributing to the YOLOv5 project! Regarding the error you are experiencing, it seems to be related to a path issue. For more information, please check the following [similar issue](https://github.com/ultralytics/yolov5/issues/335).
> 
> If you need further assistance, feel free to provide more details about your environment and your reproducible example. We are looking forward to your Pull Request!

tks for your answer, but i can't find solution in your link sent me :(((

**Comment by glenn-jocher** [comment]
@chelsea456 I apologize that the suggested link did not help. Without more information about your environment and code, it's difficult to determine the root cause of the error. Can you provide more details about how you are testing your classification model and what code you are using?

**Comment by chelsea456** [comment]
>  @chelsea456 I apologize that the suggested link did not help. Without more information about your environment and code, it's difficult to determine the root cause of the error. Can you provide more details about how you are testing your classification model and what code you are using?

Tks sir!!! I fixed problem

**Comment by sohang3112** [comment]
@chelsea456 How did you fix this issue?? I am facing the same issue in Windows 11, not sure how to fix. Some other issues are also there about this, but all of them are marked stale.

**Comment by chelsea456** [comment]
> @chelsea456 How did you fix this issue?? I am facing the same issue in Windows 11, not sure how to fix. Some other issues are also there about this, but all of them are marked stale.
I slove it by training local, if u train on gg colab, u only can use on colab

**Comment by sohang3112** [comment]
@chelsea456 Thanks, I think I understand the issue now. I trained model on a Linux server and got this error when running `predict.py` on Windows. Maybe yolo is using a pickle file somewhere and storing `pathlib.Path` objects in it. Right now, my workaround is to run `predict.py` in WSL, but I wish this issue was prioritised more, as so many people have faced the issue.

**Comment by sohang3112** [comment]
@chelsea456 Thanks, I think I understand the issue now. I trained model on a Linux server and got this error when running `predict.py` on Windows. Maybe yolo is using a pickle file somewhere and storing `pathlib.Path` objects in it. Right now, my workaround is to run `predict.py` in WSL, but I wish this issue was prioritised more, as so many people have faced the issue.

**Comment by glenn-jocher** [comment]
@sohang3112 thank you for bringing this to our attention. We apologize for any inconvenience this issue may have caused you. The problem appears to be related to the use of `pathlib.Path` objects in a pickle file, which can cause incompatibility when using different operating systems. 

We understand that many users have faced this issue and we are constantly working on finding a solution that will work for everyone. In the meantime, you can try running `predict.py` in WSL as a temporary workaround. 

Thank you for your patience and understanding while we work on resolving this issue.

**Comment by sohang3112** [comment]
@glenn-jocher IMO easiest solution is to avoid pickling `Path` objects at all (or convert them to strings before picking). Also, this issue should be re-opened, as the problem still persists.

**Comment by ljubantomic01** [comment]
I just added:

import pathlib
temp = pathlib.PosixPath
pathlib.PosixPath = pathlib.WindowsPath

...in my Jupyter Notebook and it works now.

This error ocurred when I wanted to load classification model with torch.hub.load.

**Comment by glenn-jocher** [comment]
@ljubanradisin thank you for sharing your solution to the issue. It's great to hear that you were able to resolve the error by modifying the `pathlib` module in your Jupyter Notebook.

We appreciate your contribution in providing a workaround for loading the classification model with `torch.hub.load`. The `pathlib.PosixPath` and `pathlib.WindowsPath` modification allows for compatibility between different operating systems.

Your input is valuable and may help other users who face similar issues. Thank you once again for sharing your solution.

**Comment by sksayril** [comment]
**Using Yolov8-Cls Model it can more optimized and more capable model**  . It can solve this
(raise NotImplementedError("cannot instantiate %r on your system" NotImplementedError: cannot instantiate 'PosixPath' on your system)

Problem

**Comment by glenn-jocher** [comment]
@sksayril thank you for the suggestion! The YOLOv8-Cls model sounds promising with its optimized and enhanced capabilities. However, it's important to note that the issue you mentioned appears to be related to the handling of `PosixPath` objects in the current YOLOv5 implementation. We appreciate your understanding and continued support.

**Comment by apiwat31** [comment]
@glenn-jocher  Hello, I would like to ask permission to ask. I have encountered a problem that the model trained on colab cannot be used. There is an error like this. Where should I fix it?

  File "g:\yolov5-master\detect.py", line 295, in <module>
    main(opt)
  File "g:\yolov5-master\detect.py", line 290, in main
    run(**vars(opt))
  File "G:\yolov5-master\yolo-venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "g:\yolov5-master\detect.py", line 101, in run
    model = DetectMultiBackend(weights, device=device, dnn=dnn, data=data, fp16=half)
  File "g:\yolov5-master\models\common.py", line 356, in __init__
    model = attempt_load(weights if isinstance(weights, list) else w, device=device, inplace=True, fuse=fuse)
  File "g:\yolov5-master\models\experimental.py", line 79, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location='cpu')  # load
  File "G:\yolov5-master\yolo-venv\lib\site-packages\torch\serialization.py", line 1014, in load
    return _load(opened_zipfile,
  File "G:\yolov5-master\yolo-venv\lib\site-packages\torch\serialization.py", line 1422, in _load
    result = unpickler.load()
  File "C:\Users\acer\AppData\Local\Programs\Python\Python39\lib\pathlib.py", line 1085, in __new__
    raise NotImplementedError("cannot instantiate %r on your system"
NotImplementedError: cannot instantiate 'PosixPath' on your system

**Comment by sohang3112** [comment]
@apiwat31 The model was trained on Google Colab but you're doing inference on Windows, that's why this error is occurring. You can:
- do inference on Colab only
- do inference on Linux or Mac
- do inference on WSL in Windows

**Comment by apiwat31** [comment]
@sohang3112 I can fix it. Thank you very much for the advice.

**Comment by glenn-jocher** [comment]
@apiwat31 I'm glad to hear that you were able to resolve the issue with the advice provided. If you have any more questions or run into any other problems, feel free to reach out. Happy coding! 😊👍

**Comment by aadarsha-5** [comment]
@glenn-jocher  Now, I am facing the same issue . you mention to subsitute to section of code with initialization . But, I am confused in which section of code should I modify with initialization?
ACER@DESKTOP-M29U16B MINGW64 ~/ETEwastedetection (main)
$ python app.py
 * Serving Flask app 'app'
 * Debug mode: off
The system cannot find the path specified.
detect: weights=['my_model.pt'], source=../data/inputImage.jpg, data=data\coco128.yaml, imgsz=[416, 416], conf_thres=0.5, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_csv=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs\detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
YOLOv5  2024-1-26 Python-3.8.18 torch-2.1.2+cpu CPU

Traceback (most recent call last):
  File "detect.py", line 309, in <module>
    main(opt)
  File "detect.py", line 304, in main
    run(**vars(opt))
  File "C:\Users\ACER\miniconda2\envs\wastee\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 115, in run
    model = DetectMultiBackend(weights, device=device, dnn=dnn, data=data, fp16=half)
  File "C:\Users\ACER\ETEwastedetection\yolov5\models\common.py", line 344, in __init__
    model = attempt_load(weights if isinstance(weights, list) else w, device=device, inplace=True, fuse=fuse)
  File "C:\Users\ACER\ETEwastedetection\yolov5\models\experimental.py", line 79, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location='cpu')  # load
  File "C:\Users\ACER\miniconda2\envs\wastee\lib\site-packages\torch\serialization.py", line 1014, in load
    return _load(opened_zipfile,
  File "C:\Users\ACER\miniconda2\envs\wastee\lib\site-packages\torch\serialization.py", line 1422, in _load
    result = unpickler.load()
  File "C:\Users\ACER\miniconda2\envs\wastee\lib\pathlib.py", line 1044, in __new__
    raise NotImplementedError("cannot instantiate %r on your system"
NotImplementedError: cannot instantiate 'PosixPath' on your system

**Comment by sohang3112** [comment]
@aadarsha-5 Do inference on Linux. See [this comment](https://github.com/ultralytics/yolov5/issues/11330#issuecomment-1879875598).
