### ISSUE TITLE
Multiple cameras for source

### ISSUE THREAD

**Issue by aryanbarik** [ultralytics/yolov5#11333]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have both a Raspberry Pi camera (IMX219) and a USB Camera attached to a Jetson Nano. I'd like both of them to be used as the video input for `detect.py`. My guess is to use `list.streams` in the command which I believe would look like `python detect.py --weights yolov5s.pt list.streams`. However, I'm not sure how to initialize list.streams. Am I supposed to make a file named list.streams? What do I put in it?

**Comment by luisfmq** [comment]
hello!

you must create a .txt file witch contains both camera links, separated by enter, for example:

rtsp://login:pass@ipaddress:port/cam/realmonitor/channel=1&subtype=0
http://portid....

and on and on and on...

so, you must write at terminal "python detect.py --weights tolov5s.pt --source [yourfilename].txt"

and enjoy it!!!! :))))

**Comment by aryanbarik** [comment]
Thanks for the response @luisfmq. This is my .txt file
`csi://1
v4l2:///dev/video0`

Which I ran with the command `python3 detect.py --weights yolov5s.pt --source multicam.txt`

But I received these errors

`Traceback (most recent call last):
  File "detect.py", line 261, in <module>
    main(opt)
  File "detect.py", line 256, in main
    run(**vars(opt))
  File "/home/abarik/.local/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 111, in run
    dataset = LoadImages(source, img_size=imgsz, stride=stride, auto=pt, vid_stride=vid_stride)
  File "/home/abarik/yolov5/utils/dataloaders.py", line 254, in __init__
    raise FileNotFoundError(f'{p} does not exist')
FileNotFoundError: /home/abarik/yolov5/csi:/1 does not exist`

I know my CSI camera is connected properly as I was able to access it independently using a python script. I also tried changing csi://1 to csi://0. Any advice?
