### ISSUE TITLE
Why train dataloader only run on cpu 0, but test dataloader can run on more cpu cores?

### ISSUE THREAD

**Issue by klyjm** [ultralytics/yolov5#1134]
## ❔Question
I have set num_workers bigger than 0, but I find all threads of train dataloader only run in cpu 1 which makes trainning slowly, and more train.py run more slow, but the test dataloader running in test.py can run on num_works cores, why? How to solve it?

## Additional context
![2020-10-13 173422](https://user-images.githubusercontent.com/39526785/95871756-9de6a900-0da0-11eb-88de-4db30bd433a4.jpg)

**Comment by glenn-jocher** [comment]
@klyjm train and test dataloaders are built by the same function:
https://github.com/ultralytics/yolov5/blob/4d3680c81dad760e5d1ffe397ab2fc9169d9fb70/utils/datasets.py#L49-L72

**Comment by klyjm** [comment]
> @klyjm train and test dataloaders are built by the same function:
> https://github.com/ultralytics/yolov5/blob/4d3680c81dad760e5d1ffe397ab2fc9169d9fb70/utils/datasets.py#L49-L72

I know, so it is strange that why only train dataloader only run in cpu core 1, but test dataloader can work well.
I run 3 train.py now, and SID=18990 with num_workers=4, SID=5017 with 16, SID=4320 with 8, you can find in picture that they all run in core 0. But I have 2 cpus with 24 cores per cpu.

**Comment by klyjm** [comment]
> @klyjm train and test dataloaders are built by the same function:
> https://github.com/ultralytics/yolov5/blob/4d3680c81dad760e5d1ffe397ab2fc9169d9fb70/utils/datasets.py#L49-L72

I think I should edit the question, the dataloader run in train.py will only in one core, but in in test,py will on more num_workers cores. Is this a bug?

**Comment by glenn-jocher** [comment]
@klyjm its possible the effect you are seeing is hardware or environmentally dependent. 

In our experiments we definitely observe very substantial speedup (during training phase as well as test phase) as we increase --workers from 0 to 10 for example, i.e. on a 16-cpu VM. Indeed, training COCO would be nearly impossible to complete in a reasonable time with --workers 0. You may want to try your experiments in one of our working environments to see the correct behavior, and then debug your environment from there.

it appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below. 


## Requirements

**Python 3.8** or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including **`torch>=1.6`**. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by klyjm** [comment]
> @klyjm its possible the effect you are seeing is hardware or environmentally dependent.
> 
> In our experiments we definitely observe very substantial speedup (during training phase as well as test phase) as we increase --workers from 0 to 10 for example, i.e. on a 16-cpu VM. Indeed, training COCO would be nearly impossible to complete in a reasonable time with --workers 0. You may want to try your experiments in one of our working environments to see the correct behavior, and then debug your environment from there.
> 
> it appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally. If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below.
> 
> ## Requirements
> **Python 3.8** or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including **`torch>=1.6`**. To install run:
> 
> ```shell
> $ pip install -r requirements.txt
> ```
> 
> ## Environments
> YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):
> 
> * **Google Colab Notebook** with free GPU: [![Open In Colab](https://camo.githubusercontent.com/52feade06f2fecbf006889a904d221e6a730c194/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb)
> * **Kaggle Notebook** with free GPU: https://www.kaggle.com/models/ultralytics/yolov5
> * **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
> * **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://camo.githubusercontent.com/caa63570e9f4e9771b02fc86d87e78aad3bf9785/68747470733a2f2f696d672e736869656c64732e696f2f646f636b65722f70756c6c732f756c7472616c79746963732f796f6c6f76353f6c6f676f3d646f636b6572)
> 
> ## Status
> ![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)
> 
> If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

I find the bug is with version of python. I update python to 3.8, and there is no question.Thanks!

**Comment by pderrenger** [comment]
Great to hear updating Python resolved the issue! If you have any more questions, feel free to ask.
