### ISSUE TITLE
AttributeError: Can't get attribute 'Stem' on module 'models.common' when running detect.py using custom model

### ISSUE THREAD

**Issue by idataaki** [ultralytics/yolov5#11349]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Validation, Detection

### Bug

```
(venv) D:\project\codes\yolov5\yolov5>python detect.py --weights best.pt --source b0087.jpg
detect: weights=['best.pt'], source=b0087.jpg, data=data\coco128.yaml, 
imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs\detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
YOLOv5  v7.0-140-g1db9533 Python-3.10.7 torch-2.0.0+cpu CPU

Traceback (most recent call last):
  File "D:\project\codes\yolov5\yolov5\detect.py", line 261, in <module>
    main(opt)
  File "D:\project\codes\yolov5\yolov5\detect.py", line 256, in main   
    run(**vars(opt))
  File "D:\project\codes\yolov5\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\project\codes\yolov5\yolov5\detect.py", line 98, in run     
    model = DetectMultiBackend(weights, device=device, dnn=dnn, data=data, fp16=half)
  File "D:\project\codes\yolov5\yolov5\models\common.py", line 344, in 
__init__
    model = attempt_load(weights if isinstance(weights, list) else w, device=device, inplace=True, fuse=fuse)
  File "D:\project\codes\yolov5\yolov5\models\experimental.py", line 79, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location='cpu')  # load 
  File "D:\project\codes\yolov5\venv\lib\site-packages\torch\serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "D:\project\codes\yolov5\venv\lib\site-packages\torch\serialization.py", line 1172, in _load
    result = unpickler.load()
  File "D:\project\codes\yolov5\venv\lib\site-packages\torch\serialization.py", line 1165, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'Stem' on <module 'models.common' from 'D:\\project\\codes\\yolov5\\yolov5\\models\\common.py'>
```

### Environment

- YOLO: YOLOv5 v7.0
- OS: windows 10
- python 3.10.7

### Minimal Reproducible Example

I have attached the best.pt file
[best.zip](https://github.com/ultralytics/yolov5/files/11222513/best.zip)

### Additional

I have some trained and exported .pt files based on yolov5 with fruits dataset. I am using yolov5-LiNet. i have created the virtual env and cloned the repo. then I installed the requirements.txt file and I run the command:
`python detect.py --weights best.pt --source b0087.jpg`
detect.py and best.pt and b0087.jpg are in a same directory
i get the same error when I run the command: `python val.py --weights best.pt`

here is the link to the yolov5-LiNet model paper [YOLOv5-LiNet: A lightweight network for fruits instance segmentation](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0282297)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@idataaki, it seems like the error is due to a version incompatibility. In our repository, we specify the Python version as >=3.7.0, while you're using Python 3.10.7. We recommend downgrading your Python version to 3.7 or 3.8 and re-running the command. Additionally, try running `python -c "import torch; print(torch.__version__)"` to verify that you have PyTorch>=1.7 installed. 

If the issue persists, can you please verify if the `Stem` class is present in the `models/common.py` file? If it's not there, please try reinstalling YOLOv5 by deleting the cloned directory and reinstalling it via the instructions in the documentation. Let me know if this helps!

**Comment by larrywal-express** [comment]
class Stem(nn.Module):
    # Stem
    def __init__(self, c1, c2, k=1, s=1, p=None, g=1, act=True):  # ch_in, ch_out, kernel, stride, padding, groups
        super(Stem, self).__init__()
        c_ = int(c2/2)  # hidden channels
        self.cv1 = Conv(c1, c_, 3, 2)
        self.cv2 = Conv(c_, c_, 1, 1)
        self.cv3 = Conv(c_, c_, 3, 2)
        self.pool = torch.nn.MaxPool2d(2, stride=2)
        self.cv4 = Conv(2 * c_, c2, 1, 1)

    def forward(self, x):
        x = self.cv1(x)
        return self.cv4(torch.cat((self.cv3(self.cv2(x)), self.pool(x)), dim=1))

**Comment by idataaki** [comment]
Thanks @glenn-jocher
I did all the steps you mentioned and I am still getting the same error.

**Comment by glenn-jocher** [comment]
@idataaki i see, thanks for trying those steps. To further assist you, could you provide the exact version number of the torch package that you are using? You can check this with the command `python -c "import torch; print(torch.__version__)"`.
