### ISSUE TITLE
loading a custom model by GPU uses RAM but loading on CPU doesn't. how can I not use RAM when I load by GPU as well?

### ISSUE THREAD

**Issue by MohammadsAdrA-AI** [ultralytics/yolov5#11352]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I tried to load my custom model by this: 
```
model = torch.hub.load("./yolov5_detection/script/packages/yolov5", "custom",
        path="./raddev/yolov5_detection/model/best.pt",
        force_reload=True, source="local", device=0)
```
![image](https://user-images.githubusercontent.com/77414512/231899169-57421576-533a-4461-a25f-47a53ccd2f15.png)
![image](https://user-images.githubusercontent.com/77414512/231899227-39e22288-44ce-4ee8-a87c-043970349c40.png)
and I tried to load on cpu by this: 
```
model = torch.hub.load("./yolov5_detection/script/packages/yolov5", "custom",
        path="./raddev/yolov5_detection/model/best.pt",
        force_reload=True, source="local", device="cpu")
```
obviously no load on GPU but the htop shows no usage on RAM as well: 
![image](https://user-images.githubusercontent.com/77414512/231899477-88dc8fec-981f-445a-bfa3-047048b54084.png)
but my question is how can I load on GPU but not use RAM?

**Comment by glenn-jocher** [comment]
@MohammadsAdrA-AI loading a model on a GPU will involve using GPU memory. However, you can try reducing the GPU memory usage by running the model with a lower batch size or by reducing the input image size. This might help you load the model on the GPU without running out of memory. Also, ensure that CUDA and other prerequisites are installed and working correctly for GPU hardware acceleration. You can find more detailed information on how to do this in the Ultralytics YOLOv5 documentation at https://docs.ultralytics.com/yolov5/.

**Comment by MohammadsAdrA-AI** [comment]
> 

Im ok to use GPU RAM my problem is using main memory is. when I load on GPU 5.8GB RAM and 2.9 GPU RAM used. but when I load on CPU only 2.4GB RAM used. 
I can't undersand the difference between the 5.8 and 2.4 one

**Comment by glenn-jocher** [comment]
@MohammadsAdrA-AI I see what you mean now. When you load a model on a CPU, it only uses CPU memory, which usually has greater capacity than GPU memory. When you load a model on a GPU, it uses both CPU and GPU memory, with the majority of the memory being consumed by the GPU. So it is normal to see a difference in memory consumption when switching from a CPU to a GPU. If you are experiencing memory problems when loading a model on a GPU, you can try reducing the batch size, using a smaller input image size or consider upgrading your GPU to one with more memory capacity.

**Comment by MohammadsAdrA-AI** [comment]
Thank you so much, right now, my bottleneck is the CPU memory, is there any way to use more GPU memory and use less CPU memory?

**Comment by glenn-jocher** [comment]
@MohammadsAdrA-AI You can reduce the amount of CPU memory used by offloading some of the pre-processing work to the GPU using CUDA. This can be achieved using the PyTorch `to()` method. For example, you can move your input data to GPU memory before running it through the YOLOv5 model using the following code snippet:

```
import torch
import numpy as np 

# define your input data 
input_data = np.random.rand(1, 3, 416, 416)

# move input data to GPU memory 
input_data = torch.from_numpy(input_data).float().to('cuda')

# load YOLOv5 model on GPU 
model = torch.hub.load("./yolov5_detection/script/packages/yolov5", "custom",
        path="./raddev/yolov5_detection/model/best.pt",
        force_reload=True, source="local", device="cuda")

# run model on input data 
output = model(input_data)
```

This should move your input data to GPU memory before running the model, which can help reduce CPU memory usage. However, keep in mind that this may increase GPU memory usage, so be sure to monitor your GPU memory consumption as well.
