### ISSUE TITLE
How to open and revise model files such as yolov5s.pt?

### ISSUE THREAD

**Issue by SeuGuoTong** [ultralytics/yolov5#11353]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to open and revise model files such as yolov5s.pt?

**Comment by glenn-jocher** [comment]
@SeuGuoTong to load a pre-trained YOLOv5 PyTorch model (e.g. `yolov5s.pt`, `yolov5m.pt`, `yolov5x.pt`) in Python:

```python
import torch

model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)
```

And to save the model:

```python
model.save('yolov5s.pt')
```

You can also modify the model by accessing its weights and modifications:

```python
model.yaml['nc'] = 3  # replace number of classes
model.head[0](in_channels=3)  # replace input channels
```

After modifying the model, save it using `model.save('filename.pt')`.

**Comment by SeuGuoTong** [comment]
Thank you for your reply very much!

And I would like to know how to modify the number of layers and parameters of the network， especially how to modify the parameters in the 24 layer network architecture.
path = './weights/yolov5s.pt'
pt = torch.load(path)

model = pt["model"]













                       
Original Email
                       
                     

Sender:"Glenn Jocher"< ***@***.*** &gt;;

Sent Time:2023/4/14 14:27

To:"ultralytics/yolov5"< ***@***.*** &gt;;

Cc recipient:"SeuGuoTong"< ***@***.*** &gt;;"Mention"< ***@***.*** &gt;;

Subject:Re: [ultralytics/yolov5] How to open and revise model files such asyolov5s.pt? (Issue #11353)




 
@SeuGuoTong to load a pre-trained YOLOv5 PyTorch model (e.g. yolov5s.pt, yolov5m.pt, yolov5x.pt) in Python:
 import torch model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)
 
And to save the model:
 model.save('yolov5s.pt')
 
You can also modify the model by accessing its weights and modifications:
 model.yaml['nc'] = 3  # replace number of classes model.head[0](in_channels=3)  # replace input channels
 
After modifying the model, save it using model.save('filename.pt').
 
&mdash;

**Comment by 2846539535** [comment]
![image](https://github.com/ultralytics/yolov5/assets/88443535/0aae4202-2c44-4257-bf32-3c2db6ce2c45)
问题：为什么不能调用自己训练好的模型，是什么地方出现了错误么。

**Comment by glenn-jocher** [comment]
@2846539535 hi there! 

It seems like you're having trouble loading your custom trained model. In order to assist you better, could you please provide more details or error messages that you are encountering? This will help us understand the issue and provide you with a more accurate solution.

Thank you for reaching out to us, and we look forward to helping you resolve the problem.
