### ISSUE TITLE
Save all inference in custom folder. 

### ISSUE THREAD

**Issue by fo250061** [ultralytics/yolov5#11369]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When I run the code below, I get TypeError: Detections.save() got an unexpected keyword argument 'file'. I will like to save the inference (images) in a specific folder. I noticed that when I used results.save(), a new subfolder (expX) is created each time in runs folder. This behaviour is not desired. I will like all the inference to be saved in the out folder without any sub folders (or the runs/detect folder without any sub folders)

import os
import torch
from PIL import Image
import time

model = torch.hub.load('./yolov5', 'custom', path='best.pt', source='local', force_reload=True)

model.conf = 0.7  # NMS confidence threshold

model.iou = 0.45

# Define input and output folders

input_folder = 'in'
output_folder = 'out

# Loop over all image files in input directory
for filename in os.listdir(input_folder):
    if filename.endswith('.jpg') or filename.endswith('.png'):
        # Load image and run inference
        img_path = os.path.join(input_folder, filename)
        img = Image.open(img_path)
        results = model(img)

        # Show the results and close the window after 5 seconds
        results.show()
        results.save(file = output_folder)
        out = results.pandas().xyxy[0].to_json(orient="records") 
        print(out)

**Comment by glenn-jocher** [comment]
Hello @fo250061,

The issue with your code is that `results.save(file=output_folder)` doesn't accept a folder path as the `file` parameter. Instead, you can use `os.path.join(output_folder, filename)`. 

Try updating the line to the following:

```
results.save(os.path.join(output_folder, filename))
```

This will save the detection results for each image in the out folder, without any subfolders.

**Comment by fo250061** [comment]
I updated the code with the correction you gave, but it didn't fix the issue. Instead a new folder called runs (with sub folder detect) was created, and for each inference a new subfolder expX is created and then the image is saved there. 

Fusing layers... 
YOLOv5s summary: 157 layers, 7020913 parameters, 0 gradients, 15.8 GFLOPs
Adding AutoShape... 

Saved 1 image to runs/detect/exp8
Saved 1 image to runs/detect/exp9
Saved 1 image to runs/detect/exp10
Saved 1 image to runs/detect/exp11

**Comment by glenn-jocher** [comment]
@fo250061, my apologies for the confusion. `results.save()` does not accept a folder as an argument. It saves each image with numbered filenames `exp0.jpg`, `exp1.jpg`, `exp2.jpg`, etc. in a timestamped subfolder within `runs/detect/` by default.

If you'd like the detections to be saved to a specific folder, you can simply create this folder beforehand and move the timestamped subfolder there after running the code.

For example, with the following additions in your code:

```python
import shutil

# Define output folder
output_folder = 'out'

# Loop over all image files in input directory
for filename in os.listdir(input_folder):
    if filename.endswith('.jpg') or filename.endswith('.png'):
        # Load image and run inference
        img_path = os.path.join(input_folder, filename)
        img = Image.open(img_path)
        results = model(img)

        # Save detection output to runs/detect/ folder
        results.save()

        # Move inference output to specified output folder
        timestamp = os.listdir('runs/detect/')[0]
        shutil.move(os.path.join('runs/detect', timestamp), os.path.join(output_folder, timestamp))
```

All detections will be saved in a new timestamped folder in the `out` folder.

I hope this helps!

**Comment by snekumar** [comment]
I want to save the labels and the detected Images in separate folder ,how do I do that

**Comment by glenn-jocher** [comment]
@snekumar hello!

To save the labels and detected images in separate folders, you can modify the output path in your script. After running the detection with `results = model(img)`, save the images using `results.save()` which by default saves in `runs/detect/expX`. For labels, you can extract them from `results.pandas().xyxy[0]` and save them to your desired folder using pandas' `to_csv()` method.

Here's a quick example:

```python
import pandas as pd

# Save images
results.save()

# Save labels
labels = results.pandas().xyxy[0]
labels.to_csv('path_to_your_labels_folder/labels.csv')
```

Adjust the paths as needed to direct the outputs to different folders. This should help you organize your detected images and labels separately.
