### ISSUE TITLE
Merge classification and detection Model onnx

### ISSUE THREAD

**Issue by Mahdi-Maaref** [ultralytics/yolov5#11364]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

im trying to Merge two models first one is a detection model and i would like to feed detected object to a classifier model both model traind by yolov5 and converted to onnx , i need an onnx model that get an image and use both models to detect and classify object

note:i know i can directly classfiy and detecte object using detection model but i prefer to have more accurate model

**Comment by glenn-jocher** [comment]
@2022Mahdi to accomplish this, you can load both ONNX models within a single script and run the detection model followed by the classification model on the detected objects. After obtaining the detection results, you will need to extract the bounding boxes of the detected objects and crop them out of the original image to feed to the classification model. You can then merge the results of the two models to obtain the final predictions. You can use the ONNX runtime to execute the models within your script. For more information on using ONNX for object detection and classification, please refer to the Ultralytics YOLOv5 documentation available at https://docs.ultralytics.com/yolov5/.
