### ISSUE TITLE
modifying annotated objects that are annotated automatically using a trained yolov5 model

### ISSUE THREAD

**Issue by pejman3610** [ultralytics/yolov5#11379]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi Ultralytics team,

I was able to train a YOLOv5 model and use it to automatically annotate new datasets. However, I am currently facing an issue where I am unable to modify previously annotated objects, change label names or add new annotations. Could you please advise me if it's possible to perform these tasks with the current setup?

I would greatly appreciate your advice on this matter.

**Comment by glenn-jocher** [comment]
@pejman3610 hi there! 👋

After automating annotation with a trained YOLOv5 model, you can freely modify the annotated objects and change label names using annotation software like labelImg, VoTT, or via scripting.

For more details, feel free to check out the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/ for further guidance.

Let me know if you have any other questions. Good luck with your project!
