### ISSUE TITLE
train.py path error on startup configuration

### ISSUE THREAD

**Issue by apiszcz** [ultralytics/yolov5#11371]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

The following error occurs when starting training

```
> c:\test\lib\yolov5\train.py(40)<module>()
-> sys.path.append(str(ROOT))  # add ROOT to PATH
(Pdb) n
> c:\test\lib\yolov5\train.py(41)<module>()
-> ROOT = Path(os.path.relpath(ROOT, Path.cwd()))  # relative
(Pdb) n
ValueError: path is on mount '\\\\host.domain.com\\X', start on mount 'X:'
> c:\test\lib\yolov5\train.py(41)<module>()
-> ROOT = Path(os.path.relpath(ROOT, Path.cwd()))  # relative
```

### Environment

Yolov5
Windows Server

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@apiszcz hello! This error seems to be related to the `ROOT` path used during training. It seems like your `ROOT` path is on a network mount, which is causing some issues. One solution is to move your `ROOT` path to a local drive on your machine. You can read more about `ROOT` paths in the documentation at https://docs.ultralytics.com/yolov5/training.html#train-hyp. Let me know if this helps!
