### ISSUE TITLE
how to get the instance's mask

### ISSUE THREAD

**Issue by 44825762** [ultralytics/yolov5#11382]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I wonder how can I get the mask that only contain the segnmented instance, like the instance area are put with 255, and put other area with 0 and there is a clear boundary between instance and background. I mean I need a mask which contain only one thing, does any one know how to get this kind of mask?

**Comment by glenn-jocher** [comment]
@44825762 to get a mask containing only one instance, you could use the `instance(agnostic)` flag when running YOLOv5 in inference mode. This will output a separate `png` image for each detected instance, with the instance area put at 255 and other areas set to 0. You can then combine these masks into a single output mask by overlap/blend masks together. For more information on inference flags you can check [here](https://github.com/ultralytics/yolov5/issues/359#issuecomment-807976035).

**Comment by 44825762** [comment]
@glenn-jocher Thank you for your reply. I am using an ncnn model, would you mind tell me how can I set the flag. I can see  there is a modle.opt option, but the option does not contain an instance(agnostic) flag. Thank you very much.

**Comment by glenn-jocher** [comment]
@44825762 If you're using an ncnn model, you may need to modify your source code to add the `instance(agnostic)` flag to your inference configuration. You can add `model.opt.instance_agnostic = false;` to the settings in the source code to enable instance segmentation, making sure to recompile after the change. You can also control different flags and settings like `confidence`, `sigmoid`, and `TFLite`. Please refer to the ncnn documentation to see how to configure the options.
