### ISSUE TITLE
How to credit the authors of yolov5

### ISSUE THREAD

**Issue by bonorico** [ultralytics/yolov5#1138]
## ❔Question
Hi,
we are thinking to use your code for our research. You provide some contacts, but how do we properly credit and acknowledge you for using the software ??   I think would be in you interest to provide info on this on README.

**Comment by glenn-jocher** [comment]
@bonorico we are aiming to publish a short paper to arxiv at end of year, in the meantime you can use this DOI:
https://doi.org/10.5281/zenodo.3908559

**Comment by whoafridi** [comment]
@glenn-jocher that's great you gonna publish paper for YOLOv5 /.
