### ISSUE TITLE
Model Tuning

### ISSUE THREAD

**Issue by MaxwellHogan** [ultralytics/yolov5#11388]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am trying to tune (train) a Yolov5 model after I have run some code to optimise the architecture

is there an in-built way to call training but pass a "DetectMultiBackend"?

### Clarification

I have a model that I have loaded in my script using:
`model = DetectMultiBackend(weights, device=device)`

where 'weights' is the path to a model that I have trained using train.py. 

I have a script where I am essentially pruning some redundant connections. 

After this point, it would be prudent to do some tuning to then regain some lost performance so preferably I'd like to be able to call something like `train.run(model)` like the val.run method. 

I am thinking the quickest way would be to create a fake checkpoint file containing the model that I could pass to train, but I was going to see if anyone had a better solution before I invested time into this.

**Comment by glenn-jocher** [comment]
@MaxwellHogan i'm not quite sure what you mean by "DetectMultiBackend" - YOLOv5 currently does not have an option with that name. However, in general, you can train a YOLOv5 model using the `train.py` script provided in the repository, passing in the appropriate command line arguments. If you want to use a custom architecture, you can modify the architecture definition file and use it in training. You can find more information and examples in the `README.md` and `train.py` files in the YOLOv5 repository.

**Comment by MaxwellHogan** [comment]
@glenn-jocher Sorry, I wrote this rather quickly, I have updated the above to try to be more clear.

**Comment by glenn-jocher** [comment]
@MaxwellHogan Thanks for clarifying. To train a model using a custom architecture definition, you can modify the `models/yolo.py` file in the YOLOv5 repository to define your custom model, and then use it in training by passing the `--cfg` command line argument to `train.py`, pointing to the updated configuration file. For example, if you have a custom architecture defined in `models/my_yolo.py`, you can run `train.py --data my_data.yaml --cfg models/my_yolo.yaml --weights weights.pt`. Note that you will still need to pass in the appropriate data configuration file and weights file. You may also find the `--resume` command line option useful for loading a checkpoint file. Good luck with your training!
