### ISSUE TITLE
Why is there a difference between val.py detection results and detect.py detection results?

### ISSUE THREAD

**Issue by Eri2726** [ultralytics/yolov5#11387]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

Hi!
I've used the original data to train and validate. I use val.py and detect.py, respectively.

### Question
When I tried to execute detect.py, I noticed that there was a discrepancy between the detect.py detection results and the val.py detection results.
Details are follows：
------
This time, I use only one image .
First, I ran a val.py.
```cmd
python val.py --weights C:\Users\~~~~\models\best.pt --data C:\Users\~~~~\data\valid3\data.yaml --img 640 --save-txt --save-conf --conf-thres 0.2 --iou-thres 0.6
```
And I got the following results in runs\val\exp13\labels\IMG_0121.txt：
```txt
0 0.2742 0.624213 0.0461547 0.033026 0.847769
0 0.332273 0.707128 0.0376017 0.0249223 0.771621
0 0.395059 0.906789 0.0372657 0.0298265 0.741917
0 0.582561 0.406594 0.0304165 0.0242927 0.701719
0 0.226321 0.558442 0.0326438 0.02553 0.625718
0 0.640264 0.23205 0.0264291 0.0210307 0.595323
0 0.477026 0.730236 0.0265545 0.0219655 0.587266
0 0.317117 0.834086 0.0306103 0.0242775 0.586945
0 0.222225 0.097663 0.0422521 0.0322202 0.521401
0 0.84692 0.772109 0.0358007 0.0285754 0.513393
0 0.535209 0.91223 0.0319012 0.0249561 0.430841
0 0.804827 0.324432 0.0229721 0.0194096 0.373771
0 0.585995 0.402967 0.0236618 0.0208841 0.267536
0 0.654169 0.0538474 0.0232822 0.0184519 0.245073
```
Next, I wanted to draw a bbox, so I ran detect.py
```cmd
python detect.py --weights C:\Users\~~~~\models\best.pt --source C:\Users\~~~~\data\valid3\images\ --img 640 --save-txt --save-conf --conf-thres 0.2 --iou-thres 0.6
```
Then, I got the following result in runs\detect\exp6\labels\IMG_0121.txt
```txt
0 0.852679 0.775918 0.0248016 0.0215774 0.214456
0 0.84623 0.774058 0.031746 0.0248016 0.232218
0 0.739253 0.197297 0.0228175 0.0186012 0.252071
0 0.588294 0.402778 0.021164 0.0193452 0.29797
0 0.534557 0.911334 0.030754 0.0235615 0.417589
0 0.804729 0.324033 0.0228175 0.0190972 0.431019
0 0.641865 0.231895 0.0251323 0.0203373 0.442411
0 0.321263 0.833209 0.0274471 0.0225694 0.501713
0 0.221065 0.0959821 0.0347222 0.0272817 0.543339
0 0.477844 0.729787 0.0310847 0.0220734 0.589311
0 0.583664 0.406622 0.0271164 0.0230655 0.619704
0 0.226356 0.557788 0.0327381 0.0248016 0.649387
0 0.395503 0.90687 0.037037 0.0295139 0.741666
0 0.333333 0.707093 0.0363757 0.0248016 0.763315
0 0.274471 0.623264 0.0436508 0.03125 0.816374

```
In detect.py it was 15 records, compared to 14 in val.py.
The arguments(--img, --conf-thres, --iou-thres) ware used the same values.

Why does it happen??
Could you please let me know?

**Comment by xinranzero** [comment]
I have the same problem. It seems that val.py and detect.py use different dataloaders, and the two files are set up for different purposes. When I look at val.py, I see that if I set conf-thres=0.1, I get a message, which is reported by the following code. I checked issues and found out that this was set up to get better mAPs, but I'm not sure why. Might it have something to do with this issue? 
```
if opt.conf_thres &gt;  0.001: # https://github.com/ultralytics/yolov5/issues/1466
LOGGER.info(f'WARNING ⚠️ confidence threshold {opt.conf_thres} &gt; 0.001 produces invalid results')
```

**Comment by glenn-jocher** [comment]
Hello @xinranzero-14, thanks for the question.

Yes, you're correct. `val.py` and `detect.py` use different dataloaders as they are meant for different purposes. 

In `val.py`, we use a higher confidence threshold (`0.001`) to attain better mAP due to a known issue. It is recommended to set `--conf-thres` to a value between 0.1-0.001 depending on your use case, as lower values generate more predictions and can hurt mAP. 

On the other hand, `detect.py` uses the dataloader from `datasets.py`, which is optimized for inference speed. The default `--conf-thres` value in `detect.py` is `0.25` but you can configure it as per your requirements.

Let me know if you have any further questions.

**Comment by Eri2726** [comment]
@glenn-jocher @xinranzero 
Thank you both for your answers.
I understanded that it's because different dataloaders are used in val.py and detect.py.

**Comment by glenn-jocher** [comment]
@Eri2726 you're welcome! If you have any further questions or run into any issues, feel free to ask. We are always here to help you.
