### ISSUE TITLE
Do we have a paper for yolov5?

### ISSUE THREAD

**Issue by Shanky71** [ultralytics/yolov5#11381]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I tried searching for the yolov5 paper but couldn't find it anywhere. Do we have a published paper for it. I have to cite it in my thesis.

**Comment by glenn-jocher** [comment]
@Shanky71 the YOLOv5 paper has not been published in a peer-reviewed scientific journal as it was not submitted for peer review. However, you can find detailed information about YOLOv5 architecture and its training methods in the Ultralytics YOLOv5 documentation, which includes a link to the technical report on the YOLOv5 algorithm: https://docs.ultralytics.com/yolov5.

**Comment by shashankrajput-iitk** [comment]
@glenn-jocher  Thanks for the help. Can I cite this doc too? Like you have a bibTex file for this documentation?

**Comment by glenn-jocher** [comment]
@Shanky71, yes, you can cite the Ultralytics YOLOv5 documentation in your thesis. You can find the citation format for the documentation in the "Citation" section of the documentation homepage (https://docs.ultralytics.com/yolov5/#citation) which includes a BibTeX file for easy reference. The BibTeX entry for citing the Ultralytics YOLOv5 documentation looks like this:

```
@misc{ultralytics2021yolov5,
  author = {Ultralytics},
  title = {{YOLOv5}: {A} state-of-the-art real-time object detection system},
  year = {2021},
  howpublished = {\url{https://docs.ultralytics.com}},
  note = {Accessed: insert date here}.
}
```
Please replace "insert date here" in the "note" field with the date you accessed the documentation.

**Comment by Kejia928** [comment]
Hi @glenn-jocher, Could I ask is there have any different between yolov5s and yolov5l's model architecture? Because I see the Docs only describes the yolov5l's model architecture.

**Comment by glenn-jocher** [comment]
@Kejia928, the architecture of YOLOv5s and YOLOv5l differs in terms of size and capacity. While the documentation currently describes the YOLOv5l model architecture in detail, you can still use that information as a reference for understanding the overall architecture of YOLOv5. The main difference between YOLOv5s and YOLOv5l lies in the number of layers and model capacity, which directly impacts the trade-off between speed and accuracy. If you need specific details regarding YOLOv5s, please feel free to ask and I will be happy to assist you further.

**Comment by adamjstewart** [comment]
YOLOv5 paper on arXiv: https://arxiv.org/abs/2407.20892

**Comment by pderrenger** [comment]
@adamjstewart thanks for sharing that arXiv link! @Shanky71 you now have the option to cite either the YOLOv5 arXiv paper (https://arxiv.org/abs/2407.20892) or the documentation/repository depending on your thesis requirements - many academic institutions accept arXiv preprints for citation purposes.
