### ISSUE TITLE
Hyperparameters of pretrained models

### ISSUE THREAD

**Issue by Sylus1000** [ultralytics/yolov5#11397]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

This question is similar to #11075
Which hyperparameters were used in the pretrained yolov5x.pt ?
The default hyperparameters in train.py seem to be hyp.scratch-low.yaml (for yolov5s.pt), but were they also used for pretraining yolov5x?

**Comment by glenn-jocher** [comment]
@Sylus1000, thank you for your question! Our pre-trained models were trained using a separate set of hyperparameters that are slightly different from the defaults provided in train.py. However, the exact hyperparameters used may vary depending on the particular pre-trained model. If you're interested in fine-tuning a pre-trained model on your own data, we recommend using hyperparameters similar to those in hyp.finetune.yaml, which is designed for fine-tuning pre-trained models. If you'd like more information about the specific hyperparameters used for a particular pre-trained model, please let us know!
