### ISSUE TITLE
Right image size for training/annotation/detection

### ISSUE THREAD

**Issue by fo250061** [ultralytics/yolov5#11396]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

My image size is 1920 * 1080. After annotation, i exported them using the same size. So, when training, what size should I provide as the input size to get the best detection? 

python3 train.py --img 640 --batch 16 --epochs 1000 --data ../annotations_folder/data.yaml --cfg ./models/yolov5s.yaml --weights ''

or 

python3 train.py --img 1920 --batch 16 --epochs 1000 --data ../annotations_folder/data.yaml --cfg ./models/yolov5s.yaml --weights ''

**Comment by glenn-jocher** [comment]
@fo250061 it's recommended that you train with an image size that is similar to the size of the images you plan to detect objects on. In this case, if you plan on detecting objects on images with a size of 1920x1080, then it's recommended to use the same size for training.

However, keep in mind that training with a larger image size will lead to better accuracy, but it will also take longer to train. Therefore, you can start with a smaller image size like 640x640 and gradually increase it to a larger size as needed.
