### ISSUE TITLE
Albumentations in YOLOv5s model

### ISSUE THREAD

**Issue by namita-agarwal** [ultralytics/yolov5#11398]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Does yolov5s model use augmentation function provided by the Albumentations library by default for image blurriness?

**Comment by glenn-jocher** [comment]
@namita-agarwal, thank you for your interest in YOLOv5 🚀. No, YOLOv5 does not use Albumentations by default for augmentations such as image blurriness. However, you can easily use Albumentations to apply various image augmentations using a custom training script if desired. You can find guidance on how to implement various image augmentations in the [Albumentations documentation](https://albumentations.ai/docs/). If you have any further questions, please let me know.
