### ISSUE TITLE
Is there a way to load a segmentation model using Torch Hub?

### ISSUE THREAD

**Issue by rukshankr** [ultralytics/yolov5#11390]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,
I have read the tutorial for loading YOLOv5 using Torch Hub, but is there a feature for using the YOLOv5 segmentation models via torch.hub? 
Or is there a way to load the backbone, neck and heads of YOLOv5-seg separately as modules in PyTorch?

**Comment by glenn-jocher** [comment]
@rukshankr at the moment, YOLOv5-segmentation models are not currently available via Torch Hub. However, you can load the backbone, neck, and head separately as modules in PyTorch. You can find more information on how to do this in the `yolov5/models` directory and also in the official PyTorch documentation. Let us know if you have any more questions.
