### ISSUE TITLE
img-weights doesn't seem to work

### ISSUE THREAD

**Issue by liquored** [ultralytics/yolov5#11406]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to train a model on my own data, but there is a certain gap in the data. Because of that, I use the trick image-weights, but it doesn't seem to have much effect. The fewer amounts of data get lower precision, recall and map.
Could you please give me some advice? I have tried OHEM, which makes my model divergent.
Look forward to your reply!

**Comment by liquored** [comment]
I am sorry, maybe I didn't make sense. At first, I make the parameter 'ima-weights' False, and I found the categories which have fewer numbers get worse precision, recall and map. Then I make the parameter 'ima-weights' True, but it doesn't make any change of precision, recall and map.

**Comment by liquored** [comment]
I am sorry, maybe I didn't make sense. At first, I make the parameter 'ima-weights' False, and I found the categories which have fewer numbers get worse precision, recall and map. Then I make the parameter 'ima-weights' True, but it doesn't make any change of precision, recall and map.

**Comment by liquored** [comment]
I have already solved this problem. I am sorry, I made a mistake last week. After my analysis and experimentation, the parameter 'ima-weights' works well. My problem is because the target is too small compared to other categories. While I make the input size bigger, the precision, recall and map have improved a lot.

**Comment by glenn-jocher** [comment]
@liquored, thank you for updating the community and sharing your solution. I'm glad to hear that you were able to resolve your issue with the 'ima-weights' parameter and improve your model's performance by adjusting the input size. It's great to see that you're experimenting with different parameters and techniques to improve your results, and I wish you continued success with your YOLOv5 projects. If you have any further questions or issues in the future, please don't hesitate to ask!

**Comment by liquored** [comment]
> @liquored, thank you for updating the community and sharing your solution. I'm glad to hear that you were able to resolve your issue with the 'ima-weights' parameter and improve your model's performance by adjusting the input size. It's great to see that you're experimenting with different parameters and techniques to improve your results, and I wish you continued success with your YOLOv5 projects. If you have any further questions or issues in the future, please don't hesitate to ask!

@glenn-jocher Yes, I have resolved my issue, but in fact, there is still a question why the OHEM does't work. Not only that, but it also seems to make the model worse, just like the focal loss which also makes my model worse.

**Comment by glenn-jocher** [comment]
@liquored, it's great to hear that you found a solution to your initial problem. As for OHEM and focal loss, they can be powerful tools when applied correctly, but they may not always yield positive results in every scenario. If you need further assistance with these techniques or encounter any other challenges, feel free to ask for help. Your perseverance and dedication to improving your YOLOv5 model are commendable, and I'm here to support you in any way I can. Keep up the great work!
