### ISSUE TITLE
Changing the predicted Mask values inside NMS

### ISSUE THREAD

**Issue by renjith-raman** [ultralytics/yolov5#11402]
Inside the non_max_suppression(), the mask values(32 values) associated with every predicted boxes also gets multiplied  by the obj_conf, eventhough the intention seems only to multiply cls_conf (80values) associated with every predicted box with obj_conf.
Please let me know if it is done on purpose.

Ref: https://github.com/ultralytics/yolov5/blob/aa7c45c2cff71d498f42e9762c73cb9e5b0c699a/utils/general.py#L968

**Comment by renjith-raman** [comment]
> Inside the non_max_suppression(), the mask values(32 values) associated with every predicted boxes also gets multiplied by the obj_conf, eventhough the intention seems only to multiply cls_conf (80values) associated with every predicted box with obj_conf. Please let me know if it is done on purpose.
> 
> Ref:
> 
> https://github.com/ultralytics/yolov5/blob/aa7c45c2cff71d498f42e9762c73cb9e5b0c699a/utils/general.py#L968

I believe line https://github.com/ultralytics/yolov5/blob/master/utils/general.py#L968 should have been after line https://github.com/ultralytics/yolov5/blob/master/utils/general.py#L972

**Comment by glenn-jocher** [comment]
@renjith-raman thank you for bringing this to our attention. Yes, it appears to be a mistake and they should be flipped; i.e., line 968 should come after line 972. This has been corrected in the latest version of YOLOv5. Thank you for using our software and please let us know if you have any further questions or concerns.

**Comment by renjith-raman** [comment]
@glenn-jocher thank you for the prompt response, could you please guide me to the lateset version of YOLOv5 with this fix

**Comment by glenn-jocher** [comment]
@renjith-raman you can find the latest version of YOLOv5 with this and other fixes on our GitHub repository: https://github.com/ultralytics/yolov5. Please ensure that you pull the latest changes from the `master` branch to get the latest version. Thank you!

**Comment by renjith-raman** [comment]
@glenn-jocher Somehow I am not able to find the above mentioned changes in the branch mentioned above. I was referring to the master branch from the link you had shared.
https://github.com/ultralytics/yolov5/blob/master/utils/general.py#L968

**Comment by glenn-jocher** [comment]
@renjith-raman, I apologize for any confusion. I may have misspoken earlier. It looks like the line order revisions you mentioned in your original message are still pending in the master branch of the YOLOv5 repository. The Ultralytics team is constantly working to improve the software, so I would suggest keeping an eye on the repository for updates on this issue. 

In the meantime, you could try the following approach which reverses the order of multiplication (starts with obj_conf instead of cls_conf) on line 968:

```
mask *= (mask > conf_thr) * torch.Tensor([obj_conf])
```

Please let us know if you have any further questions or concerns. Thanks!
