### ISSUE TITLE
Difference between model.forawrd(image) and model(image)

### ISSUE THREAD

**Issue by Vikram12301** [ultralytics/yolov5#11401]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am inferencing the model with torch.hub,
I am getting two different results when using model.forward(image) and model(image)
Is there some post-processing done after model.forward(image)?
If yes, Can you please specify what changes to be made?

**Comment by glenn-jocher** [comment]
@Vikram12301 `torch.hub` is used to load GitHub hosted pretrained models, which under the hood also calls `model.forward()` method to get the results. There shouldn't be any difference between calling `model.forward(image)` and `model(image)`. Both should give you the same output.

If you can provide more details on the differences in results that you are getting, it will help me to understand the issue better and assist you further with the problem.
