### ISSUE TITLE
Train/Test split for custom dataset

### ISSUE THREAD

**Issue by robotaiguy** [ultralytics/yolov5#1140]
## ❔Question
What is the recommended % split for train/test for a custom data-set. My data-set has approximately 8,000 images with 3 classes. Every image has class 0 and either class 1 or class 2.

I've seen tutorials mention 70/30, 80/20, 90/10. Can someone please explain when you'd use which?

**Comment by whoafridi** [comment]
Try to perform 70% training, 20% validation & rest 10% for testing purpose. I find some blogs/articles use this ratio.
