### ISSUE TITLE
ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found

### ISSUE THREAD

**Issue by LiuQiTangli** [ultralytics/yolov5#11417]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

Using the pycharm tool, it works fine.
I tried to execute the detection video from the command line, but it didn't work and reported an error：

(climb) wj@work:~/Project/yolov5-master$ python detect.py --weights yolov5n.pt --source ~/Data/others/cunBA.mp4 
Traceback (most recent call last):
  File "detect.py", line 45, in <module>
    from models.common import DetectMultiBackend
  File "/home/wj/Project/yolov5-master/models/common.py", line 28, in <module>
    from utils.dataloaders import exif_transpose, letterbox
  File "/home/wj/Project/yolov5-master/utils/dataloaders.py", line 31, in <module>
    from utils.augmentations import (Albumentations, augment_hsv, classify_albumentations, classify_transforms, copy_paste,
  File "/home/wj/Project/yolov5-master/utils/augmentations.py", line 15, in <module>
    from utils.general import LOGGER, check_version, colorstr, resample_segments, segment2box, xywhn2xyxy
  File "/home/wj/Project/yolov5-master/utils/general.py", line 41, in <module>
    from utils.metrics import box_iou, fitness
  File "/home/wj/Project/yolov5-master/utils/metrics.py", line 10, in <module>
    import matplotlib.pyplot as plt
  File "/home/wj/anaconda3/envs/climb/lib/python3.8/site-packages/matplotlib/__init__.py", line 131, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "/home/wj/anaconda3/envs/climb/lib/python3.8/site-packages/matplotlib/rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/home/wj/anaconda3/envs/climb/lib/python3.8/site-packages/matplotlib/colors.py", line 56, in <module>
    from matplotlib import _api, _cm, cbook, scale
  File "/home/wj/anaconda3/envs/climb/lib/python3.8/site-packages/matplotlib/scale.py", line 22, in <module>
    from matplotlib.ticker import (
  File "/home/wj/anaconda3/envs/climb/lib/python3.8/site-packages/matplotlib/ticker.py", line 138, in <module>
    from matplotlib import transforms as mtransforms
  File "/home/wj/anaconda3/envs/climb/lib/python3.8/site-packages/matplotlib/transforms.py", line 49, in <module>
    from matplotlib._path import (
ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/wj/anaconda3/envs/climb/lib/python3.8/site-packages/matplotlib/_path.cpython-38-x86_64-linux-gnu.so)

why?

### Environment

- YOLOv5 🚀 2023-4-10 Python-3.8.16 torch-1.10.1+cu113 CUDA:0 (NVIDIA GeForce RTX 3060, 12044MiB)
- OS: ubuntu 20.04
- python 3.8.16
- 

### Minimal Reproducible Example

Based on the source code, only yolov5n.pt was added, everything else was left unchanged.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@LiuQiTangli, the error message indicates that your matplotlib installation is incompatible with the system's libstdc++. The easiest way to solve this is to reinstall matplotlib via pip which should use the compatible dependencies. Please try running `pip install matplotlib --no-cache-dir --force-reinstall` to reinstall matplotlib and see if this solves the issue. 

If the issue persists or you have other questions, please let us know.

**Comment by ShAmoNiA** [comment]
Hi @LiuQiTangli,
I had this issue too.
It looks like there's an issue with the version of the C++ standard library that Matplotlib is trying to use. Basically, it needs a newer version than what's currently installed on your system.

To fix this, you can try updating your system's packages by running sudo apt-get update and sudo apt-get upgrade. Then, install the latest version of the C++ standard library by running sudo apt-get install libstdc++6.

If that doesn't work, you can try uninstalling and then reinstalling Matplotlib by running pip uninstall matplotlib and then pip install matplotlib.

At the end, all of above solutions didn't fix my problem; I changed my environment from Conda to Python's virtual environment and everything worked perfectly for me. Perhaps Conda was causing some difficulties with this issue.

**Comment by glenn-jocher** [comment]
Thank you for sharing your experience dealing with this issue @ShAmoNiA! Updating your system's packages and installing the latest C++ standard library can indeed help address compatibility issues with Matplotlib. And as you've mentioned, switching from Conda to a Python virtual environment or environment manager is worth considering if the issue persists. Sometimes, environment managers like Conda can interfere with path dependencies and cause issues like this.

**Comment by aylive** [comment]
I met the same problem under py3.10 + torch2.0, and here's the process I solve it,
1. The c++ package is required by an old matplotlib package, so first `pip install -U matplotlib`
2. Still doesn't work beacause a dependency package of matplotlib, `kiwisolver` is not automatically updated to the newest, so
(1) uninstall the package, `pip uninstall kiwisolver`
(2) reinstall it, `pip install -U kiwisolver`
That get solved. Hope this can be helpful.

**Comment by glenn-jocher** [comment]
Thank you for sharing your solution @aylive! We appreciate your contribution to resolving this issue. By upgrading `matplotlib` and ensuring `kiwisolver` is up-to-date, you were able to successfully address the problem. We will keep this solution in mind for future reference. If you have any further questions or encounter any other issues, please don't hesitate to let us know.

**Comment by emmanuelmoupojou2** [comment]
> @LiuQiTangli, the error message indicates that your matplotlib installation is incompatible with the system's libstdc++. The easiest way to solve this is to reinstall matplotlib via pip which should use the compatible dependencies. Please try running `pip install matplotlib --no-cache-dir --force-reinstall` to reinstall matplotlib and see if this solves the issue.
> 
> If the issue persists or you have other questions, please let us know.

This solved the issue for me. Thanks!

**Comment by glenn-jocher** [comment]
@emmanuelmoupojou2 great to hear that the suggested solution worked for you! We're glad that reinstalling Matplotlib using `pip install matplotlib --no-cache-dir --force-reinstall` resolved the compatibility issue with the system's libstdc++. If you have any further questions or encounter any other issues, please feel free to ask.

**Comment by KaimingZhu** [comment]
> I met the same problem under py3.10 + torch2.0, and here's the process I solve it,
> 
> 1. The c++ package is required by an old matplotlib package, so first `pip install -U matplotlib`
> 2. Still doesn't work beacause a dependency package of matplotlib, `kiwisolver` is not automatically updated to the newest, so
>    (1) uninstall the package, `pip uninstall kiwisolver`
>    (2) reinstall it, `pip install -U kiwisolver`
>    That get solved. Hope this can be helpful.

Thanks a lot, you save my day :)

**Comment by glenn-jocher** [comment]
@KaimingZhu i'm thrilled to hear that the solution worked for you! 😊 Big thanks for sharing your experience; it's greatly appreciated and could certainly help others in the community facing similar issues. Remember, we're here to help, so don't hesitate to reach out with more questions or insights. Happy coding!
