### ISSUE TITLE
Transformer module here has no position embedding, how do you learn position values?

### ISSUE THREAD

**Issue by ohjunee** [ultralytics/yolov5#11426]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

[yolov5s-transformer.yaml](https://github.com/ultralytics/yolov5/blob/master/models/hub/yolov5s-transformer.yaml)
[TransfomerLayer](https://github.com/ultralytics/yolov5/blob/master/models/common.py)
Transformer module here has no position embedding, how do you learn position values?

**Comment by glenn-jocher** [comment]
@ohjunee the transformer module in YOLOv5 does not require explicit positional embeddings, as the transformer attends to all positions directly. Instead, positional information is implicitly provided through the sequence order presented to the transformer. Therefore, the transformer does not require any explicit positional information to learn from the features. You can find more information about the transformer module in the YOLOv5 documentation at https://docs.ultralytics.com/YOLOv5/#transformers.

**Comment by ohjunee** [comment]
If you enter this link, you will receive an error message 404 not found.

**Comment by ohjunee** [comment]
@glenn-jocher [https://docs.ultralytics.com/YOLOv5/#transformers.](https://docs.ultralytics.com/YOLOv5/#transformers.) This link displays the error message 404 not found.

**Comment by glenn-jocher** [comment]
@ohjunee i apologize for the confusion, it seems that the documentation link I provided is outdated. You can find the current YOLOv5 documentation at https://docs.ultralytics.com/. Specifically, to learn more about the transformer module used in YOLOv5, you can visit https://docs.ultralytics.com/YOLOv5/v5.0/models.html#transformers. I hope this helps!
