### ISSUE TITLE
Question: Slow Inference on Google Coral Edge TPU

### ISSUE THREAD

**Issue by NickLojewski** [ultralytics/yolov5#11422]
Hello, I have a question regarding inference on the Google Coral Edge TPU. I have exported the model in the correct format and I am trying to run inference on the TPU, but experiencing slower than expected inference times.

```
yolov5 % python detect.py --weights yolov5s-int8_edgetpu.tflite --source test.mp4 --view-img
detect: weights=['yolov5s-int8_edgetpu.tflite'], source=test.mp4, data=data/coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=True, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
requirements: /Users/nick/Desktop/requirements.txt not found, check failed.
YOLOv5 🚀 v7.0-153-gff6a9ac Python-3.10.3 torch-2.0.0 CPU

Loading yolov5s-int8_edgetpu.tflite for TensorFlow Lite Edge TPU inference...
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
video 1/1 (1/359) /yolov5/test.mp4: 640x640 8 persons, 1 umbrella, 2 handbags, 2 suitcases, 800.0ms
...
```

It appears that the inference is relying on the Google Coral TPU to some degree because if I unplug the TPU during inference, the code errors out, but these speeds are nearly the same as if I was to run inference on CPU.

What could be going on here? Is this line:
`INFO: Created TensorFlow Lite XNNPACK delegate for CPU.` any indication that the TPU isn't being utilized correctly?
 Thanks for any help!

**Comment by glenn-jocher** [comment]
@NickLojewski hello! It sounds like the TPU is being recognized by TensorFlow Lite and used, since unplugging it during inference gives an error. However, the issue might be related to the fact that you are using `--half` argument, which enables half precision (float16) inference on the CPU. This can cause slower inference times on TPU since it requires converting the data back to float32 before sending it to the TPU. I recommend disabling this argument for TPU inference and see if it improves the performance. You can do this by using `--no-half` or setting `half=False` in code. Let me know if this helps!

**Comment by NickLojewski** [comment]
Hi @glenn-jocher ! Thanks so much for this guidance and explaining why --half can cause slower inference on TPUs.

This sped things up quite a bit, I am now down from ~800ms per frame to around ~360ms per frame on yolov5s-int8_edgetpu.tflite.

An open follow up question for glenn or other folks who have gotten around to playing with a Google Coral with yolov5 models... Do these speeds seem reasonable/typical or is there more room for me to tweak and get faster inference speeds?

**Comment by glenn-jocher** [comment]
@NickLojewski, you're welcome! 360 ms per frame on yolov5s-int8_edgetpu.tflite sounds reasonable and in line with the performance reported in the [Coral Edge TPU benchmarks](https://coral.ai/docs/edgetpu/benchmarks/). *Note* that performance will be affected by factors such as model size, the type of input image (e.g. resolution), and the number of objects in the image. It's worth considering [quantization-aware training](https://github.com/ultralytics/yolov5/issues/2120) for further optimization, which can significantly reduce the model size and inference time on Edge TPUs. Finally, make sure that the Coral Accelerator Runtime (car) is up-to-date to ensure maximum performance. For more details about the acceleration of the Coral Edge TPU, visit the [Coral Examples repo](https://github.com/google-coral/examples-camera).

**Comment by NickLojewski** [comment]
@glenn-jocher Thanks you for the guidance! Closing this issue now as resolved.

**Comment by glenn-jocher** [comment]
@NickLojewski You're welcome! Don't hesitate to reach out if you have any more questions or issues in the future. Have a great day!
