### ISSUE TITLE
Some detail about  FPS

### ISSUE THREAD

**Issue by baowenshuwh** [ultralytics/yolov5#11424]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, your documentation has instructions for speed calculations: python val.py --data coco.yaml --img 640 --task speed --batch 1.(NMS times (~1 ms/img) not included) .   Is YOLOv5 FPS 1000//speed?

**Comment by glenn-jocher** [comment]
@baowenshuwh hello! The speed parameter in YOLOv5's validation script `val.py` estimates the inference time per image and is not directly related to FPS. The FPS can vary depending on the hardware and software specifications you are using for inference, as well as the batch size you are processing. In general, you can use the formula `FPS = 1 / (inference time per image)` to estimate the FPS based on the speed output from `val.py`. Let me know if you have any further questions or need additional help!
