### ISSUE TITLE
If I want to use Yolov5 to train coco2017 data , do I need to turn JSON files into  TXT files?

### ISSUE THREAD

**Issue by xinxin342** [ultralytics/yolov5#1143]
## ❔Question
If I want to use Yolov5 to train coco2017 data , do I need to turn JSON files into  TXT files?

**Comment by melgor** [comment]
This one convertion works for me: https://github.com/ssaru/convert2Yolo

**Comment by glenn-jocher** [comment]
@xinxin342 @melgor YOLOv5 will autodownload COCO 2017 data (in the correct format) on first use, there is no action required on your part.

```bash
python train.py --data coco.yaml
```

**Comment by melgor** [comment]
Thanks for pointing it out. I was using linked repo for converting my custom dataset.

**Comment by longswordinhand** [comment]
There are two ways to convert json file to yolo label:
https://github.com/ultralytics/COCO2YOLO 
https://github.com/ssaru/convert2Yolo
