### ISSUE TITLE
Output of YOLOv5-cls

### ISSUE THREAD

**Issue by Pop469** [ultralytics/yolov5#11436]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I'm getting a bunch of tensor values from my training model of YOLOv5-cls. The classification algorithm is relatively new and there are not much information available online yet. How should I interpret the values obtained from `y_pred = model(X)` ?

y_pred is returning a list of tensor values, and y_pred_class is returning a tensor value far beyond the number of classes.

Below are a snippet of my code:
`
    # Put model in train mode
    model.train()
    
    # Setup train loss and train accuracy values
    train_loss, train_acc = 0, 0
    
    # Loop through data loader data batches
    for batch, (X, y) in tqdm(enumerate(dataloader), total=len(dataloader), desc="Training"):
        # 1. Forward pass
        y_pred = model(X)

        # 2. Calculate and accumulate loss
        loss = loss_fn(y_pred.float(), y)
        loss = torch.tensor(loss, requires_grad = True)
        train_loss += loss.item() 

        # 3. Optimizer zero grad
        optimizer.zero_grad()

        # 4. Loss backward
        loss.backward()

        # 5. Optimizer step
        optimizer.step()

        # Calculate and accumulate accuracy metric across all batches
        y_pred_class = torch.argmax(torch.softmax(y_pred, dim=1), dim=1)
        train_acc += (y_pred_class == y).sum().item()/len(y_pred)

        #Display result
        print(f"Image #{batch+1}: {y}, {y_pred_class}")
`

Thanks in advanced!

### Additional

I am using VS Code to develop the algorithm, and am not familiar with command line script. Therefore, I apologise if there is an answer to solve my issue in CLS format that I don't quite get.

For reference, this is one of the output i got from y_pred, after passing through model(X):
`tensor([[-5.14512e-01,  6.83175e-01,  1.33731e-01,  1.31418e-01,  1.34558e+00,  1.72234e+00,  6.29245e-01, -2.76728e-01, -3.96464e-01, -1.60593e+00, -1.33281e+00, -1.59161e+00, -1.25221e+00, -1.29412e+00, -1.67162e+00, -8.15163e-01, -4.11459e-01, -1.67414e+00, -1.02704e+00, -1.45576e+00, -4.19274e-02, -1.76491e+00,
         -1.99907e+00, -8.70010e-01, -1.45208e+00, -1.23092e+00, -1.31659e-01, -1.22837e+00, -1.46729e+00,  2.48905e+00, -1.01842e+00, -4.29105e-01, -5.31719e-01,  1.69529e-02, -8.16940e-02, -1.87356e+00, -3.89697e-01, -5.66070e-01, -6.05016e-01, -6.00404e-01, -1.25715e+00, -8.17634e-02, -1.30800e+00, -5.35502e-01,
         -1.06091e+00, -1.84973e-01, -7.68127e-01,  1.34765e+00, -1.03045e+00, -1.98930e+00, -1.05120e+00, -8.50523e-01,  4.74759e-01, -2.42222e-01, -4.85779e-01, -4.11947e-01, -2.03746e-01, -2.60910e-01, -4.74144e-01, -9.62932e-02, -3.92410e-02, -4.02087e-01, -7.60520e-01, -1.55903e+00, -8.34840e-01, -1.14693e+00,
         -3.49327e-01, -4.91894e-01, -3.71789e-01, -2.05352e+00, -1.32119e+00, -8.11938e-02, -1.23688e+00, -7.22322e-01, -7.36215e-01, -1.37780e+00, -1.57909e-01, -7.91456e-01, -1.24680e+00,  1.72130e-01, -4.68714e-01,  1.36435e-03, -9.80313e-01, -6.21965e-01, -1.67247e+00, -1.24952e+00, -5.68711e-01, -1.62076e+00,
         -2.31079e+00, -7.12164e-01, -1.06880e+00, -8.49919e-01, -1.60569e+00, -1.38442e+00, -1.07755e+00,  3.51106e-01,  7.52479e-01, -4.71619e-01, -8.27661e-01, -6.24508e-01,  1.23073e-01, -1.05973e+00, -2.94044e-01, -1.12508e+00,  
1.14799e-01, -7.13350e-01, -9.52854e-01,  6.69980e-01,  1.36232e+00, -8.91613e-01,
         -1.26602e+00, -1.01423e-01, -9.23608e-01, -9.59819e-01, -5.90121e-01,  1.50757e-01, -1.28273e+00,  4.23033e-01,  5.20044e-01, -1.08290e+00,  6.29006e-01, -7.76553e-01, -5.21117e-02, -3.93770e-01,  1.59957e+00,  5.04155e-01,  
9.02947e-01, -1.70559e+00, -4.51658e-01, -4.16221e-01, -2.43925e-01, -1.35726e+00,
          1.47533e-01, -9.86386e-02, -1.84491e+00, -2.66352e-01, -8.82978e-01,  7.00455e-02, -7.00360e-01, -8.31534e-01, -1.63453e+00, -1.67428e+00, -1.22477e+00, -1.10187e+00,  1.49950e-01,  2.34824e-03,  7.78651e-01,  7.89358e-01,  
1.69747e+00,  2.46681e+00, -2.54968e-01,  4.83818e-01, -4.97825e-01,  7.59155e-01,
         -5.21215e-01, -1.45314e+00, -1.33149e+00, -2.84575e-01, -1.67948e-02, -1.98739e+00, -9.63865e-01, -1.03455e+00,  2.55401e-01, -9.13581e-01, -6.50095e-01, -5.67324e-01,  1.48173e-01, -4.32859e-01,  3.67979e-01, -7.33210e-01, -8.87854e-01,  8.20065e-01,  2.32341e-02, -1.07770e-03, -7.40359e-01, -1.06279e+00,
          2.74602e-01, -1.20818e+00, -6.16137e-01, -6.42228e-01, -3.76829e-01, -6.98775e-02, -1.75990e-02, -6.37745e-02, -6.81303e-01, -8.18967e-01, -5.25724e-01, -2.34785e-01, -1.14473e+00, -1.21579e+00, -8.26481e-01, -7.35828e-01, -9.90364e-01, -4.40579e-01, -1.42950e+00,  7.38132e-01,  2.60850e-02, -1.03134e+00,
         -1.45330e+00,  5.49119e-01, -1.76081e+00, -1.48322e+00, -4.77100e-01,  4.12660e-02, -7.77403e-01, -2.59639e-01, -3.04864e-01, -2.59994e-01, -4.65384e-02, -5.02703e-01, -1.60789e+00, -5.17778e-01, -1.40314e+00, -2.79951e-01,  
1.06023e-01, -1.25732e+00, -1.45280e+00, -2.76099e-01, -1.69754e+00, -2.02688e+00,
         -1.34003e+00, -4.95195e-01,  2.13042e-01,  2.66346e-01,  7.57700e-01, -8.05800e-01, -3.25655e-01, -3.74358e-01, -3.31882e-01, -6.34956e-01, -7.09174e-01, -1.23184e+00, -1.00936e+00, -5.60843e-01,  5.01182e-01, -1.70373e-01, -4.87407e-01,  9.46048e-01, -1.17981e-01, -2.67536e-01, -4.75834e-01, -7.66042e-01,
          8.99287e-01, -1.35127e+00,  1.69679e-01,  2.80488e-01, -7.01563e-01, -1.51728e+00, -3.46971e-01,  1.31754e-01, -3.33209e-01, -8.94431e-01,  1.87754e-02,  2.20804e-01,  1.18135e+00, -1.27775e+00,  3.66391e-01,  6.64786e-01,  
7.95706e-01,  3.72355e-01,  2.96411e-01, -1.20073e+00, -1.45602e+00, -6.66286e-01,
         -1.90750e+00,  9.80772e-01,  6.71295e-01,  2.64258e-01, -7.73978e-01, -3.52231e-01, -4.98632e-02, -4.92909e-01, -1.08730e+00, -4.28032e-01, -4.23054e-01,  4.35961e-02, -8.87154e-01, -5.93339e-01, -9.82695e-01,  3.66609e-01, -7.78784e-02, -6.63388e-01, -1.99974e+00, -1.74123e+00, -2.87804e-01, -9.64155e-01,
         -1.24409e+00, -5.53178e-02, -8.47024e-01, -1.13196e+00, -2.10902e-01, -9.00742e-01, -1.09067e+00, -6.87340e-01,  2.52411e-01,  6.58524e-03,  8.73800e-01, -4.00275e-01, -3.01898e-01, -1.48981e+00, -7.59504e-01, -2.15093e-01, -9.33674e-01,  5.55071e-02, -4.20648e-02, -8.49370e-01,  2.61542e-01,  1.19615e+00,
         -1.94725e-01,  1.79327e+00,  7.94657e-01, -5.99981e-01, -1.44882e+00, -1.22621e+00, -1.32880e-01, -5.00790e-01,  5.28182e-01, -2.17305e-01,  5.30920e-02, -6.99622e-01, -1.33721e+00, -9.91096e-01,  6.70018e-01, -3.51592e-01, -7.22901e-01, -1.39686e-01, -5.89614e-01, -7.08311e-01, -7.65897e-01,  8.89211e-01,
         -7.07281e-01,  3.84775e-01, -7.14382e-01,  2.31780e-01, -2.77672e-01, -2.81967e-01,  5.11710e-01,  2.85211e-02, -1.26271e+00, -4.25127e-01, -7.77426e-01,  9.60676e-01,  1.28082e-02, -1.05070e+00, -2.01651e+00, -3.32014e-01, -1.20773e+00,  8.00862e-01, -6.11828e-01, -1.01866e+00, -4.04577e-01, -1.77193e+00,
         -9.41741e-01,  1.53343e-01,  3.95693e-01, -2.17352e-01,  7.11662e-03, -1.42043e-01,  1.34291e+00, -1.02920e-01, -9.36698e-01, -1.14360e+00, -3.10666e-01, -2.65483e-01, -6.41831e-01,  3.08129e-01, -1.42153e+00,  3.76143e-01, -1.06321e+00, -1.24198e-01, -1.23608e+00, -1.26342e+00, -3.30110e-01, -2.15511e+00,
         -2.42711e+00, -1.98550e+00, -1.53737e+00, -7.73043e-01,  4.10556e-01, -1.16935e-01,  6.99736e-01, -1.23342e+00, -3.11034e-01, -1.38267e+00, -4.09437e-01, -9.38603e-01, -6.02192e-01, -2.18195e-01, -7.49149e-02,  8.27733e-01, -9.65257e-01,  1.26448e+00, -1.10953e+00,  1.69236e+00,  1.43224e+00,  8.31177e-01,
          1.02485e-01, -1.52092e+00, -9.56841e-02,  1.20097e+00,  1.57508e-01, -2.44019e-01, -1.12184e+00,  8.10556e-01,  5.92870e-01,  1.21671e+00, -1.75068e+00,  4.22199e-01,  9.68455e-01, -1.01406e+00,  3.91404e-01, -3.97379e-01,  
1.88381e+00,  8.45511e-01,  4.79066e-01,  3.94518e-01,  1.95653e-01, -1.62884e-01,
          5.52618e-01,  1.90297e+00, -1.05655e+00, -6.55232e-01, -1.02954e+00,  1.20810e-01,  1.33172e+00, -7.76476e-01, -2.18109e+00, -1.52493e+00, -8.67191e-01, -1.22804e+00, -1.87633e+00,  5.07736e+00,  1.15020e-01,  1.27712e+00,  
2.29525e+00,  4.72006e+00,  1.61168e+00, -1.74087e+00,  2.50085e+00, -2.03806e+00,
         -3.44160e-01, -1.48865e-01, -4.94886e-01,  5.91523e-01, -6.04373e-01,  2.94457e+00, -3.05849e-01,  8.39220e-01, -1.10239e+00, -4.28320e-01, -1.68819e+00, -7.42525e-01,  3.11734e+00, -4.29668e-01, -4.21251e-01, -2.31334e+00,  
1.17398e+00,  4.11683e-01, -1.58741e+00,  3.69682e+00,  1.72178e-01, -1.20744e+00,
          1.26269e+00,  1.02779e+00, -1.27416e+00,  9.83485e-01,  2.95343e+00, -1.01554e+00,  1.87737e-01,  5.21217e-01,  1.63937e+00,  7.03353e-01,  4.03969e-01,  1.64062e+00, -7.11258e-01,  2.92226e+00,  1.70202e+00, -4.11472e-01,  
1.93374e+00,  1.44771e+00,  5.59050e-01, -2.26275e-01,  4.52695e-01, -1.28393e+00,
          1.40705e+00, -3.46929e-02, -7.09379e-01,  1.84290e+00, -1.09481e+00, -6.94176e-01, -1.06794e+00, -2.08999e+00,  1.38094e+00, -3.14914e-01, -1.60188e+00, -3.31231e-01,  1.60222e-01, -7.31842e-01, -1.29111e+00,  6.21251e-01, -2.34268e-01,  4.06415e-01, -1.02690e+00,  3.01792e-01, -1.57727e-01,  1.09746e-01,
         -1.14093e+00, -2.09070e+00,  5.06934e-01,  7.50439e-01, -1.46393e-01,  2.62471e+00,  5.31739e-01,  4.16893e-01, -4.79243e-01,  2.67410e-01,  4.37180e+00, -1.43296e+00, -2.00424e-01,  9.49993e-02,  4.65613e+00, -1.04701e-01, -4.87839e-01,  1.06591e+00, -2.97151e+00, -1.12982e+00, -2.19880e-01, -2.28180e-01,
          1.05645e+00,  5.49973e+00, -7.10207e-01, -3.17539e-01, -5.61460e-02,  7.40772e-01,  1.68656e+00, -9.17021e-01, -9.39813e-01, -2.09817e+00, -4.30708e-01, -1.56255e+00, -1.40068e+00, -2.14381e+00,  3.65120e-01, -1.56729e-01, -1.82494e-01,  1.28102e+00, -1.35745e+00, -7.66857e-01, -6.05733e-01,  1.30876e+00,
         -1.60388e+00,  8.00354e-01,  3.43535e-01,  2.64980e-01,  1.31769e-01, -2.20446e-01, -1.59886e+00, -6.50717e-01,  1.04500e+00,  3.94293e-01, -4.25360e-01, -1.91806e+00, -6.59705e-01, -6.26903e-01,  1.50366e+00, -5.53136e-01,  
5.34482e-01,  5.76642e-01, -1.01540e+00,  7.43105e-01,  1.81991e+00, -1.26693e+00,
          7.91172e-01, -1.51314e+00, -8.19038e-01,  1.47515e+00, -2.18856e-01, -8.01852e-01,  1.85866e+00, -2.24526e-01,  2.95209e-01,  1.00968e+00,  3.39561e-01, -1.57720e+00,  1.09664e+00,  2.31947e+00,  5.76389e-01, -1.34957e-01,  
2.47543e+00,  3.17330e+00,  2.94220e-01,  1.61816e+00, -1.32807e+00, -3.28258e-01,
         -1.80083e+00, -1.06505e+00,  2.96606e-01, -2.11553e-01,  3.94704e-01, -6.06178e-02,  7.57936e-01,  1.54040e+00,  1.06876e+00, -1.23981e-01,  6.50621e-01,  2.36347e+00,  4.06085e+00, -9.27084e-01,  1.89393e+00,  1.99159e-01, -3.55744e-03, -4.08572e-01, -6.46538e-01, -2.83817e-01,  8.36426e-01, -4.04933e-01,
          7.97116e-01,  3.39294e+00,  1.18432e+00,  1.29595e+00,  6.83402e-01, -7.06845e-01, -4.01594e-01,  9.87429e-01, -7.59604e-01,  5.80229e-02,  4.23045e-01,  2.79128e+00,  1.47076e-01,  9.92121e-01,  1.06414e+00,  3.03851e+00, -2.58709e-01,  2.81512e-01, -1.76176e+00, -4.75472e-01,  1.80727e+00, -8.07930e-02,
          2.50287e+00,  1.32822e+00, -7.22191e-01,  2.10142e-01, -6.66571e-01, -1.25715e+00,  6.72268e-01, -5.20563e-01, -2.95017e-01,  1.53494e+00, -1.00721e-01, -2.90345e-01,  5.38388e-01,  2.45216e-01,  9.50570e-01, -6.25953e-01,  
1.14379e+00,  2.61328e+00,  3.43718e+00,  1.78537e+00, -3.01543e-01,  2.16449e+00,
         -1.37822e+00,  3.11567e-01, -1.34516e-02, -2.04138e+00,  1.55658e+00, -1.08823e+00,  1.71998e+00,  9.39008e-01, -7.83754e-01,  3.81559e+00,  7.11340e-01,  2.18118e-01,  9.84353e-01,  7.31747e-01, -4.07582e-01, -4.51344e-01, -6.72429e-01, -1.27857e+00,  2.17291e+00, -5.88723e-01,  3.39165e+00,  1.23155e+00,
         -6.67771e-01,  6.39550e-01, -1.64836e+00,  4.70342e-01, -1.07617e+00, -8.77025e-01, -9.52527e-01,  2.05248e-01,  5.34827e-03,  6.04421e+00,  1.08639e+00,  1.87964e-02,  1.52171e-01, -1.73865e+00,  3.94692e+00,  1.29132e+00, -1.64322e+00, -7.55954e-01,  3.69355e+00,  2.08250e+00,  7.51481e-01, -8.22975e-01,
          8.77216e-01, -6.78861e-01, -1.17569e+00, -8.43015e-01, -8.29408e-01, -9.11835e-02,  1.16376e-01,  8.06081e-01,  2.26972e+00,  1.25868e+00, -1.22154e+00, -2.26961e+00, -9.13179e-01,  1.07772e+00, -5.77291e-01,  2.04202e+00,  
3.31951e-01,  1.83317e+00, -1.00010e+00,  1.95771e+00, -1.27009e-01,  5.55528e-01,
         -6.91100e-01,  8.78930e-01,  3.23703e+00, -3.24119e-01, -5.96890e-01,  2.14959e+00, -7.76658e-01,  1.83911e-02, -3.85290e-01,  1.14426e+00, -4.66804e-01, -8.76682e-01, -1.43197e+00,  1.44797e+00, -5.46870e-01, -3.26424e-01,  
1.12563e+00, -1.07322e+00,  2.52850e+00,  2.32732e+00, -1.60253e+00, -3.39773e-01,
          1.14077e+00,  1.50122e+00,  2.07821e+00, -5.88786e-02, -4.78926e-01,  4.02937e-02, -6.59544e-01, -1.35941e-01,  2.01244e-01,  1.07988e-01,  5.68546e-01, -7.15990e-01,  1.65973e+00,  1.54994e+00,  2.00640e+00,  3.97142e-01,  
1.71617e+00,  1.08363e+00, -9.52201e-01, -7.11492e-01, -1.20270e+00, -2.31002e-01,
          1.71145e-01, -2.11978e-01,  5.78477e-01, -8.23241e-01,  5.14176e-01,  9.61637e-01, -1.35915e+00, -1.14711e-01,  5.39181e-01,  2.28603e-01,  1.47150e+00, -1.08173e+00,  1.46260e+00, -7.85290e-01, -8.70145e-01,  5.22475e+00,  
2.58973e+00, -2.37159e+00,  1.42816e+00, -1.93296e-01,  1.03281e+00,  2.55376e-01,
          6.51526e-01,  4.30128e+00,  3.66270e+00, -1.32903e+00,  6.24457e-01,  9.29575e-01, -1.04421e+00,  2.55274e-01, -1.40474e+00,  3.01366e+00, -1.15443e+00, -8.08375e-03,  1.13253e+00, -9.00077e-01, -6.58974e-01, -2.93530e-01, -1.78079e-01,  1.78985e+00, -2.95733e-01, -6.71151e-01, -1.86665e-01,  1.22146e+00,
          7.19733e-01, -2.20396e+00,  1.42403e+00,  1.09452e+00,  1.40353e+00, -5.40122e-01, -6.00547e-01, -1.00670e+00, -1.87810e+00,  2.73766e+00,  2.57610e-01, -1.68248e-01,  4.54116e-02, -1.90709e+00,  2.71630e+00, -1.23154e+00,  
2.53593e+00,  2.45765e+00, -2.68166e-01,  6.93046e-01,  6.35470e-01, -2.52814e+00,
          2.69507e+00,  2.31808e+00,  3.00344e+00, -9.59216e-01,  1.75271e+00, -3.33763e-01,  1.80169e+00,  5.78405e-01, -1.00893e+00,  3.27380e+00,  8.68189e-01,  1.02469e+00, -4.64216e-01,  1.02175e+00, -4.55795e-01,  1.21593e+00,  
6.44104e-02, -6.36404e-01, -1.62492e+00, -1.70539e+00, -9.60360e-01, -2.12465e+00,
         -1.13982e+00,  5.18191e-01, -1.96177e+00,  2.46977e+00,  4.11967e-01, -2.32977e+00, -3.51484e-01,  9.06077e-01, -9.11377e-01,  1.40093e-01,  5.43315e-01,  3.51297e-01, -1.71704e-01,  1.53795e+00, -3.27157e-01, -8.55308e-01, -1.06271e+00,  3.49266e-01,  5.20357e+00, -1.42396e+00,  5.11536e-01,  2.85480e+00,
          8.52531e-01, -1.70257e+00,  2.09292e+00, -5.69570e-03,  2.95963e-01,  3.19194e-01, -1.15696e+00, -9.99658e-01, -1.36978e-01, -5.81589e-02, -1.16804e+00, -2.58100e-01,  9.65930e-01, -9.83159e-01,  1.45513e+00,  2.24689e+00,  
2.25418e+00,  3.43501e+00,  8.24835e-01,  1.75585e+00, -7.75171e-01, -1.06028e+00,
          9.84522e-01, -2.64525e-02,  4.00844e-01,  1.38040e+00,  8.08584e-01, -7.36608e-01,  8.29155e-01,  7.16883e-01,  1.92852e+00, -6.17349e-01, -3.08052e-01, -1.50255e-01,  7.41179e-01, -1.23566e-01,  3.45460e-01, -7.38970e-01,  
6.17271e-01, -1.39701e+00, -2.03087e+00, -1.79438e+00,  1.02380e+00,  2.74768e+00,
          1.21388e+00,  2.71545e+00,  2.10668e-01,  4.65299e-01,  1.31145e+00,  2.42579e+00, -9.53479e-01, -1.22211e-01,  1.14471e+00,  1.19221e+00,  2.27467e+00, -8.43460e-02,  1.11825e+00,  2.40119e-01,  5.46221e-01,  2.71741e-01, -1.96279e-01,  5.88176e-02,  2.97511e-01, -2.36993e-01, -1.98900e-01, -4.62331e-01,
         -7.89310e-01, -2.57684e-01, -1.11048e-01, -3.56650e-03, -1.55442e-01, -9.98836e-01,  1.98453e-01, -8.32106e-01,  5.72283e-01,  4.14107e-01, -5.89531e-01, -7.93606e-01,  6.72142e-02,  6.46633e-01,  1.71915e+00,  1.37863e+00, -9.34547e-01, -1.12378e+00, -2.77318e-01,  1.65746e+00,  3.20650e-01, -9.19004e-02,
          1.32779e+00,  1.49004e+00,  5.03922e-01,  2.16410e+00,  1.74469e-01, -2.48669e-01, -1.11719e+00,  1.38320e+00, -2.92225e-01,  1.22943e+00, -5.78503e-01, -6.83771e-02, -2.78004e-01, -6.73558e-01,  3.24823e+00,  7.80112e-01,  
1.37380e+00, -6.48299e-01, -8.27994e-01, -1.94953e-01, -1.02799e+00, -6.34256e-01,
         -1.90422e+00, -2.55715e-01, -1.05660e+00, -1.18006e+00, -1.50605e+00, -1.74972e+00,  3.87790e-02, -1.90374e+00,  4.67859e-01,  3.42247e+00]])`

And this is an output I got from y_pred_class (I only have 10 classes):
`tensor([691])`

**Comment by glenn-jocher** [comment]
@Pop469 hi there,

The y_pred tensor values correspond to the raw output of your model. You can interpret these as confidence scores for each class. To obtain class predictions, you should apply a softmax function along the class dimension, then take the argmax along the same dimension to obtain the predicted class indices.

Regarding your second question, the y_pred_class tensor should contain the predicted class indices for each input. In case you're getting unexpected results, make sure to verify your label encoding and that the number of classes and class indices match.

I hope this helps! For a more detailed explanation, you can refer to the Ultralytics Docs at https://docs.ultralytics.com/yolov5/.

Best regards.
