### ISSUE TITLE
Error when classnames are a number

### ISSUE THREAD

**Issue by davidsasso** [ultralytics/yolov5#11439]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

I had an error trying to make detections.

I got the following error caused in line 754 in models/common.py: 

`TypeError: unsupported operand type(s) for /:'WindowsPath' and 'int'`

Line 754 in models/common.py was:

`file = save_dir / 'crops' / self.names[int(cls)] / self.files[i] if save else None`

And I named my classnames on training as 02146, 21008 and 21010 and had no problem in training process.

I could tell that it was something on concatenating some string so I tried editing the line 754 to be:

`file = save_dir / 'crops' / str(self.names[int(cls)]) / self.files[i] if save else None`

And it worked.

I did not see anything related to naming classnames as only numeric characters inside the issues section.

Maybe this line could be updated, or just be careful as user to avoid naming classnames as a only number convention.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@davidsasso - [X] No, I'm not able to submit a PR at the moment.
