### ISSUE TITLE
Load YOLOv5 from PyTorch Hub - TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by yeongnamtan** [ultralytics/yolov5#11448]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

PyTorch Hub

### Bug

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-656b02fa04be> in <module>
      4 #model = torch.hub.load('ultralytics/yolov5', 'custom', path='path/to/best.pt')
      5 
----> 6 model = torch.hub.load('ultralytics/yolov5', 'custom', path='/root/Yolov5_DeepSort_Pytorch/weights/best_Yolov5l_06April2023.pt',force_reload=True)  #download the yolov model and weights for detection later
      7 
      8 

/opt/conda/lib/python3.9/site-packages/torch/hub.py in load(repo_or_dir, model, source, trust_repo, force_reload, verbose, skip_validation, *args, **kwargs)
    540                                            verbose=verbose, skip_validation=skip_validation)
    541 
--> 542     model = _load_local(repo_or_dir, model, *args, **kwargs)
    543     return model
    544 

/opt/conda/lib/python3.9/site-packages/torch/hub.py in _load_local(hubconf_dir, model, *args, **kwargs)
    570 
    571     entry = _load_entry_from_hubconf(hub_module, model)
--> 572     model = entry(*args, **kwargs)
    573 
    574     sys.path.remove(hubconf_dir)

~/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py in custom(path, autoshape, _verbose, device)
     81 def custom(path='path/to/model.pt', autoshape=True, _verbose=True, device=None):
     82     # YOLOv5 custom or local model
---> 83     return _create(path, autoshape=autoshape, verbose=_verbose, device=device)
     84 
     85 

~/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py in _create(name, pretrained, channels, classes, autoshape, verbose, device)
     31     from pathlib import Path
     32 
---> 33     from models.common import AutoShape, DetectMultiBackend
     34     from models.experimental import attempt_load
     35     from models.yolo import ClassificationModel, DetectionModel, SegmentationModel

~/.cache/torch/hub/ultralytics_yolov5_master/models/common.py in <module>
     18 import cv2
     19 import numpy as np
---> 20 import pandas as pd
     21 import requests
     22 import torch

/opt/conda/lib/python3.9/importlib/_bootstrap.py in _find_and_load(name, import_)

/opt/conda/lib/python3.9/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/opt/conda/lib/python3.9/importlib/_bootstrap.py in _find_spec(name, path, target)

<ipython-input-1-6c34bcb55ced> in find_spec(self, fullname, path, target)
     29         if fullname == 'pandas':
     30             dw = DiscoveryWidget()
---> 31             display(dw)
     32         return None
     33 

**TypeError: 'module' object is not callable**

### Environment

-Python 3.9.0
-Pytorch 1.13

### Minimal Reproducible Example

import torch
model = torch.hub.load('ultralytics/yolov5', 'custom', path='/root/Yolov5_DeepSort_Pytorch/weights/best_Yolov5l_06April2023.pt')  

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-656b02fa04be> in <module>
      4 #model = torch.hub.load('ultralytics/yolov5', 'custom', path='path/to/best.pt')
      5 
----> 6 model = torch.hub.load('ultralytics/yolov5', 'custom', path='/root/Yolov5_DeepSort_Pytorch/weights/best_Yolov5l_06April2023.pt',force_reload=True)  #download the yolov model and weights for detection later
      7 
      8 

/opt/conda/lib/python3.9/site-packages/torch/hub.py in load(repo_or_dir, model, source, trust_repo, force_reload, verbose, skip_validation, *args, **kwargs)
    540                                            verbose=verbose, skip_validation=skip_validation)
    541 
--> 542     model = _load_local(repo_or_dir, model, *args, **kwargs)
    543     return model
    544 

/opt/conda/lib/python3.9/site-packages/torch/hub.py in _load_local(hubconf_dir, model, *args, **kwargs)
    570 
    571     entry = _load_entry_from_hubconf(hub_module, model)
--> 572     model = entry(*args, **kwargs)
    573 
    574     sys.path.remove(hubconf_dir)

~/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py in custom(path, autoshape, _verbose, device)
     81 def custom(path='path/to/model.pt', autoshape=True, _verbose=True, device=None):
     82     # YOLOv5 custom or local model
---> 83     return _create(path, autoshape=autoshape, verbose=_verbose, device=device)
     84 
     85 

~/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py in _create(name, pretrained, channels, classes, autoshape, verbose, device)
     31     from pathlib import Path
     32 
---> 33     from models.common import AutoShape, DetectMultiBackend
     34     from models.experimental import attempt_load
     35     from models.yolo import ClassificationModel, DetectionModel, SegmentationModel

~/.cache/torch/hub/ultralytics_yolov5_master/models/common.py in <module>
     18 import cv2
     19 import numpy as np
---> 20 import pandas as pd
     21 import requests
     22 import torch

/opt/conda/lib/python3.9/importlib/_bootstrap.py in _find_and_load(name, import_)

/opt/conda/lib/python3.9/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/opt/conda/lib/python3.9/importlib/_bootstrap.py in _find_spec(name, path, target)

<ipython-input-1-6c34bcb55ced> in find_spec(self, fullname, path, target)
     29         if fullname == 'pandas':
     30             dw = DiscoveryWidget()
---> 31             display(dw)
     32         return None
     33 

TypeError: 'module' object is not callable

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by yeongnamtan** [comment]
this is my code:

import torch
model = torch.hub.load('ultralytics/yolov5', 'custom', path='/root/Yolov5_DeepSort_Pytorch/weights/best_Yolov5l_06April2023.pt')

**Comment by glenn-jocher** [comment]
@yeongnamtan hello! Thank you for using YOLOv5. 

Regarding your code, it seems like you are loading a custom YOLOv5 model stored in `/root/Yolov5_DeepSort_Pytorch/weights/best_Yolov5l_06April2023.pt`. Make sure that path is correct and that the model is stored properly in that directory.

If you encounter any issues or have further questions, feel free to let us know.

**Comment by yeongnamtan** [comment]
I confirm the path is correct.  The code was working last week.

**Comment by glenn-jocher** [comment]
@yeongnamtan hello! Thank you for using YOLOv5.

If the code was working properly last week and you have not made any changes since then, it is possible that there might be an issue with the installation or environment. Try to reinstall the YOLOv5 package or check if any dependencies need to be updated.

Also, check if any system updates or changes have been made recently that could be affecting the YOLOv5 setup.

If the issue persists, please provide any error messages or additional information you have encountered.

Let us know if there's anything else we can help with!

**Comment by glenn-jocher** [comment]
@yeongnamtan it works for me in Colab:

<img width="752" alt="Screenshot 2023-04-28 at 00 52 56" src="https://user-images.githubusercontent.com/26833433/235007587-4e2bef81-7ddc-48fc-b0be-cab252ea341c.png">

**Comment by yeongnamtan** [comment]
i tried on google colab and get this error:


import torch
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')


~~~
Using cache found in /root/.cache/torch/hub/ultralytics_yolov5_master
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-14-0b150b764e1d> in <module>
      1 import torch
      2 
----> 3 model = torch.hub.load('ultralytics/yolov5', 'yolov5s')
      4 #model = torch.hub.load('ultralytics/yolov5', 'custom', path='path/to/best.pt')
      5 

/opt/conda/lib/python3.8/site-packages/torch/hub.py in load(repo_or_dir, model, source, trust_repo, force_reload, verbose, skip_validation, *args, **kwargs)
    538                                            verbose=verbose, skip_validation=skip_validation)
    539 
--> 540     model = _load_local(repo_or_dir, model, *args, **kwargs)
    541     return model
    542 

/opt/conda/lib/python3.8/site-packages/torch/hub.py in _load_local(hubconf_dir, model, *args, **kwargs)
    567 
    568     entry = _load_entry_from_hubconf(hub_module, model)
--> 569     model = entry(*args, **kwargs)
    570 
    571     sys.path.remove(hubconf_dir)

~/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py in yolov5s(pretrained, channels, classes, autoshape, _verbose, device)
     91 def yolov5s(pretrained=True, channels=3, classes=80, autoshape=True, _verbose=True, device=None):
     92     # YOLOv5-small model https://github.com/ultralytics/yolov5
---> 93     return _create('yolov5s', pretrained, channels, classes, autoshape, _verbose, device)
     94 
     95 

~/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py in _create(name, pretrained, channels, classes, autoshape, verbose, device)
     31     from pathlib import Path
     32 
---> 33     from models.common import AutoShape, DetectMultiBackend
     34     from models.experimental import attempt_load
     35     from models.yolo import ClassificationModel, DetectionModel, SegmentationModel

~/.cache/torch/hub/ultralytics_yolov5_master/models/common.py in <module>
     18 import cv2
     19 import numpy as np
---> 20 import pandas as pd
     21 import requests
     22 import torch

/opt/conda/lib/python3.8/importlib/_bootstrap.py in _find_and_load(name, import_)

/opt/conda/lib/python3.8/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/opt/conda/lib/python3.8/importlib/_bootstrap.py in _find_spec(name, path, target)

<ipython-input-1-0a658baa7257> in find_spec(self, fullname, path, target)
     29         if fullname == 'pandas':
     30             dw = DiscoveryWidget()
---> 31             display(dw)
     32         return None
     33 

TypeError: 'module' object is not callable

**Comment by glenn-jocher** [comment]
@yeongnamtan hello! 

It looks like there is an error occurring when trying to load the YOLOv5 model on Google Colab, specifically when trying to import the pandas library. Try installing the pandas library by running `!pip install pandas` before loading the YOLOv5 model. This should resolve the issue and prevent the error from occurring.

Let us know if this solution works or if you have any further questions or issues!

**Comment by yeongnamtan** [comment]
thank you. It works now after I followed your suggestion.

**Comment by glenn-jocher** [comment]
@yeongnamtan thank you for letting us know that our solution worked for you! We're glad that you were able to successfully load the YOLOv5 model after installing the pandas library. If you have any further questions or run into any other issues, feel free to ask. We're here to help!

**Comment by pstephenwille** [comment]
> @yeongnamtan hello! Thank you for using YOLOv5.
> 
> Regarding your code, it seems like you are loading a custom YOLOv5 model stored in `/root/Yolov5_DeepSort_Pytorch/weights/best_Yolov5l_06April2023.pt`. Make sure that path is correct and that the model is stored properly in that directory.
> 
> If you encounter any issues or have further questions, feel free to let us know.

what does it mean to store the model properly?
