### ISSUE TITLE
Save .zip comet experiment file on every epoch

### ISSUE THREAD

**Issue by SJavad** [ultralytics/yolov5#11449]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hi
when I run the `python train.py` command and training ends, the **_comet_** library creates a zip file to the .comet_runs directory that contains training parameters and metrics. 
the name of the zip file is something like this: `2667624c2be64b5e9bc2b414cc4844fe.zip`
I want to come to create this zip file on every epoch. 
I try to `--save-period 1` and still **_comet_** create this zip file when all training processes have ended. 
I want to save and get these zip files when training still running.
#
I designed a UI application for training the yolov5 model on the custom dataset and I want to show the training parameters live while training in the process.
how can I do that?
I design my application with PyQT.
# 
I check the `clear_ml` logging tool and seem also this tool gives me all information "after the training process" and doesn't get me the parameters online (while training is in the process).
# 
Does anyone know another way to get these parameters while training and stream that live on my own application?

**Comment by glenn-jocher** [comment]
@SJavad hi there,

Currently, the `--save-period` argument only saves the best and latest weights, as well as a results file, at the specified period. However, saving the comet.zip file with the training parameters and metrics, unfortunately, cannot currently be done during training, and is only available after the training process has ended.

As for your UI application, you might consider using the `--project` argument when training with YOLOv5 to specify a unique name for your project, and then logging to Comet using that same name. You could then live stream the corresponding Comet project page in your application to show the training parameters in real-time. Alternatively, you might consider using a different real-time logging tool that can best suit your needs.

I hope this helps! Let us know if you have any further questions or concerns.

**Comment by SJavad** [comment]
@glenn-jocher 
thanks for your response
I have to use `--save-period 1` and then use metrics in the result.csv file that is saved in the `runs/exp` folder 
do you know tools that can give metrics and parameters live while training? 
#
I see some variables in the `train.py` file such as `t0 `, `results` , `maps`, and... that represent some of these metrics and parameters.
how can I pass these variables to another Python file or pass them to my PyQT UI application? 
#
thank you again for your help ❤

**Comment by glenn-jocher** [comment]
@SJavad, glad to hear that the `--save-period 1` and `results.csv` option worked for you. 

To answer your second question, you can pass those metrics from the `train.py` file to another Python file or to your PyQT UI application in a few different ways. One way is to use a combination of Python's built-in `socket` module and a custom protocol to send data in real-time. Another way could be to use a message broker like RabbitMQ or Kafka to publish the metrics and have your UI application subscribe to those messages in real-time. 

In terms of integrating with PyQT, you can incorporate this real-time metric data into your application using the appropriate PyQT widgets, such as `QListWidget` or `QTableWidget`, depending on the formatting and display requirements of your UI. 

I hope this helps! Let us know if you have any more questions or would like us to elaborate further.

**Comment by SJavad** [comment]
@glenn-jocher 
Thank you so much for your help
I really appreciate that.

**Comment by glenn-jocher** [comment]
@SJavad, you're very welcome! It's great to see members of the YOLO community like yourself pushing the boundaries of what's possible with the model. Don't hesitate to ask if you have any further questions or issues in the future. We're always here to help!
