### ISSUE TITLE
YOLOv7 license

### ISSUE THREAD

**Issue by nick-konovalchuk** [ultralytics/yolov5#11445]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello
I'd say that making YOLO AGPL-3.0 is a bad idea, but I didn't create this issue to discuss this change.
I wanna ask if YOLOv7 can keep it's GPL-3 since it was derived from YOLOv5 when it still had GPL-3 license.

**Comment by glenn-jocher** [comment]
@bottledmind hi, thanks for your question!

Regarding YOLOv5's switch to AGPL-3.0, we made this decision after careful consideration, understanding that it might not be favorable to everyone. However, we believe this change helps protect the project and the contributors involved.

If YOLOv7 was derived from YOLOv5 when it was under the GPL-3 license, they may continue to use that version of the code under the GPL-3 license, as that license still applies to the code at that point in time. However, any new changes, improvements or features that are implemented in YOLOv5 after the switch to AGPL-3.0 cannot be incorporated into YOLOv7 without also adopting the AGPL-3.0 license.

Please let me know if you have any other questions or concerns.
