### ISSUE TITLE
Interpretation Training Results (M) vs. (B)

### ISSUE THREAD

**Issue by katiefux** [ultralytics/yolov5#11454]
Dear reader,

I have trained a model and i have a question regarding the results file that shows the loss/precision/recall/mAP... of every epoch:
What is the meaning of (M) vs. (B) in brackets for the measures precision, recall, mAP_0.5 and mAP_0.5:0.95?

![image](https://user-images.githubusercontent.com/64419179/235138416-18300a47-0237-4e35-8595-f9f2c9d29697.png)

Thanks a lot in advance for a response!

**Comment by glenn-jocher** [comment]
@katiefux hello!

(M) refers to "macro" average, which calculates the average performance metric over each class. (B) refers to "best" performance metric achieved by the model during the training process. So for example, "mAP_0.5 (B)" would refer to the best mean average precision at an IoU threshold of 0.5 achieved by the model during training, while "mAP_0.5 (M)" would refer to the macro average mean average precision at an IoU threshold of 0.5 across all classes.

I hope this answers your question! Let us know if there's anything else we can help you with.

**Comment by uri-el99** [comment]
Hi dear @glenn-jocher, thanks for all your support and hope you are doing it pretty well. 
Considering what you mentioned before, I am still a little bit confused. I have read other similar issues, but when do I consider M as Macro and B as best? and also Mask or Bos when using segmentation task.

**Comment by glenn-jocher** [comment]
@uri-el99 hello! In the context of YOLOv5, (M) stands for "macro" average and (B) for "best" performance during training. For segmentation tasks, "Mask" refers to the segmentation mask, while "Box" refers to bounding box metrics. Let me know if you need further clarification!

**Comment by uri-el99** [comment]
@glenn-jocher so basically for YOLOv5 (M) and (B) refer to Macro and Best, but when talking about YOLOv8 and YOLOv9 when doing segmentation, (M) and (B) are Mask and Box, am I right?

**Comment by glenn-jocher** [comment]
Yes, that's correct. In YOLOv5, (M) and (B) refer to Macro and

**Comment by Paryavi** [comment]
Hi @glenn-jocher I am using Yolov8 for detection, and I get (B) in performance metrics. Is the following statement correct? 

In Yolov8, for object detection, in Detmetrics class, it looks like B also means bounding box;
https://github.com/ultralytics/ultralytics/blob/77c3c0aaac25e8738c0fe976f3e17c65aca12445/ultralytics/utils/metrics.py#L855

not to be confused with Mask in same metrics.py file where M is used in SegmentMetrics class;
https://github.com/ultralytics/ultralytics/blob/77c3c0aaac25e8738c0fe976f3e17c65aca12445/ultralytics/utils/metrics.py#L1017

**Comment by flaviomassaroni** [comment]
HI @glenn-jocher I am using Yolo11-seg for segmentation. In this case, what (B) and (M) means in results graphs? Are they Macro and Best or Mask and Box?

**Comment by TheMemoryDealer** [comment]
@flaviomassaroni Mask and Box I believe. source - https://github.com/ultralytics/ultralytics/issues/5003#issuecomment-1727844276
