### ISSUE TITLE
DDP training with different machine

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#11457]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have two machine, each of which can ssh each. (also ping master_addr)

I run the code to training, but it hang.

the machine1 has load the gpu memory, but 0% usage.  
the machine 2 don't load the gpu memory  0 Mib.  

If I close the machine1 program, the machine2 will show "RuntimeError: Connection reset by peer"
So I make sure machine2 is connect to machine1

Does anyone have the idea?

machine1
```
docker run -it --gpus all --rm -v $(pwd):/mnt --network=host nvcr.io/nvidia/pytorch:21.09-py3
python -m torch.distributed.launch --nproc_per_node=4 --nnodes=2 --node_rank=0 --master_addr="192.168.1.1" --master_port=1234 train.py
```
machine2
```
docker run -it --gpus all --rm -v $(pwd):/mnt --network=host nvcr.io/nvidia/pytorch:21.09-py3
python -m torch.distributed.launch --nproc_per_node=4 --nnodes=2 --node_rank=1 --master_addr="192.168.1.1" --master_port=1234 train.py
```

It was hang with this message
```
/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py:177: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torch.distributed.run.
Note that --use_env is set by default in torch.distributed.run.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************

```

**Comment by glenn-jocher** [comment]
@alicera hello! It seems like you are trying to train on two machines using torch.distributed.launch. Have you ensured that both machines have access to the training data? Also, have you verified that your network setup is correct?

As for the hang and the error message, it seems like the warning is not related to your issue. Are you able to provide more details on where the code hangs? It might be helpful to provide more logs or error messages. 

If you're still having issues, have you tried using the newer `torch.distributed.launch` utility suggested by the FutureWarning message? You can find more information on how to use that at https://pytorch.org/docs/stable/distributed.html#launch-utility

Best of luck and let us know if you have any updates!

**Comment by alicera** [comment]
Do you know the possible reason ?

I train it with two  machine and its speed is slow  (13.08s/it)
```
    0/99      5.18G    0.09651    0.06989    0.02222         85        832:   8%|▊         | 137/1616 [29:56<5:22:32, 13.08s/it]
```
here is the command
```
torchrun --nnodes=2 --node-rank=0 --master-addr="192.168.1" --master-port=1234 --nproc-per-node 4 train.py --batch-size 64 --hyp data/hyps/hyp.scratch-med.yaml

torchrun --nnodes=2 --node-rank=1 --master-addr="192.168.1" --master-port=1234 --nproc-per-node 4 train.py --batch-size 64 --hyp data/hyps/hyp.scratch-med.yaml
```

it occupy 5GB memory for each GPUs (total 8 GPUs)

If I train it on one machine, the speed will be about    (2s/it)

Do you have any suggestion ?

**Comment by glenn-jocher** [comment]
@alicera hello! It's likely that the slower performance of the distributed training setup is due to increased overhead from communication between the two machines. This can result in slower convergence and increased training time. 

To improve performance, you could try:

1. Increasing the batch size per GPU to better utilize the available GPUs and potentially reduce communication overhead. 
2. Optimizing hyperparameters such as learning rate and weight decay, as this can have a significant impact on performance. 
3. Using a more powerful machine, if available, to reduce the number of nodes being used and thereby reduce communication overhead.

I hope this helps! Let us know if you have any further questions or concerns.
