### ISSUE TITLE
The define of --workers

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#11456]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

```
    parser.add_argument('--workers', type=int, default=8, help='max dataloader workers (per RANK in DDP mode)')
```

How to define it ?
Sometimes, it was 4, but now it is 8.

**Comment by glenn-jocher** [comment]
@alicera the `--workers` argument in the YOLOv5 command line interface specifies the maximum number of dataloader workers. You can set it to any positive integer value, depending on your system's hardware specifications. In DDP mode, the number of workers is multiplied by the number of RANKs. Therefore, if you have multiple GPUs and are using DDP for parallel training, you can increase the value of `--workers` to speed up data loading. I hope this helps! Let me know if you have any other questions.

**Comment by alicera** [comment]
so good

https://github.com/ultralytics/yolov5/blob/master/utils/dataloaders.py#L140

Assume the computer has 8 CPUs (  os.cpu_count() = 8) 
and 4 GPUs

nw = num_workers = 8 / 4 = 2

Does it mean each gpu use 2 cpu for dataloader ?   (total 8 cpu are used)


according to the parameter, --workers will be 2 for the case
```
parser.add_argument('--workers', type=int, default=8, help='max dataloader workers (per RANK in DDP mode)')
```

RANK 0  use  2 cpu
RANK 1  use  2 cpu
RANK 2  use  2 cpu
RANK 3  use  2 cpu

**Comment by glenn-jocher** [comment]
@alicera, yes, that is correct. In the case where you have a computer with 8 CPUs and 4 GPUs, setting the `--workers` parameter to the default value of 8 would result in each GPU using 2 CPUs for data loading (total of 8 CPUs being utilized by all 4 GPUs). Specifically, each DDP rank would use `--workers`/RANK CPUs for data loading. Therefore, if you have multiple GPUs and are using DDP mode for parallel training, you may want to increase the value of `--workers` to speed up data loading. Let me know if you have any other questions.
