### ISSUE TITLE
Illegal Instruction (core dumped)-Running yolov5 on Raspberry pi 3

### ISSUE THREAD

**Issue by berry-sh** [ultralytics/yolov5#11464]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am trying to run yolov5 on Ubuntu 22.04.2 LTS installed on **Raspberry pi 3**, but it gives me every time this warning 
**"/home/ubuntu/.local/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: failed to load image python extension"** 

Finally, it gives me **"Illegal Instruction (core dumped)"** even though I am using the same version for all the requirements as when running Yolo on my Laptop (it works on my Laptop).

**Comment by glenn-jocher** [comment]
@berry-sh hi there! The warning you are seeing could be caused by an issue with your TorchVision installation. You could try running `pip uninstall torchvision && pip install torchvision` to ensure that it is installed correctly. 

The "Illegal Instruction (core dumped)" error suggests that there could be a compatibility issue with your Raspberry Pi 3. YOLOv5 is optimized for use on GPUs, so running it on a CPU like the one in the Raspberry Pi 3 may be challenging or slow. You could try reducing the batch size and the image size to see if that helps.

Also, please make sure that all the dependencies including PyTorch are installed properly. You can check if PyTorch is installed correctly by running `python -c "import torch;print(torch.version.cuda)"` which should output your CUDA version. Let us know if this helps!

**Comment by berry-sh** [comment]
okay, so this time instead of installing the versions of packages that worked on my ubuntu PC (by pip freeze > requirements.txt), I just ran pip install -r requirements.txt (the text file on the repo). This file has torch version 1.7.0 and torchvision version 0.8.1. It does not install those version and instead install torch 2.0.0 and torchvision 0.15.1. When it does so, the warning is gone but still I get **Illegal Instruction** when running `python3 detect.py --source 0.` 

I then ran` python -c "import torch;print(torch.version.cuda)"` & it gave me **Illegal Instruction** as well.

If I try `pip uninstall torch && pip install torch==1.7.0`, it says no such version (only available versions are 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0)

I then tried installing torch 1.13.0 with torchvision 0.14.0, but I got the warning back **("/home/ubuntu/.local/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: failed to load image python extension")** along with the **Illegal Instruction** error BUT this time, I got **NONE** when running ` python -c "import torch;print(torch.version.cuda)"`

**Comment by berry-sh** [comment]
Is there a way maybe to use the Raspberry pi GPIO pins (because I need to connect ultrasonic sensors and motors to it) while reading and writing to these pins from my PC? This way I can run yolov5 on my PC instead of running it on the Raspberry pi.

Thanks.

**Comment by glenn-jocher** [comment]
@berry-sh hey there! Yes, you can definitely use the Raspberry Pi GPIO pins to connect and control ultrasonic sensors and motors while running YOLOv5 on your PC. One way to accomplish this is through a library like [gpiozero](https://gpiozero.readthedocs.io/en/stable/index.html), which is a simple Python library that provides a way to interact with GPIO devices connected to the Raspberry Pi. 

You can run the code that controls the GPIO pins on the Raspberry Pi while also having your YOLOv5 code running on your PC. The two can communicate with each other over a network using a protocol like [MQTT](https://mqtt.org/) or [WebSockets](https://en.wikipedia.org/wiki/WebSocket), for example. 

There are many ways to accomplish this, so it depends on your specific requirements and setup. Let us know if you have any further questions.

**Comment by berry-sh** [comment]
Thank you so much

**Comment by glenn-jocher** [comment]
@berry-sh of course, I'd be happy to help! Please let me know what your question is regarding YOLOv5 and I will do my best to assist you. :-)
