### ISSUE TITLE
Preprocessing image using ONNX model gives warning each time inference is run

### ISSUE THREAD

**Issue by MathijsNL** [ultralytics/yolov5#11473]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection, Export

### Bug

As far as I understand the check **self.model.pt** will always be False if ONNX is used. Getting this warning for each detection is annoying. I think giving this warning once when it occurs and then skip it afterwards is the way to go.

https://github.com/ultralytics/ultralytics/blob/44c7c3514d87a5e05cfb14dba5a3eeb6eb860e70/ultralytics/yolo/engine/predictor.py#L118-L121

```
    def preprocess(self, im):
        """Prepares input image before inference.
        Args:
            im (torch.Tensor | List(np.ndarray)): (N, 3, h, w) for tensor, [(h, w, 3) x N] for list.
        """
        if not isinstance(im, torch.Tensor):
            auto = all(x.shape == im[0].shape for x in im) and self.model.pt
            if not auto:
                LOGGER.warning(
                    'WARNING ⚠️ Source shapes differ. For optimal performance supply similarly-shaped sources.')

```

### Environment

Ultralytics YOLOv8.0.91 🚀 Python-3.10.10 torch-1.13.1+cpu CPU
Using WSL2 Ubuntu 22.04

### Minimal Reproducible Example

You need an ONNX exported model for this (I think OPSET 12)
```
from ultralytics import YOLO
model = YOLO('yolo.onnx', task='detect')
results = model('../images/2023-04-25_15_10_16_144.jpg', verbose=False, mode='predict')
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello @MathijsNL, 

Thank you for bringing this issue to our attention. We apologize for any inconvenience that this warning may be causing you. 

Regarding the behavior of the `self.model.pt` check, you are correct that it will always be False when using an ONNX model. We appreciate your suggestion to give this warning once when it occurs and then skip it afterwards.  

We will review your suggestion and consider it for inclusion in a future update to YOLOv5.

Thank you for your interest in YOLOv5 and for your contribution to the project!

**Comment by MathijsNL** [comment]
Thanks for your response @glenn-jocher

In the meantime if anyone comes across this issue there is a relatively simple workaround:

```
import logging
from ultralytics import YOLO

yolologger = logging.getLogger('ultralytics')
yolologger.setLevel(logging.CRITICAL)
```


And a suggestion for the warn once:
```
self.not_auto_warned = False
            if not auto and self.not_auto_warned:
                LOGGER.warning(...
                self.not_auto_warned = True
```

Also I noticed that I made the issue under the wrong repo -_- Should have been under the ultralytics repository.
Do you want me to create an issue there so it doesn't get mixed up with the issues here?

**Comment by glenn-jocher** [comment]
Hi @MathijsNL,

Thank you for providing a workaround for the warning issue. Your suggestion for the `warn once` feature is also appreciated, we will review it for inclusion in a future update.

Regarding the issue being created under the wrong repo, it's not a problem. We will transfer it to the ultralytics repository for better tracking and handling. Thank you for considering it.

Please let us know if you have any more questions or concerns, we're here to help.
