### ISSUE TITLE
Why divide by 1000 when calculating inference time per image?

### ISSUE THREAD

**Issue by Jungjihyuk** [ultralytics/yolov5#11479]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, 
I have a question about inference time per image.

**detect.py code in YOLOv5 v7.0** 

line 207~209

`# Print results
t = tuple(x.t / seen * 1E3 for x in dt)  # speeds per image 
LOGGER.info(f'Speed: %.1fms pre-process, %.1fms inference, %.1fms NMS per image at shape {(1, 3, *imgsz)}' % t)`

**Question**
If x.t is in seconds and the logger is in ms then shouldn't it be multiplied by 1000?
For example, if x.t is 0.2s and convert to ms, it is 20ms. 
So we should do 0.2*1000.
please let me know if i missed out anything. 
Thank you.

**Comment by glenn-jocher** [comment]
Hello @Jungjihyuk,

Thank you for reaching out to us with your question. 

Regarding your question, `detect.py` code in YOLOv5 v7.0 multiplies the speeds per image values by `1E3` for conversion from seconds to milliseconds. Specifically, tuple(x.t / seen * 1E3 for x in dt) computes the average speeds per image as tuple (pre-process time, inference time, NMS time) in milliseconds.

Therefore, you don't need to multiply the calculation of milliseconds by `1000` when logging the inference time per image.  

Please let us know if you have further questions. We're always here to assist you. 

Best, 
Ultralytics Team

**Comment by Jungjihyuk** [comment]
Thanks for your reply. 

After reading the answer carefully, I realized that it was my mistake.
I misunderstood `x.t / seen * 1E3` code as `x.t /(seen * 1E3)`
Now i totally understand. 

Thank you glenn.

**Comment by glenn-jocher** [comment]
Dear @Jungjihyuk,

Thank you for getting back to us with your feedback, and we're delighted to know that the issue is resolved. 

Please don't hesitate to ask if you have any further questions or need further assistance. 

Best, 
Glenn Jocher - Ultralytics Team
