### ISSUE TITLE
How to customize classification network models？

### ISSUE THREAD

**Issue by songjiahao-wq** [ultralytics/yolov5#11471]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to implement face classification, how to customize the classification network model, such as mobilenet, mobilevit, etc.

**Comment by glenn-jocher** [comment]
@songjiahao-wq hi there,

To customize the classification network model, you can modify the `models/` directory in the YOLOv5 repository. Specifically, you can modify the network architecture files to use the classification network of your choice, such as mobilenet or mobilevit. You can also modify the `train.py` script in the `scripts/` directory to use your modified network architecture file during training.

That being said, face classification is not the primary intended use case of YOLOv5, which is object detection. If you are looking specifically for face recognition models, there are specialized models and libraries available that may better suit your needs.

I hope this information helps! Let me know if you have any further questions.

Best regards,
Glenn Jocher
