### ISSUE TITLE
Super slow inference for YOLOV5n uint8 quantised pretrained model on Quadcore Cortex-A53 CPU and Adreno 702 

### ISSUE THREAD

**Issue by chinya07** [ultralytics/yolov5#11487]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, Greetings everyone!
I am using the pre-trained YOLOV5 model from this github repo which is exported to `tflite` format using `export.py` script. I have an Android app which is using pre-built TFLite C++ libraries to read and infer the object detection model. I found promising performance when this application tested on **Qualcomm SM8250-AC processor with Adreno 650 GPU**. Details are below-

`Model: YOLOV5n 320X320 uint8`
`Object detection --> GPU + NMS --> CPU --> 21~30 ms`

However, when I tested this model on a development board with **Cortex-A53 Quadcore CPU and Adreno 702 GPU**, the performance was very poor. Details are below-

`Model: YOLOV5n 320X320 uint8`
`Object detection --> GPU + NMS  --> CPU --> ~360 ms`

`Model: ssd_mobilenet 300X300 uint8`
`Object detection --> GPU + NMS --> CPU --> ~616 ms`
`Object detection + NMS--> CPU --> 1494 ms`

I've tested this android app (https://github.com/lp6m/yolov5s_android/tree/master) on **Qualcomm SDM636 processor with Adreno 509 GPU** with `yolov5s` and I found the performance on as below-

`Model: YOLOV5s 320X320 int8`
`Object detection + NMS --> CPU --> ~181 ms`

`Model: YOLOV5s 640X640 float32`
`Object detection + NMS --> CPU --> ~886 ms`

I am unsure whether there is something impacting at the android level or if something is causing the slow inference due to the shared memory on the SOM. Please help if someone has any idea about this. Let me know if any additional information is needed. 
Thank you!

**Comment by glenn-jocher** [comment]
@chinya07 hello, thank you for reaching out to us for this issue. We appreciate you sharing the details of your model and the varying performance based on the processor. Based on the information you have provided, it appears that the performance issue with YOLOv5 on the development board may be related to hardware limitations. Unfortunately, we are not experts in the specific components and architecture in your provided hardware setup, so we cannot offer specific advice. However, it may be helpful to further investigate the hardware specifications and limitations of the development board, and compare them to the requirements for running YOLOv5. It may also be useful to run additional tests and benchmarks to further evaluate and compare performance. If you have any additional information to provide, please let us know. Thank you!
