### ISSUE TITLE
I got an hubconf.py error while loading my best.pt saved model

### ISSUE THREAD

**Issue by amir-sbg** [ultralytics/yolov5#11481]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection, Other

### Bug

YOLOv5 🚀 2023-5-2 Python-3.10.11 torch-2.0.0+cu118 CPU

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[/content/drive/MyDrive/Colab Notebooks/YOLO/./yolov5/hubconf.py](https://localhost:8080/#) in _create(name, pretrained, channels, classes, autoshape, verbose, device)
     48             try:
---> 49                 model = DetectMultiBackend(path, device=device, fuse=autoshape)  # detection model
     50                 if autoshape:

8 frames
[/content/drive/MyDrive/Colab Notebooks/YOLO/./yolov5/models/common.py](https://localhost:8080/#) in __init__(self, weights, device, dnn, data, fp16, fuse)
    343         if pt:  # PyTorch
--> 344             model = attempt_load(weights if isinstance(weights, list) else w, device=device, inplace=True, fuse=fuse)
    345             stride = max(int(model.stride.max()), 32)  # model stride

[/content/drive/MyDrive/Colab Notebooks/YOLO/./yolov5/models/experimental.py](https://localhost:8080/#) in attempt_load(weights, device, inplace, fuse)
     79         ckpt = torch.load(attempt_download(w), map_location='cpu')  # load
---> 80         ckpt = (ckpt.get('ema') or ckpt['model']).to(device).float()  # FP32 model
     81 

KeyError: 'model'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
[/content/drive/MyDrive/Colab Notebooks/YOLO/./yolov5/hubconf.py](https://localhost:8080/#) in _create(name, pretrained, channels, classes, autoshape, verbose, device)
     59             except Exception:
---> 60                 model = attempt_load(path, device=device, fuse=False)  # arbitrary model
     61         else:

[/content/drive/MyDrive/Colab Notebooks/YOLO/./yolov5/models/experimental.py](https://localhost:8080/#) in attempt_load(weights, device, inplace, fuse)
     79         ckpt = torch.load(attempt_download(w), map_location='cpu')  # load
---> 80         ckpt = (ckpt.get('ema') or ckpt['model']).to(device).float()  # FP32 model
     81 

KeyError: 'model'

The above exception was the direct cause of the following exception:

Exception                                 Traceback (most recent call last)
[<ipython-input-39-1688937276cc>](https://localhost:8080/#) in <cell line: 2>()
      1 import torch
----> 2 model = torch.hub.load('./yolov5', 'custom',force_reload=True, path='./best1.pt', source='local')
      3 # model = torch.hub.load("ultralytics/yolov5", "custom", weights_path, force_reload=True)
      4 # Image
      5 img = './road.jpg'

[/usr/local/lib/python3.10/dist-packages/torch/hub.py](https://localhost:8080/#) in load(repo_or_dir, model, source, trust_repo, force_reload, verbose, skip_validation, *args, **kwargs)
    556                                            verbose=verbose, skip_validation=skip_validation)
    557 
--> 558     model = _load_local(repo_or_dir, model, *args, **kwargs)
    559     return model
    560 

[/usr/local/lib/python3.10/dist-packages/torch/hub.py](https://localhost:8080/#) in _load_local(hubconf_dir, model, *args, **kwargs)
    585 
    586         entry = _load_entry_from_hubconf(hub_module, model)
--> 587         model = entry(*args, **kwargs)
    588 
    589     return model

[/content/drive/MyDrive/Colab Notebooks/YOLO/./yolov5/hubconf.py](https://localhost:8080/#) in custom(path, autoshape, _verbose, device)
     81 def custom(path='path/to/model.pt', autoshape=True, _verbose=True, device=None):
     82     # YOLOv5 custom or local model
---> 83     return _create(path, autoshape=autoshape, verbose=_verbose, device=device)
     84 
     85 

[/content/drive/MyDrive/Colab Notebooks/YOLO/./yolov5/hubconf.py](https://localhost:8080/#) in _create(name, pretrained, channels, classes, autoshape, verbose, device)
     76         help_url = 'https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading'
     77         s = f'{e}. Cache may be out of date, try `force_reload=True` or see {help_url} for help.'
---> 78         raise Exception(s) from e
     79 
     80 

Exception: 'model'. Cache may be out of date, try `force_reload=True` or see https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading for help.

### Environment

-YOLOv5 🚀 2023-5-2 Python-3.10.11 torch-2.0.0+cu118 CPU
-Google Colab
-Python 3.10

### Minimal Reproducible Example

import torch

model = torch.hub.load('./yolov5', 'custom',force_reload=True, path='./best.pt', source='local') 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@amir-sbg hello! It seems that there was an issue with loading the YOLOv5 model in your environment. The error trace suggests that there was a `KeyError` when trying to access the `"model"` key in the checkpoint. One possible solution that you could try is to set the `force_reload` flag to `True` when loading the model with `torch.hub.load`, as suggested by the error message. This will ensure that the latest version of the model is downloaded from the PyTorch Hub.

If the issue persists, please let us know and we'd be happy to assist you further. Thanks for using YOLOv5!
