### ISSUE TITLE
Onnx layer documentation

### ISSUE THREAD

**Issue by thhart** [ultralytics/yolov5#1148]
## ❔Question

Hi, I am new to this Yolo ML and I am wondering where to find documentation about the input and output layers. I am looking for a possibility to do inference in Java however the Java coverage is not very good. I can see some kind of frameworks able to run and import models but the documentation is very bad. Following questions I have:

1. I can see the network can be trained for different resolutions. What resolution is to be expected then as input tensor, is it flexible in this?
2. Giving a max resolution can the resolution be less than that?
3. What is the output giving out then, I already understood there might be two output layers depending on: model.model[-1].export = False, but what kind of layers are these then?
4. I understand NMS is not included by default, can this be done in the model or is it recommended to do manually by evaluating the output?

Some good pointers/documentation would be nice, I know there is a lot floating around but it is a bit owerhelming with all these versions of Yolo.

**Comment by glenn-jocher** [comment]
@thhart see export tutorial https://docs.ultralytics.com/yolov5

**Comment by thhart** [comment]
Thanks for the pointer however the layer output is still mystique to me.
Can you let me know what types of layers are produced either by model.model[-1].export = False/True?

**Comment by thhart** [comment]
I could predict using the box layer format now. However I think a detailed documentation would be helpful.

**Comment by smartinellimarco** [comment]
Same boat here. Could you elaborate please? 😄
