### ISSUE TITLE
I was download the ultralytics PyTorch pt and using export.py with nms (CoreML coming up split_with_sizes expects split_sizes to sum exactly to 8500 (input tensor's size at dimension 1), but got split_sizes=[4, 1, 10] error)

### ISSUE THREAD

**Issue by gambobill** [ultralytics/yolov5#11493]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

python3 export.py --weights model-5.pt --include coreml --nms
export: data=data/coco128.yaml, weights=['model-5.pt'], imgsz=[640, 640], batch_size=1, device=cpu, half=False, inplace=False, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=17, verbose=False, workspace=4, nms=True, agnostic_nms=False, topk_per_class=100, topk_all=100, iou_thres=0.45, conf_thres=0.25, include=['coreml']
YOLOv5 🚀 v7.0-162-gc3e4e94 Python-3.8.0 torch-2.0.0 CPU

[W NNPACK.cpp:64] Could not initialize NNPACK! Reason: Unsupported hardware.
YOLOv5s6u summary (fused): 253 layers, 15257560 parameters, 0 gradients, 24.2 GFLOPs

PyTorch: starting from model-5.pt with output shape (1, 14, 8500) (29.5 MB)
Torch version 2.0.0 has not been tested with coremltools. You may run into unexpected errors. Torch 1.13.1 is the most recent version that has been tested.

CoreML: starting export with coremltools 6.2...
CoreML: export failure ❌ 1.3s: split_with_sizes expects split_sizes to sum exactly to 8500 (input tensor's size at dimension 1), but got split_sizes=[4, 1, 10]
CoreML Pipeline: starting pipeline with coremltools 6.2...
Traceback (most recent call last):
  File "export.py", line 818, in <module>
    main(opt)
  File "export.py", line 813, in main
    run(**vars(opt))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "export.py", line 733, in run
    pipeline_coreml(ct_model, im, file, model.names, y)
  File "export.py", line 540, in pipeline_coreml
    spec = model.get_spec()
AttributeError: 'NoneType' object has no attribute 'get_spec'

**Comment by glenn-jocher** [comment]
@gambobill hi there,

It looks like you're encountering an issue with exporting the YOLOv5 model to CoreML. The error message indicates that "split_with_sizes expects split_sizes to sum exactly to 8500", which suggests that the number of output classes may not be correct. 

One possible solution is to adjust the `nc` parameter in your `data/coco128.yaml` file to match the number of classes in your dataset. This could help ensure that the output tensor has the correct shape.

In addition, it seems that you're using Torch version 2.0.0, which hasn't been tested with coremltools. You may want to try downgrading to Torch 1.13.1, which is a version that has been tested with coremltools.

I hope this helps! Let us know if you have any further questions or concerns.
