### ISSUE TITLE
How to output the inference result to an excel file?

### ISSUE THREAD

**Issue by WuxiaZhang** [ultralytics/yolov5#11497]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I have trained a yolov5 model and run inference on a video, the results showed but how to save that in an Excel file ?

**Comment by glenn-jocher** [comment]
@WuxiaZhang hello! Glad to hear that you were able to run inference on a video using YOLOv5. To save the results in an Excel file, you can convert the output of your inference to a pandas DataFrame, and then write that DataFrame to an Excel file using the pandas `to_excel()` function. You will need to format the output to suit your specific requirements. 

Hope this helps! Let us know if you have any questions.
