### ISSUE TITLE
YOLOV5 citation

### ISSUE THREAD

**Issue by NanH5837** [ultralytics/yolov5#11496]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

If I use YOLOV5-7.0 in my paper, can I cite it in BibTex format as follows:
@misc{yolov5,
  author = {Ultralytics},
  title = {{ultralytics/yolov5: v7.0 - YOLOv5 SOTA Realtime Instance Segmentation}},
  year = {2022},
  howpublished = {\url{https://github.com/ultralytics/yolov5.com}},
  note = {Accessed: 7th May, 2023},
  doi  = {10.5281/zenodo.7347926},
  url  = {https://doi.org/10.5281/zenodo.7347926}
}

**Comment by glenn-jocher** [comment]
Hello @monster519,

Yes, you can use the BibTex format that you have provided to cite YOLOv5-7.0 in your paper.

Thanks for using YOLOv5. If you have any other questions, feel free to ask!

Best Regards.
