### ISSUE TITLE
Poor FPS Using yolov5n Custom Model?

### ISSUE THREAD

**Issue by MagicalPotato0001** [ultralytics/yolov5#11495]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

PC Specs:
CPU: Ryzen 5 3600 6 Core
GPU1: RTX 2070 8GB
GPU2: RTX 3060Ti 8GB
RAM: 32GB DDR4
CUDA: 11.7
CUDNN: 8.8.1.3
PYTORCH: 2.0

I have trained a custom model using yolov5n, I was hoping to get around at least 30 fps but I am getting closer to 10, so I'm sure its probably user error on my part. All my script should do is take a screenshot of my primary monitor, pass it through the model, and then display it using opencv. Here is my code and any help would be greatly appreciated :)

```
import pyautogui as pyg
import torch
import numpy as np
import cv2

print('Import Complete')

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)
model = torch.hub.load('.', 'custom','best.pt', source='local', force_reload=True) #Imports model
model = model.autoshape()
model.conf = 0.30 #Confidence setting

#Create Window
cv2.namedWindow("Live", cv2.WINDOW_NORMAL) #Creates window
 
#Resize this window
cv2.resizeWindow("Live", 480, 270) #Resizes window

while True:
    img = np.array(pyg.screenshot()) #Takes a screenshot of primary monitor.
    results = model(img) #Passes image through AI.
    r_img = results.render() #Returns a list with the images as np.array.
    img_with_boxes = r_img[0] # image with boxes as np.array
    cv2.imshow('Live', img_with_boxes) #Updates window and displays image.
    if cv2.waitKey(1) == ord('q'):
        break
```

**Comment by glenn-jocher** [comment]
@MagicalPotato0001 hi there! Your system specifications seem pretty good and they should provide you with good performance with YOLOv5. 

Since you are getting lower performance than expected, there might be a few things you could try. Firstly, I recommend you use a smaller model such as yolov5s, or with fewer anchor boxes, such as yolov5n. These models are faster and may give you the 30 fps you are looking for, especially if your primary use case is object detection.

Another thing you could try is to resize the input images before feeding them into the model, as larger input images require more computations and thus decrease the FPS. 

Lastly, you should check that your GPU is being utilized during inference and that there's no other process that might be competing for its resources. You can use your system's task manager to check for this.

I hope this helps! Let me know if you have any other questions.

**Comment by MagicalPotato0001** [comment]
@glenn-jocher Hi, I am using yolov5n because I tried yolov7 first, I have tried reshaping the images before going into the model but it provided no noticeable differences. As for my GPU utilization while running the script it only uses 3% of my GPU, it seemingly uses my GPU memory but not its processing power.
![image](https://user-images.githubusercontent.com/132117519/236593928-d4011d27-2752-41ce-8ba5-f478716535f1.png)
![image](https://user-images.githubusercontent.com/132117519/236593962-099dee60-7a30-43ed-b7b2-611d675e1856.png)
And on Cuda:
![image](https://user-images.githubusercontent.com/132117519/236594495-95023183-8674-4558-a142-91254ba674ac.png)

**Comment by glenn-jocher** [comment]
@MagicalPotato0001 hello there! 

It looks like your GPU is not being utilized properly during inference, which might be causing the lower than expected fps. I would suggest ensuring that PyTorch is properly installed with GPU support by running `torch.cuda.is_available()`. If it returns True, then PyTorch is properly installed with GPU support. 

If that's not the case, please try reinstalling PyTorch following the instructions on the official PyTorch website.

If PyTorch is installed properly, then you might want to update your NVIDIA drivers and ensure that CUDA and cuDNN versions match the requirements specified in the YOLOv5 repo requirements.txt file. 

Let me know if this helps or if you have any further questions!

**Comment by MagicalPotato0001** [comment]
@glenn-jocher ```torch.cuda.is_available()``` returns true. All drivers are up to date, and i am currently using CUDA v11.7 and CUDNN v8.8.1.3, so i think i have everything installed correctly?
![image](https://user-images.githubusercontent.com/132117519/236599772-b7f878ba-e740-4b98-b5dd-5d1739aea989.png)

Do note when i used detect.py on a video i was getting 10-20ms inference times, so im guessing it may be a code error?

**Comment by glenn-jocher** [comment]
@MagicalPotato0001 it looks like your PyTorch installation is properly set up with GPU support and your CUDA and cuDNN versions match the requirements. It's possible that the issue might be related to your code.

One thing I notice in your while loop is that you are calling `np.array(pyg.screenshot())` to capture the screen. This might be causing an overhead in processing the image. Instead, you could try using `pyg.screenshot().convert('RGB')` to capture the screen in RGB format directly. 

You could also experiment with different batch sizes when passing images through the model to see if that improves performance. Additionally, you could try using a profiler such as Nvidia's Nsight Systems to identify performance bottlenecks in your code.

Lastly, I see that you are getting good results with `detect.py` on a video, which indicates that your system is capable of providing better inference times. 

I hope these suggestions help you improve the performance of your custom YOLOv5 model. Let me know if you have any further questions!

**Comment by MagicalPotato0001** [comment]
@glenn-jocher I have installed Nvidia Nsight, as for how to use it I'm a bit lost. I changed the ```np.array(pyg.screenshot())``` to ```pyg.screenshot().convert('RGB')``` with no noticeable difference unfortunately. I noticed in Detect.py you use DetectMultiBackend instead of torch.hub.load, is there any reason why, or could that be why mine is slower?
![image](https://user-images.githubusercontent.com/132117519/236640666-d4489bab-8215-4c19-b440-82cecc3dd19a.png)
Also im not sure if this is important but i am running this on base Python 3.9, not anaconda or a virtual env.

**Comment by MagicalPotato0001** [comment]
So i figured something out lol, using ```time.time()``` before and after the model inference i found out it isnt the model that is slowing it down, the model is getting roughly 15ms times.
![image](https://user-images.githubusercontent.com/132117519/236641398-88227343-3b24-4d2d-8f04-455d6a0ced96.png)
![image](https://user-images.githubusercontent.com/132117519/236641404-0a02bc7d-7a27-43d3-883a-1faf1c90bda7.png)
I will update you when i figure out more.

**Comment by MagicalPotato0001** [comment]
So taking a screenshot adds roughly 45ms of time, that may be the main issue?

**Comment by glenn-jocher** [comment]
@MagicalPotato0001 thank you for the update! It's great to hear that you were able to pinpoint the overhead in your code when capturing screenshots, which was adding roughly 45ms of time. This was the likely cause of the lower than expected FPS.

To improve performance, you could explore alternative methods to capture frames, such as using a dedicated camera or stream input. Additionally, you could consider optimizing your code to reduce the time it takes to capture and process each frame, especially if the frames are being processed in real-time.

I hope this helps and please let us know if you have any further questions!

**Comment by MagicalPotato0001** [comment]
@glenn-jocher Do you have any recommendations for modules that will take screenshots faster?

**Comment by MagicalPotato0001** [comment]
I got it working perfectly, thanks for all your help :)

**Comment by glenn-jocher** [comment]
@MagicalPotato0001 That's great to hear! I'm glad that you were able to improve the performance of your custom YOLOv5 model. If you have any further questions or run into any issues in the future, please don't hesitate to ask - we are always here to help.
