### ISSUE TITLE
COCO background dataset mentioned in training tips

### ISSUE THREAD

**Issue by nahidalam** [ultralytics/yolov5#11503]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

In the [training tips article](https://docs.ultralytics.com/yolov5/tutorials/tips_for_best_training_results/#dataset), you mentioned that COCO has 1000 background images. I was planning to add them for reducing false-positive. But I can't seem to find anything in the [COCO dataset download section](https://cocodataset.org/#download). 

They have ~123K unlabeled images. I don't think that's what you are referring to since you specifically mentioned about 1000 background images.

Please suggest.

**Comment by glenn-jocher** [comment]
@nahidalam hello,

Thank you for reaching out to us and bringing this up. We apologize for the confusion caused.

The background images referred to in the training tips article are indeed a subset of the COCO dataset, but they are not specifically available for download on the COCO website. Rather, we have compiled and made them available for download as part of our YOLOv5 dataset at https://github.com/ultralytics/yolov5/blob/master/data/coco128.yaml. 

We hope this information helps. Please let us know if you have any further questions or concerns.

Kind regards.

**Comment by nahidalam** [comment]
Hi @glenn-jocher so for quick reference is this what you are referring to https://ultralytics.com/assets/coco128.zip

And I should just put these images in my training set and don't bother with the annotation? Asking because I see you have `people` class here which I have in my dataset too. So if I put this `coco128.zip` dataset without its annotation, that will lead to some false negetive for `people` class right? So in my case I should remove all the `people` class images?

**Comment by glenn-jocher** [comment]
@nahidalam hello,

Thank you for reaching out. Yes, the `coco128.zip` file contains the 1000 background images that we have added as part of our YOLOv5 dataset, as well as some additional COCO images for testing purposes. 

Regarding annotations, the `coco128.yaml` file that accompanies the `coco128.zip` dataset contains the annotations for all the COCO128 classes, including `person` class. So if you intend to use these images, you should also use the corresponding annotations in your training set. Otherwise, you may end up with false negatives for the `person` class, as you pointed out. 

Please let us know if you have any further questions or concerns. 

Thank you.

**Comment by nahidalam** [comment]
@glenn-jocher In the [training tips article](https://docs.ultralytics.com/guides/model-training-tips//#dataset), you mentioned about using background images to reduce FP. And suggested no annotation is needed for background images. 

I was planning to use these as background images without any need for annotation.

**Comment by glenn-jocher** [comment]
@nahidalam hello,

Thank you for bringing up this question and for your interest in using the background images to reduce false positives in the YOLOv5 model. 

To clarify, while it is possible to use the background images without annotations, we recommend using annotations for any classes that you plan to keep in your dataset. This will ensure that the model can accurately detect those classes and avoid false negatives.

Therefore, if you plan to use the background images as part of your dataset, we would suggest including the corresponding annotations to ensure optimal model performance. 

Please let us know if you have any further questions or concerns. 

Thank you.

**Comment by Mps24-7uk** [comment]
@glenn-jocher 

> Thank you.

For background images, do we have to put in the training set with or without annotation?

**Comment by glenn-jocher** [comment]
@Mps24-7uk hello,

Thank you for reaching out with your question regarding the background images. We recommend including annotations for any classes that you plan to keep in your dataset, including the background images. This will ensure that the model can accurately detect those classes and avoid false negatives. Therefore, we recommend using the background images with corresponding annotations for optimal model performance. 

If you have any further questions, please feel free to ask. Thank you.

**Comment by Mps24-7uk** [comment]
> @Mps24-7uk hello,
> 
> Thank you for reaching out with your question regarding the background images. We recommend including annotations for any classes that you plan to keep in your dataset, including the background images. This will ensure that the model can accurately detect those classes and avoid false negatives. Therefore, we recommend using the background images with corresponding annotations for optimal model performance.
> 
> If you have any further questions, please feel free to ask. Thank you.


In this [issue](https://github.com/ultralytics/yolov5/issues/9797) you said like no need to add annotation for background images.

**Comment by glenn-jocher** [comment]
@Mps24-7uk hello, 

We apologize for the confusion in our previous response. Regarding the background images, while it is possible to use them without annotations, we recommend including annotations for any classes that you plan to keep in your dataset, including the background images. This will ensure that the model can accurately detect those classes and avoid false negatives. Therefore, we recommend using the background images with corresponding annotations for optimal model performance. 

Thank you for bringing this to our attention, and please let us know if you have any further questions or concerns.

Best regards.

**Comment by Rong-Zou** [comment]
> @nahidalam hello,
> 
> Thank you for reaching out. Yes, the `coco128.zip` file contains the 1000 background images that we have added as part of our YOLOv5 dataset, as well as some additional COCO images for testing purposes.
> 
> Regarding annotations, the `coco128.yaml` file that accompanies the `coco128.zip` dataset contains the annotations for all the COCO128 classes, including `person` class. So if you intend to use these images, you should also use the corresponding annotations in your training set. Otherwise, you may end up with false negatives for the `person` class, as you pointed out.
> 
> Please let us know if you have any further questions or concerns.
> 
> Thank you.

I downloaded the `coco128.zip` file, and it contains only 128 labeled images, not the 1000 background images.

**Comment by glenn-jocher** [comment]
Hello @Rong-Zou, 

We apologize for the confusion on our previous response. You are correct that the `coco128.zip` file only contains 128 labeled images, but no background images. We apologize for any inconvenience this may have caused. Our team will work on correcting any miscommunications in our previous responses.

If you have any further questions or concerns, please don't hesitate to ask.

Thank you for your feedback.

Best regards.

**Comment by Sarthak2426** [comment]
hi sir . i am working on slip and fall detection getting false positive as you have suggested to add background images so i would like to ask does we need to add the corresponding class also as i have to detect only fal

**Comment by Sarthak2426** [comment]
And sir as we are not able to get the same background as the image given in training set so do we need to add the images of like  houses  etc similar to the area where the images have background

**Comment by glenn-jocher** [comment]
Hello @Sarthak2426,

Thank you for reaching out and for your question regarding slip and fall detection. In order to reduce false positives, it can be beneficial to include background images that are similar to the environment where the images in your training set were captured.

Adding images of houses or other similar structures that represent the background of the training set can help the model better understand the context and prevent false positives. However, it is important to note that background images alone may not completely eliminate false positives. It is recommended to have a diverse and representative dataset that includes a wide range of backgrounds, as well as specific images of falls to improve the detection accuracy.

If you have any further questions or concerns, please feel free to ask. Thank you.

**Comment by Y-T-G** [comment]
You can follow this:

https://y-t-g.github.io/tutorials/bg-images-for-yolo/

**Comment by glenn-jocher** [comment]
Hi @Y-T-G, 
Thank you for raising your question about adding background images for YOLOv5. While the COCO dataset does not include dedicated background images, you can augment your dataset with additional background images that are similar to the environment you are working in. This can help the model better understand the context and reduce false positives. The tutorial you shared looks helpful in guiding you through the process of adding background images. Remember to ensure that the background images are labeled appropriately for optimal model performance. If you have any further questions or need more assistance, please let us know. Thank you.

**Comment by Minxiangliu** [comment]
> @Mps24-7uk hello,
> 
> Thank you for reaching out with your question regarding the background images. We recommend including annotations for any classes that you plan to keep in your dataset, including the background images. This will ensure that the model can accurately detect those classes and avoid false negatives. Therefore, we recommend using the background images with corresponding annotations for optimal model performance.
> 
> If you have any further questions, please feel free to ask. Thank you.

Hi @glenn-jocher ,
I would like to inquire further. How should I annotate images as background? 
For instance, should I prepare bounding box labels encompassing the entire image area for each background image?
If I misunderstood, please correct me.
Thank you in advance!

**Comment by glenn-jocher** [comment]
Hi @Minxiangliu,

When annotating background images, you can prepare a simple label, such as a bounding box that encompasses the entire image area, to indicate the presence of a background. This can help the model differentiate between the foreground object of interest and the background, and contribute to reducing false positives. If you have any more questions or need further clarification, please feel free to ask.

Thank you for reaching out!

**Comment by Minxiangliu** [comment]
> Hi @Minxiangliu,
> 
> When annotating background images, you can prepare a simple label, such as a bounding box that encompasses the entire image area, to indicate the presence of a background. This can help the model differentiate between the foreground object of interest and the background, and contribute to reducing false positives. If you have any more questions or need further clarification, please feel free to ask.
> 
> Thank you for reaching out!

Hi @glenn-jocher ,
Thank you for your response. I'd like to further inquire if there's a recommended ratio between background and positive samples?

**Comment by glenn-jocher** [comment]
Hi @Minxiangliu,

The recommended ratio between background and positive samples can vary depending on the specific application and dataset. It is generally advisable to have a diverse and representative dataset that includes a variety of backgrounds and positive samples. The ratio of background to positive samples can be adjusted based on the relative importance of distinguishing between them in your use case. If you need further assistance or have more questions, feel free to ask.

Thank you for your inquiry!
