### ISSUE TITLE
I'm going to add background images to improve performance...

### ISSUE THREAD

**Issue by Hwaaan2** [ultralytics/yolov5#11500]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm trying to put a background image in order to improve performance, but should I put any image with no label value in the train folder and let them learn?

**Comment by glenn-jocher** [comment]
Hello @Hwaaan2!

Based on what you are trying to achieve, you don't need to include images with no label value in the train folder.

If you want to use a background image to improve performance, you can simply use that image as a part of your dataset. Please ensure that the image is labelled appropriately. In case you don't want to annotate the background image at all, you can skip annotation for that specific image.

I hope this answers your question. Let us know if you have any other questions or concerns.


Regards, 
Glenn Jocher
