### ISSUE TITLE
image classfication pretrained weights

### ISSUE THREAD

**Issue by Mahdi-Maaref** [ultralytics/yolov5#11505]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I tried to use other checkpoint like` efficientnet_b0.pt` but i couldnt find the way how to use so i tried this code:

`python classify/train.py --model efficientnet_b0.pt --epochs 10 `

and getting this error:

```
ModuleNotFoundError: No module named 'torchvision.models.efficientnet'
terminate called without an active exception
```

**Comment by glenn-jocher** [comment]
@2022Mahdi hi there!

To use a pre-trained EfficientNet model for image classification, you need to have the `timm` package installed. This is mentioned in the [Ultralytics Docs](https://docs.ultralytics.com/yolov5/) under "Pre-trained Options".

You can install `timm` by running `pip install timm`, and then you should be able to use `efficientnet_b0` as your model. Let me know if you need any further assistance!
