### ISSUE TITLE
super slow training after upgrade from v6.0 to v6.1(or v7.0)

### ISSUE THREAD

**Issue by dao027** [ultralytics/yolov5#11501]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hello, when i use v6.0, object detection training was very fast(10s/it), but after i upgrade to v6.1(v7.0 same problem), training become super slow(30min/it, training time, NOT cacheing imgs). training parameters are all the same, same data, same batchsize, same environment, same hardware.
have anyone met this before? i really want to use v7.0
i have searched more than 200 issues, and some changelogs between v6.0 and v6.1, but still no idea

**Comment by glenn-jocher** [comment]
@dao027 hi there,

I'm sorry to hear that you are experiencing slow training times after upgrading to version 6.1 of YOLOv5. Have you tried resetting your training environment and data to ensure that there are no variables impacting this? Additionally, have you tried profiling your training process to identify where exactly the slowdown is occurring? These might be good places to start in troubleshooting the issue.

Best regards.

**Comment by dao027** [comment]
> @dao027 hi there,
> 
> I'm sorry to hear that you are experiencing slow training times after upgrading to version 6.1 of YOLOv5. Have you tried resetting your training environment and data to ensure that there are no variables impacting this? Additionally, have you tried profiling your training process to identify where exactly the slowdown is occurring? These might be good places to start in troubleshooting the issue.
> 
> Best regards.

thanks for reply, finally figure it out lol. it's due to the big size of disk cached imgs, start from v6.1, caching img code seems would save the whole img info(np.array) into .npy file, my training imgs are 2560*1440 resolution, the point is my train set is stored in mounted disk, so network bandwidth is my limit. 
now i changed .npy files, saving as `max(w,h)=640 or 1280` resolution, just as v6.0 did, and training speed is normal now
thank you very much~

**Comment by glenn-jocher** [comment]
@dao027 you're welcome! I'm glad to hear that you were able to identify and resolve the issue. Thank you for sharing your solution with the community - it might be helpful to others who encounter similar problems in the future. If you have any further questions or encounter any other issues with YOLOv5, feel free to reach out.

Best regards.
