### ISSUE TITLE
What does do the function "update" in LoadStreams class?

### ISSUE THREAD

**Issue by hdnh2006** [ultralytics/yolov5#1150]
## ❔Question
Hi Glenn, I was checking the code `datasets.py` and I am not able to know what the function [`update`](https://github.com/ultralytics/yolov5/blob/c67e72200e8b5caab6b2b2fa560cdb647b46f004/utils/datasets.py#L289) does.

If I understand good, you do a verification of something each 4 frames and you distribute all of that in each thread of the processor using the function `Thread` in [line 278](https://github.com/ultralytics/yolov5/blob/c67e72200e8b5caab6b2b2fa560cdb647b46f004/utils/datasets.py#L278). I understand you call `cap.grab()` function because otherwise the function `cap.retrieve()` will always return `(False, None)`, but why you do that? just to check if the video is still sending? you update the frame in [`line 277`](https://github.com/ultralytics/yolov5/blob/c67e72200e8b5caab6b2b2fa560cdb647b46f004/utils/datasets.py#L277), don't you?

Thanks in advance

**Comment by glenn-jocher** [comment]
@hdnh2006 the function comment explains its purpose.
https://github.com/ultralytics/yolov5/blob/82e865a10d31a1118e5cc8bee4028403ca0d525d/utils/datasets.py#L289-L290

**Comment by hdnh2006** [comment]
so, what is done in [`line 277`](https://github.com/ultralytics/yolov5/blob/82e865a10d31a1118e5cc8bee4028403ca0d525d/utils/datasets.py#L277)?

What's the difference? do you just read the first?

**Comment by glenn-jocher** [comment]
@hdnh2006 the purpose of line 277 is in the comment of line 277
https://github.com/ultralytics/yolov5/blob/82e865a10d31a1118e5cc8bee4028403ca0d525d/utils/datasets.py#L277
