### ISSUE TITLE
INT8 engine for yolov8 model with imgsz=3040

### ISSUE THREAD

**Issue by sergii-matiukha** [ultralytics/yolov5#11502]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to make INT8 engine for yolov8 model with imgsz=3040,  for use in deepstream python app on jetson? And how much does the accuracy drop when switching from Fp32 to INT8?

**Comment by glenn-jocher** [comment]
@sergii-matiukha hello!

For the YOLOv5 model, the INT8 engine can be generated using TensorRT. You may refer to Nvidia's official documentation for the detailed instructions on how to generate the INT8 engine for your model with TensorRT.

Regarding the accuracy drop when switching from FP32 to INT8, the drop in accuracy can vary based on the dataset, the complexity of the model, and the precision of the quantization. However, in general, INT8 quantization results in a minimal loss of accuracy while offering a significant improvement in throughput and latency.

I hope that helps! Let me know if you have any further questions or concerns.
