### ISSUE TITLE
numpy.core._exceptions.MemoryError

### ISSUE THREAD

**Issue by Kushgupta1121** [ultralytics/yolov5#11515]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm trying to train YOLOv5,(5x6) model for 300 epochs with 1101600 images in the training set and 273600 images in the validation set. I'm using a 12 GB TitanX GPU. During training the GPU memory usage is around 3.34 GB. The server has 30 GB of ram. However, after the validation, it failed with **error:  numpy.core._exceptions.MemoryError: Unable to allocate 3.40 GiB for an array with shape (45638241, 10) and data type float64.**

Ref:
![image](https://github.com/ultralytics/yolov5/assets/101636931/81df6db5-bb9d-4711-893a-b4d24da5390e)

The first epoch is trained for 15+ hours and validation runs for 1.15 hrs but it's failing with memory issues. Any remarks to resolve the issue would be appreciated. Also, is there any way to reduce the training time with the current Hardware setup?

**Comment by glenn-jocher** [comment]
@Kushgupta1121 hi there,

It seems the error is related to memory allocation to a numpy array. Since your GPU memory usage is around 3.34 GB, it could be possible that the RAM is running out of memory during validation. One approach could be to reduce the batch size and try again to see if it decreases memory usage. Also, try disabling unnecessary augmentation operations if any in the dataset configuration. 

Regarding reducing training time, one approach would be to use mixed precision training which reduces memory usage and can speed up training by nearly 2x on supported GPUs. There is an option in the repository configuration for mixed precision training.

Best,  
Glenn Jocher

**Comment by Kushgupta1121** [comment]
@glenn-jocher Thank you for your response. I'll try the suggestions regarding the memory issue.

Can you please know where in the repository configuration can i find the option for mixed precision training?

**Comment by glenn-jocher** [comment]
@Kushgupta1121, you're welcome. The option for mixed precision training in YOLOv5's repository configuration can be found in the training configuration file `yolov5s.yaml`. You have to set `precision: 16` for mixed precision training.

Let me know if you have any further questions.

Regards,  
Glenn Jocher

**Comment by Kushgupta1121** [comment]
@glenn-jocher  Thank you for the response. Did you mean i have to modify the model yaml file like this (at line 12)?
![image](https://github.com/ultralytics/yolov5/assets/101636931/79926de5-99fa-4534-b7c4-e4c454e9f824)

**Comment by glenn-jocher** [comment]
@Kushgupta1121 Yes, that's correct. You have to set `precision: 16` in the model yaml file for mixed precision training. Let us know if this helps in speeding up the training process and if you have any further questions.

Regards,  
Glenn Jocher

**Comment by Kushgupta1121** [comment]
@glenn-jocher : Thanks for the confirmation. I tried re-running the job with a precision of 16, Img_size 640 and batch size of 16. However, the job failed after validating the 1st epoch with below mentioned error. I don't understand why it failed because I can see that there's enough memory to save the matrices while the job is running. Can you please help?
<img width="1291" alt="image" src="https://github.com/ultralytics/yolov5/assets/101636931/441c7c1d-20ee-4ed5-8e44-665bc1744d68">
 
Below is the output of the HTOP command used to monitor the memory usage while the job is running
![image](https://github.com/ultralytics/yolov5/assets/101636931/d057b39a-dde4-4699-91cc-a17f2579ee11)

Output of watch -n 1 -d free -g
![image](https://github.com/ultralytics/yolov5/assets/101636931/3e53277e-043c-4c46-af89-7c596116a899)

GPU memory usage while the job is running.
![image](https://github.com/ultralytics/yolov5/assets/101636931/c4107d34-e4ca-42ba-bcb9-9b582e5955a6)

**Comment by glenn-jocher** [comment]
Hi @Kushgupta1121,

Based on the error message it seems that the GPU ran out of memory while allocating some tensor arrays during training. From the information you provided, it seems like you have enough memory available on your GPU and CPU.

There could be a few reasons causing this issue:

- The batch size used for training might be too high, that it is causing the GPU memory to run out. Try reducing the batch size and check if this resolves the issue.
- There might be some residual GPU memory that is not being freed up between epochs. This sometimes happens in PyTorch with certain versions. Try releasing resources between training epochs. I can suggest the following in your train.py file after optimizer.step() call:
```torch.cuda.empty_cache()```
- There could be some issues with the configuration file that might be causing the MemoryError. If the above suggestions don't help, you can try removing any unnecessary augmentation operations in the configuration file to see if it helps.

Hope this helps. Let me know if you have any questions.

Regards,  
Glenn Jocher

**Comment by Kushgupta1121** [comment]
Hello @glenn-jocher, Thank you for the response. I've used the batch_size 16 and the precision: 16 in the model's YAML file. 
I can see that the model is getting trained, but I noticed a weird thing in the results.csv file: the train/cls_loss and the val/obj_loss are 0 for all the epochs. Moreover, the train/box_loss and the train/obj_loss are reducing but the precision and recall don't seem to change (increase) much. Below are the results. Can you please advice?

Thank you in advance.

Best regards,
Kush Gupta

<img width="1171" alt="Screenshot 2023-06-18 at 7 10 14 PM" src="https://github.com/ultralytics/yolov5/assets/101636931/6d236229-54e5-493f-ae17-7f99b48781cf">

**Comment by glenn-jocher** [comment]
Hi @Kushgupta1121,

Thank you for providing the information. I can see that you have made the necessary changes to the batch size and precision settings.

Regarding the results.csv file, it seems that the train/cls_loss and val/obj_loss values are showing as 0 for all epochs. This can happen if the loss function is not properly configured or if the model is not learning from the data. I would suggest checking the loss function configuration in your training pipeline to ensure it is set up correctly.

As for the precision and recall values not showing much improvement, there could be several factors at play. It's possible that your dataset may not have a balanced class distribution, leading to imbalanced results. Additionally, the model may require further fine-tuning or additional data augmentation techniques to improve performance.

I recommend trying the following:

1. Verify that your dataset has a balanced class distribution and consider using techniques like data augmentation or class weighting to address any imbalance.
2. Experiment with different hyperparameter settings, such as learning rate and weight decay, to find the optimal configuration for your specific dataset and model architecture.
3. Increase the number of training epochs to give the model more time to learn and improve.
4. Consider exploring other models or architectures that may be better suited for your specific task or dataset.

Remember that training deep learning models can be an iterative process, and it may require some experimentation and tuning to achieve the desired performance. I hope these suggestions help. Let me know if you have any further questions.

Best,  
Glenn Jocher
