### ISSUE TITLE
it looks like the the version of torch cause the error,may you can try to export with torch>=1.9,<=1.10.1,also compitable with the version onnx,wich i have successfullly convert the model to onnx.

### ISSUE THREAD

**Issue by ZCzzzzzz** [ultralytics/yolov5#11514]
it looks like the the version of torch cause the error,may you can try to export with torch>=1.9,<=1.10.1,also compitable with the version onnx,wich i have successfullly convert the model to onnx.
if not solved,may you also try to replace the silu with this:
```
class SiLU(Module):
 
    __constants__ = ['inplace']
    inplace: bool
 
    def __init__(self, inplace: bool = False):
        super(SiLU, self).__init__()
        self.inplace = inplace
 
    def forward(self, input: Tensor) -> Tensor:
    
        return input * torch.sigmoid(input)
 

```

_Originally posted by @Im-JimmyHu in https://github.com/ultralytics/yolov5/issues/7832#issuecomment-1127390916_

**Comment by glenn-jocher** [comment]
Thank you for bringing this issue to our attention, @ZCzzzzzz. We appreciate your help in troubleshooting the error.

We are already compatible with torch>=1.7. To solve the error with the ONNX export, you can also try downgrading your torch version, as you suggested.

Regarding the SiLU replacement, thank you for sharing the code snippet. We'll investigate it further to see how it may improve YOLOv5's performance and keep it in mind for future updates.

Please let us know if there's anything else we can assist you with.
