### ISSUE TITLE
Incremental learning for YOLO model

### ISSUE THREAD

**Issue by anirbanmalick** [ultralytics/yolov5#1152]
## ❔Question
I have trained a custom object detection model with 5 classes. Now I want to update my saved model parameters based on some new data samples. How should I do that?

**Comment by glenn-jocher** [comment]
@anirbanmalick you start from your previously trained weights. Nothing else required.

```bash
python train.py --data custom.yaml --weights runs/exp0/weights/best.pt
```

**Comment by anirbanmalick** [comment]
got it. Thanks @glenn-jocher

**Comment by ygkrishna** [comment]
I have trained a custom object detection model with 5 classes. Now I want to re-train my model on a 6th class and the new model should detect all the 6 classes. How should I do that?

**Comment by avinashnair02** [comment]
I have trained a custom object detection model with 100 different  classes.  I want to add more 100 classes can I use Incremental learning for the same then how?

> @anirbanmalick you start from your previously trained weights. Nothing else required.
> 
> ```shell
> python train.py --data custom.yaml --weights runs/exp0/weights/best.pt
> ```

**Comment by glenn-jocher** [comment]
@avinashnair02 see https://community.ultralytics.com/t/how-to-combine-weights-to-detect-from-multiple-datasets/38/13

**Comment by kalevikas** [comment]
How to train incremental learning model using yolo? Can you please share any repository for this

**Comment by glenn-jocher** [comment]
@kalevikas Incremental learning support is available in the latest YOLOv5. You can refer to the Ultralytics Docs for details on how to use it - https://docs.ultralytics.com/yolov5/.

**Comment by ygkrishna** [comment]
> I have trained a custom object detection model with 100 different classes. I want to add more 100 classes can I use Incremental learning for the same then how?
> 
> > @anirbanmalick you start from your previously trained weights. Nothing else required.
> > ```shell
> > python train.py --data custom.yaml --weights runs/exp0/weights/best.pt
> > ```

I think in this case, the newly trained model will start detection on the newly trained classes but not the old ones. Feel free to correct me if I am wrong.
