### ISSUE TITLE
Add multiple categories of p, r, and map to result.csv

### ISSUE THREAD

**Issue by fengzile** [ultralytics/yolov5#11524]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

What if I want to display p, r and map of all categories in result.csv when I have fewer categories? What code should I modify?

**Comment by fengzile** [comment]
Since there are only P,R and mAP values of all classes in your result.csv file, I added P,R and F1 values of each class in this.csv file (because I only have 5 classes, I want to see the distribution values of each class), but I don't know which part of the code should be modified. Could you help me point out which part?

**Comment by glenn-jocher** [comment]
@fengzile hello! 

Thank you for your question. To modify the `result.csv` file to include precision, recall, and F1 values of each class, you will need to make some changes to the `test.py` file in the YOLOv5 repository.

First, you will need to modify the `test.py` file to include additional variables to store the precision, recall, and F1 values for each class. You can do this by modifying the `results` dictionary that is used to store the evaluation results.

Next, you will need to modify the code that writes the evaluation results to the `result.csv` file. You can add code to write the precision, recall, and F1 values for each class to the file, along with the existing values for all classes.

I hope this helps! Let me know if you have any additional questions or if there is anything else I can do to assist you.
