### ISSUE TITLE
While using `classify/predict.py`, how can I specify nested folder of test images as source?

### ISSUE THREAD

**Issue by sohang3112** [ultralytics/yolov5#11532]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have a nested folder structure like this:
```
data
|- folder1
    |- sub1
        |- img1.jpg
        |- img2.jpg
    |- sub2
        |- img.jpg
|- folder2
    |- sub
        |- another_img.jpg
```
A flat folder of just images (no sub-folders) can be specified as source to `classify/predict.py`:
```python3 classify/predict.py --weights yolov5s-cls.pt --source /path/to/data/folder1/sub1/```

Does `classify/predict.py` have any way of allowing nested folder `data` as source?

**Comment by sohang3112** [comment]
I found the solution using globs 🙂:

```python3 classify/predict.py --weights yolov5s-cls.pt --source /path/to/data/*/*/*.jpg```

**Comment by glenn-jocher** [comment]
@sohang3112 thank you for sharing your solution with the community! 

Yes, using globs is a great approach to work with nested folders as source in `classify/predict.py`. It's good to know that you were able to find a way to specify the path to those images. 

If you have any further questions, don't hesistate to ask.
