### ISSUE TITLE
HSV close

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#11533]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to close the hsv augmentation for training?
set the value to 0.0 on the file ?
```
hsv_h: 0.015  # image HSV-Hue augmentation (fraction)
hsv_s: 0.7  # image HSV-Saturation augmentation (fraction)
hsv_v: 0.4  # image HSV-Value augmentation (fraction)
```

**Comment by glenn-jocher** [comment]
@alicera hello, 

To disable the HSV augmentation during training, you can set the values of `hsv_h`, `hsv_s`, and `hsv_v` to 0 in the train.yaml settings file. 

Let us know if you have any more questions.

Thank you.

**Comment by alicera** [comment]
Is the value the probability

**Comment by glenn-jocher** [comment]
@alicera hello,

Can you please provide more context about your question? Which value are you referring to? It would be helpful if you could provide more information, so we can better assist you.

Looking forward to your response.

**Comment by alicera** [comment]
Thanks for your reply

Is it mean hsv_h = 1.5%
hsv_s: 70% 
The probability of change the hsv value

```
hsv_h: 0.015  # image HSV-Hue augmentation (fraction)
hsv_s: 0.7  # image HSV-Saturation augmentation (fraction)
hsv_v: 0.4  # image HSV-Value augmentation (fraction)
```

**Comment by glenn-jocher** [comment]
@alicera hello,

Thank you for your question.

Regarding the `hsv_h`, `hsv_s`, and `hsv_v` values in the training config file, the numbers represent the fractions of how much the corresponding image channel can be modified. Therefore, `hsv_h: 0.015` represents a 1.5% adjustment fraction for the Hue channel, `hsv_s: 0.7` represents a 70% adjustment fraction for the Saturation channel, and `hsv_v: 0.4` represents a 40% adjustment fraction for the Value channel.

I hope this helps. If you have further questions or concerns, please let me know.

Thank you.
