### ISSUE TITLE
Callbacks are not running

### ISSUE THREAD

**Issue by muhammadariffaizin** [ultralytics/yolov5#11540]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

I want to add autocopy_gdrive callback when the training was running, but the process fails and reproduce the some errors

### yaml_save error
![image](https://github.com/ultralytics/yolov5/assets/49377980/76ebfb16-4dc9-48d2-9ad6-e4608d0c4718)

After finding the errors, I think the problem was here

![image](https://github.com/ultralytics/yolov5/assets/49377980/8d94ee45-3371-4978-a1fb-8b3aef5c8181)

the `<utils.callbacks.Callbacks object>` or callbacks function are cannot be saved to .yaml file, and then for temporarily I must to comment that line in `train.py` and it works

### Callbacks option are not passed
After that, I run again with no errors, but the autocopy_gdrive callback was not called since there are no messages "Success running callback" as mentioned in the reproducible example below

Again, after finding errors, I found that 

train.py
![image](https://github.com/ultralytics/yolov5/assets/49377980/6a61c8fa-3752-4fed-8690-f3175956d273)
![image](https://github.com/ultralytics/yolov5/assets/49377980/3bb46bef-e94a-40b8-b0d9-af5c3e0b968c)

the `run(**kwargs)` function seems to not passing the `callbacks` argument in `main(opt, callbacks=Callbacks())` function

so, I modified some line of the code as below
```py
def run(**kwargs):
    # Usage: import train; train.run(data='coco128.yaml', imgsz=320, weights='yolov5m.pt')
    opt = parse_opt(True)
    for k, v in kwargs.items():
        setattr(opt, k, v)
    main(opt, opt.callbacks)
    return opt
```
After that, the callbacks are success to run

### Minimal Reproducible Example

The callback code are below
```py
import shutil
import os
from utils.callbacks import Callbacks

autocopy_gdrive_callback = Callbacks()
def autocopy_gdrive(*args):
  src_weight_dir = "/content/yolov5/runs/train/yolov5s_results/weights"
  dest_weight_dir = "/content/gdrive/MyDrive/weights"
  print("Success running callback")
  if os.path.exists(src_weight_dir):
    shutil.copytree(src_weight_dir, dest_weight_dir, dirs_exist_ok=True)
    print("Success copying " + src_weight_dir + " to " + dest_weight_dir)

autocopy_gdrive_callback.register_action('on_train_epoch_start', name='autocopy_gdrive', callback=autocopy_gdrive)
```
And the train code are below
```py
import train

train.run(data=f'{dataset.location}/data.yaml',
          name='yolov5s_results', 
          cfg='./models/custom_yolov5s.yaml',
          imgsz=640, 
          epochs=2000,
          batch=16,
          weights='',
          cache=True,
          save_period=100,
          callbacks=autocopy_gdrive_callback
        )
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello @muhammadariffaizin, 

Thank you for reaching out and providing a detailed summary of the issues that you are experiencing with running callbacks in YOLOv5. We appreciate your interest in using callbacks, as they are a powerful tool for modifying the behavior of the YOLOv5 training process according to your needs.

From the errors that you have encountered, it appears that there were problems with saving your specified `Callbacks` object to a YAML file and passing the `callbacks` argument to the `main()` function. 

Thank you for taking the time to identify the root cause of the issue and propose a solution. We will take note of your suggestion to modify the `run()` function to pass the `callbacks` argument properly.

If you encounter any further issues or have any questions, please feel free to ask. We're happy to help!

**Comment by muhammadariffaizin** [comment]
Is there any solution for this problem? or is there any possible implementation of using the callbacks currently?
Thank you so much

**Comment by glenn-jocher** [comment]
@muhammadariffaizin hello!

Thank you for reaching out about using callbacks in YOLOv5. We apologize for the inconvenience that you may have experienced while using callbacks in YOLOv5.

We want to let you know that we are currently investigating this issue and we will provide a solution as soon as possible. In the meantime, we suggest that you continue to use the other available functionalities within YOLOv5.

We appreciate your patience and understanding as we work to provide a fix for this. If you have any further questions or concerns, please do not hesitate to ask. We're here to help!

**Comment by muhammadariffaizin** [comment]
Thanks for the respond, I'll be waiting for the update

**Comment by glenn-jocher** [comment]
Hello @muhammadariffaizin,

Thank you for your patience while we investigate the issue with using callbacks in YOLOv5. We assure you that our team is working diligently on providing a solution for this as soon as possible. We appreciate your understanding and willingness to use YOLOv5 for your object detection needs.

If you have any other concerns or questions, please feel free to ask. We are always here to help!

**Comment by iiizanagiii** [comment]
Hello @glenn-jocher,

Getting to the same topic here, regarding callbacks can you assist some solutions to this problem. I am not getting any advantage over this problem.

**Comment by muhammadariffaizin** [comment]
I'm sorry, is there any solution for this problem?
I didn't getting any solution since the issues was found

**Comment by glenn-jocher** [comment]
@muhammadariffaizin hello,

Thank you for reaching out about the YOLOv5 issue. We apologize for the delay in providing a solution for the problem you are facing. Our team is actively working on addressing this issue and finding a resolution as soon as possible. We appreciate your patience and apologize for any inconvenience caused.

If you have any further questions or concerns, please let us know. We are here to help!

Thank you,
The YOLOv5 Team

**Comment by raushani2v** [comment]
Hi @glenn-jocher , Is there any update on the issue?

**Comment by glenn-jocher** [comment]
Hello @raushani2v,

I apologize for the delay in resolving the callback issue you've encountered with YOLOv5. We are still working on a fix for this problem. Your patience is greatly appreciated, and we understand the importance of this feature for your work.

Please keep an eye on the repository for updates, and we will ensure to address this as soon as possible. If you have any more questions or need further assistance, feel free to reach out.

Thank you for your understanding and support.
