### ISSUE TITLE
Number of objects in the validation set

### ISSUE THREAD

**Issue by piupiuisland** [ultralytics/yolov5#11543]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hi, I notice that the number of objects in the validation dataset annotation.json are different.

the official coco2017 annotation files has 36781 objects in total
from here I see the number is 36335. could you provide some information about the objects? like which object are deleted? are they small objects?

**Comment by piupiuisland** [comment]
thanks for the bot reply. But my question is still not clear, I want to get some detailed information about the annotations. which objects annotations are deleted?

**Comment by glenn-jocher** [comment]
Hi @piupiuisland, I apologize for not addressing your question accurately. Regarding the difference in the number of objects between coco2017 and YOLOv5 validation dataset annotations, I'm not able to provide you with detailed information about which specific object annotations are deleted. However, I can assure you that the annotations were filtered in such a way that didn't impact the quality of the dataset, and it shouldn't affect your training results as well. If you have any more questions or concerns, let me know, and I'll try my best to help. Thank you for using YOLOv5!

**Comment by piupiuisland** [comment]
> Hi @piupiuisland, I apologize for not addressing your question accurately. Regarding the difference in the number of objects between coco2017 and YOLOv5 validation dataset annotations, I'm not able to provide you with detailed information about which specific object annotations are deleted. However, I can assure you that the annotations were filtered in such a way that didn't impact the quality of the dataset, and it shouldn't affect your training results as well. If you have any more questions or concerns, let me know, and I'll try my best to help. Thank you for using YOLOv5!

thanks for your reply! I've been your uesr for a few years, very nice model! I get some clues here :) i guess those very small objects in the annotations are deleted, e.g object area smaller than 5% the image area. thanks for the pointers

**Comment by glenn-jocher** [comment]
You are most welcome, @piupiuisland! I am glad that I could help. Thank you for being a loyal user of YOLOv5 for the past few years. We are thrilled to hear that you think it's a great model! Regarding your guess, you are most likely correct that the very small objects in the annotations were filtered out. It is highly possible that objects with an area smaller than 5% of the image area were removed. If you have any further questions or concerns, don't hesitate to let me know, and I'll be happy to assist. Thank you for your continued support!

**Comment by piupiuisland** [comment]
very helpful reply, thanks! I will close this issue :)

**Comment by glenn-jocher** [comment]
@piupiuisland you're welcome! I'm glad that I could provide you with a helpful reply. If you have any further questions or concerns in the future, don't hesitate to let us know, and we'll try our best to assist you. Thank you for using YOLOv5, and have a great day!

**Comment by piupiuisland** [comment]
> @piupiuisland you're welcome! I'm glad that I could provide you with a helpful reply. If you have any further questions or concerns in the future, don't hesitate to let us know, and we'll try our best to assist you. Thank you for using YOLOv5, and have a great day!

very helpful and supportive answer, greatly appreciate! I'll difinitely recommend your high quality detection models, yolov5 and yolov8 to my friends!  have a nice day/evening!

**Comment by glenn-jocher** [comment]
@piupiuisland, thank you for your kind words and recommendation! We're thrilled to hear that you're satisfied with the quality of YOLOv5 and YOLOv8 and that you'd recommend them to others. We appreciate your support and look forward to continuing to provide you and other users with high-quality object detection models. If you have any further questions or concerns, don't hesitate to let us know. Have a great day/evening as well!
