### ISSUE TITLE
Effect of resizing images prior to training, Good or Bad?

### ISSUE THREAD

**Issue by redwankarimsony** [ultralytics/yolov5#1154]
## ❔Effect of resizing images prior to training, Good or Bad? 

I want to train yolov5 with a **custom dataset that has variable image sizes**. I have managed to produce the label files accordingly. I know, yolov5 can resize them at the training time. However, if I resize the images **(without keeping the aspect ratio)**  before training into a fixed shape **`(640x640)`**, it reduces the training time per epoch but can it hurt the learning performance?

**Comment by glenn-jocher** [comment]
@redwankarimsony recommend you simply follow the custom training tutorial steps, and examine coco128 for what works in a dataset.

**Comment by glenn-jocher** [comment]
https://docs.ultralytics.com/yolov5

**Comment by Aktcob** [comment]
@redwankarimsony Try it and issue
