### ISSUE TITLE
Why do I suddenly need to pip install the ultralytics library to get yolov5 from torch hub?

### ISSUE THREAD

**Issue by dtronmans** [ultralytics/yolov5#11544]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I was always able to load yolov5 and run inference using the following lines:

`import torch

model = torch.hub.load('ultralytics/yolov5', 'custom', path=weights_path)`

and I never needed to run pip install ultralytics in order to run this code. However, since a few days ago suddenly I am no longer able to run this code without having the "ultralytics" library installed, which unfortunately is quite annoying for my code because it requires quite high version numbers for some packages, which I am not able to do because my code relies on some older versions of some libraries. Is this new? Is there anything I could do to run this code with just having torch installed?

EDIT: I now see the following Pull Request: https://github.com/ultralytics/yolov5/pull/11529 that was closed 3 days ago, which I think is the source of the problem. This is quite annoying because it also comes with me having to install a new pip package with a lot of different version requirements for different libraries that come with it. Any way to circumvent that?

**Comment by glenn-jocher** [comment]
@dtronmans hi there,

I'm sorry to hear that you are experiencing some issues with loading YOLOv5 model without installing the "ultralytics" library recently. This is a result of a recent pull request, as you have mentioned in your edit. 

Unfortunately, it is now required to have the "ultralytics" library installed to load the YOLOv5 model. The good news is that the installation process is quick and easy. 

Regarding the issue of high version numbers for some packages with the "ultralytics" library, I suggest trying to create a virtual environment and install all the required packages and dependencies within the virtual environment to avoid conflict with the current version of your libraries. 

Please let us know if you have any other questions or concerns. We are here to help.

**Comment by dtronmans** [comment]
Hey @glenn-jocher,

Thank you for the quick answer! I am indeed already installing everything in a virtual environment. However I will try to make the dependencies work with each other by being less strict on the versions for current packages.

Best regards

**Comment by glenn-jocher** [comment]
@dtronmans,

You're welcome! I'm glad that I could be of help.

Yes, that sounds like a good plan. If you have any further questions or concerns, please do not hesitate to let us know. We would be happy to assist you.

Best regards,
