### ISSUE TITLE
Detect highest only the highest confidence of a particular label

### ISSUE THREAD

**Issue by fo250061** [ultralytics/yolov5#11552]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have an image that contains multiple OBJECTS, but  ONLY 1 type of an object. 
Example: An image containing 1 cat and 1 rabbit. The image can never cannot 2 cats, or 2 rabbits, etc.  The problem is that my model is detecting 2 cats (rabbit is also detected as cat) and 1 rabbit with different level of confidences when in reality I have 1 cat and 1 rabbit. 

So, is there a way to ensure that my model only takes the highest confidence and ignore others?

**Comment by glenn-jocher** [comment]
@fo250061 hello! 

One way to achieve what you're looking for is to filter the detections by label and then take only the detection with the highest confidence. In the example you provided, you would filter by the "cat" label and take only the detection with the highest confidence while ignoring any other detections with this label.

You can easily implement this in your code by using the built-in filtering functionalities in YOLOv5, such as `--filter`, `--classes`, and `--agnostic-nms` flags. You can find more information about these flags in the YOLOv5 documentation.

Let us know if you have any more questions or if there's anything we can help with!

**Comment by fo250061** [comment]
I tried the classes but it didn't work. I couldn't locate the filter attribute and the agnostic-nms. 
https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading/#detailed-example:~:text=model.conf,custom%20inference%20size

Also, does the filtering ensure that the bounding boxes are not drawn for those predictions?

**Comment by glenn-jocher** [comment]
@fo250061 Got it! To achieve what you're looking for, you can use the `--filter` and `--conf-thres` flags in your inference command. Here's an example command:

```bash
python detect.py --source <image or video> --weights <weights> --conf 0.4 --filter cat
```

In this command, `--conf` sets the minimum object confidence, and `--filter` ensures that only the specified class is displayed. The bounding boxes for non-cat predictions won't be drawn with this setup.

Would you like further assistance with this or any additional questions?
