### ISSUE TITLE
Remove models and utils folders for detection

### ISSUE THREAD

**Issue by fjsaezm** [ultralytics/yolov5#1155]
Hi there!

I have trained the model in my own dataset and the results are great! I'm quite happy with it!

Now I want to use the trained model in an app and, in order to save some space, I'd like to have only 1 scripts for it that does the job, and obviously the weights file.

However, if I delete the folders **models** and **utils** in order to do inference, I get errors trying to load the weights file with torch.

```python
result = unpickler.load()
...
from utils.general import check_anchor_order, make_divisible, check_file
ModuleNotFoundError: No module named 'utils.general'
```

If I dont delete these folders, the model works perfectly fine.

Is there any way to save the weights or change any configuration so that I don't need to have these 2 folders where I want to make the inference?

Thank you!

**Comment by glenn-jocher** [comment]
@fjsaezm see export tutorial https://docs.ultralytics.com/yolov5 for standalone YOLOv5 inference.

**Comment by glenn-jocher** [comment]
BTW, for pytorch inference, the module dependencies are required to be available in your system path. The folders do not need to be at a high level, but they do need to be present, just like you can not run torch commands without importing torch.

**Comment by fjsaezm** [comment]
Ok, so I've assumed that these folders will have to be in my system.

So now, would It be possible to create a folder like "Resources" in which I will have 

- The two folders needed
- The detect script

And call the detect function from outside this folder?

My current Folder distribution is:

- Root
  - Folder1
     - Resources: the folder that contains what I mentioned before

Is it possible to call the detect function from a script located in "Root"? I'm trying to do it and I'm getting  the exact same error that I mentioned above...

**Comment by glenn-jocher** [comment]
@fjsaezm you probably want to load YOLOv5 from torch hub, where pytorch automatically downloads the yolov5 repo and adds it to your sys path. You can run inference directly on a PIL image or cv2 image and everything is handled automatically.

The torch hub tutorial has recently been updated here: https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading

**Comment by fjsaezm** [comment]
Thank you for your answer! 

However, I think it doesnt solve my problem, since that loads a *pretrained* YOLOv5 and I'd like to use my own weights.

Is there any way to load my weights? Do I have to train it again after loading YOLOv5 from torch hub?

Thank you again!

**Comment by glenn-jocher** [comment]
@fjsaezm you'd need to swap your model params in. There are many pytorch examples on the web for this.

**Comment by MuhammadShifa** [comment]
Hello @fjsaezm !
Have you solved this issue, I am also facing the same issue. I want to combine pose estimation of yolov7 with custom yolov5 for object detection but facing model import issue as both have models folder in their repo. Can you help me please @glenn-jocher

**Comment by glenn-jocher** [comment]
Hey @MuhammadShifa! We currently don't support YOLOv7 as it's not an official release. Regarding combining pose estimation with YOLOv5, you might want to consider creating a custom model that combines both functionalities. Feel free to check out the Ultralytics YOLOv5 documentation for guidance: https://docs.ultralytics.com/yolov5/ 🚀
