### ISSUE TITLE
Loading custom model does not work

### ISSUE THREAD

**Issue by zkytony** [ultralytics/yolov5#11553]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Previously, I can load a **custom** pretrained model like this:
```python
torch.hub.load('ultralytics/yolov5', 'custom', path='path/to/model.pt')
```
However, after some recent developments (see issues below for related problems that occur after those developments).
*  https://github.com/ultralytics/yolov5/issues/11544
* https://github.com/ultralytics/yolov5/issues/11481
* https://github.com/ultralytics/yolov5/issues/11448
* https://github.com/ultralytics/yolov5/issues/11530
the above line of code does not work any more. Running it I get
```
Exception: [Errno 20] Not a directory: 'path/to/model.py'. Cache may be out o
f date, try `force_reload=True` or see https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_mode
l_loading for help.
```

I followed the suggestion and add `force_reload=True`:
```python
torch.hub.load('ultralytics/yolov5', 'custom', path='path/to/model.pt', force_reload=True)
```
I am **getting the SAME error**:
```
Exception: [Errno 20] Not a directory: 'path/to/model.py'. Cache may be out of date, try `force_reload=True` or see https://docs.ultralytics.com
/yolov5/tutorials/pytorch_hub_model_loading for help.
```

What is going on with yolov5?

### Environment

- YOLOv5
- ubuntu 22.04
- python 3.10.6
- torch 1.13.1+cu17

### Minimal Reproducible Example

```
torch.hub.load('ultralytics/yolov5', 'custom', path='path/to/model.pt')
```
Choose a model path to replace `'path/to/model.pt'`

### Additional

No

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by zkytony** [comment]
Never mind.  My path was wrong and I didn't realize it sorry:(

This may be helpful to others who run into a similar situation.

**Comment by glenn-jocher** [comment]
@zkytony no worries at all! It's great to hear that you were able to solve the issue. Don't hesitate to reach out if you have any further questions or concerns. Thank you for your support and happy coding!

**Comment by developerlaborotory** [comment]
I just had to reset my pc xD

**Comment by glenn-jocher** [comment]
@developerlaborotory not a problem at all! Sometimes a reset can help with unforeseen issues. If you have any further questions or run into any other problems, feel free to ask. Happy coding!
