### ISSUE TITLE
3D coordinates of detected objects in the detect.py 

### ISSUE THREAD

**Issue by csmab** [ultralytics/yolov5#11559]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to add a function to display the 3D coordinates of detected objects in the detect.py file using camera d435i

### Additional

no else

**Comment by glenn-jocher** [comment]
@csmab hello! You can use the camera extrinsic calibration parameters along with the detected object bounding box coordinates to project the 2D pixel coordinates onto the 3D space. The D435i camera provides depth information, which can be used to obtain the depth (third) coordinate of the object. 

Here are the general steps you can follow to obtain the 3D coordinates:

1. Obtain the camera intrinsic and extrinsic calibration parameters. You can use `rs2::pipeline` to stream from the D435i and obtain these parameters. 
2. Use the YOLOv5 `detect.py` file to obtain the 2D pixel coordinates of the detected objects.
3. Convert the 2D pixel coordinates to the camera coordinates using the camera intrinsic calibration parameters. 
4. Use the obtained camera coordinates and the camera extrinsic calibration parameters to project onto the 3D space and obtain the 3D coordinates.


I hope this helps! Let me know if you have any further questions.

**Comment by csmab** [comment]
Thank you very much for your idea, I will try it

**Comment by glenn-jocher** [comment]
@csmab you're welcome! Feel free to reach out if you have any questions while implementing it. Good luck with your project!
