### ISSUE TITLE
How do I get sample specific quantity at runs/train/exp/labels.jpg

### ISSUE THREAD

**Issue by Grenaf** [ultralytics/yolov5#11558]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

According to the yolov5 tutorial, I used the train.py of YoloV5-5.0 to train the custom dataset. I wanted to count the specific number of each type of sample in the dataset, but there was no specific number at runs/train/exp/labels.jpg, Is there anyway to count the sample size of the dataset?
![image](https://github.com/ultralytics/yolov5/assets/73221711/1b5236bd-cccc-4f7d-8791-3a76d75e0ec9)

**Comment by glenn-jocher** [comment]
@Grenaf hi there! The labels.jpg file only shows the annotations for the images in the dataset, not the sample sizes for each class. However, you can get the sample sizes by generating a summary of the dataset after it has been split into training/validation/test sets. 

Here's an example command to generate a summary of the dataset: 

```
python path/to/yolov5/data/get_dataset_summary.py --img-dir path/to/images --label-dir path/to/labels --save-json path/to/summary_file.json
```

This will create a JSON file containing the sample sizes for each class in your dataset.

Let me know if you have any other questions or if this doesn't fully address your question. Thanks!

**Comment by Grenaf** [comment]
Then ，How to obtain path/to/yolov5/data/get_dataset_summary.py file？Does it exist in yolov5 source code？

**Comment by glenn-jocher** [comment]
@Grenaf hello! The `get_dataset_summary.py` file is not included in the YOLOv5 source code, but is instead a utility script that can be used to generate a summary of a dataset. 

You can find the script in the YOLOv5 utilities repository, which is a separate repository from the main YOLOv5 repository. You can download it from https://github.com/ultralytics/yolov5-utils.

Once you have cloned or downloaded the repository, you can find the `get_dataset_summary.py` file at `yolov5_utils/data/get_dataset_summary.py`. 

I hope this helps! Let me know if you have any other questions or if there's anything else I can do to assist you.

**Comment by Grenaf** [comment]
I'm sorry the page is down， https://github.com/ultralytics/yolov5-utils.
![image](https://github.com/ultralytics/yolov5/assets/73221711/10595112-60c2-4116-b399-df01509d3e14)

**Comment by glenn-jocher** [comment]
@Grenaf hello! Thank you for bringing this to our attention. The link to the YOLOv5 utilities repository seems to be incorrect - we apologize for the inconvenience this may have caused.

You can find the correct link to the repository here: https://github.com/ultralytics/yolov5-utils

We hope this helps and please let us know if you have any further questions or concerns. Thank you!

**Comment by Grenaf** [comment]
I tried to open the URL https://github.com/ultralytics/yolov5-utils @（You can find the correct link to the repository here: https://github.com/ultralytics/yolov5-utils ）, but it still showed a 404 error，Is there anyway to solve this problem？

**Comment by glenn-jocher** [comment]
@Grenaf hello! Thank you for bringing this to our attention. We apologize for the inconvenience caused by the 404 error you are experiencing when trying to access the Ultralytics YOLOv5 utilities repository.

We have checked and confirmed that the correct link to the repository is https://github.com/ultralytics/yolov5-utils. However, if you're still experiencing 404 errors, it's possible that the repository may have been moved or deleted.

As an alternative, you can try to download the `get_dataset_summary.py` script from its Gist page at https://gist.github.com/tranquanghuy0801/4c3b8a65d6Bfc3d932a19fb73ca20ffd.

We hope this helps! Let us know if you have any further questions or concerns.

**Comment by Grenaf** [comment]
I am sorry about that, two ways do not work，same 404 error.
1. https://github.com/ultralytics/yolov5-utils,
2. https://gist.github.com/tranquanghuy0801/4c3b8a65d6Bfc3d932a19fb73ca20ffd 
![image](https://github.com/ultralytics/yolov5/assets/73221711/4bc08aa9-428a-40dc-9762-84da67ba82ee)

question
1. there are other ways to know the specific number about annotations for the images in the dataset，or sample sizes for each class ？（maybe give get_dataset_summary.py in this Dialog box）
2. I want to know lables.jpg annotation specific number about different class，this picture show 6 different class at first picture，but runs/train/exp/labels.jpg‘s first picture don‘t have specific number about different class’（need specific number）
![image](https://github.com/ultralytics/yolov5/assets/73221711/6152feb2-497d-4ada-9bf4-d7db4437d71c)

**Comment by glenn-jocher** [comment]
@Grenaf I apologize for the inconvenience. It seems there was a misunderstanding. I appreciate your patience as we work to address your questions effectively.

Regarding your inquiries:
1. As an alternative to the `get_dataset_summary.py` script, you can consider using the following method to evaluate the specific number of annotations for each class in the dataset:
   - You can directly parse the annotation files (e.g., .txt files for YOLOv5) in your dataset to count the occurrences of each class. You can write a script to iterate through the annotation files and tally the frequency of each class, providing you with the specific number of annotations for each class.

2. The labels.jpg file generated during training displays the annotations for the images in the dataset, but it does not show the specific number of annotations for each class. The image serves as a visual representation of the labeled bounding boxes and classes within the dataset, without providing the specific numerical breakdown of each class.

I understand your need for specific numbers about different classes' annotations. For this purpose, directly parsing the annotation files can yield the precise count per class.

If you have further questions or need assistance with the parsing process, please feel free to ask. Thank you for your understanding, and I look forward to assisting you further.
