### ISSUE TITLE
YOLOv5 detect.py only detect first 49 frames of a video

### ISSUE THREAD

**Issue by KDLPro** [ultralytics/yolov5#11551]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

I tried to use detect.py to detect tree branches in a video, but unfortunately, it only detects objects within the first 49 frames. How can I fix this? I don't know what went wrong: the video itself, or something in detect.py.

CMD result: ```
python310 detect.py --weights weights/best.pt --source "/d/Documents/Commissions/Inference Videos/GH014308.MP4"
detect: weights=['weights/best.pt'], source=D:/Documents/Commissions/Inference Videos/GH014308.MP4, data=data\coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs\detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False      
YOLOv5  51c821d Python-3.10.4 torch-2.0.1+cu118 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)

Fusing layers... 
Model summary: 213 layers, 7012822 parameters, 0 gradients
video 1/1 (1/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.163s)
video 1/1 (2/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.017s)
video 1/1 (3/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 1 mahogany tree part, Done. (0.012s)
video 1/1 (4/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 1 mahogany tree part, Done. (0.018s)
video 1/1 (5/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 1 mahogany tree part, Done. (0.015s)
video 1/1 (6/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 1 mahogany tree part, Done. (0.011s)
video 1/1 (7/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 1 mahogany tree part, Done. (0.019s)
video 1/1 (8/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 1 mahogany tree part, Done. (0.017s)
video 1/1 (9/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.030s)
video 1/1 (10/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.028s)
video 1/1 (11/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.021s)
video 1/1 (12/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.026s)
video 1/1 (13/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.029s)
video 1/1 (14/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.024s)
video 1/1 (15/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.025s)
video 1/1 (16/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 1 mahogany tree part, Done. (0.026s)
video 1/1 (17/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.037s)
video 1/1 (18/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.025s)
video 1/1 (19/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.039s)
video 1/1 (20/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.027s)
video 1/1 (21/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.025s)
video 1/1 (22/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.023s)
video 1/1 (23/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.025s)
video 1/1 (24/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.027s)
video 1/1 (25/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.026s)
video 1/1 (26/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.025s)
video 1/1 (27/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.030s)
video 1/1 (28/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.023s)
video 1/1 (29/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.025s)
video 1/1 (30/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.031s)
video 1/1 (31/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.030s)
video 1/1 (32/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.028s)
video 1/1 (33/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.030s)
video 1/1 (34/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.030s)
video 1/1 (35/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.028s)
video 1/1 (36/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.026s)
video 1/1 (37/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.030s)
video 1/1 (38/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.027s)
video 1/1 (39/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.025s)
video 1/1 (40/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.024s)
video 1/1 (41/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.027s)
video 1/1 (42/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.025s)
video 1/1 (43/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.025s)
video 1/1 (44/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.029s)
video 1/1 (45/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.026s)
video 1/1 (46/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.028s)
video 1/1 (47/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.025s)
video 1/1 (48/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.025s)
video 1/1 (49/2439) D:\Documents\Commissions\Inference Videos\GH014308.MP4: 384x640 Done. (0.024s)
Speed: 2.1ms pre-process, 28.2ms inference, 4.3ms NMS per image at shape (1, 3, 640, 640)
Results saved to runs\detect\exp11
(yolov5-instance) ```

Screenshot: 
<img width="561" alt="image" src="https://github.com/ultralytics/yolov5/assets/38602758/ad080a69-de89-46a1-9837-ec0d914a7f47">

### Environment

YOLO: YOLOv5  51c821d Python-3.10.4 torch-2.0.1+cu118 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
OS: Windows 11
Python: 3.10.4

### Minimal Reproducible Example

Here's the video that I used for inferencing: https://1drv.ms/u/s!AutrB3BUl5yahL16N5KdRkIet2Xbdw?e=2d9BrW

Weights: https://1drv.ms/u/s!AutrB3BUl5yahL17Mb5zLA2FdTFNQQ?e=SKdffK

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@KDLPro hello! Thank you for reaching out. Have you tried increasing the `--max-det` flag to see if it makes a difference? Also, it could be helpful to try with a shorter video to see if the issue persists. Let me know if this helps!

**Comment by KDLPro** [comment]
Thank you! I'll try to do these. I'll get back to you when I'm done @glenn-jocher.

**Comment by KDLPro** [comment]
@glenn-jocher A shorter video did the trick. Though it has errors (due to how my model was trained). So that means it's only good for short videos? Also, this video was edited from the original using Movie Maker (.mp4 instead of .MP4, though I guess that's a minor difference).

Video result to prove it's working: https://github.com/ultralytics/yolov5/assets/38602758/f08fc8b3-d8a8-4498-95f9-c6f6509884ad

Screenshot: 
<img width="561" alt="image" src="https://github.com/ultralytics/yolov5/assets/38602758/1189580d-572f-4351-8213-6dd5e56c7e92">

**Comment by glenn-jocher** [comment]
@KDLPro, I'm glad to hear that trying a shorter video worked for you! As for the video length, YOLOv5 can process longer videos, but it also depends on the hardware you are using and the complexity of your model. If you encounter errors due to how your model was trained, you may want to review and adjust your training data. And it's good to know that the format of the video file doesn't seem to make a difference. Thanks for sharing the video result and screenshot, and let us know if you have any further questions or issues.

**Comment by KDLPro** [comment]
Another screenshot: 
<img width="586" alt="image" src="https://github.com/ultralytics/yolov5/assets/38602758/6d6edc46-542b-480a-95d6-490191484b4b">

**Comment by glenn-jocher** [comment]
@KDLPro hello! I'm glad to hear that trying a shorter video worked for you. As for the video length, YOLOv5 can process longer videos, but it also depends on the hardware you are using and the complexity of your model. If you encounter errors due to how your model was trained, you may want to review and adjust your training data. And it's good to know that the format of the video file doesn't seem to make a difference. Thank you for sharing the video result and screenshot, and let us know if you have any further questions or issues.

**Comment by KDLPro** [comment]
Sure thing, thank you!

**Comment by glenn-jocher** [comment]
@KDLPro hi there! Thank you for sharing your issue with YOLOv5. I'm glad to hear that using a shorter video helped resolve the issue you were experiencing. While YOLOv5 can process longer videos, it also depends on the hardware used and the complexity of the model. If you continue to experience errors, it may be helpful to review and adjust your training data. Thank you for sharing the screenshot and video result, and let us know if you have any further questions or issues.

**Comment by KDLPro** [comment]
@glenn-jocher Sure thing. Thanks for your help!

**Comment by glenn-jocher** [comment]
Hi @KDLPro, glad to hear that using a shorter video helped resolve the issue you were experiencing with YOLOv5. While YOLOv5 can process longer videos, it also depends on the hardware used and the complexity of the model. If you continue to experience errors, it may be helpful to review and adjust your training data. Thank you for sharing the screenshot and video result, and please feel free to let us know if you have any further questions or issues.
