### ISSUE TITLE
Cannot load yolov5 model in multiprocessing mode

### ISSUE THREAD

**Issue by wxthu** [ultralytics/yolov5#11569]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

PyTorch Hub

### Bug

I set start method like  `multiprocessing.set_start_method('spawn', force=True)` and load yolo model in pytorch `model = torch.hub.load('ultralytics/yolov5', task).eval().half()` . Then I pass the model to multiprocessing function and  following errors happened ....
<img width="1030" alt="image" src="https://github.com/ultralytics/yolov5/assets/73052387/fdcaba30-5d29-40d9-8be8-38c5127a1f54">

### Environment

Python-3.7.16 torch-1.8.1+cu102 CUDA:0 (Tesla T4, 15110MiB)

CentOS 7.3

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@wxthu hello, thank you for raising this issue.

It looks like there may be a compatibility issue with using multiprocessing and loading the YOLOv5 model. You can try passing the arguments needed for the multiprocessing function as function arguments instead of using a global variable. Another option you can try is to load the YOLOv5 model only once, regardless of how many processes you're using, so that it's not loaded multiple times.

Unfortunately, we currently do not support multiprocessing usage with YOLOv5, but we appreciate your feedback and can consider adding support in the future.

Let us know if you have any other questions or concerns.

**Comment by wxthu** [comment]
> @wxthu hello, thank you for raising this issue.
> 
> It looks like there may be a compatibility issue with using multiprocessing and loading the YOLOv5 model. You can try passing the arguments needed for the multiprocessing function as function arguments instead of using a global variable. Another option you can try is to load the YOLOv5 model only once, regardless of how many processes you're using, so that it's not loaded multiple times.
> 
> Unfortunately, we currently do not support multiprocessing usage with YOLOv5, but we appreciate your feedback and can consider adding support in the future.
> 
> Let us know if you have any other questions or concerns.

Thanks for your reply and I have tried you suggestions but still failed. For example,

```
class Task(multiprocessing.Process):
       def __init__(self, model):
             super().__init__()
             self.model = model
             ......

if __name__ == "__main__":
    multiprocessing.set_start_method('spawn', force=True)
    model = torch.hub.load('ultralytics/yolov5', task).eval().half()
    processes = []
    for i in range(4):
         processes.append(Task(model=model, ...))
```
Could you give me some further suggestions?

**Comment by glenn-jocher** [comment]
@wxthu, thanks for following up. Another thing you can try is converting the YOLOv5 model to a script module using the `torch.jit.script` function and then passing it to the multiprocessing function instead of the original module. Here's an example of how you can convert the model:

```python
model = torch.hub.load('ultralytics/yolov5', 'custom', path='yolov5s.pt')

# Convert the model to a script module
model = torch.jit.script(model)

# Define your multiprocessing function and pass the script module
def foo(script_module):
    output = script_module(input_data)
    return output

# Start your processes with the script module
if __name__ == '__main__':
    multiprocessing.set_start_method('spawn', force=True)
    processes = []
    for i in range(4):
        p = multiprocessing.Process(target=foo, args=(model,))
        processes.append(p)
        p.start()
    for p in processes:
        p.join()
```

Let me know if this helps.

**Comment by wxthu** [comment]
> @wxthu, thanks for following up. Another thing you can try is converting the YOLOv5 model to a script module using the `torch.jit.script` function and then passing it to the multiprocessing function instead of the original module. Here's an example of how you can convert the model:
> 
> ```python
> model = torch.hub.load('ultralytics/yolov5', 'custom', path='yolov5s.pt')
> 
> # Convert the model to a script module
> model = torch.jit.script(model)
> 
> # Define your multiprocessing function and pass the script module
> def foo(script_module):
>     output = script_module(input_data)
>     return output
> 
> # Start your processes with the script module
> if __name__ == '__main__':
>     multiprocessing.set_start_method('spawn', force=True)
>     processes = []
>     for i in range(4):
>         p = multiprocessing.Process(target=foo, args=(model,))
>         processes.append(p)
>         p.start()
>     for p in processes:
>         p.join()
> ```
> 
> Let me know if this helps.

Thanks for you reply. When I convert yolov5 to torchscript` model = torch.jit.script(model) `I met the following error:
![image](https://github.com/ultralytics/yolov5/assets/73052387/d09d810e-d217-469b-83a9-89e0d0b414b7)
![image](https://github.com/ultralytics/yolov5/assets/73052387/5c68b396-3e2d-45ca-969d-aa236c8dbaa6)

It seems that `torch.jit.script` or yolov5 model not supported in `torch-1.8.1+cu102` ? I was confused

**Comment by glenn-jocher** [comment]
@wxthu, thank you for sharing your experience. It looks like there may be compatibility issues between the YOLOv5 model and the PyTorch version you are using. Based on the error message you shared, it seems that the conversion to `torch.jit.script` failed due to missing torch operators. 

One possible solution is to try downgrading your PyTorch version to `1.7.0` or `1.7.1`, as these versions should be compatible with YOLOv5. You could also try updating your CUDA drivers and verifying that your GPU is compatible with the PyTorch and CUDA versions you're using.

Let us know if this helps or if you have any further questions.

**Comment by wxthu** [comment]
> @wxthu, thank you for sharing your experience. It looks like there may be compatibility issues between the YOLOv5 model and the PyTorch version you are using. Based on the error message you shared, it seems that the conversion to `torch.jit.script` failed due to missing torch operators.
> 
> One possible solution is to try downgrading your PyTorch version to `1.7.0` or `1.7.1`, as these versions should be compatible with YOLOv5. You could also try updating your CUDA drivers and verifying that your GPU is compatible with the PyTorch and CUDA versions you're using.
> 
> Let us know if this helps or if you have any further questions.

I have followed your suggestion to downgrade the PyTorch version to 1.7.1, but the same problem still exists. Thank you for your response nonetheless

**Comment by glenn-jocher** [comment]
@wxthu thank you for letting us know. Another possible solution is to try updating the CUDA drivers to the latest version and verifying that your GPU is compatible with the PyTorch and CUDA versions you're using. We also recommend checking the version compatibility of the other libraries you're using, as they may also contribute to the issue you're encountering. 

If you still encounter issues after trying these steps, feel free to provide more details about the errors or issues you're facing so we can provide further assistance.

**Comment by wxthu** [comment]
> feel free to provide more details about the errors or issues
Thanks so much and I will have a try

**Comment by glenn-jocher** [comment]
@wxthu thank you for considering our suggestions. If you encounter any further issues or errors, please don't hesitate to provide more details so that we can assist you further.

**Comment by wxthu** [comment]
> @wxthu thank you for considering our suggestions. If you encounter any further issues or errors, please don't hesitate to provide more details so that we can assist you further.

I have tried in another machine but met the same error

```
requirements: 1 package updated per /home/xiangwang/.cache/torch/hub/ultralytics_yolov5_master/requirements.txt
requirements: ⚠️ Restart runtime or rerun command for updates to take effect

YOLOv5 🚀 2023-5-23 Python-3.10.6 torch-1.13.0a0+git291649f CUDA:0 (NVIDIA Graphics Device, 24256MiB)

Fusing layers... 
YOLOv5x summary: 444 layers, 86705005 parameters, 0 gradients
Adding AutoShape... 
Traceback (most recent call last):
  File "/home/xiangwang/ours/main.py", line 40, in <module>
    model = torch.jit.script(model)
  File "/home/xiangwang/miniconda3/envs/pt_113/lib/python3.10/site-packages/torch/jit/_script.py", line 1286, in script
    return torch.jit._recursive.create_script_module(
  File "/home/xiangwang/miniconda3/envs/pt_113/lib/python3.10/site-packages/torch/jit/_recursive.py", line 476, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/home/xiangwang/miniconda3/envs/pt_113/lib/python3.10/site-packages/torch/jit/_recursive.py", line 538, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/xiangwang/miniconda3/envs/pt_113/lib/python3.10/site-packages/torch/jit/_script.py", line 615, in _construct
    init_fn(script_module)
  File "/home/xiangwang/miniconda3/envs/pt_113/lib/python3.10/site-packages/torch/jit/_recursive.py", line 516, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/home/xiangwang/miniconda3/envs/pt_113/lib/python3.10/site-packages/torch/jit/_recursive.py", line 538, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/xiangwang/miniconda3/envs/pt_113/lib/python3.10/site-packages/torch/jit/_script.py", line 615, in _construct
    init_fn(script_module)
  File "/home/xiangwang/miniconda3/envs/pt_113/lib/python3.10/site-packages/torch/jit/_recursive.py", line 516, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/home/xiangwang/miniconda3/envs/pt_113/lib/python3.10/site-packages/torch/jit/_recursive.py", line 538, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/xiangwang/miniconda3/envs/pt_113/lib/python3.10/site-packages/torch/jit/_script.py", line 615, in _construct
    init_fn(script_module)
  File "/home/xiangwang/miniconda3/envs/pt_113/lib/python3.10/site-packages/torch/jit/_recursive.py", line 516, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/home/xiangwang/miniconda3/envs/pt_113/lib/python3.10/site-packages/torch/jit/_recursive.py", line 538, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/xiangwang/miniconda3/envs/pt_113/lib/python3.10/site-packages/torch/jit/_script.py", line 615, in _construct
    init_fn(script_module)
  File "/home/xiangwang/miniconda3/envs/pt_113/lib/python3.10/site-packages/torch/jit/_recursive.py", line 516, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/home/xiangwang/miniconda3/envs/pt_113/lib/python3.10/site-packages/torch/jit/_recursive.py", line 542, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/home/xiangwang/miniconda3/envs/pt_113/lib/python3.10/site-packages/torch/jit/_recursive.py", line 393, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
  File "/home/xiangwang/miniconda3/envs/pt_113/lib/python3.10/site-packages/torch/jit/_script.py", line 1466, in _recursive_compile_class
    return _compile_and_register_class(obj, rcb, _qual_name)
  File "/home/xiangwang/miniconda3/envs/pt_113/lib/python3.10/site-packages/torch/jit/_recursive.py", line 45, in _compile_and_register_class
    ast = get_jit_class_def(obj, obj.__name__)
  File "/home/xiangwang/miniconda3/envs/pt_113/lib/python3.10/site-packages/torch/jit/frontend.py", line 234, in get_jit_class_def
    method_defs = [
  File "/home/xiangwang/miniconda3/envs/pt_113/lib/python3.10/site-packages/torch/jit/frontend.py", line 235, in <listcomp>
    get_jit_def(obj, name, self_name=self_name, is_classmethod=is_classmethod(obj))
  File "/home/xiangwang/miniconda3/envs/pt_113/lib/python3.10/site-packages/torch/jit/frontend.py", line 293, in get_jit_def
    return build_def(parsed_def.ctx, fn_def, type_line, def_name, self_name=self_name, pdt_arg_types=pdt_arg_types)
  File "/home/xiangwang/miniconda3/envs/pt_113/lib/python3.10/site-packages/torch/jit/frontend.py", line 331, in build_def
    param_list = build_param_list(ctx, py_def.args, self_name, pdt_arg_types)
  File "/home/xiangwang/miniconda3/envs/pt_113/lib/python3.10/site-packages/torch/jit/frontend.py", line 359, in build_param_list
    raise NotSupportedError(ctx_range, _vararg_kwarg_err)
torch.jit.frontend.NotSupportedError: Compiled functions can't take variable number of arguments or use keyword-only arguments with defaults:
  File "/home/xiangwang/miniconda3/envs/pt_113/lib/python3.10/warnings.py", line 477
    def __exit__(self, *exc_info):
                       ~~~~~~~~~ <--- HERE
        if not self._entered:
            raise RuntimeError("Cannot exit %r without entering first" % self)
'__torch__.warnings.catch_warnings' is being compiled since it was called from 'SPPF.forward'
  File "/home/xiangwang/.cache/torch/hub/ultralytics_yolov5_master/models/common.py", line 229
    def forward(self, x):
        x = self.cv1(x)
        with warnings.catch_warnings():
             ~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
            warnings.simplefilter('ignore')  # suppress torch 1.9.0 max_pool2d() warning
            y1 = self.m(x)
```
Driver version: 520.61.05
Cuda version: 11.8
Pytorch version: 1.13

**Comment by glenn-jocher** [comment]
Hello @wxthu, sorry to hear that you are still facing issues. It seems like there may be compatibility issues between the YOLOv5 model and the current version of PyTorch you are using. As you have already tried downgrading to PyTorch 1.7.1, you could try updating your CUDA drivers to the latest version and verifying that your GPU is compatible with the PyTorch and CUDA versions you are currently using. Additionally, you could also check version compatibility for other libraries you are using, as they may also contribute to the issue.

If you still encounter the same problem after trying the above suggestions, please provide more details about the errors or issues you are facing, so that we can assist you further.

**Comment by wxthu** [comment]
> Hello @wxthu, sorry to hear that you are still facing issues. It seems like there may be compatibility issues between the YOLOv5 model and the current version of PyTorch you are using. As you have already tried downgrading to PyTorch 1.7.1, you could try updating your CUDA drivers to the latest version and verifying that your GPU is compatible with the PyTorch and CUDA versions you are currently using. Additionally, you could also check version compatibility for other libraries you are using, as they may also contribute to the issue.
> 
> If you still encounter the same problem after trying the above suggestions, please provide more details about the errors or issues you are facing, so that we can assist you further.

you means that I need to upgrade my CUDA driver from current 520.61.05 to latest 530.30.02??

**Comment by wxthu** [comment]
Here is my test code:

```
import multiprocessing as mp
import torch
import torchvision.models as repo


class TaskEngine(mp.Process):
    def __init__(self,
                 name: str,
                 barrier: mp.Barrier,
                 model,
                 ):
        super().__init__(name=name)
        self._name = name
        self._barrier = barrier
        self._model = model

    def warmup(self):
        img = torch.rand(1, 3, 640, 640, dtype=torch.float16).cuda()
        self._model.cuda()
        for _ in range(50):
            out = self._model(img)

        torch.cuda.synchronize()
        del img, out

    @torch.no_grad()
    def run(self):
        self.warmup()
        self._barrier.wait()
        
        count = 0
        while count < 50:

            ims = torch.rand((1, 3, 640, 640),
                             dtype=torch.float16).cuda()
            y = self._model(ims)
            torch.cuda.synchronize()
            y = y.cpu()
            
            count += 1

        print("{} has finished successfully !!!".format(self._name))



if __name__ == '__main__':
    mp.set_start_method('spawn', force=True)
        
    processes = list()
    tasks = ['yolov5x', 'yolov5x', 'yolov5x']
    shared_barr = mp.Barrier(len(tasks))
    model = torch.hub.load('ultralytics/yolov5', 'custom', path='yolov5x.pt')
    model = torch.jit.script(model)
    for j, task in enumerate(tasks):
        # model = repo.resnet.resnet18().eval().half()
        processes.append(TaskEngine(name='task_%d'%(j),
                                    barrier=shared_barr,
                                    model=model,
                                    )
                         )
    
    for ps in processes:
        ps.start()
    
    for ps in processes:
        ps.join()
```

  if you are able to successfully run this code, please let me know your system configuration.

**Comment by glenn-jocher** [comment]
@wxthu hello! 

Thank you for sharing your test code with us. It would be helpful if you could provide more details about the errors or issues you are facing so that we can assist you further. 

However, in terms of system configuration, it would be helpful to know what GPU and cuda version you are using, as that can affect the performance of the model. Additionally, it would also be helpful to know what version of PyTorch you are using. 

If you can provide more details about your system configuration and the errors you are experiencing, we can try to assist you further.

**Comment by wxthu** [comment]
> @wxthu hello!
> 
> Thank you for sharing your test code with us. It would be helpful if you could provide more details about the errors or issues you are facing so that we can assist you further.
> 
> However, in terms of system configuration, it would be helpful to know what GPU and cuda version you are using, as that can affect the performance of the model. Additionally, it would also be helpful to know what version of PyTorch you are using.
> 
> If you can provide more details about your system configuration and the errors you are experiencing, we can try to assist you further.

I mean whether you have run my test code successfully in your testbed and if yes, can you share me information about your platform configuration ?  I have tried many times and always failed and met the same above error. The latest trial is on RTX 4090Ti, cuda 11.8 , driver version 520.61.05 and pytorch 1.13

**Comment by glenn-jocher** [comment]
@wxthu hello,

Thank you for sharing your test code with us. We have not yet run your test code, but we appreciate the detailed information about your system configuration. It would be helpful to know what specific error you are experiencing when running the test code. If you can provide more details about the error, we may be able to provide additional assistance.

In terms of our platform configuration, we have a variety of systems that we use for testing, including systems with NVIDIA GPUs and different versions of CUDA and PyTorch. However, system configuration can vary widely and can affect the performance and behavior of the model, so it may not be useful to compare configurations directly.

Please let us know if you have any additional information about the error you are experiencing, and we will do our best to assist you further.

Best regards,

**Comment by wxthu** [comment]
> @wxthu hello,
> 
> Thank you for sharing your test code with us. We have not yet run your test code, but we appreciate the detailed information about your system configuration. It would be helpful to know what specific error you are experiencing when running the test code. If you can provide more details about the error, we may be able to provide additional assistance.
> 
> In terms of our platform configuration, we have a variety of systems that we use for testing, including systems with NVIDIA GPUs and different versions of CUDA and PyTorch. However, system configuration can vary widely and can affect the performance and behavior of the model, so it may not be useful to compare configurations directly.
> 
> Please let us know if you have any additional information about the error you are experiencing, and we will do our best to assist you further.
> 
> Best regards,

Here are error msgs:
![image](https://github.com/ultralytics/yolov5/assets/73052387/8798ed1d-6f98-4940-a654-43ed4101cd1f)
![image](https://github.com/ultralytics/yolov5/assets/73052387/459a720b-0bc2-4fb2-b92b-d121e9dd4bb8)

**Comment by glenn-jocher** [comment]
Hello @wxthu,

Thank you for providing more details about the errors you are experiencing when running your test code. Based on the error messages you provided, it seems like there is an issue with the `__setstate__` method in the custom YOLOv5 model you are using.

One possible solution is to update your YOLOv5 model to the latest version and rerun your tests. Alternatively, you could try modifying the `__setstate__` method in the custom YOLOv5 model to resolve the issue.

If you are still experiencing the same errors after trying these suggestions, please provide additional details about your system configuration and any other relevant information, and we will do our best to assist you further.

Thank you, and best regards.

**Comment by wxthu** [comment]
> Hello @wxthu,
> 
> Thank you for providing more details about the errors you are experiencing when running your test code. Based on the error messages you provided, it seems like there is an issue with the `__setstate__` method in the custom YOLOv5 model you are using.
> 
> One possible solution is to update your YOLOv5 model to the latest version and rerun your tests. Alternatively, you could try modifying the `__setstate__` method in the custom YOLOv5 model to resolve the issue.
> 
> If you are still experiencing the same errors after trying these suggestions, please provide additional details about your system configuration and any other relevant information, and we will do our best to assist you further.
> 
> Thank you, and best regards.

I downloaded the yolov5 model by  `model = torch.hub.load('ultralytics/yolov5', 'custom', path='yolov5x.pt')` and  I do not know how to update YOLOv5 model to latest version?

**Comment by glenn-jocher** [comment]
Hello @wxthu,

To update the YOLOv5 model to the latest version, you can simply modify the "yolov5x.pt" file path in your code to point to the latest version of the YOLOv5 model. You can download the latest YOLOv5 models from the Ultralytics GitHub repository.

For example, you can use the following line of code to download the latest YOLOv5x.pt model:

```
model = torch.hub.load('ultralytics/yolov5', 'custom', path='yolov5x.pt')
```

You can replace 'yolov5x.pt' with the path to the latest YOLOv5 model you want to use.

If you still experience issues after updating the YOLOv5 model to the latest version, please let us know and we will do our best to assist you further.

Thank you,

**Comment by wxthu** [comment]
I am not sure which version is latest and could you send me some related link?

**Comment by wxthu** [comment]
> Hello @wxthu,
> 
> To update the YOLOv5 model to the latest version, you can simply modify the "yolov5x.pt" file path in your code to point to the latest version of the YOLOv5 model. You can download the latest YOLOv5 models from the Ultralytics GitHub repository.
> 
> For example, you can use the following line of code to download the latest YOLOv5x.pt model:
> 
> ```
> model = torch.hub.load('ultralytics/yolov5', 'custom', path='yolov5x.pt')
> ```
> 
> You can replace 'yolov5x.pt' with the path to the latest YOLOv5 model you want to use.
> 
> If you still experience issues after updating the YOLOv5 model to the latest version, please let us know and we will do our best to assist you further.
> 
> Thank you,

I always use this command to get latest yolov5 model `model = torch.hub.load('ultralytics/yolov5', 'custom', path='yolov5x.pt')` and still experience issues... emo.....

**Comment by glenn-jocher** [comment]
Hello @wxthu,

I'm sorry to hear that you're still experiencing issues even after updating to the latest version of the YOLOv5 model. 

To troubleshoot the issue, could you provide more information about the errors you're encountering? It would be helpful if you could include the error messages you are seeing in your response and any relevant system configuration details, such as the GPU and CUDA version you are using. 

Once we have more information about the issue, we can try to provide further assistance to help resolve the problem.

Thank you,

**Comment by wxthu** [comment]
> Hello @wxthu,
> 
> I'm sorry to hear that you're still experiencing issues even after updating to the latest version of the YOLOv5 model.
> 
> To troubleshoot the issue, could you provide more information about the errors you're encountering? It would be helpful if you could include the error messages you are seeing in your response and any relevant system configuration details, such as the GPU and CUDA version you are using.
> 
> Once we have more information about the issue, we can try to provide further assistance to help resolve the problem.
> 
> Thank you,

Driver: 520.61.05
CUDA: 11.8
GPU: GeForce RTX 4090

**Comment by wxthu** [comment]
I have included error msgs many times and you could scroll up the screen ...

**Comment by glenn-jocher** [comment]
Hello @wxthu,

Thank you for providing information about your system configuration and the errors you are encountering. Based on the error message you provided earlier, it seems like there is an issue with the `__setstate__` method in the custom YOLOv5 model you are using.

One possible solution is to update your YOLOv5 model to the latest version and rerun your tests. If this does not resolve the issues, you may need to modify the `__setstate__` method in your custom YOLOv5 model. 

Additionally, you may want to try running your tests with a different system configuration, such as a different version of CUDA or PyTorch, to see if this resolves the errors you are encountering.

If you are still experiencing issues after trying these suggestions, please do not hesitate to ask us for further assistance. We aim to provide professional and helpful support for all users, and we appreciate your patience as we work to resolve any issues you are experiencing.

Thank you.

**Comment by wxthu** [comment]
> Hello @wxthu,
> 
> Thank you for providing information about your system configuration and the errors you are encountering. Based on the error message you provided earlier, it seems like there is an issue with the `__setstate__` method in the custom YOLOv5 model you are using.
> 
> One possible solution is to update your YOLOv5 model to the latest version and rerun your tests. If this does not resolve the issues, you may need to modify the `__setstate__` method in your custom YOLOv5 model.
> 
> Additionally, you may want to try running your tests with a different system configuration, such as a different version of CUDA or PyTorch, to see if this resolves the errors you are encountering.
> 
> If you are still experiencing issues after trying these suggestions, please do not hesitate to ask us for further assistance. We aim to provide professional and helpful support for all users, and we appreciate your patience as we work to resolve any issues you are experiencing.
> 
> Thank you.

I have tried on different platforms with different system configuration... I am going crazy hhhhhh

**Comment by glenn-jocher** [comment]
Hello @wxthu,

I'm sorry to hear that you have still been experiencing problems with the YOLOv5 custom model even after trying different system configurations.

If you are still encountering issues with the model, it may be helpful to provide additional details, such as code snippets, debugging information (e.g., stack traces), or any other relevant information that may help us identify what is causing the problem. 

We appreciate your patience and dedication to resolving this issue, and we are here to support you in any way we can.

Best regards.

**Comment by wxthu** [comment]
I have completed yolov5 inference in multiprocessing mode in another way and thank you so much

**Comment by glenn-jocher** [comment]
@wxthu hello,

We are glad to hear that you have found a workaround for your issue with YOLOv5 inference in multiprocessing mode. If you have any further questions or run into any issues in the future, please do not hesitate to ask. We are here to provide professional and helpful support to all users.

Thank you.

Regards,
