### ISSUE TITLE
Export to edgetpu doesn't work

### ISSUE THREAD

**Issue by easy-and-simple** [ultralytics/yolov5#11562]
I try to export yolov5 model with per-trained weights and export is successful but then it is not working when I try to run it on edgetpu.
What is the problem and how to fix it?

**************************************************************************
it reports that export is successful
**************************************************************************

python export.py --weights yolov5s.pt --include edgetpu --int8 --data coco128.yaml
export: data=coco128.yaml, weights=['yolov5s.pt'], imgsz=[640, 640], batch_size=1, device=cpu, half=False, inplace=False, keras=False, optimize=False, int8=True, dynamic=False, simplify=False, opset=17, verbose=False, workspace=4, nms=False, agnostic_nms=False, topk_per_class=100, topk_all=100, iou_thres=0.45, conf_thres=0.25, include=['edgetpu']
YOLOv5 🚀 v7.0-166-g54e9515 Python-3.7.16 torch-1.13.1+cu117 CPU

Fusing layers... 
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients

PyTorch: starting from yolov5s.pt with output shape (1, 25200, 85) (14.1 MB)

TensorFlow SavedModel: starting export with tensorflow 2.4.0...

                 from  n    params  module                                  arguments                     
  0                -1  1      3520  models.common.Conv                      [3, 32, 6, 2, 2]              
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]                
  2                -1  1     18816  models.common.C3                        [64, 64, 1]                   
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]               
  4                -1  1    115712  models.common.C3                        [128, 128, 2]                 
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]              
  6                -1  1    625152  models.common.C3                        [256, 256, 3]                 
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]              
  8                -1  1   1182720  models.common.C3                        [512, 512, 1]                 
  9                -1  1    656896  models.common.SPPF                      [512, 512, 5]                 
 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]              
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 12           [-1, 6]  1         0  models.common.Concat                    [1]                           
 13                -1  1    361984  models.common.C3                        [512, 256, 1, False]          
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]              
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 16           [-1, 4]  1         0  models.common.Concat                    [1]                           
 17                -1  1     90880  models.common.C3                        [256, 128, 1, False]          
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]              
 19          [-1, 14]  1         0  models.common.Concat                    [1]                           
 20                -1  1    296448  models.common.C3                        [256, 256, 1, False]          
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]              
 22          [-1, 10]  1         0  models.common.Concat                    [1]                           
 23                -1  1   1182720  models.common.C3                        [512, 512, 1, False]          
 24      [17, 20, 23]  1    229245  models.yolo.Detect                      [80, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512], [640, 640]]
Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_1 (InputLayer)            [(1, 640, 640, 3)]   0                                            
__________________________________________________________________________________________________
tf_conv (TFConv)                (1, 320, 320, 32)    3488        input_1[0][0]                    
__________________________________________________________________________________________________
tf_conv_1 (TFConv)              (1, 160, 160, 64)    18496       tf_conv[0][0]                    
__________________________________________________________________________________________________
tf_c3 (TFC3)                    (1, 160, 160, 64)    18624       tf_conv_1[0][0]                  
__________________________________________________________________________________________________
tf_conv_7 (TFConv)              (1, 80, 80, 128)     73856       tf_c3[0][0]                      
__________________________________________________________________________________________________
tf_c3_1 (TFC3)                  (1, 80, 80, 128)     115200      tf_conv_7[0][0]                  
__________________________________________________________________________________________________
tf_conv_15 (TFConv)             (1, 40, 40, 256)     295168      tf_c3_1[0][0]                    
__________________________________________________________________________________________________
tf_c3_2 (TFC3)                  (1, 40, 40, 256)     623872      tf_conv_15[0][0]                 
__________________________________________________________________________________________________
tf_conv_25 (TFConv)             (1, 20, 20, 512)     1180160     tf_c3_2[0][0]                    
__________________________________________________________________________________________________
tf_c3_3 (TFC3)                  (1, 20, 20, 512)     1181184     tf_conv_25[0][0]                 
__________________________________________________________________________________________________
tfsppf (TFSPPF)                 (1, 20, 20, 512)     656128      tf_c3_3[0][0]                    
__________________________________________________________________________________________________
tf_conv_33 (TFConv)             (1, 20, 20, 256)     131328      tfsppf[0][0]                     
__________________________________________________________________________________________________
tf_upsample (TFUpsample)        (1, 40, 40, 256)     0           tf_conv_33[0][0]                 
__________________________________________________________________________________________________
tf_concat (TFConcat)            (1, 40, 40, 512)     0           tf_upsample[0][0]                
                                                                 tf_c3_2[0][0]                    
__________________________________________________________________________________________________
tf_c3_4 (TFC3)                  (1, 40, 40, 256)     361216      tf_concat[0][0]                  
__________________________________________________________________________________________________
tf_conv_39 (TFConv)             (1, 40, 40, 128)     32896       tf_c3_4[0][0]                    
__________________________________________________________________________________________________
tf_upsample_1 (TFUpsample)      (1, 80, 80, 128)     0           tf_conv_39[0][0]                 
__________________________________________________________________________________________________
tf_concat_1 (TFConcat)          (1, 80, 80, 256)     0           tf_upsample_1[0][0]              
                                                                 tf_c3_1[0][0]                    
__________________________________________________________________________________________________
tf_c3_5 (TFC3)                  (1, 80, 80, 128)     90496       tf_concat_1[0][0]                
__________________________________________________________________________________________________
tf_conv_45 (TFConv)             (1, 40, 40, 128)     147584      tf_c3_5[0][0]                    
__________________________________________________________________________________________________
tf_concat_2 (TFConcat)          (1, 40, 40, 256)     0           tf_conv_45[0][0]                 
                                                                 tf_conv_39[0][0]                 
__________________________________________________________________________________________________
tf_c3_6 (TFC3)                  (1, 40, 40, 256)     295680      tf_concat_2[0][0]                
__________________________________________________________________________________________________
tf_conv_51 (TFConv)             (1, 20, 20, 256)     590080      tf_c3_6[0][0]                    
__________________________________________________________________________________________________
tf_concat_3 (TFConcat)          (1, 20, 20, 512)     0           tf_conv_51[0][0]                 
                                                                 tf_conv_33[0][0]                 
__________________________________________________________________________________________________
tf_c3_7 (TFC3)                  (1, 20, 20, 512)     1181184     tf_concat_3[0][0]                
__________________________________________________________________________________________________
tf_detect (TFDetect)            ((1, 25200, 85),)    229245      tf_c3_5[0][0]                    
                                                                 tf_c3_6[0][0]                    
                                                                 tf_c3_7[0][0]                    
==================================================================================================
Total params: 7,225,885
Trainable params: 0
Non-trainable params: 7,225,885
__________________________________________________________________________________________________
TensorFlow SavedModel: export success ✅ 3.4s, saved as yolov5s_saved_model (27.9 MB)

TensorFlow Lite: starting export with tensorflow 2.4.0...
WARNING:absl:Found untraced functions such as tf_conv_2_layer_call_fn, tf_conv_2_layer_call_and_return_conditional_losses, tf_conv_3_layer_call_fn, tf_conv_3_layer_call_and_return_conditional_losses, tf_conv_4_layer_call_fn while saving (showing 5 of 520). These functions will not be directly callable after loading.
WARNING:absl:Found untraced functions such as tf_conv_2_layer_call_fn, tf_conv_2_layer_call_and_return_conditional_losses, tf_conv_3_layer_call_fn, tf_conv_3_layer_call_and_return_conditional_losses, tf_conv_4_layer_call_fn while saving (showing 5 of 520). These functions will not be directly callable after loading.
TensorFlow Lite: export success ✅ 98.9s, saved as yolov5s-int8.tflite (7.3 MB)

Edge TPU: starting export with Edge TPU compiler 16.0.384591198...
Edge TPU Compiler version 16.0.384591198
Searching for valid delegate with step 10
Try to compile segment with 281 ops
Started a compilation timeout timer of 180 seconds.

Model compiled successfully in 6341 ms.

Input model: yolov5s-int8.tflite
Input size: 7.34MiB
Output model: ./yolov5s-int8_edgetpu.tflite
Output size: 8.24MiB
On-chip memory used for caching model parameters: 6.84MiB
On-chip memory remaining for caching model parameters: 0.00B
Off-chip memory used for streaming uncached model parameters: 273.38KiB
Number of Edge TPU subgraphs: 1
Total number of operations: 281
Operation log: ./yolov5s-int8_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 257
Number of operations that will run on CPU: 24

Operator                       Count      Status

CONV_2D                        60         Mapped to Edge TPU
LOGISTIC                       63         Mapped to Edge TPU
LOGISTIC                       3          More than one subgraph is not supported
RESIZE_NEAREST_NEIGHBOR        2          Mapped to Edge TPU
RESHAPE                        3          Operation is otherwise supported, but not mapped due to some unspecified limitation
RESHAPE                        3          Mapped to Edge TPU
PAD                            7          Mapped to Edge TPU
CONCATENATION                  15         Mapped to Edge TPU
CONCATENATION                  1          More than one subgraph is not supported
CONCATENATION                  1          Operation is otherwise supported, but not mapped due to some unspecified limitation
ADD                            9          Mapped to Edge TPU
ADD                            1          More than one subgraph is not supported
MAX_POOL_2D                    3          Mapped to Edge TPU
STRIDED_SLICE                  3          More than one subgraph is not supported
STRIDED_SLICE                  6          Mapped to Edge TPU
MUL                            69         Mapped to Edge TPU
MUL                            6          More than one subgraph is not supported
QUANTIZE                       3          Operation is otherwise supported, but not mapped due to some unspecified limitation
QUANTIZE                       20         Mapped to Edge TPU
QUANTIZE                       3          More than one subgraph is not supported
Compilation child process completed within timeout period.
Compilation succeeded! 
Edge TPU: export success ✅ 6.6s, saved as yolov5s-int8_edgetpu.tflite (8.2 MB)

Export complete (109.3s)
Results saved to /home/vvv/yolov5
Detect:          python detect.py --weights yolov5s-int8_edgetpu.tflite 
Validate:        python val.py --weights yolov5s-int8_edgetpu.tflite 
PyTorch Hub:     model = torch.hub.load('ultralytics/yolov5', 'custom', 'yolov5s-int8_edgetpu.tflite') 

********************************************************************************************
fail to run detect image pycoral example
********************************************************************************************

python3 examples/detect_image.py --model test_data/yolov5s-int8_edgetpu.tflite --labels test_data/yolo_labels.txt --input test_data/grace_hopper.bmp --output ${HOME}/grace_hopper_processed.bmp
/home/vvv/coral/pycoral/examples/detect_image.py:78: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use LANCZOS or Resampling.LANCZOS instead.
  interpreter, image.size, lambda size: image.resize(size, Image.ANTIALIAS))
----INFERENCE TIME----
Note: The first inference is slow because it includes loading the model into Edge TPU memory.
Traceback (most recent call last):
  File "/home/vvv/coral/pycoral/examples/detect_image.py", line 108, in <module>
    main()
  File "/home/vvv/coral/pycoral/examples/detect_image.py", line 87, in main
    objs = detect.get_objects(interpreter, args.threshold, scale)
  File "/home/vvv/miniconda3/lib/python3.9/site-packages/pycoral/adapters/detect.py", line 214, in get_objects
    elif common.output_tensor(interpreter, 3).size == 1:
  File "/home/vvv/miniconda3/lib/python3.9/site-packages/pycoral/adapters/common.py", line 29, in output_tensor
    return interpreter.tensor(interpreter.get_output_details()[i]['index'])()
IndexError: list index out of range

**Comment by easy-and-simple** [comment]
This at least runs somehow, while your yolov8 can't run at all

**Comment by glenn-jocher** [comment]
@easy-and-simple thank you for your comment. We're sorry to hear that you're having trouble running YOLOv8. We take all feedback seriously and are constantly working to improve our software. If you could provide more specific information about the issues you are encountering, we would be happy to assist you in resolving them. Alternatively, if you have any other questions or concerns about YOLOv5, please don't hesitate to let us know. Thank you for your support.
