### ISSUE TITLE
custom data question about anchor ratios?

### ISSUE THREAD

**Issue by kunyaoli** [ultralytics/yolov5#1156]
## ❔Question

my own data  have special bonding box,so i used your autoanchor method ,but where could i change the ratio of anchor?

**Comment by glenn-jocher** [comment]
@kunyaoli you can manually update anchors, or also paste the autoanchor output here:
https://github.com/ultralytics/yolov5/blob/3b57cb56412976847b91ef184ca2f2a99491d8ab/models/yolov5s.yaml#L6-L11
