### ISSUE TITLE
Question about camera

### ISSUE THREAD

**Issue by kenloumixx** [ultralytics/yolov5#11578]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I am newbie and I want to use real time video using camera module usb for the inference of this model. 

In this case, should I use the option of webcam, video or RTSP, RTMP, HTTP stream?

TIA!

**Comment by glenn-jocher** [comment]
@kenloumixx hello and welcome to the YOLOv5 community! 

To use your camera module for inference with YOLOv5, you should select the option of Video in the command line interface (CLI) argument when invoking the detection script.  

You can modify the source of the video input stream by changing the value of the --source *(you may also use the short form -s)* to 0 to select the default camera device or to the path of your device. If you are uncertain about the path of your device, you can try experimenting with different options and see which one works. 

You can also explore other video stream options such as RTSP, RTMP, HTTP, or even IP cameras. To do this, you should select the option corresponding to the stream type, followed by the path to the stream in the --source argument. 

I hope this helps! If you have any further questions, do not hesitate to ask.
