### ISSUE TITLE
is precision-curve generate according to validation batches? 

### ISSUE THREAD

**Issue by yjackboo** [ultralytics/yolov5#11571]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi ! I would like to ask, is the Precision-Curve get generated inside train/exp folder based on the validation batches or based on 
entire validation dataset ? 

Thank you so much..

**Comment by glenn-jocher** [comment]
@yjackboo hello,

The Precision-Curve in the train/exp folder is generated based on the entire validation dataset, not just the batches. If you have any other questions or concerns, please don't hesitate to ask.

Best regards.
