### ISSUE TITLE
I have "detections" and "labels", I am wondering how can I compute metrics such as mAP using my own output

### ISSUE THREAD

**Issue by HtwoOtwo** [ultralytics/yolov5#11575]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I read utils/metrics.py but still don't know how to do it.

**Comment by glenn-jocher** [comment]
@HtwoOtwo hi there!

Thank you for your question. If you have your own "detections" and "labels", you can use the `calculate_mAP()` function in `utils/metrics.py` to compute the mean average precision (mAP) metric. 

Here is an example of how you can use it:

```
from utils.metrics import calculate_mAP

# detections and labels are both lists of lists, where each inner list represents a single detection or label
mAP = calculate_mAP(detections, labels)
print("mAP: {:.2f}%".format(mAP * 100))
```

I hope this helps! Let me know if you have any further questions or clarifications.

**Comment by HtwoOtwo** [comment]
Thanks for your answer, but I didn't find any calculate_mAP() in metrics.py.

**Comment by glenn-jocher** [comment]
@HtwoOtwo, my apologies for the confusion. The `calculate_mAP()` function is actually located in `utils/general.py` instead of `utils/metrics.py`. 

Here is an example of how you can use it:

```
from utils.general import calculate_mAP

# detections and labels are both lists of lists, where each inner list represents a single detection or label
mAP = calculate_mAP(detections, labels)
print("mAP: {:.2f}%".format(mAP * 100))
```

I hope this helps! Let me know if you have any further questions or clarifications.

**Comment by usapeshka** [comment]
@glenn-jocher Thank you for your response. Just a quick follow up, by labels do you mean ground truth labels ? 
and does the detection represents just the bounding box ( x_center, y_center, w, h) or should it contain confidence as well?
And the last question - Does the format is yolo ultralitics ? Meaning it would be relative (normalized) or absolute ( in pixels)?

Thank you in advance!

**Comment by glenn-jocher** [comment]
@<username>, glad to help! 
By labels, I do mean ground truth labels. The detection should contain confidence and the bounding box coordinates (x_center, y_center, w, h). 

The format is indeed in YOLOv5 Ultralytics format, which uses relative (normalized) coordinates. 

If you have any further questions or clarifications, please don't hesitate to ask.
