### ISSUE TITLE
Unable to get feature map if path of images (string) are passed as arguments

### ISSUE THREAD

**Issue by nrvora** [ultralytics/yolov5#11581]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have trained a custom yolov5 model for a specific task, Now I want to use a feature map of the detection layer to further use it in different pipelines. Though I am able to get the feature map, there is one problem.

1) If I pass the image argument as NumPy array:- 
![image](https://github.com/ultralytics/yolov5/assets/42088255/6a72b529-cd6d-469d-94a1-973b2e5ef502)
I get output as a list from where I can get my feature map.

2) If I pass the image argument as file path:- 
![image](https://github.com/ultralytics/yolov5/assets/42088255/90220784-e372-4a75-94cf-627a8a431c51)
I get output as Detections class from common.py, from where I can get my bounding box but cannot get the feature map

I would like to know why is this the case and also how can I get a feature map given the second case.

I have gone through #3522 but here it is mentioned to use the detection class of yolo.py but my model uses the detection class of common.py

**Comment by nrvora** [comment]
Resolved in #11836. Thanks.

**Comment by glenn-jocher** [comment]
@freaksie fantastic! I'm glad to hear that the issue has been resolved in #11836. Thank you for letting us know!

If you have any more questions or encounter any other issues, please don't hesitate to reach out again. Stay tuned for more updates and improvements to YOLOv5 in the future!

Keep up the great work and happy coding!
