### ISSUE TITLE
yolov5 with cropped folder to get detected with h5 folder cnn image classification

### ISSUE THREAD

**Issue by jokermah** [ultralytics/yolov5#11580]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

do you have any reference to video files got detected with yolov5 and pull out the result summary, then one of the cropped folder will detected to cnn image classification h5 folder to make sure is it true the object is correct

for example, i have this video (2 person, 1 book, 1 calculator, 1 cell phone) but yolov5 detected as (2 person, 1 book, 2 cell phone). so, i made a cnn image classification for cell phone and calculator to get the h5 folder. now, i want to put them together. i want the program to pull out the images from cell phone cropped folder into the cnn image classification.

i'm new to machine learning and have limited programming knowledge. i hope someone can help me with this issue, thank you

**Comment by glenn-jocher** [comment]
@jokermah hello, 

Regarding your question, YOLOv5 supports video detection. You can use the `detect.py` script with the `--source` parameter set to your video file, and it will output the results in the console or a specified text file.

To verify the objects detected in your cropped folder, you can use the `classify.py` script to classify the images using your image classification model. The output of this script can also be used in conjunction with the results of the `detect.py` script to further filter or classify the detected objects.

If you have any further questions, feel free to ask. Good luck with your project!
