### ISSUE TITLE
Train a model for Detection only; not classification.

### ISSUE THREAD

**Issue by Haalum** [ultralytics/yolov5#11583]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is there a way to train yolov5 for detection only and not the classification of the detected object? I'm working on small object detection and don't care about the classification. I want the model to learn detection only.

Note: I looked for this in the issue section but couldn't find any related post. Thanks in advance.

**Comment by glenn-jocher** [comment]
@Haalum hello there,

Yes, you can train YOLOv5 for detection only without the classification of the detected objects. You can simply ignore the classification layer in the final layer of the network architecture while training the model. 

In the YOLOv5 implementation, by default, the model is trained to perform both object detection and classification, but it is possible to train a model for detection only by simply removing the classification layer from the model's final layer. By doing this, YOLOv5 will only detect objects and won't predict their classes.

Hope this helps. Let us know if you have any further questions!

**Comment by Haalum** [comment]
Thank you for your prompt reply. Appreciate it. I will try this and will reach out if I have any questions.

**Comment by Zephyr69** [comment]
I think --single-cls is what you are looking for.

**Comment by glenn-jocher** [comment]
@Haalum hello!

Yes, you are absolutely right. The `--single-cls` option in YOLOv5 is used to train the model for single-class object detection, where the model detects and localizes objects but does not classify them into classes. This option may be useful in cases where the model needs to detect objects of a very specific nature and there are no predefined classes for such objects.

Thank you for contributing to the YOLOv5 community and feel free to reach out if you have any further questions or concerns.
