### ISSUE TITLE
train.py not running on jupyter notebook

### ISSUE THREAD

**Issue by han-s0l0** [ultralytics/yolov5#11591]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hey, I am struggling to run the train.py on jupyter, I tried to change my yaml and all of the things I thought were a problem but It didn't helped. It always shows the same error: 

![image](https://github.com/ultralytics/yolov5/assets/111011292/34af137b-a8a0-4f10-9a41-6a87b18bff10)

I am using the same code I used on colab before and it works pretty well there but now I have to use AWS and it's not working, I don't have any ideia of what is causing it

details about the environment: 
![image](https://github.com/ultralytics/yolov5/assets/111011292/e31adea2-5e54-457c-84c7-7144a572f1c1)

**Comment by glenn-jocher** [comment]
@han-s0l0 hello,

Thank you for your question. It seems like there might be an issue with setting the correct paths and environment variables on your AWS instance. 

Have you checked if your instance has the required dependencies installed? You can check by running the following command in your terminal: 

```bash
pip3 freeze | grep torch
```

If the output doesn't include PyTorch, you can install it by running the following command: 

```bash
pip3 install torch torchvision torchaudio
```

Additionally, ensure that the paths to your data and configuration files are set correctly. Double-check the location and names of your files.

Let me know if this resolves your issue or if you require further assistance.

Best, 
Glenn Jocher

**Comment by han-s0l0** [comment]
It's everything installed correctly, I also checked the paths.
![image](https://github.com/ultralytics/yolov5/assets/111011292/52545c59-f53b-423c-977d-47936eb1f237)

**Comment by han-s0l0** [comment]
I found the problem! The issue is that for some reason I have 2 pythons installed and it was running the older one, I changed to run python3 and it worked. 

Thanks for your help!

**Comment by glenn-jocher** [comment]
@han-s0l0 great news! I'm glad to hear that you were able to solve your issue. Remember to always double-check your environment variables and dependencies when running into similar issues. Don't hesitate to reach out again in case you encounter any other problems or have further questions. Cheers!
