### ISSUE TITLE
Model Depth

### ISSUE THREAD

**Issue by samahwaleed** [ultralytics/yolov5#11594]
What is the model depth for YOLOv5, YOLOv6, YOLOv7?

**Comment by glenn-jocher** [comment]
@samahwaleed hello, 

Thank you for your interest in YOLOv5, YOLOv6, and YOLOv7. The model depth for YOLOv5 is 5, which is where the name derives from. However, YOLOv6 and YOLOv7 are not released yet and we do not have any information regarding their model depth. 

If you have any further questions or concerns, please feel free to ask. 

Thank you.
