### ISSUE TITLE
Genarate .wts file fail using gen_wts.py

### ISSUE THREAD

**Issue by a514154639** [ultralytics/yolov5#11599]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Once i use gen_wts.py convert .pt to .wts and it works, but when i use the latest yolov5 to train my model, the .pt file can't be convert to .wts. The errors are as follows:
Traceback (most recent call last):
  File "/share/home/xk/yolov5-mod/gen_wts.py", line 30, in <module>
    model = torch.load(pt_file, map_location=device)['model'].float()  # load to FP32
  File "/share/home/xk/anaconda3/lib/python3.10/site-packages/torch/serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/share/home/xk/anaconda3/lib/python3.10/site-packages/torch/serialization.py", line 1046, in _load
    result = unpickler.load()
  File "/share/home/xk/anaconda3/lib/python3.10/site-packages/torch/serialization.py", line 1039, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'DetectionModel' on <module 'models.yolo' from '/share/home/xk/yolov5-mod/models/yolo.py'>

This is my env:
YOLOv5 🚀 2022-5-16 torch 1.11.0+cu102 CPU

**Comment by glenn-jocher** [comment]
@a514154639 hello! It looks like you are running into an AttributeError when trying to convert your .pt file to a .wts file using gen_wts.py. The error message mentions that it can't get the attribute 'DetectionModel' on the 'yolo' module, which could indicate that there may be a compatibility issue between your .pt file and the latest version of YOLOv5 that you are using.

One thing you can try is to use the same version of YOLOv5 that you used to train your model when using gen_wts.py to convert your .pt file to a .wts file. This can help ensure that there are no compatibility issues that could be causing the error you are seeing.

Also, please make sure that you are following the correct steps and requirements for using gen_wts.py. You can refer to the YOLOv5 documentation for more information on how to use gen_wts.py.

I hope this helps! Let me know if you have any other questions or concerns.

**Comment by a514154639** [comment]
> @a514154639 hello! It looks like you are running into an AttributeError when trying to convert your .pt file to a .wts file using gen_wts.py. The error message mentions that it can't get the attribute 'DetectionModel' on the 'yolo' module, which could indicate that there may be a compatibility issue between your .pt file and the latest version of YOLOv5 that you are using.
> 
> One thing you can try is to use the same version of YOLOv5 that you used to train your model when using gen_wts.py to convert your .pt file to a .wts file. This can help ensure that there are no compatibility issues that could be causing the error you are seeing.
> 
> Also, please make sure that you are following the correct steps and requirements for using gen_wts.py. You can refer to the YOLOv5 documentation for more information on how to use gen_wts.py.
> 
> I hope this helps! Let me know if you have any other questions or concerns.

Thanks! I have solved it! Just update model/yolo.py, my version is too old.

**Comment by glenn-jocher** [comment]
Great to hear that you were able to solve the issue, @a514154639! Updating the model/yolo.py file would definitely help ensure compatibility between your .pt file and the latest version of YOLOv5. 

If you encounter any further issues, feel free to ask for help or guidance. We are always happy to assist. Best of luck with your project!
