### ISSUE TITLE
Ask a question: Is YOLOV5 trained with rectangular boxes? Is the segmentation also a rectangular box? Can polygons work?

### ISSUE THREAD

**Issue by JXCrazy** [ultralytics/yolov5#11598]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Ask a question: Is YOLOV5 trained with rectangular boxes? Is the segmentation also a rectangular box? Can polygons work?

**Comment by glenn-jocher** [comment]
@JXCrazy hi there! Yes, YOLOv5 is trained with rectangular bounding boxes and the segmentation is also a rectangular box. However, you may be interested to know that YOLOv5 does support using polygons for annotations. You can use the [labelImg](https://github.com/tzutalin/labelImg) tool to create annotated images with polygons and then use the `--rect` flag with `detect.py` to enable polygon detection. Let us know if you have any further questions!

**Comment by JXCrazy** [comment]
OK, thank you for your pertinent answer. But I learned that there is no  '--rect'  flag in the detect.py file of Yolov5. The polygon file marked by labelImg must also be converted into a 'txt' format suitable for Yolov5.

**Comment by glenn-jocher** [comment]
@JXCrazy, thank you for your comment. You are correct that there is no `--rect` flag in the `detect.py` file of YOLOv5. Instead, you can use the `--source` flag along with your annotated images to detect polygons. 

Regarding the polygon file, you are right that it needs to be converted into a 'txt' format which is suitable for YOLOv5. The annotation format should be as follows for each object in the image: 

`<object-class> <x-center> <y-center> <width> <height>`

Where `<object-class>` is the class of the object (e.g., "car", "person", etc.), and `<x-center>`, `<y-center>`, `<width>`, and `<height>` are normalized coordinates of the bounding box. Please let me know if you have any further questions or concerns.
