### ISSUE TITLE
Use onnx as pre-trained weights

### ISSUE THREAD

**Issue by TimotheeWrightFicha** [ultralytics/yolov5#11595]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Hello, 
From [documentation on ONNX for Yolov5](https://docs.ultralytics.com/yolov5/tutorials/model_export/#export-a-trained-yolov5-model), it seems detect.py, val.py handles onnx format along with other.

Could it be possible to make train.py accept onnx files as weights ?

```
!python /content/yolov5/train.py --img-size 640 --batch-size 16 --epochs 50 --data $data_yaml_path --weights $previous_model_weight --name my_model --cache

AssertionError: /content/drive/my_model.onnx acceptable suffix is ['.pt']
```

### Use case

Could be used to finetune an onnx model using yolov5

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@TimotheeWrightFicha hi there,

Thank you for reaching out to us. The YOLOv5 model undergoes several transformations during the training process, which are currently not supported by the ONNX format. Although the inference performance will be similar to .pt weights, we can't guarantee the same training results at the moment. However, if you want to perform inference, you can use the `--weights` flag in `train.py` to load the ONNX format weights.

Thank you for your interest in YOLOv5!

Best regards.

**Comment by TimotheeWrightFicha** [comment]
Hi @glenn-jocher thank you for this detailed answer and your work on Yolov5 :)

**Comment by glenn-jocher** [comment]
Hi @TimotheeWrightFicha,

Thank you for your kind words and support, it is much appreciated! We are always happy to help and continue developing YOLOv5 to make it better and more convenient to use for everyone. If you have any further questions or issues, please do not hesitate to open an issue on our repo.

Best, 
Glenn
