### ISSUE TITLE
ImportError: cannot import name 'TryExcept' from 'utils' (unknown location)

### ISSUE THREAD

**Issue by ngocnd2402** [ultralytics/yolov5#11593]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Hi, 
I trained the model yolov5m on google colab with a custom dataset labeled person only, and then saved the ckpt to local. I want to load ckpt to apply to the tracking problem, with the command:
import torch
from ultralytics import YOLO
model = torch.hub.load('ultralytics/yolov5', 'custom', 'trained_v5_30ep.pt')
Then the error:  ImportError: cannot import name 'TryExcept' from 'utils' (unknown location)
Hope you can help me soon. Thanks a lot

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ngocnd2402 hello! Thank you for reaching out to us. We apologize for the inconvenience. This error occurs because the `TryExcept` module is not present in the `utils` module of YOLOv5.

There are a few things you can try to resolve this:

1. Make sure you are using the latest version of YOLOv5.

2. Double-check that you have correctly installed all dependencies, including PyTorch and TorchVision.

3. Try importing `TryExcept` from the parent directory of the `utils` module, like this:

```
from ..utils.general import TryExcept
```

We hope this helps. Please let us know if you have any other questions or concerns. Thank you for your interest in YOLOv5!

**Comment by JAYANTH-MOHAN** [comment]
This is how i corrected mine goto yolov5/utils/general.py and modify like this in the import statements
```python
import sys
sys.path.append('/home/gus/yoloscratch/yolov5/')
from ultralytics.yolo.utils.checks import check_requirements
```

**Comment by ljubantomic01** [comment]
For me, that error was occuring when using predict.py for yolov5 classification in the form of **ImportError: cannot import name 'TryExcept' from 'utils' ('path to __init.py__' (which is inside site_packages/utils, in my conda environment))**. Also this py file was empty.
After trying this command : python -c "import utils; print(utils.__file__)", it seems that it wants to load init.py from my utils module inside yolov5 folder. So I just erased this __init__.py file from my conda environment, and it seems to work now for predicting.

**Comment by glenn-jocher** [comment]
@ljubanradisin hi there,

I apologize for the inconvenience you experienced with the `ImportError: cannot import name 'TryExcept' from 'utils'` error while using the `predict.py` script for YOLOv5 classification.

Thank you for providing the details of your solution. It seems that removing the `__init__.py` file from the `utils` folder in your conda environment resolved the issue for you.

We appreciate your contribution and sharing your workaround. If you have any further questions or concerns, please don't hesitate to let us know.

Thank you for your support of YOLOv5!

**Comment by iaiamomo** [comment]
I solved the issue by uninstalling the utils package with `pip uninstall utils`.

**Comment by glenn-jocher** [comment]
Hello @iaiamomo,

Thank you for sharing your solution! Uninstalling the conflicting `utils` package with `pip uninstall utils` is indeed a practical approach to resolving the `ImportError: cannot import name 'TryExcept' from 'utils'` issue.

To ensure that we can assist you and others effectively, could you please provide a minimum reproducible code example? This will help us investigate the issue further and ensure it doesn't affect other users. You can find more details on how to create a minimum reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example). 🛠️

Additionally, we recommend verifying that you are using the latest versions of `torch` and the [YOLOv5 repository](https://github.com/ultralytics/yolov5). This can often resolve unexpected issues and ensure compatibility with the latest features and bug fixes.

If you encounter any further issues or have additional questions, please feel free to share them. We're here to help!

Thank you for your support and contributions to the YOLOv5 community! 😊
