### ISSUE TITLE
Training with GPU instead of CPU

### ISSUE THREAD

**Issue by malekaburaddaha** [ultralytics/yolov5#11597]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training, Multi-GPU

### Bug

I am trying to run the training on GPU since I tried with CPU and it took more than 2 days with for only 35 epochs out of 100.
I tried to change a few lines in the train.py from cpu to Cuda as a try, because I did not find a clear way on how to run on gpu, but I got the follwoing error message:

train: weights=yolov5s.pt, cfg=, data=pothole.yaml, hyp=data\hyps\hyp.scratch-low.yaml, epochs=1, batch_size=12, imgsz=300, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, noplots=False, evolve=None, bucket=, cache=None, image_weights=False, device=, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=8, project=runs\train, name=exp, exist_ok=False, quad=False, cos_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, seed=0, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest
github: up to date with https://github.com/ultralytics/yolov5 
YOLOv5  v7.0-172-gc3c1304 Python-3.9.16 torch-1.12.1 CPU

hyperparameters: lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0
ClearML: run 'pip install clearml' to automatically track, visualize and remotely train YOLOv5  in ClearML
Comet: run 'pip install comet_ml' to automatically track and visualize YOLOv5  runs in Comet
TensorBoard: Start with 'tensorboard --logdir runs\train', view at http://localhost:6006/
Traceback (most recent call last):
  File "D:\Malek\Research\Thesis\code\yolov5\train.py", line 642, in <module>
    main(opt)
  File "D:\Malek\Research\Thesis\code\yolov5\train.py", line 531, in main
    train(opt.hyp, opt, device, callbacks)
  File "D:\Malek\Research\Thesis\code\yolov5\train.py", line 124, in train
    ckpt = torch.load(weights, map_location='cuda')  # load checkpoint to CPU to avoid CUDA memory leak
  File "C:\Users\Asus\anaconda3\envs\Malek2\lib\site-packages\torch\serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\Asus\anaconda3\envs\Malek2\lib\site-packages\torch\serialization.py", line 1049, in _load
    result = unpickler.load()
  File "C:\Users\Asus\anaconda3\envs\Malek2\lib\site-packages\torch\serialization.py", line 1019, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "C:\Users\Asus\anaconda3\envs\Malek2\lib\site-packages\torch\serialization.py", line 1001, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "C:\Users\Asus\anaconda3\envs\Malek2\lib\site-packages\torch\serialization.py", line 970, in restore_location
    return default_restore_location(storage, map_location)
  File "C:\Users\Asus\anaconda3\envs\Malek2\lib\site-packages\torch\serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "C:\Users\Asus\anaconda3\envs\Malek2\lib\site-packages\torch\serialization.py", line 152, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "C:\Users\Asus\anaconda3\envs\Malek2\lib\site-packages\torch\serialization.py", line 136, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

Can you please tell me what need to be changed in order to run the training on my machine gpu instead of the CPU.

### Environment

- YOLO 5
- Windows 11 using spyder IDE
- Python-3.9.16

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@malekaburaddaha hello!

To run the training on a GPU instead of a CPU, you should specify the `--device` flag when running `train.py`. If you don't specify the flag, the default device will be used, which is the CPU.

To train on a single GPU, you can use `--device 0` and for multiple GPUs, you can use `--device 0,1,2` to specify the GPUs you want to use.

Additionally, make sure that you have CUDA installed on your machine and that you have a compatible GPU. You should also ensure that the version of PyTorch you are using is compatible with your CUDA installation.

I hope this helps! Let me know if you have any further questions.

Best regards, 
Glenn Jocher, Ultralytics team.

**Comment by Mr-Khans** [comment]
Hola @malekaburaddaha )
Try using your code in Google Colab for GPU testing. with a choice in the GPU settings
And cheak this code in your local machine

```python
import torch
print(torch.cuda.is_available())
print(torch.cuda.device_count())
print(torch.cuda.current_device())
print(torch.cuda.device(0))
print(torch.cuda.get_device_name(0))
``` 

This result will show you device and is it available CUDA (print(torch.cuda.is_available())):

CUDA is available and can be used by one device.
Device 0 refers to the GPU GeForce GTX 950M, and it is currently chosen by PyTorch.

**Comment by malekaburaddaha** [comment]
@Mr-Khans @glenn-jocher 

I just spent the last two days searching why I am getting "false" for "torch.cuda.is_available" and after trying several versions of cuda, finally it is working with cuda version 11.7 and pytorch version 1.13 
The main issues that I have are due the compatability between the pytorch version and cuda version that I have on my machine.
Thank you both for your help

**Comment by glenn-jocher** [comment]
@malekaburaddaha hello,

I am glad to hear that you were able to resolve the issue with your `torch.cuda.is_available()` returning "false". It's important to ensure the compatibility of both your PyTorch version and your CUDA version.

If you have any further issues or questions, feel free to let us know.

Best, 
Ultralytics team
