### ISSUE TITLE
train  with multy-gpu，why the usage of memory of gpu is unbalance especially for the first card 

### ISSUE THREAD

**Issue by AIFAN-Lab** [ultralytics/yolov5#116]
![image](https://user-images.githubusercontent.com/64510205/84966975-714db800-b145-11ea-8c51-4ecebcc51a8b.png)

**Comment by AIFAN-Lab** [comment]
I try increase the  --batch-size from 16 to 256, it  collapsed. If to find the reason,only the first card is out of memory.
python train.py --data coco.yaml --cfg yolov5s.yaml --weights '' --batch-size 16
So my question is how to make the every card have the equal memory usage?

**Comment by glenn-jocher** [comment]
@AIFAN-Lab for this and any other question, no one will have any idea what the context is unless you include **minimum viable code to reproduce**.

For example I would recommend you to not cache images, but since you have not included a single line of code you used to produce the above effect, I have no idea if you are using it or not.

**Comment by AIFAN-Lab** [comment]
OK. I just **git pull** the yolov5 code from the repo. And do nothing about the code. Just run the command   python train.py --data coco.yaml --cfg yolov5s.yaml --weights '' --batch-size 16.

**Comment by AIFAN-Lab** [comment]
(pt1.4.0) [xx@node01 yolov5]$ python train.py --data coco.yaml --cfg yolov5s.yaml --weights '' --batch-size 128
{'lr0': 0.01, 'momentum': 0.937, 'weight_decay': 0.0005, 'giou': 0.05, 'cls': 0.58, 'cls_pw': 1.0, 'obj': 1.0, 'obj_pw': 1.0, 'iou_t': 0.2, 'anchor_t': 4.0, 'fl_gamma': 0.0, 'hsv_h': 0.014, 'hsv_s': 0.68, 'hsv_v': 0.36, 'degrees': 0.0, 'translate': 0.0, 'scale': 0.5, 'shear': 0.0}
Namespace(adam=False, batch_size=128, bucket='', cache_images=False, cfg='./models/yolov5s.yaml', data='./data/coco.yaml', device='', epochs=300, evolve=False, img_size=[640, 640], multi_scale=False, name='', nosave=False, notest=False, rect=False, resume=False, single_cls=False, weights='')
Using CUDA Apex device0 _CudaDeviceProperties(name='GeForce RTX 2080 Ti', total_memory=11019MB)
                device1 _CudaDeviceProperties(name='GeForce RTX 2080 Ti', total_memory=11019MB)
                device2 _CudaDeviceProperties(name='GeForce RTX 2080 Ti', total_memory=11019MB)
                device3 _CudaDeviceProperties(name='GeForce RTX 2080 Ti', total_memory=11019MB)
                device4 _CudaDeviceProperties(name='GeForce RTX 2080 Ti', total_memory=11019MB)
                device5 _CudaDeviceProperties(name='GeForce RTX 2080 Ti', total_memory=11019MB)
                device6 _CudaDeviceProperties(name='GeForce RTX 2080 Ti', total_memory=11019MB)
                device7 _CudaDeviceProperties(name='GeForce RTX 2080 Ti', total_memory=11019MB)

Start Tensorboard with "tensorboard --logdir=runs", view at http://localhost:6006/

              from  n    params  module                                  arguments                     
  0             -1  1      3520  models.common.Focus                     [3, 32, 3]                    
  1             -1  1     18560  models.common.Conv                      [32, 64, 3, 2]                
  2             -1  1     20672  models.common.Bottleneck                [64, 64]                      
  3             -1  1     73984  models.common.Conv                      [64, 128, 3, 2]               
  4             -1  1    161152  models.common.BottleneckCSP             [128, 128, 3]                 
  5             -1  1    295424  models.common.Conv                      [128, 256, 3, 2]              
  6             -1  1    641792  models.common.BottleneckCSP             [256, 256, 3]                 
  7             -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]              
  8             -1  1    656896  models.common.SPP                       [512, 512, [5, 9, 13]]        
  9             -1  1   1905152  models.common.BottleneckCSP             [512, 512, 2]                 
 10             -1  1   1248768  models.common.BottleneckCSP             [512, 512, 1, False]          
 11             -1  1    130815  torch.nn.modules.conv.Conv2d            [512, 255, 1, 1]              
 12             -2  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 13        [-1, 6]  1         0  models.common.Concat                    [1]                           
 14             -1  1    197120  models.common.Conv                      [768, 256, 1, 1]              
 15             -1  1    313088  models.common.BottleneckCSP             [256, 256, 1, False]          
 16             -1  1     65535  torch.nn.modules.conv.Conv2d            [256, 255, 1, 1]              
 17             -2  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 18        [-1, 4]  1         0  models.common.Concat                    [1]                           
 19             -1  1     49408  models.common.Conv                      [384, 128, 1, 1]              
 20             -1  1     78720  models.common.BottleneckCSP             [128, 128, 1, False]          
 21             -1  1     32895  torch.nn.modules.conv.Conv2d            [128, 255, 1, 1]              
 22   [-1, 16, 11]  1         0  models.yolo.Detect                      [80, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]]]
Model Summary: 165 layers, 7.07417e+06 parameters, 7.07417e+06 gradients

Optimizer groups: 54 .bias, 60 conv.weight, 51 other
Caching labels ../coco/labels/train2017.npy (117266 found, 0 missing, 1021 empty, 0 duplicate, for 118287 images): 100%|███████████████████████████████████████████████| 118287/118287 [00:08<00:00, 14147.80it/s]
Caching labels ../coco/labels/val2017.npy (4952 found, 0 missing, 48 empty, 0 duplicate, for 5000 images): 100%|███████████████████████████████████████████████████████████| 5000/5000 [00:00<00:00, 14253.44it/s]

Analyzing anchors... Best Possible Recall (BPR) = 0.9949
Image sizes 640 train, 640 test
Using 8 dataloader workers
Starting training for 300 epochs...

**Comment by glenn-jocher** [comment]
@AIFAN-Lab ah ok! So you're simply doing a normal training with v5s and you want to use --batch 256 but you get CUDA out of memory?

I think --batch 64 will use up maybe 11 GB on a single GPU with v5s, but there is always extra overhead on GPU memory. You may want to look through the DDP implementation in train.py to see if there's anything you might want to change. I do all of my training on single-gpu, so I don't really have much info to give you. The DDP section is here:

https://github.com/ultralytics/yolov5/blob/9fdb0fbacf65ad6d8778da592ef9b87038a3f4c7/train.py#L146-L153

**Comment by AIFAN-Lab** [comment]
@glenn-jocher Thank you.What I want to say is that the memory usage of the first card will always be higher than others in one computer. It's just a phenomenon. And I find that the first card's memory may limit the batch-size.

![image](https://user-images.githubusercontent.com/64510205/84977521-1de76400-b15d-11ea-885f-5ea0786271b0.png)

**Comment by glenn-jocher** [comment]
Yeah, I see that. It might be normal, I’m not sure. Have you trained before with the same setup on other repos and observed balanced memory usage?

**Comment by AIFAN-Lab** [comment]
No,but I will try later.Thanks for your time.

**Comment by tjiagoM** [comment]
@glenn-jocher in your first comment in this thread you said that you do not recommend caching the images. Can you please explain why is that, as they supposedly speed up training? Thanks!

**Comment by glenn-jocher** [comment]
@tjiagoM do whatever works for you

**Comment by tjiagoM** [comment]
@glenn-jocher yes, I understand I can use whatever works for me, but I am asking what reasons you had to recommend that before, regardless of what I end up doing. I'm just trying to understand your reasons so I can make a decision, just because I didn't understand why you would recommend that in this situation. Thanks for your time!

**Comment by glenn-jocher** [comment]
@tjiagoM with unlimited ram, always cache. With zero ram, do not cache. For your situation, adjust accordingly.
