### ISSUE TITLE
is the prechained data with reflective vest ?

### ISSUE THREAD

**Issue by joegao1** [ultralytics/yolov5#11600]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

i want to detect persons with reflective vest only

**Comment by glenn-jocher** [comment]
@joegao1 hello!

YOLOv5 doesn't come with any pre-chained data for detecting reflective vests on persons. However, you may train the model on custom data for this use case. You might want to check out the Custom Data Training tutorial in our Tutorials section for more information.

I hope this helps! Let us know if you have any further questions or encounter any issues during training.

Best regards.

**Comment by joegao1** [comment]
Hi Glenn,

Thanks for the advices.
I have imported two yolov5 model weights, one is the original trained model given by the github master which include the person detection, another from third party trained model with reflective vest detection.
Then I combined the person detection and vest detection together to make my things work .

Thank you~

Best regards



发件人: Glenn Jocher ***@***.***>
发送时间: 2023年5月26日 15:28
收件人: ultralytics/yolov5 ***@***.***>
抄送: joegao1 ***@***.***>; Mention ***@***.***>
主题: Re: [ultralytics/yolov5] is the prechained data with reflective vest ? (Issue #11600)


@joegao1<https://github.com/joegao1> hello!

YOLOv5 doesn't come with any pre-chained data for detecting reflective vests on persons. However, you may train the model on custom data for this use case. You might want to check out the Custom Data Training tutorial in our Tutorials section for more information.

I hope this helps! Let us know if you have any further questions or encounter any issues during training.

Best regards.

**Comment by glenn-jocher** [comment]
@joegao1 hi,

I'm glad to hear that you were able to combine the person detection and vest detection models for your specific needs. Keep in mind that using a third-party trained model may not always yield the best results, so it's always a good practice to train your own models on custom data if possible.

Don't hesitate to reach out if you have any further questions or if you're facing any issues during training.

Best regards.
