### ISSUE TITLE
how can i detect rtsp every 100 frame,the parameter --vid-stride=100 isnot work

### ISSUE THREAD

**Issue by longeila** [ultralytics/yolov5#11602]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

how can i detect rtsp every 100 frame,the parameter --vid-stride=100 isnot work,and the loadstream()   ,where can i control the parameter --vid-stride
loadstream()         
   cap = cv2.VideoCapture(s)
            assert cap.isOpened(), f'{st}Failed to open {s}'
            w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
            h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
            fps = cap.get(cv2.CAP_PROP_FPS)  # warning: may return 0 or nan
            self.frames[i] = max(int(cap.get(cv2.CAP_PROP_FRAME_COUNT)), 0) or float('inf')  # infinite stream fallback
            self.fps[i] = max((fps if math.isfinite(fps) else 0) % 100, 0) or 30  # 30 FPS fallback
            # cap.set(cv2.CAP_PROP_POS_FRAMES,100)
            _, self.imgs[i] = cap.read()  # guarantee first frame
            self.threads[i] = Thread(target=self.update, args=([i, cap, s]), daemon=True)
            LOGGER.info(f"{st} Success ({self.frames[i]} frames {w}x{h} at {self.fps[i]:.2f} FPS)")
            self.threads[i].start()

**Comment by glenn-jocher** [comment]
@longeila hello! Have you tried the `--stride` parameter instead of `--vid-stride`? The `--stride` parameter can be used to set the number of frames to skip between inferred frames during video processing. Please let me know if that works for you. 

Regarding the `loadstream()` function, the `--stride` parameter can be controlled by passing it as an argument to the `VideoCapture()` function, like so: `cap = cv2.VideoCapture(s, cv2.CAP_FFMPEG)` and  `cap.set(cv2.CAP_PROP_POS_FRAMES, 100)`. Here, `100` determines the number of frames to skip before reading the first frame.

Let me know if this helps or if you have any further questions.

**Comment by ghost** [comment]
@glenn-jocher 
In YOLOv5 version 7.0, there is only the "--vid-stride" parameter available, and there is no "--stride" parameter.

I have a 60FPS RTSP (Real-Time Streaming Protocol) stream, but my computer is struggling to handle it. Therefore, I would like to reduce the frame rate to alleviate the detection workload. I don't need to detect every frame; I just want to perform detection on a fixed set of 10 frames.

**Comment by glenn-jocher** [comment]
Hello @**USERNAME**, 

Thank you for reaching out to us. I see that you are using YOLOv5 version 7.0 and looking to perform detection only on a fixed set of 10 frames from a 60FPS RTSP stream. 

In YOLOv5 version 7.0, the parameter to control the stride during video processing is `--vid-stride` as you mentioned. However, it may not fully achieve the desired results you are looking for in terms of resource management by skipping a set of 10 frames.

Alternatively, you can modify the `loadStream()` function in `/utils/datasets.py` to set the parameter "vid_stream" to the frame rate of your choosing based on your hardware capabilities and stream. You may also modify the "running" function in `/core/operations.py` to apply detection only on every 10th frame. 

Let me know if this helps or if you have any further questions.

Best, 
Glenn Jocher
