### ISSUE TITLE
Can't tell the time

### ISSUE THREAD

**Issue by krolaper** [ultralytics/yolov5#11606]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

when trying to run the analysis all the time, the error is that it cannot determine the time. The error came from nowhere.
```
File "utils/torch_utils.py", line 110, in select_device
  File "utils/general.py", line 286, in file_date
  File "pathlib.py", line 1097, in stat
FileNotFoundError: [Errno 2] No such file or directory: '/home/odinson/PycharmProjects/Panning/Video/all/dist/main/yolov5/utils/general.pyc'
```
this is after packaging via pyinstaller

### Environment

YOLOv5 🚀 2023-4-22 Python-3.10.6 torch-1.12.1+cu102 CUDA:0 (NVIDIA GeForce MX130, 2004MiB)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by krolaper** [comment]
sorry, this is a problem in pyinstaller, the bug is removed, because without pyinstaller everything is ok. I'll figure it out myself then

**Comment by glenn-jocher** [comment]
@krolaper we're sorry to hear that you're experiencing issues when running YOLOv5 after packaging via pyinstaller. However, we are glad to know that the issue is resolved when YOLOv5 is run without pyinstaller. 

If you have any further questions or concerns, please don't hesitate to reach out. Our team is always here to help.

**Comment by mashuai191** [comment]
@krolaper  i met the same issue, and then i tried to copy the general.py to general.pyc. then everything is ok. hope that works for you as well.

<img width="430" alt="image" src="https://github.com/ultralytics/yolov5/assets/40193779/eefa4f1e-c492-4b2c-a6f5-67d9b65874a2">

**Comment by glenn-jocher** [comment]
@mashuai191 It's great to see community members helping each other out! 😊 Copying `general.py` to `general.pyc` might be a workaround for the issue with pyinstaller. However, keep in mind that `.pyc` files are compiled Python files, so this might not be the best long-term solution.

If you encounter any other issues or have questions about YOLOv5, feel free to ask. The community and the Ultralytics team are here to support you. Happy coding! 🚀
