### ISSUE TITLE
About change the port of tensorboard

### ISSUE THREAD

**Issue by zdxff** [ultralytics/yolov5#11609]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Can I change the port of tensorboard? And how I do?

**Comment by glenn-jocher** [comment]
@zdxff hello! Yes, you can change the port of tensorboard by adding the `--port` argument when running tensorboard. For example, you could run `tensorboard --logdir runs --port 6006` to start tensorboard on port 6006. Let us know if you have any further questions or issues!
