### ISSUE TITLE
Object detection using YOLOv5 with Tello drone

### ISSUE THREAD

**Issue by Bitahsni** [ultralytics/yolov5#11613]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello everyone, I want to Object detection using YOLOv5 with my Tello drone, I can't use the detect.py for detection on live stream from Tello drone! I know, I should use the PyTorch Hub for detection without cloning the YOLOv5 repo, But how can I feed the live stream taken from Tello's camera into Yolo in PyTorch Hub?
Thank you in advance!

**Comment by glenn-jocher** [comment]
@Bitahsni hello,

One approach to feeding live stream data into YOLOv5 with PyTorch Hub would be to capture the video stream from the Tello's camera, convert each frame to a tensor, and pass it through the YOLOv5 model loaded from PyTorch Hub. You can use OpenCV or Pygame libraries to capture the video stream from the Tello's camera and convert each frame into a tensor that can be passed to PyTorch. You can find several examples on how to perform object detection on live streams using YOLOv5 by searching on Github or Google.

I hope this helps. Let me know if you have any further questions.

Thank you.

**Comment by chelsea456** [comment]
my project using flycam Dji detect infected dargon tree. my video link youtube: https://youtu.be/Jf4T4jK_qDs

**Comment by glenn-jocher** [comment]
@chelsea456 hello,

Thank you for sharing your project with us! The video you linked shows a great use case for object detection using YOLOv5.

If you have any specific questions or issues related to your use case, please feel free to let us know and we'll be happy to assist you.

Thank you!

**Comment by Bitahsni** [comment]
@chelsea456 and @glenn-jocher  Thank you for your answers, I will follow your instructions and I will announce the result here.

**Comment by glenn-jocher** [comment]
@Bitahsni you're welcome! We're glad to hear our suggestions were helpful. Please don't hesitate to reach out if you have any further questions or issues. We look forward to hearing about your progress.
