### ISSUE TITLE
Feature Extraction without running the entire model

### ISSUE THREAD

**Issue by samvandha** [ultralytics/yolov5#11617]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

I have a custom-trained weights file. I am using the model to first recognize objects and then use feature extraction from Stage0_conv_features to carry about morphological operations. I can successfully extract the feature map using the --visualize flag. However, as I only want the feature map from the first conv layer running the entire model will only take up more time. Is it possible to modify and only take the output from the first layer rather than running the entire model?

### Use case

I am using YOLOv5 to detect tablets in a strip of tablets. I will be using the feature map to find the contour of each tablet by selecting the best feature map suitable for contour to see the contour defects. This approach is a little different than semantic segmentation mostly to save time.
![stage0_Conv_features](https://github.com/ultralytics/yolov5/assets/37346976/a964ed09-060c-4fdc-a3a3-6811a495dc27)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@samvandha hello! Thank you for your question and for using YOLOv5 🔍 

To answer your question, it is possible to extract the feature map from the first convolutional layer without running the entire model if you modify the YOLOv5 source code. You can modify the `models/yolo.py` file and add a `forward_features()` method that only processes the first convolutional layer's feature maps. 

After you modify the code, you can use the `--source your/input/images --features` command line flag to extract the feature maps directly from your input images. 

Please let us know if you have any further questions and good luck in your work with YOLOv5!

**Comment by samvandha** [comment]
Thank you so much @glenn-jocher for the response and YOLO. We have used YOLO v5 in many use cases and it has never failed to impress.

**Comment by glenn-jocher** [comment]
@samvandha Thank you for your kind words and for using YOLOv5! We are glad to hear that it has worked well in your use cases. If you have any further questions or feedback, please don't hesitate to reach out. We are always happy to help and appreciate your support!
