### ISSUE TITLE
Weight update before training completes?

### ISSUE THREAD

**Issue by b4u365** [ultralytics/yolov5#11610]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi Team,

Training was converged at 50 epochs, however I have requested for 100 epochs, Meaning not much change in map values between 100 epochs and 50 epoch. I tried to terminate the training at 50 epochs , however the weights are not being generated if I terminate in middle. Is there any way I can get the weights written at desired epochs or  for every 20 epochs or so. So that we can check the runs and terminate if the training results are fine Enough. 

Regards,
Bharath.

**Comment by glenn-jocher** [comment]
@b4u365 hello Bharath,

Thank you for reaching out to us!

Regarding your question, it is not possible to write intermediate weights during training in YOLOv5. When you terminate training in the middle, the training process does not write any new weights, so you will need to restart training from scratch or from the last checkpoint if you have any.

However, you can choose to periodically save weights by adjusting the `--save-period` argument in the `train.py` script. This will save the weights at desired epochs or after a certain number of steps.

I hope this helps! Let us know if you have further questions or concerns.

Best, 
Glenn Jocher

**Comment by b4u365** [comment]
Appreciate Glenn for your quick response,
 
Additionally, is there any way to stop the training automatically once some desired convergence is achieved, or when there is minimal change  in ap consequent 5  epochs or so??

Superb, that's all I needed. 

Have a great Weekend.

Thanks and Regards,
Bharath

**Comment by glenn-jocher** [comment]
@b4u365 hello Bharath,

Thank you for your kind words! Regarding your question, you can use the `--early-stopping-epochs` argument in the `train.py` script to stop training automatically once some desired convergence is achieved. This argument stops training if the model's AP does not improve by a certain threshold for a specified number of epochs.

Furthermore, you can use the `--checkpoint-freq` argument to save the model checkpoints at specific epochs, so you can stop training once there is a minimal change in the AP for several consecutive epochs.

I hope this helps!

Have a great weekend!

Best, Glenn Jocher
