### ISSUE TITLE
mloss is not multi-GPU loss mean

### ISSUE THREAD

**Issue by WZMIAOMIAO** [ultralytics/yolov5#1161]
## ❔Question
first of all, thank the author for sharing the quality code.

in my opinion, mloss only calculate mean loss on gpu:0, not all gpu device.
https://github.com/ultralytics/yolov5/blob/master/train.py#L269-L286
I think we first need to use ```dist.all_reduce()``` function to calculate sum of loss from all gpu device.

refer to: https://github.com/pytorch/vision/blob/master/references/detection/utils.py#L118-L142
https://pytorch.org/tutorials/intermediate/dist_tuto.html#collective-communication

**Comment by glenn-jocher** [comment]
@WZMIAOMIAO multi-gpu training operates correctly. The official YOLOv5x weights are trained with multi-gpu for example. See mutli-gpu training tutorial for directions: https://docs.ultralytics.com/yolov5
