### ISSUE TITLE
How can I run train.py without any pt files?

### ISSUE THREAD

**Issue by stylevip** [ultralytics/yolov5#11616]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to test the training with out any pretrained models. How can I to this？

**Comment by glenn-jocher** [comment]
@stylevip hello! Yes, you can train a model from scratch with no pre-trained weights. Simply set the `--weights` argument in `train.py` to `''` and the model will be initialized randomly before starting the training process.

Let me know if you have any other questions or concerns!

**Comment by stylevip** [comment]
> 

thanks. I tried "--weights ' ', but it showed not such file or dictionary.Is there a blank between '  '?

**Comment by glenn-jocher** [comment]
@stylevip, you're welcome! Yes, there should be a space between the single quotes in `' '`. If you're still getting a "no such file or directory" error, you might want to double check the path of your `--weights` argument to make sure it's pointing to a valid directory. Let me know if this helps!

**Comment by stylevip** [comment]
> @stylevip, you're welcome! Yes, there should be a space between the single quotes in `' '`. If you're still getting a "no such file or directory" error, you might want to double check the path of your `--weights` argument to make sure it's pointing to a valid directory. Let me know if this helps!

I really appreciate it!

**Comment by glenn-jocher** [comment]
You are very welcome, @stylevip! If you have any further questions or issues with YOLOv5, feel free to reach out and the Ultralytics team and community will do our best to help you out. Happy training!
