### ISSUE TITLE
How to extract objects only when a certain confidence value (0.7 or higher) is obtained.

### ISSUE THREAD

**Issue by PGSBlog** [ultralytics/yolov5#11622]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hi! I am a student studying object detection. I want to extract an object only when confidence is 0.7 or higher in mAP, but I want to know how.

For example, if the confidence of people, dogs, and cats is greater than 0.7, I want to output people, dogs, and cats as results.

Thanks.

**Comment by glenn-jocher** [comment]
@PGSBlog hello! 

Thank you for reaching out to the YOLOv5 community for help. To extract objects with a certain confidence value, you can set the `--conf-thres` argument in the detect.py script to your desired value. For example, if you set `--conf-thres 0.7`, the script will only output detections with a confidence score of 0.7 or higher.

In your case, assuming you want to output specific object classes with a confidence score of 0.7 or higher, you can modify the detect.py script to filter out detections that do not meet your confidence threshold or class criteria.

I hope this helps. Let us know if you have any further questions or need additional assistance.

Best regards, 
The YOLOv5 team

**Comment by PGSBlog** [comment]
Thank you for quick response! 

I have one question for you.

I set conf_thres=0.75 in detect.py, but when I run the terminal, conf_thres=0.25 comes out from the CLI

So, I modified all files written with conf_thres=0.25 to conf_thres=0.75. However, when running the terminal, conf_thres=0.25 is displayed.

I don't know what the problem is....

**Comment by PGSBlog** [comment]
Solved. I did not change the default value. I fixed it by changing the default value. : )

**Comment by glenn-jocher** [comment]
@PGSBlog glad to hear that the issue has been resolved! If you have any other questions or concerns, feel free to reach out to the YOLOv5 community. Have a great day!

**Comment by PGSBlog** [comment]
Thank you for quick response. I would like to ask you another additional question! 

When detecting objects by streaming, the frames are too fast. Right now I want to run a frame about twice a second. Is it possible?

**Comment by glenn-jocher** [comment]
Hello @{GitHubUsername}, glad to hear that you found our response helpful. Regarding your question, it is possible to slow down the inference speed when detecting objects in a video stream. You can achieve this by setting the `--source` argument to your video stream source (e.g. a URL for an IP camera or the number of the camera's USB port), and then setting the `--fps` argument to the desired frame rate (e.g. 2). This will limit the number of frames processed per second to match your preferred rate of about twice a second.

I hope this helps! Let us know if you have any further questions or need additional assistance.

Best regards,
The YOLOv5 team

**Comment by PGSBlog** [comment]
If you try to test it with a webcam or YouTube, 'detect.py: error: unrecognized arguments: --fps 2' error occurs.

Can't use webcam or youtube?

And can you show me just one command example using --fps?

**Comment by glenn-jocher** [comment]
@PGSBlog hello! The `--fps` argument is only used when reading a video file with detect.py. It is not applicable to webcams or YouTube videos as these sources have their own frame rate set by default. 

If you want to limit the processing speed of frames from a webcam or YouTube video, you can use the `--source` argument to specify a frame rate, like this: 

````bash
python detect.py --source 0 --conf-thres 0.5 --source http://www.youtube.com/watch?v=XXXXXXXXXXX --fps 2
````

In this example, `--source 0` specifies the first available webcam, `--conf-thres 0.5` sets the confidence threshold to 0.5, and the `--source http://www.youtube.com/watch?v=XXXXXXXXX` specifies the video source URL for YouTube. `--fps 2` sets the desired processing frame rate to two (2) frames per second.

I hope this helps! Let us know if you have any further questions or need additional assistance.

Regards,
The YOLOv5 Team

**Comment by PGSBlog** [comment]
Thank you for always replying. One last question. I am currently working on a assignment using yolov5 open source.

When the result value comes out from the terminal CLI (e.g. 0: 480x640 1 person, 9.0ms), if 1 person comes out, I want to send it to the server with POST.

If you look at line 211 of detect.py,

```
' LOGGER.info(f'Speed: %.1fms pre-process, %.1fms inference, %.1fms NMS per image at shape {(1, 3, *imgsz)} ' %t ) '
```
I think the result value is output from the command.

```
import requests

#POST method data processing

# Execute command and get result value
result = input("Enter the command result: ")

# URL to send POST request to
url = 'Server IP'

if result.strip() == 'A':

    # request body data

    data = {
        'uid_id': '(e.g) value1',
        'title': 'Person',
        'body' : 'A person appeared.'}

    response = requests.post(url, json=data)

    if response.status_code == 200:
        response_data = response.json()
        print(response_data)
    else:
        print('Error:', response.status_code)
else:
    print('Invalid command result.')
```

The above code sends to the server in the POST method when the value 'A'  is entered.

If  '1 person'  is the result in detect.py, I want to send it in POST method. I would like some references or advice.

**Comment by glenn-jocher** [comment]
@PGSBlog hi,

Thanks for your question. To send the result of the detection to your server using POST method in detect.py script, you can modify the code on line 211 as below:

```
result_value = '' # initialize result_value as an empty string

# Extract the number of persons detected from the result string
for r in results.int_arr:
  result_value += f'{r[1]} persons, ' # concatenate the respective results

# Check if the number of persons detected is greater than 0, if so send the result to the server using POST method
if '1 person' in result_value:
    url = 'http://SERVER_IP_ADDRESS:PORT_NUMBER' # Replace with your server URL
    data = {
        'uid_id': '(e.g) value1',
        'title': 'Person',
        'body' : 'A person appeared.'}
    response = requests.post(url, json=data)
    if response.status_code == 200:
        response_data = response.json()
        print(response_data)
    else:
        print('Error:', response.status_code)
```
   
This code will check if the number of persons detected is greater than 0 in the result string 'result_value'. If the condition is true, the code sends the result to the server using the POST method with the required data.

Please replace 'http://SERVER_IP_ADDRESS:PORT_NUMBER' with your server's IP address and port number in the url variable.

Let us know if you have any further questions or need additional assistance.

Regards,
The YOLOv5 team

**Comment by PGSBlog** [comment]
Thank you very much. I'll test it after class. Thank you for always responding kindly and giving advice. : )

**Comment by glenn-jocher** [comment]
@PGSBlog hello,

You're welcome! We're always here to help and assist our community. Feel free to test it and let us know if you need further assistance. 

Have a great day!

Regards,
The YOLOv5 Team

**Comment by PGSBlog** [comment]
First, in detect.py, the command on line 209, not line 211, was a function that outputs the result value (CLI).

So, when I commented out the function on line 209 and modified it with the code you gave me, the following error occurred.
```
NameError: name 'results' is not defined. Did you mean: 'result'?
Aborted (core dumped)
```

And, as in the code below, I am trying to receive a token (url) from the Flask Server and send it in the POST method when running 1 person in the terminal.

I'd like to ask for some new advice. I'm sorry.


```
import requests

#POST method data processing

# Executing the command and getting the result value

result = input("Enter the command result: ")

# get member info of current uid -> take out token only

url2 = "Get server Token"
response2 = requests.get(url2) 

# URL to send POST request to
url = "POST server Token"
json_response = response2.json()

for i in json_response:
    
    if result.strip() == 'A':

        # request body data
        data = {
            'user_id': i['token'],
            'title': 'Person',
            'body' : 'I see 1 person.'
    }
        response = requests.post(url, json=data)
print(response)
```

**Comment by glenn-jocher** [comment]
@PGSBlog hello,

We apologize for the confusion earlier. Regarding your recent error, the cause may be the variable `results` not being defined in the function. You can check if the variable `results` exists by running the `print(results)` before this line:

```if '1 person' in result_value:```

Regarding your current code, we can see that you are trying to get a token URL from a Flask server to use in the POST request. It seems that you are using a GET request to retrieve the token from the URL specified in `url2`. 

After you receive the response from the server, you should loop through the results and get the token for each user. You can use this token to send the POST request to the server.

Here is an updated code example for your POST request:

```
import requests

#POST method data processing

# Executing the command and getting the result value
result = input("Enter the command result: ")

# Getting the server token using a GET request
url2 = "Get server Token URL"
response2 = requests.get(url2) 
json_response = response2.json()

# Extracting the token for each user from the JSON response
for i in json_response:
    token = i['token']
    
    # Sending the POST request if the result is true
    if '1 person' in result:
        url = "POST server Token URL"
        data = {
            'user_id': token,
            'title': 'Person',
            'body' : 'I see 1 person.'
        }
        response = requests.post(url, json=data)
        print(response)
```

Please replace the `Get server Token URL` and `POST server Token URL` with the correct URLs.

Let us know if you have any further questions or need additional assistance.

Regards,
The YOLOv5 Team
