### ISSUE TITLE
Fail to use yolov5x - 7.0 in OpenCV 4.6.0 c++

### ISSUE THREAD

**Issue by jeffreyhaoau** [ultralytics/yolov5#11628]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Fail to use yolov5x - 7.0 in OpenCV 4.6.0 c++
Fail to use yolov5x - 7.0 in OpenCV 4.7.0 c++
Success to use yolov5x - 7.0 in OpenCV 4.6.0 Python

Success to use yolov5x - 6.2 in OpenCV 4.6.0 c++
Success to use yolov5x - 6.2 in OpenCV 4.6.0 Python

Success to use yolov5x - 6.1 in OpenCV 4.6.0 c++
Success to use yolov5x - 6.1 in OpenCV 4.6.0 Python

**It only happens on yolov5x.
No issue with yolov5l, yolov5m.**

https://raw.githubusercontent.com/spmallick/learnopencv/master/Object-Detection-using-YOLOv5-and-OpenCV-DNN-in-CPP-and-Python/yolov5.cpp

Convert to onnx for opencv dnn.
$ python export.py --weights yolov5x.pt --include onnx

This error (Segmentation Fault) is relevant to this:
line 77: const int rows = 25200;
The loop (line79-118) will crash.

### Environment

Ubuntu 22.04
CPU
Yolov5 - 7.0
OpenCV 4.6.0, c++ DNN API

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello @jeffreyhaoau, 

Thank you for reporting this issue. We're sorry to hear that you're encountering this problem with using YOLOv5 - 7.0 in OpenCV 4.6.0 C++. 

We appreciate you including all of the environment information and other details in your report as well. This will help us to more effectively determine the root of the issue.

Regarding your point about the segmentation faults, it seems like the variable declaration `const int rows = 25200` may be causing the issue. We suggest reviewing other parts of your codebase to determine the cause of the segmentation fault in your program. 

If you have any further questions or concerns, please do not hesitate to ask. We'll do our best to help you resolve this issue. Thank you for your attention to this matter.

Best regards, 
Glenn Jocher

**Comment by jeffreyhaoau** [comment]
@glenn-jocher glenn-jocher
Sorry, I forgot this: 
**It only happens on yolov5x.
No issue with yolov5l, yolov5m.**

**Comment by glenn-jocher** [comment]
Hi @jeffreyhaoau,

Thank you for providing that additional information. It's helpful to know that the issue only appears to occur with YOLOv5x and not with YOLOv5l or YOLOv5m.

Given that, it's possible that there may be some differences in the implementation or structure of these models that could be causing the issue with YOLOv5x in OpenCV 4.6.0 C++. We suggest reviewing your code and checking for any differences in these areas that could be contributing to the problem.

If you have any further questions or concerns, please don't hesitate to ask. We'll continue to do our best to assist you in troubleshooting this issue.

Best regards, 
Glenn Jocher
