### ISSUE TITLE
Feature maps of detection layers

### ISSUE THREAD

**Issue by HelenVe** [ultralytics/yolov5#11623]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello!

I am using a custom yolov5 model.
I was wondering if there's a quick way to obtain the feature maps from the Detection layers. 

Thanks :)

**Comment by glenn-jocher** [comment]
@HelenVe hello!

Thank you for reaching out.

Yes, you can easily obtain the feature maps from the Detection layers. You just need to modify the `yolo_head()` function in the `models/yolo.py` file accordingly. Specifically, you can add a new argument to the `yolo_head()` function that controls whether to return the feature maps or not. Then, modify the function to return the feature maps when the new argument is True. After that, you can call the modified `yolo_head()` function with the new argument set to True to obtain the feature maps.

If you need further assistance, please let me know.

Best regards,

**Comment by HelenVe** [comment]
Hi Glenn, 

thank you for the quick answer!
When you say the yolo_head() function, do you mean the forward method of the Detect() class? 

Best regards,

**Comment by glenn-jocher** [comment]
@HelenVe hello! 

Yes, I apologize for not being clear earlier. I meant the `forward()` method in the `Detect()` class located in `models/detect.py`. Specifically, you should modify the `yolo_head()` function inside the `forward()` method. Let me know if you have any further questions or if I can assist you any further.

Best,
