### ISSUE TITLE
yolov5 can not torch.jit.trace-able

### ISSUE THREAD

**Issue by 1pikachu** [ultralytics/yolov5#11633]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

RuntimeError: Tracer cannot infer type of [tensor([[[5.57923e+00, 6.25768e+00, 1.08878e+01,  ..., 4.59424e-03, 7.72032e-04, 2.78392e-03],
         [1.18346e+01, 7.10616e+00, 2.36659e+01,  ..., 4.56852e-03, 8.89309e-04, 2.57247e-03],
         [1.80006e+01, 6.93209e+00, 3.17432e+01,  ..., 4.48723e-03, 8.52814e-04, 2.07415e-03],
         ...,
         [5.63079e+02, 6.01169e+02, 1.50555e+02,  ..., 1.04943e-02, 2.27958e-03, 3.75270e-03],
         [5.87008e+02, 6.01688e+02, 1.18021e+02,  ..., 8.70303e-03, 2.73107e-03, 3.01351e-03],
         [6.19238e+02, 6.11555e+02, 1.65463e+02,  ..., 9.06936e-03, 3.09023e-03, 3.60383e-03]]], device='cuda:0'), [tensor([[[[[ 4.00059e-01,  5.80164e-01,  8.69507e-02,  ..., -5.37835e+00, -7.16571e+00, -5.88111e+00],
           [-4.13613e-02,  8.19523e-01,  1.20372e+00,  ..., -5.38399e+00, -7.02418e+00, -5.96031e+00],
           [-5.10676e-01,  7.68775e-01,  2.09925e+00,  ..., -5.40202e+00, -7.06612e+00, -6.17613e+00],
           ...,
           [ 3.43397e-01,  9.42274e-01,  2.16496e+00,  ..., -5.21882e+00, -6.84618e+00, -5.92309e+00],
           [ 8.94921e-02,  9.26435e-01,  1.22517e+00,  ..., -5.18914e+00, -6.82956e+00, -5.79423e+00],
           [-4.40004e-01,  5.56957e-01,  1.07943e-01,  ..., -5.34441e+00, -6.95667e+00, -5.72024e+00]],

          [[ 7.50478e-01, -8.63435e-02,  3.28682e-01,  ..., -5.31733e+00, -6.95523e+00, -6.04924e+00],
           [ 2.47465e-01,  2.65960e-01,  1.39516e+00,  ..., -5.00473e+00, -6.69639e+00, -6.07890e+00],
           [-7.59789e-01,  1.91516e-01,  2.49449e+00,  ..., -5.18128e+00, -6.83407e+00, -6.25615e+00],
           ...,
           [ 5.91552e-01,  3.57564e-01,  2.52419e+00,  ..., -4.96057e+00, -6.65171e+00, -6.00591e+00],
           [-3.44002e-01,  3.15315e-01,  1.48473e+00,  ..., -4.87298e+00, -6.57908e+00, -5.96202e+00],
           [-9.36810e-01,  1.26931e-01,  4.61611e-01,  ..., -5.07797e+00, -6.73743e+00, -5.90376e+00]],

          [[ 8.57652e-01, -1.55389e-01,  3.99122e-01,  ..., -5.71274e+00, -6.95087e+00, -6.15736e+00],
           [ 3.55313e-01, -1.06351e-02,  1.51315e+00,  ..., -5.51946e+00, -6.72105e+00, -6.21219e+00],
           [-7.63574e-01, -4.06722e-02,  2.62285e+00,  ..., -5.53891e+00, -6.63281e+00, -6.17486e+00],
           ...,
           [ 6.11775e-01, -3.66139e-02,  2.64260e+00,  ..., -5.25890e+00, -6.37659e+00, -5.82866e+00],
           [-4.25637e-01, -1.70558e-02,  1.56548e+00,  ..., -5.40975e+00, -6.50415e+00, -5.90327e+00],
           [-1.05134e+00, -1.79090e-01,  5.23886e-01,  ..., -5.49894e+00, -6.70427e+00, -5.85343e+00]],

          ...,
          [[ 9.24088e-01, -7.47257e-04, -8.57785e-01,  ..., -4.47604e+00, -5.68056e+00, -5.26337e+00],
           [ 6.03161e-01, -1.81635e-02, -9.66387e-01,  ..., -4.16891e+00, -5.81773e+00, -5.48160e+00],
           [-1.95203e-01,  5.36896e-02, -7.53530e-01,  ..., -4.20496e+00, -6.29888e+00, -5.66194e+00],
           ...,
           [ 3.09723e-01,  3.77016e-02, -7.79235e-01,  ..., -4.22216e+00, -6.44116e+00, -5.85959e+00],
           [-5.54888e-01,  1.64620e-02, -9.78975e-01,  ..., -4.33135e+00, -6.21434e+00, -5.88328e+00],
           [-1.15129e+00, -2.66415e-02, -8.93355e-01,  ..., -4.42115e+00, -6.01235e+00, -5.61833e+00]],

          [[ 7.44515e-01, -5.35410e-01, -8.26554e-01,  ..., -4.98502e+00, -5.71386e+00, -5.61532e+00],
           [ 5.57424e-01, -7.57732e-01, -9.55983e-01,  ..., -4.78090e+00, -5.78451e+00, -5.69675e+00],
           [-2.69236e-01, -6.04813e-01, -7.69867e-01,  ..., -4.70091e+00, -6.09935e+00, -5.82592e+00],
           ...,
           [ 3.65082e-01, -6.44821e-01, -7.91110e-01,  ..., -4.42684e+00, -6.22743e+00, -5.76461e+00],
           [-5.02734e-01, -7.67401e-01, -9.78794e-01,  ..., -4.55355e+00, -6.05403e+00, -5.89301e+00],
           [-1.05007e+00, -5.26006e-01, -8.60868e-01,  ..., -4.71128e+00, -5.98322e+00, -5.90735e+00]],

          [[ 1.73417e-01, -7.82766e-01, -7.19126e-01,  ..., -5.00484e+00, -5.69743e+00, -5.43336e+00],
           [ 3.45405e-01, -1.61614e+00, -9.02367e-01,  ..., -4.89987e+00, -5.75392e+00, -5.67519e+00],
           [-1.37769e-01, -1.73775e+00, -7.53504e-01,  ..., -4.79111e+00, -6.01165e+00, -5.64690e+00],
           ...,
           [ 1.93013e-01, -1.78838e+00, -7.64545e-01,  ..., -4.54637e+00, -6.08148e+00, -5.58152e+00],
           [-3.14600e-01, -1.72387e+00, -9.38262e-01,  ..., -4.73534e+00, -5.90033e+00, -5.80163e+00],
           [-2.99852e-01, -8.21047e-01, -6.94572e-01,  ..., -4.69374e+00, -5.77641e+00, -5.62215e+00]]]]], device='cuda:0')]]
:List inputs to traced functions must have consistent element type. Found Tensor and List[Tensor]

### Environment

yolov5:
    - branch: master
    - commit: 573334200866d5400325c0e8430c7154f7f23a59
    - pip install ultralytics && pip install -r requirements.txt
OS: ubuntu18.04
python: 3.9.16
torch: 2.0.1
cuda: 11.8

### Minimal Reproducible Example

import torch
from models.common import DetectMultiBackend

weights = "./yolov5x.pt"      # download from `model = torch.hub.load('ultralytics/yolov5', 'yolov5x')`
device = torch.device("cuda")
data = "<your_path>/COCO2017/val2017"
dnn = False
model = DetectMultiBackend(weights, device=device, dnn=dnn, data=data, fp16=False)

im = torch.zeros([1, 3, 640, 640]).cuda()

model(im)
print("warmup, build grids")
torch.jit.trace(model, im)
print("jit success")

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@1pikachu thank you for reporting this issue with YOLOv5. We apologize for the inconvenience this may have caused. Our team is aware of this error and is working on a fix for a future release of YOLOv5. Please keep an eye on our GitHub repository for updates. Thank you for your patience and understanding.

**Comment by lucastack** [comment]
Hello @1pikachu, The problem is that the output of `self.model` inside `DetectMultiBackend` is a list of 2 tensors, one is the output of the model and the other is the loss, a quick solution can be to wrap it up inside another model to just get the output


```
import torch
import functools
from models.common import DetectMultiBackend

weights = "./yolov5x.pt" # download from model = torch.hub.load('ultralytics/yolov5', 'yolov5x')
device = torch.device("cuda")
data = "<your_path>/COCO2017/val2017"
dnn = False


class ModelWrapper(DetectMultiBackend):
    def __init__(self, weights="yolov5s.pt", device=..., dnn=False, data=None, fp16=False, fuse=True):
        super().__init__(weights, device, dnn, data, fp16, fuse)
    
    def forward(self, im, augment=False, visualize=False):
        out, loss = super().forward(im, augment, visualize)
        return out

    


model = ModelWrapper(weights, device=device, dnn=dnn, data=data, fp16=True)

model.forward = functools.partial(
        model.forward, augment=False, visualize=False
)

im = torch.zeros([1, 3, 640, 640], dtype=torch.float16).cuda()

out = model(im)

print("warmup, build grids")
torch.jit.trace(model, im)

torch.save(model, "traced.pt")
print("jit success")
```


If you have any question i'll be happy to help

Regards!

**Comment by glenn-jocher** [comment]
Hello @lucastack, thank you for bringing this issue to our attention. As mentioned by @fornade, one possible solution is to wrap the output of `self.model` inside another model to get the desired output. The code provided by @fornade should work for you, but if you have any questions or need further assistance, please don't hesitate to ask. Thank you for using YOLOv5!

**Comment by 1pikachu** [comment]
It looks good to me, I will have a try, thanks

**Comment by glenn-jocher** [comment]
@1pikachu thank you for your interest in YOLOv5! We hope that the provided solution works for you. If you have any further questions or concerns, please don't hesitate to reach out to us. We're always here to help you get the most out of YOLOv5!
