### ISSUE TITLE
yolov5s-cls can train with 16:9 model?

### ISSUE THREAD

**Issue by erquren** [ultralytics/yolov5#11634]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I try to train a classifying model to classify two class ,the train image all is 16:9  1920x1080

When i run classify/train.py ,the image shape default is 224x224 ,in the yolov5 detect ,i can change it to [960,544] but ,yolov5 cls cant do it.

When i train the model with 960x960, the train data is resize 1920x1080 to 960x544 and padding to 960x960

This model result is bad,any body can tell the yolov5-cls can train with 16:9 ?

**Comment by glenn-jocher** [comment]
@erquren hi there,

YOLOv5-cls can train with images of any aspect ratio and resolution, including 16:9 ratio. In order to do this, you need to adjust the image size parameter in the configuration file you are using for training. For example, in the yolov5s.yaml file, you can modify the 'img_size' value to [960,544] or any size of your choosing, and then run the training script accordingly.

If you still face any issues training with this configuration, please feel free to ask for further assistance. 

Hope this helps!

**Comment by erquren** [comment]
Thanks for you answer,GJ, when i run the command args with "--img 960 544" 
It is error for me,  the type must be int

utils/augmentations.py  

def classify_transforms(size=224):
    # Transforms to apply if albumentations not installed
    assert isinstance(size, int), f'ERROR: classify_transforms size {size} must be integer, not (list, tuple)'
    # T.Compose([T.ToTensor(), T.Resize(size), T.CenterCrop(size), T.Normalize(IMAGENET_MEAN, IMAGENET_STD)])
    return T.Compose([CenterCrop(size), ToTensor(), T.Normalize(IMAGENET_MEAN, IMAGENET_STD)])

i change to 
def classify_transforms(size=224):
    # Transforms to apply if albumentations not installed
    # assert isinstance(size, int), f'ERROR: classify_transforms size {size} must be integer, not (list, tuple)'
    # T.Compose([T.ToTensor(), T.Resize(size), T.CenterCrop(size), T.Normalize(IMAGENET_MEAN, IMAGENET_STD)])
    return T.Compose([LetterBox(size), ToTensor(), T.Normalize(IMAGENET_MEAN, IMAGENET_STD)])

and the train is can normal  run,and result is good, i did not find any args can change classify_transforms change LetterBox or CenterCrop, only modify the code

**Comment by glenn-jocher** [comment]
Hi @erquren,

Glad to hear that you were able to resolve your issue by modifying the classify_transforms function. As you noted, currently there is no argument to change the transformation from CenterCrop to LetterBox, and hence you had to modify the function manually. We appreciate your feedback and will take it into consideration for future updates to the repo.

Please feel free to ask for further assistance if you face any issues such as this in the future. Thanks for using YOLOv5!
