### ISSUE TITLE
export model to openvino gives a issue

### ISSUE THREAD

**Issue by kmlrohin1** [ultralytics/yolov5#11645]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

i m trying to export yolov5 model to openvino but i m getting the error

![image](https://github.com/ultralytics/yolov5/assets/131166922/690eaaec-9515-4fab-ad97-f5f1407c8f9c)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@kmlrohin1 hello, 

Thank you for reaching out to us. We're sorry to hear that you're experiencing an error when trying to export YOLOv5 model to OpenVINO. We would be happy to help you further with this.

It looks like the provided error is a screenshot. Could you please provide details such as Operating System, OpenVINO version and a minimal code snippet or a terminal command example along with the complete error log? This would help us to better understand the issue you are facing and assist you in resolving it.

Please let us know if you have any further questions or concerns.

**Comment by kmlrohin1** [comment]
I used  windows 11 and gpu of 1050ti
openvino version is 2023.0.0 
pytorch is 1.12 with cu118
python 3.10

**Comment by glenn-jocher** [comment]
Hi @kmlrohin1,

Thank you for sharing your environment details. To help us better assist you, could you please provide some additional details such as a minimal code snippet or command example that you are running to export the model to OpenVINO and the complete error log that you are receiving? With this additional information, we'll be able to provide more targeted solutions to help resolve your issue.

Looking forward to your response.
