### ISSUE TITLE
VOC.yaml

### ISSUE THREAD

**Issue by ZCzzzzzz** [ultralytics/yolov5#11649]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I am now encountering a problem, the size of each picture in my dataset is too large, the training time is too long, and I found that the accuracy and recall rate of epoch is less than 10 can reach more than 90%, the speed of fitting is too fast, I want to ask is there any way to automatically modify the label file while modifying the image size of the dataset, without the need to label the modified picture again?

**Comment by glenn-jocher** [comment]
@ZCzzzzzz hello,

One way to modify the label file while changing the image size of the dataset is by using a tool like LabelImg. With LabelImg, you can modify the image size and then save the annotations in YOLO format. Another option is to use a script to modify the annotations automatically based on the new image size.

Regarding the training time, you can try reducing the image size to further reduce the training time while maintaining a good accuracy and recall rate.

Hope this helps! Let us know if you have any further questions.

Best, 
Glenn Jocher, Ultralytics team

**Comment by ZCzzzzzz** [comment]
Hello, are you saying that I need to reproduce the annotation of the new image using labelimg?

**Comment by glenn-jocher** [comment]
@ZCzzzzzz hi there,

If you are planning on modifying the image size of your dataset and you want to preserve the labels of the objects in the images, you will need to update the annotations of your dataset to reflect the new image size. 

One way to do this is to use a tool like LabelImg to manually modify the annotations for each image in your dataset. Another option is to use a script to automatically update the annotations based on the new image size.

I hope that helps! If you have any further questions, please don't hesitate to ask.

Thanks, 
Glenn Jocher, Ultralytics team.
