### ISSUE TITLE
Export only single output

### ISSUE THREAD

**Issue by EnariSaarBolt** [ultralytics/yolov5#11644]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I was adviced to export yolov5 model to a single output. How would one do it? I was given this piece of code as an answer but it did not work with current yolov5. Any advice would be welcome.

```def forward(self, x):
        z = []  # inference output
        for i in range(self.nl):
            x[i] = self.m[i](x[i])  # conv
            bs, _, ny, nx = x[i].shape  # x(bs,255,20,20) to x(bs,3,20,20,85)
            x[i] = x[i].view(bs, self.na, self.no, ny, nx).permute(0, 1, 3, 4, 2).contiguous()

            if not self.training:  # inference
                if self.onnx_dynamic or self.grid[i].shape[2:4] != x[i].shape[2:4]:
                    self.grid[i], self.anchor_grid[i] = self._make_grid(nx, ny, i)

                y = x[i].sigmoid()
                if self.inplace:
                    y[..., 0:2] = (y[..., 0:2] * 2 - 0.5 + self.grid[i]) * self.stride[i]  # xy
                    y[..., 2:4] = (y[..., 2:4] * 2) ** 2 * self.anchor_grid[i]  # wh
                else:  # for YOLOv5 on AWS Inferentia https://github.com/ultralytics/yolov5/pull/2953
                    xy = (y[..., 0:2] * 2 - 0.5 + self.grid[i]) * self.stride[i]  # xy
                    wh = (y[..., 2:4] * 2) ** 2 * self.anchor_grid[i]  # wh
                    y = torch.cat((xy, wh, y[..., 4:]), -1)
                z.append(y.view(bs, -1, self.no))

        # return x if self.training else x  # 3个输出
        return x if self.training else (torch.cat(z, 1))     # 1个输出
        # return x if self.training else (torch.cat(z, 1), x)```

**Comment by glenn-jocher** [comment]
@EnariSaarBolt hi there! Thanks for your question on exporting YOLOv5 model to a single output. 

The code snippet you provided for the `forward` function should work to produce a single output. You just need to replace the `return x if self.training else (torch.cat(z, 1), x)` statement with `return x if self.training else (torch.cat(z, 1))`. This will concatenate all the outputs into a single tensor.

Let me know if you have any other questions or if you encounter any issues with this. Have a great day!

**Comment by EnariSaarBolt** [comment]
@glenn-jocher Hey, thank you for your answer. Will this work for any format output as well for example onnx? I'm asking because the following onnx_dynamic, is not present in the code anymore. is the just dynamic boolean offering the same functionality?

**Comment by glenn-jocher** [comment]
@EnariSaarBolt hello! I'm glad to help. The changes made to the `forward` function should work for any output format, including ONNX. The `onnx_dynamic` parameter is specifically for enabling dynamic input shapes for ONNX export, but it is no longer necessary in the latest version because dynamic input shapes are now supported by default. Instead, you can simply use the `export` function provided in the `models` module to export your model to ONNX. Please let me know if you have any further questions or concerns.
