### ISSUE TITLE
Huawei Ascend GPU Support

### ISSUE THREAD

**Issue by tfidmmatthew** [ultralytics/yolov5#11657]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Does yolov5 support inference or training on Huawei Ascend GPU?

**Comment by glenn-jocher** [comment]
@tfidmmatthew hello! At the moment, YOLOv5 does not support inference or training on Huawei Ascend GPU. However, we are constantly updating and improving our software, so it's possible that Ascend support will be added in the future. Thank you for your interest in YOLOv5!

**Comment by tfidmmatthew** [comment]
Thanks for your comment, well noted

**Comment by glenn-jocher** [comment]
@tfidmmatthew thank you for your comment! If you have any further questions or issues related to YOLOv5, please don't hesitate to reach out. We're always here to help!
