### ISSUE TITLE
YOLOv5 conf thresh and iou thresh inquiry

### ISSUE THREAD

**Issue by 25benjaminli** [ultralytics/yolov5#11652]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

In val.py, the following lines are included:
```
conf_thres=0.001,  # confidence threshold
iou_thres=0.6,  # NMS IoU threshold
```

Why is conf_thresh 0.001? This seems like it would heavily skew the performance of the model, if I am understanding it properly. Please explain this.

**Comment by glenn-jocher** [comment]
@25benjaminli hello,

Thank you for your question. The `conf_thres` value of 0.001 in `val.py` is used to retain all detections with a confidence value higher than or equal to 0.001. You are correct that this threshold may seem low, but it can help to keep more detections and avoid discarding potentially useful detections. 

Please note that this value can be adjusted based on the requirements of your specific use case, and we recommend experimenting with different values to find the optimal performance for your needs.

Thank you.

**Comment by 25benjaminli** [comment]
@glenn-jocher thank you for your response. I have two follow-up questions:

1. in a practical setting, wouldn't a confidence threshold as low as 0.001 create situations such as below, where there are boxes everywhere? Would it actually be reflective of the performance of the model? 
![Screenshot 2023-06-03 at 5 34 38 PM](https://github.com/ultralytics/yolov5/assets/76795078/7818e215-f0e5-4a87-b0ec-bd15cc57caba)


2. How do iou thresh and conf thresh work together to produce an output? As per my understanding, iou thresh determines when to classify a detection as a true/false positive, whereas conf thresh determines what class a detection actually is. Therefore, if you set conf thresh to something arbitrarily low such as 0.001, wouldn't there be a risk for lots of false positives? Would this negatively impact mAP?

**Comment by glenn-jocher** [comment]
Hello @25benjaminli,

Thank you for your follow-up questions.

1. In a practical setting, it is true that a low confidence threshold may create a large number of predictions, but it can also increase the chances of detecting small or hard-to-detect objects that may be important for certain applications. The decision to use a particular value for `conf_thres` depends on the specific requirements of the application. You can experiment with different values to find the optimal performance for your specific use case. 

However, it's crucial to keep in mind that using a low value of `conf_thres` may result in a high number of false positives and affect mAP negatively.

2. The output of an object detection model may contain overlapping bounding boxes that correspond to the same object. The Non-Maximum Suppression (NMS) algorithm is used to remove these overlapping boxes and keep only the most confident detection. The `conf_thres` is used to remove low confidence detections, and the `iou_thres` is used to filter out overlapping detections. Only detections with an IoU score greater than or equal to the `iou_thres` and a confidence score greater than or equal to the `conf_thres` are considered as `true positives`. Any other detection is considered a `false positive`. 

To answer your question, using a low `conf_thres` could increase the number of false positives if there is a high rate of detections with low confidence scores. If the `conf_thres` is too low, it could result in a high number of false positives and negatively impact the mAP.

Please let me know if you have any further questions.

Best regards.

**Comment by 25benjaminli** [comment]
@glenn-jocher thank you for your comprehensive response. I see why you would want to put the confidence threshold very low in some cases, such as when catching positives is extremely important (more important than having false positives).

**Comment by glenn-jocher** [comment]
@25benjaminli Thank you for your feedback. We believe that it is essential to provide the flexibility to adjust the confidence threshold based on the specific use case as there is no one-size-fits-all solution. We are happy to hear that our explanation was helpful for you to understand the rationale behind the threshold values in `val.py`. If you have any other inquiries or suggestions, please don't hesitate to post them on the YOLOv5 GitHub repo. 

Thank you for your interest in YOLOv5.

Regards.
