### ISSUE TITLE
Single class validation on testsets with combined model

### ISSUE THREAD

**Issue by raphael-97** [ultralytics/yolov5#11658]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I saw that you can detect individual classes in detect.py, but not in val.py. The --classes argument is missing in val.py

Example:
I have two test datasets. One is for dogs and the other is for cats. Now I have a yolov5 model that was trained on a combined cat AND dog dataset. 0 = cat, 1 = dog.
Now I want to validate once on the cat test data set and then validate on the dog test data set.
The reason is that I want to have a fair result on the respective test data sets and do not like to combine them.
How exactly do I do this?
The test data sets for dogs and cats currently have the class number 0 in the labels. Do i need to relabel it?

**Comment by glenn-jocher** [comment]
@Glatzenhopper hello! 

As you might have noticed, the `val.py` script doesn't have an option to specify the classes to validate on - it will validate on all classes. 

However, you can modify the script to validate on a single class by filtering the detections using the desired class ID. For instance, you can parse the predictions per image as follows:

```
pred = torch.from_numpy(prediction)
pred = non_max_suppression(pred, conf_thres=conf_thres, iou_thres=iou_thres, agnostic=agnostic_nms)

# filter detections of a single class
class_idx = 0  # cat
pred = [det[det[:, -1] == class_idx] for det in pred]

```

By setting the `class_idx` variable to 0, for instance, only detections with label "0" (`cat`) will be returned. 

Regarding the test data labels, it depends on how you prepare your data. If your class labels are "0" and "1", and you want to evaluate the model on cat images, you should relabel the cat images to have label "0" before validation. Similarly, for the dog images, you should relabel them to have label "1". 

I hope this helps! Let me know if you have any further questions or if there's anything else I can help you with.

**Comment by BodhiHami** [comment]
@glenn-jocher 

Hello i have the same problem. Where should i add these lines of code? 
I don't see the variable "prediction" and "agnostic_nms" in the val.py

**Comment by glenn-jocher** [comment]
@BodhiHami hello,

To filter the detections for a single class in the `val.py` script, you can add the lines of code I provided after the line where the predictions are obtained using `non_max_suppression()`. In the current implementation of `val.py`, the variable `prediction` is not explicitly defined, but it is the result of the `model(imgs)` call. You can find this line in the script after loading the images and before processing the predictions.

To use the `agnostic_nms` argument, you need to update the `non_max_suppression` function call. Set `agnostic_nms=True` to ignore the class information during the non-maximum suppression step, which will allow you to filter the detections based only on the class index.

Hope this clarifies your doubt! Let me know if you have any further questions.
