### ISSUE TITLE
How do I retrieve individual f1 scores from yolov5?

### ISSUE THREAD

**Issue by 25benjaminli** [ultralytics/yolov5#11662]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

The title is self explanatory. I saw on an old thread for yolov3 that this was supported, but I haven't been able to find anything similar for yolov5. Thanks!

**Comment by glenn-jocher** [comment]
@25benjaminli hi there,

To retrieve individual f1 scores from YOLOv5, you can use the `precision_recall()`, `precision()` and `recall()` functions in the `metrics.py` script. These functions return a dictionary of values where each key corresponds to an individual class. Additionally, you can also find the overall average f1 score under the key "mean".

Hope this helps! Let us know if you have any further questions.

Best regards.

**Comment by 25benjaminli** [comment]
@glenn-jocher thank you for your response! Unfortunately, I was not able to find these functions, could you point me to the line(s) where you can find them in `metrics.py`? Thanks, and sorry for the hassle!

**Comment by glenn-jocher** [comment]
Hi @25benjaminli,

I'm sorry for the confusion. The functions I mentioned for retrieving individual f1 scores can actually be found in the `utils/metrics.py` script. Specifically, `precision_recall()`, `precision()`, and `recall()` can be found on lines 45, 63, and 77 respectively.

Let me know if you need any further help.

Best, 
Glenn
