### ISSUE TITLE
how do i increase fps with yolov5

### ISSUE THREAD

**Issue by hairlinebrockeb** [ultralytics/yolov5#11668]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

how do i increase the fps with yolov5
when `results = self.model(frame)` runs my fps drops to 25-30 with 
`torch.hub.load('ultralytics/yolov5', 'yolov5s',  force_reload = True) `

fps is very low even with **cuda acceleration enabled**

### Additional

gtx 1650

**Comment by hairlinebrockeb** [comment]
thats not what i need

**Comment by lucastack** [comment]
Hi! have you tried exporting your model to an inference optimized format? 

I'd recommend to use tensorrt

```
model = torch.hub.load('ultralytics/yolov5', path='yolov5s.engine') 
```




and btw, how are you measuring that fps?

**Comment by glenn-jocher** [comment]
@hairlinebrockeb hello! Exporting your model to an inference optimized format can greatly improve its performance. Using TensorRT is a great option for this, and you can load it once it is exported as follows:

```model = torch.hub.load('ultralytics/yolov5', path='yolov5s.engine')```

Regarding the fps measurement, could you please provide more information on how you are measuring it? Keep in mind that the performance can vary depending on several factors such as the hardware used, the size of the input image, and the number of objects detected in the image.

Let me know if you have any further questions or concerns.
