### ISSUE TITLE
Explainations on images in runs/exp0

### ISSUE THREAD

**Issue by vantienpham** [ultralytics/yolov5#1166]
## ❔Question
Dear all,
After training yolov5x on custom dataset, I've got many histograms in the folder runs/exp0, what's the detail meaning of these images?
How should I understand about these pictures? For example: Does the labels.png show the density of the ground-truth annotations? What abount the labels_correlgram.png?
Here I attach these 2 images:
![labels](https://user-images.githubusercontent.com/25927039/96401527-ce45a180-11fd-11eb-9446-1321cb756cd0.png)
![labels_correlogram](https://user-images.githubusercontent.com/25927039/96401530-cf76ce80-11fd-11eb-811a-d34a6f105311.png)
Many thanks!

**Comment by glenn-jocher** [comment]
@pvtien96 yes, these are correlograms and histograms of your training labels. Axes are labelled correctly. For details see plot_labels()
https://github.com/ultralytics/yolov5/blob/9291daa6f7f24ff297aa3527d62f7bc2d839a3a2/train.py#L186

https://github.com/ultralytics/yolov5/blob/9291daa6f7f24ff297aa3527d62f7bc2d839a3a2/utils/general.py#L1182-L1212

**Comment by vantienpham** [comment]
So can you please exlain the corelograms and histograms in my case? @glenn-jocher 
My custom dataset is an egocentric hand dataset. A sample is like in this image:
![0068](https://user-images.githubusercontent.com/25927039/96687304-e823e780-13a9-11eb-950d-8898e586fd87.png)
So if i'm not wrong, the correlograms above tells that most of my training labels has a shape of a hand, right?
What about the histogram?
Any deeper analysis is appreciated.
Thanks,

**Comment by glenn-jocher** [comment]
@pvtien96 the axes are clearly marked on the correlograms and labels plots, the analysis of your data is up to you.
