### ISSUE TITLE
About the speed of the test

### ISSUE THREAD

**Issue by GJTNB** [ultralytics/yolov5#1167]
## ❔Question
My configuration is Gtx1660TI and 6G, but when I test with Yolov5S, the detection speed can reach 30FPS, but the test speed with Yolov5X is only 3FPS. May I ask if my configuration is not good, or there are other problems。
My PyTorch version is 1.6 and CUDA version is 10.1

**Comment by Aktcob** [comment]
GPU Speed measures end-to-end time per image averaged over 5000 COCO val2017 images using a V100 GPU with batch size 32.

So, what's ur setting of batch size?
