### ISSUE TITLE
my model that trained with custom data works so bad with torch.hub.load

### ISSUE THREAD

**Issue by samettoprak** [ultralytics/yolov5#11674]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I trained my custom data  with google colab. 

Colab link: [https://colab.research.google.com/github/roboflow-ai/notebooks/blob/main/notebooks/train-yolov5-object-detection-on-custom-data.ipynb](url)

My custom data is here: [https://universe.roboflow.com/trakya-university-iy7yk/signlanguagedataset](url)
So far there is no problem. I checked my model to make sure it works fine with that code:

`import os
os.system("python yolov5/detect.py --weights yolov5/runs/train/exp1/weights/best.pt --img 416 --conf 0.4 --source 0")`

![image](https://github.com/ultralytics/yolov5/assets/81929563/3ea91893-9380-43b4-947b-d50114665ca4)

And it works fine and predicts %95 right.

But i can't reach realtime results with that code. So i tried to load my trained model with torch.

```
import torch
import numpy as np
import cv2

model = torch.hub.load('ultralytics/yolov5', 'custom', path='yolov5/runs/train/yolo5/weights/best.pt')
cap = cv2.VideoCapture(0)
while cap.isOpened():
    ret, frame = cap.read()
    
    # Make detections 
    results = model(frame)
    
    cv2.imshow('YOLO', np.squeeze(results.render()))
    
    if cv2.waitKey(10) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()
```

But that predictions was terrible. It couldn't even find my hand. %100 false. 

That code works fine if i try to use your model so there is nothing wrong about this code.

`model = torch.hub.load('ultralytics/yolov5','yolov5s')`

What i wanna ask you guys is that what can i do to make my model works fine with torch or something else to get the results for realtime frames ? Or should i train it one more time with colab ? 
There is so much colab links and i don't know which one i should use.

Note - I trained my model with this code;

`!python train.py --img 416 --batch 16 --epochs 100 --data {"/content/yolov5/SignLanguageDataSet-1"}/data.yaml --cfg ./models/custom_yolov5s.yaml --weights '' --name yolov5s_results  --cache`

i'm pretty sure i saw somewhere u don't recommend this but i can't find it. Maybe it could be because the way i trained ?

-thanks

**Comment by glenn-jocher** [comment]
@samettoprak hi there! Thanks for reaching out to us for help. From your description, it sounds like your custom YOLOv5 model trained with your SignLanguageDataset-1 doesn't perform well with torch.hub.load, but it works fine when using detect.py. There could be several reasons for this discrepancy. 

Firstly, when using detect.py to inference your custom model, you might have set the same configuration as the one you used during training. But in pytorch hub, if you load a custom model along with a custom architecture, make sure to pass `nc` (number of classes) argument similar to what you passed in your data.yaml file during training.

For instance, you can try the following code where **5** is the number of classes you have in your Sign Language dataset:

```
model = torch.hub.load('ultralytics/yolov5', 'custom', path='yolov5/runs/train/yolo5/weights/best.pt', source='local', force_reload=True,nc=5)
```

Moreover, make sure that you're testing the model on quality images with no distortions during inference to avoid degraded results. 

Regarding the warning on training your model with colab, we don't have any issues with training with colab, but we don't recommend using the code found elsewhere as it might not be the latest version. Instead, we suggest following our official tutorials in this repo or from our official [documentation](https://docs.ultralytics.com/) for reference.

Let me know if this helps.
