### ISSUE TITLE
RuntimeError: Cannot find callable yolov5s-seg in hubconf

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#11679]
Hi
I load a yolov5 (bbox) weights and it is working.
but I load segmentation weight (yolov5s-seg), it is no working.

WHY???

https://github.com/ultralytics/yolov5/assets/110151053/5c79ac52-5ca2-40d4-8c49-4bba785036a3

**Comment by glenn-jocher** [comment]
@stphtan94117 hello,

Thank you for using the Ultralytics YOLOv5 repo. We apologize for the inconvenience you are experiencing while loading the segmentation weight (yolov5s-seg). We recommend that you ensure that the weight file is located in the correct path and that you have downloaded the latest version of the Ultralytics YOLOv5 repo. 

If you still encounter issues after checking the above, please provide us with additional information so that we can assist you better. 

Thank you very much.

**Comment by ghost** [comment]
@glenn-jocher 
I have confirmed that I have downloaded the latest version, and the execution result is the same as shown in the video. When using the torch.hub.load segmentation weights, it simply doesn't work. If it's regular BBOX weights, there are no problem.

I have also tried it on another Windows computer, and the same situation occurred. Whenever I encounter the segmentation weights, it simply cannot be executed.

**Comment by ghost** [comment]
![image](https://github.com/ultralytics/yolov5/assets/110151053/f6489f34-add2-467d-afd0-6b2307482be6)
I believe there may be an issue with the torch hub because I encountered the same problem when using your YOLOv5 segmentation tutorial Colab notebook. The error message "Cannot find callable yolov5s-seg in hubconf" appeared. 

Could you please fix this problem as soon as possible?

**Comment by glenn-jocher** [comment]
@stphtan94117 hello,

Thank you for using the Ultralytics YOLOv5 repo. We apologize for the inconvenience you are experiencing while using the torch hub to load segmentation weights. 

We are aware of this issue and are currently investigating it. We highly appreciate your feedback and we will do our best to address and fix this issue as soon as possible.

In the meantime, you can still use YOLOv5 segmentation by cloning our repository and loading the weights locally. We apologize for any inconvenience this may cause and we appreciate your patience and understanding.

Thank you very much.

**Comment by ghost** [comment]
May I ask if this issue has been resolved?
I know that it is possible to successfully use yolov5 segmentation by loading the weights locally,
but I want to use the torch hub to load segmentation weights.
thanks.

**Comment by ghost** [comment]
this issue have not be solved, can you fix it?

**Comment by glenn-jocher** [comment]
@stphtan94117 i apologize for the inconvenience you've been experiencing. We are aware of the issue with loading segmentation weights using the torch hub and our team is actively investigating it. We appreciate your patience and understanding as we work towards finding a solution. Thank you for bringing this to our attention.

**Comment by ghost** [comment]
@glenn-jocher 
Two weeks have passed, has this issue been resolved?
i tested and still failed

**Comment by glenn-jocher** [comment]
@stphtan94117 hello,

Thank you for your patience. We apologize for the delay in resolving this issue. Our team is actively working on finding a solution for the problem with loading segmentation weights using the torch hub. We understand your frustration and we appreciate your continued testing and feedback.

Please be assured that we are committed to resolving this issue as soon as possible. We will update the repository and notify you once a fix is available.

Thank you for your understanding and support.
