### ISSUE TITLE
Image reading problem of utils/ dataloader.py in image classification task

### ISSUE THREAD

**Issue by deepConnectionism** [ultralytics/yolov5#11676]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

         self.torch_transforms = classify_transforms(imgsz)
        # During training augment = True
        self.album_transforms = classify_albumentations(augment, imgsz) if augment else None 

Line 1191 of utils/ dataloader.py, data is read in BGR format, why is it converted to RGB during training, but not during validation?

       else:  # read image
            im = cv2.imread(f)  # BGR
        if self.album_transforms:
            sample = self.album_transforms(image=cv2.cvtColor(im, cv2.COLOR_BGR2RGB))["image"]
        else:
            sample = self.torch_transforms(im)

### Environment

YOLOv5-7.0

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by deepConnectionism** [comment]
Nice! I solved the problem and it turned out to be class ToTensor: BGR->RGB completed.

**Comment by glenn-jocher** [comment]
@deepConnectionism glad to hear that you resolved the issue with the `ToTensor` class converting BGR to RGB. If you have any further questions or concerns, please don't hesitate to ask!
