### ISSUE TITLE
Bounding box

### ISSUE THREAD

**Issue by Real-J** [ultralytics/yolov5#11675]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How can you extract the relevant coordinates from a annotated yolo v5 img, to be frank I want to generate .txt that yolo v5 can read with a img having bounding box

**Comment by glenn-jocher** [comment]
@Real-J hello,

To extract the relevant bounding box coordinates from an annotated YOLOv5 image, you can parse the annotation file and retrieve the information. The annotation file should contain the class ID and bounding box coordinates for each object in the image in the following format:
```
<class_id> <x_center> <y_center> <width> <height>
```

Once you have extracted the bounding box coordinates, you can use them to create a `.txt` file that YOLOv5 can read. The `.txt` file should have the same name as the corresponding image file and contain one row for each object in the image, in the following format:
```
<class_id> <x_center> <y_center> <width> <height>
```

I hope this helps! Let me know if you have any additional questions.
