### ISSUE TITLE
input size not equal to max model size

### ISSUE THREAD

**Issue by NatanelBirarov** [ultralytics/yolov5#11673]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I exported my model to TensorRT to use on a Jetson NX, my input size is (1920, 480, 3), and when I run the model I get the error  
```input size torch.Size([1, 3, 160, 640]) not equal to max model size (1, 3, 1920, 480)```. 
I tried the solution suggested in [this issue](https://github.com/ultralytics/yolov5/issues/11541#issuecomment-1550661548) with different sizes, also tried resizing the input image before running it through the model, but every time it says
 ```input size torch.Size([1, 3, 160, 640])```, regardless of the size I change it to. only the max model size changes.

my code:
```
model = torch.hub.load('ultralytics/yolov5', 'custom', path='final.engine', force_reload=False)
image = np.resize(image, (1920, 480, 3))  # tried a few different sizes
results = self.model(Image.fromarray(image, 'RGB')).xyxy[0].cpu().numpy()
```
I don't understand why the tensor stays the same, is it being resized again during the inference?

**Comment by glenn-jocher** [comment]
@NatanelBirarov hello! It looks like the TensorRT engine has a fixed input size of 160x640, which is why you are unable to input your desired image size of 1920x480. Even if you resize the input image, the engine is still expecting an input tensor of size 160x640. 

One solution would be to resize your input image to 160x640 before running it through the model. Another option would be to generate a new TensorRT engine that is compatible with the input size of your choice using the `yolov5trt.py` script provided in the official YOLOv5 repository. 

Hope this helps! Let us know if you have any other questions.

**Comment by NatanelBirarov** [comment]
Hello, thank you for the reply but I still don't really follow. Why does the model expects an input of 160x480?
I thought that the error means that the engine expects an input of 1920x480, because that is what I put in ```--imgsz``` when I ran
```python3 export.py --device 0 --weights final.pt --include engine --imgz 1920 480```. Isn't that what that parameter is for?
Also, I can't seem to find the file ```yolov5trt.py``` in the repository, do you mind sharing a link to it? 
Thank you again for the help.

**Comment by glenn-jocher** [comment]
Hello @NatanelBirarov! I apologize for the confusion, let me clarify. When you export the model to an engine using the `export.py` script, the `--imgsz` parameter specifies the input size of the engine, which in your case is 1920x480. However, after the engine is generated and loaded during inference, the input size is enforced by the engine, not the parameters used during generation. 

In other words, while the engine generation process allows you to specify the desired input size of the engine, the engine itself is fixed to output predictions on tensors of a specific shape (such as the expected 160x640 in your case), regardless of the input shape of the original image. 

Regarding the `yolov5trt.py` script, my apologies for the mistake - it is not provided in the official YOLOv5 repository. However, you could use the TensorRT API directly to create a new engine with the desired input shape, or use an external script like [Jetson-Inference](https://github.com/dusty-nv/jetson-inference) to generate a TensorRT engine for your model with a custom input shape.

I hope this clears things up! Let me know if you have any further questions.
