### ISSUE TITLE
 --half and --dynamic  can not both， why?

### ISSUE THREAD

**Issue by codedoves** [ultralytics/yolov5#11683]
Hello, I see this Assert half not compatible with --dynamic, i.e. use either --half or --dynamic but not both in the latest code. Why do you add this processing?
How can I convert the onnx model  fp16 and dynamic?
Thank you！

**Comment by codedoves** [comment]
I want to  convert the onnx model fp16 and dynamic both

**Comment by glenn-jocher** [comment]
Hello @codedoves, thank you for your question. Based on your request, you want to convert the ONNX model to both FP16 and Dynamic. Unfortunately, these options are not compatible with each other, so you can only use one at a time. 

If you want to take advantage of mixed precision, you can use the `--half` flag during inference to run the model in FP16 precision. Alternatively, if you want to optimize the model and make it dynamic in size, you can use the `--dynamic` flag when exporting the model to ONNX.

Please let me know if you have any other questions or if there's anything else I can help you with.
