### ISSUE TITLE
Hello, I want to change the blue color of labels pictures in the generated exp folder, how can I change it

### ISSUE THREAD

**Issue by yynnaa777** [ultralytics/yolov5#11681]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I want to change the blue color of labels pictures in the generated exp folder, how can I change it

1. [![Uploading](url) [image.png…]()](url)
![Snipaste_2023-06-08_22-42-03](https://github.com/ultralytics/yolov5/assets/100113554/3797d808-3e0a-428f-bedb-838fa1db6da6)

**Comment by glenn-jocher** [comment]
@yynnaa777 hello! I'm happy to help you with your question. It seems that you want to change the color of labels pictures in the generated exp folder. You can do this by modifying the `color` variable in the YAML file of your project. The `color` variable is a list of hue, saturation, and value (HSV) values that represent the color of bounding boxes and labels. You can change the values of this variable to achieve the desired color. 

Please be aware that modifying the `color` variable may affect the accuracy of your model, as some colors may be harder to detect than others. Let me know if you have any further questions, and I'll be happy to assist you!

**Comment by yynnaa777** [comment]
Hello, I want to change the blue picture named labels_correlog. I have tried the method you said, but it doesn't seem to change, or I didn't understand it clearly. I hope to get your answer again 

>
![Uploading Snipaste_2023-06-09_13-25-21.png…]()

**Comment by yynnaa777** [comment]
![Snipaste_2023-06-09_13-25-21](https://github.com/ultralytics/yolov5/assets/100113554/52cbb007-e3a7-4731-9bdc-c7309cdd8647)

**Comment by glenn-jocher** [comment]
Hello @yynnaa777, thank you for reaching out. To change the blue color of the label pictures, you can modify the `correlog` file in the following directory: `yolov5/data/correlations/labels_correlog.yaml`. Within that file, you can adjust the `hue`, `saturation`, and `value` values to change the color of the labels. Below is a sample configuration for a red color:

```
background: [0.0, 0.0, 0.0]
colors: 
  - [0.0, 1.0, 1.0]
lines: [0.9, 0.9]
rings: [0.75, 0.75]
hue: 0.0
saturation: 1.0
value: 1.0
```

Please note that modifying these values may affect the accuracy of your model, as some colors may be more or less distinguishable from the background than others. 

If you have any further questions or concerns, please feel free to ask. We are always happy to help. 

Best regards, 
Glenn Jocher
