### ISSUE TITLE
why padding the dataloader in test.py

### ISSUE THREAD

**Issue by yxNONG** [ultralytics/yolov5#1168]
## ❔Question
```
dataloader = create_dataloader(path, imgsz, batch_size, model.stride.max(), opt,
                                       hyp=None, augment=False, cache=False, pad=0.5, rect=True)[0]
```
the pad = 0.5 in test.py while pad =0 in train.py

**Comment by glenn-jocher** [comment]
@yxNONG edges suffer reduced recall due to the hundred or so zero-pad convolution operations in all deep CNNs. Adding a pad during inference alleviates this problem.

It is omitted during training for speed.

**Comment by www7890** [comment]
> @yxNONG edges suffer reduced recall due to the hundred or so zero-pad convolution operations in all deep CNNs. Adding a pad during inference alleviates this problem.
> 
> It is omitted during training for speed.

HI Glenn, I was wondering why you only do vertical padding for testing, but not both width and height?

**Comment by glenn-jocher** [comment]
@www7890 the pad argument to the dataloader adds a pad around all 4 edges.

**Comment by www7890** [comment]
> @www7890 the pad argument to the dataloader adds a pad around all 4 edges.

Then I must misunderstand something. 
Thanks!
