### ISSUE TITLE
Running train.py will not generate p_ Curve, r_ The four curves

### ISSUE THREAD

**Issue by DA-liu-a** [ultralytics/yolov5#11686]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

![image](https://github.com/ultralytics/yolov5/assets/136170613/8a3d4f6d-f593-40d3-85bc-f047a8da829b)
Running train.py will not generate p_ Curve, r_ The four curves

**Comment by DA-liu-a** [comment]
![image](https://github.com/ultralytics/yolov5/assets/136170613/df9fba5d-6b8f-4576-b07c-83e1c2b721ba)

**Comment by DA-liu-a** [comment]
The version is correct, but it will not generate a curve graph

**Comment by glenn-jocher** [comment]
@DA-liu-a hello! I'm sorry to hear that you're having trouble generating the p-curve and r-curve. Can you please provide more details on the issue you are facing? It would be very helpful if you can share your code snippet, or a screenshot of the error logs you received. 

Also, make sure that you have properly selected the parameters `--save-ckp` and `--save-dir` while running the `train.py` script, which are required for generating the curves.

I hope this helps! Let me know if you have any further questions or concerns.

**Comment by DA-liu-a** [comment]
The code is the latest, and the same dataset can be trained with a curve graph in the old version of YOLOv5, but running in the new YOLOv5 master will not generate a curve `graph。
This is new：
`D:\anaconda\envs\yolo\python.exe D:\yolov5-master\train.py 
github: skipping check (not a git repository), for updates see https://github.com/ultralytics/yolov5
train: weights=weights\yolov5s.pt, cfg=models/yolov5m_face.yaml, data=data\face.yaml, hyp=data\hyps\hyp.scratch.yaml, epochs=5, batch_size=4, imgsz=640, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, noplots=False, evolve=None, bucket=, cache=None, image_weights=False, device=, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=8, project=runs\train, name=exp, exist_ok=False, quad=False, cos_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, seed=0, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest
YOLOv5  2023-5-14 Python-3.8.16 torch-1.7.1+cu110 CUDA:0 (GeForce GTX 1650, 4096MiB)

hyperparameters: lr0=0.01, lrf=0.2, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=0.0, mixup=0.0
ClearML: run 'pip install clearml' to automatically track, visualize and remotely train YOLOv5  in ClearML
Comet: run 'pip install comet_ml' to automatically track and visualize YOLOv5  runs in Comet
TensorBoard: Start with 'tensorboard --logdir runs\train', view at http://localhost:6006/

                 from  n    params  module                                  arguments                     
  0                -1  1      5280  models.common.Focus                     [3, 48, 3]                    
  1                -1  1     41664  models.common.Conv                      [48, 96, 3, 2]                
  2                -1  2     65280  models.common.C3                        [96, 96, 2]                   
  3                -1  1    166272  models.common.Conv                      [96, 192, 3, 2]               
  4                -1  6    629760  models.common.C3                        [192, 192, 6]                 
  5                -1  1    664320  models.common.Conv                      [192, 384, 3, 2]              
  6                -1  6   2512896  models.common.C3                        [384, 384, 6]                 
  7                -1  1   2655744  models.common.Conv                      [384, 768, 3, 2]              
  8                -1  1   1476864  models.common.SPP                       [768, 768, [5, 9, 13]]        
  9                -1  2   4134912  models.common.C3                        [768, 768, 2, False]          
 10                -1  1    295680  models.common.Conv                      [768, 384, 1, 1]              
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 12           [-1, 6]  1         0  models.common.Concat                    [1]                           
 13                -1  2   1182720  models.common.C3                        [768, 384, 2, False]          
 14                -1  1     74112  models.common.Conv                      [384, 192, 1, 1]              
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 16           [-1, 4]  1         0  models.common.Concat                    [1]                           
 17                -1  2    296448  models.common.C3                        [384, 192, 2, False]          
 18                -1  1    332160  models.common.Conv                      [192, 192, 3, 2]              
 19          [-1, 14]  1         0  models.common.Concat                    [1]                           
 20                -1  2   1035264  models.common.C3                        [384, 384, 2, False]          
 21                -1  1   1327872  models.common.Conv                      [384, 384, 3, 2]              
 22          [-1, 10]  1         0  models.common.Concat                    [1]                           
 23                -1  2   4134912  models.common.C3                        [768, 768, 2, False]          
 24      [17, 20, 23]  1     24246  models.yolo.Detect                      [1, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [192, 384, 768]]
YOLOv5m_face summary: 309 layers, 21056406 parameters, 21056406 gradients

Transferred 59/505 items from weights\yolov5s.pt
AMP: checks passed 
optimizer: SGD(lr=0.01) with parameter groups 83 weight(decay=0.0), 86 weight(decay=0.0005), 86 bias
train: Scanning D:\yolov5-master\VOCdevkit\labels\train.cache... 59 images, 0 backgrounds, 0 corrupt: 100%|██████████| 59/59 [00:00<?, ?it/s]
val: Scanning D:\yolov5-master\VOCdevkit\labels\val.cache... 12 images, 0 backgrounds, 0 corrupt: 100%|██████████| 12/12 [00:00<?, ?it/s]

AutoAnchor: 5.13 anchors/target, 1.000 Best Possible Recall (BPR). Current anchors are a good fit to dataset 
Plotting labels to runs\train\exp22\labels.jpg... 
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs\train\exp22
Starting training for 5 epochs...

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
        0/4      1.79G        nan        nan          0          6        640: 100%|██████████| 15/15 [00:28<00:00,  1.87s/it]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 2/2 [00:01<00:00,  1.37it/s]
                   all         12         20          0          0          0          0

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
        1/4       2.1G        nan        nan          0          7        640: 100%|██████████| 15/15 [00:25<00:00,  1.68s/it]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 2/2 [00:01<00:00,  1.38it/s]
                   all         12         20          0          0          0          0

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
        2/4       2.1G        nan        nan          0          4        640: 100%|██████████| 15/15 [00:25<00:00,  1.67s/it]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 2/2 [00:01<00:00,  1.37it/s]
                   all         12         20          0          0          0          0

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
        3/4       2.1G        nan        nan          0          6        640: 100%|██████████| 15/15 [00:25<00:00,  1.67s/it]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 2/2 [00:01<00:00,  1.38it/s]
                   all         12         20          0          0          0          0

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
        4/4       2.1G        nan        nan          0          4        640: 100%|██████████| 15/15 [00:25<00:00,  1.67s/it]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 2/2 [00:01<00:00,  1.39it/s]
                   all         12         20          0          0          0          0

5 epochs completed in 0.039 hours.
Optimizer stripped from runs\train\exp22\weights\last.pt, 42.5MB
Optimizer stripped from runs\train\exp22\weights\best.pt, 42.5MB

Validating runs\train\exp22\weights\best.pt...
Fusing layers... 
YOLOv5m_face summary: 226 layers, 21037638 parameters, 0 gradients
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 2/2 [00:01<00:00,  1.34it/s]
                   all         12         20          0          0          0          0
Results saved to runs\train\exp22

Process finished with exit code 0
`
![image](https://github.com/ultralytics/yolov5/assets/136170613/260fc380-8b6f-4bdb-aa06-6722ae61d1b8)

This is old：
`D:\anaconda\envs\yolo\python.exe D:\faceyuanma\FaceDetect5\train.py 
github: skipping check (not a git repository)
YOLOv5  2021-4-12 torch 1.7.1+cu110 CUDA:0 (GeForce GTX 1650, 4096.0MB)

Namespace(adam=False, artifact_alias='latest', batch_size=4, bbox_interval=-1, bucket='', cache_images=False, cfg='models/yolov5s.yaml', data='data/face.yaml', device='', entity=None, epochs=5, evolve=False, exist_ok=False, global_rank=-1, hyp='data/hyp.scratch.yaml', image_weights=False, img_size=[640, 640], label_smoothing=0.0, linear_lr=False, local_rank=-1, multi_scale=False, name='exp', noautoanchor=False, nosave=False, notest=False, project='runs/train', quad=False, rect=False, resume=False, save_dir='runs\\train\\exp9', save_period=-1, single_cls=False, sync_bn=False, total_batch_size=4, upload_dataset=False, weights='weights/yolov5s.pt', workers=8, world_size=1)
tensorboard: Start with 'tensorboard --logdir runs/train', view at http://localhost:6006/
hyperparameters: lr0=0.01, lrf=0.2, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=0.0, mixup=0.0
wandb: Install Weights & Biases for YOLOv5 logging with 'pip install wandb' (recommended)
Overriding model.yaml nc=10 with nc=1

                 from  n    params  module                                  arguments                     
  0                -1  1      3520  models.common.Focus                     [3, 32, 3]                    
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]                
  2                -1  1     18816  models.common.C3                        [64, 64, 1]                   
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]               
  4                -1  1    156928  models.common.C3                        [128, 128, 3]                 
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]              
  6                -1  1    625152  models.common.C3                        [256, 256, 3]                 
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]              
  8                -1  1    656896  models.common.SPP                       [512, 512, [5, 9, 13]]        
  9                -1  1   1182720  models.common.C3                        [512, 512, 1, False]          
 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]              
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 12           [-1, 6]  1         0  models.common.Concat                    [1]                           
 13                -1  1    361984  models.common.C3                        [512, 256, 1, False]          
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]              
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 16           [-1, 4]  1         0  models.common.Concat                    [1]                           
 17                -1  1     90880  models.common.C3                        [256, 128, 1, False]          
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]              
 19          [-1, 14]  1         0  models.common.Concat                    [1]                           
 20                -1  1    296448  models.common.C3                        [256, 256, 1, False]          
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]              
 22          [-1, 10]  1         0  models.common.Concat                    [1]                           
 23                -1  1   1182720  models.common.C3                        [512, 512, 1, False]          
 24      [17, 20, 23]  1     16182  models.yolo.Detect                      [1, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
Model Summary: 283 layers, 7063542 parameters, 7063542 gradients, 16.5 GFLOPS

Transferred 354/362 items from weights/yolov5s.pt
Scaled weight_decay = 0.0005
Optimizer groups: 62 .bias, 62 conv.weight, 59 other
train: Scanning 'D:\faceyuanma\FaceDetect5\VOCdevkit\labels\train.cache' images and labels... 59 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 59/59 [00:00<?, ?it/s]
val: Scanning 'D:\faceyuanma\FaceDetect5\VOCdevkit\labels\val.cache' images and labels... 12 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 12/12 [00:00<?, ?it/s]
Plotting labels... 

autoanchor: Analyzing anchors... anchors/target = 5.23, Best Possible Recall (BPR) = 1.0000
Image sizes 640 train, 640 test
Using 0 dataloader workers
Logging results to runs\train\exp9
Starting training for 5 epochs...

     Epoch   gpu_mem       box       obj       cls     total    labels  img_size
       0/4    0.795G    0.1057   0.03017         0    0.1358         7       640: 100%|██████████| 15/15 [00:10<00:00,  1.46it/s]
D:\anaconda\envs\yolo\lib\site-packages\torch\optim\lr_scheduler.py:131: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
               Class      Images      Labels           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 2/2 [00:02<00:00,  1.43s/it]
                 all          12          20     0.00273        0.25     0.00109     0.00017

     Epoch   gpu_mem       box       obj       cls     total    labels  img_size
       1/4    0.814G     0.103   0.02903         0    0.1321         7       640: 100%|██████████| 15/15 [00:04<00:00,  3.40it/s]
               Class      Images      Labels           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 2/2 [00:00<00:00,  3.04it/s]
                 all          12          20      0.0024         0.4    0.000978    0.000159

     Epoch   gpu_mem       box       obj       cls     total    labels  img_size
       2/4    0.828G    0.1064   0.02965         0    0.1361         7       640: 100%|██████████| 15/15 [00:04<00:00,  3.44it/s]
               Class      Images      Labels           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 2/2 [00:00<00:00,  3.16it/s]
                 all          12          20     0.00285        0.05    0.000883    0.000112

     Epoch   gpu_mem       box       obj       cls     total    labels  img_size
       3/4    0.828G    0.1014   0.03021         0    0.1316         7       640: 100%|██████████| 15/15 [00:04<00:00,  3.52it/s]
               Class      Images      Labels           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 2/2 [00:00<00:00,  3.12it/s]
                 all          12          20     0.00182         0.2    0.000471    5.62e-05

     Epoch   gpu_mem       box       obj       cls     total    labels  img_size
       4/4     0.83G     0.103   0.02905         0     0.132         7       640: 100%|██████████| 15/15 [00:04<00:00,  3.51it/s]
               Class      Images      Labels           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 2/2 [00:00<00:00,  2.06it/s]
                 all          12          20      0.0023        0.05    0.000593     6.8e-05
5 epochs completed in 0.010 hours.

Optimizer stripped from runs\train\exp9\weights\last.pt, 14.4MB
Optimizer stripped from runs\train\exp9\weights\best.pt, 14.4MB

Process finished with exit code 0
`
![image](https://github.com/ultralytics/yolov5/assets/136170613/7991be16-9690-4ee9-a895-bc2544a99bba)

**Comment by DA-liu-a** [comment]
`D:\anaconda\envs\yolo\python.exe D:\yolov5-master\train.py 
train: weights=weights\yolov5s.pt, cfg=models/yolov5s.yaml, data=data\face.yaml, hyp=data\hyps\hyp.scratch.yaml, epochs=5, batch_size=4, imgsz=640, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, noplots=False, evolve=None, bucket=, cache=None, image_weights=False, device=, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=8, project=runs\train, name=exp, exist_ok=False, quad=False, cos_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, seed=0, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest
github: skipping check (not a git repository), for updates see https://github.com/ultralytics/yolov5
YOLOv5  2023-5-14 Python-3.8.16 torch-1.7.1+cu110 CUDA:0 (GeForce GTX 1650, 4096MiB)

hyperparameters: lr0=0.01, lrf=0.2, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=0.0, mixup=0.0
ClearML: run 'pip install clearml' to automatically track, visualize and remotely train YOLOv5  in ClearML
Comet: run 'pip install comet_ml' to automatically track and visualize YOLOv5  runs in Comet
TensorBoard: Start with 'tensorboard --logdir runs\train', view at http://localhost:6006/

                 from  n    params  module                                  arguments                     
  0                -1  1      3520  models.common.Conv                      [3, 32, 6, 2, 2]              
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]                
  2                -1  1     18816  models.common.C3                        [64, 64, 1]                   
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]               
  4                -1  2    115712  models.common.C3                        [128, 128, 2]                 
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]              
  6                -1  3    625152  models.common.C3                        [256, 256, 3]                 
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]              
  8                -1  1   1182720  models.common.C3                        [512, 512, 1]                 
  9                -1  1    656896  models.common.SPPF                      [512, 512, 5]                 
 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]              
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 12           [-1, 6]  1         0  models.common.Concat                    [1]                           
 13                -1  1    361984  models.common.C3                        [512, 256, 1, False]          
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]              
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 16           [-1, 4]  1         0  models.common.Concat                    [1]                           
 17                -1  1     90880  models.common.C3                        [256, 128, 1, False]          
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]              
 19          [-1, 14]  1         0  models.common.Concat                    [1]                           
 20                -1  1    296448  models.common.C3                        [256, 256, 1, False]          
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]              
 22          [-1, 10]  1         0  models.common.Concat                    [1]                           
 23                -1  1   1182720  models.common.C3                        [512, 512, 1, False]          
 24      [17, 20, 23]  1     16182  models.yolo.Detect                      [1, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
YOLOv5s summary: 214 layers, 7022326 parameters, 7022326 gradients, 15.9 GFLOPs

Transferred 308/349 items from weights\yolov5s.pt
AMP: checks passed 
optimizer: SGD(lr=0.01) with parameter groups 57 weight(decay=0.0), 60 weight(decay=0.0005), 60 bias
train: Scanning D:\yolov5-master\VOCdevkit\labels\train.cache... 59 images, 0 backgrounds, 0 corrupt: 100%|██████████| 59/59 [00:00<?, ?it/s]
val: Scanning D:\yolov5-master\VOCdevkit\labels\val.cache... 12 images, 0 backgrounds, 0 corrupt: 100%|██████████| 12/12 [00:00<?, ?it/s]

AutoAnchor: 5.13 anchors/target, 1.000 Best Possible Recall (BPR). Current anchors are a good fit to dataset 
Plotting labels to runs\train\exp23\labels.jpg... 
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs\train\exp23
Starting training for 5 epochs...

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
        0/4      1.07G        nan        nan          0          6        640: 100%|██████████| 15/15 [00:08<00:00,  1.70it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 2/2 [00:00<00:00,  5.10it/s]
                   all         12         20          0          0          0          0

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
        1/4      1.22G        nan        nan          0          7        640: 100%|██████████| 15/15 [00:07<00:00,  2.12it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 2/2 [00:00<00:00,  5.00it/s]
                   all         12         20          0          0          0          0

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
        2/4      1.22G        nan        nan          0          4        640: 100%|██████████| 15/15 [00:06<00:00,  2.15it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 2/2 [00:00<00:00,  5.01it/s]
                   all         12         20          0          0          0          0

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
        3/4      1.22G        nan        nan          0          6        640: 100%|██████████| 15/15 [00:06<00:00,  2.14it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 2/2 [00:00<00:00,  5.13it/s]
                   all         12         20          0          0          0          0

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
        4/4      1.22G        nan        nan          0          4        640: 100%|██████████| 15/15 [00:07<00:00,  2.12it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 2/2 [00:00<00:00,  5.12it/s]
                   all         12         20          0          0          0          0

5 epochs completed in 0.011 hours.
Optimizer stripped from runs\train\exp23\weights\last.pt, 14.4MB
Optimizer stripped from runs\train\exp23\weights\best.pt, 14.4MB

Validating runs\train\exp23\weights\best.pt...
Fusing layers... 
YOLOv5s summary: 157 layers, 7012822 parameters, 0 gradients, 15.8 GFLOPs
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 2/2 [00:00<00:00,  4.84it/s]
                   all         12         20          0          0          0          0
Results saved to runs\train\exp23

Process finished with exit code 0
`

**Comment by DA-liu-a** [comment]
I hope to receive your help. Thank you

**Comment by glenn-jocher** [comment]
@DA-liu-a dear user,

Thank you for reaching out to us with your issue regarding YOLOv5. We are happy to assist you and provide any help that we can. Can you please provide us with more details about the issue you are facing and any error messages you may have encountered? This will help us better understand the problem and provide a more targeted solution.

Looking forward to your response.

Best regards, 
The YOLOv5 Team.
