### ISSUE TITLE
Inference TensorRT model with FP16 in yolov5 with torch.hub.load

### ISSUE THREAD

**Issue by SJavad** [ultralytics/yolov5#11680]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi 🖐🌸
I have used this code for inference of the Yolov5 model:
```python
from pypylon import pylon
import cv2
import torch
import time

# conecting to the first available camera
camera = pylon.InstantCamera(pylon.TlFactory.GetInstance().CreateFirstDevice())

print("Create Camera Instance: # Find CAMERA \n")
# Grabing Continusely (video) with minimal delay
camera.StartGrabbing(pylon.GrabStrategy_LatestImageOnly) 
converter = pylon.ImageFormatConverter()
print("ImageFormatConverter # Convert Image Format BGR8 \n ")
# converting to opencv bgr format
converter.OutputPixelFormat = pylon.PixelType_BGR8packed
converter.OutputBitAlignment = pylon.OutputBitAlignment_MsbAligned

print("Loading Model: # .pt model \n")
model = torch.hub.load('.', 'custom',"..\\FinalModels\\3060FinalSmall.pt", source="local")
print("Config Model Prameters: # confidence-thresh and IOU \n")
model.conf = 0.70
model.iou = 0.45

print("Create VideoWriter Instance: # Video-Wrtie Class \n")
VideoWriter = cv2.VideoWriter("ResultRUN.avi", cv2.VideoWriter_fourcc(*"MJPG"),10,(640,640))


while camera.IsGrabbing():
    now_time = time.time()
    grabResult = camera.RetrieveResult(5000, pylon.TimeoutHandling_ThrowException)
    if grabResult.GrabSucceeded():
        # Access the image data
        image1 = converter.Convert(grabResult)
        image = image1.GetArray()
    grabResult.Release()

    results = model(image)
    print(results)
    results.render() # show results
    
    cv2.imshow("Detection",image)

    VideoWriter.write(image)
    if cv2.waitKey(20) == ord("q"):
        break
    
    
# Releasing the resource    
camera.StopGrabbing()
cv2.destroyAllWindows()

```
I want to Inference the tensorrt model with fp16 💪
how can I do that with this function -> torch.hub.load() ?🧐🤔

also, I have another question.😁
in another system when I use this code, it shows me the class names in frames as class0, class1 😑🤦‍♂️
how can I solve this problem 
how can I pass the data.yaml file to the function to use these class names?

**Comment by glenn-jocher** [comment]
@SJavad hello 👋🏼,

To use the TensorRT fp16 model with YOLOv5 using `torch.hub.load()`, you can specify the TRT engine file path in the `source` argument of the `torch.hub.load()` function. For example:

```python
model = torch.hub.load('.', 'custom', 'path/to/engine.trt', source='local', force_reload=True)
```

Regarding your question about class names being displayed as `class0`, `class1`, etc, you can pass the path to your data.yaml file to the `model` object like this:

```python
# Load model architecture from a .yaml file
model_yaml = 'path/to/model.yaml'
with open(model_yaml) as f:
    yaml_data = yaml.safe_load(f)
model = attempt_load('path/to/traced_model.pt', map_location=device)
# Set class names
model.names = yaml_data['names']
```

I hope this helps! Let me know if you have any further questions.

**Comment by SJavad** [comment]
> @SJavad hello 👋🏼,
> 
> To use the TensorRT fp16 model with YOLOv5 using `torch.hub.load()`, you can specify the TRT engine file path in the `source` argument of the `torch.hub.load()` function. For example:
> 
> ```python
> model = torch.hub.load('.', 'custom', 'path/to/engine.trt', source='local', force_reload=True)
> ```
> 
> Regarding your question about class names being displayed as `class0`, `class1`, etc, you can pass the path to your data.yaml file to the `model` object like this:
> 
> ```python
> # Load model architecture from a .yaml file
> model_yaml = 'path/to/model.yaml'
> with open(model_yaml) as f:
>     yaml_data = yaml.safe_load(f)
> model = attempt_load('path/to/traced_model.pt', map_location=device)
> # Set class names
> model.names = yaml_data['names']
> ```
> 
> I hope this helps! Let me know if you have any further questions.

Thank You, my issues have been solved. 😁✌🌸

**Comment by glenn-jocher** [comment]
@SJavad you're welcome! I'm glad that I could help solve your issues. Please don't hesitate to reach out if you have any further questions in the future. Have a great day! 😊
