### ISSUE TITLE
When batchsize=11 coco128 dataset return NAN loss.

### ISSUE THREAD

**Issue by haooyuee** [ultralytics/yolov5#11692]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I noticed that when the batchsize cannot be divisible by the number of data sets, it will cause NaN loss.
EX: python train.py --epochs 1 --upload_dataset --bbox_interval 1 --data data/coco128.yaml --batch-size 11

I printed the loss of each mini batch.
Wanted to ask if this is expected as sometimes the number of datasets may not be divisible by batchsize.

Thank you for your help

### Additional

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
  0%|          | 0/12 [00:00<?, ?it/s]tensor([nan], device='cuda:0', grad_fn=<MulBackward0>)
tensor([nan, nan, nan], device='cuda:0')
tensor(nan, device='cuda:0') tensor(nan, device='cuda:0') tensor(nan, device='cuda:0')
        0/0      2.45G        nan        nan        nan        151        640:   8%|▊         | 1/12 [00:01<00:19,  1.79s/it]tensor([nan], device='cuda:0', grad_fn=<MulBackward0>)
tensor([nan, nan, nan], device='cuda:0')
tensor(nan, device='cuda:0') tensor(nan, device='cuda:0') tensor(nan, device='cuda:0')
        0/0      2.45G        nan        nan        nan         88        640:  17%|█▋        | 2/12 [00:03<00:16,  1.66s/it]tensor([nan], device='cuda:0', grad_fn=<MulBackward0>)
tensor([nan, nan, nan], device='cuda:0')
tensor(nan, device='cuda:0') tensor(nan, device='cuda:0') tensor(nan, device='cuda:0')
        0/0      2.45G        nan        nan        nan        112        640:  25%|██▌       | 3/12 [00:04<00:14,  1.65s/it]tensor([nan], device='cuda:0', grad_fn=<MulBackward0>)
tensor([nan, nan, nan], device='cuda:0')
tensor(nan, device='cuda:0') tensor(nan, device='cuda:0') tensor(nan, device='cuda:0')
        0/0      2.45G        nan        nan        nan        158        640:  33%|███▎      | 4/12 [00:06<00:13,  1.65s/it]tensor([nan], device='cuda:0', grad_fn=<MulBackward0>)
tensor([nan, nan, nan], device='cuda:0')
tensor(nan, device='cuda:0') tensor(nan, device='cuda:0') tensor(nan, device='cuda:0')
        0/0      2.45G        nan        nan        nan        135        640:  42%|████▏     | 5/12 [00:08<00:11,  1.65s/it]tensor([nan], device='cuda:0', grad_fn=<MulBackward0>)
tensor([nan, nan, nan], device='cuda:0')
tensor(nan, device='cuda:0') tensor(nan, device='cuda:0') tensor(nan, device='cuda:0')
        0/0      2.45G        nan        nan        nan        160        640:  50%|█████     | 6/12 [00:09<00:09,  1.65s/it]tensor([nan], device='cuda:0', grad_fn=<MulBackward0>)
tensor([nan, nan, nan], device='cuda:0')
tensor(nan, device='cuda:0') tensor(nan, device='cuda:0') tensor(nan, device='cuda:0')
        0/0      2.45G        nan        nan        nan        131        640:  58%|█████▊    | 7/12 [00:11<00:08,  1.66s/it]tensor([nan], device='cuda:0', grad_fn=<MulBackward0>)
tensor([nan, nan, nan], device='cuda:0')
tensor(nan, device='cuda:0') tensor(nan, device='cuda:0') tensor(nan, device='cuda:0')
        0/0      2.45G        nan        nan        nan        155        640:  67%|██████▋   | 8/12 [00:13<00:06,  1.63s/it]tensor([nan], device='cuda:0', grad_fn=<MulBackward0>)
tensor([nan, nan, nan], device='cuda:0')
tensor(nan, device='cuda:0') tensor(nan, device='cuda:0') tensor(nan, device='cuda:0')
        0/0      2.45G        nan        nan        nan        127        640:  75%|███████▌  | 9/12 [00:14<00:04,  1.61s/it]tensor([nan], device='cuda:0', grad_fn=<MulBackward0>)
tensor([nan, nan, nan], device='cuda:0')
tensor(nan, device='cuda:0') tensor(nan, device='cuda:0') tensor(nan, device='cuda:0')
        0/0      2.45G        nan        nan        nan        151        640:  83%|████████▎ | 10/12 [00:16<00:03,  1.59s/it]tensor([nan], device='cuda:0', grad_fn=<MulBackward0>)
tensor([nan, nan, nan], device='cuda:0')
tensor(nan, device='cuda:0') tensor(nan, device='cuda:0') tensor(nan, device='cuda:0')
        0/0      2.45G        nan        nan        nan        120        640:  92%|█████████▏| 11/12 [00:17<00:01,  1.60s/it]tensor([1.05257], device='cuda:0', grad_fn=<MulBackward0>)
tensor([0.04504, 0.08434, 0.02098], device='cuda:0')
tensor(nan, device='cuda:0') tensor(nan, device='cuda:0') tensor(nan, device='cuda:0')
        0/0      2.45G        nan        nan        nan        116        640: 100%|██████████| 12/12 [00:18<00:00,  1.58s/it]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 6/6 [00:05<00:00,  1.14it/s]
                   all        128        929          0          0          0          0

**Comment by glenn-jocher** [comment]
@haooyuee it looks like you are encountering an issue with NaN loss when using a batch size of 11 with the COCO128 dataset. This might be because the number of datasets is not divisible by the batch size. The training process seems to be aborting due to this issue.

You can try using a batch size that is a divisor of the total number of datasets in the COCO128 dataset to see if that resolves the NaN loss issue. For example, using batch sizes like 8 or 16 could be a good starting point for experimentation.

Let me know if adjusting the batch size helps resolve the issue!
