### ISSUE TITLE
python train.py --resume

### ISSUE THREAD

**Issue by xinxin342** [ultralytics/yolov5#1169]
## ❔Question
1. As I continue to train, the mAP stays zero. Why is that?
2. Suppose that I set the epoch=300 at the beginning, and the training stopped when epoch=100，. Then I wanted to continue the training for 50 times. How to do this?

**Comment by whoafridi** [comment]
when you start training with any command your experiment is saved in yolov5/runs/exp.... If your training is interrupted for any reason, the following command will resume your partially completed training from the most recently updated experiment:
```py
python train.py --resume
```
or from a specific experiment:
```py
python train.py --resume runs/exp17/weights/last.pt
```

**Comment by xinxin342** [comment]
@whoafridi 
As I continue to train, the mAP stays zero. Why is that?
