### ISSUE TITLE
pre-training model with a custom data question.

### ISSUE THREAD

**Issue by danxuan2022** [ultralytics/yolov5#11690]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question
When the yolov5s pre-training model trains a custom data set, do I need to adjust the size of my training dataset to 640*640 and mark the bounding box?
Or do not care about the size of the training dataset, the yolov5s model will be automatically resized during training?
I am more worried that after marking the bounding box on the training set, the size of the training dataset needs to be resized and then re-labeled, which may be a waste of time...
my training dataset size is 1080 × 2336

![image](https://github.com/ultralytics/yolov5/assets/107532297/94a2deba-f593-40f6-a2e2-1faf43bb826a)

**Comment by glenn-jocher** [comment]
@danxuan2022 hi there! The YOLOv5 model automatically resizes input images to 640x640 during training, so you don't need to adjust the size of your training dataset. You can simply mark the bounding boxes on your existing dataset and start training. Your input images at 1080 × 2336 will be resized automatically during training. Thanks for using YOLOv5!
