### ISSUE TITLE
how to set threshold when you are converting to onnx version?

### ISSUE THREAD

**Issue by MohammadsAdrA-AI** [ultralytics/yolov5#11694]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to convert my custom model to onnx version, but I want to set the confidence threshold too. is there any way to do? or I just have to set the threshold after inference?

**Comment by glenn-jocher** [comment]
@MohammadsAdrA-AI to set the confidence threshold when converting to ONNX, use the `--include` flag in `export.py` with the desired threshold, or set it afterwards during inference. For post-inference thresholds, see [Ultralytics Docs](https://docs.ultralytics.com/yolov5). Let me know if you need further assistance!
