### ISSUE TITLE
Detect.py using model other than the default 

### ISSUE THREAD

**Issue by wymes** [ultralytics/yolov5#11691]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi

The detect.py documentation suggest that you can change the default values of the model and label  to use other models .

Is it possible to use the 

mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite

Model ?

I have tried to do this but get errors

**Comment by glenn-jocher** [comment]
@wymes hi there,

Yes, it is possible to use custom models with detect.py. To use the mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite model, you can specify the path to the model in the --weights parameter and update the --cfg to match the model architecture. Ensure that your model is compatible with the YOLOv5 implementation and format.

Let me know if you encounter any issues, and feel free to refer to our documentation at https://docs.ultralytics.com/yolov5 for more details.

Best regards 🚀
