### ISSUE TITLE
how to train classification model on my local data?

### ISSUE THREAD

**Issue by dao027** [ultralytics/yolov5#11704]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

latest version , object -detection training is all good.

Now i want to train a classification model based on yolov5x-cls.pt, but don't know how to implement on my own local data.
when i use `--data myLocalData.yaml `, it always try to download from internet rather than using my own data.
![image](https://github.com/ultralytics/yolov5/assets/35993172/7d2ae0bd-4196-49c6-8b1a-215ec5462216)

**Comment by xinghuokang** [comment]
```python
parser.add_argument('--data', 
                    type=str, 
                    default='mono_classify', 
                    help='cifar10, cifar100, mnist, imagenet, etc.')
```
modify "--data"，and prepare your custom data as the below image  
![image](https://github.com/ultralytics/yolov5/assets/30923040/6a43f16b-9c0a-4884-9040-e39a7d3de580)

**Comment by dao027** [comment]
> ```python
> parser.add_argument('--data', 
>                     type=str, 
>                     default='mono_classify', 
>                     help='cifar10, cifar100, mnist, imagenet, etc.')
> ```
> 
> modify "--data"，and prepare your custom data as the below image ![image](https://user-images.githubusercontent.com/30923040/245696324-6a43f16b-9c0a-4884-9040-e39a7d3de580.png)

many thanks for reply, can u tell me which folder should i put my labels.txt in?

**Comment by xinghuokang** [comment]
I also train my classify model，you can refer to it (https://blog.csdn.net/kxh123456/article/details/131130127)

**Comment by deepConnectionism** [comment]
The annotation file format is not currently supported. You can refer to this [repository](https://github.com/deepConnectionism/yolov5-7.0-cls).

**Comment by dao027** [comment]
thank you guys

**Comment by glenn-jocher** [comment]
@dao027 you're welcome! If you have any other questions or need further assistance, feel free to ask. Good luck with your training!
