### ISSUE TITLE
Why the final loss is scaled by batch size?

### ISSUE THREAD

**Issue by nannanmath** [ultralytics/yolov5#11703]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I find the code here:
https://github.com/ultralytics/yolov5/blob/a199480ba6bb527598df11abbc1d679ccda82670/utils/loss.py#L170-L175
I remain puzzled by the final loss multiplying batch size. I feel that will make the loss depending on batch size. If that is based on some practical experiences？

**Comment by chubbylhao** [comment]
Hey, this might help you: https://github.com/ultralytics/yolov5/issues/2377

**Comment by glenn-jocher** [comment]
@chubbylhao hello there! Thank you for reaching out. We really appreciate your interest in YOLOv5 and your willingness to help.

Thank you for sharing the link to the GitHub issue. We will take a look and provide assistance as soon as possible. If you have any additional questions or concerns, please don't hesitate to let us know. We're here to help!
