### ISSUE TITLE
model output (pred)

### ISSUE THREAD

**Issue by cd17861077351** [ultralytics/yolov5#11718]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, Thanks for sharing your excellent work.

I would like to know the content of the last demension of model output (pred, line 317, train.py), which has the size of (16,3,80,80,85). 

Does the last demension (85) has the format of (conf, x, y, w, h, c1,c2...c80) or (c1,c2...c80,x,y,w,h,conf), or any other formats?
Thanks in advance.

**Comment by Alberto1404** [comment]
### Search before asking
> 
>     * [x]  I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.
> 
> 
> ### Question
> 
> Hello, Thanks for sharing your excellent work.
> 
> I would like to know the content of the last demension of model output (pred, line 317, train.py), which has the size of (16,3,80,80,85).

Not the answer you were expecting but, you refer to the last hidden state, just before the detect module? I cannot get that tensor output. How do you do it?

> 
> Does the last demension (85) has the format of (conf, x, y, w, h, c1,c2...c80) or (c1,c2...c80,x,y,w,h,conf), or any other formats? Thanks in advance.
> ### Additional
> 
> _No response_

**Comment by glenn-jocher** [comment]
@Alberto1404 hey there! Thanks for showing interest in YOLOv5, glad to have you here. We're constantly amazed by the passionate contributors and the YOLO community, including our excellent team at Ultralytics.

For the format of the last dimension, the model output format is [x, y, w, h, objectness, 80 class scores]. The objectness score represents the probability that an object is present in the bounding box, and the class scores represent the probabilities for each class.

Hope this clears things up for you. If you have any other questions, feel free to ask!
