### ISSUE TITLE
Stem Module

### ISSUE THREAD

**Issue by PraveenMNaik** [ultralytics/yolov5#11710]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

where to find the "Stem" module which was earlier implemented, usually was available at models/common.py

please suggest, 

request for code

**Comment by glenn-jocher** [comment]
@PraveenMNaik the "Stem" module has been integrated directly into the backbone architecture and is no longer a separate entity within YOLOv5. You can find the specifics in the relevant `models/common.py` and the `models/yolo.py` files in the YOLOv5 repository. For further details, you can refer to the documentation at https://docs.ultralytics.com/yolov5. If you have any more questions or need assistance with the implementation, feel free to ask!
