### ISSUE TITLE
Your tutorial is inconsistent!

### ISSUE THREAD

**Issue by Maxwell2016LeChouchou** [ultralytics/yolov5#11714]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello you said 
Organize your train and val images and labels according to the example below. YOLOv5 assumes /coco128 is inside a /datasets directory next to the /yolov5 directory. YOLOv5 locates labels automatically for each image by replacing the last instance of /images/ in each image path with /labels/. For example:

../datasets/coco128/images/im0.jpg  # image
../datasets/coco128/labels/im0.txt  # label

However, your image shows: [image](https://github.com/ultralytics/yolov5/assets/19500229/fee96d46-7b13-410a-bc8a-05bb44dadeb5) is not consistent with label

**Comment by glenn-jocher** [comment]
@Maxwell2016LeChouchou hi there! Thanks for reaching out. Rest assured, the information provided in the tutorial aligns with the directory structure and label file naming convention required by YOLOv5. The directory setup you mentioned, `../datasets/coco128/images/im0.jpg` for images and `../datasets/coco128/labels/im0.txt` for labels, is indeed the ideal structure to follow for the automatic locating of labels. If you encounter any issues, please verify that your file paths and naming conventions match this pattern. If you have further questions or need assistance, feel free to ask! Always happy to help! 🚀
