### ISSUE TITLE
Intermediate resolutions between 640p and 1280p

### ISSUE THREAD

**Issue by Tsardoz** [ultralytics/yolov5#11715]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have been using yolov5s 640p models but want to increase accuracy.
We have time limits that prevent v5m or 1280p v5s6 models.
I would like to experiment with (say) a 768p model.
I understand --imgsz refers only to the resolution of the inference, not the training.
Training depends on the structure of the weights file (eg. yolov5s.pt).
I could structure my own structure via a yaml file for 768p and use random weights which will take forever and require more images than I have available.
Could I choose a v5s model, change the first layer to reflect 768p and randomise the weights just of the first layer and use pretrained v5s weights for the remainder? Would this work?

**Comment by glenn-jocher** [comment]
@Tsardoz the P6 models are trained at 1280, so you can use them up to that imgsz, therefore I would just use one of those if you are not looking to train a new model. If you want to train a new model you can train a P5 model at 768 if you want.
