### ISSUE TITLE
Image inverting when using the CPU-backend

### ISSUE THREAD

**Issue by HerrAskinSM** [ultralytics/yolov5#11726]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Validation

### Bug

Greetings, colleagues!
At startup val.ру using the python command
val.py --weights yolov5n.pt --batch-size 1 --dnn --verbose --device cpu
images with labels are saved in the results folder. Some images are inverted by color. The strange thing is that when using --device 0 instead --device cpu, the same images are saved in normal form.
In general, the problem is deeper. I have after training when inference of yolov5n.onnx using OpenCV cv::dnn::Net has no detection when using CPU, but when switching to CUDA, detections appear. I thought that the inversion of the image and the lack of detection may be related.
![val_batch0_labels](https://github.com/ultralytics/yolov5/assets/72979657/431ee489-07e3-442a-a24d-cab59525cb24)
![val_batch0_pred](https://github.com/ultralytics/yolov5/assets/72979657/f3da080b-8a89-4498-a280-6c70b56b6c0e)
![val_batch1_labels](https://github.com/ultralytics/yolov5/assets/72979657/694217e8-fbf2-44b3-9eb0-566ae592b56b)
![val_batch1_pred](https://github.com/ultralytics/yolov5/assets/72979657/85f7a491-ce34-4d6c-b9a0-1b70a14d9076)
![val_batch2_labels](https://github.com/ultralytics/yolov5/assets/72979657/554bc7fc-0390-4f06-a692-c739233143f0)
![val_batch2_pred](https://github.com/ultralytics/yolov5/assets/72979657/c7bb90b5-0162-4cb8-b804-2fe4f8c572b7)

### Environment

- YOLOv5 🚀 v7.0-181-g3812a1a Python-3.9.5 torch-1.12.1+cu116 CUDA:0 (NVIDIA GeForce RTX 3090, 24268MiB)
- Ubuntu 20.04
- Python 3.9.5

### Minimal Reproducible Example

val.py --weights yolov5n.onnx --batch-size 1 --dnn --verbose --device cpu
val.py --weights yolov5n.onnx --batch-size 1 --verbose --device 0

val.py --weights yolov5m.pt --batch-size 1 --dnn --verbose --device cpu
val.py --weights yolov5m.pt --batch-size 1 --verbose --device 0

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@HerrAskinSM hi there! Thank you for reaching out and reporting this issue.

Regarding the images being inverted when using the CPU backend, it seems like there might be an inconsistency between the CPU and CUDA backends. We appreciate you providing the specific command examples for reproduction.

Additionally, you mentioned that after training when using the yolov5n.onnx model and OpenCV's cv::dnn::Net for inference, you noticed no detections when using the CPU, but detections appeared when switching to CUDA. This could indeed be related.

To better assist you, we kindly ask you to provide more details on your system environment, such as the version of OpenCV used and any relevant specifications of your hardware setup.

Our team will look into this issue and investigate a possible solution. In the meantime, if you have any other information or insights that might be useful, please feel free to share them. We appreciate your willingness to contribute and submit a pull request to help resolve this issue.

Thank you for your patience, and we'll do our best to address this as soon as possible.

**Comment by HerrAskinSM** [comment]
Used OpenCV versions: 4.5.5.62, 4.7.0, 4,7,0_dev (latest)

**Comment by glenn-jocher** [comment]
Hi @HerrAskinSM,

Thank you for providing the OpenCV versions you have used (4.5.5.62, 4.7.0, 4.7.0_dev).

We will investigate this issue further and try to reproduce it using the provided OpenCV versions. It will help us narrow down the possible causes and find a solution.

Please allow us some time to analyze the problem and get back to you. If you have any additional details or insights that you think might be relevant, please don't hesitate to share them.

We appreciate your patience and contribution to resolving this issue.

Thank you.

**Comment by EliSheppard** [comment]
Is there a solution to this?
ultralytics              8.2.86
opencv-python-headless   4.10.0.84

I'm fine tuning YoloV8s.

**Comment by glenn-jocher** [comment]
@EliSheppard please ensure you're using the latest YOLOv5 version and verify if the issue persists. If it does, provide more details about the problem for further assistance.

**Comment by EliSheppard** [comment]
As I said, I I using YoloV8s.

**Comment by glenn-jocher** [comment]
For YOLOv8-specific issues, please refer to the Ultralytics YOLOv8 repository and documentation for guidance. If you encounter any problems, ensure you're using the latest version.
