### ISSUE TITLE
Image resize while inferencing

### ISSUE THREAD

**Issue by anirbanmalick** [ultralytics/yolov5#1172]
## ❔Question
I have a dataset with ~20 classes and with varying size of images. While training i resized the training images into 320x320.
Now when I perform inference, I observe for larger inference images, if I pass img_size = 640, detection is better. And for smaller images it is working better with resizing into 160x160

How should we make the inference so that it works with the same img_size that I am using for training (i.e, --img 320)?

**Comment by Aktcob** [comment]
Usually, inferring with larger size makes better results for all size objects.

**Comment by anirbanmalick** [comment]
I did not understand @Aktcob  Does it mean even if I train with resizing training images into 320, inference can give better result with resizing with bigger image(ex: 640)?
My assumption was - we should train and inference by doing the similar resizing operation.

**Comment by glenn-jocher** [comment]
@anirbanmalick 

- typically you will see best results by detecting at the same --img-size you trained at: `python train.py --img 640` and then `python detect.py --img 640`.
- separately, training and detecting at larger sizes with usually produce better results.

**Comment by anirbanmalick** [comment]
@glenn-jocher This answers my question. Thanks!
