### ISSUE TITLE
SyntaxError: EOL while scanning string literal

### ISSUE THREAD

**Issue by jianganghuang** [ultralytics/yolov5#11720]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Hello,Thanks for your excellent work. When I try to execute "python train.py" after preparing everything, Imeet the problem beloe,i it maybe caused by some symbols. What should I do? 

![image](https://github.com/ultralytics/yolov5/assets/127812522/b6e91ca6-faf8-437f-9940-3b074fd62202)

![image](https://github.com/ultralytics/yolov5/assets/127812522/3321b13b-448d-4f46-903c-a2bdf399cee3)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@hjg12345 hi,

Thank you for reaching out and for your kind words! I'm sorry to hear that you're experiencing a `SyntaxError: EOL while scanning string literal` error. This error usually occurs when there is a problem with the syntax or formatting of a string in your code.

To help you resolve this issue, could you please provide the relevant code snippets from your `train.py` file that are causing the error? This will allow us to better understand the problem and provide you with an appropriate solution.

In the meantime, here are a few general suggestions to check for common causes of this error:

1. Make sure that all string literals (text enclosed in quotes) in your code are properly closed with matching quotation marks.
2. Check for any special characters or escape sequences within your string literals that may be causing the error.
3. Verify that there are no missing or misplaced parentheses, brackets, or braces in your code.

Once we have more information about your specific code, we will be able to assist you further. Thank you for your patience, and we look forward to helping you resolve this issue!

**Comment by hjg12345** [comment]
I just changed my parser. this problem maybe caused by the specift sybbol like "✅" 、”⚠️“  or some else.
![image](https://github.com/ultralytics/yolov5/assets/127812522/f059efb1-33e3-42b5-bab7-a5487bb66601)

**Comment by hjg12345** [comment]
I just changed my parser. this problem maybe caused by the specift sybbol like "✅" 、”⚠️“ or some else.
![image](https://github.com/ultralytics/yolov5/assets/127812522/9a057064-d160-4933-8e54-a860193e6cae)

**Comment by hjg12345** [comment]
I just changed my parser. this problem maybe caused by the specific sybmol like "✅" 、”⚠️“ or some else.
image

**Comment by jianganghuang** [comment]
I just changed my parser. this problem maybe caused by the specific sybmol like "✅" 、”⚠️“ or some else. It can make " ' " disabled
![image](https://github.com/ultralytics/yolov5/assets/127812522/8095e85f-0642-4195-a8a6-f5da0aca44c6)
![image](https://github.com/ultralytics/yolov5/assets/127812522/886b6d96-963a-424a-af4c-5ee9e621c93f)

**Comment by glenn-jocher** [comment]
@hjg12345 thank you for identifying the potential cause of the issue. Based on the screenshots you provided, it seems that there may be specific symbols such as "✅" or "⚠️" causing the problem and disabling the apostrophe ('').

To resolve this issue, I would recommend removing any special symbols or unicode characters from your code, especially within string literals. You can replace them with equivalent ASCII characters or remove them altogether if they are not necessary for your code's functionality.

If the issue persists or if you have any additional questions, please let us know. We are here to help!
