### ISSUE TITLE
unsupported operand

### ISSUE THREAD

**Issue by Mahdi-Maaref** [ultralytics/yolov5#11727]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

while trying to save crop using detect.py i get this error:

```
save_one_box(xyxy, imc, file=save_dir / 'crops' / names[c] / f'{p.stem}.jpg', BGR=True)
TypeError: unsupported operand type(s) for /: 'PosixPath' and 'int'
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Mahdi-Maaref** [comment]
solved:
change this line in detect.py

`save_one_box(xyxy, imc, file=save_dir / 'crops' / str(names[c]) / f'{p.stem}.jpg', BGR=True)
`

**Comment by glenn-jocher** [comment]
@2022Mahdi glad to hear that you were able to solve the issue! Thank you for sharing the solution with us. Your suggestion to modify the `save_one_box` line in `detect.py` seems to have resolved the problem. We genuinely appreciate your effort to contribute to the YOLOv5 community by providing this solution.

**Comment by dimka11** [comment]
I have the same error now while using inference via torch hub model.

**Comment by glenn-jocher** [comment]
@dimka11 thanks for reaching out! I'm sorry to hear that you're encountering the same error during inference using the torch hub model. Could you please provide more details about the error you're experiencing? Specifically, if you could share the exact error message and any relevant code snippets, it would greatly help in understanding and resolving the issue. Additionally, please make sure that you are using the latest version of YOLOv5 and have followed the installation instructions correctly. Looking forward to your response!

**Comment by dimka11** [comment]
```
Downloading: "https://github.com/ultralytics/yolov5/zipball/master" to /root/.cache/torch/hub/master.zip
Collecting ultralytics
  Downloading ultralytics-8.0.203-py3-none-any.whl (644 kB)
```
How can I sure that I using last version via torch hub?


```
Cell In[4], line 14, in predict(model, images, save_dir)
     12 results = model(images, size=1920, augment=False)

---> 14 crops = results.crop(save=True, save_dir=save_dir, exist_ok=True)
     15 return results

File ~/.cache/torch/hub/ultralytics_yolov5_master/models/common.py:812, in Detections.crop(self, save, save_dir, exist_ok)
    810 def crop(self, save=True, save_dir='runs/detect/exp', exist_ok=False):
    811     save_dir = increment_path(save_dir, exist_ok, mkdir=True) if save else None
--> 812     return self._run(crop=True, save=save, save_dir=save_dir)

File ~/.cache/torch/hub/ultralytics_yolov5_master/models/common.py:767, in Detections._run(self, pprint, show, save, crop, render, labels, save_dir)
    765 label = f'{self.names[int(cls)]} {conf:.2f}'
    766 if crop:
--> 767     file = save_dir / 'crops' / self.names[int(cls)] / self.files[i] if save else None
    768     crops.append({
    769         'box': box,
    770         'conf': conf,
    771         'cls': cls,
    772         'label': label,
    773         'im': save_one_box(box, im, file=file, save=save)})
    774 else:  # all others

TypeError: unsupported operand type(s) for /: 'PosixPath' and 'int'
```

Also I have the integer class name - 0 in the dataset

**Comment by glenn-jocher** [comment]
@dimka11 it appears that you're encountering an issue with the torch hub model and getting the error "TypeError: unsupported operand type(s) for /: 'PosixPath' and 'int'." 

To ensure you are using the latest version of YOLOv5 via torch hub, you can run the following command before loading the model:

```python
import torch
torch.hub.download_url_to_file('https://github.com/ultralytics/yolov5/zipball/master', 'yolov5_master.zip', progress=True)
```

This will download the latest version of YOLOv5 from the master branch.

Regarding the error, it seems to be related to the presence of an integer class name in your dataset. The code is trying to save the cropped image using a Path object and integer class name as sub-paths, which is causing the error.

To resolve this issue, you can convert the integer class name to a string before concatenating it with the save directory path. Here's an example of how you can modify the code:

```python
file = save_dir / 'crops' / str(self.names[int(cls)]) / self.files[i] if save else None
```

By converting the integer class name to a string using `str()`, you should be able to avoid the unsupported operand error.

I hope this resolves the issue for you. Let me know if you have any further questions or concerns!
