### ISSUE TITLE
Issue with Running Inference on Custom Finetuned YOLOv5 Model

### ISSUE THREAD

**Issue by pierluigidovesi** [ultralytics/yolov5#11732]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,

I'm experiencing an issue when trying to run inference using `detect.py` on a YOLOv5 model that I've finetuned on custom data.

Here is the simplified version of the training code used:

```python
from ultralytics import YOLO

class TaskSettings:
    data: str
    epochs: int = 100
    batch: int = 8
    imgsz: int = 640

def main() -> None:
    args = parse_args()
    models_path = Path("./models")

    models = {
        key: YOLO(models_path / f"yolov5{key}.pt") for key in args.model_keys.split(",")
    }

    settings = TaskSettings(data=args.data_path)

    for model_key in models:
        models[model_key].train(**asdict(settings))
        models[model_key].export(format="onnx", batch=1)
        models[model_key].export(format="tflite", int8=True, batch=1)

```

The model training is successful based on the metrics and qualitative results. However, when I run inference with the `detect.py` (or `val.py`) script, I encounter an issue.

The command for running inference is:

```bash
python detect.py --weights path_to_weights/best.pt --source path_to_images --data path_to_data.yaml
```

I've added custom print statements in `detect.py` that yield the following results:

```python
(L158) det: tensor([[0.00000e+00, 0.00000e+00, 7.00000e+01, 9.30000e+01, 2.42085e+04, 6.34000e+02],
        [0.00000e+00, 0.00000e+00, 1.42000e+02, 1.63000e+02, 7.77347e+03, 6.26000e+03],
        [0.00000e+00, 3.30000e+01, 8.30000e+01, 7.20000e+01, 3.81636e+03, 6.08000e+03],
        [3.00000e+00, 1.60000e+01, 4.00000e+01, 3.50000e+01, 2.02598e+03, 4.75700e+03]])
(L159) det[:, 5].unique(): tensor([ 634., 4757., 6080., 6260.])
```

The unique class indices from the output tensor change with every processed image.

The subsequent error traceback is:

```python
Traceback (most recent call last):
  File "detect.py", line 263, in <module>
    main(opt)
  File "detect.py", line 258, in main
    run(**vars(opt))
  File "/miniconda3/envs/py310_pt/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 162, in run
    s += f"{n} {names[int(c)]}{'s' * (n > 1)}, "  # add to string
KeyError: 634
```

The error occurs regardless of whether I load the ONNX or TFLite model.

For the custom data, I'm using a YAML configuration with 4 classes. The `data.yaml` file is as follows:

```yaml
names:
- Class1
- Class2
- Class3
- Class4
nc: 4
train: path_to_train_images
val: path_to_val_images
```

I've also tried converting the class names to a dictionary, but this did not make any difference.

The versions of the packages I'm using are as follows:

```bash
torch                     2.0.1                    pypi_0    pypi
ultralytics               8.0.117                  pypi_0    pypi
yolov5                    7.0.12                   pypi_0    pypi
```

Any help or suggestions would be greatly appreciated. Thanks!

**Comment by glenn-jocher** [comment]
@pierluigidovesi hi there,

Thank you for reaching out and providing detailed information about the issue you are facing.

Based on the provided information, it seems like the error occurs when the class indices are not present in the `names` list defined in the `data.yaml` file. This can lead to a `KeyError` when trying to access the class names based on the class indices.

To resolve this issue, please ensure that the class indices in the output tensor correspond to the class names defined in the `data.yaml` file. Double-check that the class indices range from 0 to `nc-1` (in your case, 0 to 3). Also, confirm that the class names are correctly specified in the `names` list in the `data.yaml` file.

If the issue persists, please try upgrading to the latest versions of the packages you are using, including `ultralytics` and `yolov5`.

Additionally, it's worth noting that the YOLOv5 repository you are currently using is not the official repository maintained by Ultralytics. I suggest checking the official Ultralytics YOLOv5 repository (https://github.com/ultralytics/yolov5) for the latest updates, bug fixes, and helpful resources.

I hope this helps! If you have any further questions, please feel free to ask.

**Comment by pierluigidovesi** [comment]
Hi,

Thank you for your quick response and the suggestions. I want to clarify a couple of points:

1. The `detect.py` script I'm using is directly cloned from the official Ultralytics YOLOv5 repository that you linked. So, I'm not using any third-party version of the script.

2. Based on your recommendation, I tried again changing the `names` section in my `data.yaml` file to a dictionary mapping, but the issue persists. My updated `data.yaml` now looks like this:

```yaml
path: path_to_dataset
train: train/images
val: val/images
names:
  0: Class1
  1: Class2
  2: Class3
  3: Class4
```

Despite these changes, I am still facing the same issue. Could there be any other aspect I might be overlooking?

Thank you again for your help.

**Comment by glenn-jocher** [comment]
@pierluigidovesi hi,

Thank you for providing additional information and for clarifying your points. I apologize for any confusion caused.

Based on the updated information you provided, it seems like the issue is not related to the `names` section in the `data.yaml` file or the specific version of the `detect.py` script.

To further investigate the issue, it would be helpful to have more details about your dataset and the specific steps you took to prepare it. Could you please provide more information about your dataset, such as the number of classes, the format of the bounding box annotations, and any preprocessing steps you performed?

Additionally, it would be beneficial to see the exact command you are using to run the `detect.py` script, along with the full error traceback you receive. This will help us understand the context in which the error occurs and provide more accurate guidance.

Thank you for your patience, and I look forward to assisting you further.

**Comment by pierluigidovesi** [comment]
Hi,

The number of classes in my dataset is 4. The images are in JPEG format with an original size of 2592x1944. During training, I set the image size (`imgsz`) to 640.

The bounding box annotations are in the classic YOLO format, with corresponding TXT files having the same name as the images. An example of the bounding box format is as follows:

```txt
1 0.6956118821421271 0.3873875085928158 0.006396322114783803 0.008965784844654545
0 0.4085648148148148 0.3852880658436214 0.01620370370370372 0.021604938271604923
...
```

The structure of my dataset directory is:

```
.
├── data.yaml
├── train
│   ├── images  [338 entries]
│   ├── labels  [338 entries]
└── val
    ├── images  [51 entries]
    └── labels  [51 entries]
```

The command and full error traceback that I'm using to run the `detect.py` script can be found in the first message of my issue.

Despite following the recommended steps, I am still facing the issue. I would appreciate any further guidance on this.

**Comment by glenn-jocher** [comment]
@pierluigidovesi hi,

Thank you for providing additional information about your dataset and the steps you've taken. Based on the details you provided, it seems like you've followed the correct steps for preparing your dataset and configuring the `data.yaml` file.

To further debug the issue, it would be helpful to see the exact command you are using to run the `detect.py` script, as well as the full error traceback you receive. This will allow us to understand the context in which the error occurs and provide more accurate guidance.

Additionally, please ensure that the file paths in the `data.yaml` file are correct and point to the correct directories.

If the issue persists, you can try the following troubleshooting steps:

1. Double-check that the class indices in the bounding box annotations match the class names specified in the `data.yaml` file.

2. Verify that the bounding box annotations have been properly converted to the YOLO format, with the class index followed by the normalized coordinates of the bounding box.

3. Ensure that the file extensions in the image and label directories match (e.g., `.jpg` for images and `.txt` for labels) and that the file names correspond to each other.

If the issue still persists after trying these troubleshooting steps, please provide the exact command and error traceback, and any additional information that may help us understand the issue. This will allow us to provide more specific guidance.

I hope this helps! If you have any further questions or concerns, please don't hesitate to ask.
