### ISSUE TITLE
Loading Yolov5 custom model without Internet Connection

### ISSUE THREAD

**Issue by mbober01** [ultralytics/yolov5#11733]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is there a way to load a custom Yolov5 model i have weights file  for without internet connection and without cloning whole yolov5 repo.
I don't want to rely on cache on local machine as well. It should always work without relying on anything else.
If cloning yolov5 repo is needed to achieve it is there a way to minimize the files needed from it for it to load successfully.

**Comment by glenn-jocher** [comment]
@mbober01 hi there! Yes, you can load a custom YOLOv5 model without an internet connection and without cloning the entire YOLOv5 repo. You can load a custom model using only the YOLOv5 script and the weights file. No internet connection or cloned repo is required. However, if cloning the YOLOv5 repo is necessary, you can minimize the files needed by cloning only the necessary files such as the custom model definition, requirements, and scripts. For more details, you can refer to the YOLOv5 documentation at docs.ultralytics.com/yolov5. Let me know if you need any further assistance!

**Comment by superyo12** [comment]
@mbober01 HI! I'm working with PyPI yolov5 and I solved the issue of load a custom trained weight file without internet connection just passing the absolute path to the file in yolov5.load(). Hope this solution works for you too.

**Comment by glenn-jocher** [comment]
Hey there! Thanks for sharing your solution! Using the absolute path in `yolov5.load()` is indeed a straightforward way to load custom weights offline. Great tip! 😊 If anyone else has questions or needs further clarification, feel free to ask. Happy coding!
