### ISSUE TITLE
Extract features from specific layers

### ISSUE THREAD

**Issue by maxiaotian520** [ultralytics/yolov5#1173]
## ❔Question
Is there a way to extract features from specific intermediate layers of the model?

**Comment by Aktcob** [comment]
add additional output branch for specific layers

**Comment by glenn-jocher** [comment]
@maxiaotian520 yes like @Aktcob comment, you can output whatever you want from the model forward function, like any pytorch model.

**Comment by maxiaotian520** [comment]
@glenn-jocher  Got it, it's really helpful, thank you. And I also have one more question that need your help, which is the role of BottleneckCSP layer. I mean, like, which kind of feature was extracted or treated by BottleneckCSP after a image was passing through the architecture?

**Comment by GiuliaCiaramella** [comment]
@maxiaotian520  did you manage the problem?
