### ISSUE TITLE
Trained yolov5 weights (in onnx format) and custom/recent models don't have the same architecture! why ?

### ISSUE THREAD

**Issue by besmaguesmi** [ultralytics/yolov5#11744]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Dear all, @glenn-jocher 

The difference of architecture between that I noticed come from the onnx version. I have to use old opset version (<=12), is there any possibility to remove split layer from the architecture?

![Screenshot from 2023-06-20 11-48-10](https://github.com/ultralytics/yolov5/assets/36562278/5ff11f4f-4f00-451a-a17f-683904578b8e)

Thanks

**Comment by glenn-jocher** [comment]
@Guemann-ui hi there!

The architectural differences you're seeing are a result of the ONNX version used. YOLOv5 has been designed to work with recent ONNX versions, and using older opset versions may introduce architectural variances. To remove the split layer from the architecture, updating to a more recent ONNX version, if possible, is recommended.

Your feedback is appreciated and contributes to the ongoing evolution of YOLOv5. For specific guidance on modifying the ONNX output, our documentation at https://docs.ultralytics.com/yolov5 can offer further assistance.

Thank you for bringing this to our attention!
