### ISSUE TITLE
How to export confusion matrix output to csv from metrics.py?

### ISSUE THREAD

**Issue by fnadiaibrahim** [ultralytics/yolov5#11740]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, i was searching for a way to export confusion matrix data into csv, and also results for each class confidence values into csv.  Is there also a way to export data of detections from detect.py in form of csv with the images? These output can give significant analysis for my current project. 

I have tried all the changes from pull request but it seems unsuccessful.

**Comment by glenn-jocher** [comment]
@fnadiaibrahim hi there! To export the confusion matrix from metrics.py to a CSV file, you can use the `plot_confusion_matrix` function to generate the confusion matrix plot, and then manually extract the required data from the plot using Python's data manipulation libraries like Pandas and export it to a CSV file. 

For exporting class confidence values, you can modify the `plot_results()` function in `utils/torch_utils.py` to save the results to a CSV file. As for exporting data from `detect.py` to CSV, you can customize the `save_one_json` function in `detect.py` to save the data to a CSV format.

Hope this helps! Let me know if you need further assistance.
