### ISSUE TITLE
Error in val.py on Jetson Nano

### ISSUE THREAD

**Issue by abhinavvsharma** [ultralytics/yolov5#11747]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Hi, I am traying to run ```val.py``` using CUDA on Jetson Nano but I am getting ```RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!```. I have tried specifying ```0``` and ```cuda:0``` as ```--device``` arguments, but I still get the same error. The code works on ```cpu```.  

Command: 
```
python3 val.py --weights /home/yolov5/pruned_models/exp657/unpruned/best.pt --data /home/yolov5/data/coco_minitrain_25k_n_cls_1_dk_v1_1_cls_0.yaml --source 0
```

I am sharing the error log here:
```
Traceback (most recent call last):
  File "val.py", line 396, in <module>
    main(opt)
  File "val.py", line 369, in main
    run(**vars(opt))
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "val.py", line 246, in run
    correct = process_batch(predn, labelsn, iouv)
  File "val.py", line 83, in process_batch
    iou = box_iou(labels[:, 1:], detections[:, :4])
  File "/home/yolov5/utils/metrics.py", line 278, in box_iou
    inter = (torch.min(a2, b2) - torch.max(a1, b1)).clamp(0).prod(2)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

### Environment

 - YOLO - YOLOv5 🚀 v6.1-249-g7c2691f Python-3.6.9 torch-1.10.0 CUDA:0 (NVIDIA Tegra X1, 3964MiB)
 - OS - Ubuntu 18.04
 - Python - 3.6.9
 - Device - Jetson Nano
 - Jetpack - 4.6.1
 - CUDA - 10.2

### Minimal Reproducible Example

```
python3 val.py --weights /home/yolov5/pruned_models/yolov5n.pt --data /home/yolov5/data/coco_minitrain_25k_n_cls_1_dk_v1_1_cls_0.yaml --source 0
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@abhinavvsharma hi there, it seems like the issue might be related to the compatibility of the CUDA environment with your Jetson Nano device. Please make sure that the correct CUDA version and drivers are installed for your setup.

You may also check if the CUDA device is properly set and accessible using `torch.cuda.is_available()`.

Feel free to refer to the Ultralytics Docs for further assistance, and if you find a solution, your contribution to the YOLOv5 project through a PR would be much appreciated!

Cheers!
