### ISSUE TITLE
How i can save image detection with counting object detection?

### ISSUE THREAD

**Issue by kosongdansatu** [ultralytics/yolov5#11748]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How i can save image detection with counting object detection? and this is link my expectation result [https://drive.google.com/file/d/1_BoWYXQcPnAzNW13myGr3oGOdij7SWqC/view?usp=sharing](url)

**Comment by glenn-jocher** [comment]
@kosongdansatu you can use the `detect` method in YOLOv5 to save images with bounding box annotations. You may also customize the detection results as per your requirement. Refer to the [Ultralytics Docs](https://docs.ultralytics.com/yolov5) for detailed instructions. Feel free to reach out if you need further assistance. 😊
