### ISSUE TITLE
Image classification issue

### ISSUE THREAD

**Issue by Mahdi-Maaref** [ultralytics/yolov5#11742]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

well  dear @glenn-jocher  , i would to do a classfication task which classify number from 0 to 9 but using yolo defualt augmentations cause misseing part of image by changeing size ratio and  scale  and its not possible for network to see image and classify well even for human beacuse of similarity between numbers 
here is yolo code:

`A.RandomResizedCrop(height=size, width=size, scale=(0.8, 1.0), ratio=(0.9, 1.11), p=0.0)`

i tried to set scale and ratio value to (1.0,1.0) but steel issue persists ,thank u in advance

**Comment by Mahdi-Maaref** [comment]
also i tried to set  false augmentation in classify/train.py but network tend to be overfit soon

**Comment by glenn-jocher** [comment]
@2022Mahdi hi there! Thanks for reaching out! It sounds like you're running into some challenges with image classification and YOLOv5's default augmentations. YOLO is primarily designed for object detection, so for straightforward image classification tasks, you may find better results using a dedicated image classification model.

For issues related to overfitting, you might consider experimenting with different network architectures, regularization techniques, or adjusting the amount of available training data.

Feel free to check out the YOLOv5 [documentation](https://docs.ultralytics.com/yolov5) for more information, and don't hesitate to ask if you have further questions. Good luck with your project!
