### ISSUE TITLE
NVIDIA ISAAC ROS

### ISSUE THREAD

**Issue by reinzler** [ultralytics/yolov5#11753]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, is it possible to use ultralytics with YOLOv5 model inside the NVIDIA ISAAC ROS container on Jetson Orin Nano? Pytorch version- 1.12, torchvision version - 0.13, CUDA- 11.4? Thanks in advance

**Comment by glenn-jocher** [comment]
@reinzler hi there! Thanks for reaching out. Yes, it's definitely possible to run YOLOv5 with Ultralytics inside the NVIDIA ISAAC ROS container on Jetson Orin Nano. You can install the required PyTorch and torchvision versions, ensuring compatibility with your platform, and then use the YOLOv5 codebase as usual. If you encounter any specific issues during the setup, feel free to ask for help. Good luck!
