### ISSUE TITLE
Yolo 5 test output modification 

### ISSUE THREAD

**Issue by malekaburaddaha** [ultralytics/yolov5#11754]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to modify the output when running the test of Yolo, where I want to save each image's metrics with its predicted/output bounding box coordinates in a csv file.

The question is that: Where should I add my code to get the desired output, I checked detect.py, and predict.py... and was not sure where exactly my code fits, so just wanted to make sure which file should I work on to get the desired results?

**Comment by fnadiaibrahim** [comment]
yeah i want to do that too ! Hope @glenn-jocher hear us out.

**Comment by malekaburaddaha** [comment]
@glenn-jocher Can you assist us please

**Comment by glenn-jocher** [comment]
@malekaburaddaha hello there! Thanks for reaching out. To achieve your goal, you can modify the `test.py` file in the YOLOv5 repository. This file handles the testing process, and you can add your code to save the metrics and predicted bounding box coordinates to a CSV file.

Remember to look for the area where the predictions are processed, for example in the `for` loop that handles the detections. You can use the `csv` module in Python to help with creating and writing to the CSV file.

I hope this points you in the right direction! Let me know if you have any further questions. 🚀
