### ISSUE TITLE
analysis parameter changes during file analysis

### ISSUE THREAD

**Issue by krolaper** [ultralytics/yolov5#11757]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is it possible to update the analysis parameters, if they have been changed, during the analysis of a file without restarting it from the very beginning? Let me explain with an example: the client wants to analyze a video / webcam and find people in each frame, but during the analysis he decided to change `classes` from people to cars, while the analysis does not restart, but continues from the frame on which the changes were made. Suppose in the `detect.py` script in the `def run` method I will read an entry from the text file to define `classes` and compare it with the existing one, if it differs, replace and continue the analysis on the frame on which the replacement was made. At what stage of the code is it best to do this and will it even work?

**Comment by glenn-jocher** [comment]
@krolaper hi there! 👋 I understand the need for updating analysis parameters on-the-fly. YOLOv5's architecture currently does not support modifying analysis parameters during runtime without restarting from scratch. However, you can implement a custom solution within the `def process` method in `detect.py` to achieve this, although it's a non-trivial task.

Keep in mind that such a feature involves complex state management and could significantly affect performance and consistency. Remember, YOLOv5 is optimized for static configurations for efficiency and accuracy. Happy to help with further details or custom implementation suggestions. 🚀
