### ISSUE TITLE
How long does it take to actually start training after executing "python train.py"

### ISSUE THREAD

**Issue by jianganghuang** [ultralytics/yolov5#11751]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

when I prepare my datasets and environment, I execute "python train.py",and I wait for 30 minutes but it doesn't start training, it just output the network information below. I want to know how long it will actually train after executing "python train.py"? 30minutes is normal?
![image](https://github.com/ultralytics/yolov5/assets/127812522/7907d1f2-64f9-4e8b-800d-c562c3aff5dc)

**Comment by jianganghuang** [comment]
Now is 50minutes,but still don't start train.
YOLOv5 🚀 v7.0-181-g3812a1a Python-3.9.16 torch-1.10.0 CUDA:2 (GeForce RTX 3090, 24268MiB)

**Comment by jianganghuang** [comment]
Now is 60minutes, it finally continue output information as below, I want to know in the 60minutes what the yolov5 did! and its normal to spend 60minutes before actually training? 
![image](https://github.com/ultralytics/yolov5/assets/127812522/de069895-dbf5-40eb-b4e8-c344eddc21cb)

**Comment by glenn-jocher** [comment]
@hjg12345 it's usual for YOLOv5 training to begin within a few minutes after executing `python train.py`, and slower startup times can occur during large dataset loading or complex network initialization. Your training may also be dependent on hardware and other setup specifics. It's great to hear training has now started for you, and the progress output seems normal. For additional assistance with YOLOv5, you can refer to the official Ultralytics Docs at https://docs.ultralytics.com/yolov5. 🚀
