### ISSUE TITLE
Option to train on cropped quadratic images

### ISSUE THREAD

**Issue by IlkayW** [ultralytics/yolov5#11750]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hiho,

is there an option to train on cropped quadratic images?

The inference on my model will be fixed on 640x640 with original input images @1920x1080.
So, there will be a cropping from 16:9 to 1:1 aspect ratio.

When i train with --img 640 the aspect ratios if the train image are still 16:9.

I'm not sure. if this question was asked before, but i didn't find anything similar.

Greetings,
Ilkay

**Comment by glenn-jocher** [comment]
@IlkayW hi Ilkay,

Thanks for reaching out! YOLOv5 does support training on images of different aspect ratios, including square images. If you want to train on cropped 640x640 images, you should preprocess your dataset to crop the images to this aspect ratio before training.

During training, the `--img-size` argument will resize your images to the specified resolution, maintaining the aspect ratio by default. For square training, ensure your dataset is preprocessed to be square.

For more detailed guidance on data preparation, please refer to our documentation.

Happy training! 😊
