### ISSUE TITLE
why this code takes a large time?and how to solve it?

### ISSUE THREAD

**Issue by Soikie** [ultralytics/yolov5#11767]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

This problem appears in a function named non_max_suppression in ulils.general .
In the for sentence ,the function only have one for sentence.
`x = x[xc[xi]]` ,it takes 0.2s,
and i changed it to
 `qqq = xc[xi]
x = x[qqq]
`
the second sentence `x = x[qqq]`,takes 0.19s 
why this code takes such a large time? and how to solve it?

**Comment by glenn-jocher** [comment]
@Soikie this issue might be related to the non_max_suppression function in the utils/general file of YOLOv5. It seems that the code `x = x[xc[xi]]` is taking a long time to execute. When you changed it to `qqq = xc[xi]` and `x = x[qqq]`, the execution time improved slightly.

The reason for the performance difference might be related to the way the indexing operation is performed in Python. However, keep in mind that this is just speculation without further investigation.

To further optimize the code, you could consider using other indexing techniques or exploring alternative implementations. However, please note that modifying the underlying code could have unintended consequences, so proceed with caution.

If the execution time is still unsatisfactory, please provide more details about your use case, including the input size, hardware setup, and any relevant profiling information. This will help the community provide more specific suggestions or workarounds.

Thanks for bringing this to our attention. We appreciate your contribution to the YOLOv5 project.
