### ISSUE TITLE
如何训练图片尺寸为（640,480）的模型

### ISSUE THREAD

**Issue by xingjunhong** [ultralytics/yolov5#11768]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

目前官方的模型训练的尺寸是正方形尺寸，如何训练修改为长方形（640,480）尺寸的模型？

**Comment by glenn-jocher** [comment]
@xingjunhong hi there,

To train the YOLOv5 model with a rectangular shape such as (640, 480), you can modify the input size in the training configuration file. Simply edit the `--img` argument in the `--hyp` section of the `yaml` file to specify your desired dimensions (e.g., `--img: '640, 480'`). This will ensure that the input images are resized to the specified dimensions during training.

Please note that modifying the input size may affect the performance and accuracy of your model, so it's important to experiment with different sizes and evaluate the results accordingly.

If you have any further questions or encounter any issues, please don't hesitate to ask.

Best regards,
Glenn Jocher

**Comment by xingjunhong** [comment]
> @xingjunhong hi there,
> 
> To train the YOLOv5 model with a rectangular shape such as (640, 480), you can modify the input size in the training configuration file. Simply edit the `--img` argument in the `--hyp` section of the `yaml` file to specify your desired dimensions (e.g., `--img: '640, 480'`). This will ensure that the input images are resized to the specified dimensions during training.
> 
> Please note that modifying the input size may affect the performance and accuracy of your model, so it's important to experiment with different sizes and evaluate the results accordingly.
> 
> If you have any further questions or encounter any issues, please don't hesitate to ask.
> 
> Best regards, Glenn Jocher

修改这个参数后，会出现报错。
parser.add_argument('--imgsz', '--img', '--img-size', type=int, default=[640, 480], help='train, val image size (pixels)')

Traceback (most recent call last):
  File "train.py", line 634, in <module>
    main(opt)
  File "train.py", line 528, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 283, in train
    for i, (imgs, targets, paths, _) in pbar:  # batch -------------------------------------------------------------
  File "/mnt/hdd/home/xingjh/anaconda3/envs/yolov5/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/mnt/hdd2/extension/xingjh/02.work/yolov5/utils/dataloaders.py", line 172, in __iter__
    yield next(self.iterator)
  File "/mnt/hdd/home/xingjh/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/mnt/hdd/home/xingjh/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/mnt/hdd/home/xingjh/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/mnt/hdd/home/xingjh/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/mnt/hdd/home/xingjh/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/mnt/hdd/home/xingjh/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/hdd/home/xingjh/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/hdd2/extension/xingjh/02.work/yolov5/utils/dataloaders.py", line 669, in __getitem__
    img, (h0, w0), (h, w) = self.load_image(index)
  File "/mnt/hdd2/extension/xingjh/02.work/yolov5/utils/dataloaders.py", line 737, in load_image
    r = self.img_size / max(h0, w0)  # ratio
TypeError: unsupported operand type(s) for /: 'list' and 'int'

**Comment by glenn-jocher** [comment]
@xingjunhong I apologize for the confusion. It seems that the issue you encountered is related to a type mismatch in the `imgsz` argument.

To resolve this error, make sure that the `imgsz` argument in the `--hyp` section of the `yaml` file is specified as a single integer (e.g., `imgsz: 640`). The `img_size` argument should be a single integer value, not a list. 

Once you make this adjustment, you should be able to train the model successfully with the desired rectangular shape (640, 480).

If you have any further questions or need additional assistance, please feel free to ask.

Best regards,
Glenn Jocher

**Comment by xingjunhong** [comment]
> @xingjunhong I apologize for the confusion. It seems that the issue you encountered is related to a type mismatch in the `imgsz` argument.
> 
> To resolve this error, make sure that the `imgsz` argument in the `--hyp` section of the `yaml` file is specified as a single integer (e.g., `imgsz: 640`). The `img_size` argument should be a single integer value, not a list.
> 
> Once you make this adjustment, you should be able to train the model successfully with the desired rectangular shape (640, 480).
> 
> If you have any further questions or need additional assistance, please feel free to ask.
> 
> Best regards, Glenn Jocher



但是我想训练的是（640,480）尺寸的模型，而不是（640,640）尺寸的模型

**Comment by glenn-jocher** [comment]
@xingjunhong I apologize for the confusion in my previous response.

To train a YOLOv5 model with a resolution of (640, 480) instead of (640, 640), you can modify the `img_size` argument directly in the `--hyp` section of the `yaml` file. Simply change the value of `img_size` to `480`. It should look like this: `img_size: 480`.

By setting the `img_size` to 480, you will be training the model with the desired rectangular shape of (640, 480).

Please let me know if you have any further questions or need any additional assistance.

Best regards,
Glenn Jocher

**Comment by JiahuiSun** [comment]
好家伙，跨语言交流，在训练的时候声明rect参数即可：python train.py --imgsz 640 --rect

**Comment by glenn-jocher** [comment]
@JiahuiSun hello,

Thank you for your input. Yes, when training the YOLOv5 model, you can specify the `rect` parameter to resize the input images to a rectangular aspect ratio. To specify a rectangular input size of (640, 480), you can use the following command: 

`python train.py --imgsz 640 480 --rect`

This will ensure that the input images are resized to the desired dimensions during training.

If you have any further questions or need additional assistance, please don't hesitate to ask.

Best regards,

**Comment by s2244521** [comment]
> @xingjunhong I apologize for the confusion. It seems that the issue you encountered is related to a type mismatch in the `imgsz` argument.
> 
> To resolve this error, make sure that the `imgsz` argument in the `--hyp` section of the `yaml` file is specified as a single integer (e.g., `imgsz: 640`). The `img_size` argument should be a single integer value, not a list.
> 
> Once you make this adjustment, you should be able to train the model successfully with the desired rectangular shape (640, 480).
> 
> If you have any further questions or need additional assistance, please feel free to ask.
> 
> Best regards, Glenn Jocher

Hi @glenn-jocher ,
If I train with rectangle model and I get the bad result (low AP and Recall), what parameters you recommend that I can change to improve my model result?

Best regards, Tina

**Comment by s2244521** [comment]
> @xingjunhong hi there,
> 
> To train the YOLOv5 model with a rectangular shape such as (640, 480), you can modify the input size in the training configuration file. Simply edit the `--img` argument in the `--hyp` section of the `yaml` file to specify your desired dimensions (e.g., `--img: '640, 480'`). This will ensure that the input images are resized to the specified dimensions during training.
> 
> Please note that modifying the input size may affect the performance and accuracy of your model, so it's important to experiment with different sizes and evaluate the results accordingly.
> 
> If you have any further questions or encounter any issues, please don't hesitate to ask.
> 
> Best regards, Glenn Jocher
Hi @glenn-jocher ,
If I train with rectangle model and I get the bad result (low AP and Recall), what parameters you recommend that I can change to improve my model result?

Best regards, Tina

**Comment by glenn-jocher** [comment]
Hi @s2244521,

If you are training a YOLOv5 model with a rectangular shape and experiencing lower AP and Recall, there are several parameters you can try adjusting to improve your model's results. Here are a few recommendations:

1. **Anchor boxes**: Experiment with different anchor box configurations that better suit your dataset. You can modify the `anchor.yaml` file to specify anchor box sizes and aspect ratios that are more representative of your dataset.

2. **Learning rate**: Adjust the learning rate in the training configuration file (`--hyp.yaml`). Lowering the learning rate can help the model converge more slowly and potentially improve performance.

3. **Image size**: Try using different image sizes during training. You can modify the `--img` argument in the `--hyp` section of the `yaml` file to specify different dimensions and see if it improves your model's accuracy.

4. **Data augmentation**: Explore different data augmentation techniques to increase the diversity of your training data. This can help the model generalize better to unseen examples. You can modify augmentation settings in the `--data.yaml` file.

Please note that these recommendations may require some experimentation and fine-tuning to find the best configuration for your specific dataset. It's always a good idea to keep track of your changes and evaluate the results using metrics such as AP and Recall.

If you have any further questions or need additional guidance, please let me know.

Best regards, Glenn Jocher

**Comment by LeiaLi** [comment]
The training data of Yolo is Coco, which are square images and the annotations are normalized. If I use rect mode, should I re-annotate the labels?

**Comment by pderrenger** [comment]
Hi @LeiaLi,  

No need to re-annotate labels when using `--rect` mode. YOLOv5's dataloader automatically handles rectangular training by adjusting image dimensions while preserving normalized annotations. The existing COCO-style labels (normalized xywh format) remain valid, as the preprocessing accounts for aspect ratio changes. For details, see the [Ultralytics Training Documentation](https://docs.ultralytics.com/yolov5/train_custom_data/#before-you-start).
