### ISSUE TITLE
ONNX model rectangular inference

### ISSUE THREAD

**Issue by rgaignoux** [ultralytics/yolov5#11763]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

After exporting the yolov5s.pt model to the onnx format, I noticed that the inference of the onnx model wasn't rectangular.

With yolov5s.pt : data/images/zidane.jpg: **384x640** 2 persons, 2 ties, 22.8ms
With yolov5s.onnx : data/images/zidane.jpg: **640x640** 2 persons, 2 ties, 33.3ms

Is it possible to do rectangular inference with an onnx model ?

**Comment by glenn-jocher** [comment]
@rgaignoux yes, it is possible to perform rectangular inference with an ONNX model in YOLOv5. By default, the exported ONNX model assumes a square input shape. However, you can modify the input resolution to achieve rectangular inference.

To do this, you can specify the `--rect` flag during the `export` command, which will ensure that the exported ONNX model supports rectangular inference. For example:
```
python detect.py --weights yolov5s.pt --img-size 640 --rect --export onnx
```
By using the `--rect` flag, the input resolution will be set to a square shape, and the exported ONNX model will support both square and rectangular inference.

I hope this helps! If you have any further questions, feel free to ask.
