### ISSUE TITLE
Yolov5 multi-object detection anomaly.

### ISSUE THREAD

**Issue by zl21516** [ultralytics/yolov5#11778]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When it comes to detecting multiple video streams, there seems to be no issue with using pt (PyTorch) models. However, when using other models such as onnx or engine models, an exception is thrown. How can this problem be resolved?

**Comment by glenn-jocher** [comment]
@zl21516 hi there! 👋

When working with multiple video streams and using YOLOv5 with PyTorch models, there shouldn't be any issues. However, it seems that you're encountering exceptions when using other models such as ONNX or engine models.

To resolve this problem, there are a few things you can try:

1. Ensure that the ONNX or engine models you're using are compatible with the version of YOLOv5 you have installed. Different versions may have different requirements.

2. Check if there are any specific instructions or guidelines for using ONNX or engine models with YOLOv5. The documentation or README of the model files may provide valuable insights.

3. Make sure that all the required dependencies for ONNX or engine models are properly installed. Sometimes, additional libraries or packages might be necessary for loading and running these models.

4. If the issue persists, you can consider opening a new issue on the [YOLOv5 GitHub repository](https://github.com/ultralytics/yolov5/issues) with detailed information about the exception you're encountering, the steps to reproduce it, and any relevant code snippets or logs. With more specific details, the community and the Ultralytics team will be able to provide more targeted help.

I hope this helps! If you have any further questions or need more assistance, please don't hesitate to ask.
