### ISSUE TITLE
Using LabelBox

### ISSUE THREAD

**Issue by sarasilva-digitalsense** [ultralytics/yolov5#11773]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello! I am starting a project in which I'm planning on using LabelBox to do the segmentation task to later on use on Yolov5. I noticed that Ultralytics has provided a labelbox_json2yolo.py script before. However, I believe LabelBox has since changed their labeling format and that script no longer works. I've also tried using the Labelbox eport_to_coco.py and then the general_json2yolo.py script provided by Ultralytics but that doesn't work either. Do you have any suggestions for this issue?

Thank you!

**Comment by glenn-jocher** [comment]
@Sara-desense hello! 

Thank you for reaching out. We appreciate your interest in using YOLOv5 with LabelBox for your project.

Regarding your concern, it seems that the labelbox_json2yolo.py script provided by Ultralytics may not be compatible with the latest labeling format of LabelBox. You've mentioned that you've also tried using the Labelbox export_to_coco.py and general_json2yolo.py script of Ultralytics, but to no avail.

We suggest that you reach out to LabelBox's support team for assistance regarding their labeling format, as they may be able to provide more insights and assistance to your concern.

Thank you for submitting this issue, and we hope this helps. If you have any further questions or concerns, please don't hesitate to ask.

Best, 
Glenn Jocher.

**Comment by AmitAilianiSDC** [comment]
@sarasilva-digitalsense were you able to figure out exporting label box annotations for yolo5?
