### ISSUE TITLE
Roboflow for Datasets, Labeling, and Active Learning BUG

### ISSUE THREAD

**Issue by tonygem2022** [ultralytics/yolov5#11771]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

When running: https://github.com/ultralytics/yolov5/issues/4975

importing the roboflow data (rf = Roboflow(model_format="yolov5", notebook="ultralytics")) returns the following:

RuntimeError: API Key is of Incorrect Type 
 Expected Type: <class 'str'>
 Input Type: <class 'NoneType'>

Unable to see why?

### Environment

Running in COLAB environment

### Minimal Reproducible Example

from roboflow import Roboflow
rf = Roboflow(model_format="yolov5", notebook="ultralytics")
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-2-2f6135367ffe>](https://localhost:8080/#) in <cell line: 2>()
      1 from roboflow import Roboflow
----> 2 rf = Roboflow(model_format="yolov5", notebook="ultralytics")

2 frames
[/usr/local/lib/python3.10/dist-packages/roboflow/__init__.py](https://localhost:8080/#) in check_key(api_key, model, notebook, num_retries)
     18 def check_key(api_key, model, notebook, num_retries=0):
     19     if type(api_key) is not str:
---> 20         raise RuntimeError(
     21             "API Key is of Incorrect Type \n Expected Type: "
     22             + str(type(""))

RuntimeError: API Key is of Incorrect Type 
 Expected Type: <class 'str'>
 Input Type: <class 'NoneType'>

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@tonygem2022 hi there! It looks like the issue you're encountering is related to the API key being of an incorrect type. The code is expecting the API key to be a string, but it seems to be receiving a NoneType. Have you set and passed the correct API key for the Roboflow import? 

If you need further assistance, I recommend reaching out to the Ultralytics documentation at https://docs.ultralytics.com/yolov5 for guidance on setting up the API key correctly. 

If you have any other questions, feel free to ask!
