### ISSUE TITLE
Why set clip_boxes=False when export to TensorFlow savedmodel format

### ISSUE THREAD

**Issue by mrbulb** [ultralytics/yolov5#11780]
Hello, I'm curious whey that set `clip_boxes=False` when export to TensorFlow savedmodel format, it may cause invalid coordinates which may < 0

https://github.com/ultralytics/yolov5/blob/0004c745daeebb0eb6455b90c3e8abb308e61320/models/tf.py#L488

**Comment by glenn-jocher** [comment]
@mrbulb the `clip_boxes=False` setting in the code you mentioned allows the bounding box coordinates to have values less than zero. This can be helpful in scenarios where the bounding box extends beyond the image boundaries. By default, the bounding box coordinates are clipped to the image size, preventing any validation errors.

If you are working with images that have objects partially or fully outside the image boundaries, you may need to set `clip_boxes=False` to ensure that the exported TensorFlow SavedModel includes those coordinates.

However, please note that in most cases, it is recommended to keep `clip_boxes=True` to ensure that the bounding box coordinates are within valid image boundaries. This helps to avoid any potential issues related to invalid coordinates.
