### ISSUE TITLE
“https://github.com/ultralytics/yolov5.wiki.git” can not open

### ISSUE THREAD

**Issue by MackDing** [ultralytics/yolov5#11786]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

“https://github.com/ultralytics/yolov5.wiki.git” can not open

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@MackDing hi there! 👋

I apologize for the inconvenience you are experiencing with opening the YOLOv5 Wiki link. The YOLOv5 Wiki has been deprecated and is no longer available at that URL.

Instead, you can find all the documentation and tutorials for YOLOv5 on our official website at https://docs.ultralytics.com/yolov5/.

If you have any specific questions or need assistance with YOLOv5, feel free to ask and I'll be more than happy to help you out.

Thank you for your understanding and support!

**Comment by MackDing** [comment]
> @MackDing hi there! 👋
> 
> I apologize for the inconvenience you are experiencing with opening the YOLOv5 Wiki link. The YOLOv5 Wiki has been deprecated and is no longer available at that URL.
> 
> Instead, you can find all the documentation and tutorials for YOLOv5 on our official website at https:docs.ultralytics.com/yolov5/.
> 
> If you have any specific questions or need assistance with YOLOv5, feel free to ask and I'll be more than happy to help you out.
> 
> Thank you for your understanding and support!

@glenn-jocher Great!

I've seen this old URL on the homepage has disappeared,
Being able to help everyone keep me happy~

**Comment by MackDing** [comment]
> @MackDing hi there! 👋
> 
> I apologize for the inconvenience you are experiencing with opening the YOLOv5 Wiki link. The YOLOv5 Wiki has been deprecated and is no longer available at that URL.
> 
> Instead, you can find all the documentation and tutorials for YOLOv5 on our official website at https:docs.ultralytics.com/yolov5/.
> 
> If you have any specific questions or need assistance with YOLOv5, feel free to ask and I'll be more than happy to help you out.
> 
> Thank you for your understanding and support!

@glenn-jocher Great!

I've seen this old URL on the homepage has disappeared,
Being able to help everyone keep me happy~

**Comment by glenn-jocher** [comment]
@MackDing thank you for your kind words! 😊 Our team is dedicated to providing the best support and resources for the YOLOv5 community. If you have any further questions or need assistance, feel free to reach out anytime. We're here to help!
