### ISSUE TITLE
Frames Per Second are Dropping Fast

### ISSUE THREAD

**Issue by NOxDriver** [ultralytics/yolov5#1178]
## ❔Question

I've managed to train my own custom model to detect animals.
However, as I start running, the FPS on Yolo main is around 10 FPS. Then after 2 minutes it goes down to less than 1 and the phone overheats.

Same with Tiny Yolo. It starts at 30 then goes down to less than one within minutes.

Looking around the web, people are saying that it is my iPhone 8. However, when I use iDetection, it doesn't happen and it is smooth. So it seems my phone can handle it.

Any suggestions as to how to fix this?

**Comment by glenn-jocher** [comment]
@NOxDriver sure, thermal throttling is standard practice for any passively-cooled hardware. You have to differentiate steady state performance from initial performance.

iDetection source code is available as a reference app for business customers, email for details.

**Comment by NOxDriver** [comment]
@glenn-jocher Ah, thanks! 
I think we are just going to work on a few things on the other aspects of the app and then will make an appointment with you guys.
Thanks for the feedback.

**Comment by glenn-jocher** [comment]
Sure!

**Comment by NOxDriver** [comment]
@glenn-jocher I tried to make contact via the email contact form. Please let me know if you got it?

**Comment by glenn-jocher** [comment]
@NOxDriver no, have not received anything. You can send en email directly to: glenn.jocher@ultralytics.com
