### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by akshaykadam771** [ultralytics/yolov5#1179]
i had trained the yolov5 model on my custom dataset on colab and after that i am trying to run this in my local system using webcam but it is giving me issue "Illegal instruction (core dumped)" and i am not able to run it locally.
![yolov5_error_1](https://user-images.githubusercontent.com/62059604/96569862-489e2080-12e7-11eb-9329-25eecf6360ce.png)

but when i tried with the default yolov5s.pt model weights which comes with repostory then i am able to execute.

![yolov5_run_error_2](https://user-images.githubusercontent.com/62059604/96569913-59e72d00-12e7-11eb-8be1-f9c16191b5e7.png)

 anyone knows what will be the issue?

**Comment by glenn-jocher** [comment]
it appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below. 


## Requirements

**Python 3.8** or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including **`torch>=1.6`**. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by akshaykadam771** [comment]
i had tested with same requirements as mentioned in above. my concern is when i am trying to run my custom trained model in same environment then it is giving me the error "Illegal instruction (core dumped)" but if i am going to test with the default pretrained model which is trained on coco (yolov5s.pt)  in same environment then it is working. why? is there is a problem with my trained model file?
Thanks in advance.

**Comment by akshaykadam771** [comment]
is there any changes i have to do in any files for testing my custom model?

**Comment by glenn-jocher** [comment]
@akshaykadam771 custom models are trained exactly the same as the official models. We train the official models in a Google Cloud environment above in the Environments section, and then simply upload them to this repo. No other special action is done with the official models.

If the official environments work correctly for training and testing your custom model, then there is an issue with your local environment.

**Comment by akshaykadam771** [comment]
Ok Thank you @glenn-jocher i will try to check again with my environment

**Comment by akshaykadam771** [comment]
@glenn-jocher i checked again with new environment but same issue is there. it works with default downloaded yolov5s.pt model

![yolov5_locla_check](https://user-images.githubusercontent.com/62059604/96905252-d891c500-14b5-11eb-8041-19c43d38b7b6.png)

but it is giving me error with my custom trained model

![yolov5_now_error](https://user-images.githubusercontent.com/62059604/96905400-070fa000-14b6-11eb-960b-e77f805e1de4.png)

for both i have used same environment, so why it is giving me the error?

**Comment by glenn-jocher** [comment]
@akshaykadam771 I I'd recommend using a verified environment to train and test:

it appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below. 


## Requirements

**Python 3.8** or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including **`torch>=1.6`**. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by akshaykadam771** [comment]
yes @glenn-jocher it was problem with my system itself. it is working in other system. Thank you so much @glenn-jocher
