### ISSUE TITLE
How to deploy the model (.pt) or convert to tf model(.pb)

### ISSUE THREAD

**Issue by elvinest** [ultralytics/yolov5#118]
How to deploy .pt file to production environment (web or mobile) or convert to tensorflow model file (.pb)

I trained my own dataset and generated the last.pt file,I can run detect.py perfectly to predict, but I don’t know how to deploy models(.pt) or convert them to tensorflow model files(.pb)

Hope help me! Thanks.

**Comment by BernardinD** [comment]
Any luck with this?

**Comment by ShihuaiXu** [comment]
Any luck with this?

**Comment by sleepyheead** [comment]
Any luck with this?

**Comment by glenn-jocher** [comment]
@sheerrrr for exporting YOLOv5 PyTorch models to TensorFlow or TFLite see https://github.com/ultralytics/yolov5/pull/1127

**Comment by Dutra-Apex** [comment]
You can export a torch as a .onnx file using `toch.onnx.export`
From there you can either deploy the .onnx file, or convert it to a .pb file by using tesnorflow onnx backend: https://github.com/onnx/onnx-tensorflow

**Comment by glenn-jocher** [comment]
@Dutra-Apex that's correct! You can export your `.pt` model to ONNX format using `torch.onnx.export`, and then use the ONNX model in various production environments or convert it to TensorFlow's `.pb` format using the ONNX-TensorFlow converter. For detailed instructions on exporting to ONNX and further conversion, please refer to our documentation. If you encounter any issues or have further questions, feel free to ask here. Happy deploying! 😊🚀
