### ISSUE TITLE
How to change output layer activation function to softmax

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#1180]
## ❔Question
I'm trying to train a model for PPE detection, based of the second approach detailed in this paper: https://www.sciencedirect.com/science/article/abs/pii/S0926580519308325

The author mention that they achieved better results when the model was trained using the softmax activation function in the final output layers (section 5.3.2 in paper). How would I make this change in yolov5? 

I've looked at the answer to this issue: https://github.com/ultralytics/yolov5/issues/584 , but if I'm not mistaken, this will change the activation function in all layers, not just the final ones.

**Comment by glenn-jocher** [comment]
@adamwhats97 I wouldn't worry about it, softmax and sigmoid (what YOLOv5 already uses on all outputs) will produce nearly the same results in most cases. For class vectors, softmax is mainly used for single-labelleing (i.e. person vs dog), whereas sigmoid is capable of multi-labelling (i.e. dog and german-shephard).

In any case, the output activations are handled in the Detect() module:
https://github.com/ultralytics/yolov5/blob/f532bc68a9df86e7f64121f2ee94d40187f44231/models/yolo.py#L22

**Comment by ghost** [comment]
Thanks a lot!
