### ISSUE TITLE
concat problem: RuntimeError: Sizes of tensors must match except in dimension 3. Got 11 and 12 (The offending index is 2)

### ISSUE THREAD

**Issue by ZXW2001** [ultralytics/yolov5#11803]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello！ I replace the SPPF module in the yolov5s6.yaml file of yolov5 v7.0 with the following hasppf module, but I encountered some errors and I'm not sure what went wrong. Could you help me? Thank you. 
Specifically, in the hasppf module, there is an "upsample" that converts a （1，128，5，5） tensor to a （1，128，10，10） tensor. However, using this "upsample" leads to an error when validating after the first training epoch. The error message are as follows. If I remove the "upsample" from hasppf and set the parameters of the “Conv” module above the "upsample" to k=1, s=1, p=0, then there are no errors after the first training epoch. 

**My questions are:**
 1. Is the error related to the "upsample"? Could you provide more details?
 2. If I want to add the "upsample" back into hasppf, what should I do to avoid errors?
 3. How to print the torch size of each module's output in the yolov5 model?

**hasppf module in common.py:**
```
class hasppf(nn.Module):
    def __init__(self,c1, c2):
        super().__init__()
        self.cv0 = Conv(c1, 256, 1, 1, 0, 1, 1)
        self.cv1 = Conv(512, 256, 3, 1, 1, 1, 1)
        self.cv2 = Conv(256, 128, 3, 1, 3, 1, 3)
        self.m = nn.MaxPool2d(kernel_size=5, stride=1, padding=2)
        self.cv3 = Conv(512, 128, 3, 2, 1, 1, 1)
        self.cv4 = Conv(768, c2, 1, 1, 0, 1, 1)
        self.upsample = nn.Upsample(scale_factor=2, mode='nearest')
    def forward(self, x):
        y = self.cv0(x)
        z = self.cv1(x)
        w = self.upsample(self.cv3(self.m(x)))
        v = self.cv2(z)
        return self.cv4(torch.cat((y,z,w,v),1))
```
c1 = c2 = 512

**Error message:**
      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
       0/74      1.77G    0.09974    0.02621          0         12        640: 100%|██████████| 67/67 [00:32<00:00,  2.09it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95:   0%|          | 0/6 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 648, in <module>
    main(opt)
  File "train.py", line 537, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 360, in train
    results, maps, _ = validate.run(data_dict,
  File "C:\Users\Lenovo\.conda\envs\yolov5\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "F:\pycharmproject\learn\yolov5-master\yolov5-featurefusion\yolov5-haspp\val.py", line 210, in run
    preds, train_out = model(im) if compute_loss else (model(im, augment=augment), None)
  File "C:\Users\Lenovo\.conda\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "F:\pycharmproject\learn\yolov5-master\yolov5-featurefusion\yolov5-haspp\models\yolo.py", line 209, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "F:\pycharmproject\learn\yolov5-master\yolov5-featurefusion\yolov5-haspp\models\yolo.py", line 121, in _forward_once
    x = m(x)  # run
  File "C:\Users\Lenovo\.conda\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "F:\pycharmproject\learn\yolov5-master\yolov5-featurefusion\yolov5-haspp\models\common.py", line 275, in forward
    return self.cv4(torch.cat((y,z,w,v),1))
RuntimeError: Sizes of tensors must match except in dimension 3. Got 11 and 12 (The offending index is 2)

**When debug train.py:**
![image](https://github.com/ultralytics/yolov5/assets/102674283/9a573c42-f853-4793-aeb4-4d02d2577c24)

### Additional

Python-3.8.16 torch-1.8.0 CUDA:0 (NVIDIA T400, 2048MiB)
--batch-size 4
--img 640

**Comment by glenn-jocher** [comment]
@ZXW2001 hi there! Thanks for reaching out and providing all the relevant information.

Regarding your questions:

1. The error seems to be related to the `torch.cat()` function, specifically in the third dimension (`dimension 3`). The error message indicates that the sizes of the tensors being concatenated in dimension 3 don't match. In your `hasppf` module, you are concatenating tensors `y`, `z`, `w`, and `v`. The sizes of these tensors must be the same in dimension 3. You mentioned that the `upsample` operation converts a `(1, 128, 5, 5)` tensor to a `(1, 128, 10, 10)` tensor. It seems that this is where the size mismatch occurs. Please ensure that the sizes of tensors `y`, `z`, `w`, and `v` are consistent and match in dimension 3 before concatenation.

2. To avoid errors and add the `upsample` operation back into the `hasppf` module, you need to ensure that the output sizes of tensors `y`, `z`, `w`, and `v` match in the third dimension (`dimension 3`) before concatenating them. You may need to adjust the sizes of these tensors or perform additional operations to make them compatible for concatenation.

3. To print the torch size of each module's output in the YOLOv5 model, you can add print statements in the forward function of the model or use the `print` function to output the shapes of the tensors at different stages of the forward pass. For example, you can add `print(x.shape)` statements after each operation in the `forward` method to check the size of `x` at that point.

I hope this helps! Let me know if you have any further questions.

**Comment by ZXW2001** [comment]
Hi ! @glenn-jocher Thank you for your help! So I've tried several times , add the "upsample" back into the "hasppf" module, but i still don't know how to deal with the concat error . It runs successfully in yolo.py. Failed after first training epoch. 
Is there any clue? Thank you very much!

**Comment by glenn-jocher** [comment]
@ZXW2001 You're welcome! It's great to hear that you've been experimenting with adding the "upsample" back into the "hasppf" module. Regarding the concat error, to address this issue, you should carefully verify the dimensions of the tensors being concatenated (`y`, `z`, `w`, and `v`) before the `torch.cat()` operation. Specifically, ensure that the sizes of these tensors match in the third dimension (`dimension 3`) to avoid the concat error. You might need to inspect the output tensor shapes of each component (`y`, `z`, `w`, and `v`) individually in the `forward` method, and reconcile any discrepancies to ensure they are compatible for concatenation.

If you encounter any other issues, don't hesitate to reach out. Good luck, and I'm here to help if needed!
