### ISSUE TITLE
How to get a weight information when the weight is inference? 

### ISSUE THREAD

**Issue by star4s** [ultralytics/yolov5#11822]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to get a weight information when the weight is inference? 
Before inference, I loaded the weight.
After I load the weight, How can I get information of the weight such as class information?
Thank you for your help.

**Comment by glenn-jocher** [comment]
@star4s hello,

Thank you for your question. To get information about the weights after loading them for inference, you can access the "names" attribute of the model. This will give you the class information associated with each weight.

Here's an example code snippet:

```python
import torch
from models import yolov5

# Load the weights
weights = 'path/to/weights.pt'
model = yolov5.load(weights)

# Get the class information
class_info = model.names
print(class_info)
```

The `class_info` variable will contain a list of class names associated with the weights.

I hope this helps! Let me know if you have any further questions.

Kind regards,
Glenn

**Comment by star4s** [comment]
Thank you for your answer.
I followed your instruction. But I cannot run your code.

line 2, in <module>
    from models import yolov5
ImportError: cannot import name 'yolov5'

how can I use the function yolov5.load?

**Comment by glenn-jocher** [comment]
@star4s hello,

Thank you for trying out the code. I apologize for the confusion. It seems that the `yolov5` module is not imported correctly.

To resolve this issue, make sure that the `yolov5` module is in your Python path. You can do this by adding the path to the `yolov5` module to the `sys.path` list before importing it.

Here's an updated code snippet:

```python
import sys
sys.path.append('path/to/yolov5/module')

from models import yolov5

# Load the weights
weights = 'path/to/weights.pt'
model = yolov5.load(weights)

# Get the class information
class_info = model.names
print(class_info)
```

Replace `'path/to/yolov5/module'` in `sys.path.append()` with the actual path to the `yolov5` module. This will ensure that the module is imported correctly.

I hope this resolves the issue. Let me know if you have any further questions.

Kind regards,
Glenn
