### ISSUE TITLE
Is it possible to detect certain classes and then not detect after a time period?

### ISSUE THREAD

**Issue by NevilleMthw** [ultralytics/yolov5#11824]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,

I am trying to create a basic pipeline using the existing ```detect.py``` code. I want to know if it can accommodate an additional feature which acts like a sort of filter. For example, I want the model to detect only person count and then if the person count or person is not in the frame, it should continue with the rest of the detection for the other classes such as remote, wallet, cell phone etc. I am using the ```yolov5x.pt``` weights trained on the COCO dataset. Just want to know if adding such a filter or condition would be possible with the existing code.

Thanks for the help.

Regards,
Neville

**Comment by NevilleMthw** [comment]
I have solved the issue with the use of a simple if-else condition.

**Comment by glenn-jocher** [comment]
@NevilleMthw hi Neville,

Thank you for reaching out. I'm glad to hear that you were able to solve the issue using a simple if-else condition. Indeed, you can use conditional statements in your code to handle specific detection requirements like filtering for a particular class and continuing with the detection for other classes.

In the YOLOv5 repository, we provide a flexible and customizable framework that allows users to modify and extend the code to suit their specific needs. By incorporating conditional statements, you can create your desired pipeline and adjust the behavior of the model accordingly.

If you have any further questions or need assistance with any other aspect of YOLOv5, please feel free to ask. We are here to help!

Best regards,
Glenn Jocher
