### ISSUE TITLE
onnx inference - ending up with too many random predictions, why?

### ISSUE THREAD

**Issue by nbiseb** [ultralytics/yolov5#11847]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I trained a model to detect fluid levels in oil glasses and exported it to onnx format. I end up with a lot of random predictions, even after doing non-max-supression and confidence filtering. When loading the model with torch.hub.load i get exactly 2 prediction, which is what i would expect. Any ideas how to solve this issue?

![image](https://github.com/ultralytics/yolov5/assets/123727774/de641006-39f9-4800-a368-54a03469562a)

**Comment by glenn-jocher** [comment]
@nbiseb hi there! It seems that you are experiencing random predictions when using your trained YOLOv5 model in the ONNX format. This issue can be frustrating, but I'm here to help!

One possible reason for this behavior could be a difference in the post-processing steps between the `torch.hub.load` function and your implementation. Make sure that you are applying non-maximum suppression (NMS) and confidence filtering after making predictions with your ONNX model.

Check if you are using the same parameters for NMS and confidence filtering in both the `torch.hub.load` function and your own implementation. Differences in these parameters can lead to variations in the number and accuracy of the predictions.

Another area to investigate is the input data preprocessing. Double-check that you are preprocessing the input data in the same way when using the ONNX model as when training and evaluating the model.

If the above suggestions don't resolve the issue, please provide more details about your implementation and share a minimal reproducible code snippet. This will help us better understand the problem and provide you with a more specific solution.

It's important to note that YOLOv5 is an open-source project maintained by the YOLO community and the Ultralytics team. We rely on the community's feedback and contributions to improve the model and address any issues. Thank you for your interest and your patience.
