### ISSUE TITLE
What is ultralytics/yolov5's versioning policy?

### ISSUE THREAD

**Issue by Keiku** [ultralytics/yolov5#11842]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Sorry for the newbie question. Let me ask you some questions.
* What is ultralytics/yolov5's versioning policy?
* Does ultralytics produce release notes?
* From which version did you start yolov8? The repository name remains yolov5.
* What were the main factors that led to you uploading to yolov8?

**Comment by glenn-jocher** [comment]
@Keiku hi there!

Thank you for reaching out with your questions. Let me address them for you:

The versioning policy for ultralytics/yolov5 follows [Semantic Versioning](https://semver.org/). This means that each release is assigned a version number in the format of `MAJOR.MINOR.PATCH`, where:

- `MAJOR` increments when there are incompatible API changes,
- `MINOR` increments when functionality is added in a backward-compatible manner, and
- `PATCH` increments when backward-compatible bug fixes are made.

Yes, Ultralytics does produce release notes for each version. You can find the release notes in the [yolov5 GitHub repository](https://github.com/ultralytics/yolov5/releases). These notes detail the changes, enhancements, and bug fixes in each release.

Although the repository name remains yolov5, Ultralytics introduced YOLOv8 as our latest state-of-the-art object detection model. YOLOv8 was designed to offer improved performance, accuracy, and ease of use. The YOLOv8 model builds upon the foundation of YOLOv5 while incorporating new techniques and advancements.

We constantly strive to improve our models, and the development of YOLOv8 was driven by a combination of factors, including advancements in object detection research, feedback from the community and users, and our commitment to pushing the boundaries of what is possible in object detection.

I hope this clarifies your questions. If you have any further inquiries, feel free to ask!

**Comment by Keiku** [comment]
Thank you for your kind comment. I'll check the release notes for past changes.

**Comment by Keiku** [comment]
@glenn-jocher Release notes stop on Nov 23, 2022. I know you are busy, but I would appreciate it if you could post the release notes so that everyone can understand the update.

**Comment by glenn-jocher** [comment]
@Keiku hello! Thank you for your message. I apologize for the missing release notes after November 23, 2022. We understand the importance of keeping the community updated about the changes and enhancements in each release.

We appreciate your patience, and I will make sure to post the release notes for the subsequent updates as soon as possible. Thank you for bringing this to our attention, and we value your contribution to the YOLOv5 community.
