### ISSUE TITLE
The reasoning time change in yolov5 after I added different groupings became very strange.

### ISSUE THREAD

**Issue by wangtao0219** [ultralytics/yolov5#11843]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

According to shufflenet it is affecting the number of visits (MACs), the yolov5 model provides the calculation of FLOPS, is there a way to measure the MACs of the model?

**Comment by glenn-jocher** [comment]
@wangtao0219 hi there,

Thank you for reaching out with your question about measuring the MACs (Multiply–accumulate operations) in the YOLOv5 model. 

Currently, the YOLOv5 model does not provide a built-in calculation for MACs. However, you can estimate the number of MACs by examining the model architecture and the operations involved in each layer. There are also external tools and libraries available, such as the Neural Network Intelligence (NNI) or DeepSpeed libraries, which can assist you in calculating MACs.

Please note that YOLOv5 is a community-driven project, and the Ultralytics team is continually working to improve and enhance the model. If you have any further questions or need assistance, feel free to ask. 

Best,
Glenn Jocher
