### ISSUE TITLE
Changing labels of default YOLOv5 model

### ISSUE THREAD

**Issue by fatihbulbul1** [ultralytics/yolov5#11855]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am using the default YOLOv5m6 model to predict from video for my object detection project. I want to change just some of labels - for example when YOLO detects a "baseball bat", I want it to labeled as "unnecessary" etc. Is there any way I can do it just changing some code, or I should train the model from scratch by just changing labels?

**Comment by fatihbulbul1** [comment]
i found it explained here : https://github.com/ultralytics/yolov5/issues/3577

**Comment by glenn-jocher** [comment]
@fatihbulbul1 thanks for finding the information you needed! The YOLOv5 community strives to provide comprehensive documentation and resources to help users with their projects. If you have any further questions or need assistance, feel free to ask. Keep up the great work!
