### ISSUE TITLE
Acceptable suffix

### ISSUE THREAD

**Issue by ammar3010** [ultralytics/yolov5#11858]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

detect.py was running fine when i cloned the repo but i had to make some changes in the code (only detect.py) to match with my case but it is giving this error:

```
Traceback (most recent call last):
  File "/home/aidev/VectraCom/threat_detection/threat_detection.py", line 7, in <module>
    image,results = main(img=img)
  File "/home/aidev/VectraCom/threat_detection/yolov5/detect.py", line 164, in main
    image,results = run(img)
  File "/home/aidev/anaconda3/envs/t_detect/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/aidev/VectraCom/threat_detection/yolov5/detect.py", line 74, in run
    model = DetectMultiBackend(weights, device=device, dnn=dnn, data=data, fp16=half)
  File "/home/aidev/VectraCom/threat_detection/yolov5/models/common.py", line 335, in __init__
    pt, jit, onnx, xml, engine, coreml, saved_model, pb, tflite, edgetpu, tfjs, paddle, triton = self._model_type(w)
  File "/home/aidev/VectraCom/threat_detection/yolov5/models/common.py", line 607, in _model_type
    check_suffix(p, sf)  # checks
  File "/home/aidev/VectraCom/threat_detection/yolov5/utils/general.py", line 427, in check_suffix
    assert s in suffix, f'{msg}{f} acceptable suffix is {suffix}'

```    

I only changed the way image is inferenced. I passed the image from another file to detect.py after that it stopped working
    

### Environment

- YOLO: YOLOv5 🚀 2023-7-13 Python-3.10.12 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce 940MX, 4044MiB)
- OS: Ubuntu 22.04
- Pyhon: 3.10.4 (conda)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello @ammar3010,

Based on the error you provided, it seems there is an issue with the acceptable suffix for the model weights in your code. The error message indicates that the suffix of the model weights you are using is not compatible.

To resolve this issue, please double-check the suffix of the model weights you are using and ensure that it matches the acceptable suffix specified by YOLOv5. You can find the acceptable suffix in the `check_suffix` function in the `yolov5/utils/general.py` file. Make sure the suffix of your model weights matches one of the accepted suffixes.

If you have made changes to the code in `detect.py`, please review the changes you made and ensure they are not causing any conflicts with the model loading and inference process. Pay special attention to any modifications related to the weights suffix or the model loading code.

If you are still facing issues after following these steps, please provide more details about the changes you made to the code and any relevant code snippets. This will help us better understand the problem and provide you with further assistance.

Let us know if you have any further questions or need more help!

**Comment by ammar3010** [comment]
Thanks. And yes i made some changes to model while making other changes by mistake. It's working now.

**Comment by glenn-jocher** [comment]
@ammar3010 great to hear that you were able to resolve the issue you were facing! Mistakes happen, and it's all part of the learning process. If you have any further questions or need any assistance in the future, don't hesitate to ask. The YOLOv5 community and the Ultralytics team are always here to help.

Happy coding!
