### ISSUE TITLE
yolov5n

### ISSUE THREAD

**Issue by ZCzzzzzz** [ultralytics/yolov5#11854]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I would like to ask what are the differences between yolov5s and yolov5n in version 7.0? For example, which is better in terms of accuracy and inference speed, I looked at the yolov5s.yaml and yolov5n.yaml files respectively, and found that the width_multiple parameters are different, I want to ask yolov5s.pt and yolov5n.pt these two pre-trained weight files are different in terms of network structure? Or is it only the values of the relevant parameters that are different?

**Comment by glenn-jocher** [comment]
@ZCzzzzzz hi there! Thanks for reaching out to us.

In terms of accuracy and inference speed, the differences between yolov5s and yolov5n lie primarily in their network structures and model sizes. The width_multiple parameter you mentioned controls the network width, where yolov5s has a width_multiple of 0.33 and yolov5n has a width_multiple of 0.50.

Regarding the pre-trained weight files, yolov5s.pt and yolov5n.pt do have differences in both network structure and the values of relevant parameters. yolov5n.pt is specifically optimized for improved accuracy, whereas yolov5s.pt is optimized for faster inference speed. 

Feel free to further explore and experiment with these models to find the best fit for your specific use case. Let us know if you have any more questions!

Best regards.
