### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by Taylent** [ultralytics/yolov5#1186]
## ❔Question

Hello, I would like to ask, if our data only has one class, then how should we set and optimize the parameters? We hope to optimize the minimum parameters in the shortest time and get some improvement. How do these parameters(cls, cls_pw, and so on) affect the model?

We look forward to hearing from you soon. Thank you very much.

**Comment by glenn-jocher** [comment]
@Taylent see Hyperparameter Evolution tutorial for this:
https://docs.ultralytics.com/yolov5
