### ISSUE TITLE
Does yolov5-7.0 support rotated bounding boxes?

### ISSUE THREAD

**Issue by Digital2Slave** [ultralytics/yolov5#11877]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I use `label studio v1.8.0`  to label rotated rectangle on my custom dataset. The dataset can be exported with the yolo object detect format.

![image](https://github.com/ultralytics/yolov5/assets/7224107/f8982376-4129-4eae-8f5a-d73a0343eab3)

 
But i'm not sure, does `yolov5-7.0`  support rotated bounding boxes or not?

Any response is appreciate, :handshake: 
 
Thanks a lot in advance!

**Comment by glenn-jocher** [comment]
@Digital2Slave yes, YOLOv5-7.0 does support rotated bounding boxes. You can annotate your dataset with rotated rectangles using `label studio v1.8.0` and export it in the YOLO object detection format. YOLOv5-7.0 is capable of detecting objects with rotated bounding boxes. If you have any further questions or need assistance, feel free to ask.

**Comment by Digital2Slave** [comment]
@glenn-jocher Great job !  Thanks very much.

**Comment by glenn-jocher** [comment]
@Digital2Slave thank you! 🙌 The credit goes to the YOLO community and the amazing Ultralytics team that works hard to maintain and improve YOLOv5. If you have any questions or need further assistance, feel free to ask.

**Comment by chengwuxinlin** [comment]
> @Digital2Slave yes, YOLOv5-7.0 does support rotated bounding boxes. You can annotate your dataset with rotated rectangles using `label studio v1.8.0` and export it in the YOLO object detection format. YOLOv5-7.0 is capable of detecting objects with rotated bounding boxes. If you have any further questions or need assistance, feel free to ask.

Hello, original YOLO output is 4 dimension, if I want to pred the rotated angle, do I need to modify the original model myself?
