### ISSUE TITLE
how to set 

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#1187]
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.

**Comment by glenn-jocher** [comment]
?

**Comment by alicera** [comment]
the log is for  python -m torch.distributed.launch --nproc_per_node 4 train.py --batch-size 128 --data ./data/mydata.yaml --cfg ./models/yolov5s.yaml --weights ''


*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Using CUDA device0 _CudaDeviceProperties(name='GeForce GTX 1080 Ti', total_memory=11178MB)
           device1 _CudaDeviceProperties(name='GeForce GTX 1080 Ti', total_memory=11178MB)
           device2 _CudaDeviceProperties(name='GeForce GTX 1080 Ti', total_memory=11178MB)
           device3 _CudaDeviceProperties(name='GeForce GTX 1080 Ti', total_memory=11178MB)

Namespace(adam=False, batch_size=32, bucket='', cache_images=False, cfg='./models/yolov5s.yaml', data='./data/mydata.yaml', device='', epochs=300, evolve=False, global_rank=0, hyp='data/hyp.scratch.yaml', image_weights=False, img_size=[640, 640], local_rank=0, logdir='runs/', multi_scale=False, name='', noautoanchor=False, nosave=False, notest=False, rect=False, resume=False, single_cls=False, sync_bn=False, total_batch_size=128, weights='', workers=8, world_size=4)
Start Tensorboard with "tensorboard --logdir runs/", view at http://localhost:6006/
Hyperparameters {'lr0': 0.01, 'lrf': 0.2, 'momentum': 0.937, 'weight_decay': 0.0005, 'warmup_epochs': 3.0, 'warmup_momentum': 0.8, 'warmup_bias_lr': 0.1, 'giou': 0.05, 'cls': 0.5, 'cls_pw': 1.0, 'obj': 1.0, 'obj_pw': 1.0, 'iou_t': 0.2, 'anchor_t': 4.0, 'fl_gamma': 0.0, 'hsv_h': 0.015, 'hsv_s': 0.7, 'hsv_v': 0.4, 'degrees': 0.0, 'translate': 0.1, 'scale': 0.5, 'shear': 0.0, 'perspective': 0.0, 'flipud': 0.0, 'fliplr': 0.5, 'mosaic': 1.0, 'mixup': 0.0}


So I have to  "export OMP_NUM_THREADS=4" for using 4GPU?

**Comment by glenn-jocher** [comment]
@alicera see multi-gpu tutorial for instructions
https://docs.ultralytics.com/yolov5
