### ISSUE TITLE
Using ensemble to append models with different classes on inference

### ISSUE THREAD

**Issue by ashleyha** [ultralytics/yolov5#1188]
Apologies if this has been asked before. Is there a way to use the ensembling approach during inference to run multiple models that have been trained on different classes over the same data? 

What I'm seeing is if I run something like this:
`python detect.py --weights model_a.pt model_b.pt --img 640 --source ./inference/images/`

Where model_a has been trained on classes in set a and model_b has been trained on classes in set b, it will detect both a and b but label all the objects as b. Thanks for any pointers.

**Comment by glenn-jocher** [comment]
No, that won’t work. See the Model Ensembling Tutorial for correct usage:
https://docs.ultralytics.com/yolov5

**Comment by ashleyha** [comment]
Great, thank you for the clarification!
