### ISSUE TITLE
about yolov5-ghost.yaml

### ISSUE THREAD

**Issue by graybox123** [ultralytics/yolov5#11883]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, could you please provide the  val result of yolov5-ghost.yaml? I want to use it for comparison. thanks!  :)

**Comment by glenn-jocher** [comment]
@graybox123 sure, I'd be happy to help! Unfortunately, the `yolov5-ghost.yaml` is not a pre-trained model provided by the Ultralytics team. It seems that you might be referring to a custom configuration file. 

For comparison purposes, you can utilize the `yolov5s.yaml` configuration file or any other available pre-trained YOLOv5 model from the Ultralytics YOLOv5 repository. You can find the validation results provided in the repository's documentation and tutorials.

If you have any further questions or need assistance, please feel free to ask. We're here to help!

**Comment by graybox123** [comment]
ok,thankyou

**Comment by glenn-jocher** [comment]
@graybox123 you're welcome! If you have any more questions or need further assistance, feel free to ask. We're here to help!
