### ISSUE TITLE
Invalid SOS parameters for sequential JPEG

### ISSUE THREAD

**Issue by aliaminibagh** [ultralytics/yolov5#11880]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

when use yolo in train custom dataset, I encounter these expressions during training. Can you tell me the reason?

![image](https://github.com/ultralytics/yolov5/assets/59368585/3a9fce50-4202-4ec5-b6e2-50b54b15d2f3)

**Comment by glenn-jocher** [comment]
@aliaminibagh hi,

The error message "Invalid SOS parameters for sequential JPEG" typically occurs when there is an issue with the image file format or it is corrupted. Please make sure that your custom dataset images are in a supported format such as JPEG or PNG. Also, check if the images are not corrupted and can be opened with an image viewer.

If the issue still persists, please provide more information such as the version of YOLOv5 you are using, the steps you followed to train the dataset, and any relevant logs or error messages you encountered. This will help us investigate further.

Additionally, if you have any other questions or need further assistance, feel free to ask.

Thanks!

**Comment by aliaminibagh** [comment]
> @aliaminibagh hi,
> 
> The error message "Invalid SOS parameters for sequential JPEG" typically occurs when there is an issue with the image file format or it is corrupted. Please make sure that your custom dataset images are in a supported format such as JPEG or PNG. Also, check if the images are not corrupted and can be opened with an image viewer.
> 
> If the issue still persists, please provide more information such as the version of YOLOv5 you are using, the steps you followed to train the dataset, and any relevant logs or error messages you encountered. This will help us investigate further.
> 
> Additionally, if you have any other questions or need further assistance, feel free to ask.
> 
> Thanks!

Thanks a lot @glenn-jocher

**Comment by glenn-jocher** [comment]
Hi @aliaminibagh,

The error message "Invalid SOS parameters for sequential JPEG" typically occurs when there is an issue with the image file format or it is corrupted. Please make sure that your custom dataset images are in a supported format such as JPEG or PNG. Also, check if the images are not corrupted and can be opened with an image viewer.

If the issue still persists, please provide more information such as the version of YOLOv5 you are using, the steps you followed to train the dataset, and any relevant logs or error messages you encountered. This will help us investigate further.

Additionally, if you have any other questions or need further assistance, feel free to ask.

Thanks!

Glenn Jocher

**Comment by roscoekerby** [comment]
I used this script to correct my images... They were still viewable and did not appear corrupt, but this fixed the issue.

```
import os
from PIL import Image

def fix_jpeg_sos_parameters(image_folder):
    # Iterate through all files in the directory
    for filename in os.listdir(image_folder):
        # Process only JPEG files
        if filename.endswith(".jpg") or filename.endswith(".jpeg"):
            image_path = os.path.join(image_folder, filename)
            try:
                # Open the image
                with Image.open(image_path) as img:
                    # If the image opens without errors, re-save it
                    img.save(image_path, "JPEG")
                    print(f"Re-saved image {filename} successfully to ensure proper SOS parameters.")
            except Exception as e:
                print(f"Error processing {filename}: {e}")

# Specify your image directory
image_directory = "/content/datasets/Cow Muzzle Yolo Dataset/test/images"

# Run the function
fix_jpeg_sos_parameters(image_directory)
```

**Comment by glenn-jocher** [comment]
Great solution! Re-saving images with PIL can indeed resolve SOS parameter issues. If you encounter further problems, ensure you're using the latest YOLOv5 version. If you have more questions, feel free to ask!
