### ISSUE TITLE
Multiple Questions About Yolov5 Inferencing

### ISSUE THREAD

**Issue by SJavad** [ultralytics/yolov5#11885]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi 🖐
I have multiple Questions about using torch.hub.load for inferencing yolov5 custom models
### 1: how can I Access the X, Y, W, and H of predicted bounding boxes individually? 
I want to get xywh of the predicted bounding boxes for calculating the center of the rectangle. how can I get that? 
### 2: how can I disable the multi-prediction of one class? 
I want to disable the multi-prediction of the class.
for example, I have object-1 and object-goal class and I don't want to detect multiple objects of these and just want to detect one Highest confidence of the class. 
how can I do that? 
### 3: I want to set conditions on the detected classes:
I want to set conditions for detecting objects, for example, I want to say ( if object-1 is detected, then print("Hello World") or something like that.)
how can I do this? 
### 4: I have made a robot It detects the human hand and follows that hand.
something like this:

![image](https://github.com/ultralytics/yolov5/assets/64639184/3fe2c75a-32c7-4cc9-b857-7b2a3c2d0499)

How can I instruct the robot motors to follow the coordinates of the detected rectangle if a human hand is detected?
Should I send the data with the **SERIAL BUS** or **I2C** or **UART** to the robot engines?
I have an Nvidia Jetson board. 
how can I communicate with that motors?

**Comment by glenn-jocher** [comment]
@SJavad hello! Thank you for reaching out with your questions about using torch.hub.load for inferencing YOLOv5 custom models. I'll be happy to help you with them.

1. To access the X, Y, W, and H of predicted bounding boxes individually, you can use the `pred[:,:4]` indexing. This will give you a tensor with the predicted bounding box coordinates in the format [X, Y, W, H].

2. To disable multi-prediction of one class, you can use the `--max-det` command-line argument when running the `detect.py` script. Set it to 1 to detect only the highest confidence object of each class.

3. To set conditions on the detected classes, you can check the predicted class labels using `pred[:, -1]` indexing. You can then use simple if statements or switch cases to perform actions based on the detected classes.

4. For instructing the robot motors to follow the coordinates of the detected rectangle, you will need to establish communication between your Nvidia Jetson board and the motors. The choice of communication protocol, such as SERIAL BUS, I2C, or UART, depends on the specific setup of your robot. You will need to consult the documentation or resources for your robot motors to determine the appropriate communication method and how to send data to control the motors.

I hope this helps! Let me know if you have any further questions.

**Comment by SJavad** [comment]
@glenn-jocher thank you so much for your response 🌸❤

**Comment by SJavad** [comment]
> @SJavad hello! Thank you for reaching out with your questions about using torch.hub.load for inferencing YOLOv5 custom models. I'll be happy to help you with them.
> 
> 1. To access the X, Y, W, and H of predicted bounding boxes individually, you can use the `pred[:,:4]` indexing. This will give you a tensor with the predicted bounding box coordinates in the format [X, Y, W, H].
> 2. To disable multi-prediction of one class, you can use the `--max-det` command-line argument when running the `detect.py` script. Set it to 1 to detect only the highest confidence object of each class.
> 3. To set conditions on the detected classes, you can check the predicted class labels using `pred[:, -1]` indexing. You can then use simple if statements or switch cases to perform actions based on the detected classes.
> 4. For instructing the robot motors to follow the coordinates of the detected rectangle, you will need to establish communication between your Nvidia Jetson board and the motors. The choice of communication protocol, such as SERIAL BUS, I2C, or UART, depends on the specific setup of your robot. You will need to consult the documentation or resources for your robot motors to determine the appropriate communication method and how to send data to control the motors.
> 
> I hope this helps! Let me know if you have any further questions.
@glenn-jocher 
this is my code:
```python
model = torch.hub.load("custom_model.pt")
while True:
     image = cv2.imread('Image_path")
     results = model(image)
     print(results[:,-1])
```
and when I run this code
it gives me an error:
```python
    print(results[:,-1])
TypeError: 'Detections' object is not subscriptable
```
what can I do?

**Comment by glenn-jocher** [comment]
@SJavad the error you are encountering, `'Detections' object is not subscriptable`, suggests that the `results` object returned by the `model(image)` call is not directly subscriptable. 
 
To access the predicted class labels, you can use the `pred` attribute of the `results` object, followed by the `[:, -1]` indexing. Here's an example of how you can modify your code to access the predicted class labels:

```python
model = torch.hub.load("custom_model.pt")
while True:
     image = cv2.imread('Image_path')
     results = model(image)
     print(results.pred[:, -1])
```

By using `results.pred[:, -1]`, you will be able to access the predicted class labels. Let me know if you have any further questions or encounter any issues!

**Comment by SJavad** [comment]
>  @SJavad the error you are encountering, `'Detections' object is not subscriptable`, suggests that the `results` object returned by the `model(image)` call is not directly subscriptable. 
>  
> To access the predicted class labels, you can use the `pred` attribute of the `results` object, followed by the `[:, -1]` indexing. Here's an example of how you can modify your code to access the predicted class labels:
> 
> ```python
> model = torch.hub.load("custom_model.pt")
> while True:
>      image = cv2.imread('Image_path')
>      results = model(image)
>      print(results.pred[:, -1])
> ```
> 
> By using `results.pred[:, -1]`, you will be able to access the predicted class labels. Let me know if you have any further questions or encounter any issues!

Thank you so much 🌸❤️

**Comment by glenn-jocher** [comment]
@SJavad the error message `'Detections' object is not subscriptable` suggests that the `results` object returned by the `model(image)` call is not directly subscriptable. To access the predicted class labels, you can use the `pred` attribute of the `results` object, followed by the `[:, -1]` indexing. Here's an example modification of your code to access the predicted class labels:

```python
model = torch.hub.load("custom_model.pt")
while True:
     image = cv2.imread('Image_path')
     results = model(image)
     print(results.pred[:, -1])
```

Using `results.pred[:, -1]` should allow you to access the predicted class labels. Feel free to reach out if you have any further questions or encounter any issues!

**Comment by SJavad** [comment]
> @SJavad the error message `'Detections' object is not subscriptable` suggests that the `results` object returned by the `model(image)` call is not directly subscriptable. To access the predicted class labels, you can use the `pred` attribute of the `results` object, followed by the `[:, -1]` indexing. Here's an example modification of your code to access the predicted class labels:
> 
> ```python
> model = torch.hub.load("custom_model.pt")
> while True:
>      image = cv2.imread('Image_path')
>      results = model(image)
>      print(results.pred[:, -1])
> ```
> 
> Using `results.pred[:, -1]` should allow you to access the predicted class labels. Feel free to reach out if you have any further questions or encounter any issues!

@glenn-jocher 
Hey 🖐
when I call `print(results.pred[:,-1]) or print(results.pred[:,:4])` it says:
```
print(results.pred[:,-1])
TypeError: list indices must be integers or slices, not tuple
```

**Comment by glenn-jocher** [comment]
@SJavad The error message you encountered, `TypeError: list indices must be integers or slices, not tuple`, indicates that the indexing operation you used on `results.pred` is not in the correct format.

To address this issue, you can modify your code as follows:

```python
print(results.pred[:, -1])
print(results.pred[:, :4])
```

By using square brackets (`[]`) instead of parentheses (`()`) for indexing, you should be able to access the predicted class labels (`results.pred[:, -1]`) and the coordinates (`results.pred[:, :4]`) correctly.

Feel free to reach out if you have any further questions or encounter any issues!
