### ISSUE TITLE
@hojat-ardi hello! Thank you for your interest in YOLOv5 and your question about using Resnet50 as the backbone.

### ISSUE THREAD

**Issue by hojat-ardi** [ultralytics/yolov5#11893]
@hojat-ardi hello! Thank you for your interest in YOLOv5 and your question about using Resnet50 as the backbone.

To use Resnet50 as the backbone in YOLOv5, you need to make modifications to the YOLOv5 code. Here are the general steps:

1. Locate the `models\models.py` file in the YOLOv5 repository.
2. In this file, you will find a section that defines the backbone architecture. Look for the `CSPDarknet` or `CSPResNet` class, depending on the YOLOv5 version you are using.
3. Replace the existing backbone with the Resnet50 architecture. You can use the torchvision implementation of Resnet50 or any other implementation that suits your needs. Make sure the input and output shapes of the backbone match the expected input and output shapes of the YOLOv5 model.
4. Update the `forward()` method of the model to account for the changes. Adjust the forward pass to include the necessary connections between the backbone and the head of the YOLOv5 model.

Keep in mind that making such changes may require additional modifications to ensure the compatibility of the model. You might need to adjust the shape/stride constraints and handle any errors or inconsistencies that arise.

Please note that while this approach can be used as a starting point, it requires careful consideration and testing to ensure that the modified model functions correctly.

I hope this helps! If you have any further questions, please let me know.

_Originally posted by @glenn-jocher in https://github.com/ultralytics/yolov5/issues/6003#issuecomment-1622813281_

**Comment by glenn-jocher** [comment]
@hojat-ardi to use Resnet50 as the backbone in YOLOv5, you need to make modifications to the YOLOv5 code. Here are the general steps:

1. Locate the `models\models.py` file in the YOLOv5 repository.
2. In this file, you will find a section that defines the backbone architecture. Look for the `CSPDarknet` or `CSPResNet` class, depending on the YOLOv5 version you are using.
3. Replace the existing backbone with the Resnet50 architecture. You can use the torchvision implementation of Resnet50 or any other implementation that suits your needs. Make sure the input and output shapes of the backbone match the expected input and output shapes of the YOLOv5 model.
4. Update the `forward()` method of the model to account for the changes. Adjust the forward pass to include the necessary connections between the backbone and the head of the YOLOv5 model.

Keep in mind that making such changes may require additional modifications to ensure the compatibility of the model. You might need to adjust the shape/stride constraints and handle any errors or inconsistencies that arise.

Please note that while this approach can be used as a starting point, it requires careful consideration and testing to ensure that the modified model functions correctly.

I hope this helps! If you have any further questions, please let me know.

**Comment by hojat-ardi** [comment]
thank you so much

**Comment by glenn-jocher** [comment]
@hojat-ardi you're welcome! If you have any more questions or need further assistance, feel free to reach out. Happy coding! 😊👍

**Comment by Shikusora** [comment]
hello @glenn-jocher , i am a beginner and i would like to ask on which specific lines do i need to replace so that it would be possible to use resnet50 on yolov5? thank you so much and have a great day ahead

**Comment by glenn-jocher** [comment]
Hello! 😊 To integrate Resnet50 as the backbone for YOLOv5, you won't be replacing specific lines but rather adjusting parts of the model definition in `models\models.py`. 

Primarily, you'll work on modifying the backbone architecture defined in the model class. This involves:

1. Substituting the `CSPDarknet` or similar class with your Resnet50 implementation.

2. Ensuring the Resnet50 backbone outputs are correctly integrated with the YOLOv5 head – adjusting the `forward()` function as necessary.

Since implementations can vary, I can't point to specific lines to replace. The key is ensuring the input/output dimensions of Resnet50 match what YOLOv5 expects for seamless integration. It's a bit of a custom job, so diving into the code and understanding the model architecture will be crucial.

Remember, such modifications require testing and fine-tuning. Don't hesitate to ask if you need further clarification!

Have a wonderful day too!

**Comment by omkar-chaubal-45** [comment]
> @hojat-ardi to use Resnet50 as the backbone in YOLOv5, you need to make modifications to the YOLOv5 code. Here are the general steps:
> 
> 1. Locate the `models\models.py` file in the YOLOv5 repository.
> 2. In this file, you will find a section that defines the backbone architecture. Look for the `CSPDarknet` or `CSPResNet` class, depending on the YOLOv5 version you are using.
> 3. Replace the existing backbone with the Resnet50 architecture. You can use the torchvision implementation of Resnet50 or any other implementation that suits your needs. Make sure the input and output shapes of the backbone match the expected input and output shapes of the YOLOv5 model.
> 4. Update the `forward()` method of the model to account for the changes. Adjust the forward pass to include the necessary connections between the backbone and the head of the YOLOv5 model.
> 
> Keep in mind that making such changes may require additional modifications to ensure the compatibility of the model. You might need to adjust the shape/stride constraints and handle any errors or inconsistencies that arise.
> 
> Please note that while this approach can be used as a starting point, it requires careful consideration and testing to ensure that the modified model functions correctly.
> 
> I hope this helps! If you have any further questions, please let me know.

Hi there! I followed this. However, it throws an error:  AttributeError: 'DetectionModel' object has no attribute 'stride' .
How to solve this?
