### ISSUE TITLE
Image not found yolo v8l

### ISSUE THREAD

**Issue by puneet2059** [ultralytics/yolov5#11890]
I am training a yolo v8l model with input image 512*512 (3400 images) .
Model will run for 35 epochs and then show 

AssertionError                            Traceback (most recent call last)
[<ipython-input-2-3f8ccf2d3a02>](https://localhost:8080/#) in <cell line: 3>()
      1 from ultralytics import YOLO
      2 model=YOLO("yolov8l.yaml")
----> 3 results=model.train(data="/content/drive/MyDrive/Colab Notebooks/yolo/data.yaml",epochs=50,batch=2)

7 frames
[/usr/local/lib/python3.10/dist-packages/torch/_utils.py](https://localhost:8080/#) in reraise(self)
    642             # instantiate since we don't know how to
    643             raise RuntimeError(msg) from None
--> 644         raise exception
    645 
    646 

AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/data/base.py", line 180, in __getitem__
    return self.transforms(self.get_label_info(index))
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/data/base.py", line 184, in get_label_info
    label["img"], label["ori_shape"], label["resized_shape"] = self.load_image(index)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/data/base.py", line 123, in load_image
    assert im is not None, f"Image Not Found {f}"
AssertionError: Image Not Found /content/drive/MyDrive/Colab Notebooks/yolo/train/images/sub_image_1_0_IMG_0393.JPG

This error keeps changing with different image names, but when I check my images and label folder, everything is there. I referred to previously given solutions like removing the cache file if present and checking the presence of image and the right format.
But everything looks pefect.

**Comment by glenn-jocher** [comment]
@puneet2059 make sure to verify that the image paths in your dataset configuration file (`data.yaml`) are correct. The error message suggests that the DataLoader is unable to find the image at the specified path (`/content/drive/MyDrive/Colab Notebooks/yolo/train/images/sub_image_1_0_IMG_0393.JPG`).

Please double-check the following:
- The image file exists in the specified directory.
- The file name is spelled correctly, including the file extension.
- The path is correctly specified in the `data.yaml` file.

If you have confirmed that the image paths are correct, try printing out some of the image paths during data loading to see if there is anything unusual. You can add a few lines of code to YOLOv5's `load_image` function to print the image path before the assertion:

```python
...
def load_image(self, index):
    image_path = self.image_files[index]  # Add this line to print the image path
    print(f"Loading image: {image_path}")
    im = ...
    ...
```

Please let me know if you continue to encounter issues or need any further assistance.

**Comment by puneet2059** [comment]
hi I did this to check whether I have all the files or not 
import os

def check_files_exist(image_folder, label_folder):
    image_files = os.listdir(image_folder)
    label_files = os.listdir(label_folder)
    
    missing_images = []
    missing_labels = []
    
    for image_file in image_files:
        image_path = os.path.join(image_folder, image_file)
        label_file = image_file.replace(".jpg", ".txt")
        label_path = os.path.join(label_folder, label_file)
        
        if not os.path.exists(image_path):
            missing_images.append(image_file)
        
        if not os.path.exists(label_path):
            missing_labels.append(label_file)
    
    return missing_images, missing_labels

# Example usage:
images_folder = "/content/drive/MyDrive/Colab Notebooks/train/images"
labels_folder = "/content/drive/MyDrive/Colab Notebooks/train/labels"

missing_images, missing_labels = check_files_exist(images_folder, labels_folder)

if len(missing_images) > 0:
    print("Missing image files:")
    for image_file in missing_images:
        print(image_file)

if len(missing_labels) > 0:
    print("Missing label files:")
    for label_file in missing_labels:
        print(label_file)
it is showing names of the missing label with respect to images but  if I search for these files in my drive they are present there with the proper label and images,
 what should I do ?

**Comment by glenn-jocher** [comment]
@puneet2059 it seems that the code you provided is correctly checking for missing image and label files in the specified directories. However, it is strange that the missing files are being reported even though they are present in your drive.

To troubleshoot this issue, I recommend the following steps:

1. Double-check the file paths: Verify that the `images_folder` and `labels_folder` variables in your code accurately point to the correct directory where the image and label files are located. Make sure there are no typos or incorrect paths.

2. Confirm the file extensions: Ensure that the file extensions for the images and labels match the expected format. In your code, you are checking for images with the ".jpg" extension and corresponding label files with the ".txt" extension. Make sure the actual files have the correct extensions.

3. Check for case sensitivity: File system behavior can vary depending on the operating system. Ensure that the filenames and paths in your code match the case sensitivity of the actual files in your drive. For example, if your code is looking for "image.jpg" but the file is actually named "Image.jpg", it may not be recognized.

4. Verify permissions: Make sure you have read permissions for the directories and files in question. If the files are located in a different directory or accessible only to specific users, you may encounter issues when trying to access them.

If you have completed these steps and are still experiencing the issue, please provide more context or additional code snippets that may help us understand and debug the problem further.

**Comment by puneet2059** [comment]
AssertionError                            Traceback (most recent call last)
[<ipython-input-3-ecbc69cec875>](https://localhost:8080/#) in <cell line: 7>()
      5 
      6 # Train the model
----> 7 results = model.train(data="/content/drive/MyDrive/Colab Notebooks/data.yaml", epochs=50)
      8 
      9 

7 frames
[/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/engine/model.py](https://localhost:8080/#) in train(self, **kwargs)
    205             self.trainer.model = self.trainer.get_model(weights=self.model if self.ckpt else None, cfg=self.model.yaml)
    206             self.model = self.trainer.model
--> 207         self.trainer.train()
    208         # update model and cfg after training
    209         self.model, _ = attempt_load_one_weight(str(self.trainer.best))

[/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/engine/trainer.py](https://localhost:8080/#) in train(self)
    181                 ddp_cleanup(command, self)
    182         else:
--> 183             self._do_train(int(os.getenv("RANK", -1)), world_size)
    184 
    185     def _setup_ddp(self, rank, world_size):

[/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/engine/trainer.py](https://localhost:8080/#) in _do_train(self, rank, world_size)
    282             self.tloss = None
    283             self.optimizer.zero_grad()
--> 284             for i, batch in pbar:
    285                 self.run_callbacks("on_train_batch_start")
    286                 # Warmup

[/usr/local/lib/python3.10/dist-packages/tqdm/std.py](https://localhost:8080/#) in __iter__(self)
   1176 
   1177         try:
-> 1178             for obj in iterable:
   1179                 yield obj
   1180                 # Update and possibly print the progressbar.

[/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py](https://localhost:8080/#) in __next__(self)
    631                 # TODO(https://github.com/pytorch/pytorch/issues/76750)
    632                 self._reset()  # type: ignore[call-arg]
--> 633             data = self._next_data()
    634             self._num_yielded += 1
    635             if self._dataset_kind == _DatasetKind.Iterable and \

[/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py](https://localhost:8080/#) in _next_data(self)
   1343             else:
   1344                 del self._task_info[idx]
-> 1345                 return self._process_data(data)
   1346 
   1347     def _try_put_index(self):

[/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py](https://localhost:8080/#) in _process_data(self, data)
   1369         self._try_put_index()
   1370         if isinstance(data, ExceptionWrapper):
-> 1371             data.reraise()
   1372         return data
   1373 

[/usr/local/lib/python3.10/dist-packages/torch/_utils.py](https://localhost:8080/#) in reraise(self)
    642             # instantiate since we don't know how to
    643             raise RuntimeError(msg) from None
--> 644         raise exception
    645 
    646 

AssertionError: Caught AssertionError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/data/base.py", line 180, in __getitem__
    return self.transforms(self.get_label_info(index))
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/data/base.py", line 184, in get_label_info
    label["img"], label["ori_shape"], label["resized_shape"] = self.load_image(index)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/data/base.py", line 123, in load_image
    assert im is not None, f"Image Not Found {f}"
AssertionError: Image Not Found /content/drive/MyDrive/Colab Notebooks/train/images/sub_image_0_3_IMG_0486.JPG
still facing same error but at 47 epoch it keeps on changing I checked everything.

**Comment by puneet2059** [comment]
do you think changing image and label name can help ?
for example :sub_image_0_0_IMG_0193 to IMG0193

**Comment by glenn-jocher** [comment]
@puneet2059 changing the image and label names may help resolve the issue you are facing. By simplifying the names and removing special characters, you can eliminate any potential file naming discrepancies that might cause the DataLoader to fail in finding the images.

I suggest modifying the names to a simple format, such as 'IMG0193.jpg' for the image and 'IMG0193.txt' for the corresponding label. Ensure that both the image and label files have the same base name and appropriate extensions.

After making the changes, update your dataset configuration file (`data.yaml`) to reflect the new file names. Verify that the `image_folder` and `label_folder` paths in your code also match the updated file names.

Once you have made these adjustments, try running the training process again and see if the error persists.

Let me know if you have any further questions or encounter any other issues.

**Comment by puneet2059** [comment]
But there is one thing that I have already run this model on the same images but at that time they were unprocessed and then it was working. But now it is very weird that I am getting this error.

**Comment by glenn-jocher** [comment]
@puneet2059 hi,

It's strange that you are encountering this error after running the model on the same images without any issues before. It's possible that some changes or processing done to the images may be causing the problem.

To troubleshoot this issue, I recommend the following steps:

1. Verify the changes: Review any recent modifications or processing steps applied to the images. Check if any transformations or resizing could potentially impact the loading of images in the training process.

2. Confirm the image format: Ensure that the images are in a compatible format supported by YOLOv5 (e.g., JPEG or PNG). If the images were converted to a different format or have unusual file extensions, it may cause the DataLoader to fail.

3. Check the image paths: Double-check that the image paths specified in your dataset configuration file (`data.yaml`) are correct and match the new image names or directory structure.

4. Validate the data preprocessing: Verify that the data preprocessing steps applied to the images are correctly handled and synchronized with the training process. Ensure that any resizing, cropping, or augmentation operations are properly implemented and do not cause image loading issues.

By carefully reviewing these factors, you should be able to pinpoint the cause of the error and resolve it. If you have any further questions or need additional assistance, please don't hesitate to ask.

Thank you.

**Comment by puneet2059** [comment]
Is it by any chance that since I am using free version of google collab and that's the reason why its showing error after sometime ?

**Comment by glenn-jocher** [comment]
@puneet2059 hi there,

Using the free version of Google Colab should not be the cause of the error you are experiencing while running YOLOv5. The free version of Google Colab provides limited computational resources, such as GPU and storage space, but it should not impact the functionality or stability of the model itself.

The error you are facing might be related to other factors, such as incorrect image or label file paths, unsupported image formats, or issues with the data preprocessing steps. I recommend double-checking these aspects to ensure everything is set up correctly.

If you are still encountering the error after verifying these factors, please provide more details, such as the specific error message or traceback, any recent changes you made to the code or data, and any other relevant information. This will help us further investigate and assist you in resolving the issue.

Let me know if you have any more questions or need additional help.

Thank you.

**Comment by puneet2059** [comment]
I tried again with same image name but the only difference was that i used 1300 images and it ran successfully with 50 epochs .

**Comment by glenn-jocher** [comment]
@puneet2059 hi there,

That's great to hear that you were able to run the YOLOv5 model successfully with 1300 images and 50 epochs! It's possible that the previous error you encountered was specific to the image processing or data loading for a particular subset of images.

If you encounter any further issues or have any questions, feel free to ask. We're here to assist you.

Thank you.

**Comment by yiluzhou1** [comment]
I did have exactly the same issue "AssertionError: Image Not Found" after a certain number of epochs. With the same dataset in the folder, for most times, it can run successfully for 150 epochs... Not sure why sometimes it stuck after several epochs at a random Image Not Found. I've verified that the image file did exist there.
I've searched around, and found many people have the same issue. I wonder if it is concurrency issue, I'll try num_workers=1, and see if this problem can go away.

**Comment by puneet2059** [comment]
I tried this with Google Colab plus it worked fine every time I run. That's the only change I did.

**Comment by glenn-jocher** [comment]
@yiluzhou1 hi there,

Thank you for sharing your experience with running YOLOv5 on Google Colab. It's great to hear that you were able to run it successfully without encountering the "Image Not Found" issue.

In some cases, running the code on different platforms or environments can have an impact on the execution and stability of the training process. It's possible that the issue you encountered previously may have been specific to your local setup.

If you have any further questions or concerns, feel free to reach out. We're here to assist you.

Thank you.

**Comment by yiluzhou1** [comment]
> @yiluzhou1 hi there,
> 
> Thank you for sharing your experience with running YOLOv5 on Google Colab. It's great to hear that you were able to run it successfully without encountering the "Image Not Found" issue.
> 
> In some cases, running the code on different platforms or environments can have an impact on the execution and stability of the training process. It's possible that the issue you encountered previously may have been specific to your local setup.
> 
> If you have any further questions or concerns, feel free to reach out. We're here to assist you.
> 
> Thank you.



> @yiluzhou1 hi there,
> 
> Thank you for sharing your experience with running YOLOv5 on Google Colab. It's great to hear that you were able to run it successfully without encountering the "Image Not Found" issue.
> 
> In some cases, running the code on different platforms or environments can have an impact on the execution and stability of the training process. It's possible that the issue you encountered previously may have been specific to your local setup.
> 
> If you have any further questions or concerns, feel free to reach out. We're here to assist you.
> 
> Thank you.

Thanks for your response! I've tried num_workers=1, the "Image Not Found" issue persists occasionally. Unfortunately, I couldn't use other platforms or Google Colab, as I'm doing training on internal clinical images. Probably I can add "try... except" in dataloaders.py to bypass this error in case of unsuccessful read images.

**Comment by glenn-jocher** [comment]
@yiluzhou1 thanks for your response! It's unfortunate that the "Image Not Found" issue still persists occasionally even after trying `num_workers=1`. Considering your specific use case with internal clinical images, using other platforms or Google Colab may not be feasible.

One possible approach to handle the "Image Not Found" issue is to add a `try... except` block in the `dataloader.py` file. By implementing error handling, you can bypass the error and continue the training process even in cases where the images are not successfully read.

Feel free to give this approach a try and let us know if it resolves the issue for you. If you have any further questions or need additional assistance, feel free to ask. We're here to help.

Thank you.

**Comment by vahidajalluian** [comment]
To the team developing this library, this damn problem is due to the libpng version you have used, we have also encountered this problem and after some search, we have found that this is the problem of libpng that cannot open the image on "Windows OS". So we changed all of our images to jpg format and now we can train without interruption.

**Comment by pderrenger** [comment]
@vahidajalluian thank you for sharing your findings! It's helpful to know that converting images to JPG format resolved the issue for you on Windows OS. If others encounter similar problems, this is a great workaround to try. For further troubleshooting, ensure you're using the latest YOLOv5 version and dependencies. For more guidance, refer to the [YOLO Common Issues](https://docs.ultralytics.com/guides/yolo-common-issues/).
