### ISSUE TITLE
How to train video object detection with yolov5

### ISSUE THREAD

**Issue by 15114842111** [ultralytics/yolov5#11892]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I would like to know the directory of the images and the annotations when we train videos object detection with yolov5. Thanks to answer me.

**Comment by glenn-jocher** [comment]
@15114842111 to train video object detection with YOLOv5, you should follow the same data organization as for image object detection. You will need both the image frames and their corresponding annotations.

The directory structure for training videos typically includes two folders:
1. **Images folder**: This folder contains individual image frames extracted from the video. Each image should have a corresponding annotation file.
2. **Annotations folder**: This folder contains the annotation files for the image frames. Each annotation file should follow the same format as the image annotation files for image object detection.

Make sure to appropriately label your video frames and annotations to maintain consistency across the dataset.

If you have any more questions, feel free to ask.
