### ISSUE TITLE
Yolov5 inference ready model support

### ISSUE THREAD

**Issue by lexical-yoda** [ultralytics/yolov5#11898]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is there any way to convert the trained yolov5 model on custom data to be exported into a single pytorch model that can be loaded and inferred with a simple torch.load model object

**Comment by glenn-jocher** [comment]
@lexical-yoda yes, you can convert your trained YOLOv5 model on custom data into a single PyTorch model that can be loaded and used for inference with just a torch.load model object. 

To achieve this, you can use the `export.py` script provided in the YOLOv5 repository. This script allows you to export a trained model into various formats, including TorchScript and ONNX.

For exporting to a TorchScript model, you can run the following command:

```bash
python export.py --weights path/to/weights.pt --img size --batch 1
```

Replace `path/to/weights.pt` with the path to your trained YOLOv5 weights file. The `--img size` flag specifies the input image size, and `--batch 1` sets the batch size to 1.

After running the export script, you will get a `yolov5s.torchscript.pt` file that you can load using `torch.jit.load` and use for inference.

Please note that the exported model will be in a TorchScript format, not exactly a single PyTorch model file. However, you can use it in your code as a model object and perform inference as desired.

Feel free to reach out if you have any further questions or need additional assistance.
