### ISSUE TITLE
Question about weights parameter and transfer learning

### ISSUE THREAD

**Issue by EmreBasar1** [ultralytics/yolov5#11901]
### Question

1- When we train with --weights parameter is ' ', does it train from strach ( means no weights used ) or does it use anything pre trained ( not weights but some other things )

2- How can we do transfer learning, which parameters should we use ?

**Comment by glenn-jocher** [comment]
@EmreBasar1 1. When training with the `--weights` parameter set to an empty string (`''`), YOLOv5 trains the model from scratch without using any pre-trained weights. It initializes the model with random weights and learns from the provided dataset.

2. To perform transfer learning, you can use pre-trained weights as a starting point and fine-tune the model on your specific task or dataset. To do this, provide the path to the pre-trained weights using the `--weights` parameter. Additionally, you can freeze certain layers to prevent them from being updated during training by using the `--freeze` parameter. This allows the model to retain the knowledge learned from the pre-training while adapting to your specific task.

Let me know if you have any further questions!
