### ISSUE TITLE
Yolov5 with Albumentations

### ISSUE THREAD

**Issue by yeongnamtan** [ultralytics/yolov5#11904]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

when I run train.py, I get below.... is albumentations turned on ?? what does 'always_apply' mean ? Do I need to specify albumentations when I run training

albumentations: Blur(always_apply=False, p=0.01, blur_limit=(3, 7)), MedianBlur(always_apply=False, p=0.01, blur_limit=(3, 7)), ToGray(always_apply=False, p=0.01), CLAHE(always_apply=False, p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8)), RandomBrightnessContrast(always_apply=False, p=0.01, brightness_limit=(-0.2, 0.2), contrast_limit=(-0.2, 0.2), brightness_by_max=True)

Same question for hyperparameter augmentations.  Do I need to specify anything in hyp.scratch.yaml

**Comment by PawelKinczyk** [comment]
As i know if you have installed library "Albumentation" the augmentation apply automatically... Look at the [augmentation.py](https://github.com/ultralytics/yolov5/blob/def7a0fd19c1629903c3b073b4df265407719a07/utils/augmentations.py#L16-L17). Here i have a question it is possible to switch off augmentation with "albumentation" and "hyp.no-augmentation.yaml" at once without changing the code in yolov5? I have augmented data and don't want to augment them again...???

**Comment by glenn-jocher** [comment]
@PawelKinczyk yes, you are correct that if you have the Albumentations library installed, the augmentations specified in `augmentation.py` will be applied automatically during training. However, if you do not want to apply any augmentations and use the augmented data directly, you can switch off the augmentations by using the `--nosave` flag when running `train.py`. This flag will disable saving augmented images.

Regarding the `hyp.no-augmentation.yaml` file, it is not directly related to Albumentations but rather specifies hyperparameters for training. If you don't want to apply any augmentations, you don't need to make any changes to this file.

Please note that the Albumentations library and the hyperparameters defined in `hyp.scratch.yaml` are independent of each other. If you have specific requirements for hyperparameter augmentations, you can modify the `hyp.scratch.yaml` file accordingly.

I hope this clarifies your concerns. If you have any further questions, feel free to ask.

**Comment by PawelKinczyk** [comment]
@glenn-jocher  thank you! Ok i will have one more question. YOLO with augmentation hyper parameters / or using albumentation creates another images or just change input image with sat chance?

**Comment by glenn-jocher** [comment]
@yeongnamtan you're welcome! In YOLOv5, the augmentations specified in the hyperparameters or implemented with Albumentations are applied to the input images during training. These augmentations can modify the appearance of the images by applying transformations such as blurring, brightness/contrast adjustments, or color shifts.

However, it's important to note that these augmentations do not create additional images. Instead, they modify the original images on-the-fly before they are fed into the model for training. This allows the model to learn from a diverse set of augmented images, which can improve its ability to handle variations in real-world data.

If you have any more questions, feel free to ask!

**Comment by PawelKinczyk** [comment]
thanks a lot!

**Comment by glenn-jocher** [comment]
@PawelKinczyk thanks for using YOLOv5! We're glad you're finding it useful for your project. The albumentations mentioned in the output are a set of augmentations that can be applied to your training data when using YOLOv5.

The `always_apply` parameter determines if the augmentation is always applied to the data or if it is only applied with a certain probability (`p`) value. For example, if `always_apply` is set to False and `p` is set to 0.01, the augmentation will be applied with a 1% chance.

Regarding the hyperparameter augmentations, you don't need to specify anything in the `hyp.scratch.yaml` file for albumentations. The `hyp.scratch.yaml` file contains hyperparameters for training, while the augmentations are controlled in the `augmentation.py` file.

If you have more questions or need further assistance, please feel free to ask. We're here to help!

**Comment by yeongnamtan** [comment]
What does the 1% chance mean ?


The always_apply parameter determines if the augmentation is always applied
to the data or if it is only applied with a certain probability (p) value.
For example, if always_apply is set to False and p is set to 0.01, the
augmentation will be applied with a 1% chance.

**Comment by glenn-jocher** [comment]
@yeongnamtan the `always_apply` parameter in the Albumentations library determines whether an augmentation is always applied to the data or if it is applied with a certain probability (`p`) value. When `always_apply` is set to `False` and `p` is set to `0.01`, it means that the augmentation will be applied with a 1% chance. This allows for a random application of the augmentation during training.

If you have more questions or need further clarification, feel free to ask. We're here to assist you!

**Comment by yeongnamtan** [comment]
What do u mean when you say augmentation is applied with 1% chance?

**Comment by glenn-jocher** [comment]
@yeongnamtan the `always_apply` parameter in the Albumentations library determines whether an augmentation is always applied to the data or if it is applied with a certain probability (`p`) value. When `always_apply` is set to `False` and `p` is set to `0.01`, it means that the augmentation will be applied with a 1% chance. This allows for a random application of the augmentation during training.

If you have any further questions or need additional clarification, please feel free to ask. We're here to assist you!

**Comment by yeongnamtan** [comment]
Could you help me understand what do u mean by "applied with a 1% chance"?

**Comment by glenn-jocher** [comment]
@yeongnamtan the "applied with a 1% chance" means that when the `always_apply` parameter is set to `False` and the `p` parameter is set to `0.01`, the augmentation will be applied randomly to the data with a probability of 1%. In other words, for each image, there is a 1% chance that this specific augmentation will be applied during training.

This random application of augmentations helps to introduce diversity in the training data, allowing the model to learn from a wider range of variations and improve its robustness. If you have any further questions, feel free to ask!

**Comment by yeongnamtan** [comment]
Thank you so much for the explanation. 
Does this mean 1% of all images will have this augmentation?



"there is a 1% chance that this specific augmentation will be applied during training".

**Comment by glenn-jocher** [comment]
@yeongnamtan yes, that's correct. When the augmentation is specified with a `p` value of 0.01, it means that there is a 1% chance that this specific augmentation will be applied to each individual image during training. This random application allows for a varied and diverse set of augmented images, which can improve the model's ability to handle different variations in real-world data. If you have any more questions, feel free to ask!

**Comment by yeongnamtan** [comment]
@glenn-jocher Thank u very much

**Comment by glenn-jocher** [comment]
@yeongnamtan you're welcome! I'm glad I could assist you. If you have any more questions or need further help, feel free to ask. The YOLOv5 community and the Ultralytics team are here to support you.
