### ISSUE TITLE
True Positive,False Negative,Flase positive 

### ISSUE THREAD

**Issue by Sarthak2426** [ultralytics/yolov5#11917]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to get the tp,fp and fn?

### Additional

Respected authority, i need to ask that how i can print the fp,tp,fn rate and also sir i want to get the ground truth vs prediction so that i can get to know about the total number of object in ground truth and from there how many the model is able to  able to predict. Kindly help me out please  and also i have tried to change the normalize=False also but its not working my dataset has 2 classes.

**Comment by glenn-jocher** [comment]
@Sarthak2426 the true positive (TP), false positive (FP), and false negative (FN) rates can be calculated using the performance metrics provided by the YOLOv5 API. To obtain these rates, you can follow these steps:

1. After running the YOLOv5 `detect.py` script, you will get the results in the form of bounding boxes and class predictions.

2. You can compare these predictions with the ground truth annotations to calculate the TP, FP, and FN rates.

3. Iterate through each predicted bounding box and compare it with the ground truth annotations. If there is a match (i.e., the predicted class and the ground truth class are the same), it is a TP. If there is no match, it is an FP. If there is a ground truth annotation with no predicted bounding box, it is an FN.

4. Keep track of these counts and calculate the rates as follows:
   - TP Rate: TP / (TP + FN)
   - FP Rate: FP / (FP + TN) (TN is the number of true negatives, which is not relevant in object detection)

Regarding obtaining the ground truth vs. prediction counts, you can follow a similar procedure as above. Iterate through the ground truth annotations and compare them with the predicted bounding boxes. Count the number of predicted bounding boxes that match each ground truth annotation. This will give you the total number of objects in the ground truth and the number of objects predicted by the model.

I hope this helps! Let me know if you have any further questions.

**Comment by Sarthak2426** [comment]
@glenn-jocher  thank you sir for the response. sir if we have more then more images doing manually will be time consuming and confusing also. can u help in that case please.

**Comment by glenn-jocher** [comment]
@Sarthak2426, thank you for reaching out! I understand that manually calculating the TP, FP, and FN rates can be time-consuming and confusing, especially if you have a large number of images. 

To automate this process, you can use evaluation scripts provided by the YOLOv5 community. These scripts can help you calculate the performance metrics for your object detection model.

One popular script is the `cocoapi` evaluation script, which can be found in the `ultralytics/yolov5` GitHub repository under `val.py`. This script allows you to evaluate your model using the COCO dataset format and provides metrics such as average precision (AP), mean average precision (mAP), and recall.

To use the `val.py` script, you need to format your ground truth annotations and predictions in the COCO dataset format. Once you have done that, you can run the script to obtain the desired performance metrics.

I hope this helps! Feel free to let me know if you have any further questions or need any additional assistance.

**Comment by Sarthak2426** [comment]
> @Sarthak2426, thank you for reaching out! I understand that manually calculating the TP, FP, and FN rates can be time-consuming and confusing, especially if you have a large number of images.
> 
> To automate this process, you can use evaluation scripts provided by the YOLOv5 community. These scripts can help you calculate the performance metrics for your object detection model.
> 
> One popular script is the `cocoapi` evaluation script, which can be found in the `ultralytics/yolov5` GitHub repository under `val.py`. This script allows you to evaluate your model using the COCO dataset format and provides metrics such as average precision (AP), mean average precision (mAP), and recall.
> 
> To use the `val.py` script, you need to format your ground truth annotations and predictions in the COCO dataset format. Once you have done that, you can run the script to obtain the desired performance metrics.
> 
> I hope this helps! Feel free to let me know if you have any further questions or need any additional assistance.

thank you sir . sorry for the inconvenience one question like while training we use yolov5 format from roboflow so i need to do the same thing but using the format COCO

**Comment by glenn-jocher** [comment]
@Sarthak2426 using the COCO dataset format for evaluation is slightly different from the YOLOv5 format used during training. However, you can easily convert your ground truth annotations and predictions to the COCO format using the `--save-json` flag provided by the YOLOv5 `val.py` script.

Here's how you can do it:

1. Run the `val.py` script with the `--save-json` flag and specify an output directory to save the COCO-formatted JSON files. For example:
```
python val.py --data <data.yaml> --weights <weights.pth> --save-json --task <task> --json-folder <output_dir>
```

2. After running the script, you will find the COCO-formatted JSON files in the specified `output_dir`. These files will contain the ground truth annotations and predictions for each image.

3. You can then use these JSON files to evaluate your model using the COCO evaluation script, such as the one provided by the `cocoapi`. This script will calculate metrics like AP, mAP, and recall for your model's performance.

I hope this clarifies the process of using the COCO format for evaluation. If you have any further questions or need assistance, please feel free to ask!

**Comment by Sarthak2426** [comment]
@glenn-jocher . thank you so much for your time and effort sir . sir last question how we can use the val.py on video sir which is a totally unseen data for model

**Comment by glenn-jocher** [comment]
@Sarthak2426 sure! Here's a friendly and professional reply to the YOLOv5 GitHub issue:

"Hi there!

Thank you for your kind words! Regarding your last question, you can indeed use the `val.py` script to evaluate your model on video data. However, since videos are a sequence of frames, you will need to modify the script slightly.

1. First, you need to split the video into individual frames. There are various tools and libraries available for this, such as OpenCV or FFMPEG.

2. Once you have the frames, you can use the `val.py` script to evaluate each frame individually. You can pass the frames through the script using a loop or by modifying the script to accept a single frame as input.

3. After evaluating each frame, you can combine the results to obtain the overall performance metrics for the video. This can be done by aggregating the TP, FP, FN counts, or by calculating the average precision (AP), mAP, or other required metrics accordingly.

Remember to ensure that your frames are properly formatted, and the objects of interest are clearly visible for accurate evaluation.

I hope this helps! If you have any further questions or need more assistance, please feel free to ask. Good luck with your evaluation on the unseen video data!

**Comment by Sarthak2426** [comment]
Thank you sir for your valuable time and useful responses @glenn-jocher

**Comment by glenn-jocher** [comment]
@Sarthak2426 hi there!

You're very welcome! I'm glad I could assist you. If you have any more questions or need further assistance, feel free to ask. I'm here to help!

Best regards

**Comment by Sarthak2426** [comment]
sure sir. thank you once again

**Comment by glenn-jocher** [comment]
@Sarthak2426 hi there,

You're welcome! If you have any more questions or need further assistance, feel free to ask. I'm here to help!

Thank you!
