### ISSUE TITLE
Training target individually by detection heads

### ISSUE THREAD

**Issue by www7890** [ultralytics/yolov5#11932]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Hi, 
Is it possible to train different classes of target on different yolo head?

For example, I have three classes: Apple, Lion, and Spacecraft, which are extremely different for their size.

And now I want to train those samples on different head(due to the ability of detection different size of object)

For the smallest grid size head, learns Apple.
For middle one, learns Lion.
For the biggest one, learns Spacecraft.
(This idea is only to do experiment, and may remain lots of detail to check of course)

How can I modify the code to implement this, and by doing so, do I need to adjust the class label index to be like: Apple: class index: 0
Lion: class index: 0
Spacecraft: class index: 0

or just stay on: Apple:0, Lion:1, Spacecraft:2?

Thanks

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@www7890 yes, it is possible to train different classes of targets on different YOLO detection heads in YOLOv5. 

To implement this, you will need to modify the model architecture in the `models/yolo.py` file. You can specify different numbers of detection heads with different grid sizes to handle objects of different sizes. Each detection head can have its own set of anchor boxes and predict specific classes of objects.

Regarding the class label index, you do not need to adjust it to be the same for all classes. You can keep the class index as Apple: 0, Lion: 1, Spacecraft: 2. The model will handle the different class indices correctly during training and inference.

If you decide to experiment with this approach, please share your findings with the YOLO community and the Ultralytics team. We value your contribution and would be glad to assist you along the way. Let us know if you have any further questions.

**Comment by www7890** [comment]
> @www7890 yes, it is possible to train different classes of targets on different YOLO detection heads in YOLOv5.
> 
> To implement this, you will need to modify the model architecture in the `models/yolo.py` file. You can specify different numbers of detection heads with different grid sizes to handle objects of different sizes. Each detection head can have its own set of anchor boxes and predict specific classes of objects.
> 
> Regarding the class label index, you do not need to adjust it to be the same for all classes. You can keep the class index as Apple: 0, Lion: 1, Spacecraft: 2. The model will handle the different class indices correctly during training and inference.
> 
> If you decide to experiment with this approach, please share your findings with the YOLO community and the Ultralytics team. We value your contribution and would be glad to assist you along the way. Let us know if you have any further questions.

Thank you for your response,
Yes I will start to do coding work and do some experiment, if there is question or any finding, I will continuously update here!

**Comment by glenn-jocher** [comment]
@www7890 thank you for your enthusiasm! We appreciate your willingness to contribute and share your findings with the YOLO community and the Ultralytics team. If you have any questions or need further assistance during your coding work and experiments, feel free to reach out. We're here to help. Good luck with your project!

**Comment by www7890** [comment]
> @www7890 thank you for your enthusiasm! We appreciate your willingness to contribute and share your findings with the YOLO community and the Ultralytics team. If you have any questions or need further assistance during your coding work and experiments, feel free to reach out. We're here to help. Good luck with your project!

I was implementing coding part, and wondered something.

For original yolov5 design, each head detect all classes with different grid size, and the shape should be nc+5

For my case, how can I modify the code to made the shape to be 1+5, 1+5 ,1+5 (three heads corresponding to a class)?
or I can only make the output to be zero for the class which I don't want the head to output prediction (which means I still remain the computation of model of prediction, but I made the irresponsible class prediction to be zero in rude.)

------------------------------------------------------update 2023.0802 --------------------------------------------------------
Now I choose the easy way to do it.  For the build_target function, I remove the targets of particular class for corresponding head.

**Comment by glenn-jocher** [comment]
@www7890 to modify the code and make the shape of each head in YOLOv5 to be 1+5 (1 class + 5 attributes), you can make the following changes:

1. In the `models/yolo.py` file, locate the `forward` method of the `Detect` class. This is where the predictions are generated for each detection head.

2. Inside the `forward` method, you will find a loop that iterates over the detection heads. Within this loop, you can modify the shape of the predictions tensor for each head.

3. Modify the line `pred = x[i].forward()[:, self.nc:]` to `pred = x[i].forward()[:, :6]`. This will change the shape of the predictions tensor for each head to be 1+5.

By making this modification, each head will only predict one class and five attributes instead of all classes. Ensure that the number of classes in your dataset matches the number of heads you have modified.

Please note that removing the targets for a particular class in the `build_targets` function, as you mentioned in your update, is a valid approach if you want to disregard the predictions for that class entirely.

Let us know if you have any further questions. Happy coding!

**Comment by www7890** [comment]
> @www7890 to modify the code and make the shape of each head in YOLOv5 to be 1+5 (1 class + 5 attributes), you can make the following changes:
> 
>     1. In the `models/yolo.py` file, locate the `forward` method of the `Detect` class. This is where the predictions are generated for each detection head.
> 
>     2. Inside the `forward` method, you will find a loop that iterates over the detection heads. Within this loop, you can modify the shape of the predictions tensor for each head.
> 
>     3. Modify the line `pred = x[i].forward()[:, self.nc:]` to `pred = x[i].forward()[:, :6]`. This will change the shape of the predictions tensor for each head to be 1+5.
> 
> 
> By making this modification, each head will only predict one class and five attributes instead of all classes. Ensure that the number of classes in your dataset matches the number of heads you have modified.
> 
> Please note that removing the targets for a particular class in the `build_targets` function, as you mentioned in your update, is a valid approach if you want to disregard the predictions for that class entirely.
> 
> Let us know if you have any further questions. Happy coding!

Thanks to your suggestion, I am working on this. 
For the update part of experiment, I remain everything the same but remove unwanted class of each head, and it shows that although the head is not given by some particular classes of target to learn, still it can somehow learned to detect that thing.

For example, the normal training, I can get three classes: Apple, Lion, Spacecraft about 0.90~0.97 mAP. And when I remove Lion when build_target for all heads, it still can perform about mAP 0.56 for Lion.

`        for i in range(self.nl):
            anchors, shape = self.anchors[i], p[i].shape
            
            gain[2:6] = torch.tensor(shape)[[3, 2, 3, 2]]  # xyxy gain
           ####new added####
            not_class_1=  (targets[:,:,1] != 1)  
            target_not_class_1 = targets[not_class_1]
            ################
            t = targets * gain  # shape(3,n,7)
            ...
            ...

`

**Comment by glenn-jocher** [comment]
@www7890 thanks for sharing your update! It's interesting to see that even if you remove a particular class from the targets for each head, the model can still learn to detect that class to some extent.

This behavior is likely a result of the strong learning capacity of the YOLO model. It can generalize and learn features that are common across different classes. However, removing the specific class from the targets explicitly may limit the model's ability to accurately detect that class.

Keep experimenting and evaluating the model's performance with different settings and variations. It would be great if you could provide further updates on your findings. Feel free to ask any more questions or share any other observations. Happy coding!

**Comment by www7890** [comment]
> @www7890 thanks for sharing your update! It's interesting to see that even if you remove a particular class from the targets for each head, the model can still learn to detect that class to some extent.
> 
> This behavior is likely a result of the strong learning capacity of the YOLO model. It can generalize and learn features that are common across different classes. However, removing the specific class from the targets explicitly may limit the model's ability to accurately detect that class.
> 
> Keep experimenting and evaluating the model's performance with different settings and variations. It would be great if you could provide further updates on your findings. Feel free to ask any more questions or share any other observations. Happy coding!

Thank you for your reply, I have tried the part you mentioned. And this is how I change the code in yolo.py since I cannot find the exact code line as yours:
`                else:  # Detect (boxes only)
                    xy, wh, conf_all = x[i].sigmoid().split((2, 2, self.nc + 1), 4)  #for all classes    
                    if i==0: #head one
                        conf = torch.cat((conf_all[..., :1], conf_all[..., 0:1]), dim=-1) #newly added
                    elif i==1:
                        conf = torch.cat((conf_all[..., :1], conf_all[..., 1:2]), dim=-1) #newly added
                    else: 
                        conf = torch.cat((conf_all[..., :1], conf_all[..., 2:]), dim=-1) #newly added

                    xy = (xy * 2 + self.grid[i]) * self.stride[i]  # xy
                    wh = (wh * 2) ** 2 * self.anchor_grid[i]  # wh
                    y = torch.cat((xy, wh, conf), 4)
                z.append(y.view(bs, self.na * nx * ny, 1+5))`

I keep the conf of the class  I want the head to output, and erase other class conf.
For each head I keep different conf of class.

The training result of this model, All the prediction are correct for the bbox position, but all the class becomes the same, that is, the head predict all things as Apple, as Lion and Spacecraft.

It seems that I was wrong because I thought when I restrict the output of a head by erasing the conf of other classes, will make it focus on determining the target class learning. But the result shows that the model gives up learning the class classification.
And the most weird part is that all validation loss for box, cls, obj are normal. No overfitting sign shows up.

I think it may be other coding part needed to fix, can you give me some suggestion? thanks!

**Comment by www7890** [comment]
> @www7890 thanks for sharing your update! It's interesting to see that even if you remove a particular class from the targets for each head, the model can still learn to detect that class to some extent.
> 
> This behavior is likely a result of the strong learning capacity of the YOLO model. It can generalize and learn features that are common across different classes. However, removing the specific class from the targets explicitly may limit the model's ability to accurately detect that class.
> 
> Keep experimenting and evaluating the model's performance with different settings and variations. It would be great if you could provide further updates on your findings. Feel free to ask any more questions or share any other observations. Happy coding!

> @www7890 thanks for sharing your update! It's interesting to see that even if you remove a particular class from the targets for each head, the model can still learn to detect that class to some extent.
> 
> This behavior is likely a result of the strong learning capacity of the YOLO model. It can generalize and learn features that are common across different classes. However, removing the specific class from the targets explicitly may limit the model's ability to accurately detect that class.
> 
> Keep experimenting and evaluating the model's performance with different settings and variations. It would be great if you could provide further updates on your findings. Feel free to ask any more questions or share any other observations. Happy coding!

Thank you for your reply, I have tried the part you mentioned. And this is how I change the code in yolo.py since I cannot find the exact code line as yours:

               'else:  # Detect (boxes only)
                    xy, wh, conf_all = x[i].sigmoid().split((2, 2, self.nc + 1), 4)  #for all classes    
                    if i==0: #head one
                        conf = torch.cat((conf_all[..., :1], conf_all[..., 0:1]), dim=-1) #newly added
                    elif i==1:
                        conf = torch.cat((conf_all[..., :1], conf_all[..., 1:2]), dim=-1) #newly added
                    else: 
                        conf = torch.cat((conf_all[..., :1], conf_all[..., 2:]), dim=-1) #newly added

                    xy = (xy * 2 + self.grid[i]) * self.stride[i]  # xy
                    wh = (wh * 2) ** 2 * self.anchor_grid[i]  # wh
                    y = torch.cat((xy, wh, conf), 4)
                z.append(y.view(bs, self.na * nx * ny, 1+5))'


I keep the conf of the class  I want the head to output, and erase other class conf.
For each head I keep different conf of class.

The training result of this model, All the prediction are correct for the bbox position, but all the class becomes the same, that is, the head predict all things as Apple, as Lion and Spacecraft.

It seems that I was wrong because I thought when I restrict the output of a head by erasing the conf of other classes, will make it focus on determining the target class learning. But the result shows that the model gives up learning the class classification.
And the most weird part is that all validation loss for box, cls, obj are normal. No overfitting sign shows up.

I think it may be other coding part needed to fix, can you give me some suggestion? thanks!

**Comment by www7890** [comment]
> @www7890 thanks for sharing your update! It's interesting to see that even if you remove a particular class from the targets for each head, the model can still learn to detect that class to some extent.
> 
> This behavior is likely a result of the strong learning capacity of the YOLO model. It can generalize and learn features that are common across different classes. However, removing the specific class from the targets explicitly may limit the model's ability to accurately detect that class.
> 
> Keep experimenting and evaluating the model's performance with different settings and variations. It would be great if you could provide further updates on your findings. Feel free to ask any more questions or share any other observations. Happy coding!

@glenn-jocher  
thanks for sharing your update! It's interesting to see that even if you remove a particular class from the targets for each head, the model can still learn to detect that class to some extent.
> 
> This behavior is likely a result of the strong learning capacity of the YOLO model. It can generalize and learn features that are common across different classes. However, removing the specific class from the targets explicitly may limit the model's ability to accurately detect that class.
> 
> Keep experimenting and evaluating the model's performance with different settings and variations. It would be great if you could provide further updates on your findings. Feel free to ask any more questions or share any other observations. Happy coding!

Thank you for your reply, I have tried the part you mentioned. And this is how I change the code in yolo.py since I cannot find the exact code line as yours:

               'else:  # Detect (boxes only)
                    xy, wh, conf_all = x[i].sigmoid().split((2, 2, self.nc + 1), 4)  #for all classes    
                    if i==0: #head one
                        conf = torch.cat((conf_all[..., :1], conf_all[..., 0:1]), dim=-1) #newly added
                    elif i==1:
                        conf = torch.cat((conf_all[..., :1], conf_all[..., 1:2]), dim=-1) #newly added
                    else: 
                        conf = torch.cat((conf_all[..., :1], conf_all[..., 2:]), dim=-1) #newly added

                    xy = (xy * 2 + self.grid[i]) * self.stride[i]  # xy
                    wh = (wh * 2) ** 2 * self.anchor_grid[i]  # wh
                    y = torch.cat((xy, wh, conf), 4)
                z.append(y.view(bs, self.na * nx * ny, 1+5))'


I keep the conf of the class  I want the head to output, and erase other class conf.
For each head I keep different conf of class.

The training result of this model, All the prediction are correct for the bbox position, but all the class becomes the same, that is, the head predict all things as Apple, as Lion and Spacecraft.

It seems that I was wrong because I thought when I restrict the output of a head by erasing the conf of other classes, will make it focus on determining the target class learning. But the result shows that the model gives up learning the class classification.
And the most weird part is that all validation loss for box, cls, obj are normal. No overfitting sign shows up.

I think it may be other coding part needed to fix, can you give me some suggestion? thanks!

**Comment by www7890** [comment]
> @www7890 thanks for sharing your update! It's interesting to see that even if you remove a particular class from the targets for each head, the model can still learn to detect that class to some extent.
> 
> This behavior is likely a result of the strong learning capacity of the YOLO model. It can generalize and learn features that are common across different classes. However, removing the specific class from the targets explicitly may limit the model's ability to accurately detect that class.
> 
> Keep experimenting and evaluating the model's performance with different settings and variations. It would be great if you could provide further updates on your findings. Feel free to ask any more questions or share any other observations. Happy coding!

Thank you for your reply, I have tried the part you mentioned. And this is how I change the code in yolo.py since I cannot find the exact code line as yours:

                `else: # Detect (boxes only)
                    xy, wh, conf_all = x[i].sigmoid().split((2, 2, self.nc + 1), 4)  #for all classes                   
                    if i == 0:
                        conf = torch.cat((conf_all[..., :1], conf_all[..., 0:1]), dim=-1)
                    elif i == 1:
                        conf = torch.cat((conf_all[..., :1], conf_all[..., 1:2]), dim=-1)
                    else:
                        conf = torch.cat((conf_all[..., :1], conf_all[..., 2:]), dim=-1)
                 
                    xy = (xy * 2 + self.grid[i]) * self.stride[i]  # xy
                    wh = (wh * 2) ** 2 * self.anchor_grid[i]  # wh
                    y = torch.cat((xy, wh, conf), 4)
                z.append(y.view(bs, self.na * nx * ny, 1+5))` 

I keep the conf of the classes I want for a head to predict, and erase others.
By doing so, I can restrict the head to output particular class.
But when I finished  training, the result shows that the model is struggled on learning class classification, each head sees other classes object as the same as the one it have learned. For example: the first head sees everything as Apple, the second one sees every other object as Lion...

the bbox position and size is perfectly correct, but only the class is wrong.
This result surprises me because I thought the model shall learned to determine the target object and ignored others.

Is there any suggestion or there is some coding part I still need to fix up?
Thank you

**Comment by glenn-jocher** [comment]
@www7890 thank you for the update and for sharing the code changes you made in the `yolo.py` file. 

From your description, it seems that your modification successfully restricts each head to predict a specific class. However, you are experiencing difficulties with class classification, as each head seems to recognize objects from other classes as the one it has been trained on (e.g., the first head recognizing everything as an Apple).

One possible reason for this behavior could be that the model is not receiving enough examples or diversity of objects for each class during training. This can lead to a biased or skewed learning pattern, causing the model to make incorrect class predictions.

To address this issue, you may consider the following:

1. Ensure that your dataset has a balanced distribution of objects from each class. If one class has significantly fewer examples compared to others, it may affect the model's ability to learn and correctly identify objects from that class.

2. Increase the representation of the classes with lower performance during training. You can do this by augmenting the dataset with more examples of those classes or using techniques like data synthesis or transfer learning.

3. Consider adjusting the loss function or training parameters to prioritize the correct classification of objects. For example, you can experiment with changing the weights or scaling factors associated with class predictions in the loss calculation.

It's worth noting that these suggestions are general guidelines, and the effectiveness may depend on your specific dataset and use case. It's important to experiment, iterate, and evaluate the impact of these changes on the model's performance.

I hope these suggestions help you address the issue you are facing. Please let me know if you have any further questions or if there's anything else I can assist you with.

**Comment by www7890** [comment]
> @www7890 thank you for the update and for sharing the code changes you made in the `yolo.py` file.
> 
> From your description, it seems that your modification successfully restricts each head to predict a specific class. However, you are experiencing difficulties with class classification, as each head seems to recognize objects from other classes as the one it has been trained on (e.g., the first head recognizing everything as an Apple).
> 
> One possible reason for this behavior could be that the model is not receiving enough examples or diversity of objects for each class during training. This can lead to a biased or skewed learning pattern, causing the model to make incorrect class predictions.
> 
> To address this issue, you may consider the following:
> 
>     1. Ensure that your dataset has a balanced distribution of objects from each class. If one class has significantly fewer examples compared to others, it may affect the model's ability to learn and correctly identify objects from that class.
> 
>     2. Increase the representation of the classes with lower performance during training. You can do this by augmenting the dataset with more examples of those classes or using techniques like data synthesis or transfer learning.
> 
>     3. Consider adjusting the loss function or training parameters to prioritize the correct classification of objects. For example, you can experiment with changing the weights or scaling factors associated with class predictions in the loss calculation.
> 
> 
> It's worth noting that these suggestions are general guidelines, and the effectiveness may depend on your specific dataset and use case. It's important to experiment, iterate, and evaluate the impact of these changes on the model's performance.
> 
> I hope these suggestions help you address the issue you are facing. Please let me know if you have any further questions or if there's anything else I can assist you with.

I realize there was some bug to fix, now I am doing some experiment and don't have a conclusion yet.
I will present here as long as I finish.

While I was designing my experiment , I was struggle on a situation. Please help me!
I have now five classes: Apple, Lion, Monkey, Train, Spacecraft. The classes index is: 0,1,2,3,4
I assign class:0 to head one. Class:1,2 to head two. Class:4 to head three, which means I abandon class:3

Then I met the error, shows as follow:

utils/loss.py", line 175, in __call__
    t[range(n), tcls[i]] = self.cp
IndexError: index 4 is out of bounds for dimension 1 with size 4

I think it is just a simple issue of class label assignment, so I map the class order from 0,1,2,4 to 0,1,2,3 in the function: build_targets.

The model is able to train, but the result is weird, for class:0,1,2, they have normal mAP, but for class:4, it has mAP: 0 all the time.
I cannot figure out why...

**Comment by glenn-jocher** [comment]
@www7890 it's great to hear that you're conducting experiments and working on resolving the issues you encountered. I understand that you have five classes (Apple, Lion, Monkey, Train, Spacecraft) with class indices 0, 1, 2, 3, and 4. You assigned class 0 to head one, classes 1 and 2 to head two, and class 4 to head three, thereby excluding class 3.

Regarding the error message you encountered (`IndexError: index 4 is out of bounds for dimension 1 with size 4`) in `utils/loss.py`, it appears to be related to the class label assignment. It's a simple issue of mapping the class order from 0, 1, 2, 4 to 0, 1, 2, 3 in the `build_targets` function to resolve this.

However, you mentioned that despite being able to train the model, you're observing unusual results. Specifically, classes 0, 1, and 2 have normal mean Average Precision (mAP), but class 4 consistently has an mAP of 0. It's challenging to identify the exact cause without inspecting the code and data thoroughly.

To investigate further, I recommend verifying the following:

1. Ensure that class 4 (Spacecraft) has enough instances in the training dataset and that it is correctly labeled.

2. Double-check your data preprocessing pipeline to ensure that the images and annotations are correctly loaded and processed.

3. Review the training settings and hyperparameters. Consider experimenting with different learning rates, batch sizes, and optimization algorithms to see if they have any effect on the results.

4. If class 4 instances are scarce, you may consider data augmentation techniques to artificially increase the number of training examples for this class. This can help balance the class representation and potentially improve the model's performance.

By carefully reviewing and adjusting these aspects, you may be able to identify the cause of the anomaly and improve the mAP for class 4.

Thank you for reaching out, and please don't hesitate to ask any further questions or provide additional details as needed. I'm here to assist you throughout your experimentation process.

**Comment by www7890** [comment]
> @www7890 it's great to hear that you're conducting experiments and working on resolving the issues you encountered. I understand that you have five classes (Apple, Lion, Monkey, Train, Spacecraft) with class indices 0, 1, 2, 3, and 4. You assigned class 0 to head one, classes 1 and 2 to head two, and class 4 to head three, thereby excluding class 3.
> 
> Regarding the error message you encountered (`IndexError: index 4 is out of bounds for dimension 1 with size 4`) in `utils/loss.py`, it appears to be related to the class label assignment. It's a simple issue of mapping the class order from 0, 1, 2, 4 to 0, 1, 2, 3 in the `build_targets` function to resolve this.
> 
> However, you mentioned that despite being able to train the model, you're observing unusual results. Specifically, classes 0, 1, and 2 have normal mean Average Precision (mAP), but class 4 consistently has an mAP of 0. It's challenging to identify the exact cause without inspecting the code and data thoroughly.
> 
> To investigate further, I recommend verifying the following:
> 
>     1. Ensure that class 4 (Spacecraft) has enough instances in the training dataset and that it is correctly labeled.
> 
>     2. Double-check your data preprocessing pipeline to ensure that the images and annotations are correctly loaded and processed.
> 
>     3. Review the training settings and hyperparameters. Consider experimenting with different learning rates, batch sizes, and optimization algorithms to see if they have any effect on the results.
> 
>     4. If class 4 instances are scarce, you may consider data augmentation techniques to artificially increase the number of training examples for this class. This can help balance the class representation and potentially improve the model's performance.
> 
> 
> By carefully reviewing and adjusting these aspects, you may be able to identify the cause of the anomaly and improve the mAP for class 4.
> 
> Thank you for reaching out, and please don't hesitate to ask any further questions or provide additional details as needed. I'm here to assist you throughout your experimentation process.

I did fix the issue!!!

In the file: val.py
There is a line: `for si, pred in enumerate(preds):....`
The following is the code I add the code to reverse the class of prediction back to the original order
Because while building the target, We need to make the class label: 0,1,2,4 to be: 0,1,2,3
The continuous index and label make sure the error: 

utils/loss.py", line 175, in call
t[range(n), tcls[i]] = self.cp
IndexError: index 4 is out of bounds for dimension 1 with size 4

won't happen.

After model prediction, we still need to reverse mapping the class label back to the original order, to make sure the metric computation is correct. eg. pred[:,5] = [0,1,2,3] to [0,1,2,4] 

Now I can simply define which classes to learn for the particular heads, even with non-continuous class list in data.yaml
Eg. 
In data.yaml:
trained_class: [0,1,2,3,5,8,] #'all' or [0,1....]
head_calss_mapping: {0:[0,1], 1:[2,3], 2:[5,8]}
nc: 9

Now I can focus on doing the experiment! 
Thank you for your helping, once I have some conclusion, I will share with the community here.

**Comment by glenn-jocher** [comment]
@www7890 that's great news! I'm glad to hear that you were able to fix the issue.

Thank you for sharing the code modification you made in the `val.py` file. It's indeed necessary to reverse the class predictions back to the original order to ensure correct computation of metrics and avoid the `IndexError`.

Additionally, your approach of mapping the class labels back to the original order after model prediction is important for accurate metric computation, such as mAP. Your explanation of how you achieved this by mapping `pred[:,5]` from `[0,1,2,3]` to `[0,1,2,4]` makes sense.

It's fantastic that you can now define which classes to learn for specific heads and handle non-continuous class lists in the `data.yaml` file. Your example configuration in `data.yaml` (`trained_class: [0,1,2,3,5,8,]` and `head_class_mapping: {0:[0,1], 1:[2,3], 2:[5,8]}`) demonstrates this flexibility. With this implementation, you can focus on your experiments effectively.

Thank you for your perseverance and for sharing these findings with the community. Your contributions will undoubtedly benefit other users. If you have any more updates or insights, please feel free to share them. We appreciate your engagement, and I'm here to help if you need any further assistance.

Happy experimenting!
