### ISSUE TITLE
return and saved results as detections crops using results.crop(save=True)

### ISSUE THREAD

**Issue by hulkds** [ultralytics/yolov5#11933]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

Bug when doing results.crop(save=True) after load yolov5 via pytorch hub.

Bug message:
```bash
# b = xyxy2xywh(xyxy.view(-1, 4))  # boxes
AttributeError: 'list' object has no attribute 'view'
```
Bug found in this [line](https://github.com/ultralytics/ultralytics/blob/c3c27b019a9516a9b2c78c291b61ef7cf97ff7f3/ultralytics/utils/plotting.py#L296C45-L296C45)

Solution:
```python
b = xyxy2xywh(torch.stack(xyxy).view(-1, 4))  # boxes
```

### Environment

- YOLOv5 🚀 2023-8-2 Python-3.10.12 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce GTX 1650 Ti, 3904MiB)
- Ubuntu 22.04
- Python3.10.12

### Minimal Reproducible Example

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Image
im = 'https://ultralytics.com/images/zidane.jpg'

# Inference
results = model(im)

# cropped detections dictionary
crops = results.crop(save=True)  
```

### Additional

Consider using ```BGR=True``` if the crops colors is not what you want.
```python
crops = results.crop(save=True, BGR=True) 
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@hulkds this is a known bug when using `results.crop(save=True)` after loading YOLOv5 via PyTorch Hub. The error is caused by a line in the code that expects a tensor but receives a list. 

To address this issue, you can modify the code at line 296 in `ultralytics/utils/plotting.py` as follows:

```python
b = xyxy2xywh(torch.stack(xyxy).view(-1, 4))  # boxes
```

This change will convert the list of bounding boxes into a tensor before passing it to the `xyxy2xywh` function.

Thank you for bringing this to our attention, and we appreciate your willingness to submit a PR! Your contribution is valuable to the YOLOv5 community.

**Comment by hulkds** [comment]
@glenn-jocher I faced a CI error:
```E       TypeError: stack(): argument 'tensors' (position 1) must be tuple of Tensors, not Tensor```

To address this issue, I tried to pass a tuple in ```torch.stack()``` and it works 
```python
b = xyxy2xywh(torch.stack((xyxy)).view(-1, 4))  # boxes
```

I'll rerun the Ultralytics CI workfow and will submit the PR again.

**Comment by hulkds** [comment]
@glenn-jocher new PR: https://github.com/ultralytics/ultralytics/pull/4123

**Comment by hulkds** [comment]
@glenn-jocher I have created a PR: https://github.com/ultralytics/ultralytics/pull/4124

**Comment by glenn-jocher** [comment]
@hulkds thank you for creating the pull request! We appreciate your contribution to the YOLOv5 repository. Our team will review it and provide feedback as soon as possible. Keep up the good work!

**Comment by glenn-jocher** [comment]
@hulkds ok between https://github.com/ultralytics/ultralytics/pull/4127 and https://github.com/ultralytics/yolov5/pull/11936 I think this bug should be resolved. 

Please update YOLOv5 dependencies with `pip install -r requirements.txt` and try again, thank you!
