### ISSUE TITLE
ToGray Augmentation Option in hyp yaml file

### ISSUE THREAD

**Issue by spacewalk01** [ultralytics/yolov5#11938]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Why not add the ToGray augmentation option in hyp file. So when there is a task to detect objects in a  low-light situation, we can simply set a probability value to tune the model. I know we can do it digging utils/augmentations.py code. But it could be easier this way.

**Comment by glenn-jocher** [comment]
@spacewalk01 the Ultralytics YOLOv5 team appreciates your suggestion. We value feedback from the community and constantly strive to improve our model and its usability. Adding a ToGray augmentation option in the hyp file to handle low-light detection scenarios sounds like a useful enhancement. We will consider implementing this feature in a future update to make it easier for users to tune the model for such situations. Thank you for your contribution!
