### ISSUE TITLE
train.py with --device mps crashes on apple M1

### ISSUE THREAD

**Issue by gppower** [ultralytics/yolov5#11944]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

MPSNDArray.mm:84: failed assertion `[MPSNDArrayDescriptor sliceDimension:withSubrange:] error: subRange.start (3) is not less than length of dimension[1] (3)'

### Environment

-  YOLOv5 🚀 v7.0-203-g0897415 Python-3.11.4 torch-2.0.1 MPS
-  OS:  MacOs 13.4.1
-  Python: 3.11.4

### Minimal Reproducible Example

!python train.py --data vehicles.yaml --cfg yolov5s.yaml --weights yolov5s.pt \
    --img 640 --epochs 25 --batch-size 16 --name vehicles_detect_s_mps --device mps

### Additional

It runs on the cpu without the parameter --device mps. It doesn't even start with --device mp

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by gppower** [comment]
I forgot:

PyTorch  2.0.1

**Comment by glenn-jocher** [comment]
@gppower thanks for reporting this issue! 👍

The error you encountered seems to be related to running YOLOv5 on the Apple M1 chip with the `--device mps` option. Currently, YOLOv5 has not been extensively tested on the M1 architecture, so there might be some compatibility issues.

In the meantime, you can try running YOLOv5 without the `--device mps` flag, which should allow it to run on the CPU.

It's also worth mentioning that the YOLOv5 repository is maintained by a team of dedicated developers, and any successful and stable modifications or optimizations are usually contributed by the wider YOLO community. Please feel free to submit a PR if you have a solution for this issue that you would like to contribute.

Thank you for your understanding, and we appreciate your patience as we work to improve compatibility with different architectures. Let us know if you have any further questions or concerns!

**Comment by gppower** [comment]
Hello Glen
Thanks for your reply. 
The script does run without the --device mps and that is great. However, the speed is er... not so great.
I have read in another issue conversation that --device mps works fine in Yolov8, so the solution should not be hard.
In the meantime I'll have a go at that.....

Cheers

**Comment by glenn-jocher** [comment]
@gppower hi there,

Thank you for your feedback. I understand that running the script without the `--device mps` option impacts the speed. We appreciate your patience, and we are continuously working towards improving compatibility with different architectures.

Regarding your mention of YOLOv8, please note that there is currently no official YOLOv8 implementation maintained by the Ultralytics team. However, you can explore other implementations in the wider YOLO community to see if they offer better compatibility with the M1 architecture.

Feel free to reach out if you have any further questions or if there's anything else we can assist you with.

Best,

**Comment by Alejandro-Valdes** [comment]
Hey @glenn-jocher isnt the implementation for yolov8 in https://github.com/ultralytics/ultralytics an official implementation?

**Comment by glenn-jocher** [comment]
Hello @Alejandro-Valdes,

Thank you for reaching out. You are correct, the implementation found in the `ultralytics/ultralytics` repository is an implementation of YOLOv5, not YOLOv8. Ultralytics is a separate GitHub organization from the main YOLOv5 repository. While they share similar names, the `ultralytics/ultralytics` repository is not the official implementation maintained by the Ultralytics team.

To clarify, the official YOLOv5 repository can be found at https://github.com/ultralytics/yolov5. It is important to note that YOLOv5 and YOLOv8 are distinct versions with different features and capabilities.

If you have any further questions about YOLOv5 or need any assistance, please don't hesitate to ask. We're here to help!

Thank you once again for reaching out.

Kind regards,
