### ISSUE TITLE
Loading and Inference [TRT] Yolov5 model in C++ 😫🤯

### ISSUE THREAD

**Issue by SJavad** [ultralytics/yolov5#11940]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi 🖐😪
I'm sorry. I am very disappointed and tired 🥱
Because I searched a lot on the internet about how to load a TensorRT YOLOv5 model on C++, but after so much time, I still couldn't find a way... 🤯
in python, I can easily load and inference model and visualize an output... 😍
there is anyone that knows how can I load, Inference a TensorRT Yolov5 mode on C++? 😭
I'm working on Jetson TX1 for using Yolov5... 
Thank you 🌸🖐

**Comment by glenn-jocher** [comment]
@SJavad hi there, 

I understand your frustration in not being able to find a way to load a TensorRT YOLOv5 model in C++. While there may not be a specific guide for this, you can refer to the "C++ Detection" example in the YOLOv5 repository, which demonstrates inference in C++. Although the example is for the PyTorch version of YOLOv5, you can use it as a starting point to integrate TensorRT inference into your C++ code.

For Jetson TX1, you can take advantage of the prebuilt TensorRT engines and ONNX models provided in the GitHub repository. They can be found in the `runs/train/exp` directory. You'll need to convert the ONNX model to a TensorRT engine by following the TensorRT documentation.

Please note that the YOLOv5 repository is a community-driven project, and there may be other developers who have successfully achieved what you're trying to do. If you have any further questions or need assistance, feel free to ask, and we'll do our best to help. 

Best, 
Glenn

**Comment by SJavad** [comment]
> @SJavad hi there, 
> 
> I understand your frustration in not being able to find a way to load a TensorRT YOLOv5 model in C++. While there may not be a specific guide for this, you can refer to the "C++ Detection" example in the YOLOv5 repository, which demonstrates inference in C++. Although the example is for the PyTorch version of YOLOv5, you can use it as a starting point to integrate TensorRT inference into your C++ code.
> 
> For Jetson TX1, you can take advantage of the prebuilt TensorRT engines and ONNX models provided in the GitHub repository. They can be found in the `runs/train/exp` directory. You'll need to convert the ONNX model to a TensorRT engine by following the TensorRT documentation.
> 
> Please note that the YOLOv5 repository is a community-driven project, and there may be other developers who have successfully achieved what you're trying to do. If you have any further questions or need assistance, feel free to ask, and we'll do our best to help. 
> 
> Best, 
> Glenn

@glenn-jocher 
Thank you for your response 🌸🖐️
I have no problem with converting the yolov5 to onnx and then to .engine file. 
But I have no idea to how to load and inference trt engine with c++.
My project is very depends on c++.
loading trt engine in c++ is really annoying 😞

**Comment by glenn-jocher** [comment]
@SJavad I understand that loading a TensorRT engine with C++ can be challenging. While there isn't a dedicated guide for this specific task, I can offer some suggestions to help you get started.

To load and inference a TensorRT engine in C++, you can use the TensorRT C++ API. You will need to include the necessary headers and link against the TensorRT library in your C++ project.

Here are some general steps to follow:

1. Make sure you have the TensorRT library installed on your system.

2. Include the necessary headers in your C++ code. You will typically need `NvInfer.h`, `NvOnnxConfig.h`, and `NvOnnxParser.h`.

3. Load the serialized TensorRT engine file (`.engine`) using the `ICudaEngine` class.

4. Create a TensorRT context using the `IExecutionContext` class.

5. Allocate the necessary GPU and CPU memory for input and output tensors.

6. Copy input data to GPU memory and run inference using the `execute` method.

7. Retrieve the results from GPU memory and process them as needed.

Please note that the exact implementation details may vary based on your specific use case and the version of TensorRT you are using. You may need to consult the TensorRT documentation and examples for more specific guidance.

If you encounter any specific issues during implementation or have further questions, feel free to ask. The YOLOv5 community and the Ultralytics team are here to assist you.

Best,
Glenn

**Comment by M15-3080** [comment]
> > 嘿，你好
> > 我理解您因无法找到在C++中加载 TensorRT YOLOv5 模型的方法而感到沮丧。虽然可能没有具体的指南，但您可以参考 YOLOv5 存储库中的“C++检测”示例，该示例演示了C++推理。尽管该示例适用于 YOLOv5 的 PyTorch 版本，但您可以将其用作将 TensorRT 推理集成到C++代码中的起点。
> > 对于 Jetson TX1，您可以利用 GitHub 存储库中提供的预构建的 TensorRT 引擎和 ONNX 模型。它们可以在目录中找到。您需要按照 TensorRT 文档将 ONNX 模型转换为 TensorRT 引擎。`runs/train/exp`
> > 请注意，YOLOv5 存储库是一个社区驱动的项目，可能还有其他开发人员已经成功地实现了您正在尝试做的事情。如果您有任何其他问题或需要帮助，请随时提出，我们将尽最大努力提供帮助。
> > 贝斯特，格伦
> 
> 感谢您的回复🌸🖐️我将yolov5转换为onnx然后转换为.engine文件没有问题。但是我不知道如何使用 c++ 加载和推理 trt 引擎。我的项目非常依赖于 c++。在 C++ 中加载 TRT 引擎真的很烦人😞

https://github.com/wang-xinyu/tensorrtx
I’m glad that I could be of help

**Comment by glenn-jocher** [comment]
@M15-3080 i understand your frustration in trying to load a TensorRT YOLOv5 model in C++. While there may not be a specific guide for this, you can refer to the "C++ Detection" example in the YOLOv5 repository for inference in C++. Although the example is for the PyTorch version of YOLOv5, you can use it as a starting point to integrate TensorRT inference into your C++ code.

You can also check out the tensorrtx repository by Wang Xinyu, which provides examples for loading and inferring with TensorRT models in C++. This resource may be helpful in your case.

Please keep in mind that the YOLOv5 repository is a community-driven project, and there may be other developers who have successfully accomplished what you are trying to do. If you have any further questions or need assistance, feel free to ask.

Best, 
Glenn

**Comment by SJavad** [comment]
Thanks for your helps guys 🖐️🌸
I have to test ways that you tell me and if I have any questions or problems. I'll tell you 
Thank you so much ❤️🌸

**Comment by glenn-jocher** [comment]
@SJavad you're welcome! We're glad that we could provide some assistance. Feel free to test out the suggested approaches, and if you have any questions or run into any problems along the way, don't hesitate to reach out to us. We'll be here to help you out. Thanks again and happy coding!
