### ISSUE TITLE
Ultralytics Module does not exist

### ISSUE THREAD

**Issue by kessmith** [ultralytics/yolov5#11945]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection, PyTorch Hub, Integrations

### Bug

Recently there was an addition to the code base to include the following logic `from ultralytics.utils.plotting import Annotator`

Changes like this that where added to the code base are breaking changes that make it so that you can't run the Yolov5 pytorch hub anymore as it was previously.

Now, within the code you are getting the following error:
<img width="722" alt="image" src="https://github.com/ultralytics/yolov5/assets/65629442/1b0a63ba-bbfe-4906-ba55-ba05f78a229d">

**There is no folder called Ultralytics and there is no folder/file called plotting.**

Please look into this. If I am crazy and I am missing something that would resolve this error please also let me know.

### Minimal Reproducible Example

`sys.path.append(str(ROOT))  # add ROOT to PATH`
`ROOT = Path(os.path.relpath(ROOT, Path.cwd()))  # relative`

`from ultralytics.utils.plotting import Annotator`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@kessmith this issue seems to be related to the recent addition of the `from ultralytics.utils.plotting import Annotator` line in the code. As stated, it's causing an error because there is no folder called `Ultralytics` and no file called `plotting` in the YOLOv5 codebase.

This issue needs to be looked into by the YOLOv5 maintainers. It's possible that there may have been an error in the recent changes.

If you believe that you may be missing something and there's a solution to resolve this error, please include it in your response.

Thank you for bringing this to our attention. We will investigate and work to resolve the issue.

**Comment by glenn-jocher** [comment]
@kessmith I looked into this and I am able to reproduce your error if i.e. I start from a fresh colab notebook.

The simplest way to fix this is to `pip install ultralytics` as we show in our YOLOv5 PyTorch Hub guide https://pytorch.org/hub/ultralytics_yolov5/#before-you-start

<img width="1480" alt="Screenshot 2023-08-07 at 01 16 33" src="https://github.com/ultralytics/yolov5/assets/26833433/4793d7e7-20ae-41ee-8245-1bee14fe33e3">


I understand it would be simpler without the pip install step. I'll look into solutions there, but for now this will solve your problem!

**Comment by glenn-jocher** [comment]
@kessmith good news 😃! Your original issue may now be fixed ✅ in PR #11950. This should allow you to use YOLOv5 with torch.hub.load() without installing any prerequisites first (everything should be installed automatically on first use).

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://bit.ly/yolov5-paperspace-notebook"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
