### ISSUE TITLE
print metric f1score

### ISSUE THREAD

**Issue by inginfor** [ultralytics/yolov5#11954]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

how many and which files and in which lines need to be modified in order to also print the results in terms of f1 score during training and validation?

**Comment by inginfor** [comment]
how many and which files and in which lines need to be modified in order to also print the results in terms of f1 score during training and validation?

**Comment by glenn-jocher** [comment]
@inginfor to print the results in terms of the F1 score during training and validation, you will need to modify the following files and lines:

1. In the `train.py` file:
   - In the `def train()` function, add the F1 score calculation code after the `AP` calculation code. You can use the `from utils.metrics import f1` function to calculate the F1 score.

2. In the `val.py` file:
   - In the `def test(cfg, data_cfg, weights=None, batch_size=32, imgsz=640, conf_thres=0.001, iou_thres=0.6, save_json=False, single_cls=False, augment=False, verbose=False, save_txt=False)` function, add the F1 score calculation code after the `AP` calculation code. Again, you can use the `from utils.metrics import f1` function to calculate the F1 score.

Remember to import the necessary dependencies and use the appropriate functions to calculate the F1 score in both files.

Feel free to reach out if you have any further questions.

**Comment by inginfor** [comment]
ok thanks, sorry but which line is it? I don't find AP calculation code in def train() function in train.py file and I can't find def test in the val.py file.
In addition to calculating them, which files and which lines should be modified to also print the f1 score both for a single class and for all classes?

**Comment by glenn-jocher** [comment]
@inginfor hi there! No problem at all. In the `train.py` file, the AP calculation code is located in the `results.save()` function at the end of the for loop in the `train()` function. You can add the F1 score calculation code after the `results.save()` function.

Regarding the `val.py` file, please double-check if you have the most up-to-date version of the YOLOv5 repository. In recent versions, the `test()` function has been renamed to `val()`. You can find the AP calculation code and add the F1 score calculation code after it in the `val()` function.

To print the F1 score for a single class and for all classes, you will need to modify the following files and lines:

1. In the `train.py` file:
    - In the `train()` function, after the `results.save()` function, add the F1 score calculation code using the `from utils.metrics import f1` function.
    - To print the F1 score for all classes, you can use `f1(output, target, threshold=0.5, multiclass=True)` function.
    - To print the F1 score for a single class, you can use `f1(output, target, threshold=0.5, multiclass=False)` function.

2. In the `val.py` file:
    - In the `val()` function, after the AP calculation code, add the F1 score calculation code using the `from utils.metrics import f1` function.
    - To print the F1 score for all classes, you can use `f1(output, target, threshold=0.5, multiclass=True)` function.
    - To print the F1 score for a single class, you can use `f1(output, target, threshold=0.5, multiclass=False)` function.

Remember to import the necessary dependencies, and modify the code accordingly.

Let me know if there's anything else I can help you with!

**Comment by inginfor** [comment]
ok thanks but there is not results.save() here https://github.com/ultralytics/yolov5/blob/master/train.py and there is no test() here https://github.com/ultralytics /yolov5/blob/master/val .py, which version of the YOLOv5 repository are you referring to?

**Comment by glenn-jocher** [comment]
@inginfor apologies for the confusion. It seems that there might have been some recent changes to the YOLOv5 repository. Can you please confirm the specific version of the repository you are using? This will help us provide you with the most accurate information regarding the files and lines that need to be modified. Thank you for your patience and understanding.

**Comment by inginfor** [comment]
YOLOv5 🚀 v7.0-207-gdf48c20. I am using the latest version.



cff-version: 1.2.0
preferred-citation:
  type: software
  message: If you use YOLOv5, please cite it as below.
  authors:
  - family-names: Jocher
    given-names: Glenn
    orcid: "https://orcid.org/0000-0001-5950-6979"
  title: "YOLOv5 by Ultralytics"
  version: 7.0
  doi: 10.5281/zenodo.3908559
  date-released: 2020-5-29
  license: AGPL-3.0
  url: "https://github.com/ultralytics/yolov5"

**Comment by glenn-jocher** [comment]
@inginfor thank you for providing the version information and the citation details for YOLOv5.

Regarding your question about printing the F1 score during training and validation, please note that the specific implementation details may vary depending on the version you are using. To print the F1 score, you will generally need to modify the `train.py` and `val.py` files.

In the `train.py` file, you can add the F1 score calculation code after the relevant results calculations. However, as the specific location of these calculations may have changed in the latest version, I recommend browsing through the file to find the appropriate location to insert the F1 score calculation code.

Similarly, in the `val.py` file, you can look for the location where the AP calculation code is present, and add the F1 score calculation code after that.

To print the F1 score for all classes, you can use the `f1(output, target, threshold=0.5, multiclass=True)` function. To print the F1 score for a single class, you can use the `f1(output, target, threshold=0.5, multiclass=False)` function.

Please note that these instructions are based on previous versions of YOLOv5, and there may have been updates or changes since then. I encourage you to review the relevant sections of the code and adapt the modifications accordingly.

If you have any further questions or need additional assistance, please don't hesitate to ask.

**Comment by inginfor** [comment]
ok thanks but only the train.py and val.py files need to be changed or other files too? 
Should the utils.loggers.__init__ file be modified?

**Comment by glenn-jocher** [comment]
@inginfor the `train.py` and `val.py` files are the primary files where you would modify to print the F1 score during training and validation in YOLOv5. In these files, you can add the necessary code to calculate and print the F1 score after the relevant calculations.

Regarding the `utils.loggers.__init__` file, it typically handles logging and visualization functionalities, so it may not require direct modification to print the F1 score. However, depending on your specific requirements, you can explore modifying this file to customize the logging or visualization of the F1 score if needed.

Remember to review the code in these files to determine the exact locations where the modifications need to be made. Keep in mind that these instructions are based on previous versions, so ensure you adapt them according to the version you are currently using.

Feel free to ask if you have any more questions.

**Comment by inginfor** [comment]
thanks

**Comment by glenn-jocher** [comment]
@inginfor hi there,

Thank you for reaching out. To print the F1 score during training and validation in YOLOv5, you can modify the `train.py` and `val.py` files.

In the `train.py` file, you can add the F1 score calculation code after the relevant results calculations. Similarly, in the `val.py` file, you can add the F1 score calculation code after the AP calculation code.

To print the F1 score for all classes, use `f1(output, target, threshold=0.5, multiclass=True)`. For a single class, use `f1(output, target, threshold=0.5, multiclass=False)`.

Please note that these instructions are based on previous versions, so review the code and make necessary adjustments according to the version you are using.

Feel free to ask if you have any further questions or need assistance.

Best,

**Comment by gf-zhong** [comment]
> 好的，谢谢，但只需要更改 train.py 和 val.py 文件还是其他文件也需要更改？ 应该是utils.loggers。**init**文件要修改吗？

Hello, may I ask if the problem has been resolved? Is it convenient to provide a solution? thanks

**Comment by glenn-jocher** [comment]
@gf-zhong hi there!

Thank you for your question. To print the F1 score during training and validation in YOLOv5, you need to modify the `train.py` and `val.py` files. There is no need to modify the `utils.loggers.__init__` file for this purpose.

In the `train.py` file, you can add the F1 score calculation code after the relevant results calculations. Similarly, in the `val.py` file, you can add the F1 score calculation code after the AP calculation code.

To print the F1 score for all classes, you can use the `f1(output, target, threshold=0.5, multiclass=True)` function. For calculating the F1 score for a single class, use the `f1(output, target, threshold=0.5, multiclass=False)` function.

Please ensure you review the code and make necessary adjustments according to the version of YOLOv5 you're using.

If you have any further questions or need more assistance, feel free to ask.

Thank you!
