### ISSUE TITLE
设置yolov5实时监测每三秒检测一次

### ISSUE THREAD

**Issue by uesrs** [ultralytics/yolov5#11957]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

设置yolov5实时监测每三秒检测一次

**Comment by glenn-jocher** [comment]
@uesrs hi,

To set YOLOv5 to perform real-time detection every three seconds, you can modify the `detect.py` script in the YOLOv5 repository.

Inside the script, you can add a time interval of three seconds between each detection using `time.sleep(3)`.

Please note that modifying the script may require familiarity with Python and the YOLOv5 codebase.

Let me know if you need any further assistance.

Thank you.

**Comment by uesrs** [comment]
那么如何设置yolov5实时监测，并且每三秒记录一次检测结果存入到数据库呢？谢谢。

**Comment by glenn-jocher** [comment]
@uesrs hi there,

To perform real-time detection using YOLOv5 and record the detection results into a database every three seconds, you can follow these steps:

1. Set up a database connection: First, establish a connection to your preferred database using the appropriate library or driver for your chosen database system.

2. Modify the `detect.py` script: Inside the script, add the code to initiate a database connection and create a table where you can store the detection results. You can use the Python library provided by your chosen database system to execute the necessary queries.

3. Adjust the timing: To ensure detection occurs every three seconds, insert the following line of code just before the detection loop inside `detect.py`: `time.sleep(3)`.

4. Store detection results: In the detection loop, capture the detection results and insert them into the database table you created earlier.

Remember to handle any exceptions that may arise during the database operations and close the database connection when you're done.

Please note that implementing these steps requires some knowledge of Python, database connections, and database operations. Make sure to choose a suitable database system and refer to its documentation for specific implementation details.

Let me know if you have any further questions.

Thanks!
