### ISSUE TITLE
image size

### ISSUE THREAD

**Issue by inginfor** [ultralytics/yolov5#11955]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When training a YOLOv5s model by specifying the image size, the image size should be the actual size of the images in the dataset or the size to which you want to resize before inputting them to the network?

I have images that have different sizes and I would like to resize them to 640, which would be the size of yolov5's input. This is already done automatically, if you run the command !python train.py --img 640 will the images be automatically resized?

**Comment by glenn-jocher** [comment]
@inginfor when training a YOLOv5 model, the `--img` parameter specifies the input resolution of the images, which is the size to which you want to resize the images before inputting them to the network. If you run the command `python train.py --img 640`, the images will be automatically resized to a resolution of 640x640. 

In your case, if you have images with different sizes and you want to resize them to 640x640, setting `--img 640` will resize the images to the desired resolution during training.

**Comment by inginfor** [comment]
thanks and sorry for the question

**Comment by glenn-jocher** [comment]
@inginfor you're welcome! No need to apologize for asking questions. We're here to help. If you have any more questions, feel free to ask.

**Comment by nealresearch** [comment]
Hi, So when we resize our image with varying size to 640 then the polygon(for segmentation) are also scaled to match the resized image, correct?

**Comment by glenn-jocher** [comment]
Yes, when images are resized to 640x640, the polygons for segmentation are also scaled accordingly to match the resized images.
