### ISSUE TITLE
AttributeError: 'DetectionModel' object has no attribute 'get'

### ISSUE THREAD

**Issue by pizzatakeaway** [ultralytics/yolov5#11967]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Hi! Executing Yolov5 inside a container for the images "nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04" or "nvidia/cuda:12.0.0-cudnn8-runtime-ubuntu22.04" I got following error: 

```
Optimizer stripped from yolov5/runs/train/exp/weights/last.pt, 14.9MB
Traceback (most recent call last):
  File "/root/.clearml/venvs-builds/3.10/task_repository/myproject.git/clearml/yolov5/train.py", line 652, in <module>
    main(opt)
  File "/root/.clearml/venvs-builds/3.10/task_repository/myproject.git/clearml/yolov5/train.py", line 541, in main
    train(opt.hyp, opt, device, callbacks)
  File "/root/.clearml/venvs-builds/3.10/task_repository/myproject.git/clearml/yolov5/train.py", line 421, in train
    strip_optimizer(f)  # strip optimizers
  File "/root/.clearml/venvs-builds/3.10/task_repository/myproject.git/clearml/yolov5/utils/general.py", line 982, in strip_optimizer
    if x.get('ema'):
  File "/root/.clearml/venvs-builds/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DetectionModel' object has no attribute 'get'

```
It only occurs after the last epoch is completed.
I already tried different Torch versions (1.11.0., 1.13.1 and 2.0.*) but the error persists.
Looking forward to hear your suggestions.

### Environment

- YOLO: YOLOv5 🚀 v7.0-421-g1ec29bd9 Python-3.10.12 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce GTX 1650 Ti with Max-Q Design, 3904MiB)
- OS: Ubuntu 22.04
- Python: python3.10

- Requirements:
absl-py==1.4.0
addict==2.4.0
astunparse==1.6.3
attrs==22.2.0
boto3==1.28.16
botocore==1.31.23
cachetools==5.3.1
certifi==2023.7.22
charset-normalizer==3.2.0
chex==0.1.7
clearml==1.12.1
ConfigSpace==0.7.1
contourpy==1.1.0
coremltools==6.3.0
cycler==0.11.0
Cython==3.0.0
dbus-python==1.2.18
defusedxml==0.7.1
distlib==0.3.7
dm-tree==0.1.8
filelock==3.12.2
flatbuffers==23.5.26
flax==0.6.2
fonttools==4.42.0
furl==2.1.3
gast==0.4.0
gitdb==4.0.10
GitPython==3.1.32
google-auth==2.22.0
google-auth-oauthlib==1.0.0
google-pasta==0.2.0
grpcio==1.56.2
h5py==3.9.0
hpbandster==0.7.4
idna==3.4
importlib-resources==6.0.1
jax==0.4.14
jaxlib==0.4.14
jmespath==1.0.1
joblib==1.3.2
jsonschema==4.19.0
jsonschema-specifications==2023.7.1
jstyleson==0.0.2
keras==2.13.1
kiwisolver==1.4.4
libclang==16.0.6
Markdown==3.4.4
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.7.2
mdurl==0.1.2
ml-dtypes==0.2.0
more-itertools==10.1.0
mpmath==1.3.0
msgpack==1.0.5
netifaces==0.11.0
networkx==2.8.8
numpy==1.24.3
nvidia-cublas-cu11==11.10.3.66
nvidia-cublas-cu12==12.2.4.5
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-nvrtc-cu12==12.2.128
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cuda-runtime-cu12==12.2.128
nvidia-cudnn-cu11==8.5.0.96
nvidia-cudnn-cu12==8.9.4.25
nvidia-pyindex==1.0.9
nvidia-tensorrt==99.0.0
oauthlib==3.2.2
onnx==1.14.0
onnx-simplifier==0.4.33
opencv-python==4.8.0.76
openvino==2023.0.1
openvino-dev==2023.0.1
openvino-telemetry==2023.1.0
opt-einsum==3.3.0
optax==0.1.7
orderedmultidict==1.0.1
packaging==20.9
pandas==2.0.3
pathlib2==2.3.7.post1
patsy==0.5.3
Pillow==9.1.1
platformdirs==3.10.0
protobuf==3.20.3
psutil==5.9.5
py-cpuinfo==9.0.0
pyasn1==0.5.0
pyasn1-modules==0.3.0
Pygments==2.16.1
PyGObject==3.42.1
PyJWT==2.4.0
pyparsing==3.0.9
Pyro4==4.82
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0.1
referencing==0.30.2
requests==2.31.0
requests-oauthlib==1.3.1
rich==13.5.2
rpds-py==0.9.2
rsa==4.9
s3transfer==0.6.1
scikit-learn==1.1.2
scipy==1.11.1
seaborn==0.12.2
serpent==1.41
six==1.16.0
smmap==5.0.0
statsmodels==0.13.1
sympy==1.12
tensorboard==2.13.0
tensorboard-data-server==0.7.1
tensorflow==2.13.0
tensorflow-decision-forests==1.5.0
tensorflow-estimator==2.13.0
tensorflow-hub==0.14.0
tensorflow-io-gcs-filesystem==0.33.0
tensorflowjs==4.10.0
tensorrt==8.6.1
tensorrt-bindings==8.6.1
tensorrt-libs==8.6.1
tensorstore==0.1.41
termcolor==2.3.0
texttable==1.6.7
thop==0.1.1.post2209072238
threadpoolctl==3.2.0
toolz==0.12.0
torch==1.13.1
torchvision==0.14.1
tqdm==4.66.0
typing_extensions==4.5.0
tzdata==2023.3
ultralytics==8.0.151
urllib3==1.26.16
virtualenv==20.24.2
Werkzeug==2.3.6
wrapt==1.15.0
wurlitzer==3.0.3

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@pizzatakeaway hi there! 

Thank you for reporting this issue. The error message you encountered indicates that the 'DetectionModel' object does not have the attribute 'get'. 

To help diagnose the problem, could you provide more information about your setup? It seems you are running YOLOv5 version 7.0-421-g1ec29bd9 with Python 3.10.12 and Torch 1.13.1+cu117. Are you using any specific training configurations or custom code modifications?

Additionally, have you tried running YOLOv5 outside of the container environment to see if the issue persists?

Any additional details you can provide will be helpful in troubleshooting the problem. Looking forward to your response!

**Comment by pizzatakeaway** [comment]
Hi @glenn-jocher! 
It wasn´t any custom code, only a custom dataset. The error also occured in my local environment and as well with the example `python train.py --img 640 --batch 16 --epochs 3 --data coco128.yaml --weights yolov5s.pt`.

Anyway the error appeared after I've updated my forked project. After re-cloning the `ultralytics/yolov5.git` again, the error disappeared. Ergo, something buggy happened when updating :expressionless:    

Thank you for your time!  :rainbow:

**Comment by glenn-jocher** [comment]
@pizzatakeaway Thanks for the update! It's great to hear that the issue has been resolved by re-cloning the YOLOv5 repository. Sometimes issues like this can occur during updates or merges, so re-cloning the repository can help reset everything to a clean state.

If you encounter any further issues or have any other questions, feel free to ask. Have a great day! 😊🌈
