### ISSUE TITLE
Pytorch hub can only detect 1 class?

### ISSUE THREAD

**Issue by nguyendang16** [ultralytics/yolov5#11962]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Currently I am using yolov5 to train for fire and smoke detection. However, the results between detect.py vs pytorch hub are completely different. While I use detect.py, it gives quite good results when it detects both fire and smoke separately, but when I use pytorch hub it only detects smoke even if it's fire like in the picture. Does anyone know how to fix it? Thank you.

![smoke1](https://github.com/ultralytics/yolov5/assets/141717010/14c6025a-e8d5-49d5-9f16-cef6c8fc4d71)
![pytorch_hub](https://github.com/ultralytics/yolov5/assets/141717010/6c7dbfed-dd11-4df1-bcdb-8138b5f9f905)

**Comment by glenn-jocher** [comment]
@nguyendang16 hi there! Thanks for reaching out and sharing your question. I understand that you are experiencing different results between using `detect.py` and `pytorch hub` with YOLOv5 for fire and smoke detection. While `detect.py` gives good results when it detects both fire and smoke separately, `pytorch hub` only detects smoke even when it should detect fire.

It's important to note that PyTorch Hub models, including the YOLOv5 model, are pre-trained models that may not cover all possible classes. It's possible that the YOLOv5 model available in PyTorch Hub was trained on a dataset that doesn't have a specific class for fire detection.

To achieve accurate fire and smoke detection in your task, I recommend fine-tuning the YOLOv5 model on a dataset that includes both fire and smoke examples. By training the model on your specific data, you can ensure that it learns to detect both fire and smoke accurately.

Please let me know if you have any further questions or need additional assistance. I'm here to help!
