### ISSUE TITLE
Option to specify a subset of object classes for training

### ISSUE THREAD

**Issue by definitelyuncertain** [ultralytics/yolov5#11972]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Currently, there is no easy way to configure the data loader to include only labels of a specific subset of classes available in the dataset. It requires hard-coding the classes in the code here: https://github.com/ultralytics/yolov5/blob/2370a5513ebf67bd10b8d15fd6353e008380bc43/utils/dataloaders.py#L532-L533

This request is for a feature that allows such configuration in the data YAML file.

### Use case

Datasets can have lots of classes, but only some of them may be required. For example, if one wanted to train a specialized ground vehicle detector on MS-COCO, which has many more kinds of objects.

I have had to use such a feature in a computationally constrained setting where training for a subset of classes means reduced model size.

### Additional

I've already implemented this for a project. PR coming soon.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@definitelyuncertain thank you for your suggestion and willingness to contribute to YOLOv5! We appreciate your interest in adding the feature to specify a subset of object classes for training through the data YAML file.

Your use case of training a specialized ground vehicle detector on MS-COCO with a reduced model size is indeed valuable. We understand the importance of flexibility in choosing specific classes and will consider your feature request.

We encourage you to submit a pull request with your implementation. Your contribution will help improve the YOLOv5 framework and benefit the entire community.

If you have any questions or need guidance during the PR process, please feel free to ask. We're here to assist you.

Thank you once again for your interest in YOLOv5! We look forward to your contribution.

Kind regards,
Glenn Jocher

**Comment by definitelyuncertain** [comment]
@glenn-jocher  glad to hear you're interested! I've made PR #11973 that implements this feature. Do have a look!

**Comment by glenn-jocher** [comment]
@definitelyuncertain Thank you for your contribution! We greatly appreciate your effort in implementing the feature to specify a subset of object classes for training in YOLOv5. PR #11973 is a valuable addition to the project.

Our team will review the pull request and provide feedback as soon as possible. We encourage the community to test and provide feedback on the proposed changes as well.

Thank you once again for your contribution and for making YOLOv5 even better!

Kind regards,
Glenn Jocher
