### ISSUE TITLE
Unable to Train from 'best.pt' weights

### ISSUE THREAD

**Issue by aravindchakravarti** [ultralytics/yolov5#11974]
Hi @glenn-jocher, 

Sorry, I am asking same question as before. I read all the posted previously. I too have same problem and unable to solve. 

I am training yolov5 in Google Colab. Since, the time in Google colab is limited, and since I don't know how many epochs I may train the network to achieve desired performance; I want to train step by step.

- I started training yolov5 (nano) model from scratch. I trained for 100 epochs, saved the results + weights in google drive, 
`!python train.py --img 640
                    --epochs 100 
                    --data data.yaml 
                    --weights ' '
                    --cfg yolov5n.yaml
                    --batch-size 90 
                    --name person_detection 
                    --project /content/drive/MyDrive/YoloV5_Ultralytics/results/ 
                    --patience 25`
- Then used the `best.pt` in above step to train network again for another 100 epochs. 
`!python train.py --img 640 
                    --epochs 100 
                    --data data.yaml 
                    --weights path/to/best.pt 
                    --cfg yolov5n.yaml 
                    --batch-size 90 
                    --name person_detection 
                    --project /content/drive/MyDrive/YoloV5_Ultralytics/results/ 
                    --patience 25`
- Repeat the step 2 until get desired mAP.

Unfortunately, whenever I want to continue training (i.e., using previous `best.pt`) I am seeing that, yolov5 is training is starting from fresh. Can you please help?!

![image](https://github.com/ultralytics/yolov5/assets/17874288/2bfff7b3-dc91-403a-87d1-a10d983372d8)

_Originally posted by @aravindchakravarti in https://github.com/ultralytics/yolov5/issues/7343#issuecomment-1665931745_

**Comment by glenn-jocher** [comment]
Hi @aravindchakravarti, 

I understand your frustration. When training YOLOv5, if you want to continue training from a previously saved checkpoint (`best.pt` in your case), you need to provide the `--resume` flag along with the checkpoint path. 

Here's an example command to continue training:
```
!python train.py --img 640 
                --epochs 100 
                --data data.yaml 
                --weights path/to/best.pt 
                --cfg yolov5n.yaml 
                --batch-size 90 
                --name person_detection 
                --project /content/drive/MyDrive/YoloV5_Ultralytics/results/ 
                --patience 25 
                --resume
```

With the `--resume` flag, YOLOv5 will load the checkpoint and continue training from where it left off. Make sure to specify the correct path to the `best.pt` file.

I hope this helps! Let me know if you have any further questions.

**Comment by aravindchakravarti** [comment]
@glenn-jocher Thanks for the quick response. 

Actually not a frustration! It's a pleasure to use production ready code!!

`--resume` only works when set epochs are not completed already. Right? Say for example, I wanted to train for 500 epochs, during training process, after some epochs if suddenly server disconnects/power shuts down etc, then I can use `--resume` to _resume_ from the epoch at which disturbance had happened. 

My only issue/problem is upfront I will not be knowing how many epochs I may train! For example, in few projects, I was able to get desired `mAP` as soon as 150 epochs and in some other project, it took more than 1500 epochs. 

So, 

1. Let's assume that I start training with `--epochs 100` to start with.
`!python train.py --img 640  --epochs 100  --data data.yaml  --weights ''  --cfg yolov5n.yaml  --batch-size 90  --name person_detection  --project /content/drive/MyDrive/YoloV5_Ultralytics/results/  --patience 25`

2. Then after 100 epochs, I may not be satisfied with results (i.e., mAP). So, I decide to train another 100 epoch. So, natually I would like to use `best.pt` from above (basically load the Yolov5 with `best.pt` from previous run) and then continue training from there.
When I do step 2, using command 
`!python train.py --img 640  --epochs 100  --data data.yaml  --weights path/to/best.pt  --cfg yolov5n.yaml  --batch-size 90  --name person_detection  --project /content/drive/MyDrive/YoloV5_Ultralytics/results/  --patience 25`

The 'mAP' is resetting close to zero. May be some issue with higher learning rate?! Because I read that `--resume` feature will give the exact learning rate which was previously calculated; where as command in step 2, may restart higher learning rate thinking it is a fresh training!


Also, 
I tried your suggested
`!python train.py --img 640 
                --epochs 100 
                --data data.yaml 
                --weights path/to/best.pt 
                --cfg yolov5n.yaml 
                --batch-size 90 
                --name person_detection 
                --project /content/drive/MyDrive/YoloV5_Ultralytics/results/ 
                --patience 25 
                --resume
` 
I got `AssertionError: runs/train/..../last.pt training to 100 epochs finished, nothing to resume`

**Comment by glenn-jocher** [comment]
@aravindchakravarti Thanks for the clarification!

I apologize for the confusion. You are correct that `--resume` is typically used when training is interrupted and you want to continue training from the last saved checkpoint. 

To achieve what you want, you can use the `--resume` flag along with the `--epochs` flag set to the desired total number of training epochs. This way, if you want to train for a specific number of epochs (e.g., 500), you can start training with a smaller number of epochs (e.g., 100), and then resume training and continue for the remaining epochs.

Here's an example command:
```python
!python train.py --img 640 
                --epochs 500 
                --data data.yaml 
                --weights '' 
                --cfg yolov5n.yaml 
                --batch-size 90 
                --name person_detection 
                --project /content/drive/MyDrive/YoloV5_Ultralytics/results/ 
                --patience 25
```

After training for the initial 100 epochs, you can then continue training with the same command but with the `--resume` flag added:
```python
!python train.py --img 640 
                --epochs 500 
                --data data.yaml 
                --weights path/to/best.pt 
                --cfg yolov5n.yaml 
                --batch-size 90 
                --name person_detection 
                --project /content/drive/MyDrive/YoloV5_Ultralytics/results/ 
                --patience 25 
                --resume
```

Regarding the issue you encountered with `AssertionError: runs/train/..../last.pt training to 100 epochs finished, nothing to resume`, this can happen if the training process was not interrupted and completed the specified number of epochs without being stopped. In that case, there is no need to use `--resume` since there is no interrupted training session.

I hope this helps! Let me know if you have any further questions.

**Comment by aravindchakravarti** [comment]
Thanks @glenn-jocher for clarifying!!!

**Comment by glenn-jocher** [comment]
Hi @aravindchakravarti,

I'm glad I could provide some clarification for you! If you have any more questions or need further assistance, feel free to ask. Happy training with YOLOv5!

**Comment by Muhammad-ismail786** [comment]
I am training yolov8 in Google Colab. Since, the time in Google colab is limited, and since I don't know how many epochs I may train now we want to continue the training from the previous epoches so is there any flag for yolov8

**Comment by glenn-jocher** [comment]
@Muhammad-ismail786 hi there!

To continue training from a previous checkpoint in YOLOv8, you can simply use the `--weights` flag pointing to your last saved checkpoint when starting the training process again. 

For example:
```bash
!python train.py --img 640 --batch 16 --epochs 100 --data your_dataset.yaml --weights /path/to/your/last_checkpoint.pt
```

This will automatically resume training from where it left off, using the specified checkpoint. No additional flags are needed for this operation in YOLOv8.

Happy training! 😊
