### ISSUE TITLE
detect.py中 imgsz改为1280后检测无结果 

### ISSUE THREAD

**Issue by uesrs** [ultralytics/yolov5#11985]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

权重文件是用imgsz=1280训练出来的，当我想要进行检测时，detect.py中 imgsz 改为1280后检测无结果 

### Additional

![image](https://github.com/ultralytics/yolov5/assets/118713813/9d4a8172-9b7f-41de-9ad2-7e5e2a5d80d4)

**Comment by glenn-jocher** [comment]
@uesrs hi there! It looks like you're experiencing issues with setting imgsz to 1280 in detect.py. The image you've shared isn't accessible, so I'm not able to view the exact problem.

Setting imgsz to 1280 should work for detection, assuming it matches the size of your trained images. However, be sure to confirm that your model's stride and anchor settings are compatible with this new imgsz value. You can find more details about this in the YOLOv5 documentation at https://docs.ultralytics.com/yolov5. If you continue to experience issues, feel free to provide more details or check the documentation for troubleshooting tips. Good luck!

**Comment by uesrs** [comment]
我之前使用的时python3.8版本，我更换为python3.9版本后就没事了

**Comment by glenn-jocher** [comment]
@uesrs glad to hear that the issue is resolved after switching to Python 3.9! It's possible that there might have been some compatibility issue with Python 3.8. If you encounter any more issues or have further questions, feel free to reach out. Happy detecting!
