### ISSUE TITLE
How to use yolov5 with 1280X1280 image size??

### ISSUE THREAD

**Issue by sangramdhurve** [ultralytics/yolov5#11981]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to train an object detector for small objects with 300+ classes, I'm trying to use the yolov5x6 model while hitting the command line -

python3 train.py --batch 16 --cfg /home/sangramdh/jupyter/CV/ultralytics/yolov5/yolov5/data/hyps/hyp.scratch-high.yaml --weights [yolov5x6.pt](http://yolov5x6.pt/) --data /home/sangramdh/jupyter/CV/ultralytics/data/data.yaml --img 1280 --epochs 2

it is throughing KeyError: 'nc'

please give me some suggestion what to do and how can I working with this idea, Thanks in advance to helpers.

### Additional

Traceback (most recent call last):
  File "/home/sangramdh/jupyter/CV/ultralytics/yolov5/yolov5/train.py", line 647, in <module>
    main(opt)
  File "/home/sangramdh/jupyter/CV/ultralytics/yolov5/yolov5/train.py", line 536, in main
    train(opt.hyp, opt, device, callbacks)
  File "/home/sangramdh/jupyter/CV/ultralytics/yolov5/yolov5/train.py", line 130, in train
    model = Model(cfg or ckpt['model'].yaml, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)  # create
  File "/home/sangramdh/jupyter/CV/ultralytics/yolov5/yolov5/models/yolo.py", line 179, in __init__
    if nc and nc != self.yaml['nc']:
KeyError: 'nc'

**Comment by glenn-jocher** [comment]
@sangramdhurve to train a YOLOv5 model with a 1280x1280 image size, you can modify the `--img-size` argument in the train.py command:

```bash
python train.py --batch 16 --cfg /home/sangramdh/jupyter/CV/ultralytics/yolov5/data/hyps/hyp.scratch-high.yaml --weights yolov5x6.pt --data /home/sangramdh/jupyter/CV/ultralytics/data/data.yaml --img-size 1280 --epochs 2
```
Regarding the KeyError you are experiencing, it looks like you need to specify the number of classes using `--nc` argument in the data.yaml file. Make sure to set `nc` to the correct number of classes that you have.

Let me know if this resolves your issue or if you need further assistance! Good luck with your YOLOv5 training!
