### ISSUE TITLE
inference results in training different from demo 

### ISSUE THREAD

**Issue by bdytx5** [ultralytics/yolov5#11982]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

when using ""import torch

# Model
model = torch.hub.load("ultralytics/yolov5", "yolov5s")  # or yolov5n - yolov5x6, custom

# Images
img = "https://ultralytics.com/images/zidane.jpg"  # or file, Path, PIL, OpenCV, numpy, list

# Inference
results = model(img)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc."" for infence, I simply get no detections. However, when i use detect.py, I get perfect results. There is a bug somewhere. 

### Minimal Reproducible Example

no need 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@bdytx5 hi there! Thanks for reaching out. It sounds like the issue might be related to the way the image is being provided to the model during inference. 

In the `torch.hub.load` method you're using, ensure that the image data type being provided is compatible with the model's input format. You can refer to the documentation at https://docs.ultralytics.com/yolov5 for more details on input requirements for inference. 

Regarding the difference in results between your custom inference code and the `detect.py` script, there could be a disparity in the pre-processing steps or the way the image is being loaded.

Let me know if this helps, and feel free to ask if you have further questions!
