### ISSUE TITLE
Confidence level of detection is different in ultralytics tool compared to opencv code

### ISSUE THREAD

**Issue by Pedro-Leitek** [ultralytics/yolov5#11991]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,

I asked the following in opencv forum, but I still didn't get an answer. This is urgent please help:

For the same image and model (.onnx) I made the inference using ultralytics tool and also with the opencv code found in [Object Detection using YOLOv5 OpenCV DNN in C++ and Python](https://learnopencv.com/object-detection-using-yolov5-and-opencv-dnn-in-c-and-python/)

With the ultralytics tool, I was able to get 86% confidence, while with the opencv code I got 25%.

Without showing the modified code referenced above as it is from the company I work for, are you able to give me hints to why this is happening? I’m making inference with the yolov5m6 model and 1280x1280 image input size.

Thank you

**Comment by glenn-jocher** [comment]
@Pedro-Leitek I haven't tried opencv inference myself, but one possible failure mode may be passing in images with the wrong color order, i.e. RGB vs BGR. For the correct input formats for `ultralytics` see https://docs.ultralytics.com/modes/predict/#inference-sources

<img width="2096" alt="Screenshot 2023-08-14 at 19 02 50" src="https://github.com/ultralytics/yolov5/assets/26833433/6ed8166c-771b-4017-aff0-39d1d0b209d6">

**Comment by Pedro-Leitek** [comment]
> @Pedro-Leitek I haven't tried opencv inference myself, but one possible failure mode may be passing in images with the wrong color order, i.e. RGB vs BGR. For the correct input formats for `ultralytics` see https://docs.ultralytics.com/modes/predict/#inference-sources
> 
> <img alt="Screenshot 2023-08-14 at 19 02 50" width="2000" src="https://user-images.githubusercontent.com/26833433/260520976-6ed8166c-771b-4017-aff0-39d1d0b209d6.png">

@glenn-jocher I was also wondering if that was the cause. I tried to use cv2.cvtColor(frame, cv2.COLOR_BGR2RGB), and I was able to increase the confidence value. But it was still very low compared to the 86 I get with your tool (I got 48). Also the blobfromimage function apparently already does that (?)

I have the code here :            

blob = cv2.dnn.blobFromImage(frame, 1 / 255.0, (1280, 1280), swapRB=True, crop=False)

**Comment by Pedro-Leitek** [comment]
@glenn-jocher Hi, do you have more hints of what possible is the problem? Thanks

**Comment by Pedro-Leitek** [comment]
I have a new update: It turns out your tool gives 25% confidence if the image is resized to 1280x 1280. Basically this is happening in cv2.dnn.blobFromImage(frame, 1 / 255.0, (1280, 1280), swapRB=True, crop=False) where the image is resized.
Can you explain me how detect.py works with the imgsz parameter? Do you resize the images?

Thanks

**Comment by Pedro-Leitek** [comment]
@glenn-jocher Hi there!

I discovered the issue. Basically when using cv2.dnn.blobFromImage(frame, 1 / 255.0, (1280, 1280), swapRB=True, crop=False) the image is resized, but distorted. So the solution passes by creating a square numpy array with the maximum of the dimensions of the image (height and width), put the image at the top of the numpy array (making it as a 16:9 image with padding) and only then I resize the image to 1280x1280. With this strategy https://medium.com/mlearning-ai/detecting-objects-with-yolov5-opencv-python-and-c-c7cf13d1483c I was able to get 79% confidence level. I don't know why the value is still below the 84-86%, but I'm on the right track. In detect.py do you do any more preprocessing to the image?

Thanks

**Comment by glenn-jocher** [comment]
@Pedro-Leitek Great to hear you've made progress! In `detect.py`, the `imgsz` parameter controls the input image size for inference, with no additional preprocessing applied to the image. The resizing and preprocessing are handled by the `detect.py` script directly. Good luck with your further experimentation!
