### ISSUE TITLE
libgcc_s.so.1 must be installed for pthread_cancel to work

### ISSUE THREAD

**Issue by yunchangxiaoguan** [ultralytics/yolov5#1199]
## ❔Question

python train.py  --batch-size 64 --data ./data/car.yaml --cfg ./models/car_m.yaml --weights 'weights/yolov5m.pt' --device 0,1 --epoch 50
Using CUDA device0 _CudaDeviceProperties(name='Tesla K80', total_memory=11441MB)
           device1 _CudaDeviceProperties(name='Tesla K80', total_memory=11441MB)
Namespace(adam=False, batch_size=64, bucket='', cache_images=False, cfg='./models/car_m.yaml', data='./data/car.yaml', device='0,1', epochs=50, evolve=False, global_rank=-1, hyp='data/hyp.scratch.yaml', image_weights=False, img_size=[640, 640], local_rank=-1, logdir='runs/', multi_scale=False, name='', noautoanchor=False, nosave=False, notest=False, rect=False, resume=False, single_cls=False, sync_bn=False, total_batch_size=64, weights='weights/yolov5m.pt', workers=8, world_size=1)
Start Tensorboard with "tensorboard --logdir runs/", view at http://localhost:6006/
Hyperparameters {'lr0': 0.01, 'lrf': 0.2, 'momentum': 0.937, 'weight_decay': 0.0005, 'warmup_epochs': 3.0, 'warmup_momentum': 0.8, 'warmup_bias_lr': 0.1, 'box': 0.05, 'cls': 0.5, 'cls_pw': 1.0, 'obj': 1.0, 'obj_pw': 1.0, 'iou_t': 0.2, 'anchor_t': 4.0, 'fl_gamma': 0.0, 'hsv_h': 0.015, 'hsv_s': 0.7, 'hsv_v': 0.4, 'degrees': 0.0, 'translate': 0.1, 'scale': 0.5, 'shear': 0.0, 'perspective': 0.0, 'flipud': 0.0, 'fliplr': 0.5, 'mosaic': 1.0, 'mixup': 0.0}

Transferred 506/514 items from weights/yolov5m.pt
Optimizer groups: 86 .bias, 94 conv.weight, 83 other
Scanning images: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 66488/66488 [00:05<00:00, 11291.68it/s]
libgcc_s.so.1 must be installed for pthread_cancel to work
Aborted (core dumped)

I have install  libgcc_s.so.1 ，and copy it into /lib/， /lib64 ，how to solve it，thank you！

**Comment by glenn-jocher** [comment]
@yunchangxiaoguan it appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below. 


## Requirements

**Python 3.8** or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including **`torch>=1.6`**. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by yunchangxiaoguan** [comment]
> @yunchangxiaoguan看来您可能有环境问题。如果尝试在本地运行YOLOv5，请确保满足所有依赖项要求。如果有疑问，请创建一个新的虚拟Python 3.8环境，克隆最新的存储库（**每天更改代码**），然后`pip install -r requirements.txt`再次克隆。我们还强烈建议您使用以下经过验证的环境之一。
> 
> ## 要求
> ****安装了所有[requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt)依赖项的**Python 3.8**或更高版本，包括**`torch>=1.6`**。要安装运行：
> 
> ```shell
> $ pip install -r requirements.txt
> ```
> 
> ## 环境环境
> YOLOv5可以在以下任何经过验证的最新环境中运行（预安装了所有依赖项，包括[CUDA](https://developer.nvidia.com/cuda) / [CUDNN](https://developer.nvidia.com/cudnn)，[Python](https://www.python.org/)和[PyTorch](https://pytorch.org/)）：
> 
> * ****带有免费GPU的**Google Colab笔记本**：[![在Colab中打开](https://camo.githubusercontent.com/52feade06f2fecbf006889a904d221e6a730c194/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb)
> * ****具有免费GPU的**Kaggle笔记本**：[https](https://www.kaggle.com/models/ultralytics/yolov5)：[//www.kaggle.com/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
> * **Google Cloud**深度学习VM。请参阅[GCP快速入门指南](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
> * **泊坞窗图像** https://hub.docker.com/r/ultralytics/yolov5。请参阅[Docker快速入门指南](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker拉](https://camo.githubusercontent.com/caa63570e9f4e9771b02fc86d87e78aad3bf9785/68747470733a2f2f696d672e736869656c64732e696f2f646f636b65722f70756c6c732f756c7472616c79746963732f796f6c6f76353f6c6f676f3d646f636b6572)
> 
> ## 状态
> ![CI CPU测试](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)
> 
> 如果此标志为绿色，则所有[YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions)持续集成（CI）测试都通过。这些测试评估的基本YOLOv5功能的正常运行，包括培训（[train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)），测试（[test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)），推理（[detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)）和出口（[export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)在MacOS，Windows和Ubuntu的）。

thanks，I update the torchvision ,and run ok

**Comment by pderrenger** [comment]
@yunchangxiaoguan great to hear that updating torchvision resolved the issue! If you have any more questions, feel free to ask.
