### ISSUE TITLE
Handle overlap of bounding boxes contained within each other

### ISSUE THREAD

**Issue by TimotheeWrightFicha** [ultralytics/yolov5#11992]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello @glenn-jocher,

I want to remove bounding boxes that are almost contained within each other. In my case a small bbox is contained into a big bbox. So IoU is small and cannot be used to remove this case. Actually this happened while I had a small iou for inference, hence my question

I've seen that there is an agnostic parameter but as mentioned [in a previous issue](https://github.com/ultralytics/yolov5/discussions/2248) it's only for "different classes" and here my two bbox comes from the same class.

![Example of the bboxes](https://github.com/ultralytics/yolov5/assets/125884618/2d84ab13-a0e8-410a-bfec-526177e10eb7)

Should I handle this case myself in the code or is there build in code for this in yolov5 ?

Thank you for your help as always

**Comment by glenn-jocher** [comment]
@TimotheeWrightFicha hi there!

Thanks for reaching out! For handling overlapping bounding boxes contained within each other, you can use the agnostic NMS (Non-Maximum Suppression) setting along with the `max_det` argument to automatically merge bounding boxes with multiple detections. This scenario is common in scenarios like detecting nested objects. 

To achieve this, you can set `agnostic_nms` to `True` in your inference code and use a higher value for `max_det`.

Here's some sample code:
```python
results = model(img, size=640)  # replace with your image and desired size
results.show()  # show results
```

Additionally, you may want to experiment with different IoU (Intersection over Union) thresholds and NMS techniques to further refine the results based on your specific use case.

Let me know if you need further assistance!
