### ISSUE TITLE
Difference between Ensemble with one Model and the original Detection Model

### ISSUE THREAD

**Issue by Ayame4** [ultralytics/yolov5#11990]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,

As I have thus far understood: 

In detection (`detect.py`) with yolov5s.pt as weights, first [DetectMultiBackend](https://github.com/ultralytics/yolov5/blob/dd104811c2e0419529aa7177ce160321e9694837/models/common.py#L356C63-L356C63) is called

```
if pt:  # PyTorch
       model = attempt_load(weights if isinstance(weights, list) else w, device=device, inplace=True, fuse=fuse)
```

which then creates an Ensemble where the model weights of the Detection Model are loaded. 

Now since only one model is used in the Ensemble, I am trying to replace the Ensemble with the DetectionModel directly:

```
from models.yolo import DetectionModel

if pt:  # PyTorch
    ckpt = torch.load(w, map_location='cpu')
    model = DetectionModel(ckpt['model'].yaml, ch=3).to(device)
```

however the prediction of the second way yields almost no results.

Could you help me understand what is the difference between the Ensemble with one model and the model itself? Is it possible to use the DetectionModel directly and obtain the same predictions?

I don't have a lot of experience, so I would be grateful for some help.

### Additional

Note: in order to use the DetectionModel I moved DetectMultiBackend to a new file to avoid circular dependencies.

**Comment by Ayame4** [comment]
The problem was that the DetectionModel doesn't load the weights from ckpt as input, rather the weights needed to be loaded like this:

```
from models.yolo import DetectionModel

if pt:  # PyTorch
    model = torch.load(w, map_location='cpu')['model'].float()
```

**Comment by glenn-jocher** [comment]
@Ayame4 hi there,

Thank you for sharing your findings. Indeed, the `DetectionModel` loads the weights a bit differently from the Ensemble. Your solution to load the weights directly using `torch.load` is correct, and it should yield the same predictions as using the Ensemble.

Your diligence and adaptability in finding this solution are commendable. If you have further questions or need additional assistance, feel free to ask!
