### ISSUE TITLE
CPU version

### ISSUE THREAD

**Issue by Khalilgithub-lab** [ultralytics/yolov5#11995]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Yolov5 CPU version

### Additional

hello there. i am new in this field and i need the code to implement yolov5 on CPU. Help in this regard will be appreciated.

**Comment by MohammadsAdrA-AI** [comment]
If you want to use detect.py just use --device cpu 
if you want to use one line inference by model = torch.hub(......, device = 'cpu')

**Comment by glenn-jocher** [comment]
@MohammadsAdrA-AI hello! If you want to run YOLOv5 on CPU, you can use `--device cpu` with `detect.py`. If you prefer to do one-line inference, you can set the device to 'cpu' using `model = torch.hub(...)`. Hope that helps! If you need more details, you can check out our documentation at https://docs.ultralytics.com/yolov5.
