### ISSUE TITLE
NCLL timeout when trained on Objects365

### ISSUE THREAD

**Issue by michaelzhang-ai** [ultralytics/yolov5#11996]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

[E ProcessGroupNCCL.cpp:828] [Rank 5] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=3, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1800073 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:828] [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=3, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1800199 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:828] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=3, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1800060 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:828] [Rank 7] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=3, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1800260 milliseconds before timing out.
asimov-235:3685801:3685979 [5] NCCL INFO [Service thread] Connection closed by localRank 5
asimov-235:3685801:3685926 [0] NCCL INFO comm 0x55e57923c570 rank 5 nranks 8 cudaDev 5 busId 89000 - Abort COMPLETE
[E ProcessGroupNCCL.cpp:455] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:460] To avoid data inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 5] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=3, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1800073 milliseconds before timing out.
asimov-235:3685797:3685934 [0] NCCL INFO comm 0x56408c7d69e0 rank 1 nranks 8 cudaDev 1 busId 1b000 - Abort COMPLETE
[E ProcessGroupNCCL.cpp:455] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:460] To avoid data inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=3, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1800060 milliseconds before timing out.
asimov-235:3685798:3685930 [0] NCCL INFO comm 0x55fa20a6b190 rank 2 nranks 8 cudaDev 2 busId 3d000 - Abort COMPLETE
[E ProcessGroupNCCL.cpp:455] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:460] To avoid data inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=3, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1800199 milliseconds before timing out.
asimov-235:3685803:3685937 [0] NCCL INFO comm 0x5574750414d0 rank 7 nranks 8 cudaDev 7 busId b3000 - Abort COMPLETE
[E ProcessGroupNCCL.cpp:455] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:460] To avoid data inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 7] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=3, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1800260 milliseconds before timing out.
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3685796 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3685799 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3685800 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3685802 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 1 (pid: 3685797) of binary: /mnt/home/sibo/.conda/envs/yolov5/bin/python
Traceback (most recent call last):
  File "/mnt/home/sibo/.conda/envs/yolov5/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/mnt/home/sibo/.conda/envs/yolov5/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/home/sibo/.conda/envs/yolov5/lib/python3.8/site-packages/torch/distributed/run.py", line 798, in <module>
    main()
  File "/mnt/home/sibo/.conda/envs/yolov5/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/mnt/home/sibo/.conda/envs/yolov5/lib/python3.8/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/mnt/home/sibo/.conda/envs/yolov5/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/mnt/home/sibo/.conda/envs/yolov5/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mnt/home/sibo/.conda/envs/yolov5/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
========================================================
train.py FAILED
--------------------------------------------------------
Failures:
[1]:
  time      : 2023-08-14_12:06:41
  host      : asimov-235.svail.baidu.com
  rank      : 2 (local_rank: 2)
  exitcode  : -6 (pid: 3685798)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 3685798
[2]:
  time      : 2023-08-14_12:06:41
  host      : asimov-235.svail.baidu.com
  rank      : 5 (local_rank: 5)
  exitcode  : -6 (pid: 3685801)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 3685801
[3]:
  time      : 2023-08-14_12:06:41
  host      : asimov-235.svail.baidu.com
  rank      : 7 (local_rank: 7)
  exitcode  : -6 (pid: 3685803)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 3685803
--------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-14_12:06:41
  host      : asimov-235.svail.baidu.com
  rank      : 1 (local_rank: 1)
  exitcode  : -6 (pid: 3685797)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 3685797
========================================================

### Environment

YOLOv5 🚀 v7.0-0-g915bbf29 Python-3.8.13 torch-2.0.1+cu117

### Minimal Reproducible Example

```
python -m torch.distributed.run --nproc_per_node 8 train.py --data Objects365.yaml --weights yolov5m_Objects365.pt --batch 128 --workers 8 --freeze 10 --img 640 --device 0,1,2,3,4,5,6,7 --epochs 100 --cache disk
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by michaelzhang-ai** [comment]
Even if I increase timeout from 1800s(30min) to 18000s (5hr), I can only load 44% data of objects365 train. Could I as how to expeditite load data?

[E ProcessGroupNCCL.cpp:460] To avoid data inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=3, OpType=ALLREDUCE, Timeout(ms)=18000000) ran for 18006754 milliseconds before timing out.
train: Caching images (867.2GB disk):  44%|████▍     | 634759/1443668 4:12:06

**Comment by glenn-jocher** [comment]
@sibozhang hi there! Increasing the timeout for collective operations is a good start. To expedite data loading, you could first try optimizing your data loading pipeline. This may involve using a faster storage device, pre-processing the data to reduce its size, or parallelizing the data loading process. Additionally, you may want to consider optimizing your input pipeline specifically for Objects365 dataset. Our [Ultralytics Docs](https://docs.ultralytics.com/yolov5) provide detailed information on optimizing data loading and training, which should help you address this issue more effectively. Let me know if you need further assistance!
