### ISSUE TITLE
Webcam connection problem

### ISSUE THREAD

**Issue by sjundo** [ultralytics/yolov5#11998]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I bought a Logitech Brio 4k product and ran it in Ubuntu 20.04 environment to connect webcam  for yolov5. The device number is 2 so I ran --source 2, but the color image is output normally on the laptop, but when I connect it to intel nuc, the black and white light screen is output like an infrared camera, is there a solution?

### Additional

![Uploading image.png…]()
![KakaoTalk_20230814_150854299](https://github.com/ultralytics/yolov5/assets/102020168/ec0e5bec-38a9-4f1f-a285-3b8f58a013a6)

**Comment by glenn-jocher** [comment]
@sjundo hi there! The issue might be related to the video input format or settings on the Intel NUC. Could you try adjusting the camera settings, such as resolution and color depth, on the Intel NUC to see if that resolves the black and white output? Additionally, you may want to check if the camera drivers are properly installed on the Intel NUC. Let me know if these suggestions help, and feel free to refer to the YOLOv5 documentation for more detailed guidance. Cheers!
