### ISSUE TITLE
Does training image size affecting the inference?

### ISSUE THREAD

**Issue by itsjustrafli** [ultralytics/yolov5#12009]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

So, I am training YOLOv5s custom model based on pre-trained checkpoint with `img` argument set to 640. My question is does image size defined in training affect inference for live feed input (eg: webcam)?

For instance, I have 1080p width resolution webcam used for live inferencing. Would the camera feed resolution cropped to 640 since the input image size of the training defined at 640?

**Comment by HtwoOtwo** [comment]
It will not crop to 640 but will resize to 640 using letterbox technique.

**Comment by glenn-jocher** [comment]
@HtwoOtwo it's great that you're training a custom YOLOv5s model! The image size defined during training does not directly affect the resolution of your live feed input during inference. Instead, the input image from your webcam will be resized to 640 using the letterbox technique. This technique maintains the original aspect ratio of the image while ensuring that it fits within the desired size. So, your 1080p webcam feed will be resized to 640 while preserving the aspect ratio. Keep up the good work!
