### ISSUE TITLE
val.py confidence warning

### ISSUE THREAD

**Issue by monster1129** [ultralytics/yolov5#12002]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

In the yolov5 repository, confidence>0.001 in val.py will warn of incorrect metric, but this seems to be fixed in the new yolov8 repository. I would like to ask about the differences in the code for calculating metric between the two repositories, or is there any plan to fix this warning in yolov5

**Comment by glenn-jocher** [comment]
@monster1129 hi there! Thanks for reaching out. The confidence threshold warning in val.py for confidences below 0.001 can safely be ignored as it doesn't impact the metrics. YOLOv8 indeed has some improvements, but the YOLOv5 repo is still actively maintained and valuable contributions are always appreciated. If you have further questions, feel free to ask!
