### ISSUE TITLE
About the pre-processing auto-completion part of the image

### ISSUE THREAD

**Issue by Jayus-su** [ultralytics/yolov5#12003]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi author, because of the experimental needs, I need to key out the dark areas of the image, and then fed into yolov5 for training, but I found that yolov5 will automatically complement my keyed out features, how to turn off this function?

**Comment by glenn-jocher** [comment]
@Jayus-su hi there! Thanks for reaching out. YOLOv5 indeed applies auto-completion to input images for training, which can be useful in many cases. If you want to disable this feature, you can manually preprocess your images to achieve the desired effect before feeding them into YOLOv5. This gives you control over the specific transformations applied to your data. For more details on custom data preprocessing, you can refer to the Ultralytics YOLOv5 documentation at https://docs.ultralytics.com/yolov5. Let me know if you need further assistance with this!
