### ISSUE TITLE
runs\train\exp3 is not a directory

### ISSUE THREAD

**Issue by g-hano** [ultralytics/yolov5#12008]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I wanted to train it with my own data. I ran this command

`!cd  yolov5 && python train.py --img 320 --batch 16 --epochs 500 --data dataset.yaml --weights yolov5s.pt --workers 2`

but I get this error message
```
train: weights=yolov5s.pt, cfg=, data=dataset.yaml, hyp=data\hyps\hyp.scratch-low.yaml, epochs=500, batch_size=16, imgsz=320, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, noplots=False, evolve=None, bucket=, cache=None, image_weights=False, device=, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=2, project=runs\train, name=exp, exist_ok=False, quad=False, cos_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, seed=0, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest
github: up to date with https://github.com/ultralytics/yolov5 
YOLOv5  v7.0-210-gdd10481 Python-3.11.3 torch-2.0.1+cu118 CUDA:0 (NVIDIA GeForce RTX 3080 Laptop GPU, 16384MiB)

hyperparameters: lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0
Comet: run 'pip install comet_ml' to automatically track and visualize YOLOv5  runs in Comet
TensorBoard: Start with 'tensorboard --logdir runs\train', view at http://localhost:6006/
Traceback (most recent call last):
  File "C:\Users\OneDrive\Masaüstü\yolo\yolov5\train.py", line 647, in <module>
    main(opt)
  File "C:\Users\OneDrive\Masaüstü\yolo\yolov5\train.py", line 536, in main
    train(opt.hyp, opt, device, callbacks)
  File "C:\Users\OneDrive\Masaüstü\yolo\yolov5\train.py", line 101, in train
    loggers = Loggers(save_dir, weights, opt, hyp, LOGGER)  # loggers instance
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OneDrive\Masaüstü\yolo\yolov5\utils\loggers\__init__.py", line 100, in __init__
    self.tb = SummaryWriter(str(s))
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\tensorboard\writer.py", line 247, in __init__
    self._get_file_writer()
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\tensorboard\writer.py", line 277, in _get_file_writer
    self.file_writer = FileWriter(
                       ^^^^^^^^^^^
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\tensorboard\writer.py", line 76, in __init__
    self.event_writer = EventFileWriter(
                        ^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorboard\summary\writer\event_file_writer.py", line 72, in __init__
    tf.io.gfile.makedirs(logdir)
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow\python\lib\io\file_io.py", line 513, in recursive_create_dir_v2
    _pywrap_file_io.RecursivelyCreateDir(compat.path_to_bytes(path))
tensorflow.python.framework.errors_impl.FailedPreconditionError: runs\train\exp3 is not a directory
```

**Comment by glenn-jocher** [comment]
@g-hano hi there! It looks like the issue is with the directory `runs\train\exp3`, which is not being detected as a directory. It seems to be related to the TensorBoard logging. 

To address this, make sure that the `runs\train` directory exists before you start the training. You might want to create it manually if it doesn't exist. Also, consider using the forward slash `/` instead of the backslash `\` in your file paths to avoid any unexpected errors.

Let me know if you have any more questions or need further assistance!

**Comment by 2021011131** [comment]
Hello, have you resolved this issue? I have also encountered this situation.

**Comment by 2021011131** [comment]
Hello,  I have also encountered this situation. When I changed the Chinese path to the English path,this error will no longer appear.

**Comment by glenn-jocher** [comment]
Hello @2021011131 and @user,

Thank you for bringing this to our attention. It appears that the issue may be related to the file path being used. As @user mentioned, changing the path from Chinese to English resolved the issue for them. This suggests that there might be a problem with how certain characters in the path are being handled.

To help us investigate further, could you please provide a minimum reproducible code example? This will allow us to better understand the context and reproduce the issue on our end. You can find more information on how to create a minimum reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example). 

Additionally, please ensure that you are using the latest versions of `torch` and the YOLOv5 repository. Sometimes, updating to the latest versions can resolve unexpected issues.

Here's a quick checklist to help you troubleshoot:
1. **Check Directory Paths**: Ensure that the directory paths do not contain special characters or spaces.
2. **Create Necessary Directories**: Manually create the `runs/train` directory if it does not exist.
3. **Update Dependencies**: Make sure you are using the latest versions of `torch` and YOLOv5.

If the issue persists, please share the exact command you are running and any additional error messages you encounter. This will help us provide more targeted assistance.

Thank you for your cooperation, and we look forward to resolving this issue together! 😊
