### ISSUE TITLE
visdrone dataset download

### ISSUE THREAD

**Issue by ampelmannnys** [ultralytics/yolov5#12000]

**Comment by glenn-jocher** [comment]
@ampelmannnys hi there! It looks like your message might have been cut off. If you're looking for the VisDrone dataset to use with YOLOv5, you can download it from the official website or platform where it's provided. Once you have the dataset, you can follow the YOLOv5 documentation for instructions on how to train with custom datasets. If you have any specific questions or need further assistance, feel free to ask. Good luck with your project!
