### ISSUE TITLE
How to regenerate the precision recall and metric reall curves using functions available in utils/metrics. Seems like you need to get matrices containing precision and recall values at diff thresholds from somewhere.

### ISSUE THREAD

**Issue by BobDog2** [ultralytics/yolov5#12010]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question
How can I regenerate the precision recall and metric recall curves using functions available in utils/metrics? Seems like you need to get matrices containing precision and recall values at diff thresholds from somewhere.

**Comment by BobDog2** [comment]
![image](https://github.com/ultralytics/yolov5/assets/142701783/4a33ac7b-f6c6-4ef5-904d-c2b3c61ad4e1)

**Comment by glenn-jocher** [comment]
@BobDog2 to regenerate precision-recall and metric recall curves using functions in `utils/metrics`, you can use the `precision_recall` and `pr_curve` functions. These functions internally compute precision and recall values at different thresholds.

For example, to plot the precision-recall curve:
```python
from utils.metrics import precision_recall, plot_results
...
results = ...  # model results
precision, recall, _ = precision_recall(results, plot=True)
plot_results(precision, recall, ylabel='Precision', xlabel='Recall')
```

Refer to the `utils.metrics` module for more details. Let me know if you need further assistance!
