### ISSUE TITLE
 No module named 'ultralytics.utils' No module named 'ultralytics.utils'

### ISSUE THREAD

**Issue by Allmight0000** [ultralytics/yolov5#12015]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Using cache found in C:\Users\tjcon/.cache\torch\hub\ultralytics_yolov5_master
Please read the below message and think about how it could be solved before posting it on discord.
Traceback (most recent call last):
  File "C:\Users\tjcon\OneDrive\Desktop\AI-Aimbot-2.3.2\main_torch_gpu.py", line 244, in <module>
    main()
  File "C:\Users\tjcon\OneDrive\Desktop\AI-Aimbot-2.3.2\main_torch_gpu.py", line 123, in main
    model = torch.hub.load('ultralytics/yolov5', 'custom', 'best.pt')
  File "C:\Users\tjcon\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\hub.py", line 558, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "C:\Users\tjcon\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\hub.py", line 587, in _load_local
    model = entry(*args, **kwargs)
  File "C:\Users\tjcon/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 83, in custom
    return _create(path, autoshape=autoshape, verbose=_verbose, device=device)
  File "C:\Users\tjcon/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 33, in _create
    from models.common import AutoShape, DetectMultiBackend
  File "C:\Users\tjcon/.cache\torch\hub\ultralytics_yolov5_master\models\common.py", line 38, in <module>
    from ultralytics.utils.plotting import Annotator, colors, save_one_box
ModuleNotFoundError: No module named 'ultralytics.utils'
No module named 'ultralytics.utils'

### Environment

.

### Minimal Reproducible Example

.

### Additional

.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Allmight0000 hi there,

Thanks for reaching out. It looks like you're encountering an error related to the `ultralytics.utils` module not being found.

This issue could potentially be resolved by making sure you have the latest version of the YOLOv5 repository installed. Please try updating your installation to the latest version and see if the issue persists. 

If the problem still occurs after updating, it may be helpful to provide more information about your environment and the steps you followed to reproduce the issue. This will allow us to better understand the problem and provide a more accurate solution.

Please let me know if there's anything else I can assist you with.

Kind regards,
Glenn

**Comment by whbruce** [comment]
I am seeing a similar problem. Configuration has been working (last successful build 7/21) but is now broken as poster shows. We are using poetry with `ultralytics 8.0.109`. 

```
Downloading: "https://github.com/ultralytics/yolov5/zipball/master" to /home/ubuntu/.cache/torch/hub/master.zip
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
<snip>
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/XXXXX-5esAkS-Z-py3.11/lib/python3.11/site-packages/torch/hub.py", line 558, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/XXXXX-5esAkS-Z-py3.11/lib/python3.11/site-packages/torch/hub.py", line 587, in _load_local
    model = entry(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 83, in custom
    return _create(path, autoshape=autoshape, verbose=_verbose, device=device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 33, in _create
    from models.common import AutoShape, DetectMultiBackend
  File "/home/ubuntu/.cache/torch/hub/ultralytics_yolov5_master/models/common.py", line 38, in <module>
    from ultralytics.utils.plotting import Annotator, colors, save_one_box
ModuleNotFoundError: No module named 'ultralytics.utils'
```

**Comment by glenn-jocher** [comment]
@whbruce hi there,

Thank you for bringing this issue to our attention. We apologize for the inconvenience you're experiencing.

The error message suggests that the `ultralytics.utils` module is not found. This could be due to compatibility issues between the specific version of `ultralytics` (8.0.109) you are using and the YOLOv5 repository.

To resolve this, we recommend updating your installation to the latest version of the YOLOv5 repository. Please ensure that you have the most recent version installed before attempting to use the `ultralytics.utils` module.

If the problem persists after updating, please provide more information about your environment (e.g., Python version, operating system) and the steps you followed to reproduce the issue. This will help us further investigate and provide a more accurate solution.

Thank you for your understanding and patience. Feel free to reach out if you have any further questions.

Regards,
Glenn

**Comment by whbruce** [comment]
I fixed this by pinning yolov5 release version.
```
model = torch.hub.load("ultralytics/yolov5:v7.0", ...)
```

**Comment by glenn-jocher** [comment]
@whbruce glad to hear that you were able to resolve the issue by pinning the YOLOv5 release version! Thank you for sharing your solution. This can be a helpful approach to ensure compatibility between different components.

If you have any further questions or need assistance with anything else, please feel free to ask. We're here to help!

Kind regards,
Glenn

**Comment by glenn-jocher** [comment]
Great to hear that you were able to resolve the issue by pinning the YOLOv5 release version, @Merwanski! Thank you for sharing your solution. If you have any further questions or need assistance with anything else, please feel free to ask.

**Comment by Sarai256** [comment]
> I fixed this by pinning yolov5 release version.
> 
> ```
> model = torch.hub.load("ultralytics/yolov5:v7.0", ...)
> ```

Where do you do this from in the command prompt? or in the train.py file?

**Comment by glenn-jocher** [comment]
@Sarai256 to pin the YOLOv5 release version, you can make the change in your Python code. Specifically, you can modify the line where you load the YOLOv5 model using `torch.hub.load`. Here's an example:

```python
model = torch.hub.load("ultralytics/yolov5:v7.0", ...)
```

Replace the `...` with any additional arguments you need to pass to the `load` function.

You should make this change in the Python file where you are using the YOLOv5 model, such as `train.py` or any other script that loads and uses the YOLOv5 model.

If you have any more questions or need further assistance, please feel free to ask.

**Comment by hasithasene1** [comment]
I tried pining the yolov5 version and it works. But in my case, I'm trying to load a custom model that needs to be loaded locally without downloading from the internet. So I tried the following code,

`model = torch.hub.load('yolov5', 'custom', path=model_name, source='local')`

But I'm getting a similar error 

`  File "/home/hasitha/catkin_ws/src/action_prediction/scripts/yolov5/models/common.py", line 38, in <module>
    from ultralytics.utils.plotting import Annotator, colors, save_one_box
ModuleNotFoundError: No module named 'ultralytics.utils'
`

Can you help me out?

**Comment by glenn-jocher** [comment]
@hasithasene1 to resolve the `ModuleNotFoundError: No module named 'ultralytics.utils'` issue when loading a custom model locally with YOLOv5, you can try the following steps:

1. Make sure you have the necessary dependencies installed, including `torch`, `numpy`, and `opencv-python-headless`, which are required by YOLOv5.

2. Ensure that the `ultralytics` module is installed. You can install it by running `pip install --upgrade ultralytics`.

3. Confirm that you have the latest version of the YOLOv5 repository. You can update it by executing `git pull` in the YOLOv5 directory, or you can download the latest release from GitHub.

4. Verify that the `ultralytics` package is correctly installed by running `python -c "import ultralytics"` in your terminal or command prompt. If no error is displayed, then the package is installed properly.

If you still encounter the same error, please provide more details about your environment (e.g., Python version, operating system) and the specific steps you've taken so far. This information will help us better understand the issue and provide a more accurate solution.

Thank you for your patience and understanding. Let us know if you have any further questions.

**Comment by hasithasene1** [comment]
Your 2nd instruction of upgrading ultralytics worked.

Thank you

**Comment by glenn-jocher** [comment]
@hasithasene1 glad to hear that upgrading the `ultralytics` package resolved the issue for you. You're welcome! If you have any other questions or need further assistance, feel free to ask.

**Comment by ushasai** [comment]
[Wed Nov 29 13:45:29.360409 2023] [wsgi:error] [pid 57498:tid 139624328496704] [remote 14.139.82.6:37133] An error occurred in YOLO processing: Command '/var/www/django_project/env/bin/python /var/www/django_project/yolov5/detect.py --weights Lymphangiectasia.pt --img 336 --conf 0.65 --source /var/www/django_project/media/temp_frames/frame67.jpg --save-txt' returned non-zero exit status 1.
[Wed Nov 29 13:45:29.646593 2023] [wsgi:error] [pid 57498:tid 139624328496704] [remote 14.139.82.6:37133] \r1/1 [==============================] - ETA: 0s
[Wed Nov 29 13:45:29.646854 2023] [wsgi:error] [pid 57498:tid 139624328496704] [remote 14.139.82.6:37133] \b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\r1/1 [==============================] - 0s 238ms/step
Traceback (most recent call last):
  File "/var/www/django_project/yolov5/detect.py", line 46, in <module>
    from ultralytics.utils.plotting import Annotator, colors, save_one_box
ModuleNotFoundError: No module named 'ultralytics'. 

I am getting this error. I have latest version of ultralytics and yolov5. my python version is 3.10 and ubuntu OS. Could you please help me in resolving this issue.

**Comment by glenn-jocher** [comment]
@ushasai it looks like the issue might be related to the environment or paths when running the YOLOv5 inference script within the Apache environment. Here are a few things you can check:

1. Ensure that the Python environment being used by Apache, including the `ultralytics` package, is correctly set up and accessible by the Apache user. You may need to specify the Python executable and environment explicitly in your Apache configuration to ensure the correct environment is used.

2. Verify that the `ULTRALYTICS_PATH` and other relevant environment variables are correctly set for the Apache user. This can be done in the Apache configuration or in a script that sets up the environment before running the YOLOv5 detection script.

3. Double-check the permissions and file paths for the `ultralytics` package and the YOLOv5 repository on the AWS instance to ensure that the Apache user has adequate permissions to access the required modules and files.

By investigating these aspects, you may be able to resolve the "ModuleNotFoundError: No module named 'ultralytics'" issue and successfully run the YOLOv5 inference script within the Apache environment.

If you need further assistance or clarification, please feel free to ask.
