### ISSUE TITLE
training data results 

### ISSUE THREAD

**Issue by ampelmannnys** [ultralytics/yolov5#12016]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

The metric level shown after the end of the experiment is strange. For reference, the actual experimental data results and the results stored in the run file after the experiment are similar.
![image](https://github.com/ultralytics/yolov5/assets/107301769/63f1ace3-46f1-422f-8472-ae309dad4523)
![image](https://github.com/ultralytics/yolov5/assets/107301769/c1232981-13d1-4c7a-94f2-dd4edb788f63)

**Comment by glenn-jocher** [comment]
@ampelmannnys hi there,

Thank you for reaching out. The discrepancy you're observing between the metric level shown after the experiment and the results stored in the run file can have various causes. It would be helpful to have more information about your experiment setup and any modifications you made to the code. Can you provide more details about your training data, model configuration, and training process?

Also, please make sure to include the relevant code snippets or configuration files that could help us identify the issue more effectively.

Best regards,
Glenn Jocher
