### ISSUE TITLE
run yolov5 2.0 IndexError: too many indices for tensor of dimension 1

### ISSUE THREAD

**Issue by a42385029** [ultralytics/yolov5#12011]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

run yolov5 2.0 IndexError: too many indices for tensor of dimension 

<img width="812" alt="微信截图_20230820130955" src="https://github.com/ultralytics/yolov5/assets/44129021/8a6c5a77-3f4e-4a8a-97dc-e263d3127a1d">
<img width="893" alt="微信截图_20230820130947" src="https://github.com/ultralytics/yolov5/assets/44129021/3c345b95-31ac-4758-83da-a89ba7d7a5f9">

**Comment by glenn-jocher** [comment]
@a42385029 hi there! It looks like you're encountering an IndexError while running YOLOv5 2.0. This issue might be related to the dimensions of the input tensor.

Can you provide more details about the specific command you are using and the input data you are working with? Additionally, have you checked if your input data matches the expected format for YOLOv5?

In the meantime, you can also refer to the YOLOv5 documentation at https://docs.ultralytics.com/yolov5 for guidance on input data formatting and troubleshooting common issues.

Looking forward to helping you resolve this!
