### ISSUE TITLE
About TP, TN, FP, FN

### ISSUE THREAD

**Issue by ferro07** [ultralytics/yolov5#1201]
## ❔Question
Hi @glenn-jocher 
Thanks for this great work. 
I am trying to add Tp, Fp, Fn to the test results. Firstly,  I am using  this class for calling only tp :  def ap_per_class(tp, conf, pred_cls, target_cls, plot=False, fname='precision-recall_curve.png'): 

On the test.py, adding tp to the  # Compute statistics, but I am getting followings

raceback (most recent call last):
  File "test.py", line 272, in <module>
    test(opt.data,
  File "test.py", line 88, in test
    s = ('%20s' + '%12s' * 6) % ('Class', 'Images', 'Targets', 'P', 'R', 'mAP@.5', 'mAP@.5:.95', 'tp')
TypeError: not all arguments converted during string formatting

Thanks in advance for your help

**Comment by glenn-jocher** [comment]
@ferro07 you need to put breakpoints near these variables to understand what you're getting into, as these are large multidimensional matrices of 1's and 0's. I don't know what you want to do with them exactly but I doubt printing them to screen would be very useful.

**Comment by jaqub-manuel** [comment]
@glenn-jocher  thanks for quick reply. 
I also want to find the number of FNs and thus, I can try to apply different techniques to reduce FP, FN or increase TP so on. 
(Precision = TP/TP+FP and Recall = TP/TP+FN), if I print this at test.py, I will analyze my custom dataset in more detail.
You have this values in general.py (def ap_per_class(tp, conf, pred_cls, target_cls, plot=False, fname='precision-recall_curve.png'):
but, I got errors. 
Thanks

**Comment by glenn-jocher** [comment]
@jaqub-manuel sure. Any code modifications are up to you.

**Comment by ZwNSW** [comment]
@glenn-jocher I want to talk about tp, fp, fn output to the screen, but I don't know how to modify the code. This is a difficult problem.
Thanks!

**Comment by ZwNSW** [comment]
@ferro07 Hi,Do you have solved this problem?I want to get the tp,fp,fn to analyze my problom,but I can not print them out to my terminal.

**Comment by glenn-jocher** [comment]
@ZwNSW TP, FP are computed here:
https://github.com/ultralytics/yolov5/blob/c8c5ef36c9a19c7843993ee8d51aebb685467eca/utils/general.py#L250-L263

**Comment by glenn-jocher** [comment]
@ferro07 @jaqub-manuel good news 😃! Your original issue may now be fixed ✅ in PR #5727. This PR explicitly computes TP and FP from the existing Labels, P, and R metrics:

```bash
TP = Recall * Labels
FP = TP / Precision - TP
```

These TP and FP per-class vectors are left in val.py for users to access if they want:
https://github.com/ultralytics/yolov5/blob/36d12a500eae4561d09d4955e1b50b12e57bf6c6/val.py#L240

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
