### ISSUE TITLE
How can we generate anchor boxes for a custom dataset with different image size 448,448

### ISSUE THREAD

**Issue by Mukulareddy** [ultralytics/yolov5#12027]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

 I have tried running training with my dataset. I can see in logs that the
 `AutoAnchor: 4.77 anchors/target, 1.000 Best Possible Recall (BPR). Current anchors are a good fit to dataset ✅`
Is the auto anchor flag enabled by default when we start training?

**Comment by glenn-jocher** [comment]
@Mukulareddy the auto anchor flag is enabled by default when training YOLOv5. It automatically generates anchor boxes that are a good fit for your custom dataset. The log message you mentioned, `AutoAnchor: 4.77 anchors/target, 1.000 Best Possible Recall (BPR). Current anchors are a good fit to dataset ✅`, indicates that the generated anchor boxes have a good recall rate for your dataset.

If you have any further questions or need assistance with YOLOv5, feel free to ask. We're here to help!
