### ISSUE TITLE
How to block the data augmentation in YOLOv5

### ISSUE THREAD

**Issue by zxp555** [ultralytics/yolov5#12025]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I noticed the default hyperparameters in one YAML file. as show below:
...
hsv_h: 0.015  # image HSV-Hue augmentation (fraction)
hsv_s: 0.7  # image HSV-Saturation augmentation (fraction)
hsv_v: 0.4  # image HSV-Value augmentation (fraction)
degrees: 0.0  # image rotation (+/- deg)
translate: 0.1  # image translation (+/- fraction)
....
If I want to close these data augmentation, Should I delete these words or set all these values to 0?

**Comment by glenn-jocher** [comment]
@zxp555 you can disable data augmentation in YOLOv5 by setting all the augmentation values to 0 in the YAML file. Therefore, to close these data augmentations, you can simply set `hsv_h`, `hsv_s`, `hsv_v`, `degrees`, and `translate` to 0.

Let me know if you have any further questions or need more assistance!
