### ISSUE TITLE
Multi-label Classification using YOLOv5

### ISSUE THREAD

**Issue by purnakar18** [ultralytics/yolov5#12032]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,

I have a custom dataset for which I am required to perform multi-label classification. I have followed the steps in https://blog.roboflow.com/train-yolov5-classification-custom-data/?ref=ultralytics for the task. So when I use Roboflow to annotate my custom dataset, I get 2 formats for downloading.
1. Multi-label Classification csv
2. Folder structure.

When I use the first type, the dataset comprises train/val/test folders and in each folder, there are images & a csv file with each image filename and the labels it belongs to. When I use this format to train the model I get an error that no folder for classes is found in the dataset/train directory.
When I use the second folder structure for the dataset, the dataset comprises train/val/test folders and each folder consists of folders created by concatenating the label combinations found in the training set. When I give the train command, I do not get any errors but the problem is the model treats each combination as a new class which is not the correct way.

Is there any way I can achieve multi-label classification? Or do I treat this as an object detection problem giving the bounding box details as the entire image?
Thanks in advance

**Comment by glenn-jocher** [comment]
@purnakar18 hi,

For multi-label classification using YOLOv5, you can treat it as an object detection problem by providing bounding box details for the entire image. In this case, each label would be considered as a separate object. 

Alternatively, if you want to use the multi-label classification CSV format, make sure you have a folder named "classes" in the "dataset/train" directory. This folder should contain a single text file, where each line represents a label class. 

Feel free to give either approach a try and see which one works best for your specific task. Let us know if you have any further questions or need additional assistance.

Best, Glenn

**Comment by purnakar18** [comment]
Hello Glenn,

Thanks for your above suggestions. I have tried the first approach, i.e., treating it as object detection, the mAP was over 0.5 which is decent considering the type of images and the class imbalance.
I wanted to try the second method, I had some queries regarding the same. You mention that under dataset/train create a folder called classes. This folder should have a single text file, should this text file have annotations of each image?
e.g, if image1 has labels: 1,2 &5, and image2 has labels 2&4, should the entry to the classes.txt file have the below format:
image1,1,2,5
image2,2,4
Is this the correct way?
Thanks in Advance,
Purna Kar

**Comment by glenn-jocher** [comment]
@purnakar18 hi Purna,

I'm glad to hear that treating your multi-label classification task as an object detection problem yielded good results!

Regarding your query about the second method, the text file in the "classes" folder should contain a list of all the label classes in your dataset, with each class on a separate line. This file is used to define the classes or labels that your model will be trained to predict.

For example, if your dataset has three classes (label 1, label 2, label 3), the "classes.txt" file would look like this:

```
label 1
label 2
label 3
```

There's no need to include the image names or annotations in this file; it's solely used for defining the class labels.

I hope this clarifies the process. If you have any further questions, feel free to ask.

Regards,
Glenn

**Comment by purnakar18** [comment]
Hello Glenn,

Thank you for your reply. One last confusion, this is the folder structure I am following for the dataset: dataset/train, dataset/val, dataset/test. I am uploading the actual images in the above locations. May I know where should I upload the annotations or the list of labels per image?

Thanks,
Purna

**Comment by glenn-jocher** [comment]
@purnakar18 hi Purna,

In the folder structure you mentioned (dataset/train, dataset/val, dataset/test), you can place the annotations or the list of labels per image in the same location as the images themselves. 

For each image in the dataset, you can create a corresponding text file with the same name but with the ".txt" extension instead. Each text file should contain the labels associated with that particular image. The labels should be in the format: **class_index x_center y_center width height**, where **class_index** is the index of the label class, and **x_center**, **y_center**, **width**, and **height** define the bounding box coordinates.

For example, if you have an image named "image1.jpg" located in the "dataset/train" folder, you would create a text file named "image1.txt" in the same folder. This text file would contain the labels associated with that image.

I hope this clears up any confusion. Let me know if you have any further questions.

Glenn
