### ISSUE TITLE
Learning with Google facial expression comparison dataset

### ISSUE THREAD

**Issue by S-mishina** [ultralytics/yolov5#1203]
## Question
Nice to meet you.
I want to make a facial expression analysis model using yolov5.
How do I train with yolov5 using Google's Facial Expression Comparison Dataset?
I would appreciate it if anyone could answer.
Please.
Google's Facial Expression Comparison Dataset URL
https://research.google/tools/datasets/google-facial-expression/

**Comment by glenn-jocher** [comment]
@S-mishina YOLOv5 can be applied to any object detection task. If your custom dataset is suited to this task see https://docs.ultralytics.com/yolov5/tutorials/train_custom_data to get started.
