### ISSUE TITLE
How to connect Web cam?

### ISSUE THREAD

**Issue by woongdam** [ultralytics/yolov5#1204]
Hello 

im woongdam 

first of all. thank you for sharing your project

but I cant connect Web Cam, because your code dont have way to connect Web Cam

so i want to know Real Time Object Detection way using Web Cam

Thank you

**Comment by glenn-jocher** [comment]
@woongdam inference commands for all sources including webcams are listed in the README
https://github.com/ultralytics/yolov5#inference
