### ISSUE TITLE
how to save result in csv for doing testing 

### ISSUE THREAD

**Issue by akashAD98** [ultralytics/yolov5#12041]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

want to write the  argument for saving the results in CSV file, so we can do easily testing . 

### Use case

this can be very helpful if you want to analyze your performance, get a confidence score & test real testing files that dont have the ground truth. so we can verify its accuracy later by manually 

below is example

<img width="435" alt="image" src="https://github.com/ultralytics/yolov5/assets/62583018/be95ea0c-e38c-487c-8a18-a56f7a200810">

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@akashAD98 hi there,

Thank you for reaching out. Currently, YOLOv5 does not provide a built-in feature to save the results in a CSV file. However, you can easily write a custom script to achieve this.

Here's a simple example:

```python
import csv

# Your YOLOv5 output
results = [{'label': 'cat', 'confidence': 0.95, 'bbox': [10, 20, 100, 200]}, 
           {'label': 'dog', 'confidence': 0.85, 'bbox': [50, 60, 150, 250]},
           ...
          ]

# Define CSV file path
csv_file = 'output.csv'

# Write results to CSV
with open(csv_file, mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(['Label', 'Confidence', 'BBox'])
    for result in results:
        writer.writerow([result['label'], result['confidence'], result['bbox']])
```

This is just a simple example, and you can modify it according to your specific needs. You can iterate over the YOLOv5 outputs and extract the label, confidence, and bounding box information. Then, write them row by row into a CSV file using the `csv` module.

I hope this helps! If you have any further questions, feel free to ask.

Keep in mind that YOLOv5 is an open-source project with contributions from the YOLO community and the Ultralytics team. Any praise should be directed towards them for their hard work.

Thanks again for your interest in YOLOv5.

Kind regards,
Glenn Jocher
