### ISSUE TITLE
Applying the detection to the real camera , not webcam 

### ISSUE THREAD

**Issue by Jenanaputra** [ultralytics/yolov5#12057]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is it possible for me  to detect the object by running  detect.py but with the source is from the real camera which the frame can be acquired by using a particular camera's driver ?

**Comment by glenn-jocher** [comment]
@Jenanaputra yes, it is possible to detect objects using `detect.py` with the source being a real camera. You can acquire frames from the camera using the camera's specific driver and then pass those frames as input to the `detect.py` script. 

You may need to modify the code to handle the camera input appropriately. You can refer to the [OpenCV](https://opencv.org/) library for capturing frames from the camera and converting them into a compatible format for `detect.py`. Once you have the frames, you can pass them to the `detect.py` script just like you would with any other image.

If you encounter any issues or have further questions, feel free to ask.
