### ISSUE TITLE
This error is displayed when an attention mechanism is added

### ISSUE THREAD

**Issue by HKL-BIT-0702** [ultralytics/yolov5#12064]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Hello, I reported this error when I made improvements to my module to add attention mechanism，RuntimeError: adaptive_avg_pool2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True)'. You can turn off determinism just for this operation, or you can use the 'warn_only=True' option, if that's acceptable for your application. You can also file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation.
The answer I found online is torch.use_deterministic_algorithms(False)。but, I found that when set to False, the result can not be repeated, how to solve this. Can you help me?

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@HKLCXQ hi there! It seems that you're encountering a `RuntimeError` when adding an attention mechanism to your module in YOLOv5. This error relates to the `adaptive_avg_pool2d_backward_cuda` function and the use of deterministic algorithms.

The suggestion you found online to resolve this error is to set `torch.use_deterministic_algorithms(False)`. However, you mentioned that setting it to `False` results in non-reproducible results.

In this case, I recommend looking into the PyTorch documentation and GitHub repository to see if there is any ongoing discussion or issue related to adding deterministic support for `adaptive_avg_pool2d_backward_cuda`. You can find it at https://github.com/pytorch/pytorch/issues.

By contributing to that discussion or opening a new issue, you can help prioritize the addition of deterministic support for this operation. This will ultimately benefit both YOLOv5 and the wider PyTorch community.

If you would like to contribute by submitting a PR, that would be greatly appreciated! Just make sure to follow the contributing guidelines mentioned in the project's repository.

I hope this helps, and please let me know if you have any further questions or concerns.
