### ISSUE TITLE
I am unable to run YOLOv5. Problem with ultralytics module.

### ISSUE THREAD

**Issue by TASHINOV10** [ultralytics/yolov5#12060]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Greetings,

I am new to python and programming in general.
I have been working on creating a portfolio project in which I am using yolov5 for license plate detection.

Up until recently, my program was working fine. Today I wanted to make some changes but upon testing the program, I received an error related with the **ultralytics module**.

I opened more recent versions of my code where everything used to be fine but I still get an error.
The error in questions is **ModuleNotFoundError: No module named 'ultralytics.utils'**

I am aware that there are similar posts around the internet, but nothing seems to work for my case.

The model that I have is trained with custom data which is why I am calling it in this manner:

``model = torch.hub.load('ultralytics/yolov5', 'custom', path= weightsPath)`` 

I seem to have all necessary requirements installed and yet I can't run the program.

Any suggestion why this might be the case?

Thank you in advance.

#### For better clarity, please find the complete error that I receive below:

Using cache found in C:\Users\Iliyan Tashinov/.cache\torch\hub\ultralytics_yolov5_master
Traceback (most recent call last):
  File "C:\Users\Iliyan Tashinov\Desktop\YOLO_Vignette_Sticker_Validator\branch1.py", line 32, in <module>
    model = torch.hub.load('ultralytics/yolov5', 'custom', path= weightsPath)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Iliyan Tashinov\Desktop\virtualProject\YOLO_Vignette_Sticker_Validator\Lib\site-packages\torch\hub.py", line 558, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Iliyan Tashinov\Desktop\virtualProject\YOLO_Vignette_Sticker_Validator\Lib\site-packages\torch\hub.py", line 587, in _load_local
    model = entry(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Iliyan Tashinov/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 83, in custom
    return _create(path, autoshape=autoshape, verbose=_verbose, device=device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Iliyan Tashinov/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 33, in _create
    from models.common import AutoShape, DetectMultiBackend
  File "C:\Users\Iliyan Tashinov/.cache\torch\hub\ultralytics_yolov5_master\models\common.py", line 38, in <module>
    from ultralytics.utils.plotting import Annotator, colors, save_one_box
ModuleNotFoundError: No module named 'ultralytics.utils'

#### And also, please find the installed packages that I am working with:

asttokens==2.2.1
backcall==0.2.0
certifi==2023.5.7
charset-normalizer==3.1.0
colorama==0.4.6
comm==0.1.3
contourpy==1.1.0
cycler==0.11.0
debugpy==1.6.7
decorator==5.1.1
docopt==0.6.2
executing==1.2.0
filelock==3.12.2
fonttools==4.40.0
gitdb==4.0.10
GitPython==3.1.31
idna==3.4
ipykernel==6.23.2
ipython==8.14.0
jedi==0.18.2
Jinja2==3.1.2
jupyter_client==8.2.0
jupyter_core==5.3.1
kiwisolver==1.4.4
MarkupSafe==2.1.3
matplotlib==3.7.1
matplotlib-inline==0.1.6
mpmath==1.3.0
nest-asyncio==1.5.6
networkx==3.1
numpy==1.24.3
opencv-python==4.7.0.72
packaging==23.1
pandas==2.0.2
parso==0.8.3
pickleshare==0.7.5
Pillow==9.5.0
pipreqs==0.4.13
platformdirs==3.5.3
prompt-toolkit==3.0.38
psutil==5.9.5
pure-eval==0.2.2
Pygments==2.15.1
pyparsing==3.0.9
pytesseract==0.3.10
python-dateutil==2.8.2
pytz==2023.3
pywin32==306
PyYAML==6.0
pyzmq==25.1.0
requests==2.31.0
scipy==1.10.1
seaborn==0.12.2
six==1.16.0
smmap==5.0.0
stack-data==0.6.2
sympy==1.12
thop==0.1.1.post2209072238
torch==2.0.1
torchaudio==2.0.2
torchvision==0.15.2
tornado==6.3.2
tqdm==4.65.0
traitlets==5.9.0
typing_extensions==4.6.3
tzdata==2023.3
ultralytics==8.0.119
urllib3==2.0.3
wcwidth==0.2.6
yarg==0.1.9

_No response_

**Comment by TASHINOV10** [comment]
I have trained the model successfully and now I want to use it in a program in which I want to detect license plates of vehicles and then do additional things to the images. 

My main issue is related with "calling" (not sure if this should be the right word) the model. 

Are there any suggestions on debugging the code in relation to such issues

**Comment by glenn-jocher** [comment]
@TASHINOV10 hi there,

When encountering issues with calling the model in your program, there are a few debugging steps you can follow:

1. **Check module installation**: Ensure that the `ultralytics` module is installed correctly. You can do this by running `pip show ultralytics` in your terminal to see if it is listed and properly installed. If it is not installed, you can install it using `pip install ultralytics`.

2. **Import statement**: Double-check that you have the correct import statement for the `ultralytics` module. It should be `from yolov5.models import *`. Make sure this import statement is placed at the beginning of your script.

3. **Verify the model's PATH**: Confirm that the `weightsPath` you are providing as an argument to `torch.hub.load()` is correct and points to the location of your trained weights.

4. **Consider environmental factors**: If the above steps haven't resolved the issue, it is worth checking if there are any environmental factors causing the problem. Make sure you are using the correct Python version (>=3.8.0) and have all the required dependencies installed, including PyTorch (>=1.8). You may also want to ensure that your file paths and directories are correctly specified.

By following these steps, you should be able to identify and resolve the issue with calling the model in your program. Please let me know if you have any further questions or concerns.

Happy coding!

**Comment by TASHINOV10** [comment]
@glenn-jocher thank you so much for the feedback:
Here are the results from the debugging procedure:

1. **I have checked whether `ultralytics` module is installed correctly. Upon running `pip show ultralytics` the result is the following**

Version: 8.0.119
Summary: Ultralytics YOLOv8 for SOTA object detection, multi-object tracking, instance segmentation, pose estimation and image classification.

3. **I have verified the model path and everything seems to be linked correctly**

4. **I have also checked the environmental factors. The python version is 3.11.2 and PyTorch version is 2.0.0 + CPU.**

Could you please elaborate more on point 2.
In my code I haven't imported ultralytics in any way. All I do is running this peace of code
`model = torch.hub.load('ultralytics/yolov5', 'custom', path= weightsPath)`

I haven't worked on my project for weeks. The last time I have run the script everything seemed to work fine.
But now without doing any changes I get the problem in question. On top of elaborating on point 2, could you also share if there were some changes made to the ultralytics module or anything else that I can consider doing.

Thank you once again for the assistance.

**Comment by TASHINOV10** [comment]
Okay, I have resolved the issue.

It appears that there are new requirements added for running Yolov5.
I have run this command in the console, and everything was fixed:

`pip install -r https://raw.githubusercontent.com/ultralytics/yolov5/master/requirements.txt `

I have found the resolution in the below GitHub blog post:

 https://github.com/ultralytics/ultralytics/issues/3856

**Comment by glenn-jocher** [comment]
@TASHINOV10 great to hear that you were able to resolve the issue! 

Indeed, there have been some changes and new requirements added to the YOLOv5 package. Installing the necessary packages using the command `pip install -r https://raw.githubusercontent.com/ultralytics/yolov5/master/requirements.txt` is a recommended step to ensure all dependencies are installed correctly.

Thank you for sharing your solution and the reference to the GitHub blog post. It may prove helpful to others facing a similar issue.

If you have any more questions or encounter any further issues, feel free to ask.

Happy coding!
