### ISSUE TITLE
Error Code 6: Internal Error (Unable to load library: nvinfer_builder_resource.dll)

### ISSUE THREAD

**Issue by sankolly** [ultralytics/yolov5#12078]
I tried to export the tensorrt with windows system and this happened. I tested on different version of tensorrt and the bugs are the same show as following. Is there anything I can do to fix this?
https://user-images.githubusercontent.com/27351334/173659983-5b7634e8-411a-4cff-8b7a-1ba2393f686c.png
Environment
Environment: Yolov5, Windows 10, python

**Comment by glenn-jocher** [comment]
@sankolly this error typically occurs when there is a problem loading the `nvinfer_builder_resource.dll` library. Here are a few steps you can try to fix it:

1. Make sure you have installed the correct version of TensorRT that is compatible with your system and the version of YOLOv5 you are using.

2. Verify that the `nvinfer_builder_resource.dll` file is present in the correct location. If it is missing or corrupted, you may need to reinstall TensorRT.

3. Check that all the required dependencies for TensorRT are properly installed, including CUDA and CUDNN.

If the issue persists, please provide more information about your setup and the steps you followed. This will help us troubleshoot the problem more effectively.

**Comment by sankolly** [comment]
@glenn-jocher Thanks you for your reply ,
my setup is :  

windows 10 , GTX 1060 6gb all update are done for card graphic
TensorRT-8.4.3.1
cudnn-windows-x86_64-8.9.4.25
cuda_11.6.0

for nvinfer_builder_resource.dll file is present in the correct location it seems like all correct the path also . i followed this video for tutorial https://www.youtube.com/watch?v=KoCms6vMH6A&list=PLUDHtulOtR9fubb_ZIzBxd5pyWvFrTLQp&index=20&ab_channel=SmileMe
I have repeated this video three times, and the same problem persists. I've also tried reinstalling it and using another version to see if it works or not. 
![Screenshot 2023-09-06 234132](https://github.com/ultralytics/yolov5/assets/143943711/3b91f6c6-a94e-4d1c-940d-841bf8693863)

**Comment by glenn-jocher** [comment]
@sankolly, thank you for providing the details of your setup and the steps you followed. It appears that you have installed the correct versions of TensorRT, CUDA, and CUDNN.

From the screenshot you provided, I can see the error message indicating that the `nvinfer_builder_resource.dll` library cannot be loaded. As you mentioned that the file is present in the correct location, it's possible that there may be an issue with the library itself.

I recommend trying the following steps to troubleshoot the issue further:
- Ensure that you have installed all the necessary dependencies, including the Microsoft Visual C++ Redistributable packages.
- Update your GPU drivers to the latest version.
- Try running the application as an administrator.
- Check if any antivirus software or firewall settings are interfering with the loading of the library.

If none of these steps resolve the issue, it may be worth reaching out to the YOLOv5 community or the Ultralytics team for further assistance, as they may have encountered similar problems.

Please let me know if there's anything else I can help you with.

**Comment by sankolly** [comment]
not of this work , if you can add me in discord to give me a solution for my problem in my pc , and thank you for your help 
my id in discord : sankolly

**Comment by glenn-jocher** [comment]
@sankolly thank you for reaching out. I'm glad to assist you with your issue here on GitHub. Unfortunately, I'm unable to provide direct support via Discord. However, I'll do my best to help you resolve your problem here.

Please provide detailed information about the issue you are facing, including any error messages or logs. Additionally, let us know your setup details, such as operating system, GPU, and software versions.

Once we have this information, we can work together to find a solution to your problem. I'm here to help you and will respond as soon as possible.
