### ISSUE TITLE
I wonder if this feature is available or not

### ISSUE THREAD

**Issue by anewworl** [ultralytics/yolov5#12085]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

```
                    if save_img or save_crop or view_img:  # Add bbox to image
                        c = int(cls)  # integer class
                        label = None if hide_labels else (names[c] if hide_conf else f'{names[c]} {conf:.2f}')
                        annotator.box_label(xyxy, label, color=colors(c, True))
                        # annotator.draw.polygon(segments[j], outline=colors(c, True), width=3)
                    if save_crop:
                        save_one_box(xyxy, imc, file=save_dir / 'crops' / names[c] / f'{p.stem}.jpg', BGR=True)
```
I wonder if the line `annotator.draw.polygon(segments[j], outline=colors(c, True), width=3)` from `yolov5/segment/predictpy.py` is avalialbe or not because when i testing to run it with camera. It show like below:
```
  File "D:\HOC_TAP\YASKAWA\YOLO_PyCharm\3.Training\test_seg.py", line 161, in run
    annotator.draw.polygon(segments[j], outline=colors(c, True), width=3)
AttributeError: 'Annotator' object has no attribute 'draw'
``` 
If this feature is not avalialbe is there any replacement for this line. Another thing is that if this function will give a polygone outline for and object like picture below which is the example from yolov8:

![z4655672072479_061dcd4cbc2b24729999120219836617](https://github.com/ultralytics/yolov5/assets/104755734/06c37cc6-3282-43cd-b7b1-a16cb1a1e5d8)

**Comment by glenn-jocher** [comment]
@anewworl the line `annotator.draw.polygon(segments[j], outline=colors(c, True), width=3)` in `yolov5/segment/predictpy.py` is not currently available. The error you encountered, `AttributeError: 'Annotator' object has no attribute 'draw'`, suggests that the `draw` attribute does not exist in the `Annotator` object.

If you are looking for a replacement for this line, you can try using the `cv2.polylines()` function in OpenCV to draw the polygon outline. Here is an example using the `cv2.polylines()` function:

```python
import cv2

# Assuming `segments[j]` is a list of points representing the polygon
# `image` is the image you want to draw on
# `color` is the color of the outline
# `width` is the width of the outline
cv2.polylines(image, [np.array(segments[j], dtype=np.int32)], isClosed=True, color=color, thickness=width)
```

Regarding the example image you provided from YOLOv8, you can achieve similar results with YOLOv5 by using the `cv2.polylines()` function as described above. The example image you provided illustrates an object with a polygon outline drawn around it, which can be achieved using the suggested code snippet.

Let me know if you have any further questions or need additional assistance!

**Comment by anewworl** [comment]
hm interesting. Firsly thanks for your response @glenn-jocher. so as we know `segments[j]` here is just a list of points reprensting for 1 polygon of 1 object. So how it come with the multiple segment, `[np.array(segments[j], dtype=np.int32)]` will change to what or it will stay the same. Futhermore i seen that above that line is                 
```
segments = [
                    scale_segments(im0.shape if retina_masks else im.shape[2:], x, im0.shape, normalize=True)
                    for x in reversed(masks2segments(masks))]
```
which have `normalize=True` which will return float number do we need to reverse the normalize of this steps befor we but the segments in the `cv2.polylines()`

**Comment by glenn-jocher** [comment]
@anewworl `segments[j]` represents a list of points for one polygon of an object. If you have multiple polygons or objects, you would have multiple `segments` lists, where each `segments[j]` corresponds to a different object.

When using the `cv2.polylines()` function, the `segments[j]` list should be converted to a NumPy array of `dtype=np.int32`. The `np.array(segments[j], dtype=np.int32)` expression accomplishes this conversion.

Regarding the normalization, the `normalize=True` argument in `scale_segments()` is used to normalize the segment coordinates within the image shape. If you want to reverse this normalization before using the segments in `cv2.polylines()`, you can modify the code to apply the reverse normalization before drawing the polygon. You can do this by multiplying the segments by the corresponding shape dimension.

For example, if `segments` is normalized with `normalize=True`, you can reverse the normalization as follows:
```python
segments = [
    np.multiply(x, [im0.shape[1], im0.shape[0]])  # Reverse normalization
    for x in segments
]
```

This will multiply each coordinate in `segments` by the width and height of `im0` to obtain the original pixel values.

I hope this explanation clarifies your question. Let me know if there's anything else I can assist you with!

**Comment by anewworl** [comment]
@glenn-jocher  thanks for your advice, it help me a lot.

**Comment by glenn-jocher** [comment]
@anewworl, you're welcome! I'm glad I could help. If you have any more questions or need further assistance, feel free to ask. Have a great day!
