### ISSUE TITLE
Segmentation inference within code

### ISSUE THREAD

**Issue by JNaranjo-Alcazar** [ultralytics/yolov5#12086]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi community,
I wonder when inference will be available for segmentation

```
model = torch.hub.load(
    "ultralytics/yolov5", "custom", "yolov5m-seg.pt"
)  # load from PyTorch Hub (WARNING: inference not yet supported)
```

Thanks in advance

**Comment by RizwanMunawar** [comment]
@JNaranjo-Alcazar! Segmentation module inference is not supported yet directly with PyTorch Hub. It is supported, If you are using the code locally (on your System, or PC). You can use the mentioned commands to do this.

```
git clone https://github.com/ultralytics/yolov5.git
cd yolov5
pip install -r requirements.txt
python segment/predict.py --weights yolov5n-seg.pt --source data/images/bus.jpg --view-img
```

**Comment by glenn-jocher** [comment]
@JNaranjo-Alcazar, at the moment, direct inference for segmentation modules is not yet supported through PyTorch Hub. However, you can still perform segmentation inference by running the code locally on your system.

To do this, you can follow these steps:

1. Clone the YOLOv5 repository by running `git clone https://github.com/ultralytics/yolov5.git` in your terminal or command prompt.
2. Move into the cloned repository by running `cd yolov5`.
3. Install the necessary requirements by running `pip install -r requirements.txt`.
4. Finally, you can perform the segmentation inference using the following command:
   ```
   python segment/predict.py --weights yolov5n-seg.pt --source data/images/bus.jpg --view-img
   ```

Please note that you need to replace `yolov5n-seg.pt` with the appropriate segmentation weights file that you intend to use, and `data/images/bus.jpg` with the path to your input image.

Feel free to reach out if you have any further questions or need any assistance!

**Comment by JNaranjo-Alcazar** [comment]
yes, I understand this, but I mean can the type inference be made?

```
model = torch.load('model-to-seg.pt')
results = model(image)
results.show()
```

**Comment by glenn-jocher** [comment]
@JNaranjo-Alcazar yes, you can use type inference for segmentation by loading the model and passing the image through it. Here's an example:

```python
model = torch.load('model-to-seg.pt')
results = model(image)
results.show()
```

Note that you need to replace 'model-to-seg.pt' with the path to your segmentation model weights file, and 'image' with your input image.

Let me know if you have any further questions or need additional assistance!

**Comment by JNaranjo-Alcazar** [comment]
Hi @glenn-jocher I assume that I have to read the image for instance in PIL format?

If I do it, I get an error of expected tensor?
How should I read the image to be fed to the model?

**Comment by glenn-jocher** [comment]
@JNaranjo-Alcazar You are correct. You should read the image using the PIL library and then convert it to a tensor before passing it to the model. Here's an example of how you can achieve this:

```python
from PIL import Image
import torch

# Read the image using PIL
image = Image.open('path_to_your_image.jpg')

# Convert the image to a tensor
image_tensor = transforms.ToTensor()(image).unsqueeze_(0)

# Load the segmentation model
model = torch.load('model-to-seg.pt')

# Perform inference
results = model(image_tensor)

# Display the segmentation results
results.show()
```

In this example, replace 'path_to_your_image.jpg' with the actual path to your input image. This code first reads the image using PIL, then converts it to a tensor, and finally passes it to the segmentation model for inference.

Let me know if you encounter any further issues or need additional assistance!
