### ISSUE TITLE
about eval metric

### ISSUE THREAD

**Issue by ampelmannnys** [ultralytics/yolov5#12099]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How do I get ap small/medium/large on pascal voc dataset?

**Comment by glenn-jocher** [comment]
@ampelmannnys to get the average precision (AP) for small, medium, and large objects on the Pascal VOC dataset, you can use the `test.py` script provided in the YOLOv5 repository. 

By default, the script evaluates AP for all objects collectively. However, you can modify the script to calculate AP for specific size ranges by adjusting the `yolo.py` file.

Within the `yolo.py` file, you can find the `AP` class that is responsible for calculating average precision. By modifying the function `compute_ap_per_class()`, you can specify the size ranges for small, medium, and large objects and calculate their corresponding AP values.

Please note that this modification requires understanding the code and may involve defining your own size ranges based on your dataset.

Remember, the YOLOv5 repository is a collaborative effort, and the Ultralytics team appreciates the contributions and feedback from the YOLO community.

**Comment by ampelmannnys** [comment]
@glenn-jocher The test.py has already been changed to a val.py, and there is no code related to the AP in yolo.py , but rather the compute_ap code in metric.py. How exactly do you want me to modify it?

**Comment by glenn-jocher** [comment]
@ampelmannnys Thank you for pointing out the correct file. I apologize for the confusion.

To calculate AP for different object sizes in the Pascal VOC dataset, you can modify the `compute_ap_per_class()` function in the `metric.py` file located in the `yolov5/utils` directory. 

Inside the `compute_ap_per_class()` function, you will find the conditions for determining small, medium, and large objects based on their area. You can adjust these conditions according to your requirements to define the size ranges for each category.

For example, you can modify the area thresholds in the following lines of code:

```python
if 0 < bbox_area < 32 ** 2:
    # Small objects
    # Calculate AP for small objects
elif 32 ** 2 <= bbox_area < 96 ** 2:
    # Medium objects
    # Calculate AP for medium objects
elif bbox_area >= 96 ** 2:
    # Large objects
    # Calculate AP for large objects
```

Please note that these values are just examples, and you should choose the thresholds that are suitable for your specific dataset.
