### ISSUE TITLE
Is Segmentation model export to Tensorflow supported?

### ISSUE THREAD

**Issue by johnsaturn** [ultralytics/yolov5#12092]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I ran  custom segmentation training on yolo v5  and tried to export via regular export script with tfjs (which in thus version also automatically creates the tensorflow/saved model) however I noticed the signature is same as the detection model and contents are way off.

I tried doing the export to ONNX and that did change the output signature and works fine with the expected shapes of 1,32,160,160  and  1, 25200,39 .

So now I am considering to export manually the ONNX to Tensorflow but first wanted to confirm if this wasn't supported out of the box

**Comment by glenn-jocher** [comment]
@johnsaturn the YOLOv5 repository currently does not have built-in support for exporting the segmentation model to TensorFlow. However, you can manually export the segmentation model from ONNX to TensorFlow. The ONNX export process changes the output signature and works well with the expected shapes.

If you decide to proceed with the manual export, please ensure you have the necessary libraries and dependencies installed to convert the ONNX model to TensorFlow.

Let me know if you have any further questions or need additional assistance.

**Comment by johnsaturn** [comment]
Thanks Glen! I  noticed on the export.py that indeed it didn't have the SegmentationModel logic like ONNX. Appreciate the kind help and I'll try to follow the route

**Comment by glenn-jocher** [comment]
@johnsaturn you're welcome! I'm glad I could help. Yes, currently the `export.py` script in YOLOv5 doesn't include logic for exporting the segmentation model like it does for ONNX. Feel free to follow the route of manually exporting the ONNX model to TensorFlow. Let me know if you need any further assistance along the way.
