### ISSUE TITLE
Will the version of torch& torchvision influence ?

### ISSUE THREAD

**Issue by RobinhoodKi** [ultralytics/yolov5#121]
If I can't update my torch into version-1.5, and I continue to use version-1.4.0(torch) and version-0.5.0(torchvision).
Will it heavily influence the final result?

**Comment by glenn-jocher** [comment]
@RobinhoodKi torch 1.5 is required.

**Comment by glenn-jocher** [comment]
See https://github.com/ultralytics/yolov5#requirements
