### ISSUE TITLE
crop box

### ISSUE THREAD

**Issue by duhaitong** [ultralytics/yolov5#12101]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Hello. I want the crop box to be larger than the prediction box. For example, a crop box is 1.2 times larger than a prediction box. This will help me to process the cropped image again.

### Use case

no

### Additional

no

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@duhaitong thanks for your interest in YOLOv5 and willingness to contribute!

To achieve a crop box that is larger than the prediction box, you can modify the code in the `detect.py` script.

In the `detect.py` script, after the bounding boxes are predicted, you can increase the size of the crop box by multiplying the width and height of the predicted bounding boxes by a scaling factor of 1.2. Here is an example of the modification you can make:

```python
# After the bounding boxes are predicted
pred_boxes = detections[0][:, :4]  # Assuming you are using the first element of the detections list

# Increase the size of the crop box by multiplying the width and height by a scaling factor of 1.2
pred_boxes[:, 2:] *= 1.2 # multiply width and height by 1.2

# Continue with the cropping process using the modified crop box
```

This modification will scale the width and height of the predicted bounding boxes by a factor of 1.2, making the crop box larger.

Please feel free to implement this modification and submit a pull request with your changes. Your contribution will be greatly appreciated by the YOLOv5 community!

Let me know if you have any further questions or need any additional assistance.
