### ISSUE TITLE
Wrong predict

### ISSUE THREAD

**Issue by chelsea456** [ultralytics/yolov5#12102]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have trained a dataset with 2 classes, A and B. When I make predictions, everything is fine. However, there are cases where, when I introduce an object C (which is completely different in terms of shape and size), it is identified as class A with a confidence of 80%. Can you please tell me how to eliminate such cases?

**Comment by glenn-jocher** [comment]
@chelsea456 hi there! 

It's great to hear that everything is fine with your predictions. In cases where an object C is being identified as class A with a high confidence level, there are a few steps you can take to address this issue:

1. **Check your training data**: Make sure that your training dataset contains a diverse range of examples for each class, including objects with varying shapes and sizes. This will help the model better learn the distinguishing features of each class.

2. **Increase the number of training iterations**: Training your model for more iterations can sometimes improve its accuracy and ability to correctly identify objects.

3. **Adjust the model architecture**: You can try experimenting with different YOLOv5 model architectures, such as changing the size of the model or adjusting the number of layers, to potentially improve the performance on your specific dataset.

Remember, the performance of the model is influenced by various factors, including the quality and diversity of your training data. It might take some experimentation and adjustment to achieve the desired results. 

If you have any further questions, feel free to ask. Good luck with your project!
