### ISSUE TITLE
[Question] Real-time object detection/classification

### ISSUE THREAD

**Issue by soribido** [ultralytics/yolov5#12108]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Thank you for great repo.
I have a few questions about yolov5.
We are currently performing person detection on incoming frames in real time. 

1. If we use GTX1660 GPU, is real-time classification possible after real-time object detection(yolov5s) based on pytorch?
2. If it's possible, let's suppose if 10 person objects are detected in one frame. Is it appropriate to perform inference 10 times with a batch size of 1 when applying the classification model later? (We are only modifying the core functions of 'detect.py' to process it in real-time.)
3. If the classification model requires an input size of 224x224, would it be advisable to resize the image using a letterbox algorithm?
4. Is it possible to process the yolov5 model asynchronously? Are there any related examples available? (single GPU, single model. Asynchronously processes incoming frames from two cameras in real time)

**Comment by glenn-jocher** [comment]
@soribido thank you for your questions!

1. With a GTX1660 GPU, real-time classification after real-time object detection (using yolov5s) is possible. However, the speed will depend on various factors such as the size of the input image, the complexity of the classification model, and the number of objects detected.

2. If you have 10 person objects detected in one frame and you want to perform inference with a batch size of 1 for the classification model, you can certainly do that. It is a valid approach, especially if you are modifying the core functions of 'detect.py' to process it in real-time.

3. If the classification model requires an input size of 224x224, using a letterbox algorithm to resize the image is a reasonable approach. This will maintain the aspect ratio of the image while resizing it to fit the required input size.

4. Yes, it is possible to process the yolov5 model asynchronously. However, there are currently no specific examples available within the YOLOv5 repository for processing a single model asynchronously with two cameras in real-time. Implementing asynchronous processing would require careful handling of input frames and synchronization between the model and the source cameras.

I hope this helps! If you have any further questions, feel free to ask.

**Comment by soribido** [comment]
@glenn-jocher Thank you for your answering.

**Comment by glenn-jocher** [comment]
@soribido you're welcome! I'm glad I could help. If you have any more questions, feel free to ask.
