### ISSUE TITLE
Real-time object detection app with GUI

### ISSUE THREAD

**Issue by SzymonGroch** [ultralytics/yolov5#12110]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,

I want to make an app real-time object detection but with GUI. I can't wrap my head around how to display webcam feed, like what part of code in detect.py is responsible for launching detection using webcam.

the closest thing to what I want is this: https://github.com/cnyvfang/YOLOv5-GUI
but it's for image classification

fast response is appreciated

**Comment by glenn-jocher** [comment]
@SzymonGroch hi,

To display the webcam feed while performing real-time object detection, you can modify the code in `detect.py` as follows:

1. Import the necessary libraries:
```
import cv2
from PIL import Image
```

2. Replace the line that reads the image with code to read the webcam feed:
```
# Replace this line
img = Image.open(img_path)

# with this line to read from webcam
cap = cv2.VideoCapture(0)
ret, frame = cap.read()
img = Image.fromarray(frame)
```

3. Modify the detection loop to continuously read frames from the webcam:
```
while True:
    # replace this line to read from webcam
    ret, frame = cap.read()
    img = Image.fromarray(frame)

    # Rest of the code for object detection and display
    ...
```

By making these changes, the script will continuously process frames from the webcam feed and display the output with bounding boxes.

Please note that the code provided is a basic example and may need further modifications to integrate it into your specific application.

I hope this helps! If you have any further questions, feel free to ask.

Best regards,
Glenn Jocher, author and maintainer of the Ultralytics YOLOv5 repo at https://github.com/ultralytics/yolov5 under AGPL-3.0 licenses.

**Comment by SzymonGroch** [comment]
Hi,
Sorry for late replay. I was trying to implement yolov5 in C# with little success.

Regarding your code:
I'm clueless as to what am I supposed to change since I can find line you advised me to change
for example:

**Comment by SzymonGroch** [comment]
Hi,
Sorry for late replay. I was trying to implement yolov5 in C# with little success.

Regarding your code:

I'm clueless as to what am I supposed to change since I can find line you advised me to change
for example:
```
#Replace this line
img = Image.open(img_path)
```
My current attempt is:
```
import tkinter as tk
from tkinter import ttk
import cv2
import torch
from PIL import Image, ImageTk
import time
import os


custom_model_path = os.path.join("models", "znaki21.pt")
if not os.path.exists(custom_model_path):
    print("Custom model file not found in the 'models' folder.")
    exit(1)


model = torch.load("znaki21.pt")
model.eval()

def initialize_webcam():
    global cap, selected_webcam
    if cap is not None:
        cap.release()  # Release the previously opened webcam

    # Get the selected webcam index from the dropdown
    selected_webcam = webcam_var.get()

    # Initialize the selected webcam
    cap = cv2.VideoCapture(selected_webcam)
selected_webcam = 0;

try:
    cap = cv2.VideoCapture(0)  # Adjust the camera index as needed
    if not cap.isOpened():
        raise Exception("Webcam capture object could not be opened.")
except Exception as e:
    print(f"Error: {e}")


root = tk.Tk()
root.title("Real-time Object Detection")


label = ttk.Label(root)
label.pack()


fps_label = ttk.Label(root, text="FPS: ")
fps_label.pack()


webcam_label = ttk.Label(root, text="Select Webcam:")
webcam_label.pack()


available_webcams = [f"Webcam {i}" for i in range(10)]  # You can adjust the range as needed


webcam_var = tk.StringVar()
webcam_var.set(selected_webcam)  # Set the default webcam


webcam_dropdown = ttk.Combobox(root, textvariable=webcam_var, values=available_webcams)
webcam_dropdown.pack()


initialize_button = ttk.Button(root, text="Initialize Webcam", command=initialize_webcam)
initialize_button.pack()


detected_objects_listbox = tk.Listbox(root, height=20, width=30)
detected_objects_listbox.pack()

frame_count = 0
start_time = time.time()

def update_frame():
    global frame_count, start_time
    ret, frame = cap.read()

    
    results = model(frame)

   
    detections = results.pred[0]

    
    annotated_frame = detections.render()[0]

    
    frame_count += 1
    if frame_count % 10 == 0:
        elapsed_time = time.time() - start_time
        fps = frame_count / elapsed_time
        fps_label.config(text=f"FPS: {fps:.2f}")

    
    frame_rgb = cv2.cvtColor(annotated_frame, cv2.COLOR_BGR2RGB)
    frame_tk = ImageTk.PhotoImage(Image.fromarray(frame_rgb))

    label.imgtk = frame_tk
    label.configure(image=frame_tk)

    
    detected_objects_listbox.delete(0, tk.END)  # Clear the existing items
    for obj in detections.names:
        detected_objects_listbox.insert(tk.END, obj)

    label.after(10, update_frame)  # Update every 10 milliseconds


update_frame()


root.mainloop()


if cap is not None:
    cap.release()
cv2.destroyAllWindows()
```
Initially I was working without yolov5 repo but now I'm. I've tried other solutions but all of them fail at loading model phase. 

current error:
```
Traceback (most recent call last):
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\main.py", line 17, in <module>
    model.eval()
AttributeError: 'dict' object has no attribute 'eval'
```

**Comment by SzymonGroch** [comment]
Hi,
Sorry for late replay. I was trying to implement yolov5 in C# with little success now I'm trying to deploy in python app. There's new issue but I'm moving to new thread since current one is marked as **stale**.

**Comment by glenn-jocher** [comment]
@SzymonGroch hi,

No problem at all! I understand that implementing YOLOv5 in a different programming language can be challenging. Moving to a new thread is a great idea to ensure that your new issue receives the attention it deserves.

Please go ahead and provide the details of your new issue, and I'll be more than happy to help you out with deploying YOLOv5 in your Python app.

Thank you for your patience, and I look forward to assisting you further.

Regards,
Glenn Jocher
