### ISSUE TITLE
Lack of memory - killed

### ISSUE THREAD

**Issue by gpsamt** [ultralytics/yolov5#12119]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm using an i7 machine with 16 GB of RAM, and an RTX 3070 TI with 12 GB of RAM. However, I am unable to run the Yolov5 example with coco.yaml. The process ends every time without reaching the end. I'm using python 3.11.4, Cuda 12.2 and Tensort 2.12.1 in wsl ubuntu on windows 11.  I want to do a project that would need to train yolo on a local machine. Does my hardware work?
Command : python3 train.py --img 640 --batch 16 --epochs 3 --data coco128.yaml --weights yolov5s.pt --cache

![image](https://github.com/ultralytics/yolov5/assets/102432873/4610d953-d75d-48b6-bd61-088b52d6bd54)
![image](https://github.com/ultralytics/yolov5/assets/102432873/f68e2af4-c50b-4ce9-8f04-97f9e7c6d0b3)

**Comment by glenn-jocher** [comment]
@gpsamt hi there!

Based on the information you provided, it seems like you are running out of memory during training. YOLOv5, especially when using larger models like `yolov5s.pt`, can be memory-intensive.

To optimize memory usage, you can try the following solutions:

1. Reduce the batch size (`--batch`) to a smaller value. This will decrease the amount of memory required for each iteration, but may increase training time.

2. Decrease the input image size (`--img`). Smaller images require less memory, but may impact detection accuracy.

3. If possible, consider upgrading your hardware to have more GPU memory. This will allow you to train with larger batch sizes and image sizes without running into memory issues.

Please note that YOLOv5 performance greatly depends on hardware and dataset size. If you're working with large datasets, you may need to consider distributed training on multiple GPUs or using cloud-based solutions like Google Colab or AWS.

Let me know if you need further assistance!
