### ISSUE TITLE
Gradio for YOLOv5

### ISSUE THREAD

**Issue by WangQvQ** [ultralytics/yolov5#12115]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Hi, I've been using a lot of big models lately and they all have gradio pages, I also tried to write one for YOLO, do I need to contribute code? 

### Use case

This test seems friendly to beginners.

### Additional

![image](https://github.com/ultralytics/yolov5/assets/58406737/eecefa0e-bf84-414c-b234-3d7e9c470fe9)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@WangQvQ hi there! 😊 Thank you for your interest in contributing to YOLOv5 and wanting to create a Gradio interface for YOLOv5.

Contributions are always welcome! If you would like to submit a Pull Request (PR) for the Gradio integration, it would be greatly appreciated. By doing so, you will be helping beginners and providing an easy-to-use interface for YOLOv5.

If you have any questions or need further assistance, please don't hesitate to ask. The YOLOv5 community and the Ultralytics team are here to support you throughout the process.

We look forward to your contribution and appreciate your efforts in making YOLOv5 even more accessible for everyone! 🚀🔥

**Comment by WangQvQ** [comment]
Thank you. I have submitted the Pull Request！https://github.com/ultralytics/yolov5/pull/12116

![image](https://github.com/ultralytics/yolov5/assets/58406737/268f79f5-9b03-4305-9c5f-6b0c74884d77)
![image](https://github.com/ultralytics/yolov5/assets/58406737/94b3a29e-f584-4da2-becf-2d24b5f96c52)

**Comment by glenn-jocher** [comment]
@WangQvQ thanks a lot for submitting the Pull Request! 👍🎉 We really appreciate your contribution in adding the Gradio integration to YOLOv5. Your effort will definitely make YOLOv5 more beginner-friendly and accessible to users. Our team will review your PR and provide feedback as soon as possible. Once again, thank you for your valuable contribution! 🙏🚀
