### ISSUE TITLE
Why is the inference time of CPU and GPU so different?

### ISSUE THREAD

**Issue by grapefruitL** [ultralytics/yolov5#1211]
## ❔Question
I test the inference time with command: python detect.py
my GPU is nvidia p100, my cpu clock speed is 2.1Hz
the gpu output is:
```
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.25, device='2', img_size=640, iou_thres=0.45, output='inference/output', save_conf=False, save_txt=False, source='inference/images', update=False, view_img=False, weights='yolov5s.pt')
Using CUDA device0 _CudaDeviceProperties(name='Tesla P100-PCIE-16GB', total_memory=16280MB)

Fusing layers... 
Model Summary: 140 layers, 7.45958e+06 parameters, 0 gradients
image 1/2 /new_home/kevin/train_dir/yolov5/inference/images/bus.jpg: 640x480 4 persons, 1 buss, 1 skateboards, Done. (0.022s)
image 2/2 /new_home/kevin/train_dir/yolov5/inference/images/zidane.jpg: 384x640 2 persons, 2 ties, Done. (0.019s)
Results saved to inference/output
Done. (0.156s)
```
 and the cpu output is:
```
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.25, device='cpu', img_size=640, iou_thres=0.45, output='inference/output', save_conf=False, save_txt=False, source='inference/images', update=False, view_img=False, weights='yolov5s.pt')
Using CPU

Fusing layers... 
Model Summary: 140 layers, 7.45958e+06 parameters, 0 gradients
image 1/2 /new_home/kevin/train_dir/yolov5/inference/images/bus.jpg: 640x480 4 persons, 1 buss, 1 skateboards, Done. (4.138s)
image 2/2 /new_home/kevin/train_dir/yolov5/inference/images/zidane.jpg: 384x640 2 persons, 2 ties, Done. (3.739s)
Results saved to inference/output
Done. (8.402s)
```
Why is the inference time of CPU and GPU so different?
The inference time of [yolov3tiny ](https://github.com/qqwweee/keras-yolo3)on GPU and CPU is 20ms and 80ms respectively

**Comment by zhiqwang** [comment]
The time they computed may not be consistent, It's hard to compare in this way I think.

**Comment by glenn-jocher** [comment]
@grapefruitL try a working environment.
<img width="1307" alt="Screenshot 2020-10-26 at 10 34 44" src="https://user-images.githubusercontent.com/26833433/97156454-00638000-1777-11eb-833e-8f366f835724.png">


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by grapefruitL** [comment]
It’s really weird. I added “--device cpu” and it was OK, and it was also OK after I removed it, but it was always more than 2s without adding it before.
Anyway, just solve the problem
