### ISSUE TITLE
parameters freeze invalid

### ISSUE THREAD

**Issue by densechen** [ultralytics/yolov5#1213]
Hi, thanks for providing so nice code.
In this line, we set freeze parameters with requires_grad=False, 
https://github.com/ultralytics/yolov5/blob/453acdec67202e15b772370d31eb196d844f2892/train.py#L88
However, in the following line, all paremters have been set as requires_grad=True, which overwrite the previous settings.
https://github.com/ultralytics/yolov5/blob/453acdec67202e15b772370d31eb196d844f2892/train.py#L97

**Comment by glenn-jocher** [comment]
@densechen thank you for your feedback. This item is currently a TODO https://github.com/ultralytics/yolov5/issues/679#issuecomment-671747773
