### ISSUE TITLE
how can i get the bounding boxes coordinate while running detection with webcam

### ISSUE THREAD

**Issue by cheikh98** [ultralytics/yolov5#12149]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

i am a beginner and i want to know how can i get the bounding boxes coordinate while running detection with webcam? i would like to save the coordinates in a .csv file.i want to use best.pt and not a pretrained models. i found this code in the net and i want to modify it.
![code4](https://github.com/ultralytics/yolov5/assets/114055857/f87b48b2-7de1-4e7c-838d-e542288cc7e9)
i post the url below
[https://stackoverflow.com/a/71174150/22151277](url)
@glenn-jocher

**Comment by RizwanMunawar** [comment]
To store the results in a CSV file named `results.csv`, you can modify your code as follows:

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, etc.

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

# Save results to a CSV file
results_df = results.pandas().xyxy[0]
results_df.to_csv('results.csv', index=False)

```

This code first loads the YOLOv5 model performs inference on the image, and then saves the results in a CSV file named `results.csv` using the `to_csv` method of a pandas DataFrame. The `index=False` argument ensures that the index is not saved to the CSV file.

Thanks
