### ISSUE TITLE
 j, k = ((gxy % 1. < g) & (gxy > 1.)).T 

### ISSUE THREAD

**Issue by zxj11838** [ultralytics/yolov5#1214]
## ❔Question
In the build_target() method, when calculating j、k,  Does it need to be written as follows：

j, k = ((gxy % 1. < g) & (gxy > 1.) & (gxy < torch.tensor(p[i].shape)[2] - 1)).T

**Comment by glenn-jocher** [comment]
@zxj11838 if you're considering a change in the codebase I would suggest you train before and after your proposed change to determine the effect.
