### ISSUE TITLE
Regarding anchor boxes specification

### ISSUE THREAD

**Issue by VineethMindtrace** [ultralytics/yolov5#12147]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Are the anchors in the yolov5s.yaml defined with respect to the original image size, or the feature map size at which the detection takes place.
For example are the following anchors defined wrt to the original dimensions of 640x640?
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

Additionally, how could we increase the number of anchors? If the anchors are defined with respect to the size of the feature map at the particular scale, how can i relate the bounding box labels to the anchor box size?

**Comment by glenn-jocher** [comment]
@VineethMindtrace the anchors in the yolov5s.yaml file are defined with respect to the feature map size at which the detection takes place, not the original image size. The anchor values provided in the file represent the width and height of the anchor boxes at different scales.

To increase the number of anchors, you can add additional anchor values to the yolov5s.yaml file for the desired scale(s). Make sure to maintain the same format and order of the anchor values.

When relating the bounding box labels to the anchor box size, the network will learn the offsets required to adjust the anchor boxes to fit the objects in the image. The bounding box labels are specified as normalized values (relative to the image size), and the network will use these offsets to adjust the anchor boxes accordingly.

Let me know if you have any further questions!
