### ISSUE TITLE
YOLOv5 classification with 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by wubeizi** [ultralytics/yolov5#12145]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

I encountered issues with 'NoneType' object has no attribute 'shape' and PNG input buffer is incomplete when using YOLOv5 for image classification tasks. After reviewing relevant information, I attempted to update the version of YOLOv5 and check for any damage to the images in the dataset. However, these methods still failed to solve the problem. The screenshot of the problem and error message are as follows:
![image](https://github.com/ultralytics/yolov5/assets/95267485/f81184df-1c29-46a6-88e1-18f520d33b8d)
![image](https://github.com/ultralytics/yolov5/assets/95267485/d96ed857-b1f2-46b3-936a-4b2142d6c1c8)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by RizwanMunawar** [comment]
Hey @wubeizi, could you please check the image for any potential corruption? It appears that the code is attempting to retrieve the image's width and height but is encountering difficulties, which could suggest that the image might be corrupted or unsuitable for use.

Thanks
