### ISSUE TITLE
Problem with numbers Confusion matrix

### ISSUE THREAD

**Issue by ekiprogram** [ultralytics/yolov5#12148]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I am working on a project with yolov7 and I get the following error in the confusion matrix for two data families (I delete names for privacy) What can be happening when last week I got it right and now it is wrong?
![image](https://github.com/ultralytics/yolov5/assets/145541804/a9dc66a4-4cfc-4a37-8b95-9b20c294151e)

Any incompatibility in the versions of the libraries?

Thank you very much

**Comment by kim2429** [comment]
I also have the same problem when working on a project with the YOLOV5 model. 

Could you let me know if you solved the problem??

**Comment by glenn-jocher** [comment]
@kim2429 hi, 

I understand that you are facing the same problem with the YOLOv5 model. Unfortunately, the previous user did not provide any specific details about the issue. 

To assist you better, could you please provide more information about the problem you are encountering? Include any error messages or logs that you are seeing, along with details about your dataset, training setup, and any modifications you made to the YOLOv5 code.

This will help me in understanding the issue and provide you with an appropriate solution.

Thank you.

**Comment by kim2429** [comment]
@glenn-jocher Hi,

Thank you for getting back to me.

Unfortunately, there were no error messages or logs.

I trained the yolov5x model using a dataset with 35 classes.

I ran the val.py to test the trained model with modified metrics.py

The change of metrics.py was below (lines 200-210).

sn.heatmap(array,
                       ax=ax,
                       annot=nc < 50,
                       annot_kws={
                           'size': 5},
                       cmap='Blues',
                       fmt='.2f',
                       square=True,
                       vmin=0.0,
                       xticklabels=ticklabels,
                       yticklabels=ticklabels).set_facecolor((1, 1, 1))

If you need any information, please let me know.

Thank you.

**Comment by glenn-jocher** [comment]
@kim2429,

Thank you for providing additional details about your issue.

Based on your description, it seems like you trained the yolov5x model using a dataset with 35 classes. You then ran `val.py` to test the trained model with modified `metrics.py` in the `sn.heatmap` section.

To further investigate the issue, it would be helpful to have more information such as the specific problem or unexpected behavior you are observing. Any error messages or logs related to the issue would also be beneficial in diagnosing the problem.

Please provide any additional information you can share, and I'll do my best to assist you.

Thank you.

**Comment by kim2429** [comment]
@glenn-jocher 

Thank you for your response.

When I trained the model, there were warning messages like the one below.

/home/jil/.local/lib/python3.11/site-packages/seaborn/_oldcore.py:1498: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(vector):

/home/jil/.local/lib/python3.11/site-packages/seaborn/_oldcore.py:1119: FutureWarning: use_inf_as_na option is deprecated and will be removed in a future version. Convert inf values to NaN before operating instead.
  with pd.option_context('mode.use_inf_as_na', True):

I hope this can help diagnose the problem.

Thank you.

**Comment by glenn-jocher** [comment]
@kim2429 hi,

Thank you for providing additional information.

The warning messages you shared seem to be related to the `seaborn` library and not directly related to the YOLOv5 model. These warnings generally indicate that certain functionalities or options used in the `seaborn` library are deprecated and may be removed in future versions.

While these warning messages are not critical, it is always a good practice to keep your dependencies up-to-date to ensure compatibility and to avoid any potential issues.

To address the warnings, you can try updating the `seaborn` library to the latest version or see if there are any specific fixes available in the library's documentation or GitHub repository.

If the warning messages are not causing any noticeable issues with your YOLOv5 model's performance or results, you should still be able to proceed with your testing and evaluation.

Please let us know if you have any further questions or if there is anything else we can assist you with.

Thank you.

**Comment by kim2429** [comment]
@glenn-jocher 

Thank you for your suggestion.

I updated Seaborn Library from v0.12 to v0.13, and the problem was solved!

Thank you again for your suggestion.

**Comment by glenn-jocher** [comment]
@kim2429 great to hear that updating the Seaborn library to version 0.13 resolved the problem for you! Thank you for providing this update.

If you have any further questions or if there is anything else we can assist you with, please let us know.

Thank you for using YOLOv5 and have a great day!

**Comment by ekiprogram** [comment]
Hello

I have been able to solve the problem but by modifying the version of the matplotlib library. I set it to 3.2.2.2 and it works perfectly.

thank you very much

**Comment by glenn-jocher** [comment]
@ekiprogram that's great to hear! I'm glad to know that modifying the version of the matplotlib library to 3.2.2 resolved the issue for you. If you have any other questions or need further assistance in the future, please feel free to reach out.

Thank you for your contribution, and have a fantastic day!
