### ISSUE TITLE
changed yolov5 model,i can train the model but when i run val process,a error about dimension not  matched occured(H,W of the image is wrong).

### ISSUE THREAD

**Issue by zdwwt** [ultralytics/yolov5#12150]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I can train an epoch model normally, but after training an epoch
During automatic verification on the validation set, an error occurred where the image size did not match. What is the reason for this? Is there any inconsistency in the preprocessing of the image during training and validation, or what is the possible reason? We sincerely request your answer! Thank you!
![1](https://github.com/ultralytics/yolov5/assets/96174041/580598d9-f2df-46f2-bf52-cd9f62e2c8ca)

**Comment by glenn-jocher** [comment]
@zdwwt hi there, it sounds like the error you're encountering during validation may be related to inconsistency in the preprocessing of the images between training and validation. Perhaps the image dimensions are being adjusted differently during these processes. Double-check the preprocessing steps and ensure consistency in image dimensions for both training and validation. Keep us posted on your progress!
