### ISSUE TITLE
Can i set different iou-thresh for different class

### ISSUE THREAD

**Issue by jzx-gooner** [ultralytics/yolov5#12152]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

RT
For example:
if i detect three class A，B，C
I want set class A,B the --iou-thres is 0.5
and set class c the --iou-thres 0.3
Does the repo support this feature?
Thank you very much!

**Comment by glenn-jocher** [comment]
@jzx-gooner hi there! Yes, you can set different `--iou-thres` values for different classes in YOLOv5. You can achieve this by modifying the `--iou-thres` argument in the `detect.py` script according to your requirements. Please note that this modification needs to be done in the code, and it is not supported as a built-in feature in the repo. If you need any further assistance, feel free to ask. Happy coding!
