### ISSUE TITLE
What -img-size value use?

### ISSUE THREAD

**Issue by a-esp-1** [ultralytics/yolov5#1215]
## ❔Question
Hi,

 I'm using YOLOv5 and I have a few cuestions. I have 1000x2000 images, so when I run detect.py what value should I use in --img-size? I mean I can use 1000, 2000 or 1500. So why should I use the largest or the smallest?

Another question. Is the image being scaled? I mean if I set 2000, what happens with the image? Is it scale to 2000x2000? Or is the image padded?

Thank you in advance.

**Comment by glenn-jocher** [comment]
@a-esp-1 you can use any size you want. Inputs are scaled and letterboxed as required to meet your requested --img-size.

**Comment by dongjuns** [comment]
You can find out the best image size for your model by some tests. Just get it-! :sunglasses:

**Comment by pngmafia** [comment]
@dongjuns can you please mention those tests. I am kinda starting out in this area.

**Comment by dongjuns** [comment]
@pngmafia When you train your model, you can choose the option --img like this,
if your image size is 720 x 720 pixels,
```
python train.py --img 704 --batch 32 --epochs 100 --data data.yaml --cfg yolov5s.yaml --weights yolov5s.pt
or
python train.py --img 736 --batch 32 --epochs 100 --data data.yaml --cfg yolov5s.yaml --weights yolov5s.pt
```
You can find out a little better result while changing the image size, but it depends on your dataset.

**Comment by pngmafia** [comment]
@dongjuns yes I understand using the option to change the values. But how do I figure out the best value for my dataset. My dataset is not really uniform when it comes to sizes.
