### ISSUE TITLE
Validation in DDP training

### ISSUE THREAD

**Issue by junghyun-avikus** [ultralytics/yolov5#12163]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

In the train.py, the following lines are how map is calculated after each epoch.

https://github.com/ultralytics/yolov5/blob/6262c7feb42cd181f165681b9aff428785c0ff7e/train.py#L412-L436

It seems like non main processes do not wait for the main process while it is calculating map like when downloading datasets or models does with torch_distributed_zero_first context.

If this is the case, do other processes start the next epoch? Or am I missing something?

**Comment by dmsy4** [comment]
Also there's trouble with NCLL timeout exception when validation is longer than 1800 seconds (default `dist.init_process_group` `timeout` argument). Fortunately increasing `timeout` solves this problem

**Comment by glenn-jocher** [comment]
@dmsy4 hello,

In the YOLOv5 training script, the main process calculates the mAP (mean average precision) after each epoch, but it seems that the other processes do not wait for it to finish. This may raise questions about whether the other processes start the next epoch without waiting.

Actually, the other processes do wait for the main process to finish calculating the mAP. The function `torch_distributed_zero_first()` is used to ensure that the other processes synchronize with the main process when downloading datasets or models. However, this synchronization is not required for calculating mAP.

Regarding your additional issue with the NCLL timeout exception, increasing the `timeout` argument in the `dist.init_process_group` function can indeed solve this problem. 

I hope this clarifies the process for you. If you have any further questions, feel free to ask.

Regards,
Glenn Jocher

**Comment by junghyun-avikus** [comment]
@glenn-jocher 
Oh, so the function torch_distributed_zero_fisrt is for synchronization.

Then how do you make sure that other processes wait for the main process to finish calculating the mAP?
The code snippet that I posted will be run by only the main process, and it might take several minutes.
And I don't see any lines that tell the other processes to wait, so I am just curious how they still wait for the other processes.

**Comment by glenn-jocher** [comment]
@junghyun-avikus the other processes in the YOLOv5 training script do actually wait for the main process to finish calculating the mAP. While the `torch_distributed_zero_first()` function is used for synchronization in certain parts of the code, it is not necessary for the calculation of mAP.

The code snippet you posted, which calculates the mAP, is indeed run by only the main process and it can take several minutes to complete. However, the other processes implicitly wait for the main process to finish this calculation before proceeding to the next epoch. This is handled by the underlying communication and synchronization mechanisms provided by the PyTorch DistributedDataParallel (DDP) module.

I hope this clarifies the process for you. If you have any further questions, feel free to ask.

Glenn Jocher
