### ISSUE TITLE
IndexError: index 8 is out of bounds for dimension 1 with size 4

### ISSUE THREAD

**Issue by EngrNaeemRaza** [ultralytics/yolov5#12161]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Traceback (most recent call last):
  File "/content/drive/MyDrive/yolov5_experiment/yolov5-master/train.py", line 647, in <module>
    main(opt)
  File "/content/drive/MyDrive/yolov5_experiment/yolov5-master/train.py", line 536, in main
    train(opt.hyp, opt, device, callbacks)
  File "/content/drive/MyDrive/yolov5_experiment/yolov5-master/train.py", line 359, in train
    results, maps, _ = validate.run(data_dict,
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/drive/MyDrive/yolov5_experiment/yolov5-master/val.py", line 214, in run
    loss += compute_loss(train_out, targets)[1]  # box, obj, cls
  File "/content/drive/MyDrive/yolov5_experiment/yolov5-master/utils/loss.py", line 156, in __call__
    t[range(n), tcls[i]] = self.cp
IndexError: index 8 is out of bounds for dimension 1 with size 4

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by EngrNaeemRaza** [comment]
Solved.

**Comment by glenn-jocher** [comment]
@EngrNaeemRaza great to hear that the issue has been solved! If you don't mind, could you please provide some details on how you resolved it? This would be helpful for others who might encounter a similar problem in the future. Remember that the YOLOv5 community is always here to offer support and assistance. Thanks again for your contribution!

**Comment by kjcx100** [comment]
same to me

**Comment by glenn-jocher** [comment]
@kjcx100 hi,

Thank you for reaching out. I'm sorry to hear that you're facing the same issue. Could you please provide some additional information about the problem? Specifically, it would be helpful to know the steps you followed and any error messages you encountered. This will allow us to better understand the issue and assist you in finding a solution.

Please feel free to share any relevant details, and we'll do our best to help you out.

Best, 
Glenn

**Comment by kjcx100** [comment]
from this suggest，i solved my problem https://github.com/ultralytics/yolov5/issues/9342#issuecomment-1248685039
thanks

**Comment by glenn-jocher** [comment]
@kjcx100 hi there,

I'm glad to hear that you were able to solve your problem! Thank you for sharing the solution. This is a great example of the supportive community we have around YOLOv5.

If you have any more questions or need further assistance, please don't hesitate to reach out. We're here to help!

Regards,
Glenn
