### ISSUE TITLE
How to use the detect.py file to detect live streaming？

### ISSUE THREAD

**Issue by QiuTian666** [ultralytics/yolov5#12167]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, brother. I want to use the detect.py file to detect live streaming on YouTube, but an error was reported:

AssertionError: 1/1: https://www.youtube.com/watch?v=ggOL44AhnL4... Failed to open https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1695719694/ei/rkwSZYbSKZCq1d8Pkqm3-AM/ip/165.154.243.252/id/ggOL44AhnL4.1/itag/95/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D136/hls_chunk_host/rr5 ---Sn-un57sne7.googlevideo.com playlist_ Duration/30/manifest_ Duration/30/spc/UWF9f5SU5lzxQpN34m0Pel30pOEYAV50nFv48MLuCA/vprv/1/playlist_ Type/DVR/initcwndbps/906250/mh/Yd/mm/44/mn/sn un57sne7/ms/lva/mv/m/mvi/5/pl/24/cover/11/covering/0/keepalive/yes/fexp/24007246/beids/24350018/mt/16956977/sparks/expire, ei, ip, id, itag, source, requestl, rateypass, live, sgoap, sgovp, playlist_ Duration, manifest_ Duration, spc, vprv, playlist_ Type/sig/AOq0QJ8wRAIgcHo4KNjuuwr65OzG16uOIb7lnmrw7xgsoAkSTZPMtSkCIEVtTPY9uGPLY9NcjG0CcgVVslePdGyYf2XHz-1Dl1j/lsparams/hls_ Chunk_ Host, initcwndbps, mh, mm, mn, ms, mv, mvi, pl/lsig/AG3C_ XAwRQIgX1aHk ZPO jYzP9BTmvoTUOOfURu40rQNp0OHMokoFsCIQDIWIU3RYCoOi4DBOUhBQf9GwxfwP3549hshmzFT6W52g% 3D/playlist/index.m3u8
[TCP @ 00000 21a30eca280] Connection to tcp://manifest.googlevideo.com:443 Failed: Error number -138 occurred

Can you help me? Thank you!

### Additional

That's what I wrote about the source line：
parser.add_argument('--source', type=str, default='https://www.youtube.com/watch?v=ggOL44AhnL4', help='file/dir/URL/glob, 0 for webcam')

Among them, https://www.youtube.com/watch?v=ggOL44AhnL4 is a live streaming website I casually found.
And I have no problem detecting videos on YouTube, but detecting live broadcasts will be like this.

**Comment by RizwanMunawar** [comment]
@QiuTian666, you can effortlessly execute the YouTube video using the provided command in the command line or terminal.

```bash
python detect.py --weights yolov5s.pt --source "https://www.youtube.com/watch?v=ggOL44AhnL4" --view-img
```

Thanks

**Comment by QiuTian666** [comment]
Hey, man! Thank you very much for your idea and reply!
But I still encountered a problem: when I used the method you mentioned to detect videos on YouTube, there was no problem at all. However, when I detected Live streaming website on YouTube, it would report an error. Why is this?
The two are only different in the source, and the detection video is
Python detect.py -- weights runs/train/yolov5s/weights/best. pt -- source“ https://www.youtube.com/watch?v=X -Q08HQq7fM "-- view img -- project" run/detect“
Detection live broadcast is
Python detect.py -- weights runs/train/yolov5s/weights/best. pt -- source“ https://www.youtube.com/watch?v=uXNU0XgGZhs -- view img -- project "run/detect“
These are the situations where I detected video and live streaming, respectively:
Video：
(cuda117) H:\Bks\yolov5-6.1>python detect.py --weights runs/train/yolov5s/weights/best.pt --source "https://www.youtube.com/watch?v=X-Q08HQq7fM" --view-img --project "run/detect" 
     
detect: weights=['runs/train/yolov5s/weights/best.pt'], source=https://www.youtube.com/watch?v=X-Q08HQq7fM, data=, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=True, save_
txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=run/detect, name=exp, exist_ok=False, line_thickness=3, hide_l
abels=False, hide_conf=False, half=False, dnn=False

requirements: numpy==1.18.5 not found and is required by YOLOv5, attempting auto-update...
requirements: 'pip install numpy==1.18.5' skipped (offline)
YOLOv5  2022-2-22 torch 1.13.1+cu117 CUDA:0 (NVIDIA GeForce GTX 1070, 8192MiB)

Fusing layers... 
Model Summary: 213 layers, 7012822 parameters, 0 gradients, 15.8 GFLOPs
[tcp @ 000001de9f375bc0] Connection to tcp://rr2---sn-vgqsknld.googlevideo.com:443 failed: Error number -138 occurred
1/1: https://www.youtube.com/watch?v=X-Q08HQq7fM...  Success (16744 frames 1280x720 at 29.97 FPS)

0: 384x640 Done. (0.433s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.010s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.007s)

Live broadcast：
(cuda117) H:\Bks\yolov5-6.1>python detect.py --weights runs/train/yolov5s/weights/best.pt --source "https://www.youtube.com/watch?v=uXNU0XgGZhs" --view-img --project "run/detect" 

detect: weights=['runs/train/yolov5s/weights/best.pt'], source=https://www.youtube.com/watch?v=uXNU0XgGZhs, data=, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=True, save_
txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=run/detect, name=exp, exist_ok=False, line_thickness=3, hide_l
abels=False, hide_conf=False, half=False, dnn=False

requirements: numpy==1.18.5 not found and is required by YOLOv5, attempting auto-update...
requirements: 'pip install numpy==1.18.5' skipped (offline)
YOLOv5  2022-2-22 torch 1.13.1+cu117 CUDA:0 (NVIDIA GeForce GTX 1070, 8192MiB)
Fusing layers... 
Model Summary: 213 layers, 7012822 parameters, 0 gradients, 15.8 GFLOPs
[tcp @ 00000200d3fda280] Connection to tcp://manifest.googlevideo.com:443 failed: Error number -138 occurred
[ERROR:0@39.207] global cap.cpp:166 cv::VideoCapture::open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_images.cpp:235: error: (-5:Bad argument) CAP_IMAGES: error, expected '0?[1-9][du]' pattern, got: https://manifest.googlevideo.com/a
pi/manifest/hls_playlist/expire/1695911918/ei/jjsVZczoBLC-sfIPhd25KA/ip/92.118.112.86/id/uXNU0XgGZhs.1/itag/301/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/
gir%3Dyes%3Bitag%3D299/hls_chunk_host/rr5---sn-vgqskn67.googlevideo.com/playlist_duration/30/manifest_duration/30/spc/UWF9f55G22wwxiM09aZ0kJ6OG7jQkJiRZE7mQ7-Alg/vprv/1/playlist_type/DVR/mh/Sq/mm/44/mn/sn-vgqsk
n67/ms/lva/mv/u/mvi/5/pl/25/dover/11/pacing/0/keepalive/yes/fexp/24007246/beids/24350017/mt/1695889882/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,sgoap,sgovp,playlist_duration,manifest_dura
tion,spc,vprv,playlist_type/sig/AOq0QJ8wRQIhAPwbNmI0DCTRAyAd1xVMCIJPHsr8n42kXhaJCWbPLBRgAiB-wtBJ0LePlo8_p60oWpB-xSiSt3p3ZcwxMOgRpzvg2A%3D%3D/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl/lsig/AG3C_xAwRAIgeCH-7
5rBWVAP6bkUiD6vMt54rraQCc4Ju_hVBkd1Fo8CICd5gCHyHLsIyHmwg8ZYuflPpvWGfUlIA8qfRoXfAxBS/playlist/index.m3u8 in function 'cv::icvExtractPattern'

Traceback (most recent call last):
  File "H:\Bks\yolov5-6.1\detect.py", line 257, in <module>
    main(opt)
  File "H:\Bks\yolov5-6.1\detect.py", line 252, in main
    run(**vars(opt))
  File "D:\Anaconda3\envs\cuda117\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "H:\Bks\yolov5-6.1\detect.py", line 105, in run
    dataset = LoadStreams(source, img_size=imgsz, stride=stride, auto=pt)
  File "H:\Bks\yolov5-6.1\utils\datasets.py", line 309, in __init__
    assert cap.isOpened(), f'{st}Failed to open {s}'
AssertionError: 1/1: https://www.youtube.com/watch?v=uXNU0XgGZhs... Failed to open https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1695911918/ei/jjsVZczoBLC-sfIPhd25KA/ip/92.118.112.86/id/uXN
U0XgGZhs.1/itag/301/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D299/hls_chunk_host/rr5---sn-vgqskn67.googlevideo.com/playlist_duration/30
/manifest_duration/30/spc/UWF9f55G22wwxiM09aZ0kJ6OG7jQkJiRZE7mQ7-Alg/vprv/1/playlist_type/DVR/mh/Sq/mm/44/mn/sn-vgqskn67/ms/lva/mv/u/mvi/5/pl/25/dover/11/pacing/0/keepalive/yes/fexp/24007246/beids/24350017/mt/
1695889882/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,sgoap,sgovp,playlist_duration,manifest_duration,spc,vprv,playlist_type/sig/AOq0QJ8wRQIhAPwbNmI0DCTRAyAd1xVMCIJPHsr8n42kXhaJCWbPLBRgAiB-
wtBJ0LePlo8_p60oWpB-xSiSt3p3ZcwxMOgRpzvg2A%3D%3D/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl/lsig/AG3C_xAwRAIgeCH-75rBWVAP6bkUiD6vMt54rraQCc4Ju_hVBkd1Fo8CICd5gCHyHLsIyHmwg8ZYuflPpvWGfUlIA8qfRoXfAxBS/playlist
/index.m3u8


Why is this? Thank you！

**Comment by glenn-jocher** [comment]
@QiuTian666 hi there,

Thank you for reaching out and providing detailed information regarding your issue. From the error messages you've provided, it seems that there is an issue with accessing the live stream on YouTube when using YOLOv5 for detection.

The error message indicates that there was a failed attempt to open the live stream source: "https://manifest.googlevideo.com/api/manifest/hls_playlist/..."

Unfortunately, without further context or access to the code, it is challenging to pinpoint the exact cause of this issue. It's possible that the particular live stream you are trying to access may have certain restrictions or requires additional configurations for YOLOv5 to work correctly.

One suggestion would be to check if the live stream has any viewing restrictions, such as age restrictions or location-based restrictions. Additionally, ensure that you are using the latest version of YOLOv5 and have all the necessary dependencies installed correctly.

If the issue persists, I recommend raising this concern in the YOLOv5 GitHub repository, where the developers can provide more specific guidance and assist you further.

I hope this helps, and please let me know if you have any further questions or concerns.

Thank you!
