### ISSUE TITLE
Is yolov5 supported by libTorch CPP for inference?

### ISSUE THREAD

**Issue by rtrahms** [ultralytics/yolov5#1216]
## ❔Question
Successfully trained and tested a yolov5 network using cloned repo and darknet-formatted data.
Generated pt file loads into netron.
Built a CPP app to load and use the pt file for inference.
On call to torch::jit::load(pt_file_path), exception thrown.
This happens on both CPU and CUDA variants of libTorch.

## Additional context
Visual Studio 2019
PyTorch 1.6 (libTorch)
CUDA 10.1 & CPU versions

**Comment by glenn-jocher** [comment]
@rtrahms no idea, never used libtorch. You may want to verify your workflow with a dummy model first, as YOLOv5 introduces many custom ops like hardswish etc.

**Comment by InfiniteLife** [comment]
Yes, you can. May be you need to successfully convert your model to torchscript first. And then load torchscript to C++, that's what I did. 
I had problems running model in C++ with CUDA on prebuilt libtorch(having the same setup as you do), though on CPU it was fine. I built libtorch myself and it started working.

**Comment by WANGCHAO1996** [comment]
> 
> 
> Yes, you can. May be you need to successfully convert your model to torchscript first. And then load torchscript to C++, that's what I did.
> I had problems running model in C++ with CUDA on prebuilt libtorch(having the same setup as you do), though on CPU it was fine. I built libtorch myself and it started working.

hello,yolov3 model how to convert model to torchscript ?and how to built libtorch? tahnks！I need something urgent.

**Comment by glenn-jocher** [comment]
@WANGCHAO1996 you might want to read the README:
https://docs.ultralytics.com/yolov5
