### ISSUE TITLE
Yolov5 models not scriptable

### ISSUE THREAD

**Issue by mikeseven** [ultralytics/yolov5#1217]
When trying to torch.jit.script() or trace(), there are errors due to tensor shapes not matching in torch.cat.
Likely some errors before that makes tracing infer wrong shapes.

Thanks for making Yolo v5 sciptable...

**Comment by zhiqwang** [comment]
Hi @mikeseven , I had written a `torchscript` yolov5 based on ultralytics's implementation [here](https://github.com/zhiqwang/yolov5-rt-stack). It seems that `torch.cat` here is the key to make ultralytics's yolov5 scriptable, I write a quick and dirty implentation in my own [repo](https://github.com/zhiqwang/yolov5-rt-stack/blob/4ccb662b62ccde15276113a1cac04626cd5b5583/models/backbone.py#L165-L180).

And suggestions are welcome )

**Comment by mikeseven** [comment]
Awesome. Thanks!
