### ISSUE TITLE
Where callbacks are defined inside the Yolov5 code

### ISSUE THREAD

**Issue by eypros** [ultralytics/yolov5#12170]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am using Yolov5 for some time now and I came upon the requirement to alter a callback during training.
More specifically I need to add some values to be monitored in the results.csv file which is updated after each epoch.

I have searched the code but could not find the exact location where I should add the extra code.
According to this [link](https://community.ultralytics.com/t/is-there-any-callbacks-used-in-yolov5/148) from Glenn callbacks are found in [callbacks.py](https://github.com/ultralytics/yolov5/blob/c4cb7c684ad6baf4081eb59ee1c27aa97bed4ebe/utils/callbacks.py#L7-L33) but this is just a skeleton of the code.

I have used a previous version of the code in which I could find comet code (I have the impression that it is replaced in recent version but maybe I am mistaken) in which inside __init__.py I could find a piece of code a little bigger but not the one I was looking for. 

So, my question is where should I search for to find the place to put my code for adding extra values in results.csv?

**Comment by glenn-jocher** [comment]
@eypros hi,

Thank you for your question. 

To add additional values in the `results.csv` file during training in YOLOv5, you can modify the `train.py` script. In the `train.py` script, there is a `train()` function where you can find the following line of code:

```
logger = Logger(wdir, save_dir, hyp)  # logger instance (opt.visual, opt.wandb, opt.log_imgs)
```

After this line of code, you can add your own code to log additional values to the `results.csv` file.

I hope this helps! Let me know if you have any further questions.

**Comment by eypros** [comment]
Thank you Glenn for your response. 

Basically, after inspecting the code more thoroughly I found that the actual part of writing the results.csv is inside _`utils/loggers/__init__.py`_
```

    def on_fit_epoch_end(self, vals, epoch, best_fitness, fi):
        # Callback runs at the end of each fit (train+val) epoch
        x = dict(zip(self.keys, vals))
        if self.csv:
            file = self.save_dir / 'results.csv'
            n = len(x) + 1  # number of cols
            s = '' if file.exists() else (('%20s,' * n % tuple(['epoch'] + self.keys)).rstrip(',') + '\n')  # add header
            with open(file, 'a') as f:
                f.write(s + ('%20.5g,' * n % tuple([epoch] + vals)).rstrip(',') + '\n')
         ....
```

**Comment by glenn-jocher** [comment]
@eypros you're welcome!

Yes, you are correct. The code responsible for writing the results to the `results.csv` file can be found in the `on_fit_epoch_end()` method of the `__init__.py` file located in `utils/loggers`. 

Inside this method, you can see that it writes the results to the file using the `open` function and appends the values for each epoch.

If you have any further questions, feel free to ask!

**Comment by effectXS** [comment]
Hi, 

I am newbie. below is my training which i referred from [here](https://pypi.org/project/yolov5/).
I am able to train but I want to add my own custom callbacks for logging in another system.

Training code: 
```
from yolov5 import train, val, detect, export
train.run(imgsz=640, data='coco128.yaml')
```


My custom call function inspired from this section:
```
def on_fit_epoch_end(self, vals, epoch, best_fitness, fi):
    # Callback runs at the end of each fit (train+val) epoch
    payload = dict(zip(self.keys, vals))
    r = requests.post("http://localhost:9001/post_results", data=payload)
    if not r.ok:
        raise Exception("GET failed with status code {}".format(r.status_code))
```

How and where do I add callback so I can send the training data to my logging server

**Comment by glenn-jocher** [comment]
@effectXS hi,

To add your own custom callbacks for logging during training in YOLOv5 and send the training data to your logging server, you can modify the `utils/loggers/__init__.py` file.

Inside the `on_fit_epoch_end()` method in the `__init__.py` file, you can add your custom callback code after the line `payload = dict(zip(self.keys, vals))`. In your code, you are using the `requests` library to make a POST request to your logging server. You can add your specific server URL and payload data as needed in this section.

Make sure to install the `requests` library if you haven't already by running `pip install requests`.

Please note that this is just a general guidance and you may need to adjust the code according to your specific requirements.

Hope this helps! Let me know if you have any further questions.
