### ISSUE TITLE
Pretrained backbone model

### ISSUE THREAD

**Issue by andualemw1** [ultralytics/yolov5#12185]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I am working on Yolov5, and I have trained the yolov5 backbone (by truncating the model) on another training pipeline. Then, when I try to train using the yolov5 model using the pre-trained backbone model, it returns the following error.

csd = ckpt['model'].float().state_dict()  # checkpoint state_dict as FP32
KeyError: 'model' 
I have also tried to print the keys of the checkpoints, it prints out correctly. 
I would appreciate your help!

odict_keys(['model.0.conv.weight', 'model.0.bn.weight', 'model.0.bn.bias', 'model.0.bn.running_mean', 'model.0.bn.running_var', 'model.0.bn.num_batches_tracked', 'model.1.conv.weight', 'model.1.bn.weight', 'model.1.bn.bias', 'model.1.bn.running_mean', 'model.1.bn.running_var', 'model.1.bn.num_batches_tracked', 'model.2.cv1.conv.weight', 'model.2.cv1.bn.weight', 'model.2.cv1.bn.bias', 'model.2.cv1.bn.running_mean', 'model.2.cv1.bn.running_var', 'model.2.cv1.bn.num_batches_tracked', 'model.2.cv2.conv.weight', 'model.2.cv2.bn.weight', 'model.2.cv2.bn.bias', 'model.2.cv2.bn.running_mean', 'model.2.cv2.bn.running_var', 'model.2.cv2.bn.num_batches_tracked', 'model.2.cv3.conv.weight', 'model.2.cv3.bn.weight', 'model.2.cv3.bn.bias', 'model.2.cv3.bn.running_mean', 'model.2.cv3.bn.running_var', 'model.2.cv3.bn.num_batches_tracked', 'model.2.m.0.cv1.conv.weight', 'model.2.m.0.cv1.bn.weight', 'model.2.m.0.cv1.bn.bias', 'model.2.m.0.cv1.bn.running_mean', 'model.2.m.0.cv1.bn.running_var', 'model.2.m.0.cv1.bn.num_batches_tracked', 'model.2.m.0.cv2.conv.weight', 'model.2.m.0.cv2.bn.weight', 'model.2.m.0.cv2.bn.bias', 'model.2.m.0.cv2.bn.running_mean', 'model.2.m.0.cv2.bn.running_var', 'model.2.m.0.cv2.bn.num_batches_tracked', 'model.2.m.1.cv1.conv.weight', 'model.2.m.1.cv1.bn.weight', 'model.2.m.1.cv1.bn.bias', 'model.2.m.1.cv1.bn.running_mean', 'model.2.m.1.cv1.bn.running_var', 'model.2.m.1.cv1.bn.num_batches_tracked', 'model.2.m.1.cv2.conv.weight', 'model.2.m.1.cv2.bn.weight', 'model.2.m.1.cv2.bn.bias', 'model.2.m.1.cv2.bn.running_mean', 'model.2.m.1.cv2.bn.running_var', 'model.2.m.1.cv2.bn.num_batches_tracked', 'model.3.conv.weight', 'model.3.bn.weight', 'model.3.bn.bias', 'model.3.bn.running_mean', 'model.3.bn.running_var', 'model.3.bn.num_batches_tracked', 'model.4.cv1.conv.weight', 'model.4.cv1.bn.weight', 'model.4.cv1.bn.bias', 'model.4.cv1.bn.running_mean', 'model.4.cv1.bn.running_var', 'model.4.cv1.bn.num_batches_tracked', 'model.4.cv2.conv.weight', 'model.4.cv2.bn.weight', 'model.4.cv2.bn.bias', 'model.4.cv2.bn.running_mean', 'model.4.cv2.bn.running_var', 'model.4.cv2.bn.num_batches_tracked', 'model.4.cv3.conv.weight', 'model.4.cv3.bn.weight', 'model.4.cv3.bn.bias', 'model.4.cv3.bn.running_mean', 'model.4.cv3.bn.running_var', 'model.4.cv3.bn.num_batches_tracked', 'model.4.m.0.cv1.conv.weight', 'model.4.m.0.cv1.bn.weight', 'model.4.m.0.cv1.bn.bias', 'model.4.m.0.cv1.bn.running_mean', 'model.4.m.0.cv1.bn.running_var', 'model.4.m.0.cv1.bn.num_batches_tracked', 'model.4.m.0.cv2.conv.weight', 'model.4.m.0.cv2.bn.weight', 'model.4.m.0.cv2.bn.bias', 'model.4.m.0.cv2.bn.running_mean', 'model.4.m.0.cv2.bn.running_var', 'model.4.m.0.cv2.bn.num_batches_tracked', 'model.4.m.1.cv1.conv.weight', 'model.4.m.1.cv1.bn.weight', 'model.4.m.1.cv1.bn.bias', 'model.4.m.1.cv1.bn.running_mean', 'model.4.m.1.cv1.bn.running_var', 'model.4.m.1.cv1.bn.num_batches_tracked', 'model.4.m.1.cv2.conv.weight', 'model.4.m.1.cv2.bn.weight', 'model.4.m.1.cv2.bn.bias', 'model.4.m.1.cv2.bn.running_mean', 'model.4.m.1.cv2.bn.running_var', 'model.4.m.1.cv2.bn.num_batches_tracked', 'model.4.m.2.cv1.conv.weight', 'model.4.m.2.cv1.bn.weight', 'model.4.m.2.cv1.bn.bias', 'model.4.m.2.cv1.bn.running_mean', 'model.4.m.2.cv1.bn.running_var', 'model.4.m.2.cv1.bn.num_batches_tracked', 'model.4.m.2.cv2.conv.weight', 'model.4.m.2.cv2.bn.weight', 'model.4.m.2.cv2.bn.bias', 'model.4.m.2.cv2.bn.running_mean', 'model.4.m.2.cv2.bn.running_var', 'model.4.m.2.cv2.bn.num_batches_tracked', 'model.4.m.3.cv1.conv.weight', 'model.4.m.3.cv1.bn.weight', 'model.4.m.3.cv1.bn.bias', 'model.4.m.3.cv1.bn.running_mean', 'model.4.m.3.cv1.bn.running_var', 'model.4.m.3.cv1.bn.num_batches_tracked', 'model.4.m.3.cv2.conv.weight', 'model.4.m.3.cv2.bn.weight', 'model.4.m.3.cv2.bn.bias', 'model.4.m.3.cv2.bn.running_mean', 'model.4.m.3.cv2.bn.running_var', 'model.4.m.3.cv2.bn.num_batches_tracked', 'model.5.conv.weight', 'model.5.bn.weight', 'model.5.bn.bias', 'model.5.bn.running_mean', 'model.5.bn.running_var', 'model.5.bn.num_batches_tracked', 'model.6.cv1.conv.weight', 'model.6.cv1.bn.weight', 'model.6.cv1.bn.bias', 'model.6.cv1.bn.running_mean', 'model.6.cv1.bn.running_var', 'model.6.cv1.bn.num_batches_tracked', 'model.6.cv2.conv.weight', 'model.6.cv2.bn.weight', 'model.6.cv2.bn.bias', 'model.6.cv2.bn.running_mean', 'model.6.cv2.bn.running_var', 'model.6.cv2.bn.num_batches_tracked', 'model.6.cv3.conv.weight', 'model.6.cv3.bn.weight', 'model.6.cv3.bn.bias', 'model.6.cv3.bn.running_mean', 'model.6.cv3.bn.running_var', 'model.6.cv3.bn.num_batches_tracked', 'model.6.m.0.cv1.conv.weight', 'model.6.m.0.cv1.bn.weight', 'model.6.m.0.cv1.bn.bias', 'model.6.m.0.cv1.bn.running_mean', 'model.6.m.0.cv1.bn.running_var', 'model.6.m.0.cv1.bn.num_batches_tracked', 'model.6.m.0.cv2.conv.weight', 'model.6.m.0.cv2.bn.weight', 'model.6.m.0.cv2.bn.bias', 'model.6.m.0.cv2.bn.running_mean', 'model.6.m.0.cv2.bn.running_var', 'model.6.m.0.cv2.bn.num_batches_tracked', 'model.6.m.1.cv1.conv.weight', 'model.6.m.1.cv1.bn.weight', 'model.6.m.1.cv1.bn.bias', 'model.6.m.1.cv1.bn.running_mean', 'model.6.m.1.cv1.bn.running_var', 'model.6.m.1.cv1.bn.num_batches_tracked', 'model.6.m.1.cv2.conv.weight', 'model.6.m.1.cv2.bn.weight', 'model.6.m.1.cv2.bn.bias', 'model.6.m.1.cv2.bn.running_mean', 'model.6.m.1.cv2.bn.running_var', 'model.6.m.1.cv2.bn.num_batches_tracked', 'model.6.m.2.cv1.conv.weight', 'model.6.m.2.cv1.bn.weight', 'model.6.m.2.cv1.bn.bias', 'model.6.m.2.cv1.bn.running_mean', 'model.6.m.2.cv1.bn.running_var', 'model.6.m.2.cv1.bn.num_batches_tracked', 'model.6.m.2.cv2.conv.weight', 'model.6.m.2.cv2.bn.weight', 'model.6.m.2.cv2.bn.bias', 'model.6.m.2.cv2.bn.running_mean', 'model.6.m.2.cv2.bn.running_var', 'model.6.m.2.cv2.bn.num_batches_tracked', 'model.6.m.3.cv1.conv.weight', 'model.6.m.3.cv1.bn.weight', 'model.6.m.3.cv1.bn.bias', 'model.6.m.3.cv1.bn.running_mean', 'model.6.m.3.cv1.bn.running_var', 'model.6.m.3.cv1.bn.num_batches_tracked', 'model.6.m.3.cv2.conv.weight', 'model.6.m.3.cv2.bn.weight', 'model.6.m.3.cv2.bn.bias', 'model.6.m.3.cv2.bn.running_mean', 'model.6.m.3.cv2.bn.running_var', 'model.6.m.3.cv2.bn.num_batches_tracked', 'model.6.m.4.cv1.conv.weight', 'model.6.m.4.cv1.bn.weight', 'model.6.m.4.cv1.bn.bias', 'model.6.m.4.cv1.bn.running_mean', 'model.6.m.4.cv1.bn.running_var', 'model.6.m.4.cv1.bn.num_batches_tracked', 'model.6.m.4.cv2.conv.weight', 'model.6.m.4.cv2.bn.weight', 'model.6.m.4.cv2.bn.bias', 'model.6.m.4.cv2.bn.running_mean', 'model.6.m.4.cv2.bn.running_var', 'model.6.m.4.cv2.bn.num_batches_tracked', 'model.6.m.5.cv1.conv.weight', 'model.6.m.5.cv1.bn.weight', 'model.6.m.5.cv1.bn.bias', 'model.6.m.5.cv1.bn.running_mean', 'model.6.m.5.cv1.bn.running_var', 'model.6.m.5.cv1.bn.num_batches_tracked', 'model.6.m.5.cv2.conv.weight', 'model.6.m.5.cv2.bn.weight', 'model.6.m.5.cv2.bn.bias', 'model.6.m.5.cv2.bn.running_mean', 'model.6.m.5.cv2.bn.running_var', 'model.6.m.5.cv2.bn.num_batches_tracked', 'model.7.conv.weight', 'model.7.bn.weight', 'model.7.bn.bias', 'model.7.bn.running_mean', 'model.7.bn.running_var', 'model.7.bn.num_batches_tracked', 'model.8.cv1.conv.weight', 'model.8.cv1.bn.weight', 'model.8.cv1.bn.bias', 'model.8.cv1.bn.running_mean', 'model.8.cv1.bn.running_var', 'model.8.cv1.bn.num_batches_tracked', 'model.8.cv2.conv.weight', 'model.8.cv2.bn.weight', 'model.8.cv2.bn.bias', 'model.8.cv2.bn.running_mean', 'model.8.cv2.bn.running_var', 'model.8.cv2.bn.num_batches_tracked', 'model.8.cv3.conv.weight', 'model.8.cv3.bn.weight', 'model.8.cv3.bn.bias', 'model.8.cv3.bn.running_mean', 'model.8.cv3.bn.running_var', 'model.8.cv3.bn.num_batches_tracked', 'model.8.m.0.cv1.conv.weight', 'model.8.m.0.cv1.bn.weight', 'model.8.m.0.cv1.bn.bias', 'model.8.m.0.cv1.bn.running_mean', 'model.8.m.0.cv1.bn.running_var', 'model.8.m.0.cv1.bn.num_batches_tracked', 'model.8.m.0.cv2.conv.weight', 'model.8.m.0.cv2.bn.weight', 'model.8.m.0.cv2.bn.bias', 'model.8.m.0.cv2.bn.running_mean', 'model.8.m.0.cv2.bn.running_var', 'model.8.m.0.cv2.bn.num_batches_tracked', 'model.8.m.1.cv1.conv.weight', 'model.8.m.1.cv1.bn.weight', 'model.8.m.1.cv1.bn.bias', 'model.8.m.1.cv1.bn.running_mean', 'model.8.m.1.cv1.bn.running_var', 'model.8.m.1.cv1.bn.num_batches_tracked', 'model.8.m.1.cv2.conv.weight', 'model.8.m.1.cv2.bn.weight', 'model.8.m.1.cv2.bn.bias', 'model.8.m.1.cv2.bn.running_mean', 'model.8.m.1.cv2.bn.running_var', 'model.8.m.1.cv2.bn.num_batches_tracked', 'model.9.cv1.conv.weight', 'model.9.cv1.bn.weight', 'model.9.cv1.bn.bias', 'model.9.cv1.bn.running_mean', 'model.9.cv1.bn.running_var', 'model.9.cv1.bn.num_batches_tracked', 'model.9.cv2.conv.weight', 'model.9.cv2.bn.weight', 'model.9.cv2.bn.bias', 'model.9.cv2.bn.running_mean', 'model.9.cv2.bn.running_var', 'model.9.cv2.bn.num_batches_tracked'])

**Comment by glenn-jocher** [comment]
@andualemw1 it looks like you're trying to use a pre-trained backbone model for YOLOv5, and it's resulting in a 'KeyError: 'model''. The error may be occurring due to a mismatch between the expected keys in your checkpoint and the keys in the YOLOv5 model. 

You may need to adjust the keys in your checkpoint to match those expected by YOLOv5. Double-check the keys in your checkpoint and ensure they align with the model's expected keys.

Let me know if you need further assistance!
