### ISSUE TITLE
YOLOv5 Semi-supervised learning

### ISSUE THREAD

**Issue by klock18** [ultralytics/yolov5#1218]
Hi!

I want to try and implement STAC (https://arxiv.org/abs/2005.04757) using YOLOv5. Can anyone suggest where I should add in the unsupervised loss in the YOLOv5 src for semi-supervised learning? Just having trouble getting started with this.

Thanks!

**Comment by glenn-jocher** [comment]
@klock18 losses are located in compute_loss():
https://github.com/ultralytics/yolov5/blob/453acdec67202e15b772370d31eb196d844f2892/utils/general.py#L480

**Comment by klock18** [comment]
Awesome, thanks Glenn!

**Comment by lleye** [comment]
@klock18 were you able to implement STAC in yolo?

**Comment by Zephyr69** [comment]
Sir, did you manage STAC eventually?

**Comment by PRoios** [comment]
Hey there,
Anything to share?

**Comment by glenn-jocher** [comment]
@PRoios i'm glad to help! If you have any questions about implementing STAC or any other aspect of YOLOv5, feel free to ask. Good luck with your project!
