### ISSUE TITLE
'RecursiveScriptModule' object has no attribute 'get'

### ISSUE THREAD

**Issue by KonstiDE** [ultralytics/yolov5#12188]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Export

### Bug

Hello, I convert a yolov5 model via mm-deploy like the following:

```python
config_path = 'yolov5_base.py'
model_path = 'epoch_500.pth'

register_all_modules()

model = init_detector(
    config=config_path,
    checkpoint=model_path,
    device='cpu'
).cpu()
model = model.eval()

example = torch.rand(1, 3, 512, 512).cpu()

traced_script_module = torch.jit.trace(model, example, strict=False)
optimized_traced_model = optimize_for_mobile(traced_script_module)
optimized_traced_model._save_for_lite_interpreter("traced_yolo.pt")
```

Works like a charm. However, I want to use it in the Flutter package pytorch_lite and they say to export the model via te export.py file in the yolov5 Github Repo, so I use the Colab environment of it and run:

`!python export.py --weights traced_yolo.pt` --include torchscript --img 512--optimize`

My model for producing a minimal example can be found [here](https://we.tl/t-BVSUA5P7NG).

The final error is:

`
Traceback (most recent call last):
  File "/content/yolov5/export.py", line 863, in <module>
    main(opt)
  File "/content/yolov5/export.py", line 858, in main
    run(**vars(opt))
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/yolov5/export.py", line 736, in run
    model = attempt_load(weights, device=device, inplace=True, fuse=True)  # load FP32 model
  File "/content/yolov5/models/experimental.py", line 80, in attempt_load
    ckpt = (ckpt.get('ema') or ckpt['model']).to(device).float()  # FP32 model
  File "/usr/local/lib/python3.10/dist-packages/torch/jit/_script.py", line 784, in __getattr__
    return super().__getattr__(attr)
  File "/usr/local/lib/python3.10/dist-packages/torch/jit/_script.py", line 501, in __getattr__
    return super().__getattr__(attr)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'RecursiveScriptModule' object has no attribute 'get'
`

Is there anything wrong with the workflow itself? What does the error indicate? A close ticket is #7269 but it did not rly got solved with a solution.

### Environment

- YOLO Colab enviroment
- OS: Windows 10
- Python 3.8 for the mmdeploy transfer

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@KonstiDE this issue seems to be related to using YOLOv5 with mm-deploy and exporting the model via the `export.py` script.

The error message indicates that the `RecursiveScriptModule` object does not have the attribute `get`. This issue has been reported before (#7269), but it seems that a solution hasn't been found yet.

To troubleshoot this issue, I recommend checking the compatibility between YOLOv5 and mm-deploy, ensuring that they are using compatible versions of PyTorch and other dependencies. Additionally, you can try exporting the model without the `--optimize` flag to see if that resolves the issue.

If the issue persists, I encourage you to submit a bug report with the necessary details, including the steps to reproduce the error and any error logs or traceback messages. This will help the YOLOv5 community and the Ultralytics team investigate and address the issue.

Thank you for your understanding and your willingness to contribute!

**Comment by KonstiDE** [comment]
Unfortunately, removing the `--optimize` flag is not resolving the issue. I will play around a bit and update the ticket accordingly.

**Comment by KonstiDE** [comment]
UPDATE:
I still get the same error without deploying the net with mm-deploy, but just loading in a torch model by default:

```python
enet = ENet(in_channels=3, num_classes=1)
enet.eval()

torch_loaded = torch.load("epoch=188-step=74655.ckpt", map_location="cpu")
torch_state_dict = torch_loaded["state_dict"]

for key in list(torch_state_dict.keys()):
    torch_state_dict[key.replace("model.", "")] = torch_state_dict.pop(key)

enet.load_state_dict(torch_loaded["state_dict"])

example = torch.rand(1, 3, 224, 224).cpu()

out = enet(example)
print(out)

traced_script_module = torch.jit.trace(enet, example)

print(traced_script_module)

traced_script_module.save("traced_enet.pt")
```

**Comment by glenn-jocher** [comment]
@KonstiDE i understand that removing the `--optimize` flag did not resolve the issue. Thank you for letting us know. Please feel free to experiment further and update the ticket with any new findings or details. We appreciate your contribution to troubleshooting the problem.
