### ISSUE TITLE
colors class (still in plots.py but also in ultralytics.utils.plotting)

### ISSUE THREAD

**Issue by barney2074** [ultralytics/yolov5#12190]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

Hello

I could be missing something- but to customise the detection bbox colors, I used to edit the hex values in plots.py
It seems that the colors class is now in ultralytics.utils.plotting (so editing plots.py does not work)

I have not played around with it i.e modifying detect.py to use the old class, or not sure if this will break something else.

It would be great if these kinds of settings could be located in an external config file
i.e class 1 = color 1 
In the meantime is the easiest way to customise the colors ??

thank you

Andrew

### Environment

Ubuntu 20.04
Python 3.10.12
Yolov5 v7.0

### Minimal Reproducible Example

n/a

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@barney2074 hi Andrew,

Thank you for reaching out and bringing this to our attention. The colors class has indeed been moved to `ultralytics.utils.plotting` in the latest version of YOLOv5.

To customize the detection bbox colors, you can modify the `colors` class in `ultralytics.utils.plotting`. Be careful to only modify the hex values and not the class indices.

While we don't currently have a feature that allows these settings to be located in an external config file, it's a great suggestion and we appreciate your feedback. 

If you decide to modify `detect.py` to use the old class, please be cautious as it may affect other aspects of the code.

We appreciate your understanding and support. Let us know if you have any further questions.

Best, 
Glenn

**Comment by barney2074** [comment]
thanks @glenn-jocher 

I would submit a PR- but don't really have the python skills to do it

Andrew

**Comment by glenn-jocher** [comment]
Hi @barney2074,

No worries at all, Andrew! Submitting a PR can indeed be a bit daunting, especially if you're not familiar with Python. Your participation and engagement are still valuable and appreciated, even without a PR.

If you have any other questions or need further assistance with customizing the colors or any other aspect of YOLOv5, please feel free to ask. We're here to help!

Thanks for your support,

Glenn
