### ISSUE TITLE
--save-txt data format when launching  segment/predict.py

### ISSUE THREAD

**Issue by jorgrde1** [ultralytics/yolov5#12199]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello there!
Im using Yolov5 with a segmentation model.

python segment/predict.py --weights /image_static/weights/best_yolov5_nano.pt --source /image_static/images/20230628-144945_img16.png --save-txt

When I run the predict.py with the --save-txt flag so I get a txt file with the labels, I guess that there are 1 line per object and then are the x_1, y_1 etc, per object.

My question its my assumption correct? And do you have any script to to get the center of the object with these data or how could I get?

### Additional

labels.txt data
0 0.670313 0.741667 0.66875 0.74375 0.667188 0.74375 0.664062 0.747917 0.664062 0.75 0.6625 0.752083 0.6625 0.76875 0.665625 0.772917 0.66875 0.772917 0.670313 0.775 0.671875 0.775 0.675 0.779167 0.676562 0.779167 0.678125 0.78125 0.701563 0.78125 0.703125 0.779167 0.70625 0.779167 0.70625 0.777083 0.707812 0.775 0.707812 0.770833 0.709375 0.76875 0.710938 0.770833 0.714063 0.770833 0.715625 0.76875 0.721875 0.76875 0.726562 0.7625 0.71875 0.752083 0.717188 0.752083 0.715625 0.75 0.714063 0.75 0.7125 0.747917 0.710938 0.747917 0.707812 0.74375 0.703125 0.74375 0.701563 0.741667
0 0.707812 0.65 0.70625 0.652083 0.70625 0.66875 0.709375 0.672917 0.734375 0.672917 0.739062 0.666667 0.742188 0.666667 0.74375 0.664583 0.748438 0.664583 0.75 0.6625 0.751562 0.6625 0.757812 0.654167 0.757812 0.652083 0.75625 0.652083 0.754687 0.65
0 0.657812 0.758333 0.65625 0.760417 0.65625 0.76875 0.659375 0.772917 0.66875 0.772917 0.670313 0.775 0.671875 0.775 0.675 0.779167 0.676562 0.779167 0.678125 0.78125 0.703125 0.78125 0.704687 0.779167 0.70625 0.779167 0.70625 0.772917 0.709375 0.76875 0.715625 0.76875 0.715625 0.766667 0.717188 0.764583 0.717188 0.760417 0.715625 0.758333 0.707812 0.758333 0.70625 0.760417 0.704687 0.760417 0.703125 0.7625 0.7 0.7625 0.698438 0.764583 0.692187 0.764583 0.690625 0.7625 0.684375 0.7625 0.682813 0.760417 0.679688 0.760417 0.678125 0.758333
0 0.753125 0.45 0.748438 0.45625 0.746875 0.45625 0.745313 0.458333 0.74375 0.458333 0.7375 0.466667 0.7375 0.485417 0.740625 0.489583 0.742188 0.4875 0.745313 0.4875 0.748438 0.483333 0.75 0.483333 0.751562 0.48125 0.759375 0.48125 0.764063 0.475 0.765625 0.475 0.767187 0.472917 0.771875 0.472917 0.773438 0.470833 0.773438 0.46875 0.775 0.466667 0.776563 0.466667 0.778125 0.464583 0.779688 0.464583 0.785937 0.45625 0.785937 0.452083 0.784375 0.45

**Comment by glenn-jocher** [comment]
@jorgrde1 hi there! When you run `predict.py` with the `--save-txt` flag, it will generate a text file with the labels. Each line in the file represents an object, and the values on that line correspond to the coordinates of the object in the image. The format of the coordinates depends on whether you are using normalized coordinates or absolute pixel values.

To calculate the center of the object, you can use the coordinates provided in the text file. For example, if the coordinates are in normalized format, you can calculate the center by taking the average of the x and y coordinates.

I hope this helps! Let us know if you have any further questions or need additional assistance.

**Comment by jorgrde1** [comment]
Hello, thank you I've already tried and it worked fine!

**Comment by glenn-jocher** [comment]
@jorgrde1 great to hear that it worked for you! If you have any further questions or need any assistance, feel free to ask. The YOLOv5 community and the Ultralytics team are here to help.

**Comment by PhucPhamSy** [comment]
> @jorgrde1 hi there! When you run `predict.py` with the `--save-txt` flag, it will generate a text file with the labels. Each line in the file represents an object, and the values on that line correspond to the coordinates of the object in the image. The format of the coordinates depends on whether you are using normalized coordinates or absolute pixel values.
> 
> To calculate the center of the object, you can use the coordinates provided in the text file. For example, if the coordinates are in normalized format, you can calculate the center by taking the average of the x and y coordinates.
> 
> I hope this helps! Let us know if you have any further questions or need additional assistance.

The number of coordinates has to be even, right?  [class id x y x1 y1 x2 y2 ... xn yn].
I predicted YOLOv11 and got the prediction like this [0 0.881382 0.107337 0.881382 0.111413 0.89034 0.111413 0.89034 0.107337 0.272293]
Could you explain about this case?
