### ISSUE TITLE
How to reduce stride when training

### ISSUE THREAD

**Issue by thiennn013** [ultralytics/yolov5#12197]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to reduce the stride to train with small objects but don't know where to change it, the default is currently 32

**Comment by glenn-jocher** [comment]
@thiennn013 to reduce the stride when training with YOLOv5, you can modify the `stride` parameter in the model configuration file. The default stride is set to 32, but you can change it to a smaller value to detect smaller objects.

Please refer to the YOLOv5 model configuration file (`yolov5/models/yolov5s.yaml`, for example) and locate the `strides` parameter under the `backbone` section. Adjust the value of `strides` to your desired stride, and then proceed with training.

Let us know if you have any further questions or need additional assistance.

**Comment by thiennn013** [comment]
Can you give more specific instructions? I don't know what value needs to be changed here to change the stride. Thank you very much

backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [64, 6, 2, 2]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C3, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 6, C3, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, C3, [512]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 3, C3, [1024]],
   [-1, 1, SPPF, [1024, 5]],  # 9
  ]

**Comment by glenn-jocher** [comment]
@thiennn013 in order to change the stride in YOLOv5, you can modify the `strides` values in the backbone configuration.

In the model configuration file, you will find the `backbone` section which contains a list of sub-modules with their respective configurations. Each sub-module is represented by a list of values, where the second value in each sub-module list represents the stride.

To change the stride, locate the sub-modules that have stride values you wish to modify. For example, to change the stride of the first sub-module from 2 to a different value, you can modify the second value in the list from `1` to your desired stride value (e.g., `2`, `4`, etc.).

Here is an example of how you can modify the stride of the first sub-module from 2 to a different value:

```yaml
backbone:
  [[-1, 1, Conv, [64, 6, <desired_stride>, 2]],  # 0-P1/2
   ...
  ]
```

Repeat the same procedure for any other sub-modules that you want to modify.

Please let me know if you have any further questions or need additional assistance.

**Comment by curtis18** [comment]
> @thiennn013 in order to change the stride in YOLOv5, you can modify the `strides` values in the backbone configuration.
> 
> In the model configuration file, you will find the `backbone` section which contains a list of sub-modules with their respective configurations. Each sub-module is represented by a list of values, where the second value in each sub-module list represents the stride.
> 
> To change the stride, locate the sub-modules that have stride values you wish to modify. For example, to change the stride of the first sub-module from 2 to a different value, you can modify the second value in the list from `1` to your desired stride value (e.g., `2`, `4`, etc.).
> 
> Here is an example of how you can modify the stride of the first sub-module from 2 to a different value:
> 
> ```yaml
> backbone:
>   [[-1, 1, Conv, [64, 6, <desired_stride>, 2]],  # 0-P1/2
>    ...
>   ]
> ```
> 
> Repeat the same procedure for any other sub-modules that you want to modify.
> 
> Please let me know if you have any further questions or need additional assistance.

Hello @glenn-jocher If it is yolov8, or yolov10. How to reduce stride? Thank you.

# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]] # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]] # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]] # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]] # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]] # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]] # 9

# YOLOv10x backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]] # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]] # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]] # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, SCDown, [512, 3, 2]] # 5-P4/16
  - [-1, 6, C2fCIB, [512, True]]
  - [-1, 1, SCDown, [1024, 3, 2]] # 7-P5/32
  - [-1, 3, C2fCIB, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]] # 9
  - [-1, 1, PSA, [1024]] # 10

**Comment by glenn-jocher** [comment]
Hello @curtis18, to reduce the stride in YOLOv8 or YOLOv10, modify the stride values in the `Conv` layers within the `backbone` section of the model configuration file. For example, change the stride in the first `Conv` layer from 2 to your desired value:

```yaml
backbone:
  - [-1, 1, Conv, [64, 3, <desired_stride>]] # 0-P1/2
  ...
```

Apply similar changes to other `Conv` layers as needed. Let me know if you need further assistance.

**Comment by curtis18** [comment]
Hello @glenn-jocher Thank you for your reply. You mentioned that the model strides are fixed at 8, 16, 32, what does the stride values 2 in the Conv layers mean? Does stride value 2 here is a key representing 32 strides? value 1 means 16 strides, and 0 means 8 strides?

**Comment by glenn-jocher** [comment]
Hello @curtis18, the stride values in the `Conv` layers directly represent the downsampling factor at each stage. A stride of 2 means the feature map size is halved, while a stride of 1 means no downsampling. The fixed strides of 8, 16, and 32 refer to the cumulative downsampling effect across the network layers. Let me know if you need further clarification.

**Comment by tvvarun** [comment]
Hello @glenn-jocher I have tried all different configuration of the stride values in the yaml backbone definition but only value 2 seems to work. Rest all values I get an error there any other procedure I am supposed to do?
