### ISSUE TITLE
what's the difference between the run result of yolo.py and hubconf.py?

### ISSUE THREAD

**Issue by xinxin342** [ultralytics/yolov5#1219]
## ❔Question
what's the difference between the run result of yolo.py and hubconf.py?

**Comment by glenn-jocher** [comment]
@xinxin342 hubconf.py interfaces with PyTorch Hub to allow for standalone YOLOv5 use, without needing to clone this repo. See PyTorch Hub tutorial:
https://docs.ultralytics.com/yolov5
