### ISSUE TITLE
input size ?

### ISSUE THREAD

**Issue by china56321** [ultralytics/yolov5#122]
I use yolov5x.pt to test images. and the screen shows:
![1](https://user-images.githubusercontent.com/42080579/84999045-38343880-b183-11ea-8155-ebe6183bd3bb.png)
My question :
1.My image size are all not  384x512 or 320x512, what does that mean  of the showed  384x512 or 320x512  ?
2. whether the --img-size  can be set to 640x512 ,or other size (not 640x640)?

Thanks   !

**Comment by glenn-jocher** [comment]
@china56321 use `--img-size` to change

**Comment by china56321** [comment]
> @china56321 use `--img-size` to change
What does that mean of the showed 384x512 or 320x512 ? .The  input size are all not 384x512 or 320x512.

**Comment by glenn-jocher** [comment]
@china56321 these are the inference sizes. The only thing they share in common with the original image sizes is a similar aspect ratio.
