### ISSUE TITLE
issues when exporting to TRT .engine format

### ISSUE THREAD

**Issue by Shaistrong** [ultralytics/yolov5#12202]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

when attempting to use `export.py` it doesn't export anything without showing any errors
![Screenshot 2023-10-05 185641](https://github.com/ultralytics/yolov5/assets/73827899/4bd6cdb6-bbdc-4d0a-93de-4d31c3c7cd18)

### Environment

-latest repo
-CUDA 12.1.1
-latest TRT
-cuDNN 8.9.0

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Shaistrong, thank you for bringing this issue to our attention. We appreciate your effort in troubleshooting the problem.

To better understand the issue you're facing, could you please provide a minimal reproducible example or any additional information? This will help us diagnose the problem accurately and provide you with a solution.

Additionally, could you please confirm if you have followed the steps outlined in the documentation correctly? Before running the `export.py` script, ensure that you have the latest dependencies, such as CUDA, cuDNN, and TensorRT.

We value your contribution, and if you're willing to submit a pull request (PR) with a fix, we would be grateful! However, please note that the YOLOv5 development team is actively working on addressing all reported issues. Your patience is greatly appreciated as we work towards resolving this issue.

Once again, thank you for your support, and we look forward to helping you find a resolution.

**Comment by Shaistrong** [comment]
> @Shaistrong, thank you for bringing this issue to our attention. We appreciate your effort in troubleshooting the problem.
> 
> To better understand the issue you're facing, could you please provide a minimal reproducible example or any additional information? This will help us diagnose the problem accurately and provide you with a solution.
> 
> Additionally, could you please confirm if you have followed the steps outlined in the documentation correctly? Before running the `export.py` script, ensure that you have the latest dependencies, such as CUDA, cuDNN, and TensorRT.
> 
> We value your contribution, and if you're willing to submit a pull request (PR) with a fix, we would be grateful! However, please note that the YOLOv5 development team is actively working on addressing all reported issues. Your patience is greatly appreciated as we work towards resolving this issue.
> 
> Once again, thank you for your support, and we look forward to helping you find a resolution.

hey, like I mentioned in the issue description; I installed all dependencies and have the latest commit of this repository. same issue occurs when attempting to export even the normal `yolov5s.pt` to `.engine` format. it's not an issue with my installation, it must be an issue with the repo

**Comment by glenn-jocher** [comment]
Thank you for providing additional information, @Shaistrong. We apologize for any inconvenience you may be experiencing.

Based on your explanation, it seems that the issue lies within the repository itself rather than your installation. We appreciate your patience and understanding as our development team continues to work towards resolving this issue.

If you have any further information or updates related to this problem, please feel free to add them to the issue. Your contribution is valuable and helps us improve the YOLOv5 repository.

Thank you once again for bringing this to our attention, and we will do our best to assist you in finding a resolution.

**Comment by PaoloGiglioli90** [comment]
Hi @glenn-jocher, sorry for disturbing you, I have the same exact issue, and also some of my friends on their PCs, and we are sure we are doing the right process, also because in the past it was working. Any update about the issue resolution ? Thank you in advance

**Comment by Angelthemagic** [comment]
Just as you said, I also encountered the same problem. I found that after uninstalling ONNX and restarting the compilation, ONNX would be automatically downloaded, and then the export file could be completed normally. However, if I continue to use it, it becomes unresponsive. Therefore, I uninstall ONNX each time before running the command.

**Comment by glenn-jocher** [comment]
Thank you for sharing your experience with the issue, @Angelthemagic. We appreciate your efforts in troubleshooting and finding a potential workaround.

It seems like uninstalling ONNX and then restarting the compilation before running the export command allows you to complete the export successfully. However, if you continue to use it without uninstalling ONNX, it becomes unresponsive.

While this workaround may help you in the short term, we understand that it is not an ideal solution. Our development team is actively working on resolving the issue and we hope to provide a permanent fix soon.

Thank you for your patience and understanding. Your contribution to the YOLOv5 community is greatly appreciated.

**Comment by Shaistrong** [comment]
> Thank you for sharing your experience with the issue, @Angelthemagic. We appreciate your efforts in troubleshooting and finding a potential workaround.
> 
> It seems like uninstalling ONNX and then restarting the compilation before running the export command allows you to complete the export successfully. However, if you continue to use it without uninstalling ONNX, it becomes unresponsive.
> 
> While this workaround may help you in the short term, we understand that it is not an ideal solution. Our development team is actively working on resolving the issue and we hope to provide a permanent fix soon.
> 
> Thank you for your patience and understanding. Your contribution to the YOLOv5 community is greatly appreciated.

I was able to fix it, I forgot to share the solution here. The fix for me was downgrading PyTorch to 2.0.1+cu118 using Conda, the I just reinstall TRT and it worked normally.

**Comment by glenn-jocher** [comment]
Thank you for sharing your solution, @Shaistrong.

We're glad to hear that downgrading PyTorch to version 2.0.1+cu118 using Conda and reinstalling TensorRT resolved the issue for you. It's great to see that you found a workaround that works for your specific setup.

Your contribution in sharing this solution is greatly appreciated by the YOLOv5 community. Thank you for your support and for being an active member.

If you have any further questions or run into any other issues, please don't hesitate to reach out. We're here to help.
