### ISSUE TITLE
AttributeError: 'Detections' object has no attribute 'pandas'

### ISSUE THREAD

**Issue by ammar3010** [ultralytics/yolov5#12218]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

`import torch
model = torch.hub.load('.', 'custom', '/home/aidev/VectraCom/yolov5-crowdhuman/weights/crowdhuman_yolov5m.pt', source='local') 

model.conf = 0.5
model.iou = 0.5

img = 'https://ultralytics.com/images/zidane.jpg'

results = model('https://ultralytics.com/images/zidane.jpg')

results.print()
print(results.xyxy[0])  
print(results.pandas().xyxy[0])
`

Traceback (most recent call last):
  File "hub_detect.py", line 14, in <module>
    print(results.pandas().xyxy[0])
AttributeError: 'Detections' object has no attribute 'pandas'

### Environment

- YOLOv5 custom trained
- Ubuntu: 22.04
- Python: 3.8.18

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ammar3010 hi there,

The `AttributeError` you encountered is due to the fact that the `Detections` object does not have a `.pandas()` attribute. To resolve this issue, you can convert the `Detections` object to a Pandas DataFrame using the `.numpy()` method. Here's an updated version of your code snippet:

```python
import torch
import pandas as pd

model = torch.hub.load('.', 'custom', '/home/aidev/VectraCom/yolov5-crowdhuman/weights/crowdhuman_yolov5m.pt', source='local') 

model.conf = 0.5
model.iou = 0.5

img = 'https://ultralytics.com/images/zidane.jpg'

results = model('https://ultralytics.com/images/zidane.jpg')

results.print()
print(results.xyxy[0])  
print(pd.DataFrame(results.pandas().xyxy[0].numpy()))

```

Please give it a try and let me know if it helps. If you have any further questions or issues, feel free to ask.

Best regards.

**Comment by ammar3010** [comment]
It worked thank you so much.

**Comment by glenn-jocher** [comment]
@ammar3010 you're welcome! I'm glad to hear that it worked for you. If you have any more questions or run into any further issues, don't hesitate to ask. The YOLO community and the Ultralytics team are always here to help.
