### ISSUE TITLE
specify certain classes in val.py

### ISSUE THREAD

**Issue by ryan042923** [ultralytics/yolov5#12215]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I am a beginner in this excellent project and I wanted to ask a question, by using the model you have trained, can I specify certain classes in val.py to calculate their metrics? For example, among the 80 detection targets, I just want val.py to recognize "person" and "car" , then calculate their metrics. Looking forward to your reply very much!

**Comment by glenn-jocher** [comment]
@ryan042923 yes, you can specify certain classes in `val.py` to calculate their metrics. In YOLOv5, you can use the `--save-txt` flag during the validation process to save the predicted labels in a text file. After the validation is complete, you can use the `--exist-ok` flag with `val.py` to view the metrics for specific classes.

For example, to calculate the metrics for the "person" and "car" classes, you can modify `val.py` as follows:
1. Set the `data.yaml` file's `val` section to include only the classes you are interested in, such as:
```
nc: 2
names: ['person', 'car']
```
2. Run `val.py` with the `--save-txt` flag, like this:
```
python val.py --data data.yaml --weights runs/train/exp/weights/best.pt --save-txt
```
3. After the validation is complete, you can use the `--exist-ok` flag to view the metrics for those specific classes, like this:
```
python val.py --data data.yaml --weights runs/train/exp/weights/best.pt --exist-ok
```
This will display the metrics for the "person" and "car" classes only.

I hope this helps! Let me know if you have any further questions.

**Comment by ryan042923** [comment]
Thanks for your reply and detailed answer. I use coco128.yaml, and there is no nc in it, so I can't change 80 to 2. When I followed the second step, it ran as follows:
![1](https://github.com/ultralytics/yolov5/assets/147509271/60d091c1-2a6d-44b6-9d0b-e35999f3b034)
May I ask how to deal with this kind of problem?

**Comment by glenn-jocher** [comment]
Hi @ryan042923, thank you for reaching out and providing additional information.

If you are using the `coco128.yaml` file and it does not contain the `nc` field, you can add it to the file manually to specify the number of classes. You can add it like this:
```
nc: 2
```
After adding the `nc` field with the appropriate value, you can proceed with the steps mentioned in my previous response.

Regarding the error you encountered during the second step, it seems like you are running the command from a different directory. Make sure you navigate to the YOLOv5 repository root directory (`yolov5/`) before running the command.

Please let me know if you have any further questions or need more assistance.

**Comment by ryan042923** [comment]
Thanks for the answer, I will try and give you feedback as soon as possible！

**Comment by glenn-jocher** [comment]
@ryan042923 you're welcome! I'm glad I could help. Please take your time to try it out, and feel free to reach out if you have any further questions or need any assistance. I'll be here to support you. Looking forward to your feedback!

**Comment by ryan042923** [comment]
@glenn-jocher  I'm sorry, I still haven't been able to debug it.
I used the trained model of this project (yolov5s.pt), and found that the nc is 80 in yolov5s.pt. nc: 2 set in the coco128.yaml is inconsistent with that in yolov5s.pt , causing the program to report an error.
If I want to get metrics of specify certain classes, do I need to retrain to get my .pt file instead of using the .pt file you provided?

**Comment by glenn-jocher** [comment]
@ryan042923 I apologize for any confusion. You are correct that the discrepancy in the number of classes between the pre-trained `yolov5s.pt` model (with 80 classes) and the `coco128.yaml` file (with 2 classes) can lead to errors. To calculate metrics for specified classes, retraining the model with your dataset and obtaining a custom `.pt` file is recommended. This will ensure that the model is specifically trained for the classes you are interested in, and the metrics will be accurate for those classes.

If you have any further questions or need assistance during the retraining process, please feel free to ask. I'm here to help!
