### ISSUE TITLE
Training model on pretrained weights produces no weight files or charts

### ISSUE THREAD

**Issue by jasontd92** [ultralytics/yolov5#12229]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When I train my model using pretrained weights (yolov5s.pt), the resulting training directory at runs/train/exp does not contain any charts, data, and the weights directory is empty (no best.pt or last.pt files).

**My command with pretrained weights:** 
`!python3 train.py --data pathToMyModel/yaml/data.yaml --epochs 100 --img 512 --weights yolov5s.pt`

When I train using no pretrained weights or best.pt file, I get all the expected output as described in [Local Logging](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data/#clearml-logging-and-automation-new) (but of course the model performance is less than desirable).

**My command with no pretrained weights:** 
`!python3 train.py --data pathToMyModel/yaml/data.yaml --epochs 100 --img 512`

How can I make my first training run using pretrained weights, and get the correct output so I can work with the resulting best.pt file for future training evolutions?

**Comment by jasontd92** [comment]
Please disregard. I realized the issue was that when it came to downloading the resulting `exp` directory, I was downloading one that did exist, but was not where the most recent results had been saved. Somehow a mostly empty folder containing a couple.yaml files was created that I mistook for the most recent results.

**Comment by glenn-jocher** [comment]
@jasontd92 thank you for the update and clarification! It's great to hear that you were able to identify the issue and resolve it. Sometimes, it can be easy to overlook small details like the location of the saved files. If you have any further questions or need assistance with anything else, please feel free to ask. We're here to help!
