### ISSUE TITLE
I already made model with 10 classes 10 after training by Yolov5. I would like to add new two classes into the made model  10 classes. How can I modify the the made model  10 classes by 12 classes?

### ISSUE THREAD

**Issue by star4s** [ultralytics/yolov5#12226]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have a question about modification of the model.
I already made model with 10 classes 10 after training by Yolov5. I would like to add new two classes into the made model  10 classes. How can I modify the the made model  10 classes by 12 classes?

For example,
10 classes: 1, 2, 3, ... , 9, 10
--->
12  classes: 1, 2, 3, ... , 9, 10, 11, 12

Thank you for your attention.

**Comment by glenn-jocher** [comment]
@star4s hi there,

To modify a YOLOv5 model from 10 classes to 12 classes, you will need to follow these steps:

1. Prepare your new dataset with the additional two classes. Make sure the new classes are properly annotated in your dataset.
2. Add the new classes to the `data.yaml` file in your YOLOv5 directory. Make sure to update the number of classes in the file.
3. Train the model using the updated dataset and `data.yaml` file. You can use the `--weights` flag to initialize the model with the previously trained weights.
4. Once the training is complete, the model should be updated with the additional two classes.

Please note that it's important to properly balance and annotate the new classes to avoid any biases in the model.

Best of luck with your modifications!

Ultralytics YOLOv5 Team

**Comment by star4s** [comment]
Thank you for your Answer.

**Comment by glenn-jocher** [comment]
@star4s you're welcome! If you have any further questions or need assistance with anything else, feel free to ask. Happy coding!

Ultralytics YOLOv5 Team

**Comment by star4s** [comment]
@glenn-jocher I followed your instruction. But, I met some error.

Traceback (most recent call last):
  File "train.py", line 645, in <module>
    main(opt)
  File "train.py", line 542, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 203, in train
    ema.ema.load_state_dict(ckpt['ema'].float().state_dict())
  File "/data001/dlpusers/hoonwoo.lee/.conda/envs/yolo/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1483, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Model:
	size mismatch for model.33.m.0.weight: copying a param with shape torch.Size([51, 320, 1, 1]) from checkpoint, the shape in current model is torch.Size([54, 320, 1, 1]).
	size mismatch for model.33.m.0.bias: copying a param with shape torch.Size([51]) from checkpoint, the shape in current model is torch.Size([54]).
	size mismatch for model.33.m.1.weight: copying a param with shape torch.Size([51, 640, 1, 1]) from checkpoint, the shape in current model is torch.Size([54, 640, 1, 1]).
	size mismatch for model.33.m.1.bias: copying a param with shape torch.Size([51]) from checkpoint, the shape in current model is torch.Size([54]).
	size mismatch for model.33.m.2.weight: copying a param with shape torch.Size([51, 960, 1, 1]) from checkpoint, the shape in current model is torch.Size([54, 960, 1, 1]).
	size mismatch for model.33.m.2.bias: copying a param with shape torch.Size([51]) from checkpoint, the shape in current model is torch.Size([54]).
	size mismatch for model.33.m.3.weight: copying a param with shape torch.Size([51, 1280, 1, 1]) from checkpoint, the shape in current model is torch.Size([54, 1280, 1, 1]).
	size mismatch for model.33.m.3.bias: copying a param with shape torch.Size([51]) from checkpoint, the shape in current model is torch.Size([54]).

**Comment by glenn-jocher** [comment]
@star4s hi there,

It looks like you're experiencing a size mismatch error when trying to load the state_dict of your model. The error message specifically mentions a mismatch in the shape of certain parameters.

This error typically occurs when there is a difference in the model architecture between the checkpoint you're trying to load and your current model. It's possible that the checkpoint you're using was trained with a different model configuration, such as a different number of classes.

To resolve this issue, you'll need to ensure that the checkpoint you're using is compatible with your current model architecture. Make sure that the number of classes in the checkpoint matches the number of classes in your current model. If they don't match, you'll need to either train a new model from scratch or find a compatible checkpoint that aligns with your desired number of classes.

If you require further assistance, please provide more details about your training process and any other relevant information that might help us understand the issue better.

Keep up the great work!

Glenn Jocher
Ultralytics YOLOv5 Team
