### ISSUE TITLE
Logging Yolov5 training metrics to sagemaker experiments

### ISSUE THREAD

**Issue by santoshmedisetty321** [ultralytics/yolov5#12233]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I am trying to log my yolov5 training metrics in sagemaker experiments instead of W&B and I am unable to do it. Can someone point me to a working solution example or if the question is already raised? I defined the metrics I want to log like below but it is not. working. Do I need to configure anything extra? Please help

metric_definitions = [
    {'Name': 'box_loss', 'Regex': 'box_loss\s+([\d\.e\-]+)'},
    {'Name': 'obj_loss', 'Regex': 'obj_loss\s+([\d\.e\-]+)'},
    {'Name': 'cls_loss', 'Regex': 'cls_loss\s+([\d\.e\-]+)'},
    {'Name': 'P', 'Regex': 'P\s+([\d\.]+)'},
    {'Name': 'R', 'Regex': 'R\s+([\d\.]+)'},
    {'Name': 'mAP50', 'Regex': 'mAP50\s+([\d\.]+)'},
    {'Name': 'mAP50-95', 'Regex': 'mAP50-95\s+([\d\.]+)'}
]

estimator = Estimator(
    image_uri=container,
    role=role,
    instance_count=1,
    instance_type='ml.m4.2xlarge',
    # instance_type='local',
    input_mode='File',
    output_path=outpath,
    base_job_name='yolov5-training-job',
    sagemaker_session=sagemaker_session,
    enable_sagemaker_metrics=True,
    experiment_config={
        "ExperimentName": experiment.experiment_name,
        "TrialName": trial.trial_name,
        "TrialComponentDisplayName": "Training",
    },
    metric_definitions=metric_definitions
)

train_args = estimator.fit(inputs, job_name=yolov5_training_job_name)

**Comment by glenn-jocher** [comment]
@santoshmedisetty321 hi,

To log YOLOv5 training metrics to SageMaker Experiments instead of W&B, you can use the `log_metric()` method provided by the SageMaker Training Toolkit.

Here's an example of how you can modify your code to log the desired metrics:

```python
from sagemaker.debugger import Rule, rule_configs

# Define the metric definitions
metric_definitions = [
    {'Name': 'box_loss', 'Regex': 'box_loss\s+([\d\.e\-]+)'},
    {'Name': 'obj_loss', 'Regex': 'obj_loss\s+([\d\.e\-]+)'},
    {'Name': 'cls_loss', 'Regex': 'cls_loss\s+([\d\.e\-]+)'},
    {'Name': 'P', 'Regex': 'P\s+([\d\.]+)'},
    {'Name': 'R', 'Regex': 'R\s+([\d\.]+)'},
    {'Name': 'mAP50', 'Regex': 'mAP50\s+([\d\.]+)'},
    {'Name': 'mAP50-95', 'Regex': 'mAP50-95\s+([\d\.]+)'}
]

estimator = Estimator(
    image_uri=container,
    role=role,
    instance_count=1,
    instance_type='ml.m4.2xlarge',
    # instance_type='local',
    input_mode='File',
    output_path=outpath,
    base_job_name='yolov5-training-job',
    sagemaker_session=sagemaker_session,
    enable_sagemaker_metrics=True,
    rules=[
        Rule.sagemaker(rule_configs.create_ground_truth_labels())
    ],
    metric_definitions=metric_definitions
)

# Add the logging code to your train_args
train_args = estimator.fit(inputs, job_name=yolov5_training_job_name)

# Log the metrics
sagemaker_session.logs_for_job(train_args.job_name, wait=True)
```

Make sure to check the documentation on [SageMaker Training Toolkit Logging](https://docs.aws.amazon.com/sagemaker/latest/dg/training-metrics.html) for more details on how to work with SageMaker Experiments.

I hope this helps! Let me know if you have any further questions.
