### ISSUE TITLE
WARNING ⚠️ NMS time limit 2.100s exceeded

### ISSUE THREAD

**Issue by sanjanak-rbg** [ultralytics/yolov5#12238]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Validation

### Bug

 3/15      4.89G     0.5933     0.5576       1.16         66        640: 100%|██████████| 47429/47429 [2:18:29<00:00,  5.71it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):  71%|███████   | 2105/2968 [06:00<06:03,  2.37it/s]WARNING ⚠️ NMS time limit 2.100s exceeded
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):  71%|███████   | 2108/2968 [27:17<72:53:17, 305.11s/it]WARNING ⚠️ NMS time limit 2.100s exceeded
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):  71%|███████   | 2109/2968 [3:38:58<871:14:46, 3651.32s/it]^C

### Environment

yolov8,cuda gpu

### Additional

please help me resolve this

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@sanjanak-rbg hi there! Thank you for reaching out. 

The warning message you encountered, "WARNING ⚠️ NMS time limit 2.100s exceeded," indicates that the Non-Maximum Suppression (NMS) algorithm is taking longer than the specified time limit to execute. This can occur when the number of bounding box predictions is very high or the NMS algorithm implementation is slow.

To address this, you have a few options:

1. Use a smaller image size during validation. By reducing the image size, you can decrease the number of bounding box predictions and potentially reduce the execution time of the NMS algorithm.

2. Adjust the NMS time limit. You can increase the time limit for NMS by modifying the code.

3. Improve the efficiency of the NMS algorithm implementation. If you are comfortable with modifying the YOLOv5 code, you can explore optimizing the NMS algorithm for your specific hardware or use a more efficient NMS algorithm implementation.

Please note that these options might have trade-offs in terms of accuracy or execution time. Additionally, sharing more details, such as your dataset characteristics and hardware configuration, can help the community provide more specific suggestions.

Thanks for your contribution and for being part of the YOLOv5 community! Let us know if you have any further questions or need additional assistance.

**Comment by twilson1111** [comment]
I am seeing the same issue with my M2 macbook air.  Additionally, it coincides with my 'mps' training not converging (ie: loss not decreasing), whereas 'cpu' training does converge.

**Comment by glenn-jocher** [comment]
@twilson1111 hey there! 😊 It sounds like you’re experiencing a couple of challenges with training on your M2 MacBook Air.

For the NMS time limit warning and the non-converging issue on 'mps' (Metal Performance Shaders), this is likely related to the differences in computing capabilities and optimizations between 'mps' and 'cpu'. Metal tends to work differently with parallel computations compared to CPU, which might explain the convergence issue.

A quick suggestion for the convergence problem: try adjusting your learning rate or batch size when training with 'mps'. Sometimes, slight tweaks here can significantly impact training dynamics.

For the NMS time limit exceeded warning, it's generally a performance warning rather than an error that would stop your training. If it doesn't significantly impact your training time or outcomes, it might be okay to proceed as is.

Remember, training on GPU/Metal often requires different hyperparameters tuning compared to CPU to achieve optimal results.

Let me know if these suggestions help or if you have more queries!

**Comment by twilson1111** [comment]
> @twilson1111 hey there! 😊 It sounds like you’re experiencing a couple of challenges with training on your M2 MacBook Air.
> 
> For the NMS time limit warning and the non-converging issue on 'mps' (Metal Performance Shaders), this is likely related to the differences in computing capabilities and optimizations between 'mps' and 'cpu'. Metal tends to work differently with parallel computations compared to CPU, which might explain the convergence issue.
> 
> A quick suggestion for the convergence problem: try adjusting your learning rate or batch size when training with 'mps'. Sometimes, slight tweaks here can significantly impact training dynamics.
> 
> For the NMS time limit exceeded warning, it's generally a performance warning rather than an error that would stop your training. If it doesn't significantly impact your training time or outcomes, it might be okay to proceed as is.
> 
> Remember, training on GPU/Metal often requires different hyperparameters tuning compared to CPU to achieve optimal results.
> 
> Let me know if these suggestions help or if you have more queries!

Hi Glenn,

Thank you for your assistance.  I have tried different batch sizes but haven't had much luck - although with my hardware (a new Macbook air) I cannot go past 16 without everything getting too slow.  With regards to learning rates, would it be possible for you and Ultralytics to come up with a suggestion for which learning rate/optimizer to use, or in which direction?  The reason I ask is, the optimizer for my dataset is automatic which is overriding any learning rate change I make, and there are a bunch of optimizers so if I go manual, it's hard to know where to start.  
Thank you for trying to help.  I do think it's quite unfortunate that 'mps' just doesn't converge, given that I have a newer model M GPU, and that we don't have much to point towards other than nebulous 'accuracy' concerns.  I wonder if you could help point us unfortunate mac users in a more concrete direction for getting the ultralytics library to work?  I know that the various 'mps' Ultralytics issues documented online have been going on for > 1 year, so it's concerning regarding whether this is actually a supported platform or on its way out.  There seem to be several areas where the Apple ecosystem is becoming less compatible with cross-platform AI libraries.

Update - I have gotten some results from changing optimizer to "Adam" and reducing the Lr0 by a factor of 4x from where the auto-optimizer had it (0.00025).  This allows the system to move in the right direction using 'mps' in a noticable way over the first 10 epochs.

**Comment by glenn-jocher** [comment]
Hi @twilson1111,

Great to hear you've made progress with Adam optimizer and adjusting the learning rate! 👍 It's a step in the right direction. The challenges with 'mps' on Mac hardware, especially with convergence, are indeed tricky. The specific nuances of Metal's compute model, combined with YOLOv5's architecture and your unique dataset, can make finding the perfect training configuration a bit of an art form.

Given your situation, starting with Adam was a good choice, as it's known for being well-suited to a wide range of problems. The learning rate adjustment sounds like it was effective, too. For further tuning, consider experimenting with the weight decay and the learning rate scheduler. These can also significantly impact model convergence and performance.

It's worth noting that YOLOv5 and other AI libraries do face challenges in ensuring seamless compatibility across the rapidly evolving hardware landscape, including Apple's M-series chips. We're always working to improve support and optimize performance across all platforms, including 'mps'. Your feedback and contributions from the community are invaluable as we navigate these complexities together.

Remember, experimentation is key. Small adjustments can sometimes yield surprising improvements. If you hit another roadblock, feel free to share your findings and questions. We're here to help!

Best of luck with your continued training, and thanks for being a proactive part of the YOLOv5 community!

**Comment by ErfanAlaeii** [comment]
Code Optimization: Review the relevant code and improve the parts that can be optimized. Using more optimal algorithms and reducing time complexity can be useful.

Increasing system resources: Increasing computing resources such as CPU and RAM can help improve the speed of operations.

**Comment by glenn-jocher** [comment]
Hi there!

For code optimization in YOLOv5, focusing on algorithm efficiency and reducing time complexity is indeed a great approach. You might consider profiling your code to identify bottlenecks and then optimize those specific areas. For example, optimizing loop structures or leveraging more efficient data handling can yield significant improvements.

Regarding system resources, increasing CPU and RAM can definitely help, especially when dealing with large datasets or when you're aiming to decrease training times. If feasible, upgrading your hardware or using a more powerful server could provide the boost you need.

Keep experimenting and profiling to find the best balance for your specific use case! 😊 If you have specific sections of code you're concerned about, feel free to share, and we can look into those together.

**Comment by eripe970** [comment]
> Adjust the NMS time limit. You can increase the time limit for NMS by modifying the code.

Maybe this could be a parameter to the training command?

**Comment by glenn-jocher** [comment]
Hi @eripe970,

That's a great suggestion! 🎉 Making the NMS time limit configurable via a parameter in the training command could provide more flexibility for users. We'll consider this for future updates. In the meantime, you can manually adjust the NMS time limit in the code to better suit your needs.

Thanks for your input and for being an active part of the YOLOv5 community! 😊

**Comment by shanalikhan** [comment]
> In the meantime, you can manually adjust the NMS time limit in the code to better suit your needs.

How to set this manually in latest code base? @glenn-jocher 

I'm getting the same error in training - using M3 `mps`

<img width="1238" alt="image" src="https://github.com/user-attachments/assets/6f3e9960-5546-4331-a687-9d0d501e503f">

**Comment by fmendez89** [comment]
> > In the meantime, you can manually adjust the NMS time limit in the code to better suit your needs.
> 
> How to set this manually in latest code base? @glenn-jocher
> 
> I'm getting the same error in training - using M3 `mps`
> 
> <img alt="image" width="1238" src="https://private-user-images.githubusercontent.com/8774556/377075935-6f3e9960-5546-4331-a687-9d0d501e503f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NTI5OTQsIm5iZiI6MTcyOTg1MjY5NCwicGF0aCI6Ii84Nzc0NTU2LzM3NzA3NTkzNS02ZjNlOTk2MC01NTQ2LTQzMzEtYTY4Ny05ZDBkNTAxZTUwM2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjVUMTAzODE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzY1YzcxYTUxZjIzNmQ3ZTdiOTc3NDI4ODdkMmNhODJjOTZiZjZkMjcyYjFhYTAwZjJiZDJkMDk3YzY3YjEwMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.C6axCrKCP-3jV6oM5v0N4AM-x5odPctbVi1I6DFcuZU">

Hi @shanalikhan 
did you find the solution to the warning? i'm using the same specs.

**Comment by shanalikhan** [comment]
@fmendez89 
I have fixed it by this way

```
ultralytics/utils/ops.py
```

Inside `non_max_suppression` function change

```
time_limit = 2.0 + max_time_img * bs
```

to 

```
time_limit = 60 + max_time_img * bs
```

60 worked for me, tried from 5, 10 so you need to change accordingly.
Restart the Notebook kernal if you are using the notebook

**Comment by Kickflipkid687** [comment]
> [@fmendez89](https://github.com/fmendez89) I have fixed it by this way
> 
> ```
> ultralytics/utils/ops.py
> ```
> 
> Inside `non_max_suppression` function change
> 
> ```
> time_limit = 2.0 + max_time_img * bs
> ```
> 
> to
> 
> ```
> time_limit = 60 + max_time_img * bs
> ```
> 
> 60 worked for me, tried from 5, 10 so you need to change accordingly. Restart the Notebook kernal if you are using the notebook


Thank you!  Yeah, even on a my new M3 Ultra with 96GB of Ram.  I have the model installed on a 4TB TB5 Enclosed Samsung 990 Pro SSD, which all should be fine.

I resized like 1000+ images at first to 1024, padded black to keep them more consistent, and had the 12x model resize to 640.  I tried epochs=50 imgsz=640 device=mps cache=disk batch=16.  But my RAM was going to 120+ GB sometimes and getting a ton of those warnings.

So I split into 500 images, am will be doing 2 passes.  I tried batch size of 32 as well, but still maybe more errors.  So I finally did your fix with 60, and I still got some errors, but it was staying around 60-80GB of Ram and kept processing ,and numbers dropping/accuracy going up. So I left it go overnight.  Took about 2 hours or so on GPU, and seems to have worked!

I wonder if we can push this time limit value even higher to 90, if that does anything bad?   I was seeing a ton of those warnings at first, like I said, doing new model from scratch, using 12x.  But eventually, they warnings went away for the last half of my training run.

![Image](https://github.com/user-attachments/assets/cf164e92-b3fd-4050-b35c-65a97db691dc)

**Comment by pderrenger** [comment]
Hi @Kickflipkid687,

Great to hear that increasing the NMS time limit worked for your training on the M3 Ultra! Increasing the limit to 90 or higher shouldn't cause any negative effects on model accuracy or functionality - it simply allows more processing time before triggering a warning.

The NMS time limit is primarily a monitoring mechanism rather than a functional constraint. When you increase it, you're just telling the system to be more patient before displaying warnings. The actual NMS algorithm still performs the same operations regardless of the time limit setting.

For high-resolution images or datasets with many overlapping detections, longer NMS processing times are expected. As you noticed, the warnings often decrease as training progresses since the model becomes more selective with its predictions.

If your hardware can handle the processing load without other issues (like running out of memory), feel free to set the limit high enough to avoid interrupting your workflow with warnings.

Non-Maximum Suppression is an essential post-processing step that ensures each detected object is represented by a single optimal bounding box, as explained in our [NMS documentation](https://www.ultralytics.com/glossary/non-maximum-suppression-nms).

Thanks for sharing your experience with the community!
