### ISSUE TITLE
Using a custom video stream as input

### ISSUE THREAD

**Issue by analwang** [ultralytics/yolov5#12230]
I now have a video stream data captured from ROS's simulation camera, how can I use it as input for real-time monitoring of simulation in YOLO's detect?

**Comment by glenn-jocher** [comment]
@analwang you can use a custom video stream as input for real-time monitoring in YOLOv5 using the `cv2.VideoCapture()` function from the OpenCV library. Here's an example on how you can do it:

```python
import cv2
from PIL import Image

# Define the video stream source (replace with your own source)
video_source = 'your_video_stream_url'

# Open the video stream
cap = cv2.VideoCapture(video_source)

# Loop over frames from the video stream
while True:
    # Read the frame from the video stream
    ret, frame = cap.read()

    # Check if the frame was successfully read
    if not ret:
        break

    # Convert the frame to RGB format
    frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

    # Convert the frame to a PIL image
    pil_image = Image.fromarray(frame_rgb)

    # Perform object detection on the frame using YOLOv5
    results = model(pil_image)

    # Display the results or do further processing

    # Break the loop if the 'q' key is pressed
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release the video stream and close any open windows
cap.release()
cv2.destroyAllWindows()
```

Make sure to replace `'your_video_stream_url'` with the actual URL or path to your video stream source. Additionally, adjust the code according to your specific requirements and processing needs.

I hope this helps! Let me know if you have any further questions.

**Comment by glenn-jocher** [comment]
👋 Hello @github-actions[bot], you can use the `cv2.VideoCapture()` function from the OpenCV library to read frames from your custom video stream and then perform real-time object detection using YOLOv5. An example on how to accomplish this is provided below:

```python
import cv2
from PIL import Image

# Define the video stream source (replace with your own source)
video_source = 'your_video_stream_url'

# Open the video stream
cap = cv2.VideoCapture(video_source)

# Loop over frames from the video stream
while True:
    # Read the frame from the video stream
    ret, frame = cap.read()

    # Check if the frame was successfully read
    if not ret:
        break

    # Convert the frame to RGB format
    frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    
    # Convert the frame to a PIL image
    pil_image = Image.fromarray(frame_rgb)

    # Perform object detection on the frame using YOLOv5
    results = model(pil_image)

    # Display the results or perform further processing

    # Break the loop if the 'q' key is pressed
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release the video stream and close any open windows
cap.release()
cv2.destroyAllWindows()
```

Replace `'your_video_stream_url'` with the actual URL or path to your video stream source. Additionally, adjust the code according to your specific requirements and processing needs.

Hope this helps! Let me know if you have any further questions.
