### ISSUE TITLE
What happens if a portrait-based input image is entered?

### ISSUE THREAD

**Issue by YoungjaeDev** [ultralytics/yolov5#12257]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When creating an image by extracting a video taken on an iPhone, the image is unintentionally saved as portrait-based, but the labeling is saved in 1920x1080 format. Will it have any effect on training?

![image](https://github.com/ultralytics/yolov5/assets/99321359/0d231a6b-a559-45fc-acf5-039649257ee5)

**Comment by glenn-jocher** [comment]
@youngjae-avikus the orientation of the input image does not affect the training process. YOLOv5 will automatically adjust to the dimensions of the image during training. In the case of a portrait-based input image, YOLOv5 will still be able to detect and label objects accurately. If you have any further questions or concerns, please let us know.

**Comment by YoungjaeDev** [comment]
@glenn-jocher 

Is there any code that syncs... **_"YOLOv5 will still be able to detect and label objects accurately"_**

**Comment by glenn-jocher** [comment]
@youngjae-avikus 

Yes, YOLOv5 is designed to handle images of different dimensions and orientations. When you provide a portrait-based input image, YOLOv5 will adjust to the image dimensions during training and still accurately detect and label objects. The detection and labeling capability of YOLOv5 remains unaffected by the orientation of the input image.

If you have any further questions or need assistance with the code, feel free to ask.
