### ISSUE TITLE
missing 'anchors' in exporting custom model to tflite and saved_model

### ISSUE THREAD

**Issue by mp051998** [ultralytics/yolov5#12254]
This is the command I run, and I get this error. Not able to find a similar occurence on the internet as well. Even without the --device flag, I get the same error. Any help?

python export.py --weights runs/detect/train18/weights/best.pt --include saved_model --img 416 --device 0

```
export: data=data/coco128.yaml, weights=['runs/detect/train18/weights/best.pt'], imgsz=[416], batch_size=1, device=0, half=False, inplace=False, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=17, verbose=False, workspace=4, nms=False, agnostic_nms=False, topk_per_class=100, topk_all=100, iou_thres=0.45, conf_thres=0.25, include=['saved_model']
YOLOv5 🚀 v7.0-226-gdd9e338 Python-3.9.18 torch-2.1.0+cu121 CUDA:0 (NVIDIA GeForce GTX 1660 Ti, 6144MiB)

YOLOv5nu summary (fused): 193 layers, 2503139 parameters, 0 gradients, 7.1 GFLOPs

PyTorch: starting from runs/detect/train18/weights/best.pt with output shape (1, 5, 3549) (5.0 MB)

TensorFlow SavedModel: starting export with tensorflow 2.14.0...

                 from  n    params  module                                  arguments                     
TensorFlow SavedModel: export failure ❌ 63.9s: 'anchors'
```

_Originally posted by @mp051998 in https://github.com/ultralytics/yolov5/discussions/12234_

**Comment by glenn-jocher** [comment]
Hi @mp051998! It seems that you're encountering an issue while exporting a custom YOLOv5 model to TensorFlow SavedModel. The error message suggests that the `anchors` attribute is missing.

To resolve this issue, you can try the following steps:

1. Make sure you have properly defined the `anchors` in your custom YOLOv5 model. Check the anchor values in your configuration file (typically a `.yaml` file) and ensure they are correctly specified.

2. Verify that you have the latest version of YOLOv5. Update your YOLOv5 installation using `git pull` to ensure you have the most recent codebase.

3. Double-check the model weights you are using. Ensure that the model weights (found at `runs/detect/train18/weights/best.pt`) correspond to the correct version and configuration of your custom model.

If the issue persists, please provide more details about your custom model setup, including the configuration files and any relevant customization you've made. This will help us further diagnose the problem.

Remember that your feedback and questions are valuable, and our community will be happy to assist you!

**Comment by mp051998** [comment]
> Hi @mp051998! It seems that you're encountering an issue while exporting a custom YOLOv5 model to TensorFlow SavedModel. The error message suggests that the `anchors` attribute is missing.
> 
> To resolve this issue, you can try the following steps:
> 
> 1. Make sure you have properly defined the `anchors` in your custom YOLOv5 model. Check the anchor values in your configuration file (typically a `.yaml` file) and ensure they are correctly specified.
> 2. Verify that you have the latest version of YOLOv5. Update your YOLOv5 installation using `git pull` to ensure you have the most recent codebase.
> 3. Double-check the model weights you are using. Ensure that the model weights (found at `runs/detect/train18/weights/best.pt`) correspond to the correct version and configuration of your custom model.
> 
> If the issue persists, please provide more details about your custom model setup, including the configuration files and any relevant customization you've made. This will help us further diagnose the problem.
> 
> Remember that your feedback and questions are valuable, and our community will be happy to assist you!

Thanks for your speedy reply, I resolved the issue.
I had trained my custom model by running it in python script

```
from ultralytics import YOLO
model = YOLO("yolov5nu.yaml")
results = model.train(data=config_file, epochs=100, cache=True, val=True, patience=5)
```

When I do this however the anchors are not passed along. When I switched to training using the `python train.py ` method, it worked fine.

**Comment by glenn-jocher** [comment]
Thanks for the update, @mp051998! I'm glad to hear that you resolved the issue.

Indeed, when training a custom YOLOv5 model using the `ultralytics.YOLO` API, you need to make sure that you explicitly provide the `anchors` information in your configuration file (`yolov5nu.yaml` in your case). This is because the `anchors` are not automatically inferred when using the `ultralytics.YOLO` API for training.

On the other hand, when training using the `train.py` script from the YOLOv5 repository, the `anchors` are automatically calculated based on the dataset anchors defined in the configuration file.

Therefore, if you encounter similar issues again in the future, please check if the `anchors` are correctly specified in your configuration file. 

If you have any further questions or need additional assistance, don't hesitate to ask. Our community is always here to help you out!
