### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by Auth0rM0rgan** [ultralytics/yolov5#1225]
Hello @glenn-jocher, 

I'm trying to write my own inference file to save the BBox(x1, y1, x2, y2) and the class_id of the detected object from the webcam. But, I'm getting the wrong coordinates, and also the model is not detecting well. When I'm using `detect.py` the detection is more accurate. Could you please help me with what I'm doing wrong? Thanks!

**Comment by usergxx** [comment]
you see see you batchnorm init, the batchnorm eps should be 0.001, but defalut init is 1e-5

**Comment by Auth0rM0rgan** [comment]
@supergbl Can you elaborate more? I didn't understand. my problem is, I cannot get the correct coordinates x1, y1, x2, y2 and my inference is not accurate as `detect.py`
