### ISSUE TITLE
How to change Label Size?

### ISSUE THREAD

**Issue by JWhizardz** [ultralytics/yolov5#12251]
Currently Running into this issue: 
I want to reduce the font size of the labels or just have the confidence showing. Using the "--hide-labels" hides both the labels and the confidence values. Current issue is the labels are running off the image so I can't read what the confidence values are. Is there a way to fix this issue? I've tried making adjustments to both the plot.py and detect.py as prescribed by others effected by this same issue but the instructions were unclear. 
![bouyship](https://github.com/ultralytics/yolov5/assets/148396723/bf5214a1-1ff1-447a-b443-3c43fdcc0559)

**Comment by glenn-jocher** [comment]
@JWhizardz to change the label size in YOLOv5, you can modify the code in `plot.py` file located in the YOLOv5 repository. Specifically, look for the section where the labels are being plotted, and adjust the font size according to your preference.

To show only the confidence values without the labels, you can use the `--hide-labels` argument. However, note that this will hide both the labels and the confidence values. If you want to show only the confidence values, you would need to modify the code in `plot.py` accordingly.

Please try the following steps:

1. Open the `plot.py` file in the YOLOv5 repository.
2. Find the section of code responsible for plotting the labels.
3. Locate the parameter that sets the font size and decrease its value to reduce the label size.
4. Save the file and run your detection script again to see the changes.

If you encounter any issues or the instructions are unclear, feel free to ask for further clarification.

**Comment by JWhizardz** [comment]
![image](https://github.com/ultralytics/yolov5/assets/148396723/b5397855-816b-47ba-87e9-8015efa5ba5f)
You talking about this line of code within the plots.py? Changing the values of fs by setting fs=20, had zero change on the font size. I also tried setting fs=0.001 and that two did not change the font size of the labels. Perhaps I'm adjusting the wrong parameters. Further clarification would be much appreciated.

**Comment by glenn-jocher** [comment]
Hi @JWhizardz, thank you for reaching out and providing the specific code snippet. I apologize for the confusion.

To adjust the font size of the labels, you need to modify the `fontsize` parameter in the `plot_one_box` function, not the `fs` parameter. The `fontsize` parameter controls the font size of the labels.

Please find the line of code that looks like this:
```python
label = f'{names[classification]} {conf:.2f}'
plot_one_box(xyxy, im0, label=label, color=color, line_thickness=tl, font_scale=fontsize, text_thickness=tt)
```

In this line, increase or decrease the value of `font_scale=fontsize` to adjust the font size of the labels. For example, you can try `font_scale=0.5` for a smaller font size or `font_scale=1.5` for a larger font size.

Save the file after making the changes, and run your detection script again. You should see the font size of the labels adjusted accordingly.

Feel free to ask if you have any further questions or require additional clarification.

**Comment by JWhizardz** [comment]
Thank you for the assistance, but unfortunately, I was unable to find this line of code in the plots.py or the detect.py in yolov5.

**Comment by glenn-jocher** [comment]
Hi @JWhizardz, thank you for your feedback and for trying the suggestion. I apologize for the confusion caused.

To clarify, the code snippet I mentioned previously is not present in the default `plot.py` or `detect.py` files in the YOLOv5 repository. The font size adjustment will require some modification to the existing code.

One possible approach is to modify the `plot_one_box` function in `utils/plots.py`. You can add a new parameter to the function, such as `label_fontsize`, and then adjust the font size accordingly within the function.

This modification will require understanding the code structure and making changes that suit your specific requirements. Please note that any modifications to the code should be done carefully to avoid breaking the functionality.

If you have any further questions or need assistance with making these modifications, please feel free to ask. Your feedback is valuable, and we are here to help.

Thank you for your patience and understanding.
