### ISSUE TITLE
Post-processing TFLite output

### ISSUE THREAD

**Issue by jansdhillon** [ultralytics/yolov5#12250]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello All,

I am trying to use the [tflite_flutter package](https://pub.dev/packages/tflite_flutter) with a Flutter app I am making, and I have run into a lot of issues using the tflite_model_maker. The best I've been able to get is training YOLOv5 on my dataset and then exporting it to TFLite.

When I apply NMS to the TFlite model when exporting it, I get an output shape like this:

```
  T#561(model/tf.math.multiply/Mul) shape:[1, 25200, 80], type:FLOAT32
  T#562(StatefulPartitionedCall:0) shape:[1, 100, 4], type:FLOAT32
  T#563(StatefulPartitionedCall:1) shape:[1, 100], type:FLOAT32
  T#564(StatefulPartitionedCall:2) shape:[1, 100], type:FLOAT32
  T#565(StatefulPartitionedCall:3) shape:[1], type:INT32

---------------------------------------------------------------
Your TFLite model has ‘1’ signature_def(s).

Signature#0 key: 'serving_default'
- Subgraph: Subgraph#0
- Inputs: 
    'input_1' : T#0
- Outputs: 
    'tf.image.combined_non_max_suppression' : T#562
    'tf.image.combined_non_max_suppression_1' : T#563
    'tf.image.combined_non_max_suppression_2' : T#564
    'tf.image.combined_non_max_suppression_3' : T#565
```

However, when I load this into the flutter example app, I'm warned that this operation is not supported by TFLite.

When I export it without the --nms applied, this is the output shape:
(from Netron)
```
name: StatefulPartitionedCall:0
tensor: float32[1,25200,85]
location: 532
```
However, this obviously does not work directly with the output shape defined in the [tflite_flutter package](https://pub.dev/packages/tflite_flutter).

I am no ML expert by any means so I am a bit lost about how to apply NMS to my TFLite model. From what I can understand, the tflite_model_maker package has some sort of postprocessing step to get the desired output, but I have yet to get that working (see https://github.com/tensorflow/tensorflow/issues/62135).

Could someone give me some pointers on how to process the output tensor to use in my Flutter app? From what I understand, I would have to apply the NMS algorithm from within the app itself, but I am just wondering if there's another way.  I have seen some people do it in Python. Any help is greatly appreciated.

**Comment by glenn-jocher** [comment]
@jansdhillon hi there,

To process the output tensors of your TFLite model in your Flutter app, you'll indeed need to apply the Non-Maximum Suppression (NMS) algorithm within the app itself. Currently, the tflite_flutter package doesn't support the specific operation required for NMS. 

One approach you can take is to implement the NMS algorithm manually in your Flutter app. There are several implementations available online, including Python implementations that you mentioned. You can use those Python implementations as references to understand the algorithm and then translate it to Dart code for your Flutter app. This way, you can perform NMS on the output tensors and get the desired results.

If you have further questions or need additional assistance, feel free to ask. We're here to help!

Best regards.
