### ISSUE TITLE
When using autobatch the result batch size is not a power of two. Why is it so and is it okay?

### ISSUE THREAD

**Issue by EvelinaAleksiutenko** [ultralytics/yolov5#12266]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, @glenn-jocher. I trained the model with --batch -1, and then I found by using W & B that the batch size was 52. Shouldn't the batch size be a power of two?

Thank you for your time.

**Comment by glenn-jocher** [comment]
@EvelinaAlexiutenko hi there,

While it is often recommended to use a batch size that is a power of two for optimal performance on GPUs, it is not a strict requirement. 

Using a non-power of two batch size can still work effectively, but it may lead to suboptimal performance in some cases. However, the exact impact may vary depending on the specific model architecture, GPU, and other factors.

If you would like to have a power of two batch size, you can try adjusting the mini-batch size or the number of GPUs used during training.

I hope this helps clarify the situation. Let me know if you have any further questions.

Keep up the great work!
