### ISSUE TITLE
Problem running after deploying as exe application

### ISSUE THREAD

**Issue by schosdas** [ultralytics/yolov5#12267]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

**Development environment: Windows**

I tested a function for object detection using yolov5 model and opencv.
This worked fine in python and I deployed it as an exe file using pyinstaller.
And when I run this deployed program, the following error is displayed.
`ModuleNotFoundError: No module named 'ultralytics'`

This error is for the following line.
`model = torch.hub.load('ultralytics/yolov5', 'custom', path='model.pt')`

Can you tell me the cause and solution of this problem?

My code is as follows.
```
import cv2
import torch
from PIL import Image

# YOLOv5 model load
model = torch.hub.load('ultralytics/yolov5', 'custom', path='model.pt') # Error??

# Get input from the default camera
cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()

    # Exit if the video ends
    if not ret:
        break

    # Convert the frame to a PIL image
    pil_image = Image.fromarray(frame)

    # Perform object detection using YOLOv5
    results = model(pil_image)

    # Display the detection results on the frame
    output_frame = results.render()[0]  # Convert to result image
    # Display the result frame on the screen
    cv2.imshow('Object Detection', output_frame)

    # Exit if the 'q' key is pressed
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release resources
cap.release()
cv2.destroyAllWindows()
```

P.S. And I plan to use this deployed program on a PC that is not connected to the internet. Will there be any issues?

**Comment by glenn-jocher** [comment]
@schosdas the error `ModuleNotFoundError: No module named 'ultralytics'` indicates that the `ultralytics` module is not found when running the deployed program as an executable file.

To resolve this issue, you can try adding the `ultralytics` module as a hidden import when using `pyinstaller`. This can be done by modifying your PyInstaller command with the `--hidden-import` option:

```bash
pyinstaller --hidden-import=ultralytics your_script.py
```

This ensures that the `ultralytics` module is included in the executable.

Regarding your additional question, using the deployed program on a PC that is not connected to the internet should not be an issue as long as all the required dependencies are included in the deployment. By adding the necessary hidden imports, you can ensure that all the required modules are packaged within the executable.

I hope this helps! Let me know if you have any further questions.
