### ISSUE TITLE
RuntimeError: The expanded size of the tensor (1) must match the existing size (80) at non-singleton dimension 3.  Target sizes: [1, 3, 1, 1, 2].  Tensor sizes: [3, 80, 80, 2]

### ISSUE THREAD

**Issue by youqugit** [ultralytics/yolov5#12268]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

I encountered this error while using the old version of YOLOv5 training. pt file and using the latest YOLOv5 code for inference detect.py.I forgot the specific version of YOLOv5 I used before。
I searched for the previous issue, but it has been closed and no suitable solution has been provided (the answer stated that I need to train with the latest code, but I cannot find the data from the previous training).
issue ：#https://github.com/ultralytics/yolov5/issues/5234
Are there any other solutions

error messages：
```
Traceback (most recent call last):
  File "detect.py", line 161, in <module>
    detect()
  File "detect.py", line 52, in detect
    _ = model(img.half() if half else img) if device.type != 'cpu' else None  # run once
  File "/root/miniconda3/envs/yolo-37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/ai/user/user/pingxf/pxf/be_mask_detect/models/yolo.py", line 209, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "/data/ai/user/user/pingxf/pxf/be_mask_detect/models/yolo.py", line 121, in _forward_once
    x = m(x)  # run
  File "/root/miniconda3/envs/yolo-37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/ai/user/user/yolov5/models/yolo.py", line 65, in forward
    self.grid[i], self.anchor_grid[i] = self._make_grid(nx, ny, i)
RuntimeError: The expanded size of the tensor (1) must match the existing size (80) at non-singleton dimension 3.  Target sizes: [1, 3, 1, 1, 2].  Tensor sizes: [3, 80, 80, 2]
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@youqugit this error typically occurs when there is a mismatch between the target sizes and tensor sizes in the code. It seems that you encountered this error when using an older version of YOLOv5 training.pt file and the latest code for inference using detect.py.

It's important to ensure that the training.pt file you are using is compatible with the version of YOLOv5 code you are using for inference. If the previous issue you found doesn't provide a suitable solution, it's recommended to train your model with the latest code to ensure compatibility.

If you cannot access the data from the previous training, you may need to gather or generate new data to train the model with the latest code.

Please note that if you are willing to submit a Pull Request (PR) to help resolve this issue, you can indicate that in your response. Our team greatly appreciates and encourages community contributions.

Let me know if you have any further questions or need additional assistance!

**Comment by youqugit** [comment]
@glenn-jocher Thank you for your reply.In my project, there are three old version models and a new version model, which need to predict a picture at the same time.Now it seems that there is no way to make the four models exist in one project at the same time.The model version needs to match the inference code version.I will try to retrain the model.

**Comment by glenn-jocher** [comment]
@youqugit thanks for providing more context to your issue. I understand that you have multiple models, including three old versions and one new version, and you need to predict an image using all four models simultaneously. 

To ensure compatibility, it is important that the model versions match the inference code version. In your case, since you are encountering issues with the old model versions and the latest code, retraining the models using the latest code is a recommended solution.

If you face any further difficulties or have additional questions, please feel free to ask. Happy retraining!
