### ISSUE TITLE
Is there any way to download better weights for yolov5 than those in release?

### ISSUE THREAD

**Issue by zhoujiawei3** [ultralytics/yolov5#12274]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

In another issue, I know the weights in release are pretrained with  coco dataset. With the weights in official release, I cant get the same data in papers. But I cant find any other weight, can you tell me some place to download weights  pretained with some specific datasets? like pretrained with coco and imagenet.

**Comment by glenn-jocher** [comment]
@zhoujiawei3 the weights provided in the YOLOv5 release are trained on the COCO dataset, which is a widely used benchmark for object detection. However, if you are looking for weights pretrained on specific datasets like COCO and ImageNet, I recommend exploring the YOLOv5 community and various repositories, where you may find weights trained on such datasets. Keep in mind that these weights may not be officially supported or maintained by the Ultralytics team. Feel free to experiment with different weights to find the ones that best suit your particular use case.
