### ISSUE TITLE
I want to get the coordinate system x0,y0,x0,y0. 

### ISSUE THREAD

**Issue by youngjaean** [ultralytics/yolov5#12271]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to get the coordinate system x0,y0,x0,y0. 

Currently, when I get the result in a CSV file, it comes out normalized. Also, if you get the value before normalization, it will be an int type. I want to get a value in float format. 

I also want to know if the coordinates are from the 640 or from the original image.

If I turn inference 
YOLOv5 <class 'models.common.Detections'> instance
image 1/1: 1024x1024 1 None, 1 Metal, 2 Glasss, 1 Styrofoam, 3 Batterys
Speed: 15.8ms pre-process, 13.4ms inference, 2.6ms NMS per image at shape (1, 3, 640, 640)

Also, when saved as a CSV, the 

0000.jpg | [tensor(394., device='cuda:0'), tensor(621., device='cuda:0'), tensor(447., device='cuda:0'), tensor(686., device='cuda:0')] | cat | 0.67
-- | -- | -- | --
0000.jpg | [tensor(432., device='cuda:0'), tensor(469., device='cuda:0'), tensor(584., device='cuda:0'), tensor(680., device='cuda:0')] | dog | 0.74
0000.jpg | [tensor(629., device='cuda:0'), tensor(249., device='cuda:0'), tensor(755., device='cuda:0'), tensor(344., device='cuda:0')] | gee trash | 0.79
0000.jpg | [tensor(545., device='cuda:0'), tensor(340., device='cuda:0'), tensor(706., device='cuda:0'), tensor(600., device='cuda:0')] | bee | 0.80

or 

0000.jpg | [0.41064453125, 0.63818359375, 0.0517578125, 0.0634765625] | cat
-- | -- | --
0000.jpg | [0.49609375, 0.56103515625, 0.1484375, 0.2060546875] | bee
0000.jpg | [0.67578125, 0.28955078125, 0.123046875, 0.0927734375] | dog
0000.jpg | [0.61083984375, 0.458984375, 0.1572265625, 0.25390625] | dog

**Comment by youngjaean** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.
> 
> ### Question
> I want to get the coordinate system x0,y0,x0,y0.
> 
> Currently, when I get the result in a CSV file, it comes out normalized. Also, if you get the value before normalization, it will be an int type. I want to get a value in float format.
> 
> I also want to know if the coordinates are from the 640 or from the original image.
> 
> If I turn inference YOLOv5 <class 'models.common.Detections'> instance image 1/1: 1024x1024 1 None, 1 Metal, 2 Glasss, 1 Styrofoam, 3 Batterys Speed: 15.8ms pre-process, 13.4ms inference, 2.6ms NMS per image at shape (1, 3, 640, 640)
> 
> Also, when saved as a CSV, the
> 
> 0000.jpg	[tensor(394., device='cuda:0'), tensor(621., device='cuda:0'), tensor(447., device='cuda:0'), tensor(686., device='cuda:0')]	cat	0.67
> 0000.jpg	[tensor(432., device='cuda:0'), tensor(469., device='cuda:0'), tensor(584., device='cuda:0'), tensor(680., device='cuda:0')]	dog	0.74
> 0000.jpg	[tensor(629., device='cuda:0'), tensor(249., device='cuda:0'), tensor(755., device='cuda:0'), tensor(344., device='cuda:0')]	gee trash	0.79
> 0000.jpg	[tensor(545., device='cuda:0'), tensor(340., device='cuda:0'), tensor(706., device='cuda:0'), tensor(600., device='cuda:0')]	bee	0.80
> or
> 
> 0000.jpg	[0.41064453125, 0.63818359375, 0.0517578125, 0.0634765625]	cat
> 0000.jpg	[0.49609375, 0.56103515625, 0.1484375, 0.2060546875]	bee
> 0000.jpg	[0.67578125, 0.28955078125, 0.123046875, 0.0927734375]	dog
> 0000.jpg	[0.61083984375, 0.458984375, 0.1572265625, 0.25390625]	dog
> ### Additional
> _No response_

**Comment by glenn-jocher** [comment]
@youngjaean the coordinates in the CSV output of YOLOv5 are normalized, ranging from 0 to 1. If you want the coordinates in float format, you can use the normalized values as is. Regarding your question about whether the coordinates are from the original image or a resized image, the coordinates provided are from the resized image with a size of 640x640. Thank you for your interest in YOLOv5!

**Comment by youngjaean** [comment]
Thank you for your detailed response

**Comment by glenn-jocher** [comment]
@youngjaean thanks for your question! The coordinates provided in the CSV output of YOLOv5 are normalized, ranging from 0 to 1. You can use these normalized values as is if you want to work with float coordinates. As for the origin of the coordinates, they are from the resized image with a size of 640x640. If you have any further questions, feel free to ask.
