### ISSUE TITLE
How to save image as a result with bounding box from stream or web cam video as input ?

### ISSUE THREAD

**Issue by febrianti2602** [ultralytics/yolov5#12289]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

<img width="651" alt="image" src="https://github.com/ultralytics/yolov5/assets/149127588/3730f420-7692-49c7-8018-814041e92835">

When i use --save-crop when i run detect.py, its only save an object image without bounding box. i want to save without crop the image with bounding box and save it in one folder, not split according the classes like this.

![Gambar WhatsApp 2023-10-27 pukul 09 11 22_4a0f21d2](https://github.com/ultralytics/yolov5/assets/149127588/cc2da025-8e9a-433d-80b5-878c93a59998)

**Comment by glenn-jocher** [comment]
@febrianti2602 you can save images with bounding boxes and class labels by adding the `--save-txt` flag to export results into `detect` command. For real-time webcam streams, use `detect.py --source 0` and for video files use `detect.py --source path_to_video`. This will save the images and bounding boxes in one folder with corresponding `.txt` files containing box coordinates.
