### ISSUE TITLE
can we change architecture of yolo in forward pass while inferencing/detect.py without retraining pretrained weights? 

### ISSUE THREAD

**Issue by b4u365** [ultralytics/yolov5#12292]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

can we change architecture of yolo in forward pass while inferencing/detect.py without retraining pretrained weights? 

### Additional

Hi Team ,

Thanks for your Great support,

can we change architecture of yolo v5 or v8 in forward pass while inferencing/detect.py without retraining pretrained weights?

Thanks,
Bharath

**Comment by glenn-jocher** [comment]
@b4u365 hi Bharath,

Thanks for your question! Currently, in the YOLOv5 implementation, it is not possible to change the architecture of YOLO in the forward pass during inference without retraining the pretrained weights. The architecture of the model is fixed and determined during training.

If you would like to modify the architecture, you will need to retrain the model with your desired changes. 

Feel free to reach out if you have any further questions.

Best regards,
Glenn
