### ISSUE TITLE
How do I modify the activation function for yolov5 classification detection?

### ISSUE THREAD

**Issue by huntlin** [ultralytics/yolov5#12296]
I tried modifying the activation function in model/common.py, but it didn't work；The derived onnx model is still a Sigmoid function

**Comment by glenn-jocher** [comment]
@huntlin the activation function for classification detection in YOLOv5 can be modified by editing the respective code in the `model/common.py` file. However, simply changing the code in this file might not be sufficient to modify the derived ONNX model.

To ensure that the changes take effect in the ONNX model, you will need to make the corresponding modifications in the `models/export.py` file as well. Specifically, you should check the `assign_activation` function in that file and modify it accordingly.

By making the necessary modifications in both `model/common.py` and `models/export.py`, you should be able to change the activation function for classification detection successfully.

**Comment by huntlin** [comment]
Both of the methods you mentioned have been tried and have not worked. Do you confirm that the classification model itself does not support modifying activation functions?

**Comment by glenn-jocher** [comment]
@huntlin the ability to modify the activation function for the classification model in YOLOv5 depends on the specific implementation. In the current implementation of YOLOv5, the activation function for the classification model is not easily modifiable.

However, if you still wish to modify the activation function, you may need to make changes to not only the `model/common.py` file but also the `models/export.py` file. Please note that modifying the activation function in these files may not always result in changes in the derived ONNX model.

I recommend reaching out to the YOLOv5 community or the Ultralytics team for further assistance on this matter. They may be able to provide more guidance or suggest alternative solutions.
