### ISSUE TITLE
test with 640*640 is better than 1280*1280

### ISSUE THREAD

**Issue by EtAiorsW** [ultralytics/yolov5#12298]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I trained and evaluated yolov5l on my dataset with 1280x1280 image size, but when I evaluated on test dataset, 640x640 was better than 1280x1280, with higher confidence and more accurate bounding box. Is it feasible to train with 1280x1280 image size and infer with 640x640 image size?

**Comment by glenn-jocher** [comment]
@EtAiorsW it's interesting to hear that you found better performance with 640x640 image size compared to 1280x1280 for your yolov5l model. While YOLOv5 generally achieves good results with larger input sizes, it's not uncommon to obtain better accuracy with smaller sizes in certain cases.

Regarding your question, it is certainly feasible to train with 1280x1280 image size and infer with 640x640 image size. In fact, this technique, known as "multi-scale training and testing," is commonly used to improve detection results. By performing inference at multiple scales, you can capture objects of various sizes and improve overall detection performance.

Feel free to experiment with different image sizes during training and testing to see what works best for your specific dataset and use case. Keep in mind that multi-scale training and testing can potentially increase your model's inference time, so it's important to strike a balance between accuracy and efficiency.

Let us know if you have any further questions or need assistance with anything else. Keep up the great work!

**Comment by EtAiorsW** [comment]
@glenn-jocher Thank you for your prompt reply, I noticed that there is a parameter called "--multi-scale" in train.py, I will conduct more experiment with different image sizes. Thank you again for your detailed answer.

**Comment by glenn-jocher** [comment]
@EtAiorsW you're welcome! I'm glad I could help. Yes, the `--multi-scale` parameter in `train.py` allows you to perform multi-scale training, which can be beneficial for improving detection performance. 

I encourage you to experiment with different image sizes and see how it impacts your results. If you have any further questions or need assistance with anything else, feel free to ask. Good luck with your experiments!
