### ISSUE TITLE
How to add a new label without training from scratch

### ISSUE THREAD

**Issue by phker** [ultralytics/yolov5#1229]
## ❔Question

Hello,
I'd like to ask about how to add a new label without training from scratch.

I want to add other labels to the existing yolov5s.pt. Instead of retraining the existing yolov5s.pt

If the parameter -- weights yolov5s.pt is used, will the former training result be lost so that it can no longer recognize person and bus?

I just want to add a new dataset label to identify new items, rather than retraining the entire dataset.

I looked up all the issues and I couldn't find the answer. I've asked a lot of partners who don't know how to do it. So I have to trouble you.

**Comment by glenn-jocher** [comment]
@phker your training set must include all classes you want to be able to detect.

**Comment by dongjuns** [comment]
@phker Hi, you know, that is a very interesting task in deep learning.
But not yet, we can't add a new class without retraining the previous model. :sob:

**Comment by glenn-jocher** [comment]
@dongjuns @phker yes this is correct. To train additional classes while retaining the existing classes you should label your new data **and your existing data** with **all instances of all classes** (old + new), and then train the combined (old + new) dataset together. 

There is no simple alternative today. You can always use your previous weights as new --weights however, that part is simple.
