### ISSUE TITLE
dataset.py class LoadImages has some problem i think

### ISSUE THREAD

**Issue by iop04329** [ultralytics/yolov5#123]
When i using detect.py
the img will be resize to 3,224,416
but the img should be 3,416,416
i think the problem is in dataset.py class LoadImages code
or is my using problem

**Comment by iop04329** [comment]
The code is in datasets.py
in 44 rows the class LoadImages
in 102 rows img = letterbox(img0, new_shape=(self.img_size,self.img_size))[0]
i think is letterbox function has some problem
here print the img ouput is 224,416,3
When i setting the imgsz = 416 in detect.py

**Comment by glenn-jocher** [comment]
@tsaigaga this section of the code works as intended. There is no bug.

**Comment by violet17** [comment]
> @tsaigaga this section of the code works as intended. There is no bug.

Why resize the img to 224,416,3? Why not letter box it to 416,416,3?
How does pytorch deal with input whose size is not square?

**Comment by glenn-jocher** [comment]
@violet17 this is working as intended.
