### ISSUE TITLE
cache results differ from my uploaded labels

### ISSUE THREAD

**Issue by ZooKangaroo** [ultralytics/yolov5#12301]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I use a dataset with only one catagory, so my class number must be only 0.
However, it seems that something bigger than 0 appears in the labels.
![image](https://github.com/ultralytics/yolov5/assets/52917842/100387f4-dbe7-4afc-9aa2-06a823006d15)
I've checked my labels in data, and output the paths of them, finding that every class number is exact 0 ,without any wrong.
![image](https://github.com/ultralytics/yolov5/assets/52917842/cc79f764-cec0-4dd6-ae46-908ed062c55c)
However, with some unknown operations, the final labels print the totally different things to my original datas.
![image](https://github.com/ultralytics/yolov5/assets/52917842/a3c6567c-5ebf-45c3-be99-18080255a1e6)
![image](https://github.com/ultralytics/yolov5/assets/52917842/0f852fd1-6a4e-42fa-9d0d-cf9234d0e213)

Since I don't understand what is cache, I don't know what is wrong, that my inload label_files and their path are right, 
but the result labels is wrong
![image](https://github.com/ultralytics/yolov5/assets/52917842/3b0d413d-ab96-461b-8478-fed67cf48b96)
![image](https://github.com/ultralytics/yolov5/assets/52917842/7c8cc13d-2ebc-4175-945b-f9cd12da1e10)

**Comment by glenn-jocher** [comment]
@ZooKangaroo hi there 👋,

It seems like you're experiencing some discrepancies with your labels. Although you mentioned that your class number is set to 0, you're observing different class numbers in the labels generated by YOLOv5.

The behavior you're seeing is related to caching. YOLOv5 caches preprocessed data to speed up training or inference. However, this caching can sometimes interfere with label handling and result in unexpected behavior.

To resolve this issue, you can try clearing the cache by deleting the `datasets.yaml` file in the `yolov5/data/` directory. This should ensure that the labels are generated correctly during training or inference.

If the issue persists or if you have any further questions, please let me know. I'm here to help!

**Comment by ZooKangaroo** [comment]
Thank you for your reply !
After deleting all the ```.yaml``` files in the ```/yolov5-master/data/```, nothing changed as it shows the same results appearing class 2. 
![1698828030838](https://github.com/ultralytics/yolov5/assets/52917842/2611203c-3338-4a92-b276-3f116a84db88)
And I tried to delete all the yamls under the root including those in hypes( of course it's kidding), the result is below. I'm sure no yamls exist now, hh.
![image](https://github.com/ultralytics/yolov5/assets/52917842/e4ca27d0-86ed-4d77-9091-8de7a141b834)

What I what to add is that, the datasets I use is from DOTA_v1.0 . I chose the items containing class "plane" and saving them in the file ```/DOTA_plane/train/``` . I found that the needed lines of class "plane" shows 2 as class number in the ```trainsplit``` file, and the error labels are all 2. I don't know whether it is the point.
![image](https://github.com/ultralytics/yolov5/assets/52917842/8c72e288-9afb-452a-97a5-d12c9175dd9c)
![image](https://github.com/ultralytics/yolov5/assets/52917842/d192031e-d6b7-4f4c-83c3-4f56f7597893)
![image](https://github.com/ultralytics/yolov5/assets/52917842/124accf1-b7a4-4115-91f5-3f5c1090ab5a)

**Comment by ZooKangaroo** [comment]
Sorry. The result after deleting the yamls is shown here:
![image](https://github.com/ultralytics/yolov5/assets/52917842/a6a39421-3810-4033-b045-8e953daa6ff1)

**Comment by glenn-jocher** [comment]
Hi @ZooKangaroo! Thank you for providing the additional information.

Based on the screenshots you provided, it appears that the issue is still persisting even after deleting the YAML files. The labels are still showing class 2 instead of class 0.

Since you are working with the DOTA_v1.0 dataset and selecting items containing the class "plane", it looks like the class number 2 corresponds to the class "plane" in the train split file.

To resolve this issue, you need to ensure that the class number for the "plane" class is set to 0, not 2. You can update the train split file to reflect this change.

If you've already updated the train split file and still observe the issue, please provide more details about your dataset preparation process, the format of your train split file, and any other relevant information. This will help us better understand the issue and assist you further.

Let me know if you have any questions or need further assistance.

**Comment by ZooKangaroo** [comment]
@glenn-jocher Do you mean covering the DOTA_split file when processing to only "plane" rather than making a new file named DOTA_plane?

**Comment by ZooKangaroo** [comment]
Thank you for your your answering!
It works after I delete the DOTA_split and the formal ```labels.cache```
Thank you very much again!

**Comment by glenn-jocher** [comment]
@ZooKangaroo you're welcome! I'm glad to hear that deleting the DOTA_split file and the labels.cache file resolved the issue for you.

If you have any more questions or need further assistance, feel free to ask. I'm here to help!

Thank you and happy coding!
