### ISSUE TITLE
I have trained a custom yolov5 instance model, and i have 2 class present in the predict image, what should i do i can just present just 1 class in the predict image

### ISSUE THREAD

**Issue by ziyuuuuuu** [ultralytics/yolov5#12304]
I have a question. I have used my custom-trained Yolov5 instance segmentation model and finished the inference process. but since I have two different classes that showed up at the same image, I am wondering if I can do a filter process to remain just the aimed class. I have used the supervision method (https://roboflow.com/how-to-filter-detections/yolov5) but it is not working well... The image is annotated by roboflow.

_Originally posted by @ziyuuuuuu in https://github.com/ultralytics/yolov5/issues/11506#issuecomment-1788554922_

**Comment by glenn-jocher** [comment]
@ziyuuuuuu you can filter the predicted detections to only include a specific class by using the `--conf` flag during inference. 

For example, if you want to only include the class with index 1 in the prediction results, you can run the following command:

```bash
python detect.py --source path/to/images --weights path/to/best.pt --conf 0.25 --classes 1
```

Make sure to replace `path/to/images` and `path/to/best.pt` with the appropriate paths in your setup.

Note that the `--conf` flag sets the confidence threshold for detection. You may need to adjust this value depending on your specific dataset and desired level of filtering.

Hope this helps! Let me know if you have any further questions.

**Comment by ziyuuuuuu** [comment]
Thank you! It works!!

**Comment by glenn-jocher** [comment]
@ziyuuuuuu that's great to hear! I'm glad the solution worked for you. If you have any more questions or need further assistance, feel free to ask. Happy coding!
