### ISSUE TITLE
Different Resolution Images When Training a Custom Model

### ISSUE THREAD

**Issue by qarimbas** [ultralytics/yolov5#12312]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,

I trained a custom yolov5 model using an annotated dataset consisting of 3840x2160 resolution images. It detects accurate on 3840x2160 images. However this model is not accurate when detecting different resolution images. Should I train different resolution images to overcome this issue? Thanks in advance.

Best Regards.

**Comment by glenn-jocher** [comment]
@qarimbas hi! 

When training a YOLOv5 model on a specific resolution, it is recommended to train on images of different resolutions to improve its generalization ability. This allows the model to learn robust features that are scale-invariant, enabling accurate detection on images of varying resolutions.

To address your issue, you should consider including images of different resolutions in your training dataset. This can help the model become more robust and generalize better to handle images with resolutions other than 3840x2160. Additionally, you may also experiment with augmentations such as random scaling or cropping during training to further enhance the model's ability to handle different resolutions.

I hope this helps! If you have any further questions, feel free to ask. Good luck with your training!
