### ISSUE TITLE
Tensor RT source for the custom trained models.

### ISSUE THREAD

**Issue by b4u365** [ultralytics/yolov5#12317]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi Team,

Thanks for you great Efforts,

I have a modified architecture for yolov5 which has two backbones such that it takes two inputs 1 from rgb image data and 2nd  one from ir image data.Trained this model considering yolov5s for weights initialization by fusing rgb and thermal image data. Detection results are fine but FPS is coming around 15 on jetson device. Want to increase the FPS, can you suggest any resources to increase fps.

I tried few methods of tensrort  but getting errors on the custom trained model.

Your feedback will be of great help to me

Thanks and Regards,
Bharath

**Comment by glenn-jocher** [comment]
@b4u365 hi Bharath,

Thank you for your kind words and for using YOLOv5! We appreciate your support.

To increase the FPS on your custom trained model, you can try optimizing it with TensorRT. However, since you mentioned encountering errors, please provide more details about the specific errors you are facing so that we can assist you better. This will help us understand the issue and provide appropriate guidance.

Additionally, please note that performance improvements can vary depending on the model architecture, hardware, and other factors. It is also worth considering the trade-off between accuracy and speed when optimizing the model.

Please provide more information about the errors you are encountering, and we will try our best to assist you.

Best regards,
Glenn

**Comment by b4u365** [comment]
[2023-110-yolo_tesnorrt.pptx](https://github.com/ultralytics/yolov5/files/13246685/2023-110-yolo_tesnorrt.pptx)

Hi Thanks for the quick reply

Attached is the presentation regarding the errors, to summarize the issues.

1. onnx file conversion is failed using export.py provided yolov5 repo on the **modified architecture model** which takes two inputs from rgb and ir camera, however i could able produce onnx file for on custom trained models with regular yolov5 model with out any modifications.
2. second issue is the onnx model which is output from regular yolov5s.pt using export.py has very low detection speed , regular .pt format detection speed is with 50 fps , while onnx model has 0.5 fps .

I followed this process given ultralytics below is the link for same
https://docs.ultralytics.com/yolov5/tutorials/model_export/

can you please help in addressing this issues, which will be of great help to me .

Thanks and Regards,
Bharath.

**Comment by glenn-jocher** [comment]
@b4u365 hi Bharath,

Thank you for providing the presentation and explaining the issues you are facing.

1. Regarding the failed conversion of the modified architecture model to ONNX format using the export.py script provided in the YOLOv5 repository, it's important to note that the export process might have certain limitations with modified architectures. I recommend checking if there are any special considerations or modifications required when exporting models with multiple inputs. Additionally, you might need to update the export.py script to handle your specific model architecture.

2. The significant drop in detection speed from 50 fps to 0.5 fps when using the ONNX model exported from a regular .pt model is unexpected. A potential reason for this disparity could be the presence of additional layers or operations in the ONNX model that make the inference slower. It would be helpful to compare the network architectures of the .pt model and the ONNX model to identify any discrepancies.

I recommend reaching out to the Ultralytics team directly to address these issues as they have extensive experience with YOLOv5 and may be able to provide more tailored support for your specific use case. They can assist you in identifying any potential modifications needed for exporting and optimizing your modified architecture model.

Best,
Glenn
