### ISSUE TITLE
torch.jit.trace error

### ISSUE THREAD

**Issue by daeyeoplee** [ultralytics/yolov5#12311]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

At colab i'm gonna transform yolov5 model to torchscript model an keep gets error

<img width="986" alt="image" src="https://github.com/ultralytics/yolov5/assets/83574532/73ed072d-2cd9-4a95-9290-4356fde652aa">
 
how can i solve this

**Comment by glenn-jocher** [comment]
@daeyeoplee hi there,

It looks like you are encountering an error when trying to transform a YOLOv5 model to a TorchScript model in Colab. To better assist you, could you please provide the specific error message that you are receiving?

Additionally, please make sure that you have followed the steps outlined in the [YOLOv5 PyTorch Hub Tutorial](https://pytorch.org/hub/ultralytics_yolov5/) to properly convert the model to TorchScript. Double-checking your implementation against the tutorial might help to identify any possible errors.

Looking forward to your response.
