### ISSUE TITLE
Grid size used in YOLOv5?

### ISSUE THREAD

**Issue by a-esp-1** [ultralytics/yolov5#1231]
## ❔Question
Hi,

 I'm doing inference in 10000x10000 images. My question is how can I know the grid size(SxS) used? 

In YOLOv2 is used a 13x13 grid.

Thank you in advance.

**Comment by glenn-jocher** [comment]
@a-esp-1 all YOLOv5 models use 3 multi-scale outputs at strides 8, 16 and 32.

**Comment by Axel-Jacobsen** [comment]
Is this a configurable parameter?

**Comment by glenn-jocher** [comment]
@Axel-Jacobsen this is a property of the architecture. P5 models like YOLOv5s use 3 multi-scale outputs at strides 8, 16 and 32, P6 models like YOLOv5s6 use 4 multi-scale outputs at strides 8, 16, 32 and 64.

**Comment by Axel-Jacobsen** [comment]
Gotcha, cheers!

**Comment by glenn-jocher** [comment]
@Axel-Jacobsen you're welcome! If you have any more questions, feel free to ask. Thank you for your interest in YOLOv5!
