### ISSUE TITLE
Maybe it's the memory?

### ISSUE THREAD

**Issue by zainlau** [ultralytics/yolov5#12321]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

After changing the 4060ti 16G graphics card running model, there is often a flash retreat phenomenon

### Additional

The RAM was swapped together. Two 16GB

**Comment by glenn-jocher** [comment]
@zainlau it's possible that the issue you're experiencing could be related to memory. However, it's difficult to determine the exact cause without more information. 

To help us understand the issue better, could you provide additional details such as:
- The specific YOLOv5 version you are using (e.g., v5.0, v5.0.1, etc.).
- The steps you've followed to replicate the issue.
- Any error messages or logs you've encountered during the process.

With this information, we'll be able to assist you more effectively. Thank you!
