### ISSUE TITLE
Nvidia Driver Requirement

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#1232]
## ❔Question

this is my driver
 NVIDIA-SMI 450.66       Driver Version: 450.66       CUDA Version: 11.0     |

 I enter the docker yolo, it happen

NVIDIA Deep Learning Profiler (dlprof) Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.
NVIDIA modifications are covered by the license terms that apply to the underlying project or file.

ERROR: This container was built for NVIDIA Driver Release 455.23 or later, but
       version 450.66 was detected and compatibility mode is UNAVAILABLE.

       [[CUDA Driver UNAVAILABLE (cuInit(0) returned 804)]]

NOTE: MOFED driver for multi-node communication was not detected.
      Multi-node communication performance may be reduced.

**Comment by glenn-jocher** [comment]
@alicera thanks for the feedback. I've updated the Docker quickstart guide to reflect the updated driver requirements:
https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/

You will need to update your Nvidia Driver to use the Docker image:
https://www.nvidia.com/Download/index.aspx

**Comment by alicera** [comment]
I already install new Nvidia Driver for 450.66 and build it .
Because the "FROM nvcr.io/nvidia/pytorch:20.10-py3" is build for Driver 455.23, the error happen ？


ERROR: This container was built for NVIDIA Driver Release 455.23 or later, but
version 450.66 was detected and compatibility mode is UNAVAILABLE.
