### ISSUE TITLE
Issue Encountered: SSL Certificate Verification Error During YOLOv5 Training

### ISSUE THREAD

**Issue by siddharthlanke** [ultralytics/yolov5#12328]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am a user of the YOLOv5 implementation by Ultralytics and I've encountered an SSL certificate verification error during the training process. The issue seems to be related to the download of a required font file.

Error Description:
Upon initiating the YOLOv5 training process, the script attempts to download a font file. However, the SSL certificate verification fails due to an expired certificate on the server. Consequently, the training process is interrupted.

Error Message:
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1002)

I kindly request your assistance in rectifying this SSL certificate issue to enable a smooth training process. This appears to be a server-side SSL certificate problem impacting the download of necessary files.

Thank you for your attention to this matter. Please let me know if there's any additional information or logs required from my end to assist in resolving this issue.

**Comment by glenn-jocher** [comment]
@siddharthlanke hi there! Thank you for reaching out to us regarding the SSL certificate verification error during YOLOv5 training.

We apologize for the inconvenience you are facing. This SSL certificate issue is related to the download of a font file required by the YOLOv5 training process. It seems that the certificate on the server has expired, causing the verification failure.

To rectify this, we will update the SSL certificate on the server as soon as possible to ensure a smooth training process for all users. We appreciate your patience while we work on resolving this issue.

If you have any additional information or logs that could assist us in addressing this problem, please feel free to share them with us. We will do our best to resolve this issue promptly.

Thank you for bringing this to our attention, and for your understanding. The YOLOv5 community and the Ultralytics team appreciate your support as we strive to provide the best user experience possible.

Let us know if you have any further questions or concerns.

**Comment by pvtulsiram538** [comment]
issue is still

**Comment by pderrenger** [comment]
@pvtulsiram538 hi, could you please confirm you're using the latest YOLOv5 version and that your environment’s SSL certificate store is updated? Thanks for your patience while we work to resolve this.
