### ISSUE TITLE
The tfevents are no longer recorded when hyp evolution is enabled.

### ISSUE THREAD

**Issue by geolvr** [ultralytics/yolov5#12339]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When hyperparameter evolution is enabled, tfevents are no longer recorded during the training process, so training progress cannot be tracked in real time with tensorboard.
Is there any way to still record tfevents when evolution is turned on?

**Comment by glenn-jocher** [comment]
@geolvr hello 👋,

Thank you for bringing this issue to our attention. 

I understand that when hyperparameter evolution is enabled, the tfevents are no longer recorded during the training process, making it difficult to track the training progress in real-time with tensorboard.

Currently, YOLOv5 does not have built-in support for recording tfevents during hyperparameter evolution. However, you can work around this limitation by manually saving the tfevents using the `torch.utils.tensorboard.SummaryWriter` class from PyTorch. You can create a custom callback function that saves the desired metrics during training and manually logs them using the `add_scalar` method of the `SummaryWriter` class.

Here is an example of how you can implement this:

```python
from torch.utils.tensorboard import SummaryWriter

# Create a SummaryWriter object
writer = SummaryWriter(log_dir='path/to/your/log/directory')

# Inside your training loop
for epoch in range(num_epochs):
    # your training code here
    
    # Log your desired metrics
    writer.add_scalar('loss', loss, global_step)
    writer.add_scalar('accuracy', accuracy, global_step)
    
writer.close()  # close the SummaryWriter

```

By using this approach, you can manually save the tfevents and track your training progress with tensorboard while hyperparameter evolution is enabled.

I hope this helps! Let me know if you have any further questions or need additional assistance.

Stay happy and safe!
