### ISSUE TITLE
TypeError: BaseModel.info() got an unexpected keyword argument 'detailed

### ISSUE THREAD

**Issue by qiuyuzhao** [ultralytics/yolov5#12333]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

 return self.model.info(detailed=detailed, verbose=verbose)
TypeError: BaseModel.info() got an unexpected keyword argument 'detailed

**Comment by glenn-jocher** [comment]
@qiuyuzhao this error occurs when calling the `info()` method on the `BaseModel` class with the `detailed` keyword argument, which is not expected.

To resolve this issue, you can remove the `detailed` keyword argument when calling the `info()` method.

If you need further assistance, please let us know.

**Comment by qiuyuzhao** [comment]
i remove verbose in  /ultralytics/nn/autobackend.py", line 115, model = model.fuse(verbose=verbose) if fuse else model, and detailed、verbose in engine/model.py", line 197, return self.model.info(detailed=detailed, verbose=verbose)， but when i infer /engine/results.py", line 275, in verbose
    log_string += f"{n} {self.names[int(c)]}{'s' * (n > 1)}, "
KeyError: 1511
this my code
from ultralytics import YOLO
import cv2
# Load a model
model = YOLO('yolov5x.pt')
# load a custom model
results = model("./dataset_mask/images/10.jpg") # return a list of Results objects

**Comment by glenn-jocher** [comment]
@qiuyuzhao hi there! 

It seems that you are encountering a `KeyError` in your code when trying to run inference using a custom model with YOLOv5. 

To address this issue, make sure that the class labels in your dataset align with the model's class indices. It appears that the KeyError is being raised when attempting to access the class name corresponding to the index `1511`. Verify that this index is valid and present in the `names` attribute of the `Results` object.

If you need further assistance, please let us know!

**Comment by Freesia810** [comment]
> i remove verbose in /ultralytics/nn/autobackend.py", line 115, model = model.fuse(verbose=verbose) if fuse else model, and detailed、verbose in engine/model.py", line 197, return self.model.info(detailed=detailed, verbose=verbose)， but when i infer /engine/results.py", line 275, in verbose log_string += f"{n} {self.names[int(c)]}{'s' * (n > 1)}, " KeyError: 1511 this my code from ultralytics import YOLO import cv2
> 
> # Load a model
> model = YOLO('yolov5x.pt')
> 
> # load a custom model
> results = model("./dataset_mask/images/10.jpg") # return a list of Results objects

I have met the same question, the reason is that you use the Yolo class defined in models/common.py, but the model loaded above in Yolo class define in the package ultralytics. I guess your model trained by 'train.py'. Maybe you can retrain the model in ultralytics's Yolo and reload it using YOLO('yolov5x.pt').

**Comment by glenn-jocher** [comment]
@Freesia810 it seems there might be a confusion between different versions or components of the YOLOv5 codebase. If you've made modifications to the source code, such as removing `verbose` and `detailed` arguments, it's possible that these changes are causing inconsistencies.

The `KeyError: 1511` suggests that the model is predicting a class index (1511) that does not exist in the `names` list of class labels. This could happen if the model was trained on a dataset with a different number of classes than what is being used during inference.

Please ensure that:
1. You are using the correct model weights file that corresponds to the classes in your dataset.
2. The `names` attribute in your model's `Results` object contains all the class indices that your model was trained on.

If you are using a custom dataset, make sure that the `--data` argument points to the correct YAML file with the appropriate number of classes during both training and inference.

If the issue persists, consider reverting any code changes you've made and using the original YOLOv5 codebase. For further assistance, please provide more details about the training process and the dataset you are using.
