### ISSUE TITLE
Detecting keypoints within patches of detected objects

### ISSUE THREAD

**Issue by snachi2s** [ultralytics/yolov5#12330]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello there,
I have the pretrained yolov5 model trained on my custom dataset. Now I want to estimate 4 keypoints(x,y) for each of the objects I detected using yolov5. Is it possible to add an additional head which detects n*4(n objects) keypoints to yolov5? If so, Can you help me where I need to add/modify an additional head if I want to?

### Additional

As of now I tried a simple approach of using pretrained model (like vgg, resnet) to extract features of each patches and added an regressor head to predict 4 keypoints from those patches which doesn't yield desired result.

**Comment by glenn-jocher** [comment]
@snachi2s yes, it is possible to add an additional head to YOLOv5 for detecting keypoints. To achieve this, you can modify the network architecture and add a new branch for keypoint detection.

First, you need to locate the network architecture definition in the YOLOv5 codebase. You can find it in the `models/` directory. Look for the model definition file (e.g., `yolo.py`).

Inside the model definition file, you can add the necessary layers and connections for the keypoint detection head. This head should take the feature maps from the YOLO detector and output the predicted keypoints.

You can refer to existing object detection models that have a similar keypoint detection head, such as Mask R-CNN or CenterNet, for inspiration on how to design your keypoint head.

Additionally, you may need to modify the loss function and data loading pipeline to include the keypoints and their corresponding labels.

Keep in mind that adding an additional head to the YOLOv5 architecture is a complex task and may require knowledge of deep learning frameworks like PyTorch. It's recommended to have a good understanding of the YOLOv5 codebase and the specific requirements of your task before attempting this modification.

Also, consider sharing your progress and findings with the YOLOv5 community. Collaborating and seeking feedback from others can help you overcome challenges and achieve better results.

Wishing you the best with your keypoint detection task!

**Comment by snachi2s** [comment]
Hi @glenn-jocher , 
I thought of approaching this problem with YOLO-v8 keypoint detection task. I will convert my custom dataset to YOLO expected format which is 
`<class-index> <x> <y> <width> <height> <px1> <py1> <px2> <py2> ... <pxn> <pyn>
`
I can do the Keypoints estimation in two ways,

1. **Extracting individual patches and using them as training images along with the normalized keypoints as labels for each of those patches.** By doing this way, I have only one row for each patch. For training, the YAML will be,

```
# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: ../datasets/coco8-pose  # dataset root dir
train: images/train  # train images (relative to 'path') 4 images
val: images/val  # val images (relative to 'path') 4 images
test:  # test images (optional)

# Keypoints
kpt_shape: [8, 2]  # number of keypoints, number of dims (2 for x,y or 3 for x,y,visible)
#flip_idx: [0,1,2,3,8,5,6,7,4]

# Classes dictionary
names:
  0: person
```

2. In the documentation for [Pose](https://docs.ultralytics.com/datasets/pose/#ultralytics-yolo-format) task, it was mentioned that  
    
![image](https://github.com/ultralytics/yolov5/assets/91877888/e60743b7-c268-4ced-a8de-477caa1ed6fa)

So in my case, I have multiple detected bounding boxes per image (same objects), I can create the YOLO required label.txt file for an image by adding each row for the detected bounding boxes in that image. In that way, I can represent all the bounding boxes and keypoints in a single image.

- Does both approach makes sense?

- In the second case, does YAML needs some modification? And `kpt_shape:[8, 2]` represents that 8 keypoints are there for each bounding box, so even if I have multiple detections(bounding boxes) in a single image it will work fine, right?

- If I proceed with the training in the second way, Will I be able to detect Nx8 keypoints for an image? 
N - number of bounding boxes

Thanks in Advance!

**Comment by glenn-jocher** [comment]
@snachi2s both the approaches you've outlined are reasonable ways to go about keypoints estimation with YOLOv8. Let's address your specific questions:


**Both approaches make sense** depending on your specific use case and the characteristics of your dataset. If you have multiple bounding boxes per image, the second approach of representing all bounding boxes and keypoints in a single image may be more suitable.


In the second case, the YAML file does need some modification. The `kpt_shape:[8, 2]` parameter represents that there are 8 keypoints for each bounding box. If you have multiple detections (bounding boxes) in a single image, it should work fine as long as you appropriately represent each bounding box's keypoints in the label.txt file.


If you proceed with training in the second way, you should be able to detect Nx8 keypoints for an image, where N is the number of bounding boxes. As long as each bounding box is represented correctly in the label.txt file, YOLOv8 should be able to detect the corresponding keypoints.


Wishing you the best with your YOLOv8 keypoint detection task!

**Comment by snachi2s** [comment]
Hi @glenn-jocher, 
Thanks for your quick reply!!

I converted my custom dataset to the YOLO expected format, my label.txt file for single image will look like (considering two objects in the image),

```
1 0.05674236615498861 0.7499859280056423 0.038641309738159164 0.04525299072265625 0.11354166666666667 0.42407407407407405 0.13333333333333333 0.4203703703703704 0.09427083333333333 0.40185185185185185 0.11302083333333333 0.3990740740740741 
1 0.20839789708455403 0.4052890353732639 0.11840295791625977 0.18625590006510417 0.2125 0.4777777777777778 0.23385416666666667 0.47129629629629627 0.16614583333333333 0.44907407407407407 0.18645833333333334 0.4444444444444444
```

`config.yaml` as follows,
```
path: /content/drive/MyDrive/test/data   # dataset root dir
train: train  # train images (relative to 'path') 4 images
val: val  # val images (relative to 'path') 4 images
# Keypoints
kpt_shape: [8, 2]  #2D (x,y)
flip_idx: [0,1,2,3,7,5,6,4]
# Classes dictionary
names:
  0: background
  1: person
```
training script
```
import os

from ultralytics import YOLO

model = YOLO('yolov8n-pose.pt')
model.train(data='/content/drive/MyDrive/test/config.yaml', epochs=1, imgsz=640)
```

It returns the error,
```
train: Scanning /content/drive/MyDrive/test/data/train... 1 images, 0 backgrounds, 1 corrupt: 100%|██████████| 1/1 [00:00<00:00, 116.13it/s]
train: WARNING ⚠️ /content/drive/MyDrive/test/data/train/image1.jpeg: ignoring corrupt image/label: labels require 21 columns each

len_cls, len_boxes, len_segments = (sum(x) for x in zip(*lengths))
        if len_segments and len_boxes != len_segments:
             LOGGER.warning( ValueError: not enough values to unpack (expected 3, got 0) 
```

- [x] **I checked similar issues in the repo but it doesn't solve my problem. I also checked the data loading part of images and labels**

1. In the error message, it says it expects 21 columns for each row in the label.txt file. But in my case, I have 8 keypoints which will result in 13 columns for each row (1 - class idx + 4 - bbox params + 8 keypoints). Then **why the model expects 21 columns?** 
For your reference, the last layer of the model reads 
 ` module --> ultralytics.nn.modules.head.Pose             arguments --> [1, [8, 2], [64, 128, 256]]` which means I am doing it in the right way. 

2. Why it shows the data as corrupt? Also,  when I add 8 zeros to each row (to match the expected 21 columns), the training starts with 0 corrupts.

**Comment by glenn-jocher** [comment]
@snachi2s, it looks like your label.txt file is not formatted according to YOLOv8's expectations. YOLOv8 expects a specific format for the label.txt file, with 21 columns for each row.

The format for each row in the label.txt file should be:
`class-index x_center y_center width height kpts_x1 kpts_y1 ... kpts_xN kpts_yN`

In your case, it seems that the keypoints are not being represented in the label.txt file as expected. You'll need to ensure that each row in the label.txt file contains the class index, bounding box parameters, and then the keypoints, with a total of 21 columns per row.

Adding zeros to match the expected 21 columns is not the correct approach, as it does not represent the correct keypoints for the bounding boxes.

To resolve the issue:
- Ensure that the label.txt file is formatted correctly with 21 columns for each row, including the class index, bounding box parameters, and keypoints.
- Verify that the format and content of the label.txt file align with the YOLOv8's expected input format.

This should address the corrupt data issue and allow the training to proceed without errors.

I hope this helps!
