### ISSUE TITLE
Using time_sync() to obtain time

### ISSUE THREAD

**Issue by Yakuho** [ultralytics/yolov5#12349]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

https://github.com/ultralytics/yolov5/blob/84ec8b586bd1c696f4bbf139e844a11d219f2711/utils/general.py#L183-L200

I found out in an accidental moment when I was using device ```cuda:1``` or ```cuda:2``` or whatever (Anyway, it's not ```device:0```) to achieve model inference, ```Profile``` will occupy ```device:0``` GPU memory forever. and I found that ```torch.cuda.synchronize``` can select ```device```. after my experiment, GPU memory no longer occupies ```device:0``` forever by my code. (Maybe my code isn't perfect)

```python
class Profile(contextlib.ContextDecorator):
    # YOLOv5 Profile class. Usage: @Profile() decorator or 'with Profile():' context manager
    def __init__(self, t=0.0, device=None, debug=True):
        self.t = t
        self.cuda = torch.cuda.is_available()
        self.device = device
        self.debug = debug

    def __enter__(self):
        self.start = self.time()
        return self

    def __exit__(self, type, value, traceback):
        self.dt = self.time() - self.start  # delta-time
        self.t += self.dt  # accumulate dt

    def time(self):
        if self.cuda and self.debug:
            torch.cuda.synchronize(self.device)
        return time.time()
```

In addition, I checked the pytorch document and found that ```torch.cuda.synchronize``` is synchronous operation. I want to 
know whether inference will slow when 2 YOLO model inference as the same device. If yes, ```self.debug``` may be necessary (usually inference mode do not care about performance)

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Yakuho thank you for providing detailed information about the issue you encountered. It seems that using the `Profile` class with a non-zero device causes the CUDA memory to persist on device 0. You discovered that using `torch.cuda.synchronize` allowed you to resolve the issue by selecting the correct device.

You also mentioned that you checked the PyTorch documentation and found `torch.cuda.synchronize` to be a synchronous operation. You want to confirm if there will be a slowdown in inference when running two YOLO models on the same device, and whether the `self.debug` flag will be necessary.

Your willingness to submit a pull request is appreciated, and we look forward to your contribution. Thank you for bringing this to our attention!
