### ISSUE TITLE
How to perform target detection in yolov5 on the basis of image classification？

### ISSUE THREAD

**Issue by ly1035327995** [ultralytics/yolov5#12346]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to perform target detection in yolov5 on the basis of image classification？

**Comment by glenn-jocher** [comment]
@ly1035327995 hi there,

To perform target detection in YOLOv5 based on image classification, you can use the standard YOLOv5 object detection functionality with the added capability of outputting class scores. This allows you to detect objects and classify them based on the highest scoring class. YOLOv5 supports both object detection and image classification simultaneously.

If you have any further questions or need clarification, feel free to ask.

Best regards.
