### ISSUE TITLE
set cuda

### ISSUE THREAD

**Issue by Milad-mj22** [ultralytics/yolov5#12340]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

cuda not set in select device , it is hard code in this function

### Environment

YOLO : YOLOv5
OS : linux
Python : 3.8

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Milad-mj22 thank you for bringing this issue to our attention. We appreciate your feedback and contributions to the YOLOv5 project.

Regarding your bug report, we understand that the `cuda` setting is hardcoded in the `select_device` function, and you would like it to be set dynamically instead. 

We invite you to submit a pull request (PR) with your proposed changes. Your contributions are valuable, and we appreciate your willingness to help improve YOLOv5.

If you have any questions or need further assistance, please feel free to ask. We are here to help.

Thank you again for your feedback and support!

**Note:** Please ensure that you have followed our contributing guidelines when submitting a PR.

**Comment by Milad-mj22** [comment]
I cant submit a PR , im not collaborative

**Comment by glenn-jocher** [comment]
@Milad-mj22 i understand, and thank you for letting us know. We appreciate your interest and support for YOLOv5. If you have any other feedback or questions, feel free to share them here, and we will do our best to assist you.

**Comment by Milad-mj22** [comment]
tnx
    On Saturday, November 11, 2023 at 10:50:53 PM GMT+3:30, Glenn Jocher ***@***.***> wrote:  
 
 


@Milad-mj22 i understand, and thank you for letting us know. We appreciate your interest and support for YOLOv5. If you have any other feedback or questions, feel free to share them here, and we will do our best to assist you.

**Comment by glenn-jocher** [comment]
@Milad-mj22 this message seems to be an automated notification from GitHub. If you have any further questions or need assistance, please feel free to ask directly on GitHub, and we will be happy to help. Thank you for your understanding and support!
