### ISSUE TITLE
I am trying to convert Labelme Json file to yolo format, but the bounding box is getting shifted, I will share my conversion code here.

### ISSUE THREAD

**Issue by naveenvj25** [ultralytics/yolov5#12352]
I am trying to convert Labelme Json file to yolo format, but the bounding box is getting shifted, I will share my conversion code here. 
import os
import json

def json_to_yolo(json_file, output_yolo_file):
    with open(json_file, 'r') as json_file:
        data = json.load(json_file)
    image_width=data['imageWidth']
    image_height=data['imageWidth']

    with open(output_yolo_file, 'w') as yolo_file:
          for shape in data['shapes']:
              label = shape['label']
              # Extract all x and y coordinates from the points
              x_values = [point[0] for point in shape['points']]
              y_values = [point[1] for point in shape['points']]

    # Calculate the bounding box coordinates
              x_min = min(x_values)
              print(x_min)
              x_max = max(x_values)
              print(x_max)
              y_min = min(y_values)
              print(y_min)
              y_max = max(y_values)
              print(y_max)
            # Calculate YOLO coordinates
              x_center = (x_min + x_max) / ( 2*image_width)
              y_center = (y_min + y_max) / ( 2*image_height)
              width = (x_max - x_min) / (image_width)
              height = (y_max - y_min) / (image_height)
              # YOLO format: <class_id> <center_x> <center_y> <width> <height>
              class_id = get_class_id(label)
            # Write YOLO format data to the output YOLO file
              yolo_line = f"{class_id} {x_center:.6f} {y_center:.6f} {width:.6f} {height:.6f}"
              yolo_file.write(yolo_line + "\n")

def get_class_id(label):
    # Implement your own logic to map label names to class IDs
    class_id_mapping = {
        'Grade 1': 0,
        'Grade 2': 1,
        'Grade 3': 2,
        # Add more class labels as needed
    }
    return class_id_mapping.get(label, -1)  # -1 for unknown labels

if __name__ == '__main__':
   json_file = '/content/IMG_0188.json'
   output_yolo_file = '/content/yolo_0188.txt'
   json_to_yolo(json_file, output_yolo_file)

Using json file, I am getting the correct bounding box on the image, but the box is shifted when I display the bounding box from the text file ..!

_Originally posted by @naveenvj25 in https://github.com/ultralytics/yolov5/issues/10161#issuecomment-1803096920_

**Comment by glenn-jocher** [comment]
@naveenvj25 it seems like the bounding box coordinates conversion to YOLO format in your code might be causing the issue. Ensure that the bounding box coordinates are being converted correctly to the YOLO format, considering the image dimensions. Double-check the calculation for `x_center`, `y_center`, `width`, and `height` to ensure they accurately represent the bounding box in YOLO format. Also, verify the class ID mapping to ensure it's consistent with your requirements.

**Comment by naveenvj25** [comment]
@glenn-jocher Yes, it was the error in the calculation of x_center and y_center.  Now it's working correctly.

**Comment by glenn-jocher** [comment]
@naveenvj25 glad to hear that you were able to resolve the issue! If you have any more questions or run into any other issues, feel free to ask. Keep up the good work!

**Comment by naveenvj25** [comment]
@glenn-jocher Thanks for the help..! Sure, I will ask if there is any problem.

**Comment by glenn-jocher** [comment]
@naveenvj25 you're welcome! Feel free to reach out anytime. The YOLO community and our team at Ultralytics are here to assist.
