### ISSUE TITLE
Does yolov5-5.0 support inference with ‘.engine’ weights?

### ISSUE THREAD

**Issue by GitHub-lzw** [ultralytics/yolov5#12359]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi. I have some videos that need to be detected and I hope to improve the detection speed. The version is yolov5-5.0, and system is Windows.
I have two Nvidia GPUs, but I don't know how to perform multi-GPU inference; Then I tried to generate engine weights to accelerate inferencing, but it also failed.
Is there a good way to accelerate the inference speed of videos？

**Comment by glenn-jocher** [comment]
@GitHub-lzw hi there! YOLOv5-5.0 does not currently support inference with '.engine' weights. As for multi-GPU inference on Windows, you can use the `--device` flag to specify multiple GPUs during inference. However, please note that YOLOv5 currently does not support engine weights for acceleration. If you're looking to improve inference speed for videos, I recommend experimenting with optimizations such as ONNX, TensorRT, or AMP. Let me know if you need further assistance!
