### ISSUE TITLE
Catastrophic Forgetting

### ISSUE THREAD

**Issue by mr-mainak** [ultralytics/yolov5#12355]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have trained a model_A for full 300 epochs. Now I want to again retrain model_A with some new data(say B). This leads to catastrophic forgetting of the previous data. Should I train on the new(B) + old data on the ```best.pt``` obtained from previous training. Any suggestion would be highly appreciated.
Regards

**Comment by glenn-jocher** [comment]
@mr-mainak hi there,

It sounds like you're experiencing catastrophic forgetting when retraining your model with new data. To avoid this, you can combine the new data (B) with the old data and then train the model using the `best.pt` obtained from the previous training. This approach can help mitigate catastrophic forgetting and retain knowledge from the original training.

Best regards

**Comment by mr-mainak** [comment]
> @mr-mainak hi there,
> 
> It sounds like you're experiencing catastrophic forgetting when retraining your model with new data. To avoid this, you can combine the new data (B) with the old data and then train the model using the `best.pt` obtained from the previous training. This approach can help mitigate catastrophic forgetting and retain knowledge from the original training.
> 
> Best regards

Thanks for your quick and prompt reply
Regards

**Comment by mr-mainak** [comment]
> @mr-mainak hi there,
> 
> It sounds like you're experiencing catastrophic forgetting when retraining your model with new data. To avoid this, you can combine the new data (B) with the old data and then train the model using the `best.pt` obtained from the previous training. This approach can help mitigate catastrophic forgetting and retain knowledge from the original training.
> 
> Best regards

Thanks for your quick and prompt reply
Regards

**Comment by glenn-jocher** [comment]
@mr-mainak hi there,

You're welcome! If you have any further questions or need additional assistance, feel free to reach out. We're here to help!

Best regards
