### ISSUE TITLE
Different results from exported models when using export script VS ultralytics library

### ISSUE THREAD

**Issue by rfire01** [ultralytics/yolov5#12362]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I'm trying to use tflite version yolov5 and received different results when exporting the model in different way.
On the first time I used the export script in the repo (The exported file name is yolov5n-fp16.tflite):
python export.py --weights yolov5n.pt --include  tflite

And on the second time I tried using the ultralytics library (The exported file name is yolov5nu_float16.tflite):
from ultralytics import YOLO
model = YOLO('yolov5n.pt')  # load an official model
model.export(format='tflite')

When I used option 1 with tf.lite.Interpreter it seems to work properly, I received many boxes (4 first columns) and some of them had high confidence (fifth column).

Next, I tried to load the model I got in the second method , I got only 4 lines of boxes (the rest were zeros) with very small values and very low confidence (highest confidence of 0.1).

I did my tests on the following image:

https://media.cnn.com/api/v1/images/stellar/prod/220118174717-05-tripadvisor-most-popular-destinations-2022-paris.jpg?q=h_1333,w_2000,x_0,y_0/h_618
I loaded the image and passed it to inference in the exact same way for both loaded models.

Are there differences between the two exported models that I need to take into account? Do something before or after the inference differently?

I attached the code I used for inference.
[inference.zip](https://github.com/ultralytics/yolov5/files/13316882/inference.zip)

**Comment by glenn-jocher** [comment]
👋 Thanks for reaching out! We value your feedback. YOLOv5 exports `torch` models to TFLite using official PyTorch<->TFLite conversion in `export.py`, whereas `torch` models to TFLite using `ultralytics ` PyTorch<->TFLite conversion in `YOLO().export(format='tflite')`. Differences in output might arise from how TFLite handles model conversion.

To investigate, compare outputs from models using conversion tools such as [openvino](https://github.com/openvinotoolkit/openvino) or [ONNX](https://github.com/onnx/onnx) to TFLite, ensuring that TFLite layers and parameters match.

Happy YOLO-ing!

**Comment by ZXTFINAL** [comment]
before you export the model,model.eval() may work?

**Comment by rfire01** [comment]
> before you export the model,model.eval() may work?

Yes. The issue was that the two exported tflite were not exactly the same and had a little different output.
Once I unserstood the output format it started working

**Comment by glenn-jocher** [comment]
@rfire01 glad to hear that! Yes, calling `model.eval()` before export can make a difference. Each export method uses a unique conversion process that might affect the output. Understanding the output format is key to successful usage. Good luck with your project!
