### ISSUE TITLE
yolov5 was originally a target detection model, and then the image classification function was added. What is the principle of the added image classification function?

### ISSUE THREAD

**Issue by ly1035327995** [ultralytics/yolov5#12367]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

yolov5 was originally a target detection model, and then the image classification function was added. What is the principle of the added image classification function?

**Comment by glenn-jocher** [comment]
@ly1035327995 the image classification functionality was added to YOLOv5 through the implementation of a classifier head, which performs classification on the output feature map of the detection head. This allows YOLOv5 to simultaneously perform both object detection and image classification using a single network architecture.
