### ISSUE TITLE
how to make labels if an instance has multiple disconnected parts

### ISSUE THREAD

**Issue by Jerry2990** [ultralytics/yolov5#12364]
Thanks for work.
I notice that coco-seg128 datasets labels consist of categories and coordinate **xy** without group .  
If an instance has multiple disconnected parts , e.g., 
![image](https://github.com/ultralytics/yolov5/assets/50744843/c5df8e47-53c7-4175-bfba-63ad1f9c0279)How should the label be set or do I need to change the code.
Thanks.

**Comment by glenn-jocher** [comment]
To label instances with multiple disconnected parts, you can consider each disjoint part as a separate object instance and create a separate label for each part. This can be achieved by extending the COCO format to accommodate multiple instances, each with its own category and coordinates. There is no need to change the YOLOv5 code to handle this scenario, as the framework supports multiple instances with their own labels and coordinates. If necessary, you may need to adjust your data processing pipeline to handle these disjoint parts as individual objects. If you have any specific questions about implementation, feel free to ask!
