### ISSUE TITLE
BACKBONE Structure 

### ISSUE THREAD

**Issue by anoop54** [ultralytics/yolov5#1236]
## ❔Question
I understand we are using a custom backbone with CSPNet inspirations, but which base network is it built on top of? Is it CSPNet x Darknet53 ?

**Comment by anoop54** [comment]
@glenn-jocher ?

**Comment by glenn-jocher** [comment]
@anoop54 for backbone definition see model yaml:

https://github.com/ultralytics/yolov5/blob/c8c5ef36c9a19c7843993ee8d51aebb685467eca/models/yolov5s.yaml#L12-L26
