### ISSUE TITLE
How to load images from an array instead from a path using detect.py?

### ISSUE THREAD

**Issue by DiogoFerreira77** [ultralytics/yolov5#12378]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello everyone! 

To run detect.py you have to give a source path, webcam, screenshot, etc... But what I am doing is storing images in arrays and I would like to use detect.py to run in those images. So my question is, if it is possible to adapt detect.py in order the source to be an array of images.

Any help or ideas would be very much appreciated! :)

**Comment by glenn-jocher** [comment]
@DiogoFerreira77 hi there! Currently, the `detect.py` script requires image file paths as input sources. However, you can easily convert your image arrays to files and then use `detect.py`. We appreciate your interest and always welcome new ideas and contributions. If you have more questions or need further assistance, feel free to ask! 😊
