### ISSUE TITLE
Yolo v5 in Raspberry show: segamentation fault

### ISSUE THREAD

**Issue by 13581913656** [ultralytics/yolov5#12371]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I installed Yolo V5 default installation package in Raspberry 4B, and run requirements.txt shows successful. All necessary libs are installed done, then I run defect.py finally show the Segementation fault. I would like to know what's the problem or Yolo V5 can not running in Raspberry 4B?

**Comment by 13581913656** [comment]
Issue solved, I downgrade the version of Pytorch, torchvision and torchaudio, then system are running, Happy!
pip uninstall torch torchvision
pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2

**Comment by glenn-jocher** [comment]
@13581913656 glad to hear the issue is resolved! Downgrading PyTorch, Torchvision, and Torchaudio to specific versions can sometimes help with compatibility. If you have any further questions or run into any more issues, feel free to ask. Keep up the great work!
