### ISSUE TITLE
How to Customize yolov5 model.

### ISSUE THREAD

**Issue by jahid-coder** [ultralytics/yolov5#12381]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Recently, I have used yolov5 to detect object . But I want to model tuning and want to change different function parameter such as activation, filter and layer, and output that means i want to customize the model. How can i customize the yolov5 model.

**Comment by glenn-jocher** [comment]
@jahid-coder hi there! Customizing the YOLOv5 model can be accomplished by modifying the architecture within the `models/yolov5.yaml` file. This file defines parameters such as network depth, width, and other architectural decisions. Additionally, you can modify the model using the available `--cfg`, `--weights`, and `--hyp` command line arguments. For further information, you can refer to the Ultralytics Docs at https://docs.ultralytics.com/yolov5/. Let me know if you need further assistance!

**Comment by jahid-coder** [comment]
@glenn-jocher , thanks for your response, I want to know ,how to change different function parameter such as activation, filter and layer, and output in yolov5 model. To modify or customize  the model yolov5  can i modify the common.py file ? What is the process to modify the model.

**Comment by glenn-jocher** [comment]
@jahid-coder You can customize the YOLOv5 model by modifying the architecture within the `models/yolov5.yaml` file. This file defines parameters such as activation functions, filters, layers, and output configurations. Additionally, you can modify the architecture by editing the `common.py` file, which contains the common functions used across the YOLOv5 models. For detailed instructions, you can refer to the Ultralytics Docs at https://docs.ultralytics.com/yolov5/. Let me know if you have any further questions!
