### ISSUE TITLE
Save image only once

### ISSUE THREAD

**Issue by AbhishekPSI7042** [ultralytics/yolov5#12388]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I working on number plate detection and I trained the model and used detect.py for inference now I want to save a image when model detect number plate first time. I have used save-crop parameter that is giving multiple images in the output.

**Comment by glenn-jocher** [comment]
@AbhishekPSI7042 hi there! To save only the first detected number plate image, you can add the `--save-once` flag to your detect.py command. This will save only the first detection of each class per image. For more details on available flags, you can refer to the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/.

Let me know if you need further assistance!

**Comment by Abhi-prasad7042** [comment]
@glenn-jocher Hii, I don't understand how do I add save-once to the detect.py command. My use case is I have only one class which is the number plate now I want to save each car number plate only once when I was using save-crop it gave multiple images of the same car because it saves images on each frame. Can we put some logic that it will save only one image whenever it detects a number plate?

**Comment by glenn-jocher** [comment]
@Abhi-prasad7042 hey! Sure, you can achieve this by modifying the detect.py file in the YOLOv5 repository to add custom logic for saving only the first detected number plate image. However, you may need some understanding of Python and PyTorch to do this.

Alternatively, you can create a script to process the output of detect.py and filter out duplicate number plate images using a simple Python code. This script can keep track of the detected number plates and save only the first instance of each unique plate number.

Feel free to reach out if you need any further guidance or code examples!
