### ISSUE TITLE
Data Augumentation to improve YOLOV5 Training accuracy

### ISSUE THREAD

**Issue by naveenvj25** [ultralytics/yolov5#12380]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

@glenn-jocher  I have a custom dataset with annotation labels. Now, I am planning to increase the dataset with some standard augmentation. Does the yolov5 model automatically perform augmentation? If so, by updating the default hyperparameters, can it increase the images by augmentation and further improve MAP and other matrix values? Or should I do augmentation manually, but if so, I need to do labeling also, which might take more time.

**Comment by glenn-jocher** [comment]
@naveenvj25 hi there! YOLOv5 doesn't currently perform data augmentation automatically during training. However, you can easily apply it using popular libraries like Albumentations or OpenCV, and then adapt the augmented images and bounding boxes accordingly. This typically improves model accuracy. You can learn more on data augmentation in the training section of the Ultralytics Docs. If you have further questions, feel free to ask!

**Comment by naveenvj25** [comment]
@glenn-jocher hi..!  Actually, by default, the following hyperparameters related to augmented are called in the train.py file from the hyp file. So my doubt is, does some augmentation happening  in the images while training..?

hsv_h: 0.015  # image HSV-Hue augmentation (fraction)
hsv_s: 0.7  # image HSV-Saturation augmentation (fraction)
hsv_v: 0.4  # image HSV-Value augmentation (fraction)
degrees: 0.0  # image rotation (+/- deg)
translate: 0.1  # image translation (+/- fraction)
scale: 0.5  # image scale (+/- gain)
shear: 0.0  # image shear (+/- deg)
perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
flipud: 0.0  # image flip up-down (probability)
fliplr: 0.5  # image flip left-right (probability)
mosaic: 1.0  # image mosaic (probability)

**Comment by glenn-jocher** [comment]
@naveenvj25 Those parameters in the hyp file are indeed related to augmentations. YOLOv5 does perform built-in augmentations during training using these parameters. Feel free to tweak these values to optimize your training based on your specific dataset and requirements. If you need further assistance or have more questions, don't hesitate to ask!

**Comment by naveenvj25** [comment]
Ok, thank you...I will explore that..!

**Comment by glenn-jocher** [comment]
@naveenvj25 you're welcome! If you have any more questions as you explore, feel free to reach out. Best of luck with your exploration!
