### ISSUE TITLE
Limited Speed Improvement After Converting yolov5+repvgg to TensorRT

### ISSUE THREAD

**Issue by xiaoche-24** [ultralytics/yolov5#12383]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, based on YOLOv5s, I added the RepVGG and PartialConv (Fasternet) modules. After training, the improved PyTorch (pt) model is 30% faster than the original YOLOv5s.pt model. However, after converting both to TensorRT, the improved TensorRT engine model is 30% slower than the original YOLOv5s.engine model. Can you please help me understand the reason for this?

**Comment by glenn-jocher** [comment]
@xiaoche-24 hi, thanks for reaching out! Converting models to TensorRT can yield mixed results, and performance can be influenced by various factors such as layer types, input shapes, and TensorRT parameters. It's great that you achieved a speed improvement in the PyTorch model!

To better understand the slowdown in the TensorRT engine model, could you provide information about the TensorRT conversion process, including the specific TensorRT version used, any custom TensorRT settings, and the target device for inference?

Additionally, you might find relevant insights in the Ultralytics YOLOv5 documentation at https://docs.ultralytics.com/yolov5/. Feel free to explore the optimization and deployment sections for further guidance.

Looking forward to assisting you further!
