### ISSUE TITLE
Request for Updated YOLO Pretrained models  - Inspired by RT-DETR

### ISSUE THREAD

**Issue by PraveenKumar-Rajendran** [ultralytics/yolov5#12397]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

- **Observation**: RT-DETR, a real-time transformer-based detection model, showed significant performance improvement in RT-DETR on the COCO dataset validation when pretrained with the Object365 dataset.

RT-DETR: https://github.com/lyuwenyu/RT-DETR

- **Test Results**: Comparison between the original COCO-only pretrained RT-DETR and the Object365+COCO pretrained version demonstrates a notable performance jump

<img width="688" alt="rt-detr-graph-latest" src="https://github.com/ultralytics/yolov5/assets/53290706/e36d2bfa-68ee-422b-8855-3c3baf33f5c7">

PS: Confirmed this with the custom dataset for training and validation.

- **Request**: Please consider adopting a similar pretraining approach for YOLO models, utilizing the Object365 dataset in addition to the standard COCO pretraining.

### Use case

- **Potential Impact**: This methodology could enhance YOLO models' performance (both v5  and v8), benefiting the broader YOLO community and advancing object detection capabilities.

### Additional

- **Appreciation**: Thank you for your ongoing contributions to object detection research and development.

Thank you for considering this request.

FYI,
raised a same request in YOLOv8 repository [here](https://github.com/ultralytics/ultralytics/issues/6448)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@PraveenKumar-Rajendran thank you for your suggestion! It's great to hear your interest in enhancing YOLO models. We value contributions from the community like yours. We'll look into this further and consider potential improvements for our pretrained models. Your feedback is very much appreciated. If you have any other ideas or feedback, feel free to share.

Your support and understanding make a real difference to the YOLO community. Thank you!
