### ISSUE TITLE
CoreML Output

### ISSUE THREAD

**Issue by Doris-WenZiYing** [ultralytics/yolov5#12395]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I'm a newbie for Yolo and CoreML.
I export the Yolov5 model to the CoreML model, but the output of the model only has confidence and coordinates, I wanna add the class labels to my output, what should I do? 
<img width="1068" alt="Screenshot 2023-11-19 at 15 44 32" src="https://github.com/ultralytics/yolov5/assets/95731223/a7c11642-ddc6-493c-ab35-d12fbed4882d">

**Comment by glenn-jocher** [comment]
@Doris-WenZiYing hi there! To include class labels in the CoreML output, you can use the `export` function in YOLOv5 with the `--include` flag to include class names. You can find more details in our documentation at https://docs.ultralytics.com/yolov5/. Let me know if you need further assistance!
