### ISSUE TITLE
Why is the size of the model I trained different from yolov5s.pt？

### ISSUE THREAD

**Issue by mayday0208** [ultralytics/yolov5#124]
yolov5s.pt only 13.6MB
The size of the model I trained is 52.6MB

**Comment by glenn-jocher** [comment]
@mayday0208 you have fp32 model + fp32 optimizer in your checkpoint. To remove these and reduce to fp16 use utils.strip_optimizer()

**Comment by glenn-jocher** [comment]
Also, update your repo with git pull

**Comment by rcg12387** [comment]
Here is the answer: #253
