### ISSUE TITLE
Edit detect options for training

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#1240]
I'm looking to train a model using class agnostic NMS. When I want to run detections with this, I can just add the --agnostic-nms argument. However this is not an option I can set for training, and the only ways I can think to do this is edit detect.py as below:

`# Apply NMS
        pred = non_max_suppression(pred, opt.conf_thres, opt.iou_thres, classes=opt.classes, agnostic=True)
        t2 = time_synchronized()`

Is there a more 'proper' way to do this?

**Comment by glenn-jocher** [comment]
@adamwhats97 you can update here:
https://github.com/ultralytics/yolov5/blob/c8c5ef36c9a19c7843993ee8d51aebb685467eca/test.py#L114-L117

**Comment by ghost** [comment]
Great, cheers!
