### ISSUE TITLE
AttributeError: 'AutoShape' object has no attribute 'detect'

### ISSUE THREAD

**Issue by Zwingli09** [ultralytics/yolov5#12407]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

So i try to make Real-Time Object Detection that can Screenshot Capture when object is detected and saved the screenshot on my folder. But I faced this problem. I am newbie and I need help to fix this, I'm tired of searching on the internet but can't find a solution.

def initialize_yolov5():
    model = torch.hub.load('yolov5', 'custom',
                           path=r'C:\Users\Zwingli\PycharmProjects\helmonzy\helmonzy_Fixed.pt',
                           source='local', force_reload=True)
    return model

def capture_screenshot(frame, nonhelm_detected):
        if nonhelm_detected:
            logging.info("Person detected. Capturing screenshot...")
            # Code to capture screenshot
            screenshot = frame.copy()
            screenshot_path = f"{SCREENSHOT_DIR}/screenshot_{timestamp}.jpg"
            cv2.imwrite(screenshot_path, screenshot)
            logging.info(f"Screenshot saved: {screenshot_path}")

def generate_annotation(screenshot, nonhelm_bbox):
    logging.info("Generating annotation...")
    # Code to generate annotation file
    annotation = Annotation(screenshot, nonhelm_bbox)
    annotation_path = f"{ANNOTATION_DIR}/annotation_{timestamp}.txt"
    annotation.save(annotation_path)
    logging.info(f"Annotation saved: {annotation_path}")

def main():

    model = initialize_yolov5()
    if not model:
        logging.error("Failed to initialize YOLOv5 model. Exiting...")
        return

    cap = cv2.VideoCapture(0)
    while True:
        # Read frame from video feed
        ret, frame = cap.read()
        if not ret:
            logging.error("Failed to read frame from video feed. Exiting...")
            break

        frame = model(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB), size = 400)

        detections = model.detect()

        nonhelm_detected = False
        for detection in detections:
            if detection.class_label == "non-helm":
                nonhelm_detected = True
                nonhelm_bbox = detection.bounding_box
                break

        capture_screenshot(frame, nonhelm_detected)
        if nonhelm_detected:
            generate_annotation(frame, nonhelm_bbox)

        cv2.imshow("Object Detection", frame)

        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    cap.release()
    cv2.destroyAllWindows()

if __name__ == "__main__":
    main()

Then when I run the program I get error
Traceback (most recent call last):
  File "C:\Users\Zwingli\PycharmProjects\helmonzy\test3.py", line 111, in <module>
    main()
  File "C:\Users\Zwingli\PycharmProjects\helmonzy\test3.py", line 84, in main
    detections = model.detect()
  File "C:\Users\Zwingli\PycharmProjects\helmonzy\venv\lib\site-packages\torch\nn\modules\module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'AutoShape' object has no attribute 'detect'

**Comment by glenn-jocher** [comment]
@Zwingli09 hi there! It looks like you're encountering an error related to the YOLOv5 model. The issue is that you're attempting to call the `detect` method directly on the model, whereas you should be operating on the return of the model forward pass.

In the code snippet provided, replace
```python
detections = model.detect()
```
with
```python
detections = model.predictions[0]
```

This change assumes that you're using YOLOv5 model from Ultralytics. You may need to adjust it if you're using a different version or source for the YOLOv5 model.

Let me know if that fixes the issue for you! And don't hesitate to reach out if you have any more questions.

**Comment by Zwingli09** [comment]
Alright thankyou, i will try it

**Comment by glenn-jocher** [comment]
@Zwingli09 you're welcome! Feel free to give it a try, and let me know if you have any more questions or need further assistance. Good luck with your project!
