### ISSUE TITLE
GPU Not Utilized Properly in ONNX/Triton Server Inference

### ISSUE THREAD

**Issue by sumanthvisionify** [ultralytics/yolov5#12402]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection, Export, Other

### Bug

I have trained YOLOv5 models and converted them to ONNX format. I am using Triton Server to serve these models for inference on a GPU with 12 GB . However, I've noticed that Triton Server is only utilizing around 2 GB of GPU memory, even when running multiple models(5) concurrently. This underutilization of GPU resources is impacting the overall inference performance and efficiency.

- Triton Server Version(docker) : nvcr.io/nvidia/tritonserver:23.10-py3 
- GPU: NVIDIA A10-12Q
- Operating System: Ubuntu 20.04

**Triton docker logs** 

I1116 13:06:24.997288 1 server.cc:662] 
+--------------------------+---------+--------+
| Model                    | Version | Status |
+--------------------------+---------+--------+
| model1                  | 1       | READY  |
| model2                  | 1       | READY  |
| model3                  | 1       | READY  |
| model4                  | 1       | READY  |
| model5                  | 1       | READY  |
+--------------------------+---------+--------+

I1116 13:06:25.008435 1 metrics.cc:817] Collecting metrics for GPU 0: NVIDIA A10-12Q
I1116 13:06:25.008586 1 metrics.cc:710] Collecting CPU metrics
I1116 13:06:25.008858 1 tritonserver.cc:2458] 

Triton Server is consistently utilizing only around 2 GB of GPU memory, regardless of the number of models running concurrently. This leads to underutilization of the GPU and suboptimal inference performance.

![image](https://github.com/ultralytics/yolov5/assets/112458608/a77a0dff-51f9-48cb-95a6-3ed2e6370be6)

**Note**:
This issue significantly impacts the inference performance of my application. I'm seeking assistance in resolving this problem to ensure efficient GPU resource utilization when serving multiple YOLOv5 models using Triton Server.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@sumanthvisionify hi there! Thank you for reaching out. It sounds like the Triton Server may not be utilizing your GPU resources efficiently. We recommend checking the Triton Server documentation to ensure that the server is properly configured for optimal GPU memory usage.

You may also want to verify that your YOLOv5 models are being loaded and run on the GPU within Triton Server, as this could impact GPU memory utilization. Additionally, confirming that the ONNX format conversion for your YOLOv5 models is not causing any unexpected behavior is always a good idea.

Lastly, the Triton Server version you mentioned (nvcr.io/nvidia/tritonserver:23.10-py3) implies support for the NVIDIA A100 GPU. You may want to confirm compatibility with your NVIDIA A10-12Q GPU and explore any potential GPU-specific settings that could be impacting memory usage.

For more detailed help in configuring Triton Server, you can refer to the Ultralytics Docs at https://docs.ultralytics.com/yolov5/. I hope this helps to improve the GPU resource utilization for your YOLOv5 models with Triton Server!
