### ISSUE TITLE
 ImportError when trying to implement DeepSort_YOLOv5_Pytorch

### ISSUE THREAD

**Issue by PG-9-9** [ultralytics/yolov5#12410]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

**Issue:**
I am currently attempting to implement DeepSort_YOLOv5_Pytorch in my project. As part of the setup process, I have cloned the yolo_v5 repository into my project directory. However, when I try to run the code, I encounter the following error:

```
from utils import TryExcept, emojis
ModuleNotFoundError: No module named 'utils'
```

Upon investigating the issue, I suspect that the problem may be related to the `utils` module within the yolo_v5 repository, as I cannot find the import statement for it.

**Context:**
I have followed the setup instructions for DeepSort_YOLOv5_Pytorch, including cloning the yolo_v5 repository into my project directory. The goal is to combine YOLOv5 for object detection with DeepSort for object tracking. However, it seems that the code is unable to find the required `utils` module from the yolo_v5 repository.

**Expected Behavior:**
I expect the code to run without any ImportError related to the `utils` module, allowing me to successfully implement DeepSort_YOLOv5_Pytorch in my project.

**Steps to Reproduce:**
1. Clone the DeepSort_YOLOv5_Pytorch repository.
2. Clone the yolo_v5 repository into the project directory.
3. Run the code.

**Additional Information:**
- Project Repository: (https://github.com/HowieMa/DeepSORT_YOLOv5_Pytorch)
- Operating System: Ubuntu 22.04
- Python Version: 3.11.4

### Additional

Please let me know if there are any specific steps or configurations I should follow to resolve this issue or if there's any additional information needed to assist in troubleshooting.

**Comment by glenn-jocher** [comment]
@PG-9-9 hi there,

It seems that you are encountering an issue related to the `utils` module while implementing DeepSort_YOLOv5_Pytorch in your project. The error message indicates that the `utils` module is not being found, which could potentially be a result of changes in the YOLOv5 repository.

The `utils` module is an internal part of the YOLOv5 codebase and is expected to be available within the repository. I recommend checking the `DeepSort_YOLOv5_Pytorch` repository for any specific requirements or modifications to the YOLOv5 codebase.

It's possible that the structure or dependencies of the YOLOv5 repository may have been updated, causing the issue you're facing. In addition, ensure that the YOLOv5 repository is correctly cloned within your project directory and that you are using the appropriate version specified by `DeepSort_YOLOv5_Pytorch`.

If you need further assistance, I recommend reaching out to the developers of the `DeepSort_YOLOv5_Pytorch` repository for guidance on integrating YOLOv5 with DeepSort.

Lastly, I'd like to express my appreciation for your interest in the YOLOv5 project and the community's support. Your feedback and collaboration are invaluable to us.

Best of luck with your implementation, and don't hesitate to ask if you need further assistance!
