### ISSUE TITLE
Folder YOLOv5 does not appear in the directory after its installation.

### ISSUE THREAD

**Issue by frl93** [ultralytics/yolov5#12418]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi everybody!

I am new with the use of Yolov5 tool. I have followed the steps indicated in the webpage for yolov5 installation in my laptop.

![Captura](https://github.com/ultralytics/yolov5/assets/148674315/b817b831-caf1-4610-a93c-376d3c68fdc3)

And the docker has properly installed as you can see the container in the docker desktop application.
![image](https://github.com/ultralytics/yolov5/assets/148674315/9a78781e-7fe3-46cf-ba14-e768536bf5c6)

However, when I have checked if the folder was created in my local directory root no "Yolov5" folder appears. I have followed similar steps for other dockers such as cvat, where you can see that the foder was properly created.

![image](https://github.com/ultralytics/yolov5/assets/148674315/56c1d36b-d07d-4c04-a046-f9527c98ebdd)

And CVAT folder contains the typical structure of a docker
![image](https://github.com/ultralytics/yolov5/assets/148674315/bd244a44-5eff-44a7-bd9c-7b6e9ffdc411)

Is there any step that I do not follow properly? Do I need to do something else to finish with the installation of yolov5 ?

**Comment by glenn-jocher** [comment]
@frl93 hi there! It seems like there might be some confusion with the YOLOv5 installation. YOLOv5 is not typically installed as a Docker container, so I suspect that may be the issue here. 

Did you follow the installation guide from our YOLOv5 documentation at https://docs.ultralytics.com/yolov5/ ? The installation steps there should help you set up YOLOv5 properly on your laptop.

Let me know if you have any further questions or need assistance with the installation process!

**Comment by frl93** [comment]
Hi once again @glenn-jocher!

If you are asking me if I have followed this steps: 
![image](https://github.com/ultralytics/yolov5/assets/148674315/97bfcdfe-1a9d-4c5e-890f-2e6e52b7530d)
Te answer is NO. Where I have done, as you can see in the first image of my previous comment, is first applied this command:
![image](https://github.com/ultralytics/yolov5/assets/148674315/adb60cdf-bc56-411c-a33d-5a82fd755a11)
And then, I have selected the gpu option with this command: 
![image](https://github.com/ultralytics/yolov5/assets/148674315/96ac84d7-951e-4506-a748-c4736fbab9a7)

May be I have not followed properly the installation steps and before applying "sudo docker pull ultralytics/yolov5:latest" I must install Yolov5 with the steps of the picture that I show in this comment? In this case do I need to delete the docker container that has been created in my docker desktop application?

**Comment by glenn-jocher** [comment]
@frl93 Thanks for providing the additional details. It looks like there might be some confusion with installing YOLOv5 using Docker. The steps you've followed are indeed for setting up YOLOv5 within a Docker container, however, it seems like you may have missed some crucial setup steps.

To clarify, if you want to use YOLOv5 via Docker, you should follow the steps outlined in the YOLOv5 documentation you shared first to set up the necessary environment and then use the Docker command you mentioned earlier.

You can remove the previous Docker container and then follow the YOLOv5 documentation steps to properly set up the environment before using the Docker command.
Let me know if you need any further assistance!

**Comment by enislalmi** [comment]
@frl93 if you want to use via Docker, create the Dockerfile in your project and specify the image of yolov5 like this:
```
FROM ultralytics/yolov5:latest

#Give the work directory a name
WORKDIR /app

COPY . /app

CMD ["python", "train.py"]
```

and then you can check the training directly after performing `docker build --tag "yolov5-image" .` and then `docker run `respectively

**Comment by frl93** [comment]
Hi @enislalmi!

Thanks for your comment. I have a copule of questions related to it:
  1. I am not very familiarized with the dockers as I have started to work with them a month ago. Where can I create the Dockerfile that you have mentioned
  2. Where do I have to specify the image of yolov5 in the file that you have tell me.

In addition, I have another trouble. The following picture shows my Docker Desktop at Windows, and you can see that I have a yolov5 image stopped. 
![image](https://github.com/ultralytics/yolov5/assets/148674315/a0e83ead-99d2-40ec-8f96-f3bb937504ac)

If I applied the command: "docker run --ipc=host -it --gpus all --name fermin_yolo5 ultralytics/yolov5:latest". It tells me that the container already exists.
![image](https://github.com/ultralytics/yolov5/assets/148674315/f8b8ecd4-9959-4c72-ab3b-497344f1f579)

Can you tell my which is the command that I need to apply to activate once again that image.

Thanks!

**Comment by frl93** [comment]
Hi everybody!

I have been able to up the docker and get inside it to make the desired predictions. 

To up the docker you must use: docker start <container_name>, in my case "fermin_yolo5"
To get inside the container once it is in "run" mode, you must use: docker exec -it <container_name> bash

Thanks!

**Comment by glenn-jocher** [comment]
@frl93 glad to hear you got the Docker up and running! If you encounter any further questions or run into any issues, feel free to ask. Good luck with your predictions!
