### ISSUE TITLE
yolov5 model export

### ISSUE THREAD

**Issue by Neloy262** [ultralytics/yolov5#12427]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

There are two arguments for model export, dynamic and simplify. What do they mean?

**Comment by glenn-jocher** [comment]
@Neloy262 the "dynamic" argument in model export enables ONNX dynamic axes, aiming to optimize model size. The "simplify" argument strips out optional ERT components for iOS deployment. For more details, you can refer to our [Ultralytics Docs](https://docs.ultralytics.com/yolov5/).
