### ISSUE TITLE
Cannot copy from a TensorFlowLite tensor (Identity) with shape [1, 6, 8400] to a Java object with shape [1, 80, 80, 21].

### ISSUE THREAD

**Issue by HoangBee102** [ultralytics/yolov5#12426]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Cannot copy from a TensorFlowLite tensor (Identity) with shape [1, 6, 8400] to a Java object with shape [1, 80, 80, 21].
Help me fix this error for my app, pls!

**Comment by glenn-jocher** [comment]
@HoangBee102 this error indicates a shape mismatch between the TensorFlowLite tensor and the Java object. To resolve this, ensure that the output format of the model matches the input requirements of your application. You might need to reshape or transpose the tensor accordingly. Check the model's output configuration and the input expectations of your Java object for compatibility.

If you need further assistance, consider sharing additional details about your inference pipeline, including the model configuration and relevant code snippets.

For comprehensive information on YOLOv5 usage, refer to the Ultralytics Docs at https://docs.ultralytics.com/yolov5/.

**Comment by HoangBee102** [comment]
`public void setInput(Bitmap resizedbitmap){
        boolean quantized_mode = TfliteRunMode.isQuantizedMode(this.runmode);
        int numBytesPerChannel = quantized_mode ? numBytesPerChannel_int : numBytesPerChannel_float;
        ByteBuffer imgData = ByteBuffer.allocateDirect(1 * inputSize * inputSize * 3 * numBytesPerChannel);

        int[] intValues = new int[inputSize * inputSize];
        resizedbitmap.getPixels(intValues, 0, resizedbitmap.getWidth(), 0, 0, resizedbitmap.getWidth(), resizedbitmap.getHeight());

        imgData.order(ByteOrder.nativeOrder());
        imgData.rewind();
        for (int i = 0; i < inputSize; ++i) {
            for (int j = 0; j < inputSize; ++j) {
                int pixelValue = intValues[i * inputSize + j];
                if (quantized_mode) {
                    // Quantized model
                    imgData.put((byte) ((pixelValue >> 16) & 0xFF));
                    imgData.put((byte) ((pixelValue >> 8) & 0xFF));
                    imgData.put((byte) (pixelValue & 0xFF));
                } else { // Float model
                    float r = (((pixelValue >> 16) & 0xFF)) / 255.0f;
                    float g = (((pixelValue >> 8) & 0xFF)) / 255.0f;
                    float b = ((pixelValue & 0xFF)) / 255.0f;
                    imgData.putFloat(r);
                    imgData.putFloat(g);
                    imgData.putFloat(b);
                }
            }
        }
        this.inputArray = new Object[]{imgData};
        this.outputMap = new HashMap<>();
        outputMap.put(0, this.rawres.out1);
        outputMap.put(1, this.rawres.out2);
        outputMap.put(2, this.rawres.out3);
    }`

My custom train has 2 class, model export from ultralytic hub .tflite
Model in netron app: ![image](https://github.com/ultralytics/yolov5/assets/58972899/7afe64ac-2577-466f-b0f0-a7f86e010ae5)

Model in demo app work fine: 
![image](https://github.com/ultralytics/yolov5/assets/58972899/a48585c2-fa9d-4bfd-ad30-1d9f38e8e169)

Author say me: 

> I think you don't follow this instruction. https://github.com/lp6m/yolov5s_android/tree/master/convert_model#onnx---openvino 

Pls help me howto fix???

**Comment by glenn-jocher** [comment]
@HoangBee102 i see that you're trying to use a custom YOLOv5 model in a demo app, and it seems you are facing some issues related to the model input and output configurations. It's important to ensure that the input preprocessing in your custom code matches the input requirements of the model and the post-processing matches the model's output format.

It looks like there might be a discrepancy between the input processing in your code and the model's expected input format. 

Regarding the author's suggestion, it would be helpful to review the instruction link provided and confirm if the conversion steps have been followed accurately.

For comprehensive guidance on using custom YOLOv5 models, including input preprocessing and output post-processing, I recommend referring to the Ultralytics Docs at https://docs.ultralytics.com/yolov5/.

Feel free to provide additional details or code snippets if you need further assistance.

**Comment by hyunjincho84** [comment]
@HoangBee102  did you sloved the problem?
