### ISSUE TITLE
How to save images with bounding box?

### ISSUE THREAD

**Issue by unrue** [ultralytics/yolov5#12423]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I successfully trained a Yolov5 model on custom dataset, and also successfully ran inference. Now, I would like to save images with predicted bounding boxes in the following way:

```
img_list = os.listdir(input_inference_dir)
num_images = len(img_list)
res_list = []

# Images
for i in range(num_images):
    im = cv2.imread(input_inference_dir+'/'+img_list[i])
    results = model(im)
    res_list.append(results)

try:
    for i in range(num_images):
        print("Image: ", img_list[i])
        res_list[i].xyxy[0]  
        print(res_list[i].pandas().xyxy[0])  
        image = res_list[i].render()
        cv2.imwrite("image"+str(i)+".jpg",image)
except cv2.error as e:
      print("Error: ", e)
```

The problem is I don't see any output  images in the current folder and also no error from cv2.   res_list[i] contain predictions correctly instead. I'm doing something wrong with result render? Thanks.

**Comment by glenn-jocher** [comment]
@unrue ```python
Looking good! To save images with bounding boxes, use the `results.render()` method. Remove the line `res_list[i].xyxy[0]` and replace `cv2.imwrite("image"+str(i)+".jpg",image)` with `results.render().save("image"+str(i)+".jpg")`. This should resolve your issue. Happy coding!
```

**Comment by unrue** [comment]
Thanks Glenn,

the code you suggest get the following error:

`yolov5 render TypeError: 'Detections' object is not subscriptable`

I solved using save without render()

**Comment by glenn-jocher** [comment]
@unrue glad to hear you were able to resolve the issue! The `save()` method is indeed the way to go for saving images with bounding boxes. Let me know if there's anything else I can help with. Good luck with your project!
