### ISSUE TITLE
Polygraphy compares the output of onnx and TensorRT engine is inconsistent

### ISSUE THREAD

**Issue by JensenGao** [ultralytics/yolov5#12433]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I used the following command to export the onnx model：
```
python export.py --weights $PT_MODEL --include onnx --img 640 --device 0 --simplify --opset 13 --batch-size 1
```
and，Then use the Polygraphy(https://github.com/NVIDIA/TensorRT/tree/main/tools/Polygraphy) tool to compare onnx and engine. The command is as follows
```
polygraphy run yolov5s.onnx --onnxrt --trt --pool-limit workspace:1G --save-engine yolov5s.plan --atol 1e-3 --rtol 1e-3 --fp16 --verbose --onnx-outputs mark all --trt-outputs mark all
```
The output of the two models (onnx and engine compare in fp16) only **PASSED** the comparison of model.0, and the rest **FAILED**.
In addition, when comparing with FP32, the output of all layers **PASSED** and the same thing happens with yolov5-seg models.
There is not much difference MAP between  two models
**Here is my log:**
[yolov5s_640.txt](https://github.com/ultralytics/yolov5/files/13468808/yolov5s_640.txt)
[yolov5s_640_fp32.txt](https://github.com/ultralytics/yolov5/files/13468810/yolov5s_640_fp32.txt)
[yolov5s-seg_640.txt](https://github.com/ultralytics/yolov5/files/13468811/yolov5s-seg_640.txt)
[yolov5s-seg_640_fp32.txt](https://github.com/ultralytics/yolov5/files/13468813/yolov5s-seg_640_fp32.txt)
​

**Comment by glenn-jocher** [comment]
@JensenGao thanks for reaching out! 👋 The YOLOv5 team appreciates your detailed analysis. It's likely a technical nuance and I recommend exporting the ONNX model with the same optimization settings used during the TensorRT conversion. Also, consider checking the NVIDIA TensorRT compatibility and validating the ONNX outputs with a trusted ONNX runtime such as ONNX Runtime, MXNet, or OpenVINO. If the issue persists, feel free to follow up or refer to our [Ultralytics Docs](https://docs.ultralytics.com/yolov5/) for further guidance. Good luck!

**Comment by JensenGao** [comment]
> @JensenGao thanks for reaching out! 👋 The YOLOv5 team appreciates your detailed analysis. It's likely a technical nuance and I recommend exporting the ONNX model with the same optimization settings used during the TensorRT conversion. Also, consider checking the NVIDIA TensorRT compatibility and validating the ONNX outputs with a trusted ONNX runtime such as ONNX Runtime, MXNet, or OpenVINO. If the issue persists, feel free to follow up or refer to our [Ultralytics Docs](https://docs.ultralytics.com/yolov5/) for further guidance. Good luck!

Thanks for your reply, I'll try it again.

**Comment by glenn-jocher** [comment]
@JensenGao you're welcome! If you have any further questions or encounter any issues, feel free to reach out. Good luck with your testing, and have a great day!
