### ISSUE TITLE
tif: ignoring corrupt image/label: cannot identify image file

### ISSUE THREAD

**Issue by wq247726404** [ultralytics/yolov5#12437]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I used my own saved tif file to train in YOLOV5 and got the topic to report an error. 
dataloaders.py :
       else:
            # Read image
            self.count += 1
            # im0 = cv2.imread(path)  # BGR
            im = tifffile.imread(path)
            im0 = np.transpose(im, (1, 2, 0))
            assert im0 is not None, f'Image Not Found {path}'
            s = f'image {self.count}/{self.nf} {path}: '
tif creation code is shown in Figure
![image](https://github.com/ultralytics/yolov5/assets/40755124/5b75a78c-1b5d-4567-9074-23d6825612c2)

**Comment by glenn-jocher** [comment]
@wq247726404 thanks for reaching out! It seems like your TIF image might be corrupt or incompatible. You could try re-saving the TIF file or ensuring it's in a compatible format for YOLOv5.

Also, the image link provided seems to be broken. If you have any further questions or need assistance, feel free to ask!

**Comment by wq247726404** [comment]
> @wq247726404 thanks for reaching out! It seems like your TIF image might be corrupt or incompatible. You could try re-saving the TIF file or ensuring it's in a compatible format for YOLOv5.
> 
> Also, the image link provided seems to be broken. If you have any further questions or need assistance, feel free to ask!

Thank you!The picture information is:
for file_name in os.listdir(folder_path):
    if file_name.endswith('.jpg'):
        # Extract the numerical part of the RGB image name
        rgb_number = int(os.path.splitext(file_name)[0])

        # Construct the full paths for the RGB image and flow file
        rgb_path = os.path.join(folder_path, file_name)
        flow_number = rgb_number + 2
        flow_name = f"{flow_number}.flo"
        flow_path = os.path.join(folder_path, flow_name)

        # Read the RGB image
        rgb_image = cv2.imread(rgb_path)

        # Open the optical flow file and read data
        with open(flow_path, 'rb') as flow_file:
            width, height = rgb_image.shape[1], rgb_image.shape[0]
            data = np.fromfile(flow_file, np.float32, count=2*width*height)
            flow = data.reshape((height, width, 2)).astype(np.float16)

        # Combine the RGB image and the optical flow data
        merged_image = np.dstack((rgb_image, flow))
        merged_image1 = np.transpose(merged_image,(2, 0, 1))

        # Save the merged image as a TIFF file
        output_path = os.path.join(folder_path, f"{rgb_number}.tif")
        tifffile.imsave(output_path, merged_image1)
