### ISSUE TITLE
Multiple Streams

### ISSUE THREAD

**Issue by AbhishekPSI7042** [ultralytics/yolov5#12439]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Failed to set tensor. Check 'is_dynamic || port.get_shape() == tensor->get_shape()' failed at src\inference\src\dev\isync_infer_request.cpp:280:
The input tensor size is not equal to the model input type: got [2,3,384,384] expecting [1,3,384,384].

I'm getting this error when I pass two streams at same time through .streams file. In my .streams file I have two rtsp camera ip would you tell me why I'm getting this error.

rtsp://admin:admin@192.168.0.24
rtsp://admin:admin@192.168.0.25

And when I'm passing only one camera link it is working.

**Comment by glenn-jocher** [comment]
@AbhishekPSI7042 hello! It seems like you're trying to process multiple streams simultaneously, but the model is expecting a single input stream at a time (batch size of 1). The error indicates that the input tensor shape does not match the expected shape.

YOLOv5 is designed to process one batch at a time, where a batch can consist of multiple images. However, the batch size and the input resolution must match the model's configuration. If you want to process multiple streams, you need to ensure that each stream is processed in a separate batch or adjust the batch size accordingly if the model and hardware support it.

For handling multiple streams, you might consider running separate inference processes for each stream or modifying the code to support batch inference if you're familiar with PyTorch and the YOLOv5 codebase.

For more detailed guidance on how to work with streams and batches, please refer to our documentation at https://docs.ultralytics.com/yolov5/.

Keep in mind that processing multiple streams can be resource-intensive, and you'll need to ensure your hardware can handle the load. Good luck! 😊
