### ISSUE TITLE
Can somebody help me to understan why me GPU does not work with yolov5?

### ISSUE THREAD

**Issue by frl93** [ultralytics/yolov5#12435]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi to everbody!

I have followed this steps to install the docker image of the yolov5. First, I run this command in the WSL

![image](https://github.com/ultralytics/yolov5/assets/148674315/9cc19669-5871-4cb9-91dc-9bc30557b959)

Then, I run this command for being able to share a volume of my local laptop with the docker container that I created with "fermin-yolo5" name,

xhost +
sudo docker run -it --gpus all --name fermin-yolo5 \
	-e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix \
	--ipc=host --volume="$HOME/.Xauthority:/root/.Xauthority:rw" \
	--net=host \
	-v /mnt/c/Users/18805/Yolo5:/host \
   	ultralytics/yolov5:latest bash

As you can see in the following picture, the docker has been perfectly created in the Docker Desktop application.
![image](https://github.com/ultralytics/yolov5/assets/148674315/0a1470de-eb2f-4db3-af16-2ea317741f92)

However, as you can see in previous image, when I ask to the docker to do a train with this command,

python3 train.py --batch 8 --epochs 150 --data data/yolo_data.yaml --cfg models/yolov5s.yaml

Instead of work with the GPU it uses the CPU. Therefore, it takes much more time to do the train of the model.

Cheking the administrator panel (next picture), I have seen that I have two GPU.
![image](https://github.com/ultralytics/yolov5/assets/148674315/e687bd6c-3acc-41ca-8211-880a8a717a52)

If I try this command "python3 train.py --batch 8 --epochs 150 --data data/yolo_data.yaml --cfg models/yolov5s.yaml --device 0" it uses the CPU.

However, If I type this command "python3 train.py --batch 8 --epochs 150 --data data/yolo_data.yaml --cfg models/yolov5s.yaml --device 1" The following error appears.
![image](https://github.com/ultralytics/yolov5/assets/148674315/8f21c2ad-3497-4bd3-a298-9a09c54db0f2)

I wolud be gratefull if somebody can help me.

Thanks.

PD: The [NVIDIA Container Toolkit](https://github.com/NVIDIA/nvidia-container-toolkit) was properly installed as it was a requirement for the installation of CVAT application. CVAT application is used for annotation purposes.

**Comment by glenn-jocher** [comment]
@frl93 hi there!

It looks like the GPU may not be properly enabled inside the Docker container. 🐳 You can check out our docs at https://docs.ultralytics.com/yolov5/ for detailed instructions on setting up YOLOv5 with Docker and GPU support.

Cheers!

**Comment by frl93** [comment]
Hi @glenn-jocher 

I have reinstalled the docker and the issue still continues. As you can see in the image I have 12 GB in the GPU but it only uses 3.5 of them. 
![image](https://github.com/ultralytics/yolov5/assets/148674315/39c58cef-772d-44dc-98a8-d31c5ab1fe20)

As you can see in the next image, it still continues using the CPU, when I forced it ti use the GPU through the command --device 0. "python3 train.py --batch 8 --epochs 150 --data data/yolo_data_sin_v.yaml --cfg models/yolov5s.yaml --devide 0"

![image](https://github.com/ultralytics/yolov5/assets/148674315/5fadffef-43c8-408c-a3ea-9c7389303b44)

If I increased the batch more than 11, the CPU reaches to 100% and the command aborts with the following advice.

![image](https://github.com/ultralytics/yolov5/assets/148674315/b47f2c2b-74ca-44a3-9bbb-644fac65a056)

**Comment by glenn-jocher** [comment]
@frl93 Looks like there might be a configuration issue with your environment. We recommend checking out our exhaustive documentation at https://docs.ultralytics.com/yolov5/ for troubleshooting tips and setting up YOLOv5 with Docker and GPU support.

Hope this helps!
