### ISSUE TITLE
video save

### ISSUE THREAD

**Issue by Abhi-prasad7042** [ultralytics/yolov5#12430]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is there any way that I can stop saving the video after detection. Because whenever I gave a video to my yolov5 model using detect.py it also saves the result video I don't want that could anyone please help me out?

**Comment by glenn-jocher** [comment]
@Abhi-prasad7042 you can disable the video save feature by setting the argument `--nosave` while running `detect.py`. This will prevent the output video from being saved. For more details on the available command-line arguments, please refer to the [Ultralytics Docs](https://docs.ultralytics.com/yolov5/).
