### ISSUE TITLE
How do I reference train.py in another py file and how do I set its parameters?

### ISSUE THREAD

**Issue by AFallDay** [ultralytics/yolov5#12434]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How do I reference train.py in another py file and how do I set its parameters? thanks
I tried this way under the graph, but when calling the train it calls another train.
![image](https://github.com/ultralytics/yolov5/assets/144637847/a7bc8291-dbb4-42d2-9a39-aeb7751b0f2e)
![image](https://github.com/ultralytics/yolov5/assets/144637847/d31867aa-374b-42cd-8ea2-cf01d2154a05)

**Comment by glenn-jocher** [comment]
@AFallDay you can reference train.py in another file with the following code:
```python
from train import *
```
You can set its parameters by modifying the parser options or using flags like `--batch-size`, `--epochs`, etc. For detailed guidance, refer to the Ultralytics Docs at https://docs.ultralytics.com/yolov5/. 🚀

**Comment by AFallDay** [comment]
> @AFallDay you can reference train.py in another file with the following code:
> 
> ```python
> from train import *
> ```
> 
> You can set its parameters by modifying the parser options or using flags like `--batch-size`, `--epochs`, etc. For detailed guidance, refer to the Ultralytics Docs at https://docs.ultralytics.com/yolov5/. 🚀

I've tried this approach, but it calls the train function under another file, not the train function under train.py.

**Comment by enislalmi** [comment]
You can run it directly from the Terminal using `python train.py --data path/to/your_yml_file.yml --weights yolov5s.pt --batch_size 64` and whatever other parameters you want to configure. Make sure you are in the right directory when calling this command.

**Comment by glenn-jocher** [comment]
@enislalmi absolutely, to run `train.py` from the Terminal, use:

```bash
python train.py --data path/to/your_yml_file.yml --weights yolov5s.pt --batch_size 64
```

Be sure to execute this command from the correct directory. Let me know if you need further assistance!

**Comment by brandon-hastings** [comment]
Looking at the train.py file, it appears that you can call `train.run()` within a Python file and set the parameters like so:

```
from yolov5 import train
train.run(data=path/to/your_yml_file.yml, weights=yolov5s.pt, batch_size=64)
```

It sounds like this may be what you are looking for. I installed yolov5 directly via pip if that is important.

**Comment by glenn-jocher** [comment]
@brandon-hastings I appreciate your input! Your suggested approach is indeed another way to call `train.py` functionality from within a Python file. Your installation method is also relevant – thanks for pointing that out. Feel free to refer to the Ultralytics Docs at https://docs.ultralytics.com/yolov5/ for more information. Keep up the great work! 🌟

**Comment by animeesh** [comment]
> Looking at the train.py file, it appears that you can call `train.run()` within a Python file and set the parameters like so:
> 
> ```
> from yolov5 import train
> train.run(data=path/to/your_yml_file.yml, weights=yolov5s.pt, batch_size=64)
> ```
> 
> It sounds like this may be what you are looking for. I installed yolov5 directly via pip if that is important.

this doesn't work, its give me error like freeze_support() and terminal doesn't stops its continuously repete the same thing in a loop

**Comment by glenn-jocher** [comment]
Hi @animeesh,

Thank you for your detailed input! It sounds like you're encountering an issue with the `freeze_support()` error, which is typically related to multiprocessing on certain platforms, especially Windows.

To help us investigate further, could you please provide a minimum reproducible example of your code? This will allow us to better understand the context and reproduce the issue on our end. You can find more information on creating a minimum reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please ensure that you are using the latest versions of `torch` and `yolov5` from the official repository. You can upgrade your packages with the following commands:

```bash
pip install --upgrade torch
pip install --upgrade git+https://github.com/ultralytics/yolov5.git
```

Once you've updated your packages, try running your script again. If the issue persists, please share the exact error message and any relevant code snippets.

Here's a quick example of how you might structure your script to avoid multiprocessing issues:

```python
if __name__ == "__main__":
    from yolov5 import train
    train.run(data='path/to/your_yml_file.yml', weights='yolov5s.pt', batch_size=64)
```

This ensures that the `train.run()` function is only called when the script is executed directly, which can help prevent multiprocessing-related errors.

Looking forward to your response so we can assist you further!
