### ISSUE TITLE
how to add new branch to the backbone

### ISSUE THREAD

**Issue by dusongjie** [ultralytics/yolov5#12449]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to add a branch to the YOLOv5 backbone network, and how to write yaml files？

**Comment by glenn-jocher** [comment]
@dusongjie hi there! Thanks for reaching out. To add a branch to the YOLOv5 backbone network, you can modify `models/common.py` and the corresponding `yaml` file in `models/yaml`. You can find detailed guidance in the YOLOv5 documentation [here](https://docs.ultralytics.com/yolov5/). Let me know if you need further assistance! 🚀

**Comment by dusongjie** [comment]
When I modify the yaml file, because the input image is to be passed into two branches, one is its own backbone, and one is my own design module, I use - [-1, 1, CFEM, [1024]] #0
- [-2, 1, Conv, [64, 3, 2]] # 1 Is it possible to input the original image into two modules, and how should it be implemented
![image](https://github.com/ultralytics/yolov5/assets/43609987/7faf5a88-bf6a-4188-bfe0-75821dbb8abf)

**Comment by glenn-jocher** [comment]
@dusongjie It is possible to feed the original image into two modules by specifying the desired connection points in the `yaml` file. You can utilize the `-1` and `-2` indices to connect to previous layers in the backbone. For example, `-1` corresponds to the previous layer, and `-2` corresponds to the second previous layer. The diagram you provided illustrates this nicely. If you have further questions or need additional assistance, feel free to ask! 👍

**Comment by dusongjie** [comment]
![image](https://github.com/ultralytics/yolov5/assets/43609987/92e23277-b70b-4095-bfca-1573097c6cee)
I tried -1 for the original image on the zeroth layer of the network and -2 for the original image on the first layer of the network, but I got an error:
![image](https://github.com/ultralytics/yolov5/assets/43609987/eb11a284-879b-439e-9eba-c9033e4e5402)

**Comment by glenn-jocher** [comment]
@dusongjie It seems you are encountering an error when attempting to connect the original image to multiple modules using `-1` and `-2`. It's important to note that individual layer indices for input connection must be within the range of network layers, and -1 and -2 are reserved for connecting to previous layers, not the input image. You may need to customize the backbone architecture to achieve the desired input connection to multiple modules. If you need specific guidance on this customization, please let me know, I'd be happy to assist further!

**Comment by dusongjie** [comment]
@glenn-jocher Thank you very much,can you teach me how to customize the backbone architecture in order to feed the input image to two modules.

**Comment by glenn-jocher** [comment]
@dusongjie You're welcome! Customizing the backbone architecture to feed the input image to two modules involves modifying the network structure. You would need to define the connections for the input image in the model's `forward` method and adjust the `yaml` file accordingly. To provide more detailed guidance, I'd recommend referring to the YOLOv5 documentation [here](https://docs.ultralytics.com/yolov5/) for instructions on customizing the architecture. Should you encounter any issues or have further questions during the customization process, feel free to ask for help, and I'll be happy to assist you further! Good luck! 👍

**Comment by dusongjie** [comment]
@glenn-jocher I am sorry that I could not get the information about modifying the network structure in the documentation you recommended. How can I define model's forward method for the input image? Thanks again for your reply.

**Comment by glenn-jocher** [comment]
@dusongjie I apologize for the confusion. To define the model's `forward` method for the input image, you can customize the backbone architecture by directly modifying the `models/common.py` file. Within the `forward` method, you can specify the connections for the input image to be fed into multiple modules as per your requirement. Unfortunately, due to the character limitation here, I'm unable to provide a detailed code example. However, you can refer to the YOLOv5 documentation [here](https://docs.ultralytics.com/yolov5/) for general guidance, or seek further assistance on specific code implementation in the YOLOv5 discussion forum. If you encounter any specific issues during this process, please feel free to reach out for further assistance!
