### ISSUE TITLE
How to print/save all the IoU values for each image after running detect.py?

### ISSUE THREAD

**Issue by dudas-tamas** [ultralytics/yolov5#12444]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi guys!

I need some help with the IoU values in YOLOv5.
I got a good performer model based on statistics/metrics and I would really like to know the IoU values of each image after running detect.py. I see all the images and bboxes at runs/detect/expX but I'd like to make a statistics based on the IoUs.
Can someone help and show me where I have to search for it in the code please? :)

Side info:
I run detect.py like this: python /.../.../code/yolov5/detect.py --source /.../.../.../.../.../GT_test/ --line-thickness 1 --weights /.../.../.../yolov5/runs/train/exp156/weights/best.pt --max-det 1 --device 1 --imgsz 400

Thanks in advance!

**Comment by glenn-jocher** [comment]
@dudas-tamas hi there! 👋 Currently, YOLOv5 doesn't print or save IoU values after running detect.py. If you're interested in computing IoU for each detection, I recommend modifying the source code in detect.py to include this feature. You might find helpful functions for this in models/experimental and utils directories. Good luck and thank you for your support! 🚀

**Comment by dudas-tamas** [comment]
Understood, thanks!

**Comment by glenn-jocher** [comment]
@dudas-tamas you're welcome! If you have any more questions or need further assistance, feel free to ask. 👍 We're here to help!

**Comment by dudas-tamas** [comment]
Is there any other way in YOLOv5 to find out the IoU values of the predictions? I was thinking that then it doesn't display the IoU values of the predictions, e.g. on the test set, even if I don't use detect.py? :)

**Comment by glenn-jocher** [comment]
@dudas-tamas Yes, you can calculate IoU values by accessing the bounding box coordinates and confidence scores from the model outputs (inference.py) and comparing them with the ground truth annotations. The `inference.py` file contains the post-processing logic where predictions are produced, making it a good place to start customizing IoU computation. You might also find the Ultralytics Docs useful for insights on model outputs and how to work with them. Good luck! 📦

**Comment by dudas-tamas** [comment]
Cool, thanks!

**Comment by dudas-tamas** [comment]
I did it!

if others are also interested in the details of the IoU, it should look something like this :) This is just one of many solutions, it could certainly be made nicer, but it worked for me :)

![image](https://github.com/ultralytics/yolov5/assets/80516986/8b557d66-5e51-4394-8cb5-5c805caabffd)

**Comment by glenn-jocher** [comment]
@dudas-tamas great work! It's fantastic to see you've found a solution. Your code snippet can definitely be helpful for others interested in IoU details. Keep up the good work and thanks for sharing your approach with the community! 🌟

**Comment by gameboy777x** [comment]
@dudas-tamas hi there! I also annotated the test-set with labelimg. I wonder how can I use your code to save the data results in batches? Thank you very much
