### ISSUE TITLE
Hello, detect.py does not support multi-GPU inference. How can I modify it to implement multi-GPU inference?

### ISSUE THREAD

**Issue by likecv** [ultralytics/yolov5#12452]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Hello, detect.py does not support multi-GPU inference. How can I modify it to implement multi-GPU inference?

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@likecv hello! For multi-GPU inference, you can use the `torch.nn.DataParallel` wrapper in `models/yolo.py`. This is a common PyTorch pattern 🔄 for parallelizing forward passes across multiple GPUs. For reference, you can find our YOLOv5 documentation at https://docs.ultralytics.com/yolov5/. Thank you!
