### ISSUE TITLE
How to save an image augmentations in YOLO-v5?

### ISSUE THREAD

**Issue by unikill066** [ultralytics/yolov5#12456]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am creating about 22 different image augmentations using the Albumentations class in YOLO-v5, utilizing a .hyp file. I want to save the images used during the YOLO training process to a particular filepath. In which file or function should I add the savefig() or imwrite() methods?

**Comment by glenn-jocher** [comment]
@unikill066 you can modify the `train.py` script found in the YOLOv5 repository to save the augmented images. 

You can find the data augmentation section in the `train.py` script and add the `savefig()` or `imwrite()` methods within the data loading section. 

For more details on the data augmentation process, you can refer to the official Ultralytics documentation at https://docs.ultralytics.com/yolov5/.

**Comment by unikill066** [comment]
@glenn-jocher, may you please suggest where exactly to add the changes, thanks!?

**Comment by glenn-jocher** [comment]
@unikill066 Sure! You can add the `savefig()` or `imwrite()` methods within the `train.py` script in the `datasets.py` file, specifically in the `LoadImagesAndLabels` class where the data loading and augmentation process occurs. This is the ideal location to access the images before they are fed into the training pipeline.

For more detailed guidance, you can refer to the YOLOv5 [documentation](https://docs.ultralytics.com/yolov5/).

**Comment by unikill066** [comment]
@glenn-jocher Thank you, I was able to save the training images by adding;
```
cv2.imwrite(os.path.join("/mnt/Working/neuron_detection/save_imgs", os.path.basename(label_path_sdjkbfadkjbfa).split('.')[0]+''.join(random.choice(string.ascii_letters + string.digits) for _ in range(20))
+'_.png'), img.transpose((1, 2, 0)))
```
in the `dataloaders.py` file; under `__getitem__` function in `LoadImagesAndLabels` class.

**Comment by unikill066** [comment]
@glenn-jocher Thank you, I was able to save the training images by adding;
```
import string, cv2, random

cv2.imwrite(os.path.join("/mnt/Working/neuron_detection/save_imgs", os.path.basename(label_path_sdjkbfadkjbfa).split('.')[0]+''.join(random.choice(string.ascii_letters + string.digits) for _ in range(20))
+'_.png'), img.transpose((1, 2, 0)))
```
in the `dataloaders.py` file; under `__getitem__` function in `LoadImagesAndLabels` class.

I'd like to know if there is a better way of doing it, say saving the images epoch-wise/per batch.

**Comment by glenn-jocher** [comment]
@unikill066 Great job on successfully saving the training images! Saving images epoch-wise or per batch is a good idea for tracking and analysis. You can achieve this by modifying the `train.py` script to include the saving functionality within the training loop, ensuring images are saved at the end of each epoch or batch.

Feel free to explore the Ultralytics YOLOv5 [documentation](https://docs.ultralytics.com/yolov5/) for more insights on training customization. The YOLOv5 community also provides additional examples and discussions that might be helpful. Keep up the good work!
