### ISSUE TITLE
Is it necessary to register buffer?

### ISSUE THREAD

**Issue by autograd500** [ultralytics/yolov5#12454]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

In __init__ function of class Detect , there are 2 lines codes:
```
self.register_buffer('anchors', a)  # shape(nl,na,2)--(3,3,2)
self.register_buffer('anchor_grid', a.clone().view(self.nl, 1, -1, 1, 1, 2))  # shape(nl,1,na,1,1,2)
```

In my opinion, the codes are to ensure that **'anchors'** and **'anchor_grid'** are not changed when gradient backpropagation. Am I right？

But, to ensure  **'anchors'** and **'anchor_grid'** are not changed， it seems like it's possible to do nothing？Because **'anchors'** and **'anchor_grid'** are not in the compute graph. It doesn't matter if you get rid of those two lines of code？

**Comment by glenn-jocher** [comment]
@autograd500 👋 Hi there! Thanks for reaching out. Yes, you're correct! The `register_buffer` lines effectively ensure that 'anchors' and 'anchor_grid' are not updated during gradient backpropagation. While 'anchors' and 'anchor_grid' aren't directly involved in the compute graph, using `register_buffer` is a best practice to handle non-trainable parameters like these. Indeed, if these lines were removed, the behavior should be the same in this case. Thanks for your interest!
