### ISSUE TITLE
Issue regarding false positive and false negative predicted images 

### ISSUE THREAD

**Issue by Raghunandan1234** [ultralytics/yolov5#12451]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

"I am attempting to categorize each image in the validation dataset as correct, false positive, or false negative for each class in my custom-trained model. How can I achieve this? The desired output is to have a folder structure where, for each class, there are folders for 'correct', 'false positive', and 'false negative' images. For example, if there are 2 classes, I expect 2 main folders, each containing subfolders for 'correct', 'false positive', and 'false negative' images related to that class. Is there a way to implement this?"

**Comment by glenn-jocher** [comment]
@Raghunandan1234 hi there! 🌟 To achieve this, you can first use the `detect` command to run inference on your validation dataset, then compare the predicted results with the ground truth labels using a custom script. You can find some helpful utilities for this task in the [Ultralytics Docs](https://docs.ultralytics.com/yolov5/), specifically under the `Inference` and `Custom Datasets` sections. Good luck!
