### ISSUE TITLE
MultiGPU evolve phase on HPC cluster

### ISSUE THREAD

**Issue by unrue** [ultralytics/yolov5#12455]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm running the evolve phase in Yolo5, trying to use 4 GPU in a HPC compute node. From the manual, I tried several ways, each attempt ends immediately doing nothing and with no errors:

First attempt:

```
`# Multi-GPU
for i in 0 1 2 3; do
  sleep $(expr 30 \* $i) &&  # 30-second delay (optional)
  echo 'Starting GPU '$i'...' &&
  nohup python train.py --epochs 10 --data coco128.yaml --weights yolov5s.pt --cache --device $i --evolve > evolve_gpu_$i.log &
done`

wait
```
Second attempt:
```
nohup sh -c '
for i in 0 1 2 3; do
    python train.py --epochs 10 --data coco128.yaml --weights yolov5s.pt --cache --device $i --evolve > evolve_gpu_$i.log &
done
' &

wait
```

Last attempt (Slurm on HPC cluster):

```
nohup sh -c '
for i in 0 1 2 3; do
    srun python train.py --epochs 10 --data coco128.yaml --weights yolov5s.pt --cache --device $i --evolve > evolve_gpu_$i.log &
done
' &

wait
```

Someone could explain me how to run multigpu evolve in such case? Single GPU works well. Thanks.

**Comment by glenn-jocher** [comment]
@unrue you can use the `--evolve` flag with multi-GPU by setting the `--device` to all GPUs (e.g. `--device 0,1,2,3`). Additionally, it seems there's an issue with the `nohup` command in the provided commands, consider using `bash -c` instead.

For more details, refer to the "Train/Evolve" section at https://docs.ultralytics.com/yolov5/ 🚀

**Comment by unrue** [comment]
Thanks Glenn, is running. The only warning I get is:

`WARNING ⚠️ DP not recommended, use torch.distributed.run for best DDP Multi-GPU results.`

But torch.distributed.run is not compatible with evolve phase, I gen an error. So, it is correct using it in same way? Thanks

**Comment by glenn-jocher** [comment]
@unrue glad to hear it's running! The warning message suggests using `torch.distributed.run` for optimal DDP multi-GPU results. However, for the evolve phase, using `--device` as mentioned earlier is the correct approach. This warning can be bypassed for the evolve command. Thanks!

**Comment by unrue** [comment]
Hi Glenn, update:

I'm running two evolve phase using 1 GPus and 4: After 13 hours, both have executed 20 generations. How is that possible? I expected multigpu ran more generations. Is really a multigpu evolving ?

Thanks.

**Comment by glenn-jocher** [comment]
@unrue Each GPU trains independently during the evolve phase, potentially leading to varying completion times based on the complexity of the generations. To ensure thorough testing, kindly confirm proper results with single and multi-GPU setups. Thanks!

**Comment by unrue** [comment]
So, in such case, 20 generations are referred to each GPU? So, the total of generations, I mean, the total of hyperparameter combinations tested are 80? I see just one hyp_evolve.yaml file in evolve directory. I expected one file for GPU. Or automatically is overrided each time better configuration is found?

**Comment by glenn-jocher** [comment]
@unrue Correct, each GPU evaluates different hyperparameter combinations, resulting in a total of 80 combinations for 4 GPUs. The hyp_evolve.yaml file is used to store the best hyperparameters found, and it is automatically updated with each iteration, replacing the previous values. Thanks!
