### ISSUE TITLE
Reduce false positive 

### ISSUE THREAD

**Issue by adarshksudarsan** [ultralytics/yolov5#12467]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question
@glenn-jocher 
I trained a yolov5n model for 2 class person and vehicle
the dataset used was coco > extracted person class from coco and gave it as class 0 then took car, bus, and truck from coco dataset and gave it as class 1(used every image that contains person or vehicle or both from the dataset, so the class balance is not good majority contains person, to be exact person >262465  and vehicle >59909)
The problem I am facing is water bottles chairs etc are detected as a person with more than 50% confidence.
but I can't increase the threshold by more than 50% because it affects the detection of smaller people who are far from the camera.
Is there any solution to overcome this?

**Comment by glenn-jocher** [comment]
@adarshksudarsan hi there! 👋 To reduce false positives, you could try augmenting your dataset to include more diverse examples of the person and vehicle classes. Additionally, experimenting with different training strategies like focal loss or class balancing may also help. Check out the Ultralytics Docs for more tips on optimizing your model's performance. Good luck!
