### ISSUE TITLE
NMS on multi streaming Inputs

### ISSUE THREAD

**Issue by b4u365** [ultralytics/yolov5#12461]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi Team,

Thanks for your Great Efforts,

I am doing multi streaming with yoloV5 and using this command python detect_ir_vi.py --source streams.txt. Here yolov5 takes two images as inputs from two different cameras capturing same scene, here the images are aligned (object will be at same postion on both the images). Can we run the NMS on both the images simultaneous and assign or plot the biggest confidence score on both, Meaning both the images have same highest confidence score.

Can you help in this.

Your help will be of great value to me.

Thanks and Regards,
Bharath.

**Comment by glenn-jocher** [comment]
@b4u365 hi Bharath,

Thanks for the kind words! 😊 YOLOv5 currently processes each image in isolation, so simultaneous NMS across multiple images isn't supported. However, after running inference on both images, you can compare the results and select the highest confidence score for plotting. 📷📷

If you have any more questions, feel free to ask. Keep up the great work!

**Comment by b4u365** [comment]
Thank you so much for your feedback i could able to achieve the above issue by post processing.

I am using multi streaming detection with two cameras simultaneously with help of command  
python detect_ir_vi.py --source streams.streams. 
This command can detect both the objects in both the  cameras.
How one network, can detect both the objects simultaneously. can you brief me. 
or my guess is that,  detections are happening in series rather than parallel/ simultaneous, but the detection rate is so fast that we feel both are live/Simultaneous, am I correct ?

Your reply is of great value to me.

**Comment by glenn-jocher** [comment]
@b4u365 glad to hear you were able to achieve the desired result with post-processing! 👍

In YOLOv5, while the detections are indeed processed serially, the high speed of the network enables real-time inference on multiple streams, creating the perception of simultaneous detection. This is due to the efficient design and parallel processing capabilities of the model.

Keep up the great work, and feel free to ask if you have more questions!

**Comment by b4u365** [comment]
Hey Thank you so much for you reply.

can you help in this: I want to feed NMS with two bounding box data, for example let us consider

bbox1 which consist of two detections with cam1 
[0 0.919531 0.266602 0.0671875 0.166016 0.576993
0 0.75 0.290039 0.09375 0.248047 0.894824]

and bbox2 consist of two detections with cam2
[0 0.757031 0.3125 0.0953125 0.234375 0.536331
0 0.969531 0.391602 0.0609375 0.158203 0.595627]

This bbox1 and bbox2 are of same image and same frame but with different cameras.
 I want same bbox and conf score on both the detections.
So,  I wish to apply NMS, for each individual detection meaning. i want best of bbox details btw from both cameras  by fusing each detection[0 0.919531 0.266602 0.0671875 0.166016 0.576993   0 0.757031 0.3125 0.0953125 0.234375 0.536331]  i assume all the other parameters like iou, are same. 

pred = non_max_suppression(pred, conf_thres, iou_thres, classes, agnostic_nms, max_det=max_det)

can you help me in how to feed this data into nms and get best bbox as output.

This i am doing as a post processing after detections from yolov5.

Your help will be of great value for me.

thanks and regards,
Bharath

**Comment by glenn-jocher** [comment]
@b4u365 Hi Bharath,

To apply NMS on your detections from both cameras, you can simply concatenate the two sets of bounding box predictions into one array, and then pass this combined array to the NMS function. This way, NMS will consider the detections from both cameras together and output the best bounding boxes.

For example:
```python
combined_bbox = np.concatenate((bbox1, bbox2), axis=0)
nms_output = non_max_suppression(combined_bbox, conf_thres, iou_thres, classes, agnostic_nms, max_det=max_det)
```

By doing this, you can obtain the best bounding box details between both cameras.

Keep up the great work, and feel free to reach out if you have more questions!

**Comment by b4u365** [comment]
Hey Thank you so much for your help, 

I am trying to use non max suppression  but some how i was not getting the expected 
out put.

given the two boxes generated by using --save-txt and --save-conf from two cameras for similar frame

bbx1 = [0, 0.624219, 0.336914, 0.0296875, 0.0839844, 0.680819]
bbx2 = [0, 0.617188, 0.355469, 0.025, 0.0859375, 0.366679]

i was expecting a output as bbx1 due to its higher confidence score  of 0.680819 which is above conf threshold =0.5  

 i have just used a simple case to understand the nms  below is my code for the same :                                                                  from utils.general import non_max_suppression
import numpy as np
import torch
conf_thres = 0.5
iou_thres = 0.5
classes = 0
agnostic_nms = False
max_det = 300  
bbx1 = [0, 0.624219, 0.336914, 0.0296875, 0.0839844, 0.680819]
bbx2 = [0, 0.617188, 0.355469, 0.025, 0.0859375, 0.366679]
combined_bbox = [bbx1, bbx2 ]
combined_bbox_tensor = torch.tensor(combined_bbox, dtype=torch.float64)
nms_output = non_max_suppression(combined_bbox_tensor, conf_thres, iou_thres, classes, agnostic_nms, max_det=max_det)
print(nms_output)

this code is giving me null output .:[tensor([], size=(0, 6)), tensor([], size=(0, 6))] which i was not expecting, were i was expecting bbx1 dimensions.

can you correct me, I Know  that I have given wrong input format to nms , but could not able to understand the right format to nms. The same nms works perfectly when i run on yolo.

Your feedback is of great value to me .

Thanks and Regards,
Bharath.

**Comment by glenn-jocher** [comment]
@b4u365 Hi Bharath,

It looks like the issue in your code is that you are interchanging the order of the bounding box elements. For YOLOv5 format, the order should be `[x_center, y_center, width, height, confidence, class]`, but your input seems to be in a different order.

Here's the corrected input for the `combined_bbox`:
```python
combined_bbox = [
    [0.624219, 0.336914, 0.0296875, 0.0839844, 0.680819, 0],
    [0.617188, 0.355469, 0.025, 0.0859375, 0.366679, 0]
]
```
Ensure that the confidence scores are in the correct order and try passing this `combined_bbox` to the NMS function.

Let me know if this resolves the issue, or if you have further questions!

**Comment by b4u365** [comment]
Hey Thanks so much for you help, 

Still getting the null with the specified format, given this input                                                                                               combined_bbox = [
    [0.624219, 0.336914, 0.0296875, 0.0839844, 0.680819, 0],
    [0.617188, 0.355469, 0.025, 0.0859375, 0.366679, 0]
] so  it the expected out put from nms is this right?[0.624219, 0.336914, 0.0296875, 0.0839844, 0.680819, 0]  but i am getting a null.

below is the sample code which is returning null after passing through nms.

conf_thres = 0.5
iou_thres = 0.3
classes = 0
agnostic_nms = False
max_det = 300
bbx1 = [0.624219, 0.336914, 0.0296875, 0.0839844, 0.680819,0.0]
bbx2 = [0.617188, 0.355469, 0.025, 0.0859375, 0.266679,0.0]
combined_bbox = [bbx1, bbx2 ]
combined_bbox_tensor = torch.tensor(combined_bbox, dtype=torch.float64)
nms_output = non_max_suppression(combined_bbox_tensor, conf_thres, iou_thres, classes, agnostic_nms, max_det=max_det)
print(nms_output)

Can you help in resolving this, you help will be of great value.

Thanks and Regards,
Bharath

**Comment by glenn-jocher** [comment]
@b4u365 It seems your bounding box coordinates and confidence scores are in the correct format. 

The issue might be with the confidence threshold and IoU threshold settings. Please ensure that the IoU threshold is not too high, as it may be filtering out the bounding box with a slightly lower confidence score. Also, double-check that the confidence scores meet the specified threshold.

Additionally, the `non_max_suppression` function might not be returning the expected output due to different factors, such as invalid input values or errors within the function itself. Double-check that the `non_max_suppression` function is correctly implemented and that the input format is as expected by the function.

If the issue persists, I recommend reviewing the `non_max_suppression` function for any possible issues.

Let me know if you need further assistance!
