### ISSUE TITLE
How to retrieve video before it is passed to YOLO

### ISSUE THREAD

**Issue by itsjustrafli** [ultralytics/yolov5#12466]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

So, I am running yolov5 to perform live detection with webcam. I want to retrieve the video captured by yolov5 before passing it through the detection process, is it possible? If so, how could I be doing this?

Because I am confused what variable to "refer" in case you want to get the camera input in yolov5 detection script.

Thanks in advance!

**Comment by hanming-nls** [comment]
If you are running detect.py, you can specify the --source 0 
where 0 is the device no of your webcam
On detect.py, the following line load the video
LoadStreams(source, img_size=imgsz, stride=stride, auto=pt, vid_stride=vid_stride)

If you are running your own python code, then you can use any library, e.g. OpenCV to read the image frame from webcam and preprcess the image into a contiguous array and pass to yolo.
Refer to utils/dataloaders -> \_\_next\_\_(self) for sample code

**Comment by glenn-jocher** [comment]
@hanming-nls thanks for helping out! Specifying the --source 0 in detect.py allows you to use the webcam as the input. If you prefer to use your own Python code, you can use libraries like OpenCV to read and preprocess the webcam frames before passing them to YOLOv5. Check out the utils/dataloaders -> \_\_next\_\_(self) for sample code in this regard. Good luck!
