### ISSUE TITLE
Export yolov8 with onnx==1.6.0

### ISSUE THREAD

**Issue by danielafrimi** [ultralytics/yolov5#12464]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, 
I want to export yolov8 to onnx with version 1.6.0 (the compilation to some chip via onnx required this version).
However, i can install this onnx version with python<= 3.7, and your repo requires python>=3.8.

Do u know how can i export this model? 

Thanks

**Comment by glenn-jocher** [comment]
@danielafrimi to export YOLOv8 to ONNX with onnx==1.6.0, you can create a virtual environment with Python 3.7, install onnx==1.6.0, and then export the model. For more details, refer to the YOLOv5 [documentation](https://docs.ultralytics.com/yolov5/). Good luck!
