### ISSUE TITLE
Exporting to a .engine file just stops on onnx

### ISSUE THREAD

**Issue by DarkFlyper** [ultralytics/yolov5#12476]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Export

### Bug

![image](https://github.com/ultralytics/yolov5/assets/99375543/978b354c-25e5-4ff8-90c8-da4d786f6530)

export: data=C:\Users\ADAM\Desktop\cheats\yolov5-master\data\coco128.yaml, weights=['scripts\\best.pt'], imgsz=[736], batch_size=1, device=0, half=False, inplace=False, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=17, verbose=False, workspace=4, nms=False, agnostic_nms=False, topk_per_class=100, topk_all=100, iou_thres=0.45, conf_thres=0.25, include=['engine']
YOLOv5  2023-12-5 Python-3.10.0 torch-2.1.1+cu121 CUDA:0 (NVIDIA GeForce GTX 1060, 6144MiB)

Fusing layers... 
Model summary: 213 layers, 7015519 parameters, 0 gradients, 15.8 GFLOPs

PyTorch: starting from scripts\best.pt with output shape (1, 33327, 7) (13.7 MB)

ONNX: starting export with onnx 1.15.0...

### Environment

 python C:\Users\ADAM\Desktop\cheats\yolov5-master\export.py --weights scripts\best.pt --include engine --device 0 --img 736 

### Minimal Reproducible Example

 python C:\Users\ADAM\Desktop\cheats\yolov5-master\export.py --weights scripts\best.pt --include engine --device 0 --img 736 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by yezi9527** [comment]
I have the same problem

**Comment by yezi9527** [comment]
![5K0NL@{GR}UGTQBV%Y~E NN](https://github.com/ultralytics/yolov5/assets/106239707/fb1fa0c1-6047-4fca-9b5b-ff4ea4640865)

**Comment by glenn-jocher** [comment]
@yezi9527 it looks like you're encountering an issue with exporting your model to a .engine file. The export process halts at the ONNX stage. In such cases, try running the command with the --verbose flag to gain further insights into the error.

```bash
python C:\Users\ADAM\Desktop\cheats\yolov5-master\export.py --weights scripts\best.pt --include engine --device 0 --img 736 --verbose
```

This additional information can help in diagnosing the issue. If the problem persists, consider referring to our [Ultralytics Docs](https://docs.ultralytics.com/yolov5/) for troubleshooting guidance.

**Comment by DarkFlyper** [comment]
![image](https://github.com/ultralytics/yolov5/assets/99375543/d4fecf44-3294-4f48-97fb-89162070bccf)
Same thing happens

**Comment by DarkFlyper** [comment]
Here by creating a new python environment I get this error 
, dynamic=False, simplify=False, opset=17, verbose=True, workspace=4, nms=False, agnostic_nms=False, topk_per_class=100, topk_all=100, iou_thres=0.45, conf_thres=0.25, include=['engine']
Traceback (most recent call last):
  File "C:\Users\ADAM\Desktop\test\yolov5\export.py", line 863, in <module>
    main(opt)
  File "C:\Users\ADAM\Desktop\test\yolov5\export.py", line 858, in main
    run(**vars(opt))
  File "C:\Users\ADAM\Desktop\test\cehatsv2\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\ADAM\Desktop\test\yolov5\export.py", line 732, in run
    device = select_device(device)
  File "C:\Users\ADAM\Desktop\test\yolov5\utils\torch_utils.py", line 118, in select_device
    assert torch.cuda.is_available() and torch.cuda.device_count() >= len(device.replace(',', '')), \
AssertionError: Invalid CUDA '--device 0' requested, use '--device cpu' or pass valid CUDA device(s)

What did I miss in its setup?

**Comment by glenn-jocher** [comment]
@DarkFlyper Thanks for trying that out. Since the issue persists, I recommend a thorough check of the model and input parameters. The YOLOv5 community on GitHub may have encountered similar issues and could offer additional insights. Please also feel free to consult the [Ultralytics Docs](https://docs.ultralytics.com/yolov5/) for troubleshooting tips. Let me know if you have further questions or need additional assistance!

**Comment by DarkFlyper** [comment]
YO HOLY SHIT I JUST FIXED IT OH MY GOD. So I created a new python environment and used torch 2.0.1 and torchvision 0.15.2 an d used cuda 11.8 instead of 12.1

**Comment by glenn-jocher** [comment]
@DarkFlyper that's fantastic to hear! 🎉 Your solution will surely be helpful for others facing similar issues. Thanks for sharing your fix with the community!
