### ISSUE TITLE
Issue with YOLOv5 custom model trained on Ultralytics Hub but no issues when used the same dataset to do offline model training.

### ISSUE THREAD

**Issue by MatBiocentis** [ultralytics/yolov5#12471]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

Dear all, I wanted to report a possible bug on YOLOV5 when I tried to use a custom model trained on the Ultralytics Hub web service. I've included below the two processes. The first process leads to the error:  "_AttributeError: 'Detect' object has no attribute 'grid_' "; the second process runs smoothly as expected without any errors.

1) Offline image labeling via RectLabel, annotation saved as YOLO format (bounding box, .txt file)
2) Online dataset augmentation and YOLOv5 dataset export (i.e., yaml file generation) via Roboflow
3) Online training custom YOLOv5n/s/m from pre-trained models via Ultralytics Hub
4) Download the model and import it on Jetson Nano B01 4GB (see environment)
5) Model execution (python detect.py --weights 'path/to/model,' etc.)

The following process does not produce any errors:

1) Offline image labeling via RectLabel, annotation saved as YOLO format (bounding box, .txt file)
2) Online dataset augmentation and YOLOv5 dataset export (i.e., yaml file generation) via Roboflow
3) Offline training custom YOLOv5n/s/m from pre-trained models with my PC
4) Copy the model from the PC to the Jetson Nano B01 4GB (see environment)
5) Model execution (python detect.py --weights 'path/to/model,' etc.)

Thanks a lot.

### Environment

YOLOv5 v7.0
OS: Ubuntu 20.04
Python: 3.9.0

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@MatBiocentis thanks for reporting! The issue you're encountering seems specific to the Ultralytics Hub workflow. 🤔 It's great that you've been able to successfully train and deploy your model offline! This will help us narrow down the issue. 

I'd recommend checking the model architecture and the scripts used for training and inference to identify the discrepancy. 

YOLOv5's deployment environments can sometimes result in unexpected errors. You can refer to the Ultralytics Docs for guidance on model deployment. 

Feel free to ask for more help if needed. Thank you for your contribution!

**Comment by SomaRe** [comment]
Encountered same issue, after reading this I trained the data on my pc offline, and inference now works. model did work with preview through webcam on hub.ultralytics.com, though doesn't work offline.

OS: Windows 11
python: 3.10.4
online: yolo8m
offline: yolo5m

**Comment by glenn-jocher** [comment]
Great to hear that offline training resolved the inference issue for you! It sounds like there might be a compatibility or configuration difference between the online and offline environments. For the model that doesn't work offline, ensure that the versions of YOLOv5 used for training and inference match, and that all dependencies are consistent with those specified in the YOLOv5 documentation. If the problem persists, checking the error logs might provide more insight into what's going wrong. Keep us posted! 😊
