### ISSUE TITLE
**Blob error**  Unable to export yolov5 model in openvino 

### ISSUE THREAD

**Issue by AbhishekPSI7042** [ultralytics/yolov5#12474]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hey, I am exporting my yolov5 custom model in openvino but it is giving error, I have trained the model with image size 360 and when I export the model in openvino it is successfully exported but I want to export the model in int8 but it is giving error.

**[ GENERAL_ERROR ] Can't set input blob with name: images, because model input (shape=[1,3,384,384]) and blob (shape=(1.3.640.640)) are incompatible**

**Comment by glenn-jocher** [comment]
@AbhishekPSI7042 hey there! It seems like the image size mismatch between your YOLOv5 model input and the OpenVINO blob is causing the error. The OpenVINO input blob's shape needs to match the model's input shape. You might need to adjust your model's input shape during exporting to resolve this issue. For more details, you can refer to the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/. Let me know if you need further assistance!
