### ISSUE TITLE
Cant start yolov5 .engine model

### ISSUE THREAD

**Issue by DarkFlyper** [ultralytics/yolov5#12475]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Other

### Bug

![image](https://github.com/ultralytics/yolov5/assets/99375543/6f851fa2-ceb5-4bda-81b4-e1fcc9cd576d)

### Minimal Reproducible Example

model = torch.hub.load(r'C:\Users\ADAM\Desktop\cheats\yolov5-master' , 'custom', path= r'C:\Users\ADAM\Desktop\cheats\scripts\best_nano_new.engine',source='local', force_reload=True)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@DarkFlyper hi there! It looks like you're trying to load a YOLOv5 .engine model. Have you referenced the [Ultralytics Docs](https://docs.ultralytics.com/yolov5/) for loading custom models? Also, ensure that the paths in your `torch.hub.load` function are correct, and that the model you're trying to load is compatible with the YOLOv5 implementation. Let me know if you need further assistance!

**Comment by Hyrtsi** [comment]
@DarkFlyper please read [this](https://github.com/NVIDIA/TensorRT/issues/2915) thread on TensorRT repo discussion and [this](https://github.com/ultralytics/ultralytics/issues/4597) thread on yolo8. Regenerating the engine could help.

**Comment by DarkFlyper** [comment]
I fixed it see the other issue I opened

**Comment by glenn-jocher** [comment]
Great to hear you've resolved the issue, @DarkFlyper! If you have any more questions or run into any other problems, feel free to reach out. Happy coding! 😊👍
