### ISSUE TITLE
Hyperparameter tuning with different optimizers

### ISSUE THREAD

**Issue by unrue** [ultralytics/yolov5#12480]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is it possible to set also optimizer type in the list of hyperparameter to tune? Or I have to tune each possible optimizers? Thanks.

**Comment by glenn-jocher** [comment]
@unrue hi there! Currently, YOLOv5 only supports one optimizer at a time. You'll need to tune parameters for each optimizer separately. Optimizer choice can greatly impact model performance, so it's worth experimenting! If you have any other questions, feel free to ask!

**Comment by unrue** [comment]
Thanks Glenn. Is there any guide to chose the optimal optimizer considering a dataset having 30k images and 75 classes?

**Comment by glenn-jocher** [comment]
@unrue Great question! The choice of optimizer often depends on the specific dataset and model architecture being used. For larger datasets like yours, Adam and AdamW optimizers tend to perform well. However, it's best to experiment with different optimizers and learning rates to find the best combination for your specific scenario. 🚀 You can refer to the Ultralytics Docs for more details on optimizer selection and hyperparameter tuning. Good luck with your experiments!
