### ISSUE TITLE
Cannot load an exported torchscript model using torch.jit.load

### ISSUE THREAD

**Issue by AWilco** [ultralytics/yolov5#1248]
## 🐛 Bug
When attempting to load an exported torchscript model of yolov5s.pt using test.py (or my own implementation which is copied from this) the model cannnot be loaded. The python error log is:

Traceback (most recent call last):
  File "test.py", line 290, in <module>
    save_conf=opt.save_conf,
  File "test.py", line 59, in test
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "/content/yolov5/models/experimental.py", line 137, in attempt_load
    model.append(torch.load(w, map_location=map_location)['model'].float().fuse().eval())  # load FP32 model
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 2106, in __getitem__
    return self.forward_magic_method("__getitem__", idx)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 2099, in forward_magic_method
    raise NotImplementedError()
NotImplementedError

## To Reproduce (REQUIRED)
See https://colab.research.google.com/drive/1xTOgWqoHQ3tauH-YuAkNctLU4YrBH8JI?usp=sharing as a colab which generates the error at the "Test Export and Import" section

(this has been tested with a local download of the source code from this morning and also using the google colab result)

Input:
```
python models/export.py --weights yolov5s.pt --img 640 --batch 1

python test.py --data "coco128.yaml" --weights "yolov5s.torchscript.pt"
```

Output:
```
Traceback (most recent call last):
  File "test.py", line 290, in <module>
    save_conf=opt.save_conf,
  File "test.py", line 59, in test
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "/content/yolov5/models/experimental.py", line 137, in attempt_load
    model.append(torch.load(w, map_location=map_location)['model'].float().fuse().eval())  # load FP32 model
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 2106, in __getitem__
    return self.forward_magic_method("__getitem__", idx)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 2099, in forward_magic_method
    raise NotImplementedError()
NotImplementedError
```

## Expected behavior
The model is successfully loaded by torch.jit.load

(Note that torch.load automatically redirects to torch.jit.load when called in test.py)

## Environment
 - OS: Ubuntu
 - GPU 1050

## Additional context
I have tried with a custom trained model based on cfg/yolov5s.yml also.

**Comment by glenn-jocher** [comment]
@AWilco YOLOv5 *.pt checkpoints are python dictionaries, with the actual models located in `ckpt['model']`.
```python
import torch

ckpt = torch.load('yolov5s.pt')
print(ckpt.keys())
dict_keys(['epoch', 'best_fitness', 'training_results', 'model', 'optimizer'])
```

The exported models are directly saved to their respective formats (rather than being assigned values in a checkpoint dictionary), and are not intended to be replaceable with the exported files when running detection or testing.

**Comment by AWilco** [comment]
Thanks @glenn-jocher. Sorry for labelling this as a bug when it is clearly my own confusion. I think I had already used things correctly but managed to confuse myself debugging other errors.

To confirm my understanding:
*.pt checkpoint files are portable across python projects that use pytorch. To use a checkpoint file in another project all you use is:

```
import torch
self.model = torch.load(opt["checkpoint.pt"], map_location=self.device)['model'].float().fuse().eval()
predictions = self.model(img_on_device)
```

Torchscript files would be fed into the torchscript compiler to use the model in a C++ project, but if you're staying in python and pytorch there's no reason to use it.
