### ISSUE TITLE
Distance Detection/Estimation

### ISSUE THREAD

**Issue by DylanBPY** [ultralytics/yolov5#12484]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I touched on this subject in this issue:
[https://github.com/ultralytics/yolov5/issues/12447](url)

I never went to deep into it because that want the main concern, however, now I want to get it working.
I have looked into Dist-YOLO, I cant figure out how to use it (and its outdated)
Ive also tried YOLOER-V1, which doesnt seem to work.

I am currently trying to calculate distance with cv2, it does not look like its going to turn out good though.

Any ideas, suggestions, or input on this subject would be appreciated.

**Comment by glenn-jocher** [comment]
@DylDevs hey there! Thanks for reaching out. Distance estimation with YOLOv5 is an interesting challenge. While YOLOv5 itself doesn't natively support distance estimation, some users have had success with custom implementations using depth sensors or stereo cameras. You might find our documentation on customizing YOLOv5 for specific tasks helpful: https://docs.ultralytics.com/yolov5/. Keep experimenting and feel free to share your progress with the community! 🚀

**Comment by DylanBPY** [comment]
Sorry, I forgot to respond, What I did to achieve "distance" estimation was just using the width of the bounding box to get a distance in px. This works pretty well depending on the type of vehicle being detected

**Comment by glenn-jocher** [comment]
@DylDevs that's a clever approach! Using the width of the bounding box for distance estimation is a simple yet effective method, especially for identifying different types of vehicles. Thanks for sharing your solution with the community! 🚗📏

**Comment by DylanBPY** [comment]
@glenn-jocher I realize that this issue is really really old, but I would like to bring up a suggestion. Could some form of ray casting being implemented to YOLO? I have already done this but it would be nice to have native support for it as well.

**Comment by glenn-jocher** [comment]
@DylDevs Thanks for your suggestion! Ray casting is an interesting idea and could indeed enhance certain applications of YOLOv5. While it's great to hear that you've implemented it on your own, native support would require careful consideration and development. We appreciate your input and encourage you to share more details or even contribute your implementation to the community. Your feedback helps us improve! 🚀
