### ISSUE TITLE
Yolov5 backbone feature extraction

### ISSUE THREAD

**Issue by rayika-26** [ultralytics/yolov5#12486]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Good day, I'm a student researcher conducting our thesis entitled Coffee Cherry Maturity Classification using Yolov5 Object Detection. We have already deployed our mobile application which has 2 features: real-time detection and classification through uploaded image. Our panel requested to provide details or explanation how yolov5 process our input images in our mobile application. Can you provide clear explanation for this? 

In addition, in our real-time feature of our mobile app, the camera seems to lag or low in fps, is this a problem in the trained model or its normal for yolov5?

**Comment by glenn-jocher** [comment]
@rayika-26 good day! 🌞 That’s a fascinating project you’re working on, and I appreciate your interest in YOLOv5. In terms of how YOLOv5 processes input images in your mobile application, you might find our [Ultralytics Docs](https://docs.ultralytics.com/yolov5/) helpful for understanding the model's inference process.

Regarding the real-time feature of your app, performance can depend on various factors, including hardware, model size, and input resolution. You might consider optimizations like model quantization or using a smaller model to improve real-time inference speed.

I hope this helps, and best of luck with your research! 🚀
