### ISSUE TITLE
Persistent problems during training

### ISSUE THREAD

**Issue by JerickoDG** [ultralytics/yolov5#12491]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am currently training a model using this command: `python train.py --data dataset/data.yaml --weights yolov5m.pt --img 640 --batch-size 8 --epochs 100 --hyp data/hyps/hyp.scratch-med.yaml`

The training was stopping suddenly with different errors which were the ff:

- RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
- RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR
- RuntimeError: CUDA error: an illegal memory access was encountered
- Often, there were no error messages. The training just stops suddenly.

The GPU I am using is RTX 3060Ti and my operating system is Windows 10.

Previously, I had CUDA 11.8 and complementing cuDNN version. Thus, I tried to update everything (uninstall previous version and install the latest), thus currently I have CUDA 12.1 and cuDNN 8.9.7. I also used this command to install the correct version of PyTorch based on the website: `pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121`

Aside from that, I tried lowering the batch size from 16, 8, and 4.  Also, since I have Python 3.11.3, I also tried to create an environment with Python 3.10.13. However, the problem still persisted.

With those said, I would like to ask the cause behind this problem and the corresponding solution.

If there are any further details needed, I will provide them as soon as I can. Any response will be much appreciated.

These are the images that contain the details regarding the versions of CUDA, cuDNN, and Torch, and Torchvision as well as the outputs from `nvcc --version` and `nvidia-smi` from the terminal. Moreover, the screenshots of the errors are also provided.

![image](https://github.com/ultralytics/yolov5/assets/60811658/723c6f8a-c436-4366-b3d0-eb96096e1fec)

![image](https://github.com/ultralytics/yolov5/assets/60811658/b3964c99-469f-429e-b911-ddbe3d257504)

**Comment by glenn-jocher** [comment]
@JerickoDG hi there! Thanks for reaching out. 🌟 It sounds like you've put in a lot of effort trying to troubleshoot this issue. The errors you're encountering could be related to a variety of factors. 

Have you checked the system log for any hardware-related problems or attempted training on a different machine to rule out any hardware issues?

It might also be helpful to verify the integrity of your dataset and double-check the data configuration for any anomalies. Additionally, ensuring all dependencies are up to date and compatible could help resolve the issue.

Feel free to use the latest YOLOv5 documentation for reference: https://docs.ultralytics.com/yolov5/

Let me know if you have any additional details or if any of these suggestions bring you closer to a resolution. Good luck!

**Comment by JerickoDG** [comment]
@glenn-jocher , thank you for your response. I haven't tried training on different machine, but I will try it and give you an update.

Regarding the system log checking, may I ask if you know where I can look at it in Windows 10 and what I expect to see if there are any hardware-related problems? Perhaps, an example output could help.

About the dataset integrity, upon executing the `train.py` in the terminal, the training and validation data seem to be checked. There is an indication "0 corrupt". Is that enough for the verification or are there other ways? As another step for possibly ruling out this problem, I will also try to use a dataset that worked from the past with no problems and give you an update as well.

**Comment by glenn-jocher** [comment]
@JerickoDG You're welcome! When checking the system log in Windows 10, you can use the Event Viewer to inspect system logs for any hardware-related issues. Look for critical or error events under the System or Application logs, indicating potential hardware problems. Additionally, checking the Windows Reliability Monitor might provide insights into system stability and any hardware-related issues.

As for dataset integrity, the indication "0 corrupt" is a good sign, but you may also consider running a separate script to verify the integrity of the dataset files themselves. Utilizing a known trouble-free dataset as a comparison is also a good approach to assess whether the issue is dataset-related.

I hope these suggestions help in troubleshooting, and I look forward to your updates!

**Comment by JerickoDG** [comment]
@glenn-jocher , hi. Here are some of the updates:

- On another machine (Lenovo Legion 5 - 1650Ti), I tried the latest repository with the old CUDA 11.8 and cuDNN 8.6.0. There was an error: **NotImplementedError: Could not run 'torchvision::nms' with arguments from the 'CUDA' backend.** However, it seemed to work fine when I used an old version of the YOLOv5 ultralytics repository that was maybe 94 commits behind as it went up to 33 epochs using my custom dataset before I cancelled it.
- I tried the classic Aquarium Dataset on the 3060Ti machine but the problem still persisted.
- As soon as the error happened on the 3060Ti machine, I checked the Event Viewer>Windows Logs>System and this error appeared: **The description for Event ID 13 from source nvlddmkm cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.**

Kindly refer to this snapshot for the errors (there were two errors with unique Event ID):
![image](https://github.com/ultralytics/yolov5/assets/60811658/6433c0f7-e6a6-462f-a7f5-82d311015ace)

Here are more details in XML view for each error:
![image](https://github.com/ultralytics/yolov5/assets/60811658/3867deba-b43d-42f7-85a9-05e0a161043f)

**Comment by glenn-jocher** [comment]
@JerickoDG Thank you for sharing the updates! The `NotImplementedError` on the old machine with the old version of the YOLOv5 repository seems related to the CUDA backend. This might be a compatibility issue with the older repository and the newer CUDA version. 

The persistence of the problem with the classic Aquarium Dataset on the RTX 3060Ti machine is important information and suggests that the issue is not specific to your custom dataset.

The Event Viewer error related to `nvlddmkm` suggests a potential problem with the Nvidia graphics driver. Ensuring that the graphics driver is up to date and reinstalling it may help resolve this issue.

I appreciate the detailed updates and the provided snapshots. Keep me posted on any further developments!

**Comment by JerickoDG** [comment]
@glenn-jocher The graphics driver version I have for the 3060Ti machine was 546.29 which was the latest based on the GeForce Experience application. With it being the current and latest graphics driver, I tried to reinstall it using also GeForce Experience but still, the problem still persisted. Is my graphics driver reinstallation process incorrect or are there other better ways you can recommend of doing it?

**Comment by glenn-jocher** [comment]
@JerickoDG It sounds like you've followed the standard procedure for updating the graphics driver using GeForce Experience. Sometimes, a clean installation of the graphics driver can help resolve persistent issues. You can perform a clean installation by using the "Custom (Advanced)" installation option in the Nvidia graphics driver installer and selecting the "Perform a clean installation" checkbox. This ensures that the previous driver is completely removed before the new driver is installed.

If the issue still persists after a clean installation, you might try using a slightly older version of the graphics driver to see if that resolves the problem.

I hope this helps, and I'd love to hear about any changes in the behavior after the clean installation or after trying an older driver version. Good luck!

**Comment by JerickoDG** [comment]
@glenn-jocher Hi. I tried to perform a clean installation of the graphics driver via GeForce Experience. There was a latest version release (546.33) so I upgraded it as well. I also tried downgrading the graphics driver version to 546.17 (released on Nov. 14, 2023). However, the same problems persisted (i.e., Error in Event Viewer and terminal when using train.py). Are there other ways you could possibly suggest or other actions I can try?

**Comment by glenn-jocher** [comment]
@JerickoDG I appreciate your thorough troubleshooting efforts. Given the persistence of the issue despite the steps taken, it's worth considering a few additional approaches.

Firstly, ensuring that your Windows 10 installation is fully up to date is paramount. Installing all available Windows updates can potentially address underlying system issues.

Meanwhile, monitoring the GPU temperatures during training sessions can help identify any overheating-related problems. Utilizing tools like MSI Afterburner or GPU-Z can provide real-time temperature data.

Lastly, examining system logs during the training sessions for any signs of GPU errors or warnings may yield valuable insights into the root cause of the issue.

I hope one of these approaches leads to a breakthrough. Let me know if any of these suggestions shine a light on the situation!

**Comment by JerickoDG** [comment]
@glenn-jocher Currently, I tried performing clean install with latest Nvidia Graphics Driver 546.33 (Studio Version instead of Game Ready Version) and I'm glad to tell you that the training finished up until the end (100 epochs) with no errors. I also used the old repository that was 94 commits behind and Python 3.9.18. I'll try to train again and verify if it was just a fluke or not.

**Comment by glenn-jocher** [comment]
@JerickoDG That's fantastic news! I'm glad to hear that the clean installation with the latest Nvidia Graphics Driver 546.33 (Studio Version) has seemingly resolved the issue, allowing the training to complete successfully. It's always a relief when things start falling into place.

It would definitely be worthwhile to verify the stability by running the training process again. If the successful outcome repeats, it could provide additional confirmation that the issue has been addressed.

Thank you for sharing this positive development, and I'm here to help with any further questions or concerns. Good luck with the next training run!

**Comment by JerickoDG** [comment]
@glenn-jocher I don't know if I'll consider the training success as a fluke as the problem occurred again. However, I tried performing again the clean installation of Nvidia Driver (Studio Version) 546.33 and it went past the fifth epoch. Normally when problem occurs, it does not even go past the first epoch that is why I considered it successful when it goes past five epochs.

The GPU temperature at idle is around 39C-42C and during training, it ranges to 77C-83C. The temperature went beyond once the temp limit (83C) which was at 85C but the training still continued as is.

Here are some of the snapshots from the MSI Afterburner:

![image](https://github.com/ultralytics/yolov5/assets/60811658/ad2ec3fa-9e5c-4bc2-9859-4e004136aab9)

I'll try to provide an update again if ever. But for now, I guess that the clean reinstallation of the latest studio version of graphics driver fixed the persisting problem again.

**Comment by glenn-jocher** [comment]
@JerickoDG Thank you for the detailed update! It's encouraging to see that the clean reinstallation of the latest studio version of the graphics driver has led to improved stability during training, allowing for successful progress beyond the previous hurdle.

Monitoring the GPU temperature is crucial, and it's excellent to note that the temperatures during training are within the expected range. The fact that the training continued despite briefly exceeding the temperature limit indicates good thermal management.

Remember, if any further issues arise or if you have updates to share, I'm here to assist. Wishing you continued success with your training, and I look forward to any future updates you might have.
