### ISSUE TITLE
What is the difference between YOLOv5s and YOLOv5s6?

### ISSUE THREAD

**Issue by EngrNaeemRaza** [ultralytics/yolov5#12499]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

**What is the difference between YOLOv5s and YOLOv5s6? **

### Additional

What is the difference between YOLOv5s and YOLOv5s6?

**Comment by glenn-jocher** [comment]
@EngrNaeemRaza the 's6' models in YOLOv5 have 6x more model parameters compared to the 's' models, resulting in improved accuracy at the cost of larger model size and slower inference. For more details, check out the documentation at https://docs.ultralytics.com/yolov5/.
