### ISSUE TITLE
Putting data into different numpy array's based on confidence

### ISSUE THREAD

**Issue by ThundahPrime** [ultralytics/yolov5#12490]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello! I am currently working on an application that reads out a string contains all of the detected objects using TTS, but the sentence right now is very shallow and lacks depth. I want the sentence to read out if it's very sure, quite sure or pretty sure of what an object is, but I need to classify each object based on it's confidence in order to do that. How can I separate the results based on confidence?

**Comment by glenn-jocher** [comment]
@ThundahPrime you can achieve this by iterating through detections and sorting them based on their confidence scores. For example, you can create different lists or arrays for very sure, quite sure, and pretty sure detections and then process them accordingly. Check out the `pred[..., :4]` and `pred[..., 4]` outputs in the repo's docs for further guidance.

**Comment by ThundahPrime** [comment]
> @ThundahPrime you can achieve this by iterating through detections and sorting them based on their confidence scores. For example, you can create different lists or arrays for very sure, quite sure, and pretty sure detections and then process them accordingly. Check out the `pred[..., :4]` and `pred[..., 4]` outputs in the repo's docs for further guidance.

@glenn-jocher I'm having some trouble finding it. Could you send me a link?

**Comment by glenn-jocher** [comment]
@ThundahPrime certainly! You can find the details in the "Detection Format" section of the Ultralytics Docs at https://docs.ultralytics.com/yolov5/. The `pred[..., :4]` contains the bounding box coordinates, and `pred[..., 4]` contains the confidence scores. These can be used to sort the detections based on confidence levels.
