### ISSUE TITLE
I don't know why AP is too low

### ISSUE THREAD

**Issue by ZZY-666** [ultralytics/yolov5#125]
The mAP of my detection with yolov3 can reach 0.9,but the accuracy of yolov5 is only about 0.02.
Whether it's single card training or multi card training.
Whether I trained for 100 epochs or 1000 epochs.

![微信图片_20200618184220](https://user-images.githubusercontent.com/59229974/85011042-979a4480-b193-11ea-9efd-afb6b50414da.png)

Did I fail to make the adjustment?
I will appreciate very much with your any opinions!

**Comment by ZZY-666** [comment]
I want to ask if there is any problem with the AP display. The picture is on the first issue.

**Comment by glenn-jocher** [comment]
@ZZY-666 bug fix resolved yesterday. See https://github.com/ultralytics/yolov5/issues/91

TLDR: `git pull` and run again

Closing as duplicate.
