### ISSUE TITLE
Exporting (using export.py) for CUDA-based torchscript files

### ISSUE THREAD

**Issue by rtrahms** [ultralytics/yolov5#1250]
## ❔Question
Looks like models/export.py was written to support torchscript, onnx and mlmodel for CPU only.  Has anyone tried updating the script to support export of CUDA-variants?
Thanks,
Rob

**Comment by FantasyJXF** [comment]
Just export the torchscript with `map_location=torch.device('cuda')` will do.

**Comment by rtrahms** [comment]
Thanks!  That worked.
