### ISSUE TITLE
How can I select the first 3 classes out of 11 classes in training to do validation in YOLOv5

### ISSUE THREAD

**Issue by wjlim-14** [ultralytics/yolov5#12505]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have trained the model with 11 classes and I need to use the best model to do validation and get the performance metrics and confusion matrix. Where can I configure to calculate only A,B and D classes performance?

`!python val.py --data data\jpeg_image\data.yaml --task test --weights weights\best.pt`

<img width="787" alt="image" src="https://github.com/ultralytics/yolov5/assets/74594391/653c6cea-0076-4e65-831b-a0655a7cff74">

**Comment by glenn-jocher** [comment]
@wjlim-14 you can specify the classes to be included during validation in the `data.yaml` file. Set the `val` parameter to a list of the classes to include, e.g. `val: [A, B, D]`. For more details, refer to the [Ultralytics Docs](https://docs.ultralytics.com/yolov5/).

**Comment by wjlim-14** [comment]
<img width="548" alt="image" src="https://github.com/ultralytics/yolov5/assets/74594391/16baad5e-6d3b-44b2-982d-9a5cc58391d5">
this is my data.yaml file. the train,valid,test are point to my dataset that contains images and labels. How to specific for class A,B and D in yaml?

**Comment by glenn-jocher** [comment]
@wjlim-14 You can specific the classes A, B, and D in the `data.yaml` file by modifying the `names` parameter to include only these classes.

For example:
```yaml
names:
  - A
  - B
  - D
```

For more details, refer to the [Ultralytics Docs](https://docs.ultralytics.com/yolov5/).
