### ISSUE TITLE
Make number of channels in convolution configurable

### ISSUE THREAD

**Issue by Corallo** [ultralytics/yolov5#12506]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

It would be great if the number of layer per convolution could be configurable. At the moment, it is hard-coded to 8. 
Some ASICs might have a number of core different from 8, and therefore the optimal number of channel in a convolution should be different from a multiple of 8 to get the best performance.
At the moment, the only way to optimize the model for the number of cores is to edit from source the hard-coded value. Making it configurable would make it easier for users to optimize the model without digging into the code.

### Use case

Maximize usage of SoC for Deep Learning

### Additional

I would be happy to open a PR if you would want this feature.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Corallo hi there! Thanks for the request! We really appreciate your input. It's a neat idea, and we're always looking to improve YOLOv5 for a wider audience. We'll consider this suggestion along with our overall development plan. If you decide to send a PR, that would be fantastic. If you need any guidance on the process, feel free to ask. Cheers!
