### ISSUE TITLE
How to use  Classification yolov5  model  like what we do in yolov8 ( using Ultralytics YOLO)

### ISSUE THREAD

**Issue by VYRION-Ai** [ultralytics/yolov5#12509]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to use  Classification yolov5  model  like what we do in yolov8 ( using Ultralytics YOLO)
`from ultralytics import YOLO

```
# Load a model
model = YOLO('yolov8n-cls.pt')  # load an official model
model = YOLO('path/to/best.pt')  # load a custom model

# Predict with the model
results = model('https://ultralytics.com/images/bus.jpg')  # predict on an image`
```

**Comment by glenn-jocher** [comment]
@VYRION-Ai hey there! YOLOv5 currently doesn't have a built-in classification model like YOLOv8. For classification, you can utilize YOLOv5's object detection model and then use the predicted bounding boxes to classify objects separately. Check out the Ultralytics Docs for more details on YOLOv5 usage. Keep up the great work! 🚀

**Comment by VYRION-Ai** [comment]
I did crop the box, and this is my task by the way, but I can't classifying the cropped regone

**Comment by glenn-jocher** [comment]
@VYRION-Ai you can classify the cropped regions using a separate classifier, such as a CNN or other image classification model. There are various resources available for image classification with PyTorch that can help guide you through the process. Keep up the great work! 🚀

**Comment by VYRION-Ai** [comment]
@glenn-jocher but with Yolo v5 classification model I cannot, correct?

**Comment by glenn-jocher** [comment]
@VYRION-Ai That's correct. YOLOv5 currently does not have a built-in classification model. You would need to use a separate classification model in conjunction with YOLOv5's object detection model for this task. Keep up the great work! 🚀
