### ISSUE TITLE
index: 2 Got: 384 Expected: 640

### ISSUE THREAD

**Issue by DylanBPY** [ultralytics/yolov5#12519]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have been using the Ultralytics Python module to use my yolov5 model made with Ultralytics Hub 
I switched to doing it this way, (gives more customization):
[https://docs.ultralytics.com/yolov5/tutorials/train_custom_data](url)

However if I try to use the Ultralytics module to load the model, I get this:
```
TypeError: ERROR  best.pt appears to be an Ultralytics YOLOv5 model originally trained with https://github.com/ultralytics/yolov5.
This model is NOT forwards compatible with YOLOv8 at https://github.com/ultralytics/ultralytics.
Recommend fixes are to train a new model using the latest 'ultralytics' package or to run a command with an official YOLOv8 model, i.e. 'yolo predict model=yolov8n.pt'
```

So I switched to using torch.hub.load()
It loads the model fine, however when it trys to get detection results, I get this error:
```
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: images for the following indices
 index: 2 Got: 384 Expected: 640
 Please fix either the inputs or the model.
```
I have gotten this error before using the Ultralytics module, I just changed the imgsz argument and that fixed it.
It appears that torch doesnt support that argument and Im unsure of how to go about fixing this.
Ive tried:
- imgsz
- imgsize
- size

And nothing works
Ive looked through this page about torch.hub.load() to no avail:
[https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading/](url)

I am unsure of what to do from here, any help is appreciated.

### Code
```
import os
import dxcam
import cv2
import torch 
from ultralytics import YOLO
os.chdir(os.path.dirname(__file__))

model = torch.hub.load('ultralytics/yolov5', 'custom', path='best.onnx', _verbose=False)

# Initzialize a DXcam camera
camera = dxcam.create(device_idx=0, output_color="BGR")
left = 0
top = 0
right = 1360
bottom = 768

cv2.namedWindow("test", cv2.WINDOW_NORMAL)
cv2.resizeWindow("test", 400, 200)
cv2.setWindowProperty("test", cv2.WND_PROP_TOPMOST, 1)


while True:
    frame = camera.grab(region=(left,top,right,bottom))
    if frame is None: 
        continue
    
    results = model(frame, imgsz=640)

    cv2.imshow("test", frame)
    cv2.waitKey(1)
```

**Comment by glenn-jocher** [comment]
@DylDevs hi there! It looks like you're encountering a dimension issue with the input images. To fix this, try setting the input image size using the 'img_size' argument instead of 'imgsz' when calling the model. You can find more details on image size configuration in the [Ultralytics Docs](https://docs.ultralytics.com/yolov5/). Good luck!

**Comment by DylanBPY** [comment]
@glenn-jocher Thanks for the response.
'img_size' is one of the arguments I have already tried.
It gives this error when I set `img_size = 640`:
```
TypeError: AutoShape.forward() got an unexpected keyword argument 'img_size'
```

**Comment by glenn-jocher** [comment]
@DylDevs Apologies for the confusion. It seems you are encountering an unexpected issue with the 'img_size' argument. To resolve this, you might want to check the specific version of YOLOv5 you are using and ensure compatibility with the argument names. If the issue persists, you may consider posting a question in the YOLOv5 Issues or Discussions section for further assistance. Good luck!

**Comment by DylanBPY** [comment]
I am running a custom trained YOLOv5 model
I trained it using this guide:
https://docs.ultralytics.com/yolov5/tutorials/train_custom_data/#1-create-dataset

I have tried retraining the models with different image sizes to no avail
I need to get this working in the next couple days, so any help is appreciated

**Comment by DylanBPY** [comment]
Yolov5s*

**Comment by DylanBPY** [comment]
About the argument names, I cant find any documentation about the specific argument that I am looking for

**Comment by glenn-jocher** [comment]
@DylDevs I understand your urgency. To resolve the specific issue with the 'img_size' argument, I recommend checking the YOLOv5 source code or directly reaching out to the YOLOv5 community for guidance on the correct argument usage specific to custom-trained models. The Ultralytics team and the broader community are excellent resources for resolving such technical nuances. Good luck with your project!

**Comment by DylanBPY** [comment]
Where can I reach those people?

**Comment by DylanBPY** [comment]
Just figured out that this error only happens on .onnx models, I have no idea why. I do need to figure out how to get ONNX working for my use case.

**Comment by glenn-jocher** [comment]
@DylDevs that's a meaningful discovery! Troubleshooting the ONNX-specific issue further might lead to a resolution. Feel free to share your findings or inquire on the ONNX-related aspects in relevant technical forums or communities for additional insights. Good luck with your ONNX integration!

**Comment by DylanBPY** [comment]
This issue comes up once again, does anyone have any fixes?

**Comment by glenn-jocher** [comment]
@DylDevs It seems like the issue might be related to the expected input size for the ONNX model. When exporting a YOLOv5 model to ONNX, the input size is fixed. If your custom model was trained with a different input size, you need to ensure that the inference input size matches the training size.

For ONNX models, you typically set the input size during the export process, and it cannot be changed at runtime. If you're using an ONNX model, you should preprocess your images to the expected input size before passing them to the model.

Here's a quick guide on how to preprocess your images:

1. Resize your image to the expected input size of the model (the size used during training or ONNX export).
2. Ensure the image is in the correct format (usually a color image with BGR channels).
3. Normalize the image if required by your model's training parameters.

If you continue to face issues, consider re-exporting your model to ONNX, making sure to specify the correct input size that you plan to use during inference.

If you need further assistance, the best place to reach out would be the GitHub Issues section of the YOLOv5 repository. There, you can provide detailed information about your problem, and the community, along with the maintainers, can help troubleshoot the issue more effectively. Remember to include all relevant details and what you've tried so far when you post your issue.
