### ISSUE TITLE
Add option to quantize by Tensor

### ISSUE THREAD

**Issue by Corallo** [ultralytics/yolov5#12515]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

The quantization type done by TensorFlow Lite Converter is called "Quantization by channels" (also sometimes called "Quantization by Axis"). With this type of quantization, each channel of a convolutional layer has its own quantization parameters.
This type of quantization is the standard in TensorFlow 2.x

Before that, in TF 1.x the standard was "Quantization by tensor" where all the channels of a layer were sharing the same quantization parameters.

Some ASICs (Deep Learning accelerators) are optimized for the quantization by tensor scheme. It would be nice to have a flag in the exporter to quantize by tensors instead of channels.

### Use case

Support quantization by tensor for ASICs optimized for that quantization scheme.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Corallo thanks for the feature request! We'll consider adding an option for "Quantization by tensors" in a future release, especially for ASICs optimized for this type of quantization. We greatly appreciate your proposal and any future contribution. 🙌
