### ISSUE TITLE
Manually save exported model

### ISSUE THREAD

**Issue by kerrlabajo** [ultralytics/yolov5#12517]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

I would like to have the `export.py` the feature to manually save its exported model of the weights similar to how the `train.py` optionally has the `--project` and `--name` flags for manual saving.

### Use case

The location of the weights to be exported as `.onnx` is not easily accessible in my **AWS SageMaker Training/Exporting Image**. Therefore, the ideal scenario would be to export the model in `/opt/ml/model/` because SageMaker will automatically fetch from this directory, compresses the model, then stores it according to my `OutputDataConfig`. It was also indicated in **AWS SageMaker** that the algorithm should write the model artifacts in `/opt/ml/model/` and training results in `/opt/ml/output/data/` in order to comply the `OutputDataConfig`.
> Said use case was applicable to  `train.py` because it had the `--project` and `--name` flags that can be saved at `/opt/ml/output/data/` in the SageMaker.

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@kerrlabajo hi there! Thanks for reaching out. Your suggestion to add the functionality to manually save the exported model of the weights makes a lot of sense, especially for AWS SageMaker compatibility. We'll take this into consideration and keep you updated on any developments. Your willingness to submit a PR is also greatly appreciated. Thanks again for your contribution!
