### ISSUE TITLE
Use the torch.hub.load method to load model inference

### ISSUE THREAD

**Issue by yezi9527** [ultralytics/yolov5#12512]
![erro](https://github.com/ultralytics/yolov5/assets/106239707/3649bb2c-b408-4545-ab89-1ba6f0cd5b57)

**Comment by glenn-jocher** [comment]
@yezi9527 hey there! It looks like the input size of your image doesn't match the expected 320x320 size for the model. You can resize the input image to the required size using `torch.nn.functional.interpolate` or `cv2.resize` before passing it to the model for inference. This should help resolve the assertion error you're encountering. If you need more details, you can refer to the [Ultralytics Docs](https://docs.ultralytics.com/yolov5/).

Let me know if you need further assistance!

**Comment by yezi9527** [comment]
@glenn-jocher The image size I entered is 320x320!  
monitor = {
'left': 960,
'top': 480,
'width': 320,
'height': 320
}

sct = mss.mss()
img = np.array(sct.grab(monitor))
I don’t know why it was converted to 640x640 again.
