### ISSUE TITLE
pip install -r requirements.txt have some problems

### ISSUE THREAD

**Issue by xiaoyiwei199** [ultralytics/yolov5#12525]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

when i type pip install -r requirements.txt in vscode, always have problems in torch and torchversion
**torch>=1.8.0：**ERROR: Could not find a version that satisfies the requirement torch>=1.8.0 (from versions: none)
ERROR: No matching distribution found for torch>=1.8.0
**torchvision>=0.9.0：**ERROR: Ignored the following yanked versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3
ERROR: Could not find a version that satisfies the requirement torchvision>=0.9.0 (from versions: none)
ERROR: No matching distribution found for torchvision>=0.9.0

I already tried python 3.12, 3.8 3.7.2 3.7, all version of python have same problem.

**Comment by glenn-jocher** [comment]
@xiaoyiwei199 hi there! 😊 To troubleshoot the installation issue, please ensure you have the latest version of pip installed using `pip install --upgrade pip` and that you're using a compatible Python version (3.8 or 3.9). Also, check if your environment supports PyTorch, as it requires a system supporting CUDA 11.1. For further assistance, refer to the installation section in the [Ultralytics Docs](https://docs.ultralytics.com/yolov5/). Thank you!
