### ISSUE TITLE
Structure diagram of YOLOv5

### ISSUE THREAD

**Issue by ZCzzzzzz** [ultralytics/yolov5#12523]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I am now using yolov5 7.0 version, I now want to draw a yolov5 network structure diagram, I see that the Backbone and Head in the yolov5s.yaml file are all Conv modules, but I found that many people use CBS modules when drawing yolov5 7.0 version network structure diagrams, I want to know if this approach is correct, and whether to draw Conv or CBS or other when drawing the structure diagram?

**Comment by glenn-jocher** [comment]
@ZCzzzzzz hi there! To draw the YOLOv5 network structure diagram, you can use either Conv or CBS modules. The `yolov5s.yaml` file uses Conv modules, and some diagrams use CBS modules. Both approaches are correct, so feel free to choose the one that suits your preference. You can refer to the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/ for more details. Good luck with your diagram! 👍
