### ISSUE TITLE
RuntimeError: result type Float can't be cast to the desired output type long int

### ISSUE THREAD

**Issue by YangWulve** [ultralytics/yolov5#12529]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

RuntimeError: result type Float can't be cast to the desired output type long int

It occurrs only in training, and detect.py works well.

### Environment

- Version: YOLOv5 v6.1
- OS: Ubuntu 20.04
- Python: 3.8
- Environment: CUDA11.2, and other are the same as requirements.txt

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by YangWulve** [comment]
I've tried to add '''gain = gain.long()''' at line 218 in utils/loss.py , and it seems to be work. But its strange.

**Comment by glenn-jocher** [comment]
@YangWulve great, thanks for sharing your solution! We're always grateful for community contributions. The YOLO community and the Ultralytics team really appreciate your help in making YOLOv5 better for everyone. If the solution works for you, that's wonderful. We'll investigate further and consider incorporating it into the codebase. Thank you!

**Comment by Hyrtsi** [comment]
@YangWulve can you please share your code and full stack trace? We can't know how to reproduce the error.

**Comment by YangWulve** [comment]
Hi, @Hyrtsi. Thank you for your response. I'm more than willing to provide the requested information. I have encountered the bug while strictly following the instructions outlined in the README. Below is the relevant code snippet:

`python train.py --data coco.yaml --cfg yolov5m.yaml --weights 'checkpoint in my path' --batch-size 64`

And here is the stack trace:
![runTimeError](https://github.com/ultralytics/yolov5/assets/54839060/665cff78-6d38-4735-9c7f-cc1a83fec83c)

It seems the issue arises even when adhering to the documented procedure. Please let me know if there's anything else I can provide or if further clarification is needed. I'm eager to collaborate on resolving this matter.

Best regards,

**Comment by glenn-jocher** [comment]
Hi @YangWulve, thanks for providing the details! Unfortunately, I can't view the image of the stack trace directly from the link. Could you please copy and paste the text of the error message here? This will help us better understand the exact point of failure and guide you more effectively. Looking forward to your response! 😊
