### ISSUE TITLE
Inference Resolutions,Parameters and TensorRT Usage in 1280x1280 models

### ISSUE THREAD

**Issue by harunalperentoktas** [ultralytics/yolov5#12522]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello. First of all, I have read the issues and documentation related to this topic. Although there are answers to my questions in different topic headings, I couldn't generally reach the result I wanted. The subject I want to ask about is the usage of 1280x1280 models and running these models with Tensor RT support.

First of all, during training, we set the model input to 1280 using the "--img" command. We also choose the yolov5n6 from the 1280 model family available in the YOLOv5 repository. We started the model training with appropriate commands. At the end of the day, we have our own fine-tuned yolov5n6 model specific to our custom dataset (with images at a resolution of 1920x1080, 16x9 aspect ratio).

Now, when using this model during the inference stage, if we don't specify a size parameter, it defaults to 640. However, if we specify a size parameter of 1280, it uses 1280 as the size.

Now, here's a question that arises: How does an architecture designed to work with 1280x1280 input images handle 640x640 inputs? Shouldn't the input size of an architecture be fixed? When the 1280-size model is used, the inference time increases, while it decreases with 640. This situation indicates that the model operates differently at different input sizes and even slows down as the size increases. It is possible to observe this phenomenon in detect.py as well. In short, how can it be possible?

My first question was about inference. Now I'm moving on to the part about TensorRT. When I want to use TensorRT, my intention is actually to keep the input size the same at 1280x1280. I just want to optimize the architecture to work better on NVIDIA devices. This way, an inference process running at 20 Hz should increase to 30 or 40 Hz.

Using Export.py, I can successfully generate a .engine model with a resolution of 1280x1280. The only thing to be aware of in Export.py is that the resolutions provided should be multiples of 64 because the stride value is set to 64 in common.py.

The problem arises during inference. When I want to perform inference with the .engine model, it tells me that the expected input for the engine model is 1,3,1280,1280, but the image I provide is 1,3,1280,960. So, there is a resolution problem. If I update the size parameter to 1280x1280 during inference, I still encounter a problem. It is highly likely that the software you are using internally resizes the input from 1920x1080 to 1280x960 for a specific reason.
To solve these issues, I resized my input image to 1280x1280 using cv2.resize, and I provided the [1280,1280] size parameter. Only then were I able to run it with TensorRT.

With the methods I mentioned at the end, I can create the desired TensorRT engine model. It just needs to be a multiple of 64. For example, I create a 960x960 model and resize the source image to 960x960 myself, and it works. Is this process correct? Can we adjust engine models to the desired resolution?

If you can provide more clarity on the topics I mentioned, I would greatly appreciate it. Thank you in advance.

**Comment by glenn-jocher** [comment]
@harunalperentoktas hi there! Thanks for reaching out with your detailed inquiry. It's great that you delved into various documentation and issues related to your questions. Regarding your first point, YOLOv5 architecture is designed to handle various input sizes, with internal resizing mechanisms in place. For TensorRT usage, the correct input size is crucial for inference.

In terms of TensorRT, it's key to ensure that the input dimensions align precisely with the model's expected input shape to avoid issues. Your approach of resizing input images to 1280x1280 using cv2.resize and providing [1280,1280] as the size parameter is correct for running with TensorRT.

I appreciate your active engagement with YOLOv5 and thank you for your valuable contribution to the community. If you need further assistance, feel free to ask. Cheers!

**Comment by harunalperentoktas** [comment]
Thank you for your kind words. I believe you have resolved my question regarding TensorRT. Moreover, from what you mentioned, I understand this: if the aspect ratio of the input image I provide deviates from 1:1, your software can still operate it with a different input (let's assume the default value is 640), right? For example, consider a 640x640 model. Due to my input size(aspect ratio), perhaps the software internally processes it with values like 576x484 or 1280x960 etc.

I think that this value might not be able to exceed the resolution, but at least it could be a lower value.(May be for 640x640 it is not suitable for 1280x960, I just shared for example).

I understand that we should not expect the image to be 640x640 just because we set the size parameter to 640x640.This situation is also somewhat related to maintaining the aspect ratio with using internal resizing mechanisms.

**Comment by glenn-jocher** [comment]
@harunalperentoktas you're spot on! The YOLOv5 software indeed incorporates internal resizing mechanisms, allowing it to process non-1:1 aspect ratio images, like 16:9 or others, with different internal input sizes such as 576x484 or 1280x960, though they won't exceed the model's resolution. This behavior ensures maintaining the aspect ratio and makes the software adaptable to various input dimensions. Your understanding aligns perfectly with the internal resizing logic. If there's anything else you'd like to discuss, feel free to ask. Happy to help!

**Comment by harunalperentoktas** [comment]
I appreciate for the quick responses. I'm closing the issue.

**Comment by glenn-jocher** [comment]
@harunalperentoktas you're welcome! If you have any more questions in the future, don't hesitate to ask. Have a great day and happy coding!
