### ISSUE TITLE
speed estimate using yolo5 - put coridantes of cars in xml file or csv

### ISSUE THREAD

**Issue by gchinta1** [ultralytics/yolov5#12527]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hi i am using yolo5 py porchand i can detect cars and everything ok but i have a code for speed detecting but needs cars cordinates . can i do someting else using only yolo for speed at my video?

thank you for help
![Screenshot (10)](https://github.com/ultralytics/yolov5/assets/150929924/31d9e3be-76dc-45f1-9434-0c4776546510)

**Comment by glenn-jocher** [comment]
@gchinta1 you can use YOLOv5 to detect cars and extract their coordinates. Then you can use this information for speed detection in your video. Check out the documentation for examples on how to extract bounding box coordinates. Good luck!

**Comment by gchinta1** [comment]
> @gchinta1 you can use YOLOv5 to detect cars and extract their coordinates. Then you can use this information for speed detection in your video. Check out the documentation for examples on how to extract bounding box coordinates. Good luck!
First of all thank you for your answer . I can download the coordinates of each box but in txt files and for each .. can I put all of them in csv file directly ? Or what else can I do?

**Comment by glenn-jocher** [comment]
@gchinta1 you can definitely convert the bounding box coordinates from the txt files to a single CSV file. You can iterate through each txt file, extract the coordinates, and write them to a CSV file using Python's CSV module or a library like Pandas. Check out the Ultralytics Docs for information on how to handle bounding box coordinates and file operations. Good luck!

**Comment by gchinta1** [comment]
![Screenshot (11)](https://github.com/ultralytics/yolov5/assets/150929924/4808ecf3-cf73-43a0-9520-39379f058afe)
![Screenshot (12)](https://github.com/ultralytics/yolov5/assets/150929924/491cf908-6e01-44a1-b050-256024d46924)

and this the right detect from yolo
 After doing csv from txt the positions not are corecly in video .. what am doing wrong?

this is the code:
import cv2
import csv

def read_positions_from_csv(csv_file_path):
    positions = []
    with open(csv_file_path, 'r') as csvfile:
        csv_reader = csv.reader(csvfile)


        next(csv_reader, None)

        for row in csv_reader:
            frame_number = int(row[0])
            x_min, y_min, x_max, y_max = map(float, row[1:5])

            positions.append((frame_number, (x_min, y_min, x_max, y_max)))

    return positions


def detect_cars_and_display(video_path, positions):
    cap = cv2.VideoCapture(video_path)

    for frame_number, (x_min, y_min, x_max, y_max) in positions:
        ret, frame = cap.read()
        if not ret:
            break

        
        frame_height, frame_width, _ = frame.shape
        x_min_pixel = int(x_min * frame_width)
        y_min_pixel = int(y_min * frame_height)
        x_max_pixel = int(x_max * frame_width)
        y_max_pixel = int(y_max * frame_height)

       
        cv2.rectangle(frame, (x_min_pixel, y_min_pixel), (x_max_pixel, y_max_pixel), (0, 255, 0), 2)

    
        cv2.imshow('Detected Cars', frame)
        if cv2.waitKey(30) & 0xFF == 27:  # Press 'Esc' to exit
            break

    cap.release()
    cv2.destroyAllWindows()


csv_file_path = 'Combined_Products.csv'  # Replace with the actual path to your CSV file
video_path = 'output2.mp4'  # Replace with the actual path to your video file
positions = read_positions_from_csv(csv_file_path)


detect_cars_and_display(video_path, positions)

**Comment by glenn-jocher** [comment]
@gchinta1 it seems like the issue could be with the position normalization. Make sure that you are correctly converting the coordinates from relative values (0-1) to pixel values for displaying the bounding boxes. You may need to multiply the x and y coordinates by the width and height of the frame, respectively. I recommend checking the normalization process and verifying that it aligns with your video dimensions. Good luck!
