### ISSUE TITLE
need help couldnt open shared event and best.pt

### ISSUE THREAD

**Issue by aarikg** [ultralytics/yolov5#12524]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

RuntimeError: Couldn't open shared event: <000001E5E071B4C2>, error code: <2>
RuntimeError: File runs\train\exp13\weights\best.pt cannot be opened.

This happened during epoch 3/5 and another time during epoch 7/100.

**Comment by glenn-jocher** [comment]
@CloudZeno hi there! It looks like you're encountering difficulties opening shared event files and the best.pt file during training. These errors can occur if the specified paths are incorrect or if the files are corrupted. Please ensure that the paths are accurate and the files are accessible. If the issue persists, feel free to refer to the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/ for further guidance. Good luck with your training!
