### ISSUE TITLE
How to draw pr curve？

### ISSUE THREAD

**Issue by ZwNSW** [ultralytics/yolov5#1252]
## ❔Question
When I use the code shown below to draw the pr curve, the output curve actually looks like this. The color of each category is gray. What should I do to make the color of the curve of each category different?
    if plot:
        py = np.stack(py, axis=1)
        fig, ax = plt.subplots(1, 1, figsize=(5, 5))
        ax.plot(px, py, linewidth=0.6, color='green')  # plot(recall, precision)
        ax.plot(px, py.mean(1), linewidth=0.6, color='r', label='all classes')
        ax.set_xlabel('Recall')
        ax.set_ylabel('Precision')
        ax.set_xlim(0, 1)
        ax.set_ylim(0, 1)
        plt.legend()
        fig.tight_layout()
        fig.savefig(fname, dpi=200)
![image](https://user-images.githubusercontent.com/57338462/97770577-8a448c00-1b6f-11eb-9f2e-cd16620e813f.png)

**Comment by glenn-jocher** [comment]
@ZwNSW you can modify PR Curve plotting here:
https://github.com/ultralytics/yolov5/blob/c8c5ef36c9a19c7843993ee8d51aebb685467eca/utils/general.py#L305-L317

**Comment by ZwNSW** [comment]
@glenn-jocher Hello,thanks for your reply,when I run this code shown below,the PR that appears is like this,I have three categories,but all labels are the same。Therefore, I need to add AP and the correct label to the picture.There is another problem. If the curves are all gray, then you cannot know which category that curve is.
Thanks！
    if plot:
        py = np.stack(py, axis=1)
        fig, ax = plt.subplots(1, 1, figsize=(5, 5))
        ax.plot(px, py, linewidth=0.5,label="WMI")  # plot(recall, precision)
        ax.plot(px, py.mean(1), linewidth=0.6, color='r', label='all classes %.3f mAP@0.5' % ap[:, 0].mean())
        ax.set_xlabel('Recall')
        ax.set_ylabel('Precision')
        ax.set_xlim(0, 1)
        ax.set_ylim(0, 1)
        plt.legend()
        fig.tight_layout()
        fig.savefig(fname, dpi=200)
![image](https://user-images.githubusercontent.com/57338462/97793682-30ed6300-1c2a-11eb-84c4-20e7a1f0cd88.png)

**Comment by glenn-jocher** [comment]
@ZwNSW thanks for the feedback! Yes this is true all classes plot as grey in the default plot. This is because for larger datasets like COCO with 80 classes it's not possible to display a per-class legend.

Perhaps you could submit a PR with the modifications you had in mind and we can look it there?

**Comment by ZwNSW** [comment]
![image](https://user-images.githubusercontent.com/57338462/97822349-81c78f00-1cf0-11eb-9e9e-ba243f16d525.png)

**Comment by ZwNSW** [comment]
I followed the modifications you gave, and the problem was that I couldn’t label each category.
