### ISSUE TITLE
how can I keep count of the number of times an object was detected in a video stream? 

### ISSUE THREAD

**Issue by Dbhasin1** [ultralytics/yolov5#1253]
for eg if I have 3 brands being detected in a single video, pepsi, coca-cola and sprite I want a dictionary as below:
{ pepsi: x, coca-cola: y, sprite: z }
where x, y and z are the number of times they were detected

**Comment by glenn-jocher** [comment]
@Dbhasin1 you would sum statistics inside detect.py.

**Comment by Dbhasin1** [comment]
Can you be more specific?

**Comment by Dbhasin1** [comment]
@glenn-jocher Can you be more specific? the code inside detect.py is utilizing a lot of external functions, so where exactly do I need to make my changes?

**Comment by glenn-jocher** [comment]
@Dbhasin1 all detections are printed to screen and saved to text here:
https://github.com/ultralytics/yolov5/blob/ca290dca2427fef69b687d98ac99497c27cad144/detect.py#L98-L114

**Comment by Dbhasin1** [comment]
Thank you @glenn-jocher
