### ISSUE TITLE
Can PT files trained by yolov5 be used by yolov7?

### ISSUE THREAD

**Issue by ly1035327995** [ultralytics/yolov5#12532]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Can PT files trained by yolov5 be used by yolov7?

**Comment by glenn-jocher** [comment]
@ly1035327995 yes, YOLOv5 PT files can be used with YOLOv7. The models are forward compatible. You can find more information in the Ultralytics Docs at https://docs.ultralytics.com/yolov5/.
