### ISSUE TITLE
When running the validation set to save labels, there is no labels folder in the expX folder.

### ISSUE THREAD

**Issue by Gary55555** [ultralytics/yolov5#12534]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

When running the validation set to save labels, there is no labels folder in the expX folder. Therefore, line 261 of code val.py will report an error. Should I add code here:

### Minimal Reproducible Example

if save_txt:
   if not os.path.isdir(save_dir / 'labels'):
      os.mkdir(save / 'labels')
   save_one_txt(predn, save_conf, shape, file=save_dir / 'labels' / f'{path.stem}.txt')

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Gary55555 thanks for reporting. The "labels" folder should indeed be created in the validation set. You can add the following lines before line 261 in val.py:

```python
if save_txt:
    (save_dir / 'labels').mkdir(parents=True, exist_ok=True)
```

Thanks for offering to help with a PR! Your support is appreciated.
