### ISSUE TITLE
wrong params when training and saving ckpt model

### ISSUE THREAD

**Issue by wongs19** [ultralytics/yolov5#12542]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi. I used yolo5s.pt and custom dataset to train. And I use command: torch.load("best.pt"). The dict result shows like this:
epoch -1
best_fitness None
ema None
updates None
optimizer None

That is completely different from what I understand. But I check the code saving ckpt, it seems the code is OK.

I wonder that whether is it a problem with my understanding or a problem with the training process?

**Comment by glenn-jocher** [comment]
@wongs19 hi there! It seems like you are trying to load a model checkpoint using `torch.load("best.pt")` and encountering unexpected results. The issue might be related to the loading process. The training process typically saves checkpoints using `model.save('best.pt')` and then loads them using `model.load('best.pt')`. Please refer to the [Ultralytics Docs](https://docs.ultralytics.com/yolov5/) for detailed guidance on training and saving checkpoints. Let me know if you have any more questions!

**Comment by wongs19** [comment]
> @wongs19 hi there! It seems like you are trying to load a model checkpoint using `torch.load("best.pt")` and encountering unexpected results. The issue might be related to the loading process. The training process typically saves checkpoints using `model.save('best.pt')` and then loads them using `model.load('best.pt')`. Please refer to the [Ultralytics Docs](https://docs.ultralytics.com/yolov5/) for detailed guidance on training and saving checkpoints. Let me know if you have any more questions!

Yes I Know your meaning. But in the training process, it used `torch.save(ckpt, best)` to save the best model. So I used `torch.load("best.pt")` to get the best model for inference. And then I got the wrong params.

**Comment by glenn-jocher** [comment]
@wongs19 I see, thanks for the details. It's possible that the `torch.save(ckpt, best)` approach differs from the YOLOv5 convention. Let's configure the correct method for saving and loading checkpoints for YOLOv5. You can refer to the [Ultralytics Docs](https://docs.ultralytics.com/yolov5/) for proper usage and examples. If any issues persist, feel free to ask for further assistance!

**Comment by wongs19** [comment]
> @wongs19 I see, thanks for the details. It's possible that the `torch.save(ckpt, best)` approach differs from the YOLOv5 convention. Let's configure the correct method for saving and loading checkpoints for YOLOv5. You can refer to the [Ultralytics Docs](https://docs.ultralytics.com/yolov5/) for proper usage and examples. If any issues persist, feel free to ask for further assistance!

I see.I know why `torch.load(best.pt)` loads the model file with `epoch=-1` and `optimizer= None`. The reason is that after training is completed, the model will be tested in the val data set, and strip_optimizer(f) will be called. This statement will set the value of these keys to None or -1. I tested deleting this line of code and found that the size of best.pt is 40MB, and adding strip_optimizer(f), the size of the model file is 14MB. So this line of code is to streamline the model file?

**Comment by glenn-jocher** [comment]
@wongs19 Exactly! The `strip_optimizer(f)` function in YOLOv5 is designed to streamline the model file by removing optimizer-related information, resulting in reduced file size. It's intended for sharing or deploying models without optimizer state, and it does not affect the model weights themselves. The behavior you observed is a part of this optimization process. If you have any more questions or need further clarification, feel free to ask!
