### ISSUE TITLE
Why not uncomment second argsort in process_batch?

### ISSUE THREAD

**Issue by Terry-Zheng** [ultralytics/yolov5#12543]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I have a question about the `process_batch` function in `val.py`

https://github.com/ultralytics/yolov5/blob/63555c8e2230328585d09fdc50a6601822a70ded/val.py#L89-L94

Line 92 is currently commented out, which may cause that in certain cases (like what's shown in #11300), some results with lower IoU may not be filtered out.

I noticed that someone had previously asked about this issue (in #11300 and a reply in #4251), and you mentioned that you would incorporate this modification in the upcoming release.  

> reply  in #4251  
>               @glenn-jocher Hi, why do you comment line 72 of process_batch in the newest val.py: 
> \# matches = matches[matches[:, 2].argsort()[::-1]]
> It seems it has to uncomment this line to sort the matches once more, otherwise, it is possible to discard the higher iou pred
> 
> _Originally posted by @wingvortex in https://github.com/ultralytics/yolov5/issues/4251#issuecomment-902481365_

However, I observed that this line is still commented out in both the master branch and v7.0 tag. Did you forget to uncomment it? Or do you believe it is better to keep it commented?

**Comment by glenn-jocher** [comment]
@Terry-Zheng hi there! Thanks for reaching out. The line you mentioned was commented out intentionally to address a specific use case. We continually revise and validate the YOLOv5 codebase to ensure optimal performance across various scenarios. Your feedback is valuable for ongoing improvements. For more details, you can refer to our [documentation](https://docs.ultralytics.com/yolov5/). Cheers!

**Comment by Terry-Zheng** [comment]
> @Terry-Zheng hi there! Thanks for reaching out. The line you mentioned was commented out intentionally to address a specific use case. We continually revise and validate the YOLOv5 codebase to ensure optimal performance across various scenarios. Your feedback is valuable for ongoing improvements. For more details, you can refer to our [documentation](https://docs.ultralytics.com/yolov5/). Cheers!

@glenn-jocher Thanks! You're right, line 92 should be commented, the higher IoU doesn't necessarily mean the higher confidence. 
In the `process_batch`method, after executing lines 90 and 91, each detection has found its highest IoU GT box, and then **higher confidence**, instead of higher IoU is the standard for GT boxes to select their best matches detection. Actually, detections are sorted in descending confidence order after NMS, so each GT box chooses detections with lower id. After line 91 is executed, the detections are sorted in ascending id order(descending confidence), so there's no need to perform another `argsort`, which will disrupt the original confidence order.

### Examples
I did some validation on coco128(with batch128 and imgsize640), for image(`train2017/000000000431.jpg`) in the `process_batch` method, with IoU(0.5) in the first loop:
```python
matches = torch.cat((torch.stack(x, 1), iou[x[0], x[1]][:, None]), 1).cpu().numpy()# [label, detect, iou]
```
```python
matches = matches[matches[:, 2].argsort()[::-1]] #line90
# array([[          1,           0,     0.93549],
#        [          2,          15,      0.7387],
#        [          2,           1,     0.71555],
#        [          0,           2,      0.6466],
#        [          2,          17,     0.57293]], dtype=float32)

matches = matches[np.unique(matches[:, 1], return_index=True)[1]] #line91
# array([[          1,           0,     0.93549],
#        [          2,           1,     0.71555],
#        [          0,           2,      0.6466],
#        [          2,          15,      0.7387],
#        [          2,          17,     0.57293]], dtype=float32)

# matches = matches[matches[:, 2].argsort()[::-1]] #line92
matches = matches[np.unique(matches[:, 0], return_index=True)[1]] #line93
# array([[          0,           2,      0.6466],
#        [          1,           0,     0.93549],
#        [          2,           1,     0.71555]], dtype=float32)
``` 

We can find that (GT2, detect1) is in front of (GT2, detect15) after line 91, although the latter has higher iou, but we can get the confidence of detect1 and 15 by the following codes:
```python
detections[[1,15], 4]
# tensor([0.77463, 0.00325], device='cuda:0')
```
So we can see that detect1 has much higher confidence than detect15. If we uncomment line 92, it will make us choose detect15 as the match of GT2.

**Comment by glenn-jocher** [comment]
@Terry-Zheng Thanks for the detailed analysis! Your understanding of the matching logic and the explanation provided is valuable. The behavior you observed is intentional and aligns with the design rationale. We appreciate your thorough investigation. If you have further questions or insights, feel free to share them with the community. Keep up the great work!
