### ISSUE TITLE
Confusions about EMA model and training phase

### ISSUE THREAD

**Issue by linhezheng19** [ultralytics/yolov5#1254]
## ❔Question
@glenn-jocher Hi, excuse me to disturbing you, I have some questions about EMA model and training phase.
1. Is that the EMA model used to get better evaluation results, it does not help training the normal model? Because I note the update function in EMA class just update the copy of normal model, it doesn't change anything of the normal model?

2. After 30 epoches, the test mAP is falling down gradually, is that normal? If it is not normal, do you have any idea about the problem?

## Additional context
```
def update(self, model):
        # Update EMA parameters
        with torch.no_grad():
            self.updates += 1
            d = self.decay(self.updates)

            msd = model.module.state_dict() if self.is_parallel(model) else model.state_dict()  # model state_dict
            for k, v in self.ema.state_dict().items():
                if v.dtype.is_floating_point:
                    v *= d
                    v += (1. - d) * msd[k].detach()
```

**Comment by glenn-jocher** [comment]
@LinhzTT EMA does not affect base model

**Comment by linhezheng19** [comment]
> @LinhzTT EMA does not affect base model

Thank you for your reply.

**Comment by glenn-jocher** [comment]
@LinhzTT also FYI the EMA is what is saved to checkpoints, so when training completes you will have two EMAs saved: best.pt and last.pt. The base model is not retained.

**Comment by linhezheng19** [comment]
@glenn-jocher Does this mean that if the training stops in the middle, we can only resume from the EMA model？ Which will affect the final result?

**Comment by glenn-jocher** [comment]
@LinhzTT yes --resume resumes from the EMA. This doesn't have much effect, as the EMA is essentially a steady version of the noisier base. The new base (old EMA) quickly starts to act like the old base via noisy losses and parameter updates and the new EMA continues smoothly from the previous EMA.

**Comment by glenn-jocher** [comment]
@LinhzTT see https://github.com/ultralytics/yolov5/pull/765#issuecomment-677986424 for example of --resume results.

**Comment by linhezheng19** [comment]
@glenn-jocher Understood, thanks for your reply.
