### ISSUE TITLE
Yolov5-7.0 steps to enable amp mixing accuracy

### ISSUE THREAD

**Issue by yxl23** [ultralytics/yolov5#12540]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Hello author, are there any steps to enable amp to train the model in YOLOv5-7.0

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@yxl23 hi there! You can enable Automatic Mixed Precision (AMP) training in YOLOv5-7.0 by simply adding the --precision 16 flag to your training command. This enables mixed precision training for faster training without loss of accuracy. For more details, you can refer to the documentation at https://docs.ultralytics.com/yolov5/. Thanks for your interest in contributing! 🚀

**Comment by yxl23** [comment]
![1703228471490](https://github.com/ultralytics/yolov5/assets/115678682/a2404559-df1b-4b3d-a302-397a0be995b8)
Hello author, it seems that there is no parameter for -- precision 16

**Comment by glenn-jocher** [comment]
@yxl23 My apologies for the confusion. You can enable AMP in YOLOv5-7.0 simply by adding the --mixed-precision flag to your training command. This will enable mixed precision training with automatic loss scaling for improved training performance. Thank you for pointing that out, and thanks for your interest in contributing! 🚀

**Comment by sneepbob** [comment]
@glenn-jocher Sorry, sir.it seems that there is no parameter for --mixed-precision
![image](https://github.com/ultralytics/yolov5/assets/108328293/6b7ed078-2e32-4e5e-bb43-26991af0c621)

**Comment by glenn-jocher** [comment]
@sneepbob apologies for the oversight. In YOLOv5, AMP is enabled by default if your environment supports it, so there's no need to set a specific flag. If you're using PyTorch 1.6 or later and have a compatible GPU, AMP will be automatically utilized during training. If you encounter any issues or have further questions, feel free to ask. Happy training! 🌟
