### ISSUE TITLE
AssertionError: train: No labels found in /content/drive/MyDrive/Colab/Fishai-10/train/labels.cache, can not start training.

### ISSUE THREAD

**Issue by lpkpaco** [ultralytics/yolov5#12548]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am currently using Google Colab and Roboflow to generate and train my dataset. However, I get this error message everytime when I start training.
I have looked up for solutions, like using !chmod to grant access, maintaining the directory structure etc. These methods did not work.
What should I do?
![image](https://github.com/ultralytics/yolov5/assets/50955568/b54af7bd-29df-4740-a4c0-860183e2cc18)

Here is the code that I used:
`!chmod +w /content/drive/MyDrive/Colab/Fishai-10/train/labels
 !chmod +w /content/drive/MyDrive/Colab/Fishai-10/valid/labels
 !python /content/drive/MyDrive/Colab/yolov5/train.py --batch 100 --epochs 2000 --img 640 --data 
 '/content/drive/MyDrive/Colab/Fishai-10/data.yaml' --weights yolov5s.pt --patience 100
 from google.colab import runtime
 runtime.unassign()`

And I get:
[error_message.txt](https://github.com/ultralytics/yolov5/files/13759355/error_message.txt)

**Comment by glenn-jocher** [comment]
@lpkpaco hey there! It seems like the training process is unable to find any labels in the specified location. Here's what you can do to troubleshoot.

First, ensure that your label files are correctly located in the `/content/drive/MyDrive/Colab/Fishai-10/train/labels.cache` directory.

Next, check that the label files are in the correct format and contain the expected annotations.

Finally, make sure that the path to the label files is correctly specified in the data.yaml file.

Let me know if you need more help with this!

**Comment by lpkpaco** [comment]
This is my data.yaml:
![image](https://github.com/ultralytics/yolov5/assets/50955568/457fb66b-e517-4597-8a56-54d76777ef29)

I think it is correct.
For more information, here are a few images for training and their label txt files:
![Photo-2023-12-21-16-51-58_jpg rf 6ecd133bbbfd1eb26fcfd274c976a19e](https://github.com/ultralytics/yolov5/assets/50955568/ec4f7422-6975-439e-b672-daac19a59761)
![IMG_6924_JPG rf 523331e9a276657f2fe07e2318ffaf25](https://github.com/ultralytics/yolov5/assets/50955568/d3c624c3-3bfb-43e6-b6a5-807ede0b66f7)
![Photo-2023-12-18-16-14-43_jpg rf 9ecfc7daa2f5abe2b679cd0aea08b484](https://github.com/ultralytics/yolov5/assets/50955568/fd7f2a24-255f-4149-b442-37e96af322cb)
[Photo-2023-12-21-16-51-58_jpg.rf.6ecd133bbbfd1eb26fcfd274c976a19e.txt](https://github.com/ultralytics/yolov5/files/13760753/Photo-2023-12-21-16-51-58_jpg.rf.6ecd133bbbfd1eb26fcfd274c976a19e.txt)
[IMG_6924_JPG.rf.523331e9a276657f2fe07e2318ffaf25.txt](https://github.com/ultralytics/yolov5/files/13760754/IMG_6924_JPG.rf.523331e9a276657f2fe07e2318ffaf25.txt)
[Photo-2023-12-18-16-14-43_jpg.rf.9ecfc7daa2f5abe2b679cd0aea08b484.txt](https://github.com/ultralytics/yolov5/files/13760756/Photo-2023-12-18-16-14-43_jpg.rf.9ecfc7daa2f5abe2b679cd0aea08b484.txt)

And here is the labels.cache file (I couldn't drop it here in GitHub as the file type is not supported):
[https://drive.google.com/file/d/1rZnvHzgIDU3V6UKioMNMido-vuEelXMx/view?usp=sharing](labels.cache)

I don't know what's going wrong.
Thanks for your help.

**Comment by glenn-jocher** [comment]
@lpkpaco your data.yaml configuration looks good. The label files and images are also in the correct format. However, I noticed that your labels are in ".txt" format, whereas the error message references "labels.cache". 

YOLOv5 expects labels to be in the COCO JSON format or YOLO txt format. Therefore, you might want to check the label caching process in your training pipeline.

Let me know if you need further assistance!

**Comment by lpkpaco** [comment]
I found a solution but I don't know if it would work next time.
Apparently something is wrong while Roboflow is processing some data. I exported the file in COCO format first after resizing and auto-orientation and uploaded it to a new project then exported it without committing any pre-processing or augmentations. It seems to work again. 
Thanks for your help anyways.

**Comment by lpkpaco** [comment]
I found a solution but I don't know if it would work next time.
Apparently something is wrong while Roboflow is processing some data. I exported the file in COCO format first after resizing and auto-orientation and uploaded it to a new project then exported it without committing any pre-processing or augmentations. It seems to work again. 
Thanks for your help anyways.

**Comment by glenn-jocher** [comment]
@lpkpaco I'm glad to hear you found a workaround by adjusting the data processing steps in Roboflow. It's possible that an issue during the preprocessing or augmentation stages could have affected the label files or their paths. 

For future reference, if you encounter similar issues, consider verifying each step of the data preparation process to ensure consistency and correctness of the data format before training.

If you have any more questions or run into any other issues, feel free to reach out. Happy training! 🚀

**Comment by Basketball50** [comment]
I am experiencing the same issue. It says: "No labels found in /content/Train/Images/Backpack.cache, training may not work correctly" and "No labels found in /content/Test/Images/Backpack.cache" My image files and label files have the same name and are formatted correctly. Here is an image of the structure of my folders (I am using google colab). 

<img width="176" alt="Image" src="https://github.com/user-attachments/assets/d7be6671-b5dd-4427-bf6c-e010a42275c7" />

**Comment by lpkpaco** [comment]
Hi @GreaterthanGreat,

  I couldn’t locate why did that issue happen, probably has something to do with Colab and my Roboflow exporting process. My suggestion is: you can try yolov8 if using yolov5 is not a requirement for your project. I switched to yolov8 and such problems did not happen again. The support for v8 is also better.

**Comment by Basketball50** [comment]
> Hi [@GreaterthanGreat](https://github.com/GreaterthanGreat),
> 
> I couldn’t locate why did that issue happen, probably has something to do with Colab and my Roboflow exporting process. My suggestion is: you can try yolov8 if using yolov5 is not a requirement for your project. I switched to yolov8 and such problems did not happen again. The support for v8 is also better.


Thx for the advice

I was using Yolov11 originally. Just switched yolov8 and still got the same problem.

**Comment by pderrenger** [comment]
If you're encountering the same issue with YOLOv8 after switching, the problem may lie in your dataset structure or export process. Double-check your dataset paths in the `data.yaml` file and ensure the labels directory contains `.txt` files with the correct YOLO format. Additionally, verify your dataset export settings in Roboflow to confirm compatibility. Refer to [Ultralytics YOLOv8 Docs](https://docs.ultralytics.com/) for dataset preparation guidance. Let me know if you need further clarification!

**Comment by Basketball50** [comment]
> If you're encountering the same issue with YOLOv8 after switching, the problem may lie in your dataset structure or export process. Double-check your dataset paths in the `data.yaml` file and ensure the labels directory contains `.txt` files with the correct YOLO format. Additionally, verify your dataset export settings in Roboflow to confirm compatibility. Refer to [Ultralytics YOLOv8 Docs](https://docs.ultralytics.com/) for dataset preparation guidance. Let me know if you need further clarification!

My folder structure is the following. 

<img width="176" alt="Image" src="https://github.com/user-attachments/assets/261ac497-f9e2-42ba-b31f-45925b8ccabd" />

Could the problem be that I have more folders within the Images and Labels folder and that where my images and labels are stored?

**Comment by pderrenger** [comment]
@GreaterthanGreat yes, the issue could be due to having subfolders within the `Images` and `Labels` directories. YOLO expects the images and their corresponding label `.txt` files to be directly under the respective folders specified in `data.yaml`. Ensure there are no nested subfolders, and all files are properly aligned. If subfolders are necessary, update the `data.yaml` paths to point to a `.txt` file listing all image paths instead. For more details, refer to the [YOLO dataset structure guidelines](https://docs.ultralytics.com/datasets/detect/).
