### ISSUE TITLE
Hello author, I would like to use two computers for distributed training of YOLOv5 and YOLOv8, which means I want to use multi-level multi card training. What do I need to do?

### ISSUE THREAD

**Issue by yxl23** [ultralytics/yolov5#12545]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello author, I would like to use two computers for distributed training of YOLOv5 and YOLOv8, which means I want to use multi-level multi card training. What do I need to do?

**Comment by glenn-jocher** [comment]
@yxl23 hi there! To set up distributed training for YOLOv5, you can use PyTorch's `torch.nn.parallel.DistributedDataParallel` module. It allows you to train across multiple GPUs and multiple machines. We have detailed guidance on this in our [Ultralytics Docs](https://docs.ultralytics.com/yolov5/). Feel free to check it out for step-by-step instructions. Cheers!
