### ISSUE TITLE
AttributeError: 'Model' object has no attribute 'stride'

### ISSUE THREAD

**Issue by mahilaMoghadami** [ultralytics/yolov5#12552]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hello
when I want to use another .yaml file, I get this error:
**AttributeError: 'Model' object has no attribute 'stride'** in line:
        if '_modules' in self.__dict__:
            modules = self.__dict__['_modules']
            if name in modules:
                return modules[name]
        raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
in module.py file

appreciate your help.
thank you

**Comment by glenn-jocher** [comment]
@mahilaMoghadami hi there! 😊

It looks like you might be using an incompatible .yaml file. Make sure your .yaml file is compatible with the YOLOv5 version you are using. You can find more information about the .yaml file format in the [Ultralytics documentation](https://docs.ultralytics.com/yolov5/).

Let me know if you need further assistance!

**Comment by mahilaMoghadami** [comment]
thak you

this is my .yaml content file:

# YOLOv5 🚀 by Ultralytics, GPL-3.0 license

# Parameters
nc: 80  # number of classes
depth_multiple: 1.0  # model depth multiple
width_multiple: 1.0  # layer channel multiple
anchors: 3
  # - [10,13, 16,30, 33,23]  # P3/8
  # - [30,61, 62,45, 59,119]  # P4/16
  # - [116,90, 156,198, 373,326]  # P5/32

# YOLOv5 v6.0 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [64, 6, 2, 2]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C3, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 6, C3, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, C3, [512]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 3, C3, [1024]],
   [-1, 1, SPPF, [1024, 5]],  # 9
  ]

# YOLOv5 v6.0 head
head:
  [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, C3, [512, False]],  # 13

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, C3, [256, False]],  # 17 (P3/8-small)

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 14], 1, Concat, [1]],  # cat head P4
   [-1, 3, C3, [512, False]],  # 20 (P4/16-medium)

   [-1, 1, Conv, [512, 3, 2]],
   [[-1, 10], 1, Concat, [1]],  # cat head P5
   [-1, 1, C3STR, [1024, False]],  # 23 (P5/32-large)

   [[2, 17, 20, 23], 1, CLLADetect, [nc, anchors]],  # Detect(P3, P4, P5)
  ]


which is TPH++  .yaml file.
all components are implemented.
where you think may cause problem?

**Comment by glenn-jocher** [comment]
@mahilaMoghadami The .yaml file you provided seems compatible and includes all the necessary components. Can you please ensure that you are using the latest version of YOLOv5? Also, make sure that your YOLOv5 installation is correct and that there are no conflicting versions in your environment.

Let me know if you need further assistance or encounter any more issues!
