### ISSUE TITLE
yolov5,yolov8的12种车牌检测和识别，准确率高达99%+，还有10G车牌开源数据!!!

### ISSUE THREAD

**Issue by pcb9382** [ultralytics/yolov5#12550]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

https://github.com/pcb9382/PlateRecognition

### Use case

https://github.com/pcb9382/PlateRecognition

### Additional

https://github.com/pcb9382/PlateRecognition

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@pcb9382 hi there! Thanks for your interest in YOLOv5. For suggestions and feature requests, please feel free to visit our [documentation](https://docs.ultralytics.com/yolov5/) and submit a pull request. Your contributions are greatly appreciated!
