### ISSUE TITLE
Replacing backbone with EfficientNet V2

### ISSUE THREAD

**Issue by sarajm95** [ultralytics/yolov5#12556]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello. I want to replace the backbone in YOLOv5 with EfficientNetV2. To do this, I modified the file yolov5n.yaml as follows and placed the used layers in the backbone in the common.py file. However, when running, I encounter the following error. Can you guide me on what might be causing the error? I have checked each layer and received the expected output by providing input, but when I run the program with the following parameters, I encounter a problem.

!python train.py --img 640 --batch 20 --epochs 10 --data custom_data.yaml --cfg models/yolov5n.yaml --cache --save_best
![IMG_20231229_134359_321](https://github.com/ultralytics/yolov5/assets/151884034/1bcf53c8-a7cb-45d2-9777-8204cbb83ddc)
![IMG_20231229_134416_454](https://github.com/ultralytics/yolov5/assets/151884034/70dc466f-4ef2-4403-a58b-9e7aad432985)
![IMG_20231229_134402_972](https://github.com/ultralytics/yolov5/assets/151884034/e51a1f8f-400d-47e3-9fbd-4bd5e66b6bec)

**Comment by glenn-jocher** [comment]
@sarajm95 thank you for your interest in YOLOv5 and your efforts to integrate EfficientNetV2 as the backbone. The error you're encountering could stem from several sources, like layer compatibility or input/output mismatches. Kindly make sure that the EfficientNetV2 layers are compatible with the YOLOv5 architecture. Also, cross-verify that the input and output shapes of each layer are as expected.

Your initiative and contributions to the YOLO community are commendable. For a detailed guide on customizing YOLOv5 architectures, please refer to our documentation at https://docs.ultralytics.com/yolov5/. Good luck with your implementation!
