### ISSUE TITLE
Any advice for detecting triangle which contains a number in the grayscale images?

### ISSUE THREAD

**Issue by myalos** [ultralytics/yolov5#12553]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Thanks for sharing the code, any advice for detecting triangle which contains a number in the grayscale images? Thanks in advance.

**Comment by glenn-jocher** [comment]
@myalos thanks for reaching out! You can train a YOLOv5 model to detect triangles that contain numbers by labeling the triangles and numbers in your grayscale images. Then, follow the training and inference instructions in the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/. Good luck!

**Comment by myalos** [comment]
Thanks for reply! I will try

**Comment by glenn-jocher** [comment]
@myalos you're welcome! If you have any more questions or need further assistance as you go along, feel free to ask. Happy training! 😊👍
