### ISSUE TITLE
Clothing.yaml file is missing for latest version

### ISSUE THREAD

**Issue by muralidhar972** [ultralytics/yolov5#1256]
Hello Team,

Congrats for developing the v5, it is awesome.

am working on the cloth data set, trying to implement on v5.

Got an error on clothing.yaml is missing. after doing research got know that you guys are updating the model.pt.

Any possibility to update the clothing.yaml 

Thanks for your supports

Regards,

**Comment by dongjuns** [comment]
@muralidhar972 Hi, I think you can make that clothing.yaml file, right? You can easily do that-! :sunglasses: 
But anyway, refer to this link.
<https://curiousily.com/posts/object-detection-on-custom-dataset-with-yolo-v5-using-pytorch-and-python/>

clothing.yaml
```
train: ../clothing/images/train/
val: ../clothing/images/val/
nc: 9
names:
  [
    "Jackets",
    "Jeans",
    "Shirts",
    "Shoes",
    "Skirts",
    "Tops",
    "Trousers",
    "Tshirts",
    "sunglasses",
  ]
```
