### ISSUE TITLE
 How to convert from json format with Polygon labels to YOLOv7 instance segmentation Without Roboflow?

### ISSUE THREAD

**Issue by Yuanchihwei** [ultralytics/yolov5#12560]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

   Epoch    GPU_mem   box_loss   seg_loss   obj_loss   cls_loss  Instances       Size
      7/299      18.3G    0.06648    0.05584    0.03083  0.0004405         92        640: 100%|██████████| 260/260 [41:52<00:00,  9.66s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 33/33 [02:55<00:00,  5.32s/
                   all       1038       4626      0.677      0.127      0.106     0.0427      0.673      0.119      0.101      0.037

      Epoch    GPU_mem   box_loss   seg_loss   obj_loss   cls_loss  Instances       Size
      8/299      18.3G     0.0655    0.05468    0.03018  0.0003959        167        640:  34%|███▍      | 88/260 [14:58<29:16, 10.21s/it]
Traceback (most recent call last):
  File "D:\yolov7-u7\yolov7-u7\seg\segment\train.py", line 681, in <module>
    main(opt)
  File "D:\yolov7-u7\yolov7-u7\seg\segment\train.py", line 577, in main
    train(opt.hyp, opt, device, callbacks)
  File "D:\yolov7-u7\yolov7-u7\seg\segment\train.py", line 295, in train
    for i, (imgs, targets, paths, _, masks) in pbar:  # batch ------------------------------------------------------
  File "D:\anaconda\Lib\site-packages\tqdm\std.py", line 1178, in __iter__
    for obj in iterable:
  File "D:\yolov7-u7\yolov7-u7\seg\utils\dataloaders.py", line 171, in __iter__
    yield next(self.iterator)
          ^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\Lib\site-packages\torch\utils\data\dataloader.py", line 630, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "D:\anaconda\Lib\site-packages\torch\utils\data\dataloader.py", line 1345, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\Lib\site-packages\torch\utils\data\dataloader.py", line 1371, in _process_data
    data.reraise()
  File "D:\anaconda\Lib\site-packages\torch\_utils.py", line 694, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\anaconda\Lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\Lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\Lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "D:\yolov7-u7\yolov7-u7\seg\utils\segment\dataloaders.py", line 116, in __getitem__
    img, labels, segments = mixup(img, labels, segments, *self.load_mosaic(random.randint(0, self.n - 1)))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\yolov7-u7\yolov7-u7\seg\utils\segment\augmentations.py", line 21, in mixup
    segments = np.concatenate((segments, segments2), 0)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 1 dimension(s)


******I did try to train with Yolov7-seg with "python segment/train.py --data data/custom.yaml --batch 16 --weights '' --cfg yolov7-seg.yaml --epochs 300 --name yolov7-seg --img 640 --hyp hyp.scratch-high.yaml", but it appears error above, i did search articals but I can't found how to convert from json format with Polygon labels to YOLOv7 instance segmentation Without Roboflow? Beside, format issue, any other problem could cause this error? 
Source: https://github.com/WongKinYiu/yolov7/tree/u7/seg 

Current, my label text is converted using Labelme2YOLO. 
Source: https://github.com/rooneysh/Labelme2YOLO

 I am coding beginner, Please top help me, thanks**.**** 

### Additional

n/a

**Comment by glenn-jocher** [comment]
@Yuanchihwei make sure you are using the latest code from the `Yolov7-seg` branch and have correct label formatting. Check out the YOLOv5 [docs](https://docs.ultralytics.com/yolov5/) for label format requirements. Good luck!

**Comment by mature-1111** [comment]
I meet with similar problem in yolov9.
Traceback (most recent call last):
  File "D:/zyqi/yolov9-main/segment/train.py", line 646, in <module>
    main(opt)
  File "D:/zyqi/yolov9-main/segment/train.py", line 542, in main
    train(opt.hyp, opt, device, callbacks)
  File "D:/zyqi/yolov9-main/segment/train.py", line 270, in train
    for i, (imgs, targets, paths, _, masks) in pbar:  # batch ------------------------------------------------------
  File "D:\anaconda3\envs\yolov9\lib\site-packages\tqdm\std.py", line 1181, in __iter__
    for obj in iterable:
  File "D:\zyqi\yolov9-main\utils\dataloaders.py", line 170, in __iter__
    yield next(self.iterator)
  File "D:\anaconda3\envs\yolov9\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "D:\anaconda3\envs\yolov9\lib\site-packages\torch\utils\data\dataloader.py", line 671, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\anaconda3\envs\yolov9\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\anaconda3\envs\yolov9\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\zyqi\yolov9-main\utils\segment\dataloaders.py", line 116, in __getitem__
    img, labels, segments = mixup(img, labels, segments, *self.load_mosaic(random.randint(0, self.n - 1)))
  File "D:\zyqi\yolov9-main\utils\segment\augmentations.py", line 16, in mixup
    segments = np.concatenate((segments, segments2), 0)
  File "<__array_function__ internals>", line 200, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 3 dimension(s)

**Comment by glenn-jocher** [comment]
It seems like there's a mismatch in the dimensions of your arrays during the concatenation process in the `mixup` function. This often occurs when the data isn't uniformly structured. Ensure all your `segments` arrays have the same number of dimensions before concatenation. A quick fix could be checking and reshaping arrays if necessary before the `np.concatenate` call. For example:

```python
if segments.ndim != segments2.ndim:
    # Reshape or handle arrays to match dimensions
    # Example reshaping to 3D if they are not:
    segments = segments.reshape(-1, segments.shape[0], segments.shape[1])
    segments2 = segments2.reshape(-1, segments2.shape[0], segments2.shape[1])
segments = np.concatenate((segments, segments2), 0)
```

This code is just a starting point; adjust as necessary based on your actual data structure. Good luck! 🚀

**Comment by mature-1111** [comment]
Yes,I do it. I have converted from json format with Polygon labels to YOLOv7 instance segmentation. The solution to this problem is to&nbsp;&nbsp;use hyp.scratch-high.yaml but set mixup to 0.0
&nbsp;


天空
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Glenn ***@***.***&gt;; 
发送时间: 2024年4月18日(星期四) 凌晨4:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ultralytics/yolov5]  How to convert from json format with Polygon labels to YOLOv7 instance segmentation Without Roboflow? (Issue #12560)














 
It seems like there's a mismatch in the dimensions of your arrays during the concatenation process in the mixup function. This often occurs when the data isn't uniformly structured. Ensure all your segments arrays have the same number of dimensions before concatenation. A quick fix could be checking and reshaping arrays if necessary before the np.concatenate call. For example:
 if segments.ndim != segments2.ndim:     # Reshape or handle arrays to match dimensions     # Example reshaping to 3D if they are not:     segments = segments.reshape(-1, segments.shape[0], segments.shape[1])     segments2 = segments2.reshape(-1, segments2.shape[0], segments2.shape[1]) segments = np.concatenate((segments, segments2), 0)
 
This code is just a starting point; adjust as necessary based on your actual data structure. Good luck! 🚀

**Comment by glenn-jocher** [comment]
Great to hear you've found a solution by adjusting the `hyp.scratch-high.yaml` and setting mixup to `0.0`! 🎉 Remember, small tweaks in the hyperparameters can often resolve unexpected issues or improve training performance. If you have further questions or run into more challenges, feel free to ask. Happy training! 🚀
