### ISSUE TITLE
ModuleNotFoundError: No module named 'models.yolo' running in comfyui UltralyticsDetectorProvider

### ISSUE THREAD

**Issue by b8kings0ga** [ultralytics/yolov5#12573]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

ModuleNotFoundError: No module named 'models.yolo' running in comfyui UltralyticsDetectorProvider

Error occurred when executing UltralyticsDetectorProvider:

No module named 'models.yolo'

### Environment

yolov5

### Minimal Reproducible Example

using comfyui running yolov5.pt

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@b8kings0ga hello! It looks like there might be an issue with your Python path or the way your project is structured. Please ensure that your working directory is set correctly and that the `models` directory is present in your project structure. If you're running a script, you might need to adjust your import statements or PYTHONPATH environment variable.

For further guidance, please refer to our documentation and make sure you're following the correct setup procedures. If the issue persists, could you provide more details about your directory structure and how you're running the code? This will help us diagnose the problem more effectively. Thanks for reaching out, and we appreciate your contribution to the YOLOv5 community! 😊
