### ISSUE TITLE
train the picture without the target

### ISSUE THREAD

**Issue by ZhaoMonica** [ultralytics/yolov5#12585]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When yolov5 training, how to train the picture without the target, there is an empty txt can be?

**Comment by glenn-jocher** [comment]
@ZhaoMonica hello! 👋

Yes, you can train YOLOv5 with images that do not contain any targets. For these images, simply provide an empty `.txt` file with the same name as the image file. Make sure there are no spaces or lines in the `.txt` file; it should be completely empty. This will indicate to the model that there are no annotations for that particular image.

For more detailed guidance on training with YOLOv5, you can refer to our documentation at the Ultralytics Docs.

Happy training! 😊

**Comment by ZhaoMonica** [comment]
@glenn-jocher Thank you very much for your reply, it is very helpful to me, thank you!

**Comment by glenn-jocher** [comment]
You're welcome, @ZhaoMonica! I'm glad I could help. If you have any more questions or need further assistance as you work with YOLOv5, don't hesitate to reach out. Good luck with your training! 😄🚀
