### ISSUE TITLE
Using C++ without using any libraries to do Yolov5s-ghost inference

### ISSUE THREAD

**Issue by bilal90000** [ultralytics/yolov5#12580]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi There!

I am a student working on yolov5s-ghost, and I have used this netron. app to see and code the same architecture in C++ language. Now I am getting my  RAW output tensor of the detections like this (txt file attached). I have also trained my model (yolov5s-ghost) with the coco dataset, using google colab codes available on your repository. I am using all the trained kernels and biases, the issue is that how should my output tensor of detections 1x25200x85, looks like? can it contain negative values? also i have set confidence thr of 0.25, and no detections were available, surely there is issue, because when I inferred the same image in python using detect.py, it give person and that was correct. See my tensor in txt file below, and tell me whether it is wrong or right? or I also want to know the step by step instructions, how to decode that detection, so get the same bounding box, values and detection using my c++ code as of python code (detect.py). I need detailed answers, like what will be cnf threshold, IUO, etc, and what are the step sequence, as C++ needs complete details that I don't have. Also, image and python detection is available down.

Thank you 
@glenn-jocher 

![br](https://github.com/ultralytics/yolov5/assets/155555985/4e3c7dc3-adc5-4598-ab36-de3f16fa6afa)
![br](https://github.com/ultralytics/yolov5/assets/155555985/48c14acc-2dc9-430b-bdd4-c3053ec0b088)
[txtx.log](https://github.com/ultralytics/yolov5/files/13820213/txtx.log)

![a](https://github.com/ultralytics/yolov5/assets/155555985/feee9846-5a83-46ce-8a83-026a98f30352)

**Comment by glenn-jocher** [comment]
@bilal90000 hello! Thanks for reaching out with your question. It's great to see you're working on implementing YOLOv5s-ghost in C++.

Regarding your output tensor, it's expected to have values across a range, including negative values, before applying the activation functions like sigmoid to certain parts of the tensor to get the final predictions.

The output tensor shape of 1x25200x85 suggests you're looking at raw predictions for a YOLO model with 25200 anchor boxes and 85 output values per box (for COCO, this would typically be 80 classes + 4 box coordinates + 1 objectness score).

To decode the output tensor into bounding boxes and class predictions, you'll need to follow these steps:

1. **Reshape and Apply Sigmoid**: The raw predictions need to be reshaped according to the grid size and the number of anchor boxes. Then, apply a sigmoid function to the objectness scores, class predictions, and to the tx, ty parts of the bounding box predictions to constrain them between 0 and 1.

2. **Decode Boxes**: Convert the tx, ty, tw, th outputs into the final bounding box coordinates (x, y, width, height). This involves using the anchor box dimensions and applying the exponential function to tw and th.

3. **Apply Confidence Threshold**: Filter out detections with an objectness score below your confidence threshold (e.g., 0.25).

4. **Non-Maximum Suppression (NMS)**: Apply NMS to remove overlapping boxes based on a certain Intersection Over Union (IOU) threshold, typically around 0.45 to 0.6 for YOLO.

5. **Post-Processing**: The remaining boxes after NMS are your final detections. You can then scale these back to the original image dimensions if necessary.

For detailed step-by-step instructions, I recommend reviewing the post-processing part of the detect.py script and the YOLOv5 documentation. The exact implementation details in C++ will depend on how you've set up your code, but the conceptual steps remain the same.

Keep in mind that implementing these steps in C++ without any libraries is a non-trivial task, especially for tasks like NMS, which can be computationally intensive.

Good luck with your project, and remember that the YOLO community and the Ultralytics team are here to support you! 🚀

**Comment by bilal90000** [comment]
@glenn-jocher , Thank you very much for your precious answer, Still i am not clear with 1st and 2nd steps.

1. Reshape and Apply Sigmoid: The raw predictions need to be reshaped according to the grid size and the number of anchor boxes. Then, apply a sigmoid function to the objectness scores, class predictions, and to the tx, ty parts of the bounding box predictions to constrain them between 0 and 1.

2. Decode Boxes: Convert the tx, ty, tw, th outputs into the final bounding box coordinates (x, y, width, height). This involves using the anchor box dimensions and applying the exponential function to tw and th.

My question is that, when i get my output tensor of 1x25200x85, then i need to reshape it, right? and apply sigmoid to it, but if we see the architecture using netron app, we already applied sigmoid function as shown in this figure. Are you taking about this?
![image](https://github.com/ultralytics/yolov5/assets/155555985/1df9b98f-2115-48a3-8dd9-7c6aeee8b6ae)


If not, then my tensor that is 1x25200x85, needs to be reshaped of what arguments? like what is the criteria for official yolov5s-ghost version, i am in need of exactly the same size, so that i can reshape it.


And for the second step that you mentioned. I am in need of more details of it mathmatically, if you can provide it or tell me i will be great full to you.


Before answering my question, please consider this detail.

My Raw tensor 1x25200x85, contains tx,tx,th,tw to be in range greater than 1, like 15,16,250, 240 etc,   

and my objectnees score is very small that i am getting, like 0.00123, 0.00133 etc, like these values, so how can i set objectness threshold of 0.25.

Thanks in anticipation.
Your answer means alot to me.

**Comment by glenn-jocher** [comment]
@bilal90000, I'm glad to help clarify these steps further.

1. **Reshape and Apply Sigmoid**: The output tensor doesn't need to be reshaped if it's already in the format of 1x25200x85. The sigmoid function in the architecture (as seen in Netron) is applied during the forward pass of the network. However, when you get the raw output tensor, you need to apply the sigmoid function to certain elements of this tensor:
   - Apply sigmoid to the first 5 elements of the last dimension (tx, ty, tw, th, and objectness score) to constrain them between 0 and 1.
   - Apply sigmoid to the class predictions (the remaining 80 elements in the case of COCO) to get class probabilities.

2. **Decode Boxes**: The tx, ty, tw, and th values are relative to the grid cell and anchors. Here's a simplified version of the decoding process:
   - **x, y coordinates**: Apply sigmoid to tx and ty, then add the grid cell indices (this gives you the center coordinates relative to the grid cell).
   - **width, height**: Apply the exponential function to tw and th, then multiply by the anchor dimensions (this gives you the width and height relative to the whole image).

For the objectness score, if you're seeing very small values like 0.00123, it suggests that the model is not confident about the presence of objects in those grid cells. You should apply the sigmoid function to these scores, and after that, you can filter out the ones below the confidence threshold (e.g., 0.25). It's possible that the scores are low because the model is not properly trained or there's an issue with how the data is being fed into the model.

Regarding the raw tensor values for tx, ty, tw, and th being greater than 1, this is expected before applying the sigmoid and exponential functions. These transformations will bring the coordinates into a usable range.

For mathematical details, you can refer to the YOLO papers or the detect.py script for the exact formulas used. Unfortunately, I can't provide the detailed mathematical equations here, but the process involves:
- Sigmoid for tx, ty to get center coordinates relative to grid cell.
- Exponential for tw, th to get width and height relative to anchors.
- Multiplication by stride to scale to the original image size.

Remember, the exact implementation will depend on your network's architecture and how you've trained your model. If you're seeing discrepancies, double-check your model's training and inference pipeline to ensure everything is aligned with the official YOLOv5s-ghost version.

Keep experimenting and reviewing the code, and you'll get there! 🛠️

**Comment by bilal90000** [comment]
@glenn-jocher Yes, Thank you very much for your clarification. I applied the sigmoid to my Raw tensor of 1x25200x85, then got my cnf score of the model to increase and it is now between 0 and 1.

However, after applying sigmoid to tx,ty,th,tw, I am getting most of the values to be 1 or 0.99 something, is this fishy? Or its alright to have them?

And the other thing is that, what do you mean by adding the grid cell indices in my tx and ty? Also please tell me for tw,th, that you said, after applying the exponential function, what do you mean by multiplying by the anchor dimensions?

Thats all I need to understand, And I am very thankful to you for your help with this.

Your previous response : (Just need the answer for grid cell indices adding and anchor dimensions multiplication)

"x, y coordinates: Apply sigmoid to tx and ty, then add the grid cell indices (this gives you the center coordinates relative to the grid cell).
width, height: Apply the exponential function to tw and th, then multiply by the anchor dimensions (this gives you the width and height relative to the whole image)."

**Comment by glenn-jocher** [comment]
@bilal90000, I'm glad to hear that applying the sigmoid function has brought your confidence scores into the expected range.

Regarding your concerns:

1. **Values Close to 1 or 0 After Sigmoid**: It's not unusual for the sigmoid function to produce values close to 1 or 0, especially if the raw predictions are far from 0. However, if almost all values are saturating to 1 or 0, this might indicate that the raw predictions are too extreme, which could be a sign of an issue with the model or the input data normalization.

2. **Adding Grid Cell Indices**: The output of a YOLO model is typically structured in a way that each grid cell predicts bounding boxes. The tx and ty values are offsets relative to the top-left corner of their respective grid cells. To get the absolute position of the box centers on the image, you need to add the grid cell's top-left coordinates to tx and ty after applying the sigmoid function. The grid cell indices are essentially the x and y coordinates of the grid cell in the grid space.

3. **Multiplying by Anchor Dimensions**: The tw and th values predict the width and height of the bounding box relative to the size of the anchor box. After applying the exponential function to tw and th, you need to multiply these by the dimensions of the anchor box assigned to that particular grid cell to get the absolute width and height of the predicted bounding box.

Here's a bit more detail on the steps:

- **x, y coordinates**: After applying sigmoid to tx and ty, you get values between 0 and 1. These represent the center of the bounding box relative to the grid cell. To convert these into image coordinates, you add the column index to tx and the row index to ty (assuming a zero-based index where the top-left cell is (0,0)). Then, you multiply by the stride of the grid (the size of each grid cell in pixels).

- **width, height**: After applying the exponential function to tw and th, you multiply these by the width and height of the anchor box that corresponds to the grid cell. This gives you the predicted width and height in pixels.

Remember, the stride and anchor dimensions are specific to the model configuration and must match those used during training. The stride is related to the downsampling factor of the network, and the anchor dimensions are predefined based on the dataset.

Keep iterating and verifying each step of your implementation against the official YOLOv5 code to ensure accuracy. Your persistence will pay off! 🌟

**Comment by bilal90000** [comment]
@glenn-jocher , Thank you very much for your help with this, I really appreciate it.

Just wondering, that if you got the trained weights for yolov5s-ghost?

Can you share them with me so that I can use them for this project, I will be grateful to you.

All other things are cleared. Thanks to you

**Comment by glenn-jocher** [comment]
@bilal90000, I'm glad I could assist you!

Regarding the trained weights for YOLOv5s-ghost, all official weights for YOLOv5 models are typically made available through the Ultralytics YOLOv5 repository. If the specific weights for the YOLOv5s-ghost variant are not directly listed there, they may not have been officially released or might be part of ongoing research and development.

I would recommend checking the official YOLOv5 repository and the associated documentation for any updates on available weights. If the weights are not available, you may need to train the model yourself using the provided training scripts and the COCO dataset or any other dataset of your choice.

Thank you for your understanding, and best of luck with your project! If you have any more questions or need further assistance, feel free to reach out. Keep up the great work! 👍
