### ISSUE TITLE
train on custom dataset that more different from coco dataset

### ISSUE THREAD

**Issue by SJavad** [ultralytics/yolov5#12581]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi 🖐
I want to train the Yolov5s Model on a very different dataset from the coco dataset.
how can I unfreeze more layers of Yolo layers for fine-tuning? 
Thank you for guiding me on exactly how to set these parameters in the command. 🌸😁
I appreciate your help ✌

**Comment by glenn-jocher** [comment]
@SJavad hi there! 👋

Great to hear you're working on training YOLOv5 on a custom dataset! If your dataset is significantly different from COCO, fine-tuning more layers can indeed be beneficial.

To unfreeze layers for fine-tuning, you can adjust the `--freeze` parameter in the training command. By default, YOLOv5 will freeze a certain number of layers during the initial stages of training. If you want to train all layers from the beginning, you can set `--freeze 0`, which will leave all layers unfrozen.

Here's an example command to start training without freezing any layers:

```shell
python train.py --img 640 --batch 16 --epochs 100 --data your_dataset.yaml --weights yolov5s.pt --freeze 0
```

Remember to replace `your_dataset.yaml` with the path to your dataset configuration file and adjust the `--img`, `--batch`, and `--epochs` parameters as needed for your specific use case.

For more detailed guidance on training parameters and best practices, please refer to our documentation at the Ultralytics Docs.

Happy training, and if you have any more questions, feel free to ask! 😊✌

**Comment by SJavad** [comment]
thank you so much @glenn-jocher for your help 🌸✌

**Comment by glenn-jocher** [comment]
@SJavad you're welcome! 😊 If you have any more questions or need further assistance as you progress, don't hesitate to reach out. Good luck with your training, and have fun with your project! 🚀✌
