### ISSUE TITLE
ConfusionMatrix incorrect?

### ISSUE THREAD

**Issue by GilSeamas** [ultralytics/yolov5#12586]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Validation

### Bug

I believe there is a problem in the ConfusionMatrix() method. It only counts the false positives if there are true positives.

n = matches.shape[0] > 0
m0, m1, _ = matches.transpose().astype(int)
for i, gc in enumerate(gt_classes):
    j = m0 == i
    if n and sum(j) == 1:
        self.matrix[detection_classes[m1[j]], gc] += 1  # correct
    else:
        self.matrix[self.nc, gc] += 1  # true background

if n:
    for i, dc in enumerate(detection_classes):
        if not any(m1 == i):
            self.matrix[dc, self.nc] += 1  # predicted background 
            
I believe it should be:

n = matches.shape[0] > 0
m0, m1, _ = matches.transpose().astype(int)
for i, gc in enumerate(gt_classes):
    j = m0 == i
    if n and sum(j) == 1:
        self.matrix[detection_classes[m1[j]], gc] += 1  # correct
    else:
        self.matrix[self.nc, gc] += 1  # true background

#NO IF STATEMENT HERE
for i, dc in enumerate(detection_classes):
    if not any(m1 == i):
        self.matrix[dc, self.nc] += 1  # predicted background

### Minimal Reproducible Example

n = matches.shape[0] > 0
m0, m1, _ = matches.transpose().astype(int)
for i, gc in enumerate(gt_classes):
    j = m0 == i
    if n and sum(j) == 1:
        self.matrix[detection_classes[m1[j]], gc] += 1  # correct
    else:
        self.matrix[self.nc, gc] += 1  # true background

if n:
    for i, dc in enumerate(detection_classes):
        if not any(m1 == i):
            self.matrix[dc, self.nc] += 1  # predicted background

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@GilSeamas hello! Thank you for bringing this to our attention and for your willingness to help by submitting a PR. It's great to see community members actively participating in improving YOLOv5.

From your description, it seems you've identified a potential issue with the way false positives are counted in the `ConfusionMatrix()` method. Your observation about the conditional structure that might prevent counting false positives when there are no true positives is insightful.

Before proceeding with a PR, it would be beneficial to verify this behavior with a controlled test case to ensure that the proposed change resolves the issue without introducing any new ones. If you could create a minimal reproducible example that demonstrates the problem and confirms that your suggested fix works, that would be fantastic.

Once you have this, please go ahead and submit a PR with the changes and the test case. We'll review it as soon as possible. Your contribution is much appreciated! 🚀

If you need guidance on creating a PR or on how to write the test case, please refer to our documentation at https://docs.ultralytics.com/yolov5/.

Thanks again for your support and for being an active member of the YOLOv5 community! 😊
