### ISSUE TITLE
Which model is used for --evolve ?

### ISSUE THREAD

**Issue by CylonN8** [ultralytics/yolov5#12590]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,

When using"--evolve", which model weights are used for evaluation? Where can I find the specific line of code to modify it for a custom implementation, for exemple using last.pt instead of best.pt?

Thank you

**Comment by glenn-jocher** [comment]
@simvarail hello!

When you use the `--evolve` flag, the evolution process starts with the pretrained weights specified by the `--weights` argument. If no weights are specified, it defaults to the pretrained `yolov5s.pt` model. The evolution process then iteratively updates the hyperparameters to find a set that may improve model performance.

For custom implementations or to change the starting weights, you can modify the `--weights` argument when you run the `--evolve` command. If you want to dive into the code, the relevant section for the evolution process is in the `train.py` script. Look for the function that handles the evolution logic.

For more detailed guidance on hyperparameter evolution, please refer to our documentation at https://docs.ultralytics.com/yolov5/.

Happy evolving! 🚀
