### ISSUE TITLE
How to implement the add function

### ISSUE THREAD

**Issue by Yee0717** [ultralytics/yolov5#12606]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I wrote the following code in the commn.py file, and then added these lines in mine.yaml, but my program gave an error. I finally located it in the yolo.py file, but I don't know how to modify it. Could you help me? Thanks a lot, and please forgive my poor coding skills.
commn.py:
`class Add(nn.Module):  def_init__(self,c1,c2):    super().__init__()     self.cv1 = Conv(c1,c2，1,1)  def  forward(self，x1，x2):  return self.cv1(x1 + x2)`

mine.yaml:
`[[-1，1，conv，[64，3，2，1]],#0
[-1，1，conv，[64，3，2，1]],# 1
[-1，4，layer1，[256]], # 2
[-1，1，conv，[256，3，1]], # 3
[2，1,conv，[512，3，2]], # 4
[-1，4，BasicBlock，[512]], #5
[3，4，BasicBLockHR，[256]]，#6
[5，1，UPHR，[256,2]],  #7  upsample+conv
[6，1，conv，[512，3，2，1]],#8
[[6,7],1,Add,[256]#9
]`
the problem is in  `  [[6,7],1,Add,[256]#9`

error is : TypeError: list indices must be integers or slices, not list

**Comment by glenn-jocher** [comment]
@Yee0717 hello! It looks like you're trying to implement a custom addition module in your YOLOv5 model. The error you're encountering is due to the way you're specifying the input layers for your `Add` module in your `mine.yaml` file.

In your `mine.yaml`, you're trying to pass a list of layers `[[6,7],1,Add,[256]]` to the `Add` module, which is not the correct format. The YOLOv5 model configuration expects each layer to be defined with a single index or a tuple for concatenation.

To fix this, you'll need to modify the `forward` method of your `Add` class to accept two separate inputs and then modify your YAML file to pass the indices of the layers you want to add correctly.

Here's a quick guide on how you might adjust your `Add` class:

```python
class Add(nn.Module):
    def __init__(self, c1, c2):
        super().__init__()
        self.cv1 = Conv(c1, c2, 1, 1)

    def forward(self, x1, x2):
        return self.cv1(x1 + x2)
```

And then in your `mine.yaml`, you would reference the layers to be added like this:

```yaml
# ... previous layers ...
[6, 7, Add, [256]]  # This will pass the outputs of layers 6 and 7 to the Add module
```

Please note that you'll also need to ensure that the `forward` function in your model's code can handle this custom layer and pass the correct inputs to it.

For more detailed guidance on customizing models and layers, please refer to the Ultralytics Docs. If you continue to have issues, feel free to ask for help in the discussions section of the repo. Good luck with your coding! 😊👍

**Comment by Yee0717** [comment]
> @Yee0717 hello! It looks like you're trying to implement a custom addition module in your YOLOv5 model. The error you're encountering is due to the way you're specifying the input layers for your `Add` module in your `mine.yaml` file.
> 
> In your `mine.yaml`, you're trying to pass a list of layers `[[6,7],1,Add,[256]]` to the `Add` module, which is not the correct format. The YOLOv5 model configuration expects each layer to be defined with a single index or a tuple for concatenation.
> 
> To fix this, you'll need to modify the `forward` method of your `Add` class to accept two separate inputs and then modify your YAML file to pass the indices of the layers you want to add correctly.
> 
> Here's a quick guide on how you might adjust your `Add` class:
> 
> ```python
> class Add(nn.Module):
>     def __init__(self, c1, c2):
>         super().__init__()
>         self.cv1 = Conv(c1, c2, 1, 1)
> 
>     def forward(self, x1, x2):
>         return self.cv1(x1 + x2)
> ```
> 
> And then in your `mine.yaml`, you would reference the layers to be added like this:
> 
> ```yaml
> # ... previous layers ...
> [6, 7, Add, [256]]  # This will pass the outputs of layers 6 and 7 to the Add module
> ```
> 
> Please note that you'll also need to ensure that the `forward` function in your model's code can handle this custom layer and pass the correct inputs to it.
> 
> For more detailed guidance on customizing models and layers, please refer to the Ultralytics Docs. If you continue to have issues, feel free to ask for help in the discussions section of the repo. Good luck with your coding! 😊👍

How to implement forward

**Comment by glenn-jocher** [comment]
@Yee0717 apologies for the confusion earlier. To implement the `forward` method for your custom `Add` class, you need to ensure that it can accept two separate inputs and then perform the addition operation followed by the convolution. Here's a concise example of how you might implement the `forward` method:

```python
class Add(nn.Module):
    def __init__(self, c1, c2):
        super().__init__()
        self.cv1 = Conv(c1, c2, 1, 1)

    def forward(self, x1, x2):
        return self.cv1(x1 + x2)
```

In your model's code, you'll need to ensure that the two inputs `x1` and `x2` are the outputs from the layers you want to add together. This means that when you define the `forward` function of your model, you should have something like this:

```python
def forward(self, x):
    # ... code for previous layers ...
    layer6_output = previous_layer6_output
    layer7_output = previous_layer7_output

    # Now pass the outputs from layers 6 and 7 to your Add module
    x = self.add_module(layer6_output, layer7_output)
    # ... code for subsequent layers ...
```

Make sure that `self.add_module` is an instance of your `Add` class and that it's properly defined in your model's `__init__` method.

Remember, the actual implementation will depend on the structure of your model and how you've integrated the `Add` module within it. If you need further assistance, please provide more context or consider asking in the discussions section of the repo. Good luck! 😊👍

**Comment by Yee0717** [comment]
@glenn-jocher Thanks! I succeeded, thanks to your selfless and careful help.

**Comment by glenn-jocher** [comment]
@Yee0717 You're welcome! I'm delighted to hear that you've succeeded. Remember, the YOLOv5 community and the Ultralytics team are always here to help. If you have any more questions in the future, don't hesitate to reach out. Happy coding and best of luck with your projects! 😊🚀
