### ISSUE TITLE
Tensorboard validation image visualization

### ISSUE THREAD

**Issue by JaviMota** [ultralytics/yolov5#12600]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi

I would like to follow the progress of the yolov5 training using tensorboard. Actually Im able to see different evaluation metrics evolving but I also would like to see some predicted images with their bboxes and labels in tensorboard. Is it possible to do it with the current code or do I need to add some extra one?

Also I would like to understand how augmentations works in the current pipeline. Are they applied and fixed at the beginning of the training or are the images modified during the training? My idea is to change the original image in each epoch to apply random level of noise for example.

Thank you.
Javi

**Comment by glenn-jocher** [comment]
@JaviMota hi Javi,

Great to hear you're using TensorBoard with YOLOv5! 🎉

To visualize validation images with their predicted bounding boxes and labels in TensorBoard, you don't need to add extra code. This feature is already integrated. After each validation run during training, a selection of images with predictions are logged to TensorBoard. Make sure you're using the latest version of YOLOv5 and check the TensorBoard 'Images' tab to see them.

Regarding augmentations, they are applied dynamically during training, not fixed at the beginning. Each image is randomly transformed on-the-fly as it's loaded for each epoch, which helps to improve generalization. If you want to add custom noise or other augmentations, you can modify the augmentation pipeline in the dataset loading code.

For more detailed guidance on augmentations and other features, please refer to our documentation at https://docs.ultralytics.com/yolov5/.

Happy training, and thanks for being part of the YOLO community! 😊

**Comment by JaviMota** [comment]
Hi

Thank you for the reply!

I was looking in the code where it is saved the predicted validation images during the training and I see the "add_image" function belonging to the SummaryWriter class pytorch has to work with tensorboard, it is inside the "on_train_end" function. From my understanding, this function is executed when the training ends and not at each final epoch step. Do I need maybe to use "add_image" inside "on_val_batch_end" function?

Thanks!

**Comment by glenn-jocher** [comment]
Hi again @JaviMota,

Apologies for any confusion. The `add_image` function should indeed be called after each validation epoch, not just at the end of training.

In the YOLOv5 codebase, images with predictions are logged during the validation phase of each epoch. This is handled within the `process_batch` function, which processes the outputs and logs them using `wandb.log` or `writer.add_image` if TensorBoard is enabled. This should occur in the `val.py` script.

If you're not seeing the images, ensure that TensorBoard logging is enabled with the `--tensorboard` flag when you start training. If you're still having issues, it might be a version-related problem, so make sure you're using the latest version of YOLOv5.

If you have further questions or need assistance, feel free to ask. Happy to help! 😄
