### ISSUE TITLE
Precision and Recall value

### ISSUE THREAD

**Issue by kim2429** [ultralytics/yolov5#12616]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I have a question about the training result. 
The value of precision and recall of one class was 1.0 and 0.0, respectively.
Is this result possible?

**Comment by glenn-jocher** [comment]
@kim2429 hello! Yes, it's possible to have a precision of 1.0 and recall of 0.0 for a class. This typically means that all the predictions for that class were correct (hence the perfect precision), but the model failed to identify most or all actual instances of that class (hence the zero recall). It suggests that while the model is highly confident when it does make a prediction for that class, it's very conservative and misses many or all true positives. You might want to look into your dataset balance, potential overfitting, or adjust the confidence threshold to improve recall. For more detailed guidance, please refer to our documentation. 😊

**Comment by kim2429** [comment]
Thank you very much!

**Comment by glenn-jocher** [comment]
@kim2429 you're welcome! If you have any more questions or need further assistance, feel free to ask. Happy training! 😄🚀
