### ISSUE TITLE
wondering about the size of model！

### ISSUE THREAD

**Issue by linkenceall** [ultralytics/yolov5#1261]
## Additional context
Hello Team,

the config of my model is yolo5m.yaml, the dataset is coco2017 but contain only person informatoin.
i train the model to detect person, the model works well in phase of dectection. 
the size of model is about 147M,the desier size is smaller than 50M,how to improve it?
can you explain why the size of model is larger than 44M which i download from https://github.com/ultralytics/yolov5/releases. 
Thanks for your supports

Regards,

**Comment by siyangxie** [comment]
As far as I know, the size of the model should be almost same as the one you transfer learned from. So if you're using yolov5m which is about 42MB, you should have the similar size after training.

**Comment by glenn-jocher** [comment]
Model sizes are as follows:
<img width="1127" alt="YOLOv5_models" src="https://user-images.githubusercontent.com/26833433/97850029-c274d780-1cf3-11eb-98bb-cb9c1b9f6503.png">

**Comment by linkenceall** [comment]
After converting the model precision from 32f to 16f , i get the properly size!
