### ISSUE TITLE
Small object detection problems

### ISSUE THREAD

**Issue by mesguerraf** [ultralytics/yolov5#1262]
## ❔Question
Hello, I'm trying to train the model to detect small objects (they are around 32p in the original images) on a custom dataset. I followed the tutorial but I always get 0 precision and recall during training and the final predictions are random. I am guessing that the problem lies in the fact that I'm trying to detect objects this small and I was wondering if there is something I could do to improve the performance or maybe check something in particular in the dataset I have.

## Additional context
I have already trained another model using a F-RCNN architecture with resnet backbone and the AP and AR scores are both over 0.45 but the inference time is slow so I wanted to use a one shot detector.

**Comment by glenn-jocher** [comment]
@mesguerraf see https://docs.ultralytics.com/yolov5/tutorials/train_custom_data

**Comment by iliesaya** [comment]
Same issue here, following ...

**Comment by glenn-jocher** [comment]
@mesguerraf @iliesaya for better introspection for community responses, I would suggest you train with W&B logging enabled, and then provide public links to the training runs you are referring to. Otherwise, absent any information it's unlikely you'll receive any relevant feedback. You can get started with `pip install wandb` and then train normally.

**Comment by glenn-jocher** [comment]
For an example W&B logging on the COCO128 tutorial see https://wandb.ai/glenn-jocher/YOLOv5

**Comment by mesguerraf** [comment]
Thanks for your answer! I think i solved my issue by reducing the initial image input image size and eliminating all the images where no object is present. If I have an issue in the future i'll make sure to use W&B logging !

**Comment by glenn-jocher** [comment]
@mesguerraf ok great! Just FYI in general, 32 pixel objects are considered large objects based on the 3 YOLO output grids, not small objects, and you should have no problem detecting them.

**Comment by AlexJunCpp** [comment]
> Thanks for your answer! I think i solved my issue by reducing the initial image input image size and eliminating all the images where no object is present. If I have an issue in the future i'll make sure to use W&B logging !

do you konw why  increasing the image-size input, we got 0 precision and recall sometimes during the training process?
