### ISSUE TITLE
synchronized frames of video with boxes from csv file

### ISSUE THREAD

**Issue by gchinta1** [ultralytics/yolov5#12623]
hi guys,
i am trying to synchronize the positions of boxes in the video.. the boxes start right but the are playing faster than video..when i change the fps they both go faster or slower ..can you help me synchronize them together? This is my code .. when i change the frame_number they are slower than video.. ineed a loop or where i can put it to right.

`import cv2
import csv
import time

def read_yolov5_results_from_csv(csv_file):
    yolov5_results = {}
    with open(csv_file, newline='') as csvfile:
        reader = csv.reader(csvfile, delimiter=',')
        next(reader, None)  
        
        for row in reader:
            frame_number = int(row[0]) - 1  
            label = row[1]
            x, y, width, height = map(float, row[2:6])
            yolov5_results.setdefault(frame_number, []).append((label, x, y, width, height))

    return yolov5_results

def visualize_detected_objects(video_path, yolov5_results):
    video = cv2.VideoCapture(video_path)
    fps = video.get(cv2.CAP_PROP_FPS)  
    frame_duration = 0.5 / fps 
    frame_number = 0
    while True:
      
      ret, frame = video.read()
      if not ret:
        break  
   
      frame_start_time = time.time()

      detections_for_frame = yolov5_results.get(frame_number, [])
      frame_number += 2 ##i change this and then they goes after video play
  
      for detection in detections_for_frame:
            label, x, y, width, height = detection
        
            image_width = int(video.get(cv2.CAP_PROP_FRAME_WIDTH))
            image_height = int(video.get(cv2.CAP_PROP_FRAME_HEIGHT))
            x_pixel = int(x * image_width)
            y_pixel = int(y * image_height)
            width_pixel = int(width * image_width)
            height_pixel = int(height * image_height)

            x1, y1 = int(x_pixel - width_pixel / 2), int(y_pixel - height_pixel / 2)
            x2, y2 = int(x_pixel + width_pixel / 2), int(y_pixel + height_pixel / 2)

        
            cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 2)
            cv2.putText(frame, label, (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 2)

 
      
      cv2.imshow('YOLOv5 Object Detection', frame)
   
        
      processing_time = time.time() - frame_start_time

        
      if processing_time < frame_duration:
            time.sleep(frame_duration - processing_time)

  
      if cv2.waitKey(1) & 0xFF == ord('q'):
         break

    

    video.release()
    cv2.destroyAllWindows()

csv_file_path = 'Combined_Products.csv'
video_file_path = 'output.mp4'

yolov5_results = read_yolov5_results_from_csv(csv_file_path)
visualize_detected_objects(video_file_path, yolov5_results)`

Thank you guys
![Uploading Screenshot (23).png…]()

**Comment by glenn-jocher** [comment]
@gchinta1 hello!

It looks like the issue you're facing is due to the mismatch between the frame rate of the video and the rate at which you're processing and displaying the bounding boxes. In your code, you're incrementing `frame_number` by 2 every loop iteration, which effectively skips frames and causes the boxes to move faster than the video.

To synchronize the boxes with the video, you should increment `frame_number` by 1 for each frame of the video. Here's the part of your code that needs to be adjusted:

```python
while True:
    # ...
    frame_number += 1  # Increment by 1 instead of 2
    # ...
```

Additionally, ensure that `frame_duration` is set correctly. It should be the inverse of the frames per second (fps):

```python
frame_duration = 1 / fps  # Correct frame duration calculation
```

With these changes, your bounding boxes should stay in sync with the video frames. If you still experience synchronization issues, it might be due to the processing time of each frame. Make sure that the processing time does not exceed the `frame_duration`.

For more detailed guidance, please refer to our documentation at https://docs.ultralytics.com/yolov5/.

**Comment by gchinta1** [comment]
> @gchinta1 hello!
> 
> It looks like the issue you're facing is due to the mismatch between the frame rate of the video and the rate at which you're processing and displaying the bounding boxes. In your code, you're incrementing `frame_number` by 2 every loop iteration, which effectively skips frames and causes the boxes to move faster than the video.
> 
> To synchronize the boxes with the video, you should increment `frame_number` by 1 for each frame of the video. Here's the part of your code that needs to be adjusted:
> 
> ```python
> while True:
>     # ...
>     frame_number += 1  # Increment by 1 instead of 2
>     # ...
> ```
> 
> Additionally, ensure that `frame_duration` is set correctly. It should be the inverse of the frames per second (fps):
> 
> ```python
> frame_duration = 1 / fps  # Correct frame duration calculation
> ```
> 
> With these changes, your bounding boxes should stay in sync with the video frames. If you still experience synchronization issues, it might be due to the processing time of each frame. Make sure that the processing time does not exceed the `frame_duration`.
> 
> For more detailed guidance, please refer to our documentation at https://docs.ultralytics.com/yolov5/.

@glenn-jocher thank you for helping me in all this

When i change the frame number+=1 then the boxes are moving after video .. it starts good and the boxes lose frames and video plays faster they don't follow

Thank you

**Comment by glenn-jocher** [comment]
Hello @gchinta1,

If the bounding boxes are lagging behind the video when you increment `frame_number` by 1, it suggests that the processing time for each frame might be exceeding the time allocated per frame (`frame_duration`). This can happen if the drawing and text operations are taking too long.

To address this, you can try the following:

1. Optimize the drawing and text operations if possible.
2. Pre-calculate the image width and height outside of the loop to avoid redundant calls to `video.get()`.
3. Consider processing the video frames and drawing the boxes in a lower resolution to speed up the operations if the resolution is not critical for your application.

Here's a snippet of your code with the image width and height pre-calculated:

```python
image_width = int(video.get(cv2.CAP_PROP_FRAME_WIDTH))
image_height = int(video.get(cv2.CAP_PROP_FRAME_HEIGHT))

while True:
    # ...
    for detection in detections_for_frame:
        # Use pre-calculated image_width and image_height
        # ...
```

Make sure to measure the processing time accurately and compare it with `frame_duration`. If the processing time is indeed longer, you'll need to find ways to reduce it to maintain synchronization.

If the issue persists, you may need to look into more advanced techniques such as threading to separate the video reading and processing into different threads to ensure that the display of the video is not hindered by the processing of the bounding boxes.

Keep in mind that real-time video processing can be quite demanding, and the hardware running the code could also be a limiting factor.
