### ISSUE TITLE
Negative-width bounding boxes when running on M1 (mps) HW

### ISSUE THREAD

**Issue by agentmorris** [ultralytics/yolov5#12654]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Validation

### Bug

(At Glenn's suggestion, transferring from [issue 12645](https://github.com/ultralytics/yolov5/issues/12645), which I originally filed as a question.)

I am running a trained YOLOv5x6 model using val.py with the --save_json option. I have a few images where the resulting .json file includes one or more boxes with negative width values (not negative x or y values, which seem normal and are discussed in other issues, but negative width values), but I have only observed this behavior when running on M1 hardware (with --device mps).  This issue occurs in the current YOLOv5 Python environment on M1 HW, but does not occur with at least one older YOLOv5 environment on M1 HW, and AFAIK does not occur with any YOLOv5 environment on CUDA/x86 HW.

### Hardware/OS environment

- An AWS M1 (mac2.metal) VM running OSX

### Python environment

- pip's list of packages in the "new YOLOv5" environment (in which I am able to reproduce this issue) is [here](http://dmorris.net/misc/tmp/m1-yolo-issue/yolov5-new-negative-width-pip.txt).  This directly follows "pip install -r requirements.txt"; I made no other changes to this environment.  This is a Python 3.11 environment.
- pip's list of packages in the "old YOLOv5" environment is [here](http://dmorris.net/misc/tmp/m1-yolo-issue/yolov5-old-working-pip.txt).  This is not strictly a pip install of the requirements.txt file from the (old) YOLOv5 repo, but in this case, I don't think it matters for purposes of reproducing the issue, since this is the environment that *doesn't* exhibit the behavior in question.  This is a Python 3.8 environment.

Both environments were created via Miniforge.

### Minimal Reproducible Example

I am able to share images that reproduce this behavior now, and I also have some new data that might get us closer to a root cause:

- In a Python environment based on the _current_ YOLOv5 repo, I am able to reproduce this negative-box behavior on an M1 Mac (specifically a mac2.metal M1 AWS VM).
- In a Python environment with older versions of most dependencies, with an old version of the YOLOv5 repo (based on [this commit](https://github.com/ultralytics/yolov5/commit/c23a441c9df7ca9b1f275e8c8719c949269160d1/)), on the same M1 machine, I am *not* able to reproduce this negative-box behavior.
- Either Python/YOLOv5 environment works fine (i.e., does not produce negative-width boxes) on a Linux+CUDA or Linux+CPU environment.
- The Linux+CUDA results in either environment are nearly identical to the "old YOLOv5" M1 results, with just acceptable differences out at the fourth or fifth decimal place.

The command I am running on the M1 VM is:

`python val.py --task test --data "/Users/ec2-user/images/dataset.yaml" --weights "/Users/ec2-user/md_v5a.0.0.pt" --batch-size 1 --imgsz 1280 --conf-thres 0.001 --device "mps" --save-json --project "/Users/ec2-user/yolo-results/yolo-new-no-aug" --name "yolo_results" --exist-ok --save-txt --save-conf
`

- Images are [here](http://dmorris.net/misc/tmp/m1-yolo-issue/m1-test-images.zip) (images.zip, three small images)
- Model weights are [here](https://github.com/agentmorris/MegaDetector/releases/download/v5.0/md_v5a.0.0.pt) (md_v5a.0.0.pt, a trained YOLOv5 model)
- A suitable dataset.yaml file is [here](http://dmorris.net/misc/tmp/m1-yolo-issue/dataset.yaml) (the absolute path on the first line will need adjusting)
- The COCO-formatted results from the "new YOLOv5" environment are [here](http://dmorris.net/misc/tmp/m1-yolo-issue/yolo-new-md_v5a.0.0_predictions.json) (with negative-width boxes)
- The COCO-formatted results from the "old YOLOv5 "environment are [here](http://dmorris.net/misc/tmp/m1-yolo-issue/yolo-old-md_v5a.0.0_predictions.json) (no negative boxes, nearly identical to the results from a CUDA environment)
- pip's list of packages in the "new YOLOv5" environment is [here](http://dmorris.net/misc/tmp/m1-yolo-issue/yolov5-new-negative-width-pip.txt).  This directly follows "pip -r requirements.txt"; I made no other changes to this environment.  This is a Python 3.11 environment.
- pip's list of packages in the "old YOLOv5" environment is [here](http://dmorris.net/misc/tmp/m1-yolo-issue/yolov5-old-working-pip.txt).  This is not strictly a pip install of the requirements.txt file from the (old) YOLOv5 repo, but in this case, I don't think it matters for purposes of reproducing the issue, since this is the environment that *doesn't* exhibit the behavior in question.  This is a Python 3.8 environment.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@agentmorris hello! Thank you for the detailed report and for following up on the previous issue. It's quite intriguing that you're observing negative-width bounding boxes exclusively on M1 hardware with MPS. This could be related to differences in the MPS backend or a specific library version incompatibility.

To help us diagnose and address this issue, could you please:

1. Confirm that you're using the latest commit from the YOLOv5 repository.
2. Test with different versions of PyTorch, especially the one used in your "old YOLOv5" environment where the issue does not occur.
3. If possible, isolate the issue by running inference on a single image that produces a negative-width bounding box and share the verbose output.

Your cooperation is much appreciated! We'll look into this as soon as we have more information. Meanwhile, for further guidance, please refer to our documentation at https://docs.ultralytics.com/yolov5/.

Thank you for your contribution to improving YOLOv5! 🚀

**Comment by agentmorris** [comment]
I have a more self-contained repro now, from a brand new AWS mac2.metal VM...

```bash
# Install miniforge
brew install wget
wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-MacOSX-arm64.sh --no-check-certificate
chmod a+x Miniforge3-MacOSX-arm64.sh
./Miniforge3-MacOSX-arm64.sh
source ~/.zshrc

# Get the model weights, dataset file, and test image
mkdir ~/images
wget https://github.com/agentmorris/MegaDetector/releases/download/v5.0/md_v5a.0.0.pt -O ~/images/md_v5a.0.0.pt --no-check-certificate
wget http://dmorris.net/misc/tmp/m1-yolo-issue/n7_2019-03-19_07-25-00.JPG -O ~/images/n7_2019-03-19_07-25-00.JPG
wget http://dmorris.net/misc/tmp/m1-yolo-issue/dataset.yaml -O ~/images/dataset.yaml

# Check out both YOLOv5 versions ("new" and "old") to separate folders
git clone https://github.com/ultralytics/yolov5 yolov5-new

git clone https://github.com/ultralytics/yolov5 yolov5-old
cd yolov5-old
git checkout c23a441c9df7ca9b1f275e8c8719c949269160d1

# Create Python environments
mamba create -n yolov5-new python=3.11 pip -y
cd ~/yolov5-new && mamba activate yolov5-new
pip install -r requirements.txt

mamba create -n yolov5-old python=3.8 pip -y
cd ~/yolov5-old && mamba activate yolov5-old
pip install -r requirements.txt

# The old YOLOv5 requirements.txt file specified numpy>=1.18.5, which mamba 
# satisfies with 1.24.4 as of 2024.01.21.  This results in "AttributeError: module 'numpy' 
# has no attribute 'int'. ".  So we roll back numpy to 1.21.4, which is still compatible with 
# the requirements.txt file.
pip uninstall -y numpy && pip install numpy==1.21.4

# Test
cd ~/yolov5-new && mamba activate yolov5-new
python val.py --task test --data "/Users/ec2-user/images/dataset.yaml" --weights "/Users/ec2-user/images/md_v5a.0.0.pt" --batch-size 1 --imgsz 1280 --conf-thres 0.001 --device "mps" --save-json --project "/Users/ec2-user/yolo-results/yolo-new" --name "yolo_results" --exist-ok --save-txt --save-conf

cat ~/yolo-results/yolo-new/yolo_results/md_v5a.0.0_predictions.json

# [{"image_id": "n7_2019-03-19_07-25-00", "category_id": 0, "bbox": [1252.152, 994.286, -745.002, 257.866], "score": 0.96902}]

cd ~/yolov5-old && mamba activate yolov5-old
python val.py --task test --data "/Users/ec2-user/images/dataset.yaml" --weights "/Users/ec2-user/images/md_v5a.0.0.pt" --batch-size 1 --imgsz 1280 --conf-thres 0.001 --device "mps" --save-json --project "/Users/ec2-user/yolo-results/yolo-old" --name "yolo_results" --exist-ok --save-txt --save-conf

cat ~/yolo-results/yolo-old/yolo_results/md_v5a.0.0_predictions.json

# [{"image_id": "n7_2019-03-19_07-25-00", "category_id": 0, "bbox": [135.414, 994.286, 371.736, 257.866], "score": 0.96902}]
```

**Comment by glenn-jocher** [comment]
@agentmorris, fantastic work on creating a self-contained reproducible example! This will greatly assist in debugging the issue. The negative-width bounding box in the new environment versus the correct output in the old environment suggests a regression or incompatibility introduced in the newer software stack.

Given the detailed steps you've provided, we will:

1. Replicate your environment and run the provided commands.
2. Investigate any changes between the old and new versions of YOLOv5, as well as differences in dependency versions, particularly those related to MPS support.
3. Look into the MPS backend processing to identify any potential source of the negative-width bounding box issue.

Your thorough testing and reporting are invaluable to the YOLOv5 community and the Ultralytics team. We'll update you as soon as we have more insights or require further information.

Thank you for your dedication to improving YOLOv5! 🌟

**Comment by agentmorris** [comment]
Hopefully the GHA bot isn't going to automatically close this issue?  This seems like a fairly severe issue; the negative boxes are just the manifestation that's easy to detect, the underlying issue is better described as "large discrepancies between M1 results and other results".

If I can ignore the GHA bot, you can ignore this comment. :)

**Comment by glenn-jocher** [comment]
@agentmorris, rest assured, we'll ensure this issue remains open and actively investigated given its significance. The discrepancies you've highlighted, especially with the MPS backend on M1 hardware, are indeed critical to address for ensuring consistent and reliable model performance across different platforms.

Your findings and the effort you've put into documenting this issue are greatly appreciated. We'll prioritize looking into this and keep you updated on our progress. Please feel free to add any further observations or data you may gather as we work towards a resolution.

Thank you for your patience and for contributing to the robustness of YOLOv5! 🛠️

**Comment by agentmorris** [comment]
@glenn-jocher Were you able to assess the scope of this issue before closing?  The negative-width bounding boxes were just the symptom that let us find this issue; the fact that results are incorrect on M1 HW at all seems like a possibly-big deal, unless there's something specific about this repro that limits the scope.  Any ideas?

**Comment by glenn-jocher** [comment]
@agentmorris, absolutely, your concern is valid and recognized. I've reviewed the scope, and indeed, the issue extends beyond just negative-width bounding boxes—highlighting discrepancies in results on M1 hardware is critical. We're diving deeper to understand the root cause and its implications. Once we have more clarity on the specific conditions or factors contributing to this issue, we'll update. Your insight has been invaluable in unveiling this; rest assured, we're on it! 🚀

**Comment by agentmorris** [comment]
Thanks.  The github-actions bot tricked me again. :)

**Comment by glenn-jocher** [comment]
@agentmorris, haha, those bots can be quite sneaky! 😄 If there's anything more you need help with or any more insights you gather, feel free to share. We're all ears and here to support. Happy coding!

**Comment by guybashan** [comment]
Hi,
Am I missing anything? Was this issue ever solved?

**Comment by pderrenger** [comment]
Hi, please ensure you're using the latest version of YOLOv5. If the issue persists, let us know with any additional details.

**Comment by agentmorris** [comment]
@pderrenger I am still able to replicate this issue on an M1 Mac using exactly the same instructions described above, which downloads the most recent commit of YOLOv5 and installs the most recent version of all the dependent packages (including ultralytics and torch).  This is from a completely clean M1 instance on AWS, as per above.  As was the case when I originally filed this issue, the current version of YOLOv5 gives errant results, but the old commit of YOLOv5 works fine.

FWIW on the one local Mac M3 to which I have access, I do *not* see this issue.  There are a million other differences between the local Mac M3 and the replicable AWS M1, so I don't have any reason to think this is as simple as "this problem exists on M1 HW but not M3 HW".  That data point only demonstrates that it's not the case that this issue exists on every possible Apple silicon environment.  But conveniently, it exists on the AWS environment that is easily replicable.

**Comment by guybashan** [comment]
> Hi, please ensure you're using the latest version of YOLOv5. If the issue persists, let us know with any additional details.

Hi,

- Indeed I am using the latest code from git (main branch).
- I re-run the training using this:
`/cam-analyzer/pytorch_metal_env/bin/python ../yolov5/train.py --img 416 --batch 16 --epochs 100 --data ../yolo_cfg/data.yaml --weights yolov5m.pt --device mps`
- I re-checked my "train" and "val" folders. They look ok and the files look fine. I created the labels using YoloLabel app (open source).
- I run the detection using this command: 
`/cam-analyzer/pytorch_metal_env/bin/python detect.py --save-txt --save-conf --weights /Users/user/Documents/dev/yolo_model/cam_analyzer/weights/best.pt --source /Users/user/Documents/dev/yolo_images --conf 0.1 --project /Users/columbo/Documents/dev/yolo_results --name detections --device mps`
- I use M1 Max with 64GB memory
- I enabled working with GPU

**Comment by pderrenger** [comment]
Thank you for the details. Since you're using the latest version and still experiencing issues, it might be related to the MPS backend. Please try running on CPU or CUDA (if available) to see if the issue persists. If it does, feel free to share any additional findings.

**Comment by agentmorris** [comment]
I can confirm that if I follow the instructions above, but replace:

`--device "mps"`

...with:

`--device "cpu"`

...the problem no longer manifests in my test, even with the new version of YOLOv5 on the AWS M1 VM where I can reproduce the issue.  So yes, based on this test, the issue seems specific to the mps backend.

**Comment by guybashan** [comment]
> Thank you for the details. Since you're using the latest version and still experiencing issues, it might be related to the MPS backend. Please try running on CPU or CUDA (if available) to see if the issue persists. If it does, feel free to share any additional findings.

I changed from "mps" to "cpu" and now the **weight** logs with no negative values.
The downside: instead of avg detection for ~10ms I went down to: ~70ms.

One more important thing: I didn't rerun the creation of the model. So I can only guess the issue is in the "detect.py" and not in the "train.py".

**Comment by pderrenger** [comment]
Thanks for testing that. It seems the issue is indeed with the MPS backend during detection. We'll investigate further. If you have more insights, please share them.

**Comment by guybashan** [comment]
Thanks a lot 🙏
Please let me know if there is any additional info I can supply.

**Comment by pderrenger** [comment]
@guybashan you're welcome! If you have any more details or observations, feel free to share them here. We're actively investigating the issue.

**Comment by pderrenger** [comment]
@guybashan thank you for your offer to help. If you have any new findings or details related to the issue, please feel free to share them here.

**Comment by agentmorris** [comment]
@pderrenger wrote:
> We'll investigate further

Was there ever a resolution to this issue?  These negative-width bounding boxes are particularly dramatic, but the issue is better described as "computation sometimes wrong on MPS HW", we're just more likely to notice it when negative-width boxes cause code to crash downstream.  I've seen numerous cases where it just makes coordinates wrong: sometimes a little, sometimes a lot.  In all cases, forcing CPU inference corrects the issue.  Anecdotally, the confidence and class values appear to be correct, it's only coordinates that appear to be wrong, though I haven't systematically verified that.

This seems somewhat severe as bugs go, any chance of taking a closer look at the repro I provided above?

**Comment by pderrenger** [comment]
Thanks for the ping, Dan—no upstream fix on our side yet; as an immediate mitigation, keep the forward pass on MPS but force post‑processing on CPU by moving predictions to CPU inside non_max_suppression (utils/general.py): 
```
def non_max_suppression(prediction, ...):
    if isinstance(prediction, torch.Tensor) and prediction.device.type == "mps":
        prediction = prediction.cpu()
    ...
```
This avoids the negative-width boxes while preserving MPS speed; alternatively, you can try enabling CPU fallback for unstable ops with: export PYTORCH_ENABLE_MPS_FALLBACK=1. Several recent MPS correctness reports upstream suggest this is a backend issue rather than YOLOv5; if this patch resolves your AWS M1 repro, we can reopen and also file it upstream with your minimal example. ([github.com](https://github.com/pytorch/pytorch/issues/111634))

**Comment by agentmorris** [comment]
Thanks, pointing me to look at NMS as a potential culprit is very helpful.

I can no longer reproduce this using the exact steps above; the "new" environment (current YOLOv5 repo with current dependencies as installed by pip) does not exhibit the same symptom.  I think that's good news, although it would be better news if we had a reason to think it's fixed: since this issue was a bit unpredictable before (it was deterministic for a given environment, but a little sensitive to the environment), it could be just hiding, e.g. the "fix" could just be that different MPS HW was issued by AWS.

That said, making a couple notes based on the fact that @pderrenger suggested this issue might be related to NMS.  It looks like the current YOLOv5 repo already does what @pderrenger suggested (move data to the CPU for NMS on MPS devices) [here](https://github.com/ultralytics/yolov5/blob/725b922eb16cddd396471b5a0148297b29143962/utils/general.py#L1035), whereas at [some point in history](https://github.com/ultralytics/yolov5/blob/c23a441c9df7ca9b1f275e8c8719c949269160d1/utils/general.py#L800) it did not do this.  That would feel like it must be the fix, except that if my notes are right, the code where it *doesn't* do this is the commit that was *working* when I opened this bug, which is... unsatisfying.  But since I can't reproduce it in this test harness, there's no further action here.  I'm going to assess whether forcing NMS to the CPU in my application fixes it, and if it does, I'm all set.

I noticed that the [equivalent function in the ultralytics package](https://github.com/ultralytics/ultralytics/blob/0ce094aeae5726d5dcce57ebdfbe4b53a058b55f/ultralytics/utils/nms.py#L67) does not appear to move data to the CPU for NMS on MPS devices, so it might be worth someone taking a look at whether newer models than the old YOLOv5 models I'm working with still have issues, but I don't have a repro to provide for that case.

**Comment by pderrenger** [comment]
Thanks for re-testing, Dan. Yes—current YOLOv5 main routes NMS to CPU when device is MPS to sidestep backend precision issues, which likely explains why you can’t reproduce now. We’ll track mirroring this guard in the ultralytics package for parity; if you still see coordinate drift there, please open an issue in ultralytics/ultralytics with a minimal MPS repro and your torch/torchvision versions (python -m torch.utils.collect_env). For background on how NMS is applied in the pipeline, see the NMS overview in the Ultralytics Docs. See the Non‑Maximum Suppression (NMS) Explained page for details.

**Comment by agentmorris** [comment]
FWIW, in the environments where I've been able to test, this issue appears to go away when upgrading to MacOS Tahoe.  I can't identify the precise OS version transition that fixed the issue, but this tracks with this being a mysterious low-level issue that only impacted M1 HW.  I suspect there was an MPS firmware issue that Apple fixed at some point, and we may never be able to fully reconstruct the issue.

**Comment by pderrenger** [comment]
@agentmorris Thanks for following up — that’s a very useful datapoint, and it does point to this likely being an Apple MPS/macOS issue rather than an active YOLOv5 bug; since it’s no longer reproducible on current setups, there’s nothing more to do on our side for now, but if anyone can still reproduce it on current `main`, please open a fresh issue with a minimal repro and `python -m torch.utils.collect_env`.
