### ISSUE TITLE
Is it possible for detect.py code to generate an RTSP stream with real-time detections?

### ISSUE THREAD

**Issue by NevilleMthw** [ultralytics/yolov5#12661]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,

I would like to know if there is a way to generate an RTSP stream to showcase real-time detections? Through the use of detect.py script. Is there such a functionality?

Thanks,
Neville

**Comment by glenn-jocher** [comment]
@NevilleMthw hi Neville,

Thanks for reaching out! The `detect.py` script does not natively support broadcasting the output as an RTSP stream. However, you can modify the script to include such functionality using OpenCV's VideoWriter with an appropriate GStreamer pipeline or another streaming method that supports RTSP.

For more details on how to use YOLOv5 for real-time inference and potentially adapting it for RTSP streaming, please refer to our documentation at https://docs.ultralytics.com/yolov5/.

Best of luck with your project, and if you have any more questions or need further assistance, feel free to ask!

**Comment by NevilleMthw** [comment]
Thanks for the reply, will definitely check on that. On a side note, is it possible to save the detected frames without the bounding boxes in the ```detect.py``` script?

**Comment by glenn-jocher** [comment]
@NevilleMthw, certainly! To save frames without bounding boxes, you would need to comment out or remove the lines in `detect.py` that draw the boxes on the frames. Specifically, look for the section of the code where the detections are being processed and bounding boxes are drawn, and then either skip that processing step or save the frames before that step occurs.

If you need further guidance on which lines to modify, please refer to the documentation or consider opening a discussion in the repo for community support. Happy coding! 😊👨‍💻
