### ISSUE TITLE
Custom training prediction issue. 

### ISSUE THREAD

**Issue by MajidAli44** [ultralytics/yolov5#12687]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have Trained YOLOv5 on custom datasets that can detect fire and smoke. Whenever I run and load the model using detect.py. it predicts everything is fine. but whenever I load a model using this
model = torch.hub.load('ultralytics/yolov5', 'custom', path=weights_path)
It sends the wrong prediction and cannot work well as compared detect.py.

**Comment by glenn-jocher** [comment]
@MajidAli44 hello! Thanks for reaching out and for checking the existing issues and discussions before posting your question. 🙌

It sounds like there might be a discrepancy between the predictions you get when using `detect.py` and when loading the model with `torch.hub.load`. Here are a few steps to ensure consistency:

1. **Check Model Weights**: Ensure that the `weights_path` you're using with `torch.hub.load` is the same as the one used in `detect.py`.

2. **Verify Environment**: Make sure that your Python environment is consistent when running both methods. Inconsistencies in library versions can sometimes cause unexpected behavior.

3. **Model Configuration**: Confirm that the model configuration (e.g., `yaml` file) is correctly specified when using `torch.hub.load`.

4. **Input Preprocessing**: Ensure that the input preprocessing is the same in both cases. `detect.py` handles preprocessing internally, so you'll need to replicate that when using the model directly.

5. **Inference Settings**: Double-check that the inference settings such as confidence thresholds and non-maximum suppression (NMS) are consistent between both methods.

If after checking these steps the issue persists, please provide a minimal reproducible example and any error messages or unexpected outputs you're encountering. This will help us diagnose the problem more effectively.

Remember to refer to our documentation for more detailed guidance on model usage and troubleshooting: https://docs.ultralytics.com/yolov5/.

Keep up the great work with your fire and smoke detection model! 🔥💨 Your contributions to safety and security are invaluable. If you have any more questions or need further assistance, feel free to ask. Happy coding!
