### ISSUE TITLE
当我训练时，开始都是正常的，但训练一定次数后会突然报错PermissionError: [Errno 13] Permission denied: 'runs\\train\\exp\\weights\\best.pt'，该错误提示出现在torch.save(ckpt, last)

### ISSUE THREAD

**Issue by Liu2021xx** [ultralytics/yolov5#12680]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

<img width="533" alt="000" src="https://github.com/ultralytics/yolov5/assets/89565785/166272ca-87fc-4611-8a86-9811d5136725">

### Environment

python3.8
touch1.9

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Liu2021xx hello! Thank you for reporting this issue. The `PermissionError` you're encountering when the training script tries to save `best.pt` suggests there might be a file access or permissions issue on your system. Here are a few steps you can try to resolve this:

1. Ensure that the directory `runs\train\exp\weights\` is not open in any other program, as this can lock the file.
2. Check that your user account has write permissions for the `runs\train\exp\weights\` directory.
3. If you're using Windows, disable any antivirus or backup software temporarily to see if it's interfering with file access.
4. Try running your training script as an administrator or with elevated privileges.
5. Ensure there's enough disk space available for saving the checkpoint.

If the issue persists, please provide more details about when the error occurs (e.g., after how many epochs) and whether it's reproducible if you restart the training. This will help us further diagnose the problem.

Thanks for your contribution to the YOLOv5 community! 😊

**Comment by HHHLLL1** [comment]
I have also encountered this problem. What is the cause of this problem and how can it be solved?

**Comment by pderrenger** [comment]
Likely cause is a Windows file lock or concurrent write (common with OneDrive/Dropbox sync, search indexers, or TensorBoard); please update to the latest YOLOv5 and requirements, then train to a fresh, non‑synced path and try disabling worker concurrency to rule out contention, e.g.:
git pull && pip install -U -r requirements.txt
python train.py ... --project C:/yolo_runs --name exp --workers 0
If it persists, share the full traceback and the exact epoch it fails.
