### ISSUE TITLE
Is it able to run YOLOv5 inference on non-NVIDIA GPUs?

### ISSUE THREAD

**Issue by khanhtrannnn** [ultralytics/yolov5#12688]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm working with the Khadas VIM3 board, a single-board computer. It uses a **Mali-G52 MP4 GPU**, which is not an NVIDIA GPU. It appears that YOLOv5 is compatible only with CUDA devices, as the debug log indicates a requirement for either CPU-only or CUDA devices. 

```
python3 detect.py --weights yolov5s-fp16.tflite --img-size 384 640 --conf 0.01 --line-thickness=1 --source data/videos/traffic5s.mp4 --device 0

AssertionError: Invalid CUDA '--device 0' requested, use '--device cpu' or pass valid CUDA device(s)
```

Could someone please confirm if YOLOv5 can utilize non-NVIDIA GPU? Thank you.

**Comment by glenn-jocher** [comment]
@khanhtrannnn hello! YOLOv5 primarily supports NVIDIA GPUs through CUDA for acceleration. However, you can run YOLOv5 on CPU or use the ONNX/TFLite models for running on other platforms that may support those formats. For a Mali-G52 MP4 GPU, you might want to explore running the TFLite model with inference backends that support Mali GPUs, such as Arm NN or TFLite's GPU delegate. Keep in mind that performance may vary and you might need to handle additional integration steps. For more detailed guidance, please refer to our documentation. Happy coding! 😊🚀
