### ISSUE TITLE
Process dead

### ISSUE THREAD

**Issue by zidanexu** [ultralytics/yolov5#127]
@glenn-jocher  wo train coco data by  default command python train.py --data data/coco.yaml --batch-size 256 with muti-gpu . 8 Tesla P40. I find processing will be dead after training about 50-60epoch.  
![image](https://user-images.githubusercontent.com/54395639/85021214-1f884a80-b1a4-11ea-9713-91642990c73b.png)

**Comment by glenn-jocher** [comment]
@zidanexu unless this is reproducible in a common environment (docker) with a common dataset (coco128), there is no action for us to take.
