### ISSUE TITLE
P6 models show the input dimensions as 640 instead of 1280, visualizing the model in Netron.

### ISSUE THREAD

**Issue by divineSix** [ultralytics/yolov5#12708]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm trying to use the L6 models in tensorrt with C++. When printing the input dimensions for the network, it shows up as 640. To confirm, I visualized the ONNX model in [Netron](https://netron.app/) and saw that the input dimensions are `1x3x640x640`.
**Shouldn't the input sizes be 1280, however? **

**Comment by glenn-jocher** [comment]
@divineSix hello! Thanks for reaching out. The P6 models are indeed designed for 1280x1280 inputs. However, the model configuration might default to 640x640 for compatibility or other reasons. When exporting the model to ONNX, you should specify the desired input resolution. This can be done by setting the `--img-size` argument to 1280 during the export process. If you've already done this and still see 640x640, it could be a bug or an issue with the export script.

Please ensure you're using the latest code from the repo and follow the export instructions in our documentation. If the issue persists, feel free to open a detailed issue with the steps to reproduce, and we'll look into it. Thanks for your contribution to the YOLOv5 community! 🚀
