### ISSUE TITLE
Can YOLOV5 keep the original picture size for training instead of resize?

### ISSUE THREAD

**Issue by ly1035327995** [ultralytics/yolov5#12712]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Can YOLOV5 keep the original picture size for training instead of resize?

### Additional

Can YOLOV5 keep the original picture size for training instead of resize?

**Comment by glenn-jocher** [comment]
@ly1035327995 hello! YOLOv5 typically resizes images for training to a consistent size for batch processing efficiency and GPU memory constraints. However, you can train with the original image sizes by setting the `--img-size` argument to the maximum dimensions of your dataset images. Keep in mind that this might require significant GPU memory, and you may need to adjust the batch size accordingly to fit your hardware capabilities. For more details on training custom models, please refer to our documentation. Happy training! 😊🚀

**Comment by ly1035327995** [comment]
Does YOLOV5 have detection heads with different resolutions for targets of different sizes?




李洋
***@***.***

学生


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ultralytics/yolov5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月7日(星期三) 凌晨4:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ultralytics/yolov5] Can YOLOV5 keep the original picture size for training instead of resize? (Issue #12712)





 
@ly1035327995 hello! YOLOv5 typically resizes images for training to a consistent size for batch processing efficiency and GPU memory constraints. However, you can train with the original image sizes by setting the --img-size argument to the maximum dimensions of your dataset images. Keep in mind that this might require significant GPU memory, and you may need to adjust the batch size accordingly to fit your hardware capabilities. For more details on training custom models, please refer to our documentation. Happy training! 😊🚀

**Comment by glenn-jocher** [comment]
@ly1035327995 yes, YOLOv5 utilizes multiple detection heads at different scales to detect objects of various sizes. This multi-scale approach is inherent to the YOLO architecture, allowing it to predict small, medium, and large objects effectively. The model processes the input image at three different scales, each responsible for detecting objects at different resolutions. 🎯🔍

Please refrain from sharing personal contact information on public forums to maintain privacy and security. If you have further questions, feel free to ask them here! Happy coding! 😄👨‍💻
