### ISSUE TITLE
TypeError: Argument given by name ('thickness') and position (4) in function plot_one_box()

### ISSUE THREAD

**Issue by iliesaya** [ultralytics/yolov5#1271]
I trained for 100 epoch , inference results are good, and I am trying to continue training for another 100 epoch :

`python train.py --img 416 --batch 8 --epochs 50 --data 'data/mydataset/data.yaml' --cfg ./models/yolov5s.yaml --weights 'runs/exp0_yolov5s_results/weights/best.pt' --name yolov5s_results  --cache`

result :

```
Logging results to runs/exp12_yolov5s_results
Starting training for 50 epochs...

     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
      0/49    0.902G   0.05424    0.1495  0.006613    0.2104       157       416:   0%|                                        | 0/57 [00:14<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 460, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 295, in train
    result = plot_images(images=imgs, targets=targets, paths=paths, fname=f)
  File "/home/jetson/git/yolov5/utils/general.py", line 1088, in plot_images
    plot_one_box(box, mosaic, label=label, color=color, line_thickness=tl)
  File "/home/jetson/git/yolov5/utils/general.py", line 995, in plot_one_box
    cv2.rectangle(img, c1, c2, color, thickness=tl, lineType=cv2.LINE_AA)
TypeError: Argument given by name ('thickness') and position (4)
```

if I print the value of c1 and c2 just before the line cv2.rectangle, I have this :

```
...
c1=(504, 836), c2=(540, 861)
c1=(416, 833), c2=(441, 870)
c1=(416, 904), c2=(448, 931)
c1=(911220328628224, 967), c2=(-911220328628224, 967)
```

if I go one callstack level above, and print boxes, I have this 

```
boxes = xywh2xyxy(image_targets[:, 2:6]).T
print(boxes)

[[    0.76777     0.79321     0.88478     0.83391     0.96787     0.77456     0.77456  5.2154e-08    0.092881     0.19971 -7.4506e-09     0.21158 -1.8626e-08 -2.6077e-08  2.1904e+12]
 [    0.04936     0.13754    0.064621     0.10023    0.054447      0.1935     0.24776           0           0     0.08497    0.091752    0.010358   0.0035755     0.17484     0.32576]
 [          1     0.84408     0.96278     0.88478           1     0.80847     0.80169     0.14884     0.33028      0.2845     0.06575     0.29976    0.062358     0.07762 -2.1904e+12]
 [    0.45972     0.19519     0.11888      0.1511     0.10193     0.24776     0.28846     0.46142      0.3495     0.14602     0.16636    0.071404    0.091752     0.23928     0.32576]]
```

There is something wrong with the coordinate of one of theses boxes. 

No issue running detect.py with the same weights/best.pt , results are good.

**Comment by glenn-jocher** [comment]
@iliesaya hi, thanks for the bug report. Could you provide a reproducible example, i.e. a notebook or code to reproduce?

**Comment by gkagkos** [comment]
cv2 expects a BGR format. Most likely you are trying to add a rectangle using an RGB format. Try to convert your image to BGR first.

Something like that should do the trick:
image_rgb = image_bgr[:, :, [2, 1, 0]]
image_rgb = image_bgr[:, :, ::-1]

**Comment by robmarkcole** [comment]
I am receiving the error `argument for rectangle() given by name ('thickness') and position (4)` on calling `results.show()` in the [Detailed Example](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading). This error is raised by the image created using `img2 = cv2.imread('bus.jpg')[:, :, ::-1]  # OpenCV image (BGR to RGB)`

**Comment by glenn-jocher** [comment]
@robmarkcole I just ran the 'Detailed Example' now in a new Colab notebook with no issues. The second image in the detailed example shows how to use cv2 rather than PIL for loading images.

<img width="1166" alt="Screenshot 2021-04-05 at 20 55 57" src="https://user-images.githubusercontent.com/26833433/113613387-74248580-9651-11eb-9125-ccf56917d166.png">

**Comment by nina-weng** [comment]
> cv2 expects a BGR format. Most likely you are trying to add a rectangle using an RGB format. Try to convert your image to BGR first.
> 
> Something like that should do the trick:
> image_rgb = image_bgr[:, :, [2, 1, 0]]
> image_rgb = image_bgr[:, :, ::-1]

I met the same problem and this works for me!
