### ISSUE TITLE
Retraining yolov5 for additional data

### ISSUE THREAD

**Issue by humairaneha** [ultralytics/yolov5#12723]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have trained a yolov5 model using the pre trained weight for my custom dataset.It contains approx 13000 images for training and validation  and total 8 classes are there.But for one class ,more data needed to be added to generalize prediction of various cases. But how can i retrain the model to fit with newly added data without retraining it from start.It takes around half an hour to complete one epoch.

**Comment by glenn-jocher** [comment]
@humairaneha hello! Great to hear you're expanding your dataset for better generalization. You can continue training your model with the new data by using the weights from your last training session. This process is often referred to as "fine-tuning."

Here's a concise step-by-step guide:

1. Prepare your new dataset, combining the original and the additional images for the class that needs more data.
2. Update your dataset configuration file if necessary to include the paths to the new images and annotations.
3. Resume training using the `--resume` flag with the command you used for the initial training, or specify the last saved weights with the `--weights` flag. This will continue training from where you left off.

For example:
```shell
python train.py --img 640 --batch 16 --epochs 100 --data your_dataset.yaml --weights path/to/last-saved-weights.pt --resume
```

Remember to adjust the `--img`, `--batch`, `--epochs`, and `--data` flags according to your specific needs.

For more detailed instructions, please refer to our documentation. Keep up the good work, and happy training! 🚀
