### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.general'

### ISSUE THREAD

**Issue by nisanurtas** [ultralytics/yolov5#12721]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-26-7781fda6a93e>](https://localhost:8080/#) in <cell line: 4>()
      2 import utils
      3 from IPython.display import Image  # for displaying images
----> 4 from utils.general import gdrive_download  # for downloading models/datasets
      5 print('torch %s %s' % (torch.__version__, torch.cuda.get_device_properties(0) if torch.cuda.is_available() else 'CPU'))

ModuleNotFoundError: No module named 'utils.general'

I'm getting this error after cloning the yolov5 repo and installing requirements. I'm running the code in Colab. At first i tried utils.google_utils then utils.downloads now this one utils.general. But everytime i got the same error.
```

"import torch
import utils
from IPython.display import Image  # for displaying images
from utils.general import gdrive_download  # for downloading models/datasets <<<<< here
print('torch %s %s' % (torch.__version__, torch.cuda.get_device_properties(0) if torch.cuda.is_available()
```

**Comment by glenn-jocher** [comment]
@nisanurtas hello! It looks like there might be an issue with your Python path or the way the repository was cloned. Please ensure that you're running your notebook from the root directory of the cloned YOLOv5 repository. If you're still facing the issue, you might want to try the following steps:

1. Restart your Colab runtime to ensure there are no conflicts from previous sessions.
2. Make sure you've executed the cell that clones the YOLOv5 repository and installs the requirements.
3. Use the following code snippet to navigate to the YOLOv5 directory before importing the module:

```python
%cd /path/to/yolov5
```

Replace `/path/to/yolov5` with the actual path where the repository is cloned.

If the problem persists, please refer to our documentation for more detailed instructions on setting up YOLOv5 in Colab. 😊

Keep in mind that the structure of the repository and the location of certain utilities can change over time, so always ensure you're working with the latest version of the code. If you have further issues, feel free to reach out!
