### ISSUE TITLE
RuntimeError: No such operator torchvision::nms

### ISSUE THREAD

**Issue by laomaup** [ultralytics/yolov5#1272]
Before submitting a bug report, please be aware that your issue **must be reproducible** with all of the following, otherwise it is non-actionable, and we can not help you:
 - **Current repo**: run `git fetch && git status -uno` to check and `git pull` to update repo
 - **Common dataset**: coco.yaml or coco128.yaml
 - **Common environment**: Colab, Google Cloud, or Docker image. See https://github.com/ultralytics/yolov5#environments
 
If this is a custom dataset/training question you **must include** your `train*.jpg`, `test*.jpg` and `results.png` figures, or we can not help you. You can generate these with `utils.plot_results()`.

## 🐛 Bug
Starting training for 30 epochs...

     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
      0/29    0.799G   0.07891   0.03296   0.06775    0.1796         2       640: 100%|████████████████████| 218/218 [00:51<00:00,  4.22it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95:   0%|                   | 0/19 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 482, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 318, in train
    results, maps, times = test.test(opt.data,
  File "/workspace/yolov5/test.py", line 125, in test
    output = non_max_suppression(inf_out, conf_thres=conf_thres, iou_thres=iou_thres)
  File "/workspace/yolov5/utils/general.py", line 661, in non_max_suppression
    i = torch.ops.torchvision.nms(boxes, scores, iou_thres)
  File "/root/anaconda3/envs/yolo5/lib/python3.8/site-packages/torch/_ops.py", line 61, in __getattr__
    op = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator torchvision::nms

## To Reproduce (REQUIRED)

Input:
```
python train.py --img 640 --batch 8 --epochs 30 --data ./data/handpose.yaml --cfg ./models/yolov5s.yaml --weights '' --device 0,1
Using CUDA device0 _CudaDeviceProperties(name='GeForce GTX 1080 Ti', total_memory=11177MB)
           device1 _CudaDeviceProperties(name='GeForce GTX 1080 Ti', total_memory=11178MB)

Namespace(adam=False, batch_size=8, bucket='', cache_images=False, cfg='./models/yolov5s.yaml', data='./data/handpose.yaml', device='0,1', epochs=30, evolve=False, global_rank=-1, hyp='data/hyp.scratch.yaml', image_weights=False, img_size=[640, 640], local_rank=-1, log_imgs=10, logdir='runs/', multi_scale=False, name='', noautoanchor=False, nosave=False, notest=False, rect=False, resume=False, single_cls=False, sync_bn=False, total_batch_size=8, weights='', workers=8, world_size=1)
Start Tensorboard with "tensorboard --logdir runs/", view at http://localhost:6006/
Install Weights & Biases for experiment logging via 'pip install wandb' (recommended)
Hyperparameters {'lr0': 0.01, 'lrf': 0.2, 'momentum': 0.937, 'weight_decay': 0.0005, 'warmup_epochs': 3.0, 'warmup_momentum': 0.8, 'warmup_bias_lr': 0.1, 'box': 0.05, 'cls': 0.5, 'cls_pw': 1.0, 'obj': 1.0, 'obj_pw': 1.0, 'iou_t': 0.2, 'anchor_t': 4.0, 'fl_gamma': 0.0, 'hsv_h': 0.015, 'hsv_s': 0.7, 'hsv_v': 0.4, 'degrees': 0.0, 'translate': 0.1, 'scale': 0.5, 'shear': 0.0, 'perspective': 0.0, 'flipud': 0.0, 'fliplr': 0.5, 'mosaic': 1.0, 'mixup': 0.0}
Overriding model.yaml nc=80 with nc=13

                 from  n    params  module                                  arguments                     
  0                -1  1      3520  models.common.Focus                     [3, 32, 3]                    
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]                
  2                -1  1     19904  models.common.BottleneckCSP             [64, 64, 1]                   
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]               
  4                -1  1    161152  models.common.BottleneckCSP             [128, 128, 3]                 
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]              
  6                -1  1    641792  models.common.BottleneckCSP             [256, 256, 3]                 
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]              
  8                -1  1    656896  models.common.SPP                       [512, 512, [5, 9, 13]]        
  9                -1  1   1248768  models.common.BottleneckCSP             [512, 512, 1, False]          
 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]              
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 12           [-1, 6]  1         0  models.common.Concat                    [1]                           
 13                -1  1    378624  models.common.BottleneckCSP             [512, 256, 1, False]          
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]              
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 16           [-1, 4]  1         0  models.common.Concat                    [1]                           
 17                -1  1     95104  models.common.BottleneckCSP             [256, 128, 1, False]          
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]              
 19          [-1, 14]  1         0  models.common.Concat                    [1]                           
 20                -1  1    313088  models.common.BottleneckCSP             [256, 256, 1, False]          
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]              
 22          [-1, 10]  1         0  models.common.Concat                    [1]                           
 23                -1  1   1248768  models.common.BottleneckCSP             [512, 512, 1, False]          
 24      [17, 20, 23]  1     48546  models.yolo.Detect                      [13, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
Model Summary: 191 layers, 7.28746e+06 parameters, 7.28746e+06 gradients

Optimizer groups: 62 .bias, 70 conv.weight, 59 other
Scanning images:   0%|                                                                                              | 0/1738 [00:00<?, ?it/s]WARNING: Ignoring corrupted image and/or label /workspace/yolov5/data/images/chen_7.jpg: setting an array element with a sequence.
Scanning images: 100%|█████████████████████████████████████████████████████████████████████████████████| 1738/1738 [00:00<00:00, 6555.56it/s]
Scanning labels /workspace/yolov5/data/labels.cache (1071 found, 0 missing, 0 empty, 0 duplicate, for 1737 images): 1071it [00:00, 10703.55itScanning labels /workspace/yolov5/data/labels.cache (1737 found, 0 missing, 0 empty, 0 duplicate, for 1737 images): 1737it [00:00, 10807.05it/s]
Scanning images: 100%|███████████████████████████████████████████████████████████████████████████████████| 145/145 [00:00<00:00, 5554.81it/s]
Scanning labels /workspace/yolov5/data/labels.cache (145 found, 0 missing, 0 empty, 0 duplicate, for 145 images): 145it [00:00, 8856.99it/s]

Analyzing anchors... anchors/target = 5.27, Best Possible Recall (BPR) = 1.0000
Image sizes 640 train, 640 test
Using 8 dataloader workers

```

Output:
Starting training for 30 epochs...

     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
      0/29    0.799G   0.07891   0.03296   0.06775    0.1796         2       640: 100%|████████████████████| 218/218 [00:51<00:00,  4.22it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95:   0%|                   | 0/19 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 482, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 318, in train
    results, maps, times = test.test(opt.data,
  File "/workspace/yolov5/test.py", line 125, in test
    output = non_max_suppression(inf_out, conf_thres=conf_thres, iou_thres=iou_thres)
  File "/workspace/yolov5/utils/general.py", line 661, in non_max_suppression
    i = torch.ops.torchvision.nms(boxes, scores, iou_thres)
  File "/root/anaconda3/envs/yolo5/lib/python3.8/site-packages/torch/_ops.py", line 61, in __getattr__
    op = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator torchvision::nms

## Environment

 - OS: [e.g. Ubuntu18.04]
 - GPU [e.g. 1080 Ti]
- CUDA [e.g. 10.1]
- python[e.g 3.8]

## Additional context
my conda Environment
_libgcc_mutex             0.1                        main    defaults
absl-py                   0.11.0                    <pip>
ca-certificates           2020.10.14                    0    defaults
cachetools                4.1.1                     <pip>
certifi                   2020.6.20          pyhd3eb1b0_3    defaults
chardet                   3.0.4                     <pip>
cycler                    0.10.0                    <pip>
Cython                    0.29.21                   <pip>
dataclasses               0.6                       <pip>
future                    0.18.2                    <pip>
google-auth               1.23.0                    <pip>
google-auth-oauthlib      0.4.2                     <pip>
grpcio                    1.33.2                    <pip>
idna                      2.10                      <pip>
kiwisolver                1.3.1                     <pip>
ld_impl_linux-64          2.33.1               h53a641e_7    defaults
libedit                   3.1.20191231         h14c3975_1    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
Markdown                  3.3.3                     <pip>
matplotlib                3.3.2                     <pip>
ncurses                   6.2                  he6710b0_1    defaults
numpy                     1.19.4                    <pip>
oauthlib                  3.1.0                     <pip>
opencv-python             4.4.0.46                  <pip>
openssl                   1.1.1h               h7b6447c_0    defaults
Pillow                    8.0.1                     <pip>
pip                       20.2.4                   py38_0    defaults
protobuf                  3.13.0                    <pip>
pyasn1                    0.4.8                     <pip>
pyasn1-modules            0.2.8                     <pip>
pyparsing                 2.4.7                     <pip>
python                    3.8.5                h7579374_1    defaults
python-dateutil           2.8.1                     <pip>
PyYAML                    5.3.1                     <pip>
readline                  8.0                  h7b6447c_0    defaults
requests                  2.24.0                    <pip>
requests-oauthlib         1.3.0                     <pip>
rsa                       4.6                       <pip>
scipy                     1.5.3                     <pip>
setuptools                50.3.0           py38hb0f4dca_1    defaults
six                       1.15.0                    <pip>
sqlite                    3.33.0               h62c20be_0    defaults
tensorboard               2.3.0                     <pip>
tensorboard-plugin-wit    1.7.0                     <pip>
tk                        8.6.10               hbc83047_0    defaults
torch                     1.7.0+cu101               <pip>
torchvision               0.8.1                     <pip>
tqdm                      4.51.0                    <pip>
typing-extensions         3.7.4.3                   <pip>
urllib3                   1.25.11                   <pip>
Werkzeug                  1.0.1                     <pip>
wheel                     0.35.1                     py_0    defaults
xz                        5.2.5                h7b6447c_0    defaults
zlib                      1.2.11               h7b6447c_3    defaults

**Comment by glenn-jocher** [comment]
It appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below. 


## Requirements

**Python 3.8** or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including **`torch>=1.6`**. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by glenn-jocher** [comment]
@laomaup all seems fine according to your pip list, not sure what the problem may be. Perhaps start from a clean venv and try again. You might also try the Docker image failing that.

**Comment by laomaup** [comment]
ok, i will try,think you.

**Comment by fmassa** [comment]
@glenn-jocher I just came across this issue from https://github.com/pytorch/vision/issues/1405#issuecomment-731056137

I would strongly recommend replacing https://github.com/ultralytics/yolov5/blob/199c9c787427ece5723d5309e1c7c524a99bc59d/utils/general.py#L326 with
`torchvision.ops.nms`, as in order for `torch.ops.torchvision` to be available, one first need to `import torchvision` to register NMS.

**Comment by glenn-jocher** [comment]
@fmassa ah I see. Thanks for the advice, I will create a PR for this!

**Comment by glenn-jocher** [comment]
@laomaup I've pushed a PR per @fmassa recommendations. Please `git pull` and see if the problem is fixed.

**Comment by laomaup** [comment]
it is work now，think you.



At 2020-11-20 17:41:40, "Francisco Massa" <notifications@github.com> wrote:

@glenn-jocher I just came across this issue from pytorch/vision#1405 (comment)

I would strongly recommend replacing https://github.com/ultralytics/yolov5/blob/199c9c787427ece5723d5309e1c7c524a99bc59d/utils/general.py#L326 with
torchvision.ops.nms, as in order for torch.ops.torchvision to be available, one first need to import torchvision to register NMS.

**Comment by glenn-jocher** [comment]
@laomaup great, glad to hear its working!

**Comment by serser** [comment]
I am adapting yolo code to pytorch 1.4.0 for legacy reasons. I am with torchvision 0.5.0. I still get,
```
  File "/workdir/me/yolov5/utils/general.py", line 377, in non_max_suppression
    i = torchvision.ops.nms(boxes, scores, iou_thres)  # NMS
  File "/workdir/anaconda3/envs/pt1.4/lib/python3.6/site-packages/torchvision/ops/boxes.py", line 36, in nms
    return torch.ops.torchvision.nms(boxes, scores, iou_threshold)
  File "/workdir/anaconda3/envs/pt1.4/lib/python3.6/site-packages/torch/_ops.py", line 61, in __getattr__
    op = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator torchvision::nms
```

Any suggestions?

**Comment by serser** [comment]
> /workdir/anaconda3/envs/pt1.4/lib/python3.6/site-packages/torchvision/ops/boxes.py

Might due to `conda`, installed with `pip` and this goes away.

**Comment by glenn-jocher** [comment]
@serser out of curiosity what's your constraint on upgrading `torch`?

**Comment by serser** [comment]
@glenn-jocher Nothing particular, down porting to pt1.4 only for compatibility reasons, where YOLO being a new component while all others stick with pt1.4.
