### ISSUE TITLE
Mosaic Bounding Box issue

### ISSUE THREAD

**Issue by Kanan99** [ultralytics/yolov5#12735]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

When I visualize the images after applying mosaic augmentation, I notice that the bounding box from the original image affects the augmented image. In particular, it appears that the bounding box extends into the neighboring image, resulting in overlap in the center of the mosaic.
![mosaic](https://github.com/ultralytics/yolov5/assets/64705865/36d0333a-a331-4423-9225-fe4eceaa7032)

Here is the sample image.

Any idea on how to adjust the bounding boxes? 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Kanan99 hello! Thanks for bringing this to our attention. 🙌

The issue you're describing with the bounding boxes extending into neighboring images during mosaic augmentation is indeed unexpected behavior. It's possible that there might be a bug in the mosaic data augmentation code or in the visualization script.

To address this, could you please ensure that you're using the latest version of the YOLOv5 repository? If the issue persists, it would be very helpful if you could provide a minimal reproducible example via a pull request or by sharing the relevant code snippet and environment details. This will allow us to investigate the issue more thoroughly.

In the meantime, you can refer to our documentation for more information on data augmentation and troubleshooting: https://docs.ultralytics.com/yolov5/

Your contribution to improving YOLOv5 is greatly appreciated, and we look forward to your PR. If you have any further questions or need assistance, please don't hesitate to ask.

Happy coding! 😊
