### ISSUE TITLE
Cannot export custom trained pytorch model to tensorflow pb or saved_model

### ISSUE THREAD

**Issue by useruser2023** [ultralytics/yolov5#12734]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Export

### Bug

Cannot export custom trained yolov5 nano model with two classes to tensorflow pb or saved_model.  This same issue also exists in yolov3-tiny as well.

### Environment

- Yolov5 nano

### Minimal Reproducible Example

```
python export.py --data dataset.yaml --weights best.pt --include saved_model pb  --img 320
````

### Additional

Error: 
```
PyTorch: starting from best.pt with output shape (1, 6, 2100) (5.0 MB)
2024-02-15 18:48:48.935062: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-15 18:48:48.935336: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-15 18:48:48.966243: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

TensorFlow SavedModel: starting export with tensorflow 2.15.0...
WARNING ⚠️ using Tensorflow 2.15.0 > 2.13.1 might cause issue when exporting the model to tflite https://github.com/ultralytics/yolov5/issues/12489

                 from  n    params  module                                  arguments                     
TensorFlow SavedModel: export failure ❌ 3.3s: 'anchors'

TensorFlow GraphDef: starting export with tensorflow 2.15.0...
TensorFlow GraphDef: export failure ❌ 0.0s: 'NoneType' object has no attribute 'inputs'

```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@useruser2023 hello! Thank you for reporting this issue and for providing detailed information. It seems like there might be a compatibility problem with TensorFlow version 2.15.0, as indicated by the warning message you received.

Could you please try downgrading TensorFlow to version 2.13.1 or lower and attempt the export again? This might resolve the export failure you're experiencing.

If the problem persists after downgrading, please provide the full error traceback, and we'll investigate further. You can also refer to our documentation for additional guidance on model export procedures.

Thank you for your contribution to the YOLOv5 community! 🚀

**Comment by useruser2023** [comment]
Still not working this is the trace 
```
TensorFlow SavedModel: export failure ❌ 3.5s: 'anchors'
Traceback (most recent call last):
  File "/home/linux/Github/yolov5/export.py", line 126, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/home/linux/Github/yolov5/export.py", line 410, in export_saved_model
    tf_model = TFModel(cfg=model.yaml, model=model, nc=model.nc, imgsz=imgsz)
  File "/home/linux/Github/yolov5/models/tf.py", line 456, in __init__
    self.model, self.savelist = parse_model(deepcopy(self.yaml), ch=[ch], model=model, imgsz=imgsz)
  File "/home/linux/Github/yolov5/models/tf.py", line 383, in parse_model
    anchors, nc, gd, gw, ch_mul = d['anchors'], d['nc'], d['depth_multiple'], d['width_multiple'], d.get(
KeyError: 'anchors'

TensorFlow GraphDef: starting export with tensorflow 2.13.1...
TensorFlow GraphDef: export failure ❌ 0.0s: 'NoneType' object has no attribute 'inputs'
Traceback (most recent call last):
  File "/home/linux/Github/yolov5/export.py", line 126, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/home/linux/Github/yolov5/export.py", line 445, in export_pb
    m = m.get_concrete_function(tf.TensorSpec(keras_model.inputs[0].shape, keras_model.inputs[0].dtype))
AttributeError: 'NoneType' object has no attribute 'inputs'

```

**Comment by glenn-jocher** [comment]
@useruser2023 thank you for providing the traceback. It appears there's an issue with the 'anchors' key in the model configuration and a problem with the 'inputs' attribute during the TensorFlow export process.

To resolve the 'anchors' KeyError, please ensure that your `dataset.yaml` file and model configuration are correctly set up with the anchor definitions. The export script expects the 'anchors' key to be present in the model configuration.

For the 'NoneType' AttributeError, it seems the script is unable to access the input specifications of the Keras model. This could be due to an issue with the model loading process or the conversion to a TensorFlow Keras model.

Please double-check your custom model configuration and dataset files for any discrepancies. If everything seems correct, you might want to try retraining the model with the correct configuration and then attempt to export again.

If the issue persists, it might be helpful to open a new issue with the full details of your custom model configuration and dataset so that we can replicate the problem and look into it further.

Thank you for your patience and for working with us to improve YOLOv5! 🛠️

**Comment by useruser2023** [comment]
@glenn-jocher 

> To resolve the 'anchors' KeyError, please ensure that your dataset.yaml file and model configuration are correctly set up with the anchor definitions. The export script expects the 'anchors' key to be present in the model configuration.

what `anchors` configuration are we talking about here

I will share my dataset.yaml and training files here.

```
# training.py

from ultralytics import YOLO

# Load the model.
model = YOLO('yolov5nu.pt')  # load a pre-trained model
 
# Training.
results = model.train(
   data='/full/path/dataset.yaml',
   imgsz=320, 
   epochs=1,
   batch=32,   
   name='desc',  
   ) 
```

Yaml file

```
# dataset.yaml

path: /full/path/dataset
train: images/train
val: images/val

names:
 0: class1
 1: class2

```

what changes should I make here?

**Comment by akiannejad123** [comment]
I am having similar issues with this same model, yolov5n.pt. when I train the training goes well. However when i export to another model it saves but the model does not have input layers when converting to onnx, pb, or saved_model.

**Comment by glenn-jocher** [comment]
@akiannejad123 it seems there's a misunderstanding regarding the model configuration and the export process. The `anchors` configuration mentioned earlier typically refers to the anchor box dimensions that YOLO models use to predict object locations. These are usually defined in the model's architecture file (`*.yaml` for YOLOv5), not in the `dataset.yaml` or the training script.

From the details you've provided, it looks like you're using a high-level training interface (`YOLO('yolov5nu.pt')`) and your `dataset.yaml` seems correctly set up for training purposes. However, for exporting models, especially custom-trained models, you need to ensure that the model architecture file (`*.yaml`) used during training includes the necessary configurations, including `anchors` if required by the model architecture.

For the issue of the model not having input layers when converting to ONNX, PB, or TensorFlow SavedModel, this could be related to how the model is being loaded or interpreted during the export process. The export scripts provided with YOLOv5 are designed to handle these conversions, but they rely on specific model configurations and structures.

Here are a few steps you can take to troubleshoot and potentially resolve your issues:

1. **Ensure Model Compatibility**: Make sure the model architecture (`*.yaml` file used during training) is fully compatible with the export script. This includes having all necessary configurations like `anchors` defined.

2. **Review Export Script Usage**: When using the `export.py` script, ensure you're specifying all required arguments correctly, including the `--weights` argument pointing to your custom-trained model weights.

3. **Model Architecture File**: For custom models or modifications, ensure the model architecture file (`*.yaml`) is correctly set up. This file should match the structure and requirements of YOLOv5 models, including any necessary custom configurations like `anchors`.

4. **Update and Retry**: If you haven't already, ensure you're using the latest version of the YOLOv5 repository. Sometimes, issues are resolved in newer releases.

5. **Detailed Error Reporting**: If problems persist, consider opening an issue on the YOLOv5 GitHub repository with detailed information, including the exact command you're using for export, the full error message, and details about your custom model architecture.

Remember, successful export of models, especially for formats like ONNX, PB, or TensorFlow SavedModel, requires that the model and its configurations are fully compatible with the expected input and output structures of these formats.
