### ISSUE TITLE
export int8 tflite with customdataset

### ISSUE THREAD

**Issue by timingisnow** [ultralytics/yolov5#12730]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, there

I trained custom dataset and got a .pt file and I tried to convert .pt to .tflite.
Shell script is running well, and I tried to infer a image to predict.
But class name of detection result is not correct.

**ex) custom dataset class label are A, B, C and predicted class has to be 'C' which is class_index=2,
      but the class of inferenced image is 'car' which is class_index=2 of coco128.yaml**

below is my export.py shell script:
**python export.py --data custom_dataset.yaml --weight /home/aaa/yolov5/runs/train/moel_res/weights/best.pt --int8 --include tflite**

I tried to find if --data parameter is correct but I can't find yet.

Thanks.

**Comment by timingisnow** [comment]
Close this issue

converting is successful but found reason of the above problem.
Solve : when running detect.py add parameter --data..

**Comment by glenn-jocher** [comment]
@timingisnow great to hear you've resolved the issue! If you have any more questions or run into further issues, feel free to reach out. Happy detecting! 😊👍
