### ISSUE TITLE
How can YOLOv5 enable multi-scale training?

### ISSUE THREAD

**Issue by ly1035327995** [ultralytics/yolov5#12742]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How can YOLOv5 enable multi-scale training?

**Comment by glenn-jocher** [comment]
@ly1035327995 hello!

YOLOv5 enables multi-scale training by default. The training process randomly selects a new image size every 10 batches from a range that you can define in the `*.yaml` configuration file under the `imgsz_train` parameter. The default range is 640 to 1280 pixels.

If you want to adjust the range of scales for your specific use case, you can modify the `imgsz_train` parameter in your dataset's YAML file. For example, setting `imgsz_train: [320, 640]` would train your model on image sizes randomly chosen from between 320 to 640 pixels.

For more details on configuring your training, you can refer to our documentation. Happy training! 😊🚀
