### ISSUE TITLE
polygon2bbox

### ISSUE THREAD

**Issue by 6894556** [ultralytics/yolov5#12752]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hi, I've trained detection model with my custom polygon annotated dataset. 'val_batch0_labels.jpg' showed me bboxes not polygons.  I am curious how yolov5 have transformed my polygons into bboxes. I'll  really appreciate it if you can point out where is that code line. thanks.

**Comment by glenn-jocher** [comment]
@6894556 hello! Thanks for reaching out. YOLOv5 converts polygons to bounding boxes by finding the minimum and maximum x and y coordinates of the polygon points. This process effectively creates a bounding box that encompasses the entire polygon. The conversion code is part of the dataset loading utilities.

For the exact implementation, you can refer to the dataset loading code in the YOLOv5 repository. If you need more detailed guidance, please check out our documentation at https://docs.ultralytics.com/yolov5/ for further information on how datasets are handled.

If you have any more questions or need further assistance, feel free to ask. Happy coding! 😊👍

**Comment by 6894556** [comment]
@glenn-jocher Thanks to you I think I've found it at https://github.com/ultralytics/yolov5/blob/master/utils/dataloaders.py#L1101 ! It was an amazing experience 😊

**Comment by glenn-jocher** [comment]
@6894556 That's great to hear! I'm glad you found the section of the code you were looking for. If you have any more questions or need further assistance as you continue to work with YOLOv5, don't hesitate to reach out. The community and the Ultralytics team are always here to help. Keep up the amazing work! 😊🚀
