### ISSUE TITLE
how to do real-time object detection? with yolov5 and Opencv

### ISSUE THREAD

**Issue by KhaiHoanNinh** [ultralytics/yolov5#12795]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

when I do real-time object detection with a camera and OpenCV. I need to deploy a real-time object detection window (screen) to an app GUI that I've made but I can not find the source of it. how can I do it?

### Additional

![image](https://github.com/ultralytics/yolov5/assets/106177439/00b2d1d2-d829-4f16-b782-7d88ee07e24a)
I need to deploy it to the live camera

**Comment by glenn-jocher** [comment]
@KhaiHoanNinh hello! It's great to see your interest in deploying real-time object detection using YOLOv5 and OpenCV. For integrating YOLOv5 with a live camera feed in an application GUI, you'll typically follow these steps:

1. **Capture Video Stream**: Use OpenCV to capture video stream from your camera. You can do this with `cv2.VideoCapture`.

2. **Load YOLOv5 Model**: Load your YOLOv5 model using our PyTorch Hub integration or by directly loading the model weights.

3. **Process Frames**: For each frame from your camera, convert the frame into the format expected by YOLOv5 (usually resizing and normalization), then pass it through the model to get predictions.

4. **Display Predictions**: Process the model's predictions (bounding boxes, classes, and confidence scores) and overlay them on the original frame. Then, display this frame in your GUI.

5. **Loop**: Repeat steps 3 and 4 for each new frame from the camera to achieve real-time performance.

For specific code examples and more detailed instructions, please refer to our documentation at https://docs.ultralytics.com/yolov5/. This includes examples on how to use YOLOv5 with PyTorch for real-time detections, which can be adapted for use with OpenCV for capturing and displaying the video feed.

Remember, if you're planning to use YOLOv5 in a commercial application or need to integrate it into a proprietary solution, you'll need an Ultralytics Enterprise License. The AGPL-3.0 license allows for usage as long as the entire project is open-sourced under the same license. For any commercial or internal company usage not intended to be open-sourced, an Enterprise License is required.

If you have further questions or need clarification, feel free to ask. Happy coding! 😊
