### ISSUE TITLE
HSV Augmentation

### ISSUE THREAD

**Issue by Kanan99** [ultralytics/yolov5#12790]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I looked for in different issues and discussions and can't come up with any tip

I would like to know what are the possible range for h,s,v values. 

```
hsv_h: 0.0  # image HSV-Hue augmentation (fraction)
hsv_s: 0.0 # image HSV-Saturation augmentation (fraction)
hsv_v: 0.0 # image HSV-Value augmentation (fraction)
```

**Comment by glenn-jocher** [comment]
@Kanan99 hello! Thanks for reaching out with your question. 😊

For HSV augmentation in YOLOv5, the `hsv_h`, `hsv_s`, and `hsv_v` parameters are indeed specified as fractions. These values represent the maximum possible change as a fraction of the total range for each channel:

- `hsv_h`: Hue. This can be in the range [0.0, 1.0], where 1.0 would allow the hue to be shifted by up to 360 degrees.
- `hsv_s`: Saturation. This is also in the range [0.0, 1.0], with 1.0 allowing for a shift to either completely desaturated or fully saturated.
- `hsv_v`: Value (brightness). This parameter is in the range [0.0, 1.0] as well, where 1.0 permits adjusting the brightness to its maximum or minimum value.

Adjusting these parameters can significantly affect the appearance of your images, so it's wise to experiment with small changes to see their effects. For more detailed guidance on augmentation and other features, please refer to our documentation at https://docs.ultralytics.com/yolov5/.

If you have any more questions or need further assistance, feel free to ask. Happy training! 🚀
