### ISSUE TITLE
Is there any differences between using '--single-cls' and not? Thanks

### ISSUE THREAD

**Issue by wangmh1116** [ultralytics/yolov5#128]

**Comment by glenn-jocher** [comment]
@wangmh1116 --single-cls trains any dataset in single class mode.

**Comment by mad-fogs** [comment]
> @wangmh1116 --single-cls trains any dataset in single class mode.

I set single-cls to be store_false but seems like all output labels are 0(class 0 name).
How to disable this option?

**Comment by glenn-jocher** [comment]
store_true arguments are default False
