### ISSUE TITLE
I changed to use OTA Loss but when start traning the erorr occured, how can i sovle it

### ISSUE THREAD

**Issue by oldg00se** [ultralytics/yolov5#12802]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Traceback (most recent call last):
File "e:\yolov5-6.1-ota\train-ota.py", line 655, in
main(opt)
File "e:\yolov5-6.1-ota\train-ota.py", line 551, in main
train(opt.hyp, opt, device, callbacks)
File "e:\yolov5-6.1-ota\train-ota.py", line 342, in train
loss, loss_items = compute_loss(pred, targets.to(device), imgs) # loss scaled by batch_size
File "E:\anaconda\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "E:\anaconda\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
return forward_call(*args, **kwargs)
File "e:\yolov5-6.1-ota\utils\ota.py", line 147, in forward
return self.get_losses(
File "e:\yolov5-6.1-ota\utils\ota.py", line 337, in get_losses
reg_target = gt_bboxes_per_image[matched_gt_inds]
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

**Comment by glenn-jocher** [comment]
@oldg00se hello! It looks like you're encountering a device mismatch error during training with the OTA loss. This error typically occurs when tensors are not on the same device (CPU/GPU) during operations.

To solve this, ensure that all tensors involved in the operation, including `gt_bboxes_per_image` and `matched_gt_inds`, are on the same device. You can do this by explicitly moving tensors to the desired device using `.to(device)` where `device` is either `'cuda'` for GPU or `'cpu'`.

For example, if `gt_bboxes_per_image` is a tensor that needs to be on the same device as `matched_gt_inds`, you can use:
```python
gt_bboxes_per_image = gt_bboxes_per_image.to(device)
```
Make sure to replace `device` with the actual device variable you're using in your code.

If you're still facing issues, please ensure your environment is set up correctly as per the installation instructions in our docs, and consider reviewing your modifications related to the OTA loss implementation for any device-specific operations that might have been overlooked.

For further assistance, feel free to share more detailed code snippets or context around the modifications you've made. Happy coding! 😊
