### ISSUE TITLE
An error in YOLOv5s summary

### ISSUE THREAD

**Issue by qruiwu** [ultralytics/yolov5#12806]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

After my YOLO v5 model trained, an error was apear in "YOLOv5s summary" process, and I have no idea how to solve it. If anyone know that, please tell me, thank you!
![QQ截图20240311110102](https://github.com/ultralytics/yolov5/assets/125649238/35ddb278-8c1a-4226-bd6d-1f20249dc92d)

**Comment by glenn-jocher** [comment]
@wuqrcn hello! Thanks for reaching out and for doing your due diligence by searching through existing issues and discussions before posting. 🌟

It seems like there might be an issue with the summary process after training your YOLOv5 model. To better assist you, could you please provide more specific details about the error message you're encountering? Unfortunately, the image link you've shared doesn't seem to work, so if you could describe the error text or share the error message directly in your reply, that would be very helpful.

In the meantime, ensure that you're using the latest version of the YOLOv5 repository, as updates often include bug fixes and improvements that might resolve your issue. Also, reviewing the [Ultralytics Docs](https://docs.ultralytics.com/yolov5/) could provide additional insights or steps for troubleshooting.

Looking forward to your response to assist you further! 🚀

**Comment by qruiwu** [comment]
This error caused by the conflicting library of Pillow, rewrite "Pillow<=9.5.0" in the requirements.txt, and install this version in the Python environment, and then the error can be solved.

**Comment by qruiwu** [comment]
This error caused by the conflicting library of Pillow, rewrite "Pillow<=9.5.0" in the requirements.txt, and install this version in the Python environment, and then the error can be solved.

**Comment by glenn-jocher** [comment]
@wuqrcn, fantastic detective work there! 🕵️‍♂️

Pinpointing library conflicts can indeed be tricky. For others who might encounter a similar issue, here's a quick guide based on your discovery:
1. Open `requirements.txt` in your project folder.
2. Find the line with `Pillow` and change it to `Pillow<=9.5.0`.
3. Save the file and run `pip install -r requirements.txt` in your Python environment to install the specified version of Pillow.

This should help resolve conflicts and get you back on track. Thanks for sharing your solution with the community!🚀
