### ISSUE TITLE
face crop

### ISSUE THREAD

**Issue by BooHooClaping** [ultralytics/yolov5#12817]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

what python and torch must be used? i  got error use yolov5_anime , my pthon 3.10.11 and torch 2.0

**Comment by glenn-jocher** [comment]
@BooHooClaping hello! For YOLOv5, we recommend using Python 3.8 or later and PyTorch 1.7 or later. However, your setup with Python 3.10.11 and Torch 2.0 should generally be compatible. If you're encountering specific errors, please ensure you've followed the installation instructions in our documentation and have all the necessary dependencies installed. If issues persist, feel free to share the error messages you're receiving for further assistance. Happy coding! 😊
