### ISSUE TITLE
GFLOPs

### ISSUE THREAD

**Issue by ZCzzzzzz** [ultralytics/yolov5#12821]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Can you tell me what the Chinese meaning of GFLOPs is?

**Comment by glenn-jocher** [comment]
@ZCzzzzzz hey there! 😊 GFLOPs stands for *Giga Floating Point Operations per Second*. It's a measure of a computer's performance, especially useful for understanding how fast a model like YOLOv5 can run. In Chinese, it can be translated as 千亿次浮点运算每秒. Happy coding!

**Comment by ZCzzzzzz** [comment]
Is it 100 billion floating-point operations per second? Isn't it a billion floating-point operations per second?

**Comment by glenn-jocher** [comment]
@ZCzzzzzz hey there! 😊 You're right, "Giga" means billion, so GFLOPs indeed stands for *billion floating-point operations per second.* Thanks for catching that! Happy coding!
