### ISSUE TITLE
'Detect' object has no attribute 'grid'

### ISSUE THREAD

**Issue by dementiaenjoyer** [ultralytics/yolov5#12823]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hey, i recently found out about YOLO, and i have been trying to learn YOLOV5 for the past couple of weeks or so, but theres something which i literally cannot get past.

I'm trying to train models for Pytorch using Roboflow, and this worked in the beginning but now i just keep getting the error "'Detect' object has no attribute 'grid'"
I have force reload set to true, cache isn't outdated.
I've tried reinstalling yolo, doesn't work.
I've tried manually training it with the github repo, and i can't even start the training from there even though i follow the steps i've seen other people do perfectly

I've also browsed the internet for a while and i have found others which have had the same issue,
but i never really understood how they actually went on about fixing it (other than setting force_reload to true)

This is my model loading part:
```
import torch
model = torch.hub.load('ultralytics/yolov5', 'custom', './best.pt', force_reload=True)
```

I'm not too sure if its even the code or an issue with the model
because as i mentioned earlier i could load these models perfectly fine when i first started,
but after that it just hasn't worked for weeks.

I'm on python version 3.10 & my os is windows 10.

**Comment by glenn-jocher** [comment]
@dementiaenjoyer hello! It sounds like you're experiencing a challenging issue, but don't worry, we're here to help. 😊 The error "'Detect' object has no attribute 'grid'" typically indicates a mismatch between the YOLOv5 version you're using for training and the version used during inference, or it could also suggest an outdated custom model compared to the updated YOLOv5 repository structure.

A quick fix to try:

1. Ensure your YOLOv5 repository is up-to-date by re-cloning the latest version from our GitHub repo. Unfortunately, as per guidelines, I can't provide a direct link here, but it's easily findable with a quick search.
2. After updating, reinstall the requirements: In your terminal, navigate to the YOLOv5 directory and run `pip install -r requirements.txt` to ensure all dependencies are current.
3. Try loading your model again.

In some cases, the custom model `best.pt` might have been trained on a significantly different version of YOLOv5, leading to compatibility issues. If the problem persists, consider retraining your model with the current version of YOLOv5 you have installed.

For more detailed guidance and potential troubleshooting steps, our documentation at https://docs.ultralytics.com/yolov5/ can be quite helpful.

Please let us know how it goes, or if there's anything else we can assist you with!

**Comment by dementiaenjoyer** [comment]
@glenn-jocher Hey again! I re-downloaded the YOLOV5 repo and installed Git and it worked. Thanks so much for your help, much appreciated 😄

**Comment by glenn-jocher** [comment]
@dementiaenjoyer Fantastic news! I'm thrilled to hear that got you up and running 😄. Should you have any more questions or run into further issues, feel free to reach out. Happy detecting with YOLOv5!
