### ISSUE TITLE
How to input image with original size to model in onnx format 

### ISSUE THREAD

**Issue by HouseWay** [ultralytics/yolov5#12829]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When I use exported onnx model to predict, it default resizes my input image size to 640x640.
I want to input with orginal iamge size
How do I do it?

**Comment by HouseWay** [comment]
I solved it.
add' imgsz' in `predict`
'onnx_model.predict(image_path, imgsz=5120)'

**Comment by glenn-jocher** [comment]
@HouseWei hello! Glad to hear you found a solution 🎉. It's great to see you're making progress with the ONNX model using YOLOv5. Just a heads-up, when specifying the `imgsz` parameter directly in the `predict` function like `onnx_model.predict(image_path, imgsz=5120)`, ensure that the image size is aligned with your model's capabilities and the constraints of your computing resources. Adjusting `imgsz` can significantly impact performance and accuracy, so it’s good to experiment with this setting to find the best balance for your specific use case. Happy coding and thanks for being part of the YOLOv5 community!
