### ISSUE TITLE
Is this seemingly faster way of hyperparameter evolution going to be effective?

### ISSUE THREAD

**Issue by NazmulTakbir** [ultralytics/yolov5#1282]
## ❔Question
I want to perform hyperparameter evolution for my custom training data. Since it is a very time consuming process, can I use much smaller size images for hyperparameter evolution. And then use those evolved hyperparameters to train a network with much larger image sizes. 

## Additional context
I want to perform hyperparameter evolution mainly to solve the problem of very high class imbalance in the custom training data, as it has been suggested here - https://github.com/ultralytics/yolov5/issues/1115#issuecomment-706686386

**Comment by glenn-jocher** [comment]
@NazmulTakbir correlation between your base scenario and your hyperparameter evolution scenario is up to you. As the two diverge, the correlation in improvements between the two will also naturally diverge.
