### ISSUE TITLE
After segment, how can i hide the detect bbox?

### ISSUE THREAD

**Issue by fewshotstudy** [ultralytics/yolov5#12832]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

After segment, how can i hide the detect bbox?

### Additional

After segment, how can i hide the detect bbox?

**Comment by glenn-jocher** [comment]
@fewshotstudy hello! To hide detection bounding boxes after segmentation in your results, a simple approach would be not to draw them. If you are using the visualization functions in YOLOv5, you can modify the code that plots or adds the bounding boxes to the image or output frame. Specifically, you can skip the drawing function or remove the code block that overlays bounding boxes.

For a more precise recommendation, it would help to know exactly how you're processing or visualizing your output. Generally, the modification would be where you're handling the visualization part of your pipeline. If you're using the default `detect.py`, look where results are plotted and adjust accordingly.

Remember, changes in the code might differ based on your use case and how you're running the model. If you have more context or specifics, feel free to share! 🚀

**Comment by fewshotstudy** [comment]
> @fewshotstudy hello! To hide detection bounding boxes after segmentation in your results, a simple approach would be not to draw them. If you are using the visualization functions in YOLOv5, you can modify the code that plots or adds the bounding boxes to the image or output frame. Specifically, you can skip the drawing function or remove the code block that overlays bounding boxes.
> 
> For a more precise recommendation, it would help to know exactly how you're processing or visualizing your output. Generally, the modification would be where you're handling the visualization part of your pipeline. If you're using the default `detect.py`, look where results are plotted and adjust accordingly.
> 
> Remember, changes in the code might differ based on your use case and how you're running the model. If you have more context or specifics, feel free to share! 🚀

Thank you, Sir. I mean How to set in plots.py.

**Comment by fewshotstudy** [comment]
> @fewshotstudy hello! To hide detection bounding boxes after segmentation in your results, a simple approach would be not to draw them. If you are using the visualization functions in YOLOv5, you can modify the code that plots or adds the bounding boxes to the image or output frame. Specifically, you can skip the drawing function or remove the code block that overlays bounding boxes.
> 
> For a more precise recommendation, it would help to know exactly how you're processing or visualizing your output. Generally, the modification would be where you're handling the visualization part of your pipeline. If you're using the default `detect.py`, look where results are plotted and adjust accordingly.
> 
> Remember, changes in the code might differ based on your use case and how you're running the model. If you have more context or specifics, feel free to share! 🚀

I resolve it. Best regard!

**Comment by glenn-jocher** [comment]
@fewshotstudy That's great to hear! If you have any more questions or need further assistance in the future, don't hesitate to reach out. Happy coding! 😊🚀
