### ISSUE TITLE
Can you add parameter subdivisions like darknet in cfg file to enlarge the batch-size we can set?   

### ISSUE THREAD

**Issue by skyeyeCV** [ultralytics/yolov5#1284]
Hello, my GPU's memory is 8G and the maximum batch-size I can set is only 8 when training yolov5l and input image size is 640*640.Can you add parameter subdivisions like darknet in cfg file to enlarge the batch-size we can set?   Thanks a lot.

**Comment by glenn-jocher** [comment]
@skyeyeCV YOLOv5 already automatically accumulates losses up to a 64 effective batch size, while automatically scaling LR to compensate.

The only variable for you to modify is `--batch-size`, everything else is handled automatically.

**Comment by skyeyeCV** [comment]
> @skyeyeCV YOLOv5 already automatically accumulates losses up to a 64 effective batch size, while automatically scaling LR to compensate.
> 
> The only variable for you to modify is `--batch-size`, everything else is handled automatically.

@glenn-jocher Thanks for your reply. But when I set batch-size to 16 and start to train, it will tell me out of memory.Do you mean batch-size in yolov5 has the same meaning as batch/subdivisions in yolov3 and batch in yolov5 is fixed to 64?

In yolov3 cfg file, parameter batch and subdivision are show like this:
Training
batch=64
subdivisions=16
width=416
height=416
channels=3
momentum=0.9

**Comment by glenn-jocher** [comment]
Reduce batch size.
