### ISSUE TITLE
How to convert segment json data labeled by labelme to yolo format?

### ISSUE THREAD

**Issue by fewshotstudy** [ultralytics/yolov5#12841]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to convert segment json data labeled by labelme to yolo format?
Can you share some details code?

**Comment by glenn-jocher** [comment]
@fewshotstudy hello! 😊 Converting label formats is a common task. While we don't have a direct feature in YOLOv5 for converting LabelMe JSON to YOLO format, the general process involves parsing the JSON file to extract bounding box coordinates and then saving them in the YOLO format. 

Here's a simplified code outline to get you started:

```python
import json

def convert_labelme_to_yolo(json_path, output_path):
    with open(json_path) as f:
        data = json.load(f)
    # Assuming one object per file for simplicity
    width, height = data['imageWidth'], data['imageHeight']
    for shape in data['shapes']:
        label = shape['label']
        points = shape['points'] # Assuming rectangle: top-left and bottom-right
        x1, y1 = points[0]
        x2, y2 = points[1]
        # Convert to YOLO format
        x_center = (x1 + x2) / 2 / width
        y_center = (y1 + y2) / 2 / height
        w = abs(x2 - x1) / width
        h = abs(y2 - y1) / height
        # Save to file
        with open(output_path, 'a') as f:
            f.write(f'{label} {x_center} {y_center} {w} {h}\n')

# Example usage
convert_labelme_to_yolo('path/to/your/labelme.json', 'path/to/output.txt')
```

Please adjust the code to your specific needs, especially if you have multiple objects per image or other shape types. Happy coding! 🚀

**Comment by fewshotstudy** [comment]
Thank you.Sir!
I make it!

**Comment by glenn-jocher** [comment]
Fantastic news, @fewshotstudy! 😊 Great to hear you've achieved what you set out to do. If you have more questions or need further assistance down the road, feel free to reach out. Happy developing with YOLOv5! 🚀
