### ISSUE TITLE
Yolov5 Bug in Raspi

### ISSUE THREAD

**Issue by Jinairu** [ultralytics/yolov5#12848]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

I was trying to run the Yolov5 in raspi5, when i use the weight yolov5s.pt it does work, but when i use the best.pt it does give a error message.

Now the thing is that this best.pt is from the Windows that i used to train in my pc because it has a gpu for fast train purposes, it does also work in my pc when running its image processing in yolov5, but when i try it in my raspi5 it does give an error.

### Environment

detect: weights=['best.pt'], source=0, data=data/coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_csv=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
YOLOv5 🚀 v7.0-295-gac6c4383 Python-3.11.2 torch-2.2.1 CPU

Traceback (most recent call last):
  File "/home/AquaBot/Desktop/ObjectDetection/yolov5/detect.py", line 312, in <module>
    main(opt)
  File "/home/AquaBot/Desktop/ObjectDetection/yolov5/detect.py", line 307, in main
    run(**vars(opt))
  File "/home/AquaBot/venv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/AquaBot/Desktop/ObjectDetection/yolov5/detect.py", line 115, in run
    model = DetectMultiBackend(weights, device=device, dnn=dnn, data=data, fp16=half)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/AquaBot/Desktop/ObjectDetection/yolov5/models/common.py", line 467, in __init__
    model = attempt_load(weights if isinstance(weights, list) else w, device=device, inplace=True, fuse=fuse)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/AquaBot/Desktop/ObjectDetection/yolov5/models/experimental.py", line 98, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location="cpu")  # load
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/AquaBot/venv/lib/python3.11/site-packages/torch/serialization.py", line 1026, in load
    return _load(opened_zipfile,
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/AquaBot/venv/lib/python3.11/site-packages/torch/serialization.py", line 1438, in _load
    result = unpickler.load()
             ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 874, in __new__
    raise NotImplementedError("cannot instantiate %r on your system"
NotImplementedError: cannot instantiate 'WindowsPath' on your system

### Minimal Reproducible Example

AquaBot@raspberrypi:~ $ cd Desktop
AquaBot@raspberrypi:~/Desktop $ mkdir ObjectDetection
AquaBot@raspberrypi:~/Desktop $ cd ObjectDetection
AquaBot@raspberrypi:~/Desktop/ObjectDetection $ https://github.com/ultralytics/yolov5.git
bash: https://github.com/ultralytics/yolov5.git: No such file or directory
AquaBot@raspberrypi:~/Desktop/ObjectDetection $ git clone https://github.com/ultralytics/yolov5.git
Cloning into 'yolov5'...
remote: Enumerating objects: 16522, done.
remote: Counting objects: 100% (120/120), done.
remote: Compressing objects: 100% (104/104), done.
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 4516 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
AquaBot@raspberrypi:~/Desktop/ObjectDetection $ git clone https://github.com/ultralytics/yolov5.git
Cloning into 'yolov5'...
remote: Enumerating objects: 16522, done.
remote: Counting objects: 100% (120/120), done.
remote: Compressing objects: 100% (104/104), done.
remote: Total 16522 (delta 48), reused 52 (delta 16), pack-reused 16402
Receiving objects: 100% (16522/16522), 15.18 MiB | 356.00 KiB/s, done.
Resolving deltas: 100% (11305/11305), done.
AquaBot@raspberrypi:~/Desktop/ObjectDetection $ cd yolov5
AquaBot@raspberrypi:~/Desktop/ObjectDetection/yolov5 $ source ~/venv/bin/activate
(venv) AquaBot@raspberrypi:~/Desktop/ObjectDetection/yolov5 $ pip install requirements.txt
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement requirements.txt (from versions: none)
HINT: You are attempting to install a package literally named "requirements.txt" (which cannot exist). Consider using the '-r' flag to install the packages listed in requirements.txt
ERROR: No matching distribution found for requirements.txt
(venv) AquaBot@raspberrypi:~/Desktop/ObjectDetection/yolov5 $ pip install -r requirements.txt
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: gitpython>=3.1.30 in /home/AquaBot/venv/lib/python3.11/site-packages (from -r requirements.txt (line 5)) (3.1.42)
Requirement already satisfied: matplotlib>=3.3 in /home/AquaBot/venv/lib/python3.11/site-packages (from -r requirements.txt (line 6)) (3.8.3)
Requirement already satisfied: numpy>=1.23.5 in /home/AquaBot/venv/lib/python3.11/site-packages (from -r requirements.txt (line 7)) (1.26.4)
Requirement already satisfied: opencv-python>=4.1.1 in /home/AquaBot/venv/lib/python3.11/site-packages (from -r requirements.txt (line 8)) (4.9.0.80)
Requirement already satisfied: Pillow>=9.4.0 in /home/AquaBot/venv/lib/python3.11/site-packages (from -r requirements.txt (line 9)) (10.2.0)
Requirement already satisfied: psutil in /home/AquaBot/venv/lib/python3.11/site-packages (from -r requirements.txt (line 10)) (5.9.8)
Requirement already satisfied: PyYAML>=5.3.1 in /home/AquaBot/venv/lib/python3.11/site-packages (from -r requirements.txt (line 11)) (6.0.1)
Requirement already satisfied: requests>=2.23.0 in /home/AquaBot/venv/lib/python3.11/site-packages (from -r requirements.txt (line 12)) (2.31.0)
Requirement already satisfied: scipy>=1.4.1 in /home/AquaBot/venv/lib/python3.11/site-packages (from -r requirements.txt (line 13)) (1.12.0)
Requirement already satisfied: thop>=0.1.1 in /home/AquaBot/venv/lib/python3.11/site-packages (from -r requirements.txt (line 14)) (0.1.1.post2209072238)
Requirement already satisfied: torch>=1.8.0 in /home/AquaBot/venv/lib/python3.11/site-packages (from -r requirements.txt (line 15)) (2.2.1)
Requirement already satisfied: torchvision>=0.9.0 in /home/AquaBot/venv/lib/python3.11/site-packages (from -r requirements.txt (line 16)) (0.17.1)
Requirement already satisfied: tqdm>=4.64.0 in /home/AquaBot/venv/lib/python3.11/site-packages (from -r requirements.txt (line 17)) (4.66.2)
Requirement already satisfied: ultralytics>=8.0.232 in /home/AquaBot/venv/lib/python3.11/site-packages (from -r requirements.txt (line 18)) (8.1.30)
Requirement already satisfied: pandas>=1.1.4 in /home/AquaBot/venv/lib/python3.11/site-packages (from -r requirements.txt (line 27)) (2.2.1)
Requirement already satisfied: seaborn>=0.11.0 in /home/AquaBot/venv/lib/python3.11/site-packages (from -r requirements.txt (line 28)) (0.13.2)
Requirement already satisfied: setuptools>=65.5.1 in /home/AquaBot/venv/lib/python3.11/site-packages (from -r requirements.txt (line 42)) (66.1.1)
Requirement already satisfied: wheel>=0.38.0 in /home/AquaBot/venv/lib/python3.11/site-packages (from -r requirements.txt (line 50)) (0.43.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /home/AquaBot/venv/lib/python3.11/site-packages (from gitpython>=3.1.30->-r requirements.txt (line 5)) (4.0.11)
Requirement already satisfied: contourpy>=1.0.1 in /home/AquaBot/venv/lib/python3.11/site-packages (from matplotlib>=3.3->-r requirements.txt (line 6)) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /home/AquaBot/venv/lib/python3.11/site-packages (from matplotlib>=3.3->-r requirements.txt (line 6)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/AquaBot/venv/lib/python3.11/site-packages (from matplotlib>=3.3->-r requirements.txt (line 6)) (4.50.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/AquaBot/venv/lib/python3.11/site-packages (from matplotlib>=3.3->-r requirements.txt (line 6)) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /home/AquaBot/venv/lib/python3.11/site-packages (from matplotlib>=3.3->-r requirements.txt (line 6)) (24.0)
Requirement already satisfied: pyparsing>=2.3.1 in /home/AquaBot/venv/lib/python3.11/site-packages (from matplotlib>=3.3->-r requirements.txt (line 6)) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in /home/AquaBot/venv/lib/python3.11/site-packages (from matplotlib>=3.3->-r requirements.txt (line 6)) (2.9.0.post0)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/AquaBot/venv/lib/python3.11/site-packages (from requests>=2.23.0->-r requirements.txt (line 12)) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /home/AquaBot/venv/lib/python3.11/site-packages (from requests>=2.23.0->-r requirements.txt (line 12)) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/AquaBot/venv/lib/python3.11/site-packages (from requests>=2.23.0->-r requirements.txt (line 12)) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in /home/AquaBot/venv/lib/python3.11/site-packages (from requests>=2.23.0->-r requirements.txt (line 12)) (2024.2.2)
Requirement already satisfied: filelock in /home/AquaBot/venv/lib/python3.11/site-packages (from torch>=1.8.0->-r requirements.txt (line 15)) (3.13.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /home/AquaBot/venv/lib/python3.11/site-packages (from torch>=1.8.0->-r requirements.txt (line 15)) (4.10.0)
Requirement already satisfied: sympy in /home/AquaBot/venv/lib/python3.11/site-packages (from torch>=1.8.0->-r requirements.txt (line 15)) (1.12)
Requirement already satisfied: networkx in /home/AquaBot/venv/lib/python3.11/site-packages (from torch>=1.8.0->-r requirements.txt (line 15)) (3.2.1)
Requirement already satisfied: jinja2 in /home/AquaBot/venv/lib/python3.11/site-packages (from torch>=1.8.0->-r requirements.txt (line 15)) (3.1.3)
Requirement already satisfied: fsspec in /home/AquaBot/venv/lib/python3.11/site-packages (from torch>=1.8.0->-r requirements.txt (line 15)) (2024.3.1)
Requirement already satisfied: py-cpuinfo in /home/AquaBot/venv/lib/python3.11/site-packages (from ultralytics>=8.0.232->-r requirements.txt (line 18)) (9.0.0)
Requirement already satisfied: pytz>=2020.1 in /home/AquaBot/venv/lib/python3.11/site-packages (from pandas>=1.1.4->-r requirements.txt (line 27)) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /home/AquaBot/venv/lib/python3.11/site-packages (from pandas>=1.1.4->-r requirements.txt (line 27)) (2024.1)
Requirement already satisfied: smmap<6,>=3.0.1 in /home/AquaBot/venv/lib/python3.11/site-packages (from gitdb<5,>=4.0.1->gitpython>=3.1.30->-r requirements.txt (line 5)) (5.0.1)
Requirement already satisfied: six>=1.5 in /home/AquaBot/venv/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib>=3.3->-r requirements.txt (line 6)) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/AquaBot/venv/lib/python3.11/site-packages (from jinja2->torch>=1.8.0->-r requirements.txt (line 15)) (2.1.5)
Requirement already satisfied: mpmath>=0.19 in /home/AquaBot/venv/lib/python3.11/site-packages (from sympy->torch>=1.8.0->-r requirements.txt (line 15)) (1.3.0)
(venv) AquaBot@raspberrypi:~/Desktop/ObjectDetection/yolov5 $ python detect.py --weights best.pt --source 0
detect: weights=['best.pt'], source=0, data=data/coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_csv=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
YOLOv5 🚀 v7.0-295-gac6c4383 Python-3.11.2 torch-2.2.1 CPU

Traceback (most recent call last):
  File "/home/AquaBot/Desktop/ObjectDetection/yolov5/detect.py", line 312, in <module>
    main(opt)
  File "/home/AquaBot/Desktop/ObjectDetection/yolov5/detect.py", line 307, in main
    run(**vars(opt))
  File "/home/AquaBot/venv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/AquaBot/Desktop/ObjectDetection/yolov5/detect.py", line 115, in run
    model = DetectMultiBackend(weights, device=device, dnn=dnn, data=data, fp16=half)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/AquaBot/Desktop/ObjectDetection/yolov5/models/common.py", line 467, in __init__
    model = attempt_load(weights if isinstance(weights, list) else w, device=device, inplace=True, fuse=fuse)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/AquaBot/Desktop/ObjectDetection/yolov5/models/experimental.py", line 98, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location="cpu")  # load
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/AquaBot/venv/lib/python3.11/site-packages/torch/serialization.py", line 1026, in load
    return _load(opened_zipfile,
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/AquaBot/venv/lib/python3.11/site-packages/torch/serialization.py", line 1438, in _load
    result = unpickler.load()
             ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 874, in __new__
    raise NotImplementedError("cannot instantiate %r on your system"
NotImplementedError: cannot instantiate 'WindowsPath' on your system

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Jinairu hello! It looks like the issue you're encountering with `best.pt` on your Raspberry Pi is related to path handling differences between Windows and Unix-like systems (like Raspbian on your Raspberry Pi). The model file `best.pt` seems to have been saved with Windows-style paths, which are not compatible with your Raspberry Pi's file system.

A potential solution is to re-save your model weights on your Windows machine using a method that avoids embedding Windows-specific paths. Here’s how you can do it:

1. Load your model on your Windows machine:
   ```python
   model = torch.load('path/to/best.pt', map_location=torch.device('cpu'))
   ```

2. Save the model again, specifying the `pickle_module`:
   ```python
   torch.save(model, 'path/to/new_best.pt', pickle_module=dill)
   ```

Then, transfer this `new_best.pt` to your Raspberry Pi and try loading it again. This should ideally resolve the path issues caused by different operating systems.

Let me know if this helps or if you encounter any more issues! 😊
