### ISSUE TITLE
PILLOW version too high causing bugs during model training and validation-PILLOW版本过高导致模型训练验证时发生bug

### ISSUE THREAD

**Issue by Edgar-Lzxc** [ultralytics/yolov5#12851]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Other

### Bug

I used the pip command requests.txt to install the environment and installed the PILlow installation library as Pillow-10.2.0. I found the following error, which is present in both model training and validation, as well as in Python version 3.9.
我使用pip命令requirements.txt安装环境，安装PILLow安装库为Pillow-10.2.0发现以下报错，模型训练和模型验证都有此bug，python为3.9版本也是存在的。
![bug1](https://github.com/ultralytics/yolov5/assets/46618131/3d4e2706-2575-47e6-860d-294feab4a7a5)
![bug2](https://github.com/ultralytics/yolov5/assets/46618131/9635c1eb-48fc-4225-b97a-3e296275e185)

### Environment

- YOLOv5 7.0 python==3.8

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Edgar-Lzxc** [comment]
这个兼容性BUG会导致训练和验证等功能生成在run文件夹(前提是你没改参数中默认名字)中训练或验证模型时创建文件夹中的val图片无法保存不管是label还是pred的都是一样。


This compatibility bug will cause training and validation functions to be generated in the run folder (provided that you have not changed the default name in the parameters). When training or validating a model, the val image in the folder cannot be saved, whether it is a label or pre, it is the same.

**Comment by glenn-jocher** [comment]
@Edgar-Lzxc thank you for bringing this issue to our attention! 😊

This compatibility bug seems related to how the Pillow library version interacts with YOLOv5. To resolve this, you could try downgrading the Pillow library to a version that is known to be compatible with YOLOv5, such as 8.0.1. You can do this by running:

```bash
pip install Pillow==8.0.1
```

Please give this a try and let us know if it solves the issue. Your feedback is valuable to us, and it helps improve YOLOv5 for everyone!

**Comment by Edgar-Lzxc** [comment]
你应该将Pillow库版本在[requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt)中修改进行安装Pillow最大版本限制，或者定义安装Pillow版本，不然该问题会一直存在，并且在训练和验证模型时val绘制后的图片将无法生成在工作目录中！

**Comment by glenn-jocher** [comment]
@Edgar-Lzxc Thanks for the suggestion! 🌟

We'll consider adding a version cap on Pillow in the `requirements.txt` to avoid such issues in the future. For now, you can manually adjust the Pillow version by editing your `requirements.txt`:

```bash
Pillow<=8.0.1
```
or directly install a compatible version:

```bash
pip install Pillow==8.0.1
```

We appreciate your input, helping us improve the YOLOv5 experience!
