### ISSUE TITLE
Get Scalar Validation Metrics

### ISSUE THREAD

**Issue by ArtBreguez** [ultralytics/yolov5#12854]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How can I get the metrics on `val.py ` scalar (numbers) instead of the graphs?

i want something like:

```
mAP@.5: 0.976
mAP@.5:.95: 0.612
Precision: 0.841
Recall: 0.973
```

**Comment by glenn-jocher** [comment]
@ArtBreguez hello there! 😄

You can achieve this by using the `--save-json` flag with the `val.py` script. It provides a summary of the metrics in a JSON file, which you can then read to get the scalar values. Here's a quick example:

```shell
python val.py --weights your_model.pt --data your_data.yaml --save-json
```

After running this, check the output folder for a file named `results.json`. This file will contain the metrics you're interested in, in a scalar format that you can easily read or process further.

Hope this helps! Happy coding! 🚀
