### ISSUE TITLE
validation

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#1286]
## ❔Question

how to define the validation ?
1. it just show the validation result (mAP) when training. 
like this
   Epoch   gpu_mem       box       obj       cls     total   targets  img_size
    50/299     6.83G    0.0347   0.03975         0   0.07444        36       640: 100%|████████████████████████████| 207/207 [04:58<00:00,  1.47s/it]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|████████████████| 207/207 [04:16<00:00,  1.16s/it]
                 all    8.28e+03    5.46e+04       0.674       0.957       0.947       0.645

     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
    51/299     6.83G   0.03481   0.04082         0   0.07564       103       640: 100%|████████████████████████████| 207/207 [05:01<00:00,  1.49s/it]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|████████████████| 207/207 [04:18<00:00,  1.18s/it]
                 all    8.28e+03    5.46e+04       0.675       0.958       0.948       0.645

2. 
the validation data will decide the best.weight and
if the validation result of the current epoch is bad than the validation result of last epoch, the network will choice the last weight to train it.

**Comment by glenn-jocher** [comment]
@alicera best.pt saves your best checkpoint (metric is validation mAP). last.pt saves last epoch's checkpoint.

**Comment by alicera** [comment]
So I can use the train set as validation set ?

**Comment by glenn-jocher** [comment]
@alicera your train and validation sets are completely up to you.

**Comment by alicera** [comment]
if I set the train set for coco to train and set the valid set for coco to valid.
It will be the same result that set the train set for coco to train and set the train set for coco to valid?

**Comment by glenn-jocher** [comment]
@alicera I don't understand your question. You might want to show code.

**Comment by alicera** [comment]
coco2017 dataset contain train2017(118287 images) and val2017 (5000 images)
case1 : I set the train2017 as train set and set the val2017 as validation
case2: I set the train2017 as train set and set the train2017 as validation

the case1 result and the case2 reuslt are the same AP for last.pt?
but case1 result and the case2 reuslt are the different AP for best.pt?

**Comment by glenn-jocher** [comment]
@alicera use case 1

**Comment by alicera** [comment]
use case 1？?

I just want to know the question
the case1 result and the case2 reuslt are the same AP for last.pt?
 case1 result and the case2 reuslt are the different AP for best.pt?

**Comment by glenn-jocher** [comment]
@alicera when training you require separate train and val sets. See https://en.wikipedia.org/wiki/Training,_validation,_and_test_sets
