### ISSUE TITLE
Classification Model Exported to TFLITE

### ISSUE THREAD

**Issue by Halafz7** [ultralytics/yolov5#12876]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

So I did a Classification Model training with YOLOv5 (Nano, Medium, Small) using CIFAR100 dataset and wanted to export it to another format such as TFLITE that support FP16 and INT8. But, when I try to export, it shows error

`python export.py --weights "D:\Skripsi\yolov5-master\yolov5-master\experiments\Nano-300-epochs\weights\best.pt" --include tflite --int8
D:\Conda\envs\yolo\Lib\site-packages\onnxruntime\capi\onnxruntime_validation.py:26: UserWarning: Unsupported Windows version (11). ONNX Runtime supports Windows 10 and above, only.
  warnings.warn(
export: data=D:\Skripsi\yolov5-master\yolov5-master\data\coco128.yaml, weights=['D:\\Skripsi\\yolov5-master\\yolov5-master\\experiments\\Nano-300-epochs\\weights\\best.pt'], imgsz=[640, 640], batch_size=1, device=cpu, half=False, inplace=False, keras=False, optimize=False, int8=True, per_tensor=False, dynamic=False, simplify=False, opset=17, verbose=False, workspace=4, nms=False, agnostic_nms=False, topk_per_class=100, topk_all=100, iou_thres=0.45, conf_thres=0.25, include=['tflite']
YOLOv5  2024-3-24 Python-3.12.2 torch-2.2.1 CPU

Fusing layers...
Model summary: 117 layers, 1336564 parameters, 0 gradients, 3.0 GFLOPs

PyTorch: starting from D:\Skripsi\yolov5-master\yolov5-master\experiments\Nano-300-epochs\weights\best.pt with output shape (1, 100) (2.7 MB)
Traceback (most recent call last):
  File "D:\Skripsi\yolov5-master\yolov5-master\export.py", line 936, in <module>
    main(opt)
  File "D:\Skripsi\yolov5-master\yolov5-master\export.py", line 931, in main
    run(**vars(opt))
  File "D:\Conda\envs\yolo\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Skripsi\yolov5-master\yolov5-master\export.py", line 839, in run
    assert not isinstance(model, ClassificationModel), "ClassificationModel export to TF formats not yet supported."
AssertionError: ClassificationModel export to TF formats not yet supported.`

Are you guys planning on add export feature to TFLITE for Classification Model? Thanks

**Comment by glenn-jocher** [comment]
@Halafz7 hello! 😊

Thank you for reaching out. It appears from your error log that you've encountered a limitation in the current export capabilities of the YOLOv5 repository, particularly when trying to export a Classification Model to TensorFlow Lite formats.

As of now, the export of Classification Models to TF formats (including TFLITE) isn't supported. This includes both FP16 and INT8 quantizations. Our team is constantly working on improving and extending the functionality of YOLOv5, and we appreciate the community's input on features they'd like to see.

We understand how important it is for our users to have a wide range of export options and will consider adding this feature in future updates. Keep an eye on our GitHub updates and release notes for new features and improvements.

For the meantime, for any more detailed queries or suggestions, feel free to open a discussion in the YOLOv5 GitHub Discussions section. The community and team are there to brainstorm and support.

Thank you for your understanding and support! 🚀

**Comment by Halafz7** [comment]
Hi Glenn, just asking, is export of Classification Models to TF formats (including TFLITE) supported for version after YOLOv5 (e.g.YOLOv8)?

**Comment by glenn-jocher** [comment]
Hello! 😊

As of the current updates, the YOLO architecture, including versions up to YOLOv5, doesn't inherently support exporting Classification Models directly to TensorFlow formats (TFLITE included), due to the focus on object detection.

Future versions, like a potential YOLOv8, are subject to enhancements based on feedback and evolving capabilities. We recommend keeping an eye on the GitHub repository for any future updates on export capabilities and supporting documentation.

Thank you for your curiosity and support of the YOLO series! 🚀
