### ISSUE TITLE
License and a few questions

### ISSUE THREAD

**Issue by Developer-Moon** [ultralytics/yolov5#12871]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I intend to use the code on this website (https://github.com/LongxingTan/tfyolo - YOLOv5 tensorflow) commercially.

1. What licensing policy should I follow to use this? (Because you are the original author of YOLOv5)
    ex) AGPL-3.0 License? Enterprise License? or LongxingTan (https://github.com/LongxingTan/tfyolo)?

2. If the first question concerns you.
    - 2.1 Do I have to disclose the code when using it commercially?
    - 2.2 I am trying to do TCP communication with YOLO v5. If I have to disclose my code, do I also have to disclose my TCP code?
    - 2.3 Is it okay if I obfuscate your code and make it public?

**Comment by glenn-jocher** [comment]
@Developer-Moon hello! Thanks for reaching out and for your interest in YOLOv5. I'll directly address your inquiries:

1. For commercial use of YOLOv5, regardless of the implementation (including the TensorFlow version at the mentioned repository), you need to adhere to the AGPL-3.0 license stipulations associated with our work, unless you obtain an Ultralytics Enterprise License. The licensing of any derivative work, like the one you mentioned, does not exempt you from this requirement.

    2.1 If you're using Ultralytics models, architectures, or code under the AGPL-3.0 license for commercial purposes, you are indeed required to fully open source your entire project under the same AGPL-3.0 license. There are no exceptions to this rule.
    
    2.2 In line with the AGPL-3.0 requirements, if your project incorporates our code and you choose to open source it under AGPL-3.0, you must disclose all related code, including any TCP communication code that directly interacts with or is part of the project using YOLOv5.
    
    2.3 Obfuscating the code does not exempt you from the obligations under AGPL-3.0. If you choose to distribute or use the project commercially under AGPL-3.0, the code must be made available in a form that is accessible and modifiable by others.

If your use case requires keeping your project closed-source, I strongly encourage you to consider obtaining an Ultralytics Enterprise License. This would allow commercial use without the need to open source your project. 

For more detailed information on licensing and potential next steps, please refer to our documentation at https://docs.ultralytics.com/yolov5/.

We're here to support you, so if you have any more questions or need further clarification, don't hesitate to ask. Best wishes on your project! 🚀

**Comment by Developer-Moon** [comment]
Thank you very much for your kind reply

I want to know one thing clearly

I understand that communication with the AGPL program through Pipe, Socket, IPC, and Command Line Arguments as a separate program from the AGPL program is not considered a derivative work of the GPL


**our current state**

   Project 1 : Yolo v5 + Client
   Project 2 : Server

The two projects are independent and have socket communication with each other

In the case above, should I also disclose the second project, Server Code?

**Comment by glenn-jocher** [comment]
Hey @Developer-Moon, glad you found the previous response helpful! 😊

Concerning your setup with Project 1 and Project 2 communicating over sockets:
- If Project 1 utilizes YOLOv5 and is under AGPL-3.0, and Project 2 (Server) operates independently without including or directly interacting with the YOLOv5 codebase, then Project 2 wouldn't inherently be considered a derivative work requiring disclosure under AGPL-3.0.

However, it's crucial to ensure that the separation between the two projects is clear and that Project 2 does not use or incorporate AGPL-3.0 licensed code indirectly. If in doubt or your use case is complex, consulting with a legal expert on open-source licensing is always a good step.

Hope this clarifies your query! If you have any more questions, feel free to ask. Best of luck with your projects! 🚀
