### ISSUE TITLE
YOLOv5 multi camera real-time recognition based on IP address

### ISSUE THREAD

**Issue by fsamekl** [ultralytics/yolov5#12873]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to recognize multiple video streams in the detect.py file in the yolov5 master version, or is there a tutorial on recognizing multiple video streams? For example, I have two RTSP addresses: rtsp://admin:admin @192.168.43.210.8554/live, rtsp://admin:admin @192.168.43.16:8554/live, how can I make it possible for both of them to recognize in real-time simultaneously? Please answer. Thank you

**Comment by fsamekl** [comment]
I created a streams.txt file and wrote two rtsp files inside it
Address: rtsp://admin:admin @192.168.43.210.8554/live,
rtsp://admin:admin @192.168.43.16:8554/live,
Parser. add argument ('-- source', type=str, default='streams. txt ', help='file/dir/URL/global/screen/0 (webcam)')
Error in detect.py file
<img width="690" alt="{F15A49D6-B4DD-4c2e-B4DF-A3BE9DCA476E}" src="https://github.com/ultralytics/yolov5/assets/136400249/5fb74a1f-153c-4b4a-a7e6-e78640bafd79">

I have repeatedly checked the format of rtsp in the file and found no errors. Why is this error reported

**Comment by glenn-jocher** [comment]
Hi there! It sounds like you're on the right track with using a `streams.txt` file for multi-stream detection. The error could be stemming from how `detect.py` is parsing the input from your file. Here are a few things to check:

1. **Format of `streams.txt`**: Ensure each stream URL is on a new line without any trailing commas. Like so:
   ```
   rtsp://admin:admin @fsamekl.168.43.210:8554/live
   rtsp://admin:admin@192.168.43.16:8554/live
   ```
   Note: Be mindful of spaces and special characters in URLs.

2. **Command Line Argument**: Verify your command line is correctly pointing to `streams.txt`:
   ```shell
   python detect.py --source streams.txt
   ```

3. **Code Check**: Inside `detect.py`, ensure the code that reads `streams.txt` properly splits the input URLs. If you had to customize this part, it should roughly do:
   ```python
   with open(source, 'r') as f:
       sources = [x.strip() for x in f.readlines()]
   ```
   This is a simplified example. The actual implementation might differ but ensures each line from `streams.txt` is treated as a separate source.

4. **Log Checking**: The error screenshot wasn't visible here, but double-checking the full error message in your logs often provides hints toward the issue. Look for any lines specifically mentioning failure in reading the source or parsing the URLs.

If after these checks the issue persists, consider providing more detailed logs or error messages (unfortunately, I can't see the attached image). This will help in narrowing down the potential problem areas further. Good luck, and I'm here if you have more questions! 🚀

**Comment by fsamekl** [comment]
@glenn-jocher  After changing "streams. txt" to "rtsp. streams", the program can continue to run. I don't understand what caused it

**Comment by glenn-jocher** [comment]
@fsamekl hi! Great to hear your program is running! The issue likely relates to how the program parses file extensions or special characters in file names. By changing "streams.txt" to "rtsp.streams", you might have bypassed a parsing issue or a restriction related to .txt files. It's hard to pinpoint without seeing the exact code, but what matters is it's working now. Keep experimenting and happy coding! 🎉
