### ISSUE TITLE
YOLOv5 PyTorch Quantization 

### ISSUE THREAD

**Issue by bingiflash** [ultralytics/yolov5#1288]
I'm wondering if the model can be quantized using pytorch post training static quantization and can run inference at int8 precision?

Thanks in advance

**Comment by glenn-jocher** [comment]
@bingiflash not sure, try it out.

**Comment by niaoyu** [comment]
As mentioned in the document, It only supports cpu mode. 
https://pytorch.org/tutorials/advanced/static_quantization_tutorial.html
So maybe OK in future torch version

**Comment by bingiflash** [comment]
Thanks for your reply. I was already following that tutorial, but I encountered a problem. I was trying to add Quant and DequantStubs to Model class in yolo.py. 
`self.quant_stub = torch.quantization.QuantStub()`
`self.dequnat_stub = torch.quantization.DeQuantStub()`
When i use them in forward function, I'm getting this error.
`torch.nn.modules.module.ModuleAttributeError: 'Model' object has no attribute 'quant_stub'`

I'm wondering this is because i added a new variable to init function, and it is unable to find it. I don't know. Can you help me?

**Comment by bingiflash** [comment]
Also I have one more doubt. 
` qff = torch.nn.quantized.FloatFunctional()`
`y[..., 2:4] = qff.mul(qff.mul(qff.mul(y[..., 2:4], y[..., 2:4]), 4),self.anchor_grid[i])`

is this the correct way of converting this line in yolo.py? My values are not correlating for wh.

`y[..., 2:4] = (y[..., 2:4] * 2) ** 2 * self.anchor_grid[i]  # wh`

**Comment by hebangwen** [comment]
> Also I have one more doubt.
> ` qff = torch.nn.quantized.FloatFunctional()`
> `y[..., 2:4] = qff.mul(qff.mul(qff.mul(y[..., 2:4], y[..., 2:4]), 4),self.anchor_grid[i])`
> 
> is this the correct way of converting this line in yolo.py? My values are not correlating for wh.
> 
> `y[..., 2:4] = (y[..., 2:4] * 2) ** 2 * self.anchor_grid[i] # wh`

Hi, bingiflash. I'm trying to quantize yolov5 model recently. I changed the quantization line to :

``` python
def quantize_tensor(t: torch.Tensor, scale=255, zero_point=8, dtype=torch.quint8):
    return torch.quantize_per_tensor(t, (t.max() - t.min()) / scale, zero_point, dtype)

quant_op = torch.nn.quantized.QFuncitonal()

y[..., 0:2] = quant_op.mul(
    quantize_tensor(self.stride[i]),
    quant_op.add(
        quantize_tensor(self.grid[i]),
        quant_op.add(
            quant_op.mul(
                y[..., 0:2],
                quantize_tensor(torch.tensor(2.0))
            ),
            quantize_tensor(torch.ones(size=y[..., 0:2].shape) * -0.5)
        )
    )
)
```

I found it very ugly. And it can't run also. I wonder whether you have finished transforming this line to quantized mode. Any reply and suggestions will be appreciated.

**Comment by bingiflash** [comment]
Hi, @BangwenHe. Yes and no. After days of researching and trial and error, what I understood is, last part of Detect layer in the yolov5 model cannot be converted to int 8 to process quantized tensors. So what I did is, return all the variables that were needed for the calculation and did the calculation after converting them back to Non-quantized tensors. For example, here's how my Quant model definition and forward function.

```
class QuantModel(torch.nn.Module):
    def __init__(self, cfg='models\\yolov5s.yaml', weights='yolov5s.pt'):
        super(QuantModel, self).__init__()

        self.quant = torch.quantization.QuantStub()
        self.yolo_model = Model(cfg=cfg).float()
        self.yolo_model.load_state_dict(torch.load(weights)['model'].state_dict())
        self.yolo_model.names = torch.load(weights)['model'].names
        self.dequant = torch.quantization.DeQuantStub()

    def forward(self, x):

        x = self.quant(x)
        # returns [[x1,x2,x3], self.nl, ny_l, nx_l, self.grid, self.stride, self.anchor_grid, bs_l, self.no]
        [x1, x2, x3], nl, ny_l, nx_l, grid, stride, anchor_grid, bs_l, no = self.yolo_model(x)
        x1,x2,x3 = self.dequant(x1), self.dequant(x2), self.dequant(x3)
        return [[x1, x2, x3], nl, ny_l, nx_l, grid, stride, anchor_grid, bs_l, no]

```

And while doing forward pass, I would go through all the layers in the quantized version except the detect layer, where I return the above-mentioned variables. And process the detect layer in float version.

```
# Inference
        t1 = time_synchronized()
        pred = model(img)
        if opt.quantized:
            ## Processing rest of detect layer
            x, nl, ny_l, nx_l, grid, stride, anchor_grid, bs_l, no = pred
            z = [] ## network output | nms input
            for i in range(nl):
                if grid[i].shape[2:4] != x[i].shape[2:4]:
                    yv, xv = torch.meshgrid([torch.arange(ny_l[i]), torch.arange(nx_l[i])])
                    grid[i] = torch.stack((xv, yv), 2).view((1, 1, ny_l[i], nx_l[i], 2)).float().to(x[i].device)

                y = x[i].sigmoid()
                y[..., 0:2] = (y[..., 0:2] * 2. - 0.5 + grid[i].to(x[i].device)) * stride[i]  # xy
                y[..., 2:4] = (y[..., 2:4] * 2) ** 2 * anchor_grid[i]  # wh
                z.append(y.view(bs_l[i], -1, no))

            pred_processed = torch.cat(z,1)
        else:
            pred_processed = pred[0]
        # Apply NMS
        pred = non_max_suppression(pred_processed, opt.conf_thres, opt.iou_thres, classes=opt.classes, agnostic=opt.agnostic_nms)
        t2 = time_synchronized()
```

I had to do this because of time constraints and exhaustion. Also, this is like 9 months back. Maybe things have changed. Yolov5 and PyTorch got newer versions. I'm not working on this anymore. So I didn't check if there's a better way of doing this.
Hope this helps. Best of luck.

**Comment by hebangwen** [comment]
Thanks for your rapid reply @bingiflash. I reproduce it following your suggestion. But I found that the AP value seems to be pretty low (<1%). Here are my code snippet.

```python
def forward_once(self):
        y, dt = [], []  # outputs
        
        for m in self.model:
            if m.f != -1:  # if not from previous layer
                x = y[m.f] if isinstance(m.f, int) else [x if j == -1 else y[j] for j in m.f]  # from earlier layers
        
            if self.quantization == 'static' and type(m) == Detect:
                x1, x2, x3 = x
                x1 = torch.dequantize(x1)
                x2 = torch.dequantize(x2)
                x3 = torch.dequantize(x3)
                x = [x1, x2, x3]
        
            x = m(x)  # run
            y.append(x if m.i in self.save else None)  # save output
        
        return x
```
Hope you can tell me your approximate AP result not very precise. Anyway, thanks.

**Comment by baiyueguang994** [comment]
> Hi, @BangwenHe. Yes and no. After days of researching and trial and error, what I understood is, last part of Detect layer in the yolov5 model cannot be converted to int 8 to process quantized tensors. So what I did is, return all the variables that were needed for the calculation and did the calculation after converting them back to Non-quantized tensors. For example, here's how my Quant model definition and forward function.
> 
> ```
> class QuantModel(torch.nn.Module):
>     def __init__(self, cfg='models\\yolov5s.yaml', weights='yolov5s.pt'):
>         super(QuantModel, self).__init__()
> 
>         self.quant = torch.quantization.QuantStub()
>         self.yolo_model = Model(cfg=cfg).float()
>         self.yolo_model.load_state_dict(torch.load(weights)['model'].state_dict())
>         self.yolo_model.names = torch.load(weights)['model'].names
>         self.dequant = torch.quantization.DeQuantStub()
> 
>     def forward(self, x):
> 
>         x = self.quant(x)
>         # returns [[x1,x2,x3], self.nl, ny_l, nx_l, self.grid, self.stride, self.anchor_grid, bs_l, self.no]
>         [x1, x2, x3], nl, ny_l, nx_l, grid, stride, anchor_grid, bs_l, no = self.yolo_model(x)
>         x1,x2,x3 = self.dequant(x1), self.dequant(x2), self.dequant(x3)
>         return [[x1, x2, x3], nl, ny_l, nx_l, grid, stride, anchor_grid, bs_l, no]
> ```
> 
> And while doing forward pass, I would go through all the layers in the quantized version except the detect layer, where I return the above-mentioned variables. And process the detect layer in float version.
> 
> ```
> # Inference
>         t1 = time_synchronized()
>         pred = model(img)
>         if opt.quantized:
>             ## Processing rest of detect layer
>             x, nl, ny_l, nx_l, grid, stride, anchor_grid, bs_l, no = pred
>             z = [] ## network output | nms input
>             for i in range(nl):
>                 if grid[i].shape[2:4] != x[i].shape[2:4]:
>                     yv, xv = torch.meshgrid([torch.arange(ny_l[i]), torch.arange(nx_l[i])])
>                     grid[i] = torch.stack((xv, yv), 2).view((1, 1, ny_l[i], nx_l[i], 2)).float().to(x[i].device)
> 
>                 y = x[i].sigmoid()
>                 y[..., 0:2] = (y[..., 0:2] * 2. - 0.5 + grid[i].to(x[i].device)) * stride[i]  # xy
>                 y[..., 2:4] = (y[..., 2:4] * 2) ** 2 * anchor_grid[i]  # wh
>                 z.append(y.view(bs_l[i], -1, no))
> 
>             pred_processed = torch.cat(z,1)
>         else:
>             pred_processed = pred[0]
>         # Apply NMS
>         pred = non_max_suppression(pred_processed, opt.conf_thres, opt.iou_thres, classes=opt.classes, agnostic=opt.agnostic_nms)
>         t2 = time_synchronized()
> ```
> 
> I had to do this because of time constraints and exhaustion. Also, this is like 9 months back. Maybe things have changed. Yolov5 and PyTorch got newer versions. I'm not working on this anymore. So I didn't check if there's a better way of doing this. Hope this helps. Best of luck.

Hello, could you please send your complete quantization code of YoloV5

**Comment by hebangwen** [comment]
@baiyueguang994 , I remember that I didn't hack so much for quantization. Below are my quantization code:

``` python
def quantize_static(model, dataloader, quantization):
    if quantization == 'static':
        # ignore `Detect`
        temp = model.model[:-1]
    else:
        temp = model
    temp.qconfig = torch.quantization.get_default_qconfig('fbgemm')
    temp = torch.quantization.prepare(temp)
    temp = torch.quantization.convert(temp)

    if quantization == 'static':
        model.model = torch.nn.Sequential(*temp, model.model[-1])
    else:
        model = temp

    return model
```

I did it in Augest when yolov5 version was v5.0 and now it has been upgraded to v6.0. You can try tensorflow quantization, since yolov5 also released tensorflow version in v6.0.

**Comment by baiyueguang994** [comment]
> > Also I have one more doubt.
> > ` qff = torch.nn.quantized.FloatFunctional()`
> > `y[..., 2:4] = qff.mul(qff.mul(qff.mul(y[..., 2:4], y[..., 2:4]), 4),self.anchor_grid[i])`
> > is this the correct way of converting this line in yolo.py? My values are not correlating for wh.
> > `y[..., 2:4] = (y[..., 2:4] * 2) ** 2 * self.anchor_grid[i] # wh`
> 
> Hi, bingiflash. I'm trying to quantize yolov5 model recently. I changed the quantization line to :
> 
> ```python
> def quantize_tensor(t: torch.Tensor, scale=255, zero_point=8, dtype=torch.quint8):
>     return torch.quantize_per_tensor(t, (t.max() - t.min()) / scale, zero_point, dtype)
> 
> quant_op = torch.nn.quantized.QFuncitonal()
> 
> y[..., 0:2] = quant_op.mul(
>     quantize_tensor(self.stride[i]),
>     quant_op.add(
>         quantize_tensor(self.grid[i]),
>         quant_op.add(
>             quant_op.mul(
>                 y[..., 0:2],
>                 quantize_tensor(torch.tensor(2.0))
>             ),
>             quantize_tensor(torch.ones(size=y[..., 0:2].shape) * -0.5)
>         )
>     )
> )
> ```
> 
> I found it very ugly. And it can't run also. I wonder whether you have finished transforming this line to quantized mode. Any reply and suggestions will be appreciated.



> @baiyueguang994 , I remember that I didn't hack so much for quantization. Below are my quantization code:
> 
> ```python
> def quantize_static(model, dataloader, quantization):
>     if quantization == 'static':
>         # ignore `Detect`
>         temp = model.model[:-1]
>     else:
>         temp = model
>     temp.qconfig = torch.quantization.get_default_qconfig('fbgemm')
>     temp = torch.quantization.prepare(temp)
>     temp = torch.quantization.convert(temp)
> 
>     if quantization == 'static':
>         model.model = torch.nn.Sequential(*temp, model.model[-1])
>     else:
>         model = temp
> 
>     return model
> ```
> 
> I did it in Augest when yolov5 version was v5.0 and now it has been upgraded to v6.0. You can try tensorflow quantization, since yolov5 also released tensorflow version in v6.0.

Thank you. Is that the code for loading a floating point model for quantization? Why don't you iterate through the data to get the zero_point and scale of the activated value?

**Comment by baiyueguang994** [comment]
> @baiyueguang994 , I remember that I didn't hack so much for quantization. Below are my quantization code:
> 
> ```python
> def quantize_static(model, dataloader, quantization):
>     if quantization == 'static':
>         # ignore `Detect`
>         temp = model.model[:-1]
>     else:
>         temp = model
>     temp.qconfig = torch.quantization.get_default_qconfig('fbgemm')
>     temp = torch.quantization.prepare(temp)
>     temp = torch.quantization.convert(temp)
> 
>     if quantization == 'static':
>         model.model = torch.nn.Sequential(*temp, model.model[-1])
>     else:
>         model = temp
> 
>     return model
> ```
> 
> I did it in Augest when yolov5 version was v5.0 and now it has been upgraded to v6.0. You can try tensorflow quantization, since yolov5 also released tensorflow version in v6.0.

Hello, could you please send the code for inference the quantized model？
I am inferring the following error：
NotImplementedError : Could not run ' quantizd : : conv2d.new' with arguments from the 'CPU' backend .

**Comment by dineshamara1** [comment]
@baiyueguang994 @BangwenHe Has Anyone successfully quantised the yolov5 model? If so can you please kindly help me with the code and instructions

**Comment by glenn-jocher** [comment]
@dineshamara1 this is an interesting conversation. I haven't experimented with `torch.quantization` myself. You can run GPU inference at half precision with just `detect.py --half` though on GPU. 

YOLOv5 training already employs automatic mixed precision (AMP).

CPU pytorch inference will only work at 32 bits.

Quantization capabilities vary by backend also. CoreML for example offers arbitrary quantization down, i.e. 8 bits, 4 bits, 2 bits etc. iDetection models are 8-bit quantized.

TFLite models can be exported as INT8 with `export.py --int8`.

**Comment by sherlockholmes1603** [comment]
> @baiyueguang994 @BangwenHe Has Anyone successfully quantised the yolov5 model? If so can you please kindly help me with the code and instructions

did you got the code and instruction for successfully quantizing the yolov5 model?
I actually want the quantized weights in .onnx format or .pt format

**Comment by m-guise** [comment]
Hi,
Does anyone got success in Quantization Aware Training of Yolov5?

**Comment by m-guise** [comment]
Hi @glenn-jocher 
Is there any method to train Yolov5 using Quantization Aware Training? I am wondering whether it will provide the same accuracy after QAT, as it provides on ResNet, MobileNet etc. ([link](https://pytorch.org/docs/master/quantization.html#quantization-aware-training))

**Comment by glenn-jocher** [comment]
@m-guise not officially, no. I haven't experimented with `torch.quantization` myself. You can run GPU inference at half precision with just `detect.py --half` though on GPU. 

YOLOv5 training already employs automatic mixed precision (AMP).

CPU pytorch inference will only work at 32 bits.

Quantization capabilities vary by backend also. CoreML for example offers arbitrary quantization down, i.e. 8 bits, 4 bits, 2 bits etc. iDetection models are 8-bit quantized and you can see their performance on the iOS app store.

TFLite models can be exported as INT8 with `export.py --int8`.

**Comment by GiuseppeMind** [comment]
> @baiyueguang994 , I remember that I didn't hack so much for quantization. Below are my quantization code:
> 
> ```python
> def quantize_static(model, dataloader, quantization):
>     if quantization == 'static':
>         # ignore `Detect`
>         temp = model.model[:-1]
>     else:
>         temp = model
>     temp.qconfig = torch.quantization.get_default_qconfig('fbgemm')
>     temp = torch.quantization.prepare(temp)
>     temp = torch.quantization.convert(temp)
> 
>     if quantization == 'static':
>         model.model = torch.nn.Sequential(*temp, model.model[-1])
>     else:
>         model = temp
> 
>     return model
> ```
> 
> I did it in Augest when yolov5 version was v5.0 and now it has been upgraded to v6.0. You can try tensorflow quantization, since yolov5 also released tensorflow version in v6.0.

hello!
what is model in your case? how did you load it? with the class Model in yolo.py or the class DetectMultiBackend in common.py?

**Comment by arielsolomon** [comment]
I was able to quantize the model at static mode via tflight or Nvidia's tensorrt.
The problem comes at inference step, using the quantized model at the form of onnx. While the model before quantization can be used for inference, the quantized model raise error:
“File "/opt/conda/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 192, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: serving_default_images:0 for the following indices
 index: 0 Got: 1 Expected: 10
 Please fix either the inputs or the model.”

**Comment by melika-sce** [comment]
Hi, have anyone successfully quantized yolov5?

**Comment by glenn-jocher** [comment]
@melika-sce hello,

We are glad to hear that you are interested in quantizing YOLOv5. However, as of now, there is no official implementation or specific instructions for quantizing YOLOv5 available in the official repository. 

Quantization is a complex process, and it might require custom modifications to the codebase to ensure proper functionality. If you are exploring quantization, we recommend referring to the PyTorch documentation on quantization-aware training and the `torch.quantization` module.

Moreover, it's worth mentioning that different backends and frameworks might have different capabilities when it comes to quantization. You can try utilizing frameworks like TensorFlow to perform quantization if it aligns with your requirements.

If you have any further questions or need assistance, please feel free to ask. 

Best regards.
