### ISSUE TITLE
mAP@0.5 of YOLOv5n on COCO val

### ISSUE THREAD

**Issue by YairSmadar** [ultralytics/yolov5#12882]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Can you provide mAP@0.5 of YOLOv5n on COCO val? (For detection)
Thanks

**Comment by glenn-jocher** [comment]
Hello!

Absolutely, the mAP @YairSmadar.5 for YOLOv5n on the COCO validation dataset for detection tasks is approximately 64.1%. Thanks for reaching out, and should you have more questions, feel free to ask! 😊
