### ISSUE TITLE
Weights & Biases with YOLOv5 🌟

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/yolov5#1289]
📚 This guide explains how to use **Weights & Biases** (W&B) with YOLOv5 🚀. UPDATED 25 September 2022.
* [About Weights & Biases](#about-weights-&-biases)
* [First-Time Setup](#first-time-setup)
* [Viewing runs](#viewing-runs)
* [Disabling wandb](#disabling-wandb)
* [Advanced Usage: Dataset Versioning and Evaluation](#advanced-usage)
* [Reports: Share your work with the world!](#reports)

## About Weights & Biases
Think of [W&B](https://wandb.ai/site?utm_campaign=repo_yolo_wandbtutorial) like GitHub for machine learning models. With a few lines of code, save everything you need to debug, compare and reproduce your models — architecture, hyperparameters, git commits, model weights, GPU usage, and even datasets and predictions.

Used by top researchers including teams at OpenAI, Lyft, Github, and MILA, W&B is part of the new standard of best practices for machine learning. How W&B can help you optimize your machine learning workflows:

 * [Debug](https://wandb.ai/wandb/getting-started/reports/Visualize-Debug-Machine-Learning-Models--VmlldzoyNzY5MDk#Free-2) model performance in real time
 * [GPU usage](https://wandb.ai/wandb/getting-started/reports/Visualize-Debug-Machine-Learning-Models--VmlldzoyNzY5MDk#System-4) visualized automatically
 * [Custom charts](https://wandb.ai/wandb/customizable-charts/reports/Powerful-Custom-Charts-To-Debug-Model-Peformance--VmlldzoyNzY4ODI) for powerful, extensible visualization
 * [Share insights](https://wandb.ai/wandb/getting-started/reports/Visualize-Debug-Machine-Learning-Models--VmlldzoyNzY5MDk#Share-8) interactively with collaborators
 * [Optimize hyperparameters](https://docs.wandb.com/sweeps) efficiently
 * [Track](https://docs.wandb.com/artifacts) datasets, pipelines, and production models

## First-Time Setup
<details open>
 <summary> Toggle Details </summary>
When you first train, W&B will prompt you to create a new account and will generate an **API key** for you. If you are an existing user you can retrieve your key from https://wandb.ai/authorize. This key is used to tell W&B where to log your data. You only need to supply your key once, and then it is remembered on the same device.

W&B will create a cloud **project** (default is 'YOLOv5') for your training runs, and each new training run will be provided a unique run **name** within that project as project/name. You can also manually set your project and run name as:

 ```shell
 $ python train.py --project ... --name ...
 ```

YOLOv5 notebook example: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
<img width="960" alt="Screen Shot 2021-09-29 at 10 23 13 PM" src="https://user-images.githubusercontent.com/26833433/135392431-1ab7920a-c49d-450a-b0b0-0c86ec86100e.png">

 </details>

## Viewing Runs
<details open>
  <summary> Toggle Details </summary>
Run information streams from your environment to the W&B cloud console as you train. This allows you to monitor and even cancel runs in <b>realtime</b> . All important information is logged:

 * Training & Validation losses
 * Metrics: Precision, Recall, mAP@0.5, mAP@0.5:0.95
 * Learning Rate over time
 * A bounding box debugging panel, showing the training progress over time
 * GPU: Type, **GPU Utilization**, power, temperature, **CUDA memory usage**
 * System: Disk I/0, CPU utilization, RAM memory usage
 * Your trained model as W&B Artifact
 * Environment: OS and Python types, Git repository and state, **training command**

<p align="center"><img width="900" alt="Weights & Biases dashboard" src="https://user-images.githubusercontent.com/26833433/135390767-c28b050f-8455-4004-adb0-3b730386e2b2.png"></p>
</details>

 ## Disabling wandb
* training after running `wandb disabled` inside that directory creates no wandb run
![Screenshot (84)](https://user-images.githubusercontent.com/15766192/143441777-c780bdd7-7cb4-4404-9559-b4316030a985.png)

* To enable wandb again, run `wandb online`
![Screenshot (85)](https://user-images.githubusercontent.com/15766192/143441866-7191b2cb-22f0-4e0f-ae64-2dc47dc13078.png)

## Advanced Usage
You can leverage W&B artifacts and Tables integration to easily visualize and manage your datasets, models and training evaluations. Here are some quick examples to get you started.
<details open>
 <h3> 1: Train and Log Evaluation simultaneousy </h3>
   This is an extension of the previous section, but it'll also training after uploading the dataset. <b> This also evaluation Table</b>
   Evaluation table compares your predictions and ground truths across the validation set for each epoch. It uses the references to the already uploaded datasets,
   so no images will be uploaded from your system more than once.
 <details open>
  <summary> <b>Usage</b> </summary>
   <b>Code</b> <code> $ python train.py --upload_data val</code>

![Screenshot from 2021-11-21 17-40-06](https://user-images.githubusercontent.com/15766192/142761183-c1696d8c-3f38-45ab-991a-bb0dfd98ae7d.png)
 </details>

 <h3>2. Visualize and Version Datasets</h3>
 Log, visualize, dynamically query, and understand your data with <a href='https://docs.wandb.ai/guides/data-vis/tables'>W&B Tables</a>. You can use the following command to log your dataset as a W&B Table. This will generate a <code>{dataset}_wandb.yaml</code> file which can be used to train from dataset artifact.
 <details>
  <summary> <b>Usage</b> </summary>
   <b>Code</b> <code> $ python utils/logger/wandb/log_dataset.py --project ... --name ... --data .. </code>

 ![Screenshot (64)](https://user-images.githubusercontent.com/15766192/128486078-d8433890-98a3-4d12-8986-b6c0e3fc64b9.png)
 </details>

 <h3> 3: Train using dataset artifact </h3>
   When you upload a dataset as described in the first section, you get a new config file with an added `_wandb` to its name. This file contains the information that
   can be used to train a model directly from the dataset artifact. <b> This also logs evaluation </b>
 <details>
  <summary> <b>Usage</b> </summary>
   <b>Code</b> <code> $ python train.py --data {data}_wandb.yaml </code>

![Screenshot (72)](https://user-images.githubusercontent.com/15766192/128979739-4cf63aeb-a76f-483f-8861-1c0100b938a5.png)
 </details>

   <h3> 4: Save model checkpoints as artifacts </h3>
  To enable saving and versioning checkpoints of your experiment, pass `--save_period n` with the base cammand, where `n` represents checkpoint interval.
  You can also log both the dataset and model checkpoints simultaneously. If not passed, only the final model will be logged

 <details>
  <summary> <b>Usage</b> </summary>
   <b>Code</b> <code> $ python train.py --save_period 1 </code>

![Screenshot (68)](https://user-images.githubusercontent.com/15766192/128726138-ec6c1f60-639d-437d-b4ee-3acd9de47ef3.png)
 </details>

</details>

 <h3> 5: Resume runs from checkpoint artifacts. </h3>
Any run can be resumed using artifacts if the <code>--resume</code> argument starts with <code>wandb-artifact://</code> prefix followed by the run path, i.e, <code>wandb-artifact://username/project/runid </code>. This doesn't require the model checkpoint to be present on the local system.

 <details>
  <summary> <b>Usage</b> </summary>
   <b>Code</b> <code> $ python train.py --resume wandb-artifact://{run_path} </code>

![Screenshot (70)](https://user-images.githubusercontent.com/15766192/128728988-4e84b355-6c87-41ae-a591-14aecf45343e.png)
 </details>

  <h3> 6: Resume runs from dataset artifact & checkpoint artifacts. </h3>
 <b> Local dataset or model checkpoints are not required. This can be used to resume runs directly on a different device </b>
 The syntax is same as the previous section, but you'll need to lof both the dataset and model checkpoints as artifacts, i.e, set bot <code>--upload_dataset</code> or
 train from <code>_wandb.yaml</code> file and set <code>--save_period</code>

 <details>
  <summary> <b>Usage</b> </summary>
   <b>Code</b> <code> $ python train.py --resume wandb-artifact://{run_path} </code>

![Screenshot (70)](https://user-images.githubusercontent.com/15766192/128728988-4e84b355-6c87-41ae-a591-14aecf45343e.png)
 </details>

</details>

 <h3> Reports </h3>
W&B Reports can be created from your saved runs for sharing online. Once a report is created you will receive a link you can use to publically share your results. Here is an example report created from the COCO128 tutorial trainings of all four YOLOv5 models ([link](https://wandb.ai/glenn-jocher/yolov5_tutorial/reports/YOLOv5-COCO128-Tutorial-Results--VmlldzozMDI5OTY)).

<img width="900" alt="Weights & Biases Reports" src="https://user-images.githubusercontent.com/26833433/135394029-a17eaf86-c6c1-4b1d-bb80-b90e83aaffa7.png">

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Notebooks** with free GPU: <a href="https://bit.ly/yolov5-paperspace-notebook"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/GCP-Quickstart)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/AWS-Quickstart)
- **Docker Image**. See [Docker Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/Docker-Quickstart) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/yolov5/actions/workflows/ci-testing.yml"><img src="https://github.com/ultralytics/yolov5/actions/workflows/ci-testing.yml/badge.svg" alt="YOLOv5 CI"></a>

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 [training](https://github.com/ultralytics/yolov5/blob/master/train.py), [validation](https://github.com/ultralytics/yolov5/blob/master/val.py), [inference](https://github.com/ultralytics/yolov5/blob/master/detect.py), [export](https://github.com/ultralytics/yolov5/blob/master/export.py) and [benchmarks](https://github.com/ultralytics/yolov5/blob/master/benchmarks.py) on MacOS, Windows, and Ubuntu every 24 hours and on every commit.

**Comment by ChristopherSTAN** [comment]
Really cool, I suffer from delaying update due to the google drive file system on Colab. Can't wait to try this method.

**Comment by glenn-jocher** [comment]
@ChristopherSTAN yes, this is similar to the Google Drive with Colab trick you discovered earlier. It adds a few useful features also like public sharing of your runs, and GPU monitoring:
<img width="854" alt="Screenshot 2020-11-05 at 16 44 19" src="https://user-images.githubusercontent.com/26833433/98262713-375f4000-1f86-11eb-9ce6-117089e80260.png">

And also good metadata saving, allowing for better reproducibility:
<img width="985" alt="Screenshot 2020-11-05 at 16 47 54" src="https://user-images.githubusercontent.com/26833433/98263220-da17be80-1f86-11eb-97b9-e08379c70ef0.png">

**Comment by bamboosdu** [comment]
> @ChristopherSTAN yes, this is similar to the Google Drive with Colab trick you discovered earlier. It adds a few useful features also like public sharing of your runs, and GPU monitoring:
> <img alt="Screenshot 2020-11-05 at 16 51 02" width="758" src="https://user-images.githubusercontent.com/26833433/98263455-24993b00-1f87-11eb-9f9c-e9ed2e99960e.png">
> 
> And also good metadata saving, allowing for better reproducibility:
> <img alt="Screenshot 2020-11-05 at 16 47 54" width="985" src="https://user-images.githubusercontent.com/26833433/98263220-da17be80-1f86-11eb-97b9-e08379c70ef0.png">

A stupid question. How can you produce the picture with shadow, it looks elegant.

**Comment by sithu31296** [comment]
@bamboosdu It is a screenshot with extra white background. Shadow is already included.

**Comment by glenn-jocher** [comment]
@sithu31296 yes, you to take the screenshot at just the right time of day to get the correct shadow.

**Comment by codename5281** [comment]
Hello @glenn-jocher, and thanks for this really useful tool.
I face two issues though :

1. i don't see any parser for the --logdir argument in train.py, so even after having pulled the last YOLOv5 version this way of launching a training yields an error
2. is it intended that the default run save paths are different than with a native YOLOv5 run (./yolov5/runs/train/ vs ./yolov5/runs/ before) ?

The only think i could think of regarding these issues is that i am still running my trainings under Python 3.6.5 that, if i'm not mistaken, was still recent enough a few weeks back.

What do you think ?
Thanks in advance !
J.

**Comment by glenn-jocher** [comment]
@codename5281 default directories have been updated in Unified '/project/name' results saving #1377. See Custom Training Tutorial and Colab notebook for new examples. 
https://github.com/ultralytics/yolov5#tutorials

**Comment by karasinski-mauro** [comment]
Thank you for the informations!

glenn-jocher Could you tell me how I can implement a cross-validation k-fold in YOLOv5 associated with W&B?

I would like to evaluate the 5-fold charts at the same time.

**Comment by glenn-jocher** [comment]
@karasinski-mauro interesting question. I was reading up a bit of k-fold validation at https://scikit-learn.org/stable/modules/cross_validation.html, and it seems like an interesting idea to reduce reliance on a particular split, but at the same time very computationally expensive and perhaps not suitable for most applications. 

If you are interested in applying it nonetheless, it would require a bit of additional custom code. One thing I can point you to is the autosplit() we have in YOLOv5, which will take a directory of images and randomly split them according to your requested ratios. You can run this several times to create independent k-fold splits for your data.

https://github.com/ultralytics/yolov5/blob/c0ffcdf998aa0e00f1f39e79ee8124b74b53d23f/utils/datasets.py#L918-L919

**Comment by thesauravs** [comment]
I'm facing a problem with logging into wandb. Instead of each run to be logged separately, it merges with an existing run within a project. Is yolov5 facing some issue with wandb? anyone with a similar problem? Also cannot move the runs from one project to another in wandb profile.

**Comment by glenn-jocher** [comment]
@thesauravs yes this was a bug we patched a few days ago in https://github.com/ultralytics/yolov5/pull/1852. Please git pull to receive this update and let us know if you have any other issues!

**Comment by thesauravs** [comment]
> @thesauravs yes this was a bug we patched a few days ago in #1852. Please `git pull` to receive this update and let us know if you have any other issues!

I'm using colab notebook and command git clone. The problem persists. 
![Screenshot 2021-01-14 at 9 59 38 AM](https://user-images.githubusercontent.com/52307927/104545072-55fe4900-5651-11eb-8151-a622b2f06e06.png)

![Screenshot 2021-01-14 at 9 58 40 AM](https://user-images.githubusercontent.com/52307927/104545041-39faa780-5651-11eb-9288-728a80f661b5.png)

**Comment by glenn-jocher** [comment]
@thesauravs if the issue is reproducible please open a bug report with exact code to reproduce.

**Comment by lrbrrr** [comment]
Hi @glenn-jocher, is there a way to visualize mAP/P/R/losses vs epoch instead of step or wall time in wandb.ai?

**Comment by glenn-jocher** [comment]
@lrbrrr yes! This change was implemented in a recent PR about a week ago, apologies for the lengthy wait. If you git pull and train again your wandb dashboard will log per epoch now.

**Comment by lrbrrr** [comment]
> @lrbrrr yes! This change was implemented in a recent PR about a week ago, apologies for the lengthy wait. If you git pull and train again your wandb dashboard will log per epoch now.

I just tried with coco128 dataset. I cannot see the epoch as option for x-axis.
![Screenshot from 2021-02-09 12-52-57](https://user-images.githubusercontent.com/78729788/107329179-ce7fea80-6ad5-11eb-932d-6ade2d907dd9.png)

**Comment by glenn-jocher** [comment]
@lrbrrr plotting defaults to epochs on the x axis now, no action is required on your part (there's no need to select anything).

**Comment by jaafreh** [comment]
Hi Glenn 
We are an academic group currently working on producing a paper in the title of Olive harvesting using Yolov5 architecture. We are pleased with the olive detection output results from Yolo 5 which showed a robust precision and mAP compared to other Yolo versions and RCNN algorithms. However, we are currently trying to test different hyperparameters using sweep from WandB. All the attempts in implementing sweep in the train.py file were failed.  We appreciate it if you could help us with the issues as we have limited time in submitting the paper. We finally got this error after we delete all action="store_true" from arg parser:
`train.py: error: unrecognized arguments: --batch_size=29 --cache_images=true --exist_ok=false --global_rank=-1 --hyp.anchor_t=8 --hyp.box=0.07246915121169895 --hyp.cls=0.8503969655436721 --hyp.cls_pw=1 --hyp.fliplr=0.2868210743865315 --hyp.hsv_h=0.028518921869036012 --hyp.hsv_s=1.234917241085553 --hyp.hsv_v=0.23896492378841477 --hyp.iou_t=0.1541829325843371 --hyp.lr0=0.014132676777321062 --hyp.lrf=0.15258688586250735 --hyp.momentum=0.9728345474816077 --hyp.mosaic=1 --hyp.obj=2 --hyp.obj_pw=2 --hyp.scale=0.39897504402382566 --hyp.translate=0.069231722815808 --hyp.warmup_bias_lr=0.08910230413617964 --hyp.warmup_epochs=5 --hyp.warmup_momentum=0.6153657972615175 --hyp.weight_decay=0.0007967895019431605 --image_weights=true --linear_lr=false --log_artifacts=false --log_imgs=11 --multi_scale=false --save_dir=runs/train/exp --single_cls=false --sync_bn=false --total_batch_size=9 --world_size=1
`

**Comment by glenn-jocher** [comment]
@jaafreh ah good question. I'm not an expert in sweeps but perhaps @AyushExel could help you here. It might be good to create a sweeps tutorial. I've experimented in the past, i.e. here https://wandb.ai/glenn-jocher/COCO128_evolve with a 300-generation evolution for COCO128.

The way I did the above evolution was to evolve hyps following the [Hyperparameter Evolution Tutorial](https://github.com/ultralytics/yolov5/issues/607), and then visualize the results using either the built-in plots or also the W&B sweeps visualizer.

**Comment by AyushExel** [comment]
@glenn-jocher sure I think we can come up with a nice sweeps tutorial. Let's discuss the details in our meeting tonight.

**Comment by adrianholovaty** [comment]
Any idea why my YOLOv5 W&B runs aren't getting an "outputs" section, as in the [above screenshot](https://user-images.githubusercontent.com/26833433/98184457-bd3da580-1f0a-11eb-8461-95d908a71893.jpg)? I'm very interested in using W&B's dynamic "show predicted bounding boxes at each training step" feature demonstrated at 3:00 in [this video](https://www.youtube.com/watch?v=t37gnfQzgP4), but I can't see to figure out how to do that!

(I'm using the latest master version of YOLOv5.)

**Comment by AyushExel** [comment]
Hi @adrianholovaty, In a previous update, the bounding box logger was updated to log only in the final epoch. But we're working on building a better W&B integration where you'll be able to set an argparse `--bbox-interval` to set the number of epochs-interval after which the bounding boxes will be plotted. If it is set to 1, the boxes will be plotted after every epoch. We'll keep you updated on the progress

**Comment by adrianholovaty** [comment]
@AyushExel Thanks, that makes perfect sense. Keep up the great work — you guys are awesome!

**Comment by Practcdi** [comment]
Hello Guys, @glenn-jocher 
I'm a beginner training yolov5s on the custom dataset.


# Question 

1) What is the standard data size required for yolo5 model training (FOR Good model)

2) How much map@ score should I need to get the best inference on real-world data and how to improve that?


_____


> NOTE : Some of images are unannotated
![image](https://user-images.githubusercontent.com/58843833/115222163-118ab980-a128-11eb-8101-5148da5f754a.png)


3) My **val/class_loss and val/box_loss are always 0** , How I can I fix it ?


![image](https://user-images.githubusercontent.com/58843833/115221829-b3f66d00-a127-11eb-9df6-ea133846981f.png)


Thanks,

**Comment by glenn-jocher** [comment]
@Practcdi hi there! Please see our Tips for Best Training Results ☘️ below.

## YOLOv5 Tutorials

* [Train Custom Data](https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://github.com/ultralytics/yolov5/wiki/Tips-for-Best-Training-Results)&nbsp; ☘️ RECOMMENDED

**Comment by fcakyon** [comment]
@glenn-jocher how can i visualize iteration based train loss in wandb?

**Comment by glenn-jocher** [comment]
@fcakyon iteration means one optimizer update typically, or one batch processed, but losses and metrics are only logged at the end of each epoch. Losses within each epoch are not saved.

**Comment by fcakyon** [comment]
@glenn-jocher by iteration based, i mean logging the training loss at every 100 iteration, for instance. 

Other frameworks such as mmdetection send the training logs after each iteration windows (per 100 iteration for instance) to wandb and send the validation accuracy after each epoch. 

One epoch may take 5-6 hours to complete, so being able to visualize loss within epoch (instead of waiting a full epoch) tells a lot on he future of training.

Does it make sense to you?

**Comment by glenn-jocher** [comment]
@fcakyon ah yes that makes sense. Unfortunately we don't have a similar capability right now, we'd need some updates to train.py in order to do this. I can see some epochs taking very long, i.e. OIv6 or Objects365. The main workaround currently is to view training losses directly in the 'Logs' panel which seems to update every few seconds.
https://wandb.ai/glenn-jocher/activations/runs/tlau254q/logs

**Comment by fcakyon** [comment]
@glenn-jocher i see, thanks for the fast response!

**Comment by mskmei** [comment]
Thank you for this wonderful method!!
What should I do if I want to visualize more things like accuracy and mIou (which are not included in the present code)?  Which file should I add some changes to? Thank you very much!

**Comment by KAttal007** [comment]
I keep getting the error AttributeError: module 'utils.loggers.wandb' has no attribute 'Image' 
When trying to train my custom dataset on YOLOv5.
I've made sure i have the latest version of the git repo as well as wandb installed, i tried a couple workarounds like using 'wandb.sdk.data_types.image.Image' or 'wandb.data_types.Image'

But even with these i still keep getting the error of attribute not found, and I've spent almost my entire sunday trying to figure out why this isn't recognizing the wandb attribute...

PLEASE  @glenn-jocher because my engineering project is kind of hanging on the line if i can't get it trained

**Comment by glenn-jocher** [comment]
@KAttal007 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. I just trained a model right now with latest repo and wandb without issue:
https://wandb.ai/glenn-jocher/test/runs/1gitmoxr

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem. Once we have this then @AyushExel, our wandb expert can look into the problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by angbaozhang** [comment]
> python train.py --upload_data val

hello, when i run this command ‘python train.py --upload_data val“ in yolov5 5.0，it occurs: "Instances of wandb.Artifact and wandb.apis.public.Artifact can only be top level keys in wandb.config".   I wonder if it's a version problem? may be i should use the latest v6.1?  Thank you!

**Comment by AyushExel** [comment]
@angbaozhang uploading data as artifact requires wandb==0.10.2 or lower. See this warning https://github.com/ultralytics/yolov5/blob/master/utils/loggers/__init__.py#L86

**Comment by Buse-cetin** [comment]
How does the review from the ip camera in Yolov5 help?

**Comment by ma-muyuan** [comment]
Hello @glenn-jocher ,I am trying to train the model with W&B offline, although I set the "WANDB_MODE" as "offline" in train.py, it always displays network error. So I want to ask you what should I do to train the model with W&B offline.Thank you very much!

**Comment by AyushExel** [comment]
@ma-muyuan have you tried `wandb disabled`?

**Comment by ma-muyuan** [comment]
> 

Hi @AyushExel , I haven't try `wandb disabled`, I will try if I don't have any other way.Thank you very much.
