### ISSUE TITLE
How to finetune from pretrained model

### ISSUE THREAD

**Issue by TaoXieSZ** [ultralytics/yolov5#129]
Hi Glenn,

I find train from scratch on VOC dataset kind of difficult.

Is there way to finetune from your pretrained model?

I tried but encounter this error:

`KeyError: "weights/yolov3-spp.pt is not compatible with ./models/yolov5-voc.yaml. Specify --weights '' or specify a --cfg compatible with weights/yolov3-spp.pt."`

Thanks for your help.

BTW, do our great YOLOv5 contain fashion tricks applied by YOLOv4?
For example, SAT? I am looking forward about them.

**Comment by glenn-jocher** [comment]
@ChristopherSTAN you can start from any pretrained checkpoint, but naturally you need to match the model cfg with the checkpont. v3 and v5 have different architectures, they're not compatible as the error message states.

python train.py --weights yolov3-spp.pt --cfg yolov3-spp.yaml

BTW, in the future, **always include code to reproduce**.

**Comment by TaoXieSZ** [comment]
Following your tutorial, I find that if I change the parameter `nc` for a dataset with 20 classes, it will of course change the structure of yolo heads. And it come out the incompatible error. 

I am not sure it is my mistake. In your previous yolov3, even I train on custom dataset, the model will naturally load "yolov3-spp.pt" and start training.

**Comment by TaoXieSZ** [comment]
Sorry! I found that's my fault.

I forget to delete `--resume`
