### ISSUE TITLE
How to cite and make acknowledgements for YOLO v5 in a thesis?

### ISSUE THREAD

**Issue by qruiwu** [ultralytics/yolov5#12900]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have used YOLO v5 code conducting a reasearch, but how to cite and make acknowledgements for YOLO v5 in my thesis? Please tell me the orignal references of YOLO v5, which will be cited. And if there are any specified words or comments should be stated in acknowledgements?

**Comment by glenn-jocher** [comment]
@wuqrcn hello! 😊

We're thrilled to hear about your interest in citing YOLOv5 for your thesis. Here's a concise way to acknowledge and cite YOLOv5:

In your thesis acknowledgments, you can mention something along these lines: "We thank the developers and contributors of YOLOv5 by Ultralytics for providing an efficient and open-source platform for object detection tasks."

For citing YOLOv5, you can adapt the following format to suit the citation style you're using:

- **APA:**
  Ultralytics. (Year). YOLOv5. Retrieved from https://github.com/ultralytics/yolov5. Accessed [Month] [Year].

- **MLA:**
  Ultralytics. "YOLOv5." *GitHub*. Year. Web. [Month Year].

Note: Please adjust the 'Year' and '[Month Year]' according to when you accessed the repository for your research.

We don't have an official publication for YOLOv5 yet, so referring to the GitHub repository is the most appropriate method of citation for now. Your support and acknowledgment mean a lot to us and the broader YOLO community!

If you need more detailed guidance, don't hesitate to ask. Best of luck with your thesis! 🌟

**Comment by qruiwu** [comment]
> @wuqrcn hello! 😊
> 
> We're thrilled to hear about your interest in citing YOLOv5 for your thesis. Here's a concise way to acknowledge and cite YOLOv5:
> 
> In your thesis acknowledgments, you can mention something along these lines: "We thank the developers and contributors of YOLOv5 by Ultralytics for providing an efficient and open-source platform for object detection tasks."
> 
> For citing YOLOv5, you can adapt the following format to suit the citation style you're using:
> 
> * **APA:**
>   Ultralytics. (Year). YOLOv5. Retrieved from https://github.com/ultralytics/yolov5. Accessed [Month] [Year].
> * **MLA:**
>   Ultralytics. "YOLOv5." _GitHub_. Year. Web. [Month Year].
> 
> Note: Please adjust the 'Year' and '[Month Year]' according to when you accessed the repository for your research.
> 
> We don't have an official publication for YOLOv5 yet, so referring to the GitHub repository is the most appropriate method of citation for now. Your support and acknowledgment mean a lot to us and the broader YOLO community!
> 
> If you need more detailed guidance, don't hesitate to ask. Best of luck with your thesis! 🌟

OK, thank you very much!

**Comment by glenn-jocher** [comment]
@wuqrcn You're welcome! If you have any more questions later on or need further assistance, feel free to reach out. Good luck with your thesis, and happy coding! 😊🚀
