### ISSUE TITLE
Error loading self trained model

### ISSUE THREAD

**Issue by pepsile** [ultralytics/yolov5#12916]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I encountered an error while using my own trained model for real-time detection and rendering the detection results to the front-end
Here is my code and error message
model1 = YOLO('runs/train/exp4/weights/best.pt')

def process_frame(frame):
    res = model1(frame)  # predict on an image
    res_plotted = res[0].plot()
    return res_plotted

def gen(camera,fps=30):
    delay = 1/fps
    while True:
        success, image = camera.read()
        if not success:
            break
        ret, jpeg = cv2.imencode('.jpg', image)
        frame = jpeg.tobytes()
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')
        time.sleep(delay)

def generate_frames(file):
    cap = cv2.VideoCapture(file)

    while True:
        ret, frame = cap.read()

        if not ret:
            break
        processed_frame = process_frame(frame)
        ret, buffer = cv2.imencode('.jpg', processed_frame)
        frame_data = buffer.tobytes()
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame_data + b'\r\n')

 File "E:\Anaconda3\envs\flaskdemo\lib\site-packages\werkzeug\wsgi.py", line 289, in __next__
    return self._next()
  File "E:\Anaconda3\envs\flaskdemo\lib\site-packages\werkzeug\wrappers\response.py", line 32, in _iter_encoded
    for item in iterable:
  File "C:\Users\200391\Desktop\ProjectStudy\demouse\yolov.py", line 56, in generate_frames
    processed_frame = process_frame(frame)
  File "C:\Users\200391\Desktop\ProjectStudy\demouse\yolov.py", line 30, in process_frame
    res = model1(frame)  # predict on an image
  File "E:\Anaconda3\envs\flaskdemo\lib\site-packages\ultralytics\engine\model.py", line 176, in __call__
    return self.predict(source, stream, **kwargs)
  File "E:\Anaconda3\envs\flaskdemo\lib\site-packages\ultralytics\engine\model.py", line 452, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "E:\Anaconda3\envs\flaskdemo\lib\site-packages\ultralytics\engine\predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "E:\Anaconda3\envs\flaskdemo\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "E:\Anaconda3\envs\flaskdemo\lib\site-packages\ultralytics\engine\predictor.py", line 268, in stream_inference
    s[i] += self.write_results(i, Path(paths[i]), im, s)
  File "E:\Anaconda3\envs\flaskdemo\lib\site-packages\ultralytics\engine\predictor.py", line 328, in write_results
    string += result.verbose() + f"{result.speed['inference']:.1f}ms"
  File "E:\Anaconda3\envs\flaskdemo\lib\site-packages\ultralytics\engine\results.py", line 328, in verbose
    log_string += f"{n} {self.names[int(c)]}{'s' * (n > 1)}, "
KeyError: 1275
![demo](https://github.com/ultralytics/yolov5/assets/120768686/7e2aa5b7-32be-4e4a-a74c-9abcb1c85b34)

**Comment by glenn-jocher** [comment]
Hey there! It seems like you're encountering a `KeyError` which typically indicates an issue with the class indices. From your error message, it seems like the model is attempting to access a class index (1275) that doesn't exist in the dataset's label set. This could happen if there's a mismatch between the classes your model was trained on and the classes defined in your code or inference setup. 

To troubleshoot, I suggest:
1. Double-check the number of classes your model was trained on and ensure it matches the configuration in your code where the model is loaded for inference.
2. If you're utilizing a custom dataset, verify that the class labels align with your dataset's annotations.

This usually resolves the KeyError by ensuring consistency between your training and inference environments. If the issue persists, you might want to review your training setup and dataset. Let's keep improving together! 🚀

**Comment by pepsile** [comment]
I printed the type label and the detected type ID in the detection results, and found that the detection ID
 if boxes:
            print(self.names)
            for c in boxes.cls.unique():
                # 无
                print(int(c))
                n = (boxes.cls == c).sum()  # detections per class
                log_string += f"{n} {self.names[int(c)]}{'s' * (n > 1)}, "
        return log_string
This is the message from the console output, the detected class id is too large. Why does this problem not occur when I reason with pictures or videos
{0: 'people', 1: 'bio', 2: 'plastic'}
1515
KeyError: 1515

{0: 'people', 1: 'bio', 2: 'plastic'}
875
KeyError: 875

{0: 'people', 1: 'bio', 2: 'plastic'}
1115
KeyError: 1115

{0: 'people', 1: 'bio', 2: 'plastic'}
1115
KeyError: 1115

{0: 'people', 1: 'bio', 2: 'plastic'}
1435
KeyError: 1435

**Comment by glenn-jocher** [comment]
Hey there! It looks like the class IDs detected during inference are way beyond the expected range based on your class names. This unusual behavior could be due to a mismatch in model weights used during inference or a misconfiguration in the model's definition. Here are a couple of things to check:
- Ensure that the model loaded for inference is indeed the one trained on your dataset with the correct number of classes.
- Confirm that there's no data corruption with the model weights file.

It's unusual for this issue to occur with images or videos but not elsewhere. This hints that the anomaly may lie in how the data is being processed or fed into the model during the instance where the error occurs. Double-check your data preprocessing steps to ensure consistency across different data types (images, videos, real-time feeds, etc.).

Let's aim for seamless model inference! 🌟
