### ISSUE TITLE
how to resume to evolute the hyperparameters?

### ISSUE THREAD

**Issue by gofugoo** [ultralytics/yolov5#1291]
## ❔Question
Hi,
I am trying to evolute the hyperparameters on the GPU machine of google colaboratory,  but it will break the evolution beyond 12 hours. the "--resume" is just for training, how can i continue to evolute from the broken-point.

**Comment by alicera** [comment]
especially, resume the command
"""
python -m torch.distributed.launch --nproc_per_node 2 train.py --batch-size 64 --data coco.yaml --weights yolov5l.pt
"""

https://github.com/ultralytics/yolov5/issues/475

**Comment by gofugoo** [comment]
> especially, resume the command
> """
> python -m torch.distributed.launch --nproc_per_node 2 train.py --batch-size 64 --data coco.yaml --weights yolov5l.pt
> """
> 
> #475

I do not find the argument of "--evolve" above your provided command. according to the source of "train.py"
https://github.com/ultralytics/yolov5/blob/master/train.py
`parser.add_argument('--evolve', action='store_true', help='evolve hyperparameters')`
it always do 300 loops, which seems that it cannot resume to  evolve.
 ` for _ in range(300):  # generations to evolve`

here is my command:
`!python3.8 train.py --data ../data_bbox/data2/custom.yaml --cfg ../data_bbox/data2/yolov5s.yaml --weights ../data_bbox/data2/custom.pt --batch-size 200 --epochs 300 --rect --evolve --img-size 512 --cache-images --hyp runs/evolve/hyp_evolved.yaml`

**Comment by glenn-jocher** [comment]
@gofugoo to resume hyperparameter evolution, you just use the same command.

Your evolution results file `yolov5/evolve.txt` must be present, otherwise evolution will start from the beginning again.

**Comment by glenn-jocher** [comment]
@gofugoo for persistent storage of your evolution results you can supply a `--bucket` argument to point YOLOv5 to a GCP bucket. This will read and write to [gs://your_bucket/evolve.txt](url)

**Comment by gofugoo** [comment]
> @gofugoo for persistent storage of your evolution results you can supply a `--bucket` argument to point YOLOv5 to a GCP bucket. This will read and write to [gs://your_bucket/evolve.txt](url)

Thanks.
