### ISSUE TITLE
Does Yolo5 support vertical hierarchy?

### ISSUE THREAD

**Issue by sarpx** [ultralytics/yolov5#1292]
## ❔Question
Car first then type of car. Or the dog first and then I try to find the breed of the dog. How can I do this with Yolo5?
---Person
---- Female 
---- Male
---Car
----Suv
----Jeep
---Dog
----French Bulldog
----Bull Terrier
----Chihuahua
I ask for your attention.

**Comment by glenn-jocher** [comment]
@sarpx you may want to read the YOLO9000 paper for a similar approach. This can be applied to YOLOv5 as well, it's simply a matter of structuring the output layer appropriately and supplying the data with the hierarchy labels.
https://arxiv.org/pdf/1612.08242.pdf

<img width="333" alt="Screenshot 2020-11-05 at 16 36 31" src="https://user-images.githubusercontent.com/26833433/98261756-164a1f80-1f85-11eb-9c03-d52d2f0b5c38.png">

**Comment by sarpx** [comment]
I want to work on this. On the subject of Yolo5 and vertical hierarchy. I need a simple snowball roll to get used to the code. I could not start. thank you for your attention.

**Comment by glenn-jocher** [comment]
@sarpx great!

**Comment by sarpx** [comment]
@Glenn As a code, I was hoping for quick start tips from you :)))
