### ISSUE TITLE
Manual Execution

### ISSUE THREAD

**Issue by kbkabadayi** [ultralytics/yolov5#12927]
File: https://github.com/ultralytics/yolov5/blob/master/.github/workflows/codeql-analysis.yml
Smell Description:
This smell occurs when a workflow is set to be run manually using on: workflow_dispatch keyword. It is a bad practice to run workflows manually.
Fix:
Remove workflow_dispatch at line 4

**Comment by glenn-jocher** [comment]
Hey there 👋! Thanks for reaching out with your observation.

Actually, the use of `workflow_dispatch` in the `.github/workflows/codeql-analysis.yml` allows for a higher degree of flexibility by enabling manual triggers of the workflow. This can be particularly useful for testing or debugging purposes without the need to push commits just to trigger the workflow. It's a deliberate choice to balance automation with manual control where necessary.

We aim to maintain practicality alongside efficiency in our workflows, and this approach has shown benefits in various scenarios. Nonetheless, we appreciate your input and are always evaluating our practices for improvements!

Let us know if you have any more suggestions or questions!
