### ISSUE TITLE
No labels in D:\yolov5\datasets\img\train.cache. Can not train without labels

### ISSUE THREAD

**Issue by wenjiejiang0312** [ultralytics/yolov5#12926]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm a beginner and I'm working on poultry disease detection. However, I keep getting the error message "No labels in D:\yolov5\datasets\img\train.cache. Can not train without labels." My English is not very good, and it's difficult for me to search for information. How can I solve this problem? I would greatly appreciate any help.
<img width="1280" alt="eb35df9e33b62a3995291581f263f4d5" src="https://github.com/ultralytics/yolov5/assets/154549470/12d73aa9-9f07-4aae-91eb-bef6e10fe10d">
<img width="780" alt="d2e0af05b1d205c37a258ff574ef0f4f" src="https://github.com/ultralytics/yolov5/assets/154549470/c86dc032-fd0f-4b84-b1df-b98340333828">
<img width="780" alt="9c0a43bb52e262f72e6d024fc3d632ec" src="https://github.com/ultralytics/yolov5/assets/154549470/d49c1faa-c690-41db-96cb-4a3d4070a55d">
<img width="780" alt="02224486f39238cb8cde1476fb5f0af9" src="https://github.com/ultralytics/yolov5/assets/154549470/063f7ecd-16d0-4fb4-b4b7-9ba150294adc">

**Comment by glenn-jocher** [comment]
Hello! It looks like your dataset is missing label files for your training images. Each image in your dataset needs a corresponding label file in YOLO format, which is a `.txt` file with the same name as the image file, located in the same directory. These `.txt` files should contain the class ID and bounding box coordinates for each object in the image, in the format `[class_id x_center_norm y_center_norm width_norm height_norm]`, where all normalized values are relative to the image size.

To resolve your issue, please ensure that:
1. You have label `.txt` files for all your images in the dataset.
2. Each label file is correctly formatted and located in the appropriate directory alongside its corresponding image.

📚 For more detailed guidance on preparing your dataset, you might find the documentation helpful: https://docs.ultralytics.com/yolov5/.

Hope this helps! If you have any more questions, feel free to ask. Happy training! 😊
