### ISSUE TITLE
How to show count in screen using yolov5

### ISSUE THREAD

**Issue by tasyoooo** [ultralytics/yolov5#12947]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I would like to show the count of objects in the screen using yolov5. I'm using a webcam as the source and i would like to show the objects it counts in the screen also together with the bounding boxes. I've tried adding lines of code in detect.py but nothing works, it always generated an error

**Comment by glenn-jocher** [comment]
Hello! 😊 To display the count of detected objects on the screen with YOLOv5, you can modify the code where detection bounding boxes are drawn. Here's a simple way to do it:

1. After objects are detected and before the loop that goes through detections and draws boxes, calculate the count of objects by class.
2. Use OpenCV's `cv2.putText()` to display the count on the frame.

Here's a basic snippet that you can add/modify in your `detect.py` file after detection results are processed:

```python
# Assuming 'pred' is the prediction result and 'names' are class names
for i, det in enumerate(pred):  # detections per image
    if len(det):
        # Count objects by class
        count_per_class = Counter(det[:, -1].int().tolist())
        for class_id, count in count_per_class.items():
            label = f"{names[class_id]}: {count}"
            # Display on the top-left corner, you can change the position as needed
            cv2.putText(im0, label, (10, 45 + 30 * class_id), cv2.FONT_HERSHEY_SIMPLEX, 
                        1.25, (255,255,255), 3)
```

Be sure to adjust `im0` (the frame you want to draw on), the position `(10, 45 + 30 * class_id)`, the font size, and the color `(255,255,255)` to fit your needs. 

This will display a count of each detected class on the video frames. Happy coding! 🚀

**Comment by tasyoooo** [comment]
> Hello! 😊 To display the count of detected objects on the screen with YOLOv5, you can modify the code where detection bounding boxes are drawn. Here's a simple way to do it:
> 
> 1. After objects are detected and before the loop that goes through detections and draws boxes, calculate the count of objects by class.
> 2. Use OpenCV's `cv2.putText()` to display the count on the frame.
> 
> Here's a basic snippet that you can add/modify in your `detect.py` file after detection results are processed:
> 
> ```python
> # Assuming 'pred' is the prediction result and 'names' are class names
> for i, det in enumerate(pred):  # detections per image
>     if len(det):
>         # Count objects by class
>         count_per_class = Counter(det[:, -1].int().tolist())
>         for class_id, count in count_per_class.items():
>             label = f"{names[class_id]}: {count}"
>             # Display on the top-left corner, you can change the position as needed
>             cv2.putText(im0, label, (10, 45 + 30 * class_id), cv2.FONT_HERSHEY_SIMPLEX, 
>                         1.25, (255,255,255), 3)
> ```
> 
> Be sure to adjust `im0` (the frame you want to draw on), the position `(10, 45 + 30 * class_id)`, the font size, and the color `(255,255,255)` to fit your needs.
> 
> This will display a count of each detected class on the video frames. Happy coding! 🚀

There is an error occurred:
count_per_class = Counter(det[:, -1].int().tolist())
NameError: name 'Counter' is not defined

**Comment by glenn-jocher** [comment]
Hello! 😊 It seems you're missing an import statement for the `Counter` class. You can fix this by adding the following line to the top of your script:

```python
from collections import Counter
```

This imports the `Counter` class from the Python `collections` module, allowing you to count the objects per class as shown in the snippet. Happy coding! 🚀

**Comment by tasyoooo** [comment]
> Hello! 😊 It seems you're missing an import statement for the `Counter` class. You can fix this by adding the following line to the top of your script:
> 
> ```python
> from collections import Counter
> ```
> 
> This imports the `Counter` class from the Python `collections` module, allowing you to count the objects per class as shown in the snippet. Happy coding! 🚀

it works now, thank you very much!

**Comment by glenn-jocher** [comment]
@tasyoooo you're welcome! I'm glad it worked out for you. If you have any more questions or need further assistance, feel free to ask. Happy coding! 🚀
