### ISSUE TITLE
YoloV5 Own Custom Dataset

### ISSUE THREAD

**Issue by sutthisart** [ultralytics/yolov5#1294]
## ❔Question
Do you have method for training own custom dataset?

## Additional context
I have own custom datasets (250 images and each label file of images) and I don't want to download coco dataset
and Can label file from yolo_mark of AlexeyAB use for training weights in your yolov5?
This link : https://github.com/AlexeyAB/Yolo_mark

**Comment by fabiozappo** [comment]
Hi @sutthisart,

I've just cloned the repo and trained yolov5 on my custom dataset. I suggest you to read [this guide](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data).

**Comment by sutthisart** [comment]
Thank you guys. I got this!

**Comment by sutthisart** [comment]
Excuse me, Glenn-jocher.
Do you have a research paper of this repo? @glenn-jocher

**Comment by glenn-jocher** [comment]
@sutthisart we are planning on publishing to arxiv by the end of the year, in the meantime you can use this for a DOI and bibtex https://github.com/ultralytics/yolov5#citation

**Comment by sutthisart** [comment]
Thank you so much @glenn-jocher
