### ISSUE TITLE
Can yolov5 use as a part of commercial project , if so do we need to open-source the code or the whole project ?

### ISSUE THREAD

**Issue by krupalimistry1993** [ultralytics/yolov5#12941]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to use yolov5 as a sub-part of the project  for commercial purpose. 
As per you mentioned : 
> If you're using Ultralytics (yolo) models, architectures, or code under the AGPL-3.0 license for commercial purposes, you are indeed required to fully open source your entire project under the same AGPL-3.0 license. There are no exceptions to this rule.
So my question is , 
1.) If I use the pretrained weights of the model , and custom datasets,  and train the model, do I need to open-source the code or the whole project ? 
2.) If I use the model code , scratch model and custom datasets,  and train the model, do I need to open-source the code or the whole project ? 
3.) I will not be modifying the code, just use custom dataset, train the model and use this train model for commercial usage ? What license I should have for it ?

**Comment by glenn-jocher** [comment]
Hi there! 😊

Great questions! If you're considering using YOLOv5 for a commercial project, here are the succinct answers to your queries:

1. & 2. Regardless of whether you're using pretrained weights or starting from scratch, if the project is commercial, you have two paths:
   - **Open Source**: Fully open source your entire project under the same AGPL-3.0 license.
   - **Enterprise License**: Obtain an Ultralytics Enterprise License for commercial use without the need to open source your project.

3. Even if you're just using a custom dataset and not modifying our code, the same rules apply. For commercial use without opening your project under AGPL-3.0, you’d need an Ultralytics Enterprise License.

In essence, any commercial deployment of YOLOv5, whether modified or not, necessitates either open-sourcing under AGPL-3.0 or obtaining an enterprise license. There are no exceptions to this.

For further insights, please refer to our documentation: https://docs.ultralytics.com/yolov5/

Hope this clarifies your legal pathways! If you have more questions, feel free to ask. Good luck with your project! 🌟

**Comment by krupalimistry1993** [comment]
Hi @glenn-jocher ,
thank you for you prompt reply. 
Further few questions (related to commercial usage ), 
1.) If I train the model (from scratch) using custom datasets and then export to onnx and run inference using onnx . Inference code will be custom code . Then  what license would be chosen ?
2.) Suppose I have taken Enterprise License and I think it comes with the whole yolo package. So, can I use yolo models for multiple projects ?
    For eg. I have bought 1-year subscription of Enterprise License. I want to use yolov5 for animal detection, yolov7 for flower detection, yolov8 for plant detection, etc. So different subscription for different projects or it comes all in one subscription.

**Comment by glenn-jocher** [comment]
@krupalimistry1993 hi there! 👋

Let's dive right into your questions:

1. **Custom Training & ONNX Export for Commercial Use**: Whether you train the model from scratch, use custom datasets, or employ custom code for inference (e.g., using ONNX), the project is under commercial usage. If you choose not to open source your entire project under AGPL-3.0, you will require an Ultralytics Enterprise License.

2. **Enterprise License & Multiple Projects**: Once you've acquired an Ultralytics Enterprise License, you're free to use it across multiple projects within your organization – there's no need for separate subscriptions for each project or model variant (like YOLOv5, YOLOv7, YOLOv8, etc.) within the validity period of the license. Your 1-year subscription covers the use of our models for all the different applications you mentioned.

I hope this helps clear things up! Feel free to reach out if you have any more questions. Wishing you success with your projects! 🚀

**Comment by krupalimistry1993** [comment]
@glenn-jocher thank you for clear answers.
Few more questions (for Enterprise License)
1.) The Enterprise License subscription is yearly , monthly ? 
2.) Can we choose an option like for once buying the license and then using it for future projects . No yearly, monthly thing.

**Comment by glenn-jocher** [comment]
Hi there! You're welcome. Let's quickly address your inquiries regarding the Enterprise License:

1. **Enterprise License Duration**: Typically, the Enterprise License is offered on a yearly basis. This aligns with common business needs and simplifies management for both parties.

2. **Lifetime License Option**: Currently, we focus on renewable licenses (yearly) to keep providing support and updates effectively. A perpetual (one-time payment for lifetime usage) option isn't part of our standard offerings. The yearly model ensures you receive the latest updates, improvements, and support for your projects.

I hope this helps! Let us know if there's anything more we can do for you. Happy to assist! 😊

**Comment by krupalimistry1993** [comment]
Hi @glenn-jocher , Thank you for the reply. 
I have asked a quotations for the ultralytics Enterprise License , but still haven't received it. 
Do you offer like buying a license for current model version (once and for all the current models ) something similar to Microsoft Office offers , and use it for lifetime ? If we don't require updates of future models . 
Extremely sorry for such questions.

**Comment by glenn-jocher** [comment]
@krupalimistry1993 hi! 😊 No worries about the questions – happy to clarify.

For the quotation and details on the Ultralytics Enterprise License, our sales team should be in touch with you shortly. They're best equipped to handle specific requests and inquiries.

As for licenses, we typically offer yearly subscriptions to ensure ongoing support and updates. We don't provide a lifetime purchase option similar to what you described with Microsoft Office. The yearly model helps us to continually offer timely updates and dedicated support for your projects.

If you have more questions or need further information, please feel free to reach out. Looking forward to assisting you further!
