### ISSUE TITLE
How to close window in yolov5 detection

### ISSUE THREAD

**Issue by tasyoooo** [ultralytics/yolov5#12955]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

In running the detect.py in yolov5, when  X button is clicked in the top right corner the window doesn't close. How to close the window without using the keyboard keys

**Comment by glenn-jocher** [comment]
Hello there! 👋

For window closing issues after running `detect.py` where clicking the X button doesn't work, a simple workaround involves manually handling the window closure through OpenCV. You can add a conditional check after the `cv2.imshow()` call in the code to listen for the window close event (such as clicking the X button). Unfortunately, OpenCV doesn't directly support detecting the window close button event, so a common approach is to use `cv2.waitKey()` for a keyboard interrupt to close the window.

Please check if you're using a command like `cv2.waitKey(0)` or `cv2.waitKey(1)` after `cv2.imshow()`. If so, replacing it with a keyboard interrupt check to break the loop and then using `cv2.destroyAllWindows()` to close the window when a certain key is pressed (like 'q') is a typical solution. This doesn't directly solve the 'click X to close' issue but offers a straightforward way to close the window without modifying the library's source code.

Here is a quick example snippet that might be in your `detect.py` or a similar script:

```python
while True:
    # Your code to display the frame
    cv2.imshow('frame', frame)

    # Break the loop and close the window when 'q' is pressed
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cv2.destroyAllWindows()
```

As OpenCV's `imshow()` doesn't inherently support a direct close window button interaction, relying on keyboard interrupts remains a practical approach.

Let me know if you have more questions or need further assistance. Happy coding! 😄
