### ISSUE TITLE
Is it possible to add ShuffleNetV2 as backbone in the official repo?

### ISSUE THREAD

**Issue by superbayes** [ultralytics/yolov5#12969]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

According to the information I found, ShuffleNetV2 has achieved a good balance in speed and accuracy. ShuffleNetV2 is conducive to the promotion of yoloV5 on various devices.
so,Is it possible to add ShuffleNetV2 as backbone in the official repo?

[ShuffleNet: An Extremely Efficient Convolutional Neural Network for Mobile Devices](https://www.researchgate.net/publication/318205093_ShuffleNet_An_Extremely_Efficient_Convolutional_Neural_Network_for_Mobile_Devices)

[Who is the king of lightweight CNN? Comprehensive evaluation in 7 dimensions mobilenet/shufflenet/ghostnet](https://www.bilibili.com/read/cv8801259/)

**Comment by glenn-jocher** [comment]
Hello! Thanks for bringing up the idea of incorporating ShuffleNetV2 as a backbone for YOLOv5. 🚀

We're always excited to explore ways to improve and adapt YOLOv5 for various device efficiencies and accuracies. While integrating a new backbone like ShuffleNetV2 can potentially enhance YOLOv5 for mobile and edge devices, such updates require thorough testing and validation to maintain the balance between speed, accuracy, and compatibility.

As of now, we encourage community contributions and experiments with different backbones. If you're interested in implementing ShuffleNetV2 yourself, you can fork the repo and try integrating it. This could be a valuable contribution to the community if shared back. Also, keep an eye on our updates; we're continually exploring new ideas!

For more guidance on contributing or custom modifications, check out the docs at https://docs.ultralytics.com/yolov5/.

Thanks for your enthusiasm and suggestions! 💡
