### ISSUE TITLE
Run yolov5 using tensor rt

### ISSUE THREAD

**Issue by tasyoooo** [ultralytics/yolov5#12968]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I exported Tensor RT weights (last.engine). When i use the weights in yolov5 detect it generates an error

`  File "detect.py", line 112, in run
    model = DetectMultiBackend(weights, device=device, dnn=dnn, data=data, fp16=half)
  File "C:\Users\shen\yolov5\models\common.py", line 426, in __init__
    with open(w, "rb") as f, trt.Runtime(logger) as runtime:
TypeError: pybind11::init(): factory function returned nullptr`

**Comment by glenn-jocher** [comment]
Hello! 😊 It looks like you're encountering an issue with deploying a TensorRT model in YOLOv5. This error often indicates a problem initializing the TensorRT engine from the `.engine` file. Here are a few suggestions that might help:

1. Ensure the TensorRT engine was correctly built for your specific platform and GPU. Engines are not portable across different GPU architectures or TensorRT versions.
2. Verify that your environment has the necessary dependencies for TensorRT inference, including the correct version of TensorRT installed.
3. Check if the path to the `.engine` file in your `detect.py` invocation is correct and accessible.

If the issue persists, consider re-exporting your model to the TensorRT engine format, confirming each step's success. For guidance on model conversion and deployment using TensorRT with YOLOv5, our documentation can offer further insights: https://docs.ultralytics.com/yolov5/.

Feel free to share more details if you're still facing challenges. Good luck!
