### ISSUE TITLE
How to learn with small images (48*48)

### ISSUE THREAD

**Issue by S-mishina** [ultralytics/yolov5#1296]
## ❔Question
I trained it with a 48*48 image as input --img-size48, but the output does not come.The image is not being trained properly.
Epoch has been done 1000 times.
Can yolo train an image with small input?
One thing I've been thinking about is whether it would work if I made the image of the training program's bounding box smaller.
Or do I need to do that to make it work?

I'd be happy to answer your questions.
Thank you very much.

Learning Results
![labels](https://user-images.githubusercontent.com/45090872/98225869-9c239600-1f98-11eb-8740-be670745ebf5.png)
![results](https://user-images.githubusercontent.com/45090872/98225888-a0e84a00-1f98-11eb-97f9-f4a05a4bfe72.png)

**Comment by glenn-jocher** [comment]
@S-mishina you may want to upload a public W&B run so everyone can see your full run details, otherwise it's hard to answer your question.

See https://github.com/ultralytics/yolov5/issues/1289
