### ISSUE TITLE
How to use tensor rt in yolov5 detection

### ISSUE THREAD

**Issue by tasyoooo** [ultralytics/yolov5#12973]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm using local machine with gpu rtx3050. I would like to utilize my gpu during the detection process. I am using webcam as a soure and framework tensor rt

**Comment by glenn-jocher** [comment]
Hello there! 👋

Great to hear you're leveraging YOLOv5 with TensorRT for improved performance on your RTX3050 GPU! Using TensorRT, you can significantly speed up inference time by optimizing neural network models.

Here's a general overview of the steps involved:

1. **Export YOLOv5 Model to ONNX**: Convert your trained YOLOv5 model to ONNX format. You can do this with the `export.py` script in the YOLOv5 repository.

```bash
python export.py --weights yolov5s.pt --img 640 --batch 1 --device 0 --opset 12 --include onnx
```

2. **Convert ONNX Model to TensorRT Engine**: Use the `trtexec` command or TensorRT Python API to convert the ONNX model to a TensorRT engine optimized for your GPU.

```bash
trtexec --onnx=yolov5s.onnx --saveEngine=yolov5s.engine
```

3. **Perform Inference with TensorRT**: Finally, you can load the TensorRT engine and perform inference. You'll need to handle pre-processing of your webcam feed and post-processing of the detection outputs according to YOLOv5's requirements.

While the above steps provide a high-level overview, specific implementation details can vary. For further guidance, checking documentation and examples specific to TensorRT and YOLOv5 is recommended. Feel free to explore our official documentation for more insights: https://docs.ultralytics.com/yolov5/

Wishing you success in your project! If you have any more questions, feel free to ask. 🚀
