### ISSUE TITLE
resume_evolve BUG!!!  

### ISSUE THREAD

**Issue by jackttj** [ultralytics/yolov5#12976]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Evolution

### Bug

` with open(ROOT / opt.resume_evolve, errors="ignore") as f:
                evolve_population = yaml.safe_load(f)
                print("evolve_population = " , evolve_population)
                for value in evolve_population.values():
                    print("value = " , value)
                    value = np.array([value[k] for k in hyp_GA.keys()])
                    initial_values.append(list(value))` is there any problems?

evolve_population was the   yaml  and  value just float , how can value[k]???????

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by jackttj** [comment]
not important

**Comment by glenn-jocher** [comment]
@jackttj thank you for reaching out! If there's anything specific you'd like to discuss or if you encounter any issues, feel free to let us know. We're here to help! 😊
