### ISSUE TITLE
Running test.py deletes eveything in my directory 

### ISSUE THREAD

**Issue by MaxwellHogan** [ultralytics/yolov5#1297]
I'm not yet sure what exactly is going on but thought I should report this ASAP since it might be quite major,

after running the following command twice on google colab it will delete the entire git directory 

!python test.py --img-size 416 --batch 64 --data $dataset_yaml --weights ../cfg/weights/yolov5_best.pt

luckily I had made a backup of my weights, however I have lost all my training runs, 

I am not yet sure of the cause but I re-cloned the repo and it occurred a second time

this is the output:
`Traceback (most recent call last):
  File "test.py", line 325, in <module>
  File "test.py", line 51, in test
  File "/usr/lib/python3.6/shutil.py", line 490, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib/python3.6/shutil.py", line 488, in rmtree
    os.rmdir(path)
OSError: [Errno 22] Invalid argument: '.'`

seems to be it's removing the wrong tree

**Comment by constantinfite** [comment]
@MaxwellHogan 
Hello, I'm trying to launch the test.py script but I don't know the structure of the data.yaml file.
Can you tell what you did please ?

**Comment by MaxwellHogan** [comment]
@constantinfite 

step 1 in https://docs.ultralytics.com/yolov5/tutorials/train_custom_data

**Comment by constantinfite** [comment]
@MaxwellHogan 
Thank you, but I think I don't understand what really do the script test.py.
What does it take in input and what's the output ?
For what purpose do you use it ?

**Comment by MaxwellHogan** [comment]
So I'm currently using test.py to evaluate my models after training and looking at the affect of different objectness confidence levels are on the performance of the model

yaml files are just configuration files - my data.yaml file defines the directory where my training, validation or test sets are.

if you look at what the code is doing you can see that test.py will load either the validation or test set depending on what parameters you pass to it.

**Comment by glenn-jocher** [comment]
@MaxwellHogan thanks for raising a bug report. That should definitely not be happening (!). I will try to reproduce in Colab.

**Comment by glenn-jocher** [comment]
@MaxwellHogan are you saying that `yolov5/.git` is removed, or the entire `yolov5/` directory is removed?

**Comment by MaxwellHogan** [comment]
@glenn-jocher I think the cause is when --save-dir is unassigned 

the entire yolov5/ is removed,

one last thing to add is that I mounted my google drive and cloned the repo in my drive

**Comment by glenn-jocher** [comment]
@MaxwellHogan that's not good at all. I tried to reproduce in a single cell in Colab like this but everything seemed fine. Perhaps I should move the weights outside the yolov5 dir?
```python
# Setup
!git clone https://github.com/ultralytics/yolov5  # clone repo
%cd yolov5
!pip install -qr requirements.txt  # install dependencies

import torch
from IPython.display import Image, clear_output  # to display images

clear_output()
print('Setup complete. Using torch %s %s\n' % (torch.__version__, torch.cuda.get_device_properties(0) if torch.cuda.is_available() else 'CPU'))

# Code to reproduce
!python test.py --img-size 416 --batch 64 --data coco128.yaml --weights weights/yolov5s.pt
!python test.py --img-size 416 --batch 64 --data coco128.yaml --weights weights/yolov5s.pt
```

**Comment by MaxwellHogan** [comment]
Yeah my weights are outside the yolov5

**Comment by glenn-jocher** [comment]
I updated so weights are autodownloaded to the sample_data/ directory that Colab comes with, but everything still seems fine. Are there any other steps missing here?

![Screenshot 2020-11-05 at 15 31 40](https://user-images.githubusercontent.com/26833433/98254029-11cd3900-1f7c-11eb-8785-08bce270d30a.jpg)

**Comment by glenn-jocher** [comment]
@MaxwellHogan ah, I finally see what's going on. The --save-dir, which is `yolov5/runs/test` by default, is removed and created again when testing starts. If you point --save-dir to your root directory then yes this can cause the observed behavior (!).

So we should update the logic here surrounding this. This is identical behavior to inference --save-dir, which we have an existing Issue and TODO open for a related problem of removing previous results.

We may want to create uniformity is asset creation, so that any new assets are treated similarly to the training runs, with incremented directory names inside runs/. I'll add a TODO for this. Thank for raising the issue, this is an important bug!

**Comment by glenn-jocher** [comment]
TODO: standardize content creation across train.py, test.py, detect.py using the same incremented directory strategy that train.py uses (i.e. runs/exp0, runs/exp1), robust to --save-dir '' root directory argument.

Related to https://github.com/ultralytics/yolov5/issues/663

**Comment by MaxwellHogan** [comment]
Yeah I was looking through my notebook and I think that is what has occurred, glad to help, thanks for helping me track down the issue also

**Comment by constantinfite** [comment]
@MaxwellHogan 
yes, same as you , I trained my model and now I would like to evaluate my model on my test set only.
Here's my data.yaml file
![image](https://user-images.githubusercontent.com/57963890/98258178-d5e8a280-1f80-11eb-9ee8-6f671a76ff17.png)

I have this issue 
![image](https://user-images.githubusercontent.com/57963890/98258276-f4e73480-1f80-11eb-8e18-7f4f85e4fd2f.png)

Can you tell me what's the problem please ?

**Comment by MaxwellHogan** [comment]
@constantinfite 
there is no val set there bro, just test set

**Comment by glenn-jocher** [comment]
@MaxwellHogan ok I've thought this through. Our new idea is to handle train.py, test.py and detect.py uniformly the same way that we handle training runs now, by incrementing a --save-dir on each new run.

- train.py data will be saved to runs/exp0, runs/exp1 (current default)
- test.py data will be saved to runs/test0, runs/test1, etc.
- detect.py data will be saved to runs/detect0, runs/detect1, etc.
- no files or directories are deleted
- changing --save-dir from the default will prevent incrementing. i.e. `--save-dir new_dir` will create `yolov5/new_dir` if it does not exist, but if it already exists it will not alter it's contents (other than to overwrite any same-name files already present as it saves data). `yolov5/new_dir` will not be incremented on subsequent runs.

I'd like to get your feedback on this before we move forward. What do you think?

**Comment by MaxwellHogan** [comment]
@glenn-jocher sorry I was in a meeting, yeah that all sounds good

**Comment by glenn-jocher** [comment]
@MaxwellHogan ok. Will move forward with this this week.

**Comment by constantinfite** [comment]
@MaxwellHogan thank you, I would like to run test.py but for multiple confidence score, 
how to make a loop inside this function?

**Comment by MaxwellHogan** [comment]
@constantinfite depending on which OS, you can create a .bat file (windows) or a .sh file (mac/ubuntu) to run that python script again and again with different commands, you can google examples on how to do this, 

if you are using google colab, then you can do this using a python loop since you can run bash commands

**Comment by constantinfite** [comment]
@MaxwellHogan I had the same issue as you, I was trying to do a loop inside my file and it deleted all my yolov5 folder.
I'm on colab : I have to loop inside my file or in the colab cell ?

**Comment by MaxwellHogan** [comment]
I mean if you are modifying the python script I don't know what effect that will be having

if you simply want to run the script again and again with different confidences, you do just do it in the colab cell, make sure you define `--save-dir` as it me be set to your root directory as glenn-jocker stated above as that will be what is deleting the yolov5 folder (that is the case in the current version)

**Comment by MaxwellHogan** [comment]
@constantinfite let me know if setting `--save-dir` stops it from deleting your yolov5 dir

**Comment by constantinfite** [comment]
@MaxwellHogan thanks it works !
When i set --save-dir there is no problem

**Comment by glenn-jocher** [comment]
@MaxwellHogan these changes are now been pushed to master with PR #1322. Thank you for your feedback!
