### ISSUE TITLE
ModuleNotFoundError: No module named '_lzma'

### ISSUE THREAD

**Issue by orangezishuai** [ultralytics/yolov5#1298]
Input:
```
python train.py
```

Output:
```                                                                                                                 
Traceback (most recent call last):                                                                                                                                
  File "train.py", line 24, in <module>                                                                                                                           
    import test  # import test.py to get mAP after each epoch                                                                                                     
  File "/home/user3/yolov5/yolov5/test.py", line 13, in <module>                                                                                                  
    from models.experimental import attempt_load                                                                                                                  
  File "/home/user3/yolov5/yolov5/models/experimental.py", line 7, in <module>                                                                                    
    from models.common import Conv, DWConv                                                                                                                        
  File "/home/user3/yolov5/yolov5/models/common.py", line 9, in <module>                                                                                          
    from utils.datasets import letterbox                                                                                                                          
  File "/home/user3/yolov5/yolov5/utils/datasets.py", line 17, in <module>                                                                                        
    from utils.general import xyxy2xywh, xywh2xyxy, torch_distributed_zero_first                                                                                  
  File "/home/user3/yolov5/yolov5/utils/general.py", line 28, in <module>                                                                                         
    from utils.torch_utils import is_parallel, init_torch_seeds                                                                                                   
  File "/home/user3/yolov5/yolov5/utils/torch_utils.py", line 11, in <module>                                                                                     
    import torchvision                                                                                                                                            
  File "/usr/local/lib/python3.8/site-packages/torchvision/__init__.py", line 7, in <module>                                                                      
    from torchvision import datasets                                                                                                                              
  File "/usr/local/lib/python3.8/site-packages/torchvision/datasets/__init__.py", line 6, in <module>                                                             
    from .mnist import MNIST, EMNIST, FashionMNIST, KMNIST, QMNIST                                                                                                
  File "/usr/local/lib/python3.8/site-packages/torchvision/datasets/mnist.py", line 11, in <module>                                                               
    import lzma                                                                                                                                                   
  File "/usr/local/lib/python3.8/lzma.py", line 27, in <module>                                                                                                   
    from _lzma import *                                                                                                                                           
ModuleNotFoundError: No module named '_lzma'       
```

## Environment

 - OS: [centos7]
 - GPU [tesla v100]
 - python_version [3.8.3]
 - cuda [9.2]
 - torch [1.7.0]
 - torchvison [0.8.1]
 - yolov5 [v3.1]

## Solution
frist
```
yum install xz-devel
yum install python-backports-lzma
pip install backports.lzma
```
second
```
cd /usr/local/lib/python3.8
vi lzma.py 
```
finally
modify about line 27
```
try:
    from _lzma import *
    from _lzma import _encode_filter_properties, _decode_filter_properties
except ImportError:
    from backports.lzma import *
    from backports.lzma import _encode_filter_properties, _decode_filter_properties
```
it‘s work！

**Comment by yfzjay** [comment]
It works. Thanks!

**Comment by ashwindcruz** [comment]
Thanks for coming up with this fix!
I'm using a Debian system and so installing backports.lzma and its dependencies was slightly different.
The installation instructions here detail how it should be done for different OSs:
https://pypi.org/project/backports.lzma/

After installing backports.lzma, I carried out the file edit you mentioned and that removed the error.

**Comment by mboulwafa-aiox-labs** [comment]
```
sudo apt-get install libbz2-dev
sudo cp /usr/lib/python3.8/lib-dynload/_lzma.cpython-38-x86_64-linux-gnu.so /usr/local/lib/python3.8/
```

**Comment by eeezae** [comment]
after exec
```
yum install xz-devel
yum install python-backports-lzma
pip install backports.lzma
```
error occurred:

```
File "/usr/local/lib/python3.9/lzma.py", line 31, in <module>
    from backports.lzma import *
ModuleNotFoundError: No module named 'backports'
```

**Comment by adabuleanu** [comment]
Is there a fix delivered for this issue? I managed to get the workaround working with python 3.8 on centos 7, but this looks kind of "hackish".

**Comment by glenn-jocher** [comment]
@adabuleanu @eeezae @orangezishuai this seems to be a torch issue as the error message originated on `import torchvision`. In this case I would raise this issue directly on the pytorch repository:
https://github.com/pytorch/pytorch

**Comment by Siam-Rayhan1** [comment]
I made a kivymd apk using github actions. And i'm getting the same error. By following this steps how do i solve my problem.Because i can't find lzma.py in my repositories root directory. And if i mention the path (got from error) it shows that no file or directory. 
Please help me to solve that.Please please

**Comment by glenn-jocher** [comment]
@Siam-Rayhan1 thanks for reaching out. The issue you're facing seems to be related to the absence of the `lzma` module. This module is typically included in the standard library and should be available on most systems. 

If you're unable to find the `lzma.py` file in your repository root directory and specifying the path isn't working either, it's possible that the module is missing or not installed in your environment. 

To resolve this, you can try reinstalling the Python `backports.lzma` package. Below are the steps:

1. Install the `liblzma` development package:
   ```
   sudo apt-get install liblzma-dev
   ```

2. Install the `backports.lzma` package:
   ```
   pip install backports.lzma
   ```

This should ensure that the `lzma` module is installed and available in your environment. Give it a try and let me know if you still encounter any issues.

Note: If you are still facing issues after following these steps, it would be helpful to know the specific details of your setup, such as the operating system, Python version, and any relevant error messages. This will assist in further troubleshooting.

**Comment by Siam-Rayhan1** [comment]
> @Siam-Rayhan1 thanks for reaching out. The issue you're facing seems to be related to the absence of the `lzma` module. This module is typically included in the standard library and should be available on most systems. 
> 
> If you're unable to find the `lzma.py` file in your repository root directory and specifying the path isn't working either, it's possible that the module is missing or not installed in your environment. 
> 
> To resolve this, you can try reinstalling the Python `backports.lzma` package. Below are the steps:
> 
> 1. Install the `liblzma` development package:
>    ```
>    sudo apt-get install liblzma-dev
>    ```
> 
> 2. Install the `backports.lzma` package:
>    ```
>    pip install backports.lzma
>    ```
> 
> This should ensure that the `lzma` module is installed and available in your environment. Give it a try and let me know if you still encounter any issues.
> 
> Note: If you are still facing issues after following these steps, it would be helpful to know the specific details of your setup, such as the operating system, Python version, and any relevant error messages. This will assist in further troubleshooting.





Basically I'm making an app using Pythons kivy and kivymd frame work.In my app I'm using instaloader module.Using Github Action (CI) I'm converting my app to apk.
After converting,when i try to open my apk it crashes immediately. 
Here's my ```Debug Log```

```
I/python ( 8065): Traceback (most recent call last): 
I/python ( 8065): File "/github/workspace/.buildozer/android/app/main.py", line 9, in <module> I/python ( 8065): File "/github/workspace/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/stalkgram/arm64-v8a/instaloader/__init__.py", line 16, in <module> 
I/python ( 8065): File "/github/workspace/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/stalkgram/arm64-v8a/instaloader/instaloader.py", line 24, in <module> 
I/python ( 8065): File "/github/workspace/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/stalkgram/arm64-v8a/instaloader/nodeiterator.py", line 7, in <module> 
I/python ( 8065): File "<frozen zipimport>", line 259, in load_module 
I/python ( 8065): File "/github/workspace/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/python3/arm64-v8a__ndk_target_21/python3/Lib/lzma.py", line 27, in <module> 
I/python ( 8065): ModuleNotFoundError: No module named '_lzma' I/python ( 8065): Python for android ended.
```

Here's my ```build.yml``` (CI)
```
name: CI
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install _lzma
        run: |
          sudo apt-get install python3
          pip install instaloader
          pip install backports.lzma
          sudo apt-get install lzma
          sudo apt-get install liblzma-dev
          sudo apt-get install libbz2-dev

      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash

      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - uses: actions/cache@v2
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

      - name: Install AIDL
        run: |
          sudo apt-get update
          sudo apt-get install build-essential
          sudo apt-get install libstdc++6
          sudo apt-get install aidl

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: master

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
```
Here's my  ```buildozer.spec``` requirements.
```requirements = python3==3.9.10,hostpython3==3.9.10,kivy==2.1.0,pillow,kivymd==1.1.1,certifi,android,instaloader==4.10.1,plyer==2.1.0```

**Comment by glenn-jocher** [comment]
@Siam-Rayhan1 it seems that the issue you're encountering is related to the absence of the `_lzma` module. This problem can arise when building an APK using PyInstaller or PyInstaller-based tools such as Buildozer, which can sometimes miss the required libraries.

In your case, the error message suggests that the `_lzma` module is missing, which is causing the app to crash immediately upon opening. To resolve this, you can try the following steps:

1. Install the required dependencies:
- Add the following packages to the `sudo apt-get install` command in your workflow:
  ```
  sudo apt-get install xz-utils
  sudo apt-get install liblzma-dev
  ```

2. Install the `backports.lzma` package:
- This package provides a backport of the `lzma` module and can help resolve any potential module-related issues.
  ```
  pip install backports.lzma
  ```

By following these steps, you should be able to resolve the `No module named '_lzma'` error and prevent the immediate crashing of your APK. Remember to rebuild and test your APK after making these changes.

If you continue to encounter issues after trying these steps, please provide additional details about your setup, such as the version of Buildozer or PyInstaller you're using, as well as any relevant error messages. This will assist in further troubleshooting.

**Comment by Siam-Rayhan1** [comment]
> @Siam-Rayhan1 it seems that the issue you're encountering is related to the absence of the `_lzma` module. This problem can arise when building an APK using PyInstaller or PyInstaller-based tools such as Buildozer, which can sometimes miss the required libraries.
> 
> In your case, the error message suggests that the `_lzma` module is missing, which is causing the app to crash immediately upon opening. To resolve this, you can try the following steps:
> 
> 1. Install the required dependencies:
> - Add the following packages to the `sudo apt-get install` command in your workflow:
>   ```
>   sudo apt-get install xz-utils
>   sudo apt-get install liblzma-dev
>   ```
> 
> 2. Install the `backports.lzma` package:
> - This package provides a backport of the `lzma` module and can help resolve any potential module-related issues.
>   ```
>   pip install backports.lzma
>   ```
> 
> By following these steps, you should be able to resolve the `No module named '_lzma'` error and prevent the immediate crashing of your APK. Remember to rebuild and test your APK after making these changes.
> 
> If you continue to encounter issues after trying these steps, please provide additional details about your setup, such as the version of Buildozer or PyInstaller you're using, as well as any relevant error messages. This will assist in further troubleshooting.

Still getting the same error. 
I'm using the latest ubuntu version and latest Python3 as i mentioned earlier

**Comment by glenn-jocher** [comment]
@Siam-Rayhan1 it seems that the suggested steps did not resolve the error you're experiencing. To further investigate the issue, please provide additional details about your setup, such as the specific versions of Buildozer or PyInstaller you are using. Additionally, any relevant error messages or logs would be helpful in troubleshooting the problem. With this information, we can provide more specific and targeted assistance. Thank you.

**Comment by Siam-Rayhan1** [comment]
> @Siam-Rayhan1 it seems that the suggested steps did not resolve the error you're experiencing. To further investigate the issue, please provide additional details about your setup, such as the specific versions of Buildozer or PyInstaller you are using. Additionally, any relevant error messages or logs would be helpful in troubleshooting the problem. With this information, we can provide more specific and targeted assistance. Thank you.

Buildozer == latest 
Python == 3.9.10
Ubuntu == latest 
Environment Github Actions
Using instaloader module (latest)[which requires lzma actually)
That's all from my side

**Comment by glenn-jocher** [comment]
@Siam-Rayhan1 i appreciate you providing the additional details about your setup. Based on the information you've provided, it seems like you're using the latest version of Buildozer and Python 3.9.10 on Ubuntu. You're also using the instaloader module, which requires the lzma module.

To further troubleshoot the issue, it would be helpful if you could provide any relevant error messages or logs that you have encountered. This will allow us to better understand the specific problem you're facing and provide more targeted assistance.

Thank you for your cooperation, and we'll do our best to help you resolve the issue.

**Comment by rama19998** [comment]
Traceback (most recent call last):
  File "C:/Users/rama2/.nuke/NukeDepthCrafter/menu.py", line 1, in <module>
    from nukedc import UpdateBtn, CreateDCNode, GenerateDepthAction
  File "C:\Program Files\Nuke15.1v3\pythonextensions\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users/rama2/.nuke/NukeDepthCrafter\nukedc.py", line 2, in <module>
    from DepthCrafterPlugin.utils import *
  File "C:\Program Files\Nuke15.1v3\pythonextensions\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users/rama12/.nuke/NukeDepthCrafter\DepthCrafterPlugin\utils.py", line 5, in <module>
    import numpy as np
  File "C:\Program Files\Nuke15.1v3\pythonextensions\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'numpy'


Please help me to solve .Please

**Comment by pderrenger** [comment]
@rama19998 it looks like the `numpy` module is missing. You can install it using `pip install numpy`. If the issue persists, ensure your Python environment is correctly set up.
