### ISSUE TITLE
Confusion Matrix wrong output

### ISSUE THREAD

**Issue by IbrahimAlmasri01** [ultralytics/yolov5#12982]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, 
I trained my model on 3000 images containing one class, with backgrounds.

When I do the validation, the confusion matrix shows that my model detects objects with 100% in backgrounds. Even though it doesn't really do that, since I did an inference and it doesn't detect anything in the empty images (background).

How can I solve this problem?

**Comment by glenn-jocher** [comment]
Hello! Thanks for reaching out with your inquiry about the confusion matrix output 😊.

It looks like there might be a mismatch between your validation data labeling and the predictions during the evaluation. Here’s a short checklist to help you debug the issue:

1. **Verify Labels**: Double-check your background validation images to ensure they are correctly labeled with no objects.
2. **Model Check**: Ensure the model weights used during validation are indeed the ones intended and correspond to the correct training checkpoint.
3. **Evaluation Script**: Review the evaluation script, specifically how the confusion matrix is populated, to confirm it correctly handles cases with no detections.

If everything seems correct and the issue persists, you might want to adjust the confidence threshold temporarily to see if low-confidence detections are inadvertently affecting the matrix.

Feel free to follow up if the problem remains unresolved! 😊
