### ISSUE TITLE
multi-scale

### ISSUE THREAD

**Issue by hasuoshenyun** [ultralytics/yolov5#1299]
## ❔Question
Thanks! In the part of 'multi-scale' in train.py , I find that:                
       sz = random.randrange(imgsz * 0.5, imgsz * 1.5 + gs) // gs * gs  # size      
 Should not it be that as floows?
       sz = random.randrange(imgsz * 0.5, imgsz * 1.5 , gs) // gs * gs  # size

**Comment by glenn-jocher** [comment]
@hasuoshenyun not sure. The goal here is to produce random sizes `sz` that are gs-multiples (gs typically equals 32) between 50% and 150% of the image size `imgsz`. The // produces integer division, but I see the 3rd argument may help do this for us? It looks like the max value is not inclusive in this case (i.e. 960):

```python
imgsz=640
gs=32
max([random.randrange(imgsz * 0.5, imgsz * 1.5, gs) for i in range(1000)])
928
```

https://www.geeksforgeeks.org/randrange-in-python/
