### ISSUE TITLE
Extract information of Coordinates

### ISSUE THREAD

**Issue by vishaltala** [ultralytics/yolov5#12998]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Once the Object is detected, how can i extract the information like confidence score, label and all the 4 coordinates ?

**Comment by glenn-jocher** [comment]
@vishaltala hello!

To extract confidence scores, labels, and coordinates once an object is detected, you can use the outputs from your model after processing an image. Here's a snippet showing how to do this.

If you've run the detection using the standard `detect.py`, results are stored in a list of detections, where each detection includes x1, y1, x2, y2 coordinates, confidence and class. Here's a simple example to access this info:

```python
# Assuming results are the output from a model
results = model(img)  # 'img' is your input image
for det in results.xyxy[0]:  # detections per image
    x1, y1, x2, y2, conf, cls = det
    print(f"Coordinates: ({x1}, {y1}), ({x2}, {y2})")
    print(f"Confidence: {conf}")
    print(f"Class: {int(cls)}")
```
This loop will print the bounding box coordinates, confidence score, and class ID for each detection in the image.

Hope this helps! 😊
