### ISSUE TITLE
How to get state_dict of pretrained weight

### ISSUE THREAD

**Issue by magicffourier** [ultralytics/yolov5#13]
I was trying to inference the yolov5x model and I found your pretrained weight save the whole model, which make `torch.load` function rely on the relative path of yolov5x.yaml.
And I have tried to load weight like this:
`model = Model(r'models/yolov5x.yaml')
trained_model = torch.load(opt.weights, map_location=device)['model'].to(device).eval()
model.load_state_dict(trained_model.state_dict())
model.to(device).eval()
`
But I found that the inference outputs of the two models are different

**Comment by glenn-jocher** [comment]
@magicffourier yes, checkpoints are saved as full models. The alternative is to save a state_dict, which the user would need to manually pair with a configuration file. We use the 2 file approach in https://github.com/ultralytics/yolov3 but have moved away from this on purpose, as too many people would fail to supply correct pairs of files, then raise issues on the repo for what they perceived as a bug when their incorrect pairing triggered errors (i.e. `python detect.py --weights yolov3-spp.pt --cfg yolov3.cfg`)
