### ISSUE TITLE
About the hyperparameter settings of u5 and u3 versions

### ISSUE THREAD

**Issue by xiaozhangya** [ultralytics/yolov5#1300]
## ❔Question
About the hyperparameter settings of u5 and u3 versions

## Additional context
The hyperparameter settings of the u3 version are as follows:
Can explain why the values of GIOU, cls, and obj are set, thank you.
 {'giou': 3.54,  # giou loss gain
       'cls': 37.4,  # cls loss gain
       'cls_pw': 1.0,  # cls BCELoss positive_weight
       'obj': 64.3,  # obj loss gain (*=img_size/320 if img_size != 320)
       'obj_pw': 1.0,  # obj BCELoss positive_weight

**Comment by glenn-jocher** [comment]
@xiaozhangya the hyperparameter values are not 'set' by anyone. The values are obtained via hyperparameter evolution. See hyperparameter evolution tutorial for more information.
https://docs.ultralytics.com/yolov5

**Comment by xiaozhangya** [comment]
> @xiaozhangya超参数值未被任何人“设置”。这些值是通过超参数演化获得的。有关更多信息，请参见超参数演化教程。
> https://docs.ultralytics.com/yolov5

So why are the hyperparameters of giou, obj and CLS in U3 and U5 versions so different。Can you explain the meaning of the numbers of these three parameters in the U3 version? Sincere thanks

The hyperparameter settings of the u3 version are as follows:
Can explain why the values of GIOU, cls, and obj are set, thank you.
{'giou': 3.54, # giou loss gain
'cls': 37.4, # cls loss gain
'cls_pw': 1.0, # cls BCELoss positive_weight
'obj': 64.3, # obj loss gain (*=img_size/320 if img_size != 320)
'obj_pw': 1.0, # obj BCELoss positive_weight
