### ISSUE TITLE
 Problem running inference on YOLOv5s for custom trained model using Python

### ISSUE THREAD

**Issue by iamstrang3** [ultralytics/yolov5#13011]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I’m having trouble running inference on a custom-trained YOLOv5s model using Python. I’ve trained the model with my own dataset and saved the weights as best.pt. When I try to run inference on a new image or video, I encounter issues. I keep getting this error:
ImportError: cannot import name 'plot_one_box' from 'utils.plots'

Can you please help me!

**Comment by glenn-jocher** [comment]
Hey there! 😊 It looks like there's an issue with importing a function from the utilities module. The `plot_one_box` function should be available in the `utils.plots` file. Here’s a suggestion to fix the ImportError:

1. **Check your file structure**: Ensure that the `utils/plots.py` file exists in your working directory and that it indeed contains the `plot_one_box` function.
2. **Verify your import statement**: Make sure the import statement in your script correctly points to the `plot_one_box` function. It should look like this:
   
   ```python
   from utils.plots import plot_one_box
   ```

If those steps don’t resolve your issue, it might be helpful to pull the latest version of the YOLOv5 repository to make sure you have all the updated files.

If the problem persists, please feel free to share more specifics from your error log or code snippets, and we'll dive deeper! 🚀
