### ISSUE TITLE
No module named 'models'

### ISSUE THREAD

**Issue by zyad630** [ultralytics/yolov5#13021]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

this is code :
import cv2
import math
import torch
import pygame
from models.experimental import attempt_load
from utils.general import non_max_suppression, scale_coords
from utils.torch_utils import select_device

# Initialize Pygame and Pygame Mixer
pygame.init()
pygame.mixer.init()
Sound = pygame.mixer.Sound(r"C:\Users\ITC\Downloads\mixkit-alert-alarm-1005.wav")

# Initialize YOLOv5
device = select_device('')
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True, force_reload=True)
model = attempt_load(r'C:\Users\ITC\Downloads\best.pt', map_location=device)
stride = int(model.stride.max())  # model stride
names = model.module.names if hasattr(model, 'module') else model.names

cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()
    img = frame.copy()
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # Inference
    img = torch.from_numpy(img).to(device)
    img = img.float()  # uint8 to fp16/32
    img /= 255.0  # 0 - 255 to 0.0 - 1.0
    if img.ndimension() == 3:
        img = img.unsqueeze(0)

    # Predict
    pred = model(img)[0]
    pred = non_max_suppression(pred, 0.5, 0.4)

    for i, det in enumerate(pred):
        if len(det):
            det[:, :4] = scale_coords(img.shape[2:], det[:, :4], frame.shape).round()

            for *xyxy, conf, cls in reversed(det):
                c = int(cls)
                confidence = conf.item() * 100
                if confidence > 50 and names[c] == 'person':  # Change to 'human' if that's your class name
                    x1, y1, x2, y2 = [int(i) for i in xyxy]
                    cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 0, 255), 5)
                    cv2.putText(frame, f'{names[c]} {confidence:.2f}%', (x1 + 8, y1 + 100), cv2.FONT_HERSHEY_SIMPLEX,
                                1, (255, 0, 0), 2)

                    # Add your Pygame sound logic here
                    pygame.mixer.Sound.play(Sound)
                    # You might need to add logic to stop sound when there's no detection

    cv2.imshow("command", frame)
    if cv2.waitKey(1) == ord('a'):
        break

cap.release()
cv2.destroyAllWindows()
and this is the error in juputer

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[7], line 5
      3 import torch
      4 import pygame
----> 5 from models.experimental import attempt_load
      6 from utils.general import non_max_suppression, scale_coords
      7 from utils.torch_utils import select_device

ModuleNotFoundError: No module named 'models'

**Comment by glenn-jocher** [comment]
Hey there! 🚀 It looks like your script is unable to locate the `models` module which is typically part of the directory structure. One common cause is not being in the correct directory when running your Jupyter notebook or your environment not being set up properly.

Ensure that you're running the Jupyter Notebook in the root directory of your cloned `yolov5` repository. Alternatively, you can adjust your sys path at the beginning of your script to include the root directory of YOLOv5:

```python
import sys
sys.path.append('path_to_yolov5')

from models.experimental import attempt_load
# Your other import statements and code follow here
```

Make sure to replace `'path_to_yolov5'` with the path to your YOLOv5 directory. This adjustment tells Python to include your specified directory in its search for modules.

Hope this helps! Let me know if there's anything else you need. 😊
