### ISSUE TITLE
Does YOLO perform object detection on jp2 image format?

### ISSUE THREAD

**Issue by Rjaat** [ultralytics/yolov5#13031]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to perform object detection on jp2 images.
Does YOLO support object detection on the said image format?

**Comment by glenn-jocher** [comment]
Hello! YOLOv5 primarily supports image formats that are natively handled by the PIL library, such as JPEG, PNG, BMP, and others. The JP2 (JPEG 2000) format isn't directly supported out-of-the-box.

However, you can easily convert JP2 images to a supported format like JPEG or PNG using libraries such as OpenCV or PIL before feeding them into the model. Here’s a quick example using PIL:

```python
from PIL import Image

# Load JP2 image
img = Image.open('image.jp2')

# Convert to JPEG
img.save('image.jpeg', 'JPEG')
```

After converting, you can then proceed with using the saved JPEG image for detection with YOLOv5. Hope this helps! 😊
