### ISSUE TITLE
where is yolov5 v7.0 --trian in export.py?

### ISSUE THREAD

**Issue by vtfate** [ultralytics/yolov5#13037]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

 In yolov5 6.2 has --train to set train mode, but v7.0 is disappear？

### Additional

help

**Comment by glenn-jocher** [comment]
Hello! In YOLOv5 v7.0, the `--train` flag in `export.py` has indeed been removed as part of a simplification and optimization process. If you need to perform operations that were previously handled by this flag, you might need to adjust your workflow or use other flags and settings that are available in the latest version.

For handling model exports and understanding the changes in command-line options, you can refer to the updated documentation and examples on the [YOLOv5 Documentation](https://docs.ultralytics.com/yolov5/). This should help guide you through the new setup. If you have specific requirements or further questions, feel free to ask! 😊
