### ISSUE TITLE
Can I evolve particular hyperparameters only?

### ISSUE THREAD

**Issue by NazmulTakbir** [ultralytics/yolov5#1304]
## ❔Question
I want hyperparameter evolution to mutate the following parameters only - 'box', 'cls', 'cls_pw', 'obj', 'obj_pw'. I want the values of all the other hyperparameters to stay constant. How can I do this?

**Comment by glenn-jocher** [comment]
@NazmulTakbir yes. You control the variation of each hyperparameter using the meta dictionary. If you set the mutation scale to zero, that parameter will not vary.
https://github.com/ultralytics/yolov5/blob/bd5cfff8fbdcc079ff901cb7c99fab916be06f57/train.py#L486-L515

**Comment by glenn-jocher** [comment]
@NazmulTakbir see hyperparameter evolution tutorial for more info:
https://docs.ultralytics.com/yolov5

**Comment by NazmulTakbir** [comment]
@glenn-jocher What about the lower_limit and upper_limit for the hyperparameters I do not want to vary. Suppose I want lr0 to always be 0.01
In this case should it be like this : 'lr0' : (0, 0.01, 0.01)   --   basically providing the same value for upper_limit and lower_limit

**Comment by glenn-jocher** [comment]
@NazmulTakbir the limits only apply if your freezed hyperparameter starts outside of their bounds, which i doubt would be the case.

So in summary all you need to do is set the meta dictionary tuples you want to freeze to zero for the first entry: (0, ..., ...)
