### ISSUE TITLE
How to Show Real-Time Detection of Multiple Streams Using Titled Display Windows in Yolov5?

### ISSUE THREAD

**Issue by fasih0001** [ultralytics/yolov5#13063]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to shows the real time detection results from multiple input streams in a tiled display structure? How can I do this? The following is a screenshot of what I exactly want.
![Screenshot from 2024-06-03 15-47-19](https://github.com/ultralytics/yolov5/assets/58459324/2508a427-033c-4b54-8cb3-c6f745c2b1a5)

**Comment by glenn-jocher** [comment]
Hello!

Thanks for reaching out with your question. To display real-time detection results from multiple streams in a tiled window setup using YOLOv5, you can follow these steps:

1. **Capture Streams**: Use OpenCV to capture video streams. You can create multiple `cv2.VideoCapture` instances for each stream.

2. **Perform Detection**: For each frame in each stream, use YOLOv5 to perform detection. You can do this by passing the frames to the model's inference function.

3. **Combine Frames**: After detection, you'll have frames with bounding boxes drawn. You can use `cv2.hconcat` and `cv2.vconcat` to stitch these frames together into a tiled layout.

4. **Display Tiled Frames**: Use `cv2.imshow` to display the combined tiled frames.

Here's a basic snippet to guide you:

```python
import cv2
from yolov5 import YOLOv5

# Load your pre-trained model
model = YOLOv5("path_to_your_model")

# Capture video streams
cap1 = cv2.VideoCapture('stream1_url')
cap2 = cv2.VideoCapture('stream2_url')

while True:
    ret1, frame1 = cap1.read()
    ret2, frame2 = cap2.read()

    if not ret1 or not ret2:
        break

    # Perform detection
    results1 = model(frame1)
    results2 = model(frame2)

    # Draw detections
    frame1 = results1.render()[0]
    frame2 = results2.render()[0]

    # Combine frames into a tiled display
    combined_frame = cv2.hconcat([frame1, frame2])

    # Display the tiled frames
    cv2.imshow('Tiled Detection', combined_frame)

    if cv2.waitKey(1) == ord('q'):
        break

cap1.release()
cap2.release()
cv2.destroyAllWindows()
```

Adjust the number of streams and the arrangement of tiles as needed. If you have any more questions or need further assistance, feel free to ask. Happy coding! 🚀

**Comment by fasih0001** [comment]
It would be really nice if you could guide me where in the detect.py I can modify to add the functionality of tiled window setup?

**Comment by glenn-jocher** [comment]
Hello!

To integrate a tiled window setup directly into the `detect.py` script, you'll want to modify the section where frames are processed and displayed. Here’s a brief guide:

1. **Capture and Process Multiple Streams**: You'll need to adjust the source input to handle multiple streams. This might involve modifying the `source` parameter to accept multiple inputs and setting up a loop to handle each stream.

2. **Modify Display Section**: In the part of the script where `cv2.imshow` is used to display results, replace it with a function that combines frames from multiple sources into a single window. You can use `cv2.hconcat` and `cv2.vconcat` for horizontal and vertical stacking.

3. **Rendering Combined Frames**: After detection, render the detections on each frame, combine them as described, and then display the combined frame.

Look for the loop where frames are read and processed, and integrate your changes there. This will involve some custom coding to ensure synchronization and proper layout of the video feeds.

If you need more detailed guidance on the code modifications, feel free to ask. Happy coding! 🚀
