### ISSUE TITLE
Can YOLOv5 .pt and .yaml convert to YOLOv4 .weights and .cfg?

### ISSUE THREAD

**Issue by yao-zheng-yi** [ultralytics/yolov5#1306]
I use YOLOv5 model and YOLOv4 model in Android app. I use NCNN to convert YOLOv5 .pt and YOLOv4-tiny .weights to Android .bin and .param. But in NCNN, use YOLOv5 in Android to detect need postprocessing so it's FPS smaller than YOLOv4-tiny. 
So I want to convert YOLOv5 models to YOLOv4 models,  is there a way to convert .weights to .pt and .yaml to .cfg?

**Comment by zhangjinsong3** [comment]
> I use YOLOv5 model and YOLOv4 model in Android app. I use NCNN to convert YOLOv5 .pt and YOLOv4-tiny .weights to Android .bin and .param. But in NCNN, use YOLOv5 in Android to detect need postprocessing so it's FPS smaller than YOLOv4-tiny.
> So I want to convert YOLOv5 models to YOLOv4 models, is there a way to convert .weights to .pt and .yaml to .cfg?

Maybe U can try this repo: https://github.com/enazoe/yolo-tensorrt

**Comment by siyangxie** [comment]
I don't think it's possible cuz even if v5 and v4 are similar but they're still different structures. If you're talking about converting between weight formats, yes I think it's possible by using ONNX->TRT.

**Comment by yao-zheng-yi** [comment]
> > I use YOLOv5 model and YOLOv4 model in Android app. I use NCNN to convert YOLOv5 .pt and YOLOv4-tiny .weights to Android .bin and .param. But in NCNN, use YOLOv5 in Android to detect need postprocessing so it's FPS smaller than YOLOv4-tiny.
> > So I want to convert YOLOv5 models to YOLOv4 models, is there a way to convert .weights to .pt and .yaml to .cfg?
> 
> Maybe U can try this repo: https://github.com/enazoe/yolo-tensorrt

I have tried, and I got the yolov5s.weights and yolov5s.cfg. Unfortunately when I use NCNN convert then to .bin and .param, it didn't success.

**Comment by yao-zheng-yi** [comment]
> I don't think it's possible cuz even if v5 and v4 are similar but they're still different structures. If you're talking about converting between weight formats, yes I think it's possible by using ONNX->TRT.

https://github.com/ultralytics/yolov3/blob/master/models.py can convert YOLOv3 .pt to .weights, it needs .cfg, but how can I convert .yaml to .cfg? I found they are different.

**Comment by zhangjinsong3** [comment]
> > > I use YOLOv5 model and YOLOv4 model in Android app. I use NCNN to convert YOLOv5 .pt and YOLOv4-tiny .weights to Android .bin and .param. But in NCNN, use YOLOv5 in Android to detect need postprocessing so it's FPS smaller than YOLOv4-tiny.
> > > So I want to convert YOLOv5 models to YOLOv4 models, is there a way to convert .weights to .pt and .yaml to .cfg?
> > 
> > 
> > Maybe U can try this repo: https://github.com/enazoe/yolo-tensorrt
> 
> I have tried, and I got the yolov5s.weights and yolov5s.cfg. Unfortunately when I use NCNN convert then to .bin and .param, it didn't success.

There is a yolov5 example in ncnn. And somebody find the way `yolov5.pth -> onnx -> ncnn` feasible. 
https://github.com/Tencent/ncnn/issues/2226

**Comment by yao-zheng-yi** [comment]
> > > > I use YOLOv5 model and YOLOv4 model in Android app. I use NCNN to convert YOLOv5 .pt and YOLOv4-tiny .weights to Android .bin and .param. But in NCNN, use YOLOv5 in Android to detect need postprocessing so it's FPS smaller than YOLOv4-tiny.
> > > > So I want to convert YOLOv5 models to YOLOv4 models, is there a way to convert .weights to .pt and .yaml to .cfg?
> > > 
> > > 
> > > Maybe U can try this repo: https://github.com/enazoe/yolo-tensorrt
> > 
> > 
> > I have tried, and I got the yolov5s.weights and yolov5s.cfg. Unfortunately when I use NCNN convert then to .bin and .param, it didn't success.
> 
> There is a yolov5 example in ncnn. And somebody find the way `yolov5.pth -> onnx -> ncnn` feasible.
> [Tencent/ncnn#2226](https://github.com/Tencent/ncnn/issues/2226)

I know how to use NCNN convert yolov5s.pt -> onnx -> ncnn, in this way YOLOv5's FPS only 4-6， because YOLOv5 detect need  postprocessing, it cost much time so YOLOv5 slower than YOLOv4-tiny. What I want to do is convert v5 models to v4 models to increase v5's FPS.(不知道我有没有讲清楚......）

**Comment by nihui** [comment]
https://zhuanlan.zhihu.com/p/275989233

yolov5 ncnn implementation

**Comment by yao-zheng-yi** [comment]
> https://zhuanlan.zhihu.com/p/275989233
> 
> yolov5 ncnn implementation

Thanks！

**Comment by yao-zheng-yi** [comment]
I want to know wether YOLOv5 models can convert to YOLOv4 models？What do you think？ @glenn-jocher

**Comment by Calviansyah** [comment]
@glenn-jocher hey iwanna ask again, sorry. If we want run yolov3 and yolov4, we insert cfg to the program right i mean in text editor, so what about yolo v5 who use formal yml??should i convert to ONNX or weights from .pt?or just convert .pt to yaml thanks

**Comment by Calviansyah** [comment]
> > > I use YOLOv5 model and YOLOv4 model in Android app. I use NCNN to convert YOLOv5 .pt and YOLOv4-tiny .weights to Android .bin and .param. But in NCNN, use YOLOv5 in Android to detect need postprocessing so it's FPS smaller than YOLOv4-tiny.
> > > So I want to convert YOLOv5 models to YOLOv4 models, is there a way to convert .weights to .pt and .yaml to .cfg?
> > 
> > 
> > Maybe U can try this repo: https://github.com/enazoe/yolo-tensorrt
> 
> I have tried, and I got the yolov5s.weights and yolov5s.cfg. Unfortunately when I use NCNN convert then to .bin and .param, it didn't success.

what kind of v5 format do you use?.pt or yaml? and how you convert it? thanks? where did you get the cfg, as far  i know from ultralytics they dont give the cfg thanks

**Comment by glenn-jocher** [comment]
@Calviansyah 👋 Hello! Thanks for asking about YOLOv5 🚀 **architecture visualization**. We've made visualizing YOLOv5 🚀 architectures super easy. There are 3 main ways:

## `model.yaml`

Each model has a corresponding yaml file that displays the model architecture. Here is YOLOv5s, defined by `yolov5s.yaml`:
https://github.com/ultralytics/yolov5/blob/1a3ecb8b386115fd22129eaf0760157b161efac7/models/yolov5s.yaml#L12-L48

## TensorBoard Graph

Simply start training a model, and then view the TensorBoard Graph for an interactive view of the model architecture. This example shows YOLOv5s viewed in our [Notebook](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb) –  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

```python
# Tensorboard
%load_ext tensorboard
%tensorboard --logdir runs/train

# Train YOLOv5s on COCO128 for 3 epochs
python train.py --weights yolov5s.pt --epochs 3
```

<img width="893" alt="Screenshot 2021-04-11 at 01 10 09" src="https://user-images.githubusercontent.com/26833433/114286928-349bd600-9a63-11eb-941f-7139ee6cd602.png">

## Netron viewer

Use [https://netron.app](https://netron.app/) to view exported ONNX models:

```
python export.py --weights yolov5s.pt --include onnx --simplify
```

<img width="890" alt="Screen Shot 2022-04-29 at 11 09 23 AM" src="https://user-images.githubusercontent.com/26833433/165999628-0d6095ce-58dd-49b7-a04e-25d0995e5493.png">


Good luck 🍀 and let us know if you have any other questions!
