### ISSUE TITLE
YOLOv5s Custom Model Inference in Raspberry Pi 4 Model B

### ISSUE THREAD

**Issue by unraxesy** [ultralytics/yolov5#13087]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi everyone and @glenn-jocher !
I have my own custom model `best.pt` that have been trained with my custom dataset. The dataset is done using Roboflow and the model is trained with Google Colab (local). All the data after training was saved on my PC. Now, I want to try inference on my Raspberry Pi, but I got some questions.

### QUESTIONS
1. Should I use local YOLOv5 repository that I used for training (copy the YOLOv5 local directory from my PC to Raspberry), or should I do YOLOv5 git clone (GitHub repo) on my Raspberry Pi?
2. If copying local repository is the answer (since it contains crucial files including best.pt (custom model), data.yaml (dataset yaml), and etc), what if it isn't the latest one? How do I update the local repository?
3. Should I use `model = torch.hub.load("ultralytics/yolov5", "custom", path="path/to/best.pt")` or `model = torch.hub.load("path/to/yolov5", "custom", path="path/to/best.pt", source="local")` if I want to try inference on Raspberry Pi? What is the difference between using local resource and ultralytics/yolov5?
4. There are some unique files including `data.yaml` (/yolov5/datasets/data.yaml) and `custom_yolov5s.yaml` (/yolov5/models/custom_yolov5s.yaml). Is YOLOv5 automatically called them? Because we don't define them unlike `best.pt`.

Thank you!

**Comment by glenn-jocher** [comment]
@unraxesy hello!

Thank you for your detailed questions regarding running YOLOv5 inference on a Raspberry Pi 4 Model B. Let's address each of your queries:

1. **Repository Setup on Raspberry Pi**:
   - It is generally recommended to clone the YOLOv5 repository directly on your Raspberry Pi using the command:
     ```bash
     git clone https://github.com/ultralytics/yolov5
     cd yolov5
     pip install -r requirements.txt
     ```
     This ensures you have the latest version of YOLOv5 and all necessary dependencies. You can then copy your custom model (`best.pt`), `data.yaml`, and any other custom files to the appropriate directories within this cloned repository.

2. **Updating Local Repository**:
   - If you decide to copy your local repository, you can update it by navigating to the repository directory and running:
     ```bash
     git pull origin master
     pip install -r requirements.txt
     ```
     This will fetch and integrate the latest changes from the YOLOv5 GitHub repository.

3. **Model Loading for Inference**:
   - For inference, you can use either of the following commands:
     ```python
     model = torch.hub.load("ultralytics/yolov5", "custom", path="path/to/best.pt")
     ```
     or
     ```python
     model = torch.hub.load("path/to/yolov5", "custom", path="path/to/best.pt", source="local")
     ```
     The first command loads the model from the Ultralytics GitHub repository, while the second command loads it from your local repository. If you have made custom modifications to the YOLOv5 code, you should use the local source option.

4. **Handling Custom Files (`data.yaml` and `custom_yolov5s.yaml`)**:
   - YOLOv5 does not automatically load `data.yaml` or custom model configuration files unless explicitly specified in your training or inference commands. Ensure that your `data.yaml` and custom model configuration files are correctly referenced in your scripts. For example, during training, you would specify the path to `data.yaml`:
     ```bash
     python train.py --data path/to/data.yaml --cfg path/to/custom_yolov5s.yaml --weights path/to/best.pt
     ```

For more detailed guidance on exporting and using YOLOv5 models, you can refer to the [YOLOv5 Model Export Tutorial](https://docs.ultralytics.com/yolov5/tutorials/model_export/).

If you encounter any issues or have further questions, please provide a minimum reproducible example as outlined [here](https://docs.ultralytics.com/help/minimum_reproducible_example). This will help us better understand and address your concerns.

Best of luck with your project on the Raspberry Pi! 😊
