### ISSUE TITLE
runtime error:permission denied

### ISSUE THREAD

**Issue by mdh31** [ultralytics/yolov5#13099]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi 
I want to run train with GPU like this.
01:00.0 VGA compatible controller: NVIDIA Corporation GA102 [GeForce RTX 3090] (rev a1)
02:00.0 VGA compatible controller: NVIDIA Corporation GA102 [GeForce RTX 3090] (rev a1)

My command line:
$ python -m torch.distributed.run --nproc_per_node 2 --master_port 1 segment/train.py --data ./data/gnrDataset_polygon.yaml --weights ~/mdh_share/yolov5s-seg.pt --img 640 --device 0,1

error log:
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
ERROR:torch.distributed.elastic.multiprocessing.errors.error_handler:{
  "message": {
    "message": "RuntimeError: Permission denied",
    "extraInfo": {
      "py_callstack": "Traceback (most recent call last):\n  File \"/home/wise/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py\", line 345, in wrapper\n    return f(*args, **kwargs)\n  File \"/home/wise/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/distributed/run.py\", line 719, in main\n    run(args)\n  File \"/home/wise/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/distributed/run.py\", line 710, in run\n    elastic_launch(\n  File \"/home/wise/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/distributed/launcher/api.py\", line 131, in __call__\n    return launch_agent(self._config, self._entrypoint, list(args))\n  File \"/home/wise/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/distributed/launcher/api.py\", line 252, in launch_agent\n    result = agent.run()\n  File \"/home/wise/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py\", line 125, in wrapper\n    result = f(*args, **kwargs)\n  File \"/home/wise/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py\", line 709, in run\n    result = self._invoke_run(role)\n  File \"/home/wise/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py\", line 837, in _invoke_run\n    self._initialize_workers(self._worker_group)\n  File \"/home/wise/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py\", line 125, in wrapper\n    result = f(*args, **kwargs)\n  File \"/home/wise/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py\", line 678, in _initialize_workers\n    self._rendezvous(worker_group)\n  File \"/home/wise/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py\", line 125, in wrapper\n    result = f(*args, **kwargs)\n  File \"/home/wise/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py\", line 538, in _rendezvous\n    store, group_rank, group_world_size = spec.rdzv_handler.next_rendezvous()\n  File \"/home/wise/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/distributed/elastic/rendezvous/static_tcp_rendezvous.py\", line 55, in next_rendezvous\n    self._store = TCPStore(  # type: ignore[call-arg]\nRuntimeError: Permission denied\n",
      "timestamp": "1718680548"
    }
  }
}
Traceback (most recent call last):
  File "/home/wise/anaconda3/envs/yolov5/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/wise/anaconda3/envs/yolov5/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/wise/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/distributed/run.py", line 723, in <module>
    main()
  File "/home/wise/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/wise/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/distributed/run.py", line 719, in main
    run(args)
  File "/home/wise/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/home/wise/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/wise/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 252, in launch_agent
    result = agent.run()
  File "/home/wise/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/home/wise/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 709, in run
    result = self._invoke_run(role)
  File "/home/wise/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 837, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "/home/wise/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/home/wise/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 678, in _initialize_workers
    self._rendezvous(worker_group)
  File "/home/wise/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/home/wise/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 538, in _rendezvous
    store, group_rank, group_world_size = spec.rdzv_handler.next_rendezvous()
  File "/home/wise/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/distributed/elastic/rendezvous/static_tcp_rendezvous.py", line 55, in next_rendezvous
    self._store = TCPStore(  # type: ignore[call-arg]
RuntimeError: Permission denied

Thanks a lot.

**Comment by glenn-jocher** [comment]
@mdh31 hello,

Thank you for reaching out and providing detailed information about the issue you're encountering. The "RuntimeError: Permission denied" error typically indicates that there might be a permissions issue with the port or the environment setup.

Here are a few steps to help troubleshoot and resolve this issue:

1. **Check Port Permissions**: Ensure that the port you are using (`--master_port 1`) is not restricted or already in use. You can try using a different port number, for example:
    ```bash
    python -m torch.distributed.run --nproc_per_node 2 --master_port 12345 segment/train.py --data ./data/gnrDataset_polygon.yaml --weights ~/mdh_share/yolov5s-seg.pt --img 640 --device 0,1
    ```

2. **Run as Administrator**: If you are on a Unix-based system, try running the command with `sudo` to ensure you have the necessary permissions:
    ```bash
    sudo python -m torch.distributed.run --nproc_per_node 2 --master_port 12345 segment/train.py --data ./data/gnrDataset_polygon.yaml --weights ~/mdh_share/yolov5s-seg.pt --img 640 --device 0,1
    ```

3. **Update Packages**: Ensure you are using the latest versions of `torch` and `yolov5`. You can update them using:
    ```bash
    pip install --upgrade torch
    cd yolov5
    git pull
    pip install -r requirements.txt
    ```

4. **Environment Variables**: Sometimes, setting the `OMP_NUM_THREADS` environment variable can help. You can set it to 1 before running your command:
    ```bash
    export OMP_NUM_THREADS=1
    python -m torch.distributed.run --nproc_per_node 2 --master_port 12345 segment/train.py --data ./data/gnrDataset_polygon.yaml --weights ~/mdh_share/yolov5s-seg.pt --img 640 --device 0,1
    ```

5. **Minimum Reproducible Example**: If the issue persists, please provide a minimum reproducible code example. This will help us investigate the problem more effectively. You can find more details on creating a minimum reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

If you have tried all the above steps and the issue still exists, please let us know with any additional error logs or details. This will help us assist you better.

Thank you for your patience, and we look forward to helping you resolve this issue.
