### ISSUE TITLE
No module named 'models' question

### ISSUE THREAD

**Issue by ioir123ju** [ultralytics/yolov5#131]
## 🐛 Bug
When I use yolov5 outside the repo and use "torch.load(the_mode, PATH)", I got the error "No module named 'models'"

I see a solution in #22.

But I got error when I use `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)`

`torch.nn.modules.module.ModuleAttributeError: 'BatchNorm2d' object has no attribute '_non_persistent_buffers_set'
`

So I still want to load model in this way:
`model.load_state_dict(torch.load(new_weights))`
Can you tell me how to use model.load_state_dict ?

**Comment by glenn-jocher** [comment]
@ioir123ju use Torch Hub. See https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading

<img width="800" alt="Screen Shot 2020-06-18 at 7 01 46 PM" src="https://user-images.githubusercontent.com/26833433/85088978-33c54b00-b196-11ea-9f2c-9799f26357f0.png">

**Comment by ioir123ju** [comment]
Sorry, It doesn't solve my problem.
![image](https://user-images.githubusercontent.com/14951957/85089302-e4722f80-b214-11ea-8aa8-62b029b1cf73.png)
### environment 
pytorch 1.6

**Comment by glenn-jocher** [comment]
@ioir123ju use a working environment. See https://github.com/ultralytics/yolov5#reproduce-our-environment

**Comment by ioir123ju** [comment]
yes, My environment meets your requirements.
> torch 1.6 >= torch1.5
python 3.7

And I can run detect.py in your repo.
But can't load weight in my project.

**Comment by glenn-jocher** [comment]
@ioir123ju debug your environment, or just use one of our working ones. That's what they are there for.

**Comment by rxchen** [comment]
I have the same problem, torch 1.6rc2
 File "detect.py", line 23, in detect
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "/home/ruichen/nvme/gitrepo/yolov5/models/experimental.py", line 133, in attempt_load
    model.append(torch.load(w, map_location=map_location)['model'].float().fuse().eval())  # load FP32 model
  File "/home/ruichen/nvme/gitrepo/yolov5/models/yolo.py", line 149, in fuse
    m.conv = torch_utils.fuse_conv_and_bn(m.conv, m.bn)  # update conv
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 802, in __setattr__
    remove_from(self.__dict__, self._parameters, self._buffers, self._non_persistent_buffers_set)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 772, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'Conv' object has no attribute '_non_persistent_buffers_set'

**Comment by fpingham** [comment]
Same problem over here.

**Comment by glenn-jocher** [comment]
@fpingham you are probably using an older version of the repo, an older model, or are not meeting the minimum dependency requirements. I would start from a clean slate in one of the verified environments below.

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)
