### ISSUE TITLE
What is the purpose of anchor_t?

### ISSUE THREAD

**Issue by Uoops** [ultralytics/yolov5#1310]
## ❔Question
Thank you for sharing your work! It is the best YOLO related repo in python I have ever seen!

Can you explain what anchor_t means and what it does in the training process? 

The reason is that I notice you use anchor_t instead of iou_t to generate the targets compared to your YOLOv3 work. I think iou_t is for the classification, can anchor_t does the same thing? 
`# Matches`
` r = t[:, :, 4:6] / anchors[:, None]  # wh ratio`
`j = torch.max(r, 1. / r).max(2)[0] < model.hyp['anchor_t']  # compare`
`# j = wh_iou(anchors, t[:, 4:6]) > model.hyp['iou_t']  # iou(3,n)=wh_iou(anchors(3,2), gwh(n,2))`
`t = t[j]  # filter`

## Additional context
 The code above is copied from yolov5/utils/general.py line 565

**Comment by glenn-jocher** [comment]
@Uoops yes, we use `anchor_t` instead of `iou_t` in YOLOv5. These are both thresholds for deciding which labels to match to which anchors. 

Using `anchor_t` now provides certainty that anchors are always capable of fitting a given label, and also allows you to program the range of the width-height outputs to most efficiently occupy the width-height space.

**Comment by GorillaSX** [comment]
hey @glenn-jocher , thanks for your answer for the purpose of anchor_t. But I kind of don't understand the logic and algorithm behind anchor_t, so would you mind give me a hint or share the algorithm name you're using here? I believe a good understanding of anchor_t, could help us to set right threshold here. **I appreciate it.**

**Comment by GorillaSX** [comment]
hey @glenn-jocher , I think I figured it out.

**Comment by glenn-jocher** [comment]
@GorillaSX anchor_t is the anchor width and height multiple threshold used to select label-anchor matches when computing loss.

**Comment by GorillaSX** [comment]
hey @glenn-jocher  thanks for your answer. I understood that. What confused me is those two lines code, 
```python
 r = t[:, :, 4:6] / anchors[:, None]  # wh ratio
 j = torch.max(r, 1. / r).max(2)[0] < model.hyp['anchor_t']  # compar
```
But I think I figured it out at this time, still thanks.

**Comment by glenn-jocher** [comment]
`j` are target-anchor match candidates.

**Comment by lfydegithub** [comment]
> @GorillaSX anchor_t is the anchor width and height multiple threshold used to select label-anchor matches when computing loss.

thank you for your reply, so how to get my dataset anchor_t threshold ?  appreciate it
