### ISSUE TITLE
Why am I not getting result in /output folder from a mp4 video?

### ISSUE THREAD

**Issue by paulagd** [ultralytics/yolov5#1311]
## ❔Question
Hi, I am trying to perform inference in a video and get any of the results of it but it is not happening even I do not get any results. I have installed all the requeriments and I have followed the readme installation.

PS: I have tried both with and without "--save-txt" argument.

```
python detect.py --source inference/tv3.mp4 --save-txt
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.25, device='', img_size=640, iou_thres=0.45, save_conf=False, save_dir='inference/output', save_txt=True, source='inference/tv3.mp4', update=False, view_img=False, weights='yolov5s.pt')
Using CUDA device0 _CudaDeviceProperties(name='Tesla T4', total_memory=15109MB)

Fusing layers...
Model Summary: 140 layers, 7.45958e+06 parameters, 0 gradients
Results saved to inference/output
Done. (0.049s)
```

## Additional context

It does work for me with the image examples as it also says in the readme file:

```
> python detect.py --source inference/images
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.25, device='', img_size=640, iou_thres=0.45, save_conf=False, save_dir='inference/output', save_txt=False, source='inference/images', update=False, view_img=False, weights='yolov5s.pt')
Using CUDA device0 _CudaDeviceProperties(name='Tesla T4', total_memory=15109MB)

Fusing layers...
Model Summary: 140 layers, 7.45958e+06 parameters, 0 gradients
image 1/2 /home/paulagomez/yolov5/inference/images/bus.jpg: 640x480 4 persons, 1 buss, 1 skateboards, Done. (0.013s)
image 2/2 /home/paulagomez/yolov5/inference/images/zidane.jpg: 384x640 2 persons, 2 ties, Done. (0.013s)
Results saved to inference/output
Done. (0.148s)
```

Thanks!

**Comment by glenn-jocher** [comment]
@paulagd If you can reproduce our results with this video, then the problem is likely with your file.

```python
# Code to reproduce
torch.hub.download_url_to_file('https://github.com/ultralytics/yolov5/releases/download/v1.0/decelera_landscape.mov', 'decelera_landscape.mov')
python detect.py --source decelera_landscape.mov --save-txt
```
<img width="1566" alt="Screenshot 2020-11-06 at 12 46 45" src="https://user-images.githubusercontent.com/26833433/98362834-34b82580-202e-11eb-94de-13d16dc9d8f3.png">

**Comment by paulagd** [comment]
Hi,

I can download the video with torch.hub but when I try to reproduce the code for detecting the video I get the following:

```
> python detect.py --source decelera_landscape.mov --save-txt
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.25, device='', img_size=640, iou_thres=0.45, save_conf=False, save_dir='inference/output', save_txt=True, source='decelera_landscape.mov', update=False, view_img=False, weights='yolov5s.pt')
Using CUDA device0 _CudaDeviceProperties(name='Tesla T4', total_memory=15109MB)

Fusing layers...
Model Summary: 140 layers, 7.45958e+06 parameters, 0 gradients
[ERROR:0] global /usr/src/opencv-4.4.0/modules/videoio/src/cap.cpp (142) open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.4.0) /usr/src/opencv-4.4.0/modules/videoio/src/cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): /home/paulagomez/yolov5/decelera_landscape.mov in function 'icvExtractPattern'


Results saved to inference/output
Done. (0.017s)
```

Any idea of what is whappening?

Thanks!!

**Comment by glenn-jocher** [comment]
@paulagd It appears you may have environment problems (opencv in your case). Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below. 


## Requirements

**Python 3.8** or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including **`torch>=1.6`**. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.
