### ISSUE TITLE
运行 python detect.py --source ./data/images/ --weights weights/yolov5s.pt 报错

### ISSUE THREAD

**Issue by lei-zihao** [ultralytics/yolov5#13121]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

Traceback (most recent call last):
  File "detect.py", line 198, in <module>
    detector = Yolov5Detector()
  File "/home/ros1/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 41, in __init__
    self.conf_thres = rospy.get_param("~confidence_threshold")
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/client.py", line 467, in get_param
    return _param_server[param_name] #MasterProxy does all the magic for us
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/msproxy.py", line 123, in __getitem__
    raise KeyError(key)
KeyError: '~confidence_threshold'

### Environment

PARAMETERS
 * /detect/agnostic_nms: True
 * /detect/confidence_threshold: 0.75
 * /detect/data: /home/ros1/yolo/s...
 * /detect/device: 0
 * /detect/dnn: True
 * /detect/half: False
 * /detect/inference_size_h: 640
 * /detect/inference_size_w: 640
 * /detect/input_image_topic: /usb_cam/image_raw
 * /detect/iou_threshold: 0.45
 * /detect/line_thickness: 3
 * /detect/maximum_detections: 1000
 * /detect/output_image_topic: /yolov5/image_out
 * /detect/output_topic: /yolov5/detections
 * /detect/publish_image: False
 * /detect/view_image: True
 * /detect/weights: yolov5m.pt
 * /rosdistro: melodic
 * /rosversion: 1.14.13

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@lei-zihao hello,

Thank you for reporting this issue and providing detailed information about your environment. To assist you better, we need a minimal reproducible example of the code that triggers this error. This will help us understand the context and reproduce the bug on our end. You can find guidelines on how to create a minimal reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please ensure that you are using the latest versions of `torch` and the YOLOv5 repository. You can update your packages with the following commands:

```bash
pip install --upgrade torch
git pull https://github.com/ultralytics/yolov5
```

From the traceback, it appears that the error is related to the ROS parameter `~confidence_threshold` not being found. Please verify that this parameter is correctly set in your ROS parameter server. You can check the parameters using:

```bash
rosparam list
```

If the parameter is missing, you can set it using:

```bash
rosparam set /detect/confidence_threshold 0.75
```

Feel free to share the minimal reproducible example and any additional details that might help us diagnose the issue further. We're here to help!
