### ISSUE TITLE
multi-gpu validation

### ISSUE THREAD

**Issue by yjseok** [ultralytics/yolov5#13164]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,

Is there any way to use multi-gpu during running val.py of Yolov5?
I set --device parameter as 0,1,2,3, but it doesn't work

**Comment by glenn-jocher** [comment]
@yjseok hello,

Thank you for reaching out and for your thorough search before posting your question! Currently, `val.py` in YOLOv5 does not support multi-GPU validation directly through the `--device` parameter. The multi-GPU functionality is primarily designed for training purposes using `train.py`.

However, you can achieve multi-GPU validation by modifying the code to use `torch.nn.DataParallel` or `torch.nn.parallel.DistributedDataParallel`. Here’s a brief guide on how you might approach this:

1. **Clone the YOLOv5 repository and install dependencies**:
    ```bash
    git clone https://github.com/ultralytics/yolov5
    cd yolov5
    pip install -r requirements.txt
    ```

2. **Modify `val.py` to use `torch.nn.DataParallel`**:
    ```python
    import torch
    from models.yolo import Model

    # Load model
    model = Model(cfg='yolov5s.yaml', ch=3, nc=80).to(device)

    # Wrap model with DataParallel
    if torch.cuda.device_count() > 1:
        model = torch.nn.DataParallel(model, device_ids=[0, 1, 2, 3])
    
    # Validate
    results, maps, times = validate(model=model, ...)
    ```

3. **Run the modified `val.py`**:
    ```bash
    python val.py --data coco.yaml --weights yolov5s.pt --device 0,1,2,3
    ```

For more detailed instructions and advanced configurations, you can refer to our [Multi-GPU Training Guide](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training/).

If you encounter any issues or have further questions, please provide a minimum reproducible example of your code and the specific error messages you are seeing. This will help us to better understand and address your issue. You can find more information on creating a minimum reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Lastly, please ensure you are using the latest versions of `torch` and the YOLOv5 repository to avoid any compatibility issues.
