### ISSUE TITLE
Display YouTube Source + Bounding Boxes

### ISSUE THREAD

**Issue by cloud-ray** [ultralytics/yolov5#13186]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How can you display the YouTube video source with bounding boxes when running:
_python detect.py --source "https://www.youtube.com/watch?v=eg1234"_ 

My guess is you have to create a Flask app and possibly use OpenCV? 

I'm not sure how to get started on this. Has anyone tried this before?

**Comment by glenn-jocher** [comment]
@cloud-ray hello!

Thank you for your question and for checking the existing issues and discussions. Displaying a YouTube video source with bounding boxes is indeed an interesting task! You can achieve this without necessarily creating a Flask app. Here's a step-by-step guide to get you started using OpenCV and `pafy` to stream the video and YOLOv5 for detection:

1. **Install Required Libraries**:
   Ensure you have the necessary libraries installed:
   ```bash
   pip install pafy youtube-dl opencv-python
   ```

2. **Modify `detect.py`**:
   You can modify the `detect.py` script to handle YouTube video streams. Here’s a simplified example:

   ```python
   import pafy
   import cv2
   from pathlib import Path
   import torch
   from models.common import DetectMultiBackend
   from utils.datasets import LoadStreams, LoadImages
   from utils.general import check_img_size, non_max_suppression, scale_coords, xyxy2xywh, strip_optimizer
   from utils.plots import Annotator, colors
   from utils.torch_utils import select_device, time_sync

   # Load model
   device = select_device('')
   model = DetectMultiBackend('yolov5s.pt', device=device)
   stride, names, pt = model.stride, model.names, model.pt
   imgsz = check_img_size(640, s=stride)  # check image size

   # Load YouTube video
   url = "https://www.youtube.com/watch?v=eg1234"
   video = pafy.new(url)
   best = video.getbest(preftype="mp4")
   cap = cv2.VideoCapture(best.url)

   while cap.isOpened():
       ret, frame = cap.read()
       if not ret:
           break

       # Inference
       img = torch.from_numpy(frame).to(device)
       img = img.half() if model.fp16 else img.float()  # uint8 to fp16/32
       img /= 255.0  # 0 - 255 to 0.0 - 1.0
       if img.ndimension() == 3:
           img = img.unsqueeze(0)

       pred = model(img, augment=False, visualize=False)
       pred = non_max_suppression(pred, 0.25, 0.45, None, False, max_det=1000)

       # Process detections
       for i, det in enumerate(pred):  # detections per image
           annotator = Annotator(frame, line_width=2, example=str(names))
           if len(det):
               det[:, :4] = scale_coords(img.shape[2:], det[:, :4], frame.shape).round()
               for *xyxy, conf, cls in reversed(det):
                   label = f'{names[int(cls)]} {conf:.2f}'
                   annotator.box_label(xyxy, label, color=colors(int(cls), True))

       # Display the frame
       cv2.imshow('YOLOv5 Detection', frame)
       if cv2.waitKey(1) == ord('q'):
           break

   cap.release()
   cv2.destroyAllWindows()
   ```

3. **Run the Script**:
   Save the modified script and run it:
   ```bash
   python detect.py
   ```

This script will stream the YouTube video, perform object detection using YOLOv5, and display the video with bounding boxes in real-time.

Please ensure you have the latest versions of `torch` and YOLOv5 from the [Ultralytics repository](https://github.com/ultralytics/yolov5) to avoid any compatibility issues.

If you encounter any issues or have further questions, feel free to ask. Happy coding! 😊

**Comment by cloud-ray** [comment]
Hi @glenn-jocher 

Thank you very much for your follow up and support. I didn't have much success with _pafy_, however **CamGear** provided a pretty easy integration. 

I added two versions to this repo ([RealTimeYOLO 🔴 YouTube Live](https://github.com/cloud-ray/live-object-detection)) for YOLOv5 and YOLOv8 functionality.

Thank you again!

**Comment by glenn-jocher** [comment]
Hello @cloud-ray,

Thank you for sharing your experience and the alternative solution using **CamGear**! It's great to hear that you found an effective way to integrate YouTube live streaming with YOLOv5 and YOLOv8.

For those who might be interested, **CamGear** is indeed a powerful and flexible library for video streaming, and it's fantastic that you've provided a repository showcasing both YOLOv5 and YOLOv8 functionality. This can be a valuable resource for the community.

For anyone else looking to explore similar integrations, you can check out @cloud-ray's repository here: [RealTimeYOLO 🔴 YouTube Live](https://github.com/cloud-ray/live-object-detection).

If you encounter any further issues or have more questions, feel free to reach out. The YOLO community and the Ultralytics team are always here to help! 😊
