### ISSUE TITLE
About mAP@.5, mAP@.5:.95, Precision and Recall

### ISSUE THREAD

**Issue by jaqub-manuel** [ultralytics/yolov5#1321]
Hello @glenn-jocher,

Instead of mAP@.5  mAP@.5:.95:   I want to increase my precision and recall. Thus, do I need to change this line (general.py ln 926) 
 w = [0.0, 0.0, 0.1, 0.9] to w = [0.5, 0.5, 0.0, 0.0] ?. As far as I understand the best weight (best.pt) is set to mAP@.5:.95 because it has a ratio of 0.9. 

Many Thanks

**Comment by jaqub-manuel** [comment]
Another point I wonder is, how much is the data augmentation number. I mean, for example, when there is a data set containing 500 images, for each value, for example, if shear = 1 (not 0), 500 pieces of new data are generated. Is there an exact number?

Thanks in advance ...

**Comment by glenn-jocher** [comment]
@jaqub-manuel augmentation samples each parameter randomly from a distribution in the dataloader, thus the model never sees the same image twice, no matter how long you train.

Other platforms don't seem to understand this concept, and sell augmentation as if it's something that can be performed offline before training, to multiply your small dataset into something larger (i.e. start with 100 images and end up with 200), but this is an incorrect application, likely confusing users into believing they can create larger datasets through these services.

In reality YOLOv5 and most smart training platforms produce infinite augmentation combinations in realtime as images are loaded.

**Comment by jaqub-manuel** [comment]
> @jaqub-manuel augmentation samples each parameter randomly from a distribution in the dataloader, thus the model never sees the same image twice, no matter how long you train.
> 
> Other platforms don't seem to understand this concept, and sell augmentation as if it's something that can be performed offline before training, to multiply your small dataset into something larger (i.e. start with 100 images and end up with 200), but this is an incorrect application, likely confusing users into believing they can create larger datasets through these services.
> 
> In reality YOLOv5 and most smart training platforms produce infinite augmentation combinations in realtime as images are loaded.

Thank for explanation

**Comment by jaqub-manuel** [comment]
> Hello @glenn-jocher,
> 
> Instead of mAP@.5 mAP@.5:.95: I want to increase my precision and recall. Thus, do I need to change this line (general.py ln 926)
> w = [0.0, 0.0, 0.1, 0.9] to w = [0.5, 0.5, 0.0, 0.0] ?. As far as I understand the best weight (best.pt) is set to mAP@.5:.95 because it has a ratio of 0.9.
> 
> Many Thanks

Could you give some information about best.pt calculation ? Is it right to do above ?
Thanks again

**Comment by glenn-jocher** [comment]
@jaqub-manuel best.pt is saved on maximum fitness. You can modify the fitness function here:
https://github.com/ultralytics/yolov5/blob/69caa65191e671a52cdc958f40d01e892df00cc2/utils/general.py#L926-L930
