### ISSUE TITLE
Suppress torch.hub.load() Output

### ISSUE THREAD

**Issue by DylanBPY** [ultralytics/yolov5#13237]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Goody day all!

I am working on a project using YOLOv5 to detect objects. In this project, I would like the console output to have a specific format and be clean. However, when loading a YOLOv5 model with torch.hub.load, it outputs this to the console:

```
YOLOv5  2024-7-31 Python-3.11.9 torch-2.3.1+cpu CPU

Fusing layers... 
Model summary: 157 layers, 1788931 parameters, 0 gradients, 4.2 GFLOPs
Adding AutoShape...
```

Ive been searching for a way to suppress this output to replace with my own, but I cant seem to find a way that works.
I came across this issue: https://github.com/ultralytics/yolov5/issues/2862, which hinted at 3 solutions:
1. `logging.getLogger("utils.general").setLevel(logging.WARNING)`
2. `logging.getLogger("yolov5").setLevel(logging.WARNING)`
3. `torch.hub.load(verbose=False)`

None of these solutions worked for me, I also saw this online:
```
class SuppressPrint:
    def __enter__(self):
        self._original_stdout = sys.stdout
        sys.stdout = open(os.devnull, 'w')
    
    def __exit__(self, exc_type, exc_val, exc_tb):
        sys.stdout.close()
        sys.stdout = self._original_stdout
        
with SuppressPrint():
    torch.hub.load()
```
However, this had no effect either.
If anyone had ideas as to how I could go about solving this, it would be appreciated!

Thanks!
- DylDev

**Comment by DylanBPY** [comment]
Also this is completely unrelated, but I was on the website (https://www.ultralytics.com/yolo) and I discovered a small typo here:

![image](https://github.com/user-attachments/assets/2a44cce5-9117-44d4-be5a-ced3bfe9ac0a)

**Comment by glenn-jocher** [comment]
@DylDevs hello DylDev,

Thank you for your question and for bringing the typo to our attention! We'll make sure to address that promptly.

Regarding your issue with suppressing the console output from `torch.hub.load()`, you can indeed load the YOLOv5 model silently by setting the `_verbose` parameter to `False`. Here's how you can do it:

```python
import torch

# Load model silently
model = torch.hub.load("ultralytics/yolov5", "yolov5s", _verbose=False)
```

This should suppress the output you're seeing in the console. If you still encounter issues, please ensure you are using the latest version of YOLOv5 and PyTorch.

If you have any further questions or run into any other issues, feel free to ask. The YOLO community and the Ultralytics team are always here to help!

**Comment by DylanBPY** [comment]
Thanks for the response!
I tried this:
```
torch.hub.load('ultralytics/yolov5', 'custom', path=model_path, _verbose=False)
```
This did not suppress the console output during loading though.

**Comment by glenn-jocher** [comment]
Hello @DylDevs,

Thank you for your patience and for trying out the suggested solution. I'm sorry to hear that it didn't work as expected.

To further suppress the console output, you can redirect the standard output temporarily while loading the model. Here's an example of how you can achieve this:

```python
import torch
import sys
import os

class SuppressPrint:
    def __enter__(self):
        self._original_stdout = sys.stdout
        sys.stdout = open(os.devnull, 'w')
    
    def __exit__(self, exc_type, exc_val, exc_tb):
        sys.stdout.close()
        sys.stdout = self._original_stdout

# Suppress output during model loading
with SuppressPrint():
    model = torch.hub.load('ultralytics/yolov5', 'custom', path='path/to/your/model.pt')

# Continue with your code
```

This approach should help in keeping your console output clean. If the issue persists, please ensure you are using the latest versions of YOLOv5 and PyTorch, as updates often include fixes and improvements.

If you encounter any further issues or have additional questions, feel free to reach out. The YOLO community and the Ultralytics team are here to support you! 😊

**Comment by DylanBPY** [comment]
Thanks for the response again!
But as stated in the original issue, I have already tried this solution and it did not work.

**Comment by glenn-jocher** [comment]
Hello @DylDevs,

Thank you for your patience and for clarifying that you've already tried the suggested solutions.

Given that the standard methods haven't worked, let's try a more robust approach by redirecting both `stdout` and `stderr` during the model loading process. This should cover any output that might be coming from different streams. Here's an example:

```python
import torch
import sys
import os

class SuppressOutput:
    def __enter__(self):
        self._original_stdout = sys.stdout
        self._original_stderr = sys.stderr
        sys.stdout = open(os.devnull, 'w')
        sys.stderr = open(os.devnull, 'w')
    
    def __exit__(self, exc_type, exc_val, exc_tb):
        sys.stdout.close()
        sys.stderr.close()
        sys.stdout = self._original_stdout
        sys.stderr = self._original_stderr

# Suppress output during model loading
with SuppressOutput():
    model = torch.hub.load('ultralytics/yolov5', 'custom', path='path/to/your/model.pt')

# Continue with your code
```

If this still doesn't resolve the issue, I recommend verifying that the problem persists with the latest versions of YOLOv5 and PyTorch. Sometimes, updates include fixes that might address such issues.

If you have any further questions or need additional assistance, feel free to ask. The YOLO community and the Ultralytics team are always here to help! 😊

**Comment by DylanBPY** [comment]
This solution did work! Thank you.

**Comment by glenn-jocher** [comment]
Hello @DylDevs,

I'm glad to hear that the solution worked for you! 🎉

If you encounter any more questions or run into other issues, feel free to reach out. The YOLO community and the Ultralytics team are always here to help. Keep up the great work on your project!
