### ISSUE TITLE
use Torchserve to serve the yolov5 model

### ISSUE THREAD

**Issue by alan-shangguan** [ultralytics/yolov5#1324]
## ❔Question

Hi, any suggestion on how to serve yolov5 on torchserve ?

**Comment by glenn-jocher** [comment]
@yuanyuangoo you probably want to raise your issue here:
https://github.com/pytorch/serve

**Comment by louisoutin** [comment]
I just shared a working example on how to run yolov5 on torchserve (GPU compatible):
https://github.com/ultralytics/yolov5/issues/1681

Cheers :)
