### ISSUE TITLE
Detect head structure differs

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#13258]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I've been looking into using yolov5's pretrained weights and updating it on a custom dataset. I firstly tried to fine-tune it in my own environment, but found that it was hard to re-use the model and loss functions. Thereafter, I tried to use the train.py file. However, I can't seem to get the same model architecture to start off with. By using `model = YOLO('yolov5s.pt')`, I get the following architecture for the Detect.cv3 module:
```
        (cv3): ModuleList(
          (0): Sequential(
            (0): Conv(
              (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
              (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
              (act): SiLU(inplace=True)
            )
            (1): Conv(
              (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
              (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
              (act): SiLU(inplace=True)
            )
            (2): Conv2d(128, 80, kernel_size=(1, 1), stride=(1, 1))
          )
          (1): Sequential(
            (0): Conv(
              (conv): Conv2d(256, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
              (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
              (act): SiLU(inplace=True)
            )
            (1): Conv(
              (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
              (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
              (act): SiLU(inplace=True)
            )
            (2): Conv2d(128, 80, kernel_size=(1, 1), stride=(1, 1))
          )
          (2): Sequential(
            (0): Conv(
              (conv): Conv2d(512, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
              (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
              (act): SiLU(inplace=True)
            )
            (1): Conv(
              (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
              (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
              (act): SiLU(inplace=True)
            )
            (2): Conv2d(128, 80, kernel_size=(1, 1), stride=(1, 1))
          )
        )
```
        
But the train.py script simply gives the following:
```
    (24): Detect(
      (m): ModuleList(
        (0): Conv2d(128, 255, kernel_size=(1, 1), stride=(1, 1))
        (1): Conv2d(256, 255, kernel_size=(1, 1), stride=(1, 1))
        (2): Conv2d(512, 255, kernel_size=(1, 1), stride=(1, 1))
      )
    )
```
    
Could you kindly assist on how to get the first architecture in your environment? I have triple checked yaml config files.

**Comment by glenn-jocher** [comment]
@nortjeleanne hi there,

Thank you for your detailed question! It looks like you're encountering a discrepancy in the model architecture when loading the pretrained weights versus using the `train.py` script. This issue might be related to the version of YOLOv5 or the specific configuration files being used.

Here are a few steps to help you resolve this:

1. **Ensure Latest Version**: First, make sure you are using the latest version of YOLOv5. You can update your repository by pulling the latest changes from the GitHub repo:
    ```bash
    git pull
    ```

2. **Check Configuration Files**: Verify that the configuration files (`.yaml`) used in both cases are identical. The architecture is defined in these files, and any differences can lead to the discrepancies you're seeing.

3. **Loading Pretrained Weights**: When loading the pretrained weights, ensure that the model is correctly initialized with the same architecture. You can explicitly specify the model configuration file when loading the model:
    ```python
    from yolov5 import YOLO

    model = YOLO('yolov5s.yaml')  # Ensure this matches the architecture you want
    model.load_state_dict(torch.load('yolov5s.pt')['model'])
    ```

4. **Training Script**: When using the `train.py` script, ensure that the correct configuration file is being passed. You can specify the model configuration file using the `--cfg` argument:
    ```bash
    python train.py --cfg yolov5s.yaml --weights yolov5s.pt
    ```

5. **Verify Model Structure**: After loading the model, you can print the model structure to verify that it matches your expectations:
    ```python
    print(model)
    ```

If you continue to experience issues, please provide more details about the specific versions of YOLOv5 and the configuration files you are using. This will help in diagnosing the problem more accurately.

Feel free to refer to the [YOLOv5 Architecture Documentation](https://docs.ultralytics.com/yolov5/tutorials/architecture_description/) for more insights into the model structure and configuration.

I hope this helps! If you have any further questions, please don't hesitate to ask.

**Comment by ghost** [comment]
Hi Glen, 

This was a mix up between yolov5 and yolov8 versions. Unfortunately `from yolov5 import YOLO` gives the following error:
`from yolov5 import YOLO
ImportError: cannot import name 'YOLO' from 'yolov5' (unknown location)`. 
And using `from ultralytics import YOLO` imported the yolov8 architecture. But I found that using `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)` gave the same architecture as the source code. Thanks for the tips!

**Comment by glenn-jocher** [comment]
@nortjeleanne hi there,

Thank you for the update! It sounds like you were able to resolve the issue by using the correct import and loading method. Indeed, the `torch.hub.load` method is a reliable way to load the YOLOv5 model with pretrained weights, ensuring you get the expected architecture.

For clarity and future reference, here's a concise example of how to load YOLOv5 using `torch.hub`:

```python
import torch

# Load YOLOv5 model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)

# Print model architecture
print(model)
```

This method ensures that you are using the correct YOLOv5 architecture and pretrained weights.

If you have any more questions or run into further issues, feel free to ask. The YOLO community and the Ultralytics team are always here to help! 😊
