### ISSUE TITLE
How to disable or add new scales of prediction?

### ISSUE THREAD

**Issue by layadas** [ultralytics/yolov5#13271]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

The YOLOv5 models perform predictions at 3 scales according to COCO definition of scales. In my custom dataset, the sizes of objects are different from those in COCO, and I want to be able to predict at 2 scales, or at 4 scales. How do I implement this? In addition to the config file, what other changes will be required?

Thank you fin advance for your help.

**Comment by glenn-jocher** [comment]
@layadas to modify the number of prediction scales in YOLOv5, you need to adjust the model configuration file (e.g., `yolov5s.yaml`). Specifically, you can change the `anchors` and `stride` settings to match your desired scales. Additionally, you may need to update the `Detect` layer in the model definition to reflect the new number of scales. For detailed guidance, please refer to the [YOLOv5 architecture documentation](https://docs.ultralytics.com/yolov5/tutorials/architecture_description/). If the issue persists, ensure you are using the latest version of YOLOv5.

**Comment by layadas** [comment]
@glenn-jocher Thank you for your response. As a trial, I decided to predict only at the medium and large scales. So, I commented out the first line of anchors in `yolov5l.yaml` and the inputs to the Detect layer as follows:

```
# Ultralytics YOLOv5 🚀, AGPL-3.0 license

# Parameters
nc: 80 # number of classes
depth_multiple: 1.0 # model depth multiple
width_multiple: 1.0 # layer channel multiple
anchors:
#  - [10, 13, 16, 30, 33, 23] # P3/8  # THIS HAS BEEN COMMENTED OUT
  - [30, 61, 62, 45, 59, 119] # P4/16
  - [116, 90, 156, 198, 373, 326] # P5/32

# YOLOv5 v6.0 backbone
backbone:
  # [from, number, module, args]
  [
    [-1, 1, Conv, [64, 6, 2, 2]], # 0-P1/2
    [-1, 1, Conv, [128, 3, 2]], # 1-P2/4
    [-1, 3, C3, [128]],
    [-1, 1, Conv, [256, 3, 2]], # 3-P3/8
    [-1, 6, C3, [256]],
    [-1, 1, Conv, [512, 3, 2]], # 5-P4/16
    [-1, 9, C3, [512]],
    [-1, 1, Conv, [1024, 3, 2]], # 7-P5/32
    [-1, 3, C3, [1024, False]],
    [-1, 1, SPPF, [1024, 5]], # 9
  ]

# YOLOv5 v6.0 head
head: [
    [-1, 1, Conv, [512, 1, 1]],
    [-1, 1, nn.Upsample, [None, 2, "nearest"]],
    [[-1, 6], 1, Concat, [1]], # cat backbone P4
    [-1, 3, C3, [512, False]], # 13

    [-1, 1, Conv, [256, 1, 1]],
    [-1, 1, nn.Upsample, [None, 2, "nearest"]],
    [[-1, 4], 1, Concat, [1]], # cat backbone P3
    [-1, 3, C3, [256, False]], # 17 (P3/8-small)

    [-1, 1, Conv, [256, 3, 2]],
    [[-1, 14], 1, Concat, [1]], # cat head P4
    [-1, 3, C3, [512, False]], # 20 (P4/16-medium)

    [-1, 1, Conv, [512, 3, 2]],
    [[-1, 10], 1, Concat, [1]], # cat head P5
    [-1, 3, C3, [1024, False]], # 23 (P5/32-large)

#    [[17, 20, 23], 1, Detect, [nc, anchors]], # Detect(P3, P4, P5)
    [[20, 23], 1, Detect, [nc, anchors]], # Detect(P3, P4, P5)  # Detect DOES NOT TAKE INPUTS FROM THE SMALL-SCALE HEAD

  ]
```

I made no other changes and ran the code with my dataset. The mAP50 starts with 0 and does not improve for around 50 epochs. The final mAP (after 300 epochs) is 0.48.Without these changes, the mAP50 increased from the beginning and its final value was around 0.65.

Is there something else I should have also done in the models, or is the configuration not working out for the dataset? Thanks


Also, as an additional question, the Autoanchor gives a poor fit to the dataset.

This did not happen with the 3-scale model. Is this also an indication that the configuration not working for the dataset? Is there a way to improve this from the dataset? Thanks

**Comment by glenn-jocher** [comment]
@layadas it looks like you've made the necessary changes to the model configuration to predict at medium and large scales only. However, the drop in mAP suggests that the new configuration might not be optimal for your dataset. You might want to experiment with different anchor sizes or revisit the dataset to ensure it aligns well with the new scales. Regarding the Autoanchor issue, it could indeed indicate a mismatch. You can try manually setting anchors that better fit your dataset's object sizes. For further guidance, refer to the [YOLOv5 documentation](https://docs.ultralytics.com/guides/model-training-tips//).

**Comment by layadas** [comment]
Thank you for the confirmation and for your help

**Comment by glenn-jocher** [comment]
You're welcome! If you have any more questions or need further assistance, feel free to ask.
