### ISSUE TITLE
Docker image is not working, ```torch.nn.modules.module.ModuleAttributeError: 'Hardswish' object has no attribute 'inplace```'

### ISSUE THREAD

**Issue by thomasgauvin** [ultralytics/yolov5#1327]
Before submitting a bug report, please be aware that your issue **must be reproducible** with all of the following, otherwise it is non-actionable, and we can not help you:
 - **Current repo**: run `git fetch && git status -uno` to check and `git pull` to update repo
 - **Common dataset**: coco.yaml or coco128.yaml
 - **Common environment**: Colab, Google Cloud, or Docker image. See https://github.com/ultralytics/yolov5#environments
 
If this is a custom dataset/training question you **must include** your `train*.jpg`, `test*.jpg` and `results.png` figures, or we can not help you. You can generate these with `utils.plot_results()`.

## 🐛 Bug
Attempting to run the ultralytics/yolov5:latest docker image results in torch.nn.modules.module.ModuleAttributeError: 'Hardswish' object has no attribute 'inplace'

## To Reproduce (REQUIRED)

run `python detect.py ...`

Output:
```
  File "/root/Video-Streaming/computer_vision/yolov5_mod/models/yolo.py", line 118, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/root/Video-Streaming/computer_vision/yolov5_mod/models/yolo.py", line 138, in forward_once
    x = m(x)  # run
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/Video-Streaming/computer_vision/yolov5_mod/models/common.py", line 92, in forward
    return self.conv(torch.cat([x[..., ::2, ::2], x[..., 1::2, ::2], x[..., ::2, 1::2], x[..., 1::2, 1::2]], 1))
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/Video-Streaming/computer_vision/yolov5_mod/models/common.py", line 36, in fuseforward
    return self.act(self.conv(x))
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/activation.py", line 438, in forward
    return F.hardswish(input, self.inplace)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 779, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'Hardswish' object has no attribute 'inplace'
```

## Expected behavior
It should run and begin analyzing the video frames

## Environment

 - OS: Docker
 - GPU 1080 Ti

**Comment by glenn-jocher** [comment]
Docker image operates correctly. Just pulled latest and tested today:
<img width="1014" alt="Screenshot 2020-11-09 at 20 52 56" src="https://user-images.githubusercontent.com/26833433/98589476-9ea22a80-22cd-11eb-88c4-c6e9dd135ae6.png">

**Comment by glenn-jocher** [comment]
GPU mode operates correctly also:
<img width="1014" alt="Screenshot 2020-11-09 at 20 55 25" src="https://user-images.githubusercontent.com/26833433/98589679-ede85b00-22cd-11eb-890b-8aa8c8787f4e.png">

**Comment by glenn-jocher** [comment]
See https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/

**Comment by thomasgauvin** [comment]
Thank you for the response @glenn-jocher, I will try it again perhaps there is something wrong with my configurations

**Comment by HsLOL** [comment]
hello @thomasgauvin  
I also have the same problem when I run the detect.py
The error is "torch.nn.modules.module.ModuleAttributeError: 'Hardswish' object has no attribute 'inplace'"
Have you solved this problem? If you solved this problem,what's your configurations?

thank you!

**Comment by littlePrince126** [comment]
@HsLOL Using torch-1.6.0 with torchvision-0.7.0 could slove this problem
