### ISSUE TITLE
Error with fbgemm.dll file when using Torch!

### ISSUE THREAD

**Issue by yaap1-png** [ultralytics/yolov5#13293]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

PyTorch Hub

### Bug

hi guys, i keep having this error when i try to use torch everytime. I have installed and installed torch several times using pip, I have visual C++, and I have still not resolved this issue with the "fbgemm.dll" file. can you help? this is the error:

File "C:\Users\Hp\yolov5\detect.py", line 38, in
import torch
File "C:\Users\Hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch_init_.py", line 148, in
raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\Hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

### Environment

- YOLO: YOLO v5
- - Pytoch version: 2.4.0
- Windows 11
- Python version: 3.12.5
- pip version: 24.2

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@yaap1-png thank you for reporting this issue. Please ensure you are using the latest versions of YOLOv5 and PyTorch. If the problem persists, try downgrading to Python 3.8 or 3.9, as compatibility issues can sometimes arise with newer Python versions. Let us know if this resolves your issue.

**Comment by yaap1-png** [comment]
@glenn-jocher thanks for your help!! how do I downgrade my python version? the 3.12.5 is running on all apps and honestly I need it for some code. Also, YOLOv3 works fine, its just YOLOv5, so I'm assuming its a problem with torch itself

**Comment by glenn-jocher** [comment]
To downgrade your Python version, you can install a specific version using the following command:

```sh
pip install python==3.9
```

You can also manage multiple Python versions using tools like `pyenv` or `Anaconda`. If YOLOv3 works fine, it might indeed be a compatibility issue with PyTorch and Python 3.12. Try using Python 3.9 and see if that resolves the issue.

**Comment by yaap1-png** [comment]
@glenn-jocher it works! thank you!

**Comment by glenn-jocher** [comment]
Glad to hear it worked! If you have any more questions or run into further issues, feel free to ask. The YOLO community and Ultralytics team are here to help.
