### ISSUE TITLE
ModuleNotFoundError: No module named 'models.yolo'.

### ISSUE THREAD

**Issue by Khush1593** [ultralytics/yolov5#13299]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have finetuned my model on google colab and I have downloaded best.py model and save it locally. after that I run below code
`from ultralytics import YOLO
model = YOLO("./models/best.pt")
result = model.predict("input_videos/image.png")`

 I make sure about my model path and Input Image path. Also I added __init__.py file in my models folder. Also I have again installed  ultralytics  library.  I know I can run `import os
result = os.system("python yolov5/detect.py --weights models/last.pt --img 640 --conf 0.8 --source input_videos/input_video.mp4")` This code. But this code does not give the integer as a result. So I don't know how to do prediction and detect it's location.

### Additional

I am using python version 3.12.5 and for ultralytics I am using version 8.2.87. I run this code in CPU. I also run the same type of code for detecting person without finetuning model i.e using your models. In that case I got the correct result.

**Comment by glenn-jocher** [comment]
@Khush1593 it seems like you're encountering a module import issue. Please ensure that your `best.pt` model is compatible with the version of the Ultralytics library you're using. If the issue persists, try updating to the latest version of the library and verify your model path. For more details on loading custom models, you can refer to the [PyTorch Hub tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading/). If you need further assistance, feel free to ask here.

**Comment by Khush1593** [comment]
Thank you so much @glenn-jocher for your response.

I got the solution. I have used below code:
`
import cv2
import torch
import pathlib

# Fix PosixPath issue for Windows
temp = pathlib.PosixPath
pathlib.PosixPath = pathlib.WindowsPath

# Load your custom YOLOv5 model
model = torch.hub.load("ultralytics/yolov5", "custom", path="models/last.pt", force_reload=True)

# Perform prediction
result = model("input_videos/image.png")  # Inference

# Extract predictions (bounding boxes, confidences, and class labels)
predictions = result.xyxy[0].cpu().numpy()  # xyxy format: [x_min, y_min, x_max, y_max, confidence, class]

# Set a confidence threshold (80% or 0.80)
confidence_threshold = 0.80

# Load the original image
img = cv2.imread("input_videos/image.png")

# Loop over the predictions and draw boxes with confidence above the threshold
for prediction in predictions:
    x_min, y_min, x_max, y_max, confidence, class_id = prediction

    # Only process predictions where confidence is greater than 80%
    if confidence >= confidence_threshold:
        # Draw the bounding box
        cv2.rectangle(img, (int(x_min), int(y_min)), (int(x_max), int(y_max)), (0, 255, 0), 2)

        # Prepare the label with confidence score
        label = f"Class {int(class_id)}: {confidence:.2f}"

        # Put the label text above the bounding box
        cv2.putText(img, label, (int(x_min), int(y_min) - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0, 255, 0), 2)

# Save the annotated image with only high-confidence predictions
cv2.imwrite("image_with_confidence_above_80.png", img)
`

I have to modify my code because the output format that we get from official yolo model and from finetuned model using torch module are different. **I request you also add the code in [https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading/](url) for the prediction and the output format that we get so we can easily got the idea.**

**Comment by glenn-jocher** [comment]
@Khush1593 thank you for sharing your solution. We appreciate your feedback on the documentation. We'll consider your suggestion for future updates to improve clarity on prediction outputs and formats. If you have any more questions, feel free to ask!
