### ISSUE TITLE
hyp.finetune.yaml missing

### ISSUE THREAD

**Issue by spacewalk01** [ultralytics/yolov5#13304]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi I cannot find hyp.finetune.yaml in this repo as it was mentioned in finetuning model docs in ultralytics docmentation. Did you guys change hyp.finetune.yaml into hyp.VOC.yaml?  Thank you!

**Comment by glenn-jocher** [comment]
@spacewalk01 the `hyp.finetune.yaml` file has been replaced with `hyp.VOC.yaml` for fine-tuning. You can use `hyp.VOC.yaml` for your fine-tuning needs. For more details, please refer to the latest documentation.

**Comment by spacewalk01** [comment]
Thanks

**Comment by glenn-jocher** [comment]
@spacewalk01 you're welcome! If you have any more questions about YOLOv5, feel free to ask.
