### ISSUE TITLE
Precision is lower.But the test results seems better.

### ISSUE THREAD

**Issue by ai-solver** [ultralytics/yolov5#1332]
I trained my custom dataset with yolov5.I used a small dataset to train the model, the results of P ,R ,mAP0.5,mAP0.5:0.95 were 0.8503    0.9931    0.9802     0.687.When I used a bigger dataset to train the results of P ,R ,mAP0.5,mAP0.5:0.95  were  0.7045     0.972    0.9915    0.7563,I find the test result is better than before.But precision is lower than before.Is this reasonable?

**Comment by glenn-jocher** [comment]
@ai-solver precision and recall are user selectable to whatever values you want based on confidence threshold, so they are useless indicators for training performance essentially. Focus on mAP.

**Comment by ai-solver** [comment]
I think the confidence threshold influences the precision of the  edge of the detected box.I find the parameters conf_thres=0.001,
   iou_thres=0.6 in test.py.If I want to get a better detected box ,how can I adjust it ?

**Comment by ai-solver** [comment]
@glenn-jocher

**Comment by glenn-jocher** [comment]
@ai-solver tuning your inference parameters is on you buddy. Experiment and see what works.

**Comment by ai-solver** [comment]
thanks @glenn-jocher
