### ISSUE TITLE
Randomise images for testing batch

### ISSUE THREAD

**Issue by nanometer34688** [ultralytics/yolov5#1334]
## 🚀 Feature
After a complete training cycle, the test_batch0_gt.jpg is then inferred on to give test_batch0_pred.jpg. My enhancement request would be to randomise the images in the test batch.

## Motivation

Because of my dataset, the first few images do look very similar. Meaning that when looking at the test_batch0_gt.jpg, all of the images look almost identical (especially when resized down to 640). So when i look at the test_batch0_pred.jpg, I can't determine if it had trained well enough as all test images look very similar.

## Pitch
It would be great to randomise the images of the test dataset to then use as the test_batch0_gt.jpg. This would give a more randomised testing set to quickly see after it had been trained.

**Comment by glenn-jocher** [comment]
@nanometer34688 test dataset is sorted by aspect ratio for the minimum batched rectangular inference area and fastest inference times. We will not randomize the test set.

You can save as many batch mosaics as you'd like though by adjusting L206:
https://github.com/ultralytics/yolov5/blob/19e24824587e44af7f220055b7f45cf5770333e5/test.py#L205-L211

**Comment by nanometer34688** [comment]
@glenn-jocher thank you. I'll try that instead

**Comment by glenn-jocher** [comment]
This reminds me, I've been meaning to replace 'ground truth' with 'labels' throughout the repo, as the 'ground truth' term may be confusing to non-english speakers especially. Adding TODO for this item here out of convenience.

TODO: replace 'ground truth' term with 'labels' throughout repo for clarity.

**Comment by glenn-jocher** [comment]
Removing TODO, update complete.
