### ISSUE TITLE
How to improve Precision?

### ISSUE THREAD

**Issue by blueskywwc** [ultralytics/yolov5#1335]
Hello, my training precision rate is 0.7, and the recall rate is 0.9. I hope to reduce the recall rate to improve the accuracy. How to set it, thank you!

**Comment by glenn-jocher** [comment]
@blueskywwc precision and recall are not true metrics as they are fully user-settable by varying confidence threshold. In other words, you can achieve 100% precision at your convenience on any dataset by simply setting the confidence threshold to 100%, and vice versa with recall.

mAP is a fully encompassing metric that gives you a true look at your performance, I would focus on that only.

**Comment by blueskywwc** [comment]
Thanks for your reply, I will try
