### ISSUE TITLE
detect.py is processing only 50 files

### ISSUE THREAD

**Issue by guybashan** [ultralytics/yolov5#13363]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

I am running this command:

`
/Users/columbo/Documents/dev/cam-analyzer/pytorch_metal_env/bin/python detect.py --save-txt --save-conf --weights /Users/columbo/Documents/dev/yolo_model/cam_analyzer/weights/best.pt --source /Users/columbo/Documents/dev/yolo_images --conf 0.1 --project /Users/columbo/Documents/dev/yolo_results --name detections --device mps
`

On the output it processes only 50 images. Anything I am missing?

### Environment

YOLOv5 🚀 v7.0-356-g2070b303 Python-3.12.7 torch-2.4.0 MPS

### Minimal Reproducible Example

```YOLOv5 🚀 v7.0-356-g2070b303 Python-3.12.7 torch-2.4.0 MPS```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by guybashan** [comment]
Sorry, my bad.. was something in my code that caused it.

**Comment by pderrenger** [comment]
@guybashan no worries! If you have any more questions or need further assistance, feel free to ask.

**Comment by guybashan** [comment]
🙏👍

**Comment by pderrenger** [comment]
Thank you for your support! If you have any questions or need assistance, feel free to ask.
