### ISSUE TITLE
socket.gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by mcjqwer** [ultralytics/yolov5#1339]
## ❔Question
I train the  yolov5  on  my  school  high  performance  computer  ,however i  encounter  a  strange error  .  I  surf  the  internet  but  i  don  not  know  how  to  check  it .
/gpfs/users_home/201961206025/.lsbatch/1605011843.159670.shell: line 16: /gpfs/users_home/201961206025/gpfs/users_home/201961206025/yolov5-new/output.txt: No such file or directory
Using CUDA device0 _CudaDeviceProperties(name='Tesla V100-PCIE-32GB', total_memory=32480MB)

Namespace(adam=False, batch_size=64, bucket='', cache_images=False, cfg='models/yolov5s.yaml', data='data/coco128.yaml', device='', epochs=7000, evolve=False, global_rank=-1, hyp='data/hyp.scratch.yaml', image_weights=False, img_size=[640, 640], local_rank=-1, log_imgs=10, logdir='runs/train', multi_scale=False, name='', noautoanchor=False, nosave=False, notest=False, rect=False, resume=False, single_cls=False, sync_bn=False, total_batch_size=64, weights='', workers=8, world_size=1)
Start Tensorboard with "tensorboard --logdir runs/train", view at http://localhost:6006/
Install Weights & Biases for experiment logging via 'pip install wandb' (recommended)
Hyperparameters {'lr0': 0.01, 'lrf': 0.2, 'momentum': 0.937, 'weight_decay': 0.0005, 'warmup_epochs': 3.0, 'warmup_momentum': 0.8, 'warmup_bias_lr': 0.1, 'box': 0.05, 'cls': 0.5, 'cls_pw': 1.0, 'obj': 1.0, 'obj_pw': 1.0, 'iou_t': 0.2, 'anchor_t': 4.0, 'fl_gamma': 0.0, 'hsv_h': 0.015, 'hsv_s': 0.7, 'hsv_v': 0.4, 'degrees': 0.0, 'translate': 0.1, 'scale': 0.5, 'shear': 0.0, 'perspective': 0.0, 'flipud': 0.0, 'fliplr': 0.5, 'mosaic': 1.0, 'mixup': 0.0}
Traceback (most recent call last):
  File "/gpfs/users_home/201961206025/.conda/envs/torch16gpupy38/lib/python3.8/urllib/request.py", line 1317, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/gpfs/users_home/201961206025/.conda/envs/torch16gpupy38/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/gpfs/users_home/201961206025/.conda/envs/torch16gpupy38/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/gpfs/users_home/201961206025/.conda/envs/torch16gpupy38/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/gpfs/users_home/201961206025/.conda/envs/torch16gpupy38/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/gpfs/users_home/201961206025/.conda/envs/torch16gpupy38/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/gpfs/users_home/201961206025/.conda/envs/torch16gpupy38/lib/python3.8/http/client.py", line 1392, in connect
    super().connect()
  File "/gpfs/users_home/201961206025/.conda/envs/torch16gpupy38/lib/python3.8/http/client.py", line 915, in connect
    self.sock = self._create_connection(
  File "/gpfs/users_home/201961206025/.conda/envs/torch16gpupy38/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/gpfs/users_home/201961206025/.conda/envs/torch16gpupy38/lib/python3.8/socket.py", line 914, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs/users_home/201961206025/yolov5-new/train.py", line 481, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "/gpfs/users_home/201961206025/yolov5-new/train.py", line 60, in train
    check_dataset(data_dict)  # check
  File "/gpfs/users_home/201961206025/yolov5-new/utils/general.py", line 152, in check_dataset
    torch.hub.download_url_to_file(s, f)
  File "/gpfs/users_home/201961206025/.conda/envs/torch16gpupy38/lib/python3.8/site-packages/torch/hub.py", line 425, in download_url_to_file
    u = urlopen(req)
  File "/gpfs/users_home/201961206025/.conda/envs/torch16gpupy38/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/gpfs/users_home/201961206025/.conda/envs/torch16gpupy38/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/gpfs/users_home/201961206025/.conda/envs/torch16gpupy38/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/gpfs/users_home/201961206025/.conda/envs/torch16gpupy38/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/gpfs/users_home/201961206025/.conda/envs/torch16gpupy38/lib/python3.8/urllib/request.py", line 1360, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/gpfs/users_home/201961206025/.conda/envs/torch16gpupy38/lib/python3.8/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

**Comment by glenn-jocher** [comment]
@mcjqwer it appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below. 


## Requirements

**Python 3.8** or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including **`torch>=1.6`**. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu every 24 hours and on every commit.

**Comment by mcjqwer** [comment]
> @mcjqwer it appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally. If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below.
> 
> ## Requirements
> **Python 3.8** or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including **`torch>=1.6`**. To install run:
> 
> ```shell
> $ pip install -r requirements.txt
> ```
> 
> ## Environments
> YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):
> 
> * **Google Colab Notebook** with free GPU: [![Open In Colab](https://camo.githubusercontent.com/84f0493939e0c4de4e6dbe113251b4bfb5353e57134ffd9fcab6b8714514d4d1/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb)
> * **Kaggle Notebook** with free GPU: https://www.kaggle.com/models/ultralytics/yolov5
> * **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
> * **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://camo.githubusercontent.com/280faedaf431e4c0c24fdb30ec00a66d627404e5c4c498210d3f014dd58c2c7e/68747470733a2f2f696d672e736869656c64732e696f2f646f636b65722f70756c6c732f756c7472616c79746963732f796f6c6f76353f6c6f676f3d646f636b6572)
> 
> ## Status
> ![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)
> 
> If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu every 24 hours and on every commit.

Oh ! I can  train it  success.  However ,  I  use  the  batch size of  64,  and  the  cuda  memory  only  use  about  1400M .  I use  the  pre-trained  model  of  yolov5x.  Why？  I train  yolov5  three  month  ago   and  i  use  at  least  18G  on  the  Tesla  V-100.

**Comment by glenn-jocher** [comment]
@mcjqwer CUDA memory consumption may be affected by updates to pytorch and YOLOv5 code. Please raise a bug report with code to reproduce if you believe there is a problem.

**Comment by mcjqwer** [comment]
i&nbsp; &nbsp;use&nbsp; &nbsp;the&nbsp; &nbsp;pytorch1.7.0



---Original---

**Comment by mcjqwer** [comment]
I&nbsp; want&nbsp; to&nbsp; &nbsp;ask&nbsp; &nbsp;you&nbsp; &nbsp; a&nbsp; &nbsp;careless&nbsp; &nbsp;problem.&nbsp;
I&nbsp; use&nbsp; &nbsp;the&nbsp; &nbsp;command&nbsp; &nbsp;:&nbsp; --cfg&nbsp; &nbsp;yolov5s.yaml&nbsp; &nbsp; --weights&nbsp; &nbsp;'yolov5x.pt' !&nbsp; However,&nbsp; it&nbsp; &nbsp;don't&nbsp; report&nbsp; &nbsp;an&nbsp; &nbsp;error......So,&nbsp; i&nbsp; want&nbsp; &nbsp;to&nbsp; &nbsp;know&nbsp; &nbsp;it&nbsp; &nbsp;will&nbsp; &nbsp;train&nbsp; &nbsp;base&nbsp; on&nbsp; &nbsp; which&nbsp; &nbsp; pt&nbsp; file?&nbsp; &nbsp;s&nbsp; &nbsp; or&nbsp; &nbsp; x?&nbsp; &nbsp;it&nbsp; has&nbsp; &nbsp;run&nbsp; &nbsp;3000+epochs,&nbsp; it's&nbsp; &nbsp;weight&nbsp; &nbsp;file&nbsp; &nbsp;is&nbsp; &nbsp;55M.........

---Original---

**Comment by pderrenger** [comment]
The training will use the weights from `yolov5x.pt` since that's specified with `--weights`. The `--cfg yolov5s.yaml` defines the model architecture, but the weights file determines the starting point for training. If you have further questions, feel free to ask!
