### ISSUE TITLE
still ModuleNotFoundError: No module named 'models'

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#134]
## 🐛 Bug
ModuleNotFoundError: No module named 'models'

## To Reproduce (REQUIRED)

Input:
python models/onnx_export.py 

Output:
```
Traceback (most recent call last):
  File "models/onnx_export.py", line 12, in <module>
    from models.common import *
ModuleNotFoundError: No module named 'models'

```

## Environment
docker

**Comment by dlawrences** [comment]
Clone the latest repository version. It includes a file named ``__init__.py`` placed in the models directory that fixes this issue.

Prolly the docker image has not been updated just yet?

Cheers

**Comment by alicera** [comment]
I glone the new and it is still the status

**Comment by glenn-jocher** [comment]
@alicera the correct usage is displayed in the file:
https://github.com/ultralytics/yolov5/blob/80b82e8bdea882ead6e066564f9162b9935b9d9e/models/onnx_export.py#L1-L7

@dlawrences if I run @alicera command I see the same error message, but this is not the intended usage, which is shown above.

**Comment by glenn-jocher** [comment]
ah, I just noticed, the import torch is not needed. I've removed it in e249792c2f2e19e55f676185811693a29e805632

**Comment by tsing90** [comment]
I cloned the newest code, and followed the usage instruction in `onnx_export.py`, but still got an error:

````
Traceback (most recent call last):
  File "models/onnx_export.py", line 39, in <module>
    onnx.checker.check_model(model)  # check onnx model
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/onnx/checker.py", line 86, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Node () has input size 4 not in range [min=2, max=2].

==> Context: Bad node spec: input: "476" input: "496" input: "496" input: "503" output: "504" op_type: "Resize" attribute { name: "coordinate_transformation_mode" s: "asymmetric" type: STRING } attribute { name: "cubic_coeff_a" f: -0.75 type: FLOAT } attribute { name: "mode" s: "nearest" type: STRING } attribute { name: "nearest_mode" s: "floor" type: STRING }
````
my running command is:
`export PYTHONPATH="$PWD" && python models/onnx_export.py --weights ./weights/yolov5l.pt`

**Comment by glenn-jocher** [comment]
@tsing90 your error is not reproducible. Try using a working environment:
https://github.com/ultralytics/yolov5#reproduce-our-environment

<img width="970" alt="Screen Shot 2020-06-24 at 10 58 05 AM" src="https://user-images.githubusercontent.com/26833433/85608124-9fca0800-b609-11ea-9a2f-2e9147e46608.png">
