### ISSUE TITLE
Class Activation Map

### ISSUE THREAD

**Issue by rvijgen** [ultralytics/yolov5#1341]
I would like to generate class activation maps from custom trained weights. I haven't been able to find any pointers as to how to implement this with YOLOv5.

Any help would be appreciated.

**Comment by glenn-jocher** [comment]
@rvijgen I have no idea what that is. You may want to include significantly more information when you post questions, such as references, links, examples etc.

**Comment by rvijgen** [comment]
I am looking to visualise the class activations as in this example
https://github.com/utkuozbulak/pytorch-cnn-visualizations#gradient-visualization
or as in this image

![cat_dog_ScoreCAM_On_Image](https://user-images.githubusercontent.com/1857817/98799896-ffd21700-240f-11eb-9e08-58d4c4c60f31.png)

Hope this clarifies my question

**Comment by glenn-jocher** [comment]
@rvijgen I think your question pertains to classification rather than object detection. YOLOv5 does object detection in it's default configuration.

**Comment by glenn-jocher** [comment]
For reference:

![Screenshot 2020-11-11 at 12 05 15](https://user-images.githubusercontent.com/26833433/98804236-34e16800-2416-11eb-864c-e81d291fe83f.jpg)

**Comment by rvijgen** [comment]
I was (perhaps incorrectly) assuming that a trained object detection model would activate and could be visualized similar to a classification model. Are you saying that Class Activation Mapping cannot be done on an object detection model such as YOLOv5?

**Comment by glenn-jocher** [comment]
I have no idea. I'm just pointing out your reference applies the technique to classification models, which are very different than object detection models.

You may want to raise your issue at the source you mentioned.
