### ISSUE TITLE
How to make it faster

### ISSUE THREAD

**Issue by amadeok** [ultralytics/yolov5#1343]
Hello,
I was able to train a model with custom dataset with the small model, it runs at about 2fps on my i5 3570k on ubuntu 20.04.
Could you advice any way to make  run faster? I only have a amd r7 250 gpu. 
thanks

**Comment by glenn-jocher** [comment]
@amadeok reduce --img-size.

A 2x reduction in --img-size will produce a 4x reduction in FLOPS and a corresponding increase in FPS.
