### ISSUE TITLE
How to recover optimizer parameters？

### ISSUE THREAD

**Issue by sakurasakura1996** [ultralytics/yolov5#1345]
## ❔Question
Hello, I want to ask you a question. I trained yolov5s with 500 epochs and saved the last.pt.Now, I want to continue 500 epochs based on the last.pt.How should I do? When I use --resume command,  It doesn't work. I want to know how to load optimizer parameters or is that already implemented in your code.

**Comment by sakurasakura1996** [comment]
Is the parameters of the optimizer part not saved in the yolov5 code?

**Comment by glenn-jocher** [comment]
@sakurasakura1996 all run arguments and parameters are saved in your experiment folder, i.e. `runs/train/exp0`

**Comment by glenn-jocher** [comment]
@sakurasakura1996 also, --resume is only intended for resuming interrupted runs, not for continuing fully completed runs.
