### ISSUE TITLE
Any Android APP for YOLOv5 like iDetection for YOLOv5 in IOS？

### ISSUE THREAD

**Issue by yao-zheng-yi** [ultralytics/yolov5#1346]
Hi, recently I use the APP iDetection in iPhone SE and iPad 2020，YOLOv5s detect FPS can reach 30.
But in Android, the FPS of applications for YOLOv5 only reach 5, any higher FPS APP for YOLOv5 in Android? Or are you also code a APP for Android like iDetection in IOS? @glenn-jocher

**Comment by glenn-jocher** [comment]
@yao-zheng-yi good question. Android is a bit more complicated, but there is progress here in PR #1127.

Please review there and contribute anything you can as well!

**Comment by yao-zheng-yi** [comment]
> @yao-zheng-yi good question. Android is a bit more complicated, but there is progress here in PR #1127.
> 
> Please review there and contribute anything you can as well!

Thanks, I will try

**Comment by ebyau** [comment]
@yao-zheng-yi to deploy yolov5 model to andriod do i need to convert the model to onnx or tflite?

**Comment by yao-zheng-yi** [comment]
> @yao-zheng-yi to deploy yolov5 model to andriod do i need to convert the model to onnx or tflite?

yes，I use NCNN
