### ISSUE TITLE
yolo.py中参数m.f和m.i ，这里面的f和i是代表什么？

### ISSUE THREAD

**Issue by XIEdeda** [ultralytics/yolov5#1347]
## ❔Question
![image](https://user-images.githubusercontent.com/68369130/98788889-74bb4600-243c-11eb-8764-262be7c87337.png)

**Comment by zhiqwang** [comment]
Hi @XIEdeda the `i` and `f` comes from

https://github.com/ultralytics/yolov5/blob/104f5418ea1642bc963269a1b0d09d607285d62f/models/yolo.py#L252

**Comment by glenn-jocher** [comment]
Yes, this is the index of the module `m.i`, and the index of the input `m.f`, f i.e. from layer 2.

**Comment by XIEdeda** [comment]
@zhiqwang @glenn-jocher  Thank you
