### ISSUE TITLE
the output of onnx does not mach the output of best.pt which is trained by own dataset

### ISSUE THREAD

**Issue by JiaoPaner** [ultralytics/yolov5#1348]
## ❔Question

The output of onnx model(best.onnx) does not mach the output of best.pt which is trained by my own dataset.
but the output of onnx model(yolov5s.onnx) mached the output of yolo5s.pt which is provided by the release.
## Additional context
When I export onnx model,I set model.model[-1].export = False  in export.py.

**Comment by cbarburescu** [comment]
@JiaoPaner I have the same issue with my models. Did you find a solution?

**Comment by MarcoRizk** [comment]
Same problem here the predictions are different anyone knows why ?
