### ISSUE TITLE
Distributed training in cluster not correct.

### ISSUE THREAD

**Issue by XinyuDu** [ultralytics/yolov5#135]
The model can be trained correctly on single machine multi gpus.
However, It can't be trained on multi machines multi gpus.

**Comment by xjohnxjohn** [comment]
@XinyuDu I can not train my custom data with multi-gpu. What the environment (pytorch, torchvision, cuda, cudnn version) you used? How much of gpu you training?

**Comment by glenn-jocher** [comment]
@XinyuDu if you could submit a PR for the corrections you had in mind, that would be great!

At the moment and for the foreseeable future multi-machine training is not something we will be able to debug ourselves.

**Comment by Lornatang** [comment]
@XinyuDu @xjohnxjohn @glenn-jocher I have solved this problem, this is a bug of PyTorch.I have fixed it for this and he is running as expected. If you manually build the existing version of PyTorch, this will not go wrong. This may have many bugs that have not been tested in detail. I suggest you execute the following command

run
```bash
pip install torch==1.4.0+cu100 torchvision==0.5.0+cu100 -f https://download.pytorch.org/whl/torch_stable.html
```
More details see: https://github.com/pytorch/pytorch/pull/36503

**Comment by xjohnxjohn** [comment]
@Lornatang It show error "RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM". (I use cuda v.10.0)

**Comment by Lornatang** [comment]
@xjohnxjohn What command do you use, will he get this kind of error?

**Comment by xjohnxjohn** [comment]
> @xjohnxjohn What command do you use, will he get this kind of error?

python train.py --data data/xx.yaml --cfg models/xx_yolov5s.yaml --weights weights/last.pt --img 640 --batch-size 8 --device 0,1

**Comment by xjohnxjohn** [comment]
![image](https://user-images.githubusercontent.com/7420735/85195263-29709180-b2fb-11ea-9070-e56bb4ad8bcc.png)

**Comment by Lornatang** [comment]
![选区_001](https://user-images.githubusercontent.com/31124350/85195328-f7176200-b303-11ea-8c1e-cd1280397bf4.png)
Please print your `conda list`

**Comment by xjohnxjohn** [comment]
> ![选区_001](https://user-images.githubusercontent.com/31124350/85195328-f7176200-b303-11ea-8c1e-cd1280397bf4.png)
> Please print your `conda list`

![image](https://user-images.githubusercontent.com/7420735/85195418-8d478a00-b2fc-11ea-8a39-4b259ab5c7a6.png)
![image](https://user-images.githubusercontent.com/7420735/85195436-b36d2a00-b2fc-11ea-9eb0-39d8f9496cb5.png)
I used different model of gpu, 1 is RTX-2080(8GB) and the other GTX-1080Ti(11 GB)

**Comment by xjohnxjohn** [comment]
I have the notice in the line that I masked.
![image](https://user-images.githubusercontent.com/7420735/85195824-dfd67580-b2ff-11ea-9c1b-dfb2c7a053d6.png)

**Comment by Lornatang** [comment]
Every time you modify the PyTorch version, you need to recompile Apex... 
run
```bash
$ git clone https://github.com/NVIDIA/apex
$ cd apex
$ pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
```

**Comment by XinyuDu** [comment]
> @XinyuDu if you could submit a PR for the corrections you had in mind, that would be great!
> 
> At the moment and for the foreseeable future multi-machine training is not something we will be able to debug ourselves.

Thank you for your replay.

In multi  machines multi gpus scenario, the DistributedSampler should be used for distributing the data. However, I didn't find it in train.py.
