### ISSUE TITLE
How to get the center of the Bounding Box?

### ISSUE THREAD

**Issue by rssoni** [ultralytics/yolov5#1351]
Please, advise:
 how to calculate the area of the Bounding Box and its center (Centroid)?
How to assign colors of bounding box as per a list of colors For example red for Human green for vehicle blue for animals?
Thanks in advance

**Comment by glenn-jocher** [comment]
@rssoni you can find all the variables you need in detect.py. Boxes, classes and confidences are all output and plotted here:
https://github.com/ultralytics/yolov5/blob/104f5418ea1642bc963269a1b0d09d607285d62f/detect.py#L104-L115

**Comment by rssoni** [comment]
@glenn-jocher 
Thanks a lot for the advice

**Comment by titusfx** [comment]
@glenn-jocher I found this answer on a lot of issues, why not just do a method? It looks like a lot of people are solving the same thing, it suggests that is a "needed" method.

**Comment by glenn-jocher** [comment]
@titusfx I don't know what you mean. Hub models offer outputs in a variety of formats including xywh, making your idea redundant.

**Comment by sarath-chandran-98** [comment]
@glenn-jocher 
please help:
how to draw the trajectory for the detected
