### ISSUE TITLE
PyTorch Hub AttributeError: module 'yaml' has no attribute 'FullLoader'

### ISSUE THREAD

**Issue by djalusic** [ultralytics/yolov5#1354]
## 🐛 Bug
I tried to do inference in a Google Colab notebook, but the AttributeError appears while loading the model.

## To Reproduce (REQUIRED)
See the notebook [here](https://colab.research.google.com/drive/1TdAAobWQ13nkaOh7CxC7Y-ne07xP1X2I?usp=sharing).

**Comment by glenn-jocher** [comment]
@drajsel our notebook operates correctly. I tested it just now.
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

1. run Setup
2. run Inference

<img width="1411" alt="Screenshot 2020-11-11 at 17 46 10" src="https://user-images.githubusercontent.com/26833433/98839453-d46a1f00-2445-11eb-9ee0-8eada2f38fe7.png">

**Comment by djalusic** [comment]
@glenn-jocher, thank you for the swift response, but that notebook (your Colab tutorial) doesn't include loading the model from PyTorch Hub, which is the issue here.

**Comment by glenn-jocher** [comment]
@drajsel if you are using PyTorch Hub you should start from the tutorial, which already explains your question. See https://docs.ultralytics.com/yolov5

**Comment by djalusic** [comment]
@glenn-jocher, I missed that `pyyaml` needs to be installed locally. Thanks!

**Comment by glenn-jocher** [comment]
@drajsel yes, see https://github.com/ultralytics/yolov5/blob/master/requirements.txt
