### ISSUE TITLE
The exported label txt seems have problem

### ISSUE THREAD

**Issue by wwdok** [ultralytics/yolov5#1355]
Hi, @glenn-jocher  i manage to use `python detect.py --save-txt` to semi-auto label images, but when i set `Open Dir` and `Change Save Dir` in [labelImg](https://github.com/tzutalin/labelImg/releases/tag/v1.8.1)，the labelImg can not display the exported bbox, and its command line window appears error:
```
Traceback (most recent call last):
  File "<string>", line 1268, in openNextImg
  File "<string>", line 1035, in loadFile
  File "<string>", line 1427, in loadYOLOTXTByFilename
  File "Z:\home\darrenl\tmp\labelImg\build-tools\build\labelImg\out00-PYZ.pyz\libs.yolo_io", line 112, in __init__
  File "Z:\home\darrenl\tmp\labelImg\build-tools\build\labelImg\out00-PYZ.pyz\libs.yolo_io", line 142, in parseYoloFormat
ValueError: too many values to unpack
```
If i set `Change Save Dir`  to another empty folder, it will not occur error, so i doubt it is the problem of exported label txt, could you have a try ?

**Comment by wwdok** [comment]
@glenn-jocher, i found the reason ! Because the exported txt **has a whitespace at the end of each line**, if you delete this whitespace, everything is normal !

**Comment by wwdok** [comment]
Just change the code to `f.write((('%g ' * len(line)).rstrip() + '\n') % line)` solved ~
![image](https://user-images.githubusercontent.com/43233772/98836678-ee732400-247c-11eb-917a-0454e4feda7e.png)

**Comment by glenn-jocher** [comment]
@wwdok ah I see, very interesting, thank you for raising this issue. Your fix looks good. Would you like to submit a PR for this update?

**Comment by wwdok** [comment]
@glenn-jocher Yeah, it is my first time to submit a PR, so i must carefuly learn how to do it, i will do it tomorrow😄

**Comment by carloslopezjoya** [comment]
Hello @wwdok ,  How to get bounding box coordinates in YOLO object detection and store them in variable?

**Comment by wwdok** [comment]
@carloslopezjoya You can use `python detect.py --save-txt` to generate a txt file, inside it, it contains the class id, four coordinates fraction, just like the one you prepared for training. If you want to get coordinates in python codes, they are named `xyxy`, you can search them in `detect.py`.

**Comment by carloslopezjoya** [comment]
@wwdok thanks for your answer, In my case I am running it in an IDE 'spyder' I added return xyxy and it does not return anything, it does not even save the txt
These are my configurations
![image](https://user-images.githubusercontent.com/50337865/98969383-c7e4d580-24dc-11eb-8e90-d9bbbee497dd.png)
![image](https://user-images.githubusercontent.com/50337865/98969470-ddf29600-24dc-11eb-8169-e24d9966fa5b.png)

**Comment by carloslopezjoya** [comment]
@wwdok In itself I need to store bounding box coordinates in YOLO object detection and store them in a variable

**Comment by glenn-jocher** [comment]
@carloslopezjoya `python detect.py --save-txt` saves labels.

**Comment by carloslopezjoya** [comment]
@glenn-jocher I know, in my case I use this  python detect.py --weights best.pt --img 416 --conf 0.4 --source test\images --save-txt and it works, I just need to run it from my IDE and I can't store xyxy in a variable and load in ram

**Comment by carloslopezjoya** [comment]
@glenn-jocher  I am creating an object counter, if I need to store the xyxy coordinates in a variable to manipulate them at the same time

**Comment by wwdok** [comment]
@carloslopezjoya you could try out `(torch.tensor(xyxy).view(1, 4)).tolist()[0]` and print out to verify it.
![image](https://user-images.githubusercontent.com/43233772/99140581-0cf43d80-267e-11eb-8b30-7c9355c1a906.png)
![image](https://user-images.githubusercontent.com/43233772/99140594-25fcee80-267e-11eb-9cd5-57996e6e927e.png)

**Comment by wwdok** [comment]
Hi, @glenn-jocher , I found a place that could be improved, that is adding  `assert out != source, 'Please set --save-dir to be different from --source '` , if someone set them the same, then the program will **delete all the images in the source folder**,  because the name of the image to be generated is the same as the name in the source folder, if he/her didn't backup the images, that will be an accident ~
![image](https://user-images.githubusercontent.com/43233772/99140811-f5b64f80-267f-11eb-94e3-cba48ba61be8.png)

**Comment by glenn-jocher** [comment]
@wwdok thanks for the warning! The recent PR below from a few days ago created a new common saving structure across all the 3 main files (train, test, detect). The repo will now not overwrite an existing directory unless --exist-ok is passed as an argument. If the project/name directory already exists it will be incremented to project/name2 automatically.

- Unified '/project/name' results saving #1377

**Comment by glenn-jocher** [comment]
@wwdok in the case of detect.py, --output is now --project/--name

**Comment by wwdok** [comment]
@glenn-jocher  Glad to see the file structure becomes more organized and robust !

**Comment by carloslopezjoya** [comment]
> @carloslopezjoya , podrías probar `(torch.tensor(xyxy).view(1, 4)).tolist()[0]`e imprimir para verificarlo.
> ![imagen](https://user-images.githubusercontent.com/43233772/99140581-0cf43d80-267e-11eb-8b30-7c9355c1a906.png)
> ![imagen](https://user-images.githubusercontent.com/43233772/99140594-25fcee80-267e-11eb-9cd5-57996e6e927e.png)

thanks @wwdok

**Comment by glenn-jocher** [comment]
Removing TODO, original issue resolved by PR.
