### ISSUE TITLE
how to get YOLO v5 confidence score

### ISSUE THREAD

**Issue by KangHoyong** [ultralytics/yolov5#1359]
## ❔Question

hi 

how to get YOLO v5 confidence score in code ?

**Comment by NanoCode012** [comment]
https://github.com/ultralytics/yolov5/blob/f6b3c96966d963a4c69736c8691f068e5b554247/detect.py#L158

**Comment by qayyumnazir** [comment]
I already add the argument on my command and it still doesn't save the confidence.

here's my command : python detect.py --source C:\Users\Rapid\Desktop\test --weights C:\Users\Rapid\Desktop\yolov5\runs\train\exp5\weights\best.pt --save-txt --save-conf

> https://github.com/ultralytics/yolov5/blob/f6b3c96966d963a4c69736c8691f068e5b554247/detect.py#L158

**Comment by glenn-jocher** [comment]
@qayyumnazir `--save-conf` works correctly. A 6th column is added the the *.txt labels with confidence:

<img width="1582" alt="Screen Shot 2021-12-30 at 8 23 37 AM" src="https://user-images.githubusercontent.com/26833433/147769867-0ac213cf-cade-4bac-8f72-516ab223aae2.png">

**Comment by qayyumnazir** [comment]
Try to run detect on google collab instead of doing it locally, and it works, thank you!

**Comment by Nadeemb10** [comment]
@glenn-jocher does it not save confidence scores when we run it locally?

**Comment by glenn-jocher** [comment]
Hello @Nadeemb10, thanks for your question. The `--save-conf` argument does indeed save confidence scores when running `detect.py` locally. If you're running into issues with this, it would be helpful to provide more information such as the specific command you're using. Please also make sure you're running the latest version of YOLOv5 by pulling from the repository. If the issue persists, feel free to share additional details and we will do our best to assist you.
