### ISSUE TITLE
Train custom dataset without weights

### ISSUE THREAD

**Issue by CuongNN218** [ultralytics/yolov5#1360]
## ❔Question
Thanks for your great works,
I want to train my model without pretrained weights. How can I do it ?

**Comment by CuongNN218** [comment]
@glenn-jocher Can you help me ?

**Comment by NanoCode012** [comment]
Pass `--weights ‘’` as an argument

**Comment by CuongNN218** [comment]
> Pass `--weights ‘’` as an argument

I just try it but not work for me

**Comment by KangHoyong** [comment]
https://github.com/ultralytics/yolov5/blob/master/train.py#L391 

parser.add_argument('--weights', type=str, default='yolov5s.pt', help='initial weights path') 
change code 
parser.add_argument('--weights', type=str, default='', help='initial weights path')

**Comment by glenn-jocher** [comment]
@cuong12ly1 Custom Training Tutorial already explains this:
https://docs.ultralytics.com/yolov5/tutorials/train_custom_data#5-train
