### ISSUE TITLE
test set mAP

### ISSUE THREAD

**Issue by yinyuhangi** [ultralytics/yolov5#1362]
## ❔Question
I am sorry to trouble you. I have trained 100 epochs. During the training, each epoch was automatically tested, and the mAP@0.5 of the last epoch was 0.465.But I use test.py for testing, and mAP@0.5 for the same test set is 0.459. Why is that? Is it because the mAP went down after the model was automatically pruned? Looking forward to your answers.

**Comment by yinyuhangi** [comment]
I found that after training, there was an operation on srtip_optimizer, which turned FP32 into FP16. Is that the reason why the mAP drops when you run test.py?

**Comment by glenn-jocher** [comment]
@yinyuhangi your numbers are identical for all intents and purposes.

**Comment by yinyuhangi** [comment]
@glenn-jocher How do you stop the model from switching from FP32 to FP16？Because I want to keep the high mAP model.

**Comment by glenn-jocher** [comment]
@yinyuhangi FP32 and FP16 models perform inference identically to numerical precision in our experiments. This is a non-issue.

**Comment by yinyuhangi** [comment]
@glenn-jocher Thanks a lot. But I still don't understand, I have trained 100 epochs. During the training, each epoch was automatically tested, and the mAP@0.5 of the last epoch was 0.465. But I use test.py for testing, and mAP@0.5 for the same test set is 0.459. Why is that?
