### ISSUE TITLE
Will empty labels negative samples be used for training?

### ISSUE THREAD

**Issue by yunchangxiaoguan** [ultralytics/yolov5#1363]
## Additional context
I only train one class object,but i need negative to prevent model detect false object,so i make empty label to negative samples,dose it will be training?thanks

**Comment by Laughing-q** [comment]
it seems that empty labels will be trained ( reference [line 531](https://github.com/ultralytics/yolov5/blob/f6b3c96966d963a4c69736c8691f068e5b554247/utils/general.py#L531) ), but won't be involved when testing(reference [line 281](https://github.com/ultralytics/yolov5/blob/f6b3c96966d963a4c69736c8691f068e5b554247/utils/general.py#L281) and [line 218](https://github.com/ultralytics/yolov5/blob/f6b3c96966d963a4c69736c8691f068e5b554247/test.py#L218) ).
but i'm not so sure.
hope author reply you soon.

**Comment by yunchangxiaoguan** [comment]
> 似乎空标签将被训练（参考[线531](https://github.com/ultralytics/yolov5/blob/f6b3c96966d963a4c69736c8691f068e5b554247/utils/general.py#L531)），但在测试时将不涉及（参考[线281](https://github.com/ultralytics/yolov5/blob/f6b3c96966d963a4c69736c8691f068e5b554247/utils/general.py#L281)和[218](https://github.com/ultralytics/yolov5/blob/f6b3c96966d963a4c69736c8691f068e5b554247/test.py#L218)）。
> 但我不太确定。
> 希望作者尽快回复您。

谢谢大佬

**Comment by glenn-jocher** [comment]
@yunchangxiaoguan all images contribute to the loss function during training.

**Comment by yunchangxiaoguan** [comment]
> @yunchangxiaoguan all images contribute to the loss function during training.

thanks
