### ISSUE TITLE
docker ipc host mode

### ISSUE THREAD

**Issue by QuarTerll** [ultralytics/yolov5#1364]
It is perfect when I use the yolov5 docker image in a **remote machine** through the command line in MobaXterm which is a terminal tool.

But I am trying to do this through PyCharm with ssh service so that I can change and debug code in time on **local computer** rather than debugging with vim.

However, I think the docker parameter "--ipc=host" makes this failed.

I can access the container in local command in MobaXterm with ssh but it is not working on my local computer in PyCharm with ssh service.

What can I do?
Thank you!

**Comment by glenn-jocher** [comment]
@QuarTerll oh, that's an interesting question. I don't know, but if you figure out a solution please update this thread.

We do a lot of training on GCP VMs, with and without docker, it would be nice to be able to interact with those instances through PyCharm.

**Comment by QuarTerll** [comment]
> @QuarTerll oh, that's an interesting question. I don't know, but if you figure out a solution please update this thread.
> 
> We do a lot of training on GCP VMs, with and without docker, it would be nice to be able to interact with those instances through PyCharm.

@glenn-jocher I have solved the problem. Just use normal way for this. 
1. Expose a port from the remote host to the docker image using the parameter -p when you run an image, such as xxx:22. Port 22 is the default used by service ssh.
such as `docker run -p 4567:22 ...`
2. Then config the service ssh such as password, permission for root login, and other configurations you need.
3. Finally, config the Pycharm. Tools -> Deployment -> Configuration -> choose SFTP 

In my case, I just forgot to expose a port at the beginning so I choose to config the host network to do that. And our remote host just removed to a new IP address, so there is something like an ssh key mismatched problem then I reset it...Bala Bala

So it worked even if I use the parameter "--ipc=host".

Last time I didn't try this cus I don't want to commit a new image for a personal reason :)  Ok, just lazy to run again :<
