### ISSUE TITLE
model.names showing names which are previously trained on. First I trained on 4 objects after that I removed 2 objects images and labels and retrained model. But that model.names showing previous 4 objects. Please correct me how to remove product and retrain it if I am wrong.

### ISSUE THREAD

**Issue by abpanchal95** [ultralytics/yolov5#1365]

**Comment by abpanchal95** [comment]
Also I modified data.yaml and custom_model.yaml as per new objects. And also deleted labels cache files.

**Comment by glenn-jocher** [comment]
@abpanchal95 cache files automatically delete themselves when their underlying data changes.

Training on new data/classes is the default use case, no extra steps are required beyond what we have in the Custom Training Tutorial. Please see:
https://docs.ultralytics.com/yolov5/tutorials/train_custom_data

**Comment by abpanchal95** [comment]
Could you tell me if I train a model on 5 object but now I want to remove one of them, what changes I need to do?

**Comment by glenn-jocher** [comment]
@abpanchal95 Training on new data/classes from previously trained --weights is the default use case, no extra steps are required beyond what we have in the Custom Training Tutorial. Please see:
https://docs.ultralytics.com/yolov5/tutorials/train_custom_data
