### ISSUE TITLE
I want to know the contents of runs/labels.png

### ISSUE THREAD

**Issue by KangHoyong** [ultralytics/yolov5#1366]
## Additional context
Hi 
I want to know the contents of runs/labels.png

What does width and height mean? And what does x and y mean?

**Comment by AndreaBrg** [comment]
There are 3 plots:
- Top left: histogram of class dristribution.
- Top right: heatmap of labels position. The center of each label is plotted as a point.
- Bottom left: heatmap of labels dimension: The width and height of each label is plotted as a point.

Note that in YOLO labels values are in the range [0, 1].

**Comment by Rollson** [comment]
@glenn-jocher , @AndreaBrg  Please, I also wanted to ask. Is the plot for the entire dataset (training+validation)?

**Comment by glenn-jocher** [comment]
labels.png plots your training set statistics.

**Comment by Czyfczynski** [comment]
Does the labels.png represent the labels before or after augmentation has been applied?

**Comment by glenn-jocher** [comment]
@Czyfczynski the labels.png file represents the labels after augmentation has been applied.
