### ISSUE TITLE
The result of coco128 is ten percent higher then your result. Is it normal ?

### ISSUE THREAD

**Issue by liutianling** [ultralytics/yolov5#1367]
Here is my command and result
![image](https://user-images.githubusercontent.com/32763852/98915286-ab5c9380-2504-11eb-9484-eac85e8671bb.png)

![image](https://user-images.githubusercontent.com/32763852/98916412-1c507b00-2506-11eb-8e75-d6ee7784852f.png)

**Comment by glenn-jocher** [comment]
@liutianling your results are standard. We don't display coco128 mAP anywhere so I don't know what you are referring to.
