### ISSUE TITLE
DDP

### ISSUE THREAD

**Issue by llzhaoshuo** [ultralytics/yolov5#1368]
## ❔Question
When I train my own datasets with DDP mode,do master and slave nodes have to be fully synchronized?
## Additional context
When the slave node first completes and finishes the training, but the master node has not yet completed the training, the master node cannot continue the rest of the training.

**Comment by glenn-jocher** [comment]
@llzhaoshuo sounds about right, but you might want to raise your issue on the pytorch repo as this seems to be a generic pytorch question.
