### ISSUE TITLE
Is it possible to not show a probability along with a bounding box?

### ISSUE THREAD

**Issue by Surayuth** [ultralytics/yolov5#1369]
## ❔Question
Can someone guide me which parts of the code I should look into if I want only the bounding boxes?

**Comment by glenn-jocher** [comment]
@Surayuth see PyTorch Hub tutorial for simpler plotting without labels:
https://docs.ultralytics.com/yolov5

**Comment by Surayuth** [comment]
@glenn-jocher Thank you very much
