### ISSUE TITLE
Couldn't close file exception during training

### ISSUE THREAD

**Issue by spinlud** [ultralytics/yolov5#137]
## 🐛 Bug
I've tried to run (on cpu) the default training example with the `coco128` dataset, but after some epochs I got an exception `libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Couldn't close file`: 

![image](https://user-images.githubusercontent.com/12783208/85126413-b9e0a080-b22d-11ea-9e0c-b6e5f4522ec5.png)

## To Reproduce (REQUIRED)
```shell
python train.py --img-size 256 --batch 16 --epochs 5 --data ./data/coco128.yaml --cfg ./models/yolov5s.yaml --weights ''
```

Output:
```shell
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Couldn't close file
```
See screenshot above.

## Expected behavior
Training should complete

## Environment

 - OS: MacOS 10.15.4
 - GPU No

## Additional context
I am using `conda` environment where I have installed the required dependencies for this repo:

![image](https://user-images.githubusercontent.com/12783208/85126746-602ca600-b22e-11ea-85a1-1608c8221a01.png)

**Comment by glenn-jocher** [comment]
@spinlud that's interesting. I sometimes see this locally as well on my macbook pro with conda environment, but I never see it in colab or docker. One of our unit tests is actually to train 3 epochs, test, and detect with both gpu and cpu, and these tests are currently passing in colab.

Perhaps setting the number of workers to 1 in train.py may resolve this, I'm not sure:
https://github.com/ultralytics/yolov5/blob/80b82e8bdea882ead6e066564f9162b9935b9d9e/train.py#L164-L166

In any case though, you should probably never train on cpu, there's no real use case for it, as a colab instance can train more in 1 hour than your cpu can in 1 day.

**Comment by Lornatang** [comment]
@spinlud 
run 
```bash
conda uninstall matplotlib
```

More details see： https://github.com/gammapy/gammapy/issues/2453

**Comment by spinlud** [comment]
> @spinlud that's interesting. I sometimes see this locally as well on my macbook pro with conda environment, but I never see it in colab or docker. One of our unit tests is actually to train 3 epochs, test, and detect with both gpu and cpu, and these tests are currently passing in colab.
> 
> Perhaps setting the number of workers to 1 in train.py may resolve this, I'm not sure:
> https://github.com/ultralytics/yolov5/blob/80b82e8bdea882ead6e066564f9162b9935b9d9e/train.py#L164-L166
> 
> In any case though, you should probably never train on cpu, there's no real use case for it, as a colab instance can train more in 1 hour than your cpu can in 1 day.

Hi, thanks for the reply!
I've set number of workers to 1, but got the same error unfortunately:

```python
batch_size = min(batch_size, len(dataset))
# nw = min([os.cpu_count(), batch_size if batch_size > 1 else 0, 8])  # number of workers
nw = 1  # hack
```

![image](https://user-images.githubusercontent.com/12783208/85235568-42219a00-b416-11ea-8b5b-ac56bf51a9c7.png)

**Comment by glenn-jocher** [comment]
Ok. If it is reproducible then you should probably raise an issue on the pytorch repo, as it seems to originate from the Pytorch Dataloader class.

**Comment by mrk230** [comment]
@spinlud I got it work if you set num workers = 0 instead of 1. Obviously not ideal, but seems to be an overall issue with the python multiprocessing library running on Catalina

**Comment by glenn-jocher** [comment]
@mrk230 see same effect on Catalina also. Agree it's some sort of python multiprocessing problem.

**Comment by spinlud** [comment]
Thank you guys!
