### ISSUE TITLE
resume error

### ISSUE THREAD

**Issue by carlsummer** [ultralytics/yolov5#1371]
## ❔Question
resume

## Additional context
python train.py --epochs 100 --image-weights --multi-scale --batch-size 6 --cache-images --resume runs/exp61/weights/last.pt 
![image](https://user-images.githubusercontent.com/16281965/98931130-97bb2800-2518-11eb-8450-b299d089a927.png)

**Comment by glenn-jocher** [comment]
@carlsummer --resume accepts no additional arguments. Your only options are:

```bash
python train.py --resume  # automatically finds most recent last.pt
python train.py --resume path/to/last.pt
```

**Comment by carlsummer** [comment]
thanks
![image](https://user-images.githubusercontent.com/16281965/98934255-c1764e00-251c-11eb-874b-d9e668eae5a9.png)
I’ll try a bigger graphics card tomorrow
You are my fastest reply, I like it
thanks

**Comment by carlsummer** [comment]
python train.py --batch-size 2 --resume runs/exp61_yolov5x_solarcell/weights/last.pt
that's it。
thanks
