### ISSUE TITLE
W&B Bug in Kaggle Notebook

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/yolov5#1372]
## 🐛 Bug
It is impossible to select a W&B option in the Kaggle notebook when training (on Chrome at least, other browsers not tested). This problem is compounded by the fact that wandb appears to be a default package in the kaggle notebook environment, meaning the issue is impossible to avoid by default. @AyushExel can you take a look at this please? 
<img width="1312" alt="Screenshot 2020-11-12 at 12 12 29" src="https://user-images.githubusercontent.com/26833433/98933416-e0ef8580-24e0-11eb-8ae8-a20e9f950715.png">

## To Reproduce (REQUIRED)

1. Run **Setup** cell
2. Run **Train** cell here and try to select a W&B option
<img width="1527" alt="Screenshot 2020-11-12 at 12 13 49" src="https://user-images.githubusercontent.com/26833433/98933367-d1703c80-24e0-11eb-9981-fbf0b1043e9b.png">

## Environment
https://www.kaggle.com/ultralytics/yolov5

**Comment by AyushExel** [comment]
@glenn-jocher seems like a kaggle kernel specific problem. This doesn't happen on colab. There's a simple workaround that I just tested. Calling `wandb.login()` manually solves this problem.
![Screenshot (171)](https://user-images.githubusercontent.com/15766192/98934437-18bdf380-2508-11eb-8c17-9d791ccd9af3.png)

**Comment by glenn-jocher** [comment]
@AyushExel what do you think the best way to handle this is uniformly between the Colab and Kaggle notebooks? We need to maintain a single base notebook for reduced maintenance. 

I was thinking maybe a seperate code block before train, that would install and init with a single click? 

In any case you probably want to pass this failure mode up to the maintainers of the login code to see if they can get this working natively in kaggle also.

**Comment by AyushExel** [comment]
@glenn-jocher Yes a separate init block before training would be the way to go for now. I'll pass this on to the maintainers. Right now the team is busy launching this [awesome dataset visualization feature](https://docs.wandb.com/datasets-and-predictions) that I told you about. But this will be fixed as soon as they're done with the launch.

**Comment by glenn-jocher** [comment]
Saving this here, can be inlined after existing `# Start tensorboard (optional)` cell.
```python
# Start Weights & Biases (optional)
%pip install -q wandb  #  use 'wandb disable'/'wandb enable' to turn off/on
!wandb login  
```

**Comment by glenn-jocher** [comment]
@AyushExel I tested the Kaggle notebook again and this bug is resolved now :) 

It appears that wandb is no longer a default installed package in their notebook environment, so the model trains without asking for a wandb login now. When I try to install wandb though I'm not able to paste in my key still. This happens to me in Chrome, I have not tested other browsers. The same op works fine in the Colab notebook, but Kaggle in particular seems to have issues with their UI when it comes to inserting values at prompts. Have you been able to complete this login in a kaggle notebook?

<img width="1337" alt="Screen Shot 2020-12-08 at 7 31 06 AM" src="https://user-images.githubusercontent.com/26833433/101503923-7e46a980-3927-11eb-9616-ed3be1214ecb.png">

**Comment by AyushExel** [comment]
@glenn-jocher I'll file a ticket today to get this fixed. I filed them for media panel viewing error and Recursion depth error but this error slipped out of my mind. 
Also, I needed help with a  code snippet from yolo repo. Can you please check your slack?

**Comment by glenn-jocher** [comment]
@AyushExel great, thanks! I just arrived in California, I have to take care of a few things, but I will get back on Slack later today.

**Comment by glenn-jocher** [comment]
@AyushExel verified this issue still exists in the latest (version 9) notebook today March 4th.

**Comment by AyushExel** [comment]
The issue occurs because Kaggle doesn't allow passing password in traditional way. you cannot directly copy a secret in kaggle console. Here the workaround is to save the API key as a kaggle secret.
Steps:
Click on add-ons in the kernel -> secrets -> add secret
Now copy the api key from wandb.ai/settings under any name you desire( in this case it's "wandb-key")
![Screenshot from 2021-03-05 21-14-45](https://user-images.githubusercontent.com/15766192/110138690-3b964f80-7df8-11eb-8af6-2e5d0ed4045f.png)
```
import wandb
 from kaggle_secrets import UserSecretsClient
 user_secrets = UserSecretsClient() 

personal_key_for_api = user_secrets.get_secret("wandb-key")

! wandb login $personal_key_for_api
```

**Comment by glenn-jocher** [comment]
Removing TODO as this is now fixed with the new python login commands now in our Google and Kaggle notebooks:
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb#scrollTo=2fLAV42oNb7M&line=1&uniqifier=1
```python
# Weights & Biases  (optional)
%pip install -q wandb
import wandb
wandb.login()
```

**Comment by valmetisrinivas** [comment]
Hello, I am trying to run my Kaggle notebook in offline mode (with internet off) for a code submission competition. While training WANDB is getting activated and returning an error as it cannot access my WANDB account due to the internet being off. How to avoid wandb while training is on in the kernel? Appreciate inputs.

**Comment by glenn-jocher** [comment]
@valmetisrinivas you can avoid the WANDB activation by removing the WANDB library import and the WANDB logging code from your notebook. This will prevent any attempts to access your WANDB account when running the code. Simply comment out or remove the following lines:

```python
import wandb
wandb.init()
```

By doing this, you can run your Kaggle notebook in offline mode without any issues related to WANDB. Good luck with your code submission competition!

**Comment by valmetisrinivas** [comment]
@glenn-jocher , I did try what you suggested and a few more. But none had worked. Finally, `os.environ[“WANDB_DISABLED”] = “true”` as suggested [here](https://discuss.huggingface.co/t/how-to-turn-wandb-off-in-trainer/6237/2?u=vsrinivas) worked

**Comment by glenn-jocher** [comment]
@valmetisrinivas glad to hear that you found a workaround for disabling WANDB during training by setting `os.environ["WANDB_DISABLED"] = "true"`. Thank you for sharing the solution and the link to the discussion. This will be helpful for others who may encounter a similar issue. If you have any further questions or need any more assistance, feel free to ask. 

Happy coding!

**Comment by valmetisrinivas** [comment]
Thanks Glenn

**Comment by glenn-jocher** [comment]
@valmetisrinivas Glad to hear that you found a workaround for disabling WANDB during training by setting `os.environ["WANDB_DISABLED"] = "true"`. Thank you for sharing the solution. This will be helpful for others who may encounter a similar issue. If you have any further questions or need any more assistance, feel free to ask.

Happy coding!
