### ISSUE TITLE
What is the data in pred = model(img, augment=opt.augment)[1]

### ISSUE THREAD

**Issue by abpanchal95** [ultralytics/yolov5#1375]
Could you explain or give some reference where can I get information about index 1 data?

**Comment by glenn-jocher** [comment]
See model forward function in yolo.py.

**Comment by abpanchal95** [comment]
Can I fetch coordinates and class id from index 1 tensors?

**Comment by glenn-jocher** [comment]
Yes.

**Comment by abpanchal95** [comment]
Could you please help fetching coordinates and  class if from index 1 tensors? Just tell me steps how should I proceed. I am getting 3 tensors at index 1 with sizes (1, 3, 52, 52, 5+nc), (1, 3, 26, 26, 5+nc) and (1, 3, 13, 13, 5+nc).

**Comment by glenn-jocher** [comment]
@abpanchal95 se PyTorch Hub Tutorial:
https://docs.ultralytics.com/yolov5

**Comment by abpanchal95** [comment]
Could you please explain further? I am not getting much from tutorials section.
