### ISSUE TITLE
Recall improvement. 

### ISSUE THREAD

**Issue by pngmafia** [ultralytics/yolov5#1378]
## ❔Question

I'm working on a semi-supervised object detection problem and I need a model that will give high recall. But yolov5 seems to optimize on mAP:0.5. Is there a way I can optimize on recall?
## Additional context
An additional observation, there was no difference in recall when using --conf-thres as 0.1 and 0.0001. Can anyone please explain this?

**Comment by CCRcmcpe** [comment]
I met this problem too, but in a binary classification way. My target is to classify the images into "class `target` detected" and "class `target` undetected", whilst keeping false negative count low. I suppose in this scenario, recall can be more important than AP. But anyone can give a advice how to modify yolov5's parameters to achieve this at training time?

**Comment by CCRcmcpe** [comment]
In the [hyperparameters evolution doc](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution) it seems modifying `fitness(x)` in `utils/metrics.py` can help a bit. I modified the weights to:
```
# Original: w = [0.0, 0.0, 0.1, 0.9]
w = [0.0, 0.8, 0, 0.2]  # weights for [P, R, mAP@0.5, mAP@0.5:0.95]
```
So recall value will affect more how `best.pt` will be saved.
