### ISSUE TITLE
Yolo Versions Speed Comparison

### ISSUE THREAD

**Issue by M-S-KHAN** [ultralytics/yolov5#138]
Hey there!
I would like to know, is YOLO v3-tiny faster and computationally lighter than the smallest version of Yolo-v5s or Yolo-v5s can replace v3-tiny?

**Comment by glenn-jocher** [comment]
@M-S-KHAN there's no comparison to be made. yolov3-tiny only returns about 17 AP, yolov5s gets >35 AP.
https://github.com/ultralytics/yolov3#map
