### ISSUE TITLE
Is it good to mirror the images for training?

### ISSUE THREAD

**Issue by amadeok** [ultralytics/yolov5#1381]
Hello,
I was thinking about mirroring the images of my dataset to have more variety. I mean not just rotate but to flip them symmetrically, 
such as these 2 images: 
![unnamed](https://user-images.githubusercontent.com/43666702/98999928-d06af980-2538-11eb-91e1-56d16788a4bc.png)

Is this good?
thanks

**Comment by glenn-jocher** [comment]
@amadeok left-right flips are already included as part of the YOLOv5 augmentation policy. You can modify augmentation hyperparameters here:
https://github.com/ultralytics/yolov5/blob/04081f810270712ba3a69577c47e5dcfa850fa90/data/hyp.scratch.yaml#L22-L33

**Comment by amadeok** [comment]
> @amadeok left-right flips are already included as part of the YOLOv5 augmentation policy. You can modify augmentation hyperparameters here:
> https://github.com/ultralytics/yolov5/blob/04081f810270712ba3a69577c47e5dcfa850fa90/data/hyp.scratch.yaml#L22-L33

Thanks for reply. 
So there is no need to flip them manually?
What does the `fliplr` variable exactly do?
What is  `degrees` for ?
if i set `degrees` to 15 it will be as if i had added images to the training set that were 15 degrees tilted towards each side?
