### ISSUE TITLE
opt.project bug

### ISSUE THREAD

**Issue by TaoXieSZ** [ultralytics/yolov5#1384]
I notice that the train options are updated. But I find a bug, when I change 'logdir' to 'project' here.

```python
!python train.py --data data/voc.yaml --weights yolov5l.pt \
--hyp '/content/drive/My Drive/CISC849/hyp.geo_mosaic_mixup.yaml' \
--cfg models/yolov5l.yaml \
--batch-size 16 \
--name yolov5l_pretrain_geo_mosaic_mixup \
--project '/content/drive/My Drive/yolov5-checkpoints' \
--resume '/content/drive/My Drive/yolov5-checkpoints/exp36_yolov5l_pretrain_geo_mosaic_mixup/weights/last.pt'
```

## 🐛 Bug
![image](https://user-images.githubusercontent.com/7379039/99023632-f11a6a00-259f-11eb-83db-d678a22e39fb.png)

**Comment by glenn-jocher** [comment]
@ChristopherSTAN hi there. Thanks for the bug report. Yes, --resuming previous models will be broken unfortunately by this change. The fix you recommended is correct, --project has replaced --logdir now in train.py.

**Comment by TaoXieSZ** [comment]
Hi there @glenn-jocher , I am not sure only replacing can fix. I have replace 'logdir' with 'project' and encounter this error.

**Comment by TaoXieSZ** [comment]
And it come out 'AttributeError: 'Namespace' object has no attribute 'project' ', which is very confusing for me, because I just use that option for train.py!

**Comment by glenn-jocher** [comment]
@ChristopherSTAN actually I just tried to train and resume a test run, and I get an error related to posixpath saving to opt.yaml. I'm pushing a fix for that, but I think that's unrelated to your issue.
