### ISSUE TITLE
export model

### ISSUE THREAD

**Issue by ducbluee** [ultralytics/yolov5#1385]
## ❔Question
Why export the onnx model from the pytorch model, the onnx model is twice as heavy as the pytorch model

**Comment by zhiqwang** [comment]
It seems that the pytorch model are saved as `float16` type. So it's smaller than the onnx export model.

**Comment by ducbluee** [comment]
> It seems that the pytorch model are saved as `float16` type. So it's smaller than the onnx export model.

@zhiqwang Oh, so it is, but I have one question, when I use the onnx model to predict the processing speed is much slower than the pytorch model can you help me with this problem

**Comment by zhiqwang** [comment]
Hi @ducbluee , `onnxruntime` support multiple backend such as `tensorrt`, sorry I didn't have much experience there, if you can compile `onnxruntime` with `tensorrt` or something else using gpu, it will speed up your inference (I guess)
