### ISSUE TITLE
Does YOLOv5 use CSPDarknet pre-trained weights in the backbone?

### ISSUE THREAD

**Issue by Madrz** [ultralytics/yolov5#1388]
## ❔Question
I understand that there is an option to train YOLOv5 with COCO pre-trained weights or from the scratch. I was wondering whether the backbone classifier (CSPDarknet) uses pre-trained weights or does it train from the scratch as well when we specify empty weights in training. In other words do we have specify pre-trained or empty weights for the backbone classifier separately? If so how?

## Additional context
I am trying to train on a narrow variety images of a specific object and want to use empty weights in the whole model. I know that there is an option in the training script to initialise pre-trained weights such as COCO. However I am not sure whether the backbone which is a classifier also is affected as well.

**Comment by glenn-jocher** [comment]
@Madrz you can start from a trained model or a randomly initialized model. Regions of the model are not differentiated.
See https://docs.ultralytics.com/yolov5/tutorials/train_custom_data#5-train
