### ISSUE TITLE
To change a .pt file to a .onnx file, ModuleNotFoundError: No module named'models'

### ISSUE THREAD

**Issue by leeyunhome** [ultralytics/yolov5#1389]
## ❔Question
Hello,

Sorry for leaving too many issues.
By the way, I have an additional question.
To change a .pt file to a .onnx file

I ran it like this
ModuleNotFoundError: No module named'models'
Stops with an error saying

Even if I try to install the module using pip install, it rarely works.

Can you tell me how to fix it?

Thank you.

**Comment by glenn-jocher** [comment]
@leeyunhome see Export Tutorial:
https://docs.ultralytics.com/yolov5

**Comment by leeyunhome** [comment]
> @leeyunhome see Export Tutorial:
> https://docs.ultralytics.com/yolov5

Thank you.
