### ISSUE TITLE
--resume on last.pt bug

### ISSUE THREAD

**Issue by marvision-ai** [ultralytics/yolov5#139]
Using a model I trained previously and wanted to perform more epochs to train it.

`python train.py --img 1120 --batch 8 --epochs 15 --data data/customdata.yaml --cfg models/yolov5s_customdata.yaml --weights weights/yolov5s.pt --resume`

I get the following error once the model is loaded. 

> Starting training for 15 epochs...
> Traceback (most recent call last):
>   File "train.py", line 402, in <module>
>     train(hyp)
>   File "train.py", line 360, in train
>     print('%g epochs completed in %.3f hours.\n' % (epoch - start_epoch + 1, (time.time() - t0) / 3600))
> UnboundLocalError: local variable 'epoch' referenced before assignment
>

**Comment by glenn-jocher** [comment]
@mbufi you will get the best results by training completely from start to finish.

--resume has an unresolved bug regarding LR scheduling possibly. It's intended use case was to finish incomplete training sessions, never to train again after training is complete.

**Comment by marvision-ai** [comment]
@glenn-jocher Got it. thanks!

**Comment by glenn-jocher** [comment]
@mbufi if you really want to start training from this model, you should convert it into a backbone first using utils.create_backbone()

**Comment by pranavchat14** [comment]
The value you pass in --epoch should be greater than the number of epochs you've trained your last weights on. 

For example in:  --weights  last_yolov5s_visdrone_100.pt, I trained last_yolov5s_visdrone_100.pt upto 100 epochs, so next time I want to train it for 100 more epoch I will have to pass 200 i.e 100+100.

**Comment by glenn-jocher** [comment]
@pranavchat14 thanks, I've added a check for this in the resume logic, so the source of error should be clearer now.
