### ISSUE TITLE
model size

### ISSUE THREAD

**Issue by cowarder** [ultralytics/yolov5#1393]
## ❔Question
Does the model size change greatly before and after training?

## Additional context
I trained my data with pretrained yolov5m.pt(44MB), I only changed the classnum, but the trained model is 82MB!, how to make the model smaller?

**Comment by glenn-jocher** [comment]
@cowarder your model has not completed training.

**Comment by cowarder** [comment]
@glenn-jocher hi, what do you mean of saying "not completed"? I trained yolov5m 15 epoches, and reload it to do inference, everything is fine, but the fps is low, and model size is large

**Comment by glenn-jocher** [comment]
@cowarder optimizers are stripped upon training completion.
