### ISSUE TITLE
Hyperparameters

### ISSUE THREAD

**Issue by amadeok** [ultralytics/yolov5#1395]
Hello,
I was looking for ways to do data augmentation and i found that yolov5 has some hyperparameters that appear to do that.
I wanted to know for example if i set `degrees` to 15 on `yolov5/data/hyp.scratch.yaml`, this would be the equivalent of adding another version of all the images in the dataset tilted 15 degrees to both sides?
 `fliplr` is set to 0.5 by default, this means that by default it's as if all images were mirrored symmetrically ?
thanks

**Comment by glenn-jocher** [comment]
@amadeok hyperparameters define a uniform distribution which is randomly sampled during dataloading. No new images are ever created, and an image is never presented twice the same way for training. 

**There is no such thing as creating new data**, this is a marketing gimmick propagated by some organizations who don't understand this concept. If I rip a 10 euro bill in 2 and give it back to you you do not have twice as much money.

**Comment by amadeok** [comment]
> @amadeok hyperparameters define a uniform distribution which is randomly sampled during dataloading. No new images are ever created, and an image is never presented twice the same way for training.
> 
> **There is no such thing as creating new data**, this is a marketing gimmick propagated by some organizations who don't understand this concept. If I rip a 10 euro bill in 2 and give it back to you you do not have twice as much money.

Thanks for reply. I understand images are not presented twice. What does "define a uniform distribution which is randomly sampled during dataloading" mean?

**Comment by glenn-jocher** [comment]
https://en.wikipedia.org/wiki/Continuous_uniform_distribution

**Comment by amadeok** [comment]
Ok thanks. So this means that there could be an advantage to adding actual rotated and flipped images to the dataset?

**Comment by glenn-jocher** [comment]
No
