### ISSUE TITLE
data about IoU 

### ISSUE THREAD

**Issue by wanterlim** [ultralytics/yolov5#1401]
## ❔Question
I'm currently working on object detection using yolov. I did training on my model, but i can't find the IoU. Is it the Box val that replaces the the IoU now? 
Here's my training results
![results](https://user-images.githubusercontent.com/63143827/99178985-99b8fd00-274b-11eb-830a-c9d5aa20184a.png)
.

**Comment by glenn-jocher** [comment]
Regression loss is the first column. Regression metric is CIoU.

**Comment by wanterlim** [comment]
![image](https://user-images.githubusercontent.com/63143827/99211202-64b7b380-27fa-11eb-9b8b-93fc9c5ba8ef.png)
So, is this the CIoU that you mentioned?

**Comment by glenn-jocher** [comment]
This is CIoU loss.

**Comment by wanterlim** [comment]
So, where can i find the Regression metric? Sorry,  I'm still confused.

**Comment by glenn-jocher** [comment]
utils/loss.py compute_loss()

**Comment by wanterlim** [comment]
![image](https://user-images.githubusercontent.com/63143827/100193549-98938700-2f26-11eb-9990-1a5c6ea11f08.png)
Thank you for reply, i got this error when i run the code in Colab, can you give me a right code to compute IoU?

**Comment by glenn-jocher** [comment]
@wanterlim loss.py is not a runnable file, it has functions used for loss computation. The function that computes CIoU between pairs of boxes is here:

https://github.com/ultralytics/yolov5/blob/2026d4c5eb4e3e48b5295106db85c844000d95d1/utils/general.py#L188-L231

**Comment by wanterlim** [comment]
Can you give some code to save or dispay my IoU? Do i need to retrain my dataset or using my best_weights? I really apreciate your helps

**Comment by ashu2496** [comment]
> Can you give some code to save or dispay my IoU? Do i need to retrain my dataset or using my best_weights? I really apreciate your helps

If you find work around, would you post it? i am also finding how to get IOU

**Comment by JakobStadlhuber** [comment]
Is it not possible to get the IoU metric somehow?

**Comment by glenn-jocher** [comment]
@JakobStadlhuber I don't know what you're asking

**Comment by JakobStadlhuber** [comment]
I mean we get as a result of the training process for example the mAP@0.5 or the recall... but it would be release helpful to get the IoU to compare it to results of for example papers.
Do you know how to get this metric for trained models @glenn-jocher ?

**Comment by glenn-jocher** [comment]
@JakobStadlhuber IoU is not an output, IoU threshold is an input, i.e.:
```bash
python val.py --iou_thres 0.6
```

See val.py argparser for details:
https://github.com/ultralytics/yolov5/blob/6445a8137e87f67cf3275c70e3585f634260417b/val.py#L318-L347

**Comment by JakobStadlhuber** [comment]
Okay but is't it also a metric like mentioned in this paper:

<img width="466" alt="Bildschirmfoto 2022-02-02 um 00 11 36" src="https://user-images.githubusercontent.com/20328243/152067086-72132b79-9983-46ed-97cf-a17d512c4aa7.png">

I would like to compare this numbers with the results from the training, the problem is that they don't  provide a mAP, so I thought I try to get a IoU metric value over a couple of test pictures.

**Comment by Yash-chowdary** [comment]
I am also trying to know this. Have you got any clarity about Iou mentioned in papers.? @JakobStadlhuber

**Comment by CatB1t** [comment]
> 

If i understand your question right, I tried to implement a simple script to show IoU score on each bounding box for my test data, here's [the code](https://gist.github.com/CatB1t/2c8beb2956c73087e0dc641623078e8b).

the output is very similar to original val.py output but extended with IOU score for each bounding box. **I didn't test on it large data, it may be very slow or something may break**. Here's an example of what the output looks like:

![output](https://i.ibb.co/QbB5HcY/71.jpg)

**Comment by silversurfer11** [comment]
> > 
> 
> If i understand your question right, I tried to implement a simple script to show IoU score on each bounding box for my test data, here's [the code](https://gist.github.com/CatB1t/2c8beb2956c73087e0dc641623078e8b).
> 
> the output is very similar to original val.py output but extended with IOU score for each bounding box. **I didn't test on it large data, it may be very slow or something may break**. Here's an example of what the output looks like:
> 
> ![output](https://camo.githubusercontent.com/50f30992d5a895841187debb53a04fae417adb6a90067e6f7bf793c003d7cfb5/68747470733a2f2f692e6962622e636f2f516242354863592f37312e6a7067)

@CatB1t could you confirm a few things about your code which you linked to calculate the IoU of predicted and ground-truth bounding boxes?

1. Images we want to use have to be stored in a folder like '.../datset_name/images/test' which is to be specified in dataset.yaml file. And the corresponding labels must be stored in '.../datset_name/labels/test'. 
2.  `for r in result.xywh[0]:
            iou = float(max(bbox_iou(r[None, :4], truth[:, 1:] * imgsz)))` In this step on line 80, you are calculating the IoU of each of the predicted bounding box (assuming result.xywh[0] gives a list of predicted bounding boxes) with all the ground-truth bounding boxes in label.txt one by one and selecting the max IoU as the correct one for an object. 
Is my understanding correct? Thanks in advance
