### ISSUE TITLE
resnet101.pt where to download?

### ISSUE THREAD

**Issue by KangHoyong** [ultralytics/yolov5#1404]
## Additional context
Hi 

detect.py 

    if classify:
        modelc = load_classifier(name='resnet101', n=3)  # initialize
        modelc.load_state_dict(torch.load('weights/resnet101.pt', map_location=device)['model']).to(device).eval()
        modelc.to(device).eval()

resnet101.pt where to download?

**Comment by glenn-jocher** [comment]
@KangHoyong you don't download this, you train this yourself.
