### ISSUE TITLE
In the training set dataloader, how can I find that there is no data enhancement,How can I debug the data enhancement function in the training set dataloader

### ISSUE THREAD

**Issue by XIEdeda** [ultralytics/yolov5#1405]
## Additional context
![image](https://user-images.githubusercontent.com/68369130/99224920-2504c200-2822-11eb-800a-ed552d7ea0a2.png)

**Comment by glenn-jocher** [comment]
@XIEdeda you can modify data augmentation hyperparameters in https://github.com/ultralytics/yolov5/blob/master/data/hyp.scratch.yaml

**Comment by XIEdeda** [comment]
我可能描述错了，我的意思是我debug代码的时候，怎么从训练集上怎么debug进入到数据增强那个代码中? 
![image](https://user-images.githubusercontent.com/68369130/99232539-ff30ea80-282c-11eb-9b51-757443161725.png)

**Comment by glenn-jocher** [comment]
https://github.com/ultralytics/yolov5/blob/b7007d03b4264b3bb805211a568d5e30cbb605dc/utils/datasets.py#L521-L523

**Comment by XIEdeda** [comment]
thank you
