### ISSUE TITLE
Which difference between yolov5l and yolov5-panet?

### ISSUE THREAD

**Issue by stanislavkuskov** [ultralytics/yolov5#1410]
## ❔Question
Which difference between yolov5l and yolov5-panet?

## Additional context

 .cfg files look the same except reversing anchor order. Is Panet included in the yolov5l model?

**Comment by stanislavkuskov** [comment]
The answer is here:
https://github.com/ultralytics/yolov5/commit/364fcfd7dba53f46edd4f04c037a039c0a287972#commitcomment-40145862
PANet backbone included in current models. Models in "hub" directory are old versions

**Comment by glenn-jocher** [comment]
@stanislavkuskov yes that is correct. Current YOLOv5 models are compound-scaled variants of PANet.yaml. I've corrected the anchor order issue you noted in this issue in PR #1410.

**Comment by glenn-jocher** [comment]
Thanks for spotting this!
