### ISSUE TITLE
DDP

### ISSUE THREAD

**Issue by carlsummer** [ultralytics/yolov5#1417]
train.py
has bug
`            # Broadcast if DDP
            if rank != -1:
                indices = (torch.tensor(dataset.indices) if rank == 0 else torch.zeros(dataset.n)).int()
                dist.broadcast(indices, 0)
                if rank != 0:
                    dataset.indices = indices.cpu().numpy()`

maybe
`            if rank != -1:
                #indices = (torch.tensor(dataset.indices) if rank == 0 else torch.zeros(dataset.n)).int()
                indices = (torch.tensor(dataset.indices, device=device) if rank == 0 else torch.zeros(dataset.n,
                                                                                                      device=device)).int()
                dist.broadcast(indices, 0)
                if rank != 0:
                    dataset.indices = indices.cpu().numpy()`

**Comment by glenn-jocher** [comment]
@carlsummer can you raise a bug report please if you believe there is a bug, and also a PR if you believe you have a solution? Thank you!

**Comment by glenn-jocher** [comment]
@carlsummer also for the bug report please ensure you submit **code to reproduce** your observed issue.

**Comment by NanoCode012** [comment]
@carlsummer , maybe old code or your changes to code? I just recloned and tested on coco128, and it works fine.

**Comment by carlsummer** [comment]
@NanoCode012  new code
python -m torch.distributed.launch --nproc_per_node 2 --master_addr 127.0.0.1 --master_port 29501 train.py --cache-images --image-weights --device 0,1 --multi-scale --sync-bn --epochs 300 --batch-size 16

so
dist.broadcast(indices, 0) is not cuda
