### ISSUE TITLE
Is this repo going to support Gaussian layer?

### ISSUE THREAD

**Issue by edwardnguyen1705** [ultralytics/yolov5#142]
Hi @glenn-jocher ,
Thank you for sharing excellent work. As stated in this paper [https://arxiv.org/abs/1904.04620](url), gaussian feature can help to reduce false positives and increase the mAP, do you have any plan to add this feature?

**Comment by glenn-jocher** [comment]
@edwardnguyen1705 no there are no plans for this. If you'd like to submit this feature as a PR that would be great though!

**Comment by lucky-xu-1994** [comment]
> 

Hi, @edwardnguyen1705 :
     have you tried Gaussain yolo to yolov5? is there any improvements on mAP ? looking forward to your reply! thanks!
