### ISSUE TITLE
how to reserve "person" class?

### ISSUE THREAD

**Issue by StephenZhao1** [ultralytics/yolov5#1422]
## ❔Question
As we all konw,the pretrained model like yolov5s.pt can detect many different objects like person,cat,dog and all of that.If I want to train my own new datasets and reserve "person" class from pretrained models,how can I do that?

## Additional context
One idea is to download all coco datasets and mix my dataset.I want to train my dataset without downloading coco datasets.Anybody meet some question?What file I need to change?

**Comment by itruonghai** [comment]
in detect.py, you can predict only person with --class class_id

**Comment by StephenZhao1** [comment]
Well,thanks for your answer.Let me explain my question clearly.First of all,I have trained my own datasets according to your tutorial successfully.Now I prepare my own datasets and want to detect class A,class B and class C.But I want to reserve "person" class after training my own data.When running detect.py the objects I want to recognize is class A, class B, class C, person.

**Comment by oukohou** [comment]
interesting question. Waiting for someone to answer...perhaps @ultralytics ?
Normally perhaps one will use the pretrained model to predict `person`'s bbox and use predicted bbox together with other labeled annotations to train a new model.

**Comment by glenn-jocher** [comment]
@oukohou @StephenZhao1 its very simple. All classes you want to predict in the future must be present in your training data.

**Comment by oukohou** [comment]
@glenn-jocher yeah,supposed so. Thanks for your reply.
