### ISSUE TITLE
Getting unexpected mAP results when using best weights with test.py

### ISSUE THREAD

**Issue by gizemtanriver** [ultralytics/yolov5#1427]
I am training yolox on my custom dataset with the current version of the repo. 

```
python yolov5/train.py --weights yolov5/weights/yolov5x.pt  --data datasets/lesion/lesion_data.yaml --cache \
   --cfg my_models/lesion_yolov5x_defaultanchor.yaml --single --hyp hyp/hyp_evolved_yolov5x_gen100.yaml \
   --img 512 --batch 8 --epochs 80 --name lesion_yolov5x_defaultanchor

```

During training, the results of the best epoch are:
```
 Epoch   gpu_mem       box       obj       cls     total   targets  img_size
     23/79     5.86G   0.04022   0.02975         0   0.06997         6       512: 100% 67/67 [00:30<00:00,  2.17it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100% 8/8 [00:00<00:00,  9.16it/s]
                 all          59          60       0.454       0.867       0.734       0.355
```

But when I try to test the best.pt on my val set with test.py, it gives worse results in all metrics except precision. The fitness is defined as the weighted average of the metrics, weights being [0.0, 0.0, 0.1, 0.9] respectively. So I don't understand why best.pt is not keeping my best weights from training.

```
python yolov5/test.py \
--weights runs/train/lesion_yolov5x_defaultanchor/bin/bash/weights/best.pt \
--data datasets/lesion/lesion_data.yaml --task 'val' --verbose --img-size 512 --single \
--name val_results --project runs/train/lesion_yolov5x_defaultanchor
```

```
Namespace(augment=False, batch_size=32, conf_thres=0.001, data='datasets/lesion/lesion_data.yaml', device='', exist_ok=False, img_size=512, iou_thres=0.65, name='val_results', project='runs/train/lesion_yolov5x_defaultanchor, save_conf=False, save_json=False, save_txt=False, single_cls=True, task='val', verbose=True, weights=['runs/train/lesion_yolov5x_defaultanchor/bin/bash/weights/best.pt'])
Fusing layers... 
                 all          59          60       0.505       0.767        0.63       0.342
Speed: 102.1/1.4/103.5 ms inference/NMS/total per 512x512 image at batch-size 32
Results saved to runs/train/lesion_yolov5x_defaultanchor/val_results6
Using torch 1.7.0+cu101 CUDA:0 (Tesla K80, 11441MB)
```

I am using the default yaml for yolox, just changed the number of classes to 1 for my dataset. I didn't change anything else in the code. I am working on Colab.

**Comment by yinyuhangi** [comment]
I met the same problem. Ask the author for an answer.

**Comment by glenn-jocher** [comment]
@gizemtanriver @yinyuhangi small differences i.e. 0-1% differences are normal due to variations in rectangular batch size and padding when running test.py independently. 

Anything else is likely due to human error, passing different img-size, model, data etc. best.pt is saved on every new maximum fitness epoch, with fitness defined as a weighted combination of metrics in utils/metrics:
https://github.com/ultralytics/yolov5/blob/bd29a1c94672d6e5c5e5735549ad2f88ab787012/utils/metrics.py#L9-L13

Lastly, be advised that --notest or --nosave with prevent best.pt from properly saving. If either of these two arguments are used, best.pt and last.pt will likely be identical.

**Comment by glenn-jocher** [comment]
@gizemtanriver @yinyuhangi I have some new info on this issue. I received similar mAP drop myself when training a yolov3-tiny for an update to ultraltics/yolov3, and I realized that the default iou_thres passed to test() when training is iou_thres=0.6, whereas when run directly python test.py the argparser default is 0.65.

Higher iou_thresh can benefit larger models that are trained sufficiently, like YOLOv5m/l/x. Smaller models like YOLOv3-tiny and YOLOv5s do not reach the point of overtraining as quickly, and can not take advantage of higher iou_thresh to allow more overlap from more accurate boxes, therefore their optimal iou_thresh setting is somewhat lower, perhaps 0.5-0.6. This is likely the case for many smaller models trained on custom datasets.

**Comment by glenn-jocher** [comment]
You can update this parameter here:
https://github.com/ultralytics/yolov5/blob/d81bc47823ffedd3f16448e1ccd57e32e1a8dd4d/test.py#L282

To match this one used during training:
https://github.com/ultralytics/yolov5/blob/d81bc47823ffedd3f16448e1ccd57e32e1a8dd4d/test.py#L27

**Comment by yinyuhangi** [comment]
OK, thanks. I will have a try.

**Comment by glenn-jocher** [comment]
@gizemtanriver @yinyuhangi PR #1465 should fix this. Please `git pull` and try again.
