### ISSUE TITLE
Conversion to tflite

### ISSUE THREAD

**Issue by maheeeetaaa** [ultralytics/yolov5#1429]
Hi, I have been trying to convert YOLOV5 to tflite, and for some reason the activation functions : LeakyRelu and Hardswish remain as they are in the tflite model. I tried everything and I wasn't able to solve it. Any ideas?

**Comment by rickymedrano** [comment]
@maheeetaaa Hi, were you ever able to convert to tflite to use on Coral TPU on Raspberry Pi?
