### ISSUE TITLE
Hi, Scaled-YOLOv4 has been publisehd(https://arxiv.org/abs/2011.08036), I am looking forward to your YOLOv5 paper. 

### ISSUE THREAD

**Issue by AIpakchoi** [ultralytics/yolov5#1433]

**Comment by cszer** [comment]
Look to the table in paper at page 7 ( table 11) , it is no fair comparsion because input size is large that othe networks , and no info about what pp-yolo or yolo4 can achive at this image size

**Comment by cszer** [comment]
I think it is very strange for me when authors adds mods or scaling , but don show results of baseline models
