### ISSUE TITLE
More detailed classification

### ISSUE THREAD

**Issue by carlsummer** [ultralytics/yolov5#1438]
## ❔Question
![image](https://user-images.githubusercontent.com/16281965/99516897-aea2c400-29c9-11eb-8511-68e14439b3b8.png)

![image](https://user-images.githubusercontent.com/16281965/99516982-cb3efc00-29c9-11eb-9041-75572b864a5b.png)
![image](https://user-images.githubusercontent.com/16281965/99517211-10632e00-29ca-11eb-8bae-ef76c9a6cc1c.png)

## Additional context
I have two kinds of defects, a long defect and a short defect. When I marked two categories, yolov5x could not detect long defects after training. When I mark both types of defects as short defects. yolov5x can't learn either, it can only detect short defects

Can you give me a good suggestion

**Comment by carlsummer** [comment]
![image](https://user-images.githubusercontent.com/16281965/99517758-b44cd980-29ca-11eb-9349-d6c5360d6c32.png)

**Comment by glenn-jocher** [comment]
If a person can't reliably complete the task, the model won't be able to either. 

For high aspect ratio objects in particular you may want to increase the AR limits in the dataloader. The current AR limit is 20, which means that objects with longer sides > 20 times their shorter side will be rejected as label candidates:
https://github.com/ultralytics/yolov5/blob/bd29a1c94672d6e5c5e5735549ad2f88ab787012/utils/datasets.py#L838-L844

**Comment by carlsummer** [comment]
thanks，I try

**Comment by carlsummer** [comment]
Thank you very much, so solved
`   return (w2 > wh_thr) & (h2 > wh_thr) & (w2 * h2 / (w1 * h1 + 1e-16) > area_thr) & ((ar < ar_thr) | (classes==0))`
