### ISSUE TITLE
Will you add yolov4 support

### ISSUE THREAD

**Issue by intgogo** [ultralytics/yolov5#144]
This repo has very good training skills. And most important of all,this repo can support export-onnx model and onnx is really good for production deployment.

**Comment by glenn-jocher** [comment]
@intgogo yes, a yolov4 yaml file would be a good addition. We are extremely busy, however if you'd like to help create one we would welcome the PR!

**Comment by Lornatang** [comment]
@intgogo @glenn-jocher Try it? Pull requests https://github.com/ultralytics/yolov5/pull/153.

**Comment by glenn-jocher** [comment]
@Lornatang thanks for the PR! I looked it over, it's a good try, but I believe the yolov4 architecture there is not quite correct. The head specifically should be a PANet head.

Implementing it exactly correctly will be a challenge. The best guide is the existing darknet cfg files like this one, that you can visualize with Netron.
https://github.com/ultralytics/yolov3/blob/master/cfg/yolov4.cfg

**Comment by Lornatang** [comment]
@glenn-jocher In the original YOLOv4, its activation function is Mish, and here I am LeakyReLU. I quickly tested a real data set, and the results are very satisfying to me. #6 

It'is YOLOv5l result:
![选区_002](https://user-images.githubusercontent.com/31124350/85237832-55575880-b45c-11ea-9bdc-ca75a1635846.png)

It'is YOLOv4 result:
![选区_003](https://user-images.githubusercontent.com/31124350/85237849-699b5580-b45c-11ea-96e4-637c5d82f6d3.png)

**Comment by arthurfortes** [comment]
> @glenn-jocher In the original YOLOv4, its activation function is Mish, and here I am LeakyReLU. I quickly tested a real data set, and the results are very satisfying to me. #6
> 
> It'is YOLOv5l result:
> ![选区_002](https://user-images.githubusercontent.com/31124350/85237832-55575880-b45c-11ea-9bdc-ca75a1635846.png)
> 
> It'is YOLOv4 result:
> ![选区_003](https://user-images.githubusercontent.com/31124350/85237849-699b5580-b45c-11ea-96e4-637c5d82f6d3.png)

Could you share the yolo v4 weights in .pt?

**Comment by Lornatang** [comment]
@arthurfortes Not yet, I have not obtained permission.emm...
