### ISSUE TITLE
How to use dicom images for training?

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#1440]
## How to use dicom images for training?❔

I'm using lung cancer images which is of the format of  **.dcm** not **.png** or any other image format.
Is there any way to use **.dcm** images?

**Comment by glenn-jocher** [comment]
@asim266 I'm not familiar with that format, but if cv2 can read it you can add it to the dataloader acceptable formats list here:
https://github.com/ultralytics/yolov5/blob/df0e408962f010053bf5ce61e3045dcbadcd09f4/utils/datasets.py#L24-L28

**Comment by ghost** [comment]
@glenn-jocher  **.dcm** is not supported by cv2 we need to convert the image from .dcm to cv2 supported format please check the link.
[https://stackoverflow.com/questions/53707851/using-dicom-images-with-opencv-in-python](url)
or by adding the following code in the dataset.py I guess.

`import cv2
import pydicom as dicom
ds = dicom.dcmread('sample.dcm')
dcm_sample = ds.pixel_array * 128
cv2.imshow('sample image dicom', dcm_sample)
cv2.waitKey()
`

**Comment by glenn-jocher** [comment]
@asim266 since it's not supported your best best is to simply export all your images to jpg offline, and then present the jpg dataset for training.
