### ISSUE TITLE
Converts the parameters to MB？

### ISSUE THREAD

**Issue by ZwNSW** [ultralytics/yolov5#1443]
## ❔Question
@glenn-jocher 
When I run my program, I get the model for the network with 47398900 parameters, but how do I convert the parameters to MB? I think 47398900 should be a floating-point number of 32. So my calculation is (47398900x32) bit and then convert to 180.8MB? Did I make a mistake in my calculation? Looking forward to your reply.

“Model Summary: 335 layers, 4.73989e+07 parameters, 4.73989e+07 gradients, 114.9 GFLOPS”

**Comment by glenn-jocher** [comment]
Yes. You can see the model sizes at a fixed precision in the custom training tutorial:
https://docs.ultralytics.com/yolov5/tutorials/train_custom_data#4-select-a-model

![image](https://user-images.githubusercontent.com/26833433/99656032-b65f7880-2a5c-11eb-9602-541970700226.png)

**Comment by ZwNSW** [comment]
@glenn-jocher Thaks your reply.When I browse this website（https://docs.ultralytics.com/yolov5/tutorials/train_custom_data#4-select-a-model）, how can I modify the yolov5‘s code and add the wandb module to get pictures like yours？
![Uploading image.png…]()
Looking forward to reply!

**Comment by glenn-jocher** [comment]
@ZwNSW wandb is used automatically during training if it is installed with `pip install wandb`. See Weights & Biases tutorial for more info:
https://docs.ultralytics.com/yolov5

**Comment by ZwNSW** [comment]
@glenn-jocher Thanks your reply,I want to make modifications on the basis of your model to be used for mask recognition. So, how can I cite your article or code?

**Comment by ZwNSW** [comment]
@glenn-jocher Thanks your reply,I want to make modifications on the basis of your model to be used for object detection. So, how can I cite your article or code?

**Comment by glenn-jocher** [comment]
@ZwNSW hi thanks for asking! We aim to publish a short paper to arxiv by the end of 2020. In the meantime please see https://doi.org/10.5281/zenodo.3908559 for DOI to cite this repo directory, and where you can also find bibtex and other exportable citation formats.

[![DOI](https://zenodo.org/badge/264818686.svg)](https://zenodo.org/badge/latestdoi/264818686)
