### ISSUE TITLE
No response to multiple machine training

### ISSUE THREAD

**Issue by zlstl1** [ultralytics/yolov5#1445]
## ❔Question
I followed [https://github.com/ultralytics/yolov5/issues/475] this tutorial

Single GPU learning, Multiple GPUs DP Mode, Multiple GPUs DDP Mode all working well.

But, when I try Multiple machine training have some problem

There is no response as shown in the image below.

![image](https://user-images.githubusercontent.com/35329451/99616044-e78d7800-2a5f-11eb-8701-6144e8349365.png)
![image](https://user-images.githubusercontent.com/35329451/99614722-66cd7c80-2a5d-11eb-861f-cb89a7c2a112.png)

Test img is Rank1 Node(192.168.0.102) & Master Node(192.168.0.103)
Each pc has 2 GPU and same directory&dataset ... conditon

## Additional context

> My PC Environment
> 
> Common : Ubuntu18.04.2 LTS / python3.8 / Cuda 11.1 / torch1.7.0+cu110 / torchvision 0.8.1+cu110
> 
> 0(Master Node, 192.168.0.103) : CPU - Ryzen 3960x Threadripper / GPU - RTX 3090 x2 / RAM - 48GB
> CMD : python3 -m torch.distributed.launch --nproc_per_node 2 --nnodes 3 --node_rank 0 --master_addr "192.168.0.103" --master_port 1234 train.py --batch-size 32 --data dataset.yaml --cfg yolov5x.yaml --weights yolov5x.pt
> 
> 1(Rank 1 Node, 192.168.0.102) : CPU - Ryzen 3960x Threadripper / GPU - RTX 3090 x2 / RAM - 48GB
> CMD : python3 -m torch.distributed.launch --nproc_per_node 2 --nnodes 3 --node_rank 1 --master_addr "192.168.0.103" --master_port 1234 train.py --batch-size 32 --data dataset.yaml --cfg yolov5x.yaml --weights yolov5x.pt
> 
> 2(Rank 2 Node, 192.168.0.101) : CPU - Ryzen 3960x Threadripper / GPU - RTX 3090 x2 / RAM - 48GB
> CMD : python3 -m torch.distributed.launch --nproc_per_node 2 --nnodes 3 --node_rank 2 --master_addr "192.168.0.103" --master_port 1234 train.py --batch-size 32 --data dataset.yaml --cfg yolov5x.yaml --weights yolov5x.pt
> 

**I tried below Chekclist**
Have you properly read this post?
=> Yes
Have you tried to reclone the codebase? The code changes daily.
=> Yes
Have you tried to search for your error? Someone may have already encountered it in this repo or in another and have the solution.
=> Yes, but I can't find similar situation
Have you installed all the requirements listed on top (including the correct Python and Pytorch versions)?
=> Yes
Have you tried in other environments listed in the "Environments" section below?
=> Yes
Have you tried with another dataset like coco128 or coco2017? It will make it easier to find the root cause.
=> Yes, I used custom dataset. but coco128 dataset also get same response

**Additional)**
1. I opened and allowed firewall 1234 port for all machine
2. I tried reinstalling everything
3. I tried changing python version to 3.7.x and 3.8.x

```
Anaconda pip list

absl-py                0.10.0
aiohttp                3.6.3
async-timeout          3.0.1
attrs                  20.3.0
blinker                1.4
brotlipy               0.7.0
cachetools             4.1.1
certifi                2020.6.20
cffi                   1.14.3
chardet                3.0.4
click                  7.1.2
configparser           5.0.1
cryptography           3.1.1
cycler                 0.10.0
Cython                 0.29.21
dataclasses            0.6
docker-pycreds         0.4.0
future                 0.18.2
gitdb                  4.0.5
GitPython              3.1.11
google-auth            1.23.0
google-auth-oauthlib   0.4.2
grpcio                 1.31.0
idna                   2.10
importlib-metadata     2.0.0
kiwisolver             1.2.0
Markdown               3.3.2
matplotlib             3.3.2
mkl-fft                1.2.0
mkl-random             1.1.1
mkl-service            2.3.0
multidict              4.7.6
numpy                  1.19.2
oauthlib               3.1.0
olefile                0.46
opencv-python          4.4.0.46
pathtools              0.1.2
Pillow                 8.0.0
pip                    20.2.4
promise                2.3
protobuf               3.13.0
psutil                 5.7.3
pyasn1                 0.4.8
pyasn1-modules         0.2.8
pycparser              2.20
PyJWT                  1.7.1
pyOpenSSL              19.1.0
pyparsing              2.4.7
PySocks                1.7.1
python-dateutil        2.8.1
PyYAML                 5.3.1
requests               2.24.0
requests-oauthlib      1.3.0
rsa                    4.6
scipy                  1.5.2
sentry-sdk             0.19.2
setuptools             50.3.0.post20201006
shortuuid              1.0.1
sip                    4.19.24
six                    1.15.0
smmap                  3.0.4
subprocess32           3.5.4
tensorboard            2.3.0
tensorboard-plugin-wit 1.6.0
torch                  1.7.0+cu110
torchaudio             0.7.0
torchvision            0.8.1+cu110
tornado                6.0.4
tqdm                   4.50.2
typing-extensions      3.7.4.3
urllib3                1.25.11
wandb                  0.10.10
watchdog               0.10.3
Werkzeug               1.0.1
wheel                  0.35.1
yarl                   1.6.2
zipp                   3.4.0
```

**Comment by glenn-jocher** [comment]
@zlstl1 hi, I don't have a good response for you as we don't actually do any multi-node training ourselves, and it not part of our CI tests, so there may be issues latent in the system when used in this context. 

All I can say is good luck, and if you find any bugs or implement any fixes, please be sure to submit a PR so that others may benefit as well. Thank you!

**Comment by NanoCode012** [comment]
Hi @zlstl1 ! I just saw this Issue. When adding that feature, we had to simulate multiple machines by using multiple terminals on a single machine, so it wasn't foolproof.

Could you try to enclose the `master_addr`'s ip in quotes? If not, there could be probably something else wrong as I've just tested it on the latest commit.

**Comment by erb13020** [comment]
@zlstl1

Sorry to necro this issue, but were you able to find a solution?
