### ISSUE TITLE
LoadStream cannot properly closed.

### ISSUE THREAD

**Issue by juliussin** [ultralytics/yolov5#1446]
## ❔Question
I'd like to ask about `LoadStream`. So I stream through RTSP camera and it works. But unfortunately, I can't close it properly. If I press 'Q', then it will give me `terminate called without an active exception` and the cap windows stuck. I've tried to force closed it, but my CUDA memory stuck. I wonder if I can `cap.release()` it, but `LoadStream` doesn't have `self.cap`.

## Additional context
I use command 
`python detect.py --source rtsp://mycam --view-img`

**Comment by glenn-jocher** [comment]
@juliussin Im not sure what the best approach is here. If you find a good solution though please submit a PR to help everyone else as well!
