### ISSUE TITLE
Can't run with GPU, but worked with CPU

### ISSUE THREAD

**Issue by forallsunday** [ultralytics/yolov5#1448]
Windows 10 , RTX 3080, CUDA 11.0, cudnn 8.04, pytorch 1.7.0
When I typyed "python detect.py --source data/images --weights yolov5s.pt --conf 0.25"
It shows:
RuntimeError: Expected object of device type cuda but got device type cpu for argument #1 'self' in call to _thnn_conv2d_forward.

But it was Ok "python detect.py --source data/images --weights yolov5s.pt --conf 0.25 --device CPU"

It seems ocurred in the function "attempt_load".

**Comment by JunnYu** [comment]
#1447 
#### change line 156
https://github.com/ultralytics/yolov5/blob/bd29a1c94672d6e5c5e5735549ad2f88ab787012/utils/torch_utils.py#L153-L160
```python 
flops = profile(deepcopy(model), inputs=(torch.zeros(1, 3, stride, stride).to(next(model.parameters()).device),), verbose=False)[0] / 1E9 * 2
```

**Comment by glenn-jocher** [comment]
@JunnYu ah of course. Thanks for spotting this bug! I will take a look at the PR.
