### ISSUE TITLE
Precision drop - epoch ~50

### ISSUE THREAD

**Issue by sefibk** [ultralytics/yolov5#1450]
## ❔Question
YOUR REPO IS AWESOME - THANKS!!!
When training several Yolo versions using your code, I notice a weird behavior across all metrics.
Around epoch 45 the precision drops together with a change in the increase rate of the mAP and a weird bump in the recall.
I couldn't figure out what this reflects on the performance nor the trigger to it.
Do you have any insights regarding this phenomena?

## Additional context
![image](https://user-images.githubusercontent.com/38955896/99636107-a7bc9580-2a4b-11eb-9738-4fa175977a1b.png)

**Comment by sefibk** [comment]
Added the entire tensorboard screenshot
![image](https://user-images.githubusercontent.com/38955896/99636765-8b6d2880-2a4c-11eb-955c-01a4957c100a.png)

**Comment by sefibk** [comment]
Any ideas?

**Comment by glenn-jocher** [comment]
@sefibk mAP is the only metric you should consider during training.

**Comment by sefibk** [comment]
Thanks @glenn-jocher, 
I am more curious about this phenomenon and why it may occur. 
I believe that if we can overcome it and achieve "standard" training, we may be able to achieve better results.
If you have any insights as to what happens to training at that point I would be happy to know.

**Comment by glenn-jocher** [comment]
@sefibk you'd have to experiment yourself with the hyperparameters to obtain any effects you wanted. Be advised the goal of training, or hyp evolution, is the maximum final fitness, intermediary results play no part.
