### ISSUE TITLE
SCALED yolov4

### ISSUE THREAD

**Issue by businiaoo** [ultralytics/yolov5#1451]
## ❔Question
does anyone compare yolov5 with SCALED yolov4? which is better?

**Comment by ZJU-lishuang** [comment]
I think yolov5 is better.
But we can scale yolov5 according to SCALED yolov4.

**Comment by Kumaava** [comment]
How can we create a scaled yolov5 like in yolo4?

**Comment by zidanexu** [comment]
How can we create a scaled yolov5 like in yolo4?
