### ISSUE TITLE
Having less classes improves performance of model?

### ISSUE THREAD

**Issue by amadeok** [ultralytics/yolov5#1452]
## ❔Question
Having less classes improves performance of model?

## Additional context
Hi,
After testing the same dataset with different classification of the images i've noted that the same dataset but with less classes has better performance (better precission, recall and mAP) than when it has more classes, and it takes less epochs to get a good mAP. I've been using the smallest model. Does this mean it's better to have less classes per model?

**Comment by glenn-jocher** [comment]
@amadeok I would generally assume that a limited set of resources will always accomplish `n` tasks better than `n + x` tasks.
