### ISSUE TITLE
model.eval() missing in detect method?

### ISSUE THREAD

**Issue by maryamag85** [ultralytics/yolov5#1456]
## ❔Question
I checked the detect method and there the inference is not done in the model.eval() mode. Does adding this in the detect method helps the performance of the model?

**Comment by glenn-jocher** [comment]
@maryamag85 detect.py passes all models through the .eval() method automatically within attempt_load()
https://github.com/ultralytics/yolov5/blob/199c9c787427ece5723d5309e1c7c524a99bc59d/detect.py#L32-L33
