### ISSUE TITLE
yolov5s——onnx——caffe ,model transfer problem

### ISSUE THREAD

**Issue by dadaligoudan** [ultralytics/yolov5#1457]
## ❔Question
Hi, I trained a model based on yolov5s.yaml and transfered it to caffe model.The bounding boxes do not match the object, seems it has been scaled.  I also have the same problem with models trained using  yolov4.cfg. After transfering to caffe model, the model i trained using the yolov4.cfg doesn't perform the way it should be. The bounding boxes do not match the object, seems it has been scaled. But the yolov3.cfg performed well. I have checked your official code, i still cann't find the reason.  I want to know what the difference between yolov3.cfg and v4 as well as v5 about the yolo layer? How do you use this parameters in the yolo layer?Could you please help me with this, thanks.

## Additional context
![YOLOv4](https://user-images.githubusercontent.com/33470552/99752073-9c866a00-2b1e-11eb-9029-e021715f6d12.PNG)
![yolov](https://user-images.githubusercontent.com/33470552/99752076-9d1f0080-2b1e-11eb-9aa7-77b96d4f3945.PNG)

![2767_detected](https://user-images.githubusercontent.com/33470552/99752245-ea02d700-2b1e-11eb-9937-bc78341fc295.jpg)

**Comment by hezhenjun123** [comment]
y = x[i].sigmoid()
                y[..., 0:2] = (y[..., 0:2] * 2. - 0.5 + self.grid[i].to(x[i].device)) * self.stride[i]  # xy
                y[..., 2:4] = (y[..., 2:4] * 2) ** 2 * self.anchor_grid[i]  # wh
                z.append(y.view(bs, -1, self.no))
Maybe the output decode style is different from yolov3,I also meet this question,still not be solved now.

**Comment by mengban** [comment]
Have u fix your problem yet？

**Comment by hezhenjun123** [comment]
Plz note the yolov5 output decode is different from yolov3 and v4，change it and then you could get the correct answer.

**Comment by TW0521** [comment]
how to transfer the yolov5s.pt to caffe model?

**Comment by dadaligoudan** [comment]
> Have u fix your problem yet？

Yes, i have fixed this problem and got the right result. The forward function in the Detect class is different from yolov3 and it should be modified as  described in the following picture.  I think the bounding box regression part in yolov5 is quiet dofferent from that in yolov3 and yolov4.
![yolo](https://user-images.githubusercontent.com/33470552/102327108-33303480-3fc0-11eb-9584-89e8e742d8a3.PNG)

**Comment by dadaligoudan** [comment]
> how to transfer the yolov5s.pt to caffe model?
I am not really familiar with  caffe and i do not know how to transfer FOCUS part , so i used a conv layer which stride=2 to replace it. I used export.py to transfer yolov5s.pt to onnx model. After that, I used onnx simplify tool to simplify onnx model. Last, I transferd onnx-simplified model to caffe model.

**Comment by Nioolek** [comment]
> > how to transfer the yolov5s.pt to caffe model?
> > I am not really familiar with  caffe and i do not know how to transfer FOCUS part , so i used a conv layer which stride=2 to replace it. I used export.py to transfer yolov5s.pt to onnx model. After that, I used onnx simplify tool to simplify onnx model. Last, I transferd onnx-simplified model to caffe model.

请问你在从onnx-simplified转到caffe时候用的是什么代码？还有export.py里，onnx的opset_version=11吗？

**Comment by Nioolek** [comment]
Can caffe support the Hardswish layer?

**Comment by bot66** [comment]
大佬能说一下怎么转caffe的吗？有没有博客之类的：）

**Comment by Hwijune** [comment]
@dadaligoudan How did you convert it? 
torch -> onnx -> caffe

I want to use yolo5 or csp-p7 with leaky relu model in the caffe

**Comment by ShihuaiXu** [comment]
大佬能说一下怎么转caffe的吗？有没有博客之类的：）
