### ISSUE TITLE
Jetson TX2 matplotlib version.

### ISSUE THREAD

**Issue by berkantay** [ultralytics/yolov5#1458]
## ❔Question
Hello I am trying to deploy yolov5 on jetson tx2 but I cannot upgrade matplotlib version further than 2.1.1? Have you got any suggestions

**Comment by priteshgohil** [comment]
Hi @berkantay ,
How did you deploy in Jetson tx2? can you provide some references?

**Comment by berkantay** [comment]
Hello    @priteshgohil
Most of the packages written in requirements.txt has not prebuilt version for Nvidia Jetson TX2. You should built all those corresponding libraries according to you architecture which is arm64. 

Download source code for onnx```i.e``` with corresponding version.
run ```python3.6 setup.py install``` in the source code of the module. and so on.

**Comment by priteshgohil** [comment]
Thanks @berkantay . I will give it a shot.
