### ISSUE TITLE
the result of your work on the plot

### ISSUE THREAD

**Issue by lunasdejavu** [ultralytics/yolov5#1459]
## ❔Question

I'd like to know  the image size of each point in this [plot](https://user-images.githubusercontent.com/26833433/90187293-6773ba00-dd6e-11ea-8f90-cd94afc0427f.png)
since I am working on yolov5s and the image size is 512, the mAP only can reach 28.4 .... I feel like something is wrong since I am training a dataset base on coco and other dataset like crowdhuman, BDD100K_Motor, MIO-TCD, CARPK...etc.

**Comment by glenn-jocher** [comment]
I wrote a script into test.py that automatically creates this plot. You can see the range of image sizes there. You can reproduce this plot yourself using `python test.py --task study`

https://github.com/ultralytics/yolov5/blob/394131c2aa66637177890a41654f75ceae61a0c8/test.py#L314-L325

![image](https://user-images.githubusercontent.com/26833433/99790421-5e8c4480-2b24-11eb-8075-882036dfee9e.png)
