### ISSUE TITLE
Multi GPU (GTX 1060 x2 on one processor) stuck on training.py

### ISSUE THREAD

**Issue by Daornit** [ultralytics/yolov5#1471]
## ❔Question

HI guys. I'm making a plate license detector on yolov5 and when i runing train.py on one GPU it works as expected. in my opinion if i have 2 gpu my training process speed up and i can have more batch_size ?. i followed this guide #475 .
when i use 2 GPU it stuck on following attached image.
![save](https://user-images.githubusercontent.com/34941714/99896560-9f26c200-2ccc-11eb-87a4-e1af3da622a2.png)
I waited around 2h. it still stuck on that point.

How do i diagnos it?
Anyone have any idea on this problem?

## Additional context
Ubuntu 20.04 LTS
Pytorch 1.7.0
Python 3.8.5
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```

**Comment by glenn-jocher** [comment]
@Daornit multi-GPU should only be done with identical GPUs.

**Comment by Daornit** [comment]
why is that in my opinion pytorch making a decisions to use gpu or distribute gpu works. When i searched about SLI on the pytorch people would say that it is not necessary. 

https://discuss.pytorch.org/t/multiple-but-different-gpus/63006

**Comment by glenn-jocher** [comment]
@Daornit necessary and best-practices can definitely differ. It is not best practices to attempt multi-GPU training with different GPUs.
