### ISSUE TITLE
Second stage classifier fails on apply_classifier

### ISSUE THREAD

**Issue by codingforpleasure** [ultralytics/yolov5#1472]
I'm trying to concatenate two models.
The first one is coco with yolov5s.pt for filtering only dogs class.
The second is a classifier which was built with yolov5 for classifying the dog's breed, 
therefore I have modified the code to:

```   
# Second-stage classifier
if classify:
   my_weights = '/home/chris/yolov5/my_dogs_classifier.pt'
   modelc = attempt_load(my_weights, map_location=device) # my dog classifier
   namesc = modelc.module.modelc if hasattr(modelc, 'module') else modelc.names
```

I have noticed all padding and reshaping operations to classifier inputs are handled in the apply_classifier() function,
But for some reason the apply_classifier() crashes:
```
# Apply Classifier
if classify:
     pred = apply_classifier(pred, modelc, img, im0s)
```
It fails on the following line:
```
pred_cls2 = model(torch.Tensor(ims).to(d.device)).argmax(1) 
```
Can somebody please explain,  what should be the proper way for applying my custom classifier?

**Comment by glenn-jocher** [comment]
@codingforpleasure second stage classifiers are a bit of an advanced topic. The current implementation is essentially a reference starting point you can use to implement this on your own. Note you must also separately train yourself a second stage classifier that aligns with your detection model's classes.

**Comment by kaminocode** [comment]
@glenn-jocher Can you elaborate on how to use the model's localisation as it is and a separate classifier to classify the bounding boxes.

**Comment by glenn-jocher** [comment]
> @codingforpleasure second stage classifiers are a bit of an advanced topic. The current implementation is essentially a reference starting point you can use to implement this on your own. Note you must also separately train yourself a second stage classifier that aligns with your detection model's classes.

@rahulbaburaj sorry buddy, nothing to add beyond what I already said here above. It's up to you to use it essentially if you want to, there's no tutorial or anything really, it's just there to open the door to experimenting for those interested. It's also bring-your-own-classifier.
