### ISSUE TITLE
Anyone test it  in M1?

### ISSUE THREAD

**Issue by mathpopo** [ultralytics/yolov5#1475]

**Comment by glenn-jocher** [comment]
+1 for this thread. I'm excited to see what the Apple silicon can do with PyTorch, as the A13/A14 are amazingly fast with YOLOv5 on iOS devices.

I think we may need to wait a few weeks or more likely months though before PyTorch has drivers that can interface with the neural engine, but in the immediate term CPU ops should see a very respectable speed boost. 

The writing has been on the wall for a long time with Intel, they've been sitting in place and trailing in fabrication nodes for too long, and this is what they deserve at this point. They failed to impact the mobile market, and now they are losing the laptop and desktop market. It's a good warning to businesses that get too comfortable.

**Comment by mathpopo** [comment]
@glenn-jocher  i just Interested with the M1 NPU,ARM CPU not the key

**Comment by glenn-jocher** [comment]
@mathpopo yes, neural engine inference and training would be amazing. It's not clear to me how far off this is though, and how integrated any implementation may be, i.e. the XLA support pytorch has is a bit difficult to reach compared to their CUDA support. It's possible official M1 Neural Engine support may be many months off, though you should benefit immediately from the CPU speedup.

It seems TF has some form of MacOS acceleration, though it's unclear if the M1 neural engine or the M1 CPU/GPU are responsible for improvements there.
https://blog.tensorflow.org/2020/11/accelerating-tensorflow-performance-on-mac.html

**Comment by thecaffeinedev** [comment]
Hi, @glenn-jocher I was able to test and run Yolov5 inference natively today on M1 Macbook Pro. CPU only.

**Comment by glenn-jocher** [comment]
@TheCaffeineDev yes we run often on M1 Macbooks. PyTorch CPU inference works fine. Detect.py inference speeds are a little slower than Intel:

YOLOv5 🚀 v5.0-490-g89a6e9f torch 1.9.1 CPU

- 2020 iMac 3.8 GHz 8-Core Intel Core i7: 175 ms
- 2020 M1 Macbook Air: 380 ms

**Comment by darkBuddha** [comment]
@TheCaffeineDev @glenn-jocher how did you do it? thanks

**Comment by glenn-jocher** [comment]
@darkBuddha you just run detect.py normally.

**Comment by darkBuddha** [comment]
I get 
`AttributeError: module 'torchvision' has no attribute 'ops'`
with Python 3.9 from homebrew....

**Comment by zhiqwang** [comment]
@darkBuddha It will be helpful if you could add your Pytorch and torchvision version you're using. And seems that the PyTorch team only publish the Pytorch 1.9 and torchvision 0.10 to PyPI until about two weeks ago (I didn't check it recently).

**Comment by darkBuddha** [comment]
I have M1 Mac and use P3.9 installed via homebrew. All requirements are installed. When i check with `python3 -c "import torch; print(torch.__version__)"`, it shows 1.10.0. 

But when i check `python3 -c "import torchvision; print(torchvision.__version__)"`, it shows 0.2.2, although i have torchvision 0.10.0 installed.

Thanks for any help!

**Comment by darkBuddha** [comment]
It was because of Anaconda. Now i have torchvision 0.10.1, and get another error: `RuntimeError: Couldn't load custom C++ ops. This can happen if your PyTorch and torchvision versions are incompatible, or if you had errors while compiling torchvision from source. For further information on the compatible versions, check https://github.com/pytorch/vision#installation for the compatibility matrix. Please check your PyTorch version with torch.__version__ and your torchvision version with torchvision.__version__ and verify if they are compatible, and if not please reinstall torchvision so that it matches your PyTorch install.`

**Comment by thecaffeinedev** [comment]
Hi @darkBuddha For yolov5 infer, I am using miniconda with python3.8. Torchvision version is `0.10.0`

**Comment by zhiqwang** [comment]
Hi @darkBuddha ,

~I guess that you can try to install pytorch 1.9 and torchvision 0.10 instead.~

Or you should install `torchvision` 0.11.1 if you have `torch` 1.10.0 installed.

**Comment by darkBuddha** [comment]
> Hi @darkBuddha ,
> 
> ~I guess that you can try to install pytorch 1.9 and torchvision 0.10 instead.~
> 
> Or you should install `torchvision` 0.11.1 if you have `torch` 1.10.0 installed.

Thanks so much!!!

**Comment by lesleypotters** [comment]
Hi all,
I am working on a MBP M1 in a PyTorch environment with torchvision 0.12 and torch 1.11 (as recommended). I am trying yolov5 out with a wheat detection dataset. When running:
`python train.py --img 1024 --batch 8 --epochs 100 --data wheat.yaml --cfg models/yolov5s.yaml --name wm`
it indeed starts to train for 100 epochs, but the expected time is about an hour per epoch. I find it suspicious that no gpu memory is allocated `gpu_mem 0G`, although I have to say I am a newby to yolov5 and MBP M1.

This is a prtscr:
<img width="797" alt="image" src="https://user-images.githubusercontent.com/51701144/161863283-2c00f1c4-c642-4370-aa83-e0f11bd0bbc9.png">

What could I change to improve? I have tried with `--device cpu`but to no avail. Any other options? Thanks!

Edit:
This is my `python detect.py` output (which, if I am correct, is ok):
<img width="567" alt="image" src="https://user-images.githubusercontent.com/51701144/161863621-65debf4a-37c3-401d-8554-0c7207ab0059.png">

**Comment by glenn-jocher** [comment]
@lesleypotters base M1 is pretty slow, Pro and Max are much faster but still not as fast as a CUDA GPU. Yes your times look right.

gpu_mem displays CUDA memory usage only.

See my Reddit post here: https://www.reddit.com/r/MachineLearning/comments/tbj4lf/comment/i083o5s/?utm_source=share&utm_medium=web2x&context=3

<img width="732" alt="Screenshot 2022-04-06 at 11 01 10" src="https://user-images.githubusercontent.com/26833433/161937969-9c3af4a1-d840-4164-a026-eaf7e60b45df.png">

**Comment by glenn-jocher** [comment]
See my Reddit post here: https://www.reddit.com/r/MachineLearning/comments/tbj4lf/comment/i083o5s/?utm_source=share&utm_medium=web2x&context=3

<img width="732" alt="Screenshot 2022-04-06 at 11 01 10" src="https://user-images.githubusercontent.com/26833433/161937969-9c3af4a1-d840-4164-a026-eaf7e60b45df.png">
