### ISSUE TITLE
optimize train and detection on oblique object

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#1477]
## ❔Question
Hi, i have 100.000 datas trained and the model work well detection the object if the object have right position, but if the object rotate by 15-180 degrees, the result not good. How to optimize that ? thank you

## Additional context
0 - 10 degrees score 0.70-0.82
15 - 180 degrees score 0.20 - 0.45
go with threshold => 0.60
i have trained with multiscale = true
i create the model to detect national identity card

`models/yolov5s.yaml --img 640 --batch-size 16 --multi-scale`

**Comment by glenn-jocher** [comment]
@blinkbink if you want rotational invariance you can increase the 'degrees' hyperparameter up to 180. Then all of our training images will be randomly rotated +/- 180 deg. This is suitable for certain domains like satellite imagery etc.
https://github.com/ultralytics/yolov5/blob/201bafc7cf9545362552ad5b0fc5033d64d7ae77/data/hyp.scratch.yaml#L1-L33

**Comment by ghost** [comment]
Thank you
