### ISSUE TITLE
Any Android APP for YOLOv5 like iDetection for YOLOv5 in IOS?

### ISSUE THREAD

**Issue by yao-zheng-yi** [ultralytics/yolov5#1478]
iDetection's FPS can reach 30, any Android APP use YOLOv5 can reach the same FPS?
Or will you write a APP like iDetection in  Android? @glenn-jocher

**Comment by glenn-jocher** [comment]
@yao-zheng-yi good question. Android is a bit more complicated, but there is progress here in PR  https://github.com/ultralytics/yolov5/pull/1127.

Please review there and contribute anything you can as well!

**Comment by yao-zheng-yi** [comment]
> @yao-zheng-yi good question. Android is a bit more complicated, but there is progress here in PR #1127.
> 
> Please review there and contribute anything you can as well!

Thanks, I will try

**Comment by lujiazho** [comment]
@yao-zheng-yi have you deployed the .tflite model successfully? I got some problem with that by using the method in PR #1127.
