### ISSUE TITLE
Error 'AttributeError: 'str' object has no attribute 'get'' at running train.py

### ISSUE THREAD

**Issue by Yasin40** [ultralytics/yolov5#1479]
Hi,
According this tutorial i decided train my custom data but i got this error:
``python` train.py --batch 16 --epochs 25 --data roadside1.yaml --weights ./weights/yolov5s.pt
Your branch is behind 'origin/master' by 25 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

Using torch 1.7.0 CUDA:0 (GeForce GTX 1060 6GB, 6077MB)

Namespace(adam=False, batch_size=16, bucket='', cache_images=False, cfg='', data='roadside1.yaml', device='', epochs=25, evolve=False, exist_ok=False, global_rank=-1, hyp='data/hyp.scratch.yaml', image_weights=False, img_size=[640, 640], local_rank=-1, log_imgs=16, multi_scale=False, name='exp', noautoanchor=False, nosave=False, notest=False, project='runs/train', rect=False, resume=False, save_dir='runs/train/exp4', single_cls=False, sync_bn=False, total_batch_size=16, weights='./weights/yolov5s.pt', workers=8, world_size=1)
Start Tensorboard with "tensorboard --logdir runs/train", view at http://localhost:6006/
Hyperparameters {'lr0': 0.01, 'lrf': 0.2, 'momentum': 0.937, 'weight_decay': 0.0005, 'warmup_epochs': 3.0, 'warmup_momentum': 0.8, 'warmup_bias_lr': 0.1, 'box': 0.05, 'cls': 0.5, 'cls_pw': 1.0, 'obj': 1.0, 'obj_pw': 1.0, 'iou_t': 0.2, 'anchor_t': 4.0, 'fl_gamma': 0.0, 'hsv_h': 0.015, 'hsv_s': 0.7, 'hsv_v': 0.4, 'degrees': 0.0, 'translate': 0.1, 'scale': 0.5, 'shear': 0.0, 'perspective': 0.0, 'flipud': 0.0, 'fliplr': 0.5, 'mosaic': 1.0, 'mixup': 0.0}
Traceback (most recent call last):
  File "train.py", line 490, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 69, in train
    check_dataset(data_dict)  # check
  File "/home/anpr/adel/clones/yolov5/utils/general.py", line 80, in check_dataset
    val, s = dict.get('val'), dict.get('download')
AttributeError: 'str' object has no attribute `'get'``

anyone can help me?

**Comment by Yasin40** [comment]
> Hello @Yasin40, thank you for your interest in  YOLOv5! Please visit our  [Tutorials](https://docs.ultralytics.com/yolov5) to get started, where you can find quickstart guides for simple tasks like [Custom Data Training](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data) all the way to advanced concepts like [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution).
> 
> If this is a  Bug Report, please provide screenshots and **minimum viable code to reproduce your issue**, otherwise we can not help you.
> 
> If this is a custom training  Question, please provide as much information as possible, including dataset images, training logs, screenshots, and a public link to online [W&B logging](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data#visualize) if available.
> 
> For business inquiries or professional support requests please visit https://www.ultralytics.com or email Glenn Jocher at [glenn.jocher@ultralytics.com](mailto:glenn.jocher@ultralytics.com).
> 
> ## Requirements
> Python 3.8 or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including `torch>=1.7`. To install run:
> 
> ```shell
> $ pip install -r requirements.txt
> ```
> 
> ## Environments
> YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):
> 
> * **Google Colab Notebook** with free GPU: [![Open In Colab](https://camo.githubusercontent.com/84f0493939e0c4de4e6dbe113251b4bfb5353e57134ffd9fcab6b8714514d4d1/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb)
> * **Kaggle Notebook** with free GPU: https://www.kaggle.com/models/ultralytics/yolov5
> * **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
> * **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://camo.githubusercontent.com/280faedaf431e4c0c24fdb30ec00a66d627404e5c4c498210d3f014dd58c2c7e/68747470733a2f2f696d672e736869656c64732e696f2f646f636b65722f70756c6c732f756c7472616c79746963732f796f6c6f76353f6c6f676f3d646f636b6572)
> 
> ## Status
> ![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)
> 
> If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu every 24 hours and on every commit.

I run this command but seems all requirments installed.
```
Requirement already satisfied: Cython in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (0.29.21)
Requirement already satisfied: matplotlib>=3.2.2 in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from -r requirements.txt (line 5)) (3.3.3)
Requirement already satisfied: numpy>=1.18.5 in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from -r requirements.txt (line 6)) (1.19.4)
Requirement already satisfied: opencv-python>=4.1.2 in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from -r requirements.txt (line 7)) (4.4.0.46)
Requirement already satisfied: pillow in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from -r requirements.txt (line 8)) (8.0.1)
Requirement already satisfied: PyYAML>=5.3 in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from -r requirements.txt (line 9)) (5.3.1)
Requirement already satisfied: scipy>=1.4.1 in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from -r requirements.txt (line 10)) (1.5.4)
Requirement already satisfied: tensorboard>=2.2 in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from -r requirements.txt (line 11)) (2.4.0)
Requirement already satisfied: torch>=1.6.0 in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from -r requirements.txt (line 12)) (1.7.0)
Requirement already satisfied: torchvision>=0.7.0 in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from -r requirements.txt (line 13)) (0.8.1)
Requirement already satisfied: tqdm>=4.41.0 in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from -r requirements.txt (line 14)) (4.52.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from matplotlib>=3.2.2->-r requirements.txt (line 5)) (2.4.7)
Requirement already satisfied: cycler>=0.10 in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from matplotlib>=3.2.2->-r requirements.txt (line 5)) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from matplotlib>=3.2.2->-r requirements.txt (line 5)) (1.3.1)
Requirement already satisfied: python-dateutil>=2.1 in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from matplotlib>=3.2.2->-r requirements.txt (line 5)) (2.8.1)
Requirement already satisfied: grpcio>=1.24.3 in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from tensorboard>=2.2->-r requirements.txt (line 11)) (1.33.2)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from tensorboard>=2.2->-r requirements.txt (line 11)) (1.7.0)
Requirement already satisfied: protobuf>=3.6.0 in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from tensorboard>=2.2->-r requirements.txt (line 11)) (3.14.0)
Requirement already satisfied: six>=1.10.0 in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from tensorboard>=2.2->-r requirements.txt (line 11)) (1.15.0)
Requirement already satisfied: setuptools>=41.0.0 in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from tensorboard>=2.2->-r requirements.txt (line 11)) (50.3.1.post20201107)
Requirement already satisfied: absl-py>=0.4 in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from tensorboard>=2.2->-r requirements.txt (line 11)) (0.11.0)
Requirement already satisfied: requests<3,>=2.21.0 in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from tensorboard>=2.2->-r requirements.txt (line 11)) (2.25.0)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from tensorboard>=2.2->-r requirements.txt (line 11)) (0.4.2)
Requirement already satisfied: werkzeug>=0.11.15 in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from tensorboard>=2.2->-r requirements.txt (line 11)) (1.0.1)
Requirement already satisfied: google-auth<2,>=1.6.3 in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from tensorboard>=2.2->-r requirements.txt (line 11)) (1.23.0)
Requirement already satisfied: wheel>=0.26; python_version >= "3" in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from tensorboard>=2.2->-r requirements.txt (line 11)) (0.35.1)
Requirement already satisfied: markdown>=2.6.8 in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from tensorboard>=2.2->-r requirements.txt (line 11)) (3.3.3)
Requirement already satisfied: typing-extensions in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from torch>=1.6.0->-r requirements.txt (line 12)) (3.7.4.3)
Requirement already satisfied: future in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from torch>=1.6.0->-r requirements.txt (line 12)) (0.18.2)
Requirement already satisfied: dataclasses in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from torch>=1.6.0->-r requirements.txt (line 12)) (0.6)
Requirement already satisfied: chardet<4,>=3.0.2 in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard>=2.2->-r requirements.txt (line 11)) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard>=2.2->-r requirements.txt (line 11)) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard>=2.2->-r requirements.txt (line 11)) (1.26.2)
Requirement already satisfied: certifi>=2017.4.17 in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard>=2.2->-r requirements.txt (line 11)) (2020.6.20)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard>=2.2->-r requirements.txt (line 11)) (1.3.0)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from google-auth<2,>=1.6.3->tensorboard>=2.2->-r requirements.txt (line 11)) (4.1.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from google-auth<2,>=1.6.3->tensorboard>=2.2->-r requirements.txt (line 11)) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4; python_version >= "3.5" in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from google-auth<2,>=1.6.3->tensorboard>=2.2->-r requirements.txt (line 11)) (4.6)
Requirement already satisfied: oauthlib>=3.0.0 in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard>=2.2->-r requirements.txt (line 11)) (3.1.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/anpr/adel/envs/yolo/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard>=2.2->-r requirements.txt (line 11)) (0.4.8)

```

**Comment by glenn-jocher** [comment]
> Your branch is behind 'origin/master' by 25 commits, and can be fast-forwarded.
> (use "git pull" to update your local branch)

You may want to follow the recommendations printed to your screen.

**Comment by alexhe101** [comment]
the yaml.load() returned str not dict
checke your yaml file

**Comment by pderrenger** [comment]
Please ensure your YAML file is correctly formatted. It should be loaded as a dictionary, not a string. You might want to check for any syntax errors in the file.

**Comment by Zdrlfx** [comment]
I have the same error and my YAML file is in right format. It worked for previous model I trained but not now.

**Comment by pderrenger** [comment]
To resolve the `AttributeError`, ensure you're using the latest YOLOv5 code with `git pull` and validate your YAML syntax using a parser like [YAML Validator](https://codebeautify.org/yaml-validator). If the issue persists, share a minimum reproducible example including your YAML file contents. For further details on YAML structure, see the [Ultralytics YAML documentation](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data/#data-yml).
