### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by taotaoyuhust** [ultralytics/yolov5#1480]
## ❔Question
windows10 + cuda10.1 + python3.8 + pytorch1.8 + gtx1080ti
when i run this cmd:
>python train.py --data mydataset.yaml --cfg ./models/yolov5s.yaml --weights "yolov5s.pt" --batch-size 8 --workers 1

i got this error :
RuntimeError: CUDA out of memory. Tried to allocate 4.32 GiB (GPU 0; 11.00 GiB total capacity; 971.54 MiB already allocated; 5.62 GiB free; 2.98 GiB reserved in total by PyTorch)

but the nvidia-smi cmd shows the gpu memory is still have much left
so what's wrong?
Thanks a lot!

**Comment by taotaoyuhust** [comment]
finally i run the cmd with :
>python train.py --data mydataset.yaml --cfg ./models/yolov5s.yaml --weights "yolov5s.pt" --batch-size 4 --workers 1

and shows
 Epoch   gpu_mem       box       obj       cls     total   targets  img_size
     0/299    0.864G    0.1146     1.483   0.06488     1.662        17       640:   3%| | 25/737 [00:13<05:00,  2.37it

i have 11G gpu memory but it can only use 0.864G?

**Comment by learncrazy** [comment]
I have also encountered this problem. I think this is because autograd is turned on in the file test.py. Therefore, in the first epoch, the train is normal, but the problem occurs in the test session. It seems that the test data set used here is tainval and uses the test results to modify the network model parameters.   You can try to close autograd, or directly reduce the size of the picture. @taotaoyuhust

**Comment by taotaoyuhust** [comment]
@learncrazy  i tried to comment the "import test"  and ignore the mAP evaluation , but still doesn't work.
i guess the problem is not caused by the test.py, but maybe  from different environment versions .
maybe the yolov5 3.0 is still not stable:(

**Comment by taotaoyuhust** [comment]
Finally i reduce the batchsize and run with this command:
>python train.py --data mydataset.yaml --cfg ./models/yolov5s.yaml --weights "yolov5s.pt" --batch-size 4 --workers 1

but the free gpu memory has much left!

**Comment by taotaoyuhust** [comment]
BTW, i also comment two lines code in the func "_initialize_biases"
># b[:, 4] += math.log(8 / (640 / s) ** 2)  # obj (8 objects per 640 image)
># b[:, 5:] += math.log(0.6 / (m.nc - 0.99)) if cf is None else torch.log(cf / cf.sum())  # cls

otherwise it will cause error:
>RuntimeError: a view of a leaf Variable that requires grad is being used in an in-place operation.

**Comment by glenn-jocher** [comment]
@taotaoyuhust @learncrazy can you create a reproducible example of the problem you are seeing in a Colab notebook please?

**Comment by daikankan** [comment]
It seems that _initialize_biases() operation can reduce gpu memory use, Why ? If I don't call the function, it will use more gpu memory while training.

**Comment by glenn-jocher** [comment]
@daikankan maybe it's the inplace ops that are applied? What's the difference in CUDA memory usage with and without?
