### ISSUE TITLE
Found XX duplicate training images

### ISSUE THREAD

**Issue by nanometer34688** [ultralytics/yolov5#1481]
## Additional context
Just a quick questions about what it means by 'duplicate' images. What does this mean?

As far as I am aware, every image I have has a  unique name. How does it workout what it considers is 'duplicate'?

Example:

`(1038 found, 0 missing, 400 empty, 59 duplicate, for 1438 images)`

**Comment by glenn-jocher** [comment]
@nanometer34688 this is a label scan. You have 59 text files that contain duplicate labels, i.e. two or more rows are identical in your label.txt file. 

You have 59 such files in your dataset, so you may want to take a step back and review your labels before training.

**Comment by glenn-jocher** [comment]
You can print out a list of these problem label files by uncommenting this line:
https://github.com/ultralytics/yolov5/blob/201bafc7cf9545362552ad5b0fc5033d64d7ae77/utils/datasets.py#L420-L421

**Comment by nanometer34688** [comment]
Thank you @glenn-jocher 

I will look into that
