### ISSUE TITLE
[ERROR] torch.nn.modules.module.ModuleAttributeError: 'Detect' object has no attribute 'm'

### ISSUE THREAD

**Issue by nmc-costa** [ultralytics/yolov5#1483]
## ❔Question
From tutorial.ipynb when running `!python detect.py --weights yolov5s.pt --img 640 --conf 0.25 --source data/images/ --device 0 --update`, this error is raised " ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'Detect' object has no attribute 'm'".
Can you tell me a solution?

## Additional context
Namespace(weights=['yolov5s.pt'], source='data/images/', img_size=640, conf_thres=0.25, iou_thres=0.45, device='0', view_img=False, save_txt=False, save_conf=False, classes=None, agnostic_nms=False, augment=False, update=True, project='runs/detect', name='exp', exist_ok=False)
Using torch 1.8.0.dev20201122+cu101 CUDA:0 (GeForce GTX 1070, 8192MB)

/home/nmc_costa/miniconda3/envs/yolov5_v31/lib/python3.9/site-packages/torch/serialization.py:656: SourceChangeWarning: source code of class 'models.yolo.Model' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/nmc_costa/miniconda3/envs/yolov5_v31/lib/python3.9/site-packages/torch/serialization.py:656: SourceChangeWarning: source code of class 'torch.nn.modules.container.Sequential' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/nmc_costa/miniconda3/envs/yolov5_v31/lib/python3.9/site-packages/torch/serialization.py:656: SourceChangeWarning: source code of class 'models.common.Conv' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/nmc_costa/miniconda3/envs/yolov5_v31/lib/python3.9/site-packages/torch/serialization.py:656: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/nmc_costa/miniconda3/envs/yolov5_v31/lib/python3.9/site-packages/torch/serialization.py:656: SourceChangeWarning: source code of class 'torch.nn.modules.batchnorm.BatchNorm2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/nmc_costa/miniconda3/envs/yolov5_v31/lib/python3.9/site-packages/torch/serialization.py:656: SourceChangeWarning: source code of class 'torch.nn.modules.activation.LeakyReLU' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/nmc_costa/miniconda3/envs/yolov5_v31/lib/python3.9/site-packages/torch/serialization.py:656: SourceChangeWarning: source code of class 'torch.nn.modules.container.ModuleList' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/nmc_costa/miniconda3/envs/yolov5_v31/lib/python3.9/site-packages/torch/serialization.py:656: SourceChangeWarning: source code of class 'torch.nn.modules.pooling.MaxPool2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/nmc_costa/miniconda3/envs/yolov5_v31/lib/python3.9/site-packages/torch/serialization.py:656: SourceChangeWarning: source code of class 'torch.nn.modules.upsampling.Upsample' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/nmc_costa/miniconda3/envs/yolov5_v31/lib/python3.9/site-packages/torch/serialization.py:656: SourceChangeWarning: source code of class 'models.yolo.Detect' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Fusing layers... 
Model Summary: 231 layers, 7459581 parameters, 842749 gradients
Traceback (most recent call last):
  File "/mnt/c/Users/nmc_costa/google_drive/projects/bosch_P19/research/python_ws/violent_action/yolo/yolov5/detect.py", line 169, in <module>
    detect()
  File "/mnt/c/Users/nmc_costa/google_drive/projects/bosch_P19/research/python_ws/violent_action/yolo/yolov5/detect.py", line 61, in detect
    _ = model(img.half() if half else img) if device.type != 'cpu' else None  # run once
  File "/home/nmc_costa/miniconda3/envs/yolov5_v31/lib/python3.9/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/c/Users/nmc_costa/google_drive/projects/bosch_P19/research/python_ws/violent_action/yolo/yolov5/models/yolo.py", line 121, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/mnt/c/Users/nmc_costa/google_drive/projects/bosch_P19/research/python_ws/violent_action/yolo/yolov5/models/yolo.py", line 137, in forward_once
    x = m(x)  # run
  File "/home/nmc_costa/miniconda3/envs/yolov5_v31/lib/python3.9/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/c/Users/nmc_costa/google_drive/projects/bosch_P19/research/python_ws/violent_action/yolo/yolov5/models/yolo.py", line 48, in forward
    x[i] = self.m[i](x[i])  # conv
  File "/home/nmc_costa/miniconda3/envs/yolov5_v31/lib/python3.9/site-packages/torch/nn/modules/module.py", line 795, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'Detect' object has no attribute 'm'

**Comment by glenn-jocher** [comment]
@nmc-costa do not use --update

**Comment by glenn-jocher** [comment]
@nmc-costa also your error is not reproducible:

<img width="1276" alt="Screenshot 2020-11-23 at 13 27 45" src="https://user-images.githubusercontent.com/26833433/99962025-bd092b00-2d8f-11eb-8175-73730dccb713.png">

**Comment by nmc-costa** [comment]
Yes. The problem was in the weights that were already downloaded from previous version. 

Basically I needed to redownload the weights.

Reclone repo. See #690

Thank you

**Comment by glenn-jocher** [comment]
Great!
