### ISSUE TITLE
Where can I resize the output images label size

### ISSUE THREAD

**Issue by Zhen-Bo** [ultralytics/yolov5#149]
Its to big that I can't see another part of the image
I edit tl and tf in util.util,but it doesn't work well
![phplpE73q_jpg rf bd81cab9f8ff2674ce2e58278f7d37fa](https://user-images.githubusercontent.com/30999421/85210210-8fe3c700-b370-11ea-9fb8-b5b5997cff95.jpg)

**Comment by glenn-jocher** [comment]
@Zhen-Bo you can modify the plotted detections here:
https://github.com/ultralytics/yolov5/blob/24dd150fbd0614f933c6a5041e005b8a7f712771/detect.py#L101-L104

**Comment by Zhen-Bo** [comment]
Thanks <3
