### ISSUE TITLE
data enhancement

### ISSUE THREAD

**Issue by carlsummer** [ultralytics/yolov5#1490]
## ❔Question
normal
![image](https://user-images.githubusercontent.com/16281965/100043251-f604d680-2e47-11eb-930f-d02ff9add660.png)

defect
![image](https://user-images.githubusercontent.com/16281965/100043350-3c5a3580-2e48-11eb-9184-eb2e33db03dc.png)

After data enhancement
![image](https://user-images.githubusercontent.com/16281965/100043464-79262c80-2e48-11eb-957b-d2248d2c25c2.png)
![image](https://user-images.githubusercontent.com/16281965/100043492-83482b00-2e48-11eb-86da-ce42f26c26cf.png)

## Additional context
After training, it is detected as
![image](https://user-images.githubusercontent.com/16281965/100043776-13867000-2e49-11eb-9e80-7d4158b7b7b3.png)
Lead to a large area of normal inspection for defects

Can you help me do you have a good idea

**Comment by glenn-jocher** [comment]
Use a larger model, use a larger dataset, train longer, use hyperparameter evolution etc.

**Comment by carlsummer** [comment]
![image](https://user-images.githubusercontent.com/16281965/100103122-7276d400-2e9f-11eb-806a-5705b251391b.png)
Yes, you are right, since the 300th time the precision has risen significantly, but is there a better way. What I want is to make specific enhancements to this type of data when the data is enhanced, but I don’t know how to modify it

**Comment by carlsummer** [comment]
Do you find it useful to do a separate data enhancement for this kind of defect?

**Comment by carlsummer** [comment]
```
        # Labels
        x = self.labels[index]
        labels = x.copy()

        # 倒角上的缺角不进行裁剪
        if len(labels[labels[:,0] == 5]) != 0:
            # Padded resize
            img, ratio, pad = letterbox(img, new_shape=(y2b-y1b,x2b-x1b))[0]

        img4[y1a:y2a, x1a:x2a] = img[y1b:y2b, x1b:x2b]  # img4[ymin:ymax, xmin:xmax]
        padw = x1a - x1b
        padh = y1a - y1b


        if x.size > 0:  # Normalized xywh to pixel xyxy format
            if len(labels[labels[:, 0] == 5]) != 0:
                labels[:, 1] = ratio[0] * w * (x[:, 1] - x[:, 3] / 2) + pad[0]  # pad width
                labels[:, 2] = ratio[1] * h * (x[:, 2] - x[:, 4] / 2) + pad[1]  # pad height
                labels[:, 3] = ratio[0] * w * (x[:, 1] + x[:, 3] / 2) + pad[0]
                labels[:, 4] = ratio[1] * h * (x[:, 2] + x[:, 4] / 2) + pad[1]
            else:
                labels[:, 1] = w * (x[:, 1] - x[:, 3] / 2) + padw
                labels[:, 2] = h * (x[:, 2] - x[:, 4] / 2) + padh
                labels[:, 3] = w * (x[:, 1] + x[:, 3] / 2) + padw
                labels[:, 4] = h * (x[:, 2] + x[:, 4] / 2) + padh
```

I tried to modify mosaic but the effect was worse

**Comment by carlsummer** [comment]
Could it only be Use a larger model, use a larger dataset, train longer, use hyperparameter evolution etc.

**Comment by glenn-jocher** [comment]
@carlsummer there are infinite ways to improve your results. Start with the four I mentioned.

**Comment by nanhui69** [comment]
@carlsummer how big is  your data and class category？

**Comment by carlsummer** [comment]
@nanhui69 5分类

**Comment by carlsummer** [comment]
I slove it，
