### ISSUE TITLE
When model.model[-1]. export = False in export.py, coreml export failing. Please check.

### ISSUE THREAD

**Issue by abpanchal95** [ultralytics/yolov5#1491]

**Comment by al03** [comment]
Some here.

`python models/export.py --weights /Users/a/yolov5s.pt --img 640 --batch 1`

Execute failed with output:

`
Converting Frontend ==> MIL Ops:   2%|█▌                                                           | 23/932 [00:00<00:00, 1300.61 ops/s]
CoreML export failure: unexpected number of inputs for node x.2 (_convolution): 13
`

**Comment by NikolaDjapa** [comment]
Having the same error.  Here is the environment that I am using with python 3.8.0. Model that is being used is downloaded automatically by export.py script (yolov5s.pt). 

Package                Versions
---------------------- ---------
absl-py                0.11.0
attr                   0.3.1
attrs                  20.3.0
cachetools             4.1.1
certifi                2020.11.8
chardet                3.0.4
coremltools            4.0
cycler                 0.10.0
Cython                 0.29.21
dataclasses            0.6
future                 0.18.2
google-auth            1.23.0
google-auth-oauthlib   0.4.2
grpcio                 1.33.2
idna                   2.10
kiwisolver             1.3.1
Markdown               3.3.3
matplotlib             3.3.3
mpmath                 1.1.0
numpy                  1.19.4
oauthlib               3.1.0
onnx                   1.8.0
opencv-python          4.4.0.46
packaging              20.4
pandas                 1.1.4
Pillow                 8.0.1
pip                    20.2.4
protobuf               3.14.0
pyasn1                 0.4.8
pyasn1-modules         0.2.8
pyparsing              2.4.7
python-dateutil        2.8.1
pytz                   2020.4
PyYAML                 5.3.1
requests               2.25.0
requests-oauthlib      1.3.0
rsa                    4.6
scikit-learn           0.19.2
scipy                  1.5.4
seaborn                0.11.0
setuptools             50.3.2
six                    1.15.0
sympy                  1.6.2
tensorboard            2.4.0
tensorboard-plugin-wit 1.7.0
torch                  1.7.0
torchvision            0.8.1
tqdm                   4.54.0
typing-extensions      3.7.4.3
urllib3                1.26.2
Werkzeug               1.0.1
wheel                  0.35.1

**Comment by maidmehic** [comment]
Any update?
