### ISSUE TITLE
About the reference

### ISSUE THREAD

**Issue by yinyuhangi** [ultralytics/yolov5#1495]
## ❔Question
Hello, if I want to quote your work in paper, how should I fill in the relevant information? Looking forward to your reply.

**Comment by glenn-jocher** [comment]
@yinyuhangi hi thanks for asking! We aim to publish a short paper to arxiv by the end of the year. In the meantime please see https://doi.org/10.5281/zenodo.3908559 for DOI to cite this repo directory, and where you can also find bibtex and other exportable citation formats.

[![DOI](https://zenodo.org/badge/264818686.svg)](https://zenodo.org/badge/latestdoi/264818686)
