### ISSUE TITLE
calculate fps on local system

### ISSUE THREAD

**Issue by MChavoshi96** [ultralytics/yolov5#1498]
## ❔Question
I have been using the code to do detection from webcam. How can I know what is the speed of detection (fps) in my local system?

**Comment by glenn-jocher** [comment]
@MChavoshi96 detect.py displays inference speed directly to screen. Suggest you take a look at the notebook:

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>

**Comment by Diom852** [comment]
last_time = time.time()
print("fps: {}".format(1 / (time.time() - last_time)))

Python<---
