### ISSUE TITLE
Yolov5 to Darknet

### ISSUE THREAD

**Issue by j3vr0n** [ultralytics/yolov5#1499]
Has anyone managed to convert the Yolov5 PyTorch model to darknet .weights? I have an OpenCV project in Unity that only allows models to be ran in .weights or caffe formats. I’ve managed to get v4 running, but would love to use optimization found in v5.

**Comment by j3vr0n** [comment]
Anyone?

**Comment by syedali1621** [comment]
This is my question too because yolov5 is only available on pytorch and opencvforunity only run .weight files it can't run pytorch weight is there any way to run yoolov5 in unity or convert pytorch weight into darknet format?

**Comment by Nioolek** [comment]
I want to convert yolov5 to darknet or caffe too. Do you have some ways?

**Comment by Nioolek** [comment]
Can caffe support the Hardswish layer?

**Comment by flgau** [comment]
I've never done it myself, so maybe it won't work, but I think you can convert ONNX weights, to Caffe weights using this : https://github.com/xxradon/ONNXToCaffe. You can easily convert your .pth to .onnx by following pytorch tutorial : https://michhar.github.io/convert-pytorch-onnx/. So maybe by doing .pth to .onnx and after .onnx to .caffe it will work but I've never tried it

**Comment by Code-keys** [comment]
look into my git

**Comment by glenn-jocher** [comment]
@Code-keys thanks for reaching out! Converting YOLOv5 PyTorch models to darknet format is indeed possible with the provided convert.py script in the YOLOv5 repository. You can refer to the documentation at https://docs.ultralytics.com/yolov5/ for detailed instructions on how to carry out this conversion. Good luck with your project!
