### ISSUE TITLE
How to use webcam for detection in Colab

### ISSUE THREAD

**Issue by GUOOOZI** [ultralytics/yolov5#150]
I have try to use the colab for tutorial and I want to use the webcam in colab for real-time detection. 
When I code 
`!python detect.py --source 0  # webcam`
It will say that
 ```
 File "detect.py", line 158, in <module>
    detect()
  File "detect.py", line 42, in detect
    dataset = LoadStreams(source, img_size=imgsz)
  File "/content/yolov5/utils/datasets.py", line 204, in __init__
    assert cap.isOpened(), 'Failed to open %s' % s
AssertionError: Failed to open 0
```
I am trying to use JavaScript and Python to achieve real-time monitoring, but there are still many problems. Is there anyone with experience in this?

**Comment by glenn-jocher** [comment]
@GUOOOZI opencv webcam support is only available locally. All other operations should be accessible from a colab instance.

If you manage to get this working though, please do submit a PR!

**Comment by GUOOOZI** [comment]
In fact,
I have just successfully make it.
We can use JavaScript for img_data.

Thank you for answering.

**Comment by glenn-jocher** [comment]
Ah great? Could you submit a PR for the fix you applied to make it work so other people can benefit as well?

**Comment by GUOOOZI** [comment]
I just borrowed the method from this URL
[https://towardsdatascience.com/yolov3-pytorch-streaming-on-google-colab-16f4fe72e7b](url)

by the way, I am new to github. It's a little hard for me to submit a PR. But there is a Google Colab link in this website. It really works.

**Comment by Veecktor** [comment]
> I just borrowed the method from this URL
> [https://towardsdatascience.com/yolov3-pytorch-streaming-on-google-colab-16f4fe72e7b](url)
> 
> by the way, I am new to github. It's a little hard for me to submit a PR. But there is a Google Colab link in this website. It really works.

Please can you help with the exact code you used to fix the above issue, I am also facing the same issue. Thanks in advance

**Comment by GrahamboJangles** [comment]
@GUOOOZI - Please share what you did, I would also like to know how you accomplished this.

**Comment by fransachmadhw** [comment]
@GUOOOZI Hi sir, do you mind sharing your code, please? I really need the webcam to be working. Thank you

**Comment by glenn-jocher** [comment]
@fransachmadhw hello! Sure, here is an example code snippet you can use to access the webcam for real-time detection in YOLOv5:

```python
import cv2
import numpy as np
from IPython.display import display, Javascript
from google.colab.output import eval_js
from base64 import b64decode
import io


def detect():
    model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)

    video_frame = """
    <script>
      var video = document.querySelector("#myVideoElement");

      // resize the canvas to match the video dimensions
      document.querySelector("#myCanvasElement").width = video.width;
      document.querySelector("#myCanvasElement").height = video.height;

      // get canvas context for drawing
      var canvas = document.querySelector("#myCanvasElement");
      var ctx = canvas.getContext('2d');

      // draw the video to the canvas every 16ms (60fps)
      setInterval(() => {
        ctx.drawImage(video, 0, 0);
      }, 16);

      // data URL for the current canvas image
      function getCanvasImage() {
        return canvas.toDataURL('image/jpeg', 0.8);
      }
    </script>

    <video id="myVideoElement" controls autoplay></video>
    <canvas id="myCanvasElement" style="display: none"></canvas>
    """

    # display js in the output to prevent scrolling (or you can scroll forever)
    display(Javascript(video_frame))

    # use eval_js to access user's webcam and capture image
    js = Javascript('''
      async function useCam() {
        // use navigator.mediaDevices.getUserMedia to obtain camera stream
        const stream = await navigator.mediaDevices.getUserMedia({video: true});

        // display the stream as a video element
        const video = document.querySelector("#myVideoElement");
        video.srcObject = stream;

        // wait for video to play, then call window.saveFrame
        video.onloadedmetadata = (e) => {
          video.play();
          // the callback function that gets the current frame from the displayed video
          window.saveFrame = async () => {
            // create a canvas and draw the current video frame to it
            const canvas = document.createElement('canvas');
            canvas.width = video.videoWidth;
            canvas.height = video.videoHeight;
            const ctx = canvas.getContext('2d');

**Comment by fransachmadhw** [comment]
@glenn-jocher I really appreciate it but pardon me, sir. The code is incomplete sir. I already closed the last js statement and called eval_js but still got an error. Thank you

**Comment by glenn-jocher** [comment]
@fransachmadhw hello, I am sorry for the incomplete code you received earlier. Can you please provide more context on the error you encountered with the code you got? 

Also, are you trying to use the web browser and Colab to perform real-time YOLOv5 object detection? Please specify. 

I will be happy to help you resolve any issues you are experiencing.

**Comment by fransachmadhw** [comment]
@glenn-jocher Hi sir, I got the error like this
`TypeError: <IPython.core.display.Javascript object> is not JSON serializable`

Yes sir, I use a browser to run Colab.

I called the function `detect()` previously. Also, I added more lines to your code, like this
![image](https://user-images.githubusercontent.com/74099030/236151480-4f966a12-924e-4dcc-b371-cdce2a68f5e2.png)

Thank you

**Comment by glenn-jocher** [comment]
@fransachmadhw hello! Thank you for bringing this issue to our attention. It looks like there is an error with the serialization of the `Javascript` object returned by the `video_frame` variable in the `detect` function. 

To fix this issue, you can try wrapping the `video_frame` code inside a `bytes()` function to deserialize the `Javascript` object into a sequence of bytes that can be serialized. Here is an example:

```python
video_frame = """
<script>
// your JavaScript code here
</script>
"""

# convert video_frame to bytes
video_frame_bytes = bytes(video_frame.encode()) 

# display eval_js using video_frame_bytes
display(Javascript(eval_js(video_frame_bytes)))
```

Also, make sure that your IPython version is up-to-date. You can run the following command to check your IPython version:

```python
import IPython
print(IPython.__version__)
```

Let me know if this helps resolve the issue you are facing.

**Comment by aravamu2** [comment]
@fransachmadhw @glenn-jocher I was wondering if there is a working example to run yolov5s on a webcam in Google Colab for real-time detection. Thanks!

**Comment by glenn-jocher** [comment]
@aravamu2 hi there! Yes, there is a way to run YOLOv5 on a webcam in Google Colab for real-time detection. You can try the code snippet provided by Glenn in this issue: 
```python
# import necessary packages
import cv2
import numpy as np
from IPython.display import display, Javascript
from google.colab.output import eval_js
from base64 import b64decode
import io

# load the model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)

# function to perform real-time object detection
def detect():

    # define the video frame JS code
    video_frame = """
    <script>
    // your JavaScript code here
    </script>
    """

    # convert video_frame to bytes
    video_frame_bytes = bytes(video_frame.encode()) 

    # display eval_js using video_frame_bytes
    display(Javascript(eval_js(video_frame_bytes)))

    # access user's webcam and capture image for real-time detection
    js = Javascript('''
      async function useCam() {
        // use navigator.mediaDevices.getUserMedia to obtain camera stream
        const stream = await navigator.mediaDevices.getUserMedia({video: true});

        // display the stream as a video element
        const video = document.querySelector("#myVideoElement");
        video.srcObject = stream;

        // wait for video to play, then call window.saveFrame
        video.onloadedmetadata = (e) => {
          video.play();
          // the callback function that gets the current frame from the displayed video
          window.saveFrame = async () => {
            // create a canvas and draw the current video frame to it
            const canvas = document.createElement('canvas');
            canvas.width = video.videoWidth;
            canvas.height = video.videoHeight;
            const ctx = canvas.getContext('2d');
            ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
            // get the image data URL and convert to a base64-encoded byte array 
            const imageDataURL = canvas.toDataURL('image/jpeg', 0.8);
            const imageData = imageDataURL.replace(/^data:image\/(png|jpeg);base64,/, "");
            // call window.py_save_frame in Python kernel with the image byte array as argument
            google.colab.kernel.invokeFunction('py_save_frame', [imageData], {});
          }
        }
      }
    ''

**Comment by fransachmadhw** [comment]
Hello @aravamu2  , till now I still can't figure it yet on how to implement real-time webcam detection. Instead, I tried to use Streamlit to implement that and it works perfectly. Streamlit can run on both local and cloud environments like Colab.

**Comment by glenn-jocher** [comment]
Hello @fransachmadhw, 

Thank you for reaching out. If you're having trouble implementing real-time webcam detection in Colab, one alternative approach you can try is to use a Python library like Streamlit. Streamlit is a powerful tool that allows you to quickly build interactive web applications that can run both on your local machine and in the cloud (like Colab). 

Using Streamlit, you can easily set up a simple interface that takes input from the webcam and runs the YOLOv5 model to perform real-time object detection. 

I hope this helps! Let me know if you have any questions or need further assistance.
