### ISSUE TITLE
Is CiouLoss better than GiouLoss?

### ISSUE THREAD

**Issue by Edwardmark** [ultralytics/yolov5#1500]
## ❔Question

Is CiouLoss better than GiouLoss?
## Additional context
I trained my model using GiouLoss based on an historical commit using giou loss. Note that now the repo is using CIOU loss, so is the ciou loss better than giou loss? And how can I change the code to using ciou loss?
Thanks. @glenn-jocher

**Comment by glenn-jocher** [comment]
@Edwardmark CIoU loss may benefit smaller datasets on shorter trainings. For longer training on larger datasets, like COCO, there is no difference between the two, or small enough not to matter. You can read more here:

CIoU:
https://arxiv.org/abs/2005.03572

DIoU:
https://arxiv.org/abs/1911.08287

code:
https://github.com/Zzh-tju/CIoU

**Comment by Edwardmark** [comment]
@glenn-jocher Thanks for you kind reply.
