### ISSUE TITLE
I do not get the same performance as published with the pretrained model

### ISSUE THREAD

**Issue by Jacobi93** [ultralytics/yolov5#1504]
Hi,

Does anyone get the same problem as mine? I use exactly the same code and command to test pretrained models on the val set but do not get the same performance as published (e.g., mAP=35.4 from my result but 37 as published for YOLO5s).
I think one possible reason is becasue I did not download the coco 2017 dataset 100% correctly. As shown below, there are 48 empty labels. However, I was told that there are 48 empty labels indeed in the coco dataset. I am confused now. Does anyone know why？
Thanks.
<img width="945" alt="github1" src="https://user-images.githubusercontent.com/43407841/100197049-bd8ef680-2f34-11eb-8d9c-dd5ea4d4d72f.PNG">
<img width="946" alt="github2" src="https://user-images.githubusercontent.com/43407841/100197058-c1bb1400-2f34-11eb-95c7-aaf101e12f0f.PNG">

**Comment by glenn-jocher** [comment]
@Jacobi93 `pip install pycocotools` and rerun.

Our internal mAP results typically trail pycocotools mAP by about 1-2% for reasons unknown. It's been a longtime mystery.

**Comment by Jacobi93** [comment]
@glenn-jocher Thanks. I got the right performance using pycocotools.
