### ISSUE TITLE
Frame Loss in video stream

### ISSUE THREAD

**Issue by Rollson** [ultralytics/yolov5#1510]
## ❔Question
Hi, thank you for your great work:). Please I have 2 questions.
1. detect.py stops running any time there is a frame loss in the HTTP video stream.  I tried modifying the datasets.py to be able to handle frame loss but I couldn't fix it. Please what part of the datasets.py or detect.py can I modify to fix this frame loss issue and any ideas on how to do it?

2. Also which is the proper way to specify the --source argument in detect.py. Is it
python detect.py --source "http://"
or 
python detect.py --source http://

why am asking is because when the URL is not specified as a string (i.e when I run it this way: python detect.py --source http:// ) , detect.py only run for some seconds and then stops. 
Thanks for your response:)

**Comment by glenn-jocher** [comment]
@Rollson thanks for the notice. Please supply a Colab notebook with a reproducible example that we can look at.

String encapsulation is up to you and has no effect on inference.

**Comment by Rollson** [comment]
@glenn-jocher. thanks for your response. anytime there is a frame loss in the stream, it shows this error:

img = [letterbox(x, new_shape=self.img_size, auto=self.rect)[0] for x in img0]
  File "/home//Dokuments/yolov5/utils/datasets.py", line 696, in letterbox
    shape = img.shape[:2]  # current shape [height, width]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by glenn-jocher** [comment]
@Rollson so it seems that if there is a dropped frame, img will be equal to None, and this error will occur. Is there a way to reproduce this dropped stream event so we can test a fix?

**Comment by Rollson** [comment]
@glenn-jocher there is no way I can reproduce the dropped stream apart from testing with the stream url

**Comment by glenn-jocher** [comment]
@Rollson ok understood. If you can debug and produce a fix that's working on your side then, we'd be happy to review it as a PR.

**Comment by glenn-jocher** [comment]
@Rollson this same issue identified in #2155 and #2196. We should have a fix soon, though quite late for you, apologies.
