### ISSUE TITLE
Trained model deployment.

### ISSUE THREAD

**Issue by berkantay** [ultralytics/yolov5#1511]
## ❔Question

Hello,

I have finished with the training phase thanks to this repository. I obtained the model named ```best.pt``` now I want to deploy and make inference out of this model on another independent hardware (Jetson tx2 development board). How should I ***save***,***load*** and ***eval** the model?

## Additional context

Trained environment

Ubuntu 18.04
GPU:NVIDIA QUADRO P2000

Desired device to be deployed

Jetpack 4.4
Jetson TX2 Development Board

**Comment by glenn-jocher** [comment]
@berkantay please see Export tutorial:
https://docs.ultralytics.com/yolov5
