### ISSUE TITLE
Import and use 'detect', 'train' and 'test' in python script 

### ISSUE THREAD

**Issue by bonorico** [ultralytics/yolov5#1512]
## 🚀 Feature
I did sys.path.insert(1, <path_to_yolov5>) and imported detect.py, so to use detect.detect() in-script, instead of command-line.

## Motivation
The idea was to extend this approach to importing train.py (or test.py), and work with these modules and functions in-script 

## Pitch
 
In my experiment I had to add a "opt" argument to definition 'detect' in module detect.py, then copy the 'parser' object with all its arguments at the end of detect.py into my script, do  "opt = parser.parse_args()" , and finally custom-set opt.weights = <path_to_my_weights>, opt.source = <path_to_my_img_example>, opt.out="./" (current folder).

Then I executed detect.detect() from my script  and I got the error 

![Screenshot from 2020-11-25 12-35-37](https://user-images.githubusercontent.com/44023726/100256632-4c0b7400-2f45-11eb-8a53-0d8cb41ab4d4.png)

which caused the entire content of my current folder to go instantly lost. In my case this was a catastrophic data loss, that I totally did not expect. After some check up, this is because, if the out folder already exist, in line 30 of source code, 

shutil.rmtree(out)  # delete output folder

the folder it is removed and overwritten.

Just think that, it is not a remote possibility for someone to do such an horrific mistake (after all I did it), by simply trusting the code too much. I suggest to go extra safe and to avoid removing operations whatsoever. In my example, if line 30 (above) of detect.py did not exist, it would have saved my data.

Best

**Comment by glenn-jocher** [comment]
@bonorico hi, thanks for raising this issue! The output logging behavior of YOLOv5 was unified and completely updated about two weeks ago in https://github.com/ultralytics/yolov5/pull/1377 to prevent this sort of possibility. 

No data is deleted now, and data is only overwritten if --exist_ok is specifically passed. Please reclone and check often for updates.
