### ISSUE TITLE
run test.py cause lower map

### ISSUE THREAD

**Issue by Wolfhan99** [ultralytics/yolov5#1514]
## ❔Question
 Hi, @glenn-jocher , thanks for your nice work! 
But I met a problem and I wonder why, here is the thing:
I trained my custom datasets and get the mAP after training process is finished. And I used this trained last.pt to run test.py and I got the mAP is lower than the previous one.
That is to say,  run train.py and test.py will result in different mAP, do you have any clue what happen here?
I remain default settings, conf-thres is 0.001 and iou-thres is 0.65.

**Comment by glenn-jocher** [comment]
@Wolfhan99 you need to verify the same settings are used, i.e. iou threshold, confidence threshold, batch size etc.
