### ISSUE TITLE
A workaround for opencv's imread function being unable to read from unicode filepath

### ISSUE THREAD

**Issue by jikhanjung** [ultralytics/yolov5#1515]
Before submitting a bug report, please be aware that your issue **must be reproducible** with all of the following, otherwise it is non-actionable, and we can not help you:
 - **Current repo**: run `git fetch && git status -uno` to check and `git pull` to update repo
 - **Common dataset**: coco.yaml or coco128.yaml
 - **Common environment**: Colab, Google Cloud, or Docker image. See https://github.com/ultralytics/yolov5#environments
 
If this is a custom dataset/training question you **must include** your `train*.jpg`, `test*.jpg` and `results.png` figures, or we can not help you. You can generate these with `utils.plot_results()`.

## 🐛 Bug
When I try to test the detect.py with an image file with Korean characters in the filename, 'Image Not Found' assertion error occurs. 

## To Reproduce (REQUIRED)

Input:
```
cp ./data/images/zidane.jpg ./data/images/지단.jpg 
python detect.py --source ./data/images/지단.jpg
```

Output:
```
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.25, device='', exist_ok=False, img_size=640, iou_thres=0.45, name='exp', project='runs/detect', save_conf=False, save_txt=False, source='./data/images/지단.jpg', update=False, view_img=False, weights='yolov5s.pt')
Using torch 1.6.0 CUDA:0 (GeForce GTX 1050 Ti, 4096MB)

Fusing layers...
Model Summary: 232 layers, 7459581 parameters, 0 gradients
Traceback (most recent call last):
  File "detect.py", line 173, in <module>
    detect()
  File "detect.py", line 62, in detect
    for path, img, im0s, vid_cap in dataset:
  File "C:\Users\Elite\conda_projects\yolov5\utils\datasets.py", line 182, in __next__
    assert img0 is not None, 'Image Not Found ' + path
AssertionError: Image Not Found C:\Users\Elite\conda_projects\yolov5\data\images\지단.jpg
```

## Expected behavior
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.25, device='', exist_ok=False, img_size=640, iou_thres=0.45, name='exp', project='runs/detect', save_conf=False, save_txt=False, source='./data/images/지단.jpg', update=False, view_img=False, weights='yolov5s.pt')
Using torch 1.6.0 CUDA:0 (GeForce GTX 1050 Ti, 4096MB)

Fusing layers...
Model Summary: 232 layers, 7459581 parameters, 0 gradients
image 1/1 C:\Users\Elite\conda_projects\yolov5\data\images\지단.jpg: 384x640 2 persons, 2 ties, Done. (0.024s)
Results saved to runs\detect\exp8
Done. (0.790s)

## Environment

 - OS: Windows10
 - GPU: 1050 Ti

## Additional context
I resolved this issue by replacing:
            img0 = cv2.imread(path)  # BGR
with:
            ff = np.fromfile(path, np.uint8)
            img0 = cv2.imdecode(ff, cv2.IMREAD_UNCHANGED)            

in line 175 of utils/dataset.py. 

I know this is not really a bug of yolov5 per se, but it's rather an easy fix here.

**Comment by glenn-jocher** [comment]
@jikhanjung hi thanks for the interesting note here. I think the best place to bring this up would be on the two main image loading repositories, opencv and pillow. 

In any case, we could not implement this as is without significant profiling to ensure that image loading speeds were unaffected during training, testing, inference, etc, as the speed of image loading and decompressing is naturally extremely important here, and the proposed solution provides quite a different pathway for this.
