### ISSUE TITLE
A question about loss  calculation

### ISSUE THREAD

**Issue by JoJoliking** [ultralytics/yolov5#1517]
## ❔Question
What does this code control in the loss calculation function?
compute_loss：
    s = 3 / no  # output count scaling
    lbox *= h['box'] * s
    lobj *= h['obj'] * s * (1.4 if no == 4 else 1.)
    lcls *= h['cls'] * s
## Additional context
I added four offsets of the bounding box to the output of yolo5. During the coco128 training test, I found that:
1. If the offset loss value is not multiplied by s, the testing AP value will be problematic and very small.
![image](https://user-images.githubusercontent.com/55232435/100316305-3190d380-2ff5-11eb-96a0-b3f1d3368760.png)
2. When I add ：loffset *= h['box'] * s。The AP is normal， but the target number is smaller 。Like this：
![image](https://user-images.githubusercontent.com/55232435/100316680-ff33a600-2ff5-11eb-869e-04c98ca6614d.png)

**Comment by yecunliang** [comment]
Hello，I want to change the loss function for bounding box regression to CIoU.But because I'm a beginner, I don't know where and how to adjust the code,could you give me some hints or suggestions.Thank you very much!

**Comment by JoJoliking** [comment]
@yecunliang You should modify the Detect and compute_loss function. Dubug code is all you need.

**Comment by yecunliang** [comment]
> @yecunliang You should modify the Detect and compute_loss function. Dubug code is all you need.

Thank you very much!

**Comment by yecunliang** [comment]
Thank you very much!
