### ISSUE TITLE
detect.py use csi camera ass source

### ISSUE THREAD

**Issue by berkantay** [ultralytics/yolov5#1518]
## ❔Question
Hello everyone I have deployed my model to Jetson TX2. And I have csi camera attached to my board. However when tried to make inference using this camera with
```python3.6 detect.py --source 0``` pipeline was not generated. What should I give to ```--source``` to make my csi camera visible for yolov5?
## Additional context
I am able to start my camera using the gstreamer comand below.
```gst-launch-1.0 nvarguscamerasrc sensor-id=0 sensor-mode=0 ! 'video/x-raw(memory:NVMM), width=(int)1948, height=(int)1096, format=(string)NV12, framerate=(fraction)30/1' ! nvvidconv ! nveglglessink -e```

**Comment by glenn-jocher** [comment]
@berkantay I think you may need to compile cv2 from source specifically for gstreamer support if you intend to use gstreamer pipelines. I'd google the topic.
