### ISSUE TITLE
detecting different sources

### ISSUE THREAD

**Issue by ferro07** [ultralytics/yolov5#1520]
hey, @glenn-jocher 
Instead of using below sources, 
$ python detect.py --source 0  # webcam
                            file.jpg  # image 
                            file.mp4  # video
                            path/  # directory
                            path/*.jpg  # glob
                            rtsp://170.93.143.139/rtplive/470011e600ef003a004ee33696235daa  # rtsp stream
                            rtmp://192.168.1.105/live/test  # rtmp stream
                            http://112.50.243.8/PLTV/88888888/224/3221225900/1.m3u8  # http stream

How to detect the images coming to the monitor in real time. We are working on a medical device and there is no webcam or recording system. We can only see the images coming to the monitor instantly in our hands. What can we do about it? I mean, how can we detect in real time by taking the data coming to the monitor.
Thanks in advance for your help and answers ...

**Comment by glenn-jocher** [comment]
@ferro07 you'd need to interface with the program producing the images, and be able to get them into a python environment for pytorch inference, or other environments with an exported model.

**Comment by ferro07** [comment]
> 
> 
> @ferro07 you'd need to interface with the program producing the images, and be able to get them into a python environment for pytorch inference, or other environments with an exported model.

@glenn-jocher 
What do you mean by expert system ?
it is about a capture card or connecting to like raspberry pi, ardunio, jetson nano ?

**Comment by glenn-jocher** [comment]
@ferro07 deployment is something you need to work out for yourself based on your requirements and your constraints.
