### ISSUE TITLE
AttributeError: 'function' object has no attribute 'names'

### ISSUE THREAD

**Issue by DL-Alva** [ultralytics/yolov5#1521]
After finishing training the model with my own dataset, I run "detect.py" to test my data. However, it remind me:

Traceback (most recent call last):
  File "detect.py", line 164, in <module>
    detect()
  File "detect.py", line 48, in detect
    names = model.names if hasattr(model, 'names') else model.modules.names
AttributeError: 'function' object has no attribute 'names'

Would you please help me with this problem? Looking forward to your reply.

**Comment by glenn-jocher** [comment]
@DL-Alva all YOLOv5 models have a .names attribute that lists the class names. Detect.py can not find yours for some reason. You can manually create one: 
`model.names = ['class1','class2', etc...]`

**Comment by DL-Alva** [comment]
> @DL-Alva all YOLOv5 models have a .names attribute that lists the class names. Detect.py can not find yours for some reason. You can manually create one:
> `model.names = ['class1','class2', etc...]`

Thank you for your reply.  I tried it according to your suggestion. The error mentioned above is not displayed, but no target object is detected on the test sets.

**Comment by glenn-jocher** [comment]
@DL-Alva then your model is not capable of detecting objects in your test set given the inference settings you've used.

**Comment by DL-Alva** [comment]
> @DL-Alva then your model is not capable of detecting objects in your test set given the inference settings you've used.

Yes, it seems like this.
