### ISSUE TITLE
Error happens when running detect.py according to README

### ISSUE THREAD

**Issue by lipond** [ultralytics/yolov5#1522]
python detect.py --weights weights/yolov5s.pt --img-size 640 --data data/coco.yaml
usage: detect.py [-h] [--weights WEIGHTS [WEIGHTS ...]] [--source SOURCE]
                 [--img-size IMG_SIZE] [--conf-thres CONF_THRES]
                 [--iou-thres IOU_THRES] [--device DEVICE] [--view-img]
                 [--save-txt] [--save-conf] [--classes CLASSES [CLASSES ...]]
                 [--agnostic-nms] [--augment] [--update] [--project PROJECT]
                 [--name NAME] [--exist-ok]
detect.py: error: unrecognized arguments: --data data/coco.yaml

**Comment by glenn-jocher** [comment]
@lipond detect.py does not accept a --data argument. See README for detection example:
https://github.com/ultralytics/yolov5#inference
