### ISSUE TITLE
ONNX runtime of Yolo5

### ISSUE THREAD

**Issue by flixmk** [ultralytics/yolov5#1525]
## ❔Question
I want to implement my trained model into the onnx runtime.
I have found this tutorial: https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-onnx#feedback
But since i get really strange results i know i am doing something wrong. Can someone tell me what I have to look out for when changing something like this to make it work for yolov5?

## Additional context
An explanation of what to look out for would be really healpful. I saw in netron that YOLOm has 3 outputs on different stages of the network. What are they for and why 3 instead of 1?

If there is more information needed then please say so.

Thanks in advance for your time :D

**Comment by smartinellimarco** [comment]
Read this entire thread thoroughly:
- https://docs.ultralytics.com/yolov5/tutorials/model_export
You should edit export.py inside model/ folder, and change model[-1].export = True to False.
Then use NMS (browse code) over the first output returned by the onnx model.
