### ISSUE TITLE
webcam error

### ISSUE THREAD

**Issue by zfong96** [ultralytics/yolov5#1530]
$ python detect.py --source 0 # webcam

I am newbie here. Want to ask that i run the code above and i get this error, 
AttributeError: 'NoneType' object has no attribute 'shape'

my webcam is on, and i can run it using other images. 
thanks in advance

**Comment by Leggerla** [comment]
```
!git clone https://github.com/ultralytics/yolov5  # clone repo
%cd yolov5
%pip install -qr requirements.txt  # install dependencies

import torch
from IPython.display import Image, clear_output  # to display images

clear_output()
print('Setup complete. Using torch %s %s' % (torch.__version__, torch.cuda.get_device_properties(0) if torch.cuda.is_available() else 'CPU'))

```
`!python detect.py --weights yolov5s.pt --conf 0.25 --source '0' --classes 0`

This gives an error:

```
1/1: 0... Traceback (most recent call last):
  File "detect.py", line 173, in <module>
    detect()
  File "detect.py", line 49, in detect
    dataset = LoadStreams(source, img_size=imgsz)
  File "/content/yolov5/utils/datasets.py", line 275, in __init__
    assert cap.isOpened(), 'Failed to open %s' % s
AssertionError: Failed to open 0
```

If in source I write folder name of images/videos - works all good.

**Comment by zfong96** [comment]
how can i know the source for my webcam?

i am using --source 0, and the error is this 
Using torch 1.7.0+cpu CPU

Namespace(agnostic_nms=False, augment=False, classes=[0], conf_thres=0.25, device='', exist_ok=False, img_size=640, iou_thres=0.45, name='exp', project='runs/detect', save_conf=False, save_txt=False, source='0', update=False, view_img=False, weights=['yolov5/foodv2_best.pt'])
Fusing layers... 
Model Summary: 232 layers, 7254609 parameters, 0 gradients
1/1: 0...  success (640x480 at 30.00 FPS).

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
e:\psmmm\yolov5\yolov5\detect.py in <module>
    171                 strip_optimizer(opt.weights)
    172         else:
--> 173             detect()

e:\psmmm\yolov5\yolov5\detect.py in detect(save_img)
     47         view_img = True
     48         cudnn.benchmark = True  # set True to speed up constant image size inference
---> 49         dataset = LoadStreams(source, img_size=imgsz)
     50     else:
     51         save_img = True

e:\psmmm\yolov5\yolov5\utils\datasets.py in __init__(self, sources, img_size)
    284 
    285         # check for common shapes
--> 286         s = np.stack([letterbox(x, new_shape=self.img_size)[0].shape for x in self.imgs], 0)  # inference shapes
    287         self.rect = np.unique(s, axis=0).shape[0] == 1  # rect inference if all shapes equal
    288         if not self.rect:

e:\psmmm\yolov5\yolov5\utils\datasets.py in <listcomp>(.0)
    284 
    285         # check for common shapes
--> 286         s = np.stack([letterbox(x, new_shape=self.img_size)[0].shape for x in self.imgs], 0)  # inference shapes
    287         self.rect = np.unique(s, axis=0).shape[0] == 1  # rect inference if all shapes equal
    288         if not self.rect:

e:\psmmm\yolov5\yolov5\utils\datasets.py in letterbox(img, new_shape, color, auto, scaleFill, scaleup)
    694 def letterbox(img, new_shape=(640, 640), color=(114, 114, 114), auto=True, scaleFill=False, scaleup=True):
    695     # Resize image to a 32-pixel-multiple rectangle https://github.com/ultralytics/yolov3/issues/232
--> 696     shape = img.shape[:2]  # current shape [height, width]
    697     if isinstance(new_shape, int):
    698         new_shape = (new_shape, new_shape)

AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by glenn-jocher** [comment]
@zfong96 webcam is not a valid source in the Colab or Kaggle notebooks. You can use it locally, ie on your Macbook.

**Comment by zfong96** [comment]
I'm using it on my windows laptop. Using visual studio code. But i can run it on my other webcam. But my own laptop webcam, no.
Thanks anyway

**Comment by glenn-jocher** [comment]
cv2 has a complicated interplay among various backends and environments. If it doesn't work for you on one you may want to raise an issue on opencv/opencv

**Comment by TommyZihao** [comment]
@zfong96 I have the same problem, you can just change to another webcam and try, some webcams are not supported for development.

**Comment by zfong96** [comment]
@TommyZihao  thanks for the advice bro. Seems that's the problem, change another webcam, and it can run no problem
