### ISSUE TITLE
Docker images should be versioned and tagged

### ISSUE THREAD

**Issue by kinoute** [ultralytics/yolov5#1531]
## 🚀 Feature

Tag docker images.

## Motivation

Right now, a new image is built and pushed to the Docker Hub as soon as a commit is merged. It is not suitable for production. For example, today, there was a problem with the boxes.max() & normalisation stuff that just got fixed. In the meantime, people code gets broken. I had to clone and checkout to v3.1 to get things working...

## Pitch

Every release should get its own docker image tagged with the number of the release, e.g v3.0, v3.1. Thanks.

**Comment by glenn-jocher** [comment]
@kinoute yes that's a great idea. Do you know if there is an automated process we could set up for pushing tags on releases?

**Comment by glenn-jocher** [comment]
@kinoute since the release count is manageable I decided just to do this manually for now. DockerHub is now updated with all releases, i.e. 
```bash
t=ultralytics/yolov5:v3.1 && sudo docker pull $t && sudo docker run -it --ipc=host $t
```

You can see all available tags here:
https://hub.docker.com/repository/docker/ultralytics/yolov5

**Comment by kinoute** [comment]
This is much better! Thank you!
