### ISSUE TITLE
Why didn't I get the output？

### ISSUE THREAD

**Issue by Scoii-xx** [ultralytics/yolov5#1536]
## ❔Question
![(P)G59)IB MZ OXLR (99GQ](https://user-images.githubusercontent.com/64119723/100406465-dcaa9700-30a0-11eb-843d-a09a9febe3e1.png)

**Comment by glenn-jocher** [comment]
@Scoii-xx no objects were detected in your images. Can you supply a reproducible example, i.e. in a Colab notebook?

**Comment by AYang-127** [comment]
I have the same question,please help me,bro.Thanks!
