### ISSUE TITLE
Only a few categories can be detected in each image

### ISSUE THREAD

**Issue by DL-Alva** [ultralytics/yolov5#1537]
## ❔Question

After training process with the recently updated models, I run "detect.py" and found only one or two classes can be detected in each image. However, when I use the previously unupdated model to train and perform the prediction, the predicted classes will be as many as possible.

**Comment by DL-Alva** [comment]
detect result with updated model:

![20200308_00109P](https://user-images.githubusercontent.com/22760056/100429875-f368e200-30d0-11eb-8bd4-538e5954836d.jpg)
![20200308_00110P](https://user-images.githubusercontent.com/22760056/100429892-fe237700-30d0-11eb-8e49-c6327e6dcf01.jpg)


detect result with unupdated model:
![242](https://user-images.githubusercontent.com/22760056/100430121-49d62080-30d1-11eb-96eb-315c09dbcc32.jpg)

![227](https://user-images.githubusercontent.com/22760056/100430051-37f47d80-30d1-11eb-9b63-d2f64d6b939e.jpg)

**Comment by glenn-jocher** [comment]
@DL-Alva if you're asking how to improve your results, I'll just tell you what I tell everybody else:

- Use a larger model
- Use a larger dataset
- Train longer
- Use TTA
- Use Hyperparameter evolution
