### ISSUE TITLE
how to save :AssertionError: Label class 16 exceeds nc=1 in ../data.yaml. Possible class labels are 0-0

### ISSUE THREAD

**Issue by yaober** [ultralytics/yolov5#1538]

**Comment by yaober** [comment]
![image](https://user-images.githubusercontent.com/61397007/100431860-b5b98880-30d3-11eb-8017-78c33e308b20.png)

**Comment by glenn-jocher** [comment]
@yaober your dataset can only contain a class 0, as you specified in your data.yaml. You've provided labels that have up to class 16.

**Comment by yaober** [comment]
but i just have one label class,in my dataset just have one too





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ultralytics/yolov5"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月27日(星期五) 下午5:15
收件人:&nbsp;"ultralytics/yolov5"<yolov5@noreply.github.com&gt;;
抄送:&nbsp;"北方"<2576094621@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ultralytics/yolov5] how to save :AssertionError: Label class 16 exceeds nc=1 in ../data.yaml. Possible class labels are 0-0 (#1538)





 
@yaober your dataset can only contain a class 0, as you specified in your data.yaml. You've provided labels that have up to class 16.

**Comment by yaober** [comment]
> ur dataset can only contain a class 0,

but i just have one label class,in my dataset just have one too

**Comment by yaober** [comment]
![Uploading image.png…]()

**Comment by yaober** [comment]
![image](https://user-images.githubusercontent.com/61397007/100432847-24e3ac80-30d5-11eb-9a4f-874480d635cf.png)

**Comment by glenn-jocher** [comment]
@glenn-jocher your dataset has classes labelled as 16. You need to fix your dataset.

**Comment by yaober** [comment]
how to fix






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ultralytics/yolov5"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月27日(星期五) 下午5:23
收件人:&nbsp;"ultralytics/yolov5"<yolov5@noreply.github.com&gt;;
抄送:&nbsp;"北方"<2576094621@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ultralytics/yolov5] how to save :AssertionError: Label class 16 exceeds nc=1 in ../data.yaml. Possible class labels are 0-0 (#1538)





 
@glenn-jocher your dataset has classes labelled as 16. You need to fix your dataset.

**Comment by glenn-jocher** [comment]
See https://docs.ultralytics.com/yolov5/tutorials/train_custom_data

**Comment by yaober** [comment]
i follow this tips,but error to.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ultralytics/yolov5"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月27日(星期五) 下午5:25
收件人:&nbsp;"ultralytics/yolov5"<yolov5@noreply.github.com&gt;;
抄送:&nbsp;"北方"<2576094621@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ultralytics/yolov5] how to save :AssertionError: Label class 16 exceeds nc=1 in ../data.yaml. Possible class labels are 0-0 (#1538)





 
See https://docs.ultralytics.com/yolov5/tutorials/train_custom_data

**Comment by yaober** [comment]
i fthis is my dataset ,please help me, i sincerly thank for you


i use it to check it




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "ultralytics/yolov5"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月27日(星期五) 下午5:25
收件人:&nbsp;"ultralytics/yolov5"<yolov5@noreply.github.com&gt;;
抄送:&nbsp;"北方"<2576094621@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ultralytics/yolov5] how to save :AssertionError: Label class 16 exceeds nc=1 in ../data.yaml. Possible class labels are 0-0 (#1538)





 
See https://docs.ultralytics.com/yolov5/tutorials/train_custom_data

**Comment by Pambao** [comment]
That probably because your current execution have reloaded the .cache from your "labels" folder which haven't been updated when you modify the actual label in the .txt file. Try deleting the .cache file and run it again

**Comment by ghost** [comment]
That probably because your current execution has reloaded the labels from the .cache file in your label folder, which hasn't been updated when you modify the actual label in the .txt file. Maybe try to delete the .cache and rerun it.

**Comment by mayukhberkeley** [comment]
When training with data I got annotated in _Roboflow_, I saw this error when I overwrote my train, valid, and test folder with the newly downloaded dataset using `cp -r`
I removed the previous datasets completely and then download new ones, looks like the dataset folders had contents from my previously downloaded datasets

**Comment by glenn-jocher** [comment]
@mayukhberkeley  this error is generated by an unsupported 3rd party notebook. Please see the official YOLOv5 Colab Notebook below, and visit the Train Custom Data Tutorial to get started with YOLOv5.
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

## Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [ONNX and TorchScript Export](https://docs.ultralytics.com/yolov5/tutorials/model_export)
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

## Requirements

**Python 3.8** or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including **`torch>=1.7`**. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by triyam** [comment]
![image](https://user-images.githubusercontent.com/55938092/145912817-12be4d17-c3de-4c8b-aa26-c5ab48f88757.png)

Your label file may be something like this

The first part is label where I have 15 labels in default in my annotation software which are dog, bike, car etc.. which I don't require.

Change it to **1** if you are working on **single class**.

if you are working on **multiclass** then, **_change the class number to the first part of label instead of 15_**.

![image](https://user-images.githubusercontent.com/55938092/145913378-759ad09c-3fa6-449c-8efe-2a181d8c54a0.png)

I have changed it to 1 because I am working on single class

**Comment by glenn-jocher** [comment]
@triyam python is zero indexed so single class datasets should be labelled as class 0. See Train Custom Data tutorial for details on correctly formatting your dataset:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TFLite, ONNX, CoreML, TensorRT Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

Good luck 🍀 and let us know if you have any other questions!

**Comment by Kiisso** [comment]
Hello, have you solved your problem? I have the same problem.

**Comment by kranercc** [comment]
This is because your 1.txt 2.txt information has 
1 0.something 0.something
make sure that 1 is 0 if you only work with one class
here is a simple script to modify all the 1's with 0's

```py
import os
import sys

files = os.listdir(".")


for file in files:
    if ".txt" in file:
        with open(file, "r") as f:
            lines = f.readlines()
            for line in lines:
                if line[0] == "1":
                    line = line.replace("1", "0")
                    with open(file, "w") as f:
                        f.write(line)
                    print(line)
                else:
                    print(line)
                    continue
    else:
        continue


```

**Comment by vocdex** [comment]
@ kranercc
Just a warning! This will replace all the "1"s inside txt with "0". Instead, we want to replace only the class ID "1" with "0".

**Comment by Robotatron** [comment]
Isnt class: 0 reserved to be a background images in COCO? I.e. in the COCO format, the first label starts with "1", not "0".

**Comment by valentin-fngr** [comment]
> That probably because your current execution has reloaded the labels from the .cache file in your label folder, which hasn't been updated when you modify the actual label in the .txt file. Maybe try to delete the .cache and rerun it.

This also works on Yolov8

**Comment by glenn-jocher** [comment]
@valentin-fngr thank you for sharing your experience and solution. That is correct! When dealing with custom datasets, it may be necessary to manually refresh the cache file in order to reflect the latest changes made in the label files. Your solution of deleting the cache and rerunning the code can be an effective way to do this. 

Note that, depending on the specific details of your workflow, there may be different ways to handle label files and caching. In some situations, it may be more appropriate to manually refresh the cache file using certain flags or command line arguments. Thank you for sharing your insight and contributing to the community's knowledge base!

**Comment by khoshg** [comment]
Go for the Label files (.txt). Open it, and check for the class id. that is, the first number for each file. If you have one class, change the class ID to 0. That's it. Make a program to do this if you have so many files.

**Comment by glenn-jocher** [comment]
@khoshg to modify the class ID in the label files, you can follow these steps:

1. Open each label file (.txt) and locate the class ID, which is the first number in each line.
2. If you have only one class, change the class ID to 0.
3. Repeat this process for all the label files.

If you have a large number of files, you can consider writing a program to automate this process. The program can iterate through each file, open it, and update the class ID as necessary. Remember to save the modified label files after making the changes.

Please let me know if you have any further questions or need any additional assistance.
