### ISSUE TITLE
Train failed when test

### ISSUE THREAD

**Issue by yunchangxiaoguan** [ultralytics/yolov5#154]
![image](https://user-images.githubusercontent.com/47582901/85216301-584b3e00-b3b5-11ea-8653-5a67a871dab5.png)

when 1 epoch end it test but error,what is the problem,how to solve it,thanks

**Comment by glenn-jocher** [comment]
@yunchangxiaoguan environment problems. 

## Reproduce Our Environment

To access an up-to-date working environment (with all dependencies including CUDA/CUDNN, Python and PyTorch preinstalled), consider a:

- **GCP** Deep Learning VM with $300 free credit offer: See our [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Google Colab Notebook** with 12 hours of free GPU time. <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/)

**Comment by shijiexin** [comment]
use the pytorch1.5 not 1.4,and change the train.py
![image](https://user-images.githubusercontent.com/43631555/85642961-6eaf0d80-b6c5-11ea-893b-b6ad2f225427.png)

**Comment by shijiexin** [comment]
change the train.py  
154   #model = torch.nn.parallel.DistributedDataParallel(model)
          model = torch.nn.DataParallel(model)
someone also said the pytorch1.4 is ok.

**Comment by yunchangxiaoguan** [comment]
> change the train.py
> 154 #model = torch.nn.parallel.DistributedDataParallel(model)
> model = torch.nn.DataParallel(model)
> someone also said the pytorch1.4 is ok.

好的，谢谢大佬，我去试试
