### ISSUE TITLE
val/box_loss and val/cls_loss plots are not updating...

### ISSUE THREAD

**Issue by Rm1n90** [ultralytics/yolov5#1540]
Hey @glenn-jocher, 

The val/box_loss and val/cls_loss plots are not updating in both tensorboard and W&B. Also, W&B is not showing the prediction!

![box](https://user-images.githubusercontent.com/51209972/100429810-29d53b80-3096-11eb-8567-265d0a2dbb11.png)

Thanks

**Comment by glenn-jocher** [comment]
@Rm1n90 this was a bug discovered in #1528 and resolved in PR #https://github.com/ultralytics/yolov5/pull/1529.

Please git pull to receive this update, and let us know if you have any other issues.
