### ISSUE TITLE
CSPDarknet53 ? 

### ISSUE THREAD

**Issue by a-esp-1** [ultralytics/yolov5#1541]
## ❔Question
Is YOLOv5 using CSPDarknet53 as backbone?

**Comment by glenn-jocher** [comment]
@a-esp-1 YOLOv5 backbones are used. Details are shown each model yaml file:
https://github.com/ultralytics/yolov5/blob/97a5227a1a13f59dce4b896e40d411c13fbdb7b3/models/yolov5s.yaml#L12-L26
