### ISSUE TITLE
please add .strip() to remove trailing new lines caused by data preparation. All the images go to corrupted count due to this

### ISSUE THREAD

**Issue by azhar-autocanvas** [ultralytics/yolov5#1542]
https://github.com/ultralytics/yolov5/blob/97a5227a1a13f59dce4b896e40d411c13fbdb7b3/utils/datasets.py#L453

**Comment by glenn-jocher** [comment]
@azhar-autocanvas hi thanks for the suggestion. Can you please submit a PR with your recommended changes? Thank you!

**Comment by glenn-jocher** [comment]
@azhar-autocanvas this suggestion has been implemented in PR #1551. 

Thank you for your contributions!
