### ISSUE TITLE
Trailing new lines in the dataset labels

### ISSUE THREAD

**Issue by azhar-autocanvas** [ultralytics/yolov5#1543]
please add f.read().strip() to remove trailing new lines caused by data preparation. All the images go to corrupted count due to this
https://github.com/ultralytics/yolov5/blob/97a5227a1a13f59dce4b896e40d411c13fbdb7b3/utils/datasets.py#L453

**Comment by glenn-jocher** [comment]
@azhar-autocanvas let's keep this convo in #1542.
