### ISSUE TITLE
ValueError: zero-size array to reduction operation maximum which has no identity

### ISSUE THREAD

**Issue by C-BinJie** [ultralytics/yolov5#1544]
`Starting training for 50 epochs...

     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
      0/49     3.68G    0.1244   0.02945   0.02958    0.1835         8       640:   0%|      | 0/286 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 492, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 314, in train
    plot_images(images=imgs, targets=targets, paths=paths, fname=f)
  File "D:\yolov5\utils\plots.py", line 143, in plot_images
    if boxes.max() <= 1:  # if normalized
  File "D:\ProgramData\Anaconda3\envs\yolo\lib\site-packages\numpy\core\_methods.py", line 39, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation maximum which has no identity`

**Comment by glenn-jocher** [comment]
@C-BinJie this was fixed yesterday in PR https://github.com/ultralytics/yolov5/pull/1529. Please git pull and try again.
