### ISSUE TITLE
train.py stops itself

### ISSUE THREAD

**Issue by JiaLim98** [ultralytics/yolov5#155]
Hi,

Thank you so much for the incredible work.

I have modified the tutorial colab notebook to suit my own dataset. Here are the changes I made:
1. path, nc, classes in /data/coco128.yaml
2. nc in /models/yolov5x.yaml
3. the dataset was imported the same way (download from my google drive's zip file and move it alongside with yolov5 folder)

Here's the output I got (see bottom left corner):
![image](https://user-images.githubusercontent.com/66768413/85219853-b0943700-b3d9-11ea-9290-3154a0dd93ee.png)
It just interrupted itself (I did not press Ctrl+C). This happens straight after the memory bar on the top right is maxed out. I even tried using a batch size of 1 and I still get the same thing. Am I missing something?

Additional questions:
1. How to compute the most accurate anchors using the k_mean_achor in utils.py?
2. How to make the model train on images of size 600? is it resizing to 608 before the training start?

Regards,
JiaLim98

**Comment by glenn-jocher** [comment]
@JiaLim98 colab automatically ctrl c'd your program as you've exceeded the system ram. See all those images you are caching and all that memory it's using...?

**Comment by JiaLim98** [comment]
@glenn-jocher My dataset consists of 5120 train images and 3414 validate images of size 600x600. I believe it is still able to train since the image size is not that huge. Do you know how to solve this? What do you mean by 
> See all those images you are caching and all that memory it's using...?

Note: I am using yolov5x, but it shouldn't be that large to use up all the memory. Am I right?

**Comment by JiaLim98** [comment]
My original dataset is just 1.11GB total (train+validate+test). Why is it caching until 5.7GB (train) and 3.8GB (validate)? Is there something I did wrong?

**Comment by glenn-jocher** [comment]
@JiaLim98 compressed image sizes have nothing in common with the memory consumed when loaded.

**Comment by JiaLim98** [comment]
@glenn-jocher I understand now. Thank you so much!
I have one more question:
How to compute the most suitable anchors for one dataset? (e.g. the 3 lines shown below)
![image](https://user-images.githubusercontent.com/66768413/85242905-dcafc680-b472-11ea-88e5-ad8666aa0a99.png)
What does the P3/8, P4/16 and P5,32 mean?
