### ISSUE TITLE
Tech stack for yolo video feeds

### ISSUE THREAD

**Issue by 5starkarma** [ultralytics/yolov5#1556]
## ❔Question
I have some object detection models I would like to deploy into a production environment. I am wondering what stack is often used with yolov5 and why? The system I would like to create would have to handle multiple video feeds in real-time for each company (security). One of my first thoughts was to develop a system/server in-house, with GPUs, which could handle the load but this would mean setting up multiple systems of such across several companies and having to manage all of them. Also, this is 2020 so I imagine having video feeds run to a server for object detection then access by the company is direct to the server would be the possible (and the way to go).

## Additional context

I come from the world of Django but talking to a ML engineer at a big Google venture backed company, they said they used node.js, Google Cloud, and react. Is this the way to go? Why or why not? How would this look? Would Google Cloud handle each video stream as an API and node.js handle the server-side code while react handles native/web code?

To add to this I am very comfortable with Python. Is there a good way to handle this using strictly Python?

Please be kind as I am just doing the preliminary research on what systems would work best in this scenario.

**Comment by glenn-jocher** [comment]
@5starkarma that's a good question. We can natively run inference on multithreaded streams (RTSP, HTTP, etc.) in PyTorch using the YOLOv5 LoadStreams() dataloader:
https://github.com/ultralytics/yolov5/blob/68211f72c99915a15855f7b99bf5d93f5631330f/utils/datasets.py#L257

There is no limit to the number of sources you can attach to the LoadStreams() dataloader. With sufficient hardware and bandwidth you can process hundreds or even thousands of sources in parallel.

**Comment by 5starkarma** [comment]
HI @glenn-jocher! Thanks for the response.

In your experience, what cloud platform/instance choices have worked well for starting a project handling scalable amount of feeds? Also, do you have any suggestions for specific GPUs if we were to keep the systems on property? Being that you have likely been through this before do you have any bottlenecks, headaches, or cost comparisons you might be willing to share?

**Comment by glenn-jocher** [comment]
@5starkarma it's all up to your hardware really and how flexible you are in your requirements. Obviously you would target the best FLOPS/dollar you can find on the market. If you assume you'll need 1 thread per stream then you can figure out what sort of hardware you'll need, i.e. a 32 CPU box might handle decompressing 32 realtime HD streams if your network can support the throughput etc.

As for flexibility, you can process a 4k 30FPS stream in realtime or 100 smaller streams at 1 FPS, etc etc, you get the picture.

**Comment by 5starkarma** [comment]
Great responses and enough useful information to get me going down the correct path. Thanks!

**Comment by karanjakhar** [comment]
@5starkarma You can use Nvidia Deepstream SDK.
