### ISSUE TITLE
Training on additional images

### ISSUE THREAD

**Issue by ferro07** [ultralytics/yolov5#1557]
hey @glenn-jocher,
Normally I completed the training process on 10000 images and kept the best weight.
Now, I want to add 1000 additional images to the training set.
What I want to ask is, do I just have to do training on just 1000 images with the best weight, or have to do train for 1000 + 10000 or 11000 images? In short, what kind of training should be for the extra 1000 images. (I want to save time and gpu)
Thank you so much.

**Comment by glenn-jocher** [comment]
@ferro07 train on all images.

**Comment by ferro07** [comment]
@glenn-jocher 
Thanks for quick reply...
