### ISSUE TITLE
RuntimeError: expected device cuda:0 and dtype Float but got device cuda:0 and dtype Half 

### ISSUE THREAD

**Issue by Samuel-wei** [ultralytics/yolov5#156]
run the command like below:
$ python detect.py
I record the isse
`Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.4, device='', fourcc='mp4v', img_size=640, iou_thres=0.5, output='inference/output', save_txt=False, source='inference/images', view_img=False, weights='weights/yolov5s.pt')
Using CUDA device0 _CudaDeviceProperties(name='Xavier', total_memory=31926MB)

/usr/local/lib/python3.6/dist-packages/torch/serialization.py:453: SourceChangeWarning: source code of class 'torch.nn.modules.container.Sequential' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/lib/python3.6/dist-packages/torch/serialization.py:453: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/lib/python3.6/dist-packages/torch/serialization.py:453: SourceChangeWarning: source code of class 'torch.nn.modules.container.ModuleList' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Traceback (most recent call last):
  File "detect.py", line 156, in <module>
    detect()
  File "detect.py", line 52, in detect
    _ = model(img.half() if half else img) if device.type != 'cpu' else None  # run once
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yolov5/models/yolo.py", line 91, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/home/yolov5/models/yolo.py", line 108, in forward_once
    x = m(x)  # run
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yolov5/models/yolo.py", line 35, in forward
    y[..., 0:2] = (y[..., 0:2] * 2. - 0.5 + self.grid[i].to(x[i].device)) * self.stride[i]  # xy
RuntimeError: expected device cuda:0 and dtype Float but got device cuda:0 and dtype Half`

who can help me?
thanks

**Comment by Lornatang** [comment]
@Samuel-wei 
change `_ = model(img.half() if half else img) if device.type != 'cpu' else None # run once` to `_ = model(img.half() if half else img.float()) if device.type != 'cpu' else None # run once` in `File "detect.py", line 52, in detect`

**Comment by Samuel-wei** [comment]
> @Samuel-wei
> change `_ = model(img.half() if half else img) if device.type != 'cpu' else None # run once` to `_ = model(img.half() if half else img.float()) if device.type != 'cpu' else None # run once` in `File "detect.py", line 52, in detect`

thank you, I use your methods,but I can't solutions my issues.

**Comment by job2003** [comment]
@Lornatang  I change img to img.float(), but not works.

**Comment by glenn-jocher** [comment]
@job2003 @Samuel-wei your error is not reproducible. If you can reproduce this in a working environment, please let us know, otherwise this issue is non-actionable.
https://github.com/ultralytics/yolov5#reproduce-our-environment

**Comment by glenn-jocher** [comment]
## Reproduce Our Environment

To access an up-to-date working environment (with all dependencies including CUDA/CUDNN, Python and PyTorch preinstalled), consider a:

- **GCP** Deep Learning VM with $300 free credit offer: See our [GCP Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/GCP-Quickstart) 
- **Google Colab Notebook** with 12 hours of free GPU time. <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/Docker-Quickstart)
