### ISSUE TITLE
How to get FPS_speed in your code? Thank you. Your code is really helpful to me.

### ISSUE THREAD

**Issue by cmh707122660** [ultralytics/yolov5#1565]

**Comment by cmh707122660** [comment]
Sorry for that stupid question，I know how to calculate it now.

**Comment by Bangbanggetnithecar** [comment]
> Sorry for that stupid question，I know how to calculate it now.

The author did not change the FPS result when the new version was released, I was confused when I coundn't get FPS with the reciprocal value of speed gpu at first.

**Comment by glenn-jocher** [comment]
@cmh707122660 @Bangbanggetnithecar directions to reproduce speed numbers are displayed directly below the speed table.
