### ISSUE TITLE
Out of memory issue with latest git pull

### ISSUE THREAD

**Issue by Rollson** [ultralytics/yolov5#1567]
## ❔Question
Hi, thank you for your good work. I pulled the latest version from github but i am experiencing out of memory issues.

RuntimeError: CUDA out of memory. Tried to allocate 34.00 MiB (GPU 0; 5.93 GiB total capacity; 4.98 GiB already allocated; 33.94 MiB free; 5.03 GiB reserved in total by PyTorch)

I experience this issue after pulling for latest changes

My GPU is GeForce GTX 1060 6GB, OS-Ubuntu.
i also reduced the batch-size to 2 but the out of memory issue still persist.

Please what should i do?
Thank you

**Comment by glenn-jocher** [comment]
Reduce batch size
Reduce image size
Reduce model size
Use a larger GPU
