### ISSUE TITLE
error shape

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#157]
## 🐛 Bug

different shape  in detect.py   why

line 54           _ = model(img.half() if half else img) if device.type != 'cpu' else None  # run once

line 64         pred = model(img, augment=opt.augment)[0]

## To Reproduce (REQUIRED)

Input:
```
python detect.py --source inference/images/49_Greeting_peoplegreeting_49_59.jpg 


Output:
```
torch.Size([1, 10647, 85]) 

image 1/1 inference/images/49_Greeting_peoplegreeting_49_59.jpg: torch.Size([1, 7371, 85])

**Comment by alicera** [comment]
image 1/1 inference/images/49_Greeting_peoplegreeting_49_59.jpg: torch.Size([1, 7371, 85])

how to get the 7371 of Size([1, 7371, 85]) for the yolo

**Comment by alicera** [comment]
I got it ,
another q
 why  the onnx model is 3 outputs
but  the .pt model is 1 output

**Comment by glenn-jocher** [comment]
@alicera these are not bugs. Do not use the bug label for questions.
