### ISSUE TITLE
How to count "unique" objects

### ISSUE THREAD

**Issue by hrvojej** [ultralytics/yolov5#1570]
## ❔ 

I'm using DeepSort-Yolov5 implementation from [here](https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch) for object tracking which works ok.

Idea is to count object passing "close" to camera. For example let's say I want to detect only objects 5 meters from camera. 

I want to skip detections altogether if size of object is less than something defined. Please just point me in places in code where this is controlled.

Thank you for your great work!

**Comment by glenn-jocher** [comment]
@hrvojej box coordinates are available in detect.py here:
https://github.com/ultralytics/yolov5/blob/577f298d9b1a0e3874f685f54d641ac09a3cad3d/detect.py#L101-L108

**Comment by hrvojej** [comment]
Great, thank you Glenn!

**Comment by glenn-jocher** [comment]
@MilesJoseph @AyushExel 👋 Hello! Thanks for asking about object **tracking** in computer vision. YOLOv5 🚀 is an object **detector** that detect, localizes and classifies objects in a single image. It does not connect objects across multiple images, for this you need a tracking solution. A few possible tracking solutions are:

- [Extended Kalman Filter (EKF)](https://en.wikipedia.org/wiki/Kalman_filter)
- [Kanade-Lukas-Tomasi (KLT) Feature Tracker](https://en.wikipedia.org/wiki/Kanade%E2%80%93Lucas%E2%80%93Tomasi_feature_tracker)
- [YOLOv5 DeepSort Tracker](https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch) 
- [Apple iOS VNTrackObjectRequest](https://developer.apple.com/documentation/vision/tracking_multiple_objects_or_rectangles_in_video)

Good luck 🍀 and let us know if you have any other questions!
