### ISSUE TITLE
dataloader workers

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#1574]
When I train the yolo ,it will see the message.  
 "Using 1 dataloader workers" , how to set the number of the dataloader workers, and how to define it.

Analyzing anchors... anchors/target = 5.92, Best Possible Recall (BPR) = 0.9999
Image sizes 640 train, 640 test
Using 1 dataloader workers
Logging results to runs/exp6
Starting training for 300 epochs...

**Comment by glenn-jocher** [comment]
@alicera please read the argparser of each file to see settable arguments:
https://github.com/ultralytics/yolov5/blob/577f298d9b1a0e3874f685f54d641ac09a3cad3d/train.py#L413-L442

**Comment by alicera** [comment]
parser.add_argument('--workers', type=int, default=8, help='maximum number of dataloader workers') 
the workers correspond to the cpu core?
like, 4 workers  correspond to  4 core

**Comment by glenn-jocher** [comment]
1 worker uses 1 python thread I believe.
