### ISSUE TITLE
How to interpret VNCoreMLFeatureValueObservation to get bounding boxes

### ISSUE THREAD

**Issue by maidmehic** [ultralytics/yolov5#1575]
## ❔Question
Hi everyone,

I've been struggling for days now trying to interpret yolov5s Vision request output that is an array of `VNCoreMLFeatureValueObservation`. Every element of this array contains its `MLMultiArray`, so the results are three MLMultiArrays below:
```
Float32 1 × 3 × 52 × 52 × 85
Float32 1 × 3 × 26 × 26 × 85
Float32 1 × 3 × 13 × 13 × 85
```

I've found this solution that takes the first multiarray as coordinates and the second one as confidence, but that doesn't seem to give expected results: https://apple.github.io/turicreate/docs/userguide/object_detection/export-coreml.html

Also, Apple documentation says that Vision output for the object detection should be `VNRecognizedObjectObservation`, but there is no way to convert yolo5 model to CoreML that would give us this type of output. 

Any comment would be immensely helpful.
Thanks!

**Comment by gomer-noah** [comment]
@maidmehic I had this same question and looking through the posted issues it is very common. [This](https://github.com/ultralytics/yolov5/issues/343#issuecomment-658021043) comment describes what is going on much better than I could. Long story short, the way the current CoreML export function works it skips the conversion of some of the detect layers which transform the raw output to bounding boxes, confidences, etc. So if you want to use the CoreML model you have to do the post-processing (anchor boxes offset correction, NMS, etc.) yourself.
