### ISSUE TITLE
about VOC dataset mAP

### ISSUE THREAD

**Issue by yinyuhangi** [ultralytics/yolov5#1578]
## ❔Question
Hello, is there any mAP and FPS evaluation index of YoloV5s on VOC dataset?

**Comment by glenn-jocher** [comment]
Sure. VOC trains to around 0.90 mAP with YOLOv5, depending on the model.

<img width="549" alt="Screenshot 2020-12-02 at 14 00 53" src="https://user-images.githubusercontent.com/26833433/100875831-d2c0d380-34a6-11eb-9b7a-b04338dbfc24.png">

W&B results:
https://wandb.ai/glenn-jocher/VOC

**Comment by glenn-jocher** [comment]
To reproduce yourself:

```
train.py --batch 64 --weights yolov5s.pt --data voc.yaml --epochs 50 --cache --img 512 --nosave --hyp hyp.finetune.yaml --project VOC --name yolov5s
```

**Comment by yinyuhangi** [comment]
Thank you. What about FPS? And is this all done on a V100 GPU? 
I made a small improvement on Yolov5s and I wanted to compare the results. So looking forward to your reply!

**Comment by yinyuhangi** [comment]
@glenn-jocher Thank you. What about FPS? And is this all done on a V100 GPU?
Can you test the FPS on the VOC dataset?
I made a small improvement on Yolov5s and I wanted to compare the results. 
Looking forward to your reply!

**Comment by developer0hye** [comment]
@glenn-jocher 
Hi jocher,

What command did you use for yolov5m6 model?

**Comment by glenn-jocher** [comment]
@developer0hye VOC mAP is actually higher now than when this issue was originally posted. hyp.VOC.yaml contains evolved hyperparameters and the command used to produce them:

https://github.com/ultralytics/yolov5/blob/63ddb6f0d06f6309aa42bababd08c859197a27af/data/hyps/hyp.VOC.yaml#L1-L11

EDIT: to use these hyps and get the best VOC training results (smaller batch sizes are also ok, i.e. 64, 32, 16):
```bash
python train.py --batch 128 --weights yolov5m6.pt --data VOC.yaml --epochs 50 --img 512 --hyp hyp.VOC.yaml
```

**Comment by developer0hye** [comment]
@glenn-jocher Thanks! Yolov5 is very amazing!

**Comment by glenn-jocher** [comment]
@developer0hye also note the VOC hyps are evolved on YOLOv5m6 but can be safely used for all models on VOC
