### ISSUE TITLE
Unable to generate test results without labels

### ISSUE THREAD

**Issue by qianyutham** [ultralytics/yolov5#158]
Hello,

I have trained a custom dataset and am trying to create a JSON file to save the predictions of a test dataset. I have ran the following line of code:

`!python test.py --weights weights/20Junebest.pt --data data/custom_data.yaml --img 416 --save-json --conf 0.35 --task test`

But it is giving me an AssertionError (shown below) that no  labels were found in the test dataset. I am doing a "blind test" on the test dataset where no labels are provided. Could you help me out please? Many thanks in advance!

`Traceback (most recent call last):
  File "test.py", line 275, in <module>
    opt.verbose)
  File "test.py", line 75, in test
    pad=0.5)  # padding
  File "/content/drive/.shortcut-targets-by-id/1wIBTh-Zu1ojKVqbCltOCNlIMXYeh-hx7/CV/yolov5/utils/datasets.py", line 404, in __init__
    assert nf > 0 or n == 20288, 'No labels found in %s. See %s' % (os.path.dirname(file) + os.sep, help_url)
AssertionError: No labels found in data/test/. See https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data`

**Comment by glenn-jocher** [comment]
@qianyutham I don't even know what to say. The entire point of testing to see how accurately you can predict your labels.

If you have no labels, don't test.

**Comment by acebot712** [comment]
> @qianyutham I don't even know what to say. The entire point of testing to see how accurately you can predict your labels.
> 
> If you have no labels, don't test.



What he means to say is that he is using data without labels to just run inference on it. However, he is not using `detect.py` for that as he also wants to save the detections in JSON format. And `--save-json` is only available in `test.py`. So how to go about it?

**Comment by glenn-jocher** [comment]
@acebot712 we don't have a workflow designed to produce json annotations on unlabelled data, but good luck.

**Comment by glenn-jocher** [comment]
@acebot712 @qianyutham perhaps a YOLO to JSON label export function might be useful. The YOLO labels need access to the images as they are normalized though which is a constraint.

**Comment by acebot712** [comment]
@qianyutham A possible workaround I did to solve your problem would be to create a dummy labels folder and put blank dummy annotations files for all images in the test images folder. The following code snippet accomplishes that.

```python
import shutil,os
#replace with paths relevant to you
source_folder = "coco/images/val2017/"
destination_folder = "coco/labels/val2017/"

extension = ".jpg"
for (dir,subdirs,files) in os.walk(source_folder):
  for file in files:
    # absolute folder paths stored
    source_absolute = os.path.join(source_folder,file)
    destination_absolute = os.path.join(destination_folder,file)

    # copy all images to labels folder
    shutil.copy(source_absolute,destination_absolute)

    # rename them to make txt files
    filename, ext = os.path.splitext(file)
    destination_absolute_new = os.path.join(destination_folder,filename) + ".txt"
    os.rename(destination_absolute,destination_absolute_new)
    open(destination_absolute_new,'w').close()
````

Then you could run `test.py` as usual with the command:-
```
!python test.py --weights "path_to_best.pt" --img 416 --conf 0.4 --data ../data.yaml --task test --save-json
```

**Comment by qianyutham** [comment]
@acebot712 Thanks so much for all your help! Greatly appreciate it.
