### ISSUE TITLE
Is there an API to use within a program?

### ISSUE THREAD

**Issue by waylandc** [ultralytics/yolov5#1581]
## ❔Question
Every example I see is running train.py and detect.py from CLI.

Is there a way to use yolov5 from within my program? 

For example, if I've trained my model to detect properly. I want to write a program to use something like Pillow to grab/open an image and run detect on it and get the results so I can proceed with my program.

**Comment by glenn-jocher** [comment]
@waylandc see PyTorch Hub tutorial in README https://docs.ultralytics.com/yolov5

**Comment by waylandc** [comment]
Thanks, that looks like what I was looking for
