### ISSUE TITLE
training Yolo v5s for image size 320 give low mAP

### ISSUE THREAD

**Issue by ofrimasad** [ultralytics/yolov5#1586]
## ❔Question
Hi.
I have ran the training for images with size 320
`python train.py --data coco.yaml --cfg yolov5s.yaml --weights '' --batch-size 64 --img-size 320`
and I am getting a mAP 0.5-0.95 value lower than the 30% reported on your results graph.
![image](https://user-images.githubusercontent.com/4509334/100981593-aca33e00-354f-11eb-93ef-96f1ecea6aac.png)

Are there any flags or features I should turn on/off? 
Any additional settings I should define?

Thanks

**Comment by glenn-jocher** [comment]
@ofrimasad all of the models in the plot are trained using default settings. 320 image size training is definitely not a default setting, so you should not expect to obtain the plot results.

**Comment by ofrimasad** [comment]
I see. thank you very much for the fast response.
Aren't the 6 points along each plot different image sizes?
I thought the lowest point on the blue plot was Yolo v5s 320

**Comment by glenn-jocher** [comment]
@ofrimasad this plot is reproducible by:
```bash
python test.py --task study
```
https://github.com/ultralytics/yolov5/blob/f0101475788590720a3a4b1152a89d531f311dff/test.py#L321-L333

**Comment by ofrimasad** [comment]
ok.... I understand now.
So this point is the result of testing with image size 320 on the pertained  yolov5s.pt (which was probably trained with multi-scale)

thanks

**Comment by glenn-jocher** [comment]
All models are trained with all default settings. All results are reproducible.

<img width="1387" alt="Screenshot 2020-12-03 at 11 26 55" src="https://user-images.githubusercontent.com/26833433/100997376-77e8b400-355a-11eb-952a-c53eb6e1539c.png">
