### ISSUE TITLE
dataset limit

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#1589]
## ❔Question
1.Do you know the limit number of training dataset for yolov5 training?
2. Should I control how many number of training dataset for yolov5 training?
 
Above, I want to know the number of training data that is good for training.
Do you have any suggestions?
thanks you

**Comment by alicera** [comment]
Hi,github-actions  Thanks for your advice

**Comment by sezer-muhammed** [comment]
I think there is no limit for amount of the data
but your ssd or hdd may limits you

**Comment by glenn-jocher** [comment]
There is no limit on dataset sizes, and no negative effect of using ever larger datasets.

**Comment by alicera** [comment]
I train the two class  (face and mask), and I try to test the video. Sometime, for different face angle, it will be face or mask.
How to strong the detection? Do you have any idea? Thk

**Comment by sezer-muhammed** [comment]
> I train the two class (face and mask), and I try to test the video. Sometime, for different face angle, it will be face or mask.
> How to strong the detection? Do you have any idea? Thk

yolov5 is sooooooo good
