### ISSUE TITLE
When will YOLOv5 publish the paper

### ISSUE THREAD

**Issue by Alex866850** [ultralytics/yolov5#1590]
Dear Author:
The YOLOv5 released by your team is too powerful. Many of my works are based on YOLOv5. I would like to ask, when will v5 publish the paper, I can’t wait to appreciate this wonderful work.

**Comment by Alex866850** [comment]
Dear Author:
The YOLOv5 released by your team is too powerful. Many of my works are based on YOLOv5. I would like to ask, when will v5 publish the paper, I can’t wait to appreciate this wonderful work.

**Comment by glenn-jocher** [comment]
@cxr12345 hi thanks for asking! We aim to publish a short paper to arxiv soon. In the meantime please see https://doi.org/10.5281/zenodo.3908559 for DOI to cite this repo directory, and where you can also find bibtex and other exportable citation formats.

[![DOI](https://zenodo.org/badge/264818686.svg)](https://zenodo.org/badge/latestdoi/264818686)
