### ISSUE TITLE
High mAP but low confidence 

### ISSUE THREAD

**Issue by CPor99** [ultralytics/yolov5#1591]
Hi so as the title is stating, I trained a custom dataset with 5000+ images divided into 5 classes. The mAP resulted in 0.95 when the dataset is trained but when exploring using the detect.py I realised that it is giving me mixed confidence on the objects for example on one class 0.30, on another class 0.70. Is it because maybe I'm training the model for only 100 epochs?

**Comment by hcakmak7** [comment]
You should train your model with min. 300 epoch

**Comment by CPor99** [comment]
Thanks @hcakmak7, how did you come up with this conclusion?

**Comment by glenn-jocher** [comment]
@CPor99 default settings indicate 300 epochs, the question instead is why you would train anything less.
