### ISSUE TITLE
Hello I trained my model with a custom dataset. But now how can I convert .pt to .weight

### ISSUE THREAD

**Issue by WANGCHAO1996** [ultralytics/yolov5#1594]
## Additional context
Hello I trained my model with a custom dataset Single category yolov3. But now how can I convert pt to weights

**Comment by TW0521** [comment]
你解决了嘛？我也想要转换为weight

**Comment by WANGCHAO1996** [comment]
> 
> 
> 你解决了嘛？我也想要转换为weight

去下载u版本YOLOv3有两个版本 需要用archive版本训练才能转换模型
