### ISSUE TITLE
output

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#160]
why the onnx model is 3 outputs
but the .pt model is 1 output

**Comment by sim-kelly** [comment]
Having the same issue here - my outputs do not make any sense
![image](https://user-images.githubusercontent.com/28448427/94716333-af4da100-031c-11eb-97dd-c309825d9ce1.png)

**Comment by glenn-jocher** [comment]
@sim-kelly @alicera these are standard yolo output grids, one per object size. See https://arxiv.org/abs/1804.02767
