### ISSUE TITLE
Anchor boxes vs image sizes

### ISSUE THREAD

**Issue by abhiagwl4262** [ultralytics/yolov5#1600]
## ❔Question
@glenn-jocher 
As we are using absolute values of width and height to define anchor boxes, shouldn't these anchors be changing when we choose different sizes for our input?

**Comment by glenn-jocher** [comment]
@abhiagwl4262 anchor boxes are absolute values, they are not a function of image size.

**Comment by glenn-jocher** [comment]
@abhiagwl4262 if you train at different dimensions, autoanchor will recompute anchors as necessary. No action is required on your part.

**Comment by abhiagwl4262** [comment]
@glenn-jocher, I understand that no coding will be required from my side to handle that in yolov5, But I am asking about the dependence of anchor boxes vs image sizes. these are proportional to each other ?

**Comment by glenn-jocher** [comment]
@abhiagwl4262 autoanchor evaluates and evolves new anchors if necessary based on a variety of factors, including your dataset, augmentation policy and training arguments like --img-size.

**Comment by abhiagwl4262** [comment]
@glenn-jocher The anchors written in **models/yolov5l.yaml** are for which image size?

**Comment by glenn-jocher** [comment]
@abhiagwl4262 default image size. See train.py argparser for defaults.

**Comment by abhiagwl4262** [comment]
@glenn-jocher 

When I am running the code with  following anchors, It is working fine. 
        - [10,13, 16,30, 33,23]  # P3/8
        - [30,61, 62,45, 59,119]  # P4/16
        - [116,90, 156,198, 373,326]  # P5/32

BUT with these anchors it is giving me runtime error. 
        - [16.50029451,22.14040388, 18.91975319,44.96244468, 31.99475061,34.56197343]              
        - [47.62996923,59.15185718, 116.19496863,93.09935385, 81.33333349,233.47319635]          
        - [148.88888995,200.27972539, 129.16666508,611.18880272, 185.2777799,592.26107279]    
        
tobj[img_ids, anchor_ids, grid_j, grid_i] = giou.detach().clamp(0).type(tobj.dtype)  # giou ratio
RuntimeError: CUDA error: device-side assert triggered
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program

**I hope the dimensions I am using for anchors are supported**
