### ISSUE TITLE
Low confidence score despite accurate bbox and correct prediction 

### ISSUE THREAD

**Issue by maryamag85** [ultralytics/yolov5#1602]
## ❔Question
I am applying default pretrained yolov5 model in a data to have a simple object detection. I use defult coco classes and do not change any parameters configuration and yet I get Low confidence score despite accurate bbox and correct prediction. Confidence threshod = 0.45 and IOU = .5 and scores are < 0.6

**Comment by glenn-jocher** [comment]
@maryamag85 you should train until your validation losses begin to overfit. Judging by your above description, this has not happened in your case.

**Comment by maryamag85** [comment]
I am not training the model or fine-tuning on a specific dataset. I am trying to use the model as it is. Do I still need to do training?

**Comment by glenn-jocher** [comment]
If you are using official models then there is no action to take. Confidences displayed are accurate.
