### ISSUE TITLE
Detection on Raspberry Pi Camera

### ISSUE THREAD

**Issue by murthax** [ultralytics/yolov5#1604]
## ❔Can I Run Yolov5 against a Pi cam?

I have cloned and installed requirements and I'm able to run detection against a model with my webcam. When I try and use my csi camera I get errors. Curious if there is something I should look into to get this working.

This is on a Jetson Xavier NX.

Here are some results:

~/yolov5$ v4l2-ctl --list-devices
vi-output, imx219 10-0010 (platform:15c10000.vi:2):
	/dev/video0
C922 Pro Stream Webcam (usb-3610000.xhci-2.4):
	/dev/video1

~/yolov5$ python3 detect.py --source 1
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.25, device='', exist_ok=False, img_size=640, iou_thres=0.45, name='exp', project='runs/detect', save_conf=False, save_txt=False, source='1', update=False, view_img=False, weights='yolov5s.pt')
Using torch 1.7.0 CUDA:0 (Xavier, 7771MB)

Fusing layers... 
Model Summary: 232 layers, 7459581 parameters, 0 gradients
1/1: 1...  success (640x480 at 30.00 FPS).

----
~/yolov5$ python3 detect.py --source 0
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.25, device='', exist_ok=False, img_size=640, iou_thres=0.45, name='exp', project='runs/detect', save_conf=False, save_txt=False, source='0', update=False, view_img=False, weights='yolov5s.pt')
Using torch 1.7.0 CUDA:0 (Xavier, 7771MB)

Fusing layers... 
Model Summary: 232 layers, 7459581 parameters, 0 gradients
VIDEOIO ERROR: V4L: Unable to get camera FPS
1/1: 0...  success (3264x2464 at 99.00 FPS).

Whoa!  I could def be doing something wrong. It returns a huge window which is solid green.

Any thoughts are appreciated.

**Comment by MiroslavDirk** [comment]
> ## ❔Can I Run Yolov5 against a Pi cam?
> I have cloned and installed requirements and I'm able to run detection against a model with my webcam. When I try and use my csi camera I get errors. Curious if there is something I should look into to get this working.
> 
> This is on a Jetson Xavier NX.
> 
> Here are some results:
> 
> ~/yolov5$ v4l2-ctl --list-devices
> vi-output, imx219 10-0010 (platform:15c10000.vi:2):
> /dev/video0
> C922 Pro Stream Webcam (usb-3610000.xhci-2.4):
> /dev/video1
> 
> ~/yolov5$ python3 detect.py --source 1
> Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.25, device='', exist_ok=False, img_size=640, iou_thres=0.45, name='exp', project='runs/detect', save_conf=False, save_txt=False, source='1', update=False, view_img=False, weights='yolov5s.pt')
> Using torch 1.7.0 CUDA:0 (Xavier, 7771MB)
> 
> Fusing layers...
> Model Summary: 232 layers, 7459581 parameters, 0 gradients
> 1/1: 1... success (640x480 at 30.00 FPS).
> 
> ~/yolov5$ python3 detect.py --source 0
> Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.25, device='', exist_ok=False, img_size=640, iou_thres=0.45, name='exp', project='runs/detect', save_conf=False, save_txt=False, source='0', update=False, view_img=False, weights='yolov5s.pt')
> Using torch 1.7.0 CUDA:0 (Xavier, 7771MB)
> 
> Fusing layers...
> Model Summary: 232 layers, 7459581 parameters, 0 gradients
> VIDEOIO ERROR: V4L: Unable to get camera FPS
> 1/1: 0... success (3264x2464 at 99.00 FPS).
> 
> Whoa! I could def be doing something wrong. It returns a huge window which is solid green.
> 
> Any thoughts are appreciated.

yeah, i have the same question in jetson nano camera

**Comment by e96031413** [comment]
Same problem here, I cannot use CSI camera to detect, however when I use yolov5s.pt and C270 webcam on JetsonNano to detect, I got 7.5 FPS only but when I switch to ultralytics/yolov3 branch with yolov3-tiny.pt, I got 30 FPS with same C270 webcam. It's pretty weird.
