### ISSUE TITLE
resume question

### ISSUE THREAD

**Issue by chongkuiqi** [ultralytics/yolov5#1606]
## ❔Question
I use the command
"""
python -m torch.distributed.launch --nproc_per_node 2 train.py --resume
"""
to resume  my last train?

but i find the code will be stuck at "model = DDP(model, device_ids=[opt.local_rank], output_device=opt.local_rank)".  I use 2 gpus, but when i print the opt.local_rank,  both of them are 0,  but should it  be that one is 0 and the other is 1?  Could  you give me some advices?

Thanks for your help!

**Comment by alicera** [comment]
$ python -m torch.distributed.launch --nproc_per_node 2 train.py --batch-size 64 --data coco.yaml --weights yolov5l.pt

Does the command  resume the yolov5l.pt?

**Comment by chongkuiqi** [comment]
> $ python -m torch.distributed.launch --nproc_per_node 2 train.py --batch-size 64 --data coco.yaml --weights yolov5l.pt
> 
> Does the command resume the yolov5l.pt?

I  think it doesn't, in main() of train.py, there is a line "opt = argparse.Namespace(**yaml.load(f, Loader=yaml.FullLoader))", it will change the opt.local_rank, but in DDP it shouldn't change, and i find the YOLOv5 4.0 has solved the problem, you can try it.
