### ISSUE TITLE
How do I parse inf_out from test.py?

### ISSUE THREAD

**Issue by lanahoffman** [ultralytics/yolov5#1610]
## ❔Question
How do I parse inf_out from test.py?

## Additional context

I'm interested in understanding the test.py, specifically the output of:
`inf_out, train_out = model(img, augment=augment)  # inference and training outputs`

As a small test, I'm running the following command:
```
python test.py \
--weights yolov5s.pt \
--data config.yml \
--batch-size 6 \
--img-size 128 \
--conf-thres 0.2
```

The shape of inf_out is torch.Size([6, 1260, 85]).  The first dimension corresponds to my batch size, but what does the rest mean?  Why are there 1260,85 numbers there and what do they mean?

Thanks!

**Comment by ghost** [comment]
bs, 
predicted bbox, 
cls number + 4 bbox position (x, y, w, h) + 1 conf.

**Comment by lanahoffman** [comment]
Thank you, @Sun-Rider!
