### ISSUE TITLE
Different mAP with yours while running test.py on COCO2017

### ISSUE THREAD

**Issue by zyx792726304** [ultralytics/yolov5#1615]
## ❔Question
![image](https://user-images.githubusercontent.com/49439344/101278550-ec3f8380-37f6-11eb-8aa2-66d274b79a8a.png)
I run python test.py --data coco.yaml --img 640 --conf 0.001 --iou 0.65,but I got different result with yours.Here is your result:
![image](https://user-images.githubusercontent.com/49439344/101278575-15f8aa80-37f7-11eb-91f7-c5af6866677c.png)
Here is my result:
![image](https://user-images.githubusercontent.com/49439344/101278583-2a3ca780-37f7-11eb-88b4-27414af32000.png)

Is there something wrong with my setting?What should I do to reproduce your result?

**Comment by glenn-jocher** [comment]
@zyx792726304 install pycocotools for official mAP results, then test.
`pip install pycocotools`

**Comment by glenn-jocher** [comment]
You can see a good example of this in the colab notebook. Unfortunately our repo mAP always reports slightly less than the pycocotools mAP, and I'm not quite sure why.

<img width="1623" alt="Screenshot 2020-12-06 at 14 16 28" src="https://user-images.githubusercontent.com/26833433/101281136-bdf97e00-37cd-11eb-9769-105f9bb9242b.png">
