### ISSUE TITLE
why all the "image_id"s of "yolov5s_predictions.json" are the same ID?   "yolov5s_predictions.json" is the prediction of yolov5s ,which is in the task of "test" on the dev-test2017. 

### ISSUE THREAD

**Issue by Jackyinuo** [ultralytics/yolov5#1618]
Before submitting a bug report, please be aware that your issue **must be reproducible** with all of the following, otherwise it is non-actionable, and we can not help you:
 - **Current repo**: run `git fetch && git status -uno` to check and `git pull` to update repo
 - **Common dataset**: coco.yaml or coco128.yaml
 - **Common environment**: Colab, Google Cloud, or Docker image. See https://github.com/ultralytics/yolov5#environments
 
If this is a custom dataset/training question you **must include** your `train*.jpg`, `test*.jpg` and `results.png` figures, or we can not help you. You can generate these with `utils.plot_results()`.

## To Reproduce (REQUIRED)

Input:
```
import torch

a = torch.tensor([5])
c = a / 0
```

Output:
```
Traceback (most recent call last):
  File "/Users/glennjocher/opt/anaconda3/envs/env1/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-be04c762b799>", line 5, in <module>
    c = a / 0
RuntimeError: ZeroDivisionError
```

## Environment

 - OS: [e.g. Ubuntu]
 - GPU [e.g. 2080 Ti]

**Comment by glenn-jocher** [comment]
@Jackyinuo image_id is set here for each detection. These are only utilized if your dataset is COCO.
https://github.com/ultralytics/yolov5/blob/791dadb51c7da5641a4841eb8a5f319bbc24982b/test.py#L159-L162

**Comment by Jackyinuo** [comment]
Thank you for your reply. This is caused by a small mistake.@
