### ISSUE TITLE
Converting model including NMS to ONNX

### ISSUE THREAD

**Issue by edwardnguyen1705** [ultralytics/yolov5#1624]
Dear @glenn-jocher ,

Have you ever converted a full model either including NMS or all (NMS, autoshape) to ONNX successfully?

**Comment by zhiqwang** [comment]
Current autoshape use OpenCV resize function, so it has difficultly to conclude it to the ONNX model (I guess). torchvision has a similar funciton named [`GeneralizedRCNNTransform`](https://github.com/pytorch/vision/blob/d3d393672b877f80fedd2d11de6b84fb19599c2e/torchvision/models/detection/transform.py#L58). Replace it to `GeneralizedRCNNTransform`  should make sense to export `yolov5` to a full model. I have made some experiments in [my own repo](https://github.com/zhiqwang/yolov5-rt-stack), and [here](https://github.com/zhiqwang/yolov5-rt-stack/blob/master/notebooks/export-onnx-inference-onnxruntime.ipynb) is a working jupyter notebook.

And If we replace opencv function to `GeneralizedRCNNTransform` (which key ops is `torch.nn.functional.interpolate` comparing to OpenCV's `cv2.resize`), there maybe some numerical difference for using different interpolation mode.

Point it out if I'm wrong here.

BTW, NMS in this repo should be exported successfully now.

**Comment by glenn-jocher** [comment]
@zhiqwang autoshape() models can accept PIL, cv2, and numpy inputs, or any combination of the above in a list. Some examples are:
https://github.com/ultralytics/yolov5/blob/68e6ab668b30a6014215b94e399151f8c76e471a/models/common.py#L131-L138
