### ISSUE TITLE
UnboundLocalError: local variable 'half' referenced before assignment

### ISSUE THREAD

**Issue by tudoupaigu946** [ultralytics/yolov5#163]
error:
Reading image shapes: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 32860/32860 [00:01<00:00, 17261.58it/s]
Caching labels /data/test/yolov5/voc/labels.npy (32789 found, 0 missing, 71 empty, 0 duplicate, for 32860 images): 100%|█████████████████████████████| 32860/32860 [00:02<00:00, 13888.24it/s]
Saving labels to /data/test/yolov5/voc/labels.npy for faster future loading
Caching labels /data/test/yolov5/voc/labels.npy (3644 found, 0 missing, 7 empty, 0 duplicate, for 3651 images): 100%|██████████████████████████████████| 3651/3651 [00:00<00:00, 13830.62it/s]
Saving labels to /data/test/yolov5/voc/labels.npy for faster future loading
Label width-height:         n      mean       min       max  matching    recall
                    4.204e+04     196.4        12       825    0.4615    0.9999
Image sizes 640 train, 640 test
Using 8 dataloader workers
Starting training for 100 epochs...

     Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
      0/99     9.78G    0.0384   0.02523   0.07062    0.1343         8       640: 100%|███████████████████████████████████████████████████████████████████| 4108/4108 [30:23<00:00,  2.25it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95:   0%|                                                                   | 0/457 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 402, in <module>
    train(hyp)
  File "train.py", line 308, in train
    fast=ni < n_burn)
  File "/data/test/yolov5/test.py", line 89, in test
    img = img.half() if half else img.float()  # uint8 to fp16/32
UnboundLocalError: local variable 'half' referenced before assignment

command:
python train.py --data data/41.yaml --cfg models/yolov5x_my.yaml --weights weights/yolov5x.pt --batch-size 8 --epochs 100
environment:
V100,cuda10.1

**Comment by glenn-jocher** [comment]
@jy1023408440 thanks for the bug report, but unless this issue is reproducible on a common dataset in a common environment (colab, docker), there is nothing for us to do. If you can reproduce this with the above conditions please let us know.
