### ISSUE TITLE
Why diffrent colors of bboxs?

### ISSUE THREAD

**Issue by TommyZihao** [ultralytics/yolov5#1638]
When I run detect.py several times, there are different colors of bounding box but of the same object.
How can I configure the colors of the specific class bounding box?
For example, red for people bbox, green for car bbox.
Thank you !

**Comment by zhiqwang** [comment]
Checkout this line to determine colors of objects.

https://github.com/ultralytics/yolov5/blob/68e6ab668b30a6014215b94e399151f8c76e471a/detect.py#L56

**Comment by TommyZihao** [comment]
> Checkout this line to determine colors of objects.
> 
> https://github.com/ultralytics/yolov5/blob/68e6ab668b30a6014215b94e399151f8c76e471a/detect.py#L56

Thank you so much, I figure it out.
