### ISSUE TITLE
Training the yolov5 on coco from scratch?

### ISSUE THREAD

**Issue by qih96** [ultralytics/yolov5#164]
i don't see the function that load weight just for backbone network. yolov5 is trained from scratch?

**Comment by glenn-jocher** [comment]
@qih96 yes. All yolov5 models are trained from scratch.

**Comment by qih96** [comment]
@glenn-jocher Thanks for your reply, i will close the issue.

**Comment by qih96** [comment]
@glenn-jocher Can you upload the training log file for the latest models ?  thank you very much

**Comment by glenn-jocher** [comment]
results.txt files for the official weights are in the Google Drive folder:
https://drive.google.com/drive/u/1/folders/1Drs_Aiu7xx6S-ix95f9kNsA6ueKRpN2J
<img width="1126" alt="Screen Shot 2020-07-08 at 9 29 07 AM" src="https://user-images.githubusercontent.com/26833433/86945123-82af3200-c0fd-11ea-9083-6498326f3f19.png">

**Comment by qih96** [comment]
i see it, but the upload dates of results.txt and models are not match. it seems the txt files are the log of  the previous version models.

**Comment by glenn-jocher** [comment]
@qih96 yes thats possible. These should correspond to the current weights. 
[results226.txt](https://github.com/ultralytics/yolov5/files/4898173/results226.txt)
[results227.txt](https://github.com/ultralytics/yolov5/files/4898174/results227.txt)
[results228.txt](https://github.com/ultralytics/yolov5/files/4898175/results228.txt)
[results235.txt](https://github.com/ultralytics/yolov5/files/4898176/results235.txt)
![results](https://user-images.githubusercontent.com/26833433/87067161-88be1500-c1c8-11ea-9ab9-faae8c0d5efd.png)

**Comment by qih96** [comment]
thank you！
