### ISSUE TITLE
duplicated boxes between classes all with high probabilities

### ISSUE THREAD

**Issue by fanweiya** [ultralytics/yolov5#1648]
Hi, YoloV5 works great with my datasets. Thanks. But sometimes, I encountered duplicated boxed between classes. As shown in the picture.
![image](https://user-images.githubusercontent.com/11371707/101569453-7bbf7f00-3a0f-11eb-9783-aac2161b7c82.png)
Whlie threshodling might help, those 2 boxed are all above the thresholds. How to keep the one with the highest probability or only single label. Thanks again.

**Comment by glenn-jocher** [comment]
@fanweiya you use class-agnostic NMS by setting agnostic=True in the NMS function:
`python detect.py --agnostic-nms`

**Comment by fanweiya** [comment]
> @fanweiya，您可以通过在NMS功能中设置agn​​ostic = True来使用与类无关的NMS：
> `python detect.py --agnostic-nms`
ok,thank you
