### ISSUE TITLE
Convert the label format

### ISSUE THREAD

**Issue by QCHighing** [ultralytics/yolov5#1652]
https://github.com/ultralytics/yolov5/blob/84f9bb5d92dd8ae453df3c712d2092344d29ad90/data/scripts/get_voc.sh#L44-L45

Why does the calculation here need to `-1`?

Many thanks.

**Comment by glenn-jocher** [comment]
@QCHighing this function converts VOC labels into YOLO format. For YOLO format requirements see custom training tutorial:
https://docs.ultralytics.com/yolov5/tutorials/train_custom_data
