### ISSUE TITLE
parameters in test phase

### ISSUE THREAD

**Issue by lidehuihxjz** [ultralytics/yolov5#1654]
There are 4 parameters in test phase, which is  **p, r, ap50** and **ap**. What's the meaning of the **p** and **r**?
Is the **r** means recall? If so, what's the corresponding IoU?
And is the **p** means some kind of precision?

**Comment by glenn-jocher** [comment]
@lidehuihxjz https://en.wikipedia.org/wiki/Precision_and_recall
