### ISSUE TITLE
v3.1 release pretrained model of yolov5s is about 14M? not 7M?

### ISSUE THREAD

**Issue by universewill** [ultralytics/yolov5#1658]
v3.1 release pretrained model of yolov5s is about 14M? not 7M?

**Comment by glenn-jocher** [comment]
@universewill do not use a bug label for questions.

See https://docs.ultralytics.com/yolov5/tutorials/train_custom_data
![image](https://user-images.githubusercontent.com/26833433/101716125-8d297b00-3a51-11eb-8ee9-e6c3f9026bb5.png)
