### ISSUE TITLE
Is there any way to reduce 14M yolov5s model file to 7M?

### ISSUE THREAD

**Issue by universewill** [ultralytics/yolov5#1660]
Is there any way to reduce 14M yolov5s model file to 7M?

**Comment by yuvalgrossman** [comment]
I'm not sure what exactly you mean by reducing size but you can easily adjust the model size using the parameters depth_multiple and width_multiple, in the models/yolov5s.yaml configuration file. 
For example, I generated a new configuration file (and called it yolov5xs.yaml) by simply copying that file and changing the above parameter to:
depth_multiple: 0.2  # model depth multiple
width_multiple: 0.25  # layer channel multiple

The weights are about 3.8 MB

Of course, there is a tradeoff between model complexity (hence size) and performance.

**Comment by glenn-jocher** [comment]
@yuvalgrossman good points! Also the filesize can completely vary based upon quantization. For FP16 quantization filesizes are shown here. At FP8 they are half, at FP4 they are 1/4 etc, again with the caveat emptor warning on reduced accuracy etc.

<img width="1127" alt="97808084-edfcb100-1c64-11eb-83eb-ffed43a0859f" src="https://user-images.githubusercontent.com/26833433/102243440-068cf780-3eb0-11eb-949f-dcc755d987cf.png">

**Comment by saeedadeeb103** [comment]
> 

i mean i did that but when i train i still use Yolov5n.pt, if there is a way i can train on yolov5xs.yaml can u share it pls.

**Comment by glenn-jocher** [comment]
@saeedadeeb103 to train with a custom configuration file, you can use the --cfg flag to specify the model configuration. For example:

```bash
python train.py --cfg models/yolov5xs.yaml --data your_data.yaml --weights '' --batch-size 32 --epochs 300
```

This command trains YOLOv5 model using the yolov5xs.yaml configuration file. Be sure to adjust the other training parameters accordingly. For more detailed information, you can refer to the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/.
