### ISSUE TITLE
Why *2 in flops calculation with using thop.profile ?

### ISSUE THREAD

**Issue by KaiOtter** [ultralytics/yolov5#1664]
## ❔Question
Hi, I'm confused with the following expression which is located in model_info(), in yolov5/utils/torch_utils.py.

- “flops = profile(deepcopy(model), inputs=(img,), verbose=False)[0] / 1E9 * 2  # stride FLOPS” 

Why do you multiply a factor 2 ? I tried to compare the result to the one from torchsummaryX. The experiment is on mobilenetV2 backbone. And, the flops of above expression is near half of flops calculated by torchsummaryX.

Can anyone explain for me? thanks.

**Comment by glenn-jocher** [comment]
Most of modern hardware architectures uses FMA instructions for operations with tensors.
FMA computes a*x+b as one operation. Roughly Multiply Accumulate Operation (MAC)s = 0.5 * FLOPS.
