### ISSUE TITLE
bbox shift in train examples

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#1668]
## ❔Question

I construct label as Tutorial shows:
  - Original Images size is 1080 x 1280
  - Calculate bbox x_center, y_center, width, height.
  - Normalize with 1080 (x_center, width) and  1280(height, y_center)
  - Train My custom dataset with command python train.py --img 640 --weights .....

But when model training, the example train batch images bbox are all shift.

**Comment by glenn-jocher** [comment]
@EvilPsyCHo if train and test jpgs do not show correct labels then your labels are incorrect. See labelling section of custom training tutorial for correct formatting: https://docs.ultralytics.com/yolov5/tutorials/train_custom_data

**Comment by burglarhobbit** [comment]
@glenn-jocher My labels are annotated correctly and display great when plotted manually (x1,y1,w,h), but when I create the normalized dataset using this formula: ```((x1+w)/(2*im_w), (x2+h)/(2*im_h), w/im_w, h/im_h)```, it plots a shifted bbox in train as well as test label. what could be the reason? I face the same issue as the OP.

![image](https://user-images.githubusercontent.com/15987266/102055667-31e0eb00-3db9-11eb-910e-2d3d1be436d1.png)

If I plot the boxes manually, it works like a charm, but not on the custom training set as observed.

Edit: It is resolved. My formula was incorrect.
