### ISSUE TITLE
Grayscale camera usage

### ISSUE THREAD

**Issue by hcakmak7** [ultralytics/yolov5#1670]
## ❔Question
Hello,
I want to know if there are any ways to use yolov5 with grayscale cameras. 

When I try to use it with grayscale camera, i got

```
img = img[:, :, :, ::-1].transpose(0, 3, 1, 2)  # BGR to RGB, to bsx3x416x416
IndexError: too many indices for array: array is 3-dimensional, but 4 were indexed
```
these error.

Thank you

**Comment by glenn-jocher** [comment]
@hcakmak7 cv2 typically loads a grey image as 3-ch (there are grey images in COCO and training proceeds fine). If this is not happening in your case you may want to update the dataloader to accomodate your situation.
