### ISSUE TITLE
Images sizes do not match. This will causes images to be display incorrectly in the UI.

### ISSUE THREAD

**Issue by HerrLieber** [ultralytics/yolov5#1676]
## ❔Question

When I follow the tutorial "Train custom data", I run the following command:

python train.py --img 640 --batch 64 --epochs 5 --data coco128.yaml --weights yolov5s.pt

Two errors then occur:

1:

Analyzing anchors... anchors/target = 4.26, Best Possible Recall (BPR) = 0.9946
Image sizes 640 train, 640 test
Using 0 dataloader workers
Logging results to runs\train\exp14
Starting training for 5 epochs...

     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
  0%|                                                                                            | 0/2 [00:00<?, ?it/s]Images sizes do not match. This will causes images to be display incorrectly in the UI.

2:
Traceback (most recent call last):
  File "traingai.py", line 503, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "traingai.py", line 288, in train
    pred = model(imgs)  # forward
  File "F:\Anaconda\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "F:\github\yolov5\models\yolo.py", line 122, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "F:\github\yolov5\models\yolo.py", line 138, in forward_once
    x = m(x)  # run
  File "F:\Anaconda\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "F:\github\yolov5\models\common.py", line 94, in forward
    return self.conv(torch.cat([x[..., ::2, ::2], x[..., 1::2, ::2], x[..., ::2, 1::2], x[..., 1::2, 1::2]], 1))
  File "F:\Anaconda\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "F:\github\yolov5\models\common.py", line 35, in forward
    return self.act(self.bn(self.conv(x)))
  File "F:\Anaconda\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "F:\Anaconda\lib\site-packages\torch\nn\modules\conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "F:\Anaconda\lib\site-packages\torch\nn\modules\conv.py", line 416, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_ALLOC_FAILED

For the second error, I saw that someone said it was solved by installing torch.version.cuda==10.1, but I still get the second error after installing torch.version.cuda==10.1. At the same time I uninstalled the corresponding cuda software as well as cudnn (i.e. 10.2 as shown by nvcc -V) and installed cuda 10.1 as well as the corresponding cudnn version.

The rest of the environment I have configured to run the command: 

python detect.py --source 0  # webcam
                            file.jpg  # image 
                            file.mp4  # video

Thanks for your help!

**Comment by glenn-jocher** [comment]
@HerrLieber it appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below. 


## Requirements

**Python 3.8** or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including **`torch>=1.7`**. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by isildur7** [comment]
I have the same issue. After the first epoch, I see the message - "Images sizes do not match. This will causes images to be display incorrectly in the UI." The mosaics are totally wrong. My image size is 512x512.
Here is the image I see: 
![image](https://user-images.githubusercontent.com/42990935/107894623-31221d80-6efe-11eb-9548-39ec5b1a22c0.png)

**Comment by glenn-jocher** [comment]
@isildur7 the 'Images sizes do not match. This will causes images to be display incorrectly in the UI.' warning is from matplotlib I believe, and has always been present, with no apparent ill effects that I know of (COCO128 mosaics are correct despite message).

@isildur7 I don't know how you expect your images to appear. I would start by running the Train Custom Data tutorial to validate your training pipeline, and then substituting your own data. You can get started here:

## Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [ONNX and TorchScript Export](https://docs.ultralytics.com/yolov5/tutorials/model_export)
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by isildur7** [comment]
sorry here is more info. I did look at your tutorial and it was most helpful. I ran the following command:
`train.py --img 512 --batch 8 --epochs 10 --data datacfg.yaml --cfg ./models/yolov5m-custom.yaml --weights yolov5m.pt --name wbcv0.1 --cache`
The model trains but it's only the UI that appears to be wonky. I am not sure if the training data being fed is actually what the UI shows and that is my concern. Here are a few examples of actual training data:
![000001](https://user-images.githubusercontent.com/42990935/107979287-52314f80-6f8c-11eb-8b78-43ef08deb3d7.jpg)
![000134](https://user-images.githubusercontent.com/42990935/107979305-58bfc700-6f8c-11eb-82fe-7147498660a9.jpg)

**Comment by glenn-jocher** [comment]
@isildur7 yes the jpgs generated display the training mosaics and labels. If these labels do not appear correct then there is an error in your dataset labels. There are no known issues in the jpgs. You can see examples of them in the tutorial.

If you'd like to modify augmentation hyps you can do this in the default hyperparameter file here:
https://github.com/ultralytics/yolov5/blob/master/data/hyp.scratch.yaml

**Comment by akshat-suwalka** [comment]
@glenn-jocher I am training the model with a dataset which have some image 1920x1200 and some image as 2048x1536 and when I write code for training it will be :- 

!python train.py --img 1200 --batch 16 --epochs 3 --data my_custom.yaml --weights yolov5s.pt --nosave --cache

My question is that since i will definitely get the warning or error as " 'Images sizes do not match. This will causes images to be display incorrectly in the UI."  Does it will impact my model performance?

Same error we are getting when we are using simply (without changing any piece of code) of your Colab code. There also we are getting same error.

In earlier comment you mention that it is matplotlib error. 
Just want to clarify that Is it going to affect my model performace on custom dataset like consider an example where I have all images of same dimension as 1920x1200 then Which model will give better results the one with 1920x1200 OR the one which have some images as 1920x1200 and some images as 2048x1536.

Do I really have to make all images size to be equal so that YOLO V5 will work properly OR Should I ignore the image size error?

**Comment by glenn-jocher** [comment]
@akshat-suwalka Images sizes do not match message is generated by the plotting routines before or after training.

Training is not affected.

**Comment by akshat-suwalka** [comment]
@glenn-jocher Thank you for your response!

**Comment by ys31jp** [comment]
Hi, is this mean that the Images sizes do not match message will not be an issues?

**Comment by glenn-jocher** [comment]
@ys31jp this is just a matplotlib message that sometimes appears when labels.jpg is created, it has no effect on training.

**Comment by glenn-jocher** [comment]
UPDATE: issue re-raised in https://github.com/ultralytics/yolov5/issues/3575, seems to original in W&B, not in matplotlib.
