### ISSUE TITLE
about evaluating small object's mAP

### ISSUE THREAD

**Issue by yinyuhangi** [ultralytics/yolov5#1679]
## ❔Question
Hello, may I ask if I have trained a model using VOC dataset and I want to test only the small object mAP in the model? How can I operate?
Can I use coco's evaluation function to test my model?
Looking forward to your reply.

**Comment by glenn-jocher** [comment]
@yinyuhangi ah, thats a good question. Yes, you can always use pycocotools, the challenge though is that you need an annotations.json for the VOC data, which we don't have available. You may be able to find one online, else you'd need to create your own.

Note that more detail is available in test.py if you use the --verbose flag, but this does not display by size:
`python test.py --verbose`
