### ISSUE TITLE
Why the input of the first conv2d layer is 12?

### ISSUE THREAD

**Issue by RainbowSun11Q2H** [ultralytics/yolov5#168]
Thank you for your nice work.

When I read your code, I have a question about the weight of the first conv2d layer in the first Focus module.
The size of input images is (3, 640, 640). When I set a breakpoint in the yolo.py, the first conv2d layer is Conv2d(12, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False). However, the training process can going on normally. How can you do it? Why is the input 12? Do you have some other operation for the image? 
![image](https://user-images.githubusercontent.com/63624265/85279899-c1b47500-b4b9-11ea-8a78-68c5d683934b.png)

Thank you for your time.

Rainbow

**Comment by yxNONG** [comment]
@RainbowSun11Q2H you can see the detail of focus in models/common.py
there are a transform of shape befort the Conv
the original input splited into 4 part in wh dimension, then cat them in channel dimension
suppose you have input 
[  1    1
   1    1 ]       -------------->           [ 1 ] * 4
in general,  (c, w, h) ---> (4c, w/2, h/2)
so the input is 4 time of the original

**Comment by maykulkarni** [comment]
@yxNONG what's the use of this operation? Is there any literature that I can read about this technique?

**Comment by yxNONG** [comment]
@maykulkarni have no idea where it was mention, 
in my point of view, what the fuse layer do is downsample.
for speed:
instead of conv, it avoid many FLOPs
if you have input [batch , w, h, channel = 3]
a 3x3 conv to downsample to [batch, w/2, h/2, channels = 12]
FLOPs is  about 10*c*w*h

i did not have too much idea about how it affect the mAP

**Comment by maykulkarni** [comment]
@yxNONG thanks, it is answered here: #207
