### ISSUE TITLE
No module named 'models' 

### ISSUE THREAD

**Issue by yao-zheng-yi** [ultralytics/yolov5#1680]
Hi, I try to use yolov5 for my project, I created a new folder has three files: detect.py, models_all.py, utils_all.py and my own weights best.pt, models_all.py include all code in folder models, and utils_all.py also include all code in folder utils. But when I run 
`python detect.py`
and get the error as follows:

`Traceback (most recent call last):
  File "detect.py", line 226, in <module>
    detect()
  File "detect.py", line 40, in detect
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "E:\yolov5\exe\models_all.py", line 367, in attempt_load
    model.append(torch.load(w, map_location=map_location)['model'].float().fuse().eval())  # load FP32 model
  File "C:\Users\cwy\Anaconda3\envs\yolov5\lib\site-packages\torch\serialization.py", line 584, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\cwy\Anaconda3\envs\yolov5\lib\site-packages\torch\serialization.py", line 842, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'models'`

I found that if my folder structure is

---detect.py
---best.pt
     ------models/common.py
     ------models/experimental.py
     ------models/export.py
     ------models/yolo.py

     ------utils/activations.py
     ------utils/dataset.py
     ------utils/general.py
     ------utils/google_utils.py
     ------utils/torch_utils.py
it will work correctly，but if my folder structure is

---detect.py
---best.pt
---models_all.py
---utils.py
it will get error as follow:

`Traceback (most recent call last):
  File "detect.py", line 226, in <module>
    detect()
  File "detect.py", line 40, in detect
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "E:\yolov5\exe\models_all.py", line 367, in attempt_load
    model.append(torch.load(w, map_location=map_location)['model'].float().fuse().eval())  # load FP32 model
  File "C:\Users\cwy\Anaconda3\envs\yolov5\lib\site-packages\torch\serialization.py", line 584, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\cwy\Anaconda3\envs\yolov5\lib\site-packages\torch\serialization.py", line 842, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'models'`

I found the same issue in another repo, but could not solve my problem.
Could you help  me？
@glenn-jocher

**Comment by glenn-jocher** [comment]
@yao-zheng-yi the recommended way of using YOLOv5 independently in other projects is first training a custom model, and then loading it in your project using PyTorch Hub. See PyTorch Hub tutorial for details:
https://docs.ultralytics.com/yolov5

Custom model loading has been simplified now with PyTorch Hub in PR https://github.com/ultralytics/yolov5/pull/1677 🚀

## Custom Models
This example loads a custom 20-class [VOC](https://github.com/ultralytics/yolov5/blob/master/data/voc.yaml)-trained YOLOv5s model `'yolov5s_voc_best.pt'` with PyTorch Hub.
```python
model = torch.hub.load('ultralytics/yolov5', 'custom', path_or_model='yolov5s_voc_best.pt')
model = model.autoshape()  # for PIL/cv2/np inputs and NMS
```

**Comment by yao-zheng-yi** [comment]
@glenn-jocher Thanks for your reply！
I try to load yolov5s.pt by

`# Load model
    # model = attempt_load(weights, map_location=device)  # load FP32 model
    model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True).autoshape()
    imgsz = check_img_size(imgsz, s=model.stride.max())  # check img_size
    if half:
        model.half()  # to FP16`

in detect.py, but I got the error message that say

`Adding autoShape...
Traceback (most recent call last):
  File "detect.py", line 174, in <module>

    detect()

  File "detect.py", line 62, in detect

    _ = model(img.half() if half else img) if device.type != 'cpu' else None  # run once

  File "C:\Users\cwy\Anaconda3\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\yolov5\exe\yolov5\exe\models\common.py", line 141, in forward
    return self.model(imgs.to(p.device).type_as(p), augment, profile)  # inference
  File "C:\Users\cwy\Anaconda3\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\yolov5\exe\yolov5\exe\models\yolo.py", line 122, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "E:\yolov5\exe\yolov5\exe\models\yolo.py", line 138, in forward_once
    x = m(x)  # run
  File "C:\Users\cwy\Anaconda3\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\yolov5\exe\yolov5\exe\models\common.py", line 94, in forward
    return self.conv(torch.cat([x[..., ::2, ::2], x[..., 1::2, ::2], x[..., ::2, 1::2], x[..., 1::2, 1::2]], 1))
  File "C:\Users\cwy\Anaconda3\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\yolov5\exe\yolov5\exe\models\common.py", line 35, in forward
    return self.act(self.bn(self.conv(x)))
  File "C:\Users\cwy\Anaconda3\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\cwy\Anaconda3\envs\yolov5\lib\site-packages\torch\nn\modules\conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "C:\Users\cwy\Anaconda3\envs\yolov5\lib\site-packages\torch\nn\modules\conv.py", line 415, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,

RuntimeError: "unfolded2d_copy" not implemented for 'Half'`

**Comment by gkagkos** [comment]
@yao-zheng-yi hi! I think that this [link](https://github.com/ultralytics/yolov5/issues/353) can help you. As the author of the link explained: **the key of this problem is Pickle needs the same file structure between the calling file and the source file if use the following code to save model**. I was struggling as well with this problem. 

I manage to solve my problem by saving the weights and reload them.

**Comment by yao-zheng-yi** [comment]
@polydefk Hi, thanks for your reply!
I found the solution:
`solution
use sys.path to include the source file. do it like this:

import sys
sys.path.insert(0, './yolov5')`

add the code in detect.py, but I don't konw where to add?

And if my folder structure is
---detect.py
---best.pt
---models_all.py
---utils.py

no yolov5 project, it can also solve my problem?

**Comment by gkagkos** [comment]
Then I suggest the following:
1) load the model on your local yolov5 directory 
2) save the model with something like torch.save(model.state_dict())
3) on your local project load the saved model with something like: torch.load(model.load_state_dict(state_dict, strict=True))
I can't explain it in a simpler way... For me this works.

**Comment by yao-zheng-yi** [comment]
> Then I suggest the following:
> 
> 1. load the model on your local yolov5 directory
> 2. save the model with something like torch.save(model.state_dict())
> 3. on your local project load the saved model with something like: torch.load(model.load_state_dict(state_dict, strict=True))
>    I can't explain it in a simpler way... For me this works.

Thanks! Your apporach didn't work for me, but I have solve it, thank you so much!

**Comment by KevinZhanggg** [comment]
> > Then I suggest the following:
> > 
> > 1. load the model on your local yolov5 directory
> > 2. save the model with something like torch.save(model.state_dict())
> > 3. on your local project load the saved model with something like: torch.load(model.load_state_dict(state_dict, strict=True))
> >    I can't explain it in a simpler way... For me this works.
> 
> Thanks! Your apporach didn't work for me, but I have solve it, thank you so much!

Dude, How you solved it ?

**Comment by burakpols** [comment]
> yolov

You should write the folder name which is your model in it.

**Comment by futureflsl** [comment]
> > Then I suggest the following:
> > 
> > 1. load the model on your local yolov5 directory
> > 2. save the model with something like torch.save(model.state_dict())
> > 3. on your local project load the saved model with something like: torch.load(model.load_state_dict(state_dict, strict=True))
> >    I can't explain it in a simpler way... For me this works.
> 
> Thanks! Your apporach didn't work for me, but I have solve it, thank you so much!

How to solve this problem.I just have the same problem

**Comment by Coding-Rod** [comment]
I got this, code:

```python
!python detect.py --source inference/images/horses.jpg --cfg cfg/yolor_p6.cfg --weights yolor_p6.pt --conf 0.25 --img-size 1280 --device 0 --output /content/drive/MyDrive/Tesis/assets/yolor/
```

OUTPUT:
```shell
Namespace(agnostic_nms=False, augment=False, cfg='cfg/yolor_p6.cfg', classes=None, conf_thres=0.25, device='0', img_size=1280, iou_thres=0.5, names='data/coco.names', output='/content/drive/MyDrive/Tesis/assets/yolor/', save_txt=False, source='inference/images/horses.jpg', update=False, view_img=False, weights=['yolor_p6.pt'])
Traceback (most recent call last):
  File "detect.py", line 186, in <module>
    detect()
  File "detect.py", line 44, in detect
    model.load_state_dict(torch.load(weights[0], map_location=device)['model'])
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 764, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.
```

**Comment by glenn-jocher** [comment]
@Rod5919 your *.pt file is incomplete or corrupted

**Comment by mikatsukons** [comment]
> @Rod5919 your *.pt file is incomplete or corrupted

Traceback (most recent call last):
  File "detect.py", line 186, in <module>
    detect()
  File "detect.py", line 44, in detect
    model.load_state_dict(torch.load(weights[0], map_location=device)['model'])
  File "/home/mkon/miniconda3/envs/conda_env/lib/python3.8/site-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/mkon/miniconda3/envs/conda_env/lib/python3.8/site-packages/torch/serialization.py", line 764, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.

I get the same error. How can we solve it? I just ran scripts/get_pretrained.sh.

**Comment by glenn-jocher** [comment]
@mikatsukons 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
