### ISSUE TITLE
Deploying yolov5 to TorchServe (GPU compatible)

### ISSUE THREAD

**Issue by louisoutin** [ultralytics/yolov5#1681]
## 🚀 Feature

- Enable yolov5 deployment to torchserve on docker (GPU compatible).
- Use a fixed batch_size (fill with 0 for fast inference if the batch is not full)

## Motivation

I wanted to use YOLOv5 for my personal projects, using a GPU with fixed batch inference (multiple videos in concurrences),
and TorchServe seemed to be the best option. For this reason, I wanted to share this with the community, as I had some issues in settings things up (especially the handler file).

## Pitch

Just sharing things :)

You can check this feature on this github repository:
https://github.com/louisoutin/yolov5_torchserve

Any feedbacks are welcome, thanks!

**Comment by glenn-jocher** [comment]
@louisoutin awesome! Thank you for your contributions. I've not used TorchServe in the past, but I know we have had a request for a tutorial from other users. Can you explain a bit about the typical use-case here? How do you send images to the server and get results back? Thanks!

**Comment by louisoutin** [comment]
Hey, thanks @glenn-jocher !

I just updated the Readme with a "Getting predictions" part. But basically here it's how it's done:

Once the dockerimage is running, you can send POST requests to: `localhost:8080/predictions/my_model` (with `my_model` being the name of your model).

The handler in this project expect the inputs images to be sent via a Multipart form with a "key/value" form having in the keys the strings "img"+`[index]` and in the values, the bytes of each images.

Example:
-------
For a batch_size of 5, we would have the following in our Multipart form request:

```
"img1": [bytes_of_the_1st_image],
"img2": [bytes_of_the_2st_image],
"img3": [bytes_of_the_3st_image],
"img4": [bytes_of_the_4st_image],
"img5": [bytes_of_the_5st_image],
```

The returned json of the request contain a single list. Each i-th element of this list represent the i-th image detection results (represented by: `(x1, y1, x2, y2, conf, cls)`)

Note that if there is less input images than the batch size, the rest of the inference batch will be padded with zeros inputs.

**Comment by jdongca2003** [comment]
You can find my scripts for YoloV5 torchServe setup  https://github.com/jdongca2003/Yolov5_torchserve

**Comment by metempasa** [comment]
Hey @louisoutin, i tried your project but it always returns --model-store directory not found: model_store.

I made directory named model_store everywhere literally. but still same. 

What should i do, any idea ?

**Comment by khelkun** [comment]
Another YOLOv5.0 Release v7.0 deploy: https://github.com/ben-omji/serve_yolov5

**Comment by glenn-jocher** [comment]
@khelkun thank you for sharing these repositories! It's great to see the YOLOv5 community actively contributing to different deployment options. The effort to make YOLOv5 accessible for various platforms is truly appreciated. 🙌 If there's anything specific you'd like assistance with, feel free to ask!
