### ISSUE TITLE
Training tutorial link is broken

### ISSUE THREAD

**Issue by zhiqwang** [ultralytics/yolov5#1682]
## 🐛 Bug
Hi yolov5 teams,

This issue is just for reporting a linking problem.
The link of the training tutorial is changed to <https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data-🚀> now, but in the README and wiki home page, the link is still <https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data>, which is broken now.

**Comment by glenn-jocher** [comment]
Thank you for the quick notice of this bug! I've reset the link back to
it's original.

<https://www.ultralytics.com/>


*Glenn Jocher*Founder & CEO, Ultralytics LLC
+1 301 237 6695
 <https://www.facebook.com/ultralytics>
<https://www.twitter.com/ultralytics>
<https://www.youtube.com/ultralytics>
<https://www.github.com/ultralytics>
<https://www.linkedin.com/company/ultralytics>
<https://www.instagram.com/ultralytics>
<https://contact.ultralytics.com/>

**Comment by zhiqwang** [comment]
Hi @glenn-jocher Ah, yep, so I closed it!
