### ISSUE TITLE
export onnx code

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#1683]
## ❔Question

What does it do?

export.py

    # Update model
    for k, m in model.named_modules():
        m._non_persistent_buffers_set = set()  # pytorch 1.6.0 compatibility
        if isinstance(m, models.common.Conv) and isinstance(m.act, nn.Hardswish):
            m.act = Hardswish()  # assign activation
        # if isinstance(m, models.yolo.Detect):
        #     m.forward = m.forward_export  # assign forward (optional)

**Comment by zhiqwang** [comment]
Because pytorch has limitation to export the module named `nn.Hardswish()` in pytorch 1.7.1 and minors. It can be removed if you are using pytorch nightly version.

**Comment by alicera** [comment]
I try to  "#  m.act = Hardswish() " and directly print the "m.act".
I find the "m.act" is the  "Hardswish()"

For example
            print(m.act,"  before \n")
            m.act = Hardswish()  # assign activation
            print(m.act,"  after\n")
the values are the same

**Comment by glenn-jocher** [comment]
`Hardswish()` is an export-friendly workaround. `nn.Hardswish()` is the official pytorch module.

**Comment by alicera** [comment]
What does it do?
    

# TorchScript export
    try:
        print('\nStarting TorchScript export with torch %s...' % torch.__version__)
        f = opt.weights.replace('.pt', '.torchscript.pt')  # filename
        ts = torch.jit.trace(model, img)
        ts.save(f)
        print('TorchScript export success, saved as %s' % f)
    except Exception as e:
        print('TorchScript export failure: %s' % e)
