### ISSUE TITLE
How to deploy to the web？

### ISSUE THREAD

**Issue by XIEdeda** [ultralytics/yolov5#1684]

**Comment by glenn-jocher** [comment]
@XIEdeda there's a variety of options. What's your exact use case?

**Comment by XIEdeda** [comment]
@glenn-jocher It is to display the model on the web, deploy the model to the server, and then upload the image to call the model and return the result

**Comment by glenn-jocher** [comment]
@XIEdeda Torchserve might work best for you then, see https://github.com/ultralytics/yolov5/issues/1681
