### ISSUE TITLE
How to improve the detection result for night scence.

### ISSUE THREAD

**Issue by Egolee0713** [ultralytics/yolov5#1685]
## ❔Question
how to improve Yolov5 performance for night scene.

## Additional context
Firstly, thank you for your great job! @glenn-jocher . And then I have trained Yolov5 for person detection by combination of Coco, Wider person and Crowd person dataset. It has a great performance during the day, but sometimes it has some wrong detection during night. As I know,  add some night images to train model (but I do not have many night data)  or improve the confidence(but it would decrease recall)  would be some method to help. Beside  the above methods,  I want to know how  to improve Yolov5 performance for night scene, may be some special image augmentation? It would be nice if you can give me some suggection. @glenn-jocher

**Comment by glenn-jocher** [comment]
@yongjingli improving results always consists of the same few changes. In general your options are:

- larger dataset
- larger model
- longer traininig
- better labels
- more diverse dataset
- hyperparameter evolution

You've basically landed in one of the red X's below, and you need to take some or all of the above steps to improve your results.

<img width="1248" alt="Screen Shot 2020-12-14 at 6 02 10 PM" src="https://user-images.githubusercontent.com/26833433/102158539-86767b80-3e36-11eb-84fc-69635996c63f.png">

**Comment by Egolee0713** [comment]
OK, I got this, I will try the options you mention above. Thank you for your kind response. @glenn-jocher
