### ISSUE TITLE
Training with Negative Images

### ISSUE THREAD

**Issue by marvision-ai** [ultralytics/yolov5#1689]
Hello! I am in the process of training with negative sample images (images with no specfic objects) to remove false positive detections.
## ❔Question
In the Train custom data tutorial it states: 

> export your labels to YOLO format, with one *.txt file per image (if no objects in image, no *.txt file is required). 

Just to clarify my understanding... If I add the negative sample images to the image dataset without supplying an empty *.txt in the annotation folder, the model will know this is a negative sample and use it to improve the training loss? Has anything changed since last writing this? 

Thank you in advance!

**Comment by glenn-jocher** [comment]
@marvision-ai yes, you can add as many negative/background images to your dataset as you want and they will automatically be included for training, helping to reduce FPs as you noted. 

When the dataset is being scanned these should show up as 'missing' (if you have not supplied a label file), or 'empty' if you supplied an empty label file, but they are both treated identically and both methods work well. You can see COCO128 for example already has 2 images with no labels.

<img width="982" alt="Screen Shot 2020-12-14 at 10 55 03 AM" src="https://user-images.githubusercontent.com/26833433/102122822-ecdda880-3dfa-11eb-9635-6f0efc905c8f.png">

**Comment by marvision-ai** [comment]
@glenn-jocher  Thank you! Makes complete sense. :smile:
