### ISSUE TITLE
Errors on MAC

### ISSUE THREAD

**Issue by Nigysty** [ultralytics/yolov5#1690]
system macos 11.0.1 (macpro 2020 i5)

When I test on MAC with code“python detect.py --source 0”，
The local camera cannot be turned on，And the terminal shows
“Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.25, device='', exist_ok=False, img_size=640, iou_thres=0.45, name='exp', project='runs/detect', save_conf=False, save_txt=False, source='0', update=False, view_img=False, weights='yolov5s.pt')
Using torch 1.7.1 CPU

Fusing layers... 
Model Summary: 232 layers, 7459581 parameters, 0 gradients, 17.5 GFLOPS
zsh: abort      python detect.py --source 0”

**Comment by glenn-jocher** [comment]
@Nigysty hi, thanks for the bug report. This may possibly due to MacOS Big Sur 11.0 upgrade. I've had my own issues with cv2 webcam connections after upgrading, as I develop locally on a Macbook pro also. I'm assuming detection operates correctly for local images and videos?

**Comment by Nigysty** [comment]
> @Nigysty hi, thanks for the bug report. This may possibly due to MacOS Big Sur 11.0 upgrade. I've had my own issues with cv2 webcam connections after upgrading, as I develop locally on a Macbook pro also. I'm assuming detection operates correctly for local images and videos?

yes，detection operates correctly for local images
