### ISSUE TITLE
Hardswish

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#1691]
## ❔Question
Why do you set two method for Hardswish?

method1:
class Hardswish(nn.Module):  # export-friendly version of nn.Hardswish()
    @staticmethod
    def forward(x):
        # return x * F.hardsigmoid(x)  # for torchscript and CoreML
        return x * F.hardtanh(x + 3, 0., 6.) / 6.  # for torchscript, CoreML and ONNX

method2:
self.act = nn.Hardswish()

**Comment by glenn-jocher** [comment]
`# for torchscript, CoreML and ONNX`

**Comment by alicera** [comment]
Your method  " x * F.hardtanh(x + 3, 0., 6.) / 6. "

I want to  change this  x * torch.minimum(F.relu(x + 3.0), 6) / 6.0
But the onnx doesnt support "torch.minimum"
Do you have any idea ?thanks

**Comment by alicera** [comment]
"x * torch.clip(x + 3, 0, 6) / 6" is the same as  " x * F.hardtanh(x + 3, 0., 6.) / 6. " , right??

**Comment by zhiqwang** [comment]
Hi @alicera , maybe the code [here](https://github.com/rwightman/pytorch-image-models/blob/9a25fdf3ad0414b4d66da443fe60ae0aa14edc84/timm/models/layers/activations.py#L74-L85) can help you. But actually it should be numerical equivalent to 

https://github.com/ultralytics/yolov5/blob/1fc9d42a64f248d72e1d3c7b25064998026a478f/utils/activations.py#L15-L19

**Comment by zachluo** [comment]
> "x * torch.clip(x + 3, 0, 6) / 6" is the same as " x * F.hardtanh(x + 3, 0., 6.) / 6. " , right??

I think it is
