### ISSUE TITLE
COCO dataset lacks of labels

### ISSUE THREAD

**Issue by gaoypeng** [ultralytics/yolov5#1693]
I download coco2017labels.zip from the website 'https://github.com/ultralytics/yolov5/releases/download/v1.0/coco2017labels.zip'. But I only get 11726 txt files in the train2017 folder and 4952 files in the val2017 folder. Is the original data set missing files?

**Comment by NanoCode012** [comment]
Those are ‘negative’ samples aka images with no objects to be detected.

**Comment by Hlings** [comment]
But I find the corresponding images in train2017 folder

**Comment by Hlings** [comment]
> Those are ‘negative’ samples aka images with no objects to be detected.

But I find the corresponding images in train2017 folder

**Comment by gaoypeng** [comment]
> Those are ‘negative’ samples aka images with no objects to be detected.

But I find the corresponding images in train2017 folder

**Comment by NanoCode012** [comment]
See https://github.com/ultralytics/yolov5/issues/659

**Comment by gaoypeng** [comment]
> See #659

thank you.
