### ISSUE TITLE
Export model of yolov5s to torchscript don't work anymore

### ISSUE THREAD

**Issue by WeNeedMore** [ultralytics/yolov5#1696]
pytorch version : 1.7.0
libtorch version tried: 1.6.0, 1.7.0, 1.7.1
compiler: vc2017 64bits
os : win10 64

Using codes of this header(f7a923b446c0a8913330ef8cc4526cdcbc5974f3) to export the model of yolo5s to torchscript model and loaded by libtorch. In the old day , following codes work

```
std::vector<torch::jit::IValue> inputs;    
auto input= cv::Mat::zeros(640, 640, CV_32FC3);
auto input_tensor = torch::from_blob(input.data, {1, input.rows, input.cols, 3}).to(torch::kCUDA);    
input_tensor = input_tensor.permute({0, 3, 1, 2}).contiguous();
inputs.emplace_back(std::move(input_tensor));

torch::jit::IValue forward_results = module.forward(inputs);
auto detections = forward_results .toTuple()->elements()[0].toTensor();
```

But now, the type of the output is not tuple but list, and the size not equal to 4 but only 3. The output of the detect.py is a tuple, 
it has two element, first one is the tensor, second is the list with 3 tensors, the output we need is the first one, but instead the libtorch always obtain the second one(list with 3 tensors).

```
auto forward_results = module.forward(inputs);
if(forward_results.isTensor()){
    cout<<"is tensor"<<endl;
    auto ts = forward_results.toTensor();
    cout<<"tensor dim = "<<ts.dim()<<endl;
    for(int64 j = 0; j != ts.dim(); ++j){
        cout<<"dim "<<j<<" = "<<ts.size(j)<<endl;
    }
}
```

Do you still have the link of the old models?Thanks

**Comment by glenn-jocher** [comment]
@WeNeedMore all models are attached to each release as release assets at the time of release:
https://github.com/ultralytics/yolov5/releases

**Comment by WeNeedMore** [comment]
> 
> 
> @WeNeedMore all models are attached to each release as release assets at the time of release:
> https://github.com/ultralytics/yolov5/releases

Thanks, but the models are lost I think, when I click on the link(yolov5s) of v3.0, it always leas me to the top of the page but not download the model, when I click on v2.0, the google drive say the model is deleted.

The warning message I saw when export the model

`torch\jit\_trace.py:934: TracerWarning: Encountering a list at the output of the tracer might cause the trace to be incorrect, this is only valid if the container structure does not change based on the module's inputs. Consider using a constant container instead (e.g. for `list`, use a `tuple` instead. for `dict`, use a `NamedTuple` instead). If you absolutely need this and know the side effects, pass strict=False to trace() to allow this behavior.`

**Comment by glenn-jocher** [comment]
@WeNeedMore all models are available for all release, you just download whatever you want. It's very simple.

<img width="1029" alt="Screen Shot 2020-12-15 at 11 46 05 AM" src="https://user-images.githubusercontent.com/26833433/102264895-21b93080-3ecb-11eb-917f-b69a8b666a09.png">

**Comment by WeNeedMore** [comment]
> 
> 
> @WeNeedMore all models are available for all release, you just download whatever you want. It's very simple.
> 
> <img alt="Screen Shot 2020-12-15 at 11 46 05 AM" width="1029" src="https://user-images.githubusercontent.com/26833433/102264895-21b93080-3ecb-11eb-917f-b69a8b666a09.png">

Thanks, please click  on the link by yourself, I tried with v3.0, v2.0 with firefox and chrome, don't work

**Comment by glenn-jocher** [comment]
@WeNeedMore I just downloaded all four YOLOv5s release models by clicking their link in the release assets: v1, v2, v3, v3.1. All download correctly.

**Comment by glenn-jocher** [comment]
@WeNeedMore what's your geographical location? You can also download these directly from the command line using wget, curl etc, or even with the torch download function:

```python
import torch

torch.hub.download_url_to_file('https://github.com/ultralytics/yolov5/releases/download/v1.0/yolov5s.pt', 'yolov5s.pt')
```

**Comment by glenn-jocher** [comment]
<img width="1037" alt="Screen Shot 2020-12-15 at 12 10 02 PM" src="https://user-images.githubusercontent.com/26833433/102267242-7a3dfd00-3ece-11eb-879c-650ed1f58261.png">

**Comment by WeNeedMore** [comment]
> 
> 
> <img alt="Screen Shot 2020-12-15 at 12 10 02 PM" width="1037" src="https://user-images.githubusercontent.com/26833433/102267242-7a3dfd00-3ece-11eb-879c-650ed1f58261.png">

Sorry, my bad, I click on the wrong url, thanks for your help. Will post when find out the version still work

**Comment by WeNeedMore** [comment]
Find out the issue, in order to use it on c++, you need to 

1. Change line 50 form True to False

`model.model[-1].export = False  `

2. In order to run on the gpu, you need to change 'cpu' to 'cuda', line 33 and line 41

line 33

`model = attempt_load(opt.weights, map_location=torch.device('cuda')) `

line 41

`img = torch.zeros(opt.batch_size, 3, *opt.img_size).to(device='cuda')    # image size(1,3,320,192) iDetection`
