### ISSUE TITLE
detect.py --classes IndexError

### ISSUE THREAD

**Issue by VvvvvGH** [ultralytics/yolov5#17]
## 🐛 Bug
```
Traceback (most recent call last):
  File "detect.py", line 172, in <module>
    detect()
  File "detect.py", line 79, in detect
    fast=True, classes=opt.classes, agnostic=opt.agnostic_nms)
  File "D:\yolov5-master\utils\utils.py", line 511, in non_max_suppression
    x = x[(j.view(-1, 1) == torch.tensor(classes, device=j.device)).any(1)]
IndexError: The shape of the mask [21] at index 0does not match the shape of the indexed tensor [20, 6] at index 0
```
## To Reproduce
**REQUIRED**: Code to reproduce your issue below
```
 python detect.py --source 0 --weights yolov5x.pt --view-img --classes 0
```

## Expected behavior
No error produce

## Environment

 - OS: Windows
 - GPU 1080

## Additional context
https://github.com/ultralytics/yolov5/blob/7c2832cd4903e072bd4e20e175144101ff088313/utils/utils.py#L501-L512

## Possible fix
Change 
```
 if classes: 
     x = x[(j.view(-1, 1) == torch.tensor(classes, device=j.device)).any(1)] 
```
To
```
 if classes: 
     x = x[(x[:, 5:].view(-1, 1) == torch.tensor(classes, device=j.device)).any(1)] 
```

**Comment by glenn-jocher** [comment]
@VvvvvGH thank you for your bug report! We can successfully reproduce this following your example. I will look into this.

**Comment by glenn-jocher** [comment]
@VvvvvGH yes you are correct, x and j are becoming different shapes causing the error. Your solution works well. I will push a fix shortly.

**Comment by Tamme** [comment]
Same fix needs to be applied in yolov3 repo also

**Comment by glenn-jocher** [comment]
@Tamme submit a PR on the relevant repo please.
