### ISSUE TITLE
How is it different than YOLOv4? (other than speed and size)

### ISSUE THREAD

**Issue by priteshgohil** [ultralytics/yolov5#170]
Explanation on how is it different than YOLOv4 is much appreciated.

A concrete description on uniqueness would help us to use this code with confidence.

**Comment by glenn-jocher** [comment]
We are aiming to publish a paper towards the end of the year. In the meantime this might help: https://blog.roboflow.ai/yolov4-versus-yolov5/

**Comment by priteshgohil** [comment]
Thanks @glenn-jocher
