### ISSUE TITLE
Wandb Problem

### ISSUE THREAD

**Issue by Rickyhu2** [ultralytics/yolov5#1703]
## ❔Question
after i pip install wandb ,when i try to run train.py,there is a problem " wandb.errors.error.Usage Error:api_key not configured (no-tty). Run wandb login",what should I do?

**Comment by glenn-jocher** [comment]
@hhl0202 you can try to run `$ wandb login` before training. Once you are logged in, train.py will use W&B automatically without. asking for any other login info.
