### ISSUE TITLE
confusion_matrix.png and results.png problem

### ISSUE THREAD

**Issue by cgyeon-muhayu** [ultralytics/yolov5#1707]
## ❔Question
The other pngs are fine, but these two png files are a problem.
Has anyone experienced this kind of situation?

## Additional context
![image](https://user-images.githubusercontent.com/73932777/102313348-d2026400-3fb3-11eb-9cb3-41e96f0cc44e.png)
![image](https://user-images.githubusercontent.com/73932777/102313390-e9d9e800-3fb3-11eb-968d-1b98908935c3.png)

**Comment by glenn-jocher** [comment]
@cgyeon-muhayu your box and cls are nan, indicating you likely have no validation labels due to improper labelling.

**Comment by yin1820** [comment]
> @cgyeon-muhayu your box and cls are nan, indicating you likely have no validation labels due to improper labelling.

I also met this problem, how do you solve it？

**Comment by yin1820** [comment]
I also met this problem, how do you solve it？@cgyeon-muhayu
