### ISSUE TITLE
How can I get a P-R curve of coco mAP method

### ISSUE THREAD

**Issue by LEEGILJUN** [ultralytics/yolov5#1708]
## ❔Question
Hi I think YOLO V5 is the best model.
Thank you for making this model.
I have one question.
I want to get 0.5:0.95 P-R curve on when i work during Train and Test.py

I want to get something like the image below.
but it is mAP@0.5
![image](https://user-images.githubusercontent.com/23168829/102312665-784d6a00-3fb2-11eb-8ea7-c8566695bde2.png)

Can I simply modify it in the code to get P-R curve? about 0.5:0.95 
Or do I need to add new code?

Thank you

**Comment by NanoCode012** [comment]
There should be PR curve under runs/train/exp# directory.

**Comment by LEEGILJUN** [comment]
@NanoCode012 Yes I know but it does not include object classes of each other 
ex) it did not include 0.5:0.95 mAP of 0, 1, 2 object classes.....only total mAP.....Like the attached picture

**Comment by glenn-jocher** [comment]
@LEEGILJUN you can update the python code here to mean the 10 threshold outputs into a new `py`:
https://github.com/ultralytics/yolov5/blob/1fc9d42a64f248d72e1d3c7b25064998026a478f/utils/metrics.py#L64-L75

**Comment by LEEGILJUN** [comment]
@glenn-jocher I changed the code according to your opinion.
like the image below!! it is right??
![image](https://user-images.githubusercontent.com/23168829/102435007-3dead800-4059-11eb-8efb-a095d96c4737.png)

**Comment by glenn-jocher** [comment]
No. `py` is what gets plotted.  You need to average `py` across thresholds.

**Comment by LEEGILJUN** [comment]
@glenn-jocher 
Thanks but I don't understand... 
I know that the mAP threshold is 0.5, 0.05, 0.95 !!!
but I can not found the iou threshold in metrix.py...
only found like the image below

![image](https://user-images.githubusercontent.com/23168829/102446066-48649c00-4070-11eb-8e50-b9809472fb62.png)

If I misunderstood, your mean that a make new code in the original code of metrics.py??
Thank you for your help in the midst of busy.
I still lack a lot.
If it's okay, please give me a little more hints.

**Comment by glenn-jocher** [comment]
@LEEGILJUN `py` is defined at 0.5. You need to define it at every value and then take the mean through the threshold dimension.
