### ISSUE TITLE
Anchor Problems

### ISSUE THREAD

**Issue by JiaLim98** [ultralytics/yolov5#171]
@glenn-jocher Recently I got incredibly low AP and Precision and Recall to be zero (see fig. below)
![image](https://user-images.githubusercontent.com/66768413/85303241-d2c2ad80-b4dc-11ea-96ef-1482c83c48cf.png)
I have cloned the repo again and still get the same thing. I also made sure that the autoanchor is 'false'
I manually computed the anchors using k_mean_anchors in utils.py and substitute 9 anchors to the .models/yolov5s.yaml and similar output was obtained.

What does the P3/8, P4/16 and P5/32 mean?
![image](https://user-images.githubusercontent.com/66768413/85304293-2aade400-b4de-11ea-8b14-45ca85b62e3a.png)
Above shows the anchor generated using k_mean_anchors

Regards,
JiaLim98

**Comment by glenn-jocher** [comment]
@JiaLim98 train 300 epochs and post your results.png.

**Comment by JiaLim98** [comment]
@glenn-jocher My apologies. It was normal.
