### ISSUE TITLE
How can I parse ONNX output in C# for ML.NET

### ISSUE THREAD

**Issue by raulsf6** [ultralytics/yolov5#1716]
## ❔Question
How can I parse the output layer of yolov5s exported to ONNX in C#?

## Additional context
I trained yolov5s with a custom dataset and I exported to ONNX to use it with in my project with ML.NET. However, I do not know how to parse the output to extract the detections as it is used in detect.py. The output has a [1,3,80,80,7] shape.

**Comment by glenn-jocher** [comment]
@raulsf6 for ONNX export you may want to try export=False for bounding box outputs.

**Comment by raulsf6** [comment]
@glenn-jocher  where exactly?

**Comment by raulsf6** [comment]
@glenn-jocher nvm, I just noticed where the line is. The real question would be, why?

**Comment by kellansteele** [comment]
@raulsf6 When export=True, the Detect() layer is not exported, whereas when export=False, the Detect() layer is exported. A nice way to see what changes is using Netron. You'd export your model with export=True and export it (saved under a different name) with export=False. Upload them to [Netron](https://netron.app/) (also see [Netron repo](https://github.com/lutzroeder/Netron)) and you'll see there's a (very wide looking) addition to the export=False version. I believe this is the Detect() layer. 

There are a few more things that need to be implemented even after this though. A good starting point is here: [ultralytics/yolov5#343 (comment)](https://github.com/ultralytics/yolov5/issues/343#issuecomment-658021043).

Also, this might be helpful: [BobLd/YOLOv4MLNet/issues/2#issuecomment](https://github.com/BobLd/YOLOv4MLNet/issues/2#issuecomment-740634809). There's a branch off of YOLOv4MLNet for a YOLOv5MLNet implementation. The few things that haven't been implemented yet I'm actually trying to figure out for myself and would love to hear about how you get on!

**Comment by raulsf6** [comment]
@kellansteele thanks for your answer! Now I get [1, 25200, 7] extra layer which I suppose is the Detect layer. 

I can see that NMS is not still implemented in the branch you sent me, so maybe I'm going to retrain my model in Yolov4. Anyway, [this example project](https://docs.microsoft.com/en-gb/dotnet/machine-learning/tutorials/object-detection-onnx) implements some kind of NMS for TinyYolov2. Could it be useful? Again, thanks for your answer.

**Comment by deanbennettdeveloper** [comment]
I've managed to get ML.NET and YoloV5 working. Took a while and lots of research but eventually cracked it. My boxes are slightly off though so something still not quite right, but I'm only interested in fast predictions and good confidence so it's fine for me. The export=False in the export function was the key.

In the end I used some of BobLd code and some from other places. interleavePixelColors: false when creating the prediction was key and I'd previously missed this. However unlike BobLd code I've used the raw output which the export=False, then my prediction filter code is like this if it helps you (I've just took the C++ code and manually did the came in .net. Like I say bounding boxes are slightly off for some reason, would be nice to find out what that issue is (it could be the NMS routine).

List<float[]> postProcesssedResults = new List<float[]>();

      int size = Output.Length; // 1x25200x85=2142000
      int dimensions = categories.Length + 5;
      int rows = (int)(size / dimensions); //25200
      int confidenceIndex = 4;
      int labelStartIndex = 5;
      float modelWidth = 416.0F;
      float modelHeight = 416.0F;
      float xGain = modelWidth / imageWidth;
      float yGain = modelHeight / imageHeight;

      List<YoloV5Result> resultsNms = new List<YoloV5Result>();

      for (int i = 0; i < rows; ++i) {
        
        int index = i * dimensions;
        if (Output[index + confidenceIndex] <= scoreThres) continue;

        for (int j = labelStartIndex; j < dimensions; ++j) {
          Output[index + j] = Output[index + j] * Output[index + confidenceIndex];
        }

        for (int k = labelStartIndex; k < dimensions; ++k) {
          
          if (Output[index + k] <= iouThres) continue;

          string label = categories[k - labelStartIndex];
          float confidence = Output[index + k];

          Console.WriteLine("Image:" + file + " Label:" + label + " Conf:" + confidence);

          var x1 = (Output[index] - Output[index + 2] / 2) / xGain; //top left x
          var y1 = (Output[index + 1] - Output[index + 3] / 2) / yGain; //top left y
          var x2 = (Output[index] + Output[index + 2] / 2) / xGain; //bottom right x
          var y2 = (Output[index + 1] + Output[index + 3] / 2) / yGain; //bottom right y

          resultsNms.Add(new YoloV5Result(x1, y1, x2, y2, label, confidence, ""));

        }
      }

      List<YoloV5Result> r = new List<YoloV5Result>();

      foreach(var label in resultsNms.Select(p => p.Label).Distinct()) {
        r.Add(resultsNms.Where(p => p.Label == label).OrderByDescending(p => p.Confidence).First());
      }

      return r;

**Comment by BobLd** [comment]
In the test I did on YoloV5, I've not converted the model myself but used the model provided [here](https://github.com/BobLd/YOLOv4MLNet/issues/2#issuecomment-728439973), so `Detect()` is not included in the model. Could anyone share a link to a Onnx model with `export=False`? If not, I'll do the conversion myself.

@kellansteele, @raulsf6 You can find a simple implementation of NMS [here](https://github.com/BobLd/YOLOv4MLNet/blob/7e48f8dea2ccaaa5e7bd10d0b3dc5543cc59a888/YOLOv4MLNet/DataStructures/YoloV4Prediction.cs#L137-L167):
```csharp
// Non-maximum Suppression
postProcesssedResults = postProcesssedResults.OrderByDescending(x => x[4]).ToList(); // sort by confidence
List<YoloV4Result> resultsNms = new List<YoloV4Result>();


int f = 0;
while (f < postProcesssedResults.Count)
{
	var res = postProcesssedResults[f];
	if (res == null)
	{
		f++;
		continue;
	}

	var conf = res[4];
	string label = categories[(int)res[5]];

	resultsNms.Add(new YoloV4Result(res.Take(4).ToArray(), label, conf));
	postProcesssedResults[f] = null;

	var iou = postProcesssedResults.Select(bbox => bbox == null ? float.NaN : BoxIoU(res, bbox)).ToList();
	for (int i = 0; i < iou.Count; i++)
	{
		if (float.IsNaN(iou[i])) continue;
		if (iou[i] > iouThres)
		{
			postProcesssedResults[i] = null;
		}
	}
	f++;
}
```

I will try to have a look today.

**Comment by raulsf6** [comment]
@BobLd I tested your yolov5 branch with yolov5s model exported with export = True. I suppose NMS or the filter is not working (even uncommenting line 165) because I get a really messy output.

![cars road _processed](https://user-images.githubusercontent.com/28561912/102755507-d1c8e680-436e-11eb-9923-e6304983e29f.jpg)

On the other hand, @deanbennettdeveloper, what else exactly did you modify? Specially in YoloV5Result and YoloV4Prediction

(EDIT)

@deanbennettdeveloper, nvm, I just fixed it, shapes and sizes had to be adjusted. Fixing the boxes issue would be really nice, I'll keep trying. Thanks!

**Comment by deanbennettdeveloper** [comment]
@raulsf6 Yes what you're seeing is exactly what I saw when I was using the Export = True. When you export with Export = False you will get an extra output, and vector looks something like for a 15 class and 640 x 640 model

[VectorType(1, 25200, 20)]
[ColumnName("output")]
public float[] Output { get; set; }

In example cases though there are 80 classes so you'll have 85 instead of 20. The array you'll get for Output therefore will be 25200 x 85 in length. This output can be used directly i.e. no need to apply sigmoid etc.

You'll still get the original outputs too but I've ignore them now I have the raw output. If you then loop through this array and grab the boxes, confidence and class score then you'll get correct results. You will get overlapping boxes over object detection, that's where I've created a very basic loop to grab just the highest confidence of each label (this is flawed I know, but for my use I don't need more than this). Here's my whole prediction class. It would be good to get it working through the original Export = True way, but for now this seems to be good enough for my use.

public class YoloV5Prediction {

    /// <summary>
    /// Identity
    /// </summary>
    [VectorType(1, 25200, 20)]
    [ColumnName("output")]
    public float[] Output { get; set; }

    [ColumnName("width")]
    public float ImageWidth { get; set; }

    [ColumnName("height")]
    public float ImageHeight { get; set; }

    public IReadOnlyList<YoloV5Result> GetResults(string file, float imageWidth, float imageHeight, string[] categories, float scoreThres = 0.5f, float iouThres = 0.5f) {

      //List<float[]> postProcesssedResults = new List<float[]>();

      int size = Output.Length; // 1x25200x85=2142000
      int dimensions = categories.Length + 5;
      int rows = (int)(size / dimensions); //25200
      int confidenceIndex = 4;
      int labelStartIndex = 5;
      float modelWidth = 640.0F;
      float modelHeight = 640.0F;
      float xGain = modelWidth / imageWidth;
      float yGain = modelHeight / imageHeight;

      List<YoloV5Result> resultsNms = new List<YoloV5Result>();

      for (int i = 0; i < rows; ++i) {
        
        int index = i * dimensions;
        if (Output[index + confidenceIndex] <= scoreThres) continue;

        for (int j = labelStartIndex; j < dimensions; ++j) {
          Output[index + j] = Output[index + j] * Output[index + confidenceIndex];
        }

        for (int k = labelStartIndex; k < dimensions; ++k) {
          
          if (Output[index + k] <= scoreThres) continue;

          string label = categories[k - labelStartIndex];
          float confidence = Output[index + k];

          var x1 = (Output[index] - Output[index + 2] / 2) / xGain; //top left x
          var y1 = (Output[index + 1] - Output[index + 3] / 2) / yGain; //top left y
          var x2 = (Output[index] + Output[index + 2] / 2) / xGain; //bottom right x
          var y2 = (Output[index + 1] + Output[index + 3] / 2) / yGain; //bottom right y

          resultsNms.Add(new YoloV5Result(x1, y1, x2, y2, label, confidence, ""));

        }
      }

      List<YoloV5Result> r = new List<YoloV5Result>();

      foreach(var label in resultsNms.Select(p => p.Label).Distinct()) {
        r.Add(resultsNms.Where(p => p.Label == label).OrderByDescending(p => p.Confidence).First());
      }

      return r;

    }

  }

**Comment by deanbennettdeveloper** [comment]
@raulsf6 In my Result class I added another constructor just for ease and location of the output image which I use later in my code, that's only change.

public YoloV5Result(float x1, float y1, float x2, float y2, string label, float confidence, string output) {
          BBox = new float[] { x1, y1, x2, y2 };
          Label = label;
          Confidence = confidence;
          OutputLocation = output;
        }

**Comment by raulsf6** [comment]
@deanbennettdeveloper I saw that you changed the constructor, I just fixed it calling it like this:

`resultsNms.Add(new YoloV5Result(new[] { x1, y1, x2, y2 }, label, confidence));`

My model justs uses 2 classes so I tuned the rest of the code and it is labeling and classifying perfectly. However I suppose that boxes are not working because of the implementation of IoU and NMS, maybe @BobLd implementations are useful here?

**Comment by BobLd** [comment]
see [here](https://github.com/BobLd/YOLOv4MLNet/issues/2) regarding @raulsf6 comment on wrong bounding boxes

**Comment by farhanrw** [comment]
How are the inference times like in ML.Net for your tests? In my case there is a big increase in test times. For both cases I am talking about the CPU runtimes.

**Comment by luqmanmusa** [comment]
Hi @deanbennettdeveloper, was wondering how did you implement your code with your 'main program'? Is it similar to @BobLd Program.cs?
