### ISSUE TITLE
about conf in train.py

### ISSUE THREAD

**Issue by ai1361720220000** [ultralytics/yolov5#1717]
## ❔Question
The model was tested on val data each epoch, and i found the mAPs was based on the conf_thres which was a default value of 0.001. Could you tell me why during training time, the conf_thres was set on 0.001? 
```
if not opt.notest or final_epoch:  # Calculate mAP
                results, maps, times = test.test(opt.data,
                                                 batch_size=total_batch_size,
                                                 imgsz=imgsz_test,
                                                 model=ema.ema,
                                                 single_cls=opt.single_cls,
                                                 dataloader=testloader,
                                                 save_dir=save_dir,
                                                 plots=epoch == 0 or final_epoch,  # plot first and last
                                                 log_imgs=opt.log_imgs if wandb else 0
```

**Comment by glenn-jocher** [comment]
@ai1361720220000 at the risk of using circular logic, the confidence threshold was set to 0.001 because this is the confidence threshold for training and testing.

**Comment by ai1361720220000** [comment]
> @ai1361720220000 at the risk of using circular logic, the confidence threshold was set to 0.001 because this is the confidence threshold for training and testing.

Thanks for your answer. But i'm still confused about circular logic? What does that mean? 
In my mind, if the confidence threshold was set to 0.001, there will be numbers of boxes outputed from a certain image. But according to the result of trainning and testing time, the mAP still can come to a high value. Why?
Also if i set conf threshold to 0.001,  the mAP was a much lower value by detect.py. Why in testing time and detection time, the conf has to be set differently.

**Comment by glenn-jocher** [comment]
@ai1361720220000 circular logic means it's hot because its summer and it's summer because it's hot.

You're free to use whatever arguments you want, nothing 'has' to be set any specific way.
