### ISSUE TITLE
android gpu/cpu annomaly

### ISSUE THREAD

**Issue by oranmichel** [ultralytics/yolov5#1718]
@zldrobit 
good evening
the cpu prediction on android is pretty good while the gpu prediction is bad.
all the bboxs are not located properly (starts from the top left corner) while the bboxs sizes and the predicted classes are just right.
is there any explanation to this phenomena?
thanks

**Comment by glenn-jocher** [comment]
@oranmichel hi, did you resolve your original issue?

Also did you see a speedup when moving from android CPU to GPU?

**Comment by oranmichel** [comment]
Solved it, thank you very much.
Managed to speedup X2 moving from cpu to gpu on galaxy s8.

**Comment by glenn-jocher** [comment]
@oranmichel got it. Did the export quantization (FP32, FP16, FP8 etc.) affect your inference speed on either backend (CPU, GPU)?

**Comment by oranmichel** [comment]
Didn't try FP8 yet, FP16 affected the cpu but almost didn't affect the gpu.
I can also say that multithread gave X3 on the CPU which was really
effective.

**Comment by glenn-jocher** [comment]
Interesting! Android is pretty different than iOS, where the backend execution is assigned by the OS, and can vary by layer/module type.
