### ISSUE TITLE
How to run yolov3 from yolov5 repository implementtion?

### ISSUE THREAD

**Issue by RadoslawDebosz** [ultralytics/yolov5#1720]
## ❔Question
Hello,
I have a problem with a runing yolov3-spp on yolov5 implementation. 

but when I ran train.py with weights: yolov3-spp.weights & model: https://github.com/ultralytics/yolov5/blob/master/models/hub/yolov3-spp.yaml, Then  I've got an error:

  File "/media/ra/tools/yolov5/train.py", line 88, in train
    state_dict = ckpt['model'].float().state_dict()  # to FP32
AttributeError: 'collections.OrderedDict' object has no attribute 'float'
Internal process exited

So I've changed the line  in torch/nn/modules/module.py: (I know that it is  poor workaround)

from:
      state_dict = ckpt['model'].float().state_dict()  # to FP32
to:
       state_dict= ckpt['model']

and then I've run train.py and it works without any error, but  I have very poor results after  1 epoch :

```
   Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 100/100 [00:07<00:00, 13.11it/s]
                 all         400     2.8e+03       0.157     0.00044     0.00174    0.000494
```

In comparing with yolov5 on the same dataset :

  ```
Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 100/100 [00:07<00:00, 12.89it/s]
                 all         400     2.8e+03       0.396       0.416       0.407       0.248
```

I think the problem is with the incompatible versions. Could you help me how to change yolov5 implementation for yolov3 ?
I've downloaded weights using this script: https://github.com/ultralytics/yolov3/blob/master/weights/download_weights.sh.

Best Regards,
Radoslaw

**Comment by glenn-jocher** [comment]
@RadoslawDebosz if you want train yolov3, you can use ultralytics/yolov3 directly:

```bash
git clone https://github.com/ultralytics/yolov3
cd yolov3
python train.py --cfg yolov3-spp.yaml --weights ''
# or 
python train.py --weights yolov3-spp.pt
```

**Comment by whoafridi** [comment]
YOLOv3 & YOLOv5 is different with their implementation & others. so, don't try this
