### ISSUE TITLE
yolov5x.pt is not compatible with ./models/yolov5x.yam

### ISSUE THREAD

**Issue by minertom** [ultralytics/yolov5#1721]
I have seen this question asked before and I have read the responses. 

My interpretation of the responses is that there is the possibility that some older yolov5x.yaml files could have been loaded and that they need to be purged.

 I have downloaded the jupyter notebook to two different directories and have attempted to run on google colab. In both cases, i have received the same error.

I believe that this is the command which causes the error.
`!python train.py --img 640 --batch 4 --epochs 30 \
  --data ./data/clothing.yaml --cfg ./models/yolov5x.yaml --weights yolov5x.pt \
  --name yolov5x_clothing --cache`

This is the full error

`Traceback (most recent call last):
  File "train.py", line 116, in train
    ckpt['model'] = {k: v for k, v in ckpt['model'].float().state_dict().items()
  File "train.py", line 117, in <dictcomp>
    if model.state_dict()[k].shape == v.shape}  # to FP32, filter
KeyError: 'model.18.conv.weight'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 404, in <module>
    train(hyp)
  File "train.py", line 122, in train
    raise KeyError(s) from e
KeyError: "yolov5x.pt is not compatible with ./models/yolov5x.yaml. Specify --weights '' or specify a --cfg compatible with yolov5x.pt."`

How best to proceed?
Thank You 
Tom

**Comment by glenn-jocher** [comment]
@minertom your code or your models, or both are out of date. Use latest and train normally.

**Comment by minertom** [comment]
Thank you for your quick response. I do not understand how my code or
models can be out of date? I never have downloaded before today. The code
came directly from github.

Regards
Tom

**Comment by glenn-jocher** [comment]
@minertom if they are not out of date then they may be modified. If you are running into an error with current master please provide a link to a Colab notebook so we can reproduce ourselves. Thanks!

**Comment by minertom** [comment]
Here is the link. Yes, I am sure that I am running into this error with
current master.

https://colab.research.google.com/drive/1e4zvS6LyhOAayEDh3bz8MXFTJcVFSvZX?usp=sharing#scrollTo=yvQJa9kuoiTD

Thank You

**Comment by glenn-jocher** [comment]
@minertom your link is a 3rd party notebook, out of our control. If you are having issues with it you should raise these directly with the authors of that notebook.

The official notebook is here, authored by Ultralytics, and everything works correctly.
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb
