### ISSUE TITLE
RuntimeError index out of bounds assertion error

### ISSUE THREAD

**Issue by Eitanaso** [ultralytics/yolov5#1724]
## ❔Question
I've been having this problem since I edited the dataset to have more classes and less images, the original dataset has approximately 6000 train images/annotations and 600 validation images/annotations with only 2 classes and trains with no problem. At the start I tried with 100 train images, 10 validation images and 40 classes, the training did run good, so I decided to try with 500 train images, 50 validation images and 13 classes and this error started appearing. 

Since I saw that the problem is only when de validation step is done, I already deleted the labels which I found were out of bounds, but this keeps happening and don't know why.

Has someone had this problem already and solved it? Or does someone know what should I do/try doing?

![error](https://user-images.githubusercontent.com/53804725/102567464-53dfb380-40c0-11eb-8e56-08fa7661e80e.png)

## Additional context

The dataset is an edit of the SKU110K_fixed in the way that it can be used with this model and have followed the steps from the tutorial. The detection problem (when the dataset had 2 classes) did do well, but now, with the classification problem, I have been having this error.

**Comment by glenn-jocher** [comment]
@Eitanaso if everything works, you modify your dataset, and functionality is broken, the culprit would lie in your modifications.
