### ISSUE TITLE
Video rotation when running detection.

### ISSUE THREAD

**Issue by Seneca-Sys** [ultralytics/yolov5#1725]
The issue is simple im running detection on a video, however the output and the detection is rotated 90* to the left.

To reproduce:

Run detection on a video taken with aspect ratio of a phone.

**Comment by glenn-jocher** [comment]
@Seneca-Sys see https://github.com/ultralytics/yolov5/pull/1124 for a video rotation solution. Note there are added dependency requirements.

**Comment by glenn-jocher** [comment]
@Seneca-Sys also note we have video sources for issue reproducibility here. The reason #1124 is not merged into master is that the dependency requirements become onerous. 

https://github.com/ultralytics/yolov5/releases/download/v1.0/decelera_landscape.mov
https://github.com/ultralytics/yolov5/releases/download/v1.0/decelera_portrait.mov
