### ISSUE TITLE
INT8

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#1730]
## ❔Question

version : tensorrt 7.2 、 onnx-tensorrt7.2

I use the onnx-tensorrt command to parser yolov5
"auto parser = UniquePtrnvonnxparser::IParser(nvonnxparser::createParser(*network, gLogger.getTRTLogger()));"

yolov5 can detect the object for fp16
yolov5 cant detect any object for int8

I build the process of int8 doesnt meet any error.
How to solve it ? Do you have any idea?

**Comment by Wulingtian** [comment]
你好，我在 tensorrt 7.2下成功生成了fp16和int8量化的模型，fp16模型正常出框，int8模型不出框，请问你有遇到过这种问题吗？我是通过pt->onnx->trt生成的模型。

**Comment by alicera** [comment]
> 你好，我在 tensorrt 7.2下成功生成了fp16和int8量化的模型，fp16模型正常出框，int8模型不出框，请问你有遇到过这种问题吗？我是通过pt->onnx->trt生成的模型。

me,too.
Do you have any idea?

**Comment by Wulingtian** [comment]
https://github.com/enazoe/yolo-tensorrt 你用这个GitHub代码也没有跑出框吗？会不会是tensorrt 版本太高了？

**Comment by alicera** [comment]
I also use the  tensorrt 7.2.
The project can works for INT8. 
But it directly use weight -> trt.  Not onnx -> trt

**Comment by Wulingtian** [comment]
你做int8量化的时候有尝试降低trt版本吗？

**Comment by swave2015** [comment]
me too, int8 no detect

**Comment by alicera** [comment]
I try to use trt 7.1.
 It is the same status.

**Comment by Wulingtian** [comment]
我准备试试pt->onnx->caffe->trt int 这条路

**Comment by Wulingtian** [comment]
问一下，你是yolov5的3.1版本转换为onnx的模型吗? 3.0以上的模型增加了激活函数Hardswish，当前onnx还不支持.

**Comment by alicera** [comment]
It use the class Hardswish to replace  nn.Hardswish() when export the onnx.
So, you've done it with other yolov5 version?

class Hardswish(nn.Module):  # export-friendly version of nn.Hardswish()
    @staticmethod
    def forward(x):
        # return x * F.hardsigmoid(x)  # for torchscript and CoreML
        return x * F.hardtanh(x + 3, 0., 6.) / 6.  # for torchscript, CoreML and ONNX

**Comment by Wulingtian** [comment]
> It use the class Hardswish to replace nn.Hardswish() when export the onnx.
> So, you've done it with other yolov5 version?
> 
> class Hardswish(nn.Module): # export-friendly version of nn.Hardswish()
> @staticmethod
> def forward(x):
> # return x * F.hardsigmoid(x) # for torchscript and CoreML
> return x * F.hardtanh(x + 3, 0., 6.) / 6. # for torchscript, CoreML and ONNX

你现在解决了吗？

**Comment by Wulingtian** [comment]
> It use the class Hardswish to replace nn.Hardswish() when export the onnx.
> So, you've done it with other yolov5 version?
> 
> class Hardswish(nn.Module): # export-friendly version of nn.Hardswish()
> @staticmethod
> def forward(x):
> # return x * F.hardsigmoid(x) # for torchscript and CoreML
> return x * F.hardtanh(x + 3, 0., 6.) / 6. # for torchscript, CoreML and ONNX

老哥，加个联系方式？

**Comment by alicera** [comment]
what is your mail

**Comment by Wulingtian** [comment]
> what is your mail
2813389262@qq.com

**Comment by abcilike** [comment]
onnx->trt int8 need change leakyrelu -> relu
leakyrelu int8 quant unstable
