### ISSUE TITLE
How to handle this error, Error in cpuinfo: failed to parse file /sys/devices/system/cpu/kernel_max: "-1 " is not an unsigned number

### ISSUE THREAD

**Issue by tonywang-sh** [ultralytics/yolov5#1733]
## ❔Question
When running the script of detect.py with yolov5s.pt in ARM ubuntu, there is an error message, Error in cpuinfo: failed to parse file /sys/devices/system/cpu/kernel_max: "-1 " is not an unsigned number.
what is the reason about this error, how to solve it?

## Additional context
with the runtime, pytorch 1.6.0 compiled in ARM ubuntu system, and quad-core cortex-A53

The error message is the below:
Fusing layers... 
Error in cpuinfo: failed to parse file /sys/devices/system/cpu/kernel_max: "-1
" is not an unsigned number
Error in cpuinfo: failed to parse file /sys/devices/system/cpu/kernel_max: "-1
" is not an unsigned number
Error in cpuinfo: failed to parse file /sys/devices/system/cpu/kernel_max: "-1
" is not an unsigned number
Error in cpuinfo: failed to parse file /sys/devices/system/cpu/kernel_max: "-1
" is not an unsigned number
Model Summary: 191 layers, 7.26588e+06 parameters, 0 gradients, 16.9 GFLOPS

**Comment by QasimWani** [comment]
@tonywang-sh longshot but do you remember how you were able to solve this issue?

**Comment by ajithkumarmcw** [comment]
@QasimWani were u able solve this error ?

**Comment by glenn-jocher** [comment]
Hello @ajithkumarmcw, 

I see that you're having an error in CPUinfo related to parsing the file `/sys/devices/system/cpu/kernel_max`. Unfortunately, I cannot provide a specific solution without more information about your setup and the steps you have taken so far.

However, I can suggest a few general troubleshooting steps that may help:

1. Make sure you have the latest version of YOLOv5 and PyTorch installed.
2. Check your system configuration to ensure that it meets the system requirements mentioned in the YOLOv5 repository.
3. Double-check that the file `/sys/devices/system/cpu/kernel_max` exists and has the correct permissions.
4. If you are running YOLOv5 on a different platform or architecture, you may need to make adjustments for compatibility.
5. Consider searching for similar issues on the YOLOv5 GitHub repository or asking for help on the official YOLOv5 discussion forum.

Remember, the YOLOv5 GitHub repository is maintained by a dedicated team that provides active support and updates. If you cannot find a solution, I encourage you to open a new issue with detailed information about your error, including system configurations, software versions, and steps to reproduce the error.

Thanks, and I hope this helps to point you in the right direction!
