### ISSUE TITLE
mss grab color conversion problem using TorchHub

### ISSUE THREAD

**Issue by gpierard** [ultralytics/yolov5#1735]
## 🐛 Bug
Images grabbed with `mss` need to be converted to RGB before being fed as input to `torch`'s `model`s

However the proposed solution to do this conversion to RGB does not work `img2 = cv2.imread('bus.jpg')[:, :, ::-1]`

Instead, this has to be used: 

 `result = model(cv2.cvtColor(scr, cv2.COLOR_BGR2RGB), size=400)`

## To Reproduce (REQUIRED)

Input:

See full code and resolution [on SO](https://stackoverflow.com/questions/65363565/pytorch-with-yolov5-color-channel-and-result-display/65364108#65364108)

Output:
`result.show()` outputting a non-normal color channel image, with dramatically reduced model accuracy of course (since it was trained on normal color channels).

## Expected behavior
Converting the image to RGB using `result = model(cv2.cvtColor(scr, cv2.COLOR_BGR2RGB), size=400)` fixed the problem.
- TorchHub shows a normal image with `result.show()`
- Accuracy of the model back to normal

## Environment

 - OS: [Windows 10]
 - GPU [e.g. RTX 2080 SUPER]

**Comment by glenn-jocher** [comment]
@gpierard thanks for raising this issue. I can't reproduce on Windows actually because I don't have access to a suitable environment. Can you try to run the following code in your example and post a screenshot here of the result?

```python
import cv2
import numpy as np

file = 'data/images/bus.jpg'
im1 = cv2.imread(file)[:, :, ::-1]
im2 = cv2.cvtColor(cv2.imread(file), cv2.COLOR_BGR2RGB)
print(np.allclose(im1, im2))
```

On MacOS I see:
<img width="1152" alt="Screen Shot 2020-12-20 at 10 02 21 AM" src="https://user-images.githubusercontent.com/26833433/102720647-77fee880-42aa-11eb-9ca9-d9453537a652.png">

In Colab [notebook](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb?hl=en) I see:
<img width="1110" alt="Screen Shot 2020-12-20 at 10 03 08 AM" src="https://user-images.githubusercontent.com/26833433/102720685-9a910180-42aa-11eb-92cb-8f9c601ba440.png">

**Comment by gpierard** [comment]
My aim is to use `sct.grab` and not `cv2.imread`. This returns True. 

```
import cv2
import numpy as np
import os
os.chdir("C:/GP/")
os.getcwd()
file = 'test.jpg'
im1 = cv2.imread(file)[:, :, ::-1]
im2 = cv2.cvtColor(cv2.imread(file), cv2.COLOR_BGR2RGB)
print(np.allclose(im1, im2))
```

However this returns `ValueError: operands could not be broadcast together with shapes (500,300,4) (500,300,3) `

```
from mss import mss
sct = mss()
monitor = {"top": 160, "left": 160, "width": 300, "height": 500}
screen = np.array(sct.grab(monitor))

cv2.imshow("img",screen)
if cv2.waitKey(20000) & 0xFF == ord('q'):
    cv2.destroyAllWindows()

screen.shape
im1 = screen[:, :, ::-1]
im2 = cv2.cvtColor(screen, cv2.COLOR_BGR2RGB)
print(np.allclose(im1, im2))
```

so now I have this equal to `screen`. This image is displaying colors correctly.
`cv2.imshow("screen",screen)`
![image](https://user-images.githubusercontent.com/18371712/102821120-cc06eb80-43d6-11eb-910f-2acccd89dd81.png)

Problem is, AFTER passing this `screen` image as argument to `model`, then displaying the **result**, the color channel has changed.
```
import torch
model = torch.hub.load('ultralytics/yolov5', 'custom', path_or_model='runs/train/exp29/weights/best.pt')
#model = model.fuse()  # for PIL/cv2/np inputs and NMS
model = model.autoshape()  # for PIL/cv2/np inputs and NMS
result = model(screen, size=400) 
result.display(save=False, show=True, pprint= True)
```
![image](https://user-images.githubusercontent.com/18371712/102821521-84349400-43d7-11eb-8a0f-833ddea61124.png)

And I have to convert `screen` using the above mentioned method before passing it to `model` otherwise the accuracy is very low, since the color channel of the input seems to have been not correctly fed to `model()` somehow.

Displaying these two images shows the difference in color channels. Only the second solution brings my model accuracy as well as the `result.display` back to normal, not the first one as advised.

```
im1 = screen[:, :, ::-1]
im2 = cv2.cvtColor(screen, cv2.COLOR_BGR2RGB)

```
Cheers.

**Comment by wb-08** [comment]
Try:

**Comment by cakiryusuff** [comment]
> Try: result = model(screen, size=640) cv2.imshow('Screen', result.render()[0])

This worked, thanks.

**Comment by glenn-jocher** [comment]
@cakiryusuff you're welcome! If you have any more questions or need further assistance, feel free to ask. Good luck with your project!
