### ISSUE TITLE
How to configure channel size

### ISSUE THREAD

**Issue by thhart** [ultralytics/yolov5#1739]
I checked the training tutorial but could not find a central configuration setting to specify the input channel size for training. Is this possible within yaml files or is it necessary to change something in yolo.py for instance?
I tried to put ch into yaml but it looks like not being parsed.

**Comment by glenn-jocher** [comment]
@thhart you can create a YOLOv5 model with non-default channel size with PyTorch Hub. See PyTorch Hub tutorial:
https://docs.ultralytics.com/yolov5

The training dataloader defaults to 3 ch images, you'd have to manually modify it to your needs:
https://github.com/ultralytics/yolov5/blob/ab0db8d1049409840c587564fc5fb4680acf0d07/utils/datasets.py#L336

**Comment by glenn-jocher** [comment]
@thhart by the way, `yaml['ch']` fields are not currently used,  but you could modify yolo.py directly to use these similar to now `yaml['nc']` is used or overridden.

https://github.com/ultralytics/yolov5/blob/ab0db8d1049409840c587564fc5fb4680acf0d07/models/yolo.py#L69-L87

**Comment by glenn-jocher** [comment]
@thhart I would perhaps update yolo.py L84 to this to allow you to use a `ch` field in the yaml.

```python
        self.model, self.save = parse_model(deepcopy(self.yaml), ch=[self.yaml.get('ch', ch)])  # model, savelist
```

**Comment by glenn-jocher** [comment]
@thhart PR #1741 is merged now, adding support for optional input channel definition in model yaml files, i.e.

```yaml
# parameters
nc: 80  # number of classes
ch: 10  # input channels  <------------------------
depth_multiple: 0.33  # model depth multiple
width_multiple: 0.50  # layer channel multiple
```

Tested with 1, 3 and 10 channel models.

**Comment by wangfurong123** [comment]
Hello, I used the YOLOv5 model to train a single-channel image, but it was unsuccessful. How do I modify the data loader part in the datasets.py file? Sincerely hope you can answer, thank you.

**Comment by wangfurong123** [comment]
Hello, I used the YOLOv5 model to train a single-channel image, but it was unsuccessful. How can I modify the data loader part in the datasets.py file to train a single-channel image? Sincerely hope you can answer, thank you.

**Comment by glenn-jocher** [comment]
@wangfurong123 dataloaders are in datasets.py:
https://github.com/ultralytics/yolov5/blob/7a39803476f8ae55fb25ed93a400a3bba998d5e7/utils/datasets.py#L377-L378

**Comment by pourmand1376** [comment]
> @thhart PR #1741 is merged now, adding support for optional input channel definition in model yaml files, i.e.
> 
> ```yaml
> # parameters
> nc: 80  # number of classes
> ch: 10  # input channels  <------------------------
> depth_multiple: 0.33  # model depth multiple
> width_multiple: 0.50  # layer channel multiple
> ```
> 
> Tested with 1, 3 and 10 channel models.

What type of image do you recommend for multi-channel input?

**Comment by xiaoche-24** [comment]
I have successfully obtained a six-channel input pt model. How can I convert it to an onnx model? What modifications need to be made to export.py?I ran export.py directly and reported the following error:
Traceback (most recent call last):
  File "export.py", line 653, in <module>
    main(opt)
  File "export.py", line 648, in main
    run(**vars(opt))
  File "/home/lixiaojun/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "export.py", line 549, in run
    y = model(im)  # dry runs
  File "/home/lixiaojun/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lixiaojun/workfile/yolov5-master/models/yolo.py", line 245, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "/home/lixiaojun/workfile/yolov5-master/models/yolo.py", line 121, in _forward_once
    x = m(x)  # run
  File "/home/lixiaojun/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lixiaojun/workfile/yolov5-master/models/common.py", line 3013, in forward_fuse
    return self.act(self.conv(x))
  File "/home/lixiaojun/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lixiaojun/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/lixiaojun/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [32, 3, 6, 6], expected input[1, 6, 640, 640] to have 3 channels, but got 6 channels instead

**Comment by glenn-jocher** [comment]
Hi @xiaoche-24! To convert a six-channel input PyTorch model to an ONNX model, you need to make some modifications in the `export.py` script.

You received the error because the weights of one of the layers in your model have a fixed size of [32, 3, 6, 6]. This implies that it expects an input with 3 channels, but your input has 6 channels.

To resolve this issue, you need to modify the `export.py` script. Specifically, you should update the line where the model is defined to handle the case of your six-channel input. You can modify the `parse_model` function in `models/yolo.py` to accept a custom number of input channels.

Make sure to change the default value of `ch` to 6 (or the number of channels in your input) and re-run the export script.

Let me know if you have any further questions or need additional assistance!

**Comment by wq247726404** [comment]
> I have successfully obtained a six-channel input pt model. How can I convert it to an onnx model? What modifications need to be made to export.py?I ran export.py directly and reported the following error: Traceback (most recent call last): File "export.py", line 653, in main(opt) File "export.py", line 648, in main run(**vars(opt)) File "/home/lixiaojun/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context return func(*args, **kwargs) File "export.py", line 549, in run y = model(im) # dry runs File "/home/lixiaojun/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl return forward_call(*input, **kwargs) File "/home/lixiaojun/workfile/yolov5-master/models/yolo.py", line 245, in forward return self._forward_once(x, profile, visualize) # single-scale inference, train File "/home/lixiaojun/workfile/yolov5-master/models/yolo.py", line 121, in _forward_once x = m(x) # run File "/home/lixiaojun/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl return forward_call(*input, **kwargs) File "/home/lixiaojun/workfile/yolov5-master/models/common.py", line 3013, in forward_fuse return self.act(self.conv(x)) File "/home/lixiaojun/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl return forward_call(*input, **kwargs) File "/home/lixiaojun/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 463, in forward return self._conv_forward(input, self.weight, self.bias) File "/home/lixiaojun/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward return F.conv2d(input, weight, bias, self.stride, RuntimeError: Given groups=1, weight of size [32, 3, 6, 6], expected input[1, 6, 640, 640] to have 3 channels, but got 6 channels instead

Hi bro, can I tweet you to ask some questions?

**Comment by xiaoche-24** [comment]
> > I have successfully obtained a six-channel input pt model. How can I convert it to an onnx model? What modifications need to be made to export.py?I ran export.py directly and reported the following error: Traceback (most recent call last): File "export.py", line 653, in main(opt) File "export.py", line 648, in main run(**vars(opt)) File "/home/lixiaojun/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context return func(*args, **kwargs) File "export.py", line 549, in run y = model(im) # dry runs File "/home/lixiaojun/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl return forward_call(*input, **kwargs) File "/home/lixiaojun/workfile/yolov5-master/models/yolo.py", line 245, in forward return self._forward_once(x, profile, visualize) # single-scale inference, train File "/home/lixiaojun/workfile/yolov5-master/models/yolo.py", line 121, in _forward_once x = m(x) # run File "/home/lixiaojun/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl return forward_call(*input, **kwargs) File "/home/lixiaojun/workfile/yolov5-master/models/common.py", line 3013, in forward_fuse return self.act(self.conv(x)) File "/home/lixiaojun/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl return forward_call(*input, **kwargs) File "/home/lixiaojun/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 463, in forward return self._conv_forward(input, self.weight, self.bias) File "/home/lixiaojun/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward return F.conv2d(input, weight, bias, self.stride, RuntimeError: Given groups=1, weight of size [32, 3, 6, 6], expected input[1, 6, 640, 640] to have 3 channels, but got 6 channels instead
> 
> Hi bro, can I tweet you to ask some questions?

sry，I don't have Twitter.You can ask the question directly here.

**Comment by wq247726404** [comment]
> > > I have successfully obtained a six-channel input pt model. How can I convert it to an onnx model? What modifications need to be made to export.py?I ran export.py directly and reported the following error: Traceback (most recent call last): File "export.py", line 653, in main(opt) File "export.py", line 648, in main run(**vars(opt)) File "/home/lixiaojun/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context return func(*args, **kwargs) File "export.py", line 549, in run y = model(im) # dry runs File "/home/lixiaojun/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl return forward_call(*input, **kwargs) File "/home/lixiaojun/workfile/yolov5-master/models/yolo.py", line 245, in forward return self._forward_once(x, profile, visualize) # single-scale inference, train File "/home/lixiaojun/workfile/yolov5-master/models/yolo.py", line 121, in _forward_once x = m(x) # run File "/home/lixiaojun/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl return forward_call(*input, **kwargs) File "/home/lixiaojun/workfile/yolov5-master/models/common.py", line 3013, in forward_fuse return self.act(self.conv(x)) File "/home/lixiaojun/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl return forward_call(*input, **kwargs) File "/home/lixiaojun/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 463, in forward return self._conv_forward(input, self.weight, self.bias) File "/home/lixiaojun/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward return F.conv2d(input, weight, bias, self.stride, RuntimeError: Given groups=1, weight of size [32, 3, 6, 6], expected input[1, 6, 640, 640] to have 3 channels, but got 6 channels instead
> > 
> > 
> > Hi bro, can I tweet you to ask some questions?
> 
> sry，I don't have Twitter.You can ask the question directly here.

do you have wechat xiongdi

**Comment by glenn-jocher** [comment]
@wq247726404 i'm here to help with any questions you may have regarding YOLOv5! Feel free to ask here and I'll do my best to assist you.

**Comment by Sibgat-Ul** [comment]
hello again, i have been following the [Multispectral](https://docs.ultralytics.com/datasets/detect/coco8-multispectral/#dataset-yaml), where the yaml file looks like:

```yaml
path: ../datasets/coco8-multispectral # dataset root dir
train: images/train # train images (relative to 'path') 4 images
val: images/val # val images (relative to 'path') 4 images
test: # test images (optional)

# Number of multispectral image channels
channels: 10
```

following the above file, i made:
```yaml
channels: 4
nc: 2
train: ./train
val: ./valid
```

but while printing the shape of input of the first layer i see: `torch.Size([1, 3, 256, 256])`

can you guide me on this? I have also followed the guides given on link above to merge the channels.
thanks

**Comment by xiaoche-24** [comment]
> hello again, i have been following the [Multispectral](https://docs.ultralytics.com/datasets/detect/coco8-multispectral/#dataset-yaml), where the yaml file looks like:
> 
> path: ../datasets/coco8-multispectral # dataset root dir
> train: images/train # train images (relative to 'path') 4 images
> val: images/val # val images (relative to 'path') 4 images
> test: # test images (optional)
> 
> # Number of multispectral image channels
> channels: 10
> 
> following the above file, i made:
> 
> channels: 4
> nc: 2
> train: ./train
> val: ./valid
> 
> but while printing the shape of input of the first layer i see: `torch.Size([1, 3, 256, 256])`
> 
> can you guide me on this? I have also followed the guides given on link above to merge the channels. thanks

Modify the ch parameter in the model file.

**Comment by pderrenger** [comment]
@Sibgat-Ul There's confusion between two different YAML files here. You're setting `channels: 4` in your dataset YAML, but to actually change the model's input channels, you need to modify the model YAML file with `ch: 4`.

To properly set up a 4-channel input model:

1. Create your model with the correct channels by either:
   - Adding `ch: 4` to your model YAML file (models/yolov5s.yaml, etc.)
   - Using PyTorch Hub with custom channel specification as mentioned earlier

2. Make sure your dataloader correctly loads 4-channel images:
   - The `LoadImgs` class in datasets.py may need modification to handle your 4-channel format
   - Verify your images are properly stacked/merged as 4-channel tensors

If you've already trained a model with 4 channels but see 3 channels during export, you may need to modify the export script to match your input channels as previously discussed for the 6-channel case.
