### ISSUE TITLE
Yolov5 is too low in accuracy on dataset coco128.zip

### ISSUE THREAD

**Issue by sunsdy2018** [ultralytics/yolov5#1745]
I downloaded yolov5-master yesterday and ran the code according to the link 'https://github.com/ultralytics/yolov5/issues/12', the datased was coco128.zip described in this link. All of the args were almost the same like those in the link. After 200 generations to evolve, the precision was still very low. Was I wrong? 
The screenshot was as follows:
![image](https://user-images.githubusercontent.com/38706610/102715689-1f633600-4312-11eb-89a0-b9a0caf76a15.png)

![image](https://user-images.githubusercontent.com/38706610/102715712-491c5d00-4312-11eb-8394-c79f96169945.png)

**Comment by glenn-jocher** [comment]
@sunsdy2018 hyperparameter evolution is handled in a separate tutorial which you should probably review:
https://docs.ultralytics.com/yolov5

Individual generations have no performance constraints nor expectations, they are random mutations, and there is no point displaying one. If a single instance of a population at a given generation looks poor, there is no conclusion to draw. A child born today may suffer from innumerable genetic diseases even after billions of years of evolution on Earth.

You should instead look at evolve.txt and hyp.evolved.yaml for current best results.
