### ISSUE TITLE
When I run detect.py, I got a prediction of nan.

### ISSUE THREAD

**Issue by Ramsden1** [ultralytics/yolov5#1749]
## ❔Question

I run the detect.py by 

> python detect.py --classes 2 --weights best.py --device 0

The code has no error, but the output image of this code has no bounding box annotated.
Then I tried to print this **pred**,  
> pred = model(img, augment=opt.augment)[0]

I find that the output tensor has a lot of nan values and some float numbers. But when I change device to CPU, this problem appeared.
So now I can only run it by CPU, can anyone tell me where is the wrong?

Thank you.

**Comment by wudashuo** [comment]
Yes, I also found this problem. You can find more details in #1625.
Are you using Windows + Pytorch1.7? If yes:
A bad solution is set `cudnn.benchmark = True`,  this will bring another problem, the results are pretty disastrous, according @glenn-jocher said. 
My solution is install pytorch1.6.0+CU101 by `pip install torch==1.6.0+cu101 torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html`, and there's no need to downgrade your CUDA if you are using CUDA10.2 or CUDA11.x, it works fine with my env(CUDA11.1, Python3.8, Pytorch1.6.0+CU101)

**Comment by Ramsden1** [comment]
> 
> 
> Yes, I also found this problem. You can find more details in #1625.
> Are you using Windows + Pytorch1.7? If yes:
> A bad solution is set `cudnn.benchmark = True`, this will bring another problem, the results are pretty disastrous, according @glenn-jocher said.
> My solution is install pytorch1.6.0+CU101 by `pip install torch==1.6.0+cu101 torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html`, and there's no need to downgrade your CUDA if you are using CUDA10.2 or CUDA11.x, it works fine with my env(CUDA11.1, Python3.8, Pytorch1.6.0+CU101)

Yes, My env is Windows + pytorch1.7 + cuda11.
I change the version of pytorch as you said, and it works for me.
Thank you!
