### ISSUE TITLE
How to draw curve graph like this

### ISSUE THREAD

**Issue by TommyZihao** [ultralytics/yolov5#175]
How to draw curve graph like this
![image](https://user-images.githubusercontent.com/36354458/85372045-d3525700-b563-11ea-8f8a-8fcfc36a7aec.png)

I can only draw graph like this
![image](https://user-images.githubusercontent.com/36354458/85372112-f11fbc00-b563-11ea-85fa-496061e983c0.png)

**Comment by glenn-jocher** [comment]
@TommyZihao you can start by reading the readme before raising issues:
https://github.com/ultralytics/yolov5#reproduce-our-training
