### ISSUE TITLE
FLOPS calculation results inconsistent (reported 13G vs reproduced 17.5G for v5s)

### ISSUE THREAD

**Issue by simon900314** [ultralytics/yolov5#1751]
Hi,

I profiled the yolov5s model and found that the flops are 17.5G, while the repo reported to be 13G. Not sure whether it is a typo.

**Comment by glenn-jocher** [comment]
@simon900314 yes, you've spotted a quirk that we are planning on updating on the next model release, perhaps in a week or two. The current FLOPS shown in the README attempt to reconcile the rectangular inference being done when gathering the statistics, so they multiply the default 640x640 assumed input shaped by 480/640, under the assumption that rectangular inference is saving about 25% of a typical square area from being processed.

This is understandably confusing though, so in the future when we update the table next we will simply provide FLOPS at 640x640. 

TODO: Update FLOPS to 640x640

**Comment by simon900314** [comment]
Thanks for the reponse!

**Comment by glenn-jocher** [comment]
@simon900314 GFLOPS have been updated now with correct values for 640x640 inference with fused models. Removing TODO. Let us know if you spot any other issues!
