### ISSUE TITLE
Export ONNX with CUDA

### ISSUE THREAD

**Issue by IvensaMDH** [ultralytics/yolov5#1755]
## ❔Question
Using export.py to ONNX, and setting device to 'cuda', i receive the following error:

> RuntimeError: Input, output and indices must be on the current device

I have tried `.to(device)` on input and model without success.

Do you have any suggestions on how this issue can be resolved?

**Comment by ymzis69** [comment]
Hello, I also encountered this problem. Do you know how to solve it? Thank you for your reply.
