### ISSUE TITLE
How to change the resolution of a usb camera when running live detection？

### ISSUE THREAD

**Issue by HerrLieber** [ultralytics/yolov5#1757]
## ❔Question

I run the following command on jetson nano:

python3 detect.py --source 0 --weights yolov5s.pt
![runyolov5](https://user-images.githubusercontent.com/58136274/102897728-c528b900-4468-11eb-84dd-a319d1463916.jpg)

As you can see from the image above, the webcam has an input resolution of 2304*1536 and an fps of only 2. But normally the fps should be around 10. So I think the webcam’s input resolution is too high, which causes the inference speed to slow down. So how can I reduce the input resolution of the webcam? Or how can I improve FPS?

And the webcam is Logitech C920 Pro Webcam.

**Comment by glenn-jocher** [comment]
@HerrLieber you might try updating the loadStreams() dataloader and perhaps requesting different cap properties.

https://github.com/ultralytics/yolov5/blob/3004fb5bc17b5eb3f864d38a6fc9dbc18ec24109/utils/datasets.py#L257-L283

**Comment by HerrLieber** [comment]
> @HerrLieber，您可以尝试更新loadStreams（）数据加载器，并可能请求不同的cap属性。
> 
> https://github.com/ultralytics/yolov5/blob/3004fb5bc17b5eb3f864d38a6fc9dbc18ec24109/utils/datasets.py#L257-L283

After I changed the w and h to 800*600 on lines 276 and 277, I managed to change the resolution of the webcam input, thanks for your help!

But at the same time I noticed that the FPS is still 2. Then I changed a few more sets of w*h and the FPS is 2. So I would like to ask if the FPS is locked at 2? If so, how can I change the locked FPS and if not, how can I increase the FPS?

**Comment by HerrLieber** [comment]
> @HerrLieber you might try updating the loadStreams() dataloader and perhaps requesting different cap properties.
> 
> https://github.com/ultralytics/yolov5/blob/3004fb5bc17b5eb3f864d38a6fc9dbc18ec24109/utils/datasets.py#L257-L283

After I changed the w and h to 800*600 on lines 276 and 277, I managed to change the resolution of the webcam input, thanks for your help!

I noticed that when I run detect.py, I don't need to load the --models in the parameters (I need to load my own models file (**.yaml) when training my own dataset), so I'm wondering if the parameters I'm training, such as the number of categories etc., are already loaded when I load the weights file (**.pt) --weights that I've trained.

**Comment by glenn-jocher** [comment]
@HerrLieber YOLOv5 *.pt files are standalone models that can operate independently for inference, nothing else is needed. model yaml files are used to create a new YOLOv5 model which is randomly initialized (i.e. for training).

```bash
detect.py --weights yolov5_custom.pt
```
