### ISSUE TITLE
path for validation directory in yolov5/data/coco128.yaml 

### ISSUE THREAD

**Issue by tayyabmujahid** [ultralytics/yolov5#1758]
## ❔Question
is the line 14 in coco128.yaml which lists the directory for validation images correct?
`14: val: ../coco128/images/train2017/  # 128 images`

**Comment by glenn-jocher** [comment]
@tayyabmujahid yes everything is correct.

Note that COCO128 trains and tests on the same images simply to validate the training pipeline by proving that overtraining is possible. Real-world ML datasets should point to independent val sets, like voc.yaml and coco.yaml.

**Comment by tayyabmujahid** [comment]
@glenn-jocher got it thanks.

**Comment by tayyabmujahid** [comment]
> @tayyabmujahid yes everything is correct.
> 
> Note that COCO128 trains and tests on the same images simply to validate the training pipeline by proving that overtraining is possible. Real-world ML datasets should point to independent val sets, like voc.yaml and coco.yaml.

@glenn-jocher  i have another question why would we want to use overtraining to validate the training pipeline. Why cant we just use the val or test sets
Thanks
