### ISSUE TITLE
Cannot detect large rectangular object. Anchors? 

### ISSUE THREAD

**Issue by yasindagasan** [ultralytics/yolov5#176]
I need help, probably about the anchor sizes.

I have been working with rectangular images which are sized around 1024x128.

I am trying to train a single class object detection model. I am having difficulties getting the large objects detected. I have tried both the auto anchor calculation with k-means as well as the default anchor parameters of the yolov5. Both did not help.

During the initial phases of the training, I see that there are some predictions made on those large ones. However, as the training goes on and the model gets better overall, those detections disappear and the model ends up not detecting those large objects. 

For your better understanding, I wanted to attach the labels.png. I cannot detect objects which have a width size greater than 0.4.  

![image](https://user-images.githubusercontent.com/20746470/85373677-f5090980-b576-11ea-89c4-2683c72c1e45.png)

I am doing rectangular training with the following parameters:

```
python3 train.py \
  --img-size 1024 \
  --batch 8 \
  --epochs 3000 \
  --data ./data/custom/horizontal_23062020.yaml \
  --cfg ./models/custom/horizontal_21062020_l.yaml \
  --weights weights/yolov5l.pt \
  --name horizontal_23062020_l_all_val-45 \
  --cache \
  --rect 
```
I have not observed anything strange with the training logs :
![image](https://user-images.githubusercontent.com/20746470/85374132-aad45800-b577-11ea-90da-9f7c1b6277c7.png)

My anchor adjustment is like the following:
![image](https://user-images.githubusercontent.com/20746470/85376113-a198ba80-b57a-11ea-954a-809e5168d6a4.png)

My question is:

1) How can I get those objects detected? I am okay even with a partial fit of a bounding box on these objects. 

I have previously had this issue with yolov3 but it appeared again with the existence of a similar dataset with large objects. 

I wanted to dig more on this as my colleague used yolov4 and was able to detect those large ones in two pieces. I just used exactly the same anchor boxes used in yolov4, still couldn't get them with yolov5. I like using your repository and want to keep using Yolov5 PyTorch. I am just curious how to solve this issue? 

Any help would be appreciated! I have had this issue for a long time.

**Comment by glenn-jocher** [comment]
@yasindagasan training minimizes losses equitably across labels, not across label space. If you want more equitable performance across the label space, you should provide labels with more evenly distribute across it.

**Comment by ray-lee-94** [comment]
I just meet the same problems
