### ISSUE TITLE
How to tile images on inference with Yolo Object Detection

### ISSUE THREAD

**Issue by NOxDriver** [ultralytics/yolov5#1765]
I've recently trained a custom yolov5 model.

I've researched the technique of tiling, taking a large image and splitting it into 5x5 smaller images, allowing the inference not to take up as much ram as trying to run the inference on the initial large image. However, there is no instruction on how to do this on real-time inference.

Does anyone know how to do tiling on real-time inference?

Also, does it increase the time by the number of tiled images?

**Comment by glenn-jocher** [comment]
@NOxDriver you might want to visit https://github.com/ultralytics/xview-yolov3 for an example of a tiled Dataloader and tiled version of detect.py.

**Comment by YoungjaeDev** [comment]
@glenn-jocher 
Where can I see the tile code exactly?

**Comment by glenn-jocher** [comment]
@youngjae-avikus in xview-yolov3 detect.py and dataloaders. https://github.com/ultralytics/xview-yolov3

You might want to see SAHI-YOLOv5 also for a more recent tiling implementation.
