### ISSUE TITLE
onnx model OPENCV read and detect/test

### ISSUE THREAD

**Issue by erolgerceker** [ultralytics/yolov5#1767]
how can i test onnx model on opencv

**Comment by erolgerceker** [comment]
i got layer error

**Comment by moured** [comment]
Having same issue , did you manage to parse yolo onnx output ? can you share how ?

**Comment by erolgerceker** [comment]
> Having same issue , did you manage to parse yolo onnx output ? can you share how ?

no :(

**Comment by moured** [comment]
> > Having same issue , did you manage to parse yolo onnx output ? can you share how ?
> 
> no :(

Good news, I have solved the issue. Please check my repo : https://github.com/moured/YOLO-ONNX-Parse-Example
