### ISSUE TITLE
output_name of Onnx model doesn't match the result of export.py

### ISSUE THREAD

**Issue by laocan** [ultralytics/yolov5#1768]
## ❔Question
when i load .onnx file to infer:
    onnx_session = onnxruntime.InferenceSession(onnx_path)
    onnx_session.get_outputs()
i get result of output_name:['output', '731', '751'].
but in the export.py, the output_names equals to ['output'],
i dont know why [..., '731', '751']  occur
thx for help.

**Comment by zhu-zhaofei** [comment]
I get the same questions. 0.0
