### ISSUE TITLE
How does the yolov5 model deal with the imbalance of positive and negative samples?

### ISSUE THREAD

**Issue by blueskywwc** [ultralytics/yolov5#1769]
There are many positive samples in the training data, and a few positive samples, and the sample distribution is very unbalanced. In addition to enriching the number of samples, how does the YOLOv5 model deal with this imbalance problem, thank you!

**Comment by glenn-jocher** [comment]
@blueskywwc the imbalance problem is somewhat ameliorated by the use of seperate objectness and classification outputs. Other than that, nothing is used to address the imbalance.

The _class imbalance_ can be several orders of magnitude in COCO between classes, and the seperate _objectness imbalance_ is also several orders of magnitude (between foreground vs background).

**Comment by blueskywwc** [comment]
Thanks, I see

**Comment by young169** [comment]
> 
> 
> Thanks, I see

For the words "positive samples", do you mean that if an area has an object, it is a positive sample, and "negative samples" means that this area doesn't contain an object? If so, have you encountered problem that objects belonging to different classes, and each classes' sample number are highly imbalanced? How can I fix that?

**Comment by glenn-jocher** [comment]
@young169 yes that is correct. I would recommend training normally with all default settings.
