### ISSUE TITLE
Object Detection BBox size 

### ISSUE THREAD

**Issue by LEEGILJUN** [ultralytics/yolov5#1770]
## ❔Question
Hello
Can the size and font size of the box displaying the object be adjusted?
because I made an object box of images file when I run the detect.py
it is very big so It is difficult to confirm that a box is created when several images are overlapped.
Which value can I adjust in which file?
Thank you

**Comment by glenn-jocher** [comment]
@LEEGILJUN plotting functionality in detect.py can be modified here:
https://github.com/ultralytics/yolov5/blob/8a81839cad49c0d3d64b343e78d954f815b4ff91/detect.py#L110-L113
