### ISSUE TITLE
Hello, how can I use yolov5 to detect objects in high-resolution images?

### ISSUE THREAD

**Issue by chr0929** [ultralytics/yolov5#1772]
## ❔Question
Hello, how to use yolov5 to detect objects in high-resolution images? The image resolution is (10000,10000)

**Comment by greeneley** [comment]
Possible. When you train your model, you must resize image with param --img-size (default 640).  If you use a high-resolution image, you'll have a error: CUDA, out of memory.

**Comment by InfiniteLife** [comment]
with such big images, especially if it contains small objects(medical imagine) I can think of only custom sliding window strategy

**Comment by glenn-jocher** [comment]
@chr0929 use a larger GPU or a tiled dataloader and inference pipeline. See our xview repo for the latter:
https://github.com/ultralytics/xview-yolov3

![6](https://user-images.githubusercontent.com/26833433/103104482-64ba8880-45dc-11eb-9d42-4e3d1b736b29.jpg)

**Comment by chr0929** [comment]
@InfiniteLife Thank you for your reply. If resize the image to 640, nothing will be detected. How does the sliding window operate?

**Comment by InfiniteLife** [comment]
@chr0929 basically you just split your 1 big image into a handful of smaller ones. Like if you have 10000x10000 you might want to split it in 100 images with size 1000x1000 without overlap. And treat each crop like it is its own data sample - train network on it. Of course you are cropping your bounding boxes accordingly.  You might want to do this kind of cropping offline(generate data before training) or on the fly, which will provide richier data to the network - because you can pick a lot of random parameters in such data generation, like location and crop size. On inference time you make similar strategy, but as final step you will stitch your detections if you want to.

**Comment by glenn-jocher** [comment]
@InfiniteLife yes this is correct. We use random online cropping in the https://github.com/ultralytics/xview-yolov3 dataloader to allow training at native resolution, and then run inference at native resolution as well by using the same approach in detect.py.

**Comment by Songpenglei123** [comment]
> @InfiniteLife yes this is correct. We use random online cropping in the https://github.com/ultralytics/xview-yolov3 dataloader to allow training at native resolution, and then run inference at native resolution as well by using the same approach in detect.py.

Thank you for your answer, I would like to ask how to add this strategy to the yolov5 project？

**Comment by glenn-jocher** [comment]
@Songpenglei123 see Albumentations integration https://github.com/ultralytics/yolov5/pull/3882 which you can pair with cropping transforms like RandomCrop() and RandomCropNearBBox()
https://albumentations.ai/docs/api_reference/augmentations/crops/transforms/

**Comment by tailtNinjavanVN** [comment]
Sorry @glenn-jocher,

I should use Albumentations when image resolution is what (quality >= 2K or quality >= 3K) ?
Thanks in advanced for your replying!

**Comment by glenn-jocher** [comment]
@tailtNinjavanVN albumentations is suitable for use at any image size large or small.

**Comment by tailtNinjavanVN** [comment]
@glenn-jocher, thanks for your replying!

Could i train + detect 2K/3K resolution images without albumentation on yolov5?

**Comment by glenn-jocher** [comment]
@tailtNinjavanVN yes! Albumentations is optional, if it's installed it's used and if not installed then training proceeds without it. To train at 2k for example:
```
python train.py --img 1920
```

But of course the larger the images the more memory required to train.
