### ISSUE TITLE
Using pytorch tensor as input for a pretrained model

### ISSUE THREAD

**Issue by Danhi1** [ultralytics/yolov5#1774]
## ❔Question
The model works when I'm using PIL images, however for speed considerations I decided to switch to d3dshot-produced pytorch gpu tensors.
I load the model without autoshape(). The tensor I'm forwarding into model is of correct shape(640x640x3), and is located on the gpu. The model errors out with a size mismatch. Please help me understand why.
I can put it through model if I convert the tensor back to numpy array and it works, but I want to do all the calculations on the GPU.

## Additional context
import cv2
import torch
from PIL import Image, ImageDraw

model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True).fuse()
print("MODEL LOADED SUCCESSFULLY")

import d3dshot

d = d3dshot.create(capture_output="pytorch_gpu")
screen = d.screenshot(region = (8, 31, 648, 511))  #640x480 image with default windows offset

#making sure the tensor is created on the gpu
torch.set_default_tensor_type('torch.cuda.FloatTensor')

#padding to needed size
target = torch.zeros(640, 640, 3)
target = target.byte() #the screenshot tensor is of byte type, so we convert this to byte as well

target[:480, :, :] = screen 

#now we need to convert it all to a float tensor
target2 = torch.zeros(640, 640, 3)
target2 = target / 255.0

results = model(target2)

THE ERROR:
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-13-2136e5f29b99> in <module>
----> 1 results = model(target2)

C:\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
    720             result = self._slow_forward(*input, **kwargs)
    721         else:
--> 722             result = self.forward(*input, **kwargs)
    723         for hook in itertools.chain(
    724                 _global_forward_hooks.values(),

~/.cache\torch\hub\ultralytics_yolov5_master\models\yolo.py in forward(self, x, augment, profile)
    121             return torch.cat(y, 1), None  # augmented inference, train
    122         else:
--> 123             return self.forward_once(x, profile)  # single-scale inference, train
    124 
    125     def forward_once(self, x, profile=False):

~/.cache\torch\hub\ultralytics_yolov5_master\models\yolo.py in forward_once(self, x, profile)
    137                 print('%10.1f%10.0f%10.1fms %-40s' % (o, m.np, dt[-1], m.type))
    138 
--> 139             x = m(x)  # run
    140             y.append(x if m.i in self.save else None)  # save output
    141 

C:\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
    720             result = self._slow_forward(*input, **kwargs)
    721         else:
--> 722             result = self.forward(*input, **kwargs)
    723         for hook in itertools.chain(
    724                 _global_forward_hooks.values(),

~/.cache\torch\hub\ultralytics_yolov5_master\models\common.py in forward(self, x)
    107 
    108     def forward(self, x):  # x(b,c,w,h) -> y(b,4c,w/2,h/2)
--> 109         return self.conv(torch.cat([x[..., ::2, ::2], x[..., 1::2, ::2], x[..., ::2, 1::2], x[..., 1::2, 1::2]], 1))
    110 
    111 

RuntimeError: Sizes of tensors must match except in dimension 2. Got 1 and 2 (The offending index is 0)

**Comment by glenn-jocher** [comment]
@Danhi1 your input shape is incorrect for pytorch inputs. See .autoshape() forward() method for acceptable input shapes for each format:

https://github.com/ultralytics/yolov5/blob/8a81839cad49c0d3d64b343e78d954f815b4ff91/models/common.py#L146-L153
