### ISSUE TITLE
ValueError: API key must be 40 characters long, yours was 1

### ISSUE THREAD

**Issue by zhangsong1213** [ultralytics/yolov5#1777]
when i run !wandb login 
i got  ValueError: API key must be 40 characters long, yours was 1
![image](https://user-images.githubusercontent.com/48464621/103131466-da594e00-46db-11eb-8475-61daffd306e5.png)

**Comment by glenn-jocher** [comment]
@zhangsong1213 you can copy and paste from the login site provided by `wandb login` command. CTRL+V to paste the API key, which should be 40 characters as the message says.

**Comment by SebaSilvaS** [comment]
> @zhangsong1213 you can copy and paste from the login site provided by `wandb login` command. CTRL+V to paste the API key, which should be 40 characters as the message says.

Hello, I am also having troubles with wandb logging. CTRL + V does not work, I can not write by hand either. It is not receiving any input at all.
In my particular case I'm running it from the command prompt on Windows 10. I made sure to download the last version of yolov5 (few hours ago).

**Comment by dada1437903138** [comment]
> > @zhangsong1213 you can copy and paste from the login site provided by `wandb login` command. CTRL+V to paste the API key, which should be 40 characters as the message says.
> 
> Hello, I am also having troubles with wandb logging. CTRL + V does not work, I can not write by hand either. It is not receiving any input at all.
> In my particular case I'm running it from the command prompt on Windows 10. I made sure to download the last version of yolov5 (few hours ago).

I have met the same problem bro，have you solved it？

**Comment by SebaSilvaS** [comment]
> I have met the same problem bro，have you solved it？

@dada1437903138 Yes! It seems that just right-clicking pastes the code. Copy code, right-click and hit enter. That worked for me :D

**Comment by sankadivandya** [comment]
> > I have met the same problem bro，have you solved it？
> 
> @dada1437903138 Yes! It seems that just right-clicking pastes the code. Copy code, right-click and hit enter. That worked for me :D

Thank you!!! I was going crazy... :D

**Comment by jiandanhaoba** [comment]
> 

你的可以吗，我的还是不行呢？

**Comment by jiandanhaoba** [comment]
> 

手动输入了40个字符 成功了。。。哭死我

**Comment by sunhuihang** [comment]
> > 
> 
> 手动输入了40个字符 成功了。。。哭死我

shift + insert

**Comment by glenn-jocher** [comment]
@sunhuihang glad to hear that you were able to resolve the issue by manually entering the 40-character API key. Sometimes, certain keyboards or terminal emulators may not properly support keyboard shortcuts like CTRL + V. Another alternative is to use the "shift + insert" shortcut to paste the code. If you encounter any further issues or have any other questions, feel free to ask. Happy coding!

**Comment by haochengxi** [comment]
Don't use Ctrl + V. Use Shift + Insert will solve this problem

**Comment by pderrenger** [comment]
@haochengxi thanks for sharing this helpful tip! For others encountering similar issues, right-clicking in the terminal or using `Shift + Insert` are common Windows paste methods. For more details on W&B integration, see our [Weights & Biases integration guide](https://docs.ultralytics.com/integrations/weights-biases/).
