### ISSUE TITLE
If set some labels = -1, what will happen?

### ISSUE THREAD

**Issue by Nise-2-meet-U** [ultralytics/yolov5#1778]
## ❔Question
There are some very small objects in all kinds of datasets, which will led bad training result. 
In dataloader.py, I put black rect to those boxsize < 1600, and I want get rid those labels accordingly by set labels[i,:] = -1. 
like this:
        else:
            # Load image
            img, (h0, w0), (h, w) = load_image(self, index)
            # Letterbox
            shape = self.batch_shapes[self.batch[index]] if self.rect else self.img_size  # final letterboxed shape
            img, ratio, pad = letterbox(img, shape, auto=False, scaleup=self.augment)
            shapes = (h0, w0), ((h / h0, w / w0), pad)  # for COCO mAP rescaling

            # Load labels
            labels = []
            x = self.labels[index]
            if x.size > 0:
                # Normalized xywh to pixel xyxy format
                labels = x.copy()
                labels[:, 1] = ratio[0] * w * (x[:, 1] - x[:, 3] / 2) + pad[0]  # pad width
                labels[:, 2] = ratio[1] * h * (x[:, 2] - x[:, 4] / 2) + pad[1]  # pad height
                labels[:, 3] = ratio[0] * w * (x[:, 1] + x[:, 3] / 2) + pad[0]
                labels[:, 4] = ratio[1] * h * (x[:, 2] + x[:, 4] / 2) + pad[1]

            **for i in range(len(labels)):
                if ((labels[i, 3] - labels[i, 1]) * (labels[i, 4] - labels[i, 2])) < 1600:
                    cv2.rectangle(img, (labels[i, 1], labels[i, 2]), (labels[i, 3], labels[i, 4]), (0, 0, 0), -1)
                    labels[i,:] = -1**

Is there a better way to get rid those boxes and labels in the trainning process?
@glenn-jocher
## Additional context
![1](https://user-images.githubusercontent.com/75665054/103136926-86606080-46ff-11eb-9d7c-5d7dbe18f979.png)

**Comment by glenn-jocher** [comment]
@Nise-2-meet-U you are referring to label candidate criteria. We don't have a parameterized system for defining candidate criteria, these are instead hard coded into the dataloader at the moment. You can modify or update this functionality to incorporate your custom requirements here.
https://github.com/ultralytics/yolov5/blob/c0ffcdf998aa0e00f1f39e79ee8124b74b53d23f/utils/datasets.py#L814-L820

**Comment by Nise-2-meet-U** [comment]
> @Nise-2-meet-U you are referring to label candidate criteria. We don't have a parameterized system for defining candidate criteria, these are instead hard coded into the dataloader at the moment. You can modify or update this functionality to incorporate your custom requirements here.
> https://github.com/ultralytics/yolov5/blob/c0ffcdf998aa0e00f1f39e79ee8124b74b53d23f/utils/datasets.py#L814-L820

Thanks for replying!
