### ISSUE TITLE
Associative Embedding for Sub Objects in Yolov5

### ISSUE THREAD

**Issue by noorahmedds** [ultralytics/yolov5#1780]
## ❔Question
I read the corner net paper and was thinking whether it would be appropriate to implement something similar in the yolov5 repo. What i want to do is for the model to **generate embeddings** for each predicted anchor box (ncls+5+1) and minimize the distance between this embedding for the same pair (face and body in my case) and maximise the distance between opposing pair (face of person1 and body of person2). Am i asking too much from the model or is this a valid solution? I have trained a baseline model with mean pull push losses but Im getting some sad looking results. Any idea if this is the right direction?

**Comment by glenn-jocher** [comment]
@noorahmedds this is outside of my specialty so I can't really offer any advice here. I briefly reviewed the papers though and am not sure if the proposed solutions are viable pathways for improvement. If you have any success please let us know.

**Comment by noorahmedds** [comment]
Yeah will update this thread when i progress.
