### ISSUE TITLE
'cap' object  is not self. initialized

### ISSUE THREAD

**Issue by rohandubey** [ultralytics/yolov5#1781]
## 🐛 Bug
cap.release() function should be embedded in utils.dataset as closing of a webcam will governed by utils.dataset not detect.py.
But on running utils.dataset, it was throwing off error saying cap is not a a self declared variable in Class LoadStream.

## To Reproduce (REQUIRED)

Input:
In utils.dataset() file, class LoadStream:
```
def __next__(self):
        self.count += 1
        img0 = self.imgs.copy()
        if cv2.waitKey(1) == ord('q'):  # q to quit
            self.cap.release()
            cv2.destroyAllWindows()
            raise StopIteration
```

Output:
```
self.cap.release()
AttributeError: 'LoadStreams' object has no attribute 'cap'
```

## Expected behavior
utlis.dataset should effectively be able to release camera.

**Comment by glenn-jocher** [comment]
@rohandubey LoadStreams initiates one or more more daemon threads for multi-source streaming. The cv2 cap objects are inside each thread, they are not properties of the dataloader as you note.

**Comment by rohandubey** [comment]
@glenn-jocher The opening and closing of cv2 cap object is governed by the dataloader class,  and currently it doesn't release the camera as "cap" is not exclusively defined inside, thus not freeing up the camera pointer.
By defining cap as self.cap we dont ned extra command of cv2.waitkey() in detect.py and it closes and frees the camera self in datasets.py thus reducing code and making it efficient.
If it helps, i can can suggest the changes more specifically.
Thank you
