### ISSUE TITLE
The mAP value varies greatly when test.py is run

### ISSUE THREAD

**Issue by caixiiaoyang** [ultralytics/yolov5#1782]
## ❔Question

 when I run “python test.py --weights runs/train/exp12/weights/last.pt --data data/ship.yaml  --task test --save-json”，I get the following results：
Scanning '/home/caixy/yolov5/shipdata/labels/test.cache' for images and labels... 980 found, 0 missing, 62 empty, 0 corrupted: **Class        Images        Targets              P              R          ###  mAP@.5 ###  mAP@.5:.95:** 
   **all             980            1.98e+03            0.719    0.802        ###  0.773  ###  0.575**

Speed: 11.3/0.9/12.2 ms inference/NMS/total per 640x640 image at batch-size 32

Evaluating pycocotools mAP... saving runs/test/exp5/last_predictions.json...
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
Loading and preparing results...
DONE (t=0.02s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=1.29s).
Accumulating evaluation results...
DONE (t=0.27s).
 ### **Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.023**
 ### **Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.029**
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.025
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.001
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.007
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.034
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.235
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.298
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.299
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.053
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.210
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.309
Results saved to runs/test/exp5
Why is there such a big difference between the above mAP value and the below？

**Comment by glenn-jocher** [comment]
@caixiiaoyang the issue probably lies in the pycocotools annotations file you are supplying.

**Comment by caixiiaoyang** [comment]
> @caixiiaoyang the issue probably lies in the pycocotools annotations file you are supplying.

What is the specific format of the annotation file? I doubt that there is a problem with the predicted JSON file format generated by the program.
The JSON prediction result generated by that program are as follow:
[{"image_id": 582, "category_id": 0, "bbox": [121.404, 74.144, 506.678, 123.63], "score": 0.96094}, {"image_id": 582, "category_id": 3, "bbox": [354.795, 8.219, 518.205, 32.705], "score": 0.10358}, {"image_id": 582, "category_id": 3, "bbox": [569.178, 10.445, 303.822, 29.452], "score": 0.01767}, {"image_id": 582, "category_id": 3, "bbox": [3.253, 8.219, 326.199, 21.747], "score": 0.00551}, {"image_id": 582, "category_id": 3, "bbox": [0.0, 6.336, 560.274, 34.76], "score": 0.00386}, {"image_id": 582, "category_id": 5, "bbox": [121.404, 74.144, 506.678, 123.63], "score": 0.00309}, {"image_id": 582, "category_id": 3, "bbox": [305.137, 10.36, 288.356, 22.603], "score": 0.00289}, {"image_id": 582, "category_id": 3, "bbox": [121.404, 74.658, 505.993, 123.288], "score": 0.00192}, {"image_id": 582, "category_id": 3, "bbox": [194.007, 11.216, 288.87, 21.062], "score": 0.00189}, {"image_id": 582, "category_id": 3, "bbox": [134.418, 9.075, 279.966, 21.233], "score": 0.00159}, {"image_id": 582, "category_id": 2, "bbox": [121.404, 74.658, 505.993, 123.288], "score": 0.00149}, {"image_id": 582, "category_id": 3, "bbox": [266.096, 10.959, 163.014, 20.377], "score": 0.00144}, {"image_id": 194, "category_id": 3, "bbox": [879.657, 219.734, 41.82, 23.073], "score": 0.00164}, {"image_id": 194, "category_id": 5, "bbox": [912.103, 237.399, 9.897, 9.734], "score": 0.00125}, {"image_id": 194, "category_id": 3, "bbox": [876.773, 204.592, 44.704, 37.494], "score": 0.00109}, {"image_id": 194, "category_id": 5, "bbox": [913.545, 230.549, 8.455, 14.781], "score": 0.00105}, {"image_id": 194, "category_id": 5, "bbox": [913.545, 240.103, 8.455, 14.06], "score": 0.00101}, {"image_id": 876, "category_id": 0, "bbox": [8.987, 11.234, 463.437, 159.526], "score": 0.94141}, {"image_id": 876, "category_id": 3, "bbox": [0.391, 114.199, 60.86, 46.598], "score": 0.00758}, ..........
The Real JSON format tag are as follows：
{
    "images": [
        {
            "file_name": "00303.jpg",
            "id": 1,
            "height": 333,
            "width": 500
        },
        {
            "file_name": "04841.jpg",
            "id": 2,
            "height": 332,
            "width": 500
        },
        {
            "file_name": "00037.jpg",
            "id": 3,
            "height": 343,
            "width": 500
        },......
 "annotations": [
        {
            "id": 1,
            "image_id": 1,
            "bbox": [
                15,
                110,
                302,
                93
            ],
            "category_id": 6,
            "area": 28086,
            "iscrowd": 0
        },
        {
            "id": 2,
            "image_id": 1,
            "bbox": [
                49,
                112,
                427,
                87
            ],
            "category_id": 6,
            "area": 37149,
            "iscrowd": 0
        },
        {
            "id": 3,
            "image_id": 2,
            "bbox": [
                45,
                111,
                396,
                127
            ],
            "category_id": 4,
            "area": 50292,
            "iscrowd": 0
        },
        {
            "id": 4,
            "image_id": 3,
            "bbox": [
                249,
                147,
                115,
                119
            ],
            "category_id": 6,
            "area": 13685,
            "iscrowd": 0
        },
        {
            "id": 5,
            "image_id": 3,
            "bbox": [
                0,
                157,
                214,
                103
            ],
            "category_id": 6,
            "area": 22042,
            "iscrowd": 0
        },
        {
            "id": 6,
            "image_id": 3,
            "bbox": [
                149,
                45,
                351,
                213
            ],
            "category_id": 6,
            "area": 74763,
            "iscrowd": 0
        },
        {
            "id": 7,
            "image_id": 4,
            "bbox": [
                1546,
                1949,
                2269,
                438
            ],
            "category_id": 2,
            "area": 993822,
            "iscrowd": 0
        },
        {
            "id": 8,
            "image_id": 4,
            "bbox": [
                658,
                2086,
                739,
                276
            ],
            "category_id": 2,
            "area": 203964,
            "iscrowd": 0
        },
        {
            "id": 9,
            "image_id": 5,
            "bbox": [
                222,
                192,
                222,
                369
            ],
            "category_id": 5,
            "area": 81918,
            "iscrowd": 0
        },
        {
            "id": 10,
            "image_id": 6,
            "bbox": [
                4,
                0,
                282,
                287
            ],
            "category_id": 6,
            "area": 80934,
            "iscrowd": 0
        },.......
 "categories": [
        {
            "id": 1,
            "name": "liner"
        },
        {
            "id": 2,
            "name": "container ship"
        },
        {
            "id": 3,
            "name": "bulk carrier"
        },
        {
            "id": 4,
            "name": "island reef"
        },
        {
            "id": 5,
            "name": "sailboat"
        },
        {
            "id": 6,
            "name": "other ship"
        }

**Comment by glenn-jocher** [comment]
@caixiiaoyang predictions json is correct. To use pycocotools with a custom dataset you must supply your own labels json file.
