### ISSUE TITLE
How to cite YOLOv5?

### ISSUE THREAD

**Issue by a-esp-1** [ultralytics/yolov5#1784]
## ❔Question

Hi @glenn-jocher ,

I'm using YOLOv5 for my thesis and I need to cite it. Do you think this is the correct way cosidering thre isn't a official paper?

@software{glenn_jocher_2020_4154370,
  author       = {Glenn Jocher},
  title        = {{ultralytics/yolov5: v3.1 - Bug Fixes and 
                   Performance Improvements}},
  month        = oct,
  year         = 2020,
  publisher    = {Zenodo},
  version      = {v3.1},
  doi          = {10.5281/zenodo.4154370},
  url          = {https://doi.org/10.5281/zenodo.4154370},
  howpublished    = {\url{https://github.com/ultralytics/yolov5}}
}

**Comment by glenn-jocher** [comment]
@a-esp-1 hi thanks for asking! We aim to publish a short paper to arxiv soon. In the meantime please see https://doi.org/10.5281/zenodo.3908559 for DOI to cite this repo directory, and where you can also find bibtex and other exportable citation formats.

[![DOI](https://zenodo.org/badge/264818686.svg)](https://zenodo.org/badge/latestdoi/264818686)

What you have there seems to fit well with the bibtex exported format here:
https://zenodo.org/record/4154370/export/hx#.X-eTv2T0lsY

**Comment by MorphSeur** [comment]
Hi @glenn-jocher,
Can I know please if you published the ArXiv paper in order to cite YOLOv5?
Many thanks!

**Comment by adamjstewart** [comment]
YOLOv5 paper on arXiv: https://arxiv.org/abs/2407.20892

**Comment by pderrenger** [comment]
@MorphSeur @adamjstewart Thanks Adam for sharing the arXiv paper link! Yes, the YOLOv5 paper is now available and can be used for proper academic citation. This should provide the official reference you were looking for instead of relying solely on the Zenodo DOI.
