### ISSUE TITLE
F1 score not printed in test.py

### ISSUE THREAD

**Issue by zigiiprens** [ultralytics/yolov5#1785]
Hello,

I am reporting an issue about the not printed `F1 score` in `test.py`. Here, we can best see this, there is 6 variable tags plotted but 7 variables need to be plotted.

![Screenshot from 2020-12-27 00-17-10](https://user-images.githubusercontent.com/29894513/103159364-a6645280-47d9-11eb-87a6-97212e09c8ff.png)

**Comment by glenn-jocher** [comment]
F1 is computed but not displayed to screen as it is not a common metric. You can customize test.py to print this out in your own code if you'd like, but I don't think we want to print this metric out in master.

**Comment by zigiiprens** [comment]
Thank you, but since we compute the metrics, why not printing it. It is just my opinion.
- why do you think that it is not necessary?
- how do I customize it to print it out? It is only need in the 96's line?

**Comment by glenn-jocher** [comment]
@zigiiprens we simply don't receive a lot of requests for it. It's also quite simple to calculate provided the displayed P and R values, thereby making it somewhat redundant. See https://en.wikipedia.org/wiki/F-score

In python you can print any value with `print(value)`

**Comment by zigiiprens** [comment]
😂 Thank you for your advice.
