### ISSUE TITLE
Load custom model with pytorch hub

### ISSUE THREAD

**Issue by BruceYangxl** [ultralytics/yolov5#1787]
## ❔Runing codes:  torch.hub.load('ultralytics/yolov5', 'custom', path_or_model='best.pt'),  will raise an error "RuntimeError: Cannot find callable custom in hubconf".
But it runs OK,  wiht the code " model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)"

**Comment by glenn-jocher** [comment]
@BruceYangxl your cache is out of date (you are using old code). use force_reload=True as shown in PyTorch Hub tutorial:
https://docs.ultralytics.com/yolov5

### Force Reload
If you run into problems with the above steps, setting `force_reload=True` may help by discarding the existing cache and force a fresh download of the latest YOLOv5 version from PyTorch Hub.
```python
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True, force_reload=True)  # force reload
```

**Comment by BruceYangxl** [comment]
@glenn-jocher Thank you very much! it is in fact that my cache is out of date.

**Comment by I-am-vishalmaurya** [comment]
RuntimeError: Cannot find callable custom_yolov5s in hubconf
![Screenshot 2021-11-15 200447](https://user-images.githubusercontent.com/57991538/141799893-f20f8aff-5b87-4cde-8ae4-506dc4647dd7.png)
