### ISSUE TITLE
@glenn best practices for running trained YOLOv5 models in new python environments is to use PyTorch Hub. See PyTorch Hub Tutorial:

### ISSUE THREAD

**Issue by BruceYangxl** [ultralytics/yolov5#1789]
@glenn  but when I use "torch.hub.load" to load my own model weights, it raises an error "RuntimeError: Cannot find callable custom in hubconf"

**Comment by glenn-jocher** [comment]
@BruceYangxl your cache is out of date (you are using old code). use force_reload=True as shown in PyTorch Hub tutorial:
https://docs.ultralytics.com/yolov5

### Force Reload
If you run into problems with the above steps, setting `force_reload=True` may help by discarding the existing cache and force a fresh download of the latest YOLOv5 version from PyTorch Hub.
```python
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True, force_reload=True)  # force reload
```
