### ISSUE TITLE
can not use torchscript convert model

### ISSUE THREAD

**Issue by JiaoPaner** [ultralytics/yolov5#179]
I use torchscript convert model ,has some errors :

```
RuntimeError: Only tensors or tuples of tensors can be output from traced functions (getOutput at ../torch/csrc/jit/tracer.cpp:212).
```

my codes as follows:<br>
```
model = torch.load("weights/yolov5s.pt", map_location="cpu")['model']
model.to("cpu").eval()
example = torch.rand(1, 3, 224, 224).cpu()
traced_script_module = torch.jit.trace(model, example)
output = traced_script_module(torch.ones(1,3,224,224).cpu())
traced_script_module.save('yolov5s-trace.pt')
print(output)
```

**Comment by glenn-jocher** [comment]
@JiaoPaner torchscript is not supported. Feel free to submit a PR for it.

**Comment by jakepoz** [comment]
I was able to successfully export this model to TorchScript with the following modifications to the `onnx_export.py` script:

https://gist.github.com/jakepoz/eb36163814a8f1b6ceb31e8addbba270

**Comment by glenn-jocher** [comment]
@jakepoz thanks buddy. Could you submit a PR with your additions for torchscript export? Might help a lot of people. Thanks!
