### ISSUE TITLE
correlogram for predicted bounding boxes

### ISSUE THREAD

**Issue by jeff42e** [ultralytics/yolov5#1797]
As far as I understood, the correlogram plot in yolov5 is made to show how the input images and its bounding box details look like. I wanted to ask if there is any piece of code where I can also have the same correlogram analysis on my predicted bounding box data? In order to make a first rough comparison about the distribution, it would be very useful

**Comment by glenn-jocher** [comment]
@jeff42e that's not a bad idea. You'd have to accumulate your predictions in the same format as the labels, then you simply pass them to plot_labels().

https://github.com/ultralytics/yolov5/blob/73cf75faa848cb6c7cd8ff1b192ad341098c042c/utils/plots.py#L256-L257
