### ISSUE TITLE
Is it useful to uncomment the code 'a += random.choice([-180, -90, 0, 90])' in line 747 of datasets.py?

### ISSUE THREAD

**Issue by universewill** [ultralytics/yolov5#1798]
I want to rotate the image and target (-90,0,90, 180) degrees for augmentation.
Is it enough to uncomment the code in line 747 of datasets.py?

Will the targets' rect be rotated accordinglly and correctly?

**Comment by glenn-jocher** [comment]
@universewill yes that will work well! You can observe the result in your train jpgs.
