### ISSUE TITLE
can load the trained model in CPU ( using opencv ) ?

### ISSUE THREAD

**Issue by vishnukv64** [ultralytics/yolov5#180]
## 🚀 Feature
how to load the trained model via a cpu and do inference?

## Motivation
Loading the model in a CPU and do inference probably using opencv or using other methods

**Comment by glenn-jocher** [comment]
@vishnukv64 cpu loading is the default action currently if no gpu is detected on your system:

```
(env1) glennjocher@Glenns-MBP yolov5 % python detect.py
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.4, device='', fourcc='mp4v', img_size=640, iou_thres=0.5, output='inference/output', save_txt=False, source='inference/images', view_img=False, weights='weights/yolov5s.pt')
Using CPU

image 1/2 inference/images/bus.jpg: 640x512 4 persons, 1 buss, Done. (0.373s)
image 2/2 inference/images/zidane.jpg: 384x640 2 persons, 1 ties, Done. (0.291s)
Results saved to /Users/glennjocher/PycharmProjects/yolov5/inference/output
Done. (0.842s)
(env1) glennjocher@Glenns-MBP yolov5 % 

```

**Comment by vishnukv64** [comment]
Thanks bro!! So we need pytorch ( that's the only dependency )

**Comment by glenn-jocher** [comment]
@vishnukv64 see https://github.com/ultralytics/yolov5#requirements

Recommend you start with the colab notebook, its the easiest way to get started playing with things.

**Comment by glenn-jocher** [comment]
@vishnukv64 actually, if you use pytorch hub you don't even need to clone this repo. See https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading

**Comment by vishnukv64** [comment]
@glenn-jocher  Can i load my trained model in pytorch hub and use it? or its only available for pre trained models on cooc dataset?

**Comment by glenn-jocher** [comment]
@vishnukv64 you can do anything you want if you work enough at it.

**Comment by vishnukv64** [comment]
# @glenn-jocher  thank you for your help bro!!
