### ISSUE TITLE
When training my custom data，object、cls、total loss become NAN after about 3 epochs

### ISSUE THREAD

**Issue by cloud-zZ** [ultralytics/yolov5#1801]
## Additional context
![image](https://user-images.githubusercontent.com/28640968/103262814-f6f9cc80-49e0-11eb-9cec-302bc4b34517.png)

**Comment by jaqub-manuel** [comment]
@cloud-zZ you dont have any test dataset because your targets seem 0 and corrupted data...Follow instructions for custom dataset training...

**Comment by cloud-zZ** [comment]
> @cloud-zZ you dont have any test dataset because your targets seem 0 and corrupted data...Follow instructions for custom dataset training...

thanks，and i found the batchsize I set is too big....change to a smaller one then problem solved.
