### ISSUE TITLE
question about yolov5

### ISSUE THREAD

**Issue by wuzuiyuzui** [ultralytics/yolov5#1802]
Hello, I remember you said that the report on yolov5 will be released at the end of this year. Could you tell me the specific time? In addition, I would like to ask if I use the improved yolov5 to publish articles on applications in  industries.

Does this act constitute infringement?

**Comment by glenn-jocher** [comment]
@wuzuiyuzui hi that's perfectly fine, there's no worries with generating your own publications. 

We are running experiments and have not been able to write a publication yet as the results are still improving (see upcoming v4.0 release PR), but I would assume we should have one out sometime in Q1 2021.
