### ISSUE TITLE
Low detection confidences after training for single class

### ISSUE THREAD

**Issue by AzharSindhi** [ultralytics/yolov5#1803]
After training for 480 epochs, results were okay on terminal. However in the inference detected objects have low detection confidences even on training images (not more than 0.5).

This isn't the problem for multi-class, because I have also trained yolov5 for three classes and it gave accurate bounding boxes with good confidence scores.

Besides low detection confidence, the mAP scores of single class are also lower compared to the model trained on three classes.

_(Note that these scores are according to the best confidence threshold for each model found separately: 0.7 for three classes and 0.4 for one class)_
### Three class model scores
<img src="https://user-images.githubusercontent.com/24705300/103277400-b7d07900-49ea-11eb-840c-5da9946c7b45.png" width="400"><img src="https://user-images.githubusercontent.com/24705300/103277411-bdc65a00-49ea-11eb-82b8-2f16f812bd01.png" width="400">
<img src="https://user-images.githubusercontent.com/24705300/103277305-89529e00-49ea-11eb-9e06-5d07d3ff1f2e.png" width="400">

As we can see if we combine outgoing, incoming, and unknown vehicles to single class named vehicle, logically the scores should be close to the class with highest mAP above i.e. outgoing. However the results are as following: 
### Single class model scores
<img src="https://user-images.githubusercontent.com/24705300/103277468-dfbfdc80-49ea-11eb-9217-b3a8be9da677.png" width="400"><img src="https://user-images.githubusercontent.com/24705300/103277475-e3536380-49ea-11eb-80be-f0b9167ac1bb.png" width="400">
<img src="https://user-images.githubusercontent.com/24705300/103277480-e64e5400-49ea-11eb-9c11-1a082c938dfe.png" width="400">

Please comment on why the confidence probability are lower in case of single class. Also what are your views about the scores of two models?

Thank you

### Training Details
**GPU: MSI Gaming X Trio RTX 3090 (24 GB)**

My training bash script is: `python train.py --img 640 --batch 8 --epochs 500 --data actors_1class.yaml --cfg yolov5l.yaml --device 0 --weights '' `

I changed the nc variable to 1 in yolov5l.yaml file. Also modified actors_1class.yaml file accordingly.

**Comment by glenn-jocher** [comment]
@AzharSindhi that's great you've developed your own metrics, but the best way to compare runs is simply to compare them in a common format by using the provided outputs, i.e. a link to your W&B project or overlay them on the same results.png file (by placing both results.txt files in the same folder and running plots.plot_results(save_dir=folder), mAP curves etc.

**Comment by biendltb** [comment]
I found the same issue when comparing Yolov5 detection with my previous model Scaled Yolov4. Yolov5 gives lower detection confidence for classes.

**Comment by glenn-jocher** [comment]
@biendltb thanks for your feedback. YOLOv5 and YOLOv4 have different architectures and training methodologies, so it's expected to see differences in performance. If you need further assistance, feel free to ask!
