### ISSUE TITLE
Failed to run yolov5 using CPU

### ISSUE THREAD

**Issue by KleinXin** [ultralytics/yolov5#1805]
## ❔Question

I am using the latest version of yolov5. 
It is fine to train and run inference using GPU on Ubuntu16.04. But it fails to run inference using CPU although I set '--device cpu'. GPU0 is used with this configuration.

It is also very weird that when setting device to cpu, less GPU memory is used（1.0G instead of 1.3G）.

Any help is appreciated!

**Comment by NanoCode012** [comment]
I was a bit curious, so I trained with device cpu and noticed that 1gb of gpu0 was occupied and a small amount for other gpus . However, the utilization stayed at 0.

Same thing happened for detecting using CPU. However, inference was successful for me. How did you know the inference failed?

**Comment by KleinXin** [comment]
> I was a bit curious, so I trained with device cpu and noticed that 1gb of gpu0 was occupied and a small amount for other gpus . However, the utilization stayed at 0.
> 
> Same thing happened for detecting using CPU. However, inference was successful for me. How did you know the inference failed?

I think running with CPU is failed because I noticed that GPU0 was occupied about 1GB when device option is set to cpu.

After comparing GPU and CPU options, I think maybe data is loaded in GPU whether running in GPU or CPU modes.

It still has some problems in detect.py because the program is not running purely in CPU.

**Comment by glenn-jocher** [comment]
@KleinXin the CI tests run every 24 hours on a CPU only machine, so there is no problem with CPU operation. The full suite of CI tests (below) are also available in Google Colab, and run both on --device 0 and on --device cpu, and I'm not aware of any issue there either. 

If you have a **reproducible** issue, please supply code to reproduce or even better a colab notebook that reproduces your issue. 

```bash
# Unit tests
%%shell
export PYTHONPATH="$PWD"  # to run *.py. files in subdirectories

rm -rf runs  # remove runs/
for m in yolov5s; do  # models
  python train.py --weights $m.pt --epochs 3 --img 320 --device 0  # train pretrained
  python train.py --weights '' --cfg $m.yaml --epochs 3 --img 320 --device 0  # train scratch
  for d in 0 cpu; do  # devices
    python detect.py --weights $m.pt --device $d  # detect official
    python detect.py --weights runs/train/exp/weights/best.pt --device $d  # detect custom
    python test.py --weights $m.pt --device $d # test official
    python test.py --weights runs/train/exp/weights/best.pt --device $d # test custom
  done
  python hubconf.py  # hub
  python models/yolo.py --cfg $m.yaml  # inspect
  python models/export.py --weights $m.pt --img 640 --batch 1  # export
done
```

**Comment by KleinXin** [comment]
> @KleinXin the CI tests run every 24 hours on a CPU only machine, so there is no problem with CPU operation. The full suite of CI tests (below) are also available in Google Colab, and run both on --device 0 and on --device cpu, and I'm not aware of any issue there either.
> 
> If you have a **reproducible** issue, please supply code to reproduce or even better a colab notebook that reproduces your issue.
> 
> ```shell
> # Unit tests
> %%shell
> export PYTHONPATH="$PWD"  # to run *.py. files in subdirectories
> 
> rm -rf runs  # remove runs/
> for m in yolov5s; do  # models
>   python train.py --weights $m.pt --epochs 3 --img 320 --device 0  # train pretrained
>   python train.py --weights '' --cfg $m.yaml --epochs 3 --img 320 --device 0  # train scratch
>   for d in 0 cpu; do  # devices
>     python detect.py --weights $m.pt --device $d  # detect official
>     python detect.py --weights runs/train/exp/weights/best.pt --device $d  # detect custom
>     python test.py --weights $m.pt --device $d # test official
>     python test.py --weights runs/train/exp/weights/best.pt --device $d # test custom
>   done
>   python hubconf.py  # hub
>   python models/yolo.py --cfg $m.yaml  # inspect
>   python models/export.py --weights $m.pt --img 640 --batch 1  # export
> done
> ```

I tried to run detect.py on a CPU only machine. It works fine.

So I think maybe it has some default options in the program that GPU is still used on a machine that has GPU although running mode is set to be cpu.

**Comment by glenn-jocher** [comment]
@KleinXin I'm not understanding the issue. As I said if you have reproducible code to demonstrate the issue, please send it over.

GPU and CPU inference both work perfectly well for me in colab:
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb
<img width="1168" alt="Screen Shot 2020-12-29 at 6 42 18 PM" src="https://user-images.githubusercontent.com/26833433/103326546-ae083f00-4a05-11eb-9904-619f748f80b6.png">

**Comment by NanoCode012** [comment]
@glenn-jocher I think what @KleinXin is trying to say could be as follows.

When detecting as “python detect.py —device cpu”, it would take 1GB of GPU0. Therefore, it is not solely using only CPU. Inference does work!

I notice this as well. I ran “watch -n 1 nvidia-smi” and noticed that GPU memory(with 0 utilization) is used as the program is run.

**Comment by glenn-jocher** [comment]
@NanoCode012 oh interesting. I'm not sure what that means, perhaps torch is checking the cuda hardware as part of it's background tasks on import. There's nothing special about any of the code on CPU-only hardware vs forcing --device cpu on GPU hardware, the two cases are handled identically other than select_device().

**Comment by KleinXin** [comment]
> @glenn-jocher I think what @KleinXin is trying to say could be as follows.
> 
> When detecting as “python detect.py —device cpu”, it would take 1GB of GPU0. Therefore, it is not solely using only CPU. Inference does work!
> 
> I notice this as well. I ran “watch -n 1 nvidia-smi” and noticed that GPU memory(with 0 utilization) is used as the program is run.

Yes, exactly right!

**Comment by KleinXin** [comment]
> @NanoCode012 oh interesting. I'm not sure what that means, perhaps torch is checking the cuda hardware as part of it's background tasks on import. There's nothing special about any of the code on CPU-only hardware vs forcing --device cpu on GPU hardware, the two cases are handled identically other than select_device().

Maybe some default settings of select_device() need to be changed on machines with GPU if one wants to run using only CPU.

**Comment by NanoCode012** [comment]
@glenn-jocher , I was thinking of setting CUDA Env to “” because then it won’t see the GPU.

**Comment by KleinXin** [comment]
@NanoCode012 @glenn-jocher 

After adding os.environ["CUDA_VISIBLE_DEVICES"] = "-1" to detect.py, GPU is not used any more.
