### ISSUE TITLE
batch inference

### ISSUE THREAD

**Issue by simplew2011** [ultralytics/yolov5#1806]
## ❔Question

how can i inference a batch image (such as 10 images) a time.

**Comment by NanoCode012** [comment]
See https://github.com/ultralytics/yolov5#pytorch-hub

**Comment by simplew2011** [comment]
For the same number of images, the total time of batch one-time prediction （PyTorch Hub） and traversing a single prediction, theoretically, will the former take less time than the latter？
In my actual experiment, the latter is faster

**Comment by glenn-jocher** [comment]
Batched inference will always be faster.

<img width="1192" alt="Screen Shot 2020-12-30 at 8 16 34 PM" src="https://user-images.githubusercontent.com/26833433/103394224-027dee00-4adc-11eb-829b-4ef059819167.png">

code:
```python
import torch
from PIL import Image


# Model
device = torch.device('cuda:0')
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True).to(device)

# Images
for f in ['zidane.jpg', 'bus.jpg']:  # download 2 images
    print(f'Downloading {f}...')
    torch.hub.download_url_to_file('https://github.com/ultralytics/yolov5/releases/download/v1.0/' + f, f)
imgs = [Image.open('bus.jpg')]  # batched list of images

# Inference
%timeit [model(imgs) for _ in range(32)]  # batch-size 1 
%timeit model(imgs * 32)  # batch-size 32
```

**Comment by simplew2011** [comment]
I mean using detect.py for signle test and model = torch.hub.load()  for batch test (remove plot process，just model inference process)
The average time consumption of the former is less than that of the latter.

**Comment by glenn-jocher** [comment]
Apples and oranges, different methods can’t be compared.

**Comment by dmoham1476** [comment]
If I create a batch_list of images using img_list.append(img) in the 'for path, img, img0 loop', I get this error when I try to predict
return self.conv(torch.cat([x[..., ::2, ::2], x[..., 1::2, ::2], x[..., ::2, 1::2], x[..., 1::2, 1::2]], 1))
TypeError: list indices must be integers or slices, not tuple
pred = model(img_list*8, augment=augment)[0]

**Comment by nihalsangeeth** [comment]
@dmoham1476 You have to convert the list into a tensor. `pred = model(torch.cat(img_list*8), dim=0), augment=augment)[0]` should work. Not sure if the TorchHub model is automatically doing that. Either way the documentation for batch inference could be clearer.

**Comment by glenn-jocher** [comment]
@nihalsangeeth see PyTorch Hub tutorial for batched inference example:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)


## Detailed Example

This example shows **batched inference** with **PIL** and **OpenCV** image sources. `results` can be **printed** to console, **saved** to `runs/hub`, **showed** to screen on supported environments, and returned as **tensors** or **pandas** dataframes.
```python
import cv2
import torch
from PIL import Image

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Images
for f in ['zidane.jpg', 'bus.jpg']:
    torch.hub.download_url_to_file('https://ultralytics.com/images/' + f, f)  # download 2 images
img1 = Image.open('zidane.jpg')  # PIL image
img2 = cv2.imread('bus.jpg')[..., ::-1]  # OpenCV image (BGR to RGB)
imgs = [img1, img2]  # batch of images

# Inference
results = model(imgs, size=640)  # includes NMS

# Results
results.print()  
results.save()  # or .show()

results.xyxy[0]  # img1 predictions (tensor)
results.pandas().xyxy[0]  # img1 predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 1  433.50  433.50   517.5  714.5    0.687988     27     tie
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```

**Comment by myuvarajmp** [comment]
> @dmoham1476 You have to convert the list into a tensor. `pred = model(torch.cat(img_list*8), dim=0), augment=augment)[0]` should work. Not sure if the TorchHub model is automatically doing that. Either way the documentation for batch inference could be clearer.

Could you please elaborate more on what code changes need to be done in detect.py of yolov5 4.0 to work in batch mode. Consider I have 10 images in a folder and need to see the inference of them as batch.

**Comment by myuvarajmp** [comment]
> @dmoham1476 You have to convert the list into a tensor. `pred = model(torch.cat(img_list*8), dim=0), augment=augment)[0]` should work. Not sure if the TorchHub model is automatically doing that. Either way the documentation for batch inference could be clearer.

Could you please elaborate more on what code changes need to be done in detect.py of yolov5 4.0 to work in batch mode. Consider I have 10 images in a folder and need to see the inference of them as batch.

**Comment by glenn-jocher** [comment]
@myuvarajmp see PyTorch Hub tutorial for batched inference example:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)


## Detailed Example

This example shows **batched inference** with **PIL** and **OpenCV** image sources. `results` can be **printed** to console, **saved** to `runs/hub`, **showed** to screen on supported environments, and returned as **tensors** or **pandas** dataframes.
```python
import cv2
import torch
from PIL import Image

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Images
for f in ['zidane.jpg', 'bus.jpg']:
    torch.hub.download_url_to_file('https://ultralytics.com/images/' + f, f)  # download 2 images
img1 = Image.open('zidane.jpg')  # PIL image
img2 = cv2.imread('bus.jpg')[..., ::-1]  # OpenCV image (BGR to RGB)
imgs = [img1, img2]  # batch of images

# Inference
results = model(imgs, size=640)  # includes NMS

# Results
results.print()  
results.save()  # or .show()

results.xyxy[0]  # img1 predictions (tensor)
results.pandas().xyxy[0]  # img1 predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 1  433.50  433.50   517.5  714.5    0.687988     27     tie
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```

**Comment by santoshmedisetty** [comment]
Just curious, Has anyone tried batch inference with the TensorRT model(.engine)? If so, how can this be done?
