### ISSUE TITLE
Appear RuntimeError when Add the number of anchor

### ISSUE THREAD

**Issue by p110120p1** [ultralytics/yolov5#1807]
Hi, I'm trying to add the number of anchor to make the model benefit the detection project. It works well when I adjust the digital at 3 or 4,but it appears to error when I adjust the digital at 5 or more 
Here's my yolov5s.yaml setup:
``` # parameters
nc: 2  # number of classes
depth_multiple: 0.33  # model depth multiple
width_multiple: 0.50  # layer channel multiple

# anchors
anchors: 5
```

Here's the Error log:

m.anchor_grid[:] = new_anchors.clone().view_as(m.anchor_grid)  # for inference
RuntimeError: shape '[3, 1, 5, 1, 1, 2]' is invalid for input of size 28

**Comment by glenn-jocher** [comment]
@p110120p1 your issue is not reproducible. Anchor definition operates correctly as an integer from the model yaml file, regardless of the integer value. If you have a reproducible issue, please submit a full bug report including code to reproduce. Thank you.

![Screen Shot 2020-12-30 at 10 29 46 AM](https://user-images.githubusercontent.com/26833433/103373628-4942f800-4a8a-11eb-800f-bf5de4a6d128.jpg)

**Comment by p110120p1** [comment]
> @p110120p1 your issue is not reproducible. Anchor definition operates correctly as an integer from the model yaml file, regardless of the integer value. If you have a reproducible issue, please submit a full bug report including code to reproduce. Thank you.
> 
> ![Screen Shot 2020-12-30 at 10 29 46 AM](https://user-images.githubusercontent.com/26833433/103373628-4942f800-4a8a-11eb-800f-bf5de4a6d128.jpg)

Thank you for your kind help, But this error still exists when I change the environment and use Colab,  Here's the Error log screenshots:
![image](https://user-images.githubusercontent.com/54127320/103389772-ddc15f00-4b4b-11eb-8495-e124b49a7d53.png)
And his environment configuration and yolov5s.yaml configuration are as follows: 
![image](https://user-images.githubusercontent.com/54127320/103389854-46a8d700-4b4c-11eb-9956-3b5659b8ed2b.png)
![image](https://user-images.githubusercontent.com/54127320/103389882-7952cf80-4b4c-11eb-96fd-e0ac7d2bd230.png)

**Comment by glenn-jocher** [comment]
@p110120p1 we don't assist in debugging 3rd party modifications. The official YOLOv5 colab notebook is here, and operates correctly. I'd advise you to start there.
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

**Comment by p110120p1** [comment]
> @p110120p1 we don't assist in debugging 3rd party modifications. The official YOLOv5 colab notebook is here, and operates correctly. I'd advise you to start there.
> https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

OK. I had no problem using PNG images as datasets before, but this time using JPG datasets was an error in both the local and colab environment. I'll try something else. Thank you
