### ISSUE TITLE
what is train2017.shapes this file used for in custom training?

### ISSUE THREAD

**Issue by TommyZihao** [ultralytics/yolov5#181]
I see this file in coco128/images. And it contains width and height of that 128 images.
I don't know what is this file used for.
Should I make this file specially when I train my own datasets, or just ignore it?

**Comment by glenn-jocher** [comment]
@TommyZihao it's a shapes file. They're managed automatically, there is no action for you to take.

**Comment by craine** [comment]
I'm getting an error on a dataset from https://public.roboflow.ai/  -- Mask Wearing dataset. 
I keep getting errors on the missing train.shapes file? See screenshot. 

Optimizer groups: 126 .bias, 132 conv.weight, 123 other
Reading image shapes: 100%|██████████████████| 105/105 [00:00<00:00, 841.93it/s]
Traceback (most recent call last):
  File "/kaggle/working/utils/datasets.py", line 298, in __init__
    with open(sp, 'r') as f:  # read existing shapefile
FileNotFoundError: [Errno 2] No such file or directory: '../input/wearingmaskc19/MaskWearingfull/Mask Wearing/train/images.shapes'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "train.py", line 406, in <module>
    train(hyp)
  File "train.py", line 164, in train
    stride=gs)
  File "/kaggle/working/utils/datasets.py", line 303, in __init__
    np.savetxt(sp, s, fmt='%g')  # overwrites existing (if any)
  File "<__array_function__ internals>", line 6, in savetxt
  File "/opt/conda/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1364, in savetxt
    open(fname, 'wt').close()
OSError: [Errno 30] Read-only file system: '../input/wearingmaskc19/MaskWearingfull/Mask Wearing/train/images.shapes'

<img width="1161" alt="Screen Shot 2020-06-24 at 5 09 02 PM" src="https://user-images.githubusercontent.com/6070016/85628645-77a8cc00-b63e-11ea-8aaf-003960c38bd2.png">

What am I doing wrong? This is on Kaggle not Colabs.

**Comment by glenn-jocher** [comment]
@craine thanks for the bug report. *.shapes files simply maintain a list of image shapes. They should be created and destroyed as necessary. It seems something did not work correctly in your case. Can you link to a notebook to reproduce?

**Comment by glenn-jocher** [comment]
@craine ah, I see the problem. It appears you are using a Read-only file system that is preventing yolov5 from writing the shapes file. 

Read-only file systems are not supported.

**Comment by craine** [comment]
@glenn-jocher Got it. The /working is writeable. Does it need to write shapes file to the same folder as the images? Or could it go to /working?

**Comment by glenn-jocher** [comment]
@craine you can modify the dataloader here:
https://github.com/ultralytics/yolov5/blob/227aa735dccea28f44bc069b24a5a6356e9a707a/utils/datasets.py#L259

**Comment by craine** [comment]
@glenn-jocher I added you to my notebook in Kaggle. The folder is writeable now. I moved it to the working folder so all my files writeable for files and images and labels. But it still isn't writing shapes file. I doing exactly have setup in Colabs but can't get it to work here.

**Comment by glenn-jocher** [comment]
@craine its possible your issue is unrelated to the shapes files then. They are not needed to run, as if they are not located they will simply be created on demand (and saved, assuming the drive is writable). 

I suppose it would be good to write a kaggle notebook tutorial, though it would simply be as close as possible to a copy of the colab notebook.

**Comment by glenn-jocher** [comment]
@craine I copied the colab notebook into kaggle. No issues at all, everything works exactly the same as in colab.
https://www.kaggle.com/models/ultralytics/yolov5-tutorial

<img width="1447" alt="Screen Shot 2020-07-04 at 10 57 56 PM" src="https://user-images.githubusercontent.com/26833433/86526528-f0333800-be49-11ea-9a23-5e903dbb5efd.png">
