### ISSUE TITLE
请问有人遇到 yolov5s 的onnx模型转trt int8不出框的情况吗？不管是yolov5 3.1的版本还是2.0的，都不出框。。。

### ISSUE THREAD

**Issue by Wulingtian** [ultralytics/yolov5#1812]
有onnx转trt int8可以交流一下

**Comment by wudashuo** [comment]
README-Tutorial-TensorRT Deployment: https://github.com/wang-xinyu/tensorrtx
use .wts instead of onnx

**Comment by zhiyoujingtian** [comment]
> 有onnx转trt int8可以交流一下

you konw why? I also encountered this problem

**Comment by lufanma** [comment]
> 有onnx转trt int8可以交流一下

Hi~我在onnx-tensorrt转yolov5, engine推理的时候也遇到没有检测框输出的问题（主要是表现为置信度得分过低和框坐标解码出来的数值明显异常），请问您有了解到是什么原因吗？还是说应该使用.wts-tensorrt吖？求指教

**Comment by glenn-jocher** [comment]
@lufanma hi there! 感谢你的问题。可能是因为在将模型转换为TensorRT时，出现了某些参数设置不对的情况。我们通常建议尝试使用.wts转换，以便更好地适配TensorRT。你可以参考Ultralytics官方文档中的教程，里面有详细的转换说明。希望对你有所帮助！
