### ISSUE TITLE
Convert denormalised of bbox to normalized value while testing

### ISSUE THREAD

**Issue by fahimnawaz7** [ultralytics/yolov5#1813]
## ❔Question
I trained the custom data set with 3 classes. While testing, I got denormalized values 0.219097 0.692691 0.377083 0.0219269. Now I want to get the normalized value of the box for CROPPING the BOUNDING BOX. What should be the correct approach or mathematical equation?

**Comment by glenn-jocher** [comment]
@fahimnawaz7 normalized coordinates fall in a 0-1 range. To transform into pixels simply multiply by your image size.
