### ISSUE TITLE
Does anybody know how would datasets.py augment the dataset?

### ISSUE THREAD

**Issue by lujiazho** [ultralytics/yolov5#1819]
## ❔Question
Does anybody know how would datasets.py augment the dataset?

I mean I've seen that there are a lot of augmentation methods in the _datasets.py_ and we can adjust the parameters in the _hyp.scratch.yaml_, but I do not know whether our datasets would expand? our training data would be expanded into several categories such as original, hsv, mosaic, mixup... And all of those categories are several times the size of my original dataset and they would be all put into the training process?

**Comment by glenn-jocher** [comment]
Augmentation hyperparameters define uniform distributions which are randomly sampled during dataloading. No new images are ever saved, the dataset never grows in size, and an image is never presented twice the same way for training. 

**There is no such thing as creating new data**, this is a common misconception and a marketing gimmick propagated by some organizations who don't understand augmentation. If I show you two views of a 10 euro note I have not shown you 20 euros.

![YOLOv5 augmentation](https://user-images.githubusercontent.com/26833433/103451471-3f331c00-4c79-11eb-8cca-726af6a3a898.jpg)

**Comment by lujiazho** [comment]
> Augmentation hyperparameters define uniform distributions which are randomly sampled during dataloading. No new images are ever saved, the dataset never grows in size, and an image is never presented twice the same way for training.
> 
> **There is no such thing as creating new data**, this is a common misconception and a marketing gimmick propagated by some organizations who don't understand augmentation. If I show you two views of a 10 euro note I have not shown you 20 euros.
> 
> ![YOLOv5 augmentation](https://user-images.githubusercontent.com/26833433/103451471-3f331c00-4c79-11eb-8cca-726af6a3a898.jpg)

thanks very much!
