### ISSUE TITLE
how to update weights?

### ISSUE THREAD

**Issue by whuyyc** [ultralytics/yolov5#1820]
## ❔Question
how to update weights for single cls target?

## Additional context
for example:
I got a weight w1 from trianing set t1 which includes 3000 sonar images of single class. Now I get 10 new images of which the distribution is different from t1 cause the different types of sonar but have the same target class as t1. How should I use the new images to update my weight?
Here are 3 methods, but I do not know which one should be chosen:
1. Train the 10 images from w1;
2. Train 3000+10 images from w1;
3. Train 3000+10 images from scratch.
For methond 1,  I am confused whether the network will learn more about the distribution of new images or not? Because it is similar to train t1 base on weight pretained on COCO.
For method 2, does the new weight w2 equal to trianing from n epochs on 10 images and n+m epochs on 3000 images? (w1 is trained  well from m epochs on 3000 images)

**Comment by glenn-jocher** [comment]
Use option 2. Option 1 will cause the model to gradually forget the original 3000 images (weight_decay, etc.).

**Comment by whuyyc** [comment]
> Use option 2. Option 1 will cause the model to gradually forget the original 3000 images (weight_decay, etc.).

Thank you very much with worship in my eyes 0-0
