### ISSUE TITLE
yolov3_tiny.yaml is not working with yolov5 repo

### ISSUE THREAD

**Issue by moured** [ultralytics/yolov5#1822]
## 🐛 Bug
[THE SAME ISSUE I SUBMITTED IN yolov3 repo, I don't know which repo is more suitable]
I just cloned the yolov5 repo then added yolov3-tiny.yaml from yolov3 repo. But, it is not working. Details below.

## To Reproduce (REQUIRED)

Input:
```
python3 train.py --data models_pool/yolov3_tiny/data.yaml --img 256 --batch 4 --epochs 100 --cfg models_pool/yolov3_tiny/model.yaml --weights ''
```
## Output:

Traceback (most recent call last):
  File "train.py", line 538, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 93, in train
    model = Model(opt.cfg, ch=3, nc=nc).to(device)  # create
  File "/home/yolov5/models/yolo.py", line 85, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=[ch])  # model, savelist
  File "/home/yolov5/models/yolo.py", line 253, in parse_model
    m_ = nn.Sequential(*[m(*args) for _ in range(n)]) if n > 1 else m(*args)  # module
TypeError: __init__() takes 2 positional arguments but 5 were given
I0102 20:26:53.518604 140082319169344 internal.py:138] Internal process exited

## Environment
ubuntu 18.04 , GPU.

**Comment by glenn-jocher** [comment]
@moured thanks for the bug report. I just tested this code myself, and I am able to reproduce your result. I will investigate the cause of the problem.

<img width="1239" alt="Screen Shot 2021-01-02 at 12 46 50 PM" src="https://user-images.githubusercontent.com/26833433/103466301-9af0ba00-4cf8-11eb-9f4c-6c42662a45ed.png">

**Comment by glenn-jocher** [comment]
@moured issue is resolved. Please git pull to receive the fix, and let us know if you run into any other problems!
