### ISSUE TITLE
Map_score

### ISSUE THREAD

**Issue by sezarxray** [ultralytics/yolov5#1824]
## ❔Question
I change your test code so now I can evaluate every dataset with coco...
but unfortunately mAP with coco API is by far lower than your evaluation for example I run this code and here is my results...
test.py --weights runs/exp26/weights/best.pt --data data/dataset_9910.yaml --task test --save-json --verbose --save-txt --conf-thres .5 --img-size 1024  --batch 8 --save-dir runs/exp26/test_tresh5 --iou-thres .2

## Additional context

Namespace(augment=False, batch_size=8, conf_thres=0.5, data=&apos;data/dataset_9910.yaml&apos;, device=&apos;&apos;, img_size=1024, iou_thres=0.2, save_conf=False, save_dir=&apos;runs/exp26/test_tresh5&apos;, save_json=True, save_txt=True, single_cls=False, task=&apos;test&apos;, verbose=True, weights=[&apos;runs/exp26/weights/best.pt&apos;])
Using CUDA device0 _CudaDeviceProperties(name=&apos;GeForce GTX 1070&apos;, total_memory=8119MB)

Fusing layers... 
Model Summary: 188 layers, 2.1509e+07 parameters, 0 gradients
Scanning labels ../dataset/labels/test.cache (1315 found, 0 missing, 0 empty, 0 duplicate, for 161Scanning labels ../dataset/labels/test.cache (1610 found, 0 missing, 0 empty, 0 duplicate, for 1610 images): 1610it [00:00, 11953.05it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%
                 all    1.61e+03    7.51e+04       0.656       0.184       0.671       0.457
          pedestrian    1.61e+03     2.1e+04       0.872       0.214       0.888       0.502
              people    1.61e+03    6.38e+03       0.927       0.016       0.928       0.515
             bicycle    1.61e+03     1.3e+03       0.699      0.0553       0.708       0.418
                 car    1.61e+03    2.81e+04       0.866       0.676       0.922       0.692
                 van    1.61e+03    5.77e+03       0.772       0.213       0.792       0.642
               truck    1.61e+03    2.66e+03       0.775       0.203       0.794       0.611
            tricycle    1.61e+03         530           0           0           0           0
     awning-tricycle    1.61e+03         599           0           0           0           0
                 bus    1.61e+03    2.94e+03       0.884       0.379        0.91       0.734
               motor    1.61e+03    5.84e+03       0.761      0.0821       0.765       0.454
Speed: 22.6/1.2/23.8 ms inference/NMS/total per 1024x1024 image at batch-size 8

COCO mAP with pycocotools... saving runs/exp26/test_tresh5/detections_val2017_best_results.json...
data json path /test/test_images_anno.json
loading annotations into memory...
Done (t=0.32s)
creating index...
index created!
Loading and preparing results...
DONE (t=0.19s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=29.29s).
Accumulating evaluation results...
DONE (t=0.84s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.113
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.172
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.125
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.048
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.185
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.291
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.042
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.107
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.129
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.056
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.216
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.319
Results saved to runs/exp26/test_tresh5

**Comment by glenn-jocher** [comment]
@sezarxray your implementation may be incorrect. repo mAP and pycocotools mAP generally fall within a 1-2% tolerance, as displayed in the Colab notebook example on COCO.

<img width="1165" alt="Screen Shot 2021-01-03 at 9 32 57 AM" src="https://user-images.githubusercontent.com/26833433/103484856-bd411100-4da6-11eb-99f2-66edcf552099.png">
