### ISSUE TITLE
Relation between yolo.cfg and yolo.yaml files

### ISSUE THREAD

**Issue by ferro07** [ultralytics/yolov5#1825]
Hey Dear @glenn-jocher 
Thanks for the nice work you have done. Yolov3 had cfg files in the old version but now you used yaml files in both yolov3 and yolov5. Can you explain the conversion of cfg file to yaml file? Especially for researches, yaml files seem more complicated. Actually what I want to tell you; how to convert yolov5s.yaml to cfg, or cfg to yaml ?,
If possible, you can give a short definition about this, then it will be more usable ?

# parameters
nc: 80  # number of classes
depth_multiple: 0.33  # model depth multiple
width_multiple: 0.50  # layer channel multiple

# anchors
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

# YOLOv5 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Focus, [64, 3]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, BottleneckCSP, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 9, BottleneckCSP, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, BottleneckCSP, [512]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 1, SPP, [1024, [5, 9, 13]]],
   [-1, 3, BottleneckCSP, [1024, False]],  # 9
  ]

# YOLOv5 head
head:
  [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, BottleneckCSP, [512, False]],  # 13

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, BottleneckCSP, [256, False]],  # 17 (P3/8-small)

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 14], 1, Concat, [1]],  # cat head P4
   [-1, 3, BottleneckCSP, [512, False]],  # 20 (P4/16-medium)

   [-1, 1, Conv, [512, 3, 2]],
   [[-1, 10], 1, Concat, [1]],  # cat head P5
   [-1, 3, BottleneckCSP, [1024, False]],  # 23 (P5/32-large)

   [[17, 20, 23], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
  ]

to ------------
[net]
# Testing
#batch=1
#subdivisions=1
# Training
batch=64
subdivisions=1
width=416
height=416
channels=3
momentum=0.9
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1

learning_rate=0.00261
burn_in=1000

max_batches = 2000200
policy=steps
steps=1600000,1800000
scales=.1,.1

#weights_reject_freq=1001
#ema_alpha=0.9998
#equidistant_point=1000
#num_sigmas_reject_badlabels=3
#badlabels_rejection_percentage=0.2

[convolutional]
batch_normalize=1
filters=32
size=3
stride=2
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=64
size=3
stride=2
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=64
size=3
stride=1
pad=1
activation=leaky

[route]
layers=-1
groups=2
group_id=1

[convolutional]
batch_normalize=1
filters=32
size=3
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=32
size=3
stride=1
pad=1
activation=leaky

[route]
layers = -1,-2

[convolutional]
batch_normalize=1
filters=64
size=1
stride=1
pad=1
activation=leaky

[route]
layers = -6,-1
--------------------------------------

**Comment by glenn-jocher** [comment]
@ferro07 https://github.com/ultralytics/yolov3/blob/archive/cfg/yolov3.cfg takes up 788 lines of code(!). 

https://github.com/ultralytics/yolov5/blob/master/models/hub/yolov3.yaml requires only 51 lines of code to do the same. 

The yaml model definitions are a massive leap forward in terms of simplicity, readability, and using a modern parameter definition format (yaml), which PyCharm can parse and read well, unlike the *.cfg files, which are not recognized anywhere.

If you'd like to revert back to the older, more complicated method, the archive branch of ultralytics/yolov3 repo is available to you.

**Comment by jaqub-manuel** [comment]
@glenn-jocher 
Thanks a lot for the explanation ... How did you change the cfg file or how we can change the numbers or parameters in the yaml file. For example it is more difficult to change the number of filters or any parameters compared to the cfg file, isn't it?
How to modify yaml file ?

**Comment by ferro07** [comment]
@glenn-jocher 
Thanks a lot for the explanation ... How did you change the cfg file or how we can change the numbers or parameters in the yaml file. For example it is more difficult to change the number of filters or any parameters compared to the cfg file, isn't it?
How to modify yaml file ?

**Comment by sharoseali** [comment]
@glenn-jocher Thanks for your all work. If I want to test my already custom trained yolov4 PyTorch model using this repo **Ultralytics/Yolov5**  how can I do it? This repo uses a yaml file. Also, there is no parser available to change cfg to YAML. Even if I want to retrain the yolov4 model using this REPO. I cant. Can you suggest any time-saving way to reach me there......
Thanks

**Comment by glenn-jocher** [comment]
@sharoseali we no longer support darknet cfg files. Our new yaml files for model definition are shorter and the yaml format is a purpose-designed configuration format that works well here. The only place you can train and use the older cfg files now is in the YOLOv3 archive branch:

## Branch Notice

The [ultralytics/yolov3](https://github.com/ultralytics/yolov3) repository is now divided into two branches:
* [Master branch](https://github.com/ultralytics/yolov3/tree/master): Forward-compatible with all [YOLOv5](https://github.com/ultralytics/yolov5) models and methods (**recommended** ✅).
```bash
$ git clone https://github.com/ultralytics/yolov3  # master branch (default)
```
* [Archive branch](https://github.com/ultralytics/yolov3/tree/archive): Backwards-compatible with original [darknet](https://pjreddie.com/darknet/) *.cfg models (**no longer maintained** ⚠️). 
```bash
$ git clone https://github.com/ultralytics/yolov3 -b archive  # archive branch
```
