### ISSUE TITLE
How to run on iOS or Android?

### ISSUE THREAD

**Issue by alex-imperfect** [ultralytics/yolov5#1828]
How is it possible to run yolov5 in Xcode or Android Studio?
There is the iOS app iDetection, so at least it's possible to run on iOS. Has anyone found a way to do so?

**Comment by lujiazho** [comment]
@alex-imperfect It seams that ultralytics didn't give the way to do that

**Comment by glenn-jocher** [comment]
@alex-imperfect @leaving-voider see https://github.com/ultralytics/yolov5/pull/959 for an android implementation.

**Comment by jlcool** [comment]
@glenn-jocher Where is the source code of iDetection

**Comment by fanatic-studio** [comment]
@glenn-jocher Where is the source code of iDetection

**Comment by glenn-jocher** [comment]
@jlcool @view-team we have not open-sourced the iDetection source code, however soon you'll be able to preview your own custom models in iOS and Android using the Ultralytics HUB. Please visit https://ultralytics.com/hub to learn more.
