### ISSUE TITLE
训练的时候数据加载的进度条不往前走,但是pycharm的DEBUG模式下却可以正常训练,这是什么原因?

### ISSUE THREAD

**Issue by jdwuyao** [ultralytics/yolov5#1833]
## ❔Question
我用正常的训练命令python train.py 或者 用pycharm中的train训练, 程序卡在进度条不动,分析怀疑是在数据加载这里进入死循环了
![image](https://user-images.githubusercontent.com/18142402/103539143-7d774800-4ed2-11eb-85b5-033542e728d0.png)
但是当我用debug模式的时候却可以正常训练,程序畅通运行起来,这是什么原因?

**Comment by wudashuo** [comment]
glenn大神不懂中文

**Comment by wwdok** [comment]
Yes, here you had better use english, not only for youself, but also for the community
