### ISSUE TITLE
Intended use of --save-txt flag

### ISSUE THREAD

**Issue by 5starkarma** [ultralytics/yolov5#1834]
## ❔Question
I am interested in making a system which will work on post-processing detections frame-by-frame as well as using detections across multiple frames 

e.g. one case may be if a detection/class exists in 9/10 frames then the 10th frame should be this class as well. Another may use detections across 30 frames (both cases used in same post-processing system).

Are using the text files from the `--save-txt` flag the most efficient way to handle the processes (I imagine pickles or even relational DBs would be a better way to handle it server-side)? What is the intended use of these text files? Is this for detecting server-side then sending the text files to a local machine for post-processing?

## Additional context

I know every system has different requirements. I am just trying to get an understanding of the intentions of yolov5 as it stands.

Thanks!

**Comment by 5starkarma** [comment]
I guess it may be easier to ask this: I want to process detections on a server but be able to send the detections elsewhere for post-processing. I know how to set up a Google Cloud Deep Learning VM Instance and process rtsp stream using `detect.py` but how have you allowed clients to access the text files/video/etc after processing the detections and/or doing more post-processing? Have you done this? Looking for ideas. 

Thanks!

**Comment by glenn-jocher** [comment]
@5starkarma --save-txt simply saves detections to text. These are in the same format as training labels, so they are suitable for active learning and autolabelling of datasets.

Value added logic/code is up to you of course. The idea is that detect.py simply provides a basis for you to update and tailor to your own needs. See PyTorch Hub Tutorial also for a python command line inference method which may provide you more flexibility.
https://docs.ultralytics.com/yolov5

**Comment by 5starkarma** [comment]
@glenn-jocher 

>  so they are suitable for active learning and autolabelling of datasets.

That makes sense and is actually quite useful for autolabelling. Thank you. 

What I am trying to do with adding code/logic is having the video/text files/etc accessible from the outside (maybe sending it to a bucket for accessing). I am wondering if you have done anything like this or have any suggestions.
