### ISSUE TITLE
What does each tensor in the model output represent?

### ISSUE THREAD

**Issue by MaxwellHogan** [ultralytics/yolov5#1835]
## ❔Question
To try and save me some time could you tell me what each tensor in the output of the model is,

I know when the model is set to eval, the first tensor is what is taken as the inference and the second tensor is used to calculate the loss ....at least I think I know that, 

I am still trying to fully understand what the outputs are during training

**Comment by MaxwellHogan** [comment]
Dumb questions deserve no answers - the output is the three detection layers

**Comment by glenn-jocher** [comment]
Yes the outputs are the 3 detections layers. You can see the 3 output convolutions at the end of the model by simply running print(model).

**Comment by MaxwellHogan** [comment]
After some decent sleep I was finally able realise this haha
