### ISSUE TITLE
error onnx

### ISSUE THREAD

**Issue by alikarimi120** [ultralytics/yolov5#1839]
## terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.5.0-pre) /opt/opencv/modules/dnn/src/onnx/onnx_importer.cpp:613: error: (-2:Unspecified error) in function 'void cv::dnn::dnn4_v20200908::ONNXImporter::populateNet(cv::dnn::dnn4_v20200908::Net)'
> Slice layer only supports steps = 1 (expected: 'countNonZero(step_blob != 1) == 0'), where
>     'countNonZero(step_blob != 1)' is 1
> must be equal to
>     '0' is 0

**Comment by hpc203** [comment]
> ## i got that error in onnx c++ for yolov5.onxx
> ## terminate called after throwing an instance of 'cv::Exception'
> what(): OpenCV(4.5.0-pre) /opt/opencv/modules/dnn/src/onnx/onnx_importer.cpp:613: error: (-2:Unspecified error) in function 'void cv::dnn::dnn4_v20200908::ONNXImporter::populateNet(cv::dnn::dnn4_v20200908::Net)'
> 
> > Slice layer only supports steps = 1 (expected: 'countNonZero(step_blob != 1) == 0'), where
> > 'countNonZero(step_blob != 1)' is 1
> > must be equal to
> > '0' is 0

watch my github code
https://github.com/hpc203/yolov5-dnn-cpp-python

**Comment by alikarimi120** [comment]
Thanks, is it running properly?
Do I need to change the onnx file?

**Comment by Elbek-Khoshimjonov** [comment]
> > ## i got that error in onnx c++ for yolov5.onxx
> > ## terminate called after throwing an instance of 'cv::Exception'
> > what(): OpenCV(4.5.0-pre) /opt/opencv/modules/dnn/src/onnx/onnx_importer.cpp:613: error: (-2:Unspecified error) in function 'void cv::dnn::dnn4_v20200908::ONNXImporter::populateNet(cv::dnn::dnn4_v20200908::Net)'
> > > Slice layer only supports steps = 1 (expected: 'countNonZero(step_blob != 1) == 0'), where
> > > 'countNonZero(step_blob != 1)' is 1
> > > must be equal to
> > > '0' is 0
> 
> watch my github code
> https://github.com/hpc203/yolov5-dnn-cpp-python

Any update?

**Comment by CristianBold4** [comment]
@alikarimi120 have you been able to solve the issue? I'm facing it rn

**Comment by glenn-jocher** [comment]
@CristianBold4 some examples of YOLOv5 C++ inference are below, perhaps these might help!

## C++ Inference

YOLOv5 OpenCV DNN C++ inference on exported ONNX model examples:
- https://github.com/Hexmagic/ONNX-yolov5/blob/master/src/test.cpp
- https://github.com/doleron/yolov5-opencv-cpp-python

YOLOv5 OpenVINO C++ inference examples:
- https://github.com/dacquaviva/yolov5-openvino-cpp-python
