### ISSUE TITLE
GPU utilisation is very low while training 

### ISSUE THREAD

**Issue by deepkshikha** [ultralytics/yolov5#184]
![GPU Utilization](https://user-images.githubusercontent.com/13184577/85433557-38c53880-b5a2-11ea-8fc1-39c0e499ea8e.PNG)

**Comment by PaulHeraty** [comment]
Most likely related to your batch size being too small? You're only using ~2GB of the 32GB RAM on GPU. Try increasing the batch size.

**Comment by deepkshikha** [comment]
I increased it 512 still not getting better utilization.

**Comment by glenn-jocher** [comment]
@deepkshikha if you have an 8-V100 machine you might be able to help us develop our multi-gpu code better. We do all of our training on single-gpu so its likely multi-gpu is not fully optimized. Can you run the following tests and report back the COCO epoch speeds and gpu utilization for 1, 2, 4 and 8 GPUs?

```bash
# Multi-GPU speed test
rm -rf yolov5 && git clone https://github.com/ultralytics/yolov5
bash yolov5/data/get_coco2017.sh && cd yolov5
pip install -r requirements.txt

for x in yolov5l # models
do
  for d in 0 0,1 0,1,2,3 0,1,2,3,4,5,6,7 # devices
  do
    python train.py --weights '' --cfg $x.yaml --epochs 1 --img 640 --device $d  # train
  done
done
```

EDIT: You might want to run this in our docker container for consistency also.

**Comment by deepkshikha** [comment]
Hi @glenn-jocher  missed the comment. I will check it. Just a query why the sequence of GPU devices is like this?? I hope this is just GPU devices as per machine infrastructure.

**Comment by glenn-jocher** [comment]
@deepkshikha it's 1, 2, 4, and 8 gpus. Bash for loop with spaces between values.

**Comment by deepkshikha** [comment]
Thanks to clarify. I will check in sometime and post here. Also is there any paper/Blog on network ??? Does this code can be modified. I have not explored complete code but was looking for model description part in PyTorch code.

**Comment by glenn-jocher** [comment]
@deepkshikha we are limited on resources and are targeting a publication by end of year. There are numerous 3rd party blogs and videos out there you can view currently though, for example:
https://blog.roboflow.ai/yolov5-improvements-and-evaluation/
