### ISSUE TITLE
Why the weights can saved as fp16 directly？

### ISSUE THREAD

**Issue by LuTaoChen** [ultralytics/yolov5#1840]
## ❔Question
I notice in the end of training,model is trained in fp32 but saved as fp16 due to code
`x['model'].half()`
in strip_optimizer() of utils.general.py.
I wander why weights can be quantified to fp16 direcly?Will this operation may cause some reduction of performance?

**Comment by glenn-jocher** [comment]
Zero reduction in performance.

**Comment by LuTaoChen** [comment]
> Zero reduction in performance.

Thanks for answering my question!

> Zero reduction in performance.

Thanks for answering my question!But I still can't figure out why.Is the weights are scaled when saved as fp16 or just the rounding error are negligiable？

**Comment by glenn-jocher** [comment]
@LuTaoChen our results (YOLOv5 pycocotools mAP all models on COCO) showed that numerical precision past 16 bits appears to add nothing to a saved model. 

Please advise if your own empirical results differ.
