### ISSUE TITLE
occur an error when use train.py

### ISSUE THREAD

**Issue by bigbrotherwei** [ultralytics/yolov5#1842]
## ❔Question
when l use  command  ` python3 train.py --img 640 --batch-size 8 --epochs 10 --data ../junyahuan/data.yaml --cfg models/yolov5s.yaml --weights weights/yolov5s.pt `   to train my own dataset,  it occurs a warning called  `WARNING: Ignoring corrupted image and/or label ../junyahuan/train/images/sl001002.JPG: duplicate labels`.   however, every picture occurs this warning and finally it becomes an error called `labels, shapes = zip(*cache.values())
ValueError: not enough values to unpack (expected 2, got 0)`
Is there something wrong with my pictures or labels ?

**Comment by bigbrotherwei** [comment]
![1](https://user-images.githubusercontent.com/67535186/103629463-4c9f1d80-4f7b-11eb-8a1a-8582e5d452e4.png)
![2](https://user-images.githubusercontent.com/67535186/103629478-50cb3b00-4f7b-11eb-8fae-7ea23d729832.png)
![3](https://user-images.githubusercontent.com/67535186/103629483-5163d180-4f7b-11eb-8848-7de0f09760a9.png)
![4](https://user-images.githubusercontent.com/67535186/103629485-5294fe80-4f7b-11eb-817a-e5fd98e8c91c.png)
![5](https://user-images.githubusercontent.com/67535186/103629494-56288580-4f7b-11eb-81ca-274d8a84b680.png)
![6](https://user-images.githubusercontent.com/67535186/103629496-56c11c00-4f7b-11eb-8445-7135a5bd485a.png)
![7](https://user-images.githubusercontent.com/67535186/103629506-5b85d000-4f7b-11eb-8747-56e745a5c104.png)

thanks for answering my question, l upload some pictures to make this question easier to understand，
the first picture is the struct of my dataset,
the second picture is the content of data.yaml,
the third picture is the content of 'train' dir,
and next are content of images and labels in 'train',
the last one is the error l got.

**Comment by bigbrotherwei** [comment]
l get the reason for this error. since my labels have double data, it comes with this question. 0_0

**Comment by lsd1994** [comment]
我也碰到这个问题了==已解决，谢谢

**Comment by starsky68** [comment]
What is the reason for this problem?
@bigbrotherwei 
what is  double data?
@lsd1994 
请问如何解决，我明明是按照教程去做的，是哪里遗漏 了嘛

**Comment by lsd1994** [comment]
就是数据标错了，一个目标标了两次，问题不大

**Comment by starsky68** [comment]
> 就是数据标错了，一个目标标了两次，问题不大

好的，我也不知道动了哪里，又好了

**Comment by bigbrotherwei** [comment]
> What is the reason for this problem?
> @bigbrotherwei
> what is double data?
> @lsd1994
> 请问如何解决，我明明是按照教程去做的，是哪里遗漏 了嘛

确认下label里面是不是有重复的数据，我是用脚本把coco数据集转成label格式的，然后多运行了一遍，导致同一个目标label里有两行一样的数据，把重复的删掉就没事了

**Comment by starsky68** [comment]
> > What is the reason for this problem?
> > @bigbrotherwei
> > what is double data?
> > @lsd1994
> > 请问如何解决，我明明是按照教程去做的，是哪里遗漏 了嘛
> 
> 确认下label里面是不是有重复的数据，我是用脚本把coco数据集转成label格式的，然后多运行了一遍，导致同一个目标label里有两行一样的数据，把重复的删掉就没事了

好的，谢谢了

**Comment by forever208** [comment]
也有可能是你的 labels 的坐标不∈ [0, 1]
