### ISSUE TITLE
Questions about the PR curve.

### ISSUE THREAD

**Issue by learncrazy** [ultralytics/yolov5#1843]
## ❔Question
Thank you for your work. I used yolov5 to train one of my own models, and the resulting PR curve looks a little weird. Is there a mistake in my training process? Or is this caused by my dataset?
![precision-recall_curve](https://user-images.githubusercontent.com/50286586/103629802-bdded080-4f7b-11eb-83af-1838a8c7ba67.png)
![results](https://user-images.githubusercontent.com/50286586/103629821-c33c1b00-4f7b-11eb-93ec-22610cf539d3.png)

**Comment by glenn-jocher** [comment]
@learncrazy looks fine. If your validation set is composed of low statistics (few images) the metrics your curve may be more discretized as in your example.

**Comment by glenn-jocher** [comment]
You may want to update your code though (git pull), your images are out of date.

**Comment by learncrazy** [comment]
I got it. Thank you for your answer. I will try to increase the number of validation sets and update code.

**Comment by IssaIssa1** [comment]
the PR curve that is automatically generated in the results folder is over which dataset train, valid or test?

**Comment by learncrazy** [comment]
@IssaIssa1 It should be a validation set.
