### ISSUE TITLE
How to train better model when custom dataset contains a lot of Small Objects?

### ISSUE THREAD

**Issue by TommyZihao** [ultralytics/yolov5#1845]
## ❔Question

Should I use larger --img-size?
--image-weights?
or small anchors?

**Comment by glenn-jocher** [comment]
@TommyZihao when you say better model, do you have a reference point to compare against? Better than what?

**Comment by TommyZihao** [comment]
> @TommyZihao when you say better model, do you have a reference point to compare against? Better than what?

better than default train.py hyperparameter. For example, default img-size 640.

**Comment by hujunchao** [comment]
it's an interesting and hard problem， and I also want to get advice

**Comment by glenn-jocher** [comment]
@TommyZihao can you upload your default training results here so we can see what needs improvement?
