### ISSUE TITLE
Details about anchor generation

### ISSUE THREAD

**Issue by TommyZihao** [ultralytics/yolov5#1846]
## ❔Question

![image](https://user-images.githubusercontent.com/36354458/103641932-6cd7d800-4f8d-11eb-8ca0-e5bb9d840ab5.png)

I want to add detials about anchor generation in my paper, could anyone tell me how to explain this red frame.
What is past_thr,Best Possible Recall (BPR) and thr?
How to find better anchors to suit my own custom dataset? For example, many small objects in dataset.
Thanks a lot!

**Comment by glenn-jocher** [comment]
@TommyZihao this is the autoanchor portion of YOLOv5. It analyzes your dataset and computes new anchors if necessary, first using kmeans and then using genetic evolution with the actual loss criteria used in training as its fitness metric.

There is no action needed on your part, new anchors are integrated into training and saved with your model automatically.

past_thr is past threshold, best possible recall is your dataset's best possible recall (google is your friend...), and thr is threshold for anchor-target matches (from hyperparameters).

**Comment by TommyZihao** [comment]
> @TommyZihao this is the autoanchor portion of YOLOv5. It analyzes your dataset and computes new anchors if necessary, first using kmeans and then using genetic evolution with the actual loss criteria used in training as its fitness metric.
> 
> There is no action needed on your part, new anchors are integrated into training and saved with your model automatically.
> 
> past_thr is past threshold, best possible recall is your dataset's best possible recall (google is your friend...), and thr is threshold for anchor-target matches (from hyperparameters).

Thanks a lot!
