### ISSUE TITLE
AttributeError: Can't get attribute 'SiLU' on <module 'torch.nn.modules.activation'

### ISSUE THREAD

**Issue by WANGCHAO1996** [ultralytics/yolov5#1849]
## ❔Question

Using torch 1.6.0 CUDA:0 (GeForce RTX 2080 Ti, 11264.0MB)

Namespace(adam=False, batch_size=4, bucket='', cache_images=False, cfg='models/yolov5x.yaml', data='data/data.yaml', device='0', epochs=500, evolve=False, exist_ok=False, global_rank=-1, hyp='data/hyp.scratch.yaml', image_weights=False, img_size=[640, 640], local_rank=-1, log_artifacts=False, log_imgs=16, multi_scale=False, name='exp', noautoanchor=False, nosave=False, notest=False, project='runs/train', rect=False, resume=False, save_dir='runs\\train\\exp6', single_cls=False, sync_bn=False, total_batch_size=4, weights='weights/yolov5x.pt', workers=8, world_size=1)
Start Tensorboard with "tensorboard --logdir runs/train", view at http://localhost:6006/
Hyperparameters {'lr0': 0.01, 'lrf': 0.2, 'momentum': 0.937, 'weight_decay': 0.0005, 'warmup_epochs': 3.0, 'warmup_momentum': 0.8, 'warmup_bias_lr': 0.1, 'box': 0.05, 'cls': 0.5, 'cls_pw': 1.0, 'obj': 1.0, 'obj_pw': 1.0, 'iou_t': 0.2, 'anchor_t': 4.0, 'fl_gamma': 0.0, 'hsv_h': 0.015, 'hsv_s': 0.7, 'hsv_v': 0.4, 'degrees': 0.0, 'translate': 0.1, 'scale': 0.5, 'shear': 0.0, 'perspective': 0.0, 'flipud': 0.0, 'fliplr': 0.5, 'mosaic': 1.0, 'mixup': 0.0}
Traceback (most recent call last):
  File "E:/yolov5-master/train.py", line 513, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "E:/yolov5-master/train.py", line 83, in train
    ckpt = torch.load(weights, map_location=device)  # load checkpoint
  File "D:\d\Anaconda3\envs\yolov5\lib\site-packages\torch\serialization.py", line 584, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "D:\d\Anaconda3\envs\yolov5\lib\site-packages\torch\serialization.py", line 842, in _load
    result = unpickler.load()
AttributeError: Can't get attribute 'SiLU' on <module 'torch.nn.modules.activation' from 'D:\\d\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\torch\\nn\\modules\\activation.py'>
Internal process exited

**Comment by NanoCode012** [comment]
Update `torch` to 1.7

**Comment by glenn-jocher** [comment]
@NanoCode012 I've created a PR https://github.com/ultralytics/yolov5/pull/1853 that runs dependency checks before anything else. So far I've only added this to train.py, not detect.py or test.py, though perhaps I should add the checks there also in the `if __name__ == '__main__':` section.

I'm not sure how this will respond to conda packages, or if this would affect pytorch hub functionality, but it might help better identify these issues by providing clearer error messages. PyCharm does this already automatically which is nice (yellow bar in my screenshot), this would take it a step further and throw an error and prevent running of the code.

<img width="1495" alt="Screen Shot 2021-01-05 at 11 48 55 PM" src="https://user-images.githubusercontent.com/26833433/103743100-97875800-4fb0-11eb-8585-b72b0112549e.png">

EDIT: Original idea from https://stackoverflow.com/questions/16294819/check-if-my-python-has-all-required-packages

**Comment by NanoCode012** [comment]
I ran a quick `python train.py --epochs 3` on my conda env and got the error when running as expected when I was missing a package.

I'm using VS Code and don't see the same yellow bar as yours, but I think the error message does it well enough.

It might be good to add it to test/detect just to be on the safe side.

**Comment by glenn-jocher** [comment]
@NanoCode012 ok great thanks for the feedback. I'll add add it to test and detect also.

**Comment by HamdiTarek** [comment]
How can I add 'SiLU' if my server doesn't support pip and the network is blocked (can't download anything)? my torch is 1.6.0. I can use only torch 1.6.0 on this server.

**Comment by glenn-jocher** [comment]
@HamdiTarek 

## Requirements

[**Python>=3.6.0**](https://www.python.org/) with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) installed including [**PyTorch>=1.7**](https://pytorch.org/get-started/locally/). To get started:
```bash
$ git clone https://github.com/ultralytics/yolov5
$ cd yolov5
$ pip install -r requirements.txt
```
