### ISSUE TITLE
W&B id is always the same and continue with the old logging.

### ISSUE THREAD

**Issue by TommyZihao** [ultralytics/yolov5#1851]
When I run train.py to train a new mission, W&B always generates the same ID and continue(append) with the old visualization.
I have tried to relogin wandb, change the --name, --project, --data, but not work.
I tried `wandb init`, it indeed generates a new ID, but when I run train.py, it's the old ID again.

**Comment by TommyZihao** [comment]
I also tried to reboot my cloud server, change the user account of W&B

**Comment by TommyZihao** [comment]
![image](https://user-images.githubusercontent.com/36354458/103730375-b07a2280-501d-11eb-922d-5d92ec8b2114.png)

**Comment by TommyZihao** [comment]
![image](https://user-images.githubusercontent.com/36354458/103730467-e7e8cf00-501d-11eb-9a39-8790b1a77bc3.png)

**Comment by TommyZihao** [comment]
I have fixed this bug.
See my PR 
https://github.com/ultralytics/yolov5/pull/1852

**Comment by glenn-jocher** [comment]
@TommyZihao thanks for the PR, will move the conversation over there.
