### ISSUE TITLE
Getting error on loading custom trained model

### ISSUE THREAD

**Issue by p9anand** [ultralytics/yolov5#1856]
Before submitting a bug report, please be aware that your issue **must be reproducible** with all of the following, otherwise it is non-actionable, and we can not help you:
 - **Current repo**: run `git fetch && git status -uno` to check and `git pull` to update repo
 - **Common dataset**: coco.yaml or coco128.yaml
 - **Common environment**: Colab, Google Cloud, or Docker image. See https://github.com/ultralytics/yolov5#environments
 
If this is a custom dataset/training question you **must include** your `train*.jpg`, `test*.jpg` and `results.png` figures, or we can not help you. You can generate these with `utils.plot_results()`.

## To Reproduce (REQUIRED)

Input:
```
import torch

a = torch.tensor([5])
c = a / 0
```

Output:
```
Traceback (most recent call last):
  File "/Users/glennjocher/opt/anaconda3/envs/env1/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-be04c762b799>", line 5, in <module>
    c = a / 0
RuntimeError: ZeroDivisionError
```

## Environment

 - OS: [e.g. Ubuntu]
 - GPU [e.g. 2080 Ti]

## Additional context

![image](https://user-images.githubusercontent.com/7848315/103785973-d9bca200-5061-11eb-80b8-f4e3a95721d4.png)

and got following error: 
![image](https://user-images.githubusercontent.com/7848315/103786027-efca6280-5061-11eb-863a-d02382456819.png)

![image](https://user-images.githubusercontent.com/7848315/103786081-007ad880-5062-11eb-9d48-272fcddfccd8.png)

![image](https://user-images.githubusercontent.com/7848315/103786129-14263f00-5062-11eb-821a-70beb9ef0696.png)

**Comment by p9anand** [comment]
[Uploading weights.zip…]()
weights file.

**Comment by p9anand** [comment]
I was able to load the weights file. but it seems for some layers number of parameters are zero and because of this performance of the model has degraded. Is there way to go back to previous version of loading custom model in pytorch hub.

![image](https://user-images.githubusercontent.com/7848315/103794456-be09c980-506a-11eb-9f94-238428276853.png)

**Comment by glenn-jocher** [comment]
@p9anand see PyTorch Hub tutorial for instructions on custom model loading:
https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading

It's very simple:
## Custom Models
This example loads a custom 20-class [VOC](https://github.com/ultralytics/yolov5/blob/master/data/voc.yaml)-trained YOLOv5s model `'yolov5s_voc_best.pt'` with PyTorch Hub.
```python
model = torch.hub.load('ultralytics/yolov5', 'custom', path_or_model='yolov5s_voc_best.pt')  # custom model
```
