### ISSUE TITLE
How to go about training YOLOv5 as an autoencoder?

### ISSUE THREAD

**Issue by bohare** [ultralytics/yolov5#1857]
## ❔Question
I am trying to train the model on a custom dataset. Since the custom dataset is not too big, I would like to fine-tune an autoencoder based on YOLOv5 on an unlabeled dataset first and then fine-tune it further on the custom dataset so that it generalizes better.

My question is how can I approach this problem. Where can I make the changes to use a YOLOv5 model instance as an autoencoder?

Any guidance would be much appreciated. Thanks.

**Comment by glenn-jocher** [comment]
@bohare encoders are typically used in vision paired with decoders for segmentation tasks. You could basically consider the entire model one large encoder I suppose due to the image-dimension reductions as the model deepens.

What is your use case specifically?

**Comment by bohare** [comment]
@glenn-jocher Thanks a lot for your response. 

I would like to finetune one of the pretrained yolov5 weights on a custom dataset (in a different domain from COCO). The dataset being not too large presents itself as a challenge in the final trained weights being generalizable enough. I do have, however, a much bigger unlabeled dataset from the same domain on which I would like to train (more like, fine-tune) yolov5 as an autoencoder. Then when I am finally using the labeled smaller dataset, I will remove the final layer from the autoencoder, reattach yolov5 head (`Detect`) and finetune using the AutoEncoder weights. 

I was considering removing the `Detect` layer and attaching a custom layer on top of the 23rd `C3` layer. I tried replacing the `Detect(P3, P4, P5)` entry from the `yolov5l.yaml` (this file is not specific since ideally, I could use any of the 3 other variants; `yolov5s.yaml`, `yolov5m.yaml` or `yolov5x.yaml`) and writing a custom `Conv` layer but it throws `ZeroDivisionError: float division by zero` when initializing the weights in `kaiming_uniform_` method. Something like this: `[23, 1, Conv, [nc, False]]` meaning that it should take the input from 23rd layer and output `nc` channels. Is this correct?

If you have any pointers, I would hugely appreciate it. Thank you.

**Comment by glenn-jocher** [comment]
@bohare oh sure. To introduce custom layers you can simply delete the Detect() layer in model.yaml and then replace it with something like this. The arguments are the input stage indices [17, 20, 23], the number of times this layer repeats (once), the name of the module (Custom), and the module argument list, [] for no arguments. 

```yaml
   [[17, 20, 23], 1, Custom, [custom_argument_list]],  # Custom with inputs P3, P4, P5
```

The input into your module will be the 3 stage outputs as a list of tensors. You can modify the weight initialization code here if it causing problems:
https://github.com/ultralytics/yolov5/blob/fea9c9b80c5c0f73f66b93cd10003b9500452579/utils/torch_utils.py#L125-L135

**Comment by bohare** [comment]
@glenn-jocher Thank you for your response. I actually did something very similar and got it working. Had to add another upsampling layer to make the final layer dimensions match but now the entire architecture works as an AutoEncoder. Did not need to alter `initialize_weights(model)`. Thank you again. :)

**Comment by sarmientoj24** [comment]
@bohare is there a repo that I could check for your implementation of yolov5 autoencoder?
