### ISSUE TITLE
Calculating AP at specific IOU

### ISSUE THREAD

**Issue by BLOO69** [ultralytics/yolov5#1861]
## ❔Question
I wish to be able to display 2 separate mAP in one run, which are mAP@.25 and mAP@.5. By using linspace(0.25,0.5,2), the variable mAP50 in the code should give me mAP@.25. I was thinking of finding mAP@.5 = ((mAP@0.25:0.5) * 2) -mAP@.25. However, the outputs do not seem to tally. Could it be due to the fitness function in metrics.py? Thank you!
![image](https://user-images.githubusercontent.com/73099790/103857442-7aa66e00-50f1-11eb-8293-b103f4e4098c.png)

## Additional context
![image](https://user-images.githubusercontent.com/73099790/103855856-80e71b00-50ee-11eb-88c4-7f5b18ba795e.png)
I modified the linspace to allow me to evaluate mAP at 2 specific threshold, 0.25 and 0.5.

**Output**
Map@.25 = 0.56075
Map@.50 = 0.54849

![image](https://user-images.githubusercontent.com/73099790/103856218-3f0aa480-50ef-11eb-8c72-d5f840692ac3.png)
I changed the linspace range to include both threshold. [0.25,0.5,2]

**Output**
Map@0.25:0.5 = 0.55336

However, 
(Map@0.25 + Map@0.5)/2 = 0.55462

**Comment by glenn-jocher** [comment]
@BLOO69 fitness is used for evolution.
