### ISSUE TITLE
Caching images problem

### ISSUE THREAD

**Issue by Bilgee** [ultralytics/yolov5#1862]
I am trying to train a detection model using my custom dataset.
When I set image-size at 640, it works. But when I set mage-size at 1280, it shows the following error. I already tried --workers 0, but there was no difference.
yolov5: v4.0
env: google colab

Transferred 500/506 items from yolov5m.pt
Scaled weight_decay = 0.0005
Optimizer groups: 86 .bias, 86 conv.weight, 83 other
Scanning '/content/fish/labels/train.cache' for images and labels... 2368 found, 0 missing, 0 empty, 0 corrupted: 100% 2368/2368 [00:00<00:00, 26000292.86it/s]
Caching images (6.5GB): 100% 2368/2368 [04:12<00:00,  9.37it/s]
Scanning '/content/fish/labels/val.cache' for images and labels... 591 found, 0 missing, 0 empty, 0 corrupted: 100% 591/591 [00:00<00:00, 4063661.74it/s]
Caching images (1.3GB):  77% 458/591 [00:56<00:14,  9.14it/s]Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 720, in next
    item = self._items.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 520, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 202, in train
    rank=-1, world_size=opt.world_size, workers=opt.workers, pad=0.5)[0]
  File "/content/yolov5/utils/datasets.py", line 71, in create_dataloader
    image_weights=image_weights)
  File "/content/yolov5/utils/datasets.py", line 432, in __init__
    for i, x in pbar:
  File "/usr/local/lib/python3.6/dist-packages/tqdm/std.py", line 1104, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 724, in next
    self._cond.wait(timeout)
  File "/usr/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 1192) is killed by signal: Killed. 
Caching images (1.3GB):  77% 458/591 [00:58<00:17,  7.77it/s]

**Comment by glenn-jocher** [comment]
@Bilgee don't --cache if your system doesn't have the RAM to support it.

**Comment by Bilgee** [comment]
@glenn-jocher thank you for reply. Yolov5 caching is memory caching? I think that caching makes special files like tfrecords, right? 

Scanning **'/content/fish/labels/train.cache'** for images and labels... 2368 found, 0 missing, 0 empty, 0 corrupted: 100% 2368/2368 [00:00<00:00, 26000292.86it/s]
Caching images **(6.5GB)**: 100% 2368/2368 [04:12<00:00, 9.37it/s]
Scanning **'/content/fish/labels/val.cache'** for images and labels... 591 found, 0 missing, 0 empty, 0 corrupted: 100% 591/591 [00:00<00:00, 4063661.74it/s]
Caching images **(1.3GB):** 77% 458/591 [00:56<00:14, 9.14it/s]Traceback (most recent call last):

it failed here. Google Colab RAM is almost 13GB.

**Comment by Bilgee** [comment]
I think that after creating train.cache or val.cache, the code does not release memory, so that it fails to allocate the more memory.

**Comment by Bilgee** [comment]
@glenn-jocher

**Comment by phantom-cloud** [comment]
Try setting the image size between 640 and 1000 seems you are low on memory
