### ISSUE TITLE
IOU Used in Objectness Loss

### ISSUE THREAD

**Issue by wtiandong** [ultralytics/yolov5#1863]
## ❔Question
Could you please give some references that use IOU as objectness labels?

## Additional context
I notice it is called objectness smooth in yolov4 codes, but I can't find who is first using this method or in any papers, not even in the yolov4 paper.
Thank you.

**Comment by glenn-jocher** [comment]
@wtiandong I implemented this on my own to enable NMS to benefit from predicted box accuracies without adding any additional parameters to the model. Other techniques implemented uncertainty predictions directly as sigmas for regression values, I think under name Gaussian NMS or Gaussian object detection, named after German scientist Carl Gauss, the father of the modern Normal distribution.

**Comment by glenn-jocher** [comment]
https://arxiv.org/pdf/1904.04620.pdf might be a good reference.

**Comment by wtiandong** [comment]
@glenn-jocher Thank you! I searched more on the web and found another paper in which the authors add IOU prediction in their detection network for better NMS results. 
The paper:
[Precise Detection in Densely Packed Scenes](https://arxiv.org/pdf/1904.00853.pdf )

**Comment by wtiandong** [comment]
Problem solved
