### ISSUE TITLE
Hyperparameter Evolution: load dataset every time

### ISSUE THREAD

**Issue by TommyZihao** [ultralytics/yolov5#1864]
when run train.py --evolve, the code will load and analyze datasets every time before training.
On default, it will load 300 times.
As we all know, these are absolutely the same dataset, no need to load and analyze again and again. This will waste a lot of time.

Can we figure out a solution to solve this?

**Comment by glenn-jocher** [comment]
The train() function within train.py operates independently each run, therefore treating each evolution training identically to a normal training, simplifying the codebase. 

Dataset **scanning** only occurs on first use or modification of a dataset.

Dataset **loading** occurs constantly throughout training every batch, this is normal unless --cache is used. --cache has already been multithreaded and should not present a time constraint should you opt to use it.
