### ISSUE TITLE
What can I do to convert yolov5s.onnx to yolov5s.trt？

### ISSUE THREAD

**Issue by wangwangteam** [ultralytics/yolov5#1865]
## ❔Question
Anyone help me!!When I execute the command on NVIDIA Jetson NX device:
./trtexec --onnx = yolov5s.onnx --saveEngine=yolov5s.trt 
 I get an error.

## Additional context
Input filename: yolov5s.onnx
ONNX IR version: 0.0.6
Opset version: 11
Producer name: pytorch
Producer version: 1.7
Domain:
Model version: 0
Doc string:
[01/07/2021-14:44:07] [W] [TRT] onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[01/07/2021-14:44:07] [W] [TRT] onnx2trt_utils.cpp:246: One or more weights outside the range of INT32 was clamped
[01/07/2021-14:44:07] [I] [TRT] ModelImporter.cpp:135: No importer registered for op: ScatterND. Attempting to import as plugin.
[01/07/2021-14:44:07] [I] [TRT] builtin_op_importers.cpp:3659: Searching for plugin: ScatterND, plugin_version: 1, plugin_namespace:
[01/07/2021-14:44:07] [E] [TRT] INVALID_ARGUMENT: getPluginCreator could not find plugin ScatterND version 1
ERROR: builtin_op_importers.cpp:3661 In function importFallbackPluginImporter:
[8] Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"
[01/07/2021-14:44:07] [E] Failed to parse onnx file
[01/07/2021-14:44:07] [E] Parsing model failed
[01/07/2021-14:44:07] [E] Engine creation failed
[01/07/2021-14:44:07] [E] Engine set up failed
&&&& FAILED TensorRT.trtexec # ./trtexec --onnx=yolov5s.onnx --saveEngine=yolov5s.trt

**Comment by mfruhner** [comment]
Hey, the current version of the onnx2trt converter does not support some needed operations. You have to use [this repo](https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5) to convert your Yolov5 model to a TRT Engine. Currently it only supports up to version 3.1 though and not v4 yet.

Cheers

**Comment by wudashuo** [comment]
The official tutorial has given the way to convert:
![image](https://user-images.githubusercontent.com/5948604/103891984-beb36600-5125-11eb-9e3e-733ac034f697.png)

**Comment by wangwangteam** [comment]
> Hey, the current version of the onnx2trt converter does not support some needed operations. You have to use [this repo](https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5) to convert your Yolov5 model to a TRT Engine. Currently it only supports up to version 3.1 though and not v4 yet.
> 
> Cheers

If I use the v3.1 version, how should I use the onnx model for reasoning? Can you provide me with a sample code?

**Comment by wudashuo** [comment]
> If I use the v3.1 version, how should I use the onnx model for reasoning? Can you provide me with a sample code?

As @mfruhner said, onnx2trt converter **does NOT** support some operations! Please read it carefully.
He and I had given the correct way to convert to TRT，which is the [REPO](https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5) that author suggested in tutorial.

**Comment by Olalaye** [comment]
> Hey, the current version of the onnx2trt converter does not support some needed operations. You have to use [this repo](https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5) to convert your Yolov5 model to a TRT Engine. Currently it only supports up to version 3.1 though and not v4 yet.
> 
> Cheers

I think V4.0 is now supported
![image](https://user-images.githubusercontent.com/37449685/104153310-fddf0100-541c-11eb-94be-d064da4348a5.png)

**Comment by cloud-zZ** [comment]
> > Hey, the current version of the onnx2trt converter does not support some needed operations. You have to use [this repo](https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5) to convert your Yolov5 model to a TRT Engine. Currently it only supports up to version 3.1 though and not v4 yet.
> > Cheers
> 
> I think V4.0 is now supported
> ![image](https://user-images.githubusercontent.com/37449685/104153310-fddf0100-541c-11eb-94be-d064da4348a5.png)

you sure? Because when i set "model.model[-1].export = False" and convert my onnx to trt,there's still error that "scatterND" layer is not supported....... how can this be solved?

**Comment by Olalaye** [comment]
@cloud-zZ please refer to this repo and issue to them if there is any problem.

**Comment by wudashuo** [comment]
> you sure? Because when i set "model.model[-1].export = False" and convert my onnx to trt,there's still error that "scatterND" layer is not supported....... how can this be solved?

Please read this issue carefully, "onnx2trt are not supported" had been said two times already, and the right way to convert to TRT also had been given many times.
