### ISSUE TITLE
FP16 shows slower inference on Turing vs FP32

### ISSUE THREAD

**Issue by freitaucher** [ultralytics/yolov5#1866]
Dear all,

badly need your advice. I have a yolov5l (in fact, even a sequence of yolov5l)  which gives the following inference times on my PC1:

PC1: Ubuntu20.04, RTX2080Ti: inference/image ~ 0.10s (FP16), ~ 0.12s (FP32)
PC1: Windows10, RTX2080Ti: inference/image ~ 0.13s (FP16), ~ 0.15s (FP32)

Testing it on PC2 (with the same Turing architecture) the picture is completely the opposite:
PC2: Windows10, GTX1660Ti: inference/image ~ 2s (FP16), ~ 0.4s (FP32)

## ❔Question
i.e., FP16 becomes about 5 times slower compared to FP32 (!) The same story we get on GTX1650 (which is also Turing). As far as I know, on Turing this should not happen (e.g. GTX1650 benchmark shows FP16 (half) performance 5.97 TFLOPS compared to 2.98 in FP32). Where can be a problem?

## Additional context
Inference is run on python3.8 with pytorch1.7 using cuda10.2.

**Comment by glenn-jocher** [comment]
@Stancoo anecdotal results may vary but on aggregate FP16 inference will be no slower than FP32 on all cuda devices, and many cuda devices are capable of faster FP16 inference vs FP32 of course, setting aside the larger batch size argument, which will also allow you to further increase your batched inference speed.

**Comment by freitaucher** [comment]
@glenn-jocher  Thanks! Sadly, this does not concern the batched inference. Of course, it is not yolov5-specific problem, but rather has to do with pytorch performance on Nvidia in general. Once I get some reasonable hint from nvidia I will link it here.
