### ISSUE TITLE
anchor

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#1871]
## ❔Question
YOLOV5 code will auto generate new anchor for default, right?
 parser.add_argument('--noautoanchor', action='store_true', help='disable autoanchor check')

If it will generate new anchor, where is the final anchors value?

**Comment by glenn-jocher** [comment]
@alicera autoanchor results are printed to screen and new anchors are automatically integrated into your model. No action is required on your part.

**Comment by alicera** [comment]
Does the anchor automatically write to yolov5s.yaml ?

**Comment by glenn-jocher** [comment]
@alicera autoanchor will not update your yaml. It automatically saves new anchors in your model.pt file, and prints the new anchors to screen also. If you want you can copy and paste these new anchors into your yaml file to use these in the future:

<img width="960" alt="Screen Shot 2021-01-10 at 8 10 49 PM" src="https://user-images.githubusercontent.com/26833433/104146633-3b418100-5380-11eb-81c1-d59440a00a56.png">

**Comment by ggyybb** [comment]
> @alicera autoanchor不会更新您的Yaml。它会自动将新的锚点保存在您的model.pt文件中，并将新的锚点也打印到屏幕上。如果您愿意，可以将这些新锚复制并粘贴到yaml文件中，以备将来使用：
> 
> <img alt="屏幕快照2021-01-10,8 10 49 PM" width="960" src="https://user-images.githubusercontent.com/26833433/104146633-3b418100-5380-11eb-81c1-d59440a00a56.png">

But, how can i get new anchors from my_new_model.pt file.I want print new anchors by load my_new_model.pt,because the trainning message already gone.

**Comment by glenn-jocher** [comment]
@ggyybb you can examine the anchors of any trained YOLOv5 model like this:

### Input
```python
import torch

model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True, autoshape=False)  # hub model
# -- or --
model = torch.load('yolov5s.pt')['model']  # local model

print(model.model[-1].anchor_grid.squeeze())
```

### Output
```python
tensor([[[ 10.,  13.],
         [ 16.,  30.],
         [ 33.,  23.]],

        [[ 30.,  61.],
         [ 62.,  45.],
         [ 59., 119.]],

        [[116.,  90.],
         [156., 198.],
         [373., 326.]]], dtype=torch.float16)
```

**Comment by alicera** [comment]
I train the new yolov5.
And run above the code to get anchors.
But I find the anchors value doesnt change.
Should I set some parameter to open the anchors function? 

Here is the anchors for my dataset

> 
tensor([[[ 10.,  13.],
         [ 16.,  30.],
         [ 33.,  23.]],

        [[ 30.,  61.],
         [ 62.,  45.],
         [ 59., 119.]],

        [[116.,  90.],
         [156., 198.],
         [373., 326.]]], dtype=torch.float16)
>

**Comment by glenn-jocher** [comment]
@alicera autoanchor will modify anchors it finds unsuitable. If your anchors are the same as the default then autoanchor has determined your anchors are suitable and no changes are necessary.

**Comment by alicera** [comment]
I already use the new version.
I try to load my custom weight and it show the 
```
  File "get_anchor.py", line 17, in main
    print(model.model[-1].anchor_grid.squeeze())
AttributeError: 'list' object has no attribute 'squeeze'
```

**Comment by glenn-jocher** [comment]
@alicera YOLOv5 🚀 anchors are saved as [Detect()](https://github.com/ultralytics/yolov5/blob/f17c86b7f0d2038288d7292cb82dec2433cc91e5/models/yolo.py#L33-L70) layer attributes on model creation, and updated as necessary by AutoAnchor before training starts. Their exact location is here:
https://github.com/ultralytics/yolov5/blob/f17c86b7f0d2038288d7292cb82dec2433cc91e5/models/yolo.py#L45

You can examine the anchors of any trained YOLOv5 model like this:

### Input
```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', autoshape=False)  # official model
model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt',  autoshape=False)  # custom model

# Anchors
m = model.model[-1]  # Detect() layer
print(m.anchors * m.stride.view(-1, 1, 1))  # print anchors
```

### Output
```python
YOLOv5 🚀 2021-11-22 torch 1.10.0+cu111 CUDA:0 (Tesla V100-SXM2-16GB, 16160MiB)
#           x     y
tensor([[[ 10.,  13.],
         [ 16.,  30.],
         [ 33.,  23.]],  # P3/8-small

        [[ 30.,  61.],
         [ 62.,  45.],
         [ 59., 119.]],  # P4/16-medium

        [[116.,  90.],
         [156., 198.],
         [373., 326.]]], dtype=torch.float16)  # P5/32-large
```

**Comment by DungHD-1997** [comment]
Hi @glenn-jocher 
I already use the new version.
I try to load my custom weight and it show:
    m = model.model[-1]  # Detect() layer
TypeError: 'DetectionModel' object is not subscriptable

my code:

  import torch
  
  model = torch.hub.load('ultralytics/yolov5', 'custom', "D:/yolov5/runs/train/exp13/weights/best.pt",  autoshape=False)
  m = model.model[-1]  # Detect() layer
  print(m.anchors * m.stride.view(-1, 1, 1))  # print anchors
where did I go wrong ?

**Comment by glenn-jocher** [comment]
@DungHD-1997 hi,

The error message you encountered, `TypeError: 'DetectionModel' object is not subscriptable`, suggests that you are trying to index the `model.model` object, but it is not subscriptable.

In YOLOv5, the `model.model` attribute refers to the underlying model structure, which is a list of model layers. To access the desired layer, you can use the `model.model[-1]` syntax to get the last layer (`Detect()` layer).

However, in the newer versions of YOLOv5, the way to access anchors has changed slightly. You can use the `model.module.model[-1]` syntax instead of `model.model[-1]`. 

Here's an updated version of your code:
```python
import torch

model = torch.hub.load('ultralytics/yolov5', 'custom', "D:/yolov5/runs/train/exp13/weights/best.pt", autoshape=False)
m = model.module.model[-1]  # Detect() layer
print(m.anchors * m.stride.view(-1, 1, 1))  # print anchors
```

By using `model.module.model[-1]`, you will be able to access the `Detect()` layer and obtain the anchors successfully.

Let me know if you have any further questions.

**Comment by DungHD-1997** [comment]
@glenn-jocher 

Thank you very much for the information provided. but in my case the program was able to work with the code below:
import torch
model = torch.load('yolov5s.pt')['model']  # local model

m = model.model[-1]  # Detect() layer
print(m.anchors * m.stride.view(-1, 1, 1))  # print anchors

**Comment by glenn-jocher** [comment]
Hi @DungHD-1997,

I'm glad to hear that you were able to get it working with the code you shared. 

In newer versions of YOLOv5, the recommended way to load the model is by using `torch.hub.load()` or `torch.load_state_dict()` to load the model weights. However, the `torch.load()` method you used can still work as long as you have the compatible model structure.

If you have any further questions or need additional assistance, feel free to ask.

Thank you for your support and happy coding!
