### ISSUE TITLE
Hyperparameter evolution going in the wrong direction? 

### ISSUE THREAD

**Issue by djollet** [ultralytics/yolov5#1872]
Hello everyone,

## ❔Question

i tried to evolve the hyperparameters for my yolov5 network, but the resulting evolve.png looks quite strange:

![evolve](https://user-images.githubusercontent.com/77045564/103986939-eccb9100-518b-11eb-9e38-3a0379efaad2.png)

Is this normal? For me it looks like the evolution is going in the wrong direction..

Thanks in advance for your help.

**Comment by glenn-jocher** [comment]
@djollet results are correct. There is no temporal or generational information displayed in these plots, colors indicate density. The cross is indicating your best evolved mutation. The hyps associated with this mutation are displayed as indicated in hyp.evolve.yaml and evolve.txt top row.

**Comment by djollet** [comment]
Okay thank you for the information. However, the results seem to be not very good, because the highest fitness value that was reached was 0.04. Do I need the optimization to train much longer? In this trial I trained for 300 generations.

**Comment by glenn-jocher** [comment]
@djollet evolution results are subject to initial conditions as explained in the evolution tutorial, and is a last resort of extreme measure once you've exhausted all other basic channels for improvement.

If your baseline results are zero you shouldn't expect much improvement.
