### ISSUE TITLE
Questions about train.

### ISSUE THREAD

**Issue by learncrazy** [ultralytics/yolov5#1873]
## ❔Question
Recently I started training yolov5s with my data set from scratch (without using initial weights). I found a phenomenon, every time I finished training, the effect was better than the last time. The mAP of the first time was 0.80, the second time was 0.833, and the third time was 0.866. But theoretically speaking, each training should have the same or similar results.  I am very confused about this.

**Comment by glenn-jocher** [comment]
@learncrazy see https://pytorch.org/docs/stable/notes/randomness.html.

**Comment by learncrazy** [comment]
@glenn-jocher   Thank you very much for your answers. But it is for this reason that I have the current confusion. In theory, after fixing the seed, the result of each training should be basically the same. But now the result is that as the number of training increases, the better the training results. I am wondering whether it retrained the last trained model.

**Comment by glenn-jocher** [comment]
@learncrazy see https://pytorch.org/docs/stable/notes/randomness.html.

Completely reproducible results are not guaranteed across PyTorch releases, individual commits, or different platforms. Furthermore, results may not be reproducible between CPU and GPU executions, even when using identical seeds.

**Comment by learncrazy** [comment]
@glenn-jocher Thank you very much for your answers. I use the same computer and the same environment. My question is not only the reproducibility, but also the training results are always better than the last time. This makes me feel like it automatically loads the last weight and continues training.

**Comment by glenn-jocher** [comment]
@learncrazy your results are not 'better', they are random due to the nondeterministic nature of the training. You can attempt mitigating steps per the link I sent if it's a priority for you.

**Comment by learncrazy** [comment]
@glenn-jocher Okay, thank you for your help.
