### ISSUE TITLE
Max number of detected objects ?

### ISSUE THREAD

**Issue by codename5281** [ultralytics/yolov5#1875]
Hello and thanks for this work !

I haven't experimented on that neither went back to the base architecture of the model but just from a dataset i am working on, i was wondering : is there a maximum number of objects above which YOLOv5 won't be able to perform detection ? In some really crowded pictures this number gets stuck at 300, interestingly only the most obvious candidates for my class, with detection performed on 4032px-wide images from a model trained from YOLOv5m. 
Could someone enlight me about that behaviour ?

Thanks in advance !
J.

**Comment by glenn-jocher** [comment]
@codename5281 you'll want to update the NMS settings for dense scene detection. Default max object count is 300:
https://github.com/ultralytics/yolov5/blob/3e25f1e9e52069189fb140d50c09dddb5be3cff0/utils/general.py#L279-L297

**Comment by codename5281** [comment]
Thank you for your fast answer ! I'll try that.

**Comment by taqpoly2** [comment]
If I work with small objects, should I change max_wh param?
     min_wh, max_wh = 2, 4096  # (pixels) minimum and maximum box width and height 
Or  the alogrithm learns the right size from the training set? Thank you.

**Comment by glenn-jocher** [comment]
@taqpoly2 no, settings are not learned, they are inputs. There are two sets of candidate settings: labels for training and NMS for inference. NMS settings are displayed in my previous message, label candidate criteria are here. Set as appropriate for your situation:
https://github.com/ultralytics/yolov5/blob/046c37e465d60b9047ff0e91f44594817e5a935c/utils/datasets.py#L900-L906
