### ISSUE TITLE
Funny triple detections for constant-sized objects

### ISSUE THREAD

**Issue by vnoblet-nanovare** [ultralytics/yolov5#1876]
### Context

When playing with yolov5 for a project, my anchor per target was 6.54 instead of an expected maximum.

To give a little bit of context my dataset is composed of object of fixed size 40x40 pixels. I actually use yollow to localize object but not finding their shape. I know that it reduces my dimension space and prevent the CNN to learn differently from w,h but yolov5 does actually a really good job for localization.

## Default priors

So the default anchor sizes of ultralytics is :
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32 
 and I believe that the two priors 156,198 and 373,326 are too big for every targets making my anchors go down to 7 anchors per target and one prior is to small for 46% of the targets which make my anchor per target go down to 8.54 per target. The combinations of the two being 6.54 anchors per target. Anchors are too small or too big because they can not meet with the requirements of max(ratio, 1/ratio) < anchor_t (the possible output space being [0.25, 4[ )
So 156,198  * pwh can not reach 40,40, neither can 373,326 * pwh and 10,13 * pwh can reach 39.9999x40 but not 40x40 but with approximation error it can.

## Rework priors fails

With 6.45 anchors per target, my maximum recall is 1 and there is no autoanchor triggered. Since I am sure that the 3 detections layers are not working together and one is trained more than the others (P4), I set the anchors to the only center possible which is 40x40. Actually everything that respect anchor_t should be fine.

  -  [40,40, 40,40, 40,40]  # P3/8
  -  [40,40, 40,40, 40,40]  # P4/16
  -  [40,40, 40,40, 40,40]  # P5/32

Now my anchors per target is 9 which is a good news. But when re-traning I found weird detections. The x, y coordinates were trained well but the w,h were really big or really small or at the right size. Some detections are tripled with 10x10 detections, 40x40 detections and 160x160 detections and can not be handled by NMS even though the center point is the same.

![40x40x40_](https://user-images.githubusercontent.com/71650571/104041308-24145f00-51d9-11eb-91f8-24ed79c3e90c.png)

I immediately thought about the output of 3 detection layers not learning properly from w, h. And I found that the anchors were actually divided by the stride of the layer.
 
![image](https://user-images.githubusercontent.com/71650571/104033373-b9125a80-51cf-11eb-9143-fdde645e460f.png)

## Strangely rework priors succeeds

So I changed the anchors to:
  - [20,20, 20,20, 20,20]  # P3/8
  - [40,40, 40,40, 40,40]  # P4/16
  - [80,80, 80,80, 80,80]  # P5/32
  
![20x40x80](https://user-images.githubusercontent.com/71650571/104037808-1ceb5200-51d5-11eb-9d37-02d04aeacdd1.png)

And it made disappeared the small and big detections. I can not know for sure if the 3 detections are working well because the prediction tensor is not ordered so I can not see which prediction comes from which layers.

I re-made the scenario twice and had the same weird phenomena. Again, whatever the priors, I expect the CNN to learn properly w,h as long as the priors are not too far from the ground-truth bounding box which appears to behave strangely for me.

## ❔Question

So finally my question is why dividing the anchor size by the stride in the detection layer ? And would you happen to have any lead on why choosing the priors at the unique center of my bounding-box distribution makes the CNN learns badly ? And how can I make sure that the 3 detection layers are working in my case.
I might need only one detection layer since my object are the same size but I don't know how to change the model architecture to use only one detection layer.

Thanks a lot for reading me =)

**Comment by glenn-jocher** [comment]
@vnoblet-nanovare there's not much to be gained manually defining anchors. Autoanchor will adjust your anchors as necessary based on your dataset automatically, therefore I would not modify the model.yaml unless you're doing it for educational/research purposes.

**Comment by vnoblet-nanovare** [comment]
@glenn-jocher thank you for your quick answer. Indeed I am running a research project. I don't specifically aim to modify the anchors in model.yaml but I am curious to understand how the three detection layers will learn different object sizes and why a simple case like I tried did not work and if I am training properly.
So are you saying that even if with a BPR above the 0.98 threshold that will not trigger the autoanchor functionnality, there is not much to gain to maximize the number of anchors per target and thus maximize the number of neurons in the detections layers that will be involve in training ?
