### ISSUE TITLE
wandb: ERROR Error while calling W&B API: Error 1062: Duplicate entry '189160-gbp6y2en' for key 'PRIMARY' (<Response [409]>)

### ISSUE THREAD

**Issue by awsaf49** [ultralytics/yolov5#1878]
If I try to train  `v3` on an existing `--project` using `v5` repo I get this error, `wandb: ERROR Error while calling W&B API: Error 1062: Duplicate entry '189160-gbp6y2en' for key 'PRIMARY' (<Response [409]>)`. Changing the `--project` name temporary solves the problem.
But YOLOv5 runs smoothly.

**Comment by glenn-jocher** [comment]
@awsaf49 hi thanks for the bug report! Is there any way you could provide a colab notebook that allows us to reproduce this error ourselves?

@AyushExel do you have any ideas on this?

**Comment by AyushExel** [comment]
@awsaf49 Hi. Thanks for reporting this. As Glenn said, it'd be helpful if you could share some code that could reproduce this.
Even the steps to reproduce would be sufficient I guess.

**Comment by awsaf49** [comment]
It works fine now, I don't why I was getting that error.
