### ISSUE TITLE
train and validation loss

### ISSUE THREAD

**Issue by esmaeil71** [ultralytics/yolov5#1879]
why my validation loss is lower than train loss? How can i fix it.
![Capture](https://user-images.githubusercontent.com/53658751/104055900-cc8be880-5204-11eb-9db2-f1d89f03832b.JPG)

**Comment by glenn-jocher** [comment]
Augmentation.

**Comment by esmaeil71** [comment]
@glenn-jocher Thanks a lot.

**Comment by gohguodong** [comment]
Hi,

i have similar problem. my validation loss is significantly lower than the train loss. is this normal?

![image](https://user-images.githubusercontent.com/74038126/118440947-0ae96500-b71b-11eb-97b8-afc6f26b9516.png)

i believe my dataset is large enough
![image](https://user-images.githubusercontent.com/74038126/118441269-8814da00-b71b-11eb-9c45-2797ff30649d.png)

may i know if data augmentation could help resolve the problem?

**Comment by glenn-jocher** [comment]
@gohguodong your data looks fine. Larger train losses are due to augmentation during training that is absent during testing.

**Comment by glenn-jocher** [comment]
@gohguodong this reminds me though, I need to update the barplot (top left) to show the same colors as the boxes (top right)
