### ISSUE TITLE
Is yolov5 model anchor-based or anchor-free ?

### ISSUE THREAD

**Issue by lujiazho** [ultralytics/yolov5#1881]
## ❔Question
Is yolov5 model anchor-based or anchor-free ?

**Comment by glenn-jocher** [comment]
@leaving-voider see model files:
https://github.com/ultralytics/yolov5/blob/3e25f1e9e52069189fb140d50c09dddb5be3cff0/models/yolov5s.yaml#L6-L11

**Comment by lujiazho** [comment]
@glenn-jocher Thank U! But I am not familiar with the whole architecture, I will dig into that later. So this means it's anchor-based right?

**Comment by ShirleyHe2020** [comment]
> @leaving-voider see model files:
> https://github.com/ultralytics/yolov5/blob/3e25f1e9e52069189fb140d50c09dddb5be3cff0/models/yolov5s.yaml#L6-L11

Hi , does this mean : in order to get better training result on my custom dataset, I need to do fine-tuing on anchors per object shape?

**Comment by glenn-jocher** [comment]
@ShirleyHe2020 autoanchor automatically analyzes and updates your anchors as necessary prior to the start of training for best results. No action is required on your part.

**Comment by ShirleyHe2020** [comment]
> @ShirleyHe2020 autoanchor automatically analyzes and updates your anchors as necessary prior to the start of training for best results. No action is required on your part.

Thanks for your prompt reply. One more question： 'automatically analyze and update anchors ', does it mean yolov5 use  Adaptive Training Sample Selection( ATSS)  ? ( https://openaccess.thecvf.com/content_CVPR_2020/papers/Zhang_Bridging_the_Gap_Between_Anchor-Based_and_Anchor-Free_Detection_via_Adaptive_CVPR_2020_paper.pdf) , if not , what's  the difference?

**Comment by glenn-jocher** [comment]
@ShirleyHe2020 no we don't use ATSS. 

We evaluate your anchors against your train dataset in combination with your training settings like --img-size, and if the Best Possible Recall is below threshold then the anchors are determined to not be a good fit for your data, and new anchors are computed to replace them using genetic algorithm optimizer initialized by a kmeans method. This is all transparent and fully displayed to the workspace at the beginning of training:

<img width="1567" alt="Screenshot 2021-04-10 at 16 35 31" src="https://user-images.githubusercontent.com/26833433/114273570-da772280-9a1a-11eb-8e0a-f692d4352773.png">
