### ISSUE TITLE
Network Design of Yolov5

### ISSUE THREAD

**Issue by flixmk** [ultralytics/yolov5#1882]
## ❔Question
I have a question about the network design of yolov5. When writing a somewhat scientific essay about my work with Yolov5 I need to describe the network architecture. Has anything changed in this regard from yolov3? And is the paper oy Alexey for yolov4 still useable for this network?

And I have a second question. Does Yolo have Pooling Layers? I have heard that it doesnt, but when looking at the Darknet-53 backbone it seems to have a Avgpool layer at the end? Am I missing something?

**Comment by glenn-jocher** [comment]
@Kraufel model architecture is defined by yaml files in the models/directory. i.e.:
https://github.com/ultralytics/yolov5/blob/3e25f1e9e52069189fb140d50c09dddb5be3cff0/models/yolov5s.yaml#L1-L48

**Comment by flixmk** [comment]
@glenn-jocher Thank you. But what kind of backbone, head and neck is used? Backbone doesnt seem to be Darknet-53.

**Comment by zhiqwang** [comment]
Hi @Kraufel, I've refactored the [`backbone`](https://github.com/zhiqwang/yolov5-rt-stack/blob/2ddc86e872474faa8d52d62689e5ef5dd2d18a55/models/darknet.py#L45) and [`neck`](https://github.com/zhiqwang/yolov5-rt-stack/blob/2ddc86e872474faa8d52d62689e5ef5dd2d18a55/models/backbone_utils.py#L10) from the _yaml_ config architecture in here, maybe you could refer to these.

BTW, [here](https://github.com/ultralytics/yolov5/issues/280#issuecomment-774578839) is an diagram overview of YOLOv5 release 4.0 .
