### ISSUE TITLE
resume problem

### ISSUE THREAD

**Issue by sezarxray** [ultralytics/yolov5#1884]
Before submitting a bug report, please be aware that your issue **must be reproducible** with all of the following, otherwise it is non-actionable, and we can not help you:
 - **Current repo**: 3e25f1e
 - **Common dataset**: coco.yaml or coco128.yaml
If this is a custom dataset/training question you **must include** your `train*.jpg`, `test*.jpg` and `results.png` figures, or we can not help you. You can generate these with `utils.plot_results()`.

## 🐛 Bug
resume comment results in drop in  accuracy
## To Reproduce (REQUIRED)
python train.py --img 1024  --batch 16 --epochs 150 --data dataset_9910.yaml --weights yolov5m.pt  --hyp hyp_evolved.yaml  --workers 8 --name=p1 --resume

![image](https://user-images.githubusercontent.com/60059255/104089704-ed465380-5281-11eb-99fc-ae2f6857599c.png)

## Environment

 - OS: [e.g. Ubuntu]
 - GPU [e.g. 2080 Ti]

**Comment by glenn-jocher** [comment]
@sezarxray --resume accepts **zero** additional arguments. The proper usage is:

```bash
python train.py --resume  # resumes from most recent training
python train.py --resume path/to/last.pt
```

**Comment by sezarxray** [comment]
thanks but even with you code problem exist!

**Comment by sezarxray** [comment]
before resume:
<pre>     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
    17/149     7.45G   0.01701    0.0367 0.0006905   0.05439       116      1024:  89%|▉| 1108/1247 [1:45:07&lt;13:11,  5.69^C
</pre>

after resume:

<pre>     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
    16/149     7.41G    0.1392   0.08824  0.009352    0.2368       114      1024:   1%|▏                             | 8/1247 [00:10&lt;23:21,  1.13s/it]</pre>

**Comment by glenn-jocher** [comment]
@sezarxray --resume operates correctly. If you believe otherwise please file a full bug report with exact code to reproduce.

<img width="1396" alt="Screen Shot 2021-01-22 at 9 46 13 PM" src="https://user-images.githubusercontent.com/26833433/105570008-5191fa00-5cfb-11eb-8b27-704d0a6535b5.png">
