### ISSUE TITLE
About additional training

### ISSUE THREAD

**Issue by DaehanKim-Korea** [ultralytics/yolov5#1885]
## ❔Question
For example,

The goal is to detect and classify poodles, Siberian husky, bulldogs, pomeranians, yorkshire terriers, other (6class).

At this time,
First of all, I have a pre-trained model for detecting and classifying all dogs.(1 class)

After that, do I need to freeze 23 layers and train only the last layer to learn with 6class?

<img width="695" alt="스크린샷 2021-01-09 오후 7 49 02" src="https://user-images.githubusercontent.com/48986889/104089667-fb14cc80-52b3-11eb-8fea-baded66e2a40.png">

The dataset used to train the pre-training weights contains many dogs in one image. Additional data includes no more than 5 dogs in one image.

According to my experiment, If the data set used for training of the pre-training weights is used together, dogs are detected well, but classification performance is poor.

Using only the additional training data set, dogs are poorly detected.

The ratio of the class is as follows.
class 0 is another dog.

![image](https://user-images.githubusercontent.com/48986889/104089736-9e65e180-52b4-11eb-8078-de64fbfaf3c4.png)

**Comment by glenn-jocher** [comment]
@koreadhkim train with default settings, and collect more data for underrepresented classes. Information on freezing layers is available in the tutorials section of the README:
https://docs.ultralytics.com/yolov5
