### ISSUE TITLE
What is the resized size for training,testing and inference?

### ISSUE THREAD

**Issue by BLOO69** [ultralytics/yolov5#1888]
## ❔Question
I am confused about the img-size used for these three codes. Let's say i have a input image of size 1280x720. When i run the inference code with img-sz = 608, the code prints that the size is (352,608). This means that it resizes by the long side and pads the short side to a multiple of 32. When i run the testing code with the same size, the output is now (608,608). Could it be that it is resized to (352,608) and then padded to a square image? I assume that the train code should be the same as the testing code. Assuming I am right, is there a reason for this? May i know if there is any way to change the testing and inference code to resize by short side? Thank You!

**Comment by glenn-jocher** [comment]
@BLOO69 detect.py runs rectangular inference on a single image, test.py sorts a dataset by aspect ratio and assembles batches of differently shaped images together for batched rectangular inference.

The dataloaders involved are completely different.
