### ISSUE TITLE
Issue with github api rate limiting

### ISSUE THREAD

**Issue by iceisfun** [ultralytics/yolov5#1890]
It seems that utils/google_utils.py has an issue in attempt_download after updating to the latest v4 stuff.

os.path.isfile is checked after calls to github, this ends up causing exceptions when a cluster of machines start making this api call and end up with rate limiting exceptions.

this function probably just needs to check if weights exists before making the api call.

    # Don't download if we already have this file
    if os.path.isfile(weights):
        return

before

    response = requests.get('https://api.github.com/repos/ultralytics/yolov5/releases/latest').json()  # github api

Keep up the good work on yolov5

**Comment by glenn-jocher** [comment]
@iceisfun good observation. I'd noticed intermitent CI failures since this the v4.0 release which includes this update, this is likely the reason. There is a .exists() check in the function, I suppose we simply need to move it to before the API call. I'll look into this.

**Comment by glenn-jocher** [comment]
@iceisfun a fix for this has been implemented in PR #1894. Please git pull to receive this update and let us know if you spot any other issues!
