### ISSUE TITLE
My val class loss increase

### ISSUE THREAD

**Issue by pakcheera** [ultralytics/yolov5#1892]
## ❔Question
Hello I do the insect detection in yolov5. I have 90 pictures ( 2 classes ). I use Roboflow to prepare the picture(3 augmentations per picture). then I run the model yolov5s. but I get the graph in following. I don't know why my  val class increase. Can anyone help me.
![isssue](https://user-images.githubusercontent.com/72345015/104122800-cb2ffc80-5379-11eb-890a-4edd49d77691.JPG)

**Comment by glenn-jocher** [comment]
@pakcheera overfitting is a desired training trait, if you don't see it this is a good indicator that you have not trained long enough. Ideally however all of your loss components would begin to overfit in a synchronized way. If classification loss is overfitting early, you should take steps to reduce it's gain, increase augmentation, or of course increase your dataset, as with 90 images nothing great will be achievable (think 1 or 2 orders of magnitude larger at a minimum, i.e. 1000 to 10k images).
