### ISSUE TITLE
what is the new quad dataloader?

### ISSUE THREAD

**Issue by GriffinTheWu** [ultralytics/yolov5#1898]
## ❔Question
I see a new feature in v4.0
parser.add_argument('--quad', action='store_true', help='quad dataloader')
May I ask what is this quad dataloader?

**Comment by glenn-jocher** [comment]
@GriffinTheWu the quad dataloader is an experimental feature we thought of that may allow some benefits of higher --img size training at lower --img sizes.

When `python train.py --quad` is run, the dataloader is in `quad` mode, and replaces with the default collate function with a quad-collate function here:
https://github.com/ultralytics/yolov5/blob/b1cf25dd9a7ba6a47703457bc04b8b77e469803b/utils/datasets.py#L582-L583

This quad-collate function will reshapes a batch from 16x3x640x640 to 4x3x1280x1280, which does not have much effect by itself as it is only rearranging the mosaics in the batch, but which interestingly allows for 2x upscaling of some images within the batch (one of the 4 mosaics in each quad is upscaled by 2x, the other 3 mosaics are deleted). The upscaling probability is set here:
https://github.com/ultralytics/yolov5/blob/b1cf25dd9a7ba6a47703457bc04b8b77e469803b/utils/datasets.py#L593

We haven't been able to run as many experiments as we'd like on it yet, but we did train a normal YOLOv5l model and a YOLOv5l model with --quad, and the --quad model predictably can run inference at --img-sizes above 640, while the normal model suffers worse performance at > 640 image sizes (both models were trained at --img 640). The compromise though (there's always a compromise) is that the quad model performs slightly worse at 640. So you could consider --img 640 --quad as a middle ground that trains with the speed of --img 640 but with a bit of the higher mAP seen when training directly at --img 1280 (which of course would normally take 4x longer than training at --img 640).
