### ISSUE TITLE
Mosaic problem

### ISSUE THREAD

**Issue by JoJoliking** [ultralytics/yolov5#1899]
## ❔Question
When I use --img-size = [864, 864],  and mosaic: 1.0 in finetune.yaml. I can get the normal loss value. 
But, when I set mosaic: 1.0 in finetune.yaml. I get an abnormal loss value. 
At the same time, in order to prevent the size change, I only modified this line： 
            # Letterbox
            # shape = self.batch_shapes[self.batch[index]] if self.rect else self.img_size  # final letterboxed shape
            ########################## rec ##########################
            shape = [self.rec_size[1], self.rec_size[0]]  # self.rec_size is [864, 864]]
            ########################## rec ##########################
            img, ratio, pad = letterbox(img, shape, auto=False, scaleup=self.augment)

**Comment by JoJoliking** [comment]
@glenn-jocher 
The normal loss value is :
![nromal](https://user-images.githubusercontent.com/55232435/104155203-9a0b0700-5421-11eb-9379-830178e82018.png)
The abnormal loss value is :
![2LLJXC $HLXGFTL~L8CN DJ](https://user-images.githubusercontent.com/55232435/104155243-b60ea880-5421-11eb-8c38-137aa2fcfdeb.png)

**Comment by JoJoliking** [comment]
I'm sorry. There is a problem with the problem description.
Correct :
But, when I set mosaic: 0.0 in finetune.yaml. I get an abnormal loss value.

**Comment by glenn-jocher** [comment]
@JoJoliking we don't provide support for issues originating in modified code. I would recommend training with default setttings (though you can experiment with different hyp files).
