### ISSUE TITLE
nohup output

### ISSUE THREAD

**Issue by zidanexu** [ultralytics/yolov5#19]
hi @glenn-jocher 
I running command below , I want to running the program behind backend. 
![image](https://user-images.githubusercontent.com/54395639/83876917-37a3a700-a76c-11ea-9769-1f0c26c0dab4.png)
but i find  the nohup.out file was update  very frequently,  May it is different with terminal  in show
![image](https://user-images.githubusercontent.com/54395639/83877140-99641100-a76c-11ea-86a9-601571547622.png)

**Comment by glenn-jocher** [comment]
@zidanexu I don't understand. Are you saying you want to train silently, with nothing printed to screen? What is the use case / benefit of this?
