### ISSUE TITLE
image process

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#190]
your images process do 
 img /= 255.0  # 0 - 255 to 0.0 - 1.0

do you do the mean and std ?

**Comment by glenn-jocher** [comment]
no

**Comment by alicera** [comment]
I find your output  xywh conf cls
 x[:, 5:] *= x[:, 4:5]  # conf = obj_conf * cls_conf

you dont do the exp or softmax for decode .   why

**Comment by glenn-jocher** [comment]
This output is multi-class capable, so softmax is not used. Exp is not appropriate here.

**Comment by alicera** [comment]
how to make sure the network out range is 0~1

**Comment by glenn-jocher** [comment]
@alicera you can use a sigmoid activation to transform an imput into a 0-1 bounded range 😃

**Comment by alicera** [comment]
so the yolo code , the output value will be sometime out of range 0~1 , right

**Comment by glenn-jocher** [comment]
@alicera no, all YOLOv5 outputs are sigmoid during a forward inference pass.

**Comment by alicera** [comment]
thanks
