### ISSUE TITLE
Unable to export weights into onnx

### ISSUE THREAD

**Issue by usamatariq70** [ultralytics/yolov5#1900]
Before submitting a bug report, please be aware that your issue **must be reproducible** with all of the following, otherwise it is non-actionable, and we can not help you:
 - **Current repo**: run `git fetch && git status -uno` to check and `git pull` to update repo
 - **Common dataset**: coco.yaml or coco128.yaml
 - **Common environment**: Colab, Google Cloud, or Docker image. See https://github.com/ultralytics/yolov5#environments
 
If this is a custom dataset/training question you **must include** your `train*.jpg`, `test*.jpg` and `results.png` figures, or we can not help you. You can generate these with `utils.plot_results()`.

## 🐛 Bug
Whenever I run the export command, I get the error which I shared below.

## To Reproduce (REQUIRED)

Input:
```
!export PYTHONPATH="$PWD" && python models/export.py --weights yolov5s.pt --batch 1
```

Output:
```
Traceback (most recent call last):
  File "models/export.py", line 33, in <module>
    model = attempt_load(opt.weights, map_location=torch.device('cpu'))  # load FP32 model
  File "./models/experimental.py", line 118, in attempt_load
    model.append(torch.load(w, map_location=map_location)['model'].float().fuse().eval())  # load FP32 model
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 584, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 842, in _load
    result = unpickler.load()
AttributeError: Can't get attribute 'SiLU' on <module 'torch.nn.modules.activation' from '/usr/local/lib/python3.6/dist-packages/torch/nn/modules/activation.py'>
```

## Expected behavior
That given weights should be converted into onnx weights.  Kindly let me know where I am doing anything wrong, or feel free to ask me the changes I made to run the script.

## Environment

 - Google Colab
 - torch==1.6.0+cu101
 - torchsummary==1.5.1
 - torchtext==0.3.1
 - torchvision==0.7.0+cu101
 - onnx==1.8.0
 - onnxruntime==1.6.0
 - coremltools==4.0

## Additional context
I have fixed the problem by making few changes in the files. Also when I upgrade torch to 1.7.0 I get "CoreML export failure: unexpected number of inputs for node x.2 (_ convolution): 13" error. So some issue is there too.

**Comment by glenn-jocher** [comment]
@usamatariq70 you are not meeting the requirements, specifically torch>=1.7 as the bot already mentioned above.

**Comment by usamatariq70** [comment]
> @usamatariq70 you are not meeting the requirements, specifically torch>=1.7 as the bot already mentioned above.

When I upgrade to torch>=1.7, I get this error "CoreML export failure: unexpected number of inputs for node x.2 (_convolution): 13" on yolov5s.pt

**Comment by glenn-jocher** [comment]
@usamatariq70 for CoreML you'll have to wait for a new version of coremltools that is compatible with the more recent pytorch versions. You may want to raise an issue directly on the coremltools repo regarding forward compatibility with torch>=1.7.0

**Comment by usamatariq70** [comment]
okay
Thank you

**Comment by usamatariq70** [comment]
Okay thank you

**Comment by xujuntdw111** [comment]
I meet the same question as you. Either torch=1.6 or torch=1.7 will report an error.  
Has the problem been solved？

> @usamatariq70 for CoreML you'll have to wait for a new version of coremltools that is compatible with the more recent pytorch versions. You may want to raise an issue directly on the coremltools repo regarding forward compatibility with torch>=1.7.0

**Comment by usamatariq70** [comment]
> I meet the same question as you. Either torch=1.6 or torch=1.7 will report an error.
> Has the problem been solved？
> 
> > @usamatariq70 for CoreML you'll have to wait for a new version of coremltools that is compatible with the more recent pytorch versions. You may want to raise an issue directly on the coremltools repo regarding forward compatibility with torch>=1.7.0

No I reported the issue on CoreML repo but they didnt responded yet. But if you want to convert yolov5 pretrained weights that I have cracked the way
