### ISSUE TITLE
About no object samples in train step.

### ISSUE THREAD

**Issue by www516717402** [ultralytics/yolov5#1902]
Hello authors, thank you for open great project.
I meet some question that many False detection when no object in images. How reduce this issue?
Add some samples with no object in train?

**Comment by glenn-jocher** [comment]
@www516717402 with no examples it's not possible to provide any relevant feedback.

**Comment by www516717402** [comment]
@glenn-jocher Face detect:
![image](https://user-images.githubusercontent.com/30460509/104261798-48b25480-54c1-11eb-8765-3f1741f5cb95.png)
![image](https://user-images.githubusercontent.com/30460509/104261858-62ec3280-54c1-11eb-992a-0b1bdd307eba.png)
Many False detection when no object in images

**Comment by glenn-jocher** [comment]
@www516717402 we don't provide specific advice but the generic advice that I've repeated many times here applies:

- use a larger dataset
- use a larger model
- use a larger image size
- train more epochs

**Comment by www516717402** [comment]
@glenn-jocher I know that you said. Need some no object samples in train?

**Comment by glenn-jocher** [comment]
@www516717402 the images themselves are giant no sample regions for 99% their area.

You just need to follow my first bullet point, more data.

**Comment by www516717402** [comment]
@glenn-jocher Thank your for constructive advise. I will collect more data to train.

**Comment by henbucuoshanghai** [comment]
if there has no objects in a image,and this image can not be trained?

**Comment by glenn-jocher** [comment]
@henbucuoshanghai all images loaded by the dataloader are used for training regardless of their contents.

**Comment by henbucuoshanghai** [comment]
so a image without a object               can  also  be trained  as the background?

**Comment by glenn-jocher** [comment]
@henbucuoshanghai yes that's correct.

**Comment by henbucuoshanghai** [comment]
the last one       it can be coco formate and VOC fortamt        it deesnet ,matter?  tks
