### ISSUE TITLE
ONNX to Tensorrt errors

### ISSUE THREAD

**Issue by cloud-zZ** [ultralytics/yolov5#1903]
## ❔Question
hello guys, when I set “model.model[-1].export = False“ in model/export.py and try to convert my onnx to trt model,error ocured that said "ScatterND" layer is not supported.....any one could help?

**Comment by sarpulas** [comment]
Probably the new activation functions, it's best to convert to TensorRT directly without using ONNX & parsers: https://github.com/wang-xinyu/tensorrtx
