### ISSUE TITLE
Problem with train/val split

### ISSUE THREAD

**Issue by flixmk** [ultralytics/yolov5#1904]
## ❔Question
Hello,

I have now trained multiple models with different types of techniques of getting my data. It is going to be only a single class that needs detection.
Regarding the data:
I have my data in one big image (about 30.000x20.000). A single object is well visible at 416x416 so i chose to go with that size for each input image.
1. Method:
I check every object and get a 416x416 image around it. It is randomized so the object is not always in the middle. But there are also other objects in that image which themselfes get their own image. So I end up with a large amount of images where a few are quite similar to each other aside from the shift in x and y.
After that i split in train and val randomly. Logically some of the images that are very similar get sorted into train and val. So I end up with a pretty high similarity between val and train.

2. Method:
I go through my data with a stride of 416. This way i dont have any object twice in my dataset resultung also in a way smaller dataset.
After that i again split in train and val. Now i have no overlap between those two.

So here are my results:
![Unbenannt](https://user-images.githubusercontent.com/66331106/104192333-f9b3e300-541e-11eb-87d8-729dabcd277c.PNG)
with purple being method 2 and grey being method 1. Data augmentation in both sets is fairly high.

Those are the plotted results of the purple one:
![Unbenann2t](https://user-images.githubusercontent.com/66331106/104220590-04cb3b00-5440-11eb-8196-6abc62a9daeb.PNG)

Dou you have something in mind that might cause this unstable learning grapgs? Especially the recall one just goes up and down without improvement at all.

Another note:
I have trained the yolov5s and yolov5m with method 2. Although the medium one had sligtly better metrics it performed worse on the test data. Is there a connection to my original problem?

**Comment by glenn-jocher** [comment]
@Kraufel I don't supply custom dataset advice. My general advice, as I've repeated here many times is to ignore P and R as they are not absolute metrics, you want to focus on mAP.

**Comment by flixmk** [comment]
@glenn-jocher I understand. But i am seeking general advice on designing the train and val set, since i got so total different results. (would Method 1 be considered 'cheating'?)
Also i would be interested to know if it is normal to have the mAP@0.5 fluctuate that hard?

**Comment by glenn-jocher** [comment]
@Kraufel results will vary by many factors, including your model, dataset, anchors, hyperparameters and training settings.
