### ISSUE TITLE
About iou_thres when calculate map

### ISSUE THREAD

**Issue by cmh707122660** [ultralytics/yolov5#1906]
## ❔Question
I just want to know why you calculate map by set iou_thres(nms) = 0.65. What if I set 0.6 or 0.5 and it performance better? And why you train it with 0.6 iou_thres? 
Thank you. Hope for some answers.

**Comment by glenn-jocher** [comment]
@cmh707122660 parameters are set via empirical results on COCO, tune as necessary for your dataset or use case needs.

**Comment by cmh707122660** [comment]
@glenn-jocher So can I just use pycocotools and instances_val2017.json to calculate my model map and use the first two values in the result. And if I find  which iou_thres better, I can use it as my result.

**Comment by glenn-jocher** [comment]
Yes you can test at various —iou-thres on your custom dataset to see what works best

**Comment by cmh707122660** [comment]
@glenn-jocher Get it! Thank you.
