### ISSUE TITLE
new model on custom dataset map drop

### ISSUE THREAD

**Issue by lucasjinreal** [ultralytics/yolov5#191]
Hi, after upgrade to new model (with PANet) the model seems droped some AP. Do u have any idea why?

Previous model, I can get a mAP of 0.855 in 5 epochs, new model get only 0.803 in 23 epochs and mAP doesn't increase after that. 

Do u have any idea about this problem could be?

**Comment by glenn-jocher** [comment]
@jinfagang new models increase mAP on COCO, see https://github.com/ultralytics/yolov5/commit/364fcfd7dba53f46edd4f04c037a039c0a287972#commitcomment-40114832

I can't speak for your custom dataset. If you want to understand the difference better you should train both (FPN and PANET) with the same settings and then overlay both of your results.txt files in the same results.png.

This is the last version of the repo before the PANet update:
https://github.com/ultralytics/yolov5/tree/ef58dac9631da217abf72d0e39aff59909c1f1b9

**Comment by glenn-jocher** [comment]
@jinfagang I've added a models/hub directory to archive models yamls now in 0825cb7fd891563a5e85e378d896970fc4b03604:

<img width="640" alt="Screen Shot 2020-06-24 at 11 59 52 AM" src="https://user-images.githubusercontent.com/26833433/85616241-42868480-b612-11ea-88ba-cf8bdddba687.png">

I've also added a matching hub folder to the Google Drive directory, so you should be able to train any of the fpn models with or without a pretrained checkpoint now.
<img width="903" alt="Screen Shot 2020-06-24 at 12 01 31 PM" src="https://user-images.githubusercontent.com/26833433/85616380-78c40400-b612-11ea-930b-4df5c8a6b918.png">

**Comment by glenn-jocher** [comment]
@jinfagang I had thought perhaps fpn was better for small objects, so I compared yolov5l for fpn and the new panet models, and the coco results improve across all object sizes: small, medium and large. See https://github.com/ultralytics/yolov5/pull/153#issuecomment-649144924

So I don't know what the cause of the mAP drop on your dataset is, but it seems like it's dataset specific in your case.

**Comment by lucasjinreal** [comment]
@glenn-jocher It maybe my dataset is extremly small in most cases, in addition, using moasic augmentation make it more smaller, in this cases PANet can not handle better than FPN. As for the root reason for this, hard to say which one is better. I tried revert to previous version model, it still gots better mAP and 88.5 vs 80.3, largely droped in this situation.

**Comment by seekFire** [comment]
@jinfagang the **yolov5-fpn.yaml** shows different backbone with **yolov5-panet.yaml** in models/hub, so whether the test in #153 is not strict...
