### ISSUE TITLE
 How can yolo read hundreds of images at once?

### ISSUE THREAD

**Issue by khs123** [ultralytics/yolov5#1911]
## ❔Question
I want to use yolo to detect thousands of images at once using the GPU to optimize the detect speed. How can yolo read hundreds of images at once?

## Additional context
I have about 10TB image data, my problem is to extract the image information, I use the Yolo model to do the job of detect the object that I need. Everything is fine with detecting images one by one, but with 10TB image data extracting each image makes it work so that I can handle all the heap, which is a long time according to my computer calculations, I will It took about 9 months to finish extracting the above images.
I do use python multithread but the speed results don't improve too much. So I think there is an approach that Yolo will detect batchs of image data (the GPU will process hundreds of images at the same time do it for me, which helps me reduce the time I spend dealing with stacks of images). on).
I am writing this question, hope you can suggest how to process hundreds of images at once using the GPU to optimize the detection of yolo.
Thanks

**Comment by glenn-jocher** [comment]
@khs123 you can use batched inference easily with PyTorch Hub version of YOLOv5. You can stack as many images together as you want into a batch before passing them to the model for batched inference:

### PyTorch Hub

To run **batched inference** with YOLOv5 and [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading):
```python
import torch
from PIL import Image

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)

# Images
img1 = Image.open('zidane.jpg')
img2 = Image.open('bus.jpg')
imgs = [img1, img2]  # batched list of images

# Inference
result = model(imgs)
```

**Comment by khs123** [comment]
Thank a lot, i will try

**Comment by khs123** [comment]
@glenn-jocher 
Your way for an existing model, I've got a local model that's been trained for my problem how can I use my model

**Comment by glenn-jocher** [comment]
@khs123 see PyTorch Hub Tutorial for loading custom models:
https://docs.ultralytics.com/yolov5

## Custom Models
This example loads a custom 20-class [VOC](https://github.com/ultralytics/yolov5/blob/master/data/voc.yaml)-trained YOLOv5s model `'yolov5s_voc_best.pt'` with PyTorch Hub.
```python
model = torch.hub.load('ultralytics/yolov5', 'custom', path_or_model='yolov5s_voc_best.pt')  # custom model
```

**Comment by khs123** [comment]
```
  File "check.py", line 6, in <module>
    model = torch.hub.load('ultralytics/yolov5', 'custom', path_or_model='/data/khanhdv/project/extract_identity_card/models/detector/back_detector_yolo5s.pt')
  File "/home/eway2020/.pyenv/versions/3.8.0/envs/extract_identity_card/lib/python3.8/site-packages/torch/hub.py", line 353, in load
    model = entry(*args, **kwargs)
  File "/home/eway2020/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 125, in custom
    hub_model = Model(model.yaml).to(next(model.parameters()).device)  # create
  File "/home/eway2020/.cache/torch/hub/ultralytics_yolov5_master/models/yolo.py", line 81, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=[ch])  # model, savelist
  File "/home/eway2020/.cache/torch/hub/ultralytics_yolov5_master/models/yolo.py", line 253, in parse_model
    m_ = nn.Sequential(*[m(*args) for _ in range(n)]) if n > 1 else m(*args)  # module
  File "/home/eway2020/.cache/torch/hub/ultralytics_yolov5_master/models/common.py", line 108, in __init__
    self.conv = Conv(c1 * 4, c2, k, s, p, g, act)
  File "/home/eway2020/.cache/torch/hub/ultralytics_yolov5_master/models/common.py", line 34, in __init__
    self.act = nn.SiLU() if act is True else (act if isinstance(act, nn.Module) else nn.Identity())
AttributeError: module 'torch.nn' has no attribute 'SiLU'
```
I use my custom model and different label and i get errors like this

**Comment by glenn-jocher** [comment]
@khs123 it appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below. 


## Requirements

**Python 3.8** or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including **`torch>=1.7`**. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by khs123** [comment]
I tried it and succeeded, but it doesn't seem to run my GPU. Because I checked my GPU there was no processing appearing.

**Comment by glenn-jocher** [comment]
@khs123 YOLOv5 operates as any standard PyTorch model. If you want the model on the GPU, you must move it there.

```bash
device = torch.device('cuda')
model = model.to(device)
```

**Comment by khs123** [comment]
I used it the way you suggest, there is one problem that when using this I test the model does not predict predictable results. But if you do the usual detect image one by one, it will pre-output the results, I don't know why the problem is above.

**Comment by khs123** [comment]
When I detect an image with the following code, I get predict 
```device = torch_utils.select_device('cpu')
# model = create(name='yolov5s', pretrained=True, channels=3, classes=80, autoshape=True)  # pretrained example
model_path = "/Users/macbook/Workspace/dyno/extract_identity_card/models/card_classification/yolo5s_all_id_detect.pt"
model = attempt_load(model_path, map_location=device)
card_bbox = None
label = None
score = None
img_path = "/Users/macbook/Workspace/dyno/extract_identity_card/test/00/841626349813_5adf6bcd45256.jpeg"
image = Image.open(img_path)
img, paths, arr_im0, pred = prd_img(model, img_path)
height, width = image.size
scaleX = max(width, height) / 416
for i, det in enumerate(pred):
    im0 = arr_im0[i]
    # Rescale boxes from img_size to im0 size
    img1_shape = img.shape[2:]
    img0_shape = im0.shape
    gain = min(img1_shape[0] / img0_shape[0], img1_shape[1] / img0_shape[1])  # gain  = old / new
    pad = (img1_shape[1] - img0_shape[1] * gain) / 2, (img1_shape[0] - img0_shape[0] * gain) / 2
    if det is not None:
        for item in det:
            x0, y0, x1, y1, score, category = item
            x0 = float(x0) * scaleX - pad[0] * scaleX
            y0 = float(y0) * scaleX - pad[1] * scaleX
            x1 = float(x1) * scaleX - pad[0] * scaleX
            y1 = float(y1) * scaleX - pad[1] * scaleX
            card_bbox = [int(x0), int(y0), int(x1), int(y1)]
            label = model.names[int(category)]
            score = float(score)
label
`Fusing layers... 
image 1/1 /Users/macbook/Workspace/dyno/extract_identity_card/test/00/841626349813_5adf6bcd45256.jpeg: 0.9628199934959412

'cmnd_old_back'
```
But when I use the pytorch hub load I get unpredictable, I guess there is a problem with image preprocessing. 
```from hubconf import custom
model = custom(path_or_model=model_path)
model.conf = 0.85
model.iou = 0.45
img2 = Image.open('/Users/macbook/Workspace/dyno/extract_identity_card/test/00/841626349813_5adf6bcd45256.jpeg')
imgs = [img2]  # batched list of images
results = model(imgs, size=416)
results.print()`
Result 
`

                 from  n    params  module                                  arguments                     
  0                -1  1      3520  models.common.Focus                     [3, 32, 3]                    
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]                
  2                -1  1     19904  models.common.BottleneckCSP             [64, 64, 1]                   
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]               
  4                -1  1    161152  models.common.BottleneckCSP             [128, 128, 3]                 
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]              
  6                -1  1    641792  models.common.BottleneckCSP             [256, 256, 3]                 
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]              
  8                -1  1    656896  models.common.SPP                       [512, 512, [5, 9, 13]]        
  9                -1  1   1248768  models.common.BottleneckCSP             [512, 512, 1, False]          
 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]              
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 12           [-1, 6]  1         0  models.common.Concat                    [1]                           
 13                -1  1    378624  models.common.BottleneckCSP             [512, 256, 1, False]          
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]              
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 16           [-1, 4]  1         0  models.common.Concat                    [1]                           
 17                -1  1     95104  models.common.BottleneckCSP             [256, 128, 1, False]          
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]              
 19          [-1, 14]  1         0  models.common.Concat                    [1]                           
 20                -1  1    313088  models.common.BottleneckCSP             [256, 256, 1, False]          
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]              
 22          [-1, 10]  1         0  models.common.Concat                    [1]                           
 23                -1  1   1248768  models.common.BottleneckCSP             [512, 512, 1, False]          
 24      [17, 20, 23]  1     26970  models.yolo.Detect                      [5, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
Model Summary: 283 layers, 7265882 parameters, 7265882 gradients, 16.9 GFLOPS

Adding autoShape... 
image 1/1: 1040x780

```

**Comment by glenn-jocher** [comment]
@khs123 everything is working correctly. Your model has simply not detected any objects in your image.

**Comment by khs123** [comment]
@glenn-jocher As I said above, when I write code detect an image, the model predict is successful. However, if written by detect with many images, the model cannot be predictable, you can clearly see the above code.
Way 1 predictes 'cmnd_old_back', but way 2 is not 
Here's how I load the model in Way 1 
```
def attempt_load(weights, map_location=torch_utils.select_device(config.DEVICE)):
    # Loads an ensemble of models weights=[a,b,c] or a single model weights=[a] or weights=a
    model = Ensemble()
    for w in weights if isinstance(weights, list) else [weights]:
        google_utils.attempt_download(w)
        model.append(torch.load(w, map_location=map_location)['model'].float().fuse().eval())  # load FP32 model

    if len(model) == 1:
        return model[-1]  # return model
    else:
        print('Ensemble created with %s\n' % weights)
        for k in ['names', 'stride']:
            setattr(model, k, getattr(model[-1], k))
        return model  # return ensemble

```

**Comment by khs123** [comment]
!python detect.py --weights /data/khanhdv/project/extract_identity_card/models/card_classification/yolo5s_all_id_detect.pt --img 640 --conf 0.25 --source /data/khanhdv/project/extract_identity_card/test/
![image](https://user-images.githubusercontent.com/3094602/107190892-fa3f9980-6a1d-11eb-9599-04506650bb20.png)

**Comment by glenn-jocher** [comment]
@khs123 we tested pytorch hub and it produces the same results as detect.py. Indeed one of the main purposes of the torch hub tutorial is to reproduce the same results:

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'custom', path_or_model='yolov5s.pt')

# Images
dir = 'https://github.com/ultralytics/yolov5/raw/master/data/images/'
imgs = [dir + f for f in ('zidane.jpg', 'bus.jpg')]  # batched list of images

# Inference
results = model(imgs)
results.print()  # or .show(), .save()
results.save()
```
![image](https://user-images.githubusercontent.com/26833433/107472807-76240980-6b24-11eb-9f6c-ce307268c2cb.png)

**Comment by glenn-jocher** [comment]
`python detect.py`
![zidane](https://user-images.githubusercontent.com/26833433/107472909-a1a6f400-6b24-11eb-8050-5be3f10782e7.jpg)

**Comment by khs123** [comment]
My country has just had a long holiday so today I'm back to my work, thanks for answering me but can see that there is a problem somewhere with this detect batch part, obviously with the detect an image, my model is still predictable. So do you have any suggestions for me another approach of running multiple images at the same time?

**Comment by glenn-jocher** [comment]
@khs123 you can use YOLOv5 pytorch hub models for batched inference. You can stack as many images as your devices memory can handle. See my example above https://github.com/ultralytics/yolov5/issues/1911#issuecomment-776473268

**Comment by khs123** [comment]
You go back to the old problem, using pytorch hub with my model is not predirct, you are testing with the most basic model so it will surely be predictable, with models that are trained according to the requirements of other problems like The problem I am dealing with is clearly a problem? Why are you still trying to protect that problem? ****

**Comment by salmankdurrani** [comment]
> `python detect.py` ![zidane](https://user-images.githubusercontent.com/26833433/107472909-a1a6f400-6b24-11eb-8050-5be3f10782e7.jpg)

can some please tell me how can I save the bounding box information to a list?

**Comment by glenn-jocher** [comment]
@salmankdurrani to save the bounding box information to a list after running detection with YOLOv5, you can modify the `detect.py` script to access the detection results directly from the model's output. The results contain the bounding box coordinates, confidence scores, and class IDs for each detection. Here's a simplified example of how you can achieve this:

1. After the model has performed inference on your images and you have the `results`, you can extract the detections like so:

```python
# Perform inference
results = model(imgs)

# Extract detections
detections = results.xyxy[0]  # Detections for the first image in batch
```

2. `detections` is a tensor where each row represents a detected object, and the columns are `(x1, y1, x2, y2, confidence, class)`. You can convert this tensor to a list of dictionaries for easier handling:

```python
# Convert detections to list of dictionaries
detection_list = []
for det in detections:
    bbox_dict = {
        "x1": det[0].item(),
        "y1": det[1].item(),
        "x2": det[2].item(),
        "y2": det[3].item(),
        "confidence": det[4].item(),
        "class": det[5].item()
    }
    detection_list.append(bbox_dict)
```

3. Now, `detection_list` contains the bounding box information for each detected object in a format that's easy to work with. You can print it, save it to a file, or use it as needed in your application.

Remember, this example assumes you're working with the results of a single image. If you're processing a batch of images, you'll need to iterate over `results.xyxy` to handle the detections for each image in your batch.

For more detailed information on working with the results and integrating YOLOv5 into your projects, please refer to the official Ultralytics documentation.

**Comment by salmankdurrani** [comment]
Thank you so much, this really helped me a lot. You're a lifesaver.

I also did it this way:

```
#Method 1
results = model(image_path)
for result in results:
    box_data = result.boxes.data.tolist()
    print(box_data)
    for box in box_data:
        x1, y1, x2, y2, score, class_id = box  # Unpack individual box data
```


and this way:

#Method 2

```
model_path = 'extracted_frames_eye_p02/Results/Saving_Epochs-/weights/best.pt'
model = YOLO(model_path)

image_folder = '/Users/Testing'
output_folder = '/Users/Testing/1'
all_detections = []
for image_file in os.listdir(image_folder):
   if image_file.endswith(".jpeg"):
       image_path = os.path.join(image_folder, image_file)
       results = model(image_path)

       # View results
       for result in results:
           boxes = result.boxes  # Boxes object for bbox output
           probs = result.probs  # Class probabilities
           
           
           for box in boxes.data.cpu().numpy():
               xywh = box[0:6]
               #print(xywh)
               all_detections.append(xywh)
```

**Comment by glenn-jocher** [comment]
@salmankdurrani, I'm glad to hear the information was helpful! Both methods you've shared for extracting bounding box information look solid. It's great to see you exploring different approaches to fit your specific needs. 

Method 1 directly accesses the `.boxes.data` attribute and converts it to a list, which is straightforward and effective for many use cases. Method 2 iterates over images in a folder, processes each, and accumulates all detections in a list, which is particularly useful for batch processing of images.

Remember, the choice between these methods depends on your project's requirements, such as whether you need to process images in batches or require additional information (like class probabilities) alongside the bounding boxes.

Keep up the good work, and don't hesitate to reach out if you have more questions or need further assistance. The YOLO community and the Ultralytics team are here to support your endeavors with YOLOv5. Happy coding! 🚀
