### ISSUE TITLE
Is it typical to see performance improvements after e.g. the 50th iteration?

### ISSUE THREAD

**Issue by asfarley** [ultralytics/yolov5#1913]
I'm training on my own data-set with 6 classes and about 15K total images, including training/test/validation. 

It looks like the vast majority of the improvement occurred from step 0 to 25 (with R reaching 0.8696), and I'm wondering if it's worth continuing to train beyond where I'm at now (step 38 with R reaching 0.872).

I understand this is mostly anecdotal, I'm just curious - what kind of curves are other users seeing?

**Comment by glenn-jocher** [comment]
@asfarley see https://github.com/ultralytics/yolov5#training for COCO results when training from scratch. Training from pretrained weights will differ.

**Comment by asfarley** [comment]
Thanks, I should have checked the readme more carefully.
