### ISSUE TITLE
Where is the SAM model in the project?

### ISSUE THREAD

**Issue by Flyooofly** [ultralytics/yolov5#1918]
## ❔Question

Where is the SAM model in the project?
## Additional context
Hi, I want to ask where is the SAM module in the project. And I can't find that in the cfg and the SAM code in the model part. Thank you!

**Comment by glenn-jocher** [comment]
@Flyooofly there's no such thing as a SAM module in this project, I don't know what that is.

**Comment by Flyooofly** [comment]
Thanks your reply. Because I find the yolov4 has&nbsp; a&nbsp; attention&nbsp; module&nbsp; named&nbsp; SAM that is&nbsp; a spatial&nbsp; attention module&nbsp; &nbsp;from&nbsp; the&nbsp; CHAMPIONSHIP. So&nbsp; I''m curious if the&nbsp; yolov5 also&nbsp; use this&nbsp; module. Thank&nbsp; you!



---Original---

**Comment by Flyooofly** [comment]
Oh. Sorry. I find my&nbsp; mistake&nbsp; in last&nbsp; email. The&nbsp; SAMis&nbsp; from&nbsp; CBAM. Because&nbsp; I use the phone to send&nbsp; e-mail,has this&nbsp; mistake.&nbsp;



---Original---
