### ISSUE TITLE
Extract bounding boxes from dataset

### ISSUE THREAD

**Issue by glancel** [ultralytics/yolov5#1921]
## ❔Question
Hello, everyone!

I have two questions for you:
1. I'd like to ask if anybody experimented with a way to extract bounding boxes drawn in the dataset as single images.
2. Is there a way to apply data augmentation directly with Yolo? My problem is that my dataset is very unbalanced and it will be complicated to balance as the proportion with class 1 and 2 is 5:1 (for each image of class 2 I have five times that number of class 1), so I was hoping if I could apply data augmentation to selected classes.

I am sorry if those questions are not directly related to this project but I've chosen this project for speed/reliability but more importantly for the community around.

Thank you for your help.

## Additional context

Annotation format is standard:

> 0 0.47578125 0.46875 0.20390625 0.1421875
> 1 0.1109375 0.5421875 0.2140625 0.0890625
> 1 0.0890625 0.63359375 0.17734375 0.0984375
> 2 0.31015625 0.77421875 0.20859375 0.27578125

**Comment by glenn-jocher** [comment]
@glancel class imbalances may not be a significant issue as you think for a 2:1 ratio. COCO suffers from extreme class imbalances worse than 100:1 and trains just fine with default settings, as you can see in labels.jpg here, one of your dataset  introspection images created automatically when training YOLOv5.
![labels](https://user-images.githubusercontent.com/26833433/104484359-10248080-557e-11eb-803c-3e49863865ff.jpg)

On your second question, data augmentation is done automatically during training. Augmentation hyperparameters are found in data/hyp.scratch.yaml.
![YOLOv5 augmentation](https://user-images.githubusercontent.com/26833433/104484328-0733af00-557e-11eb-90a9-4680f54b2d4f.jpg)
