### ISSUE TITLE
Any plans for adding support for softpool？

### ISSUE THREAD

**Issue by Wulingtian** [ultralytics/yolov5#1922]

**Comment by glenn-jocher** [comment]
@Wulingtian hi there! Could you provide some references for softpool? What does it do?

**Comment by lucasjinreal** [comment]
I think it's something here: https://github.com/alexandrosstergiou/SoftPool/blob/master/pytorch/CUDA/softpool_cuda_kernel.cu

But that's also not support very well in terms of deployment

**Comment by glenn-jocher** [comment]
@jinfagang ah looks interesting. Might be a good replacement for the maxpool layers in the SPP() module, but yes export would likely not be possible in much a model.

**Comment by Wulingtian** [comment]
@glenn-jocher https://github.com/DingXiaoH/RepVGG adding support for RepVGG?

**Comment by glenn-jocher** [comment]
@Wulingtian RepVGG results look impressive. How can they train with the extra 1x1 convolutions and shortcuts but then remove them for inference?
