### ISSUE TITLE
Training problem: batch iteration speed is different

### ISSUE THREAD

**Issue by Bilgee** [ultralytics/yolov5#1924]
I am using several Google Colab notebooks to train my model. 
But It shows different batch iteration speed. One of them is very slow. 

fold=0, 1, ...

!python train.py \
  --img 1024 --batch 4 --epochs 50 --data fold{fold}.yaml \
  --cfg models/yolov5x.yaml --hyp hyp.yaml --name yolov5x_fold{fold} --weights yolov5x.pt --cache-images --single-cls

Notebook#1: 0/49     9.48G     0.115    0.07476         0     0.1897      32      1024:   3% 12/475 [01:32<59:44,  **7.74s/it**]
Notebook#2: 0/49     9.69G    0.1008   0.06022         0     0.161        24      1024:  71% 341/478 [05:08<02:03,  **1.10it/s**]

I do not understand why It happens. I think that --img option takes all images into 1024x1024 and the batch iteration speed must be almost same right?

**Comment by glenn-jocher** [comment]
@Bilgee you want an apples to apples comparison. Different notebooks may have different hardware, gpus, etc.

**Comment by Bilgee** [comment]
@glenn-jocher I have checked CPU, GPU info. It was almost same.

**Comment by glenn-jocher** [comment]
@Bilgee different instances in colab carry no guarantee of identical performance.
