### ISSUE TITLE
请问如何在不重新训练模型的情况下，使模型只识别一个类别，比如car？

### ISSUE THREAD

**Issue by wk294701718** [ultralytics/yolov5#1928]

**Comment by LongxingTan** [comment]
在所有识别结果里，把想要的那一类筛出来就好了

**Comment by wudashuo** [comment]
请仔细阅读代码，detect.py里有个参数指令是`--classes`
另外，你用中文提问作者是看不懂的，使用英文所有人都能看懂，使用中文就只能期望同胞看到并且恰巧还知道答案

**Comment by charmere** [comment]
你可以在模型推理后，将所有不是你想要的哪一类的结果设为unknown，也就是LongxingTan所说上的筛选。
或许你希望最终的识别结果只有汽车，如果不重新训练模型的话，这是做不到的。
