### ISSUE TITLE
I want to make a images file what divided images in test.py 

### ISSUE THREAD

**Issue by LEEGILJUN** [ultralytics/yolov5#1931]
hi
when i run the test.py
it was made a one page of image plot. 
The 16 images are combined into one.
but i want to each other divided image what another the labels and prediction images.
because an combined image is very small size.
how can i make the divided images?

**Comment by glenn-jocher** [comment]
@LEEGILJUN you might repeat your command at --batch size 1, or you can use detect.py to annotate individual images.
