### ISSUE TITLE
I don't know why val obj_loss↑ 

### ISSUE THREAD

**Issue by HongYg** [ultralytics/yolov5#1932]
## ❔Question
I think have problem.
val obj_loss increase

Is it right?

## Additional context
![image](https://user-images.githubusercontent.com/45381411/104549615-915f3e80-5676-11eb-923a-f023ce4e4de2.png)
![image](https://user-images.githubusercontent.com/45381411/104550431-2c0c4d00-5678-11eb-8f8a-181f8aadae13.png)
![image](https://user-images.githubusercontent.com/45381411/104551946-2bc18100-567b-11eb-8683-c0d03f51ee27.png)

**Comment by glenn-jocher** [comment]
@HongYg your results are strange, mostly because your val box loss is zero, indicating no labelled objects in your validation set.

**Comment by HongYg** [comment]
> @HongYg 결과는 이상합니다. 대부분 val box 손실이 0이기 때문에 유효성 검사 세트에 레이블이 지정된 개체가 없음을 나타냅니다.

my dataset composition

yolov5-master - data - custom - images - train
                                                                 - val
yolov5-master - data - custom - labels   - train
                                                                 - val

and I tried train , using train, val same address like coco128.
but always val box is zero.

![image](https://user-images.githubusercontent.com/45381411/104662799-e64e9380-570e-11eb-9b32-81fcac832110.png)

**Comment by glenn-jocher** [comment]
@HongYg according to your screenshot above everything is fine. You have training targets (5 and 4), and you have 28,000 validation targets. Your mAP is 0.996, I'd say you should be pretty happy with the results.

If the wandb plots are incorrect, don't worry about them, it may simply be a wandb logging issue and not actually affecting your model.
