### ISSUE TITLE
The training speed of single machine multi GPU is slow

### ISSUE THREAD

**Issue by Mrgao9** [ultralytics/yolov5#1933]
## ❔Question
The training speed of single machine multi GPU is slow

## Additional context
I look forward to your help in answering this question！
I use rtx3090 graphics card to train coco128 data set, epochs is 300, batch size is 122, and the training time is 10 minutes;
In the single machine multi card mode, using 8 K80 graphics cards, I used DP mode and DDP mode for training, epochs is 300 and batch size is 520, but the training time is 26 minutes；
I refer to the training methods of several GPUs in this link：https://github.com/ultralytics/yolov5/issues/475
![image](https://user-images.githubusercontent.com/22071198/104557074-9672bc80-567b-11eb-89d6-f2ede26fdf0f.png)

$ python -m torch.distributed.launch --nproc_per_node 8 train.py  --batch-size 520 --data coco128.yaml --weights yolov5s.pt

The training log is as follows：
![image](https://user-images.githubusercontent.com/22071198/104556860-3f6ce780-567b-11eb-9d65-7abc6a312547.png)

Why is the training speed slower than rtx3090?

I look forward to your help in answering this question！

**Comment by glenn-jocher** [comment]
@Mrgao9 K80 is an extremely slow GPU, you're better of with the 3090.

**Comment by Mrgao9** [comment]
> @Mrgao9 K80 is an extremely slow GPU, you're better of with the 3090.

Thank you very much for your reply! I know that the computing power of K80 is very low, but I have eight K80 graphics cards on one server and use eight K80 at the same time. Will the training speed still be slower than 3090 graphics card?

**Comment by glenn-jocher** [comment]
@Mrgao9 yes. K80's are essentially useless.

**Comment by Mrgao9** [comment]
> @Mrgao9 yes. K80's are essentially useless.

Thank you again for your reply. Your reply has benefited me a lot! 

When training with K80, the batch size is increased from 520 to 960, but the training duration is the same. Is there a problem?

$ python -m torch.distributed.launch --nproc_per_node 8 train.py --batch-size 520 --data coco128.yaml --weights yolov5s.pt
-->
$ python -m torch.distributed.launch --nproc_per_node 8 train.py --batch-size 960--data coco128.yaml --weights yolov5s.pt
