### ISSUE TITLE
Question about the License of my implementation of yolov5 in tensorflow

### ISSUE THREAD

**Issue by LongxingTan** [ultralytics/yolov5#1935]
## ❔Question
Hey ultralytics,
I implemented a small yolov5 in tensorflow, [https://github.com/LongxingTan/Yolov5](https://github.com/LongxingTan/Yolov5).

When I implement this, for sure the main idea is referring to this great repo. I noticed the license is GPL.
So should I inherit the same license with yours, or i'm free to choose whatever I want? （i am not an expert of copyright at all)

Thanks for the nice code,
Longxing

**Comment by glenn-jocher** [comment]
@LongxingTan hi there, thanks for asking! Very cool that you created a TF implementation. The GPL 3.0 license that YOLOv5 has allows for usage for any purpose (including commercial), the only main requirement is that if you modify the code then your modifications should also be open-sourced under the same GPL 3.0 license. 

So if you created a TF implementation, then assigning it a GPL 3.0 license is all you need to do to stay compliant with the license :)

**Comment by LongxingTan** [comment]
@glenn-jocher 
Hey Glenn, thanks for your reply,  great.
Then no problem , I will also add a GPL3.0 license, and continue to improve it.

**Comment by solisoares** [comment]
Hi @glenn-jocher,

I am using YOLOv5 **as it is** in my repo for detection of interactions in therapy sessions.

Two questions:

1)  Using **as it is** without modification, like a library, also implies the use of GPLv3?

2) If "yes" for above, can I add copyright notice **to me**, at the beginnig of the files that **only I created**? 
Something like: 
```
Therapy Interacions Detector by Alexandre, GPL-3.0 license
```

**Comment by solisoares** [comment]
Hi @glenn-jocher,

I am using YOLOv5 as it is in my repo for detection of interactions in therapy sessions.

Two questions:

1) Using **as it is** without modification, like a library, also implies the use of GPLv3?

2) If "yes" for above, can I add copyright notice **to me**, at the beginnig of the files that **only I created**?
Something like:
```
Therapy Interacions Detector by solisoares, GPL-3.0 license
```

**Comment by glenn-jocher** [comment]
@solisoares 

1) Yes, using YOLOv5 "as is" without modification means you are using it under the terms of the GPLv3 license.

2) You are free to add a copyright notice to your own contributions at the beginning of the files you created. This is commonly done to distinguish your original work within the project while still complying with the GPL-3.0 license.

Happy coding!

**Comment by solisoares** [comment]
Thank you for the answer, I didn't add my copyright notices yet, but the code base is already under GPLv3 (https://github.com/solisoares/therapy-aid-tool)

**Comment by glenn-jocher** [comment]
@solisoares you're very welcome! It's great to hear your project is already in compliance with the GPLv3 license. Should you have any more questions or need further assistance, feel free to ask. Good luck with your therapy interactions detector project!
