### ISSUE TITLE
eorr when testing the model

### ISSUE THREAD

**Issue by phunix9** [ultralytics/yolov5#1938]
Thanks for your work!

I changed the backbone(add head). Everything was normal during training and verification.  However, when I get the best.pt and test the model, an error happened.

AttributeError: 'int' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.

Is this related to the dictionary of the  model? Can anyone help me?

Thanks!

**Comment by glenn-jocher** [comment]
@phunix9 it's likely related to your modifications. You should be able to modify the yaml files and change the architecture and train and save without issue, but if you've modified the code then we can't be of help.

If the error is reproducible please provide code or a colab notebook to reproduce. Thank you.
