### ISSUE TITLE
torch.nn.modules.module.ModuleAttributeError: 'Hardswish' object has no attribute 'inplace'

### ISSUE THREAD

**Issue by lucasjinreal** [ultralytics/yolov5#1939]
torch.nn.modules.module.ModuleAttributeError: 'Hardswish' object has no attribute 'inplace'

**Comment by StuLiu** [comment]
open ~/.local/lib/python3.8/site-packages/torch/nn/modules/activation.py
'return F.hardswish(input, self.inplace)' replace with 'return F.hardswish(input)'
————————————————
版权声明：本文为CSDN博主「Qslia」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/qq_28321119/article/details/114405292
