### ISSUE TITLE
TypeError: non_max_suppression() got an unexpected keyword argument 'fast'

### ISSUE THREAD

**Issue by Aaron3963** [ultralytics/yolov5#194]
Error log:
image 1/12 sample\203041.jpg: Traceback (most recent call last):
  File "detect.py", line 158, in <module>
    detect()
  File "detect.py", line 68, in detect
    fast=True, classes=opt.classes, agnostic=opt.agnostic_nms)
TypeError: non_max_suppression() got an unexpected keyword argument 'fast'

traced back to line 68 in detect.py:
pred = non_max_suppression(pred, opt.conf_thres, opt.iou_thres,
                                   fast=True, classes=opt.classes, agnostic=opt.agnostic_nms)

There is a "fast" parameter, so I went to find where it was defined, and I traced to ./utils/utils.py Line 542:
def non_max_suppression(prediction, conf_thres=0.1, iou_thres=0.6, merge=False, classes=None, agnostic=False):
There is a merge parameter instead of fast, I used the history version and found out that the "fast" parameter was replaced as "merge"

So I fixed the parameter in detect.py by replacing "fast" to "merge", and everything is fine :D

**Comment by glenn-jocher** [comment]
@Aaron3963 this bug has been resolved for several days now. Git pull, as your code is out of date.
