### ISSUE TITLE
about multi scaling 

### ISSUE THREAD

**Issue by xilinniao123** [ultralytics/yolov5#1941]
## ❔Question

is the 'scale' param in random_perspective is a little same as 'multi_scale'?
## Additional context
` 
def random_perspective(img, targets=(), degrees=0, translate=.1, scale=.1, shear=10, perspective=0.0, border=(0, 0)):

    height = img.shape[0] + border[0] * 2  # shape(h,w,c)

    width = img.shape[1] + border[1] * 2

    # Center
    C = np.eye(3)

    C[0, 2] = -img.shape[1] / 2  # x translation (pixels)
    C[1, 2] = -img.shape[0] / 2  # y translation (pixels)

    # Perspective
    P = np.eye(3)
    P[2, 0] = random.uniform(-perspective, perspective)  # x perspective (about y)
    P[2, 1] = random.uniform(-perspective, perspective)  # y perspective (about x)

    # Rotation and Scale 
    R = np.eye(3)
    a = random.uniform(-degrees, degrees)
    # a += random.choice([-180, -90, 0, 90])  # add 90deg rotations to small rotations
    s = random.uniform(1 - scale, 1 + scale)
    # s = 2 ** random.uniform(-scale, scale)
    R[:2] = cv2.getRotationMatrix2D(angle=a, center=(0, 0), scale=s)`

**Comment by glenn-jocher** [comment]
@hitxujian 'scale' hyperparameter scales an image contents while keeping the --img-size constant. --multi-scale scales the actual --img-size. You can see examples of 'scale' at work in our slide below.

![YOLOv5 augmentation](https://user-images.githubusercontent.com/26833433/104626385-b342cc00-564a-11eb-95bd-ea6eb380916d.jpg)
