### ISSUE TITLE
What is augmentation in the context of detection?

### ISSUE THREAD

**Issue by asfarley** [ultralytics/yolov5#1956]
I'm familiar with augmentation in the context of detection: flipping, stretching, etc to expand your data-set.

But I see that augmentation is a parameter in `detect.py` as well; how does augmentation affect inference?

**Comment by glenn-jocher** [comment]
@asfarley Test Time Augmentation (TTA) is available in test.py and detect.py for increased recall and mAP. See TTA tutorial for details:
https://docs.ultralytics.com/yolov5

**Comment by asfarley** [comment]
Thanks, I missed that tutorial link.
