### ISSUE TITLE
Is the 'classify' feature in detect.py intentionally disabled?

### ISSUE THREAD

**Issue by asfarley** [ultralytics/yolov5#1957]
In detect.py, I see:

```
classify = False
if classify:
```
And there doesn't seem to be any opportunity for `classify` to be set `True`, whereas most of the other switches are accessible via the command-line options. 

Is this intentional? Should users manually modify the code for using 2nd-stage classifiers?

**Comment by glenn-jocher** [comment]
@asfarley classification infrastructure is in place as a guide for custom 2-stage detection + classification (i.e. YOLOv5 + EfficientNet), which may reduce FPs in deployed scenarios at the obvious expense of time.

If you'd like to implement, you need a classification model trained on classes which intersect your detector classes, and yes, you'd want to set classify = True.
