### ISSUE TITLE
AttributeError: module 'wandb' has no attribute 'run'

### ISSUE THREAD

**Issue by HypnosWei** [ultralytics/yolov5#1958]
## ❔Question
When I use ipython, I just run this 
[run train.py  --epochs 2 --batch-size 32 --data ./data/train.yaml --weights ./runs/train/exp5/weights/best.pt  --cfg ./models/yolov5s.yaml ]

I already create new environment ,but it doesn't work.
I also download the whole yolov5 files again, but it doesn't work too.

but the command window show that
## Additional context
[
![bug](https://user-images.githubusercontent.com/77552198/104822585-9098f900-587e-11eb-8971-0c84076564f7.PNG)

**Comment by glenn-jocher** [comment]
@HypnosWei you code may be out of date. Is this reproducible with current master? If so please submit a colab notebook we can us to reproduce and debug. Thank you!

**Comment by HypnosWei** [comment]
I try to pip install wanb and it work ,the code keep update ? It is very awesome! 
I am a student and try to finish the final project about object detect, but the best mAP of our  training model is just 0.458 . I want to try the data augmentation , but find the  hyp.scratch.yaml has flip and some of trick, so I  don't know how can improve the result . if you have  some better recommendation ,I will very thank you!!

![end](https://user-images.githubusercontent.com/77552198/104823202-731a5e00-5883-11eb-8bdc-0f50bb89d7d6.PNG)

sorry about my pool english .

**Comment by glenn-jocher** [comment]
@HypnosWei great, so everything is working correctly now?

For training tips you may want to upload your results. If this is a custom training ❓ Question, please provide as much information as possible, including dataset images, training logs, screenshots, and a public link to online W&B logging if available.

**Comment by mattpopovich** [comment]
Just to clarify for anyone else with this issue, you get it probably because you do not have `wandb` installed. Installing it via `pip install wandb` fixed the issue for me!

**Comment by glenn-jocher** [comment]
@mattpopovich @AyushExel this is likely due to wandb creating a wandb directory, which is then not differentiable from a package import. I've raised this issue with W&B before.

**Comment by AyushExel** [comment]
@glenn-jocher this can be solved if we include the library components in check
```
    try:
        import wandb
        from wandb import init, log, join  # test that these are available
    except ImportError:
       print("msg")
```

**Comment by glenn-jocher** [comment]
Update: This may be fixed now in PR # 2574.

**Comment by mattpopovich** [comment]
Looks good to me. As expected, now gives a notice to install wandb if it's not already installed and no longer crashes before training. 
```
github: skipping check (Docker image)                                                                                                                                            
YOLOv5 🚀 v4.0-142-g1bf9365 torch 1.8.0a0+52ea372 CUDA:2 (GeForce GTX 1080, 8119.5625MB)                                                                                         
                                                                                                                                                                                 
Namespace(adam=False, artifact_alias='latest', batch_size=16, bbox_interval=-1, bucket='', cache_images=False, cfg='', data='./data/coco128.yaml', device='2', entity=None, epoch
s=5, evolve=False, exist_ok=False, global_rank=-1, hyp='data/hyp.scratch.yaml', image_weights=False, img_size=[640, 640], linear_lr=False, local_rank=-1, multi_scale=False, name
='test', noautoanchor=False, nosave=False, notest=False, project='runs/train', quad=False, rect=False, resume=False, save_dir='runs/train/test8', save_period=-1, single_cls=Fals
e, sync_bn=False, total_batch_size=16, upload_dataset=False, weights='yolov5s.pt', workers=8, world_size=1)                                                                      
Start Tensorboard with "tensorboard --logdir runs/train", view at http://localhost:6006/                                                                                         
hyperparameters: lr0=0.01, lrf=0.2, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_
pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosa
ic=1.0, mixup=0.0                                                                                                                                                                
wandb: Install Weights & Biases for YOLOv5 logging with 'pip install wandb' (recommended)                                                                                        
                                                                                                                                                                                 
                 from  n    params  module                                  arguments                                                                                            
  0                -1  1      3520  models.common.Focus                     [3, 32, 3]                                                                                           
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]        
```
