### ISSUE TITLE
Inconsistent confusion matrix

### ISSUE THREAD

**Issue by saumitrabg** [ultralytics/yolov5#1960]
## ❔Question

We are training with yolov5l.pt as a baseline with 20K+ training and 4K val datasets. There are 6 classes. 1st one shows a decent confusion matrix where I can see a high TP of 50-60%. However, with the latest epochs of new training, we are consistently seeing a high mAP (89-95%), high recall 90%+, high precision (70-80%) but the confusion matrix shows a weird matrix. As the training progresses and mAP gets better, we try the intermediate best.pt and we can detect variations of all 6 classes but over time, we only see 1-2 classes being predicted which are wrong. Background FP is 1.0. Now, for all our training, this is happening consistently.

We don't claim to get to the bottom of it and will appreciate any pointers. The img sizes are 2448x784 and we are using --rect and img 1024.
train.py --rect --img 1024 --batch 2 --epochs 50 --data coco128.yaml --weights yolov5l.pt

We will much appreciate some pointers.
<img width="1500" alt="confusion_matrix" src="https://user-images.githubusercontent.com/12634326/104830968-ef3b8400-5838-11eb-8f1c-8c4a009e38b8.png">
<img width="1500" alt="confusion_matrix (1)" src="https://user-images.githubusercontent.com/12634326/104830970-efd41a80-5838-11eb-8380-8662a958005f.png">

**Comment by saumitrabg** [comment]
Reports.
[reportYolov5.pdf](https://github.com/ultralytics/yolov5/files/5825563/reportYolov5.pdf)

**Comment by glenn-jocher** [comment]
@saumitrabg confusion matrix operates correctly. Results are a function of input parameters. You may want to review parameters here:
https://github.com/ultralytics/yolov5/blob/e8a41e8916a9372709a09a0b1c538c6425fed778/utils/metrics.py#L107-L114

and review these threads:
https://github.com/ultralytics/yolov5/pull/1474
https://github.com/kaanakan/object_detection_confusion_matrix/issues/7

**Comment by saumitrabg** [comment]
Thank you @glenn-jocher. #1474 is interesting and we will take a look.

**Comment by glenn-jocher** [comment]
@saumitrabg yes, also keep in mind that _object detection_ confusion matrices are quite new, and substantially different from the more common classification confusion matrices. 

Primarily the background will produce significant FPs at lower `conf` thresholds, and you should note that the confusion matrix `conf` is independent of the --conf argument passed to test.py. mAP benefits from the lowest --conf possible (i.e. 0.0 is best), whereas the confusion matrix will 'look' best at higher values, i.e. conf=0.9 in metrics.py L109 as the experiments I ran in https://github.com/kaanakan/object_detection_confusion_matrix/issues/7 show.

**Comment by saumitrabg** [comment]
Got it. I followed that thread you had with Kaanakan where you tried with different conf. When I tried with conf 0.6, it just shows no improvement, though it shows a high mAP score with the xl model.
<img width="1500" alt="confusion_matrix (2)" src="https://user-images.githubusercontent.com/12634326/104859784-77269a00-58dc-11eb-985d-9fddc76b151a.png">

**Comment by glenn-jocher** [comment]
@saumitrabg its unclear to me that you should expect your confusion matrix to look any certain way at a given confidence level based on your mAP. It's highly uncorrelated from mAP, which is evaluated at all confidence levels.

A dataset may produce a million FPs and a thousand TPs and still produce excellent mAP if all the FPs are gathered to the right of the PR curve, and the confusion matrix sidesteps this subtly completely.

**Comment by glenn-jocher** [comment]
@saumitrabg a confusion matrix bug was recently discovered and fixed in PR #2046. Please `git pull` to receive this update and let us know if this addresses your original issue.

**Comment by saumitrabg** [comment]
@glenn-jocher  Fantastic. We pulled in the latest and we can see a much better confusion matrix. 
![image](https://user-images.githubusercontent.com/12634326/106211311-6ea44e00-617d-11eb-9184-7f0231f895b5.png)

**Comment by glenn-jocher** [comment]
Looks great 😃
