### ISSUE TITLE
yolov5 python版可以在苹果电脑运行吗？

### ISSUE THREAD

**Issue by Tiang-88** [ultralytics/yolov5#1967]

**Comment by zhiqwang** [comment]
Why not? We could install pytorch 1.6.0+ on MacOS, so it could run yolov5.

**Comment by Tiang-88** [comment]
> 为什么不？我们可以在MacOS上安装pytorch 1.6.0+，以便它可以运行yolov5。

您好，我安装的黑苹果系统，显卡是amd5500xt.可以使用显卡加速吗

**Comment by zhiqwang** [comment]
@zzb1967736495 That's a general question for the OS you are using, I think it's a irrelevant here.

As for your question here, I don't have any experience, and I can't answer this :(

---

这个问题很难回答呀，建议到系统爱好者社区咨询一下吧
