### ISSUE TITLE
About conf_thres for map with VOC datasets

### ISSUE THREAD

**Issue by cmh707122660** [ultralytics/yolov5#1975]
## ❔Question
I want to ask for test code for VOC. For example: 
python test.py --data coco128.yaml --img 640 --conf 0.25 --iou 0.5 --weights 'test.pt'
For COCO it should be conf = 0.01 and nms_iou various.
But I don't know how to set conf and nms_iou for VOC. 
So I want to know what you set for testing mAPs for VOC.

**Comment by cmh707122660** [comment]
Hope for your reply. Thank you.

**Comment by glenn-jocher** [comment]
@cmh707122660 I recommend you simply use test.py default settings for all datasets.

**Comment by nanhui69** [comment]
is there an intersection between voc data of 07+12  and coco(14,17 or ...) data ? @glenn-jocher

**Comment by glenn-jocher** [comment]
partially
