### ISSUE TITLE
How to import model on cpu using pytorch hub?

### ISSUE THREAD

**Issue by gabrielguarisa** [ultralytics/yolov5#1976]
## How to import model on cpu using pytorch hub?

I trained a model on a gpu but I want to load it on the cpu using the pytorch hub.
When I try to use the template I get this error message:

validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

**Comment by glenn-jocher** [comment]
@gabrielguarisa you can load models trained anywhere using PyTorch Hub, including custom models. See PyTorch Hub Tutorial for details:
https://docs.ultralytics.com/yolov5

**Comment by gabrielguarisa** [comment]
@glenn-jocher thanks for the reply. I'm already using the pytorch hub to load the model. The problem is precisely to load the model on the CPU using the Pytorch hub custom option when the model was trained on another machine with a GPU. The error message I placed above appears in this scenario.

The solution I found was to create a file at the root of the repository to load the trained model into the cpu and save it again:
```
model = torch.load(
    "gpu_model.pt", map_location=torch.device("cpu")
)

torch.save(model, "cpu_model.pt")
```

This approach works but generates different results in detection, with confidence levels below that initially achieved.

**Comment by glenn-jocher** [comment]
@gabrielguarisa I'm not sure I follow. The official models were all trained on GPUs and I can load them properly on my iMac which is CPU only.


```python
import torch
from PIL import Image

# Model
model = torch.hub.load('ultralytics/yolov5', 'custom', 'yolov5s.pt', force_reload=True)
# Images
img1 = Image.open('data/images/bus.jpg')
# Inference
results = model(img1)
results.print()


Downloading: "https://github.com/ultralytics/yolov5/archive/master.zip" to /Users/glennjocher/.cache/torch/hub/master.zip
                 from  n    params  module                                  arguments                     
  0                -1  1      3520  models.common.Focus                     [3, 32, 3]                    
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]                
  2                -1  1     18816  models.common.C3                        [64, 64, 1]                   
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]               
  4                -1  1    156928  models.common.C3                        [128, 128, 3]                 
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]              
  6                -1  1    625152  models.common.C3                        [256, 256, 3]                 
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]              
  8                -1  1    656896  models.common.SPP                       [512, 512, [5, 9, 13]]        
  9                -1  1   1182720  models.common.C3                        [512, 512, 1, False]          
 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]              
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 12           [-1, 6]  1         0  models.common.Concat                    [1]                           
 13                -1  1    361984  models.common.C3                        [512, 256, 1, False]          
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]              
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 16           [-1, 4]  1         0  models.common.Concat                    [1]                           
 17                -1  1     90880  models.common.C3                        [256, 128, 1, False]          
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]              
 19          [-1, 14]  1         0  models.common.Concat                    [1]                           
 20                -1  1    296448  models.common.C3                        [256, 256, 1, False]          
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]              
 22          [-1, 10]  1         0  models.common.Concat                    [1]                           
 23                -1  1   1182720  models.common.C3                        [512, 512, 1, False]          
 24      [17, 20, 23]  1    229245  models.yolo.Detect                      [80, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
Model Summary: 283 layers, 7276605 parameters, 7276605 gradients, 17.1 GFLOPS
Adding autoShape... 
Image 1/1: 1080x810 4 persons, 1 buss, 
```

**Comment by glenn-jocher** [comment]
Actually, an even easier script is here (passing file paths directly):

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'custom', 'yolov5s.pt', force_reload=True)
# Inference
results = model('data/images/bus.jpg')
results.print()


Downloading: "https://github.com/ultralytics/yolov5/archive/master.zip" to /Users/glennjocher/.cache/torch/hub/master.zip
                 from  n    params  module                                  arguments                     
  0                -1  1      3520  models.common.Focus                     [3, 32, 3]                    
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]                
  2                -1  1     18816  models.common.C3                        [64, 64, 1]                   
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]               
  4                -1  1    156928  models.common.C3                        [128, 128, 3]                 
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]              
  6                -1  1    625152  models.common.C3                        [256, 256, 3]                 
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]              
  8                -1  1    656896  models.common.SPP                       [512, 512, [5, 9, 13]]        
  9                -1  1   1182720  models.common.C3                        [512, 512, 1, False]          
 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]              
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 12           [-1, 6]  1         0  models.common.Concat                    [1]                           
 13                -1  1    361984  models.common.C3                        [512, 256, 1, False]          
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]              
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 16           [-1, 4]  1         0  models.common.Concat                    [1]                           
 17                -1  1     90880  models.common.C3                        [256, 128, 1, False]          
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]              
 19          [-1, 14]  1         0  models.common.Concat                    [1]                           
 20                -1  1    296448  models.common.C3                        [256, 256, 1, False]          
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]              
 22          [-1, 10]  1         0  models.common.Concat                    [1]                           
 23                -1  1   1182720  models.common.C3                        [512, 512, 1, False]          
 24      [17, 20, 23]  1    229245  models.yolo.Detect                      [80, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
Model Summary: 283 layers, 7276605 parameters, 7276605 gradients, 17.1 GFLOPS
Adding autoShape... 
Image 1/1: 1080x810 4 persons, 1 buss, 
```

**Comment by gabrielguarisa** [comment]
I tested with the exact code you posted just changing some parts to use my own trained model:

```
import torch

# Model
model = torch.hub.load(
    "ultralytics/yolov5", "custom", "best.pt", force_reload=True
)
# Inference
results = model("1.jpg")
results.print()
```

And I get this error message:

```
Downloading: "https://github.com/ultralytics/yolov5/archive/master.zip" to /home/gabriel/.cache/torch/hub/master.zip
/home/gabriel/.virtualenvs/detection-fgv/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    model = torch.hub.load(
  File "/home/gabriel/.virtualenvs/detection-fgv/lib/python3.8/site-packages/torch/hub.py", line 370, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/home/gabriel/.virtualenvs/detection-fgv/lib/python3.8/site-packages/torch/hub.py", line 399, in _load_local
    model = entry(*args, **kwargs)
  File "/home/gabriel/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 121, in custom
    model = torch.load(path_or_model) if isinstance(path_or_model, str) else path_or_model  # load checkpoint
  File "/home/gabriel/.virtualenvs/detection-fgv/lib/python3.8/site-packages/torch/serialization.py", line 594, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/gabriel/.virtualenvs/detection-fgv/lib/python3.8/site-packages/torch/serialization.py", line 853, in _load
    result = unpickler.load()
  File "/home/gabriel/.virtualenvs/detection-fgv/lib/python3.8/site-packages/torch/serialization.py", line 845, in persistent_load
    load_tensor(data_type, size, key, _maybe_decode_ascii(location))
  File "/home/gabriel/.virtualenvs/detection-fgv/lib/python3.8/site-packages/torch/serialization.py", line 834, in load_tensor
    loaded_storages[key] = restore_location(storage, location)
  File "/home/gabriel/.virtualenvs/detection-fgv/lib/python3.8/site-packages/torch/serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "/home/gabriel/.virtualenvs/detection-fgv/lib/python3.8/site-packages/torch/serialization.py", line 151, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/home/gabriel/.virtualenvs/detection-fgv/lib/python3.8/site-packages/torch/serialization.py", line 135, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

**Comment by glenn-jocher** [comment]
@gabrielguarisa you may have environment issues. Is this reproducible in Colab?

**Comment by gabrielguarisa** [comment]
The same error in Colab.

![Captura de Tela (6)](https://user-images.githubusercontent.com/11513141/104964975-62213800-59bc-11eb-8649-109c7bc11ae1.png)

**Comment by glenn-jocher** [comment]
@gabrielguarisa hmm ok. So it is not an environment issue! Strange.

I'll see if I can reproduce with a custom coco128-trained model in Colab.

**Comment by glenn-jocher** [comment]
@gabrielguarisa I did a two step process to try to reproduce this, but was not able to, so everything appears to work correctly. My recommendation is to reclone a fresh copy of the repo (it changes daily), and retrain a new model.

## 1. Train YOLOv5s on COCO128
<img width="1430" alt="Screen Shot 2021-01-18 at 1 58 25 PM" src="https://user-images.githubusercontent.com/26833433/104966336-7ef64500-5995-11eb-8a96-770adfad0393.png">


## 2. Load last.pt as a custom model with PyTorch hub and perform CPU inference
<img width="1430" alt="Screen Shot 2021-01-18 at 1 58 29 PM" src="https://user-images.githubusercontent.com/26833433/104966340-81589f00-5995-11eb-8e4c-d3b7e4fd0667.png">

**Comment by glenn-jocher** [comment]
Adding results.save():
<img width="1430" alt="Screen Shot 2021-01-18 at 2 02 04 PM" src="https://user-images.githubusercontent.com/26833433/104966472-cd0b4880-5995-11eb-81cb-b37de360ff12.png">

**Comment by glenn-jocher** [comment]
@gabrielguarisa I realized I ran my CPU inference on a GPU-colab instance, so to be extra sure, I retested the deployment on a second CPU-only colab instance, and everything works just the same there also.

**Comment by molinajf** [comment]
Hi @glenn-jocher!, I have been faced the same issue @gabrielguarisa reported. Talking with Gabriel, we realized that the problem arises when we stop the GPU training process early and try to infer with the _best.pt_ or _last.pt_ models on CPU. We also noticed in this case  yolov5s model size (~55MB) is greater than models produced in a completed training process (~15MB).

**Comment by glenn-jocher** [comment]
@molinajf 👋 Hello! Thanks for asking about **training checkpoints**.  YOLOv5 🚀 checkpoints should be about 4X the size of final trained checkpoints, as they carry not just a FP16 model, but a FP16 [EMA](https://www.tensorflow.org/api_docs/python/tf/train/ExponentialMovingAverage) and an FP32 optimizer of the same size as the model (each model parameter has its own FP32 gradient saved within the optimizer). Final checkpoints contain only an FP16 model, with the EMA and optimizer both stripped after the final epoch of training:
https://github.com/ultralytics/yolov5/blob/b4a29b5a8d63a8c2d4a8929942b44e8969c5dddd/train.py#L423-L425

The `strip_optimizer()` function updates the checkpoint dictionary value for `model`, replacing it with `ema`, and sets `ema` and `optimizer` keys to `None`, which will reduce the checkpoint size by 3/4.
https://github.com/ultralytics/yolov5/blob/b4a29b5a8d63a8c2d4a8929942b44e8969c5dddd/utils/general.py#L741-L755

Final trained checkpoints after `strip_optimizer()` should match the README table sizes below.
<p align="center"><img width="700" alt="YOLOv5 Models" src="https://github.com/ultralytics/yolov5/releases/download/v1.0/model_comparison.png"></p>

You can also run `strip_optimizer()` manually on any checkpoint to convert it into finalized weights ready to train a new model:
```python
from utils.general import strip_optimizer

strip_optimizer('path/to/best.pt')
!python train.py --weights path/to/best.pt  # use best.pt to train a new model
```

### Model Exports

Exported models may be larger or smaller than their PyTorch starting points depending on their quantization. i.e. FP16 models will be the same size, FP32 models will be 2X the size, and INT8 models will be 0.5X the size. See YOLOv5 [Export tutorial](https://docs.ultralytics.com/yolov5/tutorials/model_export) for quantization options on model export.

Good luck 🍀 and let us know if you have any other questions!

**Comment by GianNuzzarello** [comment]
> Hi @glenn-jocher!, I have been faced the same issue @gabrielguarisa reported. Talking with Gabriel, we realized that the problem arises when we stop the GPU training process early and try to infer with the _best.pt_ or _last.pt_ models on CPU. We also noticed in this case yolov5s model size (~55MB) is greater than models produced in a completed training process (~15MB).

Have you found a solution? I also have this problem

**Comment by glenn-jocher** [comment]
@GianNuzzarello 👋 Hello! Thanks for asking about **training checkpoints**.  YOLOv5 🚀 checkpoints should be about 4X the size of final trained checkpoints, as they carry not just a FP16 model, but a FP16 [EMA](https://www.tensorflow.org/api_docs/python/tf/train/ExponentialMovingAverage) and an FP32 optimizer of the same size as the model (each model parameter has its own FP32 gradient saved within the optimizer). Final checkpoints contain only an FP16 model, with the EMA and optimizer both stripped after the final epoch of training:
https://github.com/ultralytics/yolov5/blob/b4a29b5a8d63a8c2d4a8929942b44e8969c5dddd/train.py#L423-L425

The `strip_optimizer()` function updates the checkpoint dictionary value for `model`, replacing it with `ema`, and sets `ema` and `optimizer` keys to `None`, which will reduce the checkpoint size by 3/4.
https://github.com/ultralytics/yolov5/blob/b4a29b5a8d63a8c2d4a8929942b44e8969c5dddd/utils/general.py#L741-L755

Final trained checkpoints after `strip_optimizer()` should match the README table sizes below.
<p align="center"><img width="700" alt="YOLOv5 Models" src="https://github.com/ultralytics/yolov5/releases/download/v1.0/model_comparison.png"></p>

You can also run `strip_optimizer()` manually on any checkpoint to convert it into finalized weights ready to train a new model:
```python
from utils.general import strip_optimizer

strip_optimizer('path/to/best.pt')
!python train.py --weights path/to/best.pt  # use best.pt to train a new model
```

### Model Exports

Exported models may be larger or smaller than their PyTorch starting points depending on their quantization. i.e. FP16 models will be the same size, FP32 models will be 2X the size, and INT8 models will be 0.5X the size. See YOLOv5 [Export tutorial](https://docs.ultralytics.com/yolov5/tutorials/model_export) for quantization options on model export.

Good luck 🍀 and let us know if you have any other questions!
