### ISSUE TITLE
Could you please add new custom datasets other than coco128 to tutorials

### ISSUE THREAD

**Issue by TommyZihao** [ultralytics/yolov5#198]
Use real custom datasets which have different classes and different labels from coco.
To imitate real custom dataset situation.
That would help much for those who have their custom dataset which is different from coco.

**Comment by TommyZihao** [comment]
Or could you please add urls to download those demo "real" custom datasets for running. Thanks!

**Comment by glenn-jocher** [comment]
@TommyZihao see https://blog.roboflow.ai/how-to-train-yolov5-on-a-custom-dataset/ for a different custom dataset

**Comment by glenn-jocher** [comment]
We also have an open PR for voc.yaml.

**Comment by josephofiowa** [comment]
@TommyZihao Any of [these datasets ](https://public.roboflow.ai/) exported as `YOLOv5 PyTorch` can be run with this [YOLOv5 Colab notebook ](https://colab.research.google.com/drive/1gDZ2xcTOgR39tGGs-EZ6i3RTs16wmzZQ) to create another example.

**Comment by josephofiowa** [comment]
@TommyZihao Any of these [object detection datasets](https://public.roboflow.ai/object-detection) exported as `YOLOv5 PyTorch` can be run with this [YOLOv5 Colab notebook](https://colab.research.google.com/drive/1gDZ2xcTOgR39tGGs-EZ6i3RTs16wmzZQ) to create another example.

**Comment by Kreijstal** [comment]
@josephofiowa do they support models as well?
