### ISSUE TITLE
I want to change the anchor box to anchor circles, where do you think the change to be made ?

### ISSUE THREAD

**Issue by gokulsoman15** [ultralytics/yolov5#1987]

**Comment by glenn-jocher** [comment]
@gokulsoman15 you can modify detect.py plotting behavior here:
https://github.com/ultralytics/yolov5/blob/d9212140b355b84e85a473be590720eb8221766c/detect.py#L110-L113

And you can modify YOLOv5 PyTorch Hub autoshape model plotting behavior here:
https://github.com/ultralytics/yolov5/blob/d9212140b355b84e85a473be590720eb8221766c/models/common.py#L252-L256
