### ISSUE TITLE
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [32, 12, 3, 3], but got 3-dimensional input of size [1, 6, 208] instead

### ISSUE THREAD

**Issue by Tylersuard** [ultralytics/yolov5#199]
- **Current repo**: Most recent version
 - **Common dataset**: coco.yaml or coco128.yaml
 - **Common environment**: Colab
 
I attempted to convert a custom trained Pytorch Yolo v5 model to ONNX using this command:
!export PYTHONPATH="$PWD" && python models/onnx_export.py --weights ./weights/last_yolov5s_results.pt --img 416 --batch 1

And received the above error.

## To Reproduce (REQUIRED)

Input:
!export PYTHONPATH="$PWD" && python models/onnx_export.py --weights ./weights/last_yolov5s_results.pt --img 416 --batch 1

Output:
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [32, 12, 3, 3], but got 3-dimensional input of size [1, 6, 208] instead

## Expected behavior
I would like the program to output an ONNX version of the yolo model I trained.

**Comment by Tylersuard** [comment]
This does not answer my question.  Can you please show me how to convert a trained model to ONNX?  The conversion script does not seem to be working for me.

**Comment by glenn-jocher** [comment]
The script is simple. You just run it.

<img width="970" alt="Screen Shot 2020-06-24 at 10 58 05 AM" src="https://user-images.githubusercontent.com/26833433/85612608-e4f03900-b60d-11ea-9de7-1c9c8e51da3c.png">

**Comment by Tylersuard** [comment]
Thank you!!! I was using a different notebook.  When I ran this in the provided tutorial notebook it worked.  I appreciate your help and I feel silly now.

**Comment by dreamhighchina** [comment]
> Thank you!!! I was using a different notebook. When I ran this in the provided tutorial notebook it worked. I appreciate your help and I feel silly now.



> Thank you!!! I was using a different notebook. When I ran this in the provided tutorial notebook it worked. I appreciate your help and I feel silly now.

when i use pytorch==1.3.0 ,i meet the same questions.

**Comment by NingAnMe** [comment]
when i use pytorch==1.8.1 ,i meet the same questions.
this help me
```shell
export PYTHONPATH="$PWD" && python models/onnx_export.py --weights ./weights/best_yolov5x_results.pt --img 1024 1024 --batch 1
```
using two number `--img 640 640` instead one `--img 640`
