### ISSUE TITLE
Why does mere inference in yolov5 model need considerable CPU usage(30%)?

### ISSUE THREAD

**Issue by dkl78167816** [ultralytics/yolov5#1990]
## ❔Question
Thanks for your great work first. 

When I implemented my live camera detection with yolov5, I found it's a bit stuck. 

And I discovered that thought I was inference by GPU, the model would still additional use CPU.
 An coarsely observe showed about 50% usage for readstream and detect. 20% usage for readstream only. 

Through debug, I found most of cpu usage is in 
https://github.com/ultralytics/yolov5/blob/d9212140b355b84e85a473be590720eb8221766c/detect.py#L71

## Additional context
Camera info: `fps 25, resolution(1920*1080)`

Readstream and detect.

![image](https://user-images.githubusercontent.com/32244400/105160918-c1618280-5b4b-11eb-99c8-be9d1f4efe0a.png)

Only readstream
![image](https://user-images.githubusercontent.com/32244400/105161117-fa99f280-5b4b-11eb-9aa5-8f275c7fd29f.png)

GPU is working
![image](https://user-images.githubusercontent.com/32244400/105161630-8b70ce00-5b4c-11eb-916d-d676ab51a87c.png)

**Comment by glenn-jocher** [comment]
@dkl78167816 I don't understand the question. L71 is the inference forward pass, it should be consuming most time and resources, that's a good thing.
