### ISSUE TITLE
How to make model to work on LIME

### ISSUE THREAD

**Issue by akshay-gupta123** [ultralytics/yolov5#1991]
## ❔I am trying the model on LIME but it's giving an error every time:
```
error                                     Traceback (most recent call last)
<ipython-input-337-fb130e3f2aaf> in <module>()
      1 
      2 # Hide color is the color for a superpixel turned OFF. Alternatively, if it is NONE, the superpixel will be replaced by the average of its pixels
----> 3 explanation = explainer.explain_instance(np.array(img),batch_predict, top_labels=5, hide_color=0, num_samples=1000)

6 frames
/root/.cache/torch/hub/ultralytics_yolov5_master/utils/datasets.py in letterbox(img, new_shape, color, auto, scaleFill, scaleup)
    804 
    805     if shape[::-1] != new_unpad:  # resize
--> 806         img = cv2.resize(img, new_unpad, interpolation=cv2.INTER_LINEAR)
    807     top, bottom = int(round(dh - 0.1)), int(round(dh + 0.1))
    808     left, right = int(round(dw - 0.1)), int(round(dw + 0.1))

error: OpenCV(4.1.2) /io/opencv/modules/imgproc/src/resize.cpp:3363: error: (-215:Assertion failed) !dsize.empty() in function 'resize'
```

Here is my code:

```
model = torch.hub.load('ultralytics/yolov5','custom', path_or_model='/content/best.pt')
model = model.autoshape() 

def get_pil_transform(): 
    transf = transforms.Compose([
        transforms.Resize((256, 256)),
        transforms.CenterCrop(224)
    ])    

    return transf

def get_preprocess_transform():
    normalize = transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                    std=[0.229, 0.224, 0.225])     
    transf = transforms.Compose([
        transforms.ToTensor(),
        normalize
    ])    

    return transf    

pill_transf = get_pil_transform()
preprocess_transform = get_preprocess_transform()

def batch_predict(images):
    batch = torch.stack(tuple(preprocess_transform(i) for i in images), dim=0)
    logits = model(images)
    result = numpy.array(logits.xyxy[0][:,4])
    result = [[i,1-i,0] for i in result]
    return result
def get_image(path):
    with open(os.path.abspath(path), 'rb') as f:
        with Image.open(f) as img:
            return img.convert('RGB') 
            
img = get_image('/content/image-mask-estimate/data/sample-images/2.jpg')

explainer = lime_image.LimeImageExplainer()
explanation = explainer.explain_instance(np.array(pill_transf(img)),batch_predict , top_labels=5, hide_color=0, num_samples=100)
```

**Comment by glenn-jocher** [comment]
@akshay-gupta123 what is LIME?

In any case, inputs into PyTorch Hub autoshape YOLOv5 models require no input or output transforms, everything is handled automatically. Input options are shown the forward() method comments:
https://github.com/ultralytics/yolov5/blob/d9212140b355b84e85a473be590720eb8221766c/models/common.py#L182-L191

You should probably review the YOLOv5 PyTorch Hub Tutorial for proper usage examples:
https://github.com/ultralytics/yolov5#pytorch-hub

**Comment by akshay-gupta123** [comment]
@glenn-jocher Thanks for replying. I get where the problem is.
Lime is short for Local Interpretable Model-Agnostic Explanations. Each part of the name reflects something that we desire in explanations. Local refers to local fidelity - i.e.,  the explanation to really reflect the behaviour of the classifier "around" the instance being predicted.  Lime is able to explain any model without needing to 'peak' into it, so it is model-agnostic.
You can read more on:  https://github.com/marcotcr/lime

**Comment by EdwinWenink** [comment]
@akshay-gupta123 did you have succes with applying LIME to yolov5? I would be interested in your results and/or insights, if you don't mind sharing. You can find my contact details through my Github account -> personal website .

**Comment by chaitanyabunny** [comment]
I am getting error while implementing LIME on object detection pytorch model. Error is :
IndexError: index 0 is out of bounds for axis 0 with size 0
​
My code is:
[LIME_model2.txt](https://github.com/ultralytics/yolov5/files/9413191/LIME_model2.txt)

Error traceback:
![image](https://user-images.githubusercontent.com/57526671/186340756-5c05fdf8-3e83-492d-8c5e-4382d5768e2a.png)

Please help to resolve the error.

**Comment by glenn-jocher** [comment]
@chaitanyabunny hi, the issue you're facing seems to be related to the alignment between the shape of the input passed to your model and the expected input shape. 

Two things could be causing this:
1. The input format or shape expected by LIME might be different from what YOLOv5 is expecting.
2. The input image might not be preprocessed correctly before being passed to both the model and LIME.

I recommend checking the input format expected by LIME and making sure that it aligns with the format required by YOLOv5. Additionally, ensure that the preprocessing steps for the input image are consistent for both YOLOv5 and LIME. 

Please supervise the formatting of the input and the required preprocessing for both YOLOv5 and LIME and reconcile any discrepancies.

If you need further assistance with the YOLOv5 model, please refer to the YOLOv5 documentation: https://docs.ultralytics.com/yolov5/
