### ISSUE TITLE
inference anchors is not same with train achors

### ISSUE THREAD

**Issue by Kerry678231** [ultralytics/yolov5#1992]
## when i train, yolo will produce new hyperparameters of anchors(number of anchors per layer). For instance, the number of anchors will be set to 5 (the default value is 3). However, yolo will not use the new value 5, but the default value 3 anchors per layer.
please check yolov5s.yaml: anchors.

**Comment by glenn-jocher** [comment]
@Kerry678231 custom anchor counts work correctly. You simply pass a number to the `anchor:` field in your model yaml. Autoanchor does the rest.

<img width="1862" alt="Screen Shot 2021-01-20 at 12 33 30 PM" src="https://user-images.githubusercontent.com/26833433/105231546-ea6a1f00-5b1b-11eb-8325-da8777b37402.png">
