### ISSUE TITLE
“CUDA out of memory” is related to the batch-size?

### ISSUE THREAD

**Issue by ZhWL123456** [ultralytics/yolov5#1996]
## ❔Question
My environemt is Pytorch1.7 CUDA9.2 2080Ti GPU
When I set the img-size as [512, 512], there would a error "RuntimeError: CUDA out of memory. Tried to allocate 8.16 GiB (GPU 0; 10.76 GiB total capacity; 953.81 MiB already allocated; 8.16 GiB free; 1.66 GiB reserved in total by PyTorch)". But when I set the img-size as [416,416] or [640,640], there is no running problem.
This phenomenon confused me, and if there is anyone know the reason?
Thanks very much! 🌹

**Comment by isjinghao** [comment]
I also wonder why！！！✍✍

**Comment by isjinghao** [comment]
I met this problem in CUDA10.1 environment too!

**Comment by glenn-jocher** [comment]
@ZhWL123456 that's odd. In general reducing batch size or reducing image size will reduce CUDA memory consumption.

**Comment by ZhWL123456** [comment]
> @ZhWL123456 that's odd. In general reducing batch size or reducing image size will reduce CUDA memory consumption.

Thank you for replying! That's reasonable. So I have changed the sever, batchsize, device, but this problem is still exist. Maybe you can make expriment about this problem~ (I set the batchsize as 1)

**Comment by glenn-jocher** [comment]
@ZhWL123456 I've never observed this behavior myself. If this is reproducible in a common environment like Colab or Kaggle notebook please let us know, otherwise it's not actionable unfortunately and there's nothing for us to do.

**Comment by ZhWL123456** [comment]
> @ZhWL123456 I've never observed this behavior myself. If this is reproducible in a common environment like Colab or Kaggle notebook please let us know, otherwise it's not actionable unfortunately and there's nothing for us to do.

It that mean you have successlly train the model with the img-size 512 ? If so, maybe it's still my problem of setting of experiment.  Sincere thanks for you!

**Comment by glenn-jocher** [comment]
@ZhWL123456 of course we've trained at 512. You can train at any size you want. All VOC models are trained at 512, see colab notebook appendix section for VOC training commands.
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb?hl=en

**Comment by ZhWL123456** [comment]
> @ZhWL123456 of course we've trained at 512. You can train at any size you want. All VOC models are trained at 512, see colab notebook appendix section for VOC training commands.
> https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb?hl=en

Great! Thank u for your warm-heart!
