### ISSUE TITLE
How about the performance if I ONLY use ReLU activation?

### ISSUE THREAD

**Issue by densechen** [ultralytics/yolov5#1998]
## ❔In different release version, I found that the activation functions have been changed.

If I only use the ReLU activation to replace all SiLU or LeakyReLU activation, will the performance decay largely?
Does any one try this?

**Comment by glenn-jocher** [comment]
@densechen YOLOv3 uses all LeakyReLU(0.1) activations, and earlier versions of YOLOv5 used these as well. If you want a true apples to apples comparison you should train one default model and another with LeakyReLU(0.1) replacement activations. The line you'd want to modify is here:
https://github.com/ultralytics/yolov5/blob/d9212140b355b84e85a473be590720eb8221766c/models/common.py#L34

**Comment by densechen** [comment]
Thanks a lot!
I will try it!

**Comment by shipengai** [comment]
> Thanks a lot!
> I will try it!

result？can you share it？

**Comment by densechen** [comment]
The influence of different acitvation function is limited.

**Comment by glenn-jocher** [comment]
@densechen @shipengai activations have a significant impact of performance. See YOLOv5 activation study:
https://wandb.ai/glenn-jocher/activations
