### ISSUE TITLE
Live streaming after Cloud Engine

### ISSUE THREAD

**Issue by 5starkarma** [ultralytics/yolov5#2000]
## ❔Question
Hi

I have been researching this like crazy but can't seem to find much info. After running stream processing on Google Cloud Engine VM how can I feed a live stream to, say, a web browser? What stack should I look into? Say I have a security system where I need to rewind the live stream... Is this usually done using VLC/ActiveX using C++? 

Literally any help or quick pointers of where to research would help a ton. I just need to know what to google and I can figure it out from there.

**Comment by glenn-jocher** [comment]
@5starkarma I'm not sure. Seems like a good question for a full stack web developer.

You can program alerts with a python script to notify you of events fairly easily (along with grabbing screenshots of those events), but the solution is going to be a function of your requirements.

**Comment by 5starkarma** [comment]
I was afraid that might be the case. 

Have you ever played around with Jetson AGX? I just found it and wondering if it would work.

**Comment by glenn-jocher** [comment]
I haven't personally used Jetson AGX, but you can certainly deploy YOLOv5 to one. See 
https://github.com/ultralytics/yolov5/issues?q=jetson
