### ISSUE TITLE
TorchScript  Model Export

### ISSUE THREAD

**Issue by wpeak58** [ultralytics/yolov5#2002]
## ❔Question
When I run the export.py file. The following error occurred：

Starting TorchScript export with torch 1.7.0+cpu...
D:\Anaconda\lib\site-packages\torch\jit\_trace.py:940: _**TracerWarning: Encountering a list at the output of the tracer might cause the trace to be incorrect, this is only valid if the container structure does not change based on the module's inputs. Consider using a constant container instead (e.g. for `list`, use a `tuple` instead. for `dict`, use a `NamedTuple` instead). If you absolutely need this and know the side effects, pass strict=False to trace() to allow this behavior.**_
  _force_outplace,
TorchScript export success, saved as ./yolov5s.torchscript.pt

please,what can i do.thanks

**Comment by zhiqwang** [comment]
This is just a warning I guess, I think that you can ignore it.

**Comment by wpeak58** [comment]
environment is :
python = 3.8 torch=1.7 
I put export.py lines 50  model.model[-1].export = True True set False,but 
Starting TorchScript export with torch 1.7.0+cpu...
E:\qt_test\yolov5-master\yolov5-master\models\yolo.py:49: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if self.grid[i].shape[2:4] != x[i].shape[2:4]:
D:\Anaconda\lib\site-packages\torch\jit\_trace.py:940: TracerWarning: Encountering a list at the output of the tracer might cause the trace to be incorrect, this is only valid if the container structure does not change based on the module's inputs. Consider using a constant container instead (e.g. for `list`, use a `tuple` instead. for `dict`, use a `NamedTuple` instead). If you absolutely need this and know the side effects, pass strict=False to trace() to allow this behavior.
  _force_outplace,
TorchScript export success, saved as ./yolov5s.torchscript.pt

how about it ?

**Comment by zhiqwang** [comment]
> TorchScript export success, saved as ./yolov5s.torchscript.pt

**Comment by wpeak58** [comment]
> This is just a warning I guess, I think that you can ignore 
Failed to load with C++ libtorch

**Comment by wpeak58** [comment]
这一般都是模型返回的结果包含列表或者字典导致的

**Comment by wpeak58** [comment]
虽然在python上转换成功，但实际应用到LIBTORCH还是加载不成功

**Comment by zhiqwang** [comment]
Ah-ha, @wpeak58 there are two ways to resolve the `LibTorch` inference.

1. Throught `torch.jit.trace`, you can refer to the implementation in yasenh's repo [here](https://github.com/yasenh/libtorch-yolov5).
1. Another is `torch.jit.script`, you can refer to my repo [here](https://github.com/zhiqwang/yolov5-rt-stack).

**Comment by glenn-jocher** [comment]
@wpeak58 this is a Warning, not an Error. Errors say 'Error'.
