### ISSUE TITLE
Can I add some black covers to all my dataset images?

### ISSUE THREAD

**Issue by gondimjoaom** [ultralytics/yolov5#2003]
## ❔Question

I want to train an object detection model to detect chickens that are only upon that water reservoir (like the one on the picture), thus I'm currently annotating chickens in images. Since I don't want to detect any chickens on the field, I'm not annotating them. But I don't want to confuse my model by entering non annotated chickens when training it. Is there an problem to just add a cover(that will be black) like the one in the second image to all training and testing images?
I don't want to annotate chickens on the ground because each annotation costs me money. This is why I'm thinking on add this cover.

## Additional context
![image](https://user-images.githubusercontent.com/29072586/105398107-b4eb3180-5c00-11eb-9390-0afba665085b.png)
![image](https://user-images.githubusercontent.com/29072586/105398119-b9afe580-5c00-11eb-84d4-2887df816401.png)

**Comment by glenn-jocher** [comment]
@gondimjoaom your dataset should reproduce your real-world deployed conditions as closely as possible. 

If blue squares are going to be in your real-world images then they should be in your training data and vice versa.

**Comment by gondimjoaom** [comment]
I'm thinking on adding the same square on the image to be put inside the network if necessary

**Comment by lipond** [comment]
I have the similar requirements. Some crowd objects are hard to be annotated one by one, but if no annotation for them, the model may be affected because they are positive objects and regarded as false ones in training process.

**Comment by glenn-jocher** [comment]
@lipond @gondimjoaom a good approach to datasets annotation and construction is to use an iterative approach. This allows a smaller initial outlay of human effort and also allows for leveraging autolabelling and active learning techniques. This is our recommended approach.

<img width="1773" alt="Screen Shot 2021-01-21 at 7 11 50 PM" src="https://user-images.githubusercontent.com/26833433/105441105-b1fe3a00-5c1c-11eb-8a65-b5a12c907479.png">
