### ISSUE TITLE
is it valuable that add --cache-images  option to detect.py?

### ISSUE THREAD

**Issue by kyshel** [ultralytics/yolov5#2004]
## 🚀 Feature
Add --cache-images  option to detect.py like train.py

## Motivation
There R about 300k images in my--source  directory, when i run detect.py, I noticed  that it seems like load and test images **one by one** , and my pc sound  "pew-pew-pew-pew..." like a rushing laser weapon, maybe the disk is trembling. And it consumes a long time.

Maybe cached option（read from disk, and test direct in RAM） can speedup ? Or yolov5 has integrated this featue and just not provide visible option for users?

## Pitch

 Add --cache-images  option to detect.py like train.py

## Alternatives

Maybe add a script that make a big cache file from  --src imgs?

## Additional context

None.

**Comment by glenn-jocher** [comment]
@kyshel the purpose of caching images into RAM during training is that each image may be loaded hundreds or thousands of times during training. 

Inference loads each image once, therefore caching images is a meaningless concept in this setting.

**Comment by glenn-jocher** [comment]
@kyshel I think what you're looking for is `batched` inference. You can use test.py for batched inference, or you can create your own inference loop using a PyTorch Hub autoshape YOLOv5 model that also runs batched inference automatically:

### PyTorch Hub

To run **batched inference** with YOLOv5 and [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading):
```python
import torch
from PIL import Image

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)

# Images
img1 = Image.open('zidane.jpg')
img2 = Image.open('bus.jpg')
imgs = [img1, img2]  # batched list of images

# Inference
result = model(imgs)
```

**Comment by kyshel** [comment]
@glenn-jocher   Thanks a lot!
