### ISSUE TITLE
about train

### ISSUE THREAD

**Issue by zcswdt** [ultralytics/yolov5#2006]
## ❔Question
Hello, when I use the yolo5s pre-training model to train 3 classifications, do I need to change the nc of yolov5s.yaml from 80 to 3?
https://github.com/ultralytics/yolov5/blob/046c37e465d60b9047ff0e91f44594817e5a935c/models/yolov5s.yaml#L2

**Comment by glenn-jocher** [comment]
@zcswdt no. You can if you want, but it will have no effect, as the model will be created to automatically adapt to your exact dataset (inheriting the `nc:` field from your dataset.yaml).

**Comment by zcswdt** [comment]
> as the model will be created to automatically adapt to your exact dataset (inheriting the `nc:` field from your dataset.yaml).

Thank you for your reply. Another question is how can I get an anchor adapted to the data set based on my data set. I have not seen a separate code to generate an anchor.

**Comment by glenn-jocher** [comment]
@zcswdt autoanchor will automatically analyze your dataset and evolve new anchors for you if required. It's an automatic step before training starts, no action is required on your part.

**Comment by glenn-jocher** [comment]
You can force autoanchor to create new anchors if you want by specifying an anchor count in the model `anchors:` field, but this is a higher risk path and I would recommend you simply leave everything alone and let it evaluate the default anchors instead, as these are proven to behave well across strides (autoanchor does not incorporate receptive field / stride constraints at the moment).

<img width="1862" alt="Screen Shot 2021-01-20 at 12 33 30 PM" src="https://user-images.githubusercontent.com/26833433/105443513-bdebfb00-5c20-11eb-9648-5581325d677e.png">

**Comment by zcswdt** [comment]
> autoanchor will automatically analyze your dataset and evolve new anchors for you if required. It's an automatic step before training starts, no action is required on your part.

Hello, where can I set the parameters of the code to automatically generate the anchor?

**Comment by glenn-jocher** [comment]
> > autoanchor will automatically analyze your dataset and evolve new anchors for you if required. It's an automatic step before training starts, no action is required on your part.
> 
> Hello, where can I set the parameters of the code to automatically generate the anchor?

No action is required on your part, it will generate new anchors if it decides it needs to automatically.

**Comment by zcswdt** [comment]
> > > autoanchor will automatically analyze your dataset and evolve new anchors for you if required. It's an automatic step before training starts, no action is required on your part.
> > 
> > 
> > Hello, where can I set the parameters of the code to automatically generate the anchor?
> 
> No action is required on your part, it will generate new anchors if it decides it needs to automatically.

Thank you for your patience. Please tell you, such as training your own data set. Where can I print out the anchors of this data set in the code? I want to print it out to see what my own data set anchors are.
