### ISSUE TITLE
Question about yolov5 v1.0 reproduce coco val dataset  test

### ISSUE THREAD

**Issue by nancy618618618** [ultralytics/yolov5#2008]
Environment:
V100, cuda10.1
 I tried to reproduce the result of yolov5 v1.0 APval and  AP50 result, use your v1.0 code and yolov5s weights, and the comment line is python test.py --img 736 --conf 0.001。 I got the result of map50 0.55, map 0.349, which is different from the value you given, map50 0.558, map 0.366. Could you give me some suggestion that what wrong with it? Thanks.

Looking forward to your response.

**Comment by glenn-jocher** [comment]
@nancy618618618 you may be looking at repo metrics, you want to `pip install pycocotools` and view the pycocotools metrics.

**Comment by nancy618618618** [comment]
> @nancy618618618 you may be looking at repo metrics, you want to `pip install pycocotools` and view the pycocotools metrics.

Thank you for your reply, I check that pycocotools is installed, so the evaluation metrics is correctly used , however the result is still the value shown above.
