### ISSUE TITLE
Very slow inference after exporting to ONNX and running inference in ML.Net (C#)

### ISSUE THREAD

**Issue by farhanrw** [ultralytics/yolov5#2012]
First of all thanks for all the work! Recently, I have been trying to export the trained network which I trained on my own dataset to ONNX. The idea is to use this trained model to run inference at one image at a time with an existing system that i have built in c#. For running the inference i have been using the code from this repository https://github.com/BobLd/YOLOv4MLNet/tree/yolo-v5-incl (Thanks Bob!)

Now the issue is i will have to run the inference on the cpu. In python that wasn’t a problem. It would run within <100 for one image. But in ml.net i see it jump up to 2000/2300 ms. If i would like to use the bigger networks (yolo5l for example), it gets even slower. Is there anything that is causing this? Or is there a way that the time can be cut down? 

Any help or suggestion would be greatly appreciated. Thanks!

**Comment by zhiqwang** [comment]
Hi @farhanrw , For a quick review of `YOLOv4MLNet`, I think that the main reason is because of the post-process procedure, such as the `NMS`, `iou`, etc., these ops have been heavily optimized in current repo. Maybe you could only compare the model inference procedure.

**Comment by farhanrw** [comment]
Hey @zhiqwang thanks for your comment. That was my guess as well. However after doing some time analysis I came to find that most of the time is spent (about 90% of the time) in the `predict()` method which has no additional code rather than what comes with ML.Net.

**Comment by zhiqwang** [comment]
EDIT: The first image will take a long time. When calculating the inference time, we will ignore the consumed time costed by the first image. And how do you compute the inference time here?

**Comment by farhanrw** [comment]
*EDITED* Yes I am aware of the fact that the first image might take a reasonable amount of time longer than regular to run. However, I am not only looking at that but looking at a bunch of images where more or less the timings are consistently large. I am just taking a look at the terminal during running `detect.py` to get the timings for each of the images during test. In the case for ML.Net I am just doing this 

![image](https://user-images.githubusercontent.com/43019847/105529239-f3cdc580-5c9a-11eb-93f4-9b97826fd12c.png)

Here the timing I am checking is only the time to call `predict`. And still it is most of the time like ~2000ms. If I would take the yolov5l it gets upto 3500 ms. Again, all of the timings are in cpu (both in the cases for pytorch and ml.net).

**Comment by zhiqwang** [comment]
> In must cases, when calculating the inference time, we will ignore the consumed time costed by the first image.

At the first time, the model will be serialized, and this operation will consume a lot of time.

**Comment by farhanrw** [comment]
Right yes I understand, but take a look at my edited comment, the timings are more or less the same for all the images to follow 😕

**Comment by zhiqwang** [comment]
Did you have computed the inference time on the onnx (python, cpu) backend?

**Comment by farhanrw** [comment]
Thanks for taking the time to reply. No I did not test that. I thought about trying to read in the onnx using pytorch but I am not sure how to do that. Doing a few searches it is not very clear to me if pytorch supports reading in onnx files. Could you share some suggestions, please?

**Comment by zhiqwang** [comment]
It seems that ML.Net is just an C# interface of [microsoft/onnxruntime](https://github.com/microsoft/onnxruntime). And [here](https://github.com/zhiqwang/yolov5-rt-stack/blob/master/notebooks/export-onnx-inference-onnxruntime.ipynb) is a demo notebook of the usage of onnxruntime python interface.

This notebook is my experiments on yolov5, there are minor changes comparing with ultralytics official implementation now, I didn't have the snippets to test ultralytics's official model :( And I only compute the GPU backend inference time, I am not very sensitive to the CPU backend inference time.

**Comment by zhiqwang** [comment]
And I found a C# demo of faster-rcnn [here](https://github.com/microsoft/onnxruntime/tree/master/csharp/sample/Microsoft.ML.OnnxRuntime.FasterRcnnSample), Maybe you can compare yolov5 with this faster-rcnn model?

**Comment by farhanrw** [comment]
Thanks @zhiqwang. Following one of the tutorials from pytorch official and also seeing your reply I ran a test by using the `ort_session.run()` and feeding it in a random tensor of the same shape as my image and the timings are good like before <100 ms. So it probably shows the right timing in python but somehow its getting to around 2000 ms in C#. No idea why!

**Comment by farhanrw** [comment]
@zhiqwang  Thanks, let me take a look and compare!

**Comment by farhanrw** [comment]
I tested this over the last few days and noticed a few patterns. If I am running inference using the ONNX model then the inference time tends to go up significantly as the resolution increases. This is weird because, I have been getting pretty consistent speeds when I was just using detect.py for running inference. If I am running the ONNX inference in pytorch (CPU) with a resolution of 640 it tends to take around 300~400ms whereas if I am using a resolution of 1024 it jumps up to around 1200ms.

**Comment by FishWoWater** [comment]
I have encountered the same problem when using C++ with TNN to perform inference ( 3s / img for yolov5s) and it does not speed up even if I set the img size to 64 x 64, which does not make sense to me. Do you have any idea?

**Comment by kkarahainko** [comment]
@farhanrw take a look here https://github.com/mentalstack/yolov5-net, inference time ~120ms on yolov5s 640x640 without ML.NET pipeline, may be useful.

**Comment by dimleve** [comment]
@kkarahainko Well done for the code! Could you please share how did you convert the sample YOLO v5 5s model into ONNX? Did you use the Python script that is provided via this repo?

**Comment by MrRace** [comment]
Same problem~ when use `python export.py --weights models/yolov5m.pt --include onnx --simplify --inplace --device 0` to convert the `yolov5m.pt ` to onnx format, the  inference of onnx format  is much slower than the pytorch format

**Comment by AhmedEmadEldinHussin** [comment]
I solver this problem bu uninstalling onnxruntime and installing onnxrutintime-gpu
pip uninstall onnxrutime 
pip install onnxrutime-gpu

**Comment by roushrsh** [comment]
I have this exact problem. Python is fine with onnx, c# isn't. Yolo model as well...

**Comment by glenn-jocher** [comment]
@roushrsh it's possible that the difference in speed between Python and C# could be due to differences in hardware, software or version compatibility. Additionally, C# may not provide the same optimisations or libraries that are available in Python.

Here are a few things you could try to improve the inference speed in C#:
- Ensure that you are using the same versions of libraries and hardware (e.g. GPU) in both Python and C# environments
- Check if your implementation is making maximum use of hardware (e.g. using GPU instead of CPU)
- Try profiling or benchmarking techniques to identify performance bottlenecks in the C# implementation
- Consider using third-party libraries or APIs that are optimised for C# and compatible with your model

I hope this helps!

**Comment by kpimel** [comment]
Try to run several  images with same session. In my case on c++ first image run takes 3sec but next images take 9ms on GPU

**Comment by glenn-jocher** [comment]
@kpimel thank you for bringing this to our attention. We appreciate your feedback and insights regarding the performance difference when running multiple images with the same session in C++.

There can be several factors contributing to the observed behavior. Running the first image usually incurs additional setup and initialization costs, such as loading the model and allocating resources. Subsequent images can benefit from these initial costs and achieve faster inference times.

We recommend batching your inference requests where possible, as this can further improve overall inference performance. By combining multiple images into a single batch, you can leverage parallelism and optimize GPU memory usage, resulting in faster inference times.

If you require further assistance or have additional questions, please don't hesitate to ask. We're here to help!
