### ISSUE TITLE
how do I integrate my custom Yolov5 model with flask

### ISSUE THREAD

**Issue by burhanuddin03** [ultralytics/yolov5#2013]
## ❔Question

I want to integrate yolov5 model with flask and I am stuck.
How do I convert best.pt to *.weights file? so after that I will convert it to tensorflow model and integrate it with flask.  
Any other suggestions would be appreciable.

**Comment by glenn-jocher** [comment]
@burhanuddin03 YOLOv5 does not support export to the older darknet *.weights format.

Tensorflow export works well though, see #1127 for details.

**Comment by burhanuddin03** [comment]
What if I use YOLOv3 then it will possible?

**Comment by burhanuddin03** [comment]
@glenn-jocher

**Comment by Ownmarc** [comment]
why do you want to convert to Tensorflow ? Flask can work with Pytorch just fine! I serve all my yolov5 models with Flask without any issue.

**Comment by burhanuddin03** [comment]
@Ownmarc Can you please guide me how can I run detect.py file from flask or integrate it with flask api?

**Comment by decent-engineer-decent-datascientist** [comment]
I suggest you take a look at the torch hub tutorial (inference in a few lines that you could build into your project), or just read detect.py.

@glenn-jocher would you ever consider building a simple REST API to bundle into this project? With something like FastAPI, it'd only take a couple dozen lines of code.

**Comment by decent-engineer-decent-datascientist** [comment]
Thinking more than 20 seconds about it, never mind haha. It'd unnecessarily complicate the repo.

**Comment by glenn-jocher** [comment]
@decent-engineer-decent-datascientist I haven't included a model serving tutorial simply because it's not my specialty so I'm not qualified to create one. I know I've seen a lot of Flask and REST API questions though so there is significant community interest in this area. If minimal (or no) modifications are required to the repo and you know how to handle these then they might be very useful additions to the existing tutorials in https://docs.ultralytics.com/yolov5, and I could help with the associated PRs.

**Comment by glenn-jocher** [comment]
@decent-engineer-decent-datascientist the main avenue I know about is Torchserve https://pytorch.org/serve/, which seems to have some sort of AWS component available, though I admit I've never looked into it myself, so a tutorial would even benefit me at this point.

**Comment by decent-engineer-decent-datascientist** [comment]
Yea I can look into putting something together next week. I like the idea of using FastAPI as it does provide a little bit more customization, both in development and deployment. It also automagically generates swagger documentation which is dope.

Here's a simple demo of what it could look like:
http://dsbyprateekg.blogspot.com/2020/06/how-to-deploy-your-ml-model-as-fast-api.html

**Comment by glenn-jocher** [comment]
@decent-engineer-decent-datascientist oh interesting! BTW, YOLOv5 hub inference also runs directly on web URIs, so if the content that needs inference is already hosted online (rare use case I admit), then all the model needs is the web URI of the file:

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)

# Image
img = 'https://github.com/ultralytics/yolov5/raw/master/data/images/zidane.jpg'

# Inference
results = model(img)
```

**Comment by decent-engineer-decent-datascientist** [comment]
Nice! 
I got a bit of free time and threw together an example that uses just the web url functionality: 
https://gist.github.com/decent-engineer-decent-datascientist/81e04ad86e102eb083416e28150aa2a1

Just need to add the ability to receive files, and I think we'd be good to start integrating into detect.py

**Comment by decent-engineer-decent-datascientist** [comment]
You'll need to install these:
```
pip install fastapi
pip install uvicorn[standard]

**Comment by decent-engineer-decent-datascientist** [comment]
@burhanuddin03 does this gist also give you direction on how to use yolov5 with flask? The patterns are nearly the same.

**Comment by glenn-jocher** [comment]
@decent-engineer-decent-datascientist oh! That gist doesn't look too scary. It seems fastapi is doing most of the magic behind the scenes? How would one use the API for sending a local image?

Do you think we could eventually make a page with drag and drop upload capability for realtime YOLOv5 previews (assuming we kept a server up 24/7 to run this?

**Comment by decent-engineer-decent-datascientist** [comment]
@glenn-jocher Yessir, FastAPI will handle pretty much everything except the actual logic. Uploading files isn't bad either, take a look at https://fastapi.tiangolo.com/tutorial/request-files/. (this isn't in the gist)

Yea that wouldn't be terribly hard. An even moe intriguing proposition would be an [ONNX.js](https://github.com/microsoft/onnxjs) deployment. That'd allow us to setup a page that hosts the inference code (drag/drop, preview results), but the processing would be done client side. After that we wouldn't even need a server, you could just host it off GitHub io. 

This would make such a cool landing page for this project. That being said, this would be a semi-significant undertaking (10-20 hours minimum).

**Comment by decent-engineer-decent-datascientist** [comment]
Looks like there's even a yolo (granted v2) [example](https://microsoft.github.io/onnxjs-demo/#/yolo).

**Comment by glenn-jocher** [comment]
@decent-engineer-decent-datascientist interesting, yes I think a smaller model like v5s would make a good js deployment option and a good demo for people looking to go down the web app route.

There's a route for a tensorflow js deployment also, using PR https://github.com/ultralytics/yolov5/pull/1127 for the Pytorch to TF conversion. I'm not sure exactly how the NMS would be handled in js deployments in general though, do you know?

**Comment by decent-engineer-decent-datascientist** [comment]
ONNX would be more performant, but tensorflow.js is probably more comfortable for most. tf.js has a [nms function](https://js.tensorflow.org/api/latest/#image.nonMaxSuppressionWithScoreAsync).

ONNX doesn't have one, but you could use something like [this](https://github.com/OpenNMS/opennms-js).

**Comment by glenn-jocher** [comment]
@decent-engineer-decent-datascientist oh awesome, so TF does have a js NMS module. Yes, the js deployments are very interesting, they can bypass a lot of compatibility issues at the expense of performance, for a single image processing they could provide a lot of value.

**Comment by WelkinU** [comment]
> @decent-engineer-decent-datascientist oh! That gist doesn't look too scary. It seems fastapi is doing most of the magic behind the scenes? How would one use the API for sending a local image?
> 
> Do you think we could eventually make a page with drag and drop upload capability for realtime YOLOv5 previews (assuming we kept a server up 24/7 to run this?

I took some of the ideas from above and built a FastAPI wrapper using FileUpload instead of web URI. Also added some html forms/templates so you can upload an image and select model through a web browser. Code is here: https://github.com/WelkinU/yolov5-fastapi-demo

Here is an example of what it looks like in a web browser:
![image](https://user-images.githubusercontent.com/47000850/107604323-cc18b000-6bfd-11eb-9631-7c226bb2ecdf.png)

**Comment by glenn-jocher** [comment]
@WelkinU wow, very cool!

**Comment by theoll** [comment]
@WelkinU Is it possible to serve video instead image in your project?

**Comment by shubham12tomar** [comment]
> ## ❔Question
> I want to integrate yolov5 model with flask and I am stuck.
> How do I convert best.pt to *.weights file? so after that I will convert it to tensorflow model and integrate it with flask.
> Any other suggestions would be appreciable.
> 
> ## Additional context

yes you can do it by using model = custom(path/to/best.pt)
please refer yolov5/hubconf.py file
