### ISSUE TITLE
detect.py - images always saved

### ISSUE THREAD

**Issue by taqpoly2** [ultralytics/yolov5#2029]
Hello, thanks for this incredible tool.

It seems that in detect.py  save_img is always set to True - the piece of code in this piece of code.below is default
Btw It would be nice to have option to switch saving images in script call like  detect.py --saveimages. Thanks.

# Set Dataloader
    vid_path, vid_writer = None, None
    if webcam:
        view_img = True
        cudnn.benchmark = True  # set True to speed up constant image size inference
        dataset = LoadStreams(source, img_size=imgsz)
    else:
        save_img = True
        dataset = LoadImages(source, img_size=imgsz)

**Comment by glenn-jocher** [comment]
@taqpoly2 thanks for the feedback, we will take it into consideration. The current settings are mainly to demo the inference capability, with the assumption that users will customize to their own needs as appropriate. 

You might also want to see YOLOv5 PyTorch Hub inference as an alternative to detect.py, this provides much greater customizability (and images are not saved by default there):
https://github.com/ultralytics/yolov5#pytorch-hub
