### ISSUE TITLE
Is it possible to retrain on custom dataset from coco checkpoint?

### ISSUE THREAD

**Issue by batrlatom** [ultralytics/yolov5#203]
Is it possible to train on a custom dataset with a different number of classes and still use pre-trained weights?

**Comment by glenn-jocher** [comment]
Sure! You can create any type of dataset you want.

I’d recommend always trying both ways: training with and without a pretrained checkpoint, and using the best result.

**Comment by batrlatom** [comment]
Could you please help me to make it work? 
My config is from yolov5s.yaml, where the only thing I changed is nc to nc=2 .
Then I have a corresponding dataset.yaml, which is the same as your dataset yaml file for coco https://github.com/ultralytics/yolov5/blob/master/data/coco.yaml .

Then I want to start from checkpoint you provided: yolov5s.pt

I am starting the code with the following command:
python train.py --batch 12 --epochs 300 --data /home/tom/Downloads/pepe_dataset/dataset.yaml --cfg /models/yolov5s.yaml --notest --weights weights/yolov5s.pt 

If I do not use the parameter --weights, then everything works correctly, but training is somewhat slowly progressing.
When I use this param, I am getting an error that config and pt file are not compatible ( I believe this is because of the different nc ) .

**Comment by glenn-jocher** [comment]
@batrlatom yes of course. You can't train a 2 class model on 80 class coco. 

If you are training on coco.yaml, then your model must have 80 classes.

You can train on any dataset with any model as long as the `nc` parameters of each are equal.

**Comment by batrlatom** [comment]
But in principle, is it possible to slice your model, omit the last layer, change it for the different NC and use this. Am I right?

**Comment by glenn-jocher** [comment]
@batrlatom you can train on any dataset with any model (from scratch or from a pretrained checkpoint) as long as the `nc` parameters of each are equal.

You should start from the tutorial:
https://docs.ultralytics.com/yolov5/tutorials/train_custom_data

**Comment by glenn-jocher** [comment]
Model *.pt and *.yaml files are updated frequently in this repo, so if your repo downloaded an older model and you are trying to train with a recent version of the repo, it's possible your new *.yaml is incompatible with the older *.pt file you have. 

To fix this, **delete all official pretrained models from your repo and try your command again**. The newest version of the models will always be downloaded and the problem should be fixed.
