### ISSUE TITLE
NMS looks like it's missing stuff?

### ISSUE THREAD

**Issue by decent-engineer-decent-datascientist** [ultralytics/yolov5#2033]
## ❔Question
So this is really odd, and I'm not sure if this is functioning as expected or not, but it seems the NMS implementation lets overlapping detections slide by.

The examples below are with an IOU threshold of 0.2:
<img width="528" alt="Screen Shot 2021-01-24 at 3 42 03 PM" src="https://user-images.githubusercontent.com/77806775/105644795-1e677c00-5e5d-11eb-83e0-49e5358b1dc2.png">
<img width="525" alt="Screen Shot 2021-01-24 at 3 41 11 PM" src="https://user-images.githubusercontent.com/77806775/105644797-1f001280-5e5d-11eb-8e74-17f7fc33ec12.png">
<img width="216" alt="Screen Shot 2021-01-24 at 3 39 30 PM" src="https://user-images.githubusercontent.com/77806775/105644798-1f98a900-5e5d-11eb-945c-28ec1d6b902d.png">

Is this the expected behavior?

## Additional context
Using a custom model based off of yolov5L. Loading into project via torch hub.

**Comment by decent-engineer-decent-datascientist** [comment]
Just to add, I am on the latest commit, tested on both torch 1.8.0 and 1.7.1 (and the corresponding torchvision versions).

**Comment by glenn-jocher** [comment]
@decent-engineer-decent-datascientist yes this is correct. Inference settings control the amount of allowable overlap, you may want to modify these to suit your custom requirements. For YOLOv5 pytorch hub autoshape models these settings are here:
https://github.com/ultralytics/yolov5/blob/3551b072b366989b82b3777c63ea485a99e0bf90/models/common.py#L167-L173

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)

# Images
url = 'https://github.com/ultralytics/yolov5/raw/master/data/images/'
imgs = [url + x for x in ['zidane.jpg', 'bus.jpg']]  # batched list of images

# Inference
model.iou = 0.45
model.conf = 0.25
print(model.iou, model.conf)
results = model(imgs)
results.print()
```

**Comment by decent-engineer-decent-datascientist** [comment]
Yessir, I did set model.iou to 0.2 for these examples. Shouldn't 0.2 catch these duplicates? Or am I misunderstanding the threshold?

**Comment by glenn-jocher** [comment]
@decent-engineer-decent-datascientist you should vary inference parameters as you see fit for your custom data, I can't provide specific recommendations.

**Comment by decent-engineer-decent-datascientist** [comment]
Oh completely understand, but disregard the custom data. Just looking at the boxes, these overlaps are within the 0.2 IOU that we set, but they're not being removed/cleaned. Am I just being dumb haha?

**Comment by glenn-jocher** [comment]
@decent-engineer-decent-datascientist if you are not happy with the performance at the threshold you've selected, you may want to modify your threshold.

**Comment by decent-engineer-decent-datascientist** [comment]
Sounds good, I'll give it a go; thank you.
