### ISSUE TITLE
Add custom object detection with addition to coco dataset

### ISSUE THREAD

**Issue by DimaMirana** [ultralytics/yolov5#2039]
##I want to detect some custom object in addition to the pre labeled coco-dataset object. But I don't want to download the coco dataset. Is there any way to do that? ❔

**Comment by DimaMirana** [comment]
I want to detect a parson and their body parts in yolov5. The coco label already have person detected. I also have pre trained model for hand and face dataset. How to merge these two weights or add a additional label in coco.names files so that it can detect all the previous detected level and the newly customized label.

**Comment by glenn-jocher** [comment]
@DimaMirana you must train on all classes that you want to detect in deployment.

**Comment by DimaMirana** [comment]
@glenn-jocher meaning I have to download all the data annotation and also the custom data annotation, combine them together and then train the model again?

**Comment by glenn-jocher** [comment]
@DimaMirana how you obtain the datasets is up to you.

To train multiple datasets simultaneously see dataset yaml:
https://github.com/ultralytics/yolov5/blob/d68afedb32fb5f3b632f67f2cbea2c89a145f0ad/data/coco128.yaml#L12-L13
