### ISSUE TITLE
Apex O2 model cannot save 

### ISSUE THREAD

**Issue by batrlatom** [ultralytics/yolov5#204]
Before submitting a bug report, please be aware that your issue **must be reproducible** with all of the following, otherwise it is non-actionable, and we can not help you:
 - **Current repo**: run `git fetch && git status -uno` to check and `git pull` to update repo
 - **Common dataset**: coco.yaml or coco128.yaml
 - **Common environment**: Colab, Google Cloud, or Docker image. See https://github.com/ultralytics/yolov5#reproduce-our-environment
 
conda environment, normally working

## 🐛 Bug

If I use optimization level O2 ( O1 works correctly )  in amp apex settings, 
```
 if mixed_precision:
                model, optimizer = amp.initialize(model, optimizer, opt_level='O2', verbosity=0)

```
Output:
```
Traceback (most recent call last):
  File "/home/tom/PycharmProjects/pekat_vision/server/detector_yolov5/yolo_detector_trainer.py", line 524, in __start_training
    torch.save(ckpt, last)
  File "/home/tom/miniconda3/envs/pekat_vision2/lib/python3.7/site-packages/torch/serialization.py", line 370, in save
    _legacy_save(obj, opened_file, pickle_module, pickle_protocol)
  File "/home/tom/miniconda3/envs/pekat_vision2/lib/python3.7/site-packages/torch/serialization.py", line 443, in _legacy_save
    pickler.dump(obj)
AttributeError: Can't pickle local object '_initialize.<locals>.patch_forward.<locals>.new_fwd'

```

## Expected behavior
I expect to save the model correctly. 

## Environment

 - OS: Ubuntu 20.04
 - GPU 1080 Ti
 - env in Conda
 - pytorch 1.5.1, cuda 10.1

**Comment by glenn-jocher** [comment]
@batrlatom thanks for the bug report. As the message says this must be reproducible in a common environment to be actionable by us (you are not using one), as well as occur in a fresh git clone (you've modified the code).

**Comment by batrlatom** [comment]
I am going to test it in docker build from your last commit. I will let you know

**Comment by glenn-jocher** [comment]
@batrlatom ok. In any case, native mixed precision support is supposedly arriving in pytorch 1.6, so the nvidia amp code in train.py may be swapped for the under-development native tools soon. I think it's already available in pytorch nightly.
