### ISSUE TITLE
AP problem

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#2040]
## ❔Question
For example, the Image grouth have one person.
I use the network for one class to detect the image and the result have two person be detect. one is correct, the other is incorrect.

When I compute a image AP, and the AP is 1. Is it correct ?

**Comment by alicera** [comment]
https://github.com/rafaelpadilla/Object-Detection-Metrics#different-competitions-different-metrics

Which metrics do you use for yolov5 ?

PASCAL VOC Challenge  or COCO Detection Challenge

**Comment by glenn-jocher** [comment]
VOC uses mAP@0.5, COCO uses mAP@0.5:0.95.

This repo computes both. You can see this clearly in the Colab notebook for example:
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb?hl=en

**Comment by alicera** [comment]
The  "mAP@0.5"  corresponds to  https://github.com/rafaelpadilla/Object-Detection-Metrics/blob/master/pascalvoc.py

How about "mAP@0.5:0.95" ? 
Do you know where it is ?
Thanks
