### ISSUE TITLE
GPU-Util is 0

### ISSUE THREAD

**Issue by WisleyWang** [ultralytics/yolov5#2043]
## ❔Question
GPU-Util is 0%

## Additional context
I tried to train the model to my data set, but I found that the GPU utilization was zero, memory was almost full, and CPU utilization was full.The GPU is only used for test dataset calculations.
![image](https://user-images.githubusercontent.com/46738733/105805644-68776b80-5fdd-11eb-9599-928251ce9f03.png)

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.165.02   Driver Version: 418.165.02   CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:21:01.0 Off |                    0 |
| N/A   38C    P0    50W / 300W |  12793MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     10605      C   python                                     12783MiB |
+-----------------------------------------------------------------------------+

**Comment by glenn-jocher** [comment]
@WisleyWang it appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below. 


## Requirements

**Python 3.8** or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including **`torch>=1.7`**. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by WisleyWang** [comment]
@glenn-jocher  absl-py                           0.11.0
argon2-cffi                       20.1.0
async-generator                   1.10
attrs                             20.3.0
backcall                          0.2.0
bleach                            3.2.2
cachetools                        4.2.0
certifi                           2020.12.5
cffi                              1.14.4
chardet                           4.0.0
cycler                            0.10.0
Cython                            0.29.21
decorator                         4.4.2
defusedxml                        0.6.0
entrypoints                       0.3
future                            0.18.2
google-auth                       1.24.0
google-auth-oauthlib              0.4.2
grpcio                            1.35.0
idna                              2.10
ipykernel                         5.4.3
ipython                           7.19.0
ipython-genutils                  0.2.0
ipywidgets                        7.6.3
jedi                              0.18.0
Jinja2                            2.11.2
jsonschema                        3.2.0
jupyter                           1.0.0
jupyter-client                    6.1.11
jupyter-console                   6.2.0
jupyter-contrib-core              0.3.3
jupyter-core                      4.7.0
jupyter-nbextensions-configurator 0.4.1
jupyterlab-pygments               0.1.2
jupyterlab-widgets                1.0.0
kiwisolver                        1.3.1
Markdown                          3.3.3
MarkupSafe                        1.1.1
matplotlib                        3.3.3
mistune                           0.8.4
nbclient                          0.5.1
nbconvert                         6.0.7
nbformat                          5.1.2
nest-asyncio                      1.4.3
notebook                          6.2.0
numpy                             1.19.5
oauthlib                          3.1.0
opencv-python                     4.5.1.48
packaging                         20.8
pandas                            1.2.1
pandocfilters                     1.4.3
parso                             0.8.1
pexpect                           4.8.0
pickleshare                       0.7.5
Pillow                            8.1.0
pip                               21.0
prometheus-client                 0.9.0
prompt-toolkit                    3.0.11
protobuf                          3.14.0
ptyprocess                        0.7.0
pyasn1                            0.4.8
pyasn1-modules                    0.2.8
pycparser                         2.20
Pygments                          2.7.4
pyparsing                         2.4.7
pyrsistent                        0.17.3
python-dateutil                   2.8.1
pytz                              2020.5
PyYAML                            5.4.1
pyzmq                             21.0.1
qtconsole                         5.0.2
QtPy                              1.9.0
requests                          2.25.1
requests-oauthlib                 1.3.0
rsa                               4.7
scipy                             1.6.0
Send2Trash                        1.5.0
setuptools                        49.6.0.post20210108
six                               1.15.0
tensorboard                       2.4.1
tensorboard-plugin-wit            1.8.0
terminado                         0.9.2
testpath                          0.4.4
torch                             1.6.0
torchvision                       0.8.2
tornado                           6.1
tqdm                              4.56.0
traitlets                         5.0.5
typing-extensions                 3.7.4.3
urllib3                           1.26.2
wcwidth                           0.2.5
webencodings                      0.5.1
Werkzeug                          1.0.1
wheel                             0.36.2
widgetsnbextension                3.5.1

Yes, I have installed and satisfied the required environment, you can check it. The code runtime also shows the GPU 0 used

**Comment by WisleyWang** [comment]
Using CUDA device0 _CudaDeviceProperties(name='Tesla V100-SXM2-16GB', total_memory=16130MB) that is my information

**Comment by glenn-jocher** [comment]
@WisleyWang then you are all set, your CUDA device is recognized and YOLOv5 will use it automatically.
