### ISSUE TITLE
Creating bounding box on images without training / testing

### ISSUE THREAD

**Issue by faldisulistiawan** [ultralytics/yolov5#2044]
Hello. 

By using the yolov5 image directory format and label file format, how can i draw those images with the bounding box drawn? I want to use this as a data cleaning preview for the label file format. So before i train my model, i want to make sure that the bounding box are in the correct size and location.

Thank you!

**Comment by Tommydw** [comment]
@faldisulistiawan I use "labelimg" for placing the bounding boxes. With labelimg you can also open your dataset and look at each image to see if the boxes are correctly placed, these can also be changed if necessary

**Comment by glenn-jocher** [comment]
@faldisulistiawan a useful hack is that image overlays are generated automatically for the first few batches right when you start training, so you could start training, wait a few batches, ctrl+c, and then check your runs/train/exp directory for your preview images. Label statistics are also generated in labels.png, labels_correlogram.png which you should verify are in line with your expectations.


![train_batch0](https://user-images.githubusercontent.com/26833433/105909528-82647e80-5fdc-11eb-9889-e0d3a2b77dd1.jpg)

**Comment by faldisulistiawan** [comment]
@Tommydw Labelimg can read Yolov5 format?
@glenn-jocher Oh wow, thanks for the tip! Why didn't i think of that before.

**Comment by Tommydw** [comment]
@faldisulistiawan Labelimg can read YOLO format like 
`3 0.491125 0.503667 0.338750 0.421333`
The format of the label file is
`<object-class> <x> <y> <width> <height>`
![image](https://user-images.githubusercontent.com/58934176/105980362-0aa65a80-6095-11eb-9af0-ed4f4120ad6b.png)
_(Picture source: https://cloudxlab.com/blog/label-custom-images-for-yolo/)_

**Comment by faldisulistiawan** [comment]
@Tommydw Thank you so much for the info!
