### ISSUE TITLE
How to detect a target in a specified area of a picture?

### ISSUE THREAD

**Issue by wulovey** [ultralytics/yolov5#2051]
## ❔Question

How to detect a target in a specified area of a picture? At the same time, according to the classification detected in this area, only relevant classifications are detected in another area? 
This is to improve the detection speed
## Additional context
![微信截图_20210127105405](https://user-images.githubusercontent.com/75718566/105936062-0165bf80-608e-11eb-884b-1719147b78e7.png)

**Comment by glenn-jocher** [comment]
@wulovey I don't follow. Inference runs on the full image. If you'd like it to run on a subset of the image then crop that area and pass it for inference instead of the full image.
