### ISSUE TITLE
Is circular object detection possible in yolov5 using bounding circles, how to change the shape of bounding box to bounding circle for detection?

### ISSUE THREAD

**Issue by gokulsoman15** [ultralytics/yolov5#2053]

**Comment by mbl1234** [comment]
您好，请问以下您是否完成了这个问题？可以和您讨论折耳根问题吗？

**Comment by glenn-jocher** [comment]
@mbl1234 hi there! We appreciate your interest, but let's keep the conversation focused on YOLOv5-related topics. If you have any questions or need assistance with YOLOv5, feel free to ask!
