### ISSUE TITLE
Run object Detection in specified ROI (Region of Interest)

### ISSUE THREAD

**Issue by shiv-acharii** [ultralytics/yolov5#2056]
I have built a custom object detection model and it's detecting the object with good accuracy.
Now i want to build an Automatic detection of entry into a restricted area, that is I want to run this model only in a specified region of the input frame

something similar to the below image example :
![image](https://user-images.githubusercontent.com/13836633/106012660-9fcf4080-60e1-11eb-94ba-2925524e7fa3.png)

I want a box defined on the frame and detection should work only in this specified region, who can I do this using this repo ?

**Comment by glenn-jocher** [comment]
@shivprasad94 the simplest solution if you want to run inference on a subset of your image space is to crop this subset and supply it directly for inference.

**Comment by loucif01** [comment]
@glenn-jocher  can we just incorporate these regions of interests into yolov5, is there any way how to do this by using anchor boxes?

**Comment by glenn-jocher** [comment]
@loucif01 no, the two concepts are not related. Anchor boxes are normalization techniques to bring the values the model needs to estimate to unity mean and variance. 

Region of interest is just cropping an image before passing it to YOLO.

**Comment by shokirxon** [comment]
@shivprasad94 were you able to figured out running detection only on specific area of the frame?

**Comment by shiv-acharii** [comment]
@shokirxon : Yes! You need to define an ROI (it can be a polygon) and now check if points of Bounding Boxes fall inside those ROI-polygon. if it returns True, show your Bounding box displayed on Frame.

Define a function which below code to Check points inside ROI
```

import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np

#ROI polygon
vts = np.array([(230,478),(500,478),(432,154),(308,154)])
pgon = patches.Polygon(vts, color="blue", alpha=0.5)

#2 points defining a box
point1 = (300,357)  # upper-right point: (xmax,ymax) of your Bounding Box
point2 = (250,250)  # lower-left point:  (xmin,ymin) of your Bounding Box

#plot the polygon patch
fig,ax = plt.subplots()
ax.add_patch(pgon)

#check if the 2 points are inside the polygon patch?
pts_inside = pgon.contains_points(ax.transData.transform([point1, point2]))

print(pts_inside) # get [ True False] output

#plot points
ax.scatter(point1[0],point1[1], color="red", zorder=6)   # point1 inside
ax.scatter(point2[0],point2[1], color="green", zorder=6) # point2 outside

plt.show()

```

I Have used Matplotlib, but you can use Shapely,geo-points, etc library here to check if points are inside ROI..
and then you can use this output to show the bounding box on frame in the below line: 

https://github.com/ultralytics/yolov5/blob/07221f1591c0ce7544bd5abf343dac2987e1614e/detect.py#L164

**Comment by shokirxon** [comment]
> @shokirxon : Yes! You need to define an ROI (it can be a polygon) and now check if points of Bounding Boxes fall inside those ROI-polygon. if it returns True, show your Bounding box displayed on Frame.
> 
> Define a function which below code to Check points inside ROI
> 
> ```
> 
> import matplotlib.pyplot as plt
> import matplotlib.patches as patches
> import numpy as np
> 
> #ROI polygon
> vts = np.array([(230,478),(500,478),(432,154),(308,154)])
> pgon = patches.Polygon(vts, color="blue", alpha=0.5)
> 
> #2 points defining a box
> point1 = (300,357)  # upper-right point: (xmax,ymax) of your Bounding Box
> point2 = (250,250)  # lower-left point:  (xmin,ymin) of your Bounding Box
> 
> #plot the polygon patch
> fig,ax = plt.subplots()
> ax.add_patch(pgon)
> 
> #check if the 2 points are inside the polygon patch?
> pts_inside = pgon.contains_points(ax.transData.transform([point1, point2]))
> 
> print(pts_inside) # get [ True False] output
> 
> #plot points
> ax.scatter(point1[0],point1[1], color="red", zorder=6)   # point1 inside
> ax.scatter(point2[0],point2[1], color="green", zorder=6) # point2 outside
> 
> plt.show()
> ```
> 
> I Have used Matplotlib, but you can use Shapely,geo-points, etc library here to check if points are inside ROI.. and then you can use this output to show the bounding box on frame in the below line:
> 
> https://github.com/ultralytics/yolov5/blob/07221f1591c0ce7544bd5abf343dac2987e1614e/detect.py#L164

I think what you are doing is not "Run object Detection in specified ROI", but deciding wether to show the bounding boxes or not. I want to crop the frame and then run detection on cropped frame. This way I objects only with in cropped frame are detected

**Comment by robotwhispering** [comment]
I agree, you're just filtering in post-processing, which can have some negative aspects. I do the same thing currently, and I'm exploring other options to reduce the need of inferring AND filtering, 100% of the time. Imagine if the size of the object you were looking for was significantly smaller. Or for whatever reason, you felt you needed to go to higher resolution images to maximize accuracy and minimize false positives...In this case, you'd be adding more rows and columns, and you might find that you need to reduce the size of your model, or reduce your frame rate considerably. 

That's where I'm at now. I explored using "motion estimation " of comparing a few frames together for delta...if there is motion, the pixels involved in the delta region are white, and everything else is black...probably would work great if I was indoors, but outdoors, the lighting changes too much. Fortunately, I have a scene which, like yours, doesn't change much except when people pass through it. So I'm going to crop every frame by the polygon, and then run that smaller area through the nn. But imagine if you were looking down a long, straight road, and it appears to come to a point...that's how my scene looks...so I'm trying to find out if there's a away that I can change the pytorch, or torchlib, sliding kernel shape from square to triangular. And then flip it 180 degrees every stride across the image...if I can do that, I would cut my inference area down much more.

It sounds crazy, I know...but looking at this image that I've attached, how could you best reduce wasted inference time?
I'm telling you...flipping triangular kernels is the key :)

[road-wallpaper-10197594](https://user-images.githubusercontent.com/60989737/194701893-02323a68-c8de-43ef-abf1-219c274ef901.jpg)

**Comment by PredictiveEquations** [comment]
@robotwhispering Let me know what you find! I think you're onto something with approaching this from a triangle orientation. Though, I wonder now if there is another polygon that could also work?

**Comment by shivprasad94** [comment]
I have defined the below custom functions in my detect.py file based on the flag value I Display the bounding box on my screen :
def CheckRange1(_coords, r): 

    # Function which takes bounding box coordinates and polygon coordinates as r
    #is_inside_roi = False[[312, 130], [433, 137], [457, 278], [308, 282]]
    #vts = np.array([(312,130),(433,137),(457, 278),(308,282)])   [[179, 15], [122, 286], [283, 283], [257, 14]]
    vts = np.array(r)
    pgon = patches.Polygon(vts, color="blue", alpha=0.5)
    # plot the polygon patch
    fig,ax = plt.subplots()
    ax.add_patch(pgon)
    for i in _coords:
        is_inside_roi = False
        print("Values:::", i[0], i[1], i[2], i[3])
        point1 = (i[2], i[3])  # upper-right point: (xmax,ymax)
        point2 = (i[0], i[1])  # lower-left point:  (xmin,ymin)
        # check if the 2 points are inside the polygon patch?
        pts_inside = pgon.contains_points(ax.transData.transform([point2, point1]))
        if(pts_inside.any()): 
            is_inside_roi = True
            break
    return is_inside_roi
`

**Comment by animeesh** [comment]
I have created the function but I am unaware of where to call this function in detect.py?

**Comment by animeesh** [comment]
unuable to get argument _coordsin the detect.py

**Comment by glenn-jocher** [comment]
@animeesh in the `detect.py` file, you can call the `CheckRange1` function within the `Detect` class, specifically in the `def show_results` method, where you handle post-processing. You can use the `_coords` argument that is passed to the `show_results` method to call the `CheckRange1` function and determine if the detected bounding boxes fall within the specified region of interest.

Remember to import the necessary libraries, such as `matplotlib` and `numpy`, at the beginning of the `detect.py` file before using them. Also, consider refactoring your code to handle the import of these libraries in a cleaner manner, if required.

If you have any more questions or need further assistance, feel free to ask!
