### ISSUE TITLE
 how to increase precision ?

### ISSUE THREAD

**Issue by WANGCHAO1996** [ultralytics/yolov5#2060]
## ❔Question
how to increase precision ? mAP and Recall is hight but precision only 0.75 how to increase it @glenn-jocher   thank you 
## Additional context
 Epoch   gpu_mem       box       obj       cls     total   targets  img_size
    30/999     9.59G   0.06571    0.2441         0    0.3098      1777       640: 100%|██████████| 371/371 [02:49<00:00,  2.19it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 8/8 [00:05<00:00,  1.50it/s]
                 all          60    1.32e+04       0.744           1       0.991       0.751

     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
    31/999     9.59G   0.06614    0.2432         0    0.3093      1261       640: 100%|██████████| 371/371 [02:54<00:00,  2.13it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 8/8 [00:05<00:00,  1.51it/s]
                 all          60    1.32e+04       0.745           1       0.991       0.751

     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
    32/999     9.59G   0.06566    0.2433         0    0.3089      1156       640: 100%|██████████| 371/371 [02:49<00:00,  2.20it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 8/8 [00:05<00:00,  1.52it/s]
                 all          60    1.32e+04       0.746       0.999       0.991       0.752

     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
    33/999     9.59G   0.06542    0.2414         0    0.3069      1854       640: 100%|██████████| 371/371 [02:51<00:00,  2.16it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 8/8 [00:05<00:00,  1.41it/s]
                 all          60    1.32e+04       0.746           1        0.99       0.753

     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
    34/999     9.59G   0.06524    0.2414         0    0.3066      1641       640: 100%|██████████| 371/371 [02:54<00:00,  2.12it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 8/8 [00:05<00:00,  1.50it/s]
                 all          60    1.32e+04       0.746           1       0.991       0.759

**Comment by Stirfry70** [comment]
I am not sure

**Comment by decent-engineer-decent-datascientist** [comment]
So those are results at an arbitrary conf_thresh. Once the model finishes (which I think it's nearly maxed out) take a look at the P vs conf (or better yet, f1 vs conf) graph. You'll probably notice a much higher P.

Also P/R are relative based on conf_thresh. Use mAP as the true measure of performance.
