### ISSUE TITLE
Interpreting model YoloV5 by Grad-cam

### ISSUE THREAD

**Issue by hoangkhoiLE** [ultralytics/yolov5#2065]
## 🚀 Feature
I want to know more about the feature of model yolov5 by a technique Grad-cam 
REF (https://keras.io/examples/vision/grad_cam/) or another method
## Motivation
 Understand more about feature, and to combine the result heatmap with another model (detection motion, colors) and to draw a heatmap about the zone of object detected

Thank you for your excellent work !

**Comment by glenn-jocher** [comment]
@hoangkhoiLE I think gradcam may be more appropriate for classification models, but I could be wrong. I can't really help you here as no experience.

See Captum also for a model interpretability attempt by the pytorch authors (have not used myself either).
https://captum.ai/

**Comment by AndreaBrg** [comment]
@hoangkhoiLE Hi, did you ever succeeded in implementing Grad-Cam or Captum for YoloV5?

@glenn-jocher I see that this issue is linked under the Implemented Enhancements in the release 5.0 but I couldn't see anything related to the topic in the repo. Did I miss something?

**Comment by glenn-jocher** [comment]
@AndreaBrg ah sorry, the release changelog was built using an automated tool, I think it tries to categorize closed issues based on their tags, so this 'enhancement' tag probably led the issue to be grouped into the Implemented Enhancements section of the changelog.

In reality no theres been no update on this. I think detection vs classification with grad-cam would be quite a challenge due the complicated output of the detection models in relation to the classification models shown in gradcam. It's doable but someone would have to dedicate time and effort to investigate and develop this.

**Comment by AndreaBrg** [comment]
@glenn-jocher Thanks for the clarification.
