### ISSUE TITLE
Yolo use my hyperparameters or these ?

### ISSUE THREAD

**Issue by Adriel-Cabral** [ultralytics/yolov5#2067]
## Additional context

When i start my training with Yolov5s, these hyperparameters appear:
![olhar](https://user-images.githubusercontent.com/66179467/106170735-8543a880-616f-11eb-8680-05e0e92ec989.png)

hyperparameters: lr0=0.01, lrf=0.2, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0

But in my .yaml have this hyperparameters:

![olhar2](https://user-images.githubusercontent.com/66179467/106170731-84127b80-616f-11eb-94cc-1bbb3b0c8cae.png)

which one does he use?

I checked and the file yolov5s.yaml in /yolov5/models/ have my hyperparameters

**Comment by glenn-jocher** [comment]
@Adriel-Cabral artbitrary fields added to your model.yaml will have no effect.

**Comment by Adriel-Cabral** [comment]
in other words, it will use this hyperparameters: lr0=0.01, lrf=0.2, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0 ?

**Comment by glenn-jocher** [comment]
@Adriel-Cabral it uses the hyperparameters printed to screen. The purpose of printing to screen to make clear to you what hyperparameters are in play.

**Comment by Adriel-Cabral** [comment]
So, How i can choose the hyperparameters that i want ? 
Sorry to disturb you, but i need know

**Comment by glenn-jocher** [comment]
See train.py argparser for all training settings, including hyperparameters:
https://github.com/ultralytics/yolov5/blob/f639e14e4d20f8eaadfbe92dbc766fee7577c56b/train.py#L436-L468

**Comment by Adriel-Cabral** [comment]
Thanks :)

**Comment by Zhangmaopeng88** [comment]
thanks！

**Comment by glenn-jocher** [comment]
@Zhangmaopeng88 you're welcome! If you have any more questions, feel free to ask. Good luck with your training!
