### ISSUE TITLE
detect.py ~10 FPS on Jetson Xavier AGX and NX

### ISSUE THREAD

**Issue by sammilei** [ultralytics/yolov5#2068]
## ❔Question
Hi, I installed YOLOv5 v3.0 into Jetpack 4.4.1 on Xavier AGX and NX following this [post](https://github.com/ultralytics/yolov5/issues/1944#issuecomment-761590696). Running `detect.py`  only gives me 10-15 PFS with a bare installation regardless of a small or large network in image size 320x256, 416x352, or 640x512 on the inference image, `bus.jpg`. Detection is a bit slower on NX than AGX, as expected. 
Other people on the internet, like in this [thread](https://github.com/ultralytics/yolov5/issues/960), claimed 30hz detecting on AGX. I wonder what I should do differently to get to 30hz.

Another question is why the detection rate in image size 320 is worse than 416.

Thank you!

## system
Linux: Ubuntu 18.04
CUDA: 10.2.89
OpenCV: 4.5.0
cuDNN: 8.0.0.180

## run
`#python3 detect.py --weights yolov5s.pt --img 416 --conf 0.25 --source inference/images/zidane.jpg
`

Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.25, device='', img_size=416, iou_thres=0.5, output='inference/output', save_txt=False, source='inference/images/zidane.jpg', update=False, view_img=False, weights=['yolov5s.pt'])
Using CUDA device0 _CudaDeviceProperties(name='Xavier', total_memory=31918MB)

**Comment by sammilei** [comment]
NVM. I also got 30FPS when using a video instead of a single image. 
```
video 1/1 (1006/1019) /home/co/Downloads/How to get better gas mileage - GEICO.mp4: 384x640 1 cars, Done. (0.032s)
video 1/1 (1007/1019) /home/cor/Downloads/How to get better gas mileage - GEICO.mp4: 384x640 1 cars, Done. (0.035s)
video 1/1 (1008/1019) /home/co/Downloads/How to get better gas mileage - GEICO.mp4: 384x640 1 airplanes, Done. (0.033s)
video 1/1 (1011/1019) /home/co/Downloads/How to get better gas mileage - GEICO.mp4: 384x640 Done. (0.036s)
video 1/1 (1012/1019) /home/co/Downloads/How to get better gas mileage - GEICO.mp4: 384x640 Done. (0.029s)
video 1/1 (1013/1019) /home/co/Downloads/How to get better gas mileage - GEICO.mp4: 384x640 Done. (0.032s)
video 1/1 (1014/1019) /home/co/Downloads/How to get better gas mileage - GEICO.mp4: 384x640 Done. (0.030s)
Results saved to inference/output
Done. (66.865s)
```

**Comment by rickymedrano** [comment]
@sammilei How are you calculating FPS when using detect.py? I'm running inference on a video as well and dont see an option to display it. Are you simply dividing the inference time by 1? i.e 1/0.032 = 31.25FPS?

**Comment by ONNONS** [comment]
I'm curious too please let me know

**Comment by ONNONS** [comment]
> @sammilei How are you calculating FPS when using detect.py? I'm running inference on a video as well and dont see an option to display it. Are you simply dividing the inference time by 1? i.e 1/0.032 = 31.25FPS?

I'm curious too please let me know
