### ISSUE TITLE
Where the changes should be made to detect horizontal line and vertical lines? Can anyone discus elaborately?

### ISSUE THREAD

**Issue by Sagor-Saha** [ultralytics/yolov5#2070]

**Comment by glenn-jocher** [comment]
@Sagor-Saha for very thin objects you may need to relax the aspect ratio constraints on labels in the dataloader, which are set to <20 by default. Other than that no real changes are required, though if your entire dataset is composed of extreme aspect ratio objects a more advanced redistribution of the convolution kernels may help you (i.e. alternate some 3x3s to 1x9 and 9x1 etc).
https://github.com/ultralytics/yolov5/blob/630ec06af6c01c17f2c2603a7a62b672bfcd8878/utils/datasets.py#L907-L913

**Comment by Sagor-Saha** [comment]
Thank you for  responding. Considering the horizontal lines are say(width 5pixel height 500-700 pixel) and vertical line are say( opposite of horizontal), would it work ifI change the aspect ratio to 500?

**Comment by glenn-jocher** [comment]
@Sagor-Saha have no idea what you mean by will it 'work', but the above function controls candidate label criteria. If you want your objects to pass and be included in training, then you should adjust the thresholds accordingly.

**Comment by Sagor-Saha** [comment]
Yes.  I mean to say if update the parameter you talked about. Will the model be able to detect horizontal and vertical line images?

**Comment by glenn-jocher** [comment]
Well, there's no way to know what sort of metrics your training might produce on your custom data unless you actually train.

If you modify the thresholds to allow these objects to pass, i.e. ar_thr=1000 will effectively allow all aspect ratio labels to pass, then they will at least be included in training.
