### ISSUE TITLE
Hi, I‘d like to handle a classes-imbalance problem

### ISSUE THREAD

**Issue by young169** [ultralytics/yolov5#2074]
## ❔Question
I want to pick out multiple classes in one image, but the numbers of different classes can hardly be of the same amount. I'm wondering if I can fix it by adding weight to classification loss? Or what do you suggest? Thanks!

**Comment by glenn-jocher** [comment]
@young169 you can add class weights to the classification loss here if you'd like to. This is the region where the loss criteria are initialized prior to training.
https://github.com/ultralytics/yolov5/blob/2acbe9699a51a0efd8ae0dbfdd775c20a628f362/utils/loss.py#L95-L98
