### ISSUE TITLE
Scaled weight_decay in a larger batchsize training

### ISSUE THREAD

**Issue by LZHgrla** [ultralytics/yolov5#2076]
I want to use `batchsize  = 256` in training, and I find that `weight_decay` is scaled by `total_batch_size / nbs` but `lr` is not scaled.

It is common that `lr` should be scaled in a larger batchsize. So...I am dizzy about why `weight_decay` is scaled and why `lr` is not scaled, could u tell me the reason, pls~

**Comment by glenn-jocher** [comment]
@LZHgrla LR is not scaled by anything under any conditions, irrespective of your batch size.
