### ISSUE TITLE
Detected box mismatch - probably a scale issue

### ISSUE THREAD

**Issue by edeyejedi** [ultralytics/yolov5#2077]
Hello all,

I think this is an easy answer but after a couple hours mucking about and searching + a long day, I couldn't get it right. I also have a distinct feeling I have been here before but i only pick up these applications intermittently.

I have a well trained model. I provide inference (detect.py) with a 1888x640 image, setting img_size to 640 when using detect.py. The inference runs, the printed image + box looks good. When I come to take the xywh data from the txt file produced so that I can make an alternate version of the image + box (e.g. a defocused/fuzzy area in the box; doesn't really matter), the box is not the right shape. I think this is something to do with padding/scaling between my input/process/output images, but I cant figure it out. Probably biggest issue is I have stepped away from python and trying to workout/redo the work flow in another language. will set up my "post processing" in python perhaps, but wondering if anyone has any insights or had similar problems with odd shape boxes!

Thanks heaps

**Comment by glenn-jocher** [comment]
@edeyejedi autolabels are produced by --save-txt in label format. label format is displayed in custom training tutorial:
https://docs.ultralytics.com/yolov5/tutorials/train_custom_data

### 2. Create Labels

After using a tool like [CVAT](https://github.com/opencv/cvat), [makesense.ai](https://www.makesense.ai/) or [Labelbox](https://labelbox.com/)  to label your images, export your labels to **YOLO format**, with one `*.txt` file per image (if no objects in image, no `*.txt` file is required). The `*.txt` file specifications are:

- One row per object
- Each row is `class x_center y_center width height` format.
- Box coordinates must be in **normalized xywh** format (from 0 - 1). If your boxes are in pixels, divide `x_center` and `width` by image width, and `y_center` and `height` by image height.
- Class numbers are zero-indexed (start from 0).

<img width="800" alt="Image Labels" src="https://user-images.githubusercontent.com/26833433/91506361-c7965000-e886-11ea-8291-c72b98c25eec.jpg">

The label file corresponding to the above image contains 2 persons (class `0`) and a tie (class `27`):

<img width="475" src="https://user-images.githubusercontent.com/26833433/98809572-0bc4d580-241e-11eb-844e-eee756f878c2.png">

**Comment by edeyejedi** [comment]
Thanks for your reply @glenn-jocher. It was a silly mistake - I parsed the yv5 output txt and ordered width and height incorrectly.
