### ISSUE TITLE
How to use multiple GPUs for inference

### ISSUE THREAD

**Issue by jiyuwangbupt** [ultralytics/yolov5#2078]
## ❔Question
Hello, How can I use multiple-GPUs for inference?

**Comment by glenn-jocher** [comment]
@jiyuwangbupt that's an interesting question. We don't receive too much demand for multi-GPU inference so detect.py is single-GPU by default, though it is also runs FP16 inference by default. 

For the best control over inference I would recommend running YOLOv5 PyTorch Hub Autoshape models. These allow for finer control (you can deploy the model multi-GPU if you wish) while also automatically handling all pre and post processing (resizing, NMS, etc). See the PyTorch Hub Tutorial for this option:
https://docs.ultralytics.com/yolov5
