### ISSUE TITLE
Data augmentation on a specific class

### ISSUE THREAD

**Issue by Auth0rM0rgan** [ultralytics/yolov5#2079]
Hey @glenn-jocher, 

I have 2 questions and will appreciate it if you can help me with my questions

1. I have 25 classes in my dataset and I don't want to do data augmentation in some of them. is there any way to do not apply data augmentation in some classes?
2.  Also, I have a unbalance dataset! how can I add weights to the loss function to deal with my unbalance dataset?

Thanks in advance!

**Comment by glenn-jocher** [comment]
@Auth0rM0rgan 

1. Augmentation is applied per image, not per class, so I'm not clear on what you're really asking here.
2. All datasets are imbalanced, I would just not worry about it and train normally with default settings to start. Once you'e established a baseline and can quantifiably demonstrate that your lower frequency classes are underperforming then come back.
