### ISSUE TITLE
There is no soud in the m3u8 # http stream

### ISSUE THREAD

**Issue by DAJINZI01** [ultralytics/yolov5#208]
There is no soud in the m3u8 # http stream

**Comment by glenn-jocher** [comment]
@DAJINZI01 I'm sorry, I don't understand your question. Can you post a screenshot or code to reproduce your issue?

**Comment by DAJINZI01** [comment]
No sound in video stream when set --source to video stream

**Comment by glenn-jocher** [comment]
Oh! Yes this makes sense, we are not a video viewing platform, we are detecting objects in videos, we do not use any audio component a stream may or may not have.

**Comment by xjohnxjohn** [comment]
> No sound in video stream when set --source to video stream

If your device support RTMP and modify the program for play sound.

**Comment by glenn-jocher** [comment]
Can you submit a PR?

**Comment by xjohnxjohn** [comment]
> Can you submit a PR?

I will submit a PR as soon as possible!
