### ISSUE TITLE
Error in creating model with Ghost modules

### ISSUE THREAD

**Issue by alrzmshy** [ultralytics/yolov5#2081]
## 🐛 Bug
Hello, I'm trying to build the yolov5s models with Ghost modules but I run into an issue. I replaced C3 with GhostBottleneck in the yaml file and added   GhostBottleneck in the list of modules that are expected in yolo.py file and as I try to construct the model, I get this error:

## To Reproduce 

Output:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-2-7facafecdabb> in <module>()
----> 1 model = Model("./models/yolov5s.yaml")
      2 

<ipython-input-1-7b447b7ed90c> in __init__(self, cfg, ch, nc)
     78             logger.info('Overriding model.yaml nc=%g with nc=%g' % (self.yaml['nc'], nc))
     79             self.yaml['nc'] = nc  # override yaml value
---> 80         self.model, self.save = parse_model(deepcopy(self.yaml), ch=[ch])  # model, savelist
     81         self.names = [str(i) for i in range(self.yaml['nc'])]  # default names
     82         # print([x.shape for x in self.forward(torch.zeros(1, ch, 64, 64))])

<ipython-input-1-7b447b7ed90c> in parse_model(d, ch)
    252 
    253         print(m, args)
--> 254         m_ = nn.Sequential(*[m(*args) for _ in range(n)]) if n > 1 else m(*args)  # module
    255         t = str(m)[8:-2].replace('__main__.', '')  # module type
    256         np = sum([x.numel() for x in m_.parameters()])  # number params

TypeError: __init__() missing 1 required positional argument: 's'
```

## Additional context
Here is my models folder that contains the modifications:

[models.zip](https://github.com/ultralytics/yolov5/files/5894783/models.zip)

**Comment by glenn-jocher** [comment]
@alrzmshy hi thanks for the bug report! Ghost bottlenecks are an interesting idea, which is why we included them. They should work just like you said, by replacing a C3 module with a Ghost Bottleneck module. I'll investigate the problem.

**Comment by glenn-jocher** [comment]
@alrzmshy I've updated GhostConv functionality a bit to make it easier to use in PR #2082. You should be able to replace a C3 module with a GhostBottleneck module now in your model.yaml and everything will work correctly. 

<img width="1177" alt="Screen Shot 2021-01-29 at 11 28 33 AM" src="https://user-images.githubusercontent.com/26833433/106318770-407a4900-6225-11eb-917f-e985321e2853.png">

**Comment by glenn-jocher** [comment]
Removing TODO as original issue is resolved in #2082.

**Comment by Henry0528** [comment]
Hello,l've recently changed  the yolov5s models with ghost modules.I used ghostconv to replace conv and replaced the bottleneck in C3 with ghostbottleneck. I train with the new model successfully and get only a very small drop in map,while  the new model costs about 8 GFlops which is half of the yolov5s model(16GFlops).But when l run the test.py and find that the time consume of testing is almost the same as the yolov5s model,sometime even longer.l don't know whether you have the same question and I wish I can get an answer.

**Comment by glenn-jocher** [comment]
@Henry0528 can you post a table of quantiative comparisons identical to the README table before and after your changes on both CPU and GPU?
