### ISSUE TITLE
Multi-GPU training is lower than single GPU training

### ISSUE THREAD

**Issue by mcmingchang** [ultralytics/yolov5#2089]
## ❔Question
Multi-GPU training is lower than single GPU training
![QQ截图20210131001646](https://user-images.githubusercontent.com/37234299/106361585-b4b60900-6359-11eb-8ff6-1bb562c85b33.png)

 python -m torch.distributed.launch --nproc_per_node 2 train.py --batch-size 64 --data coco.yaml --weights yolov5l.pt --multi-scale  --rect

**Comment by glenn-jocher** [comment]
@mcmingchang see Multi-GPU Training Tutorial:
https://docs.ultralytics.com/yolov5

Multi-GPU speeds track GPU count well.

**Comment by Jelly123456** [comment]
@mcmingchang It is not related to your question, but which command you use to show this fancy picture?

![image](https://user-images.githubusercontent.com/29449336/108943393-b1c9e200-7693-11eb-916b-89de2f05a5de.png)

**Comment by glenn-jocher** [comment]
@Jelly123456 htop command
