### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by WANGCHAO1996** [ultralytics/yolov5#2096]
## ❔Question
when i run test.py  have a error:
![图片](https://user-images.githubusercontent.com/51087601/106385065-39ac2b80-6409-11eb-9247-90926a3a55bd.png)
how to solve it @glenn-jocher   thank you !
## Additional context
if __name__ == '__main__':
    parser = argparse.ArgumentParser(prog='test.py')
    parser.add_argument('--weights', nargs='+', type=str, default='E:\\yolov5-master\\runs\\train\\exp\\weights\\best.pt', help='model.pt path(s)')
    parser.add_argument('--data', type=str, default='data\data.yaml', help='*.data path')
    parser.add_argument('--batch-size', type=int, default=32, help='size of each image batch')
    parser.add_argument('--img-size', type=int, default=640, help='inference size (pixels)')

    parser.add_argument('--conf-thres', type=float, default=0.001, help='object confidence threshold')
    parser.add_argument('--iou-thres', type=float, default=0.6, help='IOU threshold for NMS')
    parser.add_argument('--task', default='val', help="'val', 'test', 'study'")
    parser.add_argument('--device', default='', help='cuda device, i.e. 0 or 0,1,2,3 or cpu')
    parser.add_argument('--single-cls', action='store_true', help='treat as single-class dataset')
    parser.add_argument('--augment', action='store_true', help='augmented inference')
    parser.add_argument('--verbose', action='store_true', help='report mAP by class')
    parser.add_argument('--save-txt', action='store_true', help='save results to *.txt')
    parser.add_argument('--save-hybrid', action='store_true', help='save label+prediction hybrid results to *.txt')
    parser.add_argument('--save-conf', action='store_true', help='save confidences in --save-txt labels')
    parser.add_argument('--save-json', action='store_true', help='save a cocoapi-compatible JSON results file')
    parser.add_argument('--project', default='runs/test', help='save to project/name')
    parser.add_argument('--name', default='exp', help='save to project/name')
    parser.add_argument('--exist-ok', action='store_true', help='existing project/name ok, do not increment')
    opt = parser.parse_args()
    opt.save_json |= opt.data.endswith('coco.yaml')
    opt.data = check_file(opt.data)  # check file
    print(opt)
    check_requirements()
![图片](https://user-images.githubusercontent.com/51087601/106385087-58122700-6409-11eb-88cf-2760281fa11a.png)

**Comment by glenn-jocher** [comment]
@WANGCHAO1996 your paths are incorrect. See custom training tutorial for correct setup:
https://docs.ultralytics.com/yolov5/tutorials/train_custom_data
