### ISSUE TITLE
How to load custom trained model to detect sample image?

### ISSUE THREAD

**Issue by Sagor-Saha** [ultralytics/yolov5#2097]
![image_2021_01_31T08_12_18_594Z-1](https://user-images.githubusercontent.com/34040992/106386958-b0452b00-6401-11eb-92b3-0d529417ce5d.png)
I have trained model using custom dataset. I am not being able to load the model. Any code that would help resolve the issue for custom model?

**Comment by glenn-jocher** [comment]
@Sagor-Saha your code or your dependencies are out of date, suggest you update both, i.e. `git pull` etc
