### ISSUE TITLE
trained model's --img-size is 640, can I use the model to do detect with --img-size 1280,or higher?

### ISSUE THREAD

**Issue by pango99** [ultralytics/yolov5#2098]
## ❔Question
 
model is trained by train.py with --img-size 640,so can I use the model to do detect with --img-size 1280, or higher?

**Comment by glenn-jocher** [comment]
@pango99 you can run inference with any model at any size your hardware will allow, though you will obtain best results training and detecting at similar sizes naturally.

**Comment by pango99** [comment]
Ok, I see, thanks
