### ISSUE TITLE
two places using multi-scale tricks

### ISSUE THREAD

**Issue by Libaishun** [ultralytics/yolov5#21]
I see you use multi-scale tricks in two places: directly resizing model inputs in train.py and scale image with random_affine in datasets.py, which one is better to use or shoule we use them simultaneously ？

**Comment by glenn-jocher** [comment]
@Libaishun yes you are correct! Both methods are suitable for performing multi-scale image augmentation. Exact results depend on model, dataset, etc.

**Comment by Libaishun** [comment]
@glenn-jocher setting multi-scale=True in train.py seems use much more cuda memory than disable it.
