### ISSUE TITLE
batch size vs train mAP

### ISSUE THREAD

**Issue by Happyna88** [ultralytics/yolov5#2100]
## ❔Question
Hello, when i train yolov5x on coco , i get worse mAP than yours, the difference of train conf is the batch size, because i use 1080 GPU, max of batch size only can be set to 4,  much smaller than your conf of 16, other confs are all the same. Traing result is about 6% lower than your results.txt as following:( i havn't finished the training)
My train result:
     0/299     3.06G   0.08479    0.0787   0.08213    0.2456        23       640   0.05713  0.009683   0.01279  0.004966   0.06797   0.05916   0.07469
     1/299      5.8G   0.06715   0.07723   0.06716    0.2115        28       640    0.2107   0.05049   0.05753   0.02852   0.05971   0.05822   0.06051
     2/299      5.8G    0.0625   0.07376   0.05346    0.1897        43       640    0.3453   0.05318   0.08988   0.04717   0.05737   0.06062   0.05381
     3/299      5.8G   0.05817   0.07139   0.04462    0.1742        31       640    0.5294   0.03222   0.09648   0.05214   0.05806   0.06603   0.05174
     4/299      5.8G   0.05501   0.06943   0.03913    0.1636        22       640    0.5531   0.03359    0.1152   0.06331   0.05763   0.06755   0.04891
     5/299      5.8G   0.05316   0.06818   0.03614    0.1575        34       640    0.6504   0.04369    0.1377   0.07604   0.05665   0.06751   0.04601
     6/299      5.8G   0.05184   0.06713   0.03391    0.1529        72       640    0.6243   0.05703    0.1641   0.09111   0.05542   0.06687   0.04317
     7/299      5.8G   0.05102   0.06671   0.03231      0.15        16       640    0.6277   0.07661    0.1923    0.1078   0.05405   0.06577   0.04033
     8/299      5.8G   0.05018   0.06611   0.03108    0.1474        21       640    0.6626    0.1046    0.2237    0.1273   0.05251   0.06418    0.0375
     9/299      5.8G   0.04965   0.06579   0.03022    0.1457        27       640    0.6659    0.1391    0.2567    0.1478   0.05096   0.06232   0.03476
    10/299      5.8G   0.04915   0.06522   0.02949    0.1439        41       640     0.663    0.1812    0.2883    0.1682   0.04948   0.06049   0.03225
    11/299      5.8G   0.04874   0.06489   0.02878    0.1424        30       640    0.6562     0.223    0.3193    0.1888    0.0481   0.05864   0.02998
    12/299      5.8G   0.04837   0.06481   0.02828    0.1415        42       640    0.6374    0.2678    0.3504    0.2096   0.04678    0.0567   0.02792
    13/299      5.8G   0.04807   0.06432    0.0279    0.1403        20       640    0.6139    0.3094    0.3788    0.2295   0.04557   0.05498   0.02618

The 6% lower mAP , is it because of the my smaller batch size?How can i get your result, run more epoches? Should i change lr0 to a lower one because of my lower batch size and run more epoches? Hope for your help, thanks.

**Comment by Happyna88** [comment]
You mean , i need to run python train.py --epochs 10 --data coco128.yaml --weights yolov5s.pt --cache --evolve to get the suitable hyperparameter for my environment, then use the evolved hyperparameter to run train.py again?

**Comment by glenn-jocher** [comment]
@Happyna88 mAP is evaluated upon training completion, not after 13 epochs. To reproduce our results simply follow the commands in https://github.com/ultralytics/yolov5#training.
