### ISSUE TITLE
Why high --img-size model's mAP is lower than low img-size ones

### ISSUE THREAD

**Issue by pango99** [ultralytics/yolov5#2103]
## ❔Question

Hi:
   I train 2 models from official pretrained yolov5s.pt with my custom dataset,one img-size is 1280, the other is 640, I use below command to start train program,

  train 1280 img-size model, mAP is 0.711
  python train.py  --img-size 1280 --batch 6 --epochs 100 --data g:/AI/dataset/baidu/insects_200/data.yaml --weights ../yolov5s.pt
  
  train 640 img-size model, mAP is 0.750
  python train.py  --img-size 640 --batch 6 --epochs 100 --data g:/AI/dataset/baidu/insects_200/data.yaml --weights ../yolov5s.pt

I found the mAP of model with 1280 img-size is lower than 640 img-size ones(1280:0.711, 640:0.750), from my common sense, higher image size have higher details,the model trained from higher size image should have higher precision,but why 1280 img-size model's mAP is lower than 640 img-size?  Is it related to the img-size of the pretrained model(yolov5s.pt's img-size is 640)?

**Comment by glenn-jocher** [comment]
@pango99 increasing image size up to native resolution increases information, past that no new information is introduced, but additional convolutional operations become possible (at sub-pixel level), which under certain conditions may assist with small object detection.

Large object detection won't benefit from upscaling.

**Comment by glenn-jocher** [comment]
@pango99 BTW you can access larger P3-P6 output 1280 img-size pretrained models now. They're currently under the name YOLOv5s6.pt for small etc. These will perform better at all sizes and are more capable at larger image sizes, but they are also slightly larger, we are aiming to organize the results for them in a new update soon.

i.e. python detect.py --weights yolov5s6.pt

**Comment by pango99** [comment]
Hi, glenn:
     How can I download the YOLOv5s6.pt? Does it have x version? For current pretrained model, I'd better to train 640 img-size model,is it?

**Comment by glenn-jocher** [comment]
@pango99 yes, we've trained P6 models in all sizes at --img 1280. The checkpoints have been added to the current release assets while we experiment with them here:
https://github.com/ultralytics/yolov5/releases/tag/v4.0

You can autodownload them the normal way, i.e. `python detect.py --weights yolov5x6.pt`

**Comment by glenn-jocher** [comment]
BTW, these P6 models produce best results at --img 1280, but they can be used at smaller sizes also such as --img 640 or --img 320.

**Comment by pango99** [comment]
thanks,glenn, I had download the newly pretrained model, I'll retrain my model again

**Comment by pango99** [comment]
Hi, glenn:
       Can I use the 1280 img-size model trained from newly yolov5x6.pt/yolov5s6.pt with TensorRTx project(https://github.com/wang-xinyu/tensorrtx)? this project had support yolov5 version 4.0

**Comment by glenn-jocher** [comment]
@pango99 yes I think so. There are no architecture changes other than adding a P6 output.
