### ISSUE TITLE
Resume training, but not on the last run.

### ISSUE THREAD

**Issue by RobinBram** [ultralytics/yolov5#2104]
Hi!

I want to resume a training run, but not the last one I performed. I would prefer to have all the data from the training in the same file.

**Comment by RobinBram** [comment]
Found the answer: python train.py --resume runs/exp0/weights/last.pt

**Comment by glenn-jocher** [comment]
@RobinBram resuming an interrupted training run is simple. There are two options:
```bash
python train.py --resume  # resume latest training
python train.py --resume path/to/last.pt  # specify resume checkpoint
```

If you started the training with a multi-GPU command then you must resume it with the same exact configuration (and vice versa). Multi-GPU resume commands are here, assuming you are using 8 GPUs:
```bash
python -m torch.distributed.launch --nproc_per_node 8 train.py --resume  # resume latest training
python -m torch.distributed.launch --nproc_per_node 8 train.py --resume path/to/last.pt  # specify resume checkpoint
```

Note that you may not change settings when resuming, you must resume with the same exact settings (`--epochs`, `--batch` etc).
