### ISSUE TITLE
Configuration for detecting large size targets

### ISSUE THREAD

**Issue by CasonTsai** [ultralytics/yolov5#2105]
## ❔Question
There are large objects in the image.These large objects sometimes occupy 70 to 80 percent of the image area.  How to adjust the training parameters?
Currently, the value of anchor is adjusted , such as  
![image](https://user-images.githubusercontent.com/18262642/106444939-615acc80-64b9-11eb-8528-2ae231c7ae20.png) 
to 

![image](https://user-images.githubusercontent.com/18262642/106445062-851e1280-64b9-11eb-93c4-3149b1bbb880.png)

Is there any other way?

## Additional context
Thank you very much for your work

**Comment by glenn-jocher** [comment]
@CasonTsai autoanchor analyzes your custom dataset and trainings settings and will evolve appropriate anchors for you as necessary. No action is required on your part.

If you'd like to take a stab at manually defining anchors though, then yes that is the place to do that. Note autoanchor will ignore your anchors if they are unsuitable, defined as producing a low Best Possible Recall (BPR) on your data, and force evolve new anchors in that case.

**Comment by CasonTsai** [comment]
@glenn-jocher  thanks  a lot!
