### ISSUE TITLE
can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first

### ISSUE THREAD

**Issue by WestbrookZero** [ultralytics/yolov5#2106]
when i start to train , An error is as follows:
![image](https://user-images.githubusercontent.com/13358789/106464060-1d74c100-64d3-11eb-850b-045270ea624d.png)

**Comment by hehe03** [comment]
Hello @WestbrookZero ,  I've run into the same problem, and I'm wondering how did you reslove it, thanks!

**Comment by oukohou** [comment]
+1 same problem, what's the workaround?

**Comment by glenn-jocher** [comment]
@hehe91 @oukohou If you believe you have a reproducible issue, we suggest you close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose), providing screenshots and a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. Thank you!

**Comment by oukohou** [comment]
@glenn-jocher well, no bother, that's a tiny carelesses of old-versioned codes, just simply update the repo can fix it.
In case someone still uses the old codes, a tiny modification can fix it:
in `utils/general.py`'s `output_to_target` function, just add one more type assert:

```python
def output_to_target(output, width, height):
    # Convert model output to target format [batch_id, class_id, x, y, w, h, conf]
    if isinstance(output, torch.Tensor):
        output = output.cpu().numpy()

    targets = []
    for i, o in enumerate(output):
        if o is not None:
            # sometimes output can be a list of tensor, so here ensure the type again, this fixes the error.
            if isinstance(o, torch.Tensor):
                o = o.cpu().numpy()
            for pred in o:
                box = pred[:4]
                w = (box[2] - box[0]) / width
                h = (box[3] - box[1]) / height
                x = box[0] / width + w / 2
                y = box[1] / height + h / 2
                conf = pred[4]
                cls = int(pred[5])

                targets.append([i, cls, x, y, w, h, conf])

    return np.array(targets)
```
@hehe91 hope this helps.
and @glenn-jocher thanks for your great work again!

**Comment by jingruhou** [comment]
> @glenn-jocher well, no bother, that's a tiny carelesses of old-versioned codes, just simply update the repo can fix it. In case someone still uses the old codes, a tiny modification can fix it: in `utils/general.py`'s `output_to_target` function, just add one more type assert:
> 
> ```python
> def output_to_target(output, width, height):
>     # Convert model output to target format [batch_id, class_id, x, y, w, h, conf]
>     if isinstance(output, torch.Tensor):
>         output = output.cpu().numpy()
> 
>     targets = []
>     for i, o in enumerate(output):
>         if o is not None:
>             # sometimes output can be a list of tensor, so here ensure the type again, this fixes the error.
>             if isinstance(o, torch.Tensor):
>                 o = o.cpu().numpy()
>             for pred in o:
>                 box = pred[:4]
>                 w = (box[2] - box[0]) / width
>                 h = (box[3] - box[1]) / height
>                 x = box[0] / width + w / 2
>                 y = box[1] / height + h / 2
>                 conf = pred[4]
>                 cls = int(pred[5])
> 
>                 targets.append([i, cls, x, y, w, h, conf])
> 
>     return np.array(targets)
> ```
> 
> @hehe91 hope this helps. and @glenn-jocher thanks for your great work again!

thanks，resolved my question.
