### ISSUE TITLE
Different crashes on linux VM and windows PC when running the Train Custom Data tutorial for yolo5

### ISSUE THREAD

**Issue by davesargrad** [ultralytics/yolov5#2108]
## ❔Question
I am running the "Train Custom Data" tutorial, for the first time. I see a "terminated" condition as depicted below. 

I imagine that this is not to be expected. Can you guide me relative to isolating the issue. I am running this on a Fedora VM. Though a GPU is not available (as the screenshot below indicates), I'd think that the training session still runs using the CPU. 

1. Could the lack of a GPU be causing what appears to be a premature termination? 
2. What output should I see on a successful run?

## Additional context
![image](https://user-images.githubusercontent.com/48793689/106473246-92171380-6471-11eb-9729-d4a30b0d295d.png)

![image](https://user-images.githubusercontent.com/48793689/106473154-73b11800-6471-11eb-897c-35939c63fe42.png)

![image](https://user-images.githubusercontent.com/48793689/106473753-28e3d000-6472-11eb-80e4-5be43c6f2a27.png)

**Comment by davesargrad** [comment]
![image](https://user-images.githubusercontent.com/48793689/106478090-dce75a00-6476-11eb-9e2b-58bc5d12a4c0.png)

**Comment by davesargrad** [comment]
![image](https://user-images.githubusercontent.com/48793689/106478795-93e3d580-6477-11eb-8e93-da0b7c20994f.png)

**Comment by davesargrad** [comment]
It seems to crash somewhere within the call to model (i dug in and its in forward_once).. i'll try to exactly isolate.

![image](https://user-images.githubusercontent.com/48793689/106480687-a828d200-6479-11eb-8b61-29d631f2cdf1.png)

**Comment by davesargrad** [comment]
It crashes at line 37... it hits this line probably about 20 times (after the call to model, at line 289 above) before crashing.

![image](https://user-images.githubusercontent.com/48793689/106483832-f8edfa00-647c-11eb-92ea-6bdd0f8cab31.png)

**Comment by davesargrad** [comment]
Gonna take a break for now.. hopefully you guys will have something to suggest.. this last screenshot includes a debug counter that shows a consistent crash after the 28th or 29th call to run the model

By the way, thank you for all the great work on this component. I am excited to learn more from it, and from you guys.

![image](https://user-images.githubusercontent.com/48793689/106488248-83385d00-6481-11eb-8a74-d28a5736feb5.png)

**Comment by davesargrad** [comment]
Hi. Though I would like to get this working on my linux VM, I'm trying as well on my windows box. There I get a completely different error as follows:

![image](https://user-images.githubusercontent.com/48793689/106494647-aadef380-6488-11eb-8c5b-287750f8245d.png)

**Comment by davesargrad** [comment]
I managed to get the windows version running. I had to increase the size of my paging file for some reason.

I'd still very much like to get the linux VM version also working.

![image](https://user-images.githubusercontent.com/48793689/106496928-71f44e00-648b-11eb-8616-8895e5cd1425.png)

**Comment by davesargrad** [comment]
I do see a GPU related error on the run on windows. (cudart64_101.dll not found)

![image](https://user-images.githubusercontent.com/48793689/106497267-d0b9c780-648b-11eb-90f9-061d501f6f38.png)

**Comment by glenn-jocher** [comment]
@davesargrad tensorboard seems to produce the cudart error on all operating systems, we investigated but no fix is currently available. It doesn't seem to have any detrimental effect so I would just ignore it. You can see it in the Colab tutorial also here:
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb#scrollTo=1NcFxRcFdJ_O&line=1&uniqifier=1

About your OS issues, YOLOv5 is supported on all 3 main operating systems. I don't have time to help you diagnose, but I'll paste our default environmental issue reply below.

It appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below. 


## Requirements

**Python 3.8** or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including **`torch>=1.7`**. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by glenn-jocher** [comment]
@davesargrad BTW, line 37 there in common.py is just the forward function of the basic Conv() module, which is the bread and butter of the CNN architecture more or less, there's nothing with the code there. You have the latest code clearly (green check mark), so it's likely there may be something in your environment preventing correct operation. Windows is always a difficult environment unfortunately (I code on a Mac and then train on Ubuntu instances). You can run the same tutorial steps in colab to see the correct response:
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

**Comment by davesargrad** [comment]
@glenn-jocher Ty very much for your kind response. I will continue to dig, however for now I seem to be making progress on a windows platform.

Can you please tell me why you think the following detect is not actually detecting. Here I am using the bus.jpg and the zidane.jpg that are part of the yolo5 release. I am comparing my outputs to the outputs on the[ colab tutorial documentation page](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb#scrollTo=zR9ZbuQCH7FX).. they are slightly different, though my 224 layer model with 7266973 parameters is clearly proper.

![image](https://user-images.githubusercontent.com/48793689/106506501-d1f0f180-6497-11eb-881b-bfab00da89c7.png)

What I expect to see is this:
```
Fusing layers... 
Model Summary: 224 layers, 7266973 parameters, 0 gradients, 17.0 GFLOPS
image 1/2 /content/yolov5/data/images/bus.jpg: 640x480 4 persons, 1 buss, 1 skateboards, Done. (0.011s)
image 2/2 /content/yolov5/data/images/zidane.jpg: 384x640 2 persons, 2 ties, Done. (0.011s)
Results saved to runs/detect/exp..
```

In the resulting runs/detect/exp directory, I see the two images, but they do not include the bounding boxes with a (person, bus, skateboard) identifier.

The NaN's (nan) that come out of the inference dont seem good.

![image](https://user-images.githubusercontent.com/48793689/106509711-f8189080-649b-11eb-974f-19d255fc60b1.png)

The 25 sequentials that are processed inside forward_once, result in either None.. or tensors that include some nan values: 
![image](https://user-images.githubusercontent.com/48793689/106512456-a5d96e80-649f-11eb-8636-23de1241d319.png)

These same tensors also include some seemingly good data:
![image](https://user-images.githubusercontent.com/48793689/106512540-bee21f80-649f-11eb-9253-21ab40ec778d.png)

```
tensor([[[[     nan,      nan,      nan,  ...,      nan,      nan,      nan],
          [     nan,      nan,      nan,  ...,      nan,      nan,      nan],
          [     nan,      nan,      nan,  ...,      nan,      nan,      nan],
          ...,
          [     nan,      nan,      nan,  ...,      nan,      nan,      nan],
          [     nan,      nan,      nan,  ...,      nan,      nan,      nan],
          [     nan,      nan,      nan,  ...,      nan,      nan,      nan]],

         [[ 0.50391,  0.50391,  0.50391,  ...,  0.50391,  0.50391,  0.50391],
          [ 0.50391,  0.50391,  0.50391,  ...,  0.50391,  0.50391,  0.50391],
          [ 0.50391,  0.50391,  0.50391,  ...,  0.50391,  0.50391,  0.50391],
          ...,
          [ 0.50391,  0.50391,  0.50391,  ...,  0.50391,  0.50391,  0.50391],
          [ 0.50391,  0.50391,  0.50391,  ...,  0.50391,  0.50391,  0.50391],
          [ 0.50391,  0.50391,  0.50391,  ...,  0.50391,  0.50391,  0.50391]],

         [[     nan,      nan,      nan,  ...,      nan,      nan,      nan],
          [     nan,      nan,      nan,  ...,      nan,      nan,      nan],
          [     nan,      nan,      nan,  ...,      nan,      nan,      nan],
          ...,
          [     nan,      nan,      nan,  ...,      nan,      nan,      nan],
          [     nan,      nan,      nan,  ...,      nan,      nan,      nan],
          [     nan,      nan,      nan,  ...,      nan,      nan,      nan]],

         ...,

         [[ 1.90039,  1.90039,  1.90039,  ...,  1.90039,  1.90039,  1.90039],
          [ 1.90039,  1.90039,  1.90039,  ...,  1.90039,  1.90039,  1.90039],
          [ 1.90039,  1.90039,  1.90039,  ...,  1.90039,  1.90039,  1.90039],
          ...,
          [ 1.90039,  1.90039,  1.90039,  ...,  1.90039,  1.90039,  1.90039],
          [ 1.90039,  1.90039,  1.90039,  ...,  1.90039,  1.90039,  1.90039],
          [ 1.90039,  1.90039,  1.90039,  ...,  1.90039,  1.90039,  1.90039]],

         [[     nan,      nan,      nan,  ...,      nan,      nan,      nan],
          [     nan,      nan,      nan,  ...,      nan,      nan,      nan],
          [     nan,      nan,      nan,  ...,      nan,      nan,      nan],
          ...,
          [     nan,      nan,      nan,  ...,      nan,      nan,      nan],
          [     nan,      nan,      nan,  ...,      nan,      nan,      nan],
          [     nan,      nan,      nan,  ...,      nan,      nan,      nan]],

         [[-0.13367, -0.13367, -0.13367,  ..., -0.13367, -0.13367, -0.13367],
          [-0.13367, -0.13367, -0.13367,  ..., -0.13367, -0.13367, -0.13367],
          [-0.13367, -0.13367, -0.13367,  ..., -0.13367, -0.13367, -0.13367],
          ...,
          [-0.13367, -0.13367, -0.13367,  ..., -0.13367, -0.13367, -0.13367],
          [-0.13367, -0.13367, -0.13367,  ..., -0.13367, -0.13367, -0.13367],
          [-0.13367, -0.13367, -0.13367,  ..., -0.13367, -0.13367, -0.13367]]]], device='cuda:0', dtype=torch
```

**Comment by glenn-jocher** [comment]
@davesargrad the NaNs must be the source of the problem. I think this connected to CUDA version incompatibilities on Windows, there are a few issues open on this actually, i.e. https://github.com/ultralytics/yolov5/issues/1625. I think one user said downgrading to CUDA 10.1 solved this for him.

I'm assuming detect.py --device cpu works correctly?

**Comment by glenn-jocher** [comment]
The Windows CI tests (on CPU) show correct detections here, both for custom trained models and official auto-downloaded models. These tests run every 24 hours.
https://github.com/ultralytics/yolov5/runs/1803125015?check_suite_focus=true
<img width="1702" alt="Screen Shot 2021-02-01 at 12 33 45 PM" src="https://user-images.githubusercontent.com/26833433/106515002-ddd5b700-6489-11eb-96b4-61f6d2d36f24.png">

**Comment by davesargrad** [comment]
@glenn-jocher as you thought.. when i use the CPU I get proper identification.

![image](https://user-images.githubusercontent.com/48793689/106517733-e1c40200-64a6-11eb-85fb-8dd290b75043.png)

![image](https://user-images.githubusercontent.com/48793689/106517792-f607ff00-64a6-11eb-9d77-de642f6d9074.png)

Thanks very much. Assuming that I continue to isolate environment problems, I will be sure to post what I learn here. Hopefully that will help contribute to your growing knowledge base.

**Comment by wudashuo** [comment]
Yes, there is a problem with detecting on Windows, and I raised an issue about this.
It seems like something wrong with the PyTorch 1.7 Windows version. And the Linux version works fine.
You can find more details in my issue #1625
