### ISSUE TITLE
Resume training with a different number of classes

### ISSUE THREAD

**Issue by jake-shomer** [ultralytics/yolov5#2109]
## ❔Question
I am attempting to retrain my yolov5 model with an additional class. I want to use my already trained weights to initialize the model. How would I go about this? When I use `--weights` or `--resume` I get a mismatch of size error.

**Comment by glenn-jocher** [comment]
@jake-shomer --resume is only for interrupted trainings, no modifications are allowed to anything (dataset, parameters, etc.).

Starting from a previously trained model is simple, it's the default use case. To train VOC (20 classes) from COCO-trained YOLOv5s (80 classes):

`python train.py --data voc.yaml --weights yolov5s.pt`
