### ISSUE TITLE
Can't reproduce demo results

### ISSUE THREAD

**Issue by IssacCyj** [ultralytics/yolov5#2111]
## ❔Question
Hi,

First of all thanks for this amazing project!
 
As a first step I'm trying to reproduce the some demo results using the pretrained model following the instructions, which are:

```
git clone https://github.com/ultralytics/yolov5.git
cd yolov5
pip install -r requirements.txt
python detect.py --source data/images --weights yolov5s.pt --conf 0.25
```
However, no matter how I try I can't reproduce the results on data/images/zidane.jpg which should look like this in README:

![97107365-685a8d80-16c7-11eb-8c2e-83aac701d8b9](https://user-images.githubusercontent.com/25549922/106510487-d6abaa80-6483-11eb-8bb0-6e99d11d6240.jpeg)

**but I got:**

![zidane](https://user-images.githubusercontent.com/25549922/106510526-e6c38a00-6483-11eb-9a86-9d2e852216e5.jpg)

The confidence score are quite different.

I'm running on linux12.04, cuda 11.2 with pytorch1.8, I also tried running on **cpu**, **[colab](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb)**, **kaggle notebook** and **macbook**, but got same result.

Am I missing anything, or the results in README is from an old commit?

Thanks,

Issac

**Comment by glenn-jocher** [comment]
@IssacCyj your output is fine. We update models often on new releases, but we do not always update repo images to avoid inflating the git clone package sizes, so the image in the colab notebook corresponds to v3.1 models. We'll update again when we release v5.0 this month.

**Comment by IssacCyj** [comment]
thanks for you quick response!
