### ISSUE TITLE
resume from a finished checkpoint

### ISSUE THREAD

**Issue by IssacCyj** [ultralytics/yolov5#2113]
## ❔Question

After finishing a run of 30 epochs, I want to resume the training to 80 epochs, so I ran:

`python train.py --img 640 --batch 8 --epochs 80 --data data/XXX.yaml --name 80epoch --cache-images --resume runs/train/30epoch/weights/last.pt`

but got this error:
```
Traceback (most recent call last):
  File "train.py", line 522, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 152, in train
    assert start_epoch > 0, '%s training to %g epochs is finished, nothing to resume.' % (weights, epochs)
AssertionError: runs/train/30epoch/weights/last.pt training to 30 epochs is finished, nothing to resume.
```

So is it by signed? the only way to do this is to start from scratch and initialize the model by adding `--weights last.pt` argument instead of using `--resume`?

thanks

**Comment by glenn-jocher** [comment]
@IssacCyj resuming an interrupted training run is simple. There are two options:
```bash
python train.py --resume  # resume latest training
python train.py --resume path/to/last.pt  # specify resume checkpoint
```

If you started the training with a multi-GPU command then you must resume it with the same exact configuration (and vice versa). Multi-GPU resume commands are here, assuming you are using 8 GPUs:
```bash
python -m torch.distributed.launch --nproc_per_node 8 train.py --resume  # resume latest training
python -m torch.distributed.launch --nproc_per_node 8 train.py --resume path/to/last.pt  # specify resume checkpoint
```

Note that you may not change settings when resuming, you must resume with the same exact settings (`--epochs`, `--batch` etc).

**Comment by IssacCyj** [comment]
Thanks for replying.

I mean it's not an interrupted training. Say, I have finished training and now I want to training longer from the latest cpt. I think I won't be able to use --resume in this case right?

**Comment by glenn-jocher** [comment]
@IssacCyj if your training completes successfully, then no, there's nothing to resume, it's all done.

To use your trained checkpoint as a starting point for a new training, use the default train command. A new run will be created for this new training.
`python train.py --weights runs/exp/weights/best.pt`

**Comment by fahimnawaz7** [comment]
It also works for me.
Thanks @glenn-jocher.
