### ISSUE TITLE
How can I use the weights for live detect?

### ISSUE THREAD

**Issue by Manuservus11** [ultralytics/yolov5#212]
Hello I trained my model with a custom dataset. But now how can I use it for live detecten?
Regards

**Comment by glenn-jocher** [comment]
@Manuservus11 you can try a webcam if your computer has one:
`python detect.py --source 0`

**Comment by glenn-jocher** [comment]
You can also download our iDetection app if you have an iPhone.

<img src="https://user-images.githubusercontent.com/26833433/85977759-119bac00-b992-11ea-8884-ca747f087489.jpg" width="500">
