### ISSUE TITLE
In 'evolve' mode, If the original hyp is 0, It will never update

### ISSUE THREAD

**Issue by GuozhenLee** [ultralytics/yolov5#2122]
for i, k in enumerate(hyp.keys()):  # plt.hist(v.ravel(), 300)
                    hyp[k] = float(x[i + 7] * v[i])  # mutate

Because of this line, if x[ele] == 0，new hyp[ele] will never > 0

I don't whether this feature is what you designed or just a bug.

**Comment by glenn-jocher** [comment]
@GuozhenLee yes that's a good observation! In the hyp evolution [tutorial](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution
) you can see this in some hyps, such as iou_t and fl_gamma. I suppose it's a desired trait in some cases (i.e. for COCO we probably don't want any up-down flips, so leaving this value at 0.0 would make sense), though the hyp constraints (i.e. limits) are also settable directly in train.py `meta` dictionary here:
https://github.com/ultralytics/yolov5/blob/73a066993051339f6adfe5095a7852a2b9184c16/train.py#L526-L529

![image](https://user-images.githubusercontent.com/26833433/106701884-42813680-659c-11eb-8089-476bf6b22911.png)
