### ISSUE TITLE
Loading custom dataset using webcam not working

### ISSUE THREAD

**Issue by hyNTU** [ultralytics/yolov5#2123]
## ❔Question
Running on Google Colab
After getting the custom weights, --source 0 doesnt seem to work and an error is shown:
Fusing layers... 
Model Summary: 484 layers, 88404072 parameters, 0 gradients
[ WARN:0] global /io/opencv/modules/videoio/src/cap_v4l.cpp (802) open VIDEOIO ERROR: V4L: can't open camera by index 0
1/1: 0... Traceback (most recent call last):
  File "detect.py", line 173, in <module>
    detect()
  File "detect.py", line 49, in detect
    dataset = LoadStreams(source, img_size=imgsz)
  File "/content/yolov5/utils/datasets.py", line 275, in __init__
    assert cap.isOpened(), 'Failed to open %s' % s
AssertionError: Failed to open 0

**Comment by glenn-jocher** [comment]
@chuahaoyan oh, sorry buddy. Webcam with `python detect.py --source 0` is only available locally. You can point to remote  streaming sources though like rtsp, http streams, from colab though.
