### ISSUE TITLE
How do I not use the pre-train model ??? 

### ISSUE THREAD

**Issue by KangHoyong** [ultralytics/yolov5#2126]
## ❔Question

How do I not use the pre-train model

**Comment by KangHoyong** [comment]
work out

**Comment by rickymedrano** [comment]
From the wiki:

> Train a YOLOv5s model on COCO128 by specifying dataset, batch-size, image size and either pretrained --weights yolov5s.pt (recommended), or randomly initialized --weights '' --cfg yolov5s.yaml (not recommended).

So you want to do the randomly initialized option.
