### ISSUE TITLE
Convert to Tensorflow.js model

### ISSUE THREAD

**Issue by pravastacaraka** [ultralytics/yolov5#2127]
## ❔Question
Hello,, is it possible to convert the YOLOv5 PyTorch model to the Tensorflow.js model?

**Comment by glenn-jocher** [comment]
@pravastacaraka yes, you can convert to TF js by exporting to TF first and then onward to js. See https://github.com/ultralytics/yolov5/pull/1127 for TF export.

**Comment by pravastacaraka** [comment]
@glenn-jocher I have an issue with the Colab, when I try to export use
`!PYTHONPATH=. python models/tf.py --weights weights/tooth.pt --cfg models/yolov5s.yaml --img 416 --tf-nms`

There is an error

> TensorFlow saved_model export failure: 'Conv2d' object has no attribute 'conv'
> Traceback (most recent call last):
>   File "models/tf.py", line 391, in <module>
>     tf_model = tf_Model(opt.cfg, model=model, nc=nc)
>   File "models/tf.py", line 306, in __init__
>     self.model, self.savelist = parse_model(deepcopy(self.yaml), ch=[ch], model=model)  # model, savelist, ch_out
>   File "models/tf.py", line 278, in parse_model
>     else tf_m(*args, w=model.model[i])  # module
>   File "models/tf.py", line 147, in __init__
>     self.cv2 = tf_Conv(c1, c_, 1, 1, w=w.cv2)
>   File "models/tf.py", line 62, in __init__
>     kernel_initializer=keras.initializers.Constant(w.conv.weight.permute(2, 3, 1, 0).numpy()))
>   File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 779, in __getattr__
>     type(self).__name__, name))
> torch.nn.modules.module.ModuleAttributeError: 'Conv2d' object has no attribute 'conv'
> 
> Starting TensorFlow GraphDef export with TensorFlow 2.4.1...
> TensorFlow GraphDef export failure: name 'keras_model' is not defined
> Traceback (most recent call last):
>   File "models/tf.py", line 416, in <module>
>     tf.TensorSpec(keras_model.inputs[0].shape, keras_model.inputs[0].dtype))
> NameError: name 'keras_model' is not defined

Is there something wrong?

**Comment by glenn-jocher** [comment]
@pravastacaraka Keras and TF export should be working, but I remember seeing a similar error message on the PR. Is this error reproducible with the default models? 

Also I'm not sure if export is verified with TF 2.4.1, only TF 2.4.0 as far as I've seen.

**Comment by pravastacaraka** [comment]
> @pravastacaraka Keras and TF export should be working, but I remember seeing a similar error message on the PR. Is this error reproducible with the default models?

@glenn-jocher I haven't tried to convert the default model from YOLOv5.

> Also I'm not sure if export is verified with TF 2.4.1, only TF 2.4.0 as far as I've seen.

I tried this on Colab, should I change the Tensorflow version to 2.4.0 first? Because I have tried it on my laptop with installed TF 2.4.0 and PyTorch 1.7.1 the results are the same as the error I showed before.

Then I tried to change to TF 2.3.0, and PyTorch 1.6.0 resulted in a different error. Here it is the error:

> Namespace(batch_size=1, cfg='models/yolov5s.yaml', dynamic_batch_size=False, img_size=[416, 416], iou_thres=0.5, ncalib=100, no_tfl_detect=False, score_thres=0.4, source='../data/coco128.yaml', tf_nms=True, tfl_int8=False, topk_all=100, topk_per_class=100, weights='weights/tooth.pt')
> Traceback (most recent call last):
> File "tf.py", line 383, in
> model = torch.load(opt.weights, map_location=torch.device('cpu'))['model'].float() # .fuse()
> File "D:\proyek-akhir\yolov5-tf-export.env\lib\site-packages\torch\serialization.py", line 584, in load
> return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
> File "D:\proyek-akhir\yolov5-tf-export.env\lib\site-packages\torch\serialization.py", line 842, in _load
> result = unpickler.load()
> AttributeError: Can't get attribute 'SiLU' on <module 'torch.nn.modules.activation' from 'D:\proyek-akhir\yolov5-tf-export\.env\lib\site-packages\torch\nn\modules\activation.py'>

**Comment by glenn-jocher** [comment]
@pravastacaraka yes your new error is expected. torch requirements are >=1.7.0. 

In your results then it seems that 2.4.1 and 2.4.0 behave identically for our intents and purposes. You may want to verify export with a default model before trying a custom model to remove your model as a source of error.

**Comment by pravastacaraka** [comment]
@glenn-jocher Ahh... I have tried it for the YOLOv5s default model, and it works. What's wrong with my training custom model?

**Comment by glenn-jocher** [comment]
@pravastacaraka it's likely just out of date. I would git clone a new copy fo the repo and retrain your model, then it will export correctly.

**Comment by pravastacaraka** [comment]
Can I use the previous model as my checkpoint?

**Comment by batrlatom** [comment]
> @glenn-jocher Ahh... I have tried it for the YOLOv5s default model, and it works. What's wrong with my training custom model?

Do you have a nms code written in tfjs to share? I was able to convert model to tfjs correctly, but I am struggling to parse boxes and scores after the prediction. Thanks!

**Comment by glenn-jocher** [comment]
@batrlatom can you use the TF JS NMS function here?
https://js.tensorflow.org/api/latest/#image.nonMaxSuppression

**Comment by pravastacaraka** [comment]
> @batrlatom can you use the TF JS NMS function here?
> https://js.tensorflow.org/api/latest/#image.nonMaxSuppression

@glenn-jocher where can I put the code?

**Comment by glenn-jocher** [comment]
@pravastacaraka I think if you are building a TF JS version of YOLOv5 you should pipeline a nonMaxSuppression() layer immediately after the Detect() layer, but I'm a little light on details as I actually have not gone down this path myself.

**Comment by anas-899** [comment]
@pravastacaraka @batrlatom 
I have converted it to js easily using:
tensorflowjs_converter --input_format=tf_saved_model --output_format=tfjs_graph_model

was anybody able to implement the non-max-suppression and can share the javascript code?
because it's not just calling tf.NMS, there are many operations need to be done as well.

I followed the implementation from https://github.com/ModelDepot/tfjs-yolo-tiny , but I am getting wrong output.

**Comment by pravastacaraka** [comment]
@anas-899 yes, i still haven't found a way to implement the nms either

**Comment by LundinMachine** [comment]
@anas-899 that repo uses yolo v3, built on darknet not torch.

**Comment by dewball345** [comment]
> > @glenn-jocher Ahh... I have tried it for the YOLOv5s default model, and it works. What's wrong with my training custom model?
> 
> Do you have a nms code written in tfjs to share? I was able to convert model to tfjs correctly, but I am struggling to parse boxes and scores after the prediction. Thanks!

How were you able to get the prediction!!!!!!! i'm getting `Cannot read property 'name' of undefined`

**Comment by pravastacaraka** [comment]
@batrlatom Have you found the solution?

@dewball345 As I explained here https://github.com/tensorflow/tfjs/issues/4637#issuecomment-855334742

**Comment by zldrobit** [comment]
@batrlatom @anas-899 @LundinMachine @dewball345  I have updated `tf-only-export` branch in https://github.com/ultralytics/yolov5/pull/1127, and it now supports tjfs model export.
To do this, I embed `tf.image.non_max_suppresssion` in the GraphDef and tfjs models.
So, there is no NMS code written in javascript.
Plz try the updated `tf-only-export` branch.

**Comment by dewball345** [comment]
@zldrobit I also created a repo with nms, but in addition it contains some preprocessing/postprocessing utilities as well as other stuff like drawing to canvas. https://github.com/dewball345/ear.js

**Comment by zldrobit** [comment]
@dewball345 That's cool. I looked into the repo and found that you used `tf.image.nonMaxSuppressionAsync` in tfjs, which I didn't found before. I noticed that you reported the inference speed is 12 fps and your model resolution is 640x640. What device do you use for inference?

**Comment by dewball345** [comment]
@zldrobit Oh my, i didn't realize that. I'm using a relatively high-end pc, so the 12 fps is definitely not that accurate. Thanks for bringing this up, I've changed my readme so as to not mislead others

**Comment by dewball345** [comment]
> @dewball345 That's cool. I looked into the repo and found that you used `tf.image.nonMaxSuppressionAsync` in tfjs, which I didn't found before. I noticed that you reported the inference speed is 12 fps and your model resolution is 640x640. What device do you use for inference?

Originally i used tf.image.nonMaxSuppression, but i got a warning in my console.

**Comment by thaingoc2604** [comment]
how to convert model .pt to tflite

**Comment by glenn-jocher** [comment]
@thaingoc2604 see **TFLite, ONNX, CoreML, TensorRT Export** 🚀 tutorial for TFLite export instructions:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TFLite, ONNX, CoreML, TensorRT Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by SkalskiP** [comment]
Hi, @glenn-jocher 👋! I just wanted to let you know, that I created a yolov5js [npm package](https://www.npmjs.com/package/yolov5js) that allows for almost effortless deployment of YOLOv5 models converted to tensorflow.js format on websites.

I actually used the newly created package, to add YOLOv5 support in makesense.ai. Here is a pre-release [instance](https://feature-156-import-custom-model-yolov5.d2e9l8xwkaodsq.amplifyapp.com/) and a short video showcasing new feature.


https://user-images.githubusercontent.com/26109316/193219363-338c0aba-9473-43f3-bde5-f2c1669de174.mp4

**Comment by glenn-jocher** [comment]
Hi @SkalskiP, that's fantastic to hear! It's great to see the YOLOv5 community thriving and building innovative tools. Congratulations on creating the `yolov5js` NPM package and integrating YOLOv5 support into makesense.ai. Your contribution is invaluable to the community. Keep up the excellent work, and feel free to reach out if you need any assistance or have any questions.
