### ISSUE TITLE
What order of magnitude  is the total loss value when training converges?  

### ISSUE THREAD

**Issue by TangMinLeo** [ultralytics/yolov5#2128]
## ❔Question
During training process, there maybe the occasion that the total loss does not decrease. How could I judge that the training converges. I mean is there a threshold for the total loss value for convergence judgment?

**Comment by glenn-jocher** [comment]
@TangMinLeo the fitness function determines when a 'best.pt' model is saved. This function function defined by a weighted combination of metrics. You can modify this to a minimum loss formulation if you'd like, details are up to you.

https://github.com/ultralytics/yolov5/blob/73a066993051339f6adfe5095a7852a2b9184c16/utils/metrics.py#L12-L16
