### ISSUE TITLE
model forward time

### ISSUE THREAD

**Issue by bixiaopeng0** [ultralytics/yolov5#2135]
## ❔Question
Hi,
I want to train a more quickly model,so I set depth_multiple: 0.10 width_multiple: 0.35
but the model forward time is the same with yolov5s,do you know the reason?
## Additional context
` 
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.25, device='', exist_ok=False, img_size=640, iou_thres=0.45, name='exp', project='runs/detect', save_conf=False, save_txt=False, source='data/images', update=False, view_img=False, weights=['/code/u_yolov5/yolov5/runs/train/exp48/weights/last.pt'])
YOLOv5  torch 1.7.1 CUDA:0 (GeForce RTX 2080 Ti, 11019.4375MB)
Fusing layers... 
Model Summary: 196 layers, 3387234 parameters, 0 gradients, 7.7 GFLOPS
use half------------------------------------
image 1/2 /code/u_yolov5/yolov5/data/images/bus.jpg: 640x480 3 persons, Done. (0.010s)
image 2/2 /code/u_yolov5/yolov5/data/images/zidane.jpg: 384x640 2 persons, Done. (0.009s)
Results saved to runs/detect/exp25
Done. (0.099s)
平均时间. (0.009s)

Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.25, device='', exist_ok=False, img_size=640, iou_thres=0.45, name='exp', project='runs/detect', save_conf=False, save_txt=False, source='data/images', update=False, view_img=False, weights=['/code/u_yolov5/yolov5/weights/yolov5s.pt'])
YOLOv5  torch 1.7.1 CUDA:0 (GeForce RTX 2080 Ti, 11019.4375MB)

Fusing layers... 
Model Summary: 224 layers, 7266973 parameters, 0 gradients, 17.0 GFLOPS
use half------------------------------------
image 1/2 /code/u_yolov5/yolov5/data/images/bus.jpg: 640x480 4 persons, 1 bus, Done. (0.009s)
image 2/2 /code/u_yolov5/yolov5/data/images/zidane.jpg: 384x640 2 persons, 1 tie, Done. (0.009s)
Results saved to runs/detect/exp26
Done. (0.094s)
平均时间. (0.009s)

`  
        t1 = time_synchronized()
        pred = model(img, augment=False)[0]
        pred = non_max_suppression(pred, opt.conf_thres, opt.iou_thres, classes=opt.classes, agnostic=opt.agnostic_nms)
        t2 = time_synchronized()

`

**Comment by glenn-jocher** [comment]
@bixiaopeng0 the reason is likely that fixed cost operations are starting to dominate your inference time (i.e. NMS etc.).
