### ISSUE TITLE
pytorch version 1.6.0 without nn.silu() activation function.

### ISSUE THREAD

**Issue by jiyuwangbupt** [ultralytics/yolov5#2136]
## ❔Question
My pytorch version is 1.6.0 without nn.silu() activation function. Can I use the latest code for training without modifying the pytorch version?

**Comment by zhiqwang** [comment]
Actually you could just test as follows:

```
>>> m = nn.SiLU()
>>> input = torch.randn(2)
>>> output = m(input)
```

EDIT: You could replace `nn.SiLU()` with belows if there are no original implementation of `SiLU()`

https://github.com/ultralytics/yolov5/blob/73a066993051339f6adfe5095a7852a2b9184c16/utils/activations.py#L8-L12

**Comment by glenn-jocher** [comment]
@jiyuwangbupt yes you can use the export-friendly SiLU version above, though this is not optimized for training and your training will be a little slower and use a little more CUDA memory. 

I would update to 1.7.

**Comment by HamdiTarek** [comment]
How can I solve this issue if I don't have permission to change or upgrade the torch on the server (torch 1.6.0)? I am only able to change the YOLOv5 code. I am writing inference code with a custom model.


<html>
<body>


2021/11/20 07:32:14  | AttributeError: Can't get attribute 'SiLU' on
-- | --
   2021/11/20 07:32:14  | result = unpickler.load()
   2021/11/20 07:32:14  | File "/opt/cloud/3rdComponent/anaconda/lib/python3.8/site-packages/torch/serialization.py", line 842, in _load
   2021/11/20 07:32:14  | return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
   2021/11/20 07:32:14  | File "/opt/cloud/3rdComponent/anaconda/lib/python3.8/site-packages/torch/serialization.py", line 584, in load
   2021/11/20 07:32:14  | model = torch.load(model_path, map_location=device)['model'].float()
   2021/11/20 07:32:14  | File "/opt/algorithm/src/main.py", line 70, in


</body>
</html>

**Comment by glenn-jocher** [comment]
@HamdiTarek it appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual Python 3.8 environment, clone the latest repo ([code changes daily](https://github.com/ultralytics/yolov5/commits/master)), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below. 


## Requirements

[**Python>=3.6.0**](https://www.python.org/) with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) installed including [**PyTorch>=1.7**](https://pytorch.org/get-started/locally/). To get started:
```bash
$ git clone https://github.com/ultralytics/yolov5
$ cd yolov5
$ pip install -r requirements.txt
```

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), validation ([val.py](https://github.com/ultralytics/yolov5/blob/master/val.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/export.py)) on MacOS, Windows, and Ubuntu every 24 hours and on every commit.
