### ISSUE TITLE
Facing issue when inferencing yolov5 model with torchscript

### ISSUE THREAD

**Issue by sourabhyadav** [ultralytics/yolov5#2139]
## ❔Question
I am facing the below issue when facing while inferencing the model with exported torchscript model. Anyone who has tried it please share your views. 

## Additional context
Model saving was done using the ```export.py``` file:
```
# Update model
    for k, m in model.named_modules():
        m._non_persistent_buffers_set = set()  # pytorch 1.6.0 compatability
        if isinstance(m, models.common.Conv) and isinstance(m.act, nn.Hardswish):
            m.act = Hardswish()  # assign activation
        # if isinstance(m, models.yolo.Detect):
        #     m.forward = m.forward_export  # assign forward (optional)
    model.model[-1].export = True  # set Detect() layer export=True
    y = model(img)  # dry run

    # TorchScript export
    try:
        print('\nStarting TorchScript export with torch %s...' % torch.__version__)
        f = opt.weights.replace('.pt', '.torchscript.pt')  # filename
        ts = torch.jit.trace(model, img)
        ts.save(f)
        print('TorchScript export success, saved as %s' % f)
    except Exception as e:
        print('TorchScript export failure: %s' % e)
```

Run:
```
python3 models/export.py --weights yolov5m.pt --img-size 640
```

Model loading is done like this:
```
self.model = torch.jit.load(weights, map_location=self.device) # tochscrpt model and device is cuda:0 
```

Model loading seems fine. But the issue comes when we try to inference the model:
Output:
```
Traceback (most recent call last):
  File "face_recognition.py", line 84, in <module>
    embed_for_analysis()
  File "face_recognition.py", line 80, in embed_for_analysis
    inference.main(args, logger)
  File "/data/sourabh/Releases/smart_vision/facenet_master/tycoai_vision/inference.py", line 81, in main
    camera_object_list, args.face_detector, logger=logger, args=args)
  File "/data/sourabh/Releases/smart_vision/facenet_master/tycoai_vision/analyze_frames.py", line 37, in detect_and_track_faces
    logger=logger, removed_tracks=removed_tracks, args=args)
  File "/data/sourabh/Releases/smart_vision/facenet_master/tycoai_vision/analyze_frames.py", line 120, in detect_normalize_by_face_detector
    bounding_boxes = detection_network.detect(np.stack(frames_downsampled))
  File "/data/sourabh/Releases/smart_vision/facenet_master/tycoai_vision/face_detector/yolov5/yolov5_model.py", line 176, in detect
    inf_out, _ = self.model(imgs, augment=False)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
RuntimeError: forward() expected at most 2 argument(s) but received 3 argument(s). Declaration: forward(__torch__.models.yolo.Model self, Tensor x) -> (Tensor[])
```

Environment:
```
OS: Ubuntu 18.04
GPU: Nvidia RTX 2080 Ti
Cuda: 10.1
```
Is am I missing something here? 
What are things to consider when working with torchscript? 
Did anyone has tried inferencing with yolov5 torchscript model? 
Please guide.

**Comment by zhiqwang** [comment]
Hi @sourabhyadav , It seems that there are something wrong of the inputs on the `torchscript` sides. How do you process the image and sent it to the `torchscript` side?

**Comment by sourabhyadav** [comment]
Hi @zhiqwang 
Following is my inference loop:

```
for img in batch_frames:

            # Padded resize
            img = letterbox(img, new_shape=self.input_size)[0]
            # Convert
            img = img.transpose(2,0,1)  # Only transpose to 3x640x640 format, BGR to RGB Not required as frames are RGB, 
            
            img = np.ascontiguousarray(img)
            
            # Create the batach of frames
            img_list.append(torch.from_numpy(img).cuda())

        # Stack and move it to gpu
        imgs = torch.stack(img_list, 0)
        imgs = imgs.to(self.device,  non_blocking=True)
        
        # Preprocessing
        imgs = imgs.half() if self.half else imgs.float()  # uint8 to fp16/32
        imgs /= 255.0  # Normalize 0 - 255 to 0.0 - 1.0

        # Disable gradients
        with torch.no_grad():

            # Inference model
            inf_out, _ = self.model(imgs, augment=False)  # ERROR 

```

**Comment by sourabhyadav** [comment]
@zhiqwang Thanks for the observation. When I removed extra params from inference API i.e.  ```augment=False``` the inference worked:
```
# Inference model
inf_out = self.model(imgs)
```

But now it outputs the list rather than a tensor.

Below is the analysis:

At normal inference, the output is a torch tensor and the shape is consistent wrt to batch size:

Input shape:
imgs size:  torch.Size([2, 3, 384, 640])

Output shape:
dtype=torch.float16)  shape:  torch.Size([2, 15120, 85])


However, in the torchscript output is a list and the length of 3 even when the input batch size is 1 or 2.

Input Shape:
imgs size:  torch.Size([1, 3, 384, 640])

Output Shape:
inf_out[0] : torch.Size([1, 3, 48, 80, 85])
inf_out[1] : torch.Size([1, 3, 24, 40, 85])
inf_out[2] : torch.Size([1, 3, 12, 20, 85])

The doubts I am having is:
Although the overall output size matches but I am not sure how to pack these properly for further processing like nms and box filtering etc. 

Do you have any experience regarding torchscript unpacking or behavior in such batched input cases?

**Comment by zhiqwang** [comment]
Hi @sourabhyadav 

Within my limited knowledge, there are two ways to process this problem.

- The first is to export the lists of **feature map** as you are doing now, then you should rewrite the `nms` on the other backends (depends on your needs), for example, if you want to deploy it on `libtorch`, you can refer to yasenh's implementation [here](https://github.com/yasenh/libtorch-yolov5).
- The second is to contain the `nms` ops into the `torchscript`, `torchvision` did support this way, in that ways, the export of `torchscript` is `boxes`, `scores` and `labels`. And you can refer to my [repo](https://github.com/zhiqwang/yolov5-rt-stack).

**Comment by sourabhyadav** [comment]
@zhiqwang Thanks for the suggestions.
I do not have any experience with ```libtorch``` so option 1 might be difficult for me. 
Regarding option 2: I will try with your repo. 

Please help me with a few clarifications, is the models used in your repo are exactly the same as Ultralyrics Yolov5. 
Also if I have a custom trained model with less than 80 classes does your script will work for my custom trained model as well?

**Comment by zhiqwang** [comment]
> Please help me with a few clarifications, is the models used in your repo are exactly the same as Ultralyrics Yolov5.
> Also if I have a custom trained model with less than 80 classes does your script will work for my custom trained model as well?

Hi @sourabhyadav Yep, you can get the same result as in ultralytics/yolov5, and you can find the [tips](https://github.com/zhiqwang/yolov5-rt-stack#updating-checkpoint-from-ultralyticsyolov5) to convert the trained checkpoint in my repo, if you have any questions, fell free to open an issue about it.

**Comment by woshizhangcheng** [comment]
how to fix??

**Comment by pkolebski** [comment]
> how to fix??

I was also struggling with it. The easiest way was to use [https://github.com/zhiqwang/yolov5-rt-stack](yolov5-rt-stack).

**Comment by nobody-cheng** [comment]
> > how to fix??
> 
> I was also struggling with it. The easiest way was to use [https://github.com/zhiqwang/yolov5-rt-stack](yolov5-rt-stack).

```
# export.py  >>>> model.model[-1].export = False  # set
python models/export.py --weights ./runs/train/exp5/weights/best.pt --img 640 --batch 1
```

```python
import torch
import torchvision.transforms as tfrm
from PIL import Image, ImageDraw
from utils import non_max_suppression, adjust_ratio_xyxy

model = torch.jit.load("./assets/best.torchscript.pt")
img = Image.open("./images/people(47).jpg").convert("RGB")
img_ = img.resize((640, 640))
inp = tfrm.ToTensor()(img_).unsqueeze(0)
print('input shape', inp.shape)

pred = model(inp)
pred = pred[0]
print('pred shape', pred.shape)
pred = non_max_suppression(pred)[0].cpu().numpy().tolist()
print(pred)
```
