### ISSUE TITLE
Addling a CLI argument to load hyper params config form custom path would be helpful

### ISSUE THREAD

**Issue by qsheeeeen** [ultralytics/yolov5#214]
## 🚀 Feature

Addling a CLI argument to load hyper params config form custom path would be helpful to try different hyp without making any changes to this repo.
For example `python3 train.py --hyp ../hyp_custom.json`

## Motivation

I am aware that I can put a `hyp*.txt` in the repo to overwrite the default hyp. But I used this repo as a sub-module of my repo. It will change this repo to make it happened. Putting model config somewhere and loading it later is very convenient compered to loading hyp config. It would be more convenient and flexible to make it an CLI argument.

## Additional context

It is easy to make this happened and I have already make some commit to my clone.

**Comment by glenn-jocher** [comment]
@qsheeeeen yes this is a great idea! There is already a PR open on the subject, which uses yaml files for configuration, which may be more user friendly for viewing. Perhaps you could review and comment on the PR:
https://github.com/ultralytics/yolov5/pull/104
