### ISSUE TITLE
Does the resolution of image in data set need to be unified?

### ISSUE THREAD

**Issue by Mrgao9** [ultralytics/yolov5#2141]
## ❔Question
The image resolutions in my dataset are different, for example, 640 * 480 and 1920 * 1080. Does the resolution of image in data set need to be unified? Will it affect the training effect? I observed that the image resolution in the coco dataset would not differ much。

I'm looking forward to your reply. Thank you！

**Comment by hcakmak7** [comment]
As far I know, it does not effect your training. --img-size comment resize all images in same size.
