### ISSUE TITLE
how to train a multiple lables dataset for one object?

### ISSUE THREAD

**Issue by tms2003** [ultralytics/yolov5#2143]
## ❔Question

Dir sir:
 
I want to give a object multiple lables ,so, how to do this for my custom dataset?

**Comment by glenn-jocher** [comment]
@tms2003 multi-label detection is on by default. To **train** with multiple labels, you simply use multiple rows, one for each class, i.e.:

image.txt label with multi-label class 0 and 23 (same box):
```
0  .5 .5 .5 .5
23 .5 .5 .5 .5
```

**Comment by tms2003** [comment]
@glenn-jocher thank u ,so ,how can I get multi-label clas for one object when inference?

**Comment by glenn-jocher** [comment]
@tms2003 multi-label inference is the default behavior for YOLOv5 when your class count > 1. No additional steps are required to use it.

NMS settings:
https://github.com/ultralytics/yolov5/blob/86897e366312c01c2e32a004564480e4793febea/utils/general.py#L350-L358
