### ISSUE TITLE
Reading properties of pre-trained model

### ISSUE THREAD

**Issue by khalidw** [ultralytics/yolov5#2145]
## Additional context

Hi! I recently trained a few models, and I want to know what epoch has produced the best.pt model. I tried loading the trained model and reading the properties as follows:

```
ckpt = torch.load('yolov5s.pt')
ckpt['epoch']
```

the problem is I get a value of ``-1`` . Is there a way to get the epoch number of the trained model

**Comment by glenn-jocher** [comment]
@khalidw unfortunately no, checkpoints don't have their training logs embedded in them. You'd have to refer to seperate logging results, i.e. Tensorboard, W&B or results.png related to the checkpoint.
