### ISSUE TITLE
test images not saved in runs/exp

### ISSUE THREAD

**Issue by HareshKarnan** [ultralytics/yolov5#2146]
## ❔Question
I built a custom dataset on which i run yolo training using the yolov5s network. However, I noticed that before training starts, training batch images are being saved as  :
train_batch0.jpg
train_batch1.jpg
train_batch2.jpg

whereas, testing images are not generated / saved in runs/exp after each epoch. what is it that I'm missing ? 

## Additional context
here is the opt.yaml file :

```
weights: yolov5s.pt
cfg: ''
data: data/ycb.yaml
hyp: data/hyp.finetune.yaml
epochs: 300
batch_size: 32
img_size:
- 640
- 480
rect: true
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: 0,1,2,3
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
log_imgs: 16
log_artifacts: false
workers: 12
project: run
name: exp
exist_ok: false
quad: false
world_size: 1
global_rank: -1
save_dir: run/exp
total_batch_size: 32
```

**Comment by glenn-jocher** [comment]
@HareshKarnan yes train*.jpg batches are saved on first epoch so you can verify your labels are correctly overlaying your objects, and to visualize the augmentation policy effects. 

test*.jpg batches are saved only on final epoch of training. They are not plotted on first epoch because you'd likely get poor results.

**Comment by HareshKarnan** [comment]
thanks @glenn-jocher for the quick response ! Is it currently possible to locally visualize detections on the test*.jpg batches after every epoch ?

**Comment by HareshKarnan** [comment]
In the train custom data tutorial, there is an image called "test_batch0_pred.jpg", is it possible to get such predictions after each epoch of training ?

**Comment by glenn-jocher** [comment]
@HareshKarnan sure, you can customize test.py plots here:
https://github.com/ultralytics/yolov5/blob/e9b3de463ad7734d41c059a4a513472ed618b7a1/test.py#L207-L213
