### ISSUE TITLE
I want to train my own image from 0(my own image size is 1280*512, not coco image) , how to set the  '--img-size' and '--weights' ?

### ISSUE THREAD

**Issue by plantplant** [ultralytics/yolov5#2152]
## ❔Question
Thank you for your excellent@glenn-jocher. I am now having a problem with the scale parameter '--img-size' and '--weights' set in the training model.The size of my own image (not coco image) is 1280 * 512. How can I set the '--image-size' parameter? In addition, I want to start training from 0. How to set the '--weight' parameter?Must an initial weight be given?

**Comment by glenn-jocher** [comment]
@plantplant we try to make training your custom data super easy :)

If your images contain small objects you may want to train at native resolution, which for you would be `--img 1280`, though keep in mind this will use significant CUDA memory and you will need smaller batch sizes to avoid OOM (out of memory) issues. You should train at the same size you will deploy at, so keep in mind that if you train at 1280, then you will also get best results running inference at the same --img 1280 (though inference will also work at lower accuracy for smaller inference sizes, i.e. --img 640).

To start training from scratch (not recommended), you simply pass `--weights ''`. 

If you are just getting started however, I would recommend you simply train with all default settings first to establish a baseline before trying to improve performance, i.e. perhaps this command:

`python train.py --weights yolov5m.pt --img 640 --data custom.yaml`

**Comment by plantplant** [comment]
thank you very much @glenn-jocher

**Comment by ausollet** [comment]
Let's say I have images of varying sizes, do I need to resize the images to 1280 before I run the script with "python train.py --weights yolov5m.pt --img 1280 --data custom.yaml" or are the inputs being resized within the script. Was not able to find the resizing part in the script but the model still seems to run. Hence wanted to understand what is happening and how.

**Comment by glenn-jocher** [comment]
@ausollet image resizing is done automatically, no action is required on your part.
