### ISSUE TITLE
run detect.py connect rtsp aborted exit

### ISSUE THREAD

**Issue by liuhetongzi** [ultralytics/yolov5#2155]
## ❔Question
I run detect.py to connect rtsp address, When running a few minutes, the script aborted exit， I guess it can not get rtsp，the frame is none，what should I do， please give me some help，Thanks

## Additional context
environment： centos7
yolov5： lastest version ， upgrade now
command： python detect.py --source='rtsp://username:password@ip:554/h264/ch1/main/av_stream'
![image](https://user-images.githubusercontent.com/23496061/107140884-43c9af00-6960-11eb-8e29-0701d0bb176b.png)

**Comment by glenn-jocher** [comment]
@liuhetongzi I tried to reproduce your command but the `--source` does not work for me:

```bash
(venv) glennjocher@Glenns-iMac yolov5 % python detect.py --source='rtsp://admin:fivestar12345@10.192.0.126:554/h264/ch1/main/av_stream'
Namespace(weights='yolov5s.pt', source='rtsp://admin:fivestar12345@10.192.0.126:554/h264/ch1/main/av_stream', img_size=640, conf_thres=0.25, iou_thres=0.45, device='', view_img=False, save_txt=False, save_conf=False, classes=None, agnostic_nms=False, augment=False, update=False, project='runs/detect', name='exp', exist_ok=False)
YOLOv5 v4.0-70-gc32b0af torch 1.7.1 CPU

Fusing layers... 
Model Summary: 224 layers, 7266973 parameters, 0 gradients, 17.0 GFLOPS
OpenCV: Couldn't read video stream from file "rtsp://admin:fivestar12345@10.192.0.126:554/h264/ch1/main/av_stream"
[ERROR:0] global /private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-req-build-yaf6rry6/opencv/modules/videoio/src/cap.cpp (142) open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.5.1) /private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-req-build-yaf6rry6/opencv/modules/videoio/src/cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): rtsp://admin:fivestar12345@10.192.0.126:554/h264/ch1/main/av_stream in function 'icvExtractPattern'


1/1: rtsp://admin:fivestar12345@10.192.0.126:554/h264/ch1/main/av_stream... Traceback (most recent call last):
  File "/Users/glennjocher/PycharmProjects/yolov5/detect.py", line 175, in <module>
    detect()
  File "/Users/glennjocher/PycharmProjects/yolov5/detect.py", line 50, in detect
    dataset = LoadStreams(source, img_size=imgsz, stride=stride)
  File "/Users/glennjocher/PycharmProjects/yolov5/utils/datasets.py", line 278, in __init__
    assert cap.isOpened(), f'Failed to open {s}'
AssertionError: Failed to open rtsp://admin:fivestar12345@10.192.0.126:554/h264/ch1/main/av_stream
(venv) glennjocher@Glenns-iMac yolov5 % 

```

**Comment by constantinfite** [comment]
I obtain the same error, I connect 3 cameras IP to my computer.
I run the command : python detect.py --weights ./weights/best.pt --conf 0.3 --iou 0.5 --source 'streams.txt'  --save-txt --view-img.

stream.txt : 
rtsp://192.168.1.20:554/1/h264major
rtsp://192.168.1.19:554/1/h264major
rtsp://192.168.1.18:554/1/h264major

But after some time it exits with this error : 

File "C:\Users\const\Documents\PFE\Code\yolov5\utils\datasets.py", line 795, in letterbox
    shape = img.shape[:2]  # current shape [height, width]
AttributeError: 'NoneType' object has no attribute 'shape'
[h264 @ 000001c6faedcd00] error while decoding MB 68 0, bytestream -11

I think it is related to this post : https://github.com/ultralytics/yolov5/issues/1510

**Comment by glenn-jocher** [comment]
@liuhetongzi @constantinfite yes these are both related to #1510 and #2196. Will prioritize as this is an issue for multiple users now.

**Comment by Flyooofly** [comment]
> ## ❔Question
> I run detect.py to connect rtsp address, When running a few minutes, the script aborted exit， I guess it can not get rtsp，the frame is none，what should I do， please give me some help，Thanks
> 
> ## Additional context
> environment： centos7
> yolov5： lastest version ， upgrade now
> command： python detect.py --source='rtsp://username:password@ip:554/h264/ch1/main/av_stream'
> ![image](https://user-images.githubusercontent.com/23496061/107140884-43c9af00-6960-11eb-8e29-0701d0bb176b.png)

你好，请问提示 assert cap is open 这个怎么解决，是摄像头没打开吗？

**Comment by glenn-jocher** [comment]
@Flyooofly streaming sources are dropped-frame robust since a couple months ago. Your code may be out of date.

If you believe you have a reproducible issue, we suggest you close this issue and raise a new one using the 🐛 **Bug Report template**, providing screenshots and a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. Thank you!

**Comment by PIjarihd** [comment]
> ## ❔Question
> I run detect.py to connect rtsp address, When running a few minutes, the script aborted exit， I guess it can not get rtsp，the frame is none，what should I do， please give me some help，Thanks
> 
> ## Additional context
> environment： centos7
> yolov5： lastest version ， upgrade now
> command： python detect.py --source='rtsp://username:password@ip:554/h264/ch1/main/av_stream'
> ![image](https://user-images.githubusercontent.com/23496061/107140884-43c9af00-6960-11eb-8e29-0701d0bb176b.png)

Can you please explain me the command? I am trying to access the IP camera but I am failed. It  gives the following error: AssertionError: Failed to open rtsp://login:pass@IPAddress

**Comment by glenn-jocher** [comment]
@dhirajip you might want to do some debugging in the streamloader to see what's going on:
https://github.com/ultralytics/yolov5/blob/0c93ec762aec91e4fd91762870f06e786abc9b10/utils/datasets.py#L323-L334

**Comment by sarvaatmak** [comment]
> ## Question
> I run detect.py to connect rtsp address, When running a few minutes, the script aborted exit， I guess it can not get rtsp，the frame is none，what should I do， please give me some help，Thanks
> 
> ## Additional context
> environment： centos7 yolov5： lastest version ， upgrade now command： python detect.py --source='rtsp://username:password@ip:554/h264/ch1/main/av_stream' ![image](https://user-images.githubusercontent.com/23496061/107140884-43c9af00-6960-11eb-8e29-0701d0bb176b.png)

If you are running multiple streams and want to keep stream alive i would suggest that you can make this changes in the code of datasets.py

in class LoadStreams

    def __next__(self):
        self.count += 1
        #if not all(x.is_alive() for x in self.threads) or cv2.waitKey(1) == ord('q'):  # q to quit
        #for x in self.threads:
        if cv2.waitKey(1) == ord('q'):
            #cv2.waitKey(1) == ord('q') # q to quit
            cv2.destroyAllWindows()
            raise StopIteration

this way your program will not close and that window stream will be black and other streams will be working, but i have not found how to reconnect once that stream starts.
