### ISSUE TITLE
训练yolo5s模型时，如果label中的内容多复制了一遍，影响模型训练的精度吗？

### ISSUE THREAD

**Issue by yamisky** [ultralytics/yolov5#2156]
YOLO5的label中，txt的每一行代表图像中一个目标的类别和坐标，如果我错误地将label中内容多复制了一遍，比如一张图像中，有5个目标，即该图所属的标签txt中应该只有5行，但我将这5行内容复制了一遍，txt中变成10行了。对于这样的训练集和标签，会影响模型训练的精度吗？

**Comment by glenn-jocher** [comment]
@yamisky you can not train with duplicate labels. Scanning checks for duplicate labels. If an image contains duplicate labels the image will be ignored (not used) for training or testing, as well as a warning printed to screen:
https://github.com/ultralytics/yolov5/blob/a5359f6c3288c0549193681632c8e9b324e81017/utils/datasets.py#L457-L466

**Comment by yamisky** [comment]
Thanks！
&nbsp;




尹明
长沙润伟机电科技有限责任公司


 联系我









&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Glenn Jocher"<notifications@github.com&gt;; 
发送时间: 2021年2月8日(星期一) 凌晨2:03
收件人: "ultralytics/yolov5"<yolov5@noreply.github.com&gt;; 
抄送: "果子壳"<2211959895@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ultralytics/yolov5] 训练yolo5s模型时，如果label中的内容多复制了一遍，影响模型训练的精度吗？ (#2156)





 
@yamisky you can not train with duplicate labels. Scanning checks for duplicate labels. If an image contains duplicate labels the image will be ignored (not used) for training or testing, as well as a warning printed to screen:
 https://github.com/ultralytics/yolov5/blob/a5359f6c3288c0549193681632c8e9b324e81017/utils/datasets.py#L457-L466
