### ISSUE TITLE
Yolov5 with ubuntu

### ISSUE THREAD

**Issue by ingtidy2021** [ultralytics/yolov5#2157]
## ❔
Hi, I tried a code but I got an error. Can you please help me.

ubuntu@ubuntu1804:~/yolov5$ python train.py --data fire.yaml --cfg yolov5x.yaml --weights '' --batch-size 6
  File "train.py", line 40
    logger.info(colorstr('hyperparameters: ') + ', '.join(f'{k}={v}' for k, v in hyp.items()))
                                                                   ^
SyntaxError: invalid syntax

**Comment by iceisfun** [comment]
Make sure you are not using an old version of python

We are using 3.8.5 via the yolo v5 docker container

https://hub.docker.com/r/ultralytics/yolov5

**Comment by MaryiamZahoor** [comment]
You should use the following command :
**!python3**   train.py --img 640 --batch 16 --epochs 3 --data coco128.yaml --weights yolov5s.pt --nosave --cache

instead of
**!python**  train.py --img 640 --batch 16 --epochs 3 --data coco128.yaml --weights yolov5s.pt --nosave --cache

**Comment by VV1314** [comment]
> You should use the following command : **!python3** train.py --img 640 --batch 16 --epochs 3 --data coco128.yaml --weights yolov5s.pt --nosave --cache
> 
> instead of **!python** train.py --img 640 --batch 16 --epochs 3 --data coco128.yaml --weights yolov5s.pt --nosave --cache

Thank you very  very much!

**Comment by glenn-jocher** [comment]
@VV1314 you're very welcome! 😊 Feel free to reach out if you have any more questions or need further assistance. Good luck with your YOLOv5 project!
