### ISSUE TITLE
Using custom pre-trained model weights for transfer learning with different classes return RuntimeError: The size of tensor a (27) must match the size of tensor b (66) at non-singleton dimension 0

### ISSUE THREAD

**Issue by sarmientoj24** [ultralytics/yolov5#2158]
For context, I am doing road damage detection. Here is my procedure.

1. Using a larger dataset A, I trained a yolov5 model using yolov5m.pt (weights) with **4 classes**. Image resolution is 512x512.
2. Saved model as model_a.pt
3. Using a smaller dataset B, I want to use model_a.pt as starting weights (kinda like transfer learning). New dataset has **17 classes.** Current resolution is 768x640. So i used `--rect --img-size 768` and even used `--img-size 512`.

I am getting the following error:
```

autoanchor: Analyzing anchors... anchors/target = 4.04, Best Possible Recall (BPR) = 0.9959
Image sizes 512 train, 512 test
Using 2 dataloader workers
Logging results to runs/train/exp2
Starting training for 172 epochs...

     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
   143/171     5.53G    0.1064   0.05333   0.07421    0.2339       111       512:   4%|▍         | 3/71 [00:03<01:42,  1.51s/it]Traceback (most recent call last):
  File "train.py", line 526, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 304, in train
    scaler.step(optimizer)  # optimizer.step
  File "/usr/local/lib/python3.6/dist-packages/torch/cuda/amp/grad_scaler.py", line 321, in step
    retval = optimizer.step(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/optim/lr_scheduler.py", line 67, in wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/optim/sgd.py", line 106, in step
    buf.mul_(momentum).add_(d_p, alpha=1 - dampening)
RuntimeError: The size of tensor a (27) must match the size of tensor b (66) at non-singleton dimension 0
Images sizes do not match. This will causes images to be display incorrectly in the UI.
```

I am not sure how to solve the error. Is it possible to just load all weights except last one for classes?

**Comment by sarmientoj24** [comment]
not sure what is causing the error here.

**Comment by glenn-jocher** [comment]
@sarmientoj24 using pretrained weights on a different dataset is the default use case, nothing special required, class counts irrelevant. You may want to train using default settings rather than --rect. If your error is reproducible please submit a full bug report using bug report template and code to reproduce in a common environment, i.e. colab notebook.

**Comment by sarmientoj24** [comment]
@glenn-jocher i am using my own custom dataset.
I also have tried removing `--rect` on the 2nd part of training

First part of training:
1. Train on **dataset A**, using `python train.py --img 512 --weights yolo5m.pt
2. Get the model (naming convention: model_a.pt)
**Note:** Dataset A is 512x512 resolution with 4 classes.

2nd Part of training:
1. Using model_a (see first part), train model_a on **dataset B** using `python train.py --img 736 --weights model_a.pt
Error comes here.
**Note:** Dataset B has images on size 736x640 with 17 classes.

**Comment by glenn-jocher** [comment]
@sarmientoj24 the only thing I can think of is that your code or pretrained models may be out of date. 

The --img size and number of classes should not have any effect on follow on trainings. For example I can train 20-class VOC at 512 from any pretrained COCO model, which is 80 classes trained at 640. The training is designed to do all of this automatically. To start training from any model on any dataset all you need is two arguments, nothing more.

`python train.py --data any_dataset.yaml --weights yolov5_any.pt`

**Comment by sarmientoj24** [comment]
@glenn-jocher 
>  For example I can train 20-class VOC at 512 from any pretrained COCO model, which is 80 classes trained at 640. 
I did this in part 1 of the training. Went smoothly.
My problem arises when I use the trained model on that procedure for another training on a different dataset with different classes

**Comment by glenn-jocher** [comment]
@sarmientoj24 it's all the same thing. Custom models that complete training on custom datasets are handled identically to the official models (that have completed training on COCO).

The training script updates and reconfigures any pretrained model to adapt to new datasets if necessary.

**Comment by glenn-jocher** [comment]
Any dataset can use any YOLOv5 pretrained model as initial weights, the class counts do not need to match. Example usage: train VOC (20 classes) starting from COCO-pretrained YOLOv5s (80 classes):
```bash
python train.py --data voc.yaml --weights yolov5s.pt
```

**Comment by glenn-jocher** [comment]
@yang-gis @sarmientoj24 **Any** dataset can use **any** YOLOv5 pretrained model as initial weights, the class counts do not need to match. Example usage: train VOC (20 classes) starting from COCO-pretrained YOLOv5s (80 classes):
```bash
python train.py --data voc.yaml --weights yolov5s.pt
```

**Comment by shining-love** [comment]
> @yang-gis @sarmientoj24 **Any** dataset can use **any** YOLOv5 pretrained model as initial weights, the class counts do not need to match. Example usage: train VOC (20 classes) starting from COCO-pretrained YOLOv5s (80 classes):
> 
> ```shell
> python train.py --data voc.yaml --weights yolov5s.pt
> ```

no、no.it is uncorrect...

**Comment by Kimberlime** [comment]
I had the same issue. I tried transfer learning with this below commented and error did not came.
\# optimizer.load_state_dict(ckpt['optimizer'])

**Comment by glenn-jocher** [comment]
@yang-gis @Kimberlime **Any** dataset can use **any** YOLOv5 pretrained model as initial weights, the class counts do not need to match. Example usage: train VOC (20 classes) starting from COCO-pretrained YOLOv5s (80 classes):
```bash
python train.py --data voc.yaml --weights yolov5s.pt
```

If you believe you have a reproducible issue, we suggest you close this issue and raise a new one using the 🐛 **Bug Report template**, providing screenshots and a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. Thank you!

**Comment by luislagardera** [comment]
Maybe the initial weight must be fully trained??
