### ISSUE TITLE
您好，这个如何让他只检测人类呢？其他的都屏蔽掉

### ISSUE THREAD

**Issue by Tiang-88** [ultralytics/yolov5#216]

**Comment by glenn-jocher** [comment]
@zzb1967736495 to detect only humans (class 0):

`python detect.py --classes 0`

**Comment by Tiang-88** [comment]
> @ zzb1967736495仅检测人类（0类）：
> 
> `python detect.py --classes 0`

您好，如何在文件里面改呢？比如人类，其他类单独的检测
