### ISSUE TITLE
degrees is radians?

### ISSUE THREAD

**Issue by gengyanlei** [ultralytics/yolov5#2160]
https://github.com/ultralytics/yolov5/blob/a5359f6c3288c0549193681632c8e9b324e81017/utils/datasets.py#L849

**Comment by iceisfun** [comment]
This looks like an opencv question, it seems the angle is degrees with positive values being counter-clockwise according to the opencv 3.4 documentation

https://docs.opencv.org/3.4.12/da/d54/group__imgproc__transform.html#gafbbc470ce83812914a70abfb604f4326

**Comment by gengyanlei** [comment]
@iceisfun 
tks，opencv defined  angle is degrees，but yolov5 define opencv‘s input is not！
https://github.com/ultralytics/yolov5/blob/a5359f6c3288c0549193681632c8e9b324e81017/data/hyp.finetune.yaml#L30

**Comment by glenn-jocher** [comment]
@gengyanlei 'degrees' indicates that the hyperparameter unit is degrees. 

Forall hyperparameter comments and units see:
https://github.com/ultralytics/yolov5/blob/master/data/hyp.scratch.yaml
