### ISSUE TITLE
The targets of test suddenly become 0

### ISSUE THREAD

**Issue by lucky-xu-1994** [ultralytics/yolov5#2161]
##  hi, thank you for your great work! 
I trained my own data for about 20 epochs, the targets of test suddenly become 0,and got a sudden increase in loss.  

![image](https://user-images.githubusercontent.com/57120921/107192452-940c4400-6a28-11eb-81df-c62ef047f104.png)
how can I solve this problem? please help!

**Comment by glenn-jocher** [comment]
@lucky-xu-1994 loss instabilities may be due to aggressive hyps (i.e. LR too high), or an indicator of problems in your dataset.

**Comment by lucky-xu-1994** [comment]
the problem has been solved (LR too high), so I would close this issue.
