### ISSUE TITLE
various result when trained many times

### ISSUE THREAD

**Issue by jaqub-manuel** [ultralytics/yolov5#2163]
Hello, thank you for this nice work.

With the same values and the same model as the custom dataset (everything is the same), when I train the model 3 or 5 times, I get different mAP, F1 and precision recall graphs. Although I chose the number of epocks very high, I still get different results. I train yolov5 model 1000 images for training and 200 for testing and for single class. I can never get the same results. 

If you can help with this, I would be grateful.

**Comment by glenn-jocher** [comment]
See https://pytorch.org/docs/stable/notes/randomness.html
