### ISSUE TITLE
Do I need to disable image flipping/mirroring?

### ISSUE THREAD

**Issue by adrianholovaty** [ultralytics/yolov5#2164]
Hello — thanks so much for this project. It's really great! Not only is the performance top-notch, the documentation and developer experience are very solid as well.

I noticed in the generated "mosaic" images that sometimes images are flipped into a mirror image. Does this mean that yolo is learning to detect objects in that flipped perspective? I work with image data in which there is an important difference between an image and the "flipped" version of itself, so I want to make sure my model won't be learning the wrong thing.

If yolo is indeed learning the flipped images, is there a way to disable this? Or do I not need to worry about it?

**Comment by mfruhner** [comment]
Hi,
yes this means that the model will learn the flipped version as the same class. To disable this you can create your own hyperparamter file (hyp.yaml) and set `fliplr: 0.0`, so that the probability of the image being flipped while augmenting is zero.

**Comment by adrianholovaty** [comment]
@mfruhner Thanks very much!

**Comment by Transigent** [comment]
> Hi,
> yes this means that the model will learn the flipped version as the same class. To disable this you can create your own hyperparamter file (hyp.yaml) and set `fliplr: 0.0`, so that the probability of the image being flipped while augmenting is zero.

@mfruhner  Just a followup if I may, my dataset consists of images and their horizontally mirrored versions that I have added as augmentations. 
- Does this mean that with` fliplr: 0.5  # image flip left-right (probability) ` 50% of images are also flipped and effectively used as training images during training?
- If I set this to 1.0 does that mean for every supplied image its mirror will also be used in training? ie. I dont have to supply the mirrored source images at all?
- With something like `degrees: 0.0  # image rotation (+/- deg)` does that mean that each training image is rotated the specified amount **in addition** to the unrotated training image? Or instead? Is it a fixed amount or a range for randomization?

Thanks for any guidance.

**Comment by Transigent** [comment]
PS I read 'Hyperparameter Evolution' but either it didn't have an answer, or I didn't understand well enough to extract one.

**Comment by glenn-jocher** [comment]
@Transigent the hyperparameter file does not define individual augmentations, it defines distributions which are randomly sampled at runtime. No image is ever seen twice during training. fliplr 0.5 defines a 50% lr flip probability.

<img width="1310" alt="Screen Shot 2021-02-10 at 1 16 47 PM" src="https://user-images.githubusercontent.com/26833433/107573504-7662ea00-6ba2-11eb-9de3-f1bc05eb96f2.png">

**Comment by Transigent** [comment]
Excellent thanks so much @glenn-jocher .

**Comment by SyedHamza0196** [comment]
@glenn-jocher what about " degrees: 0.0 # image rotation (+/- deg) " .
Is it probability or 0.5 means 90 degrees rotation

**Comment by glenn-jocher** [comment]
@SyedHamza0196 rotation units are in comment `# image rotation (+/- deg)`

**Comment by chinhcd** [comment]
@adrianholovaty: Hello, did you try to disable the flip function in the hyperparameter? does it work?
 I set the fliplr = 0 (in data/hyps/hyp.scratch.yaml) but the model after training still detects the flip left-right image.

![2](https://user-images.githubusercontent.com/38976813/142770889-6078c566-feae-465a-9e9f-5fc780ebd6e6.jpg)
![1](https://user-images.githubusercontent.com/38976813/142770893-29fc8107-00e2-42a7-ab34-b40cabc7945e.png)

**Comment by chinhcd** [comment]
@glenn-jocher : I set the fliplr = 0, but after training, the model still detects the flip left-right image. Is there another parameter I need to change to disable the flip images function? (  flipud is disabled)
Thank you very much.

**Comment by glenn-jocher** [comment]
@chinhcd fliplr hyperparameter control this augmentation. There is no other parameter.

**Comment by chinhcd** [comment]
@glenn-jocher : the fliplr setting in hyperparameter is strange. when you have time, could you please check it.
I trained a model with 2 classes: flip and non-flip (lr). the mAP0.5 is good(0.996) but when I tested with both train and val images, the model detected wrong (about 50%)
it happens with fliplr only.

In addition, with the model (fliplr = 0.0), if we test with the flipup images and fliplr images, only fliplr images always return high confidence score.

Thank you very much.

**Comment by glenn-jocher** [comment]
@chinhcd I have extremely little time, but if you create a reproducible example of a possible problem our team can start to investigate. With the above information we have nothing to reproduce.

**Comment by sarpx** [comment]
@glenn-jocher I've had this problem myself. Even though I did fliplr 0.0, the results worked in the opposite direction of what I wanted. Now I'm making fliplr 1.0 and giving another training, but I'm not so sure about the result. It looks like we can't turn off right and left rotation. This is very important for some trainings. The opposite of something can look like another letter or another object that we teach, and it causes confusion.

**Comment by glenn-jocher** [comment]
@sarpx 👋 Hello! Thanks for asking about **image augmentation**. YOLOv5 🚀 applies online imagespace and colorspace augmentations in the trainloader (but not the val_loader) to present a new and unique augmented [Mosaic](https://github.com/ultralytics/yolov5/blob/90b7895d652c3bd3d361b2d6e9aee900fd67f5f7/utils/datasets.py#L678-L732) (original image + 3 random images) each time an image is loaded for training. **Images are never presented twice in the same way**.

![YOLOv5 augmentation](https://user-images.githubusercontent.com/26833433/120995721-f3cfed00-c785-11eb-8ee2-b6ef2fa205e8.jpg)

### Augmentation Hyperparameters

The hyperparameters used to define these augmentations are in your hyperparameter file (default `data/hyp.scratch.yaml`) defined when training:
```
python train.py --hyp hyp.scratch-low.yaml
```
https://github.com/ultralytics/yolov5/blob/b94b59e199047aa8bf2cdd4401ae9f5f42b929e6/data/hyps/hyp.scratch-low.yaml#L6-L34

### Augmentation Previews

You can view the effect of your augmentation policy in your train_batch*.jpg images once training starts. These images will be in your train logging directory, typically `yolov5/runs/train/exp`:

`train_batch0.jpg` shows train batch 0 mosaics and labels:  
<img src="https://user-images.githubusercontent.com/26833433/131255960-b536647f-7c61-4f60-bbc5-cb2544d71b2a.jpg" width="800">


### YOLOv5 Albumentations Integration

[YOLOv5](https://github.com/ultralytics/yolov5) 🚀 is now fully integrated with [Albumentations](https://github.com/albumentations-team/albumentations), a popular open-source image augmentation package. Now you can train the world's best Vision AI models even better with custom Albumentations 😃! 

PR https://github.com/ultralytics/yolov5/pull/3882 implements this integration, which will automatically apply Albumentations transforms during YOLOv5 training if `albumentations>=1.0.3` is installed in your environment. See https://github.com/ultralytics/yolov5/pull/3882 for full details.

Example `train_batch0.jpg` on COCO128 dataset with Blur, MedianBlur and ToGray. See the YOLOv5 [Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb) to reproduce: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

<img src="https://user-images.githubusercontent.com/26833433/124400879-ff331b80-dd25-11eb-9b67-fe85ac4ca104.jpg" width="800">

Good luck 🍀 and let us know if you have any other questions!
