### ISSUE TITLE
About Mosaic9

### ISSUE THREAD

**Issue by newland07** [ultralytics/yolov5#2165]
Thanks for this nice work.
How to use mosaic4 and mosaic9 together.
In strach.yaml or finetune.yaml files only mosaic = 1 is present.
I just want to compare only mosaic9, only mosaic4, and both together (mosaic9+mosaic4), then compare performans.

There are also small sized objects that I would like to detect. That's why I want to add p2 to the head part. and remove p5.
Could you have a look to head right or not ?

https://github.com/ultralytics/yolov5/blob/a5359f6c3288c0549193681632c8e9b324e81017/models/yolov5s.yaml#L28

 [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, C3, [512, False]],  # 13

   [-1, 1, Conv, [128, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P2
   [-1, 3, C3, [128, False]],  # 17 (P2/4-small)

   [-1, 1, Conv, [256, 1, 1]],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, C3, [256, False]],  # 17 (P3/8-small)

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 14], 1, Concat, [1]],  # cat head P4
   [-1, 3, C3, [512, False]],  # 20 (P4/16-medium)

   #[-1, 1, Conv, [512, 3, 2]],
   #[[-1, 10], 1, Concat, [1]],  # cat head P5
   #[-1, 3, C3, [1024, False]],  # 23 (P5/32-large)

   [[17, 20, 23], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
  ]

many Thanks...

**Comment by glenn-jocher** [comment]
@newland07 you can switch from mosaic4 to mosaic9 by switching this line in the dataloader to load_mosaic9():
https://github.com/ultralytics/yolov5/blob/ace3e02e406307ed0cebc25aebe15835767107b2/utils/datasets.py#L506
