### ISSUE TITLE
WEBP image support for training YoloV5

### ISSUE THREAD

**Issue by Transigent** [ultralytics/yolov5#2166]
## ❔Question

I noted in [this YoloV3 post](https://github.com/ultralytics/yolov3/issues/678#issuecomment-591077708) that cv2 supports a range of image formats including WEBP. 

I assumed this would apply to YoloV% also, so I went ahead and regenerated my dataset as WEBP files (they are a lot smaller for the same quality) and tried to run on Colab in the usual way but it failed saying 'no images found'.

I then modified [line 28 of utils/dataset.py ](https://github.com/ultralytics/yolov5/blob/a5359f6c3288c0549193681632c8e9b324e81017/utils/datasets.py#L28)
`img_formats = ['bmp', 'jpg', 'jpeg', 'png', 'tif', 'tiff', 'dng']  # acceptable image suffixes`
to add webp as a suffix and it appears to be working fine.

Is there a reason why WEBP files are not enabled here by default?

Thanks! 
And thanks for the superb YoloV5 library!

**Comment by glenn-jocher** [comment]
@Transigent hi, great discovery! No reason not to include webp if it works. Can you please submit a PR with the extension addition? Thank you!
