### ISSUE TITLE
ERROR: Unexpected segmentation fault encountered in worker.

### ISSUE THREAD

**Issue by ChenYingpeng** [ultralytics/yolov5#217]
`

    python train.py --data data/voc.yaml --cfg models/yolov5s.yaml --batch-size 64 --resume
    Apex recommended for faster mixed precision training: https://github.com/NVIDIA/apex
    {'lr0': 0.01, 'momentum': 0.937, 'weight_decay': 0.0005, 'giou': 0.05, 'cls': 0.58, 'cls_pw': 1.0, 'obj': 1.0, 'obj_pw': 1.0, 'iou_t': 0.2, 
    'anchor_t': 4.0, 'fl_gamma': 0.0, 'hsv_h': 0.014, 'hsv_s': 0.68, 'hsv_v': 0.36, 'degrees': 0.0, 'translate': 0.0, 'scale': 0.5, 'shear': 0.0}
    Namespace(adam=False, batch_size=64, bucket='', cache_images=False, cfg='models/yolov5s.yaml', data='data/voc.yaml', 
    device='', epochs=300, evolve=False, img_size=[640, 640], multi_scale=False, name='', noautoanchor=False, nosave=False, 
    notest=False, rect=False, resume=True, single_cls=False, weights='weights/last.pt')
    Using CUDA device0 _CudaDeviceProperties(name='TITAN Xp COLLECTORS EDITION', total_memory=12195MB)
           device1 _CudaDeviceProperties(name='TITAN Xp COLLECTORS EDITION', total_memory=12196MB)

    Start Tensorboard with "tensorboard --logdir=runs", view at http://localhost:6006/

              from  n    params  module                                  arguments                     
      0             -1  1      3520  models.common.Focus                     [3, 32, 3]                    
      1             -1  1     18560  models.common.Conv                      [32, 64, 3, 2]                
      2             -1  1     19904  models.common.BottleneckCSP             [64, 64, 1]                   
      3             -1  1     73984  models.common.Conv                      [64, 128, 3, 2]               
      4             -1  1    161152  models.common.BottleneckCSP             [128, 128, 3]                 
      5             -1  1    295424  models.common.Conv                      [128, 256, 3, 2]              
      6             -1  1    641792  models.common.BottleneckCSP             [256, 256, 3]                 
      7             -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]              
      8             -1  1    656896  models.common.SPP                       [512, 512, [5, 9, 13]]        
      9             -1  1   1248768  models.common.BottleneckCSP             [512, 512, 1, False]          
     10             -1  1    131584  models.common.Conv                      [512, 256, 1, 1]              
     11             -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
     12        [-1, 6]  1         0  models.common.Concat                    [1]                           
     13             -1  1    378624  models.common.BottleneckCSP             [512, 256, 1, False]          
     14             -1  1     33024  models.common.Conv                      [256, 128, 1, 1]              
     15             -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
     16        [-1, 4]  1         0  models.common.Concat                    [1]                           
     17             -1  1     95104  models.common.BottleneckCSP             [256, 128, 1, False]          
     18             -1  1      9675  torch.nn.modules.conv.Conv2d            [128, 75, 1, 1]               
     19             -2  1    147712  models.common.Conv                      [128, 128, 3, 2]              
     20       [-1, 14]  1         0  models.common.Concat                    [1]                           
     21             -1  1    313088  models.common.BottleneckCSP             [256, 256, 1, False]          
     22             -1  1     19275  torch.nn.modules.conv.Conv2d            [256, 75, 1, 1]               
     23             -2  1    590336  models.common.Conv                      [256, 256, 3, 2]              
     24       [-1, 10]  1         0  models.common.Concat                    [1]                           
     25             -1  1   1248768  models.common.BottleneckCSP             [512, 512, 1, False]          
     26             -1  1     38475  torch.nn.modules.conv.Conv2d            [512, 75, 1, 1]               
     27   [-1, 22, 18]  1         0  models.yolo.Detect                      [20, [[116, 90, 156, 198, 373, 326], [30, 61, 62, 45, 59, 119], [10, 13, 16, 30, 33, 23]]]
    Model Summary: 191 layers, 7.30634e+06 parameters, 7.30634e+06 gradients

    Optimizer groups: 62 .bias, 70 conv.weight, 59 other
    Caching labels /home/ss/data/VOCdevkit/VOC2007/labels.npy (16551 found, 0 missing, 0 empty, 0 duplicate, for 16551 i
    Saving labels to /home/ss/data/VOCdevkit/VOC2007/labels.npy for faster future loading
    Caching labels /home/ss/data/VOCdevkit/VOC2007/labels.npy (4952 found, 0 missing, 0 empty, 0 duplicate, for 4952 ima
    Saving labels to /home/ss/data/VOCdevkit/VOC2007/labels.npy for faster future loading

    Analyzing anchors... Best Possible Recall (BPR) = 0.9998
    Image sizes 640 train, 640 test
    Using 8 dataloader workers
    Starting training for 300 epochs...

     Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
      0%|                                                                                       | 0/259 [00:00<?, ?it/s]ERROR: Unexpected segmentation fault 
      encountered in worker.
      0%|                                                                                       | 0/259 [00:02<?, ?it/s]
    Traceback (most recent call last):
      File "train.py", line 387, in <module>
        train(hyp)
      File "train.py", line 241, in train
        pred = model(imgs)
      File "/home/ss/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
      File "/home/ss/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 449, in forward
    outputs = self.parallel_apply(self._module_copies[:len(inputs)], inputs, kwargs)
      File "/home/ss/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 474, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
      File "/home/ss/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 77, in parallel_apply
    thread.join()
      File "/home/ss/anaconda3/envs/yolov5/lib/python3.7/threading.py", line 1032, in join
    self._wait_for_tstate_lock()
      File "/home/ss/anaconda3/envs/yolov5/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
      File "/home/ss/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
    RuntimeError: DataLoader worker (pid 12367) is killed by signal: Segmentation fault. `

## Environment
 - OS: [Ubuntu16.04]
 - GPU [2*Titan-Xp]
 - Pytorch==1.4.0
 - Python==3.7

How to solve the bug? Thank you in advance.

**Comment by ShirleyHe2020** [comment]
> `
> 
> ```
> python train.py --data data/voc.yaml --cfg models/yolov5s.yaml --batch-size 64 --resume
> Apex recommended for faster mixed precision training: https://github.com/NVIDIA/apex
> {'lr0': 0.01, 'momentum': 0.937, 'weight_decay': 0.0005, 'giou': 0.05, 'cls': 0.58, 'cls_pw': 1.0, 'obj': 1.0, 'obj_pw': 1.0, 'iou_t': 0.2, 
> 'anchor_t': 4.0, 'fl_gamma': 0.0, 'hsv_h': 0.014, 'hsv_s': 0.68, 'hsv_v': 0.36, 'degrees': 0.0, 'translate': 0.0, 'scale': 0.5, 'shear': 0.0}
> Namespace(adam=False, batch_size=64, bucket='', cache_images=False, cfg='models/yolov5s.yaml', data='data/voc.yaml', 
> device='', epochs=300, evolve=False, img_size=[640, 640], multi_scale=False, name='', noautoanchor=False, nosave=False, 
> notest=False, rect=False, resume=True, single_cls=False, weights='weights/last.pt')
> Using CUDA device0 _CudaDeviceProperties(name='TITAN Xp COLLECTORS EDITION', total_memory=12195MB)
>        device1 _CudaDeviceProperties(name='TITAN Xp COLLECTORS EDITION', total_memory=12196MB)
> 
> Start Tensorboard with "tensorboard --logdir=runs", view at http://localhost:6006/
> 
>           from  n    params  module                                  arguments                     
>   0             -1  1      3520  models.common.Focus                     [3, 32, 3]                    
>   1             -1  1     18560  models.common.Conv                      [32, 64, 3, 2]                
>   2             -1  1     19904  models.common.BottleneckCSP             [64, 64, 1]                   
>   3             -1  1     73984  models.common.Conv                      [64, 128, 3, 2]               
>   4             -1  1    161152  models.common.BottleneckCSP             [128, 128, 3]                 
>   5             -1  1    295424  models.common.Conv                      [128, 256, 3, 2]              
>   6             -1  1    641792  models.common.BottleneckCSP             [256, 256, 3]                 
>   7             -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]              
>   8             -1  1    656896  models.common.SPP                       [512, 512, [5, 9, 13]]        
>   9             -1  1   1248768  models.common.BottleneckCSP             [512, 512, 1, False]          
>  10             -1  1    131584  models.common.Conv                      [512, 256, 1, 1]              
>  11             -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
>  12        [-1, 6]  1         0  models.common.Concat                    [1]                           
>  13             -1  1    378624  models.common.BottleneckCSP             [512, 256, 1, False]          
>  14             -1  1     33024  models.common.Conv                      [256, 128, 1, 1]              
>  15             -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
>  16        [-1, 4]  1         0  models.common.Concat                    [1]                           
>  17             -1  1     95104  models.common.BottleneckCSP             [256, 128, 1, False]          
>  18             -1  1      9675  torch.nn.modules.conv.Conv2d            [128, 75, 1, 1]               
>  19             -2  1    147712  models.common.Conv                      [128, 128, 3, 2]              
>  20       [-1, 14]  1         0  models.common.Concat                    [1]                           
>  21             -1  1    313088  models.common.BottleneckCSP             [256, 256, 1, False]          
>  22             -1  1     19275  torch.nn.modules.conv.Conv2d            [256, 75, 1, 1]               
>  23             -2  1    590336  models.common.Conv                      [256, 256, 3, 2]              
>  24       [-1, 10]  1         0  models.common.Concat                    [1]                           
>  25             -1  1   1248768  models.common.BottleneckCSP             [512, 512, 1, False]          
>  26             -1  1     38475  torch.nn.modules.conv.Conv2d            [512, 75, 1, 1]               
>  27   [-1, 22, 18]  1         0  models.yolo.Detect                      [20, [[116, 90, 156, 198, 373, 326], [30, 61, 62, 45, 59, 119], [10, 13, 16, 30, 33, 23]]]
> Model Summary: 191 layers, 7.30634e+06 parameters, 7.30634e+06 gradients
> 
> Optimizer groups: 62 .bias, 70 conv.weight, 59 other
> Caching labels /home/ss/data/VOCdevkit/VOC2007/labels.npy (16551 found, 0 missing, 0 empty, 0 duplicate, for 16551 i
> Saving labels to /home/ss/data/VOCdevkit/VOC2007/labels.npy for faster future loading
> Caching labels /home/ss/data/VOCdevkit/VOC2007/labels.npy (4952 found, 0 missing, 0 empty, 0 duplicate, for 4952 ima
> Saving labels to /home/ss/data/VOCdevkit/VOC2007/labels.npy for faster future loading
> 
> Analyzing anchors... Best Possible Recall (BPR) = 0.9998
> Image sizes 640 train, 640 test
> Using 8 dataloader workers
> Starting training for 300 epochs...
> 
>  Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
>   0%|                                                                                       | 0/259 [00:00<?, ?it/s]ERROR: Unexpected segmentation fault 
>   encountered in worker.
>   0%|                                                                                       | 0/259 [00:02<?, ?it/s]
> Traceback (most recent call last):
>   File "train.py", line 387, in <module>
>     train(hyp)
>   File "train.py", line 241, in train
>     pred = model(imgs)
>   File "/home/ss/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
> result = self.forward(*input, **kwargs)
>   File "/home/ss/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 449, in forward
> outputs = self.parallel_apply(self._module_copies[:len(inputs)], inputs, kwargs)
>   File "/home/ss/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 474, in parallel_apply
> return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
>   File "/home/ss/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 77, in parallel_apply
> thread.join()
>   File "/home/ss/anaconda3/envs/yolov5/lib/python3.7/threading.py", line 1032, in join
> self._wait_for_tstate_lock()
>   File "/home/ss/anaconda3/envs/yolov5/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
> elif lock.acquire(block, timeout):
>   File "/home/ss/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
> _error_if_any_worker_fails()
> RuntimeError: DataLoader worker (pid 12367) is killed by signal: Segmentation fault. `
> ```
> 
> ## Environment
> * OS: [Ubuntu16.04]
> * GPU [2*Titan-Xp]
> * Pytorch==1.4.0
> * Python==3.7
> 
> How to solve the bug? Thank you in advance.

Did you solve it ?  I encountered same error messages: at Epoch 179/299 : 
     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
   178/299     5.54G   0.02711  0.008768         0   0.03587         9       640: 100%|██████████| 836/836 [04:44<00:00,  2.94it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 74/74 [00:27<00:00,  2.69it/s]
                 all    2.36e+03    2.81e+03      0.0533      0.0594      0.0554      0.0421

     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
   179/299     5.54G   0.02733  0.008876         0   0.03621         7       640: 100%|██████████| 836/836 [04:44<00:00,  2.93it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95:  26%|██▌       | 19/74 [00:07<00:21,  2.59it/s]ERROR: Unexpected segment          ation fault encountered in worker.
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95:  26%|██▌       | 19/74 [00:07<00:21,  2.59it/s]
Traceback (most recent call last):
  File "train.py", line 527, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 344, in train
    results, maps, times = test(opt.data,
  File "/home/qian/anaconda3/envs/ultra_YOLOv5/flexible-yolov5-main/eval.py", line 110, in test
    t0 += time_synchronized() - t
  File "/home/qian/anaconda3/envs/ultra_YOLOv5/flexible-yolov5-main/utils/torch_utils.py", line 83, in time_synchronized
    torch.cuda.synchronize()
  File "/home/qian/anaconda3/lib/python3.8/site-packages/torch/cuda/__init__.py", line 380, in synchronize
    return torch._C._cuda_synchronize()
  File "/home/qian/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 16352) is killed by signal: Segmentation fault.

**Comment by glenn-jocher** [comment]
@ShirleyHe2020 your code is extremely out of date. Before you do anything you should update to the latest code with git pull or git clone.
