### ISSUE TITLE
yolo data process

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#2171]
## ❔Question

For data of training process,
If I have image size 100x160(h x w) and the yolo want to design a 640 x 640 network.
How to deal with the images is better?

1. dirctly resize the image size 100x160 to 640x640
2. resize the image size 100x160 to 640x640 with padding 0

**Comment by glenn-jocher** [comment]
@alicera train at --img 160 if you want. There's no need to modify your images.

**Comment by alicera** [comment]
which is  your process？ 
1. dirctly resize 
2. resize with padding 0

**Comment by glenn-jocher** [comment]
@alicera you don't need to resize any images, you simply pass the image size you want the model trained at and let the training code handle all other concerns (like padding).

**Comment by alicera** [comment]
I know  your design is very good and let the user dont care the images process.
Thanks you.

Your Mosaic process is compose of 4 images and resize it to 640x640.
which method do you use 
![image](https://user-images.githubusercontent.com/59388989/107499002-644b7080-6bcf-11eb-8081-9d85c3daeec7.png)

**Comment by glenn-jocher** [comment]
@alicera method 2 is used, the images are cropped and the aspect ratio is maintained.
