### ISSUE TITLE
How to remove overlapping box from another class ?

### ISSUE THREAD

**Issue by davodogster** [ultralytics/yolov5#2172]
## ❔Question
How to remove overlapping box from another class ?

## Additional context

Is there a way (preferably easy way) to remove the overlapping box with the lowest prediction score when two boxes from different classes overlap?
I understand that iou-thres won't fix it.

Here is an example (green and brown boxes from different classes)
![image](https://user-images.githubusercontent.com/46079516/107450128-934eeb80-6ba9-11eb-96ba-375069b652f1.png)

Cheers, Sam

**Comment by glenn-jocher** [comment]
@davodogster agnostic NMS aggregates all classes together during NMS:
`python detect.py --agnostic`

https://github.com/ultralytics/yolov5/blob/ace3e02e406307ed0cebc25aebe15835767107b2/detect.py#L159

**Comment by davodogster** [comment]
Thanks so much @glenn-jocher ! It works perfectly

**Comment by Ankit-Vohra** [comment]
Is there any way I can choose between the class which to remove if there's overlapping between multiple classes @glenn-jocher

**Comment by glenn-jocher** [comment]
@Ankit-Vohra modify your inference parameters as you see fit for your custom task, i.e. iou threshold, confidence threshold etc.

**Comment by goshua13** [comment]
@glenn-jocher  is there anyway to do this agnostic_nms=False flag but with the same class? 
I have an image where I don't want the classes to overlap. because a roof will never overlap another, I basically want to tell the model to always just get everything thats overlapping as one. 
not sure if this means I need to adjust other things? 
What is the best approach for this? Thanks in advance!
![image](https://github.com/ultralytics/yolov5/assets/20075458/b7761462-62f0-4a7f-afd1-92be1a2d8742)

**Comment by glenn-jocher** [comment]
@goshua13 to prevent overlapping detections of the same class, you can adjust the `iou-thres` parameter during inference. This controls the Intersection Over Union (IOU) threshold for non-maximum suppression (NMS). By increasing this threshold, you can reduce the chances of having overlapping boxes for the same class.

If you find that roofs are still being detected as multiple overlapping boxes, you might need to consider retraining your model with more representative data of roofs, ensuring that the ground truth bounding boxes in your training dataset do not overlap. This way, the model learns that roofs are distinct, non-overlapping objects.

Remember, fine-tuning these parameters requires a balance between reducing overlaps and not missing out on valid detections. It's often a process of trial and error to find the optimal settings for your specific use case.
