### ISSUE TITLE
Is info about coordinates in Train Custom Data correct?

### ISSUE THREAD

**Issue by a-esp-1** [ultralytics/yolov5#2178]
## ❔Question

I have been looking https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data and I notice that here
![image](https://user-images.githubusercontent.com/73425046/107559401-56501c80-6bdc-11eb-8a0f-f5523100c166.png)

should be width - 1 and height - 1, because top left corner starts in (0,0) and bottom right in (1,1), so for being more precise we should use x_center/(w-1) and y_center/(h-1)

**Comment by glenn-jocher** [comment]
@a-esp-1 normalization instructions are correct, and don't depend on origin. 

Both xyxy and xywh labels can be normalized by diving x and w by image width and y and h by image height.
