### ISSUE TITLE
如何在程序中修改代码，让他只检查某一个类别，比如人类，汽车，狗等？在哪里添加呢？命令python detect.py --classes 0 不是很方便，谢谢您

### ISSUE THREAD

**Issue by Tiang-88** [ultralytics/yolov5#218]

**Comment by WangLibo1995** [comment]
@zzb1967736495 
![image](https://user-images.githubusercontent.com/38718224/85944220-a63ce480-b967-11ea-9fa0-613c10be7908.png)
![image](https://user-images.githubusercontent.com/38718224/85944257-ffa51380-b967-11ea-837d-3c3d9b18888b.png)
![image](https://user-images.githubusercontent.com/38718224/85944300-4dba1700-b968-11ea-8247-b296e388cc6f.png)

**Comment by Tiang-88** [comment]
> @ zzb1967736495
> ![图片](https://user-images.githubusercontent.com/38718224/85944220-a63ce480-b967-11ea-9fa0-613c10be7908.png)
> ![图片](https://user-images.githubusercontent.com/38718224/85944257-ffa51380-b967-11ea-837d-3c3d9b18888b.png)
> ![图片](https://user-images.githubusercontent.com/38718224/85944300-4dba1700-b968-11ea-8247-b296e388cc6f.png)

最后2个图没看懂，文件夹的位置是？还有在哪里添加呢，添加到哪里去

**Comment by WangLibo1995** [comment]
@zzb1967736495 我一开始理解错了，我以为你要训练呢。只检测一个类别只要改  --classes [类别序号] 就可以了
![image](https://user-images.githubusercontent.com/38718224/85946480-40585900-b977-11ea-952f-110b70a31e14.png)
![image](https://user-images.githubusercontent.com/38718224/85946520-75fd4200-b977-11ea-9661-29b58ae3ffb4.png)
![image](https://user-images.githubusercontent.com/38718224/85946560-b78ded00-b977-11ea-9226-9728f0ff492b.png)

**Comment by Tiang-88** [comment]
> @检测到类别[类别序号]就可以了- @ zzb1967736495我一开始理解错了，我以为你要训练呢。
> ![图片](https://user-images.githubusercontent.com/38718224/85946480-40585900-b977-11ea-952f-110b70a31e14.png)
> ![图片](https://user-images.githubusercontent.com/38718224/85946520-75fd4200-b977-11ea-9661-29b58ae3ffb4.png)
> ![图片](https://user-images.githubusercontent.com/38718224/85946560-b78ded00-b977-11ea-9226-9728f0ff492b.png)
您好，这个在代码里面那块呢？parser.add_argument('--classes', nargs='+', type=int, help='filter by class')我的这里这样的，是不是在这里面改，我并没有您截图中的文件

**Comment by Tiang-88** [comment]
![image](https://user-images.githubusercontent.com/51110833/86071679-764e2800-bab2-11ea-974e-3d48ba374f0f.png)
我的是这样的，

**Comment by hktxt** [comment]
> @zzb1967736495
> ![image](https://user-images.githubusercontent.com/38718224/85944220-a63ce480-b967-11ea-9fa0-613c10be7908.png)
> ![image](https://user-images.githubusercontent.com/38718224/85944257-ffa51380-b967-11ea-837d-3c3d9b18888b.png)
> ![image](https://user-images.githubusercontent.com/38718224/85944300-4dba1700-b968-11ea-8247-b296e388cc6f.png)

Oh，GWD....
