### ISSUE TITLE
How to interpret plots

### ISSUE THREAD

**Issue by joyjeni** [ultralytics/yolov5#2180]
## How to interpret Yolo v5 plots
After training for 300 epochs those are my plots

![Imgur](https://i.imgur.com/qIciCwD.png)

Can some one help me to understand these metrics. Whats my classification accuracy? Is it 2%.

**Comment by joyjeni** [comment]
Plots are bit confusing. Its not explained in tutorial aswell. Could someone help me to interpret the results. If same data is used to test the pipeline in train and test then accuracy should increase. But plot shows classification accuracy is 2 %

**Comment by glenn-jocher** [comment]
@joyjeni first 3 columns are the 3 YOLO loss components, train top row and val bottom row.

Object detection has no accuracy metric.

**Comment by joyjeni** [comment]
Got it. This tutorial explains well about metrics. My recall is close 1 ie 0.9755. Model is performing good.
https://towardsdatascience.com/on-object-detection-metrics-with-worked-example-216f173ed31e

@glenn-jocher Thankyou for great tutorial on YOLO V5.

**Comment by mabubakarsaleem** [comment]
@glenn-jocher Sir can we plot a graph of epoch vs accuracy for every epoch during training?
