### ISSUE TITLE
yolov5x train.py error

### ISSUE THREAD

**Issue by paragjp** [ultralytics/yolov5#2181]
Hi 

I am trying to run yolov5x module on google colab on GPU, I have successfully imported following 

!pip install torch
!!pip install PyYAML
!!pip install git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI

from pathlib import Path
from tqdm import tqdm
import numpy as np
import json
import urllib
import PIL.Image as Image
import cv2
import torch
import torchvision
from IPython.display import display
from sklearn.model_selection import train_test_split
import seaborn as sns
from pylab import rcParams
import matplotlib.pyplot as plt
from matplotlib import rc
%matplotlib inline
%config InlineBackend.figure_format='retina'

When I am running following command 
**!python train.py --img 640 --batch 4 --epochs 30 \
  --data ./data/clothing.yaml --cfg ./models/yolov5x.yaml --weights yolov5x.pt \
  --name yolov5x_clothing --cache**

It is giving me following error

Traceback (most recent call last):
  File "train.py", line 404, in <module>
    train(hyp)
  File "train.py", line 70, in train
    **data_dict = yaml.load(f, Loader=yaml.FullLoader)  # model dict
AttributeError: module 'yaml' has no attribute 'FullLoader'**

Pl help

**Comment by paragjp** [comment]
Hi

Pl find enclosed screen shot of an error
![image_2021-02-11_110647](https://user-images.githubusercontent.com/41343271/107605464-3b6fbd80-6c59-11eb-9024-8aff0ce34518.png)

I am using Kaggle clothing dataset. 

Thanks

**Comment by glenn-jocher** [comment]
@paragjp your pyyaml is not meeting requirements in requirements.txt.

## Requirements

**Python 3.8** or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including **`torch>=1.7`**. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by paragjp** [comment]
@glenn-jocher 

Thanks after installing PyYAML to 5.3.1 this issue has been resolved now I am facing following issue

Traceback (most recent call last):
  File "train.py", line 404, in <module>
    train(hyp)
  File "train.py", line 122, in train
    raise KeyError(s) from e
KeyError: "yolov5x.pt is not compatible with /content/yolov5/models/yolov5x.yaml. Specify --weights '' or specify a --cfg compatible with yolov5x.pt.

My command is

**!python /content/yolov5/train.py --img 640 --batch 4 --epochs 30 \
  --data /content/yolov5/data/clothing.yaml --cfg /content/yolov5/models/yolov5x.yaml \
  --weights yolov5x.pt \
  --name yolov5_clothing --cache**


Pl help, Thanks

**Comment by paragjp** [comment]
Hi 

Any updates ?

Thanks

**Comment by NanoCode012** [comment]
@paragjp, I think it's a mismatch in code and model weights. You should pull the latest code and delete weights, so they can be auto-downloaded again.

**Comment by paragjp** [comment]
@NanoCode012 

Thanks it is working now
