### ISSUE TITLE
Can we return objectness score and class score?

### ISSUE THREAD

**Issue by abfleishman** [ultralytics/yolov5#2186]
## ❔Question
I am wondering if it is possible to return confidence scores for objectness and classification separately for each predicted box during inference? I might be conceptually off base here, but I am interested in understanding if the model is unsure if the box itself is correct or if the class it is assigning to the box is correct.  My understanding is the `conf` that is returned now is a combo of the two?

**Comment by glenn-jocher** [comment]
@abfleishman yes we display total confidence, i.e. the product of obj and cls. You can modify detect.py here to print custom outputs:
https://github.com/ultralytics/yolov5/blob/404749a33cc29d119f54b2ce35bf3b33a847a487/detect.py#L103-L114

**Comment by glenn-jocher** [comment]
@abfleishman you may need to also modify the NMS function accordingly to output the data you want here:
https://github.com/ultralytics/yolov5/blob/404749a33cc29d119f54b2ce35bf3b33a847a487/utils/general.py#L340-L346

**Comment by abfleishman** [comment]
Thanks @glenn-jocher for your rapid reply!  I just looked at the section you pointed me toward and I think I need one more nudge. 

In `detect.py` the object `det` has already been reduced to the `box (x,y,x,y)`, `conf`, and predicted `class`.  I am specifically wondering if there is a numeric "confidence score" for the "objectness" and a second numeric score for the "classification" and where I would edit the code to propagate those values forward so that they are present in the `det` object?  Current;y, the `det` object only has the `conf` which I am assuming is the combination of the two scores I am interested in.

**Comment by glenn-jocher** [comment]
@abfleishman yes these are input into NMS separately and merged there:
https://github.com/ultralytics/yolov5/blob/404749a33cc29d119f54b2ce35bf3b33a847a487/utils/general.py#L379-L381

**Comment by karsil** [comment]
I stumbled across the same problem. I think I solved it. For anyone of interest who found this thread (as I did):

```python
        # Compute conf
        x[:, 5:] *= x[:, 4:5]  # conf = obj_conf * cls_conf

        # Box/Mask
        box = xywh2xyxy(x[:, :4])  # center_x, center_y, width, height) to (x1, y1, x2, y2)
        mask = x[:, mi:]  # zero columns if no masks

        # EDIT
        x_copy = torch.clone(x)

       ... # other code

        # instead of
        # output[xi] = x[i]
        # Use:
        # new tensor: x_center, y_center, w, h, obj, classes
        output[xi] = torch.cat((x[i, :4], x_copy[i, 4:]), 1)
```

If you have a modified `detect.py`, you can extract the values like in the following:
```python
                    # Save Results
                    for x_center, y_center, w, h, obj, *class_probs in reversed(det):
                        xywh = (xyxy2xywh(torch.tensor([x_center, y_center, w, h]).view(1, 4)) / gn).view(-1).tolist()  # normalized xywh
                        obj = obj.item()
                        classes_probs_list = (c.item() / obj for c in class_probs) # as class_probs contains the merged confidences 
```

**Comment by glenn-jocher** [comment]
Nice work @karsil! Thank you for sharing your solution with the community. This will be helpful for others looking to extract separate objectness and classification scores. Keep up the great work!
