### ISSUE TITLE
Where I can see my yolo model ?

### ISSUE THREAD

**Issue by paragjp** [ultralytics/yolov5#2189]
Where I can see my yolo model ?

I run following command successfully 

!python train.py --img 640 --batch 4 --epochs 50 \
  --data clothing.yaml --cfg yolov5x.yaml \
  --weights yolov5x.pt \
  --name **yolov5_clothing** --cache

I have given my model name yolov5_clothing but could not able to see my model in any directory can you pl help ?

Thanks

**Comment by glenn-jocher** [comment]
Results are saved to `runs/train/yolov5_clothing` then in your case.

**Comment by paragjp** [comment]
Thanks, how can I see my saved model in netron ( model visualizing site ) ? Pl suggest

**Comment by glenn-jocher** [comment]
Drag and drop any model into Netron to visualize.

**Comment by paragjp** [comment]
@glenn-jocher 

Thanks but which file I have to download from model yolov5_clothing Can you guide me ?

![Capture](https://user-images.githubusercontent.com/41343271/107740963-434f6080-6d32-11eb-8b98-b1ee37f80753.JPG)

**Comment by paragjp** [comment]
Hi 

Any updates which file to be download and uploaded in Netron ?

Thanks

**Comment by aditya-dl** [comment]
Hi @paragjp, there will be a `weights` folder which will have your trained model weights as `best.pt` and `last.pt`.

**Comment by rickymedrano** [comment]
> Hi
> 
> Any updates which file to be download and uploaded in Netron ?
> 
> Thanks

Use 
`python models/export.py --weights yolov5s.pt --img 640 --batch 1` which will output an .onnx file. You can then upload that to https://netron.app/
