### ISSUE TITLE
Will you add more backbone support ?

### ISSUE THREAD

**Issue by lxyyang** [ultralytics/yolov5#219]
Will you add more backbone support ? such as CSPMobileNet-v2?

**Comment by glenn-jocher** [comment]
@lxyyang it would be great to add more backbones yes. At the moment we are very busy simply verifying and validating the basic functionality of the repo (train, test, inference), and adding a few features from our internal TODO list. 

We can leave this open for suggestions though, and of course if you would like to submit PRs yourself that would be great also!
