### ISSUE TITLE
Change the metric to mAP0.4

### ISSUE THREAD

**Issue by DatDoc** [ultralytics/yolov5#2195]
## ❔Question

Hi @glenn-jocher, how can I change the metric from mAP0.5 to mAP0.4? Thank you for your amazing work btw

**Comment by glenn-jocher** [comment]
@DatDoc well, the IoU vector that's used right now spans form 0.5 to 0.95 in steps of 0.05. You can modify this here:
https://github.com/ultralytics/yolov5/blob/17ac94b7968703e708bfeb7274de755c4b2f1f43/test.py#L73

You might be able to simply start it from 0.4, I'm not sure if there are any hard coded tensor dimensions that might break, but hopefully it's robust.

EDIT: nevermind, 10 steps are manually specified so no chance of anything breaking.
