### ISSUE TITLE
Starting training from a pre-trained checkpoint

### ISSUE THREAD

**Issue by zabir-nabil** [ultralytics/yolov5#220]
Currently, I'm using `python train.py --img 1024 --batch 2 --epochs 40 --data data.yaml --cfg yolov5x.yaml --name yolov5x` to train my model, but I assume it's training the model from randomized weight.

How can I use pre-trained weights? (I only found the resume argument helpful but not sure how to use this with the proper weights)

**Comment by glenn-jocher** [comment]
@zabir-nabil the notebook explains all of this.
