### ISSUE TITLE
How to train YOLOV5 in colab TPU

### ISSUE THREAD

**Issue by joyjeni** [ultralytics/yolov5#2200]
## How to train Yolo v5 using Colab TPU

I would like to train enire COCO dataset from scratch for academic research work. How to train using Colab TPU. Is there way in Colab to increase number of TPU in colab. What else will be better option to train COCO dataset in short time.

**Comment by glenn-jocher** [comment]
@joyjeni it's possible to train COCO on Colab, but you'll need to sign up for the Colab Pro plan for $10 per month. The default Colab does not have sufficient hard drive space to download and unzip the full COCO dataset (20 GB), and only comes with 2 CPUs, restricting you to only 2 dataloader workers, which will be slow.

The fastest way to train COCO is to use a GCP or AWS VM with a V100 or A100 GPU. You can also rent a 3090 GPU on consumer cloud platforms like vast.ai.

**Comment by glenn-jocher** [comment]
BTW here are quickstart guides for the environments I mentioned:

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/GCP-Quickstart)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/AWS-Quickstart)
- **Docker Image**. See [Docker Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/Docker-Quickstart) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.
