### ISSUE TITLE
Where is the "resnet101.pt"? I only have the "resnet101.pth" 

### ISSUE THREAD

**Issue by minuet-red** [ultralytics/yolov5#2202]
## ❔Question
Where is the "resnet101.pt"?
## Additional context
![image](https://user-images.githubusercontent.com/78399534/107849736-446ab580-6e38-11eb-8117-c9f60e6204ad.png)

**Comment by glenn-jocher** [comment]
@minuet-red this is a bring-your-own-model situation. Some users like the option of having a second stage filter first stage detections to reduce FPs before passing results. If you have a classifier (any classifier works, resnet101 is simply there as a placeholder) trained on the same classes, then you can specify it there.

There are also a number of other issues on the same topic, please search existing issues for more details:
https://github.com/ultralytics/yolov5/issues?q=is%3Aissue+resnet101
