### ISSUE TITLE
I am a researcher of Tencent. The following code conflicts with the latest version of Python. I hope you can give me a solution. Thank you very much

### ISSUE THREAD

**Issue by xianglei3** [ultralytics/yolov5#2204]
the error is : 
torch.nn.modules.module.ModuleAttributeError: 'Model' object has no attribute 'yaml'

the code is 
    if pretrained:
        with torch_distributed_zero_first(rank):
            attempt_download(weights)  # download if not found locally
        ckpt = torch.load(weights, map_location=device)  # load checkpoint
        if hyp.get('anchors'):
            ckpt['model'].yaml['anchors'] = round(hyp['anchors'])  # force autoanchor

**Comment by glenn-jocher** [comment]
@xianglei3 see https://github.com/ultralytics/yolov5/issues/2203 for a reply to your original question and lets continue the conversion there. Closing this issue as duplicate.
