### ISSUE TITLE
I'm a researcher of Tencent. When I use the latest version of win10, the following errors must appear. I sincerely hope that the reason is not correct

### ISSUE THREAD

**Issue by xianglei3** [ultralytics/yolov5#2205]
the error is :
Model' object has no attribute 'yaml'

The relevant code is
    if pretrained:
        with torch_distributed_zero_first(rank):
            attempt_download(weights)  # download if not found locally
        ckpt = torch.load(weights, map_location=device)  # load checkpoint
        if hyp.get('anchors'):
            ckpt['model'].yaml['anchors'] = round(hyp['anchors'])  # force autoanchor

**Comment by glenn-jocher** [comment]
@xianglei3 see #2203 for a reply to your original question and lets continue the conversion there. Closing this issue as duplicate.

In regards to your windows question, YOLOv5 is tested every 24 hours on all the main operating systems including windows. See status message below.

## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.
