### ISSUE TITLE
I'm a researcher of Tencent. I'm very confused about using the latest Python to train yolov5 on win10. I always report the following error

### ISSUE THREAD

**Issue by xianglei3** [ultralytics/yolov5#2206]
the error is
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'Model' object has no attribute 'yaml'

The relevant code is：
    if pretrained:
        with torch_distributed_zero_first(rank):
            attempt_download(weights)  # download if not found locally
        ckpt = torch.load(weights, map_location=device)  # load checkpoint
        if hyp.get('anchors'):
            ckpt['model'].yaml['anchors'] = round(hyp['anchors'])  # force autoanchor

**Comment by glenn-jocher** [comment]
@xianglei3 see #2203 for a reply to your original question and lets continue the conversion there. Closing this issue as duplicate.
