### ISSUE TITLE
I'm a researcher of Tencent. I want to know what the exp folder under the runs folder means. Why did I save the exp to the 29th after 15 iterations

### ISSUE THREAD

**Issue by xianglei3** [ultralytics/yolov5#2209]
I'm a researcher of Tencent. I want to know what the exp folder under the runs folder means. Why did I save the exp to the 29th after 15 iterations

**Comment by glenn-jocher** [comment]
@xianglei3 exp stands for 'experiment'. All outputs from YOLOv5 are logged to runs/train/exp* directory, or the project/name directory if you specify `--project` and `--name` when testing, training or detecting.

```
/runs
  /train
    /exp
    /exp2
    /exp3
  /test
    /exp
  /detect
    /exp
    ...
```
