### ISSUE TITLE
the order of gj and gi

### ISSUE THREAD

**Issue by pangkun248** [ultralytics/yolov5#2211]
In the build_target function, gj is clearly the coordinate in the y direction, but it is in the third dimension and gi is in the fourth dimension. I think that when reading the picture, it is also read in image.open width and height. Then the final feature map should also be in BCWH format. In this case, shouldn't gj represent the information of the fourth dimension and gi represent the information of the third dimension? Did I overlook something?

**Comment by glenn-jocher** [comment]
@pangkun248 this is just naming conventions. i and j, or y and x, typically refer to row and column.

**Comment by glenn-jocher** [comment]
@pangkun248 BTW sorry to answer your question the current implementation is correct. You can test this by running test.py (auto rectangular inference) after swapping indices (the code should break).

**Comment by pangkun248** [comment]
I see, thank you
