### ISSUE TITLE
COCO test-dev

### ISSUE THREAD

**Issue by Darcy-hash** [ultralytics/yolov5#2212]
I tried https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

But COCO test-dev's labels don't seem to have been downloaded

Where can I download COCO test-dev's labels file

Thanks a lot!!

**Comment by glenn-jocher** [comment]
@Darcy-hash you can download COCO test-dev images using the Colab or Kaggle notebooks (https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb#scrollTo=V0AJnSeCIHyJ&line=3&uniqifier=1).

There are no COCO test-dev labels publicly available. This is the entire point of the test-dev set. You can submit predictions to the server for evaluation instead.
