### ISSUE TITLE
Are TTA augument boxes one pixel shifted in de-flip ud and lr?

### ISSUE THREAD

**Issue by VdLMV** [ultralytics/yolov5#2213]
Thx for sharing your code.
Shouldn’t the lines 113 and 115 in Model.forward be:
                    yi[..., 1] = img_size[0]-1 - yi[..., 1]  # de-flip ud
                    yi[..., 0] = img_size[1]-1 - yi[..., 0]  # de-flip lr

**Comment by glenn-jocher** [comment]
> Thx for sharing your code.
> Shouldn’t the lines 113 and 115 in Model.forward be:
> yi[..., 1] = img_size[0]-1 - yi[..., 1] # de-flip ud
> yi[..., 0] = img_size[1]-1 - yi[..., 0] # de-flip lr

@VdLMV yes, I think you are right, as the points in the image span 0 to (img_size-1). You discovered bug, nice work! Can you submit a PR with your fix above? Thanks!!

**Comment by VdLMV** [comment]
You're welcome, PR submitted.
