### ISSUE TITLE
How to prevent writing data to coco128 folder

### ISSUE THREAD

**Issue by sezer-muhammed** [ultralytics/yolov5#2214]
## ❔Question
I'm trying to train my model on kaggle
i upload my dataset to kaggle's input folder and in this folder writing is not permitted
to prevent that i trained my model on my pc and create cache files then I upload my data to kaggle and tried again.
but it gave an error again.

How can I prevent writing any data from data folder?

**Comment by glenn-jocher** [comment]
@sezer-muhammed you may want to simply copy the dataset to a local directory with write permissions, i.e. `yolov5/coco128`, and then update your data.yaml to point to the new location.

**Comment by sezer-muhammed** [comment]
> @sezer-muhammed you may want to simply copy the dataset to a local directory with write permissions, i.e. `yolov5/coco128`, and then update your data.yaml to point to the new location.

for now, I'm doing this. But kaggle gives 20GB for writable area. my dataset will be 30 - 40 GB. So, after a point i cannot do this

**Comment by glenn-jocher** [comment]
@sezer-muhammed cache files are only written once. If you supply a cached dataset, then there's no write requirements for the dataset.

**Comment by sezer-muhammed** [comment]
> @sezer-muhammed cache files are only written once. If you supply a cached dataset, then there's no write requirements for the dataset.

I tried. maybe i did it wrong, ill try it again. if I cannot manage can i write again?

**Comment by glenn-jocher** [comment]
@sezer-muhammed sure, you can recache as much as you want. Caching will automatically redo itself if your dataset is modified, or if the cache file is deleted.
