### ISSUE TITLE
About onnx export

### ISSUE THREAD

**Issue by leeyunhome** [ultralytics/yolov5#2215]
## ❔Question

Hello,

![image](https://user-images.githubusercontent.com/59910227/107892531-1638c300-6f69-11eb-8ef5-d1ed46405c8c.png)

By changing the parameters of the torch.onnx.export function, I got classes and boxes as follows.

Why can the dimensions of classes and boxes explain this?

And when inferring by loading this onnx in tensorRT, can we ignore feature maps like 660 and 969? Or do I have to handle it separately?

Thank you.

**Comment by glenn-jocher** [comment]
@leeyunhome the output layers are incorrectly named here unfortunately. In your model the first output is a combined output of all 3 layers, the last 3 outputs are the individual output grids P3, P4, P5, for small, medium and large objects.

**Comment by leeyunhome** [comment]
> @leeyunhome the output layers are incorrectly named here unfortunately. In your model the first output is a combined output of all 3 layers, the last 3 outputs are the individual output grids P3, P4, P5, for small, medium and large objects.

Hello,

Is it normal except for the model name?

The following struct has OUTPUT_BLOB_NAME and OUTPUT_BBOX_NAME separated, so I tried to split the output into two.

How do I put my model in a structure like this one?
![image](https://user-images.githubusercontent.com/59910227/108435139-324fa380-728c-11eb-915e-55517fdc3b9b.png)

Thank you.

**Comment by glenn-jocher** [comment]
@leeyunhome I'm sorry I'm not sure what that is.
