### ISSUE TITLE
Exporting says invalid syntax

### ISSUE THREAD

**Issue by Prateek-Vortex** [ultralytics/yolov5#2217]
## Where am i wrong?

`export 
PYTHONPATH="$PWD" && python .content/yolov5/models/export.py 
--weights .runs/train/yolov5s_results/weights/best.pt 
--img 640 --batch 1`

**Comment by glenn-jocher** [comment]
I don't see any issues with export. 

<img width="1262" alt="Screen Shot 2021-02-15 at 1 29 19 PM" src="https://user-images.githubusercontent.com/26833433/107995655-8ceab600-6f93-11eb-962c-b7140490e6c0.png">
