### ISSUE TITLE
interruption during evolve

### ISSUE THREAD

**Issue by lrbrrr** [ultralytics/yolov5#2218]
Something wrong with yolov5 leaking semaphores?

Can we get a fix for this soon?
![Screenshot from 2021-02-15 12-41-00](https://user-images.githubusercontent.com/78729788/107916589-8ad12900-6f8c-11eb-9643-630bdc44034e.png)

**Comment by glenn-jocher** [comment]
@lrbrrr thanks for the bug report. If this is reproducible can you supply commands or a notebook to reproduce? There has been a long running issue with memory leakage when evolving under certain circumstances, though we have not been able to identify the source.

@AyushExel do you know what a leaked semaphore is? Do you think this an indicator of a problem in the underlying code?

**Comment by AyushExel** [comment]
@glenn-jocher not that I'm aware of.  But I haven't run extensive tests using evolve. A reproducible code would be helpful for engineers @lrbrrr .

**Comment by lrbrrr** [comment]
Well, I have been trying with custom dataset with `--evolve` . I cannot see this error each time but it has happened twice so far during evolve. I would like to share another screenshot from the past. 
![Screenshot from 2021-02-05 09-55-38](https://user-images.githubusercontent.com/78729788/108021433-92540900-7044-11eb-8926-3a565856c660.png)

**Comment by lrbrrr** [comment]
https://github.com/pytorch/pytorch/issues/23117

anything related to this?

**Comment by glenn-jocher** [comment]
@lrbrrr it may be related. The issue I'm thinking of causes CUDA memory to increase over generations during evolution, which may crash evolution after enough generations. I've not seen it recently though, and have successfully run 300 generations of COCO128 evolution recently in the same Colab instance over 24 hours without error (also logged to W&B). I'm not sure if the two are related but it's possible. This particular sempahore message I've not seen though.
