### ISSUE TITLE
Tried detect.py locally using webcam but nothing pops-up

### ISSUE THREAD

**Issue by abuelgasimsaadeldin** [ultralytics/yolov5#2220]
## ❔Question
When running detect.py with source set as 0 locally on my laptop I get everything success and my laptop camera flash even turns on but nothing pops-up. Very weird, I have even left it for awhile but still nothing is shown and no errors are displayed. Any ideas?

P.S detect.py on images and videos all work well.

![1613381258421](https://user-images.githubusercontent.com/68045710/107928490-5886f200-6fb3-11eb-9429-716c9b0b11a7.jpg)

**Comment by abuelgasimsaadeldin** [comment]
Fixed - Apparently after re-booting the laptop it managed to work.

**Comment by glenn-jocher** [comment]
@abuelgasimsaadeldin great to hear a reboot worked! Let us know if you run into any other problems.

**Comment by abuelgasimsaadeldin** [comment]
Hi @glenn-jocher 

Sorry for bringing this back up again but the problem is still not resolved, I tried rebooting my PC multiple times but it does not seem to work. No error messages are observed and the camera light turns on. Anybody encounter this problem before or has any solutions that I may try? It would be very much appreciated. Thank you.

PS. This only occurs while trying to run on CUDA and not on CPU.
