### ISSUE TITLE
Pytorch Hub inference returns different results than detect.py

### ISSUE THREAD

**Issue by Aoobi** [ultralytics/yolov5#2224]
Hi, 
I trained Yolov5x on my custom dataset using this notebook from roboflow: https://colab.research.google.com/drive/1gDZ2xcTOgR39tGGs-EZ6i3RTs16wmzZQ
In the notebook when I do inference I am getting good results, with confidence about 0.8 for basically every image, but when i downloaded the weights and used them in the hub locally, the results are different - if I set the threshold for 0.4 I am getting almost no results. 
Also, the class names are not displayed when inferring with torchhub. I am using this code to run inference with pytorch hub:

`model = torch.hub.load('ultralytics/yolov5', 'custom', path_or_model="path_to_my_weight_file.pt")`
`model.conf = 0.4`
`results = model(list_of_paths_to_my_images)`
`results.save("path_to_save_files")`

Thanks

**Comment by glenn-jocher** [comment]
@Aoobi we don't support 3rd party training tools. If you'd like to train and deploy correctly simply follow the official Custom Training Tutorial and the Pytorch Hub Tutorials below, and if you'd like a notebook environment we recommend the notebooks below. Good luck!

## Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>
