### ISSUE TITLE
Image size during inference (detect.py)

### ISSUE THREAD

**Issue by jovenwayfarer** [ultralytics/yolov5#2234]
## ❔Question
Hello,
I trained a model using default image size (640 in argparser) I assume it is (640,640,3), then during the inference the terminal outputs (384x640), I have checked the code and can not get why the shape is 384x640, thanks.

**Comment by glenn-jocher** [comment]
@jovenwayfarer rectangular inference! It's an awesome YOLOv5 feature. See https://github.com/ultralytics/yolov3/issues/232

**Comment by phamdat09** [comment]
hello, @glenn-jocher, as I knew, the input of the model is fixed. How does rectangular inference work?? Sorry for native question

**Comment by glenn-jocher** [comment]
@phamdat09 rectangular inference! It's an awesome YOLOv5 feature. See https://github.com/ultralytics/yolov3/issues/232 for an explanation.

**Comment by phamdat09** [comment]
@glenn-jocher , thanks for your reply! I already read your post but I am a bit confused!! For example, I have a model which is trained with input size [640, 640]. How does the model work with 1 different input size as rectangular input?

**Comment by glenn-jocher** [comment]
@phamdat09 during inference image is resized to --img-size on long side, and then padded as required on short side to meet minimum stride multiple of 32.

So --img-size argument specifies long side.

**Comment by Jiessie-jq** [comment]
I have the same question. Why the model can receive different input size? I understand the short side being padded to multiple of 32. But like there are two images, [640,32] and [640,64]. The short sides are both multiple of 32 but the two images have different size. How can they be fed into the same network?

**Comment by Jackie-LJQ** [comment]
> @phamdat09 during inference image is resized to --img-size on long side, and then padded as required on short side to meet minimum stride multiple of 32.
> 
> So --img-size argument specifies long side.

I have the same question. Why the model can receive different input size? I understand the short side being padded to multiple of 32. But like there are two images, [640,32] and [640,64]. The short sides are both multiple of 32 but the two images have different size. How can they be fed into the same network?

**Comment by phamdat09** [comment]
@Jiessie-jq It works because the output of the model is the list of anchor boxes. For example, with an image size [640, 320], output is `n` anchors. With another one, like [640, 400] output is `m` anchors. ( `n` and `m` are just a number). You can export model with different size of input to `onnx` and use the `https://netron.app/` to visualise

**Comment by Jackie-LJQ** [comment]
> @Jiessie-jq It works because the output of the model is the list of anchor boxes. For example, with an image size [640, 320], output is `n` anchors. With another one, like [640, 400] output is `m` anchors. ( `n` and `m` are just a number). You can export model with different size of input to `onnx` and use the `https://netron.app/` to visualise

Many thanks for your reply. I have another question. What about the training? I read the code about Dataset and DataLoader and I thought only letterbox function changed the input image size. I checked the image shape returned from letterbox and thay are like (640,640,3), (448,672,3)...multiple of 32. But durning training the input size seems like (640,640,3).  I use the default input size, so the shape should always be (640,640)? But I can't exactly find which function changes the image shape?

**Comment by glenn-jocher** [comment]
@Jiessie-jq all main functions (train, detect, test) accept the same --img-size argument to specify an inference image size (default 640 pixels):

```
python train.py --img 640
python test.py --img 640
python detect.py --img 640
```
