### ISSUE TITLE
Multi-GPU Training via ABCI

### ISSUE THREAD

**Issue by abebe9849** [ultralytics/yolov5#2238]
## ❔Question
I　used 
`python -m torch.distributed.launch --nproc_per_node 4 train.py --batch-size 256 --data coco.yaml --weights yolov5s.pt`

but result was here.

YOLOv5 v4.0-63-g73a0669 torch 1.7.1 CUDA:0 (Tesla V100-SXM2-16GB, 16160.5MB)
                                    CUDA:1 (Tesla V100-SXM2-16GB, 16160.5MB)
                                    CUDA:2 (Tesla V100-SXM2-16GB, 16160.5MB)
                                    CUDA:3 (Tesla V100-SXM2-16GB, 16160.5MB)

Namespace(adam=False, batch_size=64, bucket='', cache_images=False, cfg='', data='./data/coco.yaml', device='', epochs=300, evolve=False, exist_ok=False, global_rank=0, hyp='data/hyp.scratch.yaml', image_weights=False, img_size=[640, 640], local_rank=0, log_artifacts=False, log_imgs=16, multi_scale=False, name='exp', noautoanchor=False, nosave=False, notest=False, project='runs/train', quad=False, rect=False, resume=False, save_dir='runs/train/exp14', single_cls=False, sync_bn=False, total_batch_size=256, weights='yolov5s.pt', workers=8, world_size=4)
Start Tensorboard with "tensorboard --logdir runs/train", view at http://localhost:6006/
Traceback (most recent call last):
  File "/fs1/groups1/gcc50613/work/abe/yolo_env/lib/python3.8/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 196, in makedirs
    os.makedirs(path)
  File "/apps/python/3.8.2/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'runs/train/exp14'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 521, in <module>
    tb_writer = SummaryWriter(opt.save_dir)  # Tensorboard
  File "/fs1/groups1/gcc50613/work/abe/yolo_env/lib/python3.8/site-packages/torch/utils/tensorboard/writer.py", line 221, in __init__
    self._get_file_writer()
  File "/fs1/groups1/gcc50613/work/abe/yolo_env/lib/python3.8/site-packages/torch/utils/tensorboard/writer.py", line 251, in _get_file_writer
    self.file_writer = FileWriter(self.log_dir, self.max_queue,
  File "/fs1/groups1/gcc50613/work/abe/yolo_env/lib/python3.8/site-packages/torch/utils/tensorboard/writer.py", line 61, in __init__
    self.event_writer = EventFileWriter(
  File "/fs1/groups1/gcc50613/work/abe/yolo_env/lib/python3.8/site-packages/tensorboard/summary/writer/event_file_writer.py", line 77, in __init__
    tf.io.gfile.makedirs(logdir)
  File "/fs1/groups1/gcc50613/work/abe/yolo_env/lib/python3.8/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 669, in makedirs
    return get_filesystem(path).makedirs(path)
  File "/fs1/groups1/gcc50613/work/abe/yolo_env/lib/python3.8/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 198, in makedirs
    raise errors.AlreadyExistsError(
tensorboard.compat.tensorflow_stub.errors.AlreadyExistsError: Directory already exists
Internal process exited
Traceback (most recent call last):
  File "/apps/python/3.8.2/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/apps/python/3.8.2/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/fs1/groups1/gcc50613/work/abe/yolo_env/lib/python3.8/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/fs1/groups1/gcc50613/work/abe/yolo_env/lib/python3.8/site-packages/torch/distributed/launch.py", line 255, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/fs1/groups1/gcc50613/work/abe/yolo_env/bin/python', '-u', 'train.py', '--local_rank=3', '--batch-size', '256', '--data', 'coco.yaml', '--weights', 'yolov5s.pt']' returned non-zero exit status 1.

I used Tesla v100 via[ ABCI](https://github.com/aistairc/abci-docs/) 
and run this 
"""qsub -g gcc50613 -l rt_F=1 -l h_rt=72:00:00 /groups1/gcc50613/work/abe/src/train.sh """

 cat train.sh 
>>>
#!/bin/bash
source /etc/profile.d/modules.sh
module load gcc/7.4.0 python/3.8/3.8.2 cuda/10.2 cudnn/8.0/8.0.5
source /groups1/gcc50613/work/abe/yolo_env/bin/activate
cd /groups1/gcc50613/work/abe/yolov5
python -m torch.distributed.launch --nproc_per_node 4 train.py --batch-size 256 --data coco.yaml --weights yolov5s.pt

/groups1/gcc50613/work/abe/yolov5 is cloned repository
/groups1/gcc50613/work/abe/yolo_env has libraries from "pip install -r Requirements.txt"

**Comment by glenn-jocher** [comment]
@abebe9849 very interesting, did not know about ABCI before!

Your error is just saying that a directory exists when using the mkdir command:
`FileExistsError: [Errno 17] File exists: 'runs/train/exp14'`

This could just be from a previous training. You can simply remove this directory, or create a new environment etc.

**Comment by abebe9849** [comment]
I removed runs/train/* in this way
[acc13140ld@es4 train]$ pwd
/groups1/gcc50613/work/abe/yolov5/runs/train
[acc13140ld@es4 train]$ ls
[acc13140ld@es4 train]$ qsub -g gcc50613 -l rt_F=1 -l h_rt=72:00:00 /groups1/gcc50613/work/abe/src/train.sh
Your job 6166413 ("train.sh") has been submitted
[acc13140ld@es4 train]$ 

and I succeeded! thanks a lot !

**Comment by glenn-jocher** [comment]
@abebe9849 great! Let us know if you run into any other issues. Happy trainings.

**Comment by Jelly123456** [comment]
@abebe9849 I also faced the same problem that shows "directory already exists" when training with multiple GPUS.

My two GPUS are in the cooperation's private cloud. I think your command "qsub ***" is to reconnect to the GPUs. This sounds strange by "reconnecting to the GPUs".

In the older version, I can easily train with multiple GPUs without logging out and logging in again.
@glenn-jocher Could you guide how to solve this problem? Why it still shows the "directory exists" error even though I already deleted it.

**Comment by glenn-jocher** [comment]
@Jelly123456 I'm sorry I don't have experience with ABCI. OP posted a solution to his issue in https://github.com/ultralytics/yolov5/issues/2238#issuecomment-780933371, you may want to try his solution.

If none of these apply to you, we suggest you close this issue and raise a new one using the 🐛 **Bug Report template**, providing screenshots and a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) of your issue. Thank you!

**Comment by snownus** [comment]
It is related to the tensorboard version. pytorch1.7.1 match with tensorboard 2.4.1 , pytorch 1.8.0 match with tensorboard 2.5.0
