### ISSUE TITLE
pip install yolov5 - How does yolov5.predict() work?

### ISSUE THREAD

**Issue by saskia1001** [ultralytics/yolov5#2240]
## ❔Question
I pip installed yolov5 and want to integrate it into a python script for detecting my custom objects in a feed of a drone. But the basic command `results = yolov5.predict(image1)` on a jpg image did not give me anything back. When I try `results.show()` , I just get the original image back. For the `model_path` I gave the `.pt` file of my custom trained model. Does it work with my own weights and classes? How can I use yolov5.predict()? Can I find any further documentation on how to use it?

## Additional context
Thanks a lot for the YOLOv5 model. I trained a YOLOv5 model with custom data and it worked perfectly.

**Comment by glenn-jocher** [comment]
@saskia1001 that is a good question! We are not actually the original authors of the new pip package. We were planning on launching a pip package that acted as a wrapper around our PyTorch Hub functionality, but it seems we were too slow and another author did this for us. Our idea was to provide a common (and identical) interface between the pip model and PyTorch Hub model. It appears the pip package acts along these lines but is not an exact equivalent.

From https://pypi.org/project/yolov5/ the package homepage is listed as https://github.com/fcakyon/yolov5-pip. I will raise an issue there to see if they can align the pip model functionality with the torch hub model functionality, and then you should be able to to visit the hub tutorial to answer all your questions. 

## Tutorials

* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW

**Comment by saskia1001** [comment]
@glenn-jocher Thanks for the quick response! And for clearing the authorship. The PyTorch Hub functionality works great for predictions on images for my custom model. But I did not manage to make detection on a video (.mp4) or a video feed. Does this work? I did not figure it out. Looking forward to seeing and working with your pip package.

**Comment by glenn-jocher** [comment]
@saskia1001 you can think of the hub model as a higher level model than the basic pytorch model, as it handles pre and postprocessing (resizing, NMS, etc.). It accepts a single image or a batch of images. Therefore if you have a video you must load it with a package like cv2 and pass in individual frames to the hub model.

Alternatively detect.py is a fully managed solution for video inference:
`python detect.py --source video.mp4`

**Comment by saskia1001** [comment]
@glenn-jocher That helps a lot! Thank you!!!

**Comment by saskia1001** [comment]
Hi @glenn-jocher, I tried to implement the PyTorchHub approach for my drone project. I can path a numpy.ndarray into the `results = model(img, im_size)` method. That works fine. results gives back an object of the type "models.common.Detections". Is there any way to convert this object type back into a numpy.ndarray? I need to pass the detection into `cv2.imshow()`. The `results.show()` method does not do the job in my script as I need to loop through a while loop with changing frames in order to get my video stream with the detection running. If I pass `results.show()` into `cv2.imshow()`, my loop only return the first frame/img from the video stream. It would really help me to know how to get models.common.Detections back into an np.ndarray. Thanks a lot!

**Comment by glenn-jocher** [comment]
@saskia1001 yes, the Detections object provides a number of values following inference. See the Detections() class for full details:
https://github.com/ultralytics/yolov5/blob/d2e754b67bc08d3634df05932cc94d8c9314a7b1/models/common.py#L231-L246

**Comment by glenn-jocher** [comment]
@saskia1001 BTW, to answer your cv2 show question, you can do results.render(), which will overlay detections onto results.imgs, and then pass results.imgs to cv2.show()

**Comment by saskia1001** [comment]
@glenn-jocher `results.render()` did the job. I had an older version of common.py where `render()` was not included. It is the version Roboflow uses to apply the model (Colab Notebook) on which I did my first training trys and had stored locally. Thank you so much for your support! This model is awesome. Great work!

**Comment by glenn-jocher** [comment]
@saskia1001 great, glad everthing works. If you have any other issues or suggestions let us know!

**Comment by jahanvikotwal** [comment]
local variable 'results' referenced before assignment

**Comment by glenn-jocher** [comment]
@jahanvikotwal hi,

It seems that the issue you're facing is related to a local variable 'results' being referenced before assignment. This error typically occurs when you're attempting to use a variable before it has been defined or assigned a value.

To resolve this issue, make sure that you have properly initialized and assigned a value to the 'results' variable before attempting to reference it. Double-check your code for any potential syntax or logical errors that might be causing this problem.

If you're still experiencing difficulties, please share the relevant code snippet or provide more information about the specific context in which this error occurs. This will help us provide more targeted assistance.

Thank you.
