### ISSUE TITLE
Webcam crash in Intell Macbook pro

### ISSUE THREAD

**Issue by SZ-Chander** [ultralytics/yolov5#2241]
## I set the --source "0" , cudnn.benchmark == True, model is yolo-5s. And the program is work -- just one second , or half -- and crash.
And I get the warning:"fps = vid_cap.get(cv2.CAP_PROP_FPS) \n AttributeError: 'NoneType' object has no attribute 'get'".
I code a simple test to open my cam and I succeed, so maybe I can say that is not my cam warn...But Why??
Waiting for you help, thank you very much ! Yolo-v5 is very powerful and useful, Thanks for your work!

mbp2019, Mac os 15, python 3.8, opencv-python==4.4.0

**Comment by SZ-Chander** [comment]
And the save dir have been make.

**Comment by glenn-jocher** [comment]
@SZ-Chander hi sorry to hear that you are having problems running YOLOv5 on your M1 Macbook. We will test on one of our M1 Macbooks here.

**Comment by SZ-Chander** [comment]
> @SZ-Chander hi sorry to hear that you are having problems running YOLOv5 on your M1 Macbook. We will test on one of our M1 Macbooks here.
OH my friend, My Macbook is a intell mac, not m1...

**Comment by glenn-jocher** [comment]
@SZ-Chander we've tested `python detect.py --source 0` on our M1 Macbook and everything works great!

<img width="1000" alt="Screen Shot 2021-02-18 at 10 42 14 AM" src="https://user-images.githubusercontent.com/26833433/108405543-0c67c780-71d6-11eb-9ec7-a6c0b35c8b46.png">

**Comment by glenn-jocher** [comment]
@SZ-Chander ah, well if it works for M1 it should definitely work for Intel also. If you are having problems they are likely environment related. I'll link our default reply below which may help you:

It appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below. 


## Requirements

**Python 3.8** or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including **`torch>=1.7`**. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by SZ-Chander** [comment]
@glenn-jocher Ok, Thank you very much! I will try again and send the reply if it work or get other question. Have a good day!
