### ISSUE TITLE
Why does the Bottleneck module have an expansion factor(e) of 1.0?

### ISSUE THREAD

**Issue by JM-Kim-94** [ultralytics/yolov5#2244]
## Additional context
![image](https://user-images.githubusercontent.com/78307871/108464878-4d3e0a00-72c4-11eb-996e-559f5035a5b4.png)

In the C3 Module it has Bottleneck sub module whose expansion factor is 1.0. 
`        self.m = nn.Sequential(*[Bottleneck(c_, c_, shortcut, g, e=1.0) for _ in range(n)])`

I know the Bottleneck module's role: it reduce the number of channels as expansion factor e. 
However in the code, the module has e=1.0 which preserve number of channels. 
I wonder why you use factor e=1.0.

**Comment by glenn-jocher** [comment]
@JM-Kim-94 the expansion factor e=1.0 in the C3() modules is inherited from the same expansion factor in the CSPBottleneck() modules, which are based on the work in https://arxiv.org/abs/1911.11929.

**Comment by JM-Kim-94** [comment]
@glenn-jocher 
Thanks for your prompt reply!
