### ISSUE TITLE
Yolov5 baseline was trained by one gpu or multi gpus?

### ISSUE THREAD

**Issue by hujunchao** [ultralytics/yolov5#2245]
## ❔Question
Hi, thank you for your great work! And I have a question that Yolov5 baseline was trained by one gpu or multi gpus?

## Additional context
![image](https://user-images.githubusercontent.com/22813297/108485517-f8a48a00-72d7-11eb-9c56-475852a15a27.png)

**Comment by glenn-jocher** [comment]
@hujunchao we only use 1 GPU when training the models at 640. For higher --img-size we use multiple GPUs. The batch sizes for 1 V100 and commands to reproduce the trainings are shown in the README here:
https://github.com/ultralytics/yolov5#training
