### ISSUE TITLE
can I increase the number of anchors from 3 to 4 ? 

### ISSUE THREAD

**Issue by zhaiyukun** [ultralytics/yolov5#2254]

**Comment by glenn-jocher** [comment]
@zhaiyukun you can increase or decrease anchor count to any number you want.

**Comment by glenn-jocher** [comment]
@zhaiyukun to manually specify anchors, introduce them in your model.yaml here, or simply replace the arrays with a number, i.e. `anchors: 5`, to evolve 5 anchors per output layer:
https://github.com/ultralytics/yolov5/blob/6f5d6fcdaa8c1c5b24a06fdf9fd4e12c781fb4f7/models/yolov5s.yaml#L6-L11

**Comment by zhaiyukun** [comment]
thanks a lot for your reply
