### ISSUE TITLE
Dear author, can you provide a visualization scheme for YOLOV5 feature graphs during detect.py? Thank you!

### ISSUE THREAD

**Issue by 113HQ** [ultralytics/yolov5#2259]

**Comment by glenn-jocher** [comment]
@113HQ well, what features do you want to visualize exactly? The models typically have hundreds of layers and each layer has hundreds of feature maps.

**Comment by 113HQ** [comment]
Example，the three nodes of the PANet(#17、#20、#23)



---Original---

**Comment by glenn-jocher** [comment]
@113HQ yes but this is what i mean, within each of these 3 stages (17, 20 and 23) there are very many feature maps. If we take yolov5l.yaml for example, layer 17 has 256 feature maps, layer 20 has 512 and layer 23 has 1024 feature maps. So there are almost 1800 feature maps that you can look at in just the YOLOv5l output layers (for a single input image).

https://github.com/ultralytics/yolov5/blob/master/models/yolov5l.yaml

**Comment by 113HQ** [comment]
Yes，I know. I just want to know what the feature maps inside look like. Can we just choose layer 17 as an example? (for a single input image)



---Original---

**Comment by glenn-jocher** [comment]
@113HQ well, yes its certainly possible to build a visualizer. You could make maybe a 4x3 matplotlib grid, put the original image in the top left subplot, then in each of the rows put the first 3 feature maps from the output layers. You could do this by updating the model forward method to capture the outputs at the layers you were interested in, then it's just a matter of plotting and displaying them nicely. The place you'd capture the feature maps is here. I don't have a lot of free time to work on this, but if you want to get started and submit a PR that would great!
https://github.com/ultralytics/yolov5/blob/095d2c11d89892cd9c0c4d034cd1c768a0dba11c/models/yolo.py#L120-L136

**Comment by glenn-jocher** [comment]
@113HQ BTW, a single feature map may be in my opinion a shallow set of information, as you are looking at a 2d spatial slice but are not aptly observing relationships across the feature space (as the convolutions do). 

I guess an analogy is that you would be viewing the R, G, B layers of a color image by themselves, when it helps to view them together to get the complete picture.

**Comment by 113HQ** [comment]
Ok，I''ll have a try. Thanks



---Original---

**Comment by JiaLim98** [comment]
Hi @glenn-jocher,

Do you have any image for the entire architecture of YOLOv5? For example:
![image](https://user-images.githubusercontent.com/66768413/108822196-b6da5300-75f9-11eb-99ae-7f31b6bbfc15.png)
obtained from [this link](https://paperswithcode.com/task/disparity-estimation/codeless?page=3).

If you do not have a nicely plotted one, a hand sketched version will do as well, I can make it nicely myself. I have looked through all YOLOv5 publications but none of them has one image regarding the architecture. I guess getting one from you is much straightforward, otherwise making one will have misunderstanding issues and draw it wrongly. Hope you have one :D.

Many thanks for the great work on YOLOv5!

**Comment by zhiqwang** [comment]
Hi @JiaLim98 ,

Maybe you could check #280 and [this](https://github.com/zhiqwang/yolov5-rt-stack/issues/41#issuecomment-767649964) (yolov5s release 3.1 specially).

**Comment by JiaLim98** [comment]
Hi @zhiqwang,

Thank you so much! Do you have one for v4.0? because my work uses only v4.0.
To my knowledge, there are major changes in the architecture between v3.1 and v4.0 right?

**Comment by JiaLim98** [comment]
I found one following the blog you attached, [here](https://img-blog.csdnimg.cn/2021010620271767.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L1ExdTFORw==,size_16,color_FFFFFF,t_70). Is this correct?

Just to double confirm, @glenn-jocher, do you agree with the diagrams plotted? Do those directly reflect what YOLOv5 is doing?

**Comment by glenn-jocher** [comment]
@JiaLim98 yes, there were architectural changes between v3.1 and v4.0: the C3() modules replaced CSPBottleneck() modules, and SiLU() replaced HardSwish(). We actually haven't plotted the model ourselves, we typically just use the model yaml files a first order approximation of the structure, and also use Netron to view the block diagram (sometimes looks better with ONNX exported models than the pytorch ones), and sometimes the interactive TF graph view is useful also (when it works):
https://github.com/ultralytics/yolov5/blob/7a6870b81f31db40b06d2e899801febbeed96696/train.py#L324

The linked models are good too, they seem correct.

**Comment by WANGCHAO1996** [comment]
> 
> Ok，I''ll have a try. Thanks
> […](#)
> ---Original--- From: "Glenn Jocher"<notifications@github.com&gt; Date: Mon, Feb 22, 2021 13:04 PM To: "ultralytics/yolov5"<yolov5@noreply.github.com&gt;; Cc: "113HQ"<948107836@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; Subject: Re: [ultralytics/yolov5] Dear author, can you provide a visualization scheme for YOLOV5 feature graphs during detect.py? Thank you! (#2259) @113HQ BTW, a single feature map may be in my opinion a shallow set of information, as you are looking at a 2d spatial slice but are not aptly observing relationships across the feature space (as the convolutions do). I guess an analogy is that you would be viewing the R, G, B layers of a color image by themselves, when it helps to view them together to get the complete picture. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.



> 
> Ok，I''ll have a try. Thanks
> […](#)
> ---Original--- From: "Glenn Jocher"<notifications@github.com&gt; Date: Mon, Feb 22, 2021 13:04 PM To: "ultralytics/yolov5"<yolov5@noreply.github.com&gt;; Cc: "113HQ"<948107836@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; Subject: Re: [ultralytics/yolov5] Dear author, can you provide a visualization scheme for YOLOV5 feature graphs during detect.py? Thank you! (#2259) @113HQ BTW, a single feature map may be in my opinion a shallow set of information, as you are looking at a 2d spatial slice but are not aptly observing relationships across the feature space (as the convolutions do). I guess an analogy is that you would be viewing the R, G, B layers of a color image by themselves, when it helps to view them together to get the complete picture. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Hello, have you realized the visualization of feature map? Thank you

**Comment by glenn-jocher** [comment]
@WANGCHAO1996 @zhiqwang @113HQ @JiaLim98 good news 😃! Feature map visualization was added ✅ in PR #3804 by @Zigars today. This allows for visualizing feature maps from any part of the model from any function (i.e. detect.py, train.py, test.py). Feature maps are saved as *.png files in runs/features/exp directory. To turn on feature visualization set `feature_vis=True` in the model forward method and define the layer you want to visualize (default is SPP layer).

https://github.com/ultralytics/yolov5/blob/20d45aa4f18d7df7148fc6dd69a9c0607003f004/models/yolo.py#L158-L160

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

![layer_8_SPP_features](https://user-images.githubusercontent.com/26833433/123628234-27e17f80-d813-11eb-8d72-5d5560cd9ee4.png)
