### ISSUE TITLE
Second-stage classifier in detect.py

### ISSUE THREAD

**Issue by hdnh2006** [ultralytics/yolov5#2260]
## ❔Question

In [`line 41`](https://github.com/ultralytics/yolov5/blob/095d2c11d89892cd9c0c4d034cd1c768a0dba11c/detect.py#L41) of `detect.py` we can see the following:

```
    if classify:
        modelc = load_classifier(name='resnet101', n=2)  # initialize
        modelc.load_state_dict(torch.load('weights/resnet101.pt', map_location=device)['model']).to(device).eval()
```

But in the[`line 40`](https://github.com/ultralytics/yolov5/blob/095d2c11d89892cd9c0c4d034cd1c768a0dba11c/detect.py#L40) (inmmediately before), you see `classify=False`. So in this case, it never will enter into that `if` statement, so my question are:

1. what does it do this `if` statement?
2. Can we change this second-stage classifier for a pre-trained neural network? for example an alexnet or something like that.
3. In case the above is true, how it is done?

Thanks again Glenn for this fantastic tool you and your team have created.

**Comment by glenn-jocher** [comment]
@hdnh2006 this is a bring-your-own-model situation. Some users like the option of having a second stage filter first stage detections to reduce FPs. If you have a classifier trained on the same classes you can specify it there. Any classifier can be used here (EfficientNet, Resnet, etc.), the only requirement is that the classification and detection models are trained on the same classes. 

Also note that the current implementation is just a starting point for this two-stage experimentation, this is not a fully managed or implemented feature. There are also a number of other issues on the same topic also:
https://github.com/ultralytics/yolov5/issues?q=is%3Aissue+resnet101

**Comment by hdnh2006** [comment]
Thanks Glenn, for being so fast in the time of each answer.

**Comment by hdnh2006** [comment]
Sorry Glenn @glenn-jocher for re-opening this issue, but after reading different issues you recommended me I still cannot understand what a second-stage classifier works or what are the advantages.

Let's see what I understand from YOLOv3 (I assume YOLOv5 works similarly), YOLO "only looks once", so it creates multiple bounding boxes that then are classified for (let's say) a second stage of the neural network, we can say the second part of the neural network. So first, a NNet with just convolutional layers creates the BBoxes and then a classifier makes its work, then NMS is applied and blah blah blah. 

So in the case we are talking in `detect.py`, do we are replacing this second stage for another classifier to reduce de frames per seconds? In case not, why this new classifer should have the same output classes that the output of the YOLO classifier? I read in other [post](https://github.com/ultralytics/yolov5/issues/1033#issuecomment-698299892) you recommended me an example like: "plate recognition and then classify the characters", is this true? In this last case the output classes are not the same.

I don't know if I am explaining good and I know this is not a feature supported by YOLOv5, so if you cannot help me I'll understand it. 

BTW, I saw on your profile you are also in Madrid, so due to all I owe you for this fantastic tool you have created, I would like to invite you a beer if you have some time hehe.

**Comment by glenn-jocher** [comment]
@hdnh2006 ah thanks buddy. Yes I travel back and forth between Madrid and Los Angeles, I should be back in Madrid later in March. 

The classifier is entirely optional, for organizations looking to reduce FPs beyond the native YOLO capability. Nothing in the YOLO model is different, the classifier simply classifies the bounding box contents, and if the classification matches the YOLO classification then the detection is used.

**Comment by hdnh2006** [comment]
Understood! Thanks Glenn!

**Comment by summer-1010** [comment]
HI Glenn! @glenn-jocher After seeing the discustion above, i have a question that if we use the second-stage classifier, and it give out a different answer from v5 which means the origin prediction will be remove?or it will just cover the old one with the new one?I will be appreciate if u could answer me!Thanks!

**Comment by glenn-jocher** [comment]
@summer-1010 you can set up any logic you want regarding second stage classifiers. In general they may be useful for reducing FPs. See TowerScout for a deployed example of YOLOv5 paired with a second stage EfficientNet model.
https://groups.ischool.berkeley.edu/TowerScout/

<img width="1513" alt="Screenshot 2021-06-09 at 15 14 25" src="https://user-images.githubusercontent.com/26833433/121361242-6632ff80-c935-11eb-8e39-3f5e02bc50a0.png">

**Comment by summer-1010** [comment]
@glenn-jocher Thank u Glenn for repling thak quick,your reply is really useful for me ,have a good day!Thanks a lot!
