### ISSUE TITLE
cv2.imshow() is enabled

### ISSUE THREAD

**Issue by ClassifierPower** [ultralytics/yolov5#2261]
WARNING: Environment does not support cv2.imshow() or PIL Image.show() image displays
cv2.imshow() is disabled in Docker environments

运行之后报了这个错误，我该如何解决？

**Comment by ClassifierPower** [comment]
运行老版本的文件还是没有问题的，更新了之后就报了这个错误

**Comment by glenn-jocher** [comment]
@ClassifierPower this is fine, it's just a notice that no images will be displayed due to environmental restrictions. If you run the same code on a desktop environment inference results would be showed in realtime.

**Comment by ClassifierPower** [comment]
但是我确实是在windows环境运行的。事与愿违，他还是没有将推理结果实时显示。

**Comment by ydteng** [comment]
@ClassifierPower Have you solved the problem? I had the same problem.

**Comment by ClassifierPower** [comment]
我还没有解决这个问题，你解决了吗？

**Comment by ydteng** [comment]
@ClassifierPower 
解决了
你应该也是windows10环境吧？就是把utils/general.py下的isdocker()函数中的return修改为注释后面的内容即可，如下
```python
def isdocker():
    # Is environment a Docker container
    return Path('/.dockerenv').exists()
```
猜测是原来的代码是在linux下用的，后面的是Windows下的
