### ISSUE TITLE
Worst best possible recall after evolving anchors ?

### ISSUE THREAD

**Issue by Ownmarc** [ultralytics/yolov5#2263]
## ❔Question

Is it me not understanding this correctly or did the anchors evolution created worst anchors ?

Best possible recall after Kmean is 0.9995 and drops to 0.9992 after evolution.

![image](https://user-images.githubusercontent.com/24617457/108631065-21429600-7436-11eb-85a7-854d4cb7ff83.png)

**Comment by glenn-jocher** [comment]
@Ownmarc depends on your definition of better or worse. 

The evolution fitness function definition of better is here, it primarily minimizes the width and height gain deviation between the labels and the anchors (from both directions towards 1.0). BPR contributes to the definition but does not represent it fully.
https://github.com/ultralytics/yolov5/blob/095d2c11d89892cd9c0c4d034cd1c768a0dba11c/utils/autoanchor.py#L78-L98
