### ISSUE TITLE
Different Backbone

### ISSUE THREAD

**Issue by ferro07** [ultralytics/yolov5#2264]
hey Dear @glenn-jocher 
Thank you for this nice work. yolov5's infrastructure is quite nice. If possible, can you share yaml file of structures such as cspresnext50, cspresnet50, yolov4, spinet. That way it gets even more perfect.
Many Thanks.

**Comment by glenn-jocher** [comment]
@ferro07 hmm, well we can construct most any model.yaml if we have the right building blocks. I think some architectures use special layers/modules that may need to be defined (in common.py or experimental.py), and then these can be used in the model.yaml files. 

For now we've defined YOLOv3, YOLOv3-SPP, YOLOv3-tiny, YOLOv5 models and some other experimental models with FPN, PANet heads, P6 and P7 output layers etc... These extra models are saved in models/hub:
https://github.com/ultralytics/yolov5/tree/master/models/hub

If you'd like to contribute a new model yaml PR that would be awesome too!

**Comment by glenn-jocher** [comment]
@ferro07 by the way, when I created the yaml model files and loading architecture last year I tried to make everything as **parameterized** and **architecture-agnostic** as possible, so while right now most of the models are YOLO models, the yaml files can be used to define most any type of architecture, including the ones you mentioned. 

Actually I remember I just saw a reddit post about a new pip package called kindle that is based on the YOLOv5 yaml architectures that can be used to define any type of model https://github.com/JeiKeiLim/kindle
