### ISSUE TITLE
Label Missing: for images and labels... 203 found, 50 missing, 0 empty, 0 corrupted: 100%

### ISSUE THREAD

**Issue by Rana-Javed** [ultralytics/yolov5#2268]
Scanning '../GuavaDataset/labels/train.cache' for images and labels... 203 found, 50 missing, 0 empty, 0 corrupted: 100%

50 Labels are missing while caching. and results are very low:

Epoch   gpu_mem       box       obj       cls     total   targets  img_size
     49/49     1.82G   0.08977    0.1288         0    0.2186       107       416: 100% 16/16 [00:02<00:00,  7.06it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100% 2/2 [00:00<00:00,  2.75it/s]
                 all          26         131       0.147       0.191      0.0793      0.0181

**Comment by glenn-jocher** [comment]
@Rana-Javed 50 missing indicates that 50 of your images lack labels. If this was not intentional then you have a problem in your dataset. 

See https://docs.ultralytics.com/yolov5/tutorials/train_custom_data to get started.

**Comment by abuelgasimsaadeldin** [comment]
@glenn-jocher, "missing" indicates no text file at all, or an empty text file, or either? Also from what I understand from the Tips for Best Training Results it is good to have a few "missing" labels to reduce model's FP, is that correct?

**Comment by glenn-jocher** [comment]
@abuelgasimsaadeldin missing indicates no label file was found for an image, i.e. these will be treated as background images.

**Comment by MHassanlatif** [comment]
> @glenn-jocher, "missing" indicates no text file at all, or an empty text file, or either? Also from what I understand from the Tips for Best Training Results it is good to have a few "missing" labels to reduce model's FP, is that correct?

And what does (8933 found, 0 missing, **7736 empty**, 0 duplicate, for 21041 images)
7736 empty represent here?

**Comment by glenn-jocher** [comment]
@MHassanlatif empty images without any labels
