### ISSUE TITLE
When I train my custom data.  Does this code need to be modified？

### ISSUE THREAD

**Issue by yangbisheng2009** [ultralytics/yolov5#227]
My class number is 4 while the number in train.py is 80.
![image](https://user-images.githubusercontent.com/17609763/85986982-97196d80-ba1f-11ea-813f-606e12ddac7e.png)

**Comment by NanoCode012** [comment]
No. Just follow the instructions at the wiki [https://docs.ultralytics.com/yolov5/tutorials/train_custom_data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)
