### ISSUE TITLE
Count total number of object in each frame

### ISSUE THREAD

**Issue by abuelgasimsaadeldin** [ultralytics/yolov5#2271]
Hi guys,

I'm fairly new to python and went through the **detect.py** script and found the lines shown below (variable n) which obtains the total count per frame **per class**, I would like to utilize this and:

1) Find a way to sum up all the numbers detected in each iteration of the for loop and obtain the total count of objects per frame (regardless or class).

2) Display this number not only on the terminal but also on my video (either it be a webcam or a video file)

                # Print results
                for c in det[:, -1].unique():
                    n = (det[:, -1] == c).sum()  # detections per class
                    s += '%g %ss, ' % (n, names[int(c)])  # add to string

Any help for tackling both of these problems would be much appreciated. Thank you.

**Comment by glenn-jocher** [comment]
@abuelgasimsaadeldin I think you answered your own question pretty much, as `n` there contains the counts per class, and summing over the for loop provides you the sum over all classes.

You can customize image plotting with cv2 or PIL however you want. The predictions are plotted on the images here to give you an idea:
https://github.com/ultralytics/yolov5/blob/95aefea49374a1fe867794971c76337526a4d6cb/detect.py#L111-L114
