### ISSUE TITLE
Error "Directory already existed" happen when training with multiple GPUs

### ISSUE THREAD

**Issue by Jelly123456** [ultralytics/yolov5#2275]
## 🐛 Bug
When I train my own datasets with multiple GPUs, the ["runs/train/exp*" already exists] error always shows.

## To Reproduce (REQUIRED)

Input:
```
Run the command for multiple GPU training for my own datasets:
python -m torch.distributed.launch --nproc_per_node 2 train.py --batch-size 64 --data data/Allcls_one.yaml --weights weights/yolov5l.pt --cfg models/yolov5l_1cls.yaml --epochs 1 --device 0,1
```

Output:
```
Start Tensorboard with "tensorboard --logdir runs/train", view at http://localhost:6006/
Traceback (most recent call last):
  File "***/lib/python3.9/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 196, in makedirs
    os.makedirs(path)
  File "***/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'runs/train/exp5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "***/train.py", line 527, in <module>
    tb_writer = SummaryWriter(opt.save_dir)  # Tensorboard
  File "***/lib/python3.9/site-packages/torch/utils/tensorboard/writer.py", line 221, in __init__
    self._get_file_writer()
  File "***/lib/python3.9/site-packages/torch/utils/tensorboard/writer.py", line 251, in _get_file_writer
    self.file_writer = FileWriter(self.log_dir, self.max_queue,
  File "***/lib/python3.9/site-packages/torch/utils/tensorboard/writer.py", line 61, in __init__
    self.event_writer = EventFileWriter(
  File "***/lib/python3.9/site-packages/tensorboard/summary/writer/event_file_writer.py", line 77, in __init__
    tf.io.gfile.makedirs(logdir)
  File "***/lib/python3.9/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 669, in makedirs
    return get_filesystem(path).makedirs(path)
  File "***/lib/python3.9/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 198, in makedirs
    raise errors.AlreadyExistsError(
tensorboard.compat.tensorflow_stub.errors.AlreadyExistsError: Directory already exists
Traceback (most recent call last):
  File "***/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "***/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "***/lib/python3.9/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "***/lib/python3.9/site-packages/torch/distributed/launch.py", line 255, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['***/bin/python', '-u', 'train.py', '--local_rank=1', '--batch-size', '64', '--data', 'data/Allcls_one.yaml', '--weights', 'weights/yolov5l.pt', '--cfg', 'models/yolov5l_1cls.yaml', '--epochs', '1', '--device', '0,1']' returned non-zero exit status 1.
```

## Expected behavior
It should not show the "directory already exists" error because there is no such directory (runs/train/exp5) in the "runs" folder.

## Environment

 - OS: [Ubuntu]
 - GPU [Tesla V100s]

## Proposed solution
I solved locally by adding the following one-line code before "tb_writer = SummaryWriter(opt.save_dir)" which is in "train.py"
os.makedirs(opt.save_dir, exist_ok=True); This line code is to create the directory explicitly.
I was inspired by this link:
https://github.com/allenai/allennlp/pull/3843

![image](https://user-images.githubusercontent.com/29449336/108813364-d7031580-75eb-11eb-99e8-2dcb8cb5f47e.png)

After adding this code, the error disappears, and I can train successfully with multiple GPUs.

**Comment by glenn-jocher** [comment]
@Jelly123456 hi thanks for the bug report and for the proposed solution. I'm pretty confused by the error, as the tensorboard summarywriter can certainly be initialized with an existing directory. For example when resuming an interrupted training run with `python train.py --resume` then tensorboard picks up where it left off (in the same directory) with no problems. 

Maybe the error is produced **because the directory does not exist**? 

To allow us to debug could you provide a minimum reproducible example? Thanks!
https://docs.ultralytics.com/help/minimum_reproducible_example/

BTW a pro tip: the --weights, --cfg, and --data files are searched locally, so if they are unique you can simply pass the filename and we will find it automatically, i.e. as in the colab notebook example here:
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb#scrollTo=1NcFxRcFdJ_O&line=2&uniqifier=1

**Comment by glenn-jocher** [comment]
@Jelly123456 also that's strange that your error says **file** exists. runs/train/exp should be a **directory**, not a file.

**Comment by slimwangyue** [comment]
@Jelly123456 Just mkdir yourself before you run the codes and manually denote the --name as the directory you just built. Note that the codes will automatically change --name by appending numbers to it. So be sure to comment that line.

**Comment by glenn-jocher** [comment]
@slimwangyue @Jelly123456 you can log to the same directory every time using the --exist-ok flag. This prevents the log directory from incrementing:
```
python train.py --project PROJECT --name NAME --exist-ok
```
