### ISSUE TITLE
Why didn't I get results in my video test?

### ISSUE THREAD

**Issue by Kylinb** [ultralytics/yolov5#2277]
Hi,author!
/home/kylinb/anaconda3/envs/yolov5/bin/python /home/kylinb/PycharmProjects/yolov5/detect.py
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.25, device='', exist_ok=False, img_size=640, iou_thres=0.45, name='exp', project='runs/detect', save_conf=False, save_txt=False, source='/home/kylinb/PycharmProjects/yolov5/1.mp4', update=False, view_img=False, weights='/home/kylinb/PycharmProjects/yolov5/runs/train/exp2/weights/best.pt')
YOLOv5 v4.0-63-g73a0669 torch 1.7.1 CUDA:0 (GeForce RTX 2070 with Max-Q Design, 7982.3125MB)

Fusing layers... 
Model Summary: 224 layers, 7056607 parameters, 0 gradients, 16.3 GFLOPS
video 1/1 (1/-9223372036854775808) /home/kylinb/PycharmProjects/yolov5/1.mp4: 384x640 4 pigs, Done. (0.009s)

That's the problem. When I test a video,the result just like above. No video display, no video save. But the folder 'exp' would be created. Obviously, the folder is empty. It works only when testing pictures.

**Comment by glenn-jocher** [comment]
@Kylinb we use cv2 for video loading, so you may want to create a simple cv2 loop to see what's going wrong. 

You might also try exporting to a different format, or using one of our verified environments in the message above.

**Comment by VinayChaudhari1996** [comment]
Hi , @glenn-jocher @Kylinb 

I'm also getting same issue. 

1) After giving video source (.MP4 or .mkv) 
And successful run new (+Exp) empty folder is created, 

2) On colab it says fail to connect internal server X.


I think it trying to open video via cv2.show and this method is not working on colab.
Beacuse they have internal package for same. 


#### So , How can I saved detected bounding box generated video with save (TXT , Labels) etc. 
like image ? 


Thanks ,

**Comment by glenn-jocher** [comment]
@VinayChaudhari1996 inference works correctly in Colab notebook on videos. Tested myself today March 4th.
<img width="1523" alt="Screen Shot 2021-03-04 at 5 17 01 PM" src="https://user-images.githubusercontent.com/26833433/110053044-766f8900-7d0d-11eb-8f60-d5b4c59011f0.png">

**Comment by glenn-jocher** [comment]
To save txt use --save-txt. See detect.py argparser for all arguments.

**Comment by JOSHUAWENJZ** [comment]
@Kylinb Hi, Buddy! I think I find what is your problem. You need pay attention to your video encoding format. I just test some videos. And when I test a video with encoding format of 'hevc'（‘hevc’ is just a encoding style of H.265. But what you are using in OpenCV with H.264 encoding format. ）, the process was getting no results. Maybe you should modify the code of the encoding format of reading video with OpenCV, or there is just no encoder for 'hevc' format in your system, or you can just transform your videos in H.264 encoding format.
@glenn-jocher I think this issues can be closed. @Kylinb is my laboratory brother. : )

**Comment by glenn-jocher** [comment]
@JOSHUAWENJZ ok! Yes as you said we use cv2 for video reading, so the videos must be openable by cv2 for YOLOv5 inference to work.

**Comment by JOSHUAWENJZ** [comment]
@glenn-jocher @Kylinb I want to add some advice. Here is a simple solution. Just modify line 134 in detect.py as below.
`fps = 25  #enter a fixed number for fps, and it will work.`
I think the reason of no result is that OpenCV can't get the frame number and FPS information of your H.265 video. And I got some proof of my think that when I want to get the FPS of H.265 videos, I got 'inf'. @Kylinb Your 'nframes' in _datasets.py LoadImages_ function is negative number. This suggests that OpenCV got wrong information of your H.265 video.

**Comment by glenn-jocher** [comment]
@JOSHUAWENJZ so you would recommend hardcoding an FPS in detect.py L134 for better robustness to cv2 property retrieval issues there?

**Comment by JOSHUAWENJZ** [comment]
@glenn-jocher Yes. If you know the FPS of input video, just fix fps in detect.py L134. BUT I think there should be a better solution. And I will try to get right FPS and frame number of H.265 video, that is the best solution. : )

**Comment by glenn-jocher** [comment]
@JOSHUAWENJZ right, we want a robust solution that swaps in a default FPS on check failures. I don't think we can hard code 25 or 30 because then if someone runs a 60 FPS video for example then the output inference video will play at half speed.

There are a number of checks functions here in general.py, this would probably be the right place for a check_FPS() function. If you'd like to submit a PR for this that would be great!
https://github.com/ultralytics/yolov5/blob/886f1c03d839575afecb059accf74296fad395b6/utils/general.py#L55-L146

**Comment by riskycheng** [comment]
### root cause
please check the code line at:
[https://github.com/ultralytics/yolov5/blob/9d873077841434d1c6cbd1c4248ca2252820d3ba/utils/general.py#L50](https://github.com/ultralytics/yolov5/blob/9d873077841434d1c6cbd1c4248ca2252820d3ba/utils/general.py)
the author is trying to judge whether you are in Docker env by checking whether your absolutepath contains 'workspace':
```python
def isdocker():
    # Is environment a Docker container
    return Path('/workspace').exists()  # or Path('/.dockerenv').exists()
```
### solution:
Ensure there is no 'workspace' word in your full path.

**Comment by glenn-jocher** [comment]
@riskycheng this should only return True if the root directory is called `/workspace`. If there is a directory for example yolov5/workspace or workspace/yolov5 this will return False.

**Comment by riskycheng** [comment]
> @riskycheng this should only return True if the root directory is called `/workspace`. If there is a directory for example yolov5/workspace or workspace/yolov5 this will return False.

Hi @glenn-jocher ,
Thanks for correction! You are right and this is correct and clear in linux box, but it is a little bit tricky in windows.
if the path is like : `c:/workspace/yolov5/`, then it will return True, otherwise it works good since the diskname is actually invisiable for this checking.
