### ISSUE TITLE
Yolov5m6

### ISSUE THREAD

**Issue by pedrombefore** [ultralytics/yolov5#2280]
## ❔Question

I did a search in the whole repository and issues and did not find any explanation about the 6 in that .pt. Is that a special version like Yolov4Tiny with 3 Yolo Layers or it's only related to the training phase?

**Comment by glenn-jocher** [comment]
@pedrombefore v5m6.pt models are the same as YOLOv5m but with a P6 (stride 64) output layer added for larger objects. We've trained P6 versions of all YOLOv5s/m/l/x, these are denoted by a 6 at the end. 

The P6 layer increases accuracy at both 640 and 1280, so it's a great addition. It doesn't slow down the models very much, but it does increase their size substantially, maybe 50%. YOLOv5m6 is trained at 1280 and reaches a very high mAP for it's size. It will autodownload if you ask for it, ie. you can try

`python test.py --weights yolov5m6.pt --data coco.yaml`

**Comment by glenn-jocher** [comment]
@pedrombefore also more details in https://github.com/ultralytics/yolov5/issues/2110

We'll post full results soon to the README from our P6 experiments.

**Comment by pedrombefore** [comment]
@glenn-jocher  I'm doing some tests with shopping footage with a VGA input (640x480), the P6 seems a good approach to the problem. The thing is to find the balance between FPS and Accuracy, small architecture seems to work badly with small objects but runs faster. 
I will give a try to Yolov5s to compare the results.

![image](https://user-images.githubusercontent.com/60433809/108898563-b8058300-75ed-11eb-9f4e-333827b69078.png)

I did not find the issue because I searched for Yolov5m6. I will take a look at the notes. 

Thanks for the explanation

**Comment by glenn-jocher** [comment]
@pedrombefore it depends, if you want to detect people further away then you may want to run at higher resolution, and you could use a smaller model to keep your speed, i.e. maybe try YOLOv5s6 at 960 or 1280

**Comment by pedrombefore** [comment]
@glenn-jocher That's the point. I'm labeling my images to evaluate the models. Yolov5 gave me hope when trying to solve that problem.
I started with 416, 606 days ago and now 640x480, the native resolution from the IP Camera is 1280x720.

Congratulations on that work and Thanks for the tips!

If you have any published papers about Yolov5  let me know!
