### ISSUE TITLE
some questions about mosaic

### ISSUE THREAD

**Issue by zhaiyukun** [ultralytics/yolov5#2281]
## ❔Question
If using mosaic data enhancement, 4 800x800 size pictures will be reshaped into one picture with size 800x800
Q1.: but the anchor size is designed for the 800x800 size picture, do these anchors work for 4 small random sized pictures？
Q2: the network learns the feature of 4 combined pictures, does it work for the single 800x800 size pircture when testing
## Additional context

**Comment by glenn-jocher** [comment]
@zhaiyukun mosaic improves results on COCO. You can vary the mosaic hyperparameter here continuously from 0 to 1 to increase probability of using a mosaic on each image:
https://github.com/ultralytics/yolov5/blob/0070995bd58629d4628d11b1c8de9788aa55379b/data/hyp.scratch.yaml#L32

**Comment by TTLuze** [comment]
@zhaiyukun there is no resize operation in mosaic augment. In detail, four images (800*800) makes the mosaic images (1600*1600). Then, in function random_perspective(), Affine transformation or perspective transformation with dsize=(800, 800) is conducted on the mosaic images, obtaining part of mosaic images actually, rather than resize it.

**Comment by isomatical** [comment]
> @zhaiyukun there is no resize operation in mosaic augment. In detail, four images (800_800) makes the mosaic images (1600_1600). Then, in function random_perspective(), Affine transformation or perspective transformation with dsize=(800, 800) is conducted on the mosaic images, obtaining part of mosaic images actually, rather than resize it.

![train_batch0](https://user-images.githubusercontent.com/37702903/123499968-152d4600-d66d-11eb-8071-d3f4c18244e8.jpg)
The size of this mosaic image is 1280*1280 because I set --img-size 1280 in my training, which means that each image inside it has a resolution of around 426*426.

**Comment by glenn-jocher** [comment]
@isomatical no that's not correct. If you pass --img 1280 each mosaic is 1280x1280 and each image inside it is 1280 also before the scale jitter is applied:
https://github.com/ultralytics/yolov5/blob/9dc5d35fce4c768427e790f20d4b425ecad15d08/data/hyps/hyp.scratch.yaml#L27
