### ISSUE TITLE
How to improve performance of training of custom data using "plot_labels" info?

### ISSUE THREAD

**Issue by laisimiao** [ultralytics/yolov5#2287]
## ❔Question

How to improve performance of training of custom data using "plot_labels" info?
## Additional context
When I train yolov5 on custom data, I notice "plot_labels" function can save info about my dataset into "labels.jpg" and "labels_correlogram.jpg", but I don't know how to using these info to modify somewhere to improve my training and performance of model further? such as, I have a unbanlanced classes data.

**Comment by glenn-jocher** [comment]
@laisimiao yes, we provide many introspection tools in your training directory for images, labels, augmentations etc. That said, these are tools available to you, what you build with these tools or how you use them is up to you. In general your first step should be a sanity check, i.e. do the image look as you expect them to look, and if not then there may be problems in your dataset.
