### ISSUE TITLE
how to use different training dataset in each epoch

### ISSUE THREAD

**Issue by sunstudio** [ultralytics/yolov5#229]
I want to use different trianing dataset in each epoch, these  dataset are generated from a same dataset,  imgaug can do the image generation , but I don't know where to call imgarg in train.py?
Thanks a lot!

**Comment by glenn-jocher** [comment]
@sunstudio you can load a new dataset each epoch by placing the commands here within the epoch loop:
https://github.com/ultralytics/yolov5/blob/01895f3924313424e6c7d5189e5c264cdd2f3ed2/train.py#L201-L203

**Comment by sunstudio** [comment]
thank you !
