### ISSUE TITLE
label format

### ISSUE THREAD

**Issue by xiyufeng2** [ultralytics/yolov5#2293]
Box coordinates are in normalized xywh format (from 0 - 1). If your boxes are in pixels, divide x_center and w by image width, and y_center and h by image height.
        The image height here refers to the original size of the image or the resized size 416？？thank you！

**Comment by glenn-jocher** [comment]
@xiyufeng2 to normalize labels you would simply divide the existing coordinate system by its max value. The tutorial shows an example:
https://docs.ultralytics.com/yolov5/tutorials/train_custom_data/_edit

### 2. Create Labels

After using a tool like [CVAT](https://github.com/opencv/cvat), [makesense.ai](https://www.makesense.ai/) or [Labelbox](https://labelbox.com/)  to label your images, export your labels to **YOLO format**, with one `*.txt` file per image (if no objects in image, no `*.txt` file is required). The `*.txt` file specifications are:

- One row per object
- Each row is `class x_center y_center width height` format.
- Box coordinates must be in **normalized xywh** format (from 0 - 1). If your boxes are in pixels, divide `x_center` and `width` by image width, and `y_center` and `height` by image height.
- Class numbers are zero-indexed (start from 0).

<img width="800" alt="Image Labels" src="https://user-images.githubusercontent.com/26833433/91506361-c7965000-e886-11ea-8291-c72b98c25eec.jpg">

The label file corresponding to the above image contains 2 persons (class `0`) and a tie (class `27`):

<img width="475" src="https://user-images.githubusercontent.com/26833433/98809572-0bc4d580-241e-11eb-844e-eee756f878c2.png">

**Comment by LiberiFatali** [comment]
> ```
>     Box coordinates are in normalized xywh format (from 0 - 1). If your boxes are in pixels, divide x_center and w by image width, and y_center and h by image height.
>     The image height here refers to the **original size of the image or the resized size 416**？？thank you！
> ```

So I think it is the original size of the image.

**Comment by glenn-jocher** [comment]
@LiberiFatali yes, you are correct. The image height refers to the original size of the image, not the resized size of 416. If your boxes are in pixels, divide x_center and width (w) by the original image width, and y_center and height (h) by the original image height. Thank you!
