### ISSUE TITLE
Custom dataset training using YOLOv5

### ISSUE THREAD

**Issue by MrFahad** [ultralytics/yolov5#2296]
I am working on Real-Time Surveillance System based on Face Recognition in which I want to train my own custom dataset using YOLOv5.
 
I am using 100 different people images (100000). Each person images stored in different folder. 

Kindly guide me.
 
Hardware: details are as under:
                    Dell Precision 5510
                    RAM: 16 GB
                    SSD:  512 GB
                    GPU: M1000
Software:
                    Windows 10 Pro (64 bit)

**Comment by glenn-jocher** [comment]
@MrFahad sounds good! You can get started at https://docs.ultralytics.com/yolov5/tutorials/train_custom_data, and you might also want to think of using free Colab and Kaggle GPUs (see Environments in message above).

**Comment by MrFahad** [comment]
`

`

**Comment by MrFahad** [comment]
100%
67.7M/67.7M [00:00<00:00, 77.6MB/s]

replace ../coco/LICENSE? [y]es, [n]o, [A]ll, [N]one, [r]ename: N
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 6339M  100 6339M    0     0  43.9M      0  0:02:24  0:02:24 --:--:-- 31.9M
mv: cannot move './test2017' to './coco/images': No such file or directory

I am getting the above error in google colab "COCO test-dev2017"

**Comment by glenn-jocher** [comment]
@MrFahad to get started in a few clicks I would recommend the Colab notebook. To train COCO128 for example, simply run the Setup cell, and run the Train cell.
