### ISSUE TITLE
what the real output of the model?

### ISSUE THREAD

**Issue by Owen-Fish** [ultralytics/yolov5#230]
![image](https://user-images.githubusercontent.com/39903624/86003533-83343280-ba44-11ea-9024-2c6833241560.png)

Hello, thanks for your hardworking work! I have read these days, which enrich me a lot. but I have some wondering for you, hope u can help me out.

**First**: In "utils.py" module，when calculate the GIOU, I see the predicted pxy and pwh may not the same as the yolo papaer.
so that the prediction is definity not the offset of top-left corner (tx, ty, tw, th).  So could u tell me what the real meaning of the prediction.

**Second**: When I read the match strategy of anchor and ground truth. the the picture below.
![quara](https://user-images.githubusercontent.com/39903624/86004319-b75c2300-ba45-11ea-9307-836d9ed7a2f9.jpg)
for **part1**: this part you only use width and height infomation to filter out some un-closed ground truth for perticular feature map, this seems like obey the original paper for "each ground truth can match at most one anchor ". So what's your point?And on what basis?

for**part2**: I have totally no mind for this part, please tell me what's the reason for doing this.

Many thanks

**Comment by Owen-Fish** [comment]
@glenn-jocher please help me~~~~~~~~~www

**Comment by XiaoJiNu** [comment]
@Owen-Fish  Hi, I'm confused by this too,  do you konw it know？
