### ISSUE TITLE
YOLOV5S P6

### ISSUE THREAD

**Issue by bobbilichandu** [ultralytics/yolov5#2304]
## ❔Question
Where can I find yaml file for yolov5s-p6? 

## Additional context
Is it good practice to train yolov5sp6 at lower resolution?
Is it good practice to train yolov5p6 at 1280x1280 and test at lower resolutions like 704 or 768?

**Comment by glenn-jocher** [comment]
@chandu1263 yes, P6 helps mAP at resolutions from 640 to 1280 with COCO. If you train at 1280 you will still get good inference results at 768, but not vice versa. The yaml file is here (in compound scaled 1.0 1.0 size, which corresponds to YOLOv5l)
https://github.com/ultralytics/yolov5/blob/master/models/hub/yolov5-p6.yaml

**Comment by bobbilichandu** [comment]
This is for yolov5-p6 right?
I found [yolo5s6.yaml](https://github.com/ultralytics/yolov5/blob/master/models/hub/yolov5s6.yaml). 
Also, why are there anchors given in yolov5s-p6 and not in yolov5p6? yolov5s6 doesn't support autoanchoring?

**Comment by glenn-jocher** [comment]
@chandu1263 autoanchor automatically scans all models.
