### ISSUE TITLE
video ending early when running more than 60fps from gopro

### ISSUE THREAD

**Issue by Snitte** [ultralytics/yolov5#2305]
When i try to run a detect on a video from my goprohero4 silver if i set the gopro to film at more than 60 fps the program will exit the video after 83 frames at 90fps and at 112 frames at 120 fps every time in different videos with the same framerate. Ive tested with other 120 fps videos from other sources without issue

This is with the code running exactly as cloned from this git. with yolov5s weights

**Comment by glenn-jocher** [comment]
@Snitte duplicate of https://github.com/ultralytics/yolov5/issues/2064
