### ISSUE TITLE
Modeling step

### ISSUE THREAD

**Issue by Asma-94** [ultralytics/yolov5#2307]
## ❔Question
Hi, I have a problem with Modeling step,
I can't pass more than 100 epochs, the training held in 100, I need more than 100 epochs without hold,  how I can solve this problem?

**Comment by glenn-jocher** [comment]
@Asma-94 I'm sorry I don't understand. You can train any number of --epochs you want, i.e.:

```bash
python train.py --epochs 30
python train.py --epochs 300
python train.py --epochs 3000
```
