### ISSUE TITLE
yolov5: save weight during training in Google Drive

### ISSUE THREAD

**Issue by Leprechault** [ultralytics/yolov5#2308]
Hi Everyone!
I'd like to save yolov5 (`https://github.com/ultralytics/yolov5` repo) weight during training to `backup` folder in Google Drive in Google Colab, but if I try to:

```
from google.colab import drive
drive.mount('/content/drive', force_remount=True)
!rm /content/yolov5/yolov5/weights -r
!ln -s /content/drive/'My Drive'/backup 
```
The output is:

```
rm: cannot remove '/content/yolov5/yolov5/weights': No such file or directory
```
Please, any ideas for solve this?

**Comment by glenn-jocher** [comment]
@Leprechault you may have mixed up your paths. You can use the fileviewer on the left side of the Colab window to see your directory structure, including any mounted drives.

**Comment by Leprechault** [comment]
Thanks Glenn, I find in an another post that you comment in : (https://github.com/ultralytics/yolov5/issues/640), where 
@TaoXieSZ give an improvement to save checkpoints with the addiction in lines  458 to 464 modified for my with `backup` folder in Google Drive in train.py:
```
   if not opt.evolve:
        tb_writer = None
        if opt.local_rank in [-1, 0]:
           # Change the path here
            tb_writer = SummaryWriter(log_dir=increment_dir('/content/drive/My Drive/backup', opt.name))
        train(hyp, opt, device, tb_writer)
```
But is not so clear the exact position eg. before `# Set DDP variables`  or after  `# Resume`  in the train.py code. Could help me please again?

**Comment by glenn-jocher** [comment]
@Leprechault you can save checkpoints anywhere you want using the --project and --name arguments:

`python train.py --project PROJECT --name NAME`
saves to 
`./PROJECT/NAME`

**Comment by Leprechault** [comment]
Thanks again @glenn-jocher Works very well!!!!

**Comment by pillai-karthik** [comment]
Example:
!python train.py --img 416 --batch 16 --epochs 100 --data '../data.yaml' --cfg ./models/custom_yolov5s.yaml --weights '' --name yolov5s_results  --cache --project '../gdrive/MyDrive/' --name 'backup'
