### ISSUE TITLE
Docker Images Require Unreleased Linux Drivers

### ISSUE THREAD

**Issue by kidhasmoxy** [ultralytics/yolov5#231]
## 🐛 Bug
CUDA acceleration is not available when using the Docker images as the Dockerfile was updated to use 20.06-py3, which relies on Nvidia Drivers that not past release candidate/ beta stage. 

## To Reproduce (REQUIRED)

Attempt to start Docker image and you will see errors on platform support and how only CPU will be supported

Output:
```
ERROR: This container was built for NVIDIA Driver Release 450.36 or later, but
       version 440.100 was detected and compatibility mode is UNAVAILABLE.
       [[CUDA Driver UNAVAILABLE (cuInit(0) returned 804)]]
NOTE: MOFED driver for multi-node communication was not detected.
      Multi-node communication performance may be reduced.
Using CPU
```

## Expected behavior
GPU Acceleration is available on a stable channel released driver. 

## Environment

 - OS: Ubuntu 18.04 host
 - GPU Quadro P2000

## Additional context
Do we need any of the capabilities provided in the latest image or can we revert to the previous one, which depends on the latest stable driver release?

**Comment by glenn-jocher** [comment]
@kidhasmoxy thanks for the feedback! The 20.06 image was tested on a GCP VM without issue. Just in case though we've reverted the yolov5:latest image to 20.03. You should be able to pull this image now.

**Comment by sramirez** [comment]
I also have this problem with Nvidia driver release 440.100 which is the default driver provided by ubuntu-desktop-20.04.
