### ISSUE TITLE
in _ddp_init_helper     expect_sparse_gradient) RuntimeError: Model replicas must have an equal number of parameters.

### ISSUE THREAD

**Issue by AIYoungcino** [ultralytics/yolov5#2311]
在hpc上训练YOLOv5，单节点单卡可以运行，但单节点多卡，多节点多卡都会报错。

**Comment by AIYoungcino** [comment]
/public/software/apps/DeepLearning/PyTorch/rocm3.3_torch1.5/lib/python3.6/site-packages/torch/nn/parallel/distributed.py:303: UserWarning: Single-Process Multi-GPU is not the recommended mode for DDP. In this mode, each DDP instance operates on multiple devices and creates multiple module replicas within one process. The overhead of scatter/gather and GIL contention in every forward pass can slow down training. Please consider using one DDP instance per device or per module replica by explicitly setting device_ids or CUDA_VISIBLE_DEVICES. NB: There is a known issue in nn.parallel.replicate that prevents a single DDP instance to operate on multiple model replicas.
  "Single-Process Multi-GPU is not the recommended mode for "
Namespace(adam=False, batch_size=16, bucket='', cache_images=False, cfg='./models/yolov5x.yaml', data='./data/mydata.yaml', device='1', epochs=300, img_size=[640], multi_scale=False, name='', noautoanchor=False, nosave=False, notest=False, rect=False, single_cls=False, weights='weights/last.pt')
Using CUDA device0 _CudaDeviceProperties(name='Device 66a1', total_memory=16368MB)
           device1 _CudaDeviceProperties(name='Device 66a1', total_memory=16368MB)
           device2 _CudaDeviceProperties(name='Device 66a1', total_memory=16368MB)
           device3 _CudaDeviceProperties(name='Device 66a1', total_memory=16368MB)

**Comment by NanoCode012** [comment]
@xioyung, pull latest code base and check Multi-GPU Tutorial https://docs.ultralytics.com/yolov5
