### ISSUE TITLE
Speed Results for Yolov5x not consistent in Colab with official table

### ISSUE THREAD

**Issue by rickymedrano** [ultralytics/yolov5#2312]
## ❔Question
In the main readme, it shows the speed of yolov5x on a v100 is 6ms. I'm using the official Colab notebook and ran the #Reproduce section. The GPU of my instance is a T4 which has a compute capability of 7.5 while the V100 has 7.0
I'm getting 20ms for speed (you can tell it's yolov5x from the 218GLOPS). 
![yolov5xt4](https://user-images.githubusercontent.com/13972065/109376735-843f8d00-787b-11eb-9efc-c1dc25101ea2.png)
I also tested the same call on my RTX 2070 and get 12.9ms
![mine](https://user-images.githubusercontent.com/13972065/109376770-c5d03800-787b-11eb-8b3e-950740b75e34.png)
Both these cards have more compute capability than the V100 yet are running slower speed than the claimed 6.0ms in the table.
I don't have Colab Pro so can't specifcally check out a V100 to test this but wanted to see if others are experiencing slower than 6.0ms speed on cards with better compute capability than the V100?

output of `git log -1`:
commit 404749a33cc29d119f54b2ce35bf3b33a847a487 (HEAD -> master)
...

I also tested yolov5s and get fairly close results to the speed table:
Colab w/ T4: 4.5ms
RTX 2070: 2.5ms

**Comment by glenn-jocher** [comment]
@rickymedrano hey buddy. I think you have a misunderstanding of relative GPU speeds, a V100 is a much faster GPU than a T4, and is also slightly faster than the best 3090 consumer GPU. The benchmark speeds logically require similar hardware to reproduce, i.e. an n1-standard-8 instance on GCP or a p3 instance on AWS, which you can get started with via the environment quickstart guides below.

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>
