### ISSUE TITLE
How to continue a training

### ISSUE THREAD

**Issue by MolchanovYA** [ultralytics/yolov5#2314]
## ❔Question
Hello!

Could you please tell me a way to continue training?

## Additional context

I want to continue training my model after 100 completed epochs.

!python train.py --img 640 --batch 16 --epochs 100 --data mydata.yaml --weights /content/yolov5/model_100e.pt --cache --adam --nosave 

where model_100e.pt is /content/yolov5/runs/train/exp1/weights/last.pt file after first training. Before finishing of first 100 epochs P,R and mAP was better with each epoch (for example 97e mAP = 0.172, 98e mAP = 0.173, ,99e mAP = 0.174).
But after continuing training i get low results (for example 0e mAP = 0.0272, 1e mAP = 0.000552, 2e mAP 0.000162 and so on).
It seems that the training did not continue with the weights obtained after first training, but began anew.
Could you please comment it? I cannot train a model for a long time because of server limitation and trying to train with short series, for example 100 epochs. Thank you for reply!

**Comment by NanoCode012** [comment]
See https://github.com/ultralytics/yolov5/blob/cbd55da5d24becbe3b94afaaa4cdd1187a512c3f/train.py#L453

**Comment by MolchanovYA** [comment]
Including --resume cannot help me. As i see this parameter only for interrupted training. In my case i have this message


Traceback (most recent call last):
  File "train.py", line 531, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 164, in train
    assert start_epoch > 0, '%s training to %g epochs is finished, nothing to resume.' % (weights, epochs)
AssertionError: ./runs/train/exp3/weights/last.pt training to 100 epochs is finished, nothing to resume.

**Comment by MolchanovYA** [comment]
First training for 100 epochs. log of 90-99
     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
     90/99     14.1G   0.05672   0.01855   0.02626    0.1015        14       640: 100%|██████████| 752/752 [04:48<00:00,  2.61it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 94/94 [00:32<00:00,  2.87it/s]
                 all    2.98e+03     6.9e+03       0.285       0.247        0.17      0.0669
     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
     91/99     14.1G   0.05731   0.01876   0.02678    0.1028         8       640: 100%|██████████| 752/752 [04:48<00:00,  2.61it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 94/94 [00:32<00:00,  2.87it/s]
                 all    2.98e+03     6.9e+03       0.288       0.247       0.171      0.0674
     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
     92/99     14.1G   0.05692   0.01905   0.02658    0.1025         8       640: 100%|██████████| 752/752 [04:48<00:00,  2.61it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 94/94 [00:32<00:00,  2.87it/s]
                 all    2.98e+03     6.9e+03       0.286       0.248       0.172      0.0674
     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
     93/99     14.1G   0.05623   0.01876    0.0262    0.1012        14       640: 100%|██████████| 752/752 [04:48<00:00,  2.61it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 94/94 [00:32<00:00,  2.87it/s]
                 all    2.98e+03     6.9e+03        0.29       0.245       0.172      0.0675
     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
     94/99     14.1G   0.05652   0.01875   0.02624    0.1015         7       640: 100%|██████████| 752/752 [04:48<00:00,  2.61it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 94/94 [00:32<00:00,  2.86it/s]
                 all    2.98e+03     6.9e+03       0.285       0.247       0.172      0.0675
     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
     95/99     14.1G   0.05648   0.01853   0.02627    0.1013        17       640: 100%|██████████| 752/752 [04:48<00:00,  2.61it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 94/94 [00:32<00:00,  2.87it/s]
                 all    2.98e+03     6.9e+03        0.29       0.244       0.173      0.0676
     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
     96/99     14.1G   0.05669   0.01846   0.02627    0.1014         4       640: 100%|██████████| 752/752 [04:48<00:00,  2.61it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 94/94 [00:32<00:00,  2.87it/s]
                 all    2.98e+03     6.9e+03       0.289       0.244       0.173      0.0677
 Epoch   gpu_mem       box       obj       cls     total   targets  img_size
     97/99     14.1G   0.05652   0.01845   0.02647    0.1014         3       640: 100%|██████████| 752/752 [04:48<00:00,  2.60it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 94/94 [00:33<00:00,  2.85it/s]
                 all    2.98e+03     6.9e+03       0.287       0.246       0.173      0.0677
     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
     98/99     14.1G   0.05682   0.01831   0.02687     0.102         6       640: 100%|██████████| 752/752 [04:48<00:00,  2.60it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 94/94 [00:32<00:00,  2.86it/s]
                 all    2.98e+03     6.9e+03       0.287       0.245       0.173      0.0681
     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
     99/99     14.1G   0.05638   0.01805   0.02572    0.1001         6       640: 100%|██████████| 752/752 [04:48<00:00,  2.60it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 94/94 [00:37<00:00,  2.53it/s]
                  all    2.98e+03     6.9e+03       0.286       0.246       0.173      0.0677

Continue with pretrained weights  (--weights /content/yolov5/model_100e.pt) and get this results in first 10 epochs

Starting training for 100 epochs...
     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
      0/99     13.6G   0.05942   0.01881    0.0274    0.1056         9       640: 100%|██████████| 752/752 [05:24<00:00,  2.32it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 94/94 [00:34<00:00,  2.72it/s]
                 all    2.98e+03     6.9e+03       0.134       0.136      0.0272     0.00767
Images sizes do not match. This will causes images to be display incorrectly in the UI.
     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
      1/99     14.3G    0.0626    0.0202   0.02926    0.1121        23       640: 100%|██████████| 752/752 [04:59<00:00,  2.51it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 94/94 [00:26<00:00,  3.49it/s]
                 all    2.98e+03     6.9e+03      0.0213     0.00185    0.000552    6.23e-05
     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
      2/99     14.3G   0.06353   0.02052   0.02998     0.114         7       640: 100%|██████████| 752/752 [04:51<00:00,  2.58it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 94/94 [02:38<00:00,  1.68s/it]
                 all    2.98e+03     6.9e+03     0.00084      0.0648    0.000162    3.41e-05
     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
      3/99     14.3G   0.06326    0.0209   0.03011    0.1143         7       640: 100%|██████████| 752/752 [04:48<00:00,  2.61it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 94/94 [00:29<00:00,  3.13it/s]
                 all    2.98e+03     6.9e+03       0.611      0.0192     0.00578     0.00165
     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
      4/99     14.3G   0.06248   0.02018   0.02914    0.1118        13       640: 100%|██████████| 752/752 [04:47<00:00,  2.61it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 94/94 [00:24<00:00,  3.79it/s]
                 all    2.98e+03     6.9e+03      0.0252     0.00434     0.00103    0.000354
     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
      5/99     14.3G   0.06191   0.02018   0.02921    0.1113        35       640: 100%|██████████| 752/752 [04:47<00:00,  2.61it/s]


mAP is very low. Looks like training for the first time without pretrained model.
 In my opinion, the results at the start of second training should be comparable to the results at the end of first training. But it is not so.

**Comment by NanoCode012** [comment]
> Including --resume cannot help me. As I see this parameter only for interrupted training. 

I see. I misread your post. I recommend that you just set it to run to a high enough epoch, then let it run till it reaches the limit (100 in your case). Then you `--resume` it when you can to let it continue on. Then rinse and repeat.

**Comment by rightmouse** [comment]
Could he just use the last.pt from the first run as the weight for another run of 100 epochs?
Train to 200 epochs compared to training for 100 epochs, then using that model as the weight for another 100 epochs.  

Would that be the same, or do layers get frozen when using it as a transfer-learning weight?

**Comment by glenn-jocher** [comment]
@rightmouse no layers are frozen during training. The main obstacle to resuming a completed run is that the learning rate is on a specific schedule that's defined by --epochs, from max LR to min LR over epoch 0 to final epoch.

**Comment by MolchanovYA** [comment]
@glenn-jocher is it useless to train next 100 epochs after first 100 epochs? Does the retrained model inherit the experience of the first model?

**Comment by glenn-jocher** [comment]
@MolchanovYA you can start a new training from any pretrained checkpoint you want:
`python train.py --weights any_YOLOv5_checkpoint.pt`

**Comment by MolchanovYA** [comment]
@glenn-jocher this is what I do, but why are the initial metrics of the quality of retraining incomparably worse than the metrics of the first training? What is the difference between the first epoch of retraining after 100 completed epochs and 101 epochs of an incomplete series of for example 200 epochs?

**Comment by glenn-jocher** [comment]
@MolchanovYA LR scheduler resets when starting a new training run.

**Comment by not-nam-or-am-i** [comment]
This is the command that I tried and worked for me:
`!python train.py --img 320 --epochs 300 --data data.yaml --resume 'path/to/last/weight/last.pt' --weights 'path/to/last/weight/last.pt'`

**Comment by glenn-jocher** [comment]
Resuming an interrupted training run is simple. There are two options:
```bash
python train.py --resume  # resume latest training
python train.py --resume path/to/last.pt  # specify resume checkpoint
```

If you started the training with a multi-GPU command then you must resume it with the same exact configuration (and vice versa). Multi-GPU resume commands are here, assuming you are using 8 GPUs:
```bash
python -m torch.distributed.launch --nproc_per_node 8 train.py --resume  # resume latest training
python -m torch.distributed.launch --nproc_per_node 8 train.py --resume path/to/last.pt  # specify resume checkpoint
```

Note that you may not change any settings when resuming, you must resume with the same exact settings (`--epochs`, `--batch`, `--data`, etc).

**Comment by aviezab** [comment]
> @glenn-jocher this is what I do, but why are the initial metrics of the quality of retraining incomparably worse than the metrics of the first training? What is the difference between the first epoch of retraining after 100 completed epochs and 101 epochs of an incomplete series of for example 200 epochs?

I have facing same issue here when retrain a finished model.
I thought `--resume` will resume the training, but since the epoch was finished it is not going.

So I started a new one with latest checkpoint with 0.6 mAP, but after retrain it is worse.
The mAP is reduced from 0.6 to 0.3, and doing `detect.py` didn't detect anything. The model from before further better and detect all object trained.

It is better to start new one from the beginning although much longer.

**Comment by gembancud** [comment]
Hello, 
I am currently using a larger binary dataset to pretrain my model before it gets trained on a smaller dataset with more classes. When I use the best.pt from the training run the epoch counts are inherited; If I stopped at epoch 300, the next training would start at "300/n" . Do I need to pass a certain flag to reset the epoch counter?

**Comment by glenn-jocher** [comment]
@gembancud 👋 Hello! Thanks for asking about **resuming training**. YOLOv5 🚀 Learning Rate (LR) [schedulers](https://github.com/ultralytics/yolov5/blob/9f3a388cea66ca71b9bbe057929eed8fbc920a7e/train.py#L109-L142) follow predefined LR curves for the fixed number of `--epochs` defined at training start (`default=300`), and are designed to fall to a minimum LR on the final epoch for best training results. For this reason you can not modify the number of epochs once training has started.

<img width="850" alt="LR Curves" src="https://user-images.githubusercontent.com/26833433/119332195-8e113a80-bc88-11eb-8eb7-7494ff1d5c01.png">

If your training was **interrupted** for any reason you may continue where you left off using the `--resume` argument. If your training fully completed, you can start a **new** training from any model using the `--weights` argument. Examples:

## Resume Single-GPU

You may not change settings when resuming, and **no additional arguments** other than `--resume` should be passed, with an optional path to the checkpoint you'd like to resume from. If no checkpoint is passed the most recently updated `last.pt` in your `yolov5/` directory is automatically found and used:
```bash
python train.py --resume  # automatically find latest checkpoint (searches yolov5/ directory)
python train.py --resume path/to/last.pt  # specify resume checkpoint
```

## Resume Multi-GPU

[Multi-GPU DDP trainings](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) must be resumed with the same GPUs and DDP command, i.e. assuming 8 GPUs:
```bash
python -m torch.distributed.run --nproc_per_node 8 train.py --resume  # resume latest checkpoint
python -m torch.distributed.run --nproc_per_node 8 train.py --resume path/to/last.pt  # specify resume checkpoint
```

## Start from Pretrained

If you would like to **start training** from a fully trained model, use the `--weights` argument, not the `--resume` argument:
```bash
python train.py --weights path/to/best.pt  # start from pretrained model
```

Good luck and let us know if you have any other questions!

**Comment by gembancud** [comment]
I take it that there is an internal flag raised once training is completed no? (current epoch count reaches the final epoch count)
I was pretraining the larger dataset but prematurely ended it since full pretraining was very time-consuming (will resume soon) just to see if it could boost performance on the smaller dataset (so far, it does by a large margin).  Cheers!

**Comment by glenn-jocher** [comment]
@gembancud yes, you can run `strip_optimizer()` on any checkpoint to complete it's training and turn it into official pretrained weights:
https://github.com/ultralytics/yolov5/blob/7207fe95e5dc368e4402134148c5d0c35361ad88/utils/general.py#L732-L746

**Comment by dhruvildave22** [comment]
Hello!
Can anybody resolve my confusion about continuing training on the best.pt after running all EPochs successfully?

I have trained my yolov5s.pt models with coco + custom dataset for 65 EPOCHS and it create a best.pt models. I want to run more EPochs on this to get better precision and recall, so i started training best.pt which already has 65 Epochs. Earlier i thought that If i start training on best.pt, it should run from 66th EPoch but after seeing results of precision and recall value, I assume that it starts fresh again.
I tried --resume but it can be only used if the training gets interrupted.
Is there any way where i can start the training from where i finished with best.pt?

Thanks
Dhruvil Dave

**Comment by glenn-jocher** [comment]
@dhruvildave22 👋 Hello! Thanks for asking about **resuming training**. YOLOv5 🚀 Learning Rate (LR) [schedulers](https://github.com/ultralytics/yolov5/blob/9f3a388cea66ca71b9bbe057929eed8fbc920a7e/train.py#L109-L142) follow predefined LR curves for the fixed number of `--epochs` defined at training start (`default=300`), and are designed to fall to a minimum LR on the final epoch for best training results. For this reason you can not modify the number of epochs once training has started.

<img width="850" alt="LR Curves" src="https://user-images.githubusercontent.com/26833433/119332195-8e113a80-bc88-11eb-8eb7-7494ff1d5c01.png">

If your training was **interrupted** for any reason you may continue where you left off using the `--resume` argument. If your training fully completed, you can start a **new** training from any model using the `--weights` argument. Examples:

## Resume Single-GPU

You may not change settings when resuming, and **no additional arguments** other than `--resume` should be passed, with an optional path to the checkpoint you'd like to resume from. If no checkpoint is passed the most recently updated `last.pt` in your `yolov5/` directory is automatically found and used:
```bash
python train.py --resume  # automatically find latest checkpoint (searches yolov5/ directory)
python train.py --resume path/to/last.pt  # specify resume checkpoint
```

## Resume Multi-GPU

[Multi-GPU DDP trainings](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) must be resumed with the same GPUs and DDP command, i.e. assuming 8 GPUs:
```bash
python -m torch.distributed.run --nproc_per_node 8 train.py --resume  # resume latest checkpoint
python -m torch.distributed.run --nproc_per_node 8 train.py --resume path/to/last.pt  # specify resume checkpoint
```

## Start from Pretrained

If you would like to **start training** from a fully trained model, use the `--weights` argument, not the `--resume` argument:
```bash
python train.py --weights path/to/best.pt  # start from pretrained model
```

Good luck 🍀 and let us know if you have any other questions!
