### ISSUE TITLE
YOLOv5 and instance segmentation

### ISSUE THREAD

**Issue by a-esp-1** [ultralytics/yolov5#2316]
## ❔Question

Is possible to adapt YOLOv5 to instance segmentation instead object detection? Have you think in working with this idea?

Thank you.

**Comment by glenn-jocher** [comment]
@a-esp-1 hi thanks for asking. Segmentation networks rely on an hourglass architecture that scales down and then scales back up feature maps. It's something that's implementable but that we just haven't had time to experiment with.

We have been implementing segmentation label capability though, which is now in master, so we're slowly laying some of the groundwork for this capability.
