### ISSUE TITLE
Question about image preprocessing

### ISSUE THREAD

**Issue by erickim555** [ultralytics/yolov5#2318]
## ❔Question
Quick question: is the following correct about image preprocessing for YoloV5 models?

Images are input to YoloV5 models as:
- shape=[num_images, num_channels, img_height, img_width]
- float32 dtype (except for half() mode)
- pixel intensity values within [0.0, 1.0]
- RGB channel order.
- NO mean/std centering

I'm ~95% sure that this is accurate after looking through the code, but I thought that I'd ask just in case. Thanks!

Also: thank you for putting in this work! :)

**Comment by glenn-jocher** [comment]
@erickim555 you can see the preprocessing steps in the autoshape forward method here for pytorch hub versions of YOLOv5. It's all handled in a few short lines of code, starting from inputting images filenames (or various other input formats) directly for inference.

https://github.com/ultralytics/yolov5/blob/dfeec198cbb0d19bf06a26e3712b7825f993fc47/models/common.py#L183-L219

**Comment by erickim555** [comment]
@glenn-jocher Got it, it does look like my understanding is correct, eg no mean centering, [0.0, 1.0] pixel intensity values, RGB channel ordering. Thank you for the response!
