### ISSUE TITLE
Is SyncBN adopted in the reported experiments?

### ISSUE THREAD

**Issue by Joker316701882** [ultralytics/yolov5#2321]
## ❔Question
Hi @glenn-jocher. Thank you for sharing such an amazing work! But I would like to know is SyncBN adopted in the experiments reported below?

| Model | size | AP<sup>val</sup> | AP<sup>test</sup> | AP<sub>50</sub> | Speed<sub>V100</sub> | FPS<sub>V100</sub> || params | GFLOPS |
|---------- |------ |------ |------ |------ | -------- | ------| ------ |------  |  :------: |
| [YOLOv5s](https://github.com/ultralytics/yolov5/releases)    |640 |36.8     |36.8     |55.6     |**2.2ms** |**455** ||7.3M   |17.0
| [YOLOv5m](https://github.com/ultralytics/yolov5/releases)    |640 |44.5     |44.5     |63.1     |2.9ms     |345     ||21.4M  |51.3
| [YOLOv5l](https://github.com/ultralytics/yolov5/releases)    |640 |48.1     |48.1     |66.4     |3.8ms     |264     ||47.0M  |115.4
| [YOLOv5x](https://github.com/ultralytics/yolov5/releases)    |640 |**50.1** |**50.1** |**68.7** |6.0ms     |167     ||87.7M  |218.8
| | | | | | | || |
| [YOLOv5x](https://github.com/ultralytics/yolov5/releases) + TTA |832 |**51.9** |**51.9** |**69.6** |24.9ms |40      ||87.7M  |1005.3

**Comment by glenn-jocher** [comment]
@Joker316701882 you can train with sync batchnorm using the --sync argument:
```
python train.py --sync-bn
```

But no, we did not use it when training the official models.

**Comment by Joker316701882** [comment]
@glenn-jocher Thank you for your quick response!
