### ISSUE TITLE
Conversion to CoreML fails when running with --batch 2

### ISSUE THREAD

**Issue by guy4261** [ultralytics/yolov5#2322]
Hello! I'm trying to convert a model with batchsize of 2. This is with latest CoreML built from their `master` (per your suggestion in other threads).

1. Converting to batch > 1 results in a CoreML error: `generic_reshape_kernel: Invalid bottom shape (80 80 255 1 1) for reshape to (80 80 85 3 2)`.

2. Despite the error, the script acts as if the conversion worked well (it did - torch -> torchscript -> onnx, but not to coreml).

Repro:

```
$ git pull  # using your latest master
$ python models/export.py --batch 2
...
Translating MIL ==> MLModel Ops: 100%|███████████████████████████████████████████████████████| 686/686 [00:01<00:00, 654.18 ops/s]
/Users/grapaport/ms/lib/python3.6/site-packages/coremltools/models/model.py:118: RuntimeWarning:
You will not be able to run predict() on this Core ML model.
Underlying exception message was:
Error compiling model:
"compiler error:  Espresso exception: "Invalid argument":
generic_reshape_kernel: Invalid bottom shape (80 80 255 1 1) for reshape to (80 80 85 3 2)".
  RuntimeWarning,
CoreML export success, saved as ./yolov5s.mlmodel

Export complete (14.63s). Visualize with https://github.com/lutzroeder/netron.
```

**Comment by glenn-jocher** [comment]
@guy4261 export works correctly for me in Colab, unable to reproduce.

```python
!git clone https://github.com/ultralytics/yolov5  # clone repo
%cd yolov5
%pip install -qr requirements.txt coremltools  # install dependencies

import torch
from IPython.display import Image, clear_output  # to display images

clear_output()
print('Setup complete. Using torch %s %s' % (torch.__version__, torch.cuda.get_device_properties(0) if torch.cuda.is_available() else 'CPU'))

!python models/export.py --batch 2
```

**Comment by glenn-jocher** [comment]
It appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below. 


## Requirements

**Python 3.8** or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including **`torch>=1.7`**. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by guy4261** [comment]
Thanks @glenn-jocher , will check.

I'm getting zero exitcode for `!python models/export.py --batch 2` as well, still I get this error.

Thanks for the effort of running this - but did you also try to load the CoreML converted model and infer over a batch of 2 images? I will try this from scratch and report. There's the "status" badge saying `export.py` was tested - but where are those tests defined? Can't find them in the repo.

Thanks again!

**Comment by guy4261** [comment]
EDIT: works in Colab for me. I'll keep this issue open until I figure out what happened in my local environment (OS X 10.15) and update here. My apologies!

**Comment by glenn-jocher** [comment]
@guy4261 ah yes, CI tests run export.py but since coremltools is not part of requirements the export is skipped here (under Tests Workflow):
https://github.com/ultralytics/yolov5/runs/1996038442?check_suite_focus=true

**Comment by guy4261** [comment]
I started a docker container of `ultralytics/yolov5:latest` on my machine.

I `pip install`ed the requirements for CoreML conversion.

Conversion finishes well (`python models/export.py --batch 2`), with no warning messages.

However, when I copy the model (`docker cp`) outside and try to load it using `coremltools`, I get an error:

```python
>>> import coremltools as ct

>>> model = ct.models.MLModel("yolov5s.mlmodel")
~/miniconda3/envs/py38/lib/python3.8/site-packages/coremltools/models/model.py:114: RuntimeWarning: You will not be able to run predict() on this Core ML model. Underlying exception message was: Error compiling model: "compiler error:  Espresso exception: "Invalid argument": generic_reshape_kernel: Invalid bottom shape (80 80 255 1 1) for reshape to (80 80 85 3 2)".
  _warnings.warn(
```

Not sure if there is anything you can do about it, but things seem broken right now :(

BTW - when I load the model on the docker image, I'm not getting any errors; however the model is not usable on Linux anyway as this is how CoreML works (trying to `model.predict()` I get: `Exception: Model prediction is only supported on macOS version 10.13 or later.`).

@glenn-jocher please close if you consider this irreproducible or something that should not be fixed. Thanks!

**Comment by glenn-jocher** [comment]
@guy4261 we have fully working CoreML export pipelines and reference solutions (i.e. iDetection source code) for business clients, but these are all batch-size 1 solutions. 

I'm not actually aware of any batched inference examples for iOS, and it's also unclear to me what performance difference you might see at batch sizes larger than 1 on the ANE. The lowest risk implementation pipeline might of course be to run inference in a swift `for` loop for whatever contents you need.

**Comment by guy4261** [comment]
Thanks! Closing this, then.
