### ISSUE TITLE
How to create a file similar to yolov5x.pt from a trained model best.pt 

### ISSUE THREAD

**Issue by hoangcuongbk80** [ultralytics/yolov5#2323]
## ❔Question
Hi,

Thanks for your work. It's great!

I wonder that how can create a file similar to yolov5x.pt from a trained model best.pt?

The best.pt was trained for 2 object classes
I want to use this best.pt to retrain a new model with more classes.

**Comment by glenn-jocher** [comment]
@hoangcuongbk80 you can use your trained model `best.pt` as the starting point for a new training the same way you use the official models:

```bash
python train.py --data custom.yaml --weights yolov5x.pt
python train.py --data custom.yaml --weights best.pt  # <-- works the same as yolov5x.pt
```

**Comment by hoangcuongbk80** [comment]
@glenn-jocher Thanks for the quick reply.

I tried 

`python -m torch.distributed.launch --nproc_per_node 6 train.py --img 1024 --batch-size 48 --epochs 300 --data mydata.yaml --weights best.pt --device 2,3,4,5,6,7` 

and get the error:

![1](https://user-images.githubusercontent.com/10355081/109433351-30b27800-7a10-11eb-9c38-e765d810934a.png)

**Comment by glenn-jocher** [comment]
@hoangcuongbk80 command looks fine, everything should work. 

Since you are having problems its likely that your model or your YOLOv5 code are out of date. You should git clone a clean copy and if necessary retrain a new best.pt.
