### ISSUE TITLE
Ensemble with 4 models

### ISSUE THREAD

**Issue by ptran1203** [ultralytics/yolov5#2324]
## ❔Question
What are the maximum models for ensembling? I've train 4 models Yolov5x correspond to 4 folds and combine the final prediction by running

```%bash
!python3 detect.py --weights fold0.pt fold1.pt fold2.pt fold3.pt\
                --img 640\
                --conf 0.01\
                --iou 0.5\
                --source /test\
                --save-txt --save-conf --exist-ok\
                --augment
```
But the ensemble of 4 folds got the worst result, the mAP as follows:

|Model| mAP@0.4|
|--|--|
| Single Fold0 | 0.121 |
| Single Fold1 | 0.127 |
| Single Fold2 | 0.123 |
| Single Fold3 | 0.125 |
| Ensemble of fold 0, 1 | 0.139 |
| Ensemble of fold 0, 1, 2 | 0.153 |
| Ensemble of fold 0, 1, 2, 3| 0.104 |

And then, I check the `detect.py`, it loads the weight by function attemp_load, I found the comment in the code:\

```# Loads an ensemble of models weights=[a,b,c] or a single model weights=[a] or weights=a```

Does **weights=[a,b,c]** indicate that I can only run ensemble for at most 3 models?

**Comment by glenn-jocher** [comment]
@ptran1203 there is no limit on the number of models you can ensemble. If your hardware allows it you can ensemble a thousand models using our code.

Increasing performance is a different matter, **there is no guarantee than more models equals better results**. For example an ensemble of YOLOv5s and YOLOv5x together will produce worse results than YOLOv5x by itself because you are mixing good with bad.

The ensembles are NMS-level ensembles, meaning each new model appends it's results to the group, and then these all pass through NMS togethor.

**Comment by glenn-jocher** [comment]
@ptran1203 also another item to be aware of are the NMS settings. If you are ensembling many models you may want to increase the max detections and max nms thresholds:
https://github.com/ultralytics/yolov5/blob/c2026a5f35fd632c71b10fdbaf9194e714906f02/utils/general.py#L404-L412

**Comment by ptran1203** [comment]
Thank you for your quick response, I'll try your suggestion

**Comment by glenn-jocher** [comment]
@ptran1203 you should remember that the above ensembling technique is just one of many, you can enable others by uncommenting their lines instead, i.e. you can try mean ensemble, max ensemble etc here (these require identical model architecture output layers/shapes though, nms ensemble does not):
https://github.com/ultralytics/yolov5/blob/c2026a5f35fd632c71b10fdbaf9194e714906f02/models/experimental.py#L98-L111

To verify I ran again in Colab my experiment and observed results as expected:
```python
# Run YOLOv5x on COCO val2017
!python test.py --weights yolov5x.pt --data coco.yaml --img 640 --iou 0.7

# Run YOLOv5s YOLOv5x ensemble on COCO val2017
!python test.py --weights yolov5x.pt yolov5s.pt --data coco.yaml --img 640 --iou 0.7
```

```bash
Namespace(augment=False, batch_size=32, conf_thres=0.001, data='./data/coco.yaml', device='', exist_ok=False, img_size=640, iou_thres=0.7, name='exp', project='runs/test', save_conf=False, save_hybrid=False, save_json=True, save_txt=False, single_cls=False, task='val', verbose=False, weights=['yolov5x.pt'])
YOLOv5 v4.0-108-gc2026a5 torch 1.7.1+cu101 CUDA:0 (Tesla V100-SXM2-16GB, 16160.5MB)

Fusing layers... 
Model Summary: 476 layers, 87730285 parameters, 0 gradients, 218.8 GFLOPS
val: Scanning '../coco/val2017' for images and labels... 4952 found, 48 missing, 0 empty, 0 corrupted: 100% 5000/5000 [00:01<00:00, 2816.74it/s]
val: New cache created: ../coco/val2017.cache
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100% 157/157 [01:35<00:00,  1.64it/s]
                 all       5e+03    3.63e+04       0.743       0.619       0.677       0.484
Speed: 5.2/2.0/7.2 ms inference/NMS/total per 640x640 image at batch-size 32

Evaluating pycocotools mAP... saving runs/test/exp3/yolov5x_predictions.json...
loading annotations into memory...
Done (t=0.97s)
creating index...
index created!
Loading and preparing results...
DONE (t=6.15s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=106.69s).
Accumulating evaluation results...
DONE (t=17.27s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.502
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.684
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.548
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.339
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.549
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.638
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.378
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.630
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.687
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.524
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.737
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.832
Results saved to runs/test/exp3
Namespace(augment=False, batch_size=32, conf_thres=0.001, data='./data/coco.yaml', device='', exist_ok=False, img_size=640, iou_thres=0.7, name='exp', project='runs/test', save_conf=False, save_hybrid=False, save_json=True, save_txt=False, single_cls=False, task='val', verbose=False, weights=['yolov5x.pt', 'yolov5s.pt'])
YOLOv5 v4.0-108-gc2026a5 torch 1.7.1+cu101 CUDA:0 (Tesla V100-SXM2-16GB, 16160.5MB)

Fusing layers... 
Model Summary: 476 layers, 87730285 parameters, 0 gradients, 218.8 GFLOPS
Fusing layers... 
Model Summary: 224 layers, 7266973 parameters, 0 gradients, 17.0 GFLOPS
Ensemble created with ['yolov5x.pt', 'yolov5s.pt']

val: Scanning '../coco/val2017.cache' for images and labels... 4952 found, 48 missing, 0 empty, 0 corrupted: 100% 5000/5000 [00:00<00:00, 47233153.15it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100% 157/157 [01:50<00:00,  1.42it/s]
                 all       5e+03    3.63e+04       0.724       0.601       0.658       0.472
Speed: 6.2/4.1/10.3 ms inference/NMS/total per 640x640 image at batch-size 32

Evaluating pycocotools mAP... saving runs/test/exp4/yolov5x_predictions.json...
loading annotations into memory...
Done (t=0.51s)
creating index...
index created!
Loading and preparing results...
DONE (t=7.89s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=124.86s).
Accumulating evaluation results...
DONE (t=22.63s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.491
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.664
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.538
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.330
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.543
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.627
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.375
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.624
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.684
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.504
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.738
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.831
Results saved to runs/test/exp4
```

**Comment by ptran1203** [comment]
@glenn-jocher , Do `mean` and `max` ensemble calculating the mean and max of both confident score and box coordinates?

**Comment by glenn-jocher** [comment]
@ptran1203 yes, mean ensemble and max ensemble execute those operations through the ensemble dimension. In our tests they did not work as well as NMS ensemble, but you may want to test in your application to see if they work better.

**Comment by maheshmechengg** [comment]
> @ptran1203 yes, mean ensemble and max ensemble execute those operations through the ensemble dimension. In our tests they did not work as well as NMS ensemble, but you may want to test in your application to see if they work better.

This is really great! I tired with my yolov5-m & L model & got as below:
![image](https://user-images.githubusercontent.com/49720282/110076333-4e823300-7daa-11eb-8df5-e46399dae1d9.png)
mAP .5 of 0.961 mAP .5: 0.95 0.861 is good i guess...
How i can use this further for the predictions ? Kindly please let me know

**Comment by glenn-jocher** [comment]
@maheshmechengg yes, seems to be working well!

You can use model ensembling for predictions also by passing multiple models to detect.py:
```
python detect.py --weights model1.pt model2.pt model3.pt etc...
```
