### ISSUE TITLE
Training on images with one channel.

### ISSUE THREAD

**Issue by oclerc** [ultralytics/yolov5#2328]
## ❔Question
Hi everyone, 
I'm currently training on a set of thermal images that only have one channel. Could I change the .yaml model file in order to make it optimized for this? I would expect the model to be faster if I don't always process the same image three times. 

Thanks for the help!

**Comment by glenn-jocher** [comment]
@oclerc speedups due to minor variations in input channel counts are misconception. In reality any gains will be immaterial, and the cv2 dataloader should already handle greyscale images (by converting them to 3 channel), so I would just train normally in your case.
