### ISSUE TITLE
Questions about setting the right epoch

### ISSUE THREAD

**Issue by leeyunhome** [ultralytics/yolov5#2334]
## ❔Question

https://github.com/ultralytics/yolov5/issues/1633#issuecomment-740664533
Hi

I read an article about early termination, but I don't understand, so I ask again.
In order to minimize the capacity of the learned weight file (.pt), I want it to be terminated early when learning is well done.

How can I close it early?

Should I watch? Or does the learning end automatically?

**Comment by glenn-jocher** [comment]
@leeyunhome there is no early termination. Training runs for as many --epochs as you ask for.

best.pt is saved at the max fitness epoch, so no matter how much your training overfits, best.pt will always be the best checkpoint. You can cancel training at any time if you observe overfitting and use best.pt.

**Comment by adrianholovaty** [comment]
@leeyunhome You can close it early by hitting Control+C in the terminal window that's running the train.py command. (This assumes you're running it from an interactive shell.)

**Comment by leeyunhome** [comment]
> @leeyunhome there is no early termination. Training runs for as many --epochs as you ask for.
> 
> best.pt is saved at the max fitness epoch, so no matter how much your training overfits, best.pt will always be the best checkpoint. You can cancel training at any time if you observe overfitting and use best.pt.

Thank you.

**Comment by leeyunhome** [comment]
> @leeyunhome You can close it early by hitting Control+C in the terminal window that's running the train.py command. (This assumes you're running it from an interactive shell.)

Thank you.
