### ISSUE TITLE
Does YOLOv5 PyTorch support deployment to NVIDIA TensorRT 7.2.1? 

### ISSUE THREAD

**Issue by vilmara** [ultralytics/yolov5#2335]
## ❔Question
Does YOLOv5 PyTorch support deployment to NVIDIA TensorRT 7.2.1? 

The docker file at `ultralytics/yolov5/Dockerfile` builds `FROM nvcr.io/nvidia/pytorch:20.12-py3 ` (with TensorRT 7.2.2). My deployment environment supports only TRT 7.2.1, and therefore I am getting the below error:

`E0302 07:27:28.937001 90 logging.cc:43] INVALID_CONFIG: The engine plan file is not compatible with this version of TensorRT, expecting library version 7.2.1 got 7.2.2, please rebuild.`

**Comment by NanoCode012** [comment]
I see a tutorial on ReadMe. Maybe check that?

https://docs.ultralytics.com/yolov5
