### ISSUE TITLE
easy question

### ISSUE THREAD

**Issue by bigbrotherwei** [ultralytics/yolov5#2336]
## ❔Question
thank you for your excellent work, l wonder if l should keep the struct of training folder as shown below.
can l use  irregular folder structure ?

```
-train/
  -images/
  -labels/
-val/
  -images/
  -labels/
-test/
-data.yaml
```

**Comment by glenn-jocher** [comment]
@bigbrotherwei yes that works well. That's the standard dataset structure.

**Comment by bigbrotherwei** [comment]
thank you for your answer, if l make the structure as shown below, can yolo still works ?

```
-input/
     -a/
        -1.jpg
        -2.jpg
     -b/
        -3.jpg
        -4.jpg
     -c/
        -5.jpg
        -6.jpg
     -lables/
        -1.txt
        -2.txt
        -3.txt
        -4.txt
        -5.txt
        -6.txt
```

**Comment by glenn-jocher** [comment]
no
