### ISSUE TITLE
Is it possible to extract the coordinates of the box area in real time?

### ISSUE THREAD

**Issue by Choikyungho9** [ultralytics/yolov5#2337]
Hi. I have one question.
The project I have to do is to extract the coordinates of the box area of the object detected by yolov5 into the webcam image in real time.

Is it possible to extract the coordinates of the box area into the webcam image in real time??

**Comment by adrianholovaty** [comment]
I don't understand the question 100%, but it sounds like you're wanting to overlay detected objects' bounding boxes directly in the webcam image? If that's the case, then I believe you can use the `--source 0` parameter to `detect.py`, as described in the [Inference section](https://github.com/ultralytics/yolov5#inference) of the main README.

**Comment by Choikyungho9** [comment]
@adrianholovaty Thank you for answer. I want to overlay the x,y coordinates of the bounding box overlaid on that webcam. Do you know anything about this?

**Comment by adrianholovaty** [comment]
@Choikyungho9 Yes, I believe you can do that by tweaking the code in `detect.py`. In the `detect()` function, change this line...

```python
label = f'{names[int(cls)]} {conf:.2f}'
```

...to this:

```python
label = f'{xyxy[0]},{xyxy[1]}'
```

**Comment by Choikyungho9** [comment]
![b055](https://user-images.githubusercontent.com/20491139/109742208-03cdb300-7c12-11eb-814d-bd7641786bee.PNG)

@adrianholovaty Your answer is really helpful. But how do I understand the meaning of the numbers on this label? I don't really understand. 

`label = f'{xyxy[0]},{xyxy[1]` 

What do 0 and 1 mean?

**Comment by adrianholovaty** [comment]
@Choikyungho9 At that point in the code, the variable `xyxy` is a Python object that contains the bounding box coordinates. In Python, we use square brackets to access individual indexes of an array. `xyxy[0]` is the first element, and `xyxy[1]` is the second.
