### ISSUE TITLE
No labels found in test.cache

### ISSUE THREAD

**Issue by atomrun39** [ultralytics/yolov5#2339]
## ❔Question
Hi, I have trained a model, and I want to use test.py to calculate the map on my test set to see the effect of my trained model.
My yaml is as follows.

```
train: ./obj/train.txt  
val: ./obj/val.txt  
test: ./obj/test.txt  
nc: 2
names: [ '01', '02' ]
```

I use this to run: 

> python test.py --data data/obj.yaml --weights runs/train/exp6/weights/best.pt --task test --verbose

But the program went wrong as follows.

```
test: Scanning 'obj/test' for images and labels... 0 found, 0 missing, 0 empty, 400 corrupted: 100%|█████████████████████████████| 400/400 [00:00<00:00, 695.05it/s]
test: WARNING: No labels found in obj/test.cache. See https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data
test: New cache created: obj/test.cache
Traceback (most recent call last):
  File "test.py", line 320, in <module>
    save_conf=opt.save_conf,
  File "test.py", line 90, in test
    prefix=colorstr('test: ' if opt.task == 'test' else 'val: '))[0]
  File "/home/data/yolov5/utils/datasets.py", line 72, in create_dataloader
    prefix=prefix)
  File "/home/data/yolov5/utils/datasets.py", line 395, in __init__
    labels, shapes, self.segments = zip(*cache.values())
ValueError: not enough values to unpack (expected 3, got 0)
```
I checked that the test set labels were all correct. This is my data structure.
```
| -- obj
     | -- images
           | -- 1.jpg
           | -- 2.jpg
           | -- 3.jpg
     | -- labels
           | -- 1.txt
           | -- 2.txt
           | -- 3.txt
     | -- train.txt
     | -- val.txt
     | -- test.txt
| -- data
     | -- obj.yaml
```
test.txt file content
```
/home/data/yolov5/obj/images/1.jpg
/home/data/yolov5/obj/images/2.jpg
/home/data/yolov5/obj/images/3.jpg
```

**Comment by glenn-jocher** [comment]
@atomrun39 you should update your code to make sure you are up to date with master, and also delete any *.cache files that may be outdated, and let the command recache anything it needs. If this still doesn't work then there's simply some path issues in your data.yaml. You should follow the COCO128 example, i.e. run `python test.py`, and COCO128 will autodownload, allowing you to view a working example of where the dataset should be and how your data.yaml should look.

**Comment by atomrun39** [comment]
In addition, there is a problem with the operation.
```
Fusing layers... 
Model Summary: 224 layers, 7056607 parameters, 0 gradients, 16.3 GFLOPS
Scanning images:   0%|                                                            | 0/400 [00:00<?, ?it/s]
test: WARNING: Ignoring corrupted image and/or label obj/images/1.jpg: invalid image format MPO
test: WARNING: Ignoring corrupted image and/or label obj/images/2.jpg: invalid image format MPO
test: WARNING: Ignoring corrupted image and/or label obj/images/3.jpg: invalid image format MPO
```
Why is it an invalid image format MPO?

**Comment by glenn-jocher** [comment]
@atomrun39 1.jpg in your example is not a JPEG, it is actually an MPO file, which is not in the list of supported filetypes:
https://github.com/ultralytics/yolov5/blob/a3ecf0fd640465f9a7c009e81bcc5ecabf381004/utils/datasets.py#L27-L30

**Comment by atomrun39** [comment]
The original suffix for my image was JPG, I changed it directly to jpg. So is there any way to convert?

**Comment by atomrun39** [comment]
I used the latest code. I'm using a software to convert several images in my test set from JPG to jpg. Run test.py before the conversion, the picture shows corrupted; and run test.py after the conversion, the picture shows missing. Excuse me, what's going on here？
```
Fusing layers... 
Model Summary: 224 layers, 7056607 parameters, 0 gradients, 16.3 GFLOPS
test: Scanning 'obj/test' for images and labels... 0 found, 8 missing, 0 empty, 0 corrupted: 100%|██████████| 8/8 [00:00<00:00, 1722.33it/s]
test: New cache created: obj/test.cache
test: WARNING: No labels found in obj/test.cache. See https://docs.ultralytics.com/yolov5/tutorials/train_custom_data
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 1/1 [00:03<00:00,  3.22s/it]
                 all           8           0           0           0           0           0
Speed: 6.7/2.7/9.5 ms inference/NMS/total per 640x640 image at batch-size 8
/home/anaconda3/envs/py1.7/lib/python3.6/site-packages/seaborn/matrix.py:194: RuntimeWarning: All-NaN slice encountered
  vmin = np.nanmin(calc_data)
/home/anaconda3/envs/py1.7/lib/python3.6/site-packages/seaborn/matrix.py:199: RuntimeWarning: All-NaN slice encountered
  vmax = np.nanmax(calc_data)
Results saved to runs/test/exp

Process finished with exit code 0
```

**Comment by glenn-jocher** [comment]
@atomrun39 if your image is not a supported filetype it will not be used for training or testing. Once the image is no longer present in the cached data it is classified as missing. Supported filetypes are here:
https://github.com/ultralytics/yolov5/blob/a3ecf0fd640465f9a7c009e81bcc5ecabf381004/utils/datasets.py#L27-L30

**Comment by atomrun39** [comment]
Thanks for your answer, it is indeed a problem with my picture format.
