### ISSUE TITLE
Paper or description about YoloV5?

### ISSUE THREAD

**Issue by pedromoraesh** [ultralytics/yolov5#234]
## 🚀 Feature

A deep description about the network or any new feature

There is any TODO task for this?

As researcher and Master degree student i would like do understand better the network and have references to point in any published paper using Yolov5.

**Comment by glenn-jocher** [comment]
@pedromoraesh thanks for the suggestion, I hear where you are coming from. This is definitely on our TODO list, but we are extremely limited in resources at the moment, and our priority is architecture and training experimentation to mature on a more stable set of both. Our goal has always been to submit to arxiv by the end of the year.

In the meantime we've created a DOI you can use here, which updates on a release basis. The current DOI points to v1.0, which should remain in place until middle-end of July, when a v2.0 release is planned with major updates.
https://github.com/ultralytics/yolov5#citation

**Comment by pedromoraesh** [comment]
@glenn-jocher Nice! 

Thanks Glenn. Waiting for it!

It's extremely good. I wrote 3 papers this week using YoloV5, i will use DOI meanwhile!

**Comment by glenn-jocher** [comment]
@pedromoraesh oh great! I actually like publishing. Even though it can be a difficult path it really helps you examine your own data and practices, especially for peer reviewed journals. Ultralytics has several publications, including in Nature for particle physics experiments. See https://scholar.google.com/citations?user=swSrGtsAAAAJ&hl=en

I'll admit thought that the amount of attention and citations papers get in ML is orders of magnitude beyond what we see in physics.
