### ISSUE TITLE
Ignore regions

### ISSUE THREAD

**Issue by kazimpal87** [ultralytics/yolov5#2340]
Hi, some object detection datasets (like kitti) have "dont care" regions which are unannotated (like cars which appear far away in the background). Have you looked at all into modifying the loss function to take these into account so that the model isnt penalised for predicting "false positives" (which may correspond to true objects) in these unannotated regions?

thanks

**Comment by glenn-jocher** [comment]
@kazimpal87 that's interesting, but no we don't have any ignore masks. You might be able to filter objects by size though, i.e. to remove any detected cars less than 1000 pixels square perhaps. 

 If you are using KITTI and you'd like to contribute, it might help other users to be able to quickstart KITTI trainings with a kitti.yaml and download_kitti.sh to along with it (like coco.yaml and voc.yaml that both have autodownload).
