### ISSUE TITLE
Batch Inference using the model we trained

### ISSUE THREAD

**Issue by ramanathan831** [ultralytics/yolov5#2342]
## ❔Question
Hi, Can you provide an example function of how to do batch inference on the model we trained.
Detect.py is processing image sequentially
and the other example you gave is using torch.hub.load() to load the pretained model 

## Additional context
I hope I was clear.

**Comment by glenn-jocher** [comment]
@ramanathan831 see PyTorch Hub Tutorial for batched inference examples:

## Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [ONNX and TorchScript Export](https://docs.ultralytics.com/yolov5/tutorials/model_export)
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by ramanathan831** [comment]
@glenn-jocher When I load custom checkpoint using the example, I'm getting this issue:
 hub_model = Model(model.yaml).to(next(model.parameters()).device)  # create
AttributeError: 'tuple' object has no attribute 'yaml'

model = torch.hub.load('ultralytics/yolov5', 'custom', path_or_model=checkpoint)
checkpoint contains path of the .pt which was generated during training

**Comment by ramanathan831** [comment]
After using the strip optimizer function on the trained checkpoint, it is working fine now. Hope you can add a line for this step in your doc

**Comment by glenn-jocher** [comment]
@ramanathan831 just tested in colab, and loading final checkpoints or intermediate (not fully trained) checkpoints both work correctly with pytorch hub. 

If you are having problems its likely your code or your model are out of date, please clone a clean copy and retrain in that case.

**Comment by glenn-jocher** [comment]
also use force_reload with hub in case your cache may be outdated.

**Comment by ramanathan831** [comment]
So, the issue was with the fully trained checkpoints(non-stripped) ones. After using the strip function, and then using the subsequent checkpoint, I am able to run it

**Comment by glenn-jocher** [comment]
@ramanathan831 there is no issue with fully trained or partially trained checkpoints. As I said if you are experiencing problems your code (repo or hub cache) are out of date, and/or your model is out of date.

Also strip_optimizer() runs at the end of training on all checkpoints automatically.

**Comment by ramanathan831** [comment]
@glenn-jocher actually, strip optimizer was applied only to the best checkpoint. No worries now.
I had one other question, can we use this torch.hub method to deploy it in AWS instances?

**Comment by glenn-jocher** [comment]
@ramanathan831 thats not correct, strip optimizer runs on best.pt and last.pt at the end of training:
https://github.com/ultralytics/yolov5/blob/a3ecf0fd640465f9a7c009e81bcc5ecabf381004/train.py#L404-L406

**Comment by glenn-jocher** [comment]
@ramanathan831 see AWS quickstart guide.

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by ramanathan831** [comment]
Is there a possibility of using multi-gpu during inference time? Multi-GPU where each GPU we feed in batch of images

**Comment by glenn-jocher** [comment]
@ramanathan831 sure, you can create any workflows you want with the PyTorch Hub models.

**Comment by ramanathan831** [comment]
Any reference/example of how to do it?
