### ISSUE TITLE
Something wrong with fixing ema

### ISSUE THREAD

**Issue by MolchanovYA** [ultralytics/yolov5#2343]
Before submitting a bug report, please be aware that your issue **must be reproducible** with all of the following, otherwise it is non-actionable, and we can not help you:
 - **Current repo**: run `git fetch && git status -uno` to check and `git pull` to update repo
 - **Common dataset**: coco.yaml or coco128.yaml
 - **Common environment**: Colab, Google Cloud, or Docker image. See https://github.com/ultralytics/yolov5#environments
 
If this is a custom dataset/training question you **must include** your `train*.jpg`, `test*.jpg` and `results.png` figures, or we can not help you. You can generate these with `utils.plot_results()`.

## 🐛 Bug

I get an error while trying to resume a training

## To Reproduce (REQUIRED)

Input:
``
!python /content/yolov5/train.py --resume /content/drive/MyDrive/XRay/202102283/weights/last.pt
```

Output:
wandb: Run `wandb offline` to turn off syncing.

Traceback (most recent call last):
  File "train.py", line 532, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 154, in train
    ema.ema.load_state_dict(ckpt['ema'].float().state_dict())
AttributeError: 'tuple' object has no attribute 'float'

wandb: Waiting for W&B process to finish, PID 8842

## Expected behavior
Resuming of training


## Environment
Google Colab

 - OS: [e.g. Ubuntu]
 - GPU [e.g. 2080 Ti]


## Additional context
Removing float() fixes the bug.

**Comment by glenn-jocher** [comment]
@MolchanovYA sorry, there have been recent PRs to improve EMA resume behavior. Everything should work correctly now when starting and resuming a new run, however if you started and resumed your run with different versions of the code, this will likely lead to problems. 

I would suggest to restart training from a new clone.
