### ISSUE TITLE
Really low mAP when training my own dataset

### ISSUE THREAD

**Issue by GUOOOZI** [ultralytics/yolov5#235]
When training my own dataset, I found that my mAP was always low during training. Whether the training is based on pre-training weights or random weights. The following is my code and training diagram

Train in yolov5l
`python train.py --batch 19 --epochs 300 --data ./data/train_5classes.yaml --cfg ./models/customer_yolov5l_5classes.yaml --weights yolov5l.pt --name 5classes_yolov5l  --nosave --cache`
[results_5classes_yolov5l.txt](https://github.com/ultralytics/yolov5/files/4848305/results_5classes_yolov5l.txt)
![results](https://user-images.githubusercontent.com/62709607/86061245-57be4180-ba5e-11ea-80b1-df67877247cd.png)

Train in yolov5s
`python train.py --batch 60 --epochs 1000 --data ./data/train_5classes.yaml --cfg ./models/customer_yolov5s_5classes.yaml --weights yolov5s.pt --name 5classes  --nosave --cache`
[results_5classes.txt](https://github.com/ultralytics/yolov5/files/4848313/results_5classes.txt)
![results](https://user-images.githubusercontent.com/62709607/86061294-76243d00-ba5e-11ea-8871-2a476c17e35a.png)

Train in yolov5s_0weight
`python train.py --batch 60 --epochs 1000 --data ./data/train_5classes.yaml --cfg ./models/customer_yolov5s_5classes.yaml --weights '' --name 5classes_0weight  --nosave --cache`
[results_5classes_0weight.txt](https://github.com/ultralytics/yolov5/files/4848318/results_5classes_0weight.txt)
![results](https://user-images.githubusercontent.com/62709607/86061358-8e945780-ba5e-11ea-97f3-34338076ccfb.png)

**Comment by glenn-jocher** [comment]
@GUOOOZI can you upload your train*.jpg and test*.jpg images?

**Comment by GUOOOZI** [comment]
**yolov5l**

train_batch0

![train_batch0](https://user-images.githubusercontent.com/62709607/86064525-40cf1d80-ba65-11ea-8b27-210ed362499d.jpg)

train_batch1
![train_batch1](https://user-images.githubusercontent.com/62709607/86064527-4167b400-ba65-11ea-906e-0ff9cba3e8ac.jpg)

train_batch2
![train_batch2](https://user-images.githubusercontent.com/62709607/86064528-42004a80-ba65-11ea-8dc6-0e967d63c69b.jpg)

test_batch0_gt
![test_batch0_gt](https://user-images.githubusercontent.com/62709607/86064517-3dd42d00-ba65-11ea-9295-8a9491fa22b6.jpg)

test_batch0_pred
![test_batch0_pred](https://user-images.githubusercontent.com/62709607/86064523-40368700-ba65-11ea-87ef-568aac87532a.jpg)

**yolov5s**

train_batch0
![train_batch0](https://user-images.githubusercontent.com/62709607/86064630-84298c00-ba65-11ea-8cd5-bd9c66bd1070.jpg)

train_batch1
![train_batch1](https://user-images.githubusercontent.com/62709607/86064634-87247c80-ba65-11ea-949f-1b07ccf33624.jpg)

train_batch2
![train_batch2](https://user-images.githubusercontent.com/62709607/86064637-87bd1300-ba65-11ea-8c3d-06fcf33563ce.jpg)

test_batch0_gt
![test_batch0_gt](https://user-images.githubusercontent.com/62709607/86064659-986d8900-ba65-11ea-99c9-d83234ced92a.jpg)

test_batch0_pred
![test_batch0_pred](https://user-images.githubusercontent.com/62709607/86064666-9acfe300-ba65-11ea-83bc-1c9ead3ace89.jpg)

**yolov5s_0weight**

train_batch0
![train_batch0](https://user-images.githubusercontent.com/62709607/86064712-b2a76700-ba65-11ea-917e-9343a1fac740.jpg)

train_batch1
![train_batch1](https://user-images.githubusercontent.com/62709607/86064715-b33ffd80-ba65-11ea-8798-24c3521b46b1.jpg)

train_batch2
![train_batch2](https://user-images.githubusercontent.com/62709607/86064717-b3d89400-ba65-11ea-9983-e0613edfc0ca.jpg)

test_batch0_gt
![test_batch0_gt](https://user-images.githubusercontent.com/62709607/86064702-af13e000-ba65-11ea-8527-1c328c2ce3b7.jpg)

test_batch0_pred
![test_batch0_pred](https://user-images.githubusercontent.com/62709607/86064710-b20ed080-ba65-11ea-9346-be5600f113f1.jpg)

**Comment by GUOOOZI** [comment]
I am trying to train a dataset about garbage classification. And there are 5 classes in it, which are ['cardboard', 'paper','glass','metal','plastic']. @glenn-jocher

**Comment by glenn-jocher** [comment]
@GUOOOZI labels seem fine. You might try training at a low resolution, say perhaps --img-size 320, as all of the objects are fairly large. This sort of dataset displays somewhat high variety, so it would require ideally 10k training images or more to generalize well. You can see that overfitting starts extremely early, even for the training runs with no pretrained weights, which likely means your dataset may not be large enough for the task.

You could also always switch to a classifier, which may be simpler and produce better results if you do not need to localize your objects in your images.

One way to validate your training pipeline is train and test on the same images, the way coco128.yaml does. If this produces good results, but testing on your test set does not, then your model is training well, but generalizing poorly, and you likely need more (possibly a lot more) data.

**Comment by dschoerk** [comment]
i could assume that it is too difficult to learn from a dataset with such high intra class variation. it might work better to define classes of certain objects instead of materials. e.g. create classes for bottle, drinking glass, wine glass instead of just a glass class.

**Comment by GUOOOZI** [comment]
@glenn-jocher I tried using --img 320 for training and reduced the number of epochs properly, but the training results were not as good as before. After training, the mAP did not increase significantly, and during the test, a large object was often divided into several small ones for monitoring.

**yolov5s**

![results](https://user-images.githubusercontent.com/62709607/86155676-b0dcb280-bafc-11ea-936f-81ba5cf3059b.png)
<img width="709" alt="截屏2020-06-30 17 52 22" src="https://user-images.githubusercontent.com/62709607/86155868-f4cfb780-bafc-11ea-814a-377fafa64780.png">

**yolov5s_0weight**

![results](https://user-images.githubusercontent.com/62709607/86155783-cce05400-bafc-11ea-982a-079546388cfd.png)
<img width="704" alt="截屏2020-06-30 17 56 30" src="https://user-images.githubusercontent.com/62709607/86155847-ec777c80-bafc-11ea-9c6f-31f4e0ef2ea9.png">

**yolov5l**

![results](https://user-images.githubusercontent.com/62709607/86155808-dd90ca00-bafc-11ea-82ab-a4e22e40e256.png)
<img width="710" alt="截屏2020-06-30 17 41 01" src="https://user-images.githubusercontent.com/62709607/86155827-e5506e80-bafc-11ea-8c53-703b97abe4ae.png">


img320
![cardboard283](https://user-images.githubusercontent.com/62709607/86155148-ec2ab180-bafb-11ea-8dd1-928092732df4.jpg)
![glass412](https://user-images.githubusercontent.com/62709607/86155195-fba9fa80-bafb-11ea-8d67-6e0a9dcea5e7.jpg)

In fact, my training data set only has 1700 images to iterate. In the case of img640, although the displayed mAP is not high, the actual monitoring accuracy rate is more satisfactory.

img640
![cardboard333](https://user-images.githubusercontent.com/62709607/86155447-58a5b080-bafc-11ea-97a8-6cefbf19827a.jpg)
![glass372](https://user-images.githubusercontent.com/62709607/86155498-63604580-bafc-11ea-9d27-fa43eded886a.jpg)

The test was conducted in the case of img640, and the error rate was calculated after artificially checking that the deviation of the prediction frame was not large. In the case of yolov5s_0weight,overall error rate is 12.13%[cardboard:5.8%, glass:13.3%, metal:12%, paper:4.5%, plastic:25.5%].

**Comment by glenn-jocher** [comment]
@GUOOOZI it's likely you simply need more training data. 1700 with only 1 item per image is only 1700 items in your dataset, which is pretty low for the class count and variety of your data.

**Comment by glenn-jocher** [comment]
@GUOOOZI you might want to try training without autoanchor to compare also. Autoanchor is the default, you can disable it like this:
`python train.py --noautoanchor`

**Comment by GUOOOZI** [comment]
@glenn-jocher Hi, I think there are some problems of the mAP calculate during the training process. 
As mentioned above, the mAP I showed during training was very low. But when I downloaded the weights after training and ran test.py alone, the results obtained were very different from the mAP during training.

For example, in yolov5s_0weight_img320.pt, the training curve is shown as below
![image](https://user-images.githubusercontent.com/62709607/86790258-1fbb8d80-c060-11ea-8860-f437d2b7005b.png)
![image](https://user-images.githubusercontent.com/62709607/86790302-306c0380-c060-11ea-9a73-c22bc4d0cf35.png)
However, the result of test.py is totally different.

**Result of val** (the val images is as same as the train images)
![image](https://user-images.githubusercontent.com/62709607/86790480-690bdd00-c060-11ea-8fb6-e9da1d1bf4e9.png)

**Result of test**
![image](https://user-images.githubusercontent.com/62709607/86790631-8ccf2300-c060-11ea-994e-1634b97b030e.png)

In addition, after trying to train with --noautoanchor, I run the test.py directly and I got the different answer when I download the weight.pt and run it again.

**Directly(for val)** 
![image](https://user-images.githubusercontent.com/62709607/86790893-d1f35500-c060-11ea-9a94-08d34dcbc4e0.png)

**Alone**
val
![image](https://user-images.githubusercontent.com/62709607/86790982-f0f1e700-c060-11ea-83a3-5396d41aecde.png)
test
![image](https://user-images.githubusercontent.com/62709607/86791015-f94a2200-c060-11ea-8a4e-b56ccbf51d8d.png)

**Comment by glenn-jocher** [comment]
@GUOOOZI the only mAP issue I'm aware of was a multi-GPU mAP bug that reduced the reported mAP during training which has been fixed a while ago. The correct mAP was always appearing with test.py. You should git pull your code to ensure you are using the latest.

**Comment by GUOOOZI** [comment]
@glenn-jocher I trained the weight in colab, so every time I configure the environment, I will re-download the latest GitHub code. And this weight.py with --noautoanchor is trained yesterday. I don't know why the parameters displayed during training process are wrong.

And I think that it is not just the calculation of mAP that has problems, the calculation of other parameters is still far away from the results in test.py.

**Comment by GUOOOZI** [comment]
@glenn-jocher In addition, the training device is:
Using torch 1.5.1+cu101 _CudaDeviceProperties(name='Tesla P100-PCIE-16GB', major=6, minor=0, total_memory=16280MB, multi_processor_count=56)

only one GPU

**Comment by glenn-jocher** [comment]
@GUOOOZI ok. I'm a bit confused about your post, about what your main question is because you mention several different things. If you are saying that training mAP and standalone test is different, I don't think that's true. 

If you train coco128 for 100 epochs and then run test.py on last.pt, you will get almost the same mAP. If your dataset does not behave similarly, the cause is your dataset.

**Comment by GUOOOZI** [comment]
@glenn-jocher OK thank you all the same. I will try to solve it.

**Comment by glenn-jocher** [comment]
@GUOOOZI I just ran the experiment myself now. I trained yolov5s for 10 epochs, and see the same mAP reported during training and when testing the final checkpoint with test.py directly. If you have a reproducible issue then please let us know, but I don't see any problem.

<img width="1321" alt="Screen Shot 2020-07-07 at 11 44 01 AM" src="https://user-images.githubusercontent.com/26833433/86827792-4a4d1c80-c047-11ea-8249-ec9491ccdb7f.png">

<img width="1321" alt="Screen Shot 2020-07-07 at 11 44 08 AM" src="https://user-images.githubusercontent.com/26833433/86827807-4de0a380-c047-11ea-8e6c-910395378748.png">

**Comment by GUOOOZI** [comment]
@glenn-jocher Thank you for training. Yes, exactly. When I test just after the 10 epoch training my dataset, the parameters looks same as it shown in the training process
![image](https://user-images.githubusercontent.com/62709607/86831022-47c1e580-c08e-11ea-9701-0bee4ed30546.png)
![image](https://user-images.githubusercontent.com/62709607/86831071-5a3c1f00-c08e-11ea-9bf9-3ae7a5b9a43e.png)
![image](https://user-images.githubusercontent.com/62709607/86831114-645e1d80-c08e-11ea-8ba8-4e5dc14b529e.png)

However, when I download the weight.py and run it in the same dataset, I get different result.
![image](https://user-images.githubusercontent.com/62709607/86831302-a12a1480-c08e-11ea-9f99-284b1c8a560b.png)

In fact, After completing the entire training process and checking each output image, the parameters(mAP, P, R) of running test.py after downloading is closer to the true value. I am not sure if this is due to a problem with my own data set, but when I only train two classes, the parameters(mAP, P, R...) I get are closer to the actual values. But when I increased to more than 3 classes, the parameters became very low.

**Comment by glenn-jocher** [comment]
@GUOOOZI I don't know what you mean by "downloading the weights". The only weights available for download are the official weights on google drive.

**Comment by GUOOOZI** [comment]
@glenn-jocher I mean, download the weight file that has been trained to the local computer, and then use the same data set for testing. Or upload this weight file to a new colab file(not the one for training) and reconfigure the same environment before running.

**Comment by glenn-jocher** [comment]
@GUOOOZI I've tested this, again, and again your issue not reproducible. I followed your steps, trained a model in Colab, tested it, downloaded it, tested it locally, and everything is working perfectly. We have extremely limited time, please do not raise issues that are not reproducible in a common environment on a common dataset, as the above message so clearly states.

<img width="1321" alt="Screen Shot 2020-07-07 at 11 44 08 AM" src="https://user-images.githubusercontent.com/26833433/86837733-2c39e900-c054-11ea-813e-bb612bfaee85.png">

<img width="1316" alt="Screen Shot 2020-07-07 at 1 16 05 PM" src="https://user-images.githubusercontent.com/26833433/86837705-217f5400-c054-11ea-88ba-59973f27ad52.png">

**Comment by GUOOOZI** [comment]
That's all alright. Thank you for your patient. @glenn-jocher

**Comment by jingenyan** [comment]
@glenn-jocher @GUOOOZI when i train with my own dataset with the newest version only with CPU , it come across the same problem  as following:
--batch-size 16 --data data/coins/coins.yaml --cfg data/coins/yolov5s.yaml --weights ''"
     Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
     0/299        0G     0.115    0.1386   0.04377    0.2974       158       544
               Class      Images     Targets           P           R      mAP@.5
                 all          25           0           0           0           0           0

     Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
     1/299        0G    0.1153    0.1375   0.04326    0.2961       174       544
               Class      Images     Targets           P           R      mAP@.5
                 all          25         251           0           0    1.05e-06     2.1e-07

     Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
     2/299        0G    0.1121    0.1402   0.04357    0.2959       102       544
               Class      Images     Targets           P           R      mAP@.5
                 all          25         251           0           0    3.44e-05    5.39e-06

     Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
     3/299        0G     0.112     0.153   0.04328    0.3083       146       544
               Class      Images     Targets           P           R      mAP@.5
                 all          25         251           0           0     6.1e-05    9.44e-06

     Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
     4/299        0G    0.1131    0.1449   0.04286    0.3008       189       544
               Class      Images     Targets           P           R      mAP@.5
                 all          25         251           0           0    0.000104    1.55e-05

     Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
     5/299        0G    0.1105    0.1429   0.04282    0.2962       185       544
               Class      Images     Targets           P           R      mAP@.5
                 all          25         251           0           0    0.000118    1.77e-05

     Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
     6/299        0G    0.1061    0.1357   0.04279    0.2846       115       544
               Class      Images     Targets           P           R      mAP@.5
                 all          25         251           0           0    0.000208    3.06e-05

     Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
     7/299        0G    0.1082     0.132   0.04278     0.283        89       544
               Class      Images     Targets           P           R      mAP@.5
                 all          25         251           0           0    0.000269    3.79e-05

     Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
     8/299        0G    0.1071    0.1494   0.04221    0.2987       170       544
               Class      Images     Targets           P           R      mAP@.5
                 all          25         251           0           0     0.00054    6.89e-05

     Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
     9/299        0G     0.104    0.1556   0.04236     0.302       131       544
               Class      Images     Targets           P           R      mAP@.5
                 all          25         251           0           0    0.000716    9.78e-05

     Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
    10/299        0G    0.1048      0.15   0.04172    0.2964       140       544
               Class      Images     Targets           P           R      mAP@.5
                 all          25         251           0           0     0.00106    0.000144

     Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
    11/299        0G     0.106    0.1777   0.04166    0.3254       200       544
               Class      Images     Targets           P           R      mAP@.5
                 all          25         251           0           0     0.00137    0.000178

     Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
    12/299        0G    0.1059     0.161   0.04065    0.3075       159       544
               Class      Images     Targets           P           R      mAP@.5
                 all          25         251           0           0     0.00148     0.00021

     Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
    13/299        0G    0.1031    0.1507   0.04174    0.2955       124       544
               Class      Images     Targets           P           R      mAP@.5
                 all          25         251           0           0     0.00181     0.00027

     Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
    14/299        0G    0.1043     0.162   0.04087    0.3071       163       544
               Class      Images     Targets           P           R      mAP@.5
                 all          25         251           0           0     0.00179    0.000267

     Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
    15/299        0G    0.1019    0.1545   0.04114    0.2975       145       544
               Class      Images     Targets           P           R      mAP@.5
                 all          25         251           0           0     0.00189     0.00029

     Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
    16/299        0G    0.1023    0.1706   0.04046    0.3134       159       544
               Class      Images     Targets           P           R      mAP@.5
                 all          25         251           0           0      0.0021    0.000319

     Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
    17/299        0G    0.1048    0.1584   0.03994    0.3031       170       544

**Comment by jingenyan** [comment]
@glenn-jocher @GUOOOZI   train with low mAP and test as following 
Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
    40/299        0G   0.09577    0.1709   0.03726    0.3039       117       544
               Class      Images     Targets           P           R      mAP@.5
                 all          25         251           0           0     0.00469    0.000744

     Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
    41/299        0G   0.09459    0.1666   0.03743    0.2986       130       544
               Class      Images     Targets           P           R      mAP@.5
                 all          25         251       0.333     0.00218     0.00663    0.000958

     Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
    42/299        0G   0.09612    0.1806   0.03671    0.3135       155       544
               Class      Images     Targets           P           R      mAP@.5
                 all          25         251           0           0     0.00486    0.000798

     Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
    43/299        0G   0.09552    0.1659   0.03731    0.2987       139       544
               Class      Images     Targets           P           R      mAP@.5
                 all          25         251           0           0     0.00554    0.000887

     Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
    44/299        0G   0.09381     0.164   0.03688    0.2947       153       544
               Class      Images     Targets           P           R      mAP@.5

test_batch0_pred.jpg
![test_batch0_pred](https://user-images.githubusercontent.com/29670226/87660491-b93a1c00-c791-11ea-84cf-ee23315c4cc3.jpg)

test_batch0_gt.jpg
![test_batch0_gt](https://user-images.githubusercontent.com/29670226/87659606-6875f380-c790-11ea-997f-b73b2dbef404.jpg)


how to solve this problem？

**Comment by xiangmind** [comment]
> @GUOOOZI labels seem fine. You might try training at a low resolution, say perhaps --img-size 320, as all of the objects are fairly large. This sort of dataset displays somewhat high variety, so it would require ideally 10k training images or more to generalize well. You can see that overfitting starts extremely early, even for the training runs with no pretrained weights, which likely means your dataset may not be large enough for the task.
> 
> You could also always switch to a classifier, which may be simpler and produce better results if you do not need to localize your objects in your images.
> 
> One way to validate your training pipeline is train and test on the same images, the way coco128.yaml does. If this produces good results, but testing on your test set does not, then your model is training well, but generalizing poorly, and you likely need more (possibly a lot more) data.

You are smart.

**Comment by toshk15** [comment]
hello friends,

I have the same problem(low map) with kitti dataset, only with one class "car" with more instances
![2](https://user-images.githubusercontent.com/45886706/103961299-d127a280-5119-11eb-823d-75975d752aa4.jpg)


attached some images.

how have you solved the problem?
![1](https://user-images.githubusercontent.com/45886706/103961165-8148db80-5119-11eb-8b0c-415806fcf8b5.jpg)

run for training:

python train.py --img 640 --batch 16 --epochs 100 --data kitti.yaml --cfg models/yolov5s.yaml --name ki --weights yolov5s.pt --cache

**Comment by toshk15** [comment]
In the above images leave the original image size of 1242 and the .yaml file with the correct name, the result is still a low MAP.
In other words, I already tried changing the size of the image and the result is the same.
The KITTI dataset is small to train yolov5?

My best regards!

**Comment by glenn-jocher** [comment]
@toshk15 I'm not sure what mAP you are expecting from YOLOv5s on KITTI. On COCO this model returns about 0.37 mAP@0.5:0.95 with 100,000 training images and 80 classes.

**Comment by toshk15** [comment]
Hi @glenn-jocher 
The result predictions are not good how i would expect:

![000007](https://user-images.githubusercontent.com/45886706/103964049-1bac1d80-5120-11eb-9fea-8d1a8c3dd464.png)
![000006](https://user-images.githubusercontent.com/45886706/103964051-1c44b400-5120-11eb-8631-1b760986185d.png)
![000005](https://user-images.githubusercontent.com/45886706/103964052-1cdd4a80-5120-11eb-8c14-79a9838e0319.png)
![000004](https://user-images.githubusercontent.com/45886706/103964053-1d75e100-5120-11eb-9d43-f05064392969.png)
![000003](https://user-images.githubusercontent.com/45886706/103964055-1e0e7780-5120-11eb-8ea4-a6cc0501fb26.png)
![000002](https://user-images.githubusercontent.com/45886706/103964057-1ea70e00-5120-11eb-8fd0-b359efcce6da.png)
![000001](https://user-images.githubusercontent.com/45886706/103964060-1f3fa480-5120-11eb-86a2-7e3534da7e01.png)
![000000](https://user-images.githubusercontent.com/45886706/103964066-1fd83b00-5120-11eb-8f99-81b8ddd32c3f.png)

**Comment by glenn-jocher** [comment]
@toshk15 train 1000 epochs.

**Comment by irfan-gif** [comment]
@glenn-jocher YOLOv5 calculates mAP against validation dataset during training. Though which command we can calculate the against unseen test dataset (mAP, and Class wise mAP)

**Comment by glenn-jocher** [comment]
@irfan-gif test.py can evaluate mAP on train, val, or test part of a dataset with the --task option:
https://github.com/ultralytics/yolov5/blob/f5b8f7d54c9fa69210da0177fec7ac2d9e4a627c/test.py#L294

For mAP on a test set, assuming your test set has labels and is defined in data.yaml, you simply run:
```
python test.py --data data.yaml --task test
```

**Comment by irfan-gif** [comment]
@glenn-jocher thank you sir

**Comment by Sukeysun** [comment]
> In the above images leave the original image size of 1242 and the .yaml file with the correct name, the result is still a low MAP. In other words, I already tried changing the size of the image and the result is the same. The KITTI dataset is small to train yolov5?
> 
> My best regards!

Hi, did you solve your problem? I met the same problem trainning yolov5-s on a different dataset with one class

**Comment by wyh196646** [comment]
I met the same problem with @glenn-jocher ，how should i slove this？

**Comment by glenn-jocher** [comment]
@wyh196646 👋 Hello! Thanks for asking about improving YOLOv5 🚀 training results. 

Most of the time good results can be obtained with no changes to the models or training settings, **provided your dataset is sufficiently large and well labelled**. If at first you don't get good results, there are steps you might be able to take to improve, but we always recommend users **first train with all default settings** before considering any changes. This helps establish a performance baseline and spot areas for improvement.

If you have questions about your training results **we recommend you provide the maximum amount of information possible** if you expect a helpful response, including results plots (train losses, val losses, P, R, mAP), PR curve, confusion matrix, training mosaics, test results and dataset statistics images such as labels.png. All of these are located in your `project/name` directory, typically `yolov5/runs/train/exp`.

We've put together a full guide for users looking to get the best results on their YOLOv5 trainings below.

## Dataset

- **Images per class.** ≥ 1500 images per class recommended
- **Instances per class.** ≥ 10000 instances (labeled objects) per class recommended
- **Image variety.** Must be representative of deployed environment. For real-world use cases we recommend images from different times of day, different seasons, different weather, different lighting, different angles, different sources (scraped online, collected locally, different cameras) etc.
- **Label consistency.** All instances of all classes in all images must be labelled. Partial labelling will not work.
- **Label accuracy.** Labels must closely enclose each object. No space should exist between an object and it's bounding box. No objects should be missing a label.
- **Label verification.** View `train_batch*.jpg` on train start to verify your labels appear correct, i.e. see [example](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data#local-logging) mosaic.
- **Background images.** Background images are images with no objects that are added to a dataset to reduce False Positives (FP). We recommend about 0-10% background images to help reduce FPs (COCO has 1000 background images for reference, 1% of the total). No labels are required for background images.

<a href="https://arxiv.org/abs/1405.0312"><img width="800" src="https://user-images.githubusercontent.com/26833433/109398377-82b0ac00-78f1-11eb-9c76-cc7820669d0d.png" alt="COCO Analysis"></a>


## Model Selection

Larger models like YOLOv5x and [YOLOv5x6](https://github.com/ultralytics/yolov5/releases/tag/v5.0) will produce better results in nearly all cases, but have more parameters, require more CUDA memory to train, and are slower to run. For **mobile** deployments we recommend YOLOv5s/m, for **cloud** deployments we recommend YOLOv5l/x. See our README [table](https://github.com/ultralytics/yolov5#pretrained-checkpoints) for a full comparison of all models. 

<p align="center"><img width="700" alt="YOLOv5 Models" src="https://github.com/ultralytics/yolov5/releases/download/v1.0/model_comparison.png"></p>

- **Start from Pretrained weights.** Recommended for small to medium sized datasets (i.e. [VOC](https://github.com/ultralytics/yolov5/blob/master/data/VOC.yaml), [VisDrone](https://github.com/ultralytics/yolov5/blob/master/data/VisDrone.yaml), [GlobalWheat](https://github.com/ultralytics/yolov5/blob/master/data/GlobalWheat2020.yaml)). Pass the name of the model to the `--weights` argument. Models download automatically from the [latest YOLOv5 release](https://github.com/ultralytics/yolov5/releases).
```bash
python train.py --data custom.yaml --weights yolov5s.pt
                                             yolov5m.pt
                                             yolov5l.pt
                                             yolov5x.pt
                                             custom_pretrained.pt
```
- **Start from Scratch.** Recommended for large datasets (i.e. [COCO](https://github.com/ultralytics/yolov5/blob/master/data/coco.yaml), [Objects365](https://github.com/ultralytics/yolov5/blob/master/data/Objects365.yaml), [OIv6](https://storage.googleapis.com/openimages/web/index.html)). Pass the model architecture yaml you are interested in, along with an empty `--weights ''` argument:
```bash
python train.py --data custom.yaml --weights '' --cfg yolov5s.yaml
                                                      yolov5m.yaml
                                                      yolov5l.yaml
                                                      yolov5x.yaml
```


## Training Settings

Before modifying anything, **first train with default settings to establish a performance baseline**. A full list of train.py settings can be found in the [train.py](https://github.com/ultralytics/yolov5/blob/master/train.py) argparser.

- **Epochs.** Start with 300 epochs. If this overfits early then you can reduce epochs. If overfitting does not occur after 300 epochs, train longer, i.e. 600, 1200 etc epochs.
- **Image size.** COCO trains at native resolution of `--img 640`, though due to the high amount of small objects in the dataset it can benefit from training at higher resolutions such as `--img 1280`. If there are many small objects then custom datasets will benefit from training at native or higher resolution. Best inference results are obtained at the same `--img` as the training was run at, i.e. if you train at `--img 1280` you should also test and detect at `--img 1280`.
- **Batch size.** Use the largest `--batch-size` that your hardware allows for. Small batch sizes produce poor batchnorm statistics and should be avoided.
- **Hyperparameters.** Default hyperparameters are in [hyp.scratch-low.yaml](https://github.com/ultralytics/yolov5/blob/master/data/hyps/hyp.scratch-low.yaml). We recommend you train with default hyperparameters first before thinking of modifying any. In general, increasing augmentation hyperparameters will reduce and delay overfitting, allowing for longer trainings and higher final mAP. Reduction in loss component gain hyperparameters like `hyp['obj']` will help reduce overfitting in those specific loss components. For an automated method of optimizing these hyperparameters, see our [Hyperparameter Evolution Tutorial](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution).

## Further Reading

If you'd like to know more a good place to start is Karpathy's 'Recipe for Training Neural Networks', which has great ideas for training that apply broadly across all ML domains: http://karpathy.github.io/2019/04/25/recipe/

Good luck 🍀 and let us know if you have any other questions!

**Comment by ruman1609** [comment]
If your mAP stuck below level, try shuffle the data loader when train.

In my case training with my own dataset, the mAP result is change.

**Comment by glenn-jocher** [comment]
@ruman1609 if you are experiencing consistently low mAP results during training on your own dataset, you may consider shuffling the data loader. This can help introduce more randomness in the training process and potentially improve your results. Give it a try and see if it makes a difference in your training.
