### ISSUE TITLE
test.py why map of val_data is better than test_data?

### ISSUE THREAD

**Issue by ggyybb** [ultralytics/yolov5#2352]
## ❔Question
test.py why map of val_data is better than test_data?

## Additional context
hello,when i train myown data, I found that the map of val_data is better than test_data always,why?
Is val set used in training?
Should I use test set to evaluate my model, or val set or both？
Actually, I trained two models ,one is 94.3map on val and 93map on test,the other is 93.4map on val and 93.1map on test.
The former have more parameters like yolov5-p2.yaml,the latter have less parameter like yolov5.yaml origin.
Should I train the more parameter model more epochs? or use the latter model directly?

**Comment by ggyybb** [comment]
![confusion_matrix](https://user-images.githubusercontent.com/61568153/109786848-938e5400-7c48-11eb-93b4-1093767a2b3c.png)
top_right (car and backFN) box is 0.87,I think the predicted car is actually the backgroung, am i right?

**Comment by glenn-jocher** [comment]
@ggyybb you can report results from either test or val or both.

Clearly one set is going to perform better than the other, it would be very unlikely for you to return identical results on different datasets.

Neither val or test sets are used in training.

**Comment by glenn-jocher** [comment]
@ggyybb about your confusion matrix, we just had a recent PR https://github.com/ultralytics/yolov5/pull/2114 fix for this. You may want to git pull and then retest to get an updated confusion matrix.

P2 models have a P2/4 output layer, which will be better for detecting very small objects when compared to the standard (P3-P5) models.

From your results it seems both of your models perform similarly well. You might also try a P6 model to compare, i.e. yolov5-p6.yaml, scaled to the size you want (s/m/l/x) using the compound scaling constants at the top.
