### ISSUE TITLE
diminished detection rate with OpenCV compared to PIL.Image

### ISSUE THREAD

**Issue by phaabe** [ultralytics/yolov5#2356]
## ❔Question
I try to run my own trained model with OpenCV. 
And as it seems, OpenCV has a diminished detection rate compared to reading an image with `PIL.Image`. 
I try to understand this, but I cannot find out the reason. I see that `PIL.Image` returns a `JpegImageFile` and `cv2.imread` returns a numpy array. Are there some columns that must be swapped or something? It shows that with displaying the rendered results, the second code snippet shows the images with a stronger blue tone. 
I stumbled over this because I experienced the same issue with `cv2.VideoCapture`.

## Additional context
I iterate as follows over a list of paths to jpeg images.

What I tried with OpenCV
```
for jpg in jpgs:
    img = cv2.imread(jpg)

    img = Image.open(jpg)

    result = model(img, size=640)  # includes NMS
    render = result.render()[0]

    # Display the resulting frame
    cv2.imshow('frame', render)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
```

What performs better with PIL.Image:
```
for jpg in jpgs:
    img = Image.open(jpg)

    result = model(img, size=640)  # includes NMS
    render = result.render()[0]

    # Display the resulting frame
    cv2.imshow('frame', render)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
```

**Comment by phaabe** [comment]
Okay, it's RGB vs BGR order 
https://stackoverflow.com/questions/58861577/differences-between-pil-image-open-and-cv2-imdecode

**Comment by phaabe** [comment]
`frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)`
fixes it

Hopes this helps others!

**Comment by glenn-jocher** [comment]
@phaabe The PyTorch Hub tutorial shows cv2 example with the correct color ordering, you may want to start there:

## Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [ONNX and TorchScript Export](https://docs.ultralytics.com/yolov5/tutorials/model_export)
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)
