### ISSUE TITLE
Where is the weight of own dataset trained with pretraining weights?

### ISSUE THREAD

**Issue by rouyalxy** [ultralytics/yolov5#236]
Where is the weight of own dataset trained with pretraining weights?

**Comment by glenn-jocher** [comment]
@rouyalxy for pretrained checkpoints see https://github.com/ultralytics/yolov5#pretrained-checkpoints

You can download all of the weights from our google drive folder. Also, all weights are downloaded automatically if you request them, i.e. `python train.py --weights yolov5s.pt`

**Comment by rouyalxy** [comment]
I've downloaded the pretraining weights，and fine tuning pretraining weight. Where is the generated training weight？Coverage pretraining weight?

**Comment by glenn-jocher** [comment]
@rouyalxy weights are saved to ./weights folder during training.

**Comment by rouyalxy** [comment]
thanks, I see, an epoch will be saved once after training

**Comment by glenn-jocher** [comment]
last and best checkpoints are saved after each epoch.

**Comment by rouyalxy** [comment]
How to modify the folder of weight saving

**Comment by glenn-jocher** [comment]
https://github.com/ultralytics/yolov5/blob/bfd51f62f8e0a114cb94c269e83ff135e31d8bdb/train.py#L23

**Comment by rouyalxy** [comment]
How to continue the last training

**Comment by ashawkey** [comment]
https://github.com/ultralytics/yolov5/blob/bfd51f62f8e0a114cb94c269e83ff135e31d8bdb/train.py#L361
