### ISSUE TITLE
Unable to provide Wandb API in Kaggle Kernel

### ISSUE THREAD

**Issue by joyjeni** [ultralytics/yolov5#2362]
## ❔Cannot enter kaggle kernel edit mode
When I train Yolo V5 using Kaggle kernel I m unable to paste wandb API key in Kaggle Kernel. How to be in Console edit mode
There was no option to paste api key. Looks like I m not in edit mode.How to enable edit mode inside Kaggle kernel.

![image] (https://i.imgur.com/4cDrffU.png)

**Comment by NanoCode012** [comment]
I think we should have an argument to disable wandb from command line or pass in the API key... I sometimes find it inconvenient if I have to spawn multiple trainings in containers..

For example, `--wandb None` vs `--wandb APIKey`.

**Comment by glenn-jocher** [comment]
@AyushExel I think this might be the same issue https://github.com/ultralytics/yolov5/issues/1372 I reported in December with wandb and Kaggle. 

@joyjeni is your issue the same as #1372 ?

**Comment by joyjeni** [comment]
yes.

**Comment by AyushExel** [comment]
Try this 
```
import wandb
 from kaggle_secrets import UserSecretsClient
 user_secrets = UserSecretsClient() 

personal_key_for_api = user_secrets.get_secret("wandb-key")

! wandb login $personal_key_for_api
```

**Comment by joyjeni** [comment]
Gave above error
---------------------------------------------------------------------------
BackendError                              Traceback (most recent call last)
<ipython-input-5-af4d64f06910> in <module>
      4 user_secrets = UserSecretsClient()
      5 
----> 6 personal_key_for_api = user_secrets.get_secret("c629bfxxxxxxxx1")
      7 

~/.local/lib/python3.7/site-packages/kaggle_secrets.py in get_secret(self, label)
     62             'Label': label,
     63         }
---> 64         response_json = self.web_client.make_post_request(request_body, self.GET_USER_SECRET_BY_LABEL_ENDPOINT)
     65         if 'secret' not in response_json:
     66             raise BackendError(

~/.local/lib/python3.7/site-packages/kaggle_web_client.py in make_post_request(self, data, endpoint, timeout)
     48                 if not response_json.get('wasSuccessful') or 'result' not in response_json:
     49                     raise BackendError(
---> 50                         f'Unexpected response from the service. Response: {response_json}.')
     51                 return response_json['result']
     52         except (URLError, socket.timeout) as e:

BackendError: Unexpected response from the service. Response: {'errors': ['No user secrets exist for kernel id 151xxxx9 and label c629bfxxxxxxxx1'], 'error': {'code': 5, 'details': []}, 'wasSuccessful': False}.

**Comment by AyushExel** [comment]
@joyjeni The issue occurs because you cannot directly copy a secret in kaggle console. Here the workaround is to save the API key as a kaggle secret.
**Steps:**
Click on add-ons in the kernel -> secrets -> add secret 
Now copy the api key from wandb.ai/settings under any name you desire( in this case it's "wandb-key")
![Screenshot from 2021-03-05 21-14-45](https://user-images.githubusercontent.com/15766192/110138690-3b964f80-7df8-11eb-8af6-2e5d0ed4045f.png)

Now if you run the previous snippet, you should be able to log in

**Comment by joyjeni** [comment]
Thankyou it works

**Comment by AyushExel** [comment]
@glenn-jocher I found an easier fix for this that'll work out of the box.
Replace `!wandb login` with `wandb.login()` works fine.
Here's how the updated cell should look like.
```
# Weights & Biases (optional)
%pip install -q wandb 
import wandb
wandb.login()  
```
I have tested this and it works fine on Kaggle Kernels

**Comment by glenn-jocher** [comment]
@AyushExel excellent, I'll update the Colab and Kaggle notebook!

**Comment by glenn-jocher** [comment]
@joyjeni @AyushExel good news 😃! Your original issue may now been fixed ✅ in https://github.com/ultralytics/yolov5/commit/9b91db6d1aab7267db5153f0be79c8c25e84f75a.  To receive this update you can:
- `git pull` from within your `yolov5/` directory
- `git clone https://github.com/ultralytics/yolov5` again
- Force-reload PyTorch Hub: `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- View our updated [Colab](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb) and [Kaggle](https://www.kaggle.com/ultralytics/yolov5-ultralytics) notebooks

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
