### ISSUE TITLE
mAP in Train Phase

### ISSUE THREAD

**Issue by BNTzHax** [ultralytics/yolov5#2364]
## ❔Question
Hi there, thank you for your great work
I have a question, are there anyway can i display mAP in train phase ? I only see mAP display in valid phase

**Comment by glenn-jocher** [comment]
@BNTzHax COCO128 trains and evaluates on the same dataset:
https://github.com/ultralytics/yolov5/blob/e931b9da33f45551928059b8d61bddd50e401e48/data/coco128.yaml#L12-L15

This is not standard practice though, this is merely to verify the training pipeline can overfit as a sanity check before training on real data.

**Comment by BNTzHax** [comment]
> # train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/] 
>  train: ../coco128/images/train2017/  # 128 images 
>  val: ../coco128/images/train2017/  # 128 images

Thanks for your answer, but in my case i split dataset to k-fold (with train/valid set) and i want to display both mAP on train set and valid set during train phase. Are there any options for that ?

**Comment by glenn-jocher** [comment]
@BNTzHax you can pass any dataset you want in the `val:` field, or any group of datasets, which would be merged together at validation time.

**Comment by BNTzHax** [comment]
> @BNTzHax you can pass any dataset you want in the `val:` field, or any group of datasets, which would be merged together at validation time.

Thank you, i will try it
