### ISSUE TITLE
export.py export onnx for gpu failed

### ISSUE THREAD

**Issue by sveits6** [ultralytics/yolov5#2365]
when export onnx model for gpu，i change the export.py :
![图片](https://user-images.githubusercontent.com/23731100/109946833-a457cc00-7d13-11eb-8986-90e8df7e3e26.png)
but export failed:

![图片](https://user-images.githubusercontent.com/23731100/109948130-fbaa6c00-7d14-11eb-91b6-396eb666ffcf.png)

how to solve it?

**Comment by glenn-jocher** [comment]
@sveits6 fro GPU export you may want to see this PR: https://github.com/ultralytics/yolov5/pull/2297

**Comment by sveits6** [comment]
> 
> 
> @sveits6 fro GPU export you may want to see this PR: #2297

sorry, the problem is not be solved

**Comment by sveits6** [comment]
@glenn-jocher  sorry，the problem is not be solved

**Comment by toretak** [comment]
@sveits6 
I guess you should use device `cuda:0` when you loading model.

Successfully tested on code from #2297 
```bash
$ python models/export.py --device 0 --weights ../../detection/yolo5/yolov5/yolo20210116.pt 
Namespace(batch_size=1, device='0', dynamic=False, img_size=[640, 640], skip_last_layer=False, weights='../../detection/yolo5/yolov5/yolo20210116.pt')
YOLOv5 v4.0-96-ge3f5bdb torch 1.7.1 CUDA:0 (GeForce GTX 1650 with Max-Q Design, 3914.1875MB)

Fusing layers... 
Model Summary: 316 layers, 21929304 parameters, 0 gradients, 52.8 GFLOPS

Starting TorchScript export with torch 1.7.1...
/git/yolov5/.venv/lib/python3.8/site-packages/torch/jit/_trace.py:934: TracerWarning: Encountering a list at the output of the tracer might cause the trace to be incorrect, this is only valid if the container structure does not change based on the module's inputs. Consider using a constant container instead (e.g. for `list`, use a `tuple` instead. for `dict`, use a `NamedTuple` instead). If you absolutely need this and know the side effects, pass strict=False to trace() to allow this behavior.
  module._c._create_method_from_trace(
TorchScript export success, saved as ../../detection/yolo5/yolov5/yolo20210116.torchscript.pt

Starting ONNX export with onnx 1.8.1...
ONNX export success, saved as ../../detection/yolo5/yolov5/yolo20210116.onnx
CoreML export failure: No module named 'coremltools'

Export complete (7.68s). Visualize with https://github.com/lutzroeder/netron.

```

**Comment by sveits6** [comment]
@glenn-jocher @toretak 
thank you very much for your reply! 
when "model.model[-1].export = True" it works,  but "model.model[-1].export = False" it failed。
if  must make "model.model[-1].export = True" , how can i get the final result from the 3 feature maps?
