### ISSUE TITLE
.weight

### ISSUE THREAD

**Issue by chaUAV** [ultralytics/yolov5#237]
## 🚀 Feature
Hello I trained my model with a custom dataset. But now how can I convert .yaml & .pt to .cfg & .weight

**Comment by chaUAV** [comment]
I want to use yolov5 on windows 10 but when I pip install -U -r requirements.txt. 
![Capture](https://user-images.githubusercontent.com/67619154/86081853-91c02f80-bac0-11ea-8ad0-e8df509183a2.PNG)
This occurs

**Comment by glenn-jocher** [comment]
@chaUAV you can export *.pt models to ONNX and Torchscript formats using models/export.py. You can train using one of our working environments here:

## Reproduce Our Environment

To access an up-to-date working environment (with all dependencies including CUDA/CUDNN, Python and PyTorch preinstalled), consider a:

- **GCP** Deep Learning VM with $300 free credit offer: See our [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Google Colab Notebook** with 12 hours of free GPU time. <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/)
