### ISSUE TITLE
How to control camera.

### ISSUE THREAD

**Issue by Anico18** [ultralytics/yolov5#2371]
## Additional context
I'm trying to use this repository in a controlled environment inside a simulator, but I don't know how to control the camera or choose the camera I want to feed the algorithm with.

**Comment by glenn-jocher** [comment]
@Anico18 if you have multiple local cameras attached to your computer you can specify them with:
```bash
python detect.py --source 0
python detect.py --source 1
python detect.py --source 2
etc...
```

**Comment by Anico18** [comment]
And for the simulator? Which variable stores the data received by the cameras?

**Comment by glenn-jocher** [comment]
@Anico18 i'm sorry I don't know what simulator you're referring to. The camera indexing is just based on normal OpenCV operations:

https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_gui/py_video_display/py_video_display.html

> To capture a video, you need to create a VideoCapture object. Its argument can be either the device index or the name of a video file. Device index is just the number to specify which camera. Normally one camera will be connected (as in my case). So I simply pass 0 (or -1). You can select the second camera by passing 1 and so on. After that, you can capture frame-by-frame. But at the end, don’t forget to release the capture.

**Comment by Anico18** [comment]
Oh, sorry about that. I’m trying to use this with ROS. I want to give an image coming from the virtual camera of a robot to yolov5

**Comment by glenn-jocher** [comment]
@Anico18 I don't know. If it has an http or rtsp address you can access it that way. See README for all inference options:
https://github.com/ultralytics/yolov5#inference
