### ISSUE TITLE
Image size input for prediction

### ISSUE THREAD

**Issue by maheshmechengg** [ultralytics/yolov5#2372]
## ❔Question
What can be used as input image size for prediction ?

## Additional context
Hi Glen, Firstly great work on yolov5, it's much faster!

I have trained our model using image size of 736. While testing tried different input image size as like trained model 736 & then different inputs (as trained image size as 1600, & then 1200, 1400 etc..

With different image size as input for prediction it varies the output (gives more objects detected with 1600 than with 736 & lower image sizes than the original image sizes), is this expected while prediction ? If yes which we can relied on ? Your help & support on this will be much appreciated.

**Comment by glenn-jocher** [comment]
@maheshmechengg well, you can run inference at any image size your hardware will allow, but best results will be achieved by training and testing at similar resolutions. So if you trained at 736, you'll get your best inference results around 736 also.

The standard scale augmentation hyperparameter is set at 0.5, so at inference you might expect to be able to detect objects well at +/- 50% of your inference size, but if run inference at large sizes the model is also not capable of projecting sufficiently large boxes, as it's never been asked to do that in training.

https://github.com/ultralytics/yolov5/blob/e931b9da33f45551928059b8d61bddd50e401e48/data/hyp.scratch.yaml#L27

**Comment by leeyunhome** [comment]
> @maheshmechengg well, you can run inference at any image size your hardware will allow, but best results will be achieved by training and testing at similar resolutions. So if you trained at 736, you'll get your best inference results around 736 also.
> 
> The standard scale augmentation hyperparameter is set at 0.5, so at inference you might expect to be able to detect objects well at +/- 50% of your inference size, but if run inference at large sizes the model is also not capable of projecting sufficiently large boxes, as it's never been asked to do that in training.
> 
> https://github.com/ultralytics/yolov5/blob/e931b9da33f45551928059b8d61bddd50e401e48/data/hyp.scratch.yaml#L27

Hello @glenn-jocher 

I used to specify 640, 416 as --image-size.
For example, if you want to specify 640x200, how do you write it to the --image-size parameter?
!python train.py --img **640** --batch 16 --epochs 10
!python train.py --img **640x200** --batch 16 --epochs 10 ?

Thank you.

**Comment by glenn-jocher** [comment]
@leeyunhome you pass the long side to --img-size, the short side is automatically scaled. If you want to run inference at 640x200 you pass --img 640.

**Comment by leeyunhome** [comment]
> @leeyunhome you pass the long side to --img-size, the short side is automatically scaled. If you want to run inference at 640x200 you pass --img 640.

Hello, @glenn-jocher 

!python train.py --img-size 640x200 --batch 16 --epochs 10 ?

right?

Thank you.

**Comment by leeyunhome** [comment]
> @maheshmechengg well, you can run inference at any image size your hardware will allow, but best results will be achieved by training and testing at similar resolutions. So if you trained at 736, you'll get your best inference results around 736 also.
> 
> The standard scale augmentation hyperparameter is set at 0.5, so at inference you might expect to be able to detect objects well at +/- 50% of your inference size, but if run inference at large sizes the model is also not capable of projecting sufficiently large boxes, as it's never been asked to do that in training.
> 
> https://github.com/ultralytics/yolov5/blob/e931b9da33f45551928059b8d61bddd50e401e48/data/hyp.scratch.yaml#L27

Hello,

**Comment by glenn-jocher** [comment]
@leeyunhome no that is not correct. If you want to train at 640 then you pass 640:
```
python train.py --img 640
```

**Comment by leeyunhome** [comment]
> @leeyunhome no that is not correct. If you want to train at 640 then you pass 640:
> 
> ```
> python train.py --img 640
> ```

Hello, @glenn-jocher 

640x224, 640x316 Is it possible to specify image sizes with different widths and heights in this format?

Thank you.

**Comment by leeyunhome** [comment]
> @leeyunhome no that is not correct. If you want to train at 640 then you pass 640:
> 
>   ##```
> python train.py --img 640
> ```

**Comment by leeyunhome** [comment]
> @leeyunhome you pass the long side to --img-size, the short side is automatically scaled. If you want to run inference at 640x200 you pass --img 640.

Hello, @glenn-jocher 

![image](https://user-images.githubusercontent.com/59910227/110564881-ea3be680-8190-11eb-9dc5-5c7cfef60b79.png)

The custom dataset image size is 800x600. In this case, if I use --image-size 640, will it learn as 640x640?
if so
In this case, how do I learn to use 640x200?

Thank you.

**Comment by glenn-jocher** [comment]
@leeyunhome if you want to train at 640 on the long side then you pass 640:

```
python train.py --img 640
```

**Comment by leeyunhome** [comment]
> @leeyunhome if you want to train at 640 on the long side then you pass 640:
> 
> ```
> python train.py --img 640
> ```

Hello, @glenn-jocher 

You mean, the size of the other side is automatically determined according to the size of the longest side of the image?

I thought that 640x200 and 640x300 values are possible because it is any size.

Thank you.

**Comment by leeyunhome** [comment]
> @leeyunhome if you want to train at 640 on the long side then you pass 640:
> 
> ```
> python train.py --img 640
> ```

Hello, @glenn-jocher 

My original dataset image is 800x600.
By the way, if you learn with --img 640 and convert it to onnx
The input is 640x640.

If you train with --img 416 and convert to onnx
The input is 416x416.

Isn't the input size decided as a square image unconditionally?

Thank you.
