### ISSUE TITLE
hyp['iou_t']

### ISSUE THREAD

**Issue by KrystalCWT** [ultralytics/yolov5#2373]
## ❔Question

Hi,
How to generate positive and negative samples? hyp['iou_t'] isn't used in the project. How to defind the threshold?

**Comment by KrystalCWT** [comment]
Can you explain the code in build_target?
        # Match targets to anchors
        t = targets * gain
        if nt:
            # Matches
            r = t[:, :, 4:6] / anchors[:, None]  # wh ratio
            j = torch.max(r, 1. / r).max(2)[0] < model.hyp['anchor_t']  # compare
            # j = wh_iou(anchors, t[:, 4:6]) > model.hyp['iou_t']  # iou(3,n)=wh_iou(anchors(3,2), gwh(n,2))
            t = t[j]  # filter
 Thanks.

**Comment by glenn-jocher** [comment]
@KRYSTALLJY `hyp['anchor_t']` is the anchor size threshold used to match an anchor to a label. The default setting is 4, which means that labels/anchor size ratio of 1/4 > ratio > 4 will be matched to an anchor during training.
