### ISSUE TITLE
Ground truth bboxes in inference

### ISSUE THREAD

**Issue by NMVRodrigues** [ultralytics/yolov5#2374]
Unsure if it is possible, or if I should mark it as a feature request, but is there an option to see the ground truth bounding boxes during inference?

**Comment by glenn-jocher** [comment]
@NMVRodrigues test.py plots the first few batches of ground truth labels and predictions as test_batch0_labels.jpg, test_batch0_pred.jpg, etc. 

<img width="1200" alt="Screen Shot 2021-03-05 at 10 49 35 AM" src="https://user-images.githubusercontent.com/26833433/110160153-7ec4d400-7da0-11eb-8004-35ea3bce15d9.png">
