### ISSUE TITLE
Loading mode when Restart training

### ISSUE THREAD

**Issue by TaoXieSZ** [ultralytics/yolov5#238]
## 🚀 Feature

Make it possible when we want to retrain a model by less `epochs` options

## Motivation
I have train a model with 10 epochs. When I try to retrain it for one more epochs by setting --epochs 1. It will raise error

**Comment by yxNONG** [comment]
assume you have train 100(x) epochs and get the weights(last.pt)
if you want to train 20(y) more epochs 
set --epochs 120(x+y) will work

**Comment by TaoXieSZ** [comment]
> assume you have train 100(x) epochs and get the weights(last.pt)
> if you want to train 20(y) more epochs
> set --epochs 120(x+y) will work

I got your point and fix it before opening this issue.
I just want to give a suggestion.

**Comment by glenn-jocher** [comment]
@ChristopherSTAN this has been fixed now in a recent commit. Please git pull and try again.
