### ISSUE TITLE
RuntimeError: cuda runtime error (2) : out of memory

### ISSUE THREAD

**Issue by laurelrr** [ultralytics/yolov5#2380]
I am submitting this as a general question because I think the issue is on my end, rather than a bug with your software.  However, I am not sure how to correct it so any pointers you can share would be greatly appreciated.

I am trying to run your training example with coco128 but encounter a runtime error at Epoch 138/299.  
I ran a git pull just before starting the training.  However, just prior to submitting this I ran:
`$ git fetch && git status -uno`
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (1/1), done.
From https://github.com/ultralytics/yolov5
   e931b9d..300d518  master     -> origin/master
On branch master
Your branch is behind 'origin/master' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)

nothing to commit (use -u to show untracked files)

## Issue
cuda runtime error: out of memory

## To Reproduce (REQUIRED)

Input:
`$ conda env create --name yolov5 python=3.8`
`$ conda activate yolov5`
`$ pip install -r requirements`
`$ git pull`
`$ python train.py`

Output:
```
(The output downloads the coco128 dataset, installed it one directory up from yolov5 and generally seems to function correctly until here:)
[ previous output clipped]
     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
   136/299     5.36G   0.04141   0.04262  0.008143   0.09217       230       640: 100%|████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:01<00:00,  5.03it/s]               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|████████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.87it/s]                 all         128         929        0.91       0.845       0.929       0.631
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCCachingHostAllocator.cpp line=278 error=2 : out of memory

     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
   137/299     5.36G   0.04252   0.04655  0.009146   0.09822       228       640: 100%|████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:01<00:00,  4.79it/s]               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.17it/s]                 all         128         929       0.855       0.878        0.93       0.624

     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
   138/299     5.36G    0.0424   0.04541  0.008946   0.09676       174       640:  88%|████████████████████████████████████████████████████████████████████████████████▌           | 7/8 [00:01<00:00,  5.07it/s]Traceback (most recent call last):
  File "train.py", line 531, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 271, in train
    for i, (imgs, targets, paths, _) in pbar:  # batch -------------------------------------------------------------
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/site-packages/tqdm/std.py", line 1176, in __iter__
    for obj in iterable:
  File "/mnt/c/Users/Laurel/Documents/GitHub/yolov5/utils/datasets.py", line 104, in __iter__
    yield next(self.iterator)
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in pin memory thread for device 0.
Original Traceback (most recent call last):
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 31, in _pin_memory_loop
    data = pin_memory(data)
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 55, in pin_memory
    return [pin_memory(sample) for sample in data]
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 55, in <listcomp>
    return [pin_memory(sample) for sample in data]
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 47, in pin_memory
    return data.pin_memory()
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/THCCachingHostAllocator.cpp:278

```

## Expected behavior
I expected to example coco128 dataset to complete training.  My GPU has 71.9GB of memory.  

## Environment
 - OS: Windows 10 (WIP build 21322.1000), WSL 2 and using the Ubuntu 18.04 kernel.  
 - GPU: NVIDIA Quadro RTX 4000
	Driver version:	27.21.14.6542
	Driver date:	1/23/2021
	DirectX version:	12 (FL 12.1)

## Additional context
CUDA-11.1, pytorch 1.7.1

**Comment by glenn-jocher** [comment]
@laurelrr CUDA OOM just means your GPU is out of memory, or a general OOM just means your system is out of RAM. If you say your GPU has 72 GB of memory then that should clearly not be an issue though.

Sometimes simply restarting your machine and rerunning your command will clear these issues. If this keep occuring in the same epoch each time, then you likely have environment issues, and I would recommend you train in a docker image:


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>
