### ISSUE TITLE
pruning yolov5s and yolov5x, if the same model sizes,  mAP of yolov5x would higher than yolov5s?

### ISSUE THREAD

**Issue by yao-zheng-yi** [ultralytics/yolov5#2387]
@glenn-jocher Hi! I have a question.
If pruning yolov5s and yolov5x, after pruning if the model sizes of yolov5s produce to 8M and the model sizes of yolov5x also  produce to 8M, the mAP of yolov5x would also higher than yolov5s?
Compare yolov5s and yolov5x, if I want to get smaller model sizes and kepp a good mAP, which one is better?

**Comment by glenn-jocher** [comment]
@yao-zheng-yi you have to experiment to determine which one is better, I don't know the answer.

**Comment by yao-zheng-yi** [comment]
I add the code
`prune(model, 0.5)`
in test.py
mAP of yolov5s is 34.5% and mAP of yolov5x is 25.1%, but if sparsity is less than 0.4, mAP of yolov5x is higher than yolov5s.
a sparsity of 50% means  50% of the model's weight parameters. so both yolov5s and yolov5x remain 50% weight parameters, the model sizes of yolov5x would  bigger than yolov5s?
I use torch.save() to save model_normal>pt and model_pruned>pt, but no change in model sizes

**Comment by glenn-jocher** [comment]
@yao-zheng-yi right, 0.1 sparsity means that 10% of the models' weights have been set to zero. Any size reduction in the model would have to come from sparse matrix datatypes. See https://pytorch.org/docs/stable/sparse.html

Also the sparsity step is typically followed by a retraining step to finetune the sparse model, so the intermediate mAP values you see are not intended to be final results.
