### ISSUE TITLE
about Driver version

### ISSUE THREAD

**Issue by gef1998** [ultralytics/yolov5#2389]
## ❔Question
Driver version 435.21，CUDA 10.1

UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 10010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
YOLOv5 v4.0-14-gb75c432 torch 1.7.1 CPU

What version of GPU driver should I upgrade to

**Comment by glenn-jocher** [comment]
@gef1998 you should update to the latest version.
