### ISSUE TITLE
Fewer predictions and lower score with current yolov5 version 

### ISSUE THREAD

**Issue by hannesoehler** [ultralytics/yolov5#2392]
## ❔Question
I realized that with the current yolov5 version I get fewer predictions and a lower score compared to older versions of the repo (I think my last old version is from about 3 weeks ago). I ran detect.py with the same model and the same setting using the old and current version.

I attach the two outputs for the first images:
![output_new](https://user-images.githubusercontent.com/72496477/110259983-adae9600-7faa-11eb-9e27-966b1ae00056.jpg)
![output_old](https://user-images.githubusercontent.com/72496477/110260000-ba32ee80-7faa-11eb-80de-d13d1dd8c2bf.jpg)

Any idea what could cause the difference? Did any default options for detect.py change lately? Maybe I should also mention that this is not due to TTA as I saw a change there in the last weeks.

**Comment by glenn-jocher** [comment]
@hannesoehler there are many periodic changes to the repo code, and sometimes to the pretrained models, I would recommend you clone a clean version of the repo and retrain your model.

One performance impacting bug was introduced last week (and fixed a few days later), if you see a significant drop in performance this may be the cause.

Also, anecdotal results (a few examples) are not useful when comparing runs, you want to compare mAP on a test set.

**Comment by hannesoehler** [comment]
@glenn-jocher Thanks for your reply! The difference in mAP on the test set is not large (0.244 vs. 0.248).

Ok I will retrain the model with the current version and have a look at the results.

**Comment by hannesoehler** [comment]
I think I now know the cause: https://github.com/ultralytics/yolov5/pull/2252
