### ISSUE TITLE
Receiving error message on weights trained through Supervisely.

### ISSUE THREAD

**Issue by scm-setpoint** [ultralytics/yolov5#2395]
## I get the following error message when I try to run inference with a weight created through Supervisely:

AttributeError: Can't get attribute 'C3' on <module 'models.common' from '/Users/<user>/PycharmProjects/YoloV5/models/common.py'>

However, when I run another weight I created earlier through a Colab Workbook it works.

What can cause this issue?

**Comment by glenn-jocher** [comment]
@scm-setpoint we are working on supporting Supervisely integration soon, but this is still in beta testing at the moment. If you believe you have a reproducible issue, please close this issue and raise a new one using the 🐛 **Bug Report template**, providing screenshots and a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) of your issue to help us diagnose the problem. Thank you!

**Comment by mkolomeychenko** [comment]
Hi! In Supervisely we use the sources of YOLOv5 from the release `v4.0`. @scm-setpoint Please try to checkout from latest master to the version `v4.0` and try to load weights again.

**Comment by scm-setpoint** [comment]
I just made a new pull from the latest version of YoloV5 repo, and now it works, thanks!
