### ISSUE TITLE
When training, can the image size input as a command line parameter be any value?

### ISSUE THREAD

**Issue by leeyunhome** [ultralytics/yolov5#2396]
## ❔Question
Hello,

When training, can the image size input as a command line parameter be any value?
Are there any special rules that are widely used like 416x416 608x608 640x640?

Thank you.

**Comment by glenn-jocher** [comment]
@leeyunhome default value is indicated in argparser:
https://github.com/ultralytics/yolov5/blob/e8a2b83268950e346899a84e8d29e84d178553b1/train.py#L451

You can supply any value you want.

**Comment by leeyunhome** [comment]
> @leeyunhome default value is indicated in argparser:
> https://github.com/ultralytics/yolov5/blob/e8a2b83268950e346899a84e8d29e84d178553b1/train.py#L451
> 
> You can supply any value you want.

Hello @glenn-jocher ,

The original image is 800x600
When training, I specified --image-size as 640, 416 as well, and the trained model inferred the original size image.
By the way, the model trained by specifying 100 as --image-size
The reasoning is not good for both the original sized image and the small resized image.

What am I doing wrong?

Thank you.

**Comment by glenn-jocher** [comment]
@leeyunhome for best results train and run inference at the same size, i.e. for 800:
```bash
python train.py --img 800
python detect.py --img 800
```

**Comment by leeyunhome** [comment]
> @leeyunhome default value is indicated in argparser:
> https://github.com/ultralytics/yolov5/blob/e8a2b83268950e346899a84e8d29e84d178553b1/train.py#L451
> 
> You can supply any value you want.

Hello,

The default is set to 640.
Directly specifying python train.py --img 640
When the original image is 800x600
Are the remaining resolutions determined at the same ratio as 800x600?

Thank you.

**Comment by glenn-jocher** [comment]
@leeyunhome yes that's correct. --img 640 will resize the long side of each of your images to 640, maintaining aspect ratio and padding the shorter side as necessary to meet stride-multiple constraints.

**Comment by leeyunhome** [comment]
@glenn-jocher 

Thank you.
