### ISSUE TITLE
Multiple IP camera process 

### ISSUE THREAD

**Issue by constantinfite** [ultralytics/yolov5#2397]
## ❔Question
I'm currently running the script detect.py on multiple camera streams.

I would like to know how the algorithm deals with the different video stream : 

- It retrieves the first video stream, run the inference, retrieve the second video stream, run inference ?
- Or Retrieve all the video stream at the same time and run the inference for each ?

Is it sequentially or in parallel ?

Thanks

**Comment by glenn-jocher** [comment]
@constantinfite see LoadStreams() datalaoder:
https://github.com/ultralytics/yolov5/blob/e8a2b83268950e346899a84e8d29e84d178553b1/detect.py#L45-L54

**Comment by siyangxie** [comment]
Multi-threading

**Comment by constantinfite** [comment]
@glenn-jocher @SiyangXie Thanks for your answer
So it's retrieving the image at the same time and it runs inference sequentially ?

**Comment by glenn-jocher** [comment]
@constantinfite multiple webcams are accessed asynchronously in the LoadStreams() dataloader, and this data is coupled with batched inference for speed.

**Comment by constantinfite** [comment]
@glenn-jocher The batch size is 1 ? do we send one stream by one to inference ?

**Comment by glenn-jocher** [comment]
@constantinfite batch size is a function of the number of cameras that are streaming simultaneously.

**Comment by constantinfite** [comment]
@glenn-jocher  sorry to ask again ^^ just to be sure : so if I have 3 camera the batch size will be 3 ?

**Comment by glenn-jocher** [comment]
@constantinfite yes
