### ISSUE TITLE
AARCH64 Support Example Jetson Nano and Xavier NX

### ISSUE THREAD

**Issue by Xyonia** [ultralytics/yolov5#2398]
## ❔Question
Standart requirements.txt installements are not possible for this kind of processors (AARCH64) because of their architecture. Is there any planned special version or any specialized setup and reqirements install suggestion planned to release? Thanks for your great
 efforts thatyou put suchperfectly workingsystem btw.

**Comment by batrlatom** [comment]
The problem is that there are few libraries like pytorch and torchvision for example, which you need to download in the custom build and are not official release. Torchvision you need to build yourself for example. I think that docker build specifically for jetson based devices where everything is build from scratch would be best option. But you will build it 12 hours or more I believe

**Comment by glenn-jocher** [comment]
@Xyonia @batrlatom does this work?
https://ngc.nvidia.com/catalog/containers/nvidia:l4t-pytorch

## PyTorch Container for Jetson and JetPack
The l4t-pytorch docker image contains PyTorch and torchvision pre-installed in a Python 3.6 environment to get up & running quickly with PyTorch on Jetson. These containers support the following releases of JetPack for Jetson Nano, TX1/TX2, Xavier NX, and AGX Xavier:

- JetPack 4.5 (L4T R32.5.0)
- JetPack 4.4.1 (L4T R32.4.4)
- JetPack 4.4 (L4T R32.4.3)
- JetPack 4.4 Developer Preview (L4T R32.4.2)

For additional machine learning containers for Jetson, see the l4t-ml and l4t-tensorflow images. Note that the PyTorch pip wheel installers for aarch64 used by these containers are available to download independently from the Jetson Zoo.

**Comment by glenn-jocher** [comment]
@Xyonia @batrlatom for PyTorch 1.8 support on Jetson I found this also:
https://forums.developer.nvidia.com/t/pytorch-for-jetson-version-1-8-0-now-available/72048

<img width="1200" alt="Screen Shot 2021-03-08 at 11 50 47 AM" src="https://user-images.githubusercontent.com/26833433/110373615-8ab0d000-8004-11eb-9b46-721c40538996.png">

**Comment by batrlatom** [comment]
> @Xyonia @batrlatom for PyTorch 1.8 support on Jetson I found this also:
> https://forums.developer.nvidia.com/t/pytorch-for-jetson-version-1-8-0-now-available/72048

@glenn-jocher This is the right place to download pytorch for Jetpack. But you still need to
compile torchvision yourself

> @Xyonia @batrlatom does this work?
> https://ngc.nvidia.com/catalog/containers/nvidia:l4t-pytorch
> 
> ## PyTorch Container for Jetson and JetPack
> The l4t-pytorch docker image contains PyTorch and torchvision pre-installed in a Python 3.6 environment to get up & running quickly with PyTorch on Jetson. These containers support the following releases of JetPack for Jetson Nano, TX1/TX2, Xavier NX, and AGX Xavier:
> 
> * JetPack 4.5 (L4T R32.5.0)
> * JetPack 4.4.1 (L4T R32.4.4)
> * JetPack 4.4 (L4T R32.4.3)
> * JetPack 4.4 Developer Preview (L4T R32.4.2)
> 
> For additional machine learning containers for Jetson, see the l4t-ml and l4t-tensorflow images. Note that the PyTorch pip wheel installers for aarch64 used by these containers are available to download independently from the Jetson Zoo.

It worked for me. Btw you need to use tensorrt conversion to get meaningful speed on jetpack devices. But it works quite good.
I am getting like 30ms per image on jetson xavier with yolov5 medium model, 608*608 resolution and batch size 1.

**Comment by glenn-jocher** [comment]
@batrlatom oh great! What's the speedup of pytorch inference vs tensorrt inference you are seeing? Also what tool are you using for tensorrt export?

**Comment by Xyonia** [comment]
> @Xyonia @batrlatom does this work?
> https://ngc.nvidia.com/catalog/containers/nvidia:l4t-pytorch
> 
> ## PyTorch Container for Jetson and JetPack
> The l4t-pytorch docker image contains PyTorch and torchvision pre-installed in a Python 3.6 environment to get up & running quickly with PyTorch on Jetson. These containers support the following releases of JetPack for Jetson Nano, TX1/TX2, Xavier NX, and AGX Xavier:
> 
> * JetPack 4.5 (L4T R32.5.0)
> * JetPack 4.4.1 (L4T R32.4.4)
> * JetPack 4.4 (L4T R32.4.3)
> * JetPack 4.4 Developer Preview (L4T R32.4.2)
> 
> For additional machine learning containers for Jetson, see the l4t-ml and l4t-tensorflow images. Note that the PyTorch pip wheel installers for aarch64 used by these containers are available to download independently from the Jetson Zoo.



> @Xyonia @batrlatom does this work?
> https://ngc.nvidia.com/catalog/containers/nvidia:l4t-pytorch
> 
> ## PyTorch Container for Jetson and JetPack
> The l4t-pytorch docker image contains PyTorch and torchvision pre-installed in a Python 3.6 environment to get up & running quickly with PyTorch on Jetson. These containers support the following releases of JetPack for Jetson Nano, TX1/TX2, Xavier NX, and AGX Xavier:
> 
> * JetPack 4.5 (L4T R32.5.0)
> * JetPack 4.4.1 (L4T R32.4.4)
> * JetPack 4.4 (L4T R32.4.3)
> * JetPack 4.4 Developer Preview (L4T R32.4.2)
> 
> For additional machine learning containers for Jetson, see the l4t-ml and l4t-tensorflow images. Note that the PyTorch pip wheel installers for aarch64 used by these containers are available to download independently from the Jetson Zoo.

Thisone didn't worked for me but the 1.8.0 version is new i think because i didn't noticed  for days. Docker image is the best option i agree but i will try with 1.8.0 first with compiling torchvision myself without tensorrt.  @batrlatom If you dont have anything special on your system i am also would like to ask your working environment image if its available. Thanks.

**Comment by batrlatom** [comment]
> @batrlatom oh great! What's the speedup of pytorch inference vs tensorrt inference you are seeing? Also what tool are you using for tensorrt export?

The speedup is significant. I am getting about 120ms per image by using pure yolov5 implementation ( last version, medium model, 640*640 ) and 30ms per image by converting it into the tensorrt. Those numbers are from jetson xavier AGX (30w mode), but the same speedup is across all jetson devices. I have tried it also on nano, tx2, xavier nx. I am using implementation from https://github.com/wang-xinyu/tensorrtx 

Since you are using yolov5 probably commercially, I would suggest to explore the tensorrt for the deployment on nvidia hardware, the speedup is really great.

What I would love though is to have an implementation which fully translates onto the TPU hardware. 
My idea is to be able to export yolov5 to all edge devices ( TPU hardware, Tensorrt compatible one, Tensorflowlite and Tensorflowjs  for web )

Best,
Tom

**Comment by glenn-jocher** [comment]
@batrlatom wow, 4x is a huge speedup! I've never used tensorrt myself, but yes https://github.com/wang-xinyu/tensorrtx is a great implementation. 

It sounds like you've got some experience with the various edge solutions. We are actually considering opening up a full time  position later this year for providing official support for edge hardware (nvidia jetson, agx, coral tpus). If you've got time to chat it would be interesting to hear your opinion on the requirements and the challenges there, I have a Calendly you can use to set up a quick meeting here:
https://calendly.com/ultralytics/meeting

**Comment by batrlatom** [comment]
@glenn-jocher I sent you a mail

**Comment by glenn-jocher** [comment]
@batrlatom great!

**Comment by batrlatom** [comment]
@Xyonia @topiaruss @olehb I would try to make a Dockerfile for yolov5 based on L4T R32.5.0, but please wait few days

**Comment by batrlatom** [comment]
@Xyonia @topiaruss @olehb 

try this to build a docker file 
with command
```
sudo docker build . < Dockerfile
```
You need to have a Jetpack 4.5/4.5.1 ( in case of Jetpack 4.4 
change later on nvcr.io/nvidia/l4t-pytorch:r32.5.0-pth1.7-py3 to
nvcr.io/nvidia/l4t-pytorch:r32.4.4-pth1.7-py3, but I did not test it )


...

clone yolov5 and make those changes:

requirements.txt

```
# base ----------------------------------------
Cython
matplotlib>=3.2.2
numpy>=1.18.5
opencv-python>=4.1.2
Pillow
PyYAML>=5.3.1
scipy>=1.4.1
tensorboard>=2.2
torch>=1.7.0
#torchvision>=0.8.1
torchvision>=0.8.0a0+45f960c
tqdm>=4.41.0

# logging -------------------------------------
# wandb

# plotting ------------------------------------
seaborn>=0.11.0
pandas

# export --------------------------------------
# coremltools>=4.1
# onnx>=1.8.1
# scikit-learn==0.19.2  # for coreml quantization

# extras --------------------------------------
thop  # FLOPS computation
pycocotools>=2.0  # COCO mAP
```

Dockerfile
```
FROM nvcr.io/nvidia/l4t-pytorch:r32.5.0-pth1.7-py3

# Install linux packages
RUN apt update && apt install -y zip htop screen libgl1-mesa-glx

# Install python dependencies
COPY requirements.txt .
RUN python3 -m pip install --upgrade pip
RUN pip3 install --no-cache -r requirements.txt gsutil notebook

# Create working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Copy contents
COPY . /usr/src/app

# Set environment variables
ENV HOME=/usr/src/app

```

It should work. If not, try to change file at 
/etc/docker/daemon.json with this content
```
{
    "runtimes": {
        "nvidia": {
            "path": "nvidia-container-runtime",
            "runtimeArgs": []
        }
    },
    "default-runtime": "nvidia" 
}
```

**Comment by Xyonia** [comment]
Thank you so much @batrlatom , i will try this today!

**Comment by Xyonia** [comment]
Unfortunately i couldn't succeed. I tried to installed docker with no problem  but container didn't show up. I tried to install dependencies one by one it is not also succesfull.  @batrlatom

**Comment by batrlatom** [comment]
@Xyonia I have prepared the docker image, test it with ```docker pull batrlatom/yolov5:arm```

**Comment by jomdolalas** [comment]
Is this also viable for raspberry pi 3b+? or only jetson products?

**Comment by batrlatom** [comment]
@jomdolalas It is only for jetson products ( aarch64 ). From what I am aware of, raspi has little different architecture - arm7.
Unfortunatelly I do not have raspi myself, so I cannot build it for you. But I think that you should be able to build it from the Dockerfile I posted few days ago. The only thing you should change is the FROM image.

**Comment by jomdolalas** [comment]
@batrlatom what you mean by FROM image is the first line in this code right?

FROM nvcr.io/nvidia/l4t-pytorch:r32.5.0-pth1.7-py3

# Install linux packages
RUN apt update && apt install -y zip htop screen libgl1-mesa-glx

# Install python dependencies
COPY requirements.txt .
RUN python3 -m pip install --upgrade pip
RUN pip3 install --no-cache -r requirements.txt gsutil notebook

# Create working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Copy contents
COPY . /usr/src/app

# Set environment variables
ENV HOME=/usr/src/app

**Comment by batrlatom** [comment]
@jomdolalas Yes, 
the line ```FROM nvcr.io/nvidia/l4t-pytorch:r32.5.0-pth1.7-py3 ``` states that the build uses
nvidia official image with preinstalled pytorch and add new stages from there. What you need to do is
to find a docker image with pytorch already installed and use it as a base or start from scratch and
install pytorch yourself in the docker build by using RUN command. 

For more information, please take a look to the official docker documentation https://docs.docker.com/develop/develop-images/baseimages/
