### ISSUE TITLE
How to reduece the inference time？

### ISSUE THREAD

**Issue by sky-fly97** [ultralytics/yolov5#24]
Compared with v3-spp， the time of inference is **twice** long. And the aug is important so that I can not remove it. 
Is there any way to **speed up without losing too much map?**

**Comment by glenn-jocher** [comment]
@sky-fly97 we are continuously researching speed and accuracy improvements. If you have proven ideas that show quantitative improvement we'd be happy to integrate them into our work. 

If you have GPU resources you'd like to contribute to the research we can send you docker files to run as well, which will speed up our research and lead to improvements faster.

**Comment by glenn-jocher** [comment]
@sky-fly97 new models have been released yesterday which are smaller and faster. See the readme table for updated speeds.

**Comment by sky-fly97** [comment]
> @sky-fly97 new models have been released yesterday which are smaller and faster. See the readme table for updated speeds.

Wow,  Thank you for your efforts！

**Comment by sljlp** [comment]
speed of the smallest model inference on cpu is 3 fps? could you please give me some advice on how to speed up?

**Comment by glenn-jocher** [comment]
@sljlp I think for any ML model in object detection, CPU performance will always be quite slow. YOLOv5s is faster on CPU than efficientdet D0, but as you see it still does not compare to GPU speeds, or neural engines like Apple's 5 TOPS ANE speed. These are really the only acceptable solutions if you want fast inference today.
