### ISSUE TITLE
some questions about parameters

### ISSUE THREAD

**Issue by bixiaopeng0** [ultralytics/yolov5#240]
- what 's the meaning of parameters --bucket? sorry i can't understand `help='gsutil bucket'`
- and if i use one class dataset,Would it be better to use --single-cls parameters ？

**Comment by glenn-jocher** [comment]
--bucket sends training results to a GCP bucket. --single-cls trains any dataset in single class mode

**Comment by bixiaopeng0** [comment]
thanks!
