### ISSUE TITLE
RuntimeError: a view of a leaf Variable that requires grad is being used in an in-place operation.

### ISSUE THREAD

**Issue by JoaoMoranguinho** [ultralytics/yolov5#2403]
When running the default Google Colab notebook a "RuntimeError: a view of a leaf Variable that requires grad is being used in an in-place operation." message is generated in the training phase of the model.

As I understand this issue is generated in the initialize_biases function in /models/yolo.py (line 150).

`with torch.no_grad():` seems to solve this problem.

I don't know if this was a recent change in versioning or if it was a problem in my specific case.

If any other solutions arise please be sure to share them.

**Comment by glenn-jocher** [comment]
@JoaoMoranguinho I think this was resolved a long time ago in master. Are you using the official colab notebook here?
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

If you are using the latest master code and the notebook above and still see a reproducible issue, we suggest you close this issue and raise a new one using the 🐛 **Bug Report template**, providing screenshots and a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. Thank you!

**Comment by AmulPatil** [comment]
Was facing same issue. its  resolved by removing below command from roboflow version of colab script
!git reset --hard 68211f72c99915a15855f7b99bf5d93f5631330f

**Comment by glenn-jocher** [comment]
@AmulPatil @JoaoMoranguinho we do not support 3rd party training tools. 

I would highly recommend using the official Colab notebook, which works correctly and is always up to date with the latest YOLOv5 version.
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb
