### ISSUE TITLE
Can't train in DDP mode after recent update

### ISSUE THREAD

**Issue by wudashuo** [ultralytics/yolov5#2405]
## 🐛 Bug

When I pull the latest code, I found that DDP training would get stuck in the first few epochs.
I ran some tests to see which commit caused this bug and I found commit `a3ecf0fd640465f9a7c009e81bcc5ecabf381004` on Mar 3 worked well. 
But when I `git checkout` commit `e931b9da33f45551928059b8d61bddd50e401e48` on Mar 4, the bug appeared. 
And the bug still exists in the latest commit.

## To Reproduce (REQUIRED)
`python3 -m torch.distributed.launch --nproc_per_node 4 train.py`

The training process would get stuck forever unless you terminate it manually.
And it still occupied the GPU memory unless killing the process by `kill -9 xxxxx`

![stuck](https://user-images.githubusercontent.com/5948604/110415966-daa79980-80cd-11eb-8e8d-f7f56c2c9cd5.png)

## Expected behavior
Roll back to the older code, and get the expected behavior.
```bash
$ git checkout a3ecf0fd640465f9a7c009e81bcc5ecabf381004
$ python3 -m torch.distributed.launch --nproc_per_node 4 train.py
```
![worked well](https://user-images.githubusercontent.com/5948604/110415987-e004e400-80cd-11eb-8fea-b00a5305459e.png)

## Environment

 - OS: Ubuntu 20.04
 - GPU: 1080 Ti * 4
 - Python: 3.8
 - pytorch: 1.7.1
 - CUDA: 11.1
 - Driver:  455.32

## Additional
It seems like the latest commit working fine on 2 * 3090, I'm not sure yet, I will do some further tests on 3090 or other GPU.

**Comment by glenn-jocher** [comment]
@wudashuo thanks for the bug report! I'm not currently training DDP so can't verify correct operation of master myself. I looked at the compare between the commit you said worked well and the one said produced the error. There is only 1 commit between those, but I don't see anything obvious that would impact DDP training:
https://github.com/ultralytics/yolov5/compare/a3ecf0fd640465f9a7c009e81bcc5ecabf381004...e931b9da33f45551928059b8d61bddd50e401e48

In general when training DDP I always use the Docker image, for stability and reproducibility but also for speed. If you are having issues in a local or cloud environment I would recommend retrying your trainings in the docker image instead. Once docker is installed it's very easy to start training in an image, and I've found that sometimes its a lot faster also than using the native GCP/AWS deep learning AMIs.

**Comment by glenn-jocher** [comment]
@wudashuo the docker image is on pytorch 1.8 by the way, and its built 'FROM' the latest Nvidia and Facebook PyTorch image https://ngc.nvidia.com/catalog/containers/nvidia:pytorch, so the authors are incentivized to produce working images.

**Comment by wudashuo** [comment]
I currently don't have the `sudo` permission, so I can't test the bug in Docker images for now, but I'll test it later today after I got the root user.

I ran some further DDP training tests on GTX1650 * 2, and I got the same problem as I described before.
Maybe something wrong with commit `e931b9da33f45551928059b8d61bddd50e401e48`
![commits](https://user-images.githubusercontent.com/5948604/110427937-74c60c80-80e3-11eb-8c9a-2b518fca80bb.png)

I don't know if this helps you to debug:
When training on the earlier commit, everything worked well, but there is always a warning that said `Reducer buckets have been rebuilt in this iteration.` in the first epoch. It comes from `torch.nn.parallel.distributed.py`, I am not familiar with it.
![image](https://user-images.githubusercontent.com/5948604/110429295-a4761400-80e5-11eb-8a59-5ecf2f62cd30.png)
But there is no such warning in the commit `e931b9d` and later commit, which are all have stucking problem in DDP training:
![stuck](https://user-images.githubusercontent.com/5948604/110429653-3847e000-80e6-11eb-967a-cec621def342.png)

If I get the root permission I will test it in the Docker image and update this issue.

**Comment by roytseng-tw** [comment]
https://github.com/ultralytics/yolov5/blob/e8a2b83268950e346899a84e8d29e84d178553b1/train.py#L184-L218

line 217: `model.half().float()  # pre-reduce anchor precision` is the reason causing ddp hang.
Currently, the model is wrapped by DDP before line 217 at line 186.
Need to do the wrapping AFTER `model.half().float()`.
Like,
```python
            # Anchors
            if not opt.noautoanchor:
                check_anchors(dataset, model=model, thr=hyp['anchor_t'], imgsz=imgsz)
            model.half().float()  # pre-reduce anchor precision 

    # DDP mode
    if cuda and rank != -1:
        model = DDP(model, device_ids=[opt.local_rank], output_device=opt.local_rank)
```

BTW, what's the purpose of `model.half().float()`? Why do we need to reduce anchor precision?

**Comment by glenn-jocher** [comment]
@roytseng-tw ah interesting. Maybe this is because the if `rank in [-1, 0]` command means this line is only applying to the rank 0 process?

Anchor precision is preemptively reduced by this line before training starts to allow the model to train on the FP16-precision anchors. Without this the model would train on FP32 anchors, which may be altered slightly when the model is saved as FP16. I introduced this line after observing autoanchor compute an FP32 anchor as 8.249, which then was degraded to 8.250 when the model was cast to model.half().

test.py is casting the EMA to .half() everytime it tests at the end of each epoch, this line does the same for the model before training start. I'll have to think about the best solution (other than removing the line).

**Comment by glenn-jocher** [comment]
@roytseng-tw yes I think the DDP line can be moved to where you suggested. Have you been able to train this way without issue?

**Comment by roytseng-tw** [comment]
@glenn-jocher  Yes, I'am able to train without hang.

**Comment by glenn-jocher** [comment]
@roytseng-tw ok, thanks for the feedback. I'll make the change then!
