### ISSUE TITLE
The GPU cannot be used in the container

### ISSUE THREAD

**Issue by Olalaye** [ultralytics/yolov5#2406]
I'am just following this [link](https://github.com/ultralytics/yolov5/wiki/Docker-Quickstart)
 - **Current repo**: run `sudo docker pull ultralytics/yolov5:latest`
 - **Common dataset**: none
 - **Common environment**: Docker image. 
 

## 🐛 Bug
The GPU cannot be used in the container.

## To Reproduce (REQUIRED)

Input:
```
# pull image 
sudo docker pull ultralytics/yolov5:latest

# run container
sudo docker run --ipc=host --gpus all -it ultralytics/yolov5:latest

# run command
python -c "import torch; print(torch.cuda.is_available())"
```

Output:
```
/opt/conda/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at  ../c10/cuda/CUDAFunctions.cpp:104.)
  return torch._C._cuda_getDeviceCount() > 0
False
```

## Expected behavior
Use the GPU in the container.

## Environment

 - OS: Ubuntu 20.04
 - GPU: GeForce RTX 3090

**Comment by glenn-jocher** [comment]
@Olalaye this may be an indicator of underlying issues in the Docker install itself, or possibly the underlying CUDA install I think.

I verified the Docker image with a 3090 instance just now from vast.ai, and your test command, the nvidia-smi command, and a detect.py inference command all work well, so I'm not able to reproduce this problem.

## vast.ai RTX 3090 instance rental
Note that all vast.ai instances are Docker images, with docker image name specified in upper left.
<img width="1420" alt="Screen Shot 2021-03-08 at 10 22 02 PM" src="https://user-images.githubusercontent.com/26833433/110428476-2a4e7c80-805e-11eb-9090-8c5abe9ffbcd.png">

## SSH commands inside Docker container
<img width="1116" alt="Screen Shot 2021-03-08 at 10 28 55 PM" src="https://user-images.githubusercontent.com/26833433/110428485-2d496d00-805e-11eb-8f99-c06f4748aba0.png">

**Comment by glenn-jocher** [comment]
@Olalaye found this with a Google search:
https://github.com/pytorch/pytorch/issues/47038

**Comment by Olalaye** [comment]
@glenn-jocher Thank you very much for your reply.
I avoided the problem by rebooting the computer, but I still don't know what went wrong. 
Unfortunately, I need to do the same next time.
