### ISSUE TITLE
FP32 and FP16

### ISSUE THREAD

**Issue by yinyuhangi** [ultralytics/yolov5#2407]
## ❔Question
Hello. The computer I am using is Tiitan Xp, which does not support FP16 inference. Without loading the pre-training weights, the size of the yolov5s model after I trained is 14.5MB, is this automatically saved in FP32 format?

**Comment by glenn-jocher** [comment]
@yinyuhangi final checkpoints are saved in FP16.

All of the GPUs support FP16 inference, though some of them do not achieve any speed benefit from using FP16 (apart from allowing a 2x larger batch size). Pascal generation GPUs fall into this category, like the P100 and 1080Ti. 

Volta and Ampere GPUs like the 2080Ti, 3090, V100, A100, T4 have dedicated FP16 cores that allow for faster execution times vs FP32.

**Comment by yinyuhangi** [comment]
ok. Thanks!
