### ISSUE TITLE
when I changed the degree of the hyperparameter to 30, does yolov5 use both the original image and the rotated image for training?

### ISSUE THREAD

**Issue by parksh089g** [ultralytics/yolov5#2410]
when I changed the degree of the hyperparameter to 30, does yolov5 use both the original image and the rotated image for training? Or only use the rotated image?

**Comment by glenn-jocher** [comment]
@parksh089g hyperparameters define probability distributions over an n-d space that are randomly sampled at the time of dataloading, and are then applied as projective transforms and HSV transforms to each image or mosaic. We have a slide that illustrates this workflow. Effectively no image is ever presented twice the same way during training.

![YOLOv5 augmentation](https://user-images.githubusercontent.com/26833433/110527336-b0ed7300-80cb-11eb-9da8-0986939c89bb.jpg)

**Comment by adamhrv** [comment]
Are the `train_batch{ni}.jpg` plots generated from [plot_images()](https://github.com/ultralytics/yolov5/blob/master/train.py#L325) showing same bounding boxes used during training or does this visualization omit the rotation transformation? In above image, it seems the plane is no longer accurately contained by the bounding box.

Am trying to debug training with a custom dataset and wondering if this might be one of the reasons performance is lower than expected. But it looks like transformations are being applied to images and labels here https://github.com/ultralytics/yolov5/blob/master/utils/datasets.py#L903 so I'm not sure if maybe `plot_images` only shows non-rotated boxes, but with rotated img.

For example, in hyp `degrees: 90  # image rotation (+/- deg)` and box extends to nearly full frame:
![Screenshot from 2021-03-18 16-32-43](https://user-images.githubusercontent.com/199849/111652769-a3409780-8807-11eb-9c6a-8bc7e4a25214.png)

**Comment by glenn-jocher** [comment]
@adamhrv for box labels, it's not a question of whether the augmented plane is contained by the augmented box, but whether the contents of the original box are contained by the augmented box (yes). 

For segmentation labels (img.txt as `[class xy1, xy2, xy3, x4, xy5, ...]`) the augmented box contains the actual segmentation contents (i.e. would better fit the augmented plane).

**Comment by glenn-jocher** [comment]
@adamhrv but yes, if you are using large rotation angles, then at 45 degrees the augmented boxes will have the poorest fit to the original box contents.
