### ISSUE TITLE
If I reduce the image size Will the model become smaller?

### ISSUE THREAD

**Issue by leeyunhome** [ultralytics/yolov5#2416]
## ❔Question

Hello, @glenn-jocher 

!python train.py --img 416 --batch 3 --epochs 500
If I reduce the image size
Will the model become smaller?

It was small when I experimented, but I don't know exactly, so I ask.

Thank you.

**Comment by glenn-jocher** [comment]
@leeyunhome no, the model size is not a function of --img-size, they are independent.

**Comment by leeyunhome** [comment]
> @leeyunhome no, the model size is not a function of --img-size, they are independent.

Hello,

When the size of the .pt file is small, I have experienced a faster inference speed.
If the image-size is smaller, the size of the .pt file is also smaller
![image](https://user-images.githubusercontent.com/59910227/110562058-27ea4080-818c-11eb-8acb-77f82c4af92d.png)

The unit is MB.

Thank you.

**Comment by glenn-jocher** [comment]
@leeyunhome reduced image sizes will lead to reduced inference time. Model size is constant and not a function of any inference parameters.

**Comment by leeyunhome** [comment]
> @leeyunhome reduced image sizes will lead to reduced inference time. Model size is constant and not a function of any inference parameters.

Hello,

In addition to resizing the image, what affects the inference spped
Is it just the use of spcecialized engines like tensorRT?

Thank you.

**Comment by glenn-jocher** [comment]
@leeyunhome using smaller models, smaller images, and batched inference will all speed up your inference time per image. Exporting to TensorRT should also speed up inference.

**Comment by leeyunhome** [comment]
> @leeyunhome using smaller models, smaller images, and batched inference will all speed up your inference time per image. Exporting to TensorRT should also speed up inference.

@glenn-jocher 
The smallest model is yolov5s
Batch inference means that you bundle multiple images and process them in batches?

**Comment by glenn-jocher** [comment]
@leeyunhome yes. If you use batch size of 16 for example then you should see faster speeds per image than running batch size 1 in a for loop for each image.

**Comment by leeyunhome** [comment]
> @leeyunhome yes. If you use batch size of 16 for example then you should see faster speeds per image than running batch size 1 in a for loop for each image.

@glenn-jocher 

![image](https://user-images.githubusercontent.com/59910227/110726861-86332400-825d-11eb-96f7-15e1abef95ca.png)

When training, I set the batch size to 16
The batch size given as a factor affects the learning speed, right?

When inferring, do I have to set the batch size separately?

**Comment by glenn-jocher** [comment]
@leeyunhome training results are robust to variations in batch size (https://github.com/ultralytics/yolov5/issues/2377) detect.py runs at --batch 1 for the most part. You can explore batch size speedups in test.py:

```bash
python test.py --data coco128.yaml --weights yolov5s.pt --batch 1
python test.py --data coco128.yaml --weights yolov5s.pt --batch 16
python test.py --data coco128.yaml --weights yolov5s.pt --batch 64
```
