### ISSUE TITLE
Have segmentation fault during training.

### ISSUE THREAD

**Issue by GryffindorLi** [ultralytics/yolov5#2419]
## ❔Question
I trained yolov5s on coco17 dataset for object detection. And I have received segmentation fault during training, as shown below:
![image](https://user-images.githubusercontent.com/40144709/110583961-73f7ae00-81a9-11eb-8188-04666e92db54.png)
This error occurs randomly during training, and each time it appears at different time.

My environment is pytorch 1.3.0 + torchvision 0.4.1 + cuda 10.2, and I trained on 8 Tesla V100 GPU.

**Comment by glenn-jocher** [comment]
@GryffindorLi as the bot says, you'll definitely need to update your torch version. For DDP I would also highly recommend the Docker image, which of course comes with it's own environment that works correctly.
