### ISSUE TITLE
what kind of GPU will be supported for docker image

### ISSUE THREAD

**Issue by Jelly123456** [ultralytics/yolov5#2420]
## ❔Question
I am very new to use docker image. I installed docker followed this link(https://github.com/ultralytics/yolov5/wiki/Docker-Quickstart)

But when I run command: the below error shows:
`sudo docker run --ipc=host --gpus all -it ultralytics/yolov5:latest`

![image](https://user-images.githubusercontent.com/29449336/110589948-174cc100-81b2-11eb-9cb5-3eb29391c24f.png)

But when I run nvida-smi command, the driver already meets the requirement to be greater than 455.23.

![image](https://user-images.githubusercontent.com/29449336/110590678-123c4180-81b3-11eb-8b2e-c2e0d51db818.png)

## Additional context
OS: Ubuntu 20.4

Any experienced person helps me to solve this?

**Comment by glenn-jocher** [comment]
@Jelly123456 I don't have a list of supported GPUs, but you can find more documentation on the Docker base image here:
https://ngc.nvidia.com/catalog/containers/nvidia:pytorch
