### ISSUE TITLE
what's the output_layer_name 437 means?

### ISSUE THREAD

**Issue by UNeedCryDear** [ultralytics/yolov5#2426]
## ❔Question
what's the output_layer_name 437 means?

## Additional context
I used yolov5s.pt to export onnx model，then use Netron(https://netron.app/) to load onnx. In the output , I see three outputs(classes,boxes and 437),The first two are understandable, but what is the 437？

![11](https://user-images.githubusercontent.com/52729998/110724228-5a5d7180-8250-11eb-9fa4-152d46de0a68.jpg)
Because they are normalized data, how can I get the original data by renormalization

**Comment by glenn-jocher** [comment]
@UNeedCryDear P5/32 output layer (large objects). The other two are incorrectly names, they are P3/8 (small objects) and P4/16 (medium objects).

**Comment by UNeedCryDear** [comment]
@glenn-jocher thanks。
