### ISSUE TITLE
wandb/debug-internal.log: Permission denied

### ISSUE THREAD

**Issue by fanghua2021** [ultralytics/yolov5#2427]
I run train.py,but there is a problem that cannot be solved.

wandb: Network error (ConnectionError), entering retry loop. See wandb/debug-internal.log for full traceback.
wandb: W&B API key is configured (use `wandb login --relogin` to force relogin)
wandb: Network error (ConnectionError), entering retry loop. See wandb/debug-internal.log for full traceback.

I run ‘wandb/debug-internal.log’
The result appears： (pytorch1.7) -bash-4.2$ wandb/debug-internal.log
                                   -bash: wandb/debug-internal.log: Permission denied

I searched for a long time and couldn't solve this problem.And can you turn wandb off?

**Comment by glenn-jocher** [comment]
@fanghua2021 not sure what the error means but you can enable and disable wandb with `$ wandb enabled` and `$ wandb disabled`
