### ISSUE TITLE
ONNX export failure: Input, output and indices must be on the current device

### ISSUE THREAD

**Issue by buimanhlinh96** [ultralytics/yolov5#2428]
## ❔Question
Hi @glenn-jocher ,
I am trying export model from pytorch to onnx. I set --grid argument to ignore Detect layer. 
But I met a isssue :ONNX export failure: Input, output and indices must be on the current device
How can I solve this problem? Thanks
![Screenshot from 2021-03-11 13-48-51](https://user-images.githubusercontent.com/61372071/110747197-943e7000-8270-11eb-8763-2ae3256a920f.png)

**Comment by glenn-jocher** [comment]
@buimanhlinh96 yes I see this error as well when I reproduce your command. --device is a new argument, it seems it's not been properly tested.

But setting --grid does not achieve what you say you want, it includes the Detect() layer grid reconstructions and concatenation ops.
https://github.com/ultralytics/yolov5/blob/886f1c03d839575afecb059accf74296fad395b6/models/export.py#L28

**Comment by glenn-jocher** [comment]
@buimanhlinh96 this behavior is actually documented here:
https://github.com/ultralytics/yolov5/pull/2297#issuecomment-792032930

Workaround is to use either --grid or --device but not both.
