### ISSUE TITLE
Can't download weights.pt

### ISSUE THREAD

**Issue by helen12138** [ultralytics/yolov5#243]
Hi all , sorry to bother you!
I can't connect to drive.google! 
Could you provide some other sites to download pretrained weights please？

**Comment by MagicFrogSJTU** [comment]
If you are in mainland China, you should resort to certain VPN services

**Comment by glenn-jocher** [comment]
@helen12138 weights are downloaded automatically, i.e. try running

`python detect.py --weights yolov5s.pt`

**Comment by helen12138** [comment]
> @helen12138 weights are downloaded automatically, i.e. try running
> 
> `python detect.py --weights yolov5s.pt`

@glenn-jocher @MagicFrogSJTU Thanks a lot! I have downloaded weights automatically , with command above.

**Comment by glenn-jocher** [comment]
@helen12138 great! Where are you in the world?

The automatic download function attempts two different sources, so even if the google drive folder is inaccessible the second source may work.

**Comment by helen12138** [comment]
@glenn-jocher 
I'm in China. Thank you very much ! :)

**Comment by hendryjwr** [comment]
Hi there, I'm currently getting the error shown below when trying to do some training. I'm based in the UK but looks like it's having an issue with SSL certificates? Any tips? Thanks!
```
Downloading https://github.com/ultralytics/yolov5/releases/download/v4.0/yolov5s.pt to yolov5s.pt...
Download error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>
```

**Comment by hendryjwr** [comment]
My bad, looks like an issue with MacOS not installing certificates to the terminal. All sorted now :)
