### ISSUE TITLE
How to change the shape of the model?

### ISSUE THREAD

**Issue by UNeedCryDear** [ultralytics/yolov5#2431]
## ❔Question
How to change the shape of the model?

## Additional context
Thank you for your help, but now I have a new problem. In the yolov5s.onnx model,the output have shape[1,3,20,20,85] like the picture. How can I modify the code so that the shape of the output becomes[3,20,20,85],if I want to remove the outermost dimension.
![111](https://user-images.githubusercontent.com/52729998/110769302-fb6d1c00-8292-11eb-8eee-04d4dbc9ea93.png)

**Comment by glenn-jocher** [comment]
@UNeedCryDear I'm not sure I understand your question, but you may want to export your model with the --grid flag to create a single output (same as the pytorch models).

**Comment by UNeedCryDear** [comment]
@glenn-jocher It's my fault. I didn't make it clear. Now the onnx model have three output names("classes"(P3/8 output),"boxes"( P4/16),"437"(P5/32)),there have shape “[batch_size,channel，width,hight,num_class+5]”(classes:[1,3,80,80,85]),But I want model output shape to be ”[channel，width,hight,num_class+5]”,jiust like:

> classes=torch.squeeze(classes)#Remove the dimension of batch size

>  boxes=torch.squeeze(boxes)#Remove the dimension of batch size

> 437=torch.squeeze(437) #Remove the dimension of batch size

**Comment by glenn-jocher** [comment]
@UNeedCryDear oh I see. Well export.py just exports whatever model you pass to it. You can modify the Detect() layer here to suit your needs and then export:
https://github.com/ultralytics/yolov5/blob/886f1c03d839575afecb059accf74296fad395b6/models/yolo.py#L22-L57

**Comment by UNeedCryDear** [comment]
Thank you. I've solved it with your help.
