### ISSUE TITLE
Experiments on GhostNet

### ISSUE THREAD

**Issue by zachluo** [ultralytics/yolov5#2432]
## ❔Question
I am just wondering about the performance when using GhostNet in experimental.py. Could you please share this experiment?

**Comment by glenn-jocher** [comment]
@zachluo we don't have a comprehensive study, and the answer of course would depend on many variables, such as which layers were replaced, and the composition of the ghost operations in each module.

You can start experimenting with using Ghost convolutions in your training workflows by replacing C3() modules with GhostBottleneck() modules in your model.yaml file, and then starting training from your new model.yaml.
