### ISSUE TITLE
Is it possible to train at 320 size based on the model trained at 500 epochs with 640x640 image size?

### ISSUE THREAD

**Issue by leeyunhome** [ultralytics/yolov5#2434]
## ❔Question

Hello,

The following error appears when training again with a size of 320 based on a model that has been trained at 500 epochs with a 640x640 image size.

Is it impossible?

Analyzing anchors... anchors/target = 2.91, Best Possible Recall (BPR) = 0.9999
Image sizes 320 train, 320 test
Using 8 dataloader workers
Logging results to runs/train/lpr_result20
Starting training for 508 epochs...

     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
   459/507     1.78G    0.1345   0.05271    0.1162    0.3035       174       320:   0%|          | 1/2625 [00:01<1:02:27,  1.43s/it]
Traceback (most recent call last):
  File "train.py", line 512, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 299, in train
    scaler.step(optimizer)  # optimizer.step
  File "/home/yhlee/anaconda3/envs/yolov3_env/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 321, in step
    retval = optimizer.step(*args, **kwargs)
  File "/home/yhlee/anaconda3/envs/yolov3_env/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 67, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/yhlee/anaconda3/envs/yolov3_env/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/home/yhlee/anaconda3/envs/yolov3_env/lib/python3.8/site-packages/torch/optim/sgd.py", line 106, in step
    buf.mul_(momentum).add_(d_p, alpha=1 - dampening)
RuntimeError: **The size of tensor a (324) must match the size of tensor b (128)** at non-singleton dimension 0

Thank you.

**Comment by glenn-jocher** [comment]
@leeyunhome the size of images a model is trained on has no relation to it's architecture or capacity to serve as a pretrained model for further trainings. 

**YOLOv5 models trained on any dataset (with any training settings or hyps) may be used a pretrained model for further trainings (on any other dataset) downstream.**

If you believe you have a reproducible issue, we suggest you close this issue and raise a new one using the 🐛 **Bug Report template**, providing screenshots and a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. Thank you!

**Comment by leeyunhome** [comment]
Thank you.

**Comment by leeyunhome** [comment]
> @leeyunhome the size of images a model is trained on has no relation to it's architecture or capacity to serve as a pretrained model for further trainings.
> 
> **YOLOv5 models trained on any dataset (with any training settings or hyps) may be used a pretrained model for further trainings (on any other dataset) downstream.**
> 
> If you believe you have a reproducible issue, we suggest you close this issue and raise a new one using the 🐛 **Bug Report template**, providing screenshots and a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. Thank you!

Hello,

I think I will need a custom dataset to reproduce it, but I can't disclose this.

Thank you.

**Comment by leeyunhome** [comment]
Hello,

I think I will need a custom dataset to reproduce it, but I can't disclose this.

Thank you.
