### ISSUE TITLE
Cannot find reference 'fitness' in 'general.py'

### ISSUE THREAD

**Issue by BrianKenobi** [ultralytics/yolov5#2440]
## ❔Question
As the screenshots you can see. It says **"Cannot find reference 'fitness'** in **'general.py'".**
So i check the **general.py** profile, and it seems like **general.py** import fitness from **utils.metrics** .
Still not sure what kind of bug it would occur.

<img width="928" alt="fitness bug" src="https://user-images.githubusercontent.com/50870564/110902699-3fb6f580-8341-11eb-92cb-1174e324b7f0.png">
<img width="960" alt="fitness bug2" src="https://user-images.githubusercontent.com/50870564/110902707-447ba980-8341-11eb-9221-9121bc2e8243.png">

**Comment by glenn-jocher** [comment]
@BrianKenobi fitness is imported in general.py from metrics.py. Everything works correctly.

**Comment by BrianKenobi** [comment]
Just like false alarm i guess. I am still training. if there is any issue i'll report to you. Thanks!

**Comment by Jorlin24** [comment]
Is it finally resloved?

**Comment by glenn-jocher** [comment]
fitness function is in metrics.py:
https://github.com/ultralytics/yolov5/blob/d059d1da03aee9a3c0059895aa4c7c14b7f25a9e/utils/metrics.py#L15-L19
