### ISSUE TITLE
Images in MPO Format are considered corrupted

### ISSUE THREAD

**Issue by maxupp** [ultralytics/yolov5#2446]
I am using images taken by a DJI drone. These images are deemed corrupted by the dataset loader, and are thus not used.
This happens because in datasets.py the `im.format` is checked against a list of formats that doesn't contain "mpo".
If I add that entry manually everything works as expected.

MPO is a container format, that can contain any of the valid formats.

## 🐛 Bug
Images that report "MPO" as PIL.Image.format are deemed corrupted.

## To Reproduce (REQUIRED)
Try to load MPO images.
![DJI_0180](https://user-images.githubusercontent.com/5763229/110967292-819e6680-8356-11eb-97f0-35e6be8cc00b.JPG)

I'm not sure whether Github tempers with the image. If necessary I can upload somewhere else.

## Expected behavior
Images should be considered valid.

**Comment by glenn-jocher** [comment]
@maxupp ah interesting, thanks for the bug report!

If *.mpo suffixes work then we should add them to the list. We recently added *.webp as well based on user feedback. Can you add the format to the approved formats list here, and verify correct operation for your training set, and submit a PR if everything goes well please? Thanks!

https://github.com/ultralytics/yolov5/blob/886f1c03d839575afecb059accf74296fad395b6/utils/datasets.py#L27-L30

**Comment by glenn-jocher** [comment]
Removed TODO as *.mpo now added to YOLOv5 supported image formats.
