### ISSUE TITLE
How to export the exactly same yolov5s.onnx available in releases v4.0?

### ISSUE THREAD

**Issue by SCarVito** [ultralytics/yolov5#2447]
## ❔Question
Hello,
I'm working on deploying YOLOv5s model on mobile devices. 
There're some unsupported operations in the Detection layer, so that I tried several approaches to export the ONNX model with NMS on my own. None of them succeeded. 

But I found out that the yolo5s.onnx provided in releases v4.0 works pretty well. 
So, could you tell me how did you make it?

Thanks.

**Comment by glenn-jocher** [comment]
@SCarVito we provide more comprehensive export solutions to business clients, yolov5s.onnx in the v4.0 release is an example of this.
