### ISSUE TITLE
Problems with weights

### ISSUE THREAD

**Issue by qweqweq1222** [ultralytics/yolov5#2467]
## ❔Question
Hello, I have just run trainy.py script with my data and faced a problem - you wrote that weights are saved in runs directory, but in my case I have not found them. Everything is fine with hyp.yaml and opt.yaml but folder "weights" is empty. 
Do you have any guesses about this issue?

**Comment by glenn-jocher** [comment]
@qweqweq1222 after training your results should be logged to runs/train/exp, with last.pt and best.pt in runs/train/exp/weights. If this is not the case then perhaps you trained with the --nosave flag, which will not save weights.

**Comment by Sharms84** [comment]
I have the same problem .the weights directory is empty

**Comment by glenn-jocher** [comment]
@Sharms84 hi there,

I'm sorry to hear that you're experiencing the same issue with the empty "weights" directory. In most cases, the weights should be saved in the "runs/train/exp/weights" directory after training.

If you're finding that the directory is empty, there are a few things you can check:

1. Make sure you're running the train script with the `--save_weights` flag enabled. Without this flag, the weights will not be saved.
2. Verify that the training process completed successfully without any errors. If there were any errors during training, it's possible that the weights were not saved.
3. Check the permissions of the directory where the weights should be saved. Make sure that the directory is writable and accessible for the user running the training script.

If none of the above suggestions help, please provide more details about your training setup, such as the command you used to run the train script, any error messages you encountered, and any relevant configurations you made.

The YOLOv5 community and the Ultralytics team are here to assist you further. Please don't hesitate to reach out if you have any more questions or need additional help.

Best regards,
Glenn Jocher
