### ISSUE TITLE
Scanning for images and labels

### ISSUE THREAD

**Issue by saitarslanboun** [ultralytics/yolov5#2468]
## ❔Question
Dear YoloV5 developer, @glenn-jocher ! 

Sorry for distracting you within your busy schedule, but I would like to have a minor question.

`desc = f"Scanning '{cache_path}' for images and labels... {nf} found, {nm} missing, {ne} empty, {nc} corrupted"`

On the above code snippet, existing under `utils/datasets.py`, what do `nf`, `nm`, `ne`, and `nc` respectively represent?

Could you briefly explain?

Kind regards,

**Comment by glenn-jocher** [comment]
@saitarslanboun the variable definitions are right next to their usage, these are the image numbers in each category:
{nf} found, {nm} missing, {ne} empty, {nc} corrupted

**Comment by saitarslanboun** [comment]
Thank you for your quick answer, @glenn-jocher . Let me show you what I understood with the terms.

**nf:** It probably means number of images found.
**nm:** It probably means number of images stated within annotation, but missing as image files under the folder.
**ne:** What it means? Could you give more hint here? What is the difference between **nm** and **ne**?
**nc:** Corrupted images?

Kind regards,

**Comment by glenn-jocher** [comment]
@saitarslanboun yes that's correct! nf is the number of matching images and labels found, nm is the number of missing labels *.txt files, ne is the number of empty label files, nc is the number of corrupted instances.
