### ISSUE TITLE
How to draw the results of multiple models into one PR curve

### ISSUE THREAD

**Issue by phunix9** [ultralytics/yolov5#2471]
Hi, I have used yolov5 in my dataset successfully and thank you for so important work!

I have a question here.

I want to tarin and test multiple models and I need to draw a PR curve that including several models' results.

I have seen your figures in the Introduction such as Recall and Precision. Now I want to draw the results in a PR curve as those.

How could I do? 

Thanks

**Comment by glenn-jocher** [comment]
@phunix9 PR curve is saved as PR_curve.png in your run/train/exp or runs/test/exp directory:
![image](https://user-images.githubusercontent.com/26833433/111105772-eb627000-8510-11eb-8715-60015bd43645.png)

Only a single model is plotted at a time. You can run test.py with each model you want to plot to generate multiple plots. If you'd like to customize this plot you can find it here:

https://github.com/ultralytics/yolov5/blob/2d41e70e828c215a3c8486bb24ac2169084079f1/utils/metrics.py#L186-L204

**Comment by phunix9** [comment]
Thank you very much! I will try it.
