### ISSUE TITLE
usig the docker image and tensorrt has error!! help  tks!!

### ISSUE THREAD

**Issue by henbucuoshanghai** [ultralytics/yolov5#2474]
**Current repo**:  ,download .pt from yolov5 release v4.0, 
          git clone -b v4.0 https://github.com/ultralytics/yolov5.git 
         and git clone https://github.com/wang-xinyu/tensorrtx.git.

the code is official yolov5 and my docker image is official too.
In        docker exec -it -e yolo /bin/bash
In yolov5.cpp, I get the yolov5.wts successfully,and in 'build',   make

## 🐛 Bug
make
[ 20%] Building NVCC (Device) object CMakeFiles/myplugins.dir/myplugins_generated_yololayer.cu.o
/tensorrtx/yolov5/yololayer.h(85): warning: function "nvinfer1::IPluginV2Ext::configurePlugin(const nvinfer1::Dims *, int32_t, const nvinfer1::Dims *, int32_t, const nvinfer1::DataType *, const nvinfer1::DataType *, const __nv_bool *, const __nv_bool *, nvinfer1::PluginFormat, int32_t)" is hidden by "nvinfer1::YoloLayerPlugin::configurePlugin" -- virtual function override intended?

tensorrtx/yolov5/yololayer.h(85): warning: function "nvinfer1::IPluginV2Ext::configurePlugin(const nvinfer1::Dims *, int32_t, const nvinfer1::Dims *, int32_t, const nvinfer1::DataType *, const nvinfer1::DataType *, const bool *, const bool *, nvinfer1::PluginFormat, int32_t)" is hidden by "nvinfer1::YoloLayerPlugin::configurePlugin" -- virtual function override intended?

Scanning dependencies of target myplugins
[ 40%] Linking CXX shared library libmyplugins.so
[ 40%] Built target myplugins
Scanning dependencies of target yolov5
[ 60%] Building CXX object CMakeFiles/yolov5.dir/calibrator.cpp.o
[ 80%] Building CXX object CMakeFiles/yolov5.dir/yolov5.cpp.o
[100%] Linking CXX executable yolov5
[100%] Built target yolov5

Then run the              ./yolov5 -s yolov5s.wts yolov5s.engine s
Loading weights: ../yolov5s.wts
CUDA error 222 at  /tensorrtx/yolov5/yololayer.cu:37yolov5: /tensorrtx/yolov5/yololayer.cu:37: nvinfer1::YoloLayerPlugin::YoloLayerPlugin(int, int, int, int, const std::vector<Yolo::YoloKernel>&): Assertion `0' failed.
Aborted (core dumped)

## Environment
I have      docker pull ultralytics/yolov5:latest
and have a docker environment.
 - OS: [ Ubuntu]
 - GPU [   one  2080 Ti]

**Comment by glenn-jocher** [comment]
@henbucuoshanghai you may want to ask this on https://github.com/wang-xinyu/tensorrtx, and also you may want to try using the latest version of this repo rather than the v4.0 branch.

**Comment by henbucuoshanghai** [comment]
the latest version of this repo is v4.0?    isnot it ?

**Comment by glenn-jocher** [comment]
@henbucuoshanghai yes, v4.0 is the latest release, but there have been many commits since then, which you can access simply by cloning the repo and not checking out the v4.0 branch.
```
git clone https://github.com/ultralytics/yolov5
```

**Comment by henbucuoshanghai** [comment]
tks for your replay,i will try it .tks
