### ISSUE TITLE
Using empty background images during training

### ISSUE THREAD

**Issue by NMVRodrigues** [ultralytics/yolov5#2477]
Is it possible to use/include images containing only the background and no objects during training? I didn't find anything regarding how to label such images in terms of the bounding box coordinates and class, so was wondering if it was possible.

**Comment by glenn-jocher** [comment]
@NMVRodrigues yes, adding background images to your dataset is very easy, you simply add them to any of your dataset directories. No labels are required.

**Comment by NMVRodrigues** [comment]
Thanks! That works perfectly! 
Although the background images suffer a lot from false positives, but that is a training issue.
