### ISSUE TITLE
Precision values sky roeckt then drop? any idea as to why and how to fix? is it normal to do that?

### ISSUE THREAD

**Issue by SWRIGH211** [ultralytics/yolov5#2478]
## ❔Whenever i train my model then look at the precison graph, around the third epoch, precision sky rockets from 5% through to 95% then plumits back down again. I have tried to see if i was overfitting my dataset my training without augmentation, then with. however it still remains the same pattern? any ideas as to why and how to fix it? Or is this normal?

Any help would be great!

## 
![image](https://user-images.githubusercontent.com/60390273/111142144-42e9f580-857c-11eb-9ec1-7c8e1cd1bf4e.png)

**Comment by glenn-jocher** [comment]
@SWRIGH211 mAP is the main metric you should focus on, as it is an absolute value across all possible confidences. P and R are evaluated at the maximum F1 confidence, so you are only seeing a small slice of the confidence space with them.
