### ISSUE TITLE
Max Number of Bounding boxes in a single image

### ISSUE THREAD

**Issue by EFNFCTN** [ultralytics/yolov5#2479]
Hello, I wanted to know what is the maximum number of bounding boxes that can be predicted in a single image?

I have many pictures where the number of objects is higher than 300, but all predictions are **exactly** 300 objects in every image.

**Comment by glenn-jocher** [comment]
@EFNFCTN NMS has a few settings here that you may want to modify. What is the maximum object count in your detection workflow? Perhaps we should increase these defaults.
https://github.com/ultralytics/yolov5/blob/ed2c74218d6d46605cc5fa68ce9bd6ece213abe4/utils/general.py#L404-L412

**Comment by EFNFCTN** [comment]
@glenn-jocher Thank you for your quick return.

Oh, I didn't check that script, I was looking in the **detect.py** script for NMS parameter.

I have around 400 objects per image.

Thank you again!

**Comment by glenn-jocher** [comment]
@EFNFCTN ok thanks! Maybe we should raise this to 500 to impact less users. We have a limit here so the mAP computation in test.py doesn't take too long, as with --conf 0.001 a lot of boxes are typically returned.
