### ISSUE TITLE
How do I save the input image to each layer?

### ISSUE THREAD

**Issue by Jspring42** [ultralytics/yolov5#2482]
## ❔Question
I'd like to see the input to each layer as an image in an attempt to see what features the model is extracting. How can I go about doing this?

**Comment by glenn-jocher** [comment]
@Jspring42 the input image is modified as it passes through the model, it's not really 'viewable' in it's entirety as it is stretched in the channel dimension. The 3 inputs into the Detect() layer for the 3 feature sizes might be a good place to look for features, these are of different shapes, whih hundreds of channels each, for example 1280x20x20, 640x40x40, 320x80x80.

**Comment by Jspring42** [comment]
@glenn-jocher thanks.
