### ISSUE TITLE
displaying test data images that only have detected object bounding boxes

### ISSUE THREAD

**Issue by SWRIGH211** [ultralytics/yolov5#2484]
## ❔Question: I'm using a video for my test data, however not every frame in the video has a valid object to be detected. when the inference testing is ran  on the video, (the image below shows when ther model finds a frame  that has an object that can be detected and classified)
![image](https://user-images.githubusercontent.com/60390273/111209030-64ba9b00-85c3-11eb-9f02-ba261e470f9d.png)
once i have extracted the frames from the video i would like to display my test images that only have relevant detected objects in them, is this possible to achieve? i.e. from the image above i only want to display frame 4401 since it has a detected object, not frame 4400 and 4399 since nothing was detected

Many thanks in advance if someone can help me

**Comment by SWRIGH211** [comment]
i have already extracted the frames as JPEG's, im just wondering if there is a way to extract the frames that only have relevant object detection bounding boxes like frame 4401 above, to determine my test accuracy.

**Comment by glenn-jocher** [comment]
@SWRIGH211 yes you can customize detect.py directly to suit your needs:
https://github.com/ultralytics/yolov5/blob/master/detect.py
