### ISSUE TITLE
Saving / plotting other metrics and data

### ISSUE THREAD

**Issue by NMVRodrigues** [ultralytics/yolov5#2488]
Hi,

I tried looking at the source code but it didn't really help me in this situation.
Is there any way to save additional metrics/data from both training and test, even if local and not on wandb?

_e.g_ let's say I would like to store the list of obj_loss per epoch, or would like to see the RMSE (purely as an example), how would I go about doing that? Is there any specific method that needs changing? or is there any method that can be used as a template to create new ones for additional metrics?

**Comment by glenn-jocher** [comment]
@NMVRodrigues test.py passes a `results` list to train.py, you can modify this list to include additional metrics, and then access those metrics in train.py and log them however you'd like:
https://github.com/ultralytics/yolov5/blob/ed2c74218d6d46605cc5fa68ce9bd6ece213abe4/train.py#L345-L363
