### ISSUE TITLE
Is there a way to resume training? Each epoch takes more than12 minutes, and before it runs for 45 epochs already 10hrs is lost, and my colab is active only for 12 hours

### ISSUE THREAD

**Issue by Sri-user** [ultralytics/yolov5#2489]

**Comment by batrlatom** [comment]
Just use resume, pass the location of your weights from the 30th epoch and set for example number of epochs to 60. Try something like this

```
python train.py --epochs 60  --weights 30th_epoch_weights_yolov5m.pt --resume
```

**Comment by Sri-user** [comment]
@batrlatom Thank you,let me try the same and will let yu know the results

**Comment by batrlatom** [comment]
@Sri-user try my colab ... https://colab.research.google.com/drive/1Piy0dSsce4egZtFhyyerxhQMzX2-84vJ

**Comment by Sri-user** [comment]
@batrlatom Yes saw your colab. Thanks much👍

**Comment by glenn-jocher** [comment]
There are two options to resume an interrupted run:
```bash
python train.py --resume  # resume latest training
python train.py --resume path/to/last.pt  # specify resume checkpoint
```

If you started the training with a multi-GPU command then you must resume it with the same exact configuration (and vice versa). Multi-GPU resume commands are here, assuming you are using 8 GPUs:
```bash
python -m torch.distributed.launch --nproc_per_node 8 train.py --resume  # resume latest training
python -m torch.distributed.launch --nproc_per_node 8 train.py --resume path/to/last.pt  # specify resume checkpoint
```

Note that you may not change any settings when resuming, you must resume with the same exact settings (`--epochs`, `--batch`, `--data`, etc).

**Comment by Sri-user** [comment]
Hey guys thanks for your comments

But there is still one problem

!python /content/drive/MyDrive/YOLO_V5/yolov5/train.py --img 1024 --batch 16 --epochs 5 --data /content/drive/MyDrive/YOLO_V5/pneumonia_det.yaml --cfg /content/drive/MyDrive/YOLO_V5/yolov5/models/yolov5s.yaml --name /content/drive/MyDrive/YOLO_V5/runs/train/PneumoniaTrial1

I used this first. And once the 5 epochs got completed

%%time

!python /content/drive/MyDrive/YOLO_V5/yolov5/train.py --img 1024 --batch 16 --epochs 8 --data /content/drive/MyDrive/YOLO_V5/pneumonia.yaml --weights /content/drive/MyDrive/YOLO_V5/runs/train/PneumoniaTrial12/weights/last.pt --resume

I tried this. I expected the epoch to continue and run for 6,7 and 8 epochs. But i received the below error message

"AssertionError: ./drive/MyDrive/YOLO_V5/runs/train/PneumoniaTrial12/weights/last.pt training to 5 epochs is finished, nothing to resume."

I guess initially i have to set the epochs as 8. And if i stop the training at 5 epochs. I can continue later to finish the remaining 3 epochs

Am i correct. Or is there any other way ?

**Comment by Sri-user** [comment]
Hey guys, whatever i have mentioned in my previous comment is the answer. Thanks for your support
