### ISSUE TITLE
Criterion for saving the best.pt

### ISSUE THREAD

**Issue by kevin-vmi** [ultralytics/yolov5#2492]
## ❔Question
I'd like to ask if there is an easy approach to start saving the best model after certain number of epochs (e.g., starting saving best.pt from 50 epochs). Thanks!

**Comment by adamhrv** [comment]
Add `if epoch > 50:` to 
https://github.com/ultralytics/yolov5/blob/master/train.py#L381

Or, if you want to pass as CLI argument, add something like this to the argparse sections:
`parser.add_argument('--min-save-epoch', type=int, default=50)` 

and then change the line 381 to:
`if epoch > opt.min_save_epoch and (not opt.nosave) or (final_epoch and not opt.evolve):`

**Comment by jaqub-manuel** [comment]
Hey, @adamhrv 
How to save all models after 50 epochs,
I  mean, 51.pt, 52.pt...100.pt, because I am getting best metrics after 50 epochs, and want to analyse FP, TP etc. after 50 epochs...Thanks in advance

**Comment by adamhrv** [comment]
try something like this at line 392:
```
if epoch > 50:
	torch.save(ckpt, last.replace('last.pt', f'{epoch}.pt'))
```
https://github.com/ultralytics/yolov5/blob/master/train.py#L392

**Comment by kevin-vmi** [comment]
> Add `if epoch > 50:` to
> https://github.com/ultralytics/yolov5/blob/master/train.py#L381
> 
> Or, if you want to pass as CLI argument, add something like this to the argparse sections:
> `parser.add_argument('--min-save-epoch', type=int, default=50)`
> 
> and then change the line 381 to:
> `if epoch > opt.min_save_epoch and (not opt.nosave) or (final_epoch and not opt.evolve):`

Thanks! That is super helpful!

**Comment by jaqub-manuel** [comment]
> try something like this at line 392:
> 
> ```
> if epoch > 50:
> 	torch.save(ckpt, last.replace('last.pt', f'{epoch}.pt'))
> ```
> 
> https://github.com/ultralytics/yolov5/blob/master/train.py#L392

Thanks @adamhrv
