### ISSUE TITLE
 (Mul_925) Op (Mul) [ShapeInferenceError] Incompatible dimensions

### ISSUE THREAD

**Issue by mcmingchang** [ultralytics/yolov5#2495]
Use the same code for training, use the same version of onnxruntime to report an error when running.There is no problem when using pytorch1.7 for onnx model conversion, but this error occurs when using pytorch1.8 for export.When using netron for model visualization, we find that the model structure is different.

yolov5s
![111111](https://user-images.githubusercontent.com/37234299/111407405-b9b6f800-870e-11eb-899e-e0f2c0b84160.jpg)

**Comment by SimonKoppers** [comment]
same problem here. Something in the Detector module seems to cause the problem during onnx inference.

**Comment by soltkreig** [comment]
I got the same trouble. Do you have any ideas how to fix it?

**Comment by mcmingchang** [comment]
use pytorch=1.7 to export




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ultralytics/yolov5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月1日(星期四) 中午12:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ultralytics/yolov5]  (Mul_925) Op (Mul) [ShapeInferenceError] Incompatible dimensions (#2495)





 
I got the same trouble. Do you have any ideas how to fix it?
