### ISSUE TITLE
How to detect only specific classes using yolov5s.pt pre-trained model

### ISSUE THREAD

**Issue by abuelgasimsaadeldin** [ultralytics/yolov5#2496]
Hi everyone, I'm a little new to Python and am working on a vehicle classification using YOLOv5, I'm using the yolov5s.pt pre-trained model and it is doing quite a good job at classifying vehicle however it is also identifying other objects in the image. My question is how to only detect specific classes from the image. I believe the pre-trained model is trained using the COCO datasets and these are the only classes which I want to get detected:
3 - Car
4 - Motorcycle
6 - Bus
8 - Truck
Any help or where to change the codes to achieve this would be highly appreciated! Thanks you.

**Comment by ChinaRush** [comment]
you can change the code in line 98 in detect.py where you can modify the result you want to print out, only print the four classes you need.
You'd better recreate a data set that contains all the classes you want to detect, so the result is the best.

**Comment by ChinaRush** [comment]
you can change the code in line 98 and 106 in detect.py that you can modify the result which you want to print out, only print and write the four classes you need.
You'd better recreate a data set that contains all the classes you want to detect, so the result is the best.

**Comment by abuelgasimsaadeldin** [comment]
Hi @ChinaRush 

Thanks for the reply, I found out how, I just needed to add --source ... and specify the classes that I needed to detect. Thanks again for the suggestion.
