### ISSUE TITLE
Using openCV stream as source 

### ISSUE THREAD

**Issue by Snitte** [ultralytics/yolov5#2499]
## ❔Question
I have another program converting a cameras feed into an opencv stream. How would i use this opencv stream as a source for yolo to run inference on? 
Bonus info: 
Im running Baumers neoAPI with a baumer camera, which is why i cannot just use webcam sources

**Comment by glenn-jocher** [comment]
@Snitte for streaming source examples (RTSP, HTTP, RTMP) see README:
https://github.com/ultralytics/yolov5#inference

**Comment by Snitte** [comment]
Streaming ip camera's is not the problem, im trying to change the picture input in the hard code since i cannot choose my camera as a source. I figured i need to change something in utils "LoadStream" but im not sure what

**Comment by Snitte** [comment]
I have access to the feed as "camera.GetImage()" which returns an image 
or camera.GetImage().GetNPArray() Which returns the image as an array

**Comment by glenn-jocher** [comment]
@Snitte for custom requirements you can modify the streamloader here:
https://github.com/ultralytics/yolov5/blob/ed2c74218d6d46605cc5fa68ce9bd6ece213abe4/utils/datasets.py#L260-L261

**Comment by Snitte** [comment]
Thats what i gathered aswell, i however have the issue that my camera feed does not work with cv2.VideoCapture or cv2.get as it is a picture. Do you know how i would have to modify the code to enable it to support a stream of pictures?

**Comment by glenn-jocher** [comment]
@Snitte the provided YOLOv5 dataloaders are there for convenience, for custom requirements you would need to adapt the existing examples to your task.

For a fully flexible python inference example you might also want to see the YOLOv5 PyTorch Hub example, which allows you to build your own python inference pipeline:

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Images
dir = 'https://github.com/ultralytics/yolov5/raw/master/data/images/'
imgs = [dir + f for f in ('zidane.jpg', 'bus.jpg')]  # batched list of images

# Inference
results = model(imgs)
results.print()  # or .show(), .save()
```
