### ISSUE TITLE
The model architecture of onnx file is not correct

### ISSUE THREAD

**Issue by smallguoan** [ultralytics/yolov5#2500]
## ❔Question
I viewed the onnx files (yolov5s and yolov5l) by using Netron(version 4.8.0). However, I found the architectures are not correct. For example, all activation functions are sigmoid and the architecture has many "Mul" operation.  The architecture is as below:
Is the problem of onnx exporting or Netron?
## Additional context
![1615973786(1)](https://user-images.githubusercontent.com/30500828/111446555-7f1d8180-8747-11eb-9233-b12d5a01a978.jpg)

**Comment by glenn-jocher** [comment]
@smallguoan SiLU() is defined as y = x * sigmoid(x)

**Comment by atomrun39** [comment]
I also encountered this problem.  All activation functions are sigmoid in onnx, but an error occurred when loading the model with ncnn:` layer Swish not exists or registered`, the model.param generated in ncnn shows swish, so how to solve this problem please?

**Comment by glenn-jocher** [comment]
@atomrun39 If you believe you have a reproducible issue, we suggest you close this issue and raise a new one using the 🐛 **Bug Report template**, providing screenshots and a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. Thank you!
