### ISSUE TITLE
Weak Reproducible

### ISSUE THREAD

**Issue by WindVChen** [ultralytics/yolov5#2502]
## ❔Question
I run yolov5s.yaml twice, and find the result is quite different. Here is my result. 
(I have set "cudnn.benchmark, cudnn.deterministic = False, True".)
Thanks for any advice making the reult stable.
![image](https://user-images.githubusercontent.com/56162412/111467363-52756400-875f-11eb-937e-0b34c5afaafc.png)

**Comment by AndreaBrg** [comment]
You might want to try setting every possible seed for the various non deterministic operations:
```
random.seed(args.seed)
torch.manual_seed(args.seed)
torch.cuda.manual_seed(args.seed)
numpy.random.seed(args.seed)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False
```
Possibly a bit of overkill, but if reproducibility is your concern you can start with this and try to remove piece by piece and see what is needed and what isn't.

Also check this article https://pytorch.org/docs/stable/notes/randomness.html

**Comment by WindVChen** [comment]
@AndreaBrg Thanks for your reply. I do set the seeds as you mentioned above.  But it still fails to work.  I wonder if it was the augment operations like mosaic, flip that caused the problem, as the select of the operations is random.

**Comment by AndreaBrg** [comment]
You can check if the training images are the same: in the run folder there should be some images labeled as train_batchx.png if they are different between the two runs probably the problem is there.

**Comment by WindVChen** [comment]
@AndreaBrg Thanks for your reply. 
I have checked these two are the same and test_batchX.png also the same . It seems that the problem is not here :( . 
What's more, I find something weird: Different network structures have the same test_batchX.png but different train_batchX.png. I think that changing the network structure should have no effect on data generation, right?

**Comment by glenn-jocher** [comment]
@WindVChen PyTorch trainings are generally not deterministic. See https://pytorch.org/docs/stable/notes/randomness.html, and follow the pointers provided by @AndreaBrg if you'd like to attempt to reduce randomness.

**Comment by glenn-jocher** [comment]
> REPRODUCIBILITY
> 
> Completely reproducible results are not guaranteed across PyTorch releases, individual commits, or different platforms. Furthermore, results may not be reproducible between CPU and GPU executions, even when using identical seeds.
> 
> However, there are some steps you can take to limit the number of sources of nondeterministic behavior for a specific platform, device, and PyTorch release. First, you can control sources of randomness that can cause multiple executions of your application to behave differently. Second, you can configure PyTorch to avoid using nondeterministic algorithms for some operations, so that multiple calls to those operations, given the same inputs, will produce the same result.
> 
> WARNING
> 
> Deterministic operations are often slower than nondeterministic operations, so single-run performance may decrease for your model. However, determinism may save time in development by facilitating experimentation, debugging, and regression testing.
> 
>
