### ISSUE TITLE
How to save models

### ISSUE THREAD

**Issue by ferro07** [ultralytics/yolov5#2503]
Hey @glenn-jocher 
After training the model, I will fine tune only for 50 epochs, so I want to record all epochs, not just best.pt, last.pt, 
so from epochs1 to epochs 50.
How can I do that,
Thanks in advance.

**Comment by glenn-jocher** [comment]
@ferro07 you can customize checkpointing logic here:
https://github.com/ultralytics/yolov5/blob/ed2c74218d6d46605cc5fa68ce9bd6ece213abe4/train.py#L380-L396
