### ISSUE TITLE
Model use

### ISSUE THREAD

**Issue by LouisJin05** [ultralytics/yolov5#2508]
## ❔Question
How to use the exported best.onnx model trained by yolov5 in MATLAB？

**Comment by glenn-jocher** [comment]
@LouisJin05 MATLAB with YOLO may be a bit of a stretch my friend. As a former MATLAB expert (i.e. https://github.com/ultralytics/functions-matlab) I can tell you that moving over to Python would be a great idea if your situation allows it.

MATLAB implementations will always be trailing updates, meaning that the newest AI architectures and advances will arrive in Python first and then eventually the most popular may migrate to official MATLAB support, but this time lag could be years, if at all.

**Comment by LouisJin05** [comment]
Sir,


Very glad to hear from you，and&nbsp;I will continue to explore in the future！


Thank you very much！


LouisJin




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ultralytics/yolov5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月19日(星期五) 晚上7:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ultralytics/yolov5] Model use (#2508)





 
@LouisJin05 MATLAB with YOLO may be a bit of a stretch my friend. As a former MATLAB expert (i.e. https://github.com/ultralytics/functions-matlab) I can tell you that moving over to Python would be a great idea if your situation allows it.
 
MATLAB implementations will always be trailing updates, meaning that the newest AI architectures and advances will arrive in Python first and then eventually the most popular may gain event MATLAB support, but this time lag could be years, if at all.
