### ISSUE TITLE
How do I use two models in one program?

### ISSUE THREAD

**Issue by Kingstom8MB** [ultralytics/yolov5#2517]
## ❔Question

I want to use two models in one application, but I can't figure out how to add them in, can anyone tell me how to modify the official detect.py to use two models in one application?

## Additional context

I have a model for tracking objects, using the official model.One is used for authentication. Logically, you don't want to train them together, so you want to use two models

**Comment by glenn-jocher** [comment]
@Kingstom8MB you can load multiple YOLOv5 models into an environment using PyTorch Hub:
```python
import torch

# Model
model_s = torch.hub.load('ultralytics/yolov5', 'yolov5s')
model_m = torch.hub.load('ultralytics/yolov5', 'yolov5m')
```

**Comment by Kingstom8MB** [comment]
@glenn-jocher thank you for you help,i'll try it

**Comment by AfiqueAye** [comment]
Can this be applicable in yolov7???? @glenn-jocher 
Please see my query 
https://github.com/WongKinYiu/yolov7/issues/1295
Suggest me what can I do?
It will be a great help for me, please. Thanks

**Comment by glenn-jocher** [comment]
@AfiqueAye Unfortunately, YOLOv7 is not officially supported under the Ultralytics repository. However, you can explore the Ultralytics Docs at https://docs.ultralytics.com/yolov5/ for further guidance on using multiple models in one application. Good luck!

**Comment by Chunyounghawn** [comment]
> @AfiqueAye리더하게도 YOLOv7은 Ultralytics에서 공식적으로 지원되지 않습니다. 그러나 하나의 다양한 모델을 사용하는 방법에 대한 자세한 지침은 https://docs.ultralytics.com/yolov5/ 에서 Ultralytics Docs를 탐색할 수 있습니다. 당신을 믿어요!

Hello
How do I combine two models of completely different class types to represent each final box?

For example, a picture should have two boxes using two models

**Comment by glenn-jocher** [comment]
@Chunyounghawn you can simply perform inference using both models separately and then combine their results to represent each final box. Check the Ultralytics Docs at https://docs.ultralytics.com/yolov5/ for more information. Good luck!
