### ISSUE TITLE
Documentation on aspect ratio threshold 

### ISSUE THREAD

**Issue by ml5ah** [ultralytics/yolov5#2521]
## 🚀 Feature
Hi @glenn-jocher
Thanks for the amazing work with yolov5
This feature is related to documentation on the aspect ratio threshold in utils/datasets.py that is used for custom training.

## Motivation
I have been working on object detection projects and using YOLOv5 frequently for some of the training tasks at hand. However, most of the time, mAP performance did not match my expectations set seeing the mAP scores on the COCO dataset. My dataset has mostly rectangular objects, and about 10-15% of them being either very wide or very tall. Going through one of the issues on GitHub, I realized that there is an aspect ratio threshold that discards all objects having an aspect ratio > 20 by default.

## Pitch

It would be great to make this clear in the train custom dataset (https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data)
so that we can adjust this parameter from the get go during experimentation. Thanks for the help!

**Comment by glenn-jocher** [comment]
@ml5ah thanks for the feedback! Yes perhaps box candidate thresholds should be included in the hyperparameters used for training to make them easier to modify and easier to spot. Can you submit a PR for this to help others? I will add a TODO here to update the Custom Training Tutorial with this information.

In general you should also be aware that the default architecture is not optimized for high aspect ratio objects, and the models would benefit from changes targeted specifically to this domain, which may include elongation of the convolution kernels in the C3 layers, i.e. perhaps alternate 5x1 and 1x5 convolutions in place of, or in addition to, the current 3x3 and 1x1 sequences.

TODO: Update Train Custom Data Tutorial with label candidate criteria section, as well as NMS settings section.

**Comment by cszer** [comment]
Very good note 👍👍

**Comment by ml5ah** [comment]
Hey @glenn-jocher, I have included a short write-up for the Train Custom Data WiKi, please find it here:
https://github.com/ml5ah/yolov5/wiki/Train-Custom-Data

It its appropriate, could you please update it in the ultralytics/yolov5 repo. Apparently, pull requests don't work for wikis.
Thanks!

**Comment by ml5ah** [comment]
@glenn-jocher Hey, do you have time to look at this today? Would be awesome!
https://github.com/ultralytics/yolov5/pull/2653

**Comment by MrinalJain17** [comment]
Reviving this issue.

**Comment by MrinalJain17** [comment]
@glenn-jocher  Can we revive this issue? I'd be happy to draft a PR.

**Comment by ml5ah** [comment]
@MrinalJain17 could yo please review this PR? https://github.com/ultralytics/yolov5/pull/2869
@glenn-jocher thank you!

**Comment by MrinalJain17** [comment]
@ml5ah Oh, I didn't realize there was already a PR on this. Thanks of the info. Hope this feature gets merged soon.

**Comment by glenn-jocher** [comment]
TODO removed, default AR threshold increased to 100 in #5556
