### ISSUE TITLE
Multiple Batch Image Input

### ISSUE THREAD

**Issue by felixyustian** [ultralytics/yolov5#2522]
I'm trying to input multiple batches of images by every 100 images from a folder to the model. But got the error that the model don't accepted the PNGImageFile as the input. Below is my code:

dir = image_file_dir
types = *image_name.png

class image_dataset():
    def __init__(self, root):
        self.root = root
        self.imgs = list(sorted(glob.glob(root + types)))
        # print (type(self.imgs))

    def __getitem__(self, idx):
        # load images
        img_path = os.path.join(self.root, self.imgs[idx])
        # print (type(img_path))
        img = Image.open(img_path)

        return img
    
    def __len__(self):
        return len(self.imgs)

dataset = image_dataset(dir)
# print (len(dataset))
data = []
batch_size = 100
num_batch = int(len(dataset) / batch_size) - 1
for batch_i in range(num_batch):
    data_batch = []
    for i in range(batch_size):
        data_batch.append(dataset[(batch_i * batch_size + i)])
    data.append(data_batch)

When I'm trying to input data to the model, it;s got the following error:

Exception has occurred: TypeError
int() argument must be a string, a bytes-like object or a number, not 'PngImageFile'
  File "/home/felixyustian/.cache/torch/hub/ultralytics_yolov5_master/models/common.py", line 206, in forward
    im = np.array(im)  # to numpy
File "/home/felixyustian/Documents/yolov5/yolo.py", line 62, in <module>
    results = model(data)

Is the model unable to accept input batches of PNGImageFIle?

Thanks for your response

**Comment by glenn-jocher** [comment]
@felixyustian for an example of batched inference see the PyTorch Hub Tutorial:
```python
import cv2
import torch
from PIL import Image

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # for file/URI/PIL/cv2/np inputs and NMS

# Images
for f in ['zidane.jpg', 'bus.jpg']:  # download 2 images
    print(f'Downloading {f}...')
    torch.hub.download_url_to_file('https://github.com/ultralytics/yolov5/releases/download/v1.0/' + f, f)
img1 = Image.open('zidane.jpg')  # PIL image
img2 = cv2.imread('bus.jpg')[:, :, ::-1]  # OpenCV image (BGR to RGB)
imgs = [img1, img2]  # batched list of images

# Inference
results = model(imgs)  # includes NMS

# Results
results.print()  # or .show() or .save()  
```

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [ONNX and TorchScript Export](https://docs.ultralytics.com/yolov5/tutorials/model_export)
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)
