### ISSUE TITLE
Ensemble models: yolov3 vs yolov5

### ISSUE THREAD

**Issue by kevin-vmi** [ultralytics/yolov5#2523]
## ❔Question

Hello, I am using detect.py to obtain ensembled predictions from several models (in both yolov3 and 5). I found that yolov3 can generate better results, which have considerably higher scores than each of the component models, while that increase for yolov5 is much less -- the ensembled model is almost the same to its components. I wonder if there is any difference of detect.py in function between v3 and v5.

FYI, I already enabled the "multi_model" in general.py for yolov5. Thanks!

## Additional context

**Comment by glenn-jocher** [comment]
@kevin-vmi sorry I don't understand the question. Can you supply a reproducible example?

See Model Ensembling Tutorial for details related to ensembling operations.

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [ONNX and TorchScript Export](https://docs.ultralytics.com/yolov5/tutorials/model_export)
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by kevin-vmi** [comment]
Thanks for the reply. I am sorry for not able to provide a reproducible example here, as it is a relatively general question regarding the comparison between yolov3 and v5's predictions.

My question is when we use "python detect.py --weights 1.pt 2.pt 3.pt ..." using yolov3 and yolov5 respectively, is there any difference in technical details between the two? Or, it actually performs exactly the same criterion for the two frameworks?

I guess one difference would be the "multi-class" variable turned off in general.py for yolov5, while it is enabled for yolov3. Besides that, I'd like to know if there are other differences between v3 and v5's ensemble models. Thanks again for your kind help!

**Comment by glenn-jocher** [comment]
@kevin-vmi the ultralytics/yolov3 repo is on a delayed support schedule relative to ultralytics/yolov5, so in general they are quite similar besides gaps in merging YOLOv5 updates (bug fixes, feature additions) into YOLOv3.

**Comment by kevin-vmi** [comment]
Got it. Thanks. Given my using experience, they are both excellent frameworks!
