### ISSUE TITLE
Why my model size is 668MB!!!

### ISSUE THREAD

**Issue by huangyebiaoke** [ultralytics/yolov5#2527]
## ❔Question
I train with yolov5x.pt, however when finished the model size is 668MB. Unbelieveable!!!

## Additional context
![image](https://user-images.githubusercontent.com/26546591/111774718-d3ad3200-88ea-11eb-89e0-b1801f239b28.png)
![image](https://user-images.githubusercontent.com/26546591/111774756-e0318a80-88ea-11eb-9e0a-d33994afb337.png)

**Comment by glenn-jocher** [comment]
@huangyebiaoke unbelievable why? Training checkpoints contain FP16 model, FP16 EMA, and FP32 optimizer, so a training checkpoint should be 4X larger than a final checkpoint, which has EMA and optimizer stripped automatically upon training completion here:
https://github.com/ultralytics/yolov5/blob/ed2c74218d6d46605cc5fa68ce9bd6ece213abe4/train.py#L401-L405

**Comment by huangyebiaoke** [comment]
> @huangyebiaoke unbelievable why? Training checkpoints contain FP16 model, FP16 EMA, and FP32 optimizer, so a training checkpoint should be 4X larger than a final checkpoint, which has EMA and optimizer stripped automatically upon training completion here:
> https://github.com/ultralytics/yolov5/blob/ed2c74218d6d46605cc5fa68ce9bd6ece213abe4/train.py#L401-L405

Thanks, because the training is Interrupted by automatically shutdown computer。And I train by command `--resume`.

**Comment by huangyebiaoke** [comment]
> @huangyebiaoke unbelievable why? Training checkpoints contain FP16 model, FP16 EMA, and FP32 optimizer, so a training checkpoint should be 4X larger than a final checkpoint, which has EMA and optimizer stripped automatically upon training completion here:
> https://github.com/ultralytics/yolov5/blob/ed2c74218d6d46605cc5fa68ce9bd6ece213abe4/train.py#L401-L405

Thank you. So, how could I finish early the tarining. Beacuse I once set the epochs is 1000, but when it's 600 I find it's enougth. But I can't terminal it maually neither set the epochs to 601 and `--resume`.

**Comment by glenn-jocher** [comment]
@huangyebiaoke you can stop training any time with CTRL+C, and then use best.pt normally.

You can also strip optimizer and EMA from any checkpoint by calling `strip_optimizer()` manually:
https://github.com/ultralytics/yolov5/blob/ed2c74218d6d46605cc5fa68ce9bd6ece213abe4/utils/general.py#L484-L498

**Comment by huangyebiaoke** [comment]
@glenn-jocher think you, bro. I guess I know how to do it.
