### ISSUE TITLE
I want to ask some questions about R P mAp

### ISSUE THREAD

**Issue by litingting1111** [ultralytics/yolov5#2530]
After running test.py，i get some pictures about P R mAp，but i find Recall is zero,could i get the reason?

**Comment by litingting1111** [comment]
![image](https://user-images.githubusercontent.com/80535260/111779794-81234400-88f1-11eb-843a-38bee2fb3745.png)
![image](https://user-images.githubusercontent.com/80535260/111779823-8da79c80-88f1-11eb-8322-657ec930a879.png)
![image](https://user-images.githubusercontent.com/80535260/111779865-9d26e580-88f1-11eb-8142-e865497fb38d.png)
![image](https://user-images.githubusercontent.com/80535260/111779890-a57f2080-88f1-11eb-981d-64537930689c.png)

**Comment by glenn-jocher** [comment]
@litingting1111 recall is a function of confidence. At confidence = 0.8 your recall is 1.0.
