### ISSUE TITLE
use trained model in custom hierarchy 

### ISSUE THREAD

**Issue by HenriMir** [ultralytics/yolov5#2531]
I trained a yolov5 and tried to use in a custom project and when I do 

w = "/home/ubuntu/yolov5/runs/train/exp3/weights/best.pt". # location of trained weights
ckpt = torch.load(w, map_location=select_device(''))

I get an error : ModuleNotFoundError: No module named 'models.yolo'

How can I use the trained model in a python project that does not have the same hierarchy that your repository ? 

Thanks!

**Comment by HenriMir** [comment]
(it works when I copy paste the yolo.py, export.py, common.py, experimental.py manually in my models folder but that seems to be a not very satisfying workaround)

**Comment by glenn-jocher** [comment]
@HenriMir see PyTorch Hub tutorial for using custom YOLOv5 models in your own python projects:

## Custom Models
This example loads a custom 20-class [VOC](https://github.com/ultralytics/yolov5/blob/master/data/voc.yaml)-trained YOLOv5s model `'yolov5s_voc_best.pt'` with PyTorch Hub.
```python
model = torch.hub.load('ultralytics/yolov5', 'custom', path_or_model='yolov5s_voc_best.pt')  # custom model
```

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [ONNX and TorchScript Export](https://docs.ultralytics.com/yolov5/tutorials/model_export)
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by marcusdiy** [comment]
Hi, I would like to use it too without passing via torch.hub for stability reasons. I was trying like below, but not working. Wich is the right way to run an simple detection? Would it be possibile to include train.py directly? Thanks. 
@glenn-jocher Manificient work btw!

```
path_or_model = 'app/best.pt'
img = 'https://raw.githubusercontent.com/ultralytics/yolov5/master/data/images/bus.jpg'

model = torch.load(path_or_model) if isinstance(path_or_model, str) else path_or_model
if isinstance(model, dict): model = model['model']

from models.yolo import Model
hub_model = Model(model.yaml).to(next(model.parameters()).device)
hub_model.load_state_dict(model.float().state_dict())
hub_model.names = model.names
hub_model.autoshape()
results = hub_model(img)
print(results)

```

**Comment by glenn-jocher** [comment]
@marcusdiy torch hub is the simplest way to integrate a custom model into your own python workflows. 

We don't provide support for code modifications, but of course you're free to try those as well if that works better.
