### ISSUE TITLE
Train on images without objects

### ISSUE THREAD

**Issue by hoangcuongbk80** [ultralytics/yolov5#2532]
## ❔Question
Does the model learn from images without objects?

## Additional context

80% of my custom dataset is images without objects. Is it make sense to put these images in the training set? Or I just need to train the model on images having objects.

**Comment by glenn-jocher** [comment]
@hoangcuongbk80 YOLOv5 datasets can contain images with and without objects. If your image has no objects, it does not need a label txt file.

**Comment by hoangcuongbk80** [comment]
@glenn-jocher 

Thanks for your reply.

I mean does the model learn anything from images without objects (empty)? or it just ignores these images.

**Comment by kinoute** [comment]
@hoangcuongbk80 It helps to reduce the number of False Positives. You can see a full answer here: https://github.com/ultralytics/yolov5/issues/2313#issuecomment-787128847

**Comment by hoangcuongbk80** [comment]
@kinoute Thank you, it's clear now.

**Comment by glenn-jocher** [comment]
Loss is computed on all images regardless of contents.
