### ISSUE TITLE
Bounding box of the yolov5 detect.py predictions

### ISSUE THREAD

**Issue by Leprechault** [ultralytics/yolov5#2533]
For a make the predictions in the new images a use my `best.pt` model in:

```
!python detect.py --weights "/content/drive/MyDrive/backup/yolov5x_256_8/weights/best.pt" --img 256 --conf 0.5 --source ../img/val
```

That results in:
```

Fusing layers... 
Model Summary: 484 layers, 88390614 parameters, 0 gradients
image 1/740 /content/img/val/sample_10061.jpg: 224x256 Done. (0.038s)
image 2/740 /content/img/val/sample_10062.jpg: 224x256 Done. (0.031s)
```
At the end of this process, I have a `/runs/detect/exp` folder with all de predictions in the images. But I'd like a *txt file with the bounding box coordinates of the prediction in each image. Please, any ideas for me to make this?

**Comment by glenn-jocher** [comment]
@Leprechault to save detection results as text files you can use:
```
python detect.py --save-txt
```

**Comment by Leprechault** [comment]
Thank @glenn-jocher !!! Question solved. Best wishes!!

**Comment by yesid-acm** [comment]
Hi @Leprechault please, can I help me? I wrote --save-txt True But it is wrong x.X, how do you write it?
