### ISSUE TITLE
Incorrect label image given in wiki page

### ISSUE THREAD

**Issue by mattpopovich** [ultralytics/yolov5#2535]
## 🐛 Bug

The wiki page for how to [train your custom data](https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data) uses the following two images: 

![image](https://user-images.githubusercontent.com/26833433/91506361-c7965000-e886-11ea-8291-c72b98c25eec.jpg)
![label](https://user-images.githubusercontent.com/26833433/98809572-0bc4d580-241e-11eb-844e-eee756f878c2.png)

Either the label for the tie is wrong `27 0.78 0.50 0.039 0.15` and the bounding box is correct or **the bounding box is incorrect and the label is correct**. 

I think the label is actually for the bounding box of the tie on the person to the right as this image from the main yolov5 README shows:
![full image](https://user-images.githubusercontent.com/26833433/97107365-685a8d80-16c7-11eb-8c2e-83aac701d8b9.jpeg)

**Comment by glenn-jocher** [comment]
@mattpopovich yes you are right! I reproduced this also. The tie box corresponds to the second smaller tie which is no longer detected by the base model, so we should update the label box example. Will add a TODO for this. Sharp eye!

**Comment by mattpopovich** [comment]
Confirming that this has been fixed with the new label coordinates: 
![Fixed image](https://user-images.githubusercontent.com/26833433/112467037-d2568c00-8d66-11eb-8796-55402ac0d62f.png)

Thanks!

**Comment by glenn-jocher** [comment]
@mattpopovich great, thanks for the confirmation! Please let us know if you spot any other inconsistencies around the tutorials or code.
