### ISSUE TITLE
Which Amazon instance can be used to train whole COCO dataset

### ISSUE THREAD

**Issue by joyjeni** [ultralytics/yolov5#2536]
## ❔I  m research scholar and want to train whole  COCO dataset for my publication benchmark. Which amazon instance can be used. Which region. I asked for P3 as shown in tutorial. But its not available in Mumbai region. What alternatives I can use to train whole dataset. AWS support desk shared below link. Could you please help me to choose right alternative. 

https://aws.amazon.com/ec2/instance-types/

**Comment by glenn-jocher** [comment]
@joyjeni you are not restricted to any specific region with AWS or GCP, so if P3 instances are not available in the Mumbai region you are free to source them from another region, perhaps EU or US.

P3 instances are a good choice. You can see all available choices under Accelerated Computing tab from your link:
<img width="1281" alt="Screenshot 2021-03-23 at 12 52 36" src="https://user-images.githubusercontent.com/26833433/112142362-c8058800-8bd6-11eb-9db2-d18d0ce435f3.png">

**Comment by joyjeni** [comment]
Thankyou for suggestion
