### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'pycocotools>=2.0' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by yeb2Binfang** [ultralytics/yolov5#2539]
## ❔Question
Does anyone know how to install pycocotools? I tried pip install pycocotools. It did install it. However, it still said DistributionNotFound. Have no idea how to fix it. Please help. thanks！

**Comment by glenn-jocher** [comment]
@yeb2Binfang you should be able to install with `pip install pycocotools>=2.0`
https://pypi.org/project/pycocotools/

If you believe you have a reproducible issue, we suggest you close this issue and raise a new one using the 🐛 **Bug Report template**, providing screenshots and a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. Thank you!
