### ISSUE TITLE
the meaning in result.txt

### ISSUE THREAD

**Issue by helen12138** [ultralytics/yolov5#254]
Excuse me , please help me to explain the meaning of the last seven column parameters in the result.txt?
![image](https://user-images.githubusercontent.com/65990186/86214064-3e77db00-bbad-11ea-91a7-e3bf836e185a.png)
Thanks a lot

**Comment by WANGCHAO1996** [comment]
precision  Recall mAP@0.5 F1

**Comment by helen12138** [comment]
> precision Recall mAP@0.5 F1

Thanks a lot ! I found them in train.py
