### ISSUE TITLE
Is it possible to retrain my best.pt file with new images?

### ISSUE THREAD

**Issue by gondimjoaom** [ultralytics/yolov5#2541]
## Additional context

I trained my object detector and now I have new labeled data I would like to train too. Can I take the best.pt that I have from my last finished training and make it "learn more" from the new images?

**Comment by lgeuder** [comment]
you can use your best.pt with -weights in train.py

**Comment by gondimjoaom** [comment]
But in this case, if I've trained m'y best.pt with 300 epochs for example, I must put 600 (or 300 + number of desired epochs) epochs to train?

**Comment by adrianholovaty** [comment]
See the question/answers here: https://github.com/ultralytics/yolov5/issues/2498
