### ISSUE TITLE
Densenet Model

### ISSUE THREAD

**Issue by aviezab** [ultralytics/yolov5#2543]
## 🚀 Feature
Hi, I want to use other pre-trained model, such as densenet like this (https://github.com/pjreddie/darknet/blob/master/cfg/densenet201.cfg)
precisely Densenet-121, so I can run like this:
```bash
python train.py --data coco.yaml --cfg yolov5x.yaml --weights densenet121.pt --batch-size 4
```

## Motivation
I need to implement Densenet121 on yolov5 for my research, but for now I have limited knowledge.

## Pitch
I want You guys provide at least clear steps how to produce the model, and I can do it myself.
But it is also nice if You guys provide it and all people can use it.

Sorry for my asking, and thank You for providing such a beautiful framework.

**Comment by glenn-jocher** [comment]
@aviezab the last Ultralytics release backward compatible with Darknet cfg files is the ultralytcs/yolov3 archive branch:
https://github.com/ultralytics/yolov3/tree/archive

All later works are based on modern yaml files for model architecture:
https://github.com/ultralytics/yolov5/blob/master/models/yolov5s.yaml

Each layer is defined by four values. `from` defines which layer the inputs are coming from, `number` is the number of times the layer is repeated, `module` is the pytorch or custom module, and `args` are the module arguments:
https://github.com/ultralytics/yolov5/blob/0d891c601e8178e4b9665da46d630456668b1996/models/yolov5s.yaml#L12-L26

You can use this flexible yaml architecture to define any model type, including modules not present in this repo by defining them in models/common.py or models/experimental.py.

**Comment by aviezab** [comment]
Thanks for Your answer.
The Yolov3 is best fastest way, but I thought We will try to write the experimental one.

**Comment by Akshaypatil7** [comment]
@aviezab Were you able to successfully implement Densenet? I am too trying to do so.
Thanks.
