### ISSUE TITLE
streamlit uploaded image 

### ISSUE THREAD

**Issue by yupopa** [ultralytics/yolov5#2547]
## ❔Question
streamlit return BytesIO object when image uploaded how can ı pass through that type of object to my model. I use torch.hub.load to make an detection and ı used results function. How can ı pass through that type of image to results function? can you please help me 

## Additional context
ı am also getting this error 
File "/home/appuser/.cache/torch/hub/ultralytics_yolov5_master/models/common.py", line 207, in forward
    if im.shape[0] < 5:  # image in CHW

**Comment by glenn-jocher** [comment]
@yupopa PyTorch Hub Tutorial contains example BytesIO usage:

### Base64 Results
For use with API services. See https://github.com/ultralytics/yolov5/pull/2291 for details.
```python
results = model(imgs)  # inference

results.imgs # array of original images (as np array) passed to model for inference
results.render()  # updates results.imgs with boxes and labels
for img in results.imgs:
    buffered = BytesIO()
    img_base64 = Image.fromarray(img)
    img_base64.save(buffered, format="JPEG")
    print(base64.b64encode(buffered.getvalue()).decode('utf-8'))  # base64 encoded image with results
```


## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [ONNX and TorchScript Export](https://docs.ultralytics.com/yolov5/tutorials/model_export)
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)
