### ISSUE TITLE
BatchInference cost time is abnormal

### ISSUE THREAD

**Issue by LifeIsSoSolong** [ultralytics/yolov5#2548]
## ❔Question
When I inference 2560x1952 image using yolov5x-tensorrt, I got wrong time cost.
1.batchsize=1, inference cost time 127ms, cost gpu 2G
2.batchsize=9, inference cost time 1000ms, cost gpu 9G

GPU cost is normal, but Time cost is abnormal(Should cost 130~140ms?)

**Comment by dmcEric** [comment]
hi , i just meet the same problem.

**Comment by glenn-jocher** [comment]
@LifeIsSoSolong @dmcEric larger batch sizes will obviously take more time to complete. There is no problem, this is correct behavior.

**Comment by dmcEric** [comment]
but why larger batch size can save training time in one epoch?

**Comment by glenn-jocher** [comment]
@dmcEric inference on a single batch at 10x3x640x640 will always take much longer than inference on a single batch at  1x3x640x640.

Larger batch sizes improve training speed because there are less batches to process.

**Comment by dmcEric** [comment]
“Larger batch sizes improve training speed because there are less batches to process.”

**Comment by dmcEric** [comment]
but inference on a single batch at 10x3x640x640 will take 10 times longer than inference on a single batch at 1x3x640x640. Is this a normal behavior?

**Comment by glenn-jocher** [comment]
@dmcEric roughly speaking sounds about right. You might expect a slight speedup, so it should take maybe 5-10X longer for the 10x batch than a 1x batch. This all depends on your hardware of course. CPU backends will see virtually no speedup, while CUDA backends will see something similar to the speedup mentioned above.

**Comment by LifeIsSoSolong** [comment]
> @dmcEric roughly speaking sounds about right. You might expect a slight speedup, so it should take maybe 5-10X longer for the 10x batch than a 1x batch. This all depends on your hardware of course. CPU backends will see virtually no speedup, while CUDA backends will see something similar to the speedup mentioned above.

thanks for your reply~

**Comment by MrRace** [comment]
Wow，same problem！ @LifeIsSoSolong Your yolov5x-tensorrt  is dynamic or static batch size? float 16 or float 32 ?
