### ISSUE TITLE
How to reduce the font size of inference detection categories and values?

### ISSUE THREAD

**Issue by zxsitu** [ultralytics/yolov5#2550]
## ❔Question
Hello author, I am using `detect.py` to infer using images smaller than 640 pixels, and my image is 256 pixels. The inference process is successful, I would like to know how to reduce the font size of the detection results (detection category and detection value), they are filling up my graph and blocking a large area, how to solve it well?

## Additional context
None.

**Comment by adrianholovaty** [comment]
You can reduce the line thickness by changing this line in `detect.py`:

```
plot_one_box(xyxy, im0, label=label, color=colors[int(cls)], line_thickness=3)
```

Try changing it to `line_thickness=2` or `line_thickness=1`.

The font size is determined relative to that `line_thickness` value. That code lives in `plot_one_box()` in `utils/plots.py`.

**Comment by zxsitu** [comment]
@adrianholovaty Thank you! Very quick reply, I'll give it a try!
Otherwise the color of the detection box is different every time I test and I'm fainting...
