### ISSUE TITLE
How much epochs to run?

### ISSUE THREAD

**Issue by ajaysurya1221** [ultralytics/yolov5#2552]
## ❔Question
Hi, i have 1900 images with 2 classes.
i used yolov5l model to train
could you please suggest the number of epochs to run?

## Additional context

Results:

      0/89     5.61G   0.07745    0.0277   0.01785     0.123         7       640    0.7966    0.3577    0.3942    0.1884   0.04524   0.01313  0.004035
      1/89     5.61G   0.05729   0.01826  0.004725   0.08027         7       640    0.5863    0.7462    0.7054    0.3722   0.03981   0.00885  0.001732
      2/89     5.61G    0.0494   0.01557  0.004011   0.06897         7       640    0.7492    0.8203    0.8298    0.4587   0.03411  0.006995  0.001755
      3/89     5.61G   0.04651   0.01409  0.003481   0.06408         6       640    0.4882    0.8817    0.6936    0.3293    0.0369  0.007428  0.001903
      4/89     5.61G    0.0442   0.01406  0.003675   0.06194         4       640    0.9006    0.8678    0.9041    0.5832   0.02695  0.007398  0.001826
      5/89     5.61G   0.03894   0.01391  0.003172   0.05602         5       640     0.901    0.8362    0.8967    0.5295   0.03045  0.007201  0.001303
      6/89     5.61G   0.03683   0.01339  0.003254   0.05347         5       640    0.9211    0.9017    0.9472    0.6207   0.02381  0.006518  0.001319
      7/89     5.61G   0.03593   0.01311  0.002465    0.0515         8       640     0.949    0.9141    0.9534    0.6555   0.02349  0.006383 0.0007743
      8/89     5.61G   0.03374   0.01268  0.001882    0.0483         4       640    0.9618    0.9242    0.9671    0.7023     0.021  0.005757  0.001062
      9/89     5.61G   0.03252   0.01189  0.001994   0.04641         7       640    0.9743    0.9403    0.9744    0.7166   0.02162  0.005571  0.001045
     10/89     5.61G   0.03092   0.01184  0.001943    0.0447         4       640     0.974    0.9355    0.9766    0.7095   0.02003  0.005579 0.0007864
     11/89     5.61G   0.03058   0.01176  0.002077   0.04442         3       640    0.9551    0.9335    0.9696    0.6612   0.02127  0.005644 0.0007908
     12/89     5.62G   0.02998   0.01211  0.002316   0.04441        10       640    0.9519    0.9239    0.9581    0.6784   0.02125  0.005962 0.0008176
     13/89     5.62G   0.02941   0.01191  0.001881    0.0432         8       640    0.9679    0.9459     0.976    0.7107   0.01947  0.005283 0.0008002
     14/89     5.62G   0.03023   0.01232  0.003031   0.04557         4       640    0.9549    0.9426    0.9713    0.6953   0.02081  0.005568 0.0008442
     15/89     5.62G   0.02873   0.01144  0.001668   0.04183         8       640    0.9694    0.9498    0.9759    0.7334   0.01853  0.005427 0.0008159
     16/89     5.62G   0.02881   0.01154  0.001591   0.04194         7       640    0.9744    0.9451    0.9779    0.7163   0.01896   0.00526 0.0007474
     17/89     5.62G   0.02721   0.01066  0.001365   0.03923         8       640    0.9839    0.9548    0.9852    0.7569    0.0178  0.004839 0.0006572
     18/89     5.62G   0.02728   0.01072  0.001597    0.0396         6       640    0.9778    0.9634    0.9821    0.7407   0.01775  0.004922 0.0006666
     19/89     5.62G    0.0269   0.01082  0.001698   0.03942         8       640     0.975    0.9582    0.9847     0.742   0.01708  0.004923 0.0006652
     20/89     5.62G   0.02643   0.01052  0.001465   0.03842        10       640    0.9752    0.9758    0.9885    0.7702   0.01637   0.00464 0.0007204
     21/89     5.62G   0.02555    0.0103  0.001352    0.0372         8       640    0.9735    0.9693    0.9857    0.7667   0.01666  0.004775 0.0006843
     22/89     5.62G    0.0256   0.01036  0.001052   0.03702         5       640    0.9856    0.9721    0.9907    0.7694   0.01599  0.004674 0.0006197
     23/89     5.62G    0.0247   0.01018  0.001344   0.03622         5       640    0.9836    0.9715    0.9873    0.7693   0.01608  0.004584 0.0005198
     24/89     5.62G   0.02421   0.00989 0.0009864   0.03509         8       640    0.9841    0.9681    0.9863    0.7812   0.01522  0.004435 0.0004945
     25/89     5.62G   0.02448  0.009788  0.001344   0.03561         7       640    0.9887    0.9691    0.9908     0.783   0.01562  0.004436 0.0006137
     26/89     5.62G   0.02379  0.009573  0.001089   0.03445         6       640     0.986    0.9774    0.9914     0.785   0.01471  0.004341 0.0006721
     27/89     5.62G   0.02337  0.009447 0.0009981   0.03382         7       640    0.9816    0.9792    0.9905    0.7952   0.01467  0.004323  0.000596
     28/89     5.62G     0.023   0.00946 0.0008877   0.03335         8       640    0.9851    0.9782    0.9918    0.7873   0.01485  0.004373 0.0004653
     29/89     5.62G    0.0232  0.009417  0.001002   0.03361         5       640    0.9824    0.9815    0.9913    0.7993   0.01533  0.004296 0.0004429
     30/89     5.62G   0.02231  0.009215 0.0009231   0.03245         7       640    0.9796    0.9834    0.9913    0.7991   0.01456  0.004286 0.0004938
     31/89     5.62G   0.02223  0.009149  0.000817    0.0322         7       640    0.9868    0.9807    0.9924    0.7964    0.0143  0.004212 0.0006133
     32/89     5.62G   0.02225  0.009105 0.0007401    0.0321         9       640    0.9828    0.9826    0.9927    0.8139   0.01439  0.004185 0.0006154
     33/89     5.62G   0.02165  0.009316 0.0008703   0.03184         4       640    0.9819     0.986    0.9915    0.8055   0.01396   0.00433 0.0006154
     34/89     5.62G   0.02181  0.009007  0.001057   0.03187         6       640    0.9806     0.989    0.9913    0.8034   0.01403  0.004181 0.0005543
     35/89     5.62G    0.0217  0.008999 0.0007788   0.03147         6       640     0.985    0.9853    0.9929    0.8099   0.01379  0.004259 0.0004773
     36/89     5.62G   0.02107  0.008949 0.0007366   0.03076         7       640    0.9835    0.9891    0.9923    0.8187   0.01336  0.004155 0.0005448
     37/89     5.62G   0.02095  0.008842 0.0006979   0.03049         6       640    0.9826    0.9922     0.994    0.8191   0.01313  0.004094 0.0003693
     38/89     5.62G   0.02079  0.008967  0.000934   0.03069         6       640    0.9867    0.9858    0.9925    0.8195   0.01367  0.004131 0.0004072
     39/89     5.62G   0.02104  0.008995 0.0006514   0.03069         7       640    0.9893    0.9839    0.9935     0.824   0.01293  0.004023 0.0005396
     40/89     5.62G   0.02097   0.00873 0.0004828   0.03019         7       640    0.9874    0.9844    0.9924    0.8154   0.01347  0.003955 0.0004373
     41/89     5.62G   0.02023  0.008594 0.0006065   0.02943         4       640    0.9885    0.9914     0.994    0.8294   0.01268  0.003943 0.0004424
     42/89     5.62G   0.01993  0.008411 0.0006998   0.02904         2       640    0.9855    0.9931    0.9933    0.8256   0.01286   0.00394 0.0003885
     43/89     5.62G   0.02052  0.008598 0.0008578   0.02998         8       640     0.988    0.9899    0.9941    0.8341   0.01213  0.003925 0.0004102
     44/89     5.62G   0.01976  0.008564 0.0007523   0.02908         5       640    0.9847    0.9924    0.9934    0.8235   0.01273  0.003939 0.0003727
     45/89     5.62G   0.01947   0.00859 0.0008302   0.02889         4       640    0.9892    0.9885    0.9936    0.8286   0.01255  0.003957  0.000322
     46/89     5.62G   0.01934  0.008541  0.001309   0.02919         7       640    0.9889    0.9935    0.9944    0.8323   0.01235  0.003807 0.0004735
     47/89     5.62G   0.01923  0.008502 0.0008132   0.02855         7       640    0.9919    0.9895    0.9932    0.8307   0.01216  0.003837 0.0003439
     48/89     5.62G   0.01959  0.008415 0.0006851   0.02869         7       640    0.9874    0.9932    0.9933    0.8335   0.01235  0.003887 0.0003222
     49/89     5.62G   0.01905  0.008414 0.0006109   0.02807         6       640    0.9907    0.9924    0.9942    0.8338   0.01166  0.003748 0.0003084
     50/89     5.62G   0.01864  0.008403 0.0006519    0.0277         9       640    0.9889     0.994    0.9942    0.8308   0.01225  0.003802 0.0002868
     51/89     5.62G    0.0182  0.008262 0.0006768   0.02714         7       640    0.9902     0.995    0.9945    0.8432    0.0119  0.003809  0.000296
     52/89     5.62G   0.01784    0.0081 0.0005405   0.02648        10       640    0.9927    0.9926     0.995    0.8437   0.01191  0.003832 0.0003138
     53/89     5.62G   0.01884  0.008292 0.0006963   0.02783         6       640    0.9917    0.9921    0.9947    0.8459   0.01163  0.003884 0.0003183
     54/89     5.62G   0.01852   0.00811 0.0005957   0.02723         8       640    0.9924    0.9927    0.9945    0.8394   0.01192  0.003722 0.0002997
     55/89     5.62G    0.0181  0.008206 0.0005019   0.02681        10       640     0.992    0.9921    0.9948    0.8489   0.01134  0.003707 0.0002336
     56/89     5.62G   0.01793  0.007895 0.0005533   0.02637         2       640    0.9911    0.9931    0.9947    0.8515    0.0115  0.003712 0.0002762
     57/89     5.62G   0.01765  0.007903 0.0007205   0.02627         4       640    0.9913    0.9937    0.9947    0.8498   0.01141  0.003679 0.0002481
     58/89     5.62G   0.01748   0.00812 0.0006518   0.02625         7       640    0.9904    0.9932    0.9947    0.8539   0.01121  0.003721 0.0003646
     59/89     5.62G    0.0177  0.007754 0.0005649   0.02602         6       640    0.9895    0.9965    0.9946    0.8525   0.01126  0.003641 0.0003244
     60/89     5.62G   0.01704  0.007667 0.0003216   0.02502         3       640    0.9921    0.9935    0.9947    0.8541   0.01111   0.00361 0.0002588
     61/89     5.62G   0.01709  0.007705 0.0003331   0.02513         7       640     0.991    0.9956    0.9949    0.8574   0.01077  0.003556 0.0002535
     62/89     5.62G   0.01671  0.007753 0.0005981   0.02506         8       640    0.9917    0.9948    0.9948    0.8571   0.01081  0.003592 0.0002635
     63/89     5.62G   0.01673  0.007814 0.0005218   0.02507         4       640    0.9927    0.9945    0.9948     0.858   0.01087  0.003542 0.0003026
     64/89     5.62G   0.01691  0.007801  0.000473   0.02519         3       640    0.9907    0.9965    0.9948      0.86   0.01051  0.003572 0.0003251
     65/89     5.62G   0.01661   0.00742 0.0004805   0.02451         5       640    0.9905    0.9972    0.9948    0.8653   0.01035  0.003416 0.0002721
     66/89     5.62G   0.01664  0.007537 0.0004946   0.02467         5       640    0.9938    0.9942    0.9948    0.8637   0.01068  0.003463  0.000261
     67/89     5.62G   0.01651   0.00764 0.0003751   0.02453         4       640    0.9916    0.9939    0.9948    0.8655    0.0107  0.003467 0.0002659
     68/89     5.62G   0.01617  0.007529 0.0003979    0.0241         4       640    0.9911    0.9947    0.9954    0.8641   0.01067  0.003476 0.0002718
     69/89     5.62G   0.01623   0.00759 0.0003509   0.02417         5       640    0.9907    0.9954    0.9953    0.8669   0.01049  0.003405 0.0002889
     70/89     5.62G    0.0159  0.007365 0.0004449   0.02371         8       640    0.9929    0.9969    0.9955    0.8679   0.01049  0.003415 0.0002704
     71/89     5.62G   0.01614  0.007335  0.000558   0.02403         7       640    0.9944     0.994    0.9956    0.8717   0.01022  0.003455 0.0002646
     72/89     5.62G   0.01584   0.00724 0.0005344   0.02361         8       640    0.9936    0.9964    0.9953    0.8701   0.01004  0.003354 0.0003662
     73/89     5.62G   0.01588  0.007446 0.0003773    0.0237         6       640    0.9943    0.9938    0.9953    0.8654    0.0104   0.00346 0.0002504
     74/89     5.62G   0.01552  0.007329 0.0006073   0.02346         6       640    0.9961    0.9945    0.9957    0.8714   0.01001  0.003418 0.0002629
     75/89     5.62G    0.0155  0.007133  0.000475   0.02311         6       640    0.9915    0.9963    0.9954    0.8764  0.009837   0.00332 0.0002109
     76/89     5.62G   0.01594  0.007321 0.0003732   0.02363         6       640    0.9917    0.9973    0.9954    0.8791  0.009739  0.003314 0.0001874
     77/89     5.62G     0.015  0.007076 0.0005095   0.02259         3       640    0.9922    0.9973    0.9954    0.8753  0.009785  0.003324 0.0001877
     78/89     5.62G   0.01539  0.007126 0.0004585   0.02297         7       640    0.9966    0.9945    0.9955    0.8793  0.009828    0.0033  0.000162
     79/89     5.62G   0.01514  0.007055 0.0002145   0.02241         6       640    0.9935    0.9966    0.9959    0.8768  0.009672  0.003285 0.0001685
     80/89     5.62G   0.01526  0.007198 0.0004618   0.02292         6       640    0.9937    0.9959    0.9955    0.8773  0.009783  0.003277 0.0001861
     81/89     5.62G   0.01542  0.007157 0.0005106   0.02309         3       640    0.9952    0.9934    0.9958     0.879  0.009798  0.003257 0.0001904
     82/89     5.62G   0.01514  0.007137  0.000325    0.0226         7       640    0.9935    0.9956    0.9958    0.8773  0.009617  0.003233 0.0001816
     83/89     5.62G   0.01518   0.00711 0.0004236   0.02271         3       640    0.9952    0.9936    0.9957    0.8769   0.00945  0.003256 0.0001673
     84/89     5.62G   0.01515  0.007161 0.0002967   0.02261         9       640    0.9939    0.9946    0.9954    0.8816  0.009519  0.003253 0.0002043
     85/89     5.62G   0.01469  0.006944 0.0002913   0.02192         5       640    0.9954    0.9938    0.9957     0.884  0.009221  0.003182 0.0002127
     86/89     5.62G   0.01503  0.006972 0.0003568   0.02236         8       640    0.9939    0.9957    0.9959    0.8842  0.009327  0.003199 0.0002338
     87/89     5.62G   0.01465  0.006936 0.0003075   0.02189         6       640    0.9939    0.9974    0.9959    0.8847  0.009264  0.003191 0.0001608
     88/89     5.62G   0.01499  0.007125 0.0003004   0.02241         5       640    0.9926    0.9977    0.9959    0.8837  0.009394  0.003255 0.0001588
     89/89     5.62G   0.01438  0.006972 0.0002516    0.0216         6       640    0.9953    0.9954     0.996     0.883  0.009165  0.003167 0.0001518

**Comment by ChinaRush** [comment]
The default epochs are 300, just try it ,you can adjust it based on you results.

**Comment by glenn-jocher** [comment]
@ajaysurya1221 as @ChinaRush default --epochs 300 are what you should start with, and then adjust from there.

**Comment by aviezab** [comment]
@ajaysurya1221 I have tried with yolov5x model with 7 labels and 1k data, the running training shows rising mAP at  ~ epoch 130.
The bigger the pixel image, the better the mAP.
