### ISSUE TITLE
Green screen when using Raspberry pi camera v2 attached to Jetson nano

### ISSUE THREAD

**Issue by sinano1107** [ultralytics/yolov5#2553]
## ❔Question
`python3 detect.py --source 0`
I only get a green screen when I run

Maybe the solution presented [here](https://forums.developer.nvidia.com/t/how-to-slove-opencv-green-screen/82803) will work for me.
But I don't know how to change the code.
Have any of you already solved this problem?
![0D0C928D-C034-4B25-B89E-5599FED1BB6C_1_105_c](https://user-images.githubusercontent.com/45984123/111975111-8d064480-8b43-11eb-8a30-9f5a3e034bfb.jpeg)

**Comment by ghost** [comment]
I have the same problem with the green screen.

I using the Nvidia Jetson Nano and a Paspberry Pi NoIR Camera V2. https://www.raspberrypi.org/products/pi-noir-camera-v2/

But when I using a normal USB-Cam than run the yolov5 with `python3 detect.py --source 0` fine

I don't know why. I hope any of you already solved this problem.

**Comment by glenn-jocher** [comment]
@cyberFoxi @sinano1107 we are working on bringing better support for Nano and Raspberry Pi in the next few months. At the moment I'm not sure what the problem may be, though you may want to check that you can view images with cv2 with the NoIR camera first before trying to use YOLOv5. 

Also note that if you have multiple webcams attached you can access them using their indices, i.e.:
```bash
python detect.py --source 0
python detect.py --source 1
python detect.py --source 2
```

**Comment by ghost** [comment]
@glenn-jocher 

Maybe is the problem the image-size or FPS? When i run the yolov5 with the Raspberry Pi NoIR V2 Camera then i have a warning. 
Do you see on the first screenshot.

Wenn i use a USB-Cam, i have no warning (second screenshot) and yolov5 run perfektly without green sceen.

I can view images with cv2. With this code in terminal 

`gst-launch-1.0 nvarguscamerasrc sensor_mode=0 ! 'video/x-raw(memory:NVMM),width=3820, height=2464, framerate=21/1, format=NV12' ! nvvidconv flip-method=0 ! 'video/x-raw,width=960, height=616' ! nvvidconv ! nvegltransform ! nveglglessink -e
`
From this website https://www.jetsonhacks.com/2019/04/02/jetson-nano-raspberry-pi-camera/

![Jetson Nano yolov5 green screen rasp pi](https://user-images.githubusercontent.com/78427745/112272105-0dc85c00-8c7c-11eb-8e02-0f8b9963c9aa.PNG)
![Jetson Nano yolov5 no green screen usb cam](https://user-images.githubusercontent.com/78427745/112272114-102ab600-8c7c-11eb-9adf-685b5645524d.PNG)

**Comment by glenn-jocher** [comment]
@cyberFoxi ah I see! Well inference and everything else with the model seems to be operating well, it simply appears that cv2 is not reading your NoIR V2 correctly. You may want to raise the issue on the cv2 repository or perhaps on a Raspberry Pi forum, or stackoverflow. 

The YOLOv5 dataloader relies on simple cv2 commands to load streaming sources, i.e. the same as https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_gui/py_video_display/py_video_display.html, so if this doesn't work in your environment then the YOLOv5 streamloader won't either.

```python
import numpy as np
import cv2

cap = cv2.VideoCapture(0)

while(True):
    # Capture frame-by-frame
    ret, im= cap.read()

    # Display the resulting frame
    cv2.imshow('frame', im)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# When everything done, release the capture
cap.release()
cv2.destroyAllWindows()
```

**Comment by sinano1107** [comment]
@glenn-jocher 
Thank you!
By the way, I am suffering from lack of fps in reasoning with nano.
Are there any plans to support fast live inference with tensorrt?

**Comment by ghost** [comment]
@sinano1107

Will cv2 work for you on the Jetson Nano with the Raspberry Pi v2 Cam?

When I start the cv2 with the code from @glenn-jocher I get the same green screen as the yolov5.

But when I use a normal USB webcam, cv2 works fine.

I don't know why now. I have run out of ideas. 



> 
> 
> @cyberFoxi ah I see! Well inference and everything else with the model seems to be operating well, it simply appears that cv2 is not reading your NoIR V2 correctly. You may want to raise the issue on the cv2 repository or perhaps on a Raspberry Pi forum, or stackoverflow.
> 
> The YOLOv5 dataloader relies on simple cv2 commands to load streaming sources, i.e. the same as https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_gui/py_video_display/py_video_display.html, so if this doesn't work in your environment then the YOLOv5 streamloader won't either.
> 
> ```python
> import numpy as np
> import cv2
> 
> cap = cv2.VideoCapture(0)
> 
> while(True):
>     # Capture frame-by-frame
>     ret, im= cap.read()
> 
>     # Display the resulting frame
>     cv2.imshow('frame', im)
>     if cv2.waitKey(1) & 0xFF == ord('q'):
>         break
> 
> # When everything done, release the capture
> cap.release()
> cv2.destroyAllWindows()
> ```

**Comment by glenn-jocher** [comment]
@sinano1107 yes, there are plans for official support/demos/tutorials for the most common use-cases, including TensorRT on nano. I think there are already decent solutions out there, but I also think many deployment scenarios are more complicated than need be, so hopefully this year we can offer easy examples for the most common ones (nano, raspberry pi, coral tpu, fastapi, streamlit etc.).

**Comment by sinano1107** [comment]
@cyberFoxi 
The USB camera worked in my environment as well.
I haven't been able to check the Raspberry Pi camera v2.

Try to convert
`cap = cv.VideoCapture(0)`
to
`cap = cv2.VideoCapture('nvarguscamerasrc ! video/x-raw(memory:NVMM), width=3280, height=2464, format=(string)NV12, framerate=(fraction)20/1 ! nvvidconv ! video/x-raw, format=(string)BGRx ! videoconvert ! video/x-raw, format=(string)BGR ! appsink' , cv2.CAP_GSTREAMER)`

**Comment by sinano1107** [comment]
@glenn-jocher 
I have not found a way to do live inference using tensorrtx
Can you also support live inference?
If so, I can't wait to see it!

**Comment by glenn-jocher** [comment]
@sinano1107 tensorrt is a model format, like onnx, pt, tflite, mlmodel etc.

Any model format can 'support' any task.

**Comment by sinano1107** [comment]
@glenn-jocher 
Hmm.
You're absolutely right.
Thank you.

I did not understand about tensorrt. I apologize for asking the wrong question.

**Comment by glenn-jocher** [comment]
@sinano1107 for CUDA device inference like jetson nano even a desktop GPU tensorrt should speed up inference compared to pytorch, unfortunately we don't have a live demo but you can get started converting your YOLOv5 models at https://github.com/wang-xinyu/tensorrtx

**Comment by sinano1107** [comment]
@glenn-jocher 
https://github.com/wang-xinyu/tensorrtx/issues/81
I need to learn about c++ as described in this link
I'll do my best.

**Comment by ghost** [comment]
> @sinano1107 
Thanks for the answer.

I tried your suggestion. But now I get an error. 

```
import numpy as np
import cv2

cap = cv2.VideoCapture('nvarguscamerasrc ! video/x-raw(memory:NVMM), width=3280, height=2464, format=(string)NV12, framerate=(fraction)20/1 ! nvvidconv ! video/x-raw, format=(string)BGRx ! videoconvert ! video/x-raw, format=(string)BGR ! appsink', cv2.CAP_GSTREAMER)

while(True):
    # Capture frame-by-frame
    ret, im= cap.read()

    # Display the resulting frame
    cv2.imshow('frame', im)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# When everything done, release the capture
cap.release()
cv2.destroyAllWindows()
```

Error:

Traceback (most recent call last):
  File "yolov5_cam_check.py", line 11, in <module>
    cv2.imshow('frame', im)
cv2.error: OpenCV(4.5.1) /tmp/pip-req-build-zuuo394f/opencv/modules/highgui/src/window.cpp:376: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'imshow'


Do you now why?


> 
> @cyberFoxi
> The USB camera worked in my environment as well.
> I haven't been able to check the Raspberry Pi camera v2.
> 
> Try to convert
> `cap = cv.VideoCapture(0)`
> to
> `cap = cv2.VideoCapture('nvarguscamerasrc ! video/x-raw(memory:NVMM), width=3280, height=2464, format=(string)NV12, framerate=(fraction)20/1 ! nvvidconv ! video/x-raw, format=(string)BGRx ! videoconvert ! video/x-raw, format=(string)BGR ! appsink' , cv2.CAP_GSTREAMER)`

**Comment by sinano1107** [comment]
@cyberFoxi 
```
GST_STR = 'nvarguscamerasrc \
    ! video/x-raw(memory:NVMM), width=3280, height=2464, format=(string)NV12, framerate=(fraction)30/1 \
    ! nvvidconv ! video/x-raw, width=(int)640, height=(int)480, format=(string)BGRx \
    ! videoconvert \
    ! appsink'
WINDOW_NAME = 'Camera Test'
 
def main():
    cap = cv2.VideoCapture(GST_STR, cv2.CAP_GSTREAMER)
 
    while True:
        ret, img = cap.read()
        if ret != True:
            break
 
        cv2.imshow(WINDOW_NAME, img)
 
        key = cv2.waitKey(10)
        if key == 27: # ESC 
            break
 
if __name__ == "__main__":
    main()
```

What about this code?
