### ISSUE TITLE
RuntimeError: Couldn't load custom C++ ops occuring in .exe file

### ISSUE THREAD

**Issue by djollet** [ultralytics/yolov5#2554]
Hello everyone,
## ❔Question
im currently working on integrating my trained yolov5 network into a stand-allone executable for windows. For this purpose Im using PyInstaller. When the code is run in Pycharm (or other IDE), everything works just fine, but after translation to an .exe file, I get the following error:

__Traceback (most recent call last):
File "image_selecter.py", line 101, in <module>with torch.no_grad():
File "image_selecter.py", line 44, in detect# Apply NMS
File "utils\general.py", line 667, in non_max_suppression
i = torchvision.ops.nms(boxes, scores, iou_thres)
File "torchvision\ops\boxes.py", line 35, in nms
File "torchvision\extension.py", line 62, in _assert_has_ops_
RuntimeError: Couldn't load custom C++ ops. This can happen if your PyTorch and torchvision versions are incompatible, or if you had errors while compiling torchvision from source. For further information on the compatible versions, check https://github.com/pytorch/vision#installation for the compatibility matrix. Please check your PyTorch version with torch.__version__ and your torchvision version with torchvision.__version__ and verify if they are compatible, and if not please reinstall torchvision so that it matches your PyTorch install._

I rewrote the standart detect.py from YOLOv5 for my purposes (See detection.detect in script below). Basically, i want to apply the detection on single images with CPU support only. Therefore i deleted all GPU parts from the original script. 
The error massage confuses me, because i am using compatible Torch and Torchvision versions. Furthermore I don't understand, why the error only occures when executing the .exe file. Might there be a collision with other Python environments on my system?

Many thanks for your answers in advance!

Here some information about my Setup:
Windows 10
Python 3.9
CUDA 11.1
Torch 1.8.0+cu111
Torchvision 0.9.0+cu111
Using Python base interpreter

## Additional context
Aim of the script is, to safe those images from a stream of images, where the desired object lies more or less in the center of the image. 
The Script I want as .exe:
```
import time
import torch
import numpy as np
import cv2
import os

from models.experimental import attempt_load
from utils.datasets import letterbox, load_images_from_folder
from utils.general import (non_max_suppression, scale_coords,xyxy2xywh, plot_one_box)
from utils.torch_utils import time_synchronized
from models import yolo

class detection():
    def __init__(self, model, img_size = 512, conf_thresh = 0.5, iou_thresh = 0.45, device = 'cpu', augment = True,  classes=None, agnostic=False, save_dir = None):
        self.model = model
        self.img_size = img_size
        self.conf_thresh = conf_thresh
        self.iou_thresh = iou_thresh
        self.device = device
        self.augment = augment
        self.classes = classes
        self.agnostic = agnostic
        self.save_dir = save_dir
        self.names = self.model.module.names if hasattr(self.model, 'module') else self.model.names
        self.colors = [[np.random.randint(0, 255) for _ in range(3)] for _ in range(len(self.names))]

    def detect(self,image, filename):
        print(f'Processing {filename}...')
        t0 = time.time()
        img = letterbox(image, new_shape=self.img_size)[0]
        img = img[:, :, ::-1].transpose(2, 0, 1)  # BGR to RGB, to 3x416x416
        img = np.ascontiguousarray(img)
        img = torch.from_numpy(img).to(self.device)
        img = img.float()  # uint8 to fp16/32
        img /= 255.0  # 0 - 255 to 0.0 - 1.0
        if img.ndimension() == 3:
            img = img.unsqueeze(0)

        # Inference

        pred = self.model(img, augment=self.augment)[0]

        # Apply NMS
        pred = non_max_suppression(pred, self.conf_thresh, self.iou_thresh, classes=self.classes, agnostic=self.agnostic)
        t2 = time_synchronized()

        # Process detections
        for i, det in enumerate(pred):  # detections per image
            im0 = image.copy()

            gn = torch.tensor(im0.shape)[[1, 0, 1, 0]]  # normalization gain whwh
            if det is not None and len(det):
                # Rescale boxes from img_size to im0 size
                det[:, :4] = scale_coords(img.shape[2:], det[:, :4], im0.shape).round()

                # Write results
                centers = []
                confs = []
                classes = []
                for *xyxy, conf, cls in reversed(det):
                    # Write to file
                    xywh = (xyxy2xywh(torch.tensor(xyxy).view(1, 4)) / gn).view(-1).tolist()  # normalized xywh
                    cls = int(cls.numpy())
                    conf = float(conf.numpy())
                    centers.append(xywh)
                    confs.append(conf)
                    classes.append(cls)

                    if self.save_dir is not None:  # Add bbox to image
                        label = '%s %.2f' % (self.names[int(cls)], conf)
                        plot_one_box(xyxy, im0, label=label, color=self.colors[int(cls)], line_thickness=3)
                        cv2.imwrite(self.save_dir + 'inference_' + filename, im0)

            else:
                centers = ['na']
                confs = ['na']
                classes = ['na']
                if self.save_dir is not None:
                    cv2.imwrite(self.save_dir + 'inference_' + filename, im0)
            # Print time (inference + NMS)


        return classes, confs, centers #xywh normalized; xy = centre coordinates of bbox

if __name__ == "__main__" :
    t1 = time_synchronized()
    model = attempt_load('weights.pt', map_location='cpu')  # load FP32 model
    detection = detection(model=model)
    print('Loading images...')
    filenames,extensions,images = load_images_from_folder('stream/')
    print(f'{len(filenames)} images loaded!')
    first_round = True
    count = 0
    for i in range(len(filenames)):
        if filenames[count] == filenames[-1]:
            break
        else:
            image = images[count]
            filename = filenames[count] + extensions[count]
            with torch.no_grad():
                classes, confs, centers = detection.detect(image=image, filename=filename)

            if first_round == True:
                if classes[0] == 'na':
                    pass
                else:
                    for i in centers:
                        if i[0]<0.6 and  i[0]>0.5 and i[1]< 0.7 and i[1]> 0.3:
                            last_saved_image = image
                            cv2.imwrite('./selection/' + filename, image)
                            print(f'{filename} saved')
                            count+=9
                        else: pass
        count +=1
    t2 = time_synchronized()
    print('Done. (%.3fs)' % (t2 - t1))
```

**Comment by glenn-jocher** [comment]
@djollet sorry I can't help here myself as my windows experience is limited. If you succeed in packaging YOLOv5 into a windows executable though please consider writing a tutorial to help others in the future who may be trying to do the same!

**Comment by djollet** [comment]
Problem solved! 

There were some problems with other environments on my system. Although, I dont know where the problem lied in detail. 
However, i solved it by deinstalling Python, Anaconda, CUDA + cudnn... so just everything and making a complety new and clean installation.

Im using now:
Python 3.9
Base environment/interpreter
CUDA 11.2
Torch 1.8.0+cu111
Torchvision 0.9.0+cu111

No other environments are on my system anymore.
I am not using Anaconda anymore.

**Comment by glenn-jocher** [comment]
@djollet Anaconda does seem to cause problems. We never use it here, we just always install base python from python.org and then pip install requirements.
