### ISSUE TITLE
How to add LSTM to output embedding?

### ISSUE THREAD

**Issue by josjo80** [ultralytics/yolov5#2557]
## Additional context
My problem is spatio-temporal. I want to both use the spatial inductive bias of YOLO to produce a feature embedding and the temporal inductive bias of a LSTM to produce the output; classification and bbox locations. I am willing to write my own training script once the bodies of both architectures are combined.  Any help would be appreciated.

**Comment by glenn-jocher** [comment]
@josjo80 the YOLOv5 Detect() layers contain the final output convolutions in `self.m`, you might want to look at introducing any modifications there:
https://github.com/ultralytics/yolov5/blob/ad05e37d99bd1b86f7223540ad93381b8269d75c/models/yolo.py#L22-L57

**Comment by wch243294382** [comment]
have you make it succeed？

**Comment by glenn-jocher** [comment]
@wch243294382 we haven't attempted this ourselves, but we'd love to hear about your progress integrating YOLO with an LSTM. Good luck!
