### ISSUE TITLE
Different results for Detect.py and Test.py

### ISSUE THREAD

**Issue by jaqub-manuel** [ultralytics/yolov5#2559]
Dear @glenn-jocher
After the training model, I tested with my images with test.py,  False negative: 2,  False positive: 3, Ture positive: 18
But in the same situation detect.py, although everything is the same, I cannot get the same values. (FP: 8, FN 4 etc.) 

python test.py --weights best.pt --conf-thres 0.25 --img-size 512
python detect.py --weights best.pt --conf-thres 0.25 --img-size 512

Many Thanks  for your help.

**Comment by glenn-jocher** [comment]
@jaqub-manuel --iou-thresh is different by default between test.py and detect.py (0.45 and 0.65), so you should compare at identical settings for better aligned results:

https://github.com/ultralytics/yolov5/blob/0d891c601e8178e4b9665da46d630456668b1996/detect.py#L153

**Comment by jaqub-manuel** [comment]
@glenn-jocher , I have set them to 0.5 both for detect.py and test.py... everything was same..is there anything to do ?

**Comment by glenn-jocher** [comment]
@jaqub-manuel If you believe you have a reproducible issue, we suggest you close this issue and raise a new one using the 🐛 **Bug Report template**, providing screenshots and a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. Thank you!
