### ISSUE TITLE
#AssertionError: No labels found

### ISSUE THREAD

**Issue by luyao-1814787262** [ultralytics/yolov5#256]
I used the brainwash data set. When I started training with a small amount of data, there was no problem. Later, when I organized all the data  and started training, the following error occurred
`nf 0 500
Traceback (most recent call last):
  File "train.py", line 401, in <module>
    train(hyp)
  File "train.py", line 161, in train
    single_cls=opt.single_cls)
  File "/home/yuhongyi/yolov5-master/utils/datasets.py", line 405, in __init__
    assert nf > 0 or n == 20288, 'No labels found in %s. See %s' % (os.path.dirname(file) + os.sep, help_url)
AssertionError: No labels found in /home/yuhongyi/brainwash/labels/val/.`
But the data storage format is no different from before, the difference appears in my picture name and the .txt file name in labels becomes longer
brainwash_11_24_2014_images_07686000_640x480.txt

**Comment by luyao-1814787262** [comment]
I found this problem there
       `  self.label_files = [x.replace('images','labels').replace(os.path.splitext(x)[-1],'.txt')
                             for x in self.img_files]`
When this place was replaced, there were two‘ images’ in my path. The labels of my file should be replaced, but the labels in my final .txt name were mistakenly replaced

**Comment by glenn-jocher** [comment]
See https://docs.ultralytics.com/yolov5/tutorials/train_custom_data
