### ISSUE TITLE
Is YOLO predicting on the validation set?

### ISSUE THREAD

**Issue by tuh00621** [ultralytics/yolov5#2560]
## ❔Question
I was looking at the test_batch_labels and test_batch_pred images that it gives me after training a model, and the images in the train set have prediction boxes while the images in the validation set do not. Is it making predictions on the validation set despite this?

**Comment by AyushExel** [comment]
If I got the question right, I think you're asking if the predictions are made on the validation set during the training process. Yes, the model is evaluated on the validation set after every training epoch.

**Comment by tuh00621** [comment]
@AyushExel When viewing test_batch_labels and test_batch_pred image files in /runs/train/[name], the images in the train set have prediction boxes, while the images in the validation set do not. I'm not sure why this happens. I assume it's still making predictions on the validation set after every epoch but I wanted to make sure this was happening since it's not showing me the boxes in the validation set like it does for the train set.

**Comment by AyushExel** [comment]
I guess those mosaics are a sample of training images with their labels. But yes, the validation is done validation set for every epoch.

**Comment by tuh00621** [comment]
Okay, I thought it was still doing it but wanted to make sure. It's still weird how it shows the boxes for only the train set but not the val set.

**Comment by glenn-jocher** [comment]
@tuh00621 train*.jpg mosaics are produced only during epoch 0. test*.jpg images are produced only during first and last epoch.

Metrics are evaluated on val set every epoch.
