### ISSUE TITLE
about train_batch .jpg

### ISSUE THREAD

**Issue by Alex-afka** [ultralytics/yolov5#2563]
## ❔Question

![IG5_GV)5`99 Q1%J(MY6{3V](https://user-images.githubusercontent.com/69161095/112108756-9d71fa00-8beb-11eb-9b65-cd79cf8d59b1.png)
![XHY%TEAH`WF LOK0~SPT_%E](https://user-images.githubusercontent.com/69161095/112109788-f55d3080-8bec-11eb-8671-1f8c707bcefb.png)

![J}K{QTTE%3AJP@F~X@DN01L](https://user-images.githubusercontent.com/69161095/112109445-8ed81280-8bec-11eb-8203-133e90ba2679.png)

 hi  i have a problem . i have the label of ab880a185377 but it is show me the label in the train_batch.jpg.

**Comment by glenn-jocher** [comment]
@Alex-afka I'm sorry I don't understand the question. Can you explain the problem a bit more?
