### ISSUE TITLE
resume 恢复训练出现问题

### ISSUE THREAD

**Issue by hashiqi-233** [ultralytics/yolov5#2566]
## ❔Question
训练100个epoch,在50个epoch时中断，此时map=0.83然后使用python3 train.py --resume时，map突然下降到0.04，继续训练map变化不大。作者实现的resume似乎是有问题的。

## Additional context
作者继续训练加载模型参数时排除了model.24.anchors，model.24.anchor_grid，不知道为啥

**Comment by hashiqi-233** [comment]
已经找到问题，是我进化训练的时候把超参数文件中的anchors注释取消了。

**Comment by glenn-jocher** [comment]
@hashiqi-233 we just fixed a bug related to --resume with custom anchors about 20 days ago. See https://github.com/ultralytics/yolov5/pull/2361

You may be using an older version of the code before this PR. Please git pull or git clone a new version to receive these updates.
