### ISSUE TITLE
Set parameter of a single layer 

### ISSUE THREAD

**Issue by MaxwellHogan** [ultralytics/yolov5#2567]
## ❔Question
Is there an easy way to set the parameters (weights) of a single layer at a time - essentially I want to be able to randomize the parameters of each layer sequentially for an experiment.

I am going to be investigating this myself, but I wanted to ask if it has been done here to save myself some time

**Comment by glenn-jocher** [comment]
@MaxwellHogan sure, you can modify any layer's weights and biases to any values you'd like. You can see an example in yolo.py where layer biases are modified here:
https://github.com/ultralytics/yolov5/blob/0d891c601e8178e4b9665da46d630456668b1996/models/yolo.py#L144-L153

**Comment by MaxwellHogan** [comment]
@glenn-jocher cheers dude, I got what I needed now
