### ISSUE TITLE
Different prediction results between tensorrtx and YOLO's detect.py 

### ISSUE THREAD

**Issue by khushbuadav** [ultralytics/yolov5#2572]
## ❔Question
I have trained **yolov5s.pt** on custom dataset. I am using best.pt from that training to detect objects from sample images.   
I came across tensorrtx(https://github.com/wang-xinyu/tensorrtx) to improve the inference time. I was able to get the speed improvement, however, I got different detection results using tensorrtx on the same images.

## Additional context
I have followed all the steps given on https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5 link. 
Did all the necessary changes in the repo:
``` diff
diff --git a/yolov5/yololayer.h b/yolov5/yololayer.h
index 9b91c1a..89185f7 100644
--- a/yolov5/yololayer.h
+++ b/yolov5/yololayer.h
@@ -16,7 +16,7 @@ namespace Yolo
         float anchors[CHECK_COUNT * 2];
     };
     static constexpr int MAX_OUTPUT_BBOX_COUNT = 1000;
-    static constexpr int CLASS_NUM = 80;
+    static constexpr int CLASS_NUM = 8;
     static constexpr int INPUT_H = 608;
     static constexpr int INPUT_W = 608;

diff --git a/yolov5/yolov5.cpp b/yolov5/yolov5.cpp
index 9c95206..4a543c1 100644
--- a/yolov5/yolov5.cpp
+++ b/yolov5/yolov5.cpp
@@ -6,10 +6,10 @@
 #include "utils.h"
 #include "calibrator.h"

-#define USE_FP16  // set USE_INT8 or USE_FP16 or USE_FP32
+#define USE_FP32  // set USE_INT8 or USE_FP16 or USE_FP32
 #define DEVICE 0  // GPU id
-#define NMS_THRESH 0.4
-#define CONF_THRESH 0.5
+#define NMS_THRESH 0.45
+#define CONF_THRESH 0.25
 #define BATCH_SIZE 1
```
Commands i ran for inference: 
Tensorrtx: `sudo ./yolov5 -d yolov5_custom.engine /sample/images/`
Yolo Python: `python3.6 ./detect.py --source  /sample/images/ --weights custom_best.pt  --conf 0.25 --save-txt --img-size 640`

Please find below prediction comparison for yolov5 using custom_best.pt and tensorrtx enging using  `.wts` 
1. Image1-20210315-090347215.jpg
**Tensorrt prediction** => label_1 (7), label_2 (7), label_3 (14), label_4 (16), label_7 (1)
**Yolov5 prediction** => label_1 (12), label_2 (3), label_3 (11), label_4 (15), label_5 (3), label_6 (1)

2. Image2-20210315-090347124.jpg
**Tensorrt prediction** => label_1 (15), label_3 (22), label_4 (15), label_6 (1)
**Yolov5 prediction** => label_1 (14), label_2 (1), label_3 (17), label_4 (12), label_5 (1) 

I did not expect such a vast difference in the inference between the two methods. Any idea, what might be the issue or what things i can try to narrow down to the problem? 

P.S: I used the **yolov5 v4.0** repo for the test.

**Comment by glenn-jocher** [comment]
@khushbuadav for support with TensorRTx I would recommend raising an issue directly on the repository. 

In general you should check that inference settings are identical between your two experiments, including confidence threshold, iou threshold, image size and NMS settings.
