### ISSUE TITLE
Detection Output without boxes and labels on image

### ISSUE THREAD

**Issue by lgeuder** [ultralytics/yolov5#2580]
## ❔Question
How can I run the detection without having opencv put that box and label on my image.

## Additional context
I want to use the detected images with annotations to train on my model, but as the saved images contain the label and boxes from the detection directly on the image I would train that as well. Is there an easier way than outcommenting the codeline where this happens?

**Comment by AyushExel** [comment]
Wow, that's an interesting use case. There are many ways you can do this, but looking at the code, I think the easiest way would be to comment out l[ine 113](https://github.com/ultralytics/yolov5/blob/e5b0200cd250759c782207160761ca9756300065/detect.py#L113) which plots the bounding boxes. If this works as intended, you'll have the image without the boxes, and the annotations as txt file. I haven't tried it, so let me know if that doesn't work.

**Comment by glenn-jocher** [comment]
@lgeuder your images are not modified by detect.py. detect.py places a copy of your image with annotations in project/name directory.

You can autolabel a directory of images using `python detect.py --save-txt`.
