### ISSUE TITLE
About training with the entire coco dataset, not coco128

### ISSUE THREAD

**Issue by leeyunhome** [ultralytics/yolov5#2581]
## ❔Question

Hi?
Thanks for always giving good answers.
In the tutorial, we train with the coco128 dataset as follows.
download: https://github.com/ultralytics/yolov5/releases/download/v1.0/coco128.zip

How do I train it with the entire coco dataset?

Thank you.

**Comment by AyushExel** [comment]
Hi @leeyunhome . You can train on coco dataset by specifying the `--data` command-line argument. Here's the complete command.
`python train.py --data coco.yaml ` . This will train the `yolov5s.pt` model on coco for 300 epochs. 

There are other dataset config files like VOC present in the `yolov5/data` folder.
