### ISSUE TITLE
Reduce output size of yolov5 on coco

### ISSUE THREAD

**Issue by GiorgioSgl** [ultralytics/yolov5#2584]
## ❔Question
Is possible to reduce the output size of the yolov5 on coco dataset?
My idea is to remove some object that are useless in my case but without retraining yolo by zero, because is very costly in time. I don't find pretrained weights for training on coco with less classes or for a custom dataset, seems I have to retrain it from zero.

**Comment by glenn-jocher** [comment]
@GiorgioSgl model size and FLOPS are largely the same between a 1 class and an 80 class model. You're free to build your own models with any class count using PyTorch Hub and observe the model stats there compared to standard models. See PyTorch Hub Tutorial:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [ONNX and TorchScript Export](https://docs.ultralytics.com/yolov5/tutorials/model_export)
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by glenn-jocher** [comment]
@GiorgioSgl also, you can filter inference by classes using `python detect.py --classes 0 1 2` etc to only detect classes 0 1 and 2.

**Comment by GiorgioSgl** [comment]
So what you are suggesting me to do is to create my pretrained weights for yolov5 to have a specific number of classes with this code
`model = torch.hub.load('ultralytics/yolov5', 'yolov5s', classes=10)`

**Comment by glenn-jocher** [comment]
@GiorgioSgl you can create any class model you want and then compare the model's stats (FLOPS, parameters) against the normal 80 class models.

**Comment by GiorgioSgl** [comment]
It's normal that for retrain it took 1 hour for epoch on the COCO dataset with GPU of COLAB, I freeze all the layers (obviously notthe last) actually. I thought it could go more fast than that

**Comment by glenn-jocher** [comment]
@GiorgioSgl yes this seems normal. Colab is a bit handicapped from a training perspective unfortunately as the CPU count is only 2, and the dataloader becomes a bottleneck with only 2 workers.

The best workaround for smaller datasets is to --cache them into memory, which can improve training speeds significantly. For COCO though this is not an option though, as it will require about 120G of RAM to cache at --img 640.

```
python train.py --cache
```

**Comment by GiorgioSgl** [comment]
Can you suggest me how many epochs I will need to train it?

**Comment by glenn-jocher** [comment]
@GiorgioSgl see tips for best training results for epoch recommendations.

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [ONNX and TorchScript Export](https://docs.ultralytics.com/yolov5/tutorials/model_export)
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by GiorgioSgl** [comment]
Thanks amazing!

**Comment by glenn-jocher** [comment]
@GiorgioSgl one point about epochs also is that starting from pretrained weights should require less epochs, but is also a function of your dataset size. Most importantly you should be seeing some overfitting towards the end of your training. If your last epoch is also your best, you've not trained long enough and need to start over with more epochs.

**Comment by GiorgioSgl** [comment]
Okay thank you for precious suggestion!!! You are amzing too kind bro
