### ISSUE TITLE
How to get our own anchors?

### ISSUE THREAD

**Issue by BrianKenobi** [ultralytics/yolov5#2585]
I have the same problem as issue #2394. Without autoanchor, I can't get my recall more than 0.663. So I am thinking about how to get my own data's anchor so I can have a better result. Thanks.

well that's an improvement at least. Though I see your BPR is only 0.65, which means that your recall and mAP will never be higher than 0.65. You should try to supply your own manual anchors in your yolov5s.yaml file if possible to better match your data:
https://github.com/ultralytics/yolov5/blob/38ff499b26b9f8bf183cd1c08746dd33d000eb59/models/yolov5s.yaml#L6-L11

_Originally posted by @glenn-jocher in https://github.com/ultralytics/yolov5/issues/2394#issuecomment-799090203_

**Comment by glenn-jocher** [comment]
@BrianKenobi YOLOv5 anchors are saved as [Detect()](https://github.com/ultralytics/yolov5/blob/fab5085674f7748dc16d7ca25afb225fa441bc9d/models/yolo.py#L22) layer attributes on model creation, and updated as necessary by autoanchor before training starts. Their exact location is here:
https://github.com/ultralytics/yolov5/blob/fab5085674f7748dc16d7ca25afb225fa441bc9d/models/yolo.py#L34-L35

You can examine the anchors of any trained YOLOv5 model like this:

### Input
```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', autoshape=False)  # hub model
# -- or --
model = torch.load('yolov5s.pt')['model']  # local model

# Anchors
m = model.model[-1]  # Detect() layer
print(m.anchor_grid.squeeze())  # print anchors
```

### Output
```python
#           x     y
tensor([[[ 10.,  13.],
         [ 16.,  30.],
         [ 33.,  23.]],  # P3/8-small

        [[ 30.,  61.],
         [ 62.,  45.],
         [ 59., 119.]],  # P4/16-medium

        [[116.,  90.],
         [156., 198.],
         [373., 326.]]], dtype=torch.float16)  # P5/32-large
```

**Comment by BrianKenobi** [comment]
@glenn-jocher thank you!
in the line :

model = torch.load('yolov5s.pt')['model']  # local model

I'm not sure what should I put in ['model'].
So I only change 'yolov5s.pt' to my trained YoloV5x model 'best.pt'.
And the result is "ModuleNotFoundError: No module named 'models'"

<img width="556" alt="anchor" src="https://user-images.githubusercontent.com/50870564/112407230-ae884b80-8d50-11eb-9234-f50bf25ed5fb.png">
<img width="776" alt="anchor result" src="https://user-images.githubusercontent.com/50870564/112407337-e1324400-8d50-11eb-8760-2bc160c0cbe8.png">

**Comment by BrianKenobi** [comment]
I solved the problem by put the code in the YoloV5 folder. Thank you @glenn-jocher  again!

But as the result, I still get the default anchor. 
I am wondering how can I calculate my own data's anchor because using default anchors I won't get my recall higher than 0.663.
<img width="632" alt="anchor result" src="https://user-images.githubusercontent.com/50870564/112413297-e98f7c80-8d5a-11eb-9e47-1c86811d0906.png">

**Comment by glenn-jocher** [comment]
@BrianKenobi yes this is true. YOLOv5 models must either be loaded within the yolov5/ directory or via PyTorch Hub to enabled access to required module imports. To load from anywhere via PyTorch Hub:

```python
model = torch.hub.load('ultralytics/yolov5', 'custom', path_or_model='best.pt')  # custom model
```
