### ISSUE TITLE
V2.0weights & V3.0codes

### ISSUE THREAD

**Issue by mcjqwer** [ultralytics/yolov5#2590]
## Additional context
I find i cannot run yolov5-V3.0 use the weights of the trained V2.0weights with torch1.7.0
Does the  version of torch results to the problem.
And  I find the apperance of weightsV2.0 and weightsV3.0 are different.  Is  this also results from 
the torch version???

**Comment by glenn-jocher** [comment]
@mcjqwer different releases may have different architectures and weight files. Each releases weights can be found in the corresponding release assets, i.e.:

https://github.com/ultralytics/yolov5/releases/tag/v2.0
https://github.com/ultralytics/yolov5/releases/tag/v3.0
https://github.com/ultralytics/yolov5/releases/tag/v4.0

Earlier releases may only be compatible with earlier versions of PyTorch. See each release note for details.
