### ISSUE TITLE
How do I save the live video stream with detected objects?

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#2596]
## ❔Question

Hi,

I would save the live video stream after detection. How can i do it?
Because I would do the discovery overnight and watch it the next day.

It would also be nice to have a picture taken during the live stream and saved as soon as an object is detected.

**Comment by glenn-jocher** [comment]
@cyberFoxi I've created a PR 2598 to address this issue. webcam and streaming sources will now automatically be saved just like images and videos by detect.py. 

Also saving can now be disabled for all sources with the new --nosave argument:
```bash
python detect.py --nosave
```

This PR should be merged soon and then you should be able to customize it around L123-L140 to only write frames when detections are present to solve your problem. Good luck. 

```python
            # Save results (image with detections)
            if save_img:
                if dataset.mode == 'image':
                    cv2.imwrite(save_path, im0)
                else:  # 'video' or 'stream'
                    if vid_path != save_path:  # new video
                        vid_path = save_path
                        if isinstance(vid_writer, cv2.VideoWriter):
                            vid_writer.release()  # release previous video writer
                        if vid_cap:  # video
                            fps = vid_cap.get(cv2.CAP_PROP_FPS)
                            w = int(vid_cap.get(cv2.CAP_PROP_FRAME_WIDTH))
                            h = int(vid_cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
                        else:  # stream
                            fps, w, h = 30, im0.shape[1], im0.shape[0]
                            save_path += '.mp4'
                        vid_writer = cv2.VideoWriter(save_path, cv2.VideoWriter_fourcc(*'mp4v'), fps, (w, h))
                    vid_writer.write(im0)
```
