### ISSUE TITLE
Different result with detect.py and test.py

### ISSUE THREAD

**Issue by zyx792726304** [ultralytics/yolov5#2597]
## ❔Question
I come across the same problem with this issue #2559 
I run 
`python test.py --data ./data/voc.yaml --img-size 640 --conf-thres 0.2 --iou-thres 0.45 --weights ./VOC/yolov5s/weights/best.pt`
and I get the following result:
![image](https://user-images.githubusercontent.com/49439344/112458709-0a29f780-8d98-11eb-8c2e-afbc4f1c079f.png)

then I run 
`python detect.py --source ./img/2.jpg --weights ./VOC/yolov5s/weights/best.pt --iou-thres 0.45 --conf-thres 0.2 --img-size 640
`
and I get the following result:
![image](https://user-images.githubusercontent.com/49439344/112458957-4a897580-8d98-11eb-8815-50fe2a760867.png)

I have set the same iou-thres and conf-thres and img-size for them ,but why are the results different?
What should I do to make them predict the same result?

Thanks!!!Yolov5 is really a nice code!

**Comment by glenn-jocher** [comment]
@zyx792726304 👋 Hello, thank you for asking about the differences between inference with detect.py and testing with test.py! [detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py) and [test.py](https://github.com/ultralytics/yolov5/blob/master/test.py) are designed for different purposes and utilize completely separate dataloaders. test.py is designed to obtain the best mAP on a validation dataset, and detect.py is designed for best real-world inference results. A few important aspects of each:

## detect.py

- dataloader: designed for loading multiple types of media (images, videos, globs, directories, streams). https://github.com/ultralytics/yolov5/blob/16206692f245e713a5beb380de6dc4bed944986c/utils/datasets.py#L122
- image size: 640
- [confidence threshold](https://github.com/ultralytics/yolov5/blob/16206692f245e713a5beb380de6dc4bed944986c/detect.py#L152): 0.25 
- [iou threshold](https://github.com/ultralytics/yolov5/blob/16206692f245e713a5beb380de6dc4bed944986c/detect.py#L153): 0.45
- [multi-label](https://github.com/ultralytics/yolov5/blob/16206692f245e713a5beb380de6dc4bed944986c/utils/general.py#L415): False
- [padding](https://github.com/ultralytics/yolov5/blob/16206692f245e713a5beb380de6dc4bed944986c/detect.py#L45-L54): None

## test.py

- dataloader: designed to load train, val, test dataset images and labels. Augmentation capable. https://github.com/ultralytics/yolov5/blob/16206692f245e713a5beb380de6dc4bed944986c/utils/datasets.py#L341
- image size: 640
- [confidence threshold](https://github.com/ultralytics/yolov5/blob/16206692f245e713a5beb380de6dc4bed944986c/test.py#L291): 0.001
- [iou threshold](https://github.com/ultralytics/yolov5/blob/16206692f245e713a5beb380de6dc4bed944986c/test.py#L292): 0.65
- [multi-label](https://github.com/ultralytics/yolov5/blob/16206692f245e713a5beb380de6dc4bed944986c/test.py#L120): True
- [padding](https://github.com/ultralytics/yolov5/blob/16206692f245e713a5beb380de6dc4bed944986c/test.py#L83-L90): 0.5 * maximum stride
