### ISSUE TITLE
How to create .yaml files?

### ISSUE THREAD

**Issue by Duarte-Nunes** [ultralytics/yolov5#2599]
## ❔Question
Is there a way or tutorial that you can make avaiable that would allow for easily creating .yaml files for existing models?

## Additional context
I have been studying yolov4 but wanted to use this repository since its always up to date and works like a charm, however there is currently no yolov4.yaml file.

I saw another issue where this same question was made but the yolov4.yaml that was suggested by a user wasn't entirelly accurate, is there something that i can use as a guide to learn how to write the .yaml files?

**Comment by glenn-jocher** [comment]
@Duarte-Nunes yes, you should be able to design any model really using a yaml file, as long as the custom modules are available also in models/common.py or models/experimental.py. 

We tried to make the repo as model agnostic as possible, so it should be able to build and train all kinds of detection and classification models, and hopefully segmentation models in the future as well.

**Comment by Duarte-Nunes** [comment]
@glenn-jocher Howdy, thank you for you response, by taking a look at  WongKinYiu/PyTorch_YOLOv4 and YoloV5 and going back and forth comparing yaml and cfg files i think i was able to create a yolov4-tiny.yaml and yolov4-tiny-3l.yaml files.

On another note i have a question about the img size, when you have an anotation on an image in YOLO format and then its resized to 640 (or other sizes) do the boxes on the anotations also get resized?

I'm asking because im trying to make a custom dataset however i want to now if i should annotate the images after converting them to 640x640 or i could just annotate them at any size and they get auto scaled.

**Comment by glenn-jocher** [comment]
@Duarte-Nunes YOLO format labels used normalized image coordinates in the range of 0-1, so they are independent of image sizes. 

That's great that you got some new model yamls created! Please consider submitting a PR with these additions to help provide everyone else access to these also, thank you!

**Comment by glenn-jocher** [comment]
@Duarte-Nunes BTW, for full details on the YOLO format labels see:
https://docs.ultralytics.com/yolov5/tutorials/train_custom_data#2-create-labels

### 2. Create Labels

After using a tool like [CVAT](https://github.com/opencv/cvat), [makesense.ai](https://www.makesense.ai/) or [Labelbox](https://labelbox.com/)  to label your images, export your labels to **YOLO format**, with one `*.txt` file per image (if no objects in image, no `*.txt` file is required). The `*.txt` file specifications are:

- One row per object
- Each row is `class x_center y_center width height` format.
- Box coordinates must be in **normalized xywh** format (from 0 - 1). If your boxes are in pixels, divide `x_center` and `width` by image width, and `y_center` and `height` by image height.
- Class numbers are zero-indexed (start from 0).

<img width="800" alt="Image Labels" src="https://user-images.githubusercontent.com/26833433/91506361-c7965000-e886-11ea-8291-c72b98c25eec.jpg">

The label file corresponding to the above image contains 2 persons (class `0`) and a tie (class `27`):

<p align="center"><img width="428" src="https://user-images.githubusercontent.com/26833433/112467037-d2568c00-8d66-11eb-8796-55402ac0d62f.png"></p>

**Comment by Duarte-Nunes** [comment]
@glenn-jocher Thank you for the timely answers. I'll submit a PR with the files soon, just need to touch them up a bit to get rid of the janky names i used for the modules XD

**Comment by glenn-jocher** [comment]
Great! Yes, I would try to at least provide one line comment describing each module and linking to a source if applicable, i.e.:
https://github.com/ultralytics/yolov5/blob/ee169834bd0edf4e03b555688053da7bdd05a71e/models/experimental.py#L46-L57
