### ISSUE TITLE
how can I get cfg file from yaml?

### ISSUE THREAD

**Issue by monoloxo** [ultralytics/yolov5#26]
how to get cfg file like in darknet?

**Comment by glenn-jocher** [comment]
@monoloxo you'd have to write a conversion script on your own. At the moment there is no backward compatibility with darknet *.cfg files.

**Comment by stiv-yakovenko** [comment]
This is a huge disadavantage, you can't easily export models to production.

**Comment by adrianosantospb** [comment]
Hi, 

I dont know if someone still needs this, but I did a script to: https://github.com/adrianosantospb/yolov5_ultralytics_to_darnet_format

**Comment by gigDevelopment10** [comment]
Hii there!
Can I use yolov5 in android studio ??
If so could u tell how ..

**Comment by gigDevelopment10** [comment]
Hii there!
Can I use yolov5 in android studio ??
If so could u tell how ..
@adrianosantospb  and @glenn-jocher
