### ISSUE TITLE
I can't detect pictures with pytorch1.8.0

### ISSUE THREAD

**Issue by zzttqu** [ultralytics/yolov5#2601]
I install pytorch 1.8.0 in anaconda, and run the detect programme, and nothing can be detect , even I use the default setting, still don't work. But when I change to pytorch 1.7.0, It worked. 
I can train and test with pytorch 1.8.0, only can't detect. Thanks in advance.

**Comment by zzttqu** [comment]
![image](https://user-images.githubusercontent.com/80448114/112506954-33af4700-8dc9-11eb-928b-313925bfb0c3.png)
![image](https://user-images.githubusercontent.com/80448114/112507098-53466f80-8dc9-11eb-8ea1-7dca9ddd7cf8.png)
I install all packages in the requirement.txt

**Comment by glenn-jocher** [comment]
@zzttqu thanks for the bug report! This has been reported by users before, I think the common problem had to do with torch CUDA and windows. The Colab environment uses torch 1.8.0 and runs detect.py correctly:
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb?hl=en
<img width="1201" alt="Screenshot 2021-03-25 at 20 58 13" src="https://user-images.githubusercontent.com/26833433/112535878-10769e80-8dad-11eb-9549-e4a2b78b5f90.png">

And the Windows CI tests run detect.py correctly with torch 1.8 also (CI checks are not available with Windows GPU though):
https://github.com/ultralytics/yolov5/runs/2189122540?check_suite_focus=true
<img width="1706" alt="Screenshot 2021-03-25 at 21 02 24" src="https://user-images.githubusercontent.com/26833433/112536214-76632600-8dad-11eb-8c49-8dde45d2f58c.png">

**Comment by zzttqu** [comment]
I change my cudatoolkit to 10.2 and pytorch 1.8.1 and it can detect, I think the bug might be caused by cudatoolkit11.

**Comment by glenn-jocher** [comment]
Great!
