### ISSUE TITLE
Adding Another head that does not share weights with the other

### ISSUE THREAD

**Issue by naruarjun** [ultralytics/yolov5#2607]
## ❔Question
Hello. I wanted to ask what is the easiest way to add another head and train both the heads to detect different objects while using the same backbone.

## Additional context
The final model that I want needs to be trained in a Multi-Task setup where both heads share the same backbone.

**Comment by naruarjun** [comment]
#2001 has the solution

**Comment by LeonNerd** [comment]
hello, I want to do the same thing，I want needs to be trained in a Multi-Task setup where both heads share the same backbone. what should i do? thanks

**Comment by glenn-jocher** [comment]
@LeonNerd hello! To train a multi-task setup with separate heads sharing the same backbone, you can define two separate head modules in the YOLOv5 architecture. Each head will have its own set of detection classes and prediction parameters. You can find more information on this in the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/. Let me know if you need further guidance!

**Comment by jain-abhay** [comment]
> ## ❔Question
> Hello. I wanted to ask what is the easiest way to add another head and train both the heads to detect different objects while using the same backbone.
> 
> ## Additional context
> The final model that I want needs to be trained in a Multi-Task setup where both heads share the same backbone.

Hi @naruarjun , I am currently researching on a similar problem with a common backbone and 2 different heads. Please can you kindly share your inputs with me about this. Thanks
