### ISSUE TITLE
Crop and save bounding box. I found yolov4 can do and any for yolov5?

### ISSUE THREAD

**Issue by mmez-11** [ultralytics/yolov5#2608]

**Comment by shiv-acharii** [comment]
https://github.com/ultralytics/yolov5/issues/803#issuecomment-695824665

follow this comment, it works really well

**Comment by mmez-11** [comment]
> [#803 (comment)](https://github.com/ultralytics/yolov5/issues/803#issuecomment-695824665)
> 
> follow this comment, it works really well

Thanks. I checked what you mentioned. Actually i want  the bbox's area only as an image.

**Comment by shiv-acharii** [comment]
Here is the updated detect.py files which saves the bounding box as a separate image in 'test_images/results/'
actual results with input image and bounding box will be saved in 'yolov5\runs\detect\exp'
only bounding boxes cropped as image will be saved in 'yolo5/test_images/results' (manually create directory 1st)

```
import argparse
import os
import time
from pathlib import Path
import numpy as np

import cv2
import torch
import torch.backends.cudnn as cudnn
from numpy import random

from models.experimental import attempt_load
from utils.datasets import LoadStreams, LoadImages
from utils.general import check_img_size, check_requirements, check_imshow, non_max_suppression, apply_classifier, \
    scale_coords, xyxy2xywh, strip_optimizer, set_logging, increment_path
from utils.plots import plot_one_box
from utils.torch_utils import select_device, load_classifier, time_synchronized


def detect(save_img=False):
    source, weights, view_img, save_txt, imgsz = opt.source, opt.weights, opt.view_img, opt.save_txt, opt.img_size
    webcam = source.isnumeric() or source.endswith('.txt') or source.lower().startswith(
        ('rtsp://', 'rtmp://', 'http://'))

    # Directories
    save_dir = Path(increment_path(Path(opt.project) / opt.name, exist_ok=opt.exist_ok))  # increment run
    (save_dir / 'labels' if save_txt else save_dir).mkdir(parents=True, exist_ok=True)  # make dir

    # Initialize
    set_logging()
    device = select_device(opt.device)
    half = device.type != 'cpu'  # half precision only supported on CUDA

    # Load model
    model = attempt_load(weights, map_location=device)  # load FP32 model
    stride = int(model.stride.max())  # model stride
    imgsz = check_img_size(imgsz, s=stride)  # check img_size
    if half:
        model.half()  # to FP16

    # Second-stage classifier
    classify = False
    if classify:
        modelc = load_classifier(name='resnet101', n=2)  # initialize
        modelc.load_state_dict(torch.load('weights/resnet101.pt', map_location=device)['model']).to(device).eval()

    # Set Dataloader
    vid_path, vid_writer = None, None
    if webcam:
        view_img = check_imshow()
        cudnn.benchmark = True  # set True to speed up constant image size inference
        dataset = LoadStreams(source, img_size=imgsz, stride=stride)
    else:
        save_img = True
        dataset = LoadImages(source, img_size=imgsz, stride=stride)

    # Get names and colors
    names = model.module.names if hasattr(model, 'module') else model.names
    colors = [[random.randint(0, 255) for _ in range(3)] for _ in names]

    # Run inference
    if device.type != 'cpu':
        model(torch.zeros(1, 3, imgsz, imgsz).to(device).type_as(next(model.parameters())))  # run once
    t0 = time.time()
    for path, img, im0s, vid_cap in dataset:
        img = torch.from_numpy(img).to(device)
        img = img.half() if half else img.float()  # uint8 to fp16/32
        img /= 255.0  # 0 - 255 to 0.0 - 1.0
        if img.ndimension() == 3:
            img = img.unsqueeze(0)

        # Inference
        t1 = time_synchronized()
        pred = model(img, augment=opt.augment)[0]

        # Apply NMS
        pred = non_max_suppression(pred, opt.conf_thres, opt.iou_thres, classes=opt.classes, agnostic=opt.agnostic_nms)
        t2 = time_synchronized()

        # Apply Classifier
        if classify:
            pred = apply_classifier(pred, modelc, img, im0s)

        # Process detections
        for i, det in enumerate(pred):  # detections per image
            if webcam:  # batch_size >= 1
                p, s, im0, frame = path[i], '%g: ' % i, im0s[i].copy(), dataset.count
            else:
                p, s, im0, frame = path, '', im0s, getattr(dataset, 'frame', 0)

            p = Path(p)  # to Path
            save_path = str(save_dir / p.name)  # img.jpg
            txt_path = str(save_dir / 'labels' / p.stem) + ('' if dataset.mode == 'image' else f'_{frame}')  # img.txt
            s += '%gx%g ' % img.shape[2:]  # print string
            gn = torch.tensor(im0.shape)[[1, 0, 1, 0]]  # normalization gain whwh
            if len(det):
                # Rescale boxes from img_size to im0 size
                det[:, :4] = scale_coords(img.shape[2:], det[:, :4], im0.shape).round()

                # Print results
                for c in det[:, -1].unique():
                    n = (det[:, -1] == c).sum()  # detections per class
                    s += f"{n} {names[int(c)]}{'s' * (n > 1)}, "  # add to string

                # Write results
                 # Write results
                for *xyxy, conf, cls in det:
                    if save_txt:  # Write to file
                        xywh = (xyxy2xywh(torch.tensor(xyxy).view(1, 4)) / gn).view(-1).tolist()  # normalized xywh
                        with open(txt_path + '.txt', 'a') as f:
                            f.write(('%g ' * 5 + '\n') % (cls, *xywh))  # label format
                    
                    if save_img or view_img:  # Add bbox to image
                        label = '%s %.2f' % (names[int(cls)], conf)
                        plot_one_box(xyxy, im0, label=label, color=colors[int(cls)], line_thickness=3)
                    
                    save_obj = True
                    if save_obj:
                        for k in range(len(det)):
                            x,y,w,h=int(xyxy[0]), int(xyxy[1]), int(xyxy[2] - xyxy[0]), int(xyxy[3] - xyxy[1])                   
                            img_ = im0.astype(np.uint8)
                            crop_img=img_[y:y+ h, x:x + w]                          
                                
                            #!!rescale image !!!
                            filename=p.name
                            filepath=os.path.join(r'test_images/results/', filename)
                            print(filepath)
                            cv2.imwrite(filepath, crop_img) 
                            
                        else:
                            print("There is no detected object")
                            continue

            # Print time (inference + NMS)
            print(f'{s}Done. ({t2 - t1:.3f}s)')

            # Stream results
            if view_img:
                cv2.imshow(str(p), im0)
                cv2.waitKey(1)  # 1 millisecond

            # Save results (image with detections)
            if save_img:
                if dataset.mode == 'image':
                    cv2.imwrite(save_path, im0)
                else:  # 'video'
                    if vid_path != save_path:  # new video
                        vid_path = save_path
                        if isinstance(vid_writer, cv2.VideoWriter):
                            vid_writer.release()  # release previous video writer

                        fourcc = 'mp4v'  # output video codec
                        fps = vid_cap.get(cv2.CAP_PROP_FPS)
                        w = int(vid_cap.get(cv2.CAP_PROP_FRAME_WIDTH))
                        h = int(vid_cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
                        vid_writer = cv2.VideoWriter(save_path, cv2.VideoWriter_fourcc(*fourcc), fps, (w, h))
                    vid_writer.write(im0)

    if save_txt or save_img:
        s = f"\n{len(list(save_dir.glob('labels/*.txt')))} labels saved to {save_dir / 'labels'}" if save_txt else ''
        print(f"Results saved to {save_dir}{s}")

    print(f'Done. ({time.time() - t0:.3f}s)')


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--weights', nargs='+', type=str, default='yolov5s.pt', help='model.pt path(s)')
    parser.add_argument('--source', type=str, default='data/images', help='source')  # file/folder, 0 for webcam
    parser.add_argument('--img-size', type=int, default=640, help='inference size (pixels)')
    parser.add_argument('--conf-thres', type=float, default=0.25, help='object confidence threshold')
    parser.add_argument('--iou-thres', type=float, default=0.45, help='IOU threshold for NMS')
    parser.add_argument('--device', default='', help='cuda device, i.e. 0 or 0,1,2,3 or cpu')
    parser.add_argument('--view-img', action='store_true', help='display results')
    parser.add_argument('--save-txt', action='store_true', help='save results to *.txt')
    parser.add_argument('--save-conf', action='store_true', help='save confidences in --save-txt labels')
    parser.add_argument('--classes', nargs='+', type=int, help='filter by class: --class 0, or --class 0 2 3')
    parser.add_argument('--agnostic-nms', action='store_true', help='class-agnostic NMS')
    parser.add_argument('--augment', action='store_true', help='augmented inference')
    parser.add_argument('--update', action='store_true', help='update all models')
    parser.add_argument('--project', default='runs/detect', help='save results to project/name')
    parser.add_argument('--name', default='exp', help='save results to project/name')
    parser.add_argument('--exist-ok', action='store_true', help='existing project/name ok, do not increment')
    opt = parser.parse_args()
    print(opt)
    check_requirements(exclude=('pycocotools', 'thop'))

    with torch.no_grad():
        if opt.update:  # update all models (to fix SourceChangeWarning)
            for opt.weights in ['yolov5s.pt', 'yolov5m.pt', 'yolov5l.pt', 'yolov5x.pt']:
                detect()
                strip_optimizer(opt.weights)
        else:
            detect()

```

**Comment by mmez-11** [comment]
> Here is the updated detect.py files which saves the bounding box as a separate image in 'test_images/results/'
> actual results with input image and bounding box will be saved in 'yolov5\runs\detect\exp'
> only bounding boxes cropped as image will be saved in 'yolo5/test_images/results' (manually create directory 1st)
> 
> ```
> import argparse
> import os
> import time
> from pathlib import Path
> import numpy as np
> 
> import cv2
> import torch
> import torch.backends.cudnn as cudnn
> from numpy import random
> 
> from models.experimental import attempt_load
> from utils.datasets import LoadStreams, LoadImages
> from utils.general import check_img_size, check_requirements, check_imshow, non_max_suppression, apply_classifier, \
>     scale_coords, xyxy2xywh, strip_optimizer, set_logging, increment_path
> from utils.plots import plot_one_box
> from utils.torch_utils import select_device, load_classifier, time_synchronized
> 
> 
> def detect(save_img=False):
>     source, weights, view_img, save_txt, imgsz = opt.source, opt.weights, opt.view_img, opt.save_txt, opt.img_size
>     webcam = source.isnumeric() or source.endswith('.txt') or source.lower().startswith(
>         ('rtsp://', 'rtmp://', 'http://'))
> 
>     # Directories
>     save_dir = Path(increment_path(Path(opt.project) / opt.name, exist_ok=opt.exist_ok))  # increment run
>     (save_dir / 'labels' if save_txt else save_dir).mkdir(parents=True, exist_ok=True)  # make dir
> 
>     # Initialize
>     set_logging()
>     device = select_device(opt.device)
>     half = device.type != 'cpu'  # half precision only supported on CUDA
> 
>     # Load model
>     model = attempt_load(weights, map_location=device)  # load FP32 model
>     stride = int(model.stride.max())  # model stride
>     imgsz = check_img_size(imgsz, s=stride)  # check img_size
>     if half:
>         model.half()  # to FP16
> 
>     # Second-stage classifier
>     classify = False
>     if classify:
>         modelc = load_classifier(name='resnet101', n=2)  # initialize
>         modelc.load_state_dict(torch.load('weights/resnet101.pt', map_location=device)['model']).to(device).eval()
> 
>     # Set Dataloader
>     vid_path, vid_writer = None, None
>     if webcam:
>         view_img = check_imshow()
>         cudnn.benchmark = True  # set True to speed up constant image size inference
>         dataset = LoadStreams(source, img_size=imgsz, stride=stride)
>     else:
>         save_img = True
>         dataset = LoadImages(source, img_size=imgsz, stride=stride)
> 
>     # Get names and colors
>     names = model.module.names if hasattr(model, 'module') else model.names
>     colors = [[random.randint(0, 255) for _ in range(3)] for _ in names]
> 
>     # Run inference
>     if device.type != 'cpu':
>         model(torch.zeros(1, 3, imgsz, imgsz).to(device).type_as(next(model.parameters())))  # run once
>     t0 = time.time()
>     for path, img, im0s, vid_cap in dataset:
>         img = torch.from_numpy(img).to(device)
>         img = img.half() if half else img.float()  # uint8 to fp16/32
>         img /= 255.0  # 0 - 255 to 0.0 - 1.0
>         if img.ndimension() == 3:
>             img = img.unsqueeze(0)
> 
>         # Inference
>         t1 = time_synchronized()
>         pred = model(img, augment=opt.augment)[0]
> 
>         # Apply NMS
>         pred = non_max_suppression(pred, opt.conf_thres, opt.iou_thres, classes=opt.classes, agnostic=opt.agnostic_nms)
>         t2 = time_synchronized()
> 
>         # Apply Classifier
>         if classify:
>             pred = apply_classifier(pred, modelc, img, im0s)
> 
>         # Process detections
>         for i, det in enumerate(pred):  # detections per image
>             if webcam:  # batch_size >= 1
>                 p, s, im0, frame = path[i], '%g: ' % i, im0s[i].copy(), dataset.count
>             else:
>                 p, s, im0, frame = path, '', im0s, getattr(dataset, 'frame', 0)
> 
>             p = Path(p)  # to Path
>             save_path = str(save_dir / p.name)  # img.jpg
>             txt_path = str(save_dir / 'labels' / p.stem) + ('' if dataset.mode == 'image' else f'_{frame}')  # img.txt
>             s += '%gx%g ' % img.shape[2:]  # print string
>             gn = torch.tensor(im0.shape)[[1, 0, 1, 0]]  # normalization gain whwh
>             if len(det):
>                 # Rescale boxes from img_size to im0 size
>                 det[:, :4] = scale_coords(img.shape[2:], det[:, :4], im0.shape).round()
> 
>                 # Print results
>                 for c in det[:, -1].unique():
>                     n = (det[:, -1] == c).sum()  # detections per class
>                     s += f"{n} {names[int(c)]}{'s' * (n > 1)}, "  # add to string
> 
>                 # Write results
>                  # Write results
>                 for *xyxy, conf, cls in det:
>                     if save_txt:  # Write to file
>                         xywh = (xyxy2xywh(torch.tensor(xyxy).view(1, 4)) / gn).view(-1).tolist()  # normalized xywh
>                         with open(txt_path + '.txt', 'a') as f:
>                             f.write(('%g ' * 5 + '\n') % (cls, *xywh))  # label format
>                     
>                     if save_img or view_img:  # Add bbox to image
>                         label = '%s %.2f' % (names[int(cls)], conf)
>                         plot_one_box(xyxy, im0, label=label, color=colors[int(cls)], line_thickness=3)
>                     
>                     save_obj = True
>                     if save_obj:
>                         for k in range(len(det)):
>                             x,y,w,h=int(xyxy[0]), int(xyxy[1]), int(xyxy[2] - xyxy[0]), int(xyxy[3] - xyxy[1])                   
>                             img_ = im0.astype(np.uint8)
>                             crop_img=img_[y:y+ h, x:x + w]                          
>                                 
>                             #!!rescale image !!!
>                             filename=p.name
>                             filepath=os.path.join(r'test_images/results/', filename)
>                             print(filepath)
>                             cv2.imwrite(filepath, crop_img) 
>                             
>                         else:
>                             print("There is no detected object")
>                             continue
> 
>             # Print time (inference + NMS)
>             print(f'{s}Done. ({t2 - t1:.3f}s)')
> 
>             # Stream results
>             if view_img:
>                 cv2.imshow(str(p), im0)
>                 cv2.waitKey(1)  # 1 millisecond
> 
>             # Save results (image with detections)
>             if save_img:
>                 if dataset.mode == 'image':
>                     cv2.imwrite(save_path, im0)
>                 else:  # 'video'
>                     if vid_path != save_path:  # new video
>                         vid_path = save_path
>                         if isinstance(vid_writer, cv2.VideoWriter):
>                             vid_writer.release()  # release previous video writer
> 
>                         fourcc = 'mp4v'  # output video codec
>                         fps = vid_cap.get(cv2.CAP_PROP_FPS)
>                         w = int(vid_cap.get(cv2.CAP_PROP_FRAME_WIDTH))
>                         h = int(vid_cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
>                         vid_writer = cv2.VideoWriter(save_path, cv2.VideoWriter_fourcc(*fourcc), fps, (w, h))
>                     vid_writer.write(im0)
> 
>     if save_txt or save_img:
>         s = f"\n{len(list(save_dir.glob('labels/*.txt')))} labels saved to {save_dir / 'labels'}" if save_txt else ''
>         print(f"Results saved to {save_dir}{s}")
> 
>     print(f'Done. ({time.time() - t0:.3f}s)')
> 
> 
> if __name__ == '__main__':
>     parser = argparse.ArgumentParser()
>     parser.add_argument('--weights', nargs='+', type=str, default='yolov5s.pt', help='model.pt path(s)')
>     parser.add_argument('--source', type=str, default='data/images', help='source')  # file/folder, 0 for webcam
>     parser.add_argument('--img-size', type=int, default=640, help='inference size (pixels)')
>     parser.add_argument('--conf-thres', type=float, default=0.25, help='object confidence threshold')
>     parser.add_argument('--iou-thres', type=float, default=0.45, help='IOU threshold for NMS')
>     parser.add_argument('--device', default='', help='cuda device, i.e. 0 or 0,1,2,3 or cpu')
>     parser.add_argument('--view-img', action='store_true', help='display results')
>     parser.add_argument('--save-txt', action='store_true', help='save results to *.txt')
>     parser.add_argument('--save-conf', action='store_true', help='save confidences in --save-txt labels')
>     parser.add_argument('--classes', nargs='+', type=int, help='filter by class: --class 0, or --class 0 2 3')
>     parser.add_argument('--agnostic-nms', action='store_true', help='class-agnostic NMS')
>     parser.add_argument('--augment', action='store_true', help='augmented inference')
>     parser.add_argument('--update', action='store_true', help='update all models')
>     parser.add_argument('--project', default='runs/detect', help='save results to project/name')
>     parser.add_argument('--name', default='exp', help='save results to project/name')
>     parser.add_argument('--exist-ok', action='store_true', help='existing project/name ok, do not increment')
>     opt = parser.parse_args()
>     print(opt)
>     check_requirements(exclude=('pycocotools', 'thop'))
> 
>     with torch.no_grad():
>         if opt.update:  # update all models (to fix SourceChangeWarning)
>             for opt.weights in ['yolov5s.pt', 'yolov5m.pt', 'yolov5l.pt', 'yolov5x.pt']:
>                 detect()
>                 strip_optimizer(opt.weights)
>         else:
>             detect()
> ```

OMG, that is worked. Thanks a lot.

**Comment by shiv-acharii** [comment]
@mmez-11 Welcome.

**Comment by burhr2** [comment]
I have made a PR for these changes. I added the option to save the detected objects in a separate folder which will be in project/name/cropped when using detect.py. You can simply save this code as detect.py and use the option save_obj if you want to save the detected object. Thanks to @shivprasad94 for the initial codes but it only saves one object per image. I made the changes to save each detected object of an image.

```
import argparse
import os
import time
from pathlib import Path
import numpy as np

import cv2
import torch
import torch.backends.cudnn as cudnn
from numpy import random

from models.experimental import attempt_load
from utils.datasets import LoadStreams, LoadImages
from utils.general import check_img_size, check_requirements, check_imshow, non_max_suppression, apply_classifier, \
    scale_coords, xyxy2xywh, strip_optimizer, set_logging, increment_path
from utils.plots import plot_one_box
from utils.torch_utils import select_device, load_classifier, time_synchronized


def detect(save_img=False):
    source, weights, view_img, save_obj, save_txt, imgsz = opt.source, opt.weights, opt.view_img, opt.save_obj, opt.save_txt, opt.img_size
    webcam = source.isnumeric() or source.endswith('.txt') or source.lower().startswith(
        ('rtsp://', 'rtmp://', 'http://'))

    # Directories
    save_dir = Path(increment_path(Path(opt.project) / opt.name, exist_ok=opt.exist_ok))  # increment run
    (save_dir / 'labels' if save_txt else save_dir).mkdir(parents=True, exist_ok=True)  # make dir
    (save_dir / 'cropped' if save_obj else save_dir).mkdir(parents=True, exist_ok=True)
    # Initialize
    set_logging()
    device = select_device(opt.device)
    half = device.type != 'cpu'  # half precision only supported on CUDA

    # Load model
    model = attempt_load(weights, map_location=device)  # load FP32 model
    stride = int(model.stride.max())  # model stride
    imgsz = check_img_size(imgsz, s=stride)  # check img_size
    if half:
        model.half()  # to FP16

    # Second-stage classifier
    classify = False
    if classify:
        modelc = load_classifier(name='resnet101', n=2)  # initialize
        modelc.load_state_dict(torch.load('weights/resnet101.pt', map_location=device)['model']).to(device).eval()

    # Set Dataloader
    vid_path, vid_writer = None, None
    if webcam:
        view_img = check_imshow()
        cudnn.benchmark = True  # set True to speed up constant image size inference
        dataset = LoadStreams(source, img_size=imgsz, stride=stride)
    else:
        save_img = True
        dataset = LoadImages(source, img_size=imgsz, stride=stride)

    # Get names and colors
    names = model.module.names if hasattr(model, 'module') else model.names
    colors = [[random.randint(0, 255) for _ in range(3)] for _ in names]

    # Run inference
    if device.type != 'cpu':
        model(torch.zeros(1, 3, imgsz, imgsz).to(device).type_as(next(model.parameters())))  # run once
    t0 = time.time()
    for path, img, im0s, vid_cap in dataset:
        img = torch.from_numpy(img).to(device)
        img = img.half() if half else img.float()  # uint8 to fp16/32
        img /= 255.0  # 0 - 255 to 0.0 - 1.0
        if img.ndimension() == 3:
            img = img.unsqueeze(0)

        # Inference
        t1 = time_synchronized()
        pred = model(img, augment=opt.augment)[0]

        # Apply NMS
        pred = non_max_suppression(pred, opt.conf_thres, opt.iou_thres, classes=opt.classes, agnostic=opt.agnostic_nms)
        t2 = time_synchronized()

        # Apply Classifier
        if classify:
            pred = apply_classifier(pred, modelc, img, im0s)

        # Process detections
        for i, det in enumerate(pred):  # detections per image
            if webcam:  # batch_size >= 1
                p, s, im0, frame = path[i], '%g: ' % i, im0s[i].copy(), dataset.count
            else:
                p, s, im0, frame = path, '', im0s, getattr(dataset, 'frame', 0)
            
            im1=im0.copy()
            p = Path(p)  # to Path
            save_path = str(save_dir / p.name)  # img.jpg
            txt_path = str(save_dir / 'labels' / p.stem) + ('' if dataset.mode == 'image' else f'_{frame}')  # img.txt
            s += '%gx%g ' % img.shape[2:]  # print string
            gn = torch.tensor(im0.shape)[[1, 0, 1, 0]]  # normalization gain whwh
            if len(det):
                # Rescale boxes from img_size to im0 size
                det[:, :4] = scale_coords(img.shape[2:], det[:, :4], im0.shape).round()

                # Print results
                for c in det[:, -1].unique():
                    n = (det[:, -1] == c).sum()  # detections per class
                    s += f"{n} {names[int(c)]}{'s' * (n > 1)}, "  # add to string

                # Write results
                 # Write results
                k = 0 
                for *xyxy, conf, cls in det:
                    if save_txt:  # Write to file
                        xywh = (xyxy2xywh(torch.tensor(xyxy).view(1, 4)) / gn).view(-1).tolist()  # normalized xywh
                        with open(txt_path + '.txt', 'a') as f:
                            f.write(('%g ' * 5 + '\n') % (cls, *xywh))  # label format
                    
                    if save_img or view_img:  # Add bbox to image
                        label = '%s %.2f' % (names[int(cls)], conf)
                        plot_one_box(xyxy, im0, label=label, color=colors[int(cls)], line_thickness=3)
                    
                    
                    if save_obj:
                        x,y,w,h=int(xyxy[0]), int(xyxy[1]), int(xyxy[2] - xyxy[0]), int(xyxy[3] - xyxy[1])                   
                        img_ = im1.astype(np.uint8)
                        crop_img=img_[y:y+ h, x:x + w]                          
                            
                        #!!rescale image !!!
                        filename=p.name
                        filename_no_extesion=filename.split('.')[0]
                        extension=filename.split('.')[1]
                        new_filename=str(filename_no_extesion) + '_' + str(k) + '.' + str(extension) 
                        dir_path=os.path.join(save_dir,'cropped')
                        filepath=os.path.join(dir_path, new_filename)
                        print(filepath)
                        cv2.imwrite(filepath, crop_img)
                        k=k+1
                    else:
                        print("There is no detected object")
                        continue

            # Print time (inference + NMS)
            print(f'{s}Done. ({t2 - t1:.3f}s)')

            # Stream results
            if view_img:
                cv2.imshow(str(p), im0)
                cv2.waitKey(1)  # 1 millisecond

            # Save results (image with detections)
            if save_img:
                if dataset.mode == 'image':
                    cv2.imwrite(save_path, im0)
                else:  # 'video'
                    if vid_path != save_path:  # new video
                        vid_path = save_path
                        if isinstance(vid_writer, cv2.VideoWriter):
                            vid_writer.release()  # release previous video writer

                        fourcc = 'mp4v'  # output video codec
                        fps = vid_cap.get(cv2.CAP_PROP_FPS)
                        w = int(vid_cap.get(cv2.CAP_PROP_FRAME_WIDTH))
                        h = int(vid_cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
                        vid_writer = cv2.VideoWriter(save_path, cv2.VideoWriter_fourcc(*fourcc), fps, (w, h))
                    vid_writer.write(im0)

    if save_txt or save_img:
        s = f"\n{len(list(save_dir.glob('labels/*.txt')))} labels saved to {save_dir / 'labels'}" if save_txt else ''
        print(f"Results saved to {save_dir}{s}")

    print(f'Done. ({time.time() - t0:.3f}s)')


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--weights', nargs='+', type=str, default='yolov5s.pt', help='model.pt path(s)')
    parser.add_argument('--source', type=str, default='data/images', help='source')  # file/folder, 0 for webcam
    parser.add_argument('--img-size', type=int, default=640, help='inference size (pixels)')
    parser.add_argument('--conf-thres', type=float, default=0.25, help='object confidence threshold')
    parser.add_argument('--iou-thres', type=float, default=0.45, help='IOU threshold for NMS')
    parser.add_argument('--device', default='', help='cuda device, i.e. 0 or 0,1,2,3 or cpu')
    parser.add_argument('--view-img', action='store_true', help='display results')
    parser.add_argument('--save-txt', action='store_false', help='save results to *.txt')
    parser.add_argument('--save_obj', action='store_false', help='save the detected object as separate image')
    parser.add_argument('--save-conf', action='store_true', help='save confidences in --save-txt labels')
    parser.add_argument('--classes', nargs='+', type=int, help='filter by class: --class 0, or --class 0 2 3')
    parser.add_argument('--agnostic-nms', action='store_true', help='class-agnostic NMS')
    parser.add_argument('--augment', action='store_true', help='augmented inference')
    parser.add_argument('--update', action='store_true', help='update all models')
    parser.add_argument('--project', default='runs/detect', help='save results to project/name')
    parser.add_argument('--name', default='exp', help='save results to project/name')
    parser.add_argument('--exist-ok', action='store_true', help='existing project/name ok, do not increment')
    opt = parser.parse_args()
    print(opt)
    check_requirements(exclude=('pycocotools', 'thop'))

    with torch.no_grad():
        if opt.update:  # update all models (to fix SourceChangeWarning)
            for opt.weights in ['yolov5s.pt', 'yolov5m.pt', 'yolov5l.pt', 'yolov5x.pt']:
                detect()
                strip_optimizer(opt.weights)
        else:
            detect()
```

**Comment by shiv-acharii** [comment]
@Ab-Abdurrahman hey, you're correct. I made written the function only to save only 1 cropped box. Just tested your scripts, works well for multiple boxes now.
Thanks for the contribution. 👏👌

**Comment by glenn-jocher** [comment]
@Ab-Abdurrahman @shivprasad94 @mmez-11 Prediction box cropping is now available in YOLOv5 via PR https://github.com/ultralytics/yolov5/pull/2827! PyTorch Hub models can use `results.crop()` or detect.py can be called with the `--save-crop` argument. Example usage:
```
python detect.py --save-crop
```
<img width="1121" alt="Screenshot 2021-04-20 at 23 50 51" src="https://user-images.githubusercontent.com/26833433/115468484-70892500-a233-11eb-89e8-717bef0fa45b.png">

**Comment by pragyan430** [comment]
hey @glenn-jocher --save-crop saves very few cropped images from a video; only two for each class. How do I increase this number?

**Comment by glenn-jocher** [comment]
@pragyan430 --save-crop saves every detection. 

If you don't like your detections that's a separate issue that has nothing to do with cropping.

**Comment by Razamalik4497** [comment]
hey @glenn-jocher ! I'm calling my detect.py code like this: 

!python detect.py --save-crop --source "/content/gdrive/MyDrive/cap_project/Rejected" --weights /content/gdrive/MyDrive/cap_project/capbest.pt

ERROR:
detect.py: error: unrecognized arguments: --save-crop

**Comment by glenn-jocher** [comment]
@Razamalik4497 your code is out of date. To update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

**Comment by Razamalik4497** [comment]
my code is working without writing "--save-crop"

I just wrote: 
!python detect.py --source "/content/gdrive/MyDrive/cap_project/Rejected" --weights /content/gdrive/MyDrive/cap_project/capbest.pt

**Comment by jayer95** [comment]
@glenn-jocher Regarding the "save-crop" parameter, where is the code for naming each picture for the cropped pictures?

**Comment by glenn-jocher** [comment]
@jayer95 you might want to try searching detect.py for 'crop'

**Comment by jayer95** [comment]
@glenn-jocher Thank you for your help, I have found it.

**Comment by stillepuff** [comment]
@glenn-jocher hi! I want to save the whole pic with a mark cropped on it , when the label of  the video was detected, not only cropped image by saved ,what can i do thx

**Comment by glenn-jocher** [comment]
--save-crop works on videos and streams also

**Comment by stillepuff** [comment]
> --save-crop works on videos and streams also

Can I fit save-crop  save a picture every 5 seconds ?
