### ISSUE TITLE
Single channel image training？

### ISSUE THREAD

**Issue by UNeedCryDear** [ultralytics/yolov5#2609]
## 🚀 Feature

Thanks for this great work!
Can a parameter be set up to train and predict single channel image，like gray image.
## Motivation
In the actual application process, many times do not need three channel BGR-image, but a single channel gray-image. I think a lot of people will have this situation. So I hope to have a parameter that can train and predict single channel images to speed up. From three channels to single channel, I think this speed should be nearly tripled.

## Pitch
dataset=cv2.imread(train_data,0)
train(dataset,ch=1)
save(single_model)
detect_set=cv2.imread(detet_img,0)
model.predict(detect_set)

**Comment by glenn-jocher** [comment]
@UNeedCryDear single-channel to 3-channel image you will see about zero speedup. 95% of FLOPS and parameter counts are not in the initial convolution. You can verify this by creating a 1-channel model in PyTorch Hub and comparing it's metrics against the default 3-channel model:

```bash
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=False, autoshape=False, channels=3)
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=False, autoshape=False, channels=1)
```

<img width="1211" alt="Screenshot 2021-03-26 at 21 30 55" src="https://user-images.githubusercontent.com/26833433/112689502-b2b08800-8e7a-11eb-9b1c-f7fd548ec7f6.png">

See PyTorch Hub Tutorial to build your own single-channel models, though training single-channel would need some modifications to the dataloader.

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [ONNX and TorchScript Export](https://docs.ultralytics.com/yolov5/tutorials/model_export)
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by UNeedCryDear** [comment]
@glenn-jocher Thank you for your reply.
In yolovs.onnx, there are three output with shape[bs,ch,h,w,num_classes]. 

> output1: [1,3,80,80,85]

> output2:[1,3,40,40,85]

> output3:[1,3,20,20,85]
When deploying onnx_model in C + +, in the case of three channels, I had to traverse 25200（3*80*80+3*40*40+3*20*20） times to judge each anchors_box(each length is 85). But if it is a single channel, I only need to traverse 8400（25200/3）times.

Because my images are grayscale. When converting to three channels, the data of each channel is the same, which will cause huge waste. So I'm going to ask if there's any way to get a single channel model.

Thank you again for your reply. I'll try it myself.

**Comment by glenn-jocher** [comment]
@UNeedCryDear your interpretation of the output shape being a function of the channel count is incorrect. Output shape is a function of anchor count and image size only, not channel count.

**Comment by UNeedCryDear** [comment]
@glenn-jocher Well, that should be my misunderstanding

**Comment by glenn-jocher** [comment]
@UNeedCryDear yes these are 3 anchors times 85 values (4 box coordinates, 1 objectness, 80 classes), at each of 3 output strides (8, 16, 32) for small, medium, large objects.

**Comment by besmaguesmi** [comment]
Hi ! What I understood from your discussion is that training a model with only one channel or 3 channels has no impact on model speed and inference! right?

**Comment by glenn-jocher** [comment]
@besmaGuesmi yes correct, input channel count has little effect on the model. You can create models with different input channels like this and compare stats and speeds:
```python
import torch

for ch in 1, 3, 4, 10:
    model = torch.hub.load('ultralytics/yolov5', 'yolov5s', channels=ch)
    results = model(np.array((640, 640, ch)))
    results.print()
```

EDIT: Please git pull or git clone again to update your code as #5542 and #5543 fixed a bug in channel count adjustment with hub models. Above example works correctly with #5542 and #5543.

**Comment by spacewalk01** [comment]
how about single channel onnx model? I trained a model on gray scale images. I would like to export it to onnx with a single channel

**Comment by UNeedCryDear** [comment]
@spacewalk01 
https://github.com/ultralytics/yolov5/blob/2f1eb21ad6c0f715f38200c31e6e01a92c5acb25/export.py#L504
change it to
```
im = torch.zeros(batch_size, 1, *imgsz).to(device)
```
and try again:
python detect.py --weights yours_best.pt --imgsz [640,640] --include onnx
