### ISSUE TITLE
The training results are not stable

### ISSUE THREAD

**Issue by dsp6414** [ultralytics/yolov5#261]
dataset: yymnist
lr: 1e-3
result.txt
      0/99     3.01G   0.07864    0.0821   0.07286    0.2336        60       416   0.08553    0.3062    0.0858    0.0201   0.06349    0.2033   0.06995
      1/99     6.69G     0.049   0.06985   0.06808    0.1869        62       416    0.1096    0.2921   0.08863   0.03298   0.07557    0.2093   0.06907
      2/99     6.69G   0.04288   0.06557   0.06033    0.1688        55       416   0.05486    0.2628    0.0324   0.00991   0.07593    0.2529    0.1051
      3/99     6.69G   0.03922   0.06084   0.04944    0.1495        60       416    0.3488    0.5143    0.3169    0.1595   0.06411    0.2695   0.07349
      4/99     6.69G   0.03368   0.05615   0.03865    0.1285        54       416    0.3895    0.9175    0.7436    0.5165   0.02482    0.0489   0.03604
      5/99     6.69G   0.03207   0.05382   0.03021    0.1161        49       416    0.5043    0.3722    0.3107    0.1286   0.06845    0.1317   0.08807
      6/99     6.69G   0.03003   0.05173    0.0265    0.1083        51       416    0.4123    0.3503    0.2806    0.1225   0.07423    0.1311   0.05993
      7/99     6.69G   0.02779   0.05013    0.0232    0.1011        51       416    0.3954    0.8019    0.6744    0.3859   0.04543    0.1612   0.03468
      8/99     6.69G    0.0268   0.04891   0.02143   0.09715        52       416    0.3465    0.6893    0.5904    0.3243   0.04833    0.1931   0.05176
      9/99     6.69G   0.02656    0.0483   0.01898   0.09384        66       416    0.3302    0.6536    0.5028    0.2616    0.0635    0.2315   0.04907
     10/99     6.69G   0.02499   0.04729    0.0171   0.08938        51       416    0.7103    0.9623     0.955    0.7088   0.01875   0.03313   0.01078
     11/99     6.69G   0.02427   0.04623   0.01628   0.08677        58       416    0.4626    0.7631     0.685    0.3502   0.05259    0.1486   0.03942
     12/99     6.69G    0.0233   0.04485   0.01527   0.08342        49       416      0.53    0.4154    0.3389    0.1671   0.07346    0.1265     0.103
     13/99     6.69G   0.02238   0.04383   0.01449    0.0807        37       416     0.419    0.7873    0.6896    0.3935   0.05324    0.2013    0.0373
     14/99     6.69G   0.02238   0.04402   0.01389   0.08028        54       416    0.4879     0.934    0.9051    0.5224   0.03415    0.1136    0.0134
     15/99     6.69G   0.02188   0.04352   0.01344   0.07884        64       416    0.7094    0.9536    0.9549    0.7507   0.01633    0.0333    0.0106
     16/99     6.69G   0.02108   0.04277   0.01289   0.07674        62       416     0.511    0.9398    0.9147    0.7319   0.01673   0.08835   0.01377
     17/99     6.69G   0.02105   0.04253   0.01277   0.07634        38       416     0.499    0.6729    0.5901    0.3052    0.0577    0.1984   0.08442
     18/99     6.69G    0.0204   0.04144   0.01222   0.07406        57       416    0.5139    0.5715    0.5222    0.2482   0.06306    0.1724    0.0593
     19/99     6.69G   0.01971   0.04172   0.01183   0.07327        54       416     0.527     0.941    0.9243    0.7032   0.02042    0.1135   0.01226
     20/99     6.69G   0.01967    0.0413   0.01151   0.07248        56       416    0.2191     0.559    0.3858    0.1883   0.06307    0.2275   0.04027
     21/99     6.69G   0.01891   0.03996   0.01137   0.07024        52       416    0.8255    0.9644    0.9666    0.8016   0.01417   0.02902  0.008499
     22/99     6.69G   0.01897   0.04017   0.01124   0.07037        59       416    0.6702    0.9102    0.9285    0.7004    0.0187   0.04044   0.01453
     23/99     6.69G   0.01854    0.0397   0.01097   0.06921        56       416    0.4508    0.6977    0.6423    0.2796   0.05492    0.1299     0.038
     24/99     6.69G   0.01829   0.03975   0.01076    0.0688        64       416    0.5199    0.8144    0.7459    0.3888   0.04853    0.1976   0.03056
     25/99     6.69G   0.01804   0.03954   0.01055   0.06812        50       416    0.3024    0.4892    0.3006    0.1243   0.06697    0.3032   0.06301
     26/99     6.69G   0.01741   0.03864   0.01038   0.06644        57       416    0.8843    0.9706      0.98    0.8803  0.009927   0.02439  0.005913
     27/99     6.69G   0.01758   0.03868   0.01021   0.06646        58       416    0.3545    0.8312    0.7177    0.3932   0.04677    0.2429   0.02787
     28/99     6.69G   0.01726    0.0379    0.0101   0.06526        60       416    0.4823    0.7384     0.647    0.3365   0.05474    0.2178   0.04323
     29/99     6.69G   0.01705     0.038   0.01028   0.06534        55       416    0.2346    0.6263    0.4359     0.193   0.06621     0.282   0.02653
     30/99     6.69G    0.0169   0.03798  0.009682   0.06457        59       416    0.2704    0.6066    0.4343    0.2041   0.06469    0.2441   0.03393
     31/99     6.69G   0.01654    0.0372  0.009838   0.06358        57       416    0.8099    0.9648    0.9715    0.8239   0.01316   0.02817  0.006629
     32/99     6.69G   0.01622   0.03711  0.009374   0.06271        57       416    0.6936    0.9001    0.9152    0.6321    0.0247   0.04902   0.01339
     33/99     6.69G   0.01584    0.0363  0.009326   0.06147        64       416    0.4162    0.9569    0.9425    0.7539   0.01761     0.109  0.007061
     34/99     6.69G   0.01581   0.03593  0.009147   0.06089        62       416    0.9006     0.975    0.9816    0.9037  0.008501   0.02101  0.004676
     35/99     6.69G   0.01547   0.03596  0.009057    0.0605        58       416    0.5574    0.8043    0.8108    0.5266   0.03426    0.2288   0.03186
     36/99     6.69G   0.01516   0.03544   0.00918   0.05978        56       416    0.6486    0.8195    0.8406    0.5546   0.03228    0.1199   0.03043
     37/99     3.02G   0.01742   0.03845  0.009567   0.06544        60       416   0.01857   0.08993  0.005214  0.001877   0.07651    0.1799    0.1412
     38/99     3.82G   0.01527    0.0356  0.009238   0.06011        62       416    0.6367    0.9425    0.9225    0.5741   0.03128   0.06766  0.008284
     39/99     3.82G   0.01473   0.03483  0.008991   0.05855        55       416    0.6797    0.9189    0.9275    0.6748   0.02125   0.04927   0.01226
     40/99     3.83G   0.01461   0.03454  0.008525   0.05767        60       416    0.9013    0.9752    0.9843    0.8963  0.009553   0.02216  0.004537
     41/99     3.83G   0.01443   0.03434   0.00859   0.05736        54       416    0.8801    0.9687    0.9787    0.8706   0.01076   0.02432  0.006079
     42/99     3.83G    0.0142   0.03386  0.008299   0.05637        49       416     0.548    0.7896    0.7695    0.3685   0.04809    0.1272   0.02462
     43/99     3.83G   0.01419   0.03404  0.008545   0.05677        51       416    0.6806    0.7885    0.8111    0.5997   0.03066    0.1248   0.04519
     44/99     3.83G   0.01389   0.03375  0.008111   0.05576        51       416    0.7672    0.9494    0.9617    0.7486   0.01749   0.04024  0.009536
     45/99     3.83G   0.01414   0.03388  0.008267   0.05629        52       416    0.5342    0.9228    0.9258    0.7413    0.0184   0.07746   0.01033
     46/99     3.83G   0.01363    0.0333  0.008062   0.05499        66       416    0.6349    0.8082    0.8193    0.6022   0.02983    0.1388   0.04218
     47/99     3.83G   0.01345   0.03328  0.007866   0.05459        51       416    0.8883    0.9793    0.9829    0.8959  0.009076   0.02168  0.004668
     48/99     3.83G   0.01345   0.03324  0.007774   0.05447        58       416    0.6792    0.9344    0.9501    0.7748   0.01841   0.09861   0.01186
     49/99     3.83G   0.01332   0.03249  0.007748   0.05356        49       416    0.9073    0.9748    0.9816    0.8001   0.01519   0.03209  0.003917
     50/99     3.83G    0.0129   0.03191  0.007679   0.05249        37       416    0.9136    0.9787    0.9862    0.9207  0.007877   0.01956  0.004148
     51/99     3.83G   0.01295   0.03231  0.007693   0.05296        54       416     0.902    0.9803    0.9844    0.8873  0.009826   0.02283  0.004171
     52/99     3.83G   0.01297   0.03227  0.007707   0.05295        64       416    0.5403    0.8925    0.8879     0.669   0.02113    0.1072  0.009772
     53/99     3.83G   0.01257   0.03173  0.007464   0.05177        62       416    0.8523    0.9673    0.9749    0.7738   0.01571   0.03451  0.006076
     54/99     3.83G   0.01263   0.03214  0.007666   0.05244        38       416    0.3622    0.7611    0.6365    0.3101   0.05535    0.2141   0.01619
     55/99     3.83G    0.0125   0.03131  0.007353   0.05116        57       416     0.763    0.9234    0.9482    0.7929   0.01421   0.05309   0.01258
     56/99     3.83G   0.01233    0.0316  0.007199   0.05113        54       416    0.6408    0.9369    0.9459    0.8101   0.01322   0.05471   0.01138
     57/99     3.02G   0.01732   0.03749  0.008323   0.06313        60       416    0.6647    0.8767    0.8808    0.6306   0.02698   0.08666    0.0142
     58/99     3.82G    0.0119   0.03085  0.007486   0.05023        62       416    0.7238    0.8315    0.8453     0.583   0.02877    0.0965   0.03996
     59/99     3.82G   0.01178   0.03027  0.007151   0.04919        55       416    0.7186    0.9567    0.9689    0.8079   0.01473   0.04084  0.007812
     60/99     3.82G    0.0116   0.03007  0.006779   0.04845        60       416    0.7128    0.8201    0.8498      0.51   0.03634    0.1217   0.04516
     61/99     3.82G   0.01154   0.02991  0.006702   0.04815        54       416    0.7843    0.9747    0.9781    0.8038   0.01668   0.05242  0.004793
     62/99     3.82G   0.01132   0.02937  0.006522   0.04721        49       416    0.6329    0.9108    0.9174    0.7388   0.01827    0.1003   0.01424
     63/99     3.82G   0.01133   0.02963  0.006728   0.04769        51       416    0.9017    0.9797    0.9869    0.8974  0.009246   0.02405  0.003467
     64/99     3.83G   0.01132   0.02959  0.006395   0.04731        51       416    0.6779    0.9433    0.9534    0.7414   0.01819   0.07115  0.009313
     65/99     3.83G   0.01122    0.0294  0.006502   0.04713        52       416      0.85    0.9758    0.9819    0.8833  0.009626   0.02698    0.0045
     66/99     3.83G   0.01101    0.0291  0.006361   0.04648        66       416    0.7586    0.9785    0.9837    0.9035  0.008521   0.03112  0.003966
     67/99     3.83G    0.0109   0.02898  0.006212   0.04608        51       416    0.7012    0.9319    0.9453    0.7996   0.01304   0.03116  0.009445
     68/99     3.83G   0.01085   0.02884   0.00628   0.04597        58       416    0.9393    0.9842    0.9894    0.9231  0.007626   0.01966  0.002688
     69/99     3.83G   0.01068   0.02828  0.006194   0.04515        49       416    0.9006     0.984     0.988    0.9195  0.007639   0.01916  0.002697
     70/99     3.83G   0.01059   0.02798  0.006152   0.04473        37       416    0.6394    0.9707    0.9459     0.654   0.02858    0.1035  0.003535
     71/99     3.83G   0.01057   0.02831  0.006078   0.04496        54       416    0.9023    0.9831    0.9857    0.9185  0.007619   0.02137  0.002863
     72/99     3.02G   0.01767   0.03758  0.007388   0.06264        60       416     0.406    0.3079    0.2836    0.1372   0.07754    0.1527   0.08419
     73/99     3.82G   0.01095   0.02909  0.006713   0.04675        62       416    0.8053    0.9684    0.9775    0.8866  0.009877   0.02662  0.005933
     74/99     3.82G   0.01048   0.02793  0.006224   0.04464        55       416      0.93    0.9862    0.9897    0.8956  0.009114   0.02136  0.002344
     75/99     3.82G   0.01022    0.0275   0.00588    0.0436        60       416    0.9358     0.984    0.9895    0.9101  0.008222   0.02048  0.002819
     76/99     3.82G   0.01022    0.0274  0.005781    0.0434        54       416    0.6003    0.9511    0.9392    0.6456   0.02751    0.1406  0.008165
     77/99     3.82G   0.01011   0.02701  0.005566   0.04269        49       416    0.6009    0.8919    0.9083    0.6998   0.02163    0.1125   0.01591

**Comment by dsp6414** [comment]
detect result: epoch 75
![image](https://user-images.githubusercontent.com/22781941/86299848-d7513980-bc33-11ea-9c76-1c460ac91333.png)

**Comment by glenn-jocher** [comment]
@dsp6414 first of all, do not use a bug label for questions.

**Comment by dsp6414** [comment]
the label is right, below is gt annotation
![image](https://user-images.githubusercontent.com/22781941/86300498-94906100-bc35-11ea-8129-35bdbe9a5a18.png)

**Comment by glenn-jocher** [comment]
No, the label is not correct, there is no bug.

**Comment by dsp6414** [comment]
epoch: 77/99 3.82G 0.01011 0.02701 0.005566 0.04269 49 416 0.6009 0.8919 0.9083 0.6998 0.02163 0.1125 0.01591
epoch: 72/99 3.02G 0.01767 0.03758 0.007388 0.06264 60 416 0.406 0.3079 0.2836 0.1372 0.07754 0.1527 0.08419
