### ISSUE TITLE
torch.hub.load -- results.print()

### ISSUE THREAD

**Issue by yupopa** [ultralytics/yolov5#2610]
## ❔Question
I want to print my result on streamlit webapp but ı cannot print result.print() result as a string or int. How can ı print these result of function can you help me
when ı want to print it says none. I tried this st.write(model.results.print)

**Comment by glenn-jocher** [comment]
@yupopa you can do results.print() to display a text summary of your results, and also results are saved in various formats that you can use to customize your own responses with:

```
results.xyxy
results.xywh 
etc.
```

All available results attributes are shown here:
https://github.com/ultralytics/yolov5/blob/8f6e447729e34a46fdbe9552fcfac705b82deac5/models/common.py#L242-L252
