### ISSUE TITLE
What is the upper limit of YOLOv5 detection

### ISSUE THREAD

**Issue by liziang297** [ultralytics/yolov5#2612]
## ❔Question
I want to know how many targets can yolov5 detcet in the same time.

**Comment by glenn-jocher** [comment]
@liziang297 NMS settings introduce various parameters you may want to review, such as max input and output instance counts from NMS (currently 30000 and 300):
https://github.com/ultralytics/yolov5/blob/0ff5aeca6152f25b7239ff3ca72b50a56a86390b/utils/general.py#L426-L434

**Comment by liziang297** [comment]
> @liziang297 NMS settings introduce various parameters you may want to review, such as max input and output instance counts from NMS (currently 30000 and 300):
> https://github.com/ultralytics/yolov5/blob/0ff5aeca6152f25b7239ff3ca72b50a56a86390b/utils/general.py#L426-L434

Thank you very very much. You have solved my problems.^_^

**Comment by glenn-jocher** [comment]
@liziang297 I think a few users have bumped into these limits before, so we were considering raising the max_det from 300 to 1000, or perhaps tying it to use case (with higher limits for detect.py/hubconf.py than test.py).

**Comment by glenn-jocher** [comment]
TODO: flexible NMS limits per use case: 1000 for detect.py/hubconf.py, 300 for test.py.

I think this makes sense as extra detections from detect.py/hubconf.py at default settings are likely 'real' objects, whereas test.py at default settings will routinely produce many thousands of FPs at the far right side of the mAP curve.

**Comment by liziang297** [comment]
Ahhh!Thank you very much for your kind help！And I hope to be like you one day！

**Comment by glenn-jocher** [comment]
Removed TODO as upper detection limit for inference is now raised to default 1000 instances per image in https://github.com/ultralytics/yolov5/pull/3215
