### ISSUE TITLE
Features map

### ISSUE THREAD

**Issue by GiuliaCiaramella** [ultralytics/yolov5#2613]
## ❔Question

is there a feature map in yolov5 whose output is independent on image size?

## Additional context
Hello :)
I am interested in extracting the feature map from last layer in the head of the network, in particular, one of the three that goes to feed the Detect() layer. I want this feature map to produce a feature vector representing the input image. The problem I am facing, is that this vector depends on the input image size, and since my goal si to compare images starting from their feature vectors, I can't accomplish my goal if the two images have different sizes.

For now, in order to make things work, I am using VGG16() neural network to process the images and take the feature vector in the last layer before classification, which has always a lenght of 4096, since it depends on the network layer and not on the input image size. 

However, since I am already using yolov5 for detection, that would be much more efficient extract the feature vector from yolov5 instead of reprocessing the image in another NN. 

So my question is: is there a feature map in yolov5 whose output is independent on image size?
I hope that this is clear.

**Comment by zonguu** [comment]
As I concered, the true length of vector  is (number of class + 5). The size of input influences the the number of  vector , for example, 20^2 + 40^2 + 80^2.  You can compare them with the given position , layers and anchors.

**Comment by GiuliaCiaramella** [comment]
@zonguu hey, thanks for the answer. 
I think I don't complete understand it. What are those numbers that you reported? how should I take them? 

What I am sure by now, is that the smallest feature map before the detect layer has size=  [1,3,8,13,9] for an image size of 416*256.  1 and 3 are always there (I think they represent 1=batch, 3 like channels of colors, but not sure), and 9 =4classes in my model+5. 
But the lenght in third and fourth position (number 8 and 13) change with image size.

**Comment by glenn-jocher** [comment]
@GiuliaCiaramella you can always use a nn.AdaptiveAvgPool2d() layer to average the spatial dimensions away, no matter what size they are. Most classification models like VGG do this, which is why their output vector is unaffected by image size. We have a Classify() module that does this as well here that you can use an example of how to get started (i.e. and if you want you can also apply it to each of the 3 Detect() layer inputs to get equal-size feature vectors.)

https://github.com/ultralytics/yolov5/blob/005d7a8c54a39d89bf2b9dc03fba82a489cd0628/models/common.py#L305-L315

**Comment by GiuliaCiaramella** [comment]
@glenn-jocher  Amazing! Thank you, I will focus on it :)

**Comment by kimngoc99** [comment]
@GiuliaCiaramella 
Hello, you have solved the above problem. And you can help can I convert feature map to feature vector. I can't do that

**Comment by glenn-jocher** [comment]
@GiuliaCiaramella good news 😃! Feature map visualization was added ✅ in PR #3804 by @Zigars today. This allows for visualizing feature maps from any part of the model from any function (i.e. detect.py, train.py, test.py). Feature maps are saved as *.png files in runs/features/exp directory. To turn on feature visualization set `feature_vis=True` in the model forward method and define the layer you want to visualize (default is SPP layer).

https://github.com/ultralytics/yolov5/blob/20d45aa4f18d7df7148fc6dd69a9c0607003f004/models/yolo.py#L158-L160

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

![layer_8_SPP_features](https://user-images.githubusercontent.com/26833433/123628234-27e17f80-d813-11eb-8d72-5d5560cd9ee4.png)
