### ISSUE TITLE
'LoadImages' path handling appears to be broken

### ISSUE THREAD

**Issue by maxupp** [ultralytics/yolov5#2618]
## 🐛 Bug
Currently instantiating a LoadImages instance fails because the computation of the absolute path results in a faulty path.
![image](https://user-images.githubusercontent.com/5763229/112641646-d8219f80-8e42-11eb-85a5-6bbeaf4e2846.png)

I'm on the current master.

## To Reproduce (REQUIRED)
Try to load any filepath.

dest = r'E:\Datasets\mavic_material\detected.mp4'

# build dataset from source
dataset = LoadImages(source, img_size=detector.imgsz, stride=detector.stride)

Output:
```
  File "../yolov5\utils\datasets.py", line 132, in __init__
    raise Exception(f'ERROR: {p} does not exist')
Exception: ERROR: E:\Repos\snakefly\droppings\"E:\Datasets\mavic_material\videos\DJI_0370.MP4" does not exist
```

## Expected behavior
The absolute path should be the correct filepath.

**Comment by maxupp** [comment]
My mistake, had an extra pair of quotes from Windows' beloved "copy as path" function.

**Comment by glenn-jocher** [comment]
@maxupp great, glad everything is working!
