### ISSUE TITLE
incompatibility with latest matplotlib

### ISSUE THREAD

**Issue by vincentkieboom** [ultralytics/yolov5#2619]
Latest version of matplotlib is incompatible with latest yolov5 version. 
matplotlib 3.2.2 is compatible. Please update requirements.txt
Great work btw!

**Comment by glenn-jocher** [comment]
@vincentkieboom hi thanks for the notice! What incompatibilities were you seeing? I trained correctly with all plots looking good in Colab after installing matplotlib 3.4.0 here first (most recent version): https://pypi.org/project/matplotlib/

<img width="2155" alt="Screenshot 2021-03-26 at 20 54 30" src="https://user-images.githubusercontent.com/26833433/112685943-8b0af100-8e75-11eb-95a7-e3833ed4e373.png">

**Comment by vincentkieboom** [comment]
.I get an AttributeError: module 'sip' has no attribute 'setapi'. Indeed with 3.4.0 version.

**Comment by glenn-jocher** [comment]
@vincentkieboom If you believe you have a reproducible issue, we suggest you close this issue and raise a new one using the 🐛 **Bug Report template**, providing screenshots and a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. Thank you!

Alternatively our environment recommendations our below:

Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below. 


## Requirements

**Python 3.8** or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including **`torch>=1.7`**. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by glenn-jocher** [comment]
@vincentkieboom as an extra check I reviewed the CI checks (run every 24 hours and on every commit on all 3 major OSs), and they are all green with matplotlib 3.4.0 as of 11 hours ago.
https://github.com/ultralytics/yolov5/runs/2206102226?check_suite_focus=true

<img width="1320" alt="Screenshot 2021-03-27 at 12 28 34" src="https://user-images.githubusercontent.com/26833433/112719207-057c5500-8ef8-11eb-9633-75ba829aebb1.png">
