### ISSUE TITLE
How to train float32 weights instead of float16?

### ISSUE THREAD

**Issue by Zacchaeus00** [ultralytics/yolov5#262]
Hi, this repo is great. However, I found the default trained weights are in torch.cuda.HalfTensor (which probably is **float16**). I would like to output something in **float32.** How can I implement this? Thank you in advance!

**Comment by glenn-jocher** [comment]
@Zacchaeus14 `model.float()`

**Comment by yxNONG** [comment]
@Zacchaeus14 
i think the training is on float32 by default, but it test in float16.
if you want to test in float32, set `half = False ` all the time in test.py

**Comment by Zacchaeus00** [comment]
thx!
