### ISSUE TITLE
The detected object's bounding box is larger than object size 

### ISSUE THREAD

**Issue by rafiqul713** [ultralytics/yolov5#2624]
When I capture an image from the webcam (source = 0 ) and feed (runs inference) it to the pre-trained model (YOLOv5s) the size of the bounding is  2 times or 3 times larger than the object size.

**Comment by glenn-jocher** [comment]
@rafiqul713 if the bounding box is larger than the object it's possible the model simply is producing poor inference results on your images, i.e. poor generalization. 

If you suspect a bug please close this issue and raise a new one using the 🐛 **Bug Report template**, providing screenshots and a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. Thank you!
