### ISSUE TITLE
How do I use my model?

### ISSUE THREAD

**Issue by Pro100rus32** [ultralytics/yolov5#2626]
## ❔Question

How can I use my own model?
I have some code:

```
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Images
dir = 'https://github.com/ultralytics/yolov5/raw/master/data/images/'
imgs = [dir + f for f in ('zidane.jpg', 'bus.jpg')]  # batch of images

# Inference
results = model(imgs)
results.print()  # or .show(), .save()
```

I want to do something like this, but it doesn't work:

```
import torch

# Model
model = torch.load('last.pt')
# Images
imgs = 'test.png'  # batch of images

# Inference
results = model(imgs)
results.print()  # or .show(), .save()
```

**Comment by glenn-jocher** [comment]
@Pro100rus32 see YOLOv5 PyTorch Hub Tutorial for information on loading custom models:

## Custom Models
This example loads a custom 20-class [VOC](https://github.com/ultralytics/yolov5/blob/master/data/voc.yaml)-trained YOLOv5s model `'best.pt'` with PyTorch Hub.
```python
model = torch.hub.load('ultralytics/yolov5', 'custom', path_or_model='best.pt')  # custom model
```


## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [ONNX and TorchScript Export](https://docs.ultralytics.com/yolov5/tutorials/model_export)
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by Pro100rus32** [comment]
Thanks, my solution was this code:


```
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'custom', path_or_model='last.pt')

# Images
imgs = 'test.png'  # batch of images

# Inference
results = model(imgs)
results.print()  # or .show(), .save()
```

**Comment by glenn-jocher** [comment]
@Pro100rus32 yes that should work well!

**Comment by SzaremehrjardiMT** [comment]
Hey, I'm trying to do the same thing but it says "custom() got an unexpected keyword argument 'path_or_model'".

++Edit: I used "model = torch.hub.load('ultralytics/yolov5', 'custom', 'yolov5/runs/train/exp/weights/best.pt' ,force_reload=True, trust_repo=True)" and it works!

**Comment by glenn-jocher** [comment]
@SzaremehrjardiMT Great to hear that it works for you! If you have any more questions or need further assistance, feel free to ask.
