### ISSUE TITLE
Run Custom object detection in a defined area(region of interest)

### ISSUE THREAD

**Issue by shiv-acharii** [ultralytics/yolov5#2628]
I have built a Custom Human detection model, and I want to run this in a defined region of interest.

Below is the sample results, which I am trying to achieve, I want to define an area marked in Redline. and humans should be detected only in that region.
people walking outside the defined region (safe zone- footpath) should not be detected.

![image](https://user-images.githubusercontent.com/13836633/112743247-340b3600-8fb3-11eb-9426-6b1c46bb767c.png)

**any suggestion or changes in the scripts that might help me??**

**Comment by glenn-jocher** [comment]
@shivprasad94 filter your detections by location.

https://stackoverflow.com/questions/36399381/whats-the-fastest-way-of-checking-if-a-point-is-inside-a-polygon-in-python

**Comment by shiv-acharii** [comment]
Okay, so here is the function which return me whether a point is inside the polygon or not 

```
# Ray tracing
def ray_tracing_method(x,y,poly):

    n = len(poly)
    inside = False

    p1x,p1y = poly[0]
    for i in range(n+1):
        p2x,p2y = poly[i % n]
        if y > min(p1y,p2y):
            if y <= max(p1y,p2y):
                if x <= max(p1x,p2x):
                    if p1y != p2y:
                        xints = (y-p1y)*(p2x-p1x)/(p2y-p1y)+p1x
                    if p1x == p2x or x <= xints:
                        inside = not inside
        p1x,p1y = p2x,p2y

    return inside

x1,y1=1, 0.5
poly1=[(0, 0), (0, 1), (1, 1), (1, 0)]
ray_tracing_method(x1,y1,poly1)
```

**below code will help me in getting 4 coordinates (x,y,w,h) of the bounding box**

```
for k in range(len(det)):
       x,y,w,h=int(xyxy[0]), int(xyxy[1]), int(xyxy[2] - xyxy[0]), int(xyxy[3] - xyxy[1])                   
       img_ = im0.astype(np.uint8)
       crop_img=img_[y:y+ h, x:x + w] 
```
**only x and y value is enough? what about w,h?**

how multiple bounding box can be handle here?

i feel this idea might detect all boxes but my requirement should run inference only in defined region? any rules/condition can be applied in   utils/ plots.py file?

**Comment by glenn-jocher** [comment]
@shivprasad94 I'm not sure exactly what your question is, but I'm assuming for customized code the requirement is on you to develop it and handle the details. You can load YOLOv5 PyTorch Hub models right into a python environment for a fully customizable solution:

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Images
dir = 'https://github.com/ultralytics/yolov5/raw/master/data/images/'
imgs = [dir + f for f in ('zidane.jpg', 'bus.jpg')]  # batch of images

# Inference
results = model(imgs)
results.print()  # or .show(), .save()
```

**Comment by shiv-acharii** [comment]
coordinates of my bounding boxes (tensor values) printed
```
[tensor(299., device='cuda:0'), tensor(272., device='cuda:0'), tensor(327., device='cuda:0'), tensor(350., device='cuda:0')]
[tensor(314., device='cuda:0'), tensor(170., device='cuda:0'), tensor(343., device='cuda:0'), tensor(242., device='cuda:0')]
[tensor(424., device='cuda:0'), tensor(182., device='cuda:0'), tensor(458., device='cuda:0'), tensor(264., device='cuda:0')]
480x640 3 persons, Done. (0.010s)
Results saved to runs\detect\exp11
Done. (139.907s)
```

here is my coordinate of my polygon
`x1,y1,x2,y2,x3,y3,x4,y4 =230,478,500,478,432,154,308,154`

I have defined my function as below

```
def CheckRange(_coords):
    print(_coords)
    x1,y1,x2,y2,x3,y3,x4,y4 =230,478,500,478,432,154,308,154
    # the coordinates of our window - left width ; top height ; right width ; bottom height
    if ((_coords[0] > x4 and _coords[0] < x3 and _coords[1] > y4 and _coords[1] < y3)
    or (_coords[2] > x3 and _coords[2] < x2 and _coords[1] > y3 and _coords[1] < y2)
    or (_coords[0] > x1 and _coords[0] < x2 and _coords[3] > y1 and _coords[3] > y2)
    or (_coords[0] > x1 and _coords[0] < x4 and _coords[3] > y1 and _coords[3] < y4)): return True

    return False
```

i was able to do it for square box with 2 conditions but still having issues for polygons? any corrections in conditions?
