### ISSUE TITLE
do worse when resize inference image 

### ISSUE THREAD

**Issue by helen12138** [ultralytics/yolov5#263]
Sorry, I trained in with the size of 608. When I inference with the same size with traininig, it does normal.
But I want to detect more small objects , I tried to resize the images of inference to 3200 and it did worse.
When I tried to resize to 3200 in yolov4, it has no effect . 
Does it not work in yolov5?
The space of device is not enough to resize train size so large , should I change the size of train images or change the size of calculated anchors?

**Comment by glenn-jocher** [comment]
@helen12138 you should always train under the conditions you will be deploying to or running inference at.

**Comment by helen12138** [comment]
@glenn-jocher Got it! Thank you
