### ISSUE TITLE
How to do inference on test image with exported ONNX model for verification?

### ISSUE THREAD

**Issue by chowkamlee81** [ultralytics/yolov5#2637]
## ❔Question

How to do inference on test image with exported ONNX model for verification?
@glenn-jocher 
Kindly help

**Comment by glenn-jocher** [comment]
@chowkamlee81 I haven't done this myself but I know others have so you might search the issues and discussions. In general I know you need onnx-runtime installed and some additional custom code. I'm sorry I can't be more helpful, hopefully we should have more of these deployed examples available in the future.

**Comment by Rusteam** [comment]
this is basically what i've done:

```
def to_numpy(tensor):
    return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()


def run_onnx(batch, sess, input_name, output_names):
    """ run a batch thru onnx session and return output """
    ort_in = {input_name: to_numpy(batch)}
    ort_out = sess.run(output_names, ort_in)
    return ort_out


def start_onnx(model_path):
    """ start onnx session and return it along with input name """
    ort_sess = onnxruntime.InferenceSession(model_path)
    input_name = ort_sess.get_inputs()[0].name
    output_names = [o.name for o in ort_sess.get_outputs()]
    return ort_sess, input_name, output_names


ort_sess,in_names,out_names = start_onnx(onnx_model_filepath)
output = run_onnx(batch, ort_sess, n_names,out_names )
```

you will need to install [onnxruntime](https://www.onnxruntime.ai/docs/get-started/install.html)
