### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by atalayismail** [ultralytics/yolov5#2646]
## ❔Question
Hello, i am trying use 4 yolov5m models. I have 4gb GPU Memory but while i was deploying models with pytorch hub it just uses 1.2 gb cuda memory is it possible the increase this allocated memory. Because FPS Drops due to using 4 sources and models.

**Comment by glenn-jocher** [comment]
@atalayismail of course. Using more CUDA memory is as simple as increasing batch size.

**Comment by atalayismail** [comment]
@glenn-jocher okay how can i increase batch size with using the pytorch hub i searched already but i couldnt find? can you help me ?

**Comment by glenn-jocher** [comment]
@atalayismail you add more images for inference...
```
results = model([img1, img2, more images here...])
```

**Comment by atalayismail** [comment]
Okay it's a good idea but i was talking about the using 4 different models and video source
for example;
while(True):
     
      ret, img1 = cap1.read() # for model 1
      results = model(img1)
      ret, img2 = cap2.read() # for model 2
      results2 = model2(img2)
      ret, img3= cap3.read() # for model 2
      results3 = model3(img3)
      ret, img4 = cap4.read() # for model 2
      results 4= model4(img4)

in my situation what should i do ?

**Comment by atalayismail** [comment]
Also i tried to your way still fps drops.

**Comment by glenn-jocher** [comment]
@atalayismail you can do whatever you want, that's the great thing about the flexibility the YOLOV5 Hub loading option offers.

You should experiment to find out what works best for you.
