### ISSUE TITLE
usage of --weights 'last.pt' instead of --resume....  Is using weights with last.pt an alternative to --resume. And if it is so then is it working correctly. Just a doubt

### ISSUE THREAD

**Issue by NitinDatta8** [ultralytics/yolov5#265]
## 🚀 Question

**Comment by glenn-jocher** [comment]
@NitinDatta8 I don't understand your question. The code for this is here. This is the only place --resume is used.
https://github.com/ultralytics/yolov5/blob/a03adb5ab8d4d027928d33bf7c316ea59efc2d96/train.py#L381

**Comment by NitinDatta8** [comment]
1. `!python train.py --img --batch  --epochs  --data --cfg --name --weights 'last.pt'`

2. `!python train.py --img --batch  --epochs  --data --cfg --name --weights 'pretrained_weights' --resume`

do the above two lines of code perform same task?
If the answer is yes, then does the line 1 work correctly... because in another issue you recommended against using resume...
Thank you for the quick reply @glenn-jocher

**Comment by NanoCode012** [comment]
I think you just do 
`!python train.py --img --batch --epochs --data --cfg --name --resume` without the weights.
The first is equivalent to the above.

I recalled him saying it's better to train in only one time and not use resume, that's why he didn't recommend.
