### ISSUE TITLE
Resume on CPU after Google Colab GPU limit reached

### ISSUE THREAD

**Issue by orphan2020** [ultralytics/yolov5#2650]
After having reached the Google Colab GPU runtime limit, I tried to resume on CPU. Unfortunately I got the error:

RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. 
If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

Would be nice to be able to resume on CPU if that's possible...

**Comment by glenn-jocher** [comment]
@orphan2020 the current resume assumes all settings are identical to the interrupted run when it starts resuming, no modifications are allowed, so this is likely why you are running into problems. I don't believe we've had feedback from users regarding resuming on different devices, so it doesn't appear to be a popular use case at the moment, so will not add a TODO for this.

There are two options for resuming interrupted runs:
```bash
python train.py --resume  # resume latest training
python train.py --resume path/to/last.pt  # specify resume checkpoint
```

If you started the training with a multi-GPU command then you must resume it with the same exact configuration (and vice versa). Multi-GPU resume commands are here, assuming you are using 8 GPUs:
```bash
python -m torch.distributed.launch --nproc_per_node 8 train.py --resume  # resume latest training
python -m torch.distributed.launch --nproc_per_node 8 train.py --resume path/to/last.pt  # specify resume checkpoint
```

Note that you may not change any settings when resuming, you must resume with the same exact settings (`--epochs`, `--batch`, `--data`, etc).

**Comment by orphan2020** [comment]
If I stop the training now, is the last.pt any different to the last.pt after having completed the training except for more epochs ?
In other words:
Why should I not always go for 100000 epochs and just stop the training as soon as the best.pt doesn't get better ?

**Comment by glenn-jocher** [comment]
@orphan2020 YOLOv5 training checkpoints should be 4X the size of final trained checkpoints, as they carry not just a FP16 model, but a FP16 [EMA](https://www.tensorflow.org/api_docs/python/tf/train/ExponentialMovingAverage) and an FP32 optimizer of the same size as the model (each model parameter has its own FP32 gradient saved within the optimizer). Final checkpoints contain only an FP16 model, with the EMA and optimizer both stripped after the final epoch of training:
https://github.com/ultralytics/yolov5/blob/75feeb797c4a9553f4274860c6c278f1fc628f60/train.py#L435-L439

The `strip_optimizer()` function updates the checkpoint dictionary value for `model`, replacing it with `ema`, and sets `ema` and `optimizer` keys to `None`, which will reduce the checkpoint size by 3/4.
https://github.com/ultralytics/yolov5/blob/75feeb797c4a9553f4274860c6c278f1fc628f60/utils/general.py#L495-L509

Final trained checkpoints after `strip_optimizer()` should match the README table sizes below.
<p align="center"><img width="700" alt="YOLOv5 Models" src="https://user-images.githubusercontent.com/26833433/103595982-ab986000-4eb1-11eb-8c57-4726261b0a88.png"></p>

To answer your other question, there is an LR scheduler in place that will ramp down the learning rate from an initial value to a final value based on the number of --epochs you have provided. If you set epochs to 1E6 your scheduler will not lower your learning rate anytime soon, and your results will be worse.
