### ISSUE TITLE
How did you select the Precision and Recall values from the PR curve?

### ISSUE THREAD

**Issue by zxsitu** [ultralytics/yolov5#2655]
## ❔Question
Hello author, how do you determine the "best" Precision and Recall values on the PR curve? Are there any criteria?
(e.g., determine the point on the curve that provides a good trade-off between Precision and Recall)

## Additional context
Because I've looked at a lot of other object detection programs and they will only use AP and AP50, which I know is what mAP and mAP50 means. And they plot a PR curve, and other than that they don't have Precision and Recall values everywhere.
But your program also calculates Precision and Recall values, how did you get the results? Thank you.

**Comment by glenn-jocher** [comment]
@ilem777 P and R values are logged and displayed at maximum F1 confidence. 

Full P, R, and F1 curves at all confidences are saved after test.py completes in runs/test/exp.
<img width="1236" alt="Screenshot 2021-03-30 at 01 07 51" src="https://user-images.githubusercontent.com/26833433/113033999-ea2c7680-9191-11eb-932e-1bcf534ec16e.png">

**Comment by glenn-jocher** [comment]
See https://github.com/ultralytics/yolov5/pull/2057

**Comment by zxsitu** [comment]
@glenn-jocher Thank you, I understand.
