### ISSUE TITLE
On the image resolution ratio and accuracy used for training and inference

### ISSUE THREAD

**Issue by leeyunhome** [ultralytics/yolov5#2660]
## ❔Question

The ratio of the original image used for training (4:3 or 16:9) and

If the proportions of the images used for inference are different, does it affect the accuracy a lot?

**Comment by glenn-jocher** [comment]
@leeyunhome aspect ratio of objects and images is never altered in YOLOv5, only scale.

**Comment by leeyunhome** [comment]
> @leeyunhome aspect ratio of objects and images is never altered in YOLOv5, only scale.

Hello,

If the original image is 800x600
If I specify train.py --img-size 640 like this
640x? in proportion to the original image? ?The size of the part is specified, right?

Thank you.

**Comment by glenn-jocher** [comment]
@leeyunhome --img 640 means that the long side of each image is resized to 640 while maintaining aspect ratio. Padding is applied to short side as necessary to comply with stride-multiple constraints.

**Comment by leeyunhome** [comment]
> @leeyunhome --img 640 means that the long side of each image is resized to 640 while maintaining aspect ratio. Padding is applied to short side as necessary to comply with stride-multiple constraints.

Thank you

**Comment by alicera** [comment]
@leeyunhome 
Hi,
If I want to train 800x600 image as input and the model input size is 800x600.
How can I set?

**Comment by glenn-jocher** [comment]
@alicera to train at 800 pixels image size the command is:
```
python train.py --img 800
```

**Comment by alicera** [comment]
I try the command
python train.py --img 800
But the input size is 800x800 for network, not 800x600

**Comment by glenn-jocher** [comment]
@alicera you can use the --rect argument for rectangular training:
```
python train.py --rect
```

**Comment by billalkuet07** [comment]
I have trained the model with 640*640 and used detect.py with 1080*1080 images. Does it affect the output performance? Thank you.

**Comment by glenn-jocher** [comment]
@billalkuet07 in general for best results train and detect at similar image sizes.

**Comment by YoungjaeDev** [comment]
@glenn-jocher 

Hello. Is there any way to train in various aspect_ratio? Sometimes there is an issue where the performance drops dramatically when the resolution of the inference image takes a different aspect ratio than when training. Or is it appropriate to use anchor free yolov8? thank you

**Comment by glenn-jocher** [comment]
Hello @youngjae-avikus, 

Yes, you can train YOLOv5 with various aspect ratios using the `--rect` flag. This will train the YOLOv5 model to detect objects on rectangular input images without resizing them. During inference, the model will detect objects on images in their original aspect ratios without any loss of information. 

Alternatively, you can use anchor-free detection methods like YOLOv8 that do not rely on predefined anchors. However, it should be noted that anchor-free methods may require longer training time and higher computational resources. 

Hope this helps. Let me know if you have more questions.

**Comment by dharakpatel** [comment]
let say we have train a custom model from yolov8 on low resolution images if i give that model to do inference on a high resolution image how the model will handle it in background and is there any information loss in the scaling process

**Comment by glenn-jocher** [comment]
@dharakpatel hello! When you give a high-resolution image to a model trained on low-resolution images, YOLO typically resizes the input image to match the model's input dimensions. This resize process may lead to information loss, especially if there's a significant difference in resolution. For better consistency, try training and inferring at similar resolutions, or use high-resolution images during training if you expect high-res images during inference. No special background handling other than resizing occurs. 🚀
