### ISSUE TITLE
question about pseudo annotations

### ISSUE THREAD

**Issue by Shengxiaolin** [ultralytics/yolov5#2661]
## ❔Question
hi ! here i have a dataset with annotation，but the initial annotations lost many objects，so i plan to use pretrained weights to generate pseudo label and i also want to use the exist annotations，should i need to distinguish this two part annotations（and how to distinguish？use iou？)or just adding the pseudo label to the exist annotations（will cause same(or very similar) boundingbox info in one label file）when i was training.

**Comment by glenn-jocher** [comment]
@Shengxiaolin to merge autolabels with existing labels pass the --save-hybrid flag to test.py when autolabelling. There will be no distinction in the saved labels.
```bash
python test.py --save-txt --save-hybrid
```
