### ISSUE TITLE
missing flask app for google app engine

### ISSUE THREAD

**Issue by robmarkcole** [ultralytics/yolov5#2662]
## 🚀 Feature
Some files related to deploying yolov5 on app engine were added in https://github.com/ultralytics/yolov5/pull/964 but still missing is the actual flask app which would comprise of a `main.py`. Additionally a README would be nice here. 

## Motivation
I assume once everything is in place it is a one line command to deploy the app, which would be neat

CC @Guilhen

**Comment by glenn-jocher** [comment]
@Guilhen in reference to your Google app engine PR https://github.com/ultralytics/yolov5/pull/964, would you be able to provide a minimum Flask app example as requested by @robmarkcole? I think this would comprise a main.py file with a short READEME.md. If possible this would help everyone use the app engine directory that you created initially. Thanks!

**Comment by robmarkcole** [comment]
I expect it will not be much more complicated than the example at https://pytorch.org/tutorials/intermediate/flask_rest_api_tutorial.html#integrating-the-model-in-our-api-server

**Comment by Guilhen** [comment]
ok got it, I have done this in the past. As @robmarkcole mentioned, creating the app is fairly straightforward. The tricky point could be the image encoding/decoding. You are right @robmarkcole you can deploy to the cloud from the terminal using the gcloud command. 
I'll put something together and create a PR.

**Comment by glenn-jocher** [comment]
@Guilhen thanks Guilhen! I think a tutorial/demo would really help people (me too!) get started with it more easily.

**Comment by robmarkcole** [comment]
Found an example app: https://github.com/jzhang533/yolov5-flask/blob/main/app.py

**Comment by glenn-jocher** [comment]
@robmarkcole do you think we should use https://github.com/jzhang533/yolov5-flask as a reference?

**Comment by robmarkcole** [comment]
@glenn-jocher I actually forked that and tidied it up a bit https://github.com/robmarkcole/yolov5-flask

In the process of getting yolov5-flask up and running I created a pair of related issues want to look at before proceeding with this issue:

- https://github.com/ultralytics/yolov5/issues/2702
- https://github.com/ultralytics/yolov5/issues/2703

**Comment by robmarkcole** [comment]
Both the two issues referenced above are now closed, so full steam ahead on this one :-)

**Comment by glenn-jocher** [comment]
@robmarkcole yeah thanks for spotting those issues! I think the hub models are quite improved now. 

Yes I think completing a Flask app with a README in the directory would be great, especially for non web-developers like me to understand this better. If we had a main.py that we just had to execute with `python main.py` for the demo to start that would be awesome.
