### ISSUE TITLE
Suggestion: Add number of training images to W&B logging

### ISSUE THREAD

**Issue by adrianholovaty** [ultralytics/yolov5#2665]
The subject line says it all. Within my W&B account it'd be great to be able to see, for each run, the number of training images that were used.

This would help me get a better sense of how performance is improved by particular dataset increases, and it would help differentiate between runs within W&B when looking at the "table" view. I've already been adding this data manually to the W&B run descriptions, but it'd be more reliable to automate it.

I'm happy to contribute a patch if you provide some quick guidance on where this code should live! :) If this data is already in there and I overlooked it, please let me know.

**Comment by glenn-jocher** [comment]
@adrianholovaty label statistics and dataset statistics are saved to labels.jpg, labels_correlogram.jpg and printed to screen prior to training, but are not hyperparameters or run settings, and so are not logged to W&B.

Dataset statistics may be better associated as artifact properties than run properties, but if you'd like you of course simply add them to `opt` or `hyp` dicts which are currently logged.
