### ISSUE TITLE
No bounding box with labels  obtained for the test images in the inference output folder 

### ISSUE THREAD

**Issue by joshnarani9** [ultralytics/yolov5#267]
after training the model on the blood cells dataset,I have printed testbatch image
![test](https://user-images.githubusercontent.com/48877296/86353601-22476d00-bc85-11ea-9ade-403d35b01460.JPG)

command for detecting 👍 
%cd /content/yolov5/
!python detect.py --source ../test/images --weights weights/last_yolov5s_results.pt --conf 0.4 

output:
import glob
from IPython.display import Image, display

for imageName in glob.glob('/content/yolov5/inference/output/*.jpg'): #assuming JPG
    display(Image(filename=imageName))
    print("\n")
![dis](https://user-images.githubusercontent.com/48877296/86353649-38552d80-bc85-11ea-9bbb-a207d37dd30b.JPG)

No bounding boxes for the test images after running the above code

**Comment by joshnarani9** [comment]
Please check I have edited the issue

**Comment by saifeddine001** [comment]
what is the solution for this bug!?

**Comment by Alx-AI** [comment]
Does anyone have a solution for this?

**Comment by joshnarani9** [comment]
I ran with very less number of epochs previously..so it did not show output ..After that I have ran with 100 epochs and can see the results with bounding box and labels

**Comment by KenaHemnani** [comment]
@joshnarani9  I am facing the same issue. I trained the model for 200 epochs still cannot see bounding box and labels. 
If you can suggest some solution??

**Comment by soohyoen** [comment]
> @joshnarani9 I am facing the same issue. I trained the model for 200 epochs still cannot see bounding box and labels. If you can suggest some solution??

I faced the same issue. Did you solve it?

**Comment by supratim1121992** [comment]
This is due to the --conf flag used in detection. Reducing it will increase the number of successful detections but might also result in False Positives.

**Comment by glenn-jocher** [comment]
@supratim1121992 ```python
This might be caused by the --conf flag used in the detection command. Try reducing the confidence threshold to potentially increase successful detections, but keep in mind that it might also result in more false positives.```

**Comment by Ace-Eternal** [comment]
> @supratim1121992 `python This might be caused by the --conf flag used in the detection command. Try reducing the confidence threshold to potentially increase successful detections, but keep in mind that it might also result in more false positives.`

Thank you, I reduce the confidence threshold and it works!

parser.add_argument('--conf-thres', type=float, default=0.10, help='object confidence threshold')
