### ISSUE TITLE
Label-smoothing on --resume training

### ISSUE THREAD

**Issue by gondimjoaom** [ultralytics/yolov5#2671]
## Additional context

I'm training a yolo model on google colab and I make a git clone every time I begin training again with --resume. But since --label-smoothing was added two days ago, I get an error that it isn't on the hyp[] list. I was able to pass by it by checking out to a commit behind it was added.

**Comment by glenn-jocher** [comment]
@gondimjoaom sorry buddy, you are right this may interrupt resumed runs. 

While I applaud you for staying up to date with the latest changes, in general it is not advisable to update your environment or training code mid-run, as this may result in errors (or silent errors). 

The proper update workflow would be to complete any trainings and then git pull or reclone.

**Comment by gondimjoaom** [comment]
I have no problems on checking out to the working commit. It's ok :)
