### ISSUE TITLE
Feature vector

### ISSUE THREAD

**Issue by kimngoc99** [ultralytics/yolov5#2675]
## ❔Question
How to get the image feature vector in the model ?
## Additional context
Hello,
I need to extract the avatar feature vector of the input image.
Currently, for everything to work well, I am using the VGG16 () neural network to process the image and get the feature vector in the final layer before sorting, which is always 4096 in length.
However, since I used yolov5 for detection, it would be much more efficient to extract the feature vector from yolov5.
So my question is: how can I get a feature vector from the yolov5 model, please help me.

**Comment by glenn-jocher** [comment]
@kimngoc99 you can convert an image or a feature grid into a feature vector with nn.AdaptiveAvgPool2d(). The Classify() module used in YOLOv5 classifier models is an example of this:
https://github.com/ultralytics/yolov5/blob/b8b862993d8e0a267f7d96eb94307f3f0f7dce51/models/common.py#L306-L316

**Comment by kimngoc99** [comment]
@glenn-jocher Thank you very much, I will try it
