### ISSUE TITLE
What are the other variants of released models?

### ISSUE THREAD

**Issue by chunchet-ng** [ultralytics/yolov5#2676]
## ❔Question
Hi there, I have noticed that there are several variants of the models being released this time. For instance, there are yolov5l6.pt, yolov5l7-s3.pt, yolov5m6.pt, yolov5s6.pt, and yolov5x6.pt. What are the main changes of these variants, and what does it mean by the additional "6" behind the model's name?

## Additional context
You can find them on this [page (release v4.0)](https://github.com/ultralytics/yolov5/releases). 

Thank you very much.

**Comment by kinoute** [comment]
More informations about these models can be found here: https://github.com/ultralytics/yolov5/issues/2110

**Comment by glenn-jocher** [comment]
@chunchet-ng models with a '6' suffix include a P6 output layer (P3, P4, P5, P6) and are trained at 1280. These generally achieve better mAP on COOC than their default counterparts, which include the normal 3 outputs P3, P4, P5 and are trained at 640. 

We are planning on a v5.0 release soon which details all of this better in the README.
