### ISSUE TITLE
How to combine two models: one from yolov3 and another from yolov5?

### ISSUE THREAD

**Issue by ifahim** [ultralytics/yolov5#2677]
## ❔Question

I have trained a model using Ultralytics yolov3 (#classes =1, yolov3_best.pt) and pretty satisfied with that. I have another model that I trained on Ultralytics  yolov5x (#classes =1, yolov5_best.pt). I  am planning to create one torchscript by merging these two models. 

Is there a way I can combine these two models trained on yolov3 and v5? Can anyone point to the example script that does this?

**Comment by glenn-jocher** [comment]
@ifahim if you have multiple models trained on the same classes, you can ensemble them for improved results by passing them to detect.py together:
```bash
python detect.py --weights model1.pt model2.pt model3.pt etc.
```

See Model Ensembling Tutorial for details:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [ONNX and TorchScript Export](https://docs.ultralytics.com/yolov5/tutorials/model_export)
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by ifahim** [comment]
The models are trained for two separate classes. yolov3 for person and yolov5 for small objects.

**Comment by glenn-jocher** [comment]
@ifahim oh, if models are trained on seperate classes then there's no automated way to combine their outputs, you can build a custom solution.

**Comment by whuyyc** [comment]
@glenn-jocher How about using knowledge distillation after ensembling multiple models?

**Comment by glenn-jocher** [comment]
@whuyyc could you explain a bit more about how your idea would work?

**Comment by whuyyc** [comment]
@glenn-jocher Although we can ensemble several models to get a better performance than any single model, it will increase computational cost in inference. So can we make a compression for ensembling model using Knowledge Distillation to get a similar performance in a model of smaller size? But I just find the distillation method from one large model(teacher model) to one small model(student model) as shown in this picture:![image](https://user-images.githubusercontent.com/52364175/113954152-e791e700-984b-11eb-85ef-190a62688f70.png) In other words, I do not know how to fuse several models to one model, or directly use KD from ensembling models.... Could you give me some thought or suggestion please?

**Comment by akashAD98** [comment]
In this kaggle competition they have combined different models using ensamble techniques.
have a look on 1st place solution approach.
[https://www.kaggle.com/c/vinbigdata-chest-xray-abnormalities-detection/discussion/229724](url)

it will be really grateful if anyone can provide script to combine different object detection models.thanks

**Comment by glenn-jocher** [comment]
@akashAD98 ensembling is automatically built into YOLOv5. See Model Ensembling tutorial to get started.

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [ONNX and TorchScript Export](https://docs.ultralytics.com/yolov5/tutorials/model_export)
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by glenn-jocher** [comment]
@whuyyc I'm not sure the graphic you have there applies, as it shows one trained model and one model undergoing training, whereas the ensembles are normally done with multiple fully trained models. You're free to experiment with different ensembling techniques to explore what might work best. There's even various other ensembling techniques displayed in the Ensemble() module, such as mean ensemble, max ensemble, etc, that can be applied to models with the same output shapes:

https://github.com/ultralytics/yolov5/blob/c03d590320ea875a9ce5288c077a9ce5c7a1c160/models/experimental.py#L98-L111
