### ISSUE TITLE
Why do Slice operate on inputs?

### ISSUE THREAD

**Issue by murdockhou** [ultralytics/yolov5#268]
Thanks for your work first. 

I convert yolov5s into onnx and show it in netron. I find the first thing that model to do is `Slice`. I just want to know why do this?

![image](https://user-images.githubusercontent.com/18358653/86356040-2e8bf400-bc9e-11ea-8123-e3a2d781dc6a.png)

And could anyone have tried to convet yolov5 into `TVM`? I tried but stopped on this `Slice` operation.

**Comment by yxNONG** [comment]
for downsampling without computation

**Comment by xingshuohan** [comment]
I also wonder why the output of 4 slice operations is totally same?

**Comment by zhiqwang** [comment]
Hi @murdockhou, I've converted yolov5 into TVM in my [repo](https://github.com/zhiqwang/yolov5-rt-stack), and [here](https://github.com/zhiqwang/yolov5-rt-stack/blob/master/notebooks/export-relay-inference-tvm.ipynb) is a jupyter notebook to show how it works, maybe you could check these.
