### ISSUE TITLE
https://github.com/microsoft/Swin-Transformer

### ISSUE THREAD

**Issue by lucasjinreal** [ultralytics/yolov5#2680]
How about try this tech?

**Comment by glenn-jocher** [comment]
"The code will be coming soon." they say.

**Comment by lucasjinreal** [comment]
Oh. yeah

**Comment by glenn-jocher** [comment]
@jinfagang good find though, their reported mAP is super high, so I'd be interested to see the code if/once it's released.

**Comment by zhangming8** [comment]
> @jinfagang good find though, their reported mAP is super high, so I'd be interested to see the code if/once it's released.

Hi, I find you have pushed "TransformerLayer". What's the result of it ?

**Comment by glenn-jocher** [comment]
@zhangming8 see https://github.com/ultralytics/yolov5/issues/2329 for experiments with Transformer layers. They seem to show promise, though they require more resources to train, especially CUDA memory.

**Comment by lucasjinreal** [comment]
@glenn-jocher Looked into the thread seems transformer is also appliceable. Does the speed get faster as well?

**Comment by sbbug** [comment]
GOOd

**Comment by jayyoung23** [comment]
Here it comes！
@glenn-jocher 
https://github.com/microsoft/Swin-Transformer
https://github.com/SwinTransformer/Swin-Transformer-Object-Detection

**Comment by Bobo-y** [comment]
I've used swin transformer as yolov5 backbone in [my repo](https://github.com/yl305237731/flexible-yolov5).

**Comment by glenn-jocher** [comment]
@yl305237731 that's very impressive! Did you see performance improvements with the swin transformers backbone?

**Comment by Bobo-y** [comment]
@glenn-jocher I just trained on local dataset for person detection, only trained  about 10 epochs. and the recall and accuracy were almost the same as using the original yolov5, so I turned it off. 😂
