### ISSUE TITLE
How to run the trained classifier for single image inference?

### ISSUE THREAD

**Issue by Dishant-P** [ultralytics/yolov5#2687]
## ❔Question
Hi, first of all thanks for this great work and also opening up the classifier branch. I wanted to ask you that after training the classifier through classifier.py, how can I run the weights for a single image inference? 

Thanks

**Comment by glenn-jocher** [comment]
@Dishant-P you should be able to pass a batch of any size (i.e. batch size 1 in your case) to the trained model. You can see examples of inference using `model(images)` in the training loop:
https://github.com/ultralytics/yolov5/blob/058d667dc953405f76e5c03b85cbd7c4eb70d128/classifier.py#L127-L130

For best results you should also make sure you apply the same transforms as the val dataloader uses:
https://github.com/ultralytics/yolov5/blob/058d667dc953405f76e5c03b85cbd7c4eb70d128/classifier.py#L54-L63

**Comment by Dishant-P** [comment]
Thanks. I was able to make it work.
