### ISSUE TITLE
Code runs on Colab notebook but doesnt work when run on laptop. It expects weights and doesnt take .pt file to be compatible.

### ISSUE THREAD

**Issue by shayanalibhatti** [ultralytics/yolov5#269]
The same code works fine for Colab notebook but doesnt work well when run on laptop. I am using Windows 10 machine, jupyter notebook, 6GB graphics card, all dependencies installed. I use this line for starting the training process. 

**%cd C:/Users/johnny/yolov5/
!python train.py --img 416 --batch 16 --epochs 2 --data data.yaml --cfg models/custom_yolov5s.yaml --weights '' --name yolov5s_results --nosave --cache**

All the paths are given appropriately still I get the Exception shown below. Please let me know how to resolve it ? I am using custom_yolov5.yaml file. I am training it on custom data with just one class of bounding box. I tried weights ='' and also tried to use the exported last_weights.pt file that I got from running same code on Colab notebook but it keeps stuck at this following Exception. 

**2020-07-02 01:27:58.258234: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   188  100   188    0     0    188      0  0:00:01 --:--:--  0:00:01   354
Traceback (most recent call last):
  File "train.py", line 394, in <module>
    train(hyp)
  File "train.py", line 110, in train
    google_utils.attempt_download(weights)
  File "C:\Users\johnny\yolov5\utils\google_utils.py", line 40, in attempt_download
    raise Exception(msg)
Exception: '' missing, try downloading from https://drive.google.com/drive/folders/1Drs_Aiu7xx6S-ix95f9kNsA6ueKRpN2J**

I have also tried giving path to yolov5.pt that I downloaded from the above mentioned link that the exception wants me to use, but no avail. I get the following exception when I give path to yolov5s.pt :

**The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 394, in <module>
    train(hyp)
  File "train.py", line 124, in train
    raise KeyError(s) from e
KeyError: "yolov5s.pt is not compatible with models/custom_yolov5s.yaml. This may be due to model differences or yolov5s.pt may be out of date. Please delete or update yolov5s.pt and try again, or use --weights '' to train from scatch."**

Any help is highly appreciated.

**Comment by glenn-jocher** [comment]
@shayanalibhatti your code or your model or both may be out of date (as the error message states. Suggest trying with a fresh git pull. You can also use one of our working environment below. I would say that windows in general is a poor environment for anything, and ML especially.

## Reproduce Our Environment

To access an up-to-date working environment (with all dependencies including CUDA/CUDNN, Python and PyTorch preinstalled), consider a:

- **GCP** Deep Learning VM with $300 free credit offer: See our [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Google Colab Notebook** with 12 hours of free GPU time. <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)

**Comment by shayanalibhatti** [comment]
Thanks for the response and the great work you did. I got the results via the notebook using Google Colab Pro. I will try fresh GIT pull for desktop version and see if it works. 

Have a nice day.
