### ISSUE TITLE
 How can I change the path to the repository folder?

### ISSUE THREAD

**Issue by Pro100rus32** [ultralytics/yolov5#2691]
## ❔Question
How can I change the path to the repository folder?
`Using cache found in C:\Users\Андрей/.cache\torch\hub\ultralytics_yolov5_master`

p.s. I am using `torch.hub.load()`

**Comment by glenn-jocher** [comment]
@Pro100rus32 PyTorch selects a default directory for Hub caching automatically, I'm not sure if this is user-modifiable. You should ask on the PyTorch forums:
https://discuss.pytorch.org/

**Comment by Pro100rus32** [comment]
`torch.hub.set_dir(DIR)`
