### ISSUE TITLE
ONNX cannot be exported

### ISSUE THREAD

**Issue by h-moses** [ultralytics/yolov5#2692]
## 🐛 Bug
When the yolov5l model is exported to onnx, the process exits.

## To Reproduce (REQUIRED)

Input:
```
"""Exports a YOLOv5 *.pt model to ONNX and TorchScript formats
Usage:
    $ export PYTHONPATH="$PWD" && python models/export.py --weights ./weights/yolov5s.pt --img 640 --batch 1
"""

from utils.torch_utils import select_device
from utils.general import set_logging, check_img_size
from utils.activations import Hardswish, SiLU
from models.experimental import attempt_load
import models
import torch.nn as nn
import torch
import argparse
import sys
import time

sys.path.append('./')  # to run '$ python *.py' files in subdirectories


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument(
        '--weights',
        type=str,
        default='weights/best.pt',
        help='weights path')  # from yolov5/models/
    parser.add_argument(
        '--img-size',
        nargs='+',
        type=int,
        default=[
            320,
            320],
        help='image size')  # height, width
    parser.add_argument('--batch-size', type=int, default=1, help='batch size')
    parser.add_argument(
        '--dynamic',
        action='store_true',
        help='dynamic ONNX axes')
    parser.add_argument(
        '--grid',
        action='store_true',
        help='export Detect() layer grid')
    parser.add_argument(
        '--device',
        default='cpu',
        help='cuda device, i.e. 0 or 0,1,2,3 or cpu')
    opt = parser.parse_args()
    opt.img_size *= 2 if len(opt.img_size) == 1 else 1  # expand
    print(opt)
    set_logging()
    t = time.time()

    # Load PyTorch model
    device = select_device(opt.device)
    model = attempt_load(opt.weights, map_location=device)  # load FP32 model
    labels = model.names

    # Checks
    gs = int(max(model.stride))  # grid size (max stride)
    # verify img_size are gs-multiples
    opt.img_size = [check_img_size(x, gs) for x in opt.img_size]

    # Input
    # image size(1,3,320,192) iDetection
    img = torch.zeros(opt.batch_size, 3, *opt.img_size).to(device)

    # Update model
    for k, m in model.named_modules():
        m._non_persistent_buffers_set = set()  # pytorch 1.6.0 compatibility
        if isinstance(
                m, models.common.Conv):  # assign export-friendly activations
            if isinstance(m.act, nn.Hardswish):
                m.act = Hardswish()
            elif isinstance(m.act, nn.SiLU):
                m.act = SiLU()
        # elif isinstance(m, models.yolo.Detect):
        #     m.forward = m.forward_export  # assign forward (optional)
    model.model[-1].export = True  # set Detect() layer grid export
    y = model(img)  # dry run

    # ONNX export
    try:
        import onnx

        print('\nStarting ONNX export with onnx %s...' % onnx.__version__)
        f = opt.weights.replace('.pt', '.onnx')  # filename
        torch.onnx.export(model, img, f, verbose=False, opset_version=11, input_names=['images'],
                          output_names=['output'])
        # torch.onnx.export(model, img, f, verbose=False, opset_version=12, input_names=['images'],
        #                   output_names=[
        #     'classes','boxes'] if y is None else ['output'],
        #     dynamic_axes={'images': {0: 'batch', 2: 'height', 3: 'width'},  # size(1,3,640,640)
        #                   'output': {0: 'batch', 2: 'y', 3: 'x'}} if opt.dynamic else None)
        print("onnx export success")
        # Checks
        onnx_model = onnx.load(f)  # load onnx model
        onnx.checker.check_model(onnx_model)  # check onnx model
        # print(onnx.helper.printable_graph(onnx_model.graph))  # print a human
        # readable model
        print('ONNX export success, saved as %s' % f)
    except Exception as e:
        print('ONNX export failure: %s' % e)


    # Finish
    print(
        '\nExport complete (%.2fs). Visualize with https://github.com/lutzroeder/netron.' %
        (time.time() - t))

```

Output:
```
E:\workspace_python\yolov5\venv\Scripts\python.exe E:/workspace_python/yolov5/export.py
Namespace(batch_size=1, device='cpu', dynamic=False, grid=False, img_size=[320, 320], weights='weights/best.pt')
YOLOv5  v4.0-175-g1b475c1 torch 1.8.1+cu102 CPU

Fusing layers... 
Model Summary: 392 layers, 46632876 parameters, 0 gradients, 114.2 GFLOPS

Starting TorchScript export with torch 1.8.1+cu102...
TorchScript export success, saved as weights/best.torchscript.pt

Starting ONNX export with onnx 1.8.1...

Process finished with exit code -1073741819 (0xC0000005)
```

## Expected behavior
ONNX was successfully generated

## Environment
![屏幕截图 2021-04-03 002645](https://user-images.githubusercontent.com/53484434/113434698-05a6b400-9414-11eb-806f-e030b5824f32.png)

 - OS: [Windows10]
 - GPU [GTX 1050Ti]

**Comment by glenn-jocher** [comment]
@h-fighter thank you for the bug report! Your command successfully exports an ONNX model in our test, so this error is not reproducible:
<img width="1404" alt="Screenshot 2021-04-03 at 12 19 05" src="https://user-images.githubusercontent.com/26833433/113475576-d9704f00-9476-11eb-95d1-95ceb0fde410.png">

It appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below. 


## Requirements

**Python 3.8** or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including **`torch>=1.7`**. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by glenn-jocher** [comment]
@h-fighter tested also with a YOLOv5l model with no issues:
<img width="1404" alt="Screenshot 2021-04-03 at 12 19 05" src="https://user-images.githubusercontent.com/26833433/113475679-67e4d080-9477-11eb-86eb-d890034d4234.png">

**Comment by hongyaohongyao** [comment]
have you solve this problem？
