### ISSUE TITLE
Image Inference from memory

### ISSUE THREAD

**Issue by DrewRidley** [ultralytics/yolov5#2694]
## ❔Question
Hello, I was wondering if there is a way to inference on images in memory. For example, I wanted to serve the model as a web server but writing the file to the disk to inference and then deleting the file invokes significant overhead that could easily be avoided. If this is at all possible to do I would much appreciate some insight.
Thanks.

**Comment by glenn-jocher** [comment]
@DrewDaPilot yes, you can pass various different media formats directly to YOLOv5 PyTorch Hub models for inference, including of course images already loaded into memory. See PyTorch Hub Tutorial for details
https://github.com/ultralytics/yolov5/blob/9ccfa85249a2409d311bdf2e817f99377e135091/models/common.py#L238-L247

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [ONNX and TorchScript Export](https://docs.ultralytics.com/yolov5/tutorials/model_export)
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by DrewRidley** [comment]
Thanks for the reply. I tried what you suggested and I get a strange error.

`    results = model([pilImg], size=640)
  File "C:\Users\Drew\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Drew/.cache\torch\hub\ultralytics_yolov5_master\models\common.py", line 260, in forward
    files.append(Path(im.filename).with_suffix('.jpg').name if isinstance(im, Image.Image) else f'image{i}.jpg')
  File "C:\Users\Drew\anaconda3\lib\pathlib.py", line 868, in with_suffix
    raise ValueError("%r has an empty name" % (self,))
ValueError: WindowsPath('.') has an empty name
127.0.0.1 - - [05/Apr/2021 10:52:47] "POST /upload HTTP/1.1" 500 -`


'import torch
from flask import Flask, request
from PIL import Image


model = torch.hub.load('ultralytics/yolov5', 'yolov5s')
app = Flask(__name__)


@app.route('/upload', methods=['POST'])
def upload():
    if 'file' in request.files:
        image = request.files['file']
        pilImg = Image.open(image.stream)
        results = model([pilImg], size=640)
        results.print()
        return '{ success: true }'
    return "{ success: false}"'

**Comment by glenn-jocher** [comment]
@DrewDaPilot thanks for the bug report. This is a duplicate issue of https://github.com/ultralytics/yolov5/issues/2702 which was also raised today, and is caused by PIL Image objects lacking filenames. We should have a fix for this later today.

**Comment by coneill65** [comment]
> @DrewDaPilot thanks for the bug report. This is a duplicate issue of #2702 which was also raised today and is caused by PIL Image objects lacking filenames. We should have a fix for this later today.
@glenn-jocher  by any chance has this been fixed? cause I have been having this same error.
here is my code.
```python
import torch
import d3dshot

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)


d = d3dshot.create()
img = d.screenshot()
# Image
# img = 'https://github.com/ultralytics/yolov5/raw/master/data/images/zidane.jpg'  # batched list of images

# Inference
results = model(img)

# Results
results.print()
results.show()  # or .show()

# Data
print(results.pandas().xyxy[0])  # print img1 predictions (pixels)
#                   x1           y1           x2           y2   confidence        class
# tensor([[7.50637e+02, 4.37279e+01, 1.15887e+03, 7.08682e+02, 8.18137e-01, 0.00000e+00],
#         [9.33597e+01, 2.07387e+02, 1.04737e+03, 7.10224e+02, 5.78011e-01, 0.00000e+00],
#         [4.24503e+02, 4.29092e+02, 5.16300e+02, 7.16425e+02, 5.68713e-01, 2.70000e+01]])
```
here's the error.

```error
Traceback (most recent call last):
  File "C:/Users/colin/ai_projects/main.py", line 14, in <module>
    results = model(img)
  File "C:\Users\colin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\colin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\colin/.cache\torch\hub\ultralytics_yolov5_master\models\common.py", line 258, in forward
    im, f = np.asarray(exif_transpose(im)), getattr(im, 'filename') or f
AttributeError: 'Image' object has no attribute 'filename'
```

**Comment by coneill65** [comment]
the error is because it's not encoded as a NumPy image here is the working code for anyone that may be interested.
```python
import torch
import d3dshot

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)


d = d3dshot.create(capture_output="numpy")
img = d.screenshot()
# Image
# img = 'https://github.com/ultralytics/yolov5/raw/master/data/images/zidane.jpg'  # batched list of images

# Inference
results = model(img)

# Results
results.print()
results.show()  # or .show()

# Data
print(results.pandas().xyxy[0])  # print img1 predictions (pixels)
#                   x1           y1           x2           y2   confidence        class
# tensor([[7.50637e+02, 4.37279e+01, 1.15887e+03, 7.08682e+02, 8.18137e-01, 0.00000e+00],
#         [9.33597e+01, 2.07387e+02, 1.04737e+03, 7.10224e+02, 5.78011e-01, 0.00000e+00],
#         [4.24503e+02, 4.29092e+02, 5.16300e+02, 7.16425e+02, 5.68713e-01, 2.70000e+01]])
```

**Comment by glenn-jocher** [comment]
@coneill65 if a 3rd party package (especially one not in our requirements) is causing you issues in your custom code the place to inquire is directly with the package authors.
