### ISSUE TITLE
About train.If train the single class dataset.The class loss is zero, is it right？

### ISSUE THREAD

**Issue by SpongeBab** [ultralytics/yolov5#2695]
## If train the single class dataset.The class loss is zero, is it right？
Just like the chart showed:
### results.png:
![图片](https://user-images.githubusercontent.com/65898238/113469275-f1e46780-947e-11eb-849a-52d0414a418c.png)
### labels.png:
And this left-top  chart is all blue.Right-bottom is balnk.Is it right? 
![图片](https://user-images.githubusercontent.com/65898238/113469290-06c0fb00-947f-11eb-8445-328eefa1eef3.png)

**Comment by glenn-jocher** [comment]
@xiaoxiaopeng1998 yes that's correct! There is no class loss for single-class datasets.

**Comment by SpongeBab** [comment]
OK，thank you！
