### ISSUE TITLE
how can I count the objects using yolov5?

### ISSUE THREAD

**Issue by nimashee** [ultralytics/yolov5#2696]
anyone can help me, how to count the object using yolov5?

**Comment by adrianholovaty** [comment]
When you run inference (e.g., via `detect.py`), you'll get a list of all the objects detected. From then, you can write some code that examines all of the detected objects and counts how many there are.

**Comment by nimashee** [comment]
> When you run inference (e.g., via `detect.py`), you'll get a list of all the objects detected. From then, you can write some code that examines all of the detected objects and counts how many there are.

I have wrote this code:
```
class_name_count = 'palm'
            l = s[1:s.find(class_name_count)].split()[-1]
            if class_name_count in s:
                print(l,class_name_count)
                cv2.rectangle(im0, (0,0), (1100, 250), -1)
                cv2.putText(im0,1+class_name_count,(0,200), cv2.FONT_HERSHEY_SIMPLEX, 8,(255,255,255),24,cv2.LINE_AA)
```
but the output:

> TypeError: unsupported operand type(s) for +: 'int' and 'str'

**Comment by SpongeBab** [comment]
> > When you run inference (e.g., via `detect.py`), you'll get a list of all the objects detected. From then, you can write some code that examines all of the detected objects and counts how many there are.
> 
> I have wrote this code:
> 
> ```
> class_name_count = 'palm'
>             l = s[1:s.find(class_name_count)].split()[-1]
>             if class_name_count in s:
>                 print(l,class_name_count)
>                 cv2.rectangle(im0, (0,0), (1100, 250), -1)
>                 cv2.putText(im0,1+class_name_count,(0,200), cv2.FONT_HERSHEY_SIMPLEX, 8,(255,255,255),24,cv2.LINE_AA)
> ```
> 
> but the output:
> 
> > TypeError: unsupported operand type(s) for +: 'int' and 'str'


1 is num ,class_name_count is string

How can they add up...

**Comment by nimashee** [comment]
@xiaoxiaopeng1998 I think so. But, I follow this tutorial in [youtube](https://www.youtube.com/watch?v=894a4oR3oj0) and got that error

**Comment by glenn-jocher** [comment]
@nimashee nice video! You can count all objects very simply, you just look at the shape of the detections for each image. There is one object per row, i.e.:

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Images
dir = 'https://github.com/ultralytics/yolov5/raw/master/data/images/'
imgs = [dir + f for f in ('zidane.jpg', 'bus.jpg')]  # batch of images

# Inference
results = model(imgs)
results.print()  # or .show(), .save()
print(results.pandas().xyxy[0])

image 1/2: 720x1280 2 persons, 1 tie
image 2/2: 1080x810 4 persons, 1 bus
Speed: 110.3ms pre-process, 7.0ms inference, 1.1ms NMS per image at shape (2, 3, 640, 640)
    xcenter   ycenter     width    height  confidence  class    name
0  0.746094  0.522222  0.318750  0.923611    0.817871      0  person
1  0.445898  0.637326  0.745703  0.697569    0.577637      0  person
2  0.367578  0.795833  0.071875  0.400000    0.569336     27     tie
```

**Comment by nimashee** [comment]
@glenn-jocher thank you so much for your answer. I have trained my custom dataset before then I tried your code, it didn't get any error but seems not to detect the shape. So there's no object counted. Should I train my data again or any other solution?
![Screenshot from 2021-04-08 16-35-50](https://user-images.githubusercontent.com/81754659/114004970-55103880-9889-11eb-92a3-5c56f31b7635.png)

**Comment by glenn-jocher** [comment]
@nimashee yes everything works correctly in your screenshot, the model simply does not detect anything. You can lower your confidence threshold to increase recall if you'd like, or you may want to retrain your model for better results. See Tips for Best Training Results for improving training performance.

```python
model.conf = 0.01  # default 0.25
results = model(imgs)
```

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [ONNX and TorchScript Export](https://docs.ultralytics.com/yolov5/tutorials/model_export)
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by nimashee** [comment]
> @nimashee yes everything works correctly in your screenshot, the model simply does not detect anything. You can lower your confidence threshold to increase recall if you'd like, or you may want to retrain your model for better results. See Tips for Best Training Results for improving training performance.
> 
> ```python
> model.conf = 0.01  # default 0.25
> results = model(imgs)
> ```
> 
> ## YOLOv5 Tutorials
> * [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)  rocket RECOMMENDED
> * [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)  shamrock RECOMMENDED
> * [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)  star2 NEW
> * [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)  star2 NEW
> * [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
> * [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)  star NEW
> * [ONNX and TorchScript Export](https://docs.ultralytics.com/yolov5/tutorials/model_export)
> * [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
> * [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
> * [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
> * [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
> * [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)  star NEW
> * [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

Thank you so much. It works for me. Have a great day! ^^

**Comment by MilesJoseph** [comment]
> @nimashee nice video! You can count all objects very simply, you just look at the shape of the detections for each image. There is one object per row, i.e.:
> 
> ```python
> import torch
> 
> # Model
> model = torch.hub.load('ultralytics/yolov5', 'yolov5s')
> 
> # Images
> dir = 'https://github.com/ultralytics/yolov5/raw/master/data/images/'
> imgs = [dir + f for f in ('zidane.jpg', 'bus.jpg')]  # batch of images
> 
> # Inference
> results = model(imgs)
> results.print()  # or .show(), .save()
> print(results.pandas().xyxy[0])
> 
> image 1/2: 720x1280 2 persons, 1 tie
> image 2/2: 1080x810 4 persons, 1 bus
> Speed: 110.3ms pre-process, 7.0ms inference, 1.1ms NMS per image at shape (2, 3, 640, 640)
>     xcenter   ycenter     width    height  confidence  class    name
> 0  0.746094  0.522222  0.318750  0.923611    0.817871      0  person
> 1  0.445898  0.637326  0.745703  0.697569    0.577637      0  person
> 2  0.367578  0.795833  0.071875  0.400000    0.569336     27     tie
> 



hey @glenn-jocher , a few questions I have on this.... Does the results file timestamp, if not do you have any sample code to do this? Do you have any samples for export elsewhere? Do you folks have official github/article for deploying on xavier agx?

**Comment by glenn-jocher** [comment]
@MilesJoseph with the PyTorch Hub inference example you've shown above you have unlimited customization options to export/save or log results any way you want.

We don't have official Xavier AGX tutorial, but once you've exported to TensorRT (use --half for FP16) you can pass the TRT model directly for use the same way as your example above.

YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # yolov5n - yolov5x6 official model
#                                            'custom', 'path/to/best.pt')  # custom model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
results.xyxy[0]  # im predictions (tensor)

results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie

results.pandas().xyxy[0].value_counts('name')  # class counts (pandas)
# person    2
# tie       1
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by alxgrod** [comment]
> @nimashee nice video! You can count all objects very simply, you just look at the shape of the detections for each image. There is one object per row, i.e.:
> 
> ```python
> import torch
> 
> # Model
> model = torch.hub.load('ultralytics/yolov5', 'yolov5s')
> 
> # Images
> dir = 'https://github.com/ultralytics/yolov5/raw/master/data/images/'
> imgs = [dir + f for f in ('zidane.jpg', 'bus.jpg')]  # batch of images
> 
> # Inference
> results = model(imgs)
> results.print()  # or .show(), .save()
> print(results.pandas().xyxy[0])
> 
> image 1/2: 720x1280 2 persons, 1 tie
> image 2/2: 1080x810 4 persons, 1 bus
> Speed: 110.3ms pre-process, 7.0ms inference, 1.1ms NMS per image at shape (2, 3, 640, 640)
>     xcenter   ycenter     width    height  confidence  class    name
> 0  0.746094  0.522222  0.318750  0.923611    0.817871      0  person
> 1  0.445898  0.637326  0.745703  0.697569    0.577637      0  person
> 2  0.367578  0.795833  0.071875  0.400000    0.569336     27     tie
> ```

Is it possible to count total objects detected in a video? For example, counting number of cars in the street would count the ones present in the frame and then it would change for the number of cars in the next frame, instead I am trying to add up all objects detected in the video without duplicating the cars that are present in more than one frame. Your help would be greatly appreciated.

**Comment by Sarouch** [comment]
> > @nimashee nice video! You can count all objects very simply, you just look at the shape of the detections for each image. There is one object per row, i.e.:
> > ```python
> > import torch
> > 
> > # Model
> > model = torch.hub.load('ultralytics/yolov5', 'yolov5s')
> > 
> > # Images
> > dir = 'https://github.com/ultralytics/yolov5/raw/master/data/images/'
> > imgs = [dir + f for f in ('zidane.jpg', 'bus.jpg')]  # batch of images
> > 
> > # Inference
> > results = model(imgs)
> > results.print()  # or .show(), .save()
> > print(results.pandas().xyxy[0])
> > 
> > image 1/2: 720x1280 2 persons, 1 tie
> > image 2/2: 1080x810 4 persons, 1 bus
> > Speed: 110.3ms pre-process, 7.0ms inference, 1.1ms NMS per image at shape (2, 3, 640, 640)
> >     xcenter   ycenter     width    height  confidence  class    name
> > 0  0.746094  0.522222  0.318750  0.923611    0.817871      0  person
> > 1  0.445898  0.637326  0.745703  0.697569    0.577637      0  person
> > 2  0.367578  0.795833  0.071875  0.400000    0.569336     27     tie
> > ```
> 
> Is it possible to count total objects detected in a video? For example, counting number of cars in the street would count the ones present in the frame and then it would change for the number of cars in the next frame, instead I am trying to add up all objects detected in the video without duplicating the cars that are present in more than one frame. Your help would be greatly appreciated.

Hi @alxgrod , did you find a solution for your question ? I want to do the same thing, sum up all object of the same class at the end of the video.

**Comment by phoenixstar7** [comment]
Hi @alxgrod, I am able to get the conf_score per frame per object and then I am using it for my analysis. What I need is to count the number of objects detected per frame as well so I can dump all of them in a log csv file. Any pointers/help is greatly appreciated. TIA!

**Comment by Blazensei** [comment]
Hi sir @glenn-jocher how can this code  be used in detect.py in yolov5 instance segmentation and counting object that is present in the video I have only 1 class in my trained data and I want to detect and count every object on it Thankyou sir. About this in your study sir https://github.com/ultralytics/yolov5/blob/master/detect.py

**Comment by Sarouch** [comment]
> Hi sir @glenn-jocher how can this code be used in detect.py in yolov5 instance segmentation and counting object that is present in the video I have only 1 class in my trained data and I want to detect and count every object on it Thankyou sir. About this in your study sir https://github.com/ultralytics/yolov5/blob/master/detect.py

Hi @Blazensei, you can see my question/answer  [here](https://stackoverflow.com/questions/75017739/insert-an-element-at-a-specific-position-in-a-list-at-each-video-frame-in-python) it may help you.

**Comment by Sarouch** [comment]
> Hi @alxgrod, I am able to get the conf_score per frame per object and then I am using it for my analysis. What I need is to count the number of objects detected per frame as well so I can dump all of them in a log csv file. Any pointers/help is greatly appreciated. TIA!

Hi @phoenixstar7 you can see my question and answer [here on stackoverflow](https://stackoverflow.com/questions/75017739/insert-an-element-at-a-specific-position-in-a-list-at-each-video-frame-in-python) it may help you, you can ask other question if it is not clear

**Comment by Blazensei** [comment]
@Sarouch Hello sir can you guide me how to implement it inside the code? 
# YOLOv5 🚀 by Ultralytics, GPL-3.0 license
"""
Run YOLOv5 detection inference on images, videos, directories, globs, YouTube, webcam, streams, etc.
Usage - sources:
    $ python detect.py --weights yolov5s.pt --source 0                               # webcam
                                                     img.jpg                         # image
                                                     vid.mp4                         # video
                                                     screen                          # screenshot
                                                     path/                           # directory
                                                     list.txt                        # list of images
                                                     list.streams                    # list of streams
                                                     'path/*.jpg'                    # glob
                                                     'https://youtu.be/Zgi9g1ksQHc'  # YouTube
                                                     'rtsp://example.com/media.mp4'  # RTSP, RTMP, HTTP stream
Usage - formats:
    $ python detect.py --weights yolov5s.pt                 # PyTorch
                                 yolov5s.torchscript        # TorchScript
                                 yolov5s.onnx               # ONNX Runtime or OpenCV DNN with --dnn
                                 yolov5s_openvino_model     # OpenVINO
                                 yolov5s.engine             # TensorRT
                                 yolov5s.mlmodel            # CoreML (macOS-only)
                                 yolov5s_saved_model        # TensorFlow SavedModel
                                 yolov5s.pb                 # TensorFlow GraphDef
                                 yolov5s.tflite             # TensorFlow Lite
                                 yolov5s_edgetpu.tflite     # TensorFlow Edge TPU
                                 yolov5s_paddle_model       # PaddlePaddle
"""

import argparse
import os
import platform
import sys
from pathlib import Path

import torch

FILE = Path(__file__).resolve()
ROOT = FILE.parents[0]  # YOLOv5 root directory
if str(ROOT) not in sys.path:
    sys.path.append(str(ROOT))  # add ROOT to PATH
ROOT = Path(os.path.relpath(ROOT, Path.cwd()))  # relative

from models.common import DetectMultiBackend
from utils.dataloaders import IMG_FORMATS, VID_FORMATS, LoadImages, LoadScreenshots, LoadStreams
from utils.general import (LOGGER, Profile, check_file, check_img_size, check_imshow, check_requirements, colorstr, cv2,
                           increment_path, non_max_suppression, print_args, scale_boxes, strip_optimizer, xyxy2xywh)
from utils.plots import Annotator, colors, save_one_box
from utils.torch_utils import select_device, smart_inference_mode


@smart_inference_mode()
def run(
        weights=ROOT / 'yolov5s.pt',  # model path or triton URL
        source=ROOT / 'data/images',  # file/dir/URL/glob/screen/0(webcam)
        data=ROOT / 'data/coco128.yaml',  # dataset.yaml path
        imgsz=(640, 640),  # inference size (height, width)
        conf_thres=0.25,  # confidence threshold
        iou_thres=0.45,  # NMS IOU threshold
        max_det=1000,  # maximum detections per image
        device='',  # cuda device, i.e. 0 or 0,1,2,3 or cpu
        view_img=False,  # show results
        save_txt=False,  # save results to *.txt
        save_conf=False,  # save confidences in --save-txt labels
        save_crop=False,  # save cropped prediction boxes
        nosave=False,  # do not save images/videos
        classes=None,  # filter by class: --class 0, or --class 0 2 3
        agnostic_nms=False,  # class-agnostic NMS
        augment=False,  # augmented inference
        visualize=False,  # visualize features
        update=False,  # update all models
        project=ROOT / 'runs/detect',  # save results to project/name
        name='exp',  # save results to project/name
        exist_ok=False,  # existing project/name ok, do not increment
        line_thickness=3,  # bounding box thickness (pixels)
        hide_labels=False,  # hide labels
        hide_conf=False,  # hide confidences
        half=False,  # use FP16 half-precision inference
        dnn=False,  # use OpenCV DNN for ONNX inference
        vid_stride=1,  # video frame-rate stride
):
    source = str(source)
    save_img = not nosave and not source.endswith('.txt')  # save inference images
    is_file = Path(source).suffix[1:] in (IMG_FORMATS + VID_FORMATS)
    is_url = source.lower().startswith(('rtsp://', 'rtmp://', 'http://', 'https://'))
    webcam = source.isnumeric() or source.endswith('.streams') or (is_url and not is_file)
    screenshot = source.lower().startswith('screen')
    if is_url and is_file:
        source = check_file(source)  # download

    # Directories
    save_dir = increment_path(Path(project) / name, exist_ok=exist_ok)  # increment run
    (save_dir / 'labels' if save_txt else save_dir).mkdir(parents=True, exist_ok=True)  # make dir

    # Load model
    device = select_device(device)
    model = DetectMultiBackend(weights, device=device, dnn=dnn, data=data, fp16=half)
    stride, names, pt = model.stride, model.names, model.pt
    imgsz = check_img_size(imgsz, s=stride)  # check image size

    # Dataloader
    bs = 1  # batch_size
    if webcam:
        view_img = check_imshow(warn=True)
        dataset = LoadStreams(source, img_size=imgsz, stride=stride, auto=pt, vid_stride=vid_stride)
        bs = len(dataset)
    elif screenshot:
        dataset = LoadScreenshots(source, img_size=imgsz, stride=stride, auto=pt)
    else:
        dataset = LoadImages(source, img_size=imgsz, stride=stride, auto=pt, vid_stride=vid_stride)
    vid_path, vid_writer = [None] * bs, [None] * bs

    # Run inference
    model.warmup(imgsz=(1 if pt or model.triton else bs, 3, *imgsz))  # warmup
    seen, windows, dt = 0, [], (Profile(), Profile(), Profile())
    for path, im, im0s, vid_cap, s in dataset:
        with dt[0]:
            im = torch.from_numpy(im).to(model.device)
            im = im.half() if model.fp16 else im.float()  # uint8 to fp16/32
            im /= 255  # 0 - 255 to 0.0 - 1.0
            if len(im.shape) == 3:
                im = im[None]  # expand for batch dim

        # Inference
        with dt[1]:
            visualize = increment_path(save_dir / Path(path).stem, mkdir=True) if visualize else False
            pred = model(im, augment=augment, visualize=visualize)

        # NMS
        with dt[2]:
            pred = non_max_suppression(pred, conf_thres, iou_thres, classes, agnostic_nms, max_det=max_det)

        # Second-stage classifier (optional)
        # pred = utils.general.apply_classifier(pred, classifier_model, im, im0s)

        # Process predictions
        for i, det in enumerate(pred):  # per image
            seen += 1
            if webcam:  # batch_size >= 1
                p, im0, frame = path[i], im0s[i].copy(), dataset.count
                s += f'{i}: '
            else:
                p, im0, frame = path, im0s.copy(), getattr(dataset, 'frame', 0)

            p = Path(p)  # to Path
            save_path = str(save_dir / p.name)  # im.jpg
            txt_path = str(save_dir / 'labels' / p.stem) + ('' if dataset.mode == 'image' else f'_{frame}')  # im.txt
            s += '%gx%g ' % im.shape[2:]  # print string
            gn = torch.tensor(im0.shape)[[1, 0, 1, 0]]  # normalization gain whwh
            imc = im0.copy() if save_crop else im0  # for save_crop
            annotator = Annotator(im0, line_width=line_thickness, example=str(names))
            if len(det):
                # Rescale boxes from img_size to im0 size
                det[:, :4] = scale_boxes(im.shape[2:], det[:, :4], im0.shape).round()

                # Print results
                for c in det[:, 5].unique():
                    n = (det[:, 5] == c).sum()  # detections per class
                    s += f"{n} {names[int(c)]}{'s' * (n > 1)}, "  # add to string

                # Write results
                for *xyxy, conf, cls in reversed(det):
                    if save_txt:  # Write to file
                        xywh = (xyxy2xywh(torch.tensor(xyxy).view(1, 4)) / gn).view(-1).tolist()  # normalized xywh
                        line = (cls, *xywh, conf) if save_conf else (cls, *xywh)  # label format
                        with open(f'{txt_path}.txt', 'a') as f:
                            f.write(('%g ' * len(line)).rstrip() % line + '\n')

                    if save_img or save_crop or view_img:  # Add bbox to image
                        c = int(cls)  # integer class
                        label = None if hide_labels else (names[c] if hide_conf else f'{names[c]} {conf:.2f}')
                        annotator.box_label(xyxy, label, color=colors(c, True))
                    if save_crop:
                        save_one_box(xyxy, imc, file=save_dir / 'crops' / names[c] / f'{p.stem}.jpg', BGR=True)

            # Stream results
            im0 = annotator.result()
            if view_img:
                if platform.system() == 'Linux' and p not in windows:
                    windows.append(p)
                    cv2.namedWindow(str(p), cv2.WINDOW_NORMAL | cv2.WINDOW_KEEPRATIO)  # allow window resize (Linux)
                    cv2.resizeWindow(str(p), im0.shape[1], im0.shape[0])
                cv2.imshow(str(p), im0)
                cv2.waitKey(1)  # 1 millisecond

            # Save results (image with detections)
            if save_img:
                if dataset.mode == 'image':
                    cv2.imwrite(save_path, im0)
                else:  # 'video' or 'stream'
                    if vid_path[i] != save_path:  # new video
                        vid_path[i] = save_path
                        if isinstance(vid_writer[i], cv2.VideoWriter):
                            vid_writer[i].release()  # release previous video writer
                        if vid_cap:  # video
                            fps = vid_cap.get(cv2.CAP_PROP_FPS)
                            w = int(vid_cap.get(cv2.CAP_PROP_FRAME_WIDTH))
                            h = int(vid_cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
                        else:  # stream
                            fps, w, h = 30, im0.shape[1], im0.shape[0]
                        save_path = str(Path(save_path).with_suffix('.mp4'))  # force *.mp4 suffix on results videos
                        vid_writer[i] = cv2.VideoWriter(save_path, cv2.VideoWriter_fourcc(*'mp4v'), fps, (w, h))
                    vid_writer[i].write(im0)

        # Print time (inference-only)
        LOGGER.info(f"{s}{'' if len(det) else '(no detections), '}{dt[1].dt * 1E3:.1f}ms")

    # Print results
    t = tuple(x.t / seen * 1E3 for x in dt)  # speeds per image
    LOGGER.info(f'Speed: %.1fms pre-process, %.1fms inference, %.1fms NMS per image at shape {(1, 3, *imgsz)}' % t)
    if save_txt or save_img:
        s = f"\n{len(list(save_dir.glob('labels/*.txt')))} labels saved to {save_dir / 'labels'}" if save_txt else ''
        LOGGER.info(f"Results saved to {colorstr('bold', save_dir)}{s}")
    if update:
        strip_optimizer(weights[0])  # update model (to fix SourceChangeWarning)


def parse_opt():
    parser = argparse.ArgumentParser()
    parser.add_argument('--weights', nargs='+', type=str, default=ROOT / 'yolov5s.pt', help='model path or triton URL')
    parser.add_argument('--source', type=str, default=ROOT / 'data/images', help='file/dir/URL/glob/screen/0(webcam)')
    parser.add_argument('--data', type=str, default=ROOT / 'data/coco128.yaml', help='(optional) dataset.yaml path')
    parser.add_argument('--imgsz', '--img', '--img-size', nargs='+', type=int, default=[640], help='inference size h,w')
    parser.add_argument('--conf-thres', type=float, default=0.25, help='confidence threshold')
    parser.add_argument('--iou-thres', type=float, default=0.45, help='NMS IoU threshold')
    parser.add_argument('--max-det', type=int, default=1000, help='maximum detections per image')
    parser.add_argument('--device', default='', help='cuda device, i.e. 0 or 0,1,2,3 or cpu')
    parser.add_argument('--view-img', action='store_true', help='show results')
    parser.add_argument('--save-txt', action='store_true', help='save results to *.txt')
    parser.add_argument('--save-conf', action='store_true', help='save confidences in --save-txt labels')
    parser.add_argument('--save-crop', action='store_true', help='save cropped prediction boxes')
    parser.add_argument('--nosave', action='store_true', help='do not save images/videos')
    parser.add_argument('--classes', nargs='+', type=int, help='filter by class: --classes 0, or --classes 0 2 3')
    parser.add_argument('--agnostic-nms', action='store_true', help='class-agnostic NMS')
    parser.add_argument('--augment', action='store_true', help='augmented inference')
    parser.add_argument('--visualize', action='store_true', help='visualize features')
    parser.add_argument('--update', action='store_true', help='update all models')
    parser.add_argument('--project', default=ROOT / 'runs/detect', help='save results to project/name')
    parser.add_argument('--name', default='exp', help='save results to project/name')
    parser.add_argument('--exist-ok', action='store_true', help='existing project/name ok, do not increment')
    parser.add_argument('--line-thickness', default=3, type=int, help='bounding box thickness (pixels)')
    parser.add_argument('--hide-labels', default=False, action='store_true', help='hide labels')
    parser.add_argument('--hide-conf', default=False, action='store_true', help='hide confidences')
    parser.add_argument('--half', action='store_true', help='use FP16 half-precision inference')
    parser.add_argument('--dnn', action='store_true', help='use OpenCV DNN for ONNX inference')
    parser.add_argument('--vid-stride', type=int, default=1, help='video frame-rate stride')
    opt = parser.parse_args()
    opt.imgsz *= 2 if len(opt.imgsz) == 1 else 1  # expand
    print_args(vars(opt))
    return opt


def main(opt):
    check_requirements(exclude=('tensorboard', 'thop'))
    run(**vars(opt))


if __name__ == "__main__":
    opt = parse_opt()
    main(opt)

**Comment by Bhavik-Ardeshna** [comment]
> > @Sarouch @alxgrod  @nimashee nice video! You can count all objects very simply, you just look at the shape of the detections for each image. There is one object per row, i.e.:
> > ```python
> > import torch
> > 
> > # Model
> > model = torch.hub.load('ultralytics/yolov5', 'yolov5s')
> > 
> > # Images
> > dir = 'https://github.com/ultralytics/yolov5/raw/master/data/images/'
> > imgs = [dir + f for f in ('zidane.jpg', 'bus.jpg')]  # batch of images
> > 
> > # Inference
> > results = model(imgs)
> > results.print()  # or .show(), .save()
> > print(results.pandas().xyxy[0])
> > 
> > image 1/2: 720x1280 2 persons, 1 tie
> > image 2/2: 1080x810 4 persons, 1 bus
> > Speed: 110.3ms pre-process, 7.0ms inference, 1.1ms NMS per image at shape (2, 3, 640, 640)
> >     xcenter   ycenter     width    height  confidence  class    name
> > 0  0.746094  0.522222  0.318750  0.923611    0.817871      0  person
> > 1  0.445898  0.637326  0.745703  0.697569    0.577637      0  person
> > 2  0.367578  0.795833  0.071875  0.400000    0.569336     27     tie
> > ```
> 
> Is it possible to count total objects detected in a video? For example, counting number of cars in the street would count the ones present in the frame and then it would change for the number of cars in the next frame, instead I am trying to add up all objects detected in the video without duplicating the cars that are present in more than one frame. Your help would be greatly appreciated.

Hi @alxgrod , did you find a solution for your question ? I want to do the same thing, sum up all object of the same class at the end of the video (Unique objects only).
