### ISSUE TITLE
❔Question Whenever i try to run my model i run into this error AttributeError: 'NoneType' object has no attribute 'startswith' from wandbutils.py line 161 I wonder why ? Any workaround or fix

### ISSUE THREAD

**Issue by markgicharu** [ultralytics/yolov5#2697]
Before submitting a bug report, please be aware that your issue **must be reproducible** with all of the following, otherwise it is non-actionable, and we can not help you:
 - **Current repo**: run `git fetch && git status -uno` to check and `git pull` to update repo
 - **Common dataset**: coco.yaml or coco128.yaml
 - **Common environment**: Colab, Google Cloud, or Docker image. See https://github.com/ultralytics/yolov5#environments
 
If this is a custom dataset/training question you **must include** your `train*.jpg`, `test*.jpg` and `results.png` figures, or we can not help you. You can generate these with `utils.plot_results()`.

## To Reproduce (REQUIRED)

Input:
```
import torch

a = torch.tensor([5])
c = a / 0
```

Output:
```
Traceback (most recent call last):
  File "/Users/glennjocher/opt/anaconda3/envs/env1/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-be04c762b799>", line 5, in <module>
    c = a / 0
RuntimeError: ZeroDivisionError
```

## Environment

 - OS: [e.g. Ubuntu]
 - GPU [e.g. 2080 Ti]

Hello @glenn-jocher,
As per your advise i have pushed this to a bug.
I have posted the screenshots to my error and the wandb logging for assistance
## Additional context
[data.yaml.zip](https://github.com/ultralytics/yolov5/files/6253299/data.yaml.zip)
![image](https://user-images.githubusercontent.com/16897706/113489940-cb025180-94cf-11eb-8ccc-943db5f40a4f.png)
![image](https://user-images.githubusercontent.com/16897706/113489945-d35a8c80-94cf-11eb-9bd2-1c1ef580f89b.png)
![image](https://user-images.githubusercontent.com/16897706/113490054-7c08ec00-94d0-11eb-844e-9e85dfa589ff.png)
![image](https://user-images.githubusercontent.com/16897706/113490057-85925400-94d0-11eb-804b-0e1388a4f866.png)

https://wandb.ai/markgich/YOLOv5/runs/3na79834/logs?workspace=user-

**Comment by markgicharu** [comment]
Following the aadvise of @AyushExel I have recreated the same problem on the paths
I have decided to pass the absolute path and am making some headway:
![image](https://user-images.githubusercontent.com/16897706/113490232-68aa5080-94d1-11eb-957f-4d73b51424d7.png)

**Comment by glenn-jocher** [comment]
@markgicharu your last screenshot seems fine. The duplicate label warning is because your labels have duplicate rows for those images, so these particular images will be ignored for training.

**Comment by markgicharu** [comment]
@glenn-jocher This is well noted.
Thanks for the info on the duplicate label part.
As for the "NoneType" error when i pass the absolute path in the data.yaml the system works.
Am testing a small loop for 5 epochs to see the result.
I can close the issue then?

**Comment by markgicharu** [comment]
The system works perfectly
been able to do a successful run
Therefore, the passing the absolute path in the data.yaml helps alleviate this error as well as a workaround!

**Comment by glenn-jocher** [comment]
@markgicharu great, thanks for the feedback, and let us know if you run into any other problems!

**Comment by markgicharu** [comment]
@glenn-jocher Most welcome and thanks for the great support
