### ISSUE TITLE
OpenBLAS Warning

### ISSUE THREAD

**Issue by mikecr96** [ultralytics/yolov5#2698]
I'm running yolov5 on Raspberry Pi 4 Model B (4GB RAM), Manjaro OS (64 bits).
When I run the example `python detect.py --source data/images --weights yolov5s.pt --conf 0.25` I get back this:
`OpenBLAS Warning : Detect OpenMP Loop and this application may hang. Please rebuild the library with USE_OPENMP=1 option.` repeatedly. Actually it works fine, script is doing inference well but I just want to remove this warning but not ignoring it.

What should I do in order to fix it?

**Comment by fhrgithub** [comment]
I have the same problem,do you solve the problem?

**Comment by TadeasFrycak** [comment]
@mikecr96 @fhrgithub I have the same issue on RPi 4 64bit OS (Raspbian). I am using Python 3.7.3 (torch==1.8.0; torchvision==0.9.1). Do you solve the problem, please?

**Comment by phuochung** [comment]
@fhrgithub @frycaktadeas @mikecr96 Did you solve the problem?

**Comment by glenn-jocher** [comment]
@frycaktadeas sorry to hear you had trouble with this issue. The warning you mentioned is related to the OpenBLAS library. Although it doesn't affect the functionality of YOLOv5, it's understandable you'd like to address it.

For most users, the warning can be safely ignored during YOLOv5 inference, as you observed. However, if you'd like to remove the warning, you could consider rebuilding the OpenBLAS library with the USE_OPENMP=1 option as suggested. Please note that doing so is a system-level operation and may require familiarity with building software from source.

Should you decide to pursue this, you can refer to the OpenBLAS documentation or the Manjaro community for specific guidance on rebuilding OpenBLAS with the USE_OPENMP=1 option.

In the meantime, if you have any other questions or need further assistance, feel free to ask! And congratulations on your purchase of the Jetson! It's a powerful platform, and we hope it serves you well.
