### ISSUE TITLE
training crash

### ISSUE THREAD

**Issue by zidanexu** [ultralytics/yolov5#27]
- Python
 - PyTorch 1.4
 - tesla P40
 - centos
the command line:  python train.py --data data/coco.yaml --cfg  models/yolov5s.yaml --weights '' --batch-size 128 --resume --device='0,1,2,3,4,5,6,7'
![image](https://user-images.githubusercontent.com/54395639/84099897-4a083400-aa3d-11ea-9197-f27e97dba8b4.png)
btw, this case has also happened at 46 epochs

**Comment by glenn-jocher** [comment]
@zidanexu I've not seen this error before, so I'm sorry but I don't think I can help you.

I might recommend training in a common environment, such as our docker container to avoid any potential environment issues. For example environments see https://github.com/ultralytics/yolov5/wiki
