### ISSUE TITLE
Not able to use the webcam as a source by specifying the --source as 0.

### ISSUE THREAD

**Issue by SushmitaU** [ultralytics/yolov5#270]
Hi,
I wanted the model to work on live streaming so I used the command **!python detect.py --weights weights/last_yolov5s_results.pt --conf 0.4 --source 0**. But i am getting the following error:

/content/yolov5
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.4, device='', fourcc='mp4v', img_size=640, iou_thres=0.5, output='inference/output', save_txt=False, source='0', view_img=False, weights='weights/last_yolov5s_results.pt')
Using CUDA device0 _CudaDeviceProperties(name='Tesla K80', total_memory=11441MB)

[ WARN:0] global /io/opencv/modules/videoio/src/cap_v4l.cpp (802) open VIDEOIO ERROR: V4L: can't open camera by index 0
1/1: 0... Traceback (most recent call last):
  File "detect.py", line 159, in <module>
    detect()
  File "detect.py", line 44, in detect
    dataset = LoadStreams(source, img_size=imgsz)
  File "/content/yolov5/utils/datasets.py", line 224, in __init__
    assert cap.isOpened(), 'Failed to open %s' % s
AssertionError: Failed to open 0

The script is working fine for images but I needed to use webcam. Please let me know what should be done.

Thanks,
Sushmita

**Comment by glenn-jocher** [comment]
webcam operates on a local machine, not through colab.
