### ISSUE TITLE
Cancel data augmentation

### ISSUE THREAD

**Issue by huangxudong** [ultralytics/yolov5#2701]
How do I cancel data augmentation?

**Comment by glenn-jocher** [comment]
@huangxudong you can reduce or remove (set to 0) any or all augmentation hyperparameters in the default hyp.scratch.yaml file used for training:
```
python train.py --hyp hyp.scratch.yaml 
```
https://github.com/ultralytics/yolov5/blob/9ccfa85249a2409d311bdf2e817f99377e135091/data/hyp.scratch.yaml#L22-L33
