### ISSUE TITLE
How to change the bounding box thickness and label font size?

### ISSUE THREAD

**Issue by Leprechault** [ultralytics/yolov5#2705]
Hi Everyone!

My validation images have a small size and the default bounding and label are not possible to see clearly . How to change the bounding box thickness and label font size using `detect.py` function (If is possible, I'd to change the font type too. eg: serif type)?

Thanks in advance.

**Comment by glenn-jocher** [comment]
@Leprechault you can modify detect.py plotting properties here:
https://github.com/ultralytics/yolov5/blob/9ccfa85249a2409d311bdf2e817f99377e135091/detect.py#L113

**Comment by Leprechault** [comment]
Thanks @glenn-jocher 

Works if I make:
`plot_one_box(xyxy, im0, label=label, color=colors[int(cls)], line_thickness=1)`

But if I try to change font size doesn't work for:
`plot_one_box(xyxy, im0, label=label, color=colors[int(cls)], line_thickness=1, labelsize=10)` , when I try to use the `labelsize`  or `fontsize` parameter.

**Comment by glenn-jocher** [comment]
@Leprechault for finer grained control you can always modify the plotting function itself. We also have a PIL plotting function as an alternative. PIL will produce nicer looking results, but it's plotting routines are slower, so we use cv2 by default.
https://github.com/ultralytics/yolov5/blob/ec8979f1d2f99b6873c2eafe05ec5bc2febad468/utils/plots.py#L57-L83

**Comment by Leprechault** [comment]
Thank you so much for the attention @glenn-jocher !!! Problem solved.

**Comment by Mansurjons** [comment]
friend I also have these problem but I don't understand these code can you help me


def plot_one_box(x, img, color=None, label=None, line_thickness=3): 
     # Plots one bounding box on image img 
     tl = line_thickness or round(0.002 * (img.shape[0] + img.shape[1]) / 2) + 1  # line/font thickness 
     color = color or [random.randint(0, 255) for _ in range(3)] 
     c1, c2 = (int(x[0]), int(x[1])), (int(x[2]), int(x[3])) 
     cv2.rectangle(img, c1, c2, color, thickness=tl, lineType=cv2.LINE_AA) 
     if label: 
         tf = max(tl - 1, 1)  # font thickness 
         t_size = cv2.getTextSize(label, 0, fontScale=tl / 3, thickness=tf)[0] 
         c2 = c1[0] + t_size[0], c1[1] - t_size[1] - 3 
         cv2.rectangle(img, c1, c2, color, -1, cv2.LINE_AA)  # filled 
         cv2.putText(img, label, (c1[0], c1[1] - 2), 0, tl / 3, [225, 255, 255], thickness=tf, lineType=cv2.LINE_AA) 
  
  
 def plot_one_box_PIL(box, img, color=None, label=None, line_thickness=None): 
     img = Image.fromarray(img) 
     draw = ImageDraw.Draw(img) 
     line_thickness = line_thickness or max(int(min(img.size) / 200), 2) 
     draw.rectangle(box, width=line_thickness, outline=tuple(color))  # plot 
     if label: 
         fontsize = max(round(max(img.size) / 40), 12) 
         font = ImageFont.truetype("Arial.ttf", fontsize) 
         txt_width, txt_height = font.getsize(label) 
         draw.rectangle([box[0], box[1] - txt_height + 4, box[0] + txt_width, box[1]], fill=tuple(color)) 
         draw.text((box[0], box[1] - txt_height + 1), label, fill=(255, 255, 255), font=font) 
     return np.asarray(img) 
  






can you help me

**Comment by glenn-jocher** [comment]
@Mansurjons absolutely, I can help! It looks like you've shared the plotting functions for drawing bounding boxes with labels, using both OpenCV and PIL libraries. These functions allow you to customize the appearance of bounding boxes and labels in images. If you have a specific question or need help with understanding a part of the code, feel free to ask and I'll be glad to assist you further.
