### ISSUE TITLE
Inference with the pretrained and custom weights , the FPS are very low than given in README.md

### ISSUE THREAD

**Issue by research-boy** [ultralytics/yolov5#2706]
Tested Models - YOLOv5s , YOLOV5m
Tested on GPUs - NVIDIA 2070, NVIDIA Quadro 6000
Tested on OS - Ubuntu 20.04, WIndows 10
Inference Batch size : 1
Image size : 640

As per the table provided : 
 - FPS of model YOLOv5s is 455 , for which i got 34 
- FPS of model YOLOv5m is 345 , for which i got 20

**Comment by glenn-jocher** [comment]
@research-boy instructions for reproducing table results are directly below table.

<img width="871" alt="Screenshot 2021-04-05 at 20 48 24" src="https://user-images.githubusercontent.com/26833433/113612689-72a68d80-9650-11eb-8cd1-5c4a8ba945c3.png">

**Comment by research-boy** [comment]
@glenn-jocher  Does that mean the we can reproduce the same fps on coco dataset and with batch size 32 ?

**Comment by glenn-jocher** [comment]
@research-boy yes

**Comment by research-boy** [comment]
@glenn-jocher  would like to know in case of deployment , what will be the preferred parameter settings to get optimal fps? 
And is there any way to use batch processing in class loadstreams , this for trying batch processing on webcam input?

**Comment by glenn-jocher** [comment]
@research-boy the default settings for best inference under most common use cases are already in place in detect.py and PyTorch Hub model inference. You may want to adapt these as necessary to your custom requirements.
https://github.com/ultralytics/yolov5/blob/ec8979f1d2f99b6873c2eafe05ec5bc2febad468/detect.py#L149-L168

For PyTorch Hub inference see PyTorch Hub tutorial:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [ONNX and TorchScript Export](https://docs.ultralytics.com/yolov5/tutorials/model_export)
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by research-boy** [comment]
@glenn-jocher is there any way to use batch processing in class loadstreams , this for trying batch processing on webcam input?

**Comment by glenn-jocher** [comment]
@research-boy loadstreams dataloader automatically runs batched inference. If you supply 32 streams then your batch size is 32.

**Comment by vtyw** [comment]
> @research-boy the default settings for best inference under most common use cases are already in place in detect.py and PyTorch Hub model inference. You may want to adapt these as necessary to your custom requirements.

@glenn-jocher What's the difference between using `detect.py` and `hubconf.py`?

I'm surprised that the Hub version seems to process a whole list of images as one batch, as opposed to dividing the images into batches of a fixed size. The point of using a fixed batch size is to find the sweet spot between inference time (which increases sub-linearly with batch size) versus the time to load each batch.

**Comment by glenn-jocher** [comment]
@vtyw detect.py is a fully managed command-line YOLOv5 inference solution. 

YOLOv5 PyTorch Hub models with autoShape() wrappers are python inference solutions suitable for integration into custom projects. For batch-size 1 inference with these models you can simply pass one image at a time.

**Comment by vtyw** [comment]
@glenn-jocher Here's what I collected as an example:

Using yolov5s inference on 640x640 images on a single RTX 2080:

| Batch size        | Inference FPS           | FPS including output  | GPU Mem (MiB)
| ------------- |:-------------:|:-------------:|:-------------:|
| 1      | 101 | 54 | 1155
| 2      | 177      |   73 | 1169 
| 4      | 239      |    82 | 1239
| 8      | 252      |    88 | 1333
| 16      | 238      |    89 | 1573

From this I could form a conclusion such as: using a larger batch size improves FPS up to n = 8, and the increase in GPU memory is insignificant. Many object detection libraries offer this batch processing as a built-in feature, and that's why I was confused when batch processing is mentioned in the README and in some code comments but isn't actually a built-in feature as such.

**Comment by glenn-jocher** [comment]
@vtyw nice table! Batched inference is the automatic default when more than 1 image is passed for inference in our YOLOv5 PyTorch Hub solution:

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Images
dir = 'https://github.com/ultralytics/yolov5/raw/master/data/images/'
imgs = [dir + f for f in ('zidane.jpg', 'bus.jpg')]  # batch of images

# Inference
results = model(imgs)
results.print()  # or .show(), .save()
```

<img width="700" alt="Screen Shot 2021-04-08 at 11 21 16 AM" src="https://user-images.githubusercontent.com/26833433/114001866-a2c27c00-985c-11eb-8e54-91029f88af16.png">


See PyTorch Hub tutorial for details:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [ONNX and TorchScript Export](https://docs.ultralytics.com/yolov5/tutorials/model_export)
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by zeyad-mansour** [comment]
Why is batched processing (multiple images at once) faster?

Is there a way to achieve that speed by processing images singularly (stream processing)?

**Comment by research-boy** [comment]
@zeyad-mansour  If you looking specific to deploy the model on an edge device try TensorRT  with different precision, this should give better FPS.
About the batch processing here it's caching the images into memory then doing inference on that, while doing inference on live video , you will be grabbing frame by frame and loading into memory to do inference.

**Comment by zeyad-mansour** [comment]
@research-boy That's what I figured. Thanks for the explanation!
