### ISSUE TITLE
Basic doubts about yolov5 s, m, l and xl

### ISSUE THREAD

**Issue by Leprechault** [ultralytics/yolov5#2707]
Hi Everyone!

Please, I'd like to know a basic explanation about yolov5 s, m, l, and xl. My question is if s, m, l, and xl are different pre-training weight models or different yolov5 architectures for training with different numbers of convolutions and hidden layers, for example?

Thanks in advance!

**Comment by decent-engineer-decent-datascientist** [comment]
https://github.com/ultralytics/yolov5/tree/master/models

The yaml files are pretty self explanatory.
