### ISSUE TITLE
hello, everyone, In order to modify the network more conveniently based on this rep., I restructure the network part, which is divided into backbone, neck, head

### ISSUE THREAD

**Issue by Bobo-y** [ultralytics/yolov5#2710]
The original Yolo V5 was an amazing project. For professionals, it should not be difficult to understand and modify its code. I'm not an expert. When I want to make some changes to the network, it's not so easy, such as adding branches and trying other backbones. Maybe there are people like me, so I split the yolov5 model to {backbone, neck, head} to facilitate the operation of various modules and support more backbones (including resnet, mobilenet, shufflenet, efficientnet).Basically, I only changed the model, and I didn't change the architecture, training and testing of yolov5. Therefore, if the original code is updated, it is also very convenient to update this code.

[my repo](https://github.com/yl305237731/flexible-yolov5)
![image](https://user-images.githubusercontent.com/9928596/113645131-e54b5380-96b8-11eb-9f3d-e2f015765a6e.png)

**Comment by glenn-jocher** [comment]
@yl305237731 thanks for the link! I like the modular approach you have for joining different backbones.
