### ISSUE TITLE
Should yolov5 reproduce on COCO need yolov5 backbone pretrain weights?

### ISSUE THREAD

**Issue by lji72** [ultralytics/yolov5#2711]
## ❔ Question
Should yolov5 reproduce on COCO need yolov5 backbone pretrain weights?

## Additional context
I train yolov5s on coco with random init weights and it has a bad performance 8%mMAP with training 200 epochs. 
 So I doubt that the reproduce training on coco needs pretrain weights. Yolov4 needs a backbone pretrain model when training on coco.  Can you tell me whether training on coco need pretrain weights？

Many thanks for your help.

**Comment by lji72** [comment]
So can you tell me whether training on coco need backbone pretrain weight or not?

**Comment by glenn-jocher** [comment]
@lji72 all YOLOv5 models are trained from randomly initialized weights. No pretrained weights are used. Commands to reproduce our training are shown in README. Nothing else is required.
https://github.com/ultralytics/yolov5#training

## Training

Run commands below to reproduce results on [COCO](https://github.com/ultralytics/yolov5/blob/master/data/scripts/get_coco.sh) dataset (dataset auto-downloads on first use). Training times for YOLOv5s/m/l/x are 2/4/6/8 days on a single V100 (multi-GPU times faster). Use the largest `--batch-size` your GPU allows (batch sizes shown for 16 GB devices).
```bash
$ python train.py --data coco.yaml --cfg yolov5s.yaml --weights '' --batch-size 64
                                         yolov5m                                40
                                         yolov5l                                24
                                         yolov5x                                16
```
<img src="https://user-images.githubusercontent.com/26833433/90222759-949d8800-ddc1-11ea-9fa1-1c97eed2b963.png" width="900">

**Comment by lji72** [comment]
Many thanks for your reply！
