### ISSUE TITLE
YOLOv5 'Ignore' Regions

### ISSUE THREAD

**Issue by zhenzhenzhizhi** [ultralytics/yolov5#2720]
## ❔Question
How to use yolov5 to deal with the ignored area in a picture？

## Additional context
Recently, I used the UA-DETRAC data set to train the vehicle detection model, and found that the model trained by yolov5 can recognize the vehicles that ignore the area (I didn't realize the problem of ignoring the area before, so I used the original image to train directly).
<img width="443" alt="深度截图_选择区域_20210406225018" src="https://user-images.githubusercontent.com/82042615/113730427-7a3a6500-972a-11eb-8b8e-1bd1c4786954.png">

I want to deal with it as follows: the IOA (intersection over anchor) of anchor and ignore region is greater than 0.5, which can not be used as negative examples (and background)

But I don't know how to use yolov5 to realize it. I hope to get your advice.
For example:

**Comment by glenn-jocher** [comment]
@zhenzhenzhizhi I'm not sure I understand the question. You can filter detections in postprocessing to whatever candidate criteria you want, including regional criteria.

Though crowd counting specifically is best handled as a heatmap problem rather than an object detection problem.

**Comment by www516717402** [comment]
@zhenzhenzhizhi Its easy to filter ignore region please refer to mmdet. However IOA not suit for yolov5 and you need modify it by yolov5 label assign.

**Comment by zhenzhenzhizhi** [comment]
> @zhenzhenzhizhi Its easy to filter ignore region please refer to mmdet. However IOA not suit for yolov5 and you need modify it by yolov5 label assign.
你好，你有做过类似的工作吗？具体是怎么做得呢？网上说可以将忽略区域变成黑色，但是效果听说不太好。我有点没有听懂你说的标签分配，我不清楚在YOLOv5中要如何实现这个操作。

**Comment by zhenzhenzhizhi** [comment]
你好，你有做过类似的工作吗？具体是怎么做得呢？网上说可以将忽略区域变成黑色，但是效果听说不太好。我有点没有听懂你说的标签分配，我不清楚在YOLOv5中要如何实现这个操作。 @www516717402

**Comment by www516717402** [comment]
@zhenzhenzhizhi Please refer to mmdet project for more details.

**Comment by zhenzhenzhizhi** [comment]
@glenn-jocher Sorry,you could click on this link, I'm sure you'll understand me right away
https://github.com/facebookresearch/detectron2/issues/2639

**Comment by glenn-jocher** [comment]
@zhenzhenzhizhi it looks like the following two issues mention the same:

- https://github.com/facebookresearch/detectron2/issues/2639
- https://github.com/facebookresearch/detectron2/issues/1909

There is no training function for this at the moment. What dataset are you using? CrowdHuman and VisDrone were mentioned, do these both label ignore regions as -1 class?

**Comment by zhenzhenzhizhi** [comment]
The data set I use is ua-detrac, which is a vehicle detection data set.  You can scan this [https://detrac-db.rit.albany.edu/Detection](url)    
<img width="785" alt="深度截图_选择区域_20210408152525" src="https://user-images.githubusercontent.com/82042615/113985554-ddd5a700-987e-11eb-9960-f06d775a106b.png">

Can yolov5 treat ignored regions as - 1 class?

**Comment by zhenzhenzhizhi** [comment]
The data set I use is ua-detrac, which is a vehicle detection data set. You can scan this https://detrac-db.rit.albany.edu/Detection
深度截图_选择区域_20210408152525

Can yolov5 treat ignored regions as - 1 class? @glenn-jocher

**Comment by xiaomujiang** [comment]
> The data set I use is ua-detrac, which is a vehicle detection data set. You can scan this https://detrac-db.rit.albany.edu/Detection 深度截图_选择区域_20210408152525
> 
> Can yolov5 treat ignored regions as - 1 class? @glenn-jocher


if  set ignored region as -1 class , How about the effect on  UA-DETRAC data ？

**Comment by glenn-jocher** [comment]
@xiaomujiang YOLOv5 does not natively support assigning specific classes to ignored regions. The effect of setting ignored regions as -1 class on UA-DETRAC data may require additional preprocessing and adaptions to the training and evaluation process. Consider referencing related projects or customizing the YOLOv5 label assignment to accommodate this behavior.
