### ISSUE TITLE
Can feed tensor the model

### ISSUE THREAD

**Issue by mfoglio** [ultralytics/yolov5#2722]
Why does `model(img)` works but `model(torch.Tensor(img))` does not, despite having the same shape resulting in the following error?
```
RuntimeError: Sizes of tensors must match except in dimension 2. Got 1 and 2 (The offending index is 0)
```
`img` is of shape `(720, 1280, 3)` and of type `int`.
Thanks

**Comment by glenn-jocher** [comment]
@mfoglio I'm assuming you're referring to the YOLOv5 PyTorch Hub models? These use our autoShape() wrapper, which is tensor capable but mainly intended for inference directly on images, thus sidestepping any need to have your image as a torch tensor. The full list of supported formats is shown in the autoShape() forward method comments, including the required HWC or BCHW format:

https://github.com/ultralytics/yolov5/blob/c8c8da60792e37e2941fc27ee4d0594fcdcee34a/models/common.py#L224-L247

**Comment by namirinz** [comment]
@glenn-jocher

Using torch.hub yolov5s model
running this code

```det_results = yolo_model(torch.ones(4,3,720,1280))```
Get the error
```
RuntimeError                              Traceback (most recent call last)
<ipython-input-10-407ec9b2d209> in <module>
      1 image = torch.ones(4,3,720,1280)
      2 print(image.shape)
----> 3 det_results = yolo_model(image)
      4 
      5 #det_results_xyxy, det_results_xywh = process_yolo(det_results, score_thr=0.3)

/home/namriinz/miniconda3/envs/torch_env/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    887             result = self._slow_forward(*input, **kwargs)
    888         else:
--> 889             result = self.forward(*input, **kwargs)
    890         for hook in itertools.chain(
    891                 _global_forward_hooks.values(),

~/.cache/torch/hub/ultralytics_yolov5_master/models/common.py in forward(self, imgs, size, augment, profile)
    195         p = next(self.model.parameters())  # for device and type
    196         if isinstance(imgs, torch.Tensor):  # torch
--> 197             return self.model(imgs.to(p.device).type_as(p), augment, profile)  # inference
    198 
    199         # Pre-process

/home/namriinz/miniconda3/envs/torch_env/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    887             result = self._slow_forward(*input, **kwargs)
    888         else:
--> 889             result = self.forward(*input, **kwargs)
    890         for hook in itertools.chain(
    891                 _global_forward_hooks.values(),

~/.cache/torch/hub/ultralytics_yolov5_master/models/yolo.py in forward(self, x, augment, profile)
    121             return torch.cat(y, 1), None  # augmented inference, train
    122         else:
--> 123             return self.forward_once(x, profile)  # single-scale inference, train
    124 
    125     def forward_once(self, x, profile=False):

~/.cache/torch/hub/ultralytics_yolov5_master/models/yolo.py in forward_once(self, x, profile)
    137                 print('%10.1f%10.0f%10.1fms %-40s' % (o, m.np, dt[-1], m.type))
    138 
--> 139             x = m(x)  # run
    140             y.append(x if m.i in self.save else None)  # save output
    141 

/home/namriinz/miniconda3/envs/torch_env/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    887             result = self._slow_forward(*input, **kwargs)
    888         else:
--> 889             result = self.forward(*input, **kwargs)
    890         for hook in itertools.chain(
    891                 _global_forward_hooks.values(),

~/.cache/torch/hub/ultralytics_yolov5_master/models/common.py in forward(self, x)
    152 
    153     def forward(self, x):
--> 154         return torch.cat(x, self.d)
    155 
    156 

RuntimeError: Sizes of tensors must match except in dimension 2. Got 45 and 46 (The offending index is 0)
```

**Comment by glenn-jocher** [comment]
@namirinz this error is caused because you are passing a torch tensor with an image size 720, which does not meet the YOLOv5 stride-multiple constraints. Each image dimension must be an even multiple of 32 for P5 models, or 64 for P6 models. The nearest compatible image shape would be (4,3,736,1280). 

PyTorch inference uses a pass-through channel in the autoShape() wrapper which is much simpler than all of the other sources, because the use case is that the model is embedded in a more fully managed solution like detect.py which is supplying checks, pre and post processing:
https://github.com/ultralytics/yolov5/blob/c8c8da60792e37e2941fc27ee4d0594fcdcee34a/models/common.py#L250-L252

**Comment by glenn-jocher** [comment]
@namirinz I will update the comment in the forward method though to avoid confusion in the future.

**Comment by glenn-jocher** [comment]
@namirinz I've updated the comments in https://github.com/ultralytics/yolov5/pull/2725/commits/ccbe7dece9b60f15c561ce9305d3901402c21943 which is part of an existing Hub model PR https://github.com/ultralytics/yolov5/pull/2725.

**Comment by glenn-jocher** [comment]
@namirinz PR #2725 is merged now with updated comments, hopefully this will help future users.

**Comment by thaingoc2604** [comment]
I need to check if the detect result is available, if it is, the button will appear if not, how to check that, what value do we need to compare?

**Comment by glenn-jocher** [comment]
@thaingoc2604 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, custom

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by thaingoc2604** [comment]
I still don't understand what I need to do with the above code and it's at the top of the source

**Comment by thaingoc2604** [comment]
@glenn-jocher I'm also interested in how to know if the object can be recognized or not?
as you said, how can i get the results
![image](https://user-images.githubusercontent.com/66120557/149986182-0a0a9f9b-ca47-445b-9802-39f0861210a1.png)
and when that result is obtained, what value should be compared with to know the identity and to do the next action

**Comment by NgocThaiPhuong** [comment]
@glenn-jocher I'm also interested in how to know if the object can be recognized or not?
as you said, how can i get the results
![image](https://user-images.githubusercontent.com/97728025/149986554-ec11362b-bc90-4597-b177-f6ebfa6f39e0.png)
and when that result is obtained, what value should be compared with to know the identity and to do the next action

**Comment by glenn-jocher** [comment]
@NgocThaiPhuong I don't understand your question. You just copy and paste the code I've already provided you in https://github.com/ultralytics/yolov5/issues/2722#issuecomment-1014971845

**Comment by NgocThaiPhuong** [comment]
@glenn-jocher 
I still don't understand how to be able to check if I'm recognized directly, is there any way I can check how I know if I'm recognized.
I looked through #2722(comment) , I still don't understand how to do it, can you speak better?

**Comment by glenn-jocher** [comment]
@NgocThaiPhuong 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, custom

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by GiuseppeMind** [comment]
Hi!
if I run an inference on yolo model, using a tensor input, I get a strange output. Example
tensor_input.size() = torch.Size([2, 3, 640, 640])
results = model(tensor_input )
results.size() = torch.Size([2, 25200, 85])
What does that tensor represent??
Thanks!

**Comment by glenn-jocher** [comment]
@GiuseppeMind there is no reason to pass a Tensor to a PyTorch Hub model, as it accepts every form of images already, i.e. cv2, PIL, numpy, filenames and URLs.

**Comment by GiuseppeMind** [comment]
> @GiuseppeMind there is no reason to pass a Tensor to a PyTorch Hub model, as it accepts every form of images already, i.e. cv2, PIL, numpy, filenames and URLs.

I understand that but I wanted to know what that represented. Also I am trying to do quantization on the model and so I stumbled into having to deal with tensors as inputs, maybe. 
Do you have any comment on my previous question and on yolov5 quantization?
Thanks!

**Comment by glenn-jocher** [comment]
@GiuseppeMind torch inputs act as pass-throughs, i.e. as if the AutoShape class does not exist. This is due to the fact that any preprocessing steps a user has applies to a tensor are unknowable to the AutoShape class and it can thus not know a postprocessing strategy:
https://github.com/ultralytics/yolov5/blob/f735458987f7e80c32739bfe0440cbcad36aeae3/models/common.py#L533-L536

**Comment by GiuseppeMind** [comment]
> @GiuseppeMind torch inputs act as pass-throughs, i.e. as if the AutoShape class does not exist. This is due to the fact that any preprocessing steps a user has applies to a tensor are unknowable to the AutoShape class and it can thus not know a postprocessing strategy:
> 
> https://github.com/ultralytics/yolov5/blob/f735458987f7e80c32739bfe0440cbcad36aeae3/models/common.py#L533-L536

I am afraid I do not follow. I see in the forward method:

So I am using torch tensor as explained. 

```
    @torch.no_grad()
    def forward(self, imgs, size=640, augment=False, profile=False):
        # Inference from various sources. For height=640, width=1280, RGB images example inputs are:
        #   file:       imgs = 'data/images/zidane.jpg'  # str or PosixPath
        #   URI:             = 'https://ultralytics.com/images/zidane.jpg'
        #   OpenCV:          = cv2.imread('image.jpg')[:,:,::-1]  # HWC BGR to RGB x(640,1280,3)
        #   PIL:             = Image.open('image.jpg') or ImageGrab.grab()  # HWC x(640,1280,3)
        #   numpy:           = np.zeros((640,1280,3))  # HWC
        #   torch:           = torch.zeros(16,3,320,640)  # BCHW (scaled to size=640, 0-1 values)
        #   multiple:        = [Image.open('image1.jpg'), Image.open('image2.jpg'), ...]  # list of images
```

**Comment by JohnTailor** [comment]
> @GiuseppeMind torch inputs act as pass-throughs, i.e. as if the AutoShape class does not exist. This is due to the fact that any preprocessing steps a user has applies to a tensor are unknowable to the AutoShape class and it can thus not know a postprocessing strategy:
> 
> https://github.com/ultralytics/yolov5/blob/f735458987f7e80c32739bfe0440cbcad36aeae3/models/common.py#L533-L536

You are missing postprocessing for torch inputs, i.e.
you do:  
return self.model(imgs.to(p.device).type_as(p), augment, profile) 

but you should be doing postprocessing as you for images (given by filenames, PIL etc):

            y = self.model(imgs.to(p.device).type_as(p), augment, profile)   # forward
            t.append(time_sync())

            # Post-process
            y = non_max_suppression(y if self.dmb else y[0],
                                    self.conf,
                                    self.iou,
                                    self.classes,
                                    self.agnostic,
                                    self.multi_label,
                                    max_det=self.max_det)  # NMS
            for i in range(n):
                scale_coords(shape1, y[i][:, :4], shape0[i])

            t.append(time_sync())
            return Detections(imgs, y, files, t, self.names, x.shape)

**Comment by glenn-jocher** [comment]
Postprocessing is not possible without preprocessing since we do not know what preprocessing transforms the image may have undergone, and part of the postprocessing purpose is to invert those transforms, ie letterboxing, scaling etc.
