### ISSUE TITLE
If I want to train on the whole dataset, can I put all images in the train folder and leave the val folder empty?

### ISSUE THREAD

**Issue by Zacchaeus00** [ultralytics/yolov5#273]
I have cross validated the model by splitting the data into train/val. Now I want to use all data for training, how can I implement this?

**Comment by yxNONG** [comment]
@Zacchaeus14 
the mAP is reported base on the result of val, 
you can train with putting whole image in train folder. for see the result, you still need to put some image in val

however, the image use to test is also use in train will cause the result reported not reliable (may be overfitting)

**Comment by Zacchaeus00** [comment]
thx!^^
