### ISSUE TITLE
Do you have a transformer version of the pre training model？

### ISSUE THREAD

**Issue by sbbug** [ultralytics/yolov5#2733]
## ❔Question
Hello，Do you have a transformer version of the pre training model？

## Additional context
I used the non transformer pre training model, and the effect was not good！

**Comment by glenn-jocher** [comment]
@sbbug no we don't have any pretrained models available. You can train https://github.com/ultralytics/yolov5/blob/master/models/hub/yolov5s-transformer.yaml either from scratch or from pretrained weights. If starting from pretrained weights all layers with matching names and shapes will transfer over:

```bash 
python train.py --cfg yolov5s-transformer.yaml  # from scratch
python train.py --cfg yolov5s-transformer.yaml --weights yolov5s.pt  # from pretrained
```

**Comment by sbbug** [comment]
Thank you!
But I have another question. If I add transformer module, will the training effect be good from zero，Compared with pre-training?

**Comment by glenn-jocher** [comment]
@sbbug pretrained models will improve initial training performance, though large datasets like COCO may eventually train to similar or better mAP when trained from scratch.

**Comment by TimGor1997** [comment]
> Thank you!
> But I have another question. If I add transformer module, will the training effect be good from zero，Compared with pre-training?

Hi, I also want to add transformer module, does it have a better mAP than which without transformer module? And, between pre-train with trained from scratch, which transformer have a better mAP?

**Comment by glenn-jocher** [comment]
@TimGor1997 I'm not sure. The official YOLOv5 models are all trained from scratch in 300 epochs, so if you want an apples to apples comparison you might train a Transformer model likewise from scratch.
