### ISSUE TITLE
small targets

### ISSUE THREAD

**Issue by limbo-zhj** [ultralytics/yolov5#2734]
Which network can detect small targets

**Comment by glenn-jocher** [comment]
@limbo-zhj all models can detect objects of all shapes. 

If you are looking for models more suited for smaller objects you may want to try the P2 output version here, or simply train and detect at larger image sizes using the default models.
https://github.com/ultralytics/yolov5/blob/master/models/hub/yolov5-p2.yaml

**Comment by sbbug** [comment]
Hi， @glenn-jocher 
What's "anchors: 3"??

**Comment by glenn-jocher** [comment]
@sbbug YOLOv5 models use anchors. The anchors field in the yaml files defines the number of anchors.

**Comment by sbbug** [comment]
Shouldn't it be defined as follows：
`anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32`

**Comment by limbo-zhj** [comment]
Thank you for your reply

**Comment by glenn-jocher** [comment]
@sbbug YOLOv5 yamls can define anchors directly:
```yaml
# anchors
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32
```

or indirectly (autoanchor will compute 3 anchors for each output layer):
```yaml
# anchors
anchors: 3
```

**Comment by limbo-zhj** [comment]
If use fixed anchors, it will also be automatically compute 3 anchors for each output layer

**Comment by glenn-jocher** [comment]
@limbo-zhj no, if you directly define anchors then they will be compared against your data by autoanchor. If they are a good match they will be used with no changes. If they are a poor match they will be ignored and new anchors automatically computed for you by autoanchor.

You can disable autoanchor and force the use of your manual anchors with
```bash
python train.py --noautoanchor
```

**Comment by ghost** [comment]
> @limbo-zhj all models can detect objects of all shapes.
> 
> If you are looking for models more suited for smaller objects you may want to try the P2 output version here, or simply train and detect at larger image sizes using the default models.
> https://github.com/ultralytics/yolov5/blob/master/models/hub/yolov5-p2.yaml

Hi everyone, I am interested in comparing yolov5 pretrained models with different anchors, and then, check the results obtained for model ensembling these trained models.

So, I am wondering if it will be possible to have the pretrained weights for the model (yolov5-p2.yaml) mentioned above.

**Comment by glenn-jocher** [comment]
@DRTorresRuiz there are no pretrained weights available for yolov5-p2.yaml. You can either train this model from scratch on COCO to get your own pretrained weights, or you can supply pretrained weights from a similar model, which will partially transfer (all layers with matching shapes and names).

**Comment by ghost** [comment]
Thanks for your answer, @glenn-jocher. Here I share the worst and best weight partial transfer (respectively) for yolov5-p2.yaml in case someone else need it :)

```
$> python train.py --cfg .\models\hub\yolov5-p2.yaml --weights .\weights\yolov5s.pt
. . .
Transferred 52/746 items from .\weights\yolov5s.pt
```

```
$> python train.py --cfg .\models\hub\yolov5-p2.yaml --weights .\weights\yolov5l.pt
. . .
Transferred 523/746 items from .\weights\yolov5l.pt
```

**Comment by glenn-jocher** [comment]
@DRTorresRuiz yes the YOLOv5l models will transfer the most layers because they are the same size as the YOLOv5-P2 models. Both of these use the same compound scaling constants here. You can modify these as you see if for smaller or larger models (see v5m, v5s for examples of smaller sizes).
https://github.com/ultralytics/yolov5/blob/1487bc84ff3babfb502dffb5ffbdc7e02fcb1879/models/yolov5l.yaml#L3-L4
