### ISSUE TITLE
Feature Request: Persistent W&B Logging 'Command' field

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/yolov5#2739]
## 🚀 Feature

Saving original run 'Command' in W&B rather than the latest run Command, or alternatively appending the most recent Command to a Commands list.

## Motivation

Resuming interrupted runs will cause the W&B logging to overwrite the original training command with the --resume training command. **Users won't be able to reproduce the run** as they've lost access to the original training command :(

See our 🌟💡 YOLOv5 Study: batch size #2452 for an example:
https://wandb.ai/glenn-jocher/batch_size

<img width="648" alt="Screen Shot 2021-04-08 at 6 16 38 PM" src="https://user-images.githubusercontent.com/26833433/114065045-86ddcb00-989a-11eb-88db-bd8ba04ec55e.png">

@AyushExel could you pass on this feature request to the W&B dev team?

**Comment by AyushExel** [comment]
@glenn-jocher Yup. This is a great feature request. I'll pass it on :)

**Comment by AyushExel** [comment]
@glenn-jocher this feature request is now merged into master https://github.com/wandb/client/pull/2280

**Comment by glenn-jocher** [comment]
@AyushExel great news, thanks!!
