### ISSUE TITLE
Can't convert to CoreML

### ISSUE THREAD

**Issue by karanjakhar** [ultralytics/yolov5#274]
```
TypeError: Error while converting op of type: Slice. Error message: Input shape not available 
 Please try converting with higher minimum_ios_deployment_target.
You can also provide custom function/layer to convert the model.
```
Conversion from yolov5s to onnx is smooth. But when I try to convert onnx to CoreML then above error occurs. Please help. Any guide how to use these models on ios.

**Comment by glenn-jocher** [comment]
@karanjakhar we have updated `export.py` a bit to better support the 3 export channels (ONNX, TorchScript and CoreML).  See #251 for a tutorial on how to use export.py. Note that export.py is mainly a guide that provides simple first steps for users like yourself to begin creating your own export pipelines though, it does not provide end-to-end export functionality.

We do offer paid end-to-end export services however, as well as providing reference apps for iOS and Android to use your exported models in. If you have a business idea for YOLOv5 at the edge, we'd be happy to help you get started! You can email glenn.jocher@ultralytics.com for details if interested.

**Comment by Mayur2992** [comment]
> ```
> TypeError: Error while converting op of type: Slice. Error message: Input shape not available 
>  Please try converting with higher minimum_ios_deployment_target.
> You can also provide custom function/layer to convert the model.
> ```
> 
> Conversion from yolov5s to onnx is smooth. But when I try to convert onnx to CoreML then above error occurs. Please help. Any guide how to use these models on ios.

**help me if you figured out the problem!!**
Thanks in advance!
