### ISSUE TITLE
W&B Bug Report: This run didn't log images for key "Results", step 3, index 1

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/yolov5#2740]
## 🐛 Bug
Default W&B logging does not work correctly.

## To Reproduce (REQUIRED)
In Colab Notebook: https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

1. Run Setup cell
2. Run W&B login cell
3. Run Train cell

View bug at W&B console: https://wandb.ai/glenn-jocher/YOLOv5
<img width="1274" alt="Screenshot 2021-04-08 at 23 42 24" src="https://user-images.githubusercontent.com/26833433/114100122-206da280-98c4-11eb-8101-0aeaae583c48.png">

**Comment by glenn-jocher** [comment]
@AyushExel could you take a look at this? This is the first time I've started a training run since the recent updates. I just ran the Colab Notebook with no changes. Artifact uploads correctly on training completion, and metrics display, but no images appear. See https://wandb.ai/glenn-jocher/YOLOv5

**Comment by AyushExel** [comment]
@glenn-jocher I cannot reproduce this. I think maybe the run didn't sync because if you open the[ files tab of the run that you've linked](https://wandb.ai/glenn-jocher/YOLOv5/runs/23u3uq0x/files?workspace=), you'll see that there are no files there. So, probably, the images didn't get uploaded due to internet issue or something else. Is this happening every time you try to run a run?

**Comment by AyushExel** [comment]
@glenn-jocher Can you please confirm if you're seeing these issues ?

**Comment by glenn-jocher** [comment]
@AyushExel yeah buddy, still seeing these. I checked the run log and it says it uploaded '113 media files'. The link for this run is https://wandb.ai/glenn-jocher/YOLOv5/runs/yu0niihm. I also checked the local runs/train/exp directory and everything looks good locally.
<img width="1875" alt="Screenshot 2021-04-09 at 12 52 56" src="https://user-images.githubusercontent.com/26833433/114169962-87c23b80-9932-11eb-982c-67f918789221.png">

**Comment by glenn-jocher** [comment]
@AyushExel closing this as duplicate of #2741, let's focus the conversation there.

**Comment by METGALALA** [comment]
can i aks for some question ?if your problem has solved?

**Comment by glenn-jocher** [comment]
@METGALALA yes, feel free to ask your question. If you have a separate issue, please go ahead and share the details.
