### ISSUE TITLE
weight and bias‘s value in onnx are different from value dumped by python script 

### ISSUE THREAD

**Issue by zhvn100** [ultralytics/yolov5#2744]
## ❔Question
weight and bias‘s value in onnx are different from value dumped by python script 

## Additional context
The  python script is  as follow:
![image](https://user-images.githubusercontent.com/56665570/114135918-83028500-993c-11eb-9563-4c6a6df72235.png)
The onnx is  is obtained through the official tutorial .  For example , the first conv bias in onnx are as follow:
![image](https://user-images.githubusercontent.com/56665570/114136068-b80ed780-993c-11eb-9ae7-04215082fc22.png)
Through python script,i get bias too,and as follow:
![image](https://user-images.githubusercontent.com/56665570/114136186-e68cb280-993c-11eb-8e0c-145cc6da2616.png)
The bias values of the two sides are different ，and weight is different too . So please tell me why this situation occur.

**Comment by glenn-jocher** [comment]
@zhvn100 attempt_load() in export.py
https://github.com/ultralytics/yolov5/blob/c03d590320ea875a9ce5288c077a9ce5c7a1c160/models/export.py#L38

has an automatic fuse operation, so you are likely comparing the parameter values of a fused YOLOv5 model to an unfused YOLOv5 model, which may explain the difference.
https://github.com/ultralytics/yolov5/blob/c03d590320ea875a9ce5288c077a9ce5c7a1c160/models/experimental.py#L113-L134

**Comment by zhvn100** [comment]
@glenn-jocher   i  know that conv's weight value in onnx is  through bn fusion , but it's value is still not equal to weight multiply bn's weight. And the bn bias should be equal to conv bias ,because the bias of conv in yolov5 is set by false.

**Comment by glenn-jocher** [comment]
@zhvn100 you may want to see the fuse function for a full understanding of how the bias term is handled:
https://github.com/ultralytics/yolov5/blob/b5de52c4cdfefb3c7acfbff7d7f450a46b4aaada/utils/torch_utils.py#L181-L201

**Comment by zhvn100** [comment]
@glenn-jocher  thank you for your answer，i find my mistake

**Comment by zhvn100** [comment]
@glenn-jocher  thank you for your answer.  i find my mistake. But according to fuse_conv_and_bn's operation , i compute weight 
 and bias as follow: 
bn_weight * weight / math.sqrt(bn_running_var + eps)  
bn_bias - bn_weight * bn_running_mean / math.sqrt(bn_running_var + eps)
the result is a bit different , such as the first weight i compute is 0.08859554400285376, and the first weight in onnx is 0.08344794064760208.  The first bias i compute is 2.435224160192666, and the first bias in onnx is 2.431384563446045.
i wonder whether this error is caused by onnx export

**Comment by glenn-jocher** [comment]
@zhvn100 I'm not sure, the exact values will depend on the precision of the variables used in the operations, so it's possible numerical precision is causing your differences, i.e. exporting FP32 vs FP16 models?
