### ISSUE TITLE
CoreML Question

### ISSUE THREAD

**Issue by KangHoyong** [ultralytics/yolov5#2745]
## ❔Question

We converted the yolov5s model to coreML using export.py. However, classname was not created.

So in the code section
```
model = ct.convert(ts, inputs=[ct.ImageType(name='image', shape=img.shape, scale=1 / 255.0, bias=[0, 0, 0])], classifier_config=ct.ClassifierConfig(labels))
```
created by adding

However, Preview did not detect the object. What is the problem?

**Comment by topslave** [comment]
On the same topic, where can I find detailed tutorial on yolov5, I am trying to create an app that is very similar to the sample app you have on the AppStore, any help would be appreciated 
Regards
