### ISSUE TITLE
Backbone, Neck, Head ?

### ISSUE THREAD

**Issue by robertokcanale** [ultralytics/yolov5#2753]
## ❔Question
Hi, could you please provide the  backbone, neck and head used? I need this information for my thesis. Thanks

**Comment by glenn-jocher** [comment]
@robertokcanale model architectures are displayed in each model's yaml file:
https://github.com/ultralytics/yolov5/blob/b5de52c4cdfefb3c7acfbff7d7f450a46b4aaada/models/yolov5s.yaml#L1-L48
