### ISSUE TITLE
Empty outputs during inference 

### ISSUE THREAD

**Issue by johanenforcer** [ultralytics/yolov5#2754]
## ❔Question
Why are my tensor detection outputs null when im using pytorch hub to load a custom model configuration?

## Additional context
I use torch.save in order to save the model.pt during training and then load it according to how the pytorch hub tutorial does it. These are the detection outptus per image that I receive: tensor([], device='cuda:0', size=(0, 6))

**Comment by glenn-jocher** [comment]
@johanenforcer if inference runs without error then everything is working correctly.

There is no guarantee of any detections. If your model fails to detect objects in your images it is simply not capable of detecting objects at the inference parameters you have used. You can modify your inference parameters or retrain your model.
