### ISSUE TITLE
W&B Bug Report: print() output missing from Logs panel

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/yolov5#2756]
## 🐛 Bug
@AyushExel I noticed that`print()` output is missing now from the W&B 'Logs' panel, only `logger.log()` output is showing.

## To Reproduce (REQUIRED)
Train a YOLOv5 model with W&B logging. Current Logs panel looks like this from activations study, with only `logger.log()` output showing in red:
https://wandb.ai/glenn-jocher/activations
<img width="1419" alt="Screenshot 2021-04-10 at 15 46 50" src="https://user-images.githubusercontent.com/26833433/114272002-7baeaa80-9a14-11eb-976c-8ec9ed987850.png">

Previously print() outputs in white also appeared, i.e. the test metrics at the end of each epoch below in batch-size study. Now we can't see these metrics or any other console output created by print().
https://wandb.ai/glenn-jocher/batch_size
<img width="1419" alt="Screenshot 2021-04-10 at 15 46 52" src="https://user-images.githubusercontent.com/26833433/114272005-7cdfd780-9a14-11eb-8c24-4d72aa5387a8.png">

**Comment by AyushExel** [comment]
@glenn-jocher I just ran a run from the current master branch here https://wandb.ai/cayush/print_test/runs/2mrxr4ui/logs?workspace=user-cayush
This seems alright to me?
Is this a colab problem? I'm using linux for this run

**Comment by glenn-jocher** [comment]
@AyushExel ah sorry I forgot to mention, the activations study runs are in a Docker container on a GCP VM, not Colab.

If I look at my colab run from yesterday I do see the print() statements in white:
https://wandb.ai/glenn-jocher/bug/runs/3vl5t6af

So this seems to be isolated to Docker environments. I should check to make sure the Docker environment is actually printing the white lines to screen, hold on I'll do that now.

**Comment by AyushExel** [comment]
@glenn-jocher sure. And thanks for pointing this out. If this is a bug in CLI related to docker, I'll let the engineers know

**Comment by glenn-jocher** [comment]
@AyushExel I'm running an experiment, just started another GCP instance and pulling the YOLOv5 Docker image now. I'm going to train one model same as Colab example, to bug_docker project, and then train another using the same command as the activations study, which append `> /dev/null 2>&1 &` to the training commands. This runs them in the background for easier starting of subsequent runs, but it also redirects output to dev/null, not sure if that's treating print() and logger.log() differently or not.

```
python train.py --img 640 --batch 16 --epochs 3 --data coco128.yaml --weights yolov5s.pt --nosave --cache --project bug_docker
python train.py --img 640 --batch 16 --epochs 3 --data coco128.yaml --weights yolov5s.pt --nosave --cache --project bug_docker > /dev/null 2>&1 &
```

**Comment by glenn-jocher** [comment]
@AyushExel experiment result:

## Train in Docker normally
https://wandb.ai/glenn-jocher/bug_docker/runs/65rp31qs
```
python train.py --img 640 --batch 16 --epochs 3 --data coco128.yaml --weights yolov5s.pt --nosave --cache --project bug_docker --name default
```
<img width="1574" alt="Screenshot 2021-04-10 at 17 34 32" src="https://user-images.githubusercontent.com/26833433/114275521-20d07f80-9a23-11eb-9f53-e01314d5c10d.png">


## Train in Docker dev/null in background
https://wandb.ai/glenn-jocher/bug_docker/runs/2oyoy4js
```
python train.py --img 640 --batch 16 --epochs 3 --data coco128.yaml --weights yolov5s.pt --nosave --cache --project bug_docker --name devnull > /dev/null 2>&1 &
```
<img width="1574" alt="Screenshot 2021-04-10 at 17 34 49" src="https://user-images.githubusercontent.com/26833433/114275524-2332d980-9a23-11eb-8189-3fbcf45d8f47.png">


Oh, ok so the white print() statements aren't lost, they're all bunched up together at the end for some reason. But the change must have to do with the `> /dev/null 2>&1 &` suffix on the command.

**Comment by AyushExel** [comment]
@glenn-jocher awesome. So, this isn't a CLI issue
