### ISSUE TITLE
Using custom pre-trained model weights for transfer learning with different classes return RuntimeError: The size of tensor a (24) must match the size of tensor b (30) at non-singleton dimension 0

### ISSUE THREAD

**Issue by shining-love** [ultralytics/yolov5#2757]
Before submitting a bug report, please be aware that your issue **must be reproducible** with all of the following, otherwise it is non-actionable, and we can not help you:
 - **Current repo**: run `git fetch && git status -uno` to check and `git pull` to update repo
 - **Common dataset**: coco.yaml or coco128.yaml
 - **Common environment**: Colab, Google Cloud, or Docker image. See https://github.com/ultralytics/yolov5#environments
 
If this is a custom dataset/training question you **must include** your `train*.jpg`, `test*.jpg` and `results.png` figures, or we can not help you. You can generate these with `utils.plot_results()`.

## 🐛 Bug

I found a very interesting question.That is, when you first train a collection of images with a small number of categories to get the model model_1.pt,
Then I use this model to train a collection of images with a large number of categories and get an error like this:
"The size of Tensor A (24) must match The size of Tensor B (30) at non-singleton dimension 0"
But conversely, there is no problem for a model trained by a large number of categories to migrate to a small number of images.

## To Reproduce (REQUIRED)

Input:
```
import torch

a = torch.tensor([5])
c = a / 0
```

Output:
```
Traceback (most recent call last):
  File "/Users/glennjocher/opt/anaconda3/envs/env1/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-be04c762b799>", line 5, in <module>
    c = a / 0
RuntimeError: ZeroDivisionError
```

## Environment

 - OS: [e.g. Ubuntu]
 - GPU [e.g. 2080 Ti]

**Comment by shining-love** [comment]
like this issues: https://github.com/ultralytics/yolov5/issues/2158

**Comment by glenn-jocher** [comment]
@yang-gis closing as duplicate, please comment on #2158 if you are still having issues, thank you.
