### ISSUE TITLE
Android app cannot load YOLOv5 TorchScript weights

### ISSUE THREAD

**Issue by nmd2k** [ultralytics/yolov5#2760]
# Android app cannot load YOLOv5 TorchScript weights
Please help! I'm using the YOLOv5 to train my custom problem of detecting number in electrical meter.
While the model ran perfectly in my computer, its generated weights by using `models/export.py` can not be load in an android app.

## 👨‍💻 Detail: 
I was following [this tutorial android app repository](https://github.com/pytorch/android-demo-app/tree/master/ObjectDetection) to create a demo application on Android for my task (which takes electrical meter as input and returns the number detected like shown):

![image](https://i.ibb.co/ZTtqDpv/test.png)

I was following the instruction of converting the model's weights into torchscript in the [android-demo-app repository](https://github.com/pytorch/android-demo-app/tree/master/ObjectDetection) exactly. 
- set `model.model[-1].export = False`
- add mobile optimizer like below: 
``` 
    ts = torch.jit.trace(model, img)
    from torch.utils.mobile_optimizer import optimize_for_mobile
    ts = optimize_for_mobile(ts)
    ts.save(f)
```

And the converting process was success fully with a `TracerWarning`:
```
TracerWarning: 
Encountering a list at the output of the tracer might cause the trace to be incorrect, this is only valid if the container structure does not change based on the module's inputs. 
Consider using a constant container instead (e.g. for `list`, use a `tuple` instead. for `dict`, use a `NamedTuple` instead). 
If you absolutely need this and know the side effects, pass strict=False to trace() to allow this behavior.
```
### However, the model was not able to load to the app
Using `PyTorch.loadModuleFromAsset` to load the torchscript weight, the application get error and keep run into an `force stopping` scenario. I cloned the `ObjectDetection` application in [pytorch/android-demo-app/](https://github.com/pytorch/android-demo-app/), pasted the torchscript weight into `app/src/main/assets` and ran without any changes. The output log:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.pytorch.demo.objectdetection, PID: 25271
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.pytorch.demo.objectdetection/org.pytorch.demo.objectdetection.MainActivity}:  
com.facebook.jni.CppException: [enforce fail at inline_container.cc:145] . PytorchStreamReader failed reading zip archive: failed finding central directory

    Caused by: com.facebook.jni.CppException: [enforce fail at inline_container.cc:145] . PytorchStreamReader failed reading zip archive: failed finding central directory
```
This is the same as [this issue](https://github.com/pytorch/android-demo-app/issues/16). But I've checked the torch, torchvision and pytoch_android version whether they were incompatible or not. (which is not). 

Suggestion by pytorch docs about `Mix Tracing and Scripting` (I have no idea what I'm doing 😢). I was changing  `models/export.py` like below, then somehow the application **overcome** the `force stopping` scenarios, which means the model now can be load into the app, i guess? 🤔. 
```
        ts = torch.jit.trace(model, img)
        ts = torch.jit.script(ts)
        from torch.utils.mobile_optimizer import optimize_for_mobile
        ts = optimize_for_mobile(ts)
        ts.save(f)
```
Then it ran into another issue `IllegalStateException: Expected IValue type 7, actual type 11` but I don't thing the app has any problem. I've already tried to use the `yolov5s.torchscript.pt` that they provided in the repository and it worked perfectly, but when converting the original `yolov5s.pt` to torchscript type by using `models/export.py` force the app come into `stopping` scenarios.

### Is there any problem with the `models/export.py`, or it just my weight ☠. 
Please help 🙏

## 🌲Environment
Torch version: 1.8.1
Torchvision version: 0.9.1
Torch android version: 1.8.0
Torchvision android version: 1.8.0

OS: Windows 10
GPU: 1660 Super
Android Studio: 4.1.3
Java JDK: 16
Python: 3.9.2

**Comment by glenn-jocher** [comment]
@manhdung20112000 oh wow! I didn't know PyTorch did their official Android demo app with YOLOv5. That's super cool. 

@SergioSanchezUltralytics might be able to give some advice.

Another option is the TFLite export and Android app deployment PR here:
https://github.com/ultralytics/yolov5/pull/1127

**Comment by zhiqwang** [comment]
Hi @manhdung20112000 I think the following script is not the correct usage of "Mix Tracing and Scripting".

```python
ts = torch.jit.trace(model, img)
ts = torch.jit.script(ts)  # This line repeats the above
from torch.utils.mobile_optimizer import optimize_for_mobile
ts = optimize_for_mobile(ts)
ts.save(f)
```

As `torch.jit.trace` have done all the work you need.

**Comment by nmd2k** [comment]
Thanks, I've solved the problem by using the old version of `models/export.py` commits on Oct 6, 2020. 
(Sr, I don't know how to attach it in here 😢)

I wonder if the `device` was the main reason. Notice that the model was trained by `Tesla T40` on Google Colab and converted to Torch Script by my local laptop with `cpu` as device option. Thus, the torch script weights didn't work, but when I try to convert the model with Google Colab GPU (using old version of `export.py`) the problem has gone and no `IllegalStateException: Expected IValue type` shows up. 🎉

I found that there are 2 differences in the old version of `export.py`, 1 is how which device that they use to load the model, 2 is how the model get update:
**Old version**
```
    # Input
    img = torch.zeros((opt.batch_size, 3, *opt.img_size))  # image size(1,3,320,192) iDetection
    # Load PyTorch model
    model = attempt_load(opt.weights, map_location=torch.device('cpu'))  # load FP32 model
    # Update model
    for k, m in model.named_modules():
        m._non_persistent_buffers_set = set()  # pytorch 1.6.0 compatibility
        if isinstance(m, models.common.Conv) and isinstance(m.act, nn.Hardswish):
            m.act = Hardswish()
```

**Current**
```
    # Load PyTorch model
    device = select_device(opt.device)
    model = attempt_load(opt.weights, map_location=device)  # load FP32 model
    # Input
    img = torch.zeros(opt.batch_size, 3, *opt.img_size).to(device)  # image size(1,3,320,192) iDetection
    # Update model
    for k, m in model.named_modules():
        m._non_persistent_buffers_set = set()  # pytorch 1.6.0 compatibility
        if isinstance(m, models.common.Conv):  # assign export-friendly activations
            if isinstance(m.act, nn.Hardswish):
                m.act = Hardswish()
            elif isinstance(m.act, nn.SiLU):
                m.act = SiLU()
```

**Comment by ghost** [comment]
@manhdung20112000 thanks for raising an issue! We were not aware of the PyTorch YOLOv5 android demo, but are currently taking a look and should hopefully be able to provide better deployment support in the future. Keep us updated on your progress, your use case looks really interesting!

**Comment by nmd2k** [comment]
Thanks, I really appreciate your help. Everything works perfectly so far, therefore I'll close this issues.
Once again, thanks!
