### ISSUE TITLE
Limiting the number of classes in training dataset

### ISSUE THREAD

**Issue by Micky-123** [ultralytics/yolov5#2763]
## ❔Question
Hello,
If I am interested in training with limited classes, lets say 30 or 40 classes out of 80 classes of Coco dataset. What would be the modifications in the code that I would have to do? Will it be OK if annotations are still of all the 80 classes while I am training only for 30/40 classes? In general, can we expect better accuracy while training with fewer classes but with same dataset?
Thanks

**Comment by glenn-jocher** [comment]
@Micky-123 I would say that yes, it's pretty obvious that finite resources spread over many tasks will perform worse than the same resources applied to fewer tasks, for most any ML problem across domains, and for human beings also.

There's no shortcut here to train on a subset of labels other than modifying your labels. You can filter inference results by specific classes if you want without retraining, but this will not improve the performance of these classes:
```shell
python detect.py --classes 0 1 2 3
```

**Comment by Micky-123** [comment]
Thanks glenn. By 'Modifying your labels' - you mean modifying the dataset annotations for all the images or do you mean that in training module, I can suggest as what labels should be picked for training and what not.

**Comment by glenn-jocher** [comment]
@Micky-123 modifying your labels means changing your labels.
