### ISSUE TITLE
Question about P5

### ISSUE THREAD

**Issue by lujiazho** [ultralytics/yolov5#2765]
## ❔Question
It's very amazing that yolov5 has a new version! I found that P5 is a retrained version of P4 with the same architecture, but I didn't get what makes the retraining process necessary or P5 is better than P4? 

No offense, I just don't understand, hope for your reply!

**Comment by glenn-jocher** [comment]
@leaving-voider yes the new v5.0 release retrains the same P5 models as before in v4.0 release, and introduces new P6 models. 

The retraining of the P5 models use slightly different hyperparameters, in particular higher scale jitter of 0.9, as the EfficientDet paper demonstrates works well for longer trainings and larger models:
https://arxiv.org/abs/1911.09070

**Comment by lujiazho** [comment]
got it! thanks a lot!

**Comment by xinxin342** [comment]
@leaving-voider what's the mean of ‘in particular higher scale jitter of 0.9,’？
