### ISSUE TITLE
when I set devices to 0, the train.py uses all GPUs

### ISSUE THREAD

**Issue by jieruyao49** [ultralytics/yolov5#2767]
## ❔Question
when I set devices to 0, the train.py uses all GPUs(There are nine GPUs),The training instructions are as follows:
` python train.py --data /home/code/yolov5-master/data/coco128.yaml --cfg /home/code/yolov5-master/models/yolov5s.yaml --weights /home/code/yolov5-master/yolov5s.pt --batch-size 63 --device 1`

My package as follows:
_libgcc_mutex             0.1                        main    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ca-certificates           2021.1.19            h06a4308_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
certifi                        2020.12.5        py38h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cudatoolkit               10.1.243             h6bb024c_0    <unknown>
ld_impl_linux-64          2.33.1               h53a641e_7    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libffi                          3.3                  he6710b0_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgcc-ng                 9.1.0                hdf63c60_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libstdcxx-ng              9.1.0                hdf63c60_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ncurses                   6.2                  he6710b0_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
numpy                     1.20.2                    <pip>
openssl                   1.1.1k               h27cfd23_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
Pillow                    8.2.0                     <pip>
pip                       21.0.1           py38h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
python                    3.8.8                hdb3f193_4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
readline                  8.1                  h27cfd23_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
setuptools                52.0.0           py38h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
sqlite                    3.35.4               hdfb4753_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tk                        8.6.10               hbc83047_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
torch                     1.7.1+cu101               <pip>
torchvision               0.8.2                     <pip>
typing-extensions         3.7.4.3                   <pip>
wheel                     0.36.2             pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
xz                        5.2.5                h7b6447c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
zlib                      1.2.11               h7b6447c_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main

absl-py                0.12.0
cachetools             4.2.1
certifi                2020.12.5
chardet                4.0.0
cycler                 0.10.0
Cython                 0.29.22
google-auth            1.28.1
google-auth-oauthlib   0.4.4
greenlet               1.0.0
grpcio                 1.37.0
idna                   2.10
kiwisolver             1.3.1
Markdown               3.3.4
matplotlib             3.3.4
mkl-fft                1.3.0
mkl-random             1.1.1
mkl-service            2.3.0
numpy                  1.20.2
oauthlib               3.1.0
olefile                0.46
opencv-python          4.5.1.48
pandas                 1.2.3
Pillow                 8.2.0
pip                    21.0.1
protobuf               3.15.8
pyasn1                 0.4.8
pyasn1-modules         0.2.8
pycairo                1.19.1
pycocotools            2.0.2
pyparsing              2.4.7
python-dateutil        2.8.1
pytz                   2021.1
PyYAML                 5.4.1
reportlab              3.5.66
requests               2.25.1
requests-oauthlib      1.3.0
rsa                    4.7.2
scipy                  1.6.2
seaborn                0.11.1
setuptools             52.0.0.post20210125
six                    1.15.0
SQLAlchemy             1.4.5
tensorboard            2.4.1
tensorboard-plugin-wit 1.8.0
thop                   0.0.31.post2005241907
torch                  1.7.1+cu101
torchvision            0.8.2
tornado                6.1
tqdm                   4.60.0
typing-extensions      3.7.4.3
urllib3                1.26.4
Werkzeug               1.0.1
wheel                  0.36.2

**Comment by glenn-jocher** [comment]
@jieruyao49 this should be fixed in PR https://github.com/ultralytics/yolov5/pull/2750 a few days ago. Please git pull or reclone and try again, thank you!

**Comment by jieruyao49** [comment]
> @jieruyao49 this should be fixed in PR #2750 a few days ago. Please git pull or reclone and try again, thank you!

thanks,when i download the new code, i solved it
