### ISSUE TITLE
Stochastic Weighted Average (SWA) for YOLOv5

### ISSUE THREAD

**Issue by ryan994** [ultralytics/yolov5#2768]
## 🚀 Feature
SWA Object Detection

## Motivation

Hello, recently I read a research, SWA Object Detection, https://arxiv.org/abs/2012.12645. And I tried to use this method in yolov5, it worked! Is it possibel to add it in the future?

**Comment by glenn-jocher** [comment]
@ryan994 YOLOv5 uses an EMA model, which is very similar to the SWA method. We tried to implement SWA as well but were not able to produce performance gains beyond the current EMA model.

See SWA PR https://github.com/ultralytics/yolov5/pull/807 and original SWA issue https://github.com/ultralytics/yolov5/issues/793.

**Comment by ryan994** [comment]
@glenn-jocher Hi, I read swa pr #807, I found you only try to calculate BN. I tried to merge all weights, there was a little improvement. I saved all the best checkpoints, and merged last 4 to a new checkpoint.

**Comment by glenn-jocher** [comment]
@ryan994 can you quantify your results in comparison to the baseline results?

**Comment by xinxin342** [comment]
@ryan994 how to merged last 4 to a new checkpoints？
