### ISSUE TITLE
Can i convert this torch-yolo to tensortRT ?

### ISSUE THREAD

**Issue by tienhoang1094** [ultralytics/yolov5#277]
I have failed with this https://github.com/NVIDIA-AI-IOT/torch2trt.
 thanks
![image](https://user-images.githubusercontent.com/58082063/86442934-b292ba00-bd38-11ea-8201-4f012a08d498.png)

**Comment by glenn-jocher** [comment]
See https://github.com/TrojanXu/yolov5-tensorrt
