### ISSUE TITLE
Question about best.pt

### ISSUE THREAD

**Issue by ferro07** [ultralytics/yolov5#2773]
Hey @glenn-jocher,

Thanks for the nice explanation and sharing.
I work on medical data and

https://github.com/ultralytics/yolov5/blob/1487bc84ff3babfb502dffb5ffbdc7e02fcb1879/utils/metrics.py#L12
w = [0.0, 0.0, 0.1, 0.9] # weights for [P, R, mAP@0.5, mAP@0.5: 0.95]

Instead of mAP@0.5, and  mAP@0.5: 0.95, I just want to focus on F1. For this,  I made this change, w = [0.5, 0.5, 0.0, 0.0], but I don't get the best weights. What should I do for F1.
Thanks.

**Comment by glenn-jocher** [comment]
@ferro07 the best.pt is saved at maximum fitness. You're free to customize the fitness function to whatever metrics you'd like. For F1 see https://en.wikipedia.org/wiki/F-score
