### ISSUE TITLE
Changing batch size ratio

### ISSUE THREAD

**Issue by RobinBram** [ultralytics/yolov5#2777]
I'm trying to train a model similar to the noisy student approach and they have a batch size ratio between GT and pseudo Labels. Is there a simple way to take more images from a certain folder when loading the images. I have one folder with GT and one with PL and train simultanously on both but I want to take more samples from the PL folder than from the GT folder.

**Comment by glenn-jocher** [comment]
@RobinBram see this section of code for an example of modifying dataset.indices to accomplish a redistribution of your dataset sampling.
https://github.com/ultralytics/yolov5/blob/1487bc84ff3babfb502dffb5ffbdc7e02fcb1879/train.py#L252-L265

**Comment by RobinBram** [comment]
In which order are the images loaded if I have specified two folders as the train data? 
train: 
 - ../Data/yolo/images/train/
 - ../Data/Pseudolabelling/precisionrecall99
val: ../Data/yolo/images/val/

**Comment by glenn-jocher** [comment]
@RobinBram in the order you supply them.
