### ISSUE TITLE
What is the correct way to Pseudo-label?

### ISSUE THREAD

**Issue by samf1986** [ultralytics/yolov5#2778]
## ❔Question
I'm trying to implement pseudo-labeling with yolov5 by predicting labels for unlabeled data at a high confidence level (e.g. 0.9). However most of my images have multiple true positives, so I'm concerned that if I add this "student" data as is, I will be adding many false negatives to the training set. I haven't found any resources addressing this issue, so my provision solution was to black out all regions of the images not within a pseudo-label bounding box before adding the images to the training set. 

Is this correct? Do false negatives in the training set actually cause problems in Yolov5?

**Comment by glenn-jocher** [comment]
@samf1986 I don't understand your question, but in general yes, incorrect labels will negatively affect your training results.

**Comment by ShirleyHe2020** [comment]
> ## ❔Question
> I'm trying to implement pseudo-labeling with yolov5 by predicting labels for unlabeled data at a high confidence level (e.g. 0.9). However most of my images have multiple true positives, so I'm concerned that if I add this "student" data as is, I will be adding many false negatives to the training set. I haven't found any resources addressing this issue, so my provision solution was to black out all regions of the images not within a pseudo-label bounding box before adding the images to the training set.
> 
> Is this correct? Do false negatives in the training set actually cause problems in Yolov5?

I have same interest in pseudo-labeling, do you have any progress up to now?
