### ISSUE TITLE
What is the metric of the "best" weights?

### ISSUE THREAD

**Issue by Zacchaeus00** [ultralytics/yolov5#278]
Hey guys,
After training, a **best**_model_name.pt is generated in the ./weights folder. I am curious about how yolov5 picks the best weights among all epochs (is it mAP@0.5 or precision)? Moreover, can we customize the metric?

Thank you in advance!!

**Comment by glenn-jocher** [comment]
Best fitness.

https://github.com/ultralytics/yolov5/blob/3bdea3f697d4fce36c8e24a0701c0f419fa8f63a/utils/utils.py#L869-L873

**Comment by Zacchaeus00** [comment]
Now I'm clear, thank you!

**Comment by JiaLim98** [comment]
Good day, @glenn-jocher!

I wonder why are the weights for P, R, mAP@0.5 and mAP@0.5:0.95 unequal? Aren't they all equally important when determining the best weights? For example, [0.25, 0.25, 0.25, 0.25].

Regards,
JiaLim98

**Comment by glenn-jocher** [comment]
@JiaLim98 you're free to modify this as you see fit.
