### ISSUE TITLE
youtube framerate and loop issues

### ISSUE THREAD

**Issue by ashleyha** [ultralytics/yolov5#2781]
## 🐛 Bug
The framerate and endless loop issues mentioned in #2752 still persist. I've tried the new feature on a few videos; when the video ends it continues to detect on black frames. Also, the output .mp4 plays back very quickly.

## To Reproduce (REQUIRED)
`python3 detect.py --weights weights/yolov5m.pt --source 'https://www.youtube.com/watch?v=9bTTtTuYfcc'`

## Environment
 - OS: MacOS
 - CPU

**Comment by glenn-jocher** [comment]
@ashleyha thanks buddy. It seems your video example is only available in the US, but the first issue is known, the second is new information though, thanks for letting us know.

```bash
OSError: ERROR: The uploader has not made this video available in your country.
This video is available in Guam, Northern Mariana Islands, Puerto Rico, United States, Virgin Islands, U.S..
You might want to use a VPN or a proxy server (with --proxy) to workaround.
(venv) (base) glennjocher@Glenns-iMac yolov5-export % 
```
