### ISSUE TITLE
Why does yolov5s is much smaller than yolov5m but whose inference time remains almost the same?

### ISSUE THREAD

**Issue by August0424** [ultralytics/yolov5#2784]
## ❔Question
I put the picture of offiacially announced performance from https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data, which is shown as below:
![图片](https://user-images.githubusercontent.com/54147016/114646274-8cf60080-9d0d-11eb-8417-7e11d830da8e.png)

As it suggests, the model size of yolov5s is only 14M, while that of yolov5m and yolov5l is 41M and 90M respectively. Why does the inference speed of yolov5s (2.2ms) fail to gain a considerable improvement compared that of yolov5m (2.9ms) and yolov5l (3.8ms)? Obviously, the acceleration from 2.9ms/3.8ms (yolov5m/yolov5l) to 2.2ms (yolov5s) is fairly not proportionate to the extent of model size compression from 41M/90M to (yolov5m/yolov5l) 14M (yolov5s). How to explain this result?

I asked this question because I tried to further prune (using network slimming) yolov5s for more inference acceleration but ended with no pronounced positive effect whereas the model size had decreased from 14M to 5M and the FLOPS had also largely reduced. Does this phenomenon indicate that there exists no more space for yolov5s to gain remarkable improvement of inference speed by ordinary pruning method?

Looking forward to your reply. Thanks a lot!

**Comment by glenn-jocher** [comment]
@August0424 well no, I don't have explanations for every phenomenon in the YOLOv5 world, but clearly there are components to the speeds that are independent of model size/parameter count, like NMS, grid addition and anchor application in the Detect layer, etc. 

Also these results are for PyTorch inference, deployed solutions will provide their own speeds that will differ from the above as well (TensorRT, CoreML, TFLite, TF JS etc.), and quantization may or may not also affect the speeds.

I'd suggest you use a profiler like Spyder Line profiler or the PyTorch profiler for a better understanding of the temporal constraints you are running into with smaller models.
