### ISSUE TITLE
How to use TransformerBlock in common.py?

### ISSUE THREAD

**Issue by jkkkc** [ultralytics/yolov5#2786]
## ❔Question
just modify C3 in the .yaml file to C3TR? Is there anything else that needs to be changed?

**Comment by glenn-jocher** [comment]
@jkkkc yes you can replace any C3 module with a C3 Transformer module (C3TR). Nothing else needs to be changed, but be careful as these transformer modules are very resource intensive, they require a lot of free CUDA memory.
