### ISSUE TITLE
Resizing the x and y coordinates as the inference result according to the ratio of the original image

### ISSUE THREAD

**Issue by leeyunhome** [ultralytics/yolov5#2789]
## ❔Question

Since the image is scaled when learning, is it correct to resize the x and y coordinates as the inference result to match the ratio of the original video when displaying?

The increasing number is expressed in the x, y font size.

![image](https://user-images.githubusercontent.com/59910227/114676835-ae261380-9d44-11eb-9a81-692e7a9af7f2.png)

**Comment by glenn-jocher** [comment]
@leeyunhome I'm sorry I don't understand your question despite the nice graphics. 

For best results you should train and detect at the same image sizes, i.e. in your example above 416 is the closest 32-multiple to 400 so:
```
python train.py --img 416
python detect.py --img 416
```
