### ISSUE TITLE
mAP@.5 COCO test-dev2017  

### ISSUE THREAD

**Issue by yinyuhangi** [ultralytics/yolov5#2790]
Can you provide mAP@0.5 of YOLOv5s on COCO test-dev2017?

**Comment by GiorgioSgl** [comment]
| Resolution | FPS | mAP | mAP50 | mAP75 | mAP_small | mAP_medium | mAP_large |
| ---- | --- | -- | -- | -- | -- | -- | -- | 
| 640 | 0.5 | 0.35 | 0.54 | 0.37 | 0.15 | 0.34 | 0.46 |
| 416 | 1 | 0.32 | 0.50 | 0.33 | 0.08 | 0.29 | 0.48 |
| 320 | 1.6 | 0.29 | 0.46 | 0.30 | 0.05 | 0.23 | 0.47 |

That's are mine result actually, hope they can help
I have calculate the FPS on raspberry pi4
These results are on VAL, not test if I rember well. I'm really sorry.

**Comment by yinyuhangi** [comment]
Thanks. What graphics card are you using? Is the unit of the parameter in the FPS column in ms?

**Comment by GiorgioSgl** [comment]
I'm not using any graphic card, it is on raspberry pi4.
And they are Frame Per Second so in second and not ms.

**Comment by yinyuhangi** [comment]
Ok. Thank you very much.

**Comment by glenn-jocher** [comment]
@GiorgioSgl I think you need 3 dashes in your table for it to render correctly, and your second line had too many entries:

> | Resolution | FPS | mAP | mAP50 | mAP75 | mAP_small | mAP_medium | mAP_large |
> | ---- | --- | --- | --- | --- | --- | --- | --- | 
> | 640 | 0.5 | 0.35 | 0.54 | 0.37 | 0.15 | 0.34 | 0.46 |
> | 416 | 1 | 0.32 | 0.50 | 0.33 | 0.08 | 0.29 | 0.48 |
> | 320 | 1.6 | 0.29 | 0.46 | 0.30 | 0.05 | 0.23 | 0.47 |

**Comment by yinyuhangi** [comment]
@glenn-jocher Thanks for your time. Can you provide some relevant data on tesla V100?

**Comment by glenn-jocher** [comment]
@yinyuhangi all README results are obtained with V100 GCP instances. See README:
https://github.com/ultralytics/yolov5

**Comment by yinyuhangi** [comment]
@glenn-jocher However, there is no test result of mAP0.5 on COCO test-dev2017 in the result of the readme. Can you provide the results of this test?

**Comment by yinyuhangi** [comment]
@glenn-jocher However, there is no test result of mAP0.5 on COCO test-dev2017 in the result of the readme. Can you provide the results of this test?

**Comment by 846416** [comment]
How to submit to coco2017 test-dev server？

**Comment by glenn-jocher** [comment]
@846416 see COCO test-dev 2017 instructions in the YOLOv5 Colab Notebook:
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb#scrollTo=rc_KbFk0juX2

**Comment by fire717** [comment]
> @glenn-jocher However, there is no test result of mAP0.5 on COCO test-dev2017 in the result of the readme. Can you provide the results of this test?

Yes, The readme just have result of val, not test. I want to know it,too.

**Comment by glenn-jocher** [comment]
@fire717 you can run these yourself here:
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb?hl=en

<img width="1125" alt="Screen Shot 2022-01-04 at 10 44 10 AM" src="https://user-images.githubusercontent.com/26833433/148108233-6cd06213-f6dc-4b5d-9647-31963b420a9f.png">

**Comment by fire717** [comment]
> @fire717 you can run these yourself here: https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb?hl=en
> 
> <img alt="Screen Shot 2022-01-04 at 10 44 10 AM" width="1125" src="https://user-images.githubusercontent.com/26833433/148108233-6cd06213-f6dc-4b5d-9647-31963b420a9f.png">

Thx! But after I run it locally, I found it seems that there is no test-dev2017 anymore,
now there are only "val2017", "test-dev2019" and "test-challenge2019" in the submit page.  : (

By the way, I noticed that YOLOv5-5.0 release table has both mAPval0.5:0.95 and mAPtest0.5:0.95, 
but the value are the same, is it just some miswritten or they are indeed the same?

**Comment by glenn-jocher** [comment]
@fire717 you can submit to test-dev2019

**Comment by fire717** [comment]
@glenn-jocher Yes! I have submitted YOLOv5n-6.0 sucessfully, got below:

> overall performance
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.281
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.457
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.298
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.127
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.313
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.354
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.255
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.427
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.464
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.239
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.513
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.621

It's almost the same as val (28.4 | 46.0)

I'll try other models next , thx.

**Comment by glenn-jocher** [comment]
@fire717 great! Yes the COCO test and val numbers should roughly match up to within a few fractions of a percent.

**Comment by Mary14-design** [comment]
> @fire717 great! Yes the COCO test and val numbers should roughly match up to within a few fractions of a percent.

Can you please share the code you used for this calculations?
