### ISSUE TITLE
How does the images with no objects work?

### ISSUE THREAD

**Issue by Xiaocong6** [ultralytics/yolov5#2791]
## hi~Thanks for your work. In the wiki, you pointed out that the images with no objects can reduce fp. But, how does is work? How does it participate in training？In those images, there are no gt, So how do they generate negative samples？
I am very confused and look forward to your reply！

**Comment by Xiaocong6** [comment]
I have two more questions
(1) If I cut out the misdetected area, copy and paste it into some pictures. And add those to training without giving the box information, is it useful?

(2) If the misdetected area corresponding to each category is cropped, it is counted as an additional category, and the box information is given during training, is it useful?

**Comment by glenn-jocher** [comment]
@Xiaocong6 all images are handled equally during training regardless of their instance count (0 or > 0 it doesn't matter). 

If instances are present they incur objectness, class and box loss, if no instance is present only objectness loss is incurred.

**Comment by glenn-jocher** [comment]
@Xiaocong6 the full loss class is in utils/loss.py:
https://github.com/ultralytics/yolov5/blob/1487bc84ff3babfb502dffb5ffbdc7e02fcb1879/utils/loss.py#L88-L162

**Comment by Xiaocong6** [comment]
@glenn-jocher Thanks!

**Comment by FraPochetti** [comment]
Hi @Xiaocong6 have you been able to get this to work?
My main question is, how should the targets look like for a negative sample?
Right now, for each batch the `y` is a `tensor` of shape `N, 6`, where the first column is the id of the image, the followig 4 are the bbox coordinates etc.
What about when there are no bboxes?
