### ISSUE TITLE
Ensembling with Pickle PKL weights file in Pytorch 

### ISSUE THREAD

**Issue by SWRIGH211** [ultralytics/yolov5#2792]
## ❔Question
Im trying to ensemble a Faster R-CNN resnet 101 pre trained model weights with a YOLOv5s pre trainedmodel. But i'm not sure how to transfer the faster R-CNN weights pickle .PKL file into Pytorch .pt format to run ensembling? any help would be great

**Comment by glenn-jocher** [comment]
@SWRIGH211 I'm not sure, that sounds like a lost cause. You'd probably want to start with all PyTorch models before attempting any custom ensembling, so if you really wanted to go down that route the first step would be import to a *.pt checkpoint.
