### ISSUE TITLE
what is YOLOv5x6 ?

### ISSUE THREAD

**Issue by XiaoJiNu** [ultralytics/yolov5#2796]
Hi, what is YOLOv5x6  and what's the meaning of 6 ? Where is YOLOv5x6.yaml ?

**Comment by glenn-jocher** [comment]
@XiaoJiNu see v5.0 release notes for detailson YOLOv5x6:
https://github.com/ultralytics/yolov5/releases/tag/v5.0

yaml files are in models/ for core models and models/hub for all other models like yolov5x6.yaml:
https://github.com/ultralytics/yolov5/blob/14797370646d25e226f0093a5982d5cd54ba729a/models/hub/yolov5x6.yaml#L1-L60

**Comment by glenn-jocher** [comment]
This release implements **YOLOv5-P6** models and retrained **YOLOv5-P5** models. All model sizes YOLOv5s/m/l/x are now available in  both P5 and P6 architectures:

* **YOLOv5-P5** models (same architecture as v4.0 release): 3 output layers P3, P4, P5 at strides 8, 16, 32, trained at `--img 640`
```bash
python detect.py --weights yolov5s.pt  # P5 models
                           yolov5m.pt
                           yolov5l.pt
                           yolov5x.pt
```
* **YOLOv5-P6** models: **4 output layers** P3, P4, P5, P6 at strides 8, 16, 32, 64 trained at `--img 1280`
```bash
python detect.py --weights yolov5s6.pt  # P6 models
                           yolov5m6.pt
                           yolov5l6.pt
                           yolov5x6.pt
```

Example usage:
```bash
# Command Line
python detect.py --weights yolov5m.pt --img 640  # P5 model at 640
python detect.py --weights yolov5m6.pt --img 640  # P6 model at 640
python detect.py --weights yolov5m6.pt --img 1280  # P6 model at 1280
```
```python
# PyTorch Hub
model = torch.hub.load('ultralytics/yolov5', 'yolov5m6')  #  P6 model
results = model(imgs, size=1280)  # inference at 1280
```

**Comment by XiaoJiNu** [comment]
@glenn-jocher Thanks for your detailed answer and great work !
