### ISSUE TITLE
large scale dataset use --cache-images flag

### ISSUE THREAD

**Issue by Shengxiaolin** [ultralytics/yolov5#2797]
## ❔Question
hello ~ , i have dataset with a million images about 450GB and i want to use --cache-images  accelerate training（i have 128GB RAM），can i split the whole dataset into many sub dataset  and training them one by one（like resume training） ？

**Comment by glenn-jocher** [comment]
@Shengxiaolin you can do whatever want. --resume accepts no modifications in any parameters however. You might also want to verify --cache speedup beforehand on an AWS P4d instance for example before you bother implementing the details.

Resuming an interrupted training run is simple. There are two options:
```bash
python train.py --resume  # resume latest training
python train.py --resume path/to/last.pt  # specify resume checkpoint
```

If you started the training with a multi-GPU command then you must resume it with the same exact configuration (and vice versa). Multi-GPU resume commands are here, assuming you are using 8 GPUs:
```bash
python -m torch.distributed.launch --nproc_per_node 8 train.py --resume  # resume latest training
python -m torch.distributed.launch --nproc_per_node 8 train.py --resume path/to/last.pt  # specify resume checkpoint
```

Note that you may not change any settings when resuming, you must resume with the same exact settings (`--epochs`, `--batch`, `--data`, etc).

**Comment by Shengxiaolin** [comment]
thanks for the reply,i will test on my dataset.
