### ISSUE TITLE
Question about the curve.png

### ISSUE THREAD

**Issue by lujiazho** [ultralytics/yolov5#2798]
## ❔Question
I found that the horizontal axis of F1、P、R_curve.png is confidence. And I look up the source code as below
`if plots:
            plot_results(save_dir=save_dir)  # save as results.png
            if wandb_logger.wandb:
                files = ['results.png', 'confusion_matrix.png', *[f'{x}_curve.png' for x in ('F1', 'PR', 'P', 'R')]]
                wandb_logger.log({"Results": [wandb_logger.wandb.Image(str(save_dir / f), caption=f) for f in files
                                              if (save_dir / f).exists()]})`
It seems like the statistics are processed by wandb_logger. When I train my model, I didn't use the wandb, can I found the statistics to restore the F1_curve.png? Like I need the data as below

conf F1 P R
0.1 0.98 0.97 0.9
0.2 0.89 0.77 0.82
...
0.9 0.01 0.07 0.05

Where can I found those statistics?

**Comment by glenn-jocher** [comment]
@leaving-voider sure, all metrics including F1, P, R PR curves are produced by metrics.py, logged locally to runs/train and are unrelated to wandb, they are YOLOv5-specific metrics we create.

**Comment by lujiazho** [comment]
thx a lot!
