### ISSUE TITLE
test image label shift

### ISSUE THREAD

**Issue by lucasjinreal** [ultralytics/yolov5#28]
I have train image label normal but test image label shift, how could that possible? i have exactly same number of images and labels:

![image](https://user-images.githubusercontent.com/21303438/84127117-658d3200-aa71-11ea-9ae3-b694ca5299b6.png)

Some normal, some shifted.

While train is normal. What's the problem could be?

**Comment by glenn-jocher** [comment]
@jinfagang unless you can you reproduce this on COCO, your labels are the problem.

**Comment by lucasjinreal** [comment]
![image](https://user-images.githubusercontent.com/21303438/84217847-cd8a5980-aaff-11ea-8a1d-ff3df05cf48b.png)

128

**Comment by glenn-jocher** [comment]
You should clone the repo again, something is wrong with your local version.

**Comment by glenn-jocher** [comment]
Also the colab notebook shows easy examples of training.

**Comment by lucasjinreal** [comment]
@glenn-jocher  Hi, I found it caused by I have not same length images and labels in the directory.

What should I do if I have multiple batchs data, I placed all images in a single folder and very batch label in a different dir, and every time I using a different batch, I will soft link that batch labels to `labels` folder.

In this case, it can not load properly since their length not same, how to make it workable if I dont' want make many copies of images. (which waste disk space and not orgniseable)

**Comment by glenn-jocher** [comment]
@jinfagang yes I understand. The repo caches labels into *.npy files for faster loading. Perhaps a rework of this is in order for greater flexibility.

A quick fix is to delete the *.npy files and use text labels instead, or to update the dataloader to ignore *.npy files:
https://github.com/ultralytics/yolov5/blob/c14368d768749734e1a017ed8e750b33597e8746/utils/datasets.py#L332-L341

**Comment by balag59** [comment]
> @jinfagang yes I understand. The repo caches labels into *.npy files for faster loading. Perhaps a rework of this is in order for greater flexibility.
> 
> A quick fix is to delete the *.npy files and use text labels instead, or to update the dataloader to ignore *.npy files:
> https://github.com/ultralytics/yolov5/blob/c14368d768749734e1a017ed8e750b33597e8746/utils/datasets.py#L332-L341

@glenn-jocher Thank you for your work! I seem to be facing the same issue currently. Has there been any fix that's been attempted to resolve this? I've commented out the part in dataset.py where l is created from the npy file if labels_loaded=True so that l is created directly from the txt files. However, the visualized training batch 0 and 1 still seem to suffer from this issue. 

Will this affect only the visualizations or will the predictions be affected too?
Is there anything else that can I do to ensure that this doesn't happen?

**Comment by glenn-jocher** [comment]
@balag59 ha, the visualizations are not there to look pretty, they are showing you the actual data used for training. If they are not correct, your training won't be correct. If you delete npy files and are still seeing problems, then your actual labels are likely problematic. I'm working on a major upgrade of label caching and loading. This should be done this week or next week.

In the meantime start from the tutorial, which works well, and make sure your custom dataset is aligned exactly the same format and directory structure as coco128. You can inspect coco128 in Kaggle datasets also:
https://www.kaggle.com/datasets/ultralytics/coco128

**Comment by balag59** [comment]
> @balag59 ha, the visualizations are not there to look pretty, they are showing you the actual data used for training. If they are not correct, your training won't be correct. If you delete npy files and are still seeing problems, then your actual labels are likely problematic. I'm working on a major upgrade of label caching and loading. This should be done this week or next week.
> 
> In the meantime start from the tutorial, which works well, and make sure your custom dataset is aligned exactly the same format and directory structure as coco128. You can inspect coco128 in Kaggle datasets also:
> https://www.kaggle.com/datasets/ultralytics/coco128

@glenn-jocher Thank you for the prompt response! I have used your yolov3 implementation before on custom datasets extensively and it worked great and this preparation here is very similar to that except the yml part. This dataset is a collection of 4 datasets(one of them being coco) and there seems to be a weird issue where the image shown and the name for the image shown itself don't match. I've added a prefix to each of the other 3 datasets and none to coco so I know where each image is from. Could there be an issue of a mismatch between the images and labels? The number of images and labels in the train folder are not the same.I'm using a single class only( people class).Here is what the visualizations look like:
![train_batch0](https://user-images.githubusercontent.com/14803999/86890388-e09e4280-c11a-11ea-8761-550340437beb.jpg)
![train_batch1](https://user-images.githubusercontent.com/14803999/86890394-e3009c80-c11a-11ea-9891-41c15e86fc27.jpg)
![train_batch2](https://user-images.githubusercontent.com/14803999/86890409-e72cba00-c11a-11ea-9959-6b07f89e7314.jpg)

**Comment by glenn-jocher** [comment]
Yes it may be related to a different number of images and labels. The yolov5 repo has updates that removed the need to create a list of images used for training, you can now simply supply an /images folder in your data.yaml file, and it will look for any labels in a corresponding /labels folder. This is how coco128 works.

**Comment by balag59** [comment]
> Yes it may be related to a different number of images and labels. The yolov5 repo has updates that removed the need to create a list of images used for training, you can now simply supply an /images folder in your data.yaml file, and it will look for any labels in a corresponding /labels folder. This is how coco128 works.

I'm aware and that is that is what I'm doing right now. I've just given the path to the images folder in the yml file. This is still happening.Would creating a list make any difference or is there something else that I need to try?

**Comment by MarioDuran** [comment]
Hi @balag59, the only thing that worked for me right now, is to train with less than 1000 k images. 
give it a try.

**Comment by MarioDuran** [comment]
Hi @balag59 if the number of images and labels of your custom dataset is less than 1000, there is no problem, but if you have more than 1000 images, you will need to fill your custom dataset with new or repeated data, so you end up with a custom dataset of size in multiples of 1000. 

at least this workaround is working for me. hope it helps.

**Comment by HanClinto** [comment]
@MarioDuran I'm running into a similar issue, where my labels are showing up correctly in annotation software, but when I attempt to train the custom data on Yolov5, I'm getting some very odd annotation shifts.  I have 8070 training images and 2690 test images.  I tried artificially changing my dataset to 8000 and 3000 images, respectively, but it didn't seem to fix my issue.  Any idea where this problem of multiples-of-1000 is stemming from?
