### ISSUE TITLE
autoanchor

### ISSUE THREAD

**Issue by milla-Lee** [ultralytics/yolov5#2805]
## ❔Question
:autoanchor:Analzing anchors... anchors/target=2.65,Best Possible Recall(BPR)=0.9999.

## Additional context
hi,author,when i run yolov5,it reminder:autoanchor:Analzing anchors... anchors/target=2.65,Best Possible Recall(BPR)=0.9999.
there are no small tatgets in my dataset,it means the default anchors is suilable for my dataset?
BTW,do i  still need to recluster  my dataset? hope your reply,thanks.

**Comment by glenn-jocher** [comment]
@milla-Lee BPR of 0.9999 is great, this means your existing anchors work very well with your dataset. No further action is needed.

**Comment by milla-Lee** [comment]
thanks your reply!
