### ISSUE TITLE
Raspberry pi4 8GB vs Jetson Nano for my personal object detection hub?

### ISSUE THREAD

**Issue by 9christian9** [ultralytics/yolov5#2811]
## ❔Question

Ciao guys,
I'm new to this world and I'm searching to learning all about it though it is not very easy...
I'm here to ask you, which Raspberry pi4 8GB vs Jetson Nano I must be chosen to develop a small hub of Object detection?

## Additional context

I should be developing a people detector for my home that monitors about 5/6 cameras in my home h24 7/7
I can connect my cameras using RTSP.

Thanks a lot,
Christian.

**Comment by glenn-jocher** [comment]
@9christian9 if you are planning on connecting multiple sources to a single device you'll want to use some sort of GPU backend, i.e. a nano at the minimum I would say.

**Comment by 9christian9** [comment]
@glenn-jocher thanks very much for your reply...
So.. I'm searching an hardware that give me much relireliability and much FPS because I will use it to stream online in my personal application to share with my parents...
Now I test it on a mac that is of 2015 and it is very slow, 5FPS....
If I will buy a Raspberry pi4 8gb and I will buy an external GPU?
Pi it is most cheap 😆
What do you suggest? follow the road Of nano?
Can you syggest another Hardware that I can will use?

**Comment by glenn-jocher** [comment]
@9christian9 there's any number of deployment options you can use, the decision is yours based on your performance and budget constraints. 

5 FPS on a CPU is not slow, this is normal.

**Comment by 9christian9** [comment]
@glenn-jocher  I would be spend max 150€ for this project...
But I don't know which hardware buy😫

**Comment by glenn-jocher** [comment]
@9christian9 it sounds like you already have a laptop capable of 5 FPS on CPU. Therefore you're all set to produce a system for 1 FPS for 5 cameras for 0€!
