### ISSUE TITLE
Only put one image in validation to speed up training

### ISSUE THREAD

**Issue by lucacarotenuto** [ultralytics/yolov5#2812]
## ❔Question
Hi, 

Is the validation vital for the training or can I skip the validation and my training will be equally good? I already know that my model parameters are working well and I want to speed up the training so my idea was to only put one image into the validation set (empty did not work), and let the model train normally. Does that decrease performance? It should not right, because the validation is only for calculating metrics for the human and does not affect training, correct?

**Comment by GiorgioSgl** [comment]
+1

**Comment by glenn-jocher** [comment]
@lucacarotenuto @GiorgioSgl you can skip validation with `python train.py --notest`, though best.pt will not be saved in this configuration. 

You can also use few or no images in a validation dataset, in which case best.pt will naturally be unreliable.

**Comment by glenn-jocher** [comment]
See train.py argparser for a full list of options

https://github.com/ultralytics/yolov5/blob/aff03be35a8f5c7fb7da8bfd2f26a93cde416fbc/train.py#L456-L493

**Comment by aviezab** [comment]
> @lucacarotenuto @GiorgioSgl you can skip validation with `python train.py --notest`, though best.pt will not be saved in this configuration.
> 
> You can also use few or no images in a validation dataset, in which case best.pt will naturally be unreliable.

Hi Sir @glenn-jocher , for the `--notest` case, which validation result is saved in the model?
I meant, is confidence  saved based on best validation result?

This is crucial to determine the confidence at prediction.
Thank You 🙂

**Comment by glenn-jocher** [comment]
@aviezab --notest does not validate.

last.pt checkpoints are saved every epoch unless you pass --nosave

**Comment by aviezab** [comment]
@glenn-jocher sorry Sir my question was not clear before.

![image](https://user-images.githubusercontent.com/34294278/115215334-9af0ba80-a12d-11eb-9fd6-feaef222e1a4.png)

Please look at pointed image above Sir.
That mAP is confidence, right?

During the prediction, We will run `python detect.py --conf 0.5` like this.

Is confidence saved based on `val` dataset like that?
If Yes, We will add more `val` dataset because for now our `val` dataset is only little and made the mAP at finished training time like that, not so good although the prediction result is good actually.

**Comment by glenn-jocher** [comment]
@aviezab the validation results shown in your screenshot are created by test.py using a default confidence threshold of 0.001 to measure mAP. 

detect.py uses a default confidence threshold of 0.25 to produce real-world results.

Yes you should increase your val set as many classes only have 1 label.

**Comment by aviezab** [comment]
I see.
So after the training finished, the confidence is also saved to `last.pt` and `best.pt`, right?
That will influence when in the future We will use `detect.py --conf`, so We will add more val set.

Thank You Sir for answer.

**Comment by glenn-jocher** [comment]
@aviezab I don't understand your question. Confidence threshold is a parameter used to determine if a specific model output produces a detection. It is not saved anywhere.

**Comment by aviezab** [comment]
@glenn-jocher I see.
What I want to achieve is I will determine the confidence value according to information given as screenshot given so We can adjust how accurate is the prediction.

So mAP does not have correlation with confidence, and now I think the only thing We can do is fine tuning the confidence value when use `detect.py`.

**Comment by glenn-jocher** [comment]
@aviezab yes you can tune the detect.py detection settings (confidence threshold, iou threshold etc.) to your custom use case. Lowering confidence threshold will increase Recall, and increasing it will increase Precision.
