### ISSUE TITLE
question about the default threshold of NMS and mAP

### ISSUE THREAD

**Issue by lujiazho** [ultralytics/yolov5#2816]
## ❔Question
I learned that when we calculate mAP and NMS, we need the IOU threshold and confidence threshold respectively.

I found in test.py that the default IOU threshold and conf threshold is 0.6 and 0.01, but I didn't find both the two threshold for mAP calculation. 

But I found this one:
`iouv = torch.linspace(0.5, 0.95, 10).to(device)  # iou vector for mAP@0.5:0.95`
Does that mean the IOU threshold for mAP@.5 is 0.5? If it's true, but where is the conf thresthold for mAP?

**Comment by glenn-jocher** [comment]
@leaving-voider see test.py argparser for val/test parameters:
https://github.com/ultralytics/yolov5/blob/aff03be35a8f5c7fb7da8bfd2f26a93cde416fbc/test.py#L286-L306
