### ISSUE TITLE
What can I benefit from setting training to single_cls mode? (given that only one class in the dataset)

### ISSUE THREAD

**Issue by Zacchaeus00** [ultralytics/yolov5#283]
Hi sir,
I realized I can set the training process to single_cls mode, but I didn't get the point. Can I improve training **speed** or **accuracy** or any other benefits?
I would be appreciated if you can address my confusion.

**Comment by glenn-jocher** [comment]
@Zacchaeus14 trains multi-class datasets in single class mode.
