### ISSUE TITLE
Can't understand the "P3/8".

### ISSUE THREAD

**Issue by Zpadger** [ultralytics/yolov5#2835]
## ❔Question
Who can teach me the mean of these "# P3/8"/ "# P4/16" / "# P5/32"？What is the mean of "P3"? And what is the mean of "8"? Why "8"? Thank you very much for you help.

## Additional context
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

**Comment by fabien-lionti** [comment]
Yolo is based on the principle of receptive cells.

For example you can put an imaginary 80 by 80 grid on the image. When the center of an object fall into a grid cell, the output neurones associated with this cell will be responsible to output x, y, width, height, objectness score and class of that object.

To detect object from different range of size, it can be advantageous to use features from the same image at different scales.

These feature maps are obtained by using different strides (8, 16 and 32).

So P3, P4 and P5 correspond to the outputs of Yolo network associated with each of these feature maps. 8, 16, 32 correspond to the stride used to obtain these feature map.

If you want to preserve spatial information about the feature maps, you will "construct a grid" with size adapted to the feature map size.

For a 640 x 640 input image and a feature map obtained with a stride of 8, the final grid size will be 640 / 8 = 80 by 80 grid size.

**Comment by Zpadger** [comment]
@fabien-lionti  Thank you very much！

**Comment by pravastacaraka** [comment]
@fabien-lionti can you explain to me about the anchor? what is the number here:

```yaml
anchors:
[10,13, 16,30, 33,23] # P3/8
[30,61, 62,45, 59,119] # P4/16
[116,90, 156,198, 373,326] # P5/32
```

**Comment by Zpadger** [comment]
@pravastacaraka These numbers are the size of the anchor, two numbers form a group.

**Comment by glenn-jocher** [comment]
@pravastacaraka @Zpadger the P3-P6 output layers are standard names for output layers in vision AI models. The idea is simply that the stride = 2 ** P, i.e. for P6 stride = 2 ** 6 = 64. A 640x320 image will turn into a 10x5 feature map at stride 64.


Here is an good diagram from the EfficientDet paper:
![image](https://user-images.githubusercontent.com/26833433/115847360-2a92b380-a423-11eb-9f9e-f8a5cb07f52b.png)

**Comment by Zpadger** [comment]
@glenn-jocher Thank you for your explanation very much！

**Comment by pravastacaraka** [comment]
@Zpadger @glenn-jocher I still don't understand how anchors work with these numbers, are there any reading references that are easy for me to understand?

**Comment by glenn-jocher** [comment]
@pravastacaraka start here: https://pjreddie.com/publications/

**Comment by Zpadger** [comment]
@pravastacaraka Are you referring to how to generate anchors? They are a priori boxes generated by **Kmeans** clustering.

**Comment by Zpadger** [comment]
@pravastacaraka Just like these:
`
Best Accuracy = 85.23%
Best Anchors = [[7.67, 17.78], [10.33, 23.7], [13.33, 30.22], [16.67, 37.93], [21.0, 46.22], [25.67, 59.26], [32.33, 72.3], [43.0, 93.63], [60.29, 122.67]]  
  

Best Ratios = [0.43, 0.43, 0.44, 0.44, 0.44, 0.45, 0.45, 0.46, 0.49]
`

**Comment by idhamari** [comment]
> I still don't understand how anchors work with these numbers, are there any reading references that are easy for me to understand?

same here!

>For a 640 x 640 input image and a feature map obtained with a stride of 8, the final grid size will be 640 / 8 = 80 by 80 grid size.

so for 640 x 640  with a stride of 32 we get  640 / 32 = 20 by 20 grid size. In the model file:

         [116,90, 156,198, 373,326]  # P5/32 

How come the anchors' coordinates are larger than the grid size 20,20? 

Why 3 pairs? is this related to the three RGB channels?

**Comment by myasser63** [comment]
@glenn-jocher Could you please explain how

**Comment by glenn-jocher** [comment]
@myasser63 see EfficientDet paper: https://arxiv.org/abs/1911.09070

![image](https://user-images.githubusercontent.com/26833433/142458623-3f2c4da3-c2d5-4f40-a8e8-6009b01aa005.png)

**Comment by myasser63** [comment]
@glenn-jocher Could you please explain how according to the answer above
`[[-1, 1, Conv, [64, 6, 2, 2]], # 0-P1/2` is equivalant to `models.common.Conv [3, 32, 6, 2, 2]`

and P3/8 means P3= 8?

**Comment by myasser63** [comment]
> @glenn-jocher Thanks for your reply. However, the paper doesn't seem to have the clarification for my confusion. I couldn't apply the concept to understant this line
> 
> `[[-1, 1, Conv, [64, 6, 2, 2]], # 0-P1/2` is equivalant to `models.common.Conv [3, 32, 6, 2, 2]`
> 
> ![image](https://user-images.githubusercontent.com/49511207/142461576-aa97ac8f-5e0d-4111-bbf1-19865e101d92.png)

  @glenn-jocher  Could you kindly assist to clear my confusion?

**Comment by myasser63** [comment]
> @myasser63 see EfficientDet paper: https://arxiv.org/abs/1911.09070
> 
> ![image](https://user-images.githubusercontent.com/26833433/142458623-3f2c4da3-c2d5-4f40-a8e8-6009b01aa005.png)

thank you

**Comment by myasser63** [comment]
@glenn-jocher could you kindly explain `args` in the yaml file for `conv`?
`[from, number, module, args]`

**Comment by glenn-jocher** [comment]
@myasser63 from which module is the input (-1 is the previous module), the number of times the module is repeated, module name, module arguments.

**Comment by myasser63** [comment]
Are these the args for the `Conv `module `(ch_in, ch_out, kernel, stride, padding, groups)`?
if yes how are they connected to these [64, 6, 2, 2] in 
`[[-1, 1, Conv, [64, 6, 2, 2]]`

**Comment by glenn-jocher** [comment]
@myasser63 `c1` is inherited from output of previous layer, `c2=64` etc:
https://github.com/ultralytics/yolov5/blob/5185981993737861575adb07f2817a74fa4b2baa/models/common.py#L36-L46

**Comment by myasser63** [comment]
@glenn-jocher Thanks alot for the explanation

**Comment by codePerfectPlus** [comment]
> @pravastacaraka Just like these: ` Best Accuracy = 85.23% Best Anchors = [[7.67, 17.78], [10.33, 23.7], [13.33, 30.22], [16.67, 37.93], [21.0, 46.22], [25.67, 59.26], [32.33, 72.3], [43.0, 93.63], [60.29, 122.67]]
> 
> Best Ratios = [0.43, 0.43, 0.44, 0.44, 0.44, 0.45, 0.45, 0.46, 0.49] `

There is nothing like best anchors, It depends upon datasets.

**Comment by lam-thai-nguyen** [comment]
Thank you, everyone

**Comment by pderrenger** [comment]
@lam-thai-nguyen You're welcome! For anyone else following this discussion, the key takeaway is that the P3/8, P4/16, P5/32 notation refers to feature pyramid levels where the number after the slash indicates the stride (P3 = stride 8, P4 = stride 16, P5 = stride 32), and the anchor boxes at each level are optimized for detecting objects of different scales at those respective resolutions.
