### ISSUE TITLE
Normalising before resizing or the reverse?

### ISSUE THREAD

**Issue by Nishaghoul** [ultralytics/yolov5#2836]
## ❔Question
I have training, validation and test images of dimension 4032 by 3024 that I am resizing to 1024 by 1024 by using im.resize.
How are the coordinates of xmin and xmax expected to change? Also, do I normalise and values and create the lables.txt files before the resizing of images? As in, that would be using the original height and width of images and creating the labels files and then, just resizing the images. Is that the right thing to do?
Or should I first resize the images and then normalise the values according to the new height and weight that is 1024?
Also what will be the effects of resizing the image from a rectange to a square?

**Comment by glenn-jocher** [comment]
@Nishaghoul normalization of image coordinates and resizing of images are independent operations, the order you perform these does not matter.
