### ISSUE TITLE
size

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#2842]
If I want to train the size (600,400) w,h . How can I do?
What is the function of image-weights and multi-scale?

parser.add_argument('--img-size', nargs='+', type=int, default=[640, 640], help='[train, test] image sizes')
parser.add_argument('--image-weights', action='store_true', help='use weighted image selection for training')
parser.add_argument('--multi-scale', action='store_true', help='vary img-size +/- 50%%')

**Comment by glenn-jocher** [comment]
@alicera to train at 600 pixels you can pass the nearest 32 multiple:
```
python train.py --img 608
```

--image-weights use weighted image selection for training rather than random selection and --multi-scale varies the actual image size +/- 50% during training (0.5 scale jitter is already in place in your hyp yaml).

**Comment by alicera** [comment]
For the size (640,512)
If I use the python train.py --img 608 , the train size will be(608,608) , right ?
But I want to design the (640,512),
Do you have the method?

**Comment by glenn-jocher** [comment]
@alicera you can use the --rect argument for rectangular training:
```
python train.py --rect
```

**Comment by alicera** [comment]
If I do the resize  after the process of LoadImagesAndLabels and mosaic.
Is it good method ?

like this 
![image](https://user-images.githubusercontent.com/59388989/115222230-17d76080-a13d-11eb-9f99-e84843f9a5a9.png)

**Comment by alicera** [comment]
I run the command " python -m torch.distributed.launch --nproc_per_node 4  train.py --batch-size 192 --data data/oblique.yaml  --weights yolov5s.pt --img 640 --rect "

The error is 
![image](https://user-images.githubusercontent.com/59388989/115223771-be703100-a13e-11eb-955a-6e717e83849f.png)

**Comment by glenn-jocher** [comment]
@alicera training automatically handles all resizing, you should not need to modify the code in any way. You can train at any image size you want with the --img parameter:
```
python train.py --img 1280
```

**Comment by alicera** [comment]
I dont modify any code when I run the command "" python -m torch.distributed.launch --nproc_per_node 4 train.py --batch-size 192 --data data/oblique.yaml --weights yolov5s.pt --img 640 --rect ""

**Comment by glenn-jocher** [comment]
@alicera in that case it may be that rectangular training is not compatible with multi-GPU training, as this is not part of our CI tests, and I could see the batch-size alignment becoming an issue. Does your command execute successfully on single-GPU or CPU?

**Comment by wudashuo** [comment]
@alicera Maybe your dataset contains images with various aspect ratios？
I probably met a similar problem when using `--rect`. 90% of my dataset images are the same aspect ratio(1920*1080), but the rest 10% are not(e.g. 1080*1080). I deleted the 10% images with different aspect ratios, and rerun the code, it worked.
@glenn-jocher For my case, rectangular training is compatible with DDP mode. But it probably can't be training unless all the images are the same aspect ratio.

**Comment by glenn-jocher** [comment]
@wudashuo ah yes that makes sense. I was thinking with multiple dataloader worker threads in DDP it might be impossible to construct same-size batches. I'll try to run some tests later today. 

@alicera the solution above by @wudashuo should work. If **all** images are the same size then there can't be any problems with batch construction even in DDP.
