### ISSUE TITLE
On a Fedora 33 Virtual Machine.. my inference time is often a second or two.. is this normal?

### ISSUE THREAD

**Issue by davesargrad** [ultralytics/yolov5#2846]
## ❔Question
I have a simple application that uses your yolov5 inference mechanism, with the yolov5s.pt.

The following code is the focus of this question:

```
        # Inference
        t1 = time_synchronized()
        pred = self.model(img, augment=self.augment)[0]

        # Apply NMS
        pred = non_max_suppression(pred, self.conf_thresh, self.iou_thresh, classes=self.classes,
                                   agnostic=self.agnostic_nms)
        t2 = time_synchronized()
```

`            self.logger.info(f'{s}Inference Time. ({t2 - t1:.3f}s)')`

The VM:
Fedora 64-bit
8 GB RAM
4 CPU
model name	: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz

**I'm seeing an inference take anywhere from 1 to 2 seconds**. Images are only 600x600.

![image](https://user-images.githubusercontent.com/48793689/115246694-1df51f00-a0f4-11eb-9168-9fd9cc81a9d5.png)

I would have thought that the inference was a lot faster. What would you expect on a VM with the given specs (obviously using CPU, not GPU)?

![image](https://user-images.githubusercontent.com/48793689/115248440-afb15c00-a0f5-11eb-85ec-7b3fea2f1a0b.png)

I've seen it range in time from .1 second to 1.9 seconds, with the exact same picture, and in the same run of the software. 

There is not much else going on, either on the VM, or on the laptop that runs the VM (its a 16 GB RAM laptop with 6 CPUs), so it would not make sense that the process is context switching out for that long.

**Comment by davesargrad** [comment]
Would it be faster if I submitted a batch of images to the call to self.model (is this even possible)? Is there a lot of time involved in setting up and breaking down the inference?

**Comment by davesargrad** [comment]
Though, I've not measured with diligence, I believe the average time taken to perform inference on this image is about .6 to 1.0 seconds.

**Comment by davesargrad** [comment]
Hmm.. I run the same image through your detect.py script and its faster (about .1 seconds) and more reliable from a timing perspective (much less variation).. Clearly Im doing somethin in my code that is slowing things down.. I'm running it in a thread.. and the code is almost exactly the code in detect.py; within that thread.. I'll post a bit more of the code.

![image](https://user-images.githubusercontent.com/48793689/115269730-987c6980-a109-11eb-96bc-3eb781ce3e11.png)

**Comment by davesargrad** [comment]
Here is the primary method within my detect thread (which, of course, is almost exactly the code in yolov5/detect.py):

```
 def detect(self, frame_info):
        frame = frame_info[0]
        info = frame_info[1]

        # Padded resize
        img = letterbox(frame, self.imgsz, stride=self.stride)[0]

        # Convert
        img = img[:, :, ::-1].transpose(2, 0, 1)  # BGR to RGB, to 3x416x416
        img = np.ascontiguousarray(img)

        t0 = time.time()
        img = torch.from_numpy(img).to(self.device)
        img = img.half() if self.half else img.float()  # uint8 to fp16/32
        img /= 255.0  # 0 - 255 to 0.0 - 1.0
        if img.ndimension() == 3:
            img = img.unsqueeze(0)

        # Inference
        t1 = time_synchronized()
        pred = self.model(img, augment=self.augment)[0]

        # Apply NMS
        pred = non_max_suppression(pred, self.conf_thresh, self.iou_thresh, classes=self.classes,
                                   agnostic=self.agnostic_nms)
        t2 = time_synchronized()

        # Apply Classifier
        #if classify:
        #    pred = apply_classifier(pred, modelc, img, im0s)

        # Process detections
        for i, det in enumerate(pred):  # detections per image
            s = ''

            s += '%gx%g ' % img.shape[2:]  # print string
            gn = torch.tensor(frame.shape)[[1, 0, 1, 0]]  # normalization gain whwh
            labels = []
            if len(det):
                # Rescale boxes from img_size to im0 size
                det[:, :4] = scale_coords(img.shape[2:], det[:, :4], frame.shape).round()

                # Print results
                for c in det[:, -1].unique():
                    n = (det[:, -1] == c).sum()  # detections per class
                    s += f"{n} {self.names[int(c)]}{'s' * (n > 1)}, "  # add to string

                # Write results
                for *xyxy, conf, cls in reversed(det):
                    xywh = (xyxy2xywh(torch.tensor(xyxy).view(1, 4)) / gn).view(-1).tolist()  # normalized xywh
                    line = (cls, *xywh, conf)

                    label = f'{self.names[int(cls)]} {conf:.2f}'
                    labels.append({"label": label, "box": xywh})
                    plot_one_box(xyxy, frame, label=label, color=self.colors[int(cls)], line_thickness=3)

            # Print time (inference + NMS)
            self.logger.info(f'{s}Inference Time. ({t2 - t1:.3f}s)')

        self.frame_cnt += 1
        self.logger.info(f"Total Frames: {self.frame_cnt}")
        self.logger.debug(f"Frame Data: {frame}")
        self.image_info.set_attribute("labels", labels)

        info.append(copy.deepcopy(self.image_info))
        return [(frame, info)]
```

Any ideas as to why this is so much slower, and higher variance, in the time taken to perform inference? 

@glenn-jocher 
If you can suggest some things to look at, that would be much appreciated. I will do whatever experiments you suggest to isolate this.

**Comment by glenn-jocher** [comment]
@davesargrad hey buddy, from your screenshot average inference time is about 100 ms per image. 

Typically GPUs will benefit from larger batch sizes, but you would need to use PyTorch Hub batched inference to see these gains on GPU, see PyTorch Hub tutorial:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [ONNX and TorchScript Export](https://docs.ultralytics.com/yolov5/tutorials/model_export)
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by davesargrad** [comment]
@glenn-jocher Hi. I appreciate your response no doubt.. However the time that I was trying to understand was not the 100msec (which indeed is what we see in the output of detect.py, as I highlighted in that screenshot), but the 1 second or more per image, that was in the first screenshot I put in the issue (included below)

![image](https://user-images.githubusercontent.com/48793689/115307191-db086b00-a136-11eb-8fb2-ef3a7b786534.png)


I'm quite convinced its something in my code, and yet if you look at the code I provide its essentially the code in detect.py. I was just hoping to get your thoughts on things to look at to isolate my problem (pytorch hub sidesteps my problem).

Though I may eventually look at pytorch hub, right now, I'm just trying to understand the code in detect.py (and its use in my threaded application).

**Comment by glenn-jocher** [comment]
@davesargrad sorry I don't recognize your screenshot and we don't generally provide support for custom code. I would recommend PyTorch Hub for integrating YOLOv5 inference into your own python workflows though. Times are clearly displayed with results.print():

<img width="1282" alt="Screenshot 2021-04-20 at 10 11 23" src="https://user-images.githubusercontent.com/26833433/115361429-de483900-a1c0-11eb-9048-76001dcf0faa.png">

**Comment by davesargrad** [comment]
@glenn-jocher Hi. 

I appreciate that its difficult for you guys to support custom code. I never really had such expectations, was only hoping for a pointer or two.

I am close. I wrote a test application that simply wraps the class that I use in a background thread (and that leverages your detect code). I now see very consistent times with the test application

![image](https://user-images.githubusercontent.com/48793689/115388095-7cc8a000-a1a9-11eb-9c36-f2493c6b3100.png)

Clearly the issue is something in my threading and queueing model, and this is not something that pytorch hub would solve. Later today I'm sure I will have isolated this. 

No doubt I will eventually try out the pytorch hub approach. Once I have a proper application wrapping the inference logic, then I will make that move.

**Comment by glenn-jocher** [comment]
@davesargrad yes this may be dependent on your system resources and cpu count. It's possible that some packages and functions are already operating in a multithreaded mode, so if you try to multithread at a higher level you may see slower performance per thread. You can use htop for example to monitor live resource usage.

**Comment by davesargrad** [comment]
Hi @glenn-jocher Ty for those thoughts. I have just verified with a very simple wrapper that runs my threaded inference (MultiObjectDetector) (using a ThreadPoolExecutor) that the thread seems to context switch out. It is the source of my problem no doubt. Very unexpected. 

For interest sake.. this is my test application. I get perfectly consistent (and low) timing from MultiObjectDetector (which is effectively your detect code ) when use_threading is False. Anyways, I'll dig some more into my threading and queueing. This is the first time I've done serious threading in python (I've done a lot in C/C++ and Java).


```
import concurrent.futures
import cv2
import queue
import signal
import sys
import time
import threading


from image_processing.multi_object_detector import MultiObjectDetector

def signal_handler(sig, frame):
    print('You pressed Ctrl+C!')
    global terminate
    terminate = True

use_threads = True
terminate = False
if __name__ == '__main__':
    print(f"Arguments count: {len(sys.argv)}")
    print("Execution Started: " + sys.argv[0])

    filename = "assets/airplane.jpg"
    if len(sys.argv) == 2:
        filename = sys.argv[1]

    print("Processing File: " + filename)

    from_q = queue.Queue(10)
    to_q = queue.Queue(10)
    model_info = {
                     "weights": "/assets/cnn/yolov5s.pt",
                     "device": "cpu",
                     "img_size": 640,
                     "augment": False,
                     "conf_thresh": 0.25,
                     "iou_thresh": 0.45,
                     "classes": None,
                     "agnostic_nms": False
                  }

    terminate_event = threading.Event()
    signal.signal(signal.SIGINT, signal_handler)
    mod = MultiObjectDetector.MultiObjectDetector(from_q, to_q, terminate_event, model_info=model_info)

    img = cv2.imread(filename, cv2.IMREAD_COLOR)
    if img is None:
        print("Cant process image: " + filename)
        sys.exit(-1)

    input_data = (img, [])
    if not use_threads:
        detection = mod.detect(input_data)
    else:
        from_q.put(input_data)
        with concurrent.futures.ThreadPoolExecutor(max_workers=1) as executor:
            executor.submit(mod.process)
            spin_cnt = 0
            while not terminate:
                spin_cnt += 1
                print(f"Working {spin_cnt}")
                time.sleep(5)
            print("Setting Terminate Event")
            terminate_event.set()
    print("Im just quitting")

```

**Comment by davesargrad** [comment]
What I've learned is that when I use a threadpoolexecutor..

This call context switches out in a fashion that is different than when I dont use one.

`        pred = self.model(img, augment=self.augment)[0]`

**Comment by davesargrad** [comment]
Ok.. pretty sure my issue is the global interpreter lock, described [here](https://stackoverflow.com/a/21210339/15307667) and [here](https://www.youtube.com/watch?v=ph374fJqFPE): time to rethink my approach.

**Comment by davesargrad** [comment]
@glenn-jocher Ty for your thoughts.. this is something that pytorch hub wont solve (I dont think).. its a flaw in my thinking.. (thinking that I can thread in python, in the same way i would for C/C++ or Java).

By the way, that video I linked is interesting for any python developer.

:)

**Comment by glenn-jocher** [comment]
Got it, good luck!

**Comment by davesargrad** [comment]
@glenn-jocher As a follow up. It looks like I was able to solve my problem with a bit more intelligent structure. The issue I had was that I constructed my thread object in my primary thread (this contained the yolov5 model), and then I ran the inference in the background thread .. Simple fix was to create a maker function that constructs the model, and runs it, in the background thread.

Now my inference times are exactly what I get when I run detect.py.

Yay.

**Comment by glenn-jocher** [comment]
@davesargrad hmm interesting. So you're getting similar CPU speeds even while running multiple models simultaneously, one in each thread?

**Comment by davesargrad** [comment]
I only gave the yolo model 1 thread... not two ... 

I actually take images in on another thread and then pass the opencv mat as a reference using queues... 

Tomorrow I’ll also look at multiprocessing since inference is likely to be CPU bound ... 

But I’m not sure I’ll need that .. it will still be good to have as a design option 


 ultimately, of course, I’ll also leverage GPU.. in that case my performance model will be different 


But the variability I saw yesterday came from instantiating the model in 1 thread... and using it in another 


I’m no longer doing that and the performance is comparable to detect.py

**Comment by glenn-jocher** [comment]
@davesargrad ah got it, thanks!
