### ISSUE TITLE
Where can i find paper for Yolo-5s6

### ISSUE THREAD

**Issue by Roopesh-Bharatwaj-K-R** [ultralytics/yolov5#2847]
Hi, Where can i, find paper for the YOLO-5s6

**Comment by Roopesh-Bharatwaj-K-R** [comment]
Hi , Thank you very much , How can i give citation for the latest Model and reference.

**Comment by glenn-jocher** [comment]
@Roopesh-Bharatwaj-K-R no paper yet but hopefully soon. In the meantime the release notes explain the new P6 models in comparison to the P5 models: 
https://github.com/ultralytics/yolov5/releases

This release implements **YOLOv5-P6** models and retrained **YOLOv5-P5** models. All model sizes YOLOv5s/m/l/x are now available in  both P5 and P6 architectures:

* **YOLOv5-P5** models (same architecture as v4.0 release): **3 output layers** P3, P4, P5 at strides 8, 16, 32, trained at `--img 640`
```bash
python detect.py --weights yolov5s.pt  # P5 models
                           yolov5m.pt
                           yolov5l.pt
                           yolov5x.pt
```
* **YOLOv5-P6** models: **4 output layers** P3, P4, P5, P6 at strides 8, 16, 32, 64 trained at `--img 1280`
```bash
python detect.py --weights yolov5s6.pt  # P6 models
                           yolov5m6.pt
                           yolov5l6.pt
                           yolov5x6.pt
```

Example usage:
```bash
# Command Line
python detect.py --weights yolov5m.pt --img 640  # P5 model at 640
python detect.py --weights yolov5m6.pt --img 640  # P6 model at 640
python detect.py --weights yolov5m6.pt --img 1280  # P6 model at 1280
```
```python
# PyTorch Hub
model = torch.hub.load('ultralytics/yolov5', 'yolov5m6')  #  P6 model
results = model(imgs, size=1280)  # inference at 1280
```

You can cite the DOI here:
https://zenodo.org/badge/latestdoi/264818686

**Comment by Roopesh-Bharatwaj-K-R** [comment]
@glenn-jocher Thank you very much I have noted down the DOI .
