### ISSUE TITLE
wandb.errors.UsageError: api_key not configured (no-tty). call wandb.login(key=[your_api_key])

### ISSUE THREAD

**Issue by starsky68** [ultralytics/yolov5#2848]
## ❔Question

wandb.errors.UsageError: api_key not configured (no-tty). call wandb.login(key=[your_api_key])
## Additional context
 File "D:\Project\yolov5-master\utils\wandb_logging\wandb_utils.py", line 95, in __init__
    self.wandb_run = wandb.init(config=opt,
  File "D:\python3\lib\site-packages\wandb\sdk\wandb_init.py", line 741, in init
    wi.setup(kwargs)
  File "D:\python3\lib\site-packages\wandb\sdk\wandb_init.py", line 155, in setup
    wandb_login._login(anonymous=anonymous, force=force, _disable_warning=True)
  File "D:\python3\lib\site-packages\wandb\sdk\wandb_login.py", line 216, in _login
    wlogin.prompt_api_key()
  File "D:\python3\lib\site-packages\wandb\sdk\wandb_login.py", line 152, in prompt_api_key
    raise UsageError("api_key not configured (no-tty). call " + directive)
wandb.errors.UsageError: api_key not configured (no-tty). call wandb.login(key=[your_api_key])

**Comment by glenn-jocher** [comment]
@starsky68 @AyushExel it looks like you need to call `wandb login` before running your command.

**Comment by AyushExel** [comment]
@starsky68 wandb should automatically prompt you to enter the api key if not configured. If that doesn't happen then it's a bug. Can you please help me reproduce this ? What are the exact commands that you ran

**Comment by supersarr** [comment]
I have the same problem as you, have you solved it

**Comment by AyushExel** [comment]
@supersarr can you share how you ran into this problem? It'll help me give you a solution. I'm looking for the command that you ran, the system( OS ) that you're on, etc

**Comment by supersarr** [comment]
@AyushExel I ran this program “!python train.py --img 640 --batch 50 --epochs 100 --data ../yolo_A/A.yaml --weights yolov5s.pt --nosave --cache”in jupyter notebook my system( OS ) is windows10 
![QQ20210428221812](https://user-images.githubusercontent.com/74942943/116419470-abacd900-a86f-11eb-9fff-d849dc2e9452.png)

**Comment by AyushExel** [comment]
@supersarr Okay thanks for pointing out the steps. wandb should automatically prompt you to log in if you're not already logged in so this looks like a jupyter notebook bug. I'll get it fixed.  But right now, you can manually run this command to login : 
```
!wandb login
```
Run the above command in your notebook cell and let me know if that works

**Comment by supersarr** [comment]
@AyushExel  I have get the api key, and i run the command in jupyter 
![Uploading 111.png…]()

**Comment by supersarr** [comment]
![111](https://user-images.githubusercontent.com/74942943/116421017-11e62b80-a871-11eb-8704-ec6631a3299c.png)
@AyushExel   I have get the api key, and i run the command in jupyter

**Comment by AyushExel** [comment]
@supersarr do this:
* Open your terminal and activate the virtual environment if you're using that
* run `wandb login`
* When prompted, paste your api-key
* After this, run the training cell in your notebook. It should work fine

**Comment by supersarr** [comment]
@AyushExel  I follow the steps of a post，open the power shell and run wandb login, enter the api key.But it still seems to report an error
![QQ图片20210428223444](https://user-images.githubusercontent.com/74942943/116422041-f0d20a80-a871-11eb-8778-4eec306011f1.png)

**Comment by AyushExel** [comment]
@supersarr from the error, it looks like you didn't correctly copy the API key.  After running `wandb login`:
* You'll be redirected to wandb.ai/authorize
* There, click on the API-key to copy it
* Then go back to the terminal, right click and select paste, to paste the API key

**Comment by supersarr** [comment]
@AyushExel After copying and pasting it many times, it didn’t work. Finally, I used manual input and it seemed to succeed 
It’s time to go to rest now. Try again tomorrow if it works. Thank you for answering me.

**Comment by AyushExel** [comment]
@supersarr sure. Let me know if you face any other problems

**Comment by supersarr** [comment]
@AyushExel I want to use yolov5 to train on my own dataset，But when it comes to training. I encountered another problem like this 
![1](https://user-images.githubusercontent.com/74942943/116492680-76d06e80-a8cf-11eb-9de2-e829ed285793.png)
![2](https://user-images.githubusercontent.com/74942943/116492682-78019b80-a8cf-11eb-85cb-16bec9f9c5ea.png)
![3](https://user-images.githubusercontent.com/74942943/116492684-789a3200-a8cf-11eb-86ca-a1f878bc97db.png)

I went to look for the Broken pipe problem, there seems to be no suitable solution

**Comment by starsky68** [comment]
> @AyushExel I want to use yolov5 to train on my own dataset，But when it comes to training. I encountered another problem like this
> ![1](https://user-images.githubusercontent.com/74942943/116492680-76d06e80-a8cf-11eb-9de2-e829ed285793.png)
> ![2](https://user-images.githubusercontent.com/74942943/116492682-78019b80-a8cf-11eb-85cb-16bec9f9c5ea.png)
> ![3](https://user-images.githubusercontent.com/74942943/116492684-789a3200-a8cf-11eb-86ca-a1f878bc97db.png)
> 
> I went to look for the Broken pipe problem, there seems to be no suitable solution

直接把wandb的所有注释了吧，还是用tensorboard去可视化结果吧，也不影响训练。作为wandb新手用不惯。

**Comment by AyushExel** [comment]
@starsky68 broken pipe is generally caused when too much of your system memory is occupied. Are you seeing this every time you run the script? Anyway, I don't think it is YOLOv5 related but @glenn-jocher might know more on this

**Comment by glenn-jocher** [comment]
@starsky68 its likely you attempted to exceed your system resources here. Monitor your RAM and CPU threads usage.
