### ISSUE TITLE
For single class, when th R is Zero, but why the P is One?

### ISSUE THREAD

**Issue by snop222** [ultralytics/yolov5#2849]
## ❔Question
When the training reach the final epoch, could got the reasult for each class if class number is less 50.
In my reault, the values of some classes is strange as following:

```
   Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95
     all    1.79e+04    1.92e+04       0.365       0.752       0.454         0.4
01.01.13    1.79e+04          15       0.338       0.818       0.469       0.404
01.01.20    1.79e+04          18        0.21       0.556       0.328       0.282
01.03.01    1.79e+04          13       0.281           1       0.503       0.457
01.05.15    1.79e+04           5       0.273           1       0.589       0.581
01.07.31    1.79e+04           2       0.594       0.782       0.828       0.679
**01.13.01    1.79e+04           1           0           0           0           0**
01.15.05    1.79e+04           7       0.248           1       0.327       0.229
**02.01.09    1.79e+04           2           1           0       0.181       0.181**
02.01.12    1.79e+04           1       0.818           1       0.995       0.896
02.01.13    1.79e+04           2       0.509           1       0.828       0.828
**02.01.14    1.79e+04           1           1           0       0.249       0.24**9
```

For the class '01.13.01', the P and R are both zero, thais is fine.
But... For the classes '02.01.09' and '02.01.14', when th R is zero, why the P is not zero?

**Comment by glenn-jocher** [comment]
@snop222 precision value of 1 means no false positives were detected. To learn more see https://en.wikipedia.org/wiki/Precision_and_recall

I'd also recommend you increase the size of your validation set if you want reliable per-class metrics

**Comment by snop222** [comment]
Thank you veru much for your answer.
Yes, I already change the "verbose=nc < 50" to "verbose=nc < 600", because my number of classes is 543.

With the definition of Precision, when the false positives is none (fp = 0), the Precision always is 1, no mater how many is the true positives (tp = ?), even if the true positives is none too. Is it right ?

**Comment by glenn-jocher** [comment]
@snop222 yes I believe that's correct.
