### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 2.60 GiB (GPU 0; 3.81 GiB total capacity; 129.38 MiB already allocated; 2.12 GiB free; 410.00 MiB reserved in total by PyTorch)

### ISSUE THREAD

**Issue by orangezishuai** [ultralytics/yolov5#285]
GPU: gtx 1650
batch_size = 1
epochs = 5
image-size [418, 418]

RuntimeError: CUDA out of memory. Tried to allocate 2.60 GiB (GPU 0; 3.81 GiB total capacity; 129.38 MiB already allocated; 2.12 GiB free; 410.00 MiB reserved in total by PyTorch)

How can i do to solve this problem?

**Comment by glenn-jocher** [comment]
CUDA out of memory. Google it.
