### ISSUE TITLE
coremltools 4.0 converter

### ISSUE THREAD

**Issue by silvestrebahi** [ultralytics/yolov5#286]
## 🚀 Feature
A "convert coreml" pipeline like the one you already implemented for ONNX. 

## Motivation

Since coremltools 4.0 beta is now available and allows pt to mlmodel conversion, it would be awesome to have a way to generate mlmodels easily without using ONNX.  There is already an ONNX_EXPORT parameter in the actual code which allows to get onnx models from your implementation. A similar approach could be used to directly get mlmodels. Any plans for that?

Thanks for all!

**Comment by glenn-jocher** [comment]
@silvestrebahi we have updated `export.py` a bit to better support the 3 export channels (ONNX, TorchScript and CoreML).  See #251 for a tutorial on how to use export.py. Note that export.py is mainly a guide that provides simple first steps for users like yourself to begin creating your own export pipelines though, it does not provide end-to-end export functionality.

We do offer paid end-to-end export services, as well as providing reference apps for iOS and Android to use your exported models in. If you have a business idea for YOLOv5 at the edge, we'd be happy to help you get started! You can email glenn.jocher@ultralytics.com for details if interested.
