### ISSUE TITLE
When I replaced the Silu activation function, the program reported:

### ISSUE THREAD

**Issue by xuhao-anhe** [ultralytics/yolov5#2865]
## ❔Question
When I replaced the Silu activation function, the program reported:
![SWNB@U27WNE 3DYAD`CSBJ3](https://user-images.githubusercontent.com/59590631/115403913-6b21df80-a21f-11eb-8c41-14a76965eb73.png)

I'll look up the problem and say that the number of my samples can't be divided by batch_ Size, but I saw if my dataset could be divided or I continued to report this error

**Comment by glenn-jocher** [comment]
@xuhao-anhe you can replace the nn.SiLU() activation function with any other of your choosing by modifying L39 here of models/common.py:
https://github.com/ultralytics/yolov5/blob/1df8c6c963d31ce84895101a70e45e0afdcb0bc2/models/common.py#L33-L40
