### ISSUE TITLE
Count total number of objects in the video

### ISSUE THREAD

**Issue by theonlyNischal** [ultralytics/yolov5#287]
Is there any way to count the total number of objects in the given video?

For example

If there are 30 different person appearing on the video. How do we track them?

I have heard about deepsort is it applicable here?

**Comment by glenn-jocher** [comment]
@theonlyNischal counting and tracking are two completely different tasks. You may want to define your requirements more clearly. iDetection counts objects on screen for example, but it does not track.

<img src="https://user-images.githubusercontent.com/26833433/86490288-b106c900-bd1b-11ea-97c5-bff18aeac6af.PNG" width="500">
