### ISSUE TITLE
WBF for YOLOv5

### ISSUE THREAD

**Issue by jayyoung23** [ultralytics/yolov5#2873]
Hello

Recently, I found that some people tried to use yolov5 in combination with wbf《Weighted Boxes Fusion: ensembling boxes for object detection models》 in the kaggle competition. Almost all the top ten have adopted the wbf （https://github.com/ZFTurbo/Weighted-Boxes-Fusion）solution. Have you considered this solution?

**Comment by glenn-jocher** [comment]
@jayyoung23 ah very interesting! We have not tried https://github.com/ZFTurbo/Weighted-Boxes-Fusion. It looks like it may improve mAP at the expense of slower speed per their table:
https://github.com/ZFTurbo/Weighted-Boxes-Fusion#accuracy-and-speed-comparison

**Comment by Audrey528** [comment]
@glenn-jocher  Have you tried  WBF in yolov5？How about your results?
I tried run val.py in four different ways: yolov5s.pt、yolov5x.pt、yolov5s.pt+yolov5x.pt、yolov5s.pt+yolov5x.pt+wbf, and the relative results see below.
![WeChat Image_20220420181402](https://user-images.githubusercontent.com/68552295/164206822-846fe3b9-e5e3-4edd-94c4-ec936cb89c25.png)
I have some questions. First, the result of yolov5s.pt and yolov5s.pt ensemble method is worse than yolov5x.pt, is it sound？What's your original intention of designing Ensembel?Second, if you had better results in case you tride wbf, please give me some help. In my experiments, mAP and speed is worse when using wbf. 
Thanks a million!

**Comment by glenn-jocher** [comment]
@Audrey528 have not tried WBF. Ensembling multiple models is not guaranteed to improve results, especially if one model is substantially poorer than the other,.

**Comment by myasser63** [comment]
@glenn-jocher @Audrey528 Could you please give me an idea of how to extract boxes, scores, labels to apply WBF

**Comment by regainOWO** [comment]
@Audrey528 yolov5中的模型集成的原理是将个各模型推理得到的box信息取并集整合在一起，然后进行nms。我的理解是，会出现以下两种情况
1. 如果部分模型有漏检，而效果较好的模型能检测出来，map会有所提升
2. 如果部分模型有误检，而nms阶段无法将其过滤掉，map会有所下降

所以Ensembling并不一定能提高map。
至于WBF，可能要调整一下wbf的参数才能达到最好的效果。

**Comment by viethoang303** [comment]
> @glenn-jocher Have you tried WBF in yolov5？How about your results? I tried run val.py in four different ways: yolov5s.pt、yolov5x.pt、yolov5s.pt+yolov5x.pt、yolov5s.pt+yolov5x.pt+wbf, and the relative results see below. ![WeChat Image_20220420181402](https://user-images.githubusercontent.com/68552295/164206822-846fe3b9-e5e3-4edd-94c4-ec936cb89c25.png) I have some questions. First, the result of yolov5s.pt and yolov5s.pt ensemble method is worse than yolov5x.pt, is it sound？What's your original intention of designing Ensembel?Second, if you had better results in case you tride wbf, please give me some help. In my experiments, mAP and speed is worse when using wbf. Thanks a million!

Can you share code yolov5 for applying WBF, please?

**Comment by dt140120** [comment]
> 

ông nhúng được wbf vào yolo chưa, cho tôi tham khảo code với

**Comment by dt140120** [comment]
@viethoang303 
Ông nhúng được wbf vào yolo chưa cho tôi tham khảo code với

**Comment by glenn-jocher** [comment]
@dt140120 
Xin chào! Xin lưu ý rằng YOLOv5 không hỗ trợ trực tiếp WBF trong mã nguồn gốc. Tuy nhiên, bạn có thể triển khai WBF bằng cách sử dụng các thư viện Python như `Weighted-Boxes-Fusion` trong quá trình xử lý kết quả của mô hình YOLOv5.

Về cơ bản, WBF nhằm kết hợp các hộp phát hiện từ nhiều mô hình YOLOv5 lại và thực hiện quá trình NMS trên tập hợp hộp phát hiện kết hợp đó. Điều này có thể giúp cải thiện kết quả bằng cách bỏ qua các sự nhầm lẫn và tăng cường sự chính xác.

Để triển khai WBF trong YOLOv5, bạn có thể sử dụng các hàm và phương thức được cung cấp bởi `Weighted-Boxes-Fusion` để xử lý hộp phát hiện và các điểm số, nhãn tương ứng. Bạn có thể xem xét đảm bảo rằng các thông số và cài đặt của WBF đang được điều chỉnh đúng cách để đạt được kết quả tốt hơn.

Tuy nhiên, lưu ý rằng WBF không đảm bảo sẽ tăng mAP trong mọi trường hợp, và có thể gây giảm về hiệu suất. Việc sử dụng WBF cần được điều chỉnh và kiểm tra kỹ lưỡng để đảm bảo rằng nó thích hợp cho dữ liệu và công việc cụ thể của bạn.
