### ISSUE TITLE
Caching images gets stopped all of a sudden

### ISSUE THREAD

**Issue by debparth** [ultralytics/yolov5#2877]
## 🐛 Bug
When I try and use `--cache` while training then it automatically stops after acquiring ~45 GB space and then gets killed by itself. If I don't use cache then the training time kills me by giving me 52 mins in the epoch 0.

## Environment
 - OS: Ubuntu 
 - GPU: Tesla k80

## Additional context
![Screenshot 2021-04-21 183254](https://user-images.githubusercontent.com/53347017/115558383-4fc2dd00-a2d0-11eb-85bd-eb968b9ccd5d.png)

**Comment by glenn-jocher** [comment]
@debparth your system does not have sufficient memory.

Caching images is only recommended for smaller dataset or systems with sufficient available RAM. For training COCO at --img 640 you'd require about 150 GB of system RAM to use the --cache option.

**Comment by debparth** [comment]
@glenn-jocher ok. Is there a way to train model on large dataset without taking long time (52 mins) on one epoch?

**Comment by glenn-jocher** [comment]
@debparth for faster training or inference:

- use a smaller model
- use a smaller dataset
- use a smaller --img-size
- use a faster GPU
- use a larger batch size
- use Multi-GPU DPP
- use a verified environment like our Docker Image
