### ISSUE TITLE
feature map

### ISSUE THREAD

**Issue by limbo-zhj** [ultralytics/yolov5#2878]
Hello, how can I output the feature map or hot map of each layer

**Comment by glenn-jocher** [comment]
@limbo-zhj this has been asked before, but typically users don't understand the number of feature maps they would be dealing with. The YOLOv5l model for example has over a thousand output feature maps, each with it's own 80x80, 40x40 or 20x20 gird that you could look at. We don't have a standard method for viewing these, but they are easily extractable in the Detect() layer of any YOLOv5 model:

https://github.com/ultralytics/yolov5/blob/5f7d39fede4de8af98472bd009c63c3a86568e2d/models/yolo.py#L24-L58

**Comment by kimsung-git** [comment]
@glenn-jocher 
I'm also in attempt to extract feature map from the Detect as you mentioned. After printing out the input x to forward(), I verified that the shape of x is different from what you mentioned above. The the dimension I got for x is the following:

torch.Size([1, 256, 48, 80]), torch.Size([1, 512, 24, 40]), torch.Size([1, 1024, 12, 20])

I understand that the shape changes to [1, 255, 48, 80] [1, 255, 24, 40] [1, 255, 12, 20] after conv in foward(), but how come the input x dimension is not 80x80, 40x40, 20x20, but 48x80, 24x40, 12x20?

Can you explain why it is so?

Thank you

**Comment by glenn-jocher** [comment]
@kimsung-git output shapes are a function of input shapes.

**Comment by kimsung-git** [comment]
@glenn-jocher when you said "output shape", you meant x in Detect's forward method and "input shape" an image size? 

Isn't input shapes(img size) always fixed before feeding to the network i.e 640? I also tested image with different size but it's the same shapes: 48x80, 24x40, 12x20..

Thank you

**Comment by glenn-jocher** [comment]
@kimsung-git detect.py displays input shapes directly, you might want to start there:
```
python detect.py
```

**Comment by glenn-jocher** [comment]
@limbo-zhj @kimsung-git good news 😃! Feature map visualization was added ✅ in PR #3804 by @Zigars today. This allows for visualizing feature maps from any part of the model from any function (i.e. detect.py, train.py, test.py). Feature maps are saved as *.png files in runs/features/exp directory. To turn on feature visualization set `feature_vis=True` in the model forward method and define the layer you want to visualize (default is SPP layer).

https://github.com/ultralytics/yolov5/blob/20d45aa4f18d7df7148fc6dd69a9c0607003f004/models/yolo.py#L158-L160

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

![layer_8_SPP_features](https://user-images.githubusercontent.com/26833433/123628234-27e17f80-d813-11eb-8d72-5d5560cd9ee4.png)
