### ISSUE TITLE
Problems Running Test.py

### ISSUE THREAD

**Issue by murthax** [ultralytics/yolov5#288]
Hi All,

I was trying to get this working on a Jetson Nano. I tried to keep track of the steps I performed but it got a bit chaotic!

I did get PyTorch installed via https://forums.developer.nvidia.com/t/pytorch-for-jetson-nano-version-1-5-0-now-available/72048

I also installed prereqs from:

https://github.com/topiaruss/yolov5/blob/master/aarch64.Dockerfile

I did run into some issues but I thought I worked around them.

Here is a list (hopefully) of what I installed:
Package                       Version
----------------------------- -------------------
absl-py                       0.9.0
apt-clone                     0.2.1
apturl                        0.5.2
asn1crypto                    0.24.0
beautifulsoup4                4.6.0
blinker                       1.4
Brlapi                        0.6.6
cachetools                    4.1.1
certifi                       2020.6.20
chardet                       3.0.4
cryptography                  2.1.4
cupshelpers                   1.0
cycler                        0.10.0
Cython                        0.29.20
decorator                     4.1.2
defer                         1.0.6
distro-info                   0.18ubuntu0.18.04.1
feedparser                    5.2.1
google-auth                   1.18.0
google-auth-oauthlib          0.4.1
graphsurgeon                  0.4.4
grpcio                        1.30.0
html5lib                      0.999999999
httplib2                      0.9.2
idna                          2.10
importlib-metadata            1.7.0
Jetson.GPIO                   2.0.8
kazam                         1.4.5
keyring                       10.6.0
keyrings.alt                  3.0
language-selector             0.1
launchpadlib                  1.10.6
lazr.restfulclient            0.13.5
lazr.uri                      1.0.3
louis                         3.5.0
lxml                          4.2.1
macaroonbakery                1.1.3
Mako                          1.0.7
Markdown                      3.2.2
MarkupSafe                    1.0
matplotlib                    2.1.1
numpy                         1.19.0
oauth                         1.0.1
oauthlib                      3.1.0
olefile                       0.45.1
PAM                           0.4.2
pandas                        0.22.0
Pillow                        5.1.0
pip                           20.1.1
protobuf                      3.12.2
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycairo                       1.16.2
pycrypto                      2.6.1
pycups                        1.9.73
pygobject                     3.26.1
PyICU                         1.9.8
PyJWT                         1.5.3
pymacaroons                   0.13.0
PyNaCl                        1.1.2
pyparsing                     2.2.0
pyRFC3339                     1.0
python-apt                    1.6.5+ubuntu0.3
python-dateutil               2.6.1
python-debian                 0.1.32
pytz                          2018.3
pyxdg                         0.25
PyYAML                        5.3.1
requests                      2.24.0
requests-oauthlib             1.3.0
requests-unixsocket           0.1.5
rsa                           4.6
scipy                         0.19.1
SecretStorage                 2.3.1
setuptools                    48.0.0
simplejson                    3.13.2
six                           1.15.0
ssh-import-id                 5.7
system-service                0.3
systemd-python                234
tensorboard                   2.2.2
tensorboard-plugin-wit        1.7.0
tensorrt                      7.1.0.16
torch                         1.4.0
torchvision                   0.2.2.post3
tqdm                          4.47.0
ubuntu-drivers-common         0.0.0
uff                           0.6.7
unity-scope-calculator        0.1
unity-scope-chromiumbookmarks 0.1
unity-scope-colourlovers      0.1
unity-scope-devhelp           0.1
unity-scope-firefoxbookmarks  0.1
unity-scope-manpages          0.1
unity-scope-openclipart       0.1
unity-scope-texdoc            0.1
unity-scope-tomboy            0.1
unity-scope-virtualbox        0.1
unity-scope-yelp              0.1
unity-scope-zotero            0.1
urllib3                       1.25.9
urwid                         2.0.1
wadllib                       1.3.2
webencodings                  0.5
Werkzeug                      1.0.1
wheel                         0.34.2
xkit                          0.0.0
zipp                          3.1.0
zope.interface                4.3.2

when I try and  run the test.py I get:

python3 test.py
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/murthax/Downloads/yolov5-master/test.py", line 5, in <module>
    from utils.datasets import *
  File "/home/murthax/Downloads/yolov5-master/utils/datasets.py", line 12, in <module>
    import torch
  File "/usr/local/lib/python3.6/dist-packages/torch/__init__.py", line 81, in <module>
    from torch._C import *
ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory

**Comment by glenn-jocher** [comment]
@murthax nothing in this repo has ever advised anyone to insert a -m in front of a command.
