### ISSUE TITLE
Output nodes before 5D Reshape

### ISSUE THREAD

**Issue by PiyalGeorge** [ultralytics/yolov5#2881]
Can you specify the output nodes before 5D Reshape?
I'm using a 320X320 yolov5s model from 3.1 release.

Or 

In other way:
I converted the yolov5s model to onnx model following [this](https://github.com/ultralytics/yolov5/issues/251) .
Then i simplified the onnx model using [this](https://github.com/daquexian/onnx-simplifier) . I tried this in yolov5s - [release number :3.1](https://github.com/ultralytics/yolov5/releases/tag/v3.1)

I wish to know "the output nodes before 5D Reshape". How can i get these output nodes? Kindly help me to know these output nodes.

**Comment by glenn-jocher** [comment]
@PiyalGeorge I'm not sure exactly what you mean by the output nodes before 5D reshape, though the 5D reshape is in the Detect layer, so what you are looking for is probably there.

https://github.com/ultralytics/yolov5/blob/5f7d39fede4de8af98472bd009c63c3a86568e2d/models/yolo.py#L24-L58

On a side note, onnx-simplifier is now integrated with YOLOv5 export via PR https://github.com/ultralytics/yolov5/pull/2815,  you can access it like this in the latest code:
```
python export.py --simplify
```

**Comment by PiyalGeorge** [comment]
@glenn-jocher , Thanks for your reply. 
By "the output nodes before 5D Reshape" - I'm expecting the three output nodes like 742, 762, 782. 
These node number(eg:742, 762, etc) seems different in each release of yolov5s. 
What i want is, for the release number - 3.1 , yolov5s, 320X320 (or 416X416). Hope you got what i had in mind.

**Comment by glenn-jocher** [comment]
@PiyalGeorge these operations are in the Detect() layer before merging into a single output:
https://github.com/ultralytics/yolov5/blob/5f7d39fede4de8af98472bd009c63c3a86568e2d/models/yolo.py#L24-L58

**Comment by PiyalGeorge** [comment]
thanks @glenn-jocher ,

The reason i asked the question is because of this - https://developer.qualcomm.com/docs/snpe/revision_history.html
As per the qualcomm, they have added support for yolov5. So i was trying to figure it out. But still no luck.

**Comment by glenn-jocher** [comment]
@PiyalGeorge that's awesome that Qualcomm has added support for YOLOv5 models!! I didn't know about that. I wonder if they have more documentation?

**Comment by PiyalGeorge** [comment]
My ideas are from these links:- 

1. https://developer.qualcomm.com/comment/reply/68483#comment-form
2. https://docs.ultralytics.com/yolov5/tutorials/model_export
3. https://developer.qualcomm.com/docs/snpe/model_conv_tensorflow.html
4. https://github.com/onnx/onnx-tensorflow/issues/749

In the qualcomm's SNPE, the final model format we want is a .dlc file. Since there is no direct method to convert .pt file to .dlc, we need to convert the .pt file to onnx then to .dlc (that's the whole idea i get from first link). 
So first need to convert a .pt file to onnx, using 2nd link OR onnx-simplifier mentioned in 1st link. 
Once we get onnx we need the out_node to convert it to .dlc like mentioned in link 3, 4. Used netron viewer to view the onnx model and there are three output nodes.

**Comment by glenn-jocher** [comment]
@PiyalGeorge you can skip the Detect() layer concatenation and grid op with the --train mode flag:
```
python models/export.py --train
```

Make sure you use the latest master, we recently pushed a fix for this.

**Comment by evdoks** [comment]
@PiyalGeorge were you able to export an already trained YOLOv5 model to DLC?
My understanding is that export with `--train` flag results in ONNX representation without the detection layer and thus cannot be used for detection. What would be the purpose of such an export or am I missing something?

**Comment by PiyalGeorge** [comment]
Sorry to disappoint, i couldnt figure it out. Its possible, but i was busy.
