### ISSUE TITLE
Verification/test results used for labeling verification

### ISSUE THREAD

**Issue by leeyunhome** [ultralytics/yolov5#2884]
## ❔Question

In the case of yolov5, x, y, w, and h of the detected class are displayed, right?
If the reasoning result is wrong when checked with human eyes
We could use the x, y, w, h information at that time to re-label it, right?

**Comment by glenn-jocher** [comment]
@leeyunhome yes you can view the xywh predictions directly, i.e.:

```python
import cv2
import torch
from PIL import Image

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Images
for f in ['zidane.jpg', 'bus.jpg']:  # download 2 images
    print(f'Downloading {f}...')
    torch.hub.download_url_to_file('https://github.com/ultralytics/yolov5/releases/download/v1.0/' + f, f)
img1 = Image.open('zidane.jpg')  # PIL image
img2 = cv2.imread('bus.jpg')[:, :, ::-1]  # OpenCV image (BGR to RGB)
imgs = [img1, img2]  # batch of images

# Inference
results = model(imgs, size=640)  # includes NMS

# Results
results.print()  
results.xyxy[0]  # img1 predictions (tensor)
results.pandas().xyxy[0]  # img1 predictions xyxy (pandas)
results.pandas().xyxyn[0]  # img1 predictions xywh normalized (pandas)



YOLOv5 🚀 2021-4-22 torch 1.8.1 CPU
Downloading zidane.jpg...
100%|██████████| 165k/165k [00:00<00:00, 6.07MB/s]
Downloading bus.jpg...
100%|██████████| 476k/476k [00:00<00:00, 8.13MB/s]
image 1/2: 720x1280 2 persons, 2 ties
image 2/2: 1080x810 4 persons, 1 bus
Speed: 16.7ms pre-process, 357.3ms inference, 2.2ms NMS per image at shape (2, 3, 640, 640)

       xcenter     ycenter       width      height  confidence  class    name
0   948.558960  374.111023  398.173828  660.908081    0.874176      0  person
1   475.620911  574.206726   83.908081  280.874512    0.688576     27     tie
2   605.291809  451.991333  980.476929  512.460205    0.625422      0  person
3  1007.107422  362.175964   41.818298  116.033813    0.286980     27     tie

    xcenter   ycenter     width    height  confidence  class    name
0  0.741062  0.519599  0.311073  0.917928    0.874176      0  person
1  0.371579  0.797509  0.065553  0.390103    0.688576     27     tie
2  0.472884  0.627766  0.765998  0.711750    0.625422      0  person
3  0.786803  0.503022  0.032671  0.161158    0.286980     27     tie
```

**Comment by xinxin342** [comment]
@glenn-jocher  How can we do this with models we have trained locally, rather than loading them online? 

model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

**Comment by glenn-jocher** [comment]
@xinxin342 see PyTorch Hub tutorial for loading custom/local models:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [ONNX and TorchScript Export](https://docs.ultralytics.com/yolov5/tutorials/model_export)
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by parniantaghipour** [comment]
Hi,
I have tried to use results.pandas().xyxy[0]  # img1 predictions xyxy (pandas)
to check the result,  but I got "AttributeError: 'Detections' object has no attribute 'pandas'"
I can get the result in tensor format though.
What should I do to make it work?

**Comment by glenn-jocher** [comment]
@parniantaghipour your code is out of date.  To update YOLOv5 you can:
- `git pull` from within your `yolov5/` directory
- `git clone https://github.com/ultralytics/yolov5` again
- Force-reload [PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/): `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- View our updated notebooks:  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

**Comment by parniantaghipour** [comment]
@glenn-jocher 
Thank you with your help.
I am using custom model and I was using this line to load it.
model = torch.hub.load('ultralytics/yolov5', 'custom', path_or_model='best.pt')  # custom model
when I ass that force_reload=True to it, it starts to give me error saying"TypeError: custom() got an unexpected keyword argument 'path_or_model'"
am I supposed to change this line?

**Comment by lewisMurch** [comment]
> @glenn-jocher
> Thank you with your help.
> I am using custom model and I was using this line to load it.
> model = torch.hub.load('ultralytics/yolov5', 'custom', path_or_model='best.pt') # custom model
> when I ass that force_reload=True to it, it starts to give me error saying"TypeError: custom() got an unexpected keyword argument 'path_or_model'"
> am I supposed to change this line?

Did you ever find a fix for this?

**Comment by glenn-jocher** [comment]
@lewisMurch see YOLOv5 **PyTorch Hub** tutorial for current commands:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by fergil-mills** [comment]
> Did you ever find a fix for this?

@lewisMurch
Hey, I had a similar error ( 'TypeError: custom() got an unexpected keyword argument 'path_or_model' ) which was resolved by us changing 'path_or_model' to 'path'. I don't know if that fix is wise in the long run, but it might be worth a try.

**Comment by glenn-jocher** [comment]
@ycajal @lewisMurch @parniantaghipour correct syntax for custom model loading:

## Custom Models
This example loads a custom 20-class [VOC](https://github.com/ultralytics/yolov5/blob/master/data/voc.yaml)-trained YOLOv5s model `'best.pt'` with PyTorch Hub.
```python
model = torch.hub.load('ultralytics/yolov5', 'custom', path='path/to/best.pt')  # local model
model = torch.hub.load('path/to/yolov5', 'custom', path='path/to/best.pt', source='local')  # local repo
```

**Comment by Barry04** [comment]
![image](https://user-images.githubusercontent.com/61132615/161100545-b5a73827-7383-4ddc-af2a-2ff4bbacbc1f.png)
为什么我不行，使用的是官方的方法。出现上面的情况。

**Comment by glenn-jocher** [comment]
@Barry04 your pytorch is likely out of date. See https://pytorch.org/get-started/locally/ to update

**Comment by Barry04** [comment]
https://github.com/ultralytics/yolov5/issues/2884#issuecomment-1084953202
![image](https://user-images.githubusercontent.com/61132615/164619493-73a0a0fc-b25c-4a69-84ff-c1fc4ae63074.png)
1.9不支持吗？我看到写的是1.7以上就可以的？需要升级到1.11？
