### ISSUE TITLE
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 16, 1, 1])

### ISSUE THREAD

**Issue by starsky68** [ultralytics/yolov5#2885]
## ❔Question
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 16, 1, 1])

## Additional context
在运行的时候，会莫名其妙出现这个错误，然后早dataloader中使用了drop_last=True仍然没用

**Comment by fynlmq** [comment]
解决了嘛？怎么回事这是

**Comment by glenn-jocher** [comment]
@fynlmq 嗨，感谢您的问题！这个错误通常是由于网络输出维度不正确引起的。这可能是由于模型结构或数据处理的问题导致的。请确保网络输出的维度是正确的，并且检查数据处理部分以确保没有问题。如果您有任何问题，请随时咨询，我们会尽力帮助您解决问题。感谢您的理解和支持！
