### ISSUE TITLE
how can i reduce the number of layers and start training ? is it possible that from the excisting 100+ layers , that i'm reducing it to a 20 layer network ?

### ISSUE THREAD

**Issue by gokulsoman15** [ultralytics/yolov5#2887]

**Comment by glenn-jocher** [comment]
@gokulsoman15 you can modify model architecture by changing the model yaml files, and you can reduce layer count by reducing model depth multiple: 
https://github.com/ultralytics/yolov5/blob/78fd0776571589a2a85b9245b15798497ef104d3/models/yolov5s.yaml#L1-L5

**Comment by DiogoFerreira77** [comment]
And if I change the layer channel multiple value?

**Comment by glenn-jocher** [comment]
@DiogoFerreira77 yes, you can also change the channel multiplier for each layer to reduce the model size further. Check the model yaml files for the specific layer configurations: https://github.com/ultralytics/yolov5/blob/78fd0776571589a2a85b9245b15798497ef104d3/models/yolov5s.yaml
