### ISSUE TITLE
about Pytorch.hub.load

### ISSUE THREAD

**Issue by ZixuanLingit666** [ultralytics/yolov5#2888]
I already set the parameter of "force_reload=True", this problem can't be solved.

Can anyone help me?

![image](https://user-images.githubusercontent.com/52994675/115657685-e7283e80-a369-11eb-8252-035c575e3af1.png)

**Comment by glenn-jocher** [comment]
@rerester can you run `git tag` and upload your response here?

**Comment by ZixuanLingit666** [comment]
sorry， I am not familiar with complex command of git


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ultralytics/yolov5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月22日(星期四) 晚上8:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ultralytics/yolov5] about Pytorch.hub.load (#2888)





 
@rerester can you run git tag and upload your response here?

**Comment by glenn-jocher** [comment]
@rerester I'm wondering if the error may be due to git not being installed in your system. If you run `git --version` for example at the command line you should be able to tell. Can you run and upload a screenshot?

**Comment by ZixuanLingit666** [comment]
> @rerester I'm wondering if the error may be due to git not being installed in your system. If you run `git --version` for example at the command line you should be able to tell. Can you run and upload a screenshot?

oh, it works! thank!!
