### ISSUE TITLE
Hi,every one,two questions during trainning custom data

### ISSUE THREAD

**Issue by keithyh** [ultralytics/yolov5#289]
I have two datasets,both have four classes.

1.This question occurs with both datasets. While trainning,I saw "Using CPU" printed and gpu_mem is always 0G,although my machine is equiped with gpu.

2.This question occurs with only one dataset.Although I follow the same routine to train custom data,one dataset loaded pretrained weights successfully ,that is 
 python train.py --img-size 640 --batch-size 16 --epochs 300 --data ./data/dataset1.yaml --cfg ./models/yolov5s.yaml --weights weights/yolov5s.pt can be run successfully,while the other dataset can not load pretrained weights and I have to use 

python train.py --img-size 640 --batch-size 16 --epochs 300 --data ./data/dataset2.yaml --cfg ./models/yolov5s.yaml --weights ""   instead.

**Comment by NanoCode012** [comment]
1) Did u install everything properly? I got that issue if I didn't install cuda
2) What is the code for the dataset that doesn't work with pre-trained?

**Comment by keithyh** [comment]
1. I train two datasets on two Ubuntu machine,both with cuda installed
2.The codes for both datasets are identical and unchanged compared to the original,only yaml config files are modified

**Comment by NanoCode012** [comment]
1) Can you try run the code below? Can you tell me what you got?
```python
#From tutorial.ipynb
import torch
print('Setup complete. Using torch %s %s' % (torch.__version__, torch.cuda.get_device_properties(0) if torch.cuda.is_available() else 'CPU'))
```
2) I've never had problem using pre-trained. What is the error that comes with the dataset when trying to preload?

**Comment by keithyh** [comment]
1.Hi,thank you,your code exposed the problem.Perhaps it is because my cuda version is incompatible with torch1.5.1.
torch.cuda.is_available() returns False and my cuda version is 9.0.

2.My error is 
Traceback (most recent call last):
  File "train.py", line 394, in <module>
    train(hyp)
  File "train.py", line 123, in train
    raise KeyError(s) from e
KeyError: "./weights/yolov5s.pt is not compatible with ./models/yolov5s.yaml. This may be due to model differences or ./weights/yolov5s.pt may be out of date. Please delete or update ./weights/yolov5s.pt and try again, or use --weights '' to train from scratch."

when I load best.pt as pretrained model which trained 272 epochs there is no problem and the starting epoch is 272

**Comment by NanoCode012** [comment]
2. a ) Did u try to follow the suggestion? (Delete weights)
    b ) Did u change yolov5s.yaml to correct class number?

> when I load best.pt as pretrained model which trained 272 epochs there is no problem and the starting epoch is 272

I don't get what you are trying to do here. Resume training? Start training? I thought the problem was that you couldn't start it because you cannot load pre-trained weights.

**Comment by keithyh** [comment]
a) If "Delete weights" means the option --weights "" in the command line,then I have tried it and it works.
b)Yes I have
Load best.pt means resume training,and it works.I just cannot load pretrained weights.Succeed in loading pretrained weights on machine A dataset A but failed on machine B dataset B.Both machine have GPU

**Comment by NanoCode012** [comment]
a) Delete weights means to digitally delete it, then redownload

**Comment by keithyh** [comment]
Okay I am curious about  how to do that :-)

**Comment by NanoCode012** [comment]
Uhm, delete the pretrained weights. Then run the script with `--weights yolov5s.pt` or your chosen weights. The code will automatically download new one back.

I suggest re-reading the tutorial with a new git clone.

**Comment by keithyh** [comment]
Thanks ,sounds good -:)
