### ISSUE TITLE
bug of PyTorch.hub

### ISSUE THREAD

**Issue by ZixuanLingit666** [ultralytics/yolov5#2894]
## ❔Question
I have run many times, but the exception below can't be solved? my operating system is windows10  

## Additional context
![image](https://user-images.githubusercontent.com/52994675/115713583-c206f080-a3a8-11eb-9eff-acdeb19816ab.png)

**Comment by glenn-jocher** [comment]
@rerester good news 😃! Your original issue may now been fixed ✅ in PR #2900.  To receive this update you can:
- `git pull` from within your `yolov5/` directory
- `git clone https://github.com/ultralytics/yolov5` again
- Force-reload PyTorch Hub: `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
