### ISSUE TITLE
MODEL Size

### ISSUE THREAD

**Issue by erolgerceker** [ultralytics/yolov5#29]
How can i reduce the model size? or convert another format?
it is too big (240MB) :(
i used the tiny model but accuracy is not sufficent

**Comment by glenn-jocher** [comment]
@erolgerceker YOLOv5s is 27 MB.

**Comment by erolgerceker** [comment]
> @erolgerceker YOLOv5s is 27 MB.
i tried but couldnt train. i got this error.
ModuleNotFoundError: No module named 'models.yolo'; 'models' is not a package

**Comment by glenn-jocher** [comment]
@erolgerceker can you reproduce in a colab notebook?

**Comment by erolgerceker** [comment]
> @erolgerceker can you reproduce in a colab notebook?

i tried the tiny model and create new little size model but it is not working well like normal model. accuracy is too low while using tiny-model

**Comment by glenn-jocher** [comment]
@erolgerceker I don't understand what you're talking about. Are you saying there is no error as you showed below?

> > @erolgerceker YOLOv5s is 27 MB.
> > i tried but couldnt train. i got this error.
> > ModuleNotFoundError: No module named 'models.yolo'; 'models' is not a package
