### ISSUE TITLE
A question between your yoloV3 and your yolov5

### ISSUE THREAD

**Issue by zhongqiu1245** [ultralytics/yolov5#290]
Thank you for your amazing job!
Could you tell me what is the difference in performance(COCO mAP，ignore FPS) between your yoloV3 works using yolov4.cfg and yolov5 using yolov5s.yaml,......yolov5x.yaml?
 Who is the best?
What is their performance ranking(COCO mAP，ignore FPS) ？
Thank you!

**Comment by glenn-jocher** [comment]
@zhongqiu1245 all metrics are listed in both readmes. Suggest you read the readme.
