### ISSUE TITLE
About the Input Shape(HxW) question.

### ISSUE THREAD

**Issue by Zpadger** [ultralytics/yolov5#2902]
## ❔Question
The difference between picture input size (640×640) and (608×608).
## Additional context
Hello, everyone, I saw a saying on the Internet: "For example, the image input size of 416×416, 608×608, etc. is commonly used in the Yolo algorithm." At the same time, it pointed out that the image input of the YOLOv5 network model is also "608×608", but I noticed that the online opinions about the image input size are inconsistent. There is also a saying that the YOLOv5 network image input size is "640×640". I read the YOLOv5 source code, where "datasets.py" defines the letterbox, the specified picture The size is "new_shape=(640, 640)".
`def letterbox(img, new_shape=(640, 640), color=(114, 114, 114), auto=True, scaleFill=False, scaleup=True, stride=32):
    # Resize and pad image while meeting stride-multiple constraints
    shape = img.shape[:2]  # current shape [height, width]
    if isinstance(new_shape, int):
        new_shape = (new_shape, new_shape)`
 How do you understand difference between two picture input sizes? Is it related to the parameter "--img 640" set during training? Sincerely look forward to your reply.

**Comment by Zpadger** [comment]
@glenn-jocher Can you help me?Thank you.

**Comment by glenn-jocher** [comment]
@Zpadger 640 is the default YOLOv5 image size. You can vary this size using the --img-size argument in train.py, detect.py, test.py, export.py:
https://github.com/ultralytics/yolov5/blob/14d2d2d75fff27a9deb183c9cb76f107f43ca3ad/detect.py#L156

**Comment by Zpadger** [comment]
@glenn-jocher I see, thank you very much for your guidance
