### ISSUE TITLE
Only when I change the pytorch version to 1.7.0 (default version is 1.8.1) in requirments.txt then model for android is sucessfully exported.

### ISSUE THREAD

**Issue by duwangthefirst** [ultralytics/yolov5#2903]
Basically I'm following the official colab notebook.
the training procedure is all fine.

According to [https://github.com/pytorch/android-demo-app/tree/master/ObjectDetection](https://github.com/pytorch/android-demo-app/tree/master/ObjectDetection), I updated `models/export.py` like this:
- Change  `from model.model[-1].export = not opt.grid` to `model.model[-1].export = False`
- Add the following two lines of model optimization code, between `ts = torch.jit.trace(model, img)` and `ts.save(f)`:
```python
from torch.utils.mobile_optimizer import optimize_for_mobile
ts = optimize_for_mobile(ts)
```

and then I run:
```
python models/export.py --weights runs/train/exp/weights/last.pt --img-size 640 --batch-size 1
```
then it failed to generate last.torchscript.pt.

Only after I change the requirements.txt from:
```
torch>=1.7.0
torchvision>=0.8.1
```
to:
```
torch==1.7.0
torchvision==0.8.1
```

**and the installed pytorch will be of version 1.7.0 instead of 1.8.1 and finally the `last.torchscript.pt` is sucessfully generated.**

**My question is: When will this MODEL EXPORT function be compatible with the latest version of pytorch ?**

**Comment by glenn-jocher** [comment]
@duwangthefirst I just tested export.py in Colab with PyTorch 1.8.1 and torchscript export works correctly, both with and with --grid:
<img width="1340" alt="Screenshot 2021-04-23 at 13 10 27" src="https://user-images.githubusercontent.com/26833433/115863169-60d92e80-a435-11eb-8070-09bb246781b1.png">

If you believe you have a reproducible issue, we suggest you close this issue and raise a new one using the 🐛 **Bug Report template**, providing screenshots and a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. Thank you!

**Comment by glenn-jocher** [comment]
@duwangthefirst I've added default support for the PyTorch tutorial recommendation of running optimize_for_mobile() during torchscript export in PR #2908.
