### ISSUE TITLE
Loss almost did not decline.

### ISSUE THREAD

**Issue by Jinyong-Huang** [ultralytics/yolov5#291]
I tried rect==true and rect==false for training,  like python train.py --rect --batch_size 48 --cfg models/yolov5s.yaml  --data data/coco.yaml and python train.py --batch_size 48 --cfg models/yolov5s.yaml --data data/coco.yaml.  these two methods are not good. unlike training_results/results_yolov5s.txt.

results.txt:
     0/299     8.85G   0.09969    0.1017   0.09657     0.298       204       640         0         0 5.602e-05 1.021e-05   0.09888      0.09   0.09435
     1/299     8.12G   0.09384    0.1076   0.09419    0.2956       163       640         0         0 0.0003639 0.0001071    0.0982   0.08958    0.0944
     2/299     8.12G   0.09238    0.1089   0.09368    0.2949       181       640         0         0 0.0005415  0.000197   0.09803   0.08973   0.09311
     3/299     8.12G   0.09198     0.109    0.0932    0.2942       177       640         0         0 0.0005212 0.0001748   0.09795   0.08979   0.09289
     4/299     5.45G   0.09673   0.07912   0.09349    0.2694       106       256         0         0 0.0003838  8.98e-05    0.1043    0.0818   0.09294
     5/299      7.9G   0.09667   0.07917   0.09343    0.2693       103       256         0         0 0.0005336 0.0001173    0.1028    0.0837   0.09285
     6/299      7.9G   0.09661   0.07933   0.09339    0.2693       105       256         0         0 0.0006297 0.0001562    0.1016   0.08538    0.0928
     7/299      7.9G   0.09662   0.07923   0.09338    0.2692       106       256         0         0 0.0006472 0.0001602     0.101   0.08596   0.09271
     8/299      7.9G   0.09659   0.07931   0.09337    0.2693       106       256    0.0125  1.16e-06 0.0006755 0.0001769   0.09906   0.08822   0.09253
     9/299      7.9G   0.09659   0.07924   0.09338    0.2692       106       256    0.0125 4.417e-05 0.0006773 0.0002365   0.09731   0.09014   0.09238
    10/299      7.9G   0.09657   0.07932   0.09332    0.2692        98       256    0.0125 4.417e-05  0.000647 0.0002272   0.09703   0.09041   0.09236
    11/299      7.9G   0.09654   0.07935   0.09332    0.2692       106       256         0         0 0.0005944 0.0002035   0.09699   0.09047   0.09235
    12/299      7.9G   0.09659    0.0793   0.09331    0.2692       103       256         0         0 0.0006117  0.000211     0.097   0.09046   0.09235
    13/299      7.9G   0.09657   0.07935    0.0933    0.2692       103       256         0         0 0.0006021 0.0002081     0.097   0.09045   0.09235
    14/299      7.9G   0.09658   0.07933   0.09332    0.2692       106       256         0         0 0.0006197 0.0002151   0.09702   0.09044   0.09236
    15/299      7.9G   0.09654   0.07933    0.0933    0.2692       102       256         0         0 0.0006285 0.0002237   0.09702   0.09042   0.09236
    16/299      7.9G   0.09657   0.07919    0.0933    0.2691       106       256         0         0 0.0006425 0.0002269   0.09703   0.09041   0.09236
    17/299      7.9G   0.09656   0.07937   0.09326    0.2692       104       256    0.0125 4.417e-05 0.0007215 0.0002673   0.09704   0.09039   0.09236
    18/299      7.9G   0.09655   0.07934   0.09324    0.2691       100       256    0.0125 4.417e-05 0.0007069 0.0002615   0.09705   0.09038   0.09236
    19/299      7.9G   0.09657   0.07929   0.09333    0.2692       105       256         0         0 0.0006088 0.0002078   0.09706   0.09037   0.09237
    20/299      7.9G   0.09653   0.07947   0.09331    0.2693       106       256         0         0 0.0006408 0.0002214   0.09707   0.09037   0.09237
    21/299      7.9G   0.09651   0.07944   0.09327    0.2692       105       256         0         0 0.0006158 0.0002055   0.09707   0.09037   0.09237
    22/299      7.9G   0.09658   0.07926   0.09333    0.2692       106       256         0         0 0.0005771 0.0001901   0.09726    0.0901   0.09239
    23/299      7.9G   0.09651   0.07941    0.0933    0.2692       104       256         0         0 0.0005753 0.0001856   0.09722   0.09016   0.09239
    24/299      7.9G    0.0965   0.07942    0.0933    0.2692       106       256         0         0 0.0005903 0.0001892   0.09718   0.09023   0.09238
    25/299      7.9G   0.09653    0.0794   0.09326    0.2692       106       256    0.0125 7.669e-05 0.0006168 0.0002053   0.09714   0.09029   0.09238
    26/299      7.9G   0.09652   0.07945   0.09329    0.2693       105       256    0.0125 7.669e-05 0.0006641 0.0002278   0.09711   0.09035   0.09238
    27/299      7.9G    0.0965   0.07936   0.09326    0.2691       101       256    0.0125 7.669e-05 0.0006486 0.0002203   0.09709   0.09036   0.09238
    28/299      7.9G   0.09652   0.07935   0.09328    0.2692       104       256         0         0  0.000629 0.0002099   0.09708   0.09038   0.09237
    29/299      7.9G    0.0965   0.07936   0.09325    0.2691       104       256         0         0 0.0006563 0.0002203   0.09706   0.09039   0.09237
    30/299      7.9G    0.0965    0.0794   0.09326    0.2692       100       256         0         0 0.0006005 0.0001981   0.09705   0.09041   0.09236
    31/299      7.9G   0.09653   0.07932   0.09328    0.2691       105       256         0         0 0.0006003 0.0001965   0.09704   0.09042   0.09236
    32/299      7.9G   0.09651   0.07929   0.09327    0.2691       105       256         0         0 0.0005948 0.0001968   0.09702   0.09045   0.09236
    33/299      7.9G   0.09651   0.07942   0.09324    0.2692       105       256         0         0 0.0005953 0.0001961   0.09701   0.09048   0.09236
    34/299      7.9G   0.09654   0.07937   0.09326    0.2692        98       256         0         0 0.0005832 0.0001946   0.09703   0.09046   0.09236
    35/299      7.9G   0.09649   0.07941   0.09324    0.2691       105       256         0         0 0.0005951 0.0002004   0.09702   0.09049   0.09235
    36/299      7.9G   0.09647   0.07944   0.09326    0.2692       105       256         0         0 0.0006001 0.0002014     0.097   0.09052   0.09235
    37/299      7.9G    0.0965   0.07933   0.09326    0.2691       106       256         0         0 0.0005942 0.0002006   0.09699   0.09053   0.09234
    38/299      7.9G   0.09648   0.07948   0.09325    0.2692       103       256         0         0 0.0005884 0.0001958   0.09698   0.09054   0.09234
    39/299      7.9G   0.09645    0.0795   0.09327    0.2692       105       256         0         0 0.0005886 0.0001982   0.09697   0.09057   0.09234
    40/299      7.9G   0.09647   0.07945   0.09325    0.2692       106       256         0         0 0.0005844 0.0001944   0.09697   0.09057   0.09234
    41/299      7.9G   0.09648   0.07938   0.09327    0.2691       105       256         0         0 0.0006052 0.0002019   0.09695   0.09058   0.09234
    42/299      7.9G   0.09649   0.07931   0.09327    0.2691       100       256         0         0 0.0006033 0.0002052   0.09695    0.0906   0.09234
    43/299      7.9G    0.0965   0.07945   0.09323    0.2692       106       256         0         0 0.0006294 0.0002201   0.09694    0.0906   0.09234
    44/299      7.9G   0.09648   0.07935   0.09321     0.269       106       256         0         0 0.0006214 0.0002108   0.09694   0.09062   0.09234
    45/299      7.9G   0.09647   0.07939   0.09322    0.2691       105       256         0         0  0.000613  0.000206   0.09694   0.09061   0.09233
    46/299      7.9G   0.09647   0.07938   0.09324    0.2691       105       256         0         0 0.0005995 0.0002028   0.09694   0.09062   0.09233
    47/299      7.9G   0.09649   0.07936   0.09325    0.2691       104       256         0         0 0.0006064 0.0002053   0.09694   0.09059   0.09233

**Comment by Jinyong-Huang** [comment]
results:
![results](https://user-images.githubusercontent.com/55069241/86504096-458a2d80-bde7-11ea-9051-107b069fe3d5.png)

**Comment by glenn-jocher** [comment]
@Jinyong-Huang see https://github.com/ultralytics/yolov5#reproduce-our-training

**Comment by Jinyong-Huang** [comment]
I just set the batch_size=48. but the training results are quite different.

**Comment by glenn-jocher** [comment]
@Jinyong-Huang yes, results will change when you change batch-size.

**Comment by QinWinner** [comment]
> I just set the batch_size=48. but the training results are quite different.

And I you're having the same problem, but the batch can only be set to 32.Do you have another solution?
