### ISSUE TITLE
Hyperparameters evolution weird behavior

### ISSUE THREAD

**Issue by JoeNajm** [ultralytics/yolov5#2913]
## ❔Question

Hello, I am currently evolving the hyperparameters of a network that I trained previously, however, I noticed a strange behavior : the program is doing 9 epochs per generation instead of 10 (even though I specified 10 epochs at the training command).

![hyperparam_weird](https://user-images.githubusercontent.com/80056479/115938093-3b363e80-a4a2-11eb-9161-ff2d5594ff12.PNG)

Moreover, it is running for more than 300 generations as I am currently at the generation 334 according to the evolve.txt file (even though I have "for _ in range(300)" line 585 of train.py).

Have you got any clue on when will the evolution will end and if that behavior is normal ?

Moreover, in the evolve folder, I have 2 yaml folders with hyperparameters : "hyp.yaml" and "hyp_evolved.yaml". What is the difference between these 2 ? Is "hyp_evolved.yaml" the file containing the optimal hyperparameters ? 

Thanks in advance

**Comment by glenn-jocher** [comment]
@JoeNajm well that's new, I've never seen an evolution base scenario that doesn't start at epoch 0, so I'm not sure what to say. You might want to review the hyperparameter evolution tutorial. It's generally up to you to review your results periodically and you're free to quit when they've settled at a local minimum and stopped improving.

Yes hyp_evolved.yaml are your evolved hyperparameters.
