### ISSUE TITLE
precision-recall curve

### ISSUE THREAD

**Issue by maidna-crypto** [ultralytics/yolov5#2917]
## ❔Question

hi. I've trained yolov3 model on my custom dataset and then tested on a test dataset. the precision-recall curve result have some lines and coordinates on edges beside the blue result line that i don't understand what they are for. any help would be appreciated. 
![image](https://user-images.githubusercontent.com/82373861/115953848-b7308680-a4a2-11eb-9246-acf850aa9a6c.png)

**Comment by glenn-jocher** [comment]
@maidna-crypto grey lines are AP per class and blue line is mAP for all classes. For datasets with < 20 classes the AP of each class is additionally shown in the legend and each grey line is colored.
