### ISSUE TITLE
How to get VisDrone labels for train?

### ISSUE THREAD

**Issue by nocolour** [ultralytics/yolov5#2920]
## ❔Question
How to generate visdrone labels?

## Additional context

Transferred 356/362 items from yolov5s.pt
Scaled weight_decay = 0.0005
Optimizer groups: 62 .bias, 62 conv.weight, 59 other
train: Scanning '../VisDrone/VisDrone2019-DET-train/labels.cache' images and labels... 0 found, 6471 missing, 0 empty, 0 corrupted: 100%|█| 6471/6471 [00:00<?, ?it/Traceback (most recent call last):
  File "train.py", line 544, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 189, in train
    dataloader, dataset = create_dataloader(train_path, imgsz, batch_size, gs, opt,
  File "/home/desmond/Projects/Python/yolov5/utils/datasets.py", line 63, in create_dataloader
    dataset = LoadImagesAndLabels(path, imgsz, batch_size,
  File "/home/desmond/Projects/Python/yolov5/utils/datasets.py", line 396, in __init__
    assert nf > 0 or not augment, f'{prefix}No labels in {cache_path}. Can not train without labels. See {help_url}'
AssertionError: train: No labels in ../VisDrone/VisDrone2019-DET-train/labels.cache. Can not train without labels. See https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data
train: Scanning '../VisDrone/VisDrone2019-DET-train/labels.cache' images and labels... 0 found, 6471 missing, 0 empty, 0 corrupted: 100%|█| 6471/6471 [00:00<?, ?it/
(env) desmond@Goodboy:~/Projects/Python/yolov5$

**Comment by glenn-jocher** [comment]
@nocolour hi there, thanks for asking about our VisDrone autodownload. For this to work correclty, you simply train with the --data visdrone.yaml argument, and the dataset should download and labels should be converted to YOLO format automatically. I'll try it now to make sure it's working.
```bash
python train.py --data visdrone.yaml
```

Ah, I see there's a problem. I'll try to submit a PR to fix this.

**Comment by glenn-jocher** [comment]
@nocolour good news 😃! Your original issue may now been fixed ✅ in PR #2921.  To receive this update you can:
- `git pull` from within your `yolov5/` directory
- `git clone https://github.com/ultralytics/yolov5` again
- Force-reload PyTorch Hub: `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`

Please delete your existing VisDrone download folder and start over with:
```
python train.py --data visdrone.yaml
```

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by nocolour** [comment]
Thank you very must. It is working now. thanks
![Screenshot at 2021-04-27 10-01-05](https://user-images.githubusercontent.com/6244952/116173872-ec0d3980-a73f-11eb-83c2-1a6602e7dcae.png)

**Comment by glenn-jocher** [comment]
Great! 😃

**Comment by miladnasiri** [comment]
hello, how can i convert the annotation to yolo 7 format?

**Comment by glenn-jocher** [comment]
@miladnasiri hi there! You can convert annotations to YOLO format using the `labelImg` tool or by writing a script to convert annotations manually. Another option is to use our YOLOv5 [datasets tool](https://docs.ultralytics.com/yolov5/basics/usage/#create-datasets) to automatically convert annotations to YOLO format. Let me know if you need further help!
