### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by 15050188022** [ultralytics/yolov5#2930]
## ❔Question
if I want to implement inference process with a square size like  what is done in training process,where should I modifiy the code?
Thanks for your time.

**Comment by glenn-jocher** [comment]
@15050188022 there's no setting to force square inference in YOLOv5 as there's no benefit to this that I'm aware of.

If you really wanted to game the system you can create a batch of vertical and horizontal images and pass the batch to a PyTorch Hub model for inference, which will be forced to pad all the images to the same shape.

**Comment by 15050188022** [comment]
> @15050188022 there's no setting to force square inference in YOLOv5 as there's no benefit to this that I'm aware of.
> 
> If you really wanted to game the system you can create a batch of vertical and horizontal images and pass the batch to a PyTorch Hub model for inference, which will be forced to pad all the images to the same shape.

I wanna try something in the training process where the feature maps are all square but it will cause some bug in the inference.could you give me some advice for it？

**Comment by Bobo-y** [comment]
@15050188022  do you mean keep the input is like 640 * 640? in letterbox, set auto is False and scaleFill is False
