### ISSUE TITLE
View .mp4 video feed as it is performing inference

### ISSUE THREAD

**Issue by abuelgasimsaadeldin** [ultralytics/yolov5#2933]
## ❔Question
Hi, how do I view the inference process of my saved video file as it is being processed and bounding boxes are being drawn. I tried adding the argument ```--view-img``` but that just shows me a grey display and not my video.

P.S. The video does get saved in the end however after the processing, but I want to view it as it is being processed (similar to webcam pop-up).
```
python detect.py --source data/carplate-video.mp4 --weights yolov5s.pt --view-img
```

**Comment by glenn-jocher** [comment]
@abuelgasimsaadeldin your command works correctly for me, a live preview of the inference results is displayed in realtime:
```
python detect.py --source decelera_landscape.mov --view
```
<img width="2560" alt="Screenshot 2021-04-26 at 11 58 11" src="https://user-images.githubusercontent.com/26833433/116064970-ce2fce00-a686-11eb-86a1-3527c86aa09f.png">
