### ISSUE TITLE
How can I bridge torchprof with yolov5 to measure the latency?

### ISSUE THREAD

**Issue by jaskiratsingh2000** [ultralytics/yolov5#2936]
## ❔Question
How can I bridge torchprof with yolov5 to measure the latency?

## Additional context

If I want to bridge this YOLO version with the [torchprof package](https://pypi.org/project/torchprof/). I want to see layer-by-layer latency in this but unable to bridge that and it is not even written with the description. Can someone help me know how can I do that?

Please let me know.
here is the code for torchprof https://colab.research.google.com/drive/1NXix_OpbroRGayTLXRoQwLnRTE1eGWWG?usp=sharing

here is the code for running this yolov5 separately https://colab.research.google.com/drive/1-h9snr0Tu5BJj2lNpbbRRl7HHpxrcf1z?usp=sharing

Thanks

**Comment by jaskiratsingh2000** [comment]
@glenn-jocher Can you please help me with this? I would really appreciate your response. Thanks

**Comment by glenn-jocher** [comment]
@jaskiratsingh2000 we have an internal profiling tool in yolo.py, though it might be interesting to see other results also. I've never used torchprof before.

What problems are you encountering exactly?

**Comment by jaskiratsingh2000** [comment]
How can I run internal profiling tool? What command do I have to follow for
this? Can you let me know? I would be glad to try this.

Thanks

**Comment by jaskiratsingh2000** [comment]
@glenn-jocher How can I run internal profiling tool? What command do I have to follow for this? Can you let me know? I would be glad to try this.


Thanks

**Comment by jaskiratsingh2000** [comment]
Hey, can you please let me know on this
