### ISSUE TITLE
How can I run Pytorch Profiler with yolov5?

### ISSUE THREAD

**Issue by jaskiratsingh2000** [ultralytics/yolov5#2938]
## ❔Question
How can I run the PyTorch profile with yolov5?

## Additional context
I want to see within each layer. How can I run PyTorch profiler with ylov5?

**Comment by jaskiratsingh2000** [comment]
@glenn-jocher any help on this?

**Comment by glenn-jocher** [comment]
@jaskiratsingh2000 I'm not sure, I've never used pytorch profiler myself. What problems are you running into with it exactly?
