### ISSUE TITLE
Ratio between object size and image size

### ISSUE THREAD

**Issue by constantinfite** [ultralytics/yolov5#2939]
## ❔Question

Hi, I realized that when I run inference on video of size 1280x720 I am able to detect the object. However when I concatenate 4 video of size 1280x720 to one big of size 2560x1440 and I run inference on it some objects are not detected by yolo. 
The size of the object remains the same but compared to the entire image the object is smaller.

Here is an illustration : you can see that at the left the shark is detected but in the bottom left image the shark is not detected.
![Sans-titre-1](https://user-images.githubusercontent.com/57963890/116136493-aa927500-a6d2-11eb-8e26-c3ca8649588e.png)
 
Is it possible to have the same result when I concatenate and when I don't ?
Thanks!

**Comment by glenn-jocher** [comment]
@constantinfite sure. If you want the same result you need to run inference at the same resolution, i.e. --img 1280 on the left and --img 2560 on the right.

**Comment by constantinfite** [comment]
Thanks! but I train at the default resolution 640, this will not be a problem ?

**Comment by glenn-jocher** [comment]
@constantinfite if you train at 640 then you should run inference at no more than 640, or 1280 for your concatenated example.

In your original example unless you modify your inference size your objects are obviously shrinking and will be harder to spot clearly.

**Comment by constantinfite** [comment]
Ok thanks I will try at 1280 for the concat video

**Comment by constantinfite** [comment]
Thanks it works there is no difference now
