### ISSUE TITLE
How to extract the bounding box, confidences, score information from different layers other than the 3 default output layers

### ISSUE THREAD

**Issue by ithmz** [ultralytics/yolov5#2944]
## ❔Question
Dear team, 
I would like to ask some questions. My current platform does not support reading 5D output (as the default output layers are), only support <= 4D layers. Because of that, I have to extract the box, confidence and score from the layer before the Reshape layer (as in the attached photo) 
So what is the way to read from this layer, e.g (1,18,80,80).
Many thanks.
![Screenshot from 2021-04-27 18-00-11](https://user-images.githubusercontent.com/23276580/116224968-d7eb2b80-a783-11eb-8294-1b33a258039b.png)

**Comment by glenn-jocher** [comment]
@tsangz189 you can export with the --grid option to merge the 3 layers into a single 3D output:

## YOLOv5s ONNX `python models/export.py --grid --simplify`
<img width="1136" alt="Screenshot 2021-04-16 at 13 33 32" src="https://user-images.githubusercontent.com/26833433/115018681-7213bf80-9eb8-11eb-8eea-5ca3591eb99e.png">

**Comment by ithmz** [comment]
Hi @glenn-jocher, yes I can use the --grid to form into 1 single output, but the 5D layers before this couldn't be computed. So it will provide the wrong result on the last output.
Update/: I only has 1 class

**Comment by glenn-jocher** [comment]
@tsangz189 --grid produces a correct export, there are no known issues.

If you believe you have a reproducible issue, we suggest you close this issue and raise a new one using the 🐛 **Bug Report template**, providing screenshots and a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. Thank you!

**Comment by ithmz** [comment]
@glenn-jocher, let put it that way, so can I export the output directly from the output of the Conv layer?

**Comment by glenn-jocher** [comment]
@tsangz189 you can export anything you want with the right modifications. The default options available to you are in the export.py argparser:
https://github.com/ultralytics/yolov5/blob/4890499344e21950d985e1a77e84a0a4161d1db0/models/export.py#L24-L32
