### ISSUE TITLE
Using COCO metrics with my own dataset?

### ISSUE THREAD

**Issue by dariogonle** [ultralytics/yolov5#2946]
## ❔Question
Hi,

 it's possible to use COCO metrics to eval my own dataset? I mean my dataset follows the YOLO format: id, x_c, y_c, w, h, but I would like to know how good are AP_{Small, Medium, Large}. I know it's possible to implement ii by myself but I would like to know if it is already implemented.

Thank you.

**Comment by glenn-jocher** [comment]
@dariogonle any dataset with a COCO format JSON annotations file can be used. You can specify your JSON annotations file here on L256 of test.py:
https://github.com/ultralytics/yolov5/blob/4890499344e21950d985e1a77e84a0a4161d1db0/test.py#L253-L256

**Comment by dariogonle** [comment]
Thank you. But first, I need to convert my YOLO format annotations to json/COCO format, dont't I?

**Comment by glenn-jocher** [comment]
@dariogonle yes, pycocotools requires both predictions and labels in COCO format JSONs. We produce the predictions in this format, you would need to supply the labels JSONs.
