### ISSUE TITLE
Does number of classes need to include background when instantiating Model?

### ISSUE THREAD

**Issue by FraPochetti** [ultralytics/yolov5#2950]
## ❔Question
Hi Glenn,
quick one, please.
When we instantiate a new `Model` we have to pass the number of classes (`nc`), [here](https://github.com/ultralytics/yolov5/blob/4200674a136a5589972f352790f76d3f37e98dd6/models/yolo.py#L67).
Does `nc` need to include the `background` class? 
E.g. if I have 2 classes (`dog` and `cat`) does `nc` need to be equal to 3 or 2?

Thanks a lot!

**Comment by glenn-jocher** [comment]
@FraPochetti if your data has labels for dogs and cats then you have 2 classes.

**Comment by FraPochetti** [comment]
Thanks a ton!

**Comment by FraPochetti** [comment]
@glenn-jocher I have a follow-up question, please.
Does YOLO use a `background` class within the model at all?
Object Detection algos often rely on that additional class (`torchvision` does that for instance) to be able to differentiate the "actual" classes we are modeling VS "the rest".
Does YOLO do the same somewhere?

**Comment by glenn-jocher** [comment]
@FraPochetti no there is no background class, there is a seperate objectness output instead. See YOLOv3 paper:
https://arxiv.org/abs/1804.02767
