### ISSUE TITLE
What to write in place of the "device" in this code?

### ISSUE THREAD

**Issue by jaskiratsingh2000** [ultralytics/yolov5#2952]
## ❔Question
What to write in place of the device in this code?

## Additional context
Hey, I am trying to run the profiling and unable to understand that what I need to write in place of "device" in the following code.

```
img = torch.rand(8 if torch.cuda.is_available() else 1, 3, 320, 320).to(device) 
y = model(img, profile=True)
```

If in case I remove the "device" from here then it throws me the following error:
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-7-f21874f58c27> in <module>()
----> 1 img = torch.rand(8 if torch.cuda.is_available() else 1, 3, 320, 320).to(device)
      2 y = model(img, profile=True)

NameError: name 'device' is not defined
```

**Comment by glenn-jocher** [comment]
@jaskiratsingh2000 do not raise duplicate issues. This is already explained in https://github.com/ultralytics/yolov5/issues/2898#issuecomment-827129027
