### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered white train custom model yolov5

### ISSUE THREAD

**Issue by DINHQUANGMINH198** [ultralytics/yolov5#2956]
python train.py --img 416 --batch 16 --epochs 300 --data /data/minhdq/yolov5/ID_CARD_FRONT/data_ID_Front.yaml --cfg /data/minhdq/yolov5/models/yolov5s_ID_front.yaml --weights yolov5s.pt --name yolov5s_results  --cache

Output:
github: ⚠️ WARNING: code is out of date by 22 commits. Use 'git pull' to update or 'git clone https://github.com/ultralytics/yolov5' to download latest.
YOLOv5 🚀 v5.0-20-gd48a34d torch 1.8.1+cu111 CUDA:0 (GeForce RTX 3090, 24265.8125MB)

Namespace(adam=False, artifact_alias='latest', batch_size=16, bbox_interval=-1, bucket='', cache_images=True, cfg='/data/minhdq/yolov5/models/yolov5s_ID_front.yaml', data='/data/minhdq/yolov5/ID_CARD_FRONT/data_ID_Front.yaml', device='', entity=None, epochs=300, evolve=False, exist_ok=False, global_rank=-1, hyp='data/hyp.scratch.yaml', image_weights=False, img_size=[416, 416], label_smoothing=0.0, linear_lr=False, local_rank=-1, multi_scale=False, name='yolov5s_results', noautoanchor=False, nosave=False, notest=False, project='runs/train', quad=False, rect=False, resume=False, save_dir='runs/train/yolov5s_results13', save_period=-1, single_cls=False, sync_bn=False, total_batch_size=16, upload_dataset=False, weights='yolov5s.pt', workers=8, world_size=1)
tensorboard: Start with 'tensorboard --logdir runs/train', view at http://localhost:6006/
hyperparameters: lr0=0.01, lrf=0.2, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0
wandb: Install Weights & Biases for YOLOv5 logging with 'pip install wandb' (recommended)

                 from  n    params  module                                  arguments                     
  0                -1  1      3520  models.common.Focus                     [3, 32, 3]                    
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]                
  2                -1  1     18816  models.common.C3                        [64, 64, 1]                   
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]               
  4                -1  1    156928  models.common.C3                        [128, 128, 3]                 
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]              
  6                -1  1    625152  models.common.C3                        [256, 256, 3]                 
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]              
  8                -1  1    656896  models.common.SPP                       [512, 512, [5, 9, 13]]        
  9                -1  1   1182720  models.common.C3                        [512, 512, 1, False]          
 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]              
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 12           [-1, 6]  1         0  models.common.Concat                    [1]                           
 13                -1  1    361984  models.common.C3                        [512, 256, 1, False]          
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]              
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 16           [-1, 4]  1         0  models.common.Concat                    [1]                           
 17                -1  1     90880  models.common.C3                        [256, 128, 1, False]          
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]              
 19          [-1, 14]  1         0  models.common.Concat                    [1]                           
 20                -1  1    296448  models.common.C3                        [256, 256, 1, False]          
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]              
 22          [-1, 10]  1         0  models.common.Concat                    [1]                           
 23                -1  1   1182720  models.common.C3                        [512, 512, 1, False]          
 24      [17, 20, 23]  1     37758  models.yolo.Detect                      [9, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
Model Summary: 283 layers, 7085118 parameters, 7085118 gradients, 16.4 GFLOPS

Transferred 354/362 items from yolov5s.pt
Scaled weight_decay = 0.0005
Optimizer groups: 62 .bias, 62 conv.weight, 59 other
train: Scanning '/data/minhdq/yolov5/ID_CARD_FRONT/labels/train.cache' images and labels... 1075 found, 21 missing, 0 empty, 0 corrupted
train: Caching images (0.6GB): 100%|██████████████████████████████████████████████████████████████| 1096/1096 [00:00<00:00, 2065.56it/s]
val: Scanning '/data/minhdq/yolov5/ID_CARD_FRONT/labels/valid.cache' images and labels... 294 found, 6 missing, 1 empty, 0 corrupted: 10
val: Caching images (0.2GB): 100%|███████████████████████████████████████████████████████████████████| 300/300 [00:00<00:00, 787.89it/s]
Plotting labels... 

autoanchor: Analyzing anchors... anchors/target = 3.33, Best Possible Recall (BPR) = 1.0000
Image sizes 416 train, 416 test
Using 8 dataloader workers
Logging results to runs/train/yolov5s_results13
Starting training for 300 epochs...

     Epoch   gpu_mem       box       obj       cls     total    labels  img_size
     0/299     1.31G    0.1148   0.04381   0.06235     0.221        66       416: 100%|█████████████████| 69/69 [00:22<00:00,  3.00it/s]
               Class      Images      Labels           P           R      mAP@.5  mAP@.5:.95:  70%|████▏ | 7/10 [00:03<00:01,  1.67it/s]/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [79,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [1,0,0], thread: [125,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
               Class      Images      Labels           P           R      mAP@.5  mAP@.5:.95:  70%|████▏ | 7/10 [00:04<00:01,  1.73it/s]
Traceback (most recent call last):
  File "train.py", line 544, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 354, in train
    results, maps, times = test.test(data_dict,
  File "/data/minhdq/yolov5/test.py", line 115, in test
    loss += compute_loss([x.float() for x in train_out], targets)[1][:3]  # box, obj, cls
  File "/data/minhdq/yolov5/utils/loss.py", line 141, in __call__
    t[range(n), tcls[i]] = self.cp
RuntimeError: CUDA error: device-side assert triggered

## Environment
YOLOv5 🚀 v5.0-20-gd48a34d torch 1.8.1+cu111 CUDA:0 (GeForce RTX 3090, 24265.8125MB)

**Comment by glenn-jocher** [comment]
@DINHQUANGMINH198 thanks for the bug report. In order to work on this we require a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. Thank you!
