### ISSUE TITLE
check_imshow condition error

### ISSUE THREAD

**Issue by hhxdestiny** [ultralytics/yolov5#2958]
general.py line 141.

```
assert not isdocker(), 'cv2.imshow() is disabled in Docker environments'
```
change it:
```
assert isdocker(), 'cv2.imshow() is disabled in Docker environments'
```

**Comment by glenn-jocher** [comment]
@hhxdestiny cv2 imshow operations are disabled in Docker images to prevent errors on unsupported frontends.

**Comment by hhxdestiny** [comment]
> @hhxdestiny cv2 imshow operations are disabled in Docker images to prevent errors on unsupported frontends.

But my env is not docker,  it still prompts ‘cv2.imshow() is disabled in Docker environments’

**Comment by hhxdestiny** [comment]
> @hhxdestiny cv2 imshow operations are disabled in Docker images to prevent errors on unsupported frontends.
my project path is 'F:\Workspace\Test\yolov5'...
`def isdocker():
    # Is environment a Docker container
    return Path('/workspace').exists()  # or Path('/.dockerenv').exists()`

**Comment by glenn-jocher** [comment]
@hhxdestiny you may be in a docker container without realizing it.
