### ISSUE TITLE
Inferencing with multiple processes in parallel on the CPU

### ISSUE THREAD

**Issue by haimat** [ultralytics/yolov5#2960]
I want to run YOLO inference on a large list of images, so I would like to process them in parallel. On that machine I don't have a GPU, so I want to run multple processes on the CPU. I am doing so via a normal Python `multiprocessing.Pool`. Nothing fancy here, the processing function for the process pool is quite simple:

```python
def pool_proc(frame_num):
    img = Image.open(os.path.join(frames_folder, f"frame-{frame_num:05d}.jpg"))
    results = model(img, size=img_size, augment=True)
    preds = results.pandas().xyxy[0]
    return (frame_num, preds)
```

The logic works, however, running with multiple processes is quite slow. In fact it is even a bit slower than running only one single (i.e. the main) process on the CPU. So it seems even when running with multiple processes they are still not inferencing in parallel but it's as if they are waiting for each other. I am pretty sure though the pool logic works, because when I comment out the call to `model()` and replace it with a `time.sleep(1.0)` then the whole programm is running super fast and in parallel.

Any ideas what I might be missing here?

**Comment by glenn-jocher** [comment]
@haimat I think often times there is a naive assumption that a parallel loop will increase speeds, when in reality often times lower level toolboxes (PIL, OpenCV, Numpy) are already multithreading their own functions.

**Comment by haimat** [comment]
@glenn-jocher That is an interesting point, thanks for your input. So do you think that my parallel approch in the context of YOLOv5 inferencing is only helpful with multiple GPUs, but not on a single CPU?

**Comment by glenn-jocher** [comment]
@haimat I'm not really sure. This is one of those areas where you simply need to implement an experiment and proceed based on the results. In some situations multithreading helps a lot, i.e. we use it when caching images with the --cache argument, and the torch dataloader uses multiple workers etc. The main issue arises when a function within your loop is already multithreading, in which case any additional gains may be minimal or negative.

**Comment by haimat** [comment]
@glenn-jocher Ok, thanks for your input.

**Comment by haimat** [comment]
Just for the records, after some more experimenting I did find a solution to this issue. So in case anyone else stumbles accross this, what helped in my case was to limit the number of threads PyTorch uses per process to 1 via `torch.set_num_threads(1)`. So in my case this approach reduced inference time for 65 images from 263 sec. with one process down to 140 sec. with 8 parallel processes.

**Comment by glenn-jocher** [comment]
@haimat ah interesting, thanks for the update! Not a great speedup but better than nothing.

**Comment by haimat** [comment]
@glenn-jocher Well, not as much as I was hoping for, but at least reduced processing time to 50%, which is not too bad I guess.

**Comment by devendraswamy** [comment]
> torch.set_num_threads

Super effort , I am also had a list of images and I tried multiprocessing for inference but no use in my case , could you please help me to where I can change torch.set_num_threads(1), if possible please help me to use the torch.set_num_threads(1).

Thank you
