### ISSUE TITLE
What do rect and img_weight do?

### ISSUE THREAD

**Issue by xinxin342** [ultralytics/yolov5#2962]
## ❔Question
There is the following lines of code in train.py, and there are not in test.py or detect.py.How do they work？
parser.add_argument('--rect', action='store_true', help='rectangular training')
parser.add_argument('--image-weights', action='store_true', help='use weighted image selection for training')

**Comment by glenn-jocher** [comment]
@xinxin342 --rect applies rectangular image sizes when training, --img-weights applies a weighting vector to the dataloader to attempt to load images more frequently that contain more classes with worse metrics from the previous epoch.

**Comment by xinxin342** [comment]
@glenn-jocher What are the benefits of RECT? train faster？ or improve the mAP? or improve the speed of detection?

**Comment by glenn-jocher** [comment]
@xinxin342 rectangular inference reduces FLOPS and improves speed.

**Comment by xinxin342** [comment]
@glenn-jocher  improves the speed of train？

**Comment by wudashuo** [comment]
Use `--rect` if your images are all same aspect ratio. Assume your dataset images are all 1920 * 1080,  images will be resized to 640 * 360, then padded to 640 * 640, if you use `--img 640 --rect`, images won't be padded. 640 * 640 = 409600, 640 * 360 = 230400,  so the speed will be improved.
That's my opinion, am I right?

**Comment by xinxin342** [comment]
@wudashuo What are the benefits of --rect(= true)? The speed of train will be faster？ or improve the mAP of test? or improve the speed of detection?
