### ISSUE TITLE
Confusion matrix weird results

### ISSUE THREAD

**Issue by constantinfite** [ultralytics/yolov5#2964]
## ❔Question
Hi, I remove the line `array = self.matrix / (self.matrix.sum(0).reshape(1, self.nc + 1) + 1E-6)  # normalize`  at the line 164 in the file metrics.py to obtain the real number of true positive, true negative ...

When I don't set the confidence score threshold it gives me this confusion matrix

![confusion_matrix](https://user-images.githubusercontent.com/57963890/116414942-39210680-a839-11eb-9736-aa9c0fb48690.png)

These results match with my data I have 613 objects (sharks) to detect ( 551 are detected (TP) and 62 are not detected (FN))

Now when I set the confidence score threshold at 0.7 `--conf 0.7` it gives me this matrix
![confusion_matrix](https://user-images.githubusercontent.com/57963890/116415027-505ff400-a839-11eb-8391-54491e00e7be.png)

What I don't understand is that when I sum the TP and the TN for the class shark this time it gives me 448+39 = 487 and not 613.

Do you have any idea why it returns this result ? 
Thanks!

**Comment by xinxin342** [comment]
@constantinfite That's interesting, but it doesn't make much sense.
Did you check it again?

**Comment by constantinfite** [comment]
@xinxin342 yes I checked again and got the same result ...

**Comment by zxcamazing** [comment]
I have the same confusion. What a confusion matrix!

**Comment by glenn-jocher** [comment]
@zxcamazing i understand the confusion here. It seems like you're experiencing unexpected results with the generated confusion matrix. The change you made to the `metrics.py` file may have altered the calculation behavior and led to the discrepancy in the results you're observing.

When considering a confidence score threshold, it's important to note that this would impact the number of true positives, false positives, etc., as detections below the set threshold would not be accounted for.

To fully understand the issue and provide the best guidance, I'd recommend taking a step back and reconsidering the modifications made to the `metrics.py` file. Double-checking the implementation might reveal why the results differ when a confidence score threshold is set.

In case you need further assistance, our comprehensive documentation at https://docs.ultralytics.com/yolov5/ can be helpful for reference.

Let me know how it goes!
