### ISSUE TITLE
Second-stage classifier

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#2969]
## ❔Question

Could you tell me the Second-stage classifier?

![image](https://user-images.githubusercontent.com/59388989/116497527-2ca0ba80-a8da-11eb-8717-9b30215178c0.png)

**Comment by alicera** [comment]
Second-stage classifier?

**Comment by glenn-jocher** [comment]
@alicera a second stage classifier can be used to verify YOLOv5 detections for reduced FPs. 

You can see YOLOv5 with a second stage classifier in TowerScout:
https://groups.ischool.berkeley.edu/TowerScout/index.html

**Comment by glenn-jocher** [comment]
<img width="1144" alt="Screenshot 2021-06-05 at 11 07 45" src="https://user-images.githubusercontent.com/26833433/120886451-48d8fb00-c5ee-11eb-9672-f59b95af981f.png">
