### ISSUE TITLE
torchscript implementation for inference module

### ISSUE THREAD

**Issue by sudapure** [ultralytics/yolov5#297]
## 🚀 Feature
As infering with python has always some toll in latency, but i guess implementing inferencing module in c++ torchscipt will be useful for deploying in production environment as well as it would be computationally less expensive than the python implementation.

**Comment by NanoCode012** [comment]
I am not sure if this is what you want, but there is script to export model to torchscript.
https://github.com/ultralytics/yolov5/blob/5e2429e6188254ad69401b172be3772efb9698e1/models/export.py#L31-L39

**Comment by yasenh** [comment]
Hi @sudapure, you can take a look at my repo: https://github.com/yasenh/libtorch-yolov5
And I saw there is another implementation: https://github.com/zherlock030/YOLOv5_Torchscript
