### ISSUE TITLE
Pycoral.adapters.detect.get_objects (yolov5s-int8_edgetpu.tflite) Issue: list index out of range

### ISSUE THREAD

**Issue by Laomeifu** [ultralytics/yolov5#2970]
Hello,
First, I want to say thank you for your great work.
I've been using your tf.py to convert yolov5s-int8 file and with edgetpu_compile to yolov5s-int8_edgetpu.tflite. There was no error from these two steps.

However, I have my own code based on pycoral (on RPI4): pycoral.adapters.detect.get_objects (not detect.py from yolov5) to detect with model but it has error of "count" which out of range. But my code was doing all good with mobilenetv2-coco_edgetpu.tflite

To be more specific, error shows:
count = int(common.output_tensor(interpreter,3)[0])
retrun interpreter.tensor(interpreter.get_output_details()[i]['index'])()
indexError: list index out of range

I found out that output details were different. mobilenetv2 shows 'shape': array([1, 10, 4]); yolov5s shows 'shape': array([1, 3, 6400, 85])

I'm guessing this is why I have "out of range" error? I was trying to understand your tf.py but really have no idea where should I edit. 

Please help or give me any advice. Thank you all!

**Comment by glenn-jocher** [comment]
If you believe you have a reproducible issue, we suggest you close this issue and raise a new one using the 🐛 **Bug Report template**, providing screenshots and a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. Thank you!
