### ISSUE TITLE
reproduce the yolov5x in COCO2017 used 16GB V100*8

### ISSUE THREAD

**Issue by learner321** [ultralytics/yolov5#2971]
## ❔Question
Hi，could you please share the training parameters of yolov5x by V100(16GB)*8?  50.1 AP is shown on the website `https://pytorch.org/hub/ultralytics_yolov5/`, but I just got 48.x AP after 300 epoch. 

## Additional context
Namespace(adam=False, artifact_alias='latest', batch_size=16, bbox_interval=-1, bucket='', cache_images=False, cfg='models/yolov5x.yaml', data='data/coco.yaml', device='', dist_backend='nccl', dist_url='tcp://localhost:12345', distributed=True, entity=None, epochs=300, evolve=False, exist_ok=False, global_rank=0, hyp='data/hyp.scratch.yaml', image_weights=False, img_size=[640, 640], label_smoothing=0.0, linear_lr=False, local_rank=-1, multi_scale=False, name='exp', noautoanchor=False, nosave=False, notest=False, project='runs/train', quad=False, rank=0, rect=False, resume=False, save_dir='runs/train/exp69', save_period=-1, single_cls=False, sync_bn=False, total_batch_size=128, upload_dataset=False, weights='', workers=6, world_size=8)

**Comment by glenn-jocher** [comment]
@learner321 official models were all trained on single-GPU, I can't speak for results on multi-GPU. Also larger models benefit more from higher scale jitter, so for 5l, 5x models I would recommend training at hyperparameter scale: 0.75-0.95
