### ISSUE TITLE
How to organize dataset for test.py to provide scores

### ISSUE THREAD

**Issue by RobbyJS** [ultralytics/yolov5#2972]
Hi,
I am trying to train yolov5 on a dataset of my own. I train yolov5 for a few epochs, and while training I obtain scores that make sense. I leave here the results from the last epoch:
 
> Epoch   gpu_mem       box       obj       cls     total    labels  img_size
>        4/4     7.38G   0.06714   0.03434   0.01587    0.1173        25       320
>                Class      Images      Labels           P           R      mAP@.5
>                  all        1987       19604       0.478       0.108      0.0608      0.0246
> 5 epochs completed in 0.137 hours.
> 
> Optimizer stripped from runs/train/exp4/weights/last.pt, 94.3MB
> Images sizes do not match. This will causes images to be display incorrectly in the UI.

However, when I launch test.py to obtain detailed scores, the scores provided are 1 or almost 1, for all classes. The dataset is organized with the required images and labels folders, split into training val and test. For the test dataset the labels in the labels folder contain the ground truth. I do not have the predicted labels, unless yolo has produced them. The test and the val datasets contain exactly the same images and labels. 

Here is my folder structure:

> ../chips
> └── 320
>     ├── full_px_box
>     │   ├── test
>     │   ├── train
>     │   └── val
>     ├── images
>     │   ├── test
>     │   ├── train
>     │   └── val
>     └── labels
>         ├── test
>         ├── train
>         └── val

Here is my call to test:
`!python test.py --data xView_test.yaml --task test --batch-size 16 --weights ../drive/MyDrive/yolov5/xView/runs/train/exp4/weights/last.pt --verbose --device 0 --save-txt --save-hybrid --save-conf --img-size 320 --iou 0.5`

And here are the first lines of the output:

> Namespace(augment=False, batch_size=16, conf_thres=0.001, data='./data/xView_test.yaml', device='0', exist_ok=False, img_size=320, iou_thres=0.5, name='exp', project='runs/test', save_conf=True, save_hybrid=True, save_json=False, save_txt=True, single_cls=False, task='test', verbose=True, weights=['../drive/MyDrive/yolov5/xView/runs/train/exp4/weights/last.pt'])
> YOLOv5 🚀 v4.0-182-g5825ff7 torch 1.8.1+cu101 CUDA:0 (Tesla T4, 15109.75MB)
> 
> Fusing layers... 
> Model Summary: 392 layers, 46918281 parameters, 0 gradients, 115.1 GFLOPS
> test: Scanning '../xView/chips/320/labels/test' images and labels... 1987 found, 0 missing, 935 empty, 0 corrupted: 100% 1987/1987 [00:00<00:00, 2184.60it/s]
> test: New cache created: ../xView/chips/320/labels/test.cache
>                Class      Images      Labels           P           R      mAP@.5  mAP@.5:.95: 100% 125/125 [01:17<00:00,  1.62it/s]
>                  all        1987       19604           1       0.996       0.992       0.992
>  Fixed-wing Aircraft        1987           1           1           1       0.995       0.995
>       Small Aircraft        1987          14           1           1       0.995       0.995
> ...

Similar results are obtained for the rest of classes. Predictions are too good to be true, and they are quite different to those provided during training. 

**Thus the question(s):**
So what am I doing wrong? Should I use different images for validation and testing? I did it this way just as a quick test. Or the problem is because I provide ground truth labels inside labels folder, and instead I should provide the predictions there? Where do the ground truth labels go then? Or the problem is on my call to the test function?

Many thanks in advance

**Comment by kepler62f** [comment]
@RobbyJS I organized the "test" dataset the same way as you and faced the same issue. When I removed the flag "save-hybrid" I then got more sane values for P, R and the 2 mAPs. Not sure why.

**Comment by glenn-jocher** [comment]
@RobbyJS @kepler62f `--save-hybrid` with concatenate labels onto predictions before the NMS pass. It is intended to produce hybrid labels, not to produce an accurate mAP.

**Comment by xinxin342** [comment]
What does' hybrid labels' mean?
What does it do?

**Comment by glenn-jocher** [comment]
@xinxin342 `--save-hybrid` will concatenate labels onto predictions before the NMS pass.
