### ISSUE TITLE
While training on my own dataset, how do I make yolo write its cache at a desired location and not within the dataset's directory?  

### ISSUE THREAD

**Issue by Ashishk67** [ultralytics/yolov5#2976]
## ❔Question
I'm trying to train it on a fast server where the dataset is located and I can only write within my own directory.

**Comment by glenn-jocher** [comment]
@Ashishk67 good news 😃! Your original issue may now been fixed ✅ in PR #2977.  To receive this update you can:
- `git pull` from within your `yolov5/` directory
- `git clone https://github.com/ultralytics/yolov5` again
- Force-reload PyTorch Hub: `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
