### ISSUE TITLE
pycoral image detect with yolov5s-int8_edgetpu.tflite: index out of range

### ISSUE THREAD

**Issue by Laomeifu** [ultralytics/yolov5#2978]
## ❔Question
Hello,
I used tf.py from https://github.com/zldrobit/yolov5 to transform yolov5s to yolov5s-int8.tflite, and then used edgetpu_compiler to yolov5s-int8_edgetpu.tflite. It was verified successfully with detect.py from https://github.com/zldrobit/yolov5.
However, I'm trying to use https://github.com/google-coral/pycoral/blob/master/examples/detect_image.py on raspberry pi 4 to load yolov5s-int8_edgetpu.tflite. It shows index out of range error, please see attached
![image](https://user-images.githubusercontent.com/75478522/116628178-66d28200-a903-11eb-8b2c-2761a746d6c3.png)

Can anyone help? Thanks!

**Comment by dariogonle** [comment]
Could you resolve this issue? I'm facing the same problem.
