### ISSUE TITLE
detection and training problem？The object box is slightly to the left

### ISSUE THREAD

**Issue by yeyewen** [ultralytics/yolov5#298]
I am training my custom data with  2 class. I use darknet from AlexeyAB having map 78
but i use yolov5x just get map 45.and the detection boxes is slightly to the left

![image](https://user-images.githubusercontent.com/37136363/86512128-e4d41280-be31-11ea-8f58-cfed2b606d77.png)
![image](https://user-images.githubusercontent.com/37136363/86512132-e998c680-be31-11ea-9252-9b13036c90c9.png)
![image](https://user-images.githubusercontent.com/37136363/86512179-38466080-be32-11ea-9d96-34cf4fb866b2.png)

**Comment by yeyewen** [comment]
any one any ideas? The training label are right.What may cause this?

**Comment by NanoCode012** [comment]
Can you check the file `train_batch0.jpg` ? Were the boxes correct?

**Comment by glenn-jocher** [comment]
@yeyewen you need to look at your labels jpgs. See this section of the custom training tutorial:
https://docs.ultralytics.com/yolov5/tutorials/train_custom_data#6-visualize

Also, you need to train fully to 300 epochs and then if you still have issues **upload your results.png file**.

**Comment by yeyewen** [comment]
Thanks everyone！I find my bug here. I accidently changed 
![image](https://user-images.githubusercontent.com/37136363/86699754-140d9e00-c043-11ea-856a-2533ab7b621e.png)

to
![image](https://user-images.githubusercontent.com/37136363/86700107-68b11900-c043-11ea-9ef2-051203ad1c5c.png)
This changes caused  my problem!
 changing back solved my problem!

**Comment by glenn-jocher** [comment]
@yeyewen oh! Yes, make sure you always use something like PyCharm with integrated version control to easily and quickly understand changes you've made compared to the git pull you have.
