### ISSUE TITLE
hello, anyone has try to add dcn to backbone, and run successful?

### ISSUE THREAD

**Issue by Bobo-y** [ultralytics/yolov5#2981]
## ❔Question
hello, anyone has try to add dcn to backbone, and run successful?

## Additional context

I want add DeformConv2d in backbone, I use two implementation:
1. torchvision.ops.deform_conv
2. https://github.com/jinfagang/DCNv2_latest

but they have same error when train forward.

![image](https://user-images.githubusercontent.com/9928596/116668202-acf51780-a9cf-11eb-83c0-17692b705180.png)

And i debug, print weights. 

weights of DeformConv2d
![image](https://user-images.githubusercontent.com/9928596/116668701-43293d80-a9d0-11eb-97c8-83342fb38799.png)

weights of norml conv2d
![image](https://user-images.githubusercontent.com/9928596/116668715-48868800-a9d0-11eb-978a-742349249fcc.png)

I think this is caused by the mixed precision training of apex, and the DCN support for this is not very good. I train resnet with dcn for DBNet or Centertrack, There was no problem. 

Anyone can help?

**Comment by glenn-jocher** [comment]
@yl305237731 apex is not used in master, we use torch.cuda.amp. You can remove the mixed precision training here:
https://github.com/ultralytics/yolov5/blob/955eea8b96397b1f1f7666c4ee42d1c6411d0755/train.py#L301-L309

**Comment by Bobo-y** [comment]
@glenn-jocher you are so nice, when I close amp, the dcn is work now, Thanks again

**Comment by ruofei7** [comment]
Hello, how did you add dcn to the backone of yolov5? Could you please share the modified code? thank you very much!

**Comment by Bobo-y** [comment]
@ruofei7 i replace backbone by resnet with dcn, replace conv2 by dcn in Bottleneck. if you want to add dcn in original yolov5, may be you can do something in Bottleneck, here is my yolov5 repo [flexible-yolov5](https://github.com/yl305237731/flexible-yolov5) , may be it's can help you.

**Comment by developer0hye** [comment]
@ruofei7 @yl305237731 

Refer to [Simple-PyTorch-Deformable-Convolution-v2](https://github.com/developer0hye/Simple-PyTorch-Deformable-Convolution-v2) to use DCN in your model.

**Comment by yustaub** [comment]
hello, sir. You said replace conv2 by dcn in Bottleneck, there are two conv in bottleneck, you replace both or just replace the last one conv? Very appreciate for your reply!! @yl305237731

**Comment by Bobo-y** [comment]
@yustaub i use dcn with resnet as backbone, not csp

**Comment by yustaub** [comment]
Sorry for my late reply. I got it, I try to repalce conv by dcn in bottleneck in csp, I will test if it works. @yl305237731
