### ISSUE TITLE
reduce CPU memory usage while --cache-images on

### ISSUE THREAD

**Issue by PresageBoat** [ultralytics/yolov5#2984]
## 🚀 Feature

The image opened by opencv imread will be expanded in the memory, which will take up a lot of memory space, which is not conducive to loading all the training images into the memory.
If we load the image  into the memory in binary format, and  use opencv imdecode to decode it while using it. which can greatly reduce the memory usage. In the coco128 file test, the memory usage can be reduced to 6.5 times the original
## Motivation
1.reduce cpu memory usage while  --cache-images on
2.On the windows platform, there is a problem with pytorch1.81 multi-threaded data reading, and the reading thread needs to be set to 0

## Pitch

use opencv imencode and imdecode to  get better memory usage

**Comment by glenn-jocher** [comment]
@edificewang this sounds really interesting! I'm not familiar with cv2 encode and decode, but yes caching uses up significant memory. If it were possible to accomplish a similar speedup with less RAM usage that would be ideal. Could you please submit a PR with your proposal so we could understand and analyze it there? Thank you!

**Comment by PresageBoat** [comment]
@glenn-jocher Thank you very much for your approval, I will submit a pull request later.

**Comment by glenn-jocher** [comment]
@edificewang great! Also try to profile the modifications for both speed (ms to access a new 640 image during training) and RAM usage. If we could compare the 3 options that would be great:

- load from hard drive (default)
- `--cache` into RAM (current)
- `--cache` into RAM (proposed)

**Comment by PresageBoat** [comment]
@glenn-jocher 
I run test on coco128 ; set --cache-images on
--cache into RAM(current): 113.7MB
--cache int RAM(proposed):17.9MB
113.7/17.9 = 6.35
[https://github.com/ultralytics/yolov5/pull/2987](url)

**Comment by glenn-jocher** [comment]
@edificewang thanks for the RAM numbers! I'll try to profile the 3 test cases on coco128 also. Test command is:
```
python train.py --epochs 3
```
I'll compare the load_image() line in the mosaic4 function here, which loads up 128 * 3 images per epoch on L683:
https://github.com/ultralytics/yolov5/blob/d08575ee5e5259b65e1f39ac6880cd33804c4d1a/utils/datasets.py#L674-L684

**Comment by glenn-jocher** [comment]
@edificewang I was able to profile all 3 types, I uploaded my full result including screenshots to https://github.com/ultralytics/yolov5/pull/2987, please take a look there.

&nbsp; |time (ms) per image   |RAM 
---        |---          |--- 
master      |4.638             |-
master --cache         |0.005 |0.1GB
proposed --cache         |3.482  |0.0GB
