### ISSUE TITLE
small medium large coco map logging for wandb

### ISSUE THREAD

**Issue by fcakyon** [ultralytics/yolov5#2989]
Currently, after each epoch validation scores for 0.5:0.95 and 0.5 mAP are logged into wandb but small medium large 0.5:0.95 mAP scores are not logged. It is crucial for some problems to be able to compare small and large object detection performances. 

What updates are needed for adding such support?

**Comment by glenn-jocher** [comment]
@fcakyon we only compute AP per class currently, and don't have any automatic capability to segregate. In the past users have requested segregation by image, this would be segregation by instance size.

pycocotools runs this type of analysis, but it is far too slow to use during training, perhaps about 100x slower than the YOLOv5 mAP code.
