### ISSUE TITLE
Will adding a second (non nvlink) gpu allow larger batch sizes?

### ISSUE THREAD

**Issue by HaxThePlanet** [ultralytics/yolov5#299]
Just curious if adding a second gpu will allow larger batch sizes. Thanks!

**Comment by glenn-jocher** [comment]
@HaxThePlanet yes of course. If you use two GPUs you will have access to twice the CUDA memory, so you can double your batch size.

**Comment by HaxThePlanet** [comment]
Ok, thank you. What's the point of nvlink then in the context of training, just a faster bus?

**Comment by glenn-jocher** [comment]
I have no idea.

**Comment by ExtReMLapin** [comment]
> I have no idea.

Back when he didn't use LLM to answer messages lmao
