### ISSUE TITLE
[Supervisely]  Custom Model Training on Supervisely

### ISSUE THREAD

**Issue by haynec** [ultralytics/yolov5#2992]
[Supervisely] 

The Bug:
I am trying to train from a custom model on Supervisely using the YoloV5 training app. I have my custom .pt model file in my team files and direct it to that location within the Train YoloV5 app, but the training errors out with it unable to find my custom model file
![Screenshot from 2021-04-30 08-35-44](https://user-images.githubusercontent.com/58046076/116718698-199bf200-a98f-11eb-83b1-27934fbf36bc.png)
.
![Screenshot from 2021-04-30 08-31-24](https://user-images.githubusercontent.com/58046076/116718410-c7f36780-a98e-11eb-9760-c3601c9c1f25.png)

I am running the latest docker image on my computer.

## To Reproduce (REQUIRED)
Use YoloV5 training app on Supervisely to train from a custom model. 

## Expected behavior
The model should start training and be able to locate the custom model files within the team files.

**Comment by glenn-jocher** [comment]
@haynec hi, thanks for the bug report! Sorry to hear you are having problems. @mkolomeychenko at Supervisely may be able to help you here. Max can you take a look at this?
