### ISSUE TITLE
When downloading pre-trained weights...

### ISSUE THREAD

**Issue by zjysteven** [ultralytics/yolov5#30]
Hi, thanks for this awesome implementation and pre-trained models!

This is just a minor issue and maybe it is I miss something, but I think the importing path of https://github.com/ultralytics/yolov5/blob/c14368d768749734e1a017ed8e750b33597e8746/weights/download_weights.sh#L4 should be something like `from utils.google_utils import *` since the `attempt_download` function is within `utils/google_utils.py`, right?

**Comment by glenn-jocher** [comment]
@zjysteven yes, you are correct! Thank you for the bug report. We will fix this.
