### ISSUE TITLE
Issue installing on aws lambda docker

### ISSUE THREAD

**Issue by matthewchung74** [ultralytics/yolov5#3000]
## ❔Question

I am trying to run yolov5 on an aws lambda docker container. I'm am using the line below to install the model on a docker container

```
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)
```

And also, to load the model.

I then upload the container to aws but then when trying to send requests to the lambda container, I am getting a permission error.

AWS runs the process using a user that only has permissions to write to `/tmp` so I'm pretty sure that line above is writing somewhere else. I stepped through the code, and don't see anything obvious. Do you have any suggestions or know of any place that does writes within torch.hub.load?

**Comment by glenn-jocher** [comment]
@matthewchung74 cache location is displayed by the same torch.hub.load() command you're asking about, so I don't quite understand your question, as all you need to do is observe and see where it places the cache to know it's location.

**Comment by matthewchung74** [comment]
Thanks @glenn-jocher .  You are right, my question was not well worded.  I've done some more exploring, and have played with putting the model in different places using
```
torch.hub.set_dir("./model")
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)
```

however, I am noticing when I do something like the above, the yolo5s.pt file is saving in the current executing directory and the ultralytics_yolov5_master folder is saved in the model directory. shouldn't it all go in the model directory?

I am still getting some odd permission errors and think it might be due to the model placement.

colab:
https://colab.research.google.com/drive/1QvodhfV59ekhysh2BZ1qG5my2sPnIike?usp=sharing

**Comment by glenn-jocher** [comment]
@matthewchung74 `torch.hub.set_dir()` allows you to define the caching directory. torch hub models are downloaded to current directory by default.

**Comment by matthewchung74** [comment]
got it.
