### ISSUE TITLE
TorchScript model does not detect on Android

### ISSUE THREAD

**Issue by ojsj18** [ultralytics/yolov5#3008]
## ❔Question
I did the conversion following the tutorial available (TorchScript model does not detect on android) that I used my own dataset

## Additional context
error that appears in debugging:
E/AndroidRuntime: FATAL EXCEPTION: Thread-6
    Process: org.pytorch.demo.objectdetection, PID: 4759
    java.lang.ArrayIndexOutOfBoundsException: length=252000; index=252029
        at org.pytorch.demo.objectdetection.PrePostProcessor.outputsToNMSPredictions(PrePostProcessor.java:122)
        at org.pytorch.demo.objectdetection.MainActivity.run(MainActivity.java:229)
        at java.lang.Thread.run(Thread.java:764)

**Comment by glenn-jocher** [comment]
@ojsj18 you should verify the export pipeline with a default model first to better isolate the source of your error.

**Comment by ojsj18** [comment]
With the standard model the export occurs normally, I believe it is a problem with the conversion since it appeared to me in the following warning:
./models/yolo.py:50: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if self.grid[i].shape[2:4] != x[i].shape[2:4]:
TorchScript export success, saved as ./runs/train/exp18/weights/best.torchscript.pt

**Comment by obaby** [comment]
have you soloved this problem? thanks

**Comment by MjiS** [comment]
You need to change only mOutputColumn value with you number of classes+5. I was changing mOutputRow = 25200 with value calculated by 25200*(num_of_class+5) which caused this issue.

// model output is of size 25200*(num_of_class+5)
private static int mOutputRow = 25200; // as decided by the YOLOv5 model for input image of size 640*640
private static int mOutputColumn = 52; // left, top, right, bottom, score and 80 class probability
private static float mThreshold = 0.50f; // score above which a detection is generated
//
