### ISSUE TITLE
The training seems to have ended normally, but can the wandb dashboard display crashed?

### ISSUE THREAD

**Issue by leeyunhome** [ultralytics/yolov5#3015]
## ❔Question

The training seems to have ended normally, but can the wandb dashboard display crashed?
Learning is completed normally, but it is expected that when the Internet is disconnected, it will appear as crashed.

**Comment by AyushExel** [comment]
@leeyunhome this is a known issue and will be fixed in a few days. But it should not interfere with your runs and they will work as they are supposed to.

**Comment by AyushExel** [comment]
@leeyunhome can you share the link of that run that ran fine but shows up as crashed? It'll be useful for debugging

**Comment by raubitsj** [comment]
@leeyunhome ,
This is not expected but it was an issue that we have seen recently.   We have just released a new version if the client library which should handle this better: wandb==0.10.29.   Please update to this version:
```
pip install --upgrade wandb
```

If you still have the wandb run directory around you can get all your data in the wandb UI updated by running:
```
wandb sync PATH_TO_RUN_DIRECTORY
```
