### ISSUE TITLE
why not train from scratch?

### ISSUE THREAD

**Issue by Fred199683** [ultralytics/yolov5#3021]
## ❔Question

thanks for ur repo. I've read ur suggestions about getting better results. You recommend to train from the pretrained model rather than random init.  I want to know why do u recommend this?
And if my dataset is a little different from COCO, so the pretrained model only share the backbone part(and the other part is randomly init), or share the whole part? if share the whole part, will there be an error that the parameters' dimension not matching?(because my datasets is different from coco).
Hope someone can help me !

**Comment by glenn-jocher** [comment]
@Fred199683 output reshaping is handled automatically in YOLOv5. You're free to configure your model however you like.
