### ISSUE TITLE
Inference not logged

### ISSUE THREAD

**Issue by PascalHbr** [ultralytics/yolov5#3024]
I am using wandb to log the training process. Unfortunately, by default no inference on images is plotted and I haven't figured out yet how to do it. The only images that are logged for me are the result graphs and `test_batch0_labels.jpg`. But these are just the labels and not really helpful. I would need the predictions on the images to be logged, can someone help me out here please?

Thanks! :)

**Comment by glenn-jocher** [comment]
@PascalHbr there's a great set of tutorials and a video here explaining how to get the most out of W&B logging with YOLOv5:
https://docs.wandb.ai/guides/integrations/yolov5

**Comment by PascalHbr** [comment]
Awesome indeed, thanks! :)
