### ISSUE TITLE
How to add counting lines and show the cumulative counting number of people crossing the line upwards and downwards separately?

### ISSUE THREAD

**Issue by NewToDS** [ultralytics/yolov5#3025]
Hi, I'm new to computer vision and currently self learning and working on a school project counting the net people in a room with a camera facing the door. Could anyone give me some advices on **how to add a counting line** and **show the result of the net counts (in_counts-out_counts) on the video plot with using Yolov5**? Much appreciated!

**Comment by glenn-jocher** [comment]
@NewToDS YOLO is a detector, not a tracker, so you would need to integrate tracking into your pipeline (ie kalman filter, KLT, deepsort) and then apply simple line crossing functions to each track.

**Comment by NewToDS** [comment]
> @NewToDS YOLO is a detector, not a tracker, so you would need to integrate tracking into your pipeline (ie kalman filter, KLT, deepsort) and then apply simple line crossing functions to each track.

Many thanks Glenn, really appreciate it!
