### ISSUE TITLE
Training does not work when using augmented validation

### ISSUE THREAD

**Issue by wq9** [ultralytics/yolov5#3026]
## 🐛 Bug
Training does not work when using augmented validation. Some models perform significantly better when testing with augment=True, so I want to use augment=True during training validation so that best.pt is optimal.

## To Reproduce (REQUIRED)

1. In train.py `test.test` function parameters (https://github.com/ultralytics/yolov5/blob/master/train.py#L356), add `augment=True,` and save the file.
2. Start training using `python train.py --batch-size 4 --data coco128.yaml --weights yolov5s.pt --single-cls`

Output:
```
Traceback (most recent call last):
  File "train.py", line 545, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 354, in train
    results, maps, times = test.test(data_dict,
  File "/home/ubuntu/yolov5/test.py", line 116, in test
    loss += compute_loss([x.float() for x in train_out], targets)[1][:3]  # box, obj, cls
TypeError: 'NoneType' object is not iterable

```

## Expected behavior
Normal training, with augmented validation.

## Environment
N/A

**Comment by glenn-jocher** [comment]
@wq9 training is not intended to work with augmented validation, so I'll remove the bug label.
