### ISSUE TITLE
How do I save results for the entire test folder to a single txt file?

### ISSUE THREAD

**Issue by Ashishk67** [ultralytics/yolov5#3028]
## ❔Question
I trained it on the training dataset and saved the weights.
I entered the path for the test dataset to a yaml file. I want to run the trained model on my test directory of 1000 images and save the results in the format ' image_id, class, cx, cy, w, h, conf ' to a single text file. Any suggestions on how to go about it?

**Comment by glenn-jocher** [comment]
@Ashishk67 you can customize any inference workflow you want using YOLOv5 PyTorch Hub models. See PyTorch Hub Tutorial to get started:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [ONNX and TorchScript Export](https://docs.ultralytics.com/yolov5/tutorials/model_export)
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by Ashishk67** [comment]
> @Ashishk67 you can customize any inference workflow you want using YOLOv5 PyTorch Hub models. See PyTorch Hub Tutorial to get started:
> 
> ## YOLOv5 Tutorials
> * [Train Custom Data](https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data)  🚀 RECOMMENDED
> * [Tips for Best Training Results](https://github.com/ultralytics/yolov5/wiki/Tips-for-Best-Training-Results)  ☘️ RECOMMENDED
> * [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)  🌟 NEW
> * [Supervisely Ecosystem](https://github.com/ultralytics/yolov5/issues/2518)  🌟 NEW
> * [Multi-GPU Training](https://github.com/ultralytics/yolov5/issues/475)
> * [PyTorch Hub](https://github.com/ultralytics/yolov5/issues/36)  ⭐ NEW
> * [ONNX and TorchScript Export](https://github.com/ultralytics/yolov5/issues/251)
> * [Test-Time Augmentation (TTA)](https://github.com/ultralytics/yolov5/issues/303)
> * [Model Ensembling](https://github.com/ultralytics/yolov5/issues/318)
> * [Model Pruning/Sparsity](https://github.com/ultralytics/yolov5/issues/304)
> * [Hyperparameter Evolution](https://github.com/ultralytics/yolov5/issues/607)
> * [Transfer Learning with Frozen Layers](https://github.com/ultralytics/yolov5/issues/1314)  ⭐ NEW
> * [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by Ashishk67** [comment]
Hi Glenn, thanks for responding. I went through the PyTorch hub tutorial you mentioned but the thing is I'm working on a server with no internet access. The model is trained and the weights for the dataset are already saved to 'best.pt'. Could you look at my original query and guide me a little? Thank you so much for your help.
