### ISSUE TITLE
DDP wandb utils not running check_file() on --data

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/yolov5#3031]
## 🐛 Bug

@AyushExel I found a bit of a bug today on starting a DDP training with `--data coco.yaml`. All our main python files (train, test, detect) are set up so that files passed to the argparser are searched locally inside the yolov5 repo using `file = check_file(file)`. This allows for more concise commands like --cfg yolov5s.yaml rather than --cfg models/yolov5s.yaml, but it looks like opt.data got passed to the wandb utils before it had a chance to pass through check_file() first. Should be an easy fix, I think I can do this tomorrow.

<img width="1214" alt="Screenshot 2021-05-05 at 01 46 55" src="https://user-images.githubusercontent.com/26833433/117083255-94c12780-ad44-11eb-85c2-48bef8943717.png">

## To Reproduce (REQUIRED)

Start DDP training with `--data coco.yaml`
```
 python -m torch.distributed.launch --nproc_per_node 2 --master_port 1 train.py --batch 64 --cfg yolov5x.yaml --weights '' --data coco.yaml
```

**Comment by AyushExel** [comment]
@glenn-jocher I'm trying to fix it now

**Comment by AyushExel** [comment]
#3035 should fix this
