### ISSUE TITLE
What does 'Images' and 'Targets' mean in the training output ? 

### ISSUE THREAD

**Issue by ShirleyHe2020** [ultralytics/yolov5#3032]
## ❔Question

when training finished ,  I got output as below, don't understand what's  Images and Targets. eg : Why all the values are 582 for all classes ? If targets means labeled samples? there are  more than 1k  samples in liewen class, why it shows only  128 in targets ? 

![image](https://user-images.githubusercontent.com/63453957/117092580-47b77280-ad91-11eb-8907-8d10a4c5f76c.png)

**Comment by glenn-jocher** [comment]
@ShirleyHe2020 your code is out of date. Targets has been renamed to labels for clarity.
