### ISSUE TITLE
GFLOPS in test.py

### ISSUE THREAD

**Issue by whuyyc** [ultralytics/yolov5#3034]
## ❔Question
What is the meanging of GFLOPS in result of test.py? Does it refer to floating point operations per second or floating point operations? And how about the the correlation between the GFLOPS value and the model performance?

**Comment by glenn-jocher** [comment]
@whuyyc 1 GFLOP is 1 billion operations. Correlations are available to see in README Table:
https://github.com/ultralytics/yolov5#pretrained-checkpoints

**Comment by whuyyc** [comment]
@glenn-jocher Thank you very much!
