### ISSUE TITLE
Eats 200gb of page file.

### ISSUE THREAD

**Issue by xrstokes** [ultralytics/yolov5#3038]
Before submitting a bug report, please be aware that your issue **must be reproducible** with all of the following, otherwise it is non-actionable, and we can not help you:
 - **Current repo**: run `git fetch && git status -uno` to check and `git pull` to update repo
 - **Common dataset**: coco.yaml or coco128.yaml
 - **Common environment**: Colab, Google Cloud, or Docker image. See https://github.com/ultralytics/yolov5#environments
 
If this is a custom dataset/training question you **must include** your `train*.jpg`, `test*.jpg` and `results.png` figures, or we can not help you. You can generate these with `utils.plot_results()`.

## 🐛 Bug
All i did was download the latest version, get my train data from Roboflow and run this command.
`python train.py --img 640 --batch 64 --epochs 10 --data ../data.yaml --cfg models/custom_yolov5xs.yaml --weights yolov5xs.pt --name xs-evolve --cache --evolve`

`
Traceback (most recent call last):
  File "train.py", line 613, in <module>
    hyp[k] = max(hyp[k], v[1])  # lower limit
KeyError: 'anchors'
`
So i comment out this line that i read somewhere to fix it.
`#'anchors': (2, 2.0, 10.0),  # anchors per output grid (0 to ignore)`

Then i run the command again and it works this time. But after 6 hours I've used 200GB of page file and i get this error.
`raceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\grant\anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\grant\anaconda3\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\grant\anaconda3\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\grant\anaconda3\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\grant\anaconda3\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\grant\anaconda3\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\grant\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "L:\Sticker_Data\v3i.yolov5pytorch\yolov5\train.py", line 12, in <module>
    import torch.distributed as dist
  File "C:\Users\grant\anaconda3\lib\site-packages\torch\__init__.py", line 123, in <module>
    raise err
OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "C:\Users\grant\anaconda3\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.
`

It seems to work fine in every other way. detect works fine also. Seems only to be when i use --evolve. I didn't notice a lot of usage with normal train. but is wasn't watching. 

## To Reproduce (REQUIRED)

See above ^

## Environment

 - OS: [Windows 10 - Anaconda]
 - GPU [p4000 quadro]

## Additional context
Thanks for all the great work.

**Comment by xrstokes** [comment]
I would like to add that if i try on google colab i don't get the error but i crashes. I apologize if i'm using it wrong but i've been banging my head against the wall tryin to get to the bottom of it.

**Comment by glenn-jocher** [comment]
@xrstokes thanks for the bug report! Yes there is a memory leak that affects evolution in some environments, I'm not sure of the source. You can avoid the issue by setting generations=1 and evolving in a bash `while` loop instead:
```bash
while true; do python train.py ... --evolve; done
```

**Comment by xrstokes** [comment]
Sorry to bother you again. but how will i know which is the best outcome? if i loop 300 times. will hyp_evolved.yaml be the latest one or the best one? or do i sort them by performance in wandb?

**Comment by xrstokes** [comment]
I've got around it i think by running it in a container "sudo docker pull ultralytics/yolov5:latest"
But in the container i can only run a batch of 8 instead of 32 or i get the following...........wait no. It just froze. never mind. so it would appear to be in the container also. The error i get going for a bigger batch is 
"RuntimeError: cuda runtime error (2) : out of memory at ../aten/src/THC/THCCachingHostAllocator.cpp:278"


Just FYI, I'm not nagging. just trying to give you lots of info.

**Comment by glenn-jocher** [comment]
@xrstokes hyp_evolved.yaml will always display the best mutation. evolve.txt will display all generations sorted by fitness. If evolution is interrupted it will restart automatically where it left off when you restart it.
