### ISSUE TITLE
Multiple attributes with same bounding box possible?

### ISSUE THREAD

**Issue by vii33** [ultralytics/yolov5#3041]
## Situation 

Hey, I have a fruit dataset which I annotated as follows:
- One Bounding Box per Object
- Each Object gets an attribute, like color, shape.
_(This process was the most convenient approach with CVAT since the attributes can be added after the bounding box drawing very quickly)_

For YoloV5 training I tried to use one class per attribute with the **same** bounding box coordinates e.g
```
0 0.5 0.5 0.23 0.10
2 0.5 0.5 0.23 0.10
```
```
1 0.6 0.4 0.55 0.10
3 0.6 0.4 0.55 0.10
```
with `0: yellow, 1: green, 2: apple, 3: banana`

This approach doesn't get me good training results also precision and recall jump like crazy. (I'm assuming the different classes "overwrite" each other in training)

## ❔Question
So I was wondering: Is it possible to train Yolo with this bounding box attribute approach?

## Additional context

Of course, I can multiply all the attributes with each other to create a "flat list" like `0: yellow-apple, 1: red-apple, 2: yellow-banana, 3: green-banana`. But this increases class size exponentially when introducing more attributes.

Thank you for any hints.

**Comment by glenn-jocher** [comment]
@vii33 YOLO can learn any type of input-output relationship, so you're free to redefine labels to include additional dimensions such as color, rotation, etc. of each object, though these changes must also be applied to the loss function and metrics etc.

Alternatively you can split your classes into finer definitions without making any changes to the code as in your last example.

**Comment by vii33** [comment]
Hi Glenn, thanks for the quick reply. I don't get your answer completly (sorry). -> Can YoloV5 learn a "multi-label classification", in pointing two times to the same bounding box but with different classes or do they annihilate themselves in training?

**Comment by glenn-jocher** [comment]
@vii33 YOLO will learn any labels you provide. Multi-label classification is enabled by default.

There are no conflicts.

**Comment by AdamChrist** [comment]
@vii33 Hello, I have similar ideas to you, I also tried, but found that the confidence is only half of the normal.
![image](https://user-images.githubusercontent.com/12388267/132619454-8e077f08-0de5-4a9a-ac78-761d6ec9d8ef.png)
Do you have any good solutions?
