### ISSUE TITLE
Question about calculating mAP at test time

### ISSUE THREAD

**Issue by huuquan1994** [ultralytics/yolov5#3042]
## ❔Question
Thank you for your work, I really enjoyed running the codes.

I was trying to understand the way we calculate mAP by reading the [test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)
At line [197](https://github.com/ultralytics/yolov5/blob/master/test.py#L197), as I understood, the IoU values (`ious`) wasn't sorted before the further process (lines [199-211](https://github.com/ultralytics/yolov5/blob/master/test.py#L199-L211)).
Therefore, I think it doesn't guarantee that we find the best IoU (or a detected box) for a ground-truth box.
For example, a detected box is considered correct if the IoU with a ground-truth box is >= 0.5. However, there are possibilities that we detected multiple boxes with different IoU values. In this case, I think we should assign the box with the highest IoU as the correctly detected box.

Will the code affect the result of calculating mAP?

## Additional context
The comments in lines [191-192](https://github.com/ultralytics/yolov5/blob/master/test.py#L191-L192) (`# prediction indices`, `# target indices`) should be swapped, shouldn't they?

**Comment by glenn-jocher** [comment]
@huuquan1994 yes you're right, the comments should be swapped! Can you send a quick PR for this bug you spotted? Thanks!

The predictions are sorted by confidence here:
https://github.com/ultralytics/yolov5/blob/b18ca31ff5412d30ee56eb9c4adbe731f9d2148e/utils/metrics.py#L32-L33

**Comment by huuquan1994** [comment]
> @huuquan1994 yes you're right, the comments should be swapped! Can you send a quick PR for this bug you spotted? Thanks!
> 
> The predictions are sorted by confidence here:
> https://github.com/ultralytics/yolov5/blob/b18ca31ff5412d30ee56eb9c4adbe731f9d2148e/utils/metrics.py#L32-L33

Thanks, @glenn-jocher for your comments fix.

For my first question, I understood that the predictions are sorted by confidence at the `ap_per_class` function.
But before that, at [test.py](https://github.com/ultralytics/yolov5/blob/master/test.py#L194-L208), it was quite hard to understand the process.

Supposed that I have 1 test image with 1 class and **6** ground-truth bounding boxes.

I tried to print out the prediction results (after NMS).
The code on [test.py](https://github.com/ultralytics/yolov5/blob/master/test.py#L194-L208) will be modified like below:

```python
# Search for detections
if pi.shape[0]:
    # Prediction to target ious
    ious, i = box_iou(predn[pi, :4], tbox[ti]).max(1)  # best ious, indices

    # Append detections
    detected_set = set()
    # Print out all IoU values that > 0.5 (iouv[0])
    print(ious[ious > iouv[0]])
    # Print out all (targeted) IoU indices that > 0.5 (iouv[0])
    print(ti[i[ious > iouv[0]]])
    
    for j in (ious > iouv[0]).nonzero(as_tuple=False):
        d = ti[i[j]]  # detected target
        if d.item() not in detected_set:
            detected_set.add(d.item())
            detected.append(d)
            correct[pi[j]] = ious[j] > iouv  # iou_thres is 1xn
            if len(detected) == nl:  # all targets already located in image
                break
    # Print detected for further mAP calculation
    print(detected)
```

My outputs are:
```
# IoU values that > 0.5 (iouv[0])
[0.91536, 0.72824, 0.84568, 0.64040, 0.75937, 0.55075, 0.57479, 0.51508, 0.87954, 0.51129, 0.59774, 0.67086, 0.72601, 0.53363, 0.60063]

# (targeted) IoU indices that > 0.5 (iouv[0])
[3, 2, 0, 5, 1, 4, 2, 3, 4, 0, 1, 3, 5, 1, 2]

# Detected for further mAP calculation
[3, 2, 0, 5, 1, 4]
```

The corresponding IoU values of the detected targets are [0.91536, 0.72824, 0.84568, 0.64040, 0.75937, 0.55075] (which were the first elements in the list (if correctly located))

But if we consider the best IoU values for the detected boxes ([3, 2, 0, 5, 1, 4]), shouldn't they be [0.91536, 0.72824, 0.84568, **0.72601**, 0.75937, **0.87954**]?

**Comment by glenn-jocher** [comment]
@huuquan1994 there's no IoU sorting, the sorting is by prediction confidence.

**Comment by huuquan1994** [comment]
@glenn-jocher thanks for your reply!

I wonder if this affects the result of the `ap_per_class` function since if we use better IoU values (as mentioned above), the True Positive array (`correct` (https://github.com/ultralytics/yolov5/blob/master/test.py#L178)) will have more `True` values, and the mAP will be improved (I'm sorry if my understanding is incorrect).

Anyway, I just want to understand YOLOv5 better and if there's no IoU sorting, your code is perfect 😊

**Comment by glenn-jocher** [comment]
@huuquan1994 I'm not sure I understand your question correctly. Can you submit a PR with your proposed changes so that we can see and evaluate the changes against the baseline code? Thanks!

**Comment by huuquan1994** [comment]
@glenn-jocher sure, I'll do it soon!
