### ISSUE TITLE
Remove Detect() layer in newer versions

### ISSUE THREAD

**Issue by BernardinD** [ultralytics/yolov5#3045]
**Issue:** It seems the ability to remove the Detect() layer while exporting has been dropped in the newer versions of the graph. How is it achieved now?

**Goal:** I want to remove Detect() layer while exporting to ONNX.

**Comment by BernardinD** [comment]
**Update:** I see that that the functionality was taken out recently in <https://github.com/ultralytics/yolov5/commit/b292837> and was able to manually get back the ability to remove Detect() from the ONNX graph. But are there plans for it to be returned soon?

**Comment by glenn-jocher** [comment]
@BernardinD you can replace Detect() layer with a simple nn.Identity() module if you'd like before export here:
https://github.com/ultralytics/yolov5/blob/3ef3a95cfa536f3977676b6ed18f7bebf391fa2c/models/export.py#L53-L67
