### ISSUE TITLE
fp16 or fp32?

### ISSUE THREAD

**Issue by cowarder** [ultralytics/yolov5#305]
As described in README.md, the default param "half=False", which means we use fp 32. But the default trained model precision is fp16.

**Comment by glenn-jocher** [comment]
@cowarder June 19, 2020: FP16 as new default for smaller checkpoints and faster inference d4c6674.

All model saving, testing with test.py and inference with detect.py occurs in FP16 on single GPU when cuda is available now, or FP32 on CPU, where FP16 is not supported.
