### ISSUE TITLE
[ONNXRuntimeError] on using onnx exported model with --inplace argument

### ISSUE THREAD

**Issue by Mak-24** [ultralytics/yolov5#3050]
I tried exporting my custom trained model to onnx with the --inplace argument so that I also have the detect layer in the export but when I tried to use the model I get ONNX runtime error. This is not just on my model I tried doing the same on the yolov5s.pt weights. This error also comes when using --simplify param along with --inplace 

The export works without the --inplace param but The exported model doesn't have the same output as the pytorch model. I want to run this on Node so if anyone has any suggestions as to how I can get the same results without using --inplace param please let me know.

To recreate the above mentioned:
```
%cd /content/yolov5
%ls
!pip3 install onnx
!export PYTHONPATH="$PWD" && python models/export.py --weights yolov5s.pt --inplace --simplify
```

Output:
```
YOLOv5 🚀 v5.0-68-gb18ca31 torch 1.8.1+cu101 CPU

Fusing layers... 
Model Summary: 224 layers, 7266973 parameters, 0 gradients

PyTorch: starting from yolov5s.pt (14.8 MB)

TorchScript: starting export with torch 1.8.1+cu101...
/content/yolov5/models/yolo.py:51: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if self.grid[i].shape[2:4] != x[i].shape[2:4] or self.onnx_dynamic:
TorchScript: export success, saved as yolov5s.torchscript.pt (29.2 MB)
ONNX: starting export with onnx 1.9.0...
ONNX: simplifying with onnx-simplifier 0.3.5...
ONNX: simplifier failure: [ONNXRuntimeError] : 1 : FAIL : Node (Mul_925) Op (Mul) [ShapeInferenceError] Incompatible dimensions
ONNX: export success, saved as yolov5s.onnx (29.2 MB)
CoreML: export failure: No module named 'coremltools'

Export complete (9.93s). Visualize with https://github.com/lutzroeder/netron.
```

**Comment by glenn-jocher** [comment]
@Mak-24 I'm not sure I understand. If --inplace fails why use it? Export works correctly for the default use case and with --simplify also.

<img width="1218" alt="Screen Shot 2021-05-06 at 1 30 07 PM" src="https://user-images.githubusercontent.com/26833433/117291375-36449800-ae6f-11eb-86dc-69f543827540.png">

**Comment by Mak-24** [comment]
@glenn-jocher  According to the export code, it adds the detect part of it. 
```
parser.add_argument('--inplace', action='store_true', help='set YOLOv5 Detect() inplace=True')
```
And based on what I could gather from [This comment on another issue](https://github.com/ultralytics/yolov5/issues/343#issuecomment-658021043l)  I need to get the detect layer in order for it to have the same output. Since I'm implementing this on the node  I was hoping could get the final output and not do the postprocessing they have mention here.

**Comment by glenn-jocher** [comment]
@Mak-24 Detect() layer is included by default in all exported models, no arguments are required for this.

**Comment by Mak-24** [comment]
@glenn-jocher  There's an output difference between the standard PyTorch model and the onnx export.
The output of the onnx model has 3 arrays of shapes:
```
(1, 3, 80, 80, 27)
(1, 3, 40, 40, 27)
(1, 3, 20, 20, 27)
```
Meanwhile, the standard model has the shape:
```
(1, 15120, 27)
```
Am I missing something here? Based on [this issue](https://github.com/ultralytics/yolov5/issues/343#issuecomment-658021043l) I came to the conclusion the the Detect() layer is what is the cause of difference between the 2 outputs.

**Comment by glenn-jocher** [comment]
@Mak-24 your code is out of date. Please git pull or git clone to receive the latest updates.
