### ISSUE TITLE
New version is labeling just the half of total of frames in some videos

### ISSUE THREAD

**Issue by hdnh2006** [ultralytics/yolov5#3056]
Hello, something weird is happening with the last commit of this fantastic repo.

It seems the code is skipping one frame in each iteration for certain videos.

These are the videos I am doing inference: [google drive link](https://drive.google.com/drive/folders/1sGWVusg_AJTQ-ljars6hBwLPfnB_rOcA?usp=sharing)

I ran:
```
python detect.py --source my_video.mp4 --weights my_best.pt 
```
And I got the following results, then I check my git version and it seems well:
![image](https://user-images.githubusercontent.com/17271049/117333483-42dde600-ae99-11eb-830a-6f4c785b611b.png)

So I decided to try with other video and same results were obtained. Maybe my weights have the problem (it doesn't make any sense but who knows), and the results are the following:
```
python detect.py --source my_video2.mp4
```
And I got similar results:
![image](https://user-images.githubusercontent.com/17271049/117334388-3a39df80-ae9a-11eb-853c-d226e4b8c677.png)

## 🐛 Bug
Everything goes well in images
![image](https://user-images.githubusercontent.com/17271049/117334491-59387180-ae9a-11eb-9696-d1c4fc021878.png)

And everything goes well in videos from other sources
![image](https://user-images.githubusercontent.com/17271049/117335278-470b0300-ae9b-11eb-9973-809bfad0cafd.png)

## To Reproduce
Just try to inference with any weights on the videos I attached.

**Comment by glenn-jocher** [comment]
@hdnh2006 thanks for the bug report! I'm not able to reproduce this myself. We have two official videos we use for validation, both are about 1 second long (30 frames), and they both run inference correctly in our Colab notebook:

https://github.com/ultralytics/yolov5/releases/download/v1.0/decelera_landscape.mov
https://github.com/ultralytics/yolov5/releases/download/v1.0/decelera_portrait.mov

<img width="1365" alt="Screen Shot 2021-05-08 at 8 47 06 PM" src="https://user-images.githubusercontent.com/26833433/117550130-d43a8d00-b03e-11eb-9ca7-16a98163a3ae.png">

**Comment by hdnh2006** [comment]
Did you try with the attached videos in this link [link](https://drive.google.com/drive/folders/1sGWVusg_AJTQ-ljars6hBwLPfnB_rOcA?usp=sharing)?

I think it is not a problem about YOLO but OpenCV.

**Comment by glenn-jocher** [comment]
@hdnh2006 yes I get the same result with your car chase (good) and video2 (half frames) videos. 

Video2 may simply be an odd format. I can't view it on my macbook for example, so it may be lucky that cv2 can open it at all.

In any case though yes, you should raise this issue with the opencv-python repo to bring it to their attention.

**Comment by hdnh2006** [comment]
I see, that's what I'm gonna do. I just tried to post the "bug" just in case someone else had the same problem.

Thank you Glenn, and sorry for opening as a bug. Remember, I owe you a beer in case you come back to Madrid hehe. 

Best.
