### ISSUE TITLE
params

### ISSUE THREAD

**Issue by milla-Lee** [ultralytics/yolov5#3059]
## ❔Question

hi author,i have a question about params,yolov5s has 7.3M，and i saw you said default YOLOV5s：Model Summary:283 layers,7276605 parameters ,7276605 gradients,17.1 GFLOPS.
how  convert 7276605 parameters to 7.3M? 
looking forward to your reply.thanks!

**Comment by glenn-jocher** [comment]
The numbers you are comparing are the same. M stands for million.
