### ISSUE TITLE
About multi-GPU training of Yolov5 1.0

### ISSUE THREAD

**Issue by TangMinLeo** [ultralytics/yolov5#3060]
## ❔Question
Considering the pytorch version consistency, I need a Yolov5 model trained under pytorch1.4 .
 I found that  Yolov5 1.0 is a version that can run under pytorch 1.4. But there is no cue tells me how to train that version in Multi-process Multi-GPU distributed training fashion. Could anyone give some advice ?

**Comment by glenn-jocher** [comment]
@TangMinLeo sorry, due to the rapid pace of change and limited support resources we can't provide support for earlier versions of the repo. I would recommend cloning the latest version and using PyTorch 1.8.1.
