### ISSUE TITLE
YOLOv5 mAP and Precision Calculation

### ISSUE THREAD

**Issue by edahall** [ultralytics/yolov5#3062]
So I have trained my model for 1000 epochs in Google Colab and have the Tensorboard evaluation graphs as seen below. What I was wondering is how I get a single number for e.g. the mAP@.5 or the Precision.

This would help me a lot when comparing datasets, e.g. dataset 1 had a precision of 0.85 and a recall of 0.79 while dataset 2 had a precision of 0.5 and a recall of 0.62.
Thank you :)

![50 50 TRAINING](https://user-images.githubusercontent.com/67170200/117395866-5ebca880-aee8-11eb-8663-aa69eaf401a7.JPG)
![results (2)](https://user-images.githubusercontent.com/67170200/117395885-6aa86a80-aee8-11eb-86e8-6d550f35a5b3.png)

CODE USED TO OPEN TENSORBOARD:
%load_ext tensorboard
%tensorboard --logdir /content/yolov5/runs

**Comment by glenn-jocher** [comment]
@edahall evaluate best.pt or pick an arbitrary value from your tensorboard results (best or last).
```
python test.py --weights path/to/best.pt
```

**Comment by edahall** [comment]
@glenn-jocher 

> @edahall evaluate best.pt or pick an arbitrary value from your tensorboard results (best or last).
> 
> ```
> python test.py --weights path/to/best.pt
> ```

Hi, thanks for your reply. I have tried to use this before and no luck! Any help would be appreciated a lot, thank you :)
This is the output I get from running the code above (while being cd'd into the yolov5 folder) :

---
Namespace(augment=False, batch_size=32, conf_thres=0.001, data='data/coco128.yaml', device='', exist_ok=False, img_size=640, iou_thres=0.6, name='exp', project='runs/test', save_conf=False, save_hybrid=False, save_json=False, save_txt=False, single_cls=False, task='val', verbose=False, weights=['/weights/best.pt'])
YOLOv5 🚀 v5.0-73-gd2a1728 torch 1.8.1+cu102 CUDA:0 (Tesla V100-SXM2-16GB, 16160.5MB)

Traceback (most recent call last):
  File "test.py", line 329, in <module>
    opt=opt
  File "test.py", line 57, in test
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "/content/yolov5/models/experimental.py", line 120, in attempt_load
    ckpt = torch.load(w, map_location=map_location)  # load
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/weights/best.pt'
---

I tried again writing out the full path and double checking all the folder names and got this:

`!python test.py --weights /content/yolov5/runs/train/exp2/weights/best.pt` 

---
Namespace(augment=False, batch_size=32, conf_thres=0.001, data='data/coco128.yaml', device='', exist_ok=False, img_size=640, iou_thres=0.6, name='exp', project='runs/test', save_conf=False, save_hybrid=False, save_json=False, save_txt=False, single_cls=False, task='val', verbose=False, weights=['/content/yolov5/runs/train/exp2/weights/best.pt'])
YOLOv5 🚀 v5.0-73-gd2a1728 torch 1.8.1+cu102 CUDA:0 (Tesla V100-SXM2-16GB, 16160.5MB)

Fusing layers... 
Model Summary: 232 layers, 7246518 parameters, 0 gradients, 16.8 GFLOPS

WARNING: Dataset not found, nonexistent paths: ['/content/coco128/images/train2017']
Downloading https://github.com/ultralytics/yolov5/releases/download/v1.0/coco128.zip ...
100% 21.1M/21.1M [00:01<00:00, 20.5MB/s]
Dataset autodownload success

val: Scanning '../coco128/labels/train2017' images and labels... 128 found, 0 missing, 2 empty, 0 corrupted: 100% 128/128 [00:00<00:00, 2723.08it/s]
val: New cache created: ../coco128/labels/train2017.cache
               Class      Images      Labels           P           R      mAP@.5  mAP@.5:.95:  25% 1/4 [00:01<00:03,  1.20s/it]Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/content/yolov5/utils/plots.py", line 182, in plot_images
    cls = names[cls] if names else cls
KeyError: 34

               Class      Images      Labels           P           R      mAP@.5  mAP@.5:.95:  50% 2/4 [00:01<00:01,  1.16it/s]Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/content/yolov5/utils/plots.py", line 182, in plot_images
    cls = names[cls] if names else cls
KeyError: 32

               Class      Images      Labels           P           R      mAP@.5  mAP@.5:.95:  75% 3/4 [00:02<00:00,  1.30it/s]Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/content/yolov5/utils/plots.py", line 182, in plot_images
    cls = names[cls] if names else cls
KeyError: 56

               Class      Images      Labels           P           R      mAP@.5  mAP@.5:.95: 100% 4/4 [00:02<00:00,  1.34it/s]
Traceback (most recent call last):
  File "test.py", line 329, in <module>
    opt=opt
  File "test.py", line 223, in test
    p, r, ap, f1, ap_class = ap_per_class(*stats, plot=plots, save_dir=save_dir, names=names)
  File "/content/yolov5/utils/metrics.py", line 73, in ap_per_class
    plot_mc_curve(px, f1, Path(save_dir) / 'F1_curve.png', names, ylabel='F1')
  File "/content/yolov5/utils/metrics.py", line 212, in plot_mc_curve
    ax.plot(px, y, linewidth=1, label=f'{names[i]}')  # plot(confidence, metric)
KeyError: 1
---

**Comment by glenn-jocher** [comment]
@edahall my example code is just an example, **you have to pass your own model and your own dataset.**
