### ISSUE TITLE
Cls loss 0

### ISSUE THREAD

**Issue by debparth** [ultralytics/yolov5#3064]
## ❔Question
I'm training Yolov5m model over my dataset which has only 1 class in it. While training I'm seeing that my `cls loss` is 0 in each and every epoch. Is it because of the reason that I only have 1 class in my dataset or due to some other reason?

**Comment by Yassine-Fak** [comment]
Hi! I think that this is due to the fact that you have only one class in your dataset. Is that right @glenn-jocher  ? 
By the way @glenn-jocher  thank you so much for this amazing great repository and job!!!!

**Comment by glenn-jocher** [comment]
@Yassine-Fak @debparth single-class datasets don't incur class loss. If I asked you to pick a number between 0 and 0, you wouldn't have to think hard would you?

**Comment by debparth** [comment]
@glenn-jocher yea... true. And one more thing while training the img_size differs to the param passed. 

![image](https://user-images.githubusercontent.com/53347017/117448895-f0fe9400-af5c-11eb-9aa1-acc5ad6969e7.png)
 
 like here it shows that I want to use `864` then why does it shows `1728`?

**Comment by glenn-jocher** [comment]
@debparth If you believe you have a reproducible issue, we suggest you close this issue and raise a new one using the 🐛 **Bug Report template**, providing screenshots and a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. Thank you!
