### ISSUE TITLE
mAP abnormally low after resuming and can be solved by deleting shape.npy under label folder

### ISSUE THREAD

**Issue by Zacchaeus00** [ultralytics/yolov5#307]
Before submitting a bug report, please be aware that your issue **must be reproducible** with all of the following, otherwise it is non-actionable, and we can not help you:
 - **Current repo**: run `git fetch && git status -uno` to check and `git pull` to update repo
 - **Common dataset**: coco.yaml or coco128.yaml
 - **Common environment**: Colab, Google Cloud, or Docker image. See https://github.com/ultralytics/yolov5#reproduce-our-environment
 
If this is a custom dataset/training question you **must include** your `train*.jpg`, `test*.jpg` and `results.png` figures, or we can not help you. You can generate these with `utils.plot_results()`.

## To Reproduce (REQUIRED)

Input:
```
import torch

a = torch.tensor([5])
c = a / 0
```

Output:
```
Traceback (most recent call last):
  File "/Users/glennjocher/opt/anaconda3/envs/env1/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-be04c762b799>", line 5, in <module>
    c = a / 0
RuntimeError: ZeroDivisionError
```

## Environment

 - OS: [e.g. Ubuntu]
 - GPU [e.g. 2080 Ti]

**Comment by glenn-jocher** [comment]
@Zacchaeus14 can you clarify a bit better the problem you're seeing?

**Comment by glenn-jocher** [comment]
@Zacchaeus14 is this related to #306?

**Comment by Zacchaeus00** [comment]
Yes, the problem I encountered is exactly same as #306. Specifically, train.py doesn't work when it loads an old .npy file. Thank you for your reply.

**Comment by Zacchaeus00** [comment]
btw, I was running on a cloab VM.

**Comment by glenn-jocher** [comment]
@Zacchaeus14 ok got it! The dataloading code affected by this will hopefully undergo a revamp this week to fix this and incorporate a few other improvements.

I'll close this issue as duplicate and focus the conversation then on #306 since it was opened earlier.

**Comment by glenn-jocher** [comment]
@Zacchaeus14 I just pushed a major update https://github.com/ultralytics/yolov5/commit/520f5de6f0febf30dd3545793f528c3478c18299 that should resolve all label caching issues. Labels and images are scanned together the first time a dataset is trained, and cached into a labels.cache file now which contains a dictionary of image names, shapes, labels and a unique hash for the cached dataset. Images are scanned for corruption now also as part of the process. All subsequent trainings retrieve the current hash value of the dataset, and if it matches the cached value, then the cached file is used, else the entire dataset is recached and a new file saved. Please try out the changes and let me know if this resolves your issue!
