### ISSUE TITLE
[Question] How to change pop-up window display-width and height during webcam inferencing

### ISSUE THREAD

**Issue by abuelgasimsaadeldin** [ultralytics/yolov5#3072]
## ❔Question
Hi, I have seen in detect.py the argument ```--img-size``` which is set to 640 by default, I am assuming that this is the capture width and capture height. I would like to know where is the code to set the display width and height while performing live webcam inferencing so that I could adjust it accordingly [for example set it to 1280x640].  

## Additional context
I would like to experiment and see how changes in the capture width and height effect the model fps as well as changes in the display width and height. Thanks!

**Comment by glenn-jocher** [comment]
@abuelgasimsaadeldin stream properties are not modifiable as far as I know, they are fixed properties, i.e. FPS, size etc. If you were to modify them you'd want to start looking at RTSP commands/addresses etc.
