### ISSUE TITLE
Crop Image Save

### ISSUE THREAD

**Issue by tiwarikaran** [ultralytics/yolov5#3076]
## Additional context

Is there a feature that helps us to crop the image and save it directly?

**Comment by glenn-jocher** [comment]
@tiwarikaran yes you can crop detected boxes with `--save-crop`:
```
python detect.py --save-crop
```

**Comment by tiwarikaran** [comment]
![image](https://user-images.githubusercontent.com/66107781/117535517-c885a100-b013-11eb-8e4f-d33f3d9eec27.png)

What to write in the argument?

**Comment by glenn-jocher** [comment]
Your code is out of date, git pull or git clone again to update and then retry your command.

**Comment by saeedbeiraki** [comment]
I cloned again, but I got the same error.

**Comment by glenn-jocher** [comment]
@saeedbeiraki `--save-crop` **works correctly** and as intended. If you believe you have a reproducible issue, we suggest you close this issue and raise a new one using the 🐛 **Bug Report template**, providing screenshots and a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. Thank you!

<img width="1213" alt="Screenshot 2021-05-09 at 12 43 54" src="https://user-images.githubusercontent.com/26833433/117569122-5c16aa80-b0c4-11eb-94e4-7a24a27ff2ce.png">

**Comment by saeedbeiraki** [comment]
Thanks a lot @glenn-jocher. my mistake. I was cloning some old version.
