### ISSUE TITLE
Torch.hub.load deserialization error on a CPU machine

### ISSUE THREAD

**Issue by dmitrii-badretdinov** [ultralytics/yolov5#3079]
## 🐛 Bug
Using `torch.hub.load` to retrieve a model will give a CUDA deserialization error on a machine without CUDA.
That leads to the case where it's unknown how to load a model on a CPU-only machine because `torch.hub.load` and the suggested `torch.load` have significantly different syntax.

## To Reproduce

Input:
On the machine without CUDA, in a fresh Anaconda environment:
```
> conda install python torch torchvision 
> pip install pandas requests opencv-python tqdm pyyaml matplotlib seaborn
> python
>>> import torch
>>> model = torch.hub.load('ultralytics/yolov5', 'yolov5s')
```

Output:
Irrelevant parts of paths are replaced by `[...]`.
```
Using cache found in [...]Dmitrii/.cache\torch\hub\ultralytics_yolov5_master
Downloading https://github.com/ultralytics/yolov5/releases/download/v5.0/yolov5s.pt to yolov5s.pt...
100%|█████████████████| 14.1M/14.1M

Fusing layers...
Model Summary: 224 layers, 7266973 parameters, 0 gradients
Adding autoShape...
YOLOv5  2021-5-8 torch 1.8.1+cpu CPU

Traceback (most recent call last):
  File "[...]\TorchHub\test.py", line 4, in <module>
    ssd_model = torch.hub.load('NVIDIA/DeepLearningExamples:torchhub', 'nvidia_ssd', model_math=precision)
  File "[...]\Miniconda\envs\general-python\lib\site-packages\torch\hub.py", line 339, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "[...]\Miniconda\envs\general-python\lib\site-packages\torch\hub.py", line 368, in _load_local
    model = entry(*args, **kwargs)
  File "[...]Dmitrii/.cache\torch\hub\NVIDIA_DeepLearningExamples_torchhub\hubconf.py", line 369, in nvidia_ssd
    ckpt = torch.load(ckpt_file)
  File "[...]\Miniconda\envs\general-python\lib\site-packages\torch\serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "[...]\Miniconda\envs\general-python\lib\site-packages\torch\serialization.py", line 772, in _legacy_load
    result = unpickler.load()
  File "[...]\Miniconda\envs\general-python\lib\site-packages\torch\serialization.py", line 728, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "[...]\Miniconda\envs\general-python\lib\site-packages\torch\serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "[...]\Miniconda\envs\general-python\lib\site-packages\torch\serialization.py", line 151, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "[...]\Miniconda\envs\general-python\lib\site-packages\torch\serialization.py", line 135, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. 
If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map 
your storages to the CPU
```

## Expected behavior
The model loading without errors through a different command if it exists.

## Environment
 - OS: Windows 10
 - GPU: RTX 2070

## Additional information
Related issue and its solution: https://stackoverflow.com/questions/61826246/how-to-use-map-location-cpu-due-to-runtimeerror-attempting-to-deserialize-ob

**Comment by dmitrii-badretdinov** [comment]
Related issue and resolution: https://stackoverflow.com/questions/61826246/how-to-use-map-location-cpu-due-to-runtimeerror-attempting-to-deserialize-ob

**Comment by glenn-jocher** [comment]
@dmitrii-badretdinov anaconda torch installs tend to be unreliable unfortunately. We recommend pip installs for all environments. Some more info on environment issues:

It appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below. 


## Requirements

**Python 3.8** or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including **`torch>=1.7`**. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.
