### ISSUE TITLE
How can I adjust the size of the recognized box and font? 

### ISSUE THREAD

**Issue by zhxngjxnhxx** [ultralytics/yolov5#3083]
## ❔Question
How can I adjust the size of the recognized box and font? 

## Additional context
this is a great project, but how can I adjust the size of the recognized box and font? When the targets are dense, I can’t distinguish the recognition results given.

**Comment by glenn-jocher** [comment]
@zhxngjxnhxx you hide labels entirely or hide confidences using the detect.py arguments here:
https://github.com/ultralytics/yolov5/blob/251aeafcb16ebc4c9d9a6641b3677aaac2f2d2cb/detect.py#L171-L172

If you would like full control over the box plotting you can modify plot_one_box() inputs or code here:
https://github.com/ultralytics/yolov5/blob/251aeafcb16ebc4c9d9a6641b3677aaac2f2d2cb/detect.py#L108-L112
