### ISSUE TITLE
How to visualize feature mapping on YOLOV5s?

### ISSUE THREAD

**Issue by Mashood3624** [ultralytics/yolov5#3089]
## ❔Question
I have been searching for hours but I cannot find a single repo or issue on github which tells how can we visualize feature maps of a yolo model.

Sample: 
![feature](https://user-images.githubusercontent.com/57293901/117591145-7b591a80-b14c-11eb-8c23-8095d3f38ec5.png)

**Comment by glenn-jocher** [comment]
@Mashood3624 you should be able to visualize data anywhere in the model by inserting your own plotting routines wherever you want. The model forward method is probably a good place to start:
https://github.com/ultralytics/yolov5/blob/525f4f86a92a8037aec9af34460ffa2b83f1d404/models/yolo.py#L72-L118

**Comment by thanhphuchuynh** [comment]
> @Mashood3624 you should be able to visualize data anywhere in the model by inserting your own plotting routines wherever you want. The model forward method is probably a good place to start:
> https://github.com/ultralytics/yolov5/blob/525f4f86a92a8037aec9af34460ffa2b83f1d404/models/yolo.py#L72-L118

I tried it and it worked! thanks 👍 
```
for ii in range(len(x[i][0].permute(3, 0, 1, 2))):
    plt.subplot(3,7,ii+1)
    b =  np.array(255*x[i][0].permute(3, 0, 1, 2)[ii, :, :, :].permute(1, 2, 0).cpu().detach().numpy()[:, :, ::-1])
    plt.imshow(cv2.cvtColor(b.astype('uint8'), cv2.COLOR_BGR2RGB))
    plt.axis("off")
plt.show()
```

**Comment by glenn-jocher** [comment]
Oh great! Though I think there may be a bug in your plotting code, as the feature maps lack any concept of RGB or BGR 'colors'. You may have confused the anchor dimension for a color dimension.

**Comment by thanhphuchuynh** [comment]
After i remove RGB  and BGR in my code.
the result: 
![image](https://user-images.githubusercontent.com/48717211/117793262-40eb9c80-b276-11eb-8a22-ddd6ba478c46.png)

**Comment by glenn-jocher** [comment]
@ThanhPhucHuynh the feature maps have no concept of RGB or BGR as I said, but your images are in color. The channel dimension that inputs 3 colors is stretched to over a thousand channels eventually, but none of them are paired in 3s for color.

**Comment by thanhphuchuynh** [comment]
i tried again and result. thanks sir <3
![image](https://user-images.githubusercontent.com/48717211/118071620-5675d900-b3d2-11eb-89cf-85e1f9a64b39.png)

**Comment by glenn-jocher** [comment]
@ThanhPhucHuynh interesting!

**Comment by wanghangege** [comment]
> > @Mashood3624 you should be able to visualize data anywhere in the model by inserting your own plotting routines wherever you want. The model forward method is probably a good place to start:
> > https://github.com/ultralytics/yolov5/blob/525f4f86a92a8037aec9af34460ffa2b83f1d404/models/yolo.py#L72-L118
> 
> I tried it and it worked! thanks 👍
> 
> ```
> for ii in range(len(x[i][0].permute(3, 0, 1, 2))):
>     plt.subplot(3,7,ii+1)
>     b =  np.array(255*x[i][0].permute(3, 0, 1, 2)[ii, :, :, :].permute(1, 2, 0).cpu().detach().numpy()[:, :, ::-1])
>     plt.imshow(cv2.cvtColor(b.astype('uint8'), cv2.COLOR_BGR2RGB))
>     plt.axis("off")
> plt.show()
> ```

Hello, I'm a novice. I'd like to ask you, where should the visual code you disclose be inserted?

**Comment by thanhphuchuynh** [comment]
> > > @Mashood3624 you should be able to visualize data anywhere in the model by inserting your own plotting routines wherever you want. The model forward method is probably a good place to start:
> > > https://github.com/ultralytics/yolov5/blob/525f4f86a92a8037aec9af34460ffa2b83f1d404/models/yolo.py#L72-L118
> > 
> > 
> > I tried it and it worked! thanks 👍
> > ```
> > for ii in range(len(x[i][0].permute(3, 0, 1, 2))):
> >     plt.subplot(3,7,ii+1)
> >     b =  np.array(255*x[i][0].permute(3, 0, 1, 2)[ii, :, :, :].permute(1, 2, 0).cpu().detach().numpy()[:, :, ::-1])
> >     plt.imshow(cv2.cvtColor(b.astype('uint8'), cv2.COLOR_BGR2RGB))
> >     plt.axis("off")
> > plt.show()
> > ```
> 
> Hello, I'm a novice. I'd like to ask you, where should the visual code you disclose be inserted?

In the model forward method, you should custom again code.

**Comment by GiorgioSgl** [comment]
> > > @Mashood3624 you should be able to visualize data anywhere in the model by inserting your own plotting routines wherever you want. The model forward method is probably a good place to start:
> > > https://github.com/ultralytics/yolov5/blob/525f4f86a92a8037aec9af34460ffa2b83f1d404/models/yolo.py#L72-L118
> > 
> > 
> > I tried it and it worked! thanks +1
> > ```
> > for ii in range(len(x[i][0].permute(3, 0, 1, 2))):
> >     plt.subplot(3,7,ii+1)
> >     b =  np.array(255*x[i][0].permute(3, 0, 1, 2)[ii, :, :, :].permute(1, 2, 0).cpu().detach().numpy()[:, :, ::-1])
> >     plt.imshow(cv2.cvtColor(b.astype('uint8'), cv2.COLOR_BGR2RGB))
> >     plt.axis("off")
> > plt.show()
> > ```
> 
> Hello, I'm a novice. I'd like to ask you, where should the visual code you disclose be inserted?

Have you understand how to plot the feature maps?

**Comment by wanghangege** [comment]
> > > > @Mashood3624 you should be able to visualize data anywhere in the model by inserting your own plotting routines wherever you want. The model forward method is probably a good place to start:
> > > > https://github.com/ultralytics/yolov5/blob/525f4f86a92a8037aec9af34460ffa2b83f1d404/models/yolo.py#L72-L118
> > > 
> > > 
> > > I tried it and it worked! thanks +1
> > > ```
> > > for ii in range(len(x[i][0].permute(3, 0, 1, 2))):
> > >     plt.subplot(3,7,ii+1)
> > >     b =  np.array(255*x[i][0].permute(3, 0, 1, 2)[ii, :, :, :].permute(1, 2, 0).cpu().detach().numpy()[:, :, ::-1])
> > >     plt.imshow(cv2.cvtColor(b.astype('uint8'), cv2.COLOR_BGR2RGB))
> > >     plt.axis("off")
> > > plt.show()
> > > ```
> > 
> > 
> > Hello, I'm a novice. I'd like to ask you, where should the visual code you disclose be inserted?
> 
> Have you understand how to plot the feature maps?

yes, I know.  应该是在前向传播中添加可视化程序即可。

**Comment by Mashood3624** [comment]
Hi, I have tried implementing feature maps from @ThanhPhucHuynh repo but It dont look great. @glenn-jocher  Can you confirm if it is right or not ?

![Screenshot (2)](https://user-images.githubusercontent.com/57293901/123113369-5c100700-d3f3-11eb-9fa2-bff23b3f25bc.png)

https://github.com/ThanhPhucHuynh/yolov5_xray/blob/a52b9934b2912840c7df6a4e60c5910aeda96e68/models/yolo.py

here is some pictures 

![0y](https://user-images.githubusercontent.com/57293901/123113474-70540400-d3f3-11eb-9108-f7ee6ccee87e.png)
![1y](https://user-images.githubusercontent.com/57293901/123113488-72b65e00-d3f3-11eb-8121-42370bef2cd2.png)
![2y](https://user-images.githubusercontent.com/57293901/123113495-73e78b00-d3f3-11eb-8cf9-497f96fc6808.png)

**Comment by glenn-jocher** [comment]
@Mashood3624 thats incorrect.

Feature maps are square for 640x640 inputs and there are more than a thousand of them in a YOLOv5l output.

**Comment by glenn-jocher** [comment]
@Mashood3624 good news 😃! Feature map visualization was added ✅ in PR #3804 by @Zigars today. This allows for visualizing feature maps from any part of the model from any function (i.e. detect.py, train.py, test.py). Feature maps are saved as *.png files in runs/features/exp directory. To turn on feature visualization set `feature_vis=True` in the model forward method and define the layer you want to visualize (default is SPP layer).

https://github.com/ultralytics/yolov5/blob/20d45aa4f18d7df7148fc6dd69a9c0607003f004/models/yolo.py#L158-L160

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

![layer_8_SPP_features](https://user-images.githubusercontent.com/26833433/123628234-27e17f80-d813-11eb-8d72-5d5560cd9ee4.png)

**Comment by Mashood3624** [comment]
Thank you @glenn-jocher 😊

**Comment by ControllableGeneration** [comment]
1, I realize that below `if not os.path.isdir(save_dir):
os.mkdir(save_dir)
`need to be added to the 432nd line of utils/plots.py in order to not get a file or directory not found error
2, and you should do plt.close() after plt.savefig() in order to avoid opening too many images

**Comment by glenn-jocher** [comment]
@ZiyuBao making directories is handled in detect.py here:
https://github.com/ultralytics/yolov5/blob/2d99063201105d992f8b0dada3c9c7a206e582e7/detect.py#L113-L114

matplotlib is actually placed in a mode where it doesn't produce any windows here, so I think we can skip plt.close() calls
https://github.com/ultralytics/yolov5/blob/2d99063201105d992f8b0dada3c9c7a206e582e7/utils/plots.py#L20-L22

**Comment by noreenanwar** [comment]
Hi, how can we visualize class probability map after detection?

**Comment by glenn-jocher** [comment]
👋 Hello! Thanks for asking about **feature visualization**. YOLOv5 🚀 features can be visualized through all stages of the model from input to output. To visualize features from a given source run `detect.py` with the `--visualize` flag:
```bash
python detect.py --weights yolov5s.pt --source data/images/bus.jpg --visualize
```

An example [Notebook](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb) visualizing [bus.jpg](https://github.com/ultralytics/yolov5/blob/master/data/images/bus.jpg) features with YOLOv5s is shown below:

<a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
<img width="1811" alt="Screenshot 2021-08-30 at 16 44 04" src="https://user-images.githubusercontent.com/26833433/131357928-663a120a-3133-4e1a-8995-c812bd732e8a.png">

All stages are visualized by default, each with its own PNG showing the first 32 feature maps **output** from that stage. You can open any PNG for a closer look. For example the first 32 feature maps of the Focus() layer output are shown in `stage0_Focus_features.png`:

![stage0_Focus_features](https://user-images.githubusercontent.com/26833433/131359874-ecc9aef8-1c9b-44f5-ac17-d6b987093554.png)

Feature maps may be customized by updating the `feature_visualization()` function in `utils/plots.py`:
https://github.com/ultralytics/yolov5/blob/bb5ebc290e5d630a081d7cbc5a9725ed8cea0a24/utils/plots.py#L403-L427

Good luck 🍀 and let us know if you have any other questions!

**Comment by noreenanwar** [comment]
Hi, Thanks for your reply.
I want to visualize only detected objects.It is possible to only get the class probability maps ?

**Comment by glenn-jocher** [comment]
@noreenanwar class probability vectors are stripped in the NMS function, you can access the full vectors there:
https://github.com/ultralytics/yolov5/blob/0c1324067c348c985b0c689a1e71cd9ba01513e0/utils/general.py#L776-L875

**Comment by noreenanwar** [comment]
I should add the following lines in this file?.

 visualize = increment_path(save_dir / Path(path).stem, mkdir=True) if visualize else False 
 pred = model(img, augment=augment, visualize=visualize)[0]

**Comment by glenn-jocher** [comment]
@noreenanwar yes, you can customize the visualization output by adding those lines to the file. Make sure to also define the `save_dir` variable, which should hold the path where you want to save the visualizations. This will allow you to generate and save only the desired class probability maps. Let me know if you need further help with this!

**Comment by Muhammad-237** [comment]
> > @Mashood3624 you should be able to visualize data anywhere in the model by inserting your own plotting routines wherever you want. The model forward method is probably a good place to start:
> > https://github.com/ultralytics/yolov5/blob/525f4f86a92a8037aec9af34460ffa2b83f1d404/models/yolo.py#L72-L118
> 
> I tried it and it worked! thanks 👍
> 
> ```
> for ii in range(len(x[i][0].permute(3, 0, 1, 2))):
>     plt.subplot(3,7,ii+1)
>     b =  np.array(255*x[i][0].permute(3, 0, 1, 2)[ii, :, :, :].permute(1, 2, 0).cpu().detach().numpy()[:, :, ::-1])
>     plt.imshow(cv2.cvtColor(b.astype('uint8'), cv2.COLOR_BGR2RGB))
>     plt.axis("off")
> plt.show()
> ```

how did you make changes to this can you show me step by step i dont understand what you did to make feature map
