### ISSUE TITLE
Can I get a pretrained model to detect human and car?

### ISSUE THREAD

**Issue by leeyunhome** [ultralytics/yolov5#3090]
## ❔Question

I'm trying to use it for demo.

Can I get a pretrained model to detect human and car?

Is there a yolov5 pretrained model zoo?

**Comment by debparth** [comment]
@leeyunhome You can use any pre-trained model since, they are trained on COCO dataset which have this classes. You just have to filter the outputs.

**Comment by glenn-jocher** [comment]
Person and Car are classes 0 and 2 in COCO, so you can use any YOLOv5 model to detect these classes only:

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')
model.classes = [0, 2]  # person and car

# Image
img = 'https://github.com/ultralytics/yolov5/raw/master/data/images/zidane.jpg'

# Inference
results = model(img)
results.print()  # or .show(), .save()
```

**Comment by leeyunhome** [comment]
> Person and Car are classes 0 and 2 in COCO, so you can use any YOLOv5 model to detect these classes only:
> 
> ```python
> import torch
> 
> # Model
> model = torch.hub.load('ultralytics/yolov5', 'yolov5s')
> model.classes = [0, 2]  # person and car
> 
> # Image
> img = 'https://github.com/ultralytics/yolov5/raw/master/data/images/zidane.jpg'
> 
> # Inference
> results = model(img)
> results.print()  # or .show(), .save()
> ```

Hello, @glenn-jocher 

Are there any learning models other than Coco?

Thank you.

**Comment by glenn-jocher** [comment]
@leeyunhome COCO pretrained YOLOv5 models are available. You can train these on any of the datasets with autodownload capability in https://github.com/ultralytics/yolov5/tree/master/data

- [x] [COCO](https://cocodataset.org/#home)
- [x] [COCO128](https://www.kaggle.com/datasets/ultralytics/coco128)
- [x] [VOC](http://host.robots.ox.ac.uk/pascal/VOC/)
- [x] [Argoverse-HD](http://www.cs.cmu.edu/~mengtial/proj/streaming/)
- [x] [VisDrone2019-DET](https://github.com/VisDrone/VisDrone-Dataset)
- [x] [GlobalWheat-2020](http://www.global-wheat.com/)
- [ ] [KITTI](https://www.kaggle.com/twaldo/kitti-object-detection)
- [ ] [SKU110](https://github.com/eg4000/SKU110K_CVPR19) (grocery store items)
- [ ] [CityScapes](https://www.cityscapes-dataset.com/)
- [x] [Objects365](https://www.objects365.org/overview.html)
- [ ] [OpenImages](https://storage.googleapis.com/openimages/web/index.html)
