### ISSUE TITLE
Understanding the arguments column in Yolov5s and Yolov5x models

### ISSUE THREAD

**Issue by khalidw** [ultralytics/yolov5#3091]
## ❔Question
Can someone explain the arguments column, as in what exactly do each argument represent.

# Yolov5s
![image](https://user-images.githubusercontent.com/31723666/117625573-95681c80-b18f-11eb-8350-625508fcfea9.png)

# Yolov5x
![image](https://user-images.githubusercontent.com/31723666/117625984-0b6c8380-b190-11eb-88b7-14c88b25b49b.png)

**Comment by glenn-jocher** [comment]
@khalidw each module in the 'modules' column requires arguments. These arguments are shown in the 'arguments' column.
