### ISSUE TITLE
Adding more custom data augmentations 

### ISSUE THREAD

**Issue by ebyau** [ultralytics/yolov5#3092]
Hello, 
Yolov5 has some already predetermined data augmentations, however how can i add more augmentations to the existing ones

**Comment by glenn-jocher** [comment]
@ebyau you modify existing augmentations in the hyperparameter file:
https://github.com/ultralytics/yolov5/blob/525f4f86a92a8037aec9af34460ffa2b83f1d404/data/hyp.scratch.yaml#L22-L33

Or if you'd like to introduce additional custom augmentations the trainloader is a good place to start:
https://github.com/ultralytics/yolov5/blob/525f4f86a92a8037aec9af34460ffa2b83f1d404/utils/datasets.py#L521-L595
