### ISSUE TITLE
Precision Recall and mAP

### ISSUE THREAD

**Issue by carry-xz** [ultralytics/yolov5#31]
hi , nice work
But when i train with my dataset which only has one class, I get same p, r with diffierent iou threshold. is that right?  this is the result of p r and ap , I just print the value in test.py line 178.

p: [[    0.39592     0.39592     0.39592     0.39592     0.39592     0.39592     0.39592     0.39592     0.39592     0.39592]]
r: [[    0.85968     0.85968     0.85968     0.85968     0.85968     0.85968     0.85968     0.85968     0.85968     0.85968]]
ap: [[    0.76316       0.717     0.66569      0.6059     0.52429     0.42925     0.31236     0.19329     0.07503    0.005899]]
f1: [[    0.54216     0.54216     0.54216     0.54216     0.54216     0.54216     0.54216     0.54216     0.54216     0.54216]]

**Comment by glenn-jocher** [comment]
@carry-xz I'm not sure I understand the question. You can view test results by class with the `--verbose` argument:

`python test.py --verbose`
