### ISSUE TITLE
Why is my output of each class mAP0.5 instead of AP

### ISSUE THREAD

**Issue by Fan-SR** [ultralytics/yolov5#3105]
## Additional context
![1Z01X~IAHI_J6$TRZ(J)VGG](https://user-images.githubusercontent.com/52476022/117688934-d9890a80-b1eb-11eb-9acd-5422e98870d0.png)
The yellow area in the figure corresponds to each type of AP, right? A total of six categories, why each category of test results will have map0.5

**Comment by glenn-jocher** [comment]
@Fan-SR metrics are displayed per class. The metrics are also averaged over the classes in the first row labelled 'all'.
