### ISSUE TITLE
custom model working only colab

### ISSUE THREAD

**Issue by sctnightcore** [ultralytics/yolov5#3106]
## ❔Question
My model was train via google colab.  when I took it to test it on my machine and it didn't work.
## Additional context
colab
![image](https://user-images.githubusercontent.com/23263315/117733593-0523e900-b21c-11eb-81c5-664bb9e5ef59.png)

my pc
![image](https://user-images.githubusercontent.com/23263315/117733613-110fab00-b21c-11eb-8d9c-7dfc574805c4.png)

**Comment by glenn-jocher** [comment]
@sctnightcore yes I see. Sometimes windows PCs and/or anaconda environments produce incorrect or missing detections, though we have not been able to isolate the cause other than general environmental differences. If possible I would try to train and evaluate on one of our verified environments below. If you prefer to run locally with windows the best results will probably come from using our Docker image!


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by sctnightcore** [comment]
@glenn-jocher  update pytorch to 1.8.1. it working xD

**Comment by glenn-jocher** [comment]
@sctnightcore awesome!! I wonder if we should bump the requirements.txt up to 1.8.1 ...
