### ISSUE TITLE
How to restore the epoch given that internet goes off time to time 

### ISSUE THREAD

**Issue by pd2871** [ultralytics/yolov5#3111]
## ❔Question
I have been training yolov5m model on 300 epochs, but during 107 epoch, my internet went off, so how to restore the trained model so that it can start from 107 epoch?  Is there any way?

## Additional context
I have used `--resume` but it raised `no checkpoints found error`. After checking the `weights` folder, there was no any checkpoint.

**Comment by glenn-jocher** [comment]
@PDahal2871 if your training was **interrupted** for any reason you may continue where you left off using the `--resume` argument. If your training fully completed, you can start a **new** training from any model using the `--weights` argument. Examples:

## Resume Single-GPU

You may not change settings when resuming, and **no additional arguments** other than `--resume` should be passed, with an optional path to the checkpoint you'd like to resume from. If no checkpoint is passed the most recently updated `last.pt` in your `yolov5/` directory is automatically found and used:
```bash
python train.py --resume  # automatically find latest checkpoint (searches yolov5/ directory)
python train.py --resume path/to/last.pt  # specify resume checkpoint
```

## Resume Multi-GPU

[Multi-GPU DDP trainings](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) must be resumed with the same GPUs and DDP command, i.e. assuming 8 GPUs:
```bash
python -m torch.distributed.launch --nproc_per_node 8 train.py --resume  # resume latest checkpoint
python -m torch.distributed.launch --nproc_per_node 8 train.py --resume path/to/last.pt  # specify resume checkpoint
```

## Start from Pretrained

If you would like to **start training** from a fully trained model, use the `--weights` argument, not the `--resume` argument:
```bash
python train.py --weights path/to/best.pt  # start from pretrained model
```

Good luck and let us know if you have any other questions!

**Comment by pd2871** [comment]
I have mistakenly used `--nosave --cache` arguments while training the yolov5 which was the main reason for the weights not being saved on every epoch. Thanks for the convenience.

**Comment by glenn-jocher** [comment]
@PDahal2871 sure. --cache is useful for caching smaller datasets into memory for faster training, and is unrelated to checkpoint saving.
