### ISSUE TITLE
Change label border thickness and size font

### ISSUE THREAD

**Issue by nimashee** [ultralytics/yolov5#3113]
I want to change the label border thickness and the font size because it's confusing when I see the object that didn't detect. How to change this?
![image](https://user-images.githubusercontent.com/81754659/117782782-27ddee00-b26c-11eb-9fa7-f991e42eead1.png)

**Comment by debparth** [comment]
@nimashee you can use `--line-thickness` argument in detect.py file

**Comment by glenn-jocher** [comment]
@nimashee @debparth you can also use the `--hide-labels` or `--hide-conf` flags to avoid displaying these. See detect.py argparser for details:
https://github.com/ultralytics/yolov5/blob/abfcf9eb79877971acd238cafe6149711c5056ad/detect.py#L169-L171

**Comment by nimashee** [comment]
@debparth @glenn-jocher thank you!
