### ISSUE TITLE
Is there anybody whose log cannot print progress?

### ISSUE THREAD

**Issue by AnimationFan** [ultralytics/yolov5#3118]
## ❔Question
I run yolov5 and find the log doesn't print normally.

In the log, no progress bar is print, and the test result is empty at the same time

## Additional context
![image](https://user-images.githubusercontent.com/42439474/117903162-a46edc00-b301-11eb-947c-f198027be6ca.png)
i used nohup command to run training and the output is shown like this

something strange happend later.

when i try to resume the training from suddenly power cut. I find something wrong with wandb ( the log show the program cannot cnonnect to the network) so i had to modify some code with wandb.

And the most strange thing happend, the tqdm can print the progress bar nomally !!!!!!!!!

**Comment by glenn-jocher** [comment]
@AnimationFan hi, thanks for the bug report. Can you provide screenshots and code/environment to reproduce please? Thanks!
