### ISSUE TITLE
onnxruntime inference results have some positions differences  compared with pth inference results

### ISSUE THREAD

**Issue by zhedahe** [ultralytics/yolov5#3119]
## ❔Question
hi, everyone:

what I have done:
1)  use models/exports.py to export **pth to onnx model successfuly(size: 640*640)**.
2)  then refer code in detect.py to do **pth model inference successfuly and get right detections results**(resized image and original image detections coords are both ok).
3)  resize image (640*640) as **input**, I found detections results are right too by **onnxruntime inference**.

problem I met:
1) I continue to  **scale coords** in resized img back to coords in original full-scale image, found classes of detections are right, but **coords of all detections all have some deviations compared with pth inference**. i.e zidane.jpg in attachment as fellows, other test imgs have same problems:

wish somebody can do me a favor, thank you very much!

## Additional context
my code by using onnxruntime as follows:
  
    source = 'data/images' # images dir
    weights = 'yolov5s.pt'
    imgsz = 640
    onnx_model = onnx.load('yolov5s.onnx')
    try:
        onnx.checker.check_model(onnx_model)
    except (Exception, err):
        print('model error:', err)
    else:
        print('model is ok!')
    finally:
        print('modle chekc is over!')

    session_options = onnxruntime.SessionOptions()
    session_options.enable_profiling = True
    session = onnxruntime.InferenceSession("yolov5s.onnx")
    batch_size = session.get_inputs()[0].shape[0]
    img_size_h = session.get_inputs()[0].shape[2]
    img_size_w = session.get_inputs()[0].shape[3]
    print ('batch_size: {}, h:{}, w:{}'.format(batch_size, img_size_h ,img_size_w))

    for image_name in os.listdir(source):
        image_path = os.path.join(source, image_name)
        cv2_img = cv2.imread(image_path)
        
        """
        problem one:
        follow pth's operation: using padding image as line.61 code
        if comment this line.123 code, right persion in zidane.jpg  will miss a tie detection 
        """
        cv2_img = letterbox(cv2_img, imgsz, stride)[0] 

        cv2_img = cv2.cvtColor(cv2_img, cv2.COLOR_BGR2RGB)
        cv2_img = np.ascontiguousarray(cv2_img)
        image_src = Image.fromarray(cv2_img)
        print('Loaded Image Info : ',image_src.format, image_src.size, image_src.mode)

        resized =  image_src.resize((img_size_w, img_size_h))
        print('After resizing :' ,resized.size, resized.mode)

        img_in = np.transpose(resized, (2, 0, 1)).astype(np.float32) # HWC -> CHW
        img_in = np.expand_dims(img_in, axis=0)
        img_in /= 255.0
        print('Batch-Size, Channel, Height, Width : ',img_in.shape)

        input_name = session.get_inputs()[0].name
        t1 = time_synchronized()
        outputs = session.run(None, {input_name: img_in})

        print('Concatenated outputs shape: ', outputs[0].shape)
        print('Separated outputs shape: ', outputs[1].shape, outputs[2].shape, outputs[3].shape)

        filterd_predictions = non_max_suppression(torch.tensor(outputs[0]), conf_thres = 0.25, iou_thres = 0.45)
        t2 = time_synchronized()
        print ('------------------inference time: {} ms----------------------'.format(1000*(t2-t1)))

        # draw detection results in resize image, **result here is right**
        img = cv2.resize(cv2.imread(image_path), (img_size_w, img_size_h), interpolation=cv2.INTER_LINEAR)
        for pred in filterd_predictions[0]:
            pred = pred.detach().cpu().numpy()
            x1 = int(pred[0])
            y1 = int(pred[1])
            x2 = int(pred[2])
            y2 = int(pred[3])
            img = cv2.rectangle(img, (x1,y1),(x2,y2), thickness = 2, color=(0,255,0))
            # print('Confidence: ', pred[4], 'Class:', int(pred[5]))
        img_name = image_path.split('/')[-1]
        img_name = img_name.replace('.jpg', '_resize.jpg')
        cv2.imwrite('runs/ox_imgs/{}'.format(img_name), img)

        # draw detection results in original image
        """
        after scaling coords from resize img to original img, I found positions of all detetion targets are not accurate, so code as follows may have some problem
        """
        xyxy = []
        for i, det in enumerate(filterd_predictions):
            im0 = cv2.imread(image_path)
            det[:, :4] = scale_coords([img_size_h, img_size_w], det[:, :4], im0.shape).round()

            for *xyxy, conf, cls in reversed(det):
                c = int(cls)  # integer class
                label = '{} {}'.format(names[c], conf)
                img_name = image_path.split('/')[-1]
                plot_one_box(xyxy, im0, label=label, color=colors(c, True), line_thickness=3)
        cv2.imwrite('runs/ox_imgs/{}'.format(img_name), im0)

onnx result in **resized image**
![zidane_resize](https://user-images.githubusercontent.com/4446863/117813859-2cb79780-b296-11eb-9f46-769a500667eb.jpg)

onnx result in **original image**                                                                        
![zidane_onnx](https://user-images.githubusercontent.com/4446863/117813614-e104ee00-b295-11eb-8b9a-9ed65f13a112.jpg)
                  
pth result in **original image**                                                    
![zidane_pth](https://user-images.githubusercontent.com/4446863/117813619-e2ceb180-b295-11eb-8935-418c1256b81c.jpg)

**Comment by zhedahe** [comment]
@jakepoz @olehb , can you please give me some advice? thank you

**Comment by ketan-b** [comment]
Hi, there is a simple fix for this issue!

Use this in your code instead:

`cv2_img = letterbox(cv2_img, imgsz, stride, auto=False, scaleFill=False, scaleup=True)[0]`

This will add padding to your image and the resizing issue will be taken care of!
Share the updated code, are you working on running YOLOv5 in the browser using `ONNX.js`?

Original image:
![image](https://user-images.githubusercontent.com/54092325/119625039-6906fe00-be27-11eb-8c0d-e99f0cb025cb.png)

Padded image:
![image](https://user-images.githubusercontent.com/54092325/119625216-95bb1580-be27-11eb-96f7-b2e6cb75b7ae.png)

Predictions:
![image](https://user-images.githubusercontent.com/54092325/119625261-a1a6d780-be27-11eb-8cf4-f6f4d8691ab0.png)

**Comment by zhedahe** [comment]
> 
> 
> Hi, there is a simple fix for this issue!
> 
> Use this in your code instead:
> 
> `cv2_img = letterbox(cv2_img, imgsz, stride, auto=False, scaleFill=False, scaleup=True)[0]`
> 
> This will add padding to your image and the resizing issue will be taken care of!
> Share the updated code, are you working on running YOLOv5 in the browser using `ONNX.js`?
> 
> Original image:
> ![image](https://user-images.githubusercontent.com/54092325/119625039-6906fe00-be27-11eb-8c0d-e99f0cb025cb.png)
> 
> Padded image:
> ![image](https://user-images.githubusercontent.com/54092325/119625216-95bb1580-be27-11eb-96f7-b2e6cb75b7ae.png)
> 
> Predictions:
> ![image](https://user-images.githubusercontent.com/54092325/119625261-a1a6d780-be27-11eb-8cf4-f6f4d8691ab0.png)

thank you, but  I use the method you methioned  above, I use: **cv2_img = letterbox(cv2_img, imgsz, stride)[0]** , it has same result with your advice。

**Comment by ketan-b** [comment]
Did you pass these 3 arguments `auto=False, scaleFill=False, scaleup=True` explicitly?

**Comment by ketan-b** [comment]
Because they will get padding around the image, so that the new image is 640*640 and when you now run inference on this image the boxes will be in the right place!

**Comment by zhedahe** [comment]
> 
> 
> Because they will get padding around the image, so that the new image is 640*640 and when you now run inference on this image the boxes will be in the right place!

@ketan-b  thanks for your help, I try it, but detect result after change is worse than my origin code result. could you please attach detail code for me basing the  code I attatch before? thank you very much.

**Comment by ketan-b** [comment]
```
import os
import cv2
import torch
import time
import onnx, onnxruntime
import torchvision
import numpy as np
from PIL import Image

def letterbox(img, new_shape=(640, 640), color=(114, 114, 114), auto=False, scaleFill=False, scaleup=True, stride=32):
    # Resize and pad image while meeting stride-multiple constraints
    shape = img.shape[:2]  # current shape [height, width]
    if isinstance(new_shape, int):
        new_shape = (new_shape, new_shape)
    # Scale ratio (new / old)
    r = min(new_shape[0] / shape[0], new_shape[1] / shape[1])
    if not scaleup:  # only scale down, do not scale up (for better test mAP)
        r = min(r, 1.0)
    # Compute padding
    ratio = r, r  # width, height ratios
    new_unpad = int(round(shape[1] * r)), int(round(shape[0] * r))
    dw, dh = new_shape[1] - new_unpad[0], new_shape[0] - new_unpad[1]  # wh padding
    if auto:  # minimum rectangle
        dw, dh = np.mod(dw, stride), np.mod(dh, stride)  # wh padding
    elif scaleFill:  # stretch
        dw, dh = 0.0, 0.0
        new_unpad = (new_shape[1], new_shape[0])
        ratio = new_shape[1] / shape[1], new_shape[0] / shape[0]  # width, height ratios
    dw /= 2  # divide padding into 2 sides
    dh /= 2
    if shape[::-1] != new_unpad:  # resize
        img = cv2.resize(img, new_unpad, interpolation=cv2.INTER_LINEAR)
    top, bottom = int(round(dh - 0.1)), int(round(dh + 0.1))
    left, right = int(round(dw - 0.1)), int(round(dw + 0.1))
    img = cv2.copyMakeBorder(img, top, bottom, left, right, cv2.BORDER_CONSTANT, value=color)  # add border
    return img, ratio, (dw, dh)

def time_synchronized():
    # pytorch-accurate time
    if torch.cuda.is_available():
        torch.cuda.synchronize()
    return time.time()

def non_max_suppression(prediction, conf_thres=0.25, iou_thres=0.45, classes=None, agnostic=False, multi_label=False,
                        labels=(), max_det=300):
    """Runs Non-Maximum Suppression (NMS) on inference results
    Returns:
         list of detections, on (n,6) tensor per image [xyxy, conf, cls]
    """
    nc = prediction.shape[2] - 5  # number of classes
    xc = prediction[..., 4] > conf_thres  # candidates
    # Checks
    assert 0 <= conf_thres <= 1, f'Invalid Confidence threshold {conf_thres}, valid values are between 0.0 and 1.0'
    assert 0 <= iou_thres <= 1, f'Invalid IoU {iou_thres}, valid values are between 0.0 and 1.0'
    # Settings
    min_wh, max_wh = 2, 4096  # (pixels) minimum and maximum box width and height
    max_nms = 30000  # maximum number of boxes into torchvision.ops.nms()
    time_limit = 10.0  # seconds to quit after
    redundant = True  # require redundant detections
    multi_label &= nc > 1  # multiple labels per box (adds 0.5ms/img)
    merge = False  # use merge-NMS
    t = time.time()
    output = [torch.zeros((0, 6), device=prediction.device)] * prediction.shape[0]
    for xi, x in enumerate(prediction):  # image index, image inference
        # Apply constraints
        # x[((x[..., 2:4] < min_wh) | (x[..., 2:4] > max_wh)).any(1), 4] = 0  # width-height
        x = x[xc[xi]]  # confidence
        # Cat apriori labels if autolabelling
        if labels and len(labels[xi]):
            l = labels[xi]
            v = torch.zeros((len(l), nc + 5), device=x.device)
            v[:, :4] = l[:, 1:5]  # box
            v[:, 4] = 1.0  # conf
            v[range(len(l)), l[:, 0].long() + 5] = 1.0  # cls
            x = torch.cat((x, v), 0)
        # If none remain process next image
        if not x.shape[0]:
            continue
        # Compute conf
        x[:, 5:] *= x[:, 4:5]  # conf = obj_conf * cls_conf
        # Box (center x, center y, width, height) to (x1, y1, x2, y2)
        box = xywh2xyxy(x[:, :4])
        # Detections matrix nx6 (xyxy, conf, cls)
        if multi_label:
            i, j = (x[:, 5:] > conf_thres).nonzero(as_tuple=False).T
            x = torch.cat((box[i], x[i, j + 5, None], j[:, None].float()), 1)
        else:  # best class only
            conf, j = x[:, 5:].max(1, keepdim=True)
            x = torch.cat((box, conf, j.float()), 1)[conf.view(-1) > conf_thres]
        # Filter by class
        if classes is not None:
            x = x[(x[:, 5:6] == torch.tensor(classes, device=x.device)).any(1)]
        # Apply finite constraint
        # if not torch.isfinite(x).all():
        #     x = x[torch.isfinite(x).all(1)]
        # Check shape
        n = x.shape[0]  # number of boxes
        if not n:  # no boxes
            continue
        elif n > max_nms:  # excess boxes
            x = x[x[:, 4].argsort(descending=True)[:max_nms]]  # sort by confidence
        # Batched NMS
        c = x[:, 5:6] * (0 if agnostic else max_wh)  # classes
        boxes, scores = x[:, :4] + c, x[:, 4]  # boxes (offset by class), scores
        i = torchvision.ops.nms(boxes, scores, iou_thres)  # NMS
        if i.shape[0] > max_det:  # limit detections
            i = i[:max_det]
        if merge and (1 < n < 3E3):  # Merge NMS (boxes merged using weighted mean)
            # update boxes as boxes(i,4) = weights(i,n) * boxes(n,4)
            iou = box_iou(boxes[i], boxes) > iou_thres  # iou matrix
            weights = iou * scores[None]  # box weights
            x[i, :4] = torch.mm(weights, x[:, :4]).float() / weights.sum(1, keepdim=True)  # merged boxes
            if redundant:
                i = i[iou.sum(1) > 1]  # require redundancy
        output[xi] = x[i]
        if (time.time() - t) > time_limit:
            print(f'WARNING: NMS time limit {time_limit}s exceeded')
            break  # time limit exceeded
    return output

def xywh2xyxy(x):
    # Convert nx4 boxes from [x, y, w, h] to [x1, y1, x2, y2] where xy1=top-left, xy2=bottom-right
    y = x.clone() if isinstance(x, torch.Tensor) else np.copy(x)
    y[:, 0] = x[:, 0] - x[:, 2] / 2  # top left x
    y[:, 1] = x[:, 1] - x[:, 3] / 2  # top left y
    y[:, 2] = x[:, 0] + x[:, 2] / 2  # bottom right x
    y[:, 3] = x[:, 1] + x[:, 3] / 2  # bottom right y
    return y

def scale_coords(img1_shape, coords, img0_shape, ratio_pad=None):
    # Rescale coords (xyxy) from img1_shape to img0_shape
    if ratio_pad is None:  # calculate from img0_shape
        gain = min(img1_shape[0] / img0_shape[0], img1_shape[1] / img0_shape[1])  # gain  = old / new
        pad = (img1_shape[1] - img0_shape[1] * gain) / 2, (img1_shape[0] - img0_shape[0] * gain) / 2  # wh padding
    else:
        gain = ratio_pad[0][0]
        pad = ratio_pad[1]
    coords[:, [0, 2]] -= pad[0]  # x padding
    coords[:, [1, 3]] -= pad[1]  # y padding
    coords[:, :4] /= gain
    clip_coords(coords, img0_shape)
    return coords

def clip_coords(boxes, img_shape):
    # Clip bounding xyxy bounding boxes to image shape (height, width)
    boxes[:, 0].clamp_(0, img_shape[1])  # x1
    boxes[:, 1].clamp_(0, img_shape[0])  # y1
    boxes[:, 2].clamp_(0, img_shape[1])  # x2
    boxes[:, 3].clamp_(0, img_shape[0])  # y2

def plot_one_box(x, im, color=(128, 128, 128), label=None, line_thickness=3):
    # Plots one bounding box on image 'im' using OpenCV
    assert im.data.contiguous, 'Image not contiguous. Apply np.ascontiguousarray(im) to plot_on_box() input image.'
    tl = line_thickness or round(0.002 * (im.shape[0] + im.shape[1]) / 2) + 1  # line/font thickness
    c1, c2 = (int(x[0]), int(x[1])), (int(x[2]), int(x[3]))
    cv2.rectangle(im, c1, c2, color, thickness=tl, lineType=cv2.LINE_AA)
    if label:
        tf = max(tl - 1, 1)  # font thickness
        t_size = cv2.getTextSize(label, 0, fontScale=tl / 3, thickness=tf)[0]
        c2 = c1[0] + t_size[0], c1[1] - t_size[1] - 3
        cv2.rectangle(im, c1, c2, color, -1, cv2.LINE_AA)  # filled
        cv2.putText(im, label, (c1[0], c1[1] - 2), 0, tl / 3, [225, 255, 255], thickness=tf, lineType=cv2.LINE_AA)

def add_margin(pil_img, left, right, top, bottom):
    width, height = pil_img.size
    new_width = right + width
    new_height = bottom + height
    result = Image.new(pil_img.mode, (new_width, new_height), '#ffffff')
    result.paste(pil_img, (0, 0))
    return result

source = '/content/test_image' # images dir
weights = '/content/yolov5/yolov5s.pt'
imgsz = 640
stride = 32

onnx_model = onnx.load('/content/yolov5/yolov5s.onnx')

try:
    onnx.checker.check_model(onnx_model)
except (Exception, err):
    print('model error:', err)
else:
    print('model is ok!')
finally:
    print('modle chekc is over!')

session_options = onnxruntime.SessionOptions()
session_options.enable_profiling = True
session = onnxruntime.InferenceSession("/content/yolov5/yolov5s.onnx")
batch_size = session.get_inputs()[0].shape[0]
img_size_h = session.get_inputs()[0].shape[2]
img_size_w = session.get_inputs()[0].shape[3]
print ('batch_size: {}, h:{}, w:{}'.format(batch_size, img_size_h ,img_size_w))

for image_name in os.listdir(source):
    image_path = os.path.join(source, image_name)
    cv2_img = cv2.imread(image_path)
    """
    problem one:
    follow pth's operation: using padding image as line.61 code
    if comment this line.123 code, right persion in zidane.jpg  will miss a tie detection 
    """
    cv2_img = letterbox(cv2_img, imgsz, stride)[0] 
    cv2_img = cv2.cvtColor(cv2_img, cv2.COLOR_BGR2RGB)
    cv2_img = np.ascontiguousarray(cv2_img)
    image_src = Image.fromarray(cv2_img)
    print('Loaded Image Info : ',image_src.format, image_src.size, image_src.mode)
    resized =  image_src.resize((img_size_w, img_size_h))
    # resized =  add_margin(image_src, )
    print('After resizing :' ,resized.size, resized.mode)
    img_in = np.transpose(resized, (2, 0, 1)).astype(np.float32) # HWC -> CHW
    img_in = np.expand_dims(img_in, axis=0)
    img_in /= 255.0
    print('Batch-Size, Channel, Height, Width : ',img_in.shape)
    input_name = session.get_inputs()[0].name
    t1 = time_synchronized()
    outputs = session.run(None, {input_name: img_in})
    print('Concatenated outputs shape: ', outputs[0].shape)
    print('Separated outputs shape: ', outputs[1].shape, outputs[2].shape, outputs[3].shape)
    filterd_predictions = non_max_suppression(torch.tensor(outputs[0]), conf_thres = 0.25, iou_thres = 0.45)
    t2 = time_synchronized()
    print ('------------------inference time: {} ms----------------------'.format(1000*(t2-t1)))
    # draw detection results in resize image, **result here is right**
    img = cv2.resize(cv2.imread(image_path), (img_size_w, img_size_h), interpolation=cv2.INTER_LINEAR)
    for pred in filterd_predictions[0]:
        pred = pred.detach().cpu().numpy()
        x1 = int(pred[0])
        y1 = int(pred[1])
        x2 = int(pred[2])
        y2 = int(pred[3])
        img = cv2.rectangle(img, (x1,y1),(x2,y2), thickness = 2, color=(0,255,0))
        # print('Confidence: ', pred[4], 'Class:', int(pred[5]))
    img_name = image_path.split('/')[-1]
    img_name = img_name.replace('.jpg', '_resize.jpg')
    # cv2.imwrite('/content/runs/{}'.format(img_name), img)
    # draw detection results in original image

    xyxy = []
    for i, det in enumerate(filterd_predictions):
        im0 = cv2.imread(image_path)
        det[:, :4] = scale_coords([img_size_h, img_size_w], det[:, :4], im0.shape).round()
        for *xyxy, conf, cls in reversed(det):
            c = int(cls)  # integer class
            # label = '{} {}'.format(names[c], conf)
            img_name = image_path.split('/')[-1]
            plot_one_box(xyxy, im0, color=[0,0,255], line_thickness=3)
    cv2.imwrite('/content/runs/{}'.format(img_name), im0)
```

**Comment by ketan-b** [comment]
This script should run on its own, I have copied the necessary code from yolov5 repo as well!

**Comment by zhedahe** [comment]
> This script should run on its own, I have copied the necessary code from yolov5 repo as well!

thank you for your sharing, thanks. At first, what I want to say is onnxruntime inference result is not exact accurate(final detect anchors had some bias in zidane.jpg), my original detect results are nearly right in general, your code is exactly same with me(I had used the letterbox function when I try to find help here at beginning, 3 params you refer above I use default values ), in fact, I want to find the reason of deviation.

**Comment by ketan-b** [comment]
Yes, the onnxruntime inference is not accurate in many cases!
I tried loading it with ONNX.Js and got multiple errors myself.
