### ISSUE TITLE
Frozen layers work no as they will

### ISSUE THREAD

**Issue by GiorgioSgl** [ultralytics/yolov5#3123]
## ❔Question
Hi, 

What I've tried is retrain yolov5 with the backbone layers frozen.
I use as pretrained weigths the ones generated by this lines of code from the pythorch hub.
```
import torch
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', classes=26)
```

As dataset I used a subset of the COCO dataset (instead of 80 classes, I took only 26 classes). The problem is that with frozen layers I got very bad results while with no frozen layer I got the results expected.

Here some images about the training

![training](https://user-images.githubusercontent.com/29785307/117859694-a1d39e80-b28f-11eb-8c81-339bb4c7bcbd.png)

## Additional context
I was wondering if the pretrained weigths aren't pretrained on the coco dataset, maybe that's the reason.

**Comment by glenn-jocher** [comment]
@GiorgioSgl all official YOLOv5 models are trained from scratch on the COCO dataset. See **Transfer Learning with Frozen Layers** tutorial for example usage and results of freezing layers. 

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [ONNX and TorchScript Export](https://docs.ultralytics.com/yolov5/tutorials/model_export)
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)
