### ISSUE TITLE
yolov5x.pt RuntimeError

### ISSUE THREAD

**Issue by UUUserna** [ultralytics/yolov5#3124]
## ❔Question
When I using yolov5x.pt to train my data, pc arised below error:
RuntimeError: CUDA out of memory. Tried to allocate 1.26 GiB (GPU 0; 8.00 GiB total capacity; 900.68 MiB already allocated; 4.86 GiB free; 976.00 MiB reserved in total by PyTorch)

## Additional context
My image num is 200, the result is not good when I used yolov5s.pt to training

**Comment by wudashuo** [comment]
As it said: `CUDA out of memory`, use smaller batch size, use yolov5s, m, l instead of x.
You only have 200 images, the result won't be good no matter which model you use, increase the num at least 5 times more.

**Comment by UUUserna** [comment]
> As it said: `CUDA out of memory`, use smaller batch size, use yolov5s, m, l instead of x.
> You only have 200 images, the result won't be good no matter which model you use, increase the num at least 5 times more.

thanks, but why my pc shut down when I training, my memory still enough.
my graghics card is GTX3080Ti

**Comment by glenn-jocher** [comment]
@UUUserna your CUDA device/GPU is out of memory. Use smaller batch sizes, smaller image sizes, a smaller model, or a larger GPU.
