### ISSUE TITLE
add __init__.py 

### ISSUE THREAD

**Issue by KC-Zhang** [ultralytics/yolov5#3126]
## 🚀 Feature

add an empty \_\_init\_\_.py in the base folder.

## Motivation
This way, the yolov5 folder can be installed as a package within our own projects as a git-submodule, and install everything using a setup.py.  Since it is not clean to modify contents of a submodule (including adding \_\_init\_\_.py), it's better if the repo already has \_\_init\_\_.py.

**Comment by fcakyon** [comment]
@KC-Zhang You can utilize [torch hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) or use [this pypi package](https://github.com/fcakyon/yolov5-pip) for this purpose.

**Comment by KC-Zhang** [comment]
@fcakyon torch hub or PyPI is less flexible.  I need to rewrite detection.py to take custom input/output flow from my own project, which depends on utils and models, which is only importable with __init__.py.

**Comment by fcakyon** [comment]
@KC-Zhang You can simply `pip install yolov5` and prepare a single detect.py file that uses imports from `yolov5`. I'm using it this way in my projects.

**Comment by KC-Zhang** [comment]
@fcakyon That could work, let me try that. Is the pip package as good as the github in terms of performance?

**Comment by fcakyon** [comment]
@KC-Zhang  it is exact copy of this repo, only difference is its pip installable. You can check the source code [here](https://github.com/fcakyon/yolov5-pip).

**Comment by glenn-jocher** [comment]
@KC-Zhang good news 😃! Your original issue may now been fixed ✅ in PR #3127.  To receive this update you can:
- `git pull` from within your `yolov5/` directory
- `git clone https://github.com/ultralytics/yolov5` again
- Force-reload [PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/): `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- View our updated notebooks:  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by KC-Zhang** [comment]
Heyy Glenn,
I tried using the pip package. But I got error during pip install. It basically says fail to install cocotool. Is there a way to do pip install without cocotool?
    ```pycocotools/_mask.c:6:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1```

**Comment by glenn-jocher** [comment]
@KC-Zhang if you're trying to package-ize this repo, you can simply comment it from requirements.txt. If you're talking about the PyPi package then no I think it's baked in as a requirement.

What happens if you just run `pip install pycocotools`?

**Comment by fcakyon** [comment]
@KC-Zhang here are the solutions for your problem: https://github.com/cocodataset/cocoapi/issues/172. It is related with pycocotools package.

**Comment by glenn-jocher** [comment]
@fcakyon ah good catch. Perhaps we should add Cython to the requirements.txt here ahead of pycocotools.

**Comment by glenn-jocher** [comment]
@KC-Zhang @fcakyon see #3217

**Comment by KC-Zhang** [comment]
Thanks @glenn-jocher @fcakyon for looking into this. 

Unfortunately I tried installing cpython and it didn't solve the problem. I am running a python3.8 venv on Ubuntu 16.04. 

I tried all combination of pip install Cpython; pip2 install Cpython; pip3 install Cpython; pip install cpython; pip2 install cpython; pip3 install cpython;

**Comment by KC-Zhang** [comment]
I think I might have solved the problem a while ago on my local computer by messing with gcc following search result for " error: command 'x86_64-linux-gnu-gcc' failed with exit status 1" on google like [this](https://stackoverflow.com/questions/26053982/setup-script-exited-with-error-command-x86-64-linux-gnu-gcc-failed-with-exit) one. But I threw in a lot of command into terminal and not sure what was the exact command that helped.

**Comment by fcakyon** [comment]
@KC-Zhang most probably you fixed it by : `apt-get install build-essential libffi-dev`

**Comment by KC-Zhang** [comment]
@fcakyon thank you for pointing it out. I will confirm it in a new virtual machine when I got some time and confirm it here if it fixes the problem.

**Comment by glenn-jocher** [comment]
@KC-Zhang I think you might have a misspelling in your command, the package that `pycocotools` needs in `Cython`, not 'cpython'. Use this command:
```
pip install Cython pycocotools
```

**Comment by KC-Zhang** [comment]
@glenn-jocher Thank you for pointing it out. I did make a typo and didn't notice haha. I tried the correct spelling this time and it still didn't work unfortunately. What I tried:
```pip install Cython pycocotools```
```pip2 install Cython && pip install pycocotools```
```pip3 install Cython && pip install pycocotools```
```pip2 install cython && pip install pycocotools```
```pip3 install cython && pip install pycocotools```
