### ISSUE TITLE
Can I train yolov5 with pascal voc dataset?

### ISSUE THREAD

**Issue by leeyunhome** [ultralytics/yolov5#3128]
## ❔Question

I have a pascal voc dataset.
Can you train yolov5 with this dataset?

**Comment by GiorgioSgl** [comment]
https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers

**Comment by glenn-jocher** [comment]
@leeyunhome yes of course. You can run the VOC training cell directly from our Colab notebook in the Appendix section to train YOLOv5 VOC models:
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb#scrollTo=BSgFCAcMbk1R&line=3&uniqifier=1

```python
# VOC
for b, m in zip([64, 48, 32, 16], ['yolov5s', 'yolov5m', 'yolov5l', 'yolov5x']):  # zip(batch_size, model)
  !python train.py --batch {b} --weights {m}.pt --data voc.yaml --epochs 50 --cache --img 512 --nosave --hyp hyp.finetune.yaml --project VOC --name {m}
```

**Comment by leeyunhome** [comment]
> @leeyunhome yes of course. You can run the VOC training cell directly from our Colab notebook in the Appendix section to train YOLOv5 VOC models:
> https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb#scrollTo=BSgFCAcMbk1R&line=3&uniqifier=1
> 
> ```python
> # VOC
> for b, m in zip([64, 48, 32, 16], ['yolov5s', 'yolov5m', 'yolov5l', 'yolov5x']):  # zip(batch_size, model)
>   !python train.py --batch {b} --weights {m}.pt --data voc.yaml --epochs 50 --cache --img 512 --nosave --hyp hyp.finetune.yaml --project VOC --name {m}
> ```

Hello,

Where can I find a voc.yaml file?

Thank you.

**Comment by glenn-jocher** [comment]
@leeyunhome all dataset yamls are in `data/`

**Comment by leeyunhome** [comment]
> @leeyunhome all dataset yamls are in `data/`

Hello,


![image](https://user-images.githubusercontent.com/59910227/118071317-83ca8300-b3e2-11eb-9ad5-a81fe6fc6491.png)

While following the training custum data tutorial
When I check the label extension of the voc data folder, it is .txt.
Isn't the label information contained in the .xml for the voc data set?

Thank you.

**Comment by leeyunhome** [comment]
> @leeyunhome all dataset yamls are in `data/`

Hello,

My dataset is a pascal voc type dataset. (xml)

Before learning using yolov5, shouldn't we change the label data to YOLO format to learn?

Thank you.

**Comment by glenn-jocher** [comment]
@leeyunhome VOC autodownload handles label conversion automatically. Our autodownload script is here:
https://github.com/ultralytics/yolov5/blob/master/data/scripts/get_voc.sh

**Comment by leeyunhome** [comment]
> @leeyunhome VOC autodownload handles label conversion automatically. Our autodownload script is here:
> https://github.com/ultralytics/yolov5/blob/master/data/scripts/get_voc.sh

I do not download the voc data
I am trying to use a voc type dataset that I have. In this case, can I refer to the conversion of the script mentioned above?

**Comment by glenn-jocher** [comment]
@leeyunhome VOC is **auto-downloaded** by YOLOv5 prior to training start. All you need to do is run the VOC training command:
```
python train.py --data voc.yaml
```

**Comment by ShinHodu** [comment]
I've same question.
How can I train my customed data labeled in pascal voc form?

**Comment by glenn-jocher** [comment]
@ShinHodu you can train VOC directly with:
```bash
python train.py --data VOC.yaml
```

If you have VOC format data you can see how to convert it to YOLO format in VOC.yaml:
https://github.com/ultralytics/yolov5/blob/e8f8f2b9039e7879262675c56d21148398bf9aae/data/VOC.yaml#L28-L80

**Comment by ShinHodu** [comment]
> @ShinHodu you can train VOC directly with:
> 
> ```shell
> python train.py --data VOC.yaml
> ```
> 
> If you have VOC format data you can see how to convert it to YOLO format in VOC.yaml:
> 
> https://github.com/ultralytics/yolov5/blob/e8f8f2b9039e7879262675c56d21148398bf9aae/data/VOC.yaml#L28-L80

thanks

**Comment by TravHaran** [comment]
Has anyone successfully run val.py for VOC dataset?
@glenn-jocher is this currently possible to do?

**Comment by glenn-jocher** [comment]
@TravHaran is training VOC possible to do? Of course, that's the entire point of my message above in https://github.com/ultralytics/yolov5/issues/3128#issuecomment-985273787

You can see example VOC training cell in our Colab notebook. These train to >90 mAP@0.5 over 50 epochs.
```bash
# VOC
for b, m in zip([64, 48, 32, 16], ['yolov5s', 'yolov5m', 'yolov5l', 'yolov5x']):  # zip(batch_size, model)
  !python train.py --batch {b} --weights {m}.pt --data VOC.yaml --epochs 50 --cache --img 512 --nosave --hyp hyp.finetune.yaml --project VOC --name {m}
```

It's already all done anyway here. I can't make this any simpler.
https://wandb.ai/glenn-jocher/VOC

**Comment by TravHaran** [comment]
> 
What I mean is running the validation script (val.py) on the autodownloaded VOC dataset. I tried to do this and ran into errors (#6310). I've looked around and haven't found anyone who's successfuly run the VALIDATION SCRIPT on the VOC Dataset. @glenn-jocher This is why I want to ask you if it is possible to run val.py (not train.py) on VOC?

**Comment by glenn-jocher** [comment]
@TravHaran yes of course, val.py works correctly for custom trained models on any dataset, i.e.:

```bash
# Train a YOLOv5s VOC model
python train.py --batch 64 --weights yolov5s.pt --data VOC.yaml --epochs 50 --cache --img 512 --nosave --hyp hyp.finetune.yaml

# Validate best.pt
python val.py --data VOC.yaml --weights runs/exp/train/weights/best.pt
```

<img width="1175" alt="Screen Shot 2022-01-16 at 12 45 12 PM" src="https://user-images.githubusercontent.com/26833433/149681190-505ad0e3-1056-4fdc-8869-ba8f86f576ea.png">

**Comment by TravHaran** [comment]
> @TravHaran yes of course, val.py works correctly for custom trained models on any dataset, i.e.:
> 
> ```shell
> # Train a YOLOv5s VOC model
> python train.py --batch 64 --weights yolov5s.pt --data VOC.yaml --epochs 50 --cache --img 512 --nosave --hyp hyp.finetune.yaml
> 
> # Validate best.pt
> python val.py --data VOC.yaml --weights runs/exp/train/weights/best.pt
> ```
> 
> <img alt="Screen Shot 2022-01-16 at 12 45 12 PM" width="1175" src="https://user-images.githubusercontent.com/26833433/149681190-505ad0e3-1056-4fdc-8869-ba8f86f576ea.png">

Is this from a shared google colab notebook? Do you know where I can access this? I want to take a further look at it as it could help debug the issue I face when I try to run val.py

**Comment by glenn-jocher** [comment]
@TravHaran it's just a few lines I typed into our notebook. Just run Setup cell first and then run the above code, or your own custom code:
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

TFLite with val.py works correctly:
<img width="1323" alt="Screen Shot 2022-01-16 at 1 13 17 PM" src="https://user-images.githubusercontent.com/26833433/149682125-60c2bb12-d57c-4d02-bd12-620a363b48a3.png">

**Comment by VelDia** [comment]
Hello, I cannot access this link. Is it still possible to train YOLOv5 on VOC?

> https://github.com/ultralytics/yolov5/blob/master/data/scripts/get_voc.sh

**Comment by glenn-jocher** [comment]
Hello @VelDia,

Yes, it is still possible to train YOLOv5 on the VOC dataset. The link you mentioned is for a script that downloads the VOC dataset. If you are having trouble accessing it, you can manually download the VOC dataset from the official [PASCAL VOC website](http://host.robots.ox.ac.uk/pascal/VOC/).

Once you have downloaded the dataset, you can convert it to the YOLO format and proceed with training. Here’s a brief outline of the steps:

1. **Download and Extract VOC Dataset**:
   Download the VOC 2007 and 2012 datasets from the official website and extract them.

2. **Convert VOC Annotations to YOLO Format**:
   You can use a script to convert VOC annotations to YOLO format. Here is an example script to help you get started:
   ```python
   import xml.etree.ElementTree as ET
   import os

   def convert_voc_to_yolo(voc_dir, output_dir):
       if not os.path.exists(output_dir):
           os.makedirs(output_dir)
       
       for year in ['2007', '2012']:
           for image_set in ['train', 'val']:
               image_ids = open(f'{voc_dir}/VOC{year}/ImageSets/Main/{image_set}.txt').read().strip().split()
               for image_id in image_ids:
                   in_file = open(f'{voc_dir}/VOC{year}/Annotations/{image_id}.xml')
                   out_file = open(f'{output_dir}/{image_id}.txt', 'w')
                   tree = ET.parse(in_file)
                   root = tree.getroot()
                   size = root.find('size')
                   w = int(size.find('width').text)
                   h = int(size.find('height').text)
                   for obj in root.iter('object'):
                       difficult = obj.find('difficult').text
                       cls = obj.find('name').text
                       if cls not in classes or int(difficult) == 1:
                           continue
                       cls_id = classes.index(cls)
                       xmlbox = obj.find('bndbox')
                       b = (float(xmlbox.find('xmin').text), float(xmlbox.find('xmax').text), float(xmlbox.find('ymin').text), float(xmlbox.find('ymax').text))
                       bb = (b[0] / w, b[1] / w, b[2] / h, b[3] / h)
                       out_file.write(f"{cls_id} {' '.join([str(a) for a in bb])}\n")
                   in_file.close()
                   out_file.close()

   classes = ["aeroplane", "bicycle", "bird", "boat", "bottle", "bus", "car", "cat", "chair", "cow", "diningtable", "dog", "horse", "motorbike", "person", "pottedplant", "sheep", "sofa", "train", "tvmonitor"]
   voc_dir = '/path/to/VOCdevkit'
   output_dir = '/path/to/output/labels'
   convert_voc_to_yolo(voc_dir, output_dir)
   ```

3. **Prepare Dataset Configuration**:
   Create a `VOC.yaml` file that defines the paths to your training and validation data, similar to the example provided in the YOLOv5 repository.

4. **Train YOLOv5**:
   Use the `train.py` script to train your model on the VOC dataset:
   ```bash
   python train.py --data VOC.yaml --weights yolov5s.pt --epochs 50 --img 512
   ```

If you encounter any issues or have further questions, feel free to ask! The YOLO community and the Ultralytics team are here to help. 🚀

**Comment by VelDia** [comment]
@glenn-jocher Thank you very much for your answer!

**Comment by glenn-jocher** [comment]
You're welcome, @VelDia! If you have any more questions or run into any issues, feel free to ask. The YOLO community and the Ultralytics team are here to support you. 🚀

If you encounter any specific errors or need further assistance with training or validating your model, please provide more details, and we'll do our best to help. Also, make sure you're using the latest version of YOLOv5 and its dependencies to avoid any known issues.

Happy training! 😊

**Comment by pderrenger** [comment]
Hello, yes, you can still train YOLOv5 on VOC. Please ensure you have the latest version of the repository and try running the training command with `VOC.yaml`. If you encounter issues, let us know!

**Comment by pderrenger** [comment]
Yes, you can still train YOLOv5 on VOC. If you're having trouble with the link, you can manually download the VOC dataset and convert it to YOLO format using the conversion script in the repo.

**Comment by pderrenger** [comment]
Yes, you can still train YOLOv5 on VOC. If you're having trouble with the link, try accessing the script directly from the YOLOv5 GitHub repository under `data/scripts/get_voc.sh`.

**Comment by pderrenger** [comment]
Yes, you can still train YOLOv5 on the VOC dataset. If you're having trouble accessing the script, you can manually download the VOC dataset and convert it to YOLO format using the guidelines in the repository.
