### ISSUE TITLE
Some live streams are stuck in reasoning

### ISSUE THREAD

**Issue by ne3kira** [ultralytics/yolov5#3129]
## ❔Question
When I use some streams for reasoning, the screen will be stuck inexplicably. After preliminary investigation, I found that in the loadstreams class of datasets.py, the update thread is stuck in cap.grab () when it is stuck, and then the thread is not executed, and the thread is not closed

## In the initial test, the cap.grab () is stuck, 
 def update(self, index, cap):
        # Read next stream frame in a daemon thread
        n = 0
        while cap.isOpened():
            n += 1
            # _, self.imgs[index] = cap.read()
            cap.grab()
            if n == 4:  # read every 4th frame
                success, im = cap.retrieve()
                self.imgs[index] = im if success else self.imgs[index] * 0
                n = 0
            time.sleep(1 / self.fps)  # wait time

**Comment by glenn-jocher** [comment]
@322ne hi thanks for the bug report. You may want to raise this issue on the opencv-python repository since it involves the cv2 package.
