### ISSUE TITLE
My code cannot work

### ISSUE THREAD

**Issue by maxuetao** [ultralytics/yolov5#3132]
## ❔Question
When I execute the following command：
amaxv1004@ub-amaxv1004:~/DATA20T/data20t/sakuram/projects/yolov5$ CUDA_VISIBLE_DEVICES=2 python train.py --weights ./weights/yolov5x.pt  --data ./HB_early/coco.yaml --device 2 --epochs 500 --multi-scale --adam

There is no error, but there is no output.Then I found the problem：
When the code is executed to (utils/general.py     from utils.metrics import fitness ), the code will stop working without any output

How to solve this problem？
## Additional context
This problem appeared on my linux server,
When I execute the same command on my windows computer, I can train normally

**Comment by glenn-jocher** [comment]
@SakuraMaxuetao thanks for asking a question! If you believe you have a reproducible issue, we suggest you close this issue and raise a new one using the 🐛 **Bug Report template**, providing screenshots and a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. Thank you!
