### ISSUE TITLE
Wrong annotations?

### ISSUE THREAD

**Issue by LazyKai** [ultralytics/yolov5#3136]
https://github.com/ultralytics/yolov5/blob/abfcf9eb79877971acd238cafe6149711c5056ad/utils/metrics.py#L150
https://github.com/ultralytics/yolov5/blob/abfcf9eb79877971acd238cafe6149711c5056ad/utils/metrics.py#L155

Does the annotation for each of these two lines misplaced?

**Comment by glenn-jocher** [comment]
@LazyKai I think these correspond with the xytick and ytick names here:
https://github.com/ultralytics/yolov5/blob/abfcf9eb79877971acd238cafe6149711c5056ad/utils/metrics.py#L170-L172
