### ISSUE TITLE
Why high resolution images takes longer to run in the detection? And a Question Regarding Tensorboard.

### ISSUE THREAD

**Issue by YuriRibeiro** [ultralytics/yolov5#3146]
Hi,

I would like to know why detections take longer to run when using higher resolution images.

Suppose that when passing a 640x640 pixel image over the network, X seconds are spent. Then, when passing a 1200x1200 image, 2 * X seconds are spent.

Can I say that this increase in time spent is due to the fact that the YOLO network is completely convolutional and, therefore, there is an increase in the number of cells with predictions ~ proportional ~ to the increase in image resolution on the network output?

Another note:
The tensorboard may not be saving data correctly: the learning rate for the weights connected to the biases (lr2) starts to be saved only from the second batch onwards. That is, the initial rate (warmup_biaslr) does not appear on the tensorboard chart.

Thanks!

**Comment by glenn-jocher** [comment]
@YuriRibeiro doubling the image resolution from 640 to 1280 will create 4x the pixels and 4x the FLOPS that the model processes.

Can you show a plot of your tensorboard results with the missing epoch 0? Thanks!

**Comment by YuriRibeiro** [comment]
![Screenshot from 2021-05-13 13-56-54](https://user-images.githubusercontent.com/32506180/118160007-1de6f700-b3f4-11eb-8c15-4457f9a5fa93.png)

hyp.yaml parameters:
- lr0: 0.01
- lrf: 0.2
- warmup_epochs: 3.0
- warmup_bias_lr: 0.1

It seems to me that the graph starts recording the learning rates after the end of the first batch.

The lr2 rate graph should start at 'hyp: warmup_bias_lr' (0.1) and reach 'hyp: lr0' (0.01) at the end of the warmup epochs, right?

The same goes for the lr0 and lr1 graphs, which should start at 0 and reach 'hyp: lr0' (0.01) at the end of the warmup epochs.

The commit that i'm using is 5a40ce6.

**Comment by glenn-jocher** [comment]
@YuriRibeiro oh yes everything is working correctly. Metrics and values like LR are all logged at the **end of each epoch**, so you are seeing the LR at the end of epoch 0. The warmup LR will meet the LR scheduler at the end of epoch 2 (the 3rd datapoint).

At the very beginning there is nothing to log, i.e. no losses and no metrics like mAP.

**Comment by YuriRibeiro** [comment]
Thanks! So, the changes in the learning rate while in the warmup phase aren't on the graph? Right?

**Comment by glenn-jocher** [comment]
@YuriRibeiro yes they're displayed in logging results.

**Comment by YuriRibeiro** [comment]
Ok! Thanks!
