### ISSUE TITLE
About YOLOv5l and YOLOv5x

### ISSUE THREAD

**Issue by liushuai839** [ultralytics/yolov5#3148]
Hi, auhor: 
On my own dataset(TT100K dataset), I have succeeded training YOLOv5s model  for 260 epoch, the AP_50 is about 53%.(YOLOv3  about 73%), But when I trained the YOLOv5l model and YOLOv5x model, the AP_50 is about 1% for 100 epoch, It is a strange phenomenon. 
Can you give me some advice?

**Comment by wudashuo** [comment]
What's your training command? you must have something wrong with your training.

**Comment by glenn-jocher** [comment]
@liushuai839 If you believe you have a reproducible issue, we suggest you close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose), providing screenshots and a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. Thank you!

**Comment by glenn-jocher** [comment]
Hello, thank you for your interest in our work! We have noticed that this issue is very similar to one or more existing issues, and thus we are closing this as a duplicate issue. For help please see the following issue(s):

- https://github.com/ultralytics/yolov5/issues/3155
