### ISSUE TITLE
How to print model architecture of yolo v5

### ISSUE THREAD

**Issue by tim52602002** [ultralytics/yolov5#3150]
Hello, I want to know the model of yolo v5. When I use "print(model)" to print, some layers had been missing. It's look like this instruction print the model from definition of fuseforward instead of definition of forward. Then how to print model to get whole model architecture?

![43578](https://user-images.githubusercontent.com/56668848/118085985-d95c5b00-b3f5-11eb-855d-1d9ee3fdcfb2.PNG)
![conv](https://user-images.githubusercontent.com/56668848/118086055-f3963900-b3f5-11eb-84ba-92bf02642440.PNG)

**Comment by wudashuo** [comment]
Export model to onnx(simplified), and use netron to view it.

**Comment by tim52602002** [comment]
I can see the architecture from netron, but some layers like BatchNorm2d had been missing too. And the  target I want is to create a txt file to store the model architecture.
![netron](https://user-images.githubusercontent.com/56668848/118092853-39a3ca80-b3ff-11eb-8fc5-5557ab2cfe52.PNG)
