### ISSUE TITLE
Why does this happen when I train on Google colab？

### ISSUE THREAD

**Issue by supersarr** [ultralytics/yolov5#3151]
## Additional context
![1](https://user-images.githubusercontent.com/74942943/118095936-50e4b700-b403-11eb-98bb-b8e61b52de3c.jpg)
There are 9000 training data sets, which are the train and val of the widerperson. Why do I get stuck like this every time I train to the last epoch and then automatically end. I did not find the trained weight file under run/train/exp/weights

**Comment by glenn-jocher** [comment]
@supersarr there are no weights in your runs/train/exp/weights directory because you trained with the `--nosave` flag.

**Comment by supersarr** [comment]
@glenn-jocher my nosave is set to store_ture ,when i trained on a smaller dataset,everything in normal.Look at the picture I sent, after mAP@.5:.95, every time I train to the last epoch, I get stuck at 6%.Is it because the training data set is too big?

**Comment by glenn-jocher** [comment]
Checkpoints are saved by default every single epoch, so under default settings you will have checkpoints available during all training.

**Comment by supersarr** [comment]
@glenn-jocher  but i trained this dataset in google colab,it don't saved by default every single epoch

**Comment by glenn-jocher** [comment]
@supersarr default train settings save checkpoints every epoch regardless of your environment.

**Comment by sam99dave** [comment]
> @glenn-jocher but i trained this dataset in google colab,it don't saved by default every single epoch

There is an argument for that I think. I haven't tried but u can try it.

--save-period ( Its there in the train.py )

By default, its set to -1 so it doesn't save checkpoints imo.

**Comment by glenn-jocher** [comment]
@sam99dave yes, to save every checkpoint you can use
```
python train.py --save-period 1
```
