### ISSUE TITLE
How to Run train.py without using Terminal (i.e : Arguments)

### ISSUE THREAD

**Issue by hareskoruz** [ultralytics/yolov5#3152]

**Comment by Abandon-ht** [comment]
![-3bfd97a4ea012990.jpg](https://user-images.githubusercontent.com/64671747/118245524-85c03f00-b4d3-11eb-826d-cd674acf0c29.jpg)

**Comment by glenn-jocher** [comment]
@hareskoruz can you elaborate on your question, I don't understand.

**Comment by hareskoruz** [comment]
@glenn-jocher No probs Sir. I ve got the result
