### ISSUE TITLE
resume train

### ISSUE THREAD

**Issue by xinxin342** [ultralytics/yolov5#3153]
## ❔Question

My original plan was to train 800 epochs, but it stopped midway. When the model continued training, it showed CUDA out of memory.
![屏幕截图 2021-05-13 173025](https://user-images.githubusercontent.com/70836998/118107097-ef2b4980-b410-11eb-801d-45a6f42ec4fd.png)
 Why?

**Comment by glenn-jocher** [comment]
@xinxin342 if your training was **interrupted** for any reason you may continue where you left off using the `--resume` argument. If your training fully completed, you can start a **new** training from any model using the `--weights` argument. Examples:

## Resume Single-GPU

You may not change settings when resuming, and **no additional arguments** other than `--resume` should be passed, with an optional path to the checkpoint you'd like to resume from. If no checkpoint is passed the most recently updated `last.pt` in your `yolov5/` directory is automatically found and used:
```bash
python train.py --resume  # automatically find latest checkpoint (searches yolov5/ directory)
python train.py --resume path/to/last.pt  # specify resume checkpoint
```

## Resume Multi-GPU

[Multi-GPU DDP trainings](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) must be resumed with the same GPUs and DDP command, i.e. assuming 8 GPUs:
```bash
python -m torch.distributed.launch --nproc_per_node 8 train.py --resume  # resume latest checkpoint
python -m torch.distributed.launch --nproc_per_node 8 train.py --resume path/to/last.pt  # specify resume checkpoint
```

## Start from Pretrained

If you would like to **start training** from a fully trained model, use the `--weights` argument, not the `--resume` argument:
```bash
python train.py --weights path/to/best.pt  # start from pretrained model
```

Good luck and let us know if you have any other questions!

**Comment by xinxin342** [comment]
@glenn-jocher It can train normally in the morning, but in the afternoon it will be CUDA OOM

**Comment by glenn-jocher** [comment]
@xinxin342 if you are getting CUDA OOM then you must be very near the limit of your GPU memory. Simply reduce your batch size when you start training.
