### ISSUE TITLE
Tensorboard's SummaryWriter disabled ?

### ISSUE THREAD

**Issue by pfeatherstone** [ultralytics/yolov5#3158]
It looks like none of the loss curves or validation stats get reported to tensorboard anymore.
I don't really want to use wandb. It could be storing my data which i absolutely don't want.
Is there a way to re-enable this?

**Comment by glenn-jocher** [comment]
@pfeatherstone TensorBoard logging is working correctly. If you believe you have a reproducible issue, we suggest you close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose), providing screenshots and a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. Thank you!

**Comment by glenn-jocher** [comment]
Verified TensorBoard working correctly.
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb?hl=en

<img width="1900" alt="Screenshot 2021-05-13 at 22 12 46" src="https://user-images.githubusercontent.com/26833433/118181719-61635480-b438-11eb-91b7-05b4b78cea49.png">

**Comment by pfeatherstone** [comment]
Hmm, I was using --single-cls. I'll post the command line options I used tomorrow morning.

**Comment by pfeatherstone** [comment]
I did however get results.png working

**Comment by pfeatherstone** [comment]
Ok, I'm super confused. It turns out the "scalars" tab wasn't showing yesterday in tensorboard. I re-opened the exact same tfevents file this morning and it re-appeared with all the useful metrics. Dunno. Sorry for the issue.
