### ISSUE TITLE
The size of best.pt is the same regardless of the number of epochs and the image size specified during training.

### ISSUE THREAD

**Issue by leeyunhome** [ultralytics/yolov5#3160]
## ❔Question

The size of best.pt is the same regardless of the number of epochs and the image size specified during training.

![image](https://user-images.githubusercontent.com/59910227/118197520-170ac380-b48a-11eb-9a8c-e2819b0fbbd9.png)

I remember that it was over a few hundred megabytes in the previous version.
Is it correct that the capacity has been reduced?

**Comment by glenn-jocher** [comment]
@leeyunhome epochs and image size do not correlate with model size. All model sizes are shown in the release assets:
https://github.com/ultralytics/yolov5/releases/tag/v5.0

**Comment by leeyunhome** [comment]
> @leeyunhome epochs and image size do not correlate with model size. All model sizes are shown in the release assets:
> https://github.com/ultralytics/yolov5/releases/tag/v5.0

Hello,

![image](https://user-images.githubusercontent.com/59910227/118439427-f314df80-b720-11eb-8fc2-8807ef09a384.png)
Previously, when training, the sizes of best.pt and last.pt were more than 15 megabytes as shown in the image above.
If the image size or epoch is different, the capacity of best.pt and last.pt will be different.
The size of the converted .onnx file also changed accordingly.

In this lesson, I asked a question because it was strange that the capacity of best.pt and last.pt was constant at 15 mega even if the image size and epoch were different.

Thank you.

**Comment by leeyunhome** [comment]
> @leeyunhome epochs and image size do not correlate with model size. All model sizes are shown in the release assets:
> https://github.com/ultralytics/yolov5/releases/tag/v5.0

Hello, @glenn-jocher 

![image](https://user-images.githubusercontent.com/59910227/118444474-1ee79380-b728-11eb-8d5c-3af3f36e2f50.png)
Then, if I trained with yolov5s, you mean that the capacity of best.pt would only be about 14MB, right?
Could there be a slight error? Like 15 megabytes

Thank you.

**Comment by glenn-jocher** [comment]
@leeyunhome as I said, all models are available in the release assets section, you can see all file sizes there:
https://github.com/ultralytics/yolov5/releases
