### ISSUE TITLE
speed

### ISSUE THREAD

**Issue by milla-Lee** [ultralytics/yolov5#3161]
## ❔Question
hi,author,when i use test.py（yolov5l weights）,i find the speed of each calculation is different,Is this normal? looking forward to your reply.
e.g 
1、Speed: 14.5/1.6/16.1 ms inference/NMS/total per 640x640 image at batch-size 16
2、Speed: 14.7/1.9/16.6 ms inference/NMS/total per 640x640 image at batch-size 16
.....

**Comment by glenn-jocher** [comment]
@milla-Lee these results are essentially identical. If you're looking for a single speed to quote you can profile 3 times and choose the fastest.

**Comment by milla-Lee** [comment]
thanks!!!
