### ISSUE TITLE
Ablation experiment for SPP Layer

### ISSUE THREAD

**Issue by developer0hye** [ultralytics/yolov5#3163]
https://github.com/ultralytics/yolov5/blob/06372b1465f5a58463bf8c32bdf65fc679c17ebf/models/yolov5l.yaml#L23

@glenn-jocher 

Hi, jocher!

Have you experimented ablation experiment for SPP Layer?

If so, can you share the results about the experiment?

I have seen this method in many papers(yolov4, ppyolo, ...). Do you think that its performance is acceptable for lightweight detector in terms of trade-off between speed and performance?

**Comment by glenn-jocher** [comment]
@developer0hye well, the simplest ablation experiment is YOLOv3 vs YOLOv3-SPP, where the SPP() layer is the only change. You can see this comparison in https://github.com/ultralytics/yolov3#pretrained-checkpoints

The layer itself profiles very quickly, so it is not adding excessive time or FLOPS to the forward pass. You can profile individual YOLO layers using yolo.py with the profile sections uncommented.

**Comment by developer0hye** [comment]
@glenn-jocher 
Thanks for your reply. I have one question. How is mAP on val set exactly same with mAP on test set??
