### ISSUE TITLE
support neptune.ai logger

### ISSUE THREAD

**Issue by fcakyon** [ultralytics/yolov5#3164]
## 🚀 Feature
support for neptune.ai logging

## Motivation

We need to keep track of our trainings over neptune.ai instead of wandb.

## Pitch

There may be an optional argument in train.py for logging the results to neptune.ai

## Additional context

Refer to my pr: https://github.com/ultralytics/yolov5/pull/3114

**Comment by fcakyon** [comment]
@glenn-jocher what are your thoughts on this?

**Comment by fcakyon** [comment]
@glenn-jocher what are your thoughts on this?

**Comment by LjIA26** [comment]
I would also be interested in this addition.

**Comment by Robotatron** [comment]
I would be interested as well. 
Neptune is FREE for commercial use, one can use it at work, W&B can not.

**Comment by fcakyon** [comment]
@blaizzy what do you think about this support?

**Comment by Blaizzy** [comment]
@fcakyon I couldn't agree more!

Let me know how I can help to make it happen

**Comment by fcakyon** [comment]
@glenn-jocher @AyushExel can you lead us the way? @Blaizzy is the official contact person from Neptune.ai 👍

**Comment by AyushExel** [comment]
@fcakyon thanks.
Let's discuss this after the next release. 
cc @glenn-jocher

**Comment by Blaizzy** [comment]
Thanks for the warm intro, @fcakyon!

Nice to e-meet you @AyushExel, @glenn-jocher, @LjIA26, and @Robotatron.

I'm happy to connect and collaborate with you :)

**Comment by glenn-jocher** [comment]
@Blaizzy it's great to connect with you too! Looking forward to collaborating on this project 😊

**Comment by Blaizzy** [comment]
Hi @glenn-jocher 

I would love to but left Neptune.

How about we collaborate on a different project? What do you think?

**Comment by glenn-jocher** [comment]
@Blaizzy i appreciate your interest, but collaborating on a different project is currently not possible for me. However, I wish you the best of luck with your future endeavors!

**Comment by Blaizzy** [comment]
Thank you very much!

**Comment by Blaizzy** [comment]
However you can collaborate with friend and former colleague at Neptune @SiddhantSadangi

**Comment by glenn-jocher** [comment]
Thank you for the update, @Blaizzy. We'll keep @SiddhantSadangi in mind for collaboration on integrating neptune.ai logging into YOLOv5. Looking forward to potential future contributions! 😊
