### ISSUE TITLE
Can I use 'best.pt files' learned through yolov5 for Django?

### ISSUE THREAD

**Issue by Supreme-YS** [ultralytics/yolov5#3170]
## ❔Question
Hi, I'm Jacob from South Korea. these days, I'm studying project about image detecting. and then we gonna make a Service. so we need to use Django web framework. I mean, we have to use that. because we can only use Django web framework. It's a little weird.

anyways I just wanna know how can I use pre-trained model in Django. actually I have been trying to solve that problem. there's not enough information in Google. many people said "use flask." . before this project, I was able to make web service using flask with yolov5. as I wrote above, this project only have to use Django. I'm really sorry about that.... :-<

**So, Could you tell me how can I use ```best.pt``` files in Django?**
**how can I load best.pt model in Django?**

## Additional context
Good Luck for you.

**Comment by glenn-jocher** [comment]
@Supreme-YS we have a Flask REST API example with YOLOv5 here:
https://github.com/ultralytics/yolov5/tree/master/utils/flask_rest_api

We use the above code for the Ultralytics API Preview at https://ultralytics.com/yolov5

In terms of django solutions I don't have any experience unfortunately. If you get this working though it would be very helpful if you could submit a PR to create a django example for future users!

**Comment by Supreme-YS** [comment]
@glenn-jocher 
I appreciate it.I was expected more positive response. but It's okay. Many thanks👏🏻 okay. so I will try flask api during project term if we can use flask. and I'll try to figure out how can I adapt yolo model to Django. 

Thanks again🙌🏻

**Comment by adrianholovaty** [comment]
There's nothing specific about Django that would get in your way. It's just Python code. Put the inference code in your Django view function, and you're done!

**Comment by Supreme-YS** [comment]
@adrianholovaty Yes. It can be. We gonna try to put the inference code like that ways. Many thanks.

**Comment by Supreme-YS** [comment]
Thanks to your guys helping me, I could solve that problem. Many thanks Everyone. 

Best Regards.
