### ISSUE TITLE
Can I run inference on HTTP Stream with a password-protected system?

### ISSUE THREAD

**Issue by parth-singh71** [ultralytics/yolov5#3171]
## Additional context
I am trying to run inference on an HTTP Stream which is protected with a username and a password. Can someone tell me how can I do that?

**Comment by glenn-jocher** [comment]
@parth-singh71 sure, just Google RTSP streaming with authentication, i.e. https://www.wowza.com/community/t/rtsp-authentication/34886

**Comment by parth-singh71** [comment]
Thanks @glenn-jocher
