### ISSUE TITLE
Convert three yolo grids to detection bounding box

### ISSUE THREAD

**Issue by kail85** [ultralytics/yolov5#3172]
## ❔Question
After training on coco data, I exported the model as an onnx file via

```python
python models/export.py --weights yolov5m.pt --img 640 --batch 1 --grid
```
then I got an onnx file yolov5m.onnx which includes the Detect() layer. However opencv's dnn doesn't support slice operation, I would if there's any workaround? 

## Additional context

**Comment by glenn-jocher** [comment]
@kail85 you may want to explore some of the export options to see if there's one that suits your requirements better:
https://github.com/ultralytics/yolov5/blob/17b0f71538d3e9990e0e6c4b5c7c48375956efa3/models/export.py#L26-L37

**Comment by leenamx** [comment]
Hi!
I also meet the similar problem. I export the onnx model from yolov5 but the output of onnx is 3d list: [1x3x80x80x7];[1x3x40x40x7] and [1x3x20x20x7]. 
I wonder how to convert this result to bbox coordinates and confidence score?
thanks!!!

**Comment by glenn-jocher** [comment]
@PiPiNam your code is out of date. To update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>
