### ISSUE TITLE
about focal loss in loss.py

### ISSUE THREAD

**Issue by ZixuanLingit666** [ultralytics/yolov5#3179]
As we know, the most key parameter in focal loss is gamma, so g in loss.py as in the picture below.
![image](https://user-images.githubusercontent.com/52994675/118390488-e41b2800-b661-11eb-9008-b1dd6b4872f3.png)
 
when g=0 it is equal to CrossEntropy, but why the result of mAP in the setting of g=2 is worse than g=0?
or do I  misunderstand the gamma of focal loss ?

**Comment by glenn-jocher** [comment]
@rerester results will vary by many factors. If I were you I'd test small increments of g rather than jumping to 2.0 to better understand your trend.

**Comment by ZixuanLingit666** [comment]
> @rerester results will vary by many factors. If I were you I'd test small increments of g rather than jumping to 2.0 to better understand your trend.

OK, I see
