### ISSUE TITLE
How to specify max_det when using PyTorch Hub?

### ISSUE THREAD

**Issue by adrianholovaty** [ultralytics/yolov5#3180]
I'm trying to use PyTorch Hub for inference, as explained in the main YOLOv5 readme. Per [this help page](https://github.com/ultralytics/yolov5/issues/36), I know I can specify some inference settings by setting attributes on the model:

```
import torch
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')
model.conf = 0.4 # Inference setting
img = '/path/to/my-image.jpg'
results = model(img)
```

But I can't find out how to override the default `max_det` using this method. How can I increase `max_det` with this particular workflow?

To be crystal clear, by `max_det` I mean the maximum number of detections per image, as defined in `non_max_suppression()` in `utils/general.py`.

Thanks as always for YOLOv5!

**Comment by glenn-jocher** [comment]
@adrianholovaty that's a good question. There isn't any mechanism to do that at the moment other than to modify the hard coded value in your hub cache.

The limit is mainly intended for training, not for deployment, as thousands of predictions will slow down mAP computation during testing with almost no mAP improvement, so I think we actually have a TODO to apply a looser max_det when a deployment-level confidence is passed, i.e. > 0.01.

We should probably parameterize all of the hard coded settings anyway and update the function doc string. If you have time you could do this yourself and submit a PR. If not I'll add a TODO on this issue to queue it for action later.
https://github.com/ultralytics/yolov5/blob/17b0f71538d3e9990e0e6c4b5c7c48375956efa3/utils/general.py#L499-L507

**Comment by adrianholovaty** [comment]
@glenn-jocher All makes sense — thanks for the info! I've just created pull request #3215 to parameterize `max_det`.

One separate question: At what point does the hub cache get refreshed (if ever)? I updated my local cache to change the hard-coded `max_det` but want to make sure that doesn't get overridden. :)

**Comment by glenn-jocher** [comment]
@adrianholovaty great thanks!

I don't think hub refreshes unless you request it with `force_reload=True`

### Force Reload
If you run into problems with the above steps, setting `force_reload=True` may help by discarding the existing cache and force a fresh download of the latest YOLOv5 version from PyTorch Hub.
```python
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)  # force reload
```
