### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by Zzheng-6** [ultralytics/yolov5#3185]
When I tried to use the weight of the last training to continue training, the following error occurred

![image](https://user-images.githubusercontent.com/75076373/118420470-8504f400-b6f1-11eb-96c6-8699c22f5f67.png)

**Comment by glenn-jocher** [comment]
@Zzheng-6 hi, sorry about that! @AyushExel, our W&B engineer may be able to help here. Is the error reproducible if you try again? Could you also link to the W&B run that caused the problem?

**Comment by AyushExel** [comment]
@Zzheng-6 looking at the error message, it seems that you're passing config of a different model than what you're resuming the run from. That's why wandb is complaining. We can change it so that it doesn't complain in such cases but this isn't recommended. As Glenn mentioned, the run link and the full command to reproduce this error would be helpful

**Comment by Zzheng-6** [comment]
I'm sorry, I don't quite understand the solution you said. Could you tell me more about it?


I added the following two lines of code to train.py, which is running successfully:


import wandb


wandb.init(allow_ val_ change=False)


But will it bring any problems to the training?


It's strange that I didn't modify the model in the second training, it's the same as in the first training.


Thank you for your timely reply!







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ultralytics/yolov5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月17日(星期一) 下午4:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ultralytics/yolov5] Can you help me? (#3185)





 
@Zzheng-6 looking at the error message, it seems that you're passing config of a different model than what you're resuming the run from. That's why wandb is complaining. We can change it so that it doesn't complain in such cases but this isn't recommended. As Glenn mentioned, the run link and the full command to reproduce this error would be helpful

**Comment by AyushExel** [comment]
@Zzheng-6 yes the `allow_val_change` command will suppress warnings when you try to change the config when resuming, but it's not recommended. We might be able to diagnose the problem if you can provide the list of commands that you ran when you got the error. Something to reproduce the same error on our end.

**Comment by glenn-jocher** [comment]
@AyushExel hmm that's interesting. Generally I try to limit user choices in situations like this, as from experience we've seen that the more arguments a user has available when doing something the more likely it is they'll pair incompatible values together. A good example of this is in darknet yolov3, when you had to pass both a --cfg and a --weights file for detection, which would break with the wrong combination. This is also why the local --resume accepts no additional arguments.

**Comment by Zzheng-6** [comment]
It's a pity that the mistake at that time appeared in the 54th epoch, but there was no record of the 54th epoch on wandb. If I ignored his warning in this way, would it have any impact on my training results?




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "ultralytics/yolov5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月17日(星期一) 下午5:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ultralytics/yolov5] Can you help me? (#3185)





 
@Zzheng-6 yes the allow_val_change command will suppress warnings when you try to change the config when resuming, but it's not recommended. We might be able to diagnose the problem if you can provide the list of commands that you ran when you got the error. Something to reproduce the same error on our end.

**Comment by AyushExel** [comment]
> It's a pity that the mistake at that time appeared in the 54th epoch, but there was no record of the 54th epoch on wandb. If I ignored his warning in this way, would it have any impact on my training results?
> 
> 
> 
> 
> ------------------ 原始邮件 ------------------
> 发件人:                                                                                                                        "ultralytics/yolov5"                                                                                    ***@***.***&gt;;
> 发送时间:&nbsp;2021年5月17日(星期一) 下午5:13
> ***@***.***&gt;;
> ***@***.******@***.***&gt;;
> 主题:&nbsp;Re: [ultralytics/yolov5] Can you help me? (#3185)
> 
> 
> 
> 
> 
>  
> @Zzheng-6 yes the allow_val_change command will suppress warnings when you try to change the config when resuming, but it's not recommended. We might be able to diagnose the problem if you can provide the list of commands that you ran when you got the error. Something to reproduce the same error on our end.
>  
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

I'll need to reproduce this error to give a definitive answer. Can you please do any one of this? :
* Share the wandb run link of the experiment
* Provide the list of exact commands that you ran

**Comment by AyushExel** [comment]
> @AyushExel hmm that's interesting. Generally I try to limit user choices in situations like this, as from experience we've seen that the more arguments a user has available when doing something the more likely it is they'll pair incompatible values together. A good example of this is in darknet yolov3, when you had to pass both a --cfg and a --weights file for detection, which would break with the wrong combination. This is also why the local --resume accepts no additional arguments.

@glenn-jocher yes and the online resume works on the same principles as the offline resume. The only difference is that the opt values are passed into config when resuming, so if the values are not same as the checkpoint, it complains, which is intended to inform the user that they're using incompatible values.

**Comment by glenn-jocher** [comment]
@AyushExel hmm ok I see.

**Comment by Zzheng-6** [comment]
This is my wandb link
https://wandb.ai/lutrazheng/YOLOv5/table?workspace=user-lutrazheng

**Comment by AyushExel** [comment]
@Zzheng-6 thanks for this. It'll help me get to the root of the problem. In first look, I don't see any difference in both the dicts so I guess it's complaining because of the order being different. I'll probably put in `allow_val_change` in the init statements.

**Comment by AyushExel** [comment]
@glenn-jocher I tested offline resume with `python train.py --resume` and I'm not seeing this error, so I'm not making a PR to allow the above-mentioned changes. If someone else encounters this error, feel free to tag me and I'll make the changes.
