### ISSUE TITLE
Inference using ssh error: unable to open display ""

### ISSUE THREAD

**Issue by abuelgasimsaadeldin** [ultralytics/yolov5#3187]
Hi I'm working on a project on the Jetson and trying to run inference using ssh protocol and I receive the error of unable because obviously there is no display. I'm trying to search where in the script is the cv2.imshow command so that I could comment it out but I could not find it.

My question is where in the code is the command cv2.imshow that displays the pop up window for the webcam. Thank you.

**Comment by glenn-jocher** [comment]
@abuelgasimsaadeldin image displays are only enabled on supported environments. We use check_imshow() function for this determination:
https://github.com/ultralytics/yolov5/blob/36b0a9e7d01637a71ef2050d16d945de5dad7929/utils/general.py#L157-L170

If you believe you have a reproducible issue, we suggest you close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose), providing screenshots and a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. Thank you!

**Comment by abuelgasimsaadeldin** [comment]
Hi @glenn-jocher thank you for the response, I think my error is a little different. I'm running the YOLOv5 on a docker container on my Jetson Nano and everything works fine including the pop-up window display during live camera inference, but what I want to do is to be able to SSH into the Nano and run the inference (without displaying the pop-up window because obviously there is no display) then save the results as usual for later viewing. However now I receive the error ```error: unable to open display ""``` and the process just ends.

Where in the script would I need to change to be able to run inference without the need of displaying the pop-up window and save the results as usual. Thanks!

**Comment by glenn-jocher** [comment]
@abuelgasimsaadeldin this is exactly the purpose of the check_imshow() function in https://docs.ultralytics.com/yolov5/tutorials/model_ensembling7#issuecomment-842260107, to determine is showing images is viable in your environment. If this function is not working correctly in your environment then please debug and send a PR with a solution that works for your use case. Thank you!

**Comment by YoungJonathanP** [comment]
Having a similar issue. Is it possible to test inference without streaming video?
![image](https://user-images.githubusercontent.com/47680806/122866370-ace10c00-d2dc-11eb-9c7a-278e24d7a83d.png)

**Comment by glenn-jocher** [comment]
@YoungJonathanP your error indicates you are attempting to show windows in a environment with no graphical user interface capability: https://askubuntu.com/questions/614387/gksu-gtk-warning-cannot-open-display-0

The check_imshow() function determines if an environment is suitable for showing results:
https://github.com/ultralytics/yolov5/blob/b83e1a4adcf77ccafa72b22ade6cb3898ccb0e05/detect.py#L81-L82

You should verify correct operation of the function for your environment and contribute any fixes you develop to help future users please. See https://github.com/ultralytics/yolov5#contribute

The function itself is here:
https://github.com/ultralytics/yolov5/blob/b83e1a4adcf77ccafa72b22ade6cb3898ccb0e05/utils/general.py#L189-L202
