### ISSUE TITLE
Detect.py doesn't stop after video/streams end

### ISSUE THREAD

**Issue by 424124** [ultralytics/yolov5#3189]
c:\OG\yolov5>python detect.py https://www.youtube.com/watch?v=IGQBtbKSVhY
usage: detect.py [-h] [--weights WEIGHTS [WEIGHTS ...]] [--source SOURCE] [--img-size IMG_SIZE]
                 [--conf-thres CONF_THRES] [--iou-thres IOU_THRES] [--device DEVICE] [--view-img] [--save-txt]
                 [--save-conf] [--save-crop] [--nosave] [--classes CLASSES [CLASSES ...]] [--agnostic-nms] [--augment]
                 [--update] [--project PROJECT] [--name NAME] [--exist-ok] [--line-thickness LINE_THICKNESS]
                 [--hide-labels] [--hide-conf]
detect.py: error: unrecognized arguments: https://www.youtube.com/watch?v=IGQBtbKSVhY

c:\OG\yolov5>python detect.py --source https://www.youtube.com/watch?v=IGQBtbKSVhY
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.25, device='', exist_ok=False, hide_conf=False, hide_labels=False, img_size=640, iou_thres=0.45, line_thickness=1, name='exp', nosave=False, project='runs/detect', save_conf=False, save_crop=False, save_txt=False, source='https://www.youtube.com/watch?v=IGQBtbKSVhY', update=False, view_img=False, weights='yolov5s.pt')
YOLOv5  v5.0-91-g17b0f71 torch 1.8.1+cu111 CUDA:0 (NVIDIA GeForce RTX 3070, 8192.0MB)

Fusing layers...
Model Summary: 224 layers, 7266973 parameters, 0 gradients
1/1: https://www.youtube.com/watch?v=IGQBtbKSVhY...  success (1280x720 at 29.97 FPS).

0: 384x640 Done. (0.719s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.019s)
0: 384x640 1 bird, Done. (0.019s)
0: 384x640 1 bird, Done. (0.013s)
0: 384x640 1 bird, Done. (0.024s)
0: 384x640 1 bird, Done. (0.027s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.016s)
0: 384x640 Done. (0.017s)
0: 384x640 Done. (0.027s)
0: 384x640 Done. (0.026s)
0: 384x640 Done. (0.018s)
0: 384x640 Done. (0.010s)
0: 384x640 Done. (0.010s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.022s)
0: 384x640 Done. (0.026s)
0: 384x640 Done. (0.023s)
0: 384x640 Done. (0.011s)
0: 384x640 Done. (0.017s)
0: 384x640 Done. (0.014s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.018s)
0: 384x640 Done. (0.019s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.022s)
0: 384x640 Done. (0.026s)
0: 384x640 Done. (0.018s)
0: 384x640 Done. (0.011s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.020s)
0: 384x640 Done. (0.020s)
0: 384x640 Done. (0.017s)
0: 384x640 Done. (0.016s)
0: 384x640 Done. (0.010s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.021s)
0: 384x640 1 bird, Done. (0.019s)
0: 384x640 1 bird, Done. (0.019s)
0: 384x640 1 bird, Done. (0.020s)
0: 384x640 1 bird, Done. (0.018s)
0: 384x640 1 bird, Done. (0.011s)
0: 384x640 1 bird, Done. (0.017s)
0: 384x640 1 bird, Done. (0.024s)
0: 384x640 1 bird, Done. (0.026s)
0: 384x640 1 bird, Done. (0.014s)
0: 384x640 1 bird, Done. (0.018s)
0: 384x640 1 bird, Done. (0.019s)
0: 384x640 1 bird, Done. (0.015s)
0: 384x640 1 bird, Done. (0.018s)
0: 384x640 1 bird, Done. (0.016s)
0: 384x640 1 bird, Done. (0.026s)
0: 384x640 Done. (0.012s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.010s)
0: 384x640 Done. (0.010s)
0: 384x640 Done. (0.010s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.022s)
0: 384x640 Done. (0.015s)
0: 384x640 Done. (0.013s)
0: 384x640 Done. (0.016s)
0: 384x640 Done. (0.023s)
0: 384x640 Done. (0.019s)
0: 384x640 Done. (0.010s)
0: 384x640 1 bear, Done. (0.012s)
0: 384x640 1 bear, Done. (0.027s)
0: 384x640 1 bear, Done. (0.025s)
0: 384x640 1 bear, Done. (0.015s)
0: 384x640 1 bear, Done. (0.025s)
0: 384x640 Done. (0.026s)
0: 384x640 Done. (0.025s)
0: 384x640 Done. (0.014s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.011s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.022s)
0: 384x640 Done. (0.027s)
0: 384x640 Done. (0.028s)
0: 384x640 Done. (0.021s)
0: 384x640 Done. (0.011s)
0: 384x640 1 bear, Done. (0.017s)
0: 384x640 1 bear, Done. (0.020s)
0: 384x640 1 bear, Done. (0.019s)
0: 384x640 1 bear, Done. (0.023s)
0: 384x640 1 bear, Done. (0.018s)
0: 384x640 Done. (0.019s)
0: 384x640 Done. (0.011s)
0: 384x640 Done. (0.011s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.017s)
0: 384x640 Done. (0.019s)
0: 384x640 Done. (0.010s)
0: 384x640 Done. (0.011s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.022s)
0: 384x640 Done. (0.020s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.020s)
0: 384x640 Done. (0.019s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.012s)
0: 384x640 Done. (0.011s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.017s)
0: 384x640 Done. (0.017s)
0: 384x640 1 bird, Done. (0.013s)
0: 384x640 1 bird, Done. (0.017s)
0: 384x640 1 bird, Done. (0.014s)
0: 384x640 1 bird, Done. (0.026s)
0: 384x640 1 bird, Done. (0.023s)
0: 384x640 1 bird, Done. (0.027s)
0: 384x640 1 bird, Done. (0.025s)
0: 384x640 1 bird, Done. (0.021s)
0: 384x640 1 bird, Done. (0.019s)
0: 384x640 Done. (0.021s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.010s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.011s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.011s)
0: 384x640 Done. (0.013s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.022s)
0: 384x640 Done. (0.025s)
0: 384x640 Done. (0.017s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.010s)
0: 384x640 Done. (0.007s)
0: 384x640 Done. (0.013s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.011s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.013s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.011s)
0: 384x640 Done. (0.010s)
0: 384x640 Done. (0.022s)
0: 384x640 Done. (0.019s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.011s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.011s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.018s)
0: 384x640 Done. (0.019s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.020s)
0: 384x640 Done. (0.017s)
0: 384x640 Done. (0.013s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.016s)
0: 384x640 Done. (0.021s)
0: 384x640 Done. (0.018s)
0: 384x640 Done. (0.012s)
0: 384x640 Done. (0.012s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.014s)
0: 384x640 Done. (0.010s)
0: 384x640 Done. (0.017s)
0: 384x640 Done. (0.018s)
0: 384x640 Done. (0.018s)
0: 384x640 Done. (0.013s)
0: 384x640 Done. (0.015s)
0: 384x640 Done. (0.026s)
0: 384x640 Done. (0.019s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.022s)
0: 384x640 Done. (0.019s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.010s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.010s)
0: 384x640 Done. (0.018s)
0: 384x640 Done. (0.018s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.017s)
0: 384x640 Done. (0.018s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.013s)
0: 384x640 Done. (0.015s)
0: 384x640 Done. (0.021s)
0: 384x640 Done. (0.015s)
0: 384x640 Done. (0.017s)
0: 384x640 Done. (0.011s)
0: 384x640 Done. (0.010s)
0: 384x640 Done. (0.014s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.013s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.018s)
0: 384x640 Done. (0.010s)
0: 384x640 Done. (0.017s)
0: 384x640 Done. (0.013s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.011s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.016s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.011s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.021s)
0: 384x640 Done. (0.016s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.014s)
0: 384x640 Done. (0.016s)
0: 384x640 Done. (0.025s)
0: 384x640 Done. (0.017s)
0: 384x640 Done. (0.011s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.017s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.011s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.016s)
0: 384x640 Done. (0.024s)
0: 384x640 Done. (0.012s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.010s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.022s)
0: 384x640 Done. (0.022s)
0: 384x640 Done. (0.018s)
0: 384x640 Done. (0.011s)
0: 384x640 Done. (0.012s)
0: 384x640 Done. (0.011s)
0: 384x640 Done. (0.011s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.016s)
0: 384x640 Done. (0.010s)
0: 384x640 Done. (0.016s)
0: 384x640 Done. (0.014s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.010s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.010s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.014s)
0: 384x640 Done. (0.019s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.019s)
0: 384x640 Done. (0.018s)
0: 384x640 Done. (0.010s)
0: 384x640 Done. (0.017s)
0: 384x640 Done. (0.014s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.013s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.013s)
0: 384x640 Done. (0.017s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.012s)
0: 384x640 Done. (0.010s)
0: 384x640 Done. (0.011s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.021s)
0: 384x640 Done. (0.021s)
0: 384x640 Done. (0.010s)
0: 384x640 Done. (0.017s)
0: 384x640 Done. (0.016s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.010s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.019s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.012s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.010s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.009s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.015s)
0: 384x640 Done. (0.010s)
0: 384x640 Done. (0.011s)
0: 384x640 Done. (0.010s)
0: 384x640 Done. (0.017s)
0: 384x640 Done. (0.014s)
0: 384x640 Done. (0.010s)
0: 384x640 Done. (0.017s)
0: 384x640 Done. (0.017s)
0: 384x640 Done. (0.011s)
0: 384x640 Done. (0.018s)
0: 384x640 Done. (0.010s)
0: 384x640 Done. (0.008s)
0: 384x640 Done. (0.017s)
0: 384x640 Done. (0.010s)
0: 384x640 Done. (0.016s)
0: 384x640 Done. (0.012s)
0: 384x640 Done. (0.010s)
0: 384x640 Done. (0.011s)

forrtl: error (200): program aborting due to control-C event
Image              PC                Routine            Line        Source
libifcoremd.dll    00007FF80E4C3B58  Unknown               Unknown  Unknown
KERNELBASE.dll     00007FF981269D43  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FF981D66FD4  Unknown               Unknown  Unknown
ntdll.dll          00007FF983ADCEC1  Unknown               Unknown  Unknown

**Comment by glenn-jocher** [comment]
@424124 it looks like the cap.isOpened() property is not setting to False at the end of the video. This seems to be an OpenCV problem, you may want to raise an issue there. If you find a solution please let us know, or better yet please submit a PR. Thanks and good luck!

https://github.com/ultralytics/yolov5/blob/ae53f50ae75d83d792927b8196b70702218eb69e/utils/datasets.py#L301-L313

**Comment by glenn-jocher** [comment]
@424124 we're using a similar loop to https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_gui/py_video_display/py_video_display.html

**Comment by 424124** [comment]
Pressing 'q' on the pop-up helped to close.
