### ISSUE TITLE
How do you end a stream on detect.py?

### ISSUE THREAD

**Issue by 424124** [ultralytics/yolov5#3190]
So when I run detect.py, it keeps going on and on, i try to close the video but it pops up again and keeps running.

how do I tell it to stop streaming?
Is there a hotkey to close it?
i just use CTRL + C to interrupt to stop the stream, but that then i get a "cant open file, corrupted etc" in detect/exp/"video.mp4"

**Comment by glenn-jocher** [comment]
@424124 If you believe you have a reproducible issue, we suggest you close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose), providing screenshots and a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. Thank you!

**Comment by glenn-jocher** [comment]
@424124 I think there may be a solution in https://github.com/ultralytics/yolov5/pull/2769

Can you try this PR and see if it works for you?

**Comment by glenn-jocher** [comment]
@424124 good news 😃! Your original issue may now be fixed ✅ in PR #3277. This PR updates the streamloader class to properly detect stopped daemon threads and results in **correct conclusion of YouTube video inference.** To receive this update you can:
- `git pull` from within your `yolov5/` directory
- `git clone https://github.com/ultralytics/yolov5` again
- Force-reload [PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/): `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- View our updated notebooks:  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
