### ISSUE TITLE
Is it possible to make yolov5 record the predicted labels into a txt file?

### ISSUE THREAD

**Issue by 424124** [ultralytics/yolov5#3191]
If we ran detect.py on a stream, could we have the live detection or predictions load itself onto a file or program to see?  (like logging what it predicted)

i.e person1 confidence 0.6 date, time etc.

**Comment by sezer-muhammed** [comment]
> If we ran detect.py on a stream, could we have the live detection or predictions load itself onto a file or program to see? (like logging what it predicted)
> 
> i.e person1 confidence 0.6 date, time etc.

Hi,

I made this by adding a new function.

I changed draw rectangle function.
So that I can write my detections into file.
I added new input to this function "file" for this purpose.

But if you want to better system you can directly add this file operation in the main loop.

`for path, img, im0s, vid_cap in dataset:

        h, w, c = im0s.shape
        
        img = torch.from_numpy(img).to(device)
        img = img.half() if half else img.float()  # uint8 to fp16/32
        img /= 255.0  # 0 - 255 to 0.0 - 1.0
        if img.ndimension() == 3:
            img = img.unsqueeze(0)
        ayristir = path.split("\\") #i did
        uzantisiz = ayristir[-1].split(".")[0]#i did
        
        # Inference
        t1 = time_synchronized()
        pred = model(img, augment=opt.augment)[0]

        # Apply NMS
        pred = non_max_suppression(
            pred, opt.conf_thres, opt.iou_thres, classes=opt.classes)
        t2 = time_synchronized()

        # Apply Classifier
        if classify:
            pred = apply_classifier(pred, modelc, img, im0s)

        file = open("yolo-labels/"+uzantisiz+".xml", "w") #i did 
        file.write("<annotation>\n")
        file.write("	<folder>output</folder>\n")
        file.write("	<filename>"+uzantisiz+"</filename>\n")
        file.write(
            "	<path>"+path+".jpg"+"</path>\n")
        file.write("	<source>\n")
        file.write("		<database>Unknown</database>\n")
        file.write("	</source>\n")
        file.write("	<size>\n")
        file.write("		<width>"+str(w)+"</width>\n")
        file.write("		<height>"+str(h)+"</height>\n")
        file.write("		<depth>3</depth>\n")
        file.write("	</size>\n")
        file.write("	<segmented>0</segmented>\n")`

This is What I did.

**Comment by glenn-jocher** [comment]
@424124 you can use `--python detect.py --save-txt`. See detect.py argparser for details on all available arguments.

**Comment by AnubhavDixit** [comment]
Hi all, I want that the count of the bounding boxes in the output of YOLO should be printed on the image, where I need to do the changes? I can't figure it out currently.

**Comment by glenn-jocher** [comment]
@AnubhavDixit you can modify the YOLOv5 codebase to achieve this. In the `detect.py` script, you can add the functionality to display the count of bounding boxes on the image by modifying the visualization function, specifically the part where bounding boxes and labels are drawn. Feel free to refer to the file `detect.py` and make changes in the `plot_one_box` and `plot_one_frame` functions to include the count of bounding boxes on the image.
