### ISSUE TITLE
Stream with 0fps?

### ISSUE THREAD

**Issue by 424124** [ultralytics/yolov5#3196]
Tried to run detect.py on a live camera stream but there is no movement in the popup. 

Fusing layers...
Model Summary: 224 layers, 7266973 parameters, 0 gradients
1/1: 0...  success (640x480 at 0.00 FPS).
Exception in thread Thread-1
Exception in thread :
Thread-2Traceback (most recent call last):
:
  File "C:\Users\Admin\anaconda3\lib\threading.py", line 932, in _bootstrap_inner
Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\lib\threading.py", line 932, in _bootstrap_inner
        self.run()self.run()

  File "C:\Users\Admin\anaconda3\lib\threading.py", line 870, in run
  File "C:\Users\Admin\anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
      File "c:\OG\yolov5\utils\datasets.py", line 326, in update
self._target(*self._args, **self._kwargs)
  File "c:\OG\yolov5\utils\datasets.py", line 326, in update
    time.sleep(1 / self.fps)  # wait time
time.sleep(1 / self.fps)  # wait timeZeroDivisionError
: ZeroDivisionErrorfloat division by zero:
float division by zero

it still attempts to detect but on a still 0FPS or still frame?

0: 480x640 1 stop sign, Done. (0.018s)
0: 480x640 1 stop sign, Done. (0.017s)
0: 480x640 1 stop sign, Done. (0.016s)
0: 480x640 1 stop sign, Done. (0.014s)
0: 480x640 1 stop sign, Done. (0.016s)
0: 480x640 1 stop sign, Done. (0.012s)
0: 480x640 1 stop sign, Done. (0.017s)
0: 480x640 1 stop sign, Done. (0.013s)

**Comment by glenn-jocher** [comment]
@424124 0 FPS sounds like a great stream haha

I assume we'll need to add some floor to the wait time op to account for these types of streams (!).

**Comment by glenn-jocher** [comment]
@424124 good news 😃! Your original issue may now been fixed ✅ in PR #3216.  To receive this update you can:
- `git pull` from within your `yolov5/` directory
- `git clone https://github.com/ultralytics/yolov5` again
- Force-reload [PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/): `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- View our updated notebooks:  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by 424124** [comment]
@glenn-jocher Thanks, that fixed the issue perfectly!
0FPS is quite a stream haha..
