### ISSUE TITLE
Plugging custom pre-trained backbone and freezing it for N epochs

### ISSUE THREAD

**Issue by yannclaes** [ultralytics/yolov5#3197]
## ❔Question
Hi, I'm working on an object detection thesis whose goal is to study transfer learning with domain shift (natural images -> paintings). I have run some basic fine-tuning jobs using YOLOv5 (worked as easily as expected), however now I would like to perform the following:

- Take a YOLOv5 model (e.g. large) and replace its backbone with a custom trained backbone. What I mean by that is that I have a ResNeXt-101 32x8d classifier which is fully fine-tuned on paintings (and saved in some .pt file) and I would like to plug the feature extracting part of that classifier (basically all layers except the FC ones) as backbone of the YOLO model. I've already done that with Faster R-CNN models (https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html#modifying-the-model-to-add-a-different-backbone) and it's super easy, however I seem to struggle to do the same for YOLO. Is there an "easy" way or what would be the most straightforward approach? I guess I would need a specific --cfg .yaml file but I don't see how to load my ResNeXt model as backbone)
- When this is done, I would like to compare two settings: fine-tuning this new detector as is and fine-tuning it after freezing the backbone for N epochs. For instance, I would like to freeze the backbone I've just plugged in for 10 epochs, and then unfreeze after these 10 epochs to fine-tune it as well. How would I do that? I've seen the tutorial about freezing backbone but then it remains frozen during the whole training. 

Thanks in advance

**Comment by glenn-jocher** [comment]
@yannclaes hi thanks for the question! In general we don't have resources to assist users with their own design and experimentation projects, so I would simply point you to our 'Transfer Learning with Frozen Layers' tutorial below. Good luck and perhaps you can get some better community feedback from other users. 

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)
