### ISSUE TITLE
coco128/images

### ISSUE THREAD

**Issue by 123456789mojtaba** [ultralytics/yolov5#320]
in coco128/images/train2017 there is only images or images with their labels?

**Comment by glenn-jocher** [comment]
@123456789mojtaba the dataset contains the first 128 images of COCO train 2017. It is used as the tutorial dataset for YOLOv5: https://github.com/ultralytics/yolov5. **It does include labels.**

The dataset uses the same 128 images to train and test on. It is intended to validate a training pipeline by demonstrating overfitting on a small dataset before training a larger dataset.

You can see more info on the Kaggle dataset site for coco128:
https://www.kaggle.com/datasets/ultralytics/coco128

**Comment by 123456789mojtaba** [comment]
thank you because of your help.
can you lead me how to  docker the model? I know nothing  about
docker.should I docker the weights file only?

**Comment by glenn-jocher** [comment]
https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/
