### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Laudarisd** [ultralytics/yolov5#3219]
YOLOv5 🚀 2021-5-18 torch 1.9.0.dev20210517+cu111 CUDA:0 (GeForce RTX 3060, 12053.8125MB)

Fusing layers... 
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
Model Summary: 392 layers, 46600566 parameters, 0 gradients, 114.1 GFLOPS
image 1/13 /AI/AI/mapillary_AI/pytorch_yolo/test/1.png: Traceback (most recent call last):
  File "detect.py", line 186, in <module>
    detect(opt=opt)
  File "detect.py", line 101, in detect
    s += f"{n} {names[int(c)]}{'s' * (n > 1)}, "  # add to string
IndexError: list index out of range

Suddenly I am getting this error while doing inference.

Can anyone help me?
How to fix this?

I am using docker, python 3.6,

**Comment by glenn-jocher** [comment]
@Laudarisd if you believe you have a reproducible bug, we suggest you close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose), providing screenshots and a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. Thank you!
