### ISSUE TITLE
Now with FPS > 0, cmd wont end 

### ISSUE THREAD

**Issue by 424124** [ultralytics/yolov5#3220]
So after I followed instructions on how to fix #3196 by git pull, I get proper stream with FPS.
but when I close the stream by typing 'q', it cant fully complete or close.

I get:

c:\OG\yolov5>python detect.py --source 0
Namespace(weights='yolov5s.pt', source='0', img_size=640, conf_thres=0.6, iou_thres=0.45, device='', view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, update=False, project='runs/detect', name='exp', exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False)
YOLOv5  v5.0-91-g17b0f71 torch 1.8.1+cpu CPU

Fusing layers...
Model Summary: 224 layers, 7266973 parameters, 0 gradients
1/1: 0...  success (-1 frames 640x480 at 30.00 FPS).

0: 480x640 1 car, Done. (0.259s)
0: 480x640 1 car, Done. (0.265s)
0: 480x640 1 car, Done. (0.260s)
0: 480x640 1 car, Done. (0.267s)
0: 480x640 1 car, Done. (0.267s)
0: 480x640 1 car, Done. (0.258s)
0: 480x640 1 car, Done. (0.263s)
0: 480x640 1 car, Done. (0.262s)
0: 480x640 1 car, Done. (0.261s)
Results saved to runs\detect\exp
Done. (10.545s)

its stuck after it Done, command prompt doesnt move, save file in exp doesnt exist, cant close or interrupt the command in cmd

**Comment by glenn-jocher** [comment]
@424124 you might need to interrupt with CTRL C.

**Comment by 424124** [comment]
@glenn-jocher  i tried to interrupt but nothing happens, only way to do anything else is to close that command prompt and start a new one

**Comment by 424124** [comment]
I think it might have something to do with the code thinking the process hasn't ended?

I'm trying to call detect.py to load using a watchdog script with the command:
os.system('python c:\yolov5\detect.py'

so the watchdog script, when running, is supposed to: 
detects changes in directory > opens and runs detect.py > repeat on next change

problem is, detect.py doesnt stop so I can't loop it.

**Comment by glenn-jocher** [comment]
@424124 as far as I know the only sources with termination problems are youtube videos. We don't have a force stop at the end of the video yet based on framecount, and the cv2 cap object can't determine when the video has ended.

Normal videos should all end correctly.

**Comment by glenn-jocher** [comment]
@424124 good news 😃! Your original issue may now be fixed ✅ in PR #3277. This PR updates the streamloader class to properly detect stopped daemon threads and results in **correct conclusion of YouTube video inference.** To receive this update you can:
- `git pull` from within your `yolov5/` directory
- `git clone https://github.com/ultralytics/yolov5` again
- Force-reload [PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/): `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- View our updated notebooks:  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
