### ISSUE TITLE
Some code cannot work

### ISSUE THREAD

**Issue by maxuetao** [ultralytics/yolov5#3224]
## 🐛 Bug
When I execute the following command：
amaxv1004@ub-amaxv1004:~/DATA20T/data20t/sakuram/projects/yolov5$ CUDA_VISIBLE_DEVICES=2 python train.py --weights ./weights/yolov5x.pt --data ./HB_early/coco.yaml --device 2 --epochs 500 --multi-scale --adam

There is no error, but there is no output.Then I found the problem：
When the code is executed to (utils/general.py from utils.metrics import fitness ), the code will stop working without any output

## To Reproduce (REQUIRED)
I wrote a simple code ：

from utils.metrics import fitness
print("import success!")

Then execute the .py file，here is a screenshot of the result：
![image](https://user-images.githubusercontent.com/24203678/118634144-cafeac80-b804-11eb-8dea-f2c05ef2b679.png)
I can see that the background program still exists, but there is no output：
![image](https://user-images.githubusercontent.com/24203678/118634388-0c8f5780-b805-11eb-8769-48c085229c2a.png)

## Environment

 - OS: [Ubuntu]
 - GPU [Nvidia V100]

## Additional context
I don't think this problem can be reproduced completely, because it doesn't appear every time in practice, but I don't know the reason for it. Please give me some suggestions, thank you！

**Comment by glenn-jocher** [comment]
@SakuraMaxuetao I get a circular import error if I try your command:

```python
from utils.metrics import fitness
print("import success!")

Backend MacOSX is interactive backend. Turning interactive mode on.
Traceback (most recent call last):
  File "/Users/glennjocher/PycharmProjects/yolov5/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-5594053bbff8>", line 1, in <module>
    from utils.metrics import fitness
  File "/Users/glennjocher/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-C/ch-0/211.6693.115/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/glennjocher/PycharmProjects/yolov5/utils/metrics.py", line 9, in <module>
    from . import general
  File "/Users/glennjocher/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-C/ch-0/211.6693.115/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/glennjocher/PycharmProjects/yolov5/utils/general.py", line 25, in <module>
    from utils.metrics import fitness
ImportError: cannot import name 'fitness' from partially initialized module 'utils.metrics' (most likely due to a circular import) (/Users/glennjocher/PycharmProjects/yolov5/utils/metrics.py)
```

**Comment by glenn-jocher** [comment]
@SakuraMaxuetao you can import fitness from utils.general instead:
```python
from utils.general import fitness
print('works!')
Backend MacOSX is interactive backend. Turning interactive mode on.
works!
```

**Comment by maxuetao** [comment]
> @SakuraMaxuetao you can import fitness from utils.general instead:
> 
> ```python
> from utils.general import fitness
> print('works!')
> Backend MacOSX is interactive backend. Turning interactive mode on.
> works!
> ```

Sorry, this modification does not work.   The most important question is，when the code is executed to (utils/general.py from utils.metrics import fitness ), the code will stop working without any output

**Comment by glenn-jocher** [comment]
@SakuraMaxuetao my proposed solution works correctly.

<img width="1171" alt="Screenshot 2021-05-24 at 12 01 43" src="https://user-images.githubusercontent.com/26833433/119331655-e562db00-bc87-11eb-81fd-6a85a6be67a7.png">

**Comment by maxuetao** [comment]
> @SakuraMaxuetao my proposed solution works correctly.
> 
> <img alt="Screenshot 2021-05-24 at 12 01 43" width="1171" src="https://user-images.githubusercontent.com/26833433/119331655-e562db00-bc87-11eb-81fd-6a85a6be67a7.png">

![image](https://user-images.githubusercontent.com/24203678/119344095-d13fcd80-bcc9-11eb-84c8-470ac146aea7.png)
There is still no output, and the program cannot be aborted. It looks like there will be some problems when reading this function. Does this problem have anything to do with my equipment？

**Comment by glenn-jocher** [comment]
@SakuraMaxuetao it appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below. 


## Requirements

**Python 3.8** or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including **`torch>=1.7`**. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by jay1308-code** [comment]
ImportError: cannot import name 'DEFAULT_CONFIG_DICT' from 'ultralytics.yolo.utils' (/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/__init__.py)

**Comment by glenn-jocher** [comment]
@jay1308-code it seems like you are encountering an import issue with `DEFAULT_CONFIG_DICT` from `ultralytics.yolo.utils`. This could be due to an incorrect version of the Ultralytics YOLOv5 package or an incomplete installation.

To resolve this, I recommend ensuring that you have the latest version of YOLOv5 installed using the following command:

```bash
pip install -U yolov5  # Install or upgrade to the latest YOLOv5 package
```

After updating the package, please attempt to run your code again. If the issue persists, consider creating a new virtual environment and reinstalling the required dependencies as mentioned in the previous message.

Additionally, make sure to refer to the official documentation at [Ultralytics YOLOv5 Docs](https://docs.ultralytics.com/yolov5/) for detailed installation and usage instructions.

If the problem continues, feel free to provide more details, and I'd be happy to assist further!
