### ISSUE TITLE
data loading error with coco.yaml

### ISSUE THREAD

**Issue by jaecheoljung** [ultralytics/yolov5#323]
I used google colab and tried to train a simple yolov5x model with coco dataset only using given shell codes.
```
!unzip yolov5-master.zip
cd yolov5-master/
!./data/get_coco2017.sh
!./weights/download_weights.sh
!python train.py --cfg ./models/yolov5x.yaml --data ./data/coco.yaml
```

and I got errors like below.

> Optimizer groups: 134 .bias, 142 conv.weight, 131 other
> Traceback (most recent call last):
>   File "/content/yolov5-master/utils/datasets.py", line 292, in __init__
>     raise Exception('%s does not exist' % path)
> Exception: ../coco/train2017.txt does not exist
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "train.py", line 394, in <module>
>     train(hyp)
>   File "train.py", line 166, in train
>     hyp=hyp, augment=True, cache=opt.cache_images, rect=opt.rect)
>   File "/content/yolov5-master/utils/datasets.py", line 52, in create_dataloader
>     pad=pad)
>   File "/content/yolov5-master/utils/datasets.py", line 295, in __init__
>     raise Exception('Error loading data from %s. See %s' % (path, help_url))
> Exception: Error loading data from ../coco/train2017.txt. See https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data

what did I miss?

**Comment by glenn-jocher** [comment]
@jaecheoljung that sounds like a terrible idea. Full coco epochs in colab will take a couple hours each at least, probably more with such a large model. In any case, the existing colab notebook shows you perfectly well how to train on coco128, why don't you start there?
