### ISSUE TITLE
Upsample layer outputs a list

### ISSUE THREAD

**Issue by yannclaes** [ultralytics/yolov5#3230]
## ❔Question
As I was struggling to modify the backbone of a YOLOv5 medium model, it appeared that the first Upsample layer of YOLO's head outputs a list instead of a tensor (concatenated right  after), which allows to meet the in_channels requirement of the next C3 module. I think this comes from the if statement at line 135 of ```models/yolo.py```. Is this technique similar to the one used in U-Net where they concatenate convolutional layer outputs with previous outputs? 

How could I adapt this when plugging my own pre-trained backbone? Right now, I managed to plug it in somehow but I lose the information about m.f and therefore I end up with a mismatch in the number of channels since I don't enter this condition. This is what I have so far (along with other modifications in related modules like ```check_anchors()``` as my resulting model no longer has a .model attribute). I don't know how to adapt it since I don't have layers in my backbone whose output have e.g. 384 channels (or 192 later).

<img width="679" alt="resnext_backbone_issue" src="https://user-images.githubusercontent.com/44881086/118690076-f9ca5200-b807-11eb-95e2-e0cae4943fff.png">

```model[1][-1]``` denotes the Detect() layers while ```model[1][0]``` corresponds to the Conv() layer right after the initial backbone.

**Comment by glenn-jocher** [comment]
@yannclaes in `m.f` `m` is the module and `f` is the `from` attribute that tells it which layer the input is coming from.

**Comment by glenn-jocher** [comment]
@yannclaes and yes, module inputs can be from a single layer (tensor), or from multiple layers (list of tensors).

**Comment by yannclaes** [comment]
Thanks for the explanations!
