### ISSUE TITLE
Is there any picture to discribe the architecture of yolov5?

### ISSUE THREAD

**Issue by yustaub** [ultralytics/yolov5#3235]
## ❔Question
Hello, sir. Very nice work firstly!! My job is based on yolov5, and I want to introduce it, is there any pic to discribe the architure of yolov5 model? Very appreciate for your reply!!

**Comment by glenn-jocher** [comment]
@yustaub good news 😃! Your original issue may now been fixed ✅ in PR #3236. This PR fixes the model architecture visual in TensorBoard for each training run under the 'GRAPHS' section. To receive this update you can:
- `git pull` from within your `yolov5/` directory
- `git clone https://github.com/ultralytics/yolov5` again
- Force-reload [PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/): `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- View our updated notebooks:  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

<img width="1137" alt="Screenshot 2021-05-19 at 13 49 29" src="https://user-images.githubusercontent.com/26833433/118808195-824cff00-b8a9-11eb-943e-6cd138b8d0f6.png">

**Comment by yustaub** [comment]
thank you!!! I got it. Appreciate!! @glenn-jocher
