### ISSUE TITLE
Objects < 3px

### ISSUE THREAD

**Issue by liangular** [ultralytics/yolov5#3237]
## ❔Question
In my dataset like 10% of the objects are smaller than 3px. Since the autoanchor gives a warning I wanted to ask if the warning means that it won't be able to detect those in any way and upscaling the original image is the only way to deal with extremely small objects?

**Comment by Pro100rus32** [comment]
You can try editing the parameters.

https://github.com/ultralytics/yolov5/blob/17b0f71538d3e9990e0e6c4b5c7c48375956efa3/utils/general.py#L499-L507

**Comment by glenn-jocher** [comment]
@liangular @Pro100rus32 actually there's two places that size constraints are implemented. The first is for label candidates here:
https://github.com/ultralytics/yolov5/blob/b7cd1f540d5815b0a1cf2e23ce82a5fdb8f6b525/utils/datasets.py#L944-L950

And the second is the NMS candidates that @Pro100rus32 showed, inside the NMS function. In general though, yes, increasing image size will help detect smaller objects better.

**Comment by liangular** [comment]
But https://github.com/ultralytics/yolov5/blob/17b0f71538d3e9990e0e6c4b5c7c48375956efa3/utils/general.py#L500 the `min_wh` in here seems to be unused (commented out) so I guess changing the value in the `box_candidates` function will be enough. I will try out decreasing the value there and if that doesn't work I'll increase the input size.

**Comment by glenn-jocher** [comment]
@liangular `min_wh` is in effect in NMS, it is not commented out. The default value is `min_wh = 2` pixels
