### ISSUE TITLE
cant test with test.py

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#3241]
command：
python test.py --weights runs/train/exp2/weights/last.pt 

error
Namespace(augment=False, batch_size=32, conf_thres=0.001, data='data/coco128.yaml', device='', exist_ok=False, img_size=640, iou_thres=0.6, name='exp', project='runs/test', save_conf=False, save_hybrid=False, save_json=False, save_txt=False, single_cls=False, task='val', verbose=False, weights=['runs/train/exp2/weights/last.pt'])
YOLOv5 🚀 v5.0-91-g17b0f71 torch 1.9.0a0+df837d0 CUDA:0 (GeForce RTX 3060, 12045.375MB)

Fusing layers... 
Illegal instruction (core dumped)

**Comment by debparth** [comment]
@alicera I've also got the same error. I've overcome it by creating a fresh environment followed by installing packages from the requirements.txt

**Comment by alicera** [comment]
But I already git clone new version and build the docker again.

**Comment by alicera** [comment]
Does it affect the python？

I run the docker and it show the error.

ERROR: This container was built for CPUs supporting at least the AVX instruction set, but
       the CPU detected was Intel(R) Pentium(R) Gold G6400 CPU @ 4.00GHz, which does not report
       support for AVX.  An Illegal Instrution exception at runtime is likely to result.
       See https://en.wikipedia.org/wiki/Advanced_Vector_Extensions#CPUs_with_AVX .
