### ISSUE TITLE
Pretrain backbone on our data

### ISSUE THREAD

**Issue by jonlwowski012** [ultralytics/yolov5#3244]
## ❔Question
Would it be possible to pretrain my own backbone and use those weights for finetuning the object detection model?

## Additional context
My dataset is not very large and the objects I am trying to detect are very small. Therefore, the features learned by a COCO or Imagenet pretraining might not be the best for my object detection model. I am thinking of pretraining an autoencoder or contrastive learning to pretrain my backbone.

**Comment by glenn-jocher** [comment]
@jonlwowski012 the official models are trained on COCO, and work well with cross-domain tasks, i.e. GlobalWheat2020 works great with YOLOv5, so I could simply stick to the default **Train Custom Data Tutorial** for your use case.

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)
