### ISSUE TITLE
Increasing the FPS in jetson

### ISSUE THREAD

**Issue by Zumbalamambo** [ultralytics/yolov5#3245]
I have implemented YOLOv5s  in Jetson NX. Resized the input shape to 416x416 and tried to run the inference. I'm able to obtain only 4-5 fps which is very less. It would be nice to have at least 30 fps. The `tensorrt` also gives the same amount of fps. Is there any way to ramp up the accuracy?

**Comment by glenn-jocher** [comment]
@Zumbalamambo you probably want to export at the minimum rectangular shape you need for inference. For our iOS app for example we export at 192x320 width x height for inference of portrait 4k video.
https://apps.apple.com/app/id1452689527

**Comment by Zumbalamambo** [comment]
For smaller objects, the detection failed while using the smallest possible dimension. Any ways to improvise it?

**Comment by glenn-jocher** [comment]
@Zumbalamambo for small objects you'll get best results with larger image sizes. So detection of small objects and fast inference speeds are competing priorities.

**Comment by suiyi1420** [comment]
I got 30 frames in jetson nano without tensorrt acceleration, you can check the question I submitted：
https://github.com/ultralytics/yolov5/issues/3273#issue-897811871
