### ISSUE TITLE
cannot convert a .pt file to onnx format.

### ISSUE THREAD

**Issue by rohanchoudharyy** [ultralytics/yolov5#325]
I am not able to convert my model (.pt format) trained on custom dataset to onnx format. I am using the correct environment. 

Input:
```
!export PYTHONPATH="$PWD"  # add path
!python /content/yolov5/models/export.py --weights /content/gdrive/'My Drive'/last_yolov5l_results_2.pt --img 416 --batch 1  # export
```
Output:
```
Traceback (most recent call last):
  File "/content/yolov5/models/export.py", line 9, in <module>
    from models.common import *
ModuleNotFoundError: No module named 'models'
```
I read somewhere to use onnx_export.py from the the latest repository of ultralytics/yolov5 but the models folder doesn't have it now. Anyways, I download it from other source and still getting the same error. Any ideas on how I can convert a .pt file to a onnx format ? Please Help.

**Comment by glenn-jocher** [comment]
@rohanchoudharyy the file contains example usage. Suggest you follow it.
https://github.com/ultralytics/yolov5/blob/31b07b355066dadf9823920d99749fad9ac26591/models/export.py#L1-L6

**Comment by CommandoHuan** [comment]
> @rohanchoudharyy the file contains example usage. Suggest you follow it.
> 
> https://github.com/ultralytics/yolov5/blob/31b07b355066dadf9823920d99749fad9ac26591/models/export.py#L1-L6

I have the same error, and I don't know how to use it as you suggested.  When I ran it showed errors like below:
(yolo5) E:\Python\yolov5_DownloadZip>export PYTHONPATH="C:\Program Files (X86)\Python\" && python models/export.py  --weight ..\Vietnamese-License-Plate\YOLO_weights\BienSoXe.pt --batch-size 1 --imgsz 640 --include onnx
'export' is not recognized as an internal or external command,
operable program or batch file.
