### ISSUE TITLE
RuntimeError: The size of tensor a (255) must match the size of tensor b (18) at non-singleton dimension 0

### ISSUE THREAD

**Issue by rianusr** [ultralytics/yolov5#3253]
After i modify data.yaml :names into my owndata with only 1 labels, 
this error  happens at step 
`scaler.step(optimizer)  # optimizer.step `
what shoud i do to fix this bug?

**Comment by rianusr** [comment]
training log about this error!

```
autoanchor: Analyzing anchors... anchors/target = 5.01, Best Possible Recall (BPR) = 1.0000
Image sizes 640 train, 640 test
Using 8 dataloader workers
Logging results to /data/codeRepository/models/exp21
Starting training for 20 epochs...

     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
  0%|                                                                                                                                                          | 0/42 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/data/codeRepository/yolov5/train.py", line 541, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "/data/codeRepository/yolov5/train.py", line 315, in train
    scaler.step(optimizer)  # optimizer.step
  File "/data/Anaconda3/lib/python3.7/site-packages/torch/cuda/amp/grad_scaler.py", line 333, in step
    retval = optimizer.step(*args, **kwargs)
  File "/data/Anaconda3/lib/python3.7/site-packages/torch/optim/lr_scheduler.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "/data/Anaconda3/lib/python3.7/site-packages/torch/optim/optimizer.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "/data/Anaconda3/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/data/Anaconda3/lib/python3.7/site-packages/torch/optim/sgd.py", line 117, in step
    nesterov)
  File "/data/Anaconda3/lib/python3.7/site-packages/torch/optim/_functional.py", line 169, in sgd
    buf.mul_(momentum).add_(d_p, alpha=1 - dampening)
RuntimeError: The size of tensor a (255) must match the size of tensor b (18) at non-singleton dimension 0
  0%|                                                                                                                                                          | 0/42 [00:06<?, ?it/s]
```

**Comment by rianusr** [comment]
And when i modiy names into 80, The error disappeared！

**Comment by glenn-jocher** [comment]
@Rianusr your data.yaml must specify the correct number of classes, and your names list must contain names for those classes. See Train Custom Data tutorial for exact steps:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)
