### ISSUE TITLE
Train VisDrone Error on Win10

### ISSUE THREAD

**Issue by nocolour** [ultralytics/yolov5#3256]
Train VisDrone Erorr in Win10
![VisDroneError](https://user-images.githubusercontent.com/6244952/118947944-6b320e00-b98a-11eb-9e09-ce22bb930760.jpg)

**Comment by glenn-jocher** [comment]
@nocolour it appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below. 


## Requirements

**Python 3.8** or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including **`torch>=1.7`**. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by nocolour** [comment]
Test 21-05-2021
- Delete the source, re-setup the environment & re clone from git 
- Update Nvidia driver and Cuda & Cudnn to 11.3
- detect.py tested no problem
- Only train.py error **
![VisDroneError](https://user-images.githubusercontent.com/6244952/119081256-337ca200-ba2e-11eb-9cb9-e8f80bcf30dd.jpg)

**Comment by nocolour** [comment]
![VisDroneError2](https://user-images.githubusercontent.com/6244952/119081442-8bb3a400-ba2e-11eb-86e8-d5f8d97abba3.png)

**Comment by nocolour** [comment]
![VisDroneError2](https://user-images.githubusercontent.com/6244952/119081512-ab4acc80-ba2e-11eb-8ff2-2bd8f685bb02.jpg)
![nvidia-sm1](https://user-images.githubusercontent.com/6244952/119081901-89057e80-ba2f-11eb-9ed1-e3becf9abcb2.jpg)

**Comment by glenn-jocher** [comment]
@nocolour CUDA OOM indicates your GPU is out of memory.

Use a smaller batch size.
