### ISSUE TITLE
Model Ensembling?

### ISSUE THREAD

**Issue by dariogonle** [ultralytics/yolov5#3259]
## ❔Question
I've seen it is possible to use model ensembling (https://github.com/ultralytics/yolov5/issues/318) but I wonder what strategy is been followed?

I've read some papers: https://www.unirioja.es/cu/joheras/papers/ensemble.pdf and https://arxiv.org/pdf/1910.13302.pdf and there are several options: Affirmative, Consensus, Unanimous or Weighted Boxes Fusion. I would like to know which one is used in YOLOv5.

Thank you.

**Comment by glenn-jocher** [comment]
@dariogonle YOLOv5 ensembling gathers detections from all sources prior to NMS.

**Comment by glenn-jocher** [comment]
Source code for YOLOv5 Ensemble() module is here:
https://github.com/ultralytics/yolov5/blob/7b863a34dcacf8b310396d0bc1021f404ec85797/models/experimental.py#L98-L111

**Comment by dariogonle** [comment]
Thank you so much.

**Comment by glenn-jocher** [comment]
@dariogonle no problem! If you run your own experiments and spot any room for improvements in the Ensemble behavior feel free to submit a PR or let us know!

**Comment by jaideep11061982** [comment]
@glenn-jocher if were to use WBF method for ensembling we should replace nms with that ?

**Comment by glenn-jocher** [comment]
@jaideep11061982 sure, you could try starting here https://github.com/ZFTurbo/Weighted-Boxes-Fusion
