### ISSUE TITLE
About Weight Initialization Technique

### ISSUE THREAD

**Issue by debparth** [ultralytics/yolov5#3261]
## ❔Question
@glenn-jocher which weights initialization technique are we using?

**Comment by glenn-jocher** [comment]
@debparth weights initialization code is here:
https://github.com/ultralytics/yolov5/blob/7b863a34dcacf8b310396d0bc1021f404ec85797/utils/torch_utils.py#L144-L154

**Comment by debparth** [comment]
@glenn-jocher Ok. Have you done few R&D in weight initialization like using Xavier/Glorot or He initialization technique or any other ones? If so then can you share some results.
