### ISSUE TITLE
runtimeerror: tensors must be cuda and dense error with weighted image selection for training

### ISSUE THREAD

**Issue by lleye** [ultralytics/yolov5#3265]
I get a cuda runtime error when doing weighted image selection in ddp mode. below is how to replicate:

`python -m torch.distributed.launch --nproc_per_node .. --image-weights` leads to runtimeerror: tensors must be cuda and dense error.

Any idea why this is so?

**Comment by lleye** [comment]
@glenn-jocher any thoughts

**Comment by glenn-jocher** [comment]
@lleye I think these two options may simply be incompatible with each other. DDP loses dataloader modification capabilities which --img-weights relies on.

If you have time you a PR with an assert to train to check for a combination of these two with an informative error message might help future users.

**Comment by glenn-jocher** [comment]
@lleye good news 😃! Your original issue may now been fixed ✅ in PR #3275. This provides improved error handling to notify the user than DDP is not compatible with the `--image-weights` training argument. To receive this update you can:
- `git pull` from within your `yolov5/` directory
- `git clone https://github.com/ultralytics/yolov5` again
- Force-reload [PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/): `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- View our updated notebooks:  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by lleye** [comment]
thanks @glenn-jocher. any plans on making this compatible. if not, do you any suggestions on easily implementable methods for extreme class imbalance in yolov5?

**Comment by glenn-jocher** [comment]
@lleye reduce your imbalance with more data from underrepresented classes.

Also there's no requirement to train DDP, --image-weights works correctly in all other use cases.
