### ISSUE TITLE
--view-img Window spam bug

### ISSUE THREAD

**Issue by sezer-muhammed** [ultralytics/yolov5#3266]
## 🐛 Bug
İf we use --view-img command in detect.py for images, it opens new window for every image.

## To Reproduce (REQUIRED)

Input:
python detect.py --img 640 --source "FILE" --view-img

Output:
tons of window (50,000 windows for my case)
![image](https://user-images.githubusercontent.com/74321576/119057273-d7d1fa80-b9d4-11eb-8ada-4f34f244e397.png)

## Expected behavior
Single window with dynamically changing image.

## Environment

 - OS: Win 10
 - GPU: RTX 3070

## Additional context
This is because of the window name. Window name is the name of the image or video. So if inputs are image it creates a new window with images name. 

```
if view_img:                
cv2.imshow(str(p), im0)                
cv2.waitKey(1)  # 1 millisecond
```

This part should be something like this, I guess.

```
if view_img:                
cv2.imshow("Detection", im0)                
cv2.waitKey(1)  # 1 millisecond
```

**Comment by glenn-jocher** [comment]
@sezer-muhammed this is the intended `--view-img` behavior. Only videos show frames. Images show images, all of them.

I might suggest you view the results directory after inference is complete rather than trying to view the 50k inference results in realtime.

**Comment by sezer-muhammed** [comment]
> @sezer-muhammed this is the intended `--view-img` behavior. Only videos show frames. Images show images, all of them.
> 
> I might suggest you view the results directory after inference is complete rather than trying to view the 50k inference results in realtime.

I'm not using that command, but it seems a bug to me.
if its intended there is no problem, thanks

**Comment by glenn-jocher** [comment]
@sezer-muhammed though we may want to impose a limit on the number of opened windows to prevent something like this. If you have time you might submit a PR with an open window count ceiling to better handle this.
