### ISSUE TITLE
Nan in  yolov5l-transformer

### ISSUE THREAD

**Issue by mujinbao** [ultralytics/yolov5#3267]
I changed the last C3 module in yolov5l to c3tr. When training to the second or third epoch, Nan appeared  in the val. Why

**Comment by glenn-jocher** [comment]
@mujinbao NaN values are caused by increasing losses due to unstable gradients caused by your architecture modifications presumably.

**Comment by Zephyr69** [comment]
Same stuff happened to me with 6.0 yolov5m. The only change to model structure is also the last c3 module in the backbone. The dataset is one for tiny object detection; I'm not sure if that's relevant to this problem but all other (non-C3TR) models trained normally.
