### ISSUE TITLE
evolve result can`t reprodeuce

### ISSUE THREAD

**Issue by flashcp** [ultralytics/yolov5#3268]
## ❔Question
hello @glenn-jocher.
I use the following command to search good hyp-paramenters, and get best metrics  and 'hyp_evolved.yaml' in 300 iters.
` python train.py --epochs 10 --data data/cbis_ddsm_all_image.yaml --weights yolov5s.pt --cfg models/yolov5s_ddsm.yaml  --cache --evolve --img-size 1280 --batch-size 10 --device 0`

But, I try to reproduce the best metrics by using hyp_evolved.yaml, I cant get it. I dont know why this is, could you give me some advices?

## Additional context
evolve configurement
`--epochs
10
--cfg
models/yolov5s_ddsm.yaml
--data
data/cbis_ddsm_all_image.yaml
--weights
yolov5s.pt
--cache-images
--evolve
--img-size
1280
--batch-size
10
--device
0
`

train configurement
`--weights
yolov5s.pt
--hyp
runs/train/evolve/hyp_evolved.yaml
--cfg
models/yolov5s_ddsm.yaml
--data
data/cbis_ddsm_all_image.yaml
--batch-size
10
--epochs
10
--device
1
--img-size
1280
--cache-images
`

**Comment by glenn-jocher** [comment]
@flashcp reproducibility of training results is not guaranteed in PyTorch and basically never occurs in practice. See https://pytorch.org/docs/stable/notes/randomness.html

**Comment by flashcp** [comment]
> @flashcp reproducibility of training results is not guaranteed in PyTorch and basically never occurs in practice. See https://pytorch.org/docs/stable/notes/randomness.html

ok, thanks
