### ISSUE TITLE
Quant aware training possible for Yolov5?

### ISSUE THREAD

**Issue by ithmz** [ultralytics/yolov5#3269]
## ❔Question
May I ask can I train yolov5 with quant-aware training?

**Comment by glenn-jocher** [comment]
@tsangz189 we don't provide QAT resources in the official repo yet, though I know there is some 3rd party support from other organizations for YOLOv5 with QAT, you might want to search around online.

**Comment by aidansmyth95** [comment]
https://github.com/gogoymh/yolov5-qat I haven't tried this yet though, looks promising

**Comment by glenn-jocher** [comment]
@aidansmyth95 thanks for sharing this resource! While we can't officially vouch for third-party projects, it's always great to see the community experimenting and extending the capabilities of YOLOv5. Just a friendly reminder to thoroughly review the code and see if it aligns with your project requirements. Happy coding! 😊
