### ISSUE TITLE
label assign in yolov5

### ISSUE THREAD

**Issue by Laughing-q** [ultralytics/yolov5#3270]
## ❔Question
Yolov5 assigns anchors of multiple grids for each target by adding offset(this seems to increase recall), but it also seems that one grid assigned to multiple targets when training. anchors of one grid will regress multiple wh, one grid will regress multiple centers.  Am I right? Does it affect training？ 

## Additional context
when I print gij after label assign, I found a lot of duplicate pairs.

**Comment by carolo44** [comment]
You can filter out the duplicate anchors, assigning an anchor to multiple targets is at least not helping the training process, but very likely to hinder it.

**Comment by Laughing-q** [comment]
> You can filter out the duplicate anchors, assigning an anchor to multiple targets is at least not helping the training process, but very likely to hinder it.

Thanks, I have already done some experiments to verify it.

**Comment by carolo44** [comment]
> > You can filter out the duplicate anchors, assigning an anchor to multiple targets is at least not helping the training process, but very likely to hinder it.
> 
> Thanks, I have already done some experiments to verify it.

any conclusion on the common datasets or your own custom datasets?

**Comment by Laughing-q** [comment]
> > > You can filter out the duplicate anchors, assigning an anchor to multiple targets is at least not helping the training process, but very likely to hinder it.
> > 
> > 
> > Thanks, I have already done some experiments to verify it.
> 
> any conclusion on the common datasets or your own custom datasets?

sorry I forgot to reply, after I filter out the duplicate anchors, recall decrease and presicion increase, but mAP dropped in total.(experiment on my custom datasets)

**Comment by carolo44** [comment]
> 

huh, that's interesting. on my custom dataset the precision drops but recall increases. Looks like this is really data-dependent..
