### ISSUE TITLE
FNETs and instance segmentation

### ISSUE THREAD

**Issue by saitarslanboun** [ultralytics/yolov5#3272]
Hi @glenn-jocher !

Just out of curiosity, did you see this paper https://arxiv.org/pdf/2105.03824v1.pdf ?

I see that you have an attempt to use Transformer self-attention with Yolov5s setting. Self attention has complexity due to matrix multplication and several linear layers for multi-head attention. 

I am just curious, whether applying 2d fourier transform after every bottleneck instead of applying self attention at the end of the backbone is a cool idea? 

Meanwhile, I am terribly waiting for the instance segmentation feature.

Kind regards,

**Comment by glenn-jocher** [comment]
@saitarslanboun thanks for the link, yes I've heard of this paper but have not had time to review. The best way to get the feature you are interested in is to submit PRs and contribute yourself!

**Comment by saitarslanboun** [comment]
Thank you @glenn-jocher ! That was the best cover of mine in 2021 :)
