### ISSUE TITLE
A method to increase the number of frames（FPS）

### ISSUE THREAD

**Issue by suiyi1420** [ultralytics/yolov5#3273]
> I deployed YOLOV5 in Jetson NANO. When the parameter "--img-size" is set to 320, I can probably get 15 frames. When I set it to 640 or higher, only 10 frames or less, but when I check the CPU usage , Found that the CPU usage is less than 50%.

> So I checked the code in the "utils" folder. In the "datasets.py" file, I found that the function "LoadStreams" lacks many other parameter settings when initializing opencv, and the value of the parameter "--img-size" is also missing Reference, so I think the value of the parameter "--img-size" is only valid for detection.

> Therefore, I tried to add part of the initial settings of opencv in the LoadStreams function, as shown below:

![微信截图_20210521162216](https://user-images.githubusercontent.com/15998309/119106304-caf2ec80-ba50-11eb-9328-e38a3bcf12d1.png)

`
cap = cv2.VideoCapture(s,cv2.CAP_V4L2)

cap.set(cv2.CAP_PROP_FRAME_WIDTH, 1280)

cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 720)

cap.set(cv2.CAP_PROP_FPS, 30)

cap.set(cv2.CAP_PROP_FOURCC, cv2.VideoWriter_fourcc('M', 'J', 'P', 'G'))`

> After adding this code, the setting of the parameter "--img-size" will become invalid, but the result is very shocking to me. At a resolution of 1280*720, I can get about 30 frames, realizing the real real-time monitoring. Previously, I could only get 5 frames at this resolution. (The highest frame rate of my USB camera is 30)

> If you are still annoyed by the frame number problem, then try to add this code and enjoy it!

**Comment by glenn-jocher** [comment]
@suiyi1420 I think you're mixing two different topics. 

- **Input image shape** can be any value, which you seem to be modifying here for a streaming source, and this will not affect inference speed.
- **Inference shape** is an argument defined by `--img-size`, and does affect inference speed.

The two are independent from each other.
