### ISSUE TITLE
Gpu missing 

### ISSUE THREAD

**Issue by johanenforcer** [ultralytics/yolov5#3274]
## ❔Question
I have made sure to check that all drivers are updated and that the correct versions of requirements are installed, nonetheless from time to time in spaces of a couple of weeks probably, the gpu goes missing and consequently only the cpu seems to be detectable. What specifically causes this? Could it perhaps be waiting too long to update the code to the current state, I don't see how that triggers this change though? The issue also seems to resolve whenever I reboot.

Thanks in advance

**Comment by glenn-jocher** [comment]
@johanenforcer I don't believe this question is related to YOLOv5, you might want to ask on PyTorch or NVIDIA forums.
