### ISSUE TITLE
Should yolov5s.yaml be higher performance than yolov3-tiny?

### ISSUE THREAD

**Issue by DennisFaucher** [ultralytics/yolov5#328]
Before submitting a bug report, please be aware that your issue **must be reproducible** with all of the following, otherwise it is non-actionable, and we can not help you:
 - **Current repo**: run `git fetch && git status -uno` to check and `git pull` to update repo
 - **Common dataset**: coco.yaml or coco128.yaml
 - **Common environment**: Colab, Google Cloud, or Docker image. See https://github.com/ultralytics/yolov5#reproduce-our-environment
 
If this is a custom dataset/training question you **must include** your `train*.jpg`, `test*.jpg` and `results.png` figures, or we can not help you. You can generate these with `utils.plot_results()`.

## 🐛 Bug

More of a question than a bug. I just trained the same set of image recognition data with yolov3-spp.cfg, yolov3-tiny3.cfg, & yolov5s.yaml. When running detect against the same .MP4, these are the performance results:

* yolov3-spp.cfg: 0.084s/frame
* yolov3-tiny3.cfg: 0.027s/frame
* yolov5s.yaml: 0.07s/frame

[Edit. Just ran detect with the default yolov5s.pt weights and performance is also 0.07s/frame.]

In my test yolov3-tiny has much higher performance. Is that expected? Thank you.

## To Reproduce (REQUIRED)

Input:
```
python3 train.py --cfg yolov3-spp.cfg --data 6chix.data
python3 train.py --cfg yolov3-tiny3.cfg --data 6chix.data --weights ''
python3 train.py --img 1280 --data ./6chix-dataset.yaml --cfg ./models/yolov5s.yaml --weights '' --batch-size 8

```

Output:
```
* yolov3-spp.cfg: 0.084s/frame
* yolov3-tiny3.cfg: 0.027s/frame
* yolov5s.yaml: 0.07s/frame
```

## Expected behavior

Expected yolov5s to be faster than yolov3-tiny

## Environment

 - OS: [e.g. Ubuntu] Ubuntu
 - GPU [e.g. 2080 Ti] NVIDIA Jetson Xavier

## Additional context

Thanks in advance

**Comment by glenn-jocher** [comment]
@DennisFaucher first of all, **do not use a bug label for questions**.

**Comment by DennisFaucher** [comment]
@glenn-jocher My options were bug or feature request. Is feature request a better location for questions? TIA.

**Comment by glenn-jocher** [comment]
@DennisFaucher comparisons are available for all models trainable with this repo (including yolov3-spp) in our readme table: https://github.com/ultralytics/yolov5#pretrained-checkpoints

For general issues you can simply raise an issue, you do not need to use one of the templates:
<img width="928" alt="Screen Shot 2020-07-08 at 9 48 01 AM" src="https://user-images.githubusercontent.com/26833433/86947125-37e2e980-c100-11ea-895a-4c29c2ef7730.png">

**Comment by DennisFaucher** [comment]
Closing as not a bug but a question.

**Comment by glenn-jocher** [comment]
@DennisFaucher maybe we should add a 'General Question' template to the 2 existing ones? This seems to happen often with people filing bug reports for questions.
