### ISSUE TITLE
best.pt weights

### ISSUE THREAD

**Issue by SyedHamza0196** [ultralytics/yolov5#3281]
What is best.pt file based on, only mAP or mAP with best precision and recall?

**Comment by glenn-jocher** [comment]
@SyedHamza0196 best.pt is saved on every new maximum fitness epoch. Fitness is defined by a weighted combination of metrics in the fitness() function in utils/metrics:
https://github.com/ultralytics/yolov5/blob/683cefead4b9f2a8d062f953a912e46e456ed6ad/utils/metrics.py#L12-L16
