### ISSUE TITLE
All label file is empty, it will break.

### ISSUE THREAD

**Issue by SpongeBab** [ultralytics/yolov5#3286]
Before submitting a bug report, please be aware that your issue **must be reproducible** with all of the following, otherwise it is non-actionable, and we can not help you:
 - **Current repo**: run `git fetch && git status -uno` to check and `git pull` to update repo
2021.5.22 latest
 - **Common dataset**: coco.yaml or coco128.yaml
custom dataset
 - **Common environment**: Colab, Google Cloud, or Docker image. See https://github.com/ultralytics/yolov5#environments
default setup by pip -r requirement.txt
If this is a custom dataset/training question you **must include** your `train*.jpg`, `test*.jpg` and `results.png` figures, or we can not help you. You can generate these with `utils.plot_results()`.

## 🐛 Bug
I meet this error:
```
train: Scanning '..\desk_VOC\train.cache' images and labels... 1800 found, 0 missing, 1800 empty, 0 corrupted: 100%|██████████| 1800/1800 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "E:\yolov5\train.py", line 550, in <module>
    train(hyp, opt, device, tb_writer)
  File "E:\yolov5\train.py", line 193, in train
    mlc = np.concatenate(dataset.labels, 0)[:, 0].max()  # max label class
  File "D:\Miniconda\envs\yolov5\lib\site-packages\numpy\core\_methods.py", line 39, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation maximum which has no identity
```
Then I check my dataset, I find my lable is all blank.I think this is because all label is empty

## Environment

![image](https://user-images.githubusercontent.com/65898238/119217561-95f89f80-bb0d-11eb-97a0-236401ef4f3b.png)

## Additional context
My label file:
![image](https://user-images.githubusercontent.com/65898238/119217606-dbb56800-bb0d-11eb-8559-80d700e60b31.png)

**Comment by glenn-jocher** [comment]
@SpongeBab to train you will need at least one object labelled in your dataset (one instance of an object labelled), though to train well you'll want thousands of labelled instances. Your training log shows you have 1800 images with 1800 labelfiles, but all of your labelfiles are empty, i.e. there is nothing to train.

**Comment by senthurram03** [comment]
In my case the files maybe in a format that is not recognizable by the algorithm. The label files were like this and hence the above issue occurred 
```
0 
2 0.448453 0.800153 0.411984 0.394625 0.453109 0.0608333 0.475609 0.0291111 0.540781 0.00152778 0.681211 0.0387639 0.701383 0.114625 0.649398 0.466347 0.530695 0.775319 0.506641 0.83325 0.478711 0.840153
```
As you can see for the class **0** there were no polylines. You have to remove them to have the correct format

**Comment by glenn-jocher** [comment]
@senthurram03 it looks like your label file contains extra numbers beyond the expected format for YOLO, which typically expects each line to represent one bounding box with the following format:

```
<class> <x_center> <y_center> <width> <height>
```

The values should be normalized between 0 and 1, relative to the image width and height. The class value should be an integer representing the object class.

From your example, it seems there are additional numbers after the first five expected values. If these extra numbers are not meant to represent additional bounding boxes, they should be removed to comply with the expected format.

Please ensure that each label file strictly follows the YOLO format. If you have polylines or other shapes, you'll need to convert them into bounding boxes or another supported format before training YOLOv5. If you need further assistance, please refer to our documentation or consider posting a detailed question on the repo's issues page with the correct context and information.
