### ISSUE TITLE
why is the bounding box outside of the inferred image?

### ISSUE THREAD

**Issue by lity** [ultralytics/yolov5#3287]
## ❔Question
I inferred an image which size is 640x640, and got the result like this: 
{'xmin': 576.0, 'ymin': 226.5, 'xmax': 640.0, 'ymax': 435.5, 'confidence': 0.8759765625, 'class': 0, 'name': 'something'}

Notice that xmax is 640, x index of the image is in the range of 0~639 in this case.

Why bounding box is outside of the image?
Does it mean  that the detected object just right aligns the image edge 577 ~ 639 (bounding box 576 ~ 640) ?

So when I draw bounding boxes in my own dataset, should  I draw bbox 1 pixel bigger than object?

Thx for your explanation.

**Comment by glenn-jocher** [comment]
@lity the clip_coords() function handles box clipping here:
https://github.com/ultralytics/yolov5/blob/a039b7796dc495a5e5ec5ac5ba60cbecfb8b3c60/utils/general.py#L398-L404

We use the current implementation as we see a slight mAP drop when clipped to [0, dim-1]. You can modify the function though and experiment yourself.

**Comment by lity** [comment]
> @lity the clip_coords() function handles box clipping here:
> https://github.com/ultralytics/yolov5/blob/a039b7796dc495a5e5ec5ac5ba60cbecfb8b3c60/utils/general.py#L398-L404
> 
> We use the current implementation as we see a slight mAP drop when clipped to [0, dim-1]. You can modify the function though and experiment yourself.

Thanks for your reply. I guess I can just simply modify the output from img_size to img_size - 1.

This still  confuses me that when I draw bboxes in my own dataset, should the bboxes be same size as the objects or 2 pixels bigger than the objects(outside of the objects).  For instance, the object is 100 x 100, which bbox size is better 100 x 100 or 102 x 102?

**Comment by glenn-jocher** [comment]
@lity in your example 100x100 would be best. When minimizing losses the minimum loss will be at zero deviation between the label and the prediction.

**Comment by lity** [comment]
> @lity in your example 100x100 would be best. When minimizing losses the minimum loss will be at zero deviation between the label and the prediction.

I got it, thank you. 👍👍👍
