### ISSUE TITLE
Train issue.Is this normal?

### ISSUE THREAD

**Issue by SpongeBab** [ultralytics/yolov5#3291]
## ❔Question
@glenn-jocher Hi,Is this normal?
When I train,I get this train_batch:
![train_batch0](https://user-images.githubusercontent.com/65898238/119245981-2daeca00-bbb0-11eb-9f87-ab9526a5baf9.jpg)
![train_batch1](https://user-images.githubusercontent.com/65898238/119245984-30a9ba80-bbb0-11eb-8582-44e9af568996.jpg)
![train_batch2](https://user-images.githubusercontent.com/65898238/119245986-32737e00-bbb0-11eb-9398-23ec2cfd7575.jpg)

You can see the ground truth bounding box is abnormal.And my ap is very low.
```
     Epoch   gpu_mem       box       obj       cls     total    labels  img_size
     73/99     5.01G   0.08028    0.1058         0    0.1861       131       800: 100%|██████████| 900/900 [04:33<00:00,  3.29it/s]
               Class      Images      Labels           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 50/50 [00:08<00:00,  5.94it/s]
                 all         200        5876       0.143      0.0926      0.0282      0.0123
```

How can I solve it?
## Additional context
I am sure that my label txt is correct,and I redraw the ground truth BBox, you can see :
![02_20201017135000_2](https://user-images.githubusercontent.com/65898238/119246099-39e75700-bbb1-11eb-8c0d-5b3b826ba3d2.jpg)

**Comment by glenn-jocher** [comment]
@SpongeBab I can't comment on your custom dataset labels, but I can tell you that what you see in your train_batch*.jpg images is exactly what is used for training. Therefore if you aren't happy with those images you should fix your labels.

**Comment by SpongeBab** [comment]
@glenn-jocher oh,yes.Thanks for your kind reply.I found that my label was generated incorrectly.I will fix it.
