### ISSUE TITLE
the newest version cannot load webcam by detect

### ISSUE THREAD

**Issue by TT568** [ultralytics/yolov5#3292]
https://github.com/ultralytics/yolov5/commit/19100ba00709243976b1a31033be019816496cbd

message 
```
Fusing layers... 
Model Summary: 224 layers, 7266973 parameters, 0 gradients
1/1: 0...  success (-1 frames 640x480 at 30.00 FPS)

Results saved to runs/detect/exp6
Done. (0.000s)
```

**Comment by glenn-jocher** [comment]
@li26338710 good news 😃! Your original issue may now be fixed ✅ in PR #3295.  To receive this update you can:
- `git pull` from within your `yolov5/` directory
- `git clone https://github.com/ultralytics/yolov5` again
- Force-reload [PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/): `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- View our updated notebooks:  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
