### ISSUE TITLE
为什么模型训练一张图片，和一个类别，不能【拟合数据】，MAP始终没办法提高

### ISSUE THREAD

**Issue by jingenyan** [ultralytics/yolov5#330]
如下图

![image](https://user-images.githubusercontent.com/29670226/86991185-038b2e00-c1d1-11ea-81c4-e74dc80df0ab.png)

训练后完全检测不出来，为什么拟合不了

**Comment by x2ss** [comment]
我也和你有一样的问题，不知道你解决没有，我也是训练自己的数据完全检测不出来

**Comment by x2ss** [comment]
楼主，我之前一直也是训练不出来，无意中看到一个csdn上的https://blog.csdn.net/mary_0830/article/details/107014497这个链接，里面强调了：“注意！！ nc： 15 后面的空格仅有一个”。
我看了一下我的配置文件，果然有不止一个空格，我把这个地方多余的空格删了，就好了，还没有改回去再测试一下是不是这个问题，你可以试一下，希望能帮你解决这个问题！

**Comment by x2ss** [comment]
楼主，我测试了几次，觉得这种问题还是训练的epoch不够多。。。
