### ISSUE TITLE
Single machine multi-card

### ISSUE THREAD

**Issue by jywznb** [ultralytics/yolov5#332]
Single machine multi-card training error

world_size=1
  "Single-Process Multi-GPU is not the recommended mode for "
RuntimeError: Model replicas must have an equal number of parameters.

world_size=4
computer will Stuck

**Comment by glenn-jocher** [comment]
Probably an environment issue. You can use one of our working environments:
## Reproduce Our Environment

To access an up-to-date working environment (with all dependencies including CUDA/CUDNN, Python and PyTorch preinstalled), consider a:

- **GCP** Deep Learning VM with $300 free credit offer: See our [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Google Colab Notebook** with 12 hours of free GPU time. <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)

**Comment by Pluto1314** [comment]
@jywznb Hi, I also have the same problem,  are you solve this issue?
