### ISSUE TITLE
Have you tried to implement the YOLT algorithm?

### ISSUE THREAD

**Issue by zxq309** [ultralytics/yolov5#3323]
## ❔Question
YOLT is an extension of the YOLO v2 framework that can evaluate satellite images of arbitrary size，the paper name is：You Only Look Twice: Rapid Multi-Scale Object Detection In Satellite Imagery

**Comment by glenn-jocher** [comment]
@XiangqingZhang no we haven't looked into that algorithm. For satellite imagery detection you might want to see the  Ultralytics xView YOLOv3 repository which uses a sliding window for inference on any size image.
https://github.com/ultralytics/xview-yolov3

<img src="https://github.com/ultralytics/xview-yolov3/blob/master/output/5.jpg?raw=true" width="1000">
