### ISSUE TITLE
how to save pt in each epoch

### ISSUE THREAD

**Issue by SISTMrL** [ultralytics/yolov5#3324]

**Comment by dk-teknologisk-mlnn** [comment]
it already does this by itself under runs/train/exp#/weights.
you get both the best and current pt.

**Comment by Yassine-Fak** [comment]
I think only the best and the last one

**Comment by Yassine-Fak** [comment]
I think only the best and the last one, not every model will be saved

**Comment by dk-teknologisk-mlnn** [comment]
ah you want to keep them all. --save_period 1 makes wandb logger save them all. 

otherwise to do it in runs/train/exp you can update the filename in last with epoch number.
![image](https://user-images.githubusercontent.com/30144796/119493723-ca17ce80-bd60-11eb-8796-071a092154bb.png)
