### ISSUE TITLE
Is it possible to set different bbox for each class?

### ISSUE THREAD

**Issue by Choikyungho9** [ultralytics/yolov5#3326]
## ❔Question
I created a dataset with 3 classes. But I want to do different behaviors for each class. For example, when an airplane is recognized, only simple text without a bounding box is displayed.

So I looked at detect.py's code, but I'm not sure how to fix it.

Is it possible to do different image processing for each class of my personal dataset?

**Comment by glenn-jocher** [comment]
@Choikyungho9 sure, you can customize your prediction results plotting here:
https://github.com/ultralytics/yolov5/blob/aad99b63d6ac63278021a66f8a096e5232ed24b0/detect.py#L102-L116

**Comment by Choikyungho9** [comment]
@glenn-jocher 

Thank you. Let's modify the code to perform different image processing for each class.
