### ISSUE TITLE
Test with custom IOU, i.e., mAP@0.3

### ISSUE THREAD

**Issue by floriculture** [ultralytics/yolov5#3329]
Hello, 
I wanted to figure it myself but I failed. Could you please solve my question? To output mAP@0.3

**Comment by glenn-jocher** [comment]
@floriculture we don't support arbitrary metrics but you can code these yourself of course in test.py and metrics.py.

**Comment by floriculture** [comment]
@glenn-jocher  Thank you！
I found ap50 in test.py and metrics.py. The threshold you use is 0.5. I want to change it to 0.3 but failed. Could you help me?

**Comment by glenn-jocher** [comment]
@floriculture you can replace the 0.5 metric with a 0.3 value here:
https://github.com/ultralytics/yolov5/blob/aad99b63d6ac63278021a66f8a096e5232ed24b0/test.py#L79

**Comment by floriculture** [comment]
@glenn-jocher  Thank you for your help!  I'll try it now.
