### ISSUE TITLE
TPU Training/XLA Support

### ISSUE THREAD

**Issue by Tylersuard** [ultralytics/yolov5#333]
Hello.  I find your tutorials very helpful, and I'm glad you have decided to switch to Pytorch instead of Tensorflow.

I'm looking for an easy way to train Yolo v5 using TPU's on a Colab notebook.  With GPU it takes 24 hours to do around 3000 epochs, which I understand is a typical number of epochs for training a Yolo model.

Would you mind posting a tutorial for making the training TPU-compatible?

**Comment by glenn-jocher** [comment]
@Tylersuard thanks! I don't have any experience with TPUs, and from my understand XLA in PyTorch requires significant rewrite of code to implement. Additionally training in Colab is CPU and Hard Drive constrained, not GPU constrained, so these facts combined with my extremely busy schedule makes it impossible to do this anytime soon.

If you'd like to take the lead on updating the code and writing a tutorial that would be great! I'm sure more people are interested, and in this case the usability would extend to true deep learning environments with TPU access like GCP.

**Comment by glenn-jocher** [comment]
@Tylersuard I've added a TODO label to this as I think it's a good project and in the interest of the community to always have more backend options available for training. I'm assigning you to lead the development! All I can do is point you in the right direction at the moment:
https://pytorch.org/xla/release/1.5/index.html

My only recommendations are to try to keep any changes to the codebase as clean and minimal as possible when you submit a PR. Thank you!

**Comment by glenn-jocher** [comment]
Oh, and one last item, we have a suite of unit tests we run on PRs and commits, this will validate your changes to ensure you haven't broken any existing functionality. An exit code of 0 is passing.

```bash
# YOLOv5 Unit Tests
git clone https://github.com/ultralytics/yolov5 && cd yolov5
export PYTHONPATH="$PWD" # to run *.py. files in subdirectories
pip install -qr requirements.txt onnx
python3 -c "from utils.google_utils import *; gdrive_download('1n_oKgR81BJtqk75b00eAjdv03qVCQn2f', 'coco128.zip')" && mv ./coco128 ../
for x in yolov5s yolov5m yolov5l yolov5x # models
do
  python train.py --weights $x.pt --cfg $x.yaml --epochs 4 --img 320 --device 0  # train
  for di in 0 cpu # inference devices
  do
    python detect.py --weights $x.pt --device $di  # detect official
    python detect.py --weights weights/last.pt --device $di  # detect custom
    python test.py --weights $x.pt --device $di # test official
    python test.py --weights weights/last.pt --device $di # test custom
  done
  python models/yolo.py --cfg $x.yaml # inspect
  python models/export.py --weights $x.pt --img 640 --batch 1 # export
done
```

**Comment by Tylersuard** [comment]
Shoot, I shouldn't have said anything.

I'll see what I can do.

**Comment by Borda** [comment]
a solution could be to use [PyTorch-lightning](https://github.com/PytorchLightning/pytorch-lightning) which does this [TPU backend](https://pytorch-lightning.readthedocs.io/en/latest/tpu.html) duty for you...

**Comment by tianyu-sz** [comment]
👍

**Comment by LogicNg** [comment]
Any updates?

**Comment by glenn-jocher** [comment]
@Borda we've had this TPU TODO open for a while, curious to see if the new lightning module might be a solution to this.

**Comment by Borda** [comment]
yes, that shall be supported with LightningLite :tada:

**Comment by mauriceackel** [comment]
Is there any active development regarding this? Also, given that there seems so be some activity in this issue, you might want to consider reopening it..

**Comment by glenn-jocher** [comment]
@mauriceackel maybe. It's possible we might be able to integrate a backend package like lightning lite or torch_xla. We are not actively working on this right now, but the landscape may be improving for being able to provide TPU support.

Of course, the responsibility for this feature should really rest with the pytorch team themselves rather than their downstream users.

**Comment by Borda** [comment]
> Is there any active development regarding this? Also, given that there seems so be some activity in this issue, you might want to consider reopening it..

I am going to draft it this week :rabbit:

**Comment by glenn-jocher** [comment]
@Borda awesome!

**Comment by mauriceackel** [comment]
As a side not: I just fiddled around a bit by adding the pytorch_xla lib to the existing training.py, creating a device from it and overwriting the device passed in the `run` method. When I try to run training on Colab, I run in an error:

```
RuntimeError: Error while lowering: f32[3,3,2]{2,1,0} xla::cast, type=f32, dtype=Float, stype=Half
Error: torch_xla/csrc/convert_ops.cpp:83 : Unsupported XLA type 10
```

which might have to do with [this issue](https://github.com/pytorch/xla/issues/2917), that indicates that amp and pytorch XLA is not compatible?!

Take this with a grain of salt though as I have very little experience with all those technologies...

**Comment by wmcnally** [comment]
@Borda @mauriceackel any updates on TPU compatibility?

**Comment by Borda** [comment]
@aniketmaurya is preparing a draft with [PL Lite](https://pytorch-lightning.readthedocs.io/en/stable/starter/lightning_lite.html) that shall address it... :)

**Comment by jsrimr** [comment]
@Borda  Any updates? I am planning to start working on PL implementations. If you share your draft, it'd be a lot of help!

**Comment by k-kedzierski** [comment]
Hi,
Any updates on this? It would be amazing to utilise GCloud TPU Research machines for training YOLO.

**Comment by glenn-jocher** [comment]
@k-kedzierski I don't have any updates, but deploying YOLOv5 on GCloud TPU Research machines would indeed be an amazing use case! Let me know if you need any assistance.

**Comment by Borda** [comment]
It took me a while to get to it but exploring the fusion in https://github.com/Borda/lightning-YOLOs
