### ISSUE TITLE
Whats the difference between this models?

### ISSUE THREAD

**Issue by RonDudkman** [ultralytics/yolov5#335]
Hey,
I see in that link that there are different types of pre-trained models like yolov5x yolov5m and more..
https://drive.google.com/open?id=1Drs_Aiu7xx6S-ix95f9kNsA6ueKRpN2J
But there is also a hub directory which containes "yolov5x-fpn" model which I cant find any info about it.. 
Sorry if it isnt the right place to ask about it,
And thanks.

**Comment by glenn-jocher** [comment]
@RonDudkman FPN stands for feature pyramid network. Models in models/hub are experimental or historical models which have been archived for preservation.
