### ISSUE TITLE
OpenCV couldn't read tile splitted file

### ISSUE THREAD

**Issue by pikachu28** [ultralytics/yolov5#3356]
## Question ?

My input video is splitted into tiles (2x2). On running  "python detect.py --source Videos/test_tile_lost.mp4" command I am getting an error message saying "OpenCV: Couldn't read movie file "/Users/usr/Desktop/yolov5-master/Videos/test_tile_lost.mp4". 

Is there anyway to remove this error and read the file?

<img width="566" alt="Screenshot 2021-05-26 at 10 26 47 PM" src="https://user-images.githubusercontent.com/62153950/119702107-b8bee700-be72-11eb-8a7b-04f560aa3a3d.png">

**Comment by glenn-jocher** [comment]
@pikachu28 you might want to raise this issue on the opencv repo, as this is mostly unrelated to YOLOv5.
