### ISSUE TITLE
Mosaic augmentation and normalization

### ISSUE THREAD

**Issue by yannclaes** [ultralytics/yolov5#3358]
## ❔Question
Hi, I've read that YOLOv5 implemented mosaic augmentation, however I cannot seem to find where it performs so. I have looked into ```yolo.py``` but only saw scales and flips.

Also, do you perform any image normalization before feeding it into the backbone? If so, what are the mean and std vectors being used?

**Comment by glenn-jocher** [comment]
@yannclaes see the YOLOv5 trainloader here in datasets.py:
https://github.com/ultralytics/yolov5/blob/407dc5008e47b1aad5ce69f0c91b4f1ec321dd7f/utils/datasets.py#L347

Mosaics are created here:
https://github.com/ultralytics/yolov5/blob/407dc5008e47b1aad5ce69f0c91b4f1ec321dd7f/utils/datasets.py#L674-L727

**Comment by yannclaes** [comment]
Thanks! So it doesn't seem like you are performing image normalization before processing them into the model, does it?

**Comment by glenn-jocher** [comment]
@yannclaes images are rescaled from 0-255 to 0-1, but no they are not normalized (zero mean unity variance).

**Comment by doo5643** [comment]
> @yannclaes images are rescaled from 0-255 to 0-1, but no they are not normalized (zero mean unity variance).

@glenn-jocher Why didn't you add zero mean unity variance, which is commonly used in other training scripts? For example, mean = [0.485, 0.456, 0.406] and std = [0.229, 0.224, 0.225] in Imagenet case.

**Comment by glenn-jocher** [comment]
@doo5643 doesn't help. If you find otherwise though please let us know.
