### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'T'

### ISSUE THREAD

**Issue by ltc576935585** [ultralytics/yolov5#336]
Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
  0%|          | 0/16551 [00:06<?, ?it/s]
Traceback (most recent call last):
  File "/home/lts/PycharmProject/yolov5/train.py", line 396, in <module>
    train(hyp)
  File "/home/lts/PycharmProject/yolov5/train.py", line 252, in train
    loss, loss_items = compute_loss(pred, targets.to(device), model)
  File "/home/lts/PycharmProject/yolov5/utils/utils.py", line 426, in compute_loss
    tcls, tbox, indices, anchors = build_targets(p, targets, model)  # targets
  File "/home/lts/PycharmProject/yolov5/utils/utils.py", line 525, in build_targets
    j, k = ((gxy % 1. < g) & (gxy > 1.)).T
AttributeError: 'Tensor' object has no attribute 'T'

**Comment by glenn-jocher** [comment]
@ltc576935585 your environment is not correct (torch is old), and your code is out of date as well. Update both. You can use one of our working environments as well:
## Reproduce Our Environment

To access an up-to-date working environment (with all dependencies including CUDA/CUDNN, Python and PyTorch preinstalled), consider a:

- **GCP** Deep Learning VM with $300 free credit offer: See our [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Google Colab Notebook** with 12 hours of free GPU time. <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)

**Comment by world2025** [comment]
@ltc576935585 你好，请问你解决了这个问题吗？是python版本问题还是torch版本问题呢，我也出现这个问题了，我的python版本是3.6.8，torch版本是1.1.0

**Comment by dfy888** [comment]
> torch版本是1.1.0

应该是pytorch版本太低了

**Comment by MitraTj** [comment]
I use python 3.7 and cuda 9.0. 
So, how to upgrade pytorch from 1.1.0?
