### ISSUE TITLE
How to run YOLOv5 on multiple images and save predictions to a txt file?

### ISSUE THREAD

**Issue by soowoong0329** [ultralytics/yolov5#3361]
## ❔Question

I'm wondering if there is a way to get predictions for a batch of images, say from a given directory, and save the names of detected classes to a txt file? I think it should be possible but I'm unfamiliar with YOLOv5, so any advise will be much appreciated!
## Additional context
I want to save the classified image to txt file like 0 or 1(labeling number) :)

**Comment by zeyad-mansour** [comment]
That can be achieved with pandas. 
![image](https://user-images.githubusercontent.com/45726273/119760658-61bc1080-be78-11eb-92c1-5070ef5f430b.png)

**Comment by glenn-jocher** [comment]
@soowoong0329 I would read the README:
https://github.com/ultralytics/yolov5#inference
