### ISSUE TITLE
yolov5 detect with 2 gpus

### ISSUE THREAD

**Issue by wjassim** [ultralytics/yolov5#3367]
## ❔Question

Sorry if the question has been asked before but I was wondering how to use 2 GPUs to speed up yolo detection especially for high resolution images (8k). I am using 

import torch
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')
results = model('high resolution image path')

Thanks a million

**Comment by glenn-jocher** [comment]
@wjassim good question. There's no builtin automatic multi-GPU inference solution other than to load multiple models per GPU and run inference in seperate threads, i.e., in a dataloader style solution:

```python
model0 = torch.hub.load('ultralytics/yolov5', 'yolov5s', device=0)
model1 = torch.hub.load('ultralytics/yolov5', 'yolov5s', device=1)

Thread0 = Thread(target=model0, args=([imgs0]), daemon=True)
Thread1 = Thread(target=model1, args=([imgs1]), daemon=True)

Thread0.start()
Thread1.start()

```

**Comment by wjassim** [comment]
@glenn-jocher oh I see. Thank you for your reply. Maybe the input image can be divided into two halves and adopt your approach to treat each half with a single gpu spearplay before stitching the resultant halves with their detections back into a single image. Does that sound correct?

**Comment by glenn-jocher** [comment]
@wjassim sure, that's the tiling or sliding window approach for large images. I've not seen it applied with multi-GPU before but it might be possible.

**Comment by wjassim** [comment]
Thank you for your kind help @glenn-jocher. Is it possible to rerun results from Thread0 or Thread1 so we can do results.render()[0] etc.? Sorry for disturbing you again.
