### ISSUE TITLE
how can i save custom labeled name in txt file ?

### ISSUE THREAD

**Issue by soowoong0329** [ultralytics/yolov5#3372]
## ❔Question

```
Fusing layers... 
Model Summary: 476 layers, 87218881 parameters, 0 gradients, 217.2 GFLOPS
image 1/1 /content/test/images/agri_0_6652_jpeg.rf.cb83c28fe8b7c6073c6e9a75a35073cd.jpg: 416x416 1 weed, Done. (0.014s)
Done. (0.019s)
```
i just want save 'weed' in txt 

thanks!

**Comment by glenn-jocher** [comment]
@soowoong0329 try `python detect.py --save-txt`

**Comment by soowoong0329** [comment]
> @soowoong0329 try `python detect.py --save-txt`

thank you for your comment!

i tried ,but it couldn't save :(

**Comment by glenn-jocher** [comment]
@soowoong0329 `--save-txt` operates correctly.

<img width="1747" alt="Screenshot 2021-05-28 at 11 46 29" src="https://user-images.githubusercontent.com/26833433/119965274-5ec13d00-bfaa-11eb-8266-3e13b6f695c2.png">
