### ISSUE TITLE
wandb and single class training

### ISSUE THREAD

**Issue by brysd** [ultralytics/yolov5#3374]
## ❔Question
Hi, I'm having a bit of trouble trying to understand how single class training with the --single-cls flag actually works.  
Suppose I have still 4 different classes in my dataset with hence 4 different classes occurring in the annotations.  
Will the single-cls flag then train actually the model for class 0 or treat all of them as single class and do you need to make a subselection of your data within the dataloader? What are the actual end results of training?  
Or is it better to provide a data.yaml file with a single class and provide only images with annotations for that particular class?  
And how does this comply to wandb logging? I saw that for single-cls flag the label is generated as 'item' when uploading datasets to wandb instead of using the class name as specified in the data.yaml file.

Thanks for the great work by the way. I cannot imagine the amount of work already put into this open source project.

**Comment by glenn-jocher** [comment]
@brysd single class training has nothing to do with W&B. 

Single class training with the --single-cls flag trains any multi-class dataset as a single class. All instances are grouped togethor into a single class 0.

**Comment by brysd** [comment]
wow that was fast feedback!  
ok, that also explains why the labels are compacted to 'item' in W&B when using the W&B flags.  
So basically the correct approach to train a single class is by having a single class annotation set and nc=1 with appropriate class labels in the corresponding configuration files (data.yaml and custom_yolo.yaml for instance).  

So if I understand correctly --single-cls could be used for instance to train bus/car/bicycle etc in a single class like e.g. vehicle.
Correct?

**Comment by glenn-jocher** [comment]
@brysd --single-cls can be used for any purpose. It will aggregate all of the classes in a multi-class dataset into a single class with name 'item'.

**Comment by brysd** [comment]
ok thx a lot for the clarifications!
