### ISSUE TITLE
Half-precision training support

### ISSUE THREAD

**Issue by slimwangyue** [ultralytics/yolov5#3377]
## 🚀 Feature

Support more efficient data types in train.py, i.e., FP16 and TF32, to boost the training speed.

## Motivation

Training speed is important for the developers to test new ideas. However, training yolov5s on 8 A100 GPUs (40G) with batch size 512 using DDP still needs 11mins for an epoch (I'm not sure whether it is reasonable since I'm using my company's cluster and have little experience on it). It would be great if we can boost the training speed using FP16 or TF32.

## Pitch

Setup a hyper-parameter to control whether to adopt quantization training.

## Additional context

Some links may be useful:

[this](https://pytorch.org/docs/stable/notes/cuda.html#tensorfloat-32-tf32-on-ampere-devices) mentions TF32 supported already, but I did not see the training speed difference between `allow_tf32 = False` and  `allow_tf32 = True`
[this](https://pytorch.org/docs/stable/amp.html) mentions amp developed by PyTorch

**Comment by glenn-jocher** [comment]
@slimwangyue I'm not sure what TF32 is, but YOLOv5 uses Automatic Mixed Precision (AMP) training by default already:
https://github.com/ultralytics/yolov5/blob/ba6f3f974bfc4a2968964dbe5eedea73c9f5efcb/train.py#L301-L303

Without knowing what dataset you are training on and which settings you are using it's not possible to say whether 11 minutes is reasonable or not for an epoch.

YOLOv5s on COCO with default settings and --batch 64 trains in 11/min per epoch on 1 A100.
https://wandb.ai/glenn-jocher/ghost/runs/5as5mm7v/logs?workspace=user-glenn-jocher
