### ISSUE TITLE
The drawing code ‘plots.py’ appears to fix the confidence ‘conf-thres’

### ISSUE THREAD

**Issue by ddlBoJack** [ultralytics/yolov5#3381]
## 🐛 Bug
The drawing code ‘plots.py’ appears to fix the confidence ‘conf-thres’ to 0.25, which is unreasonable. 

In line 160 of ‘yolov5-master/utils/plots.py’:
```python
for j, box in enumerate(boxes.T):
    cls = int(classes[j])
    color = colors[cls % len(colors)]
    cls = names[cls] if names else cls
    if labels or conf[j] > 0.25:  # 0.25 conf thresh
        label = '%s' % cls if labels else '%s %.1f' % (cls, conf[j])
        plot_one_box(box, mosaic, label=label, color=color, line_thickness=tl)
```

## Expected behavior
To be  adjustable.

**Comment by glenn-jocher** [comment]
@ddlBoJack hi thanks for submitting a feature request! The fastest way to get your feature request into code is to submit a PR directly with the updates you would like to see.
