### ISSUE TITLE
ONNX Output format

### ISSUE THREAD

**Issue by andrzejom** [ultralytics/yolov5#3387]
## ❔Question
I have a question regarding the output that the converted model generates. When I inspect the model in netron looks like this:
https://imgur.com/yzGe39b
The last layer outputs the values into a Tensor of a size 1x25200x8. What does this vector contain? I'm looking into getting the values of Bounding boxes for detected classes however it seems a bit confusing. The model has 3 classes and the output from the last layer looks like this
https://imgur.com/LDTCPfR
It doesn't make a lot of sense to me. Perhaps someone could enlighten me
## Additional context
ONNX 1.9.0
Torch 1.8.1

**Comment by leoll2** [comment]
It's the output of the [Detect](https://github.com/ultralytics/yolov5/blob/fdbe527dc02f6f8891a1fd0baa3c5638ed5f53a4/models/yolo.py#L46) layer.

1 -> batch size
25200 -> number of predictions
8 -> x y w h objectness conf_cls1 conf_cls2 conf_cls3

You probably want to apply NMS to the predictions, which you have to apply as a post-processing stage because it's not part of the exported onnx model.

**Comment by iperov** [comment]
export to onnx does not contain  Detect layer
and the model output 1,3,80,80,16

so how to interpret these values without Detect layer on pure python?

**Comment by andrzejom** [comment]
If you choose to export model without detect layer it is indeed true that you will end up with the raw output ' 1,3,80,80,16 '. In this case you need to write your extra detect layer on top over it

**Comment by iperov** [comment]
> you need to write your extra detect layer on top over it

are you serious ?

**Comment by iperov** [comment]
who want to dig into that dirty code and write DetectLayer from scratch?

why you don't provide pure python/numpy code to process raw output from onnx model ?

**Comment by andrzejom** [comment]
But why you want to process raw output in the first place? You can use predefined detector with the architecture

**Comment by iperov** [comment]
because I want to use onnx model where pytorch will not be used

**Comment by iperov** [comment]
did you hear about simplicity and minimalism? 
It is not about Yolo repositories :D

**Comment by iperov** [comment]
nevermind, I investigated the code and writing the layer

**Comment by glenn-jocher** [comment]
ONNX exports include Detect() layer.

**Comment by PaginDm** [comment]
> nevermind, I investigated the code and writing the layer

So I have the same problem. I'm trying to write custom postprocessing for native 1,3,80,80,16 layer, but WTF. This output is different from YOLOv3 in Tensorflow implementations for example. Therefore my boxes are wrong. Can you share Detect-layer implementation?

**Comment by iperov** [comment]
only the code of Detect Layer will not help.
I changed internal code of the repo to export right onnx model which works without warnings and error at max speed.

it will be shared with DeepFaceLive release.

**Comment by AdrianOverture** [comment]
> ONNX exports include Detect() layer.

I  exported a yolov5s trained with a custom dataset using the export.py script. But I cannot manage to export it with the Detect layer. How can I do it? @glenn-jocher

**Comment by glenn-jocher** [comment]
@AdrianOverture exported models automatically include detect layer.

**Comment by AdrianOverture** [comment]
> @AdrianOverture exported models automatically include detect layer.

I don't understand then how to use the NMS. When I use in inference the first element in the output list is (31, 4032, 6). But I am expecting smth like (31, 300, 6)

**Comment by mooha1999** [comment]
@glenn-jocher 
Does the output of the onnx model requires NMS?

**Comment by glenn-jocher** [comment]
@mooha1999 yes, though there is a PR open to optionally pipeline ONNX NMS in https://github.com/ultralytics/yolov5/pull/7736

**Comment by triple-mu** [comment]
> @glenn-jocher onnx模型的输出需要NMS吗？

Now pr #7736 allows the exported onnx graph to support TensorRT parsing and adds NMS functionality by adding the registration module of the TensorRT plugin. Note that it is only valid for TensorRT, onnxruntime cannot use the onnx exported by #7736

**Comment by glenn-jocher** [comment]
@triple-Mu got it
