### ISSUE TITLE
Test with custom IOU, i.e., mAP@0.5-0.75

### ISSUE THREAD

**Issue by TaoXieSZ** [ultralytics/yolov5#339]
Hi Glen,

The Kaggle Wheat compete are evaluate with mAP@0.5-0.75. I wanted to figure it myself but I failed. Could you please solve my question? To output mAP@0.5-0.75?

Thanks.

**Comment by glenn-jocher** [comment]
@ChristopherSTAN yes you can find this here. On L170 `ap` is a matrix of AP's of size 80,10 for COCO for example. The second dimension has the AP values at the various thresholds from 0.5 to 0.95. You can select the thresholds you are interested in there.

https://github.com/ultralytics/yolov5/blob/2110f5ee89c6a9475f3fe760a6abd36ff041deab/test.py#L166-L175

**Comment by TaoXieSZ** [comment]
@glenn-jocher I see 10 elements in 2nd dimension of `s`. I assume that there will be ten elements representing 0.5, 0.55, 0.6 ... 0.95. Am I right?
https://github.com/ultralytics/yolov5/blob/e16e9e43e1b4b8f9b9819fe81d537c00ec6d606e/utils/utils.py#L224

**Comment by glenn-jocher** [comment]
@ChristopherSTAN yes exactly! So for example if `ap` is nx10 then these should be right:

- mAP@0.5: `ap[:, 0]`
- mAP@0.75 `ap[:, 6]`
- mAP@0.5:0.75 `ap[:, :7].mean(1)`
- mAP@0.5:0.95 `ap.mean(1)`

**Comment by TaoXieSZ** [comment]
@glenn-jocher Thank you! You really are my anchor of Pytorch Learning!

**Comment by glenn-jocher** [comment]
@ChristopherSTAN by the way, **very important** to note that the YOLOv5 repo mAP calculation consistently under-estimates mAP when compared to pycocotools. I don't know why this is, it's a bit of an open issue. So for example if  you see mAP@0.5=0.60 and mAP@0.5:0.95=0.40 self reported here using test.py the pycocotools equivalent will typically report maybe 0-2% higher, perhaps mAP@0.5=0.61 and mAP@0.5:0.95=0.41

EDIT: I'd be very interested to know if the Kaggle mAP result is similarly higher than what we self report. Please update with more info if you manage to compare.

**Comment by JunHyungKang** [comment]
@glenn-jocher 
For mAP@0.75, it seems that the correct value is `ap[:, 5]`
Is it right?

**Comment by glenn-jocher** [comment]
@JunHyungKang yes that's correct.

**Comment by ryrd** [comment]
hi, answer above explained that ap[:, 0] will calculate mAP@0.5, but can i calculate mAP@0.25? how?
