### ISSUE TITLE
How can I save classified image without exp???

### ISSUE THREAD

**Issue by soowoong0329** [ultralytics/yolov5#3393]
## ❔Question
I want to save classifed image without exp folder !

for example , I just want to save classified image and labels in 'runs/detect/'

not increment folder !

**Comment by glenn-jocher** [comment]
@soowoong0329 you can specify logging directory using the `--project` and `--name` arguments in train.py, test.py, detect.py. To prevent incrementing you can pass the `--exist-ok` flag.
https://github.com/ultralytics/yolov5/blob/fdbe527dc02f6f8891a1fd0baa3c5638ed5f53a4/detect.py#L169-L171

**Comment by soowoong0329** [comment]
> @soowoong0329 you can specify logging directory using the `--project` and `--name` arguments in train.py, test.py, detect.py. To prevent incrementing you can pass the `--exist-ok` flag.
> https://github.com/ultralytics/yolov5/blob/fdbe527dc02f6f8891a1fd0baa3c5638ed5f53a4/detect.py#L169-L171

Thank you for the comment ! It was a great help. :)
