### ISSUE TITLE
export model

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#3397]
########################################
input name images
input shape [1, 3, 512, 832]
input type tensor(float) 

output name: 799
output shape: [1, 26208, 8]
output type: tensor(float) 

output name: 524
output shape: [1, 3, 64, 104, 8]
output type: tensor(float) 

output name: 622
output shape: [1, 3, 32, 52, 8]
output type: tensor(float) 

output name: 720
output shape: [1, 3, 16, 26, 8]
output type: tensor(float) 
##########################################
The output is yolov5 small.
What is the function of output name: 799 and  the shape 8 of  [1, 26208, 8] ?

**Comment by glenn-jocher** [comment]
@alicera these are model outputs. Your batch size is 1, there are 26208 anchors, and your feature vector is [xywh, conf, cls...]

**Comment by alicera** [comment]
Is the 799  compose of 524, 622, 720 ?
So 26208 =  (64x 104 +32x 52 + 16x 26)*3 .
How to let onnx output be 524, 622, 720? I dont want to 799 output

Thanks.

**Comment by glenn-jocher** [comment]
@alicera yes the final output is the concatenated from the earlier ones. You can omit grid concatenation in the export by placing it in train mode:
```
python models/export.py --train
```

**Comment by alicera** [comment]
the 8 of the shape [1, 26208, 8]
[xywh, conf, cls...]
 4 + 1 + 1

 could you give me a little hint for ...

**Comment by glenn-jocher** [comment]
[xywh, conf, cls...]

Your dataset has 3 classes if your vector is length 8

**Comment by alicera** [comment]
Oh, I got it .
Thanks.
