### ISSUE TITLE
error appeared when detect

### ISSUE THREAD

**Issue by zzy444626905** [ultralytics/yolov5#340]
(yolov3-pytorch) C:\Users\zzy\Desktop\darknet-pytorch\yolov5>python detect.py --weights weights/yolov3.pt --device cpu --source img/dog.jpg
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.4, device='cpu', img_size=640, iou_thres=0.5, output='inference/output', save_txt=False, source='img/dog.jpg', update=False, view_img=False, weights=['weights/yolov3.pt'])
Using CPU

Traceback (most recent call last):
  File "detect.py", line 161, in <module>
    detect()
  File "detect.py", line 23, in detect
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "C:\Users\zzy\Desktop\darknet-pytorch\yolov5\models\experimental.py", line 133, in attempt_load
    model.append(torch.load(w, map_location=map_location)['model'].float().fuse().eval())  # load FP32 model
AttributeError: 'collections.OrderedDict' object has no attribute 'float'

**Comment by zzy444626905** [comment]
ths very much！so sorry for that，this is my mistake，it run successfully，so fast and so better

**Comment by glenn-jocher** [comment]
@zzy444626905 great!

**Comment by PromiseXu1** [comment]
@zzy444626905 I encounter the same problem when I detect, so how did you solve it? Thanks so much!

**Comment by GuHuangAI** [comment]
> @zzy444626905 I encounter the same problem when I detect, so how did you solve it? Thanks so much!

when inference, if you use ensembel model, you --weights should input yolov5x.pt and yolov5l.pt simultaneously。
