### ISSUE TITLE
data augmentation

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#3400]
## ❔Question
    parser.add_argument('--hyp', type=str, default='data/hyp.scratch.yaml', help='hyperparameters path')

The default is hyp.scratch.yaml.
How to close the hyperparameters(hsv)? set it to 0?

hsv_h: 0
hsv_s: 0
hsv_v: 0

**Comment by glenn-jocher** [comment]
@alicera if you set all HSV hyperparameters to zero then yes there will be no color augmentation.
