### ISSUE TITLE
Error with wandb

### ISSUE THREAD

**Issue by OrjwanZaafarani** [ultralytics/yolov5#3401]
## ❔Question
Why dows wandb throw an error?

`wandb: ERROR If you really want to do this, pass allow_val_change=True to config.update()`

![Screenshot from 2021-06-01 10-04-42](https://user-images.githubusercontent.com/61848961/120281049-2890ff80-c2c1-11eb-83b3-8e83adb05747.png)

**Comment by OrjwanZaafarani** [comment]
I think the issue occurred after the run was crashed, I deleted it and started again. It's working now.

**Comment by glenn-jocher** [comment]
@OrjwanZaafarani @AyushExel I think your code may be out of date as a fix for this was pushed in the last few weeks. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by AyushExel** [comment]
@OrjwanZaafarani Please let us know if pulling the latest changes doesn't fix this.

**Comment by OrjwanZaafarani** [comment]
@glenn-jocher @AyushExel I think the model file (.pt) was corrupted due to the crash. Using another model solved the issue.

**Comment by AyushExel** [comment]
@OrjwanZaafarani oh okay. Thanks for letting us know. For more context, when resuming a run if some values of the parameters don't match the checkpoint, wandb throws an error. It's more of a sanity check. We can easily make it so these changes don't cause errors but that would let these corrupt files be used for training and the accuracies will suffer.

I discussed this with @glenn-jocher on a similar issue and decided that we'll relax this check if it happens without any reasons. So, please let us know if you see this error again where you think wandb is complaining about changes you didn't make.
