### ISSUE TITLE
Yolov5 for caffe

### ISSUE THREAD

**Issue by liyuhannnnn** [ultralytics/yolov5#341]
## ❔Question
Hello,  can i convert your pretrained model like yolov5s.pt to caffemodel.

## Additional context
I am new for pytorch.  I know some converter pytorch2caffe in GitHub like https://github.com/hahnyuan/nn_tools. But i think we know that caffe is for python2 originally. And when i try to use torch1.5-cpu, caffe1.0 and python2.7.  It got wrong when i want to load yolov5s.pt.  Do you have some idea?

**Comment by glenn-jocher** [comment]
@liyuhannnnn you can export directly to ONNX and torchscript with export.py, and from there I know ONNX exports to a large variety of formats. See the export tutorial in the wiki:
https://github.com/ultralytics/yolov5/wiki
