### ISSUE TITLE
Dataset not found

### ISSUE THREAD

**Issue by tabarkarajab** [ultralytics/yolov5#3411]
## ❔Question
I have a very basic yet important question to ask that I've been using my own dataset for training but the training.py file is unable to detect my data paths why? can you help me? attaching the images for data paths

![2](https://user-images.githubusercontent.com/49900380/120380711-f15f3480-c33a-11eb-9f8a-0f1a6eee5cd0.PNG)
![4](https://user-images.githubusercontent.com/49900380/120380713-f1f7cb00-c33a-11eb-9d0c-561d83f68633.PNG)

![1](https://user-images.githubusercontent.com/49900380/120380706-ef957100-c33a-11eb-9c97-b3bf9783b385.PNG)

**Comment by glenn-jocher** [comment]
@tabarkarajab start with **Train Custom Data** tutorial below to train COCO128 first, and then follow the example for your custom dataset.


## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by tabarkarajab** [comment]
I have tried it but still getting the same issue, can you please tell me I have divided my data perfectly as shown in the figure above? @glenn-jocher
