### ISSUE TITLE
Yolov5 Network Paper

### ISSUE THREAD

**Issue by Micky-123** [ultralytics/yolov5#3412]
## ❔Question
Hi,
I earlier read in one of the questions that there was a plan to release a paper on yolov5 by end of last year. Has it been released? Or planning to release any time soon?
Thanks

**Comment by slimwangyue** [comment]
And I also want to know the detailed naming rules, i.e., what is the difference between yolov5s and yolov5s6. And also in the readme @glenn-jocher shows two comparison figures and one needs to be expanded to see. I also want to know the detailed info about this two comparisons' difference. Thanks!

**Comment by Bobo-y** [comment]
i think for standard yolov5, have three backbone output, c3, c4, c5, yolov5s6 mean adding  c6  as backbone output.  S. M, l, X just represent the size of the model.@slimwangyue

**Comment by glenn-jocher** [comment]
@slimwangyue @yl305237731 latest v5.0 Release Notes contain info on P5 vs P6 models:
https://github.com/ultralytics/yolov5/releases/tag/v5.0

This release implements **YOLOv5-P6** models and retrained **YOLOv5-P5** models. All model sizes YOLOv5s/m/l/x are now available in  both P5 and P6 architectures:

* **YOLOv5-P5** models (same architecture as v4.0 release): **3 output layers** P3, P4, P5 at strides 8, 16, 32, trained at `--img 640`
```bash
python detect.py --weights yolov5s.pt  # P5 models
                           yolov5m.pt
                           yolov5l.pt
                           yolov5x.pt
```
* **YOLOv5-P6** models: **4 output layers** P3, P4, P5, P6 at strides 8, 16, 32, 64 trained at `--img 1280`
```bash
python detect.py --weights yolov5s6.pt  # P6 models
                           yolov5m6.pt
                           yolov5l6.pt
                           yolov5x6.pt
```

Example usage:
```bash
# Command Line
python detect.py --weights yolov5m.pt --img 640  # P5 model at 640
python detect.py --weights yolov5m6.pt --img 640  # P6 model at 640
python detect.py --weights yolov5m6.pt --img 1280  # P6 model at 1280
```
```python
# PyTorch Hub
model = torch.hub.load('ultralytics/yolov5', 'yolov5m6')  #  P6 model
results = model(imgs, size=1280)  # inference at 1280
```
