### ISSUE TITLE
FLOPS result In the README 

### ISSUE THREAD

**Issue by chocosaj** [ultralytics/yolov5#3413]
## ❔Question
I find that in the table of the pretraind result has a column named FLOPS. However, as my understanding, for algorithm, FLOPS is meanless; the real deal should be FlOPs. I wonder the 17.0 of YOLOv5s in the table of FLOPS, is this actually "FLOPs" or there is other specific calculation?

**Comment by glenn-jocher** [comment]
@chocosaj that's a good point! After doing a bit of research at https://github.com/Lyken17/pytorch-OpCounter and https://en.wikipedia.org/wiki/FLOPS it seems the term we want is FLOPs with a lowercase s as you mentioned. Can you submit a PR for the README for this change please?
