### ISSUE TITLE
About Inference Accuracy

### ISSUE THREAD

**Issue by leeyunhome** [ultralytics/yolov5#3417]
## ❔Question

I learned by labeling even the number on the license plate.
Sometimes I can't find the number.
Car license plate recognition must be accurate down to one digit, right? The purpose of license plate recognition is accurate vehicle number recognition.

In order to measure the accuracy, do I have to check each image with the bounding box drawn after the inference is finished?

**Comment by glenn-jocher** [comment]
@leeyunhome 👋 Hello! If you have questions about your training results **we recommend you provide the maximum amount of information possible** if you expect a helpful response, including results plots (train losses, val losses, P, R, mAP), PR curve, confusion matrix, training mosaics, test results and dataset statistics images such as labels.png. All of these are located in your `project/name` directory, typically `yolov5/runs/train/exp`.

**Comment by leeyunhome** [comment]
> @leeyunhome 👋 Hello! If you have questions about your training results **we recommend you provide the maximum amount of information possible** if you expect a helpful response, including results plots (train losses, val losses, P, R, mAP), PR curve, confusion matrix, training mosaics, test results and dataset statistics images such as labels.png. All of these are located in your `project/name` directory, typically `yolov5/runs/train/exp`.

I used to check the training graph using wandb, but if the internet is cut in the middle, the training graph record in wandb also crashes, so there are cases where there is no complete training graph.

**Comment by leeyunhome** [comment]
> @leeyunhome 👋 Hello! If you have questions about your training results **we recommend you provide the maximum amount of information possible** if you expect a helpful response, including results plots (train losses, val losses, P, R, mAP), PR curve, confusion matrix, training mosaics, test results and dataset statistics images such as labels.png. All of these are located in your `project/name` directory, typically `yolov5/runs/train/exp`.

Here is an example of a successfully completed training graph:
![image](https://user-images.githubusercontent.com/59910227/120447319-755dfe80-c3c5-11eb-9a57-43197ae58a9f.png)

**Comment by glenn-jocher** [comment]
@leeyunhome training seems fine! You can examine detections on your val set by looking at your test_batch0.jpg etc images created by test.py automatically in your runs/test/exp directory.

**Comment by leeyunhome** [comment]
Hello,

I can't find runs/test/exp
just type python test.py?

or I have to specify my custom weight trained?

![image](https://user-images.githubusercontent.com/59910227/120462640-13f25b80-c3d6-11eb-9674-7d9ecf80ae60.png)

Thank you.

**Comment by leeyunhome** [comment]
> @leeyunhome training seems fine! You can examine detections on your val set by looking at your test_batch0.jpg etc images created by test.py automatically in your runs/test/exp directory.

I ran test.py like this:

python test.py --weights /home/aiserver/coding/GitHub/yolov5/runs/train/lpr_result_320_500epoch/weights/best.pt --data /home/aiserver/coding/GitHub/dataset_lpr/data.yaml 

![image](https://user-images.githubusercontent.com/59910227/120465190-a85dbd80-c3d8-11eb-8daf-cc06b7d02b1c.png)
![image](https://user-images.githubusercontent.com/59910227/120465366-dc38e300-c3d8-11eb-8a7f-9008ed7e84b8.png)
![image](https://user-images.githubusercontent.com/59910227/120465427-ee1a8600-c3d8-11eb-917e-c47e24931303.png)
![image](https://user-images.githubusercontent.com/59910227/120465481-fe326580-c3d8-11eb-9b60-866bb0746d17.png)
![image](https://user-images.githubusercontent.com/59910227/120465552-10ac9f00-c3d9-11eb-98aa-82847bf10230.png)

Thank you.

**Comment by glenn-jocher** [comment]
@leeyunhome `runs/test/exp` logging directories are created when `python test.py` is run.
