### ISSUE TITLE
Train inside a docker container with wandb enabled

### ISSUE THREAD

**Issue by OrjwanZaafarani** [ultralytics/yolov5#3418]
## ❔Question
How can I train inside a docker container with wandb enabled?
I managed to train in a container successfully. But, wandb is not syncing the results.

**Comment by glenn-jocher** [comment]
@OrjwanZaafarani wandb will log your YOLOv5 trainings from a Docker container just as in any other environment. The official YOLOv5 docker image does not have wandb installed automatically, but you can install it manually once inside the container with the usual command:
```bash
pip install wandb
wandb login

python train.py  # train YOLOv5 :)
```
