### ISSUE TITLE
Docker Error: git@github.com: Permission denied (publickey)

### ISSUE THREAD

**Issue by zzy444626905** [ultralytics/yolov5#342]
root@d3a977aadcec:/usr/src/app# python train.py --data coco.yaml --cfg yolov5s.yaml --weights '' --batch-size 64
Warning: Permanently added the RSA host key for IP address '13.236.229.21' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Traceback (most recent call last):
  File "train.py", line 360, in <module>
    check_git_status()
  File "/usr/src/app/utils/utils.py", line 49, in check_git_status
    s = subprocess.check_output('if [ -d .git ]; then git fetch && git status -uno; fi', shell=True).decode('utf-8')
  File "/opt/conda/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/opt/conda/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'if [ -d .git ]; then git fetch && git status -uno; fi' returned non-zero exit status 128.

**Comment by glenn-jocher** [comment]
This is checking the status of your code to see if it  is up to date with the repository master. 

Are you running this from a computer with restricted internet access?

**Comment by glenn-jocher** [comment]
I see this error now as well when running docker. It seems to be a failure to connect to github:
https://docs.github.com/en/github/authenticating-to-github/error-permission-denied-publickey

**Comment by glenn-jocher** [comment]
@zzy444626905 I was not able to fix this, so I added some logic to avoid running this command from within docker containers. 

Docker autobuild is connected to this repo, so if you wait about 10 minutes after this message posts a new yolov5:latest image should automatically be published. Can you retry your command then?
