### ISSUE TITLE
What do the output values signify in yolo-v5?

### ISSUE THREAD

**Issue by dewball345** [ultralytics/yolov5#3435]
## ❔Question
What do the output values signify in yolo-v5?
## Additional context
Okay, so basically when you do a prediction for a model that is in training mode, its output shape will be `(25200, 7)`. I know the first 4 are the x1, y1, width, and height. But what about the remaining three? What do they account for?

**Comment by glenn-jocher** [comment]
@dewball345 objectness confidence and class confidences.

**Comment by dewball345** [comment]
Okay. Is it normal that my object confidences are never greater than 0.01
but my class Confidence varies?
