### ISSUE TITLE
Non-normalized or out of bounds coordinate labels

### ISSUE THREAD

**Issue by abuelgasimsaadeldin** [ultralytics/yolov5#3436]
## ❔Question

Hello everyone, before training on my own custom dataset I performed some data **augmentations** and one of which included random rotations to my training images. While training I noticed that all of my rotated images where found to be **corrupted** and where ignored during the training.

I figured that because of the rotation effect (Example shown below) a part of the image is indeed out of index. My question is how do I solve this by making the rotated images to not be corrupted and not be ignored during training. Thank you!   

Example of original image (accepted):

[lp_r_Bezza3.txt](https://github.com/ultralytics/yolov5/files/6588843/lp_r_Bezza3.txt) 
2 0.2904647435897436 0.43353658536585366 0.2075320512820513 0.10121951219512196 
0 0.5080128205128205 0.4713414634146341 0.9278846153846154 0.8670731707317073 

Example of rotated image (corrupted):

## Additional context
label 0 - Car
label 2 - CarPlate

Edited: I think the problem is to do with my augmentation script, the txt files are not adapted accordingly. Although even if they are I'm not sure if I will still be getting "out of bounds" because the bounding boxes would be slightly our of frame.

**Comment by glenn-jocher** [comment]
@abuelgasimsaadeldin YOLOv5 handles all augmentation for you automatically, including box cropping due to augmentation effects. You can control the amount of rotation augmentation in your hyperparameter file here:
https://github.com/ultralytics/yolov5/blob/3cb9ad4fc49872cf21ea529277708f1707649cbb/data/hyp.scratch.yaml#L25-L33

**Comment by abuelgasimsaadeldin** [comment]
Hi @glenn-jocher, thank you for the reply and that is so cool I didn't know about that! May I know what are the percentage of images that would be rotated if I just the degrees over here? Plus I'm also performing some other augmentations as well including adding rain, snow, noise etc. you don't happen to those too do you? lol

**Comment by glenn-jocher** [comment]
@abuelgasimsaadeldin rotations are sampled from a uniform distribution created by the hyperparameters you supply.

![YOLOv5 augmentation](https://user-images.githubusercontent.com/26833433/120790667-888edc80-c533-11eb-8810-1b68a7300a33.jpg)
