### ISSUE TITLE
FPS Problem

### ISSUE THREAD

**Issue by atalayismail** [ultralytics/yolov5#3437]
Hello guys, i am facing fps problem with my model. I trained a yolov5m6 model and deployed my computer i have t2000 gpu it gives me a about 15fps.

Then i tried the same model with gtx 1660 super it gave me a 5 fps it makes me confused is there any idea for that situation, for the record gtx 1660 super is 1.5x better then t2000. I used pytorch hub always deploying the model.

After that i tried to use detect.py which yolov5 gave us i took 7 fps with t2000. Can someone help me to explain that situation ?

**Comment by glenn-jocher** [comment]
@atalayismail speeds will vary based on your model, CPU, GPU and drivers.

**Comment by atalayismail** [comment]
I thınk i forgot the mention about the cpu i have better cpu on my gtx 1660 super computer and also better ram but the result are not satisfying also i am using the same code on both pc.

What about the pytorch hub and yolov5 detect.py results ? those are on the same pc but someting are affecting the fps.
