### ISSUE TITLE
Autoanchor: Show worst possible recall

### ISSUE THREAD

**Issue by GGDRriedel** [ultralytics/yolov5#3438]
## 🚀 Feature
Autoanchor showing worst possible recall

## Motivation
Training my own dataset with quite the variance in box seizes

## Additional context

The best possible recall is already shown to see where the ceiling is. 

However, since I am training with my own data, getting knowledge on how good the library can deal with my labels would 
also be quite useful. 
A good step would be showing "worst possible recall". 
Assuming we have a perfect detector this would show how well the dataset is suited to usable anchors.

**Comment by glenn-jocher** [comment]
@GGDRriedel there's no such metric as worst possible recall since this value would be 0.0 in all cases.
