### ISSUE TITLE
How to run inference with CPU only?

### ISSUE THREAD

**Issue by huyhoangle86** [ultralytics/yolov5#3441]
## ❔Question
Hi, in detect.py I tried to set argument in --device = cpu to run only by CPU, but when I check the GPU status it still uses more than 1GB of my GPU as in the pic below .

## Additional context
What happened ? How can I inference only on CPU? I did try to delve into the code but no luck
![image](https://user-images.githubusercontent.com/42195775/120635874-254f6c80-c497-11eb-87b6-ae8246d10d46.png)

I'm using Scaled YOLOv4 CSP  but hey I know you guys quite close to each other :smile: . I did raise an issue in Scaled YOLOv4 but the author said he's never use inference with CPU. I know where to ask now :smile: 
Thank and have a good day.

**Comment by glenn-jocher** [comment]
@huyhoangle86 you can use `--device cpu` to assign a CPU backend:
```bash
python train.py --device cpu
python test.py --device cpu
python detect.py --device cpu
```

**Comment by huyhoangle86** [comment]
@glenn-jocher as I describe I did use --device cpu in detect.py to inference only by CPU but during the inference the program still use more than 1GB of my GPU.  You can see the screenshot above

**Comment by glenn-jocher** [comment]
@huyhoangle86 YOLOv5 does not utilize your GPU if CPU is assigned. If you're having problems on other repositories I suggest you raise them on those repositories, not this one.

**Comment by huyhoangle86** [comment]
Thanks , I'll close the issue now
