### ISSUE TITLE
Use of "Background images" when training on custom dataset helpful?

### ISSUE THREAD

**Issue by abuelgasimsaadeldin** [ultralytics/yolov5#3443]
Hi, I was going through the [Tips for Best Training Results](https://github.com/ultralytics/yolov5/wiki/Tips-for-Best-Training-Results) and found something about "background images" and how having images with no objects can reduce a models FPs. 

My question is if you have an image which is not annotated (no text file) I thought that it would simply be ignored while training and not considered as no object present in that image or am I wrong? Would love some clarification on this. Thank you.

**Comment by Bobo-y** [comment]
@abuelgasimsaadeldin if you have an image which is not annotated (no text file) , This image will still be used for training as background

**Comment by Bobo-y** [comment]
So model can learn more background patterns, i think.

**Comment by abuelgasimsaadeldin** [comment]
@yl305237731 I see, thank you so much for the clarification I assumed that it would simply be ignored while training unless we purposely added a "background" class (similar to how we would do in an image classification task).

**Comment by edmuthiah** [comment]
Duplicate of https://github.com/ultralytics/yolov5/issues/1689
