### ISSUE TITLE
Is there a way to divide the recognition rate between far and near?

### ISSUE THREAD

**Issue by Choikyungho9** [ultralytics/yolov5#3445]
## ❔Question

I have a very curious question.
Is there any way to change the object recognition rate according to the distance?

When performing real-time detection, you do not want to detect objects that are too far away (e.g. people). However, it detects even distant objects on the screen with high probability.

Is there any way to prevent this?

I don't want to detect objects that are about 3 or 4 meters away.

**Comment by SamSamhuns** [comment]
What you have described is another computer vision problem of distance regression. This is a difficult task and an ill-posed problem if you only have RGB monocular images (opposed to depth map images, images with reference objects/cameras,  stereo images/like how our brain combines what we see from two eyes to give us a sense of depth).

Some research with deep learning has been done for monocular distance estimation ([here](https://arxiv.org/abs/1909.04182)) and you can find many more online.

Personally, if the end-use is not critical, you can just go with the size of the bounding box which is proportional to the distance from the object (refer to this [repo](https://github.com/harshilpatel312/KITTI-distance-estimation) for distance regression with bounding box dimensions). The bounding box size vs the object distance relation would however be specific to each class (i.e. a car and a dog might have the same bounding box size but be at different distances from the camera)
