### ISSUE TITLE
Making Anchors in x y w h format

### ISSUE THREAD

**Issue by saitarslanboun** [ultralytics/yolov5#3446]
Dear @glenn-jocher ! I am working on extending yolov5 with yolact.

In Yolact, there is following function for predefined anchors.

```
def make_anchors(cfg, conv_h, conv_w, scale):
    prior_data = []
    # Iteration order is important (it has to sync up with the convout)
    for j, i in product(range(conv_h), range(conv_w)):
        # + 0.5 because priors are in center
        x = (i + 0.5) / conv_w
        y = (j + 0.5) / conv_h

        for ar in cfg.aspect_ratios:
            ar = sqrt(ar)
            w = scale * ar / cfg.img_size
            h = scale / ar / cfg.img_size

            prior_data += [x, y, w, h]

    return prior_data
```

How can we twist it for the Yolov5 anchor format?

I would like to use it for the anchors returned by build_targets function within the loss.py.

Kind regards,

**Comment by glenn-jocher** [comment]
@saitarslanboun anchor values are defined for width and height only in all YOLO variants:
https://github.com/ultralytics/yolov5/blob/af2bc3a1c3414ce75e49f884f828be96be556e97/models/yolov5s.yaml#L6-L11

**Comment by saitarslanboun** [comment]
I have integrated coefficient prediction, protonet prediction, mask data iteration with all augmentations, etc. I am stuck at calculating loss function, because I still couldn't find the equivalent way of getting anchors as in yolact.
