### ISSUE TITLE
How can I do ”Add“ operation in model structure？

### ISSUE THREAD

**Issue by Zigars** [ultralytics/yolov5#3447]
## ❔Question
Hello, I 'm trying to recompose my own model structure in yolov5's baseline, I know how to do "Concat" operation in .yaml cfg files, but I don't know if I want to do ”Add“ operation in model structure, I don't know how to add a "Add" operation in model.py and yolo.py, I'm confuse about it, can you tell me how to add it?

## Additional context
![image](https://user-images.githubusercontent.com/32835472/120735159-af8de400-c51c-11eb-8425-35a2ec24d392.png)

**Comment by saitarslanboun** [comment]
```
class Add(nn.Module):
    # Sum a list of tensors along dimension
    def __init__(self, dimension=1):
        super(Add, self).__init__()
        self.d = dimension

    def forward(self, x):
        return torch.sum(x, self.d)
```

Put the above function under models/common.py, import the function, and replace concat with add, and see what happens.

**Comment by Zigars** [comment]
@saitarslanboun thanks so much, I will try your way! But I think the "ADD" output channel is different from “Concat”, maybe the channel set in yolo.py need fix?

![image](https://user-images.githubusercontent.com/32835472/120947879-6e434180-c773-11eb-80f6-7bfeb99aed64.png)

**Comment by saitarslanboun** [comment]
Maybe try

```
elif m is Add:
    c2 = c2
```

?

**Comment by Zigars** [comment]
@saitarslanboun I test it, and it doesn't work. thank you all the way!

I solve this by using the next way.

models/common.py
`class Add(nn.Module):
    # Sum a list of tensors along dimension
    def __init__(self, dimension=1):
        super(Add, self).__init__()
        self.d = dimension

    def forward(self, x):
        x1 = x[0]
        x2 = x[1]
        return torch.add(x1, x2)`

models/yolo.py
` elif m is Add:
        c2 = sum([ch[x] for x in f]) // 2`

The test in yolo.py is pass. Now I'm going to test if it works in my own model structure.

**Comment by Zigars** [comment]
@saitarslanboun I test it, and it doesn't work. thank you all the way!

I solve this by using the next way.

models/common.py

`
class Add(nn.Module):
    # Sum a list of tensors along dimension
    def __init__(self, dimension=1):
        super(Add, self).__init__()
        self.d = dimension

    def forward(self, x):
        x1 = x[0]
        x2 = x[1]
        return torch.add(x1, x2)
`

models/yolo.py

`
        elif m is Add:
            c2 = sum([ch[x] for x in f]) // 2
`

The test in yolo.py is pass. Now I'm going to test if it works in my own model structure.

**Comment by saitarslanboun** [comment]
I just wrote it without any test, expected you to understand the idea. You got it, well done! :)

**Comment by Zigars** [comment]
@saitarslanboun thank you all the same!
