### ISSUE TITLE
BG mAP

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#3448]
## ❔Question

If my test data have the background images, can it compute the mAP ?
If it can,the yolov5 detect the object in the background images. Will it be compute mAP or not?

**Comment by glenn-jocher** [comment]
@alicera mAP is computed by all images in a test set regardless of image contents.

**Comment by alicera** [comment]
So yolov5 detect the object in the background images , the mAP will sees the status as error.

 Computing mAP follow the https://github.com/Cartucho/mAP#explanation

**Comment by glenn-jocher** [comment]
@alicera yes background images in your val set contribute to mAP computation. This is the correct behavior.
