### ISSUE TITLE
plot_results does not display outputs; weights.pt saved in different location [bug introduced July 9]

### ISSUE THREAD

**Issue by josephofiowa** [ultralytics/yolov5#345]
## 🐛 Bug

 1. `utils.plot_results()` creates blank output graphs:

https://github.com/ultralytics/yolov5/commit/603ea0bfdc9b0db3b367fbe7cac5ba6f9a50a49f#diff-e6186f834ed280c4cb710843e5da633b

<img width="721" alt="Screen Shot 2020-07-09 at 11 12 34 PM" src="https://user-images.githubusercontent.com/13970811/87115893-200f8080-c23a-11ea-89fe-f63c105e23c5.png">

2. The model weights are no longer saved in the same location (I believe), resulting in them not being found for inference:

<img width="1452" alt="Screen Shot 2020-07-09 at 11 22 02 PM" src="https://user-images.githubusercontent.com/13970811/87116335-22260f00-c23b-11ea-8789-76c60d42ca61.png">

These bugs were introduced today. (Perhaps [this commit ](https://github.com/ultralytics/yolov5/commit/603ea0bfdc9b0db3b367fbe7cac5ba6f9a50a49f#diff-e6186f834ed280c4cb710843e5da633b) is responsible for # 1).

## To Reproduce

This Colab notebook documents the errors clearly: https://colab.research.google.com/drive/12v_XkfhTKg0pZucI0oymdHdNRPItywo5?usp=sharing

Scroll to the expected output graphs, printouts of augmented data, and attempted inference.

_(Adapted from [YOLOv5 tutorial](https://colab.research.google.com/drive/1gDZ2xcTOgR39tGGs-EZ6i3RTs16wmzZQ))_

**Comment by glenn-jocher** [comment]
@josephofiowa hi there, yes you are correct! This change is related to a significant rework train logging to bring us more into line with best practices from tensorboard, pytorch lightning etc. Originally all files were logged to the main `yolov5/` directory, now we are logging everything to unique `yolov5/runs/exp` (exp for 'experiment') folders that tensorboard is also logging to that increment with each new training as runs/exp0, runs/exp1 etc. 

If you git clone a fresh repo and train, then all training results will be` yolov5runs/exp0/`, including results.txt and results.png, among other stuff. There is a function that returns last run I believe, I can try to find it so we can update that notebook cell to plot the latest training.

**Comment by glenn-jocher** [comment]
The main PR for this is here BTW: https://github.com/ultralytics/yolov5/pull/104

**Comment by glenn-jocher** [comment]
Ok, thinking about this for a second, there are two ways to handle this. The first would be if we added a train.py argparser argument to specify the log_dir, as it's called. You could specify '.' to dump all training results to yolov5/, which would mimic the old behavior, or a fixed dir like runs/tutorial/ (and then update all subsequent code to point to weights/results there).

The other alternative is to move all weights and results from `log_dir` to `.` right after training finishes, and then leave all subsequent code alone. What do you think?

I just realized this probably broke our notebook also (!).

**Comment by glenn-jocher** [comment]
@josephofiowa ok, I've updated the notebooks below now to fix the path issues, and also made a few small improvements. The fix I went with was to simply explain the results saving paths (i.e. runs/exp0, runs/exp1, etc), and to add the runs/exp0/ prefix to the original plotting commands. WIll work if someone trains only once, but its good enough for the tutorial probably. Let me know if you think there are any other problem items.

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)

**Comment by glenn-jocher** [comment]
@josephofiowa oh btw, the plot_results() cell you pictured above is plotting twice because plot_results() by itself is producing plots in the cell, and then Image() after it is displaying the same plots in the same cell a second time, so in the latest notebooks I removed Image().
