### ISSUE TITLE
Corrupt JPEG data

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#3450]
## ❔Question
If I test the image and it show the message.
How can I debug it? 
Corrupt JPEG data: 1 extraneous bytes before marker 0xd9
Corrupt JPEG data: 1 extraneous bytes before marker 0xd9

**Comment by glenn-jocher** [comment]
@alicera these are hard to track since the error is a low-level C error in some of the functions that cv2 uses. Essentially some of your JPGs are corrupt and not fully saved correctly. The corrupt part will simply be black.

**Comment by alicera** [comment]
Does it affect the train and test mAP?

**Comment by glenn-jocher** [comment]
@alicera good news 😃! Your original issue may now be fixed ✅ in PR #3638. This PR adds JPEG corruption error checking by @xiaowk5516 to the YOLOv5 train and testloaders. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by alicera** [comment]
Thanks.
How to do the status for code when meet the problem ?

**Comment by glenn-jocher** [comment]
@alicera the new PR #3638 should identify each corrupted JPG by name.

**Comment by abuelgasimsaadeldin** [comment]
Hi @glenn-jocher, I am currently facing this issue of "Corrupted JPEG" too and I cannot identify the reason why? Previously I was training on these same exact images and they all appeared as "found" but now all of a sudden most of them are deemed as "corrupted". I have attached one of those images below for your reference. Thanks. 

![0a7cf41a-6783-4b46-9248-9424b8602924_1](https://user-images.githubusercontent.com/68045710/122508833-37074700-d035-11eb-8991-3c00b1ba1e7a.JPG)
[0a7cf41a-6783-4b46-9248-9424b8602924_1.txt](https://github.com/ultralytics/yolov5/files/6674696/0a7cf41a-6783-4b46-9248-9424b8602924_1.txt)

**Comment by xiaowk5516** [comment]
@abuelgasimsaadeldin hi! jpg and jpeg always end with '0xff','0xd9'. I notice this image ends with '0x00'.
![image](https://user-images.githubusercontent.com/59595896/122512393-5c974f00-d03b-11eb-81e2-7103fef32499.png)
I restore this image using opencv. 
![image](https://user-images.githubusercontent.com/59595896/122512829-0e368000-d03c-11eb-9000-6da2c6d10254.png)
now all '0x00' disappear.

**Comment by abuelgasimsaadeldin** [comment]
Hi @xiaowk5516 hm interesting, so what could be the cause of this issue? The image seems fine and can be read without any problems.

**Comment by xiaowk5516** [comment]
> Hi @xiaowk5516 hm interesting, so what could be the cause of this issue? The image seems fine and can be read without any problems.

I have no idea what makes it. when we parse a picture, we usually end after encountering 0xffd9. parser may ignore the 0x00 following 0xffd9. so it seems fine.

**Comment by abuelgasimsaadeldin** [comment]
Hi @xiaowk5516 I see, than why is it still considered as "corrupted" if the parser ignores the 0x00 following 0xffd9?

**Comment by xiaowk5516** [comment]
@abuelgasimsaadeldin  hi, do all your 'corrupted' images exist some data following 0xffd9? This is not a common situation.

**Comment by glenn-jocher** [comment]
@xiaowk5516 @abuelgasimsaadeldin I tested https://github.com/ultralytics/yolov5/pull/3638 on a variety of our autodownload datasets (VOC, COCO, SKU-110k, VisDrone, etc), and almost none of them showed any corrupted JPEGs other than SKU, which already reported corrupt images before the PR. 

COCO notably has zero out of 120k corrupted, so if there is a warning about your images it's likely actually a problem in your images. If they appear ok visually you might simply load and save them again with cv2.

**Comment by glenn-jocher** [comment]
@alicera good news 😃! Your original issue may now be fixed ✅ in PR #4548. This PR automatically restores and saves corrupted JPEGs before training starts, and all images are now used for training, including the restored JPEGs.

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
