### ISSUE TITLE
How to load a Ultralytics YOLOv5 Custom Model Pytorch Hub in Pytorch Version 1.8.1

### ISSUE THREAD

**Issue by pkarthik15** [ultralytics/yolov5#3451]
How to load a Untralytics YoloV5 Custom Model Pytorch Hub in Pytorch Version 1.8.1

**Comment by pkarthik15** [comment]
Hi Thanks for your response. i am getting an error in loading the custom model using torch.hub

Any help in this regard is highly helpful

**Comment by glenn-jocher** [comment]
@pkarthik15 see YOLOv5 🚀 **PyTorch Hub** tutorial:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by pkarthik15** [comment]
import torch

print(torch.__version__)

# Custom Model
model = torch.hub.load('ultralytics/yolov5', 'best.pt')

# Images
imgs = ['https://ultralytics.com/images/zidane.jpg']  # batch of images

# Inference
results = model(imgs)

# Results
results.save()  # or .show()


Getting the error below

-----
1.8.1+cu101
Downloading: "https://github.com/ultralytics/yolov5/archive/master.zip" to /root/.cache/torch/hub/master.zip
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-5e4cb8257f1f> in <module>()
      4 
      5 # Model
----> 6 model = torch.hub.load('ultralytics/yolov5', 'best.pt')
      7 
      8 # Images

2 frames
/usr/local/lib/python3.7/dist-packages/torch/hub.py in _load_entry_from_hubconf(m, model)
    185 
    186     if func is None or not callable(func):
--> 187         raise RuntimeError('Cannot find callable {} in hubconf'.format(model))
    188 
    189     return func

RuntimeError: Cannot find callable best.pt in hubconf

-----

**Comment by glenn-jocher** [comment]
@pkarthik15 your command is incorrect. I would suggest see YOLOv5 🚀 **PyTorch Hub** tutorial as I mentioned previously:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by pkarthik15** [comment]
Thank you. Update my code as below and it worked.

import torch
model = torch.hub.load('ultralytics/yolov5', 'custom', path='best.pt', force_reload=True)

**Comment by glenn-jocher** [comment]
@pkarthik15 looks good!
