### ISSUE TITLE
Is there any model for the yolo-nano and .yaml file exist for it? 

### ISSUE THREAD

**Issue by jaskiratsingh2000** [ultralytics/yolov5#3457]
Hi @glenn-jocher I want to know if there is a yolo-nano version also available or a model with the .yaml extension which can help me understand the profiling for it.

@glenn-jocher Can you please let me know if any such model for the yolo-nano exists under ultralytics?

Thanks!

**Comment by jaskiratsingh2000** [comment]
@glenn-jocher just like we have a profiling tool where can know the proflingo of each layer of yolpv5 so is there any way I could find profling for yolo-nano? Is there any yaml file which I can take up and run directly for such profiling?

@glenn-jocher please let me know if possible that would be of great help to me. Thanks!

**Comment by glenn-jocher** [comment]
@jaskiratsingh2000 I don't know what yolo-nano is.

You can use yolo.py with any conformant yaml file you make, and of course you can also use any model yamls in this repo in the models/ and models/hub directories.

**Comment by jaskiratsingh2000** [comment]
@glenn-jocher This is the repo for the yolo-nano https://github.com/ardeal/yolo_nano
but I don't know how the YAML file can be created for it so that it can be used within the "yolo.py" @glenn-jocher Can you please let me know if you have any idea about it?
