### ISSUE TITLE
I want to delete all the preceding characters from the output result.

### ISSUE THREAD

**Issue by Choikyungho9** [ultralytics/yolov5#3458]
## ❔Question
When outputting from yolov5, I want to delete the file path and words like 'video 1/1'.

How can I delete the preceding output characters?

I don't want the file path to be printed.

## Additional context
![image](https://user-images.githubusercontent.com/20491139/120794986-dcb9b100-c573-11eb-9aff-bcc08e1cf828.png)

**Comment by glenn-jocher** [comment]
@Choikyungho9 it looks like you're using detect.py. You'd can modify the source code to whatever your requirements are there:
https://github.com/ultralytics/yolov5/blob/develop/detect.py

**Comment by Choikyungho9** [comment]
@glenn-jocher Sorry sir, no matter how much I search, I can't figure out how to delete the file path in the result window. Could you tell me which part I need to edit?

**Comment by glenn-jocher** [comment]
@Choikyungho9 if you want to change console output you should review `print()` or `logger.info()` statements.

**Comment by Choikyungho9** [comment]
@glenn-jocher thank you so much. i found it.
