### ISSUE TITLE
mAP/recall significantly down on latest 'develop' branch due to max_det?

### ISSUE THREAD

**Issue by adrianholovaty** [ultralytics/yolov5#3459]
I ran the same training, with identical parameters, data and environment, using two different Git commits of YOLOv5 — and the latest "develop" branch has significantly lower mAP/recall.

The two Git commits are:

* b133baa, and I manually changed the `utils/general.py` `max_det` value from 300 to 1000.
* 4d4a2b0, which was the latest commit as of when I ran the training. I didn't alter any YOLO code in this case.

Here are the training results. (Sorry both runs didn't last the same number of epochs, but this should be representative enough of the issue.)

<img width="1081" alt="screenshot" src="https://user-images.githubusercontent.com/180401/120796109-b592bd80-c53a-11eb-8541-dfef38ebd249.png">

My dataset has lots of little objects, often more than 300 in a single image, so I suspect this has something to do with the changes from 3f74cd9e.

My previous hacking of `max_det` felt ugly, but it gets better results than the newer approach. Is it possible that training is using `max_det=300` rather than `1000`, and that's the reason for this regression? And if so, should we change that, or at least provide a way to override it?

**Comment by glenn-jocher** [comment]
@adrianholovaty I've seen no observable change in performance recently. Increasing max_det can only increase recall and mAP, it's not possible for increased low-confidence detections to decrease mAP since they all lie to the bottom right of the PR curve.

**Comment by glenn-jocher** [comment]
@adrianholovaty if you can provide comparable results on standard datasets like VOC or COCO please let us know, otherwise there's no action for us to take.

**Comment by adrianholovaty** [comment]
@glenn-jocher Thanks. What do you suggest I do to get better results on the latest YOLOv5 code? Continue to hack the source to change `max_det` to 1000 in all cases?

**Comment by glenn-jocher** [comment]
@adrianholovaty any max_det modifications have zero to minimal impact above 300 on COCO, I can't make any recommendations on your custom dataset.
