### ISSUE TITLE
3D image support

### ISSUE THREAD

**Issue by idhamari** [ultralytics/yolov5#3461]
## 🚀 Feature
 
We are trying to apply the same code to work on 3D images.  Is there anyone who already tried/did that? it is not clear how to modify the anchors for 3D input e.g. assuming one channel 256x256x128 what is the anchor vector? 

## Motivation
There are many applications e.g. points cloud, medical images, ..etc

**Comment by idhamari** [comment]
It would be nice if there is an actual reply instead of using github-actions bot.

**Comment by glenn-jocher** [comment]
@idhamari for any idea you're probably best off providing as much detail as you can so the community can provide the best feedback, i.e. what datasets display your format, what architectures use it today, what are your example use cases with links and documentation etc.

**Comment by idhamari** [comment]
@glenn-jocher thanks for your reply. An example is the detection of one or more objects in a 3D medical image e.g. detection of heart, lung and/or kidney in a CT or MRI image. Here are some [sample images](https://www.slicer.org/wiki/SampleData). The idea is to extend the current code to support such 3D images e.g. using [conv3d](https://pytorch.org/docs/stable/generated/torch.nn.Conv3d.html) instead of conv2d and using 3D points (x,y,z) or width,height,depth instead of 2D points e.g. (x,y) or (height,width). If someone interested or willing to help, we can work on this part together.

**Comment by shahenda-mahmoud-mabrouk-saed** [comment]
hi @idhamari I am also trying to apply the same code to work on 3D images. can I ask If you were able to reach any modification regarding this point
