### ISSUE TITLE
YOLOv5s does not detect objects as in tutorial (windows)

### ISSUE THREAD

**Issue by alex-zador** [ultralytics/yolov5#3463]
## ❔Question
I've created a ipynb following by the tutorial. Some minor changes were required:
instead of !python detect.py ... I've used !run detect.py ... (to run within selected conda environment)
I have required manually install requests & seaborn packages to my Py37 environment...

But after run yolo does not detect persons, ties and bus as in tutorial (see YOLOv5 tutorial.zip).

What may be wrong?

[YOLOv5 tutorial.zip](https://github.com/ultralytics/yolov5/files/6600413/YOLOv5.tutorial.zip)

Why 
## Additional context
I worked on Windows 10, python 3.7. PyTorch 1.8.1, ...

**Comment by glenn-jocher** [comment]
@alex-zador windows and conda sometimes seem to have issues. One fix that's seemed to work (open PR in https://github.com/ultralytics/yolov5/pull/3423) is to run inference in full FP32 precision rather than FP16 as in default code. Can you try the PR update and see if that works for you?

**Comment by alex-zador** [comment]
Glenn! Grate! That partially solved my issue! With FP32 it run even faster on my GPU and detected bus, persons and ties. But it does not draw bounding boxes..
What may be a reason? 

From bot's response I found that python 3.8 is required. I used 3.7. May this be critical?

**Comment by alex-zador** [comment]
After a few runs boxes and labels appered on pictures!
Thanks!

**Comment by glenn-jocher** [comment]
@alex-zador wow, strange, thanks for the feedback. What GPU are you using?

**Comment by glenn-jocher** [comment]
@alex-zador good news 😃! Your original issue may now be fixed ✅ in PR #3423. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
