### ISSUE TITLE
Rotated labels support

### ISSUE THREAD

**Issue by jmayank23** [ultralytics/yolov5#3465]
## 🚀 Feature
Support for predicting rotated bounding boxes would be great. That is, essentially another parameter, called theta, is added to the set of labels provided to the model. Theta represents the radians by which the box is to be rotated in an anti-clockwise direction with respect to the horizontal.

## Motivation
For finer detection of objects i.e for detecting object which is sensitive to orientation, it would be beneficial to be able to get a rotated bounding box

## Alternatives

Perhaps, a good alternative to rotated bounding box can be support for predicting 4 points i.e the ground truths would consist of 4 point polygons which can essentially be used to achieve the same performance as rotated bounding boxes. Moreover, predicting a 4 point polygon can greatly increase the applicability of detection to a variety of applications.

**Comment by glenn-jocher** [comment]
@jmayank23 hi, thanks for the ideas! This is somewhat a duplicate of #510, though the 4-polygon is a new interesting idea, though of course it would also double the parameter count from 4 per box to 8, which is significantly higher than the 5 for a rotated rectangle [xywh theta].

In any case, I tell everyone the same thing. This is supervised ML, so any idea you have requires a substantial number of existing datasets that support your idea out of the box for it to gain traction and community support in the real world. I know there are probably a few rotated box sets out there, in particular for satellite imagery, but for your idea to gain the most adoption and traction it must be generalizeable as broadly as possible, so perhaps you should frame this as a 4-point 8 parameter concept, which is the minimum instance segmentation mask, and think of it as the minimum viable segmentation problem.

**Comment by glenn-jocher** [comment]
@jmayank23 but my recommendation remains the same: find datasets first, then worry about supporting them.

**Comment by XinzeLee** [comment]
@jmayank23 Hi, this is Xinze here. Recently I have posted my codes of Polygon-Boxes-Enabled Yolov5, which is a repo based on Yolov5. The link is here: https://github.com/XinzeLee/PolygonObjectDetection
1. Model part: I have provided easy-to-run jupyter notebook for you to try out the polygon-yolov5s. The effects are  shown below.
![图片](https://user-images.githubusercontent.com/87064748/125054346-ae7e4280-e0d8-11eb-9d4f-53f032bee65f.png)
2. Dataset part: If you have the segmentation labels in the dataset, you can use Polygon-Tutorial2.ipynb to transform your dataset to four-corner polygon labels.

**Comment by XinzeLee** [comment]
@glenn-jocher Hi Glenn, Xinze here. @jmayank23 Hi, this is Xinze here. Recently I have posted my codes of Polygon-Boxes-Enabled Yolov5, which is a repo based on Yolov5. The link is here: https://github.com/XinzeLee/PolygonObjectDetection
The modifications of my repo compared with your codes Ultralytics/yolov5 are summarized in front-page README.md. Do you consider to add Polygon features in your main codes?

**Comment by glenn-jocher** [comment]
@XinzeLee wow nice work! Very impressive.

**Comment by davidsvaughn** [comment]
https://github.com/hukaixuan19970627/yolov5_obb

**Comment by glenn-jocher** [comment]
@davidsvaughn impressive work! Great to see the community extending YOLOv5 for different use cases. Keep up the great work!
