### ISSUE TITLE
Yolov5.cfg for easier model loading.

### ISSUE THREAD

**Issue by sakshamjn** [ultralytics/yolov5#347]
Can we add yolov5.cfg so that It will be easier to load model.

**Comment by glenn-jocher** [comment]
@sakshamjn hi there. We made a deliberate move away from darknet style *.cfg files for a few reasons. Mostly we wanted a flexible, modern and human readable configuration format, which we found in *.yaml, and second we re-engineered the syntax to allow us to describe an entire model in a minimum of lines. 

yolov4.cfg for example is 1150 lines long (!!), while yolov5x.yaml, our largest model, is far better performing, and is defined by **just 50 lines**. This is a major leap in simplicity and performance, so no, we will not be taking a step backward and supplying any *.cfg files.

**Comment by glenn-jocher** [comment]
I'll link to yolov5x.yaml here so you can see the difference:
https://github.com/ultralytics/yolov5/blob/master/models/yolov5x.yaml
```yaml
# parameters
nc: 80  # number of classes
depth_multiple: 1.33  # model depth multiple
width_multiple: 1.25  # layer channel multiple

# anchors
anchors:
  - [116,90, 156,198, 373,326]  # P5/32
  - [30,61, 62,45, 59,119]  # P4/16
  - [10,13, 16,30, 33,23]  # P3/8

# YOLOv5 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Focus, [64, 3]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, BottleneckCSP, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 9, BottleneckCSP, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, BottleneckCSP, [512]],
   [-1, 1, Conv, [1024, 3, 2]], # 7-P5/32
   [-1, 1, SPP, [1024, [5, 9, 13]]],
  ]

# YOLOv5 head
head:
  [[-1, 3, BottleneckCSP, [1024, False]],  # 9

   [-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, BottleneckCSP, [512, False]],  # 13

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, BottleneckCSP, [256, False]],
   [-1, 1, nn.Conv2d, [na * (nc + 5), 1, 1]],  # 18 (P3/8-small)

   [-2, 1, Conv, [256, 3, 2]],
   [[-1, 14], 1, Concat, [1]],  # cat head P4
   [-1, 3, BottleneckCSP, [512, False]],
   [-1, 1, nn.Conv2d, [na * (nc + 5), 1, 1]],  # 22 (P4/16-medium)

   [-2, 1, Conv, [512, 3, 2]],
   [[-1, 10], 1, Concat, [1]],  # cat head P5
   [-1, 3, BottleneckCSP, [1024, False]],
   [-1, 1, nn.Conv2d, [na * (nc + 5), 1, 1]],  # 26 (P5/32-large)

   [[], 1, Detect, [nc, anchors]],  # Detect(P5, P4, P3)
  ]
```

Compare to yolov4.cfg in our old repo. I won't paste the contents here to save everyone from the burden of scrolling through it.
https://github.com/ultralytics/yolov3/blob/master/cfg/yolov4.cfg

**Comment by sakshamjn** [comment]
Thanks @glenn-jocher
