### ISSUE TITLE
Unable to export to onnx with inplace argument

### ISSUE THREAD

**Issue by gouravvemula0** [ultralytics/yolov5#3472]
using the pretrained model yolov5s.pt

python /content/yolov5/models/export.py --weights /yolov5/yolov5s.pt --img 640 --batch 1 --inplace --simplify

error:

TorchScript: export success, saved as /content/yolov5/yolov5s.torchscript.pt (29.4 MB)
ONNX: starting export with onnx 1.9.0...
ONNX: simplifying with onnx-simplifier 0.3.6...
ONNX: simplifier failure: [ONNXRuntimeError] : 1 : FAIL : Node (Mul_925) Op (Mul) [ShapeInferenceError] Incompatible dimensions
ONNX: export success, saved as /content/yolov5/yolov5s.onnx (29.2 MB)
CoreML: export failure: No module named 'coremltools'

onnx-simplifier is failing

**Comment by glenn-jocher** [comment]
@gouravvemula0 if export arguments are causing you problems then I would simply recommend you omit those arguments.
