### ISSUE TITLE
How to convert boundary box points(x1, y1, x2, y2) to YOLOv5 Annotation format points

### ISSUE THREAD

**Issue by MrAsimZahid** [ultralytics/yolov5#3474]
## ❔Question

How to convert boundary box points(x1, y1, x2, y2) to YOLOv5 Annotation points?

I have raw boundary box points(xmin, ymin, xmax, ymax)  available. I want to convert these points to YOLOv5 annotation format to custom train my dataset.

How can I convert these points to normalized useful points?

```
class, xmin, ymin, xmax, ymax
1, 1378.0, 536.0, 1402.0, 560.0,
1, 1338.0, 512.0, 1372.0, 539.0,
1, 1140.0, 385.0, 1179.0, 415.0,

```
Reference:

https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data#2-create-labels

**Comment by glenn-jocher** [comment]
@MrAsimZahid you can see this function as an example (normalize separately using instructions in the link you pasted)
https://github.com/ultralytics/yolov5/blob/cf4f95bc5f5ee2027e5819e5ec7c3f9ae822d433/utils/general.py#L358-L366

**Comment by MrAsimZahid** [comment]
@glenn-jocher Thank you for sharing. I was able to write the tool to convert MOT20 to YOLOv5 annotations.

Thank you for sharing.

https://github.com/MrAsimZahid/Dataset-Format-Conversions/tree/master/MOT%20to%20YOLO
