### ISSUE TITLE
Can I use some other weight file instead of yaml file in yolo.py to produce profiling?

### ISSUE THREAD

**Issue by jaskiratsingh2000** [ultralytics/yolov5#3476]
Hey @glenn-jocher I want to produce profiling for the [yolo-nano](https://github.com/ardeal/yolo_nano) but I don't have any YAML file for that which I can put into the configuration inside yolo.py instead I have the yolov3_nano_weight weight file. So is there a way that I can use this weight file and produce the profiling for it?

This is the weight file: [yolo3_nano_weights_416_voc.h5](https://drive.google.com/file/d/1oYXNVCR7BFN_iSkVStdLpv5vYJF2pP95/view?usp=sharing)

Please let me know @glenn-jocher as this can really help me a lot if this weight file can be used for profiling purposes.

**Comment by jaskiratsingh2000** [comment]
Hey @glenn-jocher Can you please tell me some concrete steps to work on the above?

**Comment by glenn-jocher** [comment]
@jaskiratsingh2000 this repo is unrelated to the one you are mentioning, there is no inter-compatability.
