### ISSUE TITLE
Meaning of "from", "number", "module", "args" in YAMLs files?

### ISSUE THREAD

**Issue by jaskiratsingh2000** [ultralytics/yolov5#3477]
https://github.com/ultralytics/yolov5/blob/3597d280eeee5cd2049999f7b1a5640cf0e1c89a/models/hub/yolov3-tiny.yaml#L13

Hey @glenn-jocher I want to know that what does the "from", "number", "module". "args" mean in the YAML file?

Does this mean the following?

"from" - input channels
"number" - output channels
"module" - name of the layers?
"args" - _don't know about this_

**Comment by jaskiratsingh2000** [comment]
@glenn-jocher Do you have any idea of the above? This can help me in making the other related yaml files so please let me know?

**Comment by glenn-jocher** [comment]
@jaskiratsingh2000 args is module arguments

**Comment by jaskiratsingh2000** [comment]
@glenn-jocher did I interpret the meanings of "from" and "number" correct above? 

What does "from" and "number" means above? Can you please ellaborate a bit on this @glenn-jocher ?

**Comment by glenn-jocher** [comment]
@jaskiratsingh2000 from which layer and how many times the module is repeated.

**Comment by jaskiratsingh2000** [comment]
@glenn-jocher thank you for replying. I get that "from" represents from which layer but writing the number under "from" category like "-1" here - https://github.com/ultralytics/yolov5/blob/3597d280eeee5cd2049999f7b1a5640cf0e1c89a/models/hub/yolov3-tiny.yaml#L14

What does that mean exactly? 

Another thing I am not able to understand in YAML file is the meaning of "backbone" and "head"? How do I know that which layers details to put under backbone and head?

So @glenn-jocher please let me know on above things. That would really be helpful.
Thanks!

**Comment by glenn-jocher** [comment]
@jaskiratsingh2000 negative indices are relative to the current index, so -1 indicates the previous layer.

**Comment by jaskiratsingh2000** [comment]
@glenn-jocher you haven't answered my other question here Another thing I am not able to understand in YAML file is the meaning of "backbone" and "head"? How do I know that which layers details to put under backbone and head?

Please let me know this as well

**Comment by glenn-jocher** [comment]
@jaskiratsingh2000 the definition is largely arbitrary and based on previous literature, you can place whatever layers you want in either.
