### ISSUE TITLE
nvidia-docker

### ISSUE THREAD

**Issue by 123456789mojtaba** [ultralytics/yolov5#348]
thank you because of this valuable project. It was very useful for me.
I trained a model on custom data. now I wanna deploy it with docker. As you said it needs nvidia docker. does windows nvidia-docker?

**Comment by glenn-jocher** [comment]
Docker works with all OS's. See https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/

**Comment by 123456789mojtaba** [comment]
> Docker works with all OS's. See https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/

docker works but I told nvidia-docker. In nvidia website it is mentioned  it works with linux only and  doesn't support windows.

https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#is-microsoft-windows-supported

**Comment by glenn-jocher** [comment]
@123456789mojtaba I don't know in that case. Probably a question for the nvidia-docker people and not the yolov5 repo right?

**Comment by 123456789mojtaba** [comment]
thank you so much
