### ISSUE TITLE
Make minor/intermediate releases

### ISSUE THREAD

**Issue by kinoute** [ultralytics/yolov5#3484]
## 🚀 Feature

A few months ago (https://github.com/ultralytics/yolov5/issues/1531), other tags different than "latest" built from master were added to the Docker Hub. Before, there was only one image version available which was the latest one, built after every commit pushed to the repo.

While this was a nice step to avoid problems in production, I think it would be nice, not only for Docker but overall, to release more frequently new (minor) versions between the majors ones.

## Motivation

For example, you released v5.0 on April 11 but you quickly found bugs right after and fixed a bunch of them in the following hours (https://github.com/ultralytics/yolov5/pull/2764). But this patch wasn't added back to the v5.0 release. Therefore, if, for production stability, we try to stay on a locked version like v5.0 instead of using latest, we are stuck with bugs.

## Pitch

This could be fixed by releasing new intermediate versions more often (v5.1, v5.2 etc), and make them available in the Docker Hub as well.

**Comment by glenn-jocher** [comment]
@kinoute thanks for the feedback! We are considering what steps we should take to better align with best practices, including moving to patch versioning (i.e. 5.0.0), establishing a new `develop` branch (`master < develop < feature`, where `master` would only update on releases) and also examining our release schedule, which is sparse now as you mentioned.

@KalenMike @SkalskiP see OP's comment on versioning and releases, similar to our conversation from last week.
