### ISSUE TITLE
why not write NMS in c extension?

### ISSUE THREAD

**Issue by bxhandhxb** [ultralytics/yolov5#349]
## ❔Question
Hi, It's an excellent codebase, but I still have a quesion about the inference time.
Why don't you write NMS in c extension, I think this will make speed faster.

**Comment by glenn-jocher** [comment]
@bxhandhxb thanks for the feedback. Can you point to some benchmarks that demonstrate improved NMS speeds with custom c code?

**Comment by bxhandhxb** [comment]
Sorry, my mistake. I just find you call the nms operation in torch. 
Thanks for your patience.
