### ISSUE TITLE
图形

### ISSUE THREAD

**Issue by zhaoguoqing12** [ultralytics/yolov5#350]
tkinter.TclError: couldn't connect to display "localhost:10.0"
![image](https://user-images.githubusercontent.com/47818312/87129534-103c7e80-c2c4-11ea-926e-4770edbe3fc4.png)

**Comment by glenn-jocher** [comment]
@zhaoguoqing12 it looks like you have environment issues. You can try one of the options below.
## Reproduce Our Environment

To access an up-to-date working environment (with all dependencies including CUDA/CUDNN, Python and PyTorch preinstalled), consider a:

- **GCP** Deep Learning VM with $300 free credit offer: See our [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Google Colab Notebook** with 12 hours of free GPU time. <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)

**Comment by zhaoguoqing12** [comment]
> @ zhaoguoqing12您好像遇到了环境问题。您可以尝试以下选项之一。
> 
> ## 重现我们的环境
> 要访问最新的工作环境（已预安装所有依赖项，包括CUDA / CUDNN，Python和PyTorch），请考虑以下事项：
> 
> * **GCP**深度学习VM提供$ 300的免费赠金：请参阅我们的[GCP快速入门指南](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
> * **Google Colab Notebook**具有12小时的免费GPU时间。[![在Colab中打开](https://camo.githubusercontent.com/52feade06f2fecbf006889a904d221e6a730c194/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb)
> * **泊坞窗图像** https://hub.docker.com/r/ultralytics/yolov5。请参阅[Docker快速入门指南](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker拉](https://camo.githubusercontent.com/caa63570e9f4e9771b02fc86d87e78aad3bf9785/68747470733a2f2f696d672e736869656c64732e696f2f646f636b65722f70756c6c732f756c7472616c79746963732f796f6c6f76353f6c6f676f3d646f636b6572)

但是测试时候没有问题，还是环境问题吗？
