### ISSUE TITLE
Images number

### ISSUE THREAD

**Issue by Asma-Fowzia** [ultralytics/yolov5#3500]
## ❔Question

Sir i want to detect safe and unsafe drive by yolov5.  Here there are 2 classes and total images is 51 for validation. But in my result why the number of images are same in class all,safe drive and unsafe drive? 

When i take images there are 20 safe drive and 31 unsafe drive images and total 51..but why the number of images shows 51 51 51...?
## Additional context
![Uploading FB_IMG_16230563212719499.jpg…]()

**Comment by glenn-jocher** [comment]
@Asma-Fowzia your image fails to load.

**Comment by Asma-Fowzia** [comment]
![1623060801432267588072](https://user-images.githubusercontent.com/79735559/120999820-5edfea80-c7ab-11eb-9a51-cf521d6cdfb5.jpg)

**Comment by Asma-Fowzia** [comment]
![Uploading 1623060935044-584162560.jpg…]()

**Comment by Asma-Fowzia** [comment]
![1623060983671-1072436021](https://user-images.githubusercontent.com/79735559/121000192-bf6f2780-c7ab-11eb-8fd1-1467c3303911.jpg)

**Comment by glenn-jocher** [comment]
This is correct. All images are used to compute mAP for each class, not just the images containing the classes.

<img width="1391" alt="Screenshot 2021-06-07 at 12 23 03" src="https://user-images.githubusercontent.com/26833433/121001003-20d2ce80-c78b-11eb-8391-7ad3accc7006.png">

**Comment by Asma-Fowzia** [comment]
Thank you sir. Sir can you pls tell me what's the difference between map@ .5 and map@5:.95: 
And also what's the meaning of 100% 4/4

**Comment by glenn-jocher** [comment]
https://blog.paperspace.com/mean-average-precision/
