### ISSUE TITLE
How to clear cache on custom model?

### ISSUE THREAD

**Issue by GGDRriedel** [ultralytics/yolov5#3504]
## ❔Question
How do I reload the cache on local models. 

## Additional context
I am loading a custom model through
```python

model = torch.hub.load(r'~\Projekte\Radspot\ultralyt\yolov5', 'custom', path=r'\remote_results\e
    ...: xp15\weights\best.pt', source='local')  # local repo
```
As shown in https://github.com/ultralytics/yolov5/issues/36

This throws: 

```
 Cache may be out of date, try `force_reload=True`. See https://github.com/ultralytics/yolov5/issues/36 for help.
```

However, using 
```python

model = torch.hub.load(r'~\Projekte\Radspot\ultralyt\yolov5', 'custom', path=r'\remote_results\e
    ...: xp15\weights\best.pt', source='local',force_reaload=True)  # local repo
```

Throws 
```
 custom() got an unexpected keyword argument 'force_reaload'
```

**Comment by glenn-jocher** [comment]
@GGDRriedel if you pass source='local' by definition no cache is used. The error message is a general message.

**Comment by GGDRriedel** [comment]
Gosh darn, tried it on a linux machine, saw more error handling, path to model is not relative to yolo5 path, it's absolute. 

I feel very stupid now. 


sorry for taking up your time

**Comment by GGDRriedel** [comment]
Solution: use absolute path, not relative path for model path
