### ISSUE TITLE
non-normalized or out of bounds coordinate labels yolov5

### ISSUE THREAD

**Issue by Aliweka2020** [ultralytics/yolov5#3509]
when I trying to train yolov5 on humancrowd dataset I get that error

AssertionError: non-normalized or out of bounds coordinate labels: D:\H.B\After B.C\coursera\DeepLearning\Master\Object Detection\Ahmed Shokry\publish\codes\dataset\CrowdHuman\CrowdHuman\labels\crowd\273275,10eced000cead4fd8.txt

this file annotation looks like:
0 0.17174515235457063 0.5 0.34349030470914127 1.0
0 0.4538319482917821 0.509386733416771 0.41458910433979684 0.983729662077597
0 0.46860572483841184 0.7171464330413017 0.2742382271468144 0.5657071339173968
0 0.5674053554939982 0.5544430538172715 0.38688827331486614 0.8961201501877347
0 0.7793167128347184 0.49874843554443055 0.40627885503231764 1.002503128911139

any suggestions.......?

**Comment by glenn-jocher** [comment]
@Aliweka2020 labels must fall between 0 and 1 (inclusive). Your labels are out of bounds.

**Comment by glenn-jocher** [comment]
@Aliweka2020 do not use a bug label for problems within your data.

**Comment by Aliweka2020** [comment]
how I could make labels fall between 0 and 1?
I have used this repository to convert crowdhuman annotation to yolov5 annotation 

https://github.com/alaksana96/darknet-crowdhuman

is there any solution?

**Comment by glenn-jocher** [comment]
@Aliweka2020 see **Train Custom Data** tutorial:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by Aliweka2020** [comment]
I have already used these tutorials and train COCO128 without any problem.

the point is, I want to train crowdhuman dataset which has different annotation from yolov5.

any suggestions ....?!!!

**Comment by glenn-jocher** [comment]
@Aliweka2020 follow label guidelines in https://docs.ultralytics.com/yolov5/tutorials/train_custom_data

**Comment by Aliweka2020** [comment]
the same ........
there isn't any instructions or guidelines on hoe to train crowdhuman dataset or to convert annotations

**Comment by glenn-jocher** [comment]
@Aliweka2020 I don't understand the issue. Your labels must fall between 0 and 1. If they are not between 0 and 1 make them so.

**Comment by Aliweka2020** [comment]
I understand that.

I am training crowdhuman dataset that has different annotation.
I used this repository to convert to yolov5 annontation 
https://github.com/nikitalpopov/crowdhuman

which says :
<x> <y> <width> <height> - float values relative to width and height of image, it can be set from 0.0 to 1.0

but in some files values above zero appears.

I am asking for two solutions that could help:

1- track error in that repository that generates some values above 1
2- suggests another method to convert from crowdhuman annotation (.odgt) to yolov5 annotations (.txt)

**Comment by glenn-jocher** [comment]
@Aliweka2020 I would raise questions regarding 3rd party repositories directly on those repositories.
