### ISSUE TITLE
Export nms operation to onnx model

### ISSUE THREAD

**Issue by Root970103** [ultralytics/yolov5#3517]
I want to export a model containing nms operation to an onnx model. Does anyone know how to do it?

**Comment by Root970103** [comment]
Or someone has ideas to convert the nms operation to trt/tvm? Thanks!

**Comment by kail85** [comment]
@Root970103 , opencv has a built in nms function you can call to perform the same operation.

**Comment by ml5ah** [comment]
@kail85 could you please share the snippet of code that uses cv2.dnn.nmsboxes on inference results for onnx exported model? Ive given it a shot but my results aren't exactly matching torchvision.ops/nms. Thanks!

**Comment by zhiqwang** [comment]
@Root970103 I've done some experiments about exporting `nms` to ONNX/TVM [here](http://github.com/zhiqwang/yolov5-rt-stack), maybe you could refer to this repo.

**Comment by Root970103** [comment]
> @Root970103 I've done some experiments about exporting `nms` to ONNX/TVM [here](https://github.com/zhiqwang/yolov5-rt-stack), maybe you could refer to this repo.

Thanks for your contribution, I will try.
