### ISSUE TITLE
Is there any lesser version than yolo-tiny which can give me the lesser computation time in profiling?

### ISSUE THREAD

**Issue by jaskiratsingh2000** [ultralytics/yolov5#3519]
@glenn-jocher 
Is there any lesser version than yolo-tiny which can give me the lesser computation time in profiling?
Version which can give me less time than 1000 ms

@glenn-jocher let me know because so far I couldn't find here

**Comment by glenn-jocher** [comment]
@jaskiratsingh2000 YOLOv5s is the smallest official model, but you can scale it smaller by reducing the compound scaling factors:
https://github.com/ultralytics/yolov5/blob/f3c3d2ce5d85ba77336a9d0a87c6a446732cdda6/models/yolov5s.yaml#L3-L4

**Comment by jaskiratsingh2000** [comment]
@glenn-jocher What do you mean by compound scaling terminology here?

**Comment by glenn-jocher** [comment]
@jaskiratsingh2000 read the EfficientDet paper https://arxiv.org/abs/1911.09070

**Comment by jaskiratsingh2000** [comment]
@glenn-jocher sure, I will read but for now if you could explain in short that would be helpful for me to utilise the rest of the time in working. Thanks

**Comment by jaskiratsingh2000** [comment]
Oh I got it. Thanks
