### ISSUE TITLE
About the FLOPs

### ISSUE THREAD

**Issue by HankYe** [ultralytics/yolov5#3521]
### Hello, I wonder why the value of FLOPs here is twice, since I find that after using thop.profile to compute the FLOPs of the model, the value times 2. Actually, when I use thop.profile to compute the FLOPs of SSD300, the value is aligned with that in the paper. I'd appreciate it if you could send an explanation!

**Comment by glenn-jocher** [comment]
@HankYe most of modern hardware architectures uses FMA instructions for operations with tensors.
FMA computes a*x+b as one operation. Roughly GMACs = 0.5 * GFLOPs, where MAC = Multiply–accumulate operation.

**Comment by HankYe** [comment]
> @HankYe most of modern hardware architectures uses FMA instructions for operations with tensors.
> FMA computes a*x+b as one operation. Roughly GMACs = 0.5 * GFLOPs, where MAC = Multiply–accumulate operation.

I see. Thanks a lot!

**Comment by soumendukrg** [comment]
If I want to report the GMACs of YOLOv5 models, I have to divide the numbers given in the table or computed by `thop` by 2. Am I correct? Also, as per my understanding, the numbers in the table assume an input of size `(1, 3, 640, 640)` whereas if I want to calculate the actual number of GLOPs used for each image of the COCO (val/test) dataset where the image size varies widely, I have to call profile using the actual image size (which is obtained after the rectangular padding in `letterbox` function) that is fed into the model. Could you please clarify if I am understanding this correctly?

**Comment by glenn-jocher** [comment]
@soumendukrg most of modern hardware architectures uses FMA instructions for operations with tensors.
FMA computes a*x+b as one operation. Roughly GMACs = 0.5 * GFLOPs

**Comment by soumendukrg** [comment]
Thanks a lot for the clarification. However, could you clarify my confusion regarding the dependency of image size on the FLOPs as I mentioned earlier?

**Comment by glenn-jocher** [comment]
FLOPs displayed assume 1x3x640x640 image

**Comment by soumendukrg** [comment]
Thanks a lot.
