### ISSUE TITLE
How to get outputs from an arbitrary layer in the YOLO and connect them to a new output layer?

### ISSUE THREAD

**Issue by tserdar** [ultralytics/yolov5#3522]
## ❔Question
Hi, 

I am looking for a way to extract image features from the last layer of the backbone. My goal is performing a few computations over these feature vectors and output an aggregated value in the final layer of the overall YOLO network for each found bounding box e.g. (x,y,w,h,my_val).

What would be the general strategy achieving this? 

I don't expect an in-depth answer, only a high-level strategy so I'd not waste a lot of time trying to understand how to do it by myself. 

Any help is appreciated, 
Thanks!

**Comment by glenn-jocher** [comment]
@rocketsfallonrocketfalls you can customize the model forward function directly, or you can create a new module and use it in the yaml file with an input from whichever layer you are interested in:

https://github.com/ultralytics/yolov5/blob/f3c3d2ce5d85ba77336a9d0a87c6a446732cdda6/models/yolov5s.yaml#L12-L48

**Comment by tserdar** [comment]
Thanks a lot for quick answer, perhaps including all I needed for starting.

**Comment by tserdar** [comment]
Hey @glenn-jocher, 

I've been having hard time to edit the forward function in the way I wanted. 

Right now, all I need is to find a way *say* get the image features on a trained model after the backbone, save the feature vector for each image passed through the network during inference. 

I'll use this to implement a diversity-based active learning method.


Should I edit Model class's forward function, or Detect's? How can I access the exact layer's outputs in a forward function?

**Comment by glenn-jocher** [comment]
@rocketsfallonrocketfalls if you only want the output feature maps you can access those in Detect() layer and simply add them to the layer outputs, then when you run inference you'll get the predictions as well as the Detect() feature maps.

**Comment by glenn-jocher** [comment]
@rocketsfallonrocketfalls the exact place is here in the Detect() forward method:
https://github.com/ultralytics/yolov5/blob/0e5cfdbea756716d5bbdfe6f3b26b2731e2facc4/models/yolo.py#L29-L69

**Comment by tserdar** [comment]
So, in `Detect.forward()`, should I consider the input `x` to be the combined feature maps for each sample in the batch before propagating them in `Detect.m` and basically add a copy of initial `x` to the outputs?

**Comment by glenn-jocher** [comment]
@rocketsfallonrocketfalls yeah sounds right!

**Comment by tserdar** [comment]
hey @glenn-jocher, thanks for your informative answers so far! 

Right now, using YOLOv5 release v4-medium - I get 3 sets of feature tensors with dimensions: [192, 32, 40], [384, 16, 20], [768, 8, 10].

I was wondering if you would have a ready-to-share insight about what would be a good way of checking similiarity of multiple images using these feature outputs. I thought of calculating sum of squared distances for each feature then aggregate the three values by summing them up but it's too "traditional" and "straight-forward". 

I thought that maybe you could say -> *only use this and lose others* or give me a technique *use this to evaluate similarity between images using the features* or vice versa. 

Your opinion about this would be extremely relevant, if you have any. It's fine otherwise too.You already helped more than enough!

**Comment by glenn-jocher** [comment]
@rocketsfallonrocketfalls if your images are the same shape you can measure the cosine similarity of the two:
https://en.wikipedia.org/wiki/Cosine_similarity

Though this method is not translationally invariant the way CNNs are. I think there are more general image similarity approaches out there (both ML and classical), but I'm not an expert on the topic.

**Comment by tserdar** [comment]
Hmm, 

Alright then. Maybe I can test multiple methods and even try combining them. 

Thanks!

**Comment by rocketsfallonrocketfalls** [comment]
Can anyone help me understand what are the dimensions of the feature vectors explicitly for? 

In my application in particular, I get 3 sets of feature maps for a single image flowing into the `Detect` layer. Their dimensions are:

1. ` 192 x 32 x 40 ` 
2. ` 384 x 16 x 20 `
3. ` 768 x 8 x 10`

If we formulate these as ` k x m x n `, what do `k`, `m` and `n` individually stand for? 

I tend to assume `k` is the number of different features for the same image with `m x n` dimensions? 

**My actual problem:** 
- I want to calculate similarity based on image features calculated by the network. 
- Using all these vectors cause computational problems as I have to load these vectors for hundreds of images and make operations on them. 

**My actual question:**
- How can I downsize/dimensionally-reduce these data for similarity checking purposes?

**Comment by vipingautam1906** [comment]
Sorry to open this thready.
@rocketsfallonrocketfalls, I am also trying to extract the feature maps and further analyze them for finding similarity in images. Could you tell me how did you get hold of feature maps in  forward method of Detect()
