### ISSUE TITLE
Question regarding Training on Custom Data

### ISSUE THREAD

**Issue by abuelgasimsaadeldin** [ultralytics/yolov5#3523]
Hi guys, I am training a yolov5 model using custom training data following this link on [Train Custom Data](https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data#5-train) and I am using yolov5s pre-trained weights. I could not find however anywhere in the guide which mentions about how many of the layers are actually frozen during the training, I'm assuming that all of the layers are frozen except for the last layer which is fine-tuned, is that correct?

**Comment by glenn-jocher** [comment]
@abuelgasimsaadeldin no layers are frozen during training. 

You can optionally choose to freeze layers, see **Transfer Learning with Frozen Layers** tutorial.

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)
