### ISSUE TITLE
Where to find list of corrupted data?

### ISSUE THREAD

**Issue by yogaaltariz** [ultralytics/yolov5#3527]
I'am train yolov5 with custom data and end up with some images/labels corrupted, so my question is where to find the list or log of the path of all corrupted images so I can fix the issue?  thanks

**Comment by glenn-jocher** [comment]
@yogaaltariz any dataset problems are displayed before training starts during image and label scanning:

<img width="1396" alt="Screen Shot 2021-06-08 at 4 16 49 PM" src="https://user-images.githubusercontent.com/26833433/121201695-007f3e80-c875-11eb-8991-077c858c42b6.png">

**Comment by yogaaltariz** [comment]
yes i got it, but is there a file that generated after scanning dataset which contain all the file paths of the corrupted data? I think it will be helpfull if there. thanks

**Comment by glenn-jocher** [comment]
@yogaaltariz no there is no file of corrupted image/label pairs, but yes that might be useful. You could submit a PR for this feature. The right area of the code to create this would be in the dataloader here:
https://github.com/ultralytics/yolov5/blob/1b5edb6f8eb14a12f21ed0370e9a0e74085424e3/utils/datasets.py#L460-L488
