### ISSUE TITLE
I just want to locate objects and do not want to do classification during inference.

### ISSUE THREAD

**Issue by matianyun** [ultralytics/yolov5#3529]
## ❔Question
Hi, how may I do if I just want to locate objects and do not want to do classification during inference? Thank you!

**Comment by glenn-jocher** [comment]
@tianyma you can train and test any dataset in single-class mode with the --single-cls argument:
```bash
python train.py --single
python test.py --single
```

**Comment by matianyun** [comment]
> @tianyma you can train and test any dataset in single-class mode with the --single-cls argument:
> 
> ```shell
> python train.py --single
> python test.py --single
> ```

Thank you for your quick reply! 
I made up to do that!
