### ISSUE TITLE
pt2onnx

### ISSUE THREAD

**Issue by kingjames1288** [ultralytics/yolov5#3541]
## ❔Question
why i convert model from pt to onnx is different from the onnx showed in demo .

**Comment by kingjames1288** [comment]
![image](https://user-images.githubusercontent.com/85596613/121284800-feb68900-c90f-11eb-917b-7c012c1f479e.png)
![image](https://user-images.githubusercontent.com/85596613/121284820-05450080-c910-11eb-8aaf-490cf25a6223.png)
just this onnx .  i convert yolov5s.pt to onnx . and see the onnx in nteron .it is different from the onnx provided by this demo

**Comment by standy-zz** [comment]
same error ...

**Comment by glenn-jocher** [comment]
@standy-zz @kingjames1288 hi thanks for letting us know about this problem! We've deleted the ONNX and CoreML v4.0 models mentioned above to avoid confusion. 

Current export.py operates correctly, I would recommend using the latest master code for all exports.

**Comment by kingjames1288** [comment]
> @standy-zz @kingjames1288 hi thanks for letting us know about this problem! We've deleted the ONNX and CoreML v4.0 models mentioned above to avoid confusion.
> 
> Current export.py operates correctly, I would recommend using the latest master code for all exports.

thank you，I view online information，we need to modify some  statement in common.py and yolo.py to get the right onnx. now , we just need to run export.py ,then  we will have the right onnx ?

**Comment by glenn-jocher** [comment]
@kingjames1288 just run export.py. See **TorchScript, ONNX, CoreML Export** tutorial:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)
