### ISSUE TITLE
how deploy gradio?

### ISSUE THREAD

**Issue by johnfelipe** [ultralytics/yolov5#3545]
Im using ubuntu 20 from scratch
    apt update
    apt upgrade
    shutdown -r now

next

    apt install python3-pip
    pip install gradio
    git clone https://github.com/AK391/yolov5.git
    cd yolov5/
    pip install -r requirements.txt

how can deploy?

**Comment by johnfelipe** [comment]
Dear can tell me how deploy in my gradio local en?

**Comment by glenn-jocher** [comment]
For the YOLOv5 API see https://ultralytics.com/yolov5

<img width="1467" alt="Screenshot 2021-06-10 at 11 57 40" src="https://user-images.githubusercontent.com/26833433/121505416-1ad72a80-c9e3-11eb-9e6d-c779807f85a1.png">

**Comment by johnfelipe** [comment]
That is awesome, but again how deploy gradio example in my local
environment?

**Comment by johnfelipe** [comment]
dear i only need deploy gradio in my personal instance, with public ip and droplet in DigitalOcean with ubuntu 20

**Comment by johnfelipe** [comment]
pls tell me how can deploy in my local env?

**Comment by johnfelipe** [comment]
pls show me how deploy gradio example
tnks

**Comment by johnfelipe** [comment]
Dear pls tell me how can run with gradio...

**Comment by johnfelipe** [comment]
root@4-ubuntu-s-8vcpu-16gb-nyc1-01:~/yolov5# python3 test.py
    Namespace(augment=False, batch_size=32, conf_thres=0.001, data='data/coco128.yaml', device='', exist_ok=False, img_size=640, iou_thres=0.6, name='exp', project='runs/test', save_conf=False, save_hybrid=False, save_json=False, save_txt=False, single_cls=False, task='val', verbose=False, weights='yolov5s.pt')
    YOLOv5 🚀 v4.0-185-gfad7d4e torch 1.9.0+cu102 CPU
    
    Fusing layers...
    [W NNPACK.cpp:79] Could not initialize NNPACK! Reason: Unsupported hardware.
    /usr/local/lib/python3.8/dist-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
      return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
    Model Summary: 224 layers, 7266973 parameters, 0 gradients, 17.0 GFLOPS
    
    WARNING: Dataset not found, nonexistent paths: ['/root/coco128/images/train2017']
    Downloading https://github.com/ultralytics/yolov5/releases/download/v1.0/coco128.zip ...
    100%|██████████████████████████████████████| 21.1M/21.1M [00:00<00:00, 96.5MB/s]
    sh: 1: unzip: not found
    Dataset autodownload failure
    
    Traceback (most recent call last):
      File "/root/yolov5/utils/datasets.py", line 368, in __init__
        raise Exception(f'{prefix}{p} does not exist')
    Exception: val: ../coco128/images/train2017 does not exist
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "test.py", line 312, in <module>
        test(opt.data,
      File "test.py", line 88, in test
        dataloader = create_dataloader(data[task], imgsz, batch_size, gs, opt, pad=0.5, rect=True,
      File "/root/yolov5/utils/datasets.py", line 63, in create_dataloader
        dataset = LoadImagesAndLabels(path, imgsz, batch_size,
      File "/root/yolov5/utils/datasets.py", line 373, in __init__
        raise Exception(f'{prefix}Error loading data from {path}: {e}\nSee {help_url}')
    Exception: val: Error loading data from ../coco128/images/train2017/: val: ../coco128/images/train2017 does not exist
    See https://docs.ultralytics.com/yolov5/tutorials/train_custom_data

but that folder exists

    root@4-ubuntu-s-8vcpu-16gb-nyc1-01:~/yolov5# ls
    Dockerfile   coco128      hubconf.py        test.py         weights
    LICENSE      coco128.zip  models            train.py        yolov5s.pt
    README.md    data         requirements.txt  tutorial.ipynb
    __pycache__  detect.py    runs              utils
