### ISSUE TITLE
How can I save the new anchor box?

### ISSUE THREAD

**Issue by SpongeBab** [ultralytics/yolov5#3546]
## ❔Question
How can I save the new anchor box?
I trained my custom dataset,and yolov5 regenerated the anchor box.I want to save it.

## Additional context
And if I dont want to use the regenerate anchor feature.Is there a way?Or I need to modify the code by myself?

**Comment by glenn-jocher** [comment]
@SpongeBab YOLOv5 anchors are saved as [Detect()](https://github.com/ultralytics/yolov5/blob/fab5085674f7748dc16d7ca25afb225fa441bc9d/models/yolo.py#L22) layer attributes on model creation, and updated as necessary by autoanchor before training starts. Their exact location is here:
https://github.com/ultralytics/yolov5/blob/fab5085674f7748dc16d7ca25afb225fa441bc9d/models/yolo.py#L34-L35

You can examine the anchors of any trained YOLOv5 model like this:

### Input
```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', autoshape=False)  # official model
model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt',  autoshape=False)  # custom model

# Anchors
m = model.model[-1]  # Detect() layer
print(m.anchor_grid.squeeze())  # print anchors
```

### Output
```python
#           x     y
tensor([[[ 10.,  13.],
         [ 16.,  30.],
         [ 33.,  23.]],  # P3/8-small

        [[ 30.,  61.],
         [ 62.,  45.],
         [ 59., 119.]],  # P4/16-medium

        [[116.,  90.],
         [156., 198.],
         [373., 326.]]], dtype=torch.float16)  # P5/32-large
```

**Comment by SpongeBab** [comment]
@glenn-jocher oh,great help.Thank you very much.
