### ISSUE TITLE
how can i use it for a WebApp ?

### ISSUE THREAD

**Issue by Yahia-M** [ultralytics/yolov5#3549]
## ❔Question
Can i use the detect.py in a flask by my owne pre-training "best.pt"?

**Comment by livjatan** [comment]
@Yahia-M 
not the most sophisticated way, but i have done it like this within my flask route:

```
_PathJPG = Path(os.path.join("./data/jpg"))
_PathJPG.mkdir(parents=True, exist_ok=True)
_PathOut = Path(os.path.join("./inference/output"))
_PathOut.mkdir(parents=True, exist_ok=True)

os.system("python ./yolov5/detect.py --weights ./yolov5/weights/best_yolov5l_data.pt --img 800 --conf 0.7 --source " + os.path.join(_PathJPG, file) + " --save-txt")
```

After that, i get the saved txt file with:
```
with open(os.path.join(_PathOut ,file[:-4] + ".txt")) as yoloAnnotations:
  for row in yoloAnnotations:
      classID, xCenter, yCenter, width, height, confidence = row.split()
      xCenter = float(xCenter)
      yCenter = float(yCenter)
      width = float(width)
      height = float(height)
      confidence = float(confidence)
```

**Comment by glenn-jocher** [comment]
@Yahia-M @livjatan you might want to try the YOLOv5 PyTorch Hub inference method:
https://pytorch.org/hub/ultralytics_yolov5/

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Image
img = 'https://ultralytics.com/images/zidane.jpg'

# Inference
results = model(img)
results.print()  # or .show(), .save()
```

**Comment by Yahia-M** [comment]
thanks for the answer, but @glenn-jocher  if i don't want to use the model pre-training in github but the one, i had just train ?

**Comment by glenn-jocher** [comment]
@Yahia-M you can use any YOLOv5 model you want, see **PyTorch Hub** Tutorial for details:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by Yahia-M** [comment]
My question is if there is a way to load my model from local and after use it to predict in a web app @glenn-jocher  

thanks for your help :+1:

**Comment by andrew-healey** [comment]
> My question is if there is a way to load my model from local and after use it to predict in a web app @glenn-jocher
> 
> thanks for your help 👍

You can load pretrained weights by replacing `yolov5s` with a path to the `.pt` file:

```py
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'custom', path='path/to/best.pt')  # default

# Image
img = 'https://ultralytics.com/images/zidane.jpg'

# Inference
results = model(img)
results.print()  # or .show(), .save()
```

**Comment by glenn-jocher** [comment]
@Sesamestrong yes almost, you would pass 'custom' for the model and then the path to your model:
```python
model = torch.hub.load('ultralytics/yolov5', 'custom', path='path/to/best.pt')  # default
```
