### ISSUE TITLE
Question related to depth_multiple and width_multiple in YAML file

### ISSUE THREAD

**Issue by jaskiratsingh2000** [ultralytics/yolov5#3560]
We are missing out on the terminology in the YAML file which becomes difficult for a newcomer to understand things. @glenn-jocher can you help me know that what does the following mean?
* What does **depth_multiple** and **width_multiple** mean here
* In how much range we can vary the values of **depth_multiple** and **width_multiple**
* What will happen on the **profiling performance** if we vary the values of **depth_multiple** and **width_multiple**
https://github.com/ultralytics/yolov5/blob/4ef92618700cb1a4fc54de970f05e3126283d0da/models/yolov5s.yaml#L3-L4

@glenn-jocher Looking forward to your response.

Thanks and Regards

**Comment by jaskiratsingh2000** [comment]
@glenn-jocher any idea on above please?

**Comment by glenn-jocher** [comment]
@jaskiratsingh2000 compound scaling is explained well in the EfficientDet paper: https://arxiv.org/abs/1911.09070

**Comment by jaskiratsingh2000** [comment]
@glenn-jocher I actually tried understanding that but wasn't able to understand that so that is why I reached out to you. If possible please let me know based upon the 3 questions i raised that would be highly appreciable and helpful for me @glenn-jocher

**Comment by jaskiratsingh2000** [comment]
@glenn-jocher just a small glimpse of information you can share on this then it would really be helpful.
