### ISSUE TITLE
I know that the dataset used in the tutorial used only 128 images out of coco2017.

### ISSUE THREAD

**Issue by leeyunhome** [ultralytics/yolov5#3566]
## ❔Question

I know that the dataset used in the tutorial used only 128 images out of coco2017.

![image](https://user-images.githubusercontent.com/59910227/121443283-2d903600-c9c8-11eb-87a6-23fa0b53116f.png)

I am trying to learn with the coco2017 full dataset. Which of the following should I download?

**Comment by glenn-jocher** [comment]
@leeyunhome COCO downloads automatically on first use in YOLOv5:
```
python train.py --data coco.yaml
```

**Comment by leeyunhome** [comment]
> @leeyunhome COCO downloads automatically on first use in YOLOv5:
> 
> ```
> python train.py --data coco.yaml
> ```

If I look at the train.py code, I can even download the coco dataset and configure the dataset folder. Is that right?

Coco's annotation is in json format, but is it also included in train.py code to convert it to yolo's label format?

Thank you.

**Comment by glenn-jocher** [comment]
@leeyunhome no action is required on your part to train COCO, just run `python train.py --data coco.yaml`

**Comment by leeyunhome** [comment]
> @leeyunhome no action is required on your part to train COCO, just run `python train.py --data coco.yaml`

I'm trying to learn about 500 epochs on the entire coco2017 dataset instead of coco128.

Is there a difference between coco128 and coco2017 full dataset?

Thank you.

**Comment by leeyunhome** [comment]
> @leeyunhome no action is required on your part to train COCO, just run `python train.py --data coco.yaml`

Hello,

COCO128 is a small tutorial dataset composed of the first 128 images in COCO train2017

It's written like this in the tutorial.

Thank you.

**Comment by leeyunhome** [comment]
> @leeyunhome no action is required on your part to train COCO, just run `python train.py --data coco.yaml`

Ah, is it okay to use coco.yaml instead of coco128?
![image](https://user-images.githubusercontent.com/59910227/121516810-99ef5180-ca29-11eb-8537-c55f86038bff.png)
