### ISSUE TITLE
General opinion about yolov5 architecture representation

### ISSUE THREAD

**Issue by Leprechault** [ultralytics/yolov5#3567]
Dear Members and especially @glenn-jocher ,

I'd like an opinion/review about yolov5 architecture representation. We found great results using yolov5 and we decided to prepare a paper. To publish details about the methodology used, we decide to make a pipeline about yolov5 architecture and we create the figure below:

![arquitetura_yolov5l_modelo_2_1](https://user-images.githubusercontent.com/17205267/121452069-c729fa00-c96c-11eb-8f3e-1401643b6290.png)

All the images were resized to 256x256 before training/validation and I ask the suggestions about the accuracy of the information in the figure in order to not incorrectly publicize the yolov5 approach.

Please, any help with this?

**Comment by glenn-jocher** [comment]
@Leprechault seems correct at first glance for a P6 model with 4 outputs. You might want to explain which output is which, i.e. P3/8 all the way to P6/64. Also `na` and `nc` are the number of anchors per output and the number of classes.

TensorBoard also automatically produces a 'graph' of the YOLOv5 on train start:
<img width="893" alt="Screenshot 2021-04-11 at 01 10 09" src="https://user-images.githubusercontent.com/26833433/114286928-349bd600-9a63-11eb-941f-7139ee6cd602.png">

**Comment by Leprechault** [comment]
Thanks, @glenn-jocher is exactly what I need.
