### ISSUE TITLE
How should we label the background image?

### ISSUE THREAD

**Issue by OOF-dura** [ultralytics/yolov5#3568]
## ❔Question

I saw a tutorial: [https://github.com/ultralytics/yolov5/wiki/Tips-for-Best-Training-Results](https://github.com/ultralytics/yolov5/wiki/Tips-for-Best-Training-Results)

It is said that. Background images are images with no objects that are added to a dataset to reduce False Positives (FP). We recommend about 0-10% background images to help reduce FPs (COCO has 1000 background images for reference, 1% of the total).

How can we label this data?
Should we just leave the label empty?

**Comment by kinoute** [comment]
You don't label these images: background images are images without annotations to make the model understand that some images might not have something to detect on it (therefore, it reduces the FP).

It can be images without an annotated file or images with an empty annotation file.

**Comment by OOF-dura** [comment]
> You don't label these images: background images are images without annotations to make the model understand that some images might not have something to detect on it (therefore, it reduces the FP).
> 
> It can be images without an annotated file or images with an empty annotation file.

Thank you so much for your clarification!
