### ISSUE TITLE
Warning: "Images sizes do not match" when W&B logging enabled

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/yolov5#3575]
@AyushExel training with W&B logging enabled in Colab notebook I get some strange warning messages (which are printed in incorrect English):
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

## Default training
<img width="980" alt="Screenshot 2021-06-10 at 13 16 39" src="https://user-images.githubusercontent.com/26833433/121516282-54616300-c9ee-11eb-81d1-451efd84f21b.png">

## W&B Logged training

<img width="952" alt="Screenshot 2021-06-10 at 13 17 13" src="https://user-images.githubusercontent.com/26833433/121516287-55929000-c9ee-11eb-9996-95407a92863a.png">

This message is not originating within the repository. Can you take a look at this and try to figure out what is happening? Thanks!
<img width="777" alt="Screenshot 2021-06-10 at 13 19 47" src="https://user-images.githubusercontent.com/26833433/121516512-94284a80-c9ee-11eb-8310-3c781efd782e.png">

**Comment by AyushExel** [comment]
@glenn-jocher It's from [here](https://github.com/wandb/client/blob/81a7cfd86a08c928aef7e6c38869eb5038cde9f9/wandb/sdk/data_types.py#L2038) in the client. It is a warning about how the images of different sizes might not be displayed correctly in the same panel. I think this warning is raised because the size of test images is different from mosiacs(?) This should not cause any problem here because we're using different panels for mosiacs/metrics and the test images. 

I'll have exact details shortly

**Comment by glenn-jocher** [comment]
@AyushExel ok I see. We probably want to suppress this warning then so as not to worry users and improve our overall UI/UX. I did something similar today with a Seaborn warning when plotting empty confusion matrices. This uses a context manager to ignore warnings for certain sections of the code: https://github.com/ultralytics/yolov5/pull/3576

**Comment by glenn-jocher** [comment]
@AyushExel any updates on this? I searched our issues and it seems this problem has been present since December 2020, first reported in https://github.com/ultralytics/yolov5/issues/1676 about 2000 issues ago. 

I think at the minimum if a fix in the W&B codebase (ideal solution) is not possible quickly then you should place the ops that cause this (presumably somewhere in utils/wandb_logging) under a warning suppression to prevent this from displaying to screen.

**Comment by AyushExel** [comment]
Oh yeah, I forgot to update you on this. Client fixes take time so I'll wrap it under a warning suppression.

**Comment by glenn-jocher** [comment]
@AyushExel awesome, thanks!

**Comment by glenn-jocher** [comment]
The code I've used before for this is:
```python
import warnings

with warnings.catch_warnings():                
    warnings.simplefilter('ignore')
    # code that produces warning

# normal code
```

**Comment by AyushExel** [comment]
@glenn-jocher client uses `logging.warning("message")` so this doesn't work. I'm trying this - https://stackoverflow.com/a/60448982/8253860

**Comment by AyushExel** [comment]
Okay, that didn't work. I'm trying a hacky way. PR up shortly.

**Comment by AyushExel** [comment]
@glenn-jocher fix here -> https://github.com/ultralytics/yolov5/pull/3611

**Comment by glenn-jocher** [comment]
@AyushExel I'm getting this warning still today in Colab, it does not seem to be resolved. Can you look into this please? 

If there is a problem we need to fix it, else we need to suppress this message, those are our only two options here.

<img width="1356" alt="Screenshot 2021-07-31 at 23 13 54" src="https://user-images.githubusercontent.com/26833433/127752564-1baa6c92-2274-423e-af2d-e05e6986bcc5.png">

**Comment by glenn-jocher** [comment]
@AyushExel training without wandb installed in Colab I verify no warnings, so I believe they originate in W&B:
<img width="1398" alt="Screenshot 2021-07-31 at 23 18 20" src="https://user-images.githubusercontent.com/26833433/127752633-8c761d46-55d1-415e-8e6e-7c210f22c0d7.png">

**Comment by AyushExel** [comment]
@glenn-jocher looking at the source, I think I know where these are getting generated. We need to enclose all wandb.Image logging operations in the context manager that suppresses the message. I'm on phone now, I'll push a fix tomorrow

**Comment by glenn-jocher** [comment]
@AyushExel awesome thanks for the quick response!
