### ISSUE TITLE
How to modify names of a YOLOv5 trained

### ISSUE THREAD

**Issue by GiorgioSgl** [ultralytics/yolov5#3577]
## ❔Question

 I run the command
`python3 detect.py --source image.jpg --weights runs/train/exp5/last.pt`

The problem is that I mismatch some name of the classes and I have to change it, but seems impossible.

How can I change it??
I need it asap, that I have to submit my thesis :)

## Additional context

I try already changing the array in the .yaml file but no success :(

**Comment by GiorgioSgl** [comment]
Just solve in a hard way, I don't know if there are smoother solutions

Actually here
https://github.com/ultralytics/yolov5/blob/095197bd4a011b867f1bb7118d1735dd84ac5ee6/detect.py#L59

You have to modify in the following way
```
names = ["myfirstclass","my second class",..,"last class"]
```

Hope it help and if there are better solution, just let me know

**Comment by bkbilly** [comment]
I had the same question, but I solved in a similar way like this:
After loading the model:
https://github.com/ultralytics/yolov5/blob/095197bd4a011b867f1bb7118d1735dd84ac5ee6/detect.py#L56
I replaced the dictionary like so:
```python
model.names[0] = 'first_class'
model.names[1] = 'second_class'
model.names[2] = 'third_class'
```
