### ISSUE TITLE
ghostbottleneck

### ISSUE THREAD

**Issue by ggyybb** [ultralytics/yolov5#358]
## ❔Question
I add ghostbottleneck to backbone,the model size decreased 50%, however, inference speed is slower than origin model.
And ,I have a question, when inference on video, at first, speed is ok(normal), after a little time, speed is getting slower, it happened on both origin yolov5s.pt and my ghost yolov5s model.
i want to know how to fix this problem.
can you give me some addvice?
 

## Additional context
![image](https://user-images.githubusercontent.com/61568153/87214228-68738f00-c35d-11ea-84e9-419b4e71da88.png)
like this, the red line may be a split line.

**Comment by ZeKunZhang1998** [comment]
Hi，when I add Ghostbottleneck,how to load pertained weights?

**Comment by jiangxinhao2020** [comment]
I have the same situation.
Replace BottleneckCSP with GhostBottleneck.
the model size decreased 50%, however, inference speed is slower than origin model. @ggyybb

**Comment by glenn-jocher** [comment]
@ggyybb @jiangxinhao2020 inference speed and model size do not correlate all the time. Look at EfficientDet for a prime example of that.
