### ISSUE TITLE
About Object tracking

### ISSUE THREAD

**Issue by leeyunhome** [ultralytics/yolov5#3581]
## ❔Question

Hello,

yolov5 is known as object detection architecture or algorithm. Is it possible to track object using yolov5?
If possible, can you tell me how to approach it?

Thank you.

**Comment by glenn-jocher** [comment]
@leeyunhome tracking is a separate task from detection, and can be handled by other algorithms such as Kalman filters, KLT trackers, or deepsort.

**Comment by nadine-alexandra** [comment]
@leeyunhome did you find a solution for object tracking with yolov5 predictions?
