### ISSUE TITLE
How to find "accuracy" for Yolov5s.yaml file?

### ISSUE THREAD

**Issue by jaskiratsingh2000** [ultralytics/yolov5#3584]
@glenn-jocher I tried running the Yolov5s.yaml file with the changed **depth_multiple** and **width_multiple** value for profiling and Ì want to compute the accuracy it gave. How can I do that?

**Comment by glenn-jocher** [comment]
@jaskiratsingh2000 test.py computes metrics:
```
python test.py --data DATA.yaml --weights WEIGHTS.pt
```

**Comment by jaskiratsingh2000** [comment]
@glenn-jocher do I have to replace the "DATA.yaml" with "yolov5s.yaml" because this is the file in which I made changes or I have to include "coco" dataset and in place of "WEIGHTS" I have to write "Yolov5s.pt? 

Please let me know @glenn-jocher

**Comment by jaskiratsingh2000** [comment]
@glenn-jocher any idea about it? Would appreciate that

**Comment by glenn-jocher** [comment]
@jaskiratsingh2000 see test.py:
https://github.com/ultralytics/yolov5/blob/4984cf54be4eb88f00ccf33a05f57681b2a770ab/test.py#L1-L346

**Comment by jaskiratsingh2000** [comment]
@glenn-jocher instead of saying directly, you are putting me more in a complex loop through this code understanding which I can't understand easily.

Would have been appreciable if you could answered my question directly.
