### ISSUE TITLE
Some question about IoU threshold and Confident score

### ISSUE THREAD

**Issue by Nhatcao99** [ultralytics/yolov5#3595]
## ❔Question
Does confident score calculation rely on IoU threshold?
What is iou thres doing in detect.py?
## Additional context
Hi, thank you for you work. I am still green so bare with my question!
As far as I understand IOU threshold is about the intersection of ground truth and predicted box. 
Meanwhile the confident score is how much the prediction sure it is the object.
Hence, I have following question as I am quite confused.

-Does the confident score calculation rely on IoU threshold like in the original Yolo paper, or they have changed through time and I missed that during my learning? 
-In file detection.py, there is only image as input, hence there is only prediction bounding box: so what is iou threshold doing there if there is no ground truth boxes? 

Thank you!

**Comment by glenn-jocher** [comment]
@Nhatcao99 confidence is a model output. IoU threshold is an NMS parameter.

**Comment by Nhatcao99** [comment]
> @Nhatcao99 confidence is a model output. IoU threshold is an NMS parameter.

In test file, I can see blog of code where prediction is consider true or false with a range of IOU. 
In detect, there is only image,  it has no ground truth to compare.  So how these IOU threshold affect detection? That what I am wondering.

**Comment by glenn-jocher** [comment]
@Nhatcao99 IoU is an NMS parameter.
