### ISSUE TITLE
when we test our dataset we found the generate json file is wrong.

### ISSUE THREAD

**Issue by jiangwenj02** [ultralytics/yolov5#3598]
## 🐛 Bug
when we test our dataset we found the generate json file is wrong.

## To Reproduce (REQUIRED)
the program convert pred bbox by follow function
def xyxy2xywh(x):
    # Convert nx4 boxes from [x1, y1, x2, y2] to [x, y, w, h] where xy1=top-left, xy2=bottom-right
    y = x.clone() if isinstance(x, torch.Tensor) else np.copy(x)
    y[:, 0] = (x[:, 0] + x[:, 2]) / 2  # x center
    y[:, 1] = (x[:, 1] + x[:, 3]) / 2  # y center
    y[:, 2] = x[:, 2] - x[:, 0]  # width
    y[:, 3] = x[:, 3] - x[:, 1]  # height
    return y

in fact, the json file required by coco, x[0] y[0] is top-left point not the center point.
it should be generate by follow function,
def xyxy2xywh2(x):
    # Convert nx4 boxes from [x1, y1, x2, y2] to [x, y, w, h] where xy1=top-left, xy2=bottom-right
    y = x.clone() if isinstance(x, torch.Tensor) else np.copy(x)
    y[:, 0] = x[:, 0]  # x center
    y[:, 1] = x[:, 1]  # y center
    y[:, 2] = x[:, 2] - x[:, 0]  # width
    y[:, 3] = x[:, 3] - x[:, 1]  # height
    return y

**Comment by glenn-jocher** [comment]
@jiangwenj02 pycocotools JSON file is generated correctly. It is used pycocotools to measure mAP on COCO in the YOLOv5 notebook:
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

<img width="1286" alt="Screenshot 2021-06-14 at 10 39 58" src="https://user-images.githubusercontent.com/26833433/121864200-ede58900-ccfc-11eb-8241-d1196f4c87bd.png">
