### ISSUE TITLE
Training issues

### ISSUE THREAD

**Issue by wjassim** [ultralytics/yolov5#3599]
## ❔Question

Hi, 
I am trying to train a custom data (coco128)  using the following command: 

python train.py --img 640 --batch 16 --epochs 5 --data coco128.yaml --weights yolov5s.pt

but training does not start due to the following errors: 

train: Scanning '..\coco128\labels\train2017.cache' images and labels... 128 found, 0 missing, 2 empty, 0 corrupted: 100%|██████████████████████████████████████████████████████████| 128/128 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\123\yolov5\utils\datasets.py", line 370, in __init__
    p = Path(p)  # os-agnostic
  File "D:\Program_Files\Anaconda3\envs\tf-gpu\lib\pathlib.py", line 1042, in __new__
    self = cls._from_parts(args, init=False)
  File "D:\Program_Files\Anaconda3\envs\tf-gpu\lib\pathlib.py", line 683, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "D:\Program_Files\Anaconda3\envs\tf-gpu\lib\pathlib.py", line 667, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 542, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 201, in train
    testloader = create_dataloader(test_path, imgsz_test, batch_size * 2, gs, single_cls,
  File "C:\Users\123\yolov5\utils\datasets.py", line 70, in create_dataloader
    dataset = LoadImagesAndLabels(path, imgsz, batch_size,
  File "C:\Users\123\yolov5\utils\datasets.py", line 386, in __init__
    raise Exception(f'{prefix}Error loading data from {path}: {e}\nSee {help_url}')
Exception: val: Error loading data from None: expected str, bytes or os.PathLike object, not NoneType
See https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data

How to solve this issue? 
Thanks a million..

**Comment by glenn-jocher** [comment]
@wjassim your error is not reproducible:
<img width="1342" alt="Screenshot 2021-06-14 at 11 21 10" src="https://user-images.githubusercontent.com/26833433/121869740-a2ce7480-cd02-11eb-9be6-76d130e32dcc.png">

We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by playground** [comment]
@wjassim did you get this resolved?  I'm getting the same error "Exception: val: Error loading data from None: expected str, bytes or os.PathLike object, not NoneType"

```
python3 train.py --img 640 --batch 16 --epochs 3 --data /server/datasets/Insects_v2/yaml/insects.yaml --weights yolov5s.pt
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 
  warn(f"Failed to load image Python extension: {e}")
train: weights=yolov5s.pt, cfg=, data=/server/datasets/Insects_v2/yaml/insects.yaml, hyp=data/hyps/hyp.scratch-low.yaml, epochs=3, batch_size=16, imgsz=640, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, noplots=False, evolve=None, bucket=, cache=None, image_weights=False, device=, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=8, project=runs/train, name=exp, exist_ok=False, quad=False, cos_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, seed=0, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest
github: up to date with https://github.com/ultralytics/yolov5 ✅
YOLOv5 🚀 v7.0-105-g226a5e4 Python-3.10.6 torch-1.13.1 CPU

hyperparameters: lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0
ClearML: run 'pip install clearml' to automatically track, visualize and remotely train YOLOv5 🚀 in ClearML
Comet: run 'pip install comet_ml' to automatically track and visualize YOLOv5 🚀 runs in Comet
TensorBoard: Start with 'tensorboard --logdir runs/train', view at http://localhost:6006/
Overriding model.yaml nc=80 with nc=5

                 from  n    params  module                                  arguments                     
  0                -1  1      3520  models.common.Conv                      [3, 32, 6, 2, 2]              
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]                
  2                -1  1     18816  models.common.C3                        [64, 64, 1]                   
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]               
  4                -1  2    115712  models.common.C3                        [128, 128, 2]                 
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]              
  6                -1  3    625152  models.common.C3                        [256, 256, 3]                 
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]              
  8                -1  1   1182720  models.common.C3                        [512, 512, 1]                 
  9                -1  1    656896  models.common.SPPF                      [512, 512, 5]                 
 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]              
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 12           [-1, 6]  1         0  models.common.Concat                    [1]                           
 13                -1  1    361984  models.common.C3                        [512, 256, 1, False]          
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]              
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 16           [-1, 4]  1         0  models.common.Concat                    [1]                           
 17                -1  1     90880  models.common.C3                        [256, 128, 1, False]          
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]              
 19          [-1, 14]  1         0  models.common.Concat                    [1]                           
 20                -1  1    296448  models.common.C3                        [256, 256, 1, False]          
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]              
 22          [-1, 10]  1         0  models.common.Concat                    [1]                           
 23                -1  1   1182720  models.common.C3                        [512, 512, 1, False]          
 24      [17, 20, 23]  1     26970  models.yolo.Detect                      [5, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
Model summary: 214 layers, 7033114 parameters, 7033114 gradients, 16.0 GFLOPs

Transferred 343/349 items from yolov5s.pt
optimizer: SGD(lr=0.01) with parameter groups 57 weight(decay=0.0), 60 weight(decay=0.0005), 60 bias
train: Scanning /server/datasets/Insects_v2/labels.cache... 16 images, 0 backgrounds, 0 corrupt: 100%|██████████| 16/16 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/server/yolov5/utils/dataloaders.py", line 467, in __init__
    p = Path(p)  # os-agnostic
  File "/usr/lib/python3.10/pathlib.py", line 960, in __new__
    self = cls._from_parts(args)
  File "/usr/lib/python3.10/pathlib.py", line 594, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.10/pathlib.py", line 578, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/server/yolov5/train.py", line 640, in <module>
    main(opt)
  File "/server/yolov5/train.py", line 529, in main
    train(opt.hyp, opt, device, callbacks)
  File "/server/yolov5/train.py", line 210, in train
    val_loader = create_dataloader(val_path,
  File "/server/yolov5/utils/dataloaders.py", line 124, in create_dataloader
    dataset = LoadImagesAndLabels(
  File "/server/yolov5/utils/dataloaders.py", line 483, in __init__
    raise Exception(f'{prefix}Error loading data from {path}: {e}\n{HELP_URL}') from e
Exception: val: Error loading data from None: expected str, bytes or os.PathLike object, not NoneType
See https://docs.ultralytics.com/yolov5/tutorials/train_custom_data

```
