### ISSUE TITLE
Use one YOLO model for n applications

### ISSUE THREAD

**Issue by gondimjoaom** [ultralytics/yolov5#3600]
## ❔Is there a way to load just one model and make predictions for 6 (for example) applications?

I know it can be done with NVIDIA's TensorRT, but does anyone know a different solution? I have 6 cameras sending frames into 6 different dockers and each of them loads one YOLOv5s model into GPU, but since there are 6 models, GPU memory sometimes can't handle it.

Any help or ideias are welcome :)

**Comment by glenn-jocher** [comment]
@gondimjoaom pass your sources to the same model.

**Comment by gondimjoaom** [comment]
I know it is probably a dumb question, but is there a way to increase the batch_size of the predict function? Or should I just call in parallel the same pred = model(img, augment=opt.augment)[0] function?

**Comment by glenn-jocher** [comment]
@gondimjoaom see YOLOv5 **PyTorch Hub** tutorial for batched inference examples:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by gondimjoaom** [comment]
thanks!!!
