### ISSUE TITLE
libtorch deploy error 

### ISSUE THREAD

**Issue by xiaolongDGitHub** [ultralytics/yolov5#3601]
export yolov5x6.torchscript.pt successful (have warnings:yolov5-master\models\yolo.py:57: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if self.grid[i].shape[2:4] != x[i].shape[2:4] or self.onnx_dynamic: ),
but when load the file with libtorch in c++,get an error :
0x00007FFB77CC286E (ucrtbase.dll) (xxx.exe 中)处有未经处理的异常: 请求了严重的程序退出。
how to deal this error ,thanks!

**Comment by xiaolongDGitHub** [comment]
thanks,@github-actions
export success,
load the yolov5x6.torchscript.pt success;
but forward  get a error,   
modelImageSize=(640,384) in the second picture
 
![微信图片_20210614135409](https://user-images.githubusercontent.com/46679084/121845459-0dd67600-cd18-11eb-9b89-3e5105ef7267.png)
![微信图片_20210614135420](https://user-images.githubusercontent.com/46679084/121845468-0fa03980-cd18-11eb-8497-0099391da9fb.png)

**Comment by glenn-jocher** [comment]
@xiaolongDGitHub I'm sorry, we don't C deployment experience so I can't help with this particular error. If the error is related to the export warning you may need to reconfigure your Detect() layer to avoid the warning.

**Comment by xiaolongDGitHub** [comment]
thanks,@glenn-jocher
I solved the  runtime error, I input the wrong image size.
