### ISSUE TITLE
Position of bounding boxes is  not correct in training data

### ISSUE THREAD

**Issue by HassanAsghar1** [ultralytics/yolov5#3606]
## ❔Question
The position of bounding boxes is at right position in my custom dataset .When i used this data for training in yolov5 then the bounding boxes got  misplaced due to padding (resizing) .Please let me know how i can fix this issue .

My custom data :
![image](https://user-images.githubusercontent.com/72445645/121884943-d4037080-cd13-11eb-9723-3b814d45fb7a.png)

Training batch image :
![image](https://user-images.githubusercontent.com/72445645/121884653-766f2400-cd13-11eb-8257-0ada46de2a6f.png)

**Comment by HassanAsghar1** [comment]
image size  = (60,140,3)

**Comment by glenn-jocher** [comment]
@HassanAsghar1 your labels are incorrect. You must fix your labels.
