### ISSUE TITLE
IOU threshold used in test.py to plot the precision, recall and F1 curves?

### ISSUE THREAD

**Issue by dariogonle** [ultralytics/yolov5#3607]
## ❔Question
In test.py these 2 curves are ploted, but to count a prediction as TP is necessary to use a IOU threshold. Which is used? Where can I change it?

## Additional context
For example in this image the Precision is calculated. Which IOU is used?
![P_curve](https://user-images.githubusercontent.com/80393891/121886547-ce0e8f00-cd15-11eb-90df-6dd78a34d998.png)

**Comment by glenn-jocher** [comment]
@dariogonle see metrics.py for metrics computation:
https://github.com/ultralytics/yolov5/blob/master/utils/metrics.py

**Comment by dariogonle** [comment]
Thank you @glenn-jocher, but I cannot see where the iou for cont a prediction as TP is set. 

https://github.com/ultralytics/yolov5/blob/f8adee156de27b97932311af5cf8755815f15328/utils/metrics.py#L19-L79


Is the image above taken for a iou = 0.5? How can I change the iou threshold?

**Comment by glenn-jocher** [comment]
@dariogonle iou vector index 0 is used. iou vector is 0.5:0.05:0.95.
https://github.com/ultralytics/yolov5/blob/239a11c19777d8b5d4e2a69aac2cc83796313fd3/utils/metrics.py#L56-L63

**Comment by dariogonle** [comment]
'''
sf
'''

**Comment by dariogonle** [comment]
Thank you so much @glenn-jocher. I got it.

Just for clarification for other users. It you want the precision and recall for an iou of 0.55, you just need to use the following code.

```
# Recall 
recall = tpc / (n_l + 1e-16)  # recall curve
r[ci] = np.interp(-px, -conf[i], recall[:, 1], left=0)  # recall[:, i]  i=>[0.5, 0.95]

# Precision
precision = tpc / (tpc + fpc)  # precision curve
p[ci] = np.interp(-px, -conf[i], precision[:, 1], left=1)  # precision[:, i]  i=>[0.5, 0.95]
```

@glenn-jocher could you confirm this is correct?

**Comment by glenn-jocher** [comment]
@dariogonle yes that's correct!

**Comment by Yu-Hang** [comment]
@glenn-jocher So in val.py, Precision and Recall are calculated with iou=0.5 by default?

**Comment by Yu-Hang** [comment]
It seems like Precision and Recall are estimation from the precision and recall curves?

`Infected          1          4      0.665      0.497      0.577      0.346`

I tested the val.py with only 1 image. My Infected class have 4 labels, and the recall is 0.497. This proves that these numbers are estimations from the curves. I wonder why do you use the estimations rather than actually calculate them?

**Comment by glenn-jocher** [comment]
@Yu-Hang I don't understand your question. Estimation is a completely different field of statistics and is not employed anywhere in YOLOv5.

**Comment by Yu-Hang** [comment]
I don't understand this line:
        `recall = tpc / (n_l + eps)  # recall curve`
     
Why add eps? Can you explain or provide reference? Thanks.

**Comment by glenn-jocher** [comment]
Protected divide
