### ISSUE TITLE
Action Recognition

### ISSUE THREAD

**Issue by hareskoruz** [ultralytics/yolov5#3613]
I am Having a Doubt whether the detected bounding box output alone can be cut out and use it for action recgnition?

## Additional context
Is there any provisions already or have to create a file to fetch from result?
If so, please provide code.

**Comment by glenn-jocher** [comment]
@hareskoruz you can create crops from detections with `python detect.py --save-crop` or from YOLOv5 pytorch hub results using `results.crop()`

**Comment by hareskoruz** [comment]
there is no provision of --save-crop arg parser in code.

**Comment by glenn-jocher** [comment]
@hareskoruz you can create crops from detections with `python detect.py --save-crop` or from YOLOv5 pytorch hub results using `results.crop()`

https://github.com/ultralytics/yolov5/blob/65f81bfefa7ea1f4fdd019dae9b675b7914e0c21/detect.py#L187

**Comment by manarelshahawy** [comment]
thanks so much @glenn-jocher 
I detected persons and cropped how can identify their activities from cropped images

**Comment by hareskoruz** [comment]
@glenn-jocher  Thanks for that..
Actually the need is , I have a model for detecting actions.. which predicts result , but needs bounding box..
can detect.py in any way helps for it?
