### ISSUE TITLE
Stop-frame video

### ISSUE THREAD

**Issue by Ann021** [ultralytics/yolov5#3616]
Hello!
Can you please tell me if I can stop frame the video every second when an object is detected and save the images to a folder?
I will be very grateful for the answer!
Thanks!

**Comment by glenn-jocher** [comment]
@Ann021 detect.py automatically saves detections in images and videos:
```
python detect.py
```

**Comment by Ann021** [comment]
Thanks you!
But 
Can I save frames from the video somehow?
