### ISSUE TITLE
How to know inference size from the weight (.pt) file?

### ISSUE THREAD

**Issue by davidten0921** [ultralytics/yolov5#3618]
## ❔
I have followed the instruction to train the model for object detection successfully.
However, I have noticed that the inference size must be given from outside parameters.
I know this size should be the same as training phase.
But what if when I don't know the inference size on given a new weight file from others?

**Comment by glenn-jocher** [comment]
@davidten0921 default inference size for official models is 640 for P5 models and 1280 for P6 models.

**Comment by amfogor** [comment]
@glenn-jocher but people train with their own sizes. It would be really nice to have it stored in the checkpoint. Otherwise it becomes quite difficult to keep track of it to use the right size for inference...

**Comment by glenn-jocher** [comment]
@amfogor yes that's true. Thanks for the feedback, we'll take it under consideration for future updates.
