### ISSUE TITLE
Need help aggregating the feature maps into smaller data

### ISSUE THREAD

**Issue by tserdar** [ultralytics/yolov5#3619]
Can anyone help me understand what are the dimensions of the feature vectors explicitly for and how can I use them for my application? 

**My actual problem:** 
- I want to calculate similarity based on image features calculated by the network. 
- Using the features I obtain using yolov5m cause computational problems as I have to load these vectors for hundreds of images and perform operations on them. 

In my application in particular, I get 3 sets of feature maps for a single image flowing into the `Detect` layer. Their dimensions are:

1. ` 192 x 32 x 40 ` 
2. ` 384 x 16 x 20 `
3. ` 768 x 8 x 10`

**My actual question:**
- How can I downsize/dimensionally-reduce these data for similarity checking purposes?

**Comment by glenn-jocher** [comment]
@rocketsfallonrocketfalls you may want to see AdaptiveAvgPool2d for averaging over the last 2 spatial dimensions.

https://pytorch.org/docs/stable/generated/torch.nn.AdaptiveAvgPool2d.html

**Comment by glenn-jocher** [comment]
@rocketsfallonrocketfalls good news 😃! Feature map visualization was added ✅ in PR #3804 by @Zigars today. This allows for visualizing feature maps from any part of the model from any function (i.e. detect.py, train.py, test.py). Feature maps are saved as *.png files in runs/features/exp directory. To turn on feature visualization set `feature_vis=True` in the model forward method and define the layer you want to visualize (default is SPP layer).

https://github.com/ultralytics/yolov5/blob/20d45aa4f18d7df7148fc6dd69a9c0607003f004/models/yolo.py#L158-L160

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

![layer_8_SPP_features](https://user-images.githubusercontent.com/26833433/123628234-27e17f80-d813-11eb-8d72-5d5560cd9ee4.png)

**Comment by tserdar** [comment]
@glenn-jocher, @Zigars, that's great news, thanks a lot!

**Comment by tserdar** [comment]
2D Pooling seems to work fine for now :)
