### ISSUE TITLE
Question about the size of weight

### ISSUE THREAD

**Issue by logic03** [ultralytics/yolov5#362]
May I ask how you got the yolov5L.pt/yolov5m.pt? Is it best.pt using coco datasets in the corresponding config? If I need to change my network structure, how do I get a pre-loaded weight like the yolov5l.pt that you provided?

Why is the best.pt of yolov5L network 'size I trained is 700+MB , instead of the 91.5MB you provided?

**Comment by glenn-jocher** [comment]
@logic03 to reproduce see https://github.com/ultralytics/yolov5#reproduce-our-training

Multi-gpu checkpoint size issue already open in #253 

Closing as duplicate.
