### ISSUE TITLE
changing torch.cudnn.benchmark bring same inference speed on video sources.

### ISSUE THREAD

**Issue by fabiozappo** [ultralytics/yolov5#3620]
## ❔Question

Hi Glenn, I'm a big fan of yolov5 and I always use it in my ML projects. 

Now I would like to improve speed performance on my source which is a set of video clips having all the same resolution. I expected that setting torch.cudnn.benchmark = True would bring better performance cause all frame shapes are equal. 
However results are the same, as you can see from following lines.

Results (benchmark = False):  608x800 Done. (0.016s)
Results (benchmark = True):  608x800 Done. (0.016s)

Also changing cudnn.benchmark from True to False in webcam inference in detect.py does not change inference speed. I have a gtx 1080, do you have any idea about the reason of this behaviour?

Thanks

**Comment by glenn-jocher** [comment]
@fabiozappo results will vary by hardware, software, drivers etc. 

On some hardware cudnn.benchmark may help process subsequent images faster as long as the inference input shape doesn't change.

**Comment by fabiozappo** [comment]
Ok, I'll do some tests on different gpus!
