### ISSUE TITLE
RuntimeError: Sizes of tensors must match except in dimension 2. Got 25 and 26 (The offending index is 0)

### ISSUE THREAD

**Issue by xiaowanzizz** [ultralytics/yolov5#3625]
🐛 Bug

I modified the yolov5 detect head.
This model can train normally.
I also get the labels.png,precison-recall_curve.png,result.txt......,but when i run the (Python test.py),there're some errors.

# YOLOv5 head
head:
  [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, BottleneckCSP, [512, False]],  # 13

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, BottleneckCSP, [256, False]],  # 17 (P3/8-small)

   [-1, 1, Conv, [128, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 2], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, BottleneckCSP, [128, False]],  

   [-1, 1, Conv, [128, 3, 2]],
   [[-1, 18], 1, Concat, [1]],  # cat head P4
   [-1, 3, BottleneckCSP, [256, False]],  # 20 (P4/16-medium)

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 14], 1, Concat, [1]],  # cat head P5
   [-1, 3, BottleneckCSP, [512, False]],  # 23 (P5/32-large)

   [[21, 24, 27], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
  ]

Input:
```
python test.py --data ...... --weights run/exp1/weights/best.pt
```

Output:
```
Traceback (most recent call last):
  File "test.py", line 278, in <module>
    test(opt.data,
  File "test.py", line 107, in test
    inf_out, train_out = model(img, augment=augment)  # inference and training outputs
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/zzf/yolov5-3.1/models/yolo.py", line 116, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/root/zzf/yolov5-3.1/models/yolo.py", line 136, in forward_once
    x = m(x)  # run
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/zzf/yolov5-3.1/models/common.py", line 157, in forward
    return torch.cat(x, self.d)
RuntimeError: Sizes of tensors must match except in dimension 2. Got 25 and 26 (The offending index is 0)
```

## Environment
pytorch1.7.1

 - OS: [Ubuntu18.04]
 - GPU [2080 Ti]

My English is very poor, if you have any offence, please forgive me

**Comment by VdLMV** [comment]
I have got error messages similar like this when I had forget to resize the images to a multiple of 32.
Maybe this help.

**Comment by xiaowanzizz** [comment]
@VdLMV  thank you
Where should I change the code?
In test.py,the default img-size is 640

**Comment by VdLMV** [comment]
@xiaowanzizz It that case your image size is a multiple of 32 and you have an another issue with your code
