### ISSUE TITLE
Pretrained model does not work with pytorch Tensors

### ISSUE THREAD

**Issue by guidopetri** [ultralytics/yolov5#3626]
## Bug
Loading the pretrained YOLOv5 model from PyTorch Hub and then running it with a PyTorch Tensor fails.

## To Reproduce (REQUIRED)

Input:
```
import torch as pt

model = pt.hub.load('ultralytics/yolov5', 'yolov5x', pretrained=True)
model(pt.zeros(1,3,720,1280))
```

Output:
```
RuntimeError                              Traceback (most recent call last)
<ipython-input-38-937812e0ad5e> in <module>
      1 t = pt.Tensor(image.transpose(2, 0, 1)).unsqueeze(0)
      2 
----> 3 model(pt.zeros(1,3,720,1280))

c:\python39\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
    887             result = self._slow_forward(*input, **kwargs)
    888         else:
--> 889             result = self.forward(*input, **kwargs)
    890         for hook in itertools.chain(
    891                 _global_forward_hooks.values(),

c:\python39\lib\site-packages\torch\autograd\grad_mode.py in decorate_context(*args, **kwargs)
     25         def decorate_context(*args, **kwargs):
     26             with self.__class__():
---> 27                 return func(*args, **kwargs)
     28         return cast(F, decorate_context)
     29 

~/.cache\torch\hub\ultralytics_yolov5_master\models\common.py in forward(self, imgs, size, augment, profile)
    255         if isinstance(imgs, torch.Tensor):  # torch
    256             with amp.autocast(enabled=p.device.type != 'cpu'):
--> 257                 return self.model(imgs.to(p.device).type_as(p), augment, profile)  # inference
    258 
    259         # Pre-process

c:\python39\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
    887             result = self._slow_forward(*input, **kwargs)
    888         else:
--> 889             result = self.forward(*input, **kwargs)
    890         for hook in itertools.chain(
    891                 _global_forward_hooks.values(),

~/.cache\torch\hub\ultralytics_yolov5_master\models\yolo.py in forward(self, x, augment, profile)
    121             return self.forward_augment(x)  # augmented inference, None
    122         else:
--> 123             return self.forward_once(x, profile)  # single-scale inference, train
    124 
    125     def forward_augment(self, x):

~/.cache\torch\hub\ultralytics_yolov5_master\models\yolo.py in forward_once(self, x, profile)
    152                 logger.info(f'{dt[-1]:10.2f} {o:10.2f} {m.np:10.0f}  {m.type}')
    153 
--> 154             x = m(x)  # run
    155             y.append(x if m.i in self.save else None)  # save output
    156 

c:\python39\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
    887             result = self._slow_forward(*input, **kwargs)
    888         else:
--> 889             result = self.forward(*input, **kwargs)
    890         for hook in itertools.chain(
    891                 _global_forward_hooks.values(),

~/.cache\torch\hub\ultralytics_yolov5_master\models\common.py in forward(self, x)
    208 
    209     def forward(self, x):
--> 210         return torch.cat(x, self.d)
    211 
    212 
RuntimeError: Sizes of tensors must match except in dimension 1. Got 46 and 45 in dimension 2 (The offending index is 1)

```

## Expected behavior
The pretrained model can take PyTorch Tensors as input.

## Environment

 - OS: Windows 10
 - GPU: N/A

## Additional context
The pretrained model works fine with numpy arrays in the way described in #36 . Not sure why, but the model fails no matter what shape the Tensor is.

**Comment by glenn-jocher** [comment]
@charlesoblack this is not a bug. You've passed an incorrectly shaped image to a YOLOv5 model. P5 models like YOLOv5x are constrained to operate on stride-32 multiple image sizes. 720 does not meet this criteria, hence the expected crash.

PyTorch Hub models automatically handle PIL, Numpy, filename, URL inputs to apply correct padding and offsets during pre and postprocessing, so you can pass the same model any shape image from these sources.

**Comment by guidopetri** [comment]
That Tensor is exactly the one described in #36 though. What is the expected Tensor shape for YOLOv5x?

**Comment by glenn-jocher** [comment]
@charlesoblack ah, I understand the confusion. This area of the code has been updated in master to reflect this a while back, but the tutorial was not updated to point to the new code. I'll do that now.
https://github.com/ultralytics/yolov5/blob/30e4c4f09297b67afedf8b2bcd851833ddc9dead/models/common.py#L243-L252

**Comment by glenn-jocher** [comment]
@charlesoblack tutorial has been updated.

**Comment by guidopetri** [comment]
Thanks! Could you also explain why the stride-32 length? That was not clear to me either.

**Comment by glenn-jocher** [comment]
@charlesoblack see release notes for comments on strides:
https://github.com/ultralytics/yolov5/releases/tag/v5.0

**Comment by guidopetri** [comment]
Cool, thanks!

**Comment by guidopetri** [comment]
@glenn-jocher sorry, clarifying question - you said:

| PyTorch Hub models automatically handle PIL, Numpy, filename, URL inputs to apply correct padding and offsets during pre and postprocessing, so you can pass the same model any shape image from these sources.

Does this mean that the pytorch hub model will also convert to tensor and use CUDA if available automatically? Or does this run strictly on CPU if it is not a tensor?

**Comment by glenn-jocher** [comment]
@charlesoblack YOLOv5 PyTorch Hub models default to CUDA device 0 if available else CPU.
