### ISSUE TITLE
Image resize function in detect.py

### ISSUE THREAD

**Issue by mansi-aggarwal-2504** [ultralytics/yolov5#3628]
Where and how is the image being resized while running `detect.py`?
Debugging didn't quite point me to it. Is `cv2.resize` being used or something else? Can someone point me to the function/ module where input image is being resized to `--img-size` parameter?

**Comment by glenn-jocher** [comment]
@mansi-aggarwal-2504 see detect.py dataloaders:
https://github.com/ultralytics/yolov5/blob/6c0e1d9fd7fe83a28972d4f35b2111553de0fcb6/detect.py#L69-L77
