### ISSUE TITLE
export to onnx use --half flag error

### ISSUE THREAD

**Issue by Wenboisstrong** [ultralytics/yolov5#3631]
## ❔Question
I try to export the yolo5s pre-trained model to fp16 test speed

run export.py --dynamic --half --device 0 --weights ../weights/yolo5s.pt --include onnx 

I get the error onnx： export failure Input, output and indices must be on the current device

I pulled the latest code
My environment ：

python 3.7
torch 1.7.0
onnx 1.9.0

I saw the same problem in the historical version,and I tried to check the device location of the variable, but to no avail, I hope I can get help. Thanks

**Comment by glenn-jocher** [comment]
@Wenboisstrong not all combination of arguments will work correctly when exporting. For ONNX exports you may want to leave these on the default device (CPU).

**Comment by Wenboisstrong** [comment]
@glenn-jocher  Thank you for your reply, but if I want to used fp16, I don’t  need --half and --device 0? When it seems to use --half, some data devices are different, but I tried to find them without success

**Comment by LeoCyclope** [comment]
Hi Guys,
I am having a similar issue, I am trying to generate an F16 ONNX model but when I try to export,  here is the issue:

`ONNX: export failure: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking arugment for argument index in method wrapper_index_select)
`

Did anyone succeed to generate an F16 precision ONNX model?

Thanks in advance,

**Comment by yinghuang** [comment]
> Hi Guys,
> I am having a similar issue, I am trying to generate an F16 ONNX model but when I try to export, here is the issue:
> 
> `ONNX: export failure: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking arugment for argument index in method wrapper_index_select) `
> 
> Did anyone succeed to generate an F16 precision ONNX model?
> 
> Thanks in advance,

[https://github.com/ultralytics/yolov5/issues/251#issuecomment-905363098](url)

**Comment by yinghuang** [comment]
The problem is caused by **dtype mismatch from constant tensors** in yolo.py--class Detect--forward.
More specifically, they are **self.grid[i]**, **self.anchor_grid[i]** and **self.stride[i]** which should have save dtype with **x[i]**.

Here is my solution,
![X5)@GB3JN PJXMX9~NBST`M](https://user-images.githubusercontent.com/22361533/130772211-77a80f4d-a163-42e9-8a0c-189bcb53f657.png)


Maybe it is not the best, it should works.

**Comment by glenn-jocher** [comment]
@Wenboisstrong @yinghuang good news 😃! Your original issue may now be fixed ✅ in PR #5110 by @SamFC10. This PR implements backend-device change improvements to allow for **YOLOv5 models to be exported to ONNX on either GPU or CPU, and to export at FP16 with the `--half` flag on GPU `--device 0`**.

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by minhnvl** [comment]
@glenn-jocher  Thanks for your fixing and updating, I could convert YOLOv5 models to ONNX, but it just got successful without --dynamic. I still get the error when adding the --dynamic. Could you check and fix it with the --dynamic. Thanks 
**Error:**
_ONNX: export failure: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking arugment for argument index in method wrapper_index_select)_

**Comment by glenn-jocher** [comment]
@minhnvl yes I see this bug also. I'm able to reproduce but I'm not certain the cause. I'd recommend using --half or --dynamic, but not both until there is a solution for this.

**Comment by data-ant** [comment]
> 

hi.How did you solve the problem when fix it with --dynamic
