### ISSUE TITLE
What's the difference between 'ema' and 'model' in checkpoints

### ISSUE THREAD

**Issue by puglial** [ultralytics/yolov5#3636]
## ❔Question

Hello, what is the difference between the model stored in the field `ema` and the model stored in the field `model` of the checkpoint? they seems to have the same structure but different weights but as far as I understand the `forward()` seems to be same, are they just trained in different ways? how `ExponentialMovingAverage` plays a role in this?

Thanks for the answer

**Comment by glenn-jocher** [comment]
@lpuglia When training a model, it is often beneficial to maintain moving averages of the trained parameters. Evaluations that use averaged parameters sometimes produce significantly better results than the final trained values.

The apply() method adds shadow copies of trained variables and add ops that maintain a moving average of the trained variables in their shadow copies. It is used when building the training model. The ops that maintain moving averages are typically run after each training step. The average() and average_name() methods give access to the shadow variables and their names. They are useful when building an evaluation model, or when restoring a model from a checkpoint file. They help use the moving averages in place of the last trained values for evaluations.

The moving averages are computed using exponential decay. You specify the decay value when creating the ExponentialMovingAverage object. The shadow variables are initialized with the same initial values as the trained variables. When you run the ops to maintain the moving averages, each shadow variable is updated with the formula:

shadow_variable -= (1 - decay) * (shadow_variable - variable)

This is mathematically equivalent to the classic formula below, but the use of an assign_sub op (the "-=" in the formula) allows concurrent lockless updates to the variables:

shadow_variable = decay * shadow_variable + (1 - decay) * variable

Reasonable values for decay are close to 1.0, typically in the multiple-nines range: 0.999, 0.9999, etc.

See https://www.tensorflow.org/api_docs/python/tf/train/ExponentialMovingAverage for more details

**Comment by puglial** [comment]
very interesting, thanks, i trained a yolov5s model using `relu` instead of `silu`, the `model` model has an mAP@.5  of 0.451, meanwhile the `ema` model has 0.541, is it the `ema` version more computationl intensive in any way during testing (e.g. extra operations performed) ?

**Comment by glenn-jocher** [comment]
@lpuglia no
