### ISSUE TITLE
W&B Exception: CondaEnvException: Unable to determine environment

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/yolov5#3639]
@AyushExel I've noticed a new message popping up in Docker trainings when logged in with W&B. Training and logging seem to operate correctly, but again we'd rather not display warnings to users if possible:
<img width="1221" alt="Screenshot 2021-06-16 at 12 41 28" src="https://user-images.githubusercontent.com/26833433/122205508-9aac3b80-cea0-11eb-8e44-a5954acdcf36.png">

## To Reproduce

```bash
# Pull latest docker
t=ultralytics/yolov5:latest && sudo docker pull $t && sudo docker run -it --ipc=host --gpus all $t

# Re-clone YOLOv5 (may not be necessary to reproduce)
cd .. && rm -rf app && git clone https://github.com/ultralytics/yolov5 -b master app && cd app

# W&B
pip install --upgrade pip wandb && wandb login API_KEY_HERE

# Train
python train.py
```

**Comment by AyushExel** [comment]
@glenn-jocher thanks for reporting. I'll ask someone to take a look

**Comment by glenn-jocher** [comment]
@AyushExel thanks! BTW the exact run that produced this is here (though all Docker runs seem to produce this now).
https://wandb.ai/glenn-jocher/study-mixup-coco/runs/3pc3i0tj
