### ISSUE TITLE
IndexError: index 77 is out of bounds for axis 0 with size 21

### ISSUE THREAD

**Issue by Mahsa-Nobakht** [ultralytics/yolov5#3643]
## ❔Question
I trained yolov5 on voc dataset  in colab after that I ran test.py then I got this error
I can't solve it
can u please help me?
thank u

## Additional context

Namespace(augment=False, batch_size=32, conf_thres=0.001, data='data/voc.yaml', device='', exist_ok=False, img_size=640, iou_thres=0.6, name='exp', project='runs/test', save_conf=False, save_hybrid=False, save_json=False, save_txt=False, single_cls=False, task='val', verbose=False, weights='yolov5m.pt')
YOLOv5 🚀 2021-5-27 torch 1.8.1+cu101 CUDA:0 (Tesla T4, 15109.75MB)

Fusing layers... 
Model Summary: 308 layers, 21356877 parameters, 0 gradients
val: Scanning '../VOC/labels/val.cache' images and labels... 4952 found, 0 missing, 0 empty, 0 corrupted: 100% 4952/4952 [00:00<00:00, 52850364.91it/s]
               Class      Images      Labels           P           R      mAP@.5  mAP@.5:.95:   0% 0/155 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "test.py", line 329, in <module>
    opt=opt
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "test.py", line 187, in test
    confusion_matrix.process_batch(predn, torch.cat((labels[:, 0:1], tbox), 1))
  File "/content/drive/My Drive/yolov5-master/utils/metrics.py", line 148, in process_batch
    self.matrix[detection_classes[m1[j]], gc] += 1  # correct
IndexError: index 77 is out of bounds for axis 0 with size 21

**Comment by glenn-jocher** [comment]
@mahsant your command is incorrect. You are attempting to test a COCO trained model on the VOC dataset.

**Comment by Mahsa-Nobakht** [comment]
> @mahsant your command is incorrect. You are attempting to test a COCO trained model on the VOC dataset.

Sorry for delay
Tnx for your support
