### ISSUE TITLE
Automatic batch size

### ISSUE THREAD

**Issue by Quaentor** [ultralytics/yolov5#3648]
Would be quite nice have an option to set the maximum possible batch size automatically

**Comment by glenn-jocher** [comment]
@Quaentor thanks for the feedback! Yes it would be nice to have an option to determine the batch size automatically, i.e.
```
python train.py --batch auto
```

The only way I can think of though is to start trainings in a subloop at increasing batch sizes until one crashes, then revert to the last good batch size. I don't know if this op can proceed in isolation with affecting your system at all. But we will keep it in mind for future releases.

**Comment by EvelinaAleksiutenko** [comment]
Hi, @glenn-jocher. I trained the model with --batch -1, and then I found by using W & B that the batch size was 52. Shouldn't the batch size be a power of two?

Thank you for your time.

**Comment by glenn-jocher** [comment]
Hi @EvelinaAlexiutenko. The requirement for a batch size to be a power of two is more of a convention than a strict rule. While a power of two can often lead to better GPU utilization, it's not always necessary. In your case, a batch size of 52 is valid and can offer good training performance as well. Feel free to experiment with different batch sizes to find the best fit for your specific use case. Thank you for using YOLOv5!
