### ISSUE TITLE
Cannot load model using torch.hub

### ISSUE THREAD

**Issue by matthewfranglen** [ultralytics/yolov5#365]
## 🐛 Bug
I cannot use your `hubconf.py` to load the model.

## To Reproduce (REQUIRED)

Input:
```python
import torch.hub

# all of these fail
model = torch.hub.load("ultralytics/yolov5", "yolov5s", pretrained=True)
model = torch.hub.load("ultralytics/yolov5", "yolov5m", pretrained=True)
model = torch.hub.load("ultralytics/yolov5", "yolov5l", pretrained=True)
```

Output:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-6-f8aae7484cc6> in <module>
----> 1 model = torch.hub.load("ultralytics/yolov5", "yolov5l", pretrained=True)

~/.cache/pypoetry/virtualenvs/dl-ultralytics-yolo-kIMoBkIY-py3.7/lib/python3.7/site-packages/torch/hub.py in load(github, model, *args, **kwargs)
    367     entry = _load_entry_from_hubconf(hub_module, model)
    368 
--> 369     model = entry(*args, **kwargs)
    370 
    371     sys.path.remove(repo_dir)

~/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py in yolov5l(pretrained, channels, classes)
     78         pytorch model
     79     """
---> 80     return create('yolov5l', pretrained, channels, classes)
     81 
     82 

~/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py in create(name, pretrained, channels, classes)
     34         google_utils.attempt_download(ckpt)  # download if not found locally
     35         state_dict = torch.load(ckpt, map_location=torch.device('cpu'))['model'].float().state_dict()  # to FP32
---> 36         state_dict = {k: v for k, v in state_dict.items() if model.state_dict()[k].shape == v.shape}  # filter
     37         model.load_state_dict(state_dict, strict=False)  # load
     38     return model

~/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py in <dictcomp>(.0)
     34         google_utils.attempt_download(ckpt)  # download if not found locally
     35         state_dict = torch.load(ckpt, map_location=torch.device('cpu'))['model'].float().state_dict()  # to FP32
---> 36         state_dict = {k: v for k, v in state_dict.items() if model.state_dict()[k].shape == v.shape}  # filter
     37         model.load_state_dict(state_dict, strict=False)  # load
     38     return model

KeyError: 'model.2.cv1.conv.weight'
```

## Expected behavior
The model should be created and the pretrained weights should be loaded.

**Comment by glenn-jocher** [comment]
@matthewfranglen this issue is not reproducible. Open a blank colab notebook, update pyyaml, restart and import the model. Everything works correctly here. If you are seeing errors you may want to delete the local cache that is being used and retry.

<img width="1244" alt="Screen Shot 2020-07-11 at 9 35 54 AM" src="https://user-images.githubusercontent.com/26833433/87229054-f3528a80-c359-11ea-9a70-99481e5c2a3b.png">

**Comment by matthewfranglen** [comment]
Deleting the cache file fixed the problem. Thank you for the speedy response.

**Comment by glenn-jocher** [comment]
@matthewfranglen yes, this is happening because the repo is changing fast, and we are introducing breaking changes in the process. 

I wonder if we could wrap the entire hub loading function in a try except to notify future users to delete their cache when a failure occurs.

**Comment by matthewfranglen** [comment]
I think that would help a lot

**Comment by glenn-jocher** [comment]
All done. Relevant code wrapped in try except clause now. Seems like a great idea. 
https://github.com/ultralytics/yolov5/blob/a5818b280edcc983cb6bec626f36db50a5221f68/hubconf.py#L31-L43

**Comment by hysaint** [comment]
Dear esteemed author:
 yeah i delete the cache ,however the commad continuning leave the error message Exception: Cache maybe be out of date, try force_reload=True. See https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading for help.   I try to add the force_reload=True argument but still not work.Could u plz help me to find out the solution？ Thanks

**Comment by glenn-jocher** [comment]
@hysaint YOLOv5 hub works correctly. Paste the following code into a new Colab notebook:
```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)

# Images
dir = 'https://github.com/ultralytics/yolov5/raw/master/data/images/'
imgs = [dir + f for f in ('zidane.jpg', 'bus.jpg')]  # batched list of images

# Inference
results = model(imgs)
results.print()  # or .show(), .save()
```

You'll see this:
<img width="1430" alt="Screen Shot 2021-01-26 at 11 50 05 AM" src="https://user-images.githubusercontent.com/26833433/105897197-b89a0200-5fcc-11eb-85e5-168f9286fcc2.png">

**Comment by hysaint** [comment]
@glenn-jocher  very thankful .it works great
