### ISSUE TITLE
two classes have the same box

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#3651]
SafetyHelmetWearing-Dataset
It has two classes , one is person the other is helmet
like this 
![image](https://user-images.githubusercontent.com/59388989/122323887-68f7ab00-cf5a-11eb-9ad6-d0be423a9071.png)

But I meet the problem 
when the person and head are similarity size
It will happen the status
red is person , blue is helmet
![image](https://user-images.githubusercontent.com/59388989/122324279-1c609f80-cf5b-11eb-84cc-09d6777608e7.png)

**Comment by shershunov** [comment]
Add those photos with false detections to the dataset.
