### ISSUE TITLE
Segmentation Fault(core dumped) error while running python3 test.py --data coco128.yaml --weights yolov5s.pt

### ISSUE THREAD

**Issue by jaskiratsingh2000** [ultralytics/yolov5#3653]
Hey @glenn-jocher I tried running the following command `python3 test.py --data coco128.yaml --weights yolov5s.pt` and got the following error:

```
Namespace(augment=False, batch_size=32, conf_thres=0.001, data='./data/coco128.yaml', device='', exist_ok=False, half=False, imgsz=640, iou_thres=0.6, name='exp', project='runs/test', save_conf=False, save_hybrid=False, save_json=False, save_txt=False, single_cls=False, task='val', verbose=False, weights=['yolov5s.pt'])
YOLOv5 🚀 v5.0-192-g30e4c4f torch 1.7.0a0+e85d494 CPU

Fusing layers... 
Model Summary: 224 layers, 7266973 parameters, 0 gradients
val: Scanning '../coco128/labels/train2017.cache' images and labe
val: Scanning '../coco128/labels/train2017.cache' images and labe
val: Scanning '../coco128/labels/train2017.cache' images and labe
val: Scanning '../coco128/labels/train2017.cache' images and labe
val: Scanning '../coco128/labels/train2017.cache' images and labe
               Class     Images     Labels          P          R Segmentation fault (core dumped)
```

@glenn-jocher I don't have any idea about this error rectification. Your help would be highly appreciable in this. Thanks

**Comment by tserdar** [comment]
Can you try removing `.cache` files (in the parent folder of labels for both train and validation sets) and try again?

I sort of remember this happened to me when I made changes in the training/validation sets but the caches were outdated. (I think?)

**Comment by jaskiratsingh2000** [comment]
@rocketsfallonrocketfalls Can you please exactly let me know that what steps I have to follow exactly. That would be of great help

**Comment by jaskiratsingh2000** [comment]
@rocketsfallonrocketfalls Moreover I don't have any `.cache` file within my whole yolov5 folder. How can I do that?

@glenn-jocher can you help me in this if you have any idea about it?

**Comment by jaskiratsingh2000** [comment]
@rocketsfallonrocketfalls Okay, I am trying that. Let see what happens

**Comment by mitrasafari** [comment]
hey, I had the same issue and I solve it by comment lines 299 and 300 in val.py  

`# Plots
    if plots:
    #confusion_matrix.plot(save_dir=save_dir, names=list(names.values()))
    #callbacks.run('on_val_end', nt, tp, fp, p, r, f1, ap, ap50, ap_class, confusion_matrix)
     print('confusion_matrix')
`

**Comment by glenn-jocher** [comment]
@mitrasafari glad to hear you were able to resolve the issue! If you have any more questions or need further assistance, feel free to ask. Good luck with your YOLOv5 project!
