### ISSUE TITLE
Label corrupted. I can't solved.

### ISSUE THREAD

**Issue by SpongeBab** [ultralytics/yolov5#3656]
## ❔Question
Why is my label corrupted? I can make sure that my picture is in good condition, and I have generated the TXT label correctly.

I have successfully trained my own dataset before. But today when I was generating the label as usual and training another new data set, there were a lot of label that were corrupted. I checked the label carefully.

Can you give me some help?

I looked in the `datasets.py`, like` def verify_image_label(args)`. But I can't find the mistake.

And the ap is 0....
## Additional context
```
train: Scanning 'E:\qxdetection\train' images and labels...4300 found, 0 missing, 0 empty, 1408 corrupted: 100%|██████████| 4300/4300 [00:31<00:00, 137.61it/s]
train: New cache created: E:\qxdetection\train.cache
val: Scanning 'E:\qxdetection\valid' images and labels...343 found, 0 missing, 0 empty, 124 corrupted: 100%|██████████| 343/343 [00:10<00:00, 33.86it/s] 
val: New cache created: E:\qxdetection\valid.cache
Plotting labels... 

autoanchor: Analyzing anchors... anchors/target = 4.12, Best Possible Recall (BPR) = 0.9910
Image sizes 1280 train, 1280 test
Using 0 dataloader workers
Logging results to runs\train\exp7
Starting training for 200 epochs...

     Epoch   gpu_mem       box       obj       cls     total    labels  img_size
     0/199     6.19G   0.08685   0.03775   0.04768    0.1723         1      1280: 100%|██████████| 2892/2892 [40:56<00:00,  1.18it/s]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 110/110 [00:43<00:00,  2.50it/s]
                 all        219          0          0          0          0          0
```

**Comment by SpongeBab** [comment]
![image](https://user-images.githubusercontent.com/65898238/122363740-c48e5c80-cf8b-11eb-94dd-33b08cfafa3d.png)
oh, I think there is something wrong with the way I divide the data set. There is a class of pictures that are not found in the training set but only in the valid set, so AP cannot be calculated. 
But I still haven't found the cause of the label corrupted.
@glenn-jocher

**Comment by glenn-jocher** [comment]
@SpongeBab if you delete your *.cache files in your dataset it will recache and display the cause of all corrupted images and/or labels.

**Comment by SpongeBab** [comment]
@glenn-jocher 
I have deleted the train and valid cache.And it show this again:
```
train: Scanning 'E:\qxdetection\train' images and labels...4300 found, 0 missing, 0 empty, 1408 corrupted: 100%|██████████| 4300/4300 [00:31<00:00, 137.61it/s]
train: New cache created: E:\qxdetection\train.cache
val: Scanning 'E:\qxdetection\valid' images and labels...343 found, 0 missing, 0 empty, 124 corrupted: 100%|██████████| 343/343 [00:10<00:00, 33.86it/s] 
val: New cache created: E:\qxdetection\valid.cache
```
I wonder how it can judge if a image is corrupted? I looked at the code, but I couldn't find anything to judge by. Can you tell me? Or give me some guide.Thank you very much~

**Comment by glenn-jocher** [comment]
@SpongeBab image-label pairs are corrupted if any of the checks fail. The checks are here:

https://github.com/ultralytics/yolov5/blob/9b6dba6207182f5b1bca596a947fc32d4150db2f/utils/datasets.py#L1054-L1087

**Comment by SpongeBab** [comment]
yes,I got it.I will debug one step by step.

**Comment by SpongeBab** [comment]
@glenn-jocher 
this line:
`        logging.info(f'{prefix}WARNING: Ignoring corrupted image and/or label {im_file}: {e}')`
Why isn't anything printed? Since it has judged it corrupted. It's strange.
It's a bug?

this is my output:
```
train: Scanning 'E:\qxdetection\train' images and labels...4300 found, 0 missing, 0 empty, 1431 corrupted: 100%|██████████| 4300/4300 [00:20<00:00, 206.33it/s]
train: New cache created: E:\qxdetection\train.cache
val: Scanning 'E:\qxdetection\valid' images and labels...343 found, 0 missing, 0 empty, 101 corrupted: 100%|██████████| 343/343 [00:09<00:00, 36.42it/s]
val: New cache created: E:\qxdetection\valid.cache
Plotting labels... 

autoanchor: Analyzing anchors... anchors/target = 4.17, Best Possible Recall (BPR) = 0.9910
Image sizes 1280 train, 1280 test
Using 0 dataloader workers
Logging results to runs\train\exp8
Starting training for 200 epochs...

     Epoch   gpu_mem       box       obj       cls     total    labels  img_size
```

**Comment by SpongeBab** [comment]
@glenn-jocher 
I just simply print the corrupted image/label.I can save it to the txt file. Maybe this is a feature I could do. 
## Input:
```
        print(f'Ignoring corrupted image and/or label {im_file}')
        logging.info(f'{prefix}WARNING: Ignoring corrupted image and/or label {im_file}: {e}')
        return [None, None, None, None, nm, nf, ne, nc]
```
## Output:
```
Ignoring corrupted image and/or label E:\qxdetection\images\train\2020-01-11_21_36_02_642.jpg
检查图像...
图像数量 55
Ignoring corrupted image and/or label E:\qxdetection\images\train\2020-01-11_21_41_15_002.jpg
检查图像...
图像数量 55
Ignoring corrupted image and/or label E:\qxdetection\images\train\2020-01-11_21_41_23_122.jpg
检查图像...
图像数量 55
Ignoring corrupted image and/or label E:\qxdetection\images\train\2020-01-11_21_41_45_650.jpg
检查图像...
图像数量 55
Ignoring corrupted image and/or label E:\qxdetection\images\train\2020-01-11_21_42_08_851.jpg
检查图像...
图像数量 55
Ignoring corrupted image and/or label E:\qxdetection\images\train\2020-01-11_21_42_17_792.jpg
```
And I check my image, it is ok.
2020-01-11_21_36_02_642.jpg
![image](https://user-images.githubusercontent.com/65898238/122492498-6cea0280-d018-11eb-825d-8f59cb26a278.png)

This is the relative label txt.
![image](https://user-images.githubusercontent.com/65898238/122492640-b63a5200-d018-11eb-97ec-a8f8f3757686.png)

All is ok.
Why it is corrupted??.It is strange.

**Comment by SpongeBab** [comment]
oh, I got it.Maybe is it because my coordinates are normalized over 1? I see that the first coordinate, `xmin`, is over 1.
@glenn-jocher

**Comment by SpongeBab** [comment]
@glenn-jocher 
yes.I solve it.
```
train: Scanning 'E:\qxdetection\train' images and labels...4300 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4300/4300 [00:20<00:00, 208.30it/s]
train: New cache created: E:\qxdetection\train.cache
val: Scanning 'E:\qxdetection\valid' images and labels...343 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 343/343 [00:09<00:00, 35.90it/s] 
val: New cache created: E:\qxdetection\valid.cache
```
Maybe this line :
         `assert (l[:, 1:] <= 1).all(), 'non-normalized or out of bounds coordinate labels'`

**Comment by SpongeBab** [comment]
I'm trying to save the corrupted image or label to a log.txt.

**Comment by glenn-jocher** [comment]
@SpongeBab good news 😃! Your original issue may now be fixed ✅ in PR #3676. This PR implements a new cache version 0.3 which provides better corrupt image/label reporting to screen. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by ibtehajali67** [comment]
> @glenn-jocher yes.I solve it.
> 
> ```
> train: Scanning 'E:\qxdetection\train' images and labels...4300 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4300/4300 [00:20<00:00, 208.30it/s]
> train: New cache created: E:\qxdetection\train.cache
> val: Scanning 'E:\qxdetection\valid' images and labels...343 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 343/343 [00:09<00:00, 35.90it/s] 
> val: New cache created: E:\qxdetection\valid.cache
> ```
> 
> Maybe this line : `assert (l[:, 1:] <= 1).all(), 'non-normalized or out of bounds coordinate labels'`

hi, how you solved this problem

**Comment by glenn-jocher** [comment]
@ibtehajali67 great to hear that the issue has been resolved! It seems that the problem was due to non-normalized or out-of-bounds coordinate labels. By ensuring that the coordinates are within the normalized range of [0, 1], you were able to fix the corrupted label issue. Well done! If you have any more questions or run into any further challenges, feel free to ask. Happy coding!

**Comment by kanis777** [comment]
hi @glenn-jocher .So I am obtaining an error that less than 10 pixels of either width or height means the image will be ignored when i train with yolov8-cls . is there anything i can do so that it accepts images with less than 10 pixels aswell?

**Comment by glenn-jocher** [comment]
Hello, YOLO models typically require images larger than 10 pixels for effective training. It's best to resize your images to meet this requirement. If you have further questions, feel free to ask!

**Comment by PhilipNaveen** [comment]
@glenn-jocher 

I'm getting this same error over and over no matter what I try. 

This is a sample label:

0 0.745512 0.599978 0.010264 0.061666

and it's corresponding image:

![Image](https://github.com/user-attachments/assets/5c1521ad-2475-4e83-b73f-86c2e47c087d)



I get error reporting like this:


[34m[1mtrain: [0mScanning '/u/dxj2ut/datasets/roboflow/train/labelTxt.cache' images and labels... 1987 found, 0 missing, 0 empty, 1987 corrupted: 100%|██████████| 1987/1987 [00:00<?, ?it/s]
[34m[1mtrain: [0mScanning '/u/dxj2ut/datasets/roboflow/train/labelTxt.cache' images and labels... 1987 found, 0 missing, 0 empty, 1987 corrupted: 100%|██████████| 1987/1987 [00:00<?, ?it/s]
[34m[1mtrain: [0mWARNING: /u/dxj2ut/datasets/roboflow/train/images/000001.jpg: ignoring corrupt image/label: list index out of range
[34m[1mtrain: [0mWARNING: /u/dxj2ut/datasets/roboflow/train/images/000002.jpg: ignoring corrupt image/label: list index out of range
[34m[1mtrain: [0mWARNING: /u/dxj2ut/datasets/roboflow/train/images/000003.jpg: ignoring corrupt image/label: list index out of range
[34m[1mtrain: [0mWARNING: /u/dxj2ut/datasets/roboflow/train/images/000004.jpg: ignoring corrupt image/label: list index out of range
.
.
.

Traceback (most recent call last):
  File "train.py", line 633, in <module>
    main(opt)
  File "train.py", line 530, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 213, in train
    train_loader, dataset = create_dataloader(train_path, imgsz, batch_size // WORLD_SIZE, gs, names, single_cls,
  File "/u/dxj2ut/yolov5_obb/utils/datasets.py", line 101, in create_dataloader
    dataset = LoadImagesAndLabels(path, names, imgsz, batch_size,
  File "/u/dxj2ut/yolov5_obb/utils/datasets.py", line 444, in __init__
    labels, shapes, self.segments = zip(*cache.values())
ValueError: not enough values to unpack (expected 3, got 0)
