### ISSUE TITLE
Names of arguments in training

### ISSUE THREAD

**Issue by tetelevm** [ultralytics/yolov5#3660]
## ❔Question

Hello! In [your wiki](/ultralytics/yolov5/wiki/Train-Custom-Data) you give example:
```
python train.py --img 640 --batch 16 --epochs 5 --data coco128.yaml --weights yolov5s.pt
```
The file `train.py` contains the lines:
```
parser.add_argument('--batch-size', type=int, default=16, help='total batch size for all GPUs')
parser.add_argument('--img-size', nargs='+', type=int, default=[504, 378], help='[train, test] image sizes')
```
Can it be a mistake to name the arguments differently?

**Comment by glenn-jocher** [comment]
@tetelevm this is correct. The python argparser package can accept shorter arguments if they don't create ambiguities.
