### ISSUE TITLE
Multi-GPU,  subprocess.CalledProcessError

### ISSUE THREAD

**Issue by DeanZag** [ultralytics/yolov5#3663]
I am trying to perform a DL training using YOLO V5 on a HPC with two GPUs. I have followed all steps by Yolo V5 Multi-GPU DistributedDataParallel Mode. The command I have used to run the training is as follow:

`(base) amrcnw@amrcnw-G482-Z54-00:~/Olive_project/Yolo_V5/yolov5$ python -m torch.distributed.launch --master_port 9963 --nproc_per_node 2 train.py --data ./data.yaml --cfg yolov5s.yaml --weights yolov5s.pt --epochs 3 --batch-size 64 --device 0,1
#*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
/home/amrcnw/anaconda3/lib/python3.8/site-packages/torch/cuda/__init__.py:125: UserWarning:
A100-PCIE-40GB with CUDA capability sm_80 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the A100-PCIE-40GB GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
/home/amrcnw/anaconda3/lib/python3.8/site-packages/torch/cuda/__init__.py:125: UserWarning:
A100-PCIE-40GB with CUDA capability sm_80 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the A100-PCIE-40GB GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Your branch is behind 'origin/master' by 457 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

Using torch 1.6.0 CUDA:0 (A100-PCIE-40GB, 40536MB)
                  CUDA:1 (A100-PCIE-40GB, 40536MB)

Traceback (most recent call last):
  File "train.py", line 483, in <module>
    dist.init_process_group(backend='nccl', init_method='env://')  # distributed backend
  File "/home/amrcnw/anaconda3/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 422, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/amrcnw/anaconda3/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 172, in _env_rendezvous_handler
    store = TCPStore(master_addr, master_port, world_size, start_daemon, timeout)
RuntimeError: Address already in use
Traceback (most recent call last):
  File "/home/amrcnw/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/amrcnw/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/amrcnw/anaconda3/lib/python3.8/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/amrcnw/anaconda3/lib/python3.8/site-packages/torch/distributed/launch.py", line 256, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/home/amrcnw/anaconda3/bin/python', '-u', 'train.py', '--local_rank=1', '--data', './data.yaml', '--cfg', 'yolov5s.yaml', '--weights', 'yolov5s.pt', '--epochs', '3', '--batch-size', '64', '--device', '0,1']' returned non-zero exit status 1.`

Also I have used the following command which gave me the same error 

`python -m torch.distributed.launch --nproc_per_node 2 train.py --img 416 --batch 16 --epochs 300 --data ./data.yaml --cfg ./models/yolov5s.yaml --weights '' --name Test_3_10Fit yolov5s.pt
`

there is an error with subprocess.CalledProcessError: Command. Can someone explain to me what is wrong?

**Comment by glenn-jocher** [comment]
@DeanZag your error is probably related to the warnings displayed on your console about mismatch in your pytorch installation.

For best results I would recommend training in the Docker image:

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by DeanZag** [comment]
Hi @glenn-jocher 

I had my images arranged by Roboflow and it was working fine on a previous GPU (GTX 1080). Currently, I am running the same images for training on HPC contain x2 NVIDIA RTX A6000 with 2TP memory. Surprisingly I have run earlier evolve training for few days on the HPC which worked fine. I am trying to run a single training where I started to notice the multi GPUs (NCCL) issue. Anyhow, I have noticed an issue with the leave [and I have followed your solution on the provided link](https://github.com/ultralytics/yolov5/issues/1552) 

I have below error where it says `train.py: error: unrecognized arguments: yolov5s.pt`. I have checked the directory for yolo5s.pt, It is in the directory   

`(base) amrcnw@amrcnw-G482-Z54-00:~/Olive_project/Yolo_V5/yolov5$ ls
data       detect.py   evolve.png  hubconf.py        LICENSE  __pycache__  requirements.txt  runs  test_infer  torch_utils.py  train.py        utils  wandb               yolov5s.pt
data.yaml  Dockerfile  evolve.txt  hyp_evolved.yaml  models   README.md    run.py            test  test.py     train           tutorial.ipynb  valid  Yolo_V_5Script.txt
(base) amrcnw@amrcnw-G482-Z54-00:~/Olive_project/Yolo_V5/yolov5$`

Please see the error below

`
(base) amrcnw@amrcnw-G482-Z54-00:~/Olive_project/Yolo_V5/yolov5$ python -m torch.distributed.launch --nproc_per_node 2 train.py --img 416 --batch 16 --epochs 300 --data ./data.yaml --cfg ./models/yolov5s.yaml --weights '' --name Test_3_10Fit yolov5s.pt
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
usage: train.py [-h] [--weights WEIGHTS] [--cfg CFG] [--data DATA] [--hyp HYP] [--epochs EPOCHS] [--batch-size BATCH_SIZE] [--img-size IMG_SIZE [IMG_SIZE ...]] [--rect] [--resume [RESUME]] [--nosave] [--notest]
                [--noautoanchor] [--evolve] [--bucket BUCKET] [--cache-images] [--image-weights] [--device DEVICE] [--multi-scale] [--single-cls] [--adam] [--sync-bn] [--local_rank LOCAL_RANK] [--log-imgs LOG_IMGS]
                [--workers WORKERS] [--project PROJECT] [--name NAME] [--exist-ok]
train.py: error: unrecognized arguments: yolov5s.pt
usage: train.py [-h] [--weights WEIGHTS] [--cfg CFG] [--data DATA] [--hyp HYP] [--epochs EPOCHS] [--batch-size BATCH_SIZE] [--img-size IMG_SIZE [IMG_SIZE ...]] [--rect] [--resume [RESUME]] [--nosave] [--notest]
                [--noautoanchor] [--evolve] [--bucket BUCKET] [--cache-images] [--image-weights] [--device DEVICE] [--multi-scale] [--single-cls] [--adam] [--sync-bn] [--local_rank LOCAL_RANK] [--log-imgs LOG_IMGS]
                [--workers WORKERS] [--project PROJECT] [--name NAME] [--exist-ok]
train.py: error: unrecognized arguments: yolov5s.pt
Traceback (most recent call last):
  File "/home/amrcnw/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/amrcnw/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/amrcnw/anaconda3/lib/python3.8/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/amrcnw/anaconda3/lib/python3.8/site-packages/torch/distributed/launch.py", line 255, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/home/amrcnw/anaconda3/bin/python', '-u', 'train.py', '--local_rank=1', '--img', '416', '--batch', '16', '--epochs', '300', '--data', './data.yaml', '--cfg', './models/yolov5s.yaml', '--weights', '', '--name', 'Test_3_10Fit', 'yolov5s.pt']' returned non-zero exit status 2.
(base) amrcnw@amrcnw-G482-Z54-00:~/Olive_project/Yolo_V5/yolov5$ ls
data       detect.py   evolve.png  hubconf.py        LICENSE  __pycache__  requirements.txt  runs  test_infer  torch_utils.py  train.py        utils  wandb               yolov5s.pt
data.yaml  Dockerfile  evolve.txt  hyp_evolved.yaml  models   README.md    run.py            test  test.py     train           tutorial.ipynb  valid  Yolo_V_5Script.txt
(base) amrcnw@amrcnw-G482-Z54-00:~/Olive_project/Yolo_V5/yolov5$

`

**Comment by DeanZag** [comment]
Hi @glenn-jocher

I had my images arranged by Roboflow and it was working fine on a previous GPU (GTX 1080). Currently, I am running the same images for training on HPC contain x2 NVIDIA RTX A6000 with 2TP memory. 

I recloned yolov5 using the following commands

 `git clone https://github.com/ultralytics/yolov5 # clone repo
cd yolov5
pip install -r requirements.txt`


Here's the output I got 
![image](https://user-images.githubusercontent.com/64921068/122607113-f679ee80-d071-11eb-8a43-1702a99b778f.png)

Nothing is happening aftere "Model Summary: 283 layers, 7063542 parameters, 7063542 gradients, 16.4 GFLOPs" (I did press Ctrl+Z to stop the process .

![image](https://user-images.githubusercontent.com/64921068/122607410-69836500-d072-11eb-85c9-8e0bbefb67e9.png)

Not sure what is it wrong as it used to work fine few weeks when I run --evolve?!!

Additional questions:

    When run the multiple GPUs command `python -m torch.distributed.launch --master_port 1234 --nproc_per_node 2 train.py --batch-size 64 --data ./data.yaml --weights yolov5s.pt` it display below output. 

![image](https://user-images.githubusercontent.com/64921068/122607674-d991eb00-d072-11eb-9b19-a5d26372ae72.png)

Thanks

**Comment by glenn-jocher** [comment]
@DeanZag your PyTorch install is incompatible with your hardware. This has nothing to do with YOLOv5. Visit https://pytorch.org/get-started/locally/

**Comment by DeanZag** [comment]
Thanks @glenn-jocher 
Just fixed the PyTorch using the following command
 `conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c nvidia`

I had to restart the HPC in order to resolve the NCCL issue and it is working.

surprisingly I have used the original commands to run training 
`python train.py --img 416 --batch 64 --epochs 300 --data ./data.yaml --cfg models/yolov5s.yaml --weights '' --name yolov5s_HPC_Train_results  --cache
`

It is working fine 
![image](https://user-images.githubusercontent.com/64921068/122645788-064a0f00-d114-11eb-869e-ce04822db624.png)

Not sure if both GPUs are on or just one?!! since didn't use the Mlti GPUs command 
`python -m torch.distributed.launch --master_port 1234 --nproc_per_node 2 train.py --batch-size 64 --data ./data.yaml --weights yolov5s.pt
`

Any ideas?

**Comment by glenn-jocher** [comment]
@DeanZag current code requires opt-in to any devices you want to use other than device 0:
```
python -m torch.distributed.run --nproc_per_node 2 train.py --data coco128.yaml --device 0,1
```
