### ISSUE TITLE
How much disk space does coco needs?

### ISSUE THREAD

**Issue by jaskiratsingh2000** [ultralytics/yolov5#3666]

**Comment by glenn-jocher** [comment]
@jaskiratsingh2000 see dataset yaml files for this info.

**Comment by jaskiratsingh2000** [comment]
@glenn-jocher Please check. The dataset yaml file doesn't have anything related to space mentioned.https://github.com/ultralytics/yolov5/blob/master/data/coco.yaml

I checked previously before opening an issue and as I didn't find that so that's why reached out to you.

**Comment by wudashuo** [comment]
https://cocodataset.org/#download

**Comment by jaskiratsingh2000** [comment]
Thank you

**Comment by jaskiratsingh2000** [comment]
@wudashuo The downloading keeps going with the increasing numbers so is it a never-ending process? till what numbers does it go?

**Comment by wudashuo** [comment]
![20210621094930](https://user-images.githubusercontent.com/5948604/122696592-07934d00-d276-11eb-8d4e-1220da38c280.png)
