### ISSUE TITLE
The `names` entry in the .yaml how should entries be ordered?

### ISSUE THREAD

**Issue by shashi-netra** [ultralytics/yolov5#367]
## ❔Question
if ihave data.yaml like this: 

```
train: ./data/train/images
val: ./data/val/images

nc: 8
names: ['Adidas','Walmart','Wells-Fargo','FedEx','Nike','Bank of America','Coca Cola','Zara']
```

what is the right way of ordering the `names`? I assume alphabetic, for some reason when displaying it swaps with something else.

p.s. we LOVE this project, couldn't upvote it enough!

**Comment by glenn-jocher** [comment]
@shashi-netra thanks! Names should be ordered by class, so Zara should not be last unless it is class 7 in your case. 

In coco.yaml for example you can see class 0 is person, class 1 is bicycle etc.
