### ISSUE TITLE
Can you publish a simplified version of the yolov5 code？

### ISSUE THREAD

**Issue by TIanCat** [ultralytics/yolov5#3671]
I think that a good code should be efficient enough and simple enough，but apparently  yolov5 is not.  It contains too many optimizations and selections unrelated to the trunk，and most people don‘t need that.  A simple code can satisfy most people's needs. Unfortunately most need a week to understand your code first.

**Comment by SpongeBab** [comment]
No.I think v5 is perfect.You just need use the feature that you want.If there is anyone hasn't learned Deep Learning, CNN.Maybe this code is difficult.
Maybe you can see  https://github.com/ultralytics/yolov3.

**Comment by TIanCat** [comment]
OK, I'm going to spend a few more days trying to understand your code. By the way, when will your paper be published?


> No.I think v5 is perfect.You just need use the feature that you want.If there is anyone hasn't learned Deep Learning, CNN.Maybe this code is difficult.
> Maybe you can see https://github.com/ultralytics/yolov3.

**Comment by glenn-jocher** [comment]
@TIanCat @SpongeBab thanks for the feedback! There is a good argument to be made for minimalistic implementations such as https://github.com/karpathy/minGPT.

These don't provide any extras, simply the minimum functionality, which makes them more readable and easier to understand.
