### ISSUE TITLE
how to set fullscreen when i run detect.py ?

### ISSUE THREAD

**Issue by fandisyamsudin** [ultralytics/yolov5#3675]
## ❔Question

how to set fullscreen when i run detect.py ?

**Comment by glenn-jocher** [comment]
@fandisyamsudin I don't understand your question. detect.py runs inference on sources, it does not have a 'screen size'.

**Comment by fkamm** [comment]
@fandisyamsudin in the detect.py file add this:

`            if view_img:
                cv2.namedWindow("window", cv2.WND_PROP_FULLSCREEN)
                cv2.setWindowProperty("window", cv2.WND_PROP_FULLSCREEN, cv2.WINDOW_FULLSCREEN)
                cv2.imshow("window", im0)
                cv2.waitKey(1)  # 1 millisecond
`

Here I found the solution [https://stackoverflow.com/questions/17696061/how-to-display-a-full-screen-images-with-python2-7-and-opencv2-4](link)
