### ISSUE TITLE
Backbone feature propagation to bounding box

### ISSUE THREAD

**Issue by Evm7** [ultralytics/yolov5#3688]
## ❔Question
Hi there,

First of all I would really like to congrat to the authors of the project! Great job!

I am currently developing a project where I need to combine Yolo object detections into a tracker that uses features from object bounding boxes as appearence information. To reduce inference time in tracking, I am wondering if there is any possibility to obtain the features of the last backbone layer from a given bounding box object. In this way, I would then not need to process again each cropped image (one for each object detected) into the backbone (avoiding another pass into the network and reducing time).

As a summary, I would like to obtain the features from the backbone that propagate to a determined object.

Is there any option to do so ?

Thank you in advance

**Comment by glenn-jocher** [comment]
@Evm7 well, there is not just one place where the backbone meets the head, there are 3 or 4 places (skip connections) that connect the two. You can see this visualizing the model with Netron or TensorBoard, or by looking at the model yaml files.
![image](https://user-images.githubusercontent.com/26833433/122637839-0dabf100-d0f1-11eb-9c43-e651ff8e6405.png)


I think for tracking what you would really want would be the features at the Detect() layer responsible for a given detection no?

**Comment by Evm7** [comment]
> @Evm7 well, there is not just one place where the backbone meets the head, there are 3 or 4 places (skip connections) that connect the two. You can see this visualizing the model with Netron or TensorBoard, or by looking at the model yaml files.
> ![image](https://user-images.githubusercontent.com/26833433/122637839-0dabf100-d0f1-11eb-9c43-e651ff8e6405.png)
> 
> I think for tracking what you would really want would be the features at the Detect() layer responsible for a given detection no?

**Comment by Evm7** [comment]
@glenn-jocher Thank you for the response. I thought about obtaining the features from the Detect() layer, but how can I obtain them if autoshape is enabled to the model? 

From a batch of 4 images, the Yolov5s model extracts a tuple with first position a tensor of shape torch.Size([4, 25200, 85]).
Is there any relation between these tensor and the features? Or it has to be obtained in another way?

Thank you in advance

**Comment by glenn-jocher** [comment]
@Evm7 feature extractions implementation is up to you naturally, though you should be able to update the autoshape wrapper easily to accomodate any model change.

The features are prior to the outputs you mention.
