### ISSUE TITLE
Tflite convertion

### ISSUE THREAD

**Issue by e-shawakri** [ultralytics/yolov5#369]
Any one found a way to convert the yolov5l into tflite?

**Comment by glenn-jocher** [comment]
The default pipeline is through ONNX. 
https://github.com/onnx/onnx-tensorflow

**Comment by e-shawakri** [comment]
it's not working through ONNX, when the model converting from ONNX into pb it removes the input and the output arrays which are named "images" and "output" and therefore the model can't be converted into tflite, because the input and output arrays are vanished when converting the model from ONNX into .pb.

**Comment by glenn-jocher** [comment]
@e-shawakri sounds like an issue for the onnx-tensorflow repo rather than this repo.

**Comment by e-shawakri** [comment]
@glenn-jocher Thanks for your replay, but i'm not asking about the problem.
I'm asking if anybody do the pipeline process and succeed to convert the model into tflite model.
