### ISSUE TITLE
Inconsistent performance of pre-training weight val

### ISSUE THREAD

**Issue by hhaAndroid** [ultralytics/yolov5#3692]
## ❔Question
Why the performance of pre-training weight val is inconsistent

## Additional context
python test.py --data coco.yaml --img 640 --conf 0.001 --iou 0.65

```python
Namespace(
augment=False, batch_size=32, conf_thres=0.001,
data='./data/coco.yaml', device='', exist_ok=False,
half=False, imgsz=640, iou_thres=0.65, name='exp',
project='runs/test', save_conf=False, save_hybrid=False,
save_json=True, save_txt=False, single_cls=False, task='val',
verbose=False, weights='yolov5s.pt'
)

Downloading https://github.com/ultralytics/yolov5/releases/download/v5.0/yolov5s.pt 

Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|████████████████████████████████| 157/157 [01:15<00:00,  2.08it/s]
                all       5000      36335      0.669      0.494      0.546      0.351

```

I did not modify any code, why is it inconsistent with the [table](https://github.com/ultralytics/yolov5#pretrained-checkpoints) performance？

**Comment by glenn-jocher** [comment]
@hhaAndroid table results are based on pycocotools mAP. To reproduce simply `pip install pycocotools` and rerun your command, or use the Colab notebook which comes with pycocotools preinstalled:
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

<img width="1169" alt="Screenshot 2021-06-19 at 12 02 53" src="https://user-images.githubusercontent.com/26833433/122638783-6d58cb00-d0f6-11eb-9e4c-594a4fd33055.png">

**Comment by hhaAndroid** [comment]
@glenn-jocher thank you very much.
