### ISSUE TITLE
`Warning: Leaking Caffe2 thread-pool after fork` with DataLoader `num_workers>0` and `pin_memory=True`

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/yolov5#3695]
The 'Leaking Caffe2 thread-pool' warning is now appearing in the YOLOv5 (https://github.com/ultralytics/yolov5) Docker Image with PyTorch 1.9. To reproduce:
```bash
t=ultralytics/yolov5:latest && sudo docker pull $t && sudo docker run -it --ipc=host --gpus all $t
python train.py --epochs 3
```
<img width="1005" alt="Screenshot 2021-06-19 at 14 44 58" src="https://user-images.githubusercontent.com/26833433/122642919-27f3c800-d10d-11eb-9ccf-a3605b22e616.png">

This is unrelated to YOLOv5 and the responsibility of the PyTorch devs. I've raised an issue directly there in https://github.com/pytorch/pytorch/issues/57273

@NanoCode012

**Comment by LundinMachine** [comment]
Hmmm, in the meantime -- pardon possibly dumb question -- what about training without threading?
