### ISSUE TITLE
How can I use DETRAC Dataset with the python3 test.py command?

### ISSUE THREAD

**Issue by jaskiratsingh2000** [ultralytics/yolov5#3696]
hi, @glenn-jocher I want to use the [DETRAC dataset ](https://detrac-db.rit.albany.edu/download)with my `python3 test.py --data DATA.yaml weights yolov5s.pt`

Can you please let me know how to create the YAML file for that I could use this directly? Please let me know @glenn-jocher

**Comment by jaskiratsingh2000** [comment]
@glenn-jocher Are you around and can answer how can this be possible?

**Comment by jaskiratsingh2000** [comment]
@glenn-jocher I am still looking forward to your reply on this. Please please let me know. It would really be appreciable. Thanks!

**Comment by jaskiratsingh2000** [comment]
@glenn-jocher I just want to know that how can I use the DETRAC Dataset with the Yolov5? Is there any YAML file already made for it?

**Comment by glenn-jocher** [comment]
@jaskiratsingh2000 please consider create a detrac.yaml to assist future users in autodownloading the dataset. You can follow the existing dataset yamls for guidance in the data/ directory.
