### ISSUE TITLE
How to train on  128*4500 pictures

### ISSUE THREAD

**Issue by woshichunge12** [ultralytics/yolov5#3701]
## ❔Question
I don’t want it to fill 128 to 4500, it consumes resources too much

**Comment by TehKonnos** [comment]
Try resizing them. Don't forget to keep the aspect-ratio though.

**Comment by woshichunge12** [comment]
@TehKonnos 
Thank you very much for your reply. The picture is the result of the original image after being stretched. Do you mean that I process the picture or modify the code? I found that the aspect-ratio of the image in the code has been processed.
It seems that I don’t need to deal with pictures. As long as --rect is used during training, non-square pictures will be processed.
like this:
python train.py --img 2560 --batch 1 --epochs 5 --data coco128.yaml --weights yolov5s.pt --nosave --rect
![image](https://user-images.githubusercontent.com/40681348/122670249-98751480-d1f3-11eb-856e-731ac915307d.png)

**Comment by TehKonnos** [comment]
I recommend to resize the picture as a square and add paddings where neened. Then use the --img xx to train. I don't think --rect is for that case.

**Comment by glenn-jocher** [comment]
@woshichunge12 yes --rect will use rectangular training rather than square mosaic training.
