### ISSUE TITLE
Why boxes are totally wrong in Android? (torchscript)

### ISSUE THREAD

**Issue by turgut090** [ultralytics/yolov5#3702]
Hi. I trained my custom data with yolo5 from this repo. The results are pretty good. However, after running detection (with torchscipt) from Android Studio I get strange box annotations. Original weights with 80 class (yolo5s) work fine. https://github.com/pytorch/android-demo-app/tree/master/ObjectDetection

![Screenshot from 2021-06-19 19-23-11](https://user-images.githubusercontent.com/38523699/122664235-40b5b980-d1b1-11eb-972f-b6b59064784a.png)

In fact ```best.pt``` does a good job on my custom video. However, afterward https://github.com/ultralytics/yolov5/issues/251 I get the above-mentioned result in the Android emulator.

**Comment by obaby** [comment]
I faced the same problem, have you soloved this? thanks.

**Comment by turgut090** [comment]
@obaby Hi. Unfortunately, I haven't.
