### ISSUE TITLE
KeyError: 'version' when testing yolov5

### ISSUE THREAD

**Issue by MagicPF** [ultralytics/yolov5#3707]
Dataset autodownload success

Traceback (most recent call last):
  File "test.py", line 355, in <module>
    main(opt)
  File "test.py", line 330, in main
    test(**vars(opt))
  File "/home/comp/e9205945/.local/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "test.py", line 95, in test
    prefix=colorstr(f'{task}: '))[0]
  File "/home/comp/e9205945/yolov5/utils/datasets.py", line 79, in create_dataloader
    prefix=prefix)
  File "/home/comp/e9205945/yolov5/utils/datasets.py", line 393, in __init__
    if cache['version'] != 0.3 or cache['hash'] != get_hash(self.label_files + self.img_files):
KeyError: 'version'

**Comment by glenn-jocher** [comment]
@MagicPF your cache is far out of date since we've been using version keys for almost a year now. Please delete any *.cache files in your dataset and re-run your command.

**Comment by glenn-jocher** [comment]
@MagicPF good news 😃! Your original issue may now be fixed ✅ in PR #3730. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
