### ISSUE TITLE
Confidence threshold in training

### ISSUE THREAD

**Issue by jjerrying** [ultralytics/yolov5#3708]
Hi, I'm jerry.
Thank you for your good project.
I have a question about confidence threshold.

## ❔Question
https://github.com/ultralytics/yolov5/blob/e8810a53e83ddb5dd6bf8e871c2ede701007047c/train.py#L442-L455

In this code, confidence threshold is 0.001.
I think this is a very small value compared with another papers.
Could you explain why use small value?

**Comment by snow-tyan** [comment]
@jjerrying It's a constant for calculating mAP

**Comment by jjerrying** [comment]
> It's a constant for calculating mAP

Thank you for your reply. 

What I want to know is why use small value(0.001) of confidence score.

Additionally, that value is for NMS operation not mAP
