### ISSUE TITLE
training custom data image size

### ISSUE THREAD

**Issue by HonestyBrave** [ultralytics/yolov5#3709]
Hi, ultralytics:
I want to train my custom data, but the image size is width = 640, height = 1280, where i should modify?
Thank you!

**Comment by HonestyBrave** [comment]
@github-actions， thank you for your reply, i have seen this tutorial, but I didn't want my picture to resize width == height, i want to specify width and height to training, thank you!

**Comment by glenn-jocher** [comment]
@HonestyBrave you can train with --img 1280 and/or --rect, though --rect is not recommended for best results.

**Comment by HonestyBrave** [comment]
@glenn-jocher Thank you for your reply, I try.
