### ISSUE TITLE
Can not use torch.load()?

### ISSUE THREAD

**Issue by SpongeBab** [ultralytics/yolov5#3712]
## Can not torch.load()
How to load the pt file saved locally.
I create my own project. I used torch.load (). But the following error occurred.
`Yolov5 training torch\serialization.py No module named 'models'`

This is the relevant solution I found. 
https://github.com/pytorch/pytorch/issues/2762
 Can you save the model without saving the class name? Otherwise we can't use the weight in other files. I don't know how to simply load V5 weights in a different folder.

**Comment by huyhoangle86** [comment]
try this .
```
import sys
sys.path.insert(0, "/path/to/your/project")
```

**Comment by SpongeBab** [comment]
> try this .
> 
> ```
> import sys
> sys.path.insert(0, "/path/to/your/project")
> ```


I also checked this method, but this method requires that the models folder of Yolov5 be copied completely. Is there another way.

**Comment by SpongeBab** [comment]
@glenn-jocher need your help~

**Comment by glenn-jocher** [comment]
@SpongeBab @huyhoangle86 see YOLOv5 **PyTorch Hub** tutorial for loading custom models:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by SpongeBab** [comment]
@glenn-jocher I found the reason.There.
```
            if (not nosave) or (final_epoch and not evolve):  # if save
                ckpt = {'epoch': epoch,
                        'best_fitness': best_fitness,
                        'training_results': results_file.read_text(),
                        'model': deepcopy(de_parallel(model)).half(),
                        'ema': deepcopy(ema.ema).half(),
                        'updates': ema.updates,
                        'optimizer': optimizer.state_dict(),
                        'wandb_id': wandb_logger.wandb_run.id if loggers['wandb'] else None}

                # Save last, best and delete
                torch.save(ckpt, last)
                if best_fitness == fi:
                    torch.save(ckpt, best)
```
This saves the relative path of the model as well, although I don't know exactly which parameter makes this happen.Maybe it is because deepcopy?
My directory must be this:
![image](https://user-images.githubusercontent.com/65898238/123241748-ff583d80-d513-11eb-8b8a-4b7029f9e0df.png)
Or it will occurs such as:
```
Traceback (most recent call last):
  File "E:\DEMO\demo.py", line 21, in <module>
    ckpt = torch.load(weights, map_location='gpu')  # load checkpoint
  File "D:\Miniconda\envs\yolov5\lib\site-packages\torch\serialization.py", line 592, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "D:\Miniconda\envs\yolov5\lib\site-packages\torch\serialization.py", line 851, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'models.common'
```
In my custom code,I just simply use the `torch.save(ckpt)`.Thank.I learned some new.😀

**Comment by glenn-jocher** [comment]
@SpongeBab we deepcopy() the model first before casting to FP16 so as to not affect the model.

**Comment by SpongeBab** [comment]
Okay, thank you, although I don't quite understand. I'll continue to look into it.

**Comment by glenn-jocher** [comment]
@SpongeBab if you want to load a custom YOLOv5 model use PyTorch Hub. See YOLOv5 **PyTorch Hub** tutorial for loading custom models:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by SpongeBab** [comment]
Okay, thank you. I'll continue to look into it.

**Comment by SpongeBab** [comment]
@glenn-jocher oh,yeah, Why I never thought of that.Just get used to `torch.load()`
Just use this for load v5https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading:

```
model = torch.hub.load('ultralytics/yolov5', 'custom', path='path/to/best.pt')  # default
model = torch.hub.load('path/to/yolov5', 'custom', path='path/to/best.pt', source='local')  # local repo
```
Thanks again for your patience!I don't need change the code anymore.
