### ISSUE TITLE
How do i use plot_one_box_PIL function?

### ISSUE THREAD

**Issue by eyobbokru** [ultralytics/yolov5#3714]
## Additional context
my lable is in amharic and my output is no encoded properly. 

if any one can help 
thank you in advance

**Comment by glenn-jocher** [comment]
@eyob70 this function along with it's cv2 equivalent plot_one_box() are used by detect.py and the YOLOv5 autoshape() wrapper for Hub models. They are not intended for custom use.

**Comment by eyobbokru** [comment]
@glenn-jocher  thank you for your response but my question is theire is equivalent function inside utils that use PIL to detect as well how do i use it?

**Comment by eyobbokru** [comment]
@glenn-jocher  how do i use it inside detect.py?

**Comment by glenn-jocher** [comment]
@eyob70 you should be able to replace the plot_one_box() with the PIL equivalent:
https://github.com/ultralytics/yolov5/blob/b83e1a4adcf77ccafa72b22ade6cb3898ccb0e05/detect.py#L144

```python
                        from utils.plots import plot_one_box_PIL
                        plot_one_box_PIL(xyxy, im0, label=label, color=colors(c, True), line_thickness=line_thickness)
```

In my current experiment the boxes are failing to plot though. I don't have time to debug but if you find a fix please submit a PR (see https://github.com/ultralytics/yolov5#contribute), thank you!

**Comment by Sterbenair** [comment]
@eyob70 @glenn-jocher 

 im0 = plot_one_box_PIL(xyxy, im0, label=label, color=colors(c, True), line_thickness=line_thickness)

**Comment by eyobbokru** [comment]
@Sterbenair  thank you it worked
