### ISSUE TITLE
Multiple Videos 

### ISSUE THREAD

**Issue by tanejaaryan** [ultralytics/yolov5#3716]
## ❔Question
Is there a way to make modifications so that I can input multiple videos simultaneously and avoid the initial loading each time. My work requires saving as much computation & time as possible.
Currently, I am calling a thread pool in python for each video, but it loads for each thread. Is there a way to directly make some changes in detect.py for this purpose?

**Comment by glenn-jocher** [comment]
@tanejaaryan you can run inference on a directory:
```bash
python detect.py --source path/to/dir
```
