### ISSUE TITLE
One object per frame

### ISSUE THREAD

**Issue by tanejaaryan** [ultralytics/yolov5#3718]
## ❔Question
Can I somehow optimise the algorithm? For each frame processed in the video, I just need to check if even one object is in the frame. If yes, I require to write that frame as it is, else I just want to black it out. I am able to check if there are >0 objects, but there is no optimisation since it detects all objects. Can I somehow just continue to the next frame as soon as only 1 object is detected in the frame? (I need to make it as fast as possible with as less computation as needed)

**Comment by tanejaaryan** [comment]
> ## ❔Question
> Can I somehow optimise the algorithm? For each frame processed in the video, I just need to check if even one object is in the frame. If yes, I require to write that frame as it is, else I just want to black it out. I am able to check if there are >0 objects, but there is no optimisation since it detects all objects. Can I somehow just continue to the next frame as soon as only 1 object is detected in the frame? (I need to make it as fast as possible with as less computation as needed)
> 
> ## Additional context

I think I found a solution. the max_det argument . Just want to confirm it skips to the next frame as soon as it finds an object right in the frame?

**Comment by glenn-jocher** [comment]
@tanejaaryan the entire purpose of a CNN is that all detections occur simultaneously. What you're talking about does not exist within the context of YOLO or any other single shot detector.

**Comment by tanejaaryan** [comment]
> @tanejaaryan the entire purpose of a CNN is that all detections occur simultaneously. What you're talking about does not exist within the context of YOLO or any other single shot detector.

Thank-you so much @glenn-jocher! I am new to this field. Would you mind redirecting me to a resource or explaining how the max-det argument works?

**Comment by glenn-jocher** [comment]
@tanejaaryan running inference is like ordering a beer, you order the entire thing regardless of how much you want to drink.

--max-det simply puts a ceiling on the number of allowed detections per image:
https://github.com/ultralytics/yolov5/blob/b83e1a4adcf77ccafa72b22ade6cb3898ccb0e05/detect.py#L192
