### ISSUE TITLE
GPU memory cost doubled and then trebled.

### ISSUE THREAD

**Issue by MarcusNerva** [ultralytics/yolov5#3724]
## ❔Question
I found a really weird phenomenon when I was training yolov5m on multiple GPUs(2 GPUs). The GPU memory cost first doubled and then trebled. This is weird. Did anyone meet this problem before? What causes this phenomenon?

At the same time, GPU 2 takes much more memory than GPU 3.(I trained yolov5m on GPU2 and GPU3)

## Additional context
![WechatIMG59](https://user-images.githubusercontent.com/37070207/122852573-72f72080-d343-11eb-82e7-114eed34364f.jpeg)

![image](https://user-images.githubusercontent.com/37070207/122852405-227fc300-d343-11eb-981a-bf01d850c937.png)

**Comment by glenn-jocher** [comment]
@MarcusNerva I'm not sure what might be the cause. for DDP trainings I would recommend using our Docker image.

**Comment by widerwew** [comment]
Hello, thanks good work.  I got this phenomenon, too. And it may be appeared because of the evaluation. When the evaluation was triggered，The GPU memory costed more and more.
