### ISSUE TITLE
The trained model has low accuracy.

### ISSUE THREAD

**Issue by leeyunhome** [ultralytics/yolov5#3728]
## ❔Question

Hello,

The coco dataset was trained with the following command.
train.py --img 384 --batch 16 --epochs 500 --data coco.yaml --cfg ./models/yolov5s.yaml --weights yolov5s.pt --name coco_384_500epoch

I think the accuracy is too low, can you explain why?
What can be improved?

![image](https://user-images.githubusercontent.com/59910227/122907536-37357880-d38e-11eb-966e-e97336f7227a.png)
![image](https://user-images.githubusercontent.com/59910227/122907609-4ae0df00-d38e-11eb-9dff-6e4f6a63f3f5.png)

Thank you.

**Comment by glenn-jocher** [comment]
@leeyunhome mAP is the only absolute metric, P and R are relative to confidence and are irrelevant to your training results.

**Comment by leeyunhome** [comment]
> @leeyunhome mAP is the only absolute metric, P and R are relative to confidence and are irrelevant to your training results.

In P and R, P is precision and R is Recall?
I didn't understand what you were saying. Sorry.

**Comment by glenn-jocher** [comment]
@leeyunhome yes.

Focus on mAP, it is the only metric that matters in your results.

**Comment by leeyunhome** [comment]
> @leeyunhome yes.
> 
> Focus on mAP, it is the only metric that matters in your results.

then
Looking at the graph above, can it be seen that the learning has gone well?

**Comment by glenn-jocher** [comment]
yes

**Comment by leeyunhome** [comment]
> yes

Thank you.
