### ISSUE TITLE
Rename objects classes

### ISSUE THREAD

**Issue by tetelevm** [ultralytics/yolov5#3733]
I trained my model and ran the script "detect.py". But when I was training, I named the classes in Russian, and now my predictions look like this:

![img](https://user-images.githubusercontent.com/46541662/122929084-317e6980-d373-11eb-9e4d-794cc9b8fdef.png)

How can I rename the class names in `best.pt` (or somewhere else) so that they print normally?

**Comment by glenn-jocher** [comment]
@tetelevm class names are model attributes which you can redefine at any time, i.e.

```python
model.names = ['name0', 'name1', etc.]

# run inference
```
