### ISSUE TITLE
AssertionError: File not found: data.yaml

### ISSUE THREAD

**Issue by FleetingA** [ultralytics/yolov5#3734]
I want to use YOLOv5 to train my custom dataset. I currently have both the yolov5 and my custom folder named UKB_CMB_yolov5 on C drive. My custom folder contains train and valid subfolders and a data.yaml file, the contents of which are:

train: ../UKB_CMB_yolov5/train/images
val: ../UKB_CMB_yolov5/valid/images

nc: 1
names: ['CMB']

When I open cmb and run the command 
`python train.py --img 416 --batch 16 --epochs 5 --data data.yaml --weights yolov5s.pt`,

I get the below error:

```
File "train.py", line 540, in main
    opt.data, opt.cfg, opt.hyp = check_file(opt.data), check_file(opt.cfg), check_file(opt.hyp)  # check files
  File "C:\Users\Angelina\yolov5\utils\general.py", line 218, in check_file
    assert len(files), f'File not found: {file}'  # assert file was found
AssertionError: File not found: data.yaml
```

What could be causing it? Does the data.yaml file have to contain relative or absolute paths (I'm using Windows 10)? 

PS: I created my dataset (including the annotations) using Roboflow.

Thanks in advance!

**Comment by FleetingA** [comment]
I did follow the above steps and still got the Assertion error. Any ideas how to solve?

**Comment by glenn-jocher** [comment]
@Razkolnikova --data requires the path to your data yaml:
```bash
python train.py --data path/to/data.yaml
```

**Comment by FleetingA** [comment]
Many thanks, that solved the problem. :)

**Comment by FleetingA** [comment]
Setting the right path to the .yaml file solves the issue.
