### ISSUE TITLE
Results interpretation

### ISSUE THREAD

**Issue by FleetingA** [ultralytics/yolov5#3735]
Hello,

Another question to do with results interpretation. I am not very sure how to interpret the results.txt file that gets generated after training is over. Also, is there any way to extract the number of false positives, true positives, false negatives, as well as to see the total mean average accuracy and loss (like with yolov4)?

Further, after training is done, can the best weights obtained from training be used to test on unseen data (more specifically, multiple images)?

Thanks in advance again!

**Comment by glenn-jocher** [comment]
@Razkolnikova see Train Custom Data tutorial for plotting results.txt files:
https://docs.ultralytics.com/yolov5/tutorials/train_custom_data#local-logging

**Comment by glenn-jocher** [comment]
@Razkolnikova you can run inference with any weights on any images:
```
python detect.py --weights path/to/best.pt --source ...
```

See README for details:
https://github.com/ultralytics/yolov5#quick-start-examples
