### ISSUE TITLE
Inquiries about test speed

### ISSUE THREAD

**Issue by KangHoyong** [ultralytics/yolov5#3742]
## Additional context

Running test.py takes eight seconds to load the model. It says Speed V100 (ms) 2.0 ms. But it actually takes 10 minutes to process the whole thing. What is the reason? Used GPU V100. We proceeded with Batch size 3.

**Comment by glenn-jocher** [comment]
@KangHoyong commands to reproduce results are supplied directly in README:
https://github.com/ultralytics/yolov5#pretrained-checkpoints
