### ISSUE TITLE
Segmentation Fault error( core dumped) while running test.py on a custom dataset on Raspberry Pi 4

### ISSUE THREAD

**Issue by jaskiratsingh2000** [ultralytics/yolov5#3744]
Hi @glenn-jocher I have custom trained the dataset successfully and trying to measure the the performance by running the **test.py** but on running the `python3 test.py --data data.yaml`

Error is:
```

test: data=data.yaml, weights=yolov5s.pt, batch_size=32, imgsz=640, conf_thres=0.001, iou_thres=0.6, task=val, device=, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=runs/test, name=exp, exist_ok=False, half=False
YOLOv5 🚀 2021-6-23 torch 1.7.0a0+57bffc3 CPU

Fusing layers... 
Model Summary: 224 layers, 7266973 parameters, 0 gradients
val: Scanning 'valid/labels.cache' images and labels... 29 found,
val: Scanning 'valid/labels.cache' images and labels... 29 found,
val: Scanning 'valid/labels.cache' images and labels... 29 found,
               Class     Images     Labels          P          R Segmentation fault (core dumped)

```

Please let me know that what can be the cause of this error? FYI, I am meeting all the requirements that are mentioned within the requirements.txt

**Comment by glenn-jocher** [comment]
@jaskiratsingh2000 it appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below. 


## Requirements

**Python 3.8** or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including **`torch>=1.7`**. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by jaskiratsingh2000** [comment]
@glenn-jocher I am looking forward to the clue on above. Let me know if possible.

**Comment by jaskiratsingh2000** [comment]
@glenn-jocher This is actually the same message I receive from your end whatever be the issue and I am not sure if you exactly read my issue above. This will not solve any problem since I have already taken care of the requirements for it. 
I have mentioned you multiple times and I would really encourage that if you can read the issue clearly and let me know the solution for that if possible I am really in a need of help as I am new to it.. Thanks!
