### ISSUE TITLE
Batch inference (session crash)

### ISSUE THREAD

**Issue by sangeethkumar1997** [ultralytics/yolov5#3746]
## 🐛 Bug
When doing batch prediction with pytorch hub, gpu memory usage is constant but running out of ram and session crashes

## To Reproduce (REQUIRED)

Input:
``` 
import torch
from PIL import Image
import os
device = torch.device('cuda:0')
model = torch.hub.load('ultralytics/yolov5', 'custom', path='runs/train/exp9/weights/best.pt').to(device)
images=os.listdir('yt')
temp1=[]
for i in range(0, len(images)//32):
  ll=i*32
  ul=(i+1)*32
  batchlist=images[ll:ul]
  batchpath=list(map(lambda x :'yt/'+x, batchlist))
  temp1.append(batchpath)

results=[]
a=0
for i in temp1:
  a=a+1
  print(a)
  batchresult=model(i)
  results.append(batchresult.xyxy)


``` 
Output:
```
After 130+ iteration of for loop, without any error , the session crashes.



```

## Expected behavior

Complete all the iteration of for loop successfully

## Environment

 - OS: [Ubuntu]
 - GPU [Tesla T4]

## Additional context
I got the same issue both in google colab and ec2 instance both with Tesla T4 GPU.

This issue is created over the reply for the issue #3743

![Screenshot from 2021-06-23 13-29-25](https://user-images.githubusercontent.com/61541017/123080424-846f2400-d43a-11eb-99f4-c3b4edf062fd.png)
![Screenshot from 2021-06-23 13-30-14](https://user-images.githubusercontent.com/61541017/123080441-8c2ec880-d43a-11eb-977d-676825d28305.png)
![Screenshot from 2021-06-23 13-31-00](https://user-images.githubusercontent.com/61541017/123080450-8fc24f80-d43a-11eb-8326-c4d1f76acce3.png)

**Comment by glenn-jocher** [comment]
@sangeethkumar1997 thanks for the details. You mentioned this is reproducible in Colab, can you provide a Colab notebook to reproduce? I think your code requires indentation to work in python and should also be enclosed by ``` top and bottom when posting to GitHub issues.

**Comment by glenn-jocher** [comment]
@sangeethkumar1997 also passing model to device 0 is redundant and not required as device 0 is used by default if available.

**Comment by sangeethkumar1997** [comment]
@glenn-jocher Hi Jocher, Thank you for the quick response. I have enclosed the code with ```  top and bottom , and also changed the indentation. Also PF link for the colab. https://github.com/sangeethkumar1997/Sangeeth/blob/master/batch_inference.ipynb

**Comment by glenn-jocher** [comment]
@sangeethkumar1997 ok thanks I'll take a look! The default image loader when files/URLs are passed is PIL. I wonder if the images are not being closed correctly by PIL after use:

https://github.com/ultralytics/yolov5/blob/ae4261c7749ff644f45c66b79ecb1fff06437052/models/common.py#L262-L265

**Comment by glenn-jocher** [comment]
@sangeethkumar1997 I'm not able to use your notebook as your youtube video is streaming very slowly (about 80kps), but I created a short code to run inference many times in a for loop and I see zero memory leaks or RAM increases over about 700 images over 2 minutes with python 3.9 on MacOS:

<img width="1422" alt="Screenshot 2021-06-23 at 13 59 34" src="https://user-images.githubusercontent.com/26833433/123093058-74037d00-d42b-11eb-8982-05a846f15fab.png">

**Comment by glenn-jocher** [comment]
@sangeethkumar1997 code to reproduce my test above:

```python
import torch
from tqdm import tqdm

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5x, custom

# Images
img = 'data/images/zidane.jpg'  # or file, PIL, OpenCV, numpy, multiple

# Inference
for i in tqdm(range(1000)):
    results = model(img)
```

**Comment by sangeethkumar1997** [comment]
@glenn-jocher I have no issue running the inference for single image in each loop. I am facing the issue when i am passing a batch of 32 images for each iteration of for loop.

**Comment by glenn-jocher** [comment]
@sangeethkumar1997 I updated my test for 1000 batches at batch-size 32. In Colab RAM usage is steady at 2.08GB at the start to 2.09GB at the end. I don't see any memory issues at all.

```python
import torch
from tqdm import tqdm

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5x, custom

# Images
for f in ['zidane.jpg', 'bus.jpg']:
    torch.hub.download_url_to_file('https://ultralytics.com/images/' + f, f)  # download 2 images
img = ['zidane.jpg'] * 32  # or file, PIL, OpenCV, numpy, multiple

# Inference
for i in tqdm(range(1000)):
    results = model(img)
```

<img width="1002" alt="Screenshot 2021-06-23 at 15 18 46" src="https://user-images.githubusercontent.com/26833433/123103845-aebee280-d436-11eb-9cee-a059c3c19887.png">

**Comment by sangeethkumar1997** [comment]
@glenn-jocher I am able to do batch prediction successfully with the following code 
``` 
import os
images=os.listdir('yt')
results=[]
batchsize=32
for i in range(0, len(images)//batchsize):
    ll=i*batchsize
    ul=(i+1)*batchsize
    batchlist=images[ll:ul]
    batchpath=list(map(lambda x :'yt/'+x, batchlist))
    batchresult=model(batchpath)
    results.append(batchresult.xyxy)

``` 

but if i change the code as below , I am facing the issue with ram.
``` 
import os
images=os.listdir('yt')
temp1=[]
for i in range(0, len(images)//32):
    ll=i*32
    ul=(i+1)*32
    batchlist=images[ll:ul]
    batchpath=list(map(lambda x :'yt/'+x, batchlist))
    temp1.append(batchpath)
results=[]
for i in temp1:
    batchresult=model(i)
    results.append(batchresult.xyxy)

``` 
This is very strange.

**Comment by glenn-jocher** [comment]
@sangeethkumar1997 if variations in your code cause variations in memory usage then the YOLOv5 code (which does not change) is likely not the cause. In this case there is no action for us to take.

**Comment by sangeethkumar1997** [comment]
@glenn-jocher I got it. Thank you for the response.
