### ISSUE TITLE
output txt

### ISSUE THREAD

**Issue by howting** [ultralytics/yolov5#375]
##
How to output detect.py result as txt

**Comment by glenn-jocher** [comment]
@howting your question is already addressed in the argparser arguments for the file you are asking about.
https://github.com/ultralytics/yolov5/blob/1b1681bac9a97f9ce17a77c8c60dbb2c3e1e00d0/detect.py#L137-L154

**Comment by alimousavi1377** [comment]
how can get x,y,w,h , score and class_id for per object of image in  yolov5 :detect.py??

i wanna get these information and save them into txt files for per image
can everyone help me to solve this issue??

**Comment by glenn-jocher** [comment]
@alimousavi1377 `python detect.py --save-txt --save-conf`
