### ISSUE TITLE
need only detection in a particular area

### ISSUE THREAD

**Issue by wlerox** [ultralytics/yolov5#3751]
## ❔Question
ı use yours yolov5 model. but ı need some help, I detect realtime or video detect, my video frame rate (1920X1200). ı need only  detect , my determine  frame. x1=200 y1=100 x2=1700 y2=1100 in video.The picture below explains my request. I change which code block please help
![tsr-region-amer](https://user-images.githubusercontent.com/33762805/123130759-b80b7780-d455-11eb-8717-ef65a2815aa7.png)

**Comment by glenn-jocher** [comment]
@wlerox you can pass any image or part of an image you want for detection, this has nothing to do with YOLOv5 really, this is simple image cropping.

**Comment by wlerox** [comment]
I'm sorry, I'll have to open a little more. yolov5 model prediction in the whole picture , ı need particularly prediction , for example my video frama size 1900X1200 ,yolo preedict particular area and ı want to not change video frame rate.

**Comment by wlerox** [comment]
so i want to change this predict area whenever i want

**Comment by wlerox** [comment]
like some  this
https://www.youtube.com/watch?v=w6gs10P2e1k

**Comment by Enahss** [comment]
Have you solved this problem

I have a same question

**Comment by wlerox** [comment]
i am still researching. ı find one method , this is is cropping all frame in detect.py ,but it is not stable video because not labelled recreate video   . You try this  under the utils  datasets.py . in column add dataset.py , find "class LoadImages" later find 
"img = letterbox(img0, self.img_size, stride=self.stride)[0]" and  Upon this    add    img0=img0[ybegin:heights, xbeging:weights . try it

**Comment by Enahss** [comment]
Thank you 
I will try it

**Comment by wlerox** [comment]
@Enahss are you solve this

**Comment by ysfmani** [comment]
Hello  my friend did you solve it ?

**Comment by ysfmani** [comment]
I need to track and detected only players in the field in the roi without detecting other persosn
![Inkedimage_LI](https://user-images.githubusercontent.com/60297855/130633805-94c6872a-0602-49d2-aea0-5fba873310f8.jpg)

**Comment by wlerox** [comment]
yes I solve. two different solution, 1 is crop image and detect later combine to image , 2 solution firtly detect person later  filtering detect person lacation before showing on the screen

**Comment by shokirxon** [comment]
> yes I solve. two different solution, 1 is crop image and detect later combine to image , 2 solution firtly detect person later filtering detect person lacation before showing on the screen

Hi @wlerox 
Thanks for  sharing "img0=img0[ybegin:heights, xbeging:weights]" above, it is working as expected. 
I was wondering how you did  "crop image and detect later combine to image". 
Could you share your modified code plz? Im attempting to solve the same problem of running detection on a cropped frame

**Comment by bilalomar** [comment]
@wlerox and @shokirxon can you guys share the code or the  method you implemented. it would be of great help. thanks :)

**Comment by animeesh** [comment]
> @wlerox and @shokirxon can you guys share the code or the method you implemented. it would be of great help. thanks :)

did you got the code on this?

**Comment by animeesh** [comment]
> @wlerox and @shokirxon can you guys share the code or the method you implemented? it would be of great help. thanks :)

did you get the code on this?

**Comment by animeesh** [comment]
> @wlerox and @shokirxon can you guys share the code or the method you implemented? it would be of great help. thanks :)

did you get the code on this?

> yes I solve. two different solution, 1 is crop image and detect later combine to image , 2 solution firtly detect person later filtering detect person lacation before showing on the screen

is the code available for opensource?

**Comment by yorucatto** [comment]
@wlerox did you finally solve it? i need help too
