### ISSUE TITLE
After Detections, Output Size and Bitrate very high

### ISSUE THREAD

**Issue by tanejaaryan** [ultralytics/yolov5#3757]
## ❔Question
Why is the output video size very high? For a 7mb input video, I'm receiving a 19 MB output (without the bounding boxes). The bitrate is almost 3X higher. Is there a way to control this? 
File size is of extreme importance to my project.

**Comment by abdulw976** [comment]
Hi, 
I converted yolov5 trained model (.pb format) to tflite using models/tf.py . But while running detect.py with tflite model I am getting "munmap_chunk(): invalid pointer" error.
Can you please help me out.
Thanks

**Comment by glenn-jocher** [comment]
@tanejaaryan you can customize the videoWriter instance here:
https://github.com/ultralytics/yolov5/blob/ae4261c7749ff644f45c66b79ecb1fff06437052/detect.py#L172

**Comment by tanejaaryan** [comment]
> @tanejaaryan you can customize the videoWriter instance here:
> 
> https://github.com/ultralytics/yolov5/blob/ae4261c7749ff644f45c66b79ecb1fff06437052/detect.py#L172

Hi @glenn-jocher , this VideoWriter Object has no attribute to control bitrate. I've tried to play around with codecs but it doesn't really make a difference. Any way arounds? Why is the bitrate even higher btw?
