### ISSUE TITLE
Can someone enlighten me how the detection works if the last layers are convolutional in YOLOv5?

### ISSUE THREAD

**Issue by tserdar** [ultralytics/yolov5#3760]
From my understanding, the output layer in the architecture consists of 3-convolutional layers with different strides for detection in different scales. 

So the predictions returned by Model.forward(img) are not bounding boxes and probabilities, but vectors of multidimensional data. 

Can someone enlighten me then how the detection works? How are those values converted into bounding boxes and confidence scores?

**Comment by glenn-jocher** [comment]
@rocketsfallonrocketfalls model outputs bounding boxes and confidences.

**Comment by tserdar** [comment]
Hi @glenn-jocher, this is the dimensions of pred[0] when I run the **forward function with a batch size of 12.** I think as long as I don't run augmented inference it automatically chooses the output of the first convolutional layer.
![image](https://user-images.githubusercontent.com/62431982/123280555-278e6f00-d509-11eb-9c61-413c46c9e85e.png)

Can you tell me what these dimensions mean (apparently the first one is the batch size)?

**Comment by tserdar** [comment]
I fixed the issue by debugging the loss function.
