### ISSUE TITLE
plot GIoU loss 

### ISSUE THREAD

**Issue by 992060356** [ultralytics/yolov5#3761]
## ❔Question

I can't find the GIoU loss plot function, why are your results.png have GIoU loss curve?   I didn't.

## Additional context
![giou](https://user-images.githubusercontent.com/75258166/123281278-24f93d00-d53c-11eb-8cae-8852499fcd79.PNG)
This is my result.
![results](https://user-images.githubusercontent.com/75258166/123281490-507c2780-d53c-11eb-8ad3-b4c80d7feccc.png)

**Comment by glenn-jocher** [comment]
@992060356 'GIoU' term has been replaced throughout the repository with 'Box'. I'll add a TODO to update the repo images with this change, thank you for letting us know!

**Comment by glenn-jocher** [comment]
TODO: Update results.png images to latest

**Comment by 992060356** [comment]
> @992060356 'GIoU' term has been replaced throughout the repository with 'Box'. I'll add a TODO to update the repo images with this change, thank you for letting us know!

Thank you, I got it . Then where can I see the rules for calculating the loss functions of box, obj, cls, and total loss

**Comment by glenn-jocher** [comment]
@992060356 see loss.py:
https://github.com/ultralytics/yolov5/blob/master/utils/loss.py

**Comment by 992060356** [comment]
> @ 992060356看loss.py：
> https://github.com/ultralytics/yolov5/blob/master/utils/loss.py

Thank you for answering me in detail.
