### ISSUE TITLE
How to save cropped images after inferencing in .tif extension rather than .jpg?

### ISSUE THREAD

**Issue by karndeepsingh** [ultralytics/yolov5#3762]
## ❔Question
Hi, Please help to understand the change needed in code to save cropped images after inferencing in .tif extension rather than .jpg.
Thanks.

**Comment by glenn-jocher** [comment]
@karndeepsingh a simple search for 'crop' in detect.py would save us both a lot of time:
https://github.com/ultralytics/yolov5/blob/417a2f425cd553c1f2a41374a6cd2710aa91d5f0/detect.py#L145-L147

**Comment by karndeepsingh** [comment]
Thankyou so much ! I did that, I wasn't able to find how to change the extension! BTW thanks!

**Comment by karndeepsingh** [comment]
I wasn't trying to inference it from detect.py script. I was doing it from Pytorch hub module. I ran the code shown below, but it saves the cropped image in .jpg format and I want it to be saved in .tif, please help me to do that with following code:
results = model(image_list,size=640)
results.crop()

I tried to change inside the common.py file but it didn't worked

**Comment by karndeepsingh** [comment]
@glenn-jocher  Please help with the above question! I tried changing the things inside the function save_to_box but it is not saving in PNG or TIF. it is continuing to save in JPG only. Please help.

**Comment by glenn-jocher** [comment]
@karndeepsingh https://github.com/ultralytics/yolov5/blob/c6c88dc601fbdbe4e3391ba14245ec2740b5d01a/models/common.py#L316-L317

**Comment by karndeepsingh** [comment]
@glenn-jocher  I went inside the save_one_box function present inside the general.py and change the extension to  ".png", it is still saving the images in "JPG".


def save_one_box(xyxy, im, file='image.jpg', gain=1.02, pad=10, square=False, BGR=False, save=True):
    # Save image crop as {file} with crop size multiple {gain} and {pad} pixels. Save and/or return crop
    xyxy = torch.tensor(xyxy).view(-1, 4)
    b = xyxy2xywh(xyxy)  # boxes
    if square:
        b[:, 2:] = b[:, 2:].max(1)[0].unsqueeze(1)  # attempt rectangle to square
    b[:, 2:] = b[:, 2:] * gain + pad  # box wh * gain + pad
    xyxy = xywh2xyxy(b).long()
    clip_coords(xyxy, im.shape)
    crop = im[int(xyxy[0, 1]):int(xyxy[0, 3]), int(xyxy[0, 0]):int(xyxy[0, 2]), ::(1 if BGR else -1)]
    if save:
        cv2.imwrite(str(increment_path(file, mkdir=True).with_suffix('.jpg')), crop)
#         crop.save(str(increment_path(file, mkdir=True).with_suffix('.tiff')), quality=200)
    return crop

**Comment by karndeepsingh** [comment]
@glenn-jocher Please help on the above issue!!

Thanks!

**Comment by glenn-jocher** [comment]
@karndeepsingh I already pointed you to the relevant code area in https://github.com/ultralytics/yolov5/issues/3762#issuecomment-872349236
