### ISSUE TITLE
Initial weights for benchmark scores

### ISSUE THREAD

**Issue by Johnathan-Xie** [ultralytics/yolov5#3763]
## ❔Question
Were weights for the benchmark scores trained from scratch or initialized via some ImageNet pretraining procedure.  If they were not from scratch could you provide a link to the weights from which the models were trained from?

**Comment by glenn-jocher** [comment]
@Johnathan-Xie all official YOLOv5 models are trained from scratch.

**Comment by glenn-jocher** [comment]
Commands to reproduce training results are shown in README here:
<img width="855" alt="Screenshot 2021-06-25 at 11 19 00" src="https://user-images.githubusercontent.com/26833433/123401530-30ce1900-d5a7-11eb-93b3-a31dd8fb0434.png">

**Comment by Johnathan-Xie** [comment]
Ok.  Thank you for the info.
