### ISSUE TITLE
Mixed Precision training

### ISSUE THREAD

**Issue by jaideep11061982** [ultralytics/yolov5#3767]
## ❔Question

Can we train Yolo on mixed precision using APex. any parameter that enables ?

**Comment by glenn-jocher** [comment]
@jaideep11061982 automatic mixed precision (AMP) training is used by default in YOLOv5. No action is required on your part.
https://github.com/ultralytics/yolov5/blob/374957317a5469742b24291caa52dedfd9d31c99/train.py#L335-L340

**Comment by jaideep11061982** [comment]
Thanku..
one more suggestion. for most of time i have found ranger optimizers have worked bit better than Adam series. 
If we can add parameter for optimizer to be used then would be great, currently its hardcoded to either Adam or SGD

**Comment by jaideep11061982** [comment]
@glenn-jocher  thanku
i see one more version of  hyp file which is hyp.finetune.yaml
does it yields better results ?

**Comment by glenn-jocher** [comment]
@jaideep11061982 the purpose of the hyps is described in the file header of each hyp file
