### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by 123456789mojtaba** [ultralytics/yolov5#377]
Thanks to your good repository.
I have trained yolov5 on my own dataset. how can I Dockerize it using your Docker start?

**Comment by glenn-jocher** [comment]
@123456789mojtaba this is not the right place for general docker questions. This is for yolov5 specific issues.

**Comment by 123456789mojtaba** [comment]
oh sorry

**Comment by 123456789mojtaba** [comment]
I can't connect to your repository.
what should I do?
