### ISSUE TITLE
Trouble detecting Close/Overlapping instances of a class

### ISSUE THREAD

**Issue by chowravc** [ultralytics/yolov5#3771]
## Trouble detecting Close/Overlapping instances of a class

Hello, thanks a lot for this great repository! I have been training a model to detect these features called islands, the bright circles/ellipses in the image below.

![0055](https://user-images.githubusercontent.com/17585864/123438850-bf19bd80-d5ee-11eb-8b93-86d83dcb09eb.jpg)

In some regions, a smaller island is contained entirely within the bounding box of a larger island. Sometimes it looks like this:

![0553](https://user-images.githubusercontent.com/17585864/123439137-0a33d080-d5ef-11eb-9162-01c3c6ecaf75.jpg)

And sometimes there is an island completely inside another.

![0499](https://user-images.githubusercontent.com/17585864/123439205-1b7cdd00-d5ef-11eb-9316-7d50eede82e2.jpg)

This did not seem like it was a problem while I was training my models, I would consistently get an mAP around 95% according to the training logs. While testing the model on the same test/train set and doing an independent mAP calculation, my results were around 77%. The model would not detect an island if it was inside the bounding box of another.

I have tried reducing the iou threshold for NMS while detecting to 0.0 but I did not see much difference.

What could I do to detect these overlapping instances?

```
!python detect.py --source <images> --weights <weights> --iou-thres 0.0 --img-size 1024 --max-det 1000 --conf-thres 0.25 --save-txt --save-conf
```

**Comment by glenn-jocher** [comment]
@chowravc to increase allowable overlaps you increase IoU threshold, not decrease it.

**Comment by chowravc** [comment]
> @chowravc to increase allowable overlaps you increase IoU threshold, not decrease it.

Ohh I see, so I was doing the opposite of what I should have been doing. Thanks for pointing out my mistake!

I'll quickly check the results and resolve the query.

**Comment by chowravc** [comment]
I'm getting much better results now, increasing the iou worked! Resolving this issue.
