### ISSUE TITLE
conf - threshold for test.py and detect.py is different

### ISSUE THREAD

**Issue by tenzinOvO** [ultralytics/yolov5#3777]
## ❔Question
Why the conf - threshold of 0.001 in test.py can acquire great mAP, while 0.001 has poor performance in detect.py. Is the method of computing mAP not suitable of actual scene?

**Comment by dariogonle** [comment]
For calculating the AP or mAP it is necessary to evaluate the model over all confidence thresholds. That's the reason why conf-thres is 0.001. But when you change to production, you may not want predictions with a confidence of 0.01. For this reason a higher conf-thres value is used.

**Comment by tenzinOvO** [comment]
@dariogonle thank you！ I have figured it out.
