### ISSUE TITLE
CIoU_NMS

### ISSUE THREAD

**Issue by milla-Lee** [ultralytics/yolov5#3781]
## ❔Question

hi  author,When I changed NMS in yolov5 to CIoU_NMS, test.py ran normally, but detect.py reported an error:
c1, c2 = (int(x[0]), int(x[1])), (int(x[2]), int(x[3]))
ValueError: cannot convert float NaN to integer
Where should I start to solve the problem? Or what caused it?
Looking forward to your answer

**Comment by Cassieyy** [comment]
Hiiii, have you tried to replace nms with softer nms?

**Comment by Cassieyy** [comment]
btw, how is the performance of ciou_nms?

**Comment by glenn-jocher** [comment]
@Cassieyy CIoU is the default regression loss in YOLOv5. See README for results.

**Comment by Cassieyy** [comment]
> @Cassieyy CIoU is the default regression loss in YOLOv5. See README for results.

Thanks for ur timely reply, i'm sorry for my mistakes, i thought ciou_nms is a new version of nms.😂

**Comment by Cassieyy** [comment]
thanks for ur timely reply!! i'm sorry for my confusion, i thought ciou_nms is a new version of nms😂😂😂. btw, is there any version of softer_nms applied for yolov5?

**Comment by glenn-jocher** [comment]
@Cassieyy oh I'm sorry I didn't see the NMS part. CIoU is used for regression loss. NMS is handled by torch using IoU I believe:
https://github.com/ultralytics/yolov5/blob/1f31b7c503867b6e8f493cf76ed2da490f834fd4/utils/general.py#L569
