### ISSUE TITLE
Is it possible to run a test with a video?

### ISSUE THREAD

**Issue by dariogonle** [ultralytics/yolov5#3783]
## ❔Question
Hi,

  I would like to test a model with a video. Is it possible? I mean to run test.py, I already know that running detect.py it is.

**Comment by glenn-jocher** [comment]
@dariogonle please read the README inference with detect.py section:
<img width="953" alt="Screenshot 2021-06-26 at 13 47 23" src="https://user-images.githubusercontent.com/26833433/123511980-0d799b80-d685-11eb-9f5f-05851d67b11b.png">
