### ISSUE TITLE
How to change Input Image Training size?

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#3796]
## ❔Question

I have a training image size is  720x1280
How can i change it in train file?

**Comment by glenn-jocher** [comment]
@hammadyounas2008 --img-size is a training parameter:
```
python train.py --img 1280
```

**Comment by ghost** [comment]
But it train on 1280x1280 not 720x1280?

**Comment by glenn-jocher** [comment]
@hammadyounas2008 `python train.py --img 1280` trains on 1280 mosaics (recommended), `python train.py --img 1280 --rect` trains on 1280 long side rectangles (not recommended).

**Comment by ghost** [comment]
Ok, thanks. How to increase filters size for custom data.?
