### ISSUE TITLE
Performance comparison(s, m, l , x)

### ISSUE THREAD

**Issue by Ronald-Kray** [ultralytics/yolov5#3800]
## ❔Question

I'm curious about the performance comparison of Yolov5 
The attached graph means that Yolov5m5's mAP can have better than Yolo 5l5's mAP or Yolov5l5's mAP can have a better than Yolov5x5's mAP????
@glenn-jocher @wudashuo

![Question](https://user-images.githubusercontent.com/76469976/123551560-4475ad00-d76a-11eb-9f5f-7c6f75a7e240.PNG)

**Comment by glenn-jocher** [comment]
@Ronald-Kray yes each model is evaluated at various image sizes in this chart. Commands to reproduce this chart are directly below it in the comments.
