### ISSUE TITLE
model information

### ISSUE THREAD

**Issue by Laudarisd** [ultralytics/yolov5#3803]
Can anyone explain me about the cnn layers in yolo models? such as 5l.pt, 5s.pt. 

And how can i see detail architecture of YOLOv5?
Thank you.

**Comment by glenn-jocher** [comment]
@Laudarisd YOLOv5 model architectures are defined in their yaml configuration files, i.e.:
https://github.com/ultralytics/yolov5/blob/5e976a274d2458869ae9743a93d5c2f67d6fa79a/models/yolov5s.yaml#L12-L48

**Comment by Laudarisd** [comment]
Thank you so much.
