### ISSUE TITLE
RuntimeError: The size of tensor a (80) must match the size of tensor b (56) at non-singleton dimension 3

### ISSUE THREAD

**Issue by OrjwanZaafarani** [ultralytics/yolov5#3809]
## ❔Question
Running the following code produces the error:
`RuntimeError: The size of tensor a (80) must match the size of tensor b (56) at non-singleton dimension 3`

What should I do?
```
from joblib import Parallel, delayed
import multiprocessing

# Images
img1 = Image.open('07574519.jpg').convert('RGB')  # PIL image
img2 = Image.open('07575814.jpg').convert('RGB')  # OpenCV image (BGR to RGB)
imgs = [img1, img2]  # batch of images

numCores = multiprocessing.cpu_count() - 1
print("Using", numCores,"cores")

def detectLogos(image):
    results = model(image)
    return results

logoDet = Parallel(n_jobs=numCores,prefer="threads",backend='threading',require='sharedmem')(delayed(detectLogos)(i) for i in imgs)
```

Update:
When I run the same code again it magically works. if I restarted the kernel and run it again, it fails.

**Comment by glenn-jocher** [comment]
@OrjwanZaafarani I think this will only work if your images are of identical shape. 

For the model forward method to be thread safe you may need to update settings in the Detect() forward method such as inplace=False or force grid construction on every image:
https://github.com/ultralytics/yolov5/blob/c6c88dc601fbdbe4e3391ba14245ec2740b5d01a/models/yolo.py#L49-L70
