### ISSUE TITLE
Should one eliminate _box_, _cls_, _obj_ params from a hyperparameters file?

### ISSUE THREAD

**Issue by cardo-correrdor** [ultralytics/yolov5#3811]
## Should one eliminate _box_, _cls_, _obj_ params from a hyperparameters file?
In the `train.py` you got an overwritten _box_, _cls_, _obj_ parameters (see lines 259 - 261). I couldn't find evidence of using values for those params from a  params file.

Moreover, I saw finetuned params were added recently (in yolov5/data/hyps/). From the `train.py` it looks like 'evolve' regime calls the same `train` function which overwrites those params. If that is actually true then may be there should be some changes... looks like some unintentional logical flaw (perhaps dosen't affect params search timing).

**Comment by glenn-jocher** [comment]
@cardo-correrdor everything is correct, no modifications are required.
