### ISSUE TITLE
How to change number of filters and filter size for custom data?

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#3815]
## ❔Question
Hi, How to change the number of filters and filter size for custom data?  Also, does change the hyperparameter effects the mAP score? For example, I have mAP 0.67, will it increase after increasing the filter size and hyperparameters?

**Comment by glenn-jocher** [comment]
@hammadyounas2008 experimental results are obviously up to you to determine empirically on your own data. You can modify any model architecture directly in it's yaml file:
https://github.com/ultralytics/yolov5/blob/master/models/yolov5s.yaml
