### ISSUE TITLE
Use wandb sweeps with YOLOv5 

### ISSUE THREAD

**Issue by yedmed** [ultralytics/yolov5#3828]
## ❔Question
Hello, 
First of all, thank you for the great work you have done so far. 
I am trying to use sweeps with YOLOv5 but apparently, it is not compatible. YOLOv5 is getting the hyperparameters from a hyp yaml file where sweeps executes the train's script by passing the hyperparameters as parameters, therefore I get the following error: 

`train.py: error: unrecognized arguments: --hyp.anchor_t=7.225289531655344 --hyp.box=0.043435988892298216 --hyp.cls=0.667897780671777 --hyp.cls_pw=0.7244308054198425 --hyp.degrees=0.5323292971959508 --hyp.fliplr=0.4565334885444531 --hyp.flipud=0.0036623437301633362 --hyp.hsv_h=0.020569196606891084 --hyp.hsv_s=0.8272109830420395 --hyp.hsv_v=0.45229517488149307 --hyp.iou_t=0.33629706281322547 --hyp.lr0=0.00400979397272457 --hyp.lrf=0.23288620454081715 --hyp.mixup=0.08188527795592496 --hyp.momentum=1.7110587364987746 --hyp.mosaic=2 --hyp.obj=0.3868508248061794 --hyp.obj_pw=1.9185801224451993 --hyp.scale=1.3973616605170278 --hyp.shear=0.5938510372919916 --hyp.translate=0.10033980506963694 --hyp.warmup_bias_lr=0.18556366676204217 --hyp.warmup_epochs=5 --hyp.warmup_momentum=1.5610831212666887 --hyp.weight_decay=0.00046710112618196433` 

An idea or a trick on how to make it work?
Thanks for your help.
## Additional context

@glenn-jocher, @AyushExel, I saw in a previous discussion that you are working on a "sweeps" tutorial! Did you manage to make it or not yet?

**Comment by AyushExel** [comment]
@yedmed hey sorry for the late reply. I haven't tested sweeps with YOLOv5. We might need some simple workarounds to pass hyperparameters and other arguments. I'll try it and reach out with the steps early next week :)

**Comment by glenn-jocher** [comment]
@AyushExel yes, we might need some sort of workaround for those hyp arguments...

**Comment by yedmed** [comment]
@AyushExel I would be so grateful, I will be waiting for your reply. This will be so helpful for me and for others who uses YOLO with wandb !!!!

**Comment by yedmed** [comment]
@glenn-jocher I think that you have already used it before in a previous project. Is there a simple way to do it ?

**Comment by glenn-jocher** [comment]
@yedmed yes I've done this before. I evolved 300 generations of COCO128 while logging them all to W&B. Then afterwards I created a sweep in the project.
https://wandb.ai/glenn-jocher/COCO128_evolve/sweeps?workspace=user-glenn-jocher


<img width="1695" alt="Screenshot 2021-07-04 at 14 35 05" src="https://user-images.githubusercontent.com/26833433/124385185-0aaa2680-dcd5-11eb-989e-c2dac56a94fe.png">

**Comment by AyushExel** [comment]
@yedmed https://github.com/ultralytics/yolov5/pull/3938
