### ISSUE TITLE
I got some errors and warning when I used distributed training.

### ISSUE THREAD

**Issue by Dejavuvvw** [ultralytics/yolov5#3829]
### 1. Why this warning appears?
![image](https://user-images.githubusercontent.com/45518210/123895192-035fe180-d992-11eb-944f-48d9e0d5bb6d.png)
### 2. This error is also confused me a lot.
![image](https://user-images.githubusercontent.com/45518210/123895374-56d22f80-d992-11eb-919d-98752159a512.png)
![image](https://user-images.githubusercontent.com/45518210/123895400-618cc480-d992-11eb-978e-febd2cd1680c.png)

## Additional context
My train command is:
`python -m torch.distributed.launch --nproc_per_node 4 train.py --batch 8 --data data/gdgrid.yaml --device 0,1,2,3 --cfg models/yolov5x_gd.yaml --multi-scale --adam --weights yolov5x.pt --epochs 150`

**Comment by glenn-jocher** [comment]
@18779042442 you should use torch.distributed.run, not .launch with the latest docker image for DDP.
