### ISSUE TITLE
Find those images from the testing dataset in which object class have been misclassified?

### ISSUE THREAD

**Issue by akshat-suwalka** [ultralytics/yolov5#3834]
## ❔Question
Hi again @glenn-jocher 
Is there any way to find only those images from my testing dataset where the object is being incorrectly classified by Yolov5?
I just need the location or that image so that I can understand by just looking that image , which object in that image are misclassified by mine algorithm.

Thanks and Hope this find in your good health.

**Comment by glenn-jocher** [comment]
@akshat-suwalka every image in every val/test set will have hundreds of FPs and FNs since testing is performed at --conf 0.001 in order to generate a full PR curve for mAP computation.
