### ISSUE TITLE
Onnx GPU export error

### ISSUE THREAD

**Issue by SkanderMarsit** [ultralytics/yolov5#3837]
Hello, 

I'm having an issue exporting my trained model to ONNX on GPU. 

The error is the following: 
`ONNX: export failure: Input, output and indices must be on the current device` 
after I run: 
`python3 export.py --weights ../best.pt --include onnx  --device 0`.
My code is up-to-date with the current master. 
I have tried adding `model.model[-1].export = True`, but it did't resolve the problem. 

I'm grateful for your help.

**Comment by glenn-jocher** [comment]
@SkanderMarsit not all arguments are compatible during export. For ONNX please export on the default device (CPU).
