### ISSUE TITLE
More information about the metrics that YOLOv5 generates

### ISSUE THREAD

**Issue by FleetingA** [ultralytics/yolov5#3842]
Hi all,

Is it possible to obtain more information about what the different metrics that get generated in the results mean, in terms of definitions/underlying constructs, but also calculations?

- objectness loss
- box loss
- classification loss
- information contained in the correlogram, etc.

Also, where can one see the IoU metric, or is there a way to derive other metrics as well?

Thanks in advance!

**Comment by glenn-jocher** [comment]
@Razkolnikova these are all standard object detection losses and metrics which are used across industry. As I mentioned before for details on loss function see loss.py, for details on metrics computation see metrics.py and for a simple explanation see https://en.wikipedia.org/wiki/Precision_and_recall
