### ISSUE TITLE
Is it possible to hide a label ?

### ISSUE THREAD

**Issue by rmarquet21** [ultralytics/yolov5#3846]
## ❔Question

Hello,
I trained a model to be able to detect people without and with a mask and then I would only like to display the box of people who do not wear them, but I can't find how to do it.
If anyone could help me thanks!

## Additional context
How I call my custom model
```
model = torch.hub.load(f'{directory_path}/object_detection', 'custom',
                       path=f'{directory_path}/object_detection/last.pt',
                       source='local')
```

**Comment by glenn-jocher** [comment]
@rmarquet21 you can filter classes during inference:
```
python detect.py --classes 0 1 2
```

**Comment by ChinaRush** [comment]
detect.py /128
for c in det[:, -1].unique():
                    #n = (det[:, -1] == c).sum()  # detections per class
                    if names(int[c]) == 'no-mask':
                       s += f"{n} {names[int(c)]}{'s' * (n > 1)}, "  # add to string

**Comment by rmarquet21** [comment]
> detect.py /128
> for c in det[:, -1].unique():
> #n = (det[:, -1] == c).sum() # detections per class
> if names(int[c]) == 'no-mask':
> s += f"{n} {names[int(c)]}{'s' * (n > 1)}, " # add to string

I use it with pytorch hub it still works ?

**Comment by rmarquet21** [comment]
I found how to fix my problem, I added an argument to model.

```python
model = torch.hub.load(f'{directory_path}/object_detection', 'custom',
                       path=f'{directory_path}/object_detection/last.pt',
                       source='local')
model.classes = [1] # 0 is with mask and 1 with no mask and I just want no mask
```
