### ISSUE TITLE
Choosing a larger model

### ISSUE THREAD

**Issue by Yu-Hang** [ultralytics/yolov5#3848]
## ❔Question

Hi there, I'm trying to choose the large model during training:

`python train.py --img 1280 --batch 14 --epochs 1000 --data '/slurm_storage/yuh5/data/thin_Pf_YOLOv5/exp3/data.yaml' --cfg ./models/custom_yolov5s.yaml --weights yolov5l.pt --name yolov5s_results  --cache  --rect`

However, the number of parameters below seems to indicate it's still using the small model:

```
Model Summary: 283 layers, 7257791 parameters, 7257791 gradients, 16.8 GFLOPS

Transferred 43/370 items from yolov5l.pt
Scaled weight_decay = 0.000546875
Optimizer groups: 62 .bias, 70 conv.weight, 59 other
```

Can you see what went wrong here?

**Comment by ChinaRush** [comment]
your model size only depend on  *yaml files. may be you still use original yaml files, you need keep the *.yaml files and *pt files matched

**Comment by glenn-jocher** [comment]
@Yu-Hang if you just want to start from a pretrained model then you don't need to pass any yaml file. See **Train Custom Data** tutorial to get started, which explains all of this already:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by Yu-Hang** [comment]
Oh I see. Thanks.
