### ISSUE TITLE
`check_python()` always fail

### ISSUE THREAD

**Issue by WenqingZong** [ultralytics/yolov5#3849]
## 🐛 Bug
`check_python()` always fail

## To Reproduce (REQUIRED)

Input:
None

Output:
AssertionError                            Traceback (most recent call last)
~/yolov5-master/train.py in <module>
    658 if __name__ == "__main__":
    659     opt = parse_opt()
--> 660     main(opt)

~/yolov5-master/train.py in main(opt)
    526         print(colorstr('train: ') + ', '.join(f'{k}={v}' for k, v in vars(opt).items()))
    527         check_git_status()
--> 528         check_requirements(exclude=['thop'])
    529
    530     # Resume

~/yolov5-master/utils/general.py in check_requirements(requirements, exclude)
    149     # Check installed dependencies meet requirements (pass *.txt file or list of packages)
    150     prefix = colorstr('red', 'bold', 'requirements:')
--> 151     check_python()  # check python version
    152     if isinstance(requirements, (str, Path)):  # requirements.txt file
    153         file = Path(requirements)

~/yolov5-master/utils/general.py in check_python(minimum, required)
    142     result = pkg.parse_version(current) >= pkg.parse_version(minimum)
    143     if required:
--> 144         assert result, f'Python {minimum} required by YOLOv5, but Python {current} is currently installed'
    145     return result
    146

AssertionError: Python 3.6.2 required by YOLOv5, but Python 3.9.1+ is currently installed

## Expected behavior
I expect it runs smoothly since I have python 3.9.1 which of cause is newer than python 3.6.2

## Environment
Python 3.9.1+ (default, Jan 20 2021, 14:49:22)
[GCC 10.2.1 20210110] on linux

**Comment by glenn-jocher** [comment]
@NevilleZong I think you're not understanding how python `assert` statements work. In any case, we require a minimum reproducible example of your issue to being taking a look. Here's a guide:

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by glenn-jocher** [comment]
@NevilleZong there's something incorrect about your python version. The '+' symbol is not recognized in any valid python version. Valid python versions may be downloaded from https://www.python.org/downloads/
