### ISSUE TITLE
Focus module?

### ISSUE THREAD

**Issue by HuKai97** [ultralytics/yolov5#3850]
Hello, which paper is your focus module from? Or did you make it yourself? What's the theory?
![image](https://user-images.githubusercontent.com/68494594/124094585-8022b680-da8b-11eb-882e-3afd9944184d.png)

**Comment by glenn-jocher** [comment]
@coderhukai I developed the Focus() module myself for YOLOv5. For details see the Focus() layer discussion  https://github.com/ultralytics/yolov5/discussions/3181

> I've received lots of interest in the **YOLOv5 🚀 Focus layer**, so I've written a short documentation here on it. I created the Focus layer myself when evolving the YOLOv3 architecture into YOLOv5, and did not adopt it from other sources. The **main purpose** of the Focus layer is to **reduce layers, reduce parameters, reduce FLOPS, reduce CUDA memory, increase forward and backward speed while minimally impacting mAP**.
> https://github.com/ultralytics/yolov5/blob/17b0f71538d3e9990e0e6c4b5c7c48375956efa3/models/common.py#L163-L171
> 
> The YOLOv5 Focus layer replaces the **first 3 YOLOv3 layers** with a **single layer**:
> <img width="1033" alt="Focus Layer" src="https://user-images.githubusercontent.com/26833433/118395682-f38f7680-b64b-11eb-8fe4-6d6103ba8176.png">
> 
> I settled on the current Focus layer design after a significant effort profiling alternative designs to the YOLOv3 input layers, both for immediate forward/backward/memory profiling results, and also comparing full 300 epoch COCO trainings to determine the effect on mAP. You can profile the Focus layer very easily against the YOLOv3 original layers replaced using the [YOLOv5 `profile()` function](https://github.com/ultralytics/yolov5/blob/17b0f71538d3e9990e0e6c4b5c7c48375956efa3/utils/torch_utils.py#L96-L102):
> 
> ```python
> import torch.nn as nn
> from models.common import Focus, Conv, Bottleneck
> from utils.torch_utils import profile 
> 
> m1 = Focus(3, 64, 3)  # YOLOv5 single layer
> m2 = nn.Sequential(Conv(3, 32, 3, 1), Conv(32, 64, 3, 2), Bottleneck(64, 64))  # YOLOv3 equivalent layers
> 
> profile(x=torch.randn(16, 3, 640, 640), ops=[m1, m2], n=100)  # profile both 100 times at batch-size 16
> ```
> 
> In our [YOLOv5 Google Colab notebook](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb) with a V100 GPU I get the following result:
> ```python
> 1.8.1+cu101 cuda _CudaDeviceProperties(name='Tesla V100-SXM2-16GB', major=7, minor=0, total_memory=16160MB, multi_processor_count=80)
> 
>       Params      GFLOPS    forward (ms)   backward (ms)                   input                  output
>         7040       23.07           4.958           12.76       (16, 3, 640, 640)      (16, 64, 320, 320)  # Focus()
>        40160       140.7           26.15             125       (16, 3, 640, 640)      (16, 64, 320, 320)  # YOLOv3 layers
> ```

**Comment by HuKai97** [comment]
Thank you! 😃

**Comment by GitHubChrischen** [comment]
does anyone tried  5x5  with stride= 2 convolution layer ？
