### ISSUE TITLE
How can I pretrain the backbone with classification dataset for better domain-specific features?

### ISSUE THREAD

**Issue by tserdar** [ultralytics/yolov5#3854]
Is it possible to pretrain the backbone of YOLOv5 models using a classification dataset?

**Comment by glenn-jocher** [comment]
@rocketsfallonrocketfalls sure, see classififier.py in classifier branch:
https://github.com/ultralytics/yolov5/blob/classifier/classifier.py

**Comment by tserdar** [comment]
@glenn-jocher, thanks!
