### ISSUE TITLE
where can i get the complete model architecture Image of yoloV5 ?

### ISSUE THREAD

**Issue by gokulsoman15** [ultralytics/yolov5#3856]

**Comment by glenn-jocher** [comment]
@gokulsoman15 https://github.com/ultralytics/yolov5/blob/c6c88dc601fbdbe4e3391ba14245ec2740b5d01a/models/yolov5s.yaml#L12-L48

**Comment by FleetingA** [comment]
![image](https://user-images.githubusercontent.com/78978040/124267732-90d93800-db30-11eb-922d-f7be28a3e25e.png)

Is it safe to say that this image is a correct representation of YOLOv5's architecture?

**Comment by glenn-jocher** [comment]
@Razkolnikova we've made visualizing YOLOv5 🚀 architectures super easy. There are two main ways:

## `model.yaml`

Each model has a corresponding yaml file that displays the model architecture. Here is YOLOv5s, defined by `yolov5s.yaml`:
https://github.com/ultralytics/yolov5/blob/831773f5a23926658ee76459ce37550643432123/models/yolov5s.yaml#L12-L48

## TensorBoard Graph

Simply start training a model, and then view the TensorBoard Graph for an interactive view of the model architecture. This example shows YOLOv5s viewed in our [Notebook](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb) –  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

```python
# Tensorboard
%load_ext tensorboard
%tensorboard --logdir runs/train

# Train YOLOv5s on COCO128 for 3 epochs
python train.py --weights yolov5s.pt --epochs 3
```

<img width="893" alt="Screenshot 2021-04-11 at 01 10 09" src="https://user-images.githubusercontent.com/26833433/114286928-349bd600-9a63-11eb-941f-7139ee6cd602.png">

**Comment by FleetingA** [comment]
I see, and if one is training YOLOv5 locally in cmd, would the commands
still be the same:

load_ext tensorboard
tensorboard --logdir runs/train

**Comment by pderrenger** [comment]
Yes, the commands are the same for running TensorBoard locally. Just ensure TensorBoard is installed in your environment.
