### ISSUE TITLE
Show N validation images with largest errors?

### ISSUE THREAD

**Issue by duckduck-sys** [ultralytics/yolov5#3858]
## ❔Question
It's often instructive to visually inspect validation images with large errors, helps find the circumstances under which a model tends to fail. Is there an option implemented somewhere to sample/save validation images with high model inference error?

**Comment by glenn-jocher** [comment]
@duckduck-sys thanks for your feedback! We don't have this capability at the moment, but we will place it on our internal feature request list.

**Comment by duckduck-sys** [comment]
@glenn-jocher Great, looking forward to it!
