### ISSUE TITLE
Prediction result cannot be shown correctly

### ISSUE THREAD

**Issue by ljjsfe** [ultralytics/yolov5#386]
I used the updated Yolov5 on my data and the result showed as following:

![image](https://user-images.githubusercontent.com/21991669/87318757-5ffe8e00-c4ee-11ea-90a2-5293f9bf9055.png)

I used the previous version and it can output the correct result in P, R, mAP. However, this one cannot. I am not sure the issue is in the test.py or utils. Thank you for checking it.

**Comment by glenn-jocher** [comment]
@ljjsfe start from the tutorial. Training operates correctly. Do not use bug labels for questions.

**Comment by ljjsfe** [comment]
Yeah
