### ISSUE TITLE
Use ONNX model in opencv.dnn

### ISSUE THREAD

**Issue by maxmahe1** [ultralytics/yolov5#3860]
## ❔Question
Error when using cv2.dnn.readNetFromONNX ? 

## Additional context
I trained my own network and converted it to onnx with export.py. However when i try to use it with cv2.dnn.readNetFromONNX I keep getting a dimension error when forwarding in net. Has anyone done the same thing ? Thanks for the help :)

**Comment by Preference-cmd** [comment]
@maxmahe1 Perhaps the 'slice' operation is not supported by dnn module, you might need another implementation to replace the 'slice' operation.

**Comment by glenn-jocher** [comment]
@maxmahe1 good news 😃! Your original issue may now be fixed ✅ in PR #4833. This PR implements architecture updates to allow for ONNX-exported YOLOv5 models to be used with OpenCV DNN.

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
