### ISSUE TITLE
Precision curve looking weird

### ISSUE THREAD

**Issue by vasnakh** [ultralytics/yolov5#3862]
## ❔Question
I am looking at the metrics and I noticed that the precision curve (shown below) is acting a bit weird - It goes up and then all of a sudden drops. The other graphs look okay. Does anyone have any idea why this is and what might fix this issue? Any help is appreciated. 

## Additional context
![Metrics_yolo](https://user-images.githubusercontent.com/11311208/124309384-7e0a3780-db1f-11eb-8c1d-2fee3e1a87cd.png)

**Comment by vasnakh** [comment]
I am not actually sure whether this is an issue but just wanted to make sure. Recall on the other hand goes up around same epoch so this might just be fine! Also I know that I am overfitting at around 80 epochs.

**Comment by glenn-jocher** [comment]
@vasnakh P and R are evaluated at arbitrary confidence levels and can be ignore as they are not absolute metrics.

mAP is the area under the P-R curve evaluated at all confidence levels, and is what you should look at.
