### ISSUE TITLE
Training Error: wandb: Network error resolved after 0:10:18.903735, resuming normal operation -- Verifying that training has gone well

### ISSUE THREAD

**Issue by FleetingA** [ultralytics/yolov5#3867]
I got results from training on a custom dataset this morning. It looks like there has been some network error - could be that the internet has stopped during the night or so (see error image below). The 300 epochs have completed (with the network error code), but then training has resumed for some reason (without me running the train command again):

![image](https://user-images.githubusercontent.com/78978040/124349808-0dc7e880-dbe9-11eb-9909-42c1b2c20353.png)

I still got the below results, but I am wondering whether everything has gone well (given the network error), or I should re-train.

![image](https://user-images.githubusercontent.com/78978040/124349828-27693000-dbe9-11eb-938c-5e62e9eacb63.png)

Any advice is much appreciated!

**Comment by glenn-jocher** [comment]
@Razkolnikova training never 'resumes on it's own', it resumes using the `python train.py --resume` command.

**Comment by FleetingA** [comment]
This is what I find puzzling too. Training had stopped before I was awake
(I had left my pc on), the 299 epochs (of a maximum of 300, which I had
set) had completed (with the network error), then training had resumed. So
when I woke up it was on the 4th/300 epoch (of a new training cycle).

This is why I find it hard to tell whether training has completed correctly.
