### ISSUE TITLE
Confidence threshold for bounding box

### ISSUE THREAD

**Issue by NMVRodrigues** [ultralytics/yolov5#3868]
Greetings,

Is there any parameter that can be changed so bounding boxes are only considered if they have a certainty above some threshold?
So, say the model is detecting something with a certainty of 0.001, that would be ignored since its too low and is just lowering the recall.

Best regards,
Nuno

**Comment by glenn-jocher** [comment]
@NMVRodrigues this is the entire purpose of the confidence threshold:
```
python detect.py --conf 0.5
```

**Comment by NMVRodrigues** [comment]
@glenn-jocher 

Sorry, was looking in the training script.
If I understand correctly, detect is only for inference correct? Is it possible to do that during training? To get an accurate Recall plot.

**Comment by glenn-jocher** [comment]
@NMVRodrigues test.py returns metrics like recall.

**Comment by NMVRodrigues** [comment]
@glenn-jocher Thank you very much for the help, closing the issue.
