### ISSUE TITLE
Why doesn't Pytorch Hub use half-precision?

### ISSUE THREAD

**Issue by andrew-healey** [ultralytics/yolov5#3869]
## ❔Question

I noticed that [`hubconf.py`](https://github.com/ultralytics/yolov5/blob/831773f5a23926658ee76459ce37550643432123/hubconf.py#L40-L55) never applies half-precision in `torch.hub.load`:

```py
    try:
        if pretrained and channels == 3 and classes == 80:
            model = attempt_load(fname, map_location=torch.device('cpu'))  # download/load FP32 model
        else:
            cfg = list((Path(__file__).parent / 'models').rglob(f'{name}.yaml'))[0]  # model.yaml path
            model = Model(cfg, channels, classes)  # create model
            if pretrained:
                ckpt = torch.load(attempt_download(fname), map_location=torch.device('cpu'))  # load
                msd = model.state_dict()  # model state_dict
                csd = ckpt['model'].float().state_dict()  # checkpoint state_dict as FP32
                csd = {k: v for k, v in csd.items() if msd[k].shape == v.shape}  # filter
                model.load_state_dict(csd, strict=False)  # load
                if len(ckpt['model'].names) == classes:
                    model.names = ckpt['model'].names  # set class names attribute
        if autoshape:
            model = model.autoshape()  # for file/URI/PIL/cv2/np inputs and NMS
        device = select_device('0' if torch.cuda.is_available() else 'cpu') if device is None else torch.device(device)
        return model.to(device)
```

So my question is: why is the model never converted to FP16, even if YOLOv5 detects a GPU? Would you accept a PR adding a `half` keyword argument to `_create` that would convert the model to half-precision?

Also, I noticed that in `hubconf.py`, you `attempt_load` the model to CPU and later convert it to GPU if necessary, while in `detect.py`, you `attempt_load` the model to the target device, whether that is CPU or GPU, directly. Is there any reason for this?

**Comment by glenn-jocher** [comment]
@Sesamestrong they already do.

YOLOv5 PyTorch Hub models run their forward passes under automatic mixed precision context managers:

https://github.com/ultralytics/yolov5/blob/9d86b54eb37ea9d2b4ae3cda0dfe8ab7aa16f2c6/models/common.py#L275-L277
