### ISSUE TITLE
detection classes parameter - usage

### ISSUE THREAD

**Issue by shashi-netra** [ultralytics/yolov5#387]
## ❔Question
Hi, I am a newbie to this awesome project. 

How do I filter output for a specific list of classes?

`python3 detect.py --source videos/video.mp4 --output video_out/ --weights best.pt --conf-thres 0.4 --classes 104`

I can see this is the way to filter it into a single class. But can we provide a list of classes indexes so we can show a select list of classes?

**Comment by glenn-jocher** [comment]
@shashi-netra sure no problem. You would use this syntax:

`python detect.py --class 0 1 2 4`

**Comment by shashi-netra** [comment]
Ohh silly me, I tried everything else comma separating, quoting, etc. except this. thanks!

**Comment by glenn-jocher** [comment]
I've updated this a bit to help everyone understand better in the future https://github.com/ultralytics/yolov5/commit/094079bd26ad7965a04430c877489109dd6004d2
