### ISSUE TITLE
训练自己的数据集的时候到第60个epoch左右损失就会突然上升，mAP也会直线下降

### ISSUE THREAD

**Issue by yg2024** [ultralytics/yolov5#3870]
![error](https://user-images.githubusercontent.com/32722588/124373699-24dd0800-dcc7-11eb-8bcf-2008a04f1012.png)

**Comment by tetelevm** [comment]
@glenn-jocher You should be prohibited from creating issues without the "I know how to create a minimally reproducible example" checkbox :)

**Comment by wudashuo** [comment]
首先Glenn大神不会中文，而且你这个问题是最最最基本的深度学习问题，如果你这都不知道怎么解决建议先学好基础知识再做研究
