### ISSUE TITLE
How can I inference the model for real-time using webcam? (using cv2.VideoCapture)

### ISSUE THREAD

**Issue by BakingBrains** [ultralytics/yolov5#3873]
## ❔Question
For YOLOv3 we used to load the model using opencv dnn module along with weight file, cfg file and object.names, Is there any way I can do similar thing in YOLOv5 apart from pytorch hub.

**Comment by glenn-jocher** [comment]
@BakingBrains as the README explains for webcam inference:
```
python detect.py --source 0
```
