### ISSUE TITLE
About detecting multi streams at the same time

### ISSUE THREAD

**Issue by xin6211** [ultralytics/yolov5#3874]
## 🐛 Bug
when i use .txt which include multi streams like rtsp to detect multi streams at the same time and save videos(i changed detect.py).The videos saved duration shorter than the origin video, then i find the class LoadStreams.update(), i found it 
![image](https://user-images.githubusercontent.com/57249279/124386067-0698fb80-dd0b-11eb-960e-9b8f67c23981.png)
it use time.sleep() to synchronize frame in streams and it will read too fast sometimes to make saved videos shorter than the origin videos. And i think it should use a thread lock to sync maybe better

## To Reproduce 

dataset.py LoadStreams.update()
```
time.sleep(1 / self.fps[i])  # wait time
```

## Expected behavior
Using thread locks to sync

## Environment

 - OS: [Ubuntu]
 - GPU [RTX 3090]

**Comment by glenn-jocher** [comment]
@Golds-l hi thanks for the bug report! Can you submit a PR with your proposed fix? Thanks! 

Please see our [Contributing Guide](CONTRIBUTING.md) to get started.

**Comment by glenn-jocher** [comment]
@Golds-l also be aware that detect.py was updated today with multi-stream saving capability in PR https://github.com/ultralytics/yolov5/pull/3864

**Comment by xin6211** [comment]
> @Golds-l also be aware that detect.py was updated today with multi-stream saving capability in PR #3864

thank you for replying so fast, i`ll brose the #3864

**Comment by xin6211** [comment]
> @Golds-l also be aware that detect.py was updated today with multi-stream saving capability in PR #3864
I`think it is useless. LoadStreams.updata() has no changes, there have some frames lost because we used times in previous frame and skipped current frame to detect next frame.If it faster than 1/fps, previous frame will be saved.

**Comment by glenn-jocher** [comment]
@Golds-l sure, please submit a PR with your proposed fix, Thanks!

**Comment by fpiemontese** [comment]
I've run into a similar issue, where videos produced by `detect.py` with YouTube sources were shorter than the original. Moreover, on repeated runs I got different numbers of output frames from the same input video, especially when the GPU (P100 from Google Colab) was under heavy load and the inference time was higher.

I noticed this while trying to run inference on a YouTube video streams at intervals of `n` frames, rather than on each frame. Is this why the `read` parameter is hardcoded to 1 in the `update()` function of `LoadStreams`?

**Comment by glenn-jocher** [comment]
@fpiemontese most video inference is done with LoadImages() which runs on a video frame-sequentially. LoadStreams is intended to maintain lag-free inference for multiple real-time streams like RTSP security cameras etc.

**Comment by fpiemontese** [comment]
Oh I see! In that case, in order to perform inference each frame of a YouTube stream, I could simply have `detect.py` use `LoadImages` rather than `LoadStreams`?

**Comment by glenn-jocher** [comment]
@fpiemontese yeah that might be the simplest solution. Could you submit a PR to redirect YouTube inference to LoadImages? Thanks!

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by glenn-jocher** [comment]
@fpiemontese the alternative is stricter control of frame skipping in LoadStreams but this will always be complicated with realtime RTSP/RTMP/HTTPS streams that will invariably suffer drops, delays etc. where YouTube videos shouldn't.

**Comment by lavrenkov-sketch** [comment]
@Golds-l Can you show your code to work with multiple RTSP streams at the same time?

**Comment by xin6211** [comment]
> @Golds-l Can you show your code to work with multiple RTSP streams at the same time?
The code i used have nothing new.if you want avoid this problem,you can use queue or some else data structure to save and read frames.You can change the code in utils/dataset.py LoadStreams.update() and LoadStreams.__next__().

**Comment by fpiemontese** [comment]
@glenn-jocher should this behaviour be governed by an optional parameter `detect.py` or would you rather all YouTube streams be passed to `LoadImages`? I think keeping at least the option to perform RT inference (with a disclaimer that it could result in frame drops) could be helpful.

**Comment by glenn-jocher** [comment]
@fpiemontese current implementation leverages the StreamLoader, if you find a better alternative please submit a PR, thanks!
