### ISSUE TITLE
What is the label barplot for?

### ISSUE THREAD

**Issue by tserdar** [ultralytics/yolov5#3881]
What does this plot (`labels.jpg`) represent after training? 

Distribution of labels predicted? Distribution of labels used in the training set?

![image](https://user-images.githubusercontent.com/62431982/124398452-110cc280-dd16-11eb-8e7f-57835c777c4b.png)

**Comment by glenn-jocher** [comment]
@rocketsfallonrocketfalls labels.jpg displayed your training labels.

**Comment by tserdar** [comment]
Thanks a lot @glenn-jocher!
