### ISSUE TITLE
Detecting small objects in large images

### ISSUE THREAD

**Issue by mansi-aggarwal-2504** [ultralytics/yolov5#3884]
I have some images which are 6000 × 4000 pixels in size ( relatively large images) and the objects that have been labelled here are quite small. I trained the model and had to set the `--img-size` parameter to `1280` as anything higher than that was throwing `RuntimeError: CUDA out of memory error`.

When I ran `detect.py`, I received zero detections. Even at `0.1` `conf-thres`.

Any idea how I can detect very small objects in large images?

**Comment by tetelevm** [comment]
As far as I know, YOLO has a minimum object size in the image.  I would advise you to split the image into 9 images with an overlap of 100 -> (0-40%), (30-70%), (60-100%) in width and height and search for objects on them with a smaller network.

**Comment by mansi-aggarwal-2504** [comment]
I also had that idea but do you know of any way I could adjust the labels to cropped images. Since I have ground truth labels (xml and txt) for the full images.

**Comment by Melhaya** [comment]
I also did some cropping to images I am using for training. reverse the normalization of the labels and adjust the X-center and Y-Center according to the cropping you did and then Normalize them back again. It will take a couple of trials to get it correct but it works. Just make sure you visualize the new labels on your cropped images as a sanity check. :)

**Comment by glenn-jocher** [comment]
@tetelevm @mansi-aggarwal-2504 @Melhaya actually a simpler solution might be to train on native resolution crops and then to run inference at batch-size 1 with native resolution. You can do this using the new Albumentations integration in https://github.com/ultralytics/yolov5/pull/3882 and using i.e. `A.RandomCrop(width=1280, height=1280)`.

**Comment by mansi-aggarwal-2504** [comment]
Hi @glenn-jocher, thank you for this tip. 
Just wanted to clarify,  when you said "train on native resolution crops", you're still suggesting I crop the 6000x4000 images into smaller images (say 6 smaller images), and run inference on similar cropped images also?

**Comment by glenn-jocher** [comment]
@mansi-aggarwal-2504 I wouldn't crop anything. It's a large developmental expense to create that pipeline.

**Comment by mansi-aggarwal-2504** [comment]
@glenn-jocher right. So you're saying I can use the 6000x4000 images and train on them and run the inference at `batch-size` 1 with same resolution images. And benefit from the new Albumentations integration. 
Just making sure I understand you correctly.

**Comment by glenn-jocher** [comment]
@mansi-aggarwal-2504 yes you can train at full size with random crops, and then run inference at full size.

**Comment by mansi-aggarwal-2504** [comment]
Thank you for your help @glenn-jocher!

**Comment by fcakyon** [comment]
@mansi-aggarwal-2504 @Melhaya @tetelevm you can perform sliced inference with lower image sizes and lower gpu memory usage on a yolov5 model using SAHI package: https://github.com/obss/sahi
