### ISSUE TITLE
How to use --evolve

### ISSUE THREAD

**Issue by supoman-lei** [ultralytics/yolov5#3886]
Hi
   When I used the train.py --epochs 10 --weights yolov5s.pt --evolve (others use default parameters) command, there were some problems(just like below）. How can I use evolve to automatically adjust better hyperparameters?Can someone help me？Please！

## Additional context
Traceback (most recent call last):
  File "train.py", line 661, in <module>
    main(opt)
  File "train.py", line 635, in main
    hyp[k] = max(hyp[k], v[1])  # lower limit
KeyError: 'anchors'
![D344U@%QMH5%MN3YAEB0`ZL](https://user-images.githubusercontent.com/69951798/124451346-dfe4ce80-ddb7-11eb-8689-511843943480.png)

**Comment by Melhaya** [comment]
Simply out comment this from the evolve hyper parameters in train.py 
**# 'anchors': (2, 2.0, 10.0),  # anchors per output grid (0 to ignore)**
It should work after that.

> Hi
> When I used the train.py --epochs 10 --weights yolov5s.pt --evolve (others use default parameters) command, there were some problems(just like below）. How can I use evolve to automatically adjust better hyperparameters?Can someone help me？Please！
> ## Additional context
> 
> Traceback (most recent call last):
> File "train.py", line 661, in
> main(opt)
> File "train.py", line 635, in main
> hyp[k] = max(hyp[k], v[1]) # lower limit
> KeyError: 'anchors'
> ![D344U@%QMH5%MN3YAEB0`ZL](https://user-images.githubusercontent.com/69951798/124451346-dfe4ce80-ddb7-11eb-8689-511843943480.png)

**Comment by supoman-lei** [comment]
> Simply out comment this from the evolve hyper parameters in train.py
> **# 'anchors': (2, 2.0, 10.0), # anchors per output grid (0 to ignore)**
> It should work after that.
> 

Thank you for your reply! I have solved it!

**Comment by glenn-jocher** [comment]
@Zhugguanglei good news 😃! Your original issue may now be fixed ✅ in PR #3887. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
