### ISSUE TITLE
Training on multiple GPU on HPC servers

### ISSUE THREAD

**Issue by Mai-Sirhan** [ultralytics/yolov5#3897]
I am using a virtual  machine on Microsoft azure. i have a 18.04 Ubuntu and four **Tesla K80** GPU's.
I have run the model through this command `python -m torch.distributed.launch --nproc_per_node 4 train.py`. unfortunately i got these errors:

**********************************************************************
               CHILD PROCESS FAILED WITH NO ERROR_FILE
**********************************************************************
CHILD PROCESS FAILED WITH NO ERROR_FILE
Child process 6597 (local_rank 0) FAILED (exitcode 1)
Error msg: Process failed with exitcode 1
Without writing an error file to <N/A>.
While this DOES NOT affect the correctness of your application,
no trace information about the error will be available for inspection.
Consider decorating your top level entrypoint function with
torch.distributed.elastic.multiprocessing.errors.record. Example:

  from torch.distributed.elastic.multiprocessing.errors import record

  @record
  def trainer_main(args):
     # do train
**********************************************************************
  warnings.warn(_no_error_file_warning_msg(rank, failure))
Traceback (most recent call last):
  File "/anaconda/envs/yolov5/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda/envs/yolov5/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/anaconda/envs/yolov5/lib/python3.6/site-packages/torch/distributed/launch.py", line 173, in <module>
    main()
  File "/anaconda/envs/yolov5/lib/python3.6/site-packages/torch/distributed/launch.py", line 169, in main
    run(args)
  File "/anaconda/envs/yolov5/lib/python3.6/site-packages/torch/distributed/run.py", line 624, in run
    )(*cmd_args)
  File "/anaconda/envs/yolov5/lib/python3.6/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/anaconda/envs/yolov5/lib/python3.6/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "/anaconda/envs/yolov5/lib/python3.6/site-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
***************************************
            train.py FAILED
=======================================
Root Cause:
[0]:
  time: 2021-07-05_14:55:32
  rank: 0 (local_rank: 0)
  exitcode: 1 (pid: 6597)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
=======================================
Other Failures:
[1]:
  time: 2021-07-05_14:55:32
  rank: 1 (local_rank: 1)
  exitcode: 1 (pid: 6598)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
[2]:
  time: 2021-07-05_14:55:32
  rank: 2 (local_rank: 2)
  exitcode: 1 (pid: 6599)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
[3]:
  time: 2021-07-05_14:55:32
  rank: 3 (local_rank: 3)
  exitcode: 1 (pid: 6600)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
***************************************

I will be happy for helping?

**Comment by glenn-jocher** [comment]
@Mai-Sirhan I would not recommend any number of K80 GPUs if you can avoid them as they are as slow as you can get.

In any case if you are training DDP you should start with the **Multi-GPU Training** tutorial and always train in our Docker image.

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

**Comment by Mai-Sirhan** [comment]
Hi @glenn-jocher, 

I run the model like the instruction in your tutorial.  
I installed the environment as you described `pip install -r requirements.txt`. after that I ran the model using your command `python -m torch.distributed.launch --nproc_per_node 4 train.py`.

What could be the problem can be in my case?

Another question,

What kind of GPU's that you recommend?

**Comment by glenn-jocher** [comment]
@Mai-Sirhan as I said above run all DDP trainings in our Docker image.

**Comment by glenn-jocher** [comment]
@Mai-Sirhan if you are running cloud instances 1-2 T4s will probably serve you better than 4 K80s and save you money as well.

**Comment by Mai-Sirhan** [comment]
Hi @glenn-jocher 

I followed your advice and installed your docker. after that I want to run the docker on my local version of yolov5 not on the latest version on GitHub, how I can do that?

thank you

**Comment by Peter-weng** [comment]
@Mai-Sirhan 
hi! i meet some problme like your's . but i uesd --sync-bn first time.The program tell me runtime out,so that i close the sync-bn and it work now but may not prefect,seem like a  litter bug.
`Starting training for 100 epochs...

     Epoch   gpu_mem       box       obj       cls     total    labels  img_size
      0/99     15.4G         0   0.02394         0   0.02394         0      1536:   0%|                                                           | 1/546 [00:09<1:23:27,  9.19s/it]Reducer buckets have been rebuilt in this iteration.
      0/99     15.2G   0.02613  0.008889   0.01166   0.04668         0      1536: 100%|███████████████████████████████████████████████████████████| 546/546 [05:39<00:00,  1.61it/s]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|█████████████████████████████████████████████████████| 546/546 [00:55<00:00,  9.76it/s]
                 all       4364        824   0.000601      0.256   0.000263   4.49e-05
`

**Comment by abuelgasimsaadeldin** [comment]
Hi @glenn-jocher, I am trying to train on 2 GeForce RTX 2080 Ti GPUs using DDP training and I receive the same error above as @Mai-Sirhan. I have followed all the instructions from cloning of the repo and installation of the requirements, my question is will the DDP training only work on a Docker container or is this issue fixable? Thank you.

Edit: Using - torch 1.9.0+cu102 and torchvision 0.10.0+cu102

**Comment by glenn-jocher** [comment]
@abuelgasimsaadeldin 👋 hi, thanks for letting us know about this problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
