### ISSUE TITLE
Suggestion regarding depoyment on Raspberry Pi

### ISSUE THREAD

**Issue by rsd2007** [ultralytics/yolov5#3898]
## ❔Question
Hi, I am using yolov5 to perform real-time detection. I want to deploy the model on raspberry-pi 4. What should I choose
1. Use the custom weights and clone repository in raspberry pi?
2. Convert the pytorch weight into tflite model, then use it on pi?
3. Or can I use pytorch hub on raspberry-pi?<br>
Thanks.

**Comment by glenn-jocher** [comment]
@rajchem for now we don't have an official export tutorial for Raspberry Pi but this is one of the categories in our YOLOv5 EXPORT competition so there should be some good solutions soon!

<p align="center">
  <a href="https://github.com/ultralytics/yolov5/discussions/3213">
  <img width="850" src="https://github.com/ultralytics/yolov5/releases/download/v1.0/banner-export-competition.png"></a>
</p>

@batrlatom

**Comment by soumendukrg** [comment]
The default yolov5 models can be run in Raspberry Pi without any modification. However, reducing latency for real-time detection might need additional tweaks.

**Comment by rsd2007** [comment]
Hi @soumendukrg can you please share what additional tweaks might needed.
