### ISSUE TITLE
Where‘s the export.py?

### ISSUE THREAD

**Issue by UNeedCryDear** [ultralytics/yolov5#3900]
## ❔Question
Thank you for your hard work!
In models(https://github.com/ultralytics/yolov5/tree/master/models) ,where's the export.py?
There is another problem here. If I train whith --img 640 --rect, when I run export.py to export the model to ONNX,  how should I set the img_size?
`parser.add_argument('--img-size', nargs='+', type=int, default=[640, 640], help='image size')  # height, width`
Suppose I have two pictures, one is 160 * 640, the other is 320 * 640, set default=[640, 320], or default=[640, 160]?  Or others?

**Comment by glenn-jocher** [comment]
@UNeedCryDear 
https://github.com/ultralytics/yolov5/blob/master/export.py

You can export at any size you want.

**Comment by UNeedCryDear** [comment]
@glenn-jocher 
Sorry, I didn't describe it clearly.
If there are tow pic A and B, shape[h，w]
A:[1280,320]
B:[320,1280]
if I train with img_size 640 --rect,when it trains, A resize to [640 ,160 ]and B resize to [160,640]？ 
How to set the ONNX network input_size when I export  to ONNX?
It means if I set the input_size with [640,160],pic.A is easy to resize to [640,160]. But how about B? B.w=1280 to resize to 160 and B.h=320 to resize 320/8=40 ,then fill the othres higth_pixels (640-40=600) pixels with 0? Or rotate B 90 degrees to change it shape to [1280,320] and then resize to [640,160]?
![20210707163146](https://user-images.githubusercontent.com/52729998/124727190-126e0300-df41-11eb-89f2-c42117a7c19d.png)

**Comment by glenn-jocher** [comment]
@UNeedCryDear I don't understand your question entirely, but as I said you can export to any fixed image size you want during export:
```
python export.py --img ...
```

or you can also ONNX export using dynamic axes:
```
python export.py --img ... --dynamic
