### ISSUE TITLE
Trainbatch0.jpg does not show all labels

### ISSUE THREAD

**Issue by tomklaver1995** [ultralytics/yolov5#3903]
Hi All,
As I state in the title my train batch does not show the correct labels, while I am absolutely sure that the labels are correct. Has anyone the same problem?

**Comment by glenn-jocher** [comment]
@tomklaver1995 your labels are incorrect.

**Comment by tomklaver1995** [comment]
@glenn-jocher Thanks for your response, I really dove into that but I just can't see why. Some labels are plotted some are not. If I plot them by hand I see the correct labels. I have an example attached.

Not Working label:
0 0.49342 0.590731 0.7335526 0.034146
0 0.5135 0.62975 0.701480 0.0360975

Working label:
0 0.35649671052631576 0.5912195121951219 0.3149671052631579 0.027317073170731707
0 0.34662828947368424 0.6141463414634146 0.29523026315789475 0.024390243902439025
0 0.3490953947368421 0.6385365853658537 0.29851973684210525 0.03024390243902439

**Comment by tomklaver1995** [comment]
I narrowed it down to the following:
almost all labels are doing fine except a few. For the ones that are not correct, I found the following.

- The labels are correctly stored in the dataset after running "create_dataloader" within the script.
- They don't exist in the variable targets within the dataloader (that is why they don't visualize in the trainbatch image)
- For an example that does not work I have the following: 0 0.3972 0.6165 0.71875 0.03
- When I change this to 0 0.3972 0.6165 0.71875 **0.5**, it suddenly works? I have no idea how this is possible.

Has anyone some ideas about this?

**Comment by glenn-jocher** [comment]
@tomklaver1995 the only thing I can think of if boxes are not appearing for you is that they have been removed as not meeting box candidate constraints, which is a normal process during training. There are minimum width and height constraints on your instance labels here, i.e. they must be >2 pixels each in width and height.

https://github.com/ultralytics/yolov5/blob/33202b7f0bbfcc55860e8c0cafbf13f227e77a84/utils/augmentations.py#L267-L272

**Comment by tomklaver1995** [comment]
@glenn-jocher Thanks glenn! I will follow all steps to check where it is going wrong, if I am able to find it I will let you know.

**Comment by tomklaver1995** [comment]
@glenn-jocher Glenn Thanks!! A lot! It was indeed one of these constraints that did not pass. ar was not always below the ar_threshold. Why is there such a threshold? And is there any risk if I increase this threshold?

Thanks once again!

**Comment by glenn-jocher** [comment]
@tomklaver1995 aspect ratio limits are in place to reject very long and thin objects, i.e. perhaps a 100x100 box got cropped down to 5x100, which would be meaningless for purposes of training on the original object in the box, so this criteria is in place to reject these labels.

Of course this is domain specific, some domains may require high AR objects, in which case you should loosen or eliminate this restriction.
