### ISSUE TITLE
Corrupted images/duplicate labels

### ISSUE THREAD

**Issue by Chitti21** [ultralytics/yolov5#3908]
## Corrupted images/duplicate labels
 How to get rid of  this error? It happens only on one of my datasets?  On other datasets, I don't get this error. 

![corrupted images](https://user-images.githubusercontent.com/75448105/124621218-b7cc9c80-de97-11eb-965d-095fb528a266.JPG)

![corrupted images 2](https://user-images.githubusercontent.com/75448105/124621310-cadf6c80-de97-11eb-9572-b9dad86ee361.JPG)

**Comment by glenn-jocher** [comment]
@Chitti21 duplicate labels mean your labels.txt files have duplicate rows, i.e. you've labelled the same object more than once.

**Comment by Chitti21** [comment]
Thanks a lot. @glenn-jocher
