### ISSUE TITLE
Didn't get PR curve while training

### ISSUE THREAD

**Issue by TanyaChutani** [ultralytics/yolov5#3909]
## 🚀 Feature

 Didn't get PR curve while training

## Motivation

 Not able to check PR curve whilst training.

**Comment by glenn-jocher** [comment]
@TanyaChutani PR curves are generated on training completion and also by calling test.py directly:
```
python test.py --data data.yaml --weights path/to/best.pt
```

**Comment by TanyaChutani** [comment]
Thanks @glenn-jocher!!
