### ISSUE TITLE
Custom TTA in Inference Phase

### ISSUE THREAD

**Issue by BNTzHax** [ultralytics/yolov5#3911]
## ❔Question
I read about Test with TTA in the tutorials: "**_Append --augment to any existing test.py command to enable TTA, and increase the image size by about 30% for improved results. Note that inference with TTA enabled will typically take about 2-3X the time of normal inference as the images are being left-right flipped and processed at 3 different resolutions, with the outputs merged before NMS. Part of the speed decrease is simply due to larger image sizes (832 vs 640), while part is due to the actual TTA operations._**". Can I custom the TTA method, like change from processed at 3 different resolutions to 5 different resolutions, add up-down flipped, etc ? And how can I do that ?

**Comment by glenn-jocher** [comment]
@BNTzHax TTA code may be modified here:
https://github.com/ultralytics/yolov5/blob/33202b7f0bbfcc55860e8c0cafbf13f227e77a84/models/yolo.py#L126-L137

**Comment by BNTzHax** [comment]
Thank you @glenn-jocher . One more question: Does this "forward_augment" also apply for image augment in train phase ?

**Comment by glenn-jocher** [comment]
@BNTzHax no, this is only for use with `test.py --augment` or `detect.py --augment` or hub models with `results = model(img, augment=True)`

**Comment by BNTzHax** [comment]
Thank you @glenn-jocher
