### ISSUE TITLE
Evolve not working

### ISSUE THREAD

**Issue by Melhaya** [ultralytics/yolov5#3918]
Hey, First of all thank you for this amazing repo!

I pulled the new repository yesterday and wanted to use --evolve but its not working. I am getting this error:

Traceback (most recent call last):
  File "train.py", line 663, in <module>
    main(opt)
  File "train.py", line 633, in main
    hyp[k] = float(x[i + 7] * v[i])  # mutate
IndexError: index 34 is out of bounds for axis 0 with size 34

This is the command I am running:

python train.py --epochs 10 --data pothole.yaml --weights yolov5s.pt --cache --evolve

P.S. Before I pulled the new repo, the command was working. I am not sure why it is not working anymore. Would appreciate your help.

Thank you
Mohamed

**Comment by Melhaya** [comment]
Nevermind I fixed it :D 

Thanks again for this repository, :)

**Comment by glenn-jocher** [comment]
@Melhaya oh ok great. I was not able to reproduce just saw your updated message. Everything works correctly in my tests.

<img width="1566" alt="Screenshot 2021-07-07 at 12 07 38" src="https://user-images.githubusercontent.com/26833433/124741518-1176aa80-df1c-11eb-9af2-26b4330299d7.png">

**Comment by Melhaya** [comment]
@glenn-jocher  Yes thanks a lot. I realized I had the old evolve.txt in my directory. So thats why it was mismatching. when I deleted it, everything worked fine :)

**Comment by Melhaya** [comment]
@glenn-jocher I do have a question about the warning of the autoanchor of small objects.
autoanchor: WARNING: Extremely small objects found. 1690 of 9340 labels are < 3 pixels in size.

I tried to find these objects in my dataset by having a threshold of 75 pxels which is the 3 pixels converted to my original image size. But I couldn't find these small labels. In fact, There was only one label below the 75 pixel threshold. 

I was wondering if you can explain how its getting those 1690 labels. :)

**Comment by glenn-jocher** [comment]
@Melhaya it's pretty simple. Given your data and your training settings 1700 of your labels are less than 3 pixels in width or height, which is not recommended if you expect good results. See autoanchor code for details.

https://github.com/ultralytics/yolov5/blob/33202b7f0bbfcc55860e8c0cafbf13f227e77a84/utils/autoanchor.py#L116-L119

**Comment by Melhaya** [comment]
@glenn-jocher Ah so its not 3 pixels in Area (w*h)?  Its 3 pixels in width or height alone. 
Am I understanding correctly?

**Comment by glenn-jocher** [comment]
@Melhaya yes

**Comment by Melhaya** [comment]
@glenn-jocher That makes more sense now. I tried it out on my dataset and the ~1700 labels match now. Thanks for the clarification
