### ISSUE TITLE
Random color and contrast changes

### ISSUE THREAD

**Issue by tetelevm** [ultralytics/yolov5#3919]
I have images, and I'm training my network on them. I have pretty similar images for recognition, but also not very diverse images for training. In general my solution works, but there is a pretty strong dependence on lighting and shadows. 

In the answer to your other question, you mentioned `Albumentations`, as I understand it, it does just that by randomly changing the color(/contrast/gamma/lighting/...). Is this true and will this integration help me, as well as how to enable it?

**Comment by glenn-jocher** [comment]
@tetelevm YOLOv5 already applies HSV colorspace augmentations to your images based on your hyperparameter in data/hyps/hyp.scratch.yaml, and you can overlay any Albumentations augmentations you want also. To get started with Albumentations see https://github.com/ultralytics/yolov5/pull/3882

**Comment by tetelevm** [comment]
@glenn-jocher 
I saw the parameters `hsv_h`, `hsv_s`, `hsv_v` in the hyperparameters. Can you please tell me which way to change them, so that lighting changes have less effect on recognition (not the exact numbers, but more/less)?

I also saw the `iou_t` parameter, and thought that increasing it would improve learning. I changed it from `0.2` to `0.4`, and that broke the learning. Don't you have a link to an explanation of what this parameter does and how and why to change it?

**Comment by tetelevm** [comment]
Okay, I just scrubbed my data a lot and then multiplied it by hand almost twice, changing the quality, colors, contrast a lot and drawing or painting over parts of the objects, and it gave very good results and speed gains. But the question of hyperparameters remained open for me.
