### ISSUE TITLE
Convert from yolov5 to Tflite

### ISSUE THREAD

**Issue by TehKonnos** [ultralytics/yolov5#3928]
## ❔Question
How can I change the shape of input from [batch,rgb,width,height] to [batch,width,height,rgb]
I tried to change the line 53 and 101 but in the final export of tflite the imput shape has the wrong order. 

## Additional context
The conversion from onnx to tflite is here: https://colab.research.google.com/drive/1tCtXEJ-E6_CoveneunwGXbgy62M_dwKb?usp=sharing
But I think my problem starts in the early stages of conversion.
Thank you for your time

**Comment by PraveenGit3** [comment]
Did u succeed in conversion to tf lite ?

**Comment by TehKonnos** [comment]
No. As I understand there are 4 options to use your pt model.
1.  Run #959 solution and check the custom android application he recommends.
2.  Add Metadata to your file, converted from ONNX to Saved_Model to TFLITE and use android studio's ML Binding method
3. Run your .pt file on android using pytorch's method as shown here: https://github.com/pytorch/android-demo-app/tree/master/ObjectDetection
4.  Train your model again with Transfer Learning from MobileNet SSD so the outputs fit Tensorflow's application.

**Comment by PraveenGit3** [comment]
I'm planning to run these yolov5  .pt on raspberry pi 4. If I convert to onxx to tf lite does it work ?

**Comment by TehKonnos** [comment]
I dont think you need any conversion. Just use detect.py there.

**Comment by zldrobit** [comment]
You could also refer to https://github.com/ultralytics/yolov5/pull/1127 and use https://github.com/zldrobit/yolov5 for TFLite model export.
