### ISSUE TITLE
what is the mean about img-size?

### ISSUE THREAD

**Issue by futureflsl** [ultralytics/yolov5#393]
sorry,i am new here,how to set Model save interval

**Comment by glenn-jocher** [comment]
@futureflsl --image size are the train and test sizes. They are default 640 both:
`python train.py --img 640 640`

best.pt and last.pt are saved every epoch.

**Comment by Byronnar** [comment]
> @futureflsl --image size are the train and test sizes. They are default 640 both:
> `python train.py --img 640 640`
> 
> best.pt and last.pt are saved every epoch.

Thank you, Can I run python train.py --img 832 832 ?  What is the limits of the img-size?

**Comment by glenn-jocher** [comment]
@Byronnar what you do is up to you.
