### ISSUE TITLE
Is Yolov5 Tensorflow based model available?

### ISSUE THREAD

**Issue by gouravsinghbais** [ultralytics/yolov5#3931]
## ❔Question
Is there any implementation available for YoloV5 using Tensorflow ?

## Additional context
While using YoloV5 with Pytorch CPU consumption goes 100% so other services do not respond and there remains no scope for multitasking, while with Tensorflow this would not be the problem. So I was wondering if there is any Tensoflow based YoloV5 model available or not.

**Comment by glenn-jocher** [comment]
@gouravsinghbais for YOLOv5 TensorFlow and Keras models see this awesome PR: https://github.com/ultralytics/yolov5/pull/1127
