### ISSUE TITLE
How to use only Hflip TTA

### ISSUE THREAD

**Issue by benihime91** [ultralytics/yolov5#3932]
## ❔Question
Hi @glenn-jocher thanks for this amazing work ... I want to only use `hflip` for TTA . If i am not wrong the default TTA uses different `scales`  ,`hflip`, `vflip` so could you point me where should I modify the code base to done TTA only with `hflip`.

**Comment by glenn-jocher** [comment]
@benihime91 TTA code is here, you can modify the augmentations as you see fit:
https://github.com/ultralytics/yolov5/blob/8c6f9e15bfc0000d18b976a95b9d7c17d407ec91/models/yolo.py#L125-L136

**Comment by benihime91** [comment]
Correct me if i am wrong:
```python
    def forward_augment(self, x):
        img_size = x.shape[-2:]  # height, width
        s = [1, 1]  # scales
        f = [None, 3]  # flips (2-ud, 3-lr)
        y = []  # outputs
        for si, fi in zip(s, f):
            xi = scale_img(x.flip(fi) if fi else x, si, gs=int(self.stride.max()))
            yi = self.forward_once(xi)[0]  # forward
            # cv2.imwrite(f'img_{si}.jpg', 255 * xi[0].cpu().numpy().transpose((1, 2, 0))[:, :, ::-1])  # save
            yi = self._descale_pred(yi, fi, si, img_size)
            y.append(yi)
        return torch.cat(y, 1), None  # augmented inference, train
```

But if I make the above changes will it work ?

**Comment by glenn-jocher** [comment]
@benihime91 modifications to the codebase are up to you, we can't provide assistance here.

**Comment by benihime91** [comment]
@glenn-jocher Thanks for the assistance
