### ISSUE TITLE
ONNX model has been generated with INT64 weights

### ISSUE THREAD

**Issue by OrcunCanDeniz** [ultralytics/yolov5#3935]
I generated an ONNX model with export.py but I get `Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.` warning during TRT engine creation. Is there a way to generate ONNX with INT32 or FLOAT32 precision?

**Comment by glenn-jocher** [comment]
@OrcunCanDeniz see **TensorRT Deployment** tutorial:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by OrcunCanDeniz** [comment]
I've already checked that repo. But my issue seems like it is related to the export of the onnx and not related to conversion of onnx to trt. It passes trtexec test but i just wondered if there is a way to export as FP32, INT32 or something else.

**Comment by mnuriyumusak** [comment]
> I've already checked that repo. But my issue seems like it is related to the export of the onnx and not related to conversion of onnx to trt. It passes trtexec test but i just wondered if there is a way to export as FP32, INT32 or something else.

did you find any solution to this problem orçun?

**Comment by OrcunCanDeniz** [comment]
No. But according to my experience with other models' conversion, this should not be a major problem.

**Comment by RapidEdgeAI** [comment]
I had the same warning when converting the Yolov5s model from ONNX to trt engine. However, the model works as expected.

**Comment by glenn-jocher** [comment]
@RapidEdgeAI thank you for bringing this to our attention. We appreciate your feedback and believe that this warning message should not affect the performance of the model. It's good to know that the model is still working as expected. If you have any other questions or concerns, feel free to ask.
