### ISSUE TITLE
yolov5+repulsion loss

### ISSUE THREAD

**Issue by SISTMrL** [ultralytics/yolov5#394]
## ❔Question
when I detect my dataset using yolov5, there's a lot of overlap between the objects that need to be detected， so I try to use the repulsion loss to solve overlap.But when I add repulsion loss to yolov5's loss, the training speed is very slow.

**Comment by zheng-yuwei** [comment]
> ## ❔Question
> when I detect my dataset using yolov5, there's a lot of overlap between the objects that need to be detected， so I try to use the repulsion loss to solve overlap.But when I add repulsion loss to yolov5's loss, the training speed is very slow.
> 
> ## Additional context

hi, how do add repulsion loss to yolov5 loss ? can you show the code for reference ~ many thanks!
