### ISSUE TITLE
What is the output in detect.py, boxes or (x1,y1,x2,y2)? 

### ISSUE THREAD

**Issue by estefica** [ultralytics/yolov5#3941]
## Hello, I'm working with detect.py and I would like to know what structure does the output in "pred = model(img, augment=opt.augment)[0]" have?  (cx,cy,w,h,....) or (x1,y1,x2,y2..)? thank you.

**Comment by Zigars** [comment]
They are the prediction target location information, xywh means the pred boxs's center coordinate and weight/height, xyxy means  the pred boxs's left-top and right-bottom coordinate, these information are the yolov5 neural networks output, maybe you should learning more basic knowledge in neural network.
