### ISSUE TITLE
For online cutting training and detection can be improve

### ISSUE THREAD

**Issue by Zigars** [ultralytics/yolov5#3942]
## 🚀 Feature

For big image training, usually people thinking about to cut the images, but yolov5 can only resize the image to small size. Such as VisDrone dataset, the smallest image can have 960*540 size, if resize to 640*640, size would be 640*360, but the target in dataset mostly are small object, resize the image make the target become more smaller, but if use bigger resolution, the cuda memory would exceed.

So I thought online cutting training and detection would be a good feature for yolov5 to improve, although cutting image would also increase the train time, but it would be a great idea for people who don't have large computing power GPU, also I think cutting image would be effective for small object detection. Although it's not a new idea in detection, it would be a useful way for people to their own detector.

**Comment by glenn-jocher** [comment]
@Zigars you can use the new Albumentations integration with RandomCrop to train on full resolution crops, i.e.:

```
python train.py --img 960
# with
A.RandomCrop(height=640, width=640, p=1.0)
```
https://github.com/ultralytics/yolov5/blob/647223a7a8e5d8fca69481d477fe9a2930a8004c/utils/augmentations.py#L22-L26

**Comment by Camilochiang** [comment]
My apologies if I misunderstood and please correct me if I'm wrong.
1. With this alternative you are actually training on the cropped resolution, no? So even if your pass the parameter,  _i.e_ 960, you will actually train YOLOv5 at 640 px  (for your example, as the mosaic dataloader  will merge 4 pics of 960 px, then crop the middle and then apply the albumentation on the image as [mention here).](https://github.com/ultralytics/yolov5/issues/46#issuecomment-643437300) This of course may help with the memory issue and finding small objects. Additionally one could later use a slicer along the pictures to the cropped resolution ( 640 px in our example)  to get the best inference results ( I would love to try but I'm running another experiment for the last couple of days. This will be my next exercise)
4. Then of course you are not fully using your data, as only one part of the image will be used. This should not be a problem in a dataset big enought, but still, will you recommend increasing the epochs?
