### ISSUE TITLE
GPU Speed (ms/img)

### ISSUE THREAD

**Issue by Ronald-Kray** [ultralytics/yolov5#3950]
## ❔Question
![image](https://user-images.githubusercontent.com/76469976/125137226-2dd53b80-e104-11eb-98ad-9ef08da5fbd3.png)
**1.How can I check GPU Speed (ms/img)?**

![image](https://user-images.githubusercontent.com/76469976/125138299-51998100-e106-11eb-9859-abee68419001.png)
**2.Could you tell me about the relationships between FLOPs and parameters?**

**Comment by glenn-jocher** [comment]
@Ronald-Kray 

1. Commands to reproduce the chart and table values are in the chart and table comments.
2. FLOPs and Parameters are not related, which is why they are listed separately.

**Comment by Ronald-Kray** [comment]
@glenn-jocher 
Thanks for the answer!
I'm doing a performance comparison of EfficientDet and Yolov5.
I could train Yolov5 all s, m, l, and x, but EfficientDet could not be trained all of them(Only D0, D1, D2) because of out-of-memory.
**My question is the Model's FLOPs(s:17, m:51.3, l:115.4, x:218.8)  is related to training or inference speed?**
The reason why I'm curious about it I'm drawing graphs on mAP vs FLOPS(EfficientDet vs Yolov5) on my custom dataset.



Could you give me a comment for me, please?

**Comment by glenn-jocher** [comment]
FLOPs is a function of model and input  image size and has nothing to do with the purpose of the forward pass.
