### ISSUE TITLE
Background images

### ISSUE THREAD

**Issue by iceisfun** [ultralytics/yolov5#3951]
## ❔Question

I have some datasets that work great except we have to add a class for "not things we are looking for" and label things that are in the background

can we just put background images without labels in or something similar or do we need to add labels?

**Comment by glenn-jocher** [comment]
@iceisfun no labels are required for background images, you just add images to your dataset. See https://docs.ultralytics.com/guides/model-training-tips/

**Comment by iceisfun** [comment]
Its not clear if they should be in train, val both or split

I end up with something like this now having 346 background images

train: 16654 found, 0 missing, 346 empty, 0 corrupted
val: 2882 found, 0 missing, 0 empty, 0 corrupted

I have an empty imagename.txt and all the imagename in train.txt -- training seems to be running fine,  does this seem correct?

**Comment by glenn-jocher** [comment]
@iceisfun sure. You can place any images in any split you want.
