### ISSUE TITLE
Is the Bottleneck class named accordingly? 

### ISSUE THREAD

**Issue by tserdar** [ultralytics/yolov5#3955]
Hello @glenn-jocher, 

I am sorry if there is smth obvious that I should be able to see by myself, but I just couldn't. I am writing my thesis, and I did a lot of work based on YOLOv5. So I am drawing the architecture of YOLOv5 (v4.0) and explaining how it works. 

In the architecture of YOLOv5 I've seen that this "Bottleneck" class has been used repeatedly but its expansion parameter `e` is always kept at `e=0.5`.

https://github.com/ultralytics/yolov5/blob/443af8b25ae5121e920623511e38465bacde75b8/models/common.py#L84-L94

At this point, isn't it more of a `residual` block instead of being a `bottleneck`? Isn't it a `bottleneck` when `e>0`?  What would be the correct way to refer to this structure in an academic environment? 
 
 
 I'd love your insight here. 
 
 The answer I expect is a one-liner -> e.g. "its definitely a `bottleneck`" or "you can call it bothways" etc. 
 
 Thanks!

**Comment by glenn-jocher** [comment]
@rocketsfallonrocketfalls residual just means some of your information is skipping layers (i.e. the shortcut flag), bottleneck typically just means your channel count is expanding or contracting, i.e. 64 > 32 > 64

**Comment by tserdar** [comment]
@glenn-jocher thank you very much for the precise answer! I wasn't aware of contracting would also be referred as a bottleneck as I couldn't find an example for that.
