### ISSUE TITLE
How onnx exported from yolov5x worked in ml.net?

### ISSUE THREAD

**Issue by alatriste-lee** [ultralytics/yolov5#396]
Is there any sample?

**Comment by HamidEbr** [comment]
This is my issue too if anyone can help.

**Comment by alatriste-lee** [comment]
hi everybody, I find this repo today and share it to you.

[将YOLO V5模型部署到wpf应用程序中 deploy yolov5 model to wpf app ](https://blog.csdn.net/apple_54477025/article/details/114003220?ops_request_misc=&request_id=&biz_id=102&utm_term=yolov5%20c#&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduweb~default-3-114003220.first_rank_v2_pc_rank_v29)



链接：https://pan.baidu.com/s/1vzSDpixWb0e0VHp5SS0okA
提取码：wfzo
