### ISSUE TITLE
How to change the width of the boundary boxes so it does not cover important parts of the image in case of multiple objects? 

### ISSUE THREAD

**Issue by andreasN78** [ultralytics/yolov5#3960]

**Comment by shershunov** [comment]
`python detect.py --line-thickness 1`

**Comment by andreasN78** [comment]
Sorry there is no argument in detect.py of name line thickness

**Comment by andreasN78** [comment]
> `python detect.py --line-thickness 1`

Sorry there is no argument in detect.py of name line thickness

**Comment by glenn-jocher** [comment]
@andreasN78 your code is out of date. To update YOLOv5:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>
