### ISSUE TITLE
How can i generate a alarm single in detect.py so when ever my target object is in the camera's range an alarm is generated?

### ISSUE THREAD

**Issue by raja-usama** [ultralytics/yolov5#3963]

**Comment by EkelviNistars** [comment]
`python detect.py --line-thickness 1`

**Comment by EkelviNistars** [comment]
Hi
You need to use PytorchHub to detect objects.
And play the sound effect when an object is detected using the winsound library.

```py
from cv2 import waitKey, destroyAllWindows, imshow, VideoCapture, rectangle
from torch import hub
from winsound import MessageBeep, MB_OK

model = hub.load('ultralytics/yolov5', 'yolov5s')
cap = VideoCapture(0)
while True:
    ret, img = cap.read()
    result = model(img, size=640)
    repos = result.xyxy[0]
    for i in range(len(repos)):
        pos = repos[i].detach()
        rectangle(img, (int(pos[0]), int(pos[1])), (int(pos[2]), int(pos[3])), (255, 255, 255), 2)
    if len(repos) > 0:
        MessageBeep(type=MB_OK)
    imshow('Detect', img)
    if waitKey(1) & 0xFF == ord("q"):
        destroyAllWindows()
        break
```

**Comment by 1Yleng** [comment]
>  How about this one, please? .py?

**Comment by glenn-jocher** [comment]
👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # yolov5n - yolov5x6 official model
#                                            'custom', 'path/to/best.pt')  # custom model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
results.xyxy[0]  # im predictions (tensor)

results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie

results.pandas().xyxy[0].value_counts('name')  # class counts (pandas)
# person    2
# tie       1
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by 1Yleng** [comment]
> ## ❔Question
> ## Additional context

Please, How did you solve it later?

**Comment by glenn-jocher** [comment]
@1Yleng i see that you've made an attempt to generate an alarm when a target object is detected in the camera's range using YOLOv5 and the winsound library. This can be achieved by making use of the results obtained from your object detection model. By checking the detected objects and triggering an alarm using winsound, you can create a successful object detection alarm system.

The code provided shows the process of capturing a video stream, running inference on each frame using the YOLOv5 model, and then displaying the results with detected objects outlined. When a detection occurs, an alarm sound is played. This is a good initial approach!

Feel free to keep iterating on this procedure and leverage the YOLOv5 results to further enhance your object detection alarm system. If you have any more specific questions or encounter any challenges, please let me know, and I'd be happy to assist further!
