### ISSUE TITLE
save specific objects

### ISSUE THREAD

**Issue by MehdiiHs** [ultralytics/yolov5#3964]
## ❔Question
Is there any way that I can find and crop objects that contain another object?

**Comment by shershunov** [comment]
`python detect.py --save-crop`

**Comment by MehdiiHs** [comment]
> `python detect.py --save-crop`

it saves all the detected objects. I want to save an object just if it contains another object. for example if a person wears a hat. not all the persons in the image.

**Comment by glenn-jocher** [comment]
@MehdiiHs you can customize the `--save-crop` logic here:

https://github.com/ultralytics/yolov5/blob/80299a57e26accf196558da01c071e13caec14ae/detect.py#L138-L152
