### ISSUE TITLE
How to Save Cropped Detections After Every Few Frames?

### ISSUE THREAD

**Issue by abuelgasimsaadeldin** [ultralytics/yolov5#3965]
## ❔Question
Hi everyone, I am running the ```detect.py``` on a video file and am saving the cropped detections by using the ```--save-crop``` argument and everything works perfectly, I am trying to know however if there is a way to save the cropped detections after every **few frames** (For example after every 30 frames, save cropped results) instead of after every frame. I would highly appreciate any help in solving this. Thanks!

**Comment by glenn-jocher** [comment]
@abuelgasimsaadeldin you can modify the --save-crop logic here:
https://github.com/ultralytics/yolov5/blob/80299a57e26accf196558da01c071e13caec14ae/detect.py#L150-L152
