### ISSUE TITLE
Yolov5 API  in Flask

### ISSUE THREAD

**Issue by PraveenGit3** [ultralytics/yolov5#3968]
## ❔Question
I would like to deploy my model  ie YOLOV5 to web server using flask  -API ,when users enter image it should return  prediction in form of table like for 10 bounding boxes on predicted  images it should generate 10 records in terms of table ?

Any reference of yolov5 deployment in flask 

![dcu](https://user-images.githubusercontent.com/26325343/125200519-7bb48580-e263-11eb-8615-0a40f98a7249.jpeg)

## Additional context
Following image is my trained model predicted image

**Comment by glenn-jocher** [comment]
@PraveenGit3 see https://github.com/ultralytics/yolov5/tree/master/utils/flask_rest_api

**Comment by PraveenGit3** [comment]
Yeah @glenn-jocher  I have used same repo but unable to run it succesfully.....I followed "readme" too ! When running "RESTAPI.PY" It say model not found but model is defined in "restapi.py"
<img width="841" alt="Screenshot 2021-07-16 at 13 01 21" src="https://user-images.githubusercontent.com/26325343/125944524-5eda577c-4c28-4d83-a58d-200e5626796c.png">

**Comment by glenn-jocher** [comment]
@PraveenGit3 we also have our own Ultralytics YOLOv5 API here :)

https://ultralytics.com/yolov5
![image](https://user-images.githubusercontent.com/26833433/125949120-21501441-f2bb-4d9e-9cdd-e8971c29d979.png)

**Comment by PraveenGit3** [comment]
@glenn-jocher  yeah Your official repo is working fine  it return detection when image is passed through curl on local flask server . 

I want to check out web interface like yours .....Hope you add custom  web interface API  for custom weights   which take image and returns prediction on image itself and text table in html
