### ISSUE TITLE
Question Regarding Argument Parser in detect.py

### ISSUE THREAD

**Issue by joneswilliam1** [ultralytics/yolov5#3969]
## ❔Question
Hi, sorry if I am asking a really simple question but I am having a really hard time with this, I want to run my ```detect.py``` and show my results but I do not want to always add the ```view-img``` argument and so I changed this line of code to 'True':
        view_img=False,  # show results

And have also add ```default=True``` in the view-image argument as follows:
    parser.add_argument('--view-img', action='store_true', default=True, help='show results')

But when I run ```python3 detect.py``` I still don't see my results only after adding ```--view-img``` do I see it. Any help please thank you.

**Comment by shershunov** [comment]
Remove line 157.

**Comment by joneswilliam1** [comment]
@EkelviNistars Thank you so much the reply, the ```view-img``` was just an example and I would like to set True a few other arguments as well such as ```save-crop``` and ```nosave```, so I would have to delete if statements and there no other easier way?

**Comment by joneswilliam1** [comment]
@EkelviNistars Sorry my bad, I just noticed that I was running the original ```detect.py``` script and not my modified one (face palm). Setting default=True works. Closing the Issue.
