### ISSUE TITLE
Question Regarding detect.py output

### ISSUE THREAD

**Issue by joneswilliam1** [ultralytics/yolov5#3971]
## ❔Question
Hi everyone, when running inference of images and videos using detect.py the output printed out during inference is something similar to as follows:
![1](https://user-images.githubusercontent.com/83490495/125203666-f73a2500-e2ab-11eb-928c-21a444ca2b04.PNG)

I have been searching and have _commented_ out all of the print statements found in the ```detect.py``` but there is still this output that is getting printed out. I would really like to know where exactly in the code this is getting printed out and get rid of it if possible and not display anything in the terminal when running inference. Thank you.

**Comment by wudashuo** [comment]
There is a bug on Windows if you use CUDA11, there is no output when detecting images or videos.
Downgrade your CUDA to 10.2, reinstall torch1.8+cu102, and the problem should be solved.
Or you can simply use Linux or macOS, there is no environmental problem on both of them.

**Comment by joneswilliam1** [comment]
Hi @wudashuo I am using Windows OS with CUDA 10.2 and I do receive an output when detecting images or videos, however, I am trying to find out where these outputs are getting printed out and get rid of them if possible and not display anything on the terminal.

**Comment by joneswilliam1** [comment]
@glenn-jocher I realize that the line below prints out everything after the colon i.e. "256x416 Done. (0.016s)" https://github.com/ultralytics/yolov5/blob/647223a7a8e5d8fca69481d477fe9a2930a8004c/detect.py#L154

May I know where in the code the string before the ':' as shown below is getting printed out? Much thanks.

```video 1/1 (1/580) C:\Users\chiaw\cargate\yolov5-compressed\data\videos\carplate2.mp4:```

**Comment by wudashuo** [comment]
Ah, sorry, I didn't read your description carefully, I thought you got no detection output when running `detect.py`.
The outputs are separated,  the first part should be in `models/common.py`, and the second part is in `detect.py` as you mentioned above.

**Comment by joneswilliam1** [comment]
@wudashuo I see, I'm sorry may know where exactly it is located in [common.py](https://github.com/ultralytics/yolov5/blob/master/models/common.py)? I can't seem to find it.

**Comment by wudashuo** [comment]
https://github.com/ultralytics/yolov5/blob/647223a7a8e5d8fca69481d477fe9a2930a8004c/models/common.py#L309
https://github.com/ultralytics/yolov5/blob/647223a7a8e5d8fca69481d477fe9a2930a8004c/models/common.py#L313

**Comment by joneswilliam1** [comment]
@wudashuo Hm I have tried commenting those out already and the output still appears, any idea? But thanks anyways.

**Comment by wudashuo** [comment]
Sorry, I gave the wrong answer. The first part of the output is in `datasets.py`
https://github.com/ultralytics/yolov5/blob/647223a7a8e5d8fca69481d477fe9a2930a8004c/utils/datasets.py#L208
https://github.com/ultralytics/yolov5/blob/647223a7a8e5d8fca69481d477fe9a2930a8004c/utils/datasets.py#L215
![20210712153309](https://user-images.githubusercontent.com/5948604/125248361-8b48d280-e326-11eb-9530-7ba1857f3748.png)

**Comment by joneswilliam1** [comment]
@wudashuo Thank you so much! it works! closing the issue.
