### ISSUE TITLE
Multi GPU's training Error

### ISSUE THREAD

**Issue by Mai-Sirhan** [ultralytics/yolov5#3974]
Hi,

I am trying to train a yolov5 network in multiple GPU environment. I followed your installation instructions in [https://github.com/ultralytics/yolov5/wiki/Docker-Quickstart](https://github.com/ultralytics/yolov5/wiki/Docker-Quickstart), and I got this error:

=============
== PyTorch ==
=============

NVIDIA Release 21.05 (build 22595835)
PyTorch Version 1.9.0a0+2ecb2c7

Container image Copyright (c) 2021, NVIDIA CORPORATION.  All rights reserved.

Copyright (c) 2014-2021 Facebook Inc.
Copyright (c) 2011-2014 Idiap Research Institute (Ronan Collobert)
Copyright (c) 2012-2014 Deepmind Technologies    (Koray Kavukcuoglu)
Copyright (c) 2011-2012 NEC Laboratories America (Koray Kavukcuoglu)
Copyright (c) 2011-2013 NYU                      (Clement Farabet)
Copyright (c) 2006-2010 NEC Laboratories America (Ronan Collobert, Leon Bottou, Iain Melvin, Jason Weston)
Copyright (c) 2006      Idiap Research Institute (Samy Bengio)
Copyright (c) 2001-2004 Idiap Research Institute (Ronan Collobert, Samy Bengio, Johnny Mariethoz)
Copyright (c) 2015      Google Inc.
Copyright (c) 2015      Yangqing Jia
Copyright (c) 2013-2016 The Caffe contributors
All rights reserved.

NVIDIA Deep Learning Profiler (dlprof) Copyright (c) 2021, NVIDIA CORPORATION.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

NOTE: MOFED driver for multi-node communication was not detected.
      Multi-node communication performance may be reduced.

*I am running on a HPC server with 64 bit AMD CPU with four Tesla-T4 GPU's. 
 Nvidia Driver Version: 470.42.01
  CUDA Version: 11.4

**Comment by glenn-jocher** [comment]
@Mai-Sirhan you haven't shown any error.
