### ISSUE TITLE
How to use my own model in Flask-API？

### ISSUE THREAD

**Issue by cj-wade** [ultralytics/yolov5#3979]
## ❔Question
How to use my own model in Flask-API？

## Additional context
![image](https://user-images.githubusercontent.com/33895584/125295299-abdd5080-e357-11eb-94b7-22e0dfee2adc.png)

I want to use my own trained model and get json results. 
[
  {
    "class": 0,
    "confidence": xxx,
    "height": xxx,
    "name": "xxx",
    "width": xxx,
    "xcenter": xxx,
    "ycenter": xxx
  },
.....
]
How can I replace this sentence: "model = torch.hub.load("ultralytics/yolov5", "yolov5s", force_reload=False)"?

**Comment by glenn-jocher** [comment]
@cj-wade see YOLOv5 **PyTorch Hub** tutorial:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by cj-wade** [comment]
> @cj-wade see YOLOv5 **PyTorch Hub** tutorial:
> 
> ## YOLOv5 Tutorials
> * [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)  🚀 RECOMMENDED
> * [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)  ☘️ RECOMMENDED
> * [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)  🌟 NEW
> * [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)  🌟 NEW
> * [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
> * [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)  ⭐ NEW
> * [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
> * [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
> * [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
> * [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
> * [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
> * [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)  ⭐ NEW
> * [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

thanks！I find a solution in these tutorials

**Comment by xkx9431** [comment]
hi @cj-wade ,
same issues, and I just find this section
![image](https://user-images.githubusercontent.com/44063249/125306735-07144080-e362-11eb-9e7d-969f3b7d0b4b.png)
 but I cannot open this  VOC link  `
custom 20-class **VOC**-trained YOLOv5s 
`
can you open this ? or where I can download the  *.bt directly ?

@glenn-jocher FYI 
Thanks & Regards,
Kevin

**Comment by cj-wade** [comment]
> hi @cj-wade ,
> same issues, and I just find this section
> ![image](https://user-images.githubusercontent.com/44063249/125306735-07144080-e362-11eb-9e7d-969f3b7d0b4b.png)
> but I cannot open this VOC link `custom 20-class **VOC**-trained YOLOv5s `
> can you open this ? or where I can download the *.bt directly ?
> 
> @glenn-jocher FYI
> Thanks & Regards,
> Kevin

yep，it is the solution I found.
but I don't understand what u say. ".bt"? ".pt"?
If u want to ues your own model, you just keep the "custom", and replace the ''path/to/yolov5" & "path=path/to/best.pt" with your own path

**Comment by xkx9431** [comment]
@cj-wade  yes , thanks for your reply, I got it.
