### ISSUE TITLE
 add ghostbottleneck module into yolov5s.yaml

### ISSUE THREAD

**Issue by polarbearwy** [ultralytics/yolov5#398]
## ❔Question
when i add ghostbottleneck module into yolov5s stucture, issue shows.

## Additional context
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 34 and 62 in dimension 2 at /pytorch/aten/src/TH/genric/THTensor.cpp:612

**Comment by glenn-jocher** [comment]
@polarbearwy you need to add custom modules you want to use to yolo.py to let it know to expect them. You can do that here:
https://github.com/ultralytics/yolov5/blob/1e94bcf3d27d9e176e419cc82751afd47250bef5/models/yolo.py#L175-L198

**Comment by polarbearwy** [comment]
I have already add custom modules  to yolo.py, but there are still problems

**Comment by mary-0830** [comment]
I have same question.

**Comment by orangezishuai** [comment]
> I have already add custom modules to yolo.py, but there are still problems

hello，are you slove this issue？thanks！

**Comment by glenn-jocher** [comment]
@polarbearwy @python-faker there was a recent PR https://github.com/ultralytics/yolov5/pull/1176 for a bug fix in GhostConv() modules. Please git pull and try again, and if the error repeats please submit a full Bug Report with code to reproduce. Thank you.

**Comment by orangezishuai** [comment]
> @polarbearwy @python-faker there was a recent PR #1176 for a bug fix in GhostConv() modules. Please git pull and try again, and if the error repeats please submit a full Bug Report with code to reproduce. Thank you.

thank you very much，I solved the problem through your method.
The reason for the problem is the lack of input parameters. My comparison is as follows

before
`class GhostConv(nn.Module):
    # Ghost Convolution https://github.com/huawei-noah/ghostnet
    def __init__(self, c1, c2, k=1, s=1, g=1, act=True):  # ch_in, ch_out, kernel, stride, groups
        super(GhostConv, self).__init__()
        c_ = c2 // 2  # hidden channels
        # self.cv1 = Conv(c1, c_, k, s, g, act)
        # self.cv2 = Conv(c_, c_, 5, 1, c_, act)`
after
`class GhostConv(nn.Module):
    # Ghost Convolution https://github.com/huawei-noah/ghostnet
    def __init__(self, c1, c2, k=1, s=1, g=1, act=True):  # ch_in, ch_out, kernel, stride, groups
        super(GhostConv, self).__init__()
        c_ = c2 // 2  # hidden channels
        self.cv1 = Conv(c1, c_, k, s, None, g, act)
        self.cv2 = Conv(c_, c_, 5, 1, None, c_, act)`

**Comment by glenn-jocher** [comment]
Great!

**Comment by lucasjinreal** [comment]
@python-faker   how's the ghostconv performance after you changed?

**Comment by Ankur-singh** [comment]
@glenn-jocher & @python-faker what did you use for weights? I tried using `yolov5s.pt` but most of the weights are simply ignored. In  the output it showed `Transferred 146/553 items from yolov5s.pt`
It would be great if someone can share the pretrained weights.

**Comment by glenn-jocher** [comment]
@Ankur-singh all of our COCO models are trained from scratch with `--weights ''`
