### ISSUE TITLE
How to build  cpu based docker image with local pre-trained models ?

### ISSUE THREAD

**Issue by xkx9431** [ultralytics/yolov5#3981]
## ❔Question
How to build  cpu based docker image with local pre-trained models ?

## Additional context

I can not install some nvida gpu driver, also, I use your dockerFile and comment on this line,
```
RUN pip install --no-cache torch==1.9.0+cu111 torchvision==0.10.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html
```

but I will meet some errors when load model, can I download the pretrained model previously? 
such as where I can get some default *.pt files ?

```python 
model = torch.hub.load('path/to/yolov5', 'custom', path='path/to/best.pt', source='local')  
```

Also if you know how to build a CPU based docker images, can you kindly give some suggestions ? 
Thanks a lot

**Comment by xkx9431** [comment]
sorry， I got it.

**Comment by glenn-jocher** [comment]
@xkx9431 official Docker image operates correctly on CPU only hardware. No modifications are required.
