### ISSUE TITLE
How to load the json file generated by test.py?

### ISSUE THREAD

**Issue by addicter2017** [ultralytics/yolov5#3987]
## ❔Question
I set --save_json =True and obtained the json file successfully. From the annotations in test.py, it said that the json file is in coco style. However, when I tried to load the file with COCO('path_to_json') I met the error: AssertionError: annotation file format <class 'list'> not supported. How could I load the json generated by test.py to COCO class?

**Comment by addicter2017** [comment]
Solved

**Comment by dsathian** [comment]
how did you solve?

**Comment by addicter2017** [comment]
Using coco.loadRes(pred_json) where coco is the istance inherit from COCO class, it can be an annotation json file in coco style
