### ISSUE TITLE
Dataset not found 

### ISSUE THREAD

**Issue by qiuqiu-ai** [ultralytics/yolov5#3989]
## ❔Question

![屏幕截图 2021-07-13 114039](https://user-images.githubusercontent.com/77093670/125386633-301eea80-e3cf-11eb-909f-5900989e049f.png)

**Comment by glenn-jocher** [comment]
@qiuqiu-ai your --data was not found. It doesn't exist in the location you've pointed to.

**Comment by qiuqiu-ai** [comment]
thank you !




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Glenn ***@***.***&gt;; 
发送时间: 2021年7月13日(星期二) 下午4:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ultralytics/yolov5] Dataset not found  (#3989)





 
@qiuqiu-ai your --data was not found. It doesn't exist in the location you've pointed to.
