### ISSUE TITLE
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one.

### ISSUE THREAD

**Issue by DennisYoung96** [ultralytics/yolov5#399]
## Environment
 - OS: [Ubuntu20]
 - GPU [NVIDIA Corporation TU102 [TITAN RTX] ] * 2

Thanks for ur great work! 
I worked very well those days in my custom datasets.
but today, i did nothing  but want transfer from A datasets to B datasets,then i run into problems like this:
Output:
```
     Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
   59/2999     1.55G    0.1143   0.01843   0.09183    0.2246        26       640: 100%|██████████████████████████████████████████████████████████████████| 87/87 [00:37<00:00,  2.35it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|██████████████████████████████████████████████████████| 22/22 [00:07<00:00,  2.88it/s]
                 all         340    1.09e+03     0.00327      0.0208     0.00251    0.000429

     Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
  0%|      
Traceback (most recent call last):
  File "my_train.py", line 411, in <module>
    train(hyp)
  File "my_train.py", line 257, in train
    pred = model(imgs)
  File "/home/yz/anaconda3/envs/torch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yz/anaconda3/envs/torch/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 475, in forward
    self.reducer.prepare_for_backward([])
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
```
it always occur when run into the second epoch. whatever i use the pretrained weights files like best.pt or yolov5s.pt or None , this bug happend as expected.
Do anyone run into the same bugs?  I'm appreciate ur  your answers

#more bugs:
if i use the arg :--evolve ，the process always interrupted ,and raise the Error like this:
```
Traceback (most recent call last):
  File "my_train.py", line 453, in <module>
    results = train(hyp.copy())
  File "my_train.py", line 169, in train
    rank=0)  # node rank
  File "/home/yz/anaconda3/envs/torch/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 364, in init_process_group
    raise RuntimeError("trying to initialize the default process group "
RuntimeError: trying to initialize the default process group twice!
```

**Comment by FinnChou** [comment]
I have the same problem, and I found that the GPU memory is unstable when training yolov5s.
reduced batch sizes is worked for me.

**Comment by glenn-jocher** [comment]
@FinnChou it appears you may have environment problems. We don't try to debug local environments. Instead we offer a variety of verified environments:

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)

**Comment by DennisYoung96** [comment]
I find that if i train with one GPU ,or change the other datasets it works again!
so , it's the problem about DistributedDataParallel?

**Comment by Pluto1314** [comment]
@DennisYoung96 I also meet this problem when I use mutil gpus. I dont know what happen.

**Comment by ZJU-lishuang** [comment]
I have the same problem in mutil gpus.
reduced batch sizes is worked for me.

**Comment by Pluto1314** [comment]
thanks, i will try

**Comment by ZJU-lishuang** [comment]
in the v2 release,the problem seems not to appear again for me.
