### ISSUE TITLE
Classification by Size

### ISSUE THREAD

**Issue by hiiksu** [ultralytics/yolov5#3990]
## ❔Question
Hello, I'm a student studying machine learning. Can I label the same shape according to the size? Or I wonder if we can classify according to size. Thank you.

**Comment by glenn-jocher** [comment]
I don't understand your question.

**Comment by hiiksu** [comment]
@glenn-jocher 
What I want to ask you is, for example, can i sort objects called A according to their size? so even if they're the same objects, can they sort them according to their size?

**Comment by glenn-jocher** [comment]
@hiiksu I'm not really sure what you're asking. Sorting objects by size is a trivial non-ML problem.

**Comment by hiiksu** [comment]
@glenn-jocher Are you saying that even if it's the same object, it's not a difficult problem to distinguish according to its size I'm sorry it's not accurate because I'm using a translator.

**Comment by glenn-jocher** [comment]
@hiiksu size is just width * height, there's nothing simpler.
