### ISSUE TITLE
how to do a custom docker image and only cpu based, also consider size ?

### ISSUE THREAD

**Issue by xkx9431** [ultralytics/yolov5#3991]
## ❔Question
when I pull the image  by `docker pull ultralytics/yolov5`
I find this is too big, is there something wrong ? 
and if I can slim the image for only default models and object detection with rest API ? 

## Additional context
![image](https://user-images.githubusercontent.com/44063249/125414485-1284487d-cee9-4228-b32a-d1349b1ce96f.png)

**Comment by glenn-jocher** [comment]
<img width="1063" alt="Screenshot 2021-07-13 at 10 17 55" src="https://user-images.githubusercontent.com/26833433/125417099-80931f40-ee6e-48fe-8de9-2e6208f81bbd.png">
