### ISSUE TITLE
Color of Bounding box and Object in Bounding box??

### ISSUE THREAD

**Issue by tanujdhiman** [ultralytics/yolov5#3992]
## ❔Question
How to make color of bounding box and object in the bounding same in yolov5 model ??

**Comment by glenn-jocher** [comment]
@tanujdhiman colors are predefined per class by the Ultralytics color palette:
https://github.com/ultralytics/yolov5/blob/8ee9fd15059e807374f52527951399e61d57b1b0/utils/plots.py#L27-L43

**Comment by tanujdhiman** [comment]
Hi @glenn-jocher . When I implement this colors are not same!!
