### ISSUE TITLE
Cite YOLOv5

### ISSUE THREAD

**Issue by Chitti21** [ultralytics/yolov5#3995]
## ❔Questions
1. How to cite YOLOv5? 
2. Plz confirm is 1 BFLOPs = 1GFLOPs?
3. while training few datasets with YOLOv5s with and without mosaic data augmentation, the difference in map@0.5 is very high (more than 45 %). However, in case of YOLOv4, with and without mosaic augmentation produces within 20 %. Is mosaic augmentation a default necessity for YOLOv5s?

**Comment by glenn-jocher** [comment]
@Chitti21 

1. <a href="https://zenodo.org/badge/latestdoi/264818686"><img src="https://zenodo.org/badge/264818686.svg" alt="YOLOv5 Citation"></a>
2. Yes
3. Architecture and data augmentation are completely independent

**Comment by Chitti21** [comment]
@glenn-jocher Thank you
