### ISSUE TITLE
C++ API

### ISSUE THREAD

**Issue by ivder** [ultralytics/yolov5#40]
Will there any C++ API like the one in AlexeyAB's repo https://github.com/AlexeyAB/darknet#how-to-use-yolo-as-dll-and-so-libraries in the future??

I dont have trouble training using pytorch, but would be good if there's an alternative to run inference in C++

**Comment by glenn-jocher** [comment]
@ivder unfortunately I can't help on this, but this might have some info: https://pytorch.org/cppdocs/

There is also a comparable issue open on the subject:
https://github.com/ultralytics/yolov5/issues/32

**Comment by yasenh** [comment]
@ivder I have a simple demo that maybe you can refer to: https://github.com/yasenh/libtorch-yolov5

**Comment by name333** [comment]
The problem has been solved, thank you again for your help！

**Comment by name333** [comment]
hello ,
    Let me post a question in your project. In detect.cpp,
// if none remain then process next image
        if (det.size(1) == 0) {
            continue;
        }
det.size(1) == 0　should be　det.size(0) == 0　
Avoid situations where there is no object in the image，Is that right？
