### ISSUE TITLE
How to set confidence at runtime?

### ISSUE THREAD

**Issue by aviezab** [ultralytics/yolov5#4002]
## ❔Question
Hi @glenn-jocher , I am curious whether can We set confidence value at runtime?

`python detect.py --conf 0.2` <-- This value

I need this since my object detection actually good enough, but for some few datasets they have to be set at lower confidence value, but lowering the value makes others break. So it will be good idea to set them dynamically at runtime.

Sincerely,
aviezab

**Comment by glenn-jocher** [comment]
@aviezab yes your command is correct. You can use your command to run inference with an arbitrary confidence, i.e. 0.2 as you show.

**Comment by aviezab** [comment]
Sorry my question was not clear,
I mean, let us say we have deploy an inference with that command.

But at running time, I want to change the `conf` value without re-executing the command. Can I?

detect.py: Line 104
`pred = non_max_suppression(pred, conf_thres, iou_thres, classes, agnostic_nms, max_det=max_det)`

is that the code to possibly change the conf_thres at running time?

**Comment by glenn-jocher** [comment]
Sure.

**Comment by aviezab** [comment]
Thanks, I'll close the issue 😃
