### ISSUE TITLE
new builds don't run on jetson agx

### ISSUE THREAD

**Issue by tfpb** [ultralytics/yolov5#4003]
Hello,
you probably know that the jetson system aren't the best in terms of updates from nvidia. 

This is the device, jetson agx with python 3.6.9 and
tensorboard                   2.5.0
tensorflow                    2.5.0+nv21.6
torch                         1.8.0
torchvision                   0.9

I can run the yolo v5 version 5 from april  (with gpu), but the current github doesn't start.

python3 train.py --img 640 --cfg yolov5s.yaml --hyp hyp.scratch.yaml --batch 32 --epochs 50 --data my.yaml --weights yolov5s.pt --name mymodel

> Starting training for 100 epochs...
>      Epoch   gpu_mem       box       obj       cls     total    labels  img_size
>   0%|                                                                                                       | 0/1184 [00:05<?, ?it/s]
> Traceback (most recent call last):
>   File "train.py", line 660, in <module>
>     main(opt)
>   File "train.py", line 558, in main
>     train(opt.hyp, opt, device)
>   File "train.py", line 345, in train
>     scaler.scale(loss).backward()
>   File "/home/jetsonagx1/.local/lib/python3.6/site-packages/torch/tensor.py", line 245, in backward
>     torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
>   File "/home/jetsonagx1/.local/lib/python3.6/site-packages/torch/autograd/__init__.py", line 147, in backward
>     allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
> RuntimeError: Unable to find a valid cuDNN algorithm to run convolution

The current build works on a windows computer, but it would be great if it could run on jetson devices.
I tested pytorch 1.7,1,8 and 1,9, allway the same cuDNN message.

thanks
regards

**Comment by glenn-jocher** [comment]
@tfpb for Jetson inference you may want to see Jetson submissions to the YOLOv5 Export Competition:

## <div align="center">Compete and Win</div>

We are super excited about our first-ever Ultralytics YOLOv5 🚀 EXPORT Competition with **$10,000** in cash prizes!  

<p align="center">
  <a href="https://github.com/ultralytics/yolov5/discussions/3213">
  <img width="850" src="https://github.com/ultralytics/yolov5/releases/download/v1.0/banner-export-competition.png"></a>
</p>

**Comment by tfpb** [comment]
Hello Glenn,
thanks for the links, I didn't knew the competition.

The thing with the bug is, that my models run on a pc without a problem, just on the jetson with python 3.6.9 the current version it's not working. While the april v5 release works fine. 

I searched the error messages and found some topics talking about 2d conv... or did you dropped support for python 3.6, (the github bot say 3.8>=, your github pages 3.6>=) 

If you have some ideas I would test it for you, I also would update python but it's glued into jetpack 4.5....

thanks :)
best regards

**Comment by glenn-jocher** [comment]
Current master is compatible with python >= 3.6, but we need to update the bot message! Ill add a TODO for this.

**Comment by glenn-jocher** [comment]
TODO update python requirement repo-wide to 3.6

**Comment by glenn-jocher** [comment]
@tfpb ok, all tutorials, responses and READMEs are now updated to reflect our new relaxed python >= 3.6.0 requirements!

**Comment by leemengwei** [comment]
> Hello Glenn,
> thanks for the links, I didn't knew the competition.
> 
> The thing with the bug is, that my models run on a pc without a problem, just on the jetson with python 3.6.9 the current version it's not working. While the april v5 release works fine.
> 
> I searched the error messages and found some topics talking about 2d conv... or did you dropped support for python 3.6, (the github bot say 3.8>=, your github pages 3.6>=)
> 
> If you have some ideas I would test it for you, I also would update python but it's glued into jetpack 4.5....
> 
> thanks :)
> best regards
@tfpb Hi, 
just simplely reduce your batch size should make it work!
