### ISSUE TITLE
Precision and recall

### ISSUE THREAD

**Issue by PaulM5406** [ultralytics/yolov5#4005]
## ❔Question
First of all, thanks for this amazing repo !

I used yolov5 repo a few month ago with a custom dataset with about 1500 images. I trained yolov5m model and I obtain about 0.9 mAP_0.5 with it, with P and R > 0.85 During training, R and P raised about at the same speed.
Now I updated yolov5 repo to last commit and I have now a dataset around 6000 images. During training, after a few epochs, my P raises very very quickly to 0.8-0.9 after just a few epochs (~5) and stays high after. However R raises very very slowly and get to an wall at about 0.4. 

The main difference between my datasets is the number of images and also that now I have images with different size, from 1 to 2 in number of pixels.  The other different is the repo that has been well upgraded since my first use of the repo.

I tried with different input size and with the model yolov5l and I observe the same phenomenon.

Would you have some idea about this phenomenon ? 

Thank in advance !

**Comment by glenn-jocher** [comment]
@PaulM5406 P and R are now evaluated at maximum F1 confidence, before they were evaluated at a fixed value. In any case, P and R do not matter, you should look at mAP, which is evaluated over all possible confidences, not just 1.
