### ISSUE TITLE
How should I modify the position of the detection label

### ISSUE THREAD

**Issue by AKclown** [ultralytics/yolov5#4006]
## ❔Question
When I run python detect.py --weights weights/best.pt . If the detection label is not displayed, I should let it display normally, or change the label to the bottom instead of the top
![IMG_2724 HEIC](https://user-images.githubusercontent.com/33648653/125714390-14082930-5ab2-4f74-a81e-7db8c96cf714.JPG)

## Additional context
This is the test result of the normal display label
![01FAHJDB9WDH17TV49PMDQNQKQ](https://user-images.githubusercontent.com/33648653/125714507-e8ca6179-8b5c-4e1e-a722-553e91fc0bc9.jpg)

Can you give me some suggestions, I will be very grateful

**Comment by ChinaRush** [comment]
you can modify   utils/plots.py/plot_one_box(), 
`cv2.retangle()`

**Comment by AKclown** [comment]
Thank you for responding so quickly, yolov5 is very powerful
