### ISSUE TITLE
Cache-images using more space than dataset as whole

### ISSUE THREAD

**Issue by its-charan-here** [ultralytics/yolov5#4008]
## ❔Question

I was training a custom YoloV5 model using my dataset. 
The dataset that I am using is 2.5 Gb in total but when I use the --cache- images feature to speed up the training process, the cache file crosses 33Gb in total. Thus causing my Ram to crash and making the machine run out of memory.
How should I resolve this?

![image](https://user-images.githubusercontent.com/45040515/125743470-ef47ee31-d78d-448b-b83b-b9f43632e61b.png)

and the total data that I am using is 2.46 GB

![image](https://user-images.githubusercontent.com/45040515/125743573-12432d33-3174-4890-a581-ee9f02cefd75.png)

My Ram reaches its upper limit: 

![image](https://user-images.githubusercontent.com/45040515/125744489-5f14b148-50d4-49c3-874a-97fe97a11be5.png)

How should I resolve it?

**Comment by glenn-jocher** [comment]
@its-charan-here you resolve it by not caching or using a machine with more memory.

Images on disk are compressed and do not represent the amount of space occupied once loaded as numpy arrays.
