### ISSUE TITLE
Letterbox resizing is not available

### ISSUE THREAD

**Issue by TanyaChutani** [ultralytics/yolov5#4009]
## 🚀 Feature

Letterbox resizing is not available in yolov5

## Motivation

Letterbox resizing preserves the aspect ratio of an image

**Comment by glenn-jocher** [comment]
@TanyaChutani thanks for the suggestion! 

Lettterbox resize is the default resize method in YOLOv5.

**Comment by TanyaChutani** [comment]
@glenn-jocher Thanks!

**Comment by zhejunliux** [comment]
hi, @glenn-jocher and @TanyaChutani ,How to use  Letterbox  in yolov5? thanks.

**Comment by TanyaChutani** [comment]
@NJ2046 It's by default present in yolov5.
