### ISSUE TITLE
Difference between the different validation losses - where can I read about this?

### ISSUE THREAD

**Issue by TWilliamson95** [ultralytics/yolov5#4014]
## ❔Question
What is the difference between validation object loss and validation box loss?

## Additional context
I've really searched the internet, and checked the documentation, but I can only find references to general validation loss. To be honest, I would love to be able to see 'validation loss' instead of it being broken down further, but in wandb.ai it automatically shows the different types. Is there a way to show validation loss generally? Thanks!

**Comment by glenn-jocher** [comment]
@TWilliamson95 start here: https://arxiv.org/abs/1804.02767
