### ISSUE TITLE
Improve the performance of training without cache.

### ISSUE THREAD

**Issue by junjihashimoto** [ultralytics/yolov5#4017]
## 🚀 Feature

When training is without cache, the usage rate of gpu will not increase.
opencv preprocessing is too slow. 
It doesn't get faster even if I increase the number of workers of dataloader.

There are two improvements.

* Replace opencv preprocessing with pytorch's one using batch.
* Cache preprocessed data on disk.

## Motivation

When I try to cache  about 80,000 images, 64GB of memory is not enough.

## Pitch

Since it cannot be cached, it takes more than 1 hour per epoch with v100.

**Comment by glenn-jocher** [comment]
@junjihashimoto hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by junjihashimoto** [comment]
I've implement the cache on disk.
https://github.com/ultralytics/yolov5/pull/4049

**Comment by glenn-jocher** [comment]
@junjihashimoto good news 😃! Your original issue may now be fixed ✅ in PR #4049. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
