### ISSUE TITLE
Not always just one grid responsible for detecting an object

### ISSUE THREAD

**Issue by huyhoangle86** [ultralytics/yolov5#4022]
## ❔Question
Hi. I remember I heard this phrase somewhere that talked about YOLO or  mayber YOLOv5 but can't remember exactly the explanations.
What does it mean when it says `Not always just one grid responsible for detecting an object` , regarding this pic below ?

Thanks.

![image](https://user-images.githubusercontent.com/42195775/125924251-385e328f-9767-4413-b473-4f0bfd3c782c.png)

**Comment by glenn-jocher** [comment]
@huyhoangle86 the pic just displays a bounding box computation.

Detections are redundant across anchors via partial overlap strategies I developed.

**Comment by huyhoangle86** [comment]
@glenn-jocher 

`the pic just displays a bounding box computation.`

yeah I know but when the phrase says  `Not always just one grid responsible for detecting an object`

That means for example the midpoint of an object fall nearby 2 grid cells , so that 2 grid cells are responsible for detect that object ? is this correct ?

**Comment by glenn-jocher** [comment]
@huyhoangle86 yes

**Comment by huyhoangle86** [comment]
@glenn-jocher  Could you be more specific? How ?

**Comment by glenn-jocher** [comment]
@huyhoangle86 see build_targets() function in loss.py:

https://github.com/ultralytics/yolov5/blob/b7e985e397e12ea2efd19bf3b6329028fb2a4c75/utils/loss.py#L168-L221
