### ISSUE TITLE
Unable to use your own trained model for detection 

### ISSUE THREAD

**Issue by shankslee2021** [ultralytics/yolov5#4023]
## ❔Question
I just posted but I don't know how it got closed

I trained a model myself and got an error when performing the detection
I have trained a model using Train Custom Data 🚀 RECOMMENDED
Then I do the detection Reference
Detection method

import torch

model = torch.load("runs/train/exp11/weights/best.pt")

results = model('test.jpg') #Error
results.save('mytest.jpg')

Run-time error

Traceback (most recent call last):
File "mytest.py", line 15, in
results = model('test.jpg')
TypeError: 'dict' object is not callable

My ultimate goal is to call my trained model in a python file for single image detection
Tell me how to do it

Friends help me

**Comment by tomklaver1995** [comment]
Try using detect.py for running inference, this is the easiest way. 

Run detect.py --weights "runs/train/exp11/weights/best.pt" --source 'test.jpg'

**Comment by glenn-jocher** [comment]
@shankslee2021 as I already posted in a separate duplicate issue by you your implementation is incorrect and you need to follow the PyTorch Hub tutorial if you want python script inference:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by shankslee2021** [comment]
@glenn-jocher 

This is the demo I'm referring to

I'm still not quite sure what's wrong with the way I've implemented it?

Could you please elaborate on this.



import cv2
import torch
from PIL import Image


model = torch.hub.load('ultralytics/yolov5', 'yolov5s')


for f in ['zidane.jpg', 'bus.jpg']:
    torch.hub.download_url_to_file('https://ultralytics.com/images/' + f, f)  # download 2 images
img1 = Image.open('zidane.jpg')  # PIL image
img2 = cv2.imread('bus.jpg')[..., ::-1]  # OpenCV image (BGR to RGB)
imgs = [img1, img2]  # batch of images


results = model(imgs, size=640)  # includes NMS


results.print()  
results.save()  # or .show()

results.xyxy[0]  # img1 predictions (tensor)
results.pandas().xyxy[0]  # img1 predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 1  433.50  433.50   517.5  714.5    0.687988     27     tie
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie

**Comment by glenn-jocher** [comment]
@shankslee2021 the demo operates correctly. Follow the demo.

**Comment by shankslee2021** [comment]
@glenn-jocher 

The demo above uses script detection, right?
My python script is basically the same as yours?
The only difference is that I load local images and the weights are already trained
Your images and weights are from the web

**Comment by shankslee2021** [comment]
@glenn-jocher

I just tested your code and the error is the same：


import torch
import cv2


model = torch.load("./yolov5s.pt")

img = cv2.imread('test.jpg')[..., ::-1]
results = model([img],size=640) #Error

results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

error:

Traceback (most recent call last):
  File "D:/code/python/yolov5/test1.py", line 9, in <module>
    results = model([img],size=640) #Error
TypeError: 'dict' object is not callable

**Comment by glenn-jocher** [comment]
> @glenn-jocher
> 
> I just tested your code and the error is the same：
> 
> import torch
> import cv2
> 
> model = torch.load("./yolov5s.pt")
> 
> img = cv2.imread('test.jpg')[..., ::-1]
> results = model([img],size=640) #Error
> 
> results.print() # or .show(), .save(), .crop(), .pandas(), etc.
> 
> error:
> 
> Traceback (most recent call last):
> File "D:/code/python/yolov5/test1.py", line 9, in
> results = model([img],size=640) #Error
> TypeError: 'dict' object is not callable

that is not my code, that is your code

**Comment by shershunov** [comment]
Have you even read the article?
Load YOLOv5 from PyTorch Hub https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading
```py
import cv2
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Images
for f in ['zidane.jpg', 'bus.jpg']:
    torch.hub.download_url_to_file('https://ultralytics.com/images/' + f, f)  # download 2 images
img1 = cv2.imread('zidane.jpg')[..., ::-1]
img2 = cv2.imread('bus.jpg')[..., ::-1]
imgs = [img1, img2]

# Inference
results = model(imgs, size=640)  # includes NMS

# Results
results.print()  
results.show()
```

**Comment by orangebin** [comment]
Hello, I would like to ask, I have trained the PT file, and CMD ->detect.py can be proved, can I implement it in the code:  
Torch. Hub. load(my.pt) -> detect, if not, please teach a method

**Comment by glenn-jocher** [comment]
@orangebin see PyTorch Hub tutorial:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by orangebin** [comment]
Ok, thank you for your reply, new study, too anxious.
