### ISSUE TITLE
Rectangular training or mosaic for highly height/width difference

### ISSUE THREAD

**Issue by tomklaver1995** [ultralytics/yolov5#4025]
Hi all,
Just to share thoughts and hear about your opinions. I have a dataset of sentences in which I want to detect letters & numbers (some sort of custom OCR model). Since sentences have a higher width than height I doubt whether to use mosaic training or rectangular training. What are your thoughts about this? 
Kind regards

**Comment by glenn-jocher** [comment]
@tomklaver1995 I'm not sure your problem is best suited to Vision AI but you can experiment both ways, rectangular training will apply minimum letterbox padding to your batches:
```
python train.py --rect
```
