### ISSUE TITLE
Training details

### ISSUE THREAD

**Issue by zachluo** [ultralytics/yolov5#4031]
## ❔Question
It will be great if my concerns about training details could be addressed. Thanks.

i) it seems like the three anchors in one grid will be responsible for one ground-truth box. Am I correct? If so, will these three anchors with different sizes be difficult to regress the ground-truth box with a specific size at the same time?

ii) if the centers of two overlapped objects are almost the same or way too close, then one grid may be responsible for two different kinds of objects during training? 

Best

**Comment by glenn-jocher** [comment]
@zachluo yes YOLOv5 provides redundancy in various dimensions such as anchors, grids, P3-P6 outputs etc.

**Comment by zachluo** [comment]
@glenn-jocher thanks!
