### ISSUE TITLE
About pytorch hub's custom category label modification problem

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#4033]
@glenn-jocher 

Hello, I studied your pytorch hub related code (https://github.com/ultralytics/yolov5/issues/36)
Regarding custom local models:
https://github.com/ultralytics/yolov5/blob/951922c735c1e98b596fd9845de25a62fcdc7c73/hubconf.py#L65-L67
There is also the following calling code:
```
model = torch.hub.load('path/to/yolov5', 'custom', path='path/to/best.pt', source='local')  # local repo
```
I have a model trained with yolov5s called `ABC.pt`, and I put it in the yolov5 root directory. My ABC.pt model has only 3 categories, how should I modify it?**I know that pytorch hub uses coco’s 80 categories, I don’t know where to modify the name of my custom category label?** Please help me, thank you.

**Comment by glenn-jocher** [comment]
@Zengyf-CVer you just load your model as in the YOLOv5 PyTorch Hub tutorial, the class count is irrelevant.

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
Thank you very much, my problem is solved.
