### ISSUE TITLE
results.print() always prints "no detections"

### ISSUE THREAD

**Issue by pnama** [ultralytics/yolov5#4035]
## ❔Question
My cuda version is 11.1 and python version 3.8.5 but results.print() always prints (no detections)..... tried python=3.7 but couldn't fix....

Also tried cuda 10.2. Didn't work..

**Comment by glenn-jocher** [comment]
@pnama we've seen that sometimes windows or anaconda installs have issues with CUDA that results in no detections during inference. 

We don't know a good fix, so the best I can do is point you to one of our working environments below where everything is verified working correctly.

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

**Comment by glenn-jocher** [comment]
@pnama it's possible also you might need a more customized pytorch install, see https://pytorch.org/get-started/locally/

**Comment by pnama** [comment]
@glenn-jocher Thank you for your reply. I'm running on Jupyter and downloaded pytorch through pytorch/get-started page. I'm currently following the youtube video and seems like everyone else got it done. I'm so lost haha.. :(

**Comment by glenn-jocher** [comment]
@pnama colab is the easiest way to get started. You just click the Setup cell and then do whatever you want afterwards, i.e. click Detect cell to see an example of inference, or see the PyTorch Hub cell in the Appendix section:
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb
