### ISSUE TITLE
where I find the count number of each detected class and how to write it on image

### ISSUE THREAD

**Issue by besbesmany** [ultralytics/yolov5#4040]
## ❔Question
I need to write the count number of each detected classes on validation and testing images

or 
at least where to find these data for each image

**Comment by besbesmany** [comment]
in detect.py this line have `s`  which contains the count of objects I need
I want to omit image size 640x480 from picture how can I do that?

```
for c in det[:, -1].unique():
                    n = (det[:, -1] == c).sum()  # detections per class
                    s += f"{n} {names[int(c)]}{'s' * (n > 1)}, "
```
I added this before saving image

                   ` cv2.putText(im0,s, (20,100), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2, cv2.LINE_AA)`
![bus](https://user-images.githubusercontent.com/35992924/126067081-448b4cba-833d-4c4a-aee9-c5b05cc7ebfa.jpg)

**Comment by besbesmany** [comment]
will solve problem

`s += f"{n} {names[int(c)]}, "`

Thanks

**Comment by TrippieHippie** [comment]
> in detect.py this line have `s` which contains the count of objects I need I want to omit image size 640x480 from picture how can I do that?
> 
> ```
> for c in det[:, -1].unique():
>                     n = (det[:, -1] == c).sum()  # detections per class
>                     s += f"{n} {names[int(c)]}{'s' * (n > 1)}, "
> ```
> 
> I added this before saving image
> 
> ```
>                ` cv2.putText(im0,s, (20,100), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2, cv2.LINE_AA)`
> ```
> 
> ![bus](https://user-images.githubusercontent.com/35992924/126067081-448b4cba-833d-4c4a-aee9-c5b05cc7ebfa.jpg)

@besbesmany Where exactly did you added cv2.putText() line?

As even I am trying to achieve the same result as yours.

**Comment by HripsimeS** [comment]
@besbesmany Hello. Could you please share your modified detect.py file that archived the output image above with number of detected object per class. Thanks in advance!
