### ISSUE TITLE
Feature_Visualization Causing Difficulties

### ISSUE THREAD

**Issue by OGK0** [ultralytics/yolov5#4042]
## ❔Question
Hi All,

I'm using YOLO v5 (downloaded a few hours ago), and trying to understand  how to get feature visualizations. Looking at some of the past threads, it seems like the way to get the feature visualizations to show up is to set "visualize=True" in yolo.py. However, I'm running into the following error:

## Additional context

Traceback (most recent call last):
  File "train.py", line 661, in <module>
    main(opt)
  File "train.py", line 559, in main
    train(opt.hyp, opt, device)
  File "train.py", line 121, in train
    model = Model(cfg or ckpt['model'].yaml, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)  # create
  File "D:\Datasets\SIIM_RSNA_Covid_Datasets\tmp\yolov5\models\yolo.py", line 108, in __init__
    m.stride = torch.tensor([s / x.shape[-2] for x in self.forward(torch.zeros(1, ch, s, s))])  # forward
  File "D:\Datasets\SIIM_RSNA_Covid_Datasets\tmp\yolov5\models\yolo.py", line 123, in forward
    return self.forward_once(x, profile, visualize)  # single-scale inference, train
  File "D:\Datasets\SIIM_RSNA_Covid_Datasets\tmp\yolov5\models\yolo.py", line 158, in forward_once
    feature_visualization(x, m.type, m.i, save_dir=visualize)
  File "D:\Datasets\SIIM_RSNA_Covid_Datasets\tmp\yolov5\utils\plots.py", line 469, in feature_visualization
    ax[i].imshow(blocks[i].squeeze())  # cmap='gray'
  File "D:\Anaconda\envs\Pytorch\lib\site-packages\matplotlib\__init__.py", line 1447, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "D:\Anaconda\envs\Pytorch\lib\site-packages\matplotlib\axes\_axes.py", line 5523, in imshow
github: up to date with https://github.com/ultralytics/yolov5 

Downloading https://github.com/ultralytics/yolov5/releases/download/v5.0/yolov5s.pt to yolov5s.pt...

    im.set_data(X)
  File "D:\Anaconda\envs\Pytorch\lib\site-packages\matplotlib\image.py", line 698, in set_data
    self._A = cbook.safe_masked_invalid(A, copy=True)
  File "D:\Anaconda\envs\Pytorch\lib\site-packages\matplotlib\cbook\__init__.py", line 682, in safe_masked_invalid
    x = np.array(x, subok=True, copy=copy)
  File "D:\Anaconda\envs\Pytorch\lib\site-packages\torch\tensor.py", line 621, in __array__
    return self.numpy()
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
wandb: Waiting for W&B process to finish, PID 21508
wandb: Program failed with code 1.  Press ctrl-c to abort syncing.
wandb: - 0.00MB of 0.00MB uploaded (0.00MB deduped)
wandb: \ 0.00MB of 0.00MB uploaded (0.00MB deduped)
wandb: | 0.00MB of 0.01MB uploaded (0.00MB deduped)
wandb: / 0.00MB of 0.01MB uploaded (0.00MB deduped)
wandb: - 0.01MB of 0.01MB uploaded (0.00MB deduped)
wandb: \ 0.01MB of 0.01MB uploaded (0.00MB deduped)
wandb: | 0.01MB of 0.01MB uploaded (0.00MB deduped)
wandb: / 0.01MB of 0.01MB uploaded (0.00MB deduped)
wandb: - 0.01MB of 0.01MB uploaded (0.00MB deduped)
wandb:                                                                                
wandb: Find user logs for this run at: D:\Datasets\SIIM_RSNA_Covid_Datasets\tmp\yolov5\wandb\run-20210717_212836-1uq5c029\logs\debug.log
wandb: Find internal logs for this run at: D:\Datasets\SIIM_RSNA_Covid_Datasets\tmp\yolov5\wandb\run-20210717_212836-1uq5c029\logs\debug-internal.log
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: 
wandb: Synced exp: https://wandb.ai/ogk01/kaggle-siim-covid/runs/1uq5c029

Is there a patch for this in the works ? Apologies is this is an issue that is currently being remediated as we speak, or if there is another step that I should be doing to get feature_visualization to work. I should note that when "visualize=False", the code runs just fine. Thanks in advance for your help !

**Comment by glenn-jocher** [comment]
@OGK0 feature visualization is super easy:
```
python detect.py --visualize
```

**Comment by glenn-jocher** [comment]
![stage0_Focus_features](https://user-images.githubusercontent.com/26833433/126062640-b63be6f4-dd6c-4254-96e2-7ac5858b8ca8.png)
