### ISSUE TITLE
Increase accuracy of bounding boxes

### ISSUE THREAD

**Issue by Markus-Zlabinger** [ultralytics/yolov5#4045]
## ❔Question

How can I prioritize bounding box accuracy during model training? For my use case, predicted bounding boxes are only useful if they have at least an IOU of 95% or more.

There are some parameters in `hyp.scratch.yaml`, but I'm unsure which and how I should adapt them.

**Comment by glenn-jocher** [comment]
@Markus-Zlabinger you can modify the loss gains in your hyp yaml according to your priorities.

**Comment by Markus-Zlabinger** [comment]
> @Markus-Zlabinger you can modify the loss gains in your hyp yaml according to your priorities.

Thanks. Is it sufficient to increase the value for `box: 0.0.05  # box loss gain` or would you recommend any other modification to the hyp yaml configuration?

**Comment by glenn-jocher** [comment]
@Markus-Zlabinger you have to do your own experiments on your custom dataset and model to determine how best to achieve your goals
