### ISSUE TITLE
Do the augmentations change between batches/epochs during training?

### ISSUE THREAD

**Issue by tserdar** [ultralytics/yolov5#4046]
Hey @glenn-jocher, 

Do the augmentations change among batches and epochs during training? 

Or they are calculated once at the start and are always used the same for same batches?

**Comment by glenn-jocher** [comment]
@rocketsfallonrocketfalls every image is augmented randomly when loaded at runtime. YOLOv5 models never see the same image twice during training.

![YOLOv5 augmentation](https://user-images.githubusercontent.com/26833433/126068530-c4e2f2e8-01b4-4e59-9fc7-262bb50c16d0.jpg)

**Comment by tserdar** [comment]
Thank you, @glenn-jocher!
