### ISSUE TITLE
Exif Image Orientation

### ISSUE THREAD

**Issue by marvision-ai** [ultralytics/yolov5#405]
## ❔Question
Have you run into issues with Exif orientation for images? 
This is sometimes quite crucial for applications, and I wonder if it would benefit others if `detect.py ` could automatically compensate for this. What are your thoughts? 

## Additional context
Please see below for more information:
https://medium.com/@ageitgey/the-dumb-reason-your-fancy-computer-vision-app-isnt-working-exif-orientation-73166c7d39da

**Comment by glenn-jocher** [comment]
@marvision-ai train.py and test.py attempt to extract an exif-corrected size during label caching.
https://github.com/ultralytics/yolov5/blob/611ec44359432b3a3ac510e3d407dcae1bb1b7af/utils/datasets.py#L34-L47

detect.py dataloader does not consider exif.

You may want to independently verify this functionality on your own however, it has not had a 3rd party review.

**Comment by marvision-ai** [comment]
@glenn-jocher will do! Thank you. I'll update if I can verify.

**Comment by glenn-jocher** [comment]
@marvision-ai yes, independent verification would be great! Definitely don't just take my word for it.
