### ISSUE TITLE
is the train.py separate dataset to train and val

### ISSUE THREAD

**Issue by besbesmany** [ultralytics/yolov5#4051]
## ❔Question
if I used 100 images in training data are they divided to train and val images 
because I found in wandb val graphs 

If data is divided what is the ration and why we use val.py  --task(val or test )

## Additional context
![1](https://user-images.githubusercontent.com/35992924/126069666-10543ee1-c2c7-4871-883d-b856feffb62a.png)

**Comment by glenn-jocher** [comment]
@besbesmany splits are entirely up to you.

**Comment by besbesmany** [comment]
how can I split please in train.py?

**Comment by glenn-jocher** [comment]
@besbesmany you define your train/val/test splits in your data yaml. See Train Custom Data Tutorial for details:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)
