### ISSUE TITLE
the pred of training

### ISSUE THREAD

**Issue by zhouxin666251** [ultralytics/yolov5#4058]
## ❔in the training, i find the output of pred always changed. for example, the output maybe [16,3,80,80,85], [16,2,80,80,85],or [16,4,80,80,85]. I want to ask the mean of 3,2,4? Why they awalys changed?
In my opinion, the 3,2,4 express Anchors, but I don't know   why they awalys changed. Thanks for you reply

**Comment by glenn-jocher** [comment]
@zhouxin666251 second dimension is anchor dimension.
