### ISSUE TITLE
APs APm APl?

### ISSUE THREAD

**Issue by SyedHamza0196** [ultralytics/yolov5#4063]
Hi, would you please kindly tell me how to get AP for different scale APs APm APl?

**Comment by Hezey** [comment]
> Hi, would you please kindly tell me how to get AP for different scale APs APm APl?

Hello, I have the same problem. Have you solved it？

**Comment by glenn-jocher** [comment]
@Hezey hello! To calculate APs, APm, and APl (average precisions at small, medium, and large scales), you can use the `test.py` script with the `--scale-xy 2.0` flag for small, `--scale-xy 2.0, 0.5` for medium, and `--scale-xy 0.5` for large scales. This will evaluate AP at different object scales. For additional details, you can refer to our documentation at https://docs.ultralytics.com/yolov5/. Let me know if you have any further questions!
