### ISSUE TITLE
AttributeError: 'WandbLogger' object has no attribute 'log_imgs'

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/yolov5#4067]
@AyushExel it looks like we've introduced a bug in PR #4053. Can you take a look? To reproduce in Colab notebook:
- Run Setup cell
- Run Train cell

<img width="1238" alt="Screenshot 2021-07-19 at 13 18 59" src="https://user-images.githubusercontent.com/26833433/126152445-72266c30-3101-470c-ad52-5282591fdbcb.png">

**Comment by AyushExel** [comment]
@glenn-jocher ahh yes. I'll put a PR in a few mins

**Comment by glenn-jocher** [comment]
@AyushExel thanks!
