### ISSUE TITLE
how to specifiy percent of augmentation to be added to training data

### ISSUE THREAD

**Issue by besbesmany** [ultralytics/yolov5#4071]
## ❔Question
when I make changes in hyp.scratch.yaml 
and I have 100 images
how to specify the the percent of augmented images like 5% or 10% of the training data

**Comment by glenn-jocher** [comment]
@besbesmany you control image augmentation via your hyperparameter yaml and any Albumentation augmentations in your pipeline:
https://github.com/ultralytics/yolov5/blob/0cc7c587870f31f0fc175a74048ceca616870aea/utils/augmentations.py#L22-L27
