### ISSUE TITLE
Docker with default pytorch + CUDA 11.1 installed

### ISSUE THREAD

**Issue by Michelvl92** [ultralytics/yolov5#4072]
## 🚀 Feature

By default make the yolov5 docker with PyTorch + CUDA 11.1 support

## Motivation

Since by default PyTorch + CUDA 10.2 is installed, new GPUS such as Nvidia RTX 3080 and RTX 3090 can't be used (30XX capable devices), Which are already widely available, and speedup in comparison with the older GPUS. TO be able to use these GPUs CUDA >= 11 is needed, see: https://github.com/pytorch/pytorch/issues/45028

**Comment by glenn-jocher** [comment]
@Michelvl92 hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

The place you'd want to modify in your case is the Dockerfile here:
https://github.com/ultralytics/yolov5/blob/0cc7c587870f31f0fc175a74048ceca616870aea/Dockerfile#L1-L24

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by lleye** [comment]
@Michelvl92 I'm experiencing the same issue. Do you have a work around?
