### ISSUE TITLE
autoanchor: WARNING: Extremely small objects found. 33135 of 180250 labels are < 3 pixels in size.

### ISSUE THREAD

**Issue by TehKonnos** [ultralytics/yolov5#4074]
## ❔Question

Well, I have a pretty large dataset that I resized to 640x640 and some of its labels are really small. Will that affect my training results?

## Additional context
I am training a binary detector that recognize signs in the road. Currently the mAp 0.5 using yolov5s.yaml is 0.49 and mAp 0.95 is 0.29
Thank you very much

**Comment by glenn-jocher** [comment]
@TehKonnos small objects will produce worse results.
