### ISSUE TITLE
Yolov5 weights are not trained / fine tuning using cuda 11.2

### ISSUE THREAD

**Issue by luqsthunder** [ultralytics/yolov5#4075]
## ❔Question
Hi, I'm trying to reproduce the [basic training tutorial](https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data) and the network doesn't show any kind of training advance. I'm using pytorch==1.9.0, opencv==4.5.3, torchvision==0.10.0, with cuda=11.1, and a 1660 super. When I change to cuda 10.1 the training works normally. This can harm those who are users of the GTX/RTX 30XX cards, the question may already be answered elsewhere, however, I didn't find anything about it, there is something that needs to be done for the training occur with cuda 11.1 ?

## Additional context
i tried with python 3.7 and 3.9.

I am using anaconda to install. Basically run the following commands in a newly created environment:

to install pytorch:

`conda install pytorch=1.9.0 torchvision=0.10.0 torchaudio cudatoolkit=11.1 -c pytorch -c nvidia`

the remaining dependencies that yolov5 needs and I need:

`conda install matplotlib pillow pyyaml scipy tqdm seaborn scipy statsmodels scikit-learn tensorboard wandb pandas coremltools onnx -c conda-forge
`

Training with cuda 10.2
![image](https://user-images.githubusercontent.com/1775527/126236572-543b5265-72d5-4e26-8984-d2f5f62a7776.png)

Training with cuda 11.2
![image](https://user-images.githubusercontent.com/1775527/126236737-8a1a7d55-32d4-44d7-bc34-75fde8939626.png)

**Comment by glenn-jocher** [comment]
@luqsthunder very interesting, thanks for the detailed analysis. Can you also run detect.py with both configurations and let me know if detect.py fails to return detections with CUDA 11.1?

It appears that certain CUDA configs fail to run inference correctly, cause unknown. I've seen this most often occur with Windows and Anaconda installs. Are you using either?

**Comment by glenn-jocher** [comment]
@luqsthunder in addition to detect.py please also run this PyTorch Hub inference code and let me know if any detections fails to appear (inference is handled differently here under an AMP context manager similar to train.py):

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5x, custom

# Images
img = 'https://ultralytics.com/images/zidane.jpg'  # or file, PIL, OpenCV, numpy, multiple

# Inference
results = model(img)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
```

**Comment by glenn-jocher** [comment]
For reference Colab nvidia-smi output shows CUDA 11.2, and everything operates correctly in the notebook:
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

<img width="956" alt="Screen Shot 2021-07-20 at 10 53 34 AM" src="https://user-images.githubusercontent.com/26833433/126292038-91cec6c0-2aed-4c00-b79d-fce617cbf294.png">

**Comment by luqsthunder** [comment]
Hi @glenn-jocher  thank you for your reply. 

I am using ubuntu 20.04, with anaconda, my driver is 470, installed using ppa (ppa:graphics-drivers), my system has cuda 11.4 installed. By anaconda I change the installed version of cudatoolkit and cudnn to anaconda environment only.

The dectetion.py file works perfectly with the webcam, images and videos. The execution of the code above does not work correctly.

For cuda 10.2 it works perfect both, detection.py and the code above.

**Comment by luqsthunder** [comment]
I checked a little deeper. I believe this has to do with how pytorch was compiled with my GPU's compute-capabilities version. I will test it on newer GPUs from the 30XX series, and show the results here to help other people with the same error.

Or something that needs to be set before inference.

sorry for the edit, I rechecked the way I selected the device and it was wrong, torch.cuda.is_available() returns true.

**Comment by wangsen1312** [comment]
@luqsthunder I have met the same problem. Any solutions now?
My card is RTX A6000 with CUDA 11.2. I have compiled pytroch1.9.0 with torchvision 0.10.0 myself. It works well on other projects.
I have also tried on other cards, such as 2080Ti with cuda 10.2 using pytorch 1.8.1, the yolo project works well.

**Comment by luqsthunder** [comment]
Hi @wangsen1312, check if you can run with predict.py similar as mentioned above. 

I'm trying to understand how predict.py works to try to make a solution to the problem. I will try something on weekend.

**Comment by wangsen1312** [comment]
@luqsthunder I tried the predict.py. it works well.

**Comment by glenn-jocher** [comment]
@luqsthunder @wangsen1312 may be related to https://forums.aws.amazon.com/thread.jspa?messageID=991036&#991036

**Comment by wangsen1312** [comment]
@glenn-jocher  I have tried different combinations, maybe it's the problem from cuda 11+ ?

**Comment by glenn-jocher** [comment]
@wangsen1312 yes maybe.
