### ISSUE TITLE
Wrong indentation

### ISSUE THREAD

**Issue by imyhxy** [ultralytics/yolov5#4076]
https://github.com/ultralytics/yolov5/blob/0cc7c587870f31f0fc175a74048ceca616870aea/utils/wandb_logging/wandb_utils.py#L295

**Comment by glenn-jocher** [comment]
@imyhxy hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
