### ISSUE TITLE
multi gpu on docker error

### ISSUE THREAD

**Issue by lleye** [ultralytics/yolov5#4077]
Hi @glenn-jocher @NanoCode012, I updated docker last week and tried training in ddp on a100s. I'm having similar issues as mentioned in this pr. 

[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)

[E ProcessGroupNCCL.cpp:566] [Rank 4] Watchdog caught collective operation timeout: WorkNCCL(OpType=BROADCAST, Timeout(ms)=60000) ran for 60960 milliseconds before timing out.

RuntimeError: replicas[0][0] in this process with sizes [48, 12, 3, 3] appears not to match sizes of the same param in process 0.

[E ProcessGroupNCCL.cpp:325] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data. To avoid this inconsistency, we are taking the entire process down. terminate called after throwing an instance of 'std::runtime_error'

Is there a suggested work around?

**Comment by iceisfun** [comment]
Just curious what is your nvidia-smi output?

**Comment by glenn-jocher** [comment]
@lleye Docker image works correctly, you simply may want to optionally update torch from https://pytorch.org/get-started/locally/ once the image is running on your specific hardware.

We are training 8x A100 instances right now with zero issues.

**Comment by lleye** [comment]
@iceisfun lease see below. 

nvidia-smi on the docker image:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.102.04   Driver Version: 450.102.04   CUDA Version: 11.3     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  A100-SXM4-40GB      Off  | 00000000:0F:00.0 Off |                    0 |
| N/A   29C    P0    51W / 400W |      3MiB / 40537MiB |      0%      Default |
|                               |                      |             Disabled |

nvidia-smi without docker:
NVIDIA-SMI 450.102.04   Driver Version: 450.102.04   CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  A100-SXM4-40GB      Off  | 00000000:0F:00.0 Off |                    0 |
| N/A   29C    P0    51W / 400W |      3MiB / 40537MiB |      0%      Default |
|                               |                      |             Disabled 

===
pip show torch on docker:
Version: 1.9.0

pip show torch without docker:
Version: 1.9.0 or 1.9.0+cu111

**Comment by lleye** [comment]
@glenn-jocher do you mean run this `pip3 install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html` in docker?

**Comment by glenn-jocher** [comment]
@lleye sure, you can run the install inside the docker image to replace the default pytorch

**Comment by lleye** [comment]
@glenn-jocher same issue, errors out as above. Just to confirm you are training on latest docker pull ultralytics/yolov5:latest

**Comment by glenn-jocher** [comment]
@lleye yes, everything works correctly:
<img width="1088" alt="Screenshot 2021-07-21 at 10 26 09" src="https://user-images.githubusercontent.com/26833433/126456946-abcde753-7391-453e-8643-e1f78b7533c4.png">

**Comment by lleye** [comment]
thanks @glenn-jocher, for some reason, it doesnt work on my end.

@iceisfun @NanoCode012 any other suggestions?

**Comment by glenn-jocher** [comment]
@lleye @iceisfun may be related to https://forums.aws.amazon.com/thread.jspa?messageID=991036&#991036

I'm seeing this now on AWS P4 instances now also.

**Comment by Wenlong0913** [comment]
Hey guys, any updates? I'm facing the same issue.
