### ISSUE TITLE
The display of AP75, APs, APm and APl

### ISSUE THREAD

**Issue by ZZY-666** [ultralytics/yolov5#4083]
Hi! After running the test.py, only AP50 (mAP) and AP will be displayed. The format of the related parts of the paper using COCO data are AP50, AP75, APs, APm and APl. In order to better compare with other algorithms, could you show other AP values?
Or are you in the source code and implemented? How should it be used?
Looking forward to your reply, thank you！

**Comment by glenn-jocher** [comment]
@ZZY-666 that's not correct, we display P, R, mAP@0.5 and mAP@0.5:0.95. See va.py for details:
https://github.com/ultralytics/yolov5/blob/master/val.py

**Comment by ZZY-666** [comment]
Yes, I know. But after running val.py, other common indicators of the COCO dataset such as AP75, APs, APm and APl are not displayed.  If we show them together, the details of the experiment and the algorithm will be more perfect, I think.

**Comment by glenn-jocher** [comment]
@ZZY-666 hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
