### ISSUE TITLE
mAP grows a lot when --resume

### ISSUE THREAD

**Issue by TaoXieSZ** [ultralytics/yolov5#409]
## ❔Question

Hi, Glen大大 (mean pro, in Chinese),

I have this several times. Before my Colab 24h timeout, I have only 0.6 mAP@0.5. But when I angrily resumed, I have surprising 0.7...

Why it happened?

**Comment by glenn-jocher** [comment]
@ChristopherSTAN see https://github.com/ultralytics/yolov5/issues/292

On COCO, --resumed training looks like this:
> ![results](https://user-images.githubusercontent.com/26833433/87072863-55cc4f00-c1d1-11ea-9aa7-c94ab11477e4.png)
> _Originally posted by @glenn-jocher in https://github.com/ultralytics/yolov5/issues/292#issuecomment-656265046_

**Comment by TaoXieSZ** [comment]
So weird...
![image](https://user-images.githubusercontent.com/7379039/87493852-aef61180-c61b-11ea-9783-d37d3c95c6fd.png)

**Comment by glenn-jocher** [comment]
Yeah that is weird. The main difference is the Ema decay counter is reset to zero on resume.

If you see better results it may indicate the Ema is not suitable for your dataset. You might want to try training without it.

**Comment by glenn-jocher** [comment]
You can simulate no Ema by setting the Ema decay very small, decay=0.001
