### ISSUE TITLE
Calculate losses with empty lebels

### ISSUE THREAD

**Issue by q1135718080** [ultralytics/yolov5#4092]
## ❔Question
How to train and calculate losses with background pictures without labels？
## Additional context
I noticed that the empty tag can also be used for normal training, but how to calculate the loss and regression process of the empty tag is not very clear

**Comment by glenn-jocher** [comment]
@q1135718080 loss is computed on all images irrespective of their contents. Details are in loss.py:
https://github.com/ultralytics/yolov5/blob/3bef77f5cb7eda3fa3cae53f2579cd3363c99744/utils/loss.py#L88-L221

**Comment by q1135718080** [comment]
Yes, sir. I'll look at the code in detail. Thank you very much
