### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by Cl-zzx** [ultralytics/yolov5#4096]
## ❔Question

when I try to run the code like this: `python detect.py --source 0`
there is a problem occurred like this:   
**assert cap.isOpened(), f'Failed to open {s}'
AssertionError: Failed to open 0** 
I don't know how to fix this problem.

**Comment by glenn-jocher** [comment]
@Cl-zzx this is just cv2 telling you your webcam doesn't work.

**Comment by glenn-jocher** [comment]
@Cl-zzx works for me:

```bash
(venv) glennjocher@Glenns-MacBook-Air yolov5 % python detect.py --source 0

detect: weights=yolov5s.pt, source=0, imgsz=640, conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False
YOLOv5 🚀 v5.0-304-g2c073cd torch 1.9.0 CPU

Fusing layers... 
Model Summary: 224 layers, 7266973 parameters, 0 gradients
1/1: 0...  success (inf frames 1280x720 at 30.00 FPS)

0: 384x640 1 person, Done. (0.389s)
0: 384x640 2 persons, Done. (0.317s)
0: 384x640 1 person, 1 clock, Done. (0.312s)
0: 384x640 1 person, 1 clock, Done. (0.312s)
0: 384x640 1 person, Done. (0.304s)
```

**Comment by Cl-zzx** [comment]
> @Cl-zzx works for me:
> 
> ```shell
> (venv) glennjocher@Glenns-MacBook-Air yolov5 % python detect.py --source 0
> 
> detect: weights=yolov5s.pt, source=0, imgsz=640, conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False
> YOLOv5 🚀 v5.0-304-g2c073cd torch 1.9.0 CPU
> 
> Fusing layers... 
> Model Summary: 224 layers, 7266973 parameters, 0 gradients
> 1/1: 0...  success (inf frames 1280x720 at 30.00 FPS)
> 
> 0: 384x640 1 person, Done. (0.389s)
> 0: 384x640 2 persons, Done. (0.317s)
> 0: 384x640 1 person, 1 clock, Done. (0.312s)
> 0: 384x640 1 person, 1 clock, Done. (0.312s)
> 0: 384x640 1 person, Done. (0.304s)
> ```

**Comment by Cl-zzx** [comment]
> @Cl-zzx works for me:
> 
> ```shell
> (venv) glennjocher@Glenns-MacBook-Air yolov5 % python detect.py --source 0
> 
> detect: weights=yolov5s.pt, source=0, imgsz=640, conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False
> YOLOv5 🚀 v5.0-304-g2c073cd torch 1.9.0 CPU
> 
> Fusing layers... 
> Model Summary: 224 layers, 7266973 parameters, 0 gradients
> 1/1: 0...  success (inf frames 1280x720 at 30.00 FPS)
> 
> 0: 384x640 1 person, Done. (0.389s)
> 0: 384x640 2 persons, Done. (0.317s)
> 0: 384x640 1 person, 1 clock, Done. (0.312s)
> 0: 384x640 1 person, 1 clock, Done. (0.312s)
> 0: 384x640 1 person, Done. (0.304s)
> ```

thanks very much,and when I restart the driver of my camera and this works for me,too
