### ISSUE TITLE
Pytorch Hub OpenCV Webcam Stream

### ISSUE THREAD

**Issue by hdow1** [ultralytics/yolov5#4098]
## ❔Question
Hi, after years of ghosting forums until I find answers to my many coding issues, this problem has broken me and I have finally admitted defeat - leading to my first ever forum post...

I understand that the Pytorch Hub YOLOv5 explanation (with Zidane and the Bus) displays an image in a window using results.show(). I am trying to show my webcam stream using Pytorch Hub and results.show() shows this as a new window for every frame.... I have tried to get this to work with OpenCV's cv2.imshow('') but I can't get it to work and results in the error "TypeError: Expected cv::UMat for argument 'mat'".

I know what I am trying to achieve is possible as the webcam can be used using the console's "detector.py --source 0" but I want to get it to work when using Pytorch hub in Spyder IDE.

See below for my (non-working) code.

Any help or advice is greatly appreciated.

Cheers

## Additional context

```
import cv2
import torch
from PIL import Image
model = torch.hub.load('ultralytics/yolov5', 'custom', path=r"C:\Users\User\.cache\torch\hub\ultralytics_yolov5_master\YerDaSellsAvon.pt")
model = model.autoshape()
model.conf = 0.65 #confidence thresh

while True:
    cap = cv2.VideoCapture(0)
    ret, frame = cap.read()
    h,w = frame.shape[:2]

    results = model(frame, size=640)  # includes NMS

    cv2.imshow("results", results)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
    #results.show()  #doesnt work lol
results.xyxy[0]  # img1 predictions (tensor)
results.pandas().xyxy[0]  # img1 predictions (pandas)

cap.release()
cv2.waitKey(0)
cv2.destroyAllWindows()
```

**Comment by glenn-jocher** [comment]
@hdow1 you can render predictions on the images saved in results.imgs and then do whatever you want with them afterwards:

```python
results = model(imgs)
results.render()  # overlay predictions onto results.imgs
results.imgs  # etc. use for any purpose
```

**Comment by hdow1** [comment]
@glenn-jocher Thank you very much for your help.
Full code below for anyone forum ghosting in the future with the same problem
```
import cv2
import torch
from PIL import Image

# Model
model = torch.hub.load('ultralytics/yolov5', 'custom', path=r"C:\Users\User\.cache\torch\hub\ultralytics_yolov5_master\YerDaSellsAvon.pt")
model = model.autoshape()
model.conf = 0.65 #confidence thresh

while True:
    cap = cv2.VideoCapture(0)
    ret, frame = cap.read()
    h,w = frame.shape[:2]


    results = model(frame, size=640)  # includes NMS
    results.render()  # overlay predictions onto results.imgs
    results.imgs  # etc. use for any purpos
    imgs = cv2.cvtColor(frame, cv2.COLOR_RGB2BGR)

    cv2.imshow("results", imgs)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

results.xyxy[0]  # img1 predictions (tensor)
results.pandas().xyxy[0]  # img1 predictions (pandas)

cap.release()
cv2.waitKey(0)
cv2.destroyAllWindows()

```
