### ISSUE TITLE
--resume/ --weights not working when additional classes added

### ISSUE THREAD

**Issue by AB19** [ultralytics/yolov5#410]
Hi, 

Thank you for your excellent work on yolov5 and the repository. 

Context: I used the pre-trained weights from the repository yolov5s.pt (80 classes) to transfer learn on 399 classes. I was successful in doing so. I added 3 more classes and tried using the last.pt from my previous run it is throwing tensor mismatch errors.  It does not throw me any errors while im trying to train 402 classes using yolov5s.pt as my initial weights.

Here is the error i get

`Traceback (most recent call last):
  File "train.py", line 388, in <module>
    train(hyp)
  File "train.py", line 259, in train
    optimizer.step()
  File "/home/agarimella/python36-env/yolov5/lib/python3.6/site-packages/torch/optim/lr_scheduler.py", line 67, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/agarimella/python36-env/yolov5/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/home/agarimella/python36-env/yolov5/lib/python3.6/site-packages/torch/optim/sgd.py", line 106, in step
    buf.mul_(momentum).add_(d_p, alpha=1 - dampening)
RuntimeError: The size of tensor a (1212) must match the size of tensor b (1221) at non-singleton dimension 0`

I understand that 1212 = (399 classes + 5) * 3 and 1221 = (402 classes + 5) * 3. What i do not understand is why does this fail for my last run but does not fail for yolov5s.pt from the repository which has a tensor of 255 = (80 classes + 5) * 3.

Any help would be much appreciated.

TIA!

**Comment by glenn-jocher** [comment]
An error is the intended effect if you try to resume one model with a different model.

**Comment by AB19** [comment]
@glenn-jocher Thank you for your response! Appreciate it.

But im getting the same error when i use the '--weights' option and point it to the last trained model with 399 classes.

Here is the command i am using 

python3.6 train.py --img 416 --batch 64 --epochs 1000 --data data.yaml --cfg cfg.yaml --weights ./weights/last.pt --cache-images 

Im still getting the mismatch from above.

**Comment by glenn-jocher** [comment]
@AB19 --resume works without errors currently. It's use case is for interrupted training. Using --resume is exactly the same as using --weights last.pt, there is no difference.
https://github.com/ultralytics/yolov5/blob/f796708b500d7fa885eaf11cd8d47e8094c1cd40/train.py#L388

**Comment by AB19** [comment]
@glenn-jocher thanks! I've read the code. 

Any suggestions on how to eliminate the tensor mismatch error.

I have a model trained with 399 labels and X images. 

I added Y additional images. 

Now, i have to train on 402 labels and X+Y images and i want to use the previous model weights as initializer.

When i try that, it fails due to tensor mismatch error when i use this command

python3.6 train.py --img 416 --batch 64 --epochs 1000 --data data.yaml --cfg cfg.yaml --weights ./weights/previous_model_weights.pt --cache-images

**Comment by glenn-jocher** [comment]
@AB19 you can finalize training on your weights at anytime and turn them into 'official' pretrained weights, at which point they will behave exactly the same as the official yolov5 weights that the repo autodownloads:
https://github.com/ultralytics/yolov5/blob/f796708b500d7fa885eaf11cd8d47e8094c1cd40/utils/utils.py#L642-L653

You should note though that anytime you load up a class-mismatched model (i.e. you load official yolov5x.pt for a 10 class dataset) the output layers into Detect() are not transferred, they are left randomly initialized for obvious reasons. This is why there is no such thing as --resuming a model with a different class count.

**Comment by AB19** [comment]
@glenn-jocher Thanks! works for me.
