### ISSUE TITLE
Can I export a onnx model with dynamic batch ?

### ISSUE THREAD

**Issue by mehul-rigyn** [ultralytics/yolov5#4106]
## ❔Question
Can I export a onnx model with dynamic batch?

**Comment by glenn-jocher** [comment]
@mehul-rigyn sure:
```
python export.py --include onnx --dynamic
```

**Comment by oopsodd** [comment]
> @mehul-rigyn sure:
> 
> ```
> python export.py --include onnx --dynamic
> ```

Can I export with dynamic batch and fixed (height, width) size ? thanks!
