### ISSUE TITLE
Is it possible to use multi-channel images to train?

### ISSUE THREAD

**Issue by lxndrrss** [ultralytics/yolov5#4109]
## ❔Question
Is there a way to use images with more than 4 channels to train yolov5?

**Comment by glenn-jocher** [comment]
@AlexRoss-WHS at the moment the dataloader converts all images to 3-ch (i.e. COCO has some 1-ch images in the dataset) and PNGs lose their transparency channel.

It's trivial to create n-channel YOLOv5 models as ch is an argument on model construction but the dataloader would need some updates.

**Comment by lxndrrss** [comment]
Ok, I will have to look into that then. Thanks for the quick answer.

**Comment by abfleishman** [comment]
@AlexRoss-WHS did you have luck editing the dataloader? I would love to see an example if you did!

**Comment by lxndrrss** [comment]
@abfleishman Yes I managed to get it working fairly easily, albeit by disabeling some verification. I basically just replaced `cv2.imread()` and `Image.open()` calls with `tifffile.imread()` (I saved the images as multi-channel tiff-files) and changed the shape computation from ` shape = exif_size(im)` to `shape = (im.shape[0], im.shape[1])` in line 860. Then I had to comment out the `augment_hsv()` call in line 565 and the verification in lines 859 and 862-866, because having too many channels broke them. After that and changing the model config it worked as normal. Hope I didn't forget something but I basically just followed the error messeges one by one until it worked, so it should be easy to figure out if I did.

**Comment by abfleishman** [comment]
Awesome!  I look forward to giving this a shot!

**Comment by Inovative-UMS** [comment]
hey @AlexRoss-WHS, 
While training (running train.py) I need to pass weights. But since there is no pretrained weights with say 4 channel images, what should a pass for weights?

**Comment by lxndrrss** [comment]
hi @Inovative-UMS,
I'm sorry but I haven't touched yolov5 since I opened this issue back in 2021, so I can't help you. It would probably be better if you opened a new issue for your problem.

**Comment by glenn-jocher** [comment]
Hi @Inovative-UMS,

I apologize for the inconvenience, but I haven't worked on YOLOv5 since I initially opened this issue in 2021. As a result, I am unable to assist you with your current problem. However, I recommend opening a new issue with detailed information about your specific problem. This will allow the YOLOv5 community and the Ultralytics team to provide you with the necessary support and guidance.

Thank you for understanding, and I wish you the best of luck in resolving your issue.

Kind regards.
