### ISSUE TITLE
train without saving run/exp

### ISSUE THREAD

**Issue by sanamlimbu1010** [ultralytics/yolov5#4111]
Hi, I am new to yolov5 (and ML) and have trained a model several (30) times to test various things, so there are many unnecessary runs, which I would like to either delete or not save in the first place. Is that even possible? 

If not, I am thinking of moving them to another folder and saving further test runs in that folder.

**Comment by glenn-jocher** [comment]
@sanamlimbu1010 you can delete whatever logs you want of course. You can also customize the logging directory using the --project and --name arguments:
https://github.com/ultralytics/yolov5/blob/2c073cd207bae1163b472c561d3fd31b1d2ba870/train.py#L504-L507


Also --nosave will only save the final epoch.

**Comment by sanamlimbu1010** [comment]
Thanks, @glenn-jocher! I will save further test trainings in another directory.
