### ISSUE TITLE
How can I keep the directory structure of 'data/images'

### ISSUE THREAD

**Issue by rainoo** [ultralytics/yolov5#4113]
## ❔Question
When I use detect, under 'runs - detect-exp', I want to keep the directory structure of 'data/images'. What should I do?

## Additional context
for example, My data/images like this：

folder1
|------a.jpg
|------b.jpg
|------folder2
   |-------c.jpg
   |-------d.jpg
folder2
|------e.jpg
|------f.jpg

and , I want 'runs - detect-exp' is same to that:

folder1
|------a.txt
|------b.txt
|------folder2
   |-------c.txt
   |-------d.txt
folder2
|------e.txt
|------f.txt

**Comment by glenn-jocher** [comment]
@rainoo hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
