### ISSUE TITLE
Minimal TRT speed difference.

### ISSUE THREAD

**Issue by otiv-stef-devisscher** [ultralytics/yolov5#4114]
## Why is there no inference speed difference between the YOLOv5s6 model and the YOLOv5m6 model in TRT?
Not sure if questions about TRT are also answered here, but I'm quite stuck on this. I was able to create a good performing detection model with transfer learning from YOLOv5m6. The issue is that this model was too slow on inference. For this reason I transfer learned the YOLOv5s6 model and performance is also good enough, however, even with this model, the TRT inference is too slow. The weird part is that looking at how much smaller the YOLOv5s6 model is compared to YOLOv5m6, the inference speed in TRT should also be significantly faster. However I get the following results (on GTX 3080):

**YOLOv5s6**: 23.4135FPS -> 5.0825s for 119 images
**YOLOv5m6**: 22.3340FPS -> 5.3282s for 119 images

and for comparison the YOLOv5m model on the same dataset:

**YOLOv5l**: 75.8793FPS -> 1.5683s for 119 images

and as you can see, there is nearly no difference between YOLOv5s6 and YOLOv5m6, but the YOLOv5l is significantly faster, while in all documentation I can find, the speed difference between YOLOv5l and YOLOv5s6 should be way smaller than between YOLOv5s6 and YOLOv5m6. 

I am almost certain I am doing something wrong, but all the file sizes of the TRT models confirm that I am not accidentally using the wrong model. 

My question is what the cause of this could be and how I could get the higher inference speed in TRT? 

## Additional context
I used the `export.py` file to export all models to onnx and then used pytorch to create the TRT models.

**Comment by glenn-jocher** [comment]
@stef-devisscher I can only speak to PyTorch GPU and iOS ANE inference speeds, which follow the expected progression from YOLOv5s (fast) to YOLOv5x (slow).

- iOS ANE Speeds: https://github.com/ultralytics/yolov5/issues/1276
- PyTorch GPU Speeds: https://github.com/ultralytics/yolov5#pretrained-checkpoints

At the same inference size P6 models like YOLOv5m6 are only slightly slower than their P5 counterparts like YOLOv5m, perhaps 5-10% slower.

For YOLOv5 TensorRT exports and related issues see https://github.com/wang-xinyu/tensorrtx
