### ISSUE TITLE
run it with pytorch1.6.0

### ISSUE THREAD

**Issue by BJLZ123** [ultralytics/yolov5#4121]
Hello ! I have to run the project with pytorch==1.6 and get this error"Can't get attribute 'SiLU' on <module 'torch.nn.modules.activation' from 'D:\\anaconda3\\envs\\".   What should I do? Thank you.

**Comment by glenn-jocher** [comment]
@BJLZ123 

## Requirements

[**Python>=3.6.0**](https://www.python.org/) with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) installed including [**PyTorch>=1.7**](https://pytorch.org/get-started/locally/). To get started:
```bash
$ git clone https://github.com/ultralytics/yolov5
$ cd yolov5
$ pip install -r requirements.txt
```
