### ISSUE TITLE
How can I train my model instead of YoloV5.

### ISSUE THREAD

**Issue by CN-zdy** [ultralytics/yolov5#4123]
## ❔Question
Hi, this is a very interesting work. I have some confusion after reading the code. 

Can I train my detector? If so, how can I train my own model instead of YoloV5?

**Comment by glenn-jocher** [comment]
@CN-zdy yes, see **Train Custom Data** Tutorial to get started on your own model:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by CN-zdy** [comment]
Thanks for your reply, I learned a lot from this tutorial.

However,  I still have some confusion. Can I use this code to train my networks?  For example, EfficientNet, ResNet, nnU-Net.....

**Comment by glenn-jocher** [comment]
@CN-zdy you can train any model.yaml you want. See models and models/hub for premade options, or you can build your own.
