### ISSUE TITLE
fitness weights

### ISSUE THREAD

**Issue by AndreaBrg** [ultralytics/yolov5#4124]
Hi I was wondering how did you come up with the weight to evaluate the model fitness found here https://github.com/ultralytics/yolov5/blob/master/utils/metrics.py#L14

Was it just trial and error or there is something deeper?

Many thanks.

**Comment by glenn-jocher** [comment]
@AndreaBrg these are arbitrary as they are defined by the user based on their priorities. For example VOC metric is mAP@0.5 so if you wanted to evolve for best VOC results you would rebalance the fitness weights to emphasise mAP@0.5.
