### ISSUE TITLE
Reproduce results on COCO dataset

### ISSUE THREAD

**Issue by buxihuo** [ultralytics/yolov5#4128]
## ❔Question
Hi, this is a very interesting work.
I used the default configuration, but did not reproduce the map value,44.5 AP is shown on the website , but I just got 43.8 AP after 300 epoch.Could you give me some advice
[results.txt](https://github.com/ultralytics/yolov5/files/6869247/results.txt)
![results](https://user-images.githubusercontent.com/84908793/126792842-af0673a8-8f1a-4f3b-8790-41f8388543ef.png)
![pycoco](https://user-images.githubusercontent.com/84908793/126792913-42745e8d-7471-4dea-96b8-117d78bb77b2.PNG)

## Additional context
GPU : v100 16g
Code version: yolov5-5.0
python train.py --data coco.yaml --cfg yolov5m.yaml --weights '' --batch-size 40
python test.py --data coco.yaml --img 640 --conf 0.001 --iou 0.65 --weights runs/train/5m/weights/best.pt --device 0

**Comment by glenn-jocher** [comment]
@buxihuo using the P6 hyps may help reduce overfitting on larger models:
https://github.com/ultralytics/yolov5/blob/master/data/hyps/hyp.scratch-p6.yaml
