### ISSUE TITLE
how to choose an appropriate weight?

### ISSUE THREAD

**Issue by xiaowk5516** [ultralytics/yolov5#4129]
## ❔Question
how to choose an appropriate weight?

## Additional context
hi! When I set the epoch to 300, overfitting occurred at about 100 epoch. I get best.pt and last.pt. Can i use best.pt directly? i notice that you mentioned when  `If this overfits early then you can reduce epochs` and best.pt is saved when map is lowest in val dataset.

**Comment by glenn-jocher** [comment]
@xiaowk5516 yes use best.pt in all cases

**Comment by xiaowk5516** [comment]
thanks!
