### ISSUE TITLE
select_device for m1 neural_engine or gpu

### ISSUE THREAD

**Issue by Dave0995** [ultralytics/yolov5#4130]
## ❔Question
how could i specify gpu device or neural engine for m1 mac in yolov5❔

## Additional context
I want to test m1 CPU with yolov5, but i don't know how to specify the device in yolov5 implementation.

Thanks for support!

**Comment by shershunov** [comment]
`python detect.py --device cpu`

**Comment by Dave0995** [comment]
Yeah, i know, but if i specify 'cpu', all the proyect would execute on cpu cores and not in gpu cores or the neural engine cores, i suppose, i'm not sure

**Comment by glenn-jocher** [comment]
@Dave0995 PyTorch only support the default cpu backend on M1 devices.

CoreML exported YOLOv5 models run on iOS device ANE backends(i.e. in our [app](https://ultralytics.com/yolov5)), but this is different of course.

**Comment by Dave0995** [comment]
Thanks for your help!!! I got a better perspective.

**Comment by Dave0995** [comment]
I will close this issue.
