### ISSUE TITLE
how to choose optimization function 

### ISSUE THREAD

**Issue by besbesmany** [ultralytics/yolov5#4131]
how to choose activation function 
python train.py --adam
to choose adam activation 
how to make relu or other activation function

**Comment by glenn-jocher** [comment]
@besbesmany the activation function throughout the model is defined on L42 here:
https://github.com/ultralytics/yolov5/blob/4495e00016cb18b35011bf99da1beb4eb639186b/models/common.py#L36-L46

**Comment by besbesmany** [comment]
thank you sir

**Comment by besbesmany** [comment]
how to add relu activation function please

**Comment by glenn-jocher** [comment]
@besbesmany 
```python
self.act = nn.ReLU()
```

Please review the pytorch documentation before asking basics questions here.

**Comment by besbesmany** [comment]
thank you so much
