### ISSUE TITLE
desktop view as webcam input

### ISSUE THREAD

**Issue by orphan2020** [ultralytics/yolov5#4132]
## 🚀 Feature

inference on the desktop view 

## Motivation

sometimes inference on a dynamic input besides video or webcam is needed if you have a integrated videostream that cannot be picked up via an address or a website that one wants to track objects on 

## Pitch

mimic desktop view as a webcam input to be able to do inference on it

## Alternatives

regular screenshots that get constantly feed as images in a loop (very slow)

**Comment by glenn-jocher** [comment]
@orphan2020 hi, thank you for your feature suggestion on how to improve YOLOv5 🚀! Yes we've heard this request before, but I'm not sure what the best approach is as I don't believe cv2 or PIL have built-in desktop screenshot functionality. 

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by orphan2020** [comment]
my workaround now: making screenshots instead,doing inference on the screenshots

**Comment by glenn-jocher** [comment]
@orphan2020 the PyTorch Hub tutorial has been updated with screenshot inference instructions:

```python
import torch
from PIL import ImageGrab

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Image
img = ImageGrab.grab()  # take the screenshot

# Inference
results = model(img)
```

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)
