### ISSUE TITLE
for test images how to calculate accuracy of classes and objects

### ISSUE THREAD

**Issue by besbesmany** [ultralytics/yolov5#4141]
I'm still confused when testing how to calculate accuracy of classes and objects
how to compare labels of test images with trained model to get accuracy

also is detector.py doesn't used to get accuracy only used to get predicted image boxes for test images?

**Comment by aditya-dl** [comment]
Hey @besbesmany, please look into val.py. If my understanding is correct, it will most likely work for your use case.

**Comment by glenn-jocher** [comment]
@besbesmany 
```
python val.py --data DATA.yaml --weights MODEL.pt
```

**Comment by besbesmany** [comment]
I use 

> @besbesmany
> 
> ```
> python val.py --data DATA.yaml --weights MODEL.pt
> ```

I use this but how to see figures and percent's of (accuracy, percision, recall, loss) of detected objects and also accuracy of classification of the validation folder images

I use both tensorboard and wandb so how to get the result

**Comment by glenn-jocher** [comment]
@besbesmany all results are printed to screen and logged to runs/val
