### ISSUE TITLE
RTMP Stream link not working. Streaming from OBS to Twitch RTMP Ingest server

### ISSUE THREAD

**Issue by nandukalidindi** [ultralytics/yolov5#4142]
## ❔Question
I have been trying to get the YOLOV5 detect.py script to work with the RTMP stream links. The HTTP stream links (`.m3u8`) works as expected.

Setup:

**Software Encoder:** OBS
**Streaming to:** Twitch
**RTMP Ingest server:** rtmp://jfk.contribute.live-video.net/app/

I included the stream key that is associated with my account. I know the URL and Stream Key are correct because I can see my stream on Twitch directly. But when I try to use the respective rtmp stream link for YOLOv5 to detect, it throws the following error

```
...
Fusing layers... 
/usr/local/lib/python3.8/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ../c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
Model Summary: 224 layers, 7266973 parameters, 0 gradients
[rtmp @ 0x7ff06ea75340] Server error: not_found

OpenCV: Couldn't read video stream from file "rtmp://jfk.contribute.live-video.net/app/{streamKey}"
1/1: rtmp://jfk.contribute.live-video.net/app/{streamKey}... Traceback (most recent call last):
...
```

Is there some additional setup or procedure that I am missing? Thanks in advance.

## Additional context

I am trying to avoid the conversion of RTMP stream to a HTTP stream as I don't want to broadcast the feed, just need to RTMP stream to detect. Eventually I am planning to setup an RTMP ingest server that just ingests for the detection.

**Comment by glenn-jocher** [comment]
@nandukalidindi we use cv2 for streaming, if you have a problem it's 99% the time your stream. Before you try to use YOLOv5 just open your stream normally in cv2 to debug.
https://stackoverflow.com/questions/65601395/best-way-to-diagnose-videocapture-not-opening-the-rtmp-stream

**Comment by nandukalidindi** [comment]
@glenn-jocher Thank you for pointing out, will try to check from the SO answer. But my stream should not have a problem because the broadcast shows up on the Twitch channel.

**Comment by nandukalidindi** [comment]
It worked with a custom server that can ingest RTMP. Not sure what the issue is with the twitch ingest URL.
