### ISSUE TITLE
segment2box、segments2boxes、resample_segments？

### ISSUE THREAD

**Issue by HuKai97** [ultralytics/yolov5#4145]
What does the segment2box、segments2boxes、resample_segments function do？And what does segment label mean?

**Comment by glenn-jocher** [comment]
@coderhukai each of these functions has a comments section that explains it's purpose:
https://github.com/ultralytics/yolov5/blob/d17b45eaad041b2fbb219232363bc865d4134d5e/utils/general.py#L430-L437

Segment labels are used for segmentation tasks.

**Comment by HuKai97** [comment]
ok, thanks!
