### ISSUE TITLE
Yolo Tmp Disk space issue

### ISSUE THREAD

**Issue by jaideep11061982** [ultralytics/yolov5#4149]
## ❔Question

If we run out of tmp disk space specially at kaggle then how in that case we can make Yolo work. Is there an option to not use disk space rather read it from source location  into RAM and then discard it .

**Comment by glenn-jocher** [comment]
@jaideep11061982 I'm not exactly sure what you are asking. Data requires disk space. 

YOLOv5 does not use any disk space other than the git clone and checkpoint saving.

**Comment by synersignart** [comment]
Guys im getting the same issue when running Train.py its punishing my SSD suddenly out of disk space while training . how do you divert it to Ram or Physical Drive or something

**Comment by glenn-jocher** [comment]
@synersignart you can try caching the dataset in RAM if you have sufficient RAM:

### Usage

```bash
python train.py  # default, no caching
python train.py --cache  # RAM cache
python train.py --cache ram  # RAM cache
python train.py --cache disk  # Hard Drive cache
```

**Comment by synersignart** [comment]
> @synersignart you can try caching the dataset in RAM if you have sufficient RAM:
> ### Usage
> 
> ```shell
> python train.py  # default, no caching
> python train.py --cache  # RAM cache
> python train.py --cache ram  # RAM cache
> python train.py --cache disk  # Hard Drive cache
> ```

ah ok and to use GPU

**Comment by glenn-jocher** [comment]
CUDA device 0 is used automatically by YOLOv5 if available, no action is required on your part.
