### ISSUE TITLE
where I can find the summary of each run like in the figure 

### ISSUE THREAD

**Issue by besbesmany** [ultralytics/yolov5#4151]
Class      Images      Labels           P           R      mAP@.5
                 all          58         386        0.25       0.456       0.384       0.261
        black-bishop          58          22           0           0       0.056      0.0354
          black-king          58          29       0.319       0.966       0.836       0.592
        black-knight          58          30        0.41       0.209       0.251       0.137
          black-pawn          58          77       0.168           1       0.907        0.64
         black-queen          58          11       0.164        0.34       0.118      0.0547
          black-rook          58          28           0           0      0.0945      0.0623
        white-bishop          58          22       0.126       0.273       0.212       0.149
          white-king          58          29       0.447       0.966       0.731       0.489
        white-knight          58          19       0.101       0.579      0.0919      0.0579
          white-pawn          58          77       0.188       0.987        0.96       0.674
         white-queen          58          16           1           0       0.266       0.183
          white-rook          58          26       0.074       0.154      0.0889      0.0578
10 epochs completed in 0.072 hours.

![9](https://user-images.githubusercontent.com/35992924/126913538-cda92b75-e2fc-4ac4-8349-01038be968c2.png)

**Comment by glenn-jocher** [comment]
@besbesmany training results are logged to runs/train

**Comment by besbesmany** [comment]
what is the file name?
I can't find summary of each class 

 Class      Images      Labels           P           R      mAP@.5
             all          58         386        0.25       0.456       0.384       0.261
    black-bishop          58          22           0           0       0.056      0.0354
      black-king          58          29       0.319       0.966       0.836       0.592
    black-knight          58          30        0.41       0.209       0.251       0.137
      black-pawn          58          77       0.168           1       0.907        0.64
     black-queen          58          11       0.164        0.34       0.118      0.0547
      black-rook          58          28           0           0      0.0945      0.0623
    white-bishop          58          22       0.126       0.273       0.212       0.149
      white-king          58          29       0.447       0.966       0.731       0.489
    white-knight          58          19       0.101       0.579      0.0919      0.0579
      white-pawn          58          77       0.188       0.987        0.96       0.674
     white-queen          58          16           1           0       0.266       0.183
      white-rook          58          26       0.074       0.154      0.0889      0.0578

**Comment by glenn-jocher** [comment]
@besbesmany per-class metrics are printed to screen automatically if your dataset has <50 classes. To force them to appear you can use the --verbose flag:
```
python val.py --verbose
```

**Comment by besbesmany** [comment]
thank you sir
