### ISSUE TITLE
Memory of GPU for detecting one image

### ISSUE THREAD

**Issue by BerkovSmartMerch** [ultralytics/yolov5#4153]
Can I somehow figure out how much GPU memory is used to process one photo with the detect.py file?

**Comment by glenn-jocher** [comment]
@BerkovSmartMerch 

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Images
imgs = 'https://ultralytics.com/images/zidane.jpg'

# Inference
results = model(imgs)
results.print()  # or .show(), .save()

# CUDA Memory    
print(f'{torch.cuda.memory_reserved() / 1E9 if torch.cuda.is_available() else 0:.3g}G CUDA memory')  # (GB)
```

**Comment by BerkovSmartMerch** [comment]
Thanks. But what I need to change in this scrypt if I want to check another model (already trained detector based on yolo5s-transfomer)? And where can I put weights on?

**Comment by glenn-jocher** [comment]
@BerkovSmartMerch see PyTorch Hub tutorial for loading custom models.

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)
