### ISSUE TITLE
The position of SPP Layer

### ISSUE THREAD

**Issue by developer0hye** [ultralytics/yolov5#4155]
https://github.com/ultralytics/yolov5/blob/8acb5734c7f0d1b7baf62b5c5dab6107a37896c6/models/yolov5l.yaml#L11-L23

Hi, @glenn-jocher 

Why do you put in the SPP Layer before CSP Layer?

Have you ever done experiment about the position of the SPP Layer?

**Comment by glenn-jocher** [comment]
@developer0hye yes I experimented with this in the past with ultralytics/yolov3 and honestly can't remember the outcome, but I'm sure it's current location is not a coincidence.

If you'd like you can experiment with swapping it's placement with layer 9 (input/output channel counts are identical) and then run 2 trainings, default and updated and report back results please.

**Comment by developer0hye** [comment]
@glenn-jocher 
Thanks for your reply

Did you read the YOLOX technical report?
