### ISSUE TITLE
Is there any way to change the inf frame?

### ISSUE THREAD

**Issue by Choikyungho9** [ultralytics/yolov5#4156]
Is there any way to change the inf frame?

When I run yolov5 for the first time, inf frames are displayed as 2595x1944 .

This is a very large screen, it fills my screen. I would like to know how to reduce the initial starting frame size.

Very large screens seem to slow down motion.

![infframe](https://user-images.githubusercontent.com/20491139/126922389-73a0e4e2-086e-4fd1-88ca-65762ff6a676.jpg)

**Comment by glenn-jocher** [comment]
@Choikyungho9 this is a property of your stream and has nothing to do with YOLOv5. Inference shape is determined by --img argument only and is independent of source shape.

**Comment by Choikyungho9** [comment]
@glenn-jocher i See. That has nothing to do with inference. Then, is there no way to adjust the full screen size when running yolov5? For example, even using a function like 'cv2.resize'
