### ISSUE TITLE
Why anchor_ T is set to 4 

### ISSUE THREAD

**Issue by Weixueying** [ultralytics/yolov5#4158]
anchor_t: 4.0  # anchor-multiple threshold   
What is the reason for this setting

**Comment by glenn-jocher** [comment]
@Weixueying hyperparameters are based on evolution

**Comment by Weixueying** [comment]
get it thanks

**Comment by glenn-jocher** [comment]
@Weixueying 4.0 means that anchors with width of 4x or 1/4x of a label will match to that label for loss purposes during training.
