### ISSUE TITLE
How to use download script

### ISSUE THREAD

**Issue by WurmD** [ultralytics/yolov5#4161]
## ❔Question
I see a download script for SKU-100K at https://github.com/ultralytics/yolov5/blob/master/data/SKU-110K.yaml#L20. How do we use it?

## Additional context
(I'm copying it into a new file and running it, but I think that is not its intended usage)

**Comment by glenn-jocher** [comment]
@WurmD all YOLOv5 datasets automatically download on first request:
```
python train.py --data VOC.yaml
python train.py --data Argoverse-HD.yaml
python train.py --data SKU-110K.yaml
...
etc.
```

**Comment by WurmD** [comment]
Neat :) even better than expected
