### ISSUE TITLE
Cant Convert Yolov5s.pt to .onnx model

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#4164]
## 🐛 Bug
So i tried to export my custom trained yolov5model (Yolov5 pytorch) to an .onnx model with the ,,export.py''. I installed the requirements.txt and everything was fine. After that i typed the command ,,python export.py --weights [path] --img 416 batch 16''.
i could successfully convert the model to .torchscript but i just want .onnx for later tensorRT inferencing in C++. So down in my post ill put the input/output from the Anaconda3 Console after submitting my export command. Im rly confused because there is no error message but also no .onnx file ):

Input:
```
(base) C:\Users\caspa\Desktop\Neuer Ordner\yolov5-master\yolov5-master>python export.py --weights C:\Users\caspa\Desktop\yolov5\yolov5s.pt --img 416 --batch 16
```

Output:
```
export: weights=C:\Users\caspa\Desktop\yolov5\yolov5s.pt, img_size=[416], batch_size=16, device=cpu, include=['torchscript', 'onnx', 'coreml'], half=False, inplace=False, train=False, optimize=False, dynamic=False, simplify=False, opset=12
YOLOv5  2021-7-26 torch 1.9.0+cpu CPU

Fusing layers...
E:\Anaconda3\lib\site-packages\torch\nn\functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
Model Summary: 232 layers, 7249215 parameters, 0 gradients

PyTorch: starting from C:\Users\caspa\Desktop\yolov5\yolov5s.pt (14.7 MB)

TorchScript: starting export with torch 1.9.0+cpu...
C:\Users\caspa\Desktop\Neuer Ordner\yolov5-master\yolov5-master\models\yolo.py:57: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if self.grid[i].shape[2:4] != x[i].shape[2:4] or self.onnx_dynamic:
TorchScript: export success, saved as C:\Users\caspa\Desktop\yolov5\yolov5s.torchscript.pt (29.4 MB)

ONNX: starting export with onnx 1.9.0...
```

## Expected behavior
I was expecting to get an .onnx file after running that command but i just got .torchscript file

## Environment
Windows 10 
NVIDIA gtx 1060
tensorrt 7.0.0.11
cuda 10.0
cudnn 10.0
and i downloaded all the requirements.txt

**Comment by glenn-jocher** [comment]
@theRandString seems like environment issues, recommend you export in a verified environment like Colab:

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


If you have a minimum reproducible bug in a verified environment please submit a new bug report including code to reproduce.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by ghost** [comment]
Yes i tried it but i didnt know how to run export.py inside google colab so i just downloaded this project because then i know how to start the python file. Ill try to research how to start the export.py inside Google Colab. Thanks for the tipp :)

**Comment by glenn-jocher** [comment]
@theRandString I can't make it any easier, you open our colab notebook, run setup cell, and then run `!python export.py`

**Comment by ghost** [comment]
Thanks alot. It works :) i was trying to fix this for 3 hours now yikes.
