### ISSUE TITLE
Runtime error: couldnt close file

### ISSUE THREAD

**Issue by vmolakala** [ultralytics/yolov5#417]
![Screen Shot 2020-07-15 at 10 51 52 AM](https://user-images.githubusercontent.com/48494383/87560432-6d03b480-c689-11ea-9fcd-df8ce692b61a.png)

Hi, I get this error every now and then when I train models on my MacBook OS, and I was wondering what I can do to fix this. Just this morning I pulled all the latest updates, and would appreciate any help. I was using the yolov3-spp.yaml file and coco.yaml.

Thanks,

Vikram

**Comment by vmolakala** [comment]
`python train.py --img 416 --batch 16 --epochs 300 --data ./data/coco.yaml --cfg ./models/yolov3-spp.yaml --weights ''`
FYI: This was my command to start  training

**Comment by glenn-jocher** [comment]
@vmolakala this is a MacOS-specific python multiprocessing bug. Suggest you try one of the following environments.


## Reproduce Our Environment

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker).

**Comment by vmolakala** [comment]
Thanks, I'll check out the Kaggle Notebook along with Docker. 

Vikram
