### ISSUE TITLE
Coco128 not learning on device 0 but will on cpu

### ISSUE THREAD

**Issue by devcop0865** [ultralytics/yolov5#4170]
Training the Coco128 dataset using device 0, results in a mAP of 0 throughout the training process. However, if I train on 'cpu' it works fine. 

I have a fresh Git clone of Yolov5 to my Desktop The Coco128 dataset is also on Desktop adjacent to the yolov5 directory.

![folder2](https://user-images.githubusercontent.com/61848576/127057132-c6f58931-276f-4c93-87fd-cd09318dc7ad.PNG)
![folder1](https://user-images.githubusercontent.com/61848576/127057145-39101fc3-b2d2-4c36-bcec-b28e5dbff3dc.PNG)

I've tried training utilizing both Python 3.9.6 and 3.8.10 individually (3.8.10 currently installed). After installing the requirements, I pip uninstalled torch and torchvision then used the Pytorch website directions for install:

> python -m pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio===0.9.0 -f https://download.pytorch.org/whl/torch_stable.html

System Specs
---------------
Windows 10 Pro 64-bit
Intel i7--10750H CPU @ 2.60 Ghz, 6 cores 
32 GB RAM
NVIDIA GeForce GTX 1660 Ti (1536 CUDA cores, CUDA 11.1)

![cuda](https://user-images.githubusercontent.com/61848576/127052897-7d839847-6dd5-4033-9060-777142235057.PNG)

Training on Device 0
[training Coco128 device 0.txt](https://github.com/ultralytics/yolov5/files/6881277/training.Coco128.device.0.txt)

Training on CPU (interrupted at 7th epoch)
[training Coco128 device cpu.txt](https://github.com/ultralytics/yolov5/files/6881279/training.Coco128.device.cpu.txt)

If I attempt to train on device 1, 2, or 3, naturally I get the following error: 

> AssertionError: CUDA unavailable, invalid device 3 requested

Thank you for your time and help.

**Comment by wudashuo** [comment]
If you train on Windows, I suggest you use CUDA10.2 and the corresponding version of PyTorch.
I met environmental problems using CUDA11 on Windows before.

**Comment by wangsen1312** [comment]
maybe it's the problem from CUDA 11+, I think some of us met the problem on ubuntu.

**Comment by devcop0865** [comment]
That worked! 10.2 works! THANK YOU!!!!!!!!!
