### ISSUE TITLE
inference time with c++, torchscript

### ISSUE THREAD

**Issue by yananren2137** [ultralytics/yolov5#4177]
## ❔Question
I using the model transformed by the torchscript with c++.
Strangely, the first two predictions（just the forward of model） took a long time（143ms and 8065ms）。
After these, the inference time is very short， about 7ms。
How can I solve this problem？Thanks

**Comment by iceisfun** [comment]
In my code I warmup the model by forwarding a blank image through it before processing data

What is your c++ inferance code based on? Just curious

**Comment by yananren2137** [comment]
> In my code I warmup the model by forwarding a blank image through it before processing data
> 
> What is your c++ inferance code based on? Just curious

I do the warmup two times. But the warmup time is too long. Strangely, the first warmup inference time is 180ms+,and the second is 8000ms.
Since the third infercne, the cost time is normal, just like 25ms.

**Comment by yananren2137** [comment]
> In my code I warmup the model by forwarding a blank image through it before processing data
> 
> What is your c++ inferance code based on? Just curious

My code is below.

Detector::Detector(const std::string& model_path, const torch::DeviceType& device_type) : device_(device_type) {
    std::vector<std::string> tokens;
    split(model_path, tokens, '/');
    try {
        // Deserialize the ScriptModule from a file using torch::jit::load().
        module_ = torch::jit::load(model_path);
    }
    catch (const c10::Error& e)
    {
        std::cerr << "Error loading " << tokens[tokens.size()-1] << std::endl;
//        std::exit(EXIT_FAILURE);
    }
    name = tokens[tokens.size()-1];

    half_ = (device_ != torch::kCPU);
    module_.to(device_);

    if (half_) {
        module_.to(torch::kHalf);
    }

    module_.eval();
}


std::vector<std::vector<Detection>>
Detector::Run(const cv::Mat& img, float conf_threshold, float iou_threshold, int size) {
    torch::NoGradGuard no_grad;
    std::cout << "---------- " << name << " New Frame----------" << std::endl;

    // TODO: check_img_size()

    /*** Pre-process ***/

    auto start = std::chrono::high_resolution_clock::now();

    // keep the original image for visualization purpose
    cv::Mat img_input = img.clone();

    std::vector<float> pad_info = LetterboxImage(img_input, img_input, cv::Size(size, size));
    const float pad_w = pad_info[0];
    const float pad_h = pad_info[1];
    const float scale = pad_info[2];

    cv::cvtColor(img_input, img_input, cv::COLOR_BGR2RGB);  // BGR -> RGB
    img_input.convertTo(img_input, CV_32FC3, 1.0f / 255.0f);  // normalization 1/255
    auto tensor_img = torch::from_blob(img_input.data, {1, img_input.rows, img_input.cols, img_input.channels()}).to(device_);

    tensor_img = tensor_img.permute({0, 3, 1, 2}).contiguous();  // BHWC -> BCHW (Batch, Channel, Height, Width)

    if (half_) {
        tensor_img = tensor_img.to(torch::kHalf);
    }

    std::vector<torch::jit::IValue> inputs;
    inputs.emplace_back(tensor_img);

    auto end = std::chrono::high_resolution_clock::now();
    auto duration = std::chrono::duration_cast<std::chrono::milliseconds>(end - start);
    // It should be known that it takes longer time at first time
    std::cout << "pre-process takes : " << duration.count() << " ms" << std::endl;

    /*** Inference ***/
    // TODO: add synchronize point
    at::cuda::CUDAStream stream = at::cuda::getCurrentCUDAStream();
    AT_CUDA_CHECK(cudaStreamSynchronize(stream));

    start = std::chrono::high_resolution_clock::now();

    // inference
    torch::jit::IValue output = module_.forward(inputs);

    stream = at::cuda::getCurrentCUDAStream();
    AT_CUDA_CHECK(cudaStreamSynchronize(stream));
    end = std::chrono::high_resolution_clock::now();
    duration = std::chrono::duration_cast<std::chrono::milliseconds>(end - start);
    // It should be known that it takes longer time at first time
    std::cout << "inference takes : " << duration.count() << " ms" << std::endl;

    /*** Post-process ***/

    start = std::chrono::high_resolution_clock::now();
    auto detections = output.toTuple()->elements()[0].toTensor();

    // result: n * 7
    // batch index(0), top-left x/y (1,2), bottom-right x/y (3,4), score(5), class id(6)
    auto result = PostProcessing(detections, pad_w, pad_h, scale, img.size(), conf_threshold, iou_threshold);

    end = std::chrono::high_resolution_clock::now();
    duration = std::chrono::duration_cast<std::chrono::milliseconds>(end - start);
    // It should be known that it takes longer time at first time
    std::cout << "post-process takes : " << duration.count() << " ms" << std::endl;

    return result;
}

**Comment by iceisfun** [comment]
Did you try what I said about processing one image before regular data?

I just process a single [ 1280, 720, 3 ] blank frame and wait for that to be complete before processing real data.

Did you just port the IOU and Letterbox from the python?

The IOU stuff is a little complicated.

        img = self.LoadImages([ np.zeros(shape=[1280, 720, 3], dtype=np.uint8) ])
        try:
            full = Model(img)
            # Waiting for model... takes a few seconds
            self.Debug('Warmup complete')
        except Exception as e:
            print(e)

**Comment by yananren2137** [comment]
> Did you try what I said about processing one image before regular data?
> 
> I just process a single [ 1280, 720, 3 ] blank frame and wait for that to be complete before processing real data.
> 
> Did you just port the IOU and Letterbox from the python?
> 
> The IOU stuff is a little complicated.
> 
> ```
>     img = self.LoadImages([ np.zeros(shape=[1280, 720, 3], dtype=np.uint8) ])
>     try:
>         full = Model(img)
>         # Waiting for model... takes a few seconds
>         self.Debug('Warmup complete')
>     except Exception as e:
>         print(e)
> ```

My warm up is inference one blank image.

cv::Mat run_img = cv::Mat::ones(img_size,img_size,CV_8UC3);

**Comment by iceisfun** [comment]
Would you share your c++ implementation of letterbox and iou/nms?

I've found your other code helpful working with c++ yolov5 myself.

If you can't its fine

**Comment by yananren2137** [comment]
> Would you share your c++ implementation of letterbox and iou/nms?
> 
> I've found your other code helpful working with c++ yolov5 myself.
> 
> If you can't its fine

My code is based on this. 
https://github.com/yasenh/libtorch-yolov5
