### ISSUE TITLE
How do I get the confidence score in percentage? 

### ISSUE THREAD

**Issue by joicejoseph3198** [ultralytics/yolov5#4183]
You know how the output has bounding box with confidence score with up to 2 decimal point. Is there a way i can change the code to display it in percentage?

**Comment by glenn-jocher** [comment]
@joicejoseph3198 you can modify labels on L158:
https://github.com/ultralytics/yolov5/blob/63a1971e3140b38c22a8c1620f7c0deda2cca53b/detect.py#L148-L162
