### ISSUE TITLE
Without yolov5 how many people will lose their jobs or fail to graduate?

### ISSUE THREAD

**Issue by liuchangji** [ultralytics/yolov5#4186]
## ❔Question

yolov5 is the best project in the world,

thank you ultralytics!

**Comment by thusinh1969** [comment]
It just takes a bit too long to train :D ... Love it.

**Comment by glenn-jocher** [comment]
@liuchangji thanks! Our mission is to make real-world AI easy and useful. We've made progress but we've just started this journey, and you and everyone else can help us by reporting any bugs you find, floating any features that come to mind, and of course contributing your own pull requests! 

We love your input! We want to make contributing to YOLOv5 as easy and transparent as possible. Please see our [Contributing Guide](CONTRIBUTING.md) to get started. 

@thusinh1969 you can use `--cache` to speed up training if you have sufficient RAM to cache your dataset, and we have an open PR https://github.com/ultralytics/yolov5/pull/4049 for caching on disk as well that should allow faster training in RAM-constrained environments

**Comment by SpongeBab** [comment]
@liuchangji Are you also a graduate student?
