### ISSUE TITLE
How to monitor images on the desktop in real time

### ISSUE THREAD

**Issue by GUOOOZI** [ultralytics/yolov5#419]
## ❔Question
I try to use the following code for screen capture 
`screen = np.array(ImageGrab.grab(bbox=BOX))`
and
` return cv2.cvtColor(screen, cv2.COLOR_BGR2RGB)
`
Also made changes in detect.py
![image](https://user-images.githubusercontent.com/62709607/87584162-fbe9ee80-c6d4-11ea-9af4-eab88b74bd7e.png)
![image](https://user-images.githubusercontent.com/62709607/87584230-158b3600-c6d5-11ea-8484-4406b738de43.png)

In fact, when I run this program, the output is
![image](https://user-images.githubusercontent.com/62709607/87584321-36ec2200-c6d5-11ea-9161-8c291c53640b.png)

The program does not continue to run, and no image is displayed. So I would like to ask for help if there is an already implemented way to monitor the images on the desktop in real time.

**Comment by avaninder** [comment]
Hey @GUOOOZI, the way I use yolov5 on my screen is via logi capture. Set it up and just leave the app running with it looking at your screen, and use --source 1,2,3,4 and so on until you find which one is your screen. Hope this helps.

**Comment by sukumr** [comment]
Hi @GUOOOZI are you able to make it work with screen capture?

**Comment by glenn-jocher** [comment]
@sukumr @charizardavi @GUOOOZI inference on screen capture is super easy:

```python
import torch
from PIL import ImageGrab

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Image
img = ImageGrab.grab()  # take a screenshot

# Inference
results = model(img)
results.show() # or .print(), .save(), .crop(), .pandas(), etc.
```

![tmpfl6ecof7](https://user-images.githubusercontent.com/26833433/141280505-d115c52a-2b5f-4d91-aa99-efa0bfc85285.jpg)

**Comment by sukumr** [comment]
@glenn-jocher thanks for your input, I want to capture the screen continuously (not just single image) in a loop and show bounding boxes. When i run result.show() it is showing seperate images and the run is terminating due to out of memory.
