### ISSUE TITLE
Precision of 0 and mAP different from 0

### ISSUE THREAD

**Issue by cyndyNKCM** [ultralytics/yolov5#4192]
Hello @glenn-jocher ,

I'm working on object detection on custom data with yolov5.

Here is the code i run :

`!python train.py --img 640 --batch 16 --epochs 90 --data /content/gdrive/MyDrive/custom_data.yaml --weights yolov5s.pt --nosave --cache`

Here is the result i get : 

 
![Capture d’écran (6)](https://user-images.githubusercontent.com/65983769/127311139-21947c1c-a3c7-435e-818e-f63a467550ef.png)

I want to know why can I have a precision of 0 but a mAP different from 0?
What are the parameters constituting the mAP?

Please what is **x\lr** in the tensorboard?

Thanks

**Comment by glenn-jocher** [comment]
@cyndyNKCM P and R are displayed at maximum F1 confidence threshold, mAP is for all confidences. See P, R plots in runs/train/exp etc for details.
