### ISSUE TITLE
Not Showing Validation accuracy while training!

### ISSUE THREAD

**Issue by karndeepsingh** [ultralytics/yolov5#4193]
## ❔Question
I have forked new updated repo recently and started training my model and it is not printing validation accuracy.
Following image shows the output.
Any help.
Thanks.
## Additional context
![image](https://user-images.githubusercontent.com/49562460/127317662-ba9936fe-b0bb-485a-b667-61141153af1e.png)

**Comment by glenn-jocher** [comment]
@karndeepsingh your validation results are displayed, they are 0.
