### ISSUE TITLE
Detailed description of the data

### ISSUE THREAD

**Issue by ONNONS** [ultralytics/yolov5#4196]
## ❔Question

thank you so much
May I ask one more question?
I need to explain the output data in yolo v5

1.confusion_matrix.png
2.F1_curve.png
3.labels_correlogram.jpg
4.labels.jpg
5.P_curve.png
6.PR_curve.png
7.R_curve.png
8.Result.png

I can't even google it, and I'm 17, so I guess it's because I don't understand yet.

I need help

what is all this

## Additional context

![image](https://user-images.githubusercontent.com/65228677/127330030-67baca1a-7e50-46f0-abba-5da20369803b.png)

**Comment by glenn-jocher** [comment]
@ONNONS these are standard object detection results and label introspection tools.

See https://en.wikipedia.org/wiki/Precision_and_recall for details.
