### ISSUE TITLE
Numerical file for the confusion matrix

### ISSUE THREAD

**Issue by zkytony** [ultralytics/yolov5#4199]
## ❔Question
It is awesome that the training program safes the confusion matrix plot at the end. Does it save the numbers in a text file? I would like to have access to it. Otherwise, I would have to regenerate the confusion matrix by myself.

**Comment by glenn-jocher** [comment]
@zkytony confusion matrices are generated automatically by val.py, values are not logged.
```
python val.py --data DATA.yaml --weights MODEL.pt
```

**Comment by zkytony** [comment]
@glenn-jocher Is the confusion matrix saved under `runs/train/` computed using training images or validation images?

Also, even though I specified "val" in the dataset yaml file, when I run `train.py`, I don't get a separate `runs/val` folder.
So I tried running `val.py`, because I want to make sure I am generating confusion matrix for validation images. The command I run is:
```
python yolov5/val.py\
       --data $DATASET_YAML_FILE\
       --img $IMG_SIZE\
       --weights $VALIDATION_MODEL_WEIGHTS\
       --save-txt\
       --save-hybrid\
       --save-conf\
       --save-json\
       --project "../results/$DATASET_NAME/runs/val"\
       --name "exp"
```
(please ignore the variables).

Strangely, even though I set `--weights` to be a model that's trained for only 1 epoch, I get a perfect confusion matrix saved under `val.py`:
![confusion_matrix](https://user-images.githubusercontent.com/7720184/127416395-80366903-f1ae-4c48-8c20-ddcf0fe0bd9e.png)
This is really confusing :confused: What did I do wrong?

**Comment by glenn-jocher** [comment]
@zkytony train.py logs results to runs/train, if you run val.py directly it will log results to runs/val.

**Comment by zkytony** [comment]
@glenn-jocher By results, does train.py generate results for the training data (i.e. data stored under “train” in the dataset yaml?) That is my question.

**Comment by zkytony** [comment]
I see. It is on the validation data.

In `train.py`:
```
    # end training -----------------------------------------------------------------------------------------------------
    if RANK in [-1, 0]:
        LOGGER.info(f'{epoch - start_epoch + 1} epochs completed in {(time.time() - t0) / 3600:.3f} hours.\n')
        if not evolve:
            if is_coco:  # COCO dataset
                for m in [last, best] if best.exists() else [last]:  # speed, mAP tests
                    results, _, _ = val.run(data_dict,
                                            batch_size=batch_size // WORLD_SIZE * 2,
                                            imgsz=imgsz,
                                            model=attempt_load(m, device).half(),
                                            iou_thres=0.7,  # NMS IoU threshold for best pycocotools results
                                            single_cls=single_cls,
                                            dataloader=val_loader,
                                            save_dir=save_dir,
                                            save_json=True,
                                            plots=False)
```
The results are generated by running `val.run`, which by default has `task='val'`. The above call does not set `task` so it is kept as `val`.
