### ISSUE TITLE
您好，现在只有电脑摄像头才可以显示窗口，怎末让传入的MP4文件也实时显示出来在桌面的呢？

### ISSUE THREAD

**Issue by Tiang-88** [ultralytics/yolov5#42]

**Comment by h030162** [comment]
detect.py
line:132

vid_writer.write(im0)
cv2.imshow("detect", im0)
cv2.waitKey(1)

**Comment by sljlp** [comment]
你好，请问再你电脑上可以实时吗？我这里测试的是3fps
