### ISSUE TITLE
关于weights的问题

### ISSUE THREAD

**Issue by zhaoguoqing12** [ultralytics/yolov5#420]
我是用train.py进行训练,但是在训练期间保存检查点,但并不想进行后期的训练,yolo 5x现在weights为675MB，有什么方法可以让模型weights参数回归到正常参数

**Comment by liuchangji** [comment]
貌似是你让他训练到最后，他就会变小了。。。我也是训练到中间就停止训练了，发现权重文件变大了

**Comment by sonica1987** [comment]
我也遇到过一次中途停止,有200多M,正常就20来M
