### ISSUE TITLE
how to change fps?

### ISSUE THREAD

**Issue by pythonmjs** [ultralytics/yolov5#4201]
## ❔Question
hi, thanks for the wonderful resource. I've question regarding fps. Currently, it is 30 fps. To process 3-minute video, it takes 30 minutes. I want to make 3 fps to process the video. How do I change it? I tried to change it manually but it didn't work.
Help would be highly appreciated to change the fps

## Additional context
<img width="1680" alt="Screen Shot 2021-07-28 at 8 23 59 AM" src="https://user-images.githubusercontent.com/22041656/127349888-ed3341ca-3bb8-4f8b-a934-64f6c8db592e.png">

**Comment by glenn-jocher** [comment]
@pythonmjs local videos are loaded using the LoadImages() class. You can modify this accordingly:
https://github.com/ultralytics/yolov5/blob/750465edae8a1eb68409377c3bba94a49d3bf196/utils/datasets.py#L154-L232
