### ISSUE TITLE
training in jupyter notebook

### ISSUE THREAD

**Issue by saadtayeb** [ultralytics/yolov5#4203]
## ❔Question

a have a large data that i can't upload in my drive o directly in colab, so i thought about using jupyter notebook 
the issue is that i cannot keep track of the training process ,the epoches ect while the training,
is there away to help me show this informations
## Additional context
this is what it looks liks
![20210728_175649](https://user-images.githubusercontent.com/57964164/127365517-aca9dc3c-8b54-43a5-81c0-21d10bb60810.jpg)
this is what i want 
![16274918393619154526159821074224](https://user-images.githubusercontent.com/57964164/127365698-45845210-e126-480f-aa53-7d190ab44b01.jpg)
thanks

**Comment by glenn-jocher** [comment]
@saadtayeb see Colab notebook examples for TensorBoard and W&B logging:
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

**Comment by saadtayeb** [comment]
the think is i want to use jupyter notebook not google colab but it does not show me the eovlution of the training
