### ISSUE TITLE
the non_max_suppression don't work ?

### ISSUE THREAD

**Issue by Libaishun** [ultralytics/yolov5#421]
I apply non_max_suppression with conf_thresh=0.3, iou_thresh=0.6,the following is the result, it seems nms doesnot work at all !
![image](https://user-images.githubusercontent.com/20390029/87622108-f7fdb100-c754-11ea-9e0f-198c67f712ab.png)

**Comment by glenn-jocher** [comment]
Do not use a bug label for questions.
