### ISSUE TITLE
AssertionError: Image Not Found

### ISSUE THREAD

**Issue by KKKKQF** [ultralytics/yolov5#4210]
## Additional context
Hi,when I use my own dataset, it can't find my images,firstly,I think it is because the images are not 'RGB',but after I make them 8-bit to 24-bit,It still reports an error as'AssertionError: Image Not Found ..\datasets\images\train\缺陷0001.jpg'

**Comment by KKKKQF** [comment]
I've solved the problem,it because of my Chinese image name

**Comment by wudashuo** [comment]
First thing first, you should NOT name your image with Chinese characters, because OpenCV hardly supports non-ASCII or non-Unicode characters, all Chinese CVers should know that.

**Comment by KKKKQF** [comment]
> First thing first, you should NOT name your image with Chinese characters, because OpenCV hardly supports non-ASCII or non-Unicode characters, all Chinese CVers should know that.


I see now
