### ISSUE TITLE
How to support camera

### ISSUE THREAD

**Issue by HarveyWa** [ultralytics/yolov5#4211]
Hello, whether the project can support usb or rtsp camera?

**Comment by wudashuo** [comment]
The answer is already in README:

![image](https://user-images.githubusercontent.com/5948604/127442898-91832740-b1c1-4e3f-8cb6-099b20ad3c56.png)

**Comment by guoguoguo123** [comment]
can support it，but RTSP have a big delay when using ,around 8~10 seconds.

**Comment by hoavt-54** [comment]
@guoguoguo123 

The delay may come from the limit of your hardware. You can use another thread to always refresh and keep the latest frame from the source video. 
Please take a look at this [code](https://stackoverflow.com/questions/43665208/how-to-get-the-latest-frame-from-capture-device-camera-in-opencv) from StackOverflow.

Edit: changed to a better code

**Comment by zombob** [comment]
> can support it，but RTSP have a big delay when using ,around 8~10 seconds.
 
@guoguoguo123
There is a easy way to resolve:
Add another line `cap.grab()` in the "update" function in file dataloaders.py
```
# _, self.imgs[index] = cap.read()
cap.grab()
cap.grab() # twice grab for getting the last frame(drop the extra frames)
if n % read == 0:
```

**Comment by GianniGi** [comment]
> Please take a look at this [code](https://stackoverflow.com/questions/43665208/how-to-get-the-latest-frame-from-capture-device-camera-in-opencv) from StackOverflow.

Thanks for your answer, right now I'm experimenting with rtsp and with youtube live cameras. The solution that you linked is still valid? thanks
