### ISSUE TITLE
v5s why used RAM 3G ??

### ISSUE THREAD

**Issue by woshizhangcheng** [ultralytics/yolov5#4213]
GPU nvidia-3060 12G  
torch 1.7.1+cu110
Python 3.7.0
Intel(R) Xeon(R) CPU E5-2687W v3 @ 3.10GHz

```
import torch
from memory_profiler import profile
@profile(precision=4)
def attempt_load(weights):
    model = torch.hub.load('ultralytics/yolov5', 'custom', weights)
    return model


if __name__ == '__main__':
    weights = '../weights/best.pt'
    model = attempt_load(weights)
```

```
Fusing layers... 
Model Summary: 224 layers, 7053910 parameters, 0 gradients
Adding AutoShape... 
Filename: /home/gpu/sibat/FXM_AIServer/debug/09.py

Line #    Mem usage    Increment  Occurences   Line Contents
============================================================
    14 973.7734 MiB 973.7734 MiB           1   @profile(precision=4)
    15                                         def attempt_load(weights):
    16 4056.6523 MiB 3082.8789 MiB           1       model = torch.hub.load('ultralytics/yolov5', 'custom', weights)
    17 4056.6523 MiB   0.0000 MiB           1       return model

```
![image](https://user-images.githubusercontent.com/34908468/127466207-28fd009f-9994-45b1-b73f-dc2a00e39c4b.png)

**Comment by lucky2046** [comment]
I have the same doubt

**Comment by glenn-jocher** [comment]
@lucky2046 the high RAM usage you're observing is a result of model loading, including the fusing of layers and the addition of AutoShape. YOLOv5 is designed to maximize speed and efficiency and thus typically performs well on modern GPUs like your Nvidia-3060. The high-level features of YOLOv5, such as the number of layers and parameters, necessitate the additional memory allocation. If you have further questions or need assistance with YOLOv5, feel free to ask!
