### ISSUE TITLE
Content of yolov5s.yaml

### ISSUE THREAD

**Issue by FleetingA** [ultralytics/yolov5#4216]
Hello,

I will be training on custom data with a single class using the smallest YOLOv5 weights. 

Should I change the contents of the yolov5s.yaml file to read nc:1, or is it sufficient that my data.yaml file contains nc:1?

Thanks in advance!

**Comment by iwordly** [comment]
Hello,
I used single classification for training yesterday. I only modified coco128.yaml and forgot to modify yolov5s.yaml. Surprisingly, it can make good predictions after completing normal training, so I think yolov5s.yaml should not be modified.

**Comment by glenn-jocher** [comment]
@FleetingA @iwordly for training custom data see Train Custom Data tutorial:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by FleetingA** [comment]
Okay, so that surely means that the yolov5s file should not be changed.

**Comment by glenn-jocher** [comment]
@FleetingA nothing needs to be changed, you just train as in the tutorial.
