### ISSUE TITLE
what is bbox_interval & save_period in details

### ISSUE THREAD

**Issue by besbesmany** [ultralytics/yolov5#4226]
what are they exactly 
 bbox_interval & save_period in train.py

is there a detailed description for train.py and val.py parameters 
it is not fully described in the .py files

**Comment by glenn-jocher** [comment]
@besbesmany these are W&B parameters used for logging. 

@AyushExel can you help out here?

**Comment by AyushExel** [comment]
@besbesmany
*   `--bbox_interval` can be used to set the interval for logging images in the W&B bounding box debugger . If not set by user this interval will be initialized as `bbox_interval = epochs//10 if epochs>10 else epochs`
![Screenshot (46)](https://user-images.githubusercontent.com/15766192/127676413-e2c71770-d4dc-4014-bd61-ccf44273397e.png)
* `--save_period` is used to set the interval for logging your model checkpoints as artifacts. By default, only the final model will be logged. But if you set `--save_period` to `n`, your models will be logged after every `n` epochs.
This can be useful for sharing results or resuming runs on another device.
![Screenshot (48)](https://user-images.githubusercontent.com/15766192/127676827-8eff1b52-3e3c-4a06-86c8-20bb7ef5a90f.png)

I'll work with the maintainers to include some details about W&B features in the W&B tutorial soon. Thanks!
P.S. Sorry for the late reply, I wrote this hours ago but I forgot to publish it.

**Comment by besbesmany** [comment]
thank you @AyushExel
