### ISSUE TITLE
Training with custom data - cls_loss is keeps zero all the time?

### ISSUE THREAD

**Issue by SuperCrystal** [ultralytics/yolov5#423]
## ❔Question

Hello! I'm training with my own data which has only one class. All seems well except that the cls_loss is always 0. I'm not sure what makes that happened. 
![1](https://user-images.githubusercontent.com/43337139/87629976-a100d780-c766-11ea-9622-a129f8c6ee53.png)

**Comment by Laughing-q** [comment]
@SuperCrystal  Because you have only one class, there is no need to care about classification,  just need to care about whether there are objects

**Comment by SuperCrystal** [comment]
> @SuperCrystal Because you have only one class, there is no need to care about classification, just need to care about whether there are objects

See it. Thx a lot!

**Comment by buimanhlinh96** [comment]
@SuperCrystal Can you show me your custom yaml file and model yaml file. I also train only one class but i got an error:"Label class 1 exceeds nc=1 in ./models/yolov5l.yaml. Correct your labels or your model" 
Thank you so much!

**Comment by Laughing-q** [comment]
@buimanhlinh96 you have just one class, it seems that your label class should contain index 0 only but contain index 1 , set single-cls=True may fix this.
