### ISSUE TITLE
Annotation issues in metrics.py

### ISSUE THREAD

**Issue by paleblackless** [ultralytics/yolov5#4230]
## ❔Question
Excuse me,  I am analyzing the  training  results of my dataset  according to ConfusionMatrix graph to reduce false detection and miss detection rate results.
I face some confusion，when reading source code implementation about  confusion matrix  generation  in metrics.py.
The following annotations ，I think it's the opposite.
https://github.com/ultralytics/yolov5/blob/master/utils/metrics.py#L150
https://github.com/ultralytics/yolov5/blob/master/utils/metrics.py#L155
Not sure if I have the right idea？

**Comment by glenn-jocher** [comment]
@liutaotao369 the confusion matrix code and comments are correct.

**Comment by paleblackless** [comment]
Thanks,I am aware of my problem.
