### ISSUE TITLE
how to draw percision, recall curve for yolov5 tensorboard

### ISSUE THREAD

**Issue by besbesmany** [ultralytics/yolov5#4232]
how to draw the pr_curve for yolov5 tensorboard?

**Comment by glenn-jocher** [comment]
@besbesmany PR curve is saved as PR_curve.png in your logging directory.

**Comment by besbesmany** [comment]
I want to compare PR curves for  several runs in same chart in tensorboard, how can I do it sir

**Comment by glenn-jocher** [comment]
@besbesmany hi, thank you for your feature suggestion on how to improve YOLOv5 🚀! You'd have to submit a PR for TensorBoard logging of the 4 curves produced: P, R, PR, F1. These four curves are produced here:
https://github.com/ultralytics/yolov5/blob/d8f18834a246cfe3589406635c7e990f8043130a/utils/metrics.py#L69-L76

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by besbesmany** [comment]
I don't know how to do it , I need help to draw pr curve for several runs in one chart for comparison

**Comment by glenn-jocher** [comment]
@besbesmany I looked into this some more, the curves won't plot as scalars in TensorBoard but they are saveable as images:
https://www.tensorflow.org/tensorboard/image_summaries?hl=en

**Comment by besbesmany** [comment]
ok thank you sir

**Comment by glenn-jocher** [comment]
@besbesmany I would use W&B to view your results, as you can view all your PR curves in a project side by side.

**Comment by glenn-jocher** [comment]
@besbesmany good news 😃! Your original issue may now be fixed ✅ in PR #4220. This PR implements callbacks and also adds all results plots to TensorBoard by default. This allows you to compare curves from different runs side by side, i.e.:

<img width="1184" alt="Screenshot 2021-08-01 at 00 17 53" src="https://user-images.githubusercontent.com/26833433/127753639-1cc78b97-00f3-4bad-8845-c4c056407940.png">

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by besbesmany** [comment]
Dear sir
which lines exactly should I  run

```
!git clone https://github.com/ultralytics/yolov5  # clone repo
%pip install -qr requirements.txt  # install dependencies

import torch
from IPython.display import Image, clear_output  # to display images
clear_output()
print(f"Setup complete. Using torch {torch.__version__} ({torch.cuda.get_device_properties(0).name if torch.cuda.is_available() else 'CPU'})")

%load_ext tensorboard
%tensorboard --logdir runs/train

# Train YOLOv5s on COCO128 for 3 epochs
!python train.py --img 640 --batch 16 --epochs 3 --data coco128.yaml --weights yolov5s.pt --cache
```

should I do anything else to compare pr curve for several runs?

I didn't understand these 2 lines:
PyTorch Hub – Force-reload with model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)
Docker – sudo docker pull ultralytics/yolov5:latest to update your image

**Comment by glenn-jocher** [comment]
@besbesmany open Colab notebook:
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

1. Run Setup cell
2. Run Tensorboard cell
3. Run Train cell

**Comment by besbesmany** [comment]
Thank you sir

**Comment by besbesmany** [comment]
is this also for wandb or tensorboard only?

**Comment by glenn-jocher** [comment]
@besbesmany both

**Comment by besbesmany** [comment]
thanks alot
