### ISSUE TITLE
how to show vector properties of the input and output of the module

### ISSUE THREAD

**Issue by Grenaf** [ultralytics/yolov5#4234]
## ❔Question
Hello author, I follow the tutorial(TorchScript, ONNX, CoreML Export) to open the onnx model using netron.How can I get results like this
![image](https://user-images.githubusercontent.com/73221711/127655747-b3023580-a9ca-42c1-8223-70f042a1e1d4.png)
I just want to know the vector properties of the input and output of the module. I tried view attributes, initializers, name. but it does not work in netron.
this is my result:
![image](https://user-images.githubusercontent.com/73221711/127655948-48139ccd-a308-4f76-8a83-3f30989e0a97.png)

## Additional context
i use netron5.0.5 and yolov5-5.0, my question comes from https://github.com/ultralytics/yolov5/issues/268

**Comment by glenn-jocher** [comment]
@Grenaf these are included when ONNX models are exported with --simplify:
```
python export.py --include onnx --simplify
```

**Comment by Grenaf** [comment]
> @Grenaf these are included when ONNX models are exported with --simplify:
> 
> ```
> python export.py --include onnx --simplify
> ```

thank you sir！it works！
