### ISSUE TITLE
Custom Data Training Issue

### ISSUE THREAD

**Issue by DundieDev** [ultralytics/yolov5#424]
I am using Google Colab to train and test my network. I have been working with it the past few days and following your tutorial which worked fine.

I wanted to create my own dataset. So I labeled all my images using LabelImg (I set format to Yolo). I ended up with 20 classes. So I created a data.yaml file (down below) in where I put my nc to 20. I edited the yolov5m.yaml to match those 20 classes.

But whenever I want to start the training process I get this error:

```
Traceback (most recent call last):
  File "train.py", line 405, in <module>
    train(hyp)
  File "train.py", line 168, in train
    assert mlc < nc, 'Label class %g exceeds nc=%g in %s. Correct your labels or your model.' % (mlc, nc, opt.cfg)
AssertionError: Label class 20 exceeds nc=20 in /content/drive/My Drive/ColabNotebooks/yolov5m.yaml. Correct your labels or your model.
```

I am starting it with this command:
`!python train.py --img 640 --batch 16 --epochs 50 --data /content/yolov5/data.yaml --cfg /content/drive/My\ Drive/ColabNotebooks/yolov5m.yaml --weights  ''`

My data.yaml looks like this:

```
train: ./train/images
val: ./valid/images

nc: 20
names: [ 'Class 1', 'Class 2', 'Class 3', 'Class 4', 'Class 5', 
'Class 6', 'Class 7', 'Class 8', 'Class 9', 'Class 10', 
'Class 11', 'Class 12', 'Class 13', 'Class 14', 'Class 15', 
'Class 16', 'Class 17', 'Class 18', 'Class 19', 'Class 20' ]
```

I don't have any idea what I have to do. I have been working on this problem for a day or two and still don't have any clue.

Any help appreciated!

**Comment by DundieDev** [comment]
Okay, even when I changed in `yolov5m.yaml` the `nc: 30`. The same error occurs...

In my data.yaml I still have nc set to 20. And there are 20 classes in the names section...

When I change in my `data.yaml` file the `nc: 30`, I get this output:

```
Traceback (most recent call last):
  File "train.py", line 405, in <module>
    train(hyp)
  File "train.py", line 72, in train
    assert len(names) == nc, '%g names found for nc=%g dataset in %s' % (len(names), nc, opt.data)  # check
AssertionError: 20 names found for nc=30 dataset in /content/yolov5/data.yaml
```

Any help appreciated.

**Comment by xevolesi** [comment]
Hi, @DundieDev !
Try to check all your .txt files for incorrect class ids. Maybe it helps.

**Comment by glenn-jocher** [comment]
@DundieDev it's very simple. You labelled your dataset as including nc: 20, but your labels include classes>19. The error message already states this. See https://docs.ultralytics.com/yolov5/tutorials/train_custom_data

**Comment by glenn-jocher** [comment]
> Okay, even when I changed in `yolov5m.yaml` the `nc: 30`. The same error occurs...
> 
> In my data.yaml I still have nc set to 20. And there are 20 classes in the names section...
> 
> When I change in my `data.yaml` file the `nc: 30`, I get this output:
> 
> ```
> Traceback (most recent call last):
>   File "train.py", line 405, in <module>
>     train(hyp)
>   File "train.py", line 72, in train
>     assert len(names) == nc, '%g names found for nc=%g dataset in %s' % (len(names), nc, opt.data)  # check
> AssertionError: 20 names found for nc=30 dataset in /content/yolov5/data.yaml
> ```
> 
> Any help appreciated.

As the error message states, you've declared that your dataset has 30 classes, but you've supplied 20 names. This will not fly for obvious reasons.

**Comment by poorneshwaran** [comment]
Hi,
And I have the same issue as AssertionError: Label class 7 exceeds nc=7 in ./models/yolov5l.yaml. Correct your labels or your model.  I print mlc gives 7.0. but as per function condition mlc < nc .

**Comment by glenn-jocher** [comment]
@poorneshwaran see https://docs.ultralytics.com/yolov5/tutorials/train_custom_data#2-create-labels

As it says, class numbers are zero-indexed. 7 classes require labels 0-6.

**Comment by glenn-jocher** [comment]
I've updated the assert error message to explain this more clearly.

**Comment by poorneshwaran** [comment]
Hi glenn,
  I've prepared the dataset labels like 0-6. but the errors are the same. so I print mlc which gives 7 and the condition follows mlc<nc.

**Comment by glenn-jocher** [comment]
@poorneshwaran you have incorrect labels, you need to fix your labels. nc=7 mean s your labels can span 0-6.

**Comment by bipulneupane** [comment]
I get the similar error while trying to train for 1 class.

`Traceback (most recent call last):`
` File "train.py", line 456, in <module>`
`   train(hyp, opt, device, tb_writer)`
`  File "train.py", line 171, in train`
`    assert mlc < nc, 'Label class %g exceeds nc=%g in %s. Possible class labels are 0-%g' % (mlc, nc, opt.data, nc - 1)`
`AssertionError: Label class 2 exceeds nc=1 in ./data/traffic.yaml. Possible class labels are 0-0`

My code for training: `!python train.py --img 640 --batch 16 --epochs 10 --data ./data/traffic.yaml --cfg ./models/yolov5s.yaml --weights '' --nosave --cache`

How first 4 lines of yolov5s.yaml looks like:
`# parameters`
`nc: 1  # number of classes`
`depth_multiple: 0.33  # model depth multiple`
`width_multiple: 0.50  # layer channel multiple`

How traffic.yaml looks like:
`# train and val datasets (image directory or *.txt file with image paths)`
`train: ./data/image`
`val: ./data/val_image`
`test: ./data/test_image`

`# number of classes`
`nc: 1`

`# class names`
`names: ['vehicle']`

I have checked all my label text files to look for errors, which i am 99.9% sure of. Is there anything else to do if i am training for 1 class? Any help would be given a millions of thanks.

**Comment by bipulneupane** [comment]
> 
> 
> I get the similar error while trying to train for 1 class.
> 
> `Traceback (most recent call last):`
> ` File "train.py", line 456, in <module>`
> ` train(hyp, opt, device, tb_writer)`
> ` File "train.py", line 171, in train`
> ` assert mlc < nc, 'Label class %g exceeds nc=%g in %s. Possible class labels are 0-%g' % (mlc, nc, opt.data, nc - 1)`
> `AssertionError: Label class 2 exceeds nc=1 in ./data/traffic.yaml. Possible class labels are 0-0`
> 
> My code for training: `!python train.py --img 640 --batch 16 --epochs 10 --data ./data/traffic.yaml --cfg ./models/yolov5s.yaml --weights '' --nosave --cache`
> 
> How first 4 lines of yolov5s.yaml looks like:
> `# parameters`
> `nc: 1 # number of classes`
> `depth_multiple: 0.33 # model depth multiple`
> `width_multiple: 0.50 # layer channel multiple`
> 
> How traffic.yaml looks like:
> `# train and val datasets (image directory or *.txt file with image paths)`
> `train: ./data/image`
> `val: ./data/val_image`
> `test: ./data/test_image`
> 
> `# number of classes`
> `nc: 1`
> 
> `# class names`
> `names: ['vehicle']`
> 
> I have checked all my label text files to look for errors, which i am 99.9% sure of. Is there anything else to do if i am training for 1 class? Any help would be given a millions of thanks.

I found out that some of my image were jpg and some png. I converted all images into jpg and the training ran without error.

**Comment by djalusic** [comment]
@bipulneupane, I had the same problem and noticed that there's a flag `single-cls` so try adding that to the command.

**Comment by mycuriosity123** [comment]
I suppose the error is bcz of mismatch in number classes in .yaml file and annotated(.txt) file classes

**Comment by THANGAKOWSALYA** [comment]
how to solve this


[Capture](https://user-images.githubusercontent.com/94602905/143854597-db6b9f8d-14d4-4d67-aa07-6d21f1bb8245.PNG)
`

**Comment by glenn-jocher** [comment]
@THANGAKOWSALYA your code may be out of date. To update:

- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

**Comment by X3nX3n** [comment]
> I am using Google Colab to train and test my network. I have been working with it the past few days and following your tutorial which worked fine.
> 
> I wanted to create my own dataset. So I labeled all my images using LabelImg (I set format to Yolo). I ended up with 20 classes. So I created a data.yaml file (down below) in where I put my nc to 20. I edited the yolov5m.yaml to match those 20 classes.
> 
> But whenever I want to start the training process I get this error:
> 
> ```
> Traceback (most recent call last):
>   File "train.py", line 405, in <module>
>     train(hyp)
>   File "train.py", line 168, in train
>     assert mlc < nc, 'Label class %g exceeds nc=%g in %s. Correct your labels or your model.' % (mlc, nc, opt.cfg)
> AssertionError: Label class 20 exceeds nc=20 in /content/drive/My Drive/ColabNotebooks/yolov5m.yaml. Correct your labels or your model.
> ```
> 
> I am starting it with this command: `!python train.py --img 640 --batch 16 --epochs 50 --data /content/yolov5/data.yaml --cfg /content/drive/My\ Drive/ColabNotebooks/yolov5m.yaml --weights ''`
> 
> My data.yaml looks like this:
> 
> ```
> train: ./train/images
> val: ./valid/images
> 
> nc: 20
> names: [ 'Class 1', 'Class 2', 'Class 3', 'Class 4', 'Class 5', 
> 'Class 6', 'Class 7', 'Class 8', 'Class 9', 'Class 10', 
> 'Class 11', 'Class 12', 'Class 13', 'Class 14', 'Class 15', 
> 'Class 16', 'Class 17', 'Class 18', 'Class 19', 'Class 20' ]
> ```
> 
> I don't have any idea what I have to do. I have been working on this problem for a day or two and still don't have any clue.
> 
> Any help appreciated!

I don't know if this will help anyone. I had the same problem. I read the code and added another class to dataset.yaml and to the list of classes in labels that I don’t use in training, it’s just there so that the "mlc <nc" condition would be satisfied and apparently it solved the problem for me ... At the moment, the network is still learning and I can't say for sure, but judging by train_batch0.png, the classes were defined correctly.

**Comment by glenn-jocher** [comment]
@RuslanChokawi if you have 20 classes your label indices can only be 0-19. The Train Custom Dataset tutorial covers this clearly:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TFLite, ONNX, CoreML, TensorRT Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

Good luck 🍀 and let us know if you have any other questions!

**Comment by X3nX3n** [comment]
> @poorneshwaran you have incorrect labels, you need to fix your labels. nc=7 mean s your labels can span 0-6.

I'm sorry, but are you sure that the condition should be "mlc <nc" and not "mlc <= nc"? I have the same number of classes in yaml and classes.txt, and I get the same error: "Label class 25 exceeds nc = 25 in. \ Data \ mydataset.yaml. Possible class labels 0-24" However, if I add to these files one class, which will be in them but will not be marked in any image, everything seems to work. Thanks!

**Comment by glenn-jocher** [comment]
@RuslanChokawi this is very simple. 25 classes are zero indexed 0-24 in your labels.txt files.

**Comment by X3nX3n** [comment]
> @RuslanChokawi this is very simple. 25 classes are zero indexed 0-24 in your labels.txt files.


I understand this, but I don't understand why it doesn't work. I have the same number of classes, I have been doing all sorts of checks all day today, but later looking into the code, I applied this solution (probably quite wild) and it worked. Perhaps tomorrow I will try to solve it somehow more adequately. I'll go through my classes again. But everything looks as it should. I switched yesterday from yolov3, but I'm not sure if this is the case.

**Comment by X3nX3n** [comment]
I think I'm doing something wrong, but I can't figure out what yet.

**Comment by kuangxiaoye** [comment]
I solved this problem: Don't change labimg's class.txt arbitrarily

**Comment by mfwz247** [comment]
> 

Can you please provide more information?

**Comment by kuangxiaoye** [comment]
> > 
> 
> Can you please provide more information?

This error happened to me because, when I finished  to label the picture by labimg software, I modified the label files content directly in the folder generated by labimg.

To fix this error.

Before labeling, I follow the regular order set the label in labimg, and label, import YOLO, this error disappeared.

**Comment by epenaintecol** [comment]
check your classes.txt taken by LabelImg. it is possible you have 21 classes instead of 20 (20 created by you and an aditional class classes.txt had by default)

**Comment by MaMie-creator** [comment]
Traceback (most recent call last):
  File "train.py", line 616, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 78, in train
    nc = 1 if opt.single_cls else int(data_dict['nc'])  # number of classes
KeyError: 'nc'


Please help me to fix this problem,
I have 4 classes that is declared in .yaml file, it works in yolov5 but error in yolov7, please help

**Comment by xzkeee** [comment]
if you change the class number, delete all the cache files in the data folder, otherwise will have this error

**Comment by saqibshinwari777** [comment]
hello! i trained yolov7 on custom dataset and have two classses it work fine .. and show the class name and confidence ... but when i try i on 5 classes dataset then only index of the class is shown ... not the class name.. every thank is perfect like yaml file ete.. so please help to show the class name and probabilty when detecting 5 class dataset

**Comment by saqibshinwari777** [comment]
> hello! i trained yolov7 on custom dataset and have two classses it work fine .. and show the class name and confidence ... but when i try i on 5 classes dataset then only index of the class is shown ... not the class name.. every thank is perfect like yaml file ete.. so please help to show the class name and probabilty when detecting 5 class dataset
![train_batch3 (1)](https://user-images.githubusercontent.com/117894556/213184076-1d62ab26-72ac-40bb-b568-e31d8c699b08.jpg)

**Comment by dhp2015** [comment]
IS there any method to increase the output length? I could only get a answer of approximately 160 words (~250 tokens) right now. thanks

**Comment by glenn-jocher** [comment]
@dhp2015 hello! To show the class names and probabilities when detecting a 5-class dataset, ensure the following:

1. In your `data.yaml` file, set `nc: 5` and provide the names for your 5 classes.

2. Confirm that the model is using the correct `yolov5.yaml` configuration file with the 5 classes specified.

If everything is properly set and you are still only seeing class indices, please provide the command you are using for inference and the contents of your `data.yaml` and modified `yolov5.yaml` files for further assistance.

Thank you!

**Comment by AshDrift98** [comment]
if the classes start from 1 and end at 20, shouldn't the "nc" be 19. it starts from zero right?
