### ISSUE TITLE
True Divide Error

### ISSUE THREAD

**Issue by JINO-ROHIT** [ultralytics/yolov5#4243]
Im facing an error while I try to run inference on videos.

![yolov5](https://user-images.githubusercontent.com/63234112/127695499-677b940a-5537-4bc7-802f-f9da3c200499.png)

Here is a link to the colab file . I hope this should help you figure the issue out
https://colab.research.google.com/drive/1s2357c2qd5xDs_AS3U5LM3NnQjpcSXfb?usp=sharing

Thanks

**Comment by shershunov** [comment]
Specify the weights.

**Comment by JINO-ROHIT** [comment]
Im using the yolov5s during training and using the best model during inference
