### ISSUE TITLE
Results: What does a FP of 1.0 mean in the confusion matrix?

### ISSUE THREAD

**Issue by FleetingA** [ultralytics/yolov5#4246]
Hello, 

I am having a hard time interpreting the resulting confusion matrix after training. What does the FP value of 1 mean?

![confusion_matrix](https://user-images.githubusercontent.com/78978040/127734187-9403141a-3ba6-4120-978f-3acb2b932bd2.png)

**Comment by glenn-jocher** [comment]
@FleetingA columns are normalized, all FPs belong to CMB class.

**Comment by FleetingA** [comment]
Thank you, does that mean that the following interpretation is
correct? True positive rate (TPR) or sensitivity is 61%. FN denotes
proportion of false negatives (i.e., 39%), or cases where the model did not
predict a CMB falsely.

**Comment by glenn-jocher** [comment]
@FleetingA see https://en.wikipedia.org/wiki/Confusion_matrix
