### ISSUE TITLE
hellow everyone, I have a question about pytorch version

### ISSUE THREAD

**Issue by jielingao** [ultralytics/yolov5#4247]
## ❔Question
How can I use the pytorch 1.6 to run the yolov5
## Additional context
I see the requirements.txt said version of torch need >=1.7, but I found some blog using torch1.6 successfully,so, I want to know which branch is support torch1.6 or how I can the model to suit torch1.6
please help me

**Comment by zhiqwang** [comment]
There are some operators (such as `nn.SiLU`) deeply dependent on PyTorch 1.7, I think it is better to upgrade your PT version.
