### ISSUE TITLE
How to change frame size and differen webcam?

### ISSUE THREAD

**Issue by Laudarisd** [ultralytics/yolov5#425]
Hello @glenn-jocher thanks for a wonderful work. I am able to run training on customize datasets.
I think these questions are bit silly to ask here . 

## ❔Question
Q.1) How can I change cam frame size while doing inference in live web cam?
I tried to change like this but didn't work for me.

```
 #w = int(vid_cap.get(cv2.CAP_PROP_FRAME_WIDTH))
 #h = int(vid_cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
 w = int(vid_cap.get(3840))
 h = int(vid_cap.get(2160))

# Did this too:
w = int(3840)
 h = int(2160)
```

Q.2) How to run inference when there is second camera? For e.g ,I tried to do inference with  '-source 0' in my notebook and it opens on notebook camera. I want to open another camera which is connected to notebook. I tried `-source 1` but it didn't work. 

## Additional context
Thank you.
Apologies for the inconvenience.

**Comment by jinzishuai** [comment]
@Laudarisd  Have you figured out the second camera question? I have a similar need as in #836.  Thanks.

**Comment by glenn-jocher** [comment]
@Laudarisd if you are talking about display size, this is between you and opencv, we do not alter that in this repo. If you are referring to inference size, you control that by `python detect.py --img 640` for example.

**Comment by OmkarShidore** [comment]
@Laudarisd
I was stuck on the same thing, you can change camera size during inference in LoadStream.

`cap = cv2.VideoCapture(s) `
`cap.set(cv2.CAP_PROP_FRAME_WIDTH, 3840) #change width here`
`cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 2160) #change width here`
`w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))`
`h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT`

Similarly, you can also change the fps of the stream.

**Comment by OmkarShidore** [comment]
> @Laudarisd Have you figured out the second camera question? I have a similar need as in #836. Thanks.

I couldn't either. But I found a workaround for Windows.
Just disable the camera that you don't want to use in the "device manager" application on windows.
Only enable the one that you want to use and use as the default source.
`--source 0`
