### ISSUE TITLE
Is my model overfit ? Image attached

### ISSUE THREAD

**Issue by thusinh1969** [ultralytics/yolov5#4250]
## ❔Question
Can someone help that if this model is overfit and I should stop it ? Sorry I do not know how to embed image apart from Google link.

![yolo](https://user-images.githubusercontent.com/35662216/127743685-aa33b9c9-f4e4-4a26-aac0-94439e2e4855.png)

[https://drive.google.com/file/d/1dJsaph9Y2-ONLDILb831bZJIFba7aUqk/view?usp=sharing](https://drive.google.com/file/d/1dJsaph9Y2-ONLDILb831bZJIFba7aUqk/view?usp=sharing)

Dataset OpenImage, 65 class. Default Yolov5 no change (YoloV5x transfered, image size 640x640). Training is at EPOCH 48.

Thanks
Steve

**Comment by glenn-jocher** [comment]
@thusinh1969 you can place an image just by dragging and dropping it in your message.
