### ISSUE TITLE
Training speed and memory

### ISSUE THREAD

**Issue by pangkun248** [ultralytics/yolov5#4252]
I noticed your instructions about training,
Run commands below to reproduce results on COCO dataset (dataset auto-downloads on first use). Training times for YOLOv5s/m/l/x are 2/4/6/8 days on a single V100 (multi-GPU times faster). Use the largest --batch-size your GPU allows (batch sizes shown for 16 GB devices).
I want to train from scratch on the coco dataset.(A100 x1).The code was just downloaded.

The following is the situation during my training.The specific parameters can be seen in the screenshot.
python train.py --cfg models/yolov5s.yaml --data data/coco.yaml --device 0 --batch-size 64    -> 16min/epoch
python train.py --cfg models/yolov5s.yaml --data data/coco.yaml --device 0 --batch-size 128  ->16min/epoch
python train.py --cfg models/yolov5s.yaml --data data/coco.yaml --device 0 --batch-size 192  ->20min/epoch
python train.py --cfg models/yolov5s.yaml --data data/coco.yaml --device 0 --batch-size 192 --workers 16->16min/epoch
![sendpix7](https://user-images.githubusercontent.com/39581901/127759471-a110c68f-d1d4-4580-afd2-ae8c8a17ef4a.jpg)
My question
1. Why I increased the batch size but the time required for training did not decrease
2. The relationship between workers and batch size, because I noticed that you seem to set it to a maximum of 8 in the code (why it is 8),
3. When epoch=0 and 1, the GPU memory has changed, about x1.5? What may be the reason for this,

**Comment by glenn-jocher** [comment]
@pangkun248 I don't understand what you're asking, what training speed differences are you referring to?

**Comment by pangkun248** [comment]
I trained with a batch size of 64 128 192 and found that the training time did not significantly decrease.

**Comment by pangkun248** [comment]
> @pangkun248 I don't understand what you're asking, what training speed differences are you referring to?

@glenn-jocherI used a batch size of 64 128 192 for training, and found that the training time did not decrease significantly with the batch size. And also found some GPU memory changes when epoch=0 and 1. I don't quite understand why this happens, can you help me?Or some opinions?

**Comment by glenn-jocher** [comment]
@pangkun248 batch size speed increases are most noticeable for small batch sizes, i.e. moving from 8 to 16 to 32. Going from 128 to 192 will not produce significant speed increases.

Note for fastest trainings you can --cache if you have sufficient RAM:
```
python train.py --cache
```

**Comment by pangkun248** [comment]
ths，I will try this
