### ISSUE TITLE
How to do multimodal fusion on yolov5?

### ISSUE THREAD

**Issue by kim1ng** [ultralytics/yolov5#4258]
## ❔Question
Thanks for repo! 

I want to do multimodal fusion on yolov5 and try to get higher preditction accuracy. I have RGB images and depth images which are aligned. Now here is my idea:

I want to train two  yolov5s, one for RGB images and the other for depth images. And I want to contact them at some level of the network. Thus there should be 2 training datasets for the whole model. How can I do to train two models at the same time and do mid-term fusion?

Any advice is appreciated. Thank you!

**Comment by glenn-jocher** [comment]
@dabifan that sounds terribly complicated. Why not just train on 4 channel images?

**Comment by kim1ng** [comment]
@glenn-jocher Thanks for the reply.
We have tried the early-fusion(4 channel images) on our datasets, and that didn't help. To make better use of the "D" information, we want to try the idea above.
Instead of fusing the RGB and depth images into 4 channel before input, is that possible for me to take tow parallel inputs and then do some processing before 'Focus module' ? Maybe do it in datasets.py ? 
Thanks again!

**Comment by glenn-jocher** [comment]
@dabifan well yes of course, you can do anything you want, though It's unclear of any added value you'd be introducing with customized architectures that aren't available via the traditional channels of compound scaling etc. If you know of publications demonstrating these benefits you might refer to those, in the absence of prior art you would simply be doing high risk research, so suitable for academia but not for industry I would say.

**Comment by kim1ng** [comment]
@glenn-jocher thanks for the advice! I'll keep trying! It's very nice of you!
