### ISSUE TITLE
How to understand DWConv？

### ISSUE THREAD

**Issue by fzhq** [ultralytics/yolov5#4259]
## ❔Question
In Yolov5，g=math.gcd(c1, c2)，which is different from the Depthwise convolution I saw (g=c1). I’m confused and I don’t know what to make of it. I am looking forward to hearing from you.
## Additional context
def DWConv(c1, c2, k=1, s=1, act=True):
    return Conv(c1, c2, k, s, g=math.gcd(c1, c2), act=act)

**Comment by glenn-jocher** [comment]
@fzhq this is obviously a generalizable implementation that works for any c1 and c2, and which reduces to your understanding of a DW conv when c1==c2.
