### ISSUE TITLE
Can we save the yolov5 result into different directory..?

### ISSUE THREAD

**Issue by vishal-nasre** [ultralytics/yolov5#4261]
## I am trying to run a custom trained yolov5 model into local.

My requirement is to save the results i.e. exp, exp1, exp2 .... files into some different directory.

I tried to make changes into the detect.py file but still, it is saving the result into the default directory.

## Can we do that by providing a path while running code below code..?

python detect.py --weights C:/Users/Dell/Desktop/best.pt --source 0 --img 416 --conf 0.4 --save-txt

**Comment by glenn-jocher** [comment]
@vishal-nasre start with the detect.py argparser arguments:
https://github.com/ultralytics/yolov5/blob/cd540d8625bba8a05329ede3522046ee53eb349d/detect.py#L201-L226

**Comment by canek13** [comment]
Yes. This [answer](https://stackoverflow.com/a/75469942/13668282) on stackoverflow may help you.

**Comment by glenn-jocher** [comment]
Thanks @canek13 for the reference! You can use the `--project` argument in `detect.py` to specify a project directory for saving results. For example, `--project your_custom_dir` will save the results in `runs/detect/your_custom_dir`.

For more details, refer to https://docs.ultralytics.com/yolov5/commands#detect
