### ISSUE TITLE
How to save a live video executed by USB 0 as a file?

### ISSUE THREAD

**Issue by Choikyungho9** [ultralytics/yolov5#4263]
Is there a function to record the screen running with a webcam in yolov5?

I want to record it in the middle while detecting it in real time and save it as an mp4 file or avi file.

I think you can use the im0 variable, but it doesn't work.

**Comment by glenn-jocher** [comment]
@Choikyungho9 seems pretty easy:

```python
import torch
from PIL import ImageGrab

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, custom

# Images
img = ImageGrab.grab()  # or file, Path, PIL, OpenCV, numpy, list

# Inference
results = model(img)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
results.show()
```

![tmpnssxhj8t copy](https://user-images.githubusercontent.com/26833433/127848313-48f28ec5-bb4f-4fa1-9801-6d79e0a113c3.jpg)

**Comment by Choikyungho9** [comment]
thank you so much
