### ISSUE TITLE
How can we do Hard negative mining?

### ISSUE THREAD

**Issue by akashAD98** [ultralytics/yolov5#4265]
is there any way to do hard negative mining? to reduce FP?

**Comment by iceisfun** [comment]
Have you tried adding background images

https://docs.ultralytics.com/tutorials/training-tips-best-results/

**Comment by akashAD98** [comment]
yes i did,, I added 1% of  background images of total data, still, results are not that much good, lots of FP are there

**Comment by glenn-jocher** [comment]
@akashAD98 see https://docs.ultralytics.com/tutorials/training-tips-best-results

**Comment by akashAD98** [comment]
@glenn-jocher what's the view on sample_weighting techniques? can we implement this in Yolo ?[https://openaccess.thecvf.com/content_CVPR_2020/papers/Cai_Learning_a_Unified_Sample_Weighting_Network_for_Object_Detection_CVPR_2020_paper.pdf](url)

**Comment by glenn-jocher** [comment]
@akashAD98 I think you're confusing problems with solutions. The correct solution to FPs is increased background images as @iceisfun has pointed out and as our tutorial explains. I would suggest you read and implement it in its entirety.
https://docs.ultralytics.com/tutorials/training-tips-best-results

**Comment by akashAD98** [comment]
@glenn-jocher  just I want to know any other methods apart from this. But I understood. Thnaks

**Comment by glenn-jocher** [comment]
@akashAD98 increase confidence threshold

**Comment by daikankan** [comment]
I also think it's important, especially for the sampling strategy and the loss design, yolov5 is good, and it can be better, but the improvement for it seems slow down.
