### ISSUE TITLE
select_device always return CUDA:0

### ISSUE THREAD

**Issue by LeoSouquet** [ultralytics/yolov5#4278]
## ❔Question

Hi Guys,

Quick question, is it normal that the function **select_device** is always returning CUDA:0 ?
For instance, in the export, if I specify --device 1, the chose device will always be the 0.

https://github.com/ultralytics/yolov5/blob/621caea53c393ca8b46261d369a6314f7d2736d7/utils/torch_utils.py#L91

Thank in advance,

Léo

**Comment by glenn-jocher** [comment]
@LeoCyclope os.environ['CUDA_VISIBLE_DEVICES'] is set to whatever device you pass in select_device() so that index 0 can be assigned to any device on your machine. The console printout is device accurate:

```
python train.py --device 5

YOLOv5 🚀 v5.0-330-g18f6ba7 torch 1.9.0+cu102 CUDA:5 (Tesla V100-SXM2-16GB, 16160.5MB)
```

**Comment by LeoSouquet** [comment]
Alright, thanks for the Precision.

My bigger issue comes from the TorchScript export.
On a multi-GPU machine, when I try to load different TorchScript models (for inference) on different GPU, they all go to the cuda:0 GPU.

My intuition is that the jit trace, registers the trace as the cuda:0 and therefore I get an error trying to infer on the CUDA:1 because the Image and some tensors are not on the same device.

I cannot find much on the matter.
Have you, in your experience, be able to load multiple torchscript models on multiple GPU at the same time? 

Thanks so much in advance,

Regards,

**Comment by glenn-jocher** [comment]
@LeoCyclope I've never used torchscript myself.

**Comment by iceisfun** [comment]
I had this same issue and its still on my list.

It seems to be an issue with the export script, did not dig into it enough to find out as it was not super important for what I was working on.

Would you post back if you find the issue?
