### ISSUE TITLE
warmup bias LR

### ISSUE THREAD

**Issue by vishnubanna** [ultralytics/yolov5#4279]
## has anyone done a comparison test to determine how much the bias LR in warm up affects the models performance?
has anyone done a comparison test to determine how much the bias LR in warm up affects the models performance?

## Additional context
so in warm up the bias LR drops from 0.1 to 0.01 over 3 epochs and all the other parameter groups will grow the 0.0 to 0.01. If this did not occur how much would the AP change?

**Comment by vishnubanna** [comment]
@glenn-jocher

**Comment by glenn-jocher** [comment]
@vishnubanna I would run the experiment yourself to determine the answer to your question.
