### ISSUE TITLE
Can I close the Evolving anchors function?

### ISSUE THREAD

**Issue by liuchangji** [ultralytics/yolov5#428]
## Additional context

when training sets scale different from test sets,evolved anchors may lower performance?

**Comment by glenn-jocher** [comment]
Anchors are evolved on training data only, not test data. You can disable autoanchor:

python train.py —noautoanchor

**Comment by liuchangji** [comment]
> Anchors are evolved on training data only, not test data. You can disable autoanchor:
> 
> python train.py —noautoanchor

thank u vert much !!!

**Comment by liuchangji** [comment]
> Anchors are evolved on training data only, not test data. You can disable autoanchor:
> 
> python train.py —noautoanchor

when i detect,do I need to set new-get anchor in some .yaml file,or new anchor has been saved in .pt?

**Comment by glenn-jocher** [comment]
@liuchangji autoanchor saves any updated anchors to your model.pt file, but it will not update your model.yaml file. You can update your model.yaml manually if you'd like to use the same anchors in the future.

**Comment by liuchangji** [comment]
> @liuchangji autoanchor saves any updated anchors to your model.pt file, but it will not update your model.yaml file. You can update your model.yaml manually if you'd like to use the same anchors in the future.

thank you for all your help!
