### ISSUE TITLE
How to start with training on single class/class that is not in MS COCO

### ISSUE THREAD

**Issue by Michelvl92** [ultralytics/yolov5#4286]
## ❔Question

I want to train a yolov5 model on a new class (let's call it class 'AAA'), that does not exist in the MS COCO classes. In the dataset that I have only the objects of class 'AAA' is labeled, and for most of the images, it also contains objects that exist in MS COCO (but are not labeled). 

**My goal:** detect as good as possible objects of class 'AAA' with as least as possible false positives. Detecting other objects is not a priority, e.g. a model with 1 class that can only detect one class suffices, but also a model with 81 that can detect all the MS COCO (even with bad performance) classes including class 81 'AAA' (but that one as good as possible).

**What is unclear to me:** in the above case, should case, should I construct a model (from the pre-trained) with only one class (If yes, how should I achieve this?: in my --data *.yaml file setting NC = 1, and is it needed to set option: --single-cls ? and/or should more settings set/changed?
Or should I just train a (from the pre-trained)  by adding one class to the 80 default classes, and then retrain?

**What I already tried:** Started with the default pre-trained model yolov5x.pt, set the in my --data *.yaml file setting NC = 1, and further used the default (training) settings. Finally, after 300 epochs, my best model was able to achieve around 0.9mAP on the val set (which is perfect), but totally fails on the real data. It detects extremely many false positives, on objects that almost don't look at class 'AAA' objects, and there are a lot of false positives on where it detects objects as class 'AAA' but actually are objects from the MS COSO dataset. So I am not sure what to do next, or if I missed something. 
I also read the tutorial but was not able to find the answer to my questions.

## Additional context

**Dataset info:**

- Train set: 6400 images, with 17000 objects annotations of class 'AAA' 
- Val set: 1600 images, with 3000 objects annotations of class 'AAA' 
- All contain at least one object of class 'AAA' 
- It could be that there are objects in from the MS COCO class, usually 'person', but those are not annotated
- No background images were used (but is possible)

**Comment by glenn-jocher** [comment]
@Michelvl92 generalization failure modes are invariably due to lack of correlation between your validation space and your deployment space. The solution of course is to align them more closely.

![Screenshot 2021-08-04 at 13 15 05](https://user-images.githubusercontent.com/26833433/128171709-b8de65f3-a5b6-4682-b736-fdd2c46c8867.jpg)

**Comment by eliastemponi** [comment]
Hi @Michelvl92 . I´m facing the same challenge.
Were you able to train you model ?
