### ISSUE TITLE
Will yoloV5 support BiFPN in the future?

### ISSUE THREAD

**Issue by zhongqiu1245** [ultralytics/yolov5#429]
## ❔Question
Hi！Thank you for your wonderful work.
Will yoloV5 support BiFPN in the future?

**Comment by glenn-jocher** [comment]
We are very low on time, if you want to you can modify the yolov5 yaml files for bifpn, see all of the different heads in models/hub

**Comment by zhongqiu1245** [comment]
Thanks for your suggestion
