### ISSUE TITLE
About more pretrained model

### ISSUE THREAD

**Issue by zhang5957** [ultralytics/yolov5#4294]
i have trained yolov5_FPN.yaml,but without pretrained model,it seems really bad.can you provide the pretrained model in  models/hub? or do you have the plan?

**Comment by glenn-jocher** [comment]
@zhang5957 all pretrained models are available from the latest release assets. There are no plans to introduce additional pretrained models.
https://github.com/ultralytics/yolov5/releases/tag/v5.0
