### ISSUE TITLE
When train my custom data, how to load pretrained model? It says not match with default weights.

### ISSUE THREAD

**Issue by h030162** [ultralytics/yolov5#43]

**Comment by glenn-jocher** [comment]
@h030162 can you supply code to reproduce your error please?

**Comment by glenn-jocher** [comment]
@h030162 I just tested this on our colab notebook, and everything works correctly. You can load up an 80 class model with pretrained weights if you are training on coco, or you can change the class count of your model and dataset as well. The only requirement is that the dataset and model class counts must match each other:

Dataset:
https://github.com/ultralytics/yolov5/blob/ad71d2d513dd1cce71b87b72af6c2685709549ad/data/coco128.yaml#L14-L15

Model:
https://github.com/ultralytics/yolov5/blob/ad71d2d513dd1cce71b87b72af6c2685709549ad/models/yolov5s.yaml#L1-L2

If you change nc, everything still works correctly. In this case the model will be composed of pretrained weights except for the output layers, which are no longer the same shape as the pretrained output layers. The output layers will remain initialized by random weights.

**Comment by h030162** [comment]
./yolov5_checkpoint/yolov5_models/yolov5x.pt is not compatible with ./models/yolov5x.yaml. Specify --weights '' or specify a --cfg compatible with ./yolov5_checkpoint/yolov5_models/yolov5x.pt.

I just change yolov5x.yaml nc from 80 to 2. and change yaml file in data .nc from 80 to2. names:["dog", "cat"]

**Comment by glenn-jocher** [comment]
@h030162 I tested this again (a second time) in colab, and everything is still working fine. I updated yolov5x.yaml and coco128.yaml to 160 classes (duplicated the names to reach 160 names), and started training with the following command, all is correct with no problems.

```
python train.py --img 640 --batch 16 --epochs 5 --data ./data/coco128.yaml --cfg ./models/yolov5x.yaml --weights yolov5x.pt
```

See https://docs.ultralytics.com/yolov5/tutorials/train_custom_data

**Comment by ou525** [comment]
@glenn-jocher I also have this problem

**Comment by glenn-jocher** [comment]
@ou525 if this is a bug report, please provide screenshots and **minimum viable code to reproduce your issue**, otherwise we can not help you.
