### ISSUE TITLE
Some questions about the bias initialization of conv in Detect() class

### ISSUE THREAD

**Issue by yusowa0716** [ultralytics/yolov5#4302]
Hi,
I am a layman in object detection and I am studying your source code. 
I noticed that your code initializes the bias of final convolution layer according to the probability, I know the reason for this, but I feel that the formula is slightly different from the original paper, could you explain more? What does 0.6 and 0.99 mean? Why not use -log((1-p)/p) and just use log(p) for obj (i.e. b.data[:, 4])
Many thanks!
 
![image](https://user-images.githubusercontent.com/52536919/128139868-39ce7fca-eea4-4a7b-8236-4a631912391b.png)

**Comment by glenn-jocher** [comment]
@XJTUNR hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by yusowa0716** [comment]
@glenn-jocher Actually, I'm not making a suggestion, I have a question about the initialization of data[:,4] and data[:,5:], can you further explain why they are initialized this way?(i.e. log(0.6/(80-0.01) means what?))

**Comment by glenn-jocher** [comment]
@XJTUNR COCO defaults. If you can quantify improvements using alternative initialization strategies feel free to submit a PR. Thanks!

**Comment by yusowa0716** [comment]
@glenn-jocher I know this is related to the COCO dataset, where can I find these numbers? Or I know that 80 represents the number of categories in COCO, but what is the special meaning of 0.6 and 0.99 and how do they form the probabilities?

**Comment by yusowa0716** [comment]
@glenn-jocher Also, the purpose of the initialization is to make the model output the same as the prior probability after Sigmoid, obviously Sigmoid(log(p)/(1-p) = p, so using the **data[:,4]** as an example, _8/((640/s)**2)_ wants to represent the prior probability of each grid point containing the object, so why use a log for initialization instead of using log(p/(1-p))? Any special insights?

I'm not sure if such changes would improve performance, but I think it would be more logical? I would like to know your intuition for initializing this way, thank you very much for sharing!

**Comment by glenn-jocher** [comment]
@XJTUNR I see your point about the sigmoid(log()) not equating. Not sure where the current implementation originated from then, the detail may have gotten lost on implementation. Can you please submit a PR to correct this? Thanks!
