### ISSUE TITLE
where I can find evolve.png

### ISSUE THREAD

**Issue by besbesmany** [ultralytics/yolov5#4304]
I run train.py --evolve
where I can find yolov5/evolve.png I can't find it after evolve
also the visualization images where to find?

how to change crossover and mutation in train.py?

**Comment by glenn-jocher** [comment]
@besbesmany see console output
<img width="1604" alt="Screenshot 2021-08-04 at 12 59 17" src="https://user-images.githubusercontent.com/26833433/128170098-62d0a6eb-20d0-4bbf-9b47-3da136c61a03.png">

**Comment by besbesmany** [comment]
thank you sir

**Comment by besbesmany** [comment]
`!python train.py --img 640 --batch 16 --epochs 10 --data coco128.yaml --weights yolov5s.pt --cache --evolve`



![21](https://user-images.githubusercontent.com/35992924/128554874-8b11950f-2a32-4b71-a2d3-574eb9cc654a.png)

**Comment by besbesmany** [comment]
how to get evolve.png with the previous error

**Comment by besbesmany** [comment]
how to get evolve.png with the previous error

**Comment by besbesmany** [comment]
what should i do?
