### ISSUE TITLE
question about confusion matrix and background fp=1.0

### ISSUE THREAD

**Issue by iceisfun** [ultralytics/yolov5#4311]
We are getting some unusual background fp numbers

In production this model works fine and we get no background false positives or other issues, I'm just confused about the 1.0 in background FP

Data set size is about 2500 samples in class "100" and about 500 samples in "background", none of the background images have anything resembling "100" data in them.

We have all fixed cameras so its hard to get many more varations on background that are meaningful, and I have similar issues with other models with less extreme examples.

This v5s is trained on 3x rtx titan batch size 30 epochs 15

![confusion_matrix](https://user-images.githubusercontent.com/701891/128299261-5eff4914-d3a0-4a8a-a34f-dcefb9e23c14.png)

mAP_0.5
0.43464
0.81822
0.97134
0.97955
0.97881
0.98231
0.98158
0.98018
0.98318
0.98345
0.98443
0.98497
 0.9871
0.98769
0.98913

**Comment by glenn-jocher** [comment]
All background FPs are class 100
