### ISSUE TITLE
about the training and the meanings with images

### ISSUE THREAD

**Issue by StringMin** [ultralytics/yolov5#4313]
## ❔Question
If you look at the photo, I wonder if the number of images in the green circle below represents the number of vals, not the number of tests.

At the beginning of learning, 3343 train images are often found...
I wonder if I'm doing something wrong

## Additional context

![116B9A8F-37FD-401A-966C-2C68A53EEBB0](https://user-images.githubusercontent.com/78468371/128311689-b05f6b17-d1db-4662-b900-f3fe87d1c582.jpeg)

**Comment by glenn-jocher** [comment]
@StringMin val.py runs on your val set.

**Comment by StringMin** [comment]
If so, I wonder if it's wrong to come out like that in the img
first img is cuted so uploading the again

(I'm sorry. I'm not good at English. If it's like the picture, is it going well? In the second photo log, images shows 920. Is it supposed to be 3343?)

![Screenshot from 2021-08-06 11-43-06](https://user-images.githubusercontent.com/78468371/128448171-c62b470f-7188-4563-b14d-d500f97d4e3f.png)

![Screenshot from 2021-08-05 16-01-25](https://user-images.githubusercontent.com/78468371/128448211-9058929c-af8d-4dff-8be8-1544cee715f4.png)
