### ISSUE TITLE
Transformer trian problem?

### ISSUE THREAD

**Issue by gentlebreeze1** [ultralytics/yolov5#4314]
i change C3 toC3TR in yolov5s.yaml and run at V100.but the error occurred.
`Traceback (most recent call last):
  File "/data/zhangyong/workspace/detect/202185/yolov5-master/train.py", line 601, in <module>
    main(opt)
  File "/data/zhangyong/workspace/detect/202185/yolov5-master/train.py", line 499, in main
    train(opt.hyp, opt, device)
  File "/data/zhangyong/workspace/detect/202185/yolov5-master/train.py", line 323, in train
    scaler.scale(loss).backward()
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/autograd/__init__.py", line 130, in backward
    Variable._execution_engine.run_backward(
RuntimeError: CUDA out of memory. Tried to allocate 9.77 GiB (GPU 0; 31.75 GiB total capacity; 19.68 GiB already allocated; 8.24 GiB free; 22.14 GiB reserved in total by PyTorch)
`
myyolov5s.yaml is
`backbone:
  # [from, number, module, args]
  [[-1, 1, Focus, [64, 3]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C3TR, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 9, C3TR, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, C3TR, [512]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 1, SPP, [1024, [5, 9, 13]]],
   [-1, 3, C3TR, [1024, False]],  # 9
  ]

# YOLOv5 head
head:
  [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, C3, [512, False]],  # 13

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, C3, [256, False]],  # 17 (P3/8-small)

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 14], 1, Concat, [1]],  # cat head P4
   [-1, 3, C3, [512, False]],  # 20 (P4/16-medium)

   [-1, 1, Conv, [512, 3, 2]],
   [[-1, 10], 1, Concat, [1]],  # cat head P5
   [-1, 3, C3, [1024, False]],  # 23 (P5/32-large)

   [[17, 20, 23], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
  ]
`
how to train transformer?

**Comment by ohjunee** [comment]
try to reduce your --batch-size

**Comment by guyiyifeurach** [comment]
Hi, your original question is because the batch-size is too big, you can reduce it, so memory cost on CUDA can reduce.
As more, how your journey with transformer training, I'm also interested in it.
