### ISSUE TITLE
How to know that when does overfitting is achieved?

### ISSUE THREAD

**Issue by jaskiratsingh2000** [ultralytics/yolov5#4319]
HI @glenn-jocher As it has been mentioned within the Yolov5 wiki of "Getting Best results" - 

> Epochs. Start with 300 epochs. If this overfits early then you can reduce epochs. If overfitting does not occur after 300 epochs, train longer, i.e. 600, 1200 etc epochs.

https://github.com/ultralytics/yolov5/wiki/Tips-for-Best-Training-Results#training-settings So how do I know that overfitting is achieved? and how can I work on it accordingly?
Also, can you please let me know the above thing is more explanatory, please?

@glenn-jocher @batrlatom Please please let me know.

**Comment by batrlatom** [comment]
Hi, you know that overfitting occurs in case your training set has high precision, but your validation set does not. It basically means that it can recognize pictures it was trained on well, but when the neural network see new pictures, it cannot predict correctly.

**Comment by jaskiratsingh2000** [comment]
@batrlatom So basically I am just trying to relate the overfitting thing with this issue that why I am getting the different mAP value. https://github.com/ultralytics/yolov5/issues/4167 I thought it might be an issue with the overfitting on Raspberry Pi. How can I overcome that?

Actually, the Accuracy Performance results I got on the Raspberry Pi were these 

```
               Class     Images     Labels          P          R     mAP@.5
                 all       5000      36335    0.00188    0.00106   0.000142   6.02e-05
```

**Comment by batrlatom** [comment]
It probably is not an overfitting problem if the only thing you changed was the computer. So can you send example of results from PC and from raspi on the same picture?

**Comment by jaskiratsingh2000** [comment]
@batrlatom Please find the results below:

### Server

**Accuracy Performance (mAP) computed on Server:**

mAP value = **0.564**

```
val: data=./data/coco.yaml, weights=['yolov5s.pt'], batch_size=32, imgsz=640, conf_thres=0.001, iou_thres=0.6, task=val, device=, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=True, project=runs/val, name=exp, exist_ok=False, half=False
/home/arani/anaconda3/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Unexpected error from cudaGetDev
iceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibil
ity was attempted on non supported HW (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
YOLOv5 🚀 v5.0-290-g62409ee torch 1.8.1+cu102 CPU
Fusing layers... 
Model Summary: 224 layers, 7266973 parameters, 0 gradients, 17.0 GFLOPs
val: Scanning '../datasets/coco/val2017.cache' images and labels... 4952 found, 48 missing, 0 empty, 0 corrupted: 100%|█| 5000/5000 [00:00<?, ?
             Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|████████████████| 157/157 [07:29<00:00,  2.87s/it]
                 all       5000      36335      0.663      0.521      0.564      0.363
Speed: 0.4ms pre-process, 76.0ms inference, 8.4ms NMS per image at shape (32, 3, 640, 640)

Evaluating pycocotools mAP... saving runs/val/exp2/best_predictions.json...
loading annotations into memory...
Done (t=0.44s)
creating index...
index created!
Loading and preparing results...
DONE (t=6.85s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=98.08s).
Accumulating evaluation results...
DONE (t=17.18s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.376
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.572
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.405
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.222
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.428
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.476
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.309
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.517
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.568
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.377
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.629
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.708
```


### Ubuntu Machine

Accuracy Performance (mAP) computed on Ubuntu Machine:

mAP value = **0.564**

```
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████████| 157/157 [1:49:30<00:00, 41.85s/it]
                 all       5000      36335      0.668      0.518      0.564      0.363
Speed: 4.0ms pre-process, 1273.3ms inference, 21.3ms NMS per image at shape (32, 3, 640, 640)
```


### Raspberry Pi 4

**Accuracy Performance (mAP) computed on Raspberry Pi 4:**

mAP value = **0.000127**

```
val: Scanning '../datasets/coco/val2017' images and labels...4952 found, 48
val: New cache created: ../datasets/coco/val2017.cache
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.               Class     Images     Labels          P          R     mAP@.               Class     Images     Labels          P          R     mAP@.               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5
                 all       5000      36335    0.00163    0.00058   0.000127   6.94e-05
Speed: 6.2ms pre-process, 2178.0ms inference, 248.3ms NMS per image at shape (32, 3, 640, 640)

Evaluating pycocotools mAP... saving runs/val/exp6/best_predictions.json...
loading annotations into memory...
Done (t=1.73s)
creating index...
index created!
Loading and preparing results...
DONE (t=20.32s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=125.62s).
Accumulating evaluation results...
DONE (t=55.08s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.001
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.001
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.001

```

Please let me know if you can help in this. That would be of great help.

**Comment by batrlatom** [comment]
I see the warning in the raspi detections. NMS time limit 10.0s exceeded . Could be this the problem? Maybe the code just do not get the response in time and marks the results as bad. Just try to dig in to the code, find where this 10s limit happens and try to increase it. I am not in front of computer now, so please do it yourself. I can take a look at the code after the weekend myself. 

If this is because of speed, you have few options.

1) lower the resolution
2) try to increase the timeout limit if this is really the problem which causes the mAP computation problem
3) ditch raspi and go with jetson nano or jetson nx

**Comment by jaskiratsingh2000** [comment]
@batrlatom The thing is that I actually don't want to work on Jetsan nano but Raspberry Pi. I would also check my own but I would also look forward to recieve your response on above. I would really appreciate your tim in this because this seems to be a serious problem for the Raspberry Pi,

@batrlatom The above 2 points you mentioned where do I need to make change for these? in val.py?

**Comment by jaskiratsingh2000** [comment]
Hi @batrlatom I hope you are doing good. So I tried what you mentioned in the this discussion here - https://github.com/ultralytics/yolov5/discussions/3430#discussioncomment-1144135 but I still got the same results and there was not any improvement in that

```
val: data=./data/coco.yaml, weights=['runs/train/exp/weights/best.pt'], batch_size=32, imgsz=640, conf_thres=0.001, iou_thres=0.6, task=val, device=, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=True, project=runs/val, name=exp, exist_ok=False, half=False
YOLOv5 🚀 v5.0-290-g62409ee torch 1.7.0a0+e85d494 CPU

Fusing layers... 
Model Summary: 224 layers, 7266973 parameters, 0 gradients, 17.0 GFLOPs
val: Scanning '../datasets/coco/val2017.cache' images and labels... 4952 fo
               Class     Images     Labels          P          R     mAP@.5
               Class     Images     Labels          P          R     mAP@.5
                 all       5000      36335      0.053    0.00138   0.000123   4.76e-05
Speed: 7.2ms pre-process, 1578.8ms inference, 502.9ms NMS per image at shape (32, 3, 640, 640)

Evaluating pycocotools mAP... saving runs/val/exp8/best_predictions.json...
loading annotations into memory...
Done (t=1.74s)
creating index...
index created!
Loading and preparing results...
DONE (t=32.39s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=330.25s).
Accumulating evaluation results...
DONE (t=90.23s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.001
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.001
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.001
Results saved to runs/val/exp8
```

@batrlatom Need your input and help here please let me know if possible. Would highly appreciate that. Thanks

**Comment by jaskiratsingh2000** [comment]
@batrlatom Do you think that it might be an issue of precision?

**Comment by batrlatom** [comment]
I do not have any other idea honestly. I think that best would be trying some solutions from other guys who participate in export competition.

**Comment by jaskiratsingh2000** [comment]
@batrlatom Do yo think it would be the issue of the overfitting? How can I check the overfitting issue? 

Also, @batrlatom I am still not able to understand the key thing that what is the difference between the current YOLO v5 and the exported YOLO v5. Because this is somehow important for me to understand.

Actually I am researcher working on the "Scalable Vehicle Detection on Edge Devices" hence making it work on the Raspberry Pi is the key. So any help in this would be great.

The people in export function have not implemented any such functionality to know such Accuracy Performance. So your response would be highly appreciable

**Comment by batrlatom** [comment]
This is probably not overfitting, since mAP on your other devices looks fine and the model and images are the same.

**Comment by jaskiratsingh2000** [comment]
@batrlatom Also as you mentioned previously that you would be looking into code after week2nd. Did you get a chance for it?

**Comment by batrlatom** [comment]
yes I looked at the code, I found exactly where it is necessary to change the value for 10 seconds and I wrote that to you. Since I do not own raspi now, I am unable to help you more. But as soon as I get my hands on raspi, I will try it.

**Comment by jaskiratsingh2000** [comment]
@batrlatom okay. These were the results computed by changing 10 seconds to 900 seconds.
Also I have a question that why do you think it is not the issue of overfitting?

Also one thing more I realized that do you think it could be an issue of training on GPU memory? 
On line #129 in val.py it says that half-precision is only supported on cuda 
During training we consumed the “gpu” memory and since Raspberry Pi is ARM cpu devices so maybe training it on the “cpu” memory might resolve this solution - https://github.com/ultralytics/yolov5/blob/771ac6c53ded79c408ed8bd99f7604b7077b7d77/train.py#L435

But bot sure if this could be an issue. Any idea on this?

**Comment by batrlatom** [comment]
I think that this would not be an overfitting problem since you have good results on normal pc ( I think you posted something like 0.5 +/- mAP ) . 

About the GPU, the raspi do not have a cuda enabled GPU, it runs the torch on the CPU. You can see that on this piece of text

```
val: data=./data/coco.yaml, weights=['runs/train/exp/weights/best.pt'], batch_size=32, imgsz=640, conf_thres=0.001, iou_thres=0.6, task=val, device=, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=True, project=runs/val, name=exp, exist_ok=False, half=False
YOLOv5 🚀 v5.0-290-g62409ee torch 1.7.0a0+e85d494 CPU
```
Training on GPU and inference on CPU is normal procedure and should not raise any problems

**Comment by Killuagg** [comment]
![results](https://github.com/ultralytics/yolov5/assets/168774427/908be8d1-3f4d-4920-8a25-f42ea9d9ff08)
Does my result have overfitting problem. Its a good result based on my image?

**Comment by glenn-jocher** [comment]
Hi @Killuagg,

Thank you for sharing your results! Based on the provided image, it looks like your model is performing well, but let's delve a bit deeper to ensure we cover all bases regarding overfitting.

### Identifying Overfitting

Overfitting typically occurs when your model performs significantly better on the training data compared to the validation data. Here are some key indicators to look for:

1. **Training vs. Validation Loss**: If your training loss continues to decrease while your validation loss starts to increase, this is a classic sign of overfitting.
2. **mAP (mean Average Precision)**: A high mAP on the training set but a significantly lower mAP on the validation set can indicate overfitting.
3. **Precision-Recall (PR) Curve**: A PR curve that shows high precision and recall on the training set but not on the validation set can also be a sign.

### Recommendations

1. **Check Training and Validation Metrics**: Ensure you are monitoring both training and validation losses, mAP, and PR curves. These metrics are typically located in your `runs/train/exp` directory.
2. **Increase Dataset Size**: If possible, increase the number of images and instances per class in your dataset. More data can help mitigate overfitting.
3. **Data Augmentation**: Use data augmentation techniques to artificially increase the diversity of your training data.
4. **Regularization Techniques**: Consider techniques like dropout or weight decay to prevent overfitting.
5. **Early Stopping**: Implement early stopping to halt training when the validation loss stops improving.

### Training on GPU vs. Inference on CPU

As you mentioned, training on a GPU and performing inference on a CPU is a common practice and should not inherently cause issues. However, ensure that your model is correctly exported and optimized for CPU inference, especially for edge devices like the Raspberry Pi.

### Further Reading

For more detailed tips on achieving the best training results, please refer to our [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips//) guide.

If you have any further questions or need additional assistance, feel free to ask. The YOLO community and the Ultralytics team are here to help!

**Comment by Killuagg** [comment]
!python val.py --data data.yaml --weights "C:\Users\King\NewClasses2\yolov5\runs\train\exp44\weights\best.onnx" --device cpu --task=test --iou-thres 0.7

![PR_curve](https://github.com/ultralytics/yolov5/assets/168774427/e07d3b20-128c-4fdf-bf6f-e03d190a2e13)
May i know.Why in the picture the iou still 0.5?

**Comment by glenn-jocher** [comment]
Hi @Killuagg,

Thank you for reaching out and providing the command and PR curve image. Let's address your concern about the IoU threshold.

### Understanding IoU Threshold in PR Curve

The IoU threshold you set in the command (`--iou-thres 0.7`) is used to determine whether a prediction is considered a true positive during evaluation. However, the PR curve you shared appears to be generated with an IoU threshold of 0.5. This discrepancy might be due to the default settings used in the visualization tools.

### Steps to Verify and Resolve

1. **Verify IoU Threshold in Evaluation**:
   Ensure that the IoU threshold is correctly applied during the evaluation. You can check the evaluation logs to confirm that the IoU threshold is set to 0.7.

2. **Update to Latest Versions**:
   Make sure you are using the latest versions of `torch` and `yolov5`. Sometimes, issues are resolved in newer releases:
   ```bash
   pip install --upgrade torch
   git pull https://github.com/ultralytics/yolov5
   ```

3. **Re-evaluate with Correct IoU Threshold**:
   Re-run the evaluation command and ensure the IoU threshold is correctly set:
   ```bash
   python val.py --data data.yaml --weights "C:\Users\King\NewClasses2\yolov5\runs\train\exp44\weights\best.onnx" --device cpu --task test --iou-thres 0.7
   ```

4. **Check PR Curve Generation**:
   If the PR curve is generated separately, ensure that the IoU threshold used for generating the curve matches the one used during evaluation.

### Minimum Reproducible Example

If the issue persists, please provide a minimum reproducible code example. This will help us investigate the problem more effectively. You can refer to our guide on creating a minimum reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

### Additional Resources

For more detailed tips on achieving the best training results and understanding evaluation metrics, please refer to our [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips//) guide.

Feel free to reach out if you have any further questions or need additional assistance. The YOLO community and the Ultralytics team are here to help! 😊

**Comment by Killuagg** [comment]
When i command !python val.py --data data.yaml --weights "C:\Users\King\NewClasses2\yolov5\runs\train\exp44\weights\best.onnx" --device cpu --task=test --iou-thres 0.8 
The graph on the right side for all classes show mAP@0.5. Its a fixed already?

![image](https://github.com/ultralytics/yolov5/assets/168774427/4442b42a-e561-4ae4-9c58-6282dbbcf4f5)
The process show IoU threshold 0.8.


 What i mean, can the graph show mAP@0.8 on the right side? or it already fixed for mAP@0.5
![image](https://github.com/ultralytics/yolov5/assets/168774427/f38db08c-5fde-41ae-b47d-02539e382978)

**Comment by glenn-jocher** [comment]
Hi @Killuagg,

Thank you for your detailed question and for sharing the images! 😊

### Understanding mAP and IoU Thresholds

The mAP (mean Average Precision) metric is typically reported at a standard IoU threshold of 0.5 (mAP@0.5) and across a range of IoU thresholds from 0.5 to 0.95 (mAP@0.5:0.95). This is a common practice in object detection to provide a comprehensive evaluation of the model's performance.

### Customizing IoU Threshold for mAP Calculation

To answer your question: the graph on the right side showing mAP@0.5 is standard and fixed in the current visualization. However, you can calculate and visualize mAP at different IoU thresholds, such as 0.8, by customizing the evaluation script.

### Steps to Calculate mAP@0.8

1. **Modify the Evaluation Script**:
   You can modify the `val.py` script to calculate mAP at a specific IoU threshold. Here’s a snippet to help you get started:

   ```python
   # In val.py, around line 129, modify the IoU threshold for mAP calculation
   iouv = torch.linspace(0.5, 0.95, 10).to(device)  # default IoU thresholds
   iouv = torch.tensor([0.8]).to(device)  # set to 0.8 for mAP@0.8
   ```

2. **Run the Evaluation**:
   After modifying the script, run the evaluation command again:
   ```bash
   python val.py --data data.yaml --weights "C:\Users\King\NewClasses2\yolov5\runs\train\exp44\weights\best.onnx" --device cpu --task test --iou-thres 0.8
   ```

### Verify Latest Versions

Please ensure you are using the latest versions of `torch` and `yolov5` to avoid any potential issues:
```bash
pip install --upgrade torch
git pull https://github.com/ultralytics/yolov5
```

### Minimum Reproducible Example

If you encounter any issues, please provide a minimum reproducible code example. This will help us investigate the problem more effectively. You can refer to our guide on creating a minimum reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any further questions or need additional assistance. The YOLO community and the Ultralytics team are here to help! 😊

**Comment by Killuagg** [comment]
Based on previous example i show you. If i using Iou threshold 0.8 with command
 python val.py --data data.yaml --weights "C:\Users\King\NewClasses2\yolov5\runs\train\exp44\weights\best.onnx" --device cpu --task test --iou-thres 0.8
 Does the result generate before produce with IoU-threshold 0.8? eventhough on graph show mAP@0.5?

**Comment by Killuagg** [comment]
My lecturer ask me to get new test dataset that have been annotated and test to my model. He ask me to change the value of iou threshold. To change the value of iou threshold just with command like before without changing any to the code inside the val.py file?

**Comment by glenn-jocher** [comment]
Hi @Killuagg,

Thank you for your question! 😊

To address your lecturer's request, you can indeed change the IoU threshold for evaluation without modifying the `val.py` script. The command you provided will set the IoU threshold to 0.8 for the evaluation:

```bash
python val.py --data data.yaml --weights "C:\Users\King\NewClasses2\yolov5\runs\train\exp44\weights\best.onnx" --device cpu --task test --iou-thres 0.8
```

### Clarification on mAP@0.5 in Graphs

The mAP@0.5 value shown in the graphs is a standard metric that is always calculated and displayed, regardless of the IoU threshold you set for evaluation. This means that even if you set `--iou-thres 0.8`, the mAP@0.5 will still be calculated and shown in the results for consistency and comparison purposes.

### Generating mAP@0.8

If you specifically need to see the mAP at IoU=0.8, you can look at the detailed evaluation results printed in the console or saved in the results files. The command you used will ensure that the evaluation considers predictions with an IoU threshold of 0.8 as true positives.

### Steps to Verify

1. **Run the Evaluation**:
   Execute the command with the desired IoU threshold:
   ```bash
   python val.py --data data.yaml --weights "C:\Users\King\NewClasses2\yolov5\runs\train\exp44\weights\best.onnx" --device cpu --task test --iou-thres 0.8
   ```

2. **Check the Results**:
   After running the evaluation, check the console output and the results files (typically saved in the `runs/val/exp` directory) for detailed metrics, including mAP at different IoU thresholds.

### Additional Resources

For more detailed tips on achieving the best training results and understanding evaluation metrics, please refer to our [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips//) guide.

If you have any further questions or need additional assistance, feel free to ask. The YOLO community and the Ultralytics team are here to help! 😊

**Comment by Killuagg** [comment]
I already change the Iou threshold with different value with command val.py --iou-thres <value>. In the console output, mostly the value are only small difference. Does the value is correct and logically?
![image](https://github.com/ultralytics/yolov5/assets/168774427/a63f6940-8f8f-4449-b442-8fb6d90e8ab1)

**Comment by glenn-jocher** [comment]
Hi @Killuagg,

Thank you for your question and for sharing the console output image! 😊

### Understanding IoU Threshold Impact

The IoU (Intersection over Union) threshold determines the criteria for a prediction to be considered a true positive. Changing the IoU threshold can affect the evaluation metrics, but the impact might not always be drastic, especially if your model is well-calibrated and consistently making accurate predictions.

### Small Differences in mAP

It's not uncommon to see only small differences in mAP (mean Average Precision) when adjusting the IoU threshold. This can happen if your model's predictions are generally close to the ground truth, meaning that slightly stricter or looser criteria (changing IoU threshold) don't significantly alter the evaluation outcome.

### Steps to Verify

1. **Ensure Latest Versions**:
   Please verify that you are using the latest versions of `torch` and `yolov5` to ensure you have the latest features and bug fixes:
   ```bash
   pip install --upgrade torch
   git pull https://github.com/ultralytics/yolov5
   ```

2. **Check Detailed Metrics**:
   Review the detailed metrics in the console output and the results files (typically saved in the `runs/val/exp` directory). These files provide a comprehensive breakdown of the evaluation metrics at different IoU thresholds.

### Minimum Reproducible Example

If you believe there might be an issue or bug, please provide a minimum reproducible code example. This will help us investigate the problem more effectively. You can refer to our guide on creating a minimum reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

### Additional Resources

For more detailed tips on achieving the best training results and understanding evaluation metrics, please refer to our [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips//) guide.

Feel free to reach out if you have any further questions or need additional assistance. The YOLO community and the Ultralytics team are here to help! 😊
