### ISSUE TITLE
How to use sample weight and resize the labeled data

### ISSUE THREAD

**Issue by jasonyeong** [ultralytics/yolov5#4326]
## ❔Question

As title, may I know how to use sample weight in YoloV5? And how to resize all labeled data to same size before training, not image size.

Also, can YoloV5 detect the labeled data(.yaml) by predict each bounding box and give the score.

**Comment by wudashuo** [comment]
All the answers are in https://github.com/ultralytics/yolov5/wiki

**Comment by jasonyeong** [comment]
> All the answers are in https://github.com/ultralytics/yolov5/wiki

Is that "python val.py ..." for detect the labeled data(.yaml) by predict each bounding box?
But apart from this, I didn't find any other relevant information about my question...
