### ISSUE TITLE
How could I test my model?

### ISSUE THREAD

**Issue by EslamHaourn** [ultralytics/yolov5#4329]
## ❔Question
Got 0 precision and recall with unlabeled test set
## Additional context
when I train on kitti dataset and got best.pt weights file and use this file to test my model on more than 7.5k images I got zero results.
Thanks.

**Comment by EslamHaourn** [comment]
Kindly, any help would be appreciated.

**Comment by G-Apple1** [comment]
> Kindly, any help would be appreciated.

Do you solute the problem?

**Comment by rlaferla** [comment]
I have the same question.  The tutorial/documentation is missing this basic information.  Please answer us and let's update the docs to show everyone how to test against newly trained data.

**Comment by glenn-jocher** [comment]
@EslamHaourn metrics are meaningless on unlabelled data obviously.

**Comment by EslamHaourn** [comment]
@glenn-jocher Yes you are right. Thanks.
@rlaferla The kitti test set is available only in their website.
