### ISSUE TITLE
Jetson Nano implementation with tensor-rt

### ISSUE THREAD

**Issue by tanejaaryan** [ultralytics/yolov5#4330]
## ❔Question

- Can someone guide me through the modifications that are required to use the tensor-rt optimisations for Yolov5?
- Could you also help as to how to implement the tensor-rt packages into a Jetson nano (or similar device)?

**Comment by MTDzi** [comment]
@tanejaaryan check out [this](https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5) project, the Cpp version works on my Nano like a charm (both in terms of speed and memory usage), although I have to admit the Python inference script does not (eats out all available memory).

Let me know if this helps.

**Comment by moritz157** [comment]
@MTDzi What speeds did you achieve? I'm testing this myself right now and would like to know what to expect in order to compare it to my results.

**Comment by MTDzi** [comment]
@moritz157 I don't have my Nano to reproduce the results now, but this is what I remember:
1. my images were smaller, 128 x 128 I think
2.  I saw around 15 ms / image, so it's roughly 67 FPS
These are probably not the exact numbers but hopefully it gives you a rough idea of what to expect.

I should have the option to check if everything I wrote checks out, but it'll be on Monday.
You can ping me then, if you're still interested.

Also: I'm curious what numbers you managed to get.

**Comment by moritz157** [comment]
@MTDzi Thanks for you reply :)

I've got around 145ms / image with an image size of 640x427.
