### ISSUE TITLE
overlap

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#4336]
If the person overlap, how to label it？
The detection will detect one object.
![image](https://user-images.githubusercontent.com/59388989/128604813-ce59d14d-063e-41e2-a4b3-42a678c971b0.png)

**Comment by iceisfun** [comment]
With IoU and NMS

https://towardsdatascience.com/non-maximum-suppression-nms-93ce178e177c

You can adjust these settings to best fit your needs


Also the NMS function has groups to allow mixed groups of classes with their own NMS

https://github.com/ultralytics/yolov5/blob/master/utils/general.py#L508

**Comment by alicera** [comment]
Is the case also the  IoU and NMS problem？
I test some image and find the status that if the network have two classes and sometime it will detect the object with the same box and different classes.
Like this
the image is  the label.
![image](https://user-images.githubusercontent.com/59388989/128623500-d8dd15db-f292-4797-9a74-ccae710a6970.png)

the image is the detect
![image](https://user-images.githubusercontent.com/59388989/128623555-eadaf98f-adea-477c-973b-7655031994dc.png)

**Comment by iceisfun** [comment]
Have you tried different values for iou_thres?

https://github.com/ultralytics/yolov5/blob/e96c74b5a1c4a27934c5d8ad52cde778af248ed8/detect.py#L119

Also are you trying to detect multiple overlapping classes at the same time? The same function applies however you have to tell the non_max_suppression which classes to look for using classes array as a parameter.

**Comment by alicera** [comment]
when training, the status can set iou ?
![image](https://user-images.githubusercontent.com/59388989/129310833-937c76e1-0e9b-4fd4-88b5-9dbefbcca8e2.png)
