### ISSUE TITLE
Turning detect.py into a .exe

### ISSUE THREAD

**Issue by Sven-Erick** [ultralytics/yolov5#434]
## ❔Question
I hope you are well.

I've got a question about creating an executable using YOLOv5. How do we go about to convert the detect. py script to an .exe? I have tried using Pyinstaller and cx_Freeze but this gives PyInstallerImportError: Failed to load dynlib/dll "caffe2_detectron_ops_gpu.dll". Your feedback will be highly appreciated. 
Thank you

Kind regards

**Comment by WelkinU** [comment]
In your PyInstaller .spec file, try adding caffe2_detectron_ops_gpu.dll to the binaries.

Example:
binaries=[('path\\to\\your\\caffe2_detectron_ops_gpu.dll' , '.')]

Note: If you use a conda environment the path should be similar to:
[ANACONDA_ROOT]\\envs\\[ENV_NAME]\\Lib\\site-packages\\torch\\lib\\caffe2_detectron_ops_gpu.dll

**Comment by Sven-Erick** [comment]
Thank you for your response @WelkinU . I have added the .DLL path to the binary and still gives the same issue. I've added --paths "path containing the .DLL", this then changed the error to PyInstallerImportError: Failed to load dynlib/dll "caffe2_nvrtc.dll"
Using Windows 10 build 18363.959
Anaconda
Pyinstaller 3.6
Torchvision 0.2.2. Post 3
Pytorch 1.5.1
Cuda 10.2
Cuda toolkit 10.1.243

**Comment by hi-one-gg** [comment]
> @WelkinU 답변 감사합니다 . 바이너리에 .DLL 경로를 추가했지만 여전히 동일한 문제가 발생합니다. --paths "path 포함 .DLL"을 추가하면 PyInstallerImportError: Failed to load dynlib/dll "caffe2_nvrtc.dll"
> Using Windows 10 build 18363.959
> Anaconda
> Pyinstaller 3.6
> Torchvision 0.2.2. Post 3
> Pytorch 1.5.1
> Cuda 10.2
> Cuda 툴킷 10.1.243

I've met he error too. How to solve?
