### ISSUE TITLE
how to do different augmentation

### ISSUE THREAD

**Issue by besbesmany** [ultralytics/yolov5#4342]
I need example of how to make augmentation
like moasic, flip ,...
what to change exactly

**Comment by mxy5201314** [comment]
look at train_batch0~3.jpg

**Comment by glenn-jocher** [comment]
@besbesmany augmentations are defined in your hyperparameter file:
![YOLOv5 augmentation](https://user-images.githubusercontent.com/26833433/129057300-e3b06048-9911-4fdc-8cba-0c449a993f62.jpg)

**Comment by besbesmany** [comment]
what is the name of hyperparameter file?
how to call it in train.py?

**Comment by glenn-jocher** [comment]
@besbesmany 
```bash
python train.py --hyp data/hyps/hyp.scratch.yaml
```

**Comment by besbesmany** [comment]
> @besbesmany
> 
> ```shell
> python train.py --hyp data/hyps/hyp.scratch.yaml
> ```

If I didn't use  `--hyp` in `train.py `
so there won't be augmentation at all, right?

**Comment by glenn-jocher** [comment]
@besbesmany you might want to familiarize yourself with the python argparser in train.py.
