### ISSUE TITLE
Better is_docker() detection

### ISSUE THREAD

**Issue by philippneugebauer** [ultralytics/yolov5#4346]
Currently, the is_docker() detection is quite poor and I was running into issues.

I found an alternative approach to https://github.com/ultralytics/yolov5/blob/e78aeac973ea3a2c58d7577453473e48f4e7a0f6/utils/general.py#L94-L96

http://youdidwhatwithtsql.com/how-to-tell-if-youre-in-a-docker-container/2466/

What do you think about it?

**Comment by iceisfun** [comment]
In our code we are already checking /proc/self/cgroup for docker and all of our yolov5 services are running in containers.

**Comment by iceisfun** [comment]
Something like this?

This is how I do it right now and it works on all of our vision servers running docker and testing on workstations returns the correct results.

Perhaps other people could run it to make sure there are no issues before opening a pr

```
def is_docker():
    with open('/proc/self/cgroup', 'rb') as f:
        data = f.read().decode()
        try:
            return len(data.split('\n')[0].split('/')) >= 3
        except IndexError as e:
            return False
    return False
```

**Comment by glenn-jocher** [comment]
@philippneugebauer @iceisfun hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
