### ISSUE TITLE
what  style="rect2" or "rect4" means in the code ?

### ISSUE THREAD

**Issue by jingenyan** [ultralytics/yolov5#435]
## ❔Question
what  style="rect2" or "rect4" means in the code ?

**Comment by SISTMrL** [comment]
have you understood the meaning of rect2 and rect4?

**Comment by jingenyan** [comment]
@SISTMrL sorry i dont understand,can you tell me

**Comment by SISTMrL** [comment]
> @SISTMrL sorry i dont understand,can you tell me

sorry i don't understand

**Comment by jingenyan** [comment]
@SISTMrL i know the function，but dont know why call  the name

**Comment by zugofn** [comment]
> ## grey_questionQuestion
> 
> what style="rect2" or "rect4" means in the code ?

Hello,maybe you can see this blog for your question:https://blog.csdn.net/cdknight_happy/article/details/109817548#t11
