### ISSUE TITLE
Flag to keep original image with augmentations

### ISSUE THREAD

**Issue by Ridhwanluthra** [ultralytics/yolov5#4353]
## 🚀 Feature

Add flag to enable keeping original image and adding a new augmented image to the dataset during runtime.

## Motivation

I am working with a small dataset and it makes sense to increase the number of images going into training. The idea is to keep the original image and also the augmented image and send both into the training pipeline.

## Pitch

When data augmentation takes place we simply append the augmented images instead of having them replace the original.

## Alternatives

Do this step before training and disable augmentations internally but that's quite tedious and would use a lot of disk space.

**Comment by glenn-jocher** [comment]
@Ridhwanluthra YOLOv5 augmentation never reuses the same image twice. Offline copying and changing of your images before training serves no purpose as far as I can tell.

![YOLOv5 augmentation](https://user-images.githubusercontent.com/26833433/129052393-34559256-7310-4e3e-a00d-e9b575c9b1ec.jpg)

**Comment by Ridhwanluthra** [comment]
@glenn-jocher if I take a very simple idea of just flip augmentations. What I want is that when an image is read the model is trained on both the original image and the flipped image effectively increasing the size of our dataset. My understanding is that this would be useful when I have a small dataset
