### ISSUE TITLE
self.sort_obj_iou

### ISSUE THREAD

**Issue by HuKai97** [ultralytics/yolov5#4356]
![image](https://user-images.githubusercontent.com/68494594/128708599-ddcc2976-0ad6-4373-94ee-33e3c2c8ff94.png)

why use sort_obj_iou? What is its function？

**Comment by glenn-jocher** [comment]
This sorts objectness IoU.

**Comment by HuKai97** [comment]
Is there any difference between sorting and not sorting？

**Comment by glenn-jocher** [comment]
@coderhukai if there were no difference there would be little point in having two options naturally.

**Comment by xiaomao19970819** [comment]
> Is there any difference between sorting and not sorting？

嗨，同学，你试了吗？这个参数，是否能带来性能提升呢？

**Comment by bilzard** [comment]
@SCAU-HuKai 
The details are explained in #3605 (although I don't understand much of it...). According to this discussion, it was introduced to improve performance in dense object situations.
It also shows the results of an experiment. There seems to be little difference in performance.

**Comment by xiaomao19970819** [comment]
@bilzard  嗨，这个链接下面几位的讨论和我有相同的困惑，这和YOLOv5的loss计算策略有关，我也一直困惑obj损失为什么会被覆盖掉，显然作者也在困惑这样的操作为什么没有带来太大的性能损失，我想这和数据集本身有关，在box比较拥挤的数据集上对obj进行排序后再计算可能性能会提升，总而言之，感谢。

**Comment by bilzard** [comment]
@SCAU-HuKai Sorry, I don't understand Chinese.
This is translation by Deepl:

> Hi, the discussion below this link has the same confusion as me, it is related to the loss calculation strategy of YOLOv5, I also have been confused why the obj loss is overwritten, apparently the author is also confused why such an operation does not bring much performance loss, I think it is related to the dataset itself, the possibility of sorting the obj on the box more crowded dataset and then calculating it. All in all, thanks.

I agree. I also don't understand much about the feature. And personally, I also have an impression of the feature is merged with not well discussed the theoretical background (though I may be misunderstanding). All end all, as it's default-off feature, I think you can neglect this feature if you think it isn't necessary.

**Comment by isJunCheng** [comment]
> @bilzard 嗨，这个链接下面几位的讨论和我有相同的困惑，这和YOLOv5的loss计算策略有关，我也一直困惑obj损失为什么会被覆盖掉，显然作者也在困惑这样的操作为什么没有带来太大的性能损失，我想这和数据集本身有关，在box比较拥挤的数据集上对obj进行排序后再计算可能性能会提升，总而言之，感谢。

I used the sorting function in a custom dataset and the result has a decrease instead. The anchor with multiple sample matches should have higher iou, not be covered by low iou. **The theory is correct, but the experimental result is opposite** and I am puzzled. Can someone help me with this please?
