### ISSUE TITLE
Library version request (pip install xxxxxx)

### ISSUE THREAD

**Issue by leekwunfung817** [ultralytics/yolov5#4358]
## ❔Question
I want to know the version of pip and its needed module, could you please provide this information?
I really need your help.

THANK YOU VERY MUCH!!!!!!!!!!!!

## For example:

python -m pip install pip==XXXXXXXXXXX
pip install wandb==XXXXXXXXXXX torchvision==XXXXXXXXXXX ........................

**Comment by mindraisin** [comment]
it's all in requirements.txt, you can run the code as in the instruction and they will be installed. Any additional modules missing along the way you can run 'pip install [packageName]' as in the error.
