### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by HassanAsghar1** [ultralytics/yolov5#4360]
## ❔Question
I am trying to resume training but unfortunately i am getting  error (see image).Please guide me about this
!python train.py --img 920 --batch 32  --epochs 500 --data customcoco.yaml  --resume /content/yolov5/runs/train/exp/weights/last.pt --save_period 1
## Additional context
Plese guide me about this how to solve it
![Capture 2](https://user-images.githubusercontent.com/72445645/128777094-b83cae9b-10a9-41f7-9b17-bbe38eb6b563.PNG)

**Comment by HassanAsghar1** [comment]
Please guide me about this?i would be very thankful?Thanks

**Comment by uefall** [comment]
pip uninstall wandb

**Comment by glenn-jocher** [comment]
@AyushExel seems to be a W&B related resume problem.

@HassanAsghar1 this region of the code has been updated recently, I would reclone the repo and start training from scratch and let us know if you run into any future issues.

**Comment by AyushExel** [comment]
@HassanAsghar1 I'll try to reproduce this and get back to you. Meanwhile can you make sure you're on the lastest version of the repo?

**Comment by AyushExel** [comment]
OK @HassanAsghar1 I've found the reason for it. It's a bug. I'll put up a fix shortly

**Comment by glenn-jocher** [comment]
@HassanAsghar1 good news 😃! Your original issue may now be fixed ✅ in PR #4388. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by HassanAsghar1** [comment]
Thanks for your support .Yes, now i can resume the training.
