### ISSUE TITLE
yolov5 Using  dji tello video streaming?

### ISSUE THREAD

**Issue by Tiang-88** [ultralytics/yolov5#4364]
## ❔Question
 parser.add_argument('--source', type=str, default='0', help='source')  # file/folder, 0 for webcam

## Here, how to replace the camera of UAV for detection
The following is the acquisition method of UAV video stream
```
from djitellopy import Tello
import cv2, math, time

tello= Tello()
tello.connect()

tello.streamon()
frame_read = tello.get_frame_read()

while True:
    # In reality you want to display frames in a seperate thread. Otherwise
    #  they will freeze while the drone moves.
    img = frame_read.frame
    cv2.imshow("drone", img)

    key = cv2.waitKey(1) & 0xff
    if key == 27: # ESC
        break
```

**Comment by Tiang-88** [comment]
tello is udp video stream

**Comment by Tiang-88** [comment]
？？？？？？

**Comment by glenn-jocher** [comment]
@zzb1967736495 I'm not sure. You may want to ask the package authors at https://github.com/hanyazou/TelloPy
