### ISSUE TITLE
There is always an object of a certain size

### ISSUE THREAD

**Issue by ONNONS** [ultralytics/yolov5#4365]
## ❔Question

There is always an object of a certain size

I know the w x h of this object, and I want to modify it into a network that detects objects of this size first.

Which part should I edit?

please answer about my question..

**Comment by iceisfun** [comment]
I would stop before NMS and evaluate all matches yourself.

I've used this before to help cull partially off screen objects and constrain object sizes for specific cameras.

**Comment by ONNONS** [comment]
I'm sorry but I'm a student with no knowledge
please explain a little more
