### ISSUE TITLE
Fine Tuning my custom data

### ISSUE THREAD

**Issue by xiaowk5516** [ultralytics/yolov5#4367]
## ❔Question
Hi, I trained a yolov5l model on my custom data(single class, about 6000 Annotations). I collect  4000 new images, which are the same class but under the different background. So is it better to finetune my yolov5l model on new data, or retrain the whole images(almost 10000) using the weight file you provided? I will collect more data in the future. looking for your reply!

**Comment by iceisfun** [comment]
It is a small number of images, I would retrain from scratch and also include true background images that do not include any instances of the single class

Making sure your input data is well labeled, diverse and you have background images has yielded the best results for all the work I've done.

See the following article for best practices

https://docs.ultralytics.com/guides/model-training-tips/

**Comment by xiaowk5516** [comment]
@iceisfun thanks! my images are labeled well, and i also added some background images. now I have almost 10000 images, I will collect more images in the future. When i collect 100K images or more, is it a better way to retrain scratch rather than finetune?

**Comment by iceisfun** [comment]
What batch size and epochs are you using? How many gpus?

For my largest model I am just under 100k with 4x A100 it trains in no time, even on 3x RTX Titan it trains quite fast.

**Comment by xiaowk5516** [comment]
@iceisfun batch-size: 16, epochs: 300, gpus: 2*2080ti

**Comment by mahdidrm** [comment]
> @iceisfun batch-size: 16, epochs: 300, gpus: 2*2080ti

Could you please tell me how you labeled over 10,000 images? Is it done by hand or automatically? I am looking forward to find an automatic algorithm or app for labeling my images!
