### ISSUE TITLE
4K Training result worse than 1K resolution

### ISSUE THREAD

**Issue by z430** [ultralytics/yolov5#4368]
## 4K training have bad result
Hi, I was training yolov5s with 4k and have really bad result. I'm using `yolov5s` model and the single class `bird`. The dataset is filtered from COCO dataset, then I trained using `--img-size 3840`.
But, if I trained with `--img-size 1280` the result is pretty good. Here is the result using different image size.
![image](https://user-images.githubusercontent.com/7395320/128832289-8c8148f9-a33e-4072-89c9-bf5018306736.png)

Anyone know why the difference is show high?

**Comment by wudashuo** [comment]
1. It doesn't mean the results will always be better when you increase `img-size`.
2. If you increase `img-size` like 1280 or 4k, you should try yolov5m, l, x, or p6, instead of s.
3. Most important, most of the images in the COCO dataset are below 1080p, why do you use 1280 or 3840 img-size?

**Comment by glenn-jocher** [comment]
@z430 your assumption is flawed, you seem to think that mAP will trend to 1 as --img-size trends to infinity, but all CNN models are built upon fixed stride lengths, i.e. for P6 models the strides are 8, 16, 32 and 64 which serve as the the basic ROIs that the model performs optimally near.
