### ISSUE TITLE
Single class training configurations finetuning.

### ISSUE THREAD

**Issue by AndreasKaratzas** [ultralytics/yolov5#4369]

**Comment by glenn-jocher** [comment]
@AndreasKaratzas if you have 1 class nc=1 naturally.

**Comment by AndreasKaratzas** [comment]
So that means that it does not classify the background like faster r-cnn, right?

**Comment by shekarneo** [comment]
at line no 212 in train.py preventing using single class nc:1
```
assert mlc < nc, f'Label class {mlc} exceeds nc={nc} in {data}. Possible class labels are 0-{nc - 1}'
```

**Comment by glenn-jocher** [comment]
@AndreasKaratzas all anchors are classified by objectness neurons. See YOLOv3 paper for more information.
https://arxiv.org/abs/1804.02767

**Comment by glenn-jocher** [comment]
@shekarneo this line checks your data labels to ensure they are aligned with your data.yaml class count `nc`.
