### ISSUE TITLE
yolov5 classification question, AssertionError: Label class 2.0 exceeds nc=2 in ./data/custom_data.yaml. Possible class labels are 0-1

### ISSUE THREAD

**Issue by HarveyWa** [ultralytics/yolov5#4370]
## Additional context
Hello, I have limited label for 0 or 1 in all samples,but i still encounter this problem during training, could you help me?
    assert mlc < nc, f'Label class {mlc} exceeds nc={nc} in {data}. Possible class labels are 0-{nc - 1}'
AssertionError: Label class 2.0 exceeds nc=2 in ./data/custom_data.yaml. Possible class labels are 0-1

**Comment by wudashuo** [comment]
As it said, you have label 2.0 in your label file.

**Comment by glenn-jocher** [comment]
@HarveyWa the error message is self-explanatory
