### ISSUE TITLE
How to set a (different) probability threshold when running detect.py on unseen data?

### ISSUE THREAD

**Issue by FleetingA** [ultralytics/yolov5#4372]
I am using YOLOv5 to detect cerebral microbleeds on a custom dataset. In order to reduce the probability of the model detecting false positives, I would like to get predictions only above 0.7 (70% certainty). Where can I change this threshold? Would that be the Intersection over Union value in the data > hyperparameters folder > hyp.finetune and hyp.scratch files?

Also, I don't want the value changed for training, only for the detection phase (detect.py).

Thanks in advance!

**Comment by FleetingA** [comment]
@glenn-jocher would you be able to shed any light on the above?

**Comment by glenn-jocher** [comment]
@FleetingA this is a basic argument in detect.py:
https://github.com/ultralytics/yolov5/blob/e7fc27406ab32b9860c9b351b30ca1c47f543433/detect.py#L200-L228
