### ISSUE TITLE
After training, how do you run detect.py with the new data?

### ISSUE THREAD

**Issue by rlaferla** [ultralytics/yolov5#4378]
## ❔Question

After training, how do you run detect.py with the new data?

## Additional context
I followed these directions but it doesn't say how to run/test your newly trained model with say a web cam.  I tried python3 detect.py --source 0 but it didn't work. I suspect I have to add some additional arguments and specify where the new model is.  I don't even know where the training saved the new model.   Bottom line is that the documentation needs an additional section that explains this.

[https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data](url)

**Comment by glenn-jocher** [comment]
@rlaferla 
```
python detect.py --weights path/to/model.pt
```
