### ISSUE TITLE
autolabelling ?

### ISSUE THREAD

**Issue by HuKai97** [ultralytics/yolov5#4380]
Hello, what is the hybrid autolabelling in NMS? Add GT to pred, and the calculated map is much higher. It's not accurate. What is its theory？I don't understand here very well.

![屏幕截图 2021-08-11 115017](https://user-images.githubusercontent.com/68494594/128966844-733924f9-fa54-483b-82d1-d6b25d0d6efc.png)

**Comment by glenn-jocher** [comment]
@coderhukai this is not meant for accurate mAP, it is meant to produce hybrid autolabels (truth + predictions).

**Comment by HuKai97** [comment]
So what are the benefits about hybrid autolabelling?

**Comment by DongLiu001** [comment]
@glenn-jocher Can you further explain the purpose of  producing truth and predictions? The ground truth will supress correct predictions apparently. It seems --_save-hybrid_ works on the senario of not all objects being labelled. Can you give any example of using --_save-hybrid_ ?

Thanks in advance!

**Comment by glenn-jocher** [comment]
@DongLiu001 --save-hybrid adds additional predictions to already-labelled images. Existing labels are retained.

**Comment by HuKai97** [comment]
It sounds a bit like teaching forcing in RNN? Can a probability p be used to control the opening and closing？
