### ISSUE TITLE
Improve fps for single class inferencing

### ISSUE THREAD

**Issue by keshav-staqu** [ultralytics/yolov5#4383]
## ❔Question
Are there any modifications that can be done to improve fps of model for single class inferencing?

## Additional context
I have trained yolov5s on custom data having only one class, I wanted to know if there is any redundant part of the code that can be removed or modified to improve fps, if I am only using it for single class predictions.

**Comment by glenn-jocher** [comment]
@keshav-staqu 👋 Hello! Thanks for asking about **inference speed issues**. YOLOv5 🚀 can be run on CPU (slowest) or [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data) (fastest). If you would like to increase your inference speed some options are:

- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s
- Run on faster GPUs, i.e.: P100 -> V100 -> A100
- Run on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

**Comment by keshav-staqu** [comment]
Hello @glenn-jocher ! I wanted to ask if there are any specific changes that can be done to improve fps with comparable accuracy if I use yolo for predicting only one class. Maybe like reducing number of anchors, or any other similar changes.

**Comment by glenn-jocher** [comment]
no
