### ISSUE TITLE
Post training Dynamic quantization

### ISSUE THREAD

**Issue by Abdulazizbek** [ultralytics/yolov5#4386]
## ❔Question

Did someone tried model **post training dynamic quantization**?
When I quantize, model size is increasing twice and inferencing time is same with FP32 model.

Based on pytorch tutorial (https://pytorch.org/tutorials/recipes/recipes/dynamic_quantization.html , https://pytorch.org/tutorials/recipes/quantization.html) I have tried to dynamic quantize when running `detect.py` :
```
model = attempt_load(weights, map_location=device)
model = torch.quantization.quantize_dynamic(model, {torch.nn.Conv2d, torch.nn.Linear}, dtype=torch.qint8)  #int8 
# model = torch.quantization.quantize_dynamic(model, dtype=torch.qint8)  #int8 
```
I am not sure `{torch.nn.Conv2d, torch.nn.Linear}` ( list of submodule names in model to apply quantization to) is correctly using or not when applying it to YOLO model

Thank you for advances beforehand

**Comment by isishan** [comment]
Same issue. I even checked the dtype using 
`for param in quantized_model.parameters():
    print(param.dtype)`
It is still fp32
Not sure if it is actually quantizing the model
