### ISSUE TITLE
EMA Decay parameters and dataset size

### ISSUE THREAD

**Issue by kazimpal87** [ultralytics/yolov5#4389]
## ❔Question
Hi,
I'm wondering about the EMA decay and how it relates to dataset size. I'm using a dataset many times larger than COCO. I think that not far into the training process, the EMA will have been updated so many times that the value
`d = self.decay(self.updates)`
will be so close to 1 that the EMA model will basically not update.

The decay function has this magic 2000 number in it:
`self.decay = lambda x: decay * (1 - math.exp(-x / 2000))`
which I guess was chosen to fit COCO? With larger datasets, does it make sense to increase this number? Or does it make more sense to lower the decay parameter from 0.9999 to something smaller?

**Comment by glenn-jocher** [comment]
@kazimpal87 this equation is a special YOLOv5 EMA feature I designed myself to force low decay values at the start of training. This results in faster convergence for users that train too few epochs (as users invariable love to do).

This has zero effect on long term training results.
