### ISSUE TITLE
error when visualizing network 

### ISSUE THREAD

**Issue by dongyingchn** [ultralytics/yolov5#439]
## ❔Question
hi, when using ./models/yolo.py to visualize the network, i got a problem as such:

File "xxx/yolov5/models/common.py", line 96, in forward
    return torch.cat(x, self.d)
TypeError: cat() received an invalid combination of arguments - got (Tensor, int), but expected one of:
 * (tuple of Tensors tensors, name dim, *, Tensor out)
 * (tuple of Tensors tensors, int dim, *, Tensor out)

## Additional context
the ./models/yolo.py script is modified by uncommenting certain commands as such:

    if __name__ == '__main__':
        parser = argparse.ArgumentParser()
        parser.add_argument('--cfg', type=str, default='yolov5s.yaml', help='model.yaml')
        parser.add_argument('--device', default='0', help='cuda device, i.e. 0 or 0,1,2,3 or cpu')
        opt = parser.parse_args()
        opt.cfg = check_file(opt.cfg)  # check file
        device = torch_utils.select_device(opt.device)
    
        # Create model
        model = Model(opt.cfg).to(device)
        model.train()

        # Profile
        img = torch.rand(8 if torch.cuda.is_available() else 1, 3, 640, 640).to(device)
        # y = model(img, profile=True)

        # ONNX export
        # model.model[-1].export = True
        # torch.onnx.export(model, img, opt.cfg.replace('.yaml', '.onnx'), verbose=True, opset_version=11)

        # Tensorboard
        from torch.utils.tensorboard import SummaryWriter
        tb_writer = SummaryWriter()
        print("Run 'tensorboard --logdir=models/runs' to view tensorboard at http://localhost:6006/")
        tb_writer.add_graph(model.model, img)  # add model to tensorboard
        tb_writer.add_image('test', img[0], dataformats='CWH')  # add model to tensorboard

**Comment by glenn-jocher** [comment]
@dongyingchn tensorboard visualization is still experimental. If you'd like to make any updates to the code please submit a PR.

You may also use Netron to view *.pt files.
