### ISSUE TITLE
Inter class (multi-label) NMS

### ISSUE THREAD

**Issue by lleye** [ultralytics/yolov5#4390]
The current nms implementation seems to be single class, is there any plan to extend to multi class? from the general utils file i see `multi_label` is false, would setting it to true fix this?

Also for nms itself, which is more stringent (less false negatives) a smaller threshold e.g. 5% or 95%? 

thanks

Also for nms 
@glenn-jocher @NanoCode012

**Comment by glenn-jocher** [comment]
@lleye NMS by default operates on each class independently (as it should).

You can enable class agnostic NMS by setting `agnostic=True`.

**Comment by iceisfun** [comment]
@glenn-jocher Its also true you can group classes together with labels=(1,2) to nms with classes 1 and 2? I tried this for a while combining several models together and ultimately split them into individual models. 

https://github.com/ultralytics/yolov5/blob/63e09fdc480c9398e7b7acb27083907ed29809de/utils/general.py#L508

**Comment by glenn-jocher** [comment]
@iceisfun i'm not sure what you mean. `agnostic=True` will ignore classes during NMS (all classes together), default `agnostic=False` will run NMS for each class independently.

**Comment by iceisfun** [comment]
I mean you have a bunch of classes in a model like people, trucks, cars, vans and you call non_max_suppression for (trucks, cars, vans) and then calling non_max_suppression again for (people)

**Comment by glenn-jocher** [comment]
@iceisfun that's not an option without code customization.

**Comment by lleye** [comment]
@glenn-jocher thanks, `agnostic=True` is what i was looking for.
