### ISSUE TITLE
Rotation and shift in TTA

### ISSUE THREAD

**Issue by FrancoisMasson1990** [ultralytics/yolov5#4394]
## ❔Question
How can we add rotation and shift image into the TTA code ?

**Comment by glenn-jocher** [comment]
@FrancoisMasson1990 I've opened up a feature request for this with albumentations in https://github.com/albumentations-team/albumentations/issues/987

**Comment by FrancoisMasson1990** [comment]
Thanks @glenn-jocher . I will follow that closely
