### ISSUE TITLE
missing and corrupted images

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#4399]
## ❔Question

How can I find the missing and corrupted images？

![image](https://user-images.githubusercontent.com/59388989/129212830-405ece53-691e-4d1e-bc68-6db5ecf1a306.png)

**Comment by glenn-jocher** [comment]
@alicera these are missing labels, which are fine if you have 110 background images.

**Comment by iceisfun** [comment]
I think they should be empty instead of missing if they are background images?

Scanning '/data/dataset/train' images and labels...24504 found, 0 missing, 732 empty, 0 corrupted

**Comment by alicera** [comment]
What is the empty on here?

**Comment by iceisfun** [comment]
Empty would just mean you have a empty .txt file for the label, so its not missing

**Comment by glenn-jocher** [comment]
@iceisfun @alicera maybe it would make more sense to combine these two categories into a single category to avoid confusion, i.e.:
```bash
val: Scanning '../datasets/coco128/labels/train2017.cache' images and labels... 128 found, 0 missing, 2 empty, 0 corrupted: 100% 128/128 [00:00<?, ?it/s]

# replace with:
val: Scanning '../datasets/coco128/labels/train2017.cache' images and labels... 128 found, 2 unlabelled, 0 corrupted: 100% 128/128 [00:00<?, ?it/s]
```

**Comment by glenn-jocher** [comment]
@iceisfun @alicera part of the issue is we've combined image stats with label stats to save space and print less to screen. The way to read this is:

```
val: Scanning '../datasets/coco128/labels/train2017.cache' images and labels... 128 found, 0 missing, 2 empty, 0 corrupted: 100% 128/128 [00:00<?, ?it/s]
```

- 128 images were found
- 128 labels were found (0 missing)
- 2 of the 128 labels were empty (no txt file)
- 0 image-label pairs were corrupt/failed checks (corrupt labels or images are excluded from the dataset)

**Comment by alicera** [comment]
So missing and empty are the same?

missing: it is the background image but no txt file
empty: (no txt file)
