### ISSUE TITLE
Trian coco128 from scratch get 0 mAP

### ISSUE THREAD

**Issue by yxNONG** [ultralytics/yolov5#44]
- GPU = 1080 Ti
 - Python = 3.7.7
 - PyTorch = 1.5
 - numpy = 1.17

thinks for your great job !
i download the coco128 and try to train it from scratch:

python train.py --img 640 --batch 16 --epochs 10 --data ./data/coco128.yaml --cfg ./models/yolov5s.yaml --weights '' --device 4，5，6，7

**The GIou, objectness, Classification work, However, the mAP, Precision and Recall is both 0, in each epoch.**

       5/9     11.1G    0.1098   0.08732     0.117    0.3142       200       640         0         0         0         0    0.1034   0.07643    0.1161

Then, i try to use the pretrained weight:
python train.py --img 640 --batch 16 --epochs 1 --data ./data/coco128.yaml --cfg ./models/yolov5s.yaml --weights yolov5s.pt --device 4，5，6，7

 **in this case, everything work well**

       0/9      7.3G   0.04367   0.07351   0.01972    0.1369       177       640    0.4245    0.7103     0.657    0.4169   0.04242   0.05659   0.01382
     
i get this with the original code.
since i didn't implement the Nvidia Apex, i change the mixed precision training = False 
simply run again and get the same result.( mAP = 0 )

any idea about this ? thanks for your reply.

**Comment by yxNONG** [comment]
i try 50 epoch, get the mAP@50 great then 0 after 15 epoch, the problem is simply due to that train from scratch need more time to converge.

**Comment by glenn-jocher** [comment]
@yxNONG yes you are correct, training from scratch takes longer to converge. Note that when training extremely small datasets like coco128.yaml from scratch, minimum training is 300 epochs, and recommended training is up to 1000 epochs.
