### ISSUE TITLE
Inference image size

### ISSUE THREAD

**Issue by BS-98** [ultralytics/yolov5#4403]
Hi,

I use **Load YOLOv5 from PyTorch Hub** tutorial:
```
import cv2
import torch
from PIL import Image

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Image
img = cv2.imread('person.jpg')[..., ::-1]  # OpenCV image (BGR to RGB)
imgs = [img]  # batch of images

# Inference
results = model(imgs, size=512)  # includes NMS

# Results
print(results.s)
```
My image is 1080x1920x3 size and I want to resize it to 512x512x3 size so I put argument `size=512` in `model`, but when I print `results.s`, which stands for `inference BCHW shape` according to `forward` method in **yolov5/models/common.py**, it returns 
`torch.Size([1, 3, 288, 512])`. 

So I have 2 questions: 
1) Why such height and width?
2) Why it is not 512x512?

**Comment by glenn-jocher** [comment]
@BS-98 why would you want your rectangular image processed in a square shape?

**Comment by BS-98** [comment]
It is quite big image and I have different model where image is resized to 512x512 and I want to compare all models farly

**Comment by iceisfun** [comment]
@glenn-jocher I asked about this earlier, if the aspect ratio of all images is the same why not convert them into square shapes?

When the model has letterboxed area does that not impact how much of the model is used?

**Comment by glenn-jocher** [comment]
@iceisfun rectangular inference is enabled by default in val.py, detect.py, and Hub models from hubconf.py, and can be used for training with `python train.py --rect`.
