### ISSUE TITLE
YoloV5+ Caméra allied vision Vimba

### ISSUE THREAD

**Issue by agnihsv** [ultralytics/yolov5#4408]
## ❔Question
Hello,
I want to use the camera vimba (allied) vision with yolov 5 to detect the objects.
But I don't know how to integrate my python code which allows me to read video streams with my allied vision Mako camera in the yoloV5 code.

I attach my python code which allows me to read the fux video below.

I would really like some help if possible.
from pymba import Vimba
from pymba import VimbaException
import cv2
import sys

def Camera_Set_ROI(camera, W: int, H: int) -> None:
         image_Height = camera.feature("Height")
         image_Width = camera.feature("Width")
         image_Height.value = H
         image_Width.value = W

def init_cameras():
# vimba object
     vimba = Vimba()
# Start vimba system
     vimba.startup()
     vmFactory = vimba.camera_ids()
# Get connected cameras
     cams = [vimba.camera(id) for id in vmFactory]
     if len(cams) == 0:
          raise OSError("No camera present.")
          for idx, device in enumerate(vmFactory):
               print("Device {} ID: {}".format(idx, device))
# Open cameras and print information
     for idx, cam in enumerate(cams):
         try:
            cam.open()
            Camera_Set_ROI(cam, 640, 480)
            cam.arm('SingleFrame')
         except VimbaException as e:
            if e.error_code == VimbaException.ERR_TIMEOUT:
                 print(e)
                 cam.disarm()
                 cam.arm('SingleFrame')
            elif e.error_code == VimbaException.ERR_DEVICE_NOT_OPENED:
                 print(e)
                 cam.open()
                 cam.arm('SingleFrame')
         return cams

def main():
        PIXEL_FORMATS_CONVERSIONS = {'BayerRG8': cv2.COLOR_BAYER_RG2RGB}
        cams = init_cameras()
        flag = True
        while flag:
                try:
                   for idx, cam in enumerate(cams):
                            frame = cam.acquire_frame()
                            img = frame.buffer_data_numpy()
# convert color space if desired
                            if(frame.pixel_format == 'BayerRG8'):
                                      img = cv2.cvtColor(img, PIXEL_FORMATS_CONVERSIONS[frame.pixel_format])
                                      img = cv2.resize(img, (400, 300))
                                      cv2.imshow("Cam {} - {}".format(idx, ["cam{}". format(idx)]), img)
                                      c = cv2.waitKey(5)
                                      if c == ord('q'):
                                                 flag = False
                except KeyboardInterrupt:
                                        sys.exit(1)
                                        for cam in cams:
                                                     cam.disarm()
                                                     cam.close()
        cv2.destroyAllWindows()
        Vimba().shutdown()

if __name__ == '__main__':
                 main()

**Comment by glenn-jocher** [comment]
@agnihsv see PyTorch Hub tutorial:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)
