### ISSUE TITLE
multi scale training

### ISSUE THREAD

**Issue by junliang230** [ultralytics/yolov5#441]
## ❔Question
According to [https://github.com/ultralytics/yolov5/blob/0281c9cd18f064dfb042531d9cb32441752ca224/train.py#L241](https://github.com/ultralytics/yolov5/blob/0281c9cd18f064dfb042531d9cb32441752ca224/train.py#L241), when set opt.multi_scale = True, it seems that only image size is scaled but the targets(boxes in image) is still not changed.  why not adjust  targets(boxes in image) if image has been scaled? thanks your reply

## Additional context
None

**Comment by Laughing-q** [comment]
@breezelj  the boxes in image are normalized to 0~1(x/image_w and y/image_h)，so we don't have to adjust targets.

**Comment by junliang230** [comment]
thanks your reply, I get it

**Comment by hujunchao** [comment]
a good question!
