### ISSUE TITLE
add ghostbottleneck module to yolov5s.yaml

### ISSUE THREAD

**Issue by leoncch** [ultralytics/yolov5#4410]
## ❔Question
when I add ghostbottleneck module to yolov5s.yaml
![image](https://user-images.githubusercontent.com/88910882/129424733-45644bff-048c-4d26-a4b2-ad1e69a11617.png)

## Additional context
# parameters
nc: 2  # number of classes
depth_multiple: 0.33  # model depth multiple
width_multiple: 0.50  # layer channel multiple

# anchors
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

# YOLOv5 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Focus, [64, 3]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, GhostBottleneck, [128, 3, 1]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 9, GhostBottleneck, [256, 3, 1]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, GhostBottleneck, [512, 3, 1]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 1, SPP, [1024, [5, 9, 13]]],
   [-1, 3, GhostBottleneck, [1024, 3, 1]],  # 9
  ]

# YOLOv5 head
head:
  [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2]],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, GhostBottleneck, [512, 3, 1]],  # 13

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2]],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, GhostBottleneck, [256, 3, 1]],  # 17 (P3/8-small)

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 14], 1, Concat, [1]],  # cat head P4
   [-1, 3, GhostBottleneck, [512, 3, 1]],  # 20 (P4/16-medium)

   [-1, 1, Conv, [512, 3, 2]],
   [[-1, 10], 1, Concat, [1]],  # cat head P5
   [-1, 3, GhostBottleneck, [1024, 3, 1]],  # 23 (P5/32-large)

   [[17, 20, 23], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
  ]

**Comment by leoncch** [comment]
can someone tell me the correct way to replace YOLOv5 bottleneckcps to ghostbottleneck, thanks！

**Comment by glenn-jocher** [comment]
@leoncch good news 😃! Your original issue may now be fixed ✅ in PR #4412. This PR adds a new `yolov5s-ghost.yaml` file to data/hub models. You can start training this with:
```bash
python train.py --cfg yolov5s-ghost.yaml --weights yolov5s.pt
```

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by fabiozappo** [comment]
@glenn-jocher is yolov5s-ghost more indicated for deploy on embedded devices? Did you run any test about number of parameters and flops?

**Comment by glenn-jocher** [comment]
@fabiozappo see PR https://github.com/ultralytics/yolov5/pull/4412
