### ISSUE TITLE
Add NVIDIA DALI support ?

### ISSUE THREAD

**Issue by PresageBoat** [ultralytics/yolov5#4411]
## 🚀 Feature

The NVIDIA Data Loading Library (DALI) is a library for data loading and pre-processing to accelerate deep learning applications. It provides a collection of highly optimized building blocks for loading and processing image, video and audio data. It can be used as a portable drop-in replacement for built in data loaders and data iterators in popular deep learning frameworks.

Deep learning applications require complex, multi-stage data processing pipelines that include loading, decoding, cropping, resizing, and many other augmentations. These data processing pipelines, which are currently executed on the CPU, have become a bottleneck, limiting the performance and scalability of training and inference.

DALI addresses the problem of the CPU bottleneck by offloading data preprocessing to the GPU. Additionally, DALI relies on its own execution engine, built to maximize the throughput of the input pipeline. Features such as prefetching, parallel execution, and batch processing are handled transparently for the user.

In addition, the deep learning frameworks have multiple data pre-processing implementations, resulting in challenges such as portability of training and inference workflows, and code maintainability. Data processing pipelines implemented using DALI are portable because they can easily be retargeted to TensorFlow, PyTorch, MXNet and PaddlePaddle.

https://docs.nvidia.com/deeplearning/dali/user-guide/docs/index.html

## Motivation

Imporve training speed!

**Comment by glenn-jocher** [comment]
@edificewang hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

Also note that you can speed up training by caching images into ram or on disk:
```bash
python train.py --cache ram
python train.py --cache disk
```

**Comment by PresageBoat** [comment]
@glenn-jocher hello ,glenn-jocher ,Thank you for your approval. I will implement it in my spare time. After passing the test function, I will submit it to you for review.

**Comment by Haoyanlong** [comment]
@edificewang Could you have implemented the DALI dataloader?
