### ISSUE TITLE
Licenses

### ISSUE THREAD

**Issue by bixiaopeng0** [ultralytics/yolov5#442]
## ❔Question
Hi, I want to join a competition in kaggle with yolov5,but the hosts need the  Apache 2.0, BSD 3.0 licenses,and GPL 3.0 is forbidden.
Could you change the license?

**Comment by glenn-jocher** [comment]
@bixiaopeng0 the competition organizers can change the license restrictions they have in place if they want to. They are forcing competitors to adopt only MIT compliant solutions for their own business reasons. Essentially they want to turn around and make money from participants, and they want to do in such a way that their products are hidden from the world, and not reproducible by other companies.

GPL 3.0 prevents this, as it requires the continuation of the open-source nature of the work.

**Comment by glenn-jocher** [comment]
There is a thread already on this topic here:
https://github.com/ultralytics/yolov5/issues/317

And in Kaggle as well:
https://www.kaggle.com/c/global-wheat-detection/discussion/163433
https://www.kaggle.com/c/global-wheat-detection/discussion/164845

**Comment by bixiaopeng0** [comment]
thanks for your reply!
