### ISSUE TITLE
The code is running but the result is stuck here

### ISSUE THREAD

**Issue by yuninn** [ultralytics/yolov5#4421]
## Additional context
I use yolov5x to train my own data. The program is still running, but the code does not continue to read the data. What should I do?
![Uploading IMG_20210815_224254.jpg…]()

**Comment by yuninn** [comment]
![IMG_20210815_224254](https://user-images.githubusercontent.com/50588276/129482768-c33f64d3-f480-42de-aab1-4a95bf11d4c0.jpg)

**Comment by glenn-jocher** [comment]
@yuninn if training does not proceed it's possible your system lacks resources (cpus, RAM, etc.)
