### ISSUE TITLE
Is it possible to use only 1 detection head from the training checkpoints on MS-COCO? 

### ISSUE THREAD

**Issue by tserdar** [ultralytics/yolov5#4423]
Hey, 

I do not have hardware and time to optimize a custom architecture on MS-COCO, so I have to use the pretrained checkpoints. 

I want to use only the detection head for the smallest scale detection to improve inference speed in my task since bigger objects are not expected to appear. Can I do it using the weights from the checkpoints somehow? Like keeping the backbone and neck weights and training only a single detection head on my custom dataset?

**Comment by glenn-jocher** [comment]
@rocketsfallonrocketfalls I think your assumption that you only require a small attention head may need some justification, i.e. empirical results obtained from ignoring P4, P5 outputs.

Anyone can customize any model with this repo, the work is on you though of course. An example YOLOv5-P3 model is here:

```yaml
# YOLOv5 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Focus, [64, 3]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C3, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 9, C3, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, C3, [512]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 1, SPP, [1024, [5, 9, 13]]],
   [-1, 3, C3, [1024, False]],  # 9
  ]

# YOLOv5 head, P3 only
head:
  [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, C3, [512, False]],  # 13

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, C3, [256, False]],  # 17 (P3/8-small)

   [[17], 1, Detect, [nc, anchors]],  # Detect(P3)
  ]
```

**Comment by tserdar** [comment]
Hey @glenn-jocher, thanks for your answer. 

I am aware that I can achieve what I want through the .yaml configurations however my hardware framework is limited therefore if I am to test this, I have to use the pretrained .pt files otherwise the model will perform bad anyway (my dataset is not really representative). 

I was hoping if I could remove detection heads from the .pt files.
