### ISSUE TITLE
GETTING AssertionError: non-normalized or out of bounds coordinate labels

### ISSUE THREAD

**Issue by IamSparky** [ultralytics/yolov5#443]
## ❔Question
_When I ran the code **!python train.py --img 1024 --batch 32 --epochs 10 --data /content/wheat.yaml --cfg models/yolov5s.yaml --name wm --nosave --cache**

I am getting this error-->
File "train.py", line 405, in <module>
    train(hyp)
  File "train.py", line 165, in train
    hyp=hyp, augment=True, cache=opt.cache_images, rect=opt.rect)
  File "/content/yolov5/utils/datasets.py", line 57, in create_dataloader
    pad=pad)
  File "/content/yolov5/utils/datasets.py", line 375, in __init__
    assert (l[:, 1:] <= 1).all(), 'non-normalized or out of bounds coordinate labels: %s' % file
AssertionError: non-normalized or out of bounds coordinate labels: /content/wheat_dataset/labels/train/93e906638.txt
  0% 0/3035 [00:00<?, ?it/s]_

## Additional context
Whereas my same file looks like this-->

%cat ../wheat_dataset/labels/train/93e906638.txt

0 0.880859 0.023438 0.044922 0.107422
0 0.918945 0.941406 0.060547 0.085938
0 0.118652 0.435059 0.073242 0.124023
0 0.823730 0.548340 0.047852 0.100586
0 0.570312 0.201172 0.050781 0.091797
0 0.033691 0.097168 0.067383 0.062500
0 0.749023 0.209961 0.064453 0.088867
0 0.329590 0.441895 0.094727 0.098633
0 0.033691 0.469238 0.067383 0.101562
0 0.424316 0.050293 0.059570 0.132812
0 0.025879 0.528809 0.051758 0.063477
0 0.111328 0.032227 0.064453 0.101562
0 0.583008 0.465820 0.042969 0.132812

**Comment by glenn-jocher** [comment]
@soumochatterjee your labels are incorrect, as the error states.

**Comment by IamSparky** [comment]
thanks gelnn...I understood where I was making mistake.

**Comment by glenn-jocher** [comment]
Great! Is it working now?

Is there a better way to display the error to help people understand better?

**Comment by IamSparky** [comment]
It is working but I am not able to train the model on Google Colab's Gpu,
As the RAM is getting exhausted during the training process .

I was doing wrong in the part of normalising my coordinates which are-->

# normalising the co-ordinates
      x_center = x + w / 2
      y_center = y + h / 2
      x_center /= 1024.0 
      y_center /= 1024.0 
      w /= 1024.0
      h /= 1024.0
Where 1024.0 refers to the width and height of all of my images

**Comment by glenn-jocher** [comment]
@soumochatterjee got it. If you are running out of RAM you can upgrade to colab pro, which offers twice the ram. If you are using --cache you can also omit it to reduce RAM usage.

**Comment by diegocfq** [comment]
Getting the same error, my images are 1920x4000 and i believe i'm parsing the xyxy to cxywh correctly.

Here is the parsing code that generates the txt:
`xmin = int(box[0].text)`
`ymin = int(box[1].text)`
`xmax = int(box[2].text)`
`ymax = int(box[3].text)`
`w = abs(xmax-xmin)`
`h = abs(ymax-ymin)`
`xc = xmin + w/2`
`yc = ymin + h/2`
`saveline = saveline + " " + str(xc/width) + " " + str(yc/height) + " " + str(w/width) + " " + str(h/height)`
`f.write(saveline+"\n")`

And this is the output:
1 0.7453125 0.125 0.020833333333333332 0.0165
1 0.7130208333333333 0.162125 0.034375 0.01225
1 0.7158854166666667 0.17475 0.0359375 0.014
1 0.7177083333333333 0.18775 0.03958333333333333 0.02
1 1.0138020833333334 0.19275 0.0484375 0.0165
1 0.821875 0.290375 0.030208333333333334 0.01275
1 0.8166666666666667 0.2905 0.03333333333333333 0.021
1 0.8640625 0.292125 0.03333333333333333 0.01775
1 0.8682291666666667 0.296875 0.051041666666666666 0.01825
1 0.6791666666666667 0.33525 0.020833333333333332 0.014
1 0.6794270833333333 0.208625 0.0328125 0.01925
1 0.66015625 0.243 0.0265625 0.015
1 0.6080729166666666 0.272 0.0453125 0.014
1 0.6341145833333334 0.349625 0.027604166666666666 0.01275
1 0.63359375 0.389375 0.0265625 0.01675
1 0.6880208333333333 0.401125 0.03854166666666667 0.01775
1 0.7041666666666667 0.40275 0.03333333333333333 0.0155
1 0.796875 0.42175 0.03125 0.02
1 0.7963541666666667 0.4155 0.030208333333333334 0.03
