### ISSUE TITLE
from where I can change the figures labels text

### ISSUE THREAD

**Issue by besbesmany** [ultralytics/yolov5#4431]
want to change label text and put labels for x and y axis

![results](https://user-images.githubusercontent.com/35992924/129558689-78f1db1a-c643-47bb-9af7-932567996918.png)

**Comment by glenn-jocher** [comment]
@besbesmany you can customize this function here:
https://github.com/ultralytics/yolov5/blob/dbc06ce29298de4a55d73fa37362dd51a03035ed/utils/plots.py#L385-L408
