### ISSUE TITLE
Big memory allocations during training

### ISSUE THREAD

**Issue by waicool20** [ultralytics/yolov5#444]
## 🐛 Bug
There seems to be sudden huge allocations when it tries to do NMS on the results, I'm running it with this command
```
python train.py --img-size 1024 --epochs 150 --batch-size 4 --cfg ./models/yolov5s.yaml --data ./data/coco128.yaml --hyp ./hyp.yaml --weights ''
```

Typical gpu usage with the above is around 3GB memory but then it suddenly wants to allocate 7GB for NMS? The epoch it happens also seems random.

Output:
```
Traceback (most recent call last):
  File "train.py", line 405, in <module>
    train(hyp)
  File "train.py", line 294, in train
    results, maps, times = test.test(opt.data,
  File "C:\Users\waicool20\Programming\python\yolov5\test.py", line 92, in test
    output = non_max_suppression(inf_out, conf_thres=conf_thres, iou_thres=iou_thres, merge=merge)
  File "C:\Users\waicool20\Programming\python\yolov5\utils\utils.py", line 612, in non_max_suppression
    i = torchvision.ops.boxes.nms(boxes, scores, iou_thres)
  File "c:\Python38\lib\site-packages\torchvision\ops\boxes.py", line 35, in nms
    return torch.ops.torchvision.nms(boxes, scores, iou_threshold)
RuntimeError: CUDA out of memory. Tried to allocate 7.11 GiB (GPU 0; 11.00 GiB total capacity; 178.01 MiB already allocated; 6.98 GiB free; 2.30 GiB reserved in total by PyTorch)
```

## Environment

 - OS: Windows
 - GPU 2080Ti

**Comment by glenn-jocher** [comment]
CUDA out of memory. You need to reduce batch size or use a larger GPU.

**Comment by waicool20** [comment]
@glenn-jocher One thing to note is that I've run this successfully a few times, but the out of memory situation with the huge allocations in NMS is very random and interrupts runs. Maybe this might be a bug with pytorch on windows.

**Comment by glenn-jocher** [comment]
@waicool20 the only memory bug I'm aware of is when using --evolve with the `for` loop set within the python file rather than in an outer bash `for` loop.

CUDA OOM is not a bug, it just is what it is, it happens to everyone if you set your parameters beyond what your GPU can handle. Using all default params/settings YOLOv5s can be trained up to about batch-size 96 on a 16GB device like a T4 or V100. You need to use Apex, and if your hyps are creating the problem you need to clearly not use them.

**Comment by glenn-jocher** [comment]
@waicool20 or put another way, everything works under the default settings. If you stray in your use case you're in uncharted waters and that's just between you and your experiments, I can't advise you there.

**Comment by glenn-jocher** [comment]
@waicool20 BTW, if you suspect a windows bug I would try to train in Docker instead below.

## Environment

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)

**Comment by waicool20** [comment]
This happens with or without custom hyp, and I have apex installed. I already begun setting up a linux install to see if that helps. I just thought it was weird the NMS would take up so much memory all of a sudden compared to the model itself.

**Comment by waicool20** [comment]
Running Linux seems to be more stable for running the default configuration multiple times without error, so I'll just run that from now on.

**Comment by glenn-jocher** [comment]
Yes, linux is certainly the preferred OS for ML in general.

**Comment by watertianyi** [comment]
@glenn-jocher 
yolov5，2080ti For 11g video memory training, there is often insufficient CUDA in video memory. The batchsize is 8, but it can be used in 2080ti 8g training. Another situation is that after installing apex, it can run in batchsize = 8, but with the addition of -- cache images, - multi scale, - single CLS, CUDA memory is insufficient. After removing these parameters, apex must be re installed to resume operation What's the situation? thank you!

**Comment by glenn-jocher** [comment]
@honghande apex is no longer required. Use the latest code.

**Comment by watertianyi** [comment]
@glenn-jocher I use yolov5x.pt as the initialization weight. CFG is yolov5x.yaml, rtx2080ti GPU graphics card is 11g. If you do not use apex and batchsize is set to 8, you will report an error that CUDA video memory is insufficient. If you use apex and batchsize set to 8, you can use it normally. What you used is the latest code yesterday

**Comment by glenn-jocher** [comment]
@honghande I guess I don't understand your question. If you have a reproducible bug please file a bug using the bug report template with clear steps to reproduce.

**Comment by watertianyi** [comment]
@glenn-jocher https://github.com/ultralytics/yolov5/issues/635#issuecomment-675824456

**Comment by YunfeiZHAO** [comment]
Firstly, thanks a lot for answer questions in the community @glenn-jocher 
I think that I have the same question as you @hande6688 

warning:
RuntimeError: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 7.93 GiB total capacity; 6.51 GiB already allocated; 18.62 MiB free; 6.60 GiB reserved in total by PyTorch)              

run:
python train.py --img 2048 --batch 4 --epochs 5 --data ./data/cityscapes.yaml --cfg ./models/yolov5s_cityscapes.yaml --weights yolov5s.pt --workers 2 

I think yolov5 is is a small architecture which takes only 15mb, and an image from cityscapes takes only 2 mb. As I set batch size to 4, The total size of neural network will be around 15 * 2 + 2*4 = 38mb as the optimizer is SGD.  
My question is how does the training process takes more than 7gb of memory in a graphic card?
Thanks in advance

**Comment by glenn-jocher** [comment]
@YunfeiZHAO thanks for the bug report! If you believe you have a reproducible issue, we suggest you close this issue and raise a new one using the 🐛 **Bug Report template**, providing screenshots and a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

I also see you are using a cityscapes dataset which is not part of the official code. For reproducibility you should try to recreate your issue with a common dataset (i..e. COCO, COCO128, VOC), in a common environment (i.e. Colab, Kaggle, Docker), with the latest version of master branch (no code modifications).

Alternatively you may submit a PR for inclusion of cityscapes dataset in the list of officially included datasets, though if you do this we also ask that you supply auto-download commands as the existing datasets employ.

Thank you!

**Comment by YunfeiZHAO** [comment]
> @YunfeiZHAO thanks for the bug report! If you believe you have a reproducible issue, we suggest you close this issue and raise a new one using the bug **Bug Report template**, providing screenshots and a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem.
> 
> I also see you are using a cityscapes dataset which is not part of the official code. For reproducibility you should try to recreate your issue with a common dataset (i..e. COCO, COCO128, VOC), in a common environment (i.e. Colab, Kaggle, Docker), with the latest version of master branch (no code modifications).
> 
> Alternatively you may submit a PR for inclusion of cityscapes dataset in the list of officially included datasets, though if you do this we also ask that you supply auto-download commands as the existing datasets employ.
> 
> Thank you!

Thank you for  you reply, I am going to report a new issue.
As for the PR, I have two questions.
1, As Cityscapes need an account authentication for downloading, so I think the zip files for the images and labels need to be downloaded manually. So I put the zip files on my cloud and download it by .sh file for now?
2, To generate the yolov5 standard dataset structure, the whole Cityscapes files need to be refactored, I used a python script to do this job, I put it alongside the .sh file?

**Comment by glenn-jocher** [comment]
@YunfeiZHAO thanks buddy! We'd want it to be publically available for download, so the two options are:

1. If Cityscapes is < 2GB we can host it directly on GitHub, i.e.: https://github.com/ultralytics/yolov5/releases/download/v1.0/coco128.zip
2. If it's larger than 2GB we can host it in an Ultralytics GCP bucket for everyone to download, i.e.: https://storage.googleapis.com/ultralytics/data/coco128.zip

About the python file, that's interesting as all the download files are bash files currently, but if you want to use a python file instead that should be fine, you can just use a line like this in cityscapes.yaml:
```yaml
download: python data/scripts/get_cityscapes.py
```

If you have a mixed bash-python file you can include python code in your bash file also. See [get_voc.sh](https://github.com/ultralytics/yolov5/blob/master/data/voc.yaml) or download_weights.sh for examples:

https://github.com/ultralytics/yolov5/blob/8f6e447729e34a46fdbe9552fcfac705b82deac5/weights/download_weights.sh#L1-L12
