### ISSUE TITLE
eval mAP implemented in the repository lower than that of pycocotools?

### ISSUE THREAD

**Issue by anonymoussss** [ultralytics/yolov5#4443]
## ❔Question
I am using yolov5m to train my custom dataset. When using val.py for validation, why is the evaluation map implemented in this repository lower than that of pycocotools? The specific output is as follows.

## Additional context

Scanning 'val2017/labels.cache' images and labels..
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|█| 48/48 [00:19<00:00
                 all       1530       2011      0.948      0.924      0.929      0.775  
Speed: 0.1ms pre-process, 2.5ms inference, 0.5ms NMS per image at shape (32, 3, 320, 320)

Evaluating pycocotools mAP... saving runs/test/exp18/best_predictions.json...  
loading annotations into memory...  
Done (t=0.07s)                 
creating index...                                                                                                    
index created!                                                           
Loading and preparing results...                   
DONE (t=0.01s)                                      
creating index...                                 
index created!                                         
Running per image evaluation...              
Evaluate annotation type *bbox*                                 
DONE (t=0.41s).                                                     
Accumulating evaluation results...                                     
DONE (t=0.13s).                                 
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=          all | maxDets=100 ] = 0.760        
 Average Precision  (AP) @[ IoU=0.50        | area=          all | maxDets=100 ] = 0.910 
 Average Precision  (AP) @[ IoU=0.75        | area=          all | maxDets=100 ] = 0.817            
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=     small | maxDets=100 ] = 0.512    
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.643  
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large     | maxDets=100 ] = 0.831  
 Average Recall       (AR) @[ IoU=0.50:0.95 | area=   all        | maxDets=  1 ] = 0.638  
 Average Recall       (AR) @[ IoU=0.50:0.95 | area=   all        | maxDets= 10 ] = 0.791                             
 Average Recall       (AR) @[ IoU=0.50:0.95 | area=   all        | maxDets=100 ] = 0.794    
 Average Recall       (AR) @[ IoU=0.50:0.95 | area= small     | maxDets=100 ] = 0.555    
 Average Recall       (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.705   
 Average Recall       (AR) @[ IoU=0.50:0.95 | area= large     | maxDets=100 ] = 0.858  
Results saved to runs/test/exp18     
1513 labels saved to runs/test/exp18/labels  .

**Comment by glenn-jocher** [comment]
@anonymoussss see https://github.com/ultralytics/yolov5/issues/2258
