### ISSUE TITLE
Why c3’s shortcut in neck are all False？

### ISSUE THREAD

**Issue by Zigars** [ultralytics/yolov5#4445]
## ❔Question
Hi, glenn, I want to know why c3’s shortcut in neck are all False？ I'm Confuse about it.
## Additional context
![image](https://user-images.githubusercontent.com/32835472/129678107-cbc05881-390f-4d90-a981-a73b95fa9c30.png)

**Comment by lijain** [comment]
Hello, I have the same problem, please answer it, thank you

**Comment by glenn-jocher** [comment]
@lijain this the YOLOv5 design.
