### ISSUE TITLE
Is there a  very small version of yolov5?  which is smaller than yolov5s?

### ISSUE THREAD

**Issue by henbucuoshanghai** [ultralytics/yolov5#4446]
so i can run it on my phone?

**Comment by glenn-jocher** [comment]
@henbucuoshanghai all YOLOv5 models are natively mobile compatible, i.e. see our TikTok with YOLOv5m running at 30 FPS on a 2 year old iPhone.

https://vm.tiktok.com/ZMRL9Beo3/

<img width="400" src="https://user-images.githubusercontent.com/26833433/129928220-b48bb1ac-066d-4747-87c6-eae622d0d45e.png">

**Comment by henbucuoshanghai** [comment]
tks for your kind reply


use tnn or ncnn? which is better? where is the relative code?
