### ISSUE TITLE
run two torch.hub.load in one app synchronously

### ISSUE THREAD

**Issue by mohammad69h94** [ultralytics/yolov5#4450]
## ❔Question
when I load two models using torch hub in one app in a docker container, does not run!
but when I remove one of them app correctly run
I guess both loading models using torc hub are synchronously running in docker and are not run in order(Respectively) and problem in this.

Is there a way to solve this problem? or other methods is exist for use?

**Comment by glenn-jocher** [comment]
@mohammad69h94 you may need to set each model's Detect() forward method inplace attribute to False:
https://github.com/ultralytics/yolov5/blob/6dd7dd8dd3c27ac8b986578f91fa14aab12357d7/models/yolo.py#L63-L69
