### ISSUE TITLE
describe these output to me please

### ISSUE THREAD

**Issue by besbesmany** [ultralytics/yolov5#4451]
![2](https://user-images.githubusercontent.com/35992924/129720695-6bd1988c-2bd9-4208-8df4-9738c5f4b8f5.png)
what is the maxDet=100 ,  10,1

what is area = all, small, medium, large

what is is difference between these previous average recalls, average precisions
and 
the next picture precision and recall is it the max or average too?

![3](https://user-images.githubusercontent.com/35992924/129720707-696005b0-02e8-4365-87f1-fdf11c1ad24c.png)

**Comment by glenn-jocher** [comment]
@besbesmany if your question originates on content from another repository you should ask your question there. These results are generated by pycocotools.
