### ISSUE TITLE
No labels in path/to/images/train2017.cache. Can not train whitout labels.

### ISSUE THREAD

**Issue by Danielvenzi** [ultralytics/yolov5#4460]
## ❔Question
How do i create the train2017.cache file to a custom dataset?

## Additional context

I wanted to train a model using only a two classes present in the coco128 dataset, but couldnt find a way to train ignoring the other classes unless i changed the dataset, so i did. 

In the coco128.yaml i changed the nc and names to match the classes that i wanted, in the dataset i ran a script that did iterations on every .txt file to find the if the classes i wanted were there to maintain and erase the other labels, so for instance if i had in a .txt file three classes and wanted to keep two (0 and 43) the script did the following:

-> ORIGINAL (.txt):
 0 label_information
 43 label_information
 27 label_information

-> RESULT (.txt):
 0 label_information
 1 label_information

It changed the old class index to a new one inside the range of the NC (number os classes) in the .yaml file. If a .txt file had one of the classes i copied the correspondent image to a new directory, and in the end had the following paths:

  images_new/train2017/ (with the correspondent images)
  labels_new/train2017/ (with the new .txt, containing only the classes that i wanted)

The labels only had the two classes i wanted and the images consisted of the correspondent labels images. The problem happens when i try to train the model using the changed coco128.yaml and the new dataset, it informs me that the train2107.cache file has no labels in it. Did i break something by chanching the the dataset that way? The error points to the Train Custom Data page but there is no information regarding the .cache file and it's generation.

**Comment by glenn-jocher** [comment]
@Danielvenzi *.cache files are generated automatically and require zero user interaction.

**Comment by Danielvenzi** [comment]
@glenn-jocher i found out the mistake was in my end, i separated the newly created images_new and labels_new to another directory with the names labels and images and it worked! Thanks for the response nevertheless.
