### ISSUE TITLE
Remove mosaic augmention in the last 15 epochs.

### ISSUE THREAD

**Issue by Jackluisus** [ultralytics/yolov5#4461]
## Additional context
It is a nice trick used in YOLOX, which can get an obvious improvement. I wish YOLOV5 can adopt it in the future version.

**Comment by glenn-jocher** [comment]
@Jackluisus hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by glenn-jocher** [comment]
@Jackluisus this may be partly implemented in #4461. 

Note that this creates a new trainloader with `rect=True` which will disable mosaic, though be warned the loader is not shuffled.  Alternatively the hyps could be updated to `mosaic=0.0` and pass with `rect=False`.

**Comment by am3n** [comment]
@Jackluisus

Hi Jack, I hope you are well.
A few days ago, I saw your source in your GitHub account [Drone_Object_Detection_Android](https://github.com/Jackluisus/Drone_Object_Detection_Android)
but again today I realized that it doesn't exist and you deleted it.
Anyway, for my work, I need a part of this source that is related to YOLO5. 
Please email me this source if it is possible for you. Thanks.
amirhoseinbarati75@gmail.com
