### ISSUE TITLE
How to use real time detection with multiple USB camera?

### ISSUE THREAD

**Issue by ccm516** [ultralytics/yolov5#4466]
How to use real time detection with multiple USB camera?

when two USB camera are connected, I use this code

1st prompt : python detect.py --source 0
2nd prompt : python detect.py --source 1

How to run two USB cameras from only one prompt for real time detection?

you told me that "python detect.py --source streams.txt", but I don't know how to use this code

**Comment by glenn-jocher** [comment]
@ccm516 place your sources in streams.txt, one per line

**Comment by ccm516** [comment]
I don't know source of USB camera...

How can i check source of USB camera?
