### ISSUE TITLE
multi-targets for a single anchor

### ISSUE THREAD

**Issue by fosaken** [ultralytics/yolov5#4468]
Thk u for ur repo and I have a question when reading the codes about build_targets and compute loss.
## ❔Question
&emsp;&emsp;I met a case that a single anchor is responsalbe to multi gt boxes.
## Additional context
&emsp;&emsp;According to gt assignment rules of yolov5, there is a case that more than one gt boxes assigned to the same anchor(if the ratio rule is satified), so the anchor will be selected many times and calculate loss with many different gt boxes.
&emsp;&emsp;Because a gt box is also assigned to neighbor grid cells in yolov5, the same problem may occurred if a neighbor cell already has an obj in it.
&emsp;&emsp;Is this an exception?I think the anchor in this case won't predict well  so why don't u guys set a rule to handle this?

**Comment by glenn-jocher** [comment]
@fosaken this is correct behavior, there is no problem.

**Comment by fosaken** [comment]
> @fosaken this is correct behavior, there is no problem.

ok , really grateful for your reply

**Comment by xxxwuwq** [comment]
> 

sorry, i can't understand that multi-targets for a single anchor is correct behavior, anyone could help me?

**Comment by glenn-jocher** [comment]
@xxxwuwq yes it's correct behavior
