### ISSUE TITLE
OpenCV 4.5.3 shape_utils assertion failed

### ISSUE THREAD

**Issue by nejcmedved** [ultralytics/yolov5#4471]
Hi all,

first thank you very much for sharing your code in this repo!

My current issue is code below

` import cv2

model = cv2.dnn.readNetFromONNX("runs/train/exp10/weights/best.onnx")
image = cv2.imread("data/images/bus.jpg")
resized = cv2.resize(image, (640, 640), interpolation = cv2.INTER_AREA)

input_blob = cv2.dnn.blobFromImage(
    image=image,
    scalefactor=1/255,
    size=(640, 640),  # img target size
    swapRB=True,  # BGR -> RGB
    crop=True  # center crop
)

model.setInput(input_blob)
output = model.forward()`

where result in last line is

`
opencv2/dnn/shape_utils.hpp:171: error: (-215:Assertion failed) start <= (int)shape.size() && end <= (int)shape.size() && start <= end in function 'cv::dnn::dnn4_v20210608::total'
`

did anyone came across this issue before?

for exporting my model I use

`
python export.py --weights=runs/train/exp10/weights/best.pt --include=onnx --simplify
`

**Comment by glenn-jocher** [comment]
@nejcmedved you should submit a bug report in the repo where the error in your custom code originates, cv2 in your case.

Note you can also run inference with your onnx model directly with detect.py:
```bash
python export.py --weights yolov5s.pt --include onnx --dynamic
python detect.py --weights yolov5s.onnx
```

**Comment by nejcmedved** [comment]
Hi Glen,

I agree. I should post this issue here.

Thanks again for very organized repo!

Best, Nejc
