### ISSUE TITLE
dockerfile

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#4473]
## ❔Question
https://github.com/ultralytics/yolov5/blob/24bea5e4b7ad369753f45e93b736d9205c37d20a/Dockerfile#L14

Why do you install  torch, numpy .... again ?

FROM nvcr.io/nvidia/pytorch:21.05-py3 should have the numpy, torch.

**Comment by glenn-jocher** [comment]
@alicera we've found this improves DDP stability.

**Comment by alicera** [comment]
https://github.com/ultralytics/yolov5/blob/24bea5e4b7ad369753f45e93b736d9205c37d20a/Dockerfile#L12
uninstall nvidia is also improving DDP stability?
