### ISSUE TITLE
How to download different (smaller) models of YOLOv5?

### ISSUE THREAD

**Issue by schubackindustries** [ultralytics/yolov5#4477]
## ❔Question

Hi, I'm looking to download more lightweight (faster) models of YOLOv5. After cloning the repo and running, I saw that it downloaded "yolov5s.pt", which runs OK on my computer but not as fast as I want. 

Are there other models I can download and swap in? I saw some people running mobile versions and somebody mentioned a "lite" version.

For reference, I just want to pass in as an argument, i.e. "python detect.py --weights [some_smaller_model] --source 0" or however it should work for detect.py

## Additional context

Thanks! Great lib

**Comment by glenn-jocher** [comment]
@schubackindustries you can compound scale an arbitrarily smaller version of YOLOv5 simply by lowering the depth and width multiples here, and then training a new model from your updated yaml:
https://github.com/ultralytics/yolov5/blob/11f85e7e71d91810460a2eee22235a2264b458eb/models/yolov5s.yaml#L3-L6

This also seems interesting:
https://github.com/ppogg/shufflev2-yolov5

**Comment by ppogg** [comment]
> @schubackindustries you can compound scale an arbitrarily smaller version of YOLOv5 simply by lowering the depth and width multiples here, and then training a new model from your updated yaml:
> https://github.com/ultralytics/yolov5/blob/11f85e7e71d91810460a2eee22235a2264b458eb/models/yolov5s.yaml#L3-L6
> 
> This also seems interesting:
> https://github.com/ppogg/shufflev2-yolov5

Thank you! Actually, this part of the work is not perfect yet. I have been following your repo. I also hope to get some suggestions from you:
[https://github.com/ultralytics/yolov5/issues/4501](https://github.com/ultralytics/yolov5/issues/4501)
