### ISSUE TITLE
validation data

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#4486]
## ❔Question
set the validation data to be 5000 image when training.
set the validation data to be 1 image when training.
Is it good method to speed up train time? And keep the accuracy ?

**Comment by iceisfun** [comment]
Also see --noval on train.py

https://github.com/ultralytics/yolov5/blob/d1182c4f29e2141be856b85c5d613480a2fffc5d/train.py#L432

**Comment by alicera** [comment]
So the val data is just to check mAP.
val data doesn't affect the final result for training.
