### ISSUE TITLE
tensorboard

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#4489]
## ❔Question

Do you have the Tutorials for tensorboard?
To see the val.py result.

**Comment by glenn-jocher** [comment]
@alicera TensorBoard integrates with train.py, see Colab Notebook, run TensorBoard cell before training.

**Comment by alicera** [comment]
Do you have the Tutorials for these png?

![image](https://user-images.githubusercontent.com/59388989/130201864-51315661-b8a3-4370-9c19-9778d82b68fa.png)

**Comment by iceisfun** [comment]
I launch tensorboard like this

In docker run command map the port, default TensorBoard port is 6006
```
--net host

OR
-p 6006:6006
-
```

Inside Docker before running train
```
tensorboard --bind_all --logdir=runs/train/exp &
```
