### ISSUE TITLE
为什么训练过程的mAP有收敛，但是非常小，基本保持在0.01左右%？有没有人有类似的情况

### ISSUE THREAD

**Issue by jingenyan** [ultralytics/yolov5#449]
为什么训练过程的mAP有收敛，但是非常小，基本保持在0.01左右%？有没有人有类似的情况

**Comment by shenglih** [comment]
^translation: why is that during training mAP did converge but turned out very small at around 0.01%? Anyone had similar experiences?

**Comment by sonica1987** [comment]
mAP随着训练应该越来越高才对,你看看你的验证集里的图片是不是和训练集偏差很大,识别不出来就会很低,同样p和r也会很低
