### ISSUE TITLE
How to run "python detect.py --source streams.txt"?

### ISSUE THREAD

**Issue by ccm516** [ultralytics/yolov5#4490]
How to run "python detect.py --source streams.txt"?

I run "python detect.py --source streams.txt"
It's Not working.......
I don't know how to get my address of USB camera

1/1: streams.txt... Traceback (most recent call last):
  File "detect.py", line 173, in <module>
    detect()
  File "detect.py", line 52, in detect
    dataset = LoadStreams(source, img_size=imgsz)
  File "C:\Users\Desktop\yolov5\utils\datasets.py", line 239, in __init__
    assert cap.isOpened(), 'Failed to open %s' % s
AssertionError: Failed to open streams.txt

Please let me know details..

**Comment by glenn-jocher** [comment]
@ccm516 what is the contents of your streams.txt file?

**Comment by ccm516** [comment]
I've run "python detect.py --source 0" or "python detect.py --source 1" because I use USB camera

so I don't know what is contents of .txt
Because it's the first time I've seen it this way

I tried "0", "0 1". It's not working

**Comment by ccm516** [comment]
oh I solved the problem. Thank you!

**Comment by wangjp1233** [comment]
23/5000 
Hello, how do I configure different PT weights for each RTSP stream  Thank you

**Comment by glenn-jocher** [comment]
@wangjp1233 to configure different PT weights for each RTSP stream, you can modify the `streams.yaml` file to include the PT weight along with the RTSP streams using the `path` and `format` fields. You can find more details in the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/

If you have any further questions or need additional assistance, feel free to ask!
