### ISSUE TITLE
Can't start training with wandb

### ISSUE THREAD

**Issue by alekseibahmatov** [ultralytics/yolov5#4493]
## ❔Question
I'm using anaconda to create isolated python environment. The problem is I want to use wandb but every time I start training it says I have to install wandb using pip but I've done it already.

P.S i've downloaded yolov5 repo today so I believe it is up to date.

**Comment by AyushExel** [comment]
@alekseibahmatov how have you installed wandb? Can you share the screenshot of the error message that you're getting? Have you tried installing wandb using `pip install wandb` ?

**Comment by alekseibahmatov** [comment]
> @alekseibahmatov how have you installed wandb? Can you share the screenshot of the error message that you're getting? Have you tried installing wandb using `pip install wandb` ?

Yes, i've installed wandb using pip install wandb. That's the problem it doesn't show any error, It just says that I have to install wandb using pip install wandb, but as I said above I already done It.

**Comment by AyushExel** [comment]
@alekseibahmatov and are you not getting wandb dashboard from thr training scripts ?

**Comment by alekseibahmatov** [comment]
@AyushExel I don't even see this 
![image](https://user-images.githubusercontent.com/42650413/130315192-405e123d-75c7-4fc3-9c04-2842ba071883.png)
training script just reminds me to install wandb but as I said I already installed it

**Comment by AyushExel** [comment]
@alekseibahmatov when you run `pip list`, do you see `wandb` listed there? 
Can you try running this python script to see if wandb is properly installed:
```
import wandb
wandb.init(project='test')
```

**Comment by alekseibahmatov** [comment]
@AyushExel 
![image](https://user-images.githubusercontent.com/42650413/130316898-e865ab33-0821-4b4d-91e3-88f04ea8f121.png)
as you can see all is working fine. But every time I start train.py I see this
![image](https://user-images.githubusercontent.com/42650413/130316976-b1ee9ec9-467c-44aa-9fa3-4a9d1f5cba36.png)

**Comment by alekseibahmatov** [comment]
@AyushExel Sorry that was my fault, I forgot to use python in command line before train.py
