### ISSUE TITLE
ndarray

### ISSUE THREAD

**Issue by Dabeaurard** [ultralytics/yolov5#4495]
hi, i have a question about doing the prediction, is it possible to pass a ndarray(a frame as variable from a video where the frame=cap.read())
i have this error: TypeError: expected str, bytes or os.PathLike object, not ndarray

**Comment by glenn-jocher** [comment]
@Dabeaurard see PyTorch Hub tutorial:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by shreyasvedpathak** [comment]
@Dabeaurard first of all, `cap.read()` will return 2 variables. The frame will be the second one. Then you can pass that frame and get results.

Load the model using saved weights
```python
import torch

model = torch.hub.load('ultralytics/yolov5', 'custom', '/path/to/your/custom/model.pt')
model.conf = 0.5 # minimum confidence threshold
```
And then you can access the predictions like this

```python
# you'll first need to load your image
ret, frame = cap.read()
results = model(frame, size=1280) # tweak size as needed

labels = results.xyxyn[0][:, -1].numpy()
cord = results.xyxyn[0][:, :-1].numpy()
```
