### ISSUE TITLE
Yolo doesn't have the ability to label it in a diagonal way!!

### ISSUE THREAD

**Issue by muhammedakyuzlu** [ultralytics/yolov5#4499]
## ❔Question

How to detect a thin and long object in the diagonal position in a crowded scene when Yolo doesn't have the ability to label it in a diagonal way? 

## Additional context

I have a dataset of a single object that looks like a pen. I labeled the dataset and train it, it worked just fine until the big problem shows. When the "pens" stack side by side in a diagonal way the Yolo fails to detect them since the labels are too close to each other. I tried to raise the thresh hold to 0.95 and still have an issue. I realized that in my dataset most of the labels have at least 60% overlapping which means that in most cases the label contains an object and half or more. So the big question is How to detect an object in such a crowded scene when Yolo doesn't have the ability to label in a diagonal way?

**Comment by glenn-jocher** [comment]
See https://github.com/ultralytics/yolov5/issues/3465

**Comment by muhammedakyuzlu** [comment]
Thank you @glenn-jocher that was helpful
