### ISSUE TITLE
Will there be a lighter yolov5？

### ISSUE THREAD

**Issue by ppogg** [ultralytics/yolov5#4501]
## Additional context
Dear author, I am a student. I have been following your warehouse for a long time, from less than 1k of yolov5 to 15k now, yolov5 is indeed a pretty good algorithm. I think that yolov5 may allow light-weight development in the past. In fact, I am also doing related work. This is the model I modified. It can achieve 2-4 times acceleration on the chip of the Arm series architecture, but the map is definitely far inferior to yolov5m and yolov5l. This is also my graduation project. I would like to ask you how to maintain the speed of a model like me without losing too much map at the same time? I also look forward to your future release of lighter models, I will always follow you, and thank you for your suggestions!
This is my project address: [https://github.com/ppogg/YOLOv5-Lite](https://github.com/ppogg/YOLOv5-Lite)

**Comment by ppogg** [comment]
Hi, sir. Yolov5 is really powerful, especially C3 block, which I think is a good idea. Actually, it also outstanding in lightweight modification, compared with depthwise or CSP block.
In fact, I have been doing this aspect of the experiment, this is the new baseline.

  ID|Model | Input_size|Flops| Params | Size（M） |Map@0.5|Map@.5:0.95
 :-----:|:-----:|:-----:|:----------:|:----:|:----:|:----:|:----:|
001| yolov5-lite| 320×320|1.43G |1.62M|3.3| 36.2|20.8| 
002| yolov3-tiny| 416×416| 6.96G|6.06M|23.0| 33.1|16.6
003| yolov4-tiny| 416×416| 5.62G|8.86M| 33.7|40.2|21.7
004| yolov5-lite| 416×416|2.42G |1.62M|3.3| 41.3|24.4| 
005| yolov5-lite| 640×640|2.42G |1.62M|3.3| 45.7|27.1| 
006| yolov5s| 640×640| 17.0G|7.3M|14.2| 55.4|36.7

The backbone is shufflenet, neck is Yolov5 Pan (with c3 block),
But I think it has reached the bottleneck. Do you have any suggestions?

Oh. In addition, I tested that concat in the following C3 block is replaced by add. The parameters can be reduced by 1 / 3, but the accuracy is declined 2 points. That's fun~

**Comment by glenn-jocher** [comment]
@ppogg thanks for the feedback! The most basic type of model reduction on the smaller side would depend on the priority:

- smaller size: most easily attained by reduction/elimination of large output layers (i.e. P5-P6) or channel count/ops on large output layers, or depthwise convolutions on large output layers.
- faster speed: most easily attained by reduction/elimination of small output layers (i.e. P1-P3) or channel count/ops on small output layers, or depthwise convolutions on small output layers.

Note that smaller size and faster speed are not necessarily highly correlated, instead speed is dominated by small object layers while size is dominated by large object layers.

**Comment by ppogg** [comment]
> @ppogg thanks for the feedback! The most basic type of model reduction on the smaller side would depend on the priority:
> 
> * smaller size: most easily attained by reduction/elimination of large output layers (i.e. P5-P6) or channel count/ops on large output layers, or depthwise convolutions on large output layers.
> * faster speed: most easily attained by reduction/elimination of small output layers (i.e. P1-P3) or channel count/ops on small output layers, or depthwise convolutions on small output layers.
> 
> Note that smaller size and faster speed are not necessarily highly correlated, instead speed is dominated by small object layers while size is dominated by large object layers.

Yes sir, I agree with your point of view deeply. In fact, I also discovered this point during the experiment. It is cool, and it is also two points that directly affect the speed and model size.

**Comment by ppogg** [comment]
The above two suggestions you gave are very useful! In fact, I have integrated the repvgg block, the model is only 10M, but the Flops of YOLOv5-Repvgg looks large (22G), the detection speed is only 10% faster on gpu, and the accuracy has dropped by 6 points. I will try you suggestions for pruning and compression~

**Comment by ppogg** [comment]
Sir, I seem to have completed all the experiments of graduation thesis. Of course, the experiment is optimized for different frameworks. 
![image](https://user-images.githubusercontent.com/82716366/137470698-1c155d81-f263-44a3-b531-c6f2a5634211.png)
![image](https://user-images.githubusercontent.com/82716366/137470811-263e628e-8b7c-4d4d-a282-1ffc8b981dfd.png)
As I see, yolov5 is a very outstanding framework, I learned a lot through it！
Thankyou, Sir!
