### ISSUE TITLE
[Solved, Solution@closing comment] UnicodeDecodeError 'cp950' with labels txt files created using makesense.ai

### ISSUE THREAD

**Issue by eecmyang** [ultralytics/yolov5#4502]
## 🐛 Bug

`UnicodeDecodeError 'cp950' codec can't decode...` error happens when used labels made with [makesense.ai](url) labeling tool.

## To Reproduce (REQUIRED)

Due to the conveniences, I wrapped my files on my D drive's Desktop, hence,

in order to reproduce the error, you need to modify both train & val's  `path` in `datasets` folder's `custom.yaml` file.
 
Then uses the following command with Anaconda environment. Preferably, create & set up a clean env to reproduce.

Input:

```
python train.py --data D:/Desktop/reproduce/datasets/custom.yaml --cfg D:/Desktop/reproduce/yolov5-master/models/yolov5s.yaml --weights D:/Desktop/reproduce/yolov5-master/weights/yolov5s.pt --batch-size 8 --name Pokemon --epochs 100
```

Output:

```
Traceback (most recent call last):
  File "train.py", line 602, in <module>
    main(opt)
  File "train.py", line 500, in main
    train(opt.hyp, opt, device)
  File "train.py", line 72, in train
    hyp = yaml.safe_load(f)  # load hyps dict
  File "C:\Anaconda3\envs\yolov5ts\lib\site-packages\yaml\__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "C:\Anaconda3\envs\yolov5ts\lib\site-packages\yaml\__init__.py", line 112, in load
    loader = Loader(stream)
  File "C:\Anaconda3\envs\yolov5ts\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "C:\Anaconda3\envs\yolov5ts\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "C:\Anaconda3\envs\yolov5ts\lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "C:\Anaconda3\envs\yolov5ts\lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
UnicodeDecodeError: 'cp950' codec can't decode byte 0xf0 in position 9: illegal multibyte sequence
```

## Expected behavior

I hope the issue to be resolve soon, or have another repository where it allows users to use previously stable version of YOLOv5.

## Environment

- OS: Windows 10 Pro 21H1 OS Build 19043.1165
- GPU: Nvidia GeForce RTX 3060

## Additional context

**Reproducible files**
[reproduce.zip](https://github.com/ultralytics/yolov5/files/7023064/reproduce.zip)

**Comment by wangyuan111** [comment]
**I also encountered the same problem**


```
root@bg:/yuan/coding/yolov5# python train.py --img-size 640 --batch-size 180 --epochs 300 --weights yolov5s.pt --data data/title.yaml --cfg models/yolov5s.yaml --devic 0 --workers 16  --project runs/train640png --hyp data/hyps/hyp.scratch.yaml --cachetrain: weights=yolov5s.pt, cfg=models/yolov5s.yaml, data=data/title.yaml, hyp=data/hyps/hyp.scratch.yaml, epochs=300, batch_size=180, imgsz=640, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, evolve=None, bucket=, cache=ram, image_weights=False, device=0, multi_scale=False, single_cls=False, adam=False, sync_bn=False, workers=16, project=runs/train640png, entity=None, name=exp, exist_ok=False, quad=False, linear_lr=False, label_smoothing=0.0, upload_dataset=False, bbox_interval=-1, save_period=-1, artifact_alias=latest, local_rank=-1, freeze=0

fatal: unable to access 'https://github.com/ultralytics/yolov5/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
github: Command 'git fetch && git config --get remote.origin.url' timed out after 5 seconds

Traceback (most recent call last):
  File "train.py", line 602, in <module>
    main(opt)
  File "train.py", line 500, in main
    train(opt.hyp, opt, device)
  File "train.py", line 72, in train
    hyp = yaml.safe_load(f)  # load hyps dict
  File "/usr/local/lib/python3.6/dist-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib/python3.6/dist-packages/yaml/__init__.py", line 112, in load
    loader = Loader(stream)
  File "/usr/local/lib/python3.6/dist-packages/yaml/loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "/usr/local/lib/python3.6/dist-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/usr/local/lib/python3.6/dist-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/usr/local/lib/python3.6/dist-packages/yaml/reader.py", line 178, in update_raw    data = self.stream.read(size)  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 35: ordinal not in range(128)
```

**Comment by RAO-CREATE** [comment]
I also encountered the same problem.
![image](https://user-images.githubusercontent.com/64192108/130717852-e759b0f4-d24c-4276-b651-7ade4b28009f.png)
OS: Windows 10
GPU: Nvidia GeForce RTX 3060

**Comment by wangyuan111** [comment]
I solved the problem by the following command，you can try
```
apt-get clean && apt-get update
apt-get install locales
locale-gen en_US.UTF-8
Generating locales (this might take a while)...
  en_US.UTF-8... done
Generation complete
```

**Comment by eecmyang** [comment]
> I solved the problem by the following command，you can try
> 
> ```
> apt-get clean && apt-get update
> apt-get install locales
> locale-gen en_US.UTF-8
> Generating locales (this might take a while)...
>   en_US.UTF-8... done
> Generation complete
> ```

That's nice, but my laboratory don't use Linux, it's sad, I know.

**Comment by RAO-CREATE** [comment]
Please give the commands for Windows 10 OS and GIT environment.

**Comment by kuonumber** [comment]
@eecmyang 
I try two methods to solve this issue.
1.  Downgrade to yolov5 version 4.
2.  Use the windows "Beta: Use Unicode UTF-8 for worldwide language support" function.

well...  both are not good enough but work.

**Comment by kuonumber** [comment]
@eecmyang
I try two methods to solve this issue.
You can choose anyone you prefer.
1. Downgrade to yolov5 version 4.
2. Use the windows "Beta: Use Unicode UTF-8 for worldwide language support" function.

Well... both are not good enough but workable.

**Comment by eecmyang** [comment]
> @eecmyang
> I try two methods to solve this issue.
> You can choose anyone you prefer.
> 
> 1. Downgrade to yolov5 version 4.
> 2. Use the windows "Beta: Use Unicode UTF-8 for worldwide language support" function.
> 
> Well... both are not good enough but workable.

I went with the first of your suggestions already. Second I haven't try, but I'll test on one of the laboratory's computers.

**Comment by RAO-CREATE** [comment]
I tried one among two methods to solve this issue i.e. use the windows "Beta: Use Unicode UTF-8 for worldwide language support" function. 
It worked well for me. Thank you.

**Comment by kensma** [comment]
Guys, I found the problem
The problem is here
[https://github.com/ultralytics/yolov5/blob/master/data/hyps/hyp.scratch.yaml](url)
Delete that damn "🚀"

**Comment by eecmyang** [comment]
> Guys, I found the problem
> The problem is here
> [https://github.com/ultralytics/yolov5/blob/master/data/hyps/hyp.scratch.yaml](url)
> Delete that damn "🚀"


Thank you for your trying and suggestion, but unfortunately, the issue remains unresolved.

![8_Sep_testing_deleted_rocket_icon](https://user-images.githubusercontent.com/51515246/132386445-3f4dd238-2a7e-43ca-b137-e9ab141bab55.jpg)

**Comment by kensma** [comment]
Same delete "🚀" in yolov5s.yaml

**Comment by eecmyang** [comment]
> Same delete "🚀" in yolov5s.yaml

Well, I guess the devil is indeed in the details, I can't believe that an icon in an annotation can cause this bizarre issue.

Thank you again. You solved this problem without any modification to the system or environment or commands, just simply deleting/modifying annotations in the files.


### Post edit_1:

In summary, for those in the future who encounter this issue/problem, just **delete the "🚀" (rocket icon) in the `.yaml` files, or remove that line of annotation that contains "🚀" (rocket icon).**
