### ISSUE TITLE
How to access/save YOLOv5 output as a variable in Python

### ISSUE THREAD

**Issue by andyclark41** [ultralytics/yolov5#4506]
## ❔Question
The output I see when detecting images using YOLOv5 is as follows:
'
detect: weights=['best.pt'], source=./Cam_Shots/Object.jpg, imgsz=[416, 416], conf_thres=0.4, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, tfl_int8=False
image 1/1 C:\Users\Path\Object.jpg: 416x416 **11 Circles, 5 Cubes**, Done. (0.284s)
Results saved to runs\detect\exp
Done. (0.308s)
'
I'm trying to extract the **11 Circles, 5 Cubes** from the output message to use elsewhere in my code - is there a way to access the output/save it to a variable  in python / Jupyter notebook.

**Comment by adrianholovaty** [comment]
@andyclark41 This took me a while to figure out as well. Here's one way to do it:

```python
import torch

# you'll first need to load your image via PIL, into the variable pil_img

model = torch.hub.load('ultralytics/yolov5', 'custom', '/path/to/your/custom/model.pt')
model.conf = 0.5 # minimum confidence threshold
results = model(pil_img, size=1280) # tweak size as needed
df = results.pandas().xyxy[0]
for index, row in df.iterrows():
    print(row['name'], row['xmin'], row['xmax'], row['ymin'], row['ymax'])
```

**Comment by glenn-jocher** [comment]
@andyclark41 in general see PyTorch Hub tutorial for python results:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by shreyasvedpathak** [comment]
> @andyclark41 This took me a while to figure out as well. Here's one way to do it:
> 
> ```python
> import torch
> 
> # you'll first need to load your image via PIL, into the variable pil_img
> 
> model = torch.hub.load('ultralytics/yolov5', 'custom', '/path/to/your/custom/model.pt')
> model.conf = 0.5 # minimum confidence threshold
> results = model(pil_img, size=1280) # tweak size as needed
> df = results.pandas().xyxy[0]
> for index, row in df.iterrows():
>     print(row['name'], row['xmin'], row['xmax'], row['ymin'], row['ymax'])
> ```

Incase you don't want pandas or a dataframe due to computation time or extra dependency, you can also do the following, notice the `n` at the end of `xyxyn`.
```python
labels = results.xyxyn[0][:, -1].numpy()
cord = results.xyxyn[0][:, :-1].numpy()
```

**Comment by andyclark41** [comment]
This is great - thanks for the help with this!
Solved my problem!
