### ISSUE TITLE
Add option to remove frames which don't detect objects in videos

### ISSUE THREAD

**Issue by sauravrao637** [ultralytics/yolov5#4507]
## 🚀 Feature
An option can be provided where frames with no objects can be removed/blacked out for reduced total output size and more relevance 

## Motivation
The output size is huge, and most use cases only need frames of videos where objects are detected. This will ensure only relevant frames are used and encoded

## Pitch
Black Frame replaced with the original or completely removed while writing the output.

**Comment by glenn-jocher** [comment]
@sauravrao637 hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
