### ISSUE TITLE
How do I make a video on TikTok?

### ISSUE THREAD

**Issue by ONNONS** [ultralytics/yolov5#4509]
## ❔Question

https://www.tiktok.com/@glennjocher/video/6997364044147543302?sender_device=pc&sender_web_id=6996620866949006850&is_from_webapp=v1&is_copy_url=0

How do I make a video on TikTok?

**Comment by glenn-jocher** [comment]
@ONNONS it's really easy, you just open the iDetection app and then start screen recording, then you can upload the screen recording to TikTok. See https://support.apple.com/en-us/HT207935
