### ISSUE TITLE
run model on Qualcomm chip

### ISSUE THREAD

**Issue by kevin780846** [ultralytics/yolov5#451]
## ❔Question
Has anyone tried to run yolov5s model on Qualcomm DSP to accelerate inference speed?

**Comment by glenn-jocher** [comment]
@kevin780846 are you referring to export to tflite format for Android? The export pipeline is pytorch > onnx > tflite. You can export to onnx using this repo, see the tutorials https://docs.ultralytics.com/yolov5

**Comment by kevin780846** [comment]
@glenn-jocher thanks for your reply.
I have successfully convert pytorch >> tflite,  but somehow it still can't work when I try to run the model on DSP, but CPU and GPU worked. So, I'm curious about that is there anyone run on Qualcomm SNPE chip(e.g. S820 or other chip supported DSP acceleration) using DSP  successfully.

**Comment by mchalecki** [comment]
> @glenn-jocher thanks for your reply.
> I have successfully convert pytorch >> tflite, but somehow it still can't work when I try to run the model on DSP, but CPU and GPU worked. So, I'm curious about that is there anyone run on Qualcomm SNPE chip(e.g. S820 or other chip supported DSP acceleration) using DSP successfully.

How did you convert it? After converting to onnx I try to convert to tensorflow using latest [onnx-tensorflow](https://github.com/onnx/onnx-tensorflow) but I receive.
`Unknown op ImageScaler in domain ai.onnx`
`Unknown op ConstantFill in domain ai.onnx`.
What version of tensorflow and onnx-tensorflow did you use?
