### ISSUE TITLE
Some questions about parameter adjustment of YOLOV5

### ISSUE THREAD

**Issue by yangtiming** [ultralytics/yolov5#4514]
## ❔Question
Background:  I take part in a Underwater Object Detection competition ，there are the number of 8200 pictures in training dataset , 350 in val dataset. I use yolov5x6. GPU : 2080ti.

when training:
#### _python train.py  --weights weights/yolov5x6.pt --cfg models/hub/yolov5x6.yaml --data data/underwater.yaml --hyp data/hyps/hyp.scratch-p6.yaml --epochs 25 --batch-size 2 --img 1280_

 There are some questions about parameter adjustment of YOLOV5：

 1. Yolov5x6 is the largest model in the yolov5, it costs lots of time to train. Can I train in the smaller model, like yolov5x , YOLOv5m etc? And then , adjust parameters in the smaller model. After performing well in the smaller model, and then I change model back to Yolov5x6. Can it perform well in Yolov5x6 ,too?
 
 2.  In  the "Tips for Best Training Results", We need start with 300 epochs. However , it costs too much time for me to  start with 300 epochs to judge if some of the parameters are helpful or not. So, what is the minimum epoch to determine whether the parameter Settings are helpful or not？
 
 3. In the file named "data/hyps/hyp.scratch-p6.yaml", there are lots of hyperparameter,like hsv_(h,s,v) , mosaic etc. Taking “ mosaic: 1.0” as an example, I don't think "mosaic: 1.0" is good for mAP in my task. So in my view, I want to setting it to "mosaic: 0.0". If I set it to "mosaic: 0.0", will it do harm to mAP? (I mean, whether the hyperparameter “mosaic: 1.0” is an optimization parameter specific to the YOLOv5-P6, if I adjust it, then the mAP score will go down？ )

**Comment by glenn-jocher** [comment]
@yangtiming yes, tuning on a smaller model and then applying those to a larger model is a common strategy in AI. You generally want to train until you observe overfitting and then adjust as the guide states.

Updating hyps will produce varying results based on your dataset, hyps and training settings. You would have to experiment on your custom dataset to determine the optimal hyps there. The current hyps in scratch are evolved for training COCO from scratch, commands to reproduce provided in README.

If your competition is popular, please consider submitting a PR for your data yaml to allow others to get started faster, thanks!
