### ISSUE TITLE
what is moasic and what is its default and how to delete it

### ISSUE THREAD

**Issue by besbesmany** [ultralytics/yolov5#4517]
what is the meaning of moasic

where I can find its default parameter

how to stop moasic and  stop augmentation in general

I use only this line is it augment data by default or not? how to stop augmentation if exist 
```
!python train.py --img 640 --batch 16 --epochs 400 --data /mydrive/data.yaml \
  --weights /mydrive/yolov5s.pt --cache --project /mydrive/train/
```

**Comment by glenn-jocher** [comment]
@besbesmany all augmentation hyperparameters are defined in your hyperparameter file, typically hyp.scratch.yaml:
https://github.com/ultralytics/yolov5/blob/79af1144c270ac7169553d450b9170f9c60f92e4/data/hyps/hyp.scratch.yaml#L6-L34

**Comment by besbesmany** [comment]
is this file work by default or not?
what is the meaning mosaic probability =1?
is this run use hyp.scratch.yaml or not?
```
!python train.py --img 640 --batch 16 --epochs 400 --data /mydrive/data.yaml \
  --weights /mydrive/yolov5s.pt --cache --project /mydrive/train/
```

**Comment by glenn-jocher** [comment]
@besbesmany hyps are described in comments next to each.

**Comment by besbesmany** [comment]
how to stop calling hyp.scratch.yaml?

or I should zero assign all hyps?

**Comment by glenn-jocher** [comment]
@besbesmany update your hyp values as you see fit.
