### ISSUE TITLE
YOLOv5 model architecture overview

### ISSUE THREAD

**Issue by dariogonle** [ultralytics/yolov5#4518]
## ❔Question

Is this architecture overview, mentionated in https://github.com/ultralytics/yolov5/issues/280, still valid?

![image](https://user-images.githubusercontent.com/80393891/130479559-3439a3e8-a845-4268-9738-551972e46208.png)

**Comment by glenn-jocher** [comment]
@dariogonle we've made visualizing YOLOv5 🚀 architectures super easy. There are two main ways:

## `model.yaml`

Each model has a corresponding yaml file that displays the model architecture. Here is YOLOv5s, defined by `yolov5s.yaml`:
https://github.com/ultralytics/yolov5/blob/79af1144c270ac7169553d450b9170f9c60f92e4/models/yolov5s.yaml#L12-L48

## TensorBoard Graph

Simply start training a model, and then view the TensorBoard Graph for an interactive view of the model architecture. This example shows YOLOv5s viewed in our [Notebook](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb) –  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

```python
# Tensorboard
%load_ext tensorboard
%tensorboard --logdir runs/train

# Train YOLOv5s on COCO128 for 3 epochs
python train.py --weights yolov5s.pt --epochs 3
```

<img width="893" alt="Screenshot 2021-04-11 at 01 10 09" src="https://user-images.githubusercontent.com/26833433/114286928-349bd600-9a63-11eb-941f-7139ee6cd602.png">

**Comment by ppogg** [comment]
That‘s cool. I like it!

**Comment by ehdrndd** [comment]
i draw it easy to see
![image](https://user-images.githubusercontent.com/81725328/131593996-c290bc86-48a1-4e91-b52b-53c40ab8befb.png)

**Comment by Layusmen** [comment]
> 
> 
> i draw it easy to see
> ![image](https://user-images.githubusercontent.com/81725328/131593996-c290bc86-48a1-4e91-b52b-53c40ab8befb.png)

how did you achieve this please?
