### ISSUE TITLE
Question & Enhancement about the code in ap_per_class

### ISSUE THREAD

**Issue by seekFire** [ultralytics/yolov5#452]
## ❔Question
In utils/utils.py, function **ap_per_class**, both the variable **p** and **r** have shape of (unique_classes.shape[0], tp.shape[1]), 
It will shows precision/recall of different class under different IoU threshold, but the code shown as follows will makes **p**/**r** hold the value only under the condition of IoU=0.5:
`r[ci] = np.interp(-pr_score, -conf[i], recall[:, 0])`
`p[ci] = np.interp(-pr_score, -conf[i], precision[:, 0])`

So I think these two lines should be moved into the loop near after them (line 260):

```
for j in range(tp.shape[1]):
    ap[ci, j] = compute_ap(recall[:, j], precision[:, j])
    r[ci, j] = np.interp(-pr_score, -conf[i], recall[:, j])
    p[ci, j] = np.interp(-pr_score, -conf[i], precision[:, j])
```

## Additional context
One more question is about the input parameter of function **ap_per_class**
According to the code in test.py (line 169-181), we know one of the input parameter of function **ap_per_class**: **conf**, is equal to **pred[:, 4]**, which comes from the output of **non_max_suppression** (test.py, line 98-102), however, In function **non_max_suppression**, the **conf** represents the class probabilities (utils/utils.py, line 594~606) which is calculated by the code:
`x[:, 5:] *= x[:, 4:5]`
this equation means **P(cls) = P(cls|is_obj) * P(is_obj)**, as we know we should use **conf** to represent IoU threshold(0.5:0.95:0.05), rather than class probabilities, so I just wonder that whether this setting is reasonable...

**Comment by glenn-jocher** [comment]
@seekFire thanks for the thorough code review and raising this issue! Before any deep dive into the code, you should run test.py before and after your changes to verify that they don't break anything and to quantify how they would impact the mAP calculations. So download and run this command (ensure you have pycocotools installed) with your proposed code change:

```bash
git clone https://github.com/ultralytics/yolov5  # clone repo
pip install -qr yolov5/requirements.txt pycocotools  # install dependencies
bash yolov5/data/get_coco2017.sh
%cd yolov5
python test.py --data coco.yaml  # BEFORE
python test.py --data coco.yaml  # AFTER
```
