### ISSUE TITLE
yolo.py does not run with --profile argument

### ISSUE THREAD

**Issue by wmcnally** [ultralytics/yolov5#4529]
Error in Detect module:

RuntimeError: Expected 4-dimensional input for 4-dimensional weight [255, 128, 1, 1], but got 5-dimensional input of size [1, 3, 80, 80, 85] instead

**Comment by glenn-jocher** [comment]
@wmcnally thanks for the bug report. This is a known issue that's been outstanding for a long time. I'll see if I can expedite a fix.
