### ISSUE TITLE
Why there are 3 or 8 points of each model in the README performance figure?

### ISSUE THREAD

**Issue by imyhxy** [ultralytics/yolov5#4532]
Hi, there. I was confused that why there are mulitple points of each model in performance fiugre. For example: why the `yolov5l6` has 8 `speed-mAP` results? Does this results come from different confidence threshold?

<p align="center"><img width="800" src="https://user-images.githubusercontent.com/26833433/114313216-f0a5e100-9af5-11eb-8445-c682b60da2e3.png"></p>

<p align="center"><img width="800" src="https://user-images.githubusercontent.com/26833433/114313219-f1d70e00-9af5-11eb-9973-52b1f98d321a.png"></p>

**Comment by glenn-jocher** [comment]
@imyhxy evaluation over a range of `--img-size`
