### ISSUE TITLE
custom() got an unexpected keyword argument 'path'

### ISSUE THREAD

**Issue by robmarkcole** [ultralytics/yolov5#4533]
## ❔Question
I've trained a model following [Train-Custom-Data](https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data) and have my `best.pt` file. I wish to use in a gradio app (following your example [here](https://github.com/AK391/yolov5/blob/master/utils/gradio/demo.py)). I searched the docs and eventually found how to load a custom model in an issue, but the approach below results in an error:
```
model = torch.hub.load('/Users/robin/Github/yolov5', 'custom', path='experiment1/best.pt', source='local')  # local repo

TypeError: custom() got an unexpected keyword argument 'path'
```

Please can you advise on correct usage. Also is it necessary to have git cloned the yolov5 repo as in the example above?

## Additional context
Would be great to get the solution added to https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data

**Comment by robmarkcole** [comment]
Alright simply not naming the arg as below resolved the issue, so I assume torch hub api was updated since this example was documented:
```
model = torch.hub.load('/Users/robin/Github/yolov5', 'custom', 'experiment1/best.pt', source='local')  # local repo
```

**Comment by glenn-jocher** [comment]
@robmarkcole works correctly on my system following the PyTorch Hub tutorial:

```python
model = torch.hub.load('.', 'custom', path='yolov5s.pt', source='local')

YOLOv5 🚀 v5.0-379-g2da6444 torch 1.9.0 CPU
Fusing layers... 
Model Summary: 224 layers, 7266973 parameters, 0 gradients
Adding AutoShape... 
```

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)
