### ISSUE TITLE
Run inference with custom weights: KeyError: 'model'

### ISSUE THREAD

**Issue by nadine-alexandra** [ultralytics/yolov5#4534]
I have trained my own data set on YOLOv5s which worked perfectly fine. Now I want to predict an image with the resulting weights (best.pt). My code looks like this:

`device = torch.device('cuda:1')`
`model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=False)`
`checkpoint = torch.load([path/to/best.pt], map_location=device)['model']`
`model.load_state_dict(checkpoint.state_dict(), strict=False, map_location=device)`

But I get this error message: "KeyError: 'model'"

Can you please tell me what I am doing wrong and how I can run the inference with my own trained weights?

Thanks!

**Comment by shreyasvedpathak** [comment]
Check this out #36

**Comment by nadine-alexandra** [comment]
@shreyasvedpathak Thank you for your comment. I've already read this, but the example under custom model uses torch.hub.load, so the weights are downloaded from a repository. I would like to just load a weights file that is stored locally on the computer and not donwload it.

**Comment by shreyasvedpathak** [comment]
@nadine-alexandra I'm extremely sorry I thought that issue had explained this. Apologies.
This is how you do it:

Here,
- the first argument is the 'yolov5' directory
- the second argument is 'custom', it tells that you want to load a custom model
- the third argument is the path to the weights file (.pt)
- fourth is the source, 'local' again means custom model saved on your machine

```python
import torch

model = torch.hub.load('yolov5', 'custom',
                       path='path/to/weights.pt',
                       source='local')

results = model(frame)

# then I guess you know what to do
```

Again, I'm sorry, I should have read it completely. I remember reading the above solution somewhere but I don't know exactly where and I thought that issue had it 😓

Edit: Found it, more explanation [here](https://pytorch.org/docs/stable/hub.html#torch.hub.load).

**Comment by nadine-alexandra** [comment]
@shreyasvedpathak Thank you so much for your help, I will try it again with your solution.

Edit: I have just seen that you added the link to the documentation. This is so great, thank you!
