### ISSUE TITLE
How many screenshots are needed for a 2d game training set

### ISSUE THREAD

**Issue by William-Scott** [ultralytics/yolov5#4537]
## ❔Question
How many screenshots are needed for a 2d game training set
## Additional context
I'm making an image recognition program for a fast-paced 2d game. I need to make a training set from 0. Because I'm the only one doing it, the workload may be very large, so I want to ask, how many screenshots I need to mark at least In order to train a better core. The game can run at 640*480 resolution, 60 frames, and the targets resolution is about 64*64 pixels.

**Comment by shreyasvedpathak** [comment]
@William-Scott I recently did something similar and got excellent results with 250-300 images using transfer learning with pre-trained weights (COCO 2017). You can also add augmentation to these images. However, I don't think you'll have many difficulties with fewer images if you use pre-trained weights.
