### ISSUE TITLE
how to get F score of data

### ISSUE THREAD

**Issue by besbesmany** [ultralytics/yolov5#4539]
where to find F score?

**Comment by glenn-jocher** [comment]
@besbesmany F1 score is computed by val.py but not displayed for brevity. You can compute it yourself given P and R (see https://en.wikipedia.org/wiki/F-score), or you can customize the code to output it here:

https://github.com/ultralytics/yolov5/blob/11f85e7e71d91810460a2eee22235a2264b458eb/val.py#L231
