### ISSUE TITLE
why same dataset, same batchsize, same params but  diff device ,the GPU Memory  different?

### ISSUE THREAD

**Issue by jaffe-fly** [ultralytics/yolov5#4544]
## ❔Question
i am train yolov5s in my own dataset,and i found that 
why same dataset, same batchsize, same params but  diff device ,the GPU Memory  different?
can anyone explain this?

**Comment by glenn-jocher** [comment]
@jaffe-fly resource utilization will vary by hardware, drivers (CUDA) and software (python, torch, YOLOv5).
