### ISSUE TITLE
label smoothing

### ISSUE THREAD

**Issue by simplecode123** [ultralytics/yolov5#4545]
## ❔Question
Hi guys, when I training yolov5 what's mean label_smoothing=0.0? It's mean label smoothing off or on? If it means off then how can I turn it on  label smoothing?

**Comment by glenn-jocher** [comment]
@LazzzyDumbass label smoothing is zero by default. You can assign a nonzero value very simply with the train.py argparser:

```
python train.py --label-smoothing 0.01
```
