### ISSUE TITLE
About Genetic Algorithm 

### ISSUE THREAD

**Issue by jaqub-manuel** [ultralytics/yolov5#4547]
Hello Dear @glenn-jocher,
 I would like to try algorithms such as differential evolution algorithm or particle swarm opt. alg. for hyper parameter optimization, apart from genetic algorithm. Where should I start or what should I change in the code part? Many thanks in advance.

**Comment by glenn-jocher** [comment]
@jaqub-manuel GA code is here that creates a new generation (population 1) to evaluate:
https://github.com/ultralytics/yolov5/blob/11f85e7e71d91810460a2eee22235a2264b458eb/train.py#L547-L577
