### ISSUE TITLE
How to change the No of Steps per epoch?

### ISSUE THREAD

**Issue by Darshcg** [ultralytics/yolov5#4555]
Hi @glenn-jocher 

I am training YoloV5m on 3.9 Million Images using 8 A100 GPUs with batch size 128.
For each epoch, it is taking around two and a half hours. So, I want to reduce the number of steps per epoch to complete one epoch within half an hour and get the checkpoint. How do I achieve it?

Thanks,
Darshan C G

**Comment by glenn-jocher** [comment]
@Darshcg 👋 Hello! Thanks for asking about **training speed issues**. YOLOv5 🚀 can be trained on CPU (slowest), [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) (fastest). If you would like to increase your training speed some options are:

- Increase `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s
- Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) DDP at larger `--batch-size`
- Train with a cached dataset: `python train.py --cache`
- Train on faster GPUs, i.e.: P100 -> V100 -> A100
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

**Comment by din682** [comment]
Hi @Darshcg 
Did you find any solution?

**Comment by hansroh** [comment]
```
from ultralytics import YOLO
from ultralytics.data import build

STEPS_PER_EPOCH = 2048
STEPS_VALIDATION = 128

class InfiniteDataLoader (build.InfiniteDataLoader):
    def __len__ (self):
        return min (
            len (self.batch_sampler.sampler),
            STEPS_PER_EPOCH if self.dataset.augment else STEPS_VALIDATION
        )
build.InfiniteDataLoader = InfiniteDataLoader

yolo = YOLO ("yolov11n.pt")
```

**Comment by pderrenger** [comment]
To adjust the number of steps per epoch, you can modify the `__len__` method in your custom `InfiniteDataLoader` as you've done. Ensure this change is integrated correctly with your training loop. If you encounter issues, verify compatibility with the latest YOLOv5 version.
