### ISSUE TITLE
AssertionError: Label class 33 exceeds nc=3 in ././models/yolov5s.yaml. Correct your labels or your model.

### ISSUE THREAD

**Issue by sarj7** [ultralytics/yolov5#4559]
i'm getting this error while training yolov5 on custom dataset. i have tried to resolve this error by following [this thread](https://github.com/ultralytics/yolov5/issues/424). i have made sure that i have nc = 3 in dataset.yaml file as well as nc = 3 in yolov5s.yaml file as well. 

![Screenshot from 2021-08-27 12-31-52](https://user-images.githubusercontent.com/19946676/131086781-4a875cf7-f665-4dd3-af36-dfafe1a9d541.png)

i deleted the cache file as well. i've also made sure that .txt label file for each individual image has classes as 0,1 or 2. i don't where does this model picks number of classes = 33. 

please help!

**Comment by glenn-jocher** [comment]
@sarj7 the error message is self explanatory. Your labels contain classes up to 33, which is about 30 more classes than you've stated in your data.yaml.
