### ISSUE TITLE
Coreml model not working

### ISSUE THREAD

**Issue by abhimanyuchadha96** [ultralytics/yolov5#4568]
Simply using the export file provided with the repo to convert a pretrained model to coreML.
Got this 'unexpected error'
![Screen Shot 2021-08-27 at 1 01 22 PM](https://user-images.githubusercontent.com/37940438/131163219-a5d6a3e0-f1d2-4357-80d9-09138ef4b6ec.png)

**Comment by abhimanyuchadha96** [comment]
@glenn-jocher

**Comment by tcollins590** [comment]
Did you solve this?
