### ISSUE TITLE
Getting no results on Raspberry Pi 4

### ISSUE THREAD

**Issue by andrelind** [ultralytics/yolov5#4570]
## 🐛 Bug

I've installed this on my Raspberry multiple times now ut I can't get no results from it
Used [this guide](https://qengineering.eu/install-pytorch-on-raspberry-pi-4.html) to setup Pytorch, both by downloading wheels or built them myself

## To Reproduce (REQUIRED)

Follow the guide and then just try to run the example

Input:

```
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, custom

# Images
img = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, PIL, OpenCV, numpy, list

# Inference
results = model(img)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
```

Output:

```
Using cache found in /home/pi/.cache/torch/hub/ultralytics_yolov5_master
YOLOv5 🚀 2021-8-27 torch 1.9.0a0+gitd69c22d CPU

Fusing layers... 
Model Summary: 224 layers, 7266973 parameters, 0 gradients
Adding AutoShape... 
image 1/1: 720x1280 (no detections)
Speed: 497.1ms pre-process, 2042.2ms inference, 2.3ms NMS per image at shape (1, 3, 384, 640)
```

## Environment

- OS: [Raspberry OS 64 bit]
- CPU

**Comment by icenaive** [comment]
> ## 🐛 Bug
> I've installed this on my Raspberry multiple times now ut I can't get no results from it
> Used [this guide](https://qengineering.eu/install-pytorch-on-raspberry-pi-4.html) to setup Pytorch, both by downloading wheels or built them myself
> 
> ## To Reproduce (REQUIRED)
> Follow the guide and then just try to run the example
> 
> Input:
> 
> ```
> import torch
> 
> # Model
> model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, custom
> 
> # Images
> img = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, PIL, OpenCV, numpy, list
> 
> # Inference
> results = model(img)
> 
> # Results
> results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
> ```
> 
> Output:
> 
> ```
> Using cache found in /home/pi/.cache/torch/hub/ultralytics_yolov5_master
> YOLOv5 🚀 2021-8-27 torch 1.9.0a0+gitd69c22d CPU
> 
> Fusing layers... 
> Model Summary: 224 layers, 7266973 parameters, 0 gradients
> Adding AutoShape... 
> image 1/1: 720x1280 (no detections)
> Speed: 497.1ms pre-process, 2042.2ms inference, 2.3ms NMS per image at shape (1, 3, 384, 640)
> ```
> 
> ## Expected behavior
> A clear and concise description of what you expected to happen.
> 
> ## Environment
> If applicable, add screenshots to help explain your problem.
> 
> * OS: [Raspberry OS 64 bit]
> * CPU
> 
> ## Additional context
> Add any other context about the problem here.

do you have any answer?i have see same bug on my raspberry, the os is ubuntu server 20.04 LTS

**Comment by andrelind** [comment]
I can get it to work on 32bit Raspberry Pi 4 but with 64bit I get no results :-/

**Comment by icenaive** [comment]
you can try v3.1 pt, i get result with this version, but i don't why

**Comment by kuonumber** [comment]
I faced the same problem, and I found the reason in my case was "core dumped".
That is,  raspberry pi can not entirely support latest pytorch version.
I try to downgrade pytorch and then everything fine.
Here is my requrirements.txt used for my pi 4.

```
# requirements.txt
matplotlib>=3.2.2  
numpy==1.20.0  
opencv-python>=4.1.2  
Pillow  
PyYAML>=5.3.1  
scipy>=1.4.1  
torch==1.8.0  
torchvision==0.9.1  
tqdm>=4.41.0  
```

**Comment by xiaoleitongxue** [comment]
I met same problem on nvidia jetson nano, I thought this problem is caused by compatibility, Jetson nano unable to run latest version model.
I solved it by downgrading yolov5s.pt weights file to version 3.1.

**Comment by glenn-jocher** [comment]
@xiaoleitongxue thank you for sharing your experience and solution. It is possible that compatibility issues can arise when running YOLOv5 on certain devices like the Nvidia Jetson Nano. Downgrading the YOLOv5s.pt weights file to version 3.1 can indeed resolve such problems. Your input will certainly help others facing similar issues on the Jetson Nano. If you have any further questions or need assistance, please feel free to ask.
