### ISSUE TITLE
When will the V6.0 come out?

### ISSUE THREAD

**Issue by TommyZihao** [ultralytics/yolov5#4571]
Hi, I want to make a video tutorial of using YOLOV5, when will the new V6.0 come out, and I can be ready for it.
My video channel : https://space.bilibili.com/1900783

**Comment by iceisfun** [comment]
Normally the changes between versions have been minimal to non existent for upgrading.

I've been able to just git pull and train.

Maybe start making your video focusing on the main thing people need help with and explaining the importance of data. Lots of people try and skip out on their data and get bad results.

https://docs.ultralytics.com/guides/model-training-tips/

**Comment by TommyZihao** [comment]
> Normally the changes between versions have been minimal to non existent for upgrading.
> 
> I've been able to just git pull and train.
> 
> Maybe start making your video focusing on the main thing people need help with and explaining the importance of data. Lots of people try and skip out on their data and get bad results.
> 
> https://docs.ultralytics.com/guides/model-training-tips/

thanks!

**Comment by pderrenger** [comment]
@TommyZihao thank you for your input! We recommend focusing on data quality and training tips, as these are crucial for achieving good results. For updates on new releases, please keep an eye on the GitHub repository.
