### ISSUE TITLE
How would I call individual layers of the network? yolov5

### ISSUE THREAD

**Issue by levnagy** [ultralytics/yolov5#4575]
Hi, 

I would like to use the last convolutional layer for gradcam visualizations, but I am not sure how to call the layer.
I can list them using this code I found in another issue, but thats as far as I get.
```

model = torch.hub.load('ultralytics/yolov5','yolov5s', autoshape=False)
print(model)


for k, v in model.named_parameters():
    print(k)
```

Output looks like this:
![image](https://user-images.githubusercontent.com/24868118/131220856-8470f60e-cd2b-47a0-a6c2-8782bc613a63.png)

Ideally, I would wanna be able to select the layer so as to use as part of this code:
![image](https://user-images.githubusercontent.com/24868118/131220885-667ac0cc-ac57-4319-afb2-6fe0cab7fa7c.png)

Where, instead of resnet I would call yolov54 (snippet above), and select the last convolutional layer for visualization.

Hopefully this is feasible. Advices are appriciated.

**Comment by glenn-jocher** [comment]
@Sarkanyhazy you can select any layer by indexing `model.model`:

```python
import torch

model = torch.hub.load('ultralytics/yolov5','yolov5s', autoshape=False)
model.model[0]

Out[5]: 
Focus(
  (conv): Conv(
    (conv): Conv2d(12, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (act): SiLU(inplace=True)
  )
)
```

**Comment by levnagy** [comment]
Thanks for your help Glenn!

**Comment by phanisai22** [comment]
> @Sarkanyhazy you can select any layer by indexing `model.model`:
> 
> ```python
> import torch
> 
> model = torch.hub.load('ultralytics/yolov5','yolov5s', autoshape=False)
> model.model[0]
> 
> Out[5]: 
> Focus(
>   (conv): Conv(
>     (conv): Conv2d(12, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
>     (act): SiLU(inplace=True)
>   )
> )
> ```



Hi, 
I tried the above code and i'm getting this error.



![image](https://user-images.githubusercontent.com/42872894/148178414-03d051a0-b4b7-4d25-9df9-57bcd853159f.png)

**Comment by Michelvl92** [comment]
@phanisai22 did you solve this?

@Sarkanyhazy how did you solved this in total with gradcam?

**Comment by Michelvl92** [comment]
@glenn-jocher this should be: `model.model.model[0]`?

But this still gives me an error:

```
Using cache found in /root/.cache/torch/hub/ultralytics_yolov5_master
YOLOv5 🚀 v6.0-232-g079b36d torch 1.10.1+cu113 CPU

Fusing layers... 
Model Summary: 213 layers, 7225885 parameters, 0 gradients
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_6269/3117303927.py in <module>
     24 cam = EigenCAM(model, target_layers, use_cuda=False)
     25 
---> 26 grayscale_cam = cam(tensor)
     27 # # Take the first image in the batch:
     28 # # grayscale_cam = grayscale_cam[0, :]

/opt/conda/lib/python3.8/site-packages/pytorch_grad_cam/base_cam.py in __call__(self, input_tensor, targets, aug_smooth, eigen_smooth)
    182                 input_tensor, targets, eigen_smooth)
    183 
--> 184         return self.forward(input_tensor,
    185                             targets, eigen_smooth)
    186 

/opt/conda/lib/python3.8/site-packages/pytorch_grad_cam/base_cam.py in forward(self, input_tensor, targets, eigen_smooth)
     80             self.model.zero_grad()
     81             loss = sum([target(output) for target, output in zip(targets, outputs)])
---> 82             loss.backward(retain_graph=True)
     83 
     84         # In most of the saliency attribution papers, the saliency is

/opt/conda/lib/python3.8/site-packages/torch/_tensor.py in backward(self, gradient, retain_graph, create_graph, inputs)
    305                 create_graph=create_graph,
    306                 inputs=inputs)
--> 307         torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
    308 
    309     def register_hook(self, hook):

/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables, inputs)
    152         retain_graph = create_graph
    153 
--> 154     Variable._execution_engine.run_backward(
    155         tensors, grad_tensors_, retain_graph, create_graph, inputs,
    156         allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

**Comment by glenn-jocher** [comment]
@Michelvl92 your error is unrelated to YOLOv5. i.e. https://discuss.pytorch.org/t/runtimeerror-element-0-of-variables-does-not-require-grad-and-does-not-have-a-grad-fn/11074

**Comment by HarrySoteriou** [comment]
> > @Sarkanyhazy you can select any layer by indexing `model.model`:
> > ```python
> > import torch
> > 
> > model = torch.hub.load('ultralytics/yolov5','yolov5s', autoshape=False)
> > model.model[0]
> > 
> > Out[5]: 
> > Focus(
> >   (conv): Conv(
> >     (conv): Conv2d(12, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
> >     (act): SiLU(inplace=True)
> >   )
> > )
> > ```
> 
> Hi, I tried the above code and i'm getting this error.
> 
> ![image](https://user-images.githubusercontent.com/42872894/148178414-03d051a0-b4b7-4d25-9df9-57bcd853159f.png)

I got it to work by indexing model 4 times

python
```
model = torch.hub.load(repo_or_dir=ROOT, model="custom", source='local', path=weights) #.to(device)
#summary(model, input_size=(1, 3, 416, 416), depth=5, verbose=1)

print(model.model.model.model[:10])
```
