### ISSUE TITLE
How can i apply the model if my image is 5000*5000 or larger?

### ISSUE THREAD

**Issue by Coderxiaobai1** [ultralytics/yolov5#458]
## ❔Question
Hi, thanks for your contribution. Should i crop the image to 640*640 as the training set, and in the inference stage, just do the same job and stich them to get an output?

**Comment by glenn-jocher** [comment]
@Coderxiaobai1 there's no size constraint. Train, test and detect at any `--img-size` you want.

**Comment by Coderxiaobai1** [comment]
thanks, with best wishes for your health.

**Comment by Coderxiaobai1** [comment]
so what is the difference between the 640 and 1280 or even 2560 when in the training stage? just the speed?

**Comment by glenn-jocher** [comment]
@Coderxiaobai1 these are the sizes of the images in pixels that the network inputs. You should train and test at the same sizes, but the size you use is up to you.

**Comment by madaosik** [comment]
Hello @glenn-jocher , I am also kind of confused by the `--img_size ` argument. In my case I am using 50x200 images - what is the resulting image size for training with the default `--img_size 640` (given that the height and width differ)? Does it even make sense in my case? I trained a model and ran the inference for the 50x200 images and the resulting bounding boxes were so huge that it covered the object itself (see the enclosed screenshot). Any suggestion is appreciated!
![image](https://user-images.githubusercontent.com/34263128/88043527-d3874780-cb4d-11ea-9302-e68457000f62.png)

**Comment by gaurav0535** [comment]
Hi I have data set with different different size do i need to resize all to make the same size/shape ?

I am having --1280*1706,453 × 300,1200 × 675

**Comment by ghost** [comment]
According to my practice,it's only my practice，this  img_size(training and inference) It's better to keep the size parameter consistent, but it's OK to approach it. If you want to train big pictures, please provide better GPU and increase img_ size.

**Comment by gaurav0535** [comment]
I need to annotate my data , I will use some tools to create that but the question is do I need to resize(img_size) the images before annotations as the images are different in size or YoloV5 will take care of it as TensorFlow object detection does?

**Comment by glenn-jocher** [comment]
@gaurav0535 train.py runs at any --img-size you specify, default is 640 `python train.py --img 640`

**Comment by gaurav0535** [comment]
@glenn-jocher Thanks man for your prompt reply
