### ISSUE TITLE
modify weights of a pretrained yolov5 and evaluate model with new weights

### ISSUE THREAD

**Issue by PariaDarbani** [ultralytics/yolov5#4580]
Hi.
I trained yolov5s. I changed a random number of weights and re-save the model as a new *.pt to evaluating and finding mAP difference.
model.load_state_dict(model_New_weights) 
torch.save(model.state_dict(), 'newModel.pt')

But I can't evaluate newModel.pt because of some errors:

  File "..\yolov5-master\yolov5-master\val.py", line 356, in <module>
    main(opt)
  File "..\yolov5-master\yolov5-master\val.py", line 331, in main
    run(**vars(opt))
  File "..\python\lib\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "..\yolov5-master\yolov5-master\val.py", line 116, in run
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "..\yolov5-master\yolov5-master\models\experimental.py", line 120, in attempt_load
    model.append(ckpt['ema' if ckpt.get('ema') else 'model'].float().fuse().eval())  # FP32 model
KeyError: 'model'

**Comment by glenn-jocher** [comment]
@PariaDarbani val.py is used for mAP computation:
```
python val.py --weights yolov5s.pt --data coco128.yaml
```

Detect.py is a fully managed CLI inference solution: 
```
python detect.py --weights yolov5s.pt --source data/images
```

For custom python inference see PyTorch Hub tutorial:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by PariaDarbani** [comment]
> @PariaDarbani val.py is used for mAP computation:
> 
> ```
> python val.py --weights yolov5s.pt --data coco128.yaml
> ```
> 
> Detect.py is a fully managed CLI inference solution:
> 
> ```
> python detect.py --weights yolov5s.pt --source data/images
> ```
> 
> For custom python inference see PyTorch Hub tutorial:
> 
> ## YOLOv5 Tutorials
> * [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)  🚀 RECOMMENDED
> * [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)  ☘️ RECOMMENDED
> * [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)  🌟 NEW
> * [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)  🌟 NEW
> * [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
> * [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)  ⭐ NEW
> * [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
> * [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
> * [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
> * [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
> * [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
> * [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)  ⭐ NEW
> * [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

Thank you.
I think there is something wrong with saving my new *.pt file. I can evaluate the best.pt but evaluating NewWeight.pt get errors that reported.

**Comment by pderrenger** [comment]
@PariaDarbani it seems like the new weights file might not be saved correctly. Ensure that the model's state_dict includes all necessary keys before saving. You might want to compare it with the structure of `
