### ISSUE TITLE
about feature

### ISSUE THREAD

**Issue by YL-yyy** [ultralytics/yolov5#4582]
## ❔Question
If I want to train and let it output feature maps, what should I do

**Comment by glenn-jocher** [comment]
@YL-yyy I don't understand your question. You can access the output feature maps directly in Detect layer():
https://github.com/ultralytics/yolov5/blob/d7aa3f153d049b89267b1b594a481a1a27fe27e6/models/yolo.py#L33-L72

**Comment by YL-yyy** [comment]
Thank you for your reply.
 I want to visual the feature map of each layer when model training, how can I do this just like the [commit](87b094bcbcf209c89febcc9a3bb0ae119fee882d) do in detect.py

**Comment by glenn-jocher** [comment]
@YL-yyy 👋 Hello! Thanks for asking about **feature visualization**. YOLOv5 🚀 features can be visualized through all stages of the model from input to output. To visualize features from a given source run `detect.py` with the `--visualize` flag:
```bash
python detect.py --weights yolov5s.pt --source data/images/bus.jpg --visualize
```

An example [Notebook](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb) visualizing [bus.jpg](https://github.com/ultralytics/yolov5/blob/master/data/images/bus.jpg) features with YOLOv5s is shown below:

<a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
<img width="1811" alt="Screenshot 2021-08-30 at 16 44 04" src="https://user-images.githubusercontent.com/26833433/131357928-663a120a-3133-4e1a-8995-c812bd732e8a.png">

All stages are visualized by default, each with its own PNG showing the first 32 feature maps **output** from that stage. You can open any PNG for a closer look. For example the first 32 feature maps of the Focus() layer output are shown in `stage0_Focus_features.png`:

![stage0_Focus_features](https://user-images.githubusercontent.com/26833433/131359874-ecc9aef8-1c9b-44f5-ac17-d6b987093554.png)

Feature maps may be customized by updating the `feature_visualization()` function in `utils/plots.py`:
https://github.com/ultralytics/yolov5/blob/bb5ebc290e5d630a081d7cbc5a9725ed8cea0a24/utils/plots.py#L403-L427

**Comment by YL-yyy** [comment]
thanks
