### ISSUE TITLE
The use of SPPF

### ISSUE THREAD

**Issue by Weixueying** [ultralytics/yolov5#4592]
## ❔Question
How to use SPPF on the network? I directly use SPPF to replace SPP. The following error occurs:
Traceback (most recent call last):
  File "/home/zwc/project/yolov5-master-828/train.py", line 602, in <module>
    main(opt)
  File "/home/zwc/project/yolov5-master-828/train.py", line 500, in main
    train(opt.hyp, opt, device)
  File "/home/zwc/project/yolov5-master-828/train.py", line 119, in train
    model = Model(cfg, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)  # create
  File "/home/zwc/project/yolov5-master-828/models/yolo.py", line 98, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=[ch])  # model, savelist
  File "/home/zwc/project/yolov5-master-828/models/yolo.py", line 265, in parse_model
    m_ = nn.Sequential(*[m(*args) for _ in range(n)]) if n > 1 else m(*args)  # module
  File "/home/zwc/project/yolov5-master-828/models/common.py", line 187, in __init__
    self.m = nn.MaxPool2d(kernel_size=k, stride=1, padding=k // 2)
TypeError: unsupported operand type(s) for //: 'list' and 'int'

**Comment by glenn-jocher** [comment]
@Weixueying SPPF usage is fully documented in PR https://github.com/ultralytics/yolov5/pull/4420

**Comment by Weixueying** [comment]
Hello, may I ask what is the principle of SPPF design? After I trained with my own dataset, the inference time in the test basically remained unchanged, which was not reduced as you said.
SPP: Speed: 0.1ms pre-process, 11.8ms inference, 1.5ms NMS per image at shape (8, 3, 512, 512)
SPPF:Speed: 0.1ms pre-process, 11.7ms inference, 1.5ms NMS per image at shape (8, 3, 512, 512)

**Comment by glenn-jocher** [comment]
@Weixueying SPPF profiling results are documented in PR https://github.com/ultralytics/yolov5/pull/4420#issuecomment-899042581

SPPF is about 1/3 faster than SPP while producing mathematically identical results. Your results are for an entire model, of which SPPF is but a small change.
