### ISSUE TITLE
why put argsort in process_batch?

### ISSUE THREAD

**Issue by xiguadong** [ultralytics/yolov5#4600]
## ❔Question
Amazing YOLOV5. The question is that the argsort in process_batch seems doing nothing, can I delete it? I am trying to write my own map.
```
def process_batch(detections, labels, iouv):
    """
    Return correct predictions matrix. Both sets of boxes are in (x1, y1, x2, y2) format.
    Arguments:
        detections (Array[N, 6]), x1, y1, x2, y2, conf, class
        labels (Array[M, 5]), class, x1, y1, x2, y2
    Returns:
        correct (Array[N, 10]), for 10 IoU levels
    """
    correct = torch.zeros(detections.shape[0], iouv.shape[0], dtype=torch.bool, device=iouv.device)
    iou = box_iou(labels[:, 1:], detections[:, :4])
    x = torch.where((iou >= iouv[0]) & (labels[:, 0:1] == detections[:, 5]))  # IoU above threshold and classes match
    if x[0].shape[0]:
        matches = torch.cat((torch.stack(x, 1), iou[x[0], x[1]][:, None]), 1).cpu().numpy()  # [label, detection, iou]
        if x[0].shape[0] > 1:

            matches = matches[matches[:, 2].argsort()[::-1]] # thisline!!!!!!!!!!!!

            matches = matches[np.unique(matches[:, 1], return_index=True)[1]]
            # matches = matches[matches[:, 2].argsort()[::-1]]
            matches = matches[np.unique(matches[:, 0], return_index=True)[1]]
        matches = torch.Tensor(matches).to(iouv.device)
        correct[matches[:, 1].long()] = matches[:, 2:3] >= iouv
    return correct
```

## Additional context
https://github.com/ultralytics/yolov5/blob/b894e69dfc341fcbfe4a307a15d6af90d90367df/val.py#L70

**Comment by glenn-jocher** [comment]
@xiguadong this is part of the mAP computation code. I'm fairly certain you'll get a different mAP if you omit this line, but you can try before and after and let us know if the results appear identical.

**Comment by xiguadong** [comment]
tks, I got it, its's used for unique.  cause the unique function will iterate to find the same element from begin to end, and move the same element to the last of the list. Unique function will point the position of the repeat element , then , delete the element after iterator over.  so if list ranked ,the same element will be the smaller one .
