### ISSUE TITLE
Whether onnx/tensorRT is supported nn.MultiheadAttention() ?

### ISSUE THREAD

**Issue by xuezu29** [ultralytics/yolov5#4602]
## ❔Question
Whether onnx/tensorRT is supported nn.MultiheadAttention() ? 
## Additional context
I'm using yolov5s-transformer.yaml, can I export to onnx? Thanks a lot!

**Comment by juechenzp** [comment]
@xuezu29 请问yolov5支持transformer转成tensorrt吗，您与试过吗
