### ISSUE TITLE
yolov5s max avreage precision 

### ISSUE THREAD

**Issue by sonyta29** [ultralytics/yolov5#4603]
## ❔Question

the mAP of yolov5 trained on the coco dataset is around 0.639, 
my question : is this mAP change when i'm using the yolov5s trained on coco to detect specific objects ? 

in other words is the yolov5s performs with the same mAP no mater  the input video is ? the mAP is static and can't be computed in real time?

thank you !

**Comment by iceisfun** [comment]
You might want to read and run val.py

mAP values can be computed if you label the data set (in this case a video) and then run val.py, unless you label the data you (or val.py) don't know the truth.

https://github.com/ultralytics/yolov5/blob/bb4da083d1b2d19fbe482ed91064498aa8f942e6/val.py#L233

**Comment by sonyta29** [comment]
@iceisfun thank you for your reply..  so to get the real time mAP i need to prepare my Ground truth data
