### ISSUE TITLE
best.pt and last.pt are disappearing when I run the test data... 

### ISSUE THREAD

**Issue by yaminikonka** [ultralytics/yolov5#4609]
## ❔When I run the train.py after few epochs I got weights, stored as last.pt and best.pt.... This works well....  (On custom data)
Afterthat I want to test these weights on my own video or images, I got error message...
![Error_Msg](https://user-images.githubusercontent.com/38562831/131352041-8a4d436e-d4f9-47f7-968e-bae61b5946e9.JPG)

I am a student, recently I got working on Robot pick and place task, for that I am going to use this model..... Kindly consider my question and reply me..... It helps me a lot.... I have already gone through 279 issues, But I could not find One relating to me... However you find something related to me, refer..   Thank you for your time and efforts to help me....

KY

**Comment by glenn-jocher** [comment]
@yaminikonka good news 😃! Your original issue may now be fixed ✅ in bb4da083d1b2d19fbe482ed91064498aa8f942e6. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
