### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by Bommi95** [ultralytics/yolov5#4614]
## ❔Question
Hello, I am training using SKU-110 data with additional augmentation and encounter this error when I try ran detect.py to inference on a picture after I finished training. Could you guide me to solve this error?

## Additional context
detect: weights=['runs/train/exp2/weights/best.pt'], source=2.jpg, imgsz=[1280, 1280], conf_thres=0.2, iou_thres=0.2, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=True, hide_conf=False, half=True
YOLOv5 🚀 2021-8-27 torch 1.9.0+cu102 CUDA:0 (Tesla T4, 15109.75MB)

Fusing layers... 
Model Summary: 224 layers, 7053910 parameters, 0 gradients, 16.3 GFLOPs
image 1/1 /content/gdrive/My Drive/Colab Notebooks/yolov5/2.jpg: Traceback (most recent call last):
  File "detect.py", line 284, in <module>
    main(opt)
  File "detect.py", line 279, in main
    run(**vars(opt))
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 204, in run
    im0 = plot_one_box(xyxy, im0, label=label, color=colors(c, True), line_width=line_thickness)
  File "/content/gdrive/My Drive/Colab Notebooks/yolov5/utils/plots.py", line 75, in plot_one_box
    if use_pil or not is_ascii(label):  # use PIL
  File "/content/gdrive/My Drive/Colab Notebooks/yolov5/utils/general.py", line 118, in is_ascii
    return len(str.encode().decode('ascii', 'ignore')) == len(str)
AttributeError: 'NoneType' object has no attribute 'encode'

**Comment by glenn-jocher** [comment]
@Bommi95 good news 😃! Your code is out of date and your original issue is probably already resolved in master. To update your code:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
