### ISSUE TITLE
Hyperparametric evolution problem

### ISSUE THREAD

**Issue by Weixueying** [ultralytics/yolov5#4623]
## ❔Question
May I ask, if the dataset is changed into our own dataset, at the beginning of the training, are the hyperparameters still evolved based on COCO dataset? How to set the hyperparameters in line with our own dataset?

**Comment by kuonumber** [comment]
@Weixueying 
This https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution post has a detail information.
I believe you can find an answer there.
