### ISSUE TITLE
cache-image

### ISSUE THREAD

**Issue by jing2523** [ultralytics/yolov5#4624]
## ❔Question
Hello, thanks for providing such a fast network, I would like to ask, if I want to use cache images to speed up the training time, but the large data set has exceeded the system RAM, is there any good idea?

**Comment by kinoute** [comment]
Use `--cache disk`. This is a new alternative where you can cache your images using the disk instead of the RAM. Sure, it won't be as fast as the RAM but It will still be faster than without no cache.
