### ISSUE TITLE
Some hyperparameters are fixed effects?

### ISSUE THREAD

**Issue by PonyPC** [ultralytics/yolov5#4625]
## ❔Question
I train several times with tweaked hyperparameters:  translate, scale, flipud, fliplr, mosaic
But it seems that those parameters is not random while previewing train_batchN.jpg between training.
Every training has same offset, same orientation and same scale. Only hsv_h, hsv_s, hsv_v are different.
So is it normal or must be the same?

**Comment by kuonumber** [comment]
@PonyPC 
The author mentioned it. https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution
You can find following sentence there.
>>This is user selectable in the meta dictionary in train.py, and is useful for fixing parameters and preventing them from evolving

**Comment by PonyPC** [comment]
@kuonumber Hi, maybe I didn't express clearly.
For instance, I trained 3 times  `exp` `exp2` `exp3`  with same command and same parameters.
While looking into these folder, there are `exp/train_batch0.jpg` `exp/train_batch1.jpg` `exp/train_batch2.jpg` 
 `exp2/train_batch0.jpg` `exp2/train_batch1.jpg` `exp2/train_batch2.jpg` 
 `exp3/train_batch0.jpg` `exp3/train_batch1.jpg` `exp3/train_batch2.jpg` 
The hyperparameters `translate`, `scale`, `flipud`, `fliplr` should make a random result on mosaic image, such as random scale, random offset, random orientation...
But every `exp/train_batchN.jpg`, `exp2/train_batchN.jpg` and `exp3/train_batchN.jpg` have same, only hsv is different.

**Comment by glenn-jocher** [comment]
@PonyPC you can vary the training RNG seed as you see fit here:
https://github.com/ultralytics/yolov5/blob/fad57c29cd27c0fcbc0038b7b7312b9b6ef922a8/train.py#L98

**Comment by PonyPC** [comment]
@glenn-jocher  
Thanks glenn-jocher, it's clear now.
So the reason is np.random and random module using different randomization.

**Comment by lifanhanhan** [comment]
> @glenn-jocher
> 谢谢glenn-jocher，现在很清楚了。
> 所以原因是np.random 和random 模块使用不同的随机化。
Can you adjust random seeds（yolov5
![QQ图片](https://user-images.githubusercontent.com/62056271/131969082-c2cb9327-91ed-406a-8c6c-9f5de3032cef.png)
）? I want to implement the same code and run the same results
