### ISSUE TITLE
Can not save image while using  plot_evolve()

### ISSUE THREAD

**Issue by kuonumber** [ultralytics/yolov5#4632]
## To Reproduce (REQUIRED)

Input:

```
from utils.plots import  plot_evolve

plot_evolve(evolve_csv="./runs/evolve/exp14/evolve.csv" )

```

Output:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-18-63a57c58c5e7> in <module>()
----> 1 plot_evolve(evolve_csv="./runs/evolve/exp14/evolve.csv" )

/content/drive/MyDrive/Colab Notebooks/yolov5/utils/plots.py in plot_evolve(evolve_csv)
    378             plt.yticks([])
    379         print('%15s: %.3g' % (k, mu))
--> 380     f = evolve_csv.with_suffix('.png')  # filename
    381     plt.savefig(f, dpi=200)
    382     print(f'Saved {f}')

AttributeError: 'str' object has no attribute 'with_suffix'

```

##  The source code shows that it should save an image after plotting results 
```
 def plot_evolve(evolve_csv=Path('path/to/evolve.csv')):  # from utils.plots import *; plot_evolve()
    # Plot evolve.csv hyp evolution results
    data = pd.read_csv(evolve_csv)
    keys = [x.strip() for x in data.columns]
    x = data.values
    f = fitness(x)
    j = np.argmax(f)  # max fitness index
    plt.figure(figsize=(10, 12), tight_layout=True)
    matplotlib.rc('font', **{'size': 8})
    for i, k in enumerate(keys[7:]):
        v = x[:, 7 + i]
        mu = v[j]  # best single result
        plt.subplot(6, 5, i + 1)
        plt.scatter(v, f, c=hist2d(v, f, 20), cmap='viridis', alpha=.8, edgecolors='none')
        plt.plot(mu, f.max(), 'k+', markersize=15)
        plt.title('%s = %.3g' % (k, mu), fontdict={'size': 9})  # limit to 40 characters
        if i % 5 != 0:
            plt.yticks([])
        print('%15s: %.3g' % (k, mu))
    f = evolve_csv.with_suffix('.png')  # filename
    plt.savefig(f, dpi=200)
    print(f'Saved {f}')
```

- google colab

**Comment by glenn-jocher** [comment]
@kuonumber good news 😃! Your original issue may now be fixed ✅ in PR #4639. This PR updates the `plot_evolve()` `evolve_csv` argument to `pathlib.Path()` objects before plotting.

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
