### ISSUE TITLE
How to solve this bug

### ISSUE THREAD

**Issue by ren1202** [ultralytics/yolov5#4636]
Epoch   gpu_mem       box       obj       cls    labels  img_size
    19/199     5.05G   0.02303   0.02033         0        41       640: 100%|████████████████████████████████████████████████████████████████████████| 314/314 [17:40<00:00,  3.38s/it]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95:   0%|                                                                   | 0/18 [00:01<?, ?it/s]
Traceback (most recent call last):
  File ".\train.py", line 610, in <module>
    main(opt)
  File ".\train.py", line 508, in main
    train(opt.hyp, opt, device)
  File ".\train.py", line 360, in train
    compute_loss=compute_loss)
  File "D:\conda\envs\pytorch1\lib\site-packages\torch\autograd\grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "D:\deep_sort_yolov5\Yolov5_DeepSort_Pytorch\yolov5\val.py", line 219, in run
    callbacks.on_val_image_end(pred, predn, path, names, img[si])
  File "D:\deep_sort_yolov5\Yolov5_DeepSort_Pytorch\yolov5\utils\callbacks.py", line 143, in on_val_image_end
    self.run_callbacks('on_val_image_end', *args, **kwargs)
  File "D:\deep_sort_yolov5\Yolov5_DeepSort_Pytorch\yolov5\utils\callbacks.py", line 71, in run_callbacks
    logger['callback'](*args, **kwargs)
  File "D:\deep_sort_yolov5\Yolov5_DeepSort_Pytorch\yolov5\utils\loggers\__init__.py", line 95, in on_val_image_end
    self.wandb.val_one_image(pred, predn, path, names, im)
  File "D:\deep_sort_yolov5\Yolov5_DeepSort_Pytorch\yolov5\utils\loggers\wandb\wandb_utils.py", line 460, in val_one_image
    self.bbox_media_panel_images.append(wandb.Image(im, boxes=boxes, caption=path.name))
  File "D:\conda\envs\pytorch1\lib\site-packages\wandb\sdk\data_types.py", line 1732, in __init__
    self._initialize_from_data(data_or_path, mode)
  File "D:\conda\envs\pytorch1\lib\site-packages\wandb\sdk\data_types.py", line 1845, in _initialize_from_data
    self._image.save(tmp_path, transparency=None)
  File "D:\conda\envs\pytorch1\lib\site-packages\PIL\Image.py", line 2148, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\10502\\AppData\\Local\\Temp\\tmpud6kkfh4wandb-media\\38nhce3a.png'

**Comment by glenn-jocher** [comment]
@ren1202 this is not a bug. Your training image is no longer available on your system.

**Comment by ren1202** [comment]
Training is normal now, but sometimes this error occurs.
![image](https://user-images.githubusercontent.com/60747672/131694018-a3ea6e24-7a94-45ff-9d19-b7f2b11a8fc5.png)

**Comment by ren1202** [comment]
It may be an error related to wandb

**Comment by glenn-jocher** [comment]
@ren1202 hmm ok, thanks for the report! I'll look in our W&B helper @AyushExel. 

@AyushExel it seems that wandb is trying to load images that may not exist.

@ren1202 are you sure that this image path is not part of your normal dataset and then you didn't alter your dataset during training? 

```
No such file or directory: 'C:\Users\10502\AppData\Local\Temp\tmpud6kkfh4wandb-media\38nhce3a.png'
```

**Comment by AyushExel** [comment]
@ren1202 Thanks for reporting. Can you please provide the commands that you ran ?

**Comment by ren1202** [comment]
![image](https://user-images.githubusercontent.com/60747672/131714903-5920900b-351a-4df2-8a33-fcb7df82bd5e.jpeg)

**Comment by ren1202** [comment]
![image](https://user-images.githubusercontent.com/60747672/131715570-e9e1b1fb-e66b-4726-b792-9df800c1efc8.jpeg)

**Comment by AyushExel** [comment]
@ren1202 Okay the command seems fine. It has something to do with windows temp dir not being accessible. You might want to look into permissions. But there's a hacky way to solve this by not logging any media to W&B. add this to your command `--bbox_interval 201` , this sets bbox log interval to `epochs+1`. This should work.

**Comment by ren1202** [comment]
Using the previous command, errors still occur in eopchs19, now I'm going to try this method of adding bbx_interval 201.
![image](https://user-images.githubusercontent.com/60747672/131748672-014c7515-ad62-463b-9154-b396439c826a.png)

**Comment by ren1202** [comment]
The error does not appear anymore, I want to know why this error occurs.

**Comment by ren1202** [comment]
The error no longer appears, I want to know why such an error occurs.
![image](https://user-images.githubusercontent.com/60747672/131785642-a8821a7c-b815-446a-b148-055213847de6.png)

**Comment by AyushExel** [comment]
@ren1202 this is something to do with windows. One or more of the following are possible:
* You don't have sufficient system permissions to create and access temp dirs. [ I doubt this is the case because then the error would have been consistently reproducible]
* You're running out of space in the system drive so the temp dirs are not being created

**Comment by ren1202** [comment]
ok, Thanks for your help.
