### ISSUE TITLE
How to infer with the trained yolov5s6？

### ISSUE THREAD

**Issue by Larry0607** [ultralytics/yolov5#4637]
## ❔Question
After training my model with yolov5s6，I want to run it with opencv.So I change my yolov5s6.pt into yolov5s6.onnx through export.py.Well,afte reading yolov5s6.onnx with opencv::dnn::readNetFromONNX() ，how to infer the model？

**Comment by glenn-jocher** [comment]
@Larry0607 you can run ONNX inference with detect.py, see example below. For OpenCV errors please raise those on the OpenCV repository, thank you!

```
# Export
python export.py --weights yolov5s.pt --include ONNX --dynamic

# ONNX Inference
python detect.py --weights yolov5s.onnx
```

**Comment by Larry0607** [comment]
> @Larry0607 you can run ONNX inference with detect.py, see example below. For OpenCV errors please raise those on the OpenCV repository, thank you!
> 
> ```
> # Export
> python export.py --weights yolov5s.pt --include ONNX --dynamic
> 
> # ONNX Inference
> python detect.py --weights yolov5s.onnx
> ```

Thank you for your answer.I want to infer yolov5s6.onnx only using opencv instead of pytorch.How can I do it?

**Comment by glenn-jocher** [comment]
@Larry0607 ONNX inference with detect.py does not use pytorch, it uses the ONNX runtime engine:
https://github.com/ultralytics/yolov5/blob/234e8ae6fabc827ef41aec42d05aceedaf228ebc/detect.py#L135-L141
