### ISSUE TITLE
pickle.UnpicklingError: STACK_GLOBAL requires str Error

### ISSUE THREAD

**Issue by yusuf-5896** [ultralytics/yolov5#4638]
I am trying to train a yolov5s model with a ready dataset.

git clone https://github.com/ultralytics/yolov5 and
After pip install -r requirements.txt and downloading the latest version, I can train without any problems.
However, when I try to download and train previous release versions, it gives an error as in the picture.

I tried v5.0 - v4.0 - v3.1 - v3.0 versions respectively, but I got the same error in all of them. In my experiments different env. I made these experiments. However, his education never started.

Currently we have model and cpp project trained using libtorch 1.6.0 and yolov5-Release_3.0. I need to train using release v3.0 and torch 1.6.0, without changing the project. So I can't use the latest version. Can you help me?

![Yolov5_error](https://user-images.githubusercontent.com/24860529/131674542-5e3de693-55c6-4e25-86ac-44f06b047f2d.png)

**Comment by glenn-jocher** [comment]
@yusuf-5896 we recommend you train with the latest YOLOv5 commit and the latest PyTorch version for best results.

**Comment by philip-sparks** [comment]
@yusuf-5896 Were you able to resolve this issue? I also ran into the same error message and have a similar requirement for utilizing an older version of yolo.

**Comment by aviezab** [comment]
LOL guys, I am stuck in here too @philip-sparks @yusuf-5896 
Even with manual command: `--weights '' --cfg yolov5s.yaml`

**Comment by daiyuanm** [comment]
Hey, guys. You can try to clear your dataset cache.

**Comment by aviezab** [comment]
@daiyuanm Which data cache exactly in which location?

**Comment by daiyuanm** [comment]
> @daiyuanm Which data cache exactly in which location?

your train cache and your val cache in the **label** folder.

![image](https://user-images.githubusercontent.com/67545374/135739013-8554f458-0bf2-48b7-a1fa-0ed060965c08.png)

**Comment by DCH8612** [comment]
> 大家好。您可以尝试清除数据集缓存。

Great, it's solved
