### ISSUE TITLE
Calculate mAP@0.1:0.5 or mAP@0.1

### ISSUE THREAD

**Issue by Michelvl92** [ultralytics/yolov5#4640]
## ❔Question
Is it possible to calculate the mAP@0.1:0.5 or mAP@0.1 relatively easily with val.py by just changing a few lines of code?

If yes, would it be possible to show an example of where and how to changed the code?
## Additional context

Is it true that I can just change line to  iouv = torch.linspace(0.1, 0.55, 10).to(device)

**Comment by glenn-jocher** [comment]
@Michelvl92 sure, you can modify your IoU vector here (default is 0.5:0.05:0.95):
https://github.com/ultralytics/yolov5/blob/234e8ae6fabc827ef41aec42d05aceedaf228ebc/val.py#L139
