### ISSUE TITLE
How to modify the color red, position, font size, etc. of the label box

### ISSUE THREAD

**Issue by ts19970816** [ultralytics/yolov5#4643]
![image](https://user-images.githubusercontent.com/51779812/131776624-d608195b-c969-4f47-b01b-2d6399508929.png)

**Comment by glenn-jocher** [comment]
@ts19970816 you can update image annotating with this line in detect.py:
https://github.com/ultralytics/yolov5/blob/fad57c29cd27c0fcbc0038b7b7312b9b6ef922a8/detect.py#L206

https://github.com/ultralytics/yolov5/blob/fad57c29cd27c0fcbc0038b7b7312b9b6ef922a8/utils/plots.py#L80-L98

**Comment by ts19970816** [comment]
thanks
