### ISSUE TITLE
Embeddings from backbone

### ISSUE THREAD

**Issue by krishnakanagal** [ultralytics/yolov5#4644]
## ❔Question
I want to extract the feature embeddings from the yolov5 backbone. Can someone give me some pointers on how would I do it? I am using the default backbone for my training.

## Additional context
I am trying to implement active learning for my project and I want to use the embeddings to make sure I am extracting diverse images. Using embedding I can rank the images on similarity and sample them so that I get diverse images for next iteration of training.

Please let me know if the question needs more clarity.

**Comment by jveitchmichaelis** [comment]
Here's a start:

```
from models import yolo
from models.experimental import attempt_load
import torch

model = attempt_load("./yolov5s.pt", 'cpu')
print(model)

sequential_model = [m for m in model.modules()][1]

# Remove detection layer
model.model = sequential_model[:-1]

# Test forward works:
x = torch.zeros((1,3,64,64), dtype=torch.float)
res = model.forward(x)
print(res.shape)

# Export
ckpt = {'model': model} # Necessary so attempt_load works
torch.save(ckpt, "yolov5s_backbone.pt")
assert attempt_load("yolov5s_backbone.pt")
```

You might need to play about with where in the model you chop the end off, but that should do it. You can call `attempt_load` on your exported model and run stuff through it as usual. Alternatively you can load the model, run your images and then check the activations at a particular layer - that's less trivial:

https://discuss.pytorch.org/t/how-to-access-input-output-activations-of-a-layer-given-its-parameters-names/53772/4

**Comment by glenn-jocher** [comment]
@krishnakanagal if you want to sample images by variety I would just look at the images directly. The augmented mosaics that are used during training don't have high correlation to the base image selected in the mosaic, i.e. I don't see any much rationale in your strategy as I understand it.

But you can always extract any layer outputs `x` in the model `forward()` method here or use the strategy proposed in https://github.com/ultralytics/yolov5/issues/4644#issuecomment-912993896:
https://github.com/ultralytics/yolov5/blob/fad57c29cd27c0fcbc0038b7b7312b9b6ef922a8/models/yolo.py#L155-L157

**Comment by krishnakanagal** [comment]
Hi @glenn-jocher I have a large dataset of images to manually look at them for sampling. I am using entropy uncertainty as a scoring function for identifying the images on which the model is uncertain and use the embeddings to calculate the similarity and try to sample diverse images. I am trying to implement this paper.   https://arxiv.org/pdf/2004.04699.pdf

**Comment by krishnakanagal** [comment]
@jveitchmichaelis Thank you so much for your suggestion.

**Comment by glenn-jocher** [comment]
@krishnakanagal hmm interesting. Well training data variety is just as important as quantity so your approach should have merit.
