### ISSUE TITLE
Detection of small objects

### ISSUE THREAD

**Issue by yocchi0425** [ultralytics/yolov5#4649]
## ❔Question

Hello.

I would like to detect objects that are quite small.
Is there a minimum size (like a threshold) that Yolov5 can detect?

**Comment by glenn-jocher** [comment]
@yocchi0425 label candidate constraint defaults are here. Labels < 2 pixels in width or height will be rejected, though you can modify this to suit your needs.
https://github.com/ultralytics/yolov5/blob/fad57c29cd27c0fcbc0038b7b7312b9b6ef922a8/utils/augmentations.py#L269-L274

**Comment by yocchi0425** [comment]
I appreciate your quick response.

**Comment by fcakyon** [comment]
@yocchi0425 you can perform sliced inference with https://github.com/obss/sahi using your yolov5 model for better small object detection.

Check the yolov5+sahi colab demo: https://colab.research.google.com/github/obss/sahi/blob/main/demo/inference_for_yolov5.ipynb

**Comment by yocchi0425** [comment]
@fcakyon 
Thank you for your sound advice.
