### ISSUE TITLE
yolov5 onnx export

### ISSUE THREAD

**Issue by trungpham2606** [ultralytics/yolov5#4652]
Dear @glenn-jocher 
I have visualized the yolov5 onnx model. And beside the 'output', it also has some others: 
![image](https://user-images.githubusercontent.com/35657426/131860910-c9e345ee-0bb3-4ce8-9f6d-890c28769a6c.png)
and 3 other outputs
![image](https://user-images.githubusercontent.com/35657426/131861019-e1a01bef-b155-4bd7-b868-3e5e114d89da.png)

we can easily get all output names using the script:
![image](https://user-images.githubusercontent.com/35657426/131861156-b2978de3-4a5b-43a7-a0d7-d50d0f9f6eab.png)

the results are ['output', '778', '839', '900'] as same as in the graph.
Can you tell me what are they ? we didnt export them.

**Comment by glenn-jocher** [comment]
@trungpham2606 'output' is used for inference, the other 3 are grid outputs used for training.

**Comment by trungpham2606** [comment]
oh @glenn-jocher , i see.
Can we export the model with nms inside ?

**Comment by zhiqwang** [comment]
Hi @glenn-jocher and @trungpham2606 ,

> Can we export the model with nms inside?

I guess the official code doesn't support this feature yet, and I believe that with minor modifications it should be possible to export onnx models that include nms. If you sirs are interested in this feature, I can submit a PR for this recently.

**Comment by trungpham2606** [comment]
@zhiqwang
Oh, I extremely need it. 
Can you please make a PR.
