### ISSUE TITLE
why early stopping occurs, how to cancel early stopping

### ISSUE THREAD

**Issue by besbesmany** [ultralytics/yolov5#4653]
![56](https://user-images.githubusercontent.com/35992924/131894048-c54cbd69-2083-49d0-933c-adbe175a567b.png)

**Comment by besbesmany** [comment]
also the classification of different classes (map , precision , recall) not appears at the end of epochs as before, how to get this data

**Comment by glenn-jocher** [comment]
@besbesmany EarlyStopping stops training when no improvement is seen for `patience` epochs. By default patience is set to 30, but you can set this to any other value you want, i.e. --patience 100.
https://github.com/ultralytics/yolov5/blob/fad57c29cd27c0fcbc0038b7b7312b9b6ef922a8/train.py#L465

you can run val.py at anytime to generate full metrics on any model:
```bash
python val.py --weights path/to/best.pt --data data.yaml
```

**Comment by glenn-jocher** [comment]
@besbesmany good news 😃! Your original issue may now be fixed ✅ in PR #4653. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
