### ISSUE TITLE
how to enhance my training result?

### ISSUE THREAD

**Issue by jamesbondzhou** [ultralytics/yolov5#4659]

**Comment by jamesbondzhou** [comment]
hello~
I trained with my dataset by using yolov5s.pt as pretrained model with 50epochs,when i test with images in another dataset,the result is bad.
i trained as single class ,also the final mAP is 0.701 
i dont know if the epoch is too small and how should i enhance my training result?

**Comment by jamesbondzhou** [comment]
I trained with my dataset by using yolov5s.pt as pretrained model with 50epochs,when i test with images in another dataset,the result is bad.
i trained as single class ,also the final mAP is 0.701 
i dont know if the epoch is too small and how should i enhance my training result?

**Comment by kinoute** [comment]
Hello,

Here are some training advices to get the best out of Yolo : https://docs.ultralytics.com/guides/model-training-tips/

**Comment by pderrenger** [comment]
@kinoute hello,

To enhance your training results, consider increasing the number of epochs, augmenting your data, and fine-tuning hyperparameters. You can find detailed tips here: https://docs.ultralytics.com/yolov5/tutorials/tips_for_best_training_results/.
