### ISSUE TITLE
Why does the model has several AP in the first figure?

### ISSUE THREAD

**Issue by Okery** [ultralytics/yolov5#466]
## ❔Question
Why does the model (e.g. yolov5s) have several numbers of AP and different GPU speeds in the first figure? 
Does it use different image sizes or test-time augmentation? 
But the first table says there is no multi-scale or test-time augmentaion.

Besides, I notice that in the figure mAP@0.5:0.95 of training part, the final mAP seems to be ~33, less than 36.6. Is it because of setting img=736 and conf=0.001?

**Comment by glenn-jocher** [comment]
First figure? You should be more clear if you expect a proper response.
