### ISSUE TITLE
INT8 Quantization Aware Training for tensorrt8

### ISSUE THREAD

**Issue by ou525** [ultralytics/yolov5#4660]
tensorrt8 has started to support qat mode, is there any plan to support.
![image](https://user-images.githubusercontent.com/23331359/131969701-41603e60-c44a-4587-9ec0-f65e5a260609.png)

**Comment by glenn-jocher** [comment]
@ou525 interesting, thanks for the link!

**Comment by m-guise** [comment]
Hi @glenn-jocher 
Any update on qat support?

**Comment by glenn-jocher** [comment]
@m-guise hi, thank you for your feature suggestion on how to improve YOLOv5 🚀! TRT export, inference, validation are all now fully supported. QAT is not available currently. 

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
