### ISSUE TITLE
anchor-free

### ISSUE THREAD

**Issue by Weixueying** [ultralytics/yolov5#4663]
## ❔Question
Hello, have you tried to replace anchor with anchor-free

**Comment by glenn-jocher** [comment]
@Weixueying hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by Zephyr69** [comment]
Wake up! Someone has released an anchor-free detector in a very similar setup to yolov5 (https://github.com/meituan/YOLOv6).

It seems to have better detection results with small target with similar overall mAP.

I hope yolov5 will adopt an anchor-free head too!

**Comment by TahereSaidi** [comment]
@Zephyr69 
Hello, I want to anchor free YOLOv5 Do you have code that does this?
Or guide me how to do this?

**Comment by glenn-jocher** [comment]
@TahereSaidi Thank you for your interest in YOLOv5 and your suggestion to incorporate an anchor-free head into the model. At the moment, the YOLOv5 repository does not include an implementation of an anchor-free YOLOv5 detector. However, we always appreciate contributions from the community.

If you would like to implement an anchor-free version yourself, you can start by referring to the anchor-free detectors, such as the one you mentioned (YOLOv6). You can study their approach and adapt it to the YOLOv5 architecture.

Feel free to explore this idea further, and if you are able to implement it, we encourage you to submit a Pull Request (PR) with your code changes. This will allow the community to review and test your modifications.

Thank you for your suggestion and your interest in further enhancing YOLOv5. Don't hesitate to reach out if you have any further questions or need additional guidance.

**Comment by TahereSaidi** [comment]
@glenn-jocher 
Thank you very much for your attention. I found this :"https://docs.ultralytics.com/models/yolov5/" that YOLO version 5 has been anchored free.
Did it do it right?
I am new in this field and I doubt whether this proposed model is correct or not?

**Comment by glenn-jocher** [comment]
@TahereSaidi hi there! Thank you for reaching out and expressing your interest in YOLOv5.

Regarding your question, please note that YOLOv5 still utilizes anchor boxes for object detection. However, it introduces various improvements and optimizations compared to previous versions. These enhancements contribute to better detection performance, especially for small objects. The documentation you mentioned provides detailed information on the YOLOv5 model and its capabilities.

If you have any further questions or need clarification, feel free to ask. We're here to help!
