### ISSUE TITLE
multi scale training is too slow

### ISSUE THREAD

**Issue by cswwp** [ultralytics/yolov5#467]
## ❔Question
multi scale training is too slow

![image](https://user-images.githubusercontent.com/11901683/88027884-7b127300-cb6a-11ea-84e5-2f6b57c2f5f6.png)
Is there any other method to accelerate the multi scale speed??

**Comment by glenn-jocher** [comment]
Yes, there’s a special method to accelerate training called using a faster GPU.

**Comment by cswwp** [comment]
@glenn-jocher  Thank you for reply. How to call faster gpu? Does this repo has added faster gpu training now?

**Comment by glenn-jocher** [comment]
@cswwp no I was just joking! There are no shortcuts here, so faster training will give you worse results. If you don't like multi-scale, then don't use it.

**Comment by cswwp** [comment]
> @cswwp no I was just joking! There are no shortcuts here, so faster training will give you worse results. If you don't like multi-scale, then don't use it.

Ok, maybe we can train without multi-class, and then finetune the model with multi-class :)
