### ISSUE TITLE
Do I need to resize the dataset image?

### ISSUE THREAD

**Issue by yocchi0425** [ultralytics/yolov5#4674]
## ❔Question
The images in my dataset are of various sizes.

In this case, do I need to resize those images manually?
Or should I use --img 1280 etc. when training?

**Comment by kinoute** [comment]
Images are resized automatically when using the `--img` argument.

**Comment by yocchi0425** [comment]
@kinoute 
I appreciate your help.

**Comment by bdeng3** [comment]
@kinoute say if we set the `--img` argument to be 640, does that mean resizing our images to (640, 640)? Or it keeps the aspect ratio of the original image by only resizing only one dimension to 640?

**Comment by glenn-jocher** [comment]
@bdeng3 aspect ratio is maintained, long side is resized to 640.

**Comment by bdeng3** [comment]
@glenn-jocher I'm a bit confused on this one. I trained a model on my custom dataset with the "--img 640" on. However, when I converted the model to a tflite version, it shows the InputLayer has an output shape (1, 640, 640, 3). It seems that we did have input size (640, 640), without maintaining the aspect ratio of the images.

**Comment by glenn-jocher** [comment]
@bdeng3 see export.py argparser:
https://github.com/ultralytics/yolov5/blob/0dc725e3dc36283ef657088bbc9e05461311c921/export.py#L307

**Comment by bdeng3** [comment]
Sorry for coming back to this issue after a while. I'm reading a number of different explanation on how image size is handle in yolov5. Could you help clarify how this is done? 

During training, when we type `python train.py --data path/to/data --weight path/to/weight --img 640`. Does that mean we resize images in our dataset into (640, 640)? If we choose to use mosaic augmentation to combine 4 images into 1, the size of the actual input image to the network becomes (1280, 1280)? 

And during inference, say if we type `python detect.py --source path/to/img --weight path/to/weight --img 640`, do we resize the long size of input image to 640, and keep its aspect ratio? But isn't that go against what the "letterbox" function is doing, who pads the image with less gray area during inference? How the aspect ratio being maintain if we use the letterbox function during inference?

**Comment by glenn-jocher** [comment]
@bdeng3 everything is handled correctly. Aspect ratio is always 1:1 in YOLOv5. For best results train and detect at similar --img-size.
