### ISSUE TITLE
Taking so long time when starting the training process!

### ISSUE THREAD

**Issue by huyhoang17** [ultralytics/yolov5#4677]
## ❔Question

I want to train the yolov5s model on a large dataset with 500.000 images (1 class). But when I try to train the model, it's taking so long time when starting the process, or after scanning all the images/labels! And did not start training yet!

How can I speed up this process? Thanks in advance

![Inkedphoto6172283121987333941_LI](https://user-images.githubusercontent.com/15128654/132124931-1955fc4e-69df-4c35-a2f8-a0008fef7d92.jpg)

**Comment by huyhoang17** [comment]
Closed!
I solved my problem

**Comment by borgarpa** [comment]
> Closed! I solved my problem

Hi! I have the same issue... How did you resolve it?

**Comment by glenn-jocher** [comment]
@borgarpa glad to hear you were able to resolve the issue! If you need further assistance or have any other questions, feel free to ask. Good luck with your project!
