### ISSUE TITLE
how to find number of instances for each class in training data

### ISSUE THREAD

**Issue by besbesmany** [ultralytics/yolov5#4680]
I want to know the number of instances (objects) for  each class in training data

**Comment by glenn-jocher** [comment]
@besbesmany labels.jpg in `runs/train/exp` automatically displays relevant dataset statistics on training starts:
![labels (1)](https://user-images.githubusercontent.com/26833433/132141898-d9ed4481-8c3f-410e-8668-76ead97d5dd0.jpg)

**Comment by besbesmany** [comment]
how to get the exact numbers from code?

**Comment by glenn-jocher** [comment]
@besbesmany https://github.com/ultralytics/yolov5/blob/548745181a4d30db3d4fe81a952ca6dbb54c7578/utils/general.py#L396
