### ISSUE TITLE
Multi-GPU Training

### ISSUE THREAD

**Issue by coallar** [ultralytics/yolov5#4683]
## ❔Question
Something went wrong when i used the command:

## Additional context
python3 -m torch.distributed.launch --nproc_per_node 2 train.py --batch 64 --data coco.yaml --weights yolov5s.pt --device 0,1

![image](https://user-images.githubusercontent.com/66529823/132201753-8782bbef-8fd6-4a0a-929f-4cd377d9150d.png)

**Comment by NauchtanRobotics** [comment]
The package `torch.distributed.launch` is part of the pytorch repository, not `yolov5`.  Did you run this command in the right environment? 

I'm new to yolo so thanks in advance for your patience in case I have missed something.

**Comment by glenn-jocher** [comment]
@coallar update your pytorch or run DDP in our Docker Image.

**Comment by coallar** [comment]
Thanks, the issue has  been solved when torch>1.8.0 installed
