### ISSUE TITLE
Train Error

### ISSUE THREAD

**Issue by Seeds-in-Winter** [ultralytics/yolov5#4693]
I am trying to run train.py. It raised an AttributeError as  below:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-513bb0a2f35f> in <module>
----> 1 train.run(img=640,batch=16,epochs=3,weights='yolov5s.pt')

~\yolov5\train.py in run(**kwargs)
    603     for k, v in kwargs.items():
    604         setattr(opt, k, v)
--> 605     main(opt)
    606 
    607 

~\yolov5\train.py in main(opt)
    506     # Train
    507     if not opt.evolve:
--> 508         train(opt.hyp, opt, device)
    509         if WORLD_SIZE > 1 and RANK == 0:
    510             _ = [print('Destroying process group... ', end=''), dist.destroy_process_group(), print('Done.')]

~\yolov5\train.py in train(hyp, opt, device, callbacks)
     98     init_seeds(1 + RANK)
     99     with torch_distributed_zero_first(RANK):
--> 100         data_dict = data_dict or check_dataset(data)  # check if None
    101     train_path, val_path = data_dict['train'], data_dict['val']
    102     nc = 1 if single_cls else int(data_dict['nc'])  # number of classes

C:/Users/ABC/yolov5\utils\general.py in check_dataset(data, autodownload)
    279 
    280     # Parse yaml
--> 281     path = extract_dir or Path(data.get('path') or '')  # optional 'path' default to '.'
    282     for k in 'train', 'val', 'test':
    283         if data.get(k):  # prepend path

AttributeError: 'str' object has no attribute 'path'
---------------------------------------------------------------------------
No matter if the problem is solved or not, thanks a lot for reading this..

**Comment by Seeds-in-Winter** [comment]
Well, I find that yaml.safe_load(open(data)) returns a **STR CLASS** instead of a **dictionary**. I checked stackoverflow but find nothing helpful.

**Comment by Seed-in-Winter** [comment]
Issue solved by myself. When writing your own data/yourdataset.yaml, make sure 
_train: images/train_
has ONE SPACE AFTER COLON。

**Comment by Seeds-in-Winter** [comment]
Issue **SOLVED** by myself. When writing your own data/yourdataset.yaml, make sure contents like this(ONE SPACE AFTER COLON): 
train: images/train
#yaml.safe_load(f) will return a str class if it's like"train:images/train"
