### ISSUE TITLE
DefaultCPUAllocator: not enough memory  when training the yolov5m

### ISSUE THREAD

**Issue by LaserLV52** [ultralytics/yolov5#4694]
## ❔Question
My environment is RTX3060 12G with 16G system RAM, also, I meet all the requirements in requirements.txt. I ran the detect.py with yolov5m.pt and yolov5s.pt, they all work normally.  I used the train.py with the command of  python train.py --img 640 --batch 16 --epochs 5 --data coco128.yaml --weights yolov5s.pt, it also work normally.

But when I used the train.py with the command of python train.py --img 640 --batch 16 --epochs 5 --data coco128.yaml --weights yolov5m.pt, I took the error of "DefaultCPUAllocator: not enough memory: you tried to allocate xxxx bytes. Buy new RAM!".

It seems that, yolov5 will load the cache into RAM for faster training, but I'm not sensitive to training speed in this computer, and the gpu_men is 6.04G when training yolov5m with batchsize=16 which is satisfactory, so I don't want to lower the batchsize further.

Is there has any method do not load the cache into the RAM when training?

I try the parameter of --cache disk, but it didn't work, the system memory still increase and not enough.

## Additional context
If I use the command of python train.py --img 640 --batch 4 --epochs 5 --data coco128.yaml --weights yolov5m.pt to train the yolov5m, it also work normally, but lower batchsize may affect the training performance, also the GPU can meet working conditions with batchsize =16.  So, I would like to find a way not to load the cache into RAM and maintain the batchsize. Thanks!

**Comment by glenn-jocher** [comment]
@LaserLV52 your system lacks sufficient resources/RAM. YOLOv5 does not cache training images unless --cache argument is passed. 

See batch size study here: https://github.com/ultralytics/yolov5/discussions/2452

**Comment by LaserLV52** [comment]
> @LaserLV52 your system lacks sufficient resources/RAM. YOLOv5 does not cache training images unless --cache argument is passed.
> 
> See batch size study here: #2452

However, in the latest version of the code, it can be easily observed that the system memory (RAM) increases significantly before the training starts, and I didn't use the --cache parameter. At the beginning of the training, the GPU memory had stabilized at 6GB and the system memory (RAM) was close to 98%. In the process of training, as long as the system memory slight fluctuation, it will cause the error of "DefaultCPUAllocator: not enough memory". At this point, the GPU memory is still surplus, which seems that nothing to do with batchsize.

Now I have changed the num_workers from the 8(default) to 4, batchsize remained 32, the problem was resolved, it can training normally, the system memory (RAM) still increased before training started, but eventually stabilized at around 75% and doesn't cause errors of "DefaultCPUAllocator: not enough memory", which shows that the problem is not completely related to batchsize, but I don't know why num_workers could caused the memory increase and the RAM increase problem in relation to batchsize and num_workers.

**Comment by 2catycm** [comment]
```python
   parser.add_argument('--cache', type=str, nargs='?', const='ram', help='image --cache ram/disk')
```
 I see in the code that the cache is default ram. so --cache disk does not work?

**Comment by LaserLV52** [comment]
> ```python
>   parser.add_argument('--cache', type=str, nargs='?', const='ram', help='image --cache ram/disk')
> ```
> 
> I see in the code that the cache is default ram. so --cache disk does not work?

Yeah, at least in my case. If I use the parameter of --cache disk,  the system memory still increase and indicate that it is out of memory. Only I decrease the parameter of **num_workers** , the system RAM will decrease.

**Comment by ahthserhsluk** [comment]
how do i reduce the no of workers? 

i used --workers 2, still got the error


my specs are: 16gb ram, rtx 3070ti  8gb, 

code: python train.py --img 1920 --batch -1 --epochs 3 --data data.yaml --weights yolov5s.pt --workers 2

i have image size = 1920*1080, i used batch = -1 for autoselect

**Comment by LaserLV52** [comment]
> how do i reduce the no of workers?
> 
> i used --workers 2, still got the error
> 
> my specs are: 16gb ram, rtx 3070ti 8gb,
> 
> code: python train.py --img 1920 --batch -1 --epochs 3 --data data.yaml --weights yolov5s.pt --workers 2
> 
> i have image size = 1920*1080, i used batch = -1 for autoselect

try --workers 0. Sometimes, you need to set workers=0, 0 means single thread. But, I don't know why single thread can solve the problem

**Comment by glenn-jocher** [comment]
@LaserLV52 Setting `--workers 0` typically resolves memory errors. YOLOv5 sets default dataloader worker count based on available CPU cores, and `--workers 0` disables multiprocessing which can reduce RAM usage. This pruning of dataloaders may help mitigate memory errors.
