### ISSUE TITLE
train.py error

### ISSUE THREAD

**Issue by ggyybb** [ultralytics/yolov5#47]
when i run train.py, i get this error:
![image](https://user-images.githubusercontent.com/61568153/84557931-8f8c7000-ad61-11ea-869b-00293edbf140.png)
datasets have been loaded

**Comment by ggyybb** [comment]
i have solve it, i add a row in utils.py after 470 line, convert gij to float type, i want to know am i right?
![image](https://user-images.githubusercontent.com/61568153/84558104-d9298a80-ad62-11ea-97ad-0e0b3ff37197.png)

**Comment by ggyybb** [comment]
> i have solve it, i add a row in utils.py after 470 line, convert gij to float type, i want to know am i right?
> ![image](https://user-images.githubusercontent.com/61568153/84558104-d9298a80-ad62-11ea-97ad-0e0b3ff37197.png)

it worked.

**Comment by glenn-jocher** [comment]
@ggyybb that's odd, you should not need to modify any code to train. If your issue is reproducible in a common environment like colab or our docker image, we can take a look. Otherwise it may simply be your environment.

**Comment by glenn-jocher** [comment]
@ggyybb I'll paste you links to working environments here just in case.

## Reproduce Our Environment

To access an up-to-date working environment (with all dependencies including CUDA/CUDNN, Python and PyTorch preinstalled), consider a:

- **GCP** Deep Learning VM with $300 free credit offer: See our [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Google Colab Notebook** with 12 hours of free GPU time. <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/)
