### ISSUE TITLE
Getting coordinates for bounding box output YOLOv5

### ISSUE THREAD

**Issue by jeff34442** [ultralytics/yolov5#470]
## ❔Question
Hi, quick question on the functionality of Yolov5. I am trying to get the output(width and height) for the generated bounding boxes, but I have no idea how. Could someone point me in the right direction?

**Comment by TaoXieSZ** [comment]
Check detect.py

**Comment by jeff34442** [comment]
@ChristopherSTAN Oh I see. I never thought to actually read that file.

**Comment by jeff34442** [comment]
@ChristopherSTAN Actually sorry, I just looked at the output again and it is only the bounding box on the image. I am looking for the vertexes of the bounding box themselves.

**Comment by TaoXieSZ** [comment]
Check the args, you can save them in .txt files.

**Comment by jeff34442** [comment]
Amazing I got it! Thanks so much.

**Comment by carloslopezjoya** [comment]
How did you do it, I need help, how to store the detection coordinates in a variable
