### ISSUE TITLE
OSError: /lib/aarch64-linux-gnu/libgomp.so.1: cannot allocate memory in static TLS block while accessing models/tf.py

### ISSUE THREAD

**Issue by jaskiratsingh2000** [ultralytics/yolov5#4703]
Hi @glenn-jocher I am trying to access the models/tf.py with the following command on my local machine nd getting this following error:

Command ran:
```
python3 models/tf.py --weights yolov5s.pt --cfg yolov5s.yaml
```
Error:
```
OSError: /lib/aarch64-linux-gnu/libgomp.so.1: cannot allocate memory in static TLS block
```

@glenn-jocher Can you please let me know on this please

**Comment by glenn-jocher** [comment]
@jaskiratsingh2000 your system likely lacks resources, you could try on a higher memory machine or a Colab instance:

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>
