### ISSUE TITLE
Getting _pickle.UnpicklingError: invalid load key, '$'. error while accessing the val.py after tflite export

### ISSUE THREAD

**Issue by jaskiratsingh2000** [ultralytics/yolov5#4708]
Hi when I am trying to run the validation test that is checking the mAP value on the tflite weights I got, I am getting this following error. Do you have any idea about that?

Command ran:
```
python3 val.py --data coco128.yaml --weights yolov5s-fp16.tflite
```

^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[Bval: data=./data/coco128.yaml, weights=['yolov5s-fp16.tflite'], batch_size=32, im│gsz=640, conf_thres=0.001, iou_thres=0.6, task=val, device=, single_cls=False, augment=False, verbose=False, save│······························_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=runs/val, name=exp, exist_ok=False, half│······························=False                                                                                                           │······························YOLOv5 🚀 v5.0-408-g2317f86 torch 1.9.0a0+gitd69c22d CPU                                                         │······························                                                                                                                 │······························Traceback (most recent call last):                                                                               │······························  File "val.py", line 354, in <module>                                                                           │······························    main(opt)                                                                                                    │······························  File "val.py", line 329, in main                                                                               │······························    run(**vars(opt))                                                                                             │······························  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 28, in decorate_context        │······························    return func(*args, **kwargs)                                                                                 │······························  File "val.py", line 119, in run                                                                                │······························    model = attempt_load(weights, map_location=device)  # load FP32 model                                        │······························  File "/home/pi/Desktop/yolov5/models/experimental.py", line 94, in attempt_load                                │······························    ckpt = torch.load(attempt_download(w), map_location=map_location)  # load                                    │······························  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 608, in load                        │······························    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)                            │······························  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 777, in _legacy_load                │······························    magic_number = pickle_module.load(f, **pickle_load_args)                                                     │······························_pickle.UnpicklingError: invalid load key, '$'.

which is the unpickling error. Do you have any idea about this? @glenn-jocher @zldrobit Your response would be highly appreciable. Thanks!

**Comment by glenn-jocher** [comment]
@jaskiratsingh2000 val.py only works with PyTorch models.

**Comment by jaskiratsingh2000** [comment]
@glenn-jocher what if I want to measure the accuracy performance that is for tf.py model. How can I do that please let me know?

**Comment by glenn-jocher** [comment]
@jaskiratsingh2000 good news 😃! Your original issue may now be fixed ✅ in PR #4711. This PR does not bring TFLite inference to val.py, but it does run checks on the weights you pass to train/val/detect to make sure that they are of the correct type, with more informative error messages if you, for example, try to pass a TFLite model to val.py.

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by glenn-jocher** [comment]
@jaskiratsingh2000 to answer your other question there is no off the shelf solution for mAP on YOLOv5 TFLite models at the moment, but they do work directly for inference with detect.py today:
```
python detect.py --weights yolov5s.tflite
```

**Comment by jaskiratsingh2000** [comment]
My main goal is to know how much accuracy does it give on YOLOv5 TFlite models? How can I do that? Does using the detect.py give something? Let me know please @glenn-jocher

**Comment by glenn-jocher** [comment]
@jaskiratsingh2000 well you could customize val.py for this purpose, or yes you could look at qualitative results from detect.py.

**Comment by jaskiratsingh2000** [comment]
@glenn-jocher What do you mean by qualitative results here and how can I do comparisons of them?

@zldrobit Can we have a script to measure the Accuracy Performance for TFlite models?

**Comment by glenn-jocher** [comment]
@jaskiratsingh2000 qualitative is the opposite of quantitative.

**Comment by jaskiratsingh2000** [comment]
But do you have any idea that if I want to get the mAP value for tflite
model what all changes would I be required to do in a script? And where is
the script for the mAP function?

**Comment by jaskiratsingh2000** [comment]
@zldrobit Is it possible to write the script for mAP value of tflite. Can you come up with that?

**Comment by zldrobit** [comment]
@jaskiratsingh2000 It's a good idea to support TFLite in `val.py` so we could examine the performance in detail after conversion. You could try adding TFLite inference code in `val.py`.
@glenn-jocher I see some code in in `detect.py` and `val.py` is replicated, e.g. in `run()`. Maybe we could refactor both files to support validations of PyTorch, ONNX, and TensorFlow/TFLite.

**Comment by jaskiratsingh2000** [comment]
@zldrobit  I actually tried this but couldn't able to do that. That is why I approached you asking if you can help in writing that script?
Please let me knoiw. That would be of great help.

**Comment by glenn-jocher** [comment]
@zldrobit yes detect.py and val.py appear to perform similar tasks, but they are also quite different. It may be possible to merge these two functionalities into a single file, though this would be a serious undertaking. We also have PyTorch Hub inference, which operates with a built-in dataloader. These 3 were developed at different times and so are not as unified as would be optimal.

There are a few key differences in their purpose, default settings, dataloaders, etc. val.py is designed to obtain the best mAP on a data.yaml val dataset, and detect.py is designed for best real-world inference results from a large variety of sources. A few important aspects of each:

## `val.py`

- **dataloader** LoadImagesAndLabels(): designed to load train, val, test dataset images and labels. Augmentation capable but disabled. https://github.com/ultralytics/yolov5/blob/e88e8f7a988662fb2d613e1aca3ae89214c84084/val.py#L145-L146
- image size: `640`
- rectangular inference: `True`
- [confidence threshold](https://github.com/ultralytics/yolov5/blob/16206692f245e713a5beb380de6dc4bed944986c/test.py#L291): `0.001`
- [iou threshold](https://github.com/ultralytics/yolov5/blob/16206692f245e713a5beb380de6dc4bed944986c/test.py#L292): `0.6`
- [multi-label](https://github.com/ultralytics/yolov5/blob/16206692f245e713a5beb380de6dc4bed944986c/test.py#L120): `True`
- [padding](https://github.com/ultralytics/yolov5/blob/16206692f245e713a5beb380de6dc4bed944986c/test.py#L83-L90): `0.5 * maximum stride`

## `detect.py`

- **dataloaders** (multiple): designed for loading multiple types of media (images, videos, globs, directories, streams). https://github.com/ultralytics/yolov5/blob/fca5e2a48fb526b57bda0c66be6b7ac1aaa8d83d/detect.py#L46-L53
- image size: `640`
- rectangular inference: `True`
- [confidence threshold](https://github.com/ultralytics/yolov5/blob/16206692f245e713a5beb380de6dc4bed944986c/detect.py#L152): `0.25` 
- [iou threshold](https://github.com/ultralytics/yolov5/blob/16206692f245e713a5beb380de6dc4bed944986c/detect.py#L153): `0.45`
- [multi-label](https://github.com/ultralytics/yolov5/blob/16206692f245e713a5beb380de6dc4bed944986c/utils/general.py#L415): `False`
- [padding](https://github.com/ultralytics/yolov5/blob/16206692f245e713a5beb380de6dc4bed944986c/detect.py#L45-L54): `None`

## YOLOv5 PyTorch Hub Inference

`models.autoShape()` class used for image loading, preprocessing, inference and NMS. For more info see [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) https://github.com/ultralytics/yolov5/blob/c5360f6e7009eb4d05f14d1cc9dae0963e949213/models/common.py#L276-L302

- image size: `640`
- rectangular inference: `True`
- [confidence threshold](https://github.com/ultralytics/yolov5/blob/abfcf9eb79877971acd238cafe6149711c5056ad/models/common.py#L226-L230): `0.25 `
- [iou threshold](https://github.com/ultralytics/yolov5/blob/abfcf9eb79877971acd238cafe6149711c5056ad/models/common.py#L226-L230): `0.45`
- [multi-label](https://github.com/ultralytics/yolov5/blob/abfcf9eb79877971acd238cafe6149711c5056ad/models/common.py#L288): `False`
- [padding](https://github.com/ultralytics/yolov5/blob/abfcf9eb79877971acd238cafe6149711c5056ad/models/common.py#L226-L230): `None`

**Comment by jaskiratsingh2000** [comment]
@zldrobit Please let me know if you can help in the writing a script to evaluate the tf models? cc @glenn-jocher
