### ISSUE TITLE
Live stream with detect.py using RTSP turns black after awhile

### ISSUE THREAD

**Issue by mche0106** [ultralytics/yolov5#4709]
After running detect.py for around 3 minutes the stream turn black. The first 3 minutes the model can detect and classify correctly. 
### result from first 3 minute : 
![Screenshot (95)](https://user-images.githubusercontent.com/64697704/132493961-3826d822-ae65-4e80-80ab-690f4ed17483.png)

### result after the error appear : 
![Screenshot (96)](https://user-images.githubusercontent.com/64697704/132493996-74d3fb73-154a-4981-a856-89e2ebedba94.png)

tried on window environment and  Linux Jetson Nano 4 GB environment and gets the same error. Am i suppose to pay for to get the stream to run on a longer period? 

## Expected behavior

able to stream for as long as the model is running.

### Window 10 
   Python 3.6.9
   Pytorch 1.7
### Linux 
    Nvidia Jetson Nano 4GB

**Comment by glenn-jocher** [comment]
@CheahMengYew your stream dropped connection. This is just between you and your stream and unrelated to YOLOv5.
