### ISSUE TITLE
can we use yolov5 for commercial use?

### ISSUE THREAD

**Issue by IamExperimenting** [ultralytics/yolov5#4716]
## Additional context
can we use yolov5 for commercial use?

**Comment by glenn-jocher** [comment]
@IamExperimenting yes, see https://github.com/ultralytics/yolov5/blob/master/LICENSE

<img width="865" alt="Screen Shot 2021-09-09 at 6 10 54 PM" src="https://user-images.githubusercontent.com/26833433/132722679-08d3a02a-4bdf-4514-a7e8-32d9a8d5bbbb.png">

**Comment by ammarsaf** [comment]
> @IamExperimenting yes, see https://github.com/ultralytics/yolov5/blob/master/LICENSE
> 
> <img alt="Screen Shot 2021-09-09 at 6 10 54 PM" width="865" src="https://user-images.githubusercontent.com/26833433/132722679-08d3a02a-4bdf-4514-a7e8-32d9a8d5bbbb.png">

Hi @glenn-jocher . Are this LICENSE (commercial use for YoloV5) still apply on 2023? What about Yolov8? Is it the same?

**Comment by glenn-jocher** [comment]
@Ammar-Azman, thank you for your question.

The current license for YOLOv5 is the AGPL-3.0 license, which allows for commercial use. However, please note that I am not a lawyer, and it's always a good idea to consult with legal professionals to ensure compliance with licensing terms.

Regarding YOLOv8, please note that there is no official YOLOv8 version. The YOLOv5 repository is the latest version at the time of writing.

If you have any further questions, feel free to ask.

**Comment by ammarsaf** [comment]
Thank you for the response @glenn-jocher . Further questions;

1. About the AGPL-3.0 license, so am I need to subscribe the enterprise license if I want to use Yolov5 for my freelance clients project (I assumed this as commercial purpose); Or I can just train the model and use it for free for commercial?

2. About the Yolov8, then why there is already Yolov8 docs on https://docs.ultralytics.com/ ?

**Comment by oliviervluijk** [comment]
@glenn-jocher , I also have a question related to the license. If I modify the code (train, test, val.py files), do I still need the license? What is the boundary of needing a license?

**Comment by glenn-jocher** [comment]
@Ammar-Azman, I appreciate your question.

If you modify the code of YOLOv5, you still need to comply with the AGPL-3.0 license. This means that if you distribute the modified code or use it in a way that falls under the definition of "distribution" according to the license terms, you must make the modified source code available to the recipients and ensure that they are aware of their rights under the AGPL-3.0.

The license boundary depends on how you plan to use and distribute the modified code. If you are using the modified code for your own internal purposes without distributing it externally, the license requirements may not apply in that specific case. However, if you distribute the modified code, provide it as a service, or include it in a product or application that is used by others, the license terms will still be applicable.

It's always recommended to consult with legal professionals to ensure compliance with open-source licenses and to understand the specific implications for your use case.

If you have any further questions or concerns, feel free to ask.

**Comment by ammarsaf** [comment]
I am sorry Mr @glenn-jocher , but my question is not related to any kind of code changing. No code changing at all. 
(I guess you mistakenly answered @ oliviervluijk question to mine. )

1. The freelance project of my clients is using Yolov5 model from your repository as the training model. The custom dataset is coming from my freelance clients, and I used Yolov5 to train on it. Hence, are my case is subjected to Enterprise license (which I need to pay Ultralytics), or I can use it for free?

2. What about the 2nd question? You stated that  there is no official Yolov8, but on the documentation there already a details on how to use Yolov8. 

Appreciate your time.

**Comment by glenn-jocher** [comment]
@oliviervluijk hi there,

The AGPL-3.0 license allows the use of YOLOv5 for commercial purposes, including projects for freelance clients provided those projects are also licensed under AGPL-3.0 and also open-sourced. You can train the YOLOv5 model using your freelance clients' custom dataset and use it in your projects without needing to pay for an Enterprise license whenever the project is also open-sourced and licensed under AGPL-3.0.

If you have any more questions or concerns, feel free to ask.

**Comment by ammarsaf** [comment]
Alright @glenn-jocher 

 If you don't mind, on what condition that I need to apply for **Enterprise license**? Can you give some examples?

**Comment by glenn-jocher** [comment]
@Ammar-Azman hi there,

The Enterprise license for YOLOv5 is generally applicable in scenarios where the AGPL-3.0 license may not meet your specific needs, such as when your project is closed-source, proprietary or commercial in nature.

It's best to reach out to https://ultralytics.com/license for further details in these cases.

If you have any further questions or concerns, feel free to ask.

**Comment by 1andDone** [comment]
@glenn-jocher if I wanted to use a custom trained YOLOv5 model to streamline the process of labeling data but not use the model in a closed-source, commercial application, is that allowed? In this case, the YOLOv5 model would be used to detect rough bounded boxes (which would be manually inspected by me) and speed up my labeling process. If it matters, the YOLOv5 model would be stored in a separate GitHub repository than the code for the web application.

**Comment by glenn-jocher** [comment]
@1andDone, certainly! The AGPL-3.0 license permits the use of YOLOv5 for your described scenario only if the project is open-sourced under AGPL-3.0. As long as the use adheres to the terms of the AGPL-3.0 license, including the distribution of the source code if applicable, you should be in compliance.

Feel free to reach out if you have any additional questions.

**Comment by KasemOmary** [comment]
I'll just parrot off some information as I've read it + look over some information I found. I'm not a lawyer ; I am not a fan of misinformation.

Releases that _were released_ under AGPL are AGPL. Releases that were released under GPL are GPL. If you notice the terms on GPL: 

_2. Basic Permissions.

All rights granted under this License are granted for the term of copyright on the Program, and are irrevocable provided the stated conditions are met_

Again, I'm not a lawyer, but **irrevocable unless the terms of the license are violated** - seems pretty clear to me. So, I looked for what a lawyer and court thought about this same question.

https://opensource.stackexchange.com/questions/4012/are-licenses-irrevocable-by-default

_A non-exclusive copyright license (such as most FOSS licenses) can be revoked at any time only if there was no consideration involved. The United States Federal Circuit Court of Appeal took this on in [Jacobsen v. Katzer in 2008](https://scholar.google.com/scholar_case?case=17776182574171214893&hl=en&as_sdt=6&as_vis=1&oi=scholarr) and ruled that there is consideration exchanged in the use of FOSS by a licensee. This indicates that an FOSS license that's silent on revocation is likely revocable only for violation of it's conditions._

Looks like there's legal precedent on this question too. That seems pretty clear to lawyers.

https://github.com/ultralytics/yolov5/tree/v7.0 - and most notably: https://github.com/ultralytics/yolov5/blob/v7.0/LICENSE 

Release 7.0 of YOLOv5 is the last version of YOLO that was released under GPL. A version YOLOv5 never appears to have been released under AGPL: https://github.com/ultralytics/yolov5/releases  

Anyone with any solid interest in using a back version of YOLO5 v7 & take advantage of GPL on YOLO5 v7 - should consult a lawyer on it.

Releasing software under GPL is pretty no taksie-backsies so long as the rules are followed. The FSF is cool like that.
