### ISSUE TITLE
[onnx export.py error] Unsupported ONNX opset version

### ISSUE THREAD

**Issue by hi-one-gg** [ultralytics/yolov5#4717]
`ONNX: starting export with onnx 1.10.1...`
`ONNX: export failure: Unsupported ONNX opset version: 13`

I'm using
yolov5-5.0, pytorch1.7.0+cu101 and python3.7.9.

How to solve it?

**Comment by glenn-jocher** [comment]
@blackCmd master code allows opset specification:
```
python export.py --opset 12
```

**Comment by hi-one-gg** [comment]
> @blackCmd master code allows opset specification:
> 
> ```
> python export.py --opset 12
> ```

yes! It solved Thank you : )
