### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by ccm516** [ultralytics/yolov5#4729]
Q1. What is the difference between conf_thres and iou_thres in def run in detect.py?

Q2. How can YOLOv5 calculate best.pt?

           # Update best mAP
            fi = fitness(np.array(results).reshape(1, -1))  # weighted combination of [P, R, mAP@.5, mAP@.5-.95]
            if fi > best_fitness:
                best_fitness = fi
            log_vals = list(mloss) + list(results) + lr
            callbacks.run('on_fit_epoch_end', log_vals, epoch, best_fitness, fi)

**Comment by glenn-jocher** [comment]
@ccm516 confidence applies to a single detection, IoU has no relation, IoU an overlap metric that evaluates the overlap between two areas: https://en.wikipedia.org/wiki/Jaccard_index

best.pt is saved on each new max fitness epoch.

**Comment by ccm516** [comment]
then, how to calculate fitness? Which part of which .py should I look at?

**Comment by glenn-jocher** [comment]
@ccm516 if you want to know what the fitness() function does you should probably take a look at it directly:
https://github.com/ultralytics/yolov5/blob/c5360f6e7009eb4d05f14d1cc9dae0963e949213/utils/metrics.py#L15-L19
