### ISSUE TITLE
It is found that the training effect of the model under win10 is completely different from that of ubuntu. 

### ISSUE THREAD

**Issue by wanghuajia** [ultralytics/yolov5#473]
It is found that the training effect of the model under win10 is completely different from that of ubuntu. 

In my data, the training result of the model under win10 is that the map is **0.5**, and the result of ubuntu is that the map is **0.94**. 

**Is this a bug or a code setting**

**Comment by glenn-jocher** [comment]
@wanghuajia if you could plot both of your windows and ubuntu results.txt files together that would help analyze the difference. The files are in yolov5/runs/exp0/results.txt, just move them both into the main yolov5/ folder and then run the plotting command: `from utils.utils import plot_results; plot_results()`
