### ISSUE TITLE
Bounding boxes coordinates 

### ISSUE THREAD

**Issue by sonyta29** [ultralytics/yolov5#4731]
## ❔Question

Hello,  I have a quick and urgent question!!
the bounding box coordinates of the detected objects are given in pixel Coordinate System ? or Camera coordinate System? 
@glenn-jocher 
I'll be grateful for anyone who can answer

**Comment by glenn-jocher** [comment]
@sonyta29 xywh coordinate conventions are shown in the Train Custom Data tutorial:
https://docs.ultralytics.com/yolov5/tutorials/train_custom_data

<img width="800" alt="Image Labels" src="https://user-images.githubusercontent.com/26833433/91506361-c7965000-e886-11ea-8291-c72b98c25eec.jpg">

The label file corresponding to the above image contains 2 persons (class `0`) and a tie (class `27`):

<p align="center"><img width="428" src="https://user-images.githubusercontent.com/26833433/112467037-d2568c00-8d66-11eb-8796-55402ac0d62f.png"></p>

**Comment by sonyta29** [comment]
@glenn-jocher  Thank you so much <3 !!
