### ISSUE TITLE
Can 2 YOLOv5 models be used in a project?

### ISSUE THREAD

**Issue by ozlem-atiz** [ultralytics/yolov5#4738]
## Additional context
Hello there
I am making a license plate recognition system. I labeled with labelimg to get the location of the plate. I used the Yolov5 model. I use tesseract for license plate data. I did a lot of research, but I couldn't create the tesseract tutorial. Do you think I can create another yolov5 model for extra tesseract training? Or if I can, how can I use these two models integrated?
thanks..

**Comment by glenn-jocher** [comment]
@ozlem-atiz for the most helpful response I'd recommend you include as much information as possible regarding your custom problem, including references, links, publications, etc. to your project or topic to help others understand. I for one have no idea what 'tesseract' is other than a high dimensional shape.

**Comment by ozlem-atiz** [comment]
> @ozlem-atiz en yararlı yanıt için, başkalarının anlamasına yardımcı olmak için projenize veya konuya referanslar, bağlantılar, yayınlar vb. dahil olmak üzere özel probleminizle ilgili mümkün olduğunca fazla bilgi eklemenizi tavsiye ederim. Yüksek boyutlu bir şekilden başka 'tesseract'ın ne olduğu hakkında hiçbir fikrim yok.

oh . ok. Thank u ..

**Comment by ozlem-atiz** [comment]
> @ozlem-atiz en yararlı yanıt için, başkalarının anlamasına yardımcı olmak için projenize veya konuya referanslar, bağlantılar, yayınlar vb. dahil olmak üzere özel probleminizle ilgili mümkün olduğunca fazla bilgi eklemenizi tavsiye ederim. Yüksek boyutlu bir şekilden başka 'tesseract'ın ne olduğu hakkında hiçbir fikrim yok.

oh . ok. Thank u..
