### ISSUE TITLE
how to use the  onnx model to predict? i am a fresh man! so,i am little weakness....

### ISSUE THREAD

**Issue by lzh1998-jansen** [ultralytics/yolov5#4739]
how to use the  onnx model to predict?t

**Comment by glenn-jocher** [comment]
@lzh1998-lzh detect.py can run inference on ONNX models exported with dynamic axes, i.e.:
```bash
# Export
python export.py --weights yolov5s.pt --include onnx --dynamic

# Inference
python detect.py --weights yolov5s.onnx
```

**Comment by lzh1998-jansen** [comment]
thank you sir, i will try.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ultralytics/yolov5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月10日(星期五) 晚上8:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ultralytics/yolov5] how to use the  onnx model to predict? i am a fresh man! so,i am little weakness.... (#4739)





 
@lzh1998-lzh detect.py can run inference on ONNX models exported with dynamic axes, i.e.:
 # Export python export.py --weights yolov5s.pt --include onnx --dynamic # Inference python detect.py --weights yolov5s.onnx
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
