### ISSUE TITLE
RTX 3090 Training - GPU utilization not stable 

### ISSUE THREAD

**Issue by anilozfuttu** [ultralytics/yolov5#4751]
Before submitting a bug report, please be aware that your issue **must be reproducible** with all of the following,
otherwise it is non-actionable, and we can not help you:

- **Current repo**: run `git fetch && git status -uno` to check and `git pull` to update repo
- **Common dataset**: coco.yaml or coco128.yaml
- **Common environment**: Colab, Google Cloud, or Docker image. See https://github.com/ultralytics/yolov5#environments

If this is a custom dataset/training question you **must include** your `train*.jpg`, `val*.jpg` and `results.png`
figures, or we can not help you. You can generate these with `utils.plot_results()`.

## 🐛 Bug

GPU Utilization randomly starting to fluctuate when training with RTX 3090 on custom dataset. 
For example, during the 4 epochs, each epoch ends in 30 minutes, while in the 5th epoch, the utilization starting to fluctuate and starts to take 2 hours per epoch. Also had similar problem with RTX 3080 GPU but at that time Pytorch was giving experimental support to 3000 series

## To Reproduce (REQUIRED)
Random
Train arguments: python yolov5/train.py --img 1344 --batch 8 --epochs 10 --data path/to/dataset --weights yolov5m6
**Training uses 13.4/24 GB of VRAM**

**# Hardware**
- MSI SuprimX RTX 3090
- Intel i9 10850k
- 32 GB DDR4 RAM

**# Environment** 
-  POP!_OS 20.04
- Nvidia Driver Version: 470.57.02  
- CUDA Version: 11.4 
- Pytorch Version: 1.9.0+cu111
- Python Version : 3.9

**Normal Utilization**
![Screenshot from 2021-09-10 18-56-32](https://user-images.githubusercontent.com/17238960/132913203-63048d2a-d1c3-40fa-b16e-c2484d460fc6.png)

**Unstable Utilization**
![Screenshot from 2021-09-10 18-36-21](https://user-images.githubusercontent.com/17238960/132913371-1d72f840-0cb5-4e4c-9c1f-0acbfa1f53ab.png)

## Additional context

What I have tried

- I formatted the PC and **only installed VSCode and Miniconda, cloned YoloV5 repo and installed "requirements.txt"**
- Checked bottlenecks for RAM usage, CPU usage even changed SSD with higher speed one. 
- All temperatures are normal GPU max: 75C and CPU max 78C
- Trained my custom dataset with no problems on my laptop which has 2070 super

**Comment by glenn-jocher** [comment]
@anilozfuttu the issue may lie with your environment, drivers or hardware. Our most recent trainings of YOLOv5l6 models at --img 1280 on AWS EC2 P4 instances with 8x A100s show stable utilization over 100 hours (300 epochs):
<img width="1371" alt="Screenshot 2021-09-10 at 23 10 02" src="https://user-images.githubusercontent.com/26833433/132918137-00ec22c0-113c-4cc7-8ca9-c42d38016da5.png">

**Comment by anilozfuttu** [comment]
Even though I couldn't find the cause, I solved the problem. Environment is the problem as you said.  

- Installing only requirements.txt gives cuda error
- Installing pytorch via pip + requirements.txt gives buggy results 
- Installing pytorch via conda + reqirements.txt solved my problem. Trainings are stable now
