### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for AutoShape

### ISSUE THREAD

**Issue by TheTechPny** [ultralytics/yolov5#4752]
I cloned the yolov5 repo and trained it using a custom dataset I created. The training went fine for the quality of my dataset however I can't seem to load the weights I've just created. 

`python train.py --img 416 --batch 4 --epochs 100 --data mytest.yaml --cfg yolov5s.yaml  --name test_results  --cache`

`    def __init__(self):
        self.lock = Lock()
        # load the trained model
        model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=False, classes=2)
        checkpoint_ = torch.load('weights/best.pt')['model']
        model.load_state_dict(checkpoint_.state_dict())`

When attempting to load the weights with the above code I get this error
https://pastebin.com/raw/KX5nkHiA

**Comment by TheTechPny** [comment]
I also trained the model in Google Colab with the same dataset and I couldn't locally load the weights either

**Comment by glenn-jocher** [comment]
@TheTechPny see PyTorch Hub tutorial for loading custom YOLOv5 models.

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by TheTechPny** [comment]
I already have my weights. I've trained the model properly, the problem I'm having is with loading the weights. I don't see anything in the tutorial about properly loading weights and I've implemented the pytorch load_state_dict code appropriately, I'm not sure what the issue is.

        # load the trained model
        model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=False)
        checkpoint_ = torch.load('weights/best.pt')['model']
        self.model = model.load_state_dict(checkpoint_.state_dict())
        self.model.conf = 0.2  # confidence threshold (0-1)

https://i.imgur.com/IK0mdGC.png

**Comment by glenn-jocher** [comment]
@TheTechPny your workflow is incorrect. See PyTorch Hub tutorial for correct workflow.

**Comment by TheTechPny** [comment]
> @TheTechPny your workflow is incorrect. See PyTorch Hub tutorial for correct workflow.

Sorry for wasting your time!

For anyone that stumbles across this same problem, look at the 'Custom Models' section of the PyTorch Hub tutorial

model = torch.hub.load('ultralytics/yolov5', 'custom', path='path/to/best.pt')  # default
model = torch.hub.load('path/to/yolov5', 'custom', path='path/to/best.pt', source='local')  # local repo
