### ISSUE TITLE
Is multiple objects assigned to a single anchor box ?

### ISSUE THREAD

**Issue by ohnabe** [ultralytics/yolov5#4767]
## ❔Question
In YOLOv5, Is there a case where more than one object can be assigned to a single anchor box?
Is YOLOv5 calculating the loss in that state?

**Comment by glenn-jocher** [comment]
@ohnabe yes. Losses are summed.

**Comment by ohnabe** [comment]
thx.

**Comment by firrice** [comment]
But in the case, in where a single anchor is assigned with multi ground truth boxes，it means the anchor has several different supervised info, wouldn't there be some competition in loss and get bad result easily?

**Comment by glenn-jocher** [comment]
@firrice any model training on more than 1 task (i.e. detection) must balance/sum losses according to the priority the user wants to see in the predictions
