### ISSUE TITLE
Can you release pretrain weights on coco datasets using image 640?

### ISSUE THREAD

**Issue by RobertLee0522** [ultralytics/yolov5#4773]
## Can you release pretrain weights yolov5s6 on coco datasets using img640?

Yolov5s6 got very good results on img1280,I know it will be worse using img640,but I wonder is there any chance that you can offer yolov5s6 pretrain weights on coco datasets using img640,I want to try something on it.
It will spends me 4days to train the weights, take too long. If you can provides the pretrain weights it will be really helpful!

Anyway thanks for your reading and Thanks for any help you can provide

**Comment by glenn-jocher** [comment]
@RobertLee0522 P6 models can be applied at all image sizes between 64-1280, so there is no point in training a new model at 640. To run inference at 640:
```
python detect.py --weights yolov5s6.pt --img 640
```
