### ISSUE TITLE
How I can save the numpy value of output features as .csv format file layer by layer (stage by stage)?

### ISSUE THREAD

**Issue by PariaDarbani** [ultralytics/yolov5#4775]
How I can save the numpy value of output features as .csv format file layer by layer (stage by stage)?

I can access the weights of each layer by model.state_dict() but how I can print or save the input/output feature maps from selective layers?

**Comment by glenn-jocher** [comment]
@PariaDarbani you can use the `--visualize` flag to output YOLOv5 feature maps:
```shell
python detect.py --visualize
```

See https://github.com/ultralytics/yolov5/pull/3920

**Comment by PariaDarbani** [comment]
Thank you. it saves the images of outputs. how I can save the numpy values or tensor of each image (numbers)

**Comment by glenn-jocher** [comment]
@PariaDarbani there's no method to save the output values directly, but you can customize the code to return values here:
https://github.com/ultralytics/yolov5/blob/aa1859909c96d5e1fc839b2746b45038ee8465c9/models/yolo.py#L158-L160

**Comment by PariaDarbani** [comment]
> @PariaDarbani there's no method to save the output values directly, but you can customize the code to return values here:
> https://github.com/ultralytics/yolov5/blob/aa1859909c96d5e1fc839b2746b45038ee8465c9/models/yolo.py#L158-L160

Thank you so much. solved. :)
