### ISSUE TITLE
val.py give close to 1 P and R for all classes

### ISSUE THREAD

**Issue by saribolagh** [ultralytics/yolov5#4777]

**Comment by glenn-jocher** [comment]
@saribolagh P and R values are evaluated at 1000 different confidence thresholds and returned at the maximum F1 confidence threshold. 

The --conf-thres used in val.py is only used for generating a mAP, and should ideally be set at 0.0 for true mAP, being set at 0.001 for a speed-accuracy compromise.

**Comment by saribolagh** [comment]
@glenn-jocher Thanks for the explanation though the the problem was due to a mistake by me in the configuration of the val.py where  --save-hybrid was set to True.  
But you comments raised another question, if one sets --conf-thres to a value close to 0 then won't it bring a lot of false positives?

**Comment by glenn-jocher** [comment]
@saribolagh yes val.py generates many false positives by default, they are necessary for a proper mAP computation.
