### ISSUE TITLE
Question about accuracy

### ISSUE THREAD

**Issue by logic03** [ultralytics/yolov5#478]
## ❔Question

Is the accuracy of Yolox still lower than that of FPN？

**Comment by logic03** [comment]
Besides, why is the best-pt model of Yolov5x the size of 1.3GB?Is there any way to make this weight file smaller?

**Comment by glenn-jocher** [comment]
@logic03 your issue has been resolved already, update your code please.

**Comment by logic03** [comment]
Besides, why is the best-pt model of Yolov5x the size of 1.3GB?Is there any way to make this weight file smaller?

**Comment by logic03** [comment]
Is the accuracy of Yolox still lower than that of Faster-rcnn？

**Comment by glenn-jocher** [comment]
update your code
