### ISSUE TITLE
Fine-tune Pretrained Weights for Commercial Use

### ISSUE THREAD

**Issue by fadamsyah** [ultralytics/yolov5#4780]
## Additional context
Hi. Thank you for providing this repo.
I'm still not clear about 1 thing. Is it legal for us to fine-tune the pre-trained weights to generate a commercial model? Thank you

**Comment by glenn-jocher** [comment]
@fadamsyah yes this use case is fine! See for license for details: https://github.com/ultralytics/yolov5/blob/master/LICENSE

<img width="985" alt="Screen Shot 2021-09-14 at 11 08 43 AM" src="https://user-images.githubusercontent.com/26833433/133229723-d256d6e9-b4a2-4658-97cb-16d1944066a2.png">

**Comment by fadamsyah** [comment]
> @fadamsyah yes this use case is fine! See for license for details: https://github.com/ultralytics/yolov5/blob/master/LICENSE
> 
> <img alt="Screen Shot 2021-09-14 at 11 08 43 AM" width="985" src="https://user-images.githubusercontent.com/26833433/133229723-d256d6e9-b4a2-4658-97cb-16d1944066a2.png">

Great! Thank you @glenn-jocher .
