### ISSUE TITLE
did the yolov5 works on polygon annotation?

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#4783]
## ❔Question
I have labeled data using polygon annotation 
did the yolov5 train on polygon annotation or it only works on the bounding box annotation?

**Comment by glenn-jocher** [comment]
@hammadyounas2008 hi! Segmentation label support is on our roadmap but not available yet.

**Comment by iceisfun** [comment]
@hammadyounas2008 There is another repo where someone has modified it to take a poly, I have not tested

https://github.com/XinzeLee/PolygonObjectDetection

**Comment by JakobStadlhuber** [comment]
Is this already supported?

**Comment by tailtNinjavanVN** [comment]
Hope feature will release in future.

**Comment by bit-scientist** [comment]
They state in v6.2 [release](https://github.com/ultralytics/yolov5/releases) that 
> v6.3 is scheduled for September and will bring official instance segmentation support to YOLOv5

**Comment by AbdulBaseerMohammedKhan** [comment]
> ## Question
> I have labeled data using polygon annotation did the yolov5 train on polygon annotation or it only works on the bounding box annotation?
> 
> ## Additional context

I have a COCO Yolo annotations (by running bash get_coco.sh in the segmentation repo of YOLOV5) file and it is in the following format
23 0.434 0.234 0.765 0.874 0.124 0.634 0.273 ....

Can you tell me what these annotations mean? Object detection is pretty straight forward like Class, Height, Width, X_Center, and Y_Center but I can't figure out what it means over here.

**Comment by AbdulBaseerMohammedKhan** [comment]
> @hammadyounas2008 hi! Segmentation label support is on our roadmap but not available yet.

I have a COCO Yolo annotations (by running bash get_coco.sh in the segmentation repo of YOLOV5) file and it is in the following format
23 0.434 0.234 0.765 0.874 0.124 0.634 0.273 ....

Can you tell me what these annotations mean? Object detection is pretty straight forward like Class, Height, Width, X_Center, and Y_Center but I can't figure out what it means over here.

**Comment by Laughing-q** [comment]
@AbdulBaseerMohammedKhan these coordinates are
```vim
class_id, x, y, x, y...
```
which these `xy` mean the boundary coordinates of segment labels.
