### ISSUE TITLE
Two Stage Classification using YOLOv5

### ISSUE THREAD

**Issue by Shahji55** [ultralytics/yolov5#4785]
I have a dataset containing bounding box of face annotation with the following 5 class age labels:

1. 3-12
2. 13-19
3. 20-39
4. 40-59
5. 60+

I was wondering if it's possible to use a two stage approach where I first use Yolov5 to detect the face crop and then use that as input for a model (EfficientNet-B0, Resnet) to perform classification with features transferred between the detector and the classifier?

**Note:** I am assuming yolo offers something like that with classify argument in detect.py. But I am not sure how to train in end to end settings and how to prepare data for yolo model.

**Comment by glenn-jocher** [comment]
@Shahji55 yes some organizations have created two stage (detect-classify) solutions. In general they may be useful for reducing FPs. See TowerScout for a deployed example of YOLOv5 paired with a second stage EfficientNet model.
https://groups.ischool.berkeley.edu/TowerScout/

<img width="1513" alt="Screenshot 2021-06-09 at 15 14 25" src="https://user-images.githubusercontent.com/26833433/121361242-6632ff80-c935-11eb-8e39-3f5e02bc50a0.png">

See also 'Second-stage classifier in detect.py' https://github.com/ultralytics/yolov5/issues/2260
