### ISSUE TITLE
yolo not detecting when running gpu

### ISSUE THREAD

**Issue by Snitte** [ultralytics/yolov5#4788]
## ❔Question
i have tried running yolo on my computer with gpu as the device however it does not detect anything. I have previously run yolov5 on this computer on gpu however it stopped working.
Does anyone have this issue? 
Running cpu, yolo detects without a problem

**Comment by glenn-jocher** [comment]
@Snitte there may be CUDA compatibility issues with the latest versions, i.e. >11.0. You might try using 10.2 with PyTorch instructions from https://pytorch.org/get-started/locally/
