### ISSUE TITLE
Trained custom model img size and detect model img size

### ISSUE THREAD

**Issue by ys31jp** [ultralytics/yolov5#4789]
## ❔Question
Hi, I have trained custom model with yolov5s6 and the image size with 1280.
Then I run the detect.py with the .pt obtained.
First, i run the detect.py with default img size 640, then I run second time with 1280.
I found that the accuracy running detect.py with 640 is higher then 1280.

Which size should I set for when running the detect.py? 
If it should be 1280, why is the detection is worst then 640. 
Thanks in advance.

**Comment by glenn-jocher** [comment]
@ys31jp results will vary by dataset, but COCO P6 models trained at --img 1280 such as YOLOv5s6.pt perform better at --img 1280 than at --img 640. You can reproduce the comparison easily yourself:

```python
# Run YOLOv5s6 on COCO val2017
!python val.py --weights yolov5s6.pt --data coco.yaml --img 640 --iou 0.65 --half
!python val.py --weights yolov5s6.pt --data coco.yaml --img 1280 --iou 0.65 --half
```

```python
Downloading https://ultralytics.com/assets/Arial.ttf to /root/.config/Ultralytics/Arial.ttf...
100% 755k/755k [00:00<00:00, 27.3MB/s]
val: data=./data/coco.yaml, weights=['yolov5s6.pt'], batch_size=32, imgsz=640, conf_thres=0.001, iou_thres=0.65, task=val, device=, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=True, project=runs/val, name=exp, exist_ok=False, half=True
YOLOv5 🚀 v5.0-430-gaa18599 torch 1.9.0+cu102 CUDA:0 (Tesla T4, 15109.75MB)

Downloading https://github.com/ultralytics/yolov5/releases/download/v5.0/yolov5s6.pt to yolov5s6.pt...
100% 24.6M/24.6M [00:00<00:00, 72.9MB/s]

Fusing layers... 
Model Summary: 291 layers, 12653596 parameters, 0 gradients
val: Scanning '../datasets/coco/val2017' images and labels...4952 found, 48 missing, 0 empty, 0 corrupted: 100% 5000/5000 [00:01<00:00, 2738.35it/s]
val: New cache created: ../datasets/coco/val2017.cache
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100% 157/157 [01:09<00:00,  2.27it/s]
                 all       5000      36335      0.659      0.524      0.563      0.377
Speed: 0.2ms pre-process, 3.2ms inference, 2.6ms NMS per image at shape (32, 3, 640, 640)

Evaluating pycocotools mAP... saving runs/val/exp/yolov5s6_predictions.json...
loading annotations into memory...
Done (t=0.42s)
creating index...
index created!
Loading and preparing results...
DONE (t=7.18s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=92.38s).
Accumulating evaluation results...
DONE (t=16.25s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.389
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.568
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.421
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.186
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.427
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.575
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.319
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.523
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.577
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.353
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.642
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.766
Results saved to runs/val/exp
val: data=./data/coco.yaml, weights=['yolov5s6.pt'], batch_size=32, imgsz=1280, conf_thres=0.001, iou_thres=0.65, task=val, device=, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=True, project=runs/val, name=exp, exist_ok=False, half=True
YOLOv5 🚀 v5.0-430-gaa18599 torch 1.9.0+cu102 CUDA:0 (Tesla T4, 15109.75MB)

Fusing layers... 
Model Summary: 291 layers, 12653596 parameters, 0 gradients
val: Scanning '../datasets/coco/val2017.cache' images and labels... 4952 found, 48 missing, 0 empty, 0 corrupted: 100% 5000/5000 [00:00<?, ?it/s]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100% 157/157 [02:08<00:00,  1.23it/s]
                 all       5000      36335      0.658      0.577      0.611      0.418
Speed: 0.5ms pre-process, 12.3ms inference, 4.2ms NMS per image at shape (32, 3, 1280, 1280)

Evaluating pycocotools mAP... saving runs/val/exp2/yolov5s6_predictions.json...
loading annotations into memory...
Done (t=0.64s)
creating index...
index created!
Loading and preparing results...
DONE (t=5.97s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=91.03s).
Accumulating evaluation results...
DONE (t=16.26s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.433
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.619
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.477
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.289
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.480
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.532
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.339
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.578
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.638
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.490
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.682
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.756
Results saved to runs/val/exp2
```

**Comment by ys31jp** [comment]
> @ys31jp results will vary by dataset, but COCO P6 models trained at --img 1280 such as YOLOv5s6.pt perform better at --img 1280 than at --img 640. You can reproduce the comparison easily yourself:
> 
> ```python
> # Run YOLOv5s6 on COCO val2017
> !python val.py --weights yolov5s6.pt --data coco.yaml --img 640 --iou 0.65 --half
> !python val.py --weights yolov5s6.pt --data coco.yaml --img 1280 --iou 0.65 --half
> ```
> 
> ```python
> Downloading https://ultralytics.com/assets/Arial.ttf to /root/.config/Ultralytics/Arial.ttf...
> 100% 755k/755k [00:00<00:00, 27.3MB/s]
> val: data=./data/coco.yaml, weights=['yolov5s6.pt'], batch_size=32, imgsz=640, conf_thres=0.001, iou_thres=0.65, task=val, device=, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=True, project=runs/val, name=exp, exist_ok=False, half=True
> YOLOv5 🚀 v5.0-430-gaa18599 torch 1.9.0+cu102 CUDA:0 (Tesla T4, 15109.75MB)
> 
> Downloading https://github.com/ultralytics/yolov5/releases/download/v5.0/yolov5s6.pt to yolov5s6.pt...
> 100% 24.6M/24.6M [00:00<00:00, 72.9MB/s]
> 
> Fusing layers... 
> Model Summary: 291 layers, 12653596 parameters, 0 gradients
> val: Scanning '../datasets/coco/val2017' images and labels...4952 found, 48 missing, 0 empty, 0 corrupted: 100% 5000/5000 [00:01<00:00, 2738.35it/s]
> val: New cache created: ../datasets/coco/val2017.cache
>                Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100% 157/157 [01:09<00:00,  2.27it/s]
>                  all       5000      36335      0.659      0.524      0.563      0.377
> Speed: 0.2ms pre-process, 3.2ms inference, 2.6ms NMS per image at shape (32, 3, 640, 640)
> 
> Evaluating pycocotools mAP... saving runs/val/exp/yolov5s6_predictions.json...
> loading annotations into memory...
> Done (t=0.42s)
> creating index...
> index created!
> Loading and preparing results...
> DONE (t=7.18s)
> creating index...
> index created!
> Running per image evaluation...
> Evaluate annotation type *bbox*
> DONE (t=92.38s).
> Accumulating evaluation results...
> DONE (t=16.25s).
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.389
>  Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.568
>  Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.421
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.186
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.427
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.575
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.319
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.523
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.577
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.353
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.642
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.766
> Results saved to runs/val/exp
> val: data=./data/coco.yaml, weights=['yolov5s6.pt'], batch_size=32, imgsz=1280, conf_thres=0.001, iou_thres=0.65, task=val, device=, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=True, project=runs/val, name=exp, exist_ok=False, half=True
> YOLOv5 🚀 v5.0-430-gaa18599 torch 1.9.0+cu102 CUDA:0 (Tesla T4, 15109.75MB)
> 
> Fusing layers... 
> Model Summary: 291 layers, 12653596 parameters, 0 gradients
> val: Scanning '../datasets/coco/val2017.cache' images and labels... 4952 found, 48 missing, 0 empty, 0 corrupted: 100% 5000/5000 [00:00<?, ?it/s]
>                Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100% 157/157 [02:08<00:00,  1.23it/s]
>                  all       5000      36335      0.658      0.577      0.611      0.418
> Speed: 0.5ms pre-process, 12.3ms inference, 4.2ms NMS per image at shape (32, 3, 1280, 1280)
> 
> Evaluating pycocotools mAP... saving runs/val/exp2/yolov5s6_predictions.json...
> loading annotations into memory...
> Done (t=0.64s)
> creating index...
> index created!
> Loading and preparing results...
> DONE (t=5.97s)
> creating index...
> index created!
> Running per image evaluation...
> Evaluate annotation type *bbox*
> DONE (t=91.03s).
> Accumulating evaluation results...
> DONE (t=16.26s).
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.433
>  Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.619
>  Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.477
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.289
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.480
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.532
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.339
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.578
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.638
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.490
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.682
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.756
> Results saved to runs/val/exp2
> ```

Thanks for the reply, I will check on it.

Besides, if i train the model with --img1280, I need to stick with this size? Like when I export to torchscript.pt, the --img size have to be 640?

**Comment by glenn-jocher** [comment]
@ys31jp --img 1280 trained models will generally produce best results at inference --img 64 to --img 1280

**Comment by ys31jp** [comment]
Alright, get it. Thanks a lot
