### ISSUE TITLE
YOLOv5s6

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#4791]
## ❔Question

How to train YOLOv5s6?
 I cant find the s6.yaml
https://github.com/ultralytics/yolov5/tree/master/models

**Comment by ys31jp** [comment]
You can check in the Train-Custom-Data
with  --weights yolov5s6.pt

![image](https://user-images.githubusercontent.com/83806490/133295506-dfedec31-2684-4afa-8aea-fe0742827c9b.png)

**Comment by glenn-jocher** [comment]
@alicera just use `python train.py --weights yolov5s6.pt` as @ys31jp recommends. Additional model yamls are in yolov5/models/hub:
https://github.com/ultralytics/yolov5/tree/master/models/hub

**Comment by alicera** [comment]
Hi @ys31jp 
If I use --weights yolov5.pt --cfg yolov5s.cfg, 
1.does the --cfg have been used?
2. " --weights yolov5.pt --cfg yolov5s.cfg"  =  "--weights yolov5.pt"  ?
3. When is the time to use  --cfg ?

**Comment by glenn-jocher** [comment]
@alicera as the tutorial states --cfg is not recommended.
