### ISSUE TITLE
Multiple bounding box for a single object

### ISSUE THREAD

**Issue by billalkuet07** [ultralytics/yolov5#4796]
## ❔Question
Hi, I have trained Yolov5l6 model with from docker image. I am using Yolov5 for single object detection (screen detection). The training precision is around 0.90 , recall 0.9 mAP@0.5  0.94  mAP@0.5-0.95 0.57.

However, I am always getting same testing performance (precision 1 and recall 1 mAP0@.5 0.9949 and mAP@0.5-0.95 0.9949. 
) regardless of model (I have tried different model). Moreover, I am getting multiple bounding boxes for a single object in output label txt files (generated by val.py). Although, the batch plot shows only one bounding box per object. Even, detect.py also gives one bounding box per object. The confusion matrix also looks different. The model is not overfitting as I have tested with some unknown data.

One of the sample of label.txt generated by val.py for a single object.

0 0.240625 0.202344 0.475 0.398438
0 0.514725 0.701093 0.351975 0.250473
0 0.30418 0.121441 0.409399 0.242881
0 0.02118 0.997351 0.04236 0.00529728
0 0.235381 1 0.470761 0
0 0.683193 1 0.633615 0
0 0.803138 0.845003 0.393723 0.309994
0 0.225124 0.876262 0.450248 0.247476
 
I have tried with following code to testing result generation. Am I missing something or making any mistake? Or it supposed to generate such bbox? If its normal, then how I can get the most confident bbox?

## Additional context
Code I have run:

python  val.py --weight /usr/src/coco/fold1/yolov5l6_results/weights/best.pt --data /usr/src/coco/fold1/data.yaml --task 'test' --img 640 --save-txt --iou-thres 0.6 --device 0   --verbose --save-hybrid

**Comment by glenn-jocher** [comment]
@billalkuet07 the purpose of --save-hybrid is to label images, not to produce accurate mAP. 

If you want a valid mAP don't use --save-hybrid, use default settings.

**Comment by billalkuet07** [comment]
Thank you for your help. It solves the problem of getting wrong performance from val.py.
 
 But I am still getting multiple bounding boxes in label.txt generated inside the labels directory from val.py code. How I can get the exactly one bbox per object? The code now I am using following:

python  val.py --weight /usr/src/coco/fold4/yolov5l6_results/weights/best.pt --data /usr/src/coco/fold4/data.yaml --task 'test' --img 640 --save-txt --iou-thres 0.6 --device 0  --augment

I also pass the --save-conf in order to get the confidence. Its not saving any confidence values for the bbox in label file.

python  val.py --weight /usr/src/coco/fold1/yolov5l6_results/weights/best.pt --data /usr/src/coco/fold1/data.yaml --task 'test' --save-txt --save-conf --img 640   --device 0

**Comment by glenn-jocher** [comment]
@billalkuet07 it's up to you to tune your inference settings to your custom requirements.
