### ISSUE TITLE
if train a custom data, should I modify the anchors?

### ISSUE THREAD

**Issue by colorful-ocean** [ultralytics/yolov5#480]
# parameters
nc: 80  # number of classes
depth_multiple: 1.33  # model depth multiple
width_multiple: 1.25  # layer channel multiple

# anchors
anchors:#modify?
  - [116,90, 156,198, 373,326]  # P5/32
  - [30,61, 62,45, 59,119]  # P4/16
  - [10,13, 16,30, 33,23]  # P3/8

**Comment by colorful-ocean** [comment]
I try to use utils.utils.kmean_anchors, but fail. 
```
AttributeError: module 'yaml' has no attribute 'FullLoader'
```

**Comment by glenn-jocher** [comment]
@colorful-ocean your yaml is not meeting the minimum version requirements. `pip install -U pyyaml`

YOLOv5 uses AutoAnchor. Your anchors are computed and analyzed against your dataset automatically, and if new anchors are needed they are evolved with a genetic algorithm and attached to your model automatically also. Things you need to do: 0.

If you see any strange effects do let us know though, this is all extremely experimental still.

**Comment by dlawrences** [comment]
One thing I would add on this is that currently, as far as I know, AutoAnchor does not modify the model `yaml`. It is also hard to track the AutoAnchor results in the terminal.

How I get it done is that I run the `utils.utils.kmean_anchors` separately on my dataset to figure out the anchors, and then reuse those anchors wherever needed. This allows for better reproducibility.

**Comment by china56321** [comment]
> One thing I would add on this is that currently, as far as I know, AutoAnchor does not modify the model `yaml`. It is also hard to track the AutoAnchor results in the terminal.
> 
> How I get it done is that I run the `utils.utils.kmean_anchors` separately on my dataset to figure out the anchors, and then reuse those anchors wherever needed. This allows for better reproducibility.

Have you solved the problem ?  how to save the anchors ?
