### ISSUE TITLE
train time 

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#4800]
## ❔Question

How many time do you take the training for yolov5s6 and yolov5m6?

**Comment by glenn-jocher** [comment]
@alicera varies by hardware and training settings.

**Comment by alicera** [comment]
Could you share your machine and training time?
Thank you very much.

**Comment by glenn-jocher** [comment]
@alicera baseline speeds and hardware are already displayed in README.

**Comment by alicera** [comment]
Sorry,I only find this
https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training
![image](https://user-images.githubusercontent.com/59388989/133713748-59a8ef57-1027-48aa-aebd-865cb3918928.png)

![image](https://user-images.githubusercontent.com/59388989/133713887-5e1c62d6-a119-4efe-9d67-a2924355f4c7.png)

**Comment by glenn-jocher** [comment]
@alicera see https://github.com/ultralytics/yolov5#pretrained-checkpoints, commands to reproduce in Table Notes below
