### ISSUE TITLE
how to create a function 

### ISSUE THREAD

**Issue by sevaraMS** [ultralytics/yolov5#4801]
I want to create a function on detect.py (getting center information of detected objects). Using this function I want to insert it to another .py file where I want to do some calculations using center points information. When I create a function on detect.py I can not call it to another .py file. How can I do this? Thank you.

**Comment by glenn-jocher** [comment]
@sevaraMS this is non-YOLOv5 specific and more suitable for a stackoverflow search:
https://stackoverflow.com/questions/20309456/call-a-function-from-another-file

**Comment by sevaraMS** [comment]
but I have done this approach, but not working, it is not sawed a function or not recognize. Thank you
