### ISSUE TITLE
How to interpret the precision and recall vs epoch curve?

### ISSUE THREAD

**Issue by YukunXia** [ultralytics/yolov5#4812]
## ❔Question

If I understand correctly, the default train.py will call the test function to calculate the metrics, and the default conf_thred is 0.001. The final precision and recall I had were both pretty high: 0.984 and 0.883. I feel confused that such a small conf_thred could lead to a precision close to 1. I checked the `P_curve.png`, and at confidence close to 0, the precision decreased to 0, which makes sense to me, but seems to be contradictory to the 0.984 precision.

## Additional context

My training curves:

![image](https://user-images.githubusercontent.com/37142664/133476369-c311e832-a369-401e-958b-66582a312db0.png)

P curve:

![image](https://user-images.githubusercontent.com/37142664/133476451-4a3a0d32-0472-4a05-916b-cdb65e3a9059.png)

R curve:

![image](https://user-images.githubusercontent.com/37142664/133476500-5d2fde36-a680-42b3-9f85-4a88bd46558d.png)

PR curve:

![image](https://user-images.githubusercontent.com/37142664/133476540-a59c3bcc-49c2-4959-989a-b3cabfea065b.png)

**Comment by glenn-jocher** [comment]
@YukunXia P and R are reported at maximum F1 confidence, not at 0.001, which would not make any sense as then R would be near 1 and P would be near zero. See F1_curve.png for this value.

**Comment by YukunXia** [comment]
Thank you! F1 curve says "all classes 0.93 at 0.505", so the conf_thred for precision and recall is actually 0.505.

**Comment by glenn-jocher** [comment]
@YukunXia yes

**Comment by jet-c-21** [comment]
@glenn-jocher what kind of confidence represented on the horizontal axis? Is it IOU thresh or Class thresh?

How can set confidence threshold when I am doing inference?

**Comment by glenn-jocher** [comment]
@jet-c-21 The confidence on the horizontal axis of the precision-recall curves and F1 curves is the objectness score threshold, not the IoU or class score threshold. You can set the confidence threshold during inference with the `--conf` argument. Check out the YOLOv5 documentation for more details.
