### ISSUE TITLE
tensorrtx cmake error

### ISSUE THREAD

**Issue by Deep-learning999** [ultralytics/yolov5#4819]
- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found CUDA: /usr/local/cuda (found version "11.1") 
CMake Error at /usr/share/OpenCV/OpenCVModules.cmake:192 (message):
  The imported target "opencv_shape" references the file

     "/usr/lib/x86_64-linux-gnu/libopencv_shape.so.3.4.1"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/share/OpenCV/OpenCVModules.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/share/OpenCV/OpenCVConfig.cmake:112 (include)
  CMakeLists.txt:36 (find_package)

CMake Warning (dev) in /usr/share/OpenCV/OpenCVModules.cmake:
  Policy CMP0011 is not set: Included scripts do automatic cmake_policy PUSH
  and POP.  Run "cmake --help-policy CMP0011" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  The included script

    /usr/share/OpenCV/OpenCVModules.cmake

  affects policy settings.  CMake is implying the NO_POLICY_SCOPE option for
  compatibility, so the effects are applied to the including context.
Call Stack (most recent call first):
  /usr/share/OpenCV/OpenCVConfig.cmake:112 (include)
  CMakeLists.txt:36 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/hy-nas/59/AlphaPose/TensorRTX/yolov5/build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.
sudo: ./yolov5: command not fouded

Can you write a tutorial on tensorrtx yolov5 to tensorrt on colab

**Comment by glenn-jocher** [comment]
@Deep-learning999 please raise tensorrtx issues on the tensorrtx repository.
