### ISSUE TITLE
how to save the object images detected by the detect.py

### ISSUE THREAD

**Issue by chenyuzhou27** [ultralytics/yolov5#4820]
I have trained my project successfully,I want to save the object images detected by the detect.py for my next step.
Anyone has solution?thanks a lot(*￣︶￣)

**Comment by chenyuzhou27** [comment]
let me add some,there are lots of boxes for lots of detected objects in one picture,I want to save all the box images one by one

**Comment by glenn-jocher** [comment]
@chenyuzhou27 to save image crops use:
```
python detect.py --save-crop
```

**Comment by chenyuzhou27** [comment]
> @chenyuzhou27 to save image crops use:
> 
> ```
> python detect.py --save-crop
> ```

wow thank you so much,I should read more carefully
