### ISSUE TITLE
libtorch import error

### ISSUE THREAD

**Issue by willa2016** [ultralytics/yolov5#483]
I export the torchscript successfully throw export.py .but find that it cannot be loaded correctlly by libtorch(cpp)，I am sure that I used the libtorch(cpp) correctly because I had loaded other detection  models correctly.  
 the bug shows when :
module = torch:jit:load(“xxx.torchscript”)
torch::jit::script::ErrorReport at memory location 0x000000FED9AF0190

**Comment by yasenh** [comment]
Hi @willa2016, I am able to load the torchscript model in my c++ application without any issue, just FYI my env is PyTorch 1.5.1, libtorch 1.5.1 and CUDA 10.2.
