### ISSUE TITLE
Loading pre trained model produces different inference results to tutorial notebook

### ISSUE THREAD

**Issue by dallan1982** [ultralytics/yolov5#4832]
I have trained a yolo5vl model on custom data, following this tutorial https://github.com/ultralytics/yolov5/issues/12 (more specifically the colab notebook in the tutorial:
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb)

I have then exported the best.pt file and loaded the model on my home desktop following this tutorial https://github.com/ultralytics/yolov5/issues/36.

Here is my code for loading the model:
`model = torch.hub.load('/yolov5', 'custom', '/models/best.pt', source='local')`
(I have locally cloned this repo and stored the best.pt file in the models directory).

I am then comparing inference results on the same images using the colab notebook with the original model and my home PC with the exported version.

Colab code for inference:
`!python detect.py --weights best.pt --img 416 --conf 0.25 --source data/custom_images/`
(from the notebook)

Code for inference on home PC:
`raw_detections = model(img).pandas().xyxy[0].to_json(orient="records")
detections = json.loads(raw_detections)`

The issue is that the inference results produced on the colab notebook with the detect.py file are far superior to the ones produced on my home PC, despite both using the same model. 
Many times the exported model version is missing multiple objects the colab version is detecting.
I have repeated this process many times with different models (yolov5s, yolov5l) and am getting the same missing detections.
If this is expected, my apologies.

**Comment by glenn-jocher** [comment]
@dallan1982 it looks like you're comparing apples to oranges here. Two different scripts on two different machines with two different sets of arguments.

**Comment by dallan1982** [comment]
> @dallan1982 it looks like you're comparing apples to oranges here. Two different scripts on two different machines with two different sets of arguments.

Thanks, I assumed because I was running the same model on the same files both with PyTorch the same inference would be produced.

Would you have any idea as to what could produce drastically different results between both cases? I was thinking maybe the way the model is loaded or the way the images are loaded and preprocessed. Both the images are loaded by reading a file with opencv into a numpy array but there are some other intermediate steps which I don’t quite understand.

Apologies if this isn’t an acceptable question and thanks for your time and hard work on this repo.

**Comment by glenn-jocher** [comment]
@dallan1982 from https://pytorch.org/docs/stable/notes/randomness.html:
> Completely reproducible results are not guaranteed across PyTorch releases, individual commits, or different platforms. Furthermore, results may not be reproducible between CPU and GPU executions, even when using identical seeds.

But to start with if you expect similar results run the same command with the same default settings.
