### ISSUE TITLE
Performance decrease using PyTorch

### ISSUE THREAD

**Issue by TheTechPny** [ultralytics/yolov5#4836]
When I use PyTorch in my custom script the performance for model(img) is drastically slower than detect.py. I pass a screenshot into my detector which just prints the results. It detects at maybe 1 frame every 2 seconds or so while running detect.py is much much faster.

**Comment by iceisfun** [comment]
The first frame will take extra time due to warm up

In your script try processing a blank frame after loading the model before testing any performance.
