### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ccm516** [ultralytics/yolov5#4837]
I have run yolov5 using USB camera, python detect.py --source.

I have a question about the FPS of the camera YOLO loads

Where is the code to load the source with cv2.cap?

**Comment by fabiozappo** [comment]
Give a look at LoadImages class in utils/datasets.py

**Comment by ccm516** [comment]
i modified the code

class LoadWebcam:  # for inference
    def __init__(self, pipe=0, img_size=640):
        self.img_size = img_size

        if pipe == '0':
            pipe = 0  # local camera

        self.pipe = pipe
        self.cap = cv2.VideoCapture(pipe)  # video capture object
        self.cap.set(cv2.CAP_PROP_BUFFERSIZE, 3)  # set buffer size



class LoadWebcam:  # for inference
    def __init__(self, pipe=0, img_size=640):
        self.img_size = img_size

        if pipe == '0':
            pipe = 0  # local camera

        self.pipe = pipe
        self.cap = cv2.VideoCapture(pipe)  # video capture object
        self.cap.set(cv2.CAP_PROP_FPS, 30)    <------------------------------------
        self.cap.set(cv2.CAP_PROP_BUFFERSIZE, 3)  # set buffer size

it doesn't work..

**Comment by iceisfun** [comment]
@ccm516 It might be worth submitting a PR with a --fps switch then using that to set cv2.CAP_PROP_FPS ?

https://github.com/ultralytics/yolov5/blob/master/CONTRIBUTING.md
