### ISSUE TITLE
How to add another detection head ?

### ISSUE THREAD

**Issue by ahong007007** [ultralytics/yolov5#4838]
## 🚀 Feature
I want to use YOLOv5 to train multiple data sets of detectors (objects365, coco, openimage600), and use a common backbone, but I want to have different detection heads corresponding to different data sets. How to add detection heads?

Thank you very much.

**Comment by jain-abhay** [comment]
> ## 🚀 Feature
> I want to use YOLOv5 to train multiple data sets of detectors (objects365, coco, openimage600), and use a common backbone, but I want to have different detection heads corresponding to different data sets. How to add detection heads?
> 
> Thank you very much.

Hi @ahong007007 were you able to build a model with a common backbone and multiple heads? Please can you kindly share your inputs if yes. Thanks
