### ISSUE TITLE
Why you train YOLOv5 with BGR image but inference with RGB?

### ISSUE THREAD

**Issue by LvJC** [ultralytics/yolov5#4848]
## ❔Question
Why you train YOLOv5 with BGR image but inference with RGB?

## Additional context
Train: https://github.com/ultralytics/yolov5/blob/302a1b0bb03b3dbae0cb41f43b6c6c998070ff49/utils/datasets.py#L648
Inference: https://github.com/ultralytics/yolov5/blob/302a1b0bb03b3dbae0cb41f43b6c6c998070ff49/utils/datasets.py#L224

**Comment by glenn-jocher** [comment]
@LvJC all YOLOv5 inference is RGB order, regardless of train, val, detect, export etc.

**Comment by LvJC** [comment]
> @LvJC all YOLOv5 inference is RGB order, regardless of train, val, detect, export etc.

Understood. But why input BGR image during training period (in `LoadImagesAndLabels ` )?

**Comment by glenn-jocher** [comment]
@LvJC cv2 package loads in BGR order

**Comment by LvJC** [comment]
> @LvJC cv2 package loads in BGR order

I knew... but then didn't turn it into RGB order as training input

**Comment by glenn-jocher** [comment]
@LvJC yes all dataloaders convert to RGB, i.e.
https://github.com/ultralytics/yolov5/blob/302a1b0bb03b3dbae0cb41f43b6c6c998070ff49/utils/datasets.py#L224

**Comment by LvJC** [comment]
> @LvJC yes all dataloaders convert to RGB, i.e.
> https://github.com/ultralytics/yolov5/blob/302a1b0bb03b3dbae0cb41f43b6c6c998070ff49/utils/datasets.py#L224

This is just for inference as is commented...
I don't think it's converted to RGB... 
Training only uses `LoadImagesAndLabels` and `LoadImagesAndLabels`  uses `load_image`, as is shown in the beginning. Maybe you can have a double check...

**Comment by glenn-jocher** [comment]
@LvJC as I've already stated in https://github.com/ultralytics/yolov5/issues/4848#issuecomment-922256036 all dataloaders convert to RGB:


> @LvJC yes all dataloaders convert to RGB, i.e.
> https://github.com/ultralytics/yolov5/blob/302a1b0bb03b3dbae0cb41f43b6c6c998070ff49/utils/datasets.py#L224
