### ISSUE TITLE
About confusion images

### ISSUE THREAD

**Issue by czczmr** [ultralytics/yolov5#4853]
## Additional context
you know when i train the model ,i get the confusion_matrix.png 
but i want  to know hou many  backgroudFP i have ,not only ratio
are there some Parameters  make me do it ?

**Comment by glenn-jocher** [comment]
@czczmr set `normalize=False` to plot absolute confusion matrix.
https://github.com/ultralytics/yolov5/blob/4d1a2ac87eb2c9c37978584f4f93af2af0260738/utils/metrics.py#L163

**Comment by czczmr** [comment]
Thank you for your answer, I have the following two questions
1. In order to remove excessive background FP, I adjusted conf_thres # confidence threshold and iou_thres # NMS IOU threshold in detect.py.
Can I continue to use the model I trained?
2. Did you use the mosic method to enhance the data? If I want to close it, what should I do?
This is a great algorithm, thank you.

**Comment by glenn-jocher** [comment]
@czczmr inference settings like confidence and IoU thresholds are independent of your model, you do not need to retrain or anything like that to vary inference settings.

You can modify hyperparameters like mosaic probability in your hyp file:
https://github.com/ultralytics/yolov5/blob/9ef94940aa5e9618e7e804f0758f9a6cebfc63a9/data/hyps/hyp.scratch.yaml#L32
