### ISSUE TITLE
Output confidence 

### ISSUE THREAD

**Issue by edeyejedi** [ultralytics/yolov5#486]
## 🚀 Feature
Output of the confidence value of each object detected. 
## Motivation
I need it for post processing. 
## Pitch
No pitch. I have done it, but it could probably be done better than the edit I made locally, maybe a different file? But i just appended the conf value to the results text file - line 98 in detect.py
                            f.write(('%g ' * 6 + '\n') % (cls, *xywh, conf))  # label format
## Alternatives
I guess this is not strictly consistent in terms of protocol - i.e. the results file format is that of the (training) labels file
So perhaps an alternate file output............ 
## Additional Info
This capability/output might already be available and haven't twigged how to get it!

**Comment by edeyejedi** [comment]
Another thing that just sprung to mind. I don't need an image output from detect.py, just the bounding box data (and the confidence!). So maybe a flag to swtich off the writing of annotated images..............?

***Edit. Ok just seen this "save_img", but it is not in the ArgumentParser list..................Maybe just ignore this

**Comment by glenn-jocher** [comment]
@edeyejedi the current text output format omits the conf because it mimics exactly the training data format, so you can run --save-txt to autolabel future training data this way.

**Comment by edeyejedi** [comment]
Hi Glenn.
Yes that is understood. Perhaps another file then would be better. Like I said though, not everyone wants to record the confidence in a text file!!!
