### ISSUE TITLE
How to continue training after an unplanned termination

### ISSUE THREAD

**Issue by Yzh619** [ultralytics/yolov5#4865]
I had an unexpected computer restart after a long training session.
The logs of the previous training are saved, including the weight files, but I don't want to start the training again, how can I build on the previous training?

**Comment by glenn-jocher** [comment]
@Yzh619 👋 Hello! Thanks for asking about **resuming training**. YOLOv5 🚀 Learning Rate (LR) [schedulers](https://github.com/ultralytics/yolov5/blob/9f3a388cea66ca71b9bbe057929eed8fbc920a7e/train.py#L109-L142) follow predefined LR curves for the fixed number of `--epochs` defined at training start (`default=300`), and are designed to fall to a minimum LR on the final epoch for best training results. For this reason you can not modify the number of epochs once training has started.

<img width="850" alt="LR Curves" src="https://user-images.githubusercontent.com/26833433/119332195-8e113a80-bc88-11eb-8eb7-7494ff1d5c01.png">

If your training was **interrupted** for any reason you may continue where you left off using the `--resume` argument. If your training fully completed, you can start a **new** training from any model using the `--weights` argument. Examples:

## Resume Single-GPU

You may not change settings when resuming, and **no additional arguments** other than `--resume` should be passed, with an optional path to the checkpoint you'd like to resume from. If no checkpoint is passed the most recently updated `last.pt` in your `yolov5/` directory is automatically found and used:
```bash
python train.py --resume  # automatically find latest checkpoint (searches yolov5/ directory)
python train.py --resume path/to/last.pt  # specify resume checkpoint
```

## Resume Multi-GPU

[Multi-GPU DDP trainings](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) must be resumed with the same GPUs and DDP command, i.e. assuming 8 GPUs:
```bash
python -m torch.distributed.run --nproc_per_node 8 train.py --resume  # resume latest checkpoint
python -m torch.distributed.run --nproc_per_node 8 train.py --resume path/to/last.pt  # specify resume checkpoint
```

## Start from Pretrained

If you would like to **start training** from a fully trained model, use the `--weights` argument, not the `--resume` argument:
```bash
python train.py --weights path/to/best.pt  # start from pretrained model
```

Good luck and let us know if you have any other questions!

**Comment by Yzh619** [comment]
> @Yzh619 👋 Hello! Thanks for asking about **resuming training**. YOLOv5 🚀 Learning Rate (LR) [schedulers](https://github.com/ultralytics/yolov5/blob/9f3a388cea66ca71b9bbe057929eed8fbc920a7e/train.py#L109-L142) follow predefined LR curves for the fixed number of `--epochs` defined at training start (`default=300`), and are designed to fall to a minimum LR on the final epoch for best training results. For this reason you can not modify the number of epochs once training has started.
> 
> <img alt="LR Curves" width="850" src="https://user-images.githubusercontent.com/26833433/119332195-8e113a80-bc88-11eb-8eb7-7494ff1d5c01.png">
> 
> If your training was **interrupted** for any reason you may continue where you left off using the `--resume` argument. If your training fully completed, you can start a **new** training from any model using the `--weights` argument. Examples:
> 
> ## Resume Single-GPU
> You may not change settings when resuming, and **no additional arguments** other than `--resume` should be passed, with an optional path to the checkpoint you'd like to resume from. If no checkpoint is passed the most recently updated `last.pt` in your `yolov5/` directory is automatically found and used:
> 
> ```shell
> python train.py --resume  # automatically find latest checkpoint (searches yolov5/ directory)
> python train.py --resume path/to/last.pt  # specify resume checkpoint
> ```
> 
> ## Resume Multi-GPU
> [Multi-GPU DDP trainings](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) must be resumed with the same GPUs and DDP command, i.e. assuming 8 GPUs:
> 
> ```shell
> python -m torch.distributed.run --nproc_per_node 8 train.py --resume  # resume latest checkpoint
> python -m torch.distributed.run --nproc_per_node 8 train.py --resume path/to/last.pt  # specify resume checkpoint
> ```
> 
> ## Start from Pretrained
> If you would like to **start training** from a fully trained model, use the `--weights` argument, not the `--resume` argument:
> 
> ```shell
> python train.py --weights path/to/best.pt  # start from pretrained model
> ```
> 
> Good luck and let us know if you have any other questions!

Thank you very much for your help, I have successfully solved the problem.

**Comment by Rohan-Python** [comment]
> @Yzh619 👋 Hello! Thanks for asking about **resuming training**. YOLOv5 🚀 Learning Rate (LR) [schedulers](https://github.com/ultralytics/yolov5/blob/9f3a388cea66ca71b9bbe057929eed8fbc920a7e/train.py#L109-L142) follow predefined LR curves for the fixed number of `--epochs` defined at training start (`default=300`), and are designed to fall to a minimum LR on the final epoch for best training results. For this reason you can not modify the number of epochs once training has started.
> 
> <img alt="LR Curves" width="850" src="https://user-images.githubusercontent.com/26833433/119332195-8e113a80-bc88-11eb-8eb7-7494ff1d5c01.png">
> 
> If your training was **interrupted** for any reason you may continue where you left off using the `--resume` argument. If your training fully completed, you can start a **new** training from any model using the `--weights` argument. Examples:
> 
> ## Resume Single-GPU
> You may not change settings when resuming, and **no additional arguments** other than `--resume` should be passed, with an optional path to the checkpoint you'd like to resume from. If no checkpoint is passed the most recently updated `last.pt` in your `yolov5/` directory is automatically found and used:
> 
> ```shell
> python train.py --resume  # automatically find latest checkpoint (searches yolov5/ directory)
> python train.py --resume path/to/last.pt  # specify resume checkpoint
> ```
> 
> ## Resume Multi-GPU
> [Multi-GPU DDP trainings](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) must be resumed with the same GPUs and DDP command, i.e. assuming 8 GPUs:
> 
> ```shell
> python -m torch.distributed.run --nproc_per_node 8 train.py --resume  # resume latest checkpoint
> python -m torch.distributed.run --nproc_per_node 8 train.py --resume path/to/last.pt  # specify resume checkpoint
> ```
> 
> ## Start from Pretrained
> If you would like to **start training** from a fully trained model, use the `--weights` argument, not the `--resume` argument:
> 
> ```shell
> python train.py --weights path/to/best.pt  # start from pretrained model
> ```
> 
> Good luck and let us know if you have any other questions!

Is it good to start from a trained model (best.pt) or from last.pt ?

**Comment by Robotatron** [comment]
@Rohan-Python from best.pt, since it has better mAP

**Comment by Minh-Tu-Cao** [comment]
@glenn-jocher What about if I want to continue training after completing first training?
E.g At first, I set 300 epoches and complete the training process. Then, I want to use the weight to further train with 300 more epoches.

**Comment by abdulwaheedsoudagar** [comment]
> @glenn-jocher What about if I want to continue training after completing first training? E.g At first, I set 300 epoches and complete the training process. Then, I want to use the weight to further train with 300 more epoches.

You can pass the last weights as arguments to the model instead of the pre-trained model, like this 
!python yolov5/segment/train.py --img 800 --batch 8 --epochs 100 --data data.yaml  --weights yolov5/runs/train-seg/exp/weights/last.pt

**Comment by glenn-jocher** [comment]
@abdulwaheedsoudagar Thank you for the insight! Continuing training from `best.pt` is indeed a solid choice due to its higher mAP. Good luck with your training!

**Comment by JunHao6** [comment]
Hi Im encountered a freezing issue after my training model crashed, this is what I get to resume running the model. Can you help me, please 


Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅
train: Scanning C:\Users\Tee Jun Hao\OneDrive - UCSI University\Hao\Year 4\FYP A\Yolo\YoloV8\X-ray Luggage Object Detection.v4i.yolov8\train\labels.cache... 306 ima
Traceback (most recent call last):
File "", line 1, in
File "C:\Users\Tee Jun Hao\Python\Lib\multiprocessing\spawn.py", line 122, in spawn_main
exitcode = _main(fd, parent_sentinel)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Tee Jun Hao\Python\Lib\multiprocessing\spawn.py", line 131, in _main
prepare(preparation_data)
File "C:\Users\Tee Jun Hao\Python\Lib\multiprocessing\spawn.py", line 246, in prepare
_fixup_main_from_path(data['init_main_from_path'])
File "C:\Users\Tee Jun Hao\Python\Lib\multiprocessing\spawn.py", line 297, in _fixup_main_from_path
main_content = runpy.run_path(main_path,
^^^^^^^^^^^^^^^^^^^^^^^^^
File "", line 286, in run_path
File "", line 98, in _run_module_code
File "", line 88, in _run_code
File "c:\Users\Tee Jun Hao\OneDrive - UCSI University\Hao\Year 4\FYP A\Yolo\YoloV8\YoloV8.py", line 17, in
result = model.train(data=data_path, epochs=100)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Tee Jun Hao\Python\Lib\site-packages\ultralytics\engine\model.py", line 674, in train
self.trainer.train()
File "C:\Users\Tee Jun Hao\Python\Lib\site-packages\ultralytics\engine\trainer.py", line 199, in train
self._do_train(world_size)
File "C:\Users\Tee Jun Hao\Python\Lib\site-packages\ultralytics\engine\trainer.py", line 318, in _do_train
self._setup_train(world_size)
File "C:\Users\Tee Jun Hao\Python\Lib\site-packages\ultralytics\engine\trainer.py", line 282, in _setup_train
self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=RANK, mode="train")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Tee Jun Hao\Python\Lib\site-packages\ultralytics\models\yolo\detect\train.py", line 55, in get_dataloader
return build_dataloader(dataset, batch_size, workers, shuffle, rank) # return dataloader
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Tee Jun Hao\Python\Lib\site-packages\ultralytics\data\build.py", line 135, in build_dataloader
return InfiniteDataLoader(
^^^^^^^^^^^^^^^^^^^
File "C:\Users\Tee Jun Hao\Python\Lib\site-packages\ultralytics\data\build.py", line 39, in init
self.iterator = super().iter()
^^^^^^^^^^^^^^^^^^
File "C:\Users\Tee Jun Hao\Python\Lib\site-packages\torch\utils\data\dataloader.py", line 439, in iter
return self._get_iterator()
^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Tee Jun Hao\Python\Lib\site-packages\torch\utils\data\dataloader.py", line 387, in _get_iterator
return _MultiProcessingDataLoaderIter(self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Tee Jun Hao\Python\Lib\site-packages\torch\utils\data\dataloader.py", line 1040, in init
w.start()
File "C:\Users\Tee Jun Hao\Python\Lib\multiprocessing\process.py", line 121, in start
self._popen = self._Popen(self)
^^^^^^^^^^^^^^^^^
File "C:\Users\Tee Jun Hao\Python\Lib\multiprocessing\context.py", line 224, in _Popen
return _default_context.get_context().Process._Popen(process_obj)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Tee Jun Hao\Python\Lib\multiprocessing\context.py", line 337, in _Popen
return Popen(process_obj)
^^^^^^^^^^^^^^^^^^
File "C:\Users\Tee Jun Hao\Python\Lib\multiprocessing\popen_spawn_win32.py", line 46, in init
prep_data = spawn.get_preparation_data(process_obj._name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Tee Jun Hao\Python\Lib\multiprocessing\spawn.py", line 164, in get_preparation_data
_check_not_importing_main()
File "C:\Users\Tee Jun Hao\Python\Lib\multiprocessing\spawn.py", line 140, in _check_not_importing_main
raise RuntimeError('''
RuntimeError:
An attempt has been made to start a new process before the
current process has finished its bootstrapping phase.

    This probably means that you are not using fork to start your
    child processes and you have forgotten to use the proper idiom
    in the main module:

        if __name__ == '__main__':
            freeze_support()
            ...

    The "freeze_support()" line can be omitted if the program
    is not going to be frozen to produce an executable.

    To fix this issue, refer to the "Safe importing of main module"
    section in https://docs.python.org/3/library/multiprocessing.html

**Comment by glenn-jocher** [comment]
Hi @JunHao6,

Thank you for reaching out and providing detailed information about the issue you're encountering. It looks like you're running into a multiprocessing issue when trying to resume training after a crash. Let's address this step-by-step:

1. **Ensure Proper Environment Setup**:
   - Make sure you are using the latest versions of YOLOv5 and PyTorch. You can update YOLOv5 by pulling the latest changes from the repository and updating your dependencies:
     ```bash
     git pull
     pip install -r requirements.txt
     ```

2. **Safe Importing of Main Module**:
   - The error message suggests that there might be an issue with how the script is being executed. Ensure that your script includes the following guard to safely handle multiprocessing:
     ```python
     if __name__ == '__main__':
         import torch
         from yolov5 import train  # Adjust the import based on your script's structure

         # Your training code here
         result = model.train(data=data_path, epochs=100)
     ```

3. **Resume Training**:
   - To resume training from the last checkpoint, you can use the `--resume` argument. This will automatically find the latest checkpoint and resume training from there:
     ```bash
     python train.py --resume
     ```
   - Alternatively, you can specify the path to the `last.pt` checkpoint explicitly:
     ```bash
     python train.py --resume path/to/last.pt
     ```

4. **Check for Freezing Layers**:
   - Ensure that the layers you intend to freeze are correctly specified. If you are freezing layers, make sure it aligns with your training strategy.

5. **Multiprocessing Configuration**:
   - If you continue to face issues, you might want to reduce the number of workers used for data loading by setting the `--workers` argument to a lower value:
     ```bash
     python train.py --resume --workers 2
     ```

If the issue persists, please provide a minimum reproducible example of your code and the exact command you are using to run the training. This will help us investigate further. You can refer to our [minimum reproducible example guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details.

Feel free to reach out if you have any other questions or need further assistance!
