### ISSUE TITLE
Issue ModuleNotFoundError : No module named 'utils.loggers.wandb' with Google Colab

### ISSUE THREAD

**Issue by tdchephuong** [ultralytics/yolov5#4868]
Before submitting a bug report, please be aware that your issue **must be reproducible** with all of the following,
otherwise it is non-actionable, and we can not help you:

- **Current repo**: run `git fetch && git status -uno` to check and `git pull` to update repo
- **Common dataset**: coco.yaml or coco128.yaml
- **Common environment**: Colab, Google Cloud, or Docker image. See https://github.com/ultralytics/yolov5#environments

If this is a custom dataset/training question you **must include** your `train*.jpg`, `val*.jpg` and `results.png`
figures, or we can not help you. You can generate these with `utils.plot_results()`.

## 🐛 Bug

I has updated a lastest source. And try to setup a Google Colab and run a train custom dataset. 
But when I trigger the train process, I got this issue as: 
`/content/AICore/yolov5
Downloading https://ultralytics.com/assets/Arial.ttf to /root/.config/Ultralytics/Arial.ttf...
Traceback (most recent call last):
  File "train.py", line 47, in <module>
    from utils.loggers.wandb.wandb_utils import check_wandb_resume
  File "/content/AICore/yolov5/utils/loggers/__init__.py", line 13, in <module>
    from utils.loggers.wandb.wandb_utils import WandbLogger
ModuleNotFoundError: No module named 'utils.loggers.wandb'`

## To Reproduce (REQUIRED)

Input: 

```
%cd /content/AICore/yolov5
!python train.py --img 720 --batch 8 --epochs 300 --data ./data/Custom_coco128.yaml --weights yolov5m.pt
```

Output:

```
/content/AICore/yolov5
Traceback (most recent call last):
  File "train.py", line 47, in <module>
    from utils.loggers.wandb.wandb_utils import check_wandb_resume
  File "/content/AICore/yolov5/utils/loggers/__init__.py", line 13, in <module>
    from utils.loggers.wandb.wandb_utils import WandbLogger
ModuleNotFoundError: No module named 'utils.loggers.wandb'
```

## Expected behavior

The training should start and run successfull.

## Environment

I using Google Colab to setup and run yolov5 training

## Additional context
1. The file Custom_coco128.yaml is not difference much with coco128.yaml, I just change the number of class and path of train/val.
2. The yolov5 is **not the root** folder. I was put the yolov5 in side my project.
structrure:
`AIcore/
       yolov5`

Thank you for your support.

**Comment by glenn-jocher** [comment]
@tdchephuong training commands should be done inside the yolov5/ directory, i.e.:
```
python train.py
```

**Comment by tdchephuong** [comment]
Hi @glenn-jocher ,

I was using cmd: `%cd /content/AICore/yolov5` before run the training command.

I  also retry in Colab with : 
`%cd /content/AICore`
`!python yolov5/train.py --img 720 --batch 8 --epochs 300 --data yolov5/data/Custom_coco128.yaml --weights yolov5m.pt`
But still got the same error.

I was tried to setup in my local computer and can start the train process:
> autoanchor: Analyzing anchors... anchors/target = 4.68, Best Possible Recall (BPR) = 1.0000
> Image sizes 1024 train, 1024 val
> Using 8 dataloader workers
> Logging results to runs\train\exp4
> Starting training for 300 epochs...

Thanks

**Comment by glenn-jocher** [comment]
@tdchephuong see official colab notebook here for training examples. Everything works correctly.
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb?hl=en

**Comment by myssgxka** [comment]
@tdchephuong Hello, did you solve the above problem?
