### ISSUE TITLE
ERROR: pycocotools unable to run: list index out of range

### ISSUE THREAD

**Issue by Lie-huo** [ultralytics/yolov5#487]
I meet a problem，how can i solve it?

COCO mAP with pycocotools... saving detections_val2017__results.json...
ERROR: pycocotools unable to run: list index out of range
Optimizer stripped from runs/exp5/weights/last.pt, 14.7MB
Optimizer stripped from runs/exp5/weights/best.pt, 14.7MB

**Comment by glenn-jocher** [comment]
@Lie-huo pycocotools is an add-on you can use with COCO data. It will try and run anytime your data file is coco.yaml.
