### ISSUE TITLE
How to train Yolov5 on grayscale dataset

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#4870]
## ❔Question
I want to know how to train a grayscale dataset using yolov5? where can I change to train the dataset
Looking for positive response

**Comment by iceisfun** [comment]
Have you tried just training on greyscale data and had bad results?

I have not tried it, however I suspect with a normal size custom data set you should be fine.

https://docs.ultralytics.com/yolov5/tutorials/train_custom_data

Keep in mind having many (>1k) well labeled samples and background data will help.

Also, don't over train your model, people are tempted to have epochs 200 or something when they have very few samples, this will not help you when your dataset is too small.

**Comment by ghost** [comment]
I have not tried just want to ask where to make change to train on a grayscale dataset?

**Comment by glenn-jocher** [comment]
@hammadyounas2008 you should be able to train greyscale datasets just fine. They will be loaded by cv2 as 3-ch images by default. COCO itself has several greyscale images.

**Comment by gboeer** [comment]
I am training the model on grayscale data as well and didn't have to make any changes to the default config or code.
