### ISSUE TITLE
Error about camera call

### ISSUE THREAD

**Issue by lvt111** [ultralytics/yolov5#4874]
## Additional context
The following error occurred when deploying Yolov5 on Jetson Tx2 to call USB
![IMG_20210921_202435](https://user-images.githubusercontent.com/91124674/134170870-4489c94d-50bc-413f-8391-d69031700e27.jpg)

**Comment by lvt111** [comment]
> ## ❔Question
> ## Additional context
>
The following error occurred when deploying Yolov5 on Jetson Tx2 to call USB
> 
> ![IMG_20210921_202435](https://user-images.githubusercontent.com/91124674/134170870-4489c94d-50bc-413f-8391-d69031700e27.jpg)

**Comment by glenn-jocher** [comment]
@lvt111 I'm not sure what the cause could be, but it looks like you can update your code. Try using master or updating, i.e. 
```
git checkout master
git pull
```
