### ISSUE TITLE
Explanation of parameters of yaml file

### ISSUE THREAD

**Issue by AlexisPapaioannou** [ultralytics/yolov5#4877]
## ❔Question
Hello,

Can anyone explain to me what means the parameters "from", "number" as well "args" as well which is the kernel size, stride and pad? 

## Additional context
 # [from, number, module, args]
  [[-1, 1, Focus, [64, 3]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C3, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 9, C3, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, C3, [512]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 1, SPP, [1024, [5, 9, 13]]],
   [-1, 3, C3, [1024, False]],  # 9
  ]

**Comment by glenn-jocher** [comment]
@AlexisPapaioannou from which layer, number of repeats, module, module arguments.

**Comment by AlexisPapaioannou** [comment]
Thank you @glenn-jocher. So, specifically for the second layer "[-1, 1, Conv, [128, 3, 2]], # 1-P2/4 " and for the module arguments, the 128 represents the number of filters, the 3 the kernel size and 2 the number of strides?

**Comment by glenn-jocher** [comment]
@AlexisPapaioannou yes that's correct. 128 is the c2 channel output count. channel input count is inherited from previous layer.
