### ISSUE TITLE
anchor_box

### ISSUE THREAD

**Issue by 123456789mojtaba** [ultralytics/yolov5#488]
where is size of anchor boxes in your code?
Ty

**Comment by glenn-jocher** [comment]
https://github.com/MagicFrogSJTU/yolov5/blob/1e95337f3aec4c12244802bb6e493b07b27aa795/models/yolov5s.yaml#L1-L52

**Comment by glenn-jocher** [comment]
https://github.com/ultralytics/yolov5/blob/5e970d45c44fff11d1eb29bfc21bed9553abf986/models/yolov5s.yaml#L1-L52
