### ISSUE TITLE
How to judge negative samples? How to calculate the position of negative samples?

### ISSUE THREAD

**Issue by Mrgao9** [ultralytics/yolov5#4881]
## ❔Question
Dear author, where is the code for negative sample processing?
## Additional context
I only see the processing of positive samples in the loss.py file 。I want to know how to judge negative samples? How to calculate the position of negative samples?

I look forward to your reply very much. Thank you very much！

**Comment by glenn-jocher** [comment]
@Mrgao9 all anchors produce objectness loss, see loss.py for details.

**Comment by Mrgao9** [comment]
> @Mrgao9 all anchors produce objectness loss, see loss.py for details.

Thank you very much for your reply. I have checked the loss.py file. The core matching rules I understand are:

1、For any output layer, the shape rule is directly used for matching, that is, the aspect ratio of the bbox and the anchor of the current layer is calculated. If the aspect ratio is greater than the set threshold, it indicates that the matching degree between the bbox and anchor is not enough, and the bbox will be discarded and considered as the background in the prediction of the layer

2、For the remaining bbox, calculate the grid in which it falls. At the same time, use the rounding rule to find the nearest two grids. Consider these three grids as responsible for predicting the bbox. It can be found that the number of roughly estimated positive samples is at least three times higher than that of the previous Yolo series

![image](https://user-images.githubusercontent.com/22071198/134323663-d30d896f-288f-4cd8-acb5-b439c66c6504.png)

As shown in the figure above, the green dot indicates the center of the bbox. Now, it is necessary to additionally consider its two nearest neighborhood grids as the positive sample anchor of the bbox. From here, we can find that the value range of XY regression branch of bbox is no longer 0 ~ 1, but -0.5 ~ 1.5


So, except for the positive samples screened, are all other samples negative?  I don't understand how negative samples are obtained

Don't you need to calculate the position of the negative sample ？
How to balance the unbalanced number of positive samples and negative samples？

**Comment by Mrgao9** [comment]
> > @Mrgao9 all anchors produce objectness loss, see loss.py for details.
> 
> Thank you very much for your reply. I have checked the loss.py file. The core matching rules I understand are:
> 
> 1、For any output layer, the shape rule is directly used for matching, that is, the aspect ratio of the bbox and the anchor of the current layer is calculated. If the aspect ratio is greater than the set threshold, it indicates that the matching degree between the bbox and anchor is not enough, and the bbox will be discarded and considered as the background in the prediction of the layer
> 
> 2、For the remaining bbox, calculate the grid in which it falls. At the same time, use the rounding rule to find the nearest two grids. Consider these three grids as responsible for predicting the bbox. It can be found that the number of roughly estimated positive samples is at least three times higher than that of the previous Yolo series
> 
> ![image](https://user-images.githubusercontent.com/22071198/134323663-d30d896f-288f-4cd8-acb5-b439c66c6504.png)
> 
> As shown in the figure above, the green dot indicates the center of the bbox. Now, it is necessary to additionally consider its two nearest neighborhood grids as the positive sample anchor of the bbox. From here, we can find that the value range of XY regression branch of bbox is no longer 0 ~ 1, but -0.5 ~ 1.5
> 
> So, except for the positive samples screened, are all other samples negative? I don't understand how negative samples are obtained
> 
> Don't you need to calculate the position of the negative sample ？
> How to balance the unbalanced number of positive samples and negative samples？

@glenn-jocher  I very much look forward to your guidance and help answer the above questions. Thank you very much！

**Comment by glenn-jocher** [comment]
@Mrgao9 I'm sorry I don't have time to respond personally but all anchor and loss computation is shown in loss.py.

**Comment by Mrgao9** [comment]
> @Mrgao9 I'm sorry I don't have time to respond personally but all anchor and loss computation is shown in loss.py.

Thank you very much for your reply！

**Comment by FrancescoB-Vintra** [comment]
Hello, I was also wondering how the negatives are handled.
I neither could find in loss.py how grid cells which are not matched with any target box are treated.

What I could understand from there, is that the IoU between predicted boxes (not anchors) with targets is used as a objectness regression target. Then, I would expect that when predictions are bad (e.g. beginning of the training) the IoU score will be low, causing that sample to be taken as a negative for that specific grid cell prediction. I can be wrong so please correct me if it's the case.

Except from this, I could not find explicit negative management, so I would also be interested in the answer to @Mrgao9 's question, if anyone can give a hint.
Thanks

**Comment by glenn-jocher** [comment]
@FrancescoB-Vintra all anchors incur loss, negative objectness target is 0.0.

**Comment by FrancescoB-Vintra** [comment]
@glenn-jocher thanks for replying

I understand here is where objectness loss is computed for both grid cells which are matched with groundtruth and those which are not
https://github.com/ultralytics/yolov5/blob/070af88108e5675358fd783aae9d91e927717322/utils/loss.py#L155

If i'm not wrong, no feedback is given to box coordinates regressors nor category in case of no match with GT

**Comment by glenn-jocher** [comment]
@FrancescoB-Vintra yes that's right.
