### ISSUE TITLE
My model is trained on 640 image size but I am forced to detect my objects on a very large image size lets say around 8000x2500 (varies)

### ISSUE THREAD

**Issue by alijundi** [ultralytics/yolov5#4883]
So my model is trained very well and it is picking up the objects as expected. However, I need to collect objects from a large image (very large) and crop the collected objects to process it later. I use the detector --img with a large image size I notice it is not picking up my objects correctly.

Can someone point me to the right direction please.

Thanks.

**Comment by glenn-jocher** [comment]
@alijundi the size of the images is irrelevant, if the objects are the same size in pixels then everything will work well.

**Comment by JJrodny** [comment]
Hey @alijundi, I was pointed to SAHI for a similar problem, hope this helps https://github.com/obss/sahi
