### ISSUE TITLE
Rotation problem

### ISSUE THREAD

**Issue by mohammad69h94** [ultralytics/yolov5#4884]
## ❔Question
In the real world, I need to detect rotated objects such as digits on the license plate.
What is your idea to detect rotation objects in degrees 45, 90, 180, 270, 360?

**Should I label this type of data? Or tune the hyperparameter to augment images to these degrees?**

**Comment by glenn-jocher** [comment]
@mohammad69h94 you can update degrees hyper parameter to 180 for fully random rotation angles if you’d like, and/or you can appply a random choice angle during augmentation as well in random_perspective()
