### ISSUE TITLE
Understanding weights file 

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#4885]
I am trying to a custom object detection model of 10 classes using YOLOV5 . For that i am using yolo5s.pt (which are weights of pretrained model on coco dataset) as my initial weights .
 I am not able to understand how i am able to use the weights of coco dataset(80 classes) to my 310class model , because from my understanding output will be like [pc1,pc2,pc3,--------pc80,bx,by,wx,wy] where pc1,pc2 are probabilities of each class.
So the yolo5s.pt(coco dataset) should be returning an output vector of form [pc1,pc2,pc3,--------pc10,bx,by,wx,wy]  where as my custom model should return [pc1,pc2,pc3,bx,by,wx,wy]. How am i able to use coco dataset with diff weight shape as the initial step

**Comment by glenn-jocher** [comment]
@richard2611 any pretrained YOLOv5 model can be trained on any other dataset, class counts are handled automatically, i.e. you can train a new YOLOv5s model on VOC (20 classes) starting from COCO trained weights (80 classes):
```
python train.py --data VOC.yaml --weights yolov5s.pt
```

Nothing else needed.

**Comment by ghost** [comment]
@glenn-jocher Thanks for your reply , I was actually able to train the model with my custom dataset.
My doubt is are the no.of parameters in yolov5s.pt(which we got from 80 classes of coco dataset) and the no.of parameters in weight file after training with custom dataset (which is of less no.of classes) same? Can the model automatically be able to reduce the parameters of output vector size according to classes  or if its less classes will it simply consider [pc1,pc2,pc3,0,0,0,0----bx,bx,wx,wy]

**Comment by glenn-jocher** [comment]
@richard2611 models are adapted as/if necessary to your dataset before training starts.
