### ISSUE TITLE
how to print frame rate per second on video (FPS)

### ISSUE THREAD

**Issue by hammad2008** [ultralytics/yolov5#4886]
## ❔Question
i have a video i want to print frame rate per second how can i do that in detect.py

**Comment by glenn-jocher** [comment]
@hammad2008 for FPS just do 1000 / inference_time (ms)

**Comment by ghost** [comment]
@glenn-jocher  is it possible to print on offline video?

**Comment by glenn-jocher** [comment]
@hammadyounas2008 video inference is explained in README:
```
python detect.py --source video.mp4
```

**Comment by ghost** [comment]
@glenn-jocher yes i have done that inference time is printed but not FPS, that's why I want to print on image

**Comment by glenn-jocher** [comment]
@hammadyounas2008 you can apply burn-in text to images using the Annotator instance in detect.py, i.e.:
https://github.com/ultralytics/yolov5/blob/59aae85a7e40701bb872df673a6ef288e99a4ae3/detect.py#L214

**Comment by ghost** [comment]
@glenn-jocher I also want to print the fps. Can you be more specific please. When I added `annotator.box_label(xyxy, label, color=colors(c, True))` after
          `  # Stream results
            if view_img:
                cv2.imshow(str(p), im0)
                cv2.waitKey(1)  # 1 millisecond`
The errorr: **NameError: name 'annotator' is not defined** occured.

**Comment by glenn-jocher** [comment]
@VirtuallKingg `annotator` is defined in detect.py on this line:
https://github.com/ultralytics/yolov5/blob/7ebb5e5da673350d4c168cf60d01986a5e0f00cc/detect.py#L141
