### ISSUE TITLE
Sliced inference with SAHI on detecting small object in large Aerial image

### ISSUE THREAD

**Issue by Bommi95** [ultralytics/yolov5#4888]
## 🚀 Feature

In the detection stage, the model perform sliced inference on a large image in order to detect small objects and avoid overlapping counts.

## Motivation

It is a better way to improving object detection on Aerial image as these image are large and come with small objects.

## Alternatives

There are libraries in github already doing this. For example SAHI: https://medium.com/codable/sahi-a-vision-library-for-performing-sliced-inference-on-large-images-small-objects-c8b086af3b80 They have a sliced inference library and did a detection example using Yolov5! Maybe we are able to integrate this in our detection process.

**Comment by glenn-jocher** [comment]
@Bommi95 hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
