### ISSUE TITLE
hyparameter

### ISSUE THREAD

**Issue by 123456789mojtaba** [ultralytics/yolov5#489]
for very small detection what changes do hyperparameter need?
for example iou_threshold and anchor_threshold?
another question is : iou_threshold for training is 0.2 but for detecting is 0.4 why aren't they same?

**Comment by glenn-jocher** [comment]
@123456789mojtaba for small object detection no changes are needed. I'd recommend training at higher --img-size however, up to native resolution for extremely small objects. 

The iou thresholds you mention serve different purposes, they are not comparable.

We have an experimental architecture focused on small object detection, if you have resources and expertise perhaps you could train it side by side with the default model and upload your results here. What is your application exactly?

**Comment by shahidammer** [comment]
```
Traceback (most recent call last):
  File "train.py", line 516, in <module>
    print_mutation(hyp, results, opt.bucket)
  File "/home/ubuntu/yolov5/utils/utils.py", line 833, in print_mutation
    b = '%10.3g' * len(hyp) % tuple(hyp.values())  # hyperparam values
TypeError: must be real number, not str
```
Getting the above error when I try to evolve the hyperparams @glenn-jocher 
`python train --evolve
`

**Comment by 123456789mojtaba** [comment]
thank you.
my application is detecting car and pedestrians in arial images

**Comment by glenn-jocher** [comment]
@123456789mojtaba --evolve is currently inoperable due to a bug introduced by a recent PR. This should be fixed within the next week or so. In the meantime you can manually try balancing your losses, as this is the first step before evolving.

**Comment by glenn-jocher** [comment]
@123456789mojtaba `--evolve` functionality has been restored in 8056fe2db84793bcb3e664d4c9fa474caf267150. We fixed the bug affecting it and added a few new features, allowing you to specify per-parameter evolution gains and limits. Please let us know if you run into anymore issues.

**Comment by nanhui69** [comment]
do you get good result by use the evolve @123456789mojtaba
