### ISSUE TITLE
Grayscale images 

### ISSUE THREAD

**Issue by AlexisPapaioannou** [ultralytics/yolov5#4894]
## ❔Question
Hello,

When I used the Yolov5 with gray scale images I received the below error. I had also added a parameter ch: 1 into the yaml file.  

## Additional context
Given groups=1, weight of size [8, 1, 3, 3], expected input[16, 3, 128, 128] to have 1 channels, but got 3 channels instead

## The custom yaml file
# parameters
nc: {num_classes}  # number of classes
ch: 1  # input channels 
depth_multiple: 0.33  # model depth multiple
width_multiple: 0.35  # layer channel multiple

# anchors
anchors:
  - [4,5,  8,10,  13,16]  # P3/8
  - [23,29,  43,55,  73,105]  # P4/16
  - [146,217,  231,300,  335,433]  # P5/32

# YOLOv5 backbone
 # [from, number, module, args] # kernel, padding, stride
backbone:
# [from, number, module, args]
  [[-1, 1, Conv, [16, 3, 2]],  # 0-P1/2
   [-1, 1, Conv, [8, 3, 2]],  # 1-P2/4
   [-1, 1, Conv, [32, 3, 2]],  # 1-P2/4
   [-1, 3, C3, [32]],
   [-1, 1, Conv, [32, 3, 2]],  # 3-P3/8
   [-1, 9, C3, [64]],
   [-1, 1, Conv, [64, 3, 2]],  # 5-P4/16
   [-1, 9, C3, [128]],
   [-1, 1, Conv, [128, 3, 2]],  # 7-P5/32
   [-1, 1, SPP, [256, [5, 9, 13]]],
   [-1, 3, C3, [128, False]],  # 9
  ]

**Comment by glenn-jocher** [comment]
@AlexisPapaioannou no modifications to anything are required to train greyscale.
