### ISSUE TITLE
determine the importance of losses

### ISSUE THREAD

**Issue by hamid-mp** [ultralytics/yolov5#4895]
Hi, I've recently change your code and add a new regression task to it beside the previous tasks. it noticed that you set a parameter ((gain)) for each calculated loss.
in hyp.scratch.yaml file you put  box: 0.05  # box loss gain    cls: 0.5  # cls loss gain. How did you choose these values?

**Comment by glenn-jocher** [comment]
@hamid-mp loss magnitudes correlate to their impact on the gradient, so tune your losses accordingly to your balancing priorities.
