### ISSUE TITLE
How many yolo models running can one NVIDIA gpu card can handle?

### ISSUE THREAD

**Issue by gondimjoaom** [ultralytics/yolov5#4896]
I'm trying to measure how many gpu cards one project is going to need and for that I need to run several tests at once. Is there any protocol or step by step to get such information?

FYI: it is a NVIDIA Tesla T4.

**Comment by glenn-jocher** [comment]
@gondimjoaom the question is a bit meaningless, as CUDA memory usage depends on a variety of factors, and model size, or number of models is just one part of this.

**Comment by aviezab** [comment]
@gondimjoaom You can run Your model, if it fits, then run `nvidia-smi` and look at the memory usage.
Then You can determine how many models the GPU can run.
