### ISSUE TITLE
Can I add IOU to the label box in a validation/test set?

### ISSUE THREAD

**Issue by nicotessone** [ultralytics/yolov5#4897]
## ❔Question
Hi, I'm very greatfull for your job!
In my project it's very important the IOU, Can I add IOU to the box label (in a simple way ) in the validation/test images?
Thank You!!

**Comment by glenn-jocher** [comment]
@nicotessone you would need to customize val.py plotting routines to accomplish this. See val.py:
https://github.com/ultralytics/yolov5/blob/master/val.py

**Comment by nicotessone** [comment]
Thanks Glenn!!
