### ISSUE TITLE
Bbox coordiantes and Class label from Neuron converted model

### ISSUE THREAD

**Issue by diazGT94** [ultralytics/yolov5#4899]
Hello, 

I've succeed in convert a model to neuron and can see the output in tensor format. However, I would like some guidance from the steps performed in the detect.py script to extract the bbox coordinates and the class name.

Thanks,

**Comment by glenn-jocher** [comment]
@diazGT94 the pre and post processing steps for inference are shown here for YOLOv5 PyTorch Hub inference:
https://github.com/ultralytics/yolov5/blob/ce7fa81d4e342ca97f7459f6dd10036b3449321b/models/common.py#L309-L348
