### ISSUE TITLE
Yolov5 Quantization : FP16 and INT8

### ISSUE THREAD

**Issue by VirajDeshwal** [ultralytics/yolov5#4900]
## Motivation
Opening this feature request for quantizing the Yolov5 to run the real-time inference on edge devices such as Jetson Nano, Intel NUC, etc.

## Pitch
Inference on a 30 FPS video stream with limited compute power would be great.

**Comment by glenn-jocher** [comment]
@VirajDeshwal thanks for the feedback! We have a current effort in place on this front, should be released publically within the next month or two.

**Comment by alikaz3mi** [comment]
This feature would be awesome! Thank you for your amazing work!
