### ISSUE TITLE
Why there is a need to convert Pytorch model to some other for making it run on Raspberry Pi?

### ISSUE THREAD

**Issue by jaskiratsingh2000** [ultralytics/yolov5#4908]
@glenn-jocher  I just have a question that what is the core difference between the Pytorch Model and the Exported(Tflite model)? As I could see that Pytorch model is not working well on the Raspberry Pi whereas the Tflite works better but I am not able to figure out at what are the reasons for that it's working.

What does the Pytorch model do that Tflite doesn't do?

@batrlatom Do you have any idea about that?

**Comment by glenn-jocher** [comment]
@jaskiratsingh2000 I don't have RPi experience myself. What do you mean 'not working well'?

**Comment by jaskiratsingh2000** [comment]
This is something a real concern. Here is what I mean by the not working well that is not giving the correct mAP value - https://github.com/jaskiratsingh2000/Research-Scalable-Vehicle-Detection-on-Edge-Devices/issues/24

**Comment by JNaranjo-Alcazar** [comment]
Hi @jaskiratsingh2000 

Although I am not a hardware expert, I have been able to work for the last 5 years in ML on mobile devices. I don't quite understand why the Pytorch model doesn't work properly on the RPi (I have no experience with it) but I guess the format is not optimised for architectures other than a conventional PC. However, it does make sense that the TFLite model does. The TFLite models are optimised for ARM architectures, the RPi being one of them. I guess the Pytorch framework must have some similar format that can work on the RPi.

However, my main concern on the RPi is the inference time. I managed to get 420 ms per image (TFLite - int8). What are your runtimes? 
Best regards

**Comment by jaskiratsingh2000** [comment]
@JNaranjo-Alcazar I also got almost the same inference time. Also, @JNaranjo-Alcazar I want to ask that were you able to check the mAP value of the TFlite version? that is is the tf.py model? I am very much curious to know that what is the accuracy performance of the tf.py model on Raspberry Pi.

Also, @glenn-jocher @batrlatom and @JNaranjo-Alcazar I want to ask you one thing that what is included inside the Pytorch model and the TFfite model? I think we are missing out on the developer documentation which can demonstrate these things. Would really apprecate your dtailed response. can you let me know please.

**Comment by jaskiratsingh2000** [comment]
@JNaranjo-Alcazar @batrlatom can you please let me know on above?

**Comment by jaskiratsingh2000** [comment]
@JNaranjo-Alcazar Any update on this?//
