### ISSUE TITLE
data train and val

### ISSUE THREAD

**Issue by thinhemb** [ultralytics/yolov5#4912]
## ❔Question
I use the same data train and val . how to let the number val = train/10

**Comment by glenn-jocher** [comment]
@thinhemb if you have a single directory of images, you can autosplit this and then point your data.yaml to the newly generated train.txt, val.txt, etc.:
https://github.com/ultralytics/yolov5/blob/149263279655d26dc3c74192773de1c9c5a772c9/utils/datasets.py#L842-L864
