### ISSUE TITLE
ONNXRuntime C++ inference code for YOLOv5.

### ISSUE THREAD

**Issue by itsnine** [ultralytics/yolov5#4915]
Hi everyone! Here is C++ implementation of inference code for YOLOv5 ONNX model using ONNXRuntime framework. If someone is interested in link to the repo: https://github.com/itsnine/yolov5-onnxruntime

Thanks for all contributors of ultralytics/yolov5.

Here is a demo of results.
![bus_result](https://user-images.githubusercontent.com/68300349/134765095-f7f092d6-ba19-4078-8165-665ca0887f1c.jpg)
![zidane_result](https://user-images.githubusercontent.com/68300349/134765099-bd6dfaf3-a467-4369-b3f9-b95006a3a4a0.jpg)

**Comment by glenn-jocher** [comment]
@itsnine very cool! Do you know if there is any benefit or drawback to C++ inference via ONNX vs TorchScript?
