### ISSUE TITLE
How can I understand the fitness?

### ISSUE THREAD

**Issue by Shawn-gitman** [ultralytics/yolov5#4918]
During the hyperparameter evolution, I see the difference between code and training log regarding fitness. I have noticed metrics.py that it limits to four weighted options(precision, recall, map0.5, map0.5:0.95). Otherwise, it shows 7 options in the log. How can I interpret these figures?

**Comment by glenn-jocher** [comment]
@Shawn-gitman evolve.csv has clearly labelled columns if that's what you're asking about:
<img width="1696" alt="Screen Shot 2021-09-25 at 7 21 13 AM" src="https://user-images.githubusercontent.com/26833433/134774771-4cf7693b-45b6-4af7-9296-d04cbca24ff1.png">

**Comment by Shawn-gitman** [comment]
Thank you! This helps my understanding.
