### ISSUE TITLE
resized image is saved without keeping aspect ratios in the inference (detect.py)

### ISSUE THREAD

**Issue by Mshz2** [ultralytics/yolov5#4921]
Question
Hi, I have a dataset with the image resolutions of 1280* 720. I have kept the --img tag 1280 for both the train.py and detect.py. However, when I run the detect.py, the saved sampled in run/detect folder, which contains image with detections, is shrinked to a rectangular shape of 1280*1280. 
 
Is there any way for the saved images to keep the original 1280*720 size? 

Best

**Comment by glenn-jocher** [comment]
@Mshz2 I don't understand your question. Annotated images are saved to runs/detect at their original shape, YOLOv5 does not alter them.
