### ISSUE TITLE
Removing System Calls

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/yolov5#4922]
@KalenMike this thread is about removing system calls like you suggested. Following removal of unzip calls in #4919 the main remaining system calls are here:

### subprocess.check_output()
We use this to return values
<img width="1036" alt="Screen Shot 2021-09-25 at 10 17 27 AM" src="https://user-images.githubusercontent.com/26833433/134780448-b08772ce-ca9c-4c9e-92de-5dc3b88dff4f.png">

### os.system()
Used when only a success/failure output is required
<img width="1036" alt="Screen Shot 2021-09-25 at 10 17 38 AM" src="https://user-images.githubusercontent.com/26833433/134780452-c3b6a9ff-cc32-4620-8124-0c3ed4f391ed.png">

Added to our TODO list.

**Comment by glenn-jocher** [comment]
@KalenMike most of the calls are either `pip`, `curl`, `gsutil` or `git` commands. The state of these is:

- `pip`: from https://stackoverflow.com/a/50255019
> The officially recommended way to install packages from a script is by calling pip's command-line interface via a subprocess. Most other answers presented here are not supported by pip. Furthermore since pip v10, all code has been moved to pip._internal precisely in order to make it clear to users that programmatic use of pip is not allowed.
> 
> Use sys.executable to ensure that you will call the same pip associated with the current runtime.
> 
> ```
> import subprocess
> import sys
> 
> def install(package):
>     subprocess.check_call([sys.executable, "-m", "pip", "install", package])
> ```

- `curl`: curl commands are useful for special download handling not available in other packages (when cookies are required, for automatic retry and resume on fail (important for large dataset downloads with shaky connections like Objects365)), and as backup download commands to the default torch download function:
https://github.com/ultralytics/yolov5/blob/39c17ce0b922bbafcf9f8da64f286fef01040727/utils/downloads.py#L24-L41

- `gsutil`: mostly used for undocumented GCP functionality during evolution. **gsutil is available as a pip install**, but the directions (https://cloud.google.com/storage/docs/gsutil_install#debian-and-ubuntu) have a big "Experimental" warning and look pretty complicated, and also vary by OS.

- `git`: used to check git status and advise user to update repo (hopefully addressing our huge issue of users not aware of updated code). **GitPython package is available as a pip install** (https://github.com/gitpython-developers/GitPython) but seems to be a 3rd party tool and no longer under active development (but is maintained).

**Comment by thecaffeinedev** [comment]
I can work on creating a PR, replacing the system calls with Python libs. If it's okay ? @glenn-jocher

**Comment by glenn-jocher** [comment]
@TheCaffeineDev we were looking at this a few weeks ago to try to improve compatibility across environments. Unfortunately most of the remaining system calls are not easy to remove as shown in  https://github.com/ultralytics/yolov5/issues/4922#issuecomment-927198737 above. If you have any ideas though then yes, please submit a PR. Thanks!
