### ISSUE TITLE
Is there a data enhancement module that comes with this project?

### ISSUE THREAD

**Issue by czczmr** [ultralytics/yolov5#4925]
## Additional context
Like translation, rotation, contrast

**Comment by glenn-jocher** [comment]
@czczmr yes, most common augmentations are set by your hyperparameter file:
https://github.com/ultralytics/yolov5/blob/39c17ce0b922bbafcf9f8da64f286fef01040727/data/hyps/hyp.scratch.yaml#L22-L34

And you can add any additional augmentations you want via our Albumentations integration here:
https://github.com/ultralytics/yolov5/blob/39c17ce0b922bbafcf9f8da64f286fef01040727/utils/augmentations.py#L17-L30
