### ISSUE TITLE
No "requests" dependecy in requirements.txt

### ISSUE THREAD

**Issue by sandstorm12** [ultralytics/yolov5#4928]
## 🐛 Bug

To get models from hub you need requests dependency, yet it is not present in the requirements.txt. Adding it would be nice.

And I think giving the pandas dependency a version requirement makes the repo more reliable.

**Comment by glenn-jocher** [comment]
@sandstorm12 hi, thank you for your feature suggestion on how to improve YOLOv5 🚀! Yes, adding `requests` is a good idea, though I'm surprised it is not installed by pytorch.

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by iceisfun** [comment]
@glenn-jocher We had this kind of issue when testing against non standard docker environments and had a number of missing requirements.

If it would be helpful I think a complete list could be made by just replicating what we did for that testing.

I did not submit a PR because the testing was an odd setup I would not expect people to use.

**Comment by glenn-jocher** [comment]
@iceisfun yes, any additional requirements you can think of please let us know. I don't know any myself other than the requests library mentioned above.

**Comment by sandstorm12** [comment]
Sure, I'm currently working on your repo in a custom docker, and I'll send you a complete list of missing requirements soon.
please keep the issue open for a couple of days
thanks :)

**Comment by glenn-jocher** [comment]
Great thanks!

**Comment by sandstorm12** [comment]
Sorry for the long wait. 

I have fully tested the train and inference scripts and the only requirement missing was "requests".
I will submit a PR.

Thanks.

**Comment by glenn-jocher** [comment]
@sandstorm12 thanks I see it!
