### ISSUE TITLE
About the data in metrics.py

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#4929]
@glenn-jocher 
Hello, when I was studying how to extract the P and R data in PR_curve.png, I found this interesting phenomenon:
https://github.com/ultralytics/yolov5/blob/39c17ce0b922bbafcf9f8da64f286fef01040727/utils/metrics.py#L305

I tried to add an output code below this code:
```python
print(f'px: {px}, py: {py.mean(1)}')
```

When the training is complete,the result is output like this in the shell:
```shell
px: [          0    0.001001    0.002002    0.003003    0.004004    0.005005    0.006006    0.007007    0.008008    0.009009     0.01001 ...(Omit)]
```

**Comment by glenn-jocher** [comment]
@Zengyf-CVer px and py are the PR curve x and y values.

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
Thank you very much.
