### ISSUE TITLE
Why the object confidence threshold  will  influence  the mAP?

### ISSUE THREAD

**Issue by daiwc** [ultralytics/yolov5#493]
## ❔Question

Why the object confidence threshold  will  influence  the mAP?

## Additional context

theoretically, the mAP is obtain by adjust  object confidence threshold to get different  precision and recall to get the area under curve  of  PR

**Comment by glenn-jocher** [comment]
@daiwc in theory --conf should be set to 0. This takes forever to compute, ergo in practice you set it to a higher value, which affects mAP and speed of computation.

**Comment by daiwc** [comment]
@glenn-jocher  Thanks a lot， the confidence threshold set to 0.001 is just to caculate  mAP ， when increasing  the  confidence threshold , a part of AUC would be abandoned.

**Comment by daiwc** [comment]
@glenn-jocher  some thing strange happened, when I increase  the test image  resolution from  640  to 1280  ,  the mAP  decrease form 0.6 to 0.477

**Comment by chafikblm** [comment]
@glenn-jocher 

**I am using Yolo v5 to the detection of objects**
![image](https://user-images.githubusercontent.com/57290900/90890421-82b37a80-e3a9-11ea-9835-85470f65c906.png)

**test**
I get the best result  with --conf 0.00011 and --img 416 

![image](https://user-images.githubusercontent.com/57290900/90890939-695efe00-e3aa-11ea-8f08-2cf8837d7c5f.png)

**See my project at this link:**
https://www.kaggle.com/chafikblm77/detection-of-objects-in-images-with-yolo-v5

###**My question is:**
Even though I got greater than 0.91 in **mAP**, I still got the probability 0.00 for each class, and --conf should be set to 0.00011 for best result
Why should --conf be set less than 0.01 and greater than 0.00011 for best result? where is the problem?? and thanks for you

![image](https://user-images.githubusercontent.com/57290900/90890613-d920b900-e3a9-11ea-80c5-d1c4ef1798d0.png)
