### ISSUE TITLE
Hyperparameter adjustment problem

### ISSUE THREAD

**Issue by ahong007007** [ultralytics/yolov5#4934]
## ❔Question

hyp['cls'] *= nc / 80. * 3. / nl  # scale to classes and layers

Thank you for your wonderful work. I found that when setting the hyperparameter cls, the training coco denominator is 80 understandable. When training objects365, should it be adjusted to

*hyp['cls'] *= nc / 365. * 3. / nl  # scale to classes and layers*

What is the principle of cls setting? Thank you very much.

![image](https://user-images.githubusercontent.com/22077027/134831715-c3031439-43f9-47a3-87f1-e7db9d3caf46.png)

**Comment by glenn-jocher** [comment]
@ahong007007 these lines adapt training settings to your dataset automatically. No action is needed on your part here.
