### ISSUE TITLE
The number of my webcam's pixels is 1920×1080, but if I run detect.py, the video is saved as 640×360

### ISSUE THREAD

**Issue by Desty2664** [ultralytics/yolov5#4937]
## ❔Question
The number of my webcam's pixels is 1920×1080, but if I run detect.py, the video is saved as 640×360
I already tried changing the image size of the parser, but to no avail.
How can I get a video as 1920×1080 using my webcam?

## Additional context
I have experience with this webcam in other projects. At that time, OpenCV recognized the webcam as 1980×1080 and used it.
![terminal](https://user-images.githubusercontent.com/90437493/134845898-4e82d4a7-3f5d-40e1-ae40-65efefa04c13.jpg)

**Comment by glenn-jocher** [comment]
@Desty2664 your stream is at 1088x1920, inference is run at 640x360. You can update you inference size with --img:
```
python detect.py --img 1280
```

EDIT: sorry had these backwards. Your stream is at 640, your inference is at 1920. If you want to modify your actual stream properties that's between you and cv2 in the dataloader. See https://github.com/ultralytics/yolov5/blob/c5ba2abb4afb9fe8c671f14eb5200647893efe30/utils/datasets.py#L280

**Comment by Desty2664** [comment]
@glenn-jocher Thanks for your help to solve the problem.
I found that this was an error in OpenCV that appeared occasionally.
It was solved by modifying the class LoadStreams in dataset.py as shown in the picture below.
![Thank you for help](https://user-images.githubusercontent.com/90437493/135024088-23a63f73-b806-4a9e-a453-43061927ae76.jpg)
