### ISSUE TITLE
onnxruntime speed is slow

### ISSUE THREAD

**Issue by happyday-lkj** [ultralytics/yolov5#4938]
## ❔Question
@timstokman 
I convert the .pt model to .onnx model file, the .pt model file is about 10ms, but the onnx model inference speed is about 100ms, it seems the .onnx model is run on cpu! how to deal with it? Also, my onnxruntime is GPU version

**Comment by timstokman** [comment]
There are diffierent versions of the onnx package. Some are suited for running model inference on the cpu, others run the model on a gpu. To install the CUDA/GPU onnxruntime (assuming you're using python here):

```
pip uninstall onnxruntime
pip install onnxruntime-gpu
```

**Comment by happyday-lkj** [comment]
> There are diffierent versions of the onnx package. Some are suited for running model inference on the cpu, others run the model on a gpu. To install the CUDA/GPU onnxruntime (assuming you're using python here):
> 
> ```
> pip uninstall onnxruntime
> pip install onnxruntime-gpu
> ```

yes, my onnxruntime version is onnxruntime-gpu==1.9.0，so, it seems that it is not this problem.

**Comment by timstokman** [comment]
Usually for me, if parts of the model can't be optimized or can't be run on my GPU, onnx will print a warning on the console when loading the model. Look at your console messages, might give a clue. When exporting the model make sure you using the --simplify option. Also, if your data might be differently sized from when you trained, consider exporting with dynamic axes, big performance improvement. If you have a new onnx version, consider specifying a later opset version when exporting, it'll start using new onnx features.

If those things don't work, you also might have more luck creating a ticket on the onnx package. They're better equiped solving performance issues.

**Comment by happyday-lkj** [comment]
> Usually for me, if parts of the model can't be optimized or can't be run on my GPU, onnx will print a warning on the console when loading the model. Look at your console messages, might give a clue. When exporting the model make sure you using the --simplify option. Also, if your data might be differently sized from when you trained, consider exporting with dynamic axes, big performance improvement. If you have a new onnx version, consider specifying a later opset version when exporting, it'll start using new onnx features.
> 
> If those things don't work, you also might have more luck creating a ticket on the onnx package. They're better equiped solving performance issues.

thanks for your reply, there is no additional message printed, and when export the model with --simplity option, the result is same

**Comment by timstokman** [comment]
I suggest you try --dynamic for the dynamic axes export, or --opset (try 14 or 15). Otherwise, create a ticket at the onnx repository.

**Comment by happyday-lkj** [comment]
> I suggest you try --dynamic for the dynamic axes export, or --opset (try 14 or 15). Otherwise, create a ticket at the onnx repository.

maybe this is the key issue, https://github.com/microsoft/onnxruntime/issues/2750

**Comment by happyday-lkj** [comment]
> I suggest you try --dynamic for the dynamic axes export, or --opset (try 14 or 15). Otherwise, create a ticket at the onnx repository.

hi, it may be my environment problem, when I run the same code in other machine, it performs well, thanks a lot!
