### ISSUE TITLE
Fitness in individual generation

### ISSUE THREAD

**Issue by Shawn-gitman** [ultralytics/yolov5#4939]
I struggle to find each fitness regarding individual generation in train.py during hyperparameter evolution. I figured that it automatically sorts all the results based on evolve.txt. How can I find the exact figure of the fitness in each generation?

**Comment by glenn-jocher** [comment]
@Shawn-gitman sorry I don't understand your question, but in general:

- results.csv logs per-epoch results
- evolve.csv logs per-generation results

**Comment by Shawn-gitman** [comment]
![Figure_1](https://user-images.githubusercontent.com/57627494/135018679-a357d1ff-f4d3-478c-8d5e-63bc7ec9800a.png)
I am in a progress to make a fitness graph like the image above. Finally, I found the solution by fixing your code. 

![image](https://user-images.githubusercontent.com/57627494/135019122-f9e4df82-0ca8-4a20-ae07-b1830f5efa08.png)

Thank you for your response!
