### ISSUE TITLE
How to run model on a constantly updating image folder?

### ISSUE THREAD

**Issue by mcybulskirv** [ultralytics/yolov5#4941]
## ❔Question
Just wondering if it is possible to continuously run my yolov5 model over a folder that constantly has its contents changing? i.e. the folder starts off with 1 image and has a new image automatically added every second, can the model just automatically and continuously run over the folder as each new image is added?

**Comment by glenn-jocher** [comment]
@mcybulskirv for custom workflows you can drop a YOLOv5 PyTorch Hub model into really any custom python code. See PyTorch Hub Tutorial to get started.

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by mcybulskirv** [comment]
> @mcybulskirv for custom workflows you can drop a YOLOv5 PyTorch Hub model into really any custom python code. See PyTorch Hub Tutorial to get started.
> 
> ## YOLOv5 Tutorials
> * [Train Custom Data](https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data)  🚀 RECOMMENDED
> * [Tips for Best Training Results](https://github.com/ultralytics/yolov5/wiki/Tips-for-Best-Training-Results)  ☘️ RECOMMENDED
> * [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)  🌟 NEW
> * [Supervisely Ecosystem](https://github.com/ultralytics/yolov5/issues/2518)  🌟 NEW
> * [Multi-GPU Training](https://github.com/ultralytics/yolov5/issues/475)
> * [PyTorch Hub](https://github.com/ultralytics/yolov5/issues/36)  ⭐ NEW
> * [TorchScript, ONNX, CoreML Export](https://github.com/ultralytics/yolov5/issues/251) 🚀
> * [Test-Time Augmentation (TTA)](https://github.com/ultralytics/yolov5/issues/303)
> * [Model Ensembling](https://github.com/ultralytics/yolov5/issues/318)
> * [Model Pruning/Sparsity](https://github.com/ultralytics/yolov5/issues/304)
> * [Hyperparameter Evolution](https://github.com/ultralytics/yolov5/issues/607)
> * [Transfer Learning with Frozen Layers](https://github.com/ultralytics/yolov5/issues/1314)  ⭐ NEW
> * [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by mcybulskirv** [comment]
@glenn-jocher thanks glenn, just for some insight - would I be able to change the images directory for detection to have /* in the path and would that then have the model constantly run until it is stopped? I essentially want the model to run over a folder continuously until it is manually stopped, and while it is running if new images are added to the directory it will process them.

**Comment by glenn-jocher** [comment]
@mcybulskirv you can implement anything you want, but the implementation effort is up to you as this is not a common use case.
