### ISSUE TITLE
torch.distributed.launch

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#4944]
## ❔Question
python -m torch.distributed.launch --nproc_per_node 2 train.py

How to let torch.distributed.launch and nproc_per_node as parameter in .py?

For example,
parser.add_argument('-m', default='torch.distributed.launch')
parser.add_argument('--nproc_per_node', default='4')

**Comment by glenn-jocher** [comment]
@alicera I don't think this is possible from within the same file, as the file itself is run once for each rank. You might create a separate python file to catch and parse these arguments and run training commands in os.system() calls.

**Comment by alicera** [comment]
Thks
