### ISSUE TITLE
Adding a new head to the model

### ISSUE THREAD

**Issue by ahong007007** [ultralytics/yolov5#4945]
## ❔Question
for example , #2001(https://github.com/ultralytics/yolov5/issues/2001)

It replaces one classification branch instead of adding one branch. How does yolov5 add multiple branches, such as multiple different detection heads, corresponding to different data sets and different task?

Thank you very much.

**Comment by glenn-jocher** [comment]
@ahong007007 losses are summed between components and heads in YOLOv5:
https://github.com/ultralytics/yolov5/blob/c5ba2abb4afb9fe8c671f14eb5200647893efe30/utils/loss.py#L91-L167

**Comment by abhigoku10** [comment]
@glenn-jocher  if I wanted to add an additional head that performs attribute recognition ie multilabel classification for only person class would it be advisable to add jus the additional head on to it FYI,, will be training only person class for bounding box detection and 11 attributes for each person manually annotated for each box in training data
