### ISSUE TITLE
AssertionError: [34m[1mtrain: [0mNo labels in data\train.cache. Can not train without labels. See https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data

### ISSUE THREAD

**Issue by yyh18434762774** [ultralytics/yolov5#4946]

**Comment by glenn-jocher** [comment]
@yyh18434762774 your data has no labels, so there is nothing to train on. See **Train Custom Data** tutorial for steps to correctly create a dataset:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by yyh18434762774** [comment]
Hello, I recently ran into a problem with data set, as follows：
[34m[1mtrain: [0mweights=yolov5s.pt, cfg=, data=data/defect.yaml, hyp=data/hyps/hyp.scratch.yaml, epochs=300, batch_size=1, img_size=[640, 640], rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, evolve=None, bucket=, cache_images=False, image_weights=False, device=, multi_scale=False, single_cls=False, adam=False, sync_bn=False, workers=8, project=runs/train, entity=None, name=exp, exist_ok=False, quad=False, linear_lr=False, label_smoothing=0.0, upload_dataset=False, bbox_interval=-1, save_period=-1, artifact_alias=latest, local_rank=-1
[34m[1mgithub: [0mskipping check (not a git repository), for updates see https://github.com/ultralytics/yolov5
YOLOv5  2021-7-17 torch 1.7.1+cu110 CUDA:0 (NVIDIA GeForce GTX 1050 Ti, 4096.0MB)

[34m[1mhyperparameters: [0mlr0=0.01, lrf=0.2, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0
[34m[1mtensorboard: [0mStart with 'tensorboard --logdir runs/train', view at http://localhost:6006/
[34m[1mwandb: [0mInstall Weights & Biases for YOLOv5 logging with 'pip install wandb' (recommended)
Overriding model.yaml nc=80 with nc=1

                 from  n    params  module                                  arguments                     
  0                -1  1      3520  models.common.Focus                     [3, 32, 3]                    
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]                
  2                -1  1     18816  models.common.C3                        [64, 64, 1]                   
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]               
  4                -1  1    156928  models.common.C3                        [128, 128, 3]                 
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]              
  6                -1  1    625152  models.common.C3                        [256, 256, 3]                 
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]              
  8                -1  1    656896  models.common.SPP                       [512, 512, [5, 9, 13]]        
  9                -1  1   1182720  models.common.C3                        [512, 512, 1, False]          
 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]              
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 12           [-1, 6]  1         0  models.common.Concat                    [1]                           
 13                -1  1    361984  models.common.C3                        [512, 256, 1, False]          
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]              
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 16           [-1, 4]  1         0  models.common.Concat                    [1]                           
 17                -1  1     90880  models.common.C3                        [256, 128, 1, False]          
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]              
 19          [-1, 14]  1         0  models.common.Concat                    [1]                           
 20                -1  1    296448  models.common.C3                        [256, 256, 1, False]          
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]              
 22          [-1, 10]  1         0  models.common.Concat                    [1]                           
 23                -1  1   1182720  models.common.C3                        [512, 512, 1, False]          
 24      [17, 20, 23]  1     16182  models.yolo.Detect                      [1, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
Model Summary: 283 layers, 7063542 parameters, 7063542 gradients, 16.4 GFLOPs

Transferred 356/362 items from yolov5s.pt
Scaled weight_decay = 0.0005
Optimizer groups: 62 .bias, 62 conv.weight, 59 other

[34m[1mtrain: [0mScanning 'data\train' images and labels...:   0%|          | 0/7 [00:00<?, ?it/s]
[34m[1mtrain: [0mScanning 'data\train' images and labels...0 found, 0 missing, 0 empty, 1 corrupted:  14%|█▍        | 1/7 [00:02<00:14,  2.50s/it]
[34m[1mtrain: [0mScanning 'data\train' images and labels...0 found, 0 missing, 0 empty, 7 corrupted: 100%|██████████| 7/7 [00:02<00:00,  2.79it/s]
[34m[1mtrain: [0mWARNING: Ignoring corrupted image and/or label data\images\11.jpg: corrupted JPEG
[34m[1mtrain: [0mWARNING: Ignoring corrupted image and/or label data\images\12.jpg: corrupted JPEG
[34m[1mtrain: [0mWARNING: Ignoring corrupted image and/or label data\images\47.jpg: corrupted JPEG
[34m[1mtrain: [0mWARNING: Ignoring corrupted image and/or label data\images\49.jpg: corrupted JPEG
[34m[1mtrain: [0mWARNING: Ignoring corrupted image and/or label data\images\60.jpg: corrupted JPEG
[34m[1mtrain: [0mWARNING: Ignoring corrupted image and/or label data\images\62.jpg: corrupted JPEG
[34m[1mtrain: [0mWARNING: Ignoring corrupted image and/or label data\images\9.jpg: corrupted JPEG
[34m[1mtrain: [0mWARNING: No labels found in data\train.cache. See https://docs.ultralytics.com/yolov5/tutorials/train_custom_data
[34m[1mtrain: [0mNew cache created: data\train.cache
Traceback (most recent call last):
  File "d:\DPlearning\yolov5-master\yolov5-hui- 8.28-2biao-2fen - 副本\train.py", line 657, in <module>
    main(opt)
  File "d:\DPlearning\yolov5-master\yolov5-hui- 8.28-2biao-2fen - 副本\train.py", line 555, in main
    train(opt.hyp, opt, device)
  File "d:\DPlearning\yolov5-master\yolov5-hui- 8.28-2biao-2fen - 副本\train.py", line 221, in train
    dataloader, dataset = create_dataloader(train_path, imgsz, batch_size // WORLD_SIZE, gs, single_cls,
  File "d:\DPlearning\yolov5-master\yolov5-hui- 8.28-2biao-2fen - 副本\utils\datasets.py", line 96, in create_dataloader
    dataset = LoadImagesAndLabels(path, imgsz, batch_size,
  File "d:\DPlearning\yolov5-master\yolov5-hui- 8.28-2biao-2fen - 副本\utils\datasets.py", line 415, in __init__
    assert nf > 0 or not augment, f'{prefix}No labels in {cache_path}. Can not train without labels. See {help_url}'
AssertionError: [34m[1mtrain: [0mNo labels in data\train.cache. Can not train without labels. See https://docs.ultralytics.com/yolov5/tutorials/train_custom_data

[Done] exited with code=1 in 6.282 seconds


I checked my data set and it has labels and generates.txt files for labels.  I tried to change a batch of data, which could work, but this batch of data would report an error.  What is the cause of this problem?

**Comment by glenn-jocher** [comment]
@yyh18434762774 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
