### ISSUE TITLE
How to display the Chinese label on th detetion box?

### ISSUE THREAD

**Issue by HTRT** [ultralytics/yolov5#4947]

**Comment by glenn-jocher** [comment]
@HTRT Arial Unicode should be used, but we should do this automatically. I'll queue this as a TODO.

```python
/Users/glennjocher/PycharmProjects/yolov5/venv/bin/python /Users/glennjocher/PycharmProjects/yolov5/detect.py

Downloading https://ultralytics.com/assets/Arial.Unicode.ttf to /Users/glennjocher/Library/Application Support/Ultralytics/Arial.Unicode.ttf...

detect: weights=yolov5s.pt, source=data/images, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False
YOLOv5 🚀 v5.0-466-gc5ba2ab torch 1.9.1 CPU

Fusing layers... 
Model Summary: 224 layers, 7266973 parameters, 0 gradients
image 1/2 /Users/glennjocher/PycharmProjects/yolov5/data/images/bus.jpg: 640x480 4 欧洲和西班牙s, 1 bus, 1 fire hydrant, Done. (0.193s)
image 2/2 /Users/glennjocher/PycharmProjects/yolov5/data/images/zidane.jpg: 384x640 2 欧洲和西班牙s, 2 ties, Done. (0.152s)
Speed: 1.1ms pre-process, 172.8ms inference, 1.0ms NMS per image at shape (1, 3, 640, 640)
Results saved to runs/detect/exp3
```

![zidane](https://user-images.githubusercontent.com/26833433/134972474-328b65d5-2655-43ca-8788-afd95e175e35.jpg)

**Comment by glenn-jocher** [comment]
TODO: implement Arial Unicode automatically for Chinese characters.

**Comment by glenn-jocher** [comment]
@HTRT good news 😃! Your original issue may now be fixed ✅ in PR #4951. This PR enables plotting images with Chinese characters. Fonts are downloaded automatically, no action required on your part other than to update your code. You **do not** need to retrain any models.

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by lonngxiang** [comment]
how to let predict labels display other languages？

**Comment by glenn-jocher** [comment]
@lonngxiang You can display labels in other languages by setting the font for the annotation using Pillow (PIL). Try the following code to display Chinese labels:

```python
from PIL import Image, ImageDraw, ImageFont

# Open image
img = Image.open('path_to_image.jpg')

# Define the font (Arial Unicode MS supports many languages, including Chinese)
font = ImageFont.truetype("path_to_Arial_Unicode.ttf", 50)

# Draw label
draw = ImageDraw.Draw(img)
draw.text((10, 10), "你好", font=font)  # Draw Chinese label at position (10, 10)

# Save or display the annotated image
img.save('output.jpg')
img.show()
```

Be sure to replace 'path_to_image.jpg' and 'path_to_Arial_Unicode.ttf' with your file paths. 

More details on using fonts with PIL can be found in the [Pillow documentation](https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.ImageDraw.text).

Let us know if you encounter any issues or have further questions!
