### ISSUE TITLE
Comparing mAP across different resolutions

### ISSUE THREAD

**Issue by lleye** [ultralytics/yolov5#4949]
Quick question on comparing mAP across different image resolutions. Say a model trained and tested at 640 and another model is trained and tested at 1280, if we get similar mAPs for both, is the model trained at the higher resolution better? I'm asking because higher resolution means a stricter iou etc.

@glenn-jocher @NanoCode012 @ferdinandl007 what do you think?

**Comment by glenn-jocher** [comment]
@lleye yes in general training at higher resolution will improve results, up to a point. i.e. COCO results are better when trained at --img 1280 than at --img 640 as you can see from our README table.
