### ISSUE TITLE
Using YOLOV5 as face Detection phase

### ISSUE THREAD

**Issue by ModynAI** [ultralytics/yolov5#4950]
## ❔Question
Hi,

I'm going to use Yolo as face detector and another deep Learning algorithm for Emotion Recognition!
in traditional implementations i saw some guys uses openCV HaarCascade with ".XML" file for detecting Face and Putting Bounding Box around the face and then this detected face feed to the Emotion Recognizer system!

So could you please help me on how to replace Haar cascade with YOLOV5 ?

Thanks
Best regards

**Comment by ModynAI** [comment]
@glenn-jocher 
Can you please Help?

Thanks
Best regards

**Comment by glenn-jocher** [comment]
@ModynAI your question is not related to YOLOv5.

**Comment by ModynAI** [comment]
@glenn-jocher Thanks for quick replay.
can you please give me some references to tackle with this problem or some suggestions?

Thanks
Best regards
