### ISSUE TITLE
Can't run on pc with GPU but can on pc without

### ISSUE THREAD

**Issue by Squeemos** [ultralytics/yolov5#4965]
## 🐛 Bug

When running train.py on gpu there are no results for training (with either COCO dataset or custom data). When running on a different computer (one that doesn't use the gpu for training) it runs just fine, albeit slow.

## To Reproduce

- Using 1660Ti with newest drivers
- From cmd run : python train.py --img 640 --batch 3 --epochs 10 --data ./data/coco128.yaml --weights ./weights/yolov5x.pt
- It loads the model, checks the images and it looks fine
- Then it starts to start training on the data and shows nan for box/obj/cls

When I ran this on a different computer which only used the CPU it had no issues (exact same files).

## Expected behavior

It should be training the data and giving results but it doesn't
(It not working on computer with gpu)
![Problem](https://user-images.githubusercontent.com/56849503/135053986-c5f2f7e3-b6fa-4b72-b83f-754b7b5e4d4d.png)

(It working on computer without gpu)
<img width="1606" alt="Working" src="https://user-images.githubusercontent.com/56849503/135055928-fb0e1463-7d44-4ddc-8ab1-f1f8459ea3c0.png">

**Comment by glenn-jocher** [comment]
@Squeemos windows can be tricky. I would recommend using one of our verified environments below. If you want to stick with your hardware a Docker image might be the best route.
