### ISSUE TITLE
How can I make docker  for custom yolov5 train on my own dataset

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#4967]
## ❔Question
How can I make a docker or containerize my custom yolov5 train on my own dataset

**Comment by glenn-jocher** [comment]
@hammadyounas2008 Docker usage examples are shown in YOLOv5 Dockerfile:

https://github.com/ultralytics/yolov5/blob/0c93ec762aec91e4fd91762870f06e786abc9b10/Dockerfile#L28-L58

**Comment by ghost** [comment]
How to give it my own Custom model or dataset? i am new to docker
