### ISSUE TITLE
I want to add the torch.add() function to common.py, how should I write it

### ISSUE THREAD

**Issue by boundaryT** [ultralytics/yolov5#4987]
## ❔Question
I want to use torch.add() to stack features without increasing the number of channels, and I want to mimic the way concat is written in commom.py.
## Additional context
class add(nn.Module):
    
    def __init__(self,alpha=0.5):
        super().__init__()
        self.alpha=alpha
    def forward(self, x):
        return torch.add(x,)

**Comment by glenn-jocher** [comment]
@boundaryT you're probably looking for torch.sum()

**Comment by ppogg** [comment]
like this？
```
class ADD(nn.Module):
    # Concatenate a list of tensors along dimension
    def __init__(self, alpha=0.5):
        super(ADD, self).__init__()
        self.a = alpha

    def forward(self, x):
        return torch.add(x, self.a)

class C3(nn.Module):
    # CSP Bottleneck with 3 convolutions
    def __init__(self, c1, c2, n=1, shortcut=True, g=1, e=0.5):  # ch_in, ch_out, number, shortcut, groups, expansion
        super(Light_C3, self).__init__()
        # use ADD replace Concat
        c_ = int(c2 * e)  # hidden channels
        self.cv1 = Conv(c1, c_, 1, 1)
        self.cv2 = Conv(c1, c_, 1, 1)
        self.cv3 = Conv(c_, c2, 1)  # act=FReLU(c2)
        self.m = nn.Sequential(*[Bottleneck(c_, c_, shortcut, g, e=1.0) for _ in range(n)])

    def forward(self, x):
        return self.cv3(torch.add(self.m(self.cv1(x)), self.cv2(x)))
```

**Comment by glenn-jocher** [comment]
@ppogg you can add things together in python with a + sign:
```
b + c
```

**Comment by boundaryT** [comment]
> @boundaryT您可能正在寻找 torch.sum()

Here's what I want： 
>>> a = torch.randn(4)
>>> a
tensor([ 0.0202,  1.0985,  1.3506, -0.6056])
>>> torch.add(a, 20)
tensor([ 20.0202,  21.0985,  21.3506,  19.3944])  like this.

**Comment by boundaryT** [comment]
> 像这样？
> 
> ```
> class ADD(nn.Module):
>     # Concatenate a list of tensors along dimension
>     def __init__(self, alpha=0.5):
>         super(ADD, self).__init__()
>         self.a = alpha
> 
>     def forward(self, x):
>         return torch.add(x, self.a)
> 
> class C3(nn.Module):
>     # CSP Bottleneck with 3 convolutions
>     def __init__(self, c1, c2, n=1, shortcut=True, g=1, e=0.5):  # ch_in, ch_out, number, shortcut, groups, expansion
>         super(Light_C3, self).__init__()
>         # use ADD replace Concat
>         c_ = int(c2 * e)  # hidden channels
>         self.cv1 = Conv(c1, c_, 1, 1)
>         self.cv2 = Conv(c1, c_, 1, 1)
>         self.cv3 = Conv(c_, c2, 1)  # act=FReLU(c2)
>         self.m = nn.Sequential(*[Bottleneck(c_, c_, shortcut, g, e=1.0) for _ in range(n)])
> 
>     def forward(self, x):
>         return self.cv3(torch.add(self.m(self.cv1(x)), self.cv2(x)))
> ```

**Comment by glenn-jocher** [comment]
@boundaryT if you want to add 20 to something use the plus sign:
```
x + 20
```

**Comment by boundaryT** [comment]
![image](https://user-images.githubusercontent.com/42082398/135395403-99e6fea3-948e-42c3-9312-c85ff801f2ee.png)


In practice I want alpha to be a tensor，thank you

**Comment by glenn-jocher** [comment]
@boundaryT yes you can add two tensors together with a plus sign.
