### ISSUE TITLE
saves output images in different color

### ISSUE THREAD

**Issue by NarenZen** [ultralytics/yolov5#4988]
this block of code saves the images in different color: https://github.com/ultralytics/yolov5/blob/cd35a009ba964331abccd30f6fa0614224105d39/models/common.py#L368

Here is the output

![Color Difference](https://user-images.githubusercontent.com/78342459/135204638-c8e89852-ccb3-4c45-9714-74ed9e09ccb2.png)

**Comment by glenn-jocher** [comment]
@NarenZen your workflow is incorrect. See PyTorch Hub tutorial for correct workflow examples.

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by NarenZen** [comment]
@glenn-jocher Found the issue

while giving the input to the model., 
reading the image should be done by this way
`img = cv2.imread("6.png")[:,:,::-1]`


**Here is the source image:**
![6](https://user-images.githubusercontent.com/78342459/135215881-e2ed0d00-7cd6-4dde-b116-51beed8ef7fe.png)

When the input is the path., it comes out with correct color(yellow)., but when the input is in numpy array.,  the umbrella changes to blue color

**Here is code which takes input as image path:**

```
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, custom

# Images
img = "6.png"

# Inference
results = model(img)

# Results
results.save()
```

![6](https://user-images.githubusercontent.com/78342459/135215463-21d9484b-24ff-4522-9aa5-e3574f4dbca6.jpg)

**Here is code which takes input as numpy array:**

```
import torch
import cv2

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, custom

# Images
img = cv2.imread("6.png")

# Inference
results = model(img)

# Results
results.save()
```

![image0](https://user-images.githubusercontent.com/78342459/135215656-10756bff-d7d2-4317-b914-f8dc8fdeea1c.jpg)

Here is the fix:

```
import torch
import cv2

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, custom

# Images
img = cv2.imread("6.png")[:,:,::-1]

# Inference
results = model(img)

# Results
results.save()
```
![image0](https://user-images.githubusercontent.com/78342459/135217512-15406876-1347-4cc1-8bf0-592f2515d1ff.jpg)

**Comment by glenn-jocher** [comment]
@NarenZen like I said, your workflow is incorrect, and my previous comment points you to the tutorial that contains the correct workflow.
