### ISSUE TITLE
backbone

### ISSUE THREAD

**Issue by 123456789mojtaba** [ultralytics/yolov5#499]
Hi.
I couldn't find yolov5 backbones. can you show me ? and how to change them?

**Comment by NanoCode012** [comment]
https://github.com/ultralytics/yolov5/blob/4b5f4806bcd513b18171034c06364432ef2c19c2/models/yolov5s.yaml#L12-L25

I don't recommend changing it unless you know what you are doing.

**Comment by 123456789mojtaba** [comment]
why didn't you use mobilenet or resnet?

**Comment by Lornatang** [comment]
@123456789mojtaba  See https://github.com/Lornatang/YOLOv4-PyTorch/blob/master/configs/COCO-Detection/mobilenetv1.yaml

**Comment by twangnh** [comment]
@Lornatang Could you suggest how to modify for ResNet?

**Comment by Lornatang** [comment]
@twangnh I think you can refer to [https://github.com/Lornatang/YOLOv4-PyTorch/blob/master/configs/COCO-Detection/vgg16.yaml](https://github.com/Lornatang/YOLOv4-PyTorch/blob/master/configs/COCO-Detection/vgg16.yaml).
At the same time, some functions need to be added to realize ResNet-101.
