### ISSUE TITLE
iou became NaN because of division by zero

### ISSUE THREAD

**Issue by abhiagwl4262** [ultralytics/yolov5#4991]
@glenn-jocher  https://github.com/ultralytics/yolov5/blob/cd35a009ba964331abccd30f6fa0614224105d39/utils/metrics.py#L224

In some case minimum of h1 became zero, hence IOU became NAN. 

In one case, The minimum of wh value from this line is coming as 1e-15. 
https://github.com/ultralytics/yolov5/blob/cd35a009ba964331abccd30f6fa0614224105d39/utils/loss.py#L133

**Comment by glenn-jocher** [comment]
@abhiagwl4262 h1 never becomes zero:
https://github.com/ultralytics/yolov5/blob/cd35a009ba964331abccd30f6fa0614224105d39/utils/metrics.py#L208-L210

any bounded value is fine for pwh
