### ISSUE TITLE
Bug about incomplete output information of Ubuntu shell

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#4992]
@glenn-jocher 
When the train.py or val.py command is executed, due to the different size (width) of the Ubuntu shell, incomplete information appears in the output information, as follows:
When the shell width is greater than the output information width, the output information is complete, as shown in the figure:
![ksnip_20210929-150805](https://user-images.githubusercontent.com/41098760/135219885-dbe2c7d0-18be-4f10-adcb-f0ccbecbe2f7.png)

When the width of the shell is smaller than the width of the output information, the output information is incomplete, even if the shell width is stretched to the right, it will not be displayed completely, as shown in the figure:
![ksnip_20210929-150856](https://user-images.githubusercontent.com/41098760/135220188-3c757b38-3f02-419b-ae49-947ec1c35642.png)

**Comment by iceisfun** [comment]
This is probably a better issue for tqdm as train just uses tqdm to display the progress bar.

https://github.com/tqdm/tqdm

**Comment by glenn-jocher** [comment]
@Zengyf-CVer yes I think this is due to known tqdm issues and/or resizing the terminal window after training starts. Would be a good idea to post this to tqdm repo as mentioned above.

**Comment by Zengyf-CVer** [comment]
Okay, let me ask and wait for my good news.
