### ISSUE TITLE
Strange resolution when doing inference (768x1280) instead of 1280x720

### ISSUE THREAD

**Issue by opassos** [ultralytics/yolov5#4995]
When I do inference on a video of resolution 1280 x 720 using the call `--img 1280` I get prints saying the frames are of shape (768 x 1280). Apparently, the predictions are correct but I am not 100% sure. Is this working as intended? Thanks

**Comment by iceisfun** [comment]
opencv shapes are

h, w, d = img.shape

so you might expect something like 720, 1280, 3 for a 1280x720xRGB(3) image

**Comment by opassos** [comment]
Yeah, that is exactly what I would expect, but I am getting 768, 1280, 3 image instead! why did it change the vertical resolution?

**Comment by glenn-jocher** [comment]
@opassos YOLOv5 P5 and P6 models have stride constraints of 32 and 64 pixels, respectively. Input images are resized and letterboxed automatically to comply with these constraints and your requested --img-size.

**Comment by opassos** [comment]
I see! so, nothing to worry about. Thanks a lot for your response.
