### ISSUE TITLE
[h264 @ 0x********] no frame! error

### ISSUE THREAD

**Issue by 0105artem** [ultralytics/yolov5#4996]
Hi, I'm trying to use yolo on my mp4 video, but it has broken frames.  When I run the script,

python detect.py --source video.mp4

after few seconds this error occurs:

[h264 @ 0xbcc42a00] no frame!
[h264 @ 0xbcc42a00] no frame!
[h264 @ 0xbcc42a00] no frame!
[h264 @ 0xbcc44f40] no frame!
[h264 @ 0xbcc4a180] no frame!
[h264 @ 0xbcd5b940] no frame!
Results saved to runs/detect/exp1
Done. (0.095s)

No more information provided. 
I know this is ffmpeg error, but I don't know how to fix this. Is there any way to skip through those bad frames? If not, how can I fix this? Right now I'm using the latest ffmpeg version from its repository, same happens with ffmpeg version 3.4.2
Extra information about my video file:
   Stream #0:1[0x1](eng): Video: h264 (Main) (avc1 / 0x31637661), yuvj420p(pc, bt709, progressive), 1920x1080, 2394 kb/s, 25 fps, 25 tbr, 600 tbn (default)
   Metadata:
      creation_time   : 2021-06-01T08:56:23.000000Z
      handler_name    : ?Apple Video Media Handler
      vendor_id       : appl
      encoder         : H.264

Operating system: Ubuntu 20.04.3
torch==1.9.1+cu111

**Comment by glenn-jocher** [comment]
@0105artem the YOLOv5 streamloader automatically ignores problem frames in streaming sources by passing a black image:
https://github.com/ultralytics/yolov5/blob/76d301bd21b4de3b0f0d067211da07e6de74b2a0/utils/datasets.py#L323-L332

**Comment by neverstoplearn** [comment]
> Hi, I'm trying to use yolo on my mp4 video, but it has broken frames. When I run the script,
> 
> python detect.py --source video.mp4
> 
> after few seconds this error occurs:
> 
> [h264 @ 0xbcc42a00] no frame! [h264 @ 0xbcc42a00] no frame! [h264 @ 0xbcc42a00] no frame! [h264 @ 0xbcc44f40] no frame! [h264 @ 0xbcc4a180] no frame! [h264 @ 0xbcd5b940] no frame! Results saved to runs/detect/exp1 Done. (0.095s)
> 
> No more information provided. I know this is ffmpeg error, but I don't know how to fix this. Is there any way to skip through those bad frames? If not, how can I fix this? Right now I'm using the latest ffmpeg version from its repository, same happens with ffmpeg version 3.4.2 Extra information about my video file: Stream #0:1[0x1](eng): Video: h264 (Main) (avc1 / 0x31637661), yuvj420p(pc, bt709, progressive), 1920x1080, 2394 kb/s, 25 fps, 25 tbr, 600 tbn (default) Metadata: creation_time : 2021-06-01T08:56:23.000000Z handler_name : ?Apple Video Media Handler vendor_id : appl encoder : H.264
> 
> Operating system: Ubuntu 20.04.3 torch==1.9.1+cu111

I meet the same error,have you solve it?
