### ISSUE TITLE
W&B Multi-GPU system panels are confusing

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/yolov5#4999]
@AyushExel got some feedback here for the W&B team. Tracking system stats on multi-GPU machines is very messy currently. If I have an 8x GPU instance and train 1 model on it, it shows all 8 GPU stats. If I have two single-GPU runs visualized, 16 lines will show up in the plots and the legends, making it nearly impossible to decipher what we see. In my screenshot below, I only have two runs selected, and I just want to see CUDA usage each of those two GPUs:

https://wandb.ai/glenn-jocher/yolov5_v6
<img width="1621" alt="Screen Shot 2021-09-29 at 11 36 27 AM" src="https://user-images.githubusercontent.com/26833433/135328736-55264ae3-47a5-40b6-87bd-ef9e3ad9c833.png">

**Comment by AyushExel** [comment]
@glenn-jocher If you click on `edit panel` you can make various changes that enable better viewing experience for these clogged charts:
for example, you can smooth the charts, use log scale, remove the GPUs that you don't want to track and use area chart. All of these are just a click away. Do any of these look satisfactory for your case?
![Screenshot (49)](https://user-images.githubusercontent.com/15766192/135343309-19eb1bd2-0a96-48c1-846d-08127ed07590.png)
![Screenshot (50)](https://user-images.githubusercontent.com/15766192/135343315-03a286bf-56c4-46a7-8474-4cddf9a7dad4.png)
![Screenshot (51)](https://user-images.githubusercontent.com/15766192/135343317-6bb75b62-ae76-4a4e-8c38-3941a365c3b5.png)
![Screenshot (48)](https://user-images.githubusercontent.com/15766192/135343322-82266b55-09f6-48c5-89c2-a699f36e9f8d.png)

**Comment by glenn-jocher** [comment]
@AyushExel I'm not quite sure if these changes are what we want. The 3rd chart looks like what most users would want I think, but these two trainings are on different GPUs and the Y axis shows filtered by GPU 0 so I don't know if that's technically correct.

Fundamentally the issue is that we only want to show the GPUs used by a given run when it is selected. I think everyone would agree that this should be the default behavior rather than needing manual clicks to sort out on each plot.

**Comment by AyushExel** [comment]
@glenn-jocher I see. Thanks for the detailed write-up. I'll forward this to the product team.
