### ISSUE TITLE
Pretrain Weight 

### ISSUE THREAD

**Issue by hustfyb** [ultralytics/yolov5#5]
It seems the pretrain weight yolov5s.pt doesn't math yolov5s.yaml.
When train with
```python train.py --img 320 --batch 16 --epochs 100 --data coco128.yaml --cfg yolov5s.yaml --weights yolov5s.pt --name coco128  --cache```
It will report not compatible.
yolov5m.pt and yolov5l.pt are fine.

**Comment by glenn-jocher** [comment]
@hustfyb thank you for the bug report. Yes you are correct, we are able to reproduce this issue that you detected. This is due to many recent updates to the repo and the time gap between the current repo and the state it was in when the pretrained checkpoints were trained. We are in the process of training updated checkpoints with the most current repo, and they will be uploaded as soon as they become available (about 1-2 weeks from now). In the meantime you can train yolov5s from scratch (as we do for our COCO results).

**Comment by acai66** [comment]
> @hustfyb thank you for the bug report. Yes you are correct, we are able to reproduce this issue that you detected. This is due to many recent updates to the repo and the time gap between the current repo and the state it was in when the pretrained checkpoints were trained. We are in the process of training updated checkpoints with the most current repo, and they will be uploaded as soon as they become available (about 1-2 weeks from now). In the meantime you can train yolov5s from scratch (as we do for our COCO results).

thank you for graet works.
does the cfg content in `Train Custom Data` match pretrain weight, content:

```
# parameters
nc: 80  # number of classes   <------------------  UPDATE to match your dataset
depth_multiple: 0.33  # model depth multiple
width_multiple: 0.50  # layer channel multiple

# anchors
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

# yolov5 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Focus, [64, 3]],  # 1-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 2-P2/4
   [-1, 3, Bottleneck, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 4-P3/8
   [-1, 9, BottleneckCSP, [256, False]],
   [-1, 1, Conv, [512, 3, 2]],  # 6-P4/16
   [-1, 9, BottleneckCSP, [512, False]],
   [-1, 1, Conv, [1024, 3, 2]], # 8-P5/32
   [-1, 1, SPP, [1024, [5, 9, 13]]],
   [-1, 12, BottleneckCSP, [1024, False]],  # 10
  ]

# yolov5 head
head:
  [[-1, 1, nn.Conv2d, [na * (nc + 5), 1, 1, 0]],  # 12 (P5/32-large)

   [-2, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 1, Conv, [512, 1, 1]],
   [-1, 3, BottleneckCSP, [512, False]],
   [-1, 1, nn.Conv2d, [na * (nc + 5), 1, 1, 0]],  # 16 (P4/16-medium)

   [-2, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 1, Conv, [256, 1, 1]],
   [-1, 3, BottleneckCSP, [256, False]],
   [-1, 1, nn.Conv2d, [na * (nc + 5), 1, 1, 0]],  # 21 (P3/8-small)

   [[], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
  ]
```

**Comment by glenn-jocher** [comment]
@hustfyb @acai66 new models have been released which address both of these issues. See c14368d768749734e1a017ed8e750b33597e8746 and view readme table for updated results.
