### ISSUE TITLE
Can I convert this pytorch version to tensorflow ?? Will the tensorflow version run with the same speed of training or inference??

### ISSUE THREAD

**Issue by dorecasan** [ultralytics/yolov5#50]

**Comment by glenn-jocher** [comment]
@dorecasan yes, I believe it should be possible to recreate similar training and inference results in TF.

**Comment by faldisulistiawan** [comment]
@dorecasan Hello, have you been able to convert Yolov5 Pytorch to Tensorflow? If yes, can you please give me the tutorial for it? Thank you

**Comment by glenn-jocher** [comment]
@faldisulistiawan @dorecasan yes YOLOv5 is convertible to TF2 and exportable to TFLite. See https://github.com/ultralytics/yolov5/pull/1127

**Comment by faldisulistiawan** [comment]
@glenn-jocher Thank you so much for the info! I needed the TF for future production needs, since productionizing TF models is easier. Although, #1127 can only be used as the inference / prediction right? I still need to train the yolov5 in the pytorch framework?

**Comment by zldrobit** [comment]
@faldisulistiawan Yes, you still have to train in PyTorch framework.
https://github.com/ultralytics/yolov5/pull/1127 is only for exporting trained models.

**Comment by faldisulistiawan** [comment]
@zldrobit Thanks!
