### ISSUE TITLE
Instance Segementation support for Yolov5

### ISSUE THREAD

**Issue by Darshvino** [ultralytics/yolov5#5001]
Hi Yolov5 team,

Does this repo support Instance Segmentation for YoloV5? 
If yes, then what is the preferred annotation used for the same.

The reason being: I have a Dataset consisting of 8Million images and I have a separate annotation file for each image which is in JSON format.
The sample JSON is available at this link: https://drive.google.com/file/d/12lASRiHGm5fhbHP5YNCaQM-SwfvnGIcR/view?usp=sharing. This is for only one image, similarly, we have it for all the images.
But the issue with using the Coco format(single format file for all the images) is that: The single JSON file for 8Million images is becoming very big and it eats up the memory.

Having said that, I have trained the YoloV5 medium on 8Million images already for Detection using Yolo txt format. For next phase, I want to train for the Instance Segmentation.

Looking forward to your reply.

Best Regards,
Darshan C G

**Comment by glenn-jocher** [comment]
@Darshvino YOLOv5 accepts segmentation labels in YOLO format, though this only helps improve augmentation policy and is not a full segmentation training with appropriate loss function, model architecture changes, plotting changes etc. This is on our long-term TODO list but is not scheduled for release until later next year. You can see YOLO box (default) vs YOLO segmentation labels in COCO128:
https://github.com/ultralytics/yolov5/releases/download/v1.0/coco128-segments.zip
https://github.com/ultralytics/yolov5/releases/download/v1.0/coco128.zip

**Comment by glenn-jocher** [comment]
@MKD-026 yes:

```
python segment/predict.py --save-txt
```
