### ISSUE TITLE
No "augment" argument

### ISSUE THREAD

**Issue by zapulam** [ultralytics/yolov5#5002]
Hello! I have a quick question regarding the augmentations within yolov5.

Background: I am attempting to train on a dataset which contains small bboxes and am having to use full image sizes to achieve good results. I would like to use an Albumentations cropping function to crop images and keep bboxes to decrease memory usage.

Question: There does not seem to be an "augment" flag in train.py, however, in the trainloader, augment is set to true. Does this mean that whatever augmentations are listed in utils/augmentations.py are automatically applied? And I simply need to add the augmentations of my choice there?

PS: Would it be useful to add an "augment" flag in train.py if there was reason to turn off augmentations?

**Comment by glenn-jocher** [comment]
@zapu222 augmentations are adjusted individually in your hyperparameter file and using any Albumentations you decide to add in augmentations.py.
https://github.com/ultralytics/yolov5/blob/42354d70252be81dedf0b889eaf5f4b071eb7694/data/hyps/hyp.scratch.yaml#L22-L34

**Comment by zapulam** [comment]
Great! Thank you!
