### ISSUE TITLE
COCO

### ISSUE THREAD

**Issue by whut-dg** [ultralytics/yolov5#5003]
Using the get_coco.sh file, the  the number of training images and the number of labels obtained are inconsistent.

**Comment by glenn-jocher** [comment]
@whut-dg not every image has labels in COCO.

**Comment by whut-dg** [comment]
thank you!



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Glenn ***@***.***&gt;; 
发送时间: 2021年9月30日(星期四) 上午9:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ultralytics/yolov5] COCO (#5003)





 
@whut-dg not every image has labels in COCO.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
