### ISSUE TITLE
detect.py and val.py

### ISSUE THREAD

**Issue by karl-gardner** [ultralytics/yolov5#5004]
2 questions:

The yolov5m.yaml file in yolov5/models is the file for the medium yolov5m model.  To run this model do I put this directory in the --cfg argument in the train.py file and if so should I change anything in the file since I only have 4 classes?

After training the yolov5m model through changing the nc variable in the yolov5m.yaml file to 4 classes instead of 80 I have trained the model with 500 epochs.  However there is no --cfg argument in the detect.py and val.py files.  I am wondering does it automatically know that the model is the medium one and there are 4 classes?

![image](https://user-images.githubusercontent.com/91646805/135379858-c1847fe5-c231-4066-862e-7799fce2b846.png)

Thanks, 

Karl Gardner | Texas Tech University

**Comment by glenn-jocher** [comment]
@kgardner330 for training custom data see Train Custom Data tutorial below. Yes detect.py accepts a --weight argument.

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by karl-gardner** [comment]
Hello Glenn,

I appreciate the help.  So the detect.py function will automatically know which model it was trained on (weather it is yolov5s, yolov5m, yolov5l, yolov5x) based on the --weight argument?

Karl Gardner | Texas Tech University

**Comment by glenn-jocher** [comment]
@kgardner330 yes

**Comment by karl-gardner** [comment]
Great! 

Thanks for the help Glenn.

Karl Gardner

**Comment by kgardner330** [comment]
Thanks for all the good work with this object detection model with very fast inference time!
