### ISSUE TITLE
About the execution position of plot_results

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#5008]
@glenn-jocher 
When the train.py file is run, results.png will be generated. I found the function to generate this picture: `plot_results`
https://github.com/ultralytics/yolov5/blob/ba99092304a2ee715b6fb954b437b2d081203794/utils/plots.py#L397-L420

#### But I did not find the code to call this function in train.py
I searched all the files in the YOLOv5 project, but I didn’t find that place and called the plot_results function.

**Comment by glenn-jocher** [comment]
@Zengyf-CVer https://github.com/ultralytics/yolov5/blob/ba99092304a2ee715b6fb954b437b2d081203794/train.py#L424
