### ISSUE TITLE
How to evaluate mAP of tensorrt yolov5 custom trained model? Is there a code available for this?

### ISSUE THREAD

**Issue by nralka2007** [ultralytics/yolov5#5009]
I have converted  a custom trained yolov5 model to tensorrt. I need to understand the ,mAP of the model. Is there an API already available for this that would work with TRT with this yolov5_trt.py[https://github.com/adujardin/tensorrtx/blob/yolov5-coco-eval/yolov5/yolov5_trt.py](url) inference code?

**Comment by glenn-jocher** [comment]
@nralka2007 your link is broken

**Comment by nralka2007** [comment]
The link is here:
https://github.com/wang-xinyu/tensorrtx/blob/master/yolov5/yolov5_trt.py
I am using the above code for inference on jetson nano with the tensorrt model (a custom trained yolov5 model converted to tensorrt). Just wanted to know if there is a code available for calculating mAP with this tensorrt model on jetson nano @glenn-jocher

**Comment by glenn-jocher** [comment]
@nralka2007 do you mean on the COCO dataset? No there's no off-the-shelf capability for this. You'd have to modify the inference area of val.py to add TRT-inference code:
https://github.com/ultralytics/yolov5/blob/89a6e9ffa78a43c17c5405caa144e514b4afd0ef/val.py#L172-L186

**Comment by jaskiratsingh2000** [comment]
@nralka2007 Were you able to do this?

**Comment by nralka2007** [comment]
@jaskiratsingh2000 , I did not try modifiying the validation script. I saved the results in a text file and then used a validation module to benchmark
