### ISSUE TITLE
YoloV5 for Classification

### ISSUE THREAD

**Issue by matpy1** [ultralytics/yolov5#5010]
Hello,

I would like to ask if it is possible to feed YoloV5 only a certain region (e.g. ground truths) of an image? 
I have images containing traffic lights (I also have the bounding boxes coordinates) and I would like to use YoloV5 to classify the traffic lights. I don't want Yolo to have to detect the traffic lights first, but rather only look at the ground truths that I already have. Is that possible or is the only way to crop the images and then feed the cropped images to YoloV5?
(I pretrained the network already so that it can classify red, green and yellow traffic lights)
Thank you a lot!

**Comment by glenn-jocher** [comment]
@matpy1 see classifier.py in classifier branch:
https://github.com/ultralytics/yolov5/tree/classifier
