### ISSUE TITLE
Maximum one object per class detection

### ISSUE THREAD

**Issue by lleye** [ultralytics/yolov5#5013]
## ❔Question
Any idea on how we can modify detect.py or test.py to only detect one item per class in one image e.g. person a cannot appear twice in one image?

## Additional context
for example only/max one ball and or one apple per image.

@glenn-jocher

**Comment by glenn-jocher** [comment]
@lleye NMS settings are here, you can set `max_det` per image:
https://github.com/ultralytics/yolov5/blob/89a6e9ffa78a43c17c5405caa144e514b4afd0ef/utils/general.py#L606-L628
