### ISSUE TITLE
Inference on Low Resolution Image for Yolov5 meduim

### ISSUE THREAD

**Issue by Darshvino** [ultralytics/yolov5#5018]
Hi Yolov5 team,

Thanks very much for your amazing work.

My question here is: I have trained the Yolov5 Medium model using the custom Dataset on 640x640 resolution. But I want to do the Inference on 416x416 or 400x400 resolution Input image. 
What is the way to do that? The main reason is I want to speed up the inference on Edge Devices. I have tried converting to TensorRT and run on Jetson Nano, and the inference time is around 210 ms per image. But I really need to bring that time below 100ms.

How do I do the Inference on 416x416 or 400 resolution? Do I need to retrain it? Or do we have any other way?

Looking forward to your reply.

Thanks and Regards,

**Comment by glenn-jocher** [comment]
@Darshvino YOLOv5 models can run inference on images sized from their minimum stride (32 pixels for P5 models) all the way up to (but not beyond) the `--img-size` they were trained at.

So if you trained YOLOv5m at 640 you can run inference from 32-640 pixels, and if you train YOLOv5m6 models at --img 1280 you can use them from 64-1280 pixels.

Our iDetection app deploys at --img 320 but uses the four official P5 models that were trained at --img 640.

**Comment by Darshvino** [comment]
Hi @glenn-jocher,

Thank you very much for your support and quick response as always.

I have tested the Inference on a 400x400 resolution input image, but the results are not the same. I am attaching the results of both 640x640 and 400x400 inference below.

640 x 640 Inference Image Output:

https://drive.google.com/file/d/1gG2A5ogelRSogAGMYHLN1dk3OkBwL4yN/view?usp=sharing

400x400 Inference Image Output:

https://drive.google.com/file/d/1dlLd8ao3cUu53XKqp2h8dPJkhS9pwRcJ/view?usp=sharing

We are getting the false-positive results in the 400x400 Inference. What exactly is the issue here? Do we have to change any parameters? 

Can you please help me to resolve this? Would be a great help from your side.

But the time taken for Inference is reduced almost by half for 400x400 Inference with TensorRT.

Looking forward to your reply.

Thanks and Regards

**Comment by glenn-jocher** [comment]
@Darshvino yes different resolutions will produce different results. In general at smaller image sizes your results will worsen and your speed will increase. This is what is shown in our README table as we evaluate YOLOv5 models over a range of image sizes:

<p align="center"><img width="800" src="https://user-images.githubusercontent.com/26833433/114313216-f0a5e100-9af5-11eb-8445-c682b60da2e3.png"></p>
<details>
  <summary>YOLOv5-P5 640 Figure (click to expand)</summary>

<p align="center"><img width="800" src="https://user-images.githubusercontent.com/26833433/114313219-f1d70e00-9af5-11eb-9973-52b1f98d321a.png"></p>
</details>
<details>
  <summary>Figure Notes (click to expand)</summary>

* GPU Speed measures end-to-end time per image averaged over 5000 COCO val2017 images using a V100 GPU with batch size
  32, and includes image preprocessing, PyTorch FP16 inference, postprocessing and NMS.
* EfficientDet data from [google/automl](https://github.com/google/automl) at batch size 8.
* **Reproduce** by
  `python val.py --task study --data coco.yaml --iou 0.7 --weights yolov5s6.pt yolov5m6.pt yolov5l6.pt yolov5x6.pt`

</details>
