### ISSUE TITLE
A bug about save-json

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#5019]
@glenn-jocher 
When I run the `val.py` file and execute the `--save-json` command (custom data set), a line like this appears in the shell:
![ksnip_20211001-140922](https://user-images.githubusercontent.com/41098760/135573656-09dec53f-e1b4-4b3a-b1c8-5725bf4a2a1c.png)

Will this error message affect it? How to eliminate it?

**Comment by glenn-jocher** [comment]
@Zengyf-CVer yes I see this line. It's looking for a 'path' field in your yaml, it's expecting to find a JSON annotations file in pycocotools format to compute pycocotools mAP. It will still save your prediction.json file though before this error happens, you should see it in your runs/train/exp directory:
https://github.com/ultralytics/yolov5/blob/cce7e78faed801377ccbdb04ebfd8cc45ad28ed9/val.py#L265-L270

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
If I use a custom data set, do I need to regenerate this instances_val2017.json manually?

**Comment by glenn-jocher** [comment]
@Zengyf-CVer yes right now you need to provide an annotations json. pycocotools needs two jsons to compare, annotations and predictions, val.py creates predictions.json from your model's predictions.

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
In other words, I need to convert the current txt file (ground truth) in yolo format into json in coco format, and then compare and calculate with the predicts.json generated by the program to obtain mAP, is that right?

**Comment by glenn-jocher** [comment]
@Zengyf-CVer yes.

It might be easier to update val.py to create the annotations json at the same time as the predictions json when --save-json is used. This would allow for pycocotools maps of any custom dataset then. If you go this route please submit a PR to help other users in the future, thanks!

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
Thank you very much for your reply.
