### ISSUE TITLE
Saved Model Position

### ISSUE THREAD

**Issue by buimanhlinh96** [ultralytics/yolov5#502]
First, thanks for your contribution for AI community. I have a question that where is model saved? I trained yolov5 i only receive the runs file which doesnt contain any saved model. Also, nothing in weights file. Can you explain for me? Thanks in advance!

**Comment by NanoCode012** [comment]
It should located in `runs/exp#/weights` for latest version. Did you run with `--nosave` and stopped mid-way?

**Comment by glenn-jocher** [comment]
Yes, see example in notebook!

**Comment by buimanhlinh96** [comment]
@NanoCode012 Yes i run with --nosave flag but there is nothing in runs/exp#/weights @@

**Comment by glenn-jocher** [comment]
@buimanhlinh96 ha. If you run with —nosave then no weights are saved except for the last epoch, so your observed results are expected.

**Comment by buimanhlinh96** [comment]
@glenn-jocher Thank you
