### ISSUE TITLE
After convert tflite, Class name

### ISSUE THREAD

**Issue by Ronald-Kray** [ultralytics/yolov5#5022]
## ❔Question
@glenn-jocher 
After convert tflite, Class name has changed.
How can I fix the class name?

## Additional contex
![mozhno-li-uteplit-dom-s-pomoshchyu-montazhnoj-peny-26](https://user-images.githubusercontent.com/76469976/135652113-5213f575-35c3-4647-bfc4-68109466d216.jpg)
t

**Comment by glenn-jocher** [comment]
@Ronald-Kray tflite models do not contain names the way pytorch models do, but you can specify a names array here during inference:
https://github.com/ultralytics/yolov5/blob/cce7e78faed801377ccbdb04ebfd8cc45ad28ed9/detect.py#L78
