### ISSUE TITLE
How to really use exported Tensorflow Lite model?

### ISSUE THREAD

**Issue by pyro000** [ultralytics/yolov5#5030]
## ❔Question

Following this tutorial: https://towardsdatascience.com/using-tensorflow-lite-for-object-detection-2a0283f94aed

I get with `interpreter.get_tensor(output_details[1]['index'])[0]` Index Error, because this model doesn't have labels or classes inside it.

Trying to understand `detect.py` and `general.py` seems really dificult for me.
Is there any introduction of how to display results with this model and include the labels from yolov5 with Python? or what source do I have to use to make this?

## Additional context

Using `detect.py` works as intended but instead of naming the objects, it appears as "class0", "class20"...

**Comment by pyro000** [comment]
I have [this colab notebook](https://colab.research.google.com/drive/1CgI_EOJK_Lq9IZc2Fibaiz1HpATKALig?usp=sharing) to show what I've done by now, if anybody can help me or link me anything useful I would be very grateful.

**Comment by glenn-jocher** [comment]
@pyro000 exported YOLOv5 models do not contain `names` arrays, only PyTorch models do. You can manually specify a `names` array in detect.py to replace the default `names = ['class0', 'class1', ...]`:
https://github.com/ultralytics/yolov5/blob/cce7e78faed801377ccbdb04ebfd8cc45ad28ed9/detect.py#L78

@zldrobit this issue seems to come up often, users are understandably confused when detection names are not shown with TFLite detect.py inference. Is there any way to embed names arrays in a TFLite model?

EDIT: @zldrobit I know previously you defaulted to COCO names, but users will arrive here with custom-trained models also.

**Comment by pyro000** [comment]
The problem is that with the [example](https://colab.research.google.com/drive/1PnXtXC2rjbY-2iSFeeqm8lbVyA4L0I_z?usp=sharing) provided by the tutorial and the labels that I defined manually in `labelmap.txt` I keep getting the error `IndexError: list index out of range` in `output_details[1]` and above, when it is supposed to exist in the `yolov5.tflite` model.

Or am I missing something? Any help is really appreciated.

**Comment by glenn-jocher** [comment]
@pyro000 your link goes to a 3rd party that I don't recognize. The official YOLOv5 colab is
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

Running inference with TFLite models is very easy:
```
python export.py --weights yolov5s.pt --include tflite
python detect.py --weights yolov5s-fp16.tflite
```

**Comment by pyro000** [comment]
That's the code I did to make the predictions of the model in Python, loading the model with `tf.lite.Interpreter`, what I'm trying is to use a custom model made by yolov5, export it as tflite then use it with Tensorflow object detection API.

> @pyro000 your link goes to a 3rd party that I don't recognize. The official YOLOv5 colab is https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb
> 
> Running inference with TFLite models is very easy:
> 
> ```
> python export.py --weights yolov5s.pt --include tflite
> python detect.py --weights yolov5s-fp16.tflite
> ```

Yes I'm aware that with detect.py works perfectly but how do I make my own code only for tflite model? The methods in the TF docs doesn't work.

**Comment by glenn-jocher** [comment]
@pyro000 oh I see. I don't have experience with the TF OD API, I'm sorry. You should try reposting this issue on the https://github.com/tensorflow/models repository to see if you can get help there.

**Comment by pyro000** [comment]
Yes I just realised this is TF issue, I'll close this.

**Comment by zldrobit** [comment]
@glenn-jocher We may embed metadata in TFLite, e.g. https://www.tensorflow.org/lite/convert/metadata_writer_tutorial#object_detectors for object detection model. But this requires the TFLite model integrate with the NMS op. Considering [the support of NMS in TFLite/TF.js](https://github.com/ultralytics/yolov5/discussions/2095#discussioncomment-326401), not all use cases could be covered by any type of the NMS ops. So I suggest we keep the NMS op in TFLite as an experimental branch for now.

**Comment by zldrobit** [comment]
@pyro000 After exported the TFLite model, you could use [my fork repo](https://github.com/zldrobit/yolov5) to run the model on Android devices.

**Comment by glenn-jocher** [comment]
@zldrobit got it, thanks! Will leave this alone for now then.

**Comment by EdjeElectronics** [comment]
An example of how to use a yolov5.tflite model inside a TFLite application (besides just using `detect.py`) would be super useful. I'm also confused trying to figure how to deploy my TFLite model in my own application.

**Comment by glenn-jocher** [comment]
@EdjeElectronics We plan to release an example for using yolov5.tflite in a TFLite app soon. In the meantime, I recommend referring to the TFLite image classification example on the TensorFlow website as a starting point for TFLite deployment.
