### ISSUE TITLE
Plot ground truth annotations for one image

### ISSUE THREAD

**Issue by karl-gardner** [ultralytics/yolov5#5033]
Hello Glenn et al,

I am trying to plot the ground truth annotations for just one image in my test set.  Would I do that by importing the Annotator class, then instantiating the Annotator class with one of my images as the images is the first argument in the Annotator constructor, then I can pass the ground truth .txt file (same format for training) into the plot_labels method in the Annotator object?  Am I on the right track for this as I am not an expert programmer but am trying to read more everyday.

Thanks,

Karl Gardner | Texas Tech University

**Comment by glenn-jocher** [comment]
@kgardner330 sure, you can reproduce what detect.py does by creating an `Annotator(im)` instance and then passing `annotator.box_label(xyxy, label)`.

**Comment by karl-gardner** [comment]
Hello Glenn,

So it seems like I have to provide the box as a list of [x,y,x,y] for each box and then make a for loop to put the annotator.box_label(xyxy,label) method in right?

Karl Gardner

**Comment by glenn-jocher** [comment]
@kgardner330 yes. box_label() plots 1 box, for multiple boxes use a `for` loop like detet.py.

**Comment by karl-gardner** [comment]
Hello again,

Ok I can do this but right now, my labels are actually already in yolo format since I used roboflow for example:
0 0.8720703125 0.0224609375 0.060546875 0.044921875

Since the box_label function accepts the two corner points as [x,y,x,y] then I would have to do the following:
[round(0.8720703125 * width - 0.060546875 * width / 2), round(0.0224609375 * height - 0.04492187 * height / 2), round(0.8720703125 * width + 0.060546875 * width / 2), round(0.0224609375 * height + 0.04492187 * height /2)]

My width and height are 512 and 512. Would this be correct with the rounding and subtraction and addition?

Thanks,

Karl Gardner | Texas Tech University

**Comment by glenn-jocher** [comment]
@kgardner330 see general.py for transforms.

https://github.com/ultralytics/yolov5/blob/b0ade48457fb8b1fc1acd9e1a34bb50e6b7205da/utils/general.py#L512-L520
