### ISSUE TITLE
About the Map

### ISSUE THREAD

**Issue by southeastboss** [ultralytics/yolov5#5041]
## Additional context
I have find in the val.py there have the Map@0.5 to evaluate the model.
If I want to change the IOU threshold like Map@0.3.
How can I change in the code.
I am confusing in change Map@0.5 to Map@0.3.

**Comment by glenn-jocher** [comment]
@southeastboss the IoU vector variable `iouv` in val.py defines the thresholds used for mAP computation. You can modify this vector to your custom requirements. The first value and the full vector are used to compute the two mAPs displayed.
https://github.com/ultralytics/yolov5/blob/1922ddeac0294a91d585020bbb7290b8e353d813/val.py#L143

**Comment by southeastboss** [comment]
Oh, I only focus on the function ap_per_class( ) and compute_ap( ) in the metrics.py before. Thanks for your guidance.

**Comment by glenn-jocher** [comment]
@southeastboss no problem! Note that the screen labels will still say 'mAP@.5' since they are hardcoded here, but the result will be evaluated at the IoU you specify for `iouv[0]`.
https://github.com/ultralytics/yolov5/blob/5afc9c25ef0874dff0c18267947ea4e8b03c90f4/val.py#L158

**Comment by southeastboss** [comment]
OK, I will continue to check the code about the mAP@.5
