### ISSUE TITLE
How to determine which version I cloned

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#5044]
A couple of months ago I cloned Yolov5 and modified it to my project's needs. 
I git pushed it to my own personal repository so it is separate from the official one. 
Now I need to run this on another PC but I can't clone it because of all the dependencies aren't included etc and after some months Yolov5 has been updated.
How do I figure out which version I was using so I can clone that instead on the other PC?

**Comment by jiujiangluck** [comment]
Following links for you to refer to:

references:
https://stackoverflow.com/questions/14872486/retrieve-specific-commit-from-a-remote-git-repository
https://stackoverflow.com/questions/14370157/git-fetch-a-specific-commit-by-hash
https://stackoverflow.com/questions/3489173/how-to-clone-git-repository-with-specific-revision-changeset
