### ISSUE TITLE
Periodical Weight Save

### ISSUE THREAD

**Issue by aseprohman** [ultralytics/yolov5#5045]
## Additional context
Hello @glenn-jocher

How to save weights in periodical epoch step ? for example  I have train my dataset for 200 epoch and I want to save my weights every 50 epoch ?  
I've try to train data with yolov4 alexeyab and he have methode for save weight in periodical batch dataset.
I hope it will possible too in your training framework

**Comment by glenn-jocher** [comment]
@aseprohman good news 😃! Your feature suggestion should now be implemented ✅ in PR #5047. This PR implements a `--save-period` argument to allow for periodic checkpointing during training, i.e. `python train.py --save-period 50` to checkpoint epoch 50, epoch 100, etc.

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
