### ISSUE TITLE
I'm not able to detect small objects

### ISSUE THREAD

**Issue by Guttappa1238** [ultralytics/yolov5#5048]
i have trained custom data with only one class, i used `yolos.pt `  and i got best mAp but when i tested on real time so many objects were not detected.

validation results:
![Screenshot from 2021-10-05 11-29-41](https://user-images.githubusercontent.com/45628395/135969119-e5aa72f8-0e79-4906-bf91-666b0d7eba2b.png)

![results](https://user-images.githubusercontent.com/45628395/135968977-a95a5e08-cc9f-4f23-968d-8bb837ebdcb2.png)

1) what should i do to increase accuracy?
2) should i try Hyperparameter Evolution?

**Comment by glenn-jocher** [comment]
@Guttappa1238 if your model is not generalizing well in deployment then it is likely that your val space and your deployment space are not sufficiently aligned (i.e. you take Spanish classes and then go to France to use your new skills). This is a common failure mode in AI pipelines.

<img width="2029" alt="dataset" src="https://user-images.githubusercontent.com/26833433/136061502-08e418d2-4ebd-4e50-b9df-57cd921ed3d1.png">

**Comment by Guttappa1238** [comment]
@glenn-jocher Thanks for thoughtful response but i need your suggestions to overcome this model generalization on deployment.

**Comment by glenn-jocher** [comment]
@Guttappa1238 beyond the info above I can't be of much use. It's up to you as the domain expert to adapt your dataset to match your real-world deployment space. Your train and val sets must naturally be subsets of your real-world deployment space, otherwise you will not achieve optimal results.
