### ISSUE TITLE
youtube video

### ISSUE THREAD

**Issue by sekisek** [ultralytics/yolov5#5049]
trying to start a youtube video from a specific time
sample:
https://youtu.be/cqIlt4OJVMg?t=222

it is starting from the beginning.
is it me or is it like that?

thanks

**Comment by glenn-jocher** [comment]
@sekisek I'm not sure what URL capabilities are handled by the `pafy` and `youtube_dl` packages. You may want to contact the authors or look at the documentation to see if this is possible and if so what updates are required to our code (if any):
https://github.com/ultralytics/yolov5/blob/5afc9c25ef0874dff0c18267947ea4e8b03c90f4/utils/datasets.py#L299-L302

**Comment by sekisek** [comment]
hi @glenn-jocher 

Thank you as always for your help!!!

what about regular videos can we start them at a certain point?

**Comment by glenn-jocher** [comment]
@sekisek detect.py processes videos from frame 0.

You can create your own custom python workflows with YOLOv5 PyTorch Hub models though. See Pytorch Hub tutorial for details:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)
