### ISSUE TITLE
P7, P2, P6 Pretrained file

### ISSUE THREAD

**Issue by aseprohman** [ultralytics/yolov5#5051]
## ❔Question
Hello @glenn-jocher
 
which one pretrained file if I want to train with yolov5-p7.yaml or yolov5-p6.yaml ?

thanks and regards

**Comment by glenn-jocher** [comment]
@aseprohman we do not have pretrained weights for these yamls, but you can point to the most similar checkpoint and YOLO will attempt to transfer as many pretrained layers as possible, i.e.:
```
python train.py --cfg yolov5-p2.yaml --weights yolov5l.pt
```

All pretrained weights are in the latest release assets at https://github.com/ultralytics/yolov5/releases/tag/v5.0

**Comment by aseprohman** [comment]
nice information, many thanks.
regards :)
