### ISSUE TITLE
What should I focus on when explaining the following table to others?

### ISSUE THREAD

**Issue by leeyunhome** [ultralytics/yolov5#5054]
## ❔Question

Hello,

What should I focus on when explaining the following table to others?
I think the last two graphs look important.
Please advise.

![image](https://user-images.githubusercontent.com/59910227/135986477-ee7958b9-5e2a-46b1-9086-219c8dff0485.png)

Thank you.

**Comment by glenn-jocher** [comment]
@leeyunhome it looks like your code is slightly out of date as the latest plots have improved labels. 

The main takeaway from your results is that you are not training long enough as your validation results have not start overfitting. You'd benefit from more epoch, i.e. try 500, 1000, 2000.
