### ISSUE TITLE
@Guttappa1238 if your model is not generalizing well in deployment then it is likely that your val space and your deployment space are not sufficiently aligned (i.e. you take Spanish classes and then go to France to use your new skills). This is a common failure mode in AI pipelines.

### ISSUE THREAD

**Issue by Bommi95** [ultralytics/yolov5#5059]
@Guttappa1238 if your model is not generalizing well in deployment then it is likely that your val space and your deployment space are not sufficiently aligned (i.e. you take Spanish classes and then go to France to use your new skills). This is a common failure mode in AI pipelines.

<img width="2029" alt="dataset" src="https://user-images.githubusercontent.com/26833433/136061502-08e418d2-4ebd-4e50-b9df-57cd921ed3d1.png">

Hi Glenn, I have a problem related to this: A model trained with SKU-110 dataset to count cars in densely packed parking cars scene. And it is generalizing well. However I have no way to measure the model performance on my real world drone image(nor do I have any information on the real counts) since the validations dataset is from SKU-110 (dataset with grocery shelves items only). Any advice on evaluating model performance? 
_Originally posted by @glenn-jocher in https://github.com/ultralytics/yolov5/issues/5048#issuecomment-934553363_

**Comment by glenn-jocher** [comment]
@Bommi95 you can create your own test set by labelling from real world data and then using `python val.py --task test` with your data.yaml.
