### ISSUE TITLE
How can you prove that you used yolov5?

### ISSUE THREAD

**Issue by leeyunhome** [ultralytics/yolov5#5062]
## ❔Question

Hello,

How can you prove that you used yolov5?
Learning process, pip list, learning graph, wandb graph
It reminds me of onnx visualization, is there anything else?

Thank you.

**Comment by glenn-jocher** [comment]
@leeyunhome well if you have the model you can inspect it in netron or pytorch to compare to the official models. 

If you only have detection results to look at there's really no way of knowing what produced those results.

**Comment by leeyunhome** [comment]
> @leeyunhome well if you have the model you can inspect it in netron or pytorch to compare to the official models.
> 
> If you only have detection results to look at there's really no way of knowing what produced those results.

Thank you very much.
