### ISSUE TITLE
Iterative training on model

### ISSUE THREAD

**Issue by mitesh741** [ultralytics/yolov5#5064]
I am developing Yolov5 training infrastructure where, **new data will be added periodically** lets say every month.

1. Lets say after two month I have substantial data to train a model so I fire training for the first time and deployed model into production for inference.
2. After one month I received new data so want to train the model (will start training on weights trained in first step) again with new data.

What data should be given to training in step 2.........?

- **All the data (Data in step 1 + New data in step 2)  ....?**
- **Keep only New data for step 2 training .......?**

I suspect during training if we give only new data then weights of old data will updated with new data and model might not perform well on data similar to old data.

I will be using yolov5s. 

Please share your thoughts.

Thanks in advance.

**Comment by glenn-jocher** [comment]
@mitesh741 typically you would train on all your available data at any point in your deployment lifecycle.

**Comment by mitesh741** [comment]
Thanks.

One more thing. Which method is used to calculate mAP? 

1) 11 point interpolation
2) All point interpolation

**Comment by glenn-jocher** [comment]
@mitesh741 mAP method is here:
https://github.com/ultralytics/yolov5/blob/48b00dbc0df672837a4af0a185210304b778dd44/utils/metrics.py#L84-L110

**Comment by mitesh741** [comment]
Thanks
