### ISSUE TITLE
Running from outside yolov5 folder fails since PR #4954

### ISSUE THREAD

**Issue by maltelorbach** [ultralytics/yolov5#5065]
## 🐛 Bug

Running any yolov5-script from outside the yolov5 folder fails. This is a regression due to https://github.com/ultralytics/yolov5/pull/4954 (which seems ironic because the PR should have make an arbitrary `cwd` possible but instead made it impossible ;) )

The attempt to determine a `ROOT` path relative to the `cwd` fails if that `cwd` is not a sub-path of `ROOT`.

## To Reproduce
```bash
git clone https://github.com/ultralytics/yolov5.git /home/user/yolov5
cd /home/user/yolov5
[install requirements etc...]
mkdir /home/user/other-dir
cd /home/user/other-dir
python /home/user/yolov5/train.py
```

Output:

```
Traceback (most recent call last):
  File "../yolov5/train.py", line 33, in <module>
    ROOT = ROOT.relative_to(Path.cwd())  # relative
  File "/home/user/.pyenv/versions/3.8.12/lib/python3.8/pathlib.py", line 908, in relative_to
    raise ValueError("{!r} does not start with {!r}"
ValueError: '/home/user/yolov5' does not start with '/home/user/other-dir'
```

## Expected behavior

The training to start.

## Additional context

This worked before https://github.com/ultralytics/yolov5/pull/4954

The same PR resulted in these issues: https://github.com/ultralytics/yolov5/issues/4973 and https://github.com/ultralytics/yolov5/issues/4970 where custom model could not be loaded from torch hub. That issue has been fixed, but not the above mentioned.

**Comment by maltelorbach** [comment]
To offer a solution: falling back to [os.path.relpath](https://docs.python.org/3/library/os.path.html#os.path.relpath) seems to do what is desired. But correct me if I'm missing something. `os.path.relpath` works with strings as well as path-like objects since Python 3.6. So instead of
```python
ROOT = ROOT.relative_to(Path.cwd())
```
we can do
```python
ROOT = Path(os.path.relpath(ROOT, Path.cwd()))
```


Only drawback is:
> On Windows, ValueError is raised when path and start are on different drives.

Not sure if that's a case that needs to be covered.

In my example above, this would be the output:
```python
>>> from pathlib import Path
>>> import os.path
>>> ROOT = Path("/home/user/yolov5")
>>> other = Path("/home/user/other")
>>> ROOT.relative_to(other)  # fails
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/malte/.pyenv/versions/3.8.12/lib/python3.8/pathlib.py", line 908, in relative_to
    raise ValueError("{!r} does not start with {!r}"
ValueError: '/home/user/yolov5' does not start with '/home/user/other'
>>> os.path.relpath(ROOT, other)  # works
'../yolov5'
```

**Comment by glenn-jocher** [comment]
@maltelorbach thanks for the bug report! Your fix looks good, can you submit a PR please?

**Comment by maltelorbach** [comment]
Of course, see: https://github.com/ultralytics/yolov5/pull/5129

**Comment by glenn-jocher** [comment]
@maltelorbach great, thank you!
