### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9f in position 10: character maps to <undefined>

### ISSUE THREAD

**Issue by Khwan7662** [ultralytics/yolov5#5066]
# yolov5 train model found the issue "UnicodeDecodeError: 'charmap'
please, help to solve this issue.

(pytorch_1) D:\6_Autonomous Systems(AI)\Week6\project\yolov5-master>python train.py --img 640 --batch 16 --epochs 10 --data config.yaml --weights yolov5s.pt
train: weights=yolov5s.pt, cfg=, data=config.yaml, hyp=data/hyps/hyp.scratch.yaml, epochs=10, batch_size=16, imgsz=640, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, evolve=None, bucket=, cache=None, image_weights=False, device=, multi_scale=False, single_cls=False, adam=False, sync_bn=False, workers=8, project=runs/train, entity=None, name=exp, exist_ok=False, quad=False, linear_lr=False, label_smoothing=0.0, upload_dataset=False, bbox_interval=-1, save_period=-1, artifact_alias=latest, local_rank=-1, freeze=0, patience=100
github: skipping check (not a git repository), for updates see https://github.com/ultralytics/yolov5
YOLOv5  2021-9-25 torch 1.9.1+cpu CPU

Traceback (most recent call last):
  File "train.py", line 614, in <module>
    main(opt)
  File "train.py", line 511, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 75, in train
    hyp = yaml.safe_load(f)  # load hyps dict
  File "C:\Users\OS\anaconda3\envs\pytorch_1\lib\site-packages\yaml\__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\OS\anaconda3\envs\pytorch_1\lib\site-packages\yaml\__init__.py", line 112, in load
    loader = Loader(stream)
  File "C:\Users\OS\anaconda3\envs\pytorch_1\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "C:\Users\OS\anaconda3\envs\pytorch_1\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "C:\Users\OS\anaconda3\envs\pytorch_1\lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "C:\Users\OS\anaconda3\envs\pytorch_1\lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "C:\Users\OS\anaconda3\envs\pytorch_1\lib\encodings\cp874.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9f in position 10: character maps to <undefined>

**Comment by Khwan7662** [comment]
Hi, Glenn Jocher
I have issued while train model error at cp874.py , line 23, in decode as message below.
 "_**return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9f in position 10: character maps to <undefined>**__"

Please help to suggest.

![Unicodedecodeerror](https://user-images.githubusercontent.com/92008307/136435403-c419fb01-07ec-422c-a0c2-dc922db8971c.PNG)

**Comment by glenn-jocher** [comment]
@Khwan7662 good news 😃! Your original issue may now be fixed ✅ in PR #5060. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by Khwan7662** [comment]
Dear  Glenn Jocher

Thank you so much, The issue have fixed as you advised.

Best regards,
Khwanchai.


ในวันที่ ศ. 8 ต.ค. 2021 เวลา 03:07 Glenn Jocher ***@***.***>
เขียนว่า:
