### ISSUE TITLE
Impossible to do "square" inference

### ISSUE THREAD

**Issue by hdnh2006** [ultralytics/yolov5#5067]
## ❔Question
No matter what I do in detect.py, I always get rectangular inference.

I want to compare the performance with another model so I ran `python train.py --rect ` as it is suggested [here](https://github.com/ultralytics/yolov5/issues/4403#issuecomment-899024993) and then I made inference with the classic command: 
`python detect.py --img 640 640`

And I am still getting size like `384x640` in the logs. 

Can somebody tell me how do I solve it?

**Comment by glenn-jocher** [comment]
@hdnh2006 pass a square image if you want square inference.

**Comment by hdnh2006** [comment]
It seems the latest version of YOLOv5 has fix this "issue". Thanks

**Comment by glenn-jocher** [comment]
@hdnh2006 oh, great!
