### ISSUE TITLE
What is inside Pytorch Model?

### ISSUE THREAD

**Issue by jaskiratsingh2000** [ultralytics/yolov5#5068]
Hi @glenn-jocher @batrlatom I just have a quick question to understand regarding which I am having a hard time understanding it since long. What is actually inside the Pytorch model and Tflite model? I don't understand that what's the format inside the PyTorch model. When do we say that we are compiling the Pytorh model then what does happen intermediately?

**Comment by glenn-jocher** [comment]
@jaskiratsingh2000 you can start with the pytorch tutorials, i.e. https://pytorch.org/tutorials/beginner/basics/buildmodel_tutorial.html

**Comment by jaskiratsingh2000** [comment]
@glenn-jocher this I know but I am specifically asking in Yolov5 pytorch models

**Comment by jaskiratsingh2000** [comment]
Like yolov5.yaml

**Comment by glenn-jocher** [comment]
@jaskiratsingh2000 you can `print(model)` or look at individual modules, i.e. `model.model[0]`

**Comment by jaskiratsingh2000** [comment]
Within which script I can find this or where I meed to print this. In detect.py?

**Comment by glenn-jocher** [comment]
@jaskiratsingh2000 you can print the model in any workspace that has it, i.e. detect.py, val.py, train.py, export.py, yolo.py. You can also load a model with hub and print it:

```python
import torch

model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, custom
print(model)
```
