### ISSUE TITLE
Cloned the latest push. Facing error "Index 0 out of range"

### ISSUE THREAD

**Issue by jamshaidsohail5** [ultralytics/yolov5#507]
## ❔Question
I cloned the latest push of this repo and ran the train.py for my problem as below. 

python ./train.py --img 1024 --batch 2 --epochs 1 --data "../input/configyolo5v1/configYolo5v1/wheat0.yaml" --cfg "../input/yolov5yaml/yolov5xx.yaml"   --name yolov5x_fold0 --weights yolov5x.pt

And I am getting the below error.
![issue](https://user-images.githubusercontent.com/30027865/88432845-6e19ac00-ce16-11ea-98c9-555114c1014d.PNG)

**Comment by glenn-jocher** [comment]
@jamshaidsohail5 it looks like you are using a custom yaml. v2.0 introduced breaking changes to the yaml structure, the output nn.Conv2d() layers are no longer required, they are produced by detect.py automatically, you simply supply the output layer indices you want in the Detect() 'from' list:

https://github.com/ultralytics/yolov5/blob/1d17b9af0f68ee97f9edc5f10fea51e9af9ef14e/models/yolov5x.yaml#L37-L48

**Comment by glenn-jocher** [comment]
So in the example above the 3 nn.Conv2d() that used to exist have been removed, and the Detect() from list is [17, 20, 23] to let the Detect() layer know that we want to read out these 3 layers.

**Comment by glenn-jocher** [comment]
@jamshaidsohail5 for complete diff see:
https://github.com/ultralytics/yolov5/commit/9da56b62ddee550c0db0662c7ca00bcc6bfcf99a#diff-6ce00358b73e368683f44e99e91698f7

**Comment by jamshaidsohail5** [comment]
Resolved thanks.
