### ISSUE TITLE
 I'm not able to detect table/Furniture objects 

### ISSUE THREAD

**Issue by longtran84** [ultralytics/yolov5#5073]
![s3url_3bf533a0-2138-11eb-a63d-0a7e0f26cac8_544880059540312](https://user-images.githubusercontent.com/33080326/136306875-e37572f6-d9db-4db4-9eb6-c19ec8fce74a.jpg)

**Comment by longtran84** [comment]
can anyone solve this problem ? thanks

**Comment by glenn-jocher** [comment]
@longtran84 I don't understand. What's the problem you are having specifically?

**Comment by longtran84** [comment]
@glenn-jocher i mean, it can't detect table object in that image.

**Comment by glenn-jocher** [comment]
@longtran84 there are no tables in your image, that's a desk.

**Comment by longtran84** [comment]
@glenn-jocher so why it not show desk object...can you help me ? thanks

**Comment by glenn-jocher** [comment]
@longtran84 YOLOv5 models are trained on COCO by default, which has 80 common classes of objects. You can see the objects here. Anything not on this list won't be detected with the official models, but you can train your own custom models also of course to detect any other classes you want as long as you have labelled data for those classes.

https://github.com/ultralytics/yolov5/blob/48b00dbc0df672837a4af0a185210304b778dd44/data/coco.yaml#L16-L27
