### ISSUE TITLE
RTP stream

### ISSUE THREAD

**Issue by Yousef-Alhattab** [ultralytics/yolov5#5075]
## ❔Question
Is there any way to run the inference on RTP?

Thank you

**Comment by glenn-jocher** [comment]
@urbansound8K you can read the README for inference examples:
<img width="869" alt="Screen Shot 2021-10-07 at 3 52 35 PM" src="https://user-images.githubusercontent.com/26833433/136473003-9916060c-0302-4be1-a6aa-8f0bb0e736b9.png">

**Comment by Yousef-Alhattab** [comment]
thanks a lot

I saw that you provide a RTSP, RTMP, and HTTP streams, but the stream I get from my camera is RTP?

Is it possible to make any modifies to get inference on RTP?

**Comment by glenn-jocher** [comment]
@urbansound8K I have no idea if your stream will work, just pass your stream address as in the examples shown above to verify functionality.
