### ISSUE TITLE
coco annotations possible?

### ISSUE THREAD

**Issue by firsakov** [ultralytics/yolov5#5076]
Hi, 

in custom data train tutorial only yolo annotation format is described,
but If i have data annotations in coco jormat and single json file for all images, is it possible to make custom train?

**Comment by glenn-jocher** [comment]
@firsakov we have PR https://github.com/ultralytics/yolov5/pull/4527 open for this task, though I don't have expected completion date for you. One that's merged then yes you can train directly from COCO-labelled JSON annotation files.

**Comment by firsakov** [comment]
@glenn-jocher thank you for reply!
yes, I have merged file. so if I understand you right, it's possible to train now with merged file (or I am struggling with English).
and how should I modify my dataset yaml file?

```python
path: ../data/yolodata/coco128  # dataset root dir
train: images/train2017  # train images (relative to 'path') 128 images
val: images/train2017  # val images (relative to 'path') 128 images
test:  # test images (optional)
```

**Comment by glenn-jocher** [comment]
@firsakov if you want to train right now with COCO format annotations you can use this repo to convert to YOLO:
https://github.com/ultralytics/JSON2YOLO

**Comment by firsakov** [comment]
@glenn-jocher  thanks!
