### ISSUE TITLE
Arial.ttf download in Docker

### ISSUE THREAD

**Issue by lchunleo** [ultralytics/yolov5#5078]
## Additional context

Hi
 i am trying to run in the yolov5 "detect.py" on my dataset and specified the weights in the docker container. However, it kept having
"Downloading https://ultralytics.com/assets/Arial.ttf to /usr/src/app/.config/Ultralytics/Arial.ttf..." which i did not see it when running  the code outside the docker container. Can advise how to remove it? thank you

**Comment by SureshbabuAkash1999** [comment]
I think, for that, you have to remove the line which redirects to the downloads in the .yaml file.

**Comment by glenn-jocher** [comment]
@lchunleo we use Arial to print all the complex UTF and Chinese characters that are commonly used. If your system does not have the font, then it is downloaded the first time YOLOv5 runs.

Docker missing the font is interesting, we should probably package it directly in the container. I'll add a TODO item for this.

TODO: RUN install Arial in Dockerfile

**Comment by glenn-jocher** [comment]
Interesting update, Arial downloads to app/.config, which the user may delete, this seems to be caused by the following line. Should delete this line or assign /root to HOME.
https://github.com/ultralytics/yolov5/blob/070af88108e5675358fd783aae9d91e927717322/Dockerfile#L25
