### ISSUE TITLE
Adjust the fps rate for input video.

### ISSUE THREAD

**Issue by SureshbabuAkash1999** [ultralytics/yolov5#5079]
Firstly, thanks a lot Ultralytics for the awesome algorithm. I have been running the algorithm in a drone and I was just wondering if there was an option to reduce the frame rate of the input video? 

 Cheers!

**Comment by glenn-jocher** [comment]
@SureshbabuAkash1999 we use cv2 for loading videos and streams. Maybe you can modify the cv2 cap properties or the loader code to adjust to your requirements. The locations are:

For images and videos:
https://github.com/ultralytics/yolov5/blob/57ce73cd4f0c3eb9b2e65f8094a3e53bda58651b/utils/datasets.py#L158-L160

For streaming sources:
https://github.com/ultralytics/yolov5/blob/57ce73cd4f0c3eb9b2e65f8094a3e53bda58651b/utils/datasets.py#L282-L284

**Comment by SureshbabuAkash1999** [comment]
Is the below given line the one that adjusts the fps? 
https://github.com/ultralytics/yolov5/blob/57ce73cd4f0c3eb9b2e65f8094a3e53bda58651b/utils/datasets.py#:~:text=self.fps%5Bi%5D%20%3D%20max(cap.get(cv2.CAP_PROP_FPS)%20%25%20100%2C%200)%20or%2030.0%20%20%23%2030%20FPS%20fallback

**Comment by glenn-jocher** [comment]
@SureshbabuAkash1999 your line link is broken

**Comment by SureshbabuAkash1999** [comment]
Is it this line in the python file dataset.py?
![Capture](https://user-images.githubusercontent.com/64519161/136904878-3a23d9e1-46b5-46ed-9a2c-75420bf12570.PNG)

**Comment by glenn-jocher** [comment]
@SureshbabuAkash1999 this is a read only property I believe, but you should the cv2 documentation. This FPS is printed to screen as a stream property when loading a stream or a webcam before inference starts.
