### ISSUE TITLE
Unexpected image sizes

### ISSUE THREAD

**Issue by rus8** [ultralytics/yolov5#5080]
## Additional context
I added `print(self.batch_shapes)` to the line 465 of utils/datasets.py.

During simple test run of val.py I see the following output:
```
val.py --batch 16
val: data=data/coco128.yaml, weights=yolov5s.pt, batch_size=16, imgsz=640, conf_thres=0.001, iou_thres=0.6, task=val, device=, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=runs/val, name=exp, exist_ok=False, half=False

...

[[512 704]
 [512 704]
 [512 704]
 [512 704]
 [512 704]
 [704 704]
 [704 640]
 [704 512]]

...
```

## Question
Is it ok to have such img sizes in batches while imgsz=640?

**Comment by glenn-jocher** [comment]
@rus8 dataloader padding arguments are here:
https://github.com/ultralytics/yolov5/blob/070af88108e5675358fd783aae9d91e927717322/val.py#L146-L153
