### ISSUE TITLE
Tensorflow export

### ISSUE THREAD

**Issue by AlexisPapaioannou** [ultralytics/yolov5#5081]
## ❔Question
On the new version, when exporting the tflite model there isn't exist the detection layer as the last layer. Should I add it when executing the tflite model?

**Comment by glenn-jocher** [comment]
@AlexisPapaioannou all exported model formats including TFLite contain the full YOLOv5 model, just like pytorch. Detect() layers are always included. If this is not the case for you you may need to update your code, and then you can export TFLite simply with
```
python export.py --weights yolov5s.pt --include tflite
```

**Comment by nrupatunga** [comment]
@glenn-jocher I get the error for converting to half-precision format 

```python export.py --weights yolov5s.pt --include tflite --half --device 0 ```
```
TensorFlow Lite: export failure: 'NoneType' object has no attribute 'call'
```
