### ISSUE TITLE
Second stage classifier recommended training regimen

### ISSUE THREAD

**Issue by patkipv** [ultralytics/yolov5#5082]
Is it possible if you could direct me to a training regimen for ResNet or EfficientNet from which the weights produced work with the existing YOLO code base? 

So I am working to get YOLO to detect objects in a video and then use the second stage classifier to classify what color the objects are. I have trained YOLO to detect the objects and also a ResNet101 model to classify the color of the object. My trained weights were .pth so as per Glenn's solution in a previous ticket I just changed it to .pt to make it work. But I keep getting errors one after the other with respect to my trained weights for the secondary classifier. I have looked at the TowerScout repo and haven't been able to figure it out.

**Comment by glenn-jocher** [comment]
@patkipv an alternative to using detect.py is to load your model with PyTorch Hub, and then crop the results for passing to your classification model. You can build this pipeline in python, it shouldn't be too difficult:

```python
model = torch.hub.load(...

results = model(img)
crops = results.crop()
```

See PyTorch Hub tutorial to get started with this route:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by patkipv** [comment]
Thank you Glenn for the quick reply. I will try that out.
