### ISSUE TITLE
Module collision when loading more than one model with Torch Hub

### ISSUE THREAD

**Issue by carloalbertobono** [ultralytics/yolov5#5083]
Hi, I think I have a similar issue to #2414 (I commented there but later realized that the issue was closed)

It prevents from loading more than one model using torch.hub
If I'm not mistaken by reading the thread, loading the model with torch.hub shadows some module names, that then become unusable within torch.

I'm using torch '1.9.1+cu102' on a Ubuntu 20.04 machine and to reproduce I do:

```
import torch
model = torch.hub.load('facebookresearch/detr', 'detr_resnet50', pretrained=True)
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)
```

that ends up in

```
~/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py in _create(name, pretrained, channels, classes, autoshape, verbose, device)
     28     from pathlib import Path
     29 
---> 30     from models.yolo import Model
     31     from models.experimental import attempt_load
     32     from utils.general import check_requirements, set_logging

ModuleNotFoundError: No module named 'models.yolo'
```

reversing the load order obviously ends up with:

```
~/.cache/torch/hub/facebookresearch_detr_master/hubconf.py in <module>
      2 import torch
      3 
----> 4 from models.backbone import Backbone, Joiner
      5 from models.detr import DETR, PostProcess
      6 from models.position_encoding import PositionEmbeddingSine

ModuleNotFoundError: No module named 'models.backbone'
```

Is there some workaround which I'm not seeing?

Thank you very much, also for the awesome project itself
cb

**Comment by glenn-jocher** [comment]
@carloalbertobono thanks for the bug report. I am able to reproduce the issue using your code in colab. I'm not sure there's a simple fix, but also this might be slightly outside of our scope. You should definitely raise on pytorch and/or hub repos also, and link to this issue. Thanks!

https://github.com/pytorch/pytorch
https://github.com/pytorch/hub

**Comment by carloalbertobono** [comment]
thank you @glenn-jocher, I'll do it!

**Comment by NicolasHug** [comment]
@glenn-jocher  this is definitely an issue on the torchhub side (which I'm looking into), so feel free to close this one

**Comment by glenn-jocher** [comment]
@NicolasHug thanks for looking into this! I'd imagine loading multiple hub models from different sources will become more common as the feature gains adoption, so probably worth the effort to find a fix. 

Will close here and follow https://github.com/pytorch/hub/issues/243
