### ISSUE TITLE
how is it different from the usual way to save a model in yolov5?

### ISSUE THREAD

**Issue by leeyunhome** [ultralytics/yolov5#5090]
## ❔Question

Hello,

I know that the pytorch model file has an extension of .pt, and when saving the model, one of two methods can be selected.

look at the code
yolov5 seems to save the entire model, is that correct?
Other than that, how is it different from the usual way to save a model in yolov5?
![image](https://user-images.githubusercontent.com/59910227/136488597-cb0f4c89-9456-446a-b56d-d8b030730a9d.png)

Thank you.

**Comment by glenn-jocher** [comment]
@leeyunhome I don't know what your exact question is, but you can read about pytorch model saving here:
https://pytorch.org/tutorials/beginner/saving_loading_models.html

**Comment by leeyunhome** [comment]
> @leeyunhome I don't know what your exact question is, but you can read about pytorch model saving here: https://pytorch.org/tutorials/beginner/saving_loading_models.html

Hello,

It is said that if you use state_dict, only a dictionary with learnable parameters (i.e. weights and biases) is stored, not the entire model.
I saw the yolov5 train code and decided that I would save the entire model, but I asked a question just in case.
Since there is no code to save with model.state_dict(), it seems to be correct to save the entire model.

Thank you.

**Comment by glenn-jocher** [comment]
@leeyunhome oh, sorry, yes the entire model is saved, so the YOLOv5 *.pt files contain a full model, not just a state dict.
