### ISSUE TITLE
AssertionError: '' acceptable suffix is ['.pt']

### ISSUE THREAD

**Issue by Karol-G** [ultralytics/yolov5#5094]
Hi,

the bug is reproducible with the current repo, the coco128.yaml and a Docker image. 

## 🐛 Bug

When I try to train on coco128 from scratch (without pretrained weight init) then I get an AssertionError.

## To Reproduce

Input command:

`python train.py --weights '' --cfg yolov5s.yaml --device 0`

Output:

```
Traceback (most recent call last):
  File "/home/k539i/Documents/projects/yolov5/train.py", line 620, in <module>
    main(opt)
  File "/home/k539i/Documents/projects/yolov5/train.py", line 517, in main
    train(opt.hyp, opt, device, callbacks)
  File "/home/k539i/Documents/projects/yolov5/train.py", line 111, in train
    check_suffix(weights, '.pt')  # check weights
  File "/home/k539i/Documents/projects/yolov5/utils/general.py", line 301, in check_suffix
    assert Path(f).suffix.lower() in suffix, f"{msg}{f} acceptable suffix is {suffix}"
AssertionError: '' acceptable suffix is ['.pt']
```

## Expected behavior

The model should train from scratch without throwing an exception.

Best
Karol

**Comment by glenn-jocher** [comment]
@Karol-G thanks for raising this bug report! Your issue is not reproducible in Docker. In order to address a possible problem we must first be able to reproduce it. Can you verify your issue is reproducible?

<img width="1271" alt="Screen Shot 2021-10-09 at 1 49 44 PM" src="https://user-images.githubusercontent.com/26833433/136673430-da747fdc-b537-4e5c-85e6-be2295023b1a.png">

**Comment by Karol-G** [comment]
Are you able to reproduce the bug in a normal python env or anaconda env?

**Comment by glenn-jocher** [comment]
@Karol-G I'm not able to reproduce your issue in Docker or in Colab or locally on my Macbook in Pycharm. If we can not reproduce your issue, there is no action for us to take.

**Comment by Karol-G** [comment]
I rechecked everything and it seems that the exception is only thrown when I use PyCharm (Linux). The same command in the same env runs without problems if executed in a terminal. No idea why that is the case.

From my side the issue is solved, but it would of course be cool if the PyCharm issue would be resolved. But that has probably low priority.

Best
Karol

**Comment by glenn-jocher** [comment]
@Karol-G got it, thanks!
