### ISSUE TITLE
@studentWUR I made a small bug fix https://github.com/ultralytics/yolov5/commit/04fddf507fcecace0ef1842f841517a4c0fdbdb3 to the classifier branch and now everything works correctly. MNIST is at 99% in 5 epochs.

### ISSUE THREAD

**Issue by hamedmh** [ultralytics/yolov5#5096]
@glenn-jocher 
Hi Glenn,

When I use the trained model, I get strange results such as this one when trying to recognize a "1":

tensor([[-7.56136,  0.97649,  0.89310, -6.52377, 12.88777, -1.86249,  2.16834, -2.48633,  0.05985, -2.34526]])

Can you please explain what might cause this?

**Your original post was:**

I made a small bug fix https://github.com/ultralytics/yolov5/commit/04fddf507fcecace0ef1842f841517a4c0fdbdb3 to the classifier branch and now everything works correctly. MNIST is at 99% in 5 epochs.

INPUT:
```bash
python classifier.py --data mnist
```

OUTPUT:
```bash
YOLOv5 v4.0-42-gb34e21b torch 1.7.0+cu101 CUDA:0 (Tesla V100-SXM2-16GB, 16130.5MB)

Training yolov5s on mnist dataset with 10 classes...
Using cache found in /root/.cache/torch/hub/ultralytics_yolov5_master

                 from  n    params  module                                  arguments                     
  0                -1  1      3520  models.common.Focus                     [3, 32, 3]                    
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]                
  2                -1  1     18816  models.common.C3                        [64, 64, 1]                   
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]               
  4                -1  1    156928  models.common.C3                        [128, 128, 3]                 
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]              
  6                -1  1    625152  models.common.C3                        [256, 256, 3]                 
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]              
  8                -1  1    656896  models.common.SPP                       [512, 512, [5, 9, 13]]        
  9                -1  1   1182720  models.common.C3                        [512, 512, 1, False]          
 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]              
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 12           [-1, 6]  1         0  models.common.Concat                    [1]                           
 13                -1  1    361984  models.common.C3                        [512, 256, 1, False]          
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]              
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 16           [-1, 4]  1         0  models.common.Concat                    [1]                           
 17                -1  1     90880  models.common.C3                        [256, 128, 1, False]          
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]              
 19          [-1, 14]  1         0  models.common.Concat                    [1]                           
 20                -1  1    296448  models.common.C3                        [256, 256, 1, False]          
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]              
 22          [-1, 10]  1         0  models.common.Concat                    [1]                           
 23                -1  1   1182720  models.common.C3                        [512, 512, 1, False]          
 24      [17, 20, 23]  1    229245  models.yolo.Detect                      [80, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
Model Summary: 283 layers, 7276605 parameters, 7276605 gradients, 17.1 GFLOPS

Model Summary: 128 layers, 1194954 parameters, 1194954 gradients, 8.5 GFLOPS

epoch     gpu_mem   train_loss  val_loss    accuracy    
1/20      0.596G    0.443       0.0617      0.983       : 100% 469/469 [00:45<00:00, 10.32it/s]
2/20      0.598G    0.0927      0.0528      0.981       : 100% 469/469 [00:45<00:00, 10.22it/s]
3/20      0.598G    0.0742      0.0448      0.986       : 100% 469/469 [00:45<00:00, 10.27it/s]
4/20      0.598G    0.0635      0.0375      0.989       : 100% 469/469 [00:45<00:00, 10.32it/s]
5/20      0.598G    0.0546      0.031       0.991       : 100% 469/469 [00:46<00:00, 10.19it/s]
6/20      0.598G    0.0531      0.0271      0.991       : 100% 469/469 [00:45<00:00, 10.24it/s]
7/20      0.598G    0.0482      0.0253      0.992       : 100% 469/469 [00:45<00:00, 10.31it/s]
```

_Originally posted by @glenn-jocher in https://github.com/ultralytics/yolov5/issues/2001#issuecomment-777051150_

**Comment by hamedmh** [comment]
@glenn-jocher
This is my inference function:

def inference():
    device = torch.device('cuda:0')

    torch.set_default_tensor_type('torch.cuda.FloatTensor')
    
    check_point_best = "/home/hamed/yolov5_classifier/yolov5-classifier/runs/train/exp8/weights/best.pt"
    
    
    # YOLOv5 Classifier
    if opt.data == "mnist":
        nc = 10  # number of classes = 10 ,för mnist (1 2 3 4 5 6 7 8 9 0)
        
    model = torch.hub.load('ultralytics/yolov5', opt.model, pretrained=True, autoshape=False)
    model.model = model.model[:8]
    m = model.model[-1]  # last layer
    ch = m.conv.in_channels if hasattr(m, 'conv') else sum([x.in_channels for x in m.m])  # ch into module
    c = Classify(ch, nc)  # Classify()
    c.i, c.f, c.type = m.i, m.f, 'models.common.Classify'  # index, from, type
    model.model[-1] = c  # replace
    for p in model.parameters():
        p.requires_grad = True  # for training

    
    # load the weights:    
    checkpoint = torch.load(check_point_best)
    model.load_state_dict(checkpoint)

    model.eval()

    # read the example image used for tracing
    if opt.data == "mnist":
        file_name = "14.png"
        path_to_files = "/home/hamed/yolov5_classifier/mnist/test/1/"        
    
    image = cv2.imread(path_to_files + file_name)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)


    if opt.data == "mnist":
        trainform = T.Compose([T.RandomGrayscale(p=0.01),
                           T.RandomHorizontalFlip(p=0.5),
                           T.RandomAffine(degrees=1, translate=(.2, .2), scale=(1 / 1.5, 1.5),
                                          shear=(-1, 1, -1, 1), fill=(114, 114, 114)),
                           # T.Resize([imgsz, imgsz]),  # very slow
                           T.ToTensor(),
                           T.Normalize((0.5, 0.5, 0.5), (0.25, 0.25, 0.25))])  # PILImage from [0, 1] to [-1, 1]
        
        # Transforms for testing (without image augmentation):
        testform = T.Compose(trainform.transforms[-2:])
        
        # Transforms for testing (without image augmentation):
        chosen_transforms = [trainform.transforms[i] for i in [0, -2, -1]]
        testform = T.Compose(chosen_transforms)

    im = Image.fromarray(image)
    img_tensor1 = testform(im).to(device).unsqueeze(0)
    
    with torch.no_grad():
        output1 = model(img_tensor1)
        
    print("Inference result : ", output1)

**Comment by glenn-jocher** [comment]
@hamedmh I looked at the classifier branch and saw it had a few issues that had arisen due to divergence with master. I've merged master, verified correct operation, and added an inference usage example:

### YOLOv5 Classifier Training
```bash
git clone https://github.com/ultralytics/yolov5 -b classifier
cd yolov5
pip install -r requirements.txt

python classifier.py --model yolov5s --data mnist --epochs 5 --img 128
```
```bash
github: up to date with https://github.com/ultralytics/yolov5 ✅
YOLOv5 🚀 v5.0-527-g76259b1 torch 1.9.0+cu111 CUDA:0 (Tesla P100-PCIE-16GB, 16280.875MB)

Training yolov5s on mnist dataset with 10 classes...
Using cache found in /root/.cache/torch/hub/ultralytics_yolov5_master
YOLOv5 🚀 v5.0-527-g76259b1 torch 1.9.0+cu111 CUDA:0 (Tesla P100-PCIE-16GB, 16280.875MB)

Fusing layers... 
Model Summary: 224 layers, 7266973 parameters, 0 gradients
/usr/local/lib/python3.7/dist-packages/torch/_tensor.py:575: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  /pytorch/aten/src/ATen/native/BinaryOps.cpp:467.)
  return torch.floor_divide(self, other)
Model Summary: 101 layers, 1192362 parameters, 1192362 gradients
Image sizes 128 train, 128 test
Using 2 dataloader workers
Logging results to runs/train/exp3
Starting training for 5 epochs...

epoch     gpu_mem   train_loss  val_loss    accuracy    
1/5       0.958G    0.436       0.152       0.953       : 100% 469/469 [00:35<00:00, 13.38it/s]
2/5       0.958G    0.128       0.0674      0.979       : 100% 469/469 [00:34<00:00, 13.43it/s]
3/5       0.958G    0.0908      0.0609      0.98        : 100% 469/469 [00:34<00:00, 13.52it/s]
4/5       0.958G    0.0689      0.0379      0.986       : 100% 469/469 [00:34<00:00, 13.52it/s]
5/5       0.958G    0.0499      0.0279      0.99        : 100% 469/469 [00:34<00:00, 13.44it/s]
Training complete. Results saved to runs/train/exp.
```

### YOLOv5 Classifier Inference
```python
import cv2
import numpy as np
import torch
import torch.nn.functional as F

# Functions
resize = torch.nn.Upsample(size=(128, 128), mode='bilinear', align_corners=False)
normalize = lambda x, mean=0.5, std=0.25: (x - mean) / std

# Model
model = torch.load('runs/train/exp/weights/best.pt')['model'].cpu().float()

# Image
im = cv2.imread('../mnist/test/0/10.png')[::-1]  # HWC, BGR to RGB
im = np.ascontiguousarray(np.asarray(im).transpose((2, 0, 1)))  # HWC to CHW
im = torch.tensor(im).unsqueeze(0) / 255.0  # to Tensor, to BCWH, rescale
im = resize(normalize(im))

# Inference
results = model(im)
p = F.softmax(results, dim=1)  # probabilities
print(p)

tensor([[9.99685e-01, 2.24096e-11, 6.25672e-06, 6.37622e-07, 2.57255e-09, 6.91358e-07, 3.36181e-05, 3.68758e-08, 6.94699e-06, 2.66681e-04]], grad_fn=<SoftmaxBackward>)
```

**Comment by hamedmh** [comment]
@glenn-jocher
Thanks Glenn!

**Comment by glenn-jocher** [comment]
@hamedmh you're welcome! Let me know if you run into any other issues.

We plan on introducing classification capabilities from this branch into master in the future, so it's useful to get feedback on it.

**Comment by hamedmh** [comment]
@glenn-jocher 
I tested training the classifier intensively and found it useful. However, many times, it fails at the beginning of the training process and gets nan training loss or a training loss value greater than 1 (greater than 100%). I then simply interrupt it and restart training again. There should be a better way of fixing this "bug". I think it is caused by using half().

**Comment by glenn-jocher** [comment]
@hamedmh yes, we just need some more experimentation there and perhaps a better warmup policy to prevent early instabilities.

**Comment by hamedmh** [comment]
Hi @glenn-jocher , 
I tried the updated repository and found the following bug in classifier.py: a DetectMultiBackend() is obtained and contains the Model(). Therefore, it needs to add  "model = model.model"  here:
        model = torch.hub.load('ultralytics/yolov5', opt.model, pretrained=True, autoshape=False)
        model = model.model
In addition, it was not possible to automaticall download the mnist dataset and the yolov5s.pt. I had to download/copy them manually.
Best regards, Hamed

**Comment by hamedmh** [comment]
Delete the folder   "/home/your_own_user/.cache/torch/hub/ultralytics_yolov5_master"   whenever you get the error:

Exception: Cache may be out of date, try `force_reload=True`. See https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading for help.

instead of setting  `force_reload=True` , which might cause other troubles.
Then, reboot Linux.

**Comment by glenn-jocher** [comment]
@hamedmh thanks for the bug report! I've updated the classifier branch with your proposed fix and verified correct MNIST classification training now (including MNIST auto-download):

```
!python classifier.py --model yolov5s --data mnist --epochs 5 --img 128
```

<img width="1385" alt="Screenshot 2021-12-06 at 21 00 49" src="https://user-images.githubusercontent.com/26833433/144914091-63d215ff-2a30-4d8e-857b-1e6c6d577161.png">

**Comment by CrucialDrew** [comment]
> @glenn-jocher I tested training the classifier intensively and found it useful. However, many times, it fails at the beginning of the training process and gets nan training loss or a training loss value greater than 1 (greater than 100%). I then simply interrupt it and restart training again. There should be a better way of fixing this "bug". I think it is caused by using half().

I run into the same issue with the latest release within the docker image.

I'm skeptical of the results even when they are not nan, because sometimes it even gets stuck a train_loss of 2.3. Sometimes the accuracy gets stuck, where it's the same every epoch, lots of weirdness.

I'm running this:

> python classifier.py --model yolov5s --data mnist --epochs 5 --img 128

Beyond that, I have not gotten the inference to work reliably either. On the mnist dataset, after training for 100+ epochs, it will still incorrectly guess most results wildly. I'm skeptical that everything is working, because you'd expect, since it achieves such high accuracy, that inference would be similarly reliable.

Maybe I'm misunderstanding how the reference example works, but my assumption is that each element in the tensor array corresponds to the index of the class.

`tensor([[2.68268e-05, 7.47103e-12, 5.50880e-01, 1.02230e-04, 7.43604e-09, 4.96133e-04, 5.27150e-02, 4.15259e-09, 3.95567e-01, 2.12854e-04]], grad_fn=<SoftmaxBackward0>)
`

So I figured it went like this:

0: 2.68268e-05
1: 7.47103e-12
2: 5.50880e-01
3: 1.02230e-04
4: 7.43604e-09
5: 4.96133e-04
6: 5.27150e-02
7: 4.15259e-09
8: 3.95567e-01
9: 2.12854e-04

As in, for the inference results, it's guessing the number in the image is the number two with 55% confidence.

Is that how it's supposed to work?

**Comment by glenn-jocher** [comment]
@CrucialDrew training and inference both work correctly **if you follow the Usage example in classifier.py.** If you make up your own training and inference workflows those results are on you. 

https://github.com/ultralytics/yolov5/blob/ecd0f6d9b97b65bab5eda27abcd4187cb2af2a9f/classifier.py#L5-L29

<img width="1150" alt="Screenshot 2021-12-11 at 14 22 36" src="https://user-images.githubusercontent.com/26833433/145678208-6fc7586e-32b3-45fc-a162-88f4cab83ac3.png">

**Comment by hamedmh** [comment]
@CrucialDrew try to use  the following (in classifier.py, in train()) to stabilize the training process - slightly :)

at about line 90 in the code:
T.Normalize((0.25, 0.25, 0.25), (0.25, 0.25, 0.25))]) 

and at about line 150 in the code:
lr0 = 0.00005 * bs

**Comment by CrucialDrew** [comment]
I just want to say - I really appreciate your help, and this project in general. I've been programming professionally for over a decade, but I have practically no experience with machine learning outside of Yolov5's object detection. I _**love**_ that you guys are empowering "regular developers". I'm trying to use this project to help a non-profit track and identify wild horses in Arizona. My intention, which may be too ambitious, is to use yolov5 to crop in images of the horse's faces, and then classifier.py to identify which horse it is (there are about 500 horses).

@glenn-jocher The only thing I've done beyond the example is change 0/10.png to other images within the test directory.

I'm running everything in the docker container you guys provide to try and keep everything reproducible.

The zero images, like your example, all seem to be great (assuming the first element in the tensor array is the probability for zero). I'm simply adding print(p) (and changing the weights path to a 100 epoch run which appeared sane, and the reference image path) to your example:

```
0/10.png (the example)
tensor([[9.99698e-01, 3.47891e-13, 6.68257e-07, 2.14603e-07, 1.22030e-09, 5.41396e-06, 1.59597e-05, 1.32416e-09, 2.59506e-06, 2.77415e-04]], grad_fn=<SoftmaxBackward0>)

0/2765.png
tensor([[9.99682e-01, 1.09383e-12, 3.36422e-07, 6.79437e-08, 9.11359e-10, 3.35350e-07, 1.33463e-05, 8.36255e-10, 1.23339e-06, 3.03032e-04]], grad_fn=<SoftmaxBackward0>)

0/2873.png
tensor([[9.91960e-01, 9.60877e-11, 8.98753e-05, 2.59980e-06, 1.29499e-07, 1.32375e-04, 4.13297e-04, 7.66207e-07, 1.32123e-04, 7.26902e-03]], grad_fn=<SoftmaxBackward0>)
```

The zero images seem perfect (as is your example in the code), but once I start trying numbers outside of zero, the results become wacky. I don't know if I'm misunderstanding what p's tensor array means, but if that's the case, I'd love to understand it!

```
5/654.png
tensor([[3.84575e-04, 6.68715e-10, 1.92637e-02, 4.27156e-02, 7.48924e-08, 9.29740e-02, 2.03506e-02, 4.00156e-05, 4.03519e-03, 8.20236e-01]], grad_fn=<SoftmaxBackward0>)

5/1089.png
tensor([[4.34444e-08, 6.27003e-08, 8.43125e-02, 2.62402e-02, 6.90831e-07, 7.08452e-01, 6.03361e-03, 2.68691e-04, 1.77312e-04, 1.74515e-01]], grad_fn=<SoftmaxBackward0>)

5/1299.png
tensor([[6.99778e-05, 2.58436e-05, 9.78765e-01, 1.58580e-03, 2.40881e-06, 6.72489e-03, 1.03913e-02, 1.32892e-03, 1.16350e-04, 9.89814e-04]], grad_fn=<SoftmaxBackward0>)
```

My assumption, although maybe incorrect, is that every time the array will be in order of the number it should correspond to, or at least that it's going to be in the same order every run. So while that makes a lot of sense for the test/0/*.png results, it looks like it's guessing 9.29740e-02, 7.08452e-01, and 6.72489e-03 for test/5/\*.png. I picked these arbitrarily, and I don't think I should so easily be able to find incorrect guesses with a 99.9% accuracy training.

My results for test/9/\*.png are super strange as well. Again, just picking arbitrarily, these are not the "worst" results.

```
9/212.png
tensor([[7.46878e-08, 5.67505e-09, 3.17187e-02, 5.00519e-06, 4.46211e-06, 7.69858e-05, 9.68190e-01, 1.43383e-11, 4.67588e-06, 8.92458e-08]], grad_fn=<SoftmaxBackward0>)

9/394.png
tensor([[1.69932e-05, 4.14017e-07, 1.43429e-03, 4.05658e-05, 4.56345e-05, 1.20660e-03, 9.97245e-01, 4.63401e-10, 1.01925e-05, 7.92591e-07]], grad_fn=<SoftmaxBackward0>)

9/521.png
tensor([[5.65174e-07, 2.78747e-07, 7.96038e-03, 4.80270e-05, 1.17674e-05, 5.70881e-04, 9.90506e-01, 1.96916e-09, 9.00627e-04, 1.12187e-06]], grad_fn=<SoftmaxBackward0>)

```

Again, assuming it goes 0,1,2,3,4,5,6,7,8,9 ... it seems super confident these nines are sixes. I understand that a 9 could look like a 6 based on its orientation, but then to give such low probabilities for a nine seems bizarre. I also don't understand how it could get a 99%+ on the training results.

My guess is that my assumption is wrong, and that these results do not go in any predictable order. If that is the case, how do I map the tensor array in p, to the number it's guessing?

**Comment by glenn-jocher** [comment]
@CrucialDrew thanks for the detailed analysis! Yes I am able to reproduce some inference workflow irregularities as well. This may be due to different preprocessing steps in the train/val loop vs the inference Usage example. I suspect the inference Usage example may need updating. I don't have time to investigate fully right now but I'll add a TODO here to follow up this week.

Don't worry about the model accuracy, the validation results are correct. The likely failure modes may be model saving/loading or inference preprocessing as mentioned above.

**Comment by glenn-jocher** [comment]
TODO: verify classifier inference workflows on MNIST classes 1-9

**Comment by glenn-jocher** [comment]
@CrucialDrew I discovered a bug in classifier.py. Inference usage example was reversing vertical dimension instead of color dimension, so all images were presented to model upside-down. For this reason 0 and 3 worked but not 9 or 4 for example.

I've implemented a fix and created a new classify() function to make inference easier. Usage example is updated as well.

```python
# YOLOv5 🚀 by Ultralytics, GPL-3.0 license
"""
Train a YOLOv5 classifier model on a classification dataset

Usage-train:
    $ python path/to/classifier.py --model yolov5s --data mnist --epochs 5 --img 128 --adam

Usage-inference:
    from classifier import *

    model = torch.load('path/to/best.pt', map_location=torch.device('cpu'))['model'].float()
    files = Path('../datasets/mnist/test/9').glob('*.png')
    for f in list(files[:10]):
        classify(model, size=128, file=f)
"""
```


Results now on MNIST 9 and 4:
```python
from classifier import *
model = torch.load('best.pt', map_location=torch.device('cpu'))['model'].float()
files = list(Path('../datasets/mnist/test/9').glob('*.png'))
for f in files[:10]:
    classify(model, size=128, file=f)
    
../datasets/mnist/test/9/4968.png prediction: 9 (1.00)
../datasets/mnist/test/9/3791.png prediction: 9 (1.00)
../datasets/mnist/test/9/1192.png prediction: 9 (0.99)
../datasets/mnist/test/9/3008.png prediction: 9 (1.00)
../datasets/mnist/test/9/4015.png prediction: 9 (0.67)
../datasets/mnist/test/9/3034.png prediction: 9 (1.00)
../datasets/mnist/test/9/7246.png prediction: 9 (1.00)
../datasets/mnist/test/9/3587.png prediction: 9 (0.96)
../datasets/mnist/test/9/9733.png prediction: 9 (1.00)
../datasets/mnist/test/9/7736.png prediction: 9 (0.99)


from classifier import *
model = torch.load('best.pt', map_location=torch.device('cpu'))['model'].float()
files = list(Path('../datasets/mnist/test/4').glob('*.png'))
for f in files[:10]:
    classify(model, size=128, file=f)
    
../datasets/mnist/test/4/360.png prediction: 4 (0.85)
../datasets/mnist/test/4/9525.png prediction: 4 (1.00)
../datasets/mnist/test/4/4001.png prediction: 4 (0.99)
../datasets/mnist/test/4/2464.png prediction: 4 (1.00)
../datasets/mnist/test/4/3752.png prediction: 4 (1.00)
../datasets/mnist/test/4/1145.png prediction: 4 (0.99)
../datasets/mnist/test/4/8613.png prediction: 4 (1.00)
../datasets/mnist/test/4/7520.png prediction: 4 (0.94)
../datasets/mnist/test/4/4029.png prediction: 4 (0.95)
```

**Comment by glenn-jocher** [comment]
@CrucialDrew removing TODO following fix. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by glenn-jocher** [comment]
@hamedmh @CrucialDrew also note that new images are logged to runs/train/exp by default now when training a classifier. Note left-right flip is enabled by default, but MNIST does not need this.

### Train images
![image](https://user-images.githubusercontent.com/26833433/146684676-cd9e0719-a523-4b5e-ac3e-ce3e6f9e1c73.png)


### Test results (true-predicted)
![image](https://user-images.githubusercontent.com/26833433/146684669-37757afa-7e32-4400-9027-dc0830c375e1.png)

**Comment by hamedmh** [comment]
Thanks @glenn-jocher !
