### ISSUE TITLE
Provide hyperparameter YAML to reproduce results

### ISSUE THREAD

**Issue by Karol-G** [ultralytics/yolov5#5097]
Hi,

I would like to reproduce your results for the MSCOCO dataset (coco.yaml) by training from scratch. 
Would you be so kind to provide the hyperparameter YAML file for YOLOv5s, YOLOv5m, YOLOv5l and YOLOv5x (maybe even for the P6 ones too)? 
Further, could you also provide the used batch size, image size or just the entire training command with all the parameters that are not in the hyperparameter YAML?
To get the mAP scores in [pretrained checkpoints](https://github.com/ultralytics/yolov5#pretrained-checkpoints), did you use additional training data or exclusively MSCOCO 2017 data?

Best
Karol

**Comment by glenn-jocher** [comment]
@Karol-G all release v5.0 models were trained with hyp.scratch-p6.yaml:
https://github.com/ultralytics/yolov5/blob/48b00dbc0df672837a4af0a185210304b778dd44/data/hyps/hyp.scratch-p6.yaml#L1-L34

**Comment by glenn-jocher** [comment]
@Karol-G also you can reproduce instructions are in the README under 'Training'

**Comment by Karol-G** [comment]
Thanks a lot!
