### ISSUE TITLE
During Evolve: CUDA Error: Misaligned Address at Arbitrary Point

### ISSUE THREAD

**Issue by tomatopuree** [ultralytics/yolov5#5101]
I am running this training script.

python train.py --img 375 --batch 4 --epochs 10 --data my_yaml_with_18_classes.yaml --weights yolov5x.pt --evolve

The evolve function works great for about 2-8 models. Then I get this error.

![cuda1](https://user-images.githubusercontent.com/688831/136567909-3db1ebf6-0306-414d-8319-b6737f5e2c49.PNG)

Looking online for possible causes of this, I see that 
- mismatched label dims and output dims
- 1 indexed labels or presence of -1 in labels

might be causing this issue.

I have neither of these issues since
- I have the correct number of classes specified in my yaml file
- All indexes are output by Roboflow, and they are 0 indexed and perfect
- The models completely train multiple times perfectly before this error pops up and stops training anyways.

Is it possible to resume an --evolve run? Why might this CUDA error happening?

**Comment by erb13020** [comment]
You may want to consider lowering your batch size.

**Comment by tomatopuree** [comment]
> You may want to consider lowering your batch size.

are you positing that there is memory leak? then why does it happen sometimes training the second model, and sometimes the eight.

additionally i'm working with 24gbs of vram

**Comment by glenn-jocher** [comment]
@tomatopuree 👋 Hello! Thanks for asking about **resuming evolution**. I'm not sure where the CUDA error you are seeing may originate. Often times resource constrained environments may produce errors in a non-deterministic fasion, so you should ensure sufficient resources (CPUs, RAM, CUDA memory) for your task. To remove environmental sources of error I would recommend training in our Docker image.

Resuming YOLOv5 🚀 evolution is a bit different than resuming a normal training run with `python train.py --resume`. If you started an evolution run which was interrupted, or finished normally, and you would like to continue for additional generations where you left off, then you pass `--resume` and specify the `--name` of the evolution you want to resume, i.e.:


## Start Evolution

Assume you evolve YOLOv5s on COCO128 for 2 epochs for 3 generations:
```shell
python train.py --epochs 10 --data coco128.yaml --weights yolov5s.pt --evolve 3
```
If this is your first evolution a new directory `runs/evolve/exp` will be created to save your results.
```shell
# ├── yolov5
#     └── runs
#         └── evolve
#             └── exp  ← evolution saved here
```

## Start a Second Evolution

Now assume you want to start a completely separate evolution: YOLOv5s on VOC for 5 epochs for 3 generations. You simply start evolving, and your new evolution will again be logged to a new directory `runs/evolve/exp2`:
```shell
python train.py --epochs 5 --data VOC.yaml --weights yolov5s.pt --evolve 3
```

You will now have two evolution runs saved:
```shell
# ├── yolov5
#     └── runs
#         └── evolve
#             ├── exp  ← first evolution (COCO128)
#             └── exp2  ← second evolution (VOC)
```

Notebook example: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
<img width="1396" alt="Screenshot 2021-09-15 at 12 23 13" src="https://user-images.githubusercontent.com/26833433/133416922-59a3e9f5-2630-4875-9c64-a982e312b400.png">


## Resume an Evolution

If you want to resume the first evolution (COCO128 saved to `runs/evolve/exp`), then you use the same exact command you started with plus `--resume --name exp`, passing the **additional** number of generations you want, i.e. `--evolve 30` for 30 more generations:
```shell
python train.py --epochs 10 --data coco128.yaml --weights yolov5s.pt --evolve 30 --resume --name exp
```
Evolution will run for an additional 30 generations and all new results will be added to the existing `runs/evolve/exp/evolve.csv`. 

Good luck and let us know if you have any other questions!

**Comment by tomatopuree** [comment]
Hello @glenn-jocher 

This is extremely clear. Many thanks.
