### ISSUE TITLE
Distance between detected objects

### ISSUE THREAD

**Issue by samahwaleed** [ultralytics/yolov5#5102]
## ❔Question

I have done object detection using yolov5 on my image dataset and I saved the results in txt file. The txt file has labeled, bbox coordination, and score for each detected object in the image. My question is how we can calculate the distance between detected objects.

Thanks

**Comment by PaulCvasa** [comment]
any answer found? having the same question..

**Comment by samahwaleed** [comment]
by calculating the centroid. Look at this:

https://stackoverflow.com/questions/41982006/compute-the-centroid-of-a-rectangle-in-python
