### ISSUE TITLE
classifier.py

### ISSUE THREAD

**Issue by sekisek** [ultralytics/yolov5#5103]
Sorry for all the questions but the detection part with classification is not clear to me.

after training with classifier branch (mnist) am I suppose to load the model like this in the detect?

`    if classify:
        modelc = load_classifier(name='resnet101', n=2)  # initialize
        modelc.load_state_dict(torch.load('weights/resnet101.pt', map_location=device)['model']).to(device).eval()
`
because using it as the first model weight is not working also

**Comment by glenn-jocher** [comment]
@sekisek I'm not sure what you're asking exactly. YOLOv5 uses an SGD optimizer with cosine or linear LR schedulers. You can learn more here: https://pytorch.org/docs/stable/optim.html
