### ISSUE TITLE
WARNING: Dataset not found.

### ISSUE THREAD

**Issue by danielsoy** [ultralytics/yolov5#5107]
Hello ppl, This yolov5 notebook, gives me this errror:

WARNING: Dataset not found, nonexistent paths: ['/content/valid/images']

I can see the images and its labels, here:/content/datasets/template_yolov5_API-1/valid/images

But the execution of the notebook, is stuck at step 3, because it is unzipping the valid images and labels
in one directory, but then tries to retrieve them, from another nonexistent location.

https://colab.research.google.com/github/roboflow-ai/yolov5-custom-training-tutorial/blob/main/yolov5-custom-training.ipynb

## Additional context
![image](https://user-images.githubusercontent.com/48926149/136639496-1d45e4cf-9f12-4b00-afe3-8a36fd739fe4.png)

![image](https://user-images.githubusercontent.com/48926149/136639514-32b1ceeb-9fe7-451b-8bf9-8737749870ec.png)

**Comment by glenn-jocher** [comment]
@danielsoy hi, thanks for raising this issue! Is there any additional information you can provide to help us reproduce the problem?

I'll loop in our Roboflow colleague @Jacobsolawetz who might be able to help.

**Comment by danielsoy** [comment]
Hi Glenn, thanks for your answer.

The issue will pop running the jupyter netbook that is linked in this
youtube video:
Custom Training Tutorial and Notebook
https://www.youtube.com/watch?v=x0ThXHbtqCQ&t=1s&ab_channel=Roboflow.

On the comments section, you can read the comments from other guys, with
the same problem.

**Comment by danielsoy** [comment]
I could make it work by editing the data.yaml file to make it point
to the path where the needed files are located.

In my case it is:
train: ../datasets/anotado-2/train/images
val: ../datasets/anotado-2/valid/images

nc: 2
names: ['bad', 'ok']

It is not a professional solution, because i need to edit the file, for every new dataset
with a different name than anotado-2....

At this moment, the model is being trained, lets see what happens...

**Comment by glenn-jocher** [comment]
@danielsoy great, thanks for the feedback! I'll pass it on to Roboflow to see if there's some fixes that can be made.

**Comment by Jacobsolawetz** [comment]
@danielsoy thanks for the info, this will help us debug speedily. I'll post here when the fix is alive.

**Comment by Jacobsolawetz** [comment]
@danielsoy @glenn-jocher the fix for this is live - long story short, I had forgotten to push some fixes to the `roboflow` pip package after I had been adapting dataset download to some more models

**Comment by glenn-jocher** [comment]
@Jacobsolawetz thanks! 

@danielsoy can you try again after a new `pip install -U roboflow` and see if this solves the problem for you?

**Comment by danielsoy** [comment]
Its well known that **Robooflow** crew delivers!
 
I will try pip i... n see how it goes, thanks again.

**Comment by danielsoy** [comment]
Yes, it works! 
All the way, down to the end of the notebook now.

Kudos to Jacobsolawetz  and glenn-jocher !🤓

**Comment by ghost** [comment]
Hi guys, same problem happened to me and pip install -U roboflow is not working.

**Comment by Emyyr** [comment]
I think it is about roboflow train-valid-test split. pip install -U roboflow not working. Maybe you can try create new dataset folder after download on roboflow.

**Comment by salehghulamqasim** [comment]
The problem with me was i didnt have any validation images so roboflow maybe didnt create path for it somehow but it would show inside data.yaml and the notebook would say dataset not found.

what i did is i tried different dataset which had validation images and it worked like a charm

so in short the problem was **i didnt have the folder valid/images since i didnt even have any validation images in roboflow at first place, fix that , add some validation images then export and try**


### GOODLUCK

**Comment by glenn-jocher** [comment]
@salehghulamqasim thanks for sharing your experience and workaround! It's great to hear that you were able to identify the issue and resolve it. If you have any further questions or need assistance, feel free to ask. Good luck with your continued work on YOLOv5!

**Comment by notanadrian** [comment]
i had the same problem dataset not found but when i check the directory in the google collab, the images file are there. btw im using yolov7

**Comment by glenn-jocher** [comment]
@notanadrian it sounds like there might be a mismatch between the expected directory path in your code and the actual location where your dataset resides. This is a common issue that can occur for various reasons, such as incorrect dataset path specifications or changes in the directory structure.

For YOLOv7, which is a different repository and not directly related to the Ultralytics YOLOv5 project, I recommend double-checking the dataset path specified in your training script or notebook. Ensure that it exactly matches the location of your dataset in Google Colab. You might also need to adjust the dataset path in any configuration files or scripts you are using.

If you're still encountering issues, consider reaching out to the YOLOv7 repository maintainers or community for more specific guidance related to YOLOv7. Good luck with your project!
