### ISSUE TITLE
Yolo error when trying to run yolov5 on hetson agx xavier.

### ISSUE THREAD

**Issue by zentorno365** [ultralytics/yolov5#511]
## ❔Question
Hello I have installed all the requirements and tried to inference yolov5 on the jetson agx xavier. I get the following error. I also couldn't  find anything related to this  online.

![20200725_014236](https://user-images.githubusercontent.com/68109767/88447966-66d0bd80-ce6b-11ea-90bf-74f4f46d1dfd.jpg)

**Comment by glenn-jocher** [comment]
@krishnam3065 make sure you have the very latest code, as the repo changes every day. git pull or reclone and try again, and if that doesn't work you can try to run from docker, which AutoBuilds and is always up to date.

- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)
