### ISSUE TITLE
Reporting FPS

### ISSUE THREAD

**Issue by karl-gardner** [ultralytics/yolov5#5113]
Hello Glenn et. al,

I see that the detect.py module uses a for loop:

![image](https://user-images.githubusercontent.com/91646805/136676509-a73c645e-67a3-4d45-be1b-4dee1fbebf3f.png)

which goes through each image separately and then runs the prediction on the image:

![image](https://user-images.githubusercontent.com/91646805/136676608-9227384f-a4b3-4de4-b1aa-49627e127ae0.png)

Since this sends each image and prediction in separately (without using an array containing all images together like training) the average timing can be used in the FPS calculation (as 1/mean(preprocessing + inference + nms)) correct?  I can just explain this in the report?  I believe this is the output that it gives from the detect.py module.

Thanks,

Karl Gardner

**Comment by glenn-jocher** [comment]
@kgardner330 yes 1 / seconds will give you FPS. You're free to choose what you include in the time, we don't have any specific guidance here. 

In other places I've seen this as 1 / inference_time, or in our [iDetection app](https://apps.apple.com/us/app/idetection/id1452689527) we provide the achieved real-world FPS, which maxes out at 30 if the source is arriving at 30 FPS.

**Comment by karl-gardner** [comment]
@glenn-jocher,

This is interesting I did not know there was an app for this.  Is this only available on app store not android?  Also, is it a lower FPS since it is used on a phone not a computer?

Karl

**Comment by glenn-jocher** [comment]
@kgardner330 oh, I thought it was pretty obvious there was an app by looking at the README no?

Also not sure what you mean by lower FPS, YOLOv5 runs faster on my iPhone than on my Macbook.

**Comment by glenn-jocher** [comment]
@kgardner330 coming to Android too as part of Ultralytics HUB at https://ultralytics.com/hub, should be out soon.
