### ISSUE TITLE
Minimum Size of Box Label in Training Dataset 

### ISSUE THREAD

**Issue by aseprohman** [ultralytics/yolov5#5115]
## ❔Question
Hello @glenn-jocher 
is there any minimum requirement size of box label in training dataset after network is resize to "img-size" setup parameter in training data process ? I've read about anchor method in some tutorial and it will affect in detection and accuracy if box size in training dataset is below minimum anchor config model. maybe in yolov5 you have set the minimum pixel that can detect depend on default anchor configuration in every yolov5 models ?

**Comment by glenn-jocher** [comment]
@aseprohman yes there are instance constraints on the training and NMS sides. Training boxes must pass these constraints:
https://github.com/ultralytics/yolov5/blob/4a6dfffdaa9300703d946c24833c87dace0d099c/utils/augmentations.py#L273-L278

NMS candidates must pass these constraints:
https://github.com/ultralytics/yolov5/blob/4a6dfffdaa9300703d946c24833c87dace0d099c/utils/general.py#L622-L629
