### ISSUE TITLE
detect.py

### ISSUE THREAD

**Issue by xinsuinizhuan** [ultralytics/yolov5#5117]
File "xxx/yolov5_v5.0/detect.py", line 288, in parse_opt
    opt.imgsz *= 2 if len(opt.imgsz) == 1 else 1  # expand
TypeError: object of type 'int' has no len()

![Uploading 图片.png…]()

**Comment by glenn-jocher** [comment]
@xinsuinizhuan you probably modified the argparser default. This argument is a list, not an int.

**Comment by glenn-jocher** [comment]
@xinsuinizhuan you can pass an image size from the command line, i.e.:
```
python detect.py --img 320
```

**Comment by xinsuinizhuan** [comment]
OK。it works,now.thankyou!
