### ISSUE TITLE
tensorrt

### ISSUE THREAD

**Issue by 123456789mojtaba** [ultralytics/yolov5#512]
Hi.
thanks because of your repo.
Can you pytorch_onnx to tensorrt in your yolov5 github repo?
Ty

**Comment by glenn-jocher** [comment]
@123456789mojtaba closing as duplicate of existing issues. Please do some research before raising new issues.

https://github.com/TrojanXu/yolov5-tensorrt
https://github.com/wang-xinyu/tensorrtx
