### ISSUE TITLE
Submit evaluation results to COCO test-dev benchmark on Papers With Code

### ISSUE THREAD

**Issue by Karol-G** [ultralytics/yolov5#5122]
Hi,

could you submit the evaluation results for your different models to the COCO test-dev benchmark on Papers With Code.
https://paperswithcode.com/sota/object-detection-on-coco

The original COCO test-dev benchmark website is a bit outdated and it seems people submit their results to Papers With Code instead. 

Best
Karol

**Comment by glenn-jocher** [comment]
We might need a paper for papers with code.

**Comment by Karol-G** [comment]
It seems you are correct. Do you intend to publish a paper on YOLOv5 anytime?

**Comment by glenn-jocher** [comment]
@Karol-G yes, we are targeting a paper to arxiv by pytorch dev day, December 1st.

**Comment by Karol-G** [comment]
Cool :)
