### ISSUE TITLE
Faster detect.py

### ISSUE THREAD

**Issue by sandstorm12** [ultralytics/yolov5#5123]
Hi, I have been working with the yolov5m model on v100 GPU, and though the inference speed of this model is around 360 fps, the detect.py script is working at around 60 fps.

I'm almost sure that the low fps on video is related to sequential loading of video and inference. I suggest re-writing the detect.py for video input to make the video loading and inference parallel.

P.S. I'm interested to implement it myself. If you think this is a good idea, just let me know :)

**Comment by glenn-jocher** [comment]
@sandstorm12 yes this is an interesting idea. We implement multithreaded loading and inference for streaming sources in the `LoadStreams()` dataloader, which works very well. You could use this as a starting point to expand this capability to image and video inference in `LoadImages()`:

https://github.com/ultralytics/yolov5/blob/9d75e42f9811718a1f5a821f2425484524df074f/utils/datasets.py#L282-L368

**Comment by sandstorm12** [comment]
Great. I'll submit a pull request in a few days.
