### ISSUE TITLE
What is the difference between the new r6 models and the regular yolo models?

### ISSUE THREAD

**Issue by hdnh2006** [ultralytics/yolov5#5128]
## ❔Question
I have seen the repo has new weights with the prefix "r6". I loaded the model `r6yolov5s.pt` and I can see using `model.names` the classes are the same as coco models.

Please, could you give an information about them?

I was searching over the issues but I could not find any issue realted.

Thanks in advance.

**Comment by glenn-jocher** [comment]
@hdnh2006 these are release v6.0 models which we are hosting on the current release assets for easy testing, i.e. `python val.py --weights r6yolov5s.pt` will autodownload. 

The v6.0 release is tomorrow October 12th, then these models will be hosted under the new release with the same names as the current ones, i.e. yolov5s.pt.
