### ISSUE TITLE
Qualitative comparison between v1.0 and v2.0

### ISSUE THREAD

**Issue by farleylai** [ultralytics/yolov5#513]
It seems like an empirical qualitative comparison/review would be necessary despite higher mAP results.
In the following, `yolov5x-v2.0` either misses or makes a wrong prediction in an [abseiling video](https://www.youtube.com/watch?v=GwlcmI36imo&t=228s) for many frames from the kinetics video dataset with conf_thres=0.35, iou_thres=0.5 and img_size=672 for both v1.0 and v2.0. 
Nonetheless, the validation results are as claimed in v2.0 release. 
Any ideas?

v1.0 (8f7e11dcef)
![frame_0002](https://user-images.githubusercontent.com/158540/88450317-eecead00-ce02-11ea-96a7-671f8b5c5f99.jpg)
![frame_0041](https://user-images.githubusercontent.com/158540/88450128-87642d80-ce01-11ea-9289-9dc5f957c7f5.jpg)

v2.0
![frame_0002](https://user-images.githubusercontent.com/158540/88450327-04dc6d80-ce03-11ea-8e4c-ec44baa5cb0a.jpg)
![frame_0041](https://user-images.githubusercontent.com/158540/88450135-8df2a500-ce01-11ea-960c-97bbc3b30f11.jpg)

All results in 50 frames:
- original: [GwlcmI36imo_000127_000137.zip](https://github.com/ultralytics/yolov5/files/4974977/GwlcmI36imo_000127_000137.zip)
- v1.0: [yolov5x-v1-output.zip](https://github.com/ultralytics/yolov5/files/4974973/yolov5x-v1-output.zip)
- v2.0: [yolov5x-v2-output.zip](https://github.com/ultralytics/yolov5/files/4974974/yolov5x-v2-output.zip)

Same command line:
```sh
python detect.py --source GwlcmI36imo_000127_000137/ --weights yolov5x.pt --conf 0.35 --iou-thres 0.5 --img-size 672
```

**Comment by glenn-jocher** [comment]
@farleylai anecdotal results are interesting to look at, but the reason mAP is used is to fly above the noise.

**Comment by chihyuwang** [comment]
Below is the result of the new version of yolov5s, it seems that the new version is not better than the old version
![zidane](https://user-images.githubusercontent.com/25482742/88458941-face7380-cec3-11ea-9ba9-8faaecbd9621.jpg)

**Comment by glenn-jocher** [comment]
@chihyuwang yes that is correct. The new yolov5s mAP is 36.1, vs the old 36.6.

**Comment by chihyuwang** [comment]
It seems that the values of speed and FPS of v1.0 and v2.0 are not changed.
https://github.com/ultralytics/yolov5/releases

**Comment by glenn-jocher** [comment]
@chihyuwang yes that is correct. The architecture is the same, the construction is a bit different and the loss function is modified a bit to better balance the different outputs. The changes tend to benefit the larger models at the expense of the smallest model.
