### ISSUE TITLE
CoreML example with SwiftUI

### ISSUE THREAD

**Issue by Updrones-SimonRegner** [ultralytics/yolov5#5130]
## Is there any good example how to work with the CoreML model?
I can not get a SwiftUI App to work with the exported model. 
Does anyone have a good example project or can tell my you to handle the Output MultiArrays? 

thank you for the help

**Comment by pytholic** [comment]
@Updrones-SimonRegner Hi mate. I kind of found this repos and trying to work with it:
https://github.com/Ma-Dan/YOLOv3-CoreML

However, I am facing some issues which I mentioned in the following issue. Take a look please.

https://github.com/ultralytics/yolov5/issues/5157

**Comment by Leon0402** [comment]
Just for reference (you both found it already): https://github.com/dbsystel/yolov5-coreml-tools 

Here is a complete export script to make it work with the official apple examples. Although it needs some more work to make it compatible with latest releases of yolov5 and also more custom models (for example different images sizes). 
It should work well for yolov5 release 2,3,4 as well as customed trained models based on those with different number of classes for instance.
