### ISSUE TITLE
using yolov5 and deepsort without internet access

### ISSUE THREAD

**Issue by Riad123321** [ultralytics/yolov5#5134]
## ❔Question
Hi
iam trying to use yolov5 with deepsort model without internet access but when i put my custom yolov5 weights path it will download pretrained yolov5 weights from internet and i don't know how to prevent that  i think the problem in attempt_load and attempt_download function can anyone help me

**Comment by iceisfun** [comment]
Have you looked at building a docker image containing all the resources required?

Start with the pre build ultralytics/yolov5:latest and add anything you need.

You can test the container with --net none to make sure it is not accessing a network, I pre download all required resources when building my containers so they don't need internet access to start up.

**Comment by glenn-jocher** [comment]
@Riad123321 model download attempts are only made if assets are not found locally. 

Also, why are you calling models that don't exist locally in the first place?
