### ISSUE TITLE
Runner-up Classes & Confidences

### ISSUE THREAD

**Issue by EricFordham** [ultralytics/yolov5#5135]
## ❔Question
Hello,

Is it possible for YOLO to output all possible classes for each object along with their confidences, not just the object with the highest confidence? For example:

![image](https://user-images.githubusercontent.com/91271373/136837276-bf08456b-4f1a-4181-a0e4-a4a6914f5715.png)

**Comment by glenn-jocher** [comment]
@EricFordham off the shelf, no. The NMS function strips all of this information, so you'd have to customize it to output the additional info you need.
