### ISSUE TITLE
Difference in pt and onnx exported model

### ISSUE THREAD

**Issue by tea1528** [ultralytics/yolov5#5137]
## ❔Question
Why are the predictions between original pytorch and exported onnx model different?

## Additional context
![zidane](https://user-images.githubusercontent.com/22886085/136854163-d113ec43-a576-4de2-95b5-bc0861b94f16.PNG)

I am using the provided colab for the inference.

I used `!python export.py --weights yolov5s.pt` for export and above command for detect.py. As you can see, the confidence scores are different from the expected results. In additional, I checked the bounding box results and 2 out of 4 bboxes have slightly different box coordinates.

Is this expected behavior?

**Comment by glenn-jocher** [comment]
@tea1528 ONNX models use square inference unless you export with --dynamic. PyTorch models use rectangular inference.

Beyond that I'm not sure what differences you mean as you haven't shown both results side by side.

**Comment by tea1528** [comment]
![zidane_orig](https://user-images.githubusercontent.com/22886085/136869029-0be806f8-b736-4bd0-b8de-5f72e30eefc8.PNG)

This is the inference result of the original PyTorch model. As you can see, the confidence scores vary. 

In addition, the bbox predictions from labels directory are:

PyTorch
27 0.786719 0.502778 0.0328125 0.161111
0 0.471875 0.629167 0.765625 0.713889
27 0.371875 0.797917 0.065625 0.390278
0 0.741406 0.522222 0.310937 0.925

ONNX
27 0.786719 0.502778 0.0328125 0.161111
0 0.473828 0.627778 0.766406 0.711111
27 0.371875 0.797917 0.065625 0.390278
0 0.741016 0.520139 0.311719 0.918056

I tried exporting onnx with --dynamic but the results are same. I am running everything on the provided colab so I should have the same dependencies as everyone else. Can you check if it's the same on your side too?

**Comment by glenn-jocher** [comment]
@tea1528 you can see the input sizes are different in your screenshots.

**Comment by tea1528** [comment]
Okay, by manually changing image loading to `LoadImages(source, img_size=imgsz, stride=stride, auto=False)`, I get same results for both pt and onnx. 

Thanks!

**Comment by glenn-jocher** [comment]
Great!
