### ISSUE TITLE
http stream

### ISSUE THREAD

**Issue by Yousef-Alhattab** [ultralytics/yolov5#5140]
## ❔Question
I tried to pass http in the inference, but it gives me a message which says:  Failed to open http://IPAddress/browse/index.asp?id=1634011018613

I passed it like this:
python detect.py --source http://IPAddress/browse/index.asp?id=1634011018613

what is the prob here, please?

thanks a lot

**Comment by glenn-jocher** [comment]
@urbansound8K you might need to enclose it in quotes (see README examples). Your stream address could also have problems.
