### ISSUE TITLE
save model weight with model.state_dict(),inference angin, Can't get the right results

### ISSUE THREAD

**Issue by Nr-rN** [ultralytics/yolov5#5148]
## ❔Question
In train.py line 373:

` ckpt = {'epoch': epoch,
                            'best_fitness': best_fitness,
                            'model': deepcopy(de_parallel(model)).half(),
                             'ema': deepcopy(ema.ema).half(),
                            'updates': ema.updates,
                            'optimizer': optimizer.state_dict(),
                            'wandb_id': loggers.wandb.wandb_run.id if loggers.wandb else None}`
`# Save last, best and delete`
`     torch.save(ckpt, last)`

change:
`ckpt = {'epoch': epoch,
                            'best_fitness': best_fitness,
                           'model': model.state_dict(),
                           'ema': deepcopy(ema.ema).half(),
                           'updates': ema.updates,
                           'optimizer': optimizer.state_dict(),
                           'wandb_id': loggers.wandb.wandb_run.id if loggers.wandb else None}`
                `# Save last, best and delete`
               ` torch.save(ckpt, last)`
 `

Use the code to inference(detect):
`from models.yolo import Model`
   ` ......`
   ` #loading model`
   ` model = Model().to(device).eval()`
    `ckpt = torch.load('xxxxxx.pt')`
    `model.load_state_dict(ckpt['model'], strict=False)`
    `....`
    `pred = model(img)` 

**I can't get rigtht results 'pred'  by dectct.py,
I don't know where the problem is,
I guess:
    1. I don't have all the parameters needed to save the model,only state_dict can't be reasoned inference
    2. load model for error rule**

**Comment by glenn-jocher** [comment]
You don't need to modify any code to use detect.py, you just train a model and then use it directly:

```bash
python train.py
python detect.py --weights runs/train/exp/weights/best.pt
```

**Comment by Nr-rN** [comment]
@glenn-jocher 
**Thank you for answering my question, but I failed to express my question clearly.**
i want use `ckpt  = {.... ,'model':model.state_dict(), .....}` to save model 
and load by 
`model = Model() `
`model.load_state_dict(torch.load(ckpt))`

because in `detect.py` line 82 `attempt_load(weights, map_location=device)`
if save model with `ckpt  = {.... ,'model': deepcopy(de_parallel(model)).half(), .....}` 
weight will contain the serialized data is bound to the specific classes and the exact directory structure used

I get Erroe:
> File "/opt/det.py", line 3, in
model = torch.load('./weights/best.pt',map_location='cpu')
File "/home/tian/.conda/envs/jiqi/lib/python3.6/site-packages/torch/serialization.py", line 368, in load
return _load(f, map_location, pickle_module)
File "/home/tian/.conda/envs/jiqi/lib/python3.6/site-packages/torch/serialization.py", line 542, in _load
result = unpickler.load()
ModuleNotFoundError: No module named 'models'

When I see the same problem:
[https://github.com/pytorch/pytorch/issues/18325](url)
i user `torch.jit.trace(model,torch.tensor(torch.rand(size=(1,3,640,640)))`
but it not work
ERROR with:

>TracingCheckError: Tracing failed sanity checks!
ERROR: Graphs differed across invocations!
	Graph diff:
		  graph(%self.1 : __torch__.models.yolo.Model,
		        %x : Tensor):
		    %2 : __torch__.torch.nn.modules.container.Sequential = prim::GetAttr[name="model"](%self.1)
		    %3 : __torch__.models.yolo.Detect = prim::GetAttr[name="24"](%2)
		    %4 : __torch__.torch.nn.modules.container.Sequential = prim::GetAttr[name="model"](%self.1)
		    %5 : __torch__.models.common.C3 = prim::GetAttr[name="23"](%4) 
...
...
...
Comparison exception: 	expected tensor shape torch.Size([1, 1, 40, 40, 2]) doesn't match with actual tensor shape torch.Size([])!

**now,i use this method ,like:** 
>m = MyModule()
> m.state_dict()
`OrderedDict([('l0.weight', tensor([[ 0.1400, 0.4563, -0.0271, -0.4406],
                                   [-0.3289, 0.2827, 0.4588, 0.2031]])),
             ('l0.bias', tensor([ 0.0300, -0.1316])),
             ('l1.weight', tensor([[0.6533, 0.3413]])),
             ('l1.bias', tensor([-0.1112]))])`

> torch.save(m.state_dict(), 'mymodule.pt')
> m_state_dict = torch.load('mymodule.pt')
> new_m = MyModule()
>new_m.load_state_dict(m_state_dict)

**When I use the new loading method for reasoning, the result is worse than the original loading method**

**Comment by glenn-jocher** [comment]
@Nr-rN we don't assist in debugging custom code. Inference examples are shown for detect.py and PyTorch Hub in the README.

If you find a reproducible bug in the unmodified repository code please raise a separate bug report.

**Comment by zcunyi** [comment]
> @glenn-jocher **Thank you for answering my question, but I failed to express my question clearly.** i want use `ckpt = {.... ,'model':model.state_dict(), .....}` to save model and load by `model = Model() ` `model.load_state_dict(torch.load(ckpt))`
> 
> because in `detect.py` line 82 `attempt_load(weights, map_location=device)` if save model with `ckpt = {.... ,'model': deepcopy(de_parallel(model)).half(), .....}` weight will contain the serialized data is bound to the specific classes and the exact directory structure used
> 
> I get Erroe:
> 
> > File "/opt/det.py", line 3, in
> > model = torch.load('./weights/best.pt',map_location='cpu')
> > File "/home/tian/.conda/envs/jiqi/lib/python3.6/site-packages/torch/serialization.py", line 368, in load
> > return _load(f, map_location, pickle_module)
> > File "/home/tian/.conda/envs/jiqi/lib/python3.6/site-packages/torch/serialization.py", line 542, in _load
> > result = unpickler.load()
> > ModuleNotFoundError: No module named 'models'
> 
> When I see the same problem: [https://github.com/pytorch/pytorch/issues/18325](url) i user `torch.jit.trace(model,torch.tensor(torch.rand(size=(1,3,640,640)))` but it not work ERROR with:
> 
> > TracingCheckError: Tracing failed sanity checks!
> > ERROR: Graphs differed across invocations!
> > Graph diff:
> > graph(%self.1 : **torch**.models.yolo.Model,
> > %x : Tensor):
> > %2 : **torch**.torch.nn.modules.container.Sequential = prim::GetAttr[name="model"](%self.1)
> > %3 : **torch**.models.yolo.Detect = prim::GetAttr[name="24"](%2)
> > %4 : **torch**.torch.nn.modules.container.Sequential = prim::GetAttr[name="model"](%self.1)
> > %5 : **torch**.models.common.C3 = prim::GetAttr[name="23"](%4)
> > ...
> > ...
> > ...
> > Comparison exception: 	expected tensor shape torch.Size([1, 1, 40, 40, 2]) doesn't match with actual tensor shape torch.Size([])!
> 
> **now,i use this method ,like:**
> 
> > m = MyModule()
> > m.state_dict()
> > `OrderedDict([('l0.weight', tensor([[ 0.1400, 0.4563, -0.0271, -0.4406],                                    [-0.3289, 0.2827, 0.4588, 0.2031]])),              ('l0.bias', tensor([ 0.0300, -0.1316])),              ('l1.weight', tensor([[0.6533, 0.3413]])),              ('l1.bias', tensor([-0.1112]))])`
> 
> > torch.save(m.state_dict(), 'mymodule.pt')
> > m_state_dict = torch.load('mymodule.pt')
> > new_m = MyModule()
> > new_m.load_state_dict(m_state_dict)
> 
> **When I use the new loading method for reasoning, the result is worse than the original loading method**

hello, how about your problem? solve it?

**Comment by zhoujian-z** [comment]
@zcunyi  how about your problem? solve it?
