### ISSUE TITLE
Labelling strategy for further blurry objects in video while driving?

### ISSUE THREAD

**Issue by joelluijmes** [ultralytics/yolov5#5149]
## ❔To Label or not to Label?

Hey, I'm training a model to detect manholes from video data. The video data is recorded from a smartphone inside a driving vehicle at 720p 30FPS. This video data I've split into frames and am labelling them with cvat. However, the manhole in the video is sometimes blurry. Raising the question, should I annotate this instance or not? 

Why is the object blurry?
1. Due vibrations of the car, not all frames are sharp. Sometimes the object is bit blurry.
2. As the car is driving, objects are coming into view. The object further away is blurry, however as we're getting closer the manhole is more clearly visible. Should I already mark the object in the distance? 
3. External factors (lighting and stuff)

What would be the best strategy for these? 
1. Remove the blurry / inrecognizable frames. Model will then train on less real world like scenario, which is okay for me. As long the objects are detected when they are close.
2. Label them: I think the model will also start detecting other objects that are blurry black shapes. Could be mitigated if there is enough data perhaps..
3. Don't label: introduces some bias, unsure from what point I should label them

### Exhibits

_Manhole in distance is just a black shape, not really recognizable_
<img src="https://user-images.githubusercontent.com/4273556/136953619-6d457ba5-ea63-4ea8-a2b5-5c7287c8c766.png" width="600" />

_Features are clearer when we are getting closer_
<img src="https://user-images.githubusercontent.com/4273556/136953750-6e23147d-13df-4a21-98da-7bea607dfafb.png" width="600" />

**Comment by joelluijmes** [comment]
Another interesting case is when there are multiple objects. Where the first object (blue) is recognizable, but the second one is meh (purple). Love to hear some input on this :) 

![image](https://user-images.githubusercontent.com/4273556/136957122-d36d7ac7-6330-4441-aedc-a323c611f61f.png)

**Comment by glenn-jocher** [comment]
@joelluijmes there's no right answer here since these questions depend on you as the author/domain expert to decide on, mostly because only you know the priorities of the product you are developing. 

The primary concept to know is that **YOLO will learn what you teach it**. If you want it to detect far away blurry objects, then label those. If you don't want it to detect those, do not label them. That is all.
