### ISSUE TITLE
Classes with no instances causes legend misalignment

### ISSUE THREAD

**Issue by NauchtanRobotics** [ultralytics/yolov5#5158]
## 🐛 Bug

I prepared some annotations which were then filtered to removed annotations for the first three classes. This cause problems with plot legends.

When there are not instances of bounding boxes for certain classes in the dataset.yaml file, the legends for various plots can be misaligned. See labels.jpg correctly shows no count for instances of class "D00", "D10" and "D20" whilst "D40" and "EB" do have bars. However, PR_curve.png mistakenly marks "D00" and "D01" in the legend as having data (but not "D40" and "EB" classes).

## To Reproduce (REQUIRED)

Prepare annotation labels that do not have any instances of the first three classes listed in the dataset yaml file, then run:

`python train.py --img 640 --batch 54 --device 0,1 --cfg models/yolov5x_road.yaml --data filtered_dataset.yaml --weights weights/IMSC/last_95.pt --hyp ./data/hyp.scratch.yaml --name TEST --epochs 1`

where filtered_dataset.yaml is:

<pre>
train: datasets/bbox_collation_6_D40_EB_only/train/images/
val: datasets/bbox_collation_6_split_D40_EB_only/val/images/
nc: 5
names: ['D00','D10','D20','D40', 'EB']
</pre>

## Expected behavior

PR Curve should have lines for classes "D40" and "EB" marked in the legend but nothing for the first three classes "D00", "D10" and "D20".

## Context 

I realise that it would be unusual to plan to have no bounding box instances for the first 3 class names, but things can evolve this way over time. In my case, I didn't want to use all of the classes provided by an open source data set. I noticed that having classes with low instance counts could harm the detection performance of my priority classes (even when I remove class weighting).  So I filter these out when training a model for production, but I retain data for those first three classes for a time in the future when I have accumulated higher instance counts. Hopefully after increasing the instance counts of those classes, the performance of priority classes will not be reduced.
![labels](https://user-images.githubusercontent.com/14794739/137065872-c02c5a64-c517-48d6-9f40-ae83a8d57a98.jpg)
![PR_curve](https://user-images.githubusercontent.com/14794739/137065881-0e59267d-c9ff-4560-9ce6-a061240eeda6.png)
.

**Comment by glenn-jocher** [comment]
@NauchtanRobotics hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

The curve plotting functions are in metrics.py here:
https://github.com/ultralytics/yolov5/blob/b754525e99ca62424c484fe529b6142f6bab939e/utils/metrics.py#L294-L333

**Comment by NauchtanRobotics** [comment]
PR submitted #5174

**Comment by NauchtanRobotics** [comment]
p.s. This problem was effecting more than just the PR_curve.png. Was effecting all plots called in ap_per_class() here:
<pre>
    if plot:
        plot_pr_curve(px, py, ap, Path(save_dir) / 'PR_curve.png', names)
        plot_mc_curve(px, f1, Path(save_dir) / 'F1_curve.png', names, ylabel='F1')
        plot_mc_curve(px, p, Path(save_dir) / 'P_curve.png', names, ylabel='Precision')
        plot_mc_curve(px, r, Path(save_dir) / 'R_curve.png', names, ylabel='Recall')
</pre>
