### ISSUE TITLE
downloading Arial.ttf

### ISSUE THREAD

**Issue by Riad123321** [ultralytics/yolov5#5159]
## ❔Question
Hi
i don't want to automatically downloading Arial.ttf file from internet at all if i have Arial.ttf file  locally where should i put it in yolov5 folder.

**Comment by glenn-jocher** [comment]
@Riad123321 Arial is used for plotting. If your system doesn't have it then it will be downloaded to your user config directory the first time you run YOLOv5. The download directory is indicated on download.

If it's already been downloaded by YOLOv5 then there's no action for you to take.

**Comment by Riad123321** [comment]
> @Riad123321 Arial is used for plotting. If your system doesn't have it then it will be downloaded to your user config directory the first time you run YOLOv5. The download directory is indicated on download.
> 
> If it's already been downloaded by YOLOv5 then there's no action for you to take.

I solve it thank you
