### ISSUE TITLE
--img-size

### ISSUE THREAD

**Issue by linhaoqi027** [ultralytics/yolov5#516]
## ❔Question
parser.add_argument('--img-size', nargs='+', type=int, default=[640, 640], help='train,test sizes') 
what does --img-size mean?
Does it mean the number of picture for train and test?

**Comment by glenn-jocher** [comment]
@linhaoqi027 ?

--img-size means the image size. units are pixels.

**Comment by linhaoqi027** [comment]
so the one step of the input is resizing the image size（like 640）?

**Comment by glenn-jocher** [comment]
Sure

**Comment by china56321** [comment]
> so the one step of the input is resizing the image size（like 640）?
Q1:
**parser.add_argument('--img-size', nargs='+', type=int, default=[640, 320], help='train,test sizes')**

**Does it  mean the training size is 640x640,and the testing size is 320x320 ?  or training size  and the testing size are both 640x320 ?**

Q2:
    **parser.add_argument('--rect', action='store_true', help='rectangular training')**

   **What does  '--rect' mean ?**

**Comment by glenn-jocher** [comment]
@china56321 yes that is correct, your train size wll be 640x640 and your test size will be 320x320! But I would strongly advise to train and test and the same sizes.

rectangular training means what it says. You can switch it on and observe the effect in your train_batch0.jpg.

**Comment by china56321** [comment]
> @china56321 yes that is correct, your train size wll be 640x640 and your test size will be 320x320! But I would strongly advise to train and test and the same sizes.
> 
> rectangular training means what it says. You can switch it on and observe the effect in your train_batch0.jpg.

What should i do if i want to train my dataset resized to 640*320 ?

**Comment by glenn-jocher** [comment]
--img 640

**Comment by kashishgoyal31** [comment]
If my original images is 100*100 then while training do you mean that  if -- img is set as 640 will it rescale the image to 640*640?

**Comment by glenn-jocher** [comment]
@kashishgoyal31 yes
