### ISSUE TITLE
How can I label the custom data and add to the already labelled data?

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#5162]
I have labelled the set of custom data already. It contains 68 classes of objects. Now, again, I have accumulated some more data and I need to label it again.
However, I am out of idea how should I label the new dataset so that the class index matches to the previously labeled data. Because the new data are to be added with the previously added dataset.

**Comment by glenn-jocher** [comment]
@VirtuallKingg to combine multiple datasets they all must share common classes, i.e. if you want to detect with COCO (class 0-79) + custom data then just label your custom classes 80 onward.

**Comment by ghost** [comment]
@glenn-jocher Thank You. After researching, I also came in the same conclusion that I must use the label names serially as they were in the previous dataset. And I can add more after that if I want. This will preserve the class index.
