### ISSUE TITLE
small images

### ISSUE THREAD

**Issue by 123456789mojtaba** [ultralytics/yolov5#517]
9623 of 171924 labels are < 3 pixels in width or height.
what can I do to this problem? which parameter can I change in yolov5?

**Comment by glenn-jocher** [comment]
You can train at a larger --img-size.

**Comment by 123456789mojtaba** [comment]
> You can train at a larger --img-size.

yeah. but it makes the inference slow. can I fix it with changing some parameters?

**Comment by glenn-jocher** [comment]
Sure, use a faster GPU.
