### ISSUE TITLE
Have you tried to add SE block?

### ISSUE THREAD

**Issue by SpongeBab** [ultralytics/yolov5#5178]
@glenn-jocher hi,Have you tried to add SE block?I'm trying to add the SE(Squeeze-and-Excite) block.If it is useless,I will give up it.

**Comment by glenn-jocher** [comment]
@SpongeBab actually, I haven't tried it. I think EfficientNet/Det models have significant use of SE blocks.

**Comment by SpongeBab** [comment]
@glenn-jocher ok,I see.I will try if I can add the SE structure to yolo.Thank you~

**Comment by yustaub** [comment]
May I know that SE block is useful? @SpongeBab
