### ISSUE TITLE
Image size after using mosaic image augmentation

### ISSUE THREAD

**Issue by aniroh** [ultralytics/yolov5#5182]
## ❔Question
Looking at the load_mosaic() function in datasets.py, I've observed that it doubles both the width and height of the output image during the process. So before starting the training, does it resize the image to the original size? Like if I'm using load_mosaic with img_size=480, it will resize it to (960,960). So is it resized back to (480,480) before training?
## Additional context
In datasets.py, if you can observe line 693 in load_mosaic() function,
`img4 = np.full((s * 2, s * 2, img.shape[2]), 114, dtype=np.uint8)  # base image with 4 tiles`
this line sets the size of base image to double the size of image_size.
I want to know if it is made small again before training.

The context to this query is because I want to know if using mosaic image augmentation makes the objects even smaller than it actually is since I'm working on small objects.

**Comment by glenn-jocher** [comment]
@aniroh mosaic does not resize images. The scale hyperparameter is responsible for scale augmentation:
https://github.com/ultralytics/yolov5/blob/0be58f16f0ce9ecdbcad0a740d54186b6d2f83d1/data/hyps/hyp.scratch.yaml#L22-L34

**Comment by shiontao** [comment]
img2, labels2 = random_perspective(img2, labels2, segments2,
                                       degrees=self.hyp['degrees'],
                                       translate=self.hyp['translate'],
                                       scale=self.hyp['scale'],
                                       shear=self.hyp['shear'],
                                       perspective=self.hyp['perspective'],
                                       **border=self.mosaic_border)  # border to remove**

**Comment by JamesMcCullochDickens** [comment]
@glenn-jocher I see that in the load_mosaic() function in the datasets.py class the random_perspective function is called with the 4mosaic, but I am not sure where the resizing to the original size occurs. The cv2.warpPerspective and cv2.warpAffine functions have a dsize parameter, but it is set to the size of the padded height and width of the 4mosaic, and the scale hyperparameter influences the matrix that is passed in, but not the final size. 

Supposing my images are of size 640 * 640 (square training), and I make a mosaic with 4 images, then the resolution will be 1280 * 1280, but where is the resizing operation occurring (back to 640 * 640).
