### ISSUE TITLE
Train a model using mp4 videos

### ISSUE THREAD

**Issue by lokeshn011101** [ultralytics/yolov5#5184]
## ❔Question
Is there any way to train a model using a bunch of mp4 videos directly?
## Additional context
I am working on a project in which the dataset has a bunch of videos and frame labels and I would like to train a YOLOv5 model on those videos. I can't find a way to train a model directly using videos. I extracted all the frames for one video and fed it to YOLOv5 and the results were amazing. But the problem is that extracting frames of all the videos takes a huge amount of space and time and there are almost 28 videos each having an average of 10k frames. Can anyone suggest any better method than this?

**Comment by glenn-jocher** [comment]
@lokeshn011101 randomly extracting a frame from a video is not possible as far as I know with any tool, so there's no possible way to load shuffled data for training from a video.

The correct workflow is to extract frames into a dataset and then train.
