### ISSUE TITLE
i want to make detection every 4 frame not every frame

### ISSUE THREAD

**Issue by VYRION-Ai** [ultralytics/yolov5#5185]
## ❔Question
i want to make detection every 4 frame not every frame?
## Additional context
i want to speed up the detection process, so i want to pass some frames from detection. how can i do that?

**Comment by glenn-jocher** [comment]
@totoadel you may be able to update the detect.py dataloaders to suit your needs, or you can also use YOLOv5 PyTorch Hub models to create your own custom inference pipeline.
https://github.com/ultralytics/yolov5/blob/7ee5aed0b3fa6a805afb0a820c40bbcbf29960de/detect.py#L120-L128

**Comment by zxq309** [comment]
@glenn-jocher How to update the detect.py dataloaders ? I want to run detection on 1 every 4 frames, and use the output to draw the same bboxes on the next 3 frames.

**Comment by glenn-jocher** [comment]
@XiangqingZhang you can customize the video loader here:
https://github.com/ultralytics/yolov5/blob/a936f5f219e7697ea059d6fcf5ead3ac7b206687/utils/datasets.py#L159-L239
