### ISSUE TITLE
Any trained data for QR codes and barcodes?

### ISSUE THREAD

**Issue by so-o** [ultralytics/yolov5#5191]
## ❔Question
Question is in the title.

I found trained data for QR codes for yolov4, not for barcodes. I need to convince some people before we start generating our own data. The trained data set I have for yolov4 doesn't work when 2 QR codes are close to each other.

**Comment by glenn-jocher** [comment]
@so-o we don't have a QR dataset ready to go, but if you find or create one it would be super useful if you could submit a PR to add it to our autodownload datasets here to allow other users to get started more easily in the future:
https://github.com/ultralytics/yolov5/tree/master/data

About improving your training results, see **Tips for Best Training Results** tutorial below. It was written for YOLOv5, but  applies broadly to Vision AI in general, so should also help with YOLOv4 training.

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by ghost** [comment]
@so-o, do you want to do actual barcode recognition or just tell if there's a barcode in the image? We do barcodes for a living ([softmatic.com](https://softmatic.com)) and can easily mass create barcodes for synthetic data.

**Comment by glenn-jocher** [comment]
@softmatic @so-o one important point to remember is that the background/surroundings of the QR/bar codes are just as important as the codes themselves, and this may not be easily simulated. i.e. if you create a synthetic dataset of codes on white/solid backgrounds this will probably fail (poor generalization, excessive FPs) when deployed in the real world. The train, val and deployed image spaces must all be subsets of a common image space for best results:

<img width="2029" alt="dataset" src="https://user-images.githubusercontent.com/26833433/137432092-6f24df9e-23c7-4583-acd0-5b9e929f3b4c.png">

**Comment by ghost** [comment]
Yeah, it's not trivial. I've been looking into generating synthetic data for another project, there's a very extensive paper that reviews the various approaches and pitfalls: [arxiv](https://arxiv.org/abs/1909.11512)
