### ISSUE TITLE
About the meaning of the model name

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#5197]
@glenn-jocher 
I found these models in the directory `yolov5/models/hub/`:
![ksnip_20211015-130008](https://user-images.githubusercontent.com/41098760/137434911-43f0239c-f3be-4ab2-8347-c5842d436782.png)

What part of the model is the difference between `p2`, `p6`, and `p7` here?

**Comment by glenn-jocher** [comment]
@Zengyf-CVer P2 models include stride 4 P2-P5 outputs for improved small object detection.

P6 models include P3-P6 output layers at stride 64, i.e. yolov5s6.pt is a P6 model.

P7 is an even larger stride 128 output model that includes output layers P3-P7.

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
In other words, P2, P6, and P7 all improve the detection of small objects? Because according to my observation, when running yolov5s6, `--img-size` needs 1280, so I can think that the above three models are used to detect small objects?

**Comment by glenn-jocher** [comment]
@Zengyf-CVer no, P6 and P7 models improve detection of large objects. P2 is for small objects.

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
Can I use your yolov5s pre-trained model, then yaml uses the P2 network structure, and then train my custom data set? Can this be done directly? Although I know that the pre-trained model of yolov5s is P5 architecture.

**Comment by glenn-jocher** [comment]
@Zengyf-CVer sure, you can try. Any pretrained `--weights` can be paired with any `--cfg` yaml, and YOLOv5 will transfer over all layers with matching names and shapes. You can see how many layers successfully transferred in the console, i.e. 
```bash
Transferred 362/362 items from yolov5s.pt
```

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
Thank you very much for your answers.

**Comment by abfleishman** [comment]
@glenn-jocher is there a good resource for learning about the stride and P3, P4, P5 etc notation?  i.e. is there a good place I can read about this to make informed decisions myself rather than asking you to explain things that are probably pretty basic?

**Comment by glenn-jocher** [comment]
@abfleishman see EfficientDet paper:
https://arxiv.org/abs/1911.09070
![image](https://user-images.githubusercontent.com/26833433/142197918-c9b96322-ece5-4cbc-ba7f-d773a6d25638.png)
