### ISSUE TITLE
Trained yolo5 on GPR images and got bad results

### ISSUE THREAD

**Issue by Rajat-Mehta** [ultralytics/yolov5#52]
I have 1200 images (1000 train, 200 test) collected by ground penetrating radar sensor and the goal is to detect different type of defects present in those images. There are 7 classes in total and the defects look like this:
![WhatsApp Image 2020-06-10 at 19 31 42](https://user-images.githubusercontent.com/11868713/84578060-f772a300-adc1-11ea-8721-219304ff8534.jpeg)
![WhatsApp Image 2020-06-10 at 19 41 51](https://user-images.githubusercontent.com/11868713/84578061-fccfed80-adc1-11ea-9578-08ab2c0dcfc4.jpeg)

I tried to train your model on my data and it is not working as expected. After 300 epochs I got only 2% mAP and it is not increasing at all. I have made the necessary changes in config files, prepared my data according to your custom data training tutorial. Am not sure what is wrong in my training process.

Do you have any idea or suggestions in order to achieve good mAP on my dataset?

Thanks,
Rajat

**Comment by glenn-jocher** [comment]
@Rajat-Mehta I've pushed a commit for better anchor-label introspection before training which may help future training runs.
https://github.com/ultralytics/yolov5/commit/31f331002905c781d9885afc6396142f25f435a0
