### ISSUE TITLE
mAPtest [0.5:0.95] missing

### ISSUE THREAD

**Issue by Karol-G** [ultralytics/yolov5#5202]
Hey,

I noticed that you updated the Pretrained Checkpoints section. It seems the mAPtest [0.5:0.95] column is missing now. Can you add it again? 

Further, in the commits before, when it was still there, mAPtest [0.5:0.95] and mAPval [0.5:0.95] was exactly the same. Were the reported test results truly equal to the val reports down to the last digit for every model?

Best
Karol

**Comment by glenn-jocher** [comment]
@Karol-G we don't have test values for v6.0 release yet, instead we've added additional profiling results to the table. Test set evaluation directions are in coco.yaml, you can submit results to the server:
https://github.com/ultralytics/yolov5/blob/fc3606420d86fac54b6fe5e67fc4be64325df5dc/data/coco.yaml#L10-L15

**Comment by Karol-G** [comment]
Thanks for the info
