### ISSUE TITLE
Zero Shot Object Tracking Tutorial

### ISSUE THREAD

**Issue by Jacobsolawetz** [ultralytics/yolov5#5209]
## 🚀 Feature

Adding a tutorial link to [zero shot object tracking](https://github.com/roboflow-ai/zero-shot-object-tracking)

## Motivation

Object tracking algorithms like deepsort require you to train a separate featurizer on your object tracks, requiring additional annotation. It would be nice to just show up with your object detection model and get tracking.

## Pitch

In the [zero shot object tracking](https://github.com/roboflow-ai/zero-shot-object-tracking), @maxhs2014, @yeldarby and I (mostly @maxhs2014) proved out an object tracking approach that used CLIP features zero shot. No need to train an additional model, you can just show up with your YOLOv5 weights and track objects in a video.

## Alternatives

Traditional deepsort for tracking on the edge and more accurate in-domain features 

## Additional Considerations

We would need to maintain this against YOLOv5 releases - or perhaps call out a particular hash that is supported

**Comment by glenn-jocher** [comment]
@Jacobsolawetz sounds interesting! What would be next steps?
