### ISSUE TITLE
Could not infer the output of the torchscript model

### ISSUE THREAD

**Issue by govindamagrawal** [ultralytics/yolov5#521]
## 🚀 Feature
Could not infer the output of the torchscript file. I guess, the same output comes from the onnx converted model.
----------------------------------------------------------------------------
import torch
import torchvision

weights = './yolov5s.pt'
img = torch.zeros((1, 3, 224, 224))  # image size(1,3,320,192) 
model = torch.load(weights, map_location=torch.device('cpu'))['model'].float()
y = model(img)  

-----------------------------------------------------------------------------
import torch
import torchvision
img = torch.zeros((1, 3, 224, 224))  # image size(1,3,320,192) 
script_model  =  torch.jit.load('yolov5s.torchscript.pt')
out = script_model(img)

------------------------------------------------------------------------------

**The shape of y[0] is torch.Size([1, 3087, 85]), whereas the shape of out[0] is torch.Size([1, 3, 7, 7, 85])**, which I am not able to understand. Please help in this regard. 

While exporting the model using export.py file, I made a small change in the following line:

    img = torch.zeros((opt.batch_size, 3, *opt.img_size)) <-- " *opt.img_size " was creating error. I do not if its working fine for others. So, I changed to:
   img =  torch.zeros((opt.batch_size, 3, 640, 640))

**Comment by glenn-jocher** [comment]
@govindamagrawal export is part of our CI tests, which are currently passing on all 3 operating systems (MacOS, Windows and Ubuntu), so if your environment is correctly configured you should not be seeing any error in export.py. I recommend you attempt your tasks in a working environment:

## Reproduce Our Environment

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)

**Comment by govindamagrawal** [comment]
Hi @glenn-jocher . Thanks a lot for such a quick response and the work. The main concern is not about whether the export is working or not. Definitely it's working. The main concern is that the output shape is different for torchscript/onnx. 
Output of the torch at index 0 is of shape ([1, 3087, 85]), whereas the shape of the output of the torchscript at index 0 is ([1, 3, 7, 7, 85]), for the same input. 
If you can verify this once and help in how to interpret the result for non-max compression?

**Comment by dagap** [comment]
@govindamagrawal Did you manage to solve this? I have the same problem with pytorch 1.7.0.
