### ISSUE TITLE
Advanced Usage: Dataset Versioning and Evaluation

### ISSUE THREAD

**Issue by Matias2379** [ultralytics/yolov5#5211]
## ❔ is log_dataset.py working?

Im trying to version my dataset, so i tried the next line of code after looking at the argparser:

`python utils/loggers/wandb/log_dataset.py`

I was hopping to see in wandb.ai the coco128 dataset, under the project Yolov5, with the name 'log dataset', but nothing happens, it runs and ends without errors or warnings.
I've already trained a couple of models and logged to wandb succesfully, to provide a little more context.
Thanks in advance

**Comment by glenn-jocher** [comment]
@Matias2379 thanks for your inquiry! Can you please provide code to reproduce the issue you are encountering?

@AyushExel can you verify the W&B logging datasets functionality please? Thanks!

**Comment by Matias2379** [comment]
Thanks for your answer @glenn-jocher. I was just trying to test the dataset logging functionality with the example dataset coco128 before using my own data. There is no much code to show, i jsut run 'python utils/loggers/wandb/log_dataset.py' from the terminal in pycharm, after clonning the yolov5 repo. Let me know if some screen captures could help.

**Comment by AyushExel** [comment]
@Matias2379 you need to install wandb. Run `pip install wandb` and then try to upload your dataset. It should work.
I'll add a message in the script to warn when wandb is not installed

**Comment by Matias2379** [comment]
Than you @AyushExel ! that was the problem. It worked as expected.

**Comment by AyushExel** [comment]
@Matias2379 Great! you can do many powerful things if you log your dataset as W&B Table. Take a look at the advanced section of [W&B tutorial](https://github.com/ultralytics/yolov5/issues/1289) and feel free to tag me if face any problems
