### ISSUE TITLE
Multi GPU training request 

### ISSUE THREAD

**Issue by sevaraMS** [ultralytics/yolov5#5216]
In the request of Nvidia Driver >= 455.23 And I installed 460 versions of Nvidia Driver and automatically installed Cuda version 11.2 In the running time I get the Error message as this depository trained based on Nvidia Driver 465.19, then I reinstalled 470 versions of Nvidia Driver and automatically installed Cuda version 11.4. 
When I run code:
sudo docker run --ipc=host -it ultralytics/yolov5:latest
I get the error that the PyTorch version is not satisfied, but for Cuda version 11.4 there is no PyTorch version available. Even for  Nvidia Driver >= 455.23 Cuda driver version no available in PyTorch. What Can I do in this situation

**Comment by glenn-jocher** [comment]
@sevaraMS for most situations 460 is fine. See release v6.0 speed discussion https://github.com/ultralytics/yolov5/pull/5141#issuecomment-941247815 with driver details. We used 460 with CUDA 11.2 running the Docker image to produce the README values.
