### ISSUE TITLE
DDP memory usage inconsistent with DP

### ISSUE THREAD

**Issue by wmcnally** [ultralytics/yolov5#5218]
DDP seems to use more memory. When training yolov5m6 on 4xV100 (32GB) GPUs I am able to use a batch size of 72 with DP. However, when I use DDP I am limited to a batch size of 48. Do you know why this might be happening? Do you have any suggestions on how to fix the issue? Thanks in advance.

**Comment by glenn-jocher** [comment]
@wmcnally DP is not recommended for use. Use DDP for all multi-gpu trainings for best results. See https://pytorch.org/tutorials/intermediate/ddp_tutorial.html#comparison-between-dataparallel-and-distributeddataparallel
