### ISSUE TITLE
A Question About the Model.

### ISSUE THREAD

**Issue by Mr-Clutch-China** [ultralytics/yolov5#5219]
## ❔Question
Sorry to trouble you,  I want to know the function of the first C3 layer. Does it only serve to deepen the network?  Because I don't think it's directly involved in feature fusion.  
## Additional context
It only concerns the model.

**Comment by glenn-jocher** [comment]
@Mr-Clutch-China `C3()` modules are the primary building blocks of YOLOv5 models. See common.py for details:
https://github.com/ultralytics/yolov5/blob/6d9b99fc4d700ee9d3e52491b852a8067efadb40/models/common.py#L125-L138

**Comment by RAO-CREATE** [comment]
How to modify or add some blocks to the yolov5 model. Please suggest to me, someone?
