### ISSUE TITLE
Increase the usage of augmented assignment statements

### ISSUE THREAD

**Issue by elfring** [ultralytics/yolov5#5224]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

Would you like to integrate anything from a transformation result which can be generated by a command like the following?
(:point_right: Please check also for questionable change suggestions because of an evolving search pattern.)
```
[Markus_Elfring@fedora lokal]$ perl -p -i.orig -0777 -e 's/^(?<indentation>\s+)(?<target>\S+)\s*=\s*\k<target>\s*(?<operator>[+\-%&|^@]|\*\*?|\/\/?|<<|>>)/$+{indentation}$+{target} $+{operator}=/gm' $(find ~/Projekte/yolov5/lokal -name '*.py')
```

**Comment by glenn-jocher** [comment]
@elfring hi, thank you for your feature suggestion on how to improve YOLOv5 🚀! I don't entirely understand what you are saying, but it seems that you'd like us to use more in-place operators.

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by elfring** [comment]
>… I don't entirely understand what you are saying, …

Will it help to improve the understanding another bit for the presented change pattern? :thinking:

**Comment by glenn-jocher** [comment]
@elfring you mean run the shell script on my computer? Ok, I'm changing the directory to this:
```bash
perl -p -i.orig -0777 -e 's/^(?<indentation>\s+)(?<target>\S+)\s*=\s*\k<target>\s*(?<operator>[+\-%&|^@]|\*\*?|\/\/?|<<|>>)/$+{indentation}$+{target} $+{operator}=/gm' $(find ./ -name '*.py')
```

Hmm, wow, this is a very powerful command! it produced 6 examples where we could use inplace operators. It looks like 2 of these changes are suitable, the other 4 are not suitable, i.e. in datasets.py this would be a problem. 
```diff
-                    b[2:] = b[2:] * 1.2 + 3  # pad
+                    b[2:] *= 1.2 + 3  # pad
```

I can put in a PR for the 2 good change locations though!

**Comment by glenn-jocher** [comment]
Also numpy matrix multiplication with @ is not yet supported (in augmentations.py):
```bash
TypeError: In-place matrix multiplication is not (yet) supported. Use 'a = a @ b' instead of 'a @= b'.
```

**Comment by glenn-jocher** [comment]
@elfring good news 😃! Your original issue may now be fixed ✅ in PR #5230. This PR adds inplace ops in 2 areas discovered by your search script (other areas not suitable).

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by elfring** [comment]
>Hmm, wow, this is a very powerful command!

Thanks for another positive feedback.

:thought_balloon: I find the shown search pattern so simple with a general consequence that it can present also questionable change suggestions.

-----

Would another change suggestion become relevant?

```diff
diff --git a/models/experimental.py b/models/experimental.py
index edccc96..f2bed7d 100644
--- a/models/experimental.py
+++ b/models/experimental.py
@@ -39,10 +39,10 @@ class Sum(nn.Module):
         if self.weight:
             w = torch.sigmoid(self.w) * 2
             for i in self.iter:
-                y = y + x[i + 1] * w[i]
+                y += x[i + 1] * w[i]
         else:
             for i in self.iter:
-                y = y + x[i + 1]
+                y += x[i + 1]
         return y
 
 
```

**Comment by elfring** [comment]
>Also numpy matrix multiplication with @ is not yet supported (in augmentations.py):

:thought_balloon: Are you looking for further collateral evolution also in this software area?

**Comment by glenn-jocher** [comment]
@elfring I think experimental.py we can not change because if I remember correctly this produces an error on training about a 'leaf variable' being modified in-place which interferes with gradient computation.

Inference would be fine, but training will not work like this.

**Comment by elfring** [comment]
How do you think about possibilities to mark source code places explicitly where in-place modification can not be applied (because of special reasons)? :thinking:

**Comment by glenn-jocher** [comment]
@elfring yes a comment in those areas makes sense!
