### ISSUE TITLE
NVIDIA GeForce RTX 3080 Ti with CUDA capability sm_86 is not compatible with the current PyTorch installation.

### ISSUE THREAD

**Issue by Yoon5** [ultralytics/yolov5#5226]
I want to train using multi gpu based on docker. I installed Nvidia 470, Cuda 11.4, PyTorch 1.9. When I started training I got below error message.
root@d1e2ab44a7f3:/usr/src/app# python -m torch.distributed.run --nproc_per_node 2 --master_port 1 train.py --data coco128.yaml --epochs 3 --device 0,1
WARNING:__main__:*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/opt/conda/lib/python3.8/site-packages/torch/cuda/__init__.py:106: UserWarning: 
NVIDIA GeForce RTX 3080 Ti with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA GeForce RTX 3080 Ti GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: (30 second timeout) 
wandb: W&B disabled due to login timeout.
train: weights=yolov5s.pt, cfg=, data=coco128.yaml, hyp=data/hyps/hyp.scratch.yaml, epochs=3, batch_size=16, imgsz=640, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, evolve=None, bucket=, cache=None, image_weights=False, device=0,1, multi_scale=False, single_cls=False, adam=False, sync_bn=False, workers=8, project=runs/train, name=exp, exist_ok=False, quad=False, linear_lr=False, label_smoothing=0.0, patience=100, freeze=0, save_period=-1, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest
github: skipping check (Docker image), for updates see https://github.com/ultralytics/yolov5
/opt/conda/lib/python3.8/site-packages/torch/cuda/__init__.py:106: UserWarning: 
NVIDIA GeForce RTX 3080 Ti with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA GeForce RTX 3080 Ti GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
YOLOv5 🚀 v6.0-0-g956be8e torch 1.9.1+cu102 CUDA:0 (NVIDIA GeForce RTX 3080 Ti, 12053.8125MB)
                                            CUDA:1 (NVIDIA GeForce RTX 3080 Ti, 12053.8125MB)

Added key: store_based_barrier_key:1 to store for rank: 0
Rank 0: Completed store-based barrier for 2 nodes.
hyperparameters: lr0=0.01, lrf=0.1, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0
TensorBoard: Start with 'tensorboard --logdir runs/train', view at http://localhost:6006/

WARNING: Dataset not found, nonexistent paths: ['/usr/src/datasets/coco128/images/train2017']
Downloading https://github.com/ultralytics/yolov5/releases/download/v1.0/coco128.zip to coco128.zip...
100%|██████████████████████████████████████| 6.66M/6.66M [00:00<00:00, 7.34MB/s]
Dataset autodownload success, saved to ../datasets

Traceback (most recent call last):
Traceback (most recent call last):
  File "train.py", line 620, in <module>
  File "train.py", line 620, in <module>
        main(opt)main(opt)

  File "train.py", line 517, in main
  File "train.py", line 517, in main
    train(opt.hyp, opt, device, callbacks)
      File "train.py", line 102, in train
train(opt.hyp, opt, device, callbacks)
  File "train.py", line 103, in train
    with torch_distributed_zero_first(LOCAL_RANK):
  File "/opt/conda/lib/python3.8/contextlib.py", line 113, in __enter__
    data_dict = data_dict or check_dataset(data)  # check if None
  File "/opt/conda/lib/python3.8/contextlib.py", line 120, in __exit__
    return next(self.gen)
  File "/usr/src/app/utils/torch_utils.py", line 37, in torch_distributed_zero_first
    next(self.gen)
  File "/usr/src/app/utils/torch_utils.py", line 40, in torch_distributed_zero_first
    dist.barrier(device_ids=[local_rank])
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2538, in barrier
    dist.barrier(device_ids=[0])
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2538, in barrier
    work = default_pg.barrier(opts=opts)
RuntimeError: NCCL error in: ../torch/lib/c10d/ProcessGroupNCCL.cpp:38, unhandled cuda error, NCCL version 2.7.8
ncclUnhandledCudaError: Call to CUDA function failed.
    work = default_pg.barrier(opts=opts)
RuntimeError: NCCL error in: ../torch/lib/c10d/ProcessGroupNCCL.cpp:38, unhandled cuda error, NCCL version 2.7.8
ncclUnhandledCudaError: Call to CUDA function failed.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 361) of binary: /opt/conda/bin/python
/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py:367: UserWarning: 

**********************************************************************
               CHILD PROCESS FAILED WITH NO ERROR_FILE                
**********************************************************************
CHILD PROCESS FAILED WITH NO ERROR_FILE
Child process 361 (local_rank 0) FAILED (exitcode 1)
Error msg: Process failed with exitcode 1
Without writing an error file to <N/A>.
While this DOES NOT affect the correctness of your application,
no trace information about the error will be available for inspection.
Consider decorating your top level entrypoint function with
torch.distributed.elastic.multiprocessing.errors.record. Example:

  from torch.distributed.elastic.multiprocessing.errors import record

  @record
  def trainer_main(args):
     # do train
**********************************************************************
  warnings.warn(_no_error_file_warning_msg(rank, failure))
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 702, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 361, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 698, in main
    run(args)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 689, in run
    elastic_launch(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 244, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
***************************************
            train.py FAILED            
=======================================
Root Cause:
[0]:
  time: 2021-10-18_01:53:20
  rank: 0 (local_rank: 0)
  exitcode: 1 (pid: 361)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
=======================================
Other Failures:
[1]:
  time: 2021-10-18_01:53:20
  rank: 1 (local_rank: 1)
  exitcode: 1 (pid: 362)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
***************************************

**Comment by ghost** [comment]
You have PyTorch binaries for CUDA 10 (1.9.1+cu102), I believe for 30xx you need the CUDA 11 version, that would be 1.9.1+cu111.

**Comment by glenn-jocher** [comment]
@Yoon5 your comments show this, you might want to follow this:

> If you want to use the NVIDIA GeForce RTX 3080 Ti GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

**Comment by Hyrtsi** [comment]
I got the same error. Steps to fix:

edit `Dockerfile` and uncomment this line

```
# RUN pip install --no-cache torch==1.10.0+cu113 torchvision==0.11.1+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
```

OR run the `pip install...` command straight in your docker 

and then `python detect.py` or whatever you're going to do works.

**Comment by tintin10q** [comment]
@Hyrtsi does this mean I need to install cuda 11.3 for it to work?

**Comment by tintin10q** [comment]
This did it for me! Thanks!

**Comment by glenn-jocher** [comment]
@tintin10q i'm glad to hear that updating to PyTorch 1.10.0+cu113 resolved the issue for you! This aligns with the CUDA version required to support the NVIDIA GeForce RTX 3080 Ti GPU. Reach out if you encounter any more issues.
