### ISSUE TITLE
C++: TensorRT / ONNX

### ISSUE THREAD

**Issue by fbens47** [ultralytics/yolov5#5229]
## ❔Question

Hi,

First, thanks for your work, that's great stuff.

I exported my custom yolov5s model (3 classes) _via_ `export.py` as ONNX model. When I run it with `detect.py` everything is perfect. But when I try to run inference with it on TensorRT (same model, same input images) the results are rogue, even for images from the training dataset. I am using the right output [1, 25200, 8] and applying NMS on the top of it. Does someone ever manage to make it work on C++?

## Additional context
TensorRT 7.2
ONNX opset 13
Preprocessing is the same as: [https://github.com/wang-xinyu/tensorrtx/blob/master/yolov5/utils.h](url)
Postprocessing is inspired from: [https://github.com/wang-xinyu/tensorrtx/blob/master/yolov5/common.hpp](url)

**Comment by glenn-jocher** [comment]
@fbens47 yes PyTorch > ONNX > TensorRT is one route, though you might also want to try the direct YOLOv5 TensorRTx export here which skips the ONNX intermediary step:
https://github.com/wang-xinyu/tensorrtx

**Comment by fbens47** [comment]
Hi, @glenn-jocher I made it work with ONNX. It was my mistake, I partially initialized my bbox... Thanks!

**Comment by NacerFaraj** [comment]
> Hi, @glenn-jocher I made it work with ONNX. It was my mistake, I partially initialized my bbox... Thanks!

Would you plz let us know how you could use onnx to work in opencv & C++? I have the same problem using converted onnx. 

thanks.
