### ISSUE TITLE
yolov5 inference on video

### ISSUE THREAD

**Issue by toshit11** [ultralytics/yolov5#523]
## ❔Question
how can I run yolov5 inference on video with my trained weights on google colab?

**Comment by glenn-jocher** [comment]
`python detect.py --source video.avi`

**Comment by Una865** [comment]
> python detect.py --source video.avi

How to set up that I have maximum one detection

**Comment by glenn-jocher** [comment]
@Una865 see detect.py argparser
https://github.com/ultralytics/yolov5/blob/5774a1514de193c74ecc5203281da8de3c13f9af/detect.py#L219

**Comment by theAI-samurai** [comment]
I would like to understand why in detect.py we do not have an argument for yolo cfg file. 
How do we load network architecture in detect.py for yolov5?

**Comment by glenn-jocher** [comment]
@theAI-samurai in `detect.py`, the architecture (e.g. YOLOv5s, YOLOv5m, etc.) is inferred from the weights file. The model automatically loads the associated architecture based on the weights provided without needing to specify it separately.
