### ISSUE TITLE
Step = 2 on wandb (Weights And Biases report)

### ISSUE THREAD

**Issue by antimo22** [ultralytics/yolov5#5235]
## ❔Question

Hi, when I use YOLOv5s on my custom dataset, the step size in the plots on wandb is 2. So I have values for the metrics only for the multiples of 2 and I can't figure out why it's happening. On COCO128 I don't have this problem. Could you explain me why?

**Comment by glenn-jocher** [comment]
@antimo22 hi, thanks for reporting this issue with your custom data! Can you provide a link to your W&B run? 

@AyushExel can you help @antimo22 here? Thanks!

**Comment by AyushExel** [comment]
@antimo22 can you please link the dashboard?

**Comment by antimo22** [comment]
Yes, here it is: https://wandb.ai/antimo22/YOLOv5/runs/upreov5b?workspace=user-antimo22
