### ISSUE TITLE
Which hyperparameter yaml in order to reproduce training?

### ISSUE THREAD

**Issue by yoni-f** [ultralytics/yolov5#5236]
## ❔Question
In the new update there are 3 main yaml files (scratch, scratch-high, scratch-low).

I want to reproduce the training of YOLOv5m (with reported 45.2 mAP @ 640x640 resolution).

Which hyp file should I use? And with what batch size? I have 4xrtx3090 cards available with 24GB each.

Thanks!!

**Comment by glenn-jocher** [comment]
@yoni-f to reproduce use this command, though you may get better results with scratch.low. In general the smaller models perform better with low augmentation and the larger models perform better with high augmentation.

```bash
python train.py --data coco.yaml --batch 64 --weights '' --cfg yolov5m.yaml --epochs 300 --img 640 --hyp hyp.scratch-med.yaml --linear --device 0
```

**Comment by yoni-f** [comment]
Thanks!

@glenn-jocher would this be the same command for the YOLOv5L (specifically the "--hyp hyp.scratch-med.yaml --linear")?
