### ISSUE TITLE
Model Structure!!!

### ISSUE THREAD

**Issue by Jay-zzcoder** [ultralytics/yolov5#5237]
Why are the yolov5x.yaml same as the yolov5s.yaml? Is the structure of yolov5s identified with that of yolov5x?

**Comment by glenn-jocher** [comment]
@Jay-zzcoder YOLOv5 models use compound scaling constants `depth_multiple` and `width_multiple` that define a particular model's depth and width:
https://github.com/ultralytics/yolov5/blob/752d97df2cf90fc825dad4d61252841c41c97532/models/yolov5x.yaml#L3-L6
