### ISSUE TITLE
Add new information about the frame

### ISSUE THREAD

**Issue by jayer95** [ultralytics/yolov5#5239]
@glenn-jocher 
 Hi, if I want to add some information to the output video after the test, as shown in the figure below, where should I start to modify it?

![output](https://user-images.githubusercontent.com/35683311/137831911-01bc2289-bd0e-4c71-9fc1-b1855461bd97.jpg)

Where is the code to add the confidence value in the upper left corner when drawing the frame? Is it "im0"?

I need specific parameters and functions, thank you

**Comment by glenn-jocher** [comment]
@jayer95 annotations are handled by detect.py here:
https://github.com/ultralytics/yolov5/blob/a18b0c36cd4df0d3b9c2623c5dda009c5f281ac9/detect.py#L225
