### ISSUE TITLE
How to output the MAP of each class ?

### ISSUE THREAD

**Issue by china56321** [ultralytics/yolov5#524]
python test.py just output  mAP@.5   mAP@.5:.95. it can't output the MAP of each class . Can it be modified to output the  MAP of each class ?

**Comment by glenn-jocher** [comment]
@china56321 to display per-class statistics use the --verbose flag: `python test.py --verbose`

**Comment by rashmi-learning** [comment]
How to get map for each class while training for every epoch

**Comment by glenn-jocher** [comment]
@rashmi-learning running test.py directly prints metrics per class. You can try to force --verbose during training if you'd like to see these printed to screen during training. Logging per class metrics is not available.
