### ISSUE TITLE
Training folders

### ISSUE THREAD

**Issue by sekisek** [ultralytics/yolov5#5242]
if I set the folders not like that:
train: ../VOC/images/train/  # 16551 images 
 val: ../VOC/images/val/  # 4952 images

but to the same 1 folder, does it automatically split to val and train?

train: ../VOC/images/pics/   
 val: ../VOC/images/pics/  

thank you!

**Comment by glenn-jocher** [comment]
@sekisek this is pretty simple. YOLOv5 trains on the data you define. If you pass the same directory then it will train on that directory and then val on that directory.
