### ISSUE TITLE
yolov5 open source pre-training model, are all pictures unzoomed, are they all trained with the original images of coco2017?

### ISSUE THREAD

**Issue by ahong007007** [ultralytics/yolov5#5246]
Thank you for your wonderful work

## ❔Question

Excuse me，yolov5 open source pre-training model, are all pictures unzoomed, are they all trained with the original images of coco2017?

**Comment by glenn-jocher** [comment]
@ahong007007 yes YOLOv5 models are pretrained on COCO 2017. P5 models are trained at --img 640, P6 models are trained at --img 1280.
