### ISSUE TITLE
What does 'general.py - def non_max_suppression - labels=()' do?

### ISSUE THREAD

**Issue by gsbeom** [ultralytics/yolov5#5247]
I am analyzing for 'non_max_suppression'.

def non_max_suppression(prediction, conf_thres=0.25, iou_thres=0.45, classes=None, agnostic=False, multi_label=False,
                        labels=(), max_det=300):

I can't understand what 'labels=()' is doing.
Please help me.

**Comment by glenn-jocher** [comment]
@gsbeom used for hybrid autolabelling:
https://github.com/ultralytics/yolov5/blob/a18b0c36cd4df0d3b9c2623c5dda009c5f281ac9/utils/general.py#L639-L647

**Comment by gsbeom** [comment]
Thank you.
I'm a beginner so I'm not sure what it does.
Could you give me a link or material to understand it?
