### ISSUE TITLE
repeat name

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#5248]
## ❔Question
```
python detect.py --save-crop
```
Assume the video name is 'mv' 
The output will be the  mv.jpg, mv1.jpg, mv2.jpg, ... 
I find mv.jpg will be repeat write many times.
It cause the crop number reduce.

**Comment by 108360232Zijie** [comment]
I want to know-how is you avoid this question, Thank

**Comment by alicera** [comment]
https://github.com/ultralytics/yolov5/blob/master/detect.py#L170
