### ISSUE TITLE
Multi-GPU lr scaling

### ISSUE THREAD

**Issue by yoni-f** [ultralytics/yolov5#5249]
## ❔Question
When training in DDP with multiple GPUs, should we use the original hyp file, or should we scale the LR by a factor of NUM_GPUS? ie: if the original lr0 in the hyp file is 0.01 and we are training with NUM_GPUS=4, should we update it to be lr0=0.04?

Thanks!

**Comment by glenn-jocher** [comment]
@yoni-f no. YOLOv5 automatically adapts to class counts, batch size, world size etc.
