### ISSUE TITLE
Writing total no. of multi-objects count in video

### ISSUE THREAD

**Issue by TrippieHippie** [ultralytics/yolov5#5254]
## ❔Question
Is there any way to retain and/or write the overall object count for 1 video? 
For eg: Object A: 2, Object 3: 1, Object 6: 2

**Comment by glenn-jocher** [comment]
@TrippieHippie you can use annotator.text() to add content similar to how we use annotator.box_label:
```python
annotator.text(xy, text, txt_color=(255, 255, 255))
```
https://github.com/ultralytics/yolov5/blob/a18b0c36cd4df0d3b9c2623c5dda009c5f281ac9/detect.py#L225

**Comment by TrippieHippie** [comment]
> @TrippieHippie you can use annotator.text() to add content similar to how we use annotator.box_label:
> 
> ```python
> annotator.text(xy, text, txt_color=(255, 255, 255))
> ```
> 
> https://github.com/ultralytics/yolov5/blob/a18b0c36cd4df0d3b9c2623c5dda009c5f281ac9/detect.py#L225

@glenn-jocher I initially commented the annotator.box_label() and then, I am passing annotator.text() as follows:
annotator.text(xyxy, label, txt_color=colors(c, True))

But it throws the error as follows:
File "detect.py", line 311, in <module>
    main(opt)
  File "detect.py", line 306, in main
    run(**vars(opt))
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 229, in run
    annotator.text(xyxy, label, txt_color=(0,0,255))
  File "/content/yolov5/utils/plots.py", line 112, in text
    w, h = self.font.getsize(text)  # text width, height
AttributeError: 'Annotator' object has no attribute 'font'

I also tried to pass 1 color like color(0, 0, 255) but it did not work as well.

**Comment by glenn-jocher** [comment]
@TrippieHippie text methods are PIL-only, so when you create an instance you should pass pil=True. You can see these details by looking at the Annotator class:
https://github.com/ultralytics/yolov5/blob/a18b0c36cd4df0d3b9c2623c5dda009c5f281ac9/utils/plots.py#L64-L118

**Comment by TrippieHippie** [comment]
@glenn-jocher your suggested method worked but that is not what I am looking for.

![image](https://user-images.githubusercontent.com/63287376/137901798-bead3f0c-2a5d-4abb-9016-500159f46e83.png)
Above is the total number of objects detected in that specific frame (but it gets updated as new objects starts to pop by), I need to store those objects count for the lifetime of that video.

**Comment by glenn-jocher** [comment]
@TrippieHippie if you want accumulated counts then you should add `n` detections per class `c` here for every image/frame:
https://github.com/ultralytics/yolov5/blob/a18b0c36cd4df0d3b9c2623c5dda009c5f281ac9/detect.py#L210-L211

**Comment by TrippieHippie** [comment]
@glenn-jocher This is my code block:
                for c in det[:, -1].unique():
                    n = (det[:, -1] == c).sum()  # detections per class
                    s += '%g %ss, ' % (n, names[int(c)])  # add to string
                    cv2.putText(im0, s, (20,100), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)

As you can see, I am using that for loop code block but it gets overwrriten as we progress onwards in video frames. **I want values of objects to retain their previous values.** 
For eg: 
(Frame 10) Object A: 1, Object B: 4, Object C: 2
(Frame  30) Object A: 6, Object B: 8, Object C: 10, Object D: 5, Object E: 7 (**Adding new values to its existing ones**)

**Comment by itsrocchi** [comment]
@TrippieHippie hi! i know that a lot of time has passed, but can you remember if you figured out a way to solve the problem? i'm facing the same issue: i need to count the total number of different object in a video.
