### ISSUE TITLE
About model structure naming

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#5258]
@glenn-jocher 
As far as I can tell, the object detection network architecture is generally: `Backbone+Neck+Head`.But I only saw Backbone and Head in your yaml file. Through the analysis of the structure, the Head in yaml is actually Neck, and the Detect at the end of the Head is the so-called "Head". Can this be understood?

**Comment by glenn-jocher** [comment]
@Zengyf-CVer I don't really know. In reality there are no parts, the architecture is the architecture, and some people just like to call some parts certain things, but there may not be consensus on these made up labels.

In the YOLOv3 paper there is only a mention of 'backbone', nothing for either of your other two terms.

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
I also saw the structure of backbone+neck+head on the blog. I also feel very confused. Thank you for solving this doubt for me.
