### ISSUE TITLE
Closing webcam when specific object is detected

### ISSUE THREAD

**Issue by plonguini** [ultralytics/yolov5#5260]
What should I do to stop webcam feed after saving the cropped image of the found object? I mean: what should I add to the code so it stops automatically after saving the first cropped image from webcam feed?

**Comment by glenn-jocher** [comment]
@plonguini you can use CTRL+C or q to quit.

**Comment by plonguini** [comment]
Thank you @glenn-jocher for your reply! I've been doing this manually, but I was looking for a solution written in the code. My goal is to have it automatically stop after saving the cropped image from the first frame that contains a detection.

**Comment by glenn-jocher** [comment]
@plonguini in python you can exit any `while` or `for` loop with `break`, so just create some detection logic that runs a `break` command when you want to stop inference.
https://www.digitalocean.com/community/tutorials/how-to-use-break-continue-and-pass-statements-when-working-with-loops-in-python-3
