### ISSUE TITLE
About the settings of yaml in data

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#5264]
@glenn-jocher 
I recently discovered a new `test` in yolov5/data/coco128.yaml:
https://github.com/ultralytics/yolov5/blob/a18b0c36cd4df0d3b9c2623c5dda009c5f281ac9/data/coco128.yaml#L14
In the past, verification and testing used a directory, which is `val`, but I don’t know how to use the newly added `test`?

**Comment by glenn-jocher** [comment]
@Zengyf-CVer test images are optional as indicated. If you have test images then you can use val.py to get labels or mAP. COCO128 does not have any test images, so the field is empty.
```bash
python val.py --task val  # default
python val.py --task test  # use test set (if exists)
```

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
If I don't have a test set, I use the verification set to run val.py. Will this affect the model inference? Or will it affect the judgment of mAP?

**Comment by glenn-jocher** [comment]
@Zengyf-CVer that's fine. Most datasets don't have a test split anyway.

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
Thank you very much.
