### ISSUE TITLE
Using torch.tensors as an input for training

### ISSUE THREAD

**Issue by Skedaddler** [ultralytics/yolov5#5267]
## ❔Question

Greetings,

I need YoloV5 for detection on pytorch.tensors, but I have faced a problem. I did the next:
1. To label the data I transformed my tensor data into images 256x256
2. Then I did labeling with [Roboflow](https://roboflow.com/)
3. There I have divided the dataset into train, validation and test
4. I have put the exported data as tensor files (.pt) into path/<_train\valid\test_>/images
5. I have put labels .txt from Roboflow into path/<_train\valid\test_>/images
6. Ran the next command:
```
# Training yolo
!python train.py --img 256 --batch 16 --epochs 150 --data '/content/drive/MyDrive/Colab Notebooks/Defects_Classification/YoloV5s/data.yaml' --weights yolov5s.pt --cache
```
And I get an error that there is no images in the folder:
```
train: weights=yolov5s.pt, cfg=, data=/content/drive/MyDrive/Colab Notebooks/Defects_Classification/YoloV5s/data.yaml, hyp=data/hyps/hyp.scratch.yaml, epochs=150, batch_size=16, imgsz=256, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, evolve=None, bucket=, cache=ram, image_weights=False, device=, multi_scale=False, single_cls=False, adam=False, sync_bn=False, workers=8, project=runs/train, name=exp, exist_ok=False, quad=False, linear_lr=False, label_smoothing=0.0, patience=100, freeze=0, save_period=-1, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest
github: up to date with https://github.com/ultralytics/yolov5 ✅
YOLOv5 🚀 v6.0-16-g6d9b99f torch 1.9.0+cu111 CUDA:0 (Tesla K80, 11441.1875MB)

hyperparameters: lr0=0.01, lrf=0.1, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0
Weights & Biases: run 'pip install wandb' to automatically track and visualize YOLOv5 🚀 runs (RECOMMENDED)
TensorBoard: Start with 'tensorboard --logdir runs/train', view at http://localhost:6006/
Overriding model.yaml nc=80 with nc=1

                 from  n    params  module                                  arguments                     
  0                -1  1      3520  models.common.Conv                      [3, 32, 6, 2, 2]              
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]                
  2                -1  1     18816  models.common.C3                        [64, 64, 1]                   
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]               
  4                -1  2    115712  models.common.C3                        [128, 128, 2]                 
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]              
  6                -1  3    625152  models.common.C3                        [256, 256, 3]                 
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]              
  8                -1  1   1182720  models.common.C3                        [512, 512, 1]                 
  9                -1  1    656896  models.common.SPPF                      [512, 512, 5]                 
 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]              
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 12           [-1, 6]  1         0  models.common.Concat                    [1]                           
 13                -1  1    361984  models.common.C3                        [512, 256, 1, False]          
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]              
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 16           [-1, 4]  1         0  models.common.Concat                    [1]                           
 17                -1  1     90880  models.common.C3                        [256, 128, 1, False]          
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]              
 19          [-1, 14]  1         0  models.common.Concat                    [1]                           
 20                -1  1    296448  models.common.C3                        [256, 256, 1, False]          
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]              
 22          [-1, 10]  1         0  models.common.Concat                    [1]                           
 23                -1  1   1182720  models.common.C3                        [512, 512, 1, False]          
 24      [17, 20, 23]  1     16182  models.yolo.Detect                      [1, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
Model Summary: 270 layers, 7022326 parameters, 7022326 gradients, 15.8 GFLOPs

Transferred 343/349 items from yolov5s.pt
Scaled weight_decay = 0.0005
optimizer: SGD with parameter groups 57 weight, 60 weight (no decay), 60 bias
albumentations: version 1.0.3 required by YOLOv5, but version 0.1.12 is currently installed
Traceback (most recent call last):
  File "/content/yolov5/utils/datasets.py", line 410, in __init__
    assert self.img_files, f'{prefix}No images found'
AssertionError: train: No images found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 620, in <module>
    main(opt)
  File "train.py", line 517, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 213, in train
    prefix=colorstr('train: '))
  File "/content/yolov5/utils/datasets.py", line 108, in create_dataloader
    prefix=prefix)
  File "/content/yolov5/utils/datasets.py", line 412, in __init__
    raise Exception(f'{prefix}Error loading data from {path}: {e}\nSee {HELP_URL}')
Exception: train: Error loading data from /content/drive/MyDrive/Colab Notebooks/Defects_Classification/YoloV5s/train/images: train: No images found
See https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data
```

I had a look at a [custom training example](https://blog.roboflow.com/how-to-train-yolov5-on-a-custom-dataset/?ref=ultralytics) and the [Custom Training Notebook](https://colab.research.google.com/github/roboflow-ai/yolov5-custom-training-tutorial/blob/main/yolov5-custom-training.ipynb) but could not find any information about training on tensors. Brief look through issues also did not give a result.

So the questions are: 
1. How should training on pytorch.tensors look like? Can someone provide me an example, please?
2. Can the labels made in Roboflow work with tensors? (Because I am not sure that demand "Box coordinates must be in normalized xywh format" will work for tensors)
3. Should I make the same directories organisation as for images?
4. Can YoloV5 understand .pt input?

## Extra information
Containment of the data.yaml file:
```
train: /content/drive/MyDrive/Colab Notebooks/Defects_Classification/YoloV5s/train/images
val: /content/drive/MyDrive/Colab Notebooks/Defects_Classification/YoloV5s/valid/images

nc: 1
names: ['0']
```

**Data information:**
- 1 class to detect
- 455 torch.tensors shaped [3, 256, 256]
- 455 .txt labels made via Roboflow

Numpy version 1.19.5
Matplotlib version 3.2.2
Pytorch version 1.9.0+cu111
Python 3.7.12
Environment: Google Colab

A visualized tensor:
![image](https://user-images.githubusercontent.com/91888664/138088910-fe4700cf-955c-4d36-8d7c-f3933f35b629.png)

**Comment by ghost** [comment]
@Skedaddler Setup looks ok, I would suspect the space in the path to your images as the culprit.

**Comment by glenn-jocher** [comment]
@Skedaddler also you should ensure your images are in one of these compatible image formats for YOLOv5 to find them. Any other files will not be used for training. These are not case-sensetive, so both `img.JPG` and `img.jpg` are fine.
https://github.com/ultralytics/yolov5/blob/15e8c4c15bff0e3c729868e2c31f80f918e31fb2/utils/datasets.py#L36

**Comment by Skedaddler** [comment]
> @Skedaddler also you should ensure your images are in one of these compatible image formats for YOLOv5 to find them. Any other files will not be used for training. These are not case-sensetive, so both `img.JPG` and `img.jpg` are fine.
> 
> https://github.com/ultralytics/yolov5/blob/15e8c4c15bff0e3c729868e2c31f80f918e31fb2/utils/datasets.py#L36

My data are tensors, so they are in .pt format. Is there a way to train YOLOv5 on tensor files? Or the input command for tensors should be different?

**Comment by Skedaddler** [comment]
@softmatic I tried to use another path without spaces but unfortunately it did not work out.

**Comment by ghost** [comment]
@Skedaddler Yes, I had misunderstood your question. The train.py script expects your data to be in one of the standard image formats (JPEG etc.) so it will not import PT files directly. However, you should be able to import the images you used for labelling.

**Comment by Skedaddler** [comment]
> @Skedaddler Yes, I had misunderstood your question. The train.py script expects your data to be in one of the standard image formats (JPEG etc.) so it will not import PT files directly. However, you should be able to import the images you used for labelling.

But I will need to detect objects on tensor dataset after training. I have a plan B:
1. Train YOLOv5 on .png images made of tensors
2. To detect an object on a test data -> tranform torch.tensor to an image
3. Detect the object from the image -> get normalized coordinates of borders as YOLOv5 output
4. According to the size of tensor recalculate the normalized coordinated into tensors' indexes
5. Crop the area of tensor with calculated indexes
6. Send it to another NN

But I was hoping there is a way to work just with tensors without transferring it to images and back.

**Comment by ghost** [comment]
Your only option would be to write your own data loader. The loader converts the imported images to numpy arrays which are then delivered to train / detect. The respective class (LoadImages) is in util/datasets.py.
