### ISSUE TITLE
Creating custom OCR key value pair identification (ROI) with yolov5

### ISSUE THREAD

**Issue by saitej123** [ultralytics/yolov5#5272]
## 🚀 Feature
please share tutorial on how to fetch key value pair from document or scanned image

## Motivation
example : extract names and son from passport document , annotations with label studio and training the yolov5

**Comment by glenn-jocher** [comment]
@saitej123 for general OCR tasks it's possible another model may be more suitable than YOLOv5, or if you want to use YOLOv5 you'd need an alphanumeric dataset with 0-9 plus A-Z, lowercase and uppercase. 

An example license plate detector with second stage OCR model is here:
https://github.com/ultralytics/yolov5/issues/5244#issuecomment-948376866

**Comment by saitej123** [comment]
Faster rcnn may give good results on ROI detection for ocr .
