### ISSUE TITLE
Adding new classes on top of pre-trained model

### ISSUE THREAD

**Issue by Amulya2110** [ultralytics/yolov5#5273]
@glenn-jocher 
If we change the number of classes and class names in  coco.yaml file(config file)  and just give the new additional classes training images and train on top of the yolo pretrained weights(yolovs.pt) , will the yolo still be able to detect the earlier pre-trained classes? or-else any other suggestions on how we can achieve this?

Thankyou.

**Comment by glenn-jocher** [comment]
@Amulya2110 you must train on all classes you want your model to predict during deployment every time you train it. 

See https://en.wikipedia.org/wiki/Catastrophic_interference for details.

**Comment by Amulya2110** [comment]
@glenn-jocher  Thanks for the reply
