### ISSUE TITLE
Vide detection output to http stream

### ISSUE THREAD

**Issue by Piyushak** [ultralytics/yolov5#5274]
## ❔Question
I am using youtube live videos for detection and want the detection result through http stream instead of the detection result showing directly. I have done this in yolov4 using flask and also trying with yolov5 but unable to do. I am very new with yolov5, please tell how to do this?

**Comment by glenn-jocher** [comment]
@Piyushak hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

I don't know how to stream videos through http myself, so I can't be of assistance here unfortunately.

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
