### ISSUE TITLE
Using 2 yolov5 models together

### ISSUE THREAD

**Issue by ozlem-atiz** [ultralytics/yolov5#5277]
## Additional context
hi, i am making license plate recognition system in jetson xavier. in my project i am using the yolov5 model to find the license plate position. Now, I have labeled the data in the plate and trained using the yolov5 model. How can I use my best.pt trained file for character reading and the file for plate detection in the project together?
  Can I use both in the same project? thank you for your help
@glenn-jocher @jdfr  @cgerum @farleylai  @timstokman @adrianholovaty

**Comment by glenn-jocher** [comment]
@ozlem-atiz yes, you can load two models simultaneously for different detection tasks, i.e.:

```bash
import torch

# Model
yolov5s_model = torch.hub.load('ultralytics/yolov5', 'yolov5s')
yolov5m_model = torch.hub.load('ultralytics/yolov5', 'yolov5m')
```

**Comment by ozlem-atiz** [comment]
ok. Thanks sir @glenn-jocher  :)
