### ISSUE TITLE
Inference time is more in release 6 vs release 4 for custom trained model yolov5m.pt

### ISSUE THREAD

**Issue by myuvarajmp** [ultralytics/yolov5#5279]
## ❔Question
Hi All,

I have custom trained model for both yolov5 release 4 and release 6 using yolov5m.pt weights given to them. When I check the inference using Nvidia T4 GPU I get inference for 4 images in batch mode at 0.062 in release 6 and 0.036 in release 4. What all things i need to check in detect.py and what could be possible issue.

**Comment by glenn-jocher** [comment]
@myuvarajmp I tested both in Colab on a P100 GPU and see similar speeds as expected. In practice your speeds may vary by hardware, software and drivers.

<img width="1231" alt="Screen Shot 2021-10-21 at 5 04 55 PM" src="https://user-images.githubusercontent.com/26833433/138305924-cf566d3c-da15-4238-b2ce-0080d2ae6a48.png">
