### ISSUE TITLE
About optimization functions

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#5284]
@glenn-jocher 
I only found two optimization functions Adam and SGD in train.py. What other optimization methods are provided in the yolov5 project? Or how should I introduce other optimization methods?
https://github.com/ultralytics/yolov5/blob/15e8c4c15bff0e3c729868e2c31f80f918e31fb2/train.py#L149-L152

**Comment by glenn-jocher** [comment]
@Zengyf-CVer yes these are the two most common optimizers employed in Vision AI, but you can actually use any torch optimizer, i.e. `optimizer = torch.optim.RMSprop(g0, lr=hyp['lr0'], ...)`. The full list of torch optimizers is here:
https://pytorch.org/docs/stable/optim.html

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
If I use `--adam`, do I need to change the value of `lr0` in hyp.scratch.yaml to 0.001?Or does the program change automatically?
https://github.com/ultralytics/yolov5/blob/79d8f1f6785dcaabc018b40a6ffd1d0a4c1d25bf/data/hyps/hyp.scratch.yaml#L6

**Comment by glenn-jocher** [comment]
@Zengyf-CVer if you use `--adam` you'll generally want to use an lr0 about 10x smaller than what you use for SGD. This is **not** adjusted automatically (to prevent confusion). This is a rough guideline, so I would experiment around that, i.e. try 5x, 10x, 20x smaller to start. You can see this guidance in your hyp file:
https://github.com/ultralytics/yolov5/blob/79d8f1f6785dcaabc018b40a6ffd1d0a4c1d25bf/data/hyps/hyp.scratch.yaml#L6

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
As far as I know, SGD is an older algorithm compared to Adam, but I did a comparative experiment and found that Adam (lr0=0.001) is not as high as the mAP value of SGD (lr0=0.01). Why? In theory, Adam should be better than SGD, but I did a lot of experiments and the result was not like this. Is it related to the architecture of YOLOv5?

**Comment by glenn-jocher** [comment]
@Zengyf-CVer different nonlinear optimizers are suited to different problems, there's not really a one-size fits all solution. SGD is of course one of the simplest and easiest to understand, it simply rolls downhill towards a local minima given user supplied momentum and lr, so there's not a lot to go wrong.

It's possible Adam is better suited to other problems, or to a different location in the hyperparameter space, given that our current hyperparameters I evolved in conjunction with the SGD optimizer.

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
Thank you very much.
