### ISSUE TITLE
Is there any way that I can do to change the label name of the model?

### ISSUE THREAD

**Issue by Git-pengyu** [ultralytics/yolov5#5286]
## ❔Question
Is there any way that I can do to change the label name of the model?

**Comment by glenn-jocher** [comment]
@Git-pengyu yes, the labels are simply stored as an array that is an attribute of the model. You can redefine this and resave your model. 
```python
model.names = ['person', ...]
```

See train.py for model saving code:
https://github.com/ultralytics/yolov5/blob/441b47c443c163040536511f76a5ba2a086e4803/train.py#L371-L382
