### ISSUE TITLE
Why are weights so much lighter than YOLOv4?

### ISSUE THREAD

**Issue by 4444borja** [ultralytics/yolov5#529]
The model file (.pt) used for inference weights ~14 MB, but in the YOLOv4 repository the .weights file takes ~250 MB.
I understand the changes have to do with this implementation using PyTorch instead of C, but I don't understand how you achieve to put what used to take 250 MB into a 14 MB file.

I'm just trying to understand how this implementation works, any help is much appreciated.
Thanks in advance.

**Comment by glenn-jocher** [comment]
@4444borja this is YOLOv5, our weights have nothing in common with v4. You are starting with an assumption that they should be similar, which is incorrect.

**Comment by 4444borja** [comment]
> @4444borja this is YOLOv5, our weights have nothing in common with v4. You are starting with an assumption that they should be similar, which is incorrect.

Thank you for the response. What I was referring to is the fact that to save the model you need to save all the parameters, and being such a big model the parameters are apparently too big to fit on ~14 MB.

Did you guys use some compression optimization to achieve this?

**Comment by gnefihs** [comment]
the sizes of the smaller networks are closer to YOLOv3-tiny which is ~30MB. And then it's probably halved because of:

> June 19, 2020: FP16 as new default for smaller checkpoints and faster inference d4c6674.

**Comment by 4444borja** [comment]
It seems that model quantization is part of what makes the model so small in comparison. Thanks a lot for the help @gnefihs !

**Comment by Linranran** [comment]
did someone know why my yolov5s.pt is 55MB?
