### ISSUE TITLE
How to adjust YOLO bbox when cropping the image before training?

### ISSUE THREAD

**Issue by sarmientoj24** [ultralytics/yolov5#5290]
## ❔Question
I have an image with YOLO bbox labels. I wish to crop the image that still has the bbox labels. How do I adjust the bbox labels of YOLO when applying the cropping procedure? The crop can be something like [x1, y1, x2, y2] coordinates where to crop it.

**Comment by glenn-jocher** [comment]
@sarmientoj24 subtract x1 and y1 from your labels.

**Comment by sarmientoj24** [comment]
which parts of the labels? also, is it only x1 and y1? I shall be cropping inside the image not just a small part of it. And how do i subtract a non-normalized width and height?

**Comment by glenn-jocher** [comment]
@sarmientoj24 these questions fall outside the scope of YOLOv5 support I believe, as they relate to simple reference frame transformations. If you have a point with respect to an origin, and you want to express it with respect to a new origin the process is pretty simple, you just subtract the new origin from the point.
