### ISSUE TITLE
About anchors are settings

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#5291]
@glenn-jocher 
I compared yaml files such as yolov5-p6 and yolov5n6 and found that the anchors settings are different:
https://github.com/ultralytics/yolov5/blob/15e8c4c15bff0e3c729868e2c31f80f918e31fb2/models/hub/yolov5-p6.yaml#L7
https://github.com/ultralytics/yolov5/blob/15e8c4c15bff0e3c729868e2c31f80f918e31fb2/models/hub/yolov5n6.yaml#L7-L11
Do these two have any effect on model training? Because I know there is an automatic anchor box algorithm, so I don’t know the difference between the two?

**Comment by glenn-jocher** [comment]
@Zengyf-CVer all the p6 models like n6, s6, etc. use the same evolved anchors on COCO that you see in their yamls. anchors: 3 tells YOLOv5 to evolve 3 anchors per output layer, which if done on COCO will result in the same values as n6.

**Comment by Zengyf-CVer** [comment]
@glenn-joche
Thank you very much.
