### ISSUE TITLE
Questions about C3 in Head

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#5292]
@glenn-jocher 
I found that all C3 shortcuts in Head are disabled. Is there any advantage to this setting?
https://github.com/ultralytics/yolov5/blob/15e8c4c15bff0e3c729868e2c31f80f918e31fb2/models/yolov5n.yaml#L32
https://github.com/ultralytics/yolov5/blob/15e8c4c15bff0e3c729868e2c31f80f918e31fb2/models/yolov5n.yaml#L37
https://github.com/ultralytics/yolov5/blob/15e8c4c15bff0e3c729868e2c31f80f918e31fb2/models/yolov5n.yaml#L41
https://github.com/ultralytics/yolov5/blob/15e8c4c15bff0e3c729868e2c31f80f918e31fb2/models/yolov5n.yaml#L45

**Comment by glenn-jocher** [comment]
@Zengyf-CVer yes they are set this way due to experimental results.
