### ISSUE TITLE
Differentiating objects of same class

### ISSUE THREAD

**Issue by usedeeplearning** [ultralytics/yolov5#5295]

**Comment by glenn-jocher** [comment]
@usedeeplearning can you be more specific in your question? If multiple people are detected then they are already separately detected.

**Comment by usedeeplearning** [comment]
i am working on classifying shots played by both the players in a game of tennis so shots played by each player are different that is why i want to classify them as player 1 and player 2

**Comment by glenn-jocher** [comment]
@usedeeplearning you may need a tracking solution then, i.e. EKF, KLT, [DeepSort](https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch) etc.

**Comment by usedeeplearning** [comment]
okay thanks a lot will try out this approach
