### ISSUE TITLE
yolov5 model training imagenet_det data set, 300 epochs can only reach 35mAP, which is still far away from SOTA68 mAP, what is the reason?

### ISSUE THREAD

**Issue by ahong007007** [ultralytics/yolov5#5297]
Thank you for your work.
## ❔Question

yolov5 model training imagenet_det data set, 300 epochs can only reach 35mAP, which is still far away from SOTA68 mAP, what is the reason?
The yolov5x used by the model, the initial weight is empty

## Additional context

[34m[1mtrain: [0mdata_dir=/tmp/coco, output_dir=/mnt/mesos/sandbox/output/yolov5_detection211018110006, model_dir=, weights=, cfg=./models/yolov5x.yaml, data=imagenet_det.yaml, hyp=data/hyps/hyp.scratch.yaml, epochs=500, batch_size=128, imgsz=640, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, evolve=None, bucket=, cache=None, image_weights=False, device=0,1,2,3,4,5,6,7, multi_scale=False, single_cls=False, adam=False, sync_bn=False, workers=8, project=runs/train, entity=None, name=exp, exist_ok=False, quad=False, linear_lr=False, label_smoothing=0.0, upload_dataset=False, bbox_interval=-1, save_period=-1, artifact_alias=latest, local_rank=0, freeze=0
[34m[1mgithub: [0mskipping check (offline), for updates see https://github.com/ultralytics/yolov5
[34m[1mWeights & Biases: [0mrun 'pip install wandb' to automatically track and visualize YOLOv5 🚀 runs (RECOMMENDED)
Plotting labels... 

[34m[1mautoanchor: [0mAnalyzing anchors... anchors/target = 3.35, Best Possible Recall (BPR) = 0.9991
                 all      20120      55446      0.494     0.0453       0.01    0.00452
                 all      20120      55446      0.485     0.0959     0.0538     0.0288
                 all      20120      55446      0.318      0.168      0.109     0.0627
                 all      20120      55446      0.358       0.21      0.168      0.104
                 all      20120      55446      0.324      0.261      0.208      0.132
                 all      20120      55446      0.391       0.26      0.232       0.15
                 all      20120      55446      0.389      0.273      0.244      0.158
                 all      20120      55446      0.396      0.274      0.253      0.165
                 all      20120      55446      0.392      0.281      0.258      0.169
                 all      20120      55446      0.402      0.284      0.262      0.172
                 all      20120      55446      0.391      0.295      0.267      0.175
                 all      20120      55446      0.379        0.3      0.272      0.178
                 all      20120      55446      0.407      0.299      0.279      0.183
                 all      20120      55446      0.435      0.295      0.287      0.189
                 all      20120      55446      0.456      0.299      0.297      0.195
                 all      20120      55446      0.467      0.306      0.307      0.203
                 all      20120      55446      0.415      0.336      0.318      0.211
                 all      20120      55446      0.438       0.34      0.328      0.219
                 all      20120      55446      0.446      0.346      0.338      0.227
                 all      20120      55446      0.483      0.341      0.346      0.234
                 all      20120      55446      0.472      0.355      0.355       0.24
                 all      20120      55446      0.495      0.355      0.363      0.246
                 all      20120      55446      0.497      0.363       0.37      0.251
                 all      20120      55446      0.507      0.367      0.377      0.257
                 all      20120      55446      0.476      0.392      0.384      0.262
                 all      20120      55446      0.502      0.388      0.391      0.267
                 all      20120      55446      0.523      0.386      0.395      0.271
                 all      20120      55446       0.52      0.391      0.401      0.274
                 all      20120      55446      0.513        0.4      0.405      0.277
                 all      20120      55446      0.516      0.404      0.409       0.28
                 all      20120      55446      0.506      0.412      0.412      0.283
                 all      20120      55446      0.544      0.401      0.416      0.286
                 all      20120      55446      0.522      0.412      0.418      0.288
                 all      20120      55446      0.531      0.411      0.422      0.291
                 all      20120      55446      0.548      0.404      0.424      0.292
                 all      20120      55446      0.535      0.412      0.426      0.294
                 all      20120      55446      0.548       0.41      0.428      0.296
                 all      20120      55446      0.525      0.423       0.43      0.297
                 all      20120      55446      0.555      0.412      0.432      0.299
                 all      20120      55446      0.527      0.426      0.434        0.3
                 all      20120      55446      0.548       0.42      0.437      0.301
                 all      20120      55446       0.53      0.429      0.438      0.303
                 all      20120      55446      0.568      0.419      0.441      0.305
                 all      20120      55446      0.563      0.422      0.443      0.306
                 all      20120      55446       0.56      0.424      0.444      0.307
                 all      20120      55446       0.54      0.433      0.444      0.308
                 all      20120      55446      0.549      0.432      0.445      0.309
                 all      20120      55446       0.57      0.428      0.447       0.31
                 all      20120      55446       0.54      0.439      0.448      0.311
                 all      20120      55446       0.57      0.427      0.449      0.312
                 all      20120      55446      0.552      0.436       0.45      0.313
                 all      20120      55446      0.517      0.454      0.452      0.314
                 all      20120      55446      0.547      0.442      0.453      0.315
                 all      20120      55446      0.538      0.446      0.454      0.316
                 all      20120      55446      0.529      0.455      0.455      0.316
                 all      20120      55446      0.547      0.447      0.456      0.317
                 all      20120      55446      0.527      0.455      0.456      0.318
                 all      20120      55446      0.551      0.445      0.457      0.318
                 all      20120      55446      0.531      0.456      0.457      0.318
                 all      20120      55446      0.553      0.444      0.458      0.319
                 all      20120      55446      0.557      0.442      0.459       0.32
                 all      20120      55446      0.548      0.449      0.461      0.321
                 all      20120      55446       0.56      0.445      0.462      0.322
                 all      20120      55446      0.572      0.441      0.462      0.322
                 all      20120      55446       0.58      0.437      0.462      0.322
                 all      20120      55446      0.575      0.439      0.463      0.323
                 all      20120      55446      0.556      0.451      0.463      0.323
                 all      20120      55446      0.534       0.46      0.463      0.323
                 all      20120      55446      0.555      0.449      0.464      0.323
                 all      20120      55446      0.567      0.447      0.464      0.323
                 all      20120      55446      0.553      0.455      0.465      0.324
                 all      20120      55446      0.546      0.459      0.465      0.324
                 all      20120      55446      0.554      0.456      0.465      0.324
                 all      20120      55446      0.567      0.451      0.466      0.325
                 all      20120      55446      0.552      0.461      0.467      0.326
                 all      20120      55446      0.555      0.458      0.467      0.326
                 all      20120      55446      0.564      0.454      0.467      0.326
                 all      20120      55446      0.558      0.458      0.468      0.326
                 all      20120      55446      0.554      0.459      0.468      0.327
                 all      20120      55446      0.546      0.465      0.468      0.328
                 all      20120      55446      0.557      0.459      0.469      0.328
                 all      20120      55446      0.569      0.456       0.47      0.328
                 all      20120      55446      0.561       0.46       0.47      0.329
                 all      20120      55446       0.57      0.456       0.47      0.329
                 all      20120      55446      0.569      0.456       0.47      0.329
                 all      20120      55446      0.581      0.451      0.472       0.33
                 all      20120      55446      0.597      0.443      0.471       0.33
                 all      20120      55446      0.575      0.453      0.471      0.329
                 all      20120      55446      0.562      0.459      0.472      0.329
                 all      20120      55446      0.552      0.467      0.472       0.33
                 all      20120      55446      0.576      0.454      0.474      0.331
                 all      20120      55446       0.56      0.462      0.474      0.331
                 all      20120      55446      0.555      0.467      0.475      0.332
                 all      20120      55446      0.566      0.463      0.475      0.332
                 all      20120      55446      0.555      0.469      0.475      0.332
                 all      20120      55446      0.555       0.47      0.476      0.333
                 all      20120      55446      0.554      0.471      0.476      0.333
                 all      20120      55446      0.574      0.462      0.476      0.333
                 all      20120      55446      0.565      0.467      0.476      0.333
                 all      20120      55446      0.565      0.468      0.477      0.334
                 all      20120      55446      0.585      0.459      0.478      0.335
                 all      20120      55446      0.579      0.462      0.479      0.335
                 all      20120      55446      0.574      0.465      0.479      0.335
                 all      20120      55446      0.575      0.467      0.479      0.335
                 all      20120      55446      0.572      0.468      0.479      0.335
                 all      20120      55446      0.581      0.465       0.48      0.335
                 all      20120      55446      0.585      0.463       0.48      0.335
                 all      20120      55446      0.561      0.475       0.48      0.335
                 all      20120      55446       0.57      0.471       0.48      0.336
                 all      20120      55446      0.573      0.471       0.48      0.336
                 all      20120      55446      0.604      0.457      0.481      0.337
                 all      20120      55446      0.598      0.462      0.481      0.337
                 all      20120      55446      0.591      0.461       0.48      0.337
                 all      20120      55446      0.607      0.455       0.48      0.336
                 all      20120      55446      0.579      0.469      0.482      0.337
                 all      20120      55446       0.59      0.465      0.481      0.337
                 all      20120      55446      0.599      0.462      0.482      0.338
                 all      20120      55446      0.587      0.468      0.483      0.338
                 all      20120      55446      0.585       0.47      0.484      0.339
                 all      20120      55446      0.596      0.463      0.484      0.339
                 all      20120      55446       0.57      0.474      0.484      0.338
                 all      20120      55446      0.592      0.464      0.484      0.339
                 all      20120      55446      0.568      0.476      0.485      0.339
                 all      20120      55446      0.568      0.475      0.485      0.339
                 all      20120      55446      0.554      0.482      0.485       0.34
                 all      20120      55446      0.564      0.477      0.485       0.34
                 all      20120      55446      0.552      0.484      0.485       0.34
                 all      20120      55446      0.555      0.483      0.485       0.34
                 all      20120      55446      0.564      0.478      0.486       0.34
                 all      20120      55446      0.573      0.476      0.486       0.34
                 all      20120      55446      0.589       0.47      0.486       0.34
                 all      20120      55446      0.591      0.468      0.486       0.34
                 all      20120      55446      0.569      0.478      0.486       0.34
                 all      20120      55446      0.565      0.481      0.487      0.341
                 all      20120      55446      0.575      0.476      0.488      0.341
                 all      20120      55446      0.601      0.463      0.488      0.341
                 all      20120      55446      0.591      0.468      0.488      0.341
                 all      20120      55446      0.578      0.474      0.489      0.342
                 all      20120      55446       0.57      0.478      0.489      0.342
                 all      20120      55446      0.579      0.474      0.489      0.342
                 all      20120      55446      0.595      0.465      0.489      0.342
                 all      20120      55446      0.588       0.47       0.49      0.343
                 all      20120      55446      0.587      0.469      0.489      0.343
                 all      20120      55446      0.574      0.477      0.489      0.343
                 all      20120      55446      0.612      0.458       0.49      0.344
                 all      20120      55446      0.562      0.484       0.49      0.344
                 all      20120      55446      0.603      0.463      0.491      0.345
                 all      20120      55446      0.599      0.465      0.491      0.345
                 all      20120      55446      0.595      0.467      0.492      0.346
                 all      20120      55446      0.566      0.482      0.493      0.346
                 all      20120      55446      0.583      0.475      0.494      0.347
                 all      20120      55446      0.593      0.472      0.494      0.347
                 all      20120      55446      0.572      0.483      0.494      0.347
                 all      20120      55446      0.606      0.466      0.495      0.348
                 all      20120      55446      0.593      0.473      0.494      0.347
                 all      20120      55446      0.581      0.481      0.495      0.348
                 all      20120      55446      0.596      0.476      0.496      0.349
                 all      20120      55446      0.578      0.485      0.496      0.348
                 all      20120      55446      0.602      0.472      0.497      0.349
                 all      20120      55446      0.599      0.474      0.497      0.349
                 all      20120      55446      0.589      0.481      0.498      0.349
                 all      20120      55446      0.584      0.485      0.498      0.349
                 all      20120      55446      0.602      0.477      0.499       0.35
                 all      20120      55446       0.59      0.482      0.498      0.349
                 all      20120      55446      0.615      0.469      0.499       0.35
                 all      20120      55446      0.597      0.481        0.5      0.351
                 all      20120      55446      0.617      0.469      0.499      0.351
                 all      20120      55446      0.598      0.478        0.5      0.352
                 all      20120      55446      0.595      0.482      0.501      0.352
                 all      20120      55446      0.603      0.478      0.501      0.352
                 all      20120      55446      0.587      0.485      0.501      0.352
                 all      20120      55446       0.58      0.488        0.5      0.352
                 all      20120      55446      0.594      0.484        0.5      0.352
                 all      20120      55446      0.591      0.485        0.5      0.352
                 all      20120      55446      0.602      0.478        0.5      0.353
                 all      20120      55446      0.601      0.478        0.5      0.352
                 all      20120      55446      0.585      0.488        0.5      0.352
                 all      20120      55446      0.591      0.486      0.501      0.352
                 all      20120      55446      0.598      0.482      0.501      0.352
                 all      20120      55446        0.6      0.481      0.502      0.353
                 all      20120      55446      0.609      0.476      0.501      0.352
                 all      20120      55446      0.606      0.476      0.501      0.353
                 all      20120      55446       0.59      0.485      0.502      0.353
                 all      20120      55446      0.604      0.479      0.502      0.353
                 all      20120      55446      0.598      0.483      0.502      0.353
                 all      20120      55446        0.6      0.483      0.503      0.354
                 all      20120      55446      0.612       0.48      0.504      0.355
                 all      20120      55446      0.585      0.497      0.505      0.355
                 all      20120      55446      0.593      0.491      0.506      0.356
                 all      20120      55446      0.593      0.492      0.506      0.357
                 all      20120      55446      0.586      0.495      0.506      0.357
                 all      20120      55446      0.585      0.494      0.507      0.357
                 all      20120      55446      0.568      0.505      0.507      0.358
                 all      20120      55446      0.589      0.492      0.507      0.358
                 all      20120      55446      0.607      0.483      0.507      0.357
                 all      20120      55446      0.583      0.498      0.509      0.358
                 all      20120      55446      0.602      0.487      0.509      0.358
                 all      20120      55446      0.597      0.491      0.509      0.358
                 all      20120      55446      0.598       0.49      0.509      0.359
                 all      20120      55446       0.58      0.501      0.509      0.359
                 all      20120      55446      0.598      0.491      0.509       0.36
                 all      20120      55446      0.605      0.488      0.511      0.359
                 all      20120      55446      0.625      0.476       0.51      0.359
                 all      20120      55446      0.607      0.487       0.51      0.359
                 all      20120      55446      0.627      0.478       0.51       0.36
                 all      20120      55446      0.612      0.486      0.511       0.36
                 all      20120      55446      0.599      0.493      0.511      0.361
                 all      20120      55446      0.614      0.484      0.511      0.361
                 all      20120      55446       0.61      0.488      0.512      0.361
                 all      20120      55446      0.616      0.485      0.513      0.362
                 all      20120      55446      0.623      0.484      0.514      0.363
                 all      20120      55446      0.624      0.485      0.515      0.363
                 all      20120      55446      0.614      0.489      0.515      0.363
                 all      20120      55446       0.62      0.486      0.515      0.363
                 all      20120      55446      0.617      0.491      0.516      0.363
                 all      20120      55446      0.618       0.49      0.517      0.364
                 all      20120      55446      0.592      0.505      0.517      0.364
                 all      20120      55446      0.603      0.501      0.516      0.364
                 all      20120      55446      0.608      0.497      0.516      0.363
                 all      20120      55446      0.609      0.496      0.516      0.364
                 all      20120      55446      0.594      0.503      0.516      0.364
                 all      20120      55446       0.61      0.496      0.517      0.364
                 all      20120      55446      0.625      0.488      0.517      0.365
                 all      20120      55446      0.604      0.499      0.518      0.365
                 all      20120      55446      0.599      0.503      0.518      0.365
                 all      20120      55446      0.611      0.497      0.519      0.366
                 all      20120      55446      0.609      0.497      0.518      0.366
                 all      20120      55446      0.603        0.5      0.518      0.366
                 all      20120      55446      0.596      0.503      0.519      0.366
                 all      20120      55446      0.627      0.485      0.519      0.366
                 all      20120      55446      0.607      0.498      0.519      0.366
                 all      20120      55446      0.605      0.496      0.519      0.366
                 all      20120      55446      0.609      0.495      0.519      0.366
                 all      20120      55446      0.616      0.492      0.521      0.368
                 all      20120      55446        0.6      0.503      0.522      0.368
                 all      20120      55446      0.618      0.494      0.522      0.368
                 all      20120      55446      0.624      0.491      0.522      0.369
                 all      20120      55446      0.603      0.503      0.522      0.369
                 all      20120      55446      0.607      0.498      0.522      0.369
                 all      20120      55446      0.615      0.497      0.522      0.369
                 all      20120      55446      0.606      0.501      0.523       0.37
                 all      20120      55446      0.596      0.509      0.524       0.37
                 all      20120      55446      0.624      0.494      0.525      0.371
                 all      20120      55446      0.625      0.497      0.525      0.371
                 all      20120      55446      0.622      0.497      0.525      0.371
                 all      20120      55446      0.625      0.498      0.526      0.371
                 all      20120      55446      0.621      0.499      0.526      0.371
                 all      20120      55446      0.613      0.503      0.527      0.372
                 all      20120      55446       0.61      0.507      0.527      0.372
                 all      20120      55446      0.622      0.501      0.528      0.373
                 all      20120      55446      0.611      0.507      0.528      0.373
                 all      20120      55446       0.63      0.498      0.529      0.374
                 all      20120      55446       0.62      0.503      0.529      0.374
                 all      20120      55446      0.622      0.502       0.53      0.374
                 all      20120      55446      0.626        0.5       0.53      0.375
                 all      20120      55446      0.621      0.503       0.53      0.375
                 all      20120      55446      0.609      0.509       0.53      0.375
                 all      20120      55446      0.622      0.503      0.531      0.375

**Comment by glenn-jocher** [comment]
@ahong007007 👋 Hello! Thanks for asking about improving YOLOv5 🚀 training results. 

This dataset is not among our [autodownload datasets in data/](https://github.com/ultralytics/yolov5/tree/master/data) so I won't be able to reproduce your training results. Please consider adding your new dataset to YOLOv5 to help future users easily start training on it by submitting a PR, i.e. an `ImageNetDet.yaml`.

Most of the time good results can be obtained with no changes to the models or training settings, **provided your dataset is sufficiently large and well labelled**. If at first you don't get good results, there are steps you might be able to take to improve, but we always recommend users **first train with all default settings** before considering any changes. This helps establish a performance baseline and spot areas for improvement.

If you have questions about your training results **we recommend you provide the maximum amount of information possible** if you expect a helpful response, including results plots (train losses, val losses, P, R, mAP), PR curve, confusion matrix, training mosaics, test results and dataset statistics images such as labels.png. All of these are located in your `project/name` directory, typically `yolov5/runs/train/exp`.

We've put together a full guide for users looking to get the best results on their YOLOv5 trainings below.

## Dataset

- **Images per class.** ≥ 1500 images per class recommended
- **Instances per class.** ≥ 10000 instances (labeled objects) per class recommended
- **Image variety.** Must be representative of deployed environment. For real-world use cases we recommend images from different times of day, different seasons, different weather, different lighting, different angles, different sources (scraped online, collected locally, different cameras) etc.
- **Label consistency.** All instances of all classes in all images must be labelled. Partial labelling will not work.
- **Label accuracy.** Labels must closely enclose each object. No space should exist between an object and it's bounding box. No objects should be missing a label.
- **Background images.** Background images are images with no objects that are added to a dataset to reduce False Positives (FP). We recommend about 0-10% background images to help reduce FPs (COCO has 1000 background images for reference, 1% of the total). No labels are required for background images.

<a href="https://arxiv.org/abs/1405.0312"><img width="800" src="https://user-images.githubusercontent.com/26833433/109398377-82b0ac00-78f1-11eb-9c76-cc7820669d0d.png" alt="COCO Analysis"></a>


## Model Selection

Larger models like YOLOv5x and [YOLOv5x6](https://github.com/ultralytics/yolov5/releases/tag/v5.0) will produce better results in nearly all cases, but have more parameters, require more CUDA memory to train, and are slower to run. For **mobile** deployments we recommend YOLOv5s/m, for **cloud** deployments we recommend YOLOv5l/x. See our README [table](https://github.com/ultralytics/yolov5#pretrained-checkpoints) for a full comparison of all models. 

<p align="center"><img width="700" alt="YOLOv5 Models" src="https://github.com/ultralytics/yolov5/releases/download/v1.0/model_comparison.png"></p>

- **Start from Pretrained weights.** Recommended for small to medium sized datasets (i.e. VOC, VisDrone, GlobalWheat). Pass the name of the model to the `--weights` argument. Models download automatically from the [latest YOLOv5 release](https://github.com/ultralytics/yolov5/releases).
```bash
python train.py --data custom.yaml --weights yolov5s.pt
                                             yolov5m.pt
                                             yolov5l.pt
                                             yolov5x.pt
                                             custom_pretrained.pt
```
- **Start from Scratch.** Recommended for large datasets (i.e. COCO, Objects365, OIv6). Pass the model architecture yaml you are interested in, along with an empty `--weights ''` argument:
```bash
python train.py --data custom.yaml --weights '' --cfg yolov5s.yaml
                                                      yolov5m.yaml
                                                      yolov5l.yaml
                                                      yolov5x.yaml
```


## Training Settings

Before modifying anything, **first train with default settings to establish a performance baseline**. A full list of train.py settings can be found in the [train.py](https://github.com/ultralytics/yolov5/blob/master/train.py) argparser.

- **Epochs.** Start with 300 epochs. If this overfits early then you can reduce epochs. If overfitting does not occur after 300 epochs, train longer, i.e. 600, 1200 etc epochs.
- **Image size.** COCO trains at native resolution of `--img 640`, though due to the high amount of small objects in the dataset it can benefit from training at higher resolutions such as `--img 1280`. If there are many small objects then custom datasets will benefit from training at native or higher resolution. Best inference results are obtained at the same `--img` as the training was run at, i.e. if you train at `--img 1280` you should also test and detect at `--img 1280`.
- **Batch size.** Use the largest `--batch-size` that your hardware allows for. Small batch sizes produce poor batchnorm statistics and should be avoided.
- **Hyperparameters.** Default hyperparameters are in [hyp.scratch.yaml](https://github.com/ultralytics/yolov5/blob/master/data/hyp.scratch.yaml). We recommend you train with default hyperparameters first before thinking of modifying any. In general, increasing augmentation hyperparameters will reduce and delay overfitting, allowing for longer trainings and higher final mAP. Reduction in loss component gain hyperparameters like `hyp['obj']` will help reduce overfitting in those specific loss components. For an automated method of optimizing these hyperparameters, see our [Hyperparameter Evolution Tutorial](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution).

## Further Reading

If you'd like to know more a good place to start is Karpathy's 'Recipe for Training Neural Networks', which has great ideas for training that apply broadly across all ML domains:
http://karpathy.github.io/2019/04/25/recipe/
