### ISSUE TITLE
something wrong with train_batch*.jpg

### ISSUE THREAD

**Issue by SummerFoam233** [ultralytics/yolov5#5301]
## ❔Question
When I was training the images after labeled in yolov5 3.0 project,I found the train_batch*.jpg appears a strange problem like below：
![train_batch1](https://user-images.githubusercontent.com/81640649/138471937-8c48d5a9-d708-40b4-a369-075f1c58ceca.jpg)

And after training,the index was also very terrible like below:
![results](https://user-images.githubusercontent.com/81640649/138471948-9eab3117-1be1-480e-a0dd-0eb3fe3185a5.png)

And this is my origin dataset and labeling process:
![image](https://user-images.githubusercontent.com/81640649/138472108-14289ead-8245-42e8-a0d9-3a0257107884.png)
![image](https://user-images.githubusercontent.com/81640649/138472267-4cd40e0a-b807-40cc-9385-6d55ba9a6dd8.png)

So what's the reason for this problem?

**Comment by glenn-jocher** [comment]
@SummerFoam233 your labels are not correct. Please see Train Custom Data tutorial for label guidance. Labels must be in xywh normalized format:
https://docs.ultralytics.com/yolov5/tutorials/train_custom_data

### 1.2 Create Labels

After using a tool like [Roboflow Annotate](https://roboflow.com/annotate?ref=ultralytics) to label your images, export your labels to **YOLO format**, with one `*.txt` file per image (if no objects in image, no `*.txt` file is required). The `*.txt` file specifications are:

- One row per object
- Each row is `class x_center y_center width height` format.
- Box coordinates must be in **normalized xywh** format (from 0 - 1). If your boxes are in pixels, divide `x_center` and `width` by image width, and `y_center` and `height` by image height.
- Class numbers are zero-indexed (start from 0).

<img width="800" alt="Image Labels" src="https://user-images.githubusercontent.com/26833433/91506361-c7965000-e886-11ea-8291-c72b98c25eec.jpg">

The label file corresponding to the above image contains 2 persons (class `0`) and a tie (class `27`):

<p align="center"><img width="428" src="https://user-images.githubusercontent.com/26833433/112467037-d2568c00-8d66-11eb-8796-55402ac0d62f.png"></p>


### 1.3 Organize Directories

Organize your train and val images and labels according to the example below. YOLOv5 assumes  `/coco128` is inside a `/datasets` directory **next to** the `/yolov5` directory. **YOLOv5 locates labels automatically for each image** by replacing the last instance of `/images/` in each image path with `/labels/`. For example:
```bash
../datasets/coco128/images/im0.jpg  # image
../datasets/coco128/labels/im0.txt  # label
```

<p align="center"><img width="700" src="https://user-images.githubusercontent.com/26833433/134436012-65111ad1-9541-4853-81a6-f19a3468b75f.png"></p>
</details>
