### ISSUE TITLE
is there any data enhancement for image rotation when yolov5 is training? How many degrees does it generally rotate? Can it be rotated 180 degrees?

### ISSUE THREAD

**Issue by ahong007007** [ultralytics/yolov5#5307]
## ❔Question
Please tell me, is there any data enhancement for image rotation when yolov5 is training? How many degrees does it generally rotate? Can it be rotated 180 degrees? Where to set it up? 

Thank you for your hard work.

**Comment by glenn-jocher** [comment]
@ahong007007 👋 Hello! Thanks for asking about **image augmentation**. YOLOv5 🚀 applies online imagespace and colorspace augmentations in the trainloader (but not the testloader) to present a new and unique augmented [Mosaic](https://github.com/ultralytics/yolov5/blob/90b7895d652c3bd3d361b2d6e9aee900fd67f5f7/utils/datasets.py#L678-L732) (original image + 3 random images) each time an image is loaded for training. **Images are never presented twice in the same way**.

![YOLOv5 augmentation](https://user-images.githubusercontent.com/26833433/120995721-f3cfed00-c785-11eb-8ee2-b6ef2fa205e8.jpg)

The hyperparameters (**including `degrees` for rotation**) used to define these augmentations are in your hyperparameter file (default `data/hyp.scratch.yaml`) defined when training:
```
python train.py --hyp hyp.scratch.yaml
```
https://github.com/ultralytics/yolov5/blob/90b7895d652c3bd3d361b2d6e9aee900fd67f5f7/data/hyp.scratch.yaml#L1-L33

Valid `degrees` range from +/- 0 (no rotation) to +/- 180 (full random rotation).

You can view the effect of your augmentation policy in your train_batch*.jpg images once training starts. These images will be in your train logging directory, typically `yolov5/runs/train/exp`:

`train_batch0.jpg` shows train batch 0 mosaics and labels:  
> <img src="https://user-images.githubusercontent.com/26833433/131255960-b536647f-7c61-4f60-bbc5-cb2544d71b2a.jpg" width="700">

Good luck and let us know if you have any other questions!
