### ISSUE TITLE
filter by class == 0 didnt work, but other not ? why?

### ISSUE THREAD

**Issue by lmcltj** [ultralytics/yolov5#531]
## ❔Question
Thanks for such a good job of open source.
I want to use the trained model in my project and can filter the classes through the parameter settings.
when I set 'filter by class == 0', it  didnt work, but other not ? why?
## Additional context
![sendpix0](https://user-images.githubusercontent.com/49978186/88625476-62aad700-d0db-11ea-80b6-8871be8a5c8c.jpg)
![sendpix1](https://user-images.githubusercontent.com/49978186/88625477-63436d80-d0db-11ea-9d78-84d7eaf107e5.jpg)

**Comment by glenn-jocher** [comment]
You’ve made incorrect code modifications. Suggest you run the default repo.

**Comment by lmcltj** [comment]
> You’ve made incorrect code modifications. Suggest you run the default repo.
Thank you for your answer, but I don't think it is the problem you said. Set classes=27 or other class_id , works well ,only classes=0(person) not.

**Comment by glenn-jocher** [comment]
@lmcltj use the default commands:
python detect.py --classes 27
