### ISSUE TITLE
How to disable wandb

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#5310]
@glenn-jocher 
I have a machine with wandb in the login state. Every time I run `train.py`, after the training is completed, some information must be uploaded to wandb, which will waste some time. I want to disable wandb, what should I do?

**Comment by AyushExel** [comment]
@Zengyf-CVer run `wandb disabled` in the command line

**Comment by Zengyf-CVer** [comment]
@AyushExel 
I want to disable wandb in `train.py`, which is more convenient, besides, I am not familiar with wandb commands.

**Comment by AyushExel** [comment]
@Zengyf-CVer you can uninstall wandb using `pip uninstall wandb`

**Comment by Zengyf-CVer** [comment]
@AyushExel 
Thank you very much for your answer, but I still want to implement this function in the `train.py` file.

**Comment by AyushExel** [comment]
@Zengyf-CVer okay, so if I'm understanding this right, you want a switch to turn on/off the wandb integration using the train.py file?
Something like this - `python train.py --disable_wandb`?

**Comment by Zengyf-CVer** [comment]
@AyushExel 
That's right, that's it.

**Comment by AyushExel** [comment]
@Zengyf-CVer this is not something that I can decide but still, I'd advise against adding more cmd-line args if possible as they get out of hand easily. You can already achieve the same by using `wandb disabled` to disable and `wandb online` to enable it.
@glenn-jocher thoughts?

**Comment by glenn-jocher** [comment]
@Zengyf-CVer you could try this to disable wandb before training:
```bash
wandb disabled
python train.py
```

or you could also remove it completely:
```bash
pip uninstall wandb
python train.py
```

**Comment by Zengyf-CVer** [comment]
@glenn-jocher  @AyushExel 
Thank you very much.
