### ISSUE TITLE
About the mixup method

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#5311]
@glenn-jocher 
I feel that this mixup method can only be used for a single object classification task. If it is used for multi-object object detection, can it make sense?
https://github.com/ultralytics/yolov5/blob/fee83c1634ddce6a95f46e8fab85699cfa069c73/utils/augmentations.py#L265-L270

I don't quite understand this code, will this affect mAP?
https://github.com/ultralytics/yolov5/blob/fee83c1634ddce6a95f46e8fab85699cfa069c73/utils/augmentations.py#L269

**Comment by glenn-jocher** [comment]
@Zengyf-CVer mixup reduces overfitting and allows for increases mAP on larger models.
