### ISSUE TITLE
Related experiments on Ghost

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#5314]
@glenn-jocher 
For the yaml of `ghost`, I did related experiments and found that mAP was almost 0 in the first 10 epochs. At the same time, the mAP of the first 50 epochs also grew slowly. Is the reason for this phenomenon because there are too many convolutional layers in `GhostConv` and `C3Ghost`?
https://github.com/ultralytics/yolov5/blob/master/models/hub/yolov5s-ghost.yaml

**Comment by glenn-jocher** [comment]
@Zengyf-CVer with the level of detail in your question no one will be able to answer it. What dataset you trained on, your hyperparameters, your training settings, whether you started from a pretrained model, etc. are a minimum level of information required for anyone to know whether your results are consistent with previous results, i.e.
https://wandb.ai/glenn-jocher/ghost

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
I am using your pre-trained model `yolov5n`, the data set is a custom small object data set, the total number of categories is 3, the others are the default settings used, the following is my yaml file,why does it cause my problem?
```yaml
# YOLOv5 🚀 by Ultralytics, GPL-3.0 license

# Parameters
nc: 3  # number of classes
depth_multiple: 0.33  # model depth multiple
width_multiple: 0.25  # layer channel multiple
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

# YOLOv5 v6.0 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [64, 6, 2, 2]],  # 0-P1/2
   [-1, 1, GhostConv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C3Ghost, [128]],
   [-1, 1, GhostConv, [256, 3, 2]],  # 3-P3/8
   [-1, 6, C3Ghost, [256]],
   [-1, 1, GhostConv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, C3Ghost, [512]],
   [-1, 1, GhostConv, [1024, 3, 2]],  # 7-P5/32
   [-1, 3, C3Ghost, [1024]],
   [-1, 1, SPPF, [1024, 5]],  # 9
  ]

# YOLOv5 v6.0 head
head:
  [[-1, 1, GhostConv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, C3Ghost, [512, False]],  # 13

   [-1, 1, GhostConv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, C3Ghost, [256, False]],  # 17 (P3/8-small)

   [-1, 1, GhostConv, [256, 3, 2]],
   [[-1, 14], 1, Concat, [1]],  # cat head P4
   [-1, 3, C3Ghost, [512, False]],  # 20 (P4/16-medium)

   [-1, 1, GhostConv, [512, 3, 2]],
   [[-1, 10], 1, Concat, [1]],  # cat head P5
   [-1, 3, C3Ghost, [1024, False]],  # 23 (P5/32-large)

   [[17, 20, 23], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
  ]

```

**Comment by glenn-jocher** [comment]
@Zengyf-CVer without a comparison to a baseline there's no rationale for you to believe there is a 'problem'. How do you define a problem? What values are you expecting from your training at this point and why?

**Comment by glenn-jocher** [comment]
@Zengyf-CVer if you want to conduct a proper experiment, then first train the baseline model with default settings, and afterward train your experimental model with the same exact settings. Display the two side by side in a logging utility like W&B or TensorBoard, and then you can examine your experimental results in comparison to your baseline results.
