### ISSUE TITLE
Batch Size Number

### ISSUE THREAD

**Issue by aseprohman** [ultralytics/yolov5#5316]
## ❔Question
Hello @glenn-jocher et all,
does the number of batches always should be a number that can divide the number of tensors on gpu ? I want to training dataset with yolov5m models but can't fit training with batch 32, only fit with 30 batch (imgsize 416 training)

**Comment by glenn-jocher** [comment]
@aseprohman there is no single-GPU or CPU batch-size constraint. 

For multi-GPU, batch-size must be evenly divisible by number of GPUs, i.e. if you have 4 GPUs you can train with --batch 8 but not with --batch 10.

**Comment by aseprohman** [comment]
thanx a lot :)
