### ISSUE TITLE
Question about anchor-target matching

### ISSUE THREAD

**Issue by seekFire** [ultralytics/yolov5#532]
## ❔Question
According to this [issue](https://github.com/ultralytics/yolov5/issues/471), the size of gt_box (suppose **Sg**) and the size of anchor_box (suppose **Sa**) should meet the constraint of the following inequality:
`1/anchor_t < (Sg / Sa) < anchor_t`
But I think the scope of (Sg / Sa) is too large (e.g: 0.25~4), is this possible that one gt_box matches two anchor_boxes ?

BTW, either using the function **wh_iou** or using hyperparameter **anchor_t** to match anchors and gt_boxes, I haven't found out any sign shows that these two method use the position of anchors (either left-top corners or center-points), so my question is:
whether or not anchors only supply the information about width & height ?
Is the offset calculated between the centers of gt_boxes and left-top of grid cells rather than the centers of anchors?

**Comment by glenn-jocher** [comment]
@seekFire yes your equation looks correct. Targets match multiple anchors. If you feel the threshold is too high you are free to modify it here:
https://github.com/ultralytics/yolov5/blob/7f8471eaebe4b192c5e6ab4e5c821d91e43cb4fe/train.py#L35

Keep in mind this work is merely a starting point for your own experiments, it's not an ML bible to follow to the letter.

**Comment by seekFire** [comment]
@glenn-jocher Oh, I see...my question is rised by my misconception that one target should only match one anchor box, so thank you very much!

**Comment by abhiagwl4262** [comment]
@glenn-jocher I have been trying to implement detector loss myself and exploring the ways in which targets can be matched with anchors. It is being very hard for me to understand the intuition behind wh_iou or wh ratio based current implementation. Why didn't you use a jaccard overlap based matching of targets and priors ?

**Comment by glenn-jocher** [comment]
@abhiagwl4262 iou and jaccard are the same thing, and iou matching code is already present here, which you can uncomment for use if you'd like.
https://github.com/ultralytics/yolov5/blob/68e6ab668b30a6014215b94e399151f8c76e471a/utils/loss.py#L176

**Comment by abhiagwl4262** [comment]
@glenn-jocher This wh_iou is different than bounding_box iou. bounding_box iou was pretty intuitive to me but I am not finding wh_iou intuitive at all. Can you help me understand this concept more clearly?

**Comment by glenn-jocher** [comment]
@abhiagwl4262 they are both simple iou functions, wh_iou assumes equal origins.

**Comment by abhiagwl4262** [comment]
@glenn-jocher Ohh I understand the intuition now. But how the assumption of same origins holds true ?
