### ISSUE TITLE
not detecting camera

### ISSUE THREAD

**Issue by Chimchar009** [ultralytics/yolov5#5323]
## python detect.py --weights D:\desktop\coding\yolov5\posters\yolov5\runs\train\poster_AI/best.pt --source 0
Namespace(weights=['D:\\desktop\\coding\\yolov5\\posters\\yolov5\\runs\\train\\poster_AI/best.pt'], source='0', img_size=640, conf_thres=0.25, iou_thres=0.45, device='', view_img=False, save_txt=False, save_conf=False, nosave=False, classes=None, agnostic_nms=False, augment=False, update=False, project='runs/detect', name='exp', exist_ok=False)
YOLOv5  2021-4-12 torch 1.9.0+cu111 CUDA:0 (NVIDIA GeForce RTX 2060, 6144.0MB)

Fusing layers...
D:\desktop\coding\python program\lib\site-packages\torch\nn\functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
Model Summary: 232 layers, 7251912 parameters, 0 gradients, 16.8 GFLOPS
1/1: 0... Traceback (most recent call last):
  File "D:\desktop\coding\yolov5\posters\yolov5\detect.py", line 178, in <module>
    detect()
  File "D:\desktop\coding\yolov5\posters\yolov5\detect.py", line 51, in detect
    dataset = LoadStreams(source, img_size=imgsz, stride=stride)
  File "D:\desktop\coding\yolov5\posters\yolov5\utils\datasets.py", line 279, in __init__
    if 'youtube.com/' in url or 'youtu.be/' in url:  # if source is YouTube video
TypeError: argument of type 'int' is not iterable

it keeps telling me int is not iterable im not sure how to fix this

**Comment by Chimchar009** [comment]
btw this is done on a windows laptop
specs are
Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz   2.59 GHz
ram 24.0 GB
system type Windows 64-bit operating system, x64-based processor
WIndows 10 Home version 20H2
Gpu nvidia 2060 6gbGPU

**Comment by glenn-jocher** [comment]
@Chimchar009 it looks like your YOLOv5 is out of date, last updated April 12th. Update your code.

- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>
