### ISSUE TITLE
Where can I download the pre-training weight files before V6.0?

### ISSUE THREAD

**Issue by Wanghe1997** [ultralytics/yolov5#5325]
Thanks.

**Comment by Zengyf-CVer** [comment]
@Wanghe1997 
- https://github.com/ultralytics/yolov5/releases/tag/v5.0
- https://github.com/ultralytics/yolov5/tags

**Comment by Wanghe1997** [comment]
> @Wanghe1997
> 
> * https://github.com/ultralytics/yolov5/releases/tag/v5.0
> * https://github.com/ultralytics/yolov5/tags

It doesn't work. When I click on the hyperlink for pre-training weights in V5.0, I am automatically redirected to the page in V6.0. I think you guys removed all pre-training weights before 6.0?

**Comment by Zengyf-CVer** [comment]
@Wanghe1997 
Click on the bottom link:
![0000000000](https://user-images.githubusercontent.com/41098760/138681858-d4bf7e68-84cd-4577-86bf-faf73218c91e.PNG)

**Comment by Wanghe1997** [comment]
> @Wanghe1997 Click on the bottom link: ![0000000000](https://user-images.githubusercontent.com/41098760/138681858-d4bf7e68-84cd-4577-86bf-faf73218c91e.PNG)

ok.Thank you
