### ISSUE TITLE
Why postprocess of yolov5 is not same with yolov3

### ISSUE THREAD

**Issue by yangfei963158659** [ultralytics/yolov5#533]
I find yolov5's postprocess is not same with yolov3。
postprocess of yolov5 is follow：
 y = x[i].sigmoid()
 y[..., 0:2] = (y[..., 0:2] * 2. - 0.5 + self.grid[i].to(x[i].device)) * self.stride[i]  # xy
 y[..., 2:4] = (y[..., 2:4] * 2) ** 2 * self.anchor_grid[i]  # wh

when I deploy yolov5 in Hi3559，I find the result is incorrect。

**Comment by yangfei963158659** [comment]
when I deploy yolov5 in Hi3559 using yolov3‘s postprocess，I find the result is incorrect。

**Comment by seekFire** [comment]
@yangfei963158659 I think you may find out the answer from this [issue](https://github.com/ultralytics/yolov5/issues/471)

**Comment by glenn-jocher** [comment]
@yangfei963158659 why would you expect them to be the same?
