### ISSUE TITLE
What is the difference between yolov5s6.pt and yolov5s.pt？And how to use yolov5s6.pt during training

### ISSUE THREAD

**Issue by Wanghe1997** [ultralytics/yolov5#5330]
if i want to use yolov5s6.pt in train.py, --weights is yolov5s6.pt ，And What should the --cfg be filled with?

**Comment by glenn-jocher** [comment]
@Wanghe1997 see https://github.com/ultralytics/yolov5/releases/tag/v5.0 for an explanation of P5 vs P6 models and usage examples of each.
