### ISSUE TITLE
Classification

### ISSUE THREAD

**Issue by vijishmadhavan** [ultralytics/yolov5#5334]
How many epochs would be good for 60 classes model?
Does image size help the model?

Thanks,
Vijish

**Comment by glenn-jocher** [comment]
@vijishmadhavan 

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')
print(model.names) 
# ['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light', 'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch', 'potted plant', 'bed', 'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush']
```

**Comment by samils7** [comment]
@vijishmadhavan it depends on the size and the balance of the dataset. Increasing image size can help performance by considering more details in detection, especially small objects. Having at least a couple hundred samples each class will make good results I believe.

**Comment by iceisfun** [comment]
@vijishmadhavan Best practices are outlined here https://docs.ultralytics.com/guides/model-training-tips/

Lots of people that have trouble with this are not following these, on some of my models I exceed 10k samples per class.

**Comment by ghost** [comment]
@vijishmadhavan the Coco 2017 train set has around 120K images for 80 classes ([details](https://paperswithcode.com/dataset/coco)). Of course, an image can contain multiple objects or several instances of the same object. If you really need that much depends on how separable your objects are: if you want to classify cars and teddy bears you will likely need fewer samples than when your classes are cars, busses, ambulances and trucks. I'd say that with few (< 10) easily separable classes, the minimum is c. 500 images per class and min. 1-2 object instances per image.

Here's a [training image](https://softmatic.com/tmp/001614.jpg) from my current project. I have 6 classes (pawn, bishop, knight, rook, queen, king). With 2.000 images, split 80:20 and 200 ep. I get to >.98 mAP.
