### ISSUE TITLE
Any difference if I use yolov3.yaml to run in yolov5?

### ISSUE THREAD

**Issue by caihaunqai** [ultralytics/yolov5#5336]
## ❔Question
Hello, I wonder if I  use yolov3.yaml to run in yolov5 codes and use all parameters set in default, the results is same? Thank you~

## Additional context

**Comment by glenn-jocher** [comment]
@caihaunqai there are some slight differences that will result in improved results, i.e. Detect output neurons are structured differently, loss function is slightly different. Model architecture itself is the exact same as YOLOv3.

**Comment by SpongeBab** [comment]
@glenn-jocher 
I just want to know this too. I just used yolov3 repo to train my own dataset, and then I used yolov5 repo again. I both used the yolov3.yaml file, and the accuracy of yolov5 repo is higher than that of yolov3 repo.

**Comment by glenn-jocher** [comment]
@SpongeBab right. This is due to the reasons I've already listed above.
