### ISSUE TITLE
Focal loss is no better than Baseline?

### ISSUE THREAD

**Issue by voscar-zhang** [ultralytics/yolov5#5337]
I tried to train baseline version and focal-loss version on my 2 classes VOC dataset（car and people)，the result was out of my expectation， focal loss worked on Yolov3 with this same dataset，but not on Yolov5. 
![image](https://user-images.githubusercontent.com/39939359/138805688-3235f515-cec1-41ec-82ea-4e39bf6278bd.png)

**Comment by zxsitu** [comment]
I tested focal loss on my own dataset and also felt that the effect was not great.

**Comment by voscar-zhang** [comment]
> I tested focal loss on my own dataset and also felt that the effect was not great.

I printed the obj loss and noobj loss of my dataset on yolov5，found that the sample imbalance was not as bad as that on yolov3. Maybe that’s why focal loss didn’t work on yolov5.

**Comment by thuangb** [comment]
Focal Loss is not magic, it only shines when there is a significant imbalance in the dataset

**Comment by glenn-jocher** [comment]
Also I think it works better for models with combined objectness-classification heads, like SSD. YOLO already partly addresses imbalance by splitting these into two.
