### ISSUE TITLE
varifocal loss

### ISSUE THREAD

**Issue by zwhua006** [ultralytics/yolov5#5339]
## Additional context
Recently I read the paper <VarifocalNet: An IoU-aware Dense Object Detector>  and I want to know if you have tried varifocal loss instead of BCE loss, I guess it will works.

**Comment by glenn-jocher** [comment]
@zwhua006 hi, thank you for your feature suggestion on how to improve YOLOv5 🚀! No, I have not tried varifocal loss with YOLOv5. It sounds like an interesting idea though!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
