### ISSUE TITLE
CPU inference using torchscript  

### ISSUE THREAD

**Issue by gauravlochab** [ultralytics/yolov5#5340]
## ❔Question
how do i use the exported torchscript model ?
## Additional context
i have loaded the model using torch jit **torch_script_model=torch.jit.load(path_to_weight)**
but i am unable to make predictions when i pass image tensor **torch_script_model(tensor)[0]**
i am getting this error RuntimeError: Dimension out of range (expected to be in range of [-3, 2], but got 3)
Ps i am exporting the yolox model with batch size 4 and image size 1280 and have tried reshaping the inference image to same size before inference but no luck

**Comment by rlrahulkanojia** [comment]
import cv2
import numpy as np
img = cv2.imread('/content/img.jpeg')
img = cv2.resize(img, (1280,1280))
img = np.transpose(img, (2,0,1))
img = np.expand_dims(img, 0).astype(np.float32)
img = torch.from_numpy(img)

**Comment by gauravlochab** [comment]
![wow](https://user-images.githubusercontent.com/20882775/138829860-f9341bd4-53c7-4644-8d82-6ae50fa25141.JPG)
 whole point for using torchscript was to dec the CPU inference time but it has increased 

my CPU specs 
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  2
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
Stepping:            7
CPU MHz:             3196.723
BogoMIPS:            4999.99

img size is same in both inferences 1280
@glenn-jocher @andreiionutdamian any suggestions ?

**Comment by andreiionutdamian** [comment]
> 
> 
> ![wow](https://user-images.githubusercontent.com/20882775/138829860-f9341bd4-53c7-4644-8d82-6ae50fa25141.JPG) whole point for using torchscript was to dec the CPU inference time but it has increased
> 
> my CPU specs Architecture: x86_64 CPU op-mode(s): 32-bit, 64-bit Byte Order: Little Endian CPU(s): 8 On-line CPU(s) list: 0-7 Thread(s) per core: 2 Core(s) per socket: 4 Socket(s): 1 NUMA node(s): 1 Vendor ID: GenuineIntel CPU family: 6 Model: 85 Model name: Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz Stepping: 7 CPU MHz: 3196.723 BogoMIPS: 4999.99
> 
> img size is same in both inferences 1280 @glenn-jocher @andreiionutdamian any suggestions ?

Hi,
My first sugestion is that you repeat your experiment on a GPU by moving the model & data on cuda then tracing the script. Also try to have identical calls (eg use identical input tensor for initial simple forward pass then replicate for the jit graph). In my experience there should be a performance gain between the two methods between 0 (for small models) up to 10-20% range based on the GPU you are using (an obviously the model architecture). In the particular case of a yolov5l6 the gain is about 15% when running on GPU with jit graph.
On the other hand you cannot compare "eager-vs-graph" tensorflow modes with pytorch as there is no such big (huge) difference in second case as opposed to the first.
Finally consider that the CPU has a limited amount of processing cores that can do so much. I am not sure that the pruning and freezing  `th.jit` is doing has the objective of helping you run inference in very low "numerical threads" environments such as CPU even if you have a 12 core one.

**Comment by gauravlochab** [comment]
i used https://github.com/yasenh/libtorch-yolov5 and deci.ai platform instead
