### ISSUE TITLE
Need Suggestions on adding self-attention mechnism in YOLOv5

### ISSUE THREAD

**Issue by jaiswati** [ultralytics/yolov5#5342]
Hello @glenn-jocher 

Could you please share any documentation or direction to add a self-attention/Vision transformed mechanism to YOLOv5?

Thank You,
@jaiswati

**Comment by glenn-jocher** [comment]
@jaiswati see https://github.com/ultralytics/yolov5/issues/2329 for transformer version experiments on YOLOv5 backbone.
