### ISSUE TITLE
Can't Download Model Even With force_reload=True

### ISSUE THREAD

**Issue by OrjwanZaafarani** [ultralytics/yolov5#5347]
## 🐛 Bug

I can't download any model even if its locally available in my machine.

## To Reproduce (REQUIRED)

Input:

```
import torch

torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)
```

Output:

```
Cache may be out of date, try `force_reload=True`. See https://github.com/ultralytics/yolov5/issues/36 for help.
```

- OS: Ubuntu 18.4
- GPU: GeForce RTX 2080 Ti

As instructed, I updated jupyter and ipywidgets but the error is still there.

**Comment by tamis-laan** [comment]
How did you fix this?

**Comment by OrjwanZaafarani** [comment]
I downloaded the requirements.
