### ISSUE TITLE
pre-weight

### ISSUE THREAD

**Issue by yang-leon996** [ultralytics/yolov5#5348]
## ❔Question
if I want to only load part of these pre-weight, what should I do ?such as I don't want to load  the pre-weight of SPP. Thank you！

**Comment by glenn-jocher** [comment]
@yang-leon996 you can add any layers you want excluded to the exclude list:
https://github.com/ultralytics/yolov5/blob/a4fece8c1480aed46a38a6344b403d79c81bd751/train.py#L119-L122

**Comment by yang-leon996** [comment]
> @yang-leon996 you can add any layers you want excluded to the exclude list:
> 
> https://github.com/ultralytics/yolov5/blob/a4fece8c1480aed46a38a6344b403d79c81bd751/train.py#L119-L122

**Comment by yang-leon996** [comment]
> > @yang-leon996 you can add any layers you want excluded to the exclude list:
> > https://github.com/ultralytics/yolov5/blob/a4fece8c1480aed46a38a6344b403d79c81bd751/train.py#L119-L122

**Comment by yang-leon996** [comment]
@glenn-jocher  exclude = ['anchor',"SPP"] if (cfg or hyp.get('anchors')) and not resume else []  is like this?

**Comment by glenn-jocher** [comment]
@yang-leon996 just print the module names and add whichever ones you'd like to to the exclude list.

**Comment by yang-leon996** [comment]
Thank you very much for replying to me in your busy schedule, I will try it out！
