### ISSUE TITLE
Object Detection MLModel for iOS with output configuration of confidence scores & coordinates for the bounding box.

### ISSUE THREAD

**Issue by ajurav1** [ultralytics/yolov5#535]
I have exported the **mlmodel** from **export.py**, and the model exported have a type of Neural Network and output configuration is 
[<VNCoreMLFeatureValueObservation: 0x281d80240> 4702BA0E-857D-4CE6-88C1-4E47186E751F requestRevision=1 confidence=1.000000 "2308" - "MultiArray : Float32 1 x 3 x 20 x 20 x 85 array" (1.000000), <VNCoreMLFeatureValueObservation: 0x281d802d0> AE0A0580-7DA2-4991-98BB-CD26EE257C7A requestRevision=1 confidence=1.000000 "2327" - "MultiArray : Float32 1 x 3 x 40 x 40 x 85 array" (1.000000), <VNCoreMLFeatureValueObservation: 0x281d80330> 0253FD2B-10B0-4047-A001-624D1864D27C requestRevision=1 confidence=1.000000 "2346" - "MultiArray : Float32 1 x 3 x 80 x 80 x 85 array" (1.000000)]

 I was looking for output type **VNRecognizedObjectObservation** in yoloV5 instead of **VNCoreMLFeatureValueObservation**.

So, my question is what information does this **VNCoreMLFeatureValueObservation** MultiArray hold (is it something like a UIImage or CGRect?, or something different?) and how can I convert this Multidimensional Array into a useful set of data that I can actually see confidence scores & coordinates?

**Comment by dlawrences** [comment]
Hi @ajurav1 

Those tensors store network predictions that are not decoded. There are a few recommendations I made in #343 to decode these and there is even a NumPy sample code that does this for the ONNX model.

There's also guidance here: https://docs.ultralytics.com/yolov5/tutorials/model_export

Take a look in there and let me know if you require further support.

**Comment by ShreshthSaxena** [comment]
Hi @dlawrences , 
I'm in the same boat trying to figure out how to convert these raw predictions to bbox coordinates. Is there a swift implementation available to interpret these outputs or someway I can add the post-processing to a CoreML pipeline and get the final outputs in Swift?

**Comment by dlawrences** [comment]
@ShreshthSaxena , there is a lot of useful information which you will be able to use on this blog: https://machinethink.net/blog/

I recommend acquiring the book as well.

**Comment by ShreshthSaxena** [comment]
thanks @dlawrences but I'm looking for help with yolov5 inference/post-processing steps specifically. Is there any description on these steps or an implementation that I can try to replicate in swift?
I can get the 3 multi arrays in swift but not sure how to turn those into bboxes and if I enable the detect layer, CoreML conversion fails

**Comment by maidmehic** [comment]
Hi @ajurav1 and @ShreshthSaxena, have you managed to convert `VNCoreMLFeatureValueObservation` MultiArrays to some useful info on Swift side?

**Comment by kir486680** [comment]
@dlawrences In the article, the author says that the "Ultralytics YOLOv5 model has a Core ML version but it requires changes before you can use it with Vision." Did you manage to make it work with Vision?

**Comment by dlawrences** [comment]
@kir486680 the CoreML model, as exported from this repository, presents the final feature maps, thus the predictions are not decoded, nor any NMS is applied.

I have been able to create the required steps locally, yes, and it works directly with Vision.

**Comment by kir486680** [comment]
@dlawrences could you please share at least some clues pls? I implemented NMS but I do not know what to do with the output from the model. I seen some implementations [here  ](https://github.com/hollance/YOLO-CoreML-MPSNNGraph/blob/master/TinyYOLO-CoreML/TinyYOLO-CoreML/YOLO.swift). Do you have something similar?

**Comment by wmcnally** [comment]
@kir486680 @dlawrences any update on this?

**Comment by yusufoos** [comment]
@glenn-jocher Thanks for your your instructions on [exporting a different size](https://github.com/ultralytics/yolov5/issues/1044#issuecomment-1013960973)

However, I'm running into the same problem as described here - The exported Model does not have the expected Ouptut interface to be used for inference (Bounding Box + Confidence). The CoreML Models you provide in your releases _are_ in the correct format. How do we transform the output from export.py to resemble like the .mlmodel you share in releases?

See pictures to see the difference

![ReleaseModel](https://user-images.githubusercontent.com/1316153/149682035-9e54217e-7cc7-4c1a-8bde-da509a212994.jpg)

![ExportModel](https://user-images.githubusercontent.com/1316153/149682036-73f1b5b8-eb05-47e3-881a-35ed07987c30.jpg)

Many thanks 🥇

**Comment by Workshed** [comment]
If you come across this issue, there's a script here for creating a CoreML model which outputs the expected values https://github.com/Workshed/yolov5-coreml-export

**Comment by glenn-jocher** [comment]
@Workshed thanks for sharing your script for creating a CoreML model that outputs the expected values with YOLOv5. This will be helpful for others who are looking to work with YOLOv5 in CoreML. Keep up the great work!
