### ISSUE TITLE
Number of layers and parameters in training and inference

### ISSUE THREAD

**Issue by besmaguesmi** [ultralytics/yolov5#5352]
Hi there!
I trained the model with different Yolov5 models. To compare between them, I have used the parameters, GFLOPS, layers numbers, etc. My question about the parameters and layers numbers, when I trained the model and run the inference I didn't get the same values of the model and I'm still which when I have used to evaluate the model ( the parameters and layers numbers of inference or of training)

Thanks.

**Comment by glenn-jocher** [comment]
@besmaGuesmi this is probably because the models are fused using model.fuse() before inference is run. This fuses the batchorm and Conv2d layers togethor.

**Comment by besmaguesmi** [comment]
Yes, I think that! So using the training parameters or inference parameters for models comparison is the same right?

**Comment by glenn-jocher** [comment]
@besmaGuesmi yes the model is the same, it is just fused before inference, resulting is slightly less layers and parameters.
