### ISSUE TITLE
How can I show ONNX results on a photo?

### ISSUE THREAD

**Issue by prp-e** [ultralytics/yolov5#5354]
## I finally could get ONNX to work, and now I ask How can I show the results on the input image? 

I used this whole code: 

```python
inp = cv2.imread('pedestrians.jpg')
net = cv2.dnn.readNetFromONNX('pedestrians_new.onnx')
inp = cv2.resize(inp, (640, 640))
inp_y = inp.transpose().reshape(1, 3, 640, 640)
net.setInput(inp_y)
out = net.forward()
print(out.shape) # outputs (1, 25200, 21)
print(out) # outputs an ndarray 
``` 

Now, I have a question, how can I show the results on my input image? Or how can I found the bounding boxes, etc.

**Comment by glenn-jocher** [comment]
@prp-e detect.py can accept ONNX models directly, and automatically annotates predictions on images.

```bash
python export.py --weights yolov5s.pt
python detect.py --weights yolov5s.onnx
```
