### ISSUE TITLE
cv2 from source  and gstreamer

### ISSUE THREAD

**Issue by sekisek** [ultralytics/yolov5#5356]
if I compiled a OpenCV from source with GStreamer support and it's working!

but when I try to run yolov5 on that environment it does not recognize that OpenCV.

is there a way to use GStreamer (OpenCV from source) with yolov5?

thanks

**Comment by glenn-jocher** [comment]
@sekisek best practices is to create a venv and install/compile any packages you need there, and then run YOLOv5 within that environment.
