### ISSUE TITLE
Yolov5s output customization

### ISSUE THREAD

**Issue by rlrahulkanojia** [ultralytics/yolov5#5359]
## ❔Question
When we export yolov5s to onnx, we get the following outputs:
[1, 25200, 85]
[1, 3, 80, 80, 85]
[1, 3, 40, 40, 85]
[1, 3, 20, 20, 85]

how can I make sure i get only following output:
[1, 25200, 85] 
and split it into 
[ 1, 25200, 5 (box coordinates + confidence)] 
[ 1, 25200, 80 ] class probabilities] , 

## Additional context

exporting to onnx

**Comment by rlrahulkanojia** [comment]
@glenn-jocher

**Comment by rlrahulkanojia** [comment]
I am able to get the output of [1,25200, 85 ] by changing following piece of code 

`return x if self.training else (torch.cat(z, 1), x)` in models/yolo.py  to 

`return torch.cat(z, 1)` 

How can i split it into the required format and is this the correct way of doing this?

**Comment by glenn-jocher** [comment]
@rlrahulkanojia ONNX exports can be used directly with detect.py, where you can see examples of output handling.
```bash
python export.py --weights yolov5s.pt --include onnx
python detect.py --weights yolov5s.onnx
```

**Comment by rlrahulkanojia** [comment]
I am actually trying to deploy it on jetson nano using jetson_inference by dusty NV (https://github.com/dusty-nv/jetson-inference)  .   I have tried it using tensortx (https://github.com/wang-xinyu/tensorrtx)  but it does not support videos and RTSP stream.

For that purpose I am trying to organize outputs as its required in detectnet and write extra code in c++.

**Comment by glenn-jocher** [comment]
@rlrahulkanojia see Jetson Nano export competition submissions: https://github.com/ultralytics/yolov5/discussions/3426

**Comment by rlrahulkanojia** [comment]
They are good solutions but some use torch libraries and some require ram around 3 GB ram which is not efficient for me due to memory and space constraints.

PS. I have already tried all of them.

It will be really helpful if you can provide any insights in getting started to support dusty NV project.

**Comment by greg2451** [comment]
Hello @rlrahulkanojia, have you found a solution to natively fit the jetson-inference project ? By that I mean properly instanciating the DetectNet object.

Like you, I would like to deploy a yolov5 custom model using dusty-nv's work.

For what it's worth, I believe you can still use the tensorrtx repo and the engine it creates. I read somewhere that you could update the code to read from an rtsp stream or even a video, but never really managed to do so.

Cheers !

**Comment by rlrahulkanojia** [comment]
I referred to a project called FASTMOT which originally uses yolov4. Hope that helps you.

**Comment by greg2451** [comment]
> I referred to a project called FASTMOT which originally uses yolov4. Hope that helps you.

Thanks for your answer! I've looked at the project, have you used this [part](https://github.com/GeekAlexis/FastMOT/blob/a185b78b771546151d42e02397f6940e4ee47bd8/fastmot/models/yolo.py#L11) where the author updates a yolo TRT engine (so hypothetically a yolov5 one) to embed the preprocessing steps so that it fits the jetson-inference required format ? (Or something like that)

**Comment by rlrahulkanojia** [comment]
Yes. To be exact. I changed the ultralytics yolov5 inference output and matched it with expected SSD output and also changed the preprocessing code in detectnet repo.

**Comment by greg2451** [comment]
Alright thanks, helps a lot, I'll try by myself and see what I can get!
Cheers
