### ISSUE TITLE
yolov5(v2).pt to yolov5.onnx  is wrong

### ISSUE THREAD

**Issue by EVAN-wt** [ultralytics/yolov5#5361]
Before submitting a bug report, please be aware that your issue **must be reproducible** with all of the following,
otherwise it is non-actionable, and we can not help you:

- **Current repo**: run `git fetch && git status -uno` to check and `git pull` to update repo
- **Common dataset**: coco.yaml or coco128.yaml
- **Common environment**: Colab, Google Cloud, or Docker image. See https://github.com/ultralytics/yolov5#environments

If this is a custom dataset/training question you **must include** your `train*.jpg`, `val*.jpg` and `results.png`
figures, or we can not help you. You can generate these with `utils.plot_results()`.

## 🐛 Bug

![image](https://user-images.githubusercontent.com/64881467/139030836-946e1521-9d60-40e8-9646-79fcb42ff2a0.png)

1.The trained yolov5(2.0).pt was transferred to ONNX
download yolov5-2.0
Prepare the model_7.pt（yolov5.pt）

2. To transfer
python3.7 models/export.py

/yolov5-2.0/yolov5-2.0# python3.7 models/export.py
Namespace(batch_size=1, img_size=[640, 640], weights='./model_7.pt')
Traceback (most recent call last):
  File "models/export.py", line 26, in <module>
    model = torch.load(opt.weights, map_location=torch.device('cpu'))['model'].float()
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/torch/serialization.py", line 581, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './model_7.pt'
root@W84172537:/mnt/d/tmp/error-model/yolov5-2.0/yolov5-2.0# python3.7 models/export.py
Namespace(batch_size=1, img_size=[640, 640], weights='./model_7.pt')
Traceback (most recent call last):
  File "models/export.py", line 26, in <module>
    model = torch.load(opt.weights, map_location=torch.device('cpu'))['model'].float()
AttributeError: 'collections.OrderedDict' object has no attribute 'float'
root@W84172537:/mnt/d/tmp/error-model/yolov5-2.0/yolov5-2.0# python3.7 models/export.py
Namespace(batch_size=1, img_size=[640, 640], weights='./composite_detection.pt')
Traceback (most recent call last):
  File "models/export.py", line 26, in <module>
    model = torch.load(opt.weights, map_location=torch.device('cpu'))['model'].float()
AttributeError: 'collections.OrderedDict' object has no attribute 'float'

**Comment by EVAN-wt** [comment]
torch                  1.7.1+cpu
torchaudio             0.7.2
torchvision            0.8.2+cpu

**Comment by EVAN-wt** [comment]
my python3.7.5  > python3.6

**Comment by EVAN-wt** [comment]
That yolov5(v5)s.pt to yolov5.onnx is success！But the yolov5(v5)s.pt to yolov5.onnx is wrong!

**Comment by glenn-jocher** [comment]
@EVAN-wt got it. We haven't tested export of <v5.0 models, so it's possible these may not export correctly. I would highly recommend training with the latest release, which we have verified exports correctly.
