### ISSUE TITLE
Maximum rows for label file

### ISSUE THREAD

**Issue by poolkoleg** [ultralytics/yolov5#5363]
Hello.

I'm trying to train YOLOv5 to find table rows in img.

When I have Label file with 14 rows:

1. 0 0.517000 0.193223 0.900000 0.032000
2. 0 0.517000 0.218637 0.900000 0.032000
3. 0 0.517000 0.244050 0.900000 0.032000
4. 0 0.517000 0.269463 0.900000 0.032000
5. 0 0.517000 0.294877 0.900000 0.032000
6. 0 0.517000 0.320290 0.900000 0.032000
7. 0 0.517000 0.345704 0.900000 0.032000
8. 0 0.517000 0.371117 0.900000 0.032000
9. 0 0.517000 0.396531 0.900000 0.032000
10. 0 0.517000 0.421944 0.900000 0.032000
11. 0 0.517000 0.447358 0.900000 0.032000
12. 0 0.517000 0.472771 0.900000 0.032000
13. 0 0.517000 0.498185 0.900000 0.032000
14. 0 0.517000 0.752319 0.900000 0.032000

Everything is ok.

But when I try to add more... For example,  15...

1. 0 0.517000 0.193223 0.900000 0.032000
2. 0 0.517000 0.218637 0.900000 0.032000
3. 0 0.517000 0.244050 0.900000 0.032000
4. 0 0.517000 0.269463 0.900000 0.032000
5. 0 0.517000 0.294877 0.900000 0.032000
6. 0 0.517000 0.320290 0.900000 0.032000
7. 0 0.517000 0.345704 0.900000 0.032000
8. 0 0.517000 0.371117 0.900000 0.032000
9. 0 0.517000 0.396531 0.900000 0.032000
10. 0 0.517000 0.421944 0.900000 0.032000
11. 0 0.517000 0.447358 0.900000 0.032000
12. 0 0.517000 0.472771 0.900000 0.032000
13. 0 0.517000 0.498185 0.900000 0.032000
14. 0 0.517000 0.752319 0.900000 0.032000
15. 0 0.517000 0.523598 0.900000 0.032000

There is error:

autoanchor: Analyzing anchors... anchors/target = 2.54, Best Possible Recall (BPR) = 0.7619. Attempting to improve anchors, please wait...
autoanchor: Running kmeans for 12 anchors on 63 points...
autoanchor: ERROR: autoanchor: ERROR: scipy.cluster.vq.kmeans requested 12 points but returned only 11
Traceback (most recent call last):
  File "train.py", line 622, in <module>
    main(opt)
  File "train.py", line 519, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 235, in train
    check_anchors(dataset, model=model, thr=hyp['anchor_t'], imgsz=imgsz)
  File "/home/jupyter/work/resources/yolov5/utils/autoanchor.py", line 53, in check_anchors
    new_bpr = metric(anchors)[0]
  File "/home/jupyter/work/resources/yolov5/utils/autoanchor.py", line 36, in metric
    r = wh[:, None] / k[None]
**RuntimeError: The size of tensor a (63) must match the size of tensor b (4) at non-singleton dimension 1**

How can I add more rows in label file ?

**Comment by glenn-jocher** [comment]
@poolkoleg see Custom Training tutorial for directions on creating YOLOv5 label files:
https://docs.ultralytics.com/yolov5/tutorials/train_custom_data

### 1.2 Create Labels

After using a tool like [Roboflow Annotate](https://roboflow.com/annotate?ref=ultralytics) to label your images, export your labels to **YOLO format**, with one `*.txt` file per image (if no objects in image, no `*.txt` file is required). The `*.txt` file specifications are:

- One row per object
- Each row is `class x_center y_center width height` format.
- Box coordinates must be in **normalized xywh** format (from 0 - 1). If your boxes are in pixels, divide `x_center` and `width` by image width, and `y_center` and `height` by image height.
- Class numbers are zero-indexed (start from 0).

<img width="800" alt="Image Labels" src="https://user-images.githubusercontent.com/26833433/91506361-c7965000-e886-11ea-8291-c72b98c25eec.jpg">

The label file corresponding to the above image contains 2 persons (class `0`) and a tie (class `27`):

<p align="center"><img width="428" src="https://user-images.githubusercontent.com/26833433/112467037-d2568c00-8d66-11eb-8796-55402ac0d62f.png"></p>

**Comment by poolkoleg** [comment]
@glenn-jocher 
I'm already saw this.

All points is ok.

I have image with 29 **same** objects.
If I take 14 of this objects - it's ok, but if more - I have error.

**Comment by glenn-jocher** [comment]
@poolkoleg label files can have unlimited numbers of instances, one per row. If you are having problems then your label format is incorrect.

**Comment by poolkoleg** [comment]
Ok, what is wrong with this format ?

<img width="378" alt="image" src="https://user-images.githubusercontent.com/64004552/139088118-20c5dc15-1e89-41ac-99e0-272b4c6eb287.png">
