### ISSUE TITLE
Can we group and download cropped images based on input images in Yolov5?

### ISSUE THREAD

**Issue by alucor-it** [ultralytics/yolov5#5364]
Hi,

I understand that the objects detected by Yolov5 can be cropped and saved. But I would like to understand whether we can save the cropped images based on the input images. For example, if test1.jpg is my test image containing bus and car, then the detected objects should be saved in "test1" folder.

Thank you

**Comment by glenn-jocher** [comment]
@alucor-it yes, you can filter classes using the `model.classes` list, and you can drop with `results.crop()`. See **PyTorch Hub** tutorial for details

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by alucor-it** [comment]
Thank you for the reply. I don't want to filter the cropped images based on the classes, instead I want to filter it based on the input image i.e "test1" folder in the above example should contain the cropped images of bus and car detected from "test1.jpg", "test2" folder in the above example should contain the cropped images of bus and car detected from "test2.jpg" and so on.

**Comment by glenn-jocher** [comment]
@alucor-it crops are grouped by class, not by source image.

**Comment by alucor-it** [comment]
Okay. Thank you
