### ISSUE TITLE
'detect.py --save-crop' Only 2 cropped targets can be saved per image

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#5366]
### line 226
                       if save_crop:
                            save_one_box(xyxy, imc, file=save_dir / 'crops' / names[c] / f'{p.stem}.jpg', BGR=True)

### line 804
        cv2.imwrite(str(increment_path(file, mkdir=True).with_suffix('.jpg')), crop)
The second will be overwritten when it is saved to a third and subsequent target.
My original file name ended with some numbers.
    -xxx11.jpg
    -xxx12.jpg
    -xxx13.jpg
    -xxx14.jpg
    -xxx21.jpg
    -xxx22.jpg
    -xxx23.jpg
    -xxx24.jpg
......

I recommend using underscores before the generated numbers in increment_path().

**Comment by glenn-jocher** [comment]
@atlastanka hi, thank you for your feature suggestion on how to improve YOLOv5 🚀! You can update to `increment_path(sep='_')`. If that solves your issue please submit a PR to help future users. 

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
