### ISSUE TITLE
Max Detection

### ISSUE THREAD

**Issue by aseprohman** [ultralytics/yolov5#5368]
## ❔Question
Hello @glenn-jocher et all,

what is the maximum value of the number of objects that can be detected by this yolov5 model per class (more than 300)? is there a comparison of the gpu capacity with the maximum detection? and what about the detection capacity in mobile devices ?

**Comment by glenn-jocher** [comment]
@aseprohman detect.py and torch hub model inference default `max_det=1000`, modify as you see fit.
https://github.com/ultralytics/yolov5/blob/a4fece8c1480aed46a38a6344b403d79c81bd751/models/common.py#L276-L283

Deployment destinations settings are up to you.

**Comment by aseprohman** [comment]
thanks, more bigger number of detection it means more hardware compute capacity needs, is it correct ?

**Comment by glenn-jocher** [comment]
@aseprohman as I said vary this setting yourself to whatever value you want.

max_det is an integer

**Comment by aseprohman** [comment]
thank you very much, maybe i need hands-on experience :)
