### ISSUE TITLE
in

### ISSUE THREAD

**Issue by 123456789mojtaba** [ultralytics/yolov5#537]
Hi.
I was training for 400 epochs. after 150 epochs pc turned off unfortunately.
Now if I continue with the best.pt model saved in weights folder does it train resume or train of first?

**Comment by Lornatang** [comment]
@123456789mojtaba It depends on your training command.

**Comment by Laughing-q** [comment]
@123456789mojtaba maybe your --resume will see a drop of some evaluation, --resume is not 100% mature yet
