### ISSUE TITLE
figure diagram

### ISSUE THREAD

**Issue by Dejavusd** [ultralytics/yolov5#5370]
how can I use C1 and C2 in yolov5.utils.plots.py to cut the figure diagram
c1, c2 = (int(box[0]), int(box[1])), (int(box[2]), int(box[3]))

https://github.com/ultralytics/yolov5/blob/aa1859909c96d5e1fc839b2746b45038ee8465c9/utils/plots.py#L87

**Comment by glenn-jocher** [comment]
@Dejavusd I don't understand your question, but c1 and c2 are just the top-left and bottom-right corners of a box.
