### ISSUE TITLE
Why losses have a gain?

### ISSUE THREAD

**Issue by Grabber** [ultralytics/yolov5#5371]
## ❔Question

Why losses have a gain per loss component: lbox (regression), lobj (objectness) and lcls (classes)?

### loss.py
```
lbox *= self.hyp['box']
lobj *= self.hyp['obj']
lcls *= self.hyp['cls']
```

### hyp.scratch.yaml
```
box: 0.05  # box loss gain
cls: 0.5  # cls loss gain
obj: 1.0  # obj loss gain (scale with pixels)
```
Why these values? Why the sum(box, cls, obj) isn't equal to 1?

I found another repo containing an implementation with very different values:

```
lbox *= 3.2
lobj *= 64
lcls *= 32
```

If these values are completely random on the begining, does the genetic algorithm converges to near 0.05, 0.5 and 1.0? Why?

**Comment by glenn-jocher** [comment]
@Grabber genetic algorithm is like any other optimizer, it will find a local minimum subject to constraints.

Loss gains are naturally used to scale and balance losses.

**Comment by foemre** [comment]
@glenn-jocher  

> Loss gains are naturally used to scale and balance losses.

Does this mean, if e.g. my box loss is high, should I increase my box loss gain even higher so that the optimizer will try to reduce box loss even further?

**Comment by glenn-jocher** [comment]
@foemre While increase loss gain will prioritize the associated loss component, you should also ensure that the overall sum of loss gains is balanced to achieve best performance. Adjust gains incrementally while monitoring model behavior.
