### ISSUE TITLE
Regarding the batch size used for different model training

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#5376]
@glenn-jocher 
I saw in README that you set batch-size like this. As far as I know, batch-size is generally 2 to the n-th power, but what is the setting of `40` and `24` here? Or is it arbitrarily set according to the different GPU memory usage?

![ksnip_20211028-185405](https://user-images.githubusercontent.com/41098760/139242296-26546d72-2978-41ca-a540-5deb4626f781.png)

**Comment by glenn-jocher** [comment]
@Zengyf-CVer arbitrary for single-GPU, or use `--batch -1` for autobatch.

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
Is this autobatch designed based on the maximum memory of a single GPU?

**Comment by glenn-jocher** [comment]
@Zengyf-CVer it's an experimental feature only available for single-GPU training at the moment. See https://github.com/ultralytics/yolov5/pull/5092

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
Thank you very much.
