### ISSUE TITLE
How to use the onnx (converted from .pt) in opencv C++

### ISSUE THREAD

**Issue by NacerFaraj** [ultralytics/yolov5#5378]
I am using OpenCV 4.5.4, which supports the use of converted yolov5 from pythorch (*.pt) to onnx.

I got a pre-trained yolov5 model. After converting it to onnx, I can load the model successfully using: `cv::dnn::readNetFromONNX("best.onnx")`. BUT, I do not know how to use it to find the bounding boxes around the objects given a test image!

There are plenty of samples showing how to do so with the darknet. But, I couldn't find any sample for using yolov5.onnx in opencv & C++.

any help?

**Comment by glenn-jocher** [comment]
@NacerFaraj we don't have C/C++ examples of cv2 DNN ONNX inference, but you can use detect.py as a reference example of python cv2 DNN ONNX inference:

```bash
python export.py --weights yolov5s.pt --include onnx

python detect.py --weights yolov5s.onnx --dnn  # DNN inference
python detect.py --weights yolov5s.onnx  # ONNX Runtime inference
```

**Comment by NacerFaraj** [comment]
> @NacerFaraj we don't have C/C++ examples of cv2 DNN ONNX inference, but you can use detect.py as a reference example of python cv2 DNN ONNX inference:
> 
> ```shell
> python export.py --weights yolov5s.pt --include onnx
> 
> python detect.py --weights yolov5s.onnx --dnn  # DNN inference
> python detect.py --weights yolov5s.onnx  # ONNX Runtime inference
> ```

Then, would you plz explain the the structure of the `output`?  And possibly, how to extract the confidences and boxes from it.

```
net = cv::dnn::readNetFromONNX("yolov5.onnx");
cv::Mat blob;
cv::dnn::blobFromImage(img, blob, 1.0/255, cv::Size(blobSize, blobSize), cv::Scalar(0, 0, 0), true, false);
net.setInput(blob);
cv::Mat output = net.forward();
```

**Comment by glenn-jocher** [comment]
@NacerFaraj for COCO with 80 classes outputs will be shape(n,85) with 85 dimension = (x,y,w,h,object_conf, class0_conf, class1_conf, ...)

**Comment by NacerFaraj** [comment]
@glenn-jocher  thank you very much. solved.

**Comment by NacerFaraj** [comment]
Dear Glenn,
The following, is a part of my code that uses "yolov5s.onnx" to detect the objects:

```
    float confThreshold  = 0.25f;
    float nmsThreshold = 0.45f;

    cv::Mat blob;
    cv::dnn::blobFromImage(frame, blob, 1.0/255.0, cv::Size(blobSize, blobSize), cv::Scalar(0, 0, 0), true, false);
    objNet.setInput(blob);

    cv::Mat OUT = objNet.forward();
    cv::Mat detectionMat(OUT.size[1], OUT.size[2], CV_32F, OUT.ptr<float>());
    std::vector<int> classIds;
    std::vector<float> confidences;
    std::vector<cv::Rect> boxes;

    float* data = (float*)detectionMat.data;
    for (int i = 0; i < detectionMat.rows; i++, data += detectionMat.cols)
    {
        cv::Mat class_scores = detectionMat.row(i).colRange(5, detectionMat.cols);
        cv::Point classIdPoint;
        double max_confidence;
        minMaxLoc(class_scores, 0, &max_confidence, 0, &classIdPoint);

        float conf = max_confidence * data[4];
        if (conf > confThreshold)
        {
            int centerX = (int)(data[0] * frame.cols / blobSize);
            int centerY = (int)(data[1] * frame.rows / blobSize);
            int width = (int)(data[2] * frame.cols / blobSize);
            int height = (int)(data[3] * frame.rows / blobSize);
            int left = centerX - width / 2;
            int top = centerY - height / 2;

            classIds.push_back(classIdPoint.x);
            confidences.push_back(conf);
            boxes.push_back(cv::Rect(left, top, width, height));
        }
    }
```

It works like a charm! However, the confidences and the accuracies are different from those of "detect.py" which also uses ""yolov5s.onnx" with cv2.dnn. The values of `confThreshold  `and `nmsThreshold `, as can be seen, are set to the values that are used in "detect.py".

this link shows the output of "detect.py" for "zidane.jpg": [https://drive.google.com/file/d/1m8ms6iVTfGt4dNNvzMQ7MEyM5v41njfq/view?usp=sharing](url)
and this is the output of mine: [https://drive.google.com/file/d/16ARvUz2YtCUYxD3HvAv9lP0s5TP-lAhZ/view?usp=sharing](url)

I definitely am doing something wrong!  I'd apricate if you (or any someone) could let me know how to correct the output.
many thanks in advance.

**Comment by futureflsl** [comment]
have you solved your problem?I just stuck in this proble likie you.can you share the code here or for me?

**Comment by NacerFaraj** [comment]
> have you solved your problem?I just stuck in this problem like you.can you share the code here or for me?

not yet :-(

**Comment by glenn-jocher** [comment]
@NacerFaraj we don't provide assistance debugging custom code due to limited resources, however for custom workflows be aware that YOLOv5 models expect inputs in RGB order.

**Comment by tingzliz** [comment]
> > have you solved your problem?I just stuck in this problem like you.can you share the code here or for me?
> 
> not yet :-(

+1 same here :(

**Comment by hilevelhdd** [comment]
I don't think yolov5 can be used in this opencv4.5.4.
The model is loaded but not detected

**Comment by PauloASMendes** [comment]
You can use Yolo the next way. In C++

auto net = cv::dnn::readNetFromONNX("yolov5.onnx");
    // using GPU for image processing
    //net.setPreferableBackend(cv::dnn::DNN_BACKEND_CUDA);
    //net.setPreferableTarget(cv::dnn::DNN_TARGET_CUDA);
    // using CPU for image processing
    net.setPreferableBackend(cv::dnn::DNN_BACKEND_OPENCV);
    net.setPreferableTarget(cv::dnn::DNN_TARGET_CPU);
    auto output_names = net.getUnconnectedOutLayersNames();
    cv::Mat myROI_redefined_YOLO, blob;
    std::vector<cv::Mat> detections;
    std::vector<int> indices[NUM_CLASSES];
    std::vector<cv::Rect> boxes[NUM_CLASSES];
    std::vector<float> scores[NUM_CLASSES];

// Creates 4-dimensional blob from image.
    cv::dnn::blobFromImage(myROI_redefined_YOLO, blob, 0.00392, cv::Size(myROI_redefined_YOLO.rows, myROI_redefined_YOLO.cols), cv::Scalar(), true, false, CV_32F);
    net.setInput(blob);
    net.forward(detections, output_names);
    // object detection using YOLOV5
    for (auto& output : detections){
            const auto num_boxes = output.rows;
            for (int i = 0; i < num_boxes; i++){
                //calculo das 5 predições para cada bounding box: x, y, w, h , confiança
                auto x = output.at<float>(i, 0) * myROI_redefined_YOLO.cols;
                auto y = output.at<float>(i, 1) * myROI_redefined_YOLO.rows;
                auto width = output.at<float>(i, 2) * myROI_redefined_YOLO.cols;
                auto height = output.at<float>(i, 3) * myROI_redefined_YOLO.rows;
                cv::Rect rect(x - width/2, y - height/2, width, height);
                
                for (int c = 0; c < NUM_CLASSES; c++){
                    auto confidence = *output.ptr<float>(i, 5 + c);
                    if (confidence >= CONFIDENCE_THRESHOLD){
                        boxes[c].push_back(rect);
                        scores[c].push_back(confidence);
                    }
                }
            }
    }
    // Realiza a supressão não máxima das bounding boxes e das pontuações  de confiança correspondentes.
    // eliminação de bounding boxes repetidas que identificam o mesmo objecto.
    for (int c = 0; c < NUM_CLASSES; c++)
            cv::dnn::NMSBoxes(boxes[c], scores[c], 0.0, NMS_THRESHOLD, indices[c]);
        
    // identificação dos objectos e correspondentes pontuações de confiança através de bounding boxes. 
    for (int c= 0; c < NUM_CLASSES; c++){
            for (size_t i = 0; i < indices[c].size(); ++i){
                const auto color = colors[c % NUM_COLORS];

                auto idx = indices[c][i];
                const auto& rect = boxes[c][idx];
                cv::rectangle(myROI_redefined_YOLO, cv::Point(rect.x, rect.y), cv::Point(rect.x + rect.width, rect.y + rect.height), color, 3);
                
                // coloco a identificação da classe do objeto contido na bounding box - pedestre ou garrafa por ex.
                std::ostringstream label_ss;
                label_ss << class_names[c] << ": " << std::fixed << std::setprecision(2) << scores[c][idx];
                auto label = label_ss.str();
                
                int baseline;
                auto label_bg_sz = cv::getTextSize(label.c_str(), cv::FONT_HERSHEY_COMPLEX_SMALL, 1, 1, &baseline);
                // defino o rectangulo que define o objeto detectado
                cv::rectangle(myROI_redefined_YOLO, cv::Point(rect.x, rect.y - label_bg_sz.height - baseline - 10), cv::Point(rect.x + label_bg_sz.width, rect.y), color, cv::FILLED);
                // coloco a identificação da classe do objecto detectado.
                cv::putText(myROI_redefined_YOLO, label.c_str(), cv::Point(rect.x, rect.y - baseline - 5), cv::FONT_HERSHEY_COMPLEX_SMALL, 1, cv::Scalar(0, 0, 0));
            }
    }

There must be changed one or other things, but I think it will work.
If you are able to detect something please answer this comment.

**Comment by PauloASMendes** [comment]
@hilevelhdd @futureflsl @NacerFaraj  please see the last comment and tell us your result.

Good luck

**Comment by PauloASMendes** [comment]
I have installed OpenCV 4.5.4 and correctly loaded the model with cv::dnn::readNetFromONNX("yolov5.onnx") after python3 export.py --weights best.pt --include onnx --simplify.

However I was unable to make detections. The output is a downscaled image without any prediction.

**Comment by glenn-jocher** [comment]
@PauloMendes33 DNN inference is simple:

```
python export.py --weights yolov5s.pt --include onnx
python detect.py --weights yolov5s.onnx --dnn
```

**Comment by rtrahms** [comment]
I have the same issue...
1) python detect.py using the exported onnx weights files and a sample image works.
2) OpenCV 4.5.4 can load the same onnx file in a simple CPP app.
3) No detections found from the same sample image in that CPP app.

**Comment by rchaud99** [comment]
> I have the same issue...
> 
> 1. python detect.py using the exported onnx weights files and a sample image works.
> 2. OpenCV 4.5.4 can load the same onnx file in a simple CPP app.
> 3. No detections found from the same sample image in that CPP app.

Were you able to figure this out @rtrahms ?

**Comment by Hexmagic** [comment]
> I have the same issue...
> 
> 1. python detect.py using the exported onnx weights files and a sample image works.
> 2. OpenCV 4.5.4 can load the same onnx file in a simple CPP app.
> 3. No detections found from the same sample image in that CPP app.

have a look at my repo [ONNX-yolov5](https://github.com/Hexmagic/ONNX-yolov5/blob/master/src/detector.cpp)

**Comment by glenn-jocher** [comment]
@Hexmagic awesome, nice work! We don't have any good C++ inference example ourselves unfortunately.

**Comment by rchaud99** [comment]
Thanks @Hexmagic! Are you getting the same results for predictions as you are using the detect.py that @glenn-jocher recommends? I'm getting wildly different results on OpenCV (even on python) than using detect.py, with the same model and inputs.

**Comment by Hexmagic** [comment]
> Thanks @Hexmagic! Are you getting the same results for predictions as you are using the detect.py that @glenn-jocher recommends? I'm getting wildly different results on OpenCV (even on python) than using detect.py, with the same model and inputs.

detect.py use img original shape，not 640x640

**Comment by rchaud99** [comment]
> > Thanks @Hexmagic! Are you getting the same results for predictions as you are using the detect.py that @glenn-jocher recommends? I'm getting wildly different results on OpenCV (even on python) than using detect.py, with the same model and inputs.
> 
> detect.py use img original shape，not 640x640

Where in detect.py is this? I see that the default --imgsz parameter is 640x640 on line 54

**Comment by Hexmagic** [comment]
detect.py 108 line `pt = True `and `img_size = 640` and `stride = 32`
```python
dataset = LoadImages(source, img_size=imgsz, stride=stride, auto=pt)
```
augmentation.py line 105, `auto=True` will make minimum rectangle,
```python
dw, dh = new_shape[1] - new_unpad[0], new_shape[0] - new_unpad[1]  # wh padding  (640-480)=160, (640-640)=0
if auto:  # minimum rectangle
    dw, dh = np.mod(dw, stride), np.mod(dh, stride)  # wh padding  160%320=0, 0%32=0
```

**Comment by Hexmagic** [comment]
> > > Thanks @Hexmagic! Are you getting the same results for predictions as you are using the detect.py that @glenn-jocher recommends? I'm getting wildly different results on OpenCV (even on python) than using detect.py, with the same model and inputs.
> > 
> > 
> > detect.py use img original shape，not 640x640
> 
> Where in detect.py is this? I see that the default --imgsz parameter is 640x640 on line 54



I was wrong,detect.py not use original shape or 640x640,108 line `pt = True `and `img_size = 640` and `stride = 32`
```python
dataset = LoadImages(source, img_size=imgsz, stride=stride, auto=pt)
```
augmentation.py line 105, `auto=True` will make minimum rectangle,
```python
dw, dh = new_shape[1] - new_unpad[0], new_shape[0] - new_unpad[1]  # wh padding  (640-480)=160, (640-640)=0
if auto:  # minimum rectangle
    dw, dh = np.mod(dw, stride), np.mod(dh, stride)  # wh padding  160%320=0, 0%32=0
```

**Comment by rchaud99** [comment]
> I was wrong,detect.py not use original shape or 640x640,108 line `pt = True `and `img_size = 640` and `stride = 32`
> 
> ```python
> dataset = LoadImages(source, img_size=imgsz, stride=stride, auto=pt)
> ```
> 
> augmentation.py line 105, `auto=True` will make minimum rectangle,
> 
> ```python
> dw, dh = new_shape[1] - new_unpad[0], new_shape[0] - new_unpad[1]  # wh padding  (640-480)=160, (640-640)=0
> if auto:  # minimum rectangle
>     dw, dh = np.mod(dw, stride), np.mod(dh, stride)  # wh padding  160%320=0, 0%32=0
> ```

Thanks - any idea why OpenCV net is much lower confidence than detect.py even when same resolution? Or is it the same for you?

**Comment by Hexmagic** [comment]
> > I was wrong,detect.py not use original shape or 640x640,108 line `pt = True `and `img_size = 640` and `stride = 32`
> > ```python
> > dataset = LoadImages(source, img_size=imgsz, stride=stride, auto=pt)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > augmentation.py line 105, `auto=True` will make minimum rectangle,
> > ```python
> > dw, dh = new_shape[1] - new_unpad[0], new_shape[0] - new_unpad[1]  # wh padding  (640-480)=160, (640-640)=0
> > if auto:  # minimum rectangle
> >     dw, dh = np.mod(dw, stride), np.mod(dh, stride)  # wh padding  160%320=0, 0%32=0
> > ```
> 
> Thanks - any idea why OpenCV net is much lower confidence than detect.py even when same resolution? Or is it the same for you?

general.py line 701, function `non_max_suppression`

```python
# Compute conf
x[:, 5:] *= x[:, 4:5]  # conf = obj_conf * cls_conf
```
and this is my [cpp file](https://github.com/Hexmagic/ONNX-yolov5/blob/master/src/test.cpp),whice get same result compare to detect.py

**Comment by rchaud99** [comment]
Thank you very much @Hexmagic 😄

**Comment by godlovehill** [comment]
@Hexmagic great job! I noticed some blogs but all of them accuracy goes down compared official version, your works really help me a lot! ^_^

**Comment by fisakhan** [comment]
I encounter the following error using `net = cv::dnn::readNetFromONNX("yolov5.onnx");` What am I missing or doing wrong?

> [ERROR:0@0.003] global /home/opencv_build/opencv/modules/dnn/src/onnx/onnx_importer.cpp (2564) parseShape DNN/ONNX(Shape): dynamic 'zero' shapes are not supported, input 243 [ 0 0 0 51 ]
> [ERROR:0@0.003] global /home/opencv_build/opencv/modules/dnn/src/onnx/onnx_importer.cpp (1042) handleNode DNN/ONNX: ERROR during processing node with 1 inputs and 1 outputs: [Shape]:(onnx_node!Shape_70) from domain='ai.onnx'
> terminate called after throwing an instance of 'cv::Exception'
>   what():  OpenCV(4.6.0-dev) /home/opencv_build/opencv/modules/dnn/src/onnx/onnx_importer.cpp:1064: error: (-2:Unspecified error) in function 'handleNode'
> > Node [Shape@ai.onnx]:(onnx_node!Shape_70) parse error: OpenCV(4.6.0-dev) /home/opencv_build/opencv/modules/dnn/src/onnx/onnx_importer.cpp:2565: error: (-215:Assertion failed) !isDynamicShape in function 'parseShape'
> > 
> Aborted (core dumped)

**Comment by glenn-jocher** [comment]
@fisakhan since this error was generated by cv2 on a working ONNX model you should raise this directly with OpenCV.

**Comment by mowais2170** [comment]
@fisakhan 
export your model using this then try again it will work

python export.py --weights yolov5s.pt --include onnx --simplify
