### ISSUE TITLE
KeyError: 'model.24.anchor_grid' with v6.0

### ISSUE THREAD

**Issue by deepsworld** [ultralytics/yolov5#5379]
## ❔Question
There is an additional key called `model.24.anchor_grid` in yolov5-v6.0 checkpoints which does not exist in the model loaded with `hub.load(pretrained=False)`. I am not sure if this is intended or I am missing any argument. I appreciate your help. 
## Additional context
Minimal code to reproduce the error
```py
import torch
from torch import hub
# pytorch 1.9 workaround 
torch.hub._validate_not_a_forked_repo=lambda a,b,c: True

def github_release_url(owner, project, tag, name):
    return f"https://github.com/{owner}/{project}/releases/download/{tag}/{name}"

tag = 'v6.0'
chkpt = 'yolov5x'
model = hub.load(f'ultralytics/yolov5:{tag}', chkpt, False, 3, 80, force_reload=True, autoshape=False)
url = github_release_url('ultralytics', 'yolov5', tag, f'{chkpt}.pt')
chkpt = hub.load_state_dict_from_url(url,
                                     model_dir=None,
                                     map_location=torch.device('cpu'))
state_dict = chkpt['model'].float().state_dict()

try:
    state_dict = { k: v for k, v in state_dict.items() if model.state_dict()[k].shape == v.shape }
except Exception as e:
    raise e
```

**Comment by deepsworld** [comment]
NOTE: The version `v5.0` when loaded in similar fashion works fine. 
@glenn-jocher  Is there a reason the register buffer for anchor grid was removed from the `Detect` module and only added when pretrained is True. Here: https://github.com/ultralytics/yolov5/blob/v5.0/models/yolo.py#L37

**Comment by glenn-jocher** [comment]
@deepsworld yes this change was introduced in OpenCV DNN PR https://github.com/ultralytics/yolov5/pull/4833, along with backward compatibility updates to allow previous version models to load and run correctly.

**Comment by Wangwang99999** [comment]
I don't see any answer to this question. Why there is no 'model.24.anchor_grid' in trained model, but it do exist in pretrained models.

**Comment by glenn-jocher** [comment]
@Wangwang99999 architecture may update over time
