### ISSUE TITLE
problem in save .pt

### ISSUE THREAD

**Issue by PariaDarbani** [ultralytics/yolov5#5380]
I trained yolov5 small. The size of best.pt is 55.9MB.
I load, then save it in CPU device as follows:
model = torch.hub.load("PATH\\yolov5-master", 'custom', path="PATH\\best.pt", source='local')
model.eval()
torch.save(model.state_dict(), "PATH\\new-best.pt")

But new-best.pt is 27.8MB and it doesn't work.

**Comment by glenn-jocher** [comment]
@PariaDarbani this is incorrect saving behavior, the file not working is expected. YOLOv5 pt files are dictionaries that include model keys. See train.py for an example model saving:

https://github.com/ultralytics/yolov5/blob/ed887b5976d94dc61fa3f7e8e07170623dc7d6ee/train.py#L376-L387

**Comment by zcunyi** [comment]
> @PariaDarbani this is incorrect saving behavior, the file not working is expected. YOLOv5 pt files are dictionaries that include model keys. See train.py for an example model saving:
> 
> https://github.com/ultralytics/yolov5/blob/ed887b5976d94dc61fa3f7e8e07170623dc7d6ee/train.py#L376-L387

I want to save the model by 'torch.save(model.state_dict())', how can I do ? thanks
