### ISSUE TITLE
training with my weight

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#5381]
## ❔Question
I already train my data and the weight names are w1.pt and w2.pt .
w1.pt is training with 300 epoch.
w2.pt is training with 100 epoch. (The goal is 300 but I stop it)

If I train another data and base on w1.pt and w2.pt.
This will start from 0 epoch. 
```
python train.py --weights w1.pt
```

This will start from 100 epoch
```
python train.py --weights w2.pt
```

How can I control the epoch to train?

**Comment by glenn-jocher** [comment]
@alicera yes this is correct behavior because w1 is fully trained and has had it's optimizer and EMA  stripped. w2 is partially trained and still has optimizer, EMA attached to checkpoint for resuming.
