### ISSUE TITLE
Using force reload=True,still got error

### ISSUE THREAD

**Issue by alanotmt** [ultralytics/yolov5#5383]
`import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s',force_reload=True)  # or yolov5m, yolov5l, yolov5x, custom

# Images
img = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, PIL, OpenCV, numpy, list

# Inference
results = model(img)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.`

Using force reload=True,still got error

`Downloading: "https://github.com/ultralytics/yolov5/archive/master.zip" to /home/alantse/.cache/torch/hub/master.zip
YOLOv5 🚀 2021-10-29 torch 1.10.0+cu102 CUDA:0 (NVIDIA GeForce RTX 3070, 7973.875MB)

Downloading https://github.com/ultralytics/yolov5/releases/download/v6.0/yolov5s.pt to /home/alantse/.cache/torch/hub/ultralytics_yolov5_master/yolov5s.pt...
100%
14.0M/14.0M [00:00<00:00, 23.5MB/s]

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py in _create(name, pretrained, channels, classes, autoshape, verbose, device)
     45         if pretrained and channels == 3 and classes == 80:
---> 46             model = attempt_load(path, map_location=device)  # download/load FP32 model
     47         else:

~/.cache/torch/hub/ultralytics_yolov5_master/models/experimental.py in attempt_load(weights, map_location, inplace, fuse)
     95         if fuse:
---> 96             model.append(ckpt['ema' if ckpt.get('ema') else 'model'].float().fuse().eval())  # FP32 model
     97         else:

~/anaconda3/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py in float(self)
    734         """
--> 735         return self._apply(lambda t: t.float() if t.is_floating_point() else t)
    736 

~/.cache/torch/hub/ultralytics_yolov5_master/models/yolo.py in _apply(self, fn)
    238         # Apply to(), cpu(), cuda(), half() to model tensors that are not parameters or registered buffers
--> 239         self = super()._apply(fn)
    240         m = self.model[-1]  # Detect()

~/anaconda3/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py in _apply(self, fn)
    569         for module in self.children():
--> 570             module._apply(fn)
    571 

~/anaconda3/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py in _apply(self, fn)
    569         for module in self.children():
--> 570             module._apply(fn)
    571 

~/anaconda3/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py in _apply(self, fn)
    569         for module in self.children():
--> 570             module._apply(fn)
    571 

~/anaconda3/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py in _apply(self, fn)
    592             with torch.no_grad():
--> 593                 param_applied = fn(param)
    594             should_use_set_data = compute_should_use_set_data(param, param_applied)

~/anaconda3/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py in <lambda>(t)
    734         """
--> 735         return self._apply(lambda t: t.float() if t.is_floating_point() else t)
    736 

RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

The above exception was the direct cause of the following exception:

Exception                                 Traceback (most recent call last)
/tmp/ipykernel_109053/694030760.py in <module>
      2 
      3 # Model
----> 4 model = torch.hub.load('ultralytics/yolov5', 'yolov5s',force_reload=True)  # or yolov5m, yolov5l, yolov5x, custom
      5 
      6 # Images

~/anaconda3/envs/py39/lib/python3.9/site-packages/torch/hub.py in load(repo_or_dir, model, source, force_reload, verbose, skip_validation, *args, **kwargs)
    397         repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, verbose, skip_validation)
    398 
--> 399     model = _load_local(repo_or_dir, model, *args, **kwargs)
    400     return model
    401 

~/anaconda3/envs/py39/lib/python3.9/site-packages/torch/hub.py in _load_local(hubconf_dir, model, *args, **kwargs)
    426 
    427     entry = _load_entry_from_hubconf(hub_module, model)
--> 428     model = entry(*args, **kwargs)
    429 
    430     sys.path.remove(hubconf_dir)

~/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py in yolov5s(pretrained, channels, classes, autoshape, verbose, device)
     78 def yolov5s(pretrained=True, channels=3, classes=80, autoshape=True, verbose=True, device=None):
     79     # YOLOv5-small model https://github.com/ultralytics/yolov5
---> 80     return _create('yolov5s', pretrained, channels, classes, autoshape, verbose, device)
     81 
     82 

~/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py in _create(name, pretrained, channels, classes, autoshape, verbose, device)
     63         help_url = 'https://github.com/ultralytics/yolov5/issues/36'
     64         s = 'Cache may be out of date, try `force_reload=True`. See %s for help.' % help_url
---> 65         raise Exception(s) from e
     66 
     67 

Exception: Cache may be out of date, try `force_reload=True`. See https://github.com/ultralytics/yolov5/issues/36 for help.`

**Comment by glenn-jocher** [comment]
@alanotmt it appears you may have CUDA/environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below. 


## Requirements

[**Python>=3.6.0**](https://www.python.org/) with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) installed including [**PyTorch>=1.7**](https://pytorch.org/get-started/locally/). To get started:
```bash
$ git clone https://github.com/ultralytics/yolov5
$ cd yolov5
$ pip install -r requirements.txt
```

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), validation ([val.py](https://github.com/ultralytics/yolov5/blob/master/val.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/export.py)) on MacOS, Windows, and Ubuntu every 24 hours and on every commit.

**Comment by RANA-ATI** [comment]
Same Error


File [~/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py:49](https://file+.vscode-resource.vscode-cdn.net/d%3A/Google%20GDCSE/Models/Recycling%20Model/Model%20Deployment/~/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py:49), in _create(name, pretrained, channels, classes, autoshape, verbose, device)
     48 try:
---> 49     model = DetectMultiBackend(path, device=device, fuse=autoshape)  # detection model
     50     if autoshape:

File [~/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:344](https://file+.vscode-resource.vscode-cdn.net/d%3A/Google%20GDCSE/Models/Recycling%20Model/Model%20Deployment/~/.cache/torch/hub/ultralytics_yolov5_master/models/common.py:344), in DetectMultiBackend.__init__(self, weights, device, dnn, data, fp16, fuse)
    343 if pt:  # PyTorch
--> 344     model = attempt_load(weights if isinstance(weights, list) else w, device=device, inplace=True, fuse=fuse)
    345     stride = max(int(model.stride.max()), 32)  # model stride

File [~/.cache\torch\hub\ultralytics_yolov5_master\models\experimental.py:80](https://file+.vscode-resource.vscode-cdn.net/d%3A/Google%20GDCSE/Models/Recycling%20Model/Model%20Deployment/~/.cache/torch/hub/ultralytics_yolov5_master/models/experimental.py:80), in attempt_load(weights, device, inplace, fuse)
     79 ckpt = torch.load(attempt_download(w), map_location='cpu')  # load
---> 80 ckpt = (ckpt.get('ema') or ckpt['model']).to(device).float()  # FP32 model
     82 # Model compatibility updates

KeyError: 'model'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
File [~/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py:60](https://file+.vscode-resource.vscode-cdn.net/d%3A/Google%20GDCSE/Models/Recycling%20Model/Model%20Deployment/~/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py:60), in _create(name, pretrained, channels, classes, autoshape, verbose, device)
     59     except Exception:
---> 60         model = attempt_load(path, device=device, fuse=False)  # arbitrary model
...
     76 help_url = 'https://github.com/ultralytics/yolov5/issues/36'
     77 s = f'{e}. Cache may be out of date, try `force_reload=True` or see {help_url} for help.'
---> 78 raise Exception(s) from e

Exception: 'model'. Cache may be out of date, try `force_reload=True` or see https://github.com/ultralytics/yolov5/issues/36 for help.


I trained the yolov5 model on custom dataset over colab and saved the model to use it for prediction over my local PC. But after trying everything, even making new env cant able to do that

**Comment by RANA-ATI** [comment]
> @alanotmt it appears you may have CUDA/environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally. If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below.
> 
> ## Requirements
> [**Python>=3.6.0**](https://www.python.org/) with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) installed including [**PyTorch>=1.7**](https://pytorch.org/get-started/locally/). To get started:
> 
> ```shell
> $ git clone https://github.com/ultralytics/yolov5
> $ cd yolov5
> $ pip install -r requirements.txt
> ```
> 
> ## Environments
> YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):
> 
> * **Google Colab and Kaggle** notebooks with free GPU: [![Open In Colab](https://camo.githubusercontent.com/84f0493939e0c4de4e6dbe113251b4bfb5353e57134ffd9fcab6b8714514d4d1/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb) [![Open In Kaggle](https://camo.githubusercontent.com/a08ca511178e691ace596a95d334f73cf4ce06e83a5c4a5169b8bb68cac27bef/68747470733a2f2f6b6167676c652e636f6d2f7374617469632f696d616765732f6f70656e2d696e2d6b6167676c652e737667)](https://www.kaggle.com/models/ultralytics/yolov5)
> * **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
> * **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
> * **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) [![Docker Pulls](https://camo.githubusercontent.com/280faedaf431e4c0c24fdb30ec00a66d627404e5c4c498210d3f014dd58c2c7e/68747470733a2f2f696d672e736869656c64732e696f2f646f636b65722f70756c6c732f756c7472616c79746963732f796f6c6f76353f6c6f676f3d646f636b6572)](https://hub.docker.com/r/ultralytics/yolov5)
> 
> ## Status
> ![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)
> 
> If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), validation ([val.py](https://github.com/ultralytics/yolov5/blob/master/val.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/export.py)) on MacOS, Windows, and Ubuntu every 24 hours and on every commit.

Same Error


File [~/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py:49](https://file+.vscode-resource.vscode-cdn.net/d%3A/Google%20GDCSE/Models/Recycling%20Model/Model%20Deployment/~/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py:49), in _create(name, pretrained, channels, classes, autoshape, verbose, device)
     48 try:
---> 49     model = DetectMultiBackend(path, device=device, fuse=autoshape)  # detection model
     50     if autoshape:

File [~/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:344](https://file+.vscode-resource.vscode-cdn.net/d%3A/Google%20GDCSE/Models/Recycling%20Model/Model%20Deployment/~/.cache/torch/hub/ultralytics_yolov5_master/models/common.py:344), in DetectMultiBackend.__init__(self, weights, device, dnn, data, fp16, fuse)
    343 if pt:  # PyTorch
--> 344     model = attempt_load(weights if isinstance(weights, list) else w, device=device, inplace=True, fuse=fuse)
    345     stride = max(int(model.stride.max()), 32)  # model stride

File [~/.cache\torch\hub\ultralytics_yolov5_master\models\experimental.py:80](https://file+.vscode-resource.vscode-cdn.net/d%3A/Google%20GDCSE/Models/Recycling%20Model/Model%20Deployment/~/.cache/torch/hub/ultralytics_yolov5_master/models/experimental.py:80), in attempt_load(weights, device, inplace, fuse)
     79 ckpt = torch.load(attempt_download(w), map_location='cpu')  # load
---> 80 ckpt = (ckpt.get('ema') or ckpt['model']).to(device).float()  # FP32 model
     82 # Model compatibility updates

KeyError: 'model'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
File [~/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py:60](https://file+.vscode-resource.vscode-cdn.net/d%3A/Google%20GDCSE/Models/Recycling%20Model/Model%20Deployment/~/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py:60), in _create(name, pretrained, channels, classes, autoshape, verbose, device)
     59     except Exception:
---> 60         model = attempt_load(path, device=device, fuse=False)  # arbitrary model
...
     76 help_url = 'https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading'
     77 s = f'{e}. Cache may be out of date, try `force_reload=True` or see {help_url} for help.'
---> 78 raise Exception(s) from e

Exception: 'model'. Cache may be out of date, try `force_reload=True` or see https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading for help.


I trained the yolov5 model on custom dataset over colab and saved the model to use it for prediction over my local PC. But after trying everything, even making new env cant able to do that


CODE IS 

import torch
import cv2
# from utils.plots import plot_one_box


def countTree(img):
    # Load the trained model from the checkpoint file
    # model = torch.hub.load('ultralytics/yolov5', 'custom',
    #                        path='weights/yolov5_model.pt', force_reload=True)
    device = torch.device('cpu')
    model = torch.hub.load('ultralytics/yolov5', 'custom',
                           path='weights/yolov5_model.pt', force_reload=True, device=device)

    results = model(img)

    # for result in results.xyxy[0]:
    #     plot_one_box(result[:4], image, label=f'{result[5]} {result[4]:.2f}')

    # cv2.imshow('Image', image)
    # cv2.waitKey(0)
    # cv2.destroyAllWindows()

    num_bboxes = len(results.xyxy[0])
    return num_bboxes
