### ISSUE TITLE
Detect.py device type

### ISSUE THREAD

**Issue by Chimchar009** [ultralytics/yolov5#5385]
## ❔Question
How do i check the device type in the --device when running the detect.py code

## Additional context
I am using the nvidia jetson xavier NX and im trying to get the detection code to use gpu instead of cpu but when i try to use --device it doesnt work or i just dont know how to use it

**Comment by glenn-jocher** [comment]
@Chimchar009 utilized `--device` is displayed in console when running any command. If your CUDA device is not displayed when using `--device 0` then you have environment/CUDA issues.

<img width="1012" alt="Screen Shot 2021-10-29 at 11 50 42 AM" src="https://user-images.githubusercontent.com/26833433/139414799-af1c01fa-8388-4315-add3-a1c5a2740fc2.png">

**Comment by Chimchar009** [comment]
is there anyway i can check what available devices are on the jetson xavier nx?
i have been trying to find but i cant seem to find the right answers or if im not asking the right questions

**Comment by Chimchar009** [comment]
my jetson source library says opencv 4.5.4 compiled cuda yes
but i cant get it to detect the gpu and use cuda

**Comment by glenn-jocher** [comment]
@Chimchar009 if your CUDA device(s) are not used by default by detect.py then your environment is not CUDA capable. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below. 


## Requirements

[**Python>=3.6.0**](https://www.python.org/) with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) installed including [**PyTorch>=1.7**](https://pytorch.org/get-started/locally/). To get started:
```bash
$ git clone https://github.com/ultralytics/yolov5
$ cd yolov5
$ pip install -r requirements.txt
```

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), validation ([val.py](https://github.com/ultralytics/yolov5/blob/master/val.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/export.py)) on MacOS, Windows, and Ubuntu every 24 hours and on every commit.

**Comment by Chimchar009** [comment]
i fixed the problem with pytorch and torchvision not installing properly as a source library on the jetson xavier thank you
