### ISSUE TITLE
training stuck at enumerate

### ISSUE THREAD

**Issue by twangnh** [ultralytics/yolov5#539]
Hi I just tried training yolov5, the enviroment is exactly as requirment file, but the training is stucking at https://github.com/ultralytics/yolov5/blob/7f8471eaebe4b192c5e6ab4e5c821d91e43cb4fe/train.py#L259

training output:

```
Optimizer groups: 62 .bias, 70 conv.weight, 59 other
Scanning labels ../coco/labels/train2017.cache (117266 found, 0 missing, 1021 em
Scanning labels ../coco/labels/val2017.cache (4952 found, 0 missing, 48 empty, 0

Analyzing anchors... Best Possible Recall (BPR) = 0.9949
Image sizes 640 train, 640 test
Using 8 dataloader workers
Starting training for 300 epochs...

     Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
  0%|                                                  | 0/1849 [00:00<?, ?it/s]Expected: %s to exist.
NoneType: None
Expected: %s to exist.
NoneType: None
Expected: %s to exist.
NoneType: None
Expected: %s to exist.
NoneType: None
Expected: %s to exist.
NoneType: None
Expected: %s to exist.
NoneType: None
Expected: %s to exist.
NoneType: None
Expected: %s to exist.
NoneType: None
```

could you pls help?

**Comment by glenn-jocher** [comment]
@twangnh not sure. Recommend starting from a working environment if you are having issues.

## Environment

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)

**Comment by ljmiao** [comment]
I meet the problem too, 
     Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
  0%|                                                                                              | 0/4927 [00:00<?, ?it/s]
the output is always like this, I found that it is stucking at loading dataset, do you solve the problem @twangnh ?
