### ISSUE TITLE
instead of upsampling operations

### ISSUE THREAD

**Issue by yang-leon996** [ultralytics/yolov5#5397]
## ❔Question
nn.ConvTranspose2d()
## Additional context
If I want to use nn.ConvTranspose2d() instead of the original upsampling operations,what should I modify nn.Unsample?Thanks!

**Comment by glenn-jocher** [comment]
@yang-leon996 I don't understand your question. Your two operations are not compatible, they produce different shape outputs.

**Comment by yang-leon996** [comment]
In yolo5m.yaml, I want to remove [-1, 1, nn.Upsample, [None, 2, 'nearest']],and use nn.ConvTranspose2d() to  restore to the resolution of P4，like [-1, 1, nn.ConvTranspose2d, [384, 3, 2, 1, 1]]. But it get the error"RuntimeError: torch.cat(): Sizes of tensors must match except in dimension 1. Got 7 and 16 in dimension 2 ".

**Comment by glenn-jocher** [comment]
@yang-leon996 ah I see! I read the docs, this transpose appears to be a deconv of sorts:
https://pytorch.org/docs/stable/generated/torch.nn.ConvTranspose2d.html

Just keep in mind the YOLOv5 upsample layers are scaling width and height by 2, i.e.:

B,C,W,H -> B,C,2W,2H

If you can reproduce similar behavior with your proposed layer it should be line replaceable. For channel differences you may need to experiment with additional changes that may be required.

**Comment by glenn-jocher** [comment]
@yang-leon996 I ran an experiment, it seems very easy to replace Upsample with ConvTranspose2d.

```python
import torch
from utils.torch_utils import profile

m1 = torch.nn.ConvTranspose2d(256, 256, 2, 2, 0)
m2 = torch.nn.Upsample(None, 2, 'nearest')
results = profile(input=torch.randn(16, 256, 80, 80), ops=[m1, m2], n=3)
```

<img width="969" alt="Screenshot 2021-10-29 at 15 37 22" src="https://user-images.githubusercontent.com/26833433/139444785-36cf848d-b162-4629-88f4-7cc647b4e86f.png">

**Comment by yang-leon996** [comment]
oh, I got it! Thank you !

**Comment by glenn-jocher** [comment]
@yang-leon996 to use this module properly you can insert it into yolov5s.yaml here:

```yaml
# YOLOv5 v6.0 head
head:
  [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.ConvTranspose2d, [512, 2, 2, 0]],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, C3, [512, False]],  # 13
```

**Comment by glenn-jocher** [comment]
@yang-leon996 but you also need to update this line to add `nn.ConvTranspose2d` to the list of modules that must scale channel count by compound scaling constants:
https://github.com/ultralytics/yolov5/blob/ed887b5976d94dc61fa3f7e8e07170623dc7d6ee/models/yolo.py#L265-L266

**Comment by glenn-jocher** [comment]
```yaml
# YOLOv5 🚀 by Ultralytics, GPL-3.0 license

# Parameters
nc: 80  # number of classes
depth_multiple: 0.33  # model depth multiple
width_multiple: 0.50  # layer channel multiple
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

# YOLOv5 v6.0 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [64, 6, 2, 2]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C3, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 6, C3, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, C3, [512]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 3, C3, [1024]],
   [-1, 1, SPPF, [1024, 5]],  # 9
  ]

# YOLOv5 v6.0 head
head:
  [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.ConvTranspose2d, [512, 2, 2, 0]],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, C3, [512, False]],  # 13

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.ConvTranspose2d, [256, 2, 2, 0]],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, C3, [256, False]],  # 17 (P3/8-small)

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 14], 1, Concat, [1]],  # cat head P4
   [-1, 3, C3, [512, False]],  # 20 (P4/16-medium)

   [-1, 1, Conv, [512, 3, 2]],
   [[-1, 10], 1, Concat, [1]],  # cat head P5
   [-1, 3, C3, [1024, False]],  # 23 (P5/32-large)

   [[17, 20, 23], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
  ]
```

**Comment by glenn-jocher** [comment]
TODO: nn.Upsample -> nn.ConvTranspose2d tests

**Comment by yang-leon996** [comment]
yeah, I have tried it. It runs successfully.

**Comment by Zengyf-CVer** [comment]
@yang-leon996 
How is the operation effect? Is mAP improved?

**Comment by yang-leon996** [comment]
@Zengyf-CVer，I’m running it, and it have not been over.

**Comment by yang-leon996** [comment]
@glenn-jocher I noted that you used the even convolution 2x2，of course, it can work. But I would like to know nn.ConvTranspose2d( in_channels, out_channels, kernel_size=3, stride=2, padding=1, out_padding=1) can get the correct results on local test, but it will get error ,although the same sets deployed in 5m.yaml. Is its parameters [512, 3, 2, 1, 1] greater than 4?

**Comment by glenn-jocher** [comment]
@yang-leon996 yes 3,2,1,1 also works, but takes more time:

```python
import torch
from utils.torch_utils import profile

m1 = torch.nn.Upsample(None, 2, 'nearest')
m2 = torch.nn.ConvTranspose2d(256, 256, 2, 2, 0)
m3 = torch.nn.ConvTranspose2d(256, 256, 3, 2, 1, 1)
results = profile(input=torch.randn(16, 256, 80, 80), ops=[m1, m2, m3], n=10)

YOLOv5 🚀 v6.0-36-ged887b5 torch 1.9.0+cu111 CUDA:0 (Tesla P100-PCIE-16GB, 16280.875MB)

      Params      GFLOPs  GPU_mem (GB)  forward (ms) backward (ms)                   input                  output
           0           0         1.493         1.622         4.624       (16, 256, 80, 80)     (16, 256, 160, 160)
      262400           0         1.179         12.49         20.35       (16, 256, 80, 80)     (16, 256, 160, 160)
      590080           0         1.179         23.02         34.39       (16, 256, 80, 80)     (16, 256, 160, 160)
```

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
This kind of time comparison can only be seen from layer to layer, and it is at the ms level. How can I roughly estimate the actual time required for this replacement without actual training, in hours.

**Comment by glenn-jocher** [comment]
@Zengyf-CVer you can run `python models/yolo.py --profile` to profile a full model and see this layer in the context.

For full training impact just train one epoch both ways.

**Comment by glenn-jocher** [comment]
@yang-leon996 I'm removing TODO on this issue since you've been able to use this module successfully. If you find improved results with this layer instead of nn.Upsample please inform us, thanks!
