### ISSUE TITLE
frame extracting

### ISSUE THREAD

**Issue by mrmoonshine24** [ultralytics/yolov5#5399]
## ❔Question
I can successfully recognise the frames who having the pedestrian crossing within them. To build a bigger dataset is it possible to extract the frames that yolov5 detect and save them to build the dataset bigger? 

Thanks

**Comment by glenn-jocher** [comment]
@mrmoonshine24 detect.py and val.py autolabelling is available with the --save-txt flag:

```bash
python detect.py --save-txt
python val.py --save-txt
```

To add new predictions onto existing labels:
```bash
python val.py --save-hybrid
```

**Comment by mrmoonshine24** [comment]
> @mrmoonshine24 detect.py and val.py autolabelling is available with the --save-txt flag:
> 
> ```shell
> python detect.py --save-txt
> python val.py --save-txt
> ```
> 
> To add new predictions onto existing labels:
> 
> ```shell
> python val.py --save-hybrid
> ```

Thank you for the fast response! The txt data only consist of the box but how can you combine this with the frame of the video. For example: I have used roboflow for labeling, downloading this dataset will have the picture and the labeling within the frame in txt file. I need to have this the same way to make the dataset bigger right?
Thanks again for your response

**Comment by glenn-jocher** [comment]
@mrmoonshine24 --save-txt creates labels in the exact format you need them for training, i.e.

```bash
python detect.py --source image1.jpg --save-txt  # creates image1.txt
```
