### ISSUE TITLE
 Tutorial for small objects

### ISSUE THREAD

**Issue by we1pingyu** [ultralytics/yolov5#54]
## 🚀 Feature

Amazing work! Could you provide a simple tutorial for training for small objects? Just like https://github.com/AlexeyAB/darknet#how-to-improve-object-detection.  I thinl modifying yaml is enough for me.

**Comment by glenn-jocher** [comment]
@we1pingyu hi there. I would simply train normally using https://docs.ultralytics.com/yolov5/tutorials/train_custom_data, and only think about advanced changes if you don't see the performance you are looking for there first.

The intention here is for everything to work well out of the box, with no special settings required.
