### ISSUE TITLE
Yolov5 repo on agx xavier via docker 

### ISSUE THREAD

**Issue by zentorno365** [ultralytics/yolov5#540]
## ❔Question
Hi glenn,
I am trying to run the docker version of yolov5 on my jetson agx xavier and ran into many errors. Upon some google search i saw that Sometimes the repo may be made for ×86 or ×64 systems and jetson agx is an arm 64 device I am facing errors.

Is this true glenn is the yolov5 docker not supported  for jetson Agx Xavier?

Thanks

**Comment by glenn-jocher** [comment]
@krishnam3065 I'm not qualified to answer this question as I've never used this hardware.

**Comment by bhaktatejas922** [comment]
You can likely get it to work by installing pytorch via an arm64 wheel: https://forums.developer.nvidia.com/t/pytorch-for-jetson-version-1-6-0-now-available/72048

**Comment by Jacobsolawetz** [comment]
I filmed a YouTube on the subject of deploying YOLOv5 with PyTorch docker on NVIDIA Jetson devices

https://www.youtube.com/watch?v=0RqvMBj7A4I
