### ISSUE TITLE
Head effectiveness

### ISSUE THREAD

**Issue by Zhiying-Li-dot** [ultralytics/yolov5#5406]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

From three heads to four heads, how do you explain its effectiveness?Could you please tell me?Thanks a lot.

**Comment by glenn-jocher** [comment]
@lizhiying-2019 If you're asking about P5 vs P6 heads, the P6 output layer is at stride 64, allowing for better detection of large objects. See v5.0 release notes for more details.
https://github.com/ultralytics/yolov5/releases/tag/v5.0

**Comment by Zhiying-Li-dot** [comment]
Thanks a lot.I get it.
