### ISSUE TITLE
About wandb export

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#5407]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

@AyushExel 
How can I export the data in wandb as a csv file to the local?
![11111](https://user-images.githubusercontent.com/41098760/139520318-b6778fd6-9ec8-4320-bb93-6f676fffdbdd.PNG)

**Comment by glenn-jocher** [comment]
@AyushExel what's the right way to export graph data from W&B as CSV?

**Comment by AyushExel** [comment]
![Screenshot from 2021-10-30 22-09-41](https://user-images.githubusercontent.com/15766192/139541684-6cae8b1f-8197-43d9-898f-74f80a3cc4f5.png)
Goto the panel you want to export, click on the options menu, click on export, then select csv format

**Comment by Zengyf-CVer** [comment]
@AyushExel @glenn-jocher 
I learned, thank you very much.
