### ISSUE TITLE
do anyone have yolov5 inference code using openvino using python??. i found some but none of them are working 

### ISSUE THREAD

**Issue by Rajesh-mandal** [ultralytics/yolov5#5408]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have a code but it's not working . i am getting output like below, when i am inferencing with openvino model using python 

![image](https://user-images.githubusercontent.com/47553660/139521835-a6857600-21e9-4d5a-9106-407dc3f7334b.png)

**Comment by Rajesh-mandal** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.
> 
> ### Question
> I have a code but it's not working . i am getting output like below, when i am inferencing with openvino model using python
> 
> ![image](https://user-images.githubusercontent.com/47553660/139521835-a6857600-21e9-4d5a-9106-407dc3f7334b.png)
> 
> ### Additional
> _No response_

i  manage to fix the code. now it's working

**Comment by Rajesh-mandal** [comment]
divide the image by 255..or normalize the image after resizing the images..

**Comment by glenn-jocher** [comment]
@Rajesh-mandal following OpenVINO export PR #6057 we'll be doing a new PR for OpenVINO inference with detect.py/val.py.

**Comment by glenn-jocher** [comment]
@Rajesh-mandal do you think you could help us with OpenVINO inference now that export is complete? We need to add OpenVino fields to DetectMultBackend() for this purpose. I've never used OpenVINO though so I don't have a good inference example to start from:

https://github.com/ultralytics/yolov5/blob/db6ec66a602a0b64a7db1711acd064eda5daf2b3/models/common.py#L277-L437

**Comment by Rajesh-mandal** [comment]
I will check it out and let you know

**Comment by glenn-jocher** [comment]
@Rajesh-mandal great, thanks!

**Comment by victorsoyvictor** [comment]
> divide the image by 255..or normalize the image after resizing the images..

Can you elaborate a bit more with a piece of code? Thanks.

**Comment by glenn-jocher** [comment]
@victorsoyvictor sure, when preparing images for model inference, you can divide the image by 255 to normalize it. Here's an example using Python:

```python
# Load the image
image = load_image_somehow()

# Resize the image
resized_image = resize_image_somehow(image)

# Normalize the image
normalized_image = resized_image / 255.0
```

This will scale the pixel values in the range [0, 1], which is a common practice for preprocessing images before feeding them into a neural network.
