### ISSUE TITLE
divided by 0 error

### ISSUE THREAD

**Issue by AlexWang1900** [ultralytics/yolov5#541]
Before submitting a bug report, please be aware that your issue **must be reproducible** with all of the following, otherwise it is non-actionable, and we can not help you:
 - **Current repo**: run `git fetch && git status -uno` to check and `git pull` to update repo
 - **Common dataset**: coco.yaml or coco128.yaml
 - **Common environment**: Colab, Google Cloud, or Docker image. See https://github.com/ultralytics/yolov5#reproduce-our-environment
 
If this is a custom dataset/training question you **must include** your `train*.jpg`, `test*.jpg` and `results.png` figures, or we can not help you. You can generate these with `utils.plot_results()`.

## 🐛 Bug
in utils.py line 345:

```
elif CIoU:  # https://github.com/Zzh-tju/DIoU-SSD-pytorch/blob/master/utils/box/box_utils.py#L47
                v = (4 / math.pi ** 2) * torch.pow(torch.atan(w2 / h2) - torch.atan(w1 / h1), 2)
                with torch.no_grad():
                    alpha = v / (1 - iou + v)   ### should add + 1e-16 to avoid alpha = NAN.
                return iou - (rho2 / c2 + v * alpha)  # CIoU
```

## To Reproduce (REQUIRED)

it's hard to reproduce, I encounter it when I was trying some new target assigning  methods..

Output:
alpha = Nan.

## Expected behavior
alpha  be a normal value between 0 -  1

## Environment

 - OS: [e.g. Ubuntu]
 - GPU [e.g. 2080 Ti]

## Additional context
it's hard to reproduce, I encounter it when I was trying some new target assigning  methods..

**Comment by glenn-jocher** [comment]
@AlexWang1900 ah, thanks for the bug report! It looks like c2 is already protected, so then alpha may be the only unprotected divide as you say. Yes we should add 1e-16 here. Would you like to submit a PR for this or I can include it in the next commit?

**Comment by AlexWang1900** [comment]
I will summit a PR thanks!😀



---Original---

**Comment by glenn-jocher** [comment]
Issue resolved, removing TODO.
