### ISSUE TITLE
How to crop the detected object after training using YOLO?

### ISSUE THREAD

**Issue by samahwaleed** [ultralytics/yolov5#5412]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am using YOLO for model training. I used save-txt to save the results in txt files. I want to crop the detected object and get the pixel values for each detected object from the txt file. The txt file has labeled, bbox coordinates and score.

Any help would be highly appreciated!

**Comment by glenn-jocher** [comment]
@samahwaleed 👋 Hello! Thanks for asking about **cropping results** with YOLOv5 🚀.  Cropping bounding box detections can be useful for training classification models on box contents for example. This feature was added in PR https://github.com/ultralytics/yolov5/pull/2827. You can crop detections using either detect.py or YOLOv5 PyTorch Hub:

## detect.py
Crops will be saved under `runs/detect/exp/crops`, with a directory for each class detected.
```bash
python detect.py --save-crop
```
<img width="450" alt="Original" src="https://user-images.githubusercontent.com/26833433/139577918-65cc8f5d-741d-4a88-8753-0154013c624d.jpg">

<img width="1067" alt="Crop" src="https://user-images.githubusercontent.com/26833433/139577896-aa26b07c-466d-4057-9bfe-b01b56007587.png">

## YOLOv5 PyTorch Hub
Crops will be saved under `runs/detect/exp/crops` if `save=True`, and also returned as a dictionary with crops as numpy arrays.
```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, custom

# Images
img = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, PIL, OpenCV, numpy, list

# Inference
results = model(img)

# Results
crops = results.crop(save=True)  # or .show(), .save(), .print(), .pandas(), etc.
```

Good luck and let us know if you have any other questions!

**Comment by samahwaleed** [comment]
Thank you. but I want to crop the images using the results saved in txt file. 
This is my code:

```
`import glob
import cv2 as cv
import matplotlib.pyplot as plt
import PIL
import numpy as np


path = glob.glob("/content/yolov5/runs/detect/exp/FrameVid1_185.JPG")


 for img in path:
    
     imgs = PIL.Image.open(img).convert('RGB')
     image_width, image_height = imgs.size
     imgArrays = np.array(imgs)
     X = (df.iloc[0:, 1]*image_width).astype(int)
     Y = (df.iloc[0:, 2]*image_height).astype(int)
     W = (df.iloc[0:, 3]*image_width).astype(int)
     H = (df.iloc[0:, 4]*image_height).astype(int)
     
     cropped_image = np.zeros(imgs.size)
     for i in range(len(X)):
       cropped_image[Y[i]: H[i], X[i]: W[i]] = imgArrays[Y[i]: H[i], X[i]: W[i]]
      
     cv2.imshow('Cropped Image', cropped_image)`
```

I got this error,

> ValueError: could not broadcast input array from shape (0,0,3) into shape (0,0)

**Comment by glenn-jocher** [comment]
@samahwaleed crops are produced by the same text file predictions, but sure you can write your own script to do this as well.

**Comment by samahwaleed** [comment]
This is my code.

  ```
path = glob.glob("/content/yolov5/runs/detect/exp/*.jpg")
   cropped_images =[]

  for img in path:
    
     imgs = PIL.Image.open(img).convert('RGB')
     image_width, image_height = imgs.size
     imgArrays = np.array(imgs)

     #image coordinates:
     #(left, right, top, bottom) = (xmin * im_width, xmax * im_width, ymin * im_height, ymax * im_height)
    
     X = (x_min*image_width)          #left
     Y = (y_min*image_height)         #top
     W = (x_max*image_width)          #right
     H = (y_max*image_height)         #bottom
     cropped_image = np.zeros((image_height, image_width, 3))
        
     for i in range(len(X)):
              x1, y1, w, h = X[i], Y[i], W[i], H[i]
              x_start = int(torch.round(x1 - (w/2)))
              y_start = int(torch.round(y1 - (h/2)))
              x_end = int(torch.round(x_start + w))
              y_end = int(torch.round(y_start + h))
              
              temp = imgArrays[y_start: y_end, x_start: x_end]
              cropped_images = temp
```

**Comment by Raymon360** [comment]
is there a method to cut-save multiple files in multiple folders?

**Comment by glenn-jocher** [comment]
@Raymon360 👋 Hello! Thanks for asking about **cropping results** with YOLOv5 🚀.  Cropping bounding box detections can be useful for training classification models on box contents for example. This feature was added in PR https://github.com/ultralytics/yolov5/pull/2827. You can crop detections using either detect.py or YOLOv5 PyTorch Hub:

## detect.py
Crops will be saved under `runs/detect/exp/crops`, with a directory for each class detected.
```bash
python detect.py --save-crop
```
<img width="450" alt="Original" src="https://user-images.githubusercontent.com/26833433/139577918-65cc8f5d-741d-4a88-8753-0154013c624d.jpg">

<img width="1067" alt="Crop" src="https://user-images.githubusercontent.com/26833433/139577896-aa26b07c-466d-4057-9bfe-b01b56007587.png">

## YOLOv5 PyTorch Hub
Crops will be saved under `runs/detect/exp/crops` if `save=True`, and also returned as a dictionary with crops as numpy arrays.
```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, custom

# Images
img = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, PIL, OpenCV, numpy, list

# Inference
results = model(img)

# Results
crops = results.crop(save=True)  # or .show(), .save(), .print(), .pandas(), etc.
```

Good luck 🍀 and let us know if you have any other questions!

**Comment by Arsmart1** [comment]
can we only detect 'person' class and only save this class? Thank you!!!

**Comment by Laughing-q** [comment]
@Arsmart1 
```python
python detect.py --source data/images --weights yolov5s.pt --classes 0
```
this might help you.

**Comment by JJ-McClure** [comment]
I just want to chime in that cropping the image using the coordinates from the txt-file _does not_ give the same image as using the save-crops function. The save-crops function result in a slightly bigger crop compared to just using the coordinates. This can be a very important distinction for small detections/images and sequential yolo detections

**Comment by varunpusarla** [comment]
Is there a better of way of doing this in YOLOv8 ?

**Comment by glenn-jocher** [comment]
@varunpusarla hello, 

YOLOv8 is not an existing version of YOLO. The latest version is YOLOv5, which is currently maintained by Ultralytics. With YOLOv5, you can detect objects in images and videos using pre-trained models or custom trained models with your own dataset. 

If you have any specific questions about implementation or functionality with YOLOv5, feel free to ask and we'll be happy to help. 

Best regards.

**Comment by NawoyaSarah** [comment]
@glenn-jocher how can i maintain scale during cropping? because the generated crops vary in dimensions, yet i wound want to use the generated crops to measure object size. hence the dimensions need to be same scale

**Comment by glenn-jocher** [comment]
@Sarai256 you can maintain the scale during cropping by calculating the width and height of the crop based on a fixed aspect ratio or a fixed scale factor. For example, if you want to maintain a fixed aspect ratio (e.g., 1:1) during cropping, you can calculate the width and height of the crop based on the longer side of the bounding box. Alternatively, if you want to maintain a fixed scale factor (e.g., 0.5), you can scale the width and height of the crop based on the original width and height of the image. By applying these calculations, you can ensure that the dimensions of the generated crops are in the same scale as the original objects.

**Comment by NawoyaSarah** [comment]
@glenn-jocher , thank you for the reply. however I am not sure to which part of the code i should include the scale factor, 
Example: python detect.py --save-crop..
Do i include the scale in that command? I am a beginner

**Comment by glenn-jocher** [comment]
@Sarai256 Thank you for reaching out! In order to maintain a specific scale during cropping, you would need to modify the code in the `detect.py` file. 

The command `python detect.py --save-crop` does not have a built-in option to specify a scale factor. To achieve the desired scale, you would need to make changes in the code itself.

One way to implement scaling is by modifying the cropping logic in the `detect.py` file. Specifically, you can calculate the width and height of the crop based on the scale factor you want to maintain. You can then adjust the cropping coordinates accordingly.

If you are a beginner, I would recommend going through the `detect.py` code and understanding how the cropping is currently implemented. From there, you can make the necessary modifications to introduce the desired scaling functionality.

Feel free to ask any further questions if you need any clarification or assistance with the code. Happy coding!
