### ISSUE TITLE
About TTA

### ISSUE THREAD

**Issue by ptran1203** [ultralytics/yolov5#5414]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I saw in the code TTA includes `1x` + `0.83x (flip lr)` + `0.67x`, so there are 3 times TTA, but I wonder why at 0.83 scale you only run hflip version of the image, why don't run both original image + hflip image?

**Comment by glenn-jocher** [comment]
@ptran1203 yes you can run additional TTA augmentations. The current augmentations are in place as a good compromise between speed and accuracy (determined by empirical experimentation), but you're free to add additional augmentations of your own, we made the structure easy to modify for that purpose.
