### ISSUE TITLE
What should I change if I want to use the DIOU-NMS,Soft-NMS. eg?

### ISSUE THREAD

**Issue by SpongeBab** [ultralytics/yolov5#5415]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I saw you use nms of torchvision. 
`i = torchvision.ops.nms(boxes, scores, iou_thres)  # NMS`
In my experiments, I found that the setting of the threshold has a big impact on the correct display of the results. Because the objects in my data set are dense, there are occlusions and other situations. What should I do if I want to change to DIOU-NMS or other NMS?

### Additional

I tried but failed.

------
Solved.

**Comment by nouranyoussry** [comment]
How have you solved it please?
I want to use soft-NMS

**Comment by rukshankr** [comment]
Please tell how you solved this

**Comment by glenn-jocher** [comment]
@rukshankr to use DIOU-NMS, you can replace the `nms` function with `diou` function in `utils/general.py`. Here is an example:

```python
from torchvision.ops import boxes as box_ops

iou_threshold = 0.45  # NMS threshold for IOU
diou_threshold = None  # NMS threshold for DIOU

# boxes: tensor[N, 4], scores: tensor[N], returns indices of keeped boxes
i = box_ops.nms(boxes, scores, iou_threshold)
j = box_ops.box_iou(boxes[i], boxes) >= iou_threshold
if diou_threshold is not None:
    # calculate DIoU
    dious = box_ops.box_diou(boxes, boxes[i][j], uv_format=True)
    j &= dious < diou_threshold
keep = i[j]
```

Similarly, you can replace `iou` with `soft_nms` for using Soft-NMS. Remember to also import `box_soft_nms` from `torchvision.ops.boxes` before using it.

Let me know if you have further questions or issues!

**Comment by rukshankr** [comment]
`ImportError: cannot import name 'box_soft_nms' from 'torchvision.ops.boxes' (/usr/local/lib/python3.9/dist-packages/torchvision/ops/boxes.py)`
`ImportError: cannot import name 'box_diou' from 'torchvision.ops.boxes' (/usr/local/lib/python3.9/dist-packages/torchvision/ops/boxes.py)`
It seems that these two implementations don't exist? 
What am I doing wrong here?

**Comment by glenn-jocher** [comment]
@rukshankr i apologize for the confusion. The `box_soft_nms` and `box_diou` functions are not yet available in the stable release of PyTorch (as of version 1.9.0). 

However, they are available in the nightly builds of PyTorch starting from version 1.10.0.dev20211104. You can install the latest nightly version of PyTorch via pip as `pip install --pre torch -f https://download.pytorch.org/whl/nightly/cu111/torch_nightly.html`.

Alternatively, you can try using an implementation of Soft NMS and DIOU NMS from a different package such as [mmdetection](https://github.com/open-mmlab/mmdetection). The mmdetection implementation is not identical to the function names mentioned earlier, but the effect should be the same. You can try:

```python
from mmdet.core import multiclass_nms, bbox_overlaps

iou_threshold = 0.45  # NMS threshold for IOU
diou_threshold = None  # NMS threshold for DIOU
soft_nms_threshold = None  # Soft NMS threshold

# boxes: tensor[N, 4], scores: tensor[N], returns indices of keeped boxes
i = multiclass_nms(boxes, scores, iou_threshold, score_thr=soft_nms_threshold)
j = bbox_overlaps(boxes[i], boxes) >= iou_threshold
if diou_threshold is not None:
    # calculate DIoU
    from mmdet.core.bbox import bbox_distance
    dious = bbox_distance(boxes, boxes[i][j], metric='diou', cpu=True)
    j &= dious < diou_threshold
keep = i[j]
```

Again, I apologize for any confusion caused by my previous message.

**Comment by rukshankr** [comment]
Ok I got the command working but it seems that the newer nightly version also does not have `box_diou` and `box_soft_nms`. Is there a way for me to `!pip` the `torch==1.10.0.dev20211104` version? `!pip install torch==1.10.0.dev20211104` didn't work.

![image](https://user-images.githubusercontent.com/58694077/230908353-2e0365cf-4641-4ede-b316-1a51bfd507f8.png)

I ran into some problems with the mmdetection also but it seems like my only choice right now so I'll try it again.

**Comment by glenn-jocher** [comment]
@rukshankr I apologize for the confusion again. It seems like `box_soft_nms` and `box_diou` are not yet available even in the latest nightly build of PyTorch. Also, it seems that you have already tried installing PyTorch 1.10.0.dev20211104, which is the correct way to install the latest nightly build. 

For the moment, the best way to use Soft-NMS and DIOU-NMS is to use a different package such as mmdetection. I’m sorry that you ran into some problems with mmdetection as well. If you provide more information about the problems you encountered, I would be happy to help you solve them.

**Comment by rukshankr** [comment]
Well it is saying that there is no such module called `mmdet.core`. I still couldn't find out where the nms code is stored in mmdet version 3.0.0.
`ModuleNotFoundError: No module named 'mmdet.core'`

The Issues section of their Gitub repo says they import nms impls from mmcv, so I directly loaded `soft_nms` from mmcv. 
That seems to work.

The mmcv version they recommend for Google Colab is `!mim install "mmcv>=2.0.0,<2.1.0"` which does not seem to have diou_nms. I still could not find diou_nms in mmcv but maybe it is in a newer version?

However, I found these two functions in `/usr/local/lib/python3.9/dist-packages/torchvision/ops/boxes.py`. Would these two functions be sufficient to write up a code to use DIoU NMS?

def distance_box_iou(boxes1: Tensor, boxes2: Tensor, eps: float = 1e-7) -> Tensor:

    Return distance intersection-over-union (Jaccard index) between two sets of boxes.

    Both sets of boxes are expected to be in "(x1, y1, x2, y2)" format with
    "0 <= x1 < x2" and "0 <= y1 < y2".

    Args:
        boxes1 (Tensor[N, 4]): first set of boxes
        boxes2 (Tensor[M, 4]): second set of boxes
        eps (float, optional): small number to prevent division by zero. Default: 1e-7

    Returns:
        Tensor[N, M]: the NxM matrix containing the pairwise distance IoU values
        for every element in boxes1 and boxes2
    """
    if not torch.jit.is_scripting() and not torch.jit.is_tracing():
        _log_api_usage_once(distance_box_iou)

    boxes1 = _upcast(boxes1)
    boxes2 = _upcast(boxes2)
    diou, _ = _box_diou_iou(boxes1, boxes2, eps=eps)
    return diou

def _box_diou_iou(boxes1: Tensor, boxes2: Tensor, eps: float = 1e-7) -> Tuple[Tensor, Tensor]:

    iou = box_iou(boxes1, boxes2)
    lti = torch.min(boxes1[:, None, :2], boxes2[:, :2])
    rbi = torch.max(boxes1[:, None, 2:], boxes2[:, 2:])
    whi = _upcast(rbi - lti).clamp(min=0)  # [N,M,2]
    diagonal_distance_squared = (whi[:, :, 0] ** 2) + (whi[:, :, 1] ** 2) + eps
    # centers of boxes
    x_p = (boxes1[:, 0] + boxes1[:, 2]) / 2
    y_p = (boxes1[:, 1] + boxes1[:, 3]) / 2
    x_g = (boxes2[:, 0] + boxes2[:, 2]) / 2
    y_g = (boxes2[:, 1] + boxes2[:, 3]) / 2
    # The distance between boxes' centers squared.
    centers_distance_squared = (_upcast((x_p[:, None] - x_g[None, :])) ** 2) + (
        _upcast((y_p[:, None] - y_g[None, :])) ** 2
    )
    # The distance IoU is the IoU penalized by a normalized
    # distance between boxes' centers squared.
    return iou - (centers_distance_squared / diagonal_distance_squared), iou

**Comment by glenn-jocher** [comment]
@rukshankr Yes, the `distance_box_iou` and `_box_diou_iou` functions from `torchvision.ops.boxes` can be used to implement DIoU NMS. Here is how you can use them:

```python
from torchvision.ops import boxes as box_ops

iou_threshold = 0.45  # NMS threshold for IOU
diou_threshold = 0.5  # NMS threshold for DIoU

# boxes: tensor[N, 4], scores: tensor[N], returns indices of keeped boxes
i = box_ops.nms(boxes, scores, iou_threshold)
j = box_ops.box_iou(boxes[i], boxes) >= iou_threshold
if diou_threshold is not None:
    # calculate DIoU
    from torchvision.ops import box_iou
    from torchvision.ops.boxes import distance_box_iou

    diou = distance_box_iou(boxes, boxes[i][j])
    j &= diou < diou_threshold
keep = i[j]
```

Note that `distance_box_iou` calculates the DIoU between two sets of boxes whereas `_box_diou_iou` calculates both the DIoU and IoU values. Also, the `distance_box_iou` function requires the boxes to be provided in the format `(x1, y1, x2, y2)` where `0 <= x1 < x2` and `0 <= y1 < y2`.

**Comment by rukshankr** [comment]
Sorry for the delayed response.

I tried the above code, by changing the last line to `i = i[j]` as there's no `keep` variable in `general.py`. 
```
        # Batched NMS
        c = x[:, 5:6] * (0 if agnostic else max_wh)  # classes
        boxes, scores = x[:, :4] + c, x[:, 4]  # boxes (offset by class), scores
        #i = torchvision.ops.nms(boxes, scores, iou_thres)  # NMS
        i = box_ops.nms(boxes, scores, iou_thres)
        j = box_ops.box_iou(boxes[i], boxes) >= iou_thres
        if diou_threshold is not None:
          # calculate DIoU
          from torchvision.ops import box_iou
          from torchvision.ops.boxes import distance_box_iou

          diou = distance_box_iou(boxes, boxes[i][j])
          j &= diou < diou_threshold
        i = i[j]
        i = i[:max_det]  # limit detections
```

However, I got this error: `IndexError: The shape of the mask [3, 24] at index 1 does not match the shape of the indexed tensor [3, 4] at index 1`
![image](https://user-images.githubusercontent.com/58694077/231837810-bc962ae1-bcf6-4438-a835-e8921a9ef39a.png)

So by your previous response I'm guessing that there's a correction of the format that needs to be done?

**Comment by rukshankr** [comment]
Since the above method did not work, I implemented my own DIoU-NMS code with the help of ChatGPT. It is as follows:
```python
import torch
from torchvision.ops.boxes import box_iou, distance_box_iou

def diou_nms(boxes, scores, iou_threshold=0.5, diou_threshold=0.5):
    """
    Performs dIoU-NMS on the input boxes.
    Args:
        boxes (Tensor[N, 4]): input boxes in (x1, y1, x2, y2) format.
        scores (Tensor[N]): input box scores.
        iou_threshold (float): IoU threshold for regular NMS.
        diou_threshold (float): dIoU threshold for dIoU-NMS.
    Returns:
        indices (Tensor[K]): indices of the boxes to keep after NMS.
    """
    # Sort boxes by scores in descending order
    sorted_idx = torch.argsort(scores, descending=True)

    # Initialize list of indices to keep
    keep = []

    while len(sorted_idx) > 0:
        # Pick the box with the highest score
        idx = sorted_idx[0]
        keep.append(idx)

        # Compute IoU between the picked box and the remaining boxes
        ious = box_iou(boxes[idx].unsqueeze(0), boxes[sorted_idx])

        # Compute dIoU between the picked box and the remaining boxes
        dious = distance_box_iou(boxes[idx].unsqueeze(0), boxes[sorted_idx])

        # Find the indices of the boxes with IoU greater than the threshold
        iou_mask = ious.squeeze(0) > iou_threshold

        # Find the indices of the boxes with dIoU greater than the threshold
        diou_mask = dious.squeeze(0) > diou_threshold

        # Apply NMS based on both IoU and dIoU
        mask = iou_mask & diou_mask

        # Remove the indices of the boxes that overlap too much with the picked box
        sorted_idx = sorted_idx[~mask]

    # Return the list of indices to keep
    return torch.tensor(keep, dtype=torch.long)
```
I post it here for the ease of another newbie like me.
Thank you for your kind responses

**Comment by glenn-jocher** [comment]
@rukshankr thank you for sharing your implementation of DIoU-NMS. This is indeed a good alternative for those who may encounter problems with the `distance_box_iou` and `_box_diou_iou` functions from `torchvision.ops.boxes`. I hope that your implementation would work well for your needs. If you have any further questions, feel free to ask.
