### ISSUE TITLE
How can I get mAp informations ?

### ISSUE THREAD

**Issue by sungchi64** [ultralytics/yolov5#5417]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I have two questions:
1. I have trained my own data sets with the latest program, how can I use the trained weights to test my testing datas (need to put the label path) and get the mAp?

2. I use detect.py in my testing images, and the pictures in the output folder only get the prediction box, category and a number. I want to know what the number means (because I didn't give a label)

I really need to know how to calculate mAp, hoping to teach me which part of the program should be changed to get the result, thank you!

**Comment by glenn-jocher** [comment]
@sungchi64 predictions display class name and detection confidence.

To obtain mAP values on labelled data use val.py and point to the split you are interested in:
```bash
python val.py --task val
python val.py --task train
python val.py --task test
```

**Comment by sungchi64** [comment]
@glenn-jocher Thank you very much!
I'll try to use it !!

**Comment by sannicosan** [comment]
I want to get the mAP for a custom model trained on a specific image I have locally @glenn-jocher @sungchi64 
Can I know how this can be done?

**Comment by sungchi64** [comment]
@sannicosan You can try `python val.py --task test`  
and change the test datasets  what you want to get the mAP.
