### ISSUE TITLE
best.pt not saved when it is from the last epoch

### ISSUE THREAD

**Issue by AlexWang1900** [ultralytics/yolov5#542]
Before submitting a bug report, please be aware that your issue **must be reproducible** with all of the following, otherwise it is non-actionable, and we can not help you:
 - **Current repo**: run `git fetch && git status -uno` to check and `git pull` to update repo
 - **Common dataset**: coco.yaml or coco128.yaml
 - **Common environment**: Colab, Google Cloud, or Docker image. See https://github.com/ultralytics/yolov5#reproduce-our-environment
 
If this is a custom dataset/training question you **must include** your `train*.jpg`, `test*.jpg` and `results.png` figures, or we can not help you. You can generate these with `utils.plot_results()`.

## 🐛 Bug
in train.py line: 390
               ```
 if (best_fitness == fi) and not final_epoch:  ### 
                    torch.save(ckpt, best)
                del ckpt
```
when the last epoch happens to have a best fitness,  it wouldn't save a best.pt,
the code outside the train.py cannot judge which .pt  is the best.  

## To Reproduce (REQUIRED)

train one epoch from an interrupted traning's  last.pt , or the best result happens to be in the last epoch.

Output:
"couldn't find best.pt" or load a wrong best.pt. (should be last.pt in this situation)

## Expected behavior
when training compeletes, one can load best.pt as it is the best result.

## Environment

 - OS: [e.g. Ubuntu]
 - GPU [e.g. 2080 Ti]

**Comment by glenn-jocher** [comment]
@AlexWang1900 yes, good point! I do believe you've found a bug. Would you like to submit a PR or should I include this in the next push?

**Comment by AlexWang1900** [comment]
I'd Like to summit a PR!

---Original---

**Comment by glenn-jocher** [comment]
Issue resolved, removing TODO.
