### ISSUE TITLE
sample a local video to detect

### ISSUE THREAD

**Issue by yang-leon996** [ultralytics/yolov5#5420]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Now I want to sample a video at several frames and detect these frames, not detect all frames of this video. What should I modify in  the class LoadImages?

**Comment by glenn-jocher** [comment]
@yang-leon996 you can modify the cv2 video parsing code here to skip frames:
https://github.com/ultralytics/yolov5/blob/5d4258fac5e6ceaa9c897f841cb737c56717a996/utils/datasets.py#L199-L211

**Comment by yang-leon996** [comment]
@glenn-jocher soorry, I have a try, but it failed, could you help me how to skip frames in detail? Thank you!

**Comment by glenn-jocher** [comment]
@yang-leon996 every self.cap.read() loads a frame. See cv2 documentation for more information.
