### ISSUE TITLE
How to off the augmentation function???

### ISSUE THREAD

**Issue by LEEGILJUN** [ultralytics/yolov5#5421]
Hello

I'd like to experiment with the augmentation function turned off.

Also, I want to experiment with the augmente function turned on and the mosaic function off.

This is because I want to know the performance difference between the use of the augmentation method and the mosaic in the data I use.

I know to control hyp in hyp.yaml. if I changed "mosaic: 1.0  # image mosaic (probability)" to "mosaic: 0.0  # image mosaic (probability)". it is turned off the mosaic function??????

or

like below photo, if i change this function augment=True -> augment=False, it is turned off the augmentation???
 
![image](https://user-images.githubusercontent.com/23168829/139608427-27716897-949c-4bba-866a-c73f26b208cd.png)

Thanks

**Comment by glenn-jocher** [comment]
@LEEGILJUN 👋 Hello! Thanks for asking about **image augmentation**. YOLOv5 🚀 applies online imagespace and colorspace augmentations in the trainloader (but not the testloader) to present a new and unique augmented [Mosaic](https://github.com/ultralytics/yolov5/blob/90b7895d652c3bd3d361b2d6e9aee900fd67f5f7/utils/datasets.py#L678-L732) (original image + 3 random images) each time an image is loaded for training. **Images are never presented twice in the same way**.

![YOLOv5 augmentation](https://user-images.githubusercontent.com/26833433/120995721-f3cfed00-c785-11eb-8ee2-b6ef2fa205e8.jpg)

The hyperparameters used to define these augmentations are in your hyperparameter file (default `data/hyp.scratch.yaml`) defined when training:
```
python train.py --hyp hyp.scratch.yaml
```
https://github.com/ultralytics/yolov5/blob/90b7895d652c3bd3d361b2d6e9aee900fd67f5f7/data/hyp.scratch.yaml#L1-L33

You can view the effect of your augmentation policy in your train_batch*.jpg images once training starts. These images will be in your train logging directory, typically `yolov5/runs/train/exp`:

`train_batch0.jpg` shows train batch 0 mosaics and labels:  
> <img src="https://user-images.githubusercontent.com/26833433/131255960-b536647f-7c61-4f60-bbc5-cb2544d71b2a.jpg" width="700">

Good luck and let us know if you have any other questions!
