### ISSUE TITLE
Pretrained model on ImageNet

### ISSUE THREAD

**Issue by fxcdl** [ultralytics/yolov5#5422]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi，thanks you for your code, do you hava a pre-trained model on ImageNet? I want to use it as my pre-trained model.

**Comment by glenn-jocher** [comment]
@fxcdl all of our models are trained from scratch on COCO. We do not have any ImageNet trained models.
