### ISSUE TITLE
Unrecognized arguments in detect.py (CCTV Source)

### ISSUE THREAD

**Issue by PIjarihd** [ultralytics/yolov5#5423]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am using YOLOv5 in jetson tx2 board. When I try to detect objects from livestream, I get the error: **detect.py:error: unrecognized arguments: --source rtsp://admin:password@IPAddress**
I used the folloeing command:
`python3 detect.py --source rtsp://admin:password@IPAddress --weights best.pt --conf 0.25`

I am not sure how to solve this.

**Comment by glenn-jocher** [comment]
@dhirajip source addresses may need to be quote enclose `--source 'address'`

**Comment by PIjarihd** [comment]
> @dhirajip source addresses may need to be quote enclose `--source 'address'`

There was a typo. I solved it. Thanks for your response.
