### ISSUE TITLE
How do I cite this repo on my paper?

### ISSUE THREAD

**Issue by jpsecundino** [ultralytics/yolov5#5424]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I writing a paper and I wold like to cite this repo. How can I do this?

**Comment by glenn-jocher** [comment]
@jpsecundino we are working on an arxiv submission by end of year, in the meantime you can use our DOI here: 
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.5563715.svg)](https://doi.org/10.5281/zenodo.5563715)

```bibtex
@software{glenn_jocher_2021_5563715,
  author       = {Glenn Jocher et. al.},
  title        = {{ultralytics/yolov5: v6.0 - YOLOv5n 'Nano' models, 
                   Roboflow integration, TensorFlow export, OpenCV
                   DNN support}},
  month        = oct,
  year         = 2021,
  publisher    = {Zenodo},
  version      = {v6.0},
  doi          = {10.5281/zenodo.5563715},
  url          = {https://doi.org/10.5281/zenodo.5563715}
}
```
