### ISSUE TITLE
how to run onnx model in opencv with C++ Code

### ISSUE THREAD

**Issue by futureflsl** [ultralytics/yolov5#5425]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

I export yolov5s.pt to yolov5s.onnx.the yolov5-6.0 version,I fllow the issue:https://github.com/ultralytics/yolov5/issues/5378,But result is bad.what is the problem

#include<  iostream>
#include <    string>
#include<opencv2/opencv.hpp>
#include <opencv2/dnn.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/highgui.hpp>
#include<vector>
using namespace cv;
using namespace std;
using namespace dnn;
int main()
{
    float confThreshold  = 0.25f;
   float nmsThreshold = 0.45f;
   int blobSize=640;
   auto net = cv::dnn::readNetFromONNX("/home/fut/ai/yolov5-6.0/pre-model/yolov5s.onnx");
   cv::Mat frame = cv::imread("../test.jpg");
    cv::Mat blob;
    cv::dnn::blobFromImage(frame, blob, 1.0/255.0, cv::Size(blobSize, blobSize), cv::Scalar(0, 0, 0), true, false);
    net.setInput(blob);

    cv::Mat OUT = net.forward();
    cv::Mat detectionMat(OUT.size[1], OUT.size[2], CV_32F, OUT.ptr<float>());
    std::vector<int> classIds;
    std::vector<float> confidences;
    std::vector<cv::Rect> boxes;

    float* data = (float*)detectionMat.data;
    for (int i = 0; i < detectionMat.rows; i++, data += detectionMat.cols)
    {
        cv::Mat class_scores = detectionMat.row(i).colRange(5, detectionMat.cols);
        cv::Point classIdPoint;
        double max_confidence;
        minMaxLoc(class_scores, 0, &max_confidence, 0, &classIdPoint);

        float conf = max_confidence * data[4];
        if (conf > confThreshold)
        {
            int centerX = (int)(data[0] * frame.cols / blobSize);
            int centerY = (int)(data[1] * frame.rows / blobSize);
            int width = (int)(data[2] * frame.cols / blobSize);
            int height = (int)(data[3] * frame.rows / blobSize);
            int left = centerX - width / 2;
            int top = centerY - height / 2;

            classIds.push_back(classIdPoint.x);
            confidences.push_back(conf);
            boxes.push_back(cv::Rect(left, top, width, height));
        }
    }

vector<int> indices;
NMSBoxes(boxes, confidences, confThreshold, nmsThreshold, indices);

for (int i=0;i<indices.size();i++)
{
   cv::rectangle(frame,boxes[i],cv::Scalar(255,0,0),2,8,0);
    stringstream ss1,ss2;  
    string str1, str2;  
    ss1 << classIds[i];    
    ss1 >> str1;  
    ss2 << confidences[i];
    ss2 >> str2;
   cv::putText(frame,str1+","+str2,cv::Point(boxes[i].x,boxes[i].y),cv::FONT_HERSHEY_SIMPLEX,1.0,cv::Scalar(0,255,0),2);
}
cv::imshow("result",frame);
cv::waitKey(0);
cv::destroyAllWindows();

    return 0;
}

**Comment by PauloMendes33** [comment]
I was able to load the model with OpenCV4.5.4 however I am unable to make detections.

**Comment by PauloMendes33** [comment]
@futureflsl
