### ISSUE TITLE
Serverless function for YOLOv5

### ISSUE THREAD

**Issue by aseprohman** [ultralytics/yolov5#5427]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hello @glenn-jocher et all,

Has anyone tried to install the yolov5 framework into the serverless function in the CVAT (Computer Vision Annotation Tool) tools? I want to use the automatic annotation feature in CVAT with custom DL model. 
maybe there is a tutorial I can learn for this case ? thanks a lot

**Comment by glenn-jocher** [comment]
@aseprohman interesting question. I don't experience with this myself but perhaps someone in the community does.

**Comment by aseprohman** [comment]
I'm still trying to install, here is documentation link from CVAT website : 

https://openvinotoolkit.github.io/cvat/docs/administration/advanced/installation_automatic_annotation
 
If it is successfully implemented, I think this automation tool can make a lot of annotation jobs more easier and less tedious :)

**Comment by aseprohman** [comment]
![Screenshot from 2021-11-02 16-59-44](https://user-images.githubusercontent.com/18188641/139825975-0ce5c6a7-3fb7-44e5-86c1-6d2d16328cbb.png)

Hello @glenn-jocher et all ,

I have tried to deploy a serverless function example that already run from openvino with yolov3 model for automatic annotations in cvat. The response data provided looks like in the image on the right terminal console, while the left terminal console is the "xywh" format from yolov5. do you have any idea to make the "xywh" value to "int" value like in the right terminal in the serverless function yolov3 ? regards

**Comment by glenn-jocher** [comment]
@aseprohman well I'd assume some coordinate transformations are required. You can see examples of coordinate transformations and operations in general.py:
https://github.com/ultralytics/yolov5/blob/19c8760caa70f4d04d3fb974d797f9d922bf6eb8/utils/general.py#L512-L614
