### ISSUE TITLE
The old version model configuration file error caused by the new version.

### ISSUE THREAD

**Issue by Lornatang** [ultralytics/yolov5#543]
Before submitting a bug report, please be aware that your issue **must be reproducible** with all of the following, otherwise it is non-actionable, and we can not help you:
 - **Current repo**: run `git fetch && git status -uno` to check and `git pull` to update repo
 - **Common dataset**: coco.yaml or coco128.yaml
 - **Common environment**: Colab, Google Cloud, or Docker image. See https://github.com/ultralytics/yolov5#reproduce-our-environment
 
If this is a custom dataset/training question you **must include** your `train*.jpg`, `test*.jpg` and `results.png` figures, or we can not help you. You can generate these with `utils.plot_results()`.

## 🐛 Bug
From models/hub/*.yaml configure file all Invalidation. I think the reason for this is that you no longer output the `nn.Conv2d` function.

## To Reproduce (REQUIRED)

Input:
```
# command
python train.py --cfg models/hub/yolov3-spp.yaml --data data/coco.yaml
```

Output:
```
# report error message
Traceback (most recent call last):
  File "train.py", line 469, in <module>
    train(hyp, tb_writer, opt, device)
    ......
IndexError: index 0 is out of range
```

## Expected behavior
Run this program normally.

## Environment
 - OS: [Ubuntu18.04]
 - GPU [2080 Ti]

## Additional context
I have read your model configuration file, I think the new version of the configuration file should be filled out in accordance with it, I am also ready to submit a PR, looking forward to your reply.

**yolov3-spp.yaml**
```
# parameters
nc: 80  # number of classes
depth_multiple: 1.0  # model depth multiple
width_multiple: 1.0  # layer channel multiple

# anchors
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

# darknet53 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [32, 3, 1]],  # 0
   [-1, 1, Conv, [64, 3, 2]],  # 1-P1/2
   [-1, 1, Bottleneck, [64]],
   [-1, 1, Conv, [128, 3, 2]],  # 3-P2/4
   [-1, 2, Bottleneck, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 5-P3/8
   [-1, 8, Bottleneck, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 7-P4/16
   [-1, 8, Bottleneck, [512]],
   [-1, 1, Conv, [1024, 3, 2]], # 9-P5/32
   [-1, 4, Bottleneck, [1024]],  # 10
  ]

# YOLOv3-SPP head
head:
  [[-1, 1, Bottleneck, [1024, False]],
   [-1, 1, SPP, [512, [5, 9, 13]]],
   [-1, 1, Conv, [1024, 3, 1]],
   [-1, 1, Conv, [512, 1, 1]],
   [-1, 1, Conv, [1024, 3, 1]],  # 15

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 8], 1, Concat, [1]],  # cat backbone P4
   [-1, 1, Bottleneck, [512, False]],
   [-1, 1, Bottleneck, [512, False]],
   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, Conv, [512, 3, 1]],  # 22

   [-1, 1, Conv, [128, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P3
   [-1, 1, Bottleneck, [256, False]],
   [-1, 2, Bottleneck, [256, False]],  # 27

   [[27, 22, 15], 1, Detect, [nc, anchors]],   # Detect(P3, P4, P5)
  ]
```

**Comment by glenn-jocher** [comment]
@Lornatang thanks for the bug report. Yes, you are correct the archived models in the hub/ folder need updating to work correctly with the new yolo.py parser. The main change in v2.0 is that the output nn.Conv2d layers are all integrated into the final Detect layer. 

Actually yes, it looks like your updated yaml file here is correct! Can you submit a PR with it?

**Comment by PiyalGeorge** [comment]
Hi @glenn-jocher , will this new version of yolov5 improve the accuracy or inference time? OR how this new update reflects in the   detection output ?

**Comment by lucasjinreal** [comment]
@Lornatang Will u also update yolov5s yolov5m yolov5l model config in v1 version? It's all broken now.

**Comment by Lornatang** [comment]
@jinfagang It's late at night now, I'll take a look for you tomorrow. Can you share your first code with me? I can send you the correct YAML file tomorrow.

**Comment by glenn-jocher** [comment]
@jinfagang @Lornatang version 1.0 will not be updated. v2.0 introduced breaking changes into the model building process, so previous yamls and pt files will not work with the current. 

You can clone the last v1.0 commit if you want to here:
https://github.com/ultralytics/yolov5/releases/tag/v2.0

**Comment by glenn-jocher** [comment]
@PiyalGeorge yes v2.0 improves accuracy of larger models in particular. 5x increased from 48.4 to 49.0. Speed is the same.
