### ISSUE TITLE
Onnx to Tensorflow with onnx-tensorflow and export_graph function

### ISSUE THREAD

**Issue by AlexisPapaioannou** [ultralytics/yolov5#5431]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is it possible to convert the Onnx file to a TensorFlow file (pb) using the export_graph function from the onnx-tensorflow repository (https://github.com/onnx/onnx-tensorflow)?

**Comment by AlexisPapaioannou** [comment]
I  used the onnx-tensorflow repository with tensorflow=2.6.0, onnx=1.9.0 and onnx-tf=1.9.0 but I received the following error. 

![image](https://user-images.githubusercontent.com/48021731/139688478-ed708932-170d-4a81-91b4-f017a44d8e62.png)

**Comment by glenn-jocher** [comment]
@AlexisPapaioannou errors produced by third party tools should be raised directly with their authors.
