### ISSUE TITLE
Get scale of object from output

### ISSUE THREAD

**Issue by TjeerdMooi** [ultralytics/yolov5#5433]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When I run model(image)[0], i get an output of shape ([1, 7371, 85]). I know that the 7371 are all of the predictions and the 85 consists of the bounding box attributes and class scores. 

However, I was wondering if there is any way to get the scale of each prediction; I want to be able to select one of the 7317 outputs and get the scale (small, medium or large). Does the first part of the predictions consist of predictions of large objects, the middle part of predictions of medium sized objects, and the last part of  predictions of small objects? 

Thanks in advance

**Comment by glenn-jocher** [comment]
@TjeerdMooi Detect() module forward method concatenates all outputs into 1, you can retrieve the individual values by putting in a breakpoint before concatenation:

https://github.com/ultralytics/yolov5/blob/4c0982a243aac3969345fc61e10eb7ea4d78e104/models/yolo.py#L34-L71
