### ISSUE TITLE
About wandb font problem

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#5435]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

@AyushExel 
How to change the font of the training chart in wandb? For example, change the scale font of the horizontal and vertical axis to the new Roman font.

**Comment by AyushExel** [comment]
@Zengyf-CVer W&B dashboard should use the same font as your system/browser. Can you share a screenshot of the problem that you're seeing?

**Comment by Zengyf-CVer** [comment]
@AyushExel 
Can the scale font of the horizontal and vertical axis of this graph, or the font of the title and legend, be changed in W&B through related settings or codes?
![11111111111111](https://user-images.githubusercontent.com/41098760/139689984-ccec5355-8cce-4362-bb5a-8bb2028f8890.PNG)
