### ISSUE TITLE
Not training without error

### ISSUE THREAD

**Issue by klock18** [ultralytics/yolov5#544]
## ❔Question

Hi,

I have been running some experiments between the different yolov5 architectures. For yolov5s and yolov5x I never have an issue but without an error code yolov5m and yolov5l will sometimes not train:

![image](https://user-images.githubusercontent.com/43727102/88742145-c9d09600-d184-11ea-9dc1-6b9e80f1798b.png)

Here I would normally expect to see the different epochs being executed.

Thanks!

**Comment by glenn-jocher** [comment]
--weights is type=str
