### ISSUE TITLE
Unexpected behavior of `check_git_status()` utility function

### ISSUE THREAD

**Issue by MrinalJain17** [ultralytics/yolov5#5440]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

The following function is called from within `train.py`.

https://github.com/ultralytics/yolov5/blob/4c0982a243aac3969345fc61e10eb7ea4d78e104/utils/general.py#L206-L222

Based on my understanding, the current implementation of `check_git_status()` makes one of two assumptions:

1. `train.py` has been called directly from inside the root YOLOv5 directory: In this case `check_git_status()` works as intended, informing whether the repository is up to date or not.
2. User has called `train.py` from somewhere else, most likely by providing the full path. For instance, `python path/to/train.py ...`. In this case, `check_git_status()` assumes that the directory from where the training script is executed is NOT version controlled.

The assumption made in scenario 2 is invalid if the training command is executed from some other **version-controlled** directory. Since that directory will also have a `.git` folder, `check_git_status()` mistakenly considers that the script has been called from within the Yolo repository.

And we end up with something like this:

![image](https://user-images.githubusercontent.com/19644085/139732946-02353c09-61dd-41b0-93d4-f6e32070e0f1.png)

### Environment

- YOLOv5  v6.0-40-g8c326a1 torch 1.10.0 CUDA:0 (Quadro P1000, 4096.0MB)
- OS: Windows
- Python: 3.8

### Additional

A potential solution could be to change the working directory to the YOLOv5 repository root within the function `check_git_status()`

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@MrinalJain17 thanks for the bug report! This is an interesting use case that indeed may cause problems. 

The solution may be to check that the current directory and `ROOT` directory match, or else to change the current working directory within the function to `ROOT`.
https://github.com/ultralytics/yolov5/blob/4c0982a243aac3969345fc61e10eb7ea4d78e104/utils/general.py#L42

If you'd like to help by submitting a PR for this fix that would really help! Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
