### ISSUE TITLE
Some questions about warmup

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#5447]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

@glenn-jocher 
Although I know a little bit about warmup, I don't know the meaning of these related parameters in yolov5. Please answer me, thank you.
https://github.com/ultralytics/yolov5/blob/4c0982a243aac3969345fc61e10eb7ea4d78e104/data/hyps/hyp.scratch.yaml#L10-L12

**Comment by glenn-jocher** [comment]
@Zengyf-CVer warmup is just meant to slowly ramp up model changes to avoid optimization instabilities which may lead to divergence and/or nan values. Epochs is the number of warmup epochs, momentum and lr are the initial momentum and bias lr values that ramp to the default values over the warmup epochs.

**Comment by glenn-jocher** [comment]
You can observe warmup effects in TensorBoard or W&B learning rates:
<img width="850" alt="LR Curves" src="https://user-images.githubusercontent.com/26833433/119332195-8e113a80-bc88-11eb-8eb7-7494ff1d5c01.png">
