### ISSUE TITLE
What's the meanings of 'args' in yolov5.yaml?

### ISSUE THREAD

**Issue by Le0v1n** [ultralytics/yolov5#5448]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When I view this .yaml file (yolov5.yaml), I dont have idea about the 'args'. 
For examples, [64, 3] means that the channel of inputs_img is 3, and 64 means the channel of output_feature map is 64?

Is this logic right?

But When I obey this logic, I get confused.

In this logic, the Conv  [128, 3, 2] means inputs channel is 3, outputs channel is 128 and stride is 2.

And I debug "train.py", I find this:
![image](https://user-images.githubusercontent.com/67271439/139812656-747ff209-4180-4490-a90f-45562c75a161.png)

Focus' args is [3, 32, **_3_** ], Conv's args is [32, 64, 3, **_2_** ]. I know the function of "depth_multiple & width_multiple", but I have no  idea about '**_3_**' & '**_2_**' in the end.

Emmmm, I think I have a poor understanding about them, the logic of mine doesn't work.

BTW, this is yolov5-v3.

I will appreciate it that you can tell me how to understand them in ur spare time!

# YOLOv5 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Focus, [64, 3]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, BottleneckCSP, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 9, BottleneckCSP, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, BottleneckCSP, [512]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 1, SPP, [1024, [5, 9, 13]]],
   [-1, 3, BottleneckCSP, [1024, False]],  # 9
  ]

**Comment by Le0v1n** [comment]
![image](https://user-images.githubusercontent.com/67271439/139816884-20a9df74-fdd3-4685-a72d-153f30b3655c.png)

I rethink this question, and I think that the args' first number means output channel, the second number means input channel and the input channel is known when Focus runs so the next layer's input have no necessary to write. The third number mean stride and its default value is 1.

For following picture :

![image](https://user-images.githubusercontent.com/67271439/139816276-cfa51733-ec8e-4aac-880a-9e3b3ec7536a.png)

The first number is input channel, the second number is output channel, the third number is kernel_size of filter (default value is 1) and the forth number is stride (default value is 1).

Is my thoughts right? If they are wrong, please correct me. Thank you very much!

**Comment by Zengyf-CVer** [comment]
@Le0v1n 
You can refer to this note:
https://github.com/ultralytics/yolov5/blob/19c8760caa70f4d04d3fb974d797f9d922bf6eb8/models/common.py#L38
#### Output channel, convolution kernel, stride, padding
https://github.com/ultralytics/yolov5/blob/19c8760caa70f4d04d3fb974d797f9d922bf6eb8/models/yolov5s.yaml#L16
The input of this layer is the output of the previous layer, so there is no need to set.

**Comment by Le0v1n** [comment]
@Zengyf-CVer 
Thanks for ur patience!

**Comment by lchunleo** [comment]
Hi 
 I learn something from the discussion. May I check what is the 'From' meant in the architecture? I noted that it mostly -1 and in the yaml file , there is a [-1,14] , what does it meant? Thanks 

![image](https://user-images.githubusercontent.com/24416494/196028833-006cc8a7-53b4-4ebe-847d-ca470ca18512.png)

**Comment by glenn-jocher** [comment]
Module inputs from which layer. -1 indicates previous layer.
