### ISSUE TITLE
correct resume True error

### ISSUE THREAD

**Issue by wonbeomjang** [ultralytics/yolov5#5452]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

First of all, thank you for the great code. I started training  with ms coco dataset, and I gave an argument as --resume True to resume after the suspension. However, my system recognized True as a string and the following error came out.  

![스크린샷, 2021-11-02 22-44-41](https://user-images.githubusercontent.com/40621030/139858679-4ab69df4-b4d4-4188-99fd-d82afedba79a.png)

If opt.resume == 'True', we were able to solve the problem with an additional code that fixes it with boolean.  

### Environment

- YOLO: YOLOv5 torch 1.10+cu112 CUDA:0 Tesla T4
- OS: Devian
- python: 3.8

### Minimal Reproducible Example

```python
ckpt = opt.resume if isinstance(opt.resume, str) else get_latest_run() 
```

### Additional

my pull request is https://github.com/ultralytics/yolov5/pull/5451

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@wonbeomjang thanks for the bug report! This may be due to a bit of confusion, as the `--resume` use cases are either:
```bash
python train.py --resume  # resume most recent run
python train.py --resume path/to/last.pt  # specify run
```

**Comment by glenn-jocher** [comment]
@wonbeomjang I think argparser ops with boolean values are actually not very common, i.e. see https://stackoverflow.com/questions/15008758/parsing-boolean-values-with-argparse
