### ISSUE TITLE
Onnx file outputs

### ISSUE THREAD

**Issue by AlexisPapaioannou** [ultralytics/yolov5#5453]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Why the output of the onnx file from yolov5s contains 3 arrays?

### Additional

![image](https://user-images.githubusercontent.com/48021731/139870444-ce427acb-0390-4b5f-af96-b6aca3e50f5c.png)

**Comment by glenn-jocher** [comment]
@AlexisPapaioannou ONNX outputs are the concatenated individual outputs in `output` and also each individual output, i.e. 350, 416, 482 in this YOLOv5s model. You can ignore the individual outputs.

<img width="1136" alt="Screenshot 2021-11-02 at 22 34 19" src="https://user-images.githubusercontent.com/26833433/139954960-b613a6ff-6cf5-4c0b-b5b8-456081082c66.png">

**Comment by AlexisPapaioannou** [comment]
okay, thank you!
