### ISSUE TITLE
Which script must I modify in order to generate my Precision-Recall curve?

### ISSUE THREAD

**Issue by ib124** [ultralytics/yolov5#5456]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello everyone, I am new to YOLOv5 and am trying to generate a precision-recall curve for a dataset that I have already trained. I can make inferences without an issue, but I need to generate this graph. I am relatively new to deep learning, and am needing to generate this graph for a conference. [This Github question](https://github.com/ultralytics/yolov5/issues/1252) has led me to the code I need to generate the plot, but I just don't know where to put it and what to run in order to generate the graph. Here is the code:

```
if plot:
   py = np.stack(py, axis=1)
   fig, ax = plt.subplots(1, 1, figsize=(5, 5))
   ax.plot(px, py, linewidth=0.5,label="WMI") # plot(recall, precision)
   ax.plot(px, py.mean(1), linewidth=0.6, color='r', label='all classes %.3f mAP@0.5' % ap[:, 0].mean())
   ax.set_xlabel('Recall')
   ax.set_ylabel('Precision')
   ax.set_xlim(0, 1)
   ax.set_ylim(0, 1)
   plt.legend()
   fig.tight_layout()
   fig.savefig(fname, dpi=200)
```

If anyone could help me, that would be greatly appreciated! Thanks!

**Comment by glenn-jocher** [comment]
@ib124 PR curves are generated by val.py, along with many other metrics and analytics. Check your runs/val/exp directory for all results.
```bash
python val.py --data coco128.yaml --weights yolov5s.pt
```
<img src="https://user-images.githubusercontent.com/26833433/139961548-f05f0795-fead-40ec-add1-c7d1fa01478b.png" width="800"  />

**Comment by ib124** [comment]
@glenn-jocher That is what I needed. Thank you!

**Comment by amriyan** [comment]
@glenn-jocher I have 10 PR curves based on 10-fold cross-validation. I have done it manually. Therefore, how do I show the 10 curves in an image with an average?

**Comment by glenn-jocher** [comment]
@amriyan to plot multiple Precision-Recall (PR) curves with an average, you'll need to modify the plotting section of the `val.py` script. You should collect the precision and recall values for each of your 10 folds and calculate their mean. Here's a simplified example of how you might adjust the plotting code:

```python
import matplotlib.pyplot as plt
import numpy as np

# Assuming px and py are lists containing recall and precision values for each fold
# For example:
# px = [fold1_recall, fold2_recall, ..., fold10_recall]
# py = [fold1_precision, fold2_precision, ..., fold10_precision]

fig, ax = plt.subplots(1, 1, figsize=(5, 5))

# Plot each fold's PR curve
for i in range(10):
    ax.plot(px[i], py[i], linewidth=0.5, label=f"Fold {i+1}")

# Calculate and plot the mean PR curve
mean_precision = np.mean(np.vstack(py), axis=0)
mean_recall = np.mean(np.vstack(px), axis=0)  # Only if recall differs per fold, otherwise use any px[i]
ax.plot(mean_recall, mean_precision, linewidth=2, color='r', label='Mean PR curve')

ax.set_xlabel('Recall')
ax.set_ylabel('Precision')
ax.set_xlim(0, 1)
ax.set_ylim(0, 1)
plt.legend()
fig.tight_layout()

# Save the figure
fig.savefig('pr_curves.png', dpi=200)
```

Remember to replace the `px` and `py` placeholders with your actual data. If your recall values are the same for each fold, you can just use one of them for the mean curve. Adjust the labels and colors as needed for clarity.
