### ISSUE TITLE
GPU inference 

### ISSUE THREAD

**Issue by noobmaster29** [ultralytics/yolov5#5457]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am running the inference detect.py file on a laptop with an Nvidia GPU. I wanted to ask if it is possible to have the inference run on the GPU instead of the CPU. Thanks in advance for any help.

**Comment by glenn-jocher** [comment]
@noobmaster29 inference runs on GPU if available automatically. You can manually select a backend with --device:
```bash
python detect.py --device 0  # CUDA device 0
python detect.py --device cpu
```

**Comment by yangboz** [comment]
> @noobmaster29 inference runs on GPU if available automatically. You can manually select a backend with --device:
> 
> ```shell
> python detect.py --device 0  # CUDA device 0
> python detect.py --device cpu
> ```

how about  this way ? for example: yolov5 = YOLOv5(model_path, device),  the device string equal to gpu:0/1/2 ?
