### ISSUE TITLE
How can I get the image coordinates of the target？Thanks

### ISSUE THREAD

**Issue by gexianwei1231** [ultralytics/yolov5#5459]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How can I get the image coordinates of the target？Where does the code need to be modified? I don't understand.Thank you very much.

**Comment by glenn-jocher** [comment]
@gexianwei1231 I'm sorry I don't understand your question.

**Comment by Zengyf-CVer** [comment]
@gexianwei1231 
https://github.com/ultralytics/yolov5/blob/0155548384e90597f140560004364633430070cd/detect.py#L222-L227
