### ISSUE TITLE
Show results in stream from GigE camera.

### ISSUE THREAD

**Issue by Meezelmao** [ultralytics/yolov5#5460]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I try to use YOLOv5 with 3 GigE cameras. My cameras brings images as NumPy array. In this example i transit frames to YOLO model. I need to show results images on stream in CV or PIL window. How can i do this? I try to plot results images in cv2 window, but it doesn't work.
  
          Img1 = Cam1.GetImage()
            if not Img1.IsEmpty():
                ImgArr1 = Img1.GetNPArray()
        
            YoloIMG1 = ImgArr1
            results = model1(YoloIMG1, size=640)
            res = results.imgs

**Comment by glenn-jocher** [comment]
@Meezelmao if you want to display results on images you can use `results.render()`, which updates results.imgs with detection boxes.

**Comment by Meezelmao** [comment]
I want to display images during a loop. I need the results for example in WebCAM as a source in detect.py (it returns a window with rendered images). Right now I cannot create a window to display the render image. I use code below. 

```
while True:
    Img1 = Cam1.GetImage()
    if not Img1.IsEmpty():
        ImgArr1 = Img1.GetNPArray()
    YoloIMG1 = ImgArr1
    results = model1(YoloIMG1, size=640)
    results.print()
```

**Comment by glenn-jocher** [comment]
@Meezelmao we don't provide support for custom code, but perhaps a community member may be able to help.
