### ISSUE TITLE
Why is the rho2 for DIOU divided by 4?

### ISSUE THREAD

**Issue by sarmientoj24** [ultralytics/yolov5#5462]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am trying to add another evaluation metric that only measures centroid distances between two preds and target bboxes. Saw that I can just reuse a part in DiOU but I noticed that it has a ` / 4`

```
rho2 = ((b2_x1 + b2_x2 - b1_x1 - b1_x2) ** 2 +
                    (b2_y1 + b2_y2 - b1_y1 - b1_y2) ** 2) / 4  # center distance squared
```

Just to clarify, this part measures the distance of the centroids of boxes, right?

**Comment by glenn-jocher** [comment]
@sarmientoj24 you might want to read the paper and/or ask the author:
https://github.com/Zzh-tju/DIoU
