### ISSUE TITLE
yolov5-v5.0 and v6.0 training time question

### ISSUE THREAD

**Issue by 992060356** [ultralytics/yolov5#5466]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I trained the v5.0 network before, and then when I trained the 6.0 network today, I found that with the same dataset, my graphics card is NVIDIA GeForce RTX 3090 with 24G of video memory, and I used yolov5x.pt as the pre-trained model, and trained under the same machine, the number of threads are both 8, the imagesize are both 640, v5.0 is set to 16batch, v6.0 set the automatic batch, it is defined in batch22, but there is a big difference in training time, v5.0 code 45 minutes an epoch, v6.0 code close to 4 hours an epoch, this is why? Isn't it the 6.0 code that has improved the speed? Why does the training time take so much longer?  
![1635926754(1)](https://user-images.githubusercontent.com/75258166/140029656-38129ea3-d1db-4f27-9019-14e587f26651.png)
![1635927007(1)](https://user-images.githubusercontent.com/75258166/140029671-027e6c51-d8db-464c-93e6-1a0bbb7008e6.png)
I hope you can help me to answer this question

**Comment by 992060356** [comment]
@glenn-jocher，can you help me resolve this question? Thank you very much！

**Comment by glenn-jocher** [comment]
@992060356 in general both training and inference speeds in v6.0 are faster than in v5.0. If your results are not consistent with this then there may be additional changes in your comparison that are not factored in, i.e. different environments, software, versions or utilization rates. You can see an apples-to-apples comparison of YOLOv5l changes between v5.0 and v6.0 in our release notes:

https://github.com/ultralytics/yolov5/releases/edit/v6.0

mAP improves from +0.3% to +1.1% across all models, and ~5% FLOPs reduction produces slight speed improvements and a reduced CUDA memory footprint. Example YOLOv5l before and after metrics:

|YOLOv5l<br><sup>Large|size<br><sup>(pixels) |mAP<sup>val<br>0.5:0.95 |mAP<sup>val<br>0.5 |Speed<br><sup>CPU b1<br>(ms) |Speed<br><sup>V100 b1<br>(ms) |Speed<br><sup>V100 b32<br>(ms) |params<br><sup>(M) |FLOPs<br><sup>@640 (B)
---                       |---  |---      |---      |---       |---     |--- |---      |---
[v5.0] (previous) |640  |48.2     |66.9     |457.9      |11.6    |2.8    |47.0     |115.4
[v6.0] (this release)  |640  |**48.8** |**67.2** |**424.5** |**10.9**|**2.7** |**46.5** |**109.1**

**Comment by lucky-xu-1994** [comment]
@992060356 Hi，I have the same problem with you on training time. yolov5-v6.0 takes twice as long to train an epoch as yolov5-v5.0 (RTX 3090).

**Comment by 992060356** [comment]
@lucky-xu-1994 Sorry, I remember I replied to this message. It may be due to network problems.
My training time is more than twice as long. but they still haven't been solved. I guarantee that their other configurations are the same, or the same result. I don't know why. Is it because of the 3090 graphics card problem? I haven't seen anyone else respond to this problem

**Comment by glenn-jocher** [comment]
@992060356 you might try downgrading to CUDA 10 as CUDA 11 has a few known issues, especially with conda, windows and consumer cards.

**Comment by 992060356** [comment]
@glenn-jocher 3090 don’t support CUDA10

**Comment by glenn-jocher** [comment]
@992060356 that's unfortunate. Then you may be stuck. In any case this may be a PyTorch issue and above our heads here at YOLOv5.

**Comment by 992060356** [comment]
@glenn-jocher Can I upgrade torch version to solve this problem？

**Comment by 992060356** [comment]
@glenn-jocherMy torch version is 1.7.0.

**Comment by glenn-jocher** [comment]
@992060356 yeah definitely. I would use the latest versions of everything you can, except for CUDA. We see the best performance with CUDA 10.2.

**Comment by 992060356** [comment]
@glenn-jocher ok,  I upgrade my torch version to 1.8.0 or the latest 1.10 to see if the training time can return to normal.

**Comment by linklist2** [comment]
@992060356 你好，请问您通过升级torch版本解决了这个问题了吗，我也是3090+torch 1.7.0，也遇到了和您同样的问题。

**Comment by linklist2** [comment]
我升级到了1.10后，v6.0的速度就正常了。

**Comment by 992060356** [comment]
> 我升级到了1.10后，v6.0的速度就正常了。

@linklist2 是吗，那太好了，我还没升级，只升torch就好了吗？

**Comment by linklist2** [comment]
@992060356 是这样的，只是将1.7 升级到了1.10

**Comment by Etern213** [comment]
> > 我升级到了1.10后，v6.0的速度就正常了。
> 
> @linklist2 是吗，那太好了，我还没升级，只升torch就好了吗？

你的问题解决了吗，我也遇到这个问题了

**Comment by 992060356** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
