### ISSUE TITLE
pycocotools unable to run: Results do not correspond to current coco set

### ISSUE THREAD

**Issue by Longging** [ultralytics/yolov5#5467]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When I run the eval.py file, I always get this error。

**Comment by glenn-jocher** [comment]
@Longging pycocotools runs automatically on COCO data, i.e. coco.yaml. For custom datasets you don't need it.

**Comment by zxq309** [comment]
@glenn-jocher "--save-json" has a bug in  save_one_json(predn, jdict, path, class_map) function from val.py, when evaluation the custom dataset and model.
![image](https://user-images.githubusercontent.com/22740766/164142679-79b337c4-26f8-4575-a774-9f2ce379c2a0.png)
for example, image or label file names as follows:(str)
![image](https://user-images.githubusercontent.com/22740766/164143066-a61a8a77-09ac-4187-bc41-88f52a50e12b.png)
![image](https://user-images.githubusercontent.com/22740766/164143087-9e03b2cc-6afb-4f54-992d-4cc90346f484.png)
image_id must be int, but cannot convert from above file names. So, the title question occurs. How to handle this?

**Comment by glenn-jocher** [comment]
@zxq309 image_id can be anything. If it's COCO it's saved as an int.

**Comment by zxq309** [comment]
if above files name, how can I change this

**Comment by zxq309** [comment]
@glenn-jocher What's going on with yolov5's evaluation being higher than Pycocotools' evaluation?
![image](https://user-images.githubusercontent.com/22740766/164349510-eb947c47-e4e4-4318-9b74-3ab53d35d934.png)

**Comment by glenn-jocher** [comment]
@zxq309 there's a known issue with differences between the two. On COCO the YOLOv5 mAP is usually lower than the pycocotools mAP, but for different datasets results may vary. We haven't been able to resolve it so we opened up a competition that's still open. See https://github.com/ultralytics/yolov5/issues/2258

**Comment by zxq309** [comment]
Ok, Thank you very much for your patient reply!

**Comment by glenn-jocher** [comment]
@zxq309 you're welcome! If you have any insight into the problem please let us know, or you can also submit a PR. 

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by yolor2** [comment]
Hello @glenn-jocher  and @zxq309 i am facing the same problem.
I have my image files and text file of validation in format of 150621_10.txt or 150621_10.jpg and have the .json file as well.
but while running val.py to generate the coco evaluation results i am getting this error "ERROR: pycocotools unable to run: Results do not correspond to current coco set".
i have look into the pred.json and there is difference in image_id key as pred.josn takes image_id from the file name and in coco image_id is inherited from image key.

Could you please help me to solve this.

**Comment by glenn-jocher** [comment]
@yolor2 pycocotools evaluation is only automated for coco.yaml. 

Other usage would require customization on your part.

**Comment by MheadHero** [comment]
> @Longging pycocotools runs automatically on COCO data, i.e. coco.yaml. For custom datasets you don't need it.

does this mean, If I using custom dataset from roboflow, den output this errors, I can ignore it?

**Comment by GunjanPatel1108** [comment]
@MheadHero you need to do the change in the annotation file. As results.json have some different format than usual. SO you need to do some changes in .json file of annotation file for your validation or test set. The changes like swap the image_id with the file name without using extension and it will work.

**Comment by MheadHero** [comment]
> @MheadHero you need to do the change in the annotation file. As results.json have some different format than usual. SO you need to do some changes in .json file of annotation file for your validation or test set. The changes like swap the image_id with the file name without using extension and it will work.

any tutorial for it, i dont really understand lol

**Comment by epureanudiana** [comment]
@MheadHero 
in the json, in `"images"` if I had one dict with` {"id": 1, file_name: "path/to/image_name.jpg" }`, I replaced it with `{"id": "image_name", file_name: "path/to/image_name.jpg" }` and in `"annotations"` everywhere I found `"image_id": 1`, I replaced with `"image_id": "image_name"`

I did the same for all integer ids!

**Comment by imadgohar** [comment]
@zxq309 Did you got these metrics on custom dataset or yolov5?

**Comment by 8yang8** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.
> 
> ### Question
> When I run the eval.py file, I always get this error。
> 
> ### Additional
> _No response_

Have you solved the problem?

**Comment by glenn-jocher** [comment]
@8yang8 yes, if you're encountering issues with custom datasets and pycocotools, it likely involves adapting your dataset's annotation format to match the expected structure. For COCO-style datasets, ensure your `image_id` fields are consistent and correctly link annotations to the respective images. Customizing scripts or annotations may be required for compatibility. For specific guidance or troubleshooting, feel free to share detailed error logs or additional context.
