### ISSUE TITLE
f1 score with different conf_thres

### ISSUE THREAD

**Issue by firsakov** [ultralytics/yolov5#5474]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,

I run val.py with default conf_thres 0.001 and get 0.93 mean f1 score, when I run val.py with 0.4 conf_thres i get same 0.93, but there are a lot of false positive with conf_thres 0.001 when I visualize predictions. please help, why script doesn't react properly on conf_thres?

**Comment by glenn-jocher** [comment]
@firsakov P and R are evaluated at max F1 confidence, not the argument confidence you pass, which is only used to compute mAP, and will only produce valid mAP values near conf = 0.0.
![image](https://user-images.githubusercontent.com/26833433/140066701-2fc6ef6f-2508-4d2e-984e-7932cc6e88a0.png)
