### ISSUE TITLE
Why the inference speed when the image size is 224 is slower than the image size is 640？

### ISSUE THREAD

**Issue by daydayup-bit** [ultralytics/yolov5#5475]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When i enter command`python val.py --data container_yolo/NEU-DET/data.yaml --weights runs/train/v5s_all_new/weights/best.pt --imgsz 640`，time of inference is **2.4ms**，the result：
![image](https://user-images.githubusercontent.com/74170825/140068750-6ce4ba0c-55a7-42c1-89d8-3db9c1984360.png)

when i enter command`python val.py --data container_yolo/NEU-DET/data.yaml --weights runs/train/v5s_all_new/weights/best.pt --imgsz 224`，time of  inference is **4.1ms**,**which is slower than inputing 640**. the result:
![image](https://user-images.githubusercontent.com/74170825/140071063-4d364820-5c96-4d16-80cf-098b893e3c77.png)

Why the inference speed when the image size is 224 is slower than the image size is 640？
And, what are the main effects of these three parameters(pre-process,inference,NMS).Especially what affects the inference time？

**Comment by glenn-jocher** [comment]
@daydayup-bit 👋 Hello! Thanks for asking about **inference speed issues**. YOLOv5 🚀 can be run on CPU (i.e. `--device cpu`, slow) or GPU if available (i.e. `--device 0`, faster). You can determine your inference device by viewing the YOLOv5 line printed to screen:

If you would like to increase your inference speed some options are:

- Increase `--batch-size` ([YOLOv5 PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) and `val.py` only)
- Reduce `--img-size`, i.e. 1280 -> 640 -> 320
- Reduce model size, i.e. YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s -> YOLOv5n
- Use a faster GPUs, i.e.: P100 -> V100 -> A100
- Use a free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

### detect.py inference
```bash
python detect.py --weights yolov5s.pt --img 640 --conf 0.25 --source data/images/
```
<img width="944" alt="detect.py" src="https://user-images.githubusercontent.com/26833433/140100842-e130b5f7-64cb-46c9-9386-72abadd19828.png">

### YOLOv5 PyTorch [Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) inference
```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Images
dir = 'https://ultralytics.com/images/'
imgs = [dir + f for f in ('zidane.jpg', 'bus.jpg')]  # batch of images

# Inference
results = model(imgs)
results.print()  # or .show(), .save()
# Speed: 631.5ms pre-process, 19.2ms inference, 1.6ms NMS per image at shape (2, 3, 640, 640)
```

**Comment by daydayup-bit** [comment]
@glenn-jocher Thank you very much for your answer. You said that reducing --img-size can increase the speed of inference, but on my machine, I found that this is not the case. When I use yolov5s to run detect.py on the GPU and enter a different --img-size, I get the following result.
![image-20211104110410987](https://user-images.githubusercontent.com/74170825/140253125-c6826937-7114-4ff9-8490-51ce2e210b9e.png)
![image](https://user-images.githubusercontent.com/74170825/140253282-36bf4138-b722-4ddc-921c-14dd39e23c01.png)
![image](https://user-images.githubusercontent.com/74170825/140253325-7c6e7e41-1eeb-4cb7-b6e9-6cd2ef9bbed4.png)
![image](https://user-images.githubusercontent.com/74170825/140253381-2a5965ef-39b4-4a37-8d43-cf34d4376160.png)
![image](https://user-images.githubusercontent.com/74170825/140253408-484691d2-e224-4745-83df-e1b00d8216cb.png)
![image](https://user-images.githubusercontent.com/74170825/140253441-8f19b680-cc4b-4460-8462-8d81cb23053d.png)
| --img-size | inference time/per img |
| ---------- | ---------------------- |
| 1280       | 10.6ms                 |
| 640        | 9.1ms                  |
| 480        | 8.4ms                  |
| 320        | 9.9ms                  |
| 224        | 9.5ms                  |

As you can see, the inference time ranking is not the 224<320<480<640<1280 we expected, but 480<640<224<320<1280. I used a total of 180 images for detect. Why does this happen? I am very confused.

**Comment by glenn-jocher** [comment]
@daydayup-bit I can't speak for your specific environment, but if your times don't improve then there's a constraint somewhere in your workflow unrelated to GPU or image size.

**Comment by daydayup-bit** [comment]
Okay, thank you for your reply.

**Comment by kuonumber** [comment]
@glenn-jocher Do you mean if I train model in larger batch size, I will get less inference time?

**Comment by glenn-jocher** [comment]
@kuonumber @daydayup-bit we recently published a full inference speed vs batch size study here:
https://community.ultralytics.com/t/yolov5-study-batch-size-vs-speed

![image](https://user-images.githubusercontent.com/26833433/157844240-0fb38aaf-76dd-44bc-86b1-4ddc8825e9b3.png)

**Comment by kuonumber** [comment]
@glenn-jocher WOW THAT'S REALLY COOL!
