### ISSUE TITLE
Model does not detect when on GPU

### ISSUE THREAD

**Issue by Joyel1441** [ultralytics/yolov5#5482]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When I use GPU in Pytorch the model outputs "no detection", but when i convert that model to cpu it detects objects successfully, what is the issue and how to fix it?
but detect.py uses GPU and detects objects successfully, but model is unable to do it

### Additional

This is the code:

import cv2
import numpy as np

cap = cv2.VideoCapture(0)

while cap.isOpened():
    ret, frame = cap.read()
    result = model(frame)
    cv2.imshow("YOLO", np.squeeze(result.render()))
    if cv2.waitKey(20) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

*****************************************************

here when I convert model to cpu it works fine

**Comment by glenn-jocher** [comment]
@Joyel1441 it appears you may have environment problems. Hub models employ Automatic Mixed Precision (AMP) context managers (as do train.py and val.py) that are absent from detect.py. If you are having AMP problems this likely stems from environment issues, i.e. possibly CUDA, conda, or windows related.

Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below. 


## Requirements

[**Python>=3.6.0**](https://www.python.org/) with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) installed including [**PyTorch>=1.7**](https://pytorch.org/get-started/locally/). To get started:
```bash
$ git clone https://github.com/ultralytics/yolov5
$ cd yolov5
$ pip install -r requirements.txt
```

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), validation ([val.py](https://github.com/ultralytics/yolov5/blob/master/val.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/export.py)) on MacOS, Windows, and Ubuntu every 24 hours and on every commit.

**Comment by Joyel1441** [comment]
> @Joyel1441 it appears you may have environment problems. Hub models employ Automatic Mixed Precision (AMP) context managers (as do train.py and val.py) that are absent from detect.py. If you are having AMP problems this likely stems from environment issues, i.e. possibly CUDA, conda, or windows related.
> 
> Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally. If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below.
> 
> ## Requirements
> [**Python>=3.6.0**](https://www.python.org/) with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) installed including [**PyTorch>=1.7**](https://pytorch.org/get-started/locally/). To get started:
> 
> ```shell
> $ git clone https://github.com/ultralytics/yolov5
> $ cd yolov5
> $ pip install -r requirements.txt
> ```
> 
> ## Environments
> YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):
> 
> * **Google Colab and Kaggle** notebooks with free GPU: [![Open In Colab](https://camo.githubusercontent.com/84f0493939e0c4de4e6dbe113251b4bfb5353e57134ffd9fcab6b8714514d4d1/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb) [![Open In Kaggle](https://camo.githubusercontent.com/a08ca511178e691ace596a95d334f73cf4ce06e83a5c4a5169b8bb68cac27bef/68747470733a2f2f6b6167676c652e636f6d2f7374617469632f696d616765732f6f70656e2d696e2d6b6167676c652e737667)](https://www.kaggle.com/models/ultralytics/yolov5)
> * **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
> * **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
> * **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) [![Docker Pulls](https://camo.githubusercontent.com/280faedaf431e4c0c24fdb30ec00a66d627404e5c4c498210d3f014dd58c2c7e/68747470733a2f2f696d672e736869656c64732e696f2f646f636b65722f70756c6c732f756c7472616c79746963732f796f6c6f76353f6c6f676f3d646f636b6572)](https://hub.docker.com/r/ultralytics/yolov5)
> 
> ## Status
> ![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)
> 
> If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), validation ([val.py](https://github.com/ultralytics/yolov5/blob/master/val.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/export.py)) on MacOS, Windows, and Ubuntu every 24 hours and on every commit.

Still didn't fix the issue, I created new env and tried, still getting same problem

**Comment by glenn-jocher** [comment]
@Joyel1441 if you're having local environment issues you can use one of our verified environments below.

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

**Comment by Joyel1441** [comment]
> @Joyel1441 if you're having local environment issues you can use one of our verified environments below.
> 
> YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):
> 
> * **Google Colab and Kaggle** notebooks with free GPU: [![Open In Colab](https://camo.githubusercontent.com/84f0493939e0c4de4e6dbe113251b4bfb5353e57134ffd9fcab6b8714514d4d1/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb) [![Open In Kaggle](https://camo.githubusercontent.com/a08ca511178e691ace596a95d334f73cf4ce06e83a5c4a5169b8bb68cac27bef/68747470733a2f2f6b6167676c652e636f6d2f7374617469632f696d616765732f6f70656e2d696e2d6b6167676c652e737667)](https://www.kaggle.com/models/ultralytics/yolov5)
> * **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
> * **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
> * **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) [![Docker Pulls](https://camo.githubusercontent.com/280faedaf431e4c0c24fdb30ec00a66d627404e5c4c498210d3f014dd58c2c7e/68747470733a2f2f696d672e736869656c64732e696f2f646f636b65722f70756c6c732f756c7472616c79746963732f796f6c6f76353f6c6f676f3d646f636b6572)](https://hub.docker.com/r/ultralytics/yolov5)

Is there any way I can run it locally?

**Comment by glenn-jocher** [comment]
@Joyel1441 we don't assist in debugging local environments, but if I were you I would start from the verified environments to see how to set up your environment, and also refer to https://pytorch.org/get-started/locally/

**Comment by Zengyf-CVer** [comment]
@Joyel1441 
I don't quite understand your sentence, please say it in detail and accurately.
```
but detect.py uses GPU and detects objects successfully, but model is unable to do it
```

**Comment by Joyel1441** [comment]
> @Joyel1441 we don't assist in debugging local environments, but if I were you I would start from the verified environments to see how to set up your environment, and also refer to https://pytorch.org/get-started/locally/



> @Joyel1441 I don't quite understand your sentence, please say it in detail and accurately.
> 
> ```
> but detect.py uses GPU and detects objects successfully, but model is unable to do it
> ```

When I load model using pytorch hub and pass images it doesn't detect any objects, but when I convert that model to cpu it detects objects
OS: windows 11
GPU: gtx 1650ti
Cuda: 11.3
pytorch: 1.10

**Comment by Zengyf-CVer** [comment]
@Joyel1441 
I understand, it's actually very simple. I read your code. You are using OpenCV to read the video frame. Therefore, you must strictly follow the OpenCV reading when using Pytorch Hub, and you need to convert the format of the picture read by OpenCV. For normal use, you can refer to this: https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading
```python
import cv2
import torch
from PIL import Image

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Images
for f in ['zidane.jpg', 'bus.jpg']:
    torch.hub.download_url_to_file('https://ultralytics.com/images/' + f, f)  # download 2 images
img1 = Image.open('zidane.jpg')  # PIL image
img2 = cv2.imread('bus.jpg')[..., ::-1]  # OpenCV image (BGR to RGB)
imgs = [img1, img2]  # batch of images

# Inference
results = model(imgs, size=640)  # includes NMS

# Results
results.print()  
results.save()  # or .show()

results.xyxy[0]  # img1 predictions (tensor)
results.pandas().xyxy[0]  # img1 predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 1  433.50  433.50   517.5  714.5    0.687988     27     tie
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie

```

**Comment by Zengyf-CVer** [comment]
@Joyel1441 
In order to use PytorchHub normally, it is recommended that you use the pillow component.

**Comment by Joyel1441** [comment]
> @Joyel1441 In order to use PytorchHub normally, it is recommended that you use the pillow component.

Even this code doesn't work:
results = model("image.jpg")
results.print()

It outputs no detections

But when I do this:
model = model.cpu()
results = model("image.jpg")
results.print()
It gives correct detections

**Comment by Zengyf-CVer** [comment]
@Joyel1441 
First of all, to be clear, there is no problem with the yolov5 pytorch hub program. I have used this for a long time, and your problem did not appear.
Secondly, I suggest you use anaconda to recreate a virtual environment.
Finally, it is also very important that pytorch is installed using the official website installation instructions. Strictly look at the configuration. To a large extent, your pytorch is problematic. https://pytorch.org/get-started/locally/

![ksnip_20211104-195503](https://user-images.githubusercontent.com/41098760/140309300-f5f05e98-4a27-4ec8-80d1-0ec6893cdb5f.png)

**Comment by Joyel1441** [comment]
> @Joyel1441 First of all, to be clear, there is no problem with the yolov5 pytorch hub program. I have used this for a long time, and your problem did not appear. Secondly, I suggest you use anaconda to recreate a virtual environment. Finally, it is also very important that pytorch is installed using the official website installation instructions. Strictly look at the configuration. To a large extent, your pytorch is problematic. https://pytorch.org/get-started/locally/
> 
> ![ksnip_20211104-195503](https://user-images.githubusercontent.com/41098760/140309300-f5f05e98-4a27-4ec8-80d1-0ec6893cdb5f.png)

I guess the problem is with my CUDA installation

**Comment by glenn-jocher** [comment]
@Joyel1441 yes, sometimes PyTorch installations fail to run inference properly on GPU. This seems to be related to CUDA, conda, or Windows, or some combination of those. The failure occurs when models are reduced in precision using .half() or using an AMP context manager. The observable result of the failure is simply a lack of detections.

Definitely follow https://pytorch.org/get-started/locally/, and consider using the Docker image if you have local environment problems. Lastly you can use one of our verified environments like Google Colab if you are having problems locally, that's why we made them.
- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

**Comment by Joyel1441** [comment]
> @Joyel1441 yes, sometimes PyTorch installations fail to run inference properly on GPU. This seems to be related to CUDA, conda, or Windows, or some combination of those. The failure occurs when models are reduced in precision using .half() or using an AMP context manager. The observable result of the failure is simply a lack of detections.
> 
> Definitely follow https://pytorch.org/get-started/locally/, and consider using the Docker image if you have local environment problems. Lastly you can use one of our verified environments like Google Colab if you are having problems locally, that's why we made them.
> 
> * **Google Colab and Kaggle** notebooks with free GPU: [![Open In Colab](https://camo.githubusercontent.com/84f0493939e0c4de4e6dbe113251b4bfb5353e57134ffd9fcab6b8714514d4d1/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb) [![Open In Kaggle](https://camo.githubusercontent.com/a08ca511178e691ace596a95d334f73cf4ce06e83a5c4a5169b8bb68cac27bef/68747470733a2f2f6b6167676c652e636f6d2f7374617469632f696d616765732f6f70656e2d696e2d6b6167676c652e737667)](https://www.kaggle.com/models/ultralytics/yolov5)
> * **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
> * **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
> * **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) [![Docker Pulls](https://camo.githubusercontent.com/280faedaf431e4c0c24fdb30ec00a66d627404e5c4c498210d3f014dd58c2c7e/68747470733a2f2f696d672e736869656c64732e696f2f646f636b65722f70756c6c732f756c7472616c79746963732f796f6c6f76353f6c6f676f3d646f636b6572)](https://hub.docker.com/r/ultralytics/yolov5)

Oh ok, Thank you for your help, I'll try using verified envs

**Comment by IvanLauLinTiong** [comment]
> > @Joyel1441 we don't assist in debugging local environments, but if I were you I would start from the verified environments to see how to set up your environment, and also refer to https://pytorch.org/get-started/locally/
> 
> > @Joyel1441 I don't quite understand your sentence, please say it in detail and accurately.
> > ```
> > but detect.py uses GPU and detects objects successfully, but model is unable to do it
> > ```
> 
> When I load model using pytorch hub and pass images it doesn't detect any objects, but when I convert that model to cpu it detects objects OS: windows 11 GPU: gtx 1650ti Cuda: 11.3 pytorch: 1.10


@Joyel1441 
Hi, just my 2 cents,   try reinstall everything with downgraded Cuda version 10.x. It might help fixing the GPU detection failure.

I was also facing this issue too and  our local working environments are roughy similar, my env is

OS: Windows 10 
GPU: gtx 1650 
Cuda: 11.3 
PyTorch: 1.10

After deep diving through Github issues,  here what I found other people have similar problems and they suggest to use Cuda version of 10.x as a workaround : 
[#1910](https://github.com/ultralytics/yolov5/issues/1910)
[#2080](https://github.com/ultralytics/yolov5/issues/2080)

So I used Cuda 10.x (specifically 10.2) with PyTorch 1.10.0 via pip installation:
`pip3 install torch==1.10.0+cu102 torchvision==0.11.1+cu102 torchaudio===0.10.0+cu102 -f https://download.pytorch.org/whl/cu102/torch_stable.html`
 
 and now it working fine on my machine.

Hope this helps.

**Comment by Joyel1441** [comment]
> > > @Joyel1441 we don't assist in debugging local environments, but if I were you I would start from the verified environments to see how to set up your environment, and also refer to https://pytorch.org/get-started/locally/
> > 
> > 
> > > @Joyel1441 I don't quite understand your sentence, please say it in detail and accurately.
> > > ```
> > > but detect.py uses GPU and detects objects successfully, but model is unable to do it
> > > ```
> > 
> > 
> > When I load model using pytorch hub and pass images it doesn't detect any objects, but when I convert that model to cpu it detects objects OS: windows 11 GPU: gtx 1650ti Cuda: 11.3 pytorch: 1.10
> 
> @Joyel1441 Hi, just my 2 cents, try reinstall everything with downgraded Cuda version 10.x. It might help fixing the GPU detection failure.
> 
> I was also facing this issue too and our local working environments are roughy similar, my env is
> 
> OS: Windows 10 GPU: gtx 1650 Cuda: 11.3 PyTorch: 1.10
> 
> After deep diving through Github issues, here what I found other people have similar problems and they suggest to use Cuda version of 10.x as a workaround : [#1910](https://github.com/ultralytics/yolov5/issues/1910) [#2080](https://github.com/ultralytics/yolov5/issues/2080)
> 
> So I used Cuda 10.x (specifically 10.2) with PyTorch 1.10.0 via pip installation: `pip3 install torch==1.10.0+cu102 torchvision==0.11.1+cu102 torchaudio===0.10.0+cu102 -f https://download.pytorch.org/whl/cu102/torch_stable.html`
> 
> and now it working fine on my machine.
> 
> Hope this helps.

Thanks, I'll try

**Comment by Joyel1441** [comment]
> > > @Joyel1441 we don't assist in debugging local environments, but if I were you I would start from the verified environments to see how to set up your environment, and also refer to https://pytorch.org/get-started/locally/
> > 
> > 
> > > @Joyel1441 I don't quite understand your sentence, please say it in detail and accurately.
> > > ```
> > > but detect.py uses GPU and detects objects successfully, but model is unable to do it
> > > ```
> > 
> > 
> > When I load model using pytorch hub and pass images it doesn't detect any objects, but when I convert that model to cpu it detects objects OS: windows 11 GPU: gtx 1650ti Cuda: 11.3 pytorch: 1.10
> 
> @Joyel1441 Hi, just my 2 cents, try reinstall everything with downgraded Cuda version 10.x. It might help fixing the GPU detection failure.
> 
> I was also facing this issue too and our local working environments are roughy similar, my env is
> 
> OS: Windows 10 GPU: gtx 1650 Cuda: 11.3 PyTorch: 1.10
> 
> After deep diving through Github issues, here what I found other people have similar problems and they suggest to use Cuda version of 10.x as a workaround : [#1910](https://github.com/ultralytics/yolov5/issues/1910) [#2080](https://github.com/ultralytics/yolov5/issues/2080)
> 
> So I used Cuda 10.x (specifically 10.2) with PyTorch 1.10.0 via pip installation: `pip3 install torch==1.10.0+cu102 torchvision==0.11.1+cu102 torchaudio===0.10.0+cu102 -f https://download.pytorch.org/whl/cu102/torch_stable.html`
> 
> and now it working fine on my machine.
> 
> Hope this helps.

Thank you so much, downgrading cuda to 10.2 worked

**Comment by Rohan-Python** [comment]
Cuda 10.2 will require lower version of pytorch and torchvision. Pytorch =1.6 and torchvision=0.7 . So will it be okay to run yolov7 on these versions of pytorch and torchvisions?

**Comment by Rohan-Python** [comment]
> > > > @Joyel1441 we don't assist in debugging local environments, but if I were you I would start from the verified environments to see how to set up your environment, and also refer to https://pytorch.org/get-started/locally/
> > > 
> > > 
> > > > @Joyel1441 I don't quite understand your sentence, please say it in detail and accurately.
> > > > ```
> > > > but detect.py uses GPU and detects objects successfully, but model is unable to do it
> > > > ```
> > > 
> > > 
> > > When I load model using pytorch hub and pass images it doesn't detect any objects, but when I convert that model to cpu it detects objects OS: windows 11 GPU: gtx 1650ti Cuda: 11.3 pytorch: 1.10
> > 
> > 
> > @Joyel1441 Hi, just my 2 cents, try reinstall everything with downgraded Cuda version 10.x. It might help fixing the GPU detection failure.
> > I was also facing this issue too and our local working environments are roughy similar, my env is
> > OS: Windows 10 GPU: gtx 1650 Cuda: 11.3 PyTorch: 1.10
> > After deep diving through Github issues, here what I found other people have similar problems and they suggest to use Cuda version of 10.x as a workaround : [#1910](https://github.com/ultralytics/yolov5/issues/1910) [#2080](https://github.com/ultralytics/yolov5/issues/2080)
> > So I used Cuda 10.x (specifically 10.2) with PyTorch 1.10.0 via pip installation: `pip3 install torch==1.10.0+cu102 torchvision==0.11.1+cu102 torchaudio===0.10.0+cu102 -f https://download.pytorch.org/whl/cu102/torch_stable.html`
> > and now it working fine on my machine.
> > Hope this helps.
> 
> Thank you so much, downgrading cuda to 10.2 worked

Cuda 10.2 will require lower version of pytorch and torchvision. Pytorch =1.6 and torchvision=0.7 . So will it be okay to run yolov7 on these versions of pytorch and torchvisions?... @Joyel1441 which yolo version are you using. and also let me know the pytorch and torchvision version for which you got succesful detections

**Comment by pderrenger** [comment]
@Rohan-Python yOLOv5 requires PyTorch >=1.7, so using PyTorch 1.6 may not be compatible. It's best to use the recommended versions for optimal performance.

**Comment by Rohan-Python** [comment]
@pderrenger Ya, But I guess I was asking for YOLOv7. And also CUDA 10.2.
Anyways , Thank You. Long back project.

**Comment by pderrenger** [comment]
YOLOv5 requires PyTorch >=1.7, so using PyTorch 1.6 may not be compatible. It's best to use the recommended versions for optimal performance.

**Comment by pderrenger** [comment]
YOLOv5 requires PyTorch >=1.7.0, so using PyTorch 1.6 may not be compatible. It's best to use the recommended versions for optimal performance.

**Comment by pderrenger** [comment]
Running YOLOv7 on PyTorch 1.6 and torchvision 0.7 may not be optimal, as these versions might not support all features or optimizations available in newer releases. It's recommended to use the versions specified in the YOLOv7 requirements for best performance and compatibility.
