### ISSUE TITLE
How can I run val.py to output only one class?

### ISSUE THREAD

**Issue by noahzn** [ultralytics/yolov5#5492]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I try to detect only the 'person' class and want to evaluate the mAP using the pre-trained model yolov5m.pt. I use my custom data and only persons are annotated, but the model outputs 80 classes. I don't know if the calculated mAP is related to the other classes it detects. Using pytorch hub I can define the number of output classes. Is it also possible with the val.py? Thanks!

**Comment by glenn-jocher** [comment]
@noahzn I don't understand your question. If your model has 80 classes then it has 80 classes, and val.py produces an AP value per class. mAP is AP averaged over classes. You can force val to display metrics per class with 
```
python val.py --verbose
```

**Comment by noahzn** [comment]
> @noahzn I don't understand your question. If your model has 80 classes then it has 80 classes, and val.py produces an AP value per class. mAP is AP averaged over classes. You can force val to display metrics per class with
> 
> ```
> python val.py --verbose
> ```

I want to evaluate the model's performance of detecting only the person, although I'm using an 80-classes model. So in my custom data, there is only one ground-truth class: person. But when I use the 80-classes model, it also detects other objects like chairs, boxes, etc. 
I just tried your method, and it worked. The mAPs of all classes (one class in my situation) and only the person class are the same (because there is only one class in my ground-truth). Thank you.

**Comment by noobmaster29** [comment]
Is it possible to modify the detect.py inference to only detect certain classes?

**Comment by glenn-jocher** [comment]
@noobmaster29 yes you can filter detect.py detections by classes:
```bash
python detect.py --classes 0 1 2
```
