### ISSUE TITLE
About the false positive rate and false positive reduction

### ISSUE THREAD

**Issue by ukaukaaaa** [ultralytics/yolov5#5496]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Thanks for the great project. I would like to calculate the false positive rate value and print out it. When I saw the "ap_per_class" function in /utils/metrics.py , I tried to add some lines to calculate the false positive rate value. Since that the calculation is related to the true negative samples number, but I found nothing point to this information. So I would like to ask if I could get the official code to calculate the false positive rate value.

Also, except setting the --conf parameter when testing, what else methods can be used to do the false positive reduction. When I tried to adjust the --conf, I found that when I increase the conf, the mAP will always decrease, which also is a confusing point.

**Comment by glenn-jocher** [comment]
@ukaukaaaa mAP computation is only valid near --conf 0.0. Any other value will result in pieces of your PR curve missing, and mAP is simply the area under the PR curve.

TP and FPs are computed automatically as part of AP:
https://github.com/ultralytics/yolov5/blob/ac2c49a2bb34aa4524d89d888760c0742384550f/utils/metrics.py#L54-L56

**Comment by ukaukaaaa** [comment]
@glenn-jocher Yes, I have noticed this code. But fpc is nx10, so how can I get the real false positive count from this information?

**Comment by glenn-jocher** [comment]
@ukaukaaaa fpc is nx10 because all metrics, including FPs and TPs are evaluated over 10 IoU thresholds for 0.5:0.05:0.95. What you look at is up to you.

**Comment by lizhiying-2019** [comment]
Is it this one?
`
![image](https://user-images.githubusercontent.com/75170833/141249283-bb1ed5ce-a398-45a5-9e98-f8d82f955dfe.png)
`
