### ISSUE TITLE
wandb.errors.UsageError: Error communicating with wandb process

### ISSUE THREAD

**Issue by QY1994-0919** [ultralytics/yolov5#5498]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

YOLOv5 🚀 2021-11-4 torch 1.7.1+cu110 CUDA:0 (GeForce RTX 3090, 24268.3125MB)
                                     CUDA:1 (GeForce RTX 3090, 24268.3125MB)
                                     CUDA:2 (GeForce RTX 3090, 24268.3125MB)
                                     CUDA:3 (GeForce RTX 3090, 24268.3125MB)

Namespace(adam=False, artifact_alias='latest', batch_size=300, bbox_interval=-1, bucket='', cache_images=False, cfg='models/yolov5s_VIT_VCenter.yaml', data='data/coco.yaml', device='', entity=None, epochs=300, evolve=False, exist_ok=False, global_rank=-1, hyp='data/hyp.scratch.yaml', image_weights=False, img_size=[640, 640], label_smoothing=0.0, linear_lr=False, local_rank=-1, multi_scale=False, name='exp', noautoanchor=False, nosave=False, notest=False, project='runs/train', quad=False, rect=False, resume=False, save_dir='runs/train/exp9', save_period=-1, single_cls=False, sync_bn=False, total_batch_size=300, upload_dataset=False, weights='weights/yolov5s.pt', workers=8, world_size=1)
[34m[1mtensorboard: [0mStart with 'tensorboard --logdir runs/train', view at http://localhost:6006/
[34m[1mhyperparameters: [0mlr0=0.01, lrf=0.2, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0
wandb: W&B API key is configured (use `wandb login --relogin` to force relogin)
[34m[1mgithub: [0mskipping check (not a git repository)
wandb: wandb version 0.12.6 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Network error (ReadTimeout), entering retry loop.
wandb: Network error (ConnectTimeout), entering retry loop.
wandb: ERROR Error communicating with wandb process
wandb: ERROR try: wandb.init(settings=wandb.Settings(start_method='fork'))
wandb: ERROR or:  wandb.init(settings=wandb.Settings(start_method='thread'))
wandb: ERROR For more info see: https://docs.wandb.ai/library/init#init-start-error
Problem at: /home/10102006/qy/yolov5_VIT_VCenter/yolov5_C3TR_VCenter2/utils/wandb_logging/wandb_utils.py 104 __init__
Traceback (most recent call last):
  File "train.py", line 546, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 73, in train
    wandb_logger = WandbLogger(opt, Path(opt.save_dir).stem, run_id, data_dict)
  File "/home/10102006/qy/yolov5_VIT_VCenter/yolov5_C3TR_VCenter2/utils/wandb_logging/wandb_utils.py", line 104, in __init__
    self.wandb_run = wandb.init(config=opt,
  File "/home/10102006/anaconda3/envs/torch17/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 870, in init
    run = wi.init()
  File "/home/10102006/anaconda3/envs/torch17/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 568, in init
    raise UsageError(error_message)
wandb.errors.UsageError: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error

### Environment

YOLOv5 🚀 2021-11-4 torch 1.7.1+cu110 CUDA:0 (GeForce RTX 3090, 24268.3125MB)
                                     CUDA:1 (GeForce RTX 3090, 24268.3125MB)
                                     CUDA:2 (GeForce RTX 3090, 24268.3125MB)
                                     CUDA:3 (GeForce RTX 3090, 24268.3125MB)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@QY1994-0919 hi thanks for the bug report! Yes this seems like a wandb bug. @AyushExel can you take a look please? Thanks!

**Comment by QY1994-0919** [comment]
@glenn-jocher @AyushExel   Hello, thank you for your reply. Now I am anxious to solve this problem. I am also looking for some solutions to this problem, please kindly give me some solutions, thank you

**Comment by AyushExel** [comment]
Hi @QY1994-0919 . Sorry for the late reply. Are you still seeing this issue? Is it reproducible for you every time?

**Comment by QY1994-0919** [comment]
@AyushExel    Hello, I rechecked the code and put it back on the cluster for training. The following error is reported。
OLOv5 🚀 2021-11-4 torch 1.7.1+cu110 CUDA:0 (A10, 22731.875MB)

Namespace(adam=False, artifact_alias='latest', batch_size=64, bbox_interval=-1, bucket='', cache_images=False, cfg='models/yolov5s_VIT_VCenter.yaml', data='data/coco.yaml', device='', entity=None, epochs=300, evolve=False, exist_ok=False, global_rank=-1, hyp='data/hyp.scratch.yaml', image_weights=False, img_size=[640, 640], label_smoothing=0.0, linear_lr=False, local_rank=-1, multi_scale=False, name='exp', noautoanchor=False, nosave=False, notest=False, project='runs/train', quad=False, rect=False, resume=False, save_dir='runs/train/exp9', save_period=-1, single_cls=False, sync_bn=False, total_batch_size=64, upload_dataset=False, weights='weights/yolov5s.pt', workers=8, world_size=1)
[34m[1mtensorboard: [0mStart with 'tensorboard --logdir runs/train', view at http://localhost:6006/
[34m[1mhyperparameters: [0mlr0=0.01, lrf=0.2, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0
wandb: W&B API key is configured (use `wandb login --relogin` to force relogin)
[34m[1mgithub: [0mskipping check (not a git repository)
wandb: Network error (ConnectTimeout), entering retry loop.
wandb: ERROR Error communicating with wandb process
wandb: ERROR try: wandb.init(settings=wandb.Settings(start_method='fork'))
wandb: ERROR or:  wandb.init(settings=wandb.Settings(start_method='thread'))
wandb: ERROR For more info see: https://docs.wandb.ai/library/init#init-start-error
Problem at: /home/10102006/qy/yolov5_VIT_VCenter/yolov5_C3TR_VCenter2/utils/wandb_logging/wandb_utils.py 104 __init__
Traceback (most recent call last):
  File "train.py", line 546, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 73, in train
    wandb_logger = WandbLogger(opt, Path(opt.save_dir).stem, run_id, data_dict)
  File "/home/10102006/qy/yolov5_VIT_VCenter/yolov5_C3TR_VCenter2/utils/wandb_logging/wandb_utils.py", line 104, in __init__
    self.wandb_run = wandb.init(config=opt,
  File "/home/10102006/anaconda3/envs/torch17/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 870, in init
    run = wi.init()
  File "/home/10102006/anaconda3/envs/torch17/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 568, in init
    raise UsageError(error_message)
wandb.errors.UsageError: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error

**Comment by AyushExel** [comment]
Okay thanks.. I'll get back to you today

**Comment by AyushExel** [comment]
@QY1994-0919 can you check if you have internet access on your instance? The error seems to occur because wandb can't connect to the server. 
Alternatively, if you have trouble with internet access on your instance, you can run these experiments in offline mode and later sync them to the cloud. Follow these steps.
* run `wandb offline` in your terminal to run an experiment in offline mode
* run the training job as usual
* run `wandb sync` to sync your runs to the cloud once you have internet access

Let me know if this helps or you're still facing some issues

**Comment by dacian7** [comment]
> * un `wandb sync` to sync your runs to the cloud once you have internet

@AyushExel yes. It helps. I just wonder why it does not work with the online mode LOL

**Comment by glenn-jocher** [comment]
@daiqing7 glad to hear it helped! 

Regarding the issue with the online mode, it could be due to various reasons like firewall, network issues, or even just some temporary server issue. It's not uncommon for API keys to expire or for the server to be under maintenance. In any case, if you face this issue frequently, it might be a good idea to contact the WandB support team for assistance.
