### ISSUE TITLE
No Attribute 'recompute_scale_factor' on Detect/Train

### ISSUE THREAD

**Issue by davidamacey** [ultralytics/yolov5#5499]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training, Detection

### Bug

Attempted to detect or train on Ubuntu 20.04 with all requirements installed and nightly pytorch installed for my gpu/cuda version.  

I have rebuilt multiple venvs with fresh clone of YOLOv5 repo and packages reinstalled.  I continue to get this error on device 0 or cpu:

```sh
(.trainTEST) user:/mnt/nvm/data/yolov5$ python3 detect.py --source /mnt/nvm/data/yolov5/data/photos_BUCKETS-MODELT
detect: weights=yolov5s.pt, source=/mnt/nvm/data/yolov5/data/photos imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False
YOLOv5 🚀 v6.0-45-g042f02f torch 1.11.0.dev20211029+cu113 CUDA:0 (NVIDIA GeForce RTX 3080 Ti, 12051.3125MB)

Fusing layers... 
Model Summary: 213 layers, 7225885 parameters, 0 gradients
Traceback (most recent call last):
  File "detect.py", line 306, in <module>
    main(opt)
  File "detect.py", line 301, in main
    run(**vars(opt))
  File "/mnt/nvm/data/yolov5/.trainTEST/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 131, in run
    model(torch.zeros(1, 3, *imgsz).to(device).type_as(next(model.parameters())))  # run once
  File "/mnt/nvm/data/yolov5/.trainTEST/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/nvm/data/yolov5/models/yolo.py", line 127, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "/mnt/nvm/data/yolov5/models/yolo.py", line 150, in _forward_once
    x = m(x)  # run
  File "/mnt/nvm/data/yolov5/.trainTEST/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/nvm/data/yolov5/.trainTEST/lib/python3.8/site-packages/torch/nn/modules/upsampling.py", line 154, in forward
    recompute_scale_factor=self.recompute_scale_factor)
  File "/mnt/nvm/data/yolov5/.trainTEST/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor'
(.trainTEST) user:/mnt/nvm/data/yolov5$ pip uninstall torch
Found existing installation: torch 1.11.0.dev20211029+cu113
```

I used this configuration on Friday with no issues. I did a YOLO rep pull over there weekend and it now displays this error.

Any help or assistance is greatly appreciated!

### Environment

YOLOv5 🚀 v6.0-45-g042f02f torch 1.11.0.dev20211029+cu113 CUDA:0 (NVIDIA GeForce RTX 3080 Ti, 12051.3125MB) Ubunte 20.04 Python 3.8.10

### Minimal Reproducible Example

python3 detect.py --source <folder>

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@davidamacey it's possible newer versions of PyTorch have additional argument requirements on certain modules like the Upsample one you show is causing issues. Current master is passing CI on Pytorch <= 1.10.0, so I would constrain your environment to official releases of torch for safest results, i.e. selecting one of the options from https://pytorch.org/get-started/locally/

**Comment by davidamacey** [comment]
@glenn-jocher Thank you for the prompt response!  I downgraded Pytorch nightly build back to 1.10.0 as recommended and it worked, success!

I will keep these .whl files for building future venv.  I must have missed the Pytorch version limit in the docs.

Thanks again for all your hard work on YOLOv5!

**Comment by glenn-jocher** [comment]
@davidamacey good news 😃! Your original issue may now be fixed ✅ in PR #6932. This PR implements PyTorch 1.11.0 compatibility updates and resolves `AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor'` errors.

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by apiszcz** [comment]
+1, thank you for the rapid fix/update

**Comment by TheStoneSpain** [comment]
Hi there,

I am using 11.1 and still have the same problem....

  File "/home/orangel/.local/lib/python3.8/site-packages/torch/nn/modules/upsampling.py", line 154, in forward
    recompute_scale_factor=self.recompute_scale_factor)

File "/home/orangel/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor'

Thanks!

**Comment by glenn-jocher** [comment]
@TheStoneMX your YOLOv5 code is likely out of date. To update:

- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>
