### ISSUE TITLE
Question about loss

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#5500]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

@glenn-jocher 
I know that there are 3 kinds of loss in yolov5. Among them, box_loss represents the bounding box loss, and cls_loss represents the category loss, but I don't quite understand what obj_loss represents?
https://github.com/ultralytics/yolov5/blob/5866646cc8347e45c17ca1204f3e770712365f99/utils/loss.py#L98-L100

**Comment by glenn-jocher** [comment]
@Zengyf-CVer objectness output identifies the presence or lack of an object. See YOLO papers for loss details:
https://pjreddie.com/publications/

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
Thank you very much.
