### ISSUE TITLE
Is there a different method to import background images from a different directory into the train?

### ISSUE THREAD

**Issue by sarpx** [ultralytics/yolov5#5501]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is there a different method to import background images from a different directory into the train?
Because I'm constantly experimenting and my background images usually don't change at all. Re-copying them for each training is both troublesome and wastes disk.
Thank you for your interest.

**Comment by glenn-jocher** [comment]
@sarpx yes your dataset yaml can include images from any source including multiple directories:
https://github.com/ultralytics/yolov5/blob/ac2c49a2bb34aa4524d89d888760c0742384550f/data/GlobalWheat2020.yaml#L10-L26

**Comment by sarpx** [comment]
You are a king :))
