### ISSUE TITLE
TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect.

### ISSUE THREAD

**Issue by kurtsenol** [ultralytics/yolov5#5505]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

While converting "best.pt" to "best.onnx" it throws the below tracerwarning:

command used: 
`python3 export.py --weights runs/train/exp/weights/best.pt --include onnx --dynamic --opset 12`

warning:

`TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!`

### Environment

CUDA Version: 11.2
OS :  Ubuntu 18.04.5 LTS
Python: Python 3.8.12

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@kurtsenol yes this Warning is present when exporting models, but you can ignore it, warnings are not errors.
