### ISSUE TITLE
About the calculation of gpu_mem

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#5506]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

@glenn-jocher 
Where is the calculation code of gpu memory in train.py? thanks.
https://github.com/ultralytics/yolov5/blob/ac2c49a2bb34aa4524d89d888760c0742384550f/train.py#L290

**Comment by glenn-jocher** [comment]
@Zengyf-CVer console reports `torch.cuda.memory_reserved()`
https://github.com/ultralytics/yolov5/blob/ac2c49a2bb34aa4524d89d888760c0742384550f/train.py#L341

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
Thank you very much.
