### ISSUE TITLE
Input image size when inference with P6 models using PyTorch Hub

### ISSUE THREAD

**Issue by onnkeat** [ultralytics/yolov5#5507]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When using PyTorch Hub inference, the default input image size is 640pixels. However, the input size of P6 models is 1280pixels(refer table at bottom).

Let say if I run the following codeblock(using model `yolov5x6`):

```
#PyTorch Hub inference

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5x6')  # or yolov5m, yolov5l, yolov5x, custom

# Images
img = 'https://ultralytics.com/images/zidane.jpg'  

# Inference
results = model(img)

# Results
results.print() 
```

1) Since `yolov5x6` image size is 1280 pixel(refer table at bottom), will the `model()` scale any size of input image to 1280x1280 automatically but not 640x640 **?** 
(unlike calling `detect.py`, we don't need to pass `--img` argument to specify image size when calling `model()` function)

2) refer to table at bottom, is 1280 image size means the model can detect any objects that are smaller or equal to 1280 pixel **?**    Or does it means that we must resize the image to 1280x1280 manually before feeding it into the model **?**

**table**
|Model |size<br><sup>(pixels) |mAP<sup>val<br>0.5:0.95 |mAP<sup>val<br>0.5 |Speed<br><sup>CPU b1<br>(ms) |Speed<br><sup>V100 b1<br>(ms) |Speed<br><sup>V100 b32<br>(ms) |params<br><sup>(M) |FLOPs<br><sup>@640 (B)
|---                    |---  |---    |---    |---    |---    |---    |---    |---
|YOLOv5n6     |1280 |34.0   |50.7   |153    |8.1    |2.1    |3.2    |4.6
|YOLOv5s6     |1280 |44.5   |63.0   |385    |8.2    |3.6    |16.8   |12.6
|YOLOv5m6     |1280 |51.0   |69.0   |887    |11.1   |6.8    |35.7   |50.0
|YOLOv5l6     |1280 |53.6   |71.6   |1784   |15.8   |10.5   |76.8   |111.4
|YOLOv5x6<br>+ TTA|1280<br>1536 |54.7<br>**55.4** |**72.4**<br>72.3 |3136<br>- |26.2<br>- |19.4<br>- |140.7<br>- |209.8<br>-

**Comment by glenn-jocher** [comment]
@onnkeat P5 models were trained at --img 640 and can detect from 32-640 sizes, with better results at higher image sizes. 

P6 models were trained at --img 1280 and can detect from 64-1280 sizes, with better results at higher image sizes.

**Comment by glenn-jocher** [comment]
@onnkeat also default Hub inference size is 640. If you do not modify this value then the default will be used. You can modify this manually:
```python
results = model(img, size=1920)
```

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
If I use the P6 pre-training model, `--img-size` is 640, what impact will this training have?

**Comment by onnkeat** [comment]
> @onnkeat also default Hub inference size is 640. If you do not modify this value then the default will be used. You can modify this manually:
> 
> ```python
> results = model(img, size=1920)
> ```

@glenn-jocher  Is the code above means that the any input image size will be scaled to 1920, and P6 models only can detect objects of size up to 1280 ?

**Comment by glenn-jocher** [comment]
@onnkeat yes that's right. A large image may also have smaller objects in it though. You should definitely experiment with your particular use case to see what settings and models work best, i.e. by running val.py at a variety of settings.

**Comment by onnkeat** [comment]
@glenn-jocher  Thank you for all clarifications! 
I have one more doubt, let say I want to inference a set of images of different sizes, can I pass different `size` argument for each image so that resizing/scaling is prevented?

For example
```
result1 = model(img1, size=1920)   #image 1
result2 = model(img2, size=512)    #image 2
result3 = model(img3, size=1024)   #image 3
result4 = model(img4, size=480)    #image 4
result5 = model(img5, size=768)    #image 5
...... #vice versa
```

**Comment by glenn-jocher** [comment]
@onnkeat yes you can do that!

**Comment by onnkeat** [comment]
> @glenn-jocher Thank you for all clarifications! I have one more doubt, let say I want to inference a set of images of different sizes, can I pass different `size` argument for each image so that resizing/scaling is prevented?
> 
> For example
> 
> ```
> result1 = model(img1, size=1920)   #image 1
> result2 = model(img2, size=512)    #image 2
> result3 = model(img3, size=1024)   #image 3
> result4 = model(img4, size=480)    #image 4
> result5 = model(img5, size=768)    #image 5
> ...... #vice versa
> ```

Thanks for the reply. After consideration, I think that it is not a good idea to pass different `--size` argument when inference a set of images of different size because we should specify a standard image `--size` that fits the detectable object size range of model to get the best result.

**Comment by glenn-jocher** [comment]
@onnkeat resizing is handled automatically by the model at the `size` you specify, it's not something you need to to yourself.
