### ISSUE TITLE
Save date in checkpoint file

### ISSUE THREAD

**Issue by developer0hye** [ultralytics/yolov5#5513]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

If we write date in checkpoint file, we may more easily mange the version of weights file.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@developer0hye yes great suggestion! I'll take a look at the PR.
