### ISSUE TITLE
Fusing weights

### ISSUE THREAD

**Issue by Chimchar009** [ultralytics/yolov5#5515]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

is is possible to merge 2 seperate weights together or do i have to train the images again but tgt

**Comment by zhiqwang** [comment]
I guess you can use this tutorial https://docs.ultralytics.com/yolov5/tutorials/model_ensembling
