### ISSUE TITLE
About workers in train.py

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#5516]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

@glenn-jocher 
I know that the `--workers` parameter represents the maximum number of dataloader workers, but is this parameter related to the number of CPU cores or the number of GPU cores? According to what indicator should I adjust this parameter? thanks.
https://github.com/ultralytics/yolov5/blob/0155548384e90597f140560004364633430070cd/train.py#L464

**Comment by glenn-jocher** [comment]
@Zengyf-CVer `--workers` is the number of CPU cores used. If you are training DDP Multi-GPU then this is the number of CPU cores used per GPU.

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
How to know the RAM usage during training? Because I want to adjust the parameter `--workers`.

**Comment by glenn-jocher** [comment]
@Zengyf-CVer if you are on linux you can use `htop` command for example to measure usage:
![image](https://user-images.githubusercontent.com/26833433/140502477-863772e8-beef-4bef-87b6-e65fa71c97ca.png)

In MacOS you can use Activity Monitor, etc.

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
I just used htop and it feels very good, thank you very much.
