### ISSUE TITLE
Some thoughts on FPS

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#5524]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

@glenn-jocher 
For yolov5 FPS calculation, is it accurate to use `detect.py` to detect a video or to detect a picture folder? Which of these two methods is more accurate?

**Comment by glenn-jocher** [comment]
@Zengyf-CVer well, they'll both be accurate but detect.py won't be as fast as it could be because it typically runs at batch-size 1, and the fastest inference speeds will be at higher batch sizes. You can test the effect of batch size on inference speed (per image) using a hub model:

```python
import torch
import numpy as np

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Inference
_ = model(np.zeros((640, 640, 3))) # warmup
for bs in 1, 2, 4, 8, 16, 32, 64:
    imgs = [np.zeros((640, 640, 3)) for i in range(bs)]
    results = model(imgs)
    results.print()  # or .show(), .save()

YOLOv5 🚀 2021-11-5 torch 1.9.0+cu111 CUDA:0 (Tesla V100-SXM2-16GB, 16160MiB)
Speed: 7.3ms pre-process, 11.7ms inference, 0.5ms NMS per image at shape (1, 3, 640, 640)
Speed: 10.4ms pre-process, 5.8ms inference, 0.4ms NMS per image at shape (2, 3, 640, 640)
Speed: 10.5ms pre-process, 2.9ms inference, 0.3ms NMS per image at shape (4, 3, 640, 640)
Speed: 12.3ms pre-process, 1.6ms inference, 0.3ms NMS per image at shape (8, 3, 640, 640)
Speed: 11.3ms pre-process, 1.4ms inference, 0.2ms NMS per image at shape (16, 3, 640, 640)
Speed: 12.6ms pre-process, 1.3ms inference, 0.2ms NMS per image at shape (32, 3, 640, 640)
Speed: 11.8ms pre-process, 1.2ms inference, 0.2ms NMS per image at shape (64, 3, 640, 640)
```

**Comment by glenn-jocher** [comment]
@Zengyf-CVer detect.py is batched-inference capable BTW, it's just that LoadImages is not a batched dataloader.

detect.py runs fastest when running on remote video streams, as it uses our asynchronous batched dataloader LoadStreams, which is extremely fast and can run for example 32 RTPS streams in parallel for YOLOv5 realtime detection at batch-size 32.

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
I learned it, thank you very much.
