### ISSUE TITLE
Is it possible to use only one head stage for small object ?

### ISSUE THREAD

**Issue by besmaguesmi** [ultralytics/yolov5#5527]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi there!
I'm working on an object detection task for small objects, I would decrease my model architecture, I used yolov5n, but I would drop the medium/large object detection in head stage!

Here is the architecture :
`# YOLOv5 v6.0 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [32, 6, 2, 2]],  # 0-P1/2
   [-1, 1, Conv, [64, 3, 2]],  # 1-P2/4
   [-1, 1, C3, [64]],
   [-1, 1, Conv, [128, 3, 2]],  # 3-P3/8
   [-1, 3, C3, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 5-P4/16
   [-1, 6, C3, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 7-P5/32
   [-1, 1, C3, [512]],
   [-1, 1, SPPF, [512, 5]],  # 9
  ]

# YOLOv5 v6.0 head
head:
  [[-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, C3, [256, False]],  # 13

   [-1, 1, Conv, [128, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, C3, [128, False]],  # 17 (P3/8-small)

   [-1, 1, Conv, [128, 3, 2]],
   [[-1, 14], 1, Concat, [1]],  # cat head P4
   [-1, 3, C3, [128, False]],  # 20 (P4/16-medium)

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 10], 1, Concat, [1]],  # cat head P5
   [-1, 3, C3, [512, False]],  # 23 (P5/32-large)

   [[17, 20, 23], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
  ]`

Do you have any idea how can I do this? 

Thanks

**Comment by glenn-jocher** [comment]
@besmaGuesmi yes of course, you can remove unwanted outputs easily, you just delete them. For example for YOLOv5n with only P3 output is below. If you reduce outputs you may want to increase your anchor count though, i.e. maybe from 3 to 6 here.

```yaml
# Parameters
nc: 80  # number of classes
depth_multiple: 0.33  # model depth multiple
width_multiple: 0.25  # layer channel multiple
anchors: 6

# YOLOv5 v6.0 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [64, 6, 2, 2]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C3, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 6, C3, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, C3, [512]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 3, C3, [1024]],
   [-1, 1, SPPF, [1024, 5]],  # 9
  ]

# YOLOv5 v6.0 head
head:
  [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, C3, [512, False]],  # 13

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, C3, [256, False]],  # 17 (P3/8-small)

   [[17], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
  ]
```

**Comment by besmaguesmi** [comment]
Yes, yes I deleted them and it didn't work! that's why I asked

**Comment by besmaguesmi** [comment]
The problem was with anchors, now it works fine, Thank you @glenn-jocher ! I'm happy to use Yolov5 on our project. Thanks

**Comment by glenn-jocher** [comment]
@besmaGuesmi great!

**Comment by majx1997** [comment]
Hi!
I drop the large object detection in head stage, the training process works fine, but the following problems occurred When I use val.py to test the performance. Can you please tell me how to solve this error? @glenn-jocher  @besmaGuesmi 
![WX20211126-144908](https://user-images.githubusercontent.com/38154161/143538856-0edb9e0d-b7f1-4a0e-9295-18a9d1af43a8.png)

**Comment by 1160404405** [comment]
Hey, if I also keep only level 17 at the detection level but still haven't changed in the log when I run train.py, do I need to change the code somewhere else

**Comment by glenn-jocher** [comment]
@1160404405 if you only want output 17, then you can update Detect() inputs and also delete everything after layer 17, including the med and small anchors.

**Comment by 1160404405** [comment]
@glenn-jocher Thank you, but I mean only use layer 17 during training, not detect.I delete the med and small anchors, but it still exists in the output log

**Comment by glenn-jocher** [comment]
@1160404405 it's very simple:

```yaml
# YOLOv5 🚀 by Ultralytics, GPL-3.0 license

# Parameters
nc: 80  # number of classes
depth_multiple: 0.33  # model depth multiple
width_multiple: 0.50  # layer channel multiple
anchors: 3

# YOLOv5 v6.0 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [64, 6, 2, 2]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C3, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 6, C3, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, C3, [512]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 3, C3, [1024]],
   [-1, 1, SPPF, [1024, 5]],  # 9
  ]

# YOLOv5 v6.0 head
head:
  [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, C3, [512, False]],  # 13

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, C3, [256, False]],  # 17 (P3/8-small)

   [[17], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
  ]
```

**Comment by Emmanuelcnnadozie** [comment]
@glenn-jocher 
I am exploring a situation where I can output all three detection layers of YOLOv5n during training (which is the default configuration), but output only one of any of the three detection scales during inference. The idea is to be able to select, in real-time, which of the three scales to compute and output during inference.
I would appreciate your input.

**Comment by emmanuelCN** [comment]
@glenn-jocher
I am exploring a situation where I can output all three detection layers of YOLOv5n during training (which is the default configuration), but output only one of any of the three detection scales during inference. The idea is to be able to select, in real-time, which of the three scales to compute and output during inference.
I would appreciate your input.

**Comment by glenn-jocher** [comment]
@emmanuelCN what's your question?

**Comment by emmanuelCN** [comment]
> @emmanuelCN what's your question?

@glenn-jocher 
I guess I should rephrase my earlier inquiry.
I have a situation where my dataset contains a set of images with small objects, another set with medium objects, and another with large objects - in this case all objects belong to one class. I have trained YOLOv5n on the whole dataset, and I have impressive results. However, I want to save more time during inference by reducing the computation time. So I came across this paper, https://link.springer.com/article/10.1007/s00521-021-05764-7#:~:text=After%20applying%20the%20discarding%20technique,improvement%20of%2048.7%25%20in%20speed.
And was wondering if I could implement something similar using YOLOv5.

So, can I modify the detect.py to detect only small objects, or only medium objects, or only large objects for any given inference image?

NB -  I am still fairly new to object detection, and my apologies if I don't "speak" object detection fluently

**Comment by glenn-jocher** [comment]
@emmanuelCN I can't really answer your question since I don't know any specifics of what your constraints are (time, budget, risk tolerance, dataset size, deployment space etc.). In general YOLOv5 has multiple output heads for detecting different size objects, which is exactly your use case, so I don't understand the strategy. You can remove heads if you want at your own risk, in general you might encounter cost savings with accuracy losses, the same compromise as any change to the model. 

Simply not passing inputs to Detect() is one option, but the FLOPs savings there are insignificant, and in the PANet head YOLOv5 uses large output layers like P5 depend on earlier smaller output layers like P3, P4 that are downscaled. 

The most obvious route, especially for a non specialist is simply to use a faster model, i.e. YOLOv5n, or a smaller image size etc.

**Comment by emmanuelCN** [comment]
@glenn-jocher 
Thank you for your reply.
I have already tried different image sizes, as well as tried the n and s models.
I guess I will remove heads and compare the performance costs.

**Comment by Nxthing71** [comment]
I try to remove the head. It works on training. but why it cant work in validation when I run val.py?

**Comment by glenn-jocher** [comment]
@Nxthing71 Removing head segments for training without adjusting the validation process correspondingly might cause inconsistencies, as the validation step expects the same model structure for accurate performance evaluation. Ensure your `val.py` is aware of the modifications you've made to the model's architecture. This usually involves tweaking the model loading or inference sections to align with your changes. A common adjustment could be to modify the detection layer references or the expected number of outputs. Remember to keep your alterations consistent across both training and validation scripts for smooth operation. 🙂
