### ISSUE TITLE
Model Weight Retraining with Class Changing

### ISSUE THREAD

**Issue by aseprohman** [ultralytics/yolov5#5529]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello @glenn-jocher  et all,

is it possible if the process of retraining the model with the number of classes that change in next time ? For example, due to the development of data, the model class which was originally 20 variants then needs to grow to 50 variants. do I have to retrain all the data from the beginning again? Or can I do the training process with the new data by increasing the number of classes in config and using the model that has been trained for 20 classes ? thanks

**Comment by glenn-jocher** [comment]
@aseprohman yes YOLOv5 can start training any dataset from a model previously trained on any other dataset, i.e. train VOC (10 classes) from a COCO (60 classes) yolov5s.pt model. This is a default use case, nothing special is required:

```bash
python train.py --weights yolov5s.pt --data VOC.yaml
```

**Comment by Anas-Alshaghouri** [comment]
> ### Search before asking
> 
>     * [x]  I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.
> 
> 
> ### Question
> 
> Hello @glenn-jocher et all,
> 
> is it possible if the process of retraining the model with the number of classes that change in next time ? For example, due to the development of data, the model class which was originally 20 variants then needs to grow to 50 variants. do I have to retrain all the data from the beginning again? Or can I do the training process with the new data by increasing the number of classes in config and using the model that has been trained for 20 classes ? thanks
> ### Additional
> 
> _No response_

Did you find any useful help?!

**Comment by Anas-Alshaghouri** [comment]
> @aseprohman yes YOLOv5 can start training any dataset from a model previously trained on any other dataset, i.e. train VOC (10 classes) from a COCO (60 classes) yolov5s.pt model. This is a default use case, nothing special is required:
> 
> ```shell
> python train.py --weights yolov5s.pt --data VOC.yaml
> ```

I know there are tons of previous similar asked question, but the only thing that still confusing me about retraining is:
Shall I include the images I already use for my first custom training, in another custom training that aims to include more classes or add new images to certain class.
Just answer me by Yes or No.
Thank you in advance.
@glenn-jocher

**Comment by glenn-jocher** [comment]
@Anas-Alshaghouri the best thread on multi-dataset training/retraining is here: https://community.ultralytics.com/t/how-to-combine-weights-to-detect-from-multiple-datasets/38

**Comment by Anas-Alshaghouri** [comment]
Thank you @glenn-jocher , it is a useful source
