### ISSUE TITLE
Why inference times vary with the same images?

### ISSUE THREAD

**Issue by foge1993** [ultralytics/yolov5#5530]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I test a image 25 times. the times vary from 30ms to 160ms. I think the vary should be very small in the condition testing a image 25 times.
![image](https://user-images.githubusercontent.com/37509794/140592272-a9500d53-c294-47af-8dc1-a0d6e86c851e.png)

**Comment by Zengyf-CVer** [comment]
@foge1993 
If there are too few pictures, different results will appear. Try to enlarge the number of pictures, hundreds or thousands, and you will get similar results.

**Comment by foge1993** [comment]
> @foge1993 If there are too few pictures, different results will appear. Try to enlarge the number of pictures, hundreds or thousands, and you will get similar results.
To enlarge the number of picture is also vary in testing a images 500 times. the vary occur in the NMS stage.
