### ISSUE TITLE
How to get the AP75 APs APM APL?

### ISSUE THREAD

**Issue by Zhiying-Li-dot** [ultralytics/yolov5#5531]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I obtain map0.5 and map0.5:0.95 when running the val.py.How to get other metrics like AP75、APs、APm、APL?Looking forward to your reply.

**Comment by glenn-jocher** [comment]
@lizhiying-2019 s m l are pycocotools-only metrics. You can obtain any of the 10 threshold values 0:5:0.05:0.95 directly in the val.py code:
https://github.com/ultralytics/yolov5/blob/60e42e16c2bc51b303e680afccd72351af7a7a69/val.py#L237

**Comment by Zhiying-Li-dot** [comment]
@glenn-jocher Thank you for letting me learn a lot. I got it.
