### ISSUE TITLE
small objects

### ISSUE THREAD

**Issue by zwhua006** [ultralytics/yolov5#5534]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Now, I want to strengthen the recognition of small objects. I saw yolov5 p2, but I feel that there are too many layers. I want to know how to use p2 while ensuring that the parameters and the size of the model are similar to the original yolov5s. I don't know how to directly change to p2,3,4 instead of p 3,4,5. thanks

**Comment by glenn-jocher** [comment]
@zwhua006 removing large outputs is easy, you just delete them and their anchors from a yaml. Nothing else required. I'll update the yamls in the data/directory to bring them up to date with the current v6.0 release.

**Comment by glenn-jocher** [comment]
@zwhua006 good news 😃! All yamls in models/hub are now updated to v6.0 ✅ release architectures in PR #5540. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by glenn-jocher** [comment]
@zwhua006 to remove P5 layer from `yolov5-p2.yaml` for example:

<img width="1371" alt="Screenshot 2021-11-06 at 15 11 36" src="https://user-images.githubusercontent.com/26833433/140612681-688357a7-489b-4ca9-add1-9da497b09151.png">

**Comment by zwhua006** [comment]
thanks,But I'm thinking if I do this, then what is the meaning of P5？

**Comment by glenn-jocher** [comment]
@zwhua006 P5 is a stride 64 large output layer. It's purpose is to detect large objects.

**Comment by abfleishman** [comment]
@glenn-jocher if making this change, is there any reason to pare down the backbone or anchors section of the YAML?  for instance if all the objects in the images are <128 or px<256 px (max edge length)?

**Comment by glenn-jocher** [comment]
@abfleishman before doing anything I would recommend training with default models.
