### ISSUE TITLE
maximum number of dataloader workers

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#5537]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to define the number?
Does it use the htop to see the number?

![image](https://user-images.githubusercontent.com/59388989/140608391-0cb72bbd-c6e5-40d5-b3b0-8dc38660ec70.png)

**Comment by glenn-jocher** [comment]
@alicera yes we check system resources when creating workers, so in your case your dataloader workers would be capped at 4.
https://github.com/ultralytics/yolov5/blob/60e42e16c2bc51b303e680afccd72351af7a7a69/utils/datasets.py#L38

**Comment by alicera** [comment]
Can it more than 8 if my htop number have 15?
Can I fix the number of multiprocessing threads to 15?
![image](https://user-images.githubusercontent.com/59388989/140674447-180b3a21-7aa8-4259-b84b-fe1abf4ac420.png)

**Comment by glenn-jocher** [comment]
@alicera yes you can adjust your dataloader workers with the `--workers` argument:
```bash
python train.py --workers 20
```
