### ISSUE TITLE
Custom Data Training and Inference

### ISSUE THREAD

**Issue by buimanhlinh96** [ultralytics/yolov5#554]
Hello everyone, i met a problem when i train my custom data. When i train my custom data (1920x1080) and coco data seperately, it's oke. But when i mix my custom data with coco data it's error. It likes "shape '[1, 3, 85, 64, 64]' is invalid for input of size 1048576" when input = 512. Sometimes, it even out of memory.!
Can you explain it for me?
Thank you!

**Comment by glenn-jocher** [comment]
You can train multiple datasets at the same time provided they share the exact same classes. You simply aggregate them in your data.yaml:
https://github.com/ultralytics/yolov5/blob/1df494e5fea4102a64042587a6d7434a11919a08/data/coco128.yaml#L10-L13
