### ISSUE TITLE
Yolov5 last version - architecture explanation

### ISSUE THREAD

**Issue by besmaguesmi** [ultralytics/yolov5#5541]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi! I'm trying to understand how the last Yolo version works layer by layer from backbone to detect, currently, I'm using Yolov5n as my model, unfortunately, until now I didn't find any paper to help me to understand more the architecture, all the guides talked only about the function of each part but they didn't explain how the architecture work layer by layer and the function of each layer! Does any help please to understand all the architectural details?
Thanks.

**Comment by glenn-jocher** [comment]
@besmaGuesmi yes I'm sorry we don't have a publication out yet, but the best place to start learning is to read the first 3 YOLO papers for v1-v3 by Redmon here:
https://pjreddie.com/publications/

**Comment by besmaguesmi** [comment]
Hi @glenn-jocher thank you for your reply! where can I find the internal architecture of C3/SPPF of Yolov5n? I really need to understand it! Thanks

**Comment by glenn-jocher** [comment]
@besmaGuesmi SPPF was introduced in v6.0 and is simply a faster (i.e. better implemented, eliminates redundant ops) version of SPP, the outputs are mathematically identical. See PR https://github.com/ultralytics/yolov5/pull/4420

C3 was introduced in v4.0, it is an CSPBottleneck() layer with one of the 4 main convolutions removed, i.e. hence the name '3', bringing additional architecture simplification. See https://github.com/ultralytics/yolov5/tree/v4.0

**Comment by besmaguesmi** [comment]
Thank you!

**Comment by besmaguesmi** [comment]
Hi, @glenn-jocher I designed this architecture as SPPF according to the link that you sent me, I would check with you if there are any missing details. Thanks
![SSPF architecture](https://user-images.githubusercontent.com/36562278/140623371-08acf7b8-da35-41c5-8202-6d7e5b8cc703.png)

**Comment by glenn-jocher** [comment]
@besmaGuesmi yes that seems correct. You can also visualize individual modules with TensorBoard once you start training. This is SPPF:

<img width="1608" alt="Screenshot 2021-11-07 at 00 09 23" src="https://user-images.githubusercontent.com/26833433/140626404-98638c15-f0e0-48cf-badf-a491c8daea8b.png">

**Comment by glenn-jocher** [comment]
@besmaGuesmi a second option for module visualization is ONNX. You can export a module and visualize it with Netron:

```python
import torch
from models.common import SPPF

torch.onnx.export(model=SPPF(128,128,5), args=torch.zeros(1,128,80,80), f='SPPF.onnx')
```

<img width="1015" alt="Screenshot 2021-11-07 at 00 15 48" src="https://user-images.githubusercontent.com/26833433/140626555-d628b6a9-e373-4c27-b189-4efbda2ecda3.png">

**Comment by besmaguesmi** [comment]
Great! Thank you @glenn-jocher
