### ISSUE TITLE
Question about how obj loss is calculated

### ISSUE THREAD

**Issue by Stanleyluuuu** [ultralytics/yolov5#5547]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Currently, I'm trying to add negative samples into training data while training on my dataset and realized that negative samples only calculate object loss. I'm wondering how the object loss is calculated? Is it calculated depending on the class? Because I don't want the model to get updated for some class on negative samples.

Another question is, what does pi[..., 4] mean? Is it the output feature map of the model? While there are 80 classes in my data, the shape of pi[..., 4] is (n, 3, 80, 80), I tried to change the number of classes to other numbers and the output shape remains (n, 3, 80, 80).

`obji = self.BCEobj(pi[..., 4], tobj)`

**Comment by glenn-jocher** [comment]
@Stanleyluuuu yes YOLO uses 3 loss components: box, class, objectness. Objectness determines whether an object exists at an anchor. I'd recommend you read about these losses in the first 3 YOLOv3 papers by Redmon:
https://pjreddie.com/publications/

**Comment by glenn-jocher** [comment]
@Stanleyluuuu also `pi` is the predicted objectness grid at output layer `i`. It's shape is only dependent on the input image shape, not the number of classes.
