### ISSUE TITLE
Hyperparameter evolution results

### ISSUE THREAD

**Issue by myasser63** [ultralytics/yolov5#5554]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have ran --evolve on YOLOv5s custom model with weights `best.pt`. 

Custom model training command line for obtaining `best.pt`:

`!python train.py --img 640 --batch 16 --epochs 200 --data '/content/data.yaml' --cfg /content/yolov5/models/yolov5s.yaml --weights yolov5s.pt  --cache`

Evolve training command line:

`!python train.py --img 640 --batch 16 --epochs 10 --data '/content/data.yaml' --cfg /content/yolov5/models/yolov5s.yaml --weights /content/yolov5/runs/train/exp/weights/best.pt  --cache --evolve`

The results from the evolution is showing the graphs for mAP as shown is the figure below. From what I have seen from the live example in [hyperparameters evolution tutortial](https://wandb.ai/cayush/yolo_coco128_sweep/sweeps/gn0iv92v?workspace=user-cayush) my results doesn't look right. 

@glenn-jocher  Could you please look at  my results and tell me what is cauing the results to look like that.

![image](https://user-images.githubusercontent.com/49511207/140675612-5b879700-d45f-4dc4-9c28-6156abb9e641.png)

**Comment by yaoshanliang** [comment]
The same question.

**Comment by glenn-jocher** [comment]
@myasser63 @yaoshanliang hi thanks for asking about your evolution results! If you are running YOLOv5 hyperparameter evolution, these can be tracked by W&B but the main output is an **evolve.csv file** with your results, and once training completes also an **evolve.jpg** plotting your results.

If you are running W&B sweeps, which are different, and have questions there, you can ask our W&B expert @AyushExel

**Comment by myasser63** [comment]
@glenn-jocher thanks for your answer. However, I am asking about the metrics graphs are these unusual shape as the example provided in the tutorial. Is there a reson for this results?

**Comment by myasser63** [comment]
@glenn-jocher I have ran my model to `--evolve` for over 400 generations but the hyp-evolve.yaml wasn't updated to show all the generations.  `evolve.csv` only contains 34 generation

The results at the end of the evolution showed different values from the values in `hyp-evolve.yaml`.

`hyp-evolve.yaml`
![image](https://user-images.githubusercontent.com/49511207/140854573-69bcc5b5-cd8d-49ce-b839-4bff7623ccc4.png)

Results at the end of the evolution
![image](https://user-images.githubusercontent.com/49511207/140854430-b3205d9d-8bf3-4ce8-b08e-4f5ed945e9eb.png)


![d6a54d11-f26f-4e78-90a4-dd51920ee838](https://user-images.githubusercontent.com/49511207/140854227-e4469bd8-485b-4c30-a025-b1db71b44649.png)

**Comment by AyushExel** [comment]
@myasser63 regarding the W&B plots - you're seeing the evolution plots which are different from W&B sweep plot. To try out the sweeps read the section https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution . For further info and customizations available for sweeps, here W&B docs [here](https://docs.wandb.ai/guides/sweeps)

**Comment by glenn-jocher** [comment]
@myasser63 in your screenshots it shows you've evolved about 34 generations. If your evolution was interrupted or terminated early, you can resume where you left off.

Resuming YOLOv5 🚀 evolution is a bit different than resuming a normal training run with `python train.py --resume`. If you started an evolution run which was interrupted, or finished normally, and you would like to continue for additional generations where you left off, then you pass `--resume` and specify the `--name` of the evolution you want to resume, i.e.:


## Start Evolution

Assume you evolve YOLOv5s on COCO128 for 2 epochs for 3 generations:
```shell
python train.py --epochs 10 --data coco128.yaml --weights yolov5s.pt --evolve 3
```
If this is your first evolution a new directory `runs/evolve/exp` will be created to save your results.
```shell
# ├── yolov5
#     └── runs
#         └── evolve
#             └── exp  ← evolution saved here
```

## Start a Second Evolution

Now assume you want to start a completely separate evolution: YOLOv5s on VOC for 5 epochs for 3 generations. You simply start evolving, and your new evolution will again be logged to a new directory `runs/evolve/exp2`:
```shell
python train.py --epochs 5 --data VOC.yaml --weights yolov5s.pt --evolve 3
```

You will now have two evolution runs saved:
```shell
# ├── yolov5
#     └── runs
#         └── evolve
#             ├── exp  ← first evolution (COCO128)
#             └── exp2  ← second evolution (VOC)
```

Notebook example: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
<img width="1396" alt="Screenshot 2021-09-15 at 12 23 13" src="https://user-images.githubusercontent.com/26833433/133416922-59a3e9f5-2630-4875-9c64-a982e312b400.png">


## Resume an Evolution

If you want to resume the first evolution (COCO128 saved to `runs/evolve/exp`), then you use the same exact command you started with plus `--resume --name exp`, passing the **additional** number of generations you want, i.e. `--evolve 30` for 30 more generations:
```shell
python train.py --epochs 10 --data coco128.yaml --weights yolov5s.pt --evolve 30 --resume --name exp
```
Evolution will run for an additional 30 generations and all new results will be added to the existing `runs/evolve/exp/evolve.csv`. 

Good luck and let us know if you have any other questions!

**Comment by myasser63** [comment]
@glenn-jocher @AyushExel Thanks alot for your reply

**Comment by bit-scientist** [comment]
If I want to evolve hyperparameters for my custom dataset with 3 classes, do I still have to start it with `--weights yolov5s.pt`? As it is based on COCO, and not my custom dataset, what weights should I use instead? Thanks.

**Comment by glenn-jocher** [comment]
@bit-scientist you choose your own scenario to evolve.

**Comment by seyeonseanpark** [comment]
Hello @glenn-jocher!
I have just one question. Is it recommended to run evolutions with a custom model with the best.pt or with the default weights?

**Comment by glenn-jocher** [comment]
@seyeonseanpark evolution scenario is up to you, there's no right answer.
