### ISSUE TITLE
Crops folder does not have cropped images

### ISSUE THREAD

**Issue by alucor-it** [ultralytics/yolov5#5555]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,
I have trained yolov5 to detect 3 objects and only one object appears per image. I have included --save-crop parameter while running detect.py. But I get empty sub folders instead of cropped images in the "crops" folder. Do I have to change any other parameter to get the cropped images?

Thanks

**Comment by glenn-jocher** [comment]
@alucor-it we had a recent fix to crops. Please git pull or git clone and try again.

**Comment by alucor-it** [comment]
Yes, it's working now. Thank you.
