### ISSUE TITLE
How to detect only CAR class using orginal model using torch.hub.

### ISSUE THREAD

**Issue by mohammad69h94** [ultralytics/yolov5#5558]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to detect only CAR class using torch.hub.
For example, when I set classes=10, Nothing is detected
I don't use custome model and I use your original model as follow:

model = torch.hub.load('ultralytics/yolov5', 'yolov5s', classes=10, pretrained=True)

### Additional

![Capture1](https://user-images.githubusercontent.com/38998372/140700248-ab7972fd-4532-4e2a-9ef4-4da4de45ce75.PNG)

**Comment by glenn-jocher** [comment]
@mohammad69h94 you've created a new YOLOv5 model with 10 output classes (last layer randomly initialized), so not detecting anything is the expected result.

You can modify model attributes prior to inference by following the [PyTorch Hub tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) examples:

<img width="801" alt="Screenshot 2021-11-08 at 11 39 35" src="https://user-images.githubusercontent.com/26833433/140727804-b78d8522-e920-4eb8-bc0b-90ebad018c55.png">
