### ISSUE TITLE
Custom naming of results images with bounding boxes

### ISSUE THREAD

**Issue by iou84** [ultralytics/yolov5#5564]
Hello everyone 
Is there a way to give custom namings to result image with bounding boxes with the results.save command? 
Or at least copy that image to a new variable and save that??

**Comment by glenn-jocher** [comment]
@iou84 you can define a custom save directory with `results.save(save_dir='path/to/save')`

You can also render predictions onto images and then do whatever you want with the imgs numpy arrays:
```python
results.render()  # plot results onto imgs
results.imgs # imgs numpy arrays
```
