### ISSUE TITLE
Image Dimension in Weights

### ISSUE THREAD

**Issue by aseprohman** [ultralytics/yolov5#5565]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello @glenn-jocher et all,

Does yolov5 model save image dimension data in weights model ? 
If I do first training with 300 epoch with imgsz 544 until finished and I do second training for new data with imgsz 640, is it possible to do or I should to do with same imgsz parameter ? thanks

**Comment by glenn-jocher** [comment]
@aseprohman sure, anything is possible. One of the main purposes behind YOLOv5 is that we make it super easy for  everyone to run experiments like what you just described.

**Comment by glenn-jocher** [comment]
@aseprohman BTW if you're asking me if you should do something or other, probably just do it both ways so you can learn the effects on your custom task.

**Comment by aseprohman** [comment]
owh yes I will try it.
thanks
