### ISSUE TITLE
what is the input and the out node names in tensorflow model?

### ISSUE THREAD

**Issue by muhammedakyuzlu** [ultralytics/yolov5#5572]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm trying to run the model.pb in c++ code for that I need the input and the output node names.
I think it is `inputs="x:0", outputs="Identity:0"` but I'm not sure.

**Comment by glenn-jocher** [comment]
@muhammedakyuzlu you can try visualizing exported models with Netron viewer.

**Comment by muhammedakyuzlu** [comment]
It is x and Identity
