### ISSUE TITLE
Save crops of inference in order of occurrence over the x-axis

### ISSUE THREAD

**Issue by Fritskee** [ultralytics/yolov5#5573]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When using `python detect.py --weights yolo5l.onnx --source <my_image.png> --save-crop` I get a folder with the cropped objects perfectly. 

However, the order of how the objects occur in the image (which is always over the x-axis) is of utmost important to me. What I noticed is that the naming of the files (and thus the order) are rather random order. Is there a way to have the filenames increment, depending on how the objects occur in the image?

As an example: the most left crop would be <file_name>_0.jpg and the most right crop would be <file_name>_09.jpg

**Comment by glenn-jocher** [comment]
@Fritskee crops are ordered by confidence, but you can insert your own sorting logic on L384 here:
https://github.com/ultralytics/yolov5/blob/79bca2bf64da04e7e1e74a132eb54171f41638cc/models/common.py#L384-L389

You can also return crops and handle them however you'd like:
```python
crops = results.crop()
```

**Comment by Fritskee** [comment]
> @Fritskee crops are ordered by confidence, but you can insert your own sorting logic on L384 here:
> 
> https://github.com/ultralytics/yolov5/blob/79bca2bf64da04e7e1e74a132eb54171f41638cc/models/common.py#L384-L389
> 
> You can also return crops and handle them however you'd like:
> 
> ```python
> crops = results.crop()
> ```

That's amazing! Thanks so much for the help!!
