### ISSUE TITLE
Trouble exporting to coreml. ONNX & Torchscript export working fine.

### ISSUE THREAD

**Issue by UnkoC0wbOy** [ultralytics/yolov5#5575]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

![Image 11-8-21 at 2 48 PM](https://user-images.githubusercontent.com/89663444/140823789-4998334b-03f7-4c7e-b9ad-54a50b8fd335.jpg)

![Image 11-8-21 at 2 50 PM](https://user-images.githubusercontent.com/89663444/140823815-94e6083c-b161-4bf2-bbce-7d08f1a5381d.jpg)

![Image 11-8-21 at 2 38 PM](https://user-images.githubusercontent.com/89663444/140822361-9dee3c2e-b712-4cf5-bd5a-b039db25b76b.jpg)

![Image 11-8-21 at 2 52 PM](https://user-images.githubusercontent.com/89663444/140824051-06d56d8c-c055-42dd-b135-7d36e943af9b.jpg)

### Environment

Running in Google Colab and on device (2014 Mac mini) having same issue.
YOLOv5 🚀 v6.0-76-g79bca2b torch 1.9.0+cu111 CPU

### Minimal Reproducible Example

! git clone https://github.com/ultralytics/yolov5
! cd yolov5
! pip install -r /content/yolov5/requirements.txt
! pip install -U coremltools==5.0 onnx scikit-learn==0.20.0
! pip install torch
! python /content/yolov5/export.py --weights yolov5s.pt --img 640 --batch 1 

### Additional

Cannot export model to coreml format.  Having no issues exporting model to onnx or TorchScript.pt format

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@UnkoC0wbOy if you want to export to coreml you can include it in the list of formats to export to:
```
python export.py --include coreml
```

See argparser for details:
https://github.com/ultralytics/yolov5/blob/79bca2bf64da04e7e1e74a132eb54171f41638cc/export.py#L352-L354

**Comment by mareczech1982** [comment]
@UnkoC0wbOy, Im not sure how CoreML works with an intel mac. Wit my silicon M1 pro I have to use Conda for installing all the dependencies. 

Good start is here: 
https://towardsdatascience.com/yes-you-can-run-pytorch-natively-on-m1-macbooks-and-heres-how-35d2eaa07a83
and here:
https://coremltools.readme.io/docs 

@glenn-jocher I can export the way you propose, but I when I run the detection:
`python detect.py --weights yolov5s.mlmodel`

 I get following error:
 File "foo_bar/yolov5/models/common.py", line 363, in forward
    box = xywh2xyxy(y['coordinates'] * [[w, h, w, h]])  # xyxy pixels

It seems that the model output does not have the key coordinates. The result has these following keys: 
dict_keys(['var_875', 'var_860', 'var_845'])

torch version:  1.8.0.post3
torchvision version:  0.9.0a0
numpy version:  1.21.1
coremltools version:  5.1.0
Python 3.9.7

**Comment by glenn-jocher** [comment]
@UnkoC0wbOy @mareczech1982 good news 😃! Your original issue may now be fixed ✅ in PR #6195. This PR adds support for YOLOv5 CoreML inference.

```python
!python export.py --weights yolov5s.pt --include coreml  # CoreML export
!python detect.py --weights yolov5s.mlmodel  # CoreML inference (MacOS-only)
!python val.py --weights yolov5s.mlmodel  # CoreML validation (MacOS-only)

model = torch.hub.load('ultralytics/yolov5', 'custom', 'yolov5s.mlmodel')  # CoreML PyTorch Hub model
```

<img width="1360" alt="Screen Shot 2022-01-04 at 5 41 07 PM" src="https://user-images.githubusercontent.com/26833433/148147262-1527cccc-19ca-43c4-b50a-c9a81cfd0bb5.png">

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by zhaoqier** [comment]
> @UnkoC0wbOy, Im not sure how CoreML works with an intel mac. Wit my silicon M1 pro I have to use Conda for installing all the dependencies.
> 
> Good start is here: https://towardsdatascience.com/yes-you-can-run-pytorch-natively-on-m1-macbooks-and-heres-how-35d2eaa07a83 and here: https://coremltools.readme.io/docs
> 
> @glenn-jocher I can export the way you propose, but I when I run the detection: `python detect.py --weights yolov5s.mlmodel`
> 
> I get following error: File "foo_bar/yolov5/models/common.py", line 363, in forward box = xywh2xyxy(y['coordinates'] * [[w, h, w, h]]) # xyxy pixels
> 
> It seems that the model output does not have the key coordinates. The result has these following keys: dict_keys(['var_875', 'var_860', 'var_845'])
> 
> torch version: 1.8.0.post3 torchvision version: 0.9.0a0 numpy version: 1.21.1 coremltools version: 5.1.0 Python 3.9.7

@mareczech1982 hi, have you solved this problem, I met the this error now when I use the .mlmodel to detect, it says the coordinated error. @glenn-jocher could you please help me with it?

Traceback (most recent call last):
  File "/Users/qierzhao/yolov3/detect.py", line 244, in <module>
    main(opt)
  File "/Users/qierzhao/yolov3/detect.py", line 239, in main
    run(**vars(opt))
  File "/Users/qierzhao/opt/anaconda3/envs/yolov3/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/Users/qierzhao/yolov3/detect.py", line 115, in run
    pred = model(im, augment=augment, visualize=visualize)
  File "/Users/qierzhao/opt/anaconda3/envs/yolov3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/qierzhao/yolov3/models/common.py", line 364, in forward
    box = xywh2xyxy(y['coordinates'] * [[w, h, w, h]])  # xyxy pixels
KeyError: 'coordinates'

Thanks

**Comment by glenn-jocher** [comment]
@zhaoqier the issue you are experiencing with the CoreML model likely stems from an inconsistency in the model output keys. Specifically, the error message `KeyError: 'coordinates'` indicates that the 'coordinates' key is missing from the model's output. 

To resolve this issue, you can modify the model's output to ensure it matches the expected format. 

In the meantime, make sure to use the latest YOLOv5 version from the [official GitHub repository](https://github.com/ultralytics/yolov5) to ensure you have the most up-to-date fixes and improvements.

If you encounter any further difficulties, feel free to reach out for more assistance.
