### ISSUE TITLE
yolov5-6.0 export onnx quite well,so How to add nms to onnx?

### ISSUE THREAD

**Issue by futureflsl** [ultralytics/yolov5#5577]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

yolov5-6.0 export onnx quite well,but output shape is [1,25200,85].this means onnx can not contain nms.so how to add nms to onnx?

**Comment by glenn-jocher** [comment]
@futureflsl you can run onnx inference directly with detect.py, which provides pytorch nms:
```bash
python detect.py --weights yolov5s.onnx
```

**Comment by futureflsl** [comment]
> @futureflsl you can run onnx inference directly with detect.py, which provides pytorch nms:
> 
> ```shell
> python detect.py --weights yolov5s.onnx
> ```

I want to add nms to yolov5 export onnx output layer,How can I do it?

**Comment by zhiqwang** [comment]
Hi @futureflsl I’ve done some experiments about exporting the `nms` into the ONNX graph [here](https://zhiqwang.com/yolov5-rt-stack/notebooks/export-onnx-inference-onnxruntime.html) before, maybe this can set as a reference.
