### ISSUE TITLE
What is the difference between evolution id  and generation in Hyperparameter Evolution

### ISSUE THREAD

**Issue by yaoshanliang** [ultralytics/yolov5#5578]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When i am using Hyperparameter Evolution, the result in hyp_evolve.yaml shows that 

    # YOLOv5 Hyperparameter Evolution Results
    # Best generation: 15
    # Last generation: 18
. I am confused that my evolution id has already gone to 300+ in wandb.ai

Does the generation represent the time of evolution? If so, the last generation should be more that 300 in the results.

**Comment by glenn-jocher** [comment]
@yaoshanliang generation is generation. If you, your dad and your grandfather live in the same house that's 3 generations. Same for YOLO evolution.
