### ISSUE TITLE
Two Successive Linear Layer is same with one linear layer.

### ISSUE THREAD

**Issue by developer0hye** [ultralytics/yolov5#5580]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi!, @glenn-jocher and @dingyiwei !

I am trying to improve the performance of object detection model with transformer layer. And I found that @dingyiwei already experimented it on this project.

I have one question about your method.

https://github.com/ultralytics/yolov5/blob/79bca2bf64da04e7e1e74a132eb54171f41638cc/models/common.py#L66

Why do you design the transformer layer with two successive linear layer?

Two Successive Linear Layer is same with one linear layer theorectically.

**Comment by glenn-jocher** [comment]
@developer0hye that's a good question, but I can't answer that myself since @dingyiwei is the C3TR author in PR# https://github.com/ultralytics/yolov5/pull/2333. 

I know 2 convolution2d layers in series are reducible to 1 if it were not for the activation layer in between, does the same hold true for fully connected layers with no activation in between?

**Comment by developer0hye** [comment]
@glenn-jocher 

If the kernel size of conv2d layer is one, your statement is true!

**Comment by dingyiwei** [comment]
Hi @developer0hye , thanks to point out this issue! It should be an activation between the two successive linear layer. I'll run experiments on that and post results here.

**Comment by mx2013713828** [comment]
> Hi @developer0hye , thanks to point out this issue! It should be an activation between the two successive linear layer. I'll run experiments on that and post results here.

I'm waiting your experiments.

**Comment by dingyiwei** [comment]
In this [comment](https://github.com/ultralytics/yolov5/issues/2329#issuecomment-789444817) I mentioned why I removed the activation function.
I have to find a new computing platform and rerun my experiments because I left the lab recently before.
