### ISSUE TITLE
save-txt

### ISSUE THREAD

**Issue by Chimchar009** [ultralytics/yolov5#5581]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

i dont think theres an exact answer to this question that ive found but is there a way to get the saved labels to save only at certain intervals or get it to save at certain sizes of the bounding boxes only?

**Comment by Zengyf-CVer** [comment]
@Chimchar009 
For the detection of video files, you can improve yourself according to the relevant code in `detect.py`. Just add the judgment code.

**Comment by Chimchar009** [comment]
could someone at least tell me where is the code that creates the label txt like how does it name the txt document is it through class_time if so where and how can i find it

**Comment by glenn-jocher** [comment]
@Chimchar009 this is easy to find in detect.py
https://github.com/ultralytics/yolov5/blob/7ebb5e5da673350d4c168cf60d01986a5e0f00cc/detect.py#L151-L158

**Comment by Chimchar009** [comment]
not what i meant but nvrm i found it
