### ISSUE TITLE
How do I get AP values for large, medium and small targets

### ISSUE THREAD

**Issue by Weixueying** [ultralytics/yolov5#5582]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, may I ask that the result I got when I used val.py to test is like this, this result is not correct, how to use my own dataset to calculate the large and small target AP value, I hope to get your reply (I would like to ask: if my current data set is in VOC format, then how to obtain the“json” file?)
Model Summary: 474 layers, 29079389 parameters, 0 gradients, 59.1 GFLOPs
val: Scanning '/tmp/wxy/coco/labels/val2017.cache' images and labels... 4952 found, 48 missing, 0 empty, 0 corrupted: 
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 
                 all       5000      36335      0.686      0.548     0.594**   0.407**
Speed: 0.1ms pre-process, 7.6ms inference, 1.5ms NMS per image at shape (16, 3, 512, 512)

Evaluating pycocotools mAP... saving /tmp/zwc/weight/val/exp17/best_ghost_100_predictions.json...
loading annotations into memory...
Done (t=0.40s)
creating index...
index created!
Loading and preparing results...
DONE (t=6.20s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=42.90s).
Accumulating evaluation results...
DONE ### (t=13.18s).
** Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.002
** Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.003
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.002
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.002
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.002
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.004
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.051
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.096
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.103
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.064
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.113
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.177
Results saved to /tmp/nihao/weight/val/exp17

**Comment by Zengyf-CVer** [comment]
@Weixueying 
- Regarding the different results, refer to: https://github.com/ultralytics/yolov5/issues/2258
- For questions about size, please refer to: https://github.com/ultralytics/yolov5/issues/5531
- Regarding the conversion of VOC to COCO JSON, you can write your own script according to the VOC tag format, and then convert it to COCO's JSON format.

**Comment by shenhaibb** [comment]
I also want to get ap values for big targets, medium targets, and small targets
I now want to test coco128 first
I converted coco128 to coco JSON format and placed it in the annotations folder
![image](https://user-images.githubusercontent.com/64736467/147388099-8a73a4e4-54e1-4dcf-8f7b-94346b52950c.png)
![image](https://user-images.githubusercontent.com/64736467/147388107-bc2e32e1-74d9-4b36-b885-595f4beda812.png)
Yolov5s_predictions.json was tested using yolov5s.pt
![image](https://user-images.githubusercontent.com/64736467/147388141-27ff3b4e-4f31-4ac6-8784-f136627eb9fc.png)
Why do I get an error when running val.py
![image](https://user-images.githubusercontent.com/64736467/147388157-caa89ec0-ab38-4bb5-b93b-f3b72fdadcef.png)

**Comment by engrjav** [comment]
any solution to it @shenhaibb

**Comment by shenhaibb** [comment]
> any solution to it

https://github.com/ultralytics/yolov5/issues/6110

**Comment by engrjav** [comment]
Thanks i will try
What i understood is to comment the lines 
# if is_coco:
              #  eval.params.imgIds = [int(Path(x).stem) for x in dataloader.dataset.img_files]  # image IDs to evaluate

in val.py 
then convert my images and annotations in serialized form and then validate
