### ISSUE TITLE
Data scanning in val.py

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#5583]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

@glenn-jocher 
When running `val.py`, there is a label scanning process, as shown in the figure:
![ksnip_20211109-124454](https://user-images.githubusercontent.com/41098760/140864347-af0237ba-1d6d-4b38-ac94-051f20dda092.png)
What do `missing`, `empty`, and `corrupted` mean here? Where is the code to calculate them? thanks.

**Comment by glenn-jocher** [comment]
@Zengyf-CVer yes this might be a little confusing:

- missing means that an image was found with no label file (missing labels). This is ok, i.e. for background images.
- empty means that an image was found with an empty label.txt file. This is also ok, i.e. for background images.
- corrupted means the image and/or label failed to pass checks, and will be ignored during training/val. 

The image and label checks are here. We check to make sure the labels are in the correct format, the image loads and has a minimum size, etc.
https://github.com/ultralytics/yolov5/blob/79bca2bf64da04e7e1e74a132eb54171f41638cc/utils/datasets.py#L883-L931

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
I learned it, thank you very much.

**Comment by DhruvAwasthi** [comment]
**Update:** the function `verify_image_label(args)` has been now moved from `yolov5/utils/datasets.py` to `yolov5/utils/dataloaders.py`.

**Comment by glenn-jocher** [comment]
@DhruvAwasthi You're welcome! I'm glad you found the information helpful. If you have any more questions or need further assistance, feel free to ask. Good luck with your YOLOv5 project!
