### ISSUE TITLE
Is any guide of converting torch mobile or tflist?

### ISSUE THREAD

**Issue by Haebuk** [ultralytics/yolov5#5585]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi!
Is there any guidance of converting my model(fine-tuned yolov5) to torch mobile or tflite?

**Comment by glenn-jocher** [comment]
@Haebuk we don't have a torch-mobile guide, but we do support TFLite export.

You can export to TFLite and verify your model like this:
```
python export.py --weights yolov5s.pt --include tflite
python detect.py --weights yolov5s-fp16.tflite
```

**Comment by Haebuk** [comment]
@glenn-jocher  thank you so much. It really helps :)
