### ISSUE TITLE
Pretrained yolov5s gets 0.371 mAP@.5:.95 on test-dev split and 0.557 mAP@.5 on test-dev split. There is a little difference from the official（0.372，0.56）, is this normal?

### ISSUE THREAD

**Issue by wangtao0219** [ultralytics/yolov5#5586]
### Search before asking

- [ ] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,

I used the pretrained yolov5s for evaluation on the official  test-dev split.I cloned the code from the repo, no modifications have been done.
To reproduce run val command below, zip runs/val/exp/yolov5x6_predictions.json, and submit to server under Participate tab.
!python val.py --weights yolov5s.pt --data coco.yaml --img 640 --conf 0.001 --iou 0.65 --task test   ，this get result（0.371，0.557），but it isn't official（0.372，0.56）
then,I used the command !python val.py --weights yolov5s.pt --data coco.yaml --img 640 --conf 0.001 --iou 0.65 --task test --augment ,it becomes (0.383,0.565)

No matter what, I never get the official result.  Is this normal? Or am I missing something.

**Comment by glenn-jocher** [comment]
@wangtao0219 I don't understand your question, as we don't have any test-dev result published for YOLOv5s. All our README results are on val. If you get 37.1 on test-dev, and we have 37.2 on val, I'd say everything is correct. What's the problem exactly?

**Comment by wangtao0219** [comment]
Sorry, I misunderstood.
I ran it again and the result was correct
