### ISSUE TITLE
Unsample

### ISSUE THREAD

**Issue by zwhua006** [ultralytics/yolov5#5587]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Nowadays I read the paper CARAFE: Content-Aware ReAssembly of FEatures,and i think it will be useful.
So I want to use CARAFEPack instead of nn.UnSample('nearst').
Firstly, I install  carafe and from carafe import CARAFEPack
According to https://github.com/myownskyW7/CARAFE, I design the class CarafePack()

```python
class CarafePack():
    def __init__(self,Channels,scale_factor):
        self.model = CARAFEPack(Channels,scale_factor)
    def forward(self,x):
        self.model = self.model.cuda()
        x = x.cuda()
        out = self.model(x)
        return out
```

And  I modify the yaml 
  [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, CarafePack, [256, 2]],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, C3, [512, False]],  # 13

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, CarafePack, [128, 2]],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, C3, [256, False]],  # 17 (P3/8-small)

but it's wrong.The error is AttributeError: 'CarafePack' object has no attribute 'parameters'.So how to  realize this idea？thanks

**Comment by glenn-jocher** [comment]
@zwhua006 be sure to also add your model to yolo.py so parse_model() can find it, and add any special handling required there:

https://github.com/ultralytics/yolov5/blob/79bca2bf64da04e7e1e74a132eb54171f41638cc/models/yolo.py#L250-L302

**Comment by zwhua006** [comment]
I closed mixed precision training and completed it .like this:
  if type(m) == CARAFEPack:
                m = m.cuda()
                x = x.cuda()
                x = m(x)
                x = x.cpu()
else:
                x = m(x)  # run
but  the error is All input tensors must be on the same device. Received cuda:0 and cpu whether m=m.cuda() x=m(x) or m=m.cuda(),x=x.cuda(),x=m(x),x=x.cpu()
I found x=m(x) the input x and output x are on cpu? and why? When I run the program,it's on cuda.when I debug this, it's not.

**Comment by glenn-jocher** [comment]
@zwhua006 backend and type handling is performed automatically, you don't need to concern yourself with this. See examples of YOLOv5 modules:
https://github.com/ultralytics/yolov5/blob/79bca2bf64da04e7e1e74a132eb54171f41638cc/models/common.py#L32-L42

**Comment by zwhua006** [comment]
Now I  don't use class CarafePack(). Because I found from carafe import CARAFEPack is useful.
Now I simplily modify yaml 
[[-1, 1, Conv, [512, 1, 1]],
[-1, 1, CarafePack, [256, 2]],
[[-1, 6], 1, Concat, [1]], # cat backbone P4
[-1, 3, C3, [512, False]], # 13

[-1, 1, Conv, [256, 1, 1]],
[-1, 1, CarafePack, [128, 2]],
[[-1, 4], 1, Concat, [1]], # cat backbone P3
[-1, 3, C3, [256, False]], # 17 (P3/8-small)

and in yolo.py  
  def _forward_once(self, x, profile=False, visualize=False):
      y, dt = [], []  # outputs
      for m in self.model:
          if m.f != -1:  # if not from previous layer
              x = y[m.f] if isinstance(m.f, int) else [x if j == -1 else y[j] for j in m.f]  # from earlier layers
          if profile:
              self._profile_one_layer(m, x, dt)
          if type(m) == CARAFEPack:
              m = m.cuda()
              x = x.cuda()
              x = m(x)
          else:
              x = m(x)  # run

but error is All input tensors must be on the same device. Received cuda:0 and cpu
I found original x=m(x).  the input x and output x are on cpu? and why? When I run the program,it's on cuda.when I debug this, it's not.

**Comment by zwhua006** [comment]
I found that the reason seems to be this. At the beginning, forward function was executed once. At this time, x was on the cpu, but afterwards, the forward was executed again during training, and both x and the model were on the GPU. The input and output in CARAFEPack need to be on the GPU, so the two cannot be met at the same time

**Comment by zwhua006** [comment]
I resolved this.But the new error appears.
 File "/home/zwhua/yolov5/train.py", line 628, in <module>
    main(opt)
  File "/home/zwhua/yolov5/train.py", line 525, in main
    train(opt.hyp, opt, device, callbacks)
  File "/home/zwhua/yolov5/train.py", line 346, in train
    callbacks.run('on_train_batch_end', ni, model, imgs, targets, paths, plots, opt.sync_bn)
  File "/home/zwhua/yolov5/utils/callbacks.py", line 76, in run
    logger['callback'](*args, **kwargs)
  File "/home/zwhua/yolov5/utils/loggers/__init__.py", line 86, in on_train_batch_end
    self.tb.add_graph(torch.jit.trace(de_parallel(model), imgs[0:1], strict=False), [])
  File "/home/zwhua/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/jit/_trace.py", line 742, in trace
    _module_class,
  File "/home/zwhua/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/jit/_trace.py", line 940, in trace_module
    _force_outplace,
  File "/home/zwhua/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 725, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/home/zwhua/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 709, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/zwhua/yolov5/models/yolo.py", line 127, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "/home/zwhua/yolov5/models/yolo.py", line 158, in _forward_once
    x = m(x)
  File "/home/zwhua/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 725, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/home/zwhua/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 709, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/zwhua/anaconda3/envs/pytorch/lib/python3.7/site-packages/carafe/carafe.py", line 250, in forward
    x = self.feature_reassemble(x, mask)
  File "/home/zwhua/anaconda3/envs/pytorch/lib/python3.7/site-packages/carafe/carafe.py", line 242, in feature_reassemble
    x = carafe(x, mask, self.up_kernel, self.up_group, self.scale_factor)
  File "/home/zwhua/anaconda3/envs/pytorch/lib/python3.7/site-packages/carafe/carafe.py", line 114, in forward
    group_size, scale_factor, routput, output)
IndexError: _Map_base::at
Do you know what caused this error?thanks
