### ISSUE TITLE
Is there any way to find which is the epoch recorded in best.pt?

### ISSUE THREAD

**Issue by thanos-sakelliou** [ultralytics/yolov5#5588]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

It is important to know which is the best epoch recorded in best.pt, so one can compare the results easily, such as in wandb debugger. I could not find it anywhere. If it is not logged it would be a very nice feature to be implemented.

**Comment by glenn-jocher** [comment]
@thanos-sakelliou it's not explicitly recorded anywhere, but best.pt is saved on maximum fitness, which is mainly correlated with mAP@0.5:0.95, so the highest mAP@0.5:0.95 epoch is very likely to be the epoch that best.pt was saved at.

You can submit a PR if you'd like to add this field to the checkpoint dictionary. Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by thanos-sakelliou** [comment]
I am using custom fitness function thus is not easy to find out every time. I am going to submit a PR thank you.

**Comment by AyushExel** [comment]
@thanos-sakelliou as you mentioned, for the wandb side of things, you can see which model performs the best when the models are logged by specifiying the `--save-period`. When the models are versioned, they're assigned aliases. `best` is assigned to the lastest model which performs best on the metric
![Screenshot (75)](https://user-images.githubusercontent.com/15766192/140966070-c3e0f6da-5837-430a-aa19-84f2956753a7.png)
