### ISSUE TITLE
torch.hub inferences 

### ISSUE THREAD

**Issue by pure-rgb** [ultralytics/yolov5#5589]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have an image and model detected well. But I need only that bounding box which covers a large area. With inferencing with `torch.hub`, how to achieve it? 

### Additional

```
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, custom

# Images
img = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, PIL, OpenCV, numpy, list

# Inference
results = model(img)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
```

**Comment by pure-rgb** [comment]
I can do it manually but I like to know if it's possible with` tf.hub` interface with any `model....` settings.

**Comment by glenn-jocher** [comment]
@Suzan009 you can filter `results` by any criteria you want, i.e. size, etc.:

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Image
img = 'https://ultralytics.com/images/zidane.jpg'

# Inference
results = model(img)

results.pandas().xyxy[0]
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 1  433.50  433.50   517.5  714.5    0.687988     27     tie
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie

```
