### ISSUE TITLE
How to verify the converted onnx model is correct?

### ISSUE THREAD

**Issue by china56321** [ultralytics/yolov5#559]
Hi , i have two questions,
Q1:How to verify whether the converted onnx model ( converted from export.py ) is correct ? Is there some code to verify the onnx model (for example , use onnx model to test a picture )
Q2: Can the converted onnx be directly deployed  without any modified ?

**Comment by fnuabhimanyu** [comment]
You can visualize and compare both the .pt file as well as the .onnx file in [Netron](https://lutzroeder.github.io/netron/).
