### ISSUE TITLE
PyTorch Hub inference –– set --img to 1280 by default when inference with P6 models to allow detecting large object automatically

### ISSUE THREAD

**Issue by onnkeat** [ultralytics/yolov5#5590]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

It is suggested that the **PyTorch Hub inference function should set the image size to 1280 automatically when P6 models is used**. It should also be documented and placed at explicit location where P6 models users is always alerted of this.

PyTorch Hub default inference size is 640 [1]. However, people may not realise that when using P6 models because it is not compulsory to pass image size argument in inference function. Hence, they may **mistakenly thinking that the pipeline will scale the image to size 1280 automatically**, but in fact it is scaled to size 640. It is common for people to think like that because scaling the input image to size 640 when using P6 model will not reap the benefits of detecting large object because the largest detectable object size of image size 640 is only 640. 

Let say a person wish to use P6 models to detect large object(up to 1280). A person may run the following code by just changing the model name to a P6 model. Usually the person won't know that he need to pass the argument `size=1280` in order to scale the image to size 1280.

```
#PyTorch Hub inference

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5x6')  # or yolov5m6, yolov5l6, yolov5x6, custom

# Inference
results = model(img)  #default image size 640

```

Based on the current implementation, the person should run the following code to scale the image to size 1280
```
results = model(img, size=1280) 
```

Reference
[1] https://github.com/ultralytics/yolov5/issues/5507#issuecomment-961205239

### Use case

Any people who use P6 models to detect large object in any use case

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@onnkeat yes this is an interesting point. The same might apply to detect.py and val.py too. 

I think the above logic might be extended in a more general way to say that models should default to inference at their training settings. i.e. you can also train P6 models at --img 640, and they will outperform P5 models trained at --img 640, so it's not safe to default any P6 model to 1280 at inference time.

Unfortunately the current model checkpoints do not retain training settings that would enable this sort of smart inference. It seems like they should though, either in the checkpoint dictionary or directly as model attributes?

**Comment by glenn-jocher** [comment]
@onnkeat BTW on this topic, I want to merge these two together at some point in the future, as it feels a bit redundant to keep both P5 and P6 versions (and it confuses users).

P6 models are generally better in most use cases (better mAP, similar speed, similar CUDA memory usage), except that they are about 50% larger (MB) than P5 versions, so for mobile deployments some users may still prefer a P5 model. I think the best move would be to create a reduced-size P6, perhaps with DepthWise convolutions smartly used in the larger output layers to reduce their size somewhat, and then simplify the range of models to just 5 of these advanced P6 models.

**Comment by glenn-jocher** [comment]
@onnkeat image size might be added to model attributes here as `model.imgsz = imgsz`
https://github.com/ultralytics/yolov5/blob/27bf4282d3d5879f0f4f7492400675ba93a3db1b/train.py#L247-L257
