### ISSUE TITLE
precision and Recall were always 0，box, OBj, and CLS were nan

### ISSUE THREAD

**Issue by zzff-sys** [ultralytics/yolov5#5591]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When I was using the YoloV5 training model, my training results for precision and Recall were always 0, and box, OBj, and CLS were nan. I'd like to ask these questions.

### Additional

I have found many ways to solve the problem, but it has not been solved yet

**Comment by zzff-sys** [comment]
I have installed the installation package in the requirements.txt file. My running environment is win10, GPU: GTX 1650, pytoch = 1.10.0, CUDA = 11.3.1

**Comment by glenn-jocher** [comment]
@zzff-sys I think there's an open torch/nvidia bug with CUDA 11 on windows/conda. Installing CUDA 10 works for other users.

**Comment by zzff-sys** [comment]
Thank you very much for your answer. The problem has been solved after modification according to your tips. Thank you @glenn-jocher

**Comment by zjs210** [comment]
> @zzff-sys我认为 Windows/conda 上的 CUDA 11 存在一个打开的Torch /nvidia 错误。安装 CUDA 10 适用于其他用户。

我是CUDA10，但是单目标检测训练后precision和Recall的训练结果都是0
