### ISSUE TITLE
Top x class predictions

### ISSUE THREAD

**Issue by JuanOnOne** [ultralytics/yolov5#5594]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi I'm trying to obtain a list of top x class predictions out of the model results, I only see in some cases 1 class output. Do I need to change the output layer to include softmax?

**Comment by glenn-jocher** [comment]
@JuanOnOne NMS passes the most likely class. You can customize it as you see fit:
https://github.com/ultralytics/yolov5/blob/7207fe95e5dc368e4402134148c5d0c35361ad88/utils/general.py#L638-L645

**Comment by JuanOnOne** [comment]
@glenn-jocher thank you very much for your prompt response! Appreciate it.
