### ISSUE TITLE
PyTorch > onnx > Browser Anchors and Bounding Boxes

### ISSUE THREAD

**Issue by jkassis** [ultralytics/yolov5#5595]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm working with the version of YOLOv5 found here...

`https://github.com/shayanalibhatti/Retail-Store-Item-Detection-using-YOLOv5`

This creates the following model configuration... 

```
nc: 1
depth_multiple: 0.33
width_multiple: 0.50

anchors:
  - [10,13, 16,30, 33,23] 
  - [30,61, 62,45, 59,119]
  - [116,90, 156,198, 373,326] 

backbone:
  [[-1, 1, Focus, [64, 3]],
   [-1, 1, Conv, [128, 3, 2]],
   [-1, 3, Bottleneck, [128]],
   [-1, 1, Conv, [256, 3, 2]],
   [-1, 9, BottleneckCSP, [256]],
   [-1, 1, Conv, [512, 3, 2]], 
   [-1, 9, BottleneckCSP, [512]],
   [-1, 1, Conv, [1024, 3, 2]],
   [-1, 1, SPP, [1024, [5, 9, 13]]],
   [-1, 6, BottleneckCSP, [1024]],
  ]

head:
  [[-1, 3, BottleneckCSP, [1024, False]],
   [-1, 1, nn.Conv2d, [na * (nc + 5), 1, 1, 0]],
   [-2, 1, nn.Upsample, [None, 2, "nearest"]],
   [[-1, 6], 1, Concat, [1]],
   [-1, 1, Conv, [512, 1, 1]],
   [-1, 3, BottleneckCSP, [512, False]],
   [-1, 1, nn.Conv2d, [na * (nc + 5), 1, 1, 0]],
   [-2, 1, nn.Upsample, [None, 2, "nearest"]],
   [[-1, 4], 1, Concat, [1]],
   [-1, 1, Conv, [256, 1, 1]],
   [-1, 3, BottleneckCSP, [256, False]],
   [-1, 1, nn.Conv2d, [na * (nc + 5), 1, 1, 0]],

   [[], 1, Detect, [nc, anchors]],
  ]
```

I've exported this to onnx and loaded it in my web browser using ONNX Runtime Web (`https://github.com/microsoft/onnxruntime/tree/master/js`).

Images go into the model for inference. Three Tensors come out...

![image](https://user-images.githubusercontent.com/3630156/141028123-5cc7efd9-d6e1-42d3-9192-4dd8c5566840.png)

I send the 'output' tensor to the post-processor to detect bounding boxes. The output Tensor eventually gets to this function where the reshape operation fails with an error saying that the expected size of the tensor does not match the size of the data...

![image](https://user-images.githubusercontent.com/3630156/141031340-b3ac62c9-b2c7-4498-92fd-7c2a41fad4ff.png)

The anchors are specified as follows... to match the model specification...

![image](https://user-images.githubusercontent.com/3630156/141028588-00803fdc-19b7-467a-bfb9-70f3e1b38858.png)

The output tensor going into that reshape operation looks like this... 
```
data:Float32Array(86400) [-1.4055006504058838, -2.6782095432281494, -1.6832102537155151, 1.0977379083633423, 0.31478673219680786, -1.1230947971343994, 0.7309814095497131, -0.7121259570121765, -1.2874948978424072, 1.4315454959869385, 0.08459210395812988, -0.47530561685562134, -0.36152759194374084, -1.927358627319336, -2.4011435508728027, -1.3033223152160645, -2.613729953765869, -3.2987048625946045, -1.7147060632705688, -3.287318468093872, -3.9702744483947754, -2.1272192001342773, -3.6558446884155273, -4.371188163757324, -2.742501974105835, -3.5995640754699707, -4.698141098022461, -1.7210001945495605, -2.833242654800415, -3.065596580505371, -1.5970734357833862, -3.273900270462036, -2.6209397315979004, -1.2001104354858398, -3.064718008041382, -2.854077100753784, -3.651319742202759, -4.234926700592041, -5.073905944824219, -2.5945727825164795, -3.390446662902832, -5.9701104164123535, 0.10446476936340332, -0.585559606552124, -3.56315541267395, 0.4630813002586365, -0.040144115686416626, -2…63, …]
dims:(5) [6, 60, 80, 3, 1]
size:86400
type:'float32'
```

If I hardcode numAnchors to '3', this reshape operation succeeds without error, but no bounding boxes appear. So I suspect that I have something else perhaps completely wrong in this pipeline. Regardless, I'm sure I shouldn't have to hardcode the numAnchors.

I'm quite new to yolo and will be reading the papers soon to better understand the expected inputs and outputs. But a little nudge in the right direction would be greatly appreciated!

- J

**Comment by Zengyf-CVer** [comment]
@jkassis
- First, please download the official program: https://github.com/ultralytics/yolov5.git
- Secondly, the yolov5 program you downloaded is old, such as `Focus` in the structure, so please use the latest official program.

```
$ git clone https://github.com/ultralytics/yolov5
$ cd yolov5
$ pip install -r requirements.txt

```

**Comment by glenn-jocher** [comment]
@jkassis naturally we can't control nor provide support for 3rd party versions of YOLOv5, so if you have issues there you should raise them with the respective authors. 

Of course I'd recommend using the official version as @Zengyf-CVer mentioned. You can train a retail store model with the SKU-110K dataset and export to ONNX in two lines of code:

```bash
python train.py --weights yolov5s.pt --data SKU-110K.yaml
python export.py --weights runs/train/exp/weights/best.pt --include onnx
```

**Comment by jkassis** [comment]
@Zengyf-CVer @glenn-jocher Thanks so much for looking at this. I took your advice and retrained the model with the official version at `https://github.com/ultralytics/yolov5`.

I get the same result in the `yolo_head` function when it attempts to reshape the output using numAnchors / numClasses.

The outputs of inference have changed a bit...

![image](https://user-images.githubusercontent.com/3630156/141160011-116641e4-d40f-4ec4-94cb-284b80dc879f.png)

**Comment by glenn-jocher** [comment]
@jkassis 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide **all** parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by jkassis** [comment]
@glenn-jocher @Zengyf-CVer

do you really think this is a potential problem with yolov5?

I'm guessing it just has something to do with my naivety and the postprocessing code I lifted from a microsoft onnx demo for yolov2 @ `https://github.com/microsoft/onnxjs-demo`.

in any case... as you requested... here is a repo with a pretty minimal test case.  The README.md explains how to install / start it and see what I'm seeing.

`https://github.com/jkassis/onnx-test`

Model is included.

**Comment by glenn-jocher** [comment]
@jkassis thanks for the details. For ONNX inference we support the methods below. If there is an issue running these commands that is within the repository scope that we provide support for, but onward deployment or custom code isn't within our support scope. If you adopted your code from another source those authors would be the right place to ask.

```python
# Export
python export.py --weights yolov5s.pt --include onnx

# Inference
python detect.py --weights yolov5s.onnx  # ONNX Runtime
python detect.py --weights yolov5s.onnx --dnn  # ONNX OpenCV DNN
python val.py --weights yolov5s.onnx --data coco128.yaml  # Validation
```

**Comment by jkassis** [comment]
@glenn-jocher thanks again for the quick reply. I know you guys are busy. I acknowledge the scope of your ability to support these things and that's why I asked about yolov5 outputs and anchors.

The code I borrowed worked for YOLOv2 onnx models. So this seems to have something to do with how YOLO has changed since then. Or perhaps with a change to the export pipeline.

Other browser-based examples are for YOLOv3 and generally in Tensorflow, so are not very helpful.

I re-trained and exported on YOLO latest and put together an isolated test repo as requested, but was hoping you might just have a sense of it. I'm pretty sure the relevant code is in that `yolo_head` function I posted.

Thanks again and LMK if anything does just strike you out of the blue.

**Comment by glenn-jocher** [comment]
@jkassis I'm sorry, I can't be of help here. I've never used javascript and I have no idea how to set up a deployment pipeline there. Our web and mobile developers who do know are severely overcommitted with our upcoming product launch at https://ultralytics.com/hub and have no current availability for consulting work.

**Comment by glenn-jocher** [comment]
@jkassis of course you can use our own working TF.js example BTW. See export.py for usage example:
https://github.com/ultralytics/yolov5/blob/30bc089cbbe0c38bb09883f01b85ca31afca653b/export.py#L6-L20

**Comment by jkassis** [comment]
Hi @glenn-jocher As you suggested... I tried the react example from zldrobit with the tensorflow.js model. That LGTM.

I removed onnx from my test project and switched to TF. When I load the same model in my test project I get this...

```
strided_slice.js:67 Uncaught (in promise) Error: ellipsis mask is not yet supported
    at stridedSlice_ (strided_slice.js:67)
    at stridedSlice (operation.js:45)
    at slice_join_executor.js:87
    at operation_executor.js:88
    at engine.js:425
    at t.e.scopedRun (engine.js:436)
    at t.e.tidy (engine.js:423)
    at Nb (globals.js:182)
    at operation_executor.js:87
    at fO (operation_executor.js:52)
stridedSlice_ @ strided_slice.js:67
stridedSlice @ operation.js:45
(anonymous) @ slice_join_executor.js:87
(anonymous) @ operation_executor.js:88
(anonymous) @ engine.js:425
e.scopedRun @ engine.js:436
e.tidy @ engine.js:423
Nb @ globals.js:182
(anonymous) @ operation_executor.js:87
fO @ operation_executor.js:52
h @ graph_executor.js:362
e.processStack @ graph_executor.js:348
(anonymous) @ graph_executor.js:310
u @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.t.<computed> @ runtime.js:97
Wm @ runtime.js:728
o @ runtime.js:728
(anonymous) @ runtime.js:728
(anonymous) @ runtime.js:728
(anonymous) @ graph_executor.js:338
(anonymous) @ graph_executor.js:258
u @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.t.<computed> @ runtime.js:97
Wm @ runtime.js:728
o @ runtime.js:728
(anonymous) @ runtime.js:728
(anonymous) @ runtime.js:728
(anonymous) @ graph_executor.js:275
(anonymous) @ graph_model.js:311
u @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.t.<computed> @ runtime.js:97
Wm @ runtime.js:728
o @ runtime.js:728
(anonymous) @ runtime.js:728
(anonymous) @ runtime.js:728
(anonymous) @ graph_model.js:312
detect @ Main.ts:72
(anonymous) @ Main.ts:13
async function (async)
detect @ Main.ts:72
(anonymous) @ Main.ts:13
async function (async)
(anonymous) @ Main.ts:12
Show 11 more frames
```

Just FYI / keeping you in the loop. Thanks for your continued advice. Also FYI... I pushed an update to that test project.

**Comment by jkassis** [comment]
@glenn-jocher The example project got me across the goal line. Many thanks! TF 3.0 with YOLOv5 is a winner.

**Comment by glenn-jocher** [comment]
@jkassis great!
