### ISSUE TITLE
How can I change the class name?

### ISSUE THREAD

**Issue by ryotaro137** [ultralytics/yolov5#5598]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm trying to detect using detect.py.
I think I need to change yaml to change the display of the class name, but since there is no such tag in passer, can you tell me what to do?
example)
Bottle → Other object name
Thank you.

**Comment by iumyx2612** [comment]
I think the class name lies in the model when you load it in `names = model.module.names if hasattr(model, 'module') else model.names  # get class names`. If you use a pretrained model, the class name should be fixed

**Comment by glenn-jocher** [comment]
@ryotaro137 class names are model attributes. You can modify any you want:
```python
model.names[0] = 'new_name'
```

**Comment by ryotaro137** [comment]
Thank you!!!
Thanks to that, I was able to take a step toward what I wanted to do!!!
I'm really thankful to you!!!
Thank you again!!!

**Comment by glenn-jocher** [comment]
@ryotaro137 great! You're welcome.
