### ISSUE TITLE
warning

### ISSUE THREAD

**Issue by 123456789mojtaba** [ultralytics/yolov5#560]
E:\Softwares\Anaconda\installation\envs\torch\lib\site-packages\torch\serialization.py:657: SourceChangeWarning: source code of class 'models.yolo.Detect' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.                                                                                 warnings.warn(msg, SourceChangeWarning)  
Hi

what does this warning saya?

**Comment by glenn-jocher** [comment]
You can ignore these.
