### ISSUE TITLE
Upgrades of YOLOv5

### ISSUE THREAD

**Issue by iumyx2612** [ultralytics/yolov5#5603]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Can you make a documentation about all the upgrades of YOLOv5 from YOLOv4. 
I've searched issues and found several things that YOLOv5 did like: SPPF, Focus class, loss function... but it's hard to track down all of them. 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@iumyx2612 hi buddy. We are unfortunately extremely overworked from repo maintenance and development work and have not had time to properly document. We are growing the team and hopefully will address this shortcoming in the future. Thanks for your feedback.

**Comment by iumyx2612** [comment]
> @iumyx2612 hi buddy. We are unfortunately extremely overworked from repo maintenance and development work and have not had time to properly document. We are growing the team and hopefully will address this shortcoming in the future. Thanks for your feedback.

Feelsbadman. Hope you can grow your team and get things done quickly, awesome repo btw
