### ISSUE TITLE
How to get the FPS?

### ISSUE THREAD

**Issue by Zhiying-Li-dot** [ultralytics/yolov5#5605]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I have found all issues,but no method that get the FPS.So I want to ask how to get FPS?Could you tell me?Thank you.

**Comment by glenn-jocher** [comment]
@lizhiying-2019 see https://en.wikipedia.org/wiki/Frame_rate

**Comment by Zhiying-Li-dot** [comment]
@glenn-jocher Yeah,I have some understanding after reading the introduction of FPS. I want to ask if there is any FPS calculation in the code?

**Comment by Zengyf-CVer** [comment]
@lizhiying-2019 
This question of yours shows that you did not search carefully in `issue`. There are calculations about FPS in yolov5. Please search carefully and you will find the answer.

**Comment by Zhiying-Li-dot** [comment]
![3](https://user-images.githubusercontent.com/75170833/141249641-e9ff83a0-56bb-43d8-9f3d-1edfb403297f.png)
Is it this one? @Zengyf-CVer

**Comment by Zengyf-CVer** [comment]
@lizhiying-2019 
No,that is to calculate the PR curve.
Refer to this:
https://github.com/ultralytics/yolov5/issues/5113

**Comment by Zhiying-Li-dot** [comment]
@Zengyf-CVer I got it. I use 1/inference time to obtain FPS.That's right?

**Comment by Zengyf-CVer** [comment]
@lizhiying-2019 
Yes.

**Comment by Zhiying-Li-dot** [comment]
@Zengyf-CVer Thanks a lot.
