### ISSUE TITLE
Use Yolov5 real time video output as input for gstreamer

### ISSUE THREAD

**Issue by schpatz** [ultralytics/yolov5#5606]
Hey there,
I'm trying to use a usb webcam as an input, which I understand is possible with getting the number from (`/dev/video*` or `gst-device-monitor-1.0`) and using the `--source` flag in the `detect.py` script. 
Now I would like to get the output of the `detect.py` file and save it in a way I could use that output file as an input for gstreamer. 
So basically use the webcam as an input, run the interference with `detect.py` and while that is running get an output file (e. g. a FIFO of frames) which I can use as an "emulated" webcam for gstreamer.
If this is already possible please let me know or if you have any ideas on how to accomplish this I would be more than greatful to hear them.
PS: Ffmpeg isn't an option since I have to use gstreamer for AWS Kinesis video streams
Pipeline: webcam -> detect.py -> gstreamer

**Comment by glenn-jocher** [comment]
@schpatz I don't have gstreamer experience but your options are to modify detect.py or to create your own custom python workflows with a [YOLOv5 PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) model.

**Comment by schpatz** [comment]
> @schpatz I don't have gstreamer experience but your options are to modify detect.py or to create your own custom python workflows with a [YOLOv5 PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) model.

Thanks for the quick answer, I suppose you may have misunderstood the issue at hand. The gstreamer side I already figured out, the only part I need is a FIFO file output from the `detect.py` script. Would you happen to have an idea how to accomplish this maybe with an opencv VideoWriter (`cv2.VideoWriter()`) or the `cv2.imwrite()` function? If not that completely fine and will keep looking into it.

**Comment by glenn-jocher** [comment]
@schpatz sorry, we don't individual provide support for code customizations but perhaps a community member might have ideas.

**Comment by Zengyf-CVer** [comment]
@schpatz 
Your question is a bit confusing:
First, what do you want to do in detect.py?
Secondly, what problem did you encounter?
Please describe your problem in detail here.

**Comment by schpatz** [comment]
> @schpatz Your question is a bit confusing: First, what do you want to do in detect.py? Secondly, what problem did you encounter? Please describe your problem in detail here.

Hey thanks for replying,
so the problem I'm facing is that I don't get a usable output from `detect.py`. It uses the opencv VideoWriter to write the output in a mp4 file. I would need to get an output I could directly use as an input for gstreamer. I think this would be possible with a FIFO queue that writes the detected images into a file. However I'm not sure how to implement it into the `detect.py` file.
In the end I would like to have a setup that takes the Webcam input runs the `detect.py` on it and passes the results through to a file I can use as input for gstreamer so that I have a real time object detection stream.
Hope this clarifies things.
Cheers

**Comment by Zengyf-CVer** [comment]
@schpatz 
Although I have never used `gstreamer`, I have done similar projects, you can refer to this link:[here](https://github.com/ultralytics/yolov5/tree/master/utils/flask_rest_api)
If you have strong programming skills, it should be able to be applied to your project.

**Comment by schpatz** [comment]
> @schpatz Although I have never used `gstreamer`, I have done similar projects, you can refer to this link:[here](https://github.com/ultralytics/yolov5/tree/master/utils/flask_rest_api) If you have strong programming skills, it should be able to be applied to your project.

That unfortunately doesnt help me much, since it's something completely different because it extracts the data and not a video but thanks either way :)

**Comment by Snehashishd2** [comment]
Hi there,
I was trying to infer yolov5 with gstremer, but facing problem with anchor and the last layer.

**Comment by research-boy** [comment]
@Snehashishd2 i would like to try this, let me know where exactly are you with this?

**Comment by gustavozantut** [comment]
Take a look!
Still very new but i started working on some way to do this
https://github.com/gustavozantut/yolov5_live_results

**Comment by glenn-jocher** [comment]
@gustavozantut great initiative! Thanks for sharing the link. Your contribution is valuable to the YOLO community. Keep up the good work!
