### ISSUE TITLE
Reuse YOLOv5s' Backbone

### ISSUE THREAD

**Issue by ayushmankumar7** [ultralytics/yolov5#5607]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I was working with the 's' model. I wanted to save just the _pretrained Backbone_ (up to **SSPF** block) and use it in a different project altogether. 
I tried following "detect.py" and "train.py" to see how the models are being loaded and saved. I also saw that `torch.load("yolov5s.pt")` is throwing an error when I try loading it outside the project. (This might be because of _deepcopy_ which is used to save ckpt['model']). 
How can I load the Arch, load the state_dict and just use or save only the trained backbone? 

### Additional

I really loved the way this project is progressing. Got to learn a lot through this Codebase.

**Comment by glenn-jocher** [comment]
@ayushmankumar7 you can load a model like this outside of the project and then handle however you'd like:

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, custom
```

If you don't need the AutoShape wrapper then you can pass `autoshape=False` on load.

See **PyTorch Hub** tutorial for details:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by ayushmankumar7** [comment]
Thank you so much for replying @glenn-jocher !!
