### ISSUE TITLE
 'Conv' object has no attribute '_non_persistent_buffers_set'

### ISSUE THREAD

**Issue by Cestbo** [ultralytics/yolov5#561]
## ❔Question
why is this error

**Comment by glenn-jocher** [comment]
@Cestbo this is a pytorch 1.6 error. Any model trained with 1.5 will cause this error. Official models are all supported, so if you delete any local models you have and rerun your commands the updated models that autodownload will work correctly.

**Comment by Cestbo** [comment]
> @Cestbo this is a pytorch 1.6 error. Any model trained with 1.5 will cause this error. Official models are all supported, so if you delete any local models you have and rerun your commands the updated models that autodownload will work correctly.

thanks，this problem has been solved.
