### ISSUE TITLE
How to make ground truth picture with bounding box ?

### ISSUE THREAD

**Issue by Haebuk** [ultralytics/yolov5#5610]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,
Is there way to make ground truth label bbox picture like below picture?

- detect.py return example
![image](https://user-images.githubusercontent.com/68543150/141226826-0c201f46-7f08-4f28-a680-8167b10e33ea.png)

I know that detect.py returns labeling picures to runs/detect/. but I don't know how to make using GT labels.
I downloaded dataset via VisDrone.yaml, so I have 3 folders(annotations, images, labels)

**Comment by Zengyf-CVer** [comment]
@Haebuk 
In fact, it is very simple. You can draw the coordinates and category information in the GT tag onto the picture through OpenCV.

**Comment by glenn-jocher** [comment]
@Haebuk @Zengyf-CVer validation labels are plotted automatically for the first few batches as `val_batch0.jpg` etc., and training mosaics with labels are also plotted automatically during training as `train_batch0.jpg` etc.

We're also working on our super cool online training tool at https://ultralytics.com/hub that allows for full dataset visualization of all the YOLOv5 datasets like VisDrone:
<img width="1458" alt="Screenshot 2021-11-11 at 12 01 38" src="https://user-images.githubusercontent.com/26833433/141287137-0d0cd88b-962f-4e0c-bda3-4c55b65e2a6a.png">

**Comment by AyushExel** [comment]
@Haebuk you can also use wandb to visualize your entire dataset and also interact with it. See [coco dataset example  ](https://wandb.ai/cayush/yolo_coco_tables/artifacts/dataset/val/1cd9bb326ed7c315b310/files/val.table.json)
To use this, run the following command with `wandb` installed:
```
python utils/logger/wandb/log_dataset.py --project ... --name ... --data ..
```
Example:
![Screenshot from 2021-11-11 19-48-26](https://user-images.githubusercontent.com/15766192/141314412-19e7209b-d2bd-4e61-be9b-d6c9f9072b82.png)


More advanced usage [here](https://github.com/ultralytics/yolov5/issues/1289)

**Comment by Haebuk** [comment]
@Zengyf-CVer @glenn-jocher @AyushExel  Thank you for answering. I'll try it :)
