### ISSUE TITLE
Training crashes after epoch

### ISSUE THREAD

**Issue by brunovollmer** [ultralytics/yolov5#5617]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

I'm currently trying to run training on a quite big dataset. Whenever a single epoch is finished the training crashes with the following error:
```
Traceback (most recent call last):
  File "train.py", line 626, in <module>
    main(opt)
  File "train.py", line 523, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 366, in train
    compute_loss=compute_loss)
  File "/home/vollmer.bruno/yolov5/env/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/vollmer.bruno/yolov5/val.py", line 236, in run
    p, r, ap, f1, ap_class = ap_per_class(*stats, plot=plots, save_dir=save_dir, names=names)
  File "/home/vollmer.bruno/yolov5/utils/metrics.py", line 56, in ap_per_class
    tpc = tp[i].cumsum(0)
  File "/home/vollmer.bruno/yolov5/env/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 20978) is killed by signal: Killed.
```

The weird thing is that it does not crash if I just take 128 images from the same dataset. When I check WandB it seems that the system memory is maxed out but I already have 30gb ram + 128 gb of swap.
![image](https://user-images.githubusercontent.com/8973456/141283671-4b8f82ec-9a01-4e6e-949b-af86f21e467f.png)

### Environment

I'm using the pre configured GCP Deep Learning Instance with a single v100.
I've created a virtual env environment with the following packages:
```
absl-py==0.15.0
cachetools==4.2.4
certifi==2021.10.8
charset-normalizer==2.0.7
click==8.0.3
configparser==5.1.0
cycler==0.11.0
Cython==0.29.24
docker-pycreds==0.4.0
gitdb==4.0.9
GitPython==3.1.24
google-auth==2.3.3
google-auth-oauthlib==0.4.6
grpcio==1.41.1
idna==3.3
importlib-metadata==4.8.2
kiwisolver==1.3.2
Markdown==3.3.4
matplotlib==3.4.3
numpy==1.21.4
oauthlib==3.1.1
opencv-python==4.5.4.58
pandas==1.3.4
pathtools==0.1.2
Pillow==8.4.0
promise==2.3
protobuf==3.19.1
psutil==5.8.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycocotools==2.0.2
pyparsing==3.0.5
python-dateutil==2.8.2
pytz==2021.3
PyYAML==6.0
requests==2.26.0
requests-oauthlib==1.3.0
rsa==4.7.2
scipy==1.7.2
seaborn==0.11.2
sentry-sdk==1.4.3
shortuuid==1.0.7
six==1.16.0
smmap==5.0.0
subprocess32==3.5.4
tensorboard==2.7.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
termcolor==1.1.0
thop==0.0.31.post2005241907
torch==1.10.0
torchvision==0.11.1
tqdm==4.62.3
typing-extensions==3.10.0.2
urllib3==1.26.7
wandb==0.12.6
Werkzeug==2.0.2
yaspin==2.1.0
zipp==3.6.0
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@brunovollmer this isn't a bug, you've just exhausted your system resourced, i.e. RAM, CPUs etc. You should train on a system with increased resources or run commands that require less resources, i.e. smaller model, smaller img size, smaller batch size etc.

**Comment by brunovollmer** [comment]
But why does it run through the whole first epoch and then crash after the validation and what swap + ram size would you recommend for a dataset with ~500k train images and a batch size of 64?

**Comment by glenn-jocher** [comment]
@brunovollmer the size of your dataset is irrelevant, the settings that will reduce your resource utilization I already mentioned above.

**Comment by brunovollmer** [comment]
ok thanks. will try batch size 40 then

**Comment by glenn-jocher** [comment]
@brunovollmer also you might want to check memory utilization with W&B disabled `wandb disabled` to isolate sources of utilization.

**Comment by brunovollmer** [comment]
Will do thanks!
