### ISSUE TITLE
Illegal instruction (core dumped) running on NVIDIA Jetson TX2 

### ISSUE THREAD

**Issue by ykn96** [ultralytics/yolov5#5624]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

Other issues have been marked stale

### YOLOv5 Component

Detection

### Bug

I git cloned the full repo and ran the programme with no further modification
Appended below is the terminal output

```
python3 detect.py --source 0
detect: weights=yolov5s.pt, source=0, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False
YOLOv5 🚀 v6.0-84-gdef7a0f torch 1.10.0 CPU

Fusing layers... 
Illegal instruction (core dumped)
````

### Environment

- YOLOv5 🚀 v6.0-84-gdef7a0f torch 1.10.0 CPU
- DJI Manifold 2G (Nvidia Jetson TX2)
ARMv8 Processor rev 3 (v8l) × 4 ARMv8 Processor rev 0 (v8l) × 2
NVIDIA Tegra X2 (nvgpu)/integrated
8GB ram, Ubuntu 18.04 LTS

### Minimal Reproducible Example

```
python3 detect.py --source 0
````
Done in a new virtual environment python 3.8, after pip install -r requirements.txt

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@fatbringer you may want to run Jetson workflows in a suitable Nvidia base image to avoid potential environment issues:
https://ngc.nvidia.com/catalog/containers/nvidia:l4t-base

**Comment by ykn96** [comment]
Hey there. Hm for this embedded computer platform, as far as I know, i am unable to run a pure NVIDIA based image in order for the USB ports to be working. An example of the OS package with Jetpack 3.3 installed can be found here. Would i expect to face similar problems if i use this ? 

The link is: https://www.dji.com/sg/manifold-2/downloads >> Manifold 2 Firmware V0.3.3.2 (Manifold 2-G Image Tool & Official Image). I am currently using a similar one that is upgraded to Jetpack 4.4.

**Comment by glenn-jocher** [comment]
@fatbringer I can't really help here, not my area of expertise. If usb drive access is the issue you can run a docker container with access to local storage using the volumes -v command:
https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/

**Comment by UygarUsta99** [comment]
I think the source of the problem is the numpy version.Try previous numpy versions such as numpy==1.19.4.

**Comment by ykn96** [comment]
@UygarUsta99 i have tried downgrading the numpy version too. I still get illegal instruction core dumped

@glenn-jocher The usb drive issue also affects my usb keyboard and mouse. Essentially i would lose control over the embedded computer since the attached mouse and keyboard wouldn't work anymore.

**Comment by ykn96** [comment]
Hi just to add on some detailsof the error
Package: python3.8-minimal3.8.9-1+xenial1 [origin: LP-PPA-deadsnakes]
python3.8 crashed with SIGILL in exec_blas
There seems to be also an error with my torch. But other i can run other repos fine
