### ISSUE TITLE
on the Xavier agx not running

### ISSUE THREAD

**Issue by ozlem-atiz** [ultralytics/yolov5#5625]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

I am trying to do training on jetson xavier agx. But I downloaded all the requirements. Setups are ok. When I start the tutorial, it gives a syntax error. I couldn't understand what the problem is. I created char.yaml file. The codes are as follows. I wrote the location of train and val according to its location.
Can you help me please @glenn-jocher @PetrDvoracek  @adrianholovaty @jacklinquan @
![Screenshot from 2021-11-12 11-42-59](https://user-images.githubusercontent.com/88368610/141438609-3abc4d96-82a7-44f1-ac84-fe4dd669475e.png)

### Environment

ubuntu 18.04
python:python3.9
computer: Nvidia Jetson Xavier AGX

### Minimal Reproducible Example
char.yaml code
```
train: /data/images/train
val: /data/images/val

# number of classes
nc: 1

# class names
names: ['plate']
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ozlem-atiz your char.yaml file is all correct, there's no issues there. You likely have environment issues. We don't have Xavier devices ourselves, but in general I would recommend running in an Xavier compatible docker image like this one:
https://ngc.nvidia.com/catalog/containers/nvidia:l4t-pytorch

**Comment by ozlem-atiz** [comment]
Hei @glenn-jocher . İ  changed in char.yaml.  And i have Illegal instruction (core dumped)
 error. Why i don t know. İ am used this command:export OPENBLAS_CORETYPE=ARMV8
i have same error. Why is this ? 
![Screenshot from 2021-11-17 09-39-38](https://user-images.githubusercontent.com/88368610/142201320-fbb64f40-b7ff-4f8d-9fac-113d01c5bba8.png)
changed .yaml file:
train: /home/omer/Desktop/yolov5/data/images/train
val: /home/omer/Desktop/yolov5/data/images/val


# number of classes
nc: 1

# class names
names: ['plate']

**Comment by glenn-jocher** [comment]
@ozlem-atiz it appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual Python 3.8 environment, clone the latest repo ([code changes daily](https://github.com/ultralytics/yolov5/commits/master)), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below. 


## Requirements

[**Python>=3.6.0**](https://www.python.org/) with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) installed including [**PyTorch>=1.7**](https://pytorch.org/get-started/locally/). To get started:
```bash
$ git clone https://github.com/ultralytics/yolov5
$ cd yolov5
$ pip install -r requirements.txt
```

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), validation ([val.py](https://github.com/ultralytics/yolov5/blob/master/val.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/export.py)) on MacOS, Windows, and Ubuntu every 24 hours and on every commit.

**Comment by ozlem-atiz** [comment]
> @ozlem-atiz it appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally. If in doubt, create a new virtual Python 3.8 environment, clone the latest repo ([code changes daily](https://github.com/ultralytics/yolov5/commits/master)), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below.
> 
> ## Requirements
> [**Python>=3.6.0**](https://www.python.org/) with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) installed including [**PyTorch>=1.7**](https://pytorch.org/get-started/locally/). To get started:
> 
> ```shell
> $ git clone https://github.com/ultralytics/yolov5
> $ cd yolov5
> $ pip install -r requirements.txt
> ```
> 
> ## Environments
> YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):
> 
> * **Google Colab and Kaggle** notebooks with free GPU: [![Open In Colab](https://camo.githubusercontent.com/84f0493939e0c4de4e6dbe113251b4bfb5353e57134ffd9fcab6b8714514d4d1/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb) [![Open In Kaggle](https://camo.githubusercontent.com/a08ca511178e691ace596a95d334f73cf4ce06e83a5c4a5169b8bb68cac27bef/68747470733a2f2f6b6167676c652e636f6d2f7374617469632f696d616765732f6f70656e2d696e2d6b6167676c652e737667)](https://www.kaggle.com/models/ultralytics/yolov5)
> * **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
> * **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
> * **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) [![Docker Pulls](https://camo.githubusercontent.com/280faedaf431e4c0c24fdb30ec00a66d627404e5c4c498210d3f014dd58c2c7e/68747470733a2f2f696d672e736869656c64732e696f2f646f636b65722f70756c6c732f756c7472616c79746963732f796f6c6f76353f6c6f676f3d646f636b6572)](https://hub.docker.com/r/ultralytics/yolov5)
> 
> ## Status
> ![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)
> 
> If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), validation ([val.py](https://github.com/ultralytics/yolov5/blob/master/val.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/export.py)) on MacOS, Windows, and Ubuntu every 24 hours and on every commit.



I changed the pytorch version. I installed all the requirements as you said. i am loaded again  the yolov5 .Now I am getting another error. New memory related bug. I researched. I created a swapfile and allocated additional memory. But the error persists. I went according to this source.
https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-16-04

![Screenshot from 2021-11-18 11-20-15](https://user-images.githubusercontent.com/88368610/142378147-b98610c8-0e0b-4644-a30a-32bb571ee57e.png)

**Comment by glenn-jocher** [comment]
@ozlem-atiz interesting. A different user recently reported a similar error and said that reducing `NUM_THREADS` here resolved the issue for them. How many cpus does your device have? Can you try to reduce this and see if this resolves your issue?

https://github.com/ultralytics/yolov5/blob/562191f5756273aca54225903f5933f7683daade/utils/datasets.py#L38

**Comment by glenn-jocher** [comment]
@ozlem-atiz also that 'System throttled due to Over-current' message doesn't look very good. Maybe a hardware swap or upgrade is a good idea.

**Comment by ozlem-atiz** [comment]
![Screenshot from 2021-11-18 14-23-33](https://user-images.githubusercontent.com/88368610/142406590-9f095610-c41f-4075-b5fc-ef697750fc99.png)

Images and labels in the train folder are read, but they do not load in the epochs section. I changed the command line you mentioned from 8 to 4

` NUM_THREADS  =  min ( 4 , os . cpu_count ())   # çok işlemli iş parçacığı sayısı 
`
@glenn-jocher

**Comment by glenn-jocher** [comment]
@ozlem-atiz does it work at 4? If not keep reducing.

**Comment by ozlem-atiz** [comment]
didn't work. I reduced it to 1 digits. always the same result:
error:OSError: [Errno 12] Cannot allocate memory
@glenn-jocher

**Comment by glenn-jocher** [comment]
@ozlem-atiz you need more RAM, your system is simply out of memory.

**Comment by ozlem-atiz** [comment]
![f3bf9be6-107a-4efa-b6ba-b3795f4ad210](https://user-images.githubusercontent.com/88368610/142430027-12d7e038-b6a5-422e-b455-582125d52abf.jpeg)

I am using jetson nano for gpu computer system. But there are not many projects in it. There is only this yolov5 project. How to upgrade ram. I guess I need to send it in for service. I don't know how to upgrade ram. I created a swapfile. But the system didn't eat it

**Comment by glenn-jocher** [comment]
@ozlem-atiz I think what's going on is that you're trying to use a jetson/xavier to train models, which I've never heard of. I think these are strictly deployment destinations for trained models. First you train in the cloud or with a desktop GPU, then you export and deploy.

**Comment by ozlem-atiz** [comment]
@glenn-jocher  mr jocher. I'm actually training on colab. But I want my system to work very well. That's why I want it to train non-stop. I want to do this from the terminal on computers with gpu. While the system is running, I want it to continue to train itself morning and evening. I want colab to train on xavier for a long time because it gives limited time  :D

**Comment by SodrSnne** [comment]
> @glenn-jocher mr jocher. I'm actually training on colab. But I want my system to work very well. That's why I want it to train non-stop. I want to do this from the terminal on computers with gpu. While the system is running, I want it to continue to train itself morning and evening. I want colab to train on xavier for a long time because it gives limited time :D

i am a jetson player , i think it could only be a inference device, not suitable for training;  you can try `detece.py `on it.

**Comment by zhangv12** [comment]
> 

Hi, I also met the implementation problems on Jetson Nano with 4GB memory and also on Xavier. My problem is like this, the input source when inferencing comes from a web camera(http://xxx.xxx.xxxx), firstly the detection program goes well, but after few minutes (maybe fewer hours on Xavier), the video showing window getting black, and the program detects nothing. I guess this is caused by the memory problem, but still have no solution. Do you have any suggestion? Thank you!

**Comment by zhangv12** [comment]
> Hi, I also met the implementation problems on Jetson Nano with 4GB memory and also on Xavier. My problem is like this, the input source when inferencing comes from a web camera(http://xxx.xxx.xxxx), firstly the detection program goes well, but after few minutes (maybe fewer hours on Xavier), the video showing window getting black, and the program detects nothing. I guess this is caused by the memory problem, but still have no solution. Do you have any suggestion? Thank you!

**Comment by glenn-jocher** [comment]
@zhangv12 YOLOv5 uses cv2 for streaming and video sources, so I would raise an issue directly on the opencv repository regarding sustained streaming over time, as this is not within our direct control.

Also if you suspect your hardware to be the cause you should reproduce on other hardware, i.e. Colab to isolate the source of the problem.

Lastly note your source or your own network connection may be at fault.
