### ISSUE TITLE
Unexpected behavior in DDP mode with dataloader workers

### ISSUE THREAD

**Issue by wico-silva** [ultralytics/yolov5#5628]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Multi-GPU

### Bug

In distributed multi-GPU training we specify the total batch size in the command-line which then gets divided per process here: https://github.com/ultralytics/yolov5/blob/master/train.py#L222

I would expect the same to be done for the number of workers but that's not the case.

So if I run:
`python -m torch.distributed.run --nproc_per_node 2 train.py --batch-size 16 --workers 8`

I expect two process each with batch size 8 and 4 dataloader workers.
Instead, I get two processes, each with batch size 8 and 8 dataloader workers which is dangerous because it might be too many workers for my CPU to handle and training gets extremely slow.

### Environment

- YOLO: master
- Ubuntu 18.04
- Python 3.6.9

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@wico-silva --workers are per RANK if you use DDP. This allows you to scale training without having to worry about manually specifying --workers, i.e.

```bash
python -m torch.distributed.run --nproc_per_node 2 train.py --batch-size 16
python -m torch.distributed.run --nproc_per_node 4 train.py --batch-size 32
python -m torch.distributed.run --nproc_per_node 8 train.py --batch-size 64
```

**Comment by wico-silva** [comment]
But then why not apply that same logic with batch size? My main point is that workers and batch size should follow the same logic. Either per rank or for world. Currently, workers is per rank and batch size is for world.

At least, this difference in logic should be documented clearly in the command-line arguments.

**Comment by glenn-jocher** [comment]
@wico-silva thanks for the feedback! Have you used other tools that follow one convention or the other for these two settings?

**Comment by glenn-jocher** [comment]
@wico-silva we can definitely put some more checks in place to prevent excess workers and to improve the console output for clarity, but I doubt it's a good idea to modify default behavior with so many users already using existing YOLOv5 DDP conventions.

**Comment by wico-silva** [comment]
What I see the most is definitely workers and batch size per rank, because that's just what naturally happens without any extra code.

It's also what makes the most sense given that `torch.distributed.run` is just taking the script `train.py` and spawning multiple processes. So it makes sense that whatever arguments come after 
`python -m torch.distributed.run --nproc_per_node X train.py`
are the same as if we were training in single GPU.

On the other hand, if we look at the PyTorch ImageNet example we see that they use workers and batch size for world. They then divide both per rank here: https://github.com/pytorch/examples/blob/master/imagenet/main.py#L145

I guess what's important is being consistent. But I also understand that this would be an annoying change for many, so a compromise would be to document this behavior in the command-line help

**Comment by glenn-jocher** [comment]
@wico-silva got it! I've opened up a PR #5631 that ticks a few of these boxes. This retains the current behavior but it updates the command line help and most importantly it caps the vcpu usage smartly with world-size, so the danger is removed that a DDP user would accidentally use too many workers. This is probably the best compromise.

**Comment by wico-silva** [comment]
thanks for the quick replies and addressing it so fast. I'll close the issue

**Comment by glenn-jocher** [comment]
@wico-silva PR #5631 is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐
