### ISSUE TITLE
Use of Mixup values

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#5629]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

@glenn-jocher 
I don't know how the value of `mixup` in the hpy file is used in the `mixup` function in `augmentations.py`?
https://github.com/ultralytics/yolov5/blob/d5b21b1ecb66b35af937ac12364aa80733222bd1/data/hyps/hyp.scratch-high.yaml#L33

https://github.com/ultralytics/yolov5/blob/d5b21b1ecb66b35af937ac12364aa80733222bd1/utils/augmentations.py#L264-L269

**Comment by glenn-jocher** [comment]
@Zengyf-CVer mixup 0.1 means 10% of the images will have mixup applied. The 10% filter is applied before mixup():
https://github.com/ultralytics/yolov5/blob/d5b21b1ecb66b35af937ac12364aa80733222bd1/utils/datasets.py#L561-L564

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
According to your explanation, the value of mosaic is 1.0, which means that 100% of the images in each batch are applied to mosaic?
https://github.com/ultralytics/yolov5/blob/d5b21b1ecb66b35af937ac12364aa80733222bd1/data/hyps/hyp.scratch.yaml#L32
https://github.com/ultralytics/yolov5/blob/d5b21b1ecb66b35af937ac12364aa80733222bd1/utils/datasets.py#L555

**Comment by glenn-jocher** [comment]
@Zengyf-CVer yes default mosaic: 1.0 hyp means mosaic is applied to all images. You can see this in the train batch jpgs produced train start:
![image](https://user-images.githubusercontent.com/26833433/141472538-4eedca0c-c7d7-4b4e-87d6-c86afd6ec859.png)

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
I learned it, thank you very much.
