### ISSUE TITLE
Media Bounding Box Debugger/Images is invalid. Please remove invalid filename characters

### ISSUE THREAD

**Issue by Wanghe1997** [ultralytics/yolov5#5634]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

[Tag v5.0] When I was using yolo v5 to train my dataset, the following error occurred in the code when epoch=99:

Media Bounding Box Debugger/Images is invalid. Please remove invalid filename characters

![程序报错](https://user-images.githubusercontent.com/45507837/141637342-442fdf88-ca07-4652-bb8e-520160d99e05.png)

I can run the code of the homepage(master)normally,but v5.0 can not run. It seems to be a problem with wandb. So how can i fix this error？And how to close wandb when I am training？ Thanks

**Comment by AyushExel** [comment]
Hi. This issue was fixed in the latest version of the master branch. Run `git pull` inside the yoloV5 dir to get the latest changes. That should fix this issue
