### ISSUE TITLE
The latest version of wandb issues

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#5636]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

@glenn-jocher @AyushExel 
I upgraded wandb to the latest version 0.12.6, ran `train.py`, and wandb reported an error. I'm sorry I didn't take a screenshot in time.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@Zengyf-CVer can you describe more? Did you see the error in the official colab? Any more info would be useful. thanks!
EDIT: @Zengyf-CVer I tried the colab but didn't see any error

**Comment by Zengyf-CVer** [comment]
@AyushExel 
I did it locally, and since I am busy lately, I will post the screenshots in two days.

**Comment by AyushExel** [comment]
@Zengyf-CVer hey were you able to reproduce this?

**Comment by Zengyf-CVer** [comment]
@AyushExel 
Since I am busy these days, I haven't been able to reply in time. Wait a minute, I'll send it to you later.

**Comment by Zengyf-CVer** [comment]
@AyushExel 
Unfortunately, I failed to reproduce the error that day. I upgraded the version to 0.12.6 again, but there were no errors.
I am using the new clone's yolov5 project today, which may be the reason why the relevant code has been updated. Thank you for waiting so long, I'm really sorry.

**Comment by AyushExel** [comment]
No worries. Happy to help!
