### ISSUE TITLE
How to add  a custom object class  with addition to coco dataset 

### ISSUE THREAD

**Issue by husnejahan** [ultralytics/yolov5#5639]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to add  a custom object class  with addition to coco dataset  by custom training?

### Additional

Custom trained model can not detect coco classes. How to get a single one.

**Comment by glenn-jocher** [comment]
@husnejahan a model must be trained on all classes it's expected to be able to detect. You can train on multiple datasets very easily, however the class indices and labels must not conflict, i.e. label any additional dataset classes starting from index 80 if COCO is your first dataset.
https://github.com/ultralytics/yolov5/blob/540ef0dd30be9bcf6882c9625c49f61c5c764f52/data/GlobalWheat2020.yaml#L10-L27

**Comment by husnejahan** [comment]
@glenn-jocher  Thank you. But do you mean I will have to train a model with coco class data & additional class data together?

I want to use pre-trained weight and transfer learning for some coco class and additional class. This [https://docs.ultralytics.com/yolov5/tutorials/train_custom_data] Train-Custom-Data is for only custom object detection, I want both as as a single model.

**Comment by glenn-jocher** [comment]
@husnejahan yes I understand, my previous message already covers this https://github.com/ultralytics/yolov5/issues/5639#issuecomment-968340909
