### ISSUE TITLE
why set 'lf = lambda x: (((1 + math.cos(x * math.pi / epochs)) / 2) ** 1.0) * 0.8 + 0.2' ?

### ISSUE THREAD

**Issue by clw5180** [ultralytics/yolov5#564]
Usually lr will decrease to 0.01x or less , but here 0.2x is the least. Why set learning rate like this? Thanks a lot!

And why   **1.0 ?

**Comment by glenn-jocher** [comment]
@clw5180 you're free to modify as you see fit for your own tasks.
