### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by AndreasKaratzas** [ultralytics/yolov5#5642]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How much does caching really boost the execution? Is there a way to test the code without actually caching the data in order to fetch the relative results?

**Comment by glenn-jocher** [comment]
@AndreasKaratzas why ask someone when you can just run the experiment yourself? No one will be able to quantify results for you on your own hardware but you.

**Comment by AndreasKaratzas** [comment]
I thought that the creators had already some recorded improvements before and after this feature. I will run some experiments myself and log them here then.

**Comment by glenn-jocher** [comment]
@AndreasKaratzas we don't have profiling results available, but in most cases caching will improve speeds. Results will vary based upon hardware, software, drivers, training settings and dataset.
