### ISSUE TITLE
pretrained and weight

### ISSUE THREAD

**Issue by QY1994-0919** [ultralytics/yolov5#5644]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

The network structure of Yolov5 has been changed, and the weight file needs to be pre-trained again. What should be changed in the train.py code

**Comment by glenn-jocher** [comment]
@QY1994-0919 architecture was updated in v6.0 release. See release notes for details:
https://github.com/ultralytics/yolov5/releases/tag/v6.0
