### ISSUE TITLE
How to use trained `pt` file for inference with pytorch?

### ISSUE THREAD

**Issue by mzhadigerov** [ultralytics/yolov5#5647]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I trained `yolov5s` and got model weights. Now I want to use it for inference. I'm using this code: 

```
model = torch.hub.load("ultralytics/yolov5", 'custom', path="data/id_card_detection/best.pt")
```

It works okay, but it loads the model from the internet. How to change `ultralytics/yolov5` part to use local model and where can I download the model from?

**Comment by glenn-jocher** [comment]
@mzhadigerov your local model is obviously not downloaded from the internet. If you mean repo cache, which is downloaded from the internet, you can point to a local yolov5 repo using the examples shown in the YOLOv5 **PyTorch Hub** tutorial:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by mzhadigerov** [comment]
@glenn Sorry, what I mean is the first argument ---> `ultralytics/yolov5` 

So, what you mean is that I can instead clone the `yolov5` repository to my local machine first and then substitute `ultralytics/yolov5` with `path/to/cloned/yolov5/repo` ?

like this:

```
model = torch.hub.load("path/to/cloned/yolov5/repo", 'custom', path="data/id_card_detection/best.pt")
```

**Comment by glenn-jocher** [comment]
@mzhadigerov read the PyTorch Hub tutorial as I've indicated earlier.
