### ISSUE TITLE
iDetection models 

### ISSUE THREAD

**Issue by Vadbeg** [ultralytics/yolov5#5648]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How did you convert the models for iDetection? Did you use coreml or torchscript? And if you used CoreML, please share the method with us. Because original script doesn't export Detection head. Screenshot from Netron.
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/31592578/141751025-fb0b96fb-dccd-448c-a33b-789b68521933.png">

### Additional

This repo suggests to use torchscript model:
https://github.com/pytorch/ios-demo-app

**Comment by glenn-jocher** [comment]
@Vadbeg your code may be out of date, all export formats contain all model modules including Detect.

**Comment by Vadbeg** [comment]
@glenn-jocher Okay, please, try the command below and send the screenshot of the resulting model to Neutron. 
```
python export.py --include coreml --img 640
```

Because with the latest version of code, when I run script for detection:
```
python detect.py --weights ../weights/best.mlmodel --source ../data/images/test --img-size 640 --hide-labels --hide-conf
```

I get this error:
```
Traceback (most recent call last):
  File "detect.py", line 244, in <module>
    main(opt)
  File "detect.py", line 239, in main
    run(**vars(opt))
  File "/Users/vadim.tsitko/.virtualenv/yolov5-env/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 115, in run
    pred = model(im, augment=augment, visualize=visualize)
  File "/Users/vadim.tsitko/.virtualenv/yolov5-env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/vadim.tsitko/Projects/count-yolo/yolov5/models/common.py", line 362, in forward
    box = xywh2xyxy(y['coordinates'] * [[w, h, w, h]])  # xyxy pixels
KeyError: 'coordinates'
```

**Comment by congxing** [comment]
I am seeing the same issue using the latest version.

**Comment by glenn-jocher** [comment]
@Vadbeg @congxing good news 😃! Your original issue may now be fixed ✅ in PR #6195. This PR adds support for YOLOv5 CoreML inference.

```python
!python export.py --weights yolov5s.pt --include coreml  # CoreML export
!python detect.py --weights yolov5s.mlmodel  # CoreML inference (MacOS-only)
!python val.py --weights yolov5s.mlmodel  # CoreML validation (MacOS-only)

model = torch.hub.load('ultralytics/yolov5', 'custom', 'yolov5s.mlmodel')  # CoreML PyTorch Hub model
```

<img width="1360" alt="Screen Shot 2022-01-04 at 5 41 07 PM" src="https://user-images.githubusercontent.com/26833433/148147262-1527cccc-19ca-43c4-b50a-c9a81cfd0bb5.png">

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by congxing** [comment]
Thanks for fixing @glenn-jocher. I verified it was working on yolov5.mlmodel. However, for a customized model which is trained on another dataset, it seems the exported coreml model showing old labels using detect.py. 

For example, I trained the model on a custom dataset with two labels ['pet', 'person']. Using best.pt, the detected box is marked as 'person', but best.mlmodel shows bicycle instead.

**Comment by glenn-jocher** [comment]
@congxing ah yes, thanks for the feedback! The CoreML models do not contain class names embedded, these are sourced from the data.yaml, which defaults to COCO128. I'll think about how to handle this better:
https://github.com/ultralytics/yolov5/blob/00d7b978690d16729f411393bbd56f9dbd6a840c/detect.py#L220

**Comment by congxing** [comment]
Got it. Thanks for the pointer.
