### ISSUE TITLE
onnx model include detect layer

### ISSUE THREAD

**Issue by asizk** [ultralytics/yolov5#5651]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

In the previous version, the pt model was converted to the onnx model without decoding part. In the latest 6.0, the onnx model generated by the pt model includes the decoding part in the detect. I currently want to remove the decoding part, how to operate?

**_6.0 version .onnx structure: include decoding structure_**
![new1](https://user-images.githubusercontent.com/57747203/141760191-9db26260-146b-4ddc-b4f7-f617ac8748d3.jpg)
![new2](https://user-images.githubusercontent.com/57747203/141760198-c88d7166-90c3-4762-901f-aaa917f69f4a.jpg)
_**old version .onnx structure:**_
![old1](https://user-images.githubusercontent.com/57747203/141760201-9d2fdfad-f7f1-46ae-a286-cd08525b72d6.jpg)
![old2](https://user-images.githubusercontent.com/57747203/141760202-7d13a217-930a-4fdf-8ca5-d5838a40869e.jpg)

**Comment by glenn-jocher** [comment]
@asizk all YOLOv5 exports contain full models including Detect() layer. Can you modify a model in export.py (prior to export) if you choose to here:
https://github.com/ultralytics/yolov5/blob/c2523be634a94da2b1b2a43c11b25827a0de990d/export.py#L291-L303

**Comment by asizk** [comment]
> @asizk all YOLOv5 exports contain full models including Detect() layer. Can you modify a model in export.py (prior to export) if you choose to here:
> 
> https://github.com/ultralytics/yolov5/blob/c2523be634a94da2b1b2a43c11b25827a0de990d/export.py#L291-L303

thanks！When I changed the train of line 294 to False, I completed the requirement
