### ISSUE TITLE
A way to package trained model locally for inference

### ISSUE THREAD

**Issue by sarmientoj24** [ultralytics/yolov5#5652]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I would like to know if there is a way how I could package the trained model for inference (locally) so I do not need to incorporate the whole yolov5 code when integrating to my application.

My idea is to have something like `torch hub` where I could do

```
model = load_model('/path/to/model')
result = model(image, **parameters)
```

**Comment by glenn-jocher** [comment]
@sarmientoj24 see YOLOv5 **TorchScript, ONNX, CoreML Export** tutorial:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by sarmientoj24** [comment]
@glenn-jocher Saw the link but it doesnt tell me how to
- use it for inference with parameters
- use it inline instead of via command line

**Comment by glenn-jocher** [comment]
@sarmientoj24 not sure which export format you are referring to here, but all of them are inferenceable via detect.py which you can use as an example to start from.

**Comment by sarmientoj24** [comment]
@glenn-jocher is the torchscript and onnx way + `detect.py` preferable to using torch hub for inference in locally hosted systems? I was able to use a local model (from the `best.py` checkpoint) by loading it via torch hub and using for inference but the torchscript/onnx way might be preferable. 

Although the latter forces me to have the whole yolov5 directory integrated within the application as well, right?

**Comment by glenn-jocher** [comment]
@sarmientoj24 I can't advise you as this depends on your design requirements. Pytorch hub probably offers the simplest integration with other python workflows, but if you want to optimize or deploy to different platforms altogether like Android or iOS then clearly you're constrained to the export route.
