### ISSUE TITLE
How can we use flask rest api for video live streaming

### ISSUE THREAD

**Issue by Adarsh474532** [ultralytics/yolov5#5656]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How can we use flask rest api for video live streaming

**Comment by glenn-jocher** [comment]
@Adarsh474532 see https://github.com/ultralytics/yolov5/tree/master/utils/flask_rest_api and direct any questions to PR https://github.com/ultralytics/yolov5/pull/2732 author
