### ISSUE TITLE
RuntimeError: Cannot find callable custom_yolov5s in hubconf

### ISSUE THREAD

**Issue by I-am-vishalmaurya** [ultralytics/yolov5#5657]
RuntimeError: Cannot find callable custom_yolov5s in hubconf
![Screenshot 2021-11-15 200447](https://user-images.githubusercontent.com/57991538/141799893-f20f8aff-5b87-4cde-8ae4-506dc4647dd7.png)

_Originally posted by @I-am-vishalmaurya in https://github.com/ultralytics/yolov5/issues/1787#issuecomment-968971941_

**Comment by glenn-jocher** [comment]
@I-am-vishalmaurya your command is incorrect so an error is the expected result. See PyTorch Hub tutorial to get started using YOLOv5 PyTorch Hub models:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by I-am-vishalmaurya** [comment]
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, custom 
this is the code for loading the custom file right?

**Comment by glenn-jocher** [comment]
@I-am-vishalmaurya yes

**Comment by I-am-vishalmaurya** [comment]
![Screenshot 2021-11-15 202903](https://user-images.githubusercontent.com/57991538/141803733-e4c81001-0ac2-434e-8000-b982e531969e.png)
After reading some documentation I have reached here.

**Comment by I-am-vishalmaurya** [comment]
and to clone the repository I have used this 
# clone YOLOv5 repository
!git clone https://github.com/ultralytics/yolov5  # clone repo
%cd yolov5
!git reset --hard 886f1c03d839575afecb059accf74296fad395b6

**Comment by I-am-vishalmaurya** [comment]
Okay I have resolved this issue

**Comment by sharmas1ddharth** [comment]
> Okay I have resolved this issue

How did you do this can you please share with me.

**Comment by glenn-jocher** [comment]
@sharmas1ddharth 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, etc.
# model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')  # custom trained model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by sharmas1ddharth** [comment]
> @sharmas1ddharth 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`.
> 
> ### Simple Inference Example
> This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.
> 
> ```python
> import torch
> 
> # Model
> model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, etc.
> # model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')  # custom trained model
> 
> # Images
> im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list
> 
> # Inference
> results = model(im)
> 
> # Results
> results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
> 
> results.xyxy[0]  # im predictions (tensor)
> results.pandas().xyxy[0]  # im predictions (pandas)
> #      xmin    ymin    xmax   ymax  confidence  class    name
> # 0  749.50   43.50  1148.0  704.5    0.874023      0  person
> # 2  114.75  195.75  1095.0  708.0    0.624512      0  person
> # 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
> ```
> 
> <img alt="" width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">
> 
> See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.
> 
> Good luck 🍀 and let us know if you have any other questions!

Thank you so much @glenn-jocher it's working

**Comment by RAJ-DSML** [comment]
@glenn-jocher  👋 Hi, I'm trying to perform this same thing as @I-am-vishalmaurya  
![Capture](https://github.com/ultralytics/yolov5/assets/68045953/904e7bd3-4cc2-46fe-baaf-df4123f83196)

but I got this error:
raise RuntimeError(f'Cannot find callable {model} in hubconf')
RuntimeError: Cannot find callable yolov3 in hubconf

Are these steps essential for the code to work?

$ git clone https://github.com/ultralytics/yolov5
$ cd yolov5
$ pip install -r requirements.txt

**Comment by glenn-jocher** [comment]
@RAJ-DSML hey there! It looks like you're trying to load a model that isn't directly available via the YOLOv5 PyTorch Hub. The error you're seeing is because `yolov3` isn't a model option in the YOLOv5 repository. You'll want to use one of the available YOLOv5 models (`yolov5s`, `yolov5m`, `yolov5l`, `yolov5x`) or a custom model if you have trained one.

Here's a quick example of how to load a YOLOv5 model:

```python
import torch

# Load YOLOv5s model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')
```

And yes, cloning the repository and installing requirements are essential steps to ensure all dependencies are correctly set up for running YOLOv5 models. Make sure you have the latest version of the repository and have installed all necessary packages from `requirements.txt`. 😊
