### ISSUE TITLE
detect.py after converting in onnx with half precision doesn't work

### ISSUE THREAD

**Issue by skprot** [ultralytics/yolov5#5659]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

After converting .pt weights in .onnx format with half precision and running it with detect.py an error appears related to the fact that not all layers have been transferred to float16. 
 `onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from yolov5l.onnx failed:Type Error: Type parameter (T) of Optype (Concat) bound to different types (tensor(float) and tensor(float16) in node (Concat_505).`

I executed export.py code with parameters: `python export.py --weights yolov5l.pt --half --device 0`
And after sucsessful convertation I ran the following command: `python detect.py --weights yolov5l.onnx  --half --device 0` and it gave me an error above. 

### Additional

There is no such error if I translate without the --half flag

**Comment by skprot** [comment]
Forgot about --inplace flag

**Comment by glenn-jocher** [comment]
@skprot note that --half and --device detect.py arguments only apply to pytorch inference. ONNX inference will run on whatever onnxruntime installation was chosen here (if not already installed) and at whatever precision you exported at:
https://github.com/ultralytics/yolov5/blob/c2523be634a94da2b1b2a43c11b25827a0de990d/models/common.py#L315-L318

**Comment by matbun** [comment]
@skprot could you provide an example for your solution? I am still stuck. I am doing:  
`python export.py --weights best.pt --include onnx --simplify --half --device 0 --inplace`
and
`python detect.py --weights best.onnx`

But I still get the error:
```
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(float)) , expected: (tensor(float16))
```

Also adding `--half` argument to `detect.py`

**Comment by glenn-jocher** [comment]
@matbun detect.py --half handling only applies to pt, jit, engine backends:
https://github.com/ultralytics/yolov5/blob/b3eaf5008bb8a34de481a6ef7ac8ba520d97b70e/detect.py#L96-L100

**Comment by glenn-jocher** [comment]
@matbun @skprot good news 😃! Your original issue may now be fixed ✅ in PR #6268. 

Usage example:

```bash
# Export
python export.py --weights yolov5s.pt --include onnx --simplify --inplace --device 0 --half

# Inference
python detect.py --weights yolov5s.onnx --device 0 --half
python val.py --weights yolov5s.onnx --data data.yaml --device 0 --half
```

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by matbun** [comment]
@glenn-jocher Thank you! I confirm it works for me :)

**Comment by glenn-jocher** [comment]
@matbun great!
