### ISSUE TITLE
Need assistance interpreting results of F1 graph

### ISSUE THREAD

**Issue by ib124** [ultralytics/yolov5#5663]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I have run the ```val.py``` script and have generated an F1 curve. I know that the F1 score was calculated as follows: 

2 * [(precision * recall) / (precision + recall)].

When the graph is graphed against the confidence, is this graph basically telling you which confidence interval to specify when making detections? In my case, could I just specify ```--conf 0.298``` when running the ```python detect.py``` command?

Thanks!

![InkedF1_curve - Copy](https://user-images.githubusercontent.com/71450942/141857274-ac3a719f-82fe-478d-9558-2224493a5117.jpg)

**Comment by glenn-jocher** [comment]
@ib124 your deployment confidence threshold is a design decision that's up to you, based primarily on your Precision vs Recall compromise. This graph provides you information to help you make an informed decision.

**Comment by ib124** [comment]
@glenn-jocher Thank you!
