### ISSUE TITLE
Training on objects365, too slow

### ISSUE THREAD

**Issue by HuitMahoon** [ultralytics/yolov5#5665]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am trying to train Objects365 based on yolov5s. using the command line:
`python train.py --data custom.yaml --weights '' --cfg yolov5s.yaml --batch-size 32`
But the training speed is too slow, >3s/it.
My GPU is TITAN RTX 24G. And cuda is available.

Has anyone finished training on this datasets ,or share the model file? Thanks.

**Comment by glenn-jocher** [comment]
@HuitMahoon we've trained Objects365 here with no problems. This took about 3 days on an AWS P4 instance to train from scratch.
https://github.com/ultralytics/yolov5/releases/download/v6.0/yolov5m_Objects365.pt

**Comment by Guttappa1238** [comment]
> @HuitMahoon we've trained Objects365 here with no problems. This took about 3 days on an AWS P4 instance to train from scratch. https://github.com/ultralytics/yolov5/releases/download/v6.0/yolov5m_Objects365.pt

can you please provide dataset link?

**Comment by HuitMahoon** [comment]
> > @HuitMahoon we've trained Objects365 here with no problems. This took about 3 days on an AWS P4 instance to train from scratch. https://github.com/ultralytics/yolov5/releases/download/v6.0/yolov5m_Objects365.pt
> 
> can you please provide dataset link?

The datasets :
https://www.objects365.org/download.html
