### ISSUE TITLE
i don't understand the part of code in build_target function

### ISSUE THREAD

**Issue by heyitao** [ultralytics/yolov5#5669]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

![image](https://user-images.githubusercontent.com/22836696/141986894-64b04d9f-a0f3-4494-91b8-cc55061e7ef6.png)

whats the mean of Offsets computing ?  for label balance?
I dont understand the mean if j k l m in Offsets computing

**Comment by glenn-jocher** [comment]
@heyitao YOLOv5 uses a redundant multi-target assignment strategy that improves recall and mAP. j, k, l, m are indices of neighboring grid cells queued for target assignment of a particular label, each with a particular offset to the primary grid cell.

**Comment by heyitao** [comment]
> @heyitao YOLOv5 uses a redundant multi-target assignment strategy that improves recall and mAP. j, k, l, m are indices of neighboring grid cells queued for target assignment of a particular label, each with a particular offset to the primary grid cell.

@glenn-jocher  thanks for your reply;  And so, thats the reason why using  "y.sigmoid() * 2 -0.5", which the result is larger than 1.0, to regress the x and y ?

**Comment by glenn-jocher** [comment]
@heyitao no, our regression function avoids sigmoid extremes.

**Comment by heyitao** [comment]
@glenn-jocher  but how neighboring grid cells predict the x and y ? as far as i can see, it need predict a number larger than 1, like this , am i wrong?
![d7c22ad9fe3a47a3dd4fa09cbedc251e](https://user-images.githubusercontent.com/22836696/141995216-6dcb0e0b-2b11-4ee3-873a-1bfc1a5f2c9a.jpg)

**Comment by bilzard** [comment]
@heyitao 
If my understanding is correct, `(x, y)` are the center point of the predicted target.
The coordinate of the grid cell is in the range of `[0.0, 1.0] * [0.0, 1.0]`, and the center of the grid is defined as `(0.5, 0.5)`.
So the model seems to be designed to be capable of predicting object out of the grid cell.

It was discussed in the issue.
https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading8#issuecomment-657135751

**Comment by bilzard** [comment]
Like the picture below. The inner square shows the grid cell of the interest, and the outer square shows the receptive field.
<img width="206" alt="Screen Shot 2022-01-18 at 9 16 12" src="https://user-images.githubusercontent.com/36561962/149850284-29a3170c-8bb3-401c-b9de-708ebeb5f1a9.png">

**Comment by heyitao** [comment]
@bilzard oh, thanks !  This is what I want to say about the "y.sigmoid() * 2 -0.5", it expand the receptive field from 1X1 to 2X2, so that y can predict the target as long as target in receptive field even though the target is out side of grid cell. 
BTW, it interact with redundant multi-target assignment strategy, which build some target out of the grid cell.

**Comment by bilzard** [comment]
Sorry, I haven't understand target assignment part. It will need to struggle more with the code for me.
