### ISSUE TITLE
Error in pre-trained weights loading

### ISSUE THREAD

**Issue by aia39** [ultralytics/yolov5#567]
## Traceback (most recent call last):
  File "train_colab.py", line 122, in train
    ckpt['model'] = {k: v for k, v in ckpt['model'].float().state_dict().items()
  File "train_colab.py", line 123, in <dictcomp>
    if model.state_dict()[k].shape == v.shape}  # to FP32, filter
KeyError: 'model.18.conv.weight'

While using --weights yolov5s.pt 
I get this error. I have used recent weight and repo. I am using data for one class. What can be the solution?
Thanks.

**Comment by glenn-jocher** [comment]
@aia39 your code or your models are out of date. Best to start from a clean slate, reclone the repo and autodownload any pretrained weights you need again.
