### ISSUE TITLE
Adding Quantization of the model before the export of it!

### ISSUE THREAD

**Issue by ireneb612** [ultralytics/yolov5#5671]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

It would be nice to have the chence to quantize the model before exporting it .
I have tried to quantize my yolov5 model and then export it to a torchscript format. 
I was able to get the static_quantized model but then I could not convert it to the torchscript format, Any idea? 

### Use case

For Mobile Deployment !

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ireneb612 not sure. I searched https://pytorch.org/docs/stable/quantization.html for torchscript and there's zero mentions.

**Comment by ireneb612** [comment]
@glenn-jocher  read here: [https://pytorch.org/tutorials/recipes/script_optimized.html](url)

They say : "**After a PyTorch model is trained and optionally but preferably quantized** (see Quantization Recipe for more details), one essential step before the model can be used in iOS and Android apps is to convert the Python-dependent model to TorchScript, which can then further be optimized for mobile apps."

Let me know! Because I deployed Yolov5m model on a Mobile but it is too slow to function real-time and i think the only solution would be to quantize the model!
