### ISSUE TITLE
How to send YOLO Object detection result to another program (C# GUI) on the same computer?

### ISSUE THREAD

**Issue by PIjarihd** [ultralytics/yolov5#5678]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have successfully implemented and tested YOLOv5 for the custom dataset. The object detection using IPCamera is working fine. Now, I have to send the object detection result to the C# GUI running on the same computer. However, I could not figure out the way.
I am very new in programming. I studied some articles about changing the object detection results to json format. But I am afraid I am confused about the transmission part. How can I send the json format result to the C# GUI? do i have to use Socket programming? I need to this in real time.
Please guide me step-wise.
Thank you in advance.

**Comment by Zengyf-CVer** [comment]
@PIjarihd 
Can refer to this:https://github.com/ultralytics/yolov5/tree/master/utils/flask_rest_api
