### ISSUE TITLE
resume and wandb

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#5682]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

1. When I resume the weight, it show the below message.
   Do you have the readme to introduce the function? 
2. If I choose the (1), does it will use the new weight to train?

wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice:

**Comment by glenn-jocher** [comment]
@alicera W&B selection here has no impact on your training, this simply logs results to W&B, which is optional.
