### ISSUE TITLE
Pruning some classes in the model

### ISSUE THREAD

**Issue by rotem154154** [ultralytics/yolov5#5683]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to use some of the classes in yolo and I want to find a way to make the model faster by pruning weights that most used by classes that I don't care and to keep the model perform close to the original on the other classes

**Comment by glenn-jocher** [comment]
@rotem154154 we've done some pruning and sparsity experiments in https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity, though we have not invested significant effort in this direction. If you find better methods please submit a PR for future users, thank you.

**Comment by roulbac** [comment]
This function prunes the last layer of YOLO to only keep the classes of interest. 
Pass class_ids as a list of class ids you would like to keep in the model

```
def keep_classes(model, class_ids=[0]):
    with torch.no_grad():
        det_layer = model.model[-1]
        ch = tuple(m.weight.shape[1] for m in det_layer.m) # 192, 384, 768
        no = det_layer.no # no = 80 + 5
        na = det_layer.na # na = 3 (3 anchors per layer)
        nl = det_layer.nl
        indices = []
        for i in range(nl):
            for k in range(5):
                indices.append(k + no*i) # 0,1,2,3,4 + 6,7
            for class_id in class_ids:
                indices.append(5 + no*i + class_id)
        assert len(indices) == ((len(class_ids) + 5) * na)
        new_m = nn.ModuleList(nn.Conv2d(x, (5 + len(class_ids)) * na, 1) for x in ch)  # output conv
        for i in range(len(det_layer.m)):
            new_m[i].weight = nn.Parameter(
                det_layer.m[i].weight[indices, ...].clone().detach()
            )
            new_m[i].bias = nn.Parameter(
                det_layer.m[i].bias[indices, ...].clone().detach()
            )
        model.model[-1].m = new_m
        model.model[-1].nc = len(class_ids)
        model.model[-1].no = len(class_ids) + 5
        if hasattr(model, 'names'):
            model.names = [model.names[x] for x in class_ids]
```
