### ISSUE TITLE
How to load and inference using TFLITE model?

### ISSUE THREAD

**Issue by karndeepsingh** [ultralytics/yolov5#5684]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,
I have trained yolov5 model using yolov5l.pt weights and exported my model to TFLite. My query is, how can I load this TFLite model and use it for inferencing ? 
Please help.

Thanks

**Comment by glenn-jocher** [comment]
@karndeepsingh we've made inference with TFLite easy:

```bash 
python export.py --weights yolov5s.pt --include tflite
python detect.py --weights yolov5s-fp16.tflite
```

**Comment by karndeepsingh** [comment]
> @karndeepsingh we've made inference with TFLite easy:
> 
> ```shell
> python export.py --weights yolov5s.pt --include tflite
> python detect.py --weights yolov5s-fp16.tflite
> ```

Hi @glenn-jocher ,
I want to do some additional stuff with object detection. So, this loading of model and extra stuff with object detection has to done in a pipeline. Earlier, I was using torch.hub.load(  ) method to load the model and take inference out associated in pipeline.
 How similar type of loading and inferencing can be done using TFlite model?

**Comment by glenn-jocher** [comment]
@karndeepsingh designing custom pipelines is up to the architect of the custom pipeline. You can use the examples in this repo to get started.

**Comment by karndeepsingh** [comment]
@glenn-jocher  How will cropping of the detected object in an image be done when using this TFlite model?

**Comment by glenn-jocher** [comment]
@karndeepsingh YOLOv5 already does this, see detect.py argparser for details:
https://github.com/ultralytics/yolov5/blob/562191f5756273aca54225903f5933f7683daade/detect.py#L204-L235

**Comment by karndeepsingh** [comment]
@glenn-jocher Thanks for sharing. I was expecting that to load this TFlite model in torch.hub.load () method and function the similar way by using crop() method and save() method to save the result. But I feel, this same thing cant be achieved by torch.hub.load() methods instead I have to use detect.py file for TFlite model to process.

**Comment by karndeepsingh** [comment]
@glenn-jocher I have one more query please help me to understand. How to inference faster on CPU? 

 So for this inferencing time issue on CPU I converted the yolov5l trained model to onnx format and after conversion to onnx model from “pt” model, it increased its model size like from 140mb to 280mb. 
 My question here is,Why there is an increment in size and moreover is this increased onnx model would decrease the inferencing time on CPU or it will increase the inference time. I mean does this conversion of “pt” model to onnx model will improve on inferencing time?

Also,Please suggest better way to inference faster in CPU, if this approach seems to be improper.

Thanks in advance.

**Comment by glenn-jocher** [comment]
@karndeepsingh profiling results depend on many factors including your hardware so no one can tell you results but you. Detect.py displays profiling speeds automatically for any model.

torch.hub is for torch models.

**Comment by karndeepsingh** [comment]
> @karndeepsingh profiling results depend on many factors including your hardware so no one can tell you results but you. Detect.py displays profiling speeds automatically for any model.
> 
> torch.hub is for torch models.

Thank you so much. Any help, how can we reduce size of onnx model after conversion?
