### ISSUE TITLE
config NUM_THREADS for caching data or make .cache file compatible

### ISSUE THREAD

**Issue by iumyx2612** [ultralytics/yolov5#5685]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

So when I work with new dataset I have to cache data. But parameter NUM_THREAD is set too high cause program to crash
`NUM_THREADS = min(8, os.cpu_count())` 
my `os.cpu_count()` is actually 8, it use up all of my cpus and causing crash. 
I usually train yolov5 using Google Colab and interact with it there. But I want to debug something, so I downloaded my .cache file from colab to my local computer. I thought I won't go through a caching stage, but hash from the .cache file I downloaded from colab `cache['hash']` appeared to have different hash from `get_hash(self.label_files + self.img_files)` because of the the path on google colab is different from my local computer

### Use case

Low-end computers

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@iumyx2612 thanks for the feedback! What value of NUM_THREADS works on your system then? I've never seen any issues here even in resource constrained environments like Colab free.

**Comment by iumyx2612** [comment]
> @iumyx2612 thanks for the feedback! What value of NUM_THREADS works on your system then? I've never seen any issues here even in resource constrained environments like Colab free.

I have to use NUM_THREADS = 4 so it doesn't crash. 
For more info, my CPU is Intel Core i7-7700HQ @ 2.8Ghz (8CPUs). And I was using Pycharm + Google Chrome while caching

**Comment by glenn-jocher** [comment]
@iumyx2612 what happens if you do NUM_THREADS=6 or NUM_THREADS=7?

**Comment by iumyx2612** [comment]
> @iumyx2612 what happens if you do NUM_THREADS=6 or NUM_THREADS=7?

7 is okay. I tested while still opening Pycharm and tons of Google Chrome tabs

**Comment by glenn-jocher** [comment]
@iumyx2612 ok so it seems like a good first step is simply to update the code so that we leave at least 1 cpu free.
```python
NUM_THREADS = min(8, max(1, os.cpu_count() - 1))
```

**Comment by glenn-jocher** [comment]
@iumyx2612 good news 😃! Your original issue may now be fixed ✅ in PR #5706. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by iumyx2612** [comment]
> @iumyx2612 good news 😃! Your original issue may now be fixed ✅ in PR #5706. To receive this update:
> 
> * **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
> * **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
> * **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  [![Open In Colab](https://camo.githubusercontent.com/84f0493939e0c4de4e6dbe113251b4bfb5353e57134ffd9fcab6b8714514d4d1/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb) [![Open In Kaggle](https://camo.githubusercontent.com/a08ca511178e691ace596a95d334f73cf4ce06e83a5c4a5169b8bb68cac27bef/68747470733a2f2f6b6167676c652e636f6d2f7374617469632f696d616765732f6f70656e2d696e2d6b6167676c652e737667)](https://www.kaggle.com/models/ultralytics/yolov5)
> * **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image [![Docker Pulls](https://camo.githubusercontent.com/280faedaf431e4c0c24fdb30ec00a66d627404e5c4c498210d3f014dd58c2c7e/68747470733a2f2f696d672e736869656c64732e696f2f646f636b65722f70756c6c732f756c7472616c79746963732f796f6c6f76353f6c6f676f3d646f636b6572)](https://hub.docker.com/r/ultralytics/yolov5)
> 
> Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

The problem still persists, before I called `LoadImagesAndLabels` seperately on a script. Today, I ran `train.py` and CPU reached 100%, causing crash. I had to manually set NUM_THREADS to 4 and closed all other programs

**Comment by pderrenger** [comment]
Thanks for the update. Please ensure you're using the latest version of YOLOv5. If the issue persists, you might consider adjusting the `NUM_THREADS` in the `train.py` script to better suit your system's capabilities.
