### ISSUE TITLE
如何将使用yolov5n训练出来的best.pt转换成C++可以用的权重格式呢？

### ISSUE THREAD

**Issue by Wanghe1997** [ultralytics/yolov5#5686]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

作者您好。我使用v6.0版本代码，导入yolov5-nano模型训练了自己的数据集。现在因为项目需要，需要把best.pt转换成能在C++环境下使用的格式。有什么方法可以做到呢？你们有没有写类似的专题？如果有相关的教程可以分享给我吗？谢谢

### Additional
针对v6.0版本

**Comment by zhiqwang** [comment]
This question is determined by several factors, most typically your hardware device (e.g. whether you have a GPU, or whether you have an NPU boost).

**Comment by Wanghe1997** [comment]
> This question is determined by several factors, most typically your hardware device (e.g. whether you have a GPU, or whether you have an NPU boost).

i have one RTX3090 GPU.

**Comment by Wanghe1997** [comment]
> This question is determined by several factors, most typically your hardware device (e.g. whether you have a GPU, or whether you have an NPU boost).

Is there any way to convert best.pt to a form that can be used in the C++ environment（such as Visual Studio2019）under windows10? This is fine if the method is limited to Ubuntu

**Comment by zhiqwang** [comment]
I guess that you can try TensorRT as the backend.

**Comment by Wanghe1997** [comment]
> backend

Do you know libtorch? Is it currently applicable to yolov5n weight conversion of yolov5-6.0 version?

**Comment by zhiqwang** [comment]
I've done some experiments on libtorch http://github.com/zhiqwang/yolov5-rt-stack with YOLOv5 version 3.1 and above, maybe you can test whether it can satisfy your needs 😆

**Comment by Zengyf-CVer** [comment]
@Wanghe1997 
You can follow this step:
pt-->onnx-->weights

**Comment by UNeedCryDear** [comment]
如果你用的是vs2017以上的版本，也就是说支持MSVC 14.1以上的，那部署就很多了，像libTorch，tensorRT，ONNXRuntime,OpencCV等都可以，教程也多，但是如果是vs2015或者以前的版本（MSVC<=14.0）,那么基本上只有opencv可以走了，libTorch也只能使用不高于1.3的版本好像，而yolov5最低也要torch1.7，这部分还不知道说使用libtorch1.3能不能部署yolov5

**Comment by Wanghe1997** [comment]
> 如果你用的是vs2017以上的版本，也就是说支持MSVC 14.1以上的，那部署就很多了，像libTorch，tensorRT，ONNXRuntime,OpencCV等都可以，教程也多，但是如果是vs2015或者以前的版本（MSVC<=14.0）,那么基本上只有opencv可以走了，libTorch也只能使用不高于1.3的版本好像，而yolov5最低也要torch1.7，这部分还不知道说使用libtorch1.3能不能部署yolov5

现在的libtorch的教程好像都是针对以前的YOLOv5版本，比如3.0-5.0，不知道适不适用于最新的v6.0，是不是要过程中要改些代码或者参数？谢谢

**Comment by isomatical** [comment]
You can try exporting pt to torchscript.

**Comment by UNeedCryDear** [comment]
> 现在的libtorch的教程好像都是针对以前的YOLOv5版本，比如3.0-5.0，不知道适不适用于最新的v6.0，是不是要过程中要改些代码或者参数？谢谢
还没使用libtorch部署过6.0版本，暂时我也不知道
