### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by Melihemin** [ultralytics/yolov5#5688]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Will docker support come with documentation soon?

**Comment by glenn-jocher** [comment]
@Melihemin for Docker setup and use see https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/
