### ISSUE TITLE
changing yolo input dimensions using coco dataset 

### ISSUE THREAD

**Issue by yosefyehoshua** [ultralytics/yolov5#569]
hi, how can I change yolo to take input of size WxHx6xN instead of WxHx3xN?

Hi, I want to modify yolo to take 6 channel image, instead of 3, modifying to first layer is enough
Is there an easy way to do it? thanksntext

**Comment by glenn-jocher** [comment]
@yosefyehoshua torch hub tutorial has some info on varying input channels: https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading

**Comment by yosefyehoshua** [comment]
thanks for the answer. I'm now trying to train the model from torch.hub 
`model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=False, classes=10, channels=6)`

but while training:

```
`def train_m(model, criterion, optimizer, scheduler, dataloaders, datasets_size, num_epochs=25, phase='train'):
    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    for epoch in range(num_epochs):
        model.train()
        i = 0    
        for imgs, annotations in dataloaders['train']:
            print("imgs type: {}".format(type(imgs)))
            i += 1
            imgs = imgs.to(device, non_blocking=True).float() / 255.0
            annotations = [{k: v.to(device) for k, v in t.items()} for t in annotations]
            loss_dict = model(imgs, annotations)
            losses = sum(loss for loss in loss_dict.values())

            optimizer.zero_grad()
            losses.backward()
            optimizer.step()

            print(f'Iteration: {i}/{len_dataloader}, Loss: {losses}')`
```

my dataloader:

```
    train_ds = CustomCoco(root=train_coco_dir,
                          annotation=train_anno)
    val_ds = CustomCoco(root=val_coco_dir,
                          annotation=val_anno)

    
    def collate_fn(batch):
        return tuple(zip(*batch))

    train_batch_size = 4

    d_loader_train = torch.utils.data.DataLoader(train_ds,
                                            batch_size=train_batch_size,
                                            shuffle=True,
                                            num_workers=4,
                                            collate_fn=collate_fn)

    d_loader_val = torch.utils.data.DataLoader(val_ds,
                                            batch_size=train_batch_size,
                                            shuffle=True,
                                            num_workers=4,
                                            collate_fn=collate_fn)
    dataloaders = {'train': d_loader_train, 'val': d_loader_val}

    datasets_size = {'train': len(train_ds), 'val': len(val_ds)}
```




I'm gettting this error that my datakoader imgs is of 'tuple' type:

imgs = imgs.to(device, non_blocking=True).float() / 255.0
AttributeError: 'tuple' object has no attribute 'to'

what am I doing wrong?

**Comment by glenn-jocher** [comment]
@yosefyehoshua only torch tensors can be sent to a device. You've tried to do the same with a python tuple.

**Comment by yosefyehoshua** [comment]
> @yosefyehoshua only torch tensors can be sent to a device. You've tried to do the same with a python tuple.

yes because I need to use this function in my dataloader of else I get an error from collate.py 
`def collate_fn(batch):
        return tuple(zip(*batch))`
can you think about another solution?

**Comment by yosefyehoshua** [comment]
> > @yosefyehoshua only torch tensors can be sent to a device. You've tried to do the same with a python tuple.
> 
> yes because I need to use this function in my dataloader of else I get an error from collate.py
> `def collate_fn(batch): return tuple(zip(*batch))`
> can you think about another solution?

I'm basically trying to train this:
`model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=False, classes=10, channels=6)`
on custom coco dataset with 6 channels and a fixed 300x300 size images
