### ISSUE TITLE
Hyperparameter evolution doesnt terminate

### ISSUE THREAD

**Issue by myasser63** [ultralytics/yolov5#5690]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I ran hyperparameter in my own trained weights `best.pt` several times and the evolution process had the same two problem 

First the evolution doesnt stop after 300 generations `--evolve 300`. I tried stopping and resusming again and the evolution doesn't stop until crashing.

Second the evolve.csv only resords first few generations while hyp-evolve.yaml also doesn't include the results of the evolution, in my case on;y records 23 out of 300 generations.

**Comment by glenn-jocher** [comment]
@myasser63 👋 Hello! Thanks for asking about **resuming evolution**. If you have a reproducible bug please submit a bug report with steps to reproduce.

Resuming YOLOv5 🚀 evolution is a bit different than resuming a normal training run with `python train.py --resume`. If you started an evolution run which was interrupted, or finished normally, and you would like to continue for additional generations where you left off, then you pass `--resume` and specify the `--name` of the evolution you want to resume, i.e.:


## Start Evolution

Assume you evolve YOLOv5s on COCO128 for 2 epochs for 3 generations:
```shell
python train.py --epochs 10 --data coco128.yaml --weights yolov5s.pt --evolve 3
```
If this is your first evolution a new directory `runs/evolve/exp` will be created to save your results.
```shell
# ├── yolov5
#     └── runs
#         └── evolve
#             └── exp  ← evolution saved here
```

## Start a Second Evolution

Now assume you want to start a completely separate evolution: YOLOv5s on VOC for 5 epochs for 3 generations. You simply start evolving, and your new evolution will again be logged to a new directory `runs/evolve/exp2`:
```shell
python train.py --epochs 5 --data VOC.yaml --weights yolov5s.pt --evolve 3
```

You will now have two evolution runs saved:
```shell
# ├── yolov5
#     └── runs
#         └── evolve
#             ├── exp  ← first evolution (COCO128)
#             └── exp2  ← second evolution (VOC)
```

Notebook example: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
<img width="1396" alt="Screenshot 2021-09-15 at 12 23 13" src="https://user-images.githubusercontent.com/26833433/133416922-59a3e9f5-2630-4875-9c64-a982e312b400.png">


## Resume an Evolution

If you want to resume the first evolution (COCO128 saved to `runs/evolve/exp`), then you use the same exact command you started with plus `--resume --name exp`, passing the **additional** number of generations you want, i.e. `--evolve 30` for 30 more generations:
```shell
python train.py --epochs 10 --data coco128.yaml --weights yolov5s.pt --evolve 30 --resume --name exp
```
Evolution will run for an additional 30 generations and all new results will be added to the existing `runs/evolve/exp/evolve.csv`. 

Good luck and let us know if you have any other questions!
