### ISSUE TITLE
Provide tensor as input

### ISSUE THREAD

**Issue by mfoglio** [ultralytics/yolov5#5693]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is it possible to run the model on an image already stored as a torch tensor on the gpu? Should I perform any preprocessing? How should I interpret the output?

Example:
```
import cv2
import torch
import torch_tensorrt
import numpy as np
from PIL import Image
import requests

model = torch.hub.load("ultralytics/yolov5", "custom", path="/data/models/yolov5s6.pt")
model.eval()

url = "https://www.pexels.com/photo/170811/download/?search_query=car&tracking_id=jjn4hcch60g"
img = Image.open(requests.get(url, stream=True).raw)
img = np.array(img)
img = cv2.resize(img, (640, 640))
img = torch.from_numpy(img)
img = img.unsqueeze(0)
img = img.permute((0, 3, 1, 2))
img = img.to("cuda") 
img = img.float()
# Preprocessing?
print(model(img))
# Output?
```

EDIT: I fixed the error I had
EDIT2: for the preprocessing, is it sufficient to divide by 255 and have the image with shape BCHW?

**Comment by glenn-jocher** [comment]
@mfoglio you don't need any of that for YOLOv5, you just pass images directly to the model:

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Image
img = 'https://www.pexels.com/photo/170811/download/?search_query=car&tracking_id=jjn4hcch60g'

# Inference
results = model(img)
results.print()  # or .show(), .save()
```

**Comment by mfoglio** [comment]
I would like to do that since I already have the images on the GPU and it would be much faster if I wouldn't copy the images from VRAM to RAM to VRAM again.

**Comment by glenn-jocher** [comment]
@mfoglio then see detect.py
