### ISSUE TITLE
How to use hub.load load my own model?

### ISSUE THREAD

**Issue by yueyang07** [ultralytics/yolov5#5696]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to use hub.load load my own model? I've tried this code
model=torch.hub.load('/Users/yolo/','custom',path='weights/best.pt',source='local',force_reload=True)
and I use print(model),it could print the detail of the model,but when I used
results = model(img1, size=640)
results seemed to be not right,it doesn't have the funtion like pandas, xyxy
Any suggestions will be appreciated. Thank you

**Comment by glenn-jocher** [comment]
@yueyang07 the YOLOv5 AutoShape wrapper treats torch inputs as a pass-through. It handles preprocessing and postprocessing of all other formats (URLs, files, numpy arrays, PIL objects) and returns a Detections() instance.

**Comment by glenn-jocher** [comment]
@yueyang07 also if you use a local source there is nothing to force reload, so you can skip that argument.
