### ISSUE TITLE
Explain how non-max-suppression work?

### ISSUE THREAD

**Issue by muhammedakyuzlu** [ultralytics/yolov5#5697]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

First Big thanks for the work.
I'm trying to run the export TensorFlow saved model inside c++ code.
I managed to perpare the initial input and run the model successfully and got an out tensor with shape [25200,85],
now I need to apply NMS, 
The tensorflow::ops::NonMaxSuppression  and the cv::dnn::NMSBoxes  both of them can do that but I need to grab the perdition tensor to bbox take 2D matrix, scores take 1D vector and class_Id take 1D vector.

I did the bbox after converting it,   2D for bbox [num_boxes,4]     

but got confused about how to convert the 80 classes probabilities  plus the score into a single variable
1D for scores , 1D for class_Id 

can you explain how you did that so I can do it in c++ and apply NMS?

**Comment by muhammedakyuzlu** [comment]
Thanks god for print() function :) 
you multiply  obj_conf  with  cls_conf and take the highest score, BTW I loved the idea behind # boxes (offset by class), so simple

**Comment by coordxyz** [comment]
Hi, @muhammedakyuzlu, What's the idea behind #boxes (offset by class)? Why did they do this? Thx~
