### ISSUE TITLE
Questions about YOLOv5 PR

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#5698]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

@glenn-jocher 
I want to upload a PR, but I saw your guide and I did the operation. I was confused and didn't figure it out.
https://github.com/ultralytics/yolov5/blob/master/CONTRIBUTING.md
This is your interface:
![0000000](https://user-images.githubusercontent.com/41098760/142346157-5f5cd84b-3261-45c5-b422-281c68014af7.PNG)
This is the interface I see:
![1111111111](https://user-images.githubusercontent.com/41098760/142346184-89b741e4-8500-4a8f-84d5-4ea9dea73c5c.PNG)
**Since my local git cannot be uploaded now, I want to submit through the UI, what should I do?**

**Comment by glenn-jocher** [comment]
@Zengyf-CVer yes that's fine. If your green button is not enabled you probably haven't made any changes to the file. You can make your changes and then click the green button and follow the steps.

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
What happened when this happened?
![ksnip_20211118-210820](https://user-images.githubusercontent.com/41098760/142421201-40f4a590-7d06-4691-ac30-d09de580c0f8.png)

**Comment by glenn-jocher** [comment]
@Zengyf-CVer looks good! Then you just click the green button to create a PR.

**Comment by glenn-jocher** [comment]
@Zengyf-CVer these are automated CI checks on PRs. An X means that there is a problem, click details.

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
I changed the code again, there should be no problems now?
![11111111111](https://user-images.githubusercontent.com/41098760/142428757-ca5d5c93-29f6-4a0e-a07a-34642dfbbf31.PNG)

**Comment by glenn-jocher** [comment]
@Zengyf-CVer yes all CI checks are passing now!

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
Thank you very much.
