### ISSUE TITLE
Something about the code smell

### ISSUE THREAD

**Issue by rockyzhengwu** [ultralytics/yolov5#57]
thanks for your work first

I  just start to read the code in  ```utils/datasets.py```  , May be can give you some advice about the code,  you can  just ignore this or think about it.

some example
1, may be this can use a function not just write in the init , 
```
 try:
            path = str(Path(path))  # os-agnostic
            parent = str(Path(path).parent) + os.sep
            if os.path.isfile(path):  # file
                with open(path, 'r') as f:
                    f = f.read().splitlines()
                    f = [x.replace('./', parent) if x.startswith('./') else x for x in f]  # local to global path
            elif os.path.isdir(path):  # folder
                f = glob.iglob(path + os.sep + '*.*')
            else:
                raise Exception('%s does not exist' % path)
            self.img_files = [x.replace('/', os.sep) for x in f if os.path.splitext(x)[-1].lower() in img_formats]
        except:
            raise Exception('Error loading data from %s. See %s' % (path, help_url))

```
like this 
```

def load_image_files(path):
    path = str(Path(path))
    parent = str(Path(path).parent) + os.sep
    if os.path.isfile(path):
        with open(path, 'r') as f:
            image_names = f.read().splitlines()
            image_names = [x.replace('./', parent) if x.startswith('./') else x for x in image_names]
    elif os.path.isdir(path):
        image_names = glob.iglob(path + os.sep + '*.*')
    else:
        raise Exception('%s does not exist' % path)
    img_files = [name.replace('/', os.sep) for name in image_names if
                      os.path.splitext(name)[-1].lower() in IMG_FORMATS]
    return img_files

```

2. I think you can name ```ar``` to ```aspect_ratio``` not comment behind 
```
  ar = s[:, 1] / s[:, 0]  # aspect ratio
```

there are some other like this two, but i think this is not import , 
in fact , i'm not sure if i want to  summit this issues , because i also not write  clean code.

**Comment by glenn-jocher** [comment]
@rockyzhengwu thanks for your feedback! You are right that the code could use some cleanup. Best practices is to drop code into functions when it repeated elsewhere, but in this case I believe this is the only location this code block is used.

In any case there is improvement that could be made in variable naming and error checking in this code region like you mention.
