### ISSUE TITLE
Torch-TensorRT

### ISSUE THREAD

**Issue by Auth0rM0rgan** [ultralytics/yolov5#5700]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi @glenn-jocher, 

Nvidia introduced `Torch-TensorRT` for pytorch to accelerate the deep learning models during inference time some days ago. I wanted to ask you that have you tried to use `Torch-TensorRT` with the YoloV5 and see how will effect the inference time. Based on the available information, it should accelerate 3x with half precision and it seems easy to use. Im trying to use the `Torch-TensorRT` but i have problem with installation the `Torch-TensorRT`....

Here are links for `Torch-TensorRT`:   
https://github.com/NVIDIA/Torch-TensorRT
https://github.com/NVIDIA/Torch-TensorRT/blob/master/notebooks/Resnet50-example.ipynb

**Comment by glenn-jocher** [comment]
@Auth0rM0rgan no, I have not used it myself, though just today we received a TRT PR https://github.com/ultralytics/yolov5/pull/5699 for export and inference with detect.py.

You should place a feature request with NVIDIA to create a https://github.com/NVIDIA/Torch-TensorRT/blob/master/notebooks/YOLOv5-example.ipynb

If you make progress on this please update us, thanks!

**Comment by zhiqwang** [comment]
FYI, Seems that this issue try to make Torch-TensorRT work on YOLOv5: https://github.com/NVIDIA/Torch-TensorRT/issues/730 .

**Comment by mfoglio** [comment]
Yes, @zhiqwang that's exactly what I am trying to do, even though this PR seems not to use the new library `torch_tensorrt` but it seems to convert from PyTorch to ONNX and then to TensorRT

**Comment by zhiqwang** [comment]
Hi @mfoglio , I love the design of `torch_tensorrt`, and the exported `torchscript` graph will be more clean than `onnx` in my previous experiments. I'm looking forward to YOLOv5 being successfully used upon `torch_tensorrt`. (Unfortunately, there is no way for me to do some relevant tests now due to hardware resource limitations.)

**Comment by Rm1n90** [comment]
Maybe solution can be by exporting the weight file directly to TensorRT or Torchscript with 'export.py' and then compile it with the Torch-TensorRT

I will try it tomorrow by myself.

**Comment by mfoglio** [comment]
@Rm1n90 I tried here https://github.com/NVIDIA/Torch-TensorRT/issues/730#issuecomment-973070435 but maybe you'll succeed

**Comment by leeyunhome** [comment]
> 

Hello, @Rm1n90 

Thank you for your trial.

Did you succeed? If so, can you tell me how?

Thank you.

**Comment by zhiqwang** [comment]
FYI @leeyunhome , 

Finally I use the vanilla TensorRT to do inference with YOLOv5, check out https://zhiqwang.com/yolov5-rt-stack/notebooks/onnx-graphsurgeon-inference-tensorrt.html for more details, and [here](https://github.com/zhiqwang/yolov5-rt-stack/blob/main/deployment/tensorrt/) is a C++ infereface.
