### ISSUE TITLE
Why load different images for training and validating

### ISSUE THREAD

**Issue by iumyx2612** [ultralytics/yolov5#5704]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

in `train.py` 
```
   # Train Loader
    train_loader, dataset = create_dataloader(train_path, img_size, batch_size, grid_size,
                                              hyp=hyp, augment=False, cache=args.cache, rect=args.rect,
                                              workers=workers, image_weights=args.image_weights, quad=args.quad,
                                              prefix=colorstr('Train: '))
```
There's the `rect=args.rect` and usually I set this to false
```
    # Val Loader
    val_loader = create_dataloader(val_path, img_size, batch_size * 2, grid_size,
                                   hyp=hyp, cache=None if no_val else args.cache, rect=True,
                                   workers=workers, pad=0.5,
                                   prefix=colorstr('Val: '))[0]
```
But while loading image with `rect=True` in val_loader?

**Comment by glenn-jocher** [comment]
@iumyx2612 validation uses rectangular inference for faster speeds. You can set this to false and compare speeds and val_batch*.jpg images for those batches actually look like.

**Comment by iumyx2612** [comment]
> @iumyx2612 validation uses rectangular inference for faster speeds. You can set this to false and compare speeds and val_batch*.jpg images for those batches actually look like.

Thank you, I have one more question
While validating, you scale prediction box
```
            normed_pred = pred.clone()
            scale_coords(img[si].shape[1:], normed_pred[:, :4], shape, shapes[si][1])  # native-space pred
```
As well as target box
```
                target_boxes = xywh2xyxy(labels[:, 1:5])  # target boxes
                scale_coords(img[si].shape[1:], target_boxes, shape, shapes[si][1])  # native-space labels
```
Is this a must? Can I use `val.process_batch()` without scaling them?

**Comment by glenn-jocher** [comment]
@iumyx2612 sure you can do whatever you want. The code is here as a starting point for your own adventures. Note though that due to high demand we are not able to provide personal support for code modifications.

**Comment by iumyx2612** [comment]
> @iumyx2612 sure you can do whatever you want. The code is here as a starting point for your own adventures. Note though that due to high demand we are not able to provide personal support for code modifications.

aight thank you, I was afraid doing that would cause heavy bugs or wrong results
