### ISSUE TITLE
getting it to run on Jetson nano Ubuntu18.04LTS

### ISSUE THREAD

**Issue by synersignart** [ultralytics/yolov5#5705]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

1. is there a tutorial that  is easy to understand for Ubuntu 18.04 and 20 users like additional requirements in the requirements.txt
2. when I run Python train.py or detect.py is shows  Syntax Error : Non-ASCII Character '\xf0' 
3. getting to run on CSI camera

also addition Tutorial for Windows user Standalone CMD with one click Bat file to install or run functions

### Environment

YOLOV5
-----------------------------------------
Ubuntu 18.04 (Jetson Nano img) 
Python 3.9
-----------------------------------------
Windows 10
CMD.exe

### Minimal Reproducible Example

python train.py

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@synersignart as I just told another user these devices are really only meant as deployment destinations for already trained models. Your workflow would be to train a model in the cloud or with a local desktop GPU, then export to a deployment format like TRT and deploy to Jetson.

**Comment by synersignart** [comment]
ah ok , but for running lets say detect.py the same error pops out.  id like to have a tutorial that explains on a windows or linux environment as the tutorial here only shows google collab which is inconvenient for some of us to upload then download data

**Comment by glenn-jocher** [comment]
Ok understood. Checking your original post I forgot to answer one of the questions: there are no additional requirements, all requirements are in requirements.txt for all operating systems, i.e. see CI tests on Windows, Ubuntu and MacOS:
https://github.com/ultralytics/yolov5/actions/runs/1492679060
