### ISSUE TITLE
Large yolov5 image 

### ISSUE THREAD

**Issue by lchunleo** [ultralytics/yolov5#5708]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

my intention is to have a docker image to be used for inferencing . When either pulling an prebuilt yolov5 docker image or customised yolov5 docker image , i realised the docker image size can be from 17 GB to 20 GB. I noted that the nvidia pytorch image is about 5+ GB, i wonder if i can cut down the image size a smaller one? Unsure what is the component(s) that are taking the space. Please advise. Thank you

**Comment by glenn-jocher** [comment]
@lchunleo yes the Docker images are typically on the order of 6-7 GB. 

We don't add much ourselves, most of the size comes from the NVIDIA base images at https://ngc.nvidia.com/catalog/containers/nvidia:pytorch (6.5GB), while the YOLOv5 image is 6.9GB.

https://hub.docker.com/r/ultralytics/yolov5/tags
<img width="972" alt="Screenshot 2021-11-18 at 17 26 00" src="https://user-images.githubusercontent.com/26833433/142455570-0c91a9da-16de-45fe-99dc-2b418555b349.png">

**Comment by lchunleo** [comment]
> @lchunleo yes the Docker images are typically on the order of 6-7 GB.
> 
> We don't add much ourselves, most of the size comes from the NVIDIA base images at https://ngc.nvidia.com/catalog/containers/nvidia:pytorch (6.5GB), while the YOLOv5 image is 6.9GB.
> 
> https://hub.docker.com/r/ultralytics/yolov5/tags <img alt="Screenshot 2021-11-18 at 17 26 00" width="972" src="https://user-images.githubusercontent.com/26833433/142455570-0c91a9da-16de-45fe-99dc-2b418555b349.png">

Thank you @glenn-jocher for your reply. I noted that when pulling the docker for yolov5, it is already 20GB. Thus i sum the 7 GB (nvidia pytorch) and yolov5 itself (7GB), it should be around 14 GB, thus am wondering where does the additional 6GB comes from? thanks

**Comment by glenn-jocher** [comment]
@lchunleo your math is not correct. The screenshot I've displayed obviously shows the YOLOv5 image size to be 6.91 GB.
