### ISSUE TITLE
How to reduce the model size after converting the PyTorch model to TensorFlow one?

### ISSUE THREAD

**Issue by AI-Passionner** [ultralytics/yolov5#5712]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Very appreciative of such wonderful work to all YOLOV5 developers. 
I used the training scripts to get the PyTorch model, which was around 14MB (best.pt). However, after converting to the TensorFlow (saved_model) using `export.py`, It gives me a total of 220MB (including the variable folder and xx.pt file). Wondering if I made something wrong during the conversion? Thanks.

**Comment by Zengyf-CVer** [comment]
@AI-Passionner 
There are many files after the transfer, and one of the folders is relatively large, which is normal.
