### ISSUE TITLE
Autobalance in the loss calculation function

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#5716]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

@glenn-jocher 
What is the role of `autobalance` in loss calculation?
https://github.com/ultralytics/yolov5/blob/8df64a912274ea3a82df2f96f0e3c3ab95713502/utils/loss.py#L93
https://github.com/ultralytics/yolov5/blob/8df64a912274ea3a82df2f96f0e3c3ab95713502/utils/loss.py#L157-L158

**Comment by glenn-jocher** [comment]
@Zengyf-CVer autobalance will balance loss gains among the P3-P6 output layers so that they each contribute equally to the total loss. It uses a smoothing algorithm similar to EMA to adjust the output layer loss balancing gradually over time. It is off by default, but we've used it in the past to estimate good balancing parameters which are now in place.

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
Thank you very much.

**Comment by konioy** [comment]
If I have two detect layers and the corresponding strides are 16, 32, should I take (4, 1) or (1, 0.4) for the lobj weights of each layer?

**Comment by glenn-jocher** [comment]
@konioy it's up to you but the general idea is that if the number of positives is the same the negatives will be 1/4x at 2x the stride so this is meant to balance that effect.

**Comment by konioy** [comment]
Then why when there are 3 detect layers, the weight ratio of lobj is 4:1:0.4? 
I only took the last two layers of the three layers, where the strides are 16, 32, , respectively. 
So, should I take the weight ratio of lobj as 1:0.4?

**Comment by glenn-jocher** [comment]
@konioy all parameters in YOLOv5 are informed by empirical results on COCO.
