### ISSUE TITLE
Some thoughts on CIoU

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#5717]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

@glenn-jocher 
I see CIoU in yolov5 is like this:
https://github.com/ultralytics/yolov5/blob/8df64a912274ea3a82df2f96f0e3c3ab95713502/utils/metrics.py#L229
But CIoU in the paper needs to be subtracted with `1`, while CIoU in yolov5 does not seem to be subtracted with `1`. Why?
![1111111111](https://user-images.githubusercontent.com/41098760/142574548-47ae2182-a235-490e-a8f4-77b0cdf0caa6.PNG)

**Comment by thuangb** [comment]
You can look further in the code. At the end, it will be subtract by 1 so from iou **-** (rho2 / c2 + v * alpha) it will become 1 - iou **+** (rho2 / c2 + v * alpha)

**Comment by Zengyf-CVer** [comment]
@thuangb 
Thank you, can you send me the specific code piece?

**Comment by Zengyf-CVer** [comment]
@thuangb 
I saw it, thank you.
