### ISSUE TITLE
W&B production drawing

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#5718]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

@AyushExel 
I see this feature, you can select the first few lines. But I want to choose freely. I can skip a few, choose some models, and then draw. Is there this function? How should I achieve it? thanks.
![1111111](https://user-images.githubusercontent.com/41098760/142604209-e0d8ada1-1e0f-44ad-9384-0506809ac591.PNG)

**Comment by AyushExel** [comment]
@Zengyf-CVer you can choose which runs to visualize from your dashboard. Click the "eye" button to hide/show a run

**Comment by Zengyf-CVer** [comment]
@AyushExel 
I learned, thank you very much.
