### ISSUE TITLE
High precision from the start of the training

### ISSUE THREAD

**Issue by mim201820** [ultralytics/yolov5#5719]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm training using the yolov5s.pt on 30K images of 640x640 I want to detect one class on the images after training using 48 batch size and 100 epochs I found the following results. My question is that why do we get a high precision and recall starting from the 2nd epochs (~0.9)
![F1_curve](https://user-images.githubusercontent.com/65327419/142627431-36cd6137-cc92-4167-a9e4-b5f55a418131.png)
![P_curve](https://user-images.githubusercontent.com/65327419/142627433-ea946505-fb02-4f25-8de3-28316b95d446.png)
![PR_curve](https://user-images.githubusercontent.com/65327419/142627435-0e7a4476-aca6-4e55-8f69-3826cd6b31e8.png)
![R_curve](https://user-images.githubusercontent.com/65327419/142627436-8f65fa47-ee3f-4252-8b0c-a9e702d24c0a.png)
![results](https://user-images.githubusercontent.com/65327419/142627441-b8906057-1b59-4b0f-876e-fac29d6689e0.png)

**Comment by glenn-jocher** [comment]
@mim201820 metrics display your training results. I don't understand what you are asking exactly.

**Comment by mim201820** [comment]
I don't understand why my results are good from the start shouldn't we have some bad results at the start then after some epochs we see some good results.
And I want to know if my model is becoming overfitting at the end?

**Comment by glenn-jocher** [comment]
@mim201820 you're unhappy with your good results? 

We have extremely little time for support and the team is very overextended, please do not ask whimsical questions.
