### ISSUE TITLE
"RuntimeError: Unable to find a valid cuDNN algorithm to run convolution when training on host machine with gpu " error

### ISSUE THREAD

**Issue by nebiyebulan** [ultralytics/yolov5#5720]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I created a virtual environment. I installed the necessary libraries. I loaded my own dataset into it. I installed pytorch and torchvision to use gpu. I'm getting this error before the first step starts. 
""RuntimeError: Unable to find a valid cuDNN algorithm to run convolution when training on host machine with gpu
"error" .Please help me.
![1](https://user-images.githubusercontent.com/62153842/142629790-7d684333-746b-441c-a714-8863613497c8.png)

**Comment by glenn-jocher** [comment]
@nebiyebulan 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by Zengyf-CVer** [comment]
@nebiyebulan 
Your gpu memory has overflowed. Reduce the Batch Size or reduce the image size.

**Comment by nebiyebulan** [comment]
i tried this @Zengyf-CVer . I reduced the batch size from 8 to 2. I reduced the image size from 640 to 480. But I still get the same error. is there any other way?

**Comment by Zengyf-CVer** [comment]
@nebiyebulan 
Your PyTorch and Cuda models may not match, please refer to this link: https://pytorch.org/
![333](https://user-images.githubusercontent.com/41098760/142827848-d3d27dd4-0514-4ce3-9d31-4d37caec69ce.PNG)
Change the installation instructions according to your Cuda model.

**Comment by nebiyebulan** [comment]
cuda=10.2 torch=1.8.0 torchvision=0.9.0 versions available. @Zengyf-CVer

**Comment by glenn-jocher** [comment]
@nebiyebulan you should probably verify correct operation on CPU first:
```
python train.py --device cpu
```

**Comment by nebiyebulan** [comment]
Training takes place with CPU. @glenn-jocher

**Comment by glenn-jocher** [comment]
@nebiyebulan then it appears you may have environment issues related to CUDA/CUDNN. Visit https://pytorch.org/get-started/locally/

Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual Python 3.8 environment, clone the latest repo ([code changes daily](https://github.com/ultralytics/yolov5/commits/master)), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below. 


## Requirements

[**Python>=3.6.0**](https://www.python.org/) with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) installed including [**PyTorch>=1.7**](https://pytorch.org/get-started/locally/). To get started:
```bash
$ git clone https://github.com/ultralytics/yolov5
$ cd yolov5
$ pip install -r requirements.txt
```

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), validation ([val.py](https://github.com/ultralytics/yolov5/blob/master/val.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/export.py)) on MacOS, Windows, and Ubuntu every 24 hours and on every commit.

**Comment by Zengyf-CVer** [comment]
@nebiyebulan 
Enter `pip list` and send me a screenshot of your complete virtual environment.

**Comment by nebiyebulan** [comment]
sure. @Zengyf-CVer 
![2](https://user-images.githubusercontent.com/62153842/142871295-2c2dfd38-8bcf-4797-9c3d-33fb65245896.png)

**Comment by Zengyf-CVer** [comment]
@nebiyebulan 
You are using cuda 10.2, so I think the problem is here. If conditions permit, you can reinstall Cuda, and the version is 11.x, just follow the instructions on the PyTorch official website to install it. At present, I am using cuda11.1 without your problem.

**Comment by nebiyebulan** [comment]
@Zengyf-CVer I'm having trouble changing my cuda version can I upgrade the existing one? is there any other way?

**Comment by Zengyf-CVer** [comment]
@nebiyebulan 
First of all, I use Ubuntu 20.04, and secondly, if you want to upgrade Cuda, I suggest you to uninstall all three of the previous Cuda, CuDNN and graphics driver, and then reinstall it. Finally, if it is still unsuccessful, do the system again and repeat the second step.

**Comment by nebiyebulan** [comment]
I am using 18.4. I just reset jetson xavier. 11.1 OS is not compatible with my system? @Zengyf-CVer

**Comment by Zengyf-CVer** [comment]
@nebiyebulan 
If you have enough time, I suggest to install Ubuntu 20.04 and try it.

**Comment by nebiyebulan** [comment]
@Zengyf-CVer  I said I'm using jetson agx xavier. Can I pretend to change the normal operating system on this with 18.4 installed?

**Comment by PhilipRS892** [comment]
did you solved this problems?

**Comment by balajib363** [comment]
Facing the same issue, requesting to share if there are any fixes.

**Comment by MasterHM-ml** [comment]
> @nebiyebulan Your gpu memory has overflowed. Reduce the Batch Size or reduce the image size.

Can't believe reducing image-size / batch-size really fixed the issue. Thank you so much

**Comment by aliaminibagh** [comment]
> did you solved this problems?

I solved it by reduce batch size from 32 to 16 !

**Comment by mikahoy045** [comment]
I confirmed by reduce batch size / image size then the issue is disappear

**Comment by acsgn95** [comment]
It is about GPU RAM full. I couldn't see your batch_size. Please check the batch_size and reduce it. If it's still giving problem, do reduce it.

**Comment by glenn-jocher** [comment]
@acsgn95 glad to hear that reducing the batch size or image size helped solve the issue! Reducing the batch size and image size is a common workaround when faced with "GPU RAM full" issues, as it helps reduce the amount of memory needed for processing. 

In cases where reducing the batch size or image size is not an option, other possible solutions might be to try using a larger GPU with more VRAM or to implement techniques such as model distillation or mixed precision training. These techniques can help reduce the memory footprint of the model and enable it to run on GPUs with less VRAM.
