### ISSUE TITLE
Partial map or whole map?

### ISSUE THREAD

**Issue by sarpx** [ultralytics/yolov5#5723]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Some tags overlap. In this case, when I make a map that covers the whole tag, it includes the other tag. In this case, should I divide it into two or three parts instead of one label? Or should I make a single map that covers an entire tag no matter how many other tags it intersects?
Thank you for your attention

### Additional

![a1](https://user-images.githubusercontent.com/73984193/142677618-e0ef80a9-eae5-4417-b500-acadce0a5265.JPG)
![a2](https://user-images.githubusercontent.com/73984193/142677619-3b389dcf-1661-4a59-a9f1-c11f8b2f5704.JPG)

**Comment by glenn-jocher** [comment]
@sarpx the only thing to remember is that the model will learn whatever you teach it. Label your images exactly the way you want your model to predict them.
