### ISSUE TITLE
Why the converted onnx model has 6 by 6 kernel at the beginning?

### ISSUE THREAD

**Issue by matinhosseiny** [ultralytics/yolov5#5728]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I converted the yolov5 model to an onyx model and I found out it has 6 by 6 convolution. how can I convert it back to the conv 3 by 3?

**Comment by glenn-jocher** [comment]
@matinhosseiny ONNX conversion is correct. You can modify anything you want, the model will not work anymore though.
