### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\montg/.cache\\torch\\hub\\ultralytics_yolov5_master\\hubconf.py'

### ISSUE THREAD

**Issue by CodexImperium** [ultralytics/yolov5#5729]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

I ran the sample code model = torch.hub.load("ultralytics/yolov5", "yolov5s") but it the error on the title appeared and I havent found any similar problems on the bug issues

### Environment

- OS Windows 10
- Python: Python 3.8.10
- YOLOv5  

### Minimal Reproducible Example

model = torch.hub.load("ultralytics/yolov5", "yolov5s")

### Additional

![image](https://user-images.githubusercontent.com/45186933/142713898-58bd0e25-848c-4702-8b37-1ad1ef081f8e.png)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@CodexImperium this is a torch problem and should be raised on the pytorch repository:
https://github.com/pytorch/pytorch
