### ISSUE TITLE
Pretrain Weights Problems

### ISSUE THREAD

**Issue by ClassNotDefined** [ultralytics/yolov5#5732]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Pretrained weights can only be loaded with same code directory structure

### Additional

I made some mistakes in using "experimental.attempt_load".  I used this module in my own project and it run out error:
Module Not Found Error: No Module Named "models".<br>

I solved it by:

```
ckpt = torch.load(weights, map_location=device)
model = Model(cfg or ckpt['model'].yaml, ch=3, nc=nc, anchors=anchors).to(device)
exclude = ['anchor']
csd = ckpt['model'].float().state_dict()  # checkpoint state_dict as FP32
csd = intersect_dicts(csd, model.state_dict(), exclude=exclude) 
model.load_state_dict(csd, strict=False) 
```

_No response_

**Comment by glenn-jocher** [comment]
@ClassNotDefined I'm sorry I don't understand the question. Can you be more precise?

**Comment by Zengyf-CVer** [comment]
@ClassNotDefined 
It can be arbitrarily matched, but it is best to correspond. You can have a try.

**Comment by ClassNotDefined** [comment]
I made some mistakes in using "experimental.attempt_load". I used this module in my own project and it run out error:
Module Not Found Error: No Module Named "models".

I solved it by:

```
ckpt = torch.load(weights, map_location=device)
model = Model(cfg or ckpt['model'].yaml, ch=3, nc=nc, anchors=anchors).to(device)
exclude = ['anchor']
csd = ckpt['model'].float().state_dict()  # checkpoint state_dict as FP32
csd = intersect_dicts(csd, model.state_dict(), exclude=exclude) 
model.load_state_dict(csd, strict=False) 
```
