### ISSUE TITLE
how to load my own trained yolov5,so i can use like result = model(img)

### ISSUE THREAD

**Issue by nouise** [ultralytics/yolov5#5733]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

when I  use the yolov5 to detect the object in the real-time game, so i need load the yolov5 instead of console. i have tried the `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)`,however ,i don't know how to load my own trained best.pt

**Comment by glenn-jocher** [comment]
@nouise see PyTorch Hub tutorial for loading custom models:

<img width="887" alt="Screenshot 2021-11-20 at 14 38 10" src="https://user-images.githubusercontent.com/26833433/142728416-ec4d2d73-8b96-48ef-a7cc-8285156f7af9.png">

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by nouise** [comment]
> 

![image](https://user-images.githubusercontent.com/94746680/142796925-b335edc5-81ee-4463-9ab3-9ebc80c16964.png)
thank you first,however i will meet  this question by that way

**Comment by glenn-jocher** [comment]
@nouise if you are loading locally you need to ensure your paths are correct.
