### ISSUE TITLE
A problem while loading a custom trained yolov5s model

### ISSUE THREAD

**Issue by SoroushMaleki27** [ultralytics/yolov5#5735]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi everyone,
I have recently trained a yolov5 model on my own dataset of "Rollaydor" pictures. After training, the best weights got saved in the corresponding "run" folder which is good. Also, the "detect.py" file works fine and when used, it can detect the required object perfectly.
However, when I want to load the saved model to perform inference in my own code, I run into a strange error that I did not find a solution for. Here is my code:

![3](https://user-images.githubusercontent.com/94774656/142750885-d41ec013-0dab-49a7-a707-3d2aa19c7017.PNG)

And this is the error that I get:

![image](https://user-images.githubusercontent.com/94774656/142750902-86c0dfd4-f528-4663-a2a0-28413e18b158.png)

It seems like that the weights are saved in the wrong format during training and thus, they cannot be loaded. Does anyone have any idea how to solve this issue?

**Comment by Zengyf-CVer** [comment]
@SoroushMaleki27 
See https://github.com/ultralytics/yolov5/blob/5185981993737861575adb07f2817a74fa4b2baa/models/common.py#L305

**Comment by glenn-jocher** [comment]
@SoroushMaleki27 your workflow is incorrect. See YOLOv5 **PyTorch Hub** tutorial for loading custom models:

<img width="887" alt="Screenshot 2021-11-20 at 14 38 10" src="https://user-images.githubusercontent.com/26833433/142765332-a70eb949-925d-4e11-925c-8969c0d188d6.png">

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by SoroushMaleki27** [comment]
> @SoroushMaleki27 See
> 
> https://github.com/ultralytics/yolov5/blob/5185981993737861575adb07f2817a74fa4b2baa/models/common.py#L305

Thanks for your reply.

**Comment by SoroushMaleki27** [comment]
> @SoroushMaleki27 your workflow is incorrect. See YOLOv5 **PyTorch Hub** tutorial for loading custom models:
> 
> <img alt="Screenshot 2021-11-20 at 14 38 10" width="887" src="https://user-images.githubusercontent.com/26833433/142765332-a70eb949-925d-4e11-925c-8969c0d188d6.png">
> 
> ## YOLOv5 Tutorials
> * [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)  🚀 RECOMMENDED
> * [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)  ☘️ RECOMMENDED
> * [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)  🌟 NEW
> * [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)  🌟 NEW
> * [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
> * [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)  ⭐ NEW
> * [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
> * [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
> * [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
> * [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
> * [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
> * [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)  ⭐ NEW
> * [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

Thank you, Glenn, really appreciate it. I don't know why I could not find the tutorial at first.

**Comment by pderrenger** [comment]
You're welcome! If you have any more questions or need further assistance, feel free to ask.
