### ISSUE TITLE
Anchor Number

### ISSUE THREAD

**Issue by aseprohman** [ultralytics/yolov5#5738]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello @glenn-jocher et all,

Does increasing the number of anchors per output layer affect the model's performance ? e.g longer inference speed or maybe better result in detection accuracy if anchor number fit the model and dataset condition ? maybe somebody can share some experience here ? 
thanks

**Comment by glenn-jocher** [comment]
@aseprohman see YOLOv2 paper Figure 2:
https://arxiv.org/pdf/1612.08242.pdf
