### ISSUE TITLE
If you want to change Language you use, This will work

### ISSUE THREAD

**Issue by Huni0331** [ultralytics/yolov5#5739]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Add the font of the language you use.

### Use case

Plots.py
line 85~

       def box_label(self, box, label='', color=(128, 128, 128), txt_color=(255, 255, 255)):
        # Add one xyxy box to image with label
        if self.pil or not is_ascii(label):
            self.draw.rectangle(box, width=self.lw, outline=color)  # box
            if label:
                w, h = self.font.getsize(label)  # text width, height
                outside = box[1] - h >= 0  # label fits outside box
                self.draw.rectangle([box[0],
                                     box[1] - h if outside else box[1],
                                     box[0] + w + 1,
                                     box[1] + 1 if outside else box[1] + h + 1], fill=color)
                # self.draw.text((box[0], box[1]), label, fill=txt_color, font=self.font, anchor='ls')  # for PIL>8.0
        self.font_MYFONT = ImageFont.truetype("/MY_FONT/NotoSansKR-Bold.otf", 40)
        self.draw.text((box[0], box[1] - h if outside else box[1]), label, fill=txt_color, font=self.font_MYFONT)

               

> self.font_MYFONT = ImageFont.truetype("/MY_FONT/NotoSansKR-Bold.otf", 40)

**

> self.draw.text((box[0], box[1] - h if outside else box[1]), label, fill=txt_color, font=self.font_MYFONT)

**

### Additional

.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Huni0331 yes that's correct. You should be able to introduce any font you want in the Annotator class. Default is Arial.ttf:
https://github.com/ultralytics/yolov5/blob/5185981993737861575adb07f2817a74fa4b2baa/utils/plots.py#L68-L84

**Comment by Huni0331** [comment]
@glenn-jocher 

I wandered around a lot. 
Thank you
