### ISSUE TITLE
Apex.amp.initialize: lr_scheduler.LambdaLR AttributeError: 'function' object has no attribute '__self__'

### ISSUE THREAD

**Issue by Zepyhrus** [ultralytics/yolov5#574]
## 🐛 Bug
During training with mixed precision, scheduler initialized failed with `AttributeError: 'function' object has no attribute '__self__'`.

## To Reproduce (REQUIRED)

Input:
```
if mixed_precision:
        model, optimizer = amp.initialize(model, optimizer, opt_level='O1', verbosity=0)

lf = lambda x: (((1 + math.cos(x * math.pi / epochs)) / 2) ** 1.0) * 0.9 + 0.1  # cosine
scheduler = lr_scheduler.LambdaLR(optimizer, lr_lambda=lf)
```

Output:
```
Optimizer groups: 62 .bias, 70 conv.weight, 59 other
Traceback (most recent call last):
  File "train.py", line 477, in <module>
    train(hyp, tb_writer, opt, device)
  File "train.py", line 167, in train
    scheduler = lr_scheduler.LambdaLR(optimizer, lr_lambda=lf)
  File "/home/ubuntu/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/optim/lr_scheduler.py", line 189, in __init__
    super(LambdaLR, self).__init__(optimizer, last_epoch)
  File "/home/ubuntu/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/optim/lr_scheduler.py", line 74, in __init__
    self.optimizer.step = with_counter(self.optimizer.step)
  File "/home/ubuntu/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/optim/lr_scheduler.py", line 56, in with_counter
    instance_ref = weakref.ref(method.__self__)
AttributeError: 'function' object has no attribute '__self__'
```

## Expected behavior
Scheduler initialized successfully.

## Environment

 - OS: ubuntu 18.04
 - GPU: Tesla P2000;
 - CUDA: 10.2;
 - torch: 1.5.1/1.6.0 has the same probelm both;
 - apex: 0.1;

## Additional context
Following [this](https://github.com/ultralytics/yolov3/issues/912) exactly the same problem in yolov3, I have reinstall pytorch/apex pefectly, but problem persists. 

The interesting thing is: when I set `model, optimizer = amp.initialize(model, optimizer, opt_level='O1', verbosity=0)` the `opt_level` option to `O2` or `O0`, problem solved, but the training loss will yield infinite in several steps.

If I disable `mixed_precision`, training problem totally solved, hope this will provide some cues for debugging.

**Comment by glenn-jocher** [comment]
There is a PR open for pytorch 1.6. native amp. You can use this branch or simply wait a few days for it to get merged with origin/master. See https://github.com/ultralytics/yolov5/pull/573

**Comment by Zepyhrus** [comment]
> There is a PR open for pytorch 1.6. native amp. You can use this branch or simply wait a few days for it to get merged with origin/master. See #573

Hi glenn, thanks for replying. The problem is, this issue persists when I switch back to Pytorch 1.5.1.

**Comment by glenn-jocher** [comment]
it appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below. 


## Requirements

**Python 3.8** or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including **`torch>=1.6`**. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by Zepyhrus** [comment]
Cool, I'll try upgrading my env later and update this issue if any helpful information cuts.
