### ISSUE TITLE
using pandas for save coordinate

### ISSUE THREAD

**Issue by Wooks-git** [ultralytics/yolov5#5745]
### Question

i want to make csv file. trained my custom dataset.
format is
img_file_name    class_id     confidence     xmin     ymin     xmax     ymin

how to get like this?

**Comment by glenn-jocher** [comment]
@Wooks-git see YOLOv5 **PyTorch Hub** tutorial for details:

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Image
img = 'https://ultralytics.com/images/zidane.jpg'

# Inference
results = model(img)

results.pandas().xyxy[0]
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 1  433.50  433.50   517.5  714.5    0.687988     27     tie
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie

```

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by jmiller-dr** [comment]
which write methods are associated with .pandas() and .crop()?

**Comment by glenn-jocher** [comment]
Results as pandas dataframes can be saved/exported to virtually any format. See https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html

**Comment by jmiller-dr** [comment]
Right, thank you. For .crop() I’m looking to save as images. For pandas it looked like the overall object isn’t a DataFrame so I was looking for code examples of how to save all the data but I guess it’s just the “.xyxy[0]” dataframe part of it that people save?

**Comment by glenn-jocher** [comment]
results.pandas().xyxy is a dataframe of results in xyxy format
