### ISSUE TITLE
Grid divide in Image

### ISSUE THREAD

**Issue by keyur13-03** [ultralytics/yolov5#5746]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I was wondering what if we divide our image in 3x3 instead of 7x7. or what if we change that to 19 X 19. What will be the impact on results.? Moreover, what if we change number of bounding box per cell to 5 instead of two.?

**Comment by glenn-jocher** [comment]
@keyur13-03 I don't understand your question. YOLOv5 has multiple output heads (P3, P4, P5, P6) at different strides of 8, 16, 32, 64.

**Comment by keyur13-03** [comment]
As per the paper. YOLO divides input image into S X S grid cells. What if we divide out image into  19 X 19 grid cells? or what happens if I divide image into 3x3 grid cell?

**Comment by glenn-jocher** [comment]
@keyur13-03 I just don't understand your question. The output shape is only a function of the input shape and the stride, nothing else.

**Comment by supriamir** [comment]
.
