### ISSUE TITLE
About class weights

### ISSUE THREAD

**Issue by yocchi0425** [ultralytics/yolov5#5748]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to change the weight of the class when training（custom dataset）.
Please tell me how to do  change it.

**Comment by Zengyf-CVer** [comment]
@yocchi0425 
See:
https://github.com/ultralytics/yolov5/blob/7a39803476f8ae55fb25ed93a400a3bba998d5e7/models/yolov5n.yaml#L4

**Comment by yocchi0425** [comment]
@Zengyf-CVer 
thank you.  The number of images varies from class to class (Some are many and some are few). and I would like to know how to change the ratio used for training for each class.
