### ISSUE TITLE
Detection Error in TFLite

### ISSUE THREAD

**Issue by aseprohman** [ultralytics/yolov5#5755]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

does anybody have tried to detect with tflite model ? I have any error in picture bellow, when detect with tflite model

![Screenshot from 2021-11-23 21-55-35](https://user-images.githubusercontent.com/18188641/143048096-e71744f0-42b4-4b23-9690-e4914a1a1a55.png)

**Comment by glenn-jocher** [comment]
@aseprohman TFLite workflow is:

```bash
python export.py --weights yolov5s.pt
python detect.py --weights yolov5s-fp16.tflite
```
