### ISSUE TITLE
weight initialization 

### ISSUE THREAD

**Issue by MuhammadKhalid3975** [ultralytics/yolov5#5759]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to train yolov5x model on medical image data; the annotated images are pretty rare but I have 100K unannotated images that I want to use at least in an unsupervised settings, so I want to train the yolo model backbone as the encoder part of an auto-encoder.
**the question**  
Is it right to use the section above the red line as the encoder in an autoencoder?
 
![image](https://user-images.githubusercontent.com/42286079/143088249-d9911e3b-fba8-41ae-bb7b-f69c51baf081.png)

thank you in advance

**Comment by glenn-jocher** [comment]
@MuhammadKhalid3975 seems about right. This is where the downsampling stops and the upsampling starts.

**Comment by MuhammadKhalid3975** [comment]
Thank you, what would you recommend after training the backbone on my custom 100K unannotated  image?
I would just replace the original backbone weights with the new weights and then fine-tune on the annotated images!!  
@glenn-jocher

**Comment by MuhammadKhalid3975** [comment]
Thank you

**Comment by aldisf** [comment]
@MuhammadKhalid3975 

Hi Khalid, I'm trying to do a similar thing (using Yolo as image encoder), but somehow during the `.forward()`, I kept getting dimensional error. Can you share on how you take the subset of layers from YOLO (since there are several levels to `model` before you iterate through the `.children()`), thanks!

**Comment by MuhammadKhalid3975** [comment]
Hi Aldi,  Sure
 
`
from models.experimental import attempt_load
`
`model = attempt_load("YOUR .pt file or yolo original .pt files") # original `
`back_bone_layers= list(model.children())[0][:10]`
`encoder = torch.nn.Sequential(*back_bone_layers)`

hope you send me a feedback about results!

**Comment by aldisf** [comment]
@MuhammadKhalid3975 do we need to follow a specific format for the input? my dataset is curretnly in the form of B X C X H X W (eg. 16x3x224x224) and it throws an error at the forward (specifically during `torch.cat`): 


```
TypeError: cat() received an invalid combination of arguments - got (Tensor, int), but expected one of:
 * (tuple of Tensors tensors, name dim, *, Tensor out)
 * (tuple of Tensors tensors, int dim, *, Tensor out)
```

Curious of what is the data format that you are using, many thanks!
