### ISSUE TITLE
Bug when Installing requirement.txt and apex on CoLab

### ISSUE THREAD

**Issue by TaoXieSZ** [ultralytics/yolov5#576]
## 🐛 Bug
When I install the requirement.txt follow by apex.
The apex is failed to be installed and the cuda cannot be used.
But when I comment the `torch>=1.5.1` and `torchvision>=0.6`, it works again.

## To Reproduce (REQUIRED)
```python
!pip install -U -r requirements.txt
!git clone https://github.com/NVIDIA/apex && cd apex && pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" . --user && cd .. && rm -rf apex
```

**Comment by ZeKunZhang1998** [comment]
> ## 🐛 Bug
> A clear and concise description of what the bug is.
> When I install the requirement.txt follow by apex.
> The apex is failed to be installed and the cuda cannot be used.
> But when I comment the `torch>=1.5.1` and `torchvision>=0.6`, it works again.
> 
> ## To Reproduce (REQUIRED)
> ```python
> !pip install -U -r requirements.txt
> !git clone https://github.com/NVIDIA/apex && cd apex && pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" . --user && cd .. && rm -rf apex
> ```

I met this in gaggle.

**Comment by glenn-jocher** [comment]
@ChristopherSTAN @ZeKunZhang1998 apex is no longer used. Do not install it. 

Make sure you are meeting the requirements.txt dependencies, which include torch>=1.6.
