### ISSUE TITLE
TFLite Conversion class name loss?

### ISSUE THREAD

**Issue by DSmith-51** [ultralytics/yolov5#5761]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I trained on a custom data set using a Colab notebook. I ran detection with my trained weights and had no issue.

I then exported into tflite using "**python export.py --weights \yolov5s.pt --include tflite** and got my converted weights with no issue. However, when I ran detection with my **yolov5s-fp16.tflite** weights, I lost all class names for my weights. Every class detected with the out of the box Yolo model plus my custom class are now displayed with class names such as "class0" "class1." Is there a way to fix this?

Thanks

**Comment by DSmith-51** [comment]
![oid1](https://user-images.githubusercontent.com/55457924/143092183-81239ee5-5265-4c06-a8d1-9bc7b613bc5a.png)
 best.pt detect
![tfl_oid1](https://user-images.githubusercontent.com/55457924/143092220-ba8cf9ad-bd55-4731-867e-5ede589a4b5f.png)
yolov5s-fp16.tflite

**Comment by DSmith-51** [comment]
![image](https://user-images.githubusercontent.com/55457924/143092498-745819cd-d9e8-4b87-9b3e-5873fc0dda02.png)

**Comment by glenn-jocher** [comment]
@DSmith-51 some export formats like tflite do not support metadata attachment (like class names). You can manually define the detect.py class `names` array here:
https://github.com/ultralytics/yolov5/blob/7a39803476f8ae55fb25ed93a400a3bba998d5e7/detect.py#L80

**Comment by DSmith-51** [comment]
@glenn-jocher Apologize for the ignorant question but how would I modify the 12th class specifically? If there are 80 names do you just make a giant array? Thx

**Comment by glenn-jocher** [comment]
@DSmith-51 `names[11] = 'new_name'`

**Comment by erissutykmasyuri** [comment]
Hi I have same problem, but I change some class name in coco128.yaml and it's works

**Comment by glenn-jocher** [comment]
@erissutykmasyuri hello, 

Glad to hear that you are able to solve your problem. Modifying the class names as specified in the configuration file is one of the ways to display the correct class names while running `detect.py`. Although there are certain export formats that do not support metadata attachment such as class names. 

Feel free to reach out if you have any more questions or concerns.

Thank you for using YOLOv5!

**Comment by gagecates** [comment]
I only have one class name. Editing detect.py as such worked for me. Changing 'Person(s)' > 'Cattle(s)'
![Screenshot 2024-04-18 at 1 42 51 PM](https://github.com/ultralytics/yolov5/assets/64338434/2b30178f-73cb-4a01-8024-1d7de80e6ae8)

**Comment by glenn-jocher** [comment]
@gagecates, great to hear that modifying the class name directly in `detect.py` worked out for your specific use case! Just changing `'Person(s)'` to `'Cattle(s)'` is a neat trick for single-class models. If you have further questions or hit any roadblocks, feel free to drop a message here. Happy detecting! 🐄
