### ISSUE TITLE
在训练结束后，报‘NoneType’ has no attribute 'python_exit_status',该如何解决呢？

### ISSUE THREAD

**Issue by linklist2** [ultralytics/yolov5#5762]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

![image](https://user-images.githubusercontent.com/46252413/143154109-b8510d17-b63c-4244-958e-298f94266924.png)
您好，在训练结束后，报‘NoneType’ has no attribute 'python_exit_status',该如何解决呢？
当程序都执行完最后要退出的时候，最后输出这个Error，我该如何处理让这个不再输出呢？

**Comment by linklist2** [comment]
另外，除了将epoch设置为1以便debug train.py外，其他的都是默认的参数配置。使用的数据集是coco128.显卡为3090

**Comment by linklist2** [comment]
Using the default configuration to train the coco128 data set, the following error occurs after all codes are executed and the program is about to exit
![image](https://user-images.githubusercontent.com/46252413/143154138-0145e2b2-72e0-4cea-a442-1051b9fbe3a0.png)
 how can I solve this problem？I used a 3090

**Comment by chucksylar** [comment]
我也遇到了这个问题, 虽然没啥影响, 但是看着难受, 你解决了吗

**Comment by linklist2** [comment]
> 我也遇到了这个问题, 虽然没啥影响, 但是看着难受, 你解决了吗

并没有 @chucksylar ，发现v5.0版本跑的话貌似没有这个错误

**Comment by 1061700625** [comment]
workers改成0应该就好了

**Comment by linklist2** [comment]
> workers改成0应该就好了

好的，等我实验跑完试试 @1061700625

**Comment by leisongju** [comment]
这么多国人啊，支持，大家加vx交流啊，加我vx ：TD-8484，如果人多的话我拉个群
