### ISSUE TITLE
Single Class, Small object Detection Network Reshape

### ISSUE THREAD

**Issue by fwzdev1** [ultralytics/yolov5#5763]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

HI,

Here is the general setting. I'm trying to detect a single class on yolov5n with a solid time limitation, which means that I need to make it superfast. Since the object is just triangles with no more features inside it, yolov5 even worked satisfying with small width and depth at a ratio of 0.01.

**Q1:**
I was thinking about deleting the term controlling the cls loss and classification in Head and Loss Fuction, But I don't know whether it is worth doing. Cz it's a huge amount of works.

**Q2:**
Since the data is full of small objects, and not a lot of huge triangles exist in the dataset. I'm trying to cut the branch for big objects, and I wonder whether it can speed up inference?  If it does, how much would you expect? 

**Q3:**
Besides, are there any other measures you suggest for speeding up (mainly for CPU)? What I've done yet just focused on normal hyp changes, like img size, network ratio.

Thank you!

**Comment by glenn-jocher** [comment]
@fwzdev1 export to ONNX for ONNX Runtime on CPU.
