### ISSUE TITLE
 Generate tensorrt engine from the exported onnx model, and the inference results got additional error detection boxes.

### ISSUE THREAD

**Issue by reecezhu** [ultralytics/yolov5#5765]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I'm trying to deploy the model with c++ and tensorrt. I got the onnx model from the yolov5s.pt by export.py provided here, and further got the trt engine. Then I processed the image with the letterbox refer to the python version in detect.py, fed it into the engine, and got four outputs, of which dimensions are:  1x3x80x80x85, 1x3x40x40x85, 1x3x20x20x85, 1x25200x85; I directly decoded the last output, filtered with the threshold and applied nms, and finally got the results below. The image with the red boxes is the result of my c++ version, and the other is the python's that provided here. Note that I got some additional error boxes with high scores, I have tried to find out the cause: 
1.There are some subtle differences after the preprocessing of the two pictures due to the different versions of OpenCV JPEG parser, but I guess it not to be the cause;
2.In postprocessing, I refered to https://github.com/enazoe/yolo-tensorrt/blob/master/modules/trt_utils.cpp to apply the nms, but I don't think it the cause of problem due to the high scores of wrong boxes, the scores were calculated when decoding the last output.
Would you please analyse the problem and  the get some suggestions for me, thanks a lot.
![dog_det](https://user-images.githubusercontent.com/49329202/143178427-13e85ff0-6c1b-47a6-a6f9-7e138672ce83.jpg)
![dog](https://user-images.githubusercontent.com/49329202/143178457-cee37e97-6c58-49f8-96f7-44ee4a9889fc.jpg)

**Comment by glenn-jocher** [comment]
@GluttonYu TensorRT export and inference operate correctly:

```python
python export.py --weights yolov5s.pt --include engine --imgsz 640 640 --device 0
python detect.py --weights yolov5s.engine --imgsz 640 640 --device 0
```

<img width="2296" alt="Screenshot 2021-11-24 at 16 16 41" src="https://user-images.githubusercontent.com/26833433/143265041-0f84c63e-0f2b-4f50-83a6-09ce5f6c0d4c.png">

**Comment by reecezhu** [comment]
@glenn-jocher Thanks for your reply, actually I tried your suggestions and got the same problem as my c++ version, but it guided me to the real cause: my tensorrt version was 7.0 and should be 8.0+ . I guess some postprocess steps defined in the network were not well supported by tensorrt7.0.

**Comment by gustavojoseleite** [comment]
Same problem here! Are you using docker? Do you have some help to update tensorrt?

**Comment by reecezhu** [comment]
@gustavojoseleite I'm not using docker, I just downloaded tensorrt8 deb file from official and applied in my system.

**Comment by gustavojoseleite** [comment]
> @gustavojoseleite I'm not using docker, I just downloaded tensorrt8 deb file from official and applied in my system.

Works on AGX Xavier with jetpack 4.6 and tensorrt8. Thanks for answer @GluttonYu !

**Comment by we0091234** [comment]
Same ploblem  tesnorrt 7.2.3.4 got some wrong boxes,but tensorrt 8,2.0.6  is correct!  But I want to konw Why？
