### ISSUE TITLE
Are you normalizing the input? Where can I find it?

### ISSUE THREAD

**Issue by sarmientoj24** [ultralytics/yolov5#5766]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I cannot find how you normalize the input for training. Can you point me to it?

**Comment by glenn-jocher** [comment]
@sarmientoj24 input is not normalized. It is rescaled from INT8 0-255 to float 0-1.
