### ISSUE TITLE
How do i get weights related to specific code commit ?

### ISSUE THREAD

**Issue by mitesh741** [ultralytics/yolov5#5767]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

I am using has commit [https://github.com/ultralytics/yolov5/tree/9ccfa85249a2409d311bdf2e817f99377e135091](url)
in my code. I want to download weights related to this commit.

Please help.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@mitesh741 weights for each release are available at https://github.com/ultralytics/yolov5/releases
