### ISSUE TITLE
About performance reproduction

### ISSUE THREAD

**Issue by hhaAndroid** [ultralytics/yolov5#5769]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I plan to reproduce yolov5-s accuracy, but I found some doubts.

According to the readme training startup script should be `python train.py --data coco.yaml --cfg yolov5s.yaml --weights ''--hyp data/hyps/hyp.scratch-high.yaml --batch-size 64`.

But according to https://wandb.ai/glenn-jocher/YOLOv5_v6.0_official/runs/j3bufsuf/files/config.yaml, it seems that the parameters are wrong. example `lrf: 0.1`.

I want to know what is the complete boot script of the YOLOV5 v60 version?

### Additional

None

**Comment by glenn-jocher** [comment]
@hhaAndroid yes use https://wandb.ai/glenn-jocher/YOLOv5_v6.0_official/runs/j3bufsuf/files/config.yaml

**Comment by hhaAndroid** [comment]
@glenn-jocher OK, Thank you.
