### ISSUE TITLE
Fine tune on COCO subclasses

### ISSUE THREAD

**Issue by dimimal** [ultralytics/yolov5#5771]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I would like to add more data to only some specific classes which are a subset to COCO classes in order to fine tune the model. Would that be possible?

**Comment by glenn-jocher** [comment]
@dimimal of course. Just make sure to label all instances of all COCO classes in your new images.

**Comment by dimimal** [comment]
@glenn-jocher Is any tutorial example available where I could build upon?
