### ISSUE TITLE
Difference between hyp_evolve.yaml and hyp.yaml after evolve run

### ISSUE THREAD

**Issue by alexdess** [ultralytics/yolov5#5774]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,

I don't understand the difference between the generated files. By the way, at the end, they have exactly the same values, so I can use one or the other to create my optimal model, right?

During the evolution, what is the difference between the two files? I have the impression that they both keep the best values.

Thank you for your clarification.

alexdess

**Comment by glenn-jocher** [comment]
hyp_evolve.yaml contains evolution results, as the tutorial explains.

**Comment by alexdess** [comment]
For me it is not clear, what are the differences between the 2 files, can you answer this question?

**Comment by alexdess** [comment]
Can anyone explain the difference or not?

**Comment by glenn-jocher** [comment]
@alexdess good news 😃! Your original issue may now be fixed ✅ in PR #5775 . To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
