### ISSUE TITLE
Weights for each class

### ISSUE THREAD

**Issue by yocchi0425** [ultralytics/yolov5#5776]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

The number of images in my custom dataset will vary from class to class (some are more and some are less).  How do I change the training ratio (weight) for each class?

**Comment by glenn-jocher** [comment]
@yocchi0425 you can specify class weights in loss criteria here:
https://github.com/ultralytics/yolov5/blob/c55e674ac3ffa641cbbd465760701c64d3a3dcb9/utils/loss.py#L98-L100
