### ISSUE TITLE
YoloV5 compilation on TVM

### ISSUE THREAD

**Issue by tutu96177** [ultralytics/yolov5#5779]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Does the author implement YoloV5 compilation on TVM compilation framework?

**Comment by zhiqwang** [comment]
Hi @tutu96177 

I've done some experiments on exporting the YOLOv5 to TVM/Relay before <https://zhiqwang.com/yolov5-rt-stack/notebooks/export-relay-inference-tvm.html>, maybe it can used as a reference.
