### ISSUE TITLE
Speed Estimation while tracking objects using zero shot object tracking

### ISSUE THREAD

**Issue by animeshkalita82** [ultralytics/yolov5#5782]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Speed calculation of moving objects while tracking using zero shot object tracking algorithm.

### Use case

Currently working on an usecase to detect the license plate of  a car which is moving at a speed of 80 km/h. For this use case, we need to estimate the speed of each detected car and if its speed is 80km/hr then its license plate should be read and save in a csv file. Here we are able to detect the license plate and read the number but not able to estimate the speed of the cars.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@animeshkalita82 we've done some Structure From Motion (SFM) speed projects before such as https://github.com/ultralytics/velocity

**Comment by animeshkalita82** [comment]
> @animeshkalita82 we've done some Structure From Motion (SFM) speed projects before such as https://github.com/ultralytics/velocity

@glenn-jocher Thank you very much for your reply. I have checkout the project and run on my video which is a mp4 file. I have added extension == '.mp4' in getCameraParams method of images.py file. 
   isvideo = (extension == '.MOV') | (extension == '.mov') | (extension == '.m4v') | (extension == '.mp4')

But there needs to be a file with .mat extension in the matlab folder for the same video file. Can you please tell me how to create this .mat file. currently i am getting the below error.

File "vidExample.py", line 33, in vidExamplefcn
    mat = scipy.io.loadmat(pathb + cam['filename'] + '.mat')
  File "/usr/local/lib/python3.7/dist-packages/scipy/io/matlab/mio.py", line 218, in loadmat
    matfile_dict = MR.get_variables(variable_names)
  File "/usr/local/lib/python3.7/dist-packages/scipy/io/matlab/mio4.py", line 400, in get_variables
    mdict[name] = self.read_var_array(hdr)
  File "/usr/local/lib/python3.7/dist-packages/scipy/io/matlab/mio4.py", line 375, in read_var_array
    return self._matrix_reader.array_from_header(header, process)
  File "/usr/local/lib/python3.7/dist-packages/scipy/io/matlab/mio4.py", line 146, in array_from_header
    raise TypeError('No reader for class code %s' % mclass)
TypeError: No reader for class code 8
