### ISSUE TITLE
How to update trained model with more data?

### ISSUE THREAD

**Issue by diazGT94** [ultralytics/yolov5#5785]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is it possible to update a trained model by simply creating a new dataset with the new data and train the model with the previously trained weights? Or do I need to add the new data to the old dataset and train the model with the previously trained weights?

**Comment by glenn-jocher** [comment]
@diazGT94 a model must be trained on all classes you want it to detect in deployment, so your second option.
