### ISSUE TITLE
Is it possible to annotate objects from image like this ?

### ISSUE THREAD

**Issue by sudheer-palaparambil** [ultralytics/yolov5#5787]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,

      Is it possible to annotate the object from the attached images? I would like to annotate it like the SKU101 dataset and
train. My intention is to develop an object detector application to keep track of store shelf inventory.

      Thank and regards.

Sudheer P

![20211116_104858](https://user-images.githubusercontent.com/9995485/143442241-ecbac8b9-e5cf-4d10-8c62-495472f3d2fe.jpg)
![20211116_105035](https://user-images.githubusercontent.com/9995485/143442252-75bffe39-1a0b-4ecb-ba61-961b4dd09120.jpg)
![20211116_105112](https://user-images.githubusercontent.com/9995485/143442256-e2f5d775-37e2-4e45-a2df-0558adbe0b49.jpg)
![20211116_105637](https://user-images.githubusercontent.com/9995485/143442258-053c408e-3896-4541-85bb-b422e9f6ac95.jpg)
![20211116_105645](https://user-images.githubusercontent.com/9995485/143442261-d82efc61-1f87-45c0-8bb9-e59156080c70.jpg)
![20211116_105942](https://user-images.githubusercontent.com/9995485/143442267-8fd1b7bb-89e7-4350-91f4-232f61a22e3b.jpg)

**Comment by glenn-jocher** [comment]
@sudheer-palaparambil sure, try [Roboflow](https://roboflow.com/?ref=ultralytics)

**Comment by sudheer-palaparambil** [comment]
@glenn-jocher thanks for the reply. I have few more questions. Do we need to draw bounding boxes for each stacked and hanging objects? Is it possible?

**Comment by Guttappa1238** [comment]
> @glenn-jocher thanks for the reply. I have few more questions. Do we need to draw bounding boxes for each stacked and hanging objects? Is it possible?

Yes, possible but time consuming.

**Comment by sudheer-palaparambil** [comment]
@Guttappa1238 thank you.
