### ISSUE TITLE
Does not learn using GPU

### ISSUE THREAD

**Issue by maurokenny** [ultralytics/yolov5#5788]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

Yolo does not learn with gpu, however it learns with cpu.

I’ve installed torch using conda on Windows 10 (conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch)

Basically, it never learns. Box, obj, cls are always nan, and P and R are always 0.

On the other hand, when using the same code but running on cpu:

```Image sizes 512 train, 512 val
Using 1 dataloader workers
Logging results to runs\train\exp25
Starting training for 20 epochs...

     Epoch   gpu_mem       box       obj       cls    labels  img_size
      0/19        0G    0.1147   0.02892   0.05367         5       512:   2%|▋                                 | 3/152 [00:05<03:40,  1.48s/it]

```

![gpu train 0](https://user-images.githubusercontent.com/2873617/143451994-96b73767-68cc-445b-9038-19526c097820.png)
![gpu train 1](https://user-images.githubusercontent.com/2873617/143451990-8baaaabd-1984-4a4d-8e8f-8436b4afd470.png)
![gpu train 2](https://user-images.githubusercontent.com/2873617/143451993-9a78c255-f493-4da8-8b4c-5e4a4bd0eb27.png)

### Environment

Python 3.8.12 (default, Oct 12 2021, 03:01:40) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
os: windows 10
numpy.version.version
'1.21.2'
torch.version
1.10.0

### Minimal Reproducible Example

```python train.py --img 512 --workers 1 --batch 2 --epochs 20 --data yolo_train.yaml --weights yolov5s.pt --cache``` (or --img 256)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@maurokenny sometimes CUDA 11 creates issues with conda and/or windows. You should try downgrading to CUDA 10, this has worked for other users in a similar situation.

**Comment by maurokenny** [comment]
@glenn-jocher this worked for me for now. Thanks

**Comment by 1311523821** [comment]
> @glenn-jocher this worked for me for now. Thanks

I have the same problem as you. But it is still nan with CUDA 10.2( I didn't uninstall CUDA 11.1). How did you solve this problem？

**Comment by maurokenny** [comment]
It worked better for me with the LTS version: 
`conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch-lts`

**Comment by 1311523821** [comment]
> 

thanks

**Comment by Anand-kuch** [comment]
Firstly check `torch.cuda.is_available()`. If it returns false then follow this. _https://stackoverflow.com/questions/57238344/i-have-a-gpu-and-cuda-installed-in-windows-10-but-pytorchs-torch-cuda-is-availa_

**Comment by AnandSrikumar** [comment]
Did you try this? _https://stackoverflow.com/questions/57238344/i-have-a-gpu-and-cuda-installed-in-windows-10-but-pytorchs-torch-cuda-is-availa_

**Comment by owentamin1996** [comment]
> It worked better for me with the LTS version:
> `conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch-lts`

Hi, I'm having problem with CUDA 11.3 as well. It does not show any detection. Can I need help with the installation process for CUDA 10.2? I have been facing this problem for few weeks.

**Comment by glenn-jocher** [comment]
@plastic-waste-database hi there! I'm glad to hear that using CUDA 10.2 resolved the issue for you. To switch to CUDA 10.2, you can use the following command:

```bash
conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch
```

You can find more information on the installation process in the documentation at https://docs.ultralytics.com/yolov5/#requirements. Let me know if you need further assistance.
