### ISSUE TITLE
How to generate bbox, after the coremltools.predict(image) step of the coreml model

### ISSUE THREAD

**Issue by fnuabhimanyu** [ultralytics/yolov5#579]
## ❔Question
Can someone guide me on how to generate bbox, after the coremltools.predict(image) step of the coreml model? What post processing needs to be done on the predicted values?

## Additional context
Do I have to post process the predicted value using these lines:
```
y = x[i].sigmoid()
y[..., 0:2] = (y[..., 0:2] * 2. - 0.5 + self.grid[i].to(x[i].device)) * self.stride[i]  # xy
y[..., 2:4] = (y[..., 2:4] * 2) ** 2 * self.anchor_grid[i]  # wh
```
Or are they included in the CoreML model.

**Comment by hearables-pkinsella** [comment]
I'm having this issue as well. I've converted the model to CoreML using:

`model.model[-1].export = True`

This gives me three multiarray outputs that are 1x3x13x13x6, 1x3x52x52x6 and 1x3x26x26x6. Ideally I would want the output to be (x1, y1, x2, y2, conf, cls).

If I set, `model.model[-1].export = False`, then the output is the correct shape but I run into an error when converting to CoreML:

`CoreML export failure: node 2061 (expand) got 3 input(s), expected 2`

**Comment by fnuabhimanyu** [comment]
Ya, I didn't set the flag to false, and had to do post processing on the prediction of the coreml model. And it worked

**Comment by hearables-pkinsella** [comment]
@Abhimanyu8713 , would you be able to provide some code snippets for how you have done the post-processing?

**Comment by dlawrences** [comment]
Hi @hearables-pkinsella , all,

There is some guidance [here](https://github.com/ultralytics/yolov5/issues/343#issuecomment-658021043). Hope this will help you!

**Comment by fnuabhimanyu** [comment]
Hi @hearables-pkinsella, you can refer this [issue](https://github.com/ultralytics/yolov5/issues/571). Hope this helps you.

**Comment by ShreshthSaxena** [comment]
@Abhimanyu8713 were you able to get correct bounding boxes after post-processing? Did you test it on an iOS device ?

**Comment by waheed0332** [comment]
Any update regarding coreml conversion. I'm getting an error when I set model.model[-1].export = True
