### ISSUE TITLE
Measuring TP and FP

### ISSUE THREAD

**Issue by Moamoza** [ultralytics/yolov5#5790]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I am wondering how does Yolov5 label a detected Object as TP or FP. I read about IoU but in terms of matching the labels, for instance, it finds there are 2 objects which have IoU more than the threshold, which lines of the code check if they have the same label or not. I  got a little bit confused about it.

**Comment by glenn-jocher** [comment]
@Moamoza TPs and FPs is computed here:
https://github.com/ultralytics/yolov5/blob/4c7b2bdc30657354afcbc255385a163662e66c8b/utils/metrics.py#L82-L87
