### ISSUE TITLE
Robust Video Loading

### ISSUE THREAD

**Issue by SajjadPSavoji** [ultralytics/yolov5#5791]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

It is common that cv2 might crash(return false) while loading a video file as they might contain corrupted frames.
I had a similar issue while running the inference module(detect.py). The way I was able to make it work was by adding a couple of lines in LoadImages(datesets.py). In LoadImages , frames of a video are captured sequentially till the cv2.VideoCapture(self.cap) returns False.

I suggest changing this stopping criterion based on the number of frames read from the video file. This way, in case the video file contains a number of corrupted frames, the module will be able to ignore them accordingly.

To do so, I suggest adding these lines in datesets.py at line 203.
`

while ((not ret_val)and(self.frame < self.frames)):

                self.frame += 1

                ret_val, img0 = self.cap.read()

`
            

 

### Use case

It will make detect.py more robust when dealing with corrupted video files

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@SajjadPSavoji yes this a good idea!

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
