### ISSUE TITLE
PyTorch - build from source is overwritten

### ISSUE THREAD

**Issue by DP1701** [ultralytics/yolov5#5793]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello all, 

I have compiled PyTorch from source. I followed these instructions: 

[https://github.com/pytorch/pytorch/tree/release/1.10#from-source](https://github.com/pytorch/pytorch/tree/release/1.10#from-source)

With Anaconda and pip I installed all the necessary packages listed in the [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt). 

When I start the training within an Anaconda environment, the PyTorch installation is simply overwritten with the prebuilds. I currently only have one powerful CPU available and I wanted to use the CPU optimised PyTorch version. Is there a way to link the PyTorch version compiled from source with YOLOv5?

**Comment by glenn-jocher** [comment]
@DP1701 I would avoid conda and use the pip install instructions at https://pytorch.org/get-started/locally/

**Comment by DP1701** [comment]
@glenn-jocher Thank you for the quick reply. 

This installs the prebuilds and I also used them at the beginning. Unfortunately, the performance with the prebuilds is not very good. So I wanted to build PyTorch from the source and link this with YOLOv5. 

I have added two pictures. One shows all the installed packages and the second shows the overwriting of PyTorch after starting the training.
![1](https://user-images.githubusercontent.com/68444979/143483989-64552eef-7d63-44ef-b568-db1adcef91c5.png)
![2](https://user-images.githubusercontent.com/68444979/143484008-6cfdec00-cbb6-4bb2-976c-7a7f1545046b.png)

**Comment by DP1701** [comment]
Does anyone have an idea how to prevent the overwriting of the Torch installation?

**Comment by Zengyf-CVer** [comment]
@DP1701 
According to my method, you can try:
1. First uninstall your torch and torchvision.
2. Follow https://pytorch.org/get-started/locally/ to install your torch.

**Comment by DP1701** [comment]
Ok, I have reinstalled everything again and used these instructions:

[https://github.com/ultralytics/yolov5#quick-start-examples](https://github.com/ultralytics/yolov5#quick-start-examples)

All packages are up to date.

My problem is that I only have one CPU currently for training. The CPU contains 16 cores. During the training process, the CPU is only used 10 - 15 percent. Is this normal? Is there a way to speed up the training?

I start the training as follows:

```
python3 train.py --img 640 --batch 16 --epochs 50 --data data.yaml --weights yolov5s.pt
```

**Comment by Zengyf-CVer** [comment]
@DP1701 
- Because you are using a CPU, depending on your RAM, you can increase the Batch Size, such as `--batch 32` or `--batch 64` or larger.
- If you just want to improve the training speed, and don't pay much attention to mAP, you can appropriately reduce the input size, such as `--img-size 320`
