### ISSUE TITLE
multi live streams projected into top view using yolo5?

### ISSUE THREAD

**Issue by sanajabbarweb** [ultralytics/yolov5#5796]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi. An amazing tool you have developed, as yolo5 has built-in feature to take multi live streams using .txt file with IPs and perform object detection. Can we somehow project those live streams on to a common top view and combine those multiple live streams into a single top view stream?

I have a homography matrix for each live stream and i have projected each into top-view separately. Can i combine those top-views into a single top-view using yolo5?

**Comment by glenn-jocher** [comment]
@sana1988 I think you are confusing scope. YOLOv5 is an AI object detector. Post processing the results to your custom requirements is up to you and not within the scope of this repo nor our support.

**Comment by sanajabbarweb** [comment]
@glenn-jocher Thanks for very quick response. I need to monitor SOPs of covid-19 in my task. i used yolo5 for mask and no mask detection. I have few questions:
1. i took streams from multiple cameras. Using yolo i am not able to save stream from each camera. Can i save stream from each camera separately OR after stitching all videos? 
2. if i would be able to save stream from each camera then i can project those streams into a common top-view to monitor 6 feet distance. Can i do this all using yolo???

**Comment by glenn-jocher** [comment]
@sana1988 oh, mask dataset could be pretty useful! Please consider making a mask.yaml dataset to help future users get started more easily. I can help if you get a PR started. You can see existing datasets like COCO, VOC, Argoverse etc here:
https://github.com/ultralytics/yolov5/tree/master/data

About your question, in detect.py the `save_img` boolean controls saving annotated image results (images and videos), but it is disabled for multi-streams in this line:
https://github.com/ultralytics/yolov5/blob/53349dac8e9fb447bb43319811699bb72d1c2470/detect.py#L66

You'd have to customize detect.py in a new PR to enable multi-stream saving, probably with one video per stream.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by sanajabbarweb** [comment]
@glenn-jocher  we have made necessary changes in detect.py to save multiple streams separately. I have also submitted a PR. You can verify and let me know.

**Comment by glenn-jocher** [comment]
@sana1988 can you link to the PR, I don't see it. 

Could you submit a PR for the mask dataset if it's publically available?

**Comment by sanajabbarweb** [comment]
@glenn-jocher here is link to PR https://github.com/ultralytics/yolov5/pull/5931

**Comment by glenn-jocher** [comment]
@sana1988 great, thanks I'll check it out.
