### ISSUE TITLE
How shall I train YoloV5 model on VisDrone dataset?

### ISSUE THREAD

**Issue by SahilChachra** [ultralytics/yolov5#5798]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello!
I was about to train YoloV5 model on VisDrone dataset. But I saw that the size of the image is 1920x1080. So how shall I train on this large image size?

Option 1) pass --img 1920 --rect

Option 2) Shall I split each image (from train set) into say 4 parts each being 480x270. if YES, then HOW? (Keeping in mind the model will detect images passed in original resolution i.e 1920x1080)

**Comment by glenn-jocher** [comment]
@SahilChachra you can train at any `--imgsz` you want. That's why it's an argument.

**Comment by SahilChachra** [comment]
Thanks for replying @glenn-jocher . I will run experiments with original size itself.

**Comment by glenn-jocher** [comment]
@SahilChachra the only recommendation there is to train at deploy at similar image sizes for best results. What that image size is though is up to you and your use case, inference capabilities, priorities etc.

**Comment by RoyCopter** [comment]
> Thanks for replying @glenn-jocher . I will run experiments with original size itself.

Did you manage to train the yolov5 on the visdrone dataset? how did you convert the annotations? 

and can you share your pre-trained weights?

thanks!

**Comment by glenn-jocher** [comment]
@RoyCopter usage example is already shown in the VisDrone yaml:
https://github.com/ultralytics/yolov5/blob/bcc92e2169a233c3e974db40ddc9b496d9c29ec8/data/VisDrone.yaml#L1-L8
