### ISSUE TITLE
mosaic+Photometric Distortions

### ISSUE THREAD

**Issue by MAO-S-K** [ultralytics/yolov5#5800]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, can I ask you a question? , I want to introduce the data enhancement method in SSD-Photometric Distortions (Random Brightness) (Random Contrast, Hue, Saturation) (RandomLightingNoise) to mosaic. Can this idea be realized?

![image](https://user-images.githubusercontent.com/83931631/143544200-959043ac-d361-4102-86c5-68fd2aed3f43.png)
![image](https://user-images.githubusercontent.com/83931631/143544374-cdb408f0-4b96-49d8-b5ca-76c560a2bdc6.png)
![image](https://user-images.githubusercontent.com/83931631/143544506-5f09c167-cd4e-41ba-9242-50426f7d9100.png)

### Additional

https://nicehuster.github.io/2019/05/11/ssd-dataaug/

**Comment by glenn-jocher** [comment]
@MAO-S-K HSV augmentation settings can be modified here:
https://github.com/ultralytics/yolov5/blob/53349dac8e9fb447bb43319811699bb72d1c2470/data/hyps/hyp.scratch.yaml#L22-L24

Albumentations also supplies many additional colorspace augmentations, see https://github.com/ultralytics/yolov5/pull/3882

**Comment by MAO-S-K** [comment]
@glenn-jocher  Thank you, you are my idol
