### ISSUE TITLE
the ((gxy % 1.0 < g) & (gxy > 1)).T will find more anchor than 3 if x or y == 1.0 or 2.0 or 3.0....

### ISSUE THREAD

**Issue by qixi666666** [ultralytics/yolov5#5801]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

in build_targets 
j, k = ((gxy % 1.0 < g) & (gxy > 1)).T
l, m = ((gxi % 1.0 < g) & (gxi > 1)).T
if the number in gxy have x.0(x == 1 or 2 or 3...), the j, k, l, m will all be true , the number of true is not 2 but more than 2. 
this will be bad for the iou loss

**Comment by glenn-jocher** [comment]
@qixi666666 hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
