### ISSUE TITLE
V6.0 takes longer to train than V5.0

### ISSUE THREAD

**Issue by linklist2** [ultralytics/yolov5#5808]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

In the same data set, V5.0 only needs 25s / epoch, while V6.0 needs 1min11s / epoch.
I tried to use the V5.0 model yaml file in the V6.0 project, but the speed did not change significantly; Then I used V5.0 create_dataloader in the V6.0 project, the training speed is still not improved.
v5.0
![image](https://user-images.githubusercontent.com/46252413/143665557-a893ee3e-4fff-47fb-8dba-b771a15369f5.png)
v6.0
![image](https://user-images.githubusercontent.com/46252413/143665576-47efe505-accc-4e00-876f-8cc2654dc511.png)
Now I'm confused about what makes the difference.

**Comment by Etern213** [comment]
I have exactly the same problem, how did you solve it?

**Comment by linklist2** [comment]
> I have exactly the same problem, how did you solve it?

yes, I updated the version of PyTorch, then the problem has solved.

**Comment by Etern213** [comment]
> 

which version of pytorch, torchvision and torchaudio you use? And which CUDA version you use?

I use torch 1.9.0+cuda10.2 in yolov5-5.0, and I update pytorch to 1.10.0+cuda10.2, the problem did not solve, 
6.0 still take much longer train than 5.0

**Comment by Etern213** [comment]
> > I have exactly the same problem, how did you solve it?
> 
> yes, I updated the version of PyTorch, then the problem has solved.

Thank you very much for your reply. I tried many ways to solve this problem but nothing works. So, I want to know your environment to run yolov5. 

pytorch version, numpy version, and other packdge in requestment.txt.
Thank you.

**Comment by Etern213** [comment]
> > I have exactly the same problem, how did you solve it?
> 
> yes, I updated the version of PyTorch, then the problem has solved.

哎，我真是试了所有的办法都没解决这个问题。GitHub上面和这个有关的issue一共有两个#5466和#5808，但是我更新torch版本没解决这个问题。。。。训练速度依旧比5.0慢四倍还多。

可否加个微信，这个问题很急但是我有没什么头绪，该试的都试了。
可以问一下你的其它包的版本吗？

还有，你的torch是conda安装还是pip安装

**Comment by linklist2** [comment]
> 

![image](https://user-images.githubusercontent.com/46252413/163942269-beebaeac-62cc-4288-9f2b-396edd0375d5.png)

**Comment by linklist2** [comment]
> > > I have exactly the same problem, how did you solve it?
> > 
> > 
> > yes, I updated the version of PyTorch, then the problem has solved.
> 
> 哎，我真是试了所有的办法都没解决这个问题。GitHub上面和这个有关的issue一共有两个#5466和#5808，但是我更新torch版本没解决这个问题。。。。训练速度依旧比5.0慢四倍还多。
> 
> 可否加个微信，这个问题很急但是我有没什么头绪，该试的都试了。 可以问一下你的其它包的版本吗？
> 
> 还有，你的torch是conda安装还是pip安装

![image](https://user-images.githubusercontent.com/46252413/163942332-8087b91f-816f-419d-86be-bd7d29f42c19.png)

或许
![image](https://user-images.githubusercontent.com/46252413/163942353-43e18737-0ab5-45f8-9b7f-bd6f39476c6f.png)
机器不在我手上，我无法给你任何有关版本的问题的回答。
torch为conda安装

**Comment by Etern213** [comment]
> 机器不在我手上，我无法给你任何有关版本的问题的回答。 torch为conda安装

真的快要疯了，所有的办法都试了不行，感觉只能看照搬一下别人的虚拟环境看看出不出问题，然后再一步步筛查到底是哪里的原因了，现在是根本找不到问题的原因。
我的pytorch是1.10.1+cuda10.2，按你的解决思路来说应该是没有问题的啊。

此外，你的python是啥版本

**Comment by linklist2** [comment]
@Etern213 有点太久远了，可能是3.7

**Comment by Etern213** [comment]
> @Etern213 有点太久远了，可能是3.7

多谢回复了，我再想想办法吧，实在不行再来问您，真的人要麻了

**Comment by ujsyehao** [comment]
> 

请问老哥你解决了这个问题了吗

**Comment by Etern213** [comment]
> 请问老哥你解决了这个问题了吗

找到问题了但没有解决，看这个issue #7687

**Comment by glenn-jocher** [comment]
```markdown @Etern213 Thanks for your message. I haven't solved the issue yet, but I've identified the problem. It seems related to this issue #7687.
```
