### ISSUE TITLE
error when "torch.load()"

### ISSUE THREAD

**Issue by sveits6** [ultralytics/yolov5#581]
## ❔Question
Traceback (most recent call last):
File "D:\Envs\pyt1.4\lib\site-packages\torch\serialization.py", line 527, in load
with _open_zipfile_reader(f) as opened_zipfile:
File "D:\Envs\pyt1.4\lib\site-packages\torch\serialization.py", line 224, in init
super(_open_zipfile_reader, self).init(torch.C.PyTorchFileReader(name_or_buffer))
RuntimeError: version <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at ..\caffe2\serialize\inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at ..\caffe2\serialize\inline_container.cc:132)
(no backtrace available)
![图片](https://user-images.githubusercontent.com/23731100/89008418-3d1d0800-d33d-11ea-8178-e9d24ea70207.png)
How to solve it?This just happen on the newest weights file of your google drive.The weights file of last version is ok.

**Comment by glenn-jocher** [comment]
@sveits6 I don't recognize that command, and we don't assist in debugging custom code.

**Comment by mfruhner** [comment]
Hello, @glenn-jocher, I am having the same issue. It happens with the new v2.0, when starting a training in the ultralytics docker container. I pulled the latest container and started a training. It starts to download the pt file (yolov5m.pt) and then errors out:

```
Downloading https://drive.google.com/uc?export=download&id=1vobuEExpWQVpXExsJ2w-Mbf3HJjWkQJr as yolov5m.pt... Done (5.7s)
Traceback (most recent call last):
  File "train.py", line 469, in <module>
    train(hyp, tb_writer, opt, device)
  File "train.py", line 128, in train
    ckpt = torch.load(weights, map_location=device)  # load checkpoint
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 585, in load
    with _open_zipfile_reader(f) as opened_zipfile:
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 245, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at ../caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old.
```

Were those new weights trained with pytorch 1.6? The docker container uses 1.5.x

Greetings and Thanks,
Maik

**Comment by mfruhner** [comment]
Just checked it, by installing torch==1.6.0 and torchvision==0.7.0. 
It now loads correctly and starts to train. So the requirements.txt needs to be updated and the docker container rebuilt accordingly. Cheers.

**Comment by glenn-jocher** [comment]
@mfruhner thanks! Yes we are in the process of updating requirements.txt to 1.6, and will be pushing native mixed precision training PR as well.

**Comment by bbyuksel** [comment]
> Just checked it, by installing torch==1.6.0 and torchvision==0.7.0. It now loads correctly and starts to train. So the requirements.txt needs to be updated and the docker container rebuilt accordingly. Cheers.

This solved my same problem
