### ISSUE TITLE
detect original image shape

### ISSUE THREAD

**Issue by Wooks-git** [ultralytics/yolov5#5811]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

i have test dataset images shape(320x320 and 640x640)
i want to detect my test dataset for original image shape.
but this code just have one default value.

can i detect each image's shape?

**Comment by glenn-jocher** [comment]
@Wooks-git you can set `scaleup=False` in the letterbox function and then pass your max imgsz, i.e. `python val.py --img 640`

https://github.com/ultralytics/yolov5/blob/fcd180d33697848ea7acb96d7485c58110704d5e/utils/augmentations.py#L91
