### ISSUE TITLE
Training YOLOv5 on multispectral images is not stable.

### ISSUE THREAD

**Issue by rgw117** [ultralytics/yolov5#5812]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I am working on a multispectral object detection project using the YOLOv5 architecture. Therefore, I just added two groups of encoding layers and concatenated two encoded features from RGB and thermal modalities, and used the concatenated feature for the YOLOv5 model. However, I encountered a problem as it is shown in the figure below.
![image (33)](https://user-images.githubusercontent.com/67646870/143735405-8e02c2be-232b-4fd3-b6ce-a274b97ad713.png)
.
As it is shown, the training process is not stable and the learning curve fluctuates.

Do you have any clue why that kind of tendency appears? Any idea would be helpful for me. Thank you!

**Comment by glenn-jocher** [comment]
@rgw117 if you modified a model and the modified model is no longer stable then I would say your modifications are the cause of the instabilities.
