### ISSUE TITLE
YoloV5 for segmentation

### ISSUE THREAD

**Issue by jaideep11061982** [ultralytics/yolov5#5819]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Any pointers for how we can use Yolo for Instance segmentation..

**Comment by glenn-jocher** [comment]
@jaideep11061982 hi, thanks for asking! This is on our roadmap for 2022.

**Comment by jaideep11061982** [comment]
@glenn-jocher  we have some thing as YOlOACT. Is that  not doing the  above task. ?

We also have YOLO series defined in MM detect. Is there plan to leverage the MM detect framework  or YOLO will have its own framework for this. I can try giving inputs based on my understanding on YoloV5.
