### ISSUE TITLE
How can I change the stride of conv layer

### ISSUE THREAD

**Issue by PariaDarbani** [ultralytics/yolov5#5822]
How can I change the stride of the CONV layer in inference?

for example,  the first CONV layer has stride = 1, how I can run an inference with stride = 2 for the first layer.

**Comment by glenn-jocher** [comment]
@PariaDarbani see Conv() arguments:
https://github.com/ultralytics/yolov5/blob/5ca5dd4c87fcc62491173b393fd51cf244805313/models/common.py#L37-L47

**Comment by PariaDarbani** [comment]
> @PariaDarbani see Conv() arguments:
> 
> https://github.com/ultralytics/yolov5/blob/5ca5dd4c87fcc62491173b393fd51cf244805313/models/common.py#L37-L47

Thanks! but I think it's working for training YOLO, not inference.

**Comment by glenn-jocher** [comment]
@PariaDarbani Conv() layer is used in all workflows.

**Comment by PariaDarbani** [comment]
> @PariaDarbani Conv() layer is used in all workflows.

I changed the stride of Conv() from common.py and ran detect.py but there was no change in the results.
It seems that Conv() from common.py is not called for inference.
