### ISSUE TITLE
Exponential increase during evolution

### ISSUE THREAD

**Issue by alexdess** [ultralytics/yolov5#5823]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is it normal that with each evolution, the number of training doubles?

For example the following command:

> for i in 0 2 3; do
>   nohup python yolov5/train.py --epochs 30 --batch 4 --weights yolov5m.pt --data dataset_paragraph.yaml --cache --evolve 30 --device $i > evolve_gpu_$i.log &
> done

Will give me the following output (results.csv)
![image](https://user-images.githubusercontent.com/8177780/143888210-d4fbff65-62af-456f-95d1-ed4af056f91a.png)

During the second evolution:
![image](https://user-images.githubusercontent.com/8177780/143888346-8fd9562f-b076-438a-99e9-3e181341cd5a.png)

Thank you for your valuable helping.

alexdess

**Comment by glenn-jocher** [comment]
@alexdess your issue is incorrect. You are displaying results.csv, not evolve.csv.

**Comment by alexdess** [comment]
> @alexdess your issue is incorrect. You are displaying results.csv, not evolve.csv.

That's right, sorry for the mistake. My question/bug is still valid though. I have corrected the initial post

**Comment by glenn-jocher** [comment]
Evolve produces evolve.csv. Is there any problem with this file? You can ignore anything else.
