### ISSUE TITLE
DNN&ONNX is much slower than ONNX

### ISSUE THREAD

**Issue by fwzdev1** [ultralytics/yolov5#5827]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I tried inference an extremely light model (no bigger than 1MB) on I7-10870H, Ubuntu 18.04.

![Screenshot from 2021-11-30 14-44-37](https://user-images.githubusercontent.com/62492773/143999082-246c10ab-6f63-4571-af93-bcdd5a91a71b.png)
![Screenshot from 2021-11-30 14-45-07](https://user-images.githubusercontent.com/62492773/143999092-264b1b5c-92c2-4435-8fa5-bc528f2a2e3e.png)

I was expecting to get a faster inference with DNN only to find that even getting much slower, any advice?   @glenn-jocher 

Thanks

**Comment by glenn-jocher** [comment]
@fwzdev1 results are results, I'm not sure what I can contribute here.

Note that ONNX runtime comes in CPU and GPU flavors, not sure about DNN.
