### ISSUE TITLE
tensorrt using real time video.

### ISSUE THREAD

**Issue by Wooks-git** [ultralytics/yolov5#5829]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

can i use model.trt at detect.py like this command?

$ python detect.py --source 0 --weights xx.trt

**Comment by glenn-jocher** [comment]
@Wooks-git yes
