### ISSUE TITLE
How to save the full image from the result of detected video (not just crop)

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#5832]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,
I have trained my model successfully.
I detected the video and use --save-crop to save the every detected image.
But, I want save the every detected image with full graph, not just the crop.
Anyone has solution?
I will be grateful for any help you can provide :)

**Comment by glenn-jocher** [comment]
@kellychen28 video inference results are already saved by default for video inference. You can extract frames from the saved video.

**Comment by ghost** [comment]
> @kellychen28 video inference results are already saved by default for video inference. You can extract frames from the saved video.

Hi, @glenn-jocher 
How can I get the every detected image with frames?
I just get the bounding box .txt of every detected image which can't show me in visualization.

**Comment by Zengyf-CVer** [comment]
@kellychen28 
See https://github.com/ultralytics/yolov5/blob/a4207a202d6801df4586a8e044f60c496d94aeb4/detect.py#L184

https://github.com/ultralytics/yolov5/blob/a4207a202d6801df4586a8e044f60c496d94aeb4/detect.py#L190-L191

**Comment by ghost** [comment]
> @kellychen28 See
> 
> https://github.com/ultralytics/yolov5/blob/a4207a202d6801df4586a8e044f60c496d94aeb4/detect.py#L184
> 
> https://github.com/ultralytics/yolov5/blob/a4207a202d6801df4586a8e044f60c496d94aeb4/detect.py#L190-L191

Hi @Zengyf-CVer 
How can I save images?
My detect input is video.
Now, I just save the output video(.mp4)、 bounding box text(.txt)、crop detected object images(.jpg) but not the full images(.jpg) with frames. :(

**Comment by Zengyf-CVer** [comment]
@kellychen28 
In fact, the easiest way is to output all the video frames through OpenCV. You can write your own script.

**Comment by SelenaXiong0** [comment]
'nosave': False

**Comment by BADSATNABAD** [comment]
Simply replace
save_one_box(xyxy, imc, file=save_dir / 'crops' / names[c] / f'{p.stem}.jpg', BGR=True)
to
save_one_box([0, 0, 1280, 640], imc, file=save_dir / 'crops' / names[c] / f'{p.stem}.jpg', BGR=True)
in detect.py file

**Comment by Aras-K** [comment]
@BADSATNABAD  
I have replaced the line as you have suggested, image will be saved but how can i include the bounding box of the detection in to the image?
thanks:)

**Comment by muhammadqasimc** [comment]
@BADSATNABAD I have also used your code, and like @Aras-K is saying, how do we include the bounding box to the final exported/cropped image?

Edit: I got a solution
if save_crop:
    save_one_box([0, 0, 1280, 640], **annotator.result()**, file=save_dir / 'crops' / names[c] / f'{p.stem}.jpg', BGR=True)`

use annotator.result() instead of imc

**Comment by Aras-K** [comment]
@muhammadqasimc thanks:) it works. now i need to find out how to reduce the amount of pictures it takes each detection

**Comment by donghyck** [comment]
@muhammadqasimc hi, is possible to save the image without crop the image like this?
![image](https://github.com/ultralytics/yolov5/assets/149129283/1fe84a24-ed93-4d30-a150-40c9f698c0af)

**Comment by MaldiniTran** [comment]
> @muhammadqasimc thanks:) it works. now i need to find out how to reduce the amount of pictures it takes each detection

I have already changed the code but I can't see where those pictures were stored. Can you help me?
