### ISSUE TITLE
option to set workers in val.py

### ISSUE THREAD

**Issue by iumyx2612** [ultralytics/yolov5#5835]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

line 155 in val.py: https://github.com/ultralytics/yolov5/blob/master/val.py#L155
```
dataloader = create_dataloader(data[task], imgsz, batch_size, stride, single_cls, pad=pad, rect=pt,
                                       prefix=colorstr(f'{task}: '))[0]
```
so this takes me to `create_dataloader` in[ dataset.py](https://github.com/ultralytics/yolov5/blob/master/utils/datasets.py#L95)
with `nw = min([os.cpu_count() // WORLD_SIZE, batch_size if batch_size > 1 else 0, workers])  # number of workers` 
in this case, `nw=8`
so the function 
```
loader(dataset,
                  batch_size=batch_size,
                  shuffle=shuffle and sampler is None,
                  num_workers=nw,
                  sampler=sampler,
                  pin_memory=True,
                  collate_fn=LoadImagesAndLabels.collate_fn4 if quad else LoadImagesAndLabels.collate_fn)
```
takes me to `InfiniteDataLoader` which inherits from torch DataLoader
bug happens at [line 134](https://github.com/ultralytics/yolov5/blob/master/utils/datasets.py#L134)
after some debugging, it takes me to` __init__.py` from pytorch
```
 for dll in dlls:
        is_loaded = False
        if with_load_library_flags:
            res = kernel32.LoadLibraryExW(dll, None, 0x00001100)
            last_error = ctypes.get_last_error()
            if res is None and last_error != 126:
                err = ctypes.WinError(last_error)
                err.strerror += f' Error loading "{dll}" or one of its dependencies.'
                raise err
```
and the err was: `' Error loading "E:\\Anaconda\\envs\\pytorch\\lib\\site-packages\\torch\\lib\\caffe2_detectron_ops_gpu.dll" or one of its dependencies.'`
This will not happen if I modify `nw=2`, which is what I usually use on my local machine and default on google colab
![image](https://user-images.githubusercontent.com/69593462/144182991-c6805528-c3a9-4540-a63e-a4bc9963cdbc.png)
So, I need an option to pass in the workers in val.py 

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@iumyx2612 hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
