### ISSUE TITLE
Input shape for ONNX export for 1920 x 1080

### ISSUE THREAD

**Issue by rlrahulkanojia** [ultralytics/yolov5#5836]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Using the command 
`python export.py --weights yolov5s.pt --img 1080 1920 --batch 1`

My input stream is 1920 X 1080 which is my required input size. But on converting onnx using the mentioned command, I am getting the input shape of onnx to be (1,3,1088,1920).

Can you please help me understand how can I get the required input shape in onnx i.e (1920,1080)

**Comment by glenn-jocher** [comment]
@rlrahulkanojia YOLOv5 P5 models have input shape constraints of stride 32, P6 models have input shape constraints of stride 64. 1080 meets neither, 1088 meets P5 constraints.
