### ISSUE TITLE
Use activation function

### ISSUE THREAD

**Issue by phucnhs** [ultralytics/yolov5#584]
## ❔Question
Hi !
How to use activation function FRELU,MISH....in source code ?
Thanks !

**Comment by glenn-jocher** [comment]
@phucnhs you can replace existing activations in any of the default modules in models/common.py or models/experimental.py. Most modules use `common.Conv()`, which is our basic lower level convolutional module. Replacing the LeakyReLU() activation here will have the greatest effect on YOLOv5 models. You can always `print(model)` to see the effects of your changes.

https://github.com/ultralytics/yolov5/blob/48e15be498ab6f3335743b5df7fbd02edd068160/models/common.py#L18-L28

**Comment by phucnhs** [comment]
Thanks bro ! 
I see try and close issues !

**Comment by PariaDarbani** [comment]
I changed the common.py to
self.act = nn.ReLU() if act is True else (act if isinstance(act, nn.Module) else nn.Identity())
but there is no change in print(model):
...
(act): SiLU(inplace=True)
...


but when I change "SiLU" in yolov5.pt then print(model):
...
(act): ReLU(inplace=True)
...

**Comment by glenn-jocher** [comment]
@PariaDarbani activation functions can be modified here for training custom models:
https://github.com/ultralytics/yolov5/blob/306fc0119a94915b91fb6ca6f46f2d50437152e3/models/common.py#L43

**Comment by PariaDarbani** [comment]
> @PariaDarbani activation functions can be modified here for training custom models:
> https://github.com/ultralytics/yolov5/blob/306fc0119a94915b91fb6ca6f46f2d50437152e3/models/common.py#L43

I am using inference mode, not training.
I want to change the activation function (SiLU) to ReLU for pre-trained yolov5s.
I changed the common.py but it doesn't work.

**Comment by glenn-jocher** [comment]
@PariaDarbani you never change a model at inference time, you use a fully trained model.

You can modify a model before training starts.
