### ISSUE TITLE
Why is 'del' called explicitly?

### ISSUE THREAD

**Issue by developer0hye** [ultralytics/yolov5#5842]
https://github.com/ultralytics/yolov5/blob/bc484579d7be481ffb5fba95020c515afd89be9b/train.py#L199

@glenn-jocher 

Hi jocher!

Why is 'del' called explicitly?

When I ran the below code with and without `del ckpt`, it printed same maximum batch size.

Can it save memory usage? 

If so, can we set larger batch size?

```python
import torch
import torchvision.models as models

def load_model(path, device):
    ckpt = torch.load(path, map_location=device)
    #Process...
    del ckpt
    return True


if __name__ == "__main__":
    torch.backends.cudnn.benchmark = True
    load_model("./yolox_x.pth", device="cuda") # dummy work
    model = models.resnet18().cuda()

    print("model is loaded!")
    batch_size = 1
    while True:
        try:
            dummy_input = torch.randn(batch_size, 3, 224, 224).cuda()
            dummy_output = model(dummy_input)
            
            dummy_output = dummy_output.sum()
            dummy_output.backward()
            
            batch_size += 1
            
            ckpt = model.state_dict()
            del ckpt
        except:
            break
    print(f"maximum batch size: {batch_size}")
```

Weight Link: https://github.com/Megvii-BaseDetection/YOLOX/releases/download/0.1.1rc0/yolox_x.pth

**Comment by glenn-jocher** [comment]
@developer0hye deleting a variable frees memory.

### AutoBatch

You can use [YOLOv5 AutoBatch](https://github.com/ultralytics/yolov5/pull/5092) (NEW) to find the best batch size for your training by passing `--batch-size -1`. AutoBatch will solve for a 90% CUDA memory-utilization batch-size given your training settings. AutoBatch is experimental, and only works for Single-GPU training. It may not work on all systems, and is not recommended for production use.

<img width="1746" alt="Screenshot 2021-11-06 at 12 31 10" src="https://user-images.githubusercontent.com/26833433/140608327-9c0c0baf-a0ee-4551-a4ff-5ee26b155c51.png">

Good luck and let us know if you have any other questions!

**Comment by developer0hye** [comment]
@glenn-jocher 

Thanks for your reply! AutoBatch seems good!


However, when I ran the code uploaded on this issue, I couldn't set more batchsize with 'del' comapred to omitting 'del'.

The results show that calling 'del' doesn't save memory usage. I am still confusing.

**Comment by glenn-jocher** [comment]
@developer0hye they're not related. Variables are typically stored in RAM. Batch size is correlated with CUDA memory.

**Comment by developer0hye** [comment]
@glenn-jocher 
Thanks!
