### ISSUE TITLE
export .pt -> .trt (custom training weight file)

### ISSUE THREAD

**Issue by Wooks-git** [ultralytics/yolov5#5849]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi i want to export my weight file to .trt

i tried to export at my jetson nano.

i modified --data default -> when i trained .yaml file

and i used this command.
$ python3 export.py --weights best.pt --include engine

but i met illegal instruction (core dumped)

question 1.
do i need to modify export.py for my custom training env?(i.e modify number of class, output shape, etc...)

question 2.
i trained at my own PC. so i have not dataset at my jetson.
but in yaml file have imgs path.
is it matter about illegal instruction?

**Comment by glenn-jocher** [comment]
@Wooks-git for TRT export example see our Colab notebook appendix section:

https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb#scrollTo=VTRwsvA9u7ln&line=1&uniqifier=1


```python
# TensorRT 
# https://developer.nvidia.com/nvidia-tensorrt-download
!lsb_release -a  # check system
%ls /usr/local | grep cuda  # check CUDA
!wget https://ultralytics.com/assets/TensorRT-8.2.0.6.Linux.x86_64-gnu.cuda-11.4.cudnn8.2.tar.gz  # download
![ -d /content/TensorRT-8.2.0.6/ ] || tar -C /content/ -zxf ./TensorRT-8.2.0.6.Linux.x86_64-gnu.cuda-11.4.cudnn8.2.tar.gz  # unzip
%pip list | grep tensorrt || pip install /content/TensorRT-8.2.0.6/python/tensorrt-8.2.0.6-cp37-none-linux_x86_64.whl  # install
%env LD_LIBRARY_PATH=/usr/local/cuda-11.1/lib64:/content/cuda-11.1/lib64:/content/TensorRT-8.2.0.6/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64  # add to path

!python export.py --weights yolov5s.pt --include engine --imgsz 640 640 --device 0
!python detect.py --weights yolov5s.engine --imgsz 640 640 --device 0
```
