### ISSUE TITLE
whether it sopport C++ interface? I want use it by C++ in windows.

### ISSUE THREAD

**Issue by xinsuinizhuan** [ultralytics/yolov5#585]

**Comment by yasenh** [comment]
Hi @xinsuinizhuan,  I tested it in libtorch c++ interface, but I run everything in Linux, I think you can make it work in Windows if you can setup some dependencies accordingly.
Just FYI: https://github.com/yasenh/libtorch-yolov5

**Comment by xinsuinizhuan** [comment]
> 
> 
> Hi @xinsuinizhuan, I tested it in libtorch c++ interface, but I run everything in Linux, I think you can make it work in Windows if you can setup some dependencies accordingly.
> Just FYI: https://github.com/yasenh/libtorch-yolov5

how to convert the yolov5s .pt to yolov5s.torchscript.pt? could you update a yolov5s.torchscript.pt file？ I want to have a test.

**Comment by Evoluange** [comment]
@xinsuinizhuan just see https://gist.github.com/jakepoz/eb36163814a8f1b6ceb31e8addbba270

**Comment by yasenh** [comment]
> > Hi @xinsuinizhuan, I tested it in libtorch c++ interface, but I run everything in Linux, I think you can make it work in Windows if you can setup some dependencies accordingly.
> > Just FYI: https://github.com/yasenh/libtorch-yolov5
> 
> how to convert the yolov5s .pt to yolov5s.torchscript.pt? could you update a yolov5s.torchscript.pt file？ I want to have a test.

https://github.com/yasenh/libtorch-yolov5#torchscript-model-export
