### ISSUE TITLE
youtube detect fail

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#5860]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

download new yolov5 
command
```
python detect.py --source https://www.youtube.com/watch?v=ydYDqZQpim8
```

```
Model Summary: 213 layers, 7225885 parameters, 0 gradients
WARNING: Environment does not support cv2.imshow() or PIL Image.show() image displays
cv2.imshow() is disabled in Docker environments
Traceback (most recent call last):
  File "detect.py", line 243, in <module>
    main(opt)
  File "detect.py", line 238, in main
    run(**vars(opt))
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 92, in run
    dataset = LoadStreams(source, img_size=imgsz, stride=stride, auto=pt)
  File "/work/Pictures/YOLOv5/new_yolov5_1019/yolov5/123/yolov5/utils/datasets.py", line 306, in __init__
    s = pafy.new(s).getbest(preftype="mp4").url  # YouTube URL
  File "/opt/conda/lib/python3.8/site-packages/pafy/pafy.py", line 124, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts=ydl_opts)
  File "/opt/conda/lib/python3.8/site-packages/pafy/backend_youtube_dl.py", line 31, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pafy/backend_shared.py", line 97, in __init__
    self._fetch_basic()
  File "/opt/conda/lib/python3.8/site-packages/pafy/backend_youtube_dl.py", line 54, in _fetch_basic
    self._dislikes = self._ydl_info['dislike_count']
KeyError: 'dislike_count'
```

**Comment by glenn-jocher** [comment]
@alicera thanks for the bug report. Yes I am able to reproduce the same error. Likely related to changes at YouTube unlike policy.

Please raise this issue directly at https://github.com/mps-youtube/pafy and https://github.com/ytdl-org/youtube-dl which are the packages responsible for downloading and parsing YouTube videos and metadata.

**Comment by mbgpriyanka** [comment]
@alicera - got the same error but solved it using-
!pip uninstall -y pafy
!pip install git+https://github.com/Cupcakus/pafy
 then run the detection onthe youtube link -works!

**Comment by alicera** [comment]
Solved it. Thanks for your help.

**Comment by hdnh2006** [comment]
> 

These commands don't solve the issue.

**Comment by hdnh2006** [comment]
> @alicera - got the same error but solved it using-
> !pip uninstall -y pafy
> !pip install git+https://github.com/Cupcakus/pafy
> then run the detection onthe youtube link -works!

These commands don't solve the issue.

**Comment by glenn-jocher** [comment]
@alicera @hdnh2006 see https://github.com/mps-youtube/pafy/pull/305

**Comment by hdnh2006** [comment]
This is a simpler solution:
`pip install youtube-dl==2020.12.2`

**Comment by glenn-jocher** [comment]
@hdnh2006 you're saying instead of:
```
pip install -U youtube-dl git+https://github.com/Cupcakus/pafy
```

run this?
```
pip install -U youtube-dl==2020.12.2 pafy
```

EDIT: seems to also work. Pinning the pip package is probably preferable to the git install, I'll submit a PR

**Comment by asparmar14** [comment]
> @alicera - got the same error but solved it using- !pip uninstall -y pafy !pip install git+https://github.com/Cupcakus/pafy then run the detection onthe youtube link -works!

Thanks this help
