### ISSUE TITLE
Where is the test.py file?? How can I calculate TP,TN,FP,FN in inference mode?

### ISSUE THREAD

**Issue by MdRanaSarkar** [ultralytics/yolov5#5867]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I can train successfully with yolov5 . But I want to check my performance with test datasets . How can I check it ?

**Comment by glenn-jocher** [comment]
@MdRanaSarkar `python val.py --task test` will evaluate metrics on a test set.
