### ISSUE TITLE
GridMask data augmentation

### ISSUE THREAD

**Issue by ioangatop** [ultralytics/yolov5#5869]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

[Grid-Mask](https://arxiv.org/pdf/2001.04086.pdf) utilizes information removal to achieve state-of-the-art results in a variety of computer vision tasks. Extensive experiments showed that Grid-Mask method outperforms the latest AutoAugment, which is way more computationally expensive due to the use of reinforcement learning to find the best policies.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ioangatop interesting, thanks for the link.
