### ISSUE TITLE
coco128 training problem

### ISSUE THREAD

**Issue by yuyiyunyang** [ultralytics/yolov5#5870]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

YOLOv5  2021-10-12 torch 1.10.0 CUDA:0 (NVIDIA T600 Laptop GPU, 4096.0MB)

pytorch1.10 +cuda11.3    yolov5 6.0    
![1](https://user-images.githubusercontent.com/18189244/144599134-74a62fac-417e-42eb-a2c1-96d2ff6d6063.PNG)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@yuyiyunyang CUDA 11 has known PyTorch issues on some Windows/Conda systems, I recommend reverting to CUDA 10, this has resolved this issue for other users.
