### ISSUE TITLE
Yolov5 onnx conversion accuracy down (opencv-c++)

### ISSUE THREAD

**Issue by RizwanMunawar** [ultralytics/yolov5#5871]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I followed yolov5 documentation for conversion of (.pt) -> (.onnx). conversion success.
but when I tried to run yolov5 with c++ following [code](https://github.com/UNeedCryDear/yolov5-opencv-dnn-cpp), its accuracy goes down.

How to get same accuracy with onnx?

**Comment by glenn-jocher** [comment]
@RizwanMunawar exported ONNX models produce near-identical results to PyTorch models. You can verify this on your own:

```python
python export.py --weights yolov5s.pt --include onnx

python val.py --weights yolov5s.pt
python val.py --weights yolov5s.onnx
```

**Comment by RizwanMunawar** [comment]
Thanks, I already checked above commands, its working, but with custom c++ code, its not working.

**Comment by glenn-jocher** [comment]
@RizwanMunawar then the fault is clearly isolated to your custom c++ code.
