### ISSUE TITLE
How to export to onnx with another opset version

### ISSUE THREAD

**Issue by aseprohman** [ultralytics/yolov5#5875]
Hello @glenn-jocher et all, 

I want to try export pt to onnx with opset 14 or 15. does somebody ever tried this? I see error unsupported onnx version where opset not 13.
does somebody have any suggestion ? 
thanks

**Comment by glenn-jocher** [comment]
@aseprohman use `--opset` argument

```bash
python export.py --include onnx --opset 13
```

**Comment by aseprohman** [comment]
> @aseprohman use `--opset` argument
> 
> ```shell
> python export.py --include onnx --opset 13
> ```

I have do this with opset 14 but failed with error message unsupported version
