### ISSUE TITLE
channels is not matched. I try to use my own datasets,then i got this bug

### ISSUE THREAD

**Issue by jean123456789-china** [ultralytics/yolov5#5876]
### YOLOv5 Component

_i used yolov5s.pt .

### Bug
Traceback (most recent call last):
  File "E:/Python开发/mineVideo/yolov5-5.0/train.py", line 577, in <module>
    train(hyp, opt, device, tb_writer)
  File "E:/Python开发/mineVideo/yolov5-5.0/train.py", line 307, in train
    pred = model(imgs)  # forward
  File "G:\anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Python开发\mineVideo\yolov5-5.0\models\yolo.py", line 123, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "E:\Python开发\mineVideo\yolov5-5.0\models\yolo.py", line 139, in forward_once
    x = m(x)  # run
  File "G:\anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Python开发\mineVideo\yolov5-5.0\models\common.py", line 171, in forward
    return self.conv(torch.cat([x[..., ::2, ::2], x[..., 1::2, ::2], x[..., ::2, 1::2], x[..., 1::2, 1::2]], 1))
  File "G:\anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Python开发\mineVideo\yolov5-5.0\models\common.py", line 42, in forward
    return self.act(self.bn(self.conv(x)))
  File "G:\anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "G:\anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "G:\anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\conv.py", line 442, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [32, 12, 3, 3], expected input[4, 16, 320, 320] to have 12 channels, but got 16 channels instead
Images sizes do not match. This will causes images to be display incorrectly in the UI.

### Environment

i haved installed all environments in requirements. 
-python 3.8

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Zengyf-CVer** [comment]
@jean123456789-china 
Please clone the latest version of YOLOv5 v6.0.
```shell
$ git clone https://github.com/ultralytics/yolov5
$ cd yolov5
$ pip install -r requirements.txt
```

**Comment by jean123456789-china** [comment]
> @jean123456789-china Please clone the latest version of YOLOv5 v6.0.
> 
> ```shell
> $ git clone https://github.com/ultralytics/yolov5
> $ cd yolov5
> $ pip install -r requirements.txt
> ```

Thanks for help.I will try it and the result  will be updated soon.

**Comment by jean123456789-china** [comment]
i tried the yolov5-6.0,but i got the following tip:
ValueError: Media Bounding Box Debugger/Images is invalid.Please remove invalid filename characters.

**Comment by Zengyf-CVer** [comment]
@jean123456789-china 
Can you post the full screenshot?

**Comment by jean123456789-china** [comment]
![image](https://user-images.githubusercontent.com/64077307/144702562-2dc79a0f-091f-4cfc-b358-943f9d1f71da.png)
 now, it can run. i set 50 epochs, however, when it runs to 4th epoch, it comes to the following tip.
![image](https://user-images.githubusercontent.com/64077307/144702624-5744c2f5-e5d0-4746-ae6e-8fdf0fad5b70.png)
![image](https://user-images.githubusercontent.com/64077307/144702640-561363dc-a7a8-4678-92a2-2a0a5121bcb0.png)

**Comment by Zengyf-CVer** [comment]
@jean123456789-china 
The problem is found, see: https://github.com/ultralytics/yolov5/discussions/5308
This problem may be the version of wandb, you can try to upgrade or downgrade the version of wandb. If you still can’t solve it, you can ask W&B experts: @AyushExel

**Comment by AyushExel** [comment]
@Zengyf-CVer @jean123456789-china this bug was fixed a few weeks ago. You're probably running an older version of the repo. Try cloning again or run `git pull` inside the yolov5 directory

**Comment by jean123456789-china** [comment]
> @Zengyf-CVer @jean123456789-china this bug was fixed a few weeks ago. You're probably running an older version of the repo. Try cloning again or run `git pull` inside the yolov5 directory

Thanks for ur advice. I have already cloned the latest yolov5-6.0 version, i will try to update my own wandb in conda environment.The result will be updated soon.

**Comment by jean123456789-china** [comment]
> @jean123456789-china The problem is found, see: #5308 This problem may be the version of wandb, you can try to upgrade or downgrade the version of wandb. If you still can’t solve it, you can ask W&B experts: @AyushExel

Thank u so much.

**Comment by jean123456789-china** [comment]
> 

i try to update the wandb, but it is the latest. i don't know which version it should be back off to . At last, i back the yolo to yolov5 -5.0, and the Epoch runs. Also ,the channel is matched. It is fucking surprising. 
![image](https://user-images.githubusercontent.com/64077307/144704713-962b2a26-e110-4cc5-a62b-ccb5902e6c19.png)

Thank u for ur help.  @AyushExel,@Zengyf-CVer
