### ISSUE TITLE
mAP is 0 when using val.py to do inference on custom datasets

### ISSUE THREAD

**Issue by unw9527** [ultralytics/yolov5#5877]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Validation

### Bug

I installed all the packages required except that the torch version is 1.9.0+cu111 and torchvision version is 0.10.0+cu111. 

I trained on a custom dataset and the training process seemed to be fine. But when I want to measure mAP on the test set using command `python val.py --img 1600 --data /home/xxx/yolov5/data/dataset.yaml --weights /home/xxx/yolov5/runs/train/exp/weights/best.pt --task test` , where dataset.yaml contains the config for the custom dataset and best.pt is the checkpoint I got from training, it will give me a keyerror and the mAP measured is always 0. Below is the output.

```
val: data=/home/xxx/yolov5/data/dataset.yaml, weights=['/home/xxx/yolov5/runs/train/exp/weights/best.pt'], batch_size=32, imgsz=1600, conf_thres=0.001, iou_thres=0.6, task=test, device=, workers=8, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=runs/val, name=exp, exist_ok=False, half=False, dnn=False
YOLOv5 🚀 v6.0-121-g360eec6 torch 1.9.0+cu111 CUDA:0 (GeForce RTX 3090, 24268MiB)

Fusing layers...
Model Summary: 213 layers, 7015519 parameters, 0 gradients, 15.8 GFLOPs
test: Scanning '/home/xxx/yolo/PyTorch-YOLOv3-master/data/custom/valid.cache' images and labels... 200 found, 0 missing,
test: Scanning '/home/xxx/yolo/PyTorch-YOLOv3-master/data/custom/valid.cache' images and labels... 200 found, 0 missing,
test: Scanning '/home/xxx/yolo/PyTorch-YOLOv3-master/data/custom/valid.cache' images and labels... 200 found, 0 missing,
test: Scanning '/home/xxx/yolo/PyTorch-YOLOv3-master/data/custom/valid.cache' images and labels... 200 found, 0 missing,
test: Scanning '/home/xxx/yolo/PyTorch-YOLOv3-master/data/custom/valid.cache' images and labels... 200 found, 0 missing,
test: Scanning '/home/xxx/yolo/PyTorch-YOLOv3-master/data/custom/valid.cache' images and labels... 200 found, 0 missing,
test: Scanning '/home/xxx/yolo/PyTorch-YOLOv3-master/data/custom/valid.cache' images and labels... 200 found, 0 missing,
test: Scanning '/home/xxx/yolo/PyTorch-YOLOv3-master/data/custom/valid.cache' images and labels... 200 found, 0 missing,
test: Scanning '/home/xxx/yolo/PyTorch-YOLOv3-master/data/custom/valid.cache' images and labels... 200 found, 0 missing,
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95:  14%|█▍        | 1/7 [00:08<00:49,  8.32s/it] Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/xxx/miniconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/xxx/miniconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xxx/yolov5/utils/plots.py", line 237, in plot_images
    cls = names[cls] if names else cls
KeyError: 2
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95:  29%|██▊       | 2/7 [00:11<00:26,  5.37s/it] Exception in thread Thread-5:
Traceback (most recent call last):
  File "/home/xxx/miniconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/xxx/miniconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xxx/yolov5/utils/plots.py", line 237, in plot_images
    cls = names[cls] if names else cls
KeyError: 2
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95:  43%|████▎     | 3/7 [00:18<00:24,  6.04s/it] Exception in thread Thread-7:
Traceback (most recent call last):
  File "/home/xxx/miniconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/xxx/miniconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xxx/yolov5/utils/plots.py", line 237, in plot_images
    cls = names[cls] if names else cls
KeyError: 2
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 7/7 [00:26<00:00,  3.77s/it]
                 all        200          0          0          0          0          0
Speed: 1.7ms pre-process, 11.1ms inference, 13.2ms NMS per image at shape (32, 3, 1600, 1600)
Results saved to runs/val/exp4
```

When I checked the output, it seems that the model can predict the bounding boxes. But somehow it cannot measure any metrics.

![image](https://user-images.githubusercontent.com/67528514/144698498-4300f5ac-b975-4764-8467-717709351063.png)

The output is as follows:

![image](https://user-images.githubusercontent.com/67528514/144698521-cc331222-457c-470d-9e52-087cffd4077a.png)

### Environment

- YOLO: YOLOv5 🚀 v6.0-121-g360eec6 torch 1.9.0+cu111 CUDA:0 (GeForce RTX 3090, 24268MiB)
- System: Ubuntu 16.04.6 LTS
- Python: 3.8.10

### Minimal Reproducible Example

See above.

### Additional

I wonder what it means for the KeyError that it gives. And why labels in inference are 0? Labels are not 0 during training. And the label format (.txt files) are generated exactly the same way for training and testing.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@unw9527 YOLOv5 is showing you right in your output that your test set has 0 labels. I don't know what sort of metrics you expect to have computed with no labels.

**Comment by Tailwhip** [comment]
I had the same problem when I was trying to make a test using tensorrt engine with float16 (half) precision. After adding --half to the python val.py command everything went fine.

**Comment by anhtr-nguyn** [comment]
I have the same issue !!==

**Comment by glenn-jocher** [comment]
@anhtr-nguyn it's great to hear that adding the --half flag resolved the issue for you as well! This flags use half-precision (float16) during inference. Thank you for sharing your solution with the community!
