### ISSUE TITLE
High RAM consumption in inference 

### ISSUE THREAD

**Issue by mohammad69h94** [ultralytics/yolov5#5878]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

PyTorch Hub

### Bug

High RAM consumption during inference using Torch hub component. it takes 3-4 GB of Ram and it is very high. does solve this issue in the latest updates? or do you have any solution for this?

### Environment

yolov5-s
windows 10
python 3.8

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@mohammad69h94 I'm removing the bug label. Bugs cause error messages and you have no error messages, so everything is working correctly.

PyTorch isn't exactly a deployment format, you probably want to export to ONNX, TensorRT, TorchScript etc.
