### ISSUE TITLE
Explanation of labels.jpg in run/train/exp 

### ISSUE THREAD

**Issue by sml105012013** [ultralytics/yolov5#5884]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I got an image labels.jpg in run/train/exp. Could anyone explain the meaning of charts (except the top-left one) in labels.jpg ? Thank you!
![labels](https://user-images.githubusercontent.com/52030889/144715850-d0449c25-5573-4884-8c7d-9d98a8da5066.jpg)

**Comment by ChinaRush** [comment]
in plots.py line 330 :
`def plot_labels(labels, names=(), save_dir=Path('')):`
top-right is the rectangles you labeled.(x,y,w,h) is the label of your each instance  label
