### ISSUE TITLE
Speed on mobile

### ISSUE THREAD

**Issue by GuoQuanhao** [ultralytics/yolov5#5892]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, This is really a great repo, IDetection detection speed is so amazing, how you get such speed, I use torchscript for yolov5s, but the speed is so slow.

**Comment by WillowWisp** [comment]
I'm having 200-300ms with yolov5n Torchscript on Android/iOS, which is really poor for real-time detection. Am I doing something wrong or this is normal?

**Comment by glenn-jocher** [comment]
@WillowWisp see the iOS iDetection Speeds table in https://github.com/ultralytics/yolov5/issues/1276

## 🚀 Feature
We'd like to create an iDetection Speed Table for each year's iPhone release, going back as far as iDetection will run, which may be around iPhone 5 or 6. Crowd-sourcing the table will help show real-world performance of the models on various hardware. 

**If you have an iOS device, you can contribute** by downloading [iDetection](https://apps.apple.com/us/app/idetection/id1452689527), testing your speeds, and then uploading your results here. We try to test near 100% battery at room temperature (about 25°C), and record the speed after about 10 seconds of inference for each model. 

Please help by uploading your results! Thank you!!

<img src="https://user-images.githubusercontent.com/26833433/98019191-be36e000-1e01-11eb-97e0-69ca25c30531.jpg" width="800">


## iDetection v7.8 Inference Speeds

&nbsp; | Year | ASIC<br>-process | ANE<br>(TOPS) || YOLOv5s<br>(ms)   |YOLOv5m<br>(ms)   |YOLOv5l<br>(ms)   |YOLOv5x<br>(ms)
--- |---  |---  |---  |-|---   |---   |---   |---
iPhone 6  | 2014  | [A8-20nm](https://en.wikipedia.org/wiki/Apple_A8)  |-  ||90  |180  |350  |500
iPhone 6s  | 2015  | [A9-16nm](https://en.wikipedia.org/wiki/Apple_A9)  |-  ||148  |216  |304  |475
iPhone 7  | 2016  | [A10-16nm](https://en.wikipedia.org/wiki/Apple_A10)  |-  ||94.7  |140.7  |216.7  |289.8
iPhone 8/X  | 2017  | [A11-10nm](https://en.wikipedia.org/wiki/Apple_A11)  |0.6  ||-  |-  |-  |-
iPhone XR/XS  | 2018  | [A12-7nm](https://en.wikipedia.org/wiki/Apple_A12)  |5.0  ||22.3  |25.8  |43.2 |57.7
iPhone 11 | 2019  | [A13-7nm](https://en.wikipedia.org/wiki/Apple_A13)  |6.0 ||17.4  |21.3  |27.8  |41.2
iPhone 12 | 2020  | [A14-5nm](https://en.wikipedia.org/wiki/Apple_A14)  |11.0  ||14.3  |16.5  |21.0  |28.8
iPhone 13 | 2021  | [A15-5nm](https://en.wikipedia.org/wiki/Apple_A15)  |15.8  ||  |  |  |

*CoreML models exported as FP8 320x192 with [release v3.1](https://github.com/ultralytics/yolov5/releases)
*Measured with [iDetection v7.8](https://apps.apple.com/us/app/idetection/id1452689527) at 100% battery at 25°C. Average speed after 10 seconds recorded.

**Comment by WillowWisp** [comment]
@glenn-jocher Thank you for the answer. There's definitely something wrong with my yolov5n Torchscript model/implementation on mobile because as I tested, its speed is much slower than on the iDetection app, but I'm still new to ML so I don't know what's the cause of this. Could you please take a look?

# Benchmark

iPad 5th gen:
- iDetection yolov5n: ~50ms
- My yolov5n: ~110ms

iPhone 13:
- iDetection yolov5n: ~10ms
- My yolov5n: ~100ms

# My yolov5n information:
- Input size: 320x320
- Class number: 1

- Train command:
```
!python train.py --img 320 --batch 32 --epochs 10 --data "$dataset_path" --weights yolov5n.pt --name yolov5s_results_test  --cache
```

- Export script:
```
        f = file.with_suffix('.torchscript')
        fl = file.with_suffix('.torchscript.ptl') ### I'm using this model with --optimize option

        ts = torch.jit.trace(model, im, strict=False)
        d = {"shape": im.shape, "stride": int(max(model.stride)), "names": model.names}
        extra_files = {'config.txt': json.dumps(d)}  # torch._C.ExtraFilesMap()
        (optimize_for_mobile(ts) if optimize else ts).save(str(f), _extra_files=extra_files)
        (optimize_for_mobile(ts) if optimize else ts)._save_for_lite_interpreter(str(fl), _extra_files=extra_files)
```

- iOS implementation (`'LibTorch-Lite-Nightly', '~>1.11.0.20211012'`):
```
        torch::jit::mobile::Module _impl = torch::jit::_load_for_mobile(filePath.UTF8String);

        at::Tensor tensor = torch::from_blob(imageBuffer, { 1, 3, inputHeight, inputWidth }, at::kFloat);
        tensor.print();
        
        std::vector<at::IValue> inputs = { tensor };

        CFTimeInterval startTime = CACurrentMediaTime();
        auto outputTuple = _impl.forward(inputs).toTuple();
        CFTimeInterval elapsedTime = CACurrentMediaTime() - startTime;
        NSLog(@"inference time:%f", elapsedTime);
```

I'm thinking that maybe this is because the inference is running on CPU instead of GPU?

**Comment by evercherish** [comment]
Hi, WillowWisp,
I have met the same question, my model runs faster on A14 chip rather than A15.
It seems my model runs on CPU and GPU, not ANE.
Have you solved it?

**Comment by glenn-jocher** [comment]
@evercherish, thanks for reaching out. To ensure optimal inference, verify that your model is running on the desired device. On some iOS devices, it’s important to explicitly set the device for inference. You can try using `torch::jit::getAnomalyEngine()`, which may help you direct your model to run on the ANE.

Good luck! Let me know if you have any other questions.
