### ISSUE TITLE
How do I change the bounding box color?

### ISSUE THREAD

**Issue by omer3012345** [ultralytics/yolov5#5893]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How do I change the bounding box color from the default red to a color like green? When I check the plot.py file, the code for the color is set to (128, 128, 128) which is gray and not red. I haven't found the rgb value for red and am wondering how to go about changing it to green. Thanks

**Comment by Adrien-LUDWIG** [comment]
I believe the plot you are looking for is [here](https://github.com/ultralytics/yolov5/blob/1075488d893f2167737d89549c3f675b0713aa5a/utils/plots.py#L361), using the `colors` variable, which is an instance of the [Colors class](https://github.com/ultralytics/yolov5/blob/1075488d893f2167737d89549c3f675b0713aa5a/utils/plots.py#L31-L49).

You should be able to change the colors by modifying it.

**Comment by omer3012345** [comment]
@adrien-anton How do I go about changing it? I don't see the color code for default red which is #FF0000

**Comment by Zengyf-CVer** [comment]
@omer3012345 
See: https://github.com/ultralytics/yolov5/blob/1075488d893f2167737d89549c3f675b0713aa5a/utils/plots.py#L35-L36
