### ISSUE TITLE
Pip package

### ISSUE THREAD

**Issue by kartik-nighania** [ultralytics/yolov5#5897]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

It will be great if we can pip install this repo

### Use case

- easy to integrate and use in existing projects.
- will not have to exclude this folder from the static analyzers and other code formatting tools.
- Nested Github repo issue solved while integrating yolov5 as a package rather than a directory in existing git repo code.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by kartik-nighania** [comment]
@glenn-jocher should I move forward with a PR?

**Comment by glenn-jocher** [comment]
@kartik-nighania if you have some expertise on the subject then sure please submit a PR. We've tried this in the past but weren't able to cleanly migrate to a pip structure without breaking changes to existing workflows.

**Comment by kartik-nighania** [comment]
@glenn-jocher Thanks for the quick reply.

Can u tell me in a bit detail what exactly you are looking for. What all comes under support for existing workflow that when done will qualify for a pip based migration.

Also it'll be great if you can tell what all issues you faced in the past in doing this.

**Comment by glenn-jocher** [comment]
@kartik-nighania see https://github.com/ultralytics/yolov5/pull/3357

**Comment by Borda** [comment]
there is even older one #465 :rabbit:
