### ISSUE TITLE
SKU data set download

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#5898]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

@glenn-jocher 
Where is this `download` function?
https://github.com/ultralytics/yolov5/blob/1075488d893f2167737d89549c3f675b0713aa5a/data/SKU-110K.yaml#L31

**Comment by glenn-jocher** [comment]
@Zengyf-CVer the import is right there in the script a few lines up
https://github.com/ultralytics/yolov5/blob/1075488d893f2167737d89549c3f675b0713aa5a/data/SKU-110K.yaml#L25

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
Thank you very much.
