### ISSUE TITLE
choose proper "imgsz"

### ISSUE THREAD

**Issue by hamid-mp** [ultralytics/yolov5#5899]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi. in `detect.py `there is a parameter, `img_size=640`.This parameter has huge impact on inference time and preprocessing but reducing it comes with reduction of accuracy...
How did you choose this value? and in general, what do you suggest to increase preprocessing and inference speed?

**Comment by hamid-mp** [comment]
in another work, [https://github.com/deepcam-cn/yolov5-face/blob/master/detect_face.py](url)
they chose this `img_size=2048` which i've got better result but lower speed

**Comment by glenn-jocher** [comment]
@hamid-mp --img size selection is up to user's own accruacy-speed tradeoff compromise and priorities. 

YOLOv5 P5 models are trained at 640, P6 models are trained at 1280.
