### ISSUE TITLE
why exist nc in yolov5.yaml ?

### ISSUE THREAD

**Issue by hee100** [ultralytics/yolov5#5901]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Set nc in coco128.yaml but
I don't know why I set nc in model.yaml as well (yolov5n.yaml etc.)
Also what is the role of nc in model.yaml?

Even if the nc of model.yaml and coco128.yaml are different, I was curious because it train normally.

**Comment by glenn-jocher** [comment]
@HeeHee100 dataset nc supersedes if both are present. 

model yaml can be used to construct a model with no dataset, so needs it's own nc.
