### ISSUE TITLE
SKU-110K dataset training problem

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#5903]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

@glenn-jocher 
I ran this command, and some error reports appeared as a result, as shown in the picture:
```shell
python train.py --img 640 --batch-size 16 --epochs 1 --data ./data/SKU-110K.yaml --cfg ./models/yolov5s.yaml --weights ./weights/yolov5s.pt
```
![001](https://user-images.githubusercontent.com/41098760/144985603-e81ac6ef-a1a9-49bc-9b98-66fa8b692ee2.png)
![002](https://user-images.githubusercontent.com/41098760/144985620-0da691c6-4a89-4127-ae9b-374f155b7876.png)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Zengyf-CVer yes this is normal for the SKU-110K dataset. You should probably ask the authors why their JPEGs suffer from so many problems, this is out of our hands.

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
I will consult the SKU author, thank you very much.
