### ISSUE TITLE
MP4 bug

### ISSUE THREAD

**Issue by jackluo04160124** [ultralytics/yolov5#5905]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

The MP4 video cannot be played after inferring the RTSP video stream

### Environment

-YOLO: YOLOv5 v6.0-67-g60e42e1 torch 1.10.0+cu102
-OS: Ubuntu 18.04
-Python: 3.9.0

### Minimal Reproducible Example

python detect.py --source rtsp://username:password@ip:port/stream1

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@jackluo04160124 we would need a public RTSP address that reproduces the issue in order to investigate.

**Comment by jackluo04160124** [comment]
My hardware is TP-Link webcam

**Comment by jackluo04160124** [comment]
When predicting the local video, detect.py also failed to play the MP4 video after running

**Comment by glenn-jocher** [comment]
@jackluo04160124 if you can reproduce a bug on a public RTSP address please let us know, otherwise your issue is non-actionable.

**Comment by jackluo04160124** [comment]
I would like to know how to exit and save video correctly while detect WebCam. I tried to type 'p', but it didn't exit.

**Comment by jackluo04160124** [comment]
The first few times, I juest  click Pycharm's Stop button result the .mp4 file damage.

**Comment by jackluo04160124** [comment]
When the IP address of the webcam is the Intranet of the company, I cannot provide the public IP address.

**Comment by glenn-jocher** [comment]
You can press 'q' or CTRL+C to exit webcam inference.

**Comment by jackluo04160124** [comment]
But I took advantage of your advice to quit Webcam Inference after saving the MP4 file showing that it has been damaged.

**Comment by jackluo04160124** [comment]
I also verified a local video exit with CTRL + C and the saved reasoning video was also corrupted.

**Comment by jackluo04160124** [comment]
I find the problem. Cause of some code deleted that save the MP4 file has been damaged.Think you very mach, please close the issue.

**Comment by Ame1999c** [comment]
> 我找到了问题所在。保存MP4文件的某些代码已删除的原因已损坏。认为你很马赫，请关闭问题。

What's the problem with saving the MP4 code? I also have this problem and want to know how to solve it.

**Comment by yangboz** [comment]
> > 我找到了问题所在。保存MP4文件的某些代码已删除的原因已损坏。认为你很马赫，请关闭问题。
> 
> What's the problem with saving the MP4 code? I also have this problem and want to know how to solve it.

https://github.com/ultralytics/yolov5/blob/master/detect.py 195行，基于openCV的视频写操作问题所导致。

**Comment by glenn-jocher** [comment]
@yangboz yes, it seems there was an issue with the video writing using OpenCV on line 195 of detect.py. The team is aware of the issue and will address it. Thank you for your understanding and support. Please don't hesitate to reach out if you have any further questions or concerns.

**Comment by Vector-Cross** [comment]
> yes, it seems there was an issue with the video writing using OpenCV on line 195 of detect.py. The team is aware of the issue and will address it. Thank you for your understanding and support. Please don't hesitate to reach out if you have any further questions or concerns.

does it fixed? I have encountered the same issue too.

**Comment by glenn-jocher** [comment]
@Vector-Cross the issue has been identified and we're currently working on a fix. We aim to have an update soon. Your patience is greatly appreciated 🙏. If there are any updates or workarounds in the meantime, we will be sure to communicate those. Stay tuned!
