### ISSUE TITLE
Where is the paper on Yolo5?

### ISSUE THREAD

**Issue by AI-Hunter** [ultralytics/yolov5#5906]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am searching published paper on yolo5 to know the contributions and differences between yolo4 and yolo5.
Would share the link, please?

**Comment by dariogonle** [comment]
There is currently no YOLOv5 paper.

**Comment by Makki93** [comment]
https://github.com/ultralytics/yolov5/issues/1333
