### ISSUE TITLE
Image segmentation training

### ISSUE THREAD

**Issue by prashant-py-debug** [ultralytics/yolov5#5909]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, is it possible to train the yolov5 for image segmentation?

**Comment by glenn-jocher** [comment]
@prashant-py-debug not currently, but this is on our 2022 roadmap

**Comment by Laitaps** [comment]
Is there any progress or an update on image segmentation?

**Comment by glenn-jocher** [comment]
@B0tBuilder second half of the year

**Comment by Laitaps** [comment]
Thank you.  Good to know.  I used your work in my thesis and would like to expand on it,  which will require image segmentation.  Thank you for your efforts, they are much appreciated.  I could not find a singular research paper, so I ended up citing various posts and your gitlab repo.

**Comment by glenn-jocher** [comment]
@B0tBuilder great thanks for the feedback!

**Comment by protestToViolence** [comment]
Does yolo5 trained model can be integrated with pixellib segmentation library?

**Comment by glenn-jocher** [comment]
@protestToViolence we are working on segmentation support but do not have segmentation models available yet! @AyushExel FYI

**Comment by Laitaps** [comment]
> @B0tBuilder great thanks for the feedback!

If you know anyone who is a registered endorser for cs.CV at arXiv, I can publish it there.  It would contribute another bit of research using YOLOv5.  There is quite a bit right now, around 75 papers when conducting a keyword search.

**Comment by AyushExel** [comment]
@B0tBuilder hey. Not sure if I understood clearly. You're saying there are 75 yolov5 based papers on arxiv?

**Comment by glenn-jocher** [comment]
@AyushExel @B0tBuilder Google Scholar shows about 5000 publications referring to YOLOv5, with about half those since the beginning of 2022. Not sure if they might contain duplicates though.
https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=yolov5&btnG=

**Comment by Laitaps** [comment]
> @B0tBuilder hey. Not sure if I understood clearly. You're saying there are 75 yolov5 based papers on arxiv?

If you do a search for just "YOLOv5", you will get 72 search responses.  I just did another query and included the text of the document and got 201.  Though I am not sure how it is handling PDF-only reports.  The 201 results may only be those submitted in LaTeX format.

When I find an endorser for cs.CV so I can submit, it will be 202 :-)
