### ISSUE TITLE
Problem when running in Rasberry Pi 4?

### ISSUE THREAD

**Issue by dariogonle** [ultralytics/yolov5#5910]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I've been working with YOLOv5 for a while, and right now I would like to run inference on a Rasberry Pi.
![image](https://user-images.githubusercontent.com/80393891/145065608-96bd722b-9a13-4803-8b51-e36144d2c790.png)

I have created a virtual enviroment where I have cloned this repo, and where I have installed all the depedencies in requirements.txt. But when I run detect.py, I have the following error: Illegal instruction (core dumped).
![image](https://user-images.githubusercontent.com/80393891/145065415-6622036b-71d4-43bd-973e-59c4d3f2e5fb.png)

Has anyone managed to run it on a Rasberry Pi 4?

It is weird because even if I only run python3 detect.py it gives me the same error.
![image](https://user-images.githubusercontent.com/80393891/145066955-5b6068f3-c2da-4283-9bbf-db7b799f364a.png)

**Comment by glenn-jocher** [comment]
@dariogonle see https://github.com/ultralytics/yolov5/discussions/3213

**Comment by dariogonle** [comment]
Thank you @glenn-jocher. I see that one of the options is to export the model to TFlite, but that's not my point. I would like to know if it is possible to run detect.py or not in the rasberry pi, and if someone have faced the same problem I do.

I case that it is not possible, I would like to know why.

Thank you in advance.

**Comment by glenn-jocher** [comment]
@dariogonle yes you can run detect.py anyplace you have a python3 environment

**Comment by prapti1998** [comment]
I am facing the same problem on raspberry pi 4. any solutions that worked @dariogonle ?

**Comment by dariogonle** [comment]
My problem was that the Pytorch version installed with pip install -r requirements.txt is not valid for an ARM arquitecture. You need to install it properly. I recomend you to use a docker image with Pytorch for ARM.

**Comment by yuehshienlin** [comment]
I'm facing the same problem on raspberry pi 4 64-bit.
I tried many ways to solve it but didn't work.
Finally,I get the answer from #4570 to modify my requirements.txt as follow and it works!

matplotlib>=3.2.2  
numpy==1.20.0  
opencv-python>=4.1.2  
Pillow  
PyYAML>=5.3.1  
scipy>=1.4.1  
torch==1.8.0  
torchvision==0.9.1  
tqdm>=4.41.0

**Comment by glenn-jocher** [comment]
@yuehshienlin glad to hear you found a solution! Thanks for sharing the updated requirements.txt, it will definitely be helpful for others facing similar issues on Raspberry Pi 4 64-bit.
