### ISSUE TITLE
Why the inference and training so fast?

### ISSUE THREAD

**Issue by fwzdev1** [ultralytics/yolov5#5914]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

First of all, Thank you so much for your great work! @glenn-jocher 

I was really curious about what makes your yolo series so fast, especially in inference. Are there some tricks in detecting or model building? 

What makes me ask this question:
I wrote a basic and light backbone for centernet with just CBL and SE blocks and no tricks in inference at all. Though it has only about 10 layers and 90kb of weights, it still infers much slower than yolov5n with width and height ratio at 0.1, which has about 100 layers and 800kb of weights. (10ms vs 4ms)
This reminds me of your yolov3 implenmentation. I tried several yolov3 version from different people before, and no one can be as fast as your yolov3, not even close. 

Eager to receive your feedback! So much thanks!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@fwzdev1 the answer to your questions is not in a single place, it's due to an accumulation of hundreds of small improvements everywhere built into the YOLOv5 commit list (which is 1600+ commits long).
https://github.com/ultralytics/yolov5/commits/master

**Comment by barmyscotsman** [comment]
In the roboflow article, the line graph and bar graph does not match. In the line graph, it indicates is approx 2ms but on the bar graph, it is approx 7ms. Is that a mistake?

**Comment by glenn-jocher** [comment]
@barmyscotsman I'm not sure, but be aware there's many factors that go into speed. Perhaps one result is batch-size 1 and the other batch-size 32. We display both in our README:

https://github.com/ultralytics/yolov5#pretrained-checkpoints
