### ISSUE TITLE
Training from previously cached images

### ISSUE THREAD

**Issue by Dipon12** [ultralytics/yolov5#592]
## ❔Question
Is it possible to start training from previously cached images? if possible, how? and where .cache file is saved in yolo v5???
## Additional context
I am using Google Colab for training Yolo v5x on custom Dataset

**Comment by glenn-jocher** [comment]
Cached images reside in system RAM.

**Comment by peijason** [comment]
@glenn-jocher 
How to specify **no-cache**??

**Comment by glenn-jocher** [comment]
@peijason not caching is the default behavior. You don't specify anything.
