### ISSUE TITLE
how to save weights after each epoch or N epochs? thanks

### ISSUE THREAD

**Issue by nqthai309** [ultralytics/yolov5#5921]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

how to save weights after each epoch or N epochs? thanks.

**Comment by glenn-jocher** [comment]
@nqthai309 best.pt is saved on every best epoch. last.pt is saved on every `--save-period` (default 1, every epoch). see train.py `--save-period` argument:

https://github.com/ultralytics/yolov5/blob/c77a5a84e3c6083d4e707d2e252c1499e294495c/train.py#L473

**Comment by nqthai309** [comment]
@glenn-jocher  but they overwrite the old model, i want to have separate checkpoints for each epoch

**Comment by glenn-jocher** [comment]
@nqthai309 you can customize checkpointing here:
https://github.com/ultralytics/yolov5/blob/c77a5a84e3c6083d4e707d2e252c1499e294495c/train.py#L375-L394

**Comment by nqthai309** [comment]
I want to save "weights-ep1.pt", "weights-ep2.pt", ... in folder runs/train/exp/weights/ how should I edit, thanks <3
