### ISSUE TITLE
I want to train custom network 

### ISSUE THREAD

**Issue by donggru** [ultralytics/yolov5#5927]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I followed up the guide, train the model using custom DataSet.
However, I worked at learning R&D to develop the custom Product,
So I want to train the optimized network(User-defined)

To do this, How can i do this?

**Comment by Zengyf-CVer** [comment]
See: 
- https://github.com/ultralytics/yolov5/blob/master/models/yolov5s.yaml
- https://github.com/ultralytics/yolov5/blob/master/models/common.py
