### ISSUE TITLE
Is it possible to detect only even frames of a video?

### ISSUE THREAD

**Issue by hee100** [ultralytics/yolov5#5928]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am showing images and videos of images detected by YOLOv5 in a GUI made with PyQT.( Only YOLOv5 detection should be used. ) And i'm making a video speed function in the GUI.

I want to use fast forward when clicking fast or very fast in the GUI. But I don't know how to quickly play a video in YOLOv5. The way that came to mind is to convert yolo image processing frames to even frames only. But I don't know where to edit the yolov5 file. Any help would be appreciated.

**Comment by Zengyf-CVer** [comment]
@HeeHee100 
The fast forward function you mentioned is a function designed in the GUI, and the video frame can be controlled through the video component in the GUI. I have done it on the web, and the principle is the same.
