### ISSUE TITLE
Problem with Loading trained yolo weights from local device.

### ISSUE THREAD

**Issue by iresusharma** [ultralytics/yolov5#5930]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Hi,
i have weights from trained yolov5 model on my custom dataset, but while i am loading it from my local device its showing me error that :
Traceback (most recent call last):
  File "/yolov5/app.py", line 14, in <module>
    model = torch.hub.load('./yolov5', 'custom', path='./weights/best.pt', source='local')  # local repo
  File "venv/yolov5/lib/python3.9/site-packages/torch/hub.py", line 399, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "venv/yolov5/lib/python3.9/site-packages/torch/hub.py", line 425, in _load_local
    hub_module = import_module(MODULE_HUBCONF, hubconf_path)
  File "venv/yolov5/lib/python3.9/site-packages/torch/hub.py", line 76, in import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
FileNotFoundError: [Errno 2] No such file or directory: './yolov5/hubconf.py'

P.S. i am trying to load model with following line of code:- 
model = torch.hub.load('path/to/yolov5', 'custom', path='path/to/best.pt', source='local')  # local repo (found here https://github.com/ultralytics/yolov5/issues/36)
And the above not found file (hubconf.py) is also present in the repo.
Any leads would be appreciated. Thanks

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by DeepKnowledge1** [comment]
> 

path='**path/to/best.pt**, is that the model directory?

**Comment by iresusharma** [comment]
yes, its where my model best weights are

**Comment by glenn-jocher** [comment]
@iresusharma do not raise a bug report for user error. PyTorch Hub model loading works correctly. See https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading for instructions.

<img width="1003" alt="Screen Shot 2021-12-09 at 1 23 16 PM" src="https://user-images.githubusercontent.com/26833433/145395864-a4f9c930-dd06-4e26-9386-d51ba4533f9d.png">
