### ISSUE TITLE
Weird results in detect.py with the option --half?

### ISSUE THREAD

**Issue by dariogonle** [ultralytics/yolov5#5935]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am running several experiments on a Jetson Nano. The simplest one is to just run detect.py. In this case I get an average inference time of 84ms.
![image](https://user-images.githubusercontent.com/80393891/145427669-67ad3dcb-1de3-4186-975d-2e25bf0d5ee7.png)

The second experiment consist of repating the same but with the --half argument. For my surprise, I get a higher inference time (94ms).
![image](https://user-images.githubusercontent.com/80393891/145427929-10339b10-7765-4195-a842-7c17c798c770.png)

As far I am concerned, with the --half option it should be using 16FP instead 32, therefore it should be faster, shouldn't it?

Does someone know why is this happening?

Thank you in advance.

### Additional
I also test one model. Without the --half I get:
![image](https://user-images.githubusercontent.com/80393891/145429182-9af8a144-a702-49ea-9cb7-6f525531e69d.png)

But with it I get:
![image](https://user-images.githubusercontent.com/80393891/145429263-cd9a8f1a-f443-41f7-bb88-7e8114e4893c.png)

Shouldn't I get more without it?

_No response_

**Comment by glenn-jocher** [comment]
@dariogonle quantized acceleration is hardware, software and driver dependent, i.e. not all combinations support improvements in latency.
