### ISSUE TITLE
Large Performance difference between detect.py and  PyTorch Hub

### ISSUE THREAD

**Issue by pasmai** [ultralytics/yolov5#5936]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am running the inference both times on Windows on my GPU. The model is YOLOv5l and zidane.jpg was used as an input.
`YOLOv5  2021-12-2 torch 1.10.0+cu113 CUDA:0 (NVIDIA GeForce RTX 2080 Ti, 11264MiB)`

When using `model = torch.hub.load('ultralytics/yolov5', 'yolov5l')` the inference time I get is usually around 26-30 ms.
But using python `detect.py --source data/images/zidane.jpg --weights models/trained/yolov5l.pt` on the same identical image, I get an inference time of 12-15 ms.

Can anybody explain the difference in performance? And is there something I can do to speed-up the PyTorch Hub approach?

**Comment by glenn-jocher** [comment]
@pasmai 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀.  **Your issue is not reproducible.**

<img width="1349" alt="Screen Shot 2021-12-09 at 7 07 39 PM" src="https://user-images.githubusercontent.com/26833433/145451758-e9d8e9a6-62cb-4a01-8a0a-6dfca7d1df19.png">


We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by alawliat** [comment]
@pasmai I had a similar issue, I am not sure if ours are related in anyway but in my case the .pt file that was being exported (Python) was corrupt. (I export as a .pt from PyTorch Hub and load the model in C++). I think something went wrong in the latest update to master, it seems the latest update involved PyTorch Hub actually. I reverted back to an old commit on this repo from 2 weeks ago and everything was good again. 

When you execute this line, PyTorch hub pulls from Master if you do not have the repo cached already.

`model = torch.hub.load('ultralytics/yolov5', 'yolov5l')`

Try reverting back to an old commit from a week or two ago.

**Comment by pasmai** [comment]
@glenn-jocher I have recreated your program on the most recent master branch and here are my results:
`perf.py`        29.5ms
`detect.py`    17.0 ms

PyTorch Hub is still noticeably slower than `detect.py`.
```py
# perf.py
import torch

model = torch.hub.load('ultralytics/yolov5', 'yolov5m')
model('data/images/zidane_scaled.png').print()
```

```sh
(venv) D:\Documents\GitHub\yolov5>py perf.py
Using cache found in C:\Users\Pascal/.cache\torch\hub\ultralytics_yolov5_master
YOLOv5  2021-12-2 torch 1.10.0+cu113 CUDA:0 (NVIDIA GeForce RTX 2080 Ti, 11264MiB)

Downloading https://github.com/ultralytics/yolov5/releases/download/v6.0/yolov5m.pt to C:\Users\Pascal\.cache\torch\hub\ultralytics_yolov5_master\yolov5m.pt...
100%|█████████████████████████████████████████████████████████████████████████████| 40.7M/40.7M [00:01<00:00, 26.7MB/s]

Fusing layers...
Model Summary: 290 layers, 21172173 parameters, 0 gradients
Adding AutoShape...
image 1/1: 360x640 3 persons, 2 ties
Speed: 28.5ms pre-process, 29.5ms inference, 4.5ms NMS per image at shape (1, 3, 384, 640)



(venv) D:\Documents\GitHub\yolov5>py detect.py --source data\images\zidane_scaled.png --weights yolov5m.pt
detect: weights=['yolov5m.pt'], source=data\images\zidane_scaled.png, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs\detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False
YOLOv5  v6.0-133-g4fb6dd4 torch 1.10.0+cu113 CUDA:0 (NVIDIA GeForce RTX 2080 Ti, 11264MiB)

Fusing layers...
Model Summary: 290 layers, 21172173 parameters, 0 gradients
image 1/1 D:\Documents\GitHub\yolov5\data\images\zidane_scaled.png: 384x640 3 persons, 2 ties, Done. (0.017s)
Speed: 0.5ms pre-process, 17.0ms inference, 3.5ms NMS per image at shape (1, 3, 640, 640)
Results saved to runs\detect\exp4

(venv) D:\Documents\GitHub\yolov5>
```

**Comment by glenn-jocher** [comment]
@pasmai we don't control your environment, but if you can create a reproducible disparity in a common environment like Colab, Kaggle, AWS or GCP instance, please let us know, otherwise there's nothing for us to do. 

We've provided profiling results in Colab that show similar inference speeds, so in reproducible common environments there is no issue we are aware of.

![image](https://user-images.githubusercontent.com/26833433/145574149-21855c8b-1ad8-49a0-b609-9e8a36d75a91.png)

**Comment by mohammad69h94** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.
> 
> ### Question
> I am running the inference both times on Windows on my GPU. The model is YOLOv5l and zidane.jpg was used as an input. `YOLOv5 2021-12-2 torch 1.10.0+cu113 CUDA:0 (NVIDIA GeForce RTX 2080 Ti, 11264MiB)`
> 
> When using `model = torch.hub.load('ultralytics/yolov5', 'yolov5l')` the inference time I get is usually around 26-30 ms. But using python `detect.py --source data/images/zidane.jpg --weights models/trained/yolov5l.pt` on the same identical image, I get an inference time of 12-15 ms.
> 
> Can anybody explain the difference in performance? And is there something I can do to speed-up the PyTorch Hub approach?
> 
> ### Additional
> _No response_

Did you do anything about this problem? I have similar issue!

**Comment by pasmai** [comment]
@mohammad69h94 Sadly no. On my server I have an RTX Titan and the issue was not as pronounced as on my personal machine. But I did not figure out any solution. 

Have you found anything?
And you know if I can turn-off or reduce the time it takes to pre-process the images?

**Comment by pasmai** [comment]
@glenn-jocher Is there at least way to remove/reduce the pre-process time when using the model hub?
My input images are already correctly scaled.

```
hub:           28.5ms pre-process, 29.5ms inference
detect.py:      0.5ms pre-process, 17.0ms inference
```

**Comment by glenn-jocher** [comment]
@pasmai detect.py does not include dataloading in pre-process.

**Comment by pasmai** [comment]
> @pasmai detect.py does not include dataloading in pre-process.

Is that something I can turn off? Or use additional model arguments in PyHub to bring down the pre-processing time?

**Comment by glenn-jocher** [comment]
@pasmai 👋 Hello! Thanks for asking about **inference speed issues**. YOLOv5 🚀 can be run on CPU (i.e. `--device cpu`, slow) or GPU if available (i.e. `--device 0`, faster). You can determine your inference device by viewing the YOLOv5 console output:

### detect.py inference
```bash
python detect.py --weights yolov5s.pt --img 640 --conf 0.25 --source data/images/
```
<img width="944" alt="detect.py" src="https://user-images.githubusercontent.com/26833433/140100842-e130b5f7-64cb-46c9-9386-72abadd19828.png">

### YOLOv5 PyTorch [Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) inference
```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Images
dir = 'https://ultralytics.com/images/'
imgs = [dir + f for f in ('zidane.jpg', 'bus.jpg')]  # batch of images

# Inference
results = model(imgs)
results.print()  # or .show(), .save()
# Speed: 631.5ms pre-process, 19.2ms inference, 1.6ms NMS per image at shape (2, 3, 640, 640)
```

### Increase Speeds

If you would like to increase your inference speed some options are:

- Use batched inference with [YOLOv5 PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)
- Reduce `--img-size`, i.e. 1280 -> 640 -> 320
- Reduce model size, i.e. YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s -> YOLOv5n
- Use half precision FP16 inference with `python detect.py --half` and `python val.py --half`
- Use a faster GPUs, i.e.: P100 -> V100 -> A100
- [Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) to ONNX for 2-3x CPU speedup with detect.py
- Use a free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

Good luck 🍀 and let us know if you have any other questions!

**Comment by UygarUsta99** [comment]
I do not think the performance difference is a result of using models via hub.I have created a script to test this issue but I did not use hub,instead I have loaded the model the way it is done in detect.py.I found that if you use LoadStreams from utils.datasets you will have faster inference speed.But I have also found that this method will cost you higher memory usage.You can check my script out below;

```
import argparse
import os
import sys
from pathlib import Path
import numpy as np
import cv2
import torch
import torch.backends.cudnn as cudnn

FILE = Path(__file__).resolve()
ROOT = FILE.parents[0]  # YOLOv5 root directory
if str(ROOT) not in sys.path:
    sys.path.append(str(ROOT))  # add ROOT to PATH
ROOT = Path(os.path.relpath(ROOT, Path.cwd()))  # relative

from models.common import DetectMultiBackend
from utils.datasets import IMG_FORMATS, VID_FORMATS, LoadImages, LoadStreams
from utils.general import (LOGGER, check_file, check_img_size, check_imshow, check_requirements, colorstr,
                           increment_path, non_max_suppression, print_args, scale_coords, strip_optimizer, xyxy2xywh)
from utils.plots import Annotator, colors, save_one_box
from utils.torch_utils import select_device, time_sync

@torch.no_grad()
def run(weights=ROOT / 'yolov5s.pt',  # model.pt path(s)
        source=ROOT / 'data/images',  # file/dir/URL/glob, 0 for webcam
        imgsz=640,  # inference size (pixels)
        conf_thres=0.25,  # confidence threshold
        iou_thres=0.45,  # NMS IOU threshold
        max_det=1000,  # maximum detections per image
        device=0,  # cuda device, i.e. 0 or 0,1,2,3 or cpu
        view_img=True,  # show results
        save_txt=False,  # save results to *.txt
        save_conf=False,  # save confidences in --save-txt labels
        save_crop=False,  # save cropped prediction boxes
        nosave=False,  # do not save images/videos
        classes=None,  # filter by class: --class 0, or --class 0 2 3
        agnostic_nms=False,  # class-agnostic NMS
        augment=False,  # augmented inference
        visualize=False,  # visualize features
        update=False,  # update all models
        project=ROOT / 'runs/detect',  # save results to project/name
        name='exp',  # save results to project/name
        exist_ok=False,  # existing project/name ok, do not increment
        line_thickness=3,  # bounding box thickness (pixels)
        hide_labels=False,  # hide labels
        hide_conf=False,  # hide confidences
        half=False,  # use FP16 half-precision inference
        dnn=False,  # use OpenCV DNN for ONNX inference
        fast=True):
    # Load model
    source = str(source)
    device = select_device(device)
    model = DetectMultiBackend(weights, device=device, dnn=dnn)
    stride, names, pt, jit, onnx, engine = model.stride, model.names, model.pt, model.jit, model.onnx, model.engine
    imgsz = check_img_size(imgsz, s=stride)  # check image size
    # Half
    half &= (pt or engine) and device.type != 'cpu'  # half precision only supported by PyTorch on CUDA

    model.model.half() if half else model.model.float()

    cudnn.benchmark = True

    # Run inference
    model.warmup(imgsz=(1, 3, *imgsz), half=half)  # warmup

    if fast == False: #Slow inference,Low memory.
        cap = cv2.VideoCapture(0)
        while True:
            ret, im0 = cap.read()
            im = torch.from_numpy(im0).to(device)
            im = im.half() if half else im.float()  # uint8 to fp16/32
            im /= 255  # 0 - 255 to 0.0 - 1.0
            if len(im.shape) == 3:
                im = im[None]  # expand for batch dim
            t2 = time_sync()
            im = im.permute(0,3,1,2)
            pred = model(im, augment=augment, visualize=visualize)
            t3 = time_sync()
            # NMS
            pred = non_max_suppression(pred, conf_thres, iou_thres, classes, agnostic_nms, max_det=max_det)
            # Process predictions
            for i, det in enumerate(pred):
                if len(det):# per image
                    det[:, :4] = scale_coords(im.shape[2:], det[:, :4], im0.shape).round()
                    for b in range(len(det)):
                        x,y,w,h = det[:,:4][b]
                        x,y,w,h = int(x),int(y),int(w),int(h)
                        score = det[:,4][b]
                        cls = det[:,-1][b]
                        cls,score = int(cls),float(score)
                        cv2.rectangle(im0,(x,y),(w,h),(255,0,0),2)
                        cv2.putText(im0, str(cls),(w,y) , cv2.FONT_HERSHEY_SIMPLEX,
                                    1, (0,0,255), 2, cv2.LINE_AA)

            cv2.imshow("Window", im0)
            ch = cv2.waitKey(1)
            if ch == ord("q"):
                break

    if fast == True: #Fast inference,High memory.

        dataset = LoadStreams(source, img_size=imgsz, stride=stride, auto=pt and not jit)

        for path, im, im0s, vid_cap, s in dataset:
            im = torch.from_numpy(im).to(device)
            im = im.half()   # uint8 to fp16/32
            im /= 255  # 0 - 255 to 0.0 - 1.0
            if len(im.shape) == 3:
                im = im[None]  # expand for batch dim
            t2 = time_sync()
            pred = model(im, augment=augment, visualize=visualize)
            t3 = time_sync()
            # NMS
            pred = non_max_suppression(pred, conf_thres, iou_thres, classes, agnostic_nms, max_det=max_det)
            for i, det in enumerate(pred):
                im0 = im0s[i].copy()
                if len(det):# per image
                    det[:, :4] = scale_coords(im.shape[2:], det[:, :4], im0.shape).round()
                    for b in range(len(det)):
                        x,y,w,h = det[:,:4][b]
                        x,y,w,h = int(x),int(y),int(w),int(h)
                        score = det[:,4][b]
                        cls = det[:,-1][b]
                        cls,score = int(cls),float(score)
                        cv2.rectangle(im0,(x,y),(w,h),(255,0,0),2)
                        cv2.putText(im0, str(cls),(w,y) , cv2.FONT_HERSHEY_SIMPLEX,
                                    1, (0,0,255), 2, cv2.LINE_AA)

                        cv2.putText(im0, f"FPS:{1/(t3-t2):.0f}", (450, 60), cv2.FONT_HERSHEY_SIMPLEX,
                                    1, (255, 255, 255), 2, cv2.LINE_AA)

            cv2.imshow("Window", im0)
            ch = cv2.waitKey(1)
            if ch == ord("q"):
                break



def parse_opt():
    parser = argparse.ArgumentParser()
    parser.add_argument('--weights', nargs='+', type=str, default=ROOT / 'yolov5s.pt', help='model path(s)')
    parser.add_argument('--source', type=str, default=ROOT / 'data/images', help='file/dir/URL/glob, 0 for webcam')
    parser.add_argument('--imgsz', '--img', '--img-size', nargs='+', type=int, default=[640], help='inference size h,w')
    parser.add_argument('--conf-thres', type=float, default=0.25, help='confidence threshold')
    parser.add_argument('--iou-thres', type=float, default=0.45, help='NMS IoU threshold')
    parser.add_argument('--max-det', type=int, default=1000, help='maximum detections per image')
    parser.add_argument('--device', default='', help='cuda device, i.e. 0 or 0,1,2,3 or cpu')
    parser.add_argument('--view-img', action='store_true', help='show results')
    parser.add_argument('--save-txt', action='store_true', help='save results to *.txt')
    parser.add_argument('--save-conf', action='store_true', help='save confidences in --save-txt labels')
    parser.add_argument('--save-crop', action='store_true', help='save cropped prediction boxes')
    parser.add_argument('--nosave', action='store_true', help='do not save images/videos')
    parser.add_argument('--classes', nargs='+', type=int, help='filter by class: --classes 0, or --classes 0 2 3')
    parser.add_argument('--agnostic-nms', action='store_true', help='class-agnostic NMS')
    parser.add_argument('--augment', action='store_true', help='augmented inference')
    parser.add_argument('--visualize', action='store_true', help='visualize features')
    parser.add_argument('--update', action='store_true', help='update all models')
    parser.add_argument('--project', default=ROOT / 'runs/detect', help='save results to project/name')
    parser.add_argument('--name', default='exp', help='save results to project/name')
    parser.add_argument('--exist-ok', action='store_true', help='existing project/name ok, do not increment')
    parser.add_argument('--line-thickness', default=3, type=int, help='bounding box thickness (pixels)')
    parser.add_argument('--hide-labels', default=False, action='store_true', help='hide labels')
    parser.add_argument('--hide-conf', default=False, action='store_true', help='hide confidences')
    parser.add_argument('--half', action='store_true', help='use FP16 half-precision inference')
    parser.add_argument('--dnn', action='store_true', help='use OpenCV DNN for ONNX inference')
    opt = parser.parse_args()
    opt.imgsz *= 2 if len(opt.imgsz) == 1 else 1  # expand
    print_args(FILE.stem, opt)
    return opt


def main(opt):
    check_requirements(exclude=('tensorboard', 'thop'))
    run(**vars(opt))


if __name__ == "__main__":
    opt = parse_opt()
    main(opt)                             
```


In the run function,check out the last parameter called fast.If true it will infer with the LoadStreams method,if false it will run on regular opencv functions.Without LoadStreams I get half the fps.I also use fp16 precision.The code might need customization depending on your environment.

**Comment by pasmai** [comment]
@UygarUsta99 Can you make sure that the formatting of your code is correct? You need to use 3x \` to mark a block of code.

I will test it out later and let you know, thanks.

**Comment by UygarUsta99** [comment]
@pasmai I have updated my format,you are welcome.

**Comment by glenn-jocher** [comment]
@pasmai @UygarUsta99 yes LoadStreams is a multithreaded asynchronous dataloader. I made this myself for YOLOv5. It will load images into batches simultaneously while inference is happening.

**Comment by UygarUsta99** [comment]
@glenn-jocher I see,that makes sense.Can we use half precision inference after loading models with hub by calling model.half() ? Also thank you for your response.

**Comment by glenn-jocher** [comment]
@UygarUsta99 yeah sure you can cast models using .half() and .float(). You can also turn automatic mixed precision on or off, i.e. `model.amp = True`

**Comment by mohammad69h94** [comment]
> @pasmai 👋 Hello! Thanks for asking about **inference speed issues**. YOLOv5 🚀 can be run on CPU (i.e. `--device cpu`, slow) or GPU if available (i.e. `--device 0`, faster). You can determine your inference device by viewing the YOLOv5 console output:
> 
> ### detect.py inference
> ```shell
> python detect.py --weights yolov5s.pt --img 640 --conf 0.25 --source data/images/
> ```
> 
> <img alt="detect.py" width="944" src="https://user-images.githubusercontent.com/26833433/140100842-e130b5f7-64cb-46c9-9386-72abadd19828.png">
> 
> ### YOLOv5 PyTorch [Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) inference
> ```python
> import torch
> 
> # Model
> model = torch.hub.load('ultralytics/yolov5', 'yolov5s')
> 
> # Images
> dir = 'https://ultralytics.com/images/'
> imgs = [dir + f for f in ('zidane.jpg', 'bus.jpg')]  # batch of images
> 
> # Inference
> results = model(imgs)
> results.print()  # or .show(), .save()
> # Speed: 631.5ms pre-process, 19.2ms inference, 1.6ms NMS per image at shape (2, 3, 640, 640)
> ```
> 
> ### Increase Speeds
> If you would like to increase your inference speed some options are:
> 
> * Use batched inference with [YOLOv5 PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)
> * Reduce `--img-size`, i.e. 1280 -> 640 -> 320
> * Reduce model size, i.e. YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s -> YOLOv5n
> * Use half precision FP16 inference with `python detect.py --half` and `python val.py --half`
> * Use a faster GPUs, i.e.: P100 -> V100 -> A100
> * [Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) to ONNX for 2-3x CPU speedup with detect.py
> * Use a free GPU backends with up to 16GB of CUDA memory: [![Open In Colab](https://camo.githubusercontent.com/84f0493939e0c4de4e6dbe113251b4bfb5353e57134ffd9fcab6b8714514d4d1/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb) [![Open In Kaggle](https://camo.githubusercontent.com/a08ca511178e691ace596a95d334f73cf4ce06e83a5c4a5169b8bb68cac27bef/68747470733a2f2f6b6167676c652e636f6d2f7374617469632f696d616765732f6f70656e2d696e2d6b6167676c652e737667)](https://www.kaggle.com/models/ultralytics/yolov5)
> 
> Good luck 🍀 and let us know if you have any other questions!

Hi, thanks so much for your response.
You said: Export to ONNX for 2-3x CPU speedup with detect.py
It means has no effect on PyTorch Hub

**Comment by glenn-jocher** [comment]
@mohammad69h94 yes PyTorch Hub and detect.py use the same DetectMultiBackend() wrapper, so they may both benefit from ONNX export. 

Note this is CPU specific though. Some systems (AMD/M1) may not see much speedup, whereas other systems (Intel) may see up to 2-3x CPU speedup.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/yolov5s.onnx')
```

**Comment by pasmai** [comment]
@UygarUsta99 I have noticed that the detect.py script only measures the inference without and post-processing/parsing of the results. When taking the parsing into account in detect.py as well, the results are comparable.

<details><summary>Script Inference Backend</summary>

```py

# YOLOv5 🚀 by Ultralytics, GPL-3.0 license
"""
Run inference on images, videos, directories, streams, etc.

Usage:
    $ python path/to/detect.py --weights yolov5s.pt --source
                                                             img.jpg  # image
                                                             vid.mp4  # video
                                                             path/  # directory
                                                             path/*.jpg  # glob
                                                             'https://youtu.be/LNwODJXcvt4'  # YouTube
                                                             'rtsp://example.com/media.mp4'  # RTSP, RTMP, HTTP stream
"""

import argparse
import os
import sys
from pathlib import Path
import numpy as np
import pandas as pd

import cv2
import torch
import torch.backends.cudnn as cudnn

FILE = Path(__file__).resolve()
ROOT = FILE.parents[0]  # YOLOv5 root directory
if str(ROOT) not in sys.path:
    sys.path.append(str(ROOT))  # add ROOT to PATH
ROOT = Path(os.path.relpath(ROOT, Path.cwd()))  # relative

from models.common import DetectMultiBackend
from utils.augmentations import letterbox
from utils.datasets import IMG_FORMATS, VID_FORMATS, LoadImages, LoadStreams
from utils.general import (LOGGER, check_file, check_img_size, check_imshow, check_requirements, colorstr,
                           increment_path, non_max_suppression, print_args, scale_coords, strip_optimizer, xyxy2xywh)
from utils.plots import Annotator, colors, save_one_box
from utils.torch_utils import select_device, time_sync

def load_model(weights=ROOT / 'yolov5m.pt',  # model.pt path(s)
                device='',  # cuda device, i.e. 0 or 0,1,2,3 or cpu
                dnn=False,  # use OpenCV DNN for ONNX inference
                ): 
    # Load model
    device = select_device(device)
    model = DetectMultiBackend(weights, device=device, dnn=dnn)
    return model, device
    
@torch.no_grad()
def inference(
        model,  # YOLOv5 model
        image,  # input image
        device='',  # cuda device, i.e. 0 or 0,1,2,3 or cpu
        imgsz=[640, 640],  # inference size (pixels)
        conf_thres=0.25,  # confidence threshold
        iou_thres=0.45,  # NMS IOU threshold
        max_det=1000,  # maximum detections per image
        view_img=False,  # show results
        nosave=False,  # do not save images/videos
        classes=None,  # filter by class: --class 0, or --class 0 2 3
        agnostic_nms=False,  # class-agnostic NMS
        augment=False,  # augmented inference
        project=ROOT / 'runs/detect',  # save results to project/name
        name='exp',  # save results to project/name
        exist_ok=False,  # existing project/name ok, do not increment
        line_thickness=3,  # bounding box thickness (pixels)
        hide_labels=False,  # hide labels
        hide_conf=False,  # hide confidences
        half=False,  # use FP16 half-precision inference
        ):

    # Directories
    save_dir = increment_path(Path(project) / name, exist_ok=exist_ok)  # increment run
    save_dir.mkdir(parents=True, exist_ok=True)  # make dir

    # Load model
    stride, names, pt, jit, onnx, engine = model.stride, model.names, model.pt, model.jit, model.onnx, model.engine
    imgsz = check_img_size(imgsz, s=stride)  # check image size

    # Half
    half &= (pt or engine) and device.type != 'cpu'  # half precision only supported by PyTorch on CUDA
    if pt:
        model.model.half() if half else model.model.float()

    # Load image directly
    # img0: original, img: resized and padded
    img0 = image
    img = letterbox(img0, imgsz[0], stride=stride, auto=True)[0]      # Padded resize
    img = img.transpose((2, 0, 1))[::-1]  # BGR to RGB
    img = np.ascontiguousarray(img)

    # Run inference
    if pt and device.type != 'cpu': # warmup
        model(torch.zeros(1, 3, *imgsz).to(device).type_as(next(model.model.parameters())))  # TODO is warmup more efficient?
    dt, seen = [0.0, 0.0, 0.0], 1.0

    t1 = time_sync()
    im = torch.from_numpy(img).to(device)
    im = im.half() if half else im.float()  # uint8 to fp16/32
    im /= 255  # 0 - 255 to 0.0 - 1.0
    if len(im.shape) == 3:
        im = im[None]  # expand for batch dim
    t2 = time_sync()
    dt[0] += t2 - t1

    # DEBUG info
    print("Input Shape: ", np.shape(im))
    
    # Inference
    pred = model(im, augment=augment)
    t3 = time_sync()
    dt[1] += t3 - t2

    # NMS
    pred = non_max_suppression(pred, conf_thres, iou_thres, classes, agnostic_nms, max_det=max_det)
    dt[2] += time_sync() - t3

    # Second-stage classifier (optional)
    # pred = utils.general.apply_classifier(pred, classifier_model, im, im0s)

    # Process predictions
    det = pred[0]
    s = ""
    s += '%gx%g ' % im.shape[2:]  # print string
    if len(det):
        # Rescale boxes from img_size to im0 size
        det[:, :4] = scale_coords(im.shape[2:], det[:, :4], img0.shape).round()

        # Convert results to Dataframe
        data = det.cpu().data.numpy()
        df = pd.DataFrame(data, columns=['xmin', 'ymin', 'xmax', 'ymax', 'confidence', 'class'])
        df['class'] = df['class'].astype('int64')
        df.insert(0, "name", df["class"].map(lambda c: names[c]))

    # Print time (inference-only)
    LOGGER.info(f'{s}Done. ({t3 - t2:.3f}s)')

    # Stream results
    # im0 = annotator.result()

    # Print results
    t = tuple(x / seen * 1E3 for x in dt)  # speeds per image
    LOGGER.info(f'Speed: %.1fms pre-process, %.1fms inference, %.1fms NMS per image at shape {(1, 3, *imgsz)}' % t)
    return df

def parse_opt():
    parser = argparse.ArgumentParser()
    parser.add_argument('--weights', nargs='+', type=str, default=ROOT / 'yolov5s.pt', help='model path(s)')
    parser.add_argument('--source', type=str, default=ROOT / 'data/images', help='file/dir/URL/glob, 0 for webcam')
    parser.add_argument('--imgsz', '--img', '--img-size', nargs='+', type=int, default=[640], help='inference size h,w')
    parser.add_argument('--conf-thres', type=float, default=0.25, help='confidence threshold')
    parser.add_argument('--iou-thres', type=float, default=0.45, help='NMS IoU threshold')
    parser.add_argument('--max-det', type=int, default=1000, help='maximum detections per image')
    parser.add_argument('--device', default='', help='cuda device, i.e. 0 or 0,1,2,3 or cpu')
    parser.add_argument('--view-img', action='store_true', help='show results')
    parser.add_argument('--save-txt', action='store_true', help='save results to *.txt')
    parser.add_argument('--save-conf', action='store_true', help='save confidences in --save-txt labels')
    parser.add_argument('--save-crop', action='store_true', help='save cropped prediction boxes')
    parser.add_argument('--nosave', action='store_true', help='do not save images/videos')
    parser.add_argument('--classes', nargs='+', type=int, help='filter by class: --classes 0, or --classes 0 2 3')
    parser.add_argument('--agnostic-nms', action='store_true', help='class-agnostic NMS')
    parser.add_argument('--augment', action='store_true', help='augmented inference')
    parser.add_argument('--visualize', action='store_true', help='visualize features')
    parser.add_argument('--update', action='store_true', help='update all models')
    parser.add_argument('--project', default=ROOT / 'runs/detect', help='save results to project/name')
    parser.add_argument('--name', default='exp', help='save results to project/name')
    parser.add_argument('--exist-ok', action='store_true', help='existing project/name ok, do not increment')
    parser.add_argument('--line-thickness', default=3, type=int, help='bounding box thickness (pixels)')
    parser.add_argument('--hide-labels', default=False, action='store_true', help='hide labels')
    parser.add_argument('--hide-conf', default=False, action='store_true', help='hide confidences')
    parser.add_argument('--half', action='store_true', help='use FP16 half-precision inference')
    parser.add_argument('--dnn', action='store_true', help='use OpenCV DNN for ONNX inference')
    opt = parser.parse_args()
    opt.imgsz *= 2 if len(opt.imgsz) == 1 else 1  # expand
    print_args(FILE.stem, opt)
    return opt

def main(opt):
    check_requirements(exclude=('tensorboard', 'thop'))

    model, device = load_model(opt.weights, opt.device)
    image = cv2.imread(opt.source)
    inference(model=model, device=device, image=image, conf_thres=opt.conf_thres, iou_thres=opt.iou_thres, max_det=opt.max_det, view_img=opt.view_img, nosave=opt.nosave, classes=opt.classes, agnostic_nms=opt.agnostic_nms, augment=opt.augment,  project='runs/detect', name='exp', exist_ok=opt.exist_ok, line_thickness=opt.line_thickness, hide_labels=opt.hide_labels, hide_conf=opt.hide_conf, half=opt.half)

if __name__ == "__main__":
    opt = parse_opt()
    main(opt)

```
</details>


<details><summary>Script Test Performance</summary>

```py

import cv2
from pathlib import Path
import sys
import os
import time
import torch

import backend_yolo as backend



model, device = backend.load_model(weights='models/trained/yolov5m.pt')
image = cv2.imread('data/images/zidane.png')
model2 = torch.hub.load('ultralytics/yolov5',
                        'yolov5m',
                        force_reload=False, autoshape=True)

total = []

total.clear()
for i in range(11):
    start = time.time()
    model2(image)

    inference_time = time.time() - start
    total.append(inference_time)
    print("Total Inference time: {:3.0f} ms\n".format(inference_time * 1000))

total.clear()
print("Average using Hub: {:3.0f} ms\n".format(sum(total) / len(total)* 1000))
for i in range(11):
    start = time.time()
    df = backend.inference(
        model,
        device=device, 
        image=image, 
        imgsz=[640, 640],
        half=False)

    inference_time = time.time() - start
    total.append(inference_time)
    print("Total Inference time: {:3.0f} ms\n".format(inference_time * 1000))
print("Average using detect.py: {:3.0f} ms\n".format(sum(total) / len(total)*1000))
print(df)

```
</details>


```
$py perf_test.py

Average using Hub:  17 ms
Average using detect.py:  33 ms
```

**Comment by UygarUsta99** [comment]
@pasmai  Sorry for late response,thank you for your work and feedback.So this means loading models via hub we basically get a very similar inference speed.

**Comment by glenn-jocher** [comment]
@UygarUsta99 yes
