### ISSUE TITLE
add mask

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#5939]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

If I dont care the right part in the image and make a mask for it.
Making a mask to pass label it.
Is it a better way to train it?
original
![image](https://user-images.githubusercontent.com/59388989/145518193-451af0e8-58fe-4ce3-b69d-bdb4e8486899.png)

add the black mask
![image](https://user-images.githubusercontent.com/59388989/145518276-cb9643d8-9f8e-4ac8-8289-3e3129b4d6bc.png)

**Comment by Zengyf-CVer** [comment]
@alicera 
You can use the `cutout` data augmentation technique:
https://github.com/ultralytics/yolov5/blob/4fb6dd4b26a4d1c39a1e2565999be62f53fb7c71/utils/datasets.py#L612-L614

**Comment by glenn-jocher** [comment]
@alicera yes zeroing out those pixels will work fine!
