### ISSUE TITLE
Add Open Images Dataset V6 yaml to the data directory

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#5943]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

@glenn-jocher 
You can add the yaml of `Open Images Dataset V6 +` to [data](https://github.com/ultralytics/yolov5/tree/master/data).
https://storage.googleapis.com/openimages/web/index.html

![image](https://user-images.githubusercontent.com/41098760/145560143-cae3fd48-2bd4-4539-8764-3eadb34a4e31.png)

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Zengyf-CVer might make sense to create a placeholder YAML with the 600 class names. In terms of the download though OIv6 is a bit complicated. Do you think you could take the lead on this and create a PR with as much of the YAML populated as you can?

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
Because I recently searched some datasets about object detection and found that many are based on the sub-data sets extracted from the OIv6 dataset, so I got this idea. I can try to create this YAML file.

**Comment by glenn-jocher** [comment]
@Zengyf-CVer yes OIv6 is a great dataset, though it has problems in that not all images are labelled with all classes.
