### ISSUE TITLE
predict.py ??

### ISSUE THREAD

**Issue by synked16** [ultralytics/yolov5#595]
@glenn-jocher 
Hi, I have trained a custom detector on 4 classes for 100 epochs and now would like to inference on some new images... I noticed that there is no predict.py i.e. give the weights, the source of the test images and get the bbox output with scores, classes  etc with a ".txt" file as an output 

Is it possible??
(P.S. I am a noob in programming and find it hard to hack my way around with scripts like the others)

Thanks!!

**Comment by glenn-jocher** [comment]
@justAyaan see our colab notebook. It has examples for everything you need.

**Comment by justAyaan** [comment]
@glenn-jocher  actually I want to get an output ".txt" file or a pandas datafame will also do

**Comment by synked16** [comment]
ok got it!! we can add "--save-txt" in detect.py to get a '.txt' output, right?

**Comment by synked16** [comment]
and also @glenn-jocher if I have trained a model on 450x600 images, can I run inference on images with size 256x256??

**Comment by glenn-jocher** [comment]
@justAyaan you can run inference with any settings you want. You'll get the best results with settings similar to your training settings.
