### ISSUE TITLE
Video Stream (screen recording)

### ISSUE THREAD

**Issue by AndrewEstopinan** [ultralytics/yolov5#5951]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I am a little bit of a noob so I will keep this as simple as I can.

After creating and training a custom dataset I have run into many issues upon detecting from a video stream (a live screen recording). To me, it seems that Yolo was made for usage solely with video cameras and webcams and many people use it for this purpose however I have not seen anyone doing what I am trying to do (without taking screenshots). Either way, I would like to know if creating a video stream would be more ideal than actually just taking interval screenshots and applying code to that. And how someone would actually go about creating a stream of a desktop or application screen recording in HTTP or RTSP or RTMP and use it to generate a live output on yolo without using any 3rd party hardware.

**Comment by AndrewEstopinan** [comment]
RTSP*

**Comment by met5255** [comment]
Hello i made a small application which is the capture for the screen with the yolov5 pt file.


```
import numpy as np
import cv2
from mss import mss
from PIL import Image
import torch

# Screen capture
sct = mss()

# Model
model = torch.hub.load('ultralytics/yolov5', 'custom', path='last.pt')  # local custom model

while 1:
    #set the capture size
    w, h = 800, 640
    #set the capture position
    monitor = {'top': 0, 'left': 0, 'width': w, 'height': h}
    img = Image.frombytes('RGB', (w,h), sct.grab(monitor).rgb)
    screen = cv2.cvtColor(np.array(img), cv2.COLOR_RGB2BGR)
    #set the model use the screen 
    result = model(screen)
    result.display(render=True) 
    
    #show the result
    cv2.imshow('Screen', result.imgs[0])

    if cv2.waitKey(25) & 0xFF == ord('q'):
        cv2.destroyAllWindows()
        break
```


I hope this helps you.

![Képernyőfelvétel (119)](https://user-images.githubusercontent.com/34439208/145674877-5e517a2e-c1e9-4012-bc45-fd0be9059e05.png)
