### ISSUE TITLE
Detect Face and Generate ID for every face & take Screenshot using YoloV5

### ISSUE THREAD

**Issue by imsanjoykb** [ultralytics/yolov5#5957]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am doing face recognition Project using YoloV5. The Project have 3 parts.

1. Face Recognition [its already done]
2. Generate unique Face ID on detected face. [Not Done. Need Help/Suggestion]
3. Take Screenshot of every detected face. [Not Done. Need Help/Suggestion]

I have already tried. But I don't understand how to implement this 2 & 3 in YoloV5.

Any suggestion or help will be appreciated.

**Comment by glenn-jocher** [comment]
@imsanjoykb if the number of unique people is low, i.e. <100 people you could treat the faceID issue as a classification task run on the cropped faces. You can extract crops from YOLOv5 models like this:

### Cropped Results
Results can be returned and saved as detection crops:
```python
results = model(imgs)  # inference
crops = results.crop(save=True)  # cropped detections dictionary
```

See **PyTorch Hub** tutorial for details:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TFLite, ONNX, CoreML, TensorRT Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

Good luck 🍀 and let us know if you have any other questions!
