### ISSUE TITLE
Add `activation` field to model.yaml

### ISSUE THREAD

**Issue by shachargluska** [ultralytics/yolov5#5959]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Allow customizing the activation function used in the model via the config file.
For example, 
```
activation:
    leaky
```
This will change the activation in common.py to nn.LeakyReLU.

The current configurations are identical to:
```
activation:
    silu
```
Which is to use the SiLU activation function.

### Use case

Looks like many people are experimenting with different activation functions, as these have different forward/backward pass performance on different devices (GPUs, CPUs and other accelerators).
I think this will make it easier to support, without requiring a code change for each experiment.
It will also allow using older HSWISH/Leaky configurations with the current codebase - allowing for better backwards compatibility.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@shachargluska yes that might be a good idea!

See https://github.com/ultralytics/yolov5/issues/2891#issuecomment-826658992 for an example of changing activation function currently.

I'll add a TODO item here. If you can help by submitting a PR that might accelerate this feature request.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by shachargluska** [comment]
@glenn-jocher 
I've submitted a pull request:
https://github.com/ultralytics/yolov5/pull/5992

**Comment by glenn-jocher** [comment]
@shachargluska thanks I will take a look!
