### ISSUE TITLE
Convert inference result to array or image format

### ISSUE THREAD

**Issue by besmaguesmi** [ultralytics/yolov5#5962]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi
I would convert the output inference to image format (i.g, jpg, png..) or array
```
# Inference
result = model(image, size=640)  # includes NMS
```
Is it possible? Thanks

**Comment by glenn-jocher** [comment]
@besmaGuesmi `results.save()`, `results.render()`, `results.imgs`
