### ISSUE TITLE
NGC docker 

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#5963]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

```
FROM nvcr.io/nvidia/pytorch:21.10-py3
```
Do you know what is the pytorch:21.10-py3 compose of ？

For example , 
RUN apt install xxx
RUN make xxx

**Comment by iceisfun** [comment]
This is an nvidia official container and unrelated to yolov5 other than it simplifies getting setup for pytorch on nvidia hardware.

There are old Dockerfiles that do not use this if you look at old versions of the yolov5 repo.

**Comment by glenn-jocher** [comment]
@alicera yes see https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch

We were thinking of introducing a `ultralytics/yolov5:latest-cpu` container based on `ubuntu:latest`. This should allow for significantly reduced image sizes compared to the current for users only interested in CPU ops.

**Comment by alicera** [comment]
Thanks for your reply.
Where can I find the dockerfile content?

**Comment by alicera** [comment]
https://github.com/pytorch/pytorch/blob/master/docker/pytorch/ubuntu_cpu_gpu/Dockerfile
