### ISSUE TITLE
How to make input image as the first layer

### ISSUE THREAD

**Issue by phunix9** [ultralytics/yolov5#5965]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, thank you for your work and I have learned from it.

I have a question.  I need to get a new image B after several layers. For example, I construct a 10-layer network, and I get a new image B after 5th layer and get new features from B.  So I want to make the input image as the first layer and can deal with it directly.

However, I don't know how to do it. Can you help me or will you have some ohter methods to deal with the input image during the network?

**Comment by glenn-jocher** [comment]
@phunix9 are you saying that the yaml -1 input convention prevents you from accessing the input data directly at an arbitrary layer?

**Comment by phunix9** [comment]
Sorry for replying late.
Yes, you describe it more accually. My opinion is that layers actually deal with features after the first layer.  For example, layer 0 extracts feature from the input data and I also want to extract it from the input data in layer 1 (Maybe it is meaningless). However, I do not know how to modify the yaml or do some other changes.

**Comment by glenn-jocher** [comment]
@phunix9 you can access any layer from anywhere in the model in the model.yaml, that's the point of the first 'from' column.

https://github.com/ultralytics/yolov5/blob/e8ef8fb1ca34436577cf6d1f3933b0c30e19992c/models/yolov5s.yaml#L12-L48

**Comment by phunix9** [comment]
As you mentioned in yolov5s.yaml,  "-1" in Line 15 means P1 generates features from the input data.  I also want P2 to access the input data, but I don't know how to change the first 'from' column in Line 16.

**Comment by glenn-jocher** [comment]
@phunix9 haha yes I see what you mean. The 'from' values follow the python indexing convention, which means that the input is no longer accessible given the current structure. The original input is `x` here in the forward function. It is modified inplace as it moves through the model. You could copy it and handle it as you see fit here.

https://github.com/ultralytics/yolov5/blob/c9a46a60e09ab94009754ca71bde23e91aab33fe/models/yolo.py#L142-L153

**Comment by phunix9** [comment]
Thank you for your answer. I will have a try.
