### ISSUE TITLE
Retrieving trained YOLOv5 weights from WandB

### ISSUE THREAD

**Issue by aniruddh10124** [ultralytics/yolov5#5968]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

After training the weights on YOLOv5 and saving the results on WandB, how do I save and retrieve those weights from WandB for using the trained weights to detect images in the test set? I know that some change needs to be done in the argument of `!python detect.py --weight <argument>`, but what should I write in place of <argument<argument>>?
Just to be clear, I am able to retrieve the trained weights from Google Drive, but my teams requires the weights to be stored and retrieved from WandB to streamline our work, which I am not able to do.
Thank you for your time.

**Comment by glenn-jocher** [comment]
@aniruddh10124 thanks for your question! Our W&B expert @AyushExel should be able to help here.

**Comment by AyushExel** [comment]
@aniruddh10124 Hey, are you asking if you can directly pass artifact links to perform inference like you can to resume runs? 
`python detect.py --weights wandb-artifact://{artifact link}` ? This isn't supported currently. wandb is only supported in training tasks.

## How can you access the weights uploaded as W&B artifact?
Each artifact comes with an API. If you go to your dashboard where model is saved, you should see something like this:
![2021-12-14 15_43_22-yolov5-integration Artifacts – Weights   Biases](https://user-images.githubusercontent.com/15766192/146031327-0efec258-54e3-46dd-b0aa-8b1790ccd630.png)

You can copy and execute this api in your system and it'll download the weights. You can then use the the weights normally. Example:
`python detect.py --weight {path to downloaded model}`

Hope this helps :)

**Comment by aniruddh10124** [comment]
@AyushExel So, I guess what we are trying to do is not currently supported by WandB. Thank you for your clarification.

**Comment by AyushExel** [comment]
@glenn-jocher are there any plans to support passing weights links for inference as Anirudh is describing? Not just for artifacts but also things like s3 bucket, GCP etc. links

**Comment by glenn-jocher** [comment]
@AyushExel that's funny, that's probably the only argument that doesn't allow direct URL passing, because we already have the autodownload handling for the release assets. I tested it out just now and it seems to already be partially enabled, but the workflow has issues. I can take a look at it this week, I'll add a TODO.

**Comment by glenn-jocher** [comment]
TODO: URL --weights argument, i.e.:

```bash
python detect.py --weights https://ultralytics.com/assets/yolov5s6.pt
```
