### ISSUE TITLE
export.py .pt to INT8 .engine model

### ISSUE THREAD

**Issue by adventurousbanana** [ultralytics/yolov5#5969]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is there a way to export a PyTorch yolov5 model to a TensorRT engine model with INT8 quantization? 

I am able to export to FP32 just fine, but the --int8 flag doesn't seem to work.

Any help would be much appreciated.

**Comment by glenn-jocher** [comment]
@adventurousbanana not all export.py arguments apply to all formats. See argparser for details.

 https://github.com/ultralytics/yolov5/blob/e8ef8fb1ca34436577cf6d1f3933b0c30e19992c/export.py#L402-L431

**Comment by adventurousbanana** [comment]
Ok. I saw, but I was just making sure. Thanks.

**Comment by renowator** [comment]
I was looking for a way to get int8 weights in TensorRT and found this repo: https://github.com/maggiez0138/yolov5_quant_sample - will try converting and run from ultralytics/yolov5/detect.py and report back here

**Comment by glenn-jocher** [comment]
@renowator, please do let us know if that works for you. However, do keep in mind that using the code from external sources can be risky and can lead to compatibility issues with the latest release. So, I would highly recommend taking a look at the official YOLOv5 documentation on TensorRT support at https://docs.ultralytics.com/tensorrt/ and also checking out the `export.py` file present in the YOLOv5 GitHub repo for more information on how to export models. 

If you face any issues, feel free to ask for help on the YOLOv5 issues page or check out our documentation. We always appreciate the feedback and contributions from the YOLO community.
