### ISSUE TITLE
Error when resuming training after changing the training data

### ISSUE THREAD

**Issue by ifahim** [ultralytics/yolov5#597]
I  have trained yolov5 for 2,000 epochs on 1,000 images (custom data on single class problem). I can resume training without any error using the following command: 

`python train.py --img 1952 --batch 16  --epochs 2050  --data ./data/custom.yaml --cfg ./models/yolov5s_custom.yaml  --weights ./runs/exp15/weights/last.pt  --cache-images`

Now I want to use the  latest `last.weight` to train on 5,000  images. So, I change the train filename in the ./data/custom.yaml 
 as below and run exactly the same command as above but I keep getting the following error:

I only changed:
```
   train:  /home/users/data/train_tiny.txt

to 

train:  /home/users/data/train_small.txt
```

```
Traceback (most recent call last):
  File "train.py", line 469, in <module>
    train(hyp, tb_writer, opt, device)
  File "train.py", line 186, in train
    world_size=opt.world_size)
  File "/home/users/yolov5/utils/datasets.py", line 60, in create_dataloader
    pad=pad)
  File "/home/users/yolov5/utils/datasets.py", line 345, in __init__
    labels, shapes = zip(*[cache[x] for x in self.img_files])
TypeError: zip argument #1349 must support iteration
```

Does something else also needs to be change if the train_file if being changed?
Thanks

**Comment by glenn-jocher** [comment]
Your dataset has a problem.

**Comment by Polary-L** [comment]
> Your dataset has a problem.
I also got this error,can u talk in detail?
what's problem and how to fix?

**Comment by Polary-L** [comment]
I found the problem
maybe:
The labels' value after label normalization is > 1 or < 0
After the picture is transcoded under windows, read it on linux

**Comment by ifahim** [comment]
@glenn-jocher @Polary-L I verified and seemed like the data had issues.  Since I was running yolov5 on server, I re-copied all the images and labels files from local to server and the problem disappeared.

**Comment by glenn-jocher** [comment]
@ifahim right. If everything works, you change one thing, and it doesn't work, then you know the source of the problem.
