### ISSUE TITLE
How to choose approciate con_thres and iou_thres?

### ISSUE THREAD

**Issue by Audrey528** [ultralytics/yolov5#5970]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I trained my custom datasets without changing any parameters, now I wanna change something, like con_thres and iou_thres, but I am confused,I don't how to change.

**Comment by glenn-jocher** [comment]
@Audrey528 IoU threshold and Confidence threshold are inference parameters, i.e. `python detect.py --conf 0.1 --iou 0.6`

You can set these to whatever you want. See our iDetection app for an example of realtime change in parameters.

- Modify Confidence Threshold and NMS IoU Threshold in realtime user sliders and instantly see the effects:
<img src="https://user-images.githubusercontent.com/26833433/94313196-2953e380-ff33-11ea-9b0a-f2d597ff0cce.jpg" width="400">

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
By the way, when will the Android version of the APP be available?

**Comment by glenn-jocher** [comment]
@Zengyf-CVer in January!

**Comment by glenn-jocher** [comment]
@SergioSanchezUltralytics

**Comment by isJunCheng** [comment]
Should conf thres and IOU thres be set to 0.001 and 0.6 during model training and testing for better accuracy?

**Comment by isJunCheng** [comment]
I found that when the conf and IOU thresholds are set to 0.001 and 0.6, more training epochs are required to obtain better AP values

**Comment by glenn-jocher** [comment]
@isJunCheng mAP is only accurate when evaluate all the way down to near zero confidence. Ideal conf-threshold for mAP computation is 0.0, 0.001 is in place for speed.

**Comment by isJunCheng** [comment]
@glenn-jocher By the way, are you calculating the AP value in yolov5 in the same way as coco?
