### ISSUE TITLE
New weights and .yaml.

### ISSUE THREAD

**Issue by ZeKunZhang1998** [ultralytics/yolov5#598]
## ❔Question
Traceback (most recent call last):
  File "train1.py", line 210, in train
    ckpt['model'] = {k: v for k, v in ckpt['model'].float().state_dict().items()
  File "train1.py", line 211, in <dictcomp>
    if model.state_dict()[k].shape == v.shape and k in model.state_dict() }  # to FP32, filter
KeyError: 'model.18.conv.weight'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train1.py", line 481, in <module>
    train(hyp)
  File "train1.py", line 217, in train
    raise KeyError(s) from e
KeyError: "weights/yolov5x.pt is not compatible with yolov5xx_10.yaml. This may be due to model differences or weights/yolov5x.pt may be out of date. Please delete or update weights/yolov5x.pt and try again, or use --weights '' to train from scatch."

## Additional context

Can you give me the   link to the recent yolov5x.pt and yolov5x.yaml?Thanks.

**Comment by glenn-jocher** [comment]
Most recent weights are autodownloaded automatically on first use, provided you don't already have weights with the same name available locally. You can also find specific weights in the each release:
https://github.com/ultralytics/yolov5/releases/tag/v2.0

**Comment by ZeKunZhang1998** [comment]
> Most recent weights are autodownloaded automatically on first use, provided you don't already have weights with the same name available locally. You can also find specific weights in the each release:
> https://github.com/ultralytics/yolov5/releases/tag/v2.0

Thanks ,let me have a try >_<

**Comment by ZeKunZhang1998** [comment]
> Most recent weights are autodownloaded automatically on first use, provided you don't already have weights with the same name available locally. You can also find specific weights in the each release:
> https://github.com/ultralytics/yolov5/releases/tag/v2.0

Traceback (most recent call last):
  File "train.py", line 461, in <module>
    train(hyp, tb_writer, opt, device)
  File "train.py", line 75, in train
    model = Model(opt.cfg, nc=nc).to(device)
  File "/content/drive/My Drive/yolov5/models/yolo.py", line 70, in __init__
    m.stride = torch.tensor([s / x.shape[-2] for x in self.forward(torch.zeros(1, ch, s, s))])  # forward
  File "/content/drive/My Drive/yolov5/models/yolo.py", line 100, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/content/drive/My Drive/yolov5/models/yolo.py", line 120, in forward_once
    x = m(x)  # run
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/drive/My Drive/yolov5/models/yolo.py", line 27, in forward
    x[i] = self.m[i](x[i])  # conv
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 164, in __getitem__
    return self._modules[self._get_abs_string_index(idx)]
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 154, in _get_abs_string_index
    raise IndexError('index {} is out of range'.format(idx))
IndexError: index 0 is out of range

 

But is it something wrong with yaml?

**Comment by ZeKunZhang1998** [comment]
> > Most recent weights are autodownloaded automatically on first use, provided you don't already have weights with the same name available locally. You can also find specific weights in the each release:
> > https://github.com/ultralytics/yolov5/releases/tag/v2.0
> 
> Traceback (most recent call last):
> File "train.py", line 461, in 
> train(hyp, tb_writer, opt, device)
> File "train.py", line 75, in train
> model = Model(opt.cfg, nc=nc).to(device)
> File "/content/drive/My Drive/yolov5/models/yolo.py", line 70, in **init**
> m.stride = torch.tensor([s / x.shape[-2] for x in self.forward(torch.zeros(1, ch, s, s))]) # forward
> File "/content/drive/My Drive/yolov5/models/yolo.py", line 100, in forward
> return self.forward_once(x, profile) # single-scale inference, train
> File "/content/drive/My Drive/yolov5/models/yolo.py", line 120, in forward_once
> x = m(x) # run
> File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/content/drive/My Drive/yolov5/models/yolo.py", line 27, in forward
> x[i] = self.m[i](x%5Bi%5D) # conv
> File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 164, in **getitem**
> return self._modules[self._get_abs_string_index(idx)]
> File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 154, in _get_abs_string_index
> raise IndexError('index {} is out of range'.format(idx))
> IndexError: index 0 is out of range
> 
> But is it something wrong with yaml?

The new version have this problem.

**Comment by glenn-jocher** [comment]
@ZeKunZhang1998 thank you for your interest in our work! This issue seems to lack the minimum requirements for a proper response, or is insufficiently detailed for us to help you. Please note that most technical problems are due to:

- **Your changes to the default repository**. If your issue is not reproducible in a fresh `git clone` version of this repository we can not debug it. Before going further run this code and ensure your issue persists:
```bash
sudo rm -rf yolov5  # remove existing
git clone https://github.com/ultralytics/yolov5 && cd yolov5 # clone latest
python detect.py  # verify detection
python train.py  # verify training (a few batches only)
# CODE TO REPRODUCE YOUR ISSUE HERE
```
- **Your custom data.** If your issue is not reproducible with COCO data we can not debug it. Visit our [Custom Training Tutorial](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data) for guidelines on training your custom data. Examine `train_batch0.jpg` and `test_batch0.jpg` for a sanity check of training and testing data.
- **Your environment.** If your issue is not reproducible in our [Google Cloud](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) VM or Jupyter Notebook we can not debug it. Ensure you meet the requirements specified in the README: Unix, MacOS, or Windows with Python >= 3.7, PyTorch >= 1.5 etc. You can also use our [Jupyter Notebook](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb) <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> and our [Docker Image](https://hub.docker.com/r/ultralytics/yolov5) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker) to test your code in a working environment.

If none of these apply to you, we suggest you close this issue and raise a new one using the **Bug Report template**, providing screenshots and **minimum viable code to reproduce your issue**. Thank you!

**Comment by ZeKunZhang1998** [comment]
Thank you,I raise a new one.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ultralytics/yolov5"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月2日(星期天) 下午3:01
收件人:&nbsp;"ultralytics/yolov5"<yolov5@noreply.github.com&gt;;
抄送:&nbsp;"  "<836963662@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ultralytics/yolov5] New weights and .yaml. (#598)





 
@ZeKunZhang1998 thank you for your interest in our work! This issue seems to lack the minimum requirements for a proper response, or is insufficiently detailed for us to help you. Please note that most technical problems are due to:
  
Your changes to the default repository. If your issue is not reproducible in a fresh git clone version of this repository we can not debug it. Before going further run this code and ensure your issue persists:
  sudo rm -rf yolov5  # remove existing git clone https://github.com/ultralytics/yolov5 &amp;&amp; cd yolov5 # clone latest python detect.py  # verify detection python train.py  # verify training (a few batches only) # CODE TO REPRODUCE YOUR ISSUE HERE
  
Your custom data. If your issue is not reproducible with COCO data we can not debug it. Visit our Custom Training Tutorial for guidelines on training your custom data. Examine train_batch0.jpg and test_batch0.jpg for a sanity check of training and testing data.
 
Your environment. If your issue is not reproducible in our Google Cloud VM or Jupyter Notebook we can not debug it. Ensure you meet the requirements specified in the README: Unix, MacOS, or Windows with Python &gt;= 3.7, PyTorch &gt;= 1.5 etc. You can also use our Jupyter Notebook  and our Docker Image  to test your code in a working environment.
  
If none of these apply to you, we suggest you close this issue and raise a new one using the Bug Report template, providing screenshots and minimum viable code to reproduce your issue. Thank you!
