### ISSUE TITLE
How to set Loglevel (= silence) ?

### ISSUE THREAD

**Issue by ozett** [ultralytics/yolov5#5980]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

trying the pytorch code examples: https://github.com/ultralytics/yolov5/issues/36
but seems hard to find a way to complete silence the inference.
Everytime the rocket is shown. Would love to see some option-examples (on wiki/readme.md) to silence this.

as i am a n00b i would be glad about some easy hints to silence this
![image](https://user-images.githubusercontent.com/5937811/146020498-b19367b2-68b1-4611-97ff-0a7ddcf85a7a.png)

**Comment by ozett** [comment]
i found [hints on stackoverflow](https://stackoverflow.com/questions/38537905/set-logging-levels), but still the cache-message appears.
any hints to silence this too?

![image](https://user-images.githubusercontent.com/5937811/146022966-c6f1ed8a-814f-4779-b9d6-028a34cc24d1.png)

**Comment by glenn-jocher** [comment]
@ozett the 'Using cache found in' message is part of `torch` and not under our control. You might raise an issue on pytorch/pytorch

**Comment by ozett** [comment]
thanks for fast answer. great!

there is no python-way to silence submodles/touch-call? 😢

**Comment by ozett** [comment]
maybe declare the "hub.load" as a custom-model? to silence the cache-notification?

**Comment by ozett** [comment]
i needed that all for my python-script in node-red.
dirty-solution now running: i jump over this torch-message now with a split node. 
![image](https://user-images.githubusercontent.com/5937811/146672625-810cf99b-3c0a-41ac-a097-a34f9843f2d4.png)

thanks for helping on the first steps and silencing the yolo-messages.
