### ISSUE TITLE
How to run 24/7? 

### ISSUE THREAD

**Issue by Mehul343** [ultralytics/yolov5#5981]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Where can I run PyTorch Hub code for object detection 24/7?

**Comment by glenn-jocher** [comment]
@Mehul343 you can create an API, i.e. see https://ultralytics.com/yolov5

<img width="1479" alt="Screen Shot 2021-12-14 at 4 13 19 PM" src="https://user-images.githubusercontent.com/26833433/146025342-1d305cd5-cee4-4acb-a0b1-d090cdac4d13.png">

**Comment by alexandar-m** [comment]
Have a same question with no answer.
I'm testing YoloV5 for some time.
On mp4 FHD videos its all ok even if video is longer than 20 min.
With images tested more than a thousand but on streaming its a problem!

I was testing Yolov5 with OCR on 5-10 IP HD (2MP) cams changing from 1, 2, 4 to 8 FPS.... it runs for some time without problem, but eventually just stops or loops one frame from streams until I stop it even if that stream is ok.

After restart again, can work for few hour but never more a day.
PC is 1TB SSD 64 GB RAM with i9 and Nvidia 3070 TI
Network is 1 Gbps

Tried to change  datasets.py:

while cap.isOpened() and n < f:
to
while True and n < f:  

but no luck.

**Comment by glenn-jocher** [comment]
@alexandar-m that's pretty funny. The current implementations of everything in detect.py are meant as starting points for users to begin in their own development efforts, not as end solutions for commercial/industrial applications. 

I don't know what updates might be warranted to increase the robustness of the streamloader, but once you find out feel free to submit a PR to help future users in the same situation.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by Nisse123** [comment]
I don´t know what the underlying cause is.
Sometimes 
`success, im = cap.read()`
just hangs forever.
By experimenting as a workaround I just reopen the capture device in the loop. You have to test on which number to reinitialize . This is of course not a solution.
```
 def update(self, i, cap,s):
        # Read stream "i" frames in daemon thread
        n, f, read = 0, self.frames[i], 1  # frame number, frame array, inference every "read" frame
        while cap.isOpened() and n < f:
            n += 1```
            # _, self.imgs[index] = cap.read()
            if n % 2000 == 0:
                cap.release()
                s1 = pafy.new(s).getbest(preftype="mp4").url  # YouTube URL
                s1 = eval(s1) if s.isnumeric() else s1  # i.e. s = '0' local webcam
                cap = cv2.VideoCapture(s1)
                assert cap.isOpened(), f"Failed to open {s}"
                w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
                h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
               
            if n % read == 0:
                success, im = cap.read()
                #print(success)
                self.imgs[i] = im if success else self.imgs[i] * 0
            time.sleep(1 / self.fps[i])

**Comment by glenn-jocher** [comment]
@Nisse123 interesting. I would raise this issue in the cv2 repository, as it seems like the issue originates in cv2. Though they might just say the issue originates in the stream/network and there's nothing for them to do.

I think the real question is how would one build a robust streamloader that can handle dropouts, i.e. with exponential backoff and perhaps reconnection after a set time, taking care not to build up a buffer of images.

The streamloader adds additional constraints in that it must be multi-stream capable, i.e. if one stream fails the rest must still process in realtime, which I think it does already currently.

**Comment by alexandar-m** [comment]
Somehow by accident have deleted my own question long time a go and found your answer today. In meantime i have made and tested multicamera live solution for 24/7 stable long time run for YoloV5 and YoloV8 :)

> @alexandar-m that's pretty funny. The current implementations of everything in detect.py are meant as starting points for users to begin in their own development efforts, not as end solutions for commercial/industrial applications. 
> 
> I don't know what updates might be warranted to increase the robustness of the streamloader, but once you find out feel free to submit a PR to help future users in the same situation.
> 
> Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
>

**Comment by glenn-jocher** [comment]
Great to hear you've developed a multicamera solution! If you have improvements to share, consider submitting a pull request to benefit the community. Your contributions are always welcome.
