### ISSUE TITLE
When is the confusion matrix created?

### ISSUE THREAD

**Issue by hee100** [ultralytics/yolov5#5982]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Thank you for always giving me good answers.

I wonder if the sum of all epochs will result in a confusion matrix, or will it be created by the creation of last.pt from the last epoch.

**Comment by Zengyf-CVer** [comment]
@HeeHee100 
The easiest way is to look at the directory where the confusion matrix file is generated when performing training, and observe whether the confusion matrix file is updated in each period. Of course, you can also find program fragments related to the confusion matrix.

**Comment by glenn-jocher** [comment]
@HeeHee100 val.py creates a confusion matrix automatically when run directly or at the end of training.
