### ISSUE TITLE
TensorRT seems to slowing down the inference speed

### ISSUE THREAD

**Issue by davidan208** [ultralytics/yolov5#5984]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm running Yolov5 - v6.0 on Jetson Nano 4Gb.
When trying to inference a 1920x1080 video on **yolov5s.pt** and **yolov5s.engine** generated from the _export.py_ code.
The problem I'm having is that, using TensorRT seems to slowing down the inference speed comparing to using original path file and I don't know why or how to solve this problem.
One other thing is that, why using **yolov5s.pt** return class names like "horse" or "person" while yolov5s.engine only return "class 0", "class 17",... on the same _detect.py code_
Please help me!!!
Inference with **yolov5s.pt** :
![pt_1](https://user-images.githubusercontent.com/37769067/146106239-45d90d62-eefa-480a-b91e-069d2dbf49c5.png)

Inference with **yolov5s.engine**:
![enigne_2](https://user-images.githubusercontent.com/37769067/146106425-abb6eef6-a385-4f33-a884-a0d6f487e4bf.png)

Thank you for your help!!!

**Comment by glenn-jocher** [comment]
@davidan208 👋 Hello! Thanks for asking about YOLOv5 🚀 **TensorRT Export**. [NVIDIA TensorRT](https://developer.nvidia.com/tensorrt) format can accelerate inference by optimizing a `*.engine` model to a specific GPU and hardware backend.

## Install TensorRT

See our Notebooks Appendix section for examples: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

```bash
# https://developer.nvidia.com/nvidia-tensorrt-download
!lsb_release -a  # check system
%ls /usr/local | grep cuda  # check CUDA
!wget https://ultralytics.com/assets/TensorRT-8.2.0.6.Linux.x86_64-gnu.cuda-11.4.cudnn8.2.tar.gz  # download
![ -d /content/TensorRT-8.2.0.6/ ] || tar -C /content/ -zxf ./TensorRT-8.2.0.6.Linux.x86_64-gnu.cuda-11.4.cudnn8.2.tar.gz  # unzip
%pip list | grep tensorrt || pip install /content/TensorRT-8.2.0.6/python/tensorrt-8.2.0.6-cp37-none-linux_x86_64.whl  # install
%env LD_LIBRARY_PATH=/usr/local/cuda-11.1/lib64:/content/cuda-11.1/lib64:/content/TensorRT-8.2.0.6/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64  # add to path
```


## Export YOLOv5 TensorRT Model

Run `export.py --include engine` to export a TensorRT model

```bash
python export.py --weights yolov5s.pt --include engine --imgsz 640 640 --device 0
```

## Profiling Results

Below are profiling results by running `detect.py` with PyTorch CPU, PyTorch GPU, and TensorRT GPU. TensorRT inference speeds should be about 2-5x faster than PyTorch GPU inference.

<img width="1474" alt="Screenshot 2021-12-15 at 14 00 54" src="https://user-images.githubusercontent.com/26833433/146191722-86228a33-04a7-450f-9869-bd5c91baccaa.png">

Good luck 🍀 and let us know if you have any other questions!

**Comment by davidan208** [comment]
@glenn-jocher Thank you for your quick response.
I have tried these following command (same as what you gave me) but the results were no different from previous attempts (TensorRT still gave the higher inference time).
This is the link to my video (1920x1080): https://drive.google.com/file/d/1stEqgGOWqcBFJHmpkWR_-KzABg8k0HLJ/view?usp=sharing

I've exported the yolov5s.pt the same way as you did with `--device 0`
First I used:
`!python3 detect.py --weights yolov5s.pt --imgsz 640 640 --device 0 --source ./data/images/1080p.mp4`
and got the result:
![no_trt](https://user-images.githubusercontent.com/37769067/146292050-e663967d-a374-427d-9859-74c2f5d2c520.png)

Then I used:
`!python3 detect.py --weights yolov5s.engine --imgsz 640 640 --device 0 --source ./data/images/1080p.mp4`
and got the result:
![TRT](https://user-images.githubusercontent.com/37769067/146292108-b8945cde-0dee-4663-bc91-01f734ed8e81.png)

**ENVIRONMENT**
_Device_: Jetson Nano 4GB
_Memory card_: 128GB
_JetPack_: version 4.6
_Ubuntu_: version 18.04
_TensorRT_: version 8.0.1
_cuDNN_: version 8.2.1
_CUDA_: version 10.2

Please help me!!!!

**Comment by glenn-jocher** [comment]
@davidan208 I can't help you as we don't have Jetson Nano devices in house unfortunately, and moreso we are not the TRT authors. This would be NVIDIA. I would recommend you raise and issue or a question on the NVIDIA TensorRT repo/forum.

**Comment by davidan208** [comment]
@glenn-jocher Guess I should start using yolov5 on Google Colab then. Thanks for your advices. Maybe I'll try on other platforms and devices later.

**Comment by thuangb** [comment]
Hi @davidan208, did you export the file yolov5s.engine on jetson nano too or on a different machine ? TensorRT only work well when you generate the *.engine file on the **same** machine. Also I see that you use 384x640 resolution for yolov5s.pth but 640x640 for yolov5s.engine so try lower the resolution

**Comment by thuangb** [comment]
Also @glenn-jocher, I see that the tensorrt file only outputs id number not the name of the class, I think you should fix that

**Comment by davidan208** [comment]
@thuangb Hi, yes I did export yolov5s.engine on the same device (Jetson Nano). About the resolution, even when I changed `--imgsz 640 640` , the log from when inferencing with path file still gave the resolution of 384x640.

**Comment by thuangb** [comment]
> @thuangb Hi, yes I did export yolov5s.engine on the same device (Jetson Nano). About the resolution, even when I changed `--imgsz 640 640` , the log from when inferencing with path file still gave the resolution of 384x640.

Hm, so strange look like it is a bug @glenn-jocher ? Btw, @davidan208 you can try using --imgsz 384 640 for yolov5s.engine

**Comment by davidan208** [comment]
Hey @thuangb it really boost up the process. After export to a 384x640 imgsz engine file, now I get much faster inference speed, only 70ms on each frames. 640x640 might be the problem, I don't know. But it sure does work faster with 384x640. Thanks a lot !!!
