### ISSUE TITLE
Two questions about the model

### ISSUE THREAD

**Issue by hee100** [ultralytics/yolov5#5985]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

i see wiki article( Tips for Best Training Results )

1. It is stated that the P6 model produces better results when the image is larger. Does this mean an image with a large object size? Or are you talking about plain sized objects in large images?

2. When using pretrained weights, the " python train.py --data custom.yaml --weights yolov5s.pt"  code is used, but
When starting from scratch, the "python train.py --data custom.yaml --weights '' --cfg yolov5s.yaml" code is used.
So what happens when you write " python train.py --data custom.yaml --weights yolov5s.pt --cfg yolov5s.yaml " code?

**Comment by glenn-jocher** [comment]
@HeeHee100 

1. Results improve on COCO. Improvements will vary by dataset and training/inference settings like imgsz etc.
2. Model is created from yaml and any layers with matching names/shapes are transferred from pt.

**Comment by hee100** [comment]
thanks reply. but i don't understand second question.
If i enter that, `python train.py --data custom.yaml --weights yolov5s.pt --cfg yolov5s.yaml` 
You mean it's not transfer learning, it's making new?

**Comment by glenn-jocher** [comment]
@HeeHee100 from https://github.com/ultralytics/yolov5/issues/5985#issuecomment-994762198: model is created from yaml and any layers with matching names/shapes are transferred from pt.

You can call it whatever you want to call it.
