### ISSUE TITLE
Maximum and minimum image size

### ISSUE THREAD

**Issue by Juanjojr9** [ultralytics/yolov5#5987]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello!

I would like to know what are the maximum and minimum sizes that can be given to each model.
I have tried in the yolov5x6 model to give **--imgsz** from 384 to 3584 and in all the images it detects something when I run detect.py. I want to know the maximum and minimum image size I can train it with.

I'm a bit confused, so I'd like to know the image size I can train each model with and then run detect.py.

I hope you can help me.

Thank you! And forgive my lack of knowledge, I still have a long way to go.

JJ.

![image](https://user-images.githubusercontent.com/56088039/146163190-b73135d7-e506-448a-a143-0669a48df4aa.png)

![image](https://user-images.githubusercontent.com/56088039/146163335-e353479a-6dd3-4a2f-ae0a-1ddcaaaa3080.png)

### Additional

I'm doing my final project for graduation using yolov5, that's why I'm so interested in learning as much as I can.

Thank you!

**Comment by glenn-jocher** [comment]
@Juanjojr9 there is no maximum.

Minimum is 32 pixels for P5 models or 64 for P6.

**Comment by Juanjojr9** [comment]
Ok, perfect, thank you very much, you have solved a big doubt for me.
I will continue studying

Thank you very much!
