### ISSUE TITLE
Influence of image size and other data set for the hyperparameters evolution

### ISSUE THREAD

**Issue by DP1701** [ultralytics/yolov5#5990]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello all, 

I have three questions and I hope someone can help me answer them :)

1. if I set the image size to 1280 for the training (--img 1280), does the value apply to both the width and the height (1280 x 1280)?

2. if I start a hyperparameter evolution, do I have to take a different dataset for the full training or can I use the same one?

3) I see in the table that the pre-trained models were trained with a size of 640. Is it advisable to use the same value for training with my own dataset if I take a pre-trained model? Or can I change the value without any problems.

**Comment by glenn-jocher** [comment]
1. image size applies to long side
2. you can evolve any base scenario you want, for it to be relevant to your use case it should align with your use case
3. Official P5 models were trained at 640, Official P6 models at 1280. Any pretrained model can be used to start training at any image size.

**Comment by DP1701** [comment]
@glenn-jocher Thank you for the explanation!

I have one more question:

When I start the hyperparameter evolution, I get the following warning:

```
AutoAnchor: 0.01 anchors/target, 0.003 Best Possible Recall (BPR). Anchors are a poor fit to dataset ⚠️, attempting to improve...
```

If I start the training without the --evolve function, I don't get a warning.

```
4.19 anchors/target, 1.000 Best Possible Recall (BPR). Current anchors are a good fit to dataset ✅
```

Is it necessary to do something for the hyperparameter evolution? If so, is there a recommended procedure?

**Comment by glenn-jocher** [comment]
@DP1701 that's not a warning. Warnings say 'warning', just like errors say 'error'.

**Comment by DP1701** [comment]
@glenn-jocher Ahh okay, sorry. I saw the exclamation mark symbol and mistook it for a warning. 

Should I still make adjustments in this case? I only ask because the message does not occur in normal training.

**Comment by glenn-jocher** [comment]
@DP1701 evolution will evolve the number of anchors here. To evolve the number of anchors it must compute anchor values at each training. You can set this to 0 to not evolve anchors.

https://github.com/ultralytics/yolov5/blob/b8a4babd603d09f518581c589fc8607993a5e192/data/hyps/hyp.scratch.yaml#L20
