### ISSUE TITLE
How to use the voc evaluation index algorithm to calculate the APs of different scale targets？

### ISSUE THREAD

**Issue by 851942817** [ultralytics/yolov5#5997]
### Search before asking

- [ ] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi！
I tried to use -- save-json to see the model's APs for different scale targets, but it seems that VOC and COCO evaluation indicators are calculated differently, and when I use the two evaluation indicators, their mAP@.5 and mAP@.5-.9  are always  different. Since my improvements are aimed at iOU, and I need APs of different scales as my evaluation metrics. I could easily replace the iou function in the source code, but there was nothing I could do about pycocotools. If i customize the calculation of voc APs of different scales, how should i define it?

**Comment by Zengyf-CVer** [comment]
@851942817 
MS COCO uses 101-point interpolation, while VOC uses all-point interpolation, so there are some differences in the calculated results.

**Comment by glenn-jocher** [comment]
@851942817 APs at each of the 10 IoU levels are here:
https://github.com/ultralytics/yolov5/blob/628817dfae670302a69f83a7c44431877f90eb3f/val.py#L242-L243

**Comment by 851942817** [comment]
> @851942817位于 10 个 IoU 级别中的每个级别的 AP 在这里：
> 
> https://github.com/ultralytics/yolov5/blob/628817dfae670302a69f83a7c44431877f90eb3f/val.py#L242-L243

Thanks！
but I don't know how to replace the iou calculation method in pycocotools, so I'm going to rewrite a code that calculates {AP_s, AP_m, AP_l} based on the source code of yolov5, but if I define {Precision=TPs/(*)}, I don't know whether * is used {TP+FP} or {TPS+FPS}. S means filtering based on area.

I tried to change some codes

![image](https://user-images.githubusercontent.com/80572230/146467481-5f8518d9-b674-4c6e-b9fa-f76783cfc712.png)

Then I tried adding some other variables. Finally, write ap_for scale function in the utils/metrics .py

![image](https://user-images.githubusercontent.com/80572230/146467891-2553fb59-eaed-4efc-a525-b1511e2ac9d5.png)

**Comment by WANGCHAO1996** [comment]
> > @851942817位于 10 个 IoU 级别中的每个级别的 AP 在这里：
> > https://github.com/ultralytics/yolov5/blob/628817dfae670302a69f83a7c44431877f90eb3f/val.py#L242-L243
> 
> Thanks！ but I don't know how to replace the iou calculation method in pycocotools, so I'm going to rewrite a code that calculates {AP_s, AP_m, AP_l} based on the source code of yolov5, but if I define {Precision=TPs/(*)}, I don't know whether * is used {TP+FP} or {TPS+FPS}. S means filtering based on area.
> 
> I tried to change some codes
> 
> ![image](https://user-images.githubusercontent.com/80572230/146467481-5f8518d9-b674-4c6e-b9fa-f76783cfc712.png)
> 
> Then I tried adding some other variables. Finally, write ap_for scale function in the utils/metrics .py
> 
> ![image](https://user-images.githubusercontent.com/80572230/146467891-2553fb59-eaed-4efc-a525-b1511e2ac9d5.png)

How can I add APs APm APl index when training my data set?

**Comment by glenn-jocher** [comment]
@WANGCHAO1996 YOLOv5 mAP code is not broken down by size, but pycocotools does have 3 different size designations.
