### ISSUE TITLE
About CPU usage and process after training

### ISSUE THREAD

**Issue by mozeqiu** [ultralytics/yolov5#6002]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

After I started training, why did the CPU run at full load and the GPU run normally? And I checked that there were many Python processes. What's the matter?I pulled the latest code，Is this a normal phenomenon， Please
![1639636900(1)](https://user-images.githubusercontent.com/49837457/146321278-06acfb8a-3bb0-4e17-9f42-fe81d2136deb.jpg)
![1639636923(1)](https://user-images.githubusercontent.com/49837457/146321298-4f7443ec-4fee-46f6-8362-be9c2cd79c85.jpg)
![1639636949(1)](https://user-images.githubusercontent.com/49837457/146321313-ca3f2041-0b61-47f7-9db4-cdcb3cb6879e.jpg)

**Comment by glenn-jocher** [comment]
@mozeqiu YOLOv5 is designed to use up to 8 dataloader workers and maximize utilization of system resources for fastest training by default.

If you want slower training you can always specify less workers, i.e. `python train.py --workers 0`

**Comment by mozeqiu** [comment]
@glenn-jocher Thank you. I see
