### ISSUE TITLE
Cannot check actual batch size at wandb when using autobatch

### ISSUE THREAD

**Issue by Seyoung9304** [ultralytics/yolov5#6008]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi! :)

I found out that when we use autobatch with `--batch-size -1` option, `-1` is logged at wandb table. 

Is there a way to log the actual batch size used for learning in wandb?

![image](https://user-images.githubusercontent.com/50132040/146389895-4be4c0c1-3133-4179-93d3-427a32a5f807.png)

**Comment by glenn-jocher** [comment]
@AyushExel do you know if there's a way to update the batch size field in wandb after creation? Or could we delay the wandb logger creation until after AutoBatch is computed here? We can't move this up because it depends on imgsz, which in turn requires model to be defined to get the model stride.

https://github.com/ultralytics/yolov5/blob/c1249a47c7fe19e2067cb25ed8347e67d26ff1f1/train.py#L134-L141

**Comment by AyushExel** [comment]
@glenn-jocher yes we can update the batch size in in wandb after the run is created as well. It should be a simple one line fix but I'm away from my system this week :( . I can add this feature on monday

**Comment by glenn-jocher** [comment]
@AyushExel awesome, thanks for the fast response!

@Seyoung9304 we should be able to push a fix for this next week. Thank you for your patience!

**Comment by Seyoung9304** [comment]
@AyushExel @glenn-jocher Thank you so much for fast response! 👍 Have a nice day 😀

**Comment by glenn-jocher** [comment]
@Seyoung9304 good news 😃! Your original issue may now be fixed ✅ in PR #6039 by @AyushExel. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
