### ISSUE TITLE
The question about version iteration

### ISSUE THREAD

**Issue by sakurasakura1996** [ultralytics/yolov5#6014]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I have a question about the version iteration of yolov5. A year ago, I should have used yolov5 v3.0 or v3.1 to train my custom dataset, the result was 71.6% mAP@0.5 and 83% recall, but now, I train on the same dataset and the test result is 73.4 % mAP@0.5 and 66% recall, did the iou threshold or confidence score threshold change, which led to the adjustment of the accuracy rate and recall rate? Or is it another reason?

**Comment by glenn-jocher** [comment]
@sakurasakura1996 your mAP improved as it should have. See release notes for details: https://github.com/ultralytics/yolov5/releases

**Comment by sakurasakura1996** [comment]
@glenn-jocher thank you! But I still don’t know why the recall has dropped so much, can you provide some possible reasons, thank you

**Comment by glenn-jocher** [comment]
@sakurasakura1996 mAP is the only metric you should look at, as it is evaluated over all possible confidences 0-1. Recall is displayed at a single confidence value only, so it not a good representation of your results.

**Comment by sakurasakura1996** [comment]
@glenn-jocher ok，thank you very much！
