### ISSUE TITLE
Docker (nvcr.io/nvidia/pytorch:21.10-py), Error when "docker build ."

### ISSUE THREAD

**Issue by hanifizzudinrahman** [ultralytics/yolov5#6016]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

[+] Building 571.1s (5/16)
 => [ 1/11] FROM nvcr.io/nvidia/pytorch:21.10-py3@sha256:267948c348eed1604ca180612d6a6ceb7298e4b0ee5900e2aee5  563.0s 
 => => sha256:7a50c2cfea6bdb37dd2fcecf1b34f9b8b97f57735244717944dd12082de7cf77 1.33GB / 2.51GB                 563.0s 
 => => extracting sha256:312d920fedccedbb19babb2d7f5d3f438ecf789ce747924dd32a677a4cdb6b31                        0.0s 
 => => sha256:9c0ad29545c4be69846aaed4d570e67593e6b07258a1432416a297c83a8d23a3 43.72MB / 43.72MB               326.8s 
[+] Building 571.2s (5/16)
 => [ 1/11] FROM nvcr.io/nvidia/pytorch:21.10-py3@sha256:267948c348eed1604ca180612d6a6ceb7298e4b0ee5900e2aee5  563.1s 
 => => sha256:7a50c2cfea6bdb37dd2fcecf1b34f9b8b97f57735244717944dd12082de7cf77 1.33GB / 2.51GB                 563.1s 
 => => extracting sha256:312d920fedccedbb19babb2d7f5d3f438ecf789ce747924dd32a677a4cdb6b31                        0.0s 
 => => sha256:9c0ad29545c4be69846aaed4d570e67593e6b07258a1432416a297c83a8d23a3 43.72MB / 43.72MB               326.8s 
[+] Building 571.4s (5/16)
 => => sha256:7a50c2cfea6bdb37dd2fcecf1b34f9b8b97f57735244717944dd12082de7cf77 1.33GB / 2.51GB                 563.2s 
 => => sha256:10c826feeab7cc4f49d1967555f661350f55ef88732bc616680aa75b3ee4f1ae 132.12MB / 538.07MB             563.2s 
 => => sha256:57e6549ecb9d491f63316a5dbf6b47084fe3f894ac5f5192c7ce2d64c08131b4 180.36MB / 188.44MB             563.2s 
 => [internal] load build context                                                                                0.3s 
[+] Building 746.5s (6/16)
 => [internal] load build definition from Dockerfile                                                             0.2s 
 => => transferring dockerfile: 2.20kB                                                                           0.0s 
 => [internal] load .dockerignore                                                                                0.2s 
 => => transferring context: 3.73kB                                                                              0.0s 
 => [internal] load metadata for nvcr.io/nvidia/pytorch:21.10-py3                                                7.7s 
 => https://ultralytics.com/assets/Arial.ttf                                                                     0.0s 
 => ERROR [ 1/11] FROM nvcr.io/nvidia/pytorch:21.10-py3@sha256:267948c348eed1604ca180612d6a6ceb7298e4b0ee5900  738.4s 
 => => resolve nvcr.io/nvidia/pytorch:21.10-py3@sha256:267948c348eed1604ca180612d6a6ceb7298e4b0ee5900e2aee579ed  0.0s 
 => => sha256:030c24bd72baf811ff270ace6c1036a1ffaafc8eee6975172a440fedd206c44a 45.09kB / 45.09kB                 0.0s 
 => => sha256:ea495e85d1bfbb493986208d2f8a0c20e6d0dc3ca942d97d6abf37c48f16b960 11.88kB / 11.88kB                 0.0s 
 => => sha256:267948c348eed1604ca180612d6a6ceb7298e4b0ee5900e2aee579edebb19caf 745B / 745B                       0.0s 
 => => sha256:f3ef4ff62e0da0ef761ec1c8a578f3035bef51043e53ae1b13a20b3e03726d17 28.57MB / 28.57MB                22.5s 
 => => sha256:0a5a58fe9f80bdf8d873a90df8f25b0c45521493c683962ead7045416ed044e0 80.18MB / 80.18MB               121.3s 
 => => sha256:ffe911d7d638437aab9d53b4010ccf19c716c99b564b6422b44569118ed19e80 77.73MB / 77.73MB                28.9s 
 => => sha256:b6ca3d91503f31b907ea0f082f73942b6cf116b4a6ba79a767afeec6d3ff7929 19.14kB / 19.14kB                23.7s 
 => => sha256:2153f05ef7a84e6c9cba0a8bd645e729fa2f9410f9b8c5d783a404ca3352f640 2.76kB / 2.76kB                  24.8s 
 => => sha256:960ad9fc339d74f9c9d97da11fabef63bf91c8df2998fca9964e2e1e55db7dca 4.05kB / 4.05kB                  26.3s 
 => => extracting sha256:f3ef4ff62e0da0ef761ec1c8a578f3035bef51043e53ae1b13a20b3e03726d17                        5.1s 
 => => sha256:423cea99f7d205805222abffe128a11b14d90320c8000aa568bc6953e3cdb833 143B / 143B                      27.6s 
 => => sha256:ea4474a67b49659bf6a4c9f352d77216781a357cfc8dfcf1d5fd1410c6ca28f2 1.18kB / 1.18kB                  28.5s 
 => => sha256:b397fb86b3bce85b096c00152e4e199e553b7d298a78486895c8a71fe0094124 394B / 394B                      29.2s 
 => => sha256:927627363759dc4a4a799184cdd59b07c100f7e21b788be85cea7bf7a058fb33 425B / 425B                      29.7s 
 => => sha256:312d920fedccedbb19babb2d7f5d3f438ecf789ce747924dd32a677a4cdb6b31 1.45kB / 1.45kB                  29.9s 
 => => sha256:7a50c2cfea6bdb37dd2fcecf1b34f9b8b97f57735244717944dd12082de7cf77 1.63GB / 2.51GB                 738.4s 
 => => sha256:06daa3d0f46c9d3ed6a1b945ef5aad249863addcf91de2aa53f18854539b0367 11.55kB / 11.55kB                30.7s 
 => => sha256:aec116761f981c14c18ada8b6160151292b94d8ddc0bb86ca1136c259c6745e7 187B / 187B                      31.9s
 => => sha256:2812dcb9b1f104373396e0c59a745948dd050d078be82ad02728da77c97566ed 172.71kB / 172.71kB              33.2s 
 => => sha256:0b40e0143bfdfb31fe9de82db1ef5fb25679c469a8295135d77d06e2b06f861d 727B / 727B                      34.1s 
 => => sha256:0617ebfc4a217d4ee06e336355fd239799c49af5e9a07159a209c7a7467ffa27 5.02kB / 5.02kB                  35.8s 
 => => sha256:45a7802e347f9ad3c137aac9461230d03e52047014e6f92e47eca5919bea7df2 135.31kB / 135.31kB              37.2s 
 => => sha256:9c3aac051d0f30a409d076d6bdef9509f04c94c7f9ad584ddf6c204bb742a22c 40.74MB / 40.74MB                67.6s 
 => => sha256:c06cf176a9cac808240f4e20877a39fe67d8cb8520a028fc13b59db3bcf1b008 64.00MB / 64.00MB               122.3s 
 => => sha256:6790e5e29cc342d9c75f12826d8946299dadd5b42f7901e21c282de5c98eb5e5 508B / 508B                     124.4s 
 => => extracting sha256:0a5a58fe9f80bdf8d873a90df8f25b0c45521493c683962ead7045416ed044e0                        9.6s 
 => => sha256:896ac25d66a98c1ce0334eb7f27484bbdd19897c6e36b46c05cbe73c53462ec9 250.89MB / 250.89MB             294.5s
 => => sha256:7dfa990e7e1717368ecef9fb287025797169d78742743ac70be38bc7f8b5624d 45.20MB / 45.20MB               373.6s 
 => => extracting sha256:ffe911d7d638437aab9d53b4010ccf19c716c99b564b6422b44569118ed19e80                        9.9s 
 => => extracting sha256:b6ca3d91503f31b907ea0f082f73942b6cf116b4a6ba79a767afeec6d3ff7929                        0.2s 
 => => extracting sha256:2153f05ef7a84e6c9cba0a8bd645e729fa2f9410f9b8c5d783a404ca3352f640                        0.0s 
 => => extracting sha256:960ad9fc339d74f9c9d97da11fabef63bf91c8df2998fca9964e2e1e55db7dca                        0.0s 
 => => extracting sha256:423cea99f7d205805222abffe128a11b14d90320c8000aa568bc6953e3cdb833                        0.0s 
 => => extracting sha256:ea4474a67b49659bf6a4c9f352d77216781a357cfc8dfcf1d5fd1410c6ca28f2                        0.0s
 => => extracting sha256:b397fb86b3bce85b096c00152e4e199e553b7d298a78486895c8a71fe0094124                        0.0s 
 => => extracting sha256:927627363759dc4a4a799184cdd59b07c100f7e21b788be85cea7bf7a058fb33                        0.0s 
 => => extracting sha256:312d920fedccedbb19babb2d7f5d3f438ecf789ce747924dd32a677a4cdb6b31                        0.0s 
 => => sha256:9c0ad29545c4be69846aaed4d570e67593e6b07258a1432416a297c83a8d23a3 43.72MB / 43.72MB               326.8s 
 => => sha256:10c826feeab7cc4f49d1967555f661350f55ef88732bc616680aa75b3ee4f1ae 415.24MB / 538.07MB             738.4s 
 => => sha256:7586e32d819735346b24330326aaea584daad95fa89bb02d27e317b5e601365b 1.13MB / 1.13MB                 380.5s 
 => => sha256:4b15b5b33bf7fee3002ff6be283d3b2967665b82e229bc5944f4bc6c74c8f8a4 27.22kB / 27.22kB               382.3s 
 => => sha256:57e6549ecb9d491f63316a5dbf6b47084fe3f894ac5f5192c7ce2d64c08131b4 188.44MB / 188.44MB             574.8s 
 => => sha256:6ad6cc7591f45fd3e054ea646fa774a4e9b2c96b3c8335ae7915548a78c62dfb 12.49MB / 12.49MB               655.7s 
 => => sha256:42f060f227fbc1ae3d18e3e2ef8904c63a316555b72403566ea23b7a55eebd68 0B / 5.12MB                     738.4s 
 => [internal] load build context                                                                                0.3s 
 => => transferring context: 1.27MB                                                                              0.3s 
------
 > [ 1/11] FROM nvcr.io/nvidia/pytorch:21.10-py3@sha256:267948c348eed1604ca180612d6a6ceb7298e4b0ee5900e2aee579edebb19caf:
------
failed to copy: httpReadSeeker: failed open: failed to authorize: rpc error: code = Unknown desc = failed to fetch anonymous token: unexpected status: 401 Unauthorized

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@hanifizzudinrahman the YOLOv5 Dockerfile has no recent build issues:

<img width="1235" alt="Screen Shot 2021-12-17 at 3 07 29 PM" src="https://user-images.githubusercontent.com/26833433/146556534-dd1eb844-c78e-4701-91dc-5577551ea0dd.png">

- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>
