### ISSUE TITLE
Fail to Detect GPU - Windows - w/ Workaround

### ISSUE THREAD

**Issue by Vettejeep** [ultralytics/yolov5#6022]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training, Detection

### Bug

Fail to Detect GPU w/ workaround

On Windows 10 YOLOv5 will fail to detect the GPU. Adding a call to “select_device” in detect.py and train.py solves the issue, perhaps just as a workaround.

Call to "!python yolov5/detect.py --device gpu" fails in Jupyter. Calls to train.py fail for no GPU found. Resolved as follows:

Change in detect.py:

if __name__ == "__main__":
device = select_device('') # added this here
opt = parse_opt()
main(opt)

Change in train.py:

if __name__ == "__main__":
device = select_device('') # added this here
opt = parse_opt()
main(opt)

(this seems hacky, but works)

### Environment

Some system info:
Windows 10
Python 3.8.8
Torch: 1.10.0
torch.cuda.is_available() gives True
YOLOv5  v6.0-139-g8f35436

### Minimal Reproducible Example

Call to "!python yolov5/detect.py --device gpu" fails in Jupyter. Calls to train.py fail for no GPU found. 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Vettejeep thanks for the bug report! I noticed you are passing `--device gpu`, but the `--device` argument only accepts 'cpu', or a cuda device index, or comma separated list of indices, i.e.:

```bash
python detect.py --device cpu
python detect.py --device 0  # single-GPU
python train.py --device 0,1,2,3  # mutli-GPU
```

https://github.com/ultralytics/yolov5/blob/407a9057478d3deea0a9984af42162d21afa2bd2/train.py#L459

**Comment by Vettejeep** [comment]
@glenn-jocher I got the "--device= gpu" parameter from a copied Kaggle script. For me detect works with:
python detect.py --device
python detect.py --device gpu
python detect.py --device 0

All give the same result of finding the GPU with my work around.

**Comment by glenn-jocher** [comment]
@Vettejeep 'gpu' is clearly not a device option as the argument above explains. This is user error.

<img width="1578" alt="Screen Shot 2021-12-17 at 5 43 41 PM" src="https://user-images.githubusercontent.com/26833433/146578720-c20f9b60-e515-4056-b7e1-0138e0476f09.png">

**Comment by glenn-jocher** [comment]
Bug label removed.
