### ISSUE TITLE
Fcocal loss , QFocal loss

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#6026]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Do you have the suggest for gamma parameter number?
I set the focal loss param to 1.5, but dont get the better result.

**Comment by ZhaoCecil** [comment]
i have the same problem， do you have any ideas now?
