### ISSUE TITLE
super categories

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#6027]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

The coco have the super categories.
Do you have the idea to use super categories?
For example,  a bus image, it will not be recognized as other super categories. If the bus is be recognized as the class in super category "vehicle" is ok, like motorcycle, car, ...
https://tech.amikelive.com/node-718/what-object-categories-labels-are-in-coco-dataset/
![image](https://user-images.githubusercontent.com/59388989/146637677-8276a73b-2ef5-4e4e-83e4-d4cd3bfa494e.png)

**Comment by glenn-jocher** [comment]
@alicera we don't employ the super categories in YOLOv5.

**Comment by Camilochiang** [comment]
I was asking me about this today. you could have a look to a two models approach. For example [here](https://medium.com/analytics-vidhya/tackling-class-imbalance-for-object-classification-using-yolov5-with-a-2-model-approach-4b77f0ffe298)

@alicera if your question is answered is a good practice to close the issue ;)

**Comment by muru-raj10** [comment]
Could we implement super categories just for validation? i.e. val.py

**Comment by glenn-jocher** [comment]
@muru-raj10 hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
