### ISSUE TITLE
What does focus mean

### ISSUE THREAD

**Issue by isJunCheng** [ultralytics/yolov5#6028]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I would like to ask what is the original intention of putting forward focus, because I see that you have removed this module in the latest Yolov5 6.0.

**Comment by Zengyf-CVer** [comment]
@isJunCheng 
See:https://github.com/ultralytics/yolov5/issues/4825

**Comment by isJunCheng** [comment]
> @isJunCheng See:#4825

Thank you very much for your reply. Maybe I didn't see it because of my wrong search method
