### ISSUE TITLE
OpenCV problem detected by webcam

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#6029]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

@glenn-jocher 
I executed this command in Ubuntu, and an error occurred:
```shell
python detect.py --source 0
```
![ksnip_20211219-101631](https://user-images.githubusercontent.com/41098760/146661224-c9257c07-28b5-4baf-86a5-d2bee3364288.png)
So I referred to this [link](https://stackoverflow.com/questions/67120450/error-2unspecified-error-the-function-is-not-implemented-rebuild-the-libra/67210407#67210407), which is to change `opencv-python` uninstall, and then reinstall. I compared it, and the version before and after opencv-python has not changed.Then it can be used normally.

```shell
# Uninstall the original opencv-python
pip uninstall opencv-python
# Reinstall opencv-python
pip install opencv-python
```
I think the reason for this phenomenon should be the installation sequence of `opencv-python`, and the installation sequence of `opencv-python` should be adjusted appropriately.
https://github.com/ultralytics/yolov5/blob/abbdd4802ea1f01c9e8c723d3792e0e0a92d604e/requirements.txt#L6

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Zengyf-CVer requirements are mainly sorted alphabetically. pip should resolve dependencies on it's own, though I've found that this usually works better when all packages are installed in a single pip install command.
