### ISSUE TITLE
yolov5s weight

### ISSUE THREAD

**Issue by Stepnen** [ultralytics/yolov5#6030]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I'm a novice. I want to ask, if the backbone network structure of yolov5s is modified, the original weight can't be used or the effect is not good, what should I do now?

**Comment by glenn-jocher** [comment]
@Stepnen you can create your own --cfg *.yaml and try to pass any pretrained --weights you want. All layers with matching names and shapes will be transferred over to the new model:

```bash
python train.py --weights yolov5s.pt --cfg *.yaml
```

**Comment by Stepnen** [comment]
@glenn-jocher Hello, for example, I want to get yolov5s-ghost.pt (if you have any, can you share it with me?). At this time, I use yolov5s.pt to train yolov5s-ghost, but the effect will not be ideal. What should I do?

**Comment by glenn-jocher** [comment]
@Stepnen we don't have this pretrained model, but you can create it on your own by training 300 COCO epochs with it from scratch:

```
python train.py --data coco.yaml --weights '' --cfg yolov5s-ghost.yaml
```

**Comment by Stepnen** [comment]
I see. Thank you！
