### ISSUE TITLE
Thinking of non-vertical bounding box

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#6031]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

@glenn-jocher 
For this kind of data in the DOTA dataset, the orientation of the bounding box labeled is not vertical, but has a certain angle. The usual label format is x1y1x2y2, but the format of this data label is:
```
x 1, y 1, x 2, y 2, x 3, y 3, x 4, y 4, category, difficult
x 1, y 1, x 2, y 2, x 3, y 3, x 4, y 4, category, difficult
```

![image](https://user-images.githubusercontent.com/41098760/146672286-0a69891e-ee70-49af-9a83-5fa4ffd91cc5.png)

I would like to ask, does YOLOv5 currently have a method to detect data in this format?

**Comment by glenn-jocher** [comment]
@Zengyf-CVer YOLOv5 can accept segment labels, but at the moment these are mainly used for smarter label augmentation. The format for segmentation labels that are accepted is:

```
class x1 y2 x2 y2 x3 y3 ...
```

You can see an example of these labels in https://github.com/ultralytics/yolov5/releases/download/v1.0/coco128-segments.zip

Our 2022 roadmap includes segmentation models that should be able to do what you have above, though note that these are typically not segmentation models but rather box plus rotation models, i.e. xywh + rotation, where rotation could range from 0-1.

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
Do you think that for the detection of data like DOTA, it is better to use the image segmentation method or the bounding box plus rotation method?

**Comment by glenn-jocher** [comment]
@Zengyf-CVer well, box + rotation is only 5 dimensions, segmentation labels are a minimum of 8 dimensions for 4 points, so box + rotation should be simpler to estimate and produce better results. Though this is a narrow use case, segmentation extends to more points and is more common.

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
Thank you very much for your answers, I have benefited a lot.
