### ISSUE TITLE
one object get two class

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#6035]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Assume there are two class detection.
And one object is be detected with two bounding box.
How can I filter the one of two box?

**Comment by Lee-jaehyun** [comment]
Oh, I was also struggling with the same problem.

Anyone who solved it, please advise.

**Comment by RizwanMunawar** [comment]
> Assume there are two class detection.
> And one object is be detected with two bounding box.
> How can I filter the one of two box?

@alicera @Lee-jaehyun , if you have two classes for detection and you have trained model (yolov5/yolov4) on both classes. then at same position (coordinates (x,y,w,h)), only  that object will be detected, whose confidence score is higher. Multiple objects can not detected at same coordinates.

**Example:**
let suppose you have two classes **(person, head)**, and you trained yolov5 on these classes. so head and person will be detected when person comes. here you can easily filter boxes.
but when you have two same classes **(person1, person2),** and you trained yolov5 on these classes, so only that person will be detected whose confidence score is higher than other one.

**Comment by glenn-jocher** [comment]
@alicera you can also use agnostic NMS, which applies to NMS to all classes at the same time:
```
python detect.py --agnostic
```
