### ISSUE TITLE
Multi-label display

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#6036]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

@glenn-jocher 
How to realize multi-label display when running `detect.py`? I drew a picture, as shown:
![多标签检测](https://user-images.githubusercontent.com/41098760/146708757-4360ff6a-c82f-4254-83f3-670c2c541d1b.png)

**Comment by glenn-jocher** [comment]
@Zengyf-CVer ah, that's a good question. Right now we default multi-class detection to multiple boxes, so the labels are overlaid and hard to see. Not sure if there's a simple solution.

**Comment by abatiSon** [comment]
Actually if the tile location can be chosen randomly as one of the square corners. The probability of overlapping will also decrease.
