### ISSUE TITLE
 I'm curious about the criteria to get the best.pt out of several criteria.

### ISSUE THREAD

**Issue by Lee-jaehyun** [ultralytics/yolov5#6037]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am training with custom data using yolov5m model.

And every time an epoch is in progress, the training results are being saved in a csv file.

Also, the weights are stored as best.pt last.pt .

Here, I am wondering about the criteria for best.pt .

train/box_loss obj_loss cls_loss       mAP_0.5.         mAP_0.5:0.95         val/box_loss  obj_Loss  cls_loss

Which of these criteria determines the best.pt ?

### Additional

Help me plz.

**Comment by glenn-jocher** [comment]
@Lee-jaehyun best.pt is saved on every maximum fitness epoch. fitness is defined by a weighted combination of metrics, but it's mostly mAP@0.5:0.95:

https://github.com/ultralytics/yolov5/blob/26f0415287b7fa333f559a8300cedc2274943ab6/utils/metrics.py#L15-L19
