### ISSUE TITLE
--freeze option doen't work as expected

### ISSUE THREAD

**Issue by bilzard** [ultralytics/yolov5#6038]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

The change made in #6019 currently not working when I specified single integer.
When specified single integer value, the `freeze` value is created as a list of single integer: e.g. `[10]`. Therefore, the `train.py` code only freezes the 11th layer, remaining other former layers 0, .., 9 are ignored.

The expected behavior is:

```python train.py --freeze 10  # freeze up to 10```.

### Minimal Reproducible Example

```
python train.py --freeze 10
```

the output:
```
freezing model.10.conv.weight
freezing model.10.bn.weight
freezing model.10.bn.bias
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by bilzard** [comment]
I read the initial issue. 
https://github.com/ultralytics/yolov5/pull/6001#issuecomment-995846227

I think meeting both specifications 1, 2 is difficult:

```
specification. 1: python train.py --freeze 10  # freeze up to 10
specification. 2: python train.py --freeze 5 6 7 8 9 10  # freeze layers 5-10
```

Because when specifying single integer, the program can't distinguish the two cases: 1) freeze only layer 10 and 2) freeze layer from 0 to 9.

I think there are two solutions:

a) give up specification 1 or 2
b) separate option for specification 1 to 2. e.g: `--freeze-up-to 10` and `--freeze 0 1 2`

**Comment by bilzard** [comment]
Personally, I prefer keeping specification 1 and give up 2 because specification 1 is simple.
But I don't know if there are the cases when freezing only middle layers or latter layers.
Since specification 1 is just a syntax sugar, keeping spec 2 might be better.

**Comment by glenn-jocher** [comment]
@bilzard thanks for the bug report! I'm able to reproduce. Will push a fix.

**Comment by glenn-jocher** [comment]
@bilzard good news 😃! Your original issue may now be fixed ✅ in PR #6044. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by bilzard** [comment]
@glenn-jocher Thank you for the quick reply.
I checked the PR. It works most of the cases, but I think this solution is insufficient.

How do the user specify to freeze only one layer? See, layer 0 only?

**Comment by glenn-jocher** [comment]
@bilzard good question! Layer 0 freeze is not supported currently. I'll take a look and see if I can add support for this use case.

**Comment by glenn-jocher** [comment]
TODO: Layer 0 freeze
