### ISSUE TITLE
Batch predition in detect.py !!

### ISSUE THREAD

**Issue by yasersakkaf** [ultralytics/yolov5#604]
## 🚀 Feature
Need batch prediction implemented in detect.py

## Motivation

I see that in test.py you have implemented batch prediction since there is a flag called '--batch-size'. I need same feature in detect.py to perform inference in batch to increase my inference speed.

**Comment by glenn-jocher** [comment]
Great! Feel free to implement this and submit a PR.

**Comment by Ownmarc** [comment]
@yasersakkaf I implemented it in #668 feel free to test it and tell me if you would like it in an other way!

**Comment by yasersakkaf** [comment]
@Ownmarc  Thanks a lot !!
I will check it out.

**Comment by yasersakkaf** [comment]
@Ownmarc, how can I implement this with changes in detect.py itself?
I just want to pass another flag like --batch-size or something in detect.py
