### ISSUE TITLE
AttributeError: module 'wandb' has no attribute 'init' while trying to run sweep on yolov5 from cmd

### ISSUE THREAD

**Issue by itsfarooq94** [ultralytics/yolov5#6040]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

while trying to run the wandb sweep on yolov5 I'm facing this issue AttributeError: module 'wandb' has no attribute 'init'
commands that I am executing 
wandb sweep D:\Office-Farooq-Yolo\Farooq_yolov5\yolov5-master\utils\loggers\wandb\sweep.yaml --project yolov5_sweep
wandb agent farooq94/yolov5_sweep/nw5vxu6e
Screenshot is attached for reference 
![yolov5_Sweep_issue](https://user-images.githubusercontent.com/77834126/146762895-b6cb3ba2-fe13-48d2-9ebd-dd24b7147232.PNG)

### Environment

- yolov5
- Windows 10
- python Python 3.8.10

### Minimal Reproducible Example

sweep.py:

import sys
from pathlib import Path

import wandb

FILE = Path(__file__).resolve()
ROOT = FILE.parents[3]  # YOLOv5 root directory
if str(ROOT) not in sys.path:
    sys.path.append(str(ROOT))  # add ROOT to PATH

from train import parse_opt, train
from utils.callbacks import Callbacks
from utils.general import increment_path
from utils.torch_utils import select_device

def sweep():
    wandb.init()
    # Get hyp dict from sweep agent
    hyp_dict = vars(wandb.config).get("_items")

    # Workaround: get necessary opt args
    opt = parse_opt(known=True)
    opt.batch_size = hyp_dict.get("batch_size")
    opt.save_dir = str(increment_path(Path(opt.project) / opt.name, exist_ok=opt.exist_ok or opt.evolve))
    opt.epochs = hyp_dict.get("epochs")
    opt.nosave = True
    opt.data = hyp_dict.get("data")
    opt.weights = str(opt.weights)
    opt.cfg = str(opt.cfg)
    opt.data = str(opt.data)
    opt.hyp = str(opt.hyp)
    opt.project = str(opt.project)
    device = select_device(opt.device, batch_size=opt.batch_size)

    # train
    train(hyp_dict, opt, device, callbacks=Callbacks())

if __name__ == "__main__":
    sweep()

### Additional

I have check from the repo that I have the latest sweep.py but unable to figure out this issue. 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@itsfarooq94 do you have wandb installed?

**Comment by itsfarooq94** [comment]
@AyushExel yes Wandb is installed and logs are working in case of training.py

**Comment by AyushExel** [comment]
@itsfarooq94 Okay. Are you sure you're running the lastest version of the repository. `wandb.init` isn't on line 24 in the lastest version, it's on [line 18](https://github.com/ultralytics/yolov5/blob/master/utils/loggers/wandb/sweep.py#L18). But still that should not cause any problems. init should be found when wandb is installed. I'm taking a closer look now

**Comment by itsfarooq94** [comment]
@AyushExel Yes I have the updated sweep.py and line no. difference is due to some added comments.

**Comment by AyushExel** [comment]
@itsfarooq94 I'm not able to reproduce. Are you sure you're seeing wandb logs when running `python train.py` in your terminal

**Comment by itsfarooq94** [comment]
@AyushExel Yes I have setup the wandb docker image and while running the python train.py logs are logged on my local lost... you can the image below
![image](https://user-images.githubusercontent.com/77834126/146768804-4bd9f339-10f4-49f4-9656-60846d2d5c14.png)

**Comment by AyushExel** [comment]
@itsfarooq94 I just tried running it with the latest version and it works for me
<img width="1440" alt="Screenshot 2021-12-20 at 4 44 25 AM" src="https://user-images.githubusercontent.com/15766192/146769202-db3ba1fe-193e-4142-8840-4bbed3d8093b.png">

**Comment by AyushExel** [comment]
@itsfarooq94 it is recommended that you run your scripts from yolov5/ folder as the library uses some relative imports assuming the folder structure.
the commands should look like this:
`wandb sweep utils/loggers/..`

**Comment by itsfarooq94** [comment]
@AyushExel Ok... I'll try and update accordingly.
Thank you.

**Comment by itsfarooq94** [comment]
@AyushExel I have downloaded the latest repo and run the code as per you suggestion and now ModuleNotFoundError: No module named 'wandb' error is throwing... where as latest version of wandb 0.12.9 is already installed (Screenshot is attached below) 
Whereas same issue of AttributeError: module 'wandb' has no attribute 'init' persists if I run with previous repo
Note: I'm using the same virtual env for both the runs but having different issues is quite strange
Your help is highly appreciated
**Command:** wandb sweep utils/loggers/wandb/sweep.yaml --project yolov5_sweep

**Run with latest repo:**
![image](https://user-images.githubusercontent.com/77834126/146776367-290baa9c-d840-4af1-8a4e-78f18bd44d90.png)
**Run with previous repo:**
![image](https://user-images.githubusercontent.com/77834126/146776647-8919a7d7-93b5-467a-b068-60e359360858.png)
**Virtual Env installed lib's:**
![image](https://user-images.githubusercontent.com/77834126/146777024-b6ba88c7-18e2-4637-b5c8-49ad0abe954e.png)

**Comment by AyushExel** [comment]
Okay, that's strange. Are you running multiple versions of python? or Are you running it inside docker? I know there are some usual issues with windows dev envs but I'm not sure what's causing this. From the error message it seems that the script couldn't  find wandb on your system.

**Comment by itsfarooq94** [comment]
@AyushExel yes multiple pythons are installed on my system but I'm running this inside virtual env with python version 3.8 and it has wandb installed as well.
![image](https://user-images.githubusercontent.com/77834126/147110458-48c9360a-8f6c-4019-98a2-28dbd577ea1a.png)
![image](https://user-images.githubusercontent.com/77834126/147111332-17cdec91-9e6f-4691-9dd2-c166034913dc.png)

**Comment by AyushExel** [comment]
@itsfarooq94 Sorry I wasn't able to reproduce this. Have you tried running this on colab ? Do you see the same error there?

**Comment by vanpelt** [comment]
The most common cause of errors like this are a file named "wandb.py" or a folder named "wandb" that contains an "__init__.py".  You should be able to run the following to see what is actually be imported in your environment:

```
import wandb
print(wandb.__path__)
```

**Comment by AyushExel** [comment]
Thanks, Chris
@itsfarooq94 if you're still facing this issue, please check ^^

**Comment by taroyutao** [comment]
环境没问题，基本就是重名文件导致，基于报错找到对应的文件，更改文件名或者删除文件即可

**Comment by 6482985729** [comment]
I am also getting this error. I am using google colab for university work. I am mounting google drive and have files stored on google drive that the colab is importing and using as well.

I have this error and have no idea why. My wandb was working fine and all of a sudden stopped and throws this error.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-5-fb49c35d35ca>](https://localhost:8080/#) in <cell line: 121>()
    119 #               augmentation (aug) used or not, etc.
    120 
--> 121 train.train_model(model, train_loader, val_loader, optimizer, criterion,
    122                   IMG_CLASS_NAMES, NUM_EPOCHS, project_name="Assignment Task 1")

[/content/drive/MyDrive/...2023 release/train.py](https://localhost:8080/#) in train_model(model, train_loader, val_loader, optimizer, criterion, class_names, n_epochs, project_name, ident_str)
    164       ident_str = datetime.now().strftime("%Y%m%d_%H%M%S")
    165     exp_name = f"{model.__class__.__name__}_{ident_str}"
--> 166     run = wandb.init(project=project_name, name=exp_name)
    167 
    168     try:

AttributeError: module 'wandb' has no attribute 'init'

**Comment by glenn-jocher** [comment]
@KingPingg it seems that you are encountering an attribute error in your Colab environment while using Wandb with YOLOv5. This error message typically occurs when there is a file or folder named "wandb" that is conflicting with the "wandb" module.

To resolve this issue, I recommend checking your Colab environment for any files or folders named "wandb" or any other potential conflicts. Renaming or removing these files should help resolve the attribute error.

If you are unable to find any conflicting files or folders, please ensure that you have the latest version of Wandb installed. You can use the following command to upgrade Wandb:

```
!pip install --upgrade wandb
```

Additionally, make sure that you have imported the "wandb" module correctly in your Colab notebook. The correct import should be:

```
import wandb
```

I hope this helps you resolve the issue. Let me know if you have any further questions or concerns.
