### ISSUE TITLE
mixup label

### ISSUE THREAD

**Issue by hee100** [ultralytics/yolov5#6045]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I know that 0.8 is a puppy and 0.2 is a cat when performing Mixup in the cat classifier model (presuming r=0.2).
but  i don't see that in the mixup code of augmentations.py. Am I mistaken?

### Additional

``` python
def mixup(im, labels, im2, labels2):
    # Applies MixUp augmentation https://arxiv.org/pdf/1710.09412.pdf
    r = np.random.beta(32.0, 32.0)  # mixup ratio, alpha=beta=32.0
    im = (im * r + im2 * (1 - r)).astype(np.uint8)
    labels = np.concatenate((labels, labels2), 0)
    return im, labels
```

**Comment by Zengyf-CVer** [comment]
@HeeHee100 
See:https://github.com/ultralytics/yolov5/blob/dc54ed5763720ced4f6784552c47534af5413d45/utils/datasets.py#L562-L564

**Comment by hee100** [comment]
thanks reply. When executing mixup, objects are not mixed up.
The location of the bounding box is different, so it blends with the background. So, how does this label work?

**Comment by Zengyf-CVer** [comment]
@HeeHee100 
Label merge, this can refer to the original paper of Mixup.
