### ISSUE TITLE
train.py --img-size does not set the Model image size

### ISSUE THREAD

**Issue by davpapp** [ultralytics/yolov5#6046]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,
I'm training a YOLOv5 model using the YOLOv5s.pt weights. I'm using a MacBook Pro, so I can only use CPU, so performance is a concern.

I've trained two models on the same dataset. One with `--img 320` and one with `--img 640`. The 320 certainly trains faster.
Now, when I try to use this model for object detection in Java (using DJL), I found that in both cases, I need to pass in an image that is resized to 640x640. If I pass in a 320x320 image, I get an exception about input size mismatch between the input and the model. This is counterintuitive -- I would that expect that for the model trained with the `--img 320` argument, the input size should be 320x320. 

So I don't understand what's going on here. I tried looking for a .cfg file in the YOLOv5 repo that would fix this, but I couldn't find it. 
What am I doing wrong? How can I change the model input size to be 320x320? What exactly does passing in the `--img 320` argument to the training script do?

Thank you in advance!

**Comment by glenn-jocher** [comment]
@davpapp I don't understand your question. YOLOv5 PyTorch models can run inference at any size. There is no fixed size.

The `--img` argument tells train.py, val.py, detect.py what size images to pass the model.
