### ISSUE TITLE
No file after exporting to TensorRT

### ISSUE THREAD

**Issue by mfoglio** [ultralytics/yolov5#6047]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

When exporting to TensorRT I have no error but no file is generated. Since the script runs pretty fast, I believe the model is not being converted to TensorRT.

### Environment

Docker Container `nvcr.io/nvidia/deepstream:6.0-triton` (Ubuntu 20, Python 3.8, TensorRT 8).

### Minimal Reproducible Example

Start a container with Deepstream 6.0 which already has TensorRT 8 installed:
```
docker run   -t   -it   --rm   --runtime nvidia   -e DISPLAY=$DISPLAY   -v /tmp/.X11-unix/:/tmp/.X11-unix  --cap-add=SYS_PTRACE   --security-opt seccomp=unconfined   --device /dev/video0   --privileged --net=host nvcr.io/nvidia/deepstream:6.0-triton bash
```
Inside the container run:
```
mkdir -p /src/models/yolov5
apt update && apt -y install python3.8-venv

cd /src/models/yolov5
git clone https://github.com/ultralytics/yolov5.git
cd yolov5
git checkout v6.0

python3 -m venv venv --system-site-packages  # system packages allow to use TensorRT
source venv/bin/activate
pip install --upgrade pip
pip3 install -r /src/yolo_v5_requirements.txt. # Note: you will need to create this file, see below
wget https://github.com/ultralytics/yolov5/releases/download/v6.0/yolov5s.pt
python3 export.py --weights yolov5s.pt --img 640 --include engine
ls # no file
```
File `yolo_v5_requirements.txt` contains YoloV5 original requirements with torch compiled for cuda 11.3:
```
# pip install -r requirements.txt

# Base ----------------------------------------
matplotlib>=3.2.2
numpy>=1.18.5
opencv-python>=4.1.2
Pillow>=7.1.2
PyYAML>=5.3.1
requests>=2.23.0
scipy>=1.4.1
# torch>=1.7.0
# torchvision>=0.8.1
tqdm>=4.41.0

# Torch ---------
--find-links https://download.pytorch.org/whl/torch_stable.html
torch==1.10.1+cu113
--find-links https://download.pytorch.org/whl/torch_stable.html
torchvision==0.11.2+cu113

# Logging -------------------------------------
tensorboard>=2.4.1
# wandb

# Plotting ------------------------------------
pandas>=1.1.4
seaborn>=0.11.0

# Export --------------------------------------
# coremltools>=4.1  # CoreML export
# onnx>=1.9.0  # ONNX export
# onnx-simplifier>=0.3.6  # ONNX simplifier
# scikit-learn==0.19.2  # CoreML quantization
# tensorflow>=2.4.1  # TFLite export
# tensorflowjs>=3.9.0  # TF.js export

# Extras --------------------------------------
# albumentations>=1.0.3
# Cython  # for pycocotools https://github.com/cocodataset/cocoapi/issues/172
# pycocotools>=2.0  # COCO mAP
# roboflow
thop  # FLOPs computation
```
Output of the `export.py` script:
```
(venv) root@ip-x-x-x-x:/src/models/yolov5/yolov5# python3 export.py --weights yolov5s.pt --img 640 --include engine
Downloading https://ultralytics.com/assets/Arial.ttf to /root/.config/Ultralytics/Arial.ttf...
export: data=data/coco128.yaml, weights=yolov5s.pt, imgsz=[640], batch_size=1, device=cpu, half=False, inplace=False, train=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=13, topk_per_class=100, topk_all=100, iou_thres=0.45, conf_thres=0.25, include=['engine']
YOLOv5 🚀 v6.0-0-g956be8e torch 1.10.1+cu113 CPU

Fusing layers... 
/src/models/yolov5/yolov5/venv/lib/python3.8/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Model Summary: 213 layers, 7225885 parameters, 0 gradients

PyTorch: starting from yolov5s.pt (14.7 MB)

Export complete (0.33s)
Results saved to /src/models/yolov5/yolov5
Visualize with https://netron.app
```

### Additional

Note that the Docker image used above contains both `cuda 11.3` and `cuda 11.4`. I believe `cuda 11.4` is used by Deepstream while `cuda 11.3` is used by TensorRT.
From the container:
```
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.version.cuda
'11.3'
>>> torch.ones([2, 4], dtype=torch.float64, device="cuda")
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0', dtype=torch.float64)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@mfoglio your code is out of date. YOLOv5 🚀 v6.0-0-g956be8e does not support TensorRT export. Git pull or git clone again to use the latest code.

**Comment by mfoglio** [comment]
Hi @glenn-jocher , I tried to use the latest commit but I have the same issue. No file after exporting. However, I do have some errors (see TensorRT part):
```
 python3 export.py --weights yolov5s.pt --img 640 --include engine
Downloading https://ultralytics.com/assets/Arial.ttf to /root/.config/Ultralytics/Arial.ttf...
export: data=data/coco128.yaml, weights=['yolov5s.pt'], imgsz=[640], batch_size=1, device=cpu, half=False, inplace=False, train=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=14, verbose=False, workspace=4, nms=False, agnostic_nms=False, topk_per_class=100, topk_all=100, iou_thres=0.45, conf_thres=0.25, include=['engine']
YOLOv5 🚀 v6.0-155-gdc54ed5 torch 1.10.1+cu113 CPU

Fusing layers... 
Model Summary: 213 layers, 7225885 parameters, 0 gradients

PyTorch: starting from yolov5s.pt (14.7 MB)
requirements: onnx not found and is required by YOLOv5, attempting auto-update...
Collecting onnx
  Downloading onnx-1.10.2-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (12.7 MB)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from onnx) (1.14.0)
Requirement already satisfied: numpy>=1.16.6 in /usr/local/lib/python3.8/dist-packages (from onnx) (1.21.2)
Requirement already satisfied: typing-extensions>=3.6.2.1 in ./venv/lib/python3.8/site-packages (from onnx) (4.0.1)
Requirement already satisfied: protobuf in ./venv/lib/python3.8/site-packages (from onnx) (3.19.1)
Installing collected packages: onnx
Successfully installed onnx-1.10.2

requirements: 1 package updated per ['onnx']
requirements: ⚠️ Restart runtime or rerun command for updates to take effect


ONNX: starting export with onnx 1.10.2...
/src/models/yolov5/yolov5/models/yolo.py:57: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if self.onnx_dynamic or self.grid[i].shape[2:4] != x[i].shape[2:4]:
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
ONNX: export success, saved as yolov5s.onnx (29.3 MB)
ONNX: run --dynamic ONNX model inference with: 'python detect.py --weights yolov5s.onnx'

TensorRT: starting export with TensorRT 8.0.1.6...
[TensorRT] WARNING: Unable to determine GPU memory usage
[TensorRT] WARNING: Unable to determine GPU memory usage
[TensorRT] INFO: [MemUsageChange] Init CUDA: CPU +0, GPU +0, now: CPU 221, GPU 0 (MiB)
[TensorRT] INTERNAL ERROR: [runtime.cpp::isCudaInstalledCorrectly::38] Error Code 6: Internal Error (CUDA initialization failure with error 100. Please check your CUDA installation:  http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html)

TensorRT: export failure: pybind11::init(): factory function returned nullptr

Export complete (4.63s)
Results saved to /src/models/yolov5/yolov5
Visualize with https://netron.app
```

**Comment by mfoglio** [comment]
@glenn-jocher following suggestion here https://github.com/NVIDIA/TensorRT/issues/308#issuecomment-918027576 I found out that calling `torch.cuda.current_device()` in `export.py` would fix the issue. I am not sure why. Do you know more about this? Should I create a PR? The fix works, I am just not sure as to why but I could dive deeper if that's needed for a PR.

**Comment by pjkessel** [comment]
The default device used is the cpu. See line 432 in export.py:

![image](https://user-images.githubusercontent.com/96572649/147224405-12faa63a-5d2a-4251-a178-86a860581440.png)

Therefore, I call export.py by adding the device flag to use the GPU:
`python3 export.py --weights yolov5s.pt --img 640 --include engine --device 0`

However, this causes me to get the following error on export_onnx which is called inside export_engine:
![image](https://user-images.githubusercontent.com/96572649/147224858-50144153-c1c5-4cd7-b02a-f16128a08bd8.png)

A workaround for me was to first export an .onnx file and subsequently export the .engine file
`python3 export.py --weights yolov5s.pt --img 640 --include onnx`
`python3 export.py --weights yolov5s.pt --img 640 --include engine --device 0`

while commenting line 293 of export.py where the export_onnx method is called:
`opset = (12, 13)[trt.__version__[0] == '8']  # test on TensorRT 7.x and 8.x`
`#export_onnx(model, im, file, opset, train, False, simplify)`
`onnx = file.with_suffix('.onnx')`
`assert onnx.exists(), f'failed to export ONNX file: {onnx}'`

**Comment by glenn-jocher** [comment]
@mfoglio yes please submit a PR with your fix, thank you!


The TensorRT export example in our Colab notebook explicitly passes a CUDA device:
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

```python
# TensorRT Install
# https://developer.nvidia.com/nvidia-tensorrt-download
!lsb_release -a  # check system
%ls /usr/local | grep cuda  # check CUDA
!wget https://ultralytics.com/assets/TensorRT-8.2.0.6.Linux.x86_64-gnu.cuda-11.4.cudnn8.2.tar.gz  # download
![ -d /content/TensorRT-8.2.0.6/ ] || tar -C /content/ -zxf ./TensorRT-8.2.0.6.Linux.x86_64-gnu.cuda-11.4.cudnn8.2.tar.gz  # unzip
%pip list | grep tensorrt || pip install /content/TensorRT-8.2.0.6/python/tensorrt-8.2.0.6-cp37-none-linux_x86_64.whl  # install
%env LD_LIBRARY_PATH=/usr/local/cuda-11.1/lib64:/content/cuda-11.1/lib64:/content/TensorRT-8.2.0.6/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64  # add to path

# Export
!python export.py --weights yolov5s.pt --include engine --imgsz 640 640 --device 0

# Inference
!python detect.py --weights yolov5s.engine --imgsz 640 640 --device 0
```

**Comment by michalkrawczyk** [comment]
> The TensorRT export example in our Colab notebook explicitly passes a CUDA device: https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

Using that colab notebook ends with:

> Traceback (most recent call last):
>   File "export.py", line 506, in <module>
>     main(opt)
>   File "export.py", line 501, in main
>     run(**vars(opt))
>   File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
>     return func(*args, **kwargs)
>   File "export.py", line 407, in run
>     model = attempt_load(weights, map_location=device, inplace=True, fuse=True)  # load FP32 model
>   File "/content/yolov5/models/experimental.py", line 96, in attempt_load
>     ckpt = torch.load(attempt_download(w), map_location=map_location)  # load
>   File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 607, in load
>     return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
>   File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 882, in _load
>     result = unpickler.load()
>   File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 857, in persistent_load
>     load_tensor(data_type, size, key, _maybe_decode_ascii(location))
>   File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 846, in load_tensor
>     loaded_storages[key] = restore_location(storage, location)
>   File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 827, in restore_location
>     return default_restore_location(storage, str(map_location))
>   File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 175, in default_restore_location
>     result = fn(storage, location)
>   File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 157, in _cuda_deserialize
>     return obj.cuda(device)
>   File "/usr/local/lib/python3.7/dist-packages/torch/_utils.py", line 79, in _cuda
>     return new_type(self.size()).copy_(self, non_blocking)
>   File "/usr/local/lib/python3.7/dist-packages/torch/cuda/__init__.py", line 606, in _lazy_new
>     return super(_CudaBase, cls).__new__(cls, *args, **kwargs)
> RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
> CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

I wonder if that's not because of using TensorRT for CUDA 11.4 while collab seems to not having it:

> cuda@
> cuda-10.0/
> cuda-10.1/
> cuda-11@
> cuda-11.0/
> cuda-11.1/

**Comment by glenn-jocher** [comment]
@michalkrawczyk we have updated install instructions for Colab now:

```python
!pip install -U nvidia-tensorrt --index-url https://pypi.ngc.nvidia.com  # install
!python export.py --weights yolov5s.pt --include engine --imgsz 640 640 --device 0  # export
!python detect.py --weights yolov5s.engine --imgsz 640 640 --device 0  # inference
```
