### ISSUE TITLE
About the gradual increase of GPU memory！

### ISSUE THREAD

**Issue by stevenXS** [ultralytics/yolov5#6049]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

The code as a whole is pretty much the same, but over time the GPU memory will increase until OOM.

- I tried calling torch.no_grad(), but it didn't work. This problem can only be solved by explicitly calling torch.empty_memory().  why?

**Comment by Zengyf-CVer** [comment]
@stevenXS 
See:https://github.com/ultralytics/yolov5/blob/dc54ed5763720ced4f6784552c47534af5413d45/train.py#L437

**Comment by stevenXS** [comment]
@Zengyf-CVer  thank you!
