### ISSUE TITLE
Is it possible that the bounding box is out of image?

### ISSUE THREAD

**Issue by simba0703** [ultralytics/yolov5#6050]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is it possible that the bounding box is out of image?

**Comment by glenn-jocher** [comment]
@simba0703 detections are generally clipped to image bounds here on L631:

https://github.com/ultralytics/yolov5/blob/dc54ed5763720ced4f6784552c47534af5413d45/utils/general.py#L619-L633
