### ISSUE TITLE
Why yolov3 and Yolov5s detection speed is not much different？

### ISSUE THREAD

**Issue by liang-jingyi** [ultralytics/yolov5#6052]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

It is well known that yolov3 and Yolov5s model parameters differ greatly.Why is there no significant difference in detection speed？
My computer used yolov3 to detect each image in an average of 17.6ms. 
But yolov5s took an average of 13.8ms for each image.
The input size is 640*640.

One more problem, I noticed that the current version completes yolov5-bifpn.yaml, but I don't see a bifpn function in common.py. Class Concat is no different from the previous version. I want to know where bifPN is set.

 Please help me.Thank you.

**Comment by glenn-jocher** [comment]
@liang-jingyi speeds depend on a variety of factors. See https://github.com/ultralytics/yolov5#pretrained-checkpoints for profiling results.

**Comment by liang-jingyi** [comment]
@glenn-jocher
One more problem, I noticed that the current version completes yolov5-bifpn.yaml. 
But I don't see a bifpn function in common.py. 
Class Concat is no different from the previous version.
 I want to know where bifPN is set.

**Comment by glenn-jocher** [comment]
@liang-jingyi bifpn architecture is defined in the yaml itself.

**Comment by liang-jingyi** [comment]
@glenn-jocher
Thanks for noticing.
Actually,I want to know how bifPN can be realized in code

**Comment by glenn-jocher** [comment]
@liang-jingyi you can train a YOLOv5l BiFPN model simply with:

```
python train.py --weights yolov5l.pt --cfg yolov5-bifpn.yaml
```

You can adjust the scaling constants if you want smaller or larger models, i.e. n, s, m, l, x etc.
https://github.com/ultralytics/yolov5/blob/dc54ed5763720ced4f6784552c47534af5413d45/models/hub/yolov5-bifpn.yaml#L5-L6

**Comment by liang-jingyi** [comment]
@glenn-jocher
I know how to train this model.
 I want to know the bifPN underlying code, 
such as SPP, Bottleneck  code in common.py
Can you tell me where I can find bifpn.

**Comment by glenn-jocher** [comment]
@liang-jingyi I've already told you, the yaml contains the BiFPN head:
https://github.com/ultralytics/yolov5/blob/dc54ed5763720ced4f6784552c47534af5413d45/models/hub/yolov5-bifpn.yaml#L27-L48

**Comment by Zengyf-CVer** [comment]
@liang-jingyi 
BiFPN does not exist as a specific function in YOLOv5. Its essence is an architectural form. You can find biFPN papers or blogs on the Internet and study it carefully.
