### ISSUE TITLE
Feature map of specific layer -- or how to specify the layer needed

### ISSUE THREAD

**Issue by achel-x** [ultralytics/yolov5#6058]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I use '--visualize' to generate the feature map of all layer default. While I hope visualize the specific layer of the model as needed.
How to specify the output of a layer of the model like this

`model.features[idx].register_forward_hook(h)`

**Comment by Zengyf-CVer** [comment]
@achel-x 
See:
https://github.com/ultralytics/yolov5/blob/dc54ed5763720ced4f6784552c47534af5413d45/utils/plots.py#L128
https://github.com/ultralytics/yolov5/blob/dc54ed5763720ced4f6784552c47534af5413d45/models/yolo.py#L151-L152

**Comment by achel-x** [comment]
@Zengyf-CVer Thanks for your reply. I can saw the line of code. But I am confused about how to assign the value to the stage. 
Could you provide a example?
Meanwhile, I want to use the hook to other operations, do you know how to use the hook to call the specific layer. 
Thanks in advance.

**Comment by Zengyf-CVer** [comment]
@achel-x 
Change the value of `m.type`
https://github.com/ultralytics/yolov5/blob/dc54ed5763720ced4f6784552c47534af5413d45/models/yolo.py#L152

**Comment by achel-x** [comment]
@Zengyf-CVer It is abstract.
https://github.com/ultralytics/yolov5/blob/dc54ed5763720ced4f6784552c47534af5413d45/utils/plots.py#L124
m.type and m.i are both correlated to which layer of a stage to be visualize. I just don't know the exact usage about the 2 values. 
The type maybe is related to https://github.com/ultralytics/yolov5/blob/dc54ed5763720ced4f6784552c47534af5413d45/models/yolo.py#L259
Is the stage directly assigned to 1-28? I use the config file -- 'yolov3.yaml'.
Moreover, my point is about how to exactly specify one layer for the sake of the usage in hook, so I need to know the specific layer assignment. 
The retrieval of each layer is desired.

**Comment by Zengyf-CVer** [comment]
@achel-x 
Corresponding to each module in the yolov5 structure yaml, you can refer to: https://github.com/ultralytics/yolov5/blob/master/models/yolov5s.yaml
You can try to print out the value of `m.type`, or check the name of the visualization file in the generated directory.
If you still have doubts, you can consult the author: @glenn-jocher

**Comment by achel-x** [comment]
@Zengyf-CVer q anyway.

**Comment by achel-x** [comment]
@Zengyf-CVer Thanks anyway.
