### ISSUE TITLE
inf_out computation

### ISSUE THREAD

**Issue by hansoullee20** [ultralytics/yolov5#6059]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello
Where can I find how inf_out was calculated?
Thank you in advance for answering!

**Comment by glenn-jocher** [comment]
@hansoullee20 what's inf_out?
