### ISSUE TITLE
How to use ONNX inference without Torch libraries?

### ISSUE THREAD

**Issue by sarmientoj24** [ultralytics/yolov5#6061]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is there a way to use a converted YOLOv5 model (to ONNX) for inference/detection without the use of Pytorch library/ies?

I saw from the `detect.py` script that you are still using NMS which is doing some tensor operations (and other parts of the code) that does the inference/detection. These operations use Pytorch if my understanding is correct.

Is there a way to do inference independent from Pytorch dependencies?

**Comment by glenn-jocher** [comment]
@sarmientoj24 sure, you can build your own inference enviornment. detect.py is just an example.

**Comment by sarmientoj24** [comment]
do you know any example of it?

**Comment by glenn-jocher** [comment]
@sarmientoj24 ask here https://github.com/microsoft/onnxruntime
