### ISSUE TITLE
How to add some private information into .pt file?

### ISSUE THREAD

**Issue by Cong-Wan** [ultralytics/yolov5#6062]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

yolov5 is a great algorithm, but I'm having some problems. Specifically, I want to add some private information to the .pt file, can this be done?

**Comment by glenn-jocher** [comment]
@Cong-Wan sure. The YOLOv5 *.pt file is just a python dictionary. You can add whatever keys you want to the dictionary:
https://github.com/ultralytics/yolov5/blob/db6ec66a602a0b64a7db1711acd064eda5daf2b3/train.py#L376-L390

**Comment by Cong-Wan** [comment]
> @Cong-Wan sure. The YOLOv5 *.pt file is just a python dictionary. You can add whatever keys you want to the dictionary:
> 
> https://github.com/ultralytics/yolov5/blob/db6ec66a602a0b64a7db1711acd064eda5daf2b3/train.py#L376-L390

Thank you for your reply!I added a dictionary after the code you mentioned, but I used the parameters function to print the *.pt parameters without the content I added.Am I parsing in the wrong way?
My code like this:
 # Save model 
 if (not nosave) or (final_epoch and not evolve):  # if save 
     ckpt = {'epoch': epoch, 
             'best_fitness': best_fitness, 
             'model': deepcopy(de_parallel(model)).half(), 
             'ema': deepcopy(ema.ema).half(), 
             'updates': ema.updates, 
             'optimizer': optimizer.state_dict(), 
             'wandb_id': loggers.wandb.wandb_run.id if loggers.wandb else None, 
             'date': datetime.now().isoformat(),
             'version': '2021-12-23'} 
  
     # Save last, best and delete 
     torch.save(ckpt, last) 
     if best_fitness == fi: 
         torch.save(ckpt, best)

**Comment by glenn-jocher** [comment]
@Cong-Wan yes you can add any keys to the dictionary as you've shown.

**Comment by Cong-Wan** [comment]
> @Cong-Wan yes you can add any keys to the dictionary as you've shown.
But I printed the parameters inside *.pt without the content I added

**Comment by Cong-Wan** [comment]
> @Cong-Wan yes you can add any keys to the dictionary as you've shown.

Thank you for your help! This problem is done! Merry Christmas!!
