### ISSUE TITLE
similar class

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#6064]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

There are two class, one is face , another is head.
The center of two classes are close and the boxes are also similar.
Do you think it is good for design ?
 
![image](https://user-images.githubusercontent.com/59388989/147073150-4f1a41c6-1341-44f0-ac29-4c874d64bbfc.png)

**Comment by glenn-jocher** [comment]
@alicera yes sure! This should work fine :)
