### ISSUE TITLE
how to use with usb camera?

### ISSUE THREAD

**Issue by HoangBee102** [ultralytics/yolov5#6069]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to build an application that detects the use of an external camera, how can I do that?

### Additional

endoscope camera

**Comment by glenn-jocher** [comment]
@HoangBee102 just point to the local camera address, i.e. factory-installed webcam is typically `--device 0`, so a plug in camera may be `--device 1`

**Comment by Zengyf-CVer** [comment]
@HoangBee102 
You can try `--device 1` or `--device 2` until the program detects your camera.

**Comment by z2060986730** [comment]
should be --device 0

**Comment by HoangBee102** [comment]
External camera in android phone!

**Comment by SuperMaximus1984** [comment]
Same question for YoloV8.
HP 960 USB webcam, no matter how I tried, neither device or source works :(

**Comment by glenn-jocher** [comment]
@SuperMaximus1984 thank you for reaching out and showing interest in YOLOv5 and YOLOv8. Unfortunately, YOLOv5 and YOLOv8 do not natively support direct connection to USB webcams on Android devices.

However, you may be able to use an external camera app that supports USB webcams to capture video or images, and then pass those files to YOLOv5 or YOLOv8 for object detection. This can be achieved by using the `--source` argument in YOLOv5 or YOLOv8 and specifying the file path of the captured video or image.

Please note that the compatibility of external camera apps with YOLOv5 or YOLOv8 may vary depending on the specific hardware and software configurations of your Android device.

If you have any other questions or need further assistance, please feel free to ask.

**Comment by 98ShufangZheng** [comment]
Hello! I use Intel RealSense depth camera on my PC, but I couldn't read images from it when I change the number in the source.  Maybe I should look into the Intel website to look for ways to connect python to the depth camera?

**Comment by 98ShufangZheng** [comment]
> Hello! I use Intel RealSense depth camera on my PC, but I couldn't read images from it when I change the number in the source. Maybe I should look into the Intel website to look for ways to connect python to the depth camera?
________________________________________________________________________________________________________________________
I opened a new project and configured a new environment for YOLO, the RealSense depth camera started to work when I change source="0" to source="1". Thanks a lot ! @glenn-jocher

**Comment by glenn-jocher** [comment]
@98ShufangZheng i'm glad to hear you managed to get your Intel RealSense depth camera working with YOLO by adjusting the source parameter! It's great that you found a solution that works for your setup. If you encounter any more issues or have further questions as you continue your project, don't hesitate to reach out. Happy coding! 😊
