### ISSUE TITLE
Why different between torch.load and  torch.hub.load for yolov5s.pt? 

### ISSUE THREAD

**Issue by nemonameless** [ultralytics/yolov5#6075]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

```
import torch
a=torch.load('yolov5s.pt')['model'].state_dict()
a['model.0.conv.weight'].sum()

# tensor(-2.48242, dtype=torch.float16)
```
and 
```
import torch
a=torch.hub.load('ultralytics/yolov5', 'yolov5s').state_dict()
a['model.model.model.0.conv.weight'].sum()

# tensor(-53.17698, device='cuda:0')
```

Why different between these two ways?

**Comment by glenn-jocher** [comment]
@nemonameless YOLOv5 Hub models are automatically fused on load.
