### ISSUE TITLE
Tensorflow int8 quantization

### ISSUE THREAD

**Issue by beekeeper23** [ultralytics/yolov5#6076]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is it necessary to use the  "LoadImages"  class in order to create the dataset for quantization? or can I use a simple function as below, with the images from the training dataset?

 def representative_dataset():
    for _ in range(100):
      data = np.random.rand(1, 244, 244, 3)
      yield [data.astype(np.float32)]

**Comment by glenn-jocher** [comment]
@beekeeper23 that's creative! In real life your dataset will have a unique colorspace histogram set that I think the quantization is attempting to handle correctly/efficiently:

![image](https://user-images.githubusercontent.com/26833433/147243293-23b24db6-9fa6-486d-96bb-f98efe14658a.png)

**Comment by zldrobit** [comment]
@beekeeper23 No, it isn't necessary for tflite int8 quantization. You could write your own code for the quantization.
