### ISSUE TITLE
Time difference between a pytorch and the same model but in tensorflow lite

### ISSUE THREAD

**Issue by dariogonle** [ultralytics/yolov5#6078]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I've been working with YOLOv5 for a while, and know I decided to run a TFlite model. For my surprise, the inference time is about 324ms, while with the pytorch model the inference time is about 10.2ms.

Does anyone know why this could be happening?

TFLite model:
![image](https://user-images.githubusercontent.com/80393891/147240793-11a95d92-3fe7-46a1-b42f-b1da88c2bbdc.png)
![image](https://user-images.githubusercontent.com/80393891/147240030-94a1f86c-f866-45d3-a758-8d84cce7b8af.png)

Pytorch model:
![image](https://user-images.githubusercontent.com/80393891/147240749-2a9b403b-e055-440b-ab40-356998093905.png)
![image](https://user-images.githubusercontent.com/80393891/147240242-7a436150-954e-4850-adc3-f964a27007a1.png)

**Comment by glenn-jocher** [comment]
@dariogonle only PyTorch, ONNX, TorchScript and TensorRT YOLOv5 models run natively on GPU, all other formats run on CPU.

**Comment by dariogonle** [comment]
Thank you so much @glenn-jocher.

**Comment by glenn-jocher** [comment]
@dariogonle BTW TFLite INT8 models are also much slower on CPU than TFLite FP16 models, though on android the opposite holds true.

**Comment by dariogonle** [comment]
Thank you so much @glenn-jocher.

Therefore I run the yolov5n.pt model on a i7-9700K
```
python3 detect.py --weights yolov5n.pt --source ../../Datasets/images/ --img-size 704 --device cpu
```
And I get this time: Speed: 5.6ms pre-process, 32.3ms inference, 0.4ms NMS per image at shape (1, 3, 704, 704).

Now I export the yolov5n.pt model to tflite
```
python3 export.py --weights yolov5n.pt --img-size 704 --include tflite
```

And I run it:
```
python3 detect.py --weights yolov5n-fp16.tflite --source ../../Datasets/images/ --img-size 704
```
And I get: Speed: 0.3ms pre-process, 68.8ms inference, 3.6ms NMS per image at shape (1, 3, 704, 704).


Is it normal that the TFLite FP16 model is is twice as slow than the pytorch model, using in both cases the CPU? 

Thank you in advance.

Edit: Are you saying that TFLite 16 FP might be slower than pytorch on a CPU, but faster on a mobile device?

**Comment by glenn-jocher** [comment]
@dariogonle yes this is perfectly normal. TFLite formats are not intended to be used on CPU, we merely provide this support for convenience and for mAP evaluation with val.py. In real life these TFLite exported models should be sent to Android or Coral Edge TPU delegates, which is what they are optimized for.

If you are looking for CPU speedup I would recommend ONNX export.

**Comment by dariogonle** [comment]
Again, thank you so much @glenn-jocher.

**Comment by dariogonle** [comment]
The last question. I've seen that these TFLite models are 16 FP. Is possible to have 32 FP or INT8 model? In this case, how can i get them? I guess that for INT8 I should use the --int8 option.

**Comment by glenn-jocher** [comment]
@dariogonle `python export.py --include tflite --int8`

**Comment by dariogonle** [comment]
Thank you, but for FP32 how should we do it?

**Comment by glenn-jocher** [comment]
@dariogonle FP32 is not available off the shelf. You can customize export.py for this if you'd like, but we don't offer support for code customization.

**Comment by dariogonle** [comment]
Thank you. This is the last one for sure. 

Another interesting thing (at least for me) I figure out, is that with the pytorch model, letter box is being applied, but not for TFLite. Is this behaviour normal?

TFLite:
![image](https://user-images.githubusercontent.com/80393891/147246599-aa426f05-78cb-411b-8f16-cd0e09191bcd.png)

Pytorch:
![image](https://user-images.githubusercontent.com/80393891/147246658-07e41ad0-2a61-47d8-8ac9-1d293d294756.png)

**Comment by glenn-jocher** [comment]
@dariogonle TFLite models are exported at a fixed inference size. Detect.py and YOLOv5 Hub models will generally pad any input images to the size argument passed during inference. If you want to run inference with TFLite models at 416x704 then they must be exported at this exact --imgsz 416 704 and inferenced at this exact --imgsz 416 704

PyTorch models can run inference at any size.
