### ISSUE TITLE
If I remove all things related to ModelEMA, will the result change a lot? Will the ema improve the mAP?

### ISSUE THREAD

**Issue by clw5180** [ultralytics/yolov5#608]
Just as above.

**Comment by SISTMrL** [comment]
have you tried?

**Comment by glenn-jocher** [comment]
@clw5180 @SISTMrL EMA provides a model moving average based on an exponential decay constant. As training progresses, each model update contributes less and less to the EMA. You can see the result of removing EMA in this insightful YOLOv5 ablation study for the Kaggle Global Wheat Detection competition:
https://www.kaggle.com/c/global-wheat-detection/discussion/172436

I saw that torch 1.6 includes support for SWA, which is very similar to EMA and performs the same function. It would be interesting to compare the two. 
https://pytorch.org/blog/pytorch-1.6-now-includes-stochastic-weight-averaging/

**Comment by srqj** [comment]
the decay factor in EMA ~ `1 - exp(-updates/2000)`,  would approach 1 when `updates` is large, i.e., `epoch * nb`? does that mean the EMA weights will just stop being updated by the new iterations? Thanks!

**Comment by glenn-jocher** [comment]
@srqj that is not a correct interpretation. The decay factor is nominally 0.9999, the equation you show only applies to decay, not parameters, and ramps up decay from 0 to its steady state value as updates trends towards infinity. The full equation is:
https://github.com/ultralytics/yolov5/blob/5a9c5c1d3b02c8796e6af153d57af5821d8db0d6/utils/torch_utils.py#L213

**Comment by srqj** [comment]
> @srqj that is not a correct interpretation. The decay factor is nominally 0.9999, the equation you show only applies to decay, not parameters, and ramps up decay from 0 to its steady state value as updates trends towards infinity. The full equation is:
> https://github.com/ultralytics/yolov5/blob/5a9c5c1d3b02c8796e6af153d57af5821d8db0d6/utils/torch_utils.py#L213

Thanks for the prompt reply! I understand that the decay will be updated to ~1 after early epochs--if `x` in the equation is the total updates--but looking at the code below, I wonder when `d=1`, doesn't it mean that ema's parameter is always itself, instead of having the contribution from the model's parameter obtained from the new iterations (`msd`)? Thanks!

 https://github.com/ultralytics/yolov5/blob/5a9c5c1d3b02c8796e6af153d57af5821d8db0d6/utils/torch_utils.py#L223-L227

**Comment by srqj** [comment]
ah, I missed that there's 0.9999 as the upper limit, thanks for your answer!

**Comment by hujunchao** [comment]
Hi! When I set d =0, this make EMA ineffective. Then I found MAP for yolov5s drop 5.1%，from 36.7% to 31.6%. Can I do something wrong? I look forward to your suggestion! Thank you!
https://github.com/ultralytics/yolov5/blob/master/utils/torch_utils.py
![image](https://user-images.githubusercontent.com/22813297/110267689-4bca4c80-7ffb-11eb-85ca-5cf418f940b1.png)

**Comment by hujunchao** [comment]
@glenn-jocher

**Comment by glenn-jocher** [comment]
@hujunchao EMA tracks an exponential moving average of the model, producing better results than using the underlying model. If you modify it's parameters then yes you will get different results.

**Comment by hujunchao** [comment]
@glenn-jocher Thank you for quick reply！It is amazing for me that EMA for yolov5s can get 5% improvement about MAP in my test! Oh, my god! I can not believe it ! Can you test EMA for MAP improvement in COCO for yolov5s or other yolov5 model?
