### ISSUE TITLE
Tipps about adding keypoint regressor 

### ISSUE THREAD

**Issue by joihn** [ultralytics/yolov5#6081]
I want to add a keypoints regressor for an computer vision problem I have (always 1 keypoint per BBox).
I can do it depending on how doable it seems.

My approach would be the following: add a new refinement for keypoint, similar to BBox refinement already present.
![image](https://user-images.githubusercontent.com/11663917/147272736-1175450b-6f8f-49d3-89ab-bba4d3b2aef3.png)

**A) What do you think the end performance would be ?**
    - maybe not as good as keypoint estimation via MaskRCNN, because it doesn't look back at the image, but it still manage to do BBox refinement so it could do keypoint refinement too, right ? 
    
_Implementation steps:_
The stage I think are the following:
1) get the keypoint from the annotation file (easy)
2) modify image augmentation pipeline to take into account keypoint (easy)
4) compute the target Keypoint_x; Keypoint_y relative to anchor (unkown difficulty)
5) create a loss similar to BBox refinement  (unkown difficulty)
6) create a metrics similar to the one of [coco](https://cocodataset.org/#keypoints-eval)  (unkown difficulty, maybe I can reuse pycocotool ? )
7) upload the metric to wandb (unkown difficulty)

**B) How doable would it be to implement all this into YOLOv5 ?**

**Comment by glenn-jocher** [comment]
@joihn anything doable with enough time and funding.
