### ISSUE TITLE
Model and image size for detecting small objects

### ISSUE THREAD

**Issue by Zypherous123** [ultralytics/yolov5#6084]
### Search before asking

- [ ] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I want to train a model that's is used to detect relatively small and overlapping objects. What model and image size would you recommend to be used for training?

Would like to hear your recommendation.

Thanks

**Comment by fire717** [comment]
For small object you should try size 1280 with model yolov5?6 (? means n,s,m,l,etc.).
For overlapping objects, also you need big size, and you can try to tune the nms threshold.

**Comment by Zypherous123** [comment]
Thanks for the reply. Is using YOLOv5l6 with image 1280 be an optimal trade off in terms of speed to performance ratio?

**Comment by glenn-jocher** [comment]
@Zypherous123 yes it's a good place to start!
