### ISSUE TITLE
wandb bug after training

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#6086]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

@AyushExel 
I used the latest clone code. After the training, W&B had an image problem, as shown in the figure:
![ksnip_20211224-113620](https://user-images.githubusercontent.com/41098760/147313221-c2047333-7db5-418f-ad07-eec27fde3a94.png)

The program will automatically enter some commands in the shell, it may be a problem with the W&B script.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@Zengyf-CVer thanks for reporting! I think this might be unrelated to wandb as the it happens after the run is finished and all logs from wandb come with a blue colored `wandb:` prefix. But I'll try to reproduce and get back to you

**Comment by AyushExel** [comment]
@Zengyf-CVer it isn't reproducible. can you verify if this is reproducible on your end
<img width="1440" alt="Screenshot 2021-12-24 at 12 04 16 PM" src="https://user-images.githubusercontent.com/15766192/147325799-a2693ef9-8601-4ec4-b8aa-ca27d327f136.png">

**Comment by Zengyf-CVer** [comment]
@AyushExel 
I ran it again and there was no such problem. It may be a problem with my clipboard. Thank you so much.
