### ISSUE TITLE
inference time error？

### ISSUE THREAD

**Issue by coallar** [ultralytics/yolov5#6088]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi， everyone，In different resolutions（736x1280 and 368x640）, the inference time cost is the same， details could be found below:

![image](https://user-images.githubusercontent.com/66529823/147323440-727e0683-9db1-49e1-897b-60594c0d7374.png)

![image](https://user-images.githubusercontent.com/66529823/147323451-05a737eb-a8ff-42c5-a4ba-05cebd751b0a.png)

what wrong is it?

**Comment by Zengyf-CVer** [comment]
@coallar 
How much is your Batch Size set?

**Comment by coallar** [comment]
> @coallar How much is your Batch Size set?

bs=1 at default

**Comment by iceisfun** [comment]
As part of the preperation for forwarding the batch each image is resized and letterboxed.

```
def letterbox(self, img, new_shape=(640, 640)...
```

**Comment by coallar** [comment]
> As part of the preperation for forwarding the batch each image is resized and letterboxed.
> 
> ```
> def letterbox(self, img, new_shape=(640, 640)...
> ```

while, as we can find in the picture above, the image size in inference is difference, one is 736 x 1080, the other is 368 x 640,
inference time in mage size of 368 x 640 should be faster than 736 x 1080 one, but the result is the opposite

**Comment by Zengyf-CVer** [comment]
@coallar 
Can you send out the final output of these two screenshots? Because I need to judge your problem based on the final reasoning time, not the reasoning time for each picture.
