### ISSUE TITLE
Why does "m_" have "i, f, type, np" attributes?

### ISSUE THREAD

**Issue by nuaasxr** [ultralytics/yolov5#6090]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

In this line of code (m_.i, m_.f, m_.type, m_.np = i, f, t, np), why does m_ have i, f, type, np attributes?
This line of code is in the yolo.py 
Line 287 in the yolo.py file:
`m_.i, m_.f, m_.type, m_.np = i, f, t, np  # attach index, 'from' index, type, number params`

**Comment by glenn-jocher** [comment]
@nuaasxr as the comment says these are index, 'from' index, type, number params

**Comment by nuaasxr** [comment]
> @nuaasxr as the comment says these are index, 'from' index, type, number params
Thank you for your reply！
I know what you mean. What I want to know is where these attributes "i, f, type, np" come from? Are these attributes inherited from which class? I didn't see where yolov5 defined them.

**Comment by glenn-jocher** [comment]
@nuaasxr these attributes are defined here on YOLOv5 model creation:
https://github.com/ultralytics/yolov5/blob/db6ec66a602a0b64a7db1711acd064eda5daf2b3/models/yolo.py#L287

**Comment by nuaasxr** [comment]
> @nuaasxr these attributes are defined here on YOLOv5 model creation:
> 
> https://github.com/ultralytics/yolov5/blob/db6ec66a602a0b64a7db1711acd064eda5daf2b3/models/yolo.py#L287

Thank you, I get it. My Python foundation is too weak

**Comment by nuaasxr** [comment]
I love yolo!
