### ISSUE TITLE
Take input image with more than three channels.

### ISSUE THREAD

**Issue by Shankar203** [ultralytics/yolov5#6091]

**Comment by glenn-jocher** [comment]
@Shankar203 thanks for the feature request! You can create an arbitrary channel input count very simply by passing `nc=5` to a new yaml, i.e. `yolov5s_5ch.yaml`, and then passing it for the --cfg argument for training, but the current issue is that the train/val loaders are constrained to 3 channels. We should be adding support for arbitrary channel training and inference in early 2022.

```
python train.py --weights yolov5s.pt --cfg yolov5s_5ch.yaml
```

**Comment by Shankar203** [comment]
Hi @glenn-jocher  , 
And what about the dataset in which format I can store so that `train.py` can access it.
Presently I am having dataset of 5 .png images one for each channel.

As for validation I am using,
`model = torch.hub.load('ultralytics/yolov5', 'yolov5m') `

**Comment by marziyemahmoudifar** [comment]
> ## Question
> ### I want to finetune a pretrained yolov5l model over a dataset with 5-channels.
> #### As I want to use pretrained model I cant edit yolov5l.yaml file. So what I want to do is that add a 1x1 conv layer on top of the yolov5l accepting (1280,1280,5) and outputting (1280,1280,3), so that it can be passed into pretrained yolov5l.
> ### How can I achieve this?

You were able to use yolov5 for 5 channel input?

**Comment by DaddySuperJam** [comment]
> @Shankar203 thanks for the feature request! You can create an arbitrary channel input count very simply by passing `nc=5` to a new yaml, i.e. `yolov5s_5ch.yaml`, and then passing it for the --cfg argument for training, but the current issue is that the train/val loaders are constrained to 3 channels. We should be adding support for arbitrary channel training and inference in early 2022.
> 
> ```
> python train.py --weights yolov5s.pt --cfg yolov5s_5ch.yaml
> ```hello @glenn-jocher,'We should be adding support for arbitrary channel training and inference in early 2022.'  have you guys supported this character?

**Comment by glenn-jocher** [comment]
@DaddySuperJam To use YOLOv5 for 5-channel inputs, you can create a new yaml file, such as `yolov5s_5ch.yaml`, and set `nc: 5`, then use it for the `--cfg` argument during training.

As for your inquiry, support for arbitrary channel training and inference is currently under development and slated for release early in 2022. Thank you for your patience and understanding.
