### ISSUE TITLE
ImportError: cannot import name 'DetectMultiBackend' . 

### ISSUE THREAD

**Issue by manish33scss** [ultralytics/yolov5#6093]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Sounds very trivial, but yolov5 fails to import DetectMultiBackend, and yes I cross checked, its present in the common.py file. exactly here, "from models.common import DetectMultiBackend". 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@manish33scss your code or models may be out of date. To update your code (new models download automatically on first use):
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

**Comment by manish33scss** [comment]
> @manish33scss your code or models may be out of date. To update your code (new models download automatically on first use):
> 
> * **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
> * **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
> * **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  [![Open In Colab](https://camo.githubusercontent.com/84f0493939e0c4de4e6dbe113251b4bfb5353e57134ffd9fcab6b8714514d4d1/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb) [![Open In Kaggle](https://camo.githubusercontent.com/a08ca511178e691ace596a95d334f73cf4ce06e83a5c4a5169b8bb68cac27bef/68747470733a2f2f6b6167676c652e636f6d2f7374617469632f696d616765732f6f70656e2d696e2d6b6167676c652e737667)](https://www.kaggle.com/models/ultralytics/yolov5)
> * **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image [![Docker Pulls](https://camo.githubusercontent.com/280faedaf431e4c0c24fdb30ec00a66d627404e5c4c498210d3f014dd58c2c7e/68747470733a2f2f696d672e736869656c64732e696f2f646f636b65722f70756c6c732f756c7472616c79746963732f796f6c6f76353f6c6f676f3d646f636b6572)](https://hub.docker.com/r/ultralytics/yolov5)

No, I've just downloaded this, it's working fine with colab, but not in my pc, it says, can't import detectmultibackend. Thing is previous version was working fine, where we used attempt_load().

**Comment by GriffinBoris** [comment]
@manish33scss @glenn-jocher I ran into a similar issue. If your project directory contains your main script and a `models` directory/package in the same directory level it tends to clash with torch when loading models and code from torch hub.

---

### Failing Project Setup Example:

#### Project Structure:
```
project/
    main.py
    models/something.py
```

#### `main.py`
```
import torch
from PIL import Image
from models.something import Anything

if __name__ == '__main__':
	image = Image.open('car.jpg')
	model = torch.hub.load('ultralytics/yolov5', 'yolov5s')
	results = model(i)
	print(results.pandas().xyxy[0].to_dict('records'))
``` 

#### Result:
Produces `ModuleNotFoundError: No module named 'models.common'`

---

### Fixed Project Setup Example:
To fix this either rename the `models` directory/package or nest it in a directory.

### Working Project Setup Example #1:
Nesting the `models` package under `some_package_name`.

#### Project Structure:
```
project/
    main.py
    some_package_name/models/something.py
```

#### `main.py`
```
import torch
from PIL import Image
from some_package_name.models.something import Anything

if __name__ == '__main__':
	image = Image.open('car.jpg')
	model = torch.hub.load('ultralytics/yolov5', 'yolov5s')
	results = model(i)
	print(results.pandas().xyxy[0].to_dict('records'))
``` 

### Working Project Setup Example #2:
Renaming the `models` package to `things`.

#### Project Structure:
```
project/
    main.py
    things/something.py
```

#### `main.py`
```
import torch
from PIL import Image
from things.something import Anything

if __name__ == '__main__':
	image = Image.open('car.jpg')
	model = torch.hub.load('ultralytics/yolov5', 'yolov5s')
	results = model(i)
	print(results.pandas().xyxy[0].to_dict('records'))
``` 


---

Hope this helps!

**Comment by glenn-jocher** [comment]
@GriffinBoris yes these are good tips! The import order also matters, so it might (should?) be possible to create YOLOv5 models first from PyTorch Hub and then import local packages afterward.

**Comment by GriffinBoris** [comment]
Roger that! I will give that a try as well!

**Comment by Rijulsin** [comment]
> @GriffinBoris yes these are good tips! The import order also matters, so it might (should?) be possible to create YOLOv5 models first from PyTorch Hub and then import local packages afterward.

Hi Glenn, did this work for you?

**Comment by glenn-jocher** [comment]
@Rijulsin a PyTorch maintainer suggested this in a separate issue.
