### ISSUE TITLE
Yolov5m architecture

### ISSUE THREAD

**Issue by karl-gardner** [ultralytics/yolov5#6094]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello Glenn,

I see that you have said that the architecture is correct for this architecture: 

![image](https://user-images.githubusercontent.com/91646805/147367781-9201b063-9935-4631-91db-822a0c5d5aa7.png)

from the following issue: 

https://github.com/ultralytics/yolov5/issues/280

Is this correct for all the different types of yolov5 models: yolov5n, yolov5s, yolov5m, yolov5l ?  I used the yolov5m and am wondering if I can use the previous image to report the architecture of the yolov5m model?

Thanks,

Karl Gardner

**Comment by glenn-jocher** [comment]
@karl-gardner yes all YOLOv5 modes use the same architecture, simply the compound scaling constants very:
https://github.com/ultralytics/yolov5/blob/db6ec66a602a0b64a7db1711acd064eda5daf2b3/models/yolov5s.yaml#L5-L6

Also note that the above diagram is for a P5 model, i.e. YOLOv5s. P6 variants, i.e. YOLOv5s6 have 4 output layers for improved large object detection. The P5/P6 differences are explained in the v5.0 release notes:
https://github.com/ultralytics/yolov5/releases/tag/v5.0

**Comment by karl-gardner** [comment]
@glenn-jocher Thanks for the heads up.  So the P6 variants are used for higher resolution images.  Does this mean that the code automatically will use the P6 when images with higher resolution is used?  Since I trained all my models with a resolution of 544 x 544 then I just used the P5 with only 3 output layers right?

Karl Gardner

**Comment by glenn-jocher** [comment]
@karl-gardner if your images contains large objects then P6 will perform better. COCO is an example where P6 models outperform P5 models.

**Comment by karl-gardner** [comment]
@glenn-jocher ok thanks. I'm actually confused about something else now, should I start a different issue?  It seems like you can run both the yolov5-P5 and yolov5-P6 models with the detect.py:

<img width="638" alt="image" src="https://user-images.githubusercontent.com/91646805/147527112-602feca9-d0b2-47ee-bcfb-846cc9594662.png">

 but can you only train with just one of the models as the P6 model? I only see configuration files for the n/s/m/l/x models and not for both P5 and P6.

Karl Gardner

**Comment by glenn-jocher** [comment]
@karl-gardner see models/hub for all additional model yamls:
https://github.com/ultralytics/yolov5/tree/master/models/hub

**Comment by karl-gardner** [comment]
@glenn-jocher so the standard models in the yolov5/models directory:

<img width="665" alt="image" src="https://user-images.githubusercontent.com/91646805/147528688-4753d06d-9173-4988-9194-20823b7a2e13.png">

This is the P5 model with only 3 output layers?  The ones for larger objects (P6 with 4 output layers) are in the models/hub right?

Thanks,

Karl Gardner

**Comment by glenn-jocher** [comment]
@karl-gardner yes that's right!

**Comment by karl-gardner** [comment]
Great, I will close this issue and cite it when I am reporting the architecture.

Karl Gardner
