### ISSUE TITLE
About yolov5 prediction head

### ISSUE THREAD

**Issue by iscyy** [ultralytics/yolov5#6096]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, would you consider replacing the output head of yolov5 with a decoupling head like yolox? Is there currently such a way?

**Comment by glenn-jocher** [comment]
@Him-wen yes this could be done within the Detect layer by applying Conv or C3 modules per each of the 3 main outputs (box, conf, cls). We have not had time to experiment with this yet, but as with most things it would probably improve mAP at the cost of increased complexity/size and slower inference.

**Comment by iscyy** [comment]
thanks

**Comment by diangu001** [comment]
> thanks

hallo,boy. 请问您有将yolo的head替换成yolox的head吗？
