### ISSUE TITLE
关于wandb/wandbについて/issue about training with wandb

### ISSUE THREAD

**Issue by pengpengdesu** [ultralytics/yolov5#6102]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

在使用wandb的前提下，我每次训练到第29轮结束的时候都会报media  bounding  box debugger/images is invalid.please remove invalid filename characters的这个错误。但是不使用wandb后就不会报这个错误。我不想就此就不用wandb，请问大佬们有什么好的方法可以解决这个问题。
On the premise of using wandb, I will report error" media bounding box debugger / images is invalid.Please remove invalid filename characters."every time I finish the 29th round of training. However, this error will not be reported if wandb is not used. I dont want to remove wandb when taining. Can you help me?
wandbを使うと、”media bounding box debugger/images is invalid.please remove invalid filename characters”というエラーが出ます。 しかし、wandbを使用しない場合、このエラーは報告されません。 このような理由でwandbをやめたくないので、この問題を解決する良い方法があれば、皆さんにお聞きしたいのです。お願い！

**Comment by AyushExel** [comment]
@pengpengdesu hey this issue has been resolved. Please clone the latest version of the yolov5 repo from GitHub or pull `git pull` inside the yolov5/ directory

**Comment by pengpengdesu** [comment]
I got it.Thank you very very very much!!!!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ultralytics/yolov5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月26日(星期天) 晚上8:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ultralytics/yolov5] 关于wandb/wandbについて/issue about training with wandb (Issue #6102)





 
@pengpengdesu hey this issue has been resolved. Please clone the latest version of the yolov5 repo from GitHub or pull git pull inside the yolov5/ directory
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AyushExel** [comment]
@pengpengdesu thanks! feel free to close this issue
