### ISSUE TITLE
When I clone yolov5 the following error is showing. And I have no idea why. Previously it was showing no module found for utils.general but now it is showing this:

### ISSUE THREAD

**Issue by debya01** [ultralytics/yolov5#6104]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Other

### Bug

ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_21592/289034434.py in <module>
      1 import torch
----> 2 from yolov5 import utils
      3 display = utils.notebook_init()  # checks

ModuleNotFoundError: No module named 'yolov5'

### Environment

Tensor flow environment, Python 3.8 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@debya01 see Colab notebook:
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

<img width="807" alt="Screen Shot 2021-12-27 at 8 10 25 AM" src="https://user-images.githubusercontent.com/26833433/147488937-ca258afc-a272-4b99-aafd-b88d9dedc7ac.png">
