### ISSUE TITLE
log_dataset quits with errors previously it was working fine

### ISSUE THREAD

**Issue by alijundi** [ultralytics/yolov5#6109]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Other

### Bug

I am getting the below every time I try to sync with wandb.

`C:\Work\Python\yolov5-master>python utils/loggers/wandb/log_dataset.py --project CLASSIFIER2T --data data/CLASSIFIER2T_dataset.yaml
wandb: Currently logged in as: alijundi1 (use `wandb login --relogin` to force relogin)
wandb: Tracking run with wandb version 0.12.9
wandb: Syncing run log dataset
wandb:  View project at https://wandb.ai/alijundi1/CLASSIFIER2T
wandb:  View run at https://wandb.ai/alijundi1/CLASSIFIER2T/runs/no1r5rc6
wandb: Run data is saved locally in C:\Work\Python\yolov5-master\wandb\run-20211227_134543-no1r5rc6
wandb: Run `wandb offline` to turn off syncing.

Scanning 'M:\AI\Training Material\CLASSIFIER2T\train.cache' images and labels... 6 found, 0 missing, 0 empty, 0 corrupted: 100%|█| 6/6 [00:00<?,
  0%|                                                                                                                      | 0/1 [00:00<?, ?it/s]wandb: Adding directory to artifact (M:\AI\Training Material\CLASSIFIER2T\train)... Done. 0.0s
wandb: Adding directory to artifact (M:\AI\Training Material\CLASSIFIER2T\train)... Done. 0.0s
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.98it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:01<00:00,  5.27it/s]
Traceback (most recent call last):
  File "C:\Work\Python\yolov5-master\utils\loggers\wandb\log_dataset.py", line 27, in <module>
    create_dataset_artifact(opt)
  File "C:\Work\Python\yolov5-master\utils\loggers\wandb\log_dataset.py", line 11, in create_dataset_artifact
    logger = WandbLogger(opt, None, job_type='Dataset Creation')  # TODO: return value unused
  File "C:\Work\Python\yolov5-master\utils\loggers\wandb\wandb_utils.py", line 190, in __init__
    self.data_dict = self.check_and_upload_dataset(opt)
  File "C:\Work\Python\yolov5-master\utils\loggers\wandb\wandb_utils.py", line 203, in check_and_upload_dataset
    config_path = self.log_dataset_artifact(opt.data,
  File "C:\Work\Python\yolov5-master\utils\loggers\wandb\wandb_utils.py", line 345, in log_dataset_artifact
    self.train_artifact = self.create_dataset_table(LoadImagesAndLabels(
  File "C:\Work\Python\yolov5-master\utils\loggers\wandb\wandb_utils.py", line 428, in create_dataset_table
    artifact.add(table, name)
  File "C:\Users\alijundi.TECOGRP\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_artifacts.py", line 500, in add
    val = obj.to_json(self)
  File "C:\Users\alijundi.TECOGRP\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\data_types.py", line 610, in to_json
    mapped_row.append(_json_helper(v, artifact))
  File "C:\Users\alijundi.TECOGRP\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\data_types.py", line 105, in _json_helper
    return val.to_json(artifact)
  File "C:\Users\alijundi.TECOGRP\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\data_types.py", line 2303, in to_json
    classes_entry = artifact.add(self._classes, class_name)
  File "C:\Users\alijundi.TECOGRP\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_artifacts.py", line 520, in add
    with self.new_file(name) as f:
  File "C:\Users\alijundi.TECOGRP\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "C:\Users\alijundi.TECOGRP\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_artifacts.py", line 359, in new_file
    raise ValueError(
ValueError: File with name "media\classes\9a0abffd2e2a2ca886e5654250e055d0_cls.classes.json" already exists at "C:\Users\ALIJUN~1.TEC\AppData\Local\Temp\tmp46s6ye0v\media\classes\9a0abffd2e2a2ca886e5654250e055d0_cls.classes.json"

wandb: Waiting for W&B process to finish, PID 16348... (failed 1). Press ctrl-c to abort syncing.
wandb:
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Synced log dataset: https://wandb.ai/alijundi1/CLASSIFIER2T/runs/no1r5rc6
wandb: Find logs at: .\wandb\run-20211227_134543-no1r5rc6\logs\debug.log
wandb:
`

Any assistance please guys I am stuck here

### Environment

Windows 10
Python 3.9.7

### Minimal Reproducible Example

python utils/loggers/wandb/log_dataset.py --project CLASSIFIER2T --data data/CLASSIFIER2T_dataset.yaml

### Additional

This was working earlier I am not sure why it is not working now!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
Hey @alijundi this seems like a windows specific issue. Have you tried to reproduce this in colab? 
I'll get someone from the team to take a look at this after the holidays, but in the meantime you can try to manually troubleshoot. 
The problem seems to be with windows temp files. I'm not sure if that'll work but maybe try manually deleting the file at `C:\Users\ALIJUN~1.TEC\AppData\Local\Temp\`.

**Comment by alijundi** [comment]
@AyushExel Thank you for your feedback. I actually did try to delete the temp file with no luck.

I managed to delete the raise error from the original

`
    @contextlib.contextmanager
    def new_file(self, name: str, mode: str = "w") -> Generator[IO, None, None]:
        self._ensure_can_add()
        path = os.path.join(self._artifact_dir.name, name.lstrip("/"))
`

delete 

`
        if os.path.exists(path):
            raise ValueError(
                'File with name "%s" already exists at "%s"' % (name, path)
            )
`

Then everything worked as expected. I am not sure why this exception is raising!

**Comment by AyushExel** [comment]
@alijundi oh nice. Can you let me know where you deleted the line from exactly? This may be helpful for debugging

**Comment by alijundi** [comment]
@AyushExel file named wandb_artifacts.py

`

    @contextlib.contextmanager
    def new_file(self, name: str, mode: str = "w") -> Generator[IO, None, None]:
        self._ensure_can_add()
        path = os.path.join(self._artifact_dir.name, name.lstrip("/"))

        if os.path.exists(path):
            raise ValueError(
                'File with name "%s" already exists at "%s"' % (name, path)
            )


        util.mkdir_exists_ok(os.path.dirname(path))
        with util.fsync_open(path, mode) as f:
            yield f

        self.add_file(path, name=name)

`

**Comment by AyushExel** [comment]
@alijundi I see. thankyou. I think windows temp files are misbehaving. I'm glad you were able to solve this, I'll point someone from the team to this.

**Comment by alvesraisa** [comment]
Thank you! I had the same error. This worked for me too.

**Comment by MiguelGD7** [comment]
Hey @alijundi, @alvesraisa  I am having the same issue but I can´t find the file wandb_artifacts.py 
where did you find this file?
thank you!

**Comment by alijundi** [comment]
file is located in :

C:\Users\XXXXXXXX\AppData\Local\Programs\Python\Python39\Lib\site-packages\wandb\sdk

**Comment by MiguelGD7** [comment]
@alijundi Thank you! That worked for me too

**Comment by ozett** [comment]
looks like the bug still persists today.

and therefore use of wandb for training yolov5 with their documented workflow only runs 
after fixing the bug manually in the local wandb-sdk-source.

but this issue helped me out. thx

![image](https://user-images.githubusercontent.com/5937811/149657312-a875b2f8-5bcb-41a5-b3f4-e82b07118fc7.png)

**Comment by glenn-jocher** [comment]
@AyushExel seems like log_dataset is still causing issues, can you look into this?

**Comment by AyushExel** [comment]
@glenn-jocher Yes, an engineer has been assigned to this. This is windows specific issue.

**Comment by glenn-jocher** [comment]
@AyushExel oh got it, thanks! 

Windows... yup.

**Comment by AyushExel** [comment]
@glenn-jocher and others, this is fixed in the current master of wandb client and will be available in the next pip version.

**Comment by glenn-jocher** [comment]
@AyushExel awesome, thanks for the update!
