### ISSUE TITLE
anchor assign

### ISSUE THREAD

**Issue by XiaoJiNu** [ultralytics/yolov5#611]
Hi, I read the code and find that you assigns anchor and targets as follow: 
    r = t[None, :, 4:6] / anchors[:, None]  # wh ratio
    j = torch.max(r, 1. / r).max(2)[0] < model.hyp['anchor_t']  # compare  
I'm confused that if there were k(k>3) targets locate in one grid and every target meets the compare condition, the output of a grid only predicts 3 of anchors. I think the output and target are not matched. How do you solve this problem?

**Comment by glenn-jocher** [comment]
@XiaoJiNu all available anchors are assigned to all past-threshold targets during training.

**Comment by glenn-jocher** [comment]
@XiaoJiNu if you anticipate large numbers of similarly sized targets per grid, you may want to increase your anchor count to a number more suitable to your liking than 3.

**Comment by XiaoJiNu** [comment]
@glenn-jocher thanks for your reply, increase anchor numbers is a good solution,  but I think there maybe a better solution although I don't konw how to do...

**Comment by glenn-jocher** [comment]
@XiaoJiNu yes, there are always better solutions out there waiting to be discovered. Experimentation is the key, the current implementation should really just be considered a starting point for your own research. If you discover a better technique please let us know!

**Comment by XiaoJiNu** [comment]
@glenn-jocher I got it, thanks for your patient reply
