### ISSUE TITLE
How to get APs values for large, medium and small targets

### ISSUE THREAD

**Issue by shenhaibb** [ultralytics/yolov5#6110]
### Search before asking

- [ ] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to get ap values for big targets, medium targets, and small targets
I now want to test coco128 first
I converted coco128 to coco JSON format and placed it in the annotations folder
![![image](https://user-images.githubusercontent.com/64736467/147472465-3c6467ce-6661-4ce7-919c-f8eaef8ac98c.png)](https://user-images.githubusercontent.com/64736467/147472427-a85f33f3-cddc-4141-a2de-4d24485ed545.png)
![image](https://user-images.githubusercontent.com/64736467/147472598-c4267319-efbf-41a2-a9af-7cb86c554505.png)

Yolov5s_predictions.json was tested using yolov5s.pt
![image](https://user-images.githubusercontent.com/64736467/147472610-258eb01e-d592-40a8-bb23-ed32cdaa74c1.png)

Why do I get an error when running val.py
![image](https://user-images.githubusercontent.com/64736467/147472624-5913fbb8-d3f6-48b8-ae65-9aa1e62e7cc7.png)

**Comment by shenhaibb** [comment]
i will try this https://github.com/ultralytics/yolov5/issues/4535#issue-978850041

**Comment by shenhaibb** [comment]
hey, i solve it
i use my own dataset and now test by coco128
annotations and imgs must be numbered from 0,1.... no str
like this
![image](https://user-images.githubusercontent.com/64736467/147546012-87f69e48-aad2-4108-9a22-6471a8bab770.png)
and this parameter must be added
![image](https://user-images.githubusercontent.com/64736467/147546076-493a6d88-b8f0-4196-8a5f-72e2d9ca35b2.png)
![image](https://user-images.githubusercontent.com/64736467/147546265-98e8f950-7302-4ae7-9904-69d1e87ee62a.png)

**Comment by shenhaibb** [comment]
but i got this result
crying...
![image](https://user-images.githubusercontent.com/64736467/147547206-9d43622b-66da-4fb2-a716-915d9584f80c.png)
anybody can help?

**Comment by Zengyf-CVer** [comment]
@shenhaibb 
In this case, there should be a problem with the JSON file you converted. Check your JSON file carefully, such as whether `str` is converted to `int`.

**Comment by shenhaibb** [comment]
oh i changed a larger dataset after taking your advice ,it seems right..
![image](https://user-images.githubusercontent.com/64736467/147624027-2f0bd3dc-30a6-4029-a47c-e391ea94c78f.png)
to be honest ,i dont know what kind of data is true
but map0.5 map0.5:0.75 , it is false, right?
![image](https://user-images.githubusercontent.com/64736467/147624052-e345bf7e-79e0-4205-a4b0-e59613975ed2.png)

thanku very much !~

**Comment by engrjav** [comment]
Hey @shenhaibb thanks a lot

After following your steps, i have also got the results the file finally ran but i am also getting zero AP here

can you explain what changes you made further

<img width="495" alt="zeroAP" src="https://user-images.githubusercontent.com/75246709/152492787-bea38a5c-ee69-4a36-9f4a-cc5aab50bd20.PNG">

**Comment by engrjav** [comment]
@shenhaibb  were you able to match your coco metrics evaluation to the yolo v5 one?

**Comment by shenhaibb** [comment]
> 
If the dataset you are using is too small, you can try to test with a larger dataset


> @shenhaibb were you able to match your coco metrics evaluation to the yolo v5 one?

**Comment by engrjav** [comment]
@shenhaibb  ok i will do the effort. 
also how much modification is required in val.py in addition to commenting "iscoco" as in https://github.com/ultralytics/yolov5/issues/4535#issue-978850041

**Comment by SamSamhuns** [comment]
@engrjav Were you able to solve your issue? I have the same issue where mAP is way higher for YOLOv5 val.py but extremely low when using the pycocotools for a custom dataset
![Screenshot 2023-01-12 at 11 51 15 AM](https://user-images.githubusercontent.com/13418507/212030856-8c43e95e-e6cf-49f3-8392-39b13edbd20b.png)

*Edit: Solved it. THe problem was the converted coco annotations had 1-indexed class ids while val.py generates 0 indexed class ids in the json file.

Created my own converter to help anyone in the future https://github.com/SamSamhuns/ml_data_processing/tree/master/annotation_format_conv
