### ISSUE TITLE
About calculating FOLPs

### ISSUE THREAD

**Issue by nuaasxr** [ultralytics/yolov5#6111]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Near line 226 in utils/torch_utils.py, why do you use 32 (stride) instead of 640 (img_size) to calculate FOLPs? Although the last 232 lines have been transformed.
Why not just use the actual image size（640） to calculate FOLPs? Is it to simplify the calculation?
```
      from thop import profile

     stride = max(int(model.stride.max()), 32) if hasattr(model, 'stride') else 32

      img = torch.zeros((1, model.yaml.get('ch', 3), stride, stride), device=next(model.parameters()).device)  # input

      flops = profile(deepcopy(model), inputs=(img,), verbose=False)[0] / 1E9 * 2  # stride GFLOPs

      img_size = img_size if isinstance(img_size, list) else [img_size, img_size]  # expand if int/float

      fs = ', %.1f GFLOPs' % (flops * img_size[0] / stride * img_size[1] / stride)  # 640x640 GFLOPs
```

**Comment by glenn-jocher** [comment]
@nuaasxr using the actual image size is much slower.

**Comment by nuaasxr** [comment]
> @nuaasxr using the actual image size is much slower.

Okay, I guessed it! Thank you!

**Comment by lawo123** [comment]
> flops = profile(deepcopy(model), inputs=(img,), verbose=False)[0] / 1E9 * 2

 Most papers (including the well-known ResNet paper)/toolboxes do not differentiate MACs and FLOPs.why *2？
@glenn-jocher

**Comment by glenn-jocher** [comment]
@lawo123 an MAC is a multiply and an addition. Each of those operations is 1 FLOP, so 1 MAC == 2 FLOPs
