### ISSUE TITLE
The training statistical results are inconsistent with wandb

### ISSUE THREAD

**Issue by hyq456** [ultralytics/yolov5#6116]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

The next two pictures are from the same training but the statistics are different.The result from val.py is always better than wandb.Is it normal? Which one is more accurate or credible
![image](https://user-images.githubusercontent.com/24841335/147535928-31b8c170-8cd7-47d1-8eef-3c96fd7746e4.png)
![image](https://user-images.githubusercontent.com/24841335/147535989-35a907bb-a8f6-4fd0-9013-f291dd95a020.png)

THANKS

**Comment by AyushExel** [comment]
@glenn-jocher I noticed that in the callbacks refactor of the loggers, the result is not logged after the training is finished.
See this [function](https://github.com/ultralytics/yolov5/blob/db6ec66a602a0b64a7db1711acd064eda5daf2b3/utils/loggers/__init__.py#L137), the `results` argument is unused.
I'll make a PR for fix this for wandb, I think the result will also need to be logged for tensorboard.

**Comment by glenn-jocher** [comment]
@AyushExel yes, good idea!
