### ISSUE TITLE
Why does the model's inference speed slow down when ‘half==True’?

### ISSUE THREAD

**Issue by nuaasxr** [ultralytics/yolov5#6118]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

To be reasonable, when ‘half==True’, the model is converted to a half-precision model, and its inference speed should be faster! In order to use ‘half==True’ on yolov5s, its inference speed slows down instead? Is it a problem with my computer?

### Additional

```
(pth) nuaave@nDELL:~/YOLO/Y5$ python detect.py
detect: weights=yolov5s.pt, source=data/images, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False
YOLOv5 🚀 2021-12-27 torch 1.10.0+cu113 CUDA:0 (NVIDIA GeForce RTX 3090, 24260MiB)

Fusing layers... 
Model Summary: 213 layers, 7225885 parameters, 0 gradients
image 1/2 /home/nuaave/YOLO/Y5/data/images/bus.jpg: 640x480 4 persons, 1 bus, Done. (0.010s)
image 2/2 /home/nuaave/YOLO/Y5/data/images/zidane.jpg: 384x640 2 persons, 1 tie, Done. (0.011s)
Speed: 0.5ms pre-process, 10.4ms inference, 1.1ms NMS per image at shape (1, 3, 640, 640)
Results saved to runs/detect/exp8
```

```
(pth) nuaave@nDELL:~/YOLO/Y5$ python detect.py --half
detect: weights=yolov5s.pt, source=data/images, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=True, dnn=False
YOLOv5 🚀 2021-12-27 torch 1.10.0+cu113 CUDA:0 (NVIDIA GeForce RTX 3090, 24260MiB)

Fusing layers... 
Model Summary: 213 layers, 7225885 parameters, 0 gradients
image 1/2 /home/nuaave/YOLO/Y5/data/images/bus.jpg: 640x480 4 persons, 1 bus, Done. (0.018s)
image 2/2 /home/nuaave/YOLO/Y5/data/images/zidane.jpg: 384x640 2 persons, 1 tie, Done. (0.019s)
Speed: 0.4ms pre-process, 18.5ms inference, 1.0ms NMS per image at shape (1, 3, 640, 640)
Results saved to runs/detect/exp9
```

```
(pth) nuaave@nDELL:~/YOLO/Y5$ python detect.py --device cpu
detect: weights=yolov5s.pt, source=data/images, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=cpu, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False
YOLOv5 🚀 2021-12-27 torch 1.10.0+cu113 CPU

Fusing layers... 
Model Summary: 213 layers, 7225885 parameters, 0 gradients
image 1/2 /home/nuaave/YOLO/Y5/data/images/bus.jpg: 640x480 4 persons, 1 bus, Done. (0.093s)
image 2/2 /home/nuaave/YOLO/Y5/data/images/zidane.jpg: 384x640 2 persons, 1 tie, Done. (0.071s)
Speed: 0.8ms pre-process, 82.0ms inference, 1.0ms NMS per image at shape (1, 3, 640, 640)
Results saved to runs/detect/exp13
```

```
(pth) nuaave@nDELL:~/YOLO/Y5$ python detect.py --half --device cpu
detect: weights=yolov5s.pt, source=data/images, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=cpu, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=True, dnn=False
YOLOv5 🚀 2021-12-27 torch 1.10.0+cu113 CPU

Fusing layers... 
Model Summary: 213 layers, 7225885 parameters, 0 gradients
image 1/2 /home/nuaave/YOLO/Y5/data/images/bus.jpg: 640x480 4 persons, 1 bus, Done. (0.090s)
image 2/2 /home/nuaave/YOLO/Y5/data/images/zidane.jpg: 384x640 2 persons, 1 tie, Done. (0.073s)
Speed: 0.8ms pre-process, 81.5ms inference, 1.3ms NMS per image at shape (1, 3, 640, 640)
Results saved to runs/detect/exp14
```

_No response_

**Comment by glenn-jocher** [comment]
@nuaasxr 👋 Hello! Thanks for asking about **inference speed issues**. YOLOv5 🚀 can be run on CPU (i.e. `--device cpu`, slow) or GPU if available (i.e. `--device 0`, faster). You can determine your inference device by viewing the YOLOv5 console output:

### detect.py inference
```bash
python detect.py --weights yolov5s.pt --img 640 --conf 0.25 --source data/images/
```
<img width="944" alt="detect.py" src="https://user-images.githubusercontent.com/26833433/140100842-e130b5f7-64cb-46c9-9386-72abadd19828.png">

### YOLOv5 PyTorch [Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) inference
```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Images
dir = 'https://ultralytics.com/images/'
imgs = [dir + f for f in ('zidane.jpg', 'bus.jpg')]  # batch of images

# Inference
results = model(imgs)
results.print()  # or .show(), .save()
# Speed: 631.5ms pre-process, 19.2ms inference, 1.6ms NMS per image at shape (2, 3, 640, 640)
```

### Increase Speeds

If you would like to increase your inference speed some options are:

- Use batched inference with [YOLOv5 PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)
- Reduce `--img-size`, i.e. 1280 -> 640 -> 320
- Reduce model size, i.e. YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s -> YOLOv5n
- Use half precision FP16 inference with `python detect.py --half` and `python val.py --half`
- Use a faster GPUs, i.e.: P100 -> V100 -> A100
- [Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) to ONNX for up to 3x CPU speedup
- [Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) to TensorRT for up to 5x GPU speedup
- Use a free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

Good luck 🍀 and let us know if you have any other questions!

**Comment by nuaasxr** [comment]
But when I use 
‘python detect.py --half`, 
the inference speed of the model slows down instead? Is this a problem with my computer?

**Comment by dariogonle** [comment]
Have you tried to use the CPU instad of the GPU with model X?

**Comment by nuaasxr** [comment]
> Have you tried to use the CPU instad of the GPU with model X?

Still the same configuration! The same GPU! You can watch my update on the question.

**Comment by Schweizliu** [comment]
Have you solved this problem yet
