### ISSUE TITLE
Detecting 2 objects in 1 object

### ISSUE THREAD

**Issue by Mehul343** [ultralytics/yolov5#6121]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is there any way to stop it from detecting 2 objects in 1 object? I made a captcha solver but it detects 2 numbers in 1 number. Like in 8 it detects 8 and 3. Is there any way to stop this. Really sorry if this is a dumb question.

**Comment by glenn-jocher** [comment]
@Mehul343
```
python detect.py --agnostic
```

**Comment by Mehul343** [comment]
> @Mehul343
> 
> ```
> python detect.py --agnostic
> ```

How can I use this argument for detecting with torch hub?

**Comment by Mehul343** [comment]
> > @Mehul343
> > ```
> > python detect.py --agnostic
> > ```
> 
> How can I use this argument for detecting with torch hub?

I figured it out myself, thank you.

**Comment by nazar220160** [comment]
Hello, could you give me the source code, I've been looking for this for a long time but I can't do it. Thanks in advance

**Comment by glenn-jocher** [comment]
@nazar220160 hi there! Thanks for reaching out. You can find the source code for YOLOv5 on the official Ultralytics YOLOv5 repository at https://github.com/ultralytics/yolov5. Feel free to explore the code there. If you have any specific questions about the source code or need further assistance, please don't hesitate to ask. Good luck with your project!
