### ISSUE TITLE
How to cancel the data augmentation of letterbox during training?

### ISSUE THREAD

**Issue by jayer95** [ultralytics/yolov5#6122]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I know that yolov5 introduced "letterbox" data augmentation and many hyperparameters to increase the strength of the model, but I need to do an experiment.

As title, how can I cancel the data augmentation of "letterbox" during training?

The images size of my training dataset is all 1920x1080. I want to do an experiment to cancel the data augmentation "letterbox" made by yolov5 during training, and resize all 1920x1080 images to 640x640, even if the images are distorted due to resizing.

I checked the argument options and hyperparameters before training, but it did not have the switch of "letterbox", or I missed an important code, please guide me, thank you.

I know that one argument is "--rect", and I don't mean rectangular training.

**Comment by glenn-jocher** [comment]
@jayer95 letterboxing is a method for fitting an image within a constrained space dictated by the model requirements. You can modify the arguments into the function here:
https://github.com/ultralytics/yolov5/blob/db6ec66a602a0b64a7db1711acd064eda5daf2b3/utils/augmentations.py#L91-L122

**Comment by jayer95** [comment]
Hi @glenn-jocher ,
I'm the author of this article,
https://github.com/ultralytics/yolov5/issues/5244

Do you mean to make this function an "argument" and add "--letterbox false" to the instruction during training?

Can I just delete this "letterbox" function (yolov5/utils/augmentations.py)?

I'm currently training with "--rect" and I don't need "letterbox".

**Comment by glenn-jocher** [comment]
@jayer95 letterbox function adapts input images to meet minimum stride length constraints. It is required.

**Comment by jayer95** [comment]
@glenn-jocher In order to make up the remainder of the width and height for multiple of 32.

**Comment by jayer95** [comment]
@glenn-jocher 
I understand.

**Comment by jayer95** [comment]
Hi @glenn-jocher ,
If I use rectangular training to force resize to 384x640,
Or I don't use rectangular training, I use like YOLOv4 (darknet) to force resize into a square like 416x416, how can I cancel the "letterbox"?

**Comment by glenn-jocher** [comment]
@jayer95 you can customize the letterbox arguments or code if you'd like.

**Comment by jayer95** [comment]
@glenn-jocher 

Hi author, after our in-depth research, we understand the mosaic parameters and letterbox practices you use during training.

![train_batch2](https://user-images.githubusercontent.com/35683311/149448091-a3adbb16-4736-41eb-9f0b-2704669e99c2.jpg)

I would like to ask you about letterbox when inference (detect.py),
When inferring,

python detect.py --source demo_h264.mp4 --weights runs/train/exp7/weights/last.pt --imgsz 320

demo_h264.mp4 ---> 1920x1080, landscape
will see him do letterbox,

video 1/1 (136/140) /home/gvsai/yolov5/demo_h264.mp4: 192x320 1 license plate, Done. (0.008s)
video 1/1 (137/140) /home/gvsai/yolov5/demo_h264.mp4: 192x320 1 license plate, Done. (0.009s)
video 1/1 (138/140) /home/gvsai/yolov5/demo_h264.mp4: 192x320 1 license plate, Done. (0.008s)

I looked at your code, you are filling the gray border of (114,114,114) up and down to make up the multiple of 32, as shown below,

![5918286](https://user-images.githubusercontent.com/35683311/149448127-a28f30e4-2bfc-4722-a985-64bdcd0dc781.jpg)

May I ask why you don't fill all of them on the top, or all of them on the bottom, as shown in the image below?

![5918289](https://user-images.githubusercontent.com/35683311/149448156-9b634632-d14e-487b-80dd-b3db2f12c772.jpg)

May I ask whether you have proved through experiments that fill the top and bottom are the best because of the mosaic parameters during training?

**Comment by glenn-jocher** [comment]
@jayer95 the current letterbox implementation provides the best results compared to the alternatives, i.e. the decision making process was informed via empirical results.

**Comment by jayer95** [comment]
@glenn-jocher Thanks for your quick reply.
