### ISSUE TITLE
Tensorflow model is not using the GPU

### ISSUE THREAD

**Issue by dariogonle** [ultralytics/yolov5#6127]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have exported the N model to TF. When I run it I get that the inference time is 30ms. If I add --device cpu I get the same time. How is it posiible when with pytorch I get 5ms as inference time with the GPU?

### Additional
Times with GPU:
pt: Speed: 0.3ms pre-process, 5.3ms inference, 0.7ms NMS per image at shape (1, 3, 640, 640)
pb: Speed: 0.3ms pre-process, 26.6ms inference, 0.6ms NMS per image at shape (1, 3, 640, 640)
_No response_

**Comment by glenn-jocher** [comment]
@dariogonle generally --device argument will only apply to ONNX, PyTorch, TorchScript and TensorRT inference, with all others defaulting to a backend, either CPU or GPU, depending on the package installed and the system resources found.
