### ISSUE TITLE
questions when training

### ISSUE THREAD

**Issue by Polary-L** [ultralytics/yolov5#613]
## ❔Question
when I train  custom data ,there is something wrong  in runs/exp0/test_batch0_pred.jpg
![image](https://user-images.githubusercontent.com/56144419/89158272-6e494280-d5a0-11ea-8e50-5cf6e3bf28ad.png)
one target gets many bb on it?  NMS  didn't apply on it or any other questions I missed?Thank you

## Additional context
I trained yolov5 with 
python train.py --img-size 640 --batch-size 16  --epochs 300 --data ./data/ETH.yaml --cfg ./models/yolov5s.yaml --weights ./weights/yolov5s.pt

and changed number of class to 1 in yolov5s.yaml&ETH.yaml

**Comment by glenn-jocher** [comment]
@Polary-L you can modify nms and detection parameters as you see fit in both detect.py and test.py.
