### ISSUE TITLE
val.py / test.py gains unbelievable great results 

### ISSUE THREAD

**Issue by Sly-Guo** [ultralytics/yolov5#6131]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hey，i met this question when i was working on my custom dataset (one is RGB dataset, the other is NIR dataset, but with the same labels and targets).

So, firstly, I trained on RGB dataset （divided into 8:2 train:val）. The metrics showed during training process is normal, like this: 
![image](https://user-images.githubusercontent.com/40057944/147717401-4cac5866-de80-4e49-8c1d-e47608ccc3e7.png)

But when I was reproducing the result by using only test.py (or the newest val.py I just cloned), they both gave too good results(everything is 1 ！！！). Here is the results from the only val.py:
![image](https://user-images.githubusercontent.com/40057944/147717485-0e86bdea-e978-4ee9-a2eb-633d0305cf29.png)

In addition, even when I validated on my NIR dataset, it still got the similar unbelievable results, which is quite confusing.

![1640832798(1)](https://user-images.githubusercontent.com/40057944/147717852-b6b3b92a-b090-4864-9395-5555ba0a04e8.jpg)

I know some extra works are done  when using only val.py, but the results shouldn't be sooooo good. 
I searched every issue in the repo while got nothing similar. 
Please help and if there are any similar issues that I didn't notice, just let me know. 
Thanks a lot!

### Additional

These are some comparisons between the labels and predictions.
You can see there are indeed some bad predictions or even wrong predictions.
 
![image](https://user-images.githubusercontent.com/40057944/147717563-e794255e-6eaa-4bef-a861-c21fb426ae77.png)
![image](https://user-images.githubusercontent.com/40057944/147717937-aae0e801-7b80-4b25-9f2f-554c499cd583.png)

And some comparisons of  NIR images :
![image](https://user-images.githubusercontent.com/40057944/147718037-976357b3-d6a6-46ce-841f-799ae7921f84.png)

![1640833013(1)](https://user-images.githubusercontent.com/40057944/147718019-1ab457fc-5359-4545-a461-79bf5fc8f6cb.jpg)

**Comment by Sly-Guo** [comment]
您好，我是郭航甫，感谢您的来信，我会尽快查看并回复，祝您生活愉快。

**Comment by foemre** [comment]
I have a similar question but want to add this: how does cross validation work in train.py?

**Comment by Sly-Guo** [comment]
> 

1. i've figured out this issue. It's because the save_hybrid flag which will be used in autolabel (in the NMS). Just set it back to store_true.

2. I don't think there is cross validation in yolov5. Maybe u can look it up more thoroughly or just try to modify the original module.
