### ISSUE TITLE
how I get AP AP50 AP75 with yolov5 v5.0

### ISSUE THREAD

**Issue by QY1994-0919** [ultralytics/yolov5#6134]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

1.I found that the final result is the result of the last epoch after trian. I need the result of AP AP50 AP75. How do I calculate it?
2.There is no val.py file in the V5.0 version of YOLOv5 I use, how do I calculate it?

andb: Run history:
wandb:        metrics/mAP_0.5 ▁▄▅▆▆▆▆▆▆▆▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇██████████████
wandb:   metrics/mAP_0.5:0.95 ▁▃▅▅▆▆▆▆▆▆▆▆▆▆▇▇▇▇▇▇▇▇▇▇▇▇▇▇████████████
wandb:      metrics/precision ▄▁▃▃▄▄▃▄▄▃▆▄▄▃▄▃▄▄▄▅▅▅▅▆▆█▅▆▅▆▆▇▇▇▇█▇▆▇▇
wandb:         metrics/recall ▁▄▅▆▆▆▆▆▆▇▆▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇█▇▇▇▇█▇▇████
wandb:         train/box_loss █▅▅▄▃▃▃▃▃▃▃▃▃▃▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁
wandb:         train/cls_loss █▄▃▃▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:         train/obj_loss ▇▅█▇▇▆▆▆▆▆▅▆▅▅▅▅▅▅▅▅▄▄▄▄▃▄▃▃▃▃▃▂▂▂▂▂▂▁▁▁
wandb:           val/box_loss █▆▅▄▃▃▃▃▃▃▃▃▃▃▂▂▂▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:           val/cls_loss █▄▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:           val/obj_loss ███▇▆▆▅▅▅▅▅▅▅▅▅▅▅▄▄▄▄▃▃▃▃▃▂▂▂▂▂▂▂▂▁▁▁▁▁▁
wandb:                  x/lr0 ▂▅██████▇▇▇▇▇▇▆▆▆▆▅▅▅▅▄▄▄▃▃▃▃▂▂▂▂▂▁▁▁▁▁▁
wandb:                  x/lr1 ▂▅██████▇▇▇▇▇▇▆▆▆▆▅▅▅▅▄▄▄▃▃▃▃▂▂▂▂▂▁▁▁▁▁▁
wandb:                  x/lr2 █▅▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb: 
wandb: Run summary:
wandb:        metrics/mAP_0.5 0.xxxx
wandb:   metrics/mAP_0.5:0.95 0.xxxx
wandb:      metrics/precision 0.xxx
wandb:         metrics/recall 0.xxx
wandb:         train/box_loss 0.xxx
wandb:         train/cls_loss 0.xxx
wandb:         train/obj_loss 0.xxx
wandb:           val/box_loss 0.xxxx
wandb:           val/cls_loss 0.xxx
wandb:           val/obj_loss 0.xxx
wandb:                  x/lr0 0.xxx
wandb:                  x/lr1 0.xxx
wandb:                  x/lr2 0.0xxx

**Comment by glenn-jocher** [comment]
@QY1994-0919 use the latest code.

val.py outputs index 0 on the 0.5:0.05:0.95 IoU vector. You can modify this index here:
https://github.com/ultralytics/yolov5/blob/db6ec66a602a0b64a7db1711acd064eda5daf2b3/val.py#L243
