### ISSUE TITLE
Yolov5  :  Where is the ModelClass        ????

### ISSUE THREAD

**Issue by Lee-jaehyun** [ultralytics/yolov5#6135]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, Everyone!!

I have a question, so I'm writing.

In general, there are two cases when loading a trained model in PyTorch.

1.  model = torch.hub.load(~~~, 'custom', path='bset.pt'  , source = 'local')
     torch.save(model, "./aaa.pt")
     

     yolo_model = torch.load("aaa.pt")                    ==>  This method saves and loads the entire model.

2. model = torch.hub.load(~~~, 'custom', path='bset.pt'  , source = 'local')
     torch.save(model.state_dict(), "./aaa.pt")

 In the above case, we know that the learned weights are loaded after defining the model class.

In general, PyTorch uses it like this:
    model = TheModelClass(*args, **kwargs) 
    model.load_state_dict(torch.load(PATH))

How to load state_dict in YOLO???

I wonder where the model class definition is.

I'm curious about loading the model with the load_state_dict method.

### Additional

Help me, plz

**Comment by iumyx2612** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.
> 
> ### Question
> Hello, Everyone!!
> 
> I have a question, so I'm writing.
> 
> In general, there are two cases when loading a trained model in PyTorch.
> 
> 1. model = torch.hub.load(~~~, 'custom', path='bset.pt'  , source = 'local')
>    torch.save(model, "./aaa.pt")
>    yolo_model = torch.load("aaa.pt")                    ==>  This method saves and loads the entire model.
> 2. model = torch.hub.load(~~~, 'custom', path='bset.pt'  , source = 'local')
>    torch.save(model.state_dict(), "./aaa.pt")
> 
> In the above case, we know that the learned weights are loaded after defining the model class.
> 
> In general, PyTorch uses it like this: model = TheModelClass(*args, **kwargs) model.load_state_dict(torch.load(PATH))
> 
> How to load state_dict in YOLO???
> 
> I wonder where the model class definition is.
> 
> I'm curious about loading the model with the load_state_dict method.
> 
> ### Additional
> Help me, plz

YOLOv5 save the whole model, not just the weights and biases, see [here](https://github.com/ultralytics/yolov5/issues/5090)
if you want to load the state_dict, check [here](https://github.com/ultralytics/yolov5/issues/1441)
the reason for saving the model like that can be found [here](https://github.com/ultralytics/yolov5/issues/1149)
if you want to know about the Model and how it's construct, check models/yolo.py, [line 309](https://github.com/ultralytics/yolov5/blob/master/models/yolo.py#L309)
