### ISSUE TITLE
About AP 

### ISSUE THREAD

**Issue by QY1994-0919** [ultralytics/yolov5#6139]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have find in the test.py there have the mAP@0.5 to evaluate the model.
If I want to change the IOU threshold like AP@0.50 AP@0.75.
How can I change in the code.
I am confusing in change  mAP@0.5 to  AP@0.50 AP@0.75.

**Comment by glenn-jocher** [comment]
@QY1994-0919 you can select other indices of the 0.5:0.05:0.95 vector here:
https://github.com/ultralytics/yolov5/blob/db6ec66a602a0b64a7db1711acd064eda5daf2b3/val.py#L243

**Comment by QY1994-0919** [comment]
1.Thanks! Since I used test.py in the V5.0 version released by YOLOv5, the following part of test.py was modified.
test.py 
 iouv = torch.linspace(0.5, 0.75, 10).to(device)  # iou vector for mAP@0.5:0.95
 s = ('%20s' + '%12s' * 6) % ('Class', 'Images', 'Labels', 'P', 'R', 'mAP@.5', 'mAP@.5:.75')
ap50, ap = ap[:, 0], ap.mean(1)  # AP@0.5, AP@0.5:0.95

2.But I didn’t figure it out a bit, because I wanted to get the results of AP@0.5 and AP@0.75. Are the results of mAP0.5 and mAP0.75 in the following results AP@0.5 and AP@0.75?
              Class     Images     Labels          P          R     mAP@.5 mAP@.5:.75:  99%|█████████▊| 155/157 [00:52<00:00,  4.24it/s]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.75:  99%|█████████▉| 156/157 [00:53<00:00,  4.27it/s]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.75: 100%|██████████| 157/157 [00:53<00:00,  2.96it/s]
                 all       4999      36772      0.659      0.503      0.548      0.469

**Comment by QY1994-0919** [comment]
@glenn-jocher 
In addition, I also want to calculate the value of mAP, how do I get it? Thank you very much

**Comment by QY1994-0919** [comment]
@glenn-jocher  Hello, I read the code below. Is the mAP0.5 in it the AP0.5 commonly seen in the paper? Is mAP0.5-0.95 the mAP?

test.py
# Compute statistics
    stats = [np.concatenate(x, 0) for x in zip(*stats)]  # to numpy
    if len(stats) and stats[0].any():
        p, r, ap, f1, ap_class = ap_per_class(*stats, plot=plots, save_dir=save_dir, names=names)
        #p, r, ap50, ap = p[:, 0], r[:, 0], ap[:, 0], ap.mean(1)  # [P, R, AP@0.5, AP@0.5:0.95]
        ap50, ap = ap[:, 0], ap.mean(1)  # AP@0.5, AP@0.5:0.95
        mp, mr, map50, map = p.mean(), r.mean(), ap50.mean(), ap.mean()
        nt = np.bincount(stats[3].astype(np.int64), minlength=nc)  # number of targets per class

**Comment by glenn-jocher** [comment]
@QY1994-0919 yes the comments on this line are correct:
```python
#p, r, ap50, ap = p[:, 0], r[:, 0], ap[:, 0], ap.mean(1)  # [P, R, AP@0.5, AP@0.5:0.95]
```

**Comment by solisoares** [comment]
@glenn-jocher, so in order to get ap60 for example, would I have to get the index `2` ?
Like `ap60, ap = ap[:, 2], ap.mean(1)  # AP@0.6, AP@0.5:0.95` 

Thank you in advance

**Comment by glenn-jocher** [comment]
@solisoares yes exactly!

**Comment by atusi-nakajima** [comment]
@glenn-jocher 
https://github.com/ultralytics/yolov5/issues/6139#issuecomment-1185025562
How can I get ap40?

Thank you in advance

**Comment by glenn-jocher** [comment]
@atusi-nakajima AP@0.4 is not directly calculated in the current implementation. However, you can interpolate from AP@0.5 and AP@0.5:0.95 to estimate AP@0.4.
