### ISSUE TITLE
i meet a problem when use --evolve

### ISSUE THREAD

**Issue by Pluto1314** [ultralytics/yolov5#614]
## ❔Question
i meet a problem when use --evolve

## Additional context
Traceback (most recent call last):
  File "train.py", line 522, in <module>
    x = x[random.choices(range(n), weights=w)[0]]  # weighted selection
AttributeError: 'builtin_function_or_method' object has no attribute 'choices'

**Comment by glenn-jocher** [comment]
May be related to https://github.com/ultralytics/yolov5/issues/615

**Comment by glenn-jocher** [comment]
@Pluto1314 this should be resolved now in https://github.com/ultralytics/yolov5/commit/eb99dff9ef4f6f2c26e6cda2f6fe1abfabce8929. Please git pull and try again.

**Comment by Pluto1314** [comment]
@glenn-jocher ok, thanks!
