### ISSUE TITLE
What name and where is the result files are read during plotting confusion matrix 

### ISSUE THREAD

**Issue by uzuco** [ultralytics/yolov5#6140]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello. I am beginner of yolo and need a help about confusion matrix.
I am trying to make an original confusion matrix, but could not find result reading part in metrics.py/train.py script.
Could you tell me at where and what name of the file should be read by scripts?
If it is reading weights, could you also tell me the writing orders( ...like what is in columns and rows ) of the weights file? 
Thanks!

**Comment by glenn-jocher** [comment]
@uzuco YOLOv5 automatically creates confusion matrices on training end or by calling val.py directly:

![image](https://user-images.githubusercontent.com/26833433/147768071-d592931a-cb67-4bc2-8f56-acab0a46a772.png)

**Comment by uzuco** [comment]
Thanks for the comment @glenn-jocher .
I could find the confusion matrix that you sent me after running train.py script.
But I have to customize that the chart (like picking up several classes) for previous runs.
Are TP, TN, FN, FP values stored in arrays or parameters?

**Comment by glenn-jocher** [comment]
@uzuco yes you can customize the confusion matrix here:
https://github.com/ultralytics/yolov5/blob/affa284352fa6d094d32fe2be69dbffe36bd20f8/utils/metrics.py#L117-L199

**Comment by uzuco** [comment]
@glenn-jocher I will try that. Thank you so much for your kind help!
