### ISSUE TITLE
Supercategories-awareness

### ISSUE THREAD

**Issue by Camilochiang** [ultralytics/yolov5#6144]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

- Is yolov5 using supercategory-awareness?  For example,  If i train in dog images and I use different breeds as classes but they are all in the same supercategory ,im not sure if  the algorithm doesn't know that the classes are related , but I guess that it could help if the algorithm know that they are all dogs, but different types.

Thanks again!

**Comment by Camilochiang** [comment]
Answered on #6027

**Comment by glenn-jocher** [comment]
@Camilochiang you probably want to read the YOLOv2 (AKA YOLO9000) paper on this:

https://arxiv.org/abs/1612.08242
