### ISSUE TITLE
Best checkpoints ....

### ISSUE THREAD

**Issue by rkinas** [ultralytics/yolov5#6145]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is any way I can save:
- best ap0.95 checkpoint
- best ap0.5 checkpoit
- best recall checkpoint
- last epoch
- best overall

I know that we can save best/last after each epoch but such feature would be really great.

**Comment by glenn-jocher** [comment]
@rkinas best.pt is saved on every best fitness epoch, where fitness is a weighted combination of metrics dominated by mAP@0.5:0.95. Recall is a function of confidence threshold and does not make sense to use a metric, but it's available to you in the fitness function:
https://github.com/ultralytics/yolov5/blob/affa284352fa6d094d32fe2be69dbffe36bd20f8/utils/metrics.py#L15-L19

For custom tasks you can update the checkpointing code here:
https://github.com/ultralytics/yolov5/blob/affa284352fa6d094d32fe2be69dbffe36bd20f8/train.py#L376-L395
