### ISSUE TITLE
Count

### ISSUE THREAD

**Issue by darko262** [ultralytics/yolov5#6146]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, thank you very much for the great application of yolo.
I have a question, I have seen a type of counting of objects that they do when crossing a virtual line. Is it possible to implement this in yoloV5 ?.

### Additional

https://github.com/tugot17/YOLO-Object-Counting-API

**Comment by glenn-jocher** [comment]
@darko262 you need a **tracker** integrated into YOLO for this, i.e. DeepSort with YOLOv5 is a good example:
https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch
