### ISSUE TITLE
Anchor algorithm and config explain

### ISSUE THREAD

**Issue by iumyx2612** [ultralytics/yolov5#6148]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have 3 questions: 
1. In [YOLOv2](https://arxiv.org/pdf/1612.08242.pdf), Redmon introduced clustering box dimension, which also uses k-mean to find best fit box on the dataset. In YOLOv5, this is further enhanced by applying Genetic Evolution (GE) algorithm after using k-mean right? Can I have the link to the Genetic Evolution algorithm? 
2. If I want the algorithm to pick good anchors for me every time, can I simply don't specify `anchors` in the model config file? 
3. Can you further explain the comments like `# P3/8`, `# P4/16`, `# P5/32` in the model config file
```
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32
```

**Comment by glenn-jocher** [comment]
@iumyx2612 if you want to simplify your config and force autoanchor every time then just specify an anchor count per output layer, i.e. you can replace the default anchors with `anchors: 3`.

AutoAnchor genetic evolution code is here:
https://github.com/ultralytics/yolov5/blob/d95978a562bec74eed1d42e370235937ab4e1d7a/utils/autoanchor.py#L148-L163

**Comment by iumyx2612** [comment]
> @iumyx2612 if you want to simplify your config and force autoanchor every time then just specify an anchor count per output layer, i.e. you can replace the default anchors with `anchors: 3`.
> 
> AutoAnchor genetic evolution code is here:
> 
> https://github.com/ultralytics/yolov5/blob/d95978a562bec74eed1d42e370235937ab4e1d7a/utils/autoanchor.py#L148-L163


So you come up with this Genetic Evolution algorithm yourself? Else can I have the link to the Genetic Evolution paper?

**Comment by glenn-jocher** [comment]
@iumyx2612 yes I came up with this GE algorithm myself. It's a slightly modified version of the main GE algorithm I used for hyperparameter evolution in train.py. See https://en.wikipedia.org/wiki/Genetic_algorithm

**Comment by iumyx2612** [comment]
> @iumyx2612 yes I came up with this GE algorithm myself. It's a slightly modified version of the main GE algorithm I used for hyperparameter evolution in train.py. See https://en.wikipedia.org/wiki/Genetic_algorithm

Very cool! I'll take a look into it. Thank you so much
