### ISSUE TITLE
Wrong import of the random module

### ISSUE THREAD

**Issue by lorenzomammana** [ultralytics/yolov5#615]
## 🐛 Bug
Training the model with the latest commit is not working, this is caused by an error when importing the random module.

## To Reproduce (REQUIRED)

Input:
```
from random import random

# Multi-scale
if opt.multi_scale:
        sz = random.randrange(imgsz * 0.5, imgsz * 1.5 + gs) // gs * gs  # size
        sf = sz / max(imgs.shape[2:])  # scale factor
        if sf != 1:
        ns = [math.ceil(x * sf / gs) * gs for x in imgs.shape[2:]]  # new shape (stretched to gs-multiple)
        imgs = F.interpolate(imgs, size=ns, mode='bilinear', align_corners=False)
```

Output:
```
Traceback (most recent call last):
  File "train.py", line 477, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 288, in train
    sz = random.randrange(imgsz * 0.5, imgsz * 1.5 + gs) // gs * gs  # size
AttributeError: 'builtin_function_or_method' object has no attribute 'randrange'
```

## Expected behavior
It should train normally, if
```
from random import random
```
is changed to
```
import random
```
everything works fine

Or since you've moved to all explicit imports it's probably correct to import choices and randrange only from random.

## Environment
 - OS:  Ubuntu
 - GPU Tesla V100
 - Python 3.8.2

**Comment by glenn-jocher** [comment]
@lorenzomammana thank you buddy! Can you submit a PR with your proposed fix please?

We just had a PR that modified some imports, it may have broken this functionality.

**Comment by glenn-jocher** [comment]
@Pluto1314 this should be resolved now in https://github.com/ultralytics/yolov5/commit/eb99dff9ef4f6f2c26e6cda2f6fe1abfabce8929. Please git pull and try again.

**Comment by glenn-jocher** [comment]
Will close, please advise if problem persists.
