### ISSUE TITLE
Yolov5 Exclude & Include

### ISSUE THREAD

**Issue by Alistar989** [ultralytics/yolov5#6150]
Hello, I'm a beginner to Yolov5 and Google Colab. 
I'm trying to train the dataset in the default Yolov5 page in Google Colab. But I want to exclude some of the classes there. 
There are by default many classes to start with, each with a 128 training images. So if I want to exclude some of these classes, what's the code in order to do so? and in which section should I put it?

**Comment by glenn-jocher** [comment]
@Alistar989 you can update the code here to filter classes from your dataset:

https://github.com/ultralytics/yolov5/blob/d95978a562bec74eed1d42e370235937ab4e1d7a/utils/datasets.py#L447-L448

**Comment by almgwary** [comment]
> filter labels to include only these classes

It is not working with me while rurnning detect.py
```
  include_class = [1,2,3,4,6,8,17,18,19,20,21 ]  # filter labels to include only these classes (optional)
        include_class_array = np.array(include_class).reshape(1, -1)
        for i, (label, segment) in enumerate(zip(self.labels, self.segments)):
```

**Comment by glenn-jocher** [comment]
@almgwary it looks like you are trying to filter classes using the `detect.py` script, but the code snippet provided will not affect the detected classes. To filter classes during detection, you can modify the `filter()' function in `detect.py` to include only the classes you are interested in. Also, ensure that the modified colors in the `detect.py` script align with the class indices after exclusion.
