### ISSUE TITLE
Further training a model's classes

### ISSUE THREAD

**Issue by HeChengHui** [ultralytics/yolov5#6154]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am trying out YoloV5m6 trained on the VisDrone dataset using `--data VisDrone.yaml`.  I am curious about how the classes would be handled in this case?

* m6 has 80 classes while VisDrone.yaml stated 10
* The ordering & names are also different:
yolo: `person, bicycle, car,...`
visdron: `pedestrian, people, bicycle,...`

What would happen to the resulting model's classes in this case?

**Comment by glenn-jocher** [comment]
@HeChengHui class differences are handled automatically by YOLOv5 when starting from pretrained weights. You can start training VisDrone from COCO-pretrained weights like this:

```bash
python train.py --data VisDrone.yaml --weights yolov5s.pt
```

**Comment by HeChengHui** [comment]
@glenn-jocher Thank you for the clarification!

**Comment by HeChengHui** [comment]
@glenn-jocher 
Another thing I would like to clarify: After training, what would happen to the old classes?

Example:
yolov5m6 has 80 classes initially, so it can detect 80 different types of objects. After additional training with VisDrone dataset, the model changes to 10 classes as previously mentioned. 
1) Does that mean for classes that are not in the 10, it will not be detected but the weights for those classes are still present inside the model? 
2) For classes that are in both datasets, will the weights for that class in the baseline model be further trained with the new images from VisDrone?

**Comment by glenn-jocher** [comment]
@HeChengHui models output layers are recreated for the class count of the new dataset you train on.
