### ISSUE TITLE
Yolov5s onnx export but with required output format

### ISSUE THREAD

**Issue by sezer-muhammed** [ultralytics/yolov5#6155]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,
I need to run yolov5s on jetson nano, I know jetson can run directly pth file but I want to do it with onnx file.

I convert yolov5s model into onnx file without any problem, and I can run it on jetson nano.

But problem is output type

![Screenshot from 2022-01-02 15-33-21](https://user-images.githubusercontent.com/74321576/147875844-d85d33e9-02b8-463c-b6b1-92aac0479a2c.png)
.

As you can see in image, yolov5 has a output with size 1*14k*85
but example model that compatible with jetson inference library from dusty_nv has an output with scores and boxes.

This causes problem because I guess they coded in this way, so I need to turn yolov5 into this format. 

Normally I would change models output layer but yolov5s is a bit complicated for me.

So how can I achieve this?

thanks

**Comment by d57montes** [comment]
The yolov5 model output still needs to be post-processed: this includes non-max-suppression among other things. You can see #708 that talks about this. I believe they link some other issues that discusses this even more. 
However, you can get get combined non-max-suppression in your ONNX model by following the workflow described in #5938.

**Comment by sezer-muhammed** [comment]
Thanks a lot!
