### ISSUE TITLE
Changing imgsz doesnt work

### ISSUE THREAD

**Issue by yagizzha** [ultralytics/yolov5#6156]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

detect: weights=yolov5s.pt, source=2, data=data\coco128.yaml, imgsz=[720, 1280], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs\detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False
YOLOv5  2022-1-1 torch 1.10.1+cu113 CUDA:0 (NVIDIA GeForce GTX 1080, 8192MiB)

Fusing layers...
Model Summary: 213 layers, 7015519 parameters, 0 gradients, 15.8 GFLOPs
WARNING: --img-size [720, 1280] must be multiple of max stride 32, updating to [736, 1280]
1/1: 2...  Success (inf frames 640x480 at 30.00 FPS)

0: 736x992 Done. (1.183s)
0: 736x992 Done. (0.012s)
0: 736x992 Done. (0.012s)

i use a camera that can go over 640x480 , but cant do that within the code 

### Environment

yolov5 master
gtx1080 
windows 10
logitech webcam

### Minimal Reproducible Example

either with --imgsz or through changing default , same result

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by yagizzha** [comment]
![image](https://user-images.githubusercontent.com/88779645/147879597-2ef07d1d-5f45-4781-b0a1-6a5e16a52133.png)
Yet 
![image](https://user-images.githubusercontent.com/88779645/147879604-4ab0f0cb-fb6d-43ac-8ce5-ed5503f0d9b1.png)
thats shortest copy i can get
i pick 720p but get automatically turned to 480

**Comment by glenn-jocher** [comment]
@yagizzha the Success line is printing info about your streaming source, the image size there is a source property and not modifiable.

--imgsz controls the **inference** size.

**Comment by SpongeBab** [comment]
@yagizzha the Success line is just printing the img-size of your video.It does not affect the inference size.video
@glenn-jocher Maybe we can change the line to like 'video frames 640x480,inference size 1280x640'.Show more info.

**Comment by yagizzha** [comment]
i see , how can i change my camera resolution ? , i couldnt see the option and im sure mine can go over 480p ?
