### ISSUE TITLE
Crop and save bounding box libtorch c++. I found yolov4 can do and any for yolov5 in c++

### ISSUE THREAD

**Issue by problemSolvingProgramming** [ultralytics/yolov5#6159]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,
I need help to edit detect.py for crop bounding boxes (detected object) as separate image. and save them in specific directory.
Crop and save bounding box libtorch c++. I found yolov4 can do and any for yolov5 in c++

**Comment by d57montes** [comment]
I believe that detect.py has a —save-crop option that does just that. And you can use —project and —name to modify the save location.

**Comment by glenn-jocher** [comment]
@problemSolvingProgramming use `--save-crop` as @d57montes said

**Comment by SpongeBab** [comment]
yes,if you just want result to save. You can use the --save-crop option.

If you want to save the result in your custom c++ code project. You must do it by yourself.

**Comment by problemSolvingProgramming** [comment]
@d57montes @SpongeBab 

Hi, I want to add crop and save bounding box libtorch c ++ to the following code, but unfortunately I do not know exactly, I can crop one person, but if there are several objects in an image, I can not crop or save them with different boundix. Thank you very much for helping us or writing the code.?

https://github.com/Nebula4869/YOLOv5-LibTorch
