### ISSUE TITLE
About COCO class label map

### ISSUE THREAD

**Issue by twangnh** [ultralytics/yolov5#616]
Hi! Thanks for the wonderful project! I have a basic question about the label map, yolov5 load preprocessed train.txt file which has class labels of each box, but the original COCO class number is lost, I'm wondering if you could share where to find the label map for mapping the current 0-80 classes to original 90 classes?

**Comment by glenn-jocher** [comment]
You can find this here:
https://github.com/ultralytics/yolov5/blob/d5b6416c87cc37fbb7a73d74e7fcaaea7d3c02d6/utils/general.py#L164-L174

**Comment by twangnh** [comment]
Thank you for pointing out!

**Comment by glenn-jocher** [comment]
You pass in your COCO class indices (80 classes) and it returns you the correct 91-count index.
