### ISSUE TITLE
about confusion matrix

### ISSUE THREAD

**Issue by shenhaibb** [ultralytics/yolov5#6163]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

![Feature_resued_C3RDB_pyramid](https://user-images.githubusercontent.com/64736467/147895815-fe8c4b30-cf93-4689-ba70-78a4463f7415.jpg)
![confusion_matrix](https://user-images.githubusercontent.com/64736467/147895821-6ace83b4-8043-4bcb-ba42-7383474dbb25.png)
These are my results from the same weight file.
What I want to ask is what data the diagonal value of the confusion matrix corresponds to？ (data is the value of each class after running val.py)

**Comment by glenn-jocher** [comment]
@shenhaibb this is a True vs Predicated confusion matrix. Each column is normalized. See https://en.wikipedia.org/wiki/Confusion_matrix

The code is here:
https://github.com/ultralytics/yolov5/blob/968e30065aa1ccbebc42d1a19fd48f2aebc5cf52/utils/metrics.py#L117-L199
