### ISSUE TITLE
IOU Threshold and Anchor Box sizes

### ISSUE THREAD

**Issue by wajhh** [ultralytics/yolov5#6166]
Hi I wanna ask that how can we find the iou threshold of our results and how do we get to see the anchor box sizes ? Please guide or leave your email se I can personally contact you thanks

**Comment by glenn-jocher** [comment]
@wajhh YOLOv5 🚀 anchors are saved as [Detect()](https://github.com/ultralytics/yolov5/blob/f17c86b7f0d2038288d7292cb82dec2433cc91e5/models/yolo.py#L33-L70) layer attributes on model creation, and updated as necessary by AutoAnchor before training starts. Their exact location is here:
https://github.com/ultralytics/yolov5/blob/f17c86b7f0d2038288d7292cb82dec2433cc91e5/models/yolo.py#L45

You can examine the anchors of any trained YOLOv5 model like this:

### Input
```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', autoshape=False)  # official model
model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt',  autoshape=False)  # custom model

# Anchors
m = model.model[-1]  # Detect() layer
print(m.anchors * m.stride.view(-1, 1, 1))  # print anchors
```

### Output
```python
YOLOv5 🚀 2021-11-22 torch 1.10.0+cu111 CUDA:0 (Tesla V100-SXM2-16GB, 16160MiB)
#           x     y
tensor([[[ 10.,  13.],
         [ 16.,  30.],
         [ 33.,  23.]],  # P3/8-small

        [[ 30.,  61.],
         [ 62.,  45.],
         [ 59., 119.]],  # P4/16-medium

        [[116.,  90.],
         [156., 198.],
         [373., 326.]]], dtype=torch.float16)  # P5/32-large
```

Good luck 🍀 and let us know if you have any other questions!

**Comment by wajhh** [comment]
> @wajhh YOLOv5 🚀 anchors are saved as [Detect()](https://github.com/ultralytics/yolov5/blob/f17c86b7f0d2038288d7292cb82dec2433cc91e5/models/yolo.py#L33-L70) layer attributes on model creation, and updated as necessary by AutoAnchor before training starts. Their exact location is here:
> 
> https://github.com/ultralytics/yolov5/blob/f17c86b7f0d2038288d7292cb82dec2433cc91e5/models/yolo.py#L45
> 
> You can examine the anchors of any trained YOLOv5 model like this:
> 
> ### Input
> ```python
> import torch
> 
> # Model
> model = torch.hub.load('ultralytics/yolov5', 'yolov5s', autoshape=False)  # official model
> model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt',  autoshape=False)  # custom model
> 
> # Anchors
> m = model.model[-1]  # Detect() layer
> print(m.anchors * m.stride.view(-1, 1, 1))  # print anchors
> ```
> 
> ### Output
> ```python
> YOLOv5 🚀 2021-11-22 torch 1.10.0+cu111 CUDA:0 (Tesla V100-SXM2-16GB, 16160MiB)
> #           x     y
> tensor([[[ 10.,  13.],
>          [ 16.,  30.],
>          [ 33.,  23.]],  # P3/8-small
> 
>         [[ 30.,  61.],
>          [ 62.,  45.],
>          [ 59., 119.]],  # P4/16-medium
> 
>         [[116.,  90.],
>          [156., 198.],
>          [373., 326.]]], dtype=torch.float16)  # P5/32-large
> ```
> 
> Good luck 🍀 and let us know if you have any other questions!

**Comment by wajhh** [comment]
@glenn-jocher thank you for your reply, I will definitely look into this and get back to you if this was helpful. Can you please let me know that iou threshold is the only one in detect.py or do we get any other iou threshold after the outcomes ?

**Comment by wajhh** [comment]
@glenn-jocher thank you for your reply, I will definitely look into this and get back to you if this was helpful. Can you please let me know that iou threshold is the only one in detect.py or do we get any other iou threshold after the outcomes ?

**Comment by jaideep11061982** [comment]
> @wajhh YOLOv5 🚀 anchors are saved as [Detect()](https://github.com/ultralytics/yolov5/blob/f17c86b7f0d2038288d7292cb82dec2433cc91e5/models/yolo.py#L33-L70) layer attributes on model creation, and updated as necessary by AutoAnchor before training starts. Their exact location is here:
> 
> https://github.com/ultralytics/yolov5/blob/f17c86b7f0d2038288d7292cb82dec2433cc91e5/models/yolo.py#L45
> 
> You can examine the anchors of any trained YOLOv5 model like this:
> 
> ### Input
> ```python
> import torch
> 
> # Model
> model = torch.hub.load('ultralytics/yolov5', 'yolov5s', autoshape=False)  # official model
> model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt',  autoshape=False)  # custom model
> 
> # Anchors
> m = model.model[-1]  # Detect() layer
> print(m.anchors * m.stride.view(-1, 1, 1))  # print anchors
> ```
> 
> ### Output
> ```python
> YOLOv5 🚀 2021-11-22 torch 1.10.0+cu111 CUDA:0 (Tesla V100-SXM2-16GB, 16160MiB)
> #           x     y
> tensor([[[ 10.,  13.],
>          [ 16.,  30.],
>          [ 33.,  23.]],  # P3/8-small
> 
>         [[ 30.,  61.],
>          [ 62.,  45.],
>          [ 59., 119.]],  # P4/16-medium
> 
>         [[116.,  90.],
>          [156., 198.],
>          [373., 326.]]], dtype=torch.float16)  # P5/32-large
> ```
> 
> Good luck 🍀 and let us know if you have any other questions!

@glenn-jocher  
1)how does these anchors  change wrt anchors_T hyper param. 

2) Does this value used while building them ?
3) default is 4 ,if i inrease it to say 8 how does anchors size will vary

**Comment by glenn-jocher** [comment]
@jaideep11061982 I don't know. Why don't you just change the hyperparameter and observe the effect on AutoAnchor?
