### ISSUE TITLE
How I can count objects using yolov5

### ISSUE THREAD

**Issue by mehar50** [ultralytics/yolov5#6167]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I trained yolov5 on my custom dataset, more specifically my goal is to count roadside trees, which perfectly works for detection. Now I want to count these trees like if a tree remains in more than one frame it should not be counted multiple times.. I'll be grateful if someone can help me in this regard... Thank you for reading this

**Comment by KristofferK** [comment]
You could take a look at the multiple object-tracking algorithm Deep SORT. Articlies like [Real Time Pear Fruit Detection and Counting Using YOLOv4 Models and Deep SORT](https://www.mdpi.com/1424-8220/21/14/4803) have successfully used Deep SORT together with YOLOv4, so I assume it would also be possible to use it with YOLOv5.

**Comment by ghost** [comment]
maybe this helps you, even if it is for yolov4 

https://www.youtube.com/watch?v=jDwC5m7c7BU

**Comment by glenn-jocher** [comment]
@mehar50 👋 Hello! Thanks for asking about object **tracking** in computer vision. YOLOv5 🚀 is an object **detector** that detect, localizes and classifies objects in a single image. It does not connect objects across multiple images, for this you need a tracking solution. A few possible tracking solutions are:

- **Extended Kalman Filter (EKF)**: https://en.wikipedia.org/wiki/Kalman_filter
- **KLT tracker**: https://en.wikipedia.org/wiki/Kanade%E2%80%93Lucas%E2%80%93Tomasi_feature_tracker
- **YOLOv5 DeepSort tracker**: https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch

Good luck 🍀 and let us know if you have any other questions!

**Comment by ghost** [comment]
@mehar50 

sorry, i misread your question. actually i also try to count objects on a single image of mine. how could you count the detected objects by classes? could you share your code please?
