### ISSUE TITLE
non-maxima-suppresseon doesn't work

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#6170]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,

I'm detecting irregulations on an image. Unfortunally the non-maxima-suppresseon doesn't work, and irregulations on an image are being detected several times.

How can I adjust the settings for these?

Thanks in advance

**Comment by glenn-jocher** [comment]
@G-Rizzle see detect.py argparser for available arguments:
https://github.com/ultralytics/yolov5/blob/968e30065aa1ccbebc42d1a19fd48f2aebc5cf52/detect.py#L216-L248

**Comment by ghost** [comment]
Hi Glenn, thank you.

I already found this, but can't really see where it is about non-maxima suppression. Is there a full documentation? I found this:

https://docs.ultralytics.com/

but that is not very helpfull, in my eyes it is not a proper documentation

**Comment by glenn-jocher** [comment]
@G-Rizzle yes we need to improve our docs! @kalenmike 

i.e. the main arguments for NMS are --conf, --iou, --agnostic, --classes etc.

The NMS function is here:
https://github.com/ultralytics/yolov5/blob/5344e54da6aa5f40fc20115c672f29c96d7827cd/utils/general.py#L647-L669

**Comment by ghost** [comment]
@glenn-jocher thanks a lot! I will try
