### ISSUE TITLE
torchscript export: success on yolov5s and bad results on yolov5m

### ISSUE THREAD

**Issue by galAcarteav** [ultralytics/yolov5#6175]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Export

### Bug

Hey,
First thank you for your amazing work!
I was trained yolov5m6 on custom data and its several day's that I'm stuck on exporting to torchscript phase.
I'm trying to run inference via c++ libtorch, when I'm running on my laptop(rtx 2060, cuda 11.3) everything work fine,
but when running on the deployment PC(gtx 1650) getting some different results for different runs:
1) yolov5m, cuda 11.3, libtorch-cxx11-abi-shared-with-deps-1.10.0+cu113: inference run but the model cant detect anything
2) yolov5m, cuda 10.2, libtorch-cxx11-abi-shared-with-deps-1.10.1+cu102: inference run, there is detections but post-process takes 160ms vs 4ms of inference (torch::masked_select takes too long)
3) yolov5m, cuda 10.2, libtorch from source inference run, there is detections but post-process takes 110ms vs 10ms of inference
4) yolov5s, cuda 10.2, libtorch from source: everything for fine in realtime(camera produce 30fps)

**the python .pt works fine with any cuda version

any ideas what can cause this?

### Environment

YOLOv5 🚀 v6.0-163-gd95978a torch 1.10.1+cu102 CUDA:0 (NVIDIA GeForce GTX 1650, 3912MiB)
OS: ubuntu 20.04
python: 3.8.10

### Additional

For libtorch inference I've adopt and modified the code from : https://github.com/yasenh/libtorch-yolov5 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@galAcarteav this code works correctly for me, though I wasn't able to run GPU inference.

```bash
!python export.py --weights yolov5s.pt yolov5m.pt --include torchscript
!python detect.py --weights yolov5s.torchscript --device cpu
!python detect.py --weights yolov5m.torchscript --device cpu
```

NMS times are both about 1ms per image, so I don't know what you mean by high post processing times.

<img width="1524" alt="Screen Shot 2022-01-03 at 10 15 05 AM" src="https://user-images.githubusercontent.com/26833433/147965002-27a75083-061e-41e7-aaba-d289ed89125a.png">

**Comment by glenn-jocher** [comment]
@galAcarteav just realized you are using a 3rd party repo. Obviously if your issue relates to inference with that repo, raise your issue there not here.

**Comment by galAcarteav** [comment]
@glenn-jocher Thanks for the checking and I'm agree with you, more appropriate to label this as a question rather then as a bug.
did you (or someone) ever experienced with something like this before or have any ideas how to target the issue?
also, do you know more recommended c++ library/framework then libtorch for deployment?

**Comment by glenn-jocher** [comment]
@galAcarteav unfortunately I don't have much C++ experience myself so can't help you there right now. The models should behave identically, except YOLOv5m is larger than YOLOv5s and so will require more resources and time to run.

It would be nice to have detect.py run these directly on GPU though, I'd like to fix that. I'll put a TODO here for that bug.

**Comment by glenn-jocher** [comment]
TODO: Run TorchScript models on GPU

**Comment by glenn-jocher** [comment]
@galAcarteav ah, I just forgot that TorchScript models must be exported on GPU in order for detect.py to run them correctly on GPU. The following works correctly:

```bash
!python export.py --weights yolov5s.pt yolov5m.pt --include torchscript --device 0
!python detect.py --weights yolov5s.torchscript --device 0
!python detect.py --weights yolov5m.torchscript --device 0
```

Inference runs on GPU now, but the second image is very slow, even though it's the same size as the first image. Strange:

<img width="857" alt="Screen Shot 2022-01-03 at 12 12 35 PM" src="https://user-images.githubusercontent.com/26833433/147975714-ed1ceef8-1418-4db3-a5d4-7860ca867e39.png">

**Comment by glenn-jocher** [comment]
@galAcarteav I added more images and now everything is fine after the first 2. So just a warmup issue. Times are 7 and 11 ms per image for YOLOv5s and m TorchScript models at 640. Not bad.

<img width="1269" alt="Screen Shot 2022-01-03 at 12 15 33 PM" src="https://user-images.githubusercontent.com/26833433/147975868-0c3c525f-7cf8-4609-8912-f844568661a9.png">

**Comment by galAcarteav** [comment]
@glenn-jocher Thank you for amazing support!(even its not related to your code..)
I also check with yolov5l on torchscript c++ and its work fine, the issue(slow post-process on c++ torch and not detect anything)
just occur on the yolov5m exported model.
I can see that there is a difference at the last layer of the models, the s/l are same but the m one is different, attaching image..
this telling something to you?

yolov5m: 
![torchscript_yolov5m](https://user-images.githubusercontent.com/79792005/148046795-209fcc92-a772-4a05-ace3-62b1b44083c7.png)

yolov5s:
![torchscript_yolov5s png](https://user-images.githubusercontent.com/79792005/148046953-42fd29b3-a6b9-4c9f-9555-89db0f4c0711.png)
yolov5l:
![torchscript_yolov5l](https://user-images.githubusercontent.com/79792005/148047091-871e9d3b-8626-47a5-af00-a4c464410533.png)

**Comment by glenn-jocher** [comment]
@galAcarteav you are not showing YOLOv5m, you are showing YOLOv5m6. This is the YOLOv5m P6 model with 4 output heads. See v5.0 release notes for details on P6 models.

https://github.com/ultralytics/yolov5/releases/tag/v5.0
