### ISSUE TITLE
An error occurred while running train.py

### ISSUE THREAD

**Issue by Muuuri21** [ultralytics/yolov5#6176]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\torchvision\io\image.py:11: UserWarning: Failed to load image Python extension: Could not find module 'C:\Users\Administrator\AppData\Local\Programs\Python\Python39\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
  warn(f"Failed to load image Python extension: {e}")

### Environment

torch                     1.10.1+cu102
torchaudio                0.10.1+cu102
torchvision               0.11.2+cu102

win10
rtx2080s
CUDA 10.2

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Laomao7 it appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual [Python 3.9](https://www.python.org/) environment, clone the latest repo ([code changes daily](https://github.com/ultralytics/yolov5/commits/master)), and `pip install` [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) again from scratch.

💡 ProTip! Try one of our verified environments below if you are having trouble with your local environment.


## Requirements

[**Python>=3.6.0**](https://www.python.org/) with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) installed including [**PyTorch>=1.7**](https://pytorch.org/get-started/locally/). To get started:
```bash
git clone https://github.com/ultralytics/yolov5  # clone
cd yolov5
pip install -r requirements.txt  # install
```

[Models](https://github.com/ultralytics/yolov5/tree/master/models) and [datasets](https://github.com/ultralytics/yolov5/tree/master/data) download automatically from the latest YOLOv5 [release](https://github.com/ultralytics/yolov5/releases) when first requested.

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), validation ([val.py](https://github.com/ultralytics/yolov5/blob/master/val.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/export.py)) on MacOS, Windows, and Ubuntu every 24 hours and on every commit.

**Comment by pankaja0285** [comment]
* I git cloned your repo
* I did create a Python venv and installed requirements.txt
I was getting Cuda unavailable, so I followed your downgrade advice for torch and torchvision but now I get Memory Error with no proper explanation of the error
My env is Python 3.9.8 and I run the repo in a Pycharm env - terminal. My laptop is a Windows 10 laptop with NVIDIA GPU, CUDA and cuDNN installed.

**Comment by glenn-jocher** [comment]
@pankaja0285 see https://pytorch.org/get-started/locally/

**Comment by Muuuri21** [comment]
> @Laomao7看来你可能有环境问题。如果您尝试在本地运行 YOLOv5，请确保您满足所有依赖项要求。如果有疑问，创建一个新的虚拟[的Python 3.9](https://www.python.org/)环境，克隆最新的回购（[代码每天都在改变](https://github.com/ultralytics/yolov5/commits/master)），并`pip install` [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt)从头。
> 
> 💡专家提示！如果您的本地环境有问题，请尝试我们在下面验证的环境之一。
> 
> ## 要求
> [**Python>=3.6.0**](https://www.python.org/)安装了所有[requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt)包括[**PyTorch>=1.7**](https://pytorch.org/get-started/locally/)。开始：
> 
> ```shell
> git clone https://github.com/ultralytics/yolov5   # clone 
> cd yolov5
> pip install -r requirements.txt   #安装
> ```
> 
> [模型](https://github.com/ultralytics/yolov5/tree/master/models)和[数据](https://github.com/ultralytics/yolov5/tree/master/data)集会在首次请求时从最新的 YOLOv5[版本](https://github.com/ultralytics/yolov5/releases)自动下载。
> 
> ## 环境
> YOLOv5 可以在以下任何经过验证的最新环境中运行（所有依赖项包括[CUDA](https://developer.nvidia.com/cuda) / [CUDNN](https://developer.nvidia.com/cudnn)、[Python](https://www.python.org/)和[PyTorch](https://pytorch.org/)预装）：
> 
> * ****带有免费 GPU 的**Google Colab 和 Kaggle**笔记本：[![在 Colab 中打开](https://camo.githubusercontent.com/84f0493939e0c4de4e6dbe113251b4bfb5353e57134ffd9fcab6b8714514d4d1/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb) [![在 Kaggle 中打开](https://camo.githubusercontent.com/a08ca511178e691ace596a95d334f73cf4ce06e83a5c4a5169b8bb68cac27bef/68747470733a2f2f6b6167676c652e636f6d2f7374617469632f696d616765732f6f70656e2d696e2d6b6167676c652e737667)](https://www.kaggle.com/models/ultralytics/yolov5)
> * **谷歌云**深度学习虚拟机。请参阅[GCP 快速入门指南](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
> * **亚马逊**深度学习 AMI。请参阅[AWS 快速入门指南](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
> * **码头工人形象**。请参阅[Docker 快速入门指南](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) [![Docker 拉动](https://camo.githubusercontent.com/280faedaf431e4c0c24fdb30ec00a66d627404e5c4c498210d3f014dd58c2c7e/68747470733a2f2f696d672e736869656c64732e696f2f646f636b65722f70756c6c732f756c7472616c79746963732f796f6c6f76353f6c6f676f3d646f636b6572)](https://hub.docker.com/r/ultralytics/yolov5)
> 
> ## 地位
> ![CI CPU 测试](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)
> 
> 如果此标志为绿色，则所有[YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions)持续集成 (CI) 测试当前都通过。CI 测试每 24 小时和每次提交验证YOLOv5 训练 ( [train.py](https://github.com/ultralytics/yolov5/blob/master/train.py) )、验证 ( [val.py](https://github.com/ultralytics/yolov5/blob/master/val.py) )、推理 ( [detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py) ) 和导出 ( [export.py](https://github.com/ultralytics/yolov5/blob/master/export.py) ) 在 MacOS、Windows 和 Ubuntu 上的正确操作。

thanks

I reinstalled python3.7.8 and yolov5 and cuda10.2

The real cause of the error should be torch and torchvision

![1641299011(1)](https://user-images.githubusercontent.com/35321224/148058573-4b16441f-6c85-4ff5-ae9a-29b2ba69db65.jpg)


![image](https://user-images.githubusercontent.com/35321224/148059140-ab17d26f-ebed-41bd-8bdb-4a3355ff2d70.png)


pip install torch==1.9.0+cu102 torchvision==0.10.0+cu102 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by pderrenger** [comment]
It seems like you've identified the issue with `torch` and `torchvision`. Make sure your CUDA version matches the PyTorch version you're installing. If you continue to face issues, consider using a verified environment like Google Colab for a smoother experience.
