### ISSUE TITLE
Constraints Regarding sizes of images

### ISSUE THREAD

**Issue by GlitchBox** [ultralytics/yolov5#618]
## ❔Question
Can I have images of numerous different sizes in my training set?
What do I do if I have to run inference on images of variable sizes?

**Comment by glenn-jocher** [comment]
@GlitchBox you can train and detect on any size or shape images you want, in any combination. I would recommend you do so at similar train and detect sizes for best results.

**Comment by GlitchBox** [comment]
@glenn-jocher When you say 'in any combination', what do you mean? I understand that I can train on images of any size. But does that mean I can have both 1024x1024 and 1280x1280 images in trainset? Or do I have to resize all the images to either of the sizes(1024 or 1280)?
In the case that I don't have to resize images, what will the argument 'img_size' be? 1024 or 1280?

**Comment by glenn-jocher** [comment]
> @GlitchBox you can train and detect on any size or shape images you want

**Comment by AmirHosseinCV** [comment]
I have a similar problem. 50% of images are about 1080p and 50% of them are about 360p and I can't resize them (Large objects in small images and small objects in large images). A solution is using `batch_size=1` and do not resize them, but It's not good. Is there a simple solution or I should change the code?

**Comment by glenn-jocher** [comment]
@AmirIR train with default settings.

**Comment by AmirHosseinCV** [comment]
> @AmirIR train with default settings.

It resizes all images to 640 [(here)](https://github.com/ultralytics/yolov5/blob/c8c5ef36c9a19c7843993ee8d51aebb685467eca/train.py#L388)

**UPDATE:** I solved the problem by customizing the **multi-scale training** feature. Thanks a lot!
