### ISSUE TITLE
Ask for the start and end timestamps of FPS

### ISSUE THREAD

**Issue by wulele2** [ultralytics/yolov5#6184]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I would like to ask if the FPS of the model is from image reading to model reasoning and then to NMS? thank u very much。

**Comment by Zengyf-CVer** [comment]
@wulele2 
formula:
1000/inference time (ms)
