### ISSUE TITLE
Training with a single class

### ISSUE THREAD

**Issue by jhl13** [ultralytics/yolov5#6187]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Thanks for this great work!
I have a question about the class loss. Why does yolov5 calculate class loss only if multiple classes?
Parameters associated with the category are not updated in the Detect?

**Comment by glenn-jocher** [comment]
@jhl13 there's no point in computing class loss if there is only a single class. Why would you want to?

**Comment by bilzard** [comment]
I'm also interesting to the topic.

It depends on the model design, but in general, class loss in single class can suppress negative prediction. 

Suppose probability of the detection is calculated by `P(detect) = confidence * P(class)`. If a predicted bounding box has lower IoU to any of the ground truth bounding boxes, lowering the class probability `P(class)` can lower the probability of the detection `P(detect)`.

If Yolov5 detect object based only on confidence value after selecting maximum class probability, the class loss in the single class do nothing for the detection.

My question is:

1. Does yolov5 calculates detection probability only on confidence value: ` P(detect) = confidence`?
2. If question 1 is true, how does yolov5 can suppress negative detection?

**Comment by glenn-jocher** [comment]
@bilzard see YOLOv3 paper for discussion on loss components: https://arxiv.org/abs/1804.02767
