### ISSUE TITLE
Validate with original Img size

### ISSUE THREAD

**Issue by jaideep11061982** [ultralytics/yolov5#6188]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I train my image using Random Crop of albumentation. without a resize Crop size X,Y drawn from original image of X1,Y1. I  want to then validate on actual Image scale without resize  (original image size say X1,Y1) . How  i can do so. Currently inference is drawn as per img size that we provide in parameters of yolo so internally Yolo may be doing a resize  , changing the scale of image compared to scale of Trained Crop resulting into bad results.. 

Can you please help  @glenn-jocher

**Comment by glenn-jocher** [comment]
@jaideep11061982 use the --imgsz argument in val.py to set any inference size you want. The single value you pass is the long side, i.e. if you want to run inference on a 4k image at 3840x1920, pass `--imgsz 3840`.

**Comment by jaideep11061982** [comment]
Thanks @glenn-jocher 
Let me tell my case.
My img size  is 720 by 1280. 

My Requirement is to give Non Resized images to Aug Pipeline of Albumentation . 

I know there is parameter call --rect , image-weights  that are to be passed , but even then I see Logs showing Val/Train size=img-size we pass . 
I think ` img, (h0, w0), (h, w) = load_image(self, index)  `resize images to img-sz 

1)
 I am trying to figure out  what  sizes does this self.shapes  has. 
```
if self.rect:
            # Sort by aspect ratio
            s = self.shapes  # wh
            ar = s[:, 1] / s[:, 0]  # aspect ratio
            irect = ar.argsort()
            self.img_files = [self.img_files[i] for i in irect]
            self.label_files = [self.label_files[i] for i in irect]
            self.labels = [self.labels[i] for i in irect]
            self.shapes = s[irect]  # wh
            ar = ar[irect]

            # Set training image shapes
            shapes = [[1, 1]] * nb
            for i in range(nb):
                ari = ar[bi == i]
                mini, maxi = ari.min(), ari.max()
                if maxi < 1:
                    shapes[i] = [maxi, 1]
                elif mini > 1:
                    shapes[i] = [1, 1 / mini]

            self.batch_shapes = np.ceil(np.array(shapes) * img_size / stride + pad).astype(np.int) * stride
```

then in get_items

we have this

```
 if mosaic:
            # Load mosaic
            img, labels = load_mosaic(self, index)
            shapes = None

            # MixUp augmentation
            if random.random() < hyp['mixup']:
                img, labels = mixup(img, labels, *load_mosaic(self, random.randint(0, self.n - 1)))

 else:
            # Load image
            img, (h0, w0), (h, w) = load_image(self, index)

            # Letterbox
            shape = self.batch_shapes[self.batch[index]] if self.rect else self.img_size  # final letterboxed shape
```

2)  I dont know what is shape value if rect is true

Also
` shapes = (h0, w0), ((h / h0, w / w0), pad)  # for COCO mAP rescaling`
if rect is True, here h/w will  be img size value   

Will that still be needed ?

**Comment by glenn-jocher** [comment]
@jaideep11061982 sure, you can do `python train.py --img 1280` in your case then. 

You can also update your hyp file to reduce or eliminate augmentations like scale jitter etc.
