### ISSUE TITLE
Where to find specific console-print?

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#6190]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,

the custom-object detection works fine for me. Now I want to count the number of objects by class the NN detectet.
In the console I see following print:
"Model Summary: 213 layers, 7015519 parameters, 0 gradients, 15.8 GFLOPs
image 1/1 C:\Users\********\uni\MA\Programmierung\ai\yolov5-master\data\images\3d.png: 448x640 34 Ballings, Done. (0.183s)"

where is this print coming from? And where is it taking its information ("34 Ballings") from?

Thanks in advance

**Comment by KristofferK** [comment]
Balling would be the name of the class. It found 34 objects with the class Balling in the 3d.png picture during inference.

The print statement is here https://github.com/ultralytics/yolov5/blob/fb839298a16fca4143dc70619a084f9ed085ac07/detect.py#L179

The 34 Ballings comes from https://github.com/ultralytics/yolov5/blob/fb839298a16fca4143dc70619a084f9ed085ac07/detect.py#L161
