### ISSUE TITLE
If my dataset has only one class and I have set nc=1 and the class name successfully, do I  need to set "-- single-CLS:"to true?

### ISSUE THREAD

**Issue by mzzjuve** [ultralytics/yolov5#6191]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

thank you for your outstanding work!

If my dataset has only one category and I have set nc=1, do I  need to set "-- single-CLS "to be true or just keep it false?

**Comment by glenn-jocher** [comment]
@mzzjuve no. --single-cls is for forcing multi-class datasets into a single-class configuration.
