### ISSUE TITLE
Why Objectness Loss is Scaled with Image Size?

### ISSUE THREAD

**Issue by bilzard** [ultralytics/yolov5#6192]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

According to train.py[1], objectness loss gain is multiplied by squared image size.
I searched PR and Issues, but I can't find the reason.
Can anyone show me the reason why this is necessary?

[1] https://github.com/ultralytics/yolov5/blob/master/train.py#L261

Seeing utils/loss.py[2], objectness loss is just a BCE loss between IoU and confidence value.
Therefore, when the downstream task's objective is metric based on IoU like mAP, I think scaling isn't necessary.
Am I misunderstanding?

[2] https://github.com/ultralytics/yolov5/blob/master/utils/loss.py#L155

**Comment by glenn-jocher** [comment]
@bilzard objectness suffers from an extreme imbalance between positive and negative samples. When an image is scaled up, the object count inside it remains the same, so the imbalance increases (gets worse). The loss gain is scaled to compensate.

This is part of the automatic adjustments we do that help users get a better result on their custom datasets the first time.

**Comment by bilzard** [comment]
@glenn-jocher Thanks for the quick response as usual.

> objectness suffers from an extreme imbalance between positive and negative samples.

Yes. This is tend to be true for the large image, but does this depend on the dataset?
I think in some case this will never be observed: for example, the user just resize the original image (eg. 320 -> 640), or using high resolution image etc.

I also wander why the gain is scaled proportional to squared image size? Are there any paper or experiments that supports this scaling rule?

**Comment by glenn-jocher** [comment]
@bilzard loss scales with output size

**Comment by bilzard** [comment]
@glenn-jocher You mean Objectiveness Loss scales with proportional to `image_size ** -2`?

FYI: Currently, I runs experiments with custom datasets, cropping in different size:

1. original: 1280x1280
2. crop: 512x512
3. crop: 320x320

I observed obj loss scaled almost proportional to `image size ** -1` not the `image_size ** -2`:
So, scale factor around 1 ( `(img_size / 640) ** 1 * const`) seems to give me image-size-invariant loss.
But since I use only positive dataset, positive/negative balance is different between original and cropped (I mean sometime cropped area contains no annotations. I discard this crop).
So I'm not sure whether the effect is came from image size or positive/negative balance.

**Comment by glenn-jocher** [comment]
@bilzard yes the loss is scaled by pixel count. A lot of these adaptations are based on empirical improvements observed after their implementation, but this in this case this is also backed up by theory, as the negative samples are very low loss, and if we weight the positive samples only we get too many FPs, so we weight the entire loss.

**Comment by bilzard** [comment]
@glenn-jocher 

> but this in this case this is also backed up by theory

I don't still get it...
I understand that the objectiveness loss is designed to be emphasized depending on the image size, but isn't the `scaling factor=2` an arbitrary value?
It depends on the dataset that how much objectiveness loss should be emphasized as increasing the image size. Therefore I think, at least, the user should be able to choose the scaling factor freely.

FYI: You might already know, but I share the result of my experiment over changing scaling factor 0-2.

## Experiment

I checked how converged objectiveness loss differs when changing image size.
Images used as a dataset is:

* Original Image: 720x1280
* Cropped Image: 512x512
* Cropped Image: 320x320

## Result

* `scaling factor=0` -> As the image size is increased, the converged objectness loss decreases.
* `scaling factor=1` -> As the image size is increased, the converged objectness loss keeps almost the same.
* `scaling factor=2` -> As the image size is increased, the converged objectiveness loss increases.

1) scaling factor = 0: `lobj = (img_size / 640) ** 0 * const`
<img width="1183" alt="Screen Shot 2022-01-07 at 9 05 28" src="https://user-images.githubusercontent.com/36561962/148469837-e918214d-3d8f-4e2b-a9be-d32b8dee0118.png">

2) scaling factor = 1: `lobj = (img_size / 640) ** 1 * const`
<img width="1184" alt="Screen Shot 2022-01-07 at 9 05 52" src="https://user-images.githubusercontent.com/36561962/148469840-0b71dbf4-1e3e-4134-a67c-2e70c54a3bfe.png">

3) scaling factor = 2: `lobj = (img_size / 640) ** 2 * const`
<img width="1177" alt="Screen Shot 2022-01-07 at 9 04 50" src="https://user-images.githubusercontent.com/36561962/148469827-c0bffd9b-2738-4e65-9438-d61fa6704b0c.png">

**Comment by bilzard** [comment]
@glenn-jocher Sorry for a lot of question, but I have something don't get from the above experiment.

* Why does converged objectness loss (=IoU prediction loss) decrease when increasing image size, setting scaling factor 0? Is this fact relating to the negative prediction increases when increases image size?
* Why does converged objectness loss keeps almost the same when increasing image size, setting scaling factor 1? Is this just true for my dataset? Or are there any theoretical explanation?
* YOLOv5 also provides Focal Loss. Is it O.K. to use this to handle with negative/positive  imbalance?

**Comment by glenn-jocher** [comment]
@bilzard I'm sorry, i don't have a lot of availability to answer questions. In general settings are in place due to empirical or theoretical benefits on a wide variety of datasets we've used YOLOv5 on. 

If you find areas for improvement please let us know (especially if these are backed up by experiments).

**Comment by bilzard** [comment]
@glenn-jocher O.K. I will study more. Thanks.
