### ISSUE TITLE
如何标注负样本，并且能够正常训练

### ISSUE THREAD

**Issue by Wanghe1997** [ultralytics/yolov5#6201]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

您好，目前我们的模型yolov5m误检率较高，一是容易把背景检测为目标，二是容易把一些当前类别检测为其他容易混淆的类别。有什么建议吗？
请问如何把这些误检的图片标注为负样本，并能正常训练？负样本的生成是只需要生成一个和图片名一样的，空的txt文件吗？还是有其他的一些操作呢？谢谢

**Comment by zhiqwang** [comment]
You can check the tips of datasets at https://docs.ultralytics.com/guides/model-training-tips/#dataset

> No labels are required for background images.

As I remember, it's also OK if you set an empty file with the same name as the background images.

**Comment by pderrenger** [comment]
@zhiqwang to handle negative samples in YOLOv5, you can indeed use empty `.txt` files with the same name as your background images. This indicates no objects are present in those images. For more details, you can refer to the [custom data tutorial](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data/).
