### ISSUE TITLE
Files are not getting saved after prediction in runs\detect\exp

### ISSUE THREAD

**Issue by anusriesto** [ultralytics/yolov5#6202]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

![image](https://user-images.githubusercontent.com/52596463/148173954-e3fa0a6f-6ab7-472f-a331-a83ddb85af78.png)

File not getting saved in that folder,

**Comment by Zengyf-CVer** [comment]
@anusriesto 
What is your run command?

**Comment by anusriesto** [comment]
python detect.py --source rtsp://5starchicken:5starchicken@192.168.101.144/stream2 --weights trail1yolov5model.pt

@Zengyf-CVer

**Comment by Zengyf-CVer** [comment]
@anusriesto 
You can debug this code:
https://github.com/ultralytics/yolov5/blob/f80c463010101e463670440537662f671cbaaa04/detect.py#L200-L204
