### ISSUE TITLE
Img-size question

### ISSUE THREAD

**Issue by dariogonle** [ultralytics/yolov5#6207]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I've working with YOLOv5 for a while a I have a question about img-size. I have trained a 416x416 model (--img-size = 416). Then I run it (detect.py) on 10000x10000 images (--img-size), and for my surprise the results were good. 

I cannot understand what's going on. How is it possible? I guess that if we use 640x640 images for training and then we detect (detect.py) with an --img-size of 416, the 640x640 images are going to be rescaled to 416x416 and then performed the detection. Since there is a lost of resolution, the results are going to be lower. Therefore, how is it possible to use a 10000x10000 image and have good results? Is the system cropping the images? Does the system adapt the weights somehow?

Another thing I do not understand are the inferece times. In this case I've trained a model with a img-size of 224. Then I performed the detections (detect.py) with different img-sizes on a NVIDIA 2080 Ti. The results are in the following table:

![image](https://user-images.githubusercontent.com/80393891/148200656-c89a7a57-f8b5-41c4-9846-09094b3e3708.png)

How is it possible that if the img-size is multiplied by 5 (192 --> 512) the inference time is equal? Is the difference of time between the models the time that the system needs for rescaling the image?

Thank you in advance.

**Comment by glenn-jocher** [comment]
@dariogonle inference times are not dominated by image size at the lower ranges, especially for smaller models.

Training and Deployment image sizes are largely irrelevant. The important thing is that your object sizes are similar during training and deployment at the --imgsz you specify.

**Comment by dariogonle** [comment]
Thank you @glenn-jocher, but what's the purpose of the imgsz? Are the images rescaled to imgsz? Are the weights obtained after training adapted to an imgsz or are independient? Does this something to do with FCN?

Thank you in advance.
