### ISSUE TITLE
Usage of detect.py

### ISSUE THREAD

**Issue by diego0718** [ultralytics/yolov5#621]
Hi all,  do you know what is the usage of the command line parameters "--agnostic-nms" and "--augment" ?. I do not found related info. Thank you!

**Comment by glenn-jocher** [comment]
@diego0718 --augment is test time augmentation, see https://docs.ultralytics.com/yolov5

--agnostic is class-agnostic NMS. All classes are grouped together for NMS rather than treating each class individually (default).
