### ISSUE TITLE
Receiving Point-Coordinates of detected objects instead of boxes

### ISSUE THREAD

**Issue by BanzerUniKL** [ultralytics/yolov5#6211]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi!

My yolov5-trained NN works great. Nevertheless it would be great if I could paint the detected area (i.e. in red) instead of having a box around it.

Is there a possibility to receive these coordinates?

Thanks in advance!

**Comment by glenn-jocher** [comment]
@BanzerUniKL 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the lightest and fastest YOLOv5 model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints).
```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, custom

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by BanzerUniKL** [comment]
@glenn-jocher 
Hey Glenn, thanks a lot for your response. So if I see it right: I can only receive the boxes around detected objects, not the coordinates in which the object is detected specifically? (i.e. in order to paint only these areas red or so).
I mean just the cutout of the detected object. Not coordinates of the box around it.


If it is not possible in YOLO. Is there another bib with which this is possible?



regards

**Comment by glenn-jocher** [comment]
@BanzerUniKL I think you're referring to instance segmentation. YOLO is an object detector.

<img width="1308" alt="Screen Shot 2022-01-06 at 8 55 09 AM" src="https://user-images.githubusercontent.com/26833433/148420075-a04b70df-cde2-4d68-a281-5234d34a0afb.png">

**Comment by BanzerUniKL** [comment]
aight, thank you!
