### ISSUE TITLE
Detections.save modifies Detections.imgs 

### ISSUE THREAD

**Issue by mulcyber** [ultralytics/yolov5#6214]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

Bug:

When calling detections.save(), detections.imgs is modified.

Expected behaviour:

detections.save() does not modifies detections.img

Origin:

In the definition of Detections.display, the for loop fetch the images and then modify them inplace.

### Environment

- YOLOv5 (loaded with torch.hub)
- Python: 3.6.9

### Minimal Reproducible Example

```
import torch

# Loading model
model = torch.hub.load("ultralytics/yolov5", "yolov5s")

# Launching inference
detections = model("data/images/bus.jpg")

# Copying original image, then save
im_origin = detections.imgs[0].copy()
detections.save()

# Comparing to new image
im_new = detections.imgs[0].copy()
print("The difference between the original and new detections.img[0]:", (im_origin - im_new).sum())
#  >>> The difference between the original and new detections.img[0]: 24563214
print("Control/expected difference:", (detections.imgs[0] - im_new).sum())
#  >>> Control/expected difference: 0

```

### Additional

to fix: add im = im.copy() after the loop in models.commons.py:366

I'll add a push request later.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@mulcyber yes, we do this on purpose for improved performance (speed) during saving ops. If you'd like to submit a PR you could add an `inplace=True` argument to the save function, i.e. `results.save(inplace=False)`

**Comment by mulcyber** [comment]
Oh! ok sorry.

Since the `render=False` parameter in display seemed saves the image back to `detections.imgs` explicitly, I though it was a mistake.

I'm make a PR in tomorrow on the morning.

BTW, it's always ndarrays in `detections.imgs`? I can use `im.copy()` safely?

**Comment by glenn-jocher** [comment]
@mulcyber yes results.imgs is always numpy arrays
