### ISSUE TITLE
How to convert yolov5.onn to TensorRT engine File? 

### ISSUE THREAD

**Issue by ray-lee-94** [ultralytics/yolov5#622]

**Comment by glenn-jocher** [comment]
@VCBE123 see https://github.com/ultralytics/yolov5/issues/45#issuecomment-667970330

**Comment by lucasjinreal** [comment]
@VCBE123 here you can found a useable solution for deploy to tensorrt via onnx http://manaai.cn/aisolution_detail.html?id=5
