### ISSUE TITLE
Test custom model on test.txt

### ISSUE THREAD

**Issue by adavradou** [ultralytics/yolov5#6220]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello everyone!

Since I saw no one asking this, I guess it's obvious, but I could not make it work. 
I have created a test.txt file (also added it in dataset.yaml) and I want to test my custom model on these images. 

I tried:
`!python detect.py --weights ../weights/best.pt --img 640 --conf 0.25 --data ../../Input/dataset.yaml`

`!python detect.py --weights ../weights/best.pt --img 640 --conf 0.25 --source /content/mydrive/Input/test.txt`

and lastly:
`
with open("/content/mydrive/Input/test.txt",'r') as f:
 for line in f:
 !python detect.py --weights ../weights/best.pt --img 640 --conf 0.25 --source line`

However, none of these approaches work. 
I guess there must be a more efficient way than manually typing the path of each test image. 

Any idea how to test my model on a test.txt?

Thank you in advance.

**Comment by glenn-jocher** [comment]
@adavradou you can run inference on a test set with:
```
python val.py --data path/to/data.yaml --task test
```
