### ISSUE TITLE
where is the code conducting the train_batch.jpg in yolov5

### ISSUE THREAD

**Issue by StawEndl** [ultralytics/yolov5#6221]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

i'm sorry to ask low-question like this. i am trying to add mask in yolov5. but i can't find the code conducting train_batch.jpg.
can you tell me the function names conducting train_batch.jpg?

**Comment by glenn-jocher** [comment]
@StawEndl train jpgs are produced here:
https://github.com/ultralytics/yolov5/blob/b4ac3df6ffd6efb02200b45083b5527af41740ec/utils/loggers/__init__.py#L91-L93

**Comment by StawEndl** [comment]
> @StawEndl train jpgs are produced here:
> 
> https://github.com/ultralytics/yolov5/blob/b4ac3df6ffd6efb02200b45083b5527af41740ec/utils/loggers/__init__.py#L91-L93

thanks~
