### ISSUE TITLE
about `yolov5-x` speed 

### ISSUE THREAD

**Issue by lyuwenyu** [ultralytics/yolov5#6225]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hi, I test speed yolov5-l is 17.1 (v100), but it has big gap with offical 12.1,  PS. s m l similar with offical.

**Comment by glenn-jocher** [comment]
@lyuwenyu see README table for commands to reproduce:

> * **Speed** averaged over COCO val images using a [AWS p3.2xlarge](https://aws.amazon.com/ec2/instance-types/p3/) instance. NMS times (~1 ms/img) not included.<br>Reproduce by `python val.py --data coco.yaml --img 640 --conf 0.25 --iou 0.45`


<img width="892" alt="Screen Shot 2022-01-06 at 9 41 17 AM" src="https://user-images.githubusercontent.com/26833433/148426690-3c1edc21-60e9-4231-9b3c-df810f99ef6f.png">


Also see v6.0 PR with notes regarding reported speeds https://github.com/ultralytics/yolov5/pull/5141#issuecomment-941247815

**Comment by lyuwenyu** [comment]
thx
