### ISSUE TITLE
how about rotate object? Will be support?

### ISSUE THREAD

**Issue by xinsuinizhuan** [ultralytics/yolov5#6226]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

I want to detect the rotate object.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@xinsuinizhuan rotation is possible but you need a suitably labelled dataset, i.e. see https://github.com/BossZard/rotation-yolov5
![image](https://user-images.githubusercontent.com/26833433/148426360-6425dbf4-6af3-4bc1-927b-10d16e6efebb.png)
