### ISSUE TITLE
How To Use best.pt In a Custom Python Script

### ISSUE THREAD

**Issue by milehighsmile** [ultralytics/yolov5#6231]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,

I have read through the tutorials for yolov5 and used the provided colab notebook to train yolov5s on custom data. I am satisfied with the training results and would like to use the resultant best.pt file to perform detections in a python script that I write. How do I load the best.pt file for the trained model in a python script that I have written so that I neither need to use the provided detect.py script nor modify detect.py by adding my own code? 

Previously I have used the state_dict's to load a trained model but I have not had success attempting to load the yolov5 model using _model = torch.hub.load('path/to/cloned/yolov5', 'custom', 'path/to/best.pt')_.

Thank you for any help.

**Comment by glenn-jocher** [comment]
@colejames-wsu 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the lightest and fastest YOLOv5 model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints).
```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, custom

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!
