### ISSUE TITLE
objects being detected twice

### ISSUE THREAD

**Issue by BanzerUniKL** [ultralytics/yolov5#6232]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hey there,

my NN sometimes detects the same object twice, but with different classes. actually they are very similar. Then there are 2 bounding boxes on top of each other. Is there a possibility to say that it has to decide for a class (for the one with the higher confidence) ?

thanks

**Comment by iceisfun** [comment]
Have you looked at how IoU works?

https://en.wikipedia.org/wiki/Jaccard_index

**Comment by glenn-jocher** [comment]
@BanzerUniKL try detect.py —agnostic

**Comment by BanzerUniKL** [comment]
> @BanzerUniKL try detect.py —agnostic>

do I see it right, that the flag takes a bool?
if i put it on true, it doesn't detect some smaller objects of class A anymore that are placed on object of class B.

Is there something else I can try?
