### ISSUE TITLE
Hay anybody run YOLOv5 on Google Coral Dev Board?

### ISSUE THREAD

**Issue by dariogonle** [ultralytics/yolov5#6234]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,

  I want to run YOLOV5n on Google Coral and I having some problems. I've exported the pt model to edgetpu with the export.py script.

Then on the Coral, I've created a virtual enviroment and I've install requirements.txt dependecies. After this I'm getting the following error:
![image](https://user-images.githubusercontent.com/80393891/148567000-d5a422e7-0bc1-495e-832f-c7436849ac8b.png)

I was wondering if someone has got it to work.
 

### Additional

I've also run the object detection example (https://github.com/google-coral/pycoral/tree/master/examples), and I got it
![image](https://user-images.githubusercontent.com/80393891/148568072-a4884f5e-90f5-4553-99f4-dc3fe50bd740.png)

But then I've changed it, and I used the yolov5_edgetpu model and it gives me the following error:
![image](https://user-images.githubusercontent.com/80393891/148568260-9da4180c-1eb4-4476-889b-1e528b1676b2.png)

_No response_

**Comment by tdhooghe** [comment]
Hi, I was wondering if YOLOv5 should work with a Google Dev Board Mini as I am planning to acquire one. Should YOLOv5 work on this board? And would it then be able to use the TPU on it? Thanks in advance! Kind regards, Thomas

**Comment by dariogonle** [comment]
Hi @tdhooghe. I managed to run YOLOv5N on a Google Dev Board (not mini) with an maximun input size of 640.

**Comment by tdhooghe** [comment]
Hi @dariogonle, thank you so much for your quick response! Could you elaborate a bit on its mAP (maybe on COCO or something) and its speed of inference? Do you know why it did not work with an input size of 1280? And how much RAM does you Google Dev Board have?

**Comment by dariogonle** [comment]
@tdhooghe I haven't use COCO. I guess that 1280 is too big, and it runs out of memory. 

![image](https://user-images.githubusercontent.com/80393891/164730226-ef5b6ecd-8de2-4db2-a4f5-270e4eaa4ef7.png)

**Comment by tdhooghe** [comment]
@dariogonle thank you for your inference times! What size are your batches? And do you also have data on batch-size of 1? 

Which yolo model do you use? And how does it perform in terms of mAP on your dataset?

**Comment by DeepKnowledge1** [comment]
@dariogonle 
is it possible to share the detection code
