### ISSUE TITLE
image flip up-down

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#6239]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

flipud: 0.5  # image flip up-down (probability)

If I have the 100+ 500 training images. And I only let the special 100 images flipud.
How can I fix the code ?

This is my method but it is not good.
I generate the additional 100 images for flipud. So the data will be 100+100+500.

**Comment by glenn-jocher** [comment]
@alicera augmentations are applied consistently to the entire training set, there is no current method to apply augmentation selectively per image.
