### ISSUE TITLE
inference consumes more time (0.25s) using tflite than using pt (0.009s)

### ISSUE THREAD

**Issue by caichao** [ultralytics/yolov5#6244]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

I used export.py script to convert *.pd weights to tflite format using the following script:

`python .\export.py --weights .\runs\train\exp16\weights\best.pt --verbose --include tflite`

![image](https://user-images.githubusercontent.com/3417516/148679531-404a5a28-1f68-4876-806c-1af6bbf2c9a2.png)

than, I use tflite formated weights to run inference using:
`python .\detect.py --weights .\runs\train\exp16\weights\best-fp16.tflite --source .\videos\ball1.mp4`
 it causes roughly 0.25s per inference. 
![image](https://user-images.githubusercontent.com/3417516/148679615-4699f0bb-b93d-4ded-b56a-67eb829e455b.png)

while inferencing using original pt weights, it consumes only around 0.01s
![image](https://user-images.githubusercontent.com/3417516/148679647-85725280-8162-43f0-93ca-5a07d6181861.png)

I just wondering what's wrong here? Am I missing something here?

### Environment

YOLOV5

tensorflow v2.7
pytorch 1.10

![image](https://user-images.githubusercontent.com/3417516/148679702-5c678011-3610-4842-a62f-775a8c5b3172.png)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@caichao results are as expected. TFLite models run on CPU.
