### ISSUE TITLE
how to sort output based on left to write in detect.py

### ISSUE THREAD

**Issue by mohammad69h94** [ultralytics/yolov5#6245]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to sort results in detect.py. I need to get detected digits in some order.
How to sort output using detect.py?
I want to use detect.py exactly and don't use torch hub

**Comment by glenn-jocher** [comment]
@mohammad69h94 detect.py outputs are sorted by confidence. You can customize sorting order here:
https://github.com/ultralytics/yolov5/blob/6865d19a92d8c160c7fc3c92256627dadce1cd1e/detect.py#L163-L177

**Comment by mohammad69h94** [comment]
> @mohammad69h94 detect.py outputs are sorted by confidence. You can customize sorting order here:
> 
> https://github.com/ultralytics/yolov5/blob/6865d19a92d8c160c7fc3c92256627dadce1cd1e/detect.py#L163-L177

Thank you so much.
my other question is why yolov5 can't detect zero digits in the following image. but can detect other digits strongly. 
and my dataset is enough and balanced. and even the number of zero labels is more than other labels.
![front_9](https://user-images.githubusercontent.com/38998372/148739548-3e24b5e4-05ff-4b93-8fdb-a7ab10af0b64.jpg)
other images:
![front_3](https://user-images.githubusercontent.com/38998372/148740031-79ce45be-bc34-4cf7-bafc-61e9248f3461.jpg)

**Comment by glenn-jocher** [comment]
@mohammad69h94 if this is arabic then the zero is the dot I think, which might be too small at smaller image sizes. The training labels candidate criteria are here, you should ensure that the zero dot labels are not rejected for being too small:
https://github.com/ultralytics/yolov5/blob/9b13a594e953e4e2688ff6ac0190a2247733e4ca/utils/augmentations.py#L272-L277

**Comment by Hisan-007** [comment]
If you want to modify the outputs of yolov5 detections after inferencing to sort it from left to right, here's what would work for you: 

```python
# Assuming 'results' contains the detection output
detections = results.xyxy[0].tolist()  # Get list of detections

# Sort the detections based on the x1 coordinate (i.e., left-to-right)
detections.sort(key=lambda x: x[0])
```

**Comment by glenn-jocher** [comment]
@HissaanAli to modify the outputs of YOLOv5 detections in order to sort them from left to right, you can use the following code snippet:

```
# Assuming 'results' contains the detection output
detections = results.xyxy[0].tolist()  # Get list of detections

# Sort the detections based on the x1 coordinate (i.e., left-to-right)
detections.sort(key=lambda x: x[0])
```

This code converts the detection results to a list and then sorts the list based on the x1 coordinate of each detection, which represents the left-to-right order.

Please note that this is an example code snippet and you may need to adapt it to your specific implementation. Let me know if you have any further questions or need any additional assistance.

**Comment by Hisan-007** [comment]
@glenn-jocher from my understanding, it seems like my response aligns with yours. Can you please confirm this? I'd appreciate it if you could also check my original answer and let me know if there's anything I might have overlooked or misunderstood.

**Comment by glenn-jocher** [comment]
@HissaanAli thank you for your response and for checking with me. Your understanding aligns with mine - modifying the `detections` list using the provided code snippet will sort the detections from left to right based on the x-coordinate.

I have reviewed your original answer, and it accurately explains how to modify the detection results to achieve the desired sorting order. If the user has any further questions or concerns, they can reach out for additional assistance.

Thank you for your contribution and for helping the YOLOv5 community.

**Comment by Hisan-007** [comment]
Thank for @glenn-jocher  the great tool. Made my life a lot easier.

**Comment by glenn-jocher** [comment]
@HissaanAli thank you for your kind words and we're glad to hear that YOLOv5 has been helpful to you! We appreciate your support and encouragement. However, it's important to note that YOLOv5 is a collaborative effort by the YOLO community and the Ultralytics team. We're grateful for the contributions from all the individuals involved in making YOLOv5 a great tool. If you have any questions or need further assistance, please don't hesitate to ask.
