### ISSUE TITLE
map@640 of yolov5_6edition

### ISSUE THREAD

**Issue by sdreamforchen** [ultralytics/yolov5#6246]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have a quesition about the map@640, do you test this resolution

### Additional

nothing

**Comment by glenn-jocher** [comment]
@sdreamforchen these are not available in the readme but very easy to produce yourself:
```bash
python val.py --weights yolov5s6.pt --data coco.yaml --img 640 --iou 0.65 --half
```
