### ISSUE TITLE
yolov5 failed to open esp32cam streams(http)

### ISSUE THREAD

**Issue by BobH62** [ultralytics/yolov5#6247]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have a stream from esp32cam, when I use the LAN ip of the cam,
command: python detect.py --source 192.168.x.x:81/stream works successfully.
However, I got a domain for the esp32cam, which is "http://xxx.xxx.xxx:4881/stream", and firefox/chrome can open it successfully,
but command:python detect.py --source 'http://fs2.iis.pub:4881/stream' simply fails.
The message is:AssertionError: 1/1: http://fs2.iis.pub:4881/stream... Failed to open http://fs2.iis.pub:4881/stream

**Comment by BobH62** [comment]
![Screenshot from 2022-01-09 23-19-09](https://user-images.githubusercontent.com/55829732/148688745-5c42a627-2b37-4d12-83f0-95c742ab232f.png)
as you can see i can open the http stream using firefox, but yolov5 cannot open it.

**Comment by BobH62** [comment]
![Screenshot from 2022-01-09 23-25-22](https://user-images.githubusercontent.com/55829732/148688828-ba882caf-ac86-4f54-932c-3424ea54c275.png)
and i can open the stream using command : python detect.py --source 192.168.x.x:81/stream 
in yolov5

**Comment by glenn-jocher** [comment]
@BobH62 address doesn't work for me in chrome:

<img width="1104" alt="Screen Shot 2022-01-09 at 8 50 04 PM" src="https://user-images.githubusercontent.com/26833433/148727539-14bbdc44-8af8-4f93-b25f-3cbaa807dbeb.png">
