### ISSUE TITLE
multi-GPU for val.py

### ISSUE THREAD

**Issue by bozihu** [ultralytics/yolov5#6249]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to use the multi-GPU to get faster inference time. When I use the comand: python -m torch.distributed.launch --nproc_per_node 2 val.py, there is a bug occur.

usage: val.py [-h] [--data DATA] [--weights WEIGHTS [WEIGHTS ...]] [--batch-size BATCH_SIZE] [--imgsz IMGSZ] [--conf-thres CONF_THRES] [--iou-thres IOU_THRES] [--task TASK] [--device DEVICE] [--workers WORKERS] [--single-cls] [--augment] [--verbose] [--save-txt] [--save-hybrid]
              [--save-conf] [--save-json] [--project PROJECT] [--name NAME] [--exist-ok] [--half] [--dnn]
val.py: error: unrecognized arguments: --local_rank=1
usage: val.py [-h] [--data DATA] [--weights WEIGHTS [WEIGHTS ...]] [--batch-size BATCH_SIZE] [--imgsz IMGSZ] [--conf-thres CONF_THRES] [--iou-thres IOU_THRES] [--task TASK] [--device DEVICE] [--workers WORKERS] [--single-cls] [--augment] [--verbose] [--save-txt] [--save-hybrid]
              [--save-conf] [--save-json] [--project PROJECT] [--name NAME] [--exist-ok] [--half] [--dnn]
val.py: error: unrecognized arguments: --local_rank=0
Traceback (most recent call last):
  File "/home/ubuntu/.conda/envs/yolov5_obb/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/.conda/envs/yolov5_obb/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/.conda/envs/yolov5_obb/lib/python3.8/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/ubuntu/.conda/envs/yolov5_obb/lib/python3.8/site-packages/torch/distributed/launch.py", line 255, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/home/ubuntu/.conda/envs/yolov5_obb/bin/python', '-u', 'val.py', '--local_rank=1']' returned non-zero exit status 2.

I want to request how to use val.py with multi-GPU?

**Comment by glenn-jocher** [comment]
@bozihu val.py only supports CPU and single GPU backends. You can pass it a single GPU index, i.e. --device 0.

**Comment by wandaoyi** [comment]
Sometimes, we may use many cameras unite to detect objects. So, we want to use multi GPU to deal with the requirement. That is why we asked about the issue.

**Comment by glenn-jocher** [comment]
@wandaoyi one option for Multi-GPU inference is you can initialize models on different backends with YOLOv5 PyTorch Hub models just for normal inference (not validation), i.e.:

```python
import torch

model0 = torch.hub.load('ultralytics/yolov5', 'yolov5s', device=0)
model1 = torch.hub.load('ultralytics/yolov5', 'yolov5s', device=1)
model2 = torch.hub.load('ultralytics/yolov5', 'yolov5s', device=2)
...
```

Make sure you git pull or `force_reload=True` as we updated this code recently in https://github.com/ultralytics/yolov5/pull/6290

**Comment by wandaoyi** [comment]
However, how can we balance the resources of&nbsp;gpus. If we have 1 to n video streaming to be detected objects. we don't know that when its' be use. So, when we use gpu=0, or 1, or 2?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Glenn ***@***.***&gt;; 
发送时间: 2022年1月14日(星期五) 下午3:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ultralytics/yolov5] multi-GPU for val.py (Issue #6249)





 
@wandaoyi one option for Multi-GPU inference is you can initialize models on different backends with YOLOv5 PyTorch Hub models just for normal inference (not validation), i.e.:
 import torch model0 = torch.hub.load('ultralytics/yolov5', 'yolov5s', device=0) model1 = torch.hub.load('ultralytics/yolov5', 'yolov5s', device=1) model2 = torch.hub.load('ultralytics/yolov5', 'yolov5s', device=2) ...
 
Make sure you git pull or force_reload=True as we updated this code recently in #6290
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by glenn-jocher** [comment]
@wandaoyi I don't know, it depends on your application. You want to create a good pipeline that produces high GPU utilization rates (i.e. check with `nvidia-smi`) to fully use your available hardware.

**Comment by wandaoyi** [comment]
Thank you all the same




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Glenn ***@***.***&gt;; 
发送时间: 2022年1月17日(星期一) 凌晨5:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ultralytics/yolov5] multi-GPU for val.py (Issue #6249)





 
@wandaoyi I don't know, it depends on your application. You want to create a good pipeline that produces high GPU utilization rates (i.e. check with nvidia-smi) to fully use your available hardware.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
