### ISSUE TITLE
missing import "plot_evolution" in train.py

### ISSUE THREAD

**Issue by weiwei2027** [ultralytics/yolov5#625]
## 🐛 Bug
     line 551 in tarin.py "plot_evolution" was not imported.   it should be imported from "utils.general".  The problem still exists after the commit 941cb2680b8a3513f5105d596517261064af492b (Aug 4, 2020).

**Comment by lorenzomammana** [comment]
Hey @WangWeiwei27 i've submitted just now a PR addressing this issue and a missing import in detect.py, this should be solved soon!

**Comment by weiwei2027** [comment]
ok, thanks @lorenzomammana

**Comment by glenn-jocher** [comment]
This has been fixed in PR https://github.com/ultralytics/yolov5/pull/627
