### ISSUE TITLE
Same pt-file, different results

### ISSUE THREAD

**Issue by SwHaraday** [ultralytics/yolov5#6250]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi Glenn !
I've finished my custom training and detection results via your detect.py are EXCELLENT !!
Aimed objects are consistently detected with no false positive.
I tested same movie with simple detection program like blow, However, result was poor compare to yours in terms of consistency.

What makes the difference ?
Are there any way to get good result as your detect.py ?

The reason why I preffer to use simple detection program is:
Real-time images from 4 cameras has to be concatenated into one before fed to model.
and your 'class LoadStreams' in datasets.py is too complicated for me to modify.

If you need pt.file and movie to check, I can send you by some way.

Thanks in advance.

[excellent_result.txt](https://github.com/ultralytics/yolov5/files/7837117/excellent_result.txt)
[poor_result.txt](https://github.com/ultralytics/yolov5/files/7837120/poor_result.txt)

-- code --
```
import torch
import cv2
# Ignore warnings
import warnings
warnings.filterwarnings("ignore") # Warning will make operation confuse!!!

# Select input source
#source = 1
source = '//*.168.52.147/ftp/V72DATA/conc/V72_20220107-075843_0000m.mov'

# Model
model = torch.hub.load(   '' # Use backend for yolov5 in this folder　
                        , 'custom' # to use model in this folder 
                        , path='20220107best.pt' #pompom_detection.pt' # the name of model is this folder
                        , source='local' # to use backend from this folder
                        , force_reload=True # clear catch　
                        , device = 'cpu' # I want to use CPU
                    ) 
model.conf = 0.50 # NMS confidence threshold　
model.iou = 0.45  # IoU threshold
model.multi_label = False  # NMS multiple labels per box
model.max_det = 1000  

# RUN
cap = cv2.VideoCapture(source) # Read source file or USB Camera

while cap.isOpened():
    # Read Frame
    ret, frame = cap.read()
    if not ret:
        print('Reached the end of the video!')
        break
    # Object Detection
    results = model(frame , size = 640) 
    results.print()
    height = frame.shape[0]
    #cv2.imshow('Object detector', results.render()[0])

    for *box, conf, cls in results.xyxy[0]:  # xyxy, confidence, class

        #--- 
        s = model.names[int(cls)]+":"+'{:.1f}'.format(float(conf)*100)
        cc = (0,0,255)
        cc2 = (255,255,255)

        #--- 
        cv2.circle(frame, (int(box[0]), int(box[1])), 2, cc, thickness=-1)
        cv2.circle(frame, (int(box[0]), int(box[3])), 2, cc, thickness=-1)
        cv2.circle(frame, (int(box[2]), int(box[1])), 2, cc, thickness=-1)
        cv2.circle(frame, (int(box[2]), int(box[3])), 2, cc, thickness=-1)
        cv2.rectangle(frame, (int(box[0]), height-45), (int(box[0])+len(s)*10, height-25), cc, -1)
        cv2.putText(frame, s, (int(box[0]), height-30), cv2.FONT_HERSHEY_TRIPLEX, 0.5, cc2, 1, cv2.LINE_AA)
    frame = cv2.resize(frame, dsize=None, fx=1.2, fy=1.2)
    #--- 
    cv2.imshow('Object detector', frame)
    # Press 'ESC' to quit
    if cv2.waitKey(1) == 27:#ord('q'): 
        break

# Clean up
cap.release()
cv2.destroyAllWindows()


```

**Comment by SwHaraday** [comment]
Hi,
I believe detection is simply big calculation according to the model equation.
As far as same images are fed, results should be the same. It is not good for anyone to have inferior results from same trained model depending on detection program.

I reviewed results text and felt that "Adding AutoShape..." suggests something different.
I wonder unintentional feed of modified images makes difference...

Thank you.

**Comment by glenn-jocher** [comment]
@SwHaraday detect.py and PyTorch Hub produce identical results, i.e. python detect.py and:

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, custom

# Images
img = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, PIL, OpenCV, numpy, list

# Inference
results = model(img)

# Results
results.show()
```

**Comment by glenn-jocher** [comment]
@SwHaraday also we don't assist in debugging custom code.

**Comment by SwHaraday** [comment]
Hi,
Thank you for your reply.
I don't ask you to debug code, just want to know what is happening.
I will check again.
If my usage contains mistake like arguments, please kindly suggest.

Thank you.

**Comment by SwHaraday** [comment]
Hi,
I misunderstood how to feed images from OpenCV video to the model.
Now results become identical.
Thank you for you comment.
