### ISSUE TITLE
Focus module gone in version 6?

### ISSUE THREAD

**Issue by iumyx2612** [ultralytics/yolov5#6257]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

So did you completely remove Focus module from YOLOv5-v6.0?
I read from [here](https://github.com/ultralytics/yolov5/issues/3850) and [here](https://github.com/ultralytics/yolov5/discussions/3181) that Focus module is simply a Conv module but less parameters, faster, less GPU mem with profiling result as a proof
But later, in [here](https://github.com/ultralytics/yolov5/issues/4825), with more profiling results, Focus module seems worse than Conv module

**Comment by glenn-jocher** [comment]
@iumyx2612 yes the Focus layer was removed in v6.0. Profiling results vary based on hardware: many consumer cards and some enterprise cards like T4 observed faster performance using the Focus layer, but other cards like V100/A100 performed better with the current implementation.

The main driver for the switch was **exportability improvements**, as now YOLOv5 is officially supported for inference on 11 different backends, many of which provide better support for the new Conv implementation.  (https://docs.ultralytics.com/yolov5/tutorials/model_export)

**Comment by iumyx2612** [comment]
> @iumyx2612 yes the Focus layer was removed in v6.0. Profiling results vary based on hardware: many consumer cards and some enterprise cards like T4 observed faster performance using the Focus layer, but other cards like V100/A100 performed better with the current implementation.
> 
> The main driver for the switch was **exportability improvements**, as now YOLOv5 is officially supported for inference on 11 different backends, many of which provide better support for the new Conv implementation. (#251)

Thank you

**Comment by songyuc** [comment]
Hi, guys!
Is this 6*6-Conv a learnable module or freezed during the training?

**Comment by glenn-jocher** [comment]
@songyuc learnable, nothing is frozen by default

**Comment by songyuc** [comment]
> @songyuc learnable, nothing is frozen by default

So, this 6*6-Conv might tend to play a role of `Focus` or a better role of feature extraction while down-samling, is this a good understanding?

**Comment by glenn-jocher** [comment]
@songyuc no. The main idea behind Focus was faster initial layer with minimal mAP impact. Focus has now been deprecated for better exportability.

**Comment by songyuc** [comment]
> @songyuc no. The main idea behind Focus was faster initial layer with minimal mAP impact. Focus has now been deprecated for better exportability.

Thanks sincerely for your answer!

**Comment by songyuc** [comment]
你好，您的邮件我已经收到，谢谢您！~O(∩_∩)O~                                                    宋玉成

**Comment by glenn-jocher** [comment]
@songyuc 你好，宋玉成！很高兴能帮到您。如果您有任何关于 YOLOv5 的疑问，请随时提问。祝您使用愉快！
