### ISSUE TITLE
Calculate bounding box from MultiArray (iOS, CoreML).

### ISSUE THREAD

**Issue by kegbird** [ultralytics/yolov5#6261]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,

I've succefully exported the last yolov5n model into a coreml model; putting it in my xcode project, I noticed that the output of the model is a sequence of 4 MLMultiArray.

![Schermata 2022-01-10 alle 23 40 48](https://user-images.githubusercontent.com/11041167/148850331-5de05f1d-a21e-4071-bbde-e39a15d8af30.png)

My question is: how can I extract bounding box, label id and confidence from these multiarray?

What I really need is the semantic of those numbers (I can't figure out how to interpret the output).

**Comment by Kegbird** [comment]
What's the point in exporting the model in coreml if it's not directly usable by iOS device?

There's no documentation about the output, nor how to integrate nms in the model.
