### ISSUE TITLE
TensorFlow SavedModel: export failure: Message third_party.py.keras.protobuf.SavedMetadata exceeds maximum protobuf size of 2GB: 2283672738

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/yolov5#6262]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Export

### Bug

YOLOv5x SavedModel format is over a 2GB TF limit:
```
TensorFlow SavedModel: export failure: Message third_party.py.keras.protobuf.SavedMetadata exceeds maximum protobuf size of 2GB: 2283672738
```

First noted in https://github.com/ultralytics/yolov5/issues/251#issuecomment-1008741802

@zldrobit could you help on this?

### Environment

Colab Notebook
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

### Minimal Reproducible Example

In Colab notebook after running Setup cell:
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb
```python
!python export.py --weights yolov5x.pt --img 640 --include saved_model
```

### Additional

See https://github.com/tensorflow/tensorflow/issues/45041 for the official TF issue

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by zldrobit** [comment]
@glenn-jocher I can confirm the problem with your provided notebook. I also found some links about the 2GB size limit: https://stackoverflow.com/a/42906762/3036450, https://github.com/tensorflow/tensorflow/issues/4291 and https://stackoverflow.com/questions/59558170/tensorflow-graph-bigger-than-2gb. According to those links, we should not break the 2GB limit of protobuf. One way to get a saved model smaller than 2GB is wrap the yolov5x pb model (~350MB) in a saved model format.

EDIT:
The exported pb model is 90% smaller than the saved_model.
![image](https://user-images.githubusercontent.com/3896992/149288117-9960a6e4-be6c-41ba-a707-fec559b96c16.png)

**Comment by zldrobit** [comment]
@glenn-jocher I sent a [PR](https://github.com/ultralytics/yolov5/pull/6292) to address this issue, but it breaks backward compatibility for saved_model export. Here's [a notebook](https://colab.research.google.com/drive/1ybv2jsV0_q338g6ngTAil4zVJznxve7m?usp=sharing) for validation.
