### ISSUE TITLE
About single class of rectangle training and export

### ISSUE THREAD

**Issue by jayer95** [ultralytics/yolov5#6263]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

This is the command I use when training,

python train.py \
    --img 640 \
    --batch 16 \
    --epochs 300 \
    --data data/license_plate_bdd100k.yaml \
    --weights '' \
    --cfg models/yolov5n-license_plate_bdd100k.yaml \
    --rect \
    --single-cls \
    --hyp data/hyps/hyp.scratch-low-license_plate_bdd100k.yaml

1. I only have one class "license plate", do I need to set the argument "--single-cls"?

When I set the "--rect" parameter, the training will be trained with the rectangle.
The size of each input image of my training dataset is 1920x1080. 

When entering training, 1920x1080 will be resized to 640x360, and 360 cannot be divisible by 32.
Therefore, through the practice of "letterbox", 360 is supplemented by 24 to become 384. (640x384)
When I finish training, I need to use "export.py" to export the trained model, the command I use is:

python export.py --weights yolov5n-license_plate_bdd100k_last.pt --optimize --opset 11 --simplif --imgsz 360 640
or
python export.py --weights yolov5n-license_plate_bdd100k_last.pt --optimize --opset 11 --simplif --imgsz 384 640

2. The .onnx model obtained by these two commands is 384x640, which one is correct?
3. Does .onnx have the concept of "letterbox"?
![gnome-shell-screenshot-DQ8HF1](https://user-images.githubusercontent.com/35683311/148877984-471bd850-1468-443d-ba15-9bed51a95532.png)

**Comment by glenn-jocher** [comment]
@jayer95 --single-cls argument is for forcing multiple-class datasets into a single-class mode. A single-class model will be produced. This argument is **not** required if your dataset is already a single class.

All YOLOv5 functions pass the user-supplied image size argument through the `check_img_size()` function to pad it as necessary for stride constraints (i.e. image must be a 32 or 64 multiple).
https://github.com/ultralytics/yolov5/blob/b3eaf5008bb8a34de481a6ef7ac8ba520d97b70e/export.py#L410-L412
