### ISSUE TITLE
How to use batch inference (use multiple images instead of single image) ??

### ISSUE THREAD

**Issue by balaji-skoruz** [ultralytics/yolov5#6265]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am looking for solution to speed up the inference time by using batch inference(multiple images) .
and also reading image from video using open cv took considerable amount of time so how do reduce it.

and also how can i use multiple GPUs for model inference and need to utilize the GPU 100%.

Thanks in advance
![image](https://user-images.githubusercontent.com/68884041/148888905-e424a01b-2cce-4f16-aedc-daa689c0b6db.png)

### Additional

I am looking for solution to speed up the inference time by using batch inference(multiple images) .
and also reading image from video using open cv took considerable amount of time so how do reduce it.

and also how can i use multiple GPUs for model inference and need to utilize the GPU 100%.

Thanks in advance
![image](https://user-images.githubusercontent.com/68884041/148888809-07bb6a64-c564-4123-826f-cd69269d2cf1.png)

**Comment by glenn-jocher** [comment]
@balaji-skoruz 👋 Hello! Thanks for asking about **batched inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes a batch of images for inference. `'yolov5s'` is the lightest and fastest YOLOv5 model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints).
```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Images
dir = 'https://ultralytics.com/images/'
imgs = [dir + f for f in ('zidane.jpg', 'bus.jpg')]  # batch of images

# Inference
results = model(imgs)

# Results
results.print  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by balaji-skoruz** [comment]
Hi @glenn-jocher , Thanks for the reply...
I have these questions.
1) how can I read images using GPU ?? is it possible ? because it took lot of time .
2) how to use multiple GPUs for inference ?? to increase speed and achieve real time.
3) and how to reduce NMS time ??  because it also took more time than detection .

thanks

**Comment by glenn-jocher** [comment]
@balaji-skoruz see [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for GPU inference.

**Comment by balaji-skoruz** [comment]
done . Thanks @glenn-jocher

**Comment by balaji-skoruz** [comment]
@glenn-jocher - is there any video library other than opencv ?
opencv took considerable amount of time to read the frame. and I need production grade video reading library

**Comment by glenn-jocher** [comment]
@balaji-skoruz PIL and OpenCV are the two major CV libraries. OpenCV tends to be faster while PIL tends to be more pythonic and simpler to use.

**Comment by balaji-skoruz** [comment]
ok

**Comment by EvelinaAleksiutenko** [comment]
Hi, @glenn-jocher should we use the same batch_size for batch_inference as the batch_size of the training? (training was on CUDA:0 Tesla T4, 15102MiB, but inference in GeForce RTX 3090 Ti)

**Comment by glenn-jocher** [comment]
@EvelinaAlexiutenko yes, when performing batch inference in YOLOv5, it's generally a good practice to use the same batch size as during training. However, please note that the batch size during inference can be adjusted based on the available GPU memory. So, if you have more memory available on your GeForce RTX 3090 Ti GPU, you may choose to increase the batch size during inference for faster processing. It's recommended to experiment and find the optimal batch size that balances speed and memory usage for your specific hardware setup.
