### ISSUE TITLE
What is hidden channel

### ISSUE THREAD

**Issue by myasser63** [ultralytics/yolov5#6267]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have a simple question. I want to understant what is the function and meaning of hidden channel used in `common.py`

     ` c_ = int(c2 * e)  # hidden channels`

**Comment by glenn-jocher** [comment]
@myasser63 `c_` is an integer channel count argument to a convolution layer

**Comment by myasser63** [comment]
@glenn-jocher Thanks for your reply. Could you please explain a bit about the purpose of hiddem channel
