### ISSUE TITLE
from onnx to tflite [NHWC]

### ISSUE THREAD

**Issue by larrywal-express** [ultralytics/yolov5#6271]
I trained a customized model. For android phone deployment, i succeeded in converting from onnx - saved_model - tflite. However my tflite model is in NCHW instead of NHWC. How do i change the ordering to NHWC?

**Comment by zldrobit** [comment]
@larrywal-express You could try using `prep.py` in https://github.com/zldrobit/onnx_tflite_yolov3 to convert NCHW kernels -> NHWC kernels inserted with transpose ops in pb files, but that script has not been updated for a long time and is only tested for TensorFlow 1.x.
