### ISSUE TITLE
The cls dim is invalid when Single_cls = True, but it seems that this dim is used for inference for single cls problem.

### ISSUE THREAD

**Issue by pocketvision** [ultralytics/yolov5#6273]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training, Validation, Detection, Export

### Bug

From ComputeLoss:
                # Classification
                if self.nc > 1:  # cls loss (only if multiple classes)
                    t = torch.full_like(ps[:, 5:], self.cn, device=device)  # targets
                    t[range(n), tcls[i]] = self.cp
                    lcls += self.BCEcls(ps[:, 5:], t)  # BCE
So, the cls dim is invalid for single_cls problem, but this last dim output is used directly in non_max_suppression() when Single_cls=True:
               # Compute conf
                x[:, 5:] *= x[:, 4:5]  # conf = obj_conf * cls_conf
I'm confused if we should add a assignment before Compute conf for single_cls=True:
               # Compute conf
                if agnostic:
                        x[:, 5:] = 1
                x[:, 5:] *= x[:, 4:5]  # conf = obj_conf * cls_conf
Or should we directly cut off the cls dim in model when Single_cls=True ?
               

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@daikankan class confidence always outputs 1 for single class models so there is no issue.

**Comment by pocketvision** [comment]
@glenn-jocher Sorry to bother you, but can you tell me how the cls confidence x[:, 5:6] can be always 1 for single cls models ? 
What I see is, because the parameters for this cls dim are not trained for single cls models, so the cls confidence x[:, 5:6] is random (my experiment results are verified), but this line (x[:, 5:] *= x[:, 4:5]  # conf = obj_conf * cls_conf) tells that we use (obj_conf multiplied by a random value) as the scores for  the final torchvision.ops.nms(boxes, scores, iou_thres).
Do I miss something, or do I misunderstand ?

**Comment by glenn-jocher** [comment]
@daikankan class confidences are intialized at 1 and have no loss for single class models.

Single class models are handled correctly and everything is correct. If you find any reproducible example to the contrary please submit a bug report with exact steps to reproduce.
