### ISSUE TITLE
set_logging stomps over root logging handlers

### ISSUE THREAD

**Issue by robby-d** [ultralytics/yolov5#6278]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Other

### Bug

I'm wondering if there is a good reason why set_logging deletes root logging handlers (see https://github.com/ultralytics/yolov5/blob/b4a29b5a8d63a8c2d4a8929942b44e8969c5dddd/utils/general.py#L49-L50).
I add handlers to the root logger so that I can log all 3rd party modules to a log file, and yolov5 doing this is deleting these handlers and making it not possible for me to load yolov5 and log its output to a file with the rest of my program's output (without resorting to some ugly runtime hacks).

Maybe there is something I am missing? Is it possible to make this behavior optional? Happy to submit a PR.

### Environment

Newest Yolov5 `master` on Ubuntu 20 LTS.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@robby-dermody this is a patch for Kaggle notebooks, which will not output any logging without this fix. See https://github.com/ultralytics/yolov5/pull/6041

**Comment by glenn-jocher** [comment]
@robby-dermody see https://github.com/ultralytics/yolov5/issues/5913#issuecomment-989816925 for original issue.

The Kaggle notebook itself is https://www.kaggle.com/models/ultralytics/yolov5

If there's a more permanent fix for the Kaggle problem that you find please let us know!

**Comment by robby-d** [comment]
ah, ouch. perhaps there is a more elegant way to go about it, e.g. detect if in a Kaggle nodebook environment, and apply the fix, or take a configuration flag that allows the fix to be specified. I'll close this ticket out as I got permission denied issues on attempting the automatic model download at startup when adding the standard integration (via Tensor hub) into my app and launching my app as a systemctl service (whereas running from the console worked fine). I was able to get Deepstack running (as a separate service via Docker that my app interacted with) and that seems less problematic, so I'll stick with that for now. Thanks for the quick reply!

**Comment by glenn-jocher** [comment]
@robby-dermody got it. We have a few specific functions for determining environments, i.e. `is_colab()`, but no `is_kaggle()` yet:
https://github.com/ultralytics/yolov5/blob/80473a65511859698aa36778c30997ba80943945/utils/general.py#L176-L183

**Comment by glenn-jocher** [comment]
@robby-dermody good news 😃! Your original issue may now be fixed ✅ in PR #6285. This PR adds a new `is_kaggle()` function and only updates root logger removal to only occur on `is_kaggle() == True`.

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
