### ISSUE TITLE
background images

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#6281]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

- Background images. Background images are images with no objects that are added to a dataset to reduce False Positives (FP). We recommend about 0-10% background images to help reduce FPs (COCO has 1000 background images for reference, 1% of the total). No labels are required for background images.

How do you research the about 0-10% background images can improve result?

If I only have two classes person and vehicle. I let the other images in COCO as background.
The rate of  background images will over than 10%

**Comment by glenn-jocher** [comment]
@alicera 0-10% is based on empirical results with client datasets. You can add as many or as little background images as you want per your custom dataset to reduce FPs.

**Comment by Fatih-Haslak** [comment]
What is the background image. I want to a image example please.

**Comment by glenn-jocher** [comment]
@pantum61 just an image with no objects in your classes.

**Comment by Fatih-Haslak** [comment]
> @pantum61 just an image with no objects in your classes.

Thank you very much. I trying to detect traffic sign in real time.
