### ISSUE TITLE
I receive this code and I have problem with the programmer need help

### ISSUE THREAD

**Issue by besbesmany** [ultralytics/yolov5#6282]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Dear friends
I want to know in this code 
1) what is these numbers (0.026s) at this lines means , he told me it is the velocity of moving objects inside each frame!
video 1/1 (28069/51201) /content/drive/MyDrive/YOLOv5-DeepSort/Road_traffic.mp4: 384x640 8 cars, Done. (0.026s)
2) to run this code I must have files named detect_customize.py  and detect_track.py or not? because these files not exists in the code folders and this is the main work of the project? so the code not run at all!
3) is the code works with colab of google or not? he told me the code works on jupyterlab only!
4) can this code work on both cpu and  Gpu or only GPU? he told me the code can't work on cpu !

![problem](https://user-images.githubusercontent.com/35992924/149286110-59833623-83be-46cd-b665-cc2b60d7d58f.png)

**Comment by glenn-jocher** [comment]
@besbesmany seems like you should ask on the YOLOv5 deepsort repo.
