### ISSUE TITLE
error in coreml export.py

### ISSUE THREAD

**Issue by mattrichard-datascience** [ultralytics/yolov5#6284]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Export

### Bug

CoreML: export failure: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host 
memory first.

### Environment

google colab
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

error comes up when running;
!python export.py --weights yolov5s.pt --include coreml --imgsz 640 640 --device 0 

### Minimal Reproducible Example

!python export.py --weights yolov5s.pt --include coreml --imgsz 640 640 --device 0 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@mattrichard-datascience CoreML is incompatible with CUDA devices, i.e. CoreML models will never run on a GPU, only CPU on MacOS and ANE on iOS.
