### ISSUE TITLE
how to train grayscale images (sigle channel) on yolov5

### ISSUE THREAD

**Issue by BossCrab-jyj** [ultralytics/yolov5#6288]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

    if pretrained:
        with torch_distributed_zero_first(rank):
            attempt_download(weights)  # download if not found locally
        ckpt = torch.load(weights, map_location=device)  # load checkpoint
        if hyp.get('anchors'):
            ckpt['model'].yaml['anchors'] = round(hyp['anchors'])  # force autoanchor
        model = Model(opt.cfg or ckpt['model'].yaml, ch=3, nc=nc).to(device)  # create
        exclude = ['anchor'] if opt.cfg or hyp.get('anchors') else []  # exclude keys
        state_dict = ckpt['model'].float().state_dict()  # to FP32
        state_dict = intersect_dicts(state_dict, model.state_dict(), exclude=exclude)  # intersect
        model.load_state_dict(state_dict, strict=False)  # load
        logger.info('Transferred %g/%g items from %s' % (len(state_dict), len(model.state_dict()), weights))  # report
    else:
        model = Model(opt.cfg, **ch=1**, nc=nc).to(device)  # create

My pictures are grayscale images. There is no need to use 3 channels，so I have modify input channel "ch=1",but will get erro "RuntimeError: Given groups=1, weight of size [32, 4, 3, 3], expected input[8, 12, 400, 400] to have 4 channels, but got 12 channels instead", Can you tell me how to train single channel  on yolov5? Thanks！

**Comment by bzisl** [comment]
Did you got a solution? I'm at same case.

**Comment by glenn-jocher** [comment]
@yingjie-jiang @bzisl thanks for your feedback! Greyscale training is in our YOLOv5 roadmap, but I can't provide an exact date for this feature at the moment.

**Comment by nlm-yuh5** [comment]
I'm dealing with problem by using NxNx3 image with duplicated channels. This seems to work well. However, @glenn-jocher can you point me to the code for color normalization of input data?

**Comment by glenn-jocher** [comment]
@nlm-yuh5 I don't do any manual normalization, I let the batchnorm layers take care of that.

**Comment by glenn-jocher** [comment]
@nlm-yuh5 there is a rescaling in all the dataloaders though if that's what you mean, from 0-255 int8 to 0-1 floats

**Comment by nlm-yuh5** [comment]
Yes, I meant rescaling to [0,1]

**Comment by glenn-jocher** [comment]
@nlm-yuh5 oh, well the /255 rescaling is in every dataloader. Just go to utils/datasets.py and search for 255 to the see the implementations.

**Comment by nlm-yuh5** [comment]
I did. But didn't find anything

**Comment by nlm-yuh5** [comment]
I found it in train.py:

[`imgs = imgs.to(device, non_blocking=True).float() / 255.0  # uint8 to float32, 0-255 to 0.0-1.0`](https://github.com/ultralytics/yolov5/blob/b75c432ea0b35b44ba364bc6acadfc85f7dddf73/train.py#L265)

So, you only divide each value by 255, no normalization

**Comment by glenn-jocher** [comment]
@nlm-yuh5 also FYI no action is required on your part to train greyscale, you just train normally. COCO contains a thousand greyscale images for example. The YOLOv5 cv2 dataloaders expand these as required to create 3ch images.

**Comment by jnulzl** [comment]
## To train gray image(single channel), you should:

- 1、Add `ch` argument in your MODEL.yaml, if it's not exist:

```yaml
# Parameters
......
nc: 80  
ch: 1 # input channels
depth_multiple: 0.33  
width_multiple: 0.50  
......
```

- 2、Modify `class LoadImagesAndLabels(Dataset)` in `utils/datasets.py`

From 

```python
class LoadImagesAndLabels(Dataset):
	......
	
	def __getitem__(self, index):
		......
	
        # Convert
        img = img.transpose((2, 0, 1))[::-1]  # HWC to CHW, BGR to RGB
        img = np.ascontiguousarray(img)
		......
```
to 

```python
class LoadImagesAndLabels(Dataset):
	......
	
	def __getitem__(self, index):
		......
	
        # Convert
        if 'USE_GRAY_INPUT' in os.environ and os.environ['USE_GRAY_INPUT']:
            img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) # bgr to gray
            img = img.reshape([1, *img.shape]) # HW to CHW
        else:
            img = img.transpose((2, 0, 1))[::-1]  # HWC to CHW, BGR to RGB
			
        img = np.ascontiguousarray(img)	
		......
```

- 3、You should also modify other ` img = img.transpose((2, 0, 1))[::-1]` in `utils/datasets.py` for using `detect.py`

- 4、Train

	- For Linux user
	```shell
	>> USE_GRAY_INPUT=1 python train.py ... # train gray image
	[>> USE_GRAY_INPUT= python train.py ... # train color image]
	```
	
	- For Windows user
	
	```shell
	>> set USE_GRAY_INPUT=1 # train gray image
	[>> set USE_GRAY_INPUT= # train color image]
	>> python train.py ...
	```

**Comment by jnulzl** [comment]
> ## To train gray image(single channel), you should:
> * 1、Add `ch` argument in your MODEL.yaml, if it's not exist:
> 
> ```yaml
> # Parameters
> ......
> nc: 80  
> ch: 1 # input channels
> depth_multiple: 0.33  
> width_multiple: 0.50  
> ......
> ```
> 
> * 2、Modify `class LoadImagesAndLabels(Dataset)` in `utils/datasets.py`
> 
> From
> 
> ```python
> class LoadImagesAndLabels(Dataset):
> 	......
> 	
> 	def __getitem__(self, index):
> 		......
> 	
>         # Convert
>         img = img.transpose((2, 0, 1))[::-1]  # HWC to CHW, BGR to RGB
>         img = np.ascontiguousarray(img)
> 		......
> ```
> 
> to
> 
> ```python
> class LoadImagesAndLabels(Dataset):
> 	......
> 	
> 	def __getitem__(self, index):
> 		......
> 	
>         # Convert
>         if 'USE_GRAY_INPUT' in os.environ and os.environ['USE_GRAY_INPUT']:
>             img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) # bgr to gray
>             img = img.reshape([1, *img.shape]) # HW to CHW
>         else:
>             img = img.transpose((2, 0, 1))[::-1]  # HWC to CHW, BGR to RGB
> 			
>         img = np.ascontiguousarray(img)	
> 		......
> ```
> 
> * 3、You should also modify other ` img = img.transpose((2, 0, 1))[::-1]` in `utils/datasets.py` for using `detect.py`
> * 4、Train
>   
>   * For Linux user
>   
>   ```shell
>    >> USE_GRAY_INPUT=1 python train.py ... # train gray image
>    [>> USE_GRAY_INPUT= python train.py ... # train color image]
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   
>   * For Windows user
>   
>   ```shell
>    >> set USE_GRAY_INPUT=1 # train gray image
>    [>> set USE_GRAY_INPUT= # train color image]
>    >> python train.py ...
>   ```

## *!!!Under the same conditions(same model, same input size, .....), rgb is better than gray, especially for small input size, such as: 256, 320 or small detect objects.*

**Comment by bzisl** [comment]
Thanks!
ready to test!!!

> El 12 abr 2022, a las 13:33, jnulzl ***@***.***> escribió:
> 
> COLOR_BGR2GRAY

============================
Paco Blasco  -  BZ Invest SL

email: ***@***.***
phone: +34 615 237 233 
skype: paco.blasco
gmail: ***@***.***

BZ Invest SL
Buenos Aires 4
46360 Buñol
Valencia (Spain)
============================

**Comment by Half-Newbie** [comment]
> > ## 要训​​练灰度图像（单通道），您应该：
> > 
> > * 1、`ch`在你的 MODEL.yaml 中添加参数，如果它不存在：
> > 
> > ```yaml
> > #参数
> > ... ... 
> > nc : 80   
> > ch : 1  #输入通道
> > depth_multiple : 0.33   
> > width_multiple : 0.50   
> > ... ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * 2、修改`class LoadImagesAndLabels(Dataset)`在`utils/datasets.py`
> > 
> > 从
> > ```python
> > class  LoadImagesAndLabels ( Dataset ): 
> > 	...... def __getitem__ ( self , index ): 
> > 		...... # 转换img = img . transpose (( 2 , 0 , 1 ))[:: - 1 ]   # HWC 到 CHW，BGR 到 RGB img = np . 作为连续数组（img）
> > 		......
> > 	
> > 	 
> > 	
> >         
> >           
> >           
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 到
> > ```python
> > class  LoadImagesAndLabels ( Dataset ): 
> > 	...... def __getitem__ ( self , index ): 
> > 		...... # 转换if 'USE_GRAY_INPUT' in os。环境和操作系统。环境[ 'USE_GRAY_INPUT' ]：
> >              img = cv2。cvtColor ( img , cv2.COLOR_BGR2GRAY ) #bgr转灰色img = img . 重塑([ 1
> > 	
> > 	 
> > 	
> >         
> >                
> >               , *图像。shape ]) # HW to CHW 
> >         else :
> >              img  =  img . transpose (( 2 , 0 , 1 ))[:: - 1 ]   # HWC 到 CHW，BGR 到 RGB 
> > 			
> >         img  =  np . 作为连续数组（img）	 
> > 		......
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * 3、您还应该修改其他` img = img.transpose((2, 0, 1))[::-1]`in`utils/datasets.py`以供使用`detect.py`
> > * 4、火车
> >   
> >   * 对于 Linux 用户
> >   
> >   ```shell
> >    >> USE_GRAY_INPUT=1 python train.py ... #训练灰度图像
> >    [ >> USE_GRAY_INPUT = python train.py ... #训练彩色图像]
> >   ```
> >   
> >   
> >       
> >         
> >       
> >   
> >         
> >       
> >   
> >       
> >     
> >   
> >   * 对于 Windows 用户
> >   
> >   ```shell
> >    >>  set USE_GRAY_INPUT=1 #训练灰度图像
> >    [ >>  set USE_GRAY_INPUT =  #训练彩色图像] 
> >    >> python train.py ...
> >   ```
> 
> ## _!!!在相同的条件下（相同的模型，相同的输入尺寸，.....），RGB优于灰色，特别是对于小输入尺寸，例如：256、320或小检测物体。_



> ## To train gray image(single channel), you should:
> * 1、Add `ch` argument in your MODEL.yaml, if it's not exist:
> 
> ```yaml
> # Parameters
> ......
> nc: 80  
> ch: 1 # input channels
> depth_multiple: 0.33  
> width_multiple: 0.50  
> ......
> ```
> 
> * 2、Modify `class LoadImagesAndLabels(Dataset)` in `utils/datasets.py`
> 
> From
> 
> ```python
> class LoadImagesAndLabels(Dataset):
> 	......
> 	
> 	def __getitem__(self, index):
> 		......
> 	
>         # Convert
>         img = img.transpose((2, 0, 1))[::-1]  # HWC to CHW, BGR to RGB
>         img = np.ascontiguousarray(img)
> 		......
> ```
> 
> to
> 
> ```python
> class LoadImagesAndLabels(Dataset):
> 	......
> 	
> 	def __getitem__(self, index):
> 		......
> 	
>         # Convert
>         if 'USE_GRAY_INPUT' in os.environ and os.environ['USE_GRAY_INPUT']:
>             img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) # bgr to gray
>             img = img.reshape([1, *img.shape]) # HW to CHW
>         else:
>             img = img.transpose((2, 0, 1))[::-1]  # HWC to CHW, BGR to RGB
> 			
>         img = np.ascontiguousarray(img)	
> 		......
> ```
> 
> * 3、You should also modify other ` img = img.transpose((2, 0, 1))[::-1]` in `utils/datasets.py` for using `detect.py`
> * 4、Train
>   
>   * For Linux user
>   
>   ```shell
>    >> USE_GRAY_INPUT=1 python train.py ... # train gray image
>    [>> USE_GRAY_INPUT= python train.py ... # train color image]
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   
>   * For Windows user
>   
>   ```shell
>    >> set USE_GRAY_INPUT=1 # train gray image
>    [>> set USE_GRAY_INPUT= # train color image]
>    >> python train.py ...
>   ```



> ## To train gray image(single channel), you should:
> * 1、Add `ch` argument in your MODEL.yaml, if it's not exist:
> 
> ```yaml
> # Parameters
> ......
> nc: 80  
> ch: 1 # input channels
> depth_multiple: 0.33  
> width_multiple: 0.50  
> ......
> ```
> 
> * 2、Modify `class LoadImagesAndLabels(Dataset)` in `utils/datasets.py`
> 
> From
> 
> ```python
> class LoadImagesAndLabels(Dataset):
> 	......
> 	
> 	def __getitem__(self, index):
> 		......
> 	
>         # Convert
>         img = img.transpose((2, 0, 1))[::-1]  # HWC to CHW, BGR to RGB
>         img = np.ascontiguousarray(img)
> 		......
> ```
> 
> to
> 
> ```python
> class LoadImagesAndLabels(Dataset):
> 	......
> 	
> 	def __getitem__(self, index):
> 		......
> 	
>         # Convert
>         if 'USE_GRAY_INPUT' in os.environ and os.environ['USE_GRAY_INPUT']:
>             img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) # bgr to gray
>             img = img.reshape([1, *img.shape]) # HW to CHW
>         else:
>             img = img.transpose((2, 0, 1))[::-1]  # HWC to CHW, BGR to RGB
> 			
>         img = np.ascontiguousarray(img)	
> 		......
> ```
> 
> * 3、You should also modify other ` img = img.transpose((2, 0, 1))[::-1]` in `utils/datasets.py` for using `detect.py`
> * 4、Train
>   
>   * For Linux user
>   
>   ```shell
>    >> USE_GRAY_INPUT=1 python train.py ... # train gray image
>    [>> USE_GRAY_INPUT= python train.py ... # train color image]
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   
>   * For Windows user
>   
>   ```shell
>    >> set USE_GRAY_INPUT=1 # train gray image
>    [>> set USE_GRAY_INPUT= # train color image]
>    >> python train.py ...
>   ```

If I want to use `detect.py` to detect single channel images
`set USE_GRAY_INPUT=1
python detect.py`
Is this command correct?I use this command ,but the `detect.py` can't work and the error message is
`RuntimeError: Given groups=1, weight of size [32, 4, 3, 3], expected input[1, 12, 320, 320] to have 4 channels, but got 12 chann
els instead
`
Can you tell me how to modify it? Thanks!

**Comment by Half-Newbie** [comment]
> > ## To train gray image(single channel), you should:
> > 
> > * 1、Add `ch` argument in your MODEL.yaml, if it's not exist:
> > 
> > ```yaml
> > # Parameters
> > ......
> > nc: 80  
> > ch: 1 # input channels
> > depth_multiple: 0.33  
> > width_multiple: 0.50  
> > ......
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * 2、Modify `class LoadImagesAndLabels(Dataset)` in `utils/datasets.py`
> > 
> > From
> > ```python
> > class LoadImagesAndLabels(Dataset):
> > 	......
> > 	
> > 	def __getitem__(self, index):
> > 		......
> > 	
> >         # Convert
> >         img = img.transpose((2, 0, 1))[::-1]  # HWC to CHW, BGR to RGB
> >         img = np.ascontiguousarray(img)
> > 		......
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to
> > ```python
> > class LoadImagesAndLabels(Dataset):
> > 	......
> > 	
> > 	def __getitem__(self, index):
> > 		......
> > 	
> >         # Convert
> >         if 'USE_GRAY_INPUT' in os.environ and os.environ['USE_GRAY_INPUT']:
> >             img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) # bgr to gray
> >             img = img.reshape([1, *img.shape]) # HW to CHW
> >         else:
> >             img = img.transpose((2, 0, 1))[::-1]  # HWC to CHW, BGR to RGB
> > 			
> >         img = np.ascontiguousarray(img)	
> > 		......
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * 3、You should also modify other ` img = img.transpose((2, 0, 1))[::-1]` in `utils/datasets.py` for using `detect.py`
> > * 4、Train
> >   
> >   * For Linux user
> >   
> >   ```shell
> >    >> USE_GRAY_INPUT=1 python train.py ... # train gray image
> >    [>> USE_GRAY_INPUT= python train.py ... # train color image]
> >   ```
> >   
> >   
> >       
> >         
> >       
> >   
> >         
> >       
> >   
> >       
> >     
> >   
> >   * For Windows user
> >   
> >   ```shell
> >    >> set USE_GRAY_INPUT=1 # train gray image
> >    [>> set USE_GRAY_INPUT= # train color image]
> >    >> python train.py ...
> >   ```
> 
> ## _!!!Under the same conditions(same model, same input size, .....), rgb is better than gray, especially for small input size, such as: 256, 320 or small detect objects._

If I want to use `detect.py` to detect single channel images
`set USE_GRAY_INPUT=1 
python detect.py`
Is this command correct? I use this command ,but the `detect.py` can't work and the error message is
`RuntimeError: Given groups=1, weight of size [32, 4, 3, 3], expected input[1, 12, 320, 320] to have 4 channels, but got 12 chann els instead`
Can you tell me how to modify it? Thanks!

**Comment by Half-Newbie** [comment]
> > ## To train gray image(single channel), you should:
> > 
> > * 1、Add `ch` argument in your MODEL.yaml, if it's not exist:
> > 
> > ```yaml
> > # Parameters
> > ......
> > nc: 80  
> > ch: 1 # input channels
> > depth_multiple: 0.33  
> > width_multiple: 0.50  
> > ......
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * 2、Modify `class LoadImagesAndLabels(Dataset)` in `utils/datasets.py`
> > 
> > From
> > ```python
> > class LoadImagesAndLabels(Dataset):
> > 	......
> > 	
> > 	def __getitem__(self, index):
> > 		......
> > 	
> >         # Convert
> >         img = img.transpose((2, 0, 1))[::-1]  # HWC to CHW, BGR to RGB
> >         img = np.ascontiguousarray(img)
> > 		......
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to
> > ```python
> > class LoadImagesAndLabels(Dataset):
> > 	......
> > 	
> > 	def __getitem__(self, index):
> > 		......
> > 	
> >         # Convert
> >         if 'USE_GRAY_INPUT' in os.environ and os.environ['USE_GRAY_INPUT']:
> >             img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) # bgr to gray
> >             img = img.reshape([1, *img.shape]) # HW to CHW
> >         else:
> >             img = img.transpose((2, 0, 1))[::-1]  # HWC to CHW, BGR to RGB
> > 			
> >         img = np.ascontiguousarray(img)	
> > 		......
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * 3、You should also modify other ` img = img.transpose((2, 0, 1))[::-1]` in `utils/datasets.py` for using `detect.py`
> > * 4、Train
> >   
> >   * For Linux user
> >   
> >   ```shell
> >    >> USE_GRAY_INPUT=1 python train.py ... # train gray image
> >    [>> USE_GRAY_INPUT= python train.py ... # train color image]
> >   ```
> >   
> >   
> >       
> >         
> >       
> >   
> >         
> >       
> >   
> >       
> >     
> >   
> >   * For Windows user
> >   
> >   ```shell
> >    >> set USE_GRAY_INPUT=1 # train gray image
> >    [>> set USE_GRAY_INPUT= # train color image]
> >    >> python train.py ...
> >   ```
> 
> ## _!!!Under the same conditions(same model, same input size, .....), rgb is better than gray, especially for small input size, such as: 256, 320 or small detect objects._


If I want to use `detect.py` to detect single channel images
`set USE_GRAY_INPUT=1 
python detect.py`
Is this command correct? I use this command ,but the `detect.py` can't work and the error message is
`RuntimeError: Given groups=1, weight of size [32, 4, 3, 3], expected input[1, 12, 320, 320] to have 4 channels, but got 12 chann els instead`
Can you tell me how to modify it? Thanks! @jnulzl

**Comment by glenn-jocher** [comment]
@Half-Newbie YOLOv5 upscales any grayscale images to 3 channel automatically during training and inference. This allows for usage of RGB, Grey and hybrid datasets. No changes are required.

**Comment by Half-Newbie** [comment]
> @Half-Newbie YOLOv5 upscales any grayscale images to 3 channel automatically during training and inference. This allows for usage of RGB, Grey and hybrid datasets. No changes are required.

Thanks! 
Just now I went to try to train  single channel images, and indeed it does not need any modification.
I'm new to YOLOv5.Can you tell me the code related to channel number conversion is in which file?
`datasets.py`?

**Comment by glenn-jocher** [comment]
@Half-Newbie yes, dataloaders.py (recently renamed from datasets.py) contains all dataloaders:
https://github.com/ultralytics/yolov5/blob/master/utils/dataloaders.py

**Comment by Half-Newbie** [comment]
> @Half-Newbie yes, dataloaders.py (recently renamed from datasets.py) contains all dataloaders: https://github.com/ultralytics/yolov5/blob/master/utils/dataloaders.py

I will read it carefully.
Thanks for your help.
