### ISSUE TITLE
Pytorch advanced indexing on GPU may cause error

### ISSUE THREAD

**Issue by hieuth133** [ultralytics/yolov5#6289]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I notice this line on loss.py that may cause error while running on GPU, as the order in which updates are applied is nondeterministic, especially when some of indices are duplicated. From my knowledge, the duplicated indices happened when many boxes lie in same 'grid space'. But somehow the training is still correct? Is there any way to remove duplicate in the code or some other thing?

Here is the code:
`tobj[b, a, gj, gi] = (1.0 - self.gr) + self.gr * score_iou  # iou ratio`
https://github.com/ultralytics/yolov5/blob/master/utils/loss.py#L143

**Comment by glenn-jocher** [comment]
@hieuth133 hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
