### ISSUE TITLE
Can we get object detection on lidar 2d stream with yolov5?

### ISSUE THREAD

**Issue by Shibaditya99** [ultralytics/yolov5#6293]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have an ouster lidar, where I can generate 2D field streams. so is it possible to detect objects on that stream using yolov5?

### Additional

If I also want to detect objects with thermal cam data using yolov5, is it possible?

**Comment by glenn-jocher** [comment]
@Shibaditya99 any 2d 3-channel labelled data is trainable off the shelf. n-channel with a few tweaks.
