### ISSUE TITLE
Something special at the last epoch of training ? 

### ISSUE THREAD

**Issue by joihn** [ultralytics/yolov5#6295]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm extending the framework with some extra code for keypoints detection.
Does something special happens at the last epoch of training ? My loss and metrics **behaves very weirdly** at the last epoch.
![image](https://user-images.githubusercontent.com/11663917/149517607-6e3cd04c-566e-4fc8-a874-5f68da56c443.png)
![image](https://user-images.githubusercontent.com/11663917/149517878-49ef3c19-2c32-4b57-9a55-bc500963a9af.png)

**Comment by glenn-jocher** [comment]
@joihn that is pretty strange. When training completes a standalone val.py call is made here. The results are not supposed to differ substantially, the intention is to produce final metrics that will match what you would see if you call val.py manually with your best.pt:

https://github.com/ultralytics/yolov5/blob/a1a9c6884c5cfda4c972f4087ad4d4b9c3da6518/train.py#L420-L443

EDIT: also this val.py call will display metrics per class, it's more verbose than during training.

**Comment by joihn** [comment]
thanks a lot for the pointer, I'll manage to troubleshoot with this valuable info

**Comment by joihn** [comment]
for future ref, the bug came from utils/loggers/__init__.py:, line 155

`self.wandb.log({k: v for k, v in zip(self.keys[3:10], results)})  # log best.pt val results`
I added some custom keys and metrics, therefore `3:10` needed to be changed
