### ISSUE TITLE
Loaded pretrained weights with a different number of class

### ISSUE THREAD

**Issue by joihn** [ultralytics/yolov5#6296]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

what happends when loaded pretrained weight but the number of classes is different ? I guess it just skip loaded the last part of the net called detect() ?

**Comment by glenn-jocher** [comment]
@joihn if you pass both a --cfg model.yaml and --weights model.pt, a new model is constructed from your yaml and then any matching layers are transferred over from your *.pt file. 

A report on the number of transferred layers is shown on screen, i.e. 'transferred 370/421 layers'
