### ISSUE TITLE
Potential Bug in Calculating Dataloader num_workers in Multi-node environment

### ISSUE THREAD

**Issue by sitecao** [ultralytics/yolov5#6298]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

From the line below, it looks like the num_workers will be a function of the cluster size and decrease as cluster size increases. (in my use case os.cpu_count() // WORLD_SIZE is always taken to be value of nw)
https://github.com/ultralytics/yolov5/blob/e7bf38277f57086bf37486201909e9c04acfaa48/utils/datasets.py#L113

For example, a p4d instance has 96 vCPUs and 8 GPUs. If we were to use a cluster of size 2, WORLD_SIZE will be 16 and we will have nw = 96 // 16 = 6. And if we have 8 nodes, WORLD_SIZE will be 64 and nw = 96 // 64 = 1.

From the reply from the author on below (unrelated) issue, it seems like this model has not been officially tested on a multi-node environment and I think this may be a potential bug. Can you please confirm on this? I think the intention of the author is os.cpu_count() //  torch.cuda.device_count()?
https://github.com/ultralytics/yolov5/issues/1445#issuecomment-732097577

**Comment by glenn-jocher** [comment]
@sitecao yes that's correct. We've used single P4d instances for training but not scaled to multi-node training, so it's possible there are multi-node bugs latent in the code.

The intention of `os.cpu_count() // WORLD_SIZE` is to use 96/8 = 12 workers on a P4d instance per RANK, i.e. to use all the available resources on a node whether it's Multi-GPU training or just 8 single-GPU trainings.

It seems like we should divide WORLD_SIZE by a node count. Is that possible?

If you can confirm a fix and submit a PR (making sure it doesn't alter the single-node behavior) I'll get that fast tracked. Thanks!
