### ISSUE TITLE
Cannot find reference 'hardtanh' in 'functional.py' 

### ISSUE THREAD

**Issue by Lornatang** [ultralytics/yolov5#63]
## 🐛 Bug
Cannot find reference 'hardtanh' in 'functional.py'  in `yolov5.utils.activations.py` 29 line

## To Reproduce

change`import torch.functional as F` to `import torch.nn.functional as F`
```
python train.py 
```

## Expected behavior

fix error message.

## Environment

 - OS: [Ubuntu18.04]
 - GPU [2080 Ti]

## Additional context
None

**Comment by glenn-jocher** [comment]
@Lornatang thank you for the bug report! Could you please submit a pull request with your proposed fix?
