### ISSUE TITLE
Transferred 794/802 items from weights/yolov5x.pt

### ISSUE THREAD

**Issue by Pluto1314** [ultralytics/yolov5#630]
## Additional context
When I use the pre training model to train my own data, do I find that the model does not fit perfectly? Why 794 / 802, not 802 / 802?
My category is only 1.
`CUDA_VISIBLE_DEVICES=4,5,6,7 python -m torch.distributed.launch --nproc_per_node 4 train.py --batch-size 64 --data data/tiny_data.yaml --cfg yolov5x.yaml --weights 'weights/yolov5x.pt' --cache --single-cls --rect --device 4,5,6,7`

**Comment by NanoCode012** [comment]
Anchors are excluded. https://github.com/ultralytics/yolov5/blob/728efa6576eae595ddcfdd8b75ab5da40ddfcaf4/train.py#L142-L147
See https://github.com/ultralytics/yolov5/issues/459

**Comment by Pluto1314** [comment]
@NanoCode012 thanks, you are right!
So when I use '-- noautoanchor', I should get 802 / 802?

**Comment by NanoCode012** [comment]
No, I don't think so. Looking at the code, `--noautoanchor` just doesn't call the line below. It doesn't try to find the BestFit anchors.
https://github.com/ultralytics/yolov5/blob/728efa6576eae595ddcfdd8b75ab5da40ddfcaf4/train.py#L222-L224
