### ISSUE TITLE
Code of plotting train_batch*.jpg

### ISSUE THREAD

**Issue by iumyx2612** [ultralytics/yolov5#6305]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I like the way you help everyone visualize their model's input while training. I want to implement it but I can't find the code in your repo. Can you link it here?

**Comment by iumyx2612** [comment]
oh nvm I found it

**Comment by sezer-muhammed** [comment]
where is it?

**Comment by glenn-jocher** [comment]
@sezer-muhammed code to plot train_batch*.jpg images is here:
https://github.com/ultralytics/yolov5/blob/ff8646cdea57a1e81a381de37b881e55ab273777/utils/plots.py#L183-L242

**Comment by sezer-muhammed** [comment]
> @sezer-muhammed code to plot train_batch*.jpg images is here:
> 
> https://github.com/ultralytics/yolov5/blob/ff8646cdea57a1e81a381de37b881e55ab273777/utils/plots.py#L183-L242

thanks, but I still cannot understand where three sample images is produced and who decides how many images will be produced during training. I have some problems with labels or I guess so, so I need to produce 100-200 training batches to see if there is any mistake
How can I change it?

**Comment by glenn-jocher** [comment]
@sezer-muhammed you can change the number of plotted batches here on L91:
https://github.com/ultralytics/yolov5/blob/d5966c93f1855baec531c3585da247cded72247f/utils/loggers/__init__.py#L91-L93
