### ISSUE TITLE
模型输出的GFLOPs

### ISSUE THREAD

**Issue by Mengyao-Zhang** [ultralytics/yolov5#6306]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Other

### Bug

Which line in the script is the GFLOPs calculation?
 Why is it different from what I did with some tools?
 In addition, after I add Coordinate Attention and CA to the C3 module, the script will not output GFLOPs. How can I solve this problem?

![image](https://user-images.githubusercontent.com/70052576/149612142-fd02e37c-72af-4d67-ae10-3d464248b8a7.png)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@18846169373 GFLOPs are computed in the `model_info()` function using the `thop` package. The computation can fail sometimes with experimental layers etc., in which case no FLOPs value is displayed.

https://github.com/ultralytics/yolov5/blob/436ffc417ac2312de18287ddc4f87bdc2f7f5734/utils/torch_utils.py#L217-L239

**Comment by 18846169373** [comment]
> @18846169373 GFLOP是使用包在`model_info()`函数中计算的。`thop`计算有时会因实验层等而失败，在这种情况下，不会显示 FLOPs 值。
> 
> https://github.com/ultralytics/yolov5/blob/436ffc417ac2312de18287ddc4f87bdc2f7f5734/utils/torch_utils.py#L217-L239

Thank you for your busy reply. Using `PTFLOPS` instead of `thop` might output MACs.

`from ptflops import get_model_complexity_info`
`with torch.cuda.device(0):`
  `flops, params = get_model_complexity_info(model, (3,416,416), as_strings=True, print_per_layer_stat=True)`
  `  print('Flops: ' + flops)`
  `  print('Params: ' + params)`

**Comment by Mengyao-Zhang** [comment]
> @18846169373 GFLOP是使用包在`model_info()`函数中计算的。`thop`计算有时会因实验层等而失败，在这种情况下，不会显示 FLOPs 值。
> 
> https://github.com/ultralytics/yolov5/blob/436ffc417ac2312de18287ddc4f87bdc2f7f5734/utils/torch_utils.py#L217-L239

Thank you for your busy reply. Using `PTFLOPS` instead of `thop` might output MACs.

`from ptflops import get_model_complexity_info`
`with torch.cuda.device(0):`
  `flops, params = get_model_complexity_info(model, (3,416,416), as_strings=True, print_per_layer_stat=True)`
  `  print('Flops: ' + flops)`
  `  print('Params: ' + params)`

**Comment by glenn-jocher** [comment]
@18846169373 thanks for the suggestion. Have you seen ptflops succeed where thop fails for YOLOv5?

**Comment by Mengyao-Zhang** [comment]
> @18846169373感谢您的建议。您是否看到 ptflops 在 YOLOv5 的 thop 失败时成功？
Some of the experimental layers I added were successful, but the output is MACs metrics  .

**Comment by glenn-jocher** [comment]
@18846169373 it's ok. FLOPs is just MACs / 2. 

Would you like to help by submitting a PR using `ptflops` instead of `thop`?

**Comment by Mengyao-Zhang** [comment]
> @18846169373 it's ok. FLOPs is just MACs / 2.
> 
> Would you like to help by submitting a PR using `ptflops` instead of `thop`?

It is my pleasure.

**Comment by YOLOonMe** [comment]
from torchvision.models import resnet18
from nni.compression.pytorch.utils.counter import count_flops_params
model = resnet18()
dummy_input = torch.randn(1, 3, 224, 224)
flops, params, results = count_flops_params(model, dummy_input)

**Comment by zhiqwang** [comment]
```python
from torchvision.models import resnet18
from nni.compression.pytorch.utils.counter import count_flops_params
model = resnet18()
dummy_input = torch.randn(1, 3, 224, 224)
flops, params, results = count_flops_params(model, dummy_input)
```
@Jike-u , That's cool here, and this approach is worth trying! The only concern here is that the `nni` dependency is a bit large.

**Comment by lawo123** [comment]
> > @18846169373 it's ok. FLOPs is just MACs / 2.
> > Would you like to help by submitting a PR using `ptflops` instead of `thop`?
> 
> It is my pleasure.

Most papers (including the well-known ResNet paper)/toolboxes do not differentiate MACs and FLOPs. what do you mean  FLOPs is just MACs / 2 ?

**Comment by glenn-jocher** [comment]
One MAC contains one multiplication and one addition. One multiplication or one addition can be seen as one FLOP. So one MAC has two FLOPs.
