### ISSUE TITLE
Analyzing Components of an electric circuit with YOLOv5

### ISSUE THREAD

**Issue by prp-e** [ultralytics/yolov5#6307]
I made this fun project using YOLOv5 and I guess it's worth sharing here:

https://haghiri75.com/en/analyzing-components-of-an-electric-circuit-with-yolov5/

**Comment by iceisfun** [comment]
if you do any more work with this you might draw some circuit like images that do not contain any real components and add them to a background class.

you could also add some symbols from other hand drawn schematics, the old radio shack project books come to mind.

and you might try label studio too, i've found it to be better than labelimg.. it runs in docker and has a much cleaner interface.

**Comment by prp-e** [comment]
> if you do any more work with this you might draw some circuit like images that do not contain any real components and add them to a background class.

Nice point. I guess it is somehow needed, as some schematics may have some non-recognizable components or may have used a notation or symbol system which is not used by most people. 

> you could also add some symbols from other hand drawn schematics, the old radio shack project books come to mind.

Great idea. I also may call my colleagues and friends who are electrical engineers. 

> and you might try label studio too, i've found it to be better than labelimg.. it runs in docker and has a much cleaner interface.

I'll give it a try. Thanks @iceisfun for your kind feedback.
