### ISSUE TITLE
Question about yolov5 overlap detection 

### ISSUE THREAD

**Issue by zentorno365** [ultralytics/yolov5#631]
## ❔Question

Hi glenn,

If my dataset has 2 overlapping labels would they both be detected or only the outer layer is detected?.

Means like if there is a face label and inside got another eyes label will both labels be detected?.

I tried with my dataset and after training i couldnt see the eyes label.

Thank you

**Comment by glenn-jocher** [comment]
I would recommend you look at the coco dataset for typical data. I don't advise or comment on custom datasets for free.
