### ISSUE TITLE
Unable to run val.py on VOC dataset... Any help would be greatly appreciated :)

### ISSUE THREAD

**Issue by TravHaran** [ultralytics/yolov5#6310]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

So far I've successfully evaluated YoloV5 models for the COCO dataset by using the val.py script.
Next I tried to do the same for the VOC dataset, and the script autodownloaded VOC under the proper directory for me, so I  know that the dataset is formatted properly and under the correct directory.

Next, within the yolov5 directory I run the val.py script: 
`python3 ./val.py --weights ./yolov5s-fp16.tflite --data ./data/VOC.yaml --img 640`

Then I get a handle full errors: 
- 'Exception in thread Thread-3'
- 'KeyError: 77'
- 'KeyError: 41'
- 'IndexError: index 56 is out of bounds for axis 0 with size 21

**So what I want to know is if anyone has tried to run val.py for a yolov5 model on the VOC dataset, and if so have they run into a similar error as mine. @glenn-jocher**

Here is the full Console Output I get:

(p37_venv) (base) travisratnaharan@DLM-TRATNAHARAN yolov5 % python3 ./val.py --weights ./yolov5s-fp16.tflite --data ./data/VOC.yaml --img 640
val: data=./data/VOC.yaml, weights=['./yolov5s-fp16.tflite'], batch_size=32, imgsz=640, conf_thres=0.001, iou_thres=0.6, task=val, device=, workers=8, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=runs/val, name=exp, exist_ok=False, half=False, dnn=False
YOLOv5 🚀 v6.0-184-g6865d19 torch 1.10.1 CPU

Loading yolov5s-fp16.tflite for TensorFlow Lite inference...
Forcing --batch-size 1 square inference shape(1,3,640,640) for non-PyTorch backends
val: Scanning '../datasets/VOC/labels/test2007.cache' images and labels... 4952 found, 0 missing, 0 empty, 0 corrupted: 100%|█████████████████████████████████████| 4952/4952 [00:00<?, ?it/s]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95:   0%|          | 1/4952 [00:00<19:43,  4.18it/s]                                                      Exception in thread Thread-3:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/travisratnaharan/Documents/Work/Deeplite/YoloV5Eval/yolov5/utils/plots.py", line 237, in plot_images
    cls = names[cls] if names else cls
KeyError: 77

               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95:   0%|          | 2/4952 [00:00<17:14,  4.78it/s]                                                      Exception in thread Thread-5:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/travisratnaharan/Documents/Work/Deeplite/YoloV5Eval/yolov5/utils/plots.py", line 237, in plot_images
    cls = names[cls] if names else cls
KeyError: 41

               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95:   0%|          | 2/4952 [00:00<25:11,  3.27it/s]                                                      
Traceback (most recent call last):
  File "./val.py", line 382, in <module>
    main(opt)
  File "./val.py", line 355, in main
    run(**vars(opt))
  File "/Users/travisratnaharan/p37_venv/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "./val.py", line 232, in run
    confusion_matrix.process_batch(predn, labelsn)
  File "/Users/travisratnaharan/Documents/Work/Deeplite/YoloV5Eval/yolov5/utils/metrics.py", line 156, in process_batch
    self.matrix[detection_classes[m1[j]], gc] += 1  # correct
IndexError: index 56 is out of bounds for axis 0 with size 21

**Comment by glenn-jocher** [comment]
@TravHaran val.py works correctly for custom trained models on any dataset, i.e.:

```bash
# Train a YOLOv5s VOC model
python train.py --batch 64 --weights yolov5s.pt --data VOC.yaml --epochs 50 --cache --img 512 --nosave --hyp hyp.finetune.yaml

# Validate best.pt
python val.py --data VOC.yaml --weights runs/exp/train/weights/best.pt
```

<img width="1175" alt="Screen Shot 2022-01-16 at 12 45 12 PM" src="https://user-images.githubusercontent.com/26833433/149681190-505ad0e3-1056-4fdc-8869-ba8f86f576ea.png">

Exported models should work as well.

**Comment by glenn-jocher** [comment]
TFLite with val.py works correctly:
<img width="1323" alt="Screen Shot 2022-01-16 at 1 13 17 PM" src="https://user-images.githubusercontent.com/26833433/149682125-60c2bb12-d57c-4d02-bd12-620a363b48a3.png">

**Comment by nicolexirakia** [comment]
@glenn-jocher I am experiencing the same issue when simply validating `yolov5s.pt` on VOC.yaml. As I understand, this is happening because `yolov5s` is trained on coco which has 80 classes and VOC contains only 20 classes. Therefore, when we predict an object with e.g. class ID 57, it runs our of bounds on the matrix containing the 20 labels of VOC. The only workaround is to simply execute the validation as single class, or on an dataset that has an equal amount of labels as the model was trained on.

**Comment by glenn-jocher** [comment]
@nicolexirakia I don't understand what you're asking. Usage example for training and validating VOC is very simple and everything works correctly:

```bash
python train.py --data VOC.yaml
python val.py --data VOC.yaml --weights path/to/best.pt
```

**Comment by nicolexirakia** [comment]
@glenn-jocher the question is rather as to what to expect. For instance, you can easily reproduce this error above just by running: ```python val.py --data VOC.yaml --weights yolov5s.pt```

I would expect that we should be able to validate the model's performance on any datasets that contain a subset of the classes that the model was trained on. A good example is the VOC dataset that contains 20 classes, and the yolov5s model that is trained on the coco dataset which contains 80 classes. I hope that the question is more clear now.

**Comment by glenn-jocher** [comment]
@nicolexirakia there is no error, instead your usage is incorrect. 

You train and validate on the same dataset. Pretrained models are trained on COCO, which is not VOC, hence your error is expected.
