### ISSUE TITLE
I have a question about mutil GPU

### ISSUE THREAD

**Issue by yangrisheng** [ultralytics/yolov5#6312]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

`python train.py --img 3600 --batch 4 --epochs 5 --data data1.yaml --weights yolov5m6.pt --name yy --hyp data/hyps/hyp.2.yaml --workers 0`
I use this code to train my model in my four GPUs. But I think this is a single GPU to run.But I meet a problem.
It is cost my four GPUs.Why? Could you tell me plz?
![Snipaste_2022-01-16_13-48-58](https://user-images.githubusercontent.com/39787375/149648970-ae8b003c-ebe1-4150-b442-b2a170d1ac72.png)

Best,
Kira

**Comment by iceisfun** [comment]
Try something like this, modify arguments as required.

```
python3 -m torch.distributed.launch --nproc_per_node 4 train.py \
    --img-size 640 \
    --batch-size 30 \
    --epochs 20 \
    --device 0,1,2,4 \
    --data /data/dataset/coco.yaml \
    --weights yolov5s.pt

```

**Comment by yangrisheng** [comment]
> 尝试这样的事情，根据需要修改参数。
> 
> ```
> python3 -m torch.distributed.launch --nproc_per_node 4 train.py \
>     --img-size 640 \
>     --batch-size 30 \
>     --epochs 20 \
>     --device 0,1,2,4 \
>     --data /data/dataset/coco.yaml \
>     --weights yolov5s.pt
> ```

Do you mean changing img size?

**Comment by iceisfun** [comment]
The important part is 

```
python3 -m torch.distributed.launch --nproc_per_node 4 train.py ...more args...
```

**Comment by yangrisheng** [comment]
> The important part is
> 
> ```
> python3 -m torch.distributed.launch --nproc_per_node 4 train.py ...more args...
> ```

Yeah.I use this command.This is another problem.And When I using this command, I failed to run the program.Stucking at the beginning of train.I don't know how to solve this.

**Comment by sdreamforchen** [comment]
I have the same problem, "subprocess.CalledProcessError: Command  returned non-zero exit status 1", when use the command above

**Comment by sdreamforchen** [comment]
When i don't use the commond " -m torch.distributed.launch --nproc_per_node 4  ", It can train, but another bug happen when 

- [ ] [val,] like this" RuntimeError: Unable to find a valid cuDNN algorithm to run convolution"

**Comment by glenn-jocher** [comment]
@sdreamforchen I would recommend the official Docker Image for all Multi-GPU DDP trainings to eliminate environment issues.

It appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual [Python 3.9](https://www.python.org/) environment, clone the latest repo ([code changes daily](https://github.com/ultralytics/yolov5/commits/master)), and `pip install` [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) again from scratch.

💡 ProTip! Try one of our verified environments below if you are having trouble with your local environment.


## Requirements

[**Python>=3.6.0**](https://www.python.org/) with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) installed including [**PyTorch>=1.7**](https://pytorch.org/get-started/locally/). To get started:
```bash
git clone https://github.com/ultralytics/yolov5  # clone
cd yolov5
pip install -r requirements.txt  # install
```

[Models](https://github.com/ultralytics/yolov5/tree/master/models) and [datasets](https://github.com/ultralytics/yolov5/tree/master/data) download automatically from the latest YOLOv5 [release](https://github.com/ultralytics/yolov5/releases) when first requested.

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), validation ([val.py](https://github.com/ultralytics/yolov5/blob/master/val.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/export.py)) on MacOS, Windows, and Ubuntu every 24 hours and on every commit.

**Comment by ShJacub** [comment]
> 

I have got the same problem. If you run it inside container, this is solved by using ultralytics docker image.

**Comment by yangrisheng** [comment]
> > 
> 
> 
> 
> I have got the same problem. If you run it inside container, this is solved by using ultralytics docker image.

new version has solved this problem.it is a bug.Now,it have solved.Thank you for your answer.

**Comment by sunyicode0012** [comment]
@yangrisheng  I have got the same problem. use YOLOV6.2 .why?
