### ISSUE TITLE
The question about pretrained weights

### ISSUE THREAD

**Issue by li624120638** [ultralytics/yolov5#6313]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Sorry,I'm a beginner.
I have a problem about pretrained weights:  
for example,my task is 10-classes,and two of these classes(person,bicycle) are the same as COCO.
I want to train my model without these two classes's datas and want my model to recognize these two classes of objects accurately.
How can I do this?

**Comment by glenn-jocher** [comment]
@li624120638 you must train on all classes you want to be able to detect, so if you want classes A and B to be detected your training set must include examples of A and B. Previously trained work will be forgotten quickly during training. See https://en.wikipedia.org/wiki/Catastrophic_interference

**Comment by li624120638** [comment]
> @li624120638 you must train on all classes you want to be able to detect, so if you want classes A and B to be detected your training set must include examples of A and B. Previously trained work will be forgotten quickly during training. See https://en.wikipedia.org/wiki/Catastrophic_interference
