### ISSUE TITLE
Isn't it better to fill mean pixel value instead of fixed gray pixels for mosaic & perspective augmentation?

### ISSUE THREAD

**Issue by bilzard** [ultralytics/yolov5#6314]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When using `mosaic`, `mosaic9`, `perspective_transformation`, and `letterbox` augmentation, background pixels are filled with gray pixels: `[114, 114, 114]` .
But isn't it natural to fill them in mean pixel value of the image?
I think it's better because it less affect batch statistics.

Or, if it is intentional, please tell me the reason.

Thanks

**Comment by glenn-jocher** [comment]
@bilzard 114 is the mean UINT8 imagenet intensity (from 0-255). 

The mosaic function and the perspective transform function only have access to a single image/mosaic, the full batch is not assembled until later by the collate function `collate_fn()`. In any case I don't think this background color is very important. I've experimented leaving it black (0) and training still produces about the same mAP.

The important thing is that ideally your deployed environment is handling image processing the same way (letterboxing, same background color etc.).

**Comment by bilzard** [comment]
> the full batch is not assembled until later by the collate function collate_fn()

I don't mean average pixel value of full batch, I mean average pixel of single image.

> The important thing is that ideally your deployed environment is handling image processing the same way (letterboxing, same background color etc.).

I see. I think in small dataset condition, it might slightly matter, but it definitely depends on the situation.
Thank you for replying.
