### ISSUE TITLE
In train.py,  the parameter group desc is error ?

### ISSUE THREAD

**Issue by otfot** [ultralytics/yolov5#6317]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

In train.py ,   define  g0, g1, g2  three different parameter group and add g1 with weight_decay, 
but the logger  print  `f"{len(g0)} weight, {len(g1)} weight (no decay), {len(g2)} bias"`

should it be `f"{len(g1)} weight, {len(g0)} weight (no decay), {len(g2)} bias"`

**Comment by glenn-jocher** [comment]
@Otfot hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

Yes I think you are correct, the reported values are backwards! Very nice catch! Can you please submit a PR with your recommended change? Thanks!

```python 
"{len(g1)} weight, {len(g0)} weight (no decay), {len(g2)} bias"
```


Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by otfot** [comment]
I have submit a PR at #6318

**Comment by glenn-jocher** [comment]
@Otfot PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐
