### ISSUE TITLE
To convert NMS to DIOU NMS

### ISSUE THREAD

**Issue by hyeonmin11** [ultralytics/yolov5#6319]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

for editing nms to DIOU NMS, I add box_diou function and compare box_diou with iou_thres in general.py 

in nonmaxsuppression function,

iou = box_diou(boxes[i], boxes) > iou_thres  # iou matrix   <<

if box_diou function is correct, is this enough to convert nms to DIOU nms??

I appreciate it for answering my former question.

**Comment by glenn-jocher** [comment]
@hyeonmin11 there is no `box_diou()` function in YOLOv5.
