### ISSUE TITLE
Freezing specific layers

### ISSUE THREAD

**Issue by joangog** [ultralytics/yolov5#6320]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

I attempted to freeze specific layers by providing the sequence of layers I wanted to freeze but got an error

Command:
python train.py --freeze 0 2

Error:
train.py: error: unrecognized arguments: 2

It seem the problem is that --freeze does not accept multiple arguments whereas, looking in the code, it should:
[    parser.add_argument('--freeze', nargs='+', type=int, default=[0], help='Freeze layers: backbone=10, first3=0 1 2')](https://github.com/ultralytics/yolov5/blob/db1f83be6312a3d68c817fd25251194e5e7e5b5d/train.py#L482)

### Environment

- YOLO: YOLOv5 🚀 v6.0-88-gd083b3e torch 1.9.0+cu102 CUDA:0 (Tesla K80, 11441MiB)
- OS: Google Colab and Ubuntu 18.04.5 LTS
- Python 3.8.8

### Minimal Reproducible Example

python train.py --freeze 0 2

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by joangog** [comment]
Nevermind, I just had an outdated version of YOLOv5. I'm closing this issue.

**Comment by glenn-jocher** [comment]
@joangog good, checked myself and everything is all good:

<img width="1507" alt="Screen Shot 2022-01-17 at 1 37 54 PM" src="https://user-images.githubusercontent.com/26833433/149847961-87c8ffa7-0e6e-4f96-8f89-638c86f25da9.png">
