### ISSUE TITLE
Model entrypoint executable "serve" was not found in container PATH

### ISSUE THREAD

**Issue by kaysagit** [ultralytics/yolov5#6323]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Integrations

### Bug

Hi, 
I am trying to deploy a trained YOLOv5 model on AWS Sagemaker for Inference. For the the deployment of the model I used the Dockerfile provided in this repo with the change of nvidia:pytorch image, which threw access denied exceptions with the latest pytorch image 
FROM pytorch/pytorch:latest
Below you can see the Dockerfile I used.

I changed the comment sign from # to // to avoid the markdown representation

// YOLOv5 🚀 by Ultralytics, GPL-3.0 license

// Start FROM Nvidia PyTorch image https://ngc.nvidia.com/catalog/containers/nvidia:pytorch
FROM pytorch/pytorch:latest

// Install linux packages
RUN apt update && apt install -y zip htop screen libgl1-mesa-glx

// Install python dependencies
COPY requirements.txt .
RUN python -m pip install --upgrade pip
RUN pip uninstall -y nvidia-tensorboard nvidia-tensorboard-plugin-dlprof
RUN pip install --no-cache -r requirements.txt coremltools onnx gsutil notebook wandb>=0.12.2
RUN pip install --no-cache -U torch torchvision numpy Pillow
// RUN pip install --no-cache torch==1.10.0+cu113 torchvision==0.11.1+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html

// Create working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

// Copy contents
COPY . /usr/src/app

// Downloads to user config dir
ADD https://ultralytics.com/assets/Arial.ttf /root/.config/Ultralytics/

// Set environment variables
// ENV HOME=/usr/src/app

// Usage Examples -------------------------------------------------------------------------------------------------------

// Build and Push
// t=ultralytics/yolov5:latest && sudo docker build -t $t . && sudo docker push $t

//Pull and Run
// t=ultralytics/yolov5:latest && sudo docker pull $t && sudo docker run -it --ipc=host --gpus all $t

// Pull and Run with local directory access
// t=ultralytics/yolov5:latest && sudo docker pull $t && sudo docker run -it --ipc=host --gpus all -v "$(pwd)"/datasets:/usr/src/datasets $t

//Kill all
//sudo docker kill $(sudo docker ps -q)

//Kill all image-based
//sudo docker kill $(sudo docker ps -qa --filter ancestor=ultralytics/yolov5:latest)

// Bash into running container
// sudo docker exec -it 5a9b5863d93d bash

//Bash into stopped container
//id=$(sudo docker ps -qa) && sudo docker start $id && sudo docker exec -it $id bash

//Clean up
//docker system prune -a --volumes

//Update Ubuntu drivers
// https://www.maketecheasier.com/install-nvidia-drivers-ubuntu/

//DDP test
//python -m torch.distributed.run --nproc_per_node 2 --master_port 1 train.py --epochs 3

//GCP VM from Image
//docker.io/ultralytics/yolov5:latest

When I want to deploy the model for inference I get the error 

Model entrypoint executable "serve" was not found in container PATH

Any suggestions how to solve this error?

### Environment

FROM pytorch/pytorch:latest

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@DL-stack I don't have sagemaker experience so I can't help here, but one point is that when posting comments in markdown you should mark code sections with ``` before and after:

\```
some code
\```

will look like:
```
some code
```

**Comment by ghost** [comment]
Have you solved the problem ?
