### ISSUE TITLE
 ModuleNotFoundError: No module named 'models.yolo'

### ISSUE THREAD

**Issue by Taitai6521** [ultralytics/yolov5#6326]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Namespace(agnostic_nms=False, augment=False, cfg='/content/drive/MyDrive/神様/Augmentedstartups/yolor/cfg/yolor_w6.cfg', classes=None, conf_thres=0.25, device='0', img_size=1280, iou_thres=0.5, names='data/coco.names', output='/content/drive/MyDrive/Dev/Soccer/Output', save_txt=False, source='/content/drive/MyDrive/神様/Augmentedstartups/yolor/inference/images/horses.jpg', update=False, view_img=False, weights=['/content/drive/MyDrive/神様/Augmentedstartups/yolor/yolor-w6.pt'])
Traceback (most recent call last):
  File "detect.py", line 186, in <module>
    detect()
  File "detect.py", line 44, in detect
    model.load_state_dict(torch.load(weights[0], map_location=device)['model'])
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 882, in _load
    result = unpickler.load()
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 875, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'models.yolo'

### Environment

YoloR
OS googlecolab

### Minimal Reproducible Example

https://github.com/Taitai6521/ModuleNotFoundError-No-module-named-models.yolo-
If you refer to the code here, you will be able to understand the contents.
Thank you very much for your cooperation.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Taitai6521 hi there! It looks like you've posted this issue in the wrong place. This is the YOLOv5 repo. 

You should post YOLOR issues directly to the YOLOR repository.

**Comment by Taitai6521** [comment]
hi, @glenn-jocher  Sorry!!

**Comment by Taitai6521** [comment]
P.S.
 https://github.com/WongKinYiu/yolor/issues/176
