### ISSUE TITLE
cornerwise bounding box

### ISSUE THREAD

**Issue by 123456789mojtaba** [ultralytics/yolov5#633]
Hi.
can we use yolov5 for datasets which their bounding boxes are not horizontal or vertical?
https://github.com/dingjiansw101/AerialDetection/blob/master/results.jpg

**Comment by glenn-jocher** [comment]
@123456789mojtaba yes, _if your datasets supplies rotation angles_ then you should be able to add a loss component for this, add an extra output neuron to each box etc. It's definitely doable, but would require a number of custom changes in practice.
