### ISSUE TITLE
youtube resolution

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#6330]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

![image](https://user-images.githubusercontent.com/59388989/149885009-95ab2fe6-e15f-48ec-97dd-5ecc7ff34d30.png)

There are 1440p youtube image.
How can I run detect.py with 1440p? I always get 1080p

**Comment by rohits45** [comment]
now yolo only allow you to run youtube video at 1080p

**Comment by glenn-jocher** [comment]
@alicera @rohits45 see pafy usage examples here:
https://github.com/mps-youtube/pafy

Any modifications would be applied here:
https://github.com/ultralytics/yolov5/blob/3119b2f27c198c6b9c02fb57d3b00b61a7bd2356/utils/datasets.py#L303-L306

**Comment by alicera** [comment]
I already try the getbest function.
But I always get 1080p, and I find pafy cant search the 1440p even I print all stream with pafy.

**Comment by glenn-jocher** [comment]
@alicera alright buddy then just raise an issue on the pafy repo, we can't really control anything outside of the pafy package here.
