### ISSUE TITLE
Final epoch training

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#6331]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I set the 150 epoch and the model end up with 150 epoch.
I think it can improve mAP if I let it continuous training.
How can I resume it with 150 and set the final epoch is 200.

**Comment by glenn-jocher** [comment]
@alicera 👋 Hello! Thanks for asking about **resuming training**. YOLOv5 🚀 Learning Rate (LR) [schedulers](https://github.com/ultralytics/yolov5/blob/9f3a388cea66ca71b9bbe057929eed8fbc920a7e/train.py#L109-L142) follow predefined LR curves for the fixed number of `--epochs` defined at training start (`default=300`), and are designed to fall to a minimum LR on the final epoch for best training results. For this reason you can not modify the number of epochs once training has started.

<img width="850" alt="LR Curves" src="https://user-images.githubusercontent.com/26833433/119332195-8e113a80-bc88-11eb-8eb7-7494ff1d5c01.png">

If your training was **interrupted** for any reason you may continue where you left off using the `--resume` argument. If your training fully completed, you can start a **new** training from any model using the `--weights` argument. Examples:

## Resume Single-GPU

You may not change settings when resuming, and **no additional arguments** other than `--resume` should be passed, with an optional path to the checkpoint you'd like to resume from. If no checkpoint is passed the most recently updated `last.pt` in your `yolov5/` directory is automatically found and used:
```bash
python train.py --resume  # automatically find latest checkpoint (searches yolov5/ directory)
python train.py --resume path/to/last.pt  # specify resume checkpoint
```

## Resume Multi-GPU

[Multi-GPU DDP trainings](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) must be resumed with the same GPUs and DDP command, i.e. assuming 8 GPUs:
```bash
python -m torch.distributed.run --nproc_per_node 8 train.py --resume  # resume latest checkpoint
python -m torch.distributed.run --nproc_per_node 8 train.py --resume path/to/last.pt  # specify resume checkpoint
```

## Start from Pretrained

If you would like to **start training** from a fully trained model, use the `--weights` argument, not the `--resume` argument:
```bash
python train.py --weights path/to/best.pt  # start from pretrained model
```

Good luck 🍀 and let us know if you have any other questions!

**Comment by alicera** [comment]
I run the command and the model end up with 150.
I want to train longer, i.e. 200 epochs. How can I train it start from 150  and let it end up with 200 ?
```
python -m torch.distributed.launch --nproc_per_node 4 train.py --batch 128 --data data/yolov5s.yaml --weights yolov5.pt --img-size 640 --device 0,1,2,3 --epochs 150
```

**Comment by glenn-jocher** [comment]
## Resume Multi-GPU

[Multi-GPU DDP trainings](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) must be resumed with the same GPUs and DDP command, i.e. assuming 8 GPUs:
```bash
python -m torch.distributed.run --nproc_per_node 8 train.py --resume  # resume latest checkpoint
python -m torch.distributed.run --nproc_per_node 8 train.py --resume path/to/last.pt  # specify resume checkpoint
```

**Comment by alicera** [comment]
```
python -m torch.distributed.run --nproc_per_node 4 train.py --resume path/to/last.pt  # specify resume checkpoint

# It show the message
AssertionError: runs/train/exp/weights/last.pt training to 150 epochs is finished, nothing to resume.
```

Even I use this command, it also meet the same problem.
```
python -m torch.distributed.run --nproc_per_node 4 train.py --resume path/to/last.pt  --epoch 200 # specify resume checkpoint
```

**Comment by glenn-jocher** [comment]
@alicera this model is fully trained and can be used to start a new training, i.e.:

```
python train.py --weights runs/train/exp/weights/last.pt
```

**Comment by alicera** [comment]
But it will start with 0. It seem unavoidable. 
And the learning rate will start with
lr0: 0.01
lrf: 0.2

Thanks for your help.

**Comment by glenn-jocher** [comment]
@alicera yes
