### ISSUE TITLE
dataset error

### ISSUE THREAD

**Issue by learncrazy** [ultralytics/yolov5#6333]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When I train the model, there is an error loading the dataset. Of the 256 images, only 31 were found, and the rest showed 'corrupted'. Excuse me, what is the reason for this?

### Additional

![Screenshot from 2022-01-18 16-41-58](https://user-images.githubusercontent.com/50286586/149901500-2c8080ce-a9f6-4c5a-b47b-af422d6fdfcc.png)

**Comment by DhruvAwasthi** [comment]
@learncrazy did you find the reason and solution for the same? I am facing the same issue.
