### ISSUE TITLE
Jupyter Notebook or JupyterLab is missing in requirements.txt

### ISSUE THREAD

**Issue by erolrecep** [ultralytics/yolov5#6339]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Thanks for open sourcing the project with all the available ready-to-use environments. Great job!

I was wondering if it missed putting Jupiter to the requirements.txt to test the project in the local or intentionally did not put to the requirements.txt.

**Comment by glenn-jocher** [comment]
@erolrecep it's not needed for any of the environments, but you're free to install any additional package you wish of course. 

For Binder issues see https://discourse.jupyter.org/t/binder-error-on-yolov5/6141/6

**Comment by erolrecep** [comment]
Thanks for the response.
