### ISSUE TITLE
Training & Inference  on greyscale images

### ISSUE THREAD

**Issue by vkramdev** [ultralytics/yolov5#634]
## ❔Question
I am training the yolov5 on my custom images which are greyscale. My images are 640*480 .I am using below as my training command:

python train.py --batch 8 --epochs=50 --data mycustomdata.yaml --cfg models/yolov5s.yaml   --name mytestmodel

However when i try to generate inference on test data i coudn't see the bounding boxes in any of the image. For debugging purpose i even tried to use the training images for inference , however i wasn't able to get the inference i.e no bounding box for the images.

Can someone help with below queries:

1. Does yolov5 works with training and inference  in greyscale images.
2. If yes, Does training on yolov5 for greyscale needs any other parameter?

## Additional context
Please point out If i am missing something.

**Comment by glenn-jocher** [comment]
@vkramdev training operates correctly on greyscale images, no changes are needed. COCO has many greyscale images.

Recommend you follow the custom training tutorial. See https://docs.ultralytics.com/yolov5

**Comment by vkramdev** [comment]
Thanks @glenn-jocher .

**Comment by jnulzl** [comment]
ref [#6288 ](https://github.com/ultralytics/yolov5/issues/6288#issuecomment-1096291591)
