### ISSUE TITLE
center padding color

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#6346]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

https://github.com/ultralytics/yolov5/blob/0cf932bf6346909189c53b375ef97551bb0c2326/utils/augmentations.py#L91

How do you research the color=(114, 114, 114)?
Why not color=(0, 0, 0)?

**Comment by glenn-jocher** [comment]
@alicera 114 is the mean ImageNet intensity (UINT8 0-255).

**Comment by alicera** [comment]
So you get the all RGB images from ImageNet. Then split RGB channel, add the pixel up, and divided by ImageNet number. It is just 114 for RBG[114, 114, 114].

Instead of using the mean=[0.485, 0.456, 0.406] and std=[0.229, 0.224, 0.225] of ImageNet to get the 114 for RBG.
https://stackoverflow.com/questions/58151507/why-pytorch-officially-use-mean-0-485-0-456-0-406-and-std-0-229-0-224-0-2

**Comment by glenn-jocher** [comment]
@alicera sure. Order of operations doesn't matter when taking averages over dimensions, so 
```python
print(np.array([0.485, 0.456, 0.406]).mean() * 255)
114.495
```

**Comment by alicera** [comment]
Let me make sure I have it right.
Get the image pixel. Let pixel - 114 is close to 0. Then the 0 will input the CNN to extract features.

**Comment by glenn-jocher** [comment]
114 just a background intensity. You can see it in all of the train batches for example.

**Comment by alicera** [comment]
Thank you for the information.

I search a background intensity.
![image](https://user-images.githubusercontent.com/59388989/150457667-8b903e95-6515-4ab6-becd-40082fcdd634.png)

Do you have experimented the background intensity that color=(114, 114, 114) is better than color=(0, 0, 0) (or other value) ?

**Comment by glenn-jocher** [comment]
@alicera yes I've done experiments and the exact background color has little effect.
