### ISSUE TITLE
how to show frames with boundingbox in hub inference

### ISSUE THREAD

**Issue by ZQQRYE** [ultralytics/yolov5#6348]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hi!thanks for your great work firstly. i am trying to show the frames with detections in an opencv gui. could you please help me with this? Shortly, i mean how can i use 'cv2.imshow' or other way that can show multiple frames to show results?

**Comment by glenn-jocher** [comment]
@SHURYE see detect.py for cv2.imshow usage
https://github.com/ultralytics/yolov5/blob/e5219099cd6e76e4f75a4c8b376531af2791d358/detect.py#L181-L186

**Comment by Guttappa1238** [comment]
@SHURYE  Try this!!

```
import numpy as np
import cv2
from mss import mss
from PIL import Image
import torch


# Read the video from specified path
cam = cv2.VideoCapture(0)

# Model
model = torch.hub.load('ultralytics/yolov5', 'custom', path='last.pt')  # local custom model

while True:
    ret,frame = cam.read()

    #set the model use the screen 
    result = model(frame)
    result.display(render=True) 
    
    #show the result
    cv2.imshow('Detection Screen', result.imgs[0])

    if cv2.waitKey(25) & 0xFF == ord('q'):
        cv2.destroyAllWindows()
        break
```

**Comment by ZQQRYE** [comment]
@glenn-jocher thanks for your reply! i will look into it.

**Comment by ZQQRYE** [comment]
@Guttappa1238 thanks!that works perfectly! thanks very much.Another question, do you know how to get the boundingbox coordination of the detections in hub reference? thanks again!!

**Comment by Guttappa1238** [comment]
@SHURYE  I guess you havn't looked at #36, 
you can get bounding box coordination using this :
`results.pandas().xyxy[0]`
