### ISSUE TITLE
Training speed suddenly slows down after the first epoch.

### ISSUE THREAD

**Issue by go2sea** [ultralytics/yolov5#6349]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

Training speed suddenly slows down after the first epoch.

I used the DDP command to train yolov5x on objects365：
![image](https://user-images.githubusercontent.com/10369479/150129085-bce1f508-d84c-4d27-a750-bc70ce966ea3.png)

The training speed is fast in the first epoch, it cost about 2 hours to finish.

But the second epoch is extremely slow, and the speed in logging is not true. The log shows the training speed is about 7.35 iterations per second, but in fact, it has stuck at 89 iterations for a while(perhaps dozens of seconds）

![image](https://user-images.githubusercontent.com/10369479/150128945-afb544fb-56d4-49cf-ba27-69925a5a8f7c.png)

Every once in a while, the GPU utilization gets stuck like this：
![image](https://user-images.githubusercontent.com/10369479/150130255-8790b8a3-d816-45c5-bac9-7aaa16da2ad2.png)

Actually， it takes 2.5 hours to finish only 30% of the second epoch:
![image](https://user-images.githubusercontent.com/10369479/150130934-eb47bc55-b8a1-4728-81ff-95e9c33e54a1.png)

And the GPU usage is again stuck here:
![image](https://user-images.githubusercontent.com/10369479/150131565-878c1de2-8655-42d7-8468-cdd65c715a4a.png)

The code I used is the latest until 2022/01/19, commit id is: 0cf932bf6346909189c53b375ef97551bb0c2326

### Environment

![image](https://user-images.githubusercontent.com/10369479/150133733-311fee33-06df-40db-a137-f4c590cbe83b.png)

### Minimal Reproducible Example

python3 -m torch.distributed.launch --nproc_per_node=8 \
                                    --master_port=6688 \
                                    --node_rank=0 \
                                    --nnodes=1 \
                                    train.py \
                                    --img 640 \
                                    --batch 128 \
                                    --epochs 300 \
                                    --data ./data/Objects365.yaml \
                                    --weights 'yolov5x.pt' \
                                    --hyp data/hyps/hyp.scratch.yaml \
                                    --name objects365

### Additional

Patience is required to reproduce this bug. The first epoch is fast, but after the first validation, training slows down at the beginning of the second epoch. 

Use Objects365 datasets to reproduce this bug, smaller datasets may not work.

Do not trust the speed shown at the log, feel the speed & watch the GPU usage by yourself !!!
Do not trust the speed shown at the log, feel the speed & watch the GPU usage by yourself !!!
Do not trust the speed shown at the log, feel the speed & watch the GPU usage by yourself !!!

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@go2sea may just be bottlenecks in other areas, i.e. HDD read speeds and/or IOPS in AWS or GCP, or other resource utilization during training.

We also recommend always using or Docker image when training DDP unless you are an expert in environments.

**Comment by glenn-jocher** [comment]
@go2sea BTW we have a trained Objects365 model here. Trained over 2-3 days on a P4d, no issues during training:
https://github.com/ultralytics/yolov5/releases/download/v6.0/yolov5m_Objects365.pt

**Comment by go2sea** [comment]
> @go2sea may just be bottlenecks in other areas, i.e. HDD read speeds and/or IOPS in AWS or GCP, or other resource utilization during training.
> 
> We also recommend always using or Docker image when training DDP unless you are an expert in environments.

But this doesn't explain that the first epoch is normal and always slows down from the second epoch.

**Comment by marcortiz11** [comment]
Is it possible that you are leaving the process running in background using nohup? I think nohup should be used for low memory intensive tasks. I realised after training the Yolov5 in foreground for several epochs, and seeing it was faster.

**Comment by wangtao0219** [comment]
@go2sea  I also encountered this problem when training the coco dataset
My GPU is 16G，batch-size 128，yolov5n（v6.1）
The training speed is fast in the first epoch, it cost about 11 minutes to finish.   
Unfortunately，it takes 1 hours to finish the second epoch，and every epochs after that,       almost inoperable.

But there is something strange, batch-size 128，yolov5n（v6.0）,It only works if you change the version. every epochs just 11 minutes.

**Comment by glenn-jocher** [comment]
@wangtao0219 our YOLOv5n v6.1 training time is 1 day 22 hours for 300 epochs, average epoch time of 7-8 minutes
https://wandb.ai/glenn-jocher/YOLOv5_v61_official

**Comment by aldudrino** [comment]
Hi, we are facing similar issue, were you able to solve the above?

**Comment by glenn-jocher** [comment]
@aldudrino hello! Could you please provide more details about the issue you are facing? It would be helpful to know which dataset you are using, your machine specs, YOLOv5 version, and any error messages you are receiving. Additionally, you may find our official tutorials and documentation helpful in troubleshooting your issue. Please let us know how we can assist you further.

**Comment by marcortiz11** [comment]
I encountered a similar issue before and it was due to a high number of workers during training. Keep it to 4-8.

**Comment by glenn-jocher** [comment]
@marcortiz11 hi there! Thank you for sharing your experience. Yes, having too many workers during training can cause slowdowns. Keeping it to 4-8 workers is a good practice. It would also be helpful to check on other factors such as your machine specs, dataset size, and YOLOv5 version to pinpoint the cause of the issue. Let us know if there is anything else we can help you with.
