### ISSUE TITLE
Specification of labels location when training on custom dataset

### ISSUE THREAD

**Issue by gvieralopez** [ultralytics/yolov5#6351]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I followed the tutorial on [training with custom data](https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data). It is quite good and I really liked it. After a first successful run, I wanted to tweak a bit the yaml file to avoid changing the original structure of the dataset. 

I tried to specify the values as in the case 2) stated in the tutorial:
`# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]`

However, when I create the .txt with relative paths (relatives to the dataset location already stated in the yaml) to each image file, I get this kind of errors:
```
train: Scanning '/content/drive/MyDrive/CYGNOML/CYGNO-ML-DATASET-LITE/images_train' images and labels...0 found, 0 missing, 0 empty, 7 corrupt: 100% 7/7 [00:00<00:00, 3832.91it/s]
train: WARNING: images/0001.png: ignoring corrupt image/label: [Errno 2] No such file or directory: 'images/0001.png'
```

And when I create the .txt with absolute paths it works perfectly. 

1. Is it the intended behavior?
2. If I specify an absolute path to the images, the labels need to be in the same absolute path but only changing the word 'images' for 'labels' in the path?

**Comment by glenn-jocher** [comment]
@gvieralopez see COCO dataset for an example usage of *.txt file for relative image lists. Relative and absolute both work.
<img width="1074" alt="Screen Shot 2022-01-19 at 1 11 32 PM" src="https://user-images.githubusercontent.com/26833433/150233232-783bc854-d0dd-4b70-8c3a-8c65303b2239.png">

**Comment by gvieralopez** [comment]
Thanks a lot for your reply. I updated the txt as suggested and now are working with relative paths.
