### ISSUE TITLE
Questions about data scanning

### ISSUE THREAD

**Issue by starspder** [ultralytics/yolov5#6358]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I have a question while using this model.
![vv](https://user-images.githubusercontent.com/20820142/150284592-2ae2b70c-238d-44fc-8112-797c4eb6aa5d.jpg)

I know that "empty" means that the .txt file exists but is empty.
Actually, I want to train with these data in the background.

By learning the background, it is possible to train the robustness against various backgrounds, and it is possible to reduce the FP phenomenon that is detected in the foreground even though it is a background.

So, I wonder if background images with "empty"  are also included as training data.

Thank you for reading my question!!

**Comment by glenn-jocher** [comment]
@starspder yes it's good to include background images to reduce FPs. **All** images in your dataset are used for training. If they have no txt file, or an empty txt file, then they are used as background images. COCO has about 1000 of these in train and 50 in val.
