### ISSUE TITLE
Issue while running detect.py

### ISSUE THREAD

**Issue by DexterFernandes** [ultralytics/yolov5#636]
I have trained the YoloV5s model on a dataset of about 450 images on a single class only. The model was trained on Colab which took place without a hiccup. Now, I am trying to run detect.py on my laptop with a CUDA-enabled version of PyTorch. I am using the following command to run the detect.py file: 
`python detect.py --source 0 --weights trained_models/soc_dist_1.pt`

After which I get the following error:
RuntimeError: shape '[1, 3, 6, 80, 80]' is invalid for input of size 819200

I am not sure why I am getting this error. I have followed all the steps listed in the Train-Custom-Data tutorial.

Any help would be very appreciated.

I have previously successfully run the detect.py script for another project that was also trained on custom data. I faced no issues there although I had trained a YoloV5m model on 5 different classes.

**Comment by glenn-jocher** [comment]
@DexterFernandes you can use a model anywhere else that meets the requirements. See https://github.com/ultralytics/yolov5#requirements

**Comment by crqqq** [comment]
> I have trained the YoloV5s model on a dataset of about 450 images on a single class only. The model was trained on Colab which took place without a hiccup. Now, I am trying to run detect.py on my laptop with a CUDA-enabled version of PyTorch. I am using the following command to run the detect.py file:
> `python detect.py --source 0 --weights trained_models/soc_dist_1.pt`
> 
> After which I get the following error:
> RuntimeError: shape '[1, 3, 6, 80, 80]' is invalid for input of size 819200
> 
> I am not sure why I am getting this error. I have followed all the steps listed in the Train-Custom-Data tutorial.
> 
> Any help would be very appreciated.
> 
> I have previously successfully run the detect.py script for another project that was also trained on custom data. I faced no issues there although I had trained a YoloV5m model on 5 different classes.

I have encountered the same question, so I would like to ask if this question has been solved??

**Comment by lingtengqiu** [comment]
> I have trained the YoloV5s model on a dataset of about 450 images on a single class only. The model was trained on Colab which took place without a hiccup. Now, I am trying to run detect.py on my laptop with a CUDA-enabled version of PyTorch. I am using the following command to run the detect.py file:
> `python detect.py --source 0 --weights trained_models/soc_dist_1.pt`
> 
> After which I get the following error:
> RuntimeError: shape '[1, 3, 6, 80, 80]' is invalid for input of size 819200
> 
> I am not sure why I am getting this error. I have followed all the steps listed in the Train-Custom-Data tutorial.
> 
> Any help would be very appreciated.
> 
> I have previously successfully run the detect.py script for another project that was also trained on custom data. I faced no issues there although I had trained a YoloV5m model on 5 different classes.


```
I solve this problem, by adding some code in yolo.py
in Detect class,  there are some bugs, you need transfer the input feature map into 255 channels
    def forward(self, x):
        # x = x.copy()  # for profiling
        z = []  # inference output
        self.training |= self.export
        for i in range(self.nl):
            #[1, 128, 80, 80]
            bs, _, ny, nx = x[i].shape  # x(bs,255,20,20) to x(bs,3,20,20,85)
            x[i] =self.m[i](x[i])
            x[i] = x[i].view(bs, self.na, self.no, ny, nx).permute(0, 1, 3, 4, 2).contiguous()
```
