### ISSUE TITLE
Inference is slow on PC (without GPU) and faster on iOS device, why?

### ISSUE THREAD

**Issue by ssooffiiaannee** [ultralytics/yolov5#6363]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have a question that puzzled me for the last few weeks, I trained a yolov5s and it works like a charm, when running yolov5s inference on CPU only, I get about 3 FPS. I wonder how can an iOS device (or android) be faster than a PC?

**Comment by glenn-jocher** [comment]
@ssooffiiaannee YOLOv5 CoreML models run on the Apple Neural Engine (ANE) on iOS devices which provide up to 15 TOPS of performance.

**Comment by glenn-jocher** [comment]
@ssooffiiaannee for further details on YOLOv5 iOS profiling see https://github.com/ultralytics/yolov5/issues/1276
