### ISSUE TITLE
我在训练的时候AP值非常低，是什么原因造成的呢？

### ISSUE THREAD

**Issue by 1640477469** [ultralytics/yolov5#6366]
![image](https://user-images.githubusercontent.com/98088542/150357244-5a0111f3-f946-44ae-aa5b-c1a0d061557b.png)
训练了100多次，map始终在0.003左右，为什么会这样呢？

**Comment by Zengyf-CVer** [comment]
@1640477469 
因为你训练的图片出现了JPEG格式问题，如图：
![ksnip_20220121-090509](https://user-images.githubusercontent.com/41098760/150446969-eb5a0906-d7e7-4387-88ea-c3c13af57850.png)
我建议你将这些异常的图像删除掉，然后在重新训练。
