### ISSUE TITLE
 TensorFlow saved_model: export failure: name 'SPPF' is not defined when exporting yolov5n version

### ISSUE THREAD

**Issue by rtm-1dyakonov** [ultralytics/yolov5#6367]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Export

### Bug

When I use export.py script from the latest release 6.0 all versions (i.e. yolov5s, yolov5m e.t.c.) export to saved_model and tfjs formats well, except for yolov5n. I get the same SPPF error all the time

![изображение](https://user-images.githubusercontent.com/65365762/150360610-3a340903-f697-4781-99dc-8417d9a4e6d5.png)

### Environment

I use [Google Colab](https://colab.research.google.com/drive/1ZoELbXJxvzao-DSvwDSJ1ckNz5nYztTF?usp=sharing) 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@rtm-1dyakonov should be fixed in master, just updated your code.

**Comment by rtm-1dyakonov** [comment]
@glenn-jocher yeah, I used the script from master and now it's working well. Thanx!

**Comment by 123jx** [comment]
所以怎么解决的呢

**Comment by glenn-jocher** [comment]
@123jx this issue has been fixed in the latest master branch of YOLOv5. You can update your code to the latest version to resolve the problem. Thank you for reporting the issue!
