### ISSUE TITLE
TensorRT works on a 2080Ti but fails on Jetson Nano

### ISSUE THREAD

**Issue by dariogonle** [ultralytics/yolov5#6371]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm using the detect script to run a TensorRT model.
```
python3 detect.py --weights yolov5n.engine --iou-thres 0.5 --conf 0.5 --source images/ --img-size 704 --half
```

This script works on a 2080Ti, but fails on a Jetson Nano.
![image](https://user-images.githubusercontent.com/80393891/150376196-aa0ad45a-d502-48c0-9ce3-7a9de3897263.png)

This is the setup used on the 2080Ti
![image](https://user-images.githubusercontent.com/80393891/150376921-daa98606-c370-4d00-a906-f9707d7ba114.png)

An this the setup on the Jetson Nano
![image](https://user-images.githubusercontent.com/80393891/150376733-ea6c84b9-4d69-4fa1-a64a-3feb2fae212f.png)

It is true that  I'm not using the same CUDA and tensorrt version, but the one used on the Jetson Nano is the dafault included by Nvidia it it's nvcr.io/nvidia/l4t-ml:r32.6.1-py3 image.

Has anybody got the same problem?

**Comment by glenn-jocher** [comment]
@dariogonle TRT models will only work on the exact hardware you exported them on.

**Comment by dariogonle** [comment]
Thank you @glenn-jocher. Have you tried to export a tensorrt model on a Jetson Nano? I'm getting the following error:
```
ERROR: Tactic Device request: 539MB Available: 429MB. Device memory is insufficient to use tactic.
```

EDIT: if you wait a long time, it finally exports the tensorrt model. It seems that the process is a little bit time-consuming on the Jetson Nano

**Comment by glenn-jocher** [comment]
@dariogonle no I haven't yet. It looks like you're out of memory though.
