### ISSUE TITLE
Wandb error when starting to train --- did not used to do that before!

### ISSUE THREAD

**Issue by alijundi** [ultralytics/yolov5#6372]
I get the below every time I start to train

`
     Epoch   gpu_mem       box       obj       cls    labels  img_size
4880/99999       14G    0.1034    0.1344  0.002613       887       640: 100% 3/3 [00:03<00:00,  1.15s/it]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100% 2/2 [00:05<00:00,  2.91s/it]
                 all        167       3911      0.952      0.592      0.706      0.557

Traceback (most recent call last):
  File "train.py", line 636, in <module>
    main(opt)
  File "train.py", line 533, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 383, in train
    callbacks.run('on_fit_epoch_end', log_vals, epoch, best_fitness, fi)
  File "/content/yolov5/utils/callbacks.py", line 77, in run
    logger['callback'](*args, **kwargs)
  File "/content/yolov5/utils/loggers/__init__.py", line 134, in on_fit_epoch_end
    self.wandb.end_epoch(best_result=best_fitness == fi)
  File "/content/yolov5/utils/loggers/wandb/wandb_utils.py", line 527, in end_epoch
    self.result_artifact.add(self.result_table, 'result')
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_artifacts.py", line 500, in add
    val = obj.to_json(self)
  File "/usr/local/lib/python3.7/dist-packages/wandb/data_types.py", line 610, in to_json
    mapped_row.append(_json_helper(v, artifact))
  File "/usr/local/lib/python3.7/dist-packages/wandb/data_types.py", line 105, in _json_helper
    return val.to_json(artifact)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/data_types.py", line 2276, in to_json
    json_dict = super(Image, self).to_json(run_or_artifact)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/data_types.py", line 625, in to_json
    artifact.add_reference(path.ref_url(), name=name)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_artifacts.py", line 450, in add_reference
    self, uri_str, name=name, checksum=checksum, max_objects=max_objects
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_artifacts.py", line 906, in store_reference
    artifact, path, name=name, checksum=checksum, max_objects=max_objects
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_artifacts.py", line 1096, in store_path
    artifact, path, name=name, checksum=checksum, max_objects=max_objects
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_artifacts.py", line 1846, in store_path
    path = entry.ref
AttributeError: 'NoneType' object has no attribute 'ref'
`

Any idea why this is happening now?

**Comment by AyushExel** [comment]
@alijundi hey thanks for reporting. I'm taking a look. Can you please confirm what version of wandb you're using? Also are you using the latest version of yolov5 repo?

**Comment by AyushExel** [comment]
@alijundi I tried to repo this with this command - ` python train.py --project wandb_bug_repro --epochs 2 --upload_dataset` and everything worked fine.

**Comment by alijundi** [comment]
@AyushExel  thank you for your prompt response. I use the latest wandb and yolov5 in colab environment (latest download every time) I still get the same problem even though two days ago it did not used to do that!

'''
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 12           [-1, 6]  1         0  models.common.Concat                    [1]                           
 13                -1  1    361984  models.common.C3                        [512, 256, 1, False]          
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]              
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 16           [-1, 4]  1         0  models.common.Concat                    [1]                           
 17                -1  1     90880  models.common.C3                        [256, 128, 1, False]          
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]              
 19          [-1, 14]  1         0  models.common.Concat                    [1]                           
 20                -1  1    296448  models.common.C3                        [256, 256, 1, False]          
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]              
 22          [-1, 10]  1         0  models.common.Concat                    [1]                           
 23                -1  1   1182720  models.common.C3                        [512, 512, 1, False]          
 24      [17, 20, 23]  1     21576  models.yolo.Detect                      [3, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
Model Summary: 270 layers, 7027720 parameters, 7027720 gradients, 15.9 GFLOPs

Transferred 348/349 items from /content/yolov5/last-fb.pt
AutoBatch: Computing optimal batch size for --imgsz 2560
AutoBatch: CUDA:0 (Tesla P100-PCIE-16GB) 15.90G total, 0.14G reserved, 0.12G allocated, 15.64G free
tcmalloc: large alloc 1258291200 bytes == 0x557dd8e5a000 @  0x7fe9955e2b6b 0x7fe995602379 0x7fe98ec21cde 0x7fe98ec23452 0x7fe8a6fdcab9 0x7fe8a6fdd817 0x7fe8a741fdc9 0x7fe8a7b0344a 0x7fe8a7ae18fe 0x7fe8a77e9d60 0x7fe95080f721 0x7fe8a7423fd0 0x7fe8a7c830d4 0x7fe8a7af5214 0x7fe8a7ae53a7 0x7fe8a770a32e 0x7fe95035f8ec 0x557cf373b4b0 0x557cf373b240 0x557cf37af0f3 0x557cf37a9ced 0x557cf373cbda 0x557cf37aa915 0x557cf37a9ced 0x557cf373cbda 0x557cf37aa915 0x557cf37a99ee 0x557cf373cbda 0x557cf37aa915 0x557cf37a9ced 0x557cf373cbda
      Params      GFLOPs  GPU_mem (GB)  forward (ms) backward (ms)                   input                  output
     7027720       253.9         3.127         120.3         203.3      (1, 3, 2560, 2560)                    list
     7027720       507.7         6.050         177.2         354.1      (2, 3, 2560, 2560)                    list
     7027720        1015        11.780           284         637.3      (4, 3, 2560, 2560)                    list
CUDA out of memory. Tried to allocate 50.00 MiB (GPU 0; 15.90 GiB total capacity; 14.70 GiB already allocated; 27.75 MiB free; 14.76 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
CUDA out of memory. Tried to allocate 800.00 MiB (GPU 0; 15.90 GiB total capacity; 14.19 GiB already allocated; 519.75 MiB free; 14.28 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
AutoBatch: Using batch-size 4 for CUDA:0 14.31G/15.90G (90%)
Scaled weight_decay = 0.0005
optimizer: SGD with parameter groups 57 weight (no decay), 60 weight, 60 bias
albumentations: version 1.0.3 required by YOLOv5, but version 0.1.12 is currently installed
train: Scanning 'artifacts/train:v0/data/labels' images and labels...90 found, 0 missing, 6 empty, 0 corrupt: 100% 90/90 [00:00<00:00, 1699.08it/s]
train: New cache created: artifacts/train:v0/data/labels.cache
val: Scanning 'artifacts/val:v0/data/labels' images and labels...90 found, 0 missing, 6 empty, 0 corrupt: 100% 90/90 [00:00<00:00, 955.18it/s]
val: New cache created: artifacts/val:v0/data/labels.cache
Plotting labels to CLASSIFIER_FB/exp/labels.jpg... 

AutoAnchor: 2.11 anchors/target, 0.971 Best Possible Recall (BPR). Anchors are a poor fit to dataset ⚠️, attempting to improve...
AutoAnchor: Running kmeans for 9 anchors on 441 points...
AutoAnchor: Evolving anchors with Genetic Algorithm: fitness = 0.8168: 100% 1000/1000 [00:08<00:00, 123.70it/s]
AutoAnchor: thr=0.25: 1.0000 best possible recall, 7.24 anchors past thr
AutoAnchor: n=9, img_size=2560, metric_all=0.445/0.817-mean/best, past_thr=0.510-mean: 264,107, 529,194, 338,403, 527,310, 1165,228, 881,329, 747,548, 1106,719, 973,1161
AutoAnchor: New anchors saved to model. Update model *.yaml to use these anchors in the future.
Image sizes 2560 train, 2560 val
Using 4 dataloader workers
Logging results to CLASSIFIER_FB/exp
Starting training for 10000 epochs...

     Epoch   gpu_mem       box       obj       cls    labels  img_size
  310/9999     12.4G   0.04902   0.09933  0.004281         6      2560: 100% 23/23 [00:31<00:00,  1.38s/it]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100% 12/12 [00:31<00:00,  2.60s/it]
                 all         90        441      0.591      0.748      0.628      0.315
**Traceback (most recent call last):
  File "train.py", line 636, in <module>
    main(opt)
  File "train.py", line 533, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 383, in train
    callbacks.run('on_fit_epoch_end', log_vals, epoch, best_fitness, fi)
  File "/content/yolov5/utils/callbacks.py", line 77, in run
    logger['callback'](*args, **kwargs)
  File "/content/yolov5/utils/loggers/__init__.py", line 134, in on_fit_epoch_end
    self.wandb.end_epoch(best_result=best_fitness == fi)
  File "/content/yolov5/utils/loggers/wandb/wandb_utils.py", line 527, in end_epoch
    self.result_artifact.add(self.result_table, 'result')
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_artifacts.py", line 500, in add
    val = obj.to_json(self)
  File "/usr/local/lib/python3.7/dist-packages/wandb/data_types.py", line 610, in to_json
    mapped_row.append(_json_helper(v, artifact))
  File "/usr/local/lib/python3.7/dist-packages/wandb/data_types.py", line 105, in _json_helper
    return val.to_json(artifact)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/data_types.py", line 2276, in to_json
    json_dict = super(Image, self).to_json(run_or_artifact)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/data_types.py", line 625, in to_json
    artifact.add_reference(path.ref_url(), name=name)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_artifacts.py", line 450, in add_reference
    self, uri_str, name=name, checksum=checksum, max_objects=max_objects
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_artifacts.py", line 906, in store_reference
    artifact, path, name=name, checksum=checksum, max_objects=max_objects
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_artifacts.py", line 1096, in store_path
    artifact, path, name=name, checksum=checksum, max_objects=max_objects
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_artifacts.py", line 1846, in store_path
    path = entry.ref
AttributeError: 'NoneType' object has no attribute 'ref'**

wandb: Waiting for W&B process to finish, PID 476... (failed 1). Press ctrl-c to abort syncing.
wandb:                                                                                
wandb: Run history:
wandb:        metrics/mAP_0.5 ▁
wandb:   metrics/mAP_0.5:0.95 ▁
wandb:      metrics/precision ▁
wandb:         metrics/recall ▁
wandb:         train/box_loss ▁
wandb:         train/cls_loss ▁
wandb:         train/obj_loss ▁
wandb:           val/box_loss ▁
wandb:           val/cls_loss ▁
wandb:           val/obj_loss ▁
wandb:                  x/lr0 ▁
wandb:                  x/lr1 ▁
wandb:                  x/lr2 ▁
wandb: 
wandb: Run summary:
wandb:        metrics/mAP_0.5 0.62753
wandb:   metrics/mAP_0.5:0.95 0.31516
wandb:      metrics/precision 0.59133
wandb:         metrics/recall 0.74816
wandb:         train/box_loss 0.04902
wandb:         train/cls_loss 0.00428
wandb:         train/obj_loss 0.09933
wandb:           val/box_loss 0.04499
wandb:           val/cls_loss 0.00179
wandb:           val/obj_loss 0.08785
wandb:                  x/lr0 0.00998
wandb:                  x/lr1 0.00998
wandb:                  x/lr2 0.00998
wandb: 
wandb: Synced 5 W&B file(s), 34 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Synced fallen-bee-2: https://wandb.ai/alijundi1/CLASSIFIER_FB/runs/15g1ktwi
wandb: Find logs at: ./wandb/run-20220121_063717-15g1ktwi/logs/debug.log
wandb: 


'''

**Comment by alijundi** [comment]
@AyushExel I also noticed that the wandb version on pip is 0.12.9 and on github is 0.12.10 I am now attempting to get the latest version from github and run setup instead on installing through pip. let you know the news in a couple of minutes

**Comment by alijundi** [comment]
@AyushExel same issue with the latest wandb from github. No luck

**Comment by morganmcg1** [comment]
@alijundi looks like your hitting CUDA OOM error no? I can see this in your latest stacktrace

> CUDA out of memory. Tried to allocate 50.00 MiB (GPU 0; 15.90 GiB total capacity; 14.70 GiB already allocated; 27.75 MiB free; 14.76 GiB reserved in total by PyTorch)

**Comment by morganmcg1** [comment]
Confirming that this code also runs fine for me:

```
!git clone https://github.com/ultralytics/yolov5  # clone
!cd yolov5 && pip install -r requirements.txt  # install
!cd yolov5 && python train.py --project wandb_bug_repro --epochs 2 --upload_dataset
```

**Comment by alijundi** [comment]
@morganmcg1 can you tell what version of wandb you used to upload the dataset? I am thinking the problem is with the upload not with the training itself. I installed wandb using pip.

The version is 0.12.9 latest in pip

**Comment by AyushExel** [comment]
@alijundi As Morgan mentioned, in the latest stack trace, you're running out of memory on GPU. Can you provide more info about what dataset and batch size you're using? Maybe try reducing the batch size.
Also, the exact command you're using would be helpful for debugging

**Comment by alijundi** [comment]
@AyushExel 

The command is

```
 %cd /content/yolov5
!python train.py \
  --data bus_dataset.yaml \
  --epochs 10000 \
  --project CLASSIFIER_FB \
  --bbox_interval 1 \
  --weights '/content/yolov5/last-fb.pt' \
  --img-size 2560 \
  --patience=1000 \
  --batch-size -1 \
  --save-period 5 \
  --cfg yolov5s.yaml
```

Batch size = -1 (Automatic Batch Automatically decided)

**Comment by alijundi** [comment]
My yaml file content is:

```
names:
- MDBSMDB
- MCC
- DB
nc: 3
train: wandb-artifact://classifier_fb/train
val: wandb-artifact://classifier_fb/val
```
I am not sure what is happening. It was training just fine for a couple of weeks. Only today I am facing this issue!

**Comment by AyushExel** [comment]
@alijundi try setting --batch-size to 16 and try again

**Comment by alijundi** [comment]
@AyushExel batch size 16 is too much for cuda at image size 2560. I am putting it now to 3 as the automatic batch size selected 4. I still do not think it is a batch size issue!

**Comment by AyushExel** [comment]
@alijundi Still seeing CUDA Out Of Memory Error or something else?

**Comment by alijundi** [comment]
@AyushExel batch size 3 is outputs same error!

batch size 16 outputs:

RuntimeError: CUDA out of memory. Tried to allocate 800.00 MiB (GPU 0; 15.90 GiB total capacity; 14.34 GiB already allocat

**Comment by alijundi** [comment]
The error is output after the epoch finishes training and exactly right after validation! I am thinking there is something wrong while uploading the result to wandb. Why do you think?

**Comment by AyushExel** [comment]
@alijundi Can you share your run link? I think this has to do with the version mismatch between client when uploading data vs using it. There was some artifacts-related bug that might be causing it. You might need to match the client version used to upload the data.

For debugging, try this.
Re-upload the data with the latest version of the client:
`python utils/loggers/wandb/log_dataset.py ...`
And then train using the same command you're using.

**Comment by alijundi** [comment]
@AyushExel I did re-install of wandb via pip and reploaded the dataset again (wandb version on both local and colab was 0.12.9

again I tried using the git version of wandb 0.12.10-dev of both local and colab and re-uploaded the dataset again. I even created a new account to eliminate probable issues.

Finally, it is not working for me any way!

Not sure why and what was updated...

**Comment by AyushExel** [comment]
Okay thanks for the detailed info. I'm trying to repro

**Comment by alijundi** [comment]
@AyushExel Thank you for your time and efforts. I am sorry for the trouble this is causing to you.

**Comment by AyushExel** [comment]
@alijundi happy to help :) 
So, I'm using my coco128_wandb.yaml file:
```
train: wandb-artifact://wandb_bug_repro/train
val: wandb-artifact://wandb_bug_repro/val
```
It worked fine in the colab with the latest version of wandb and yolov5

**Comment by alijundi** [comment]
@AyushExel this is really bizzar! Can you please try my artifacts, yaml file and command above with my API key from wandb and let me know if it works with you?

**Comment by alijundi** [comment]
to make it easier I can share my colab session (view only) as below:

https://colab.research.google.com/drive/1tIeQvi5flpMCU0LbZEi6Hp7b6TNQ7gtg?usp=sharing

**Comment by AyushExel** [comment]
@alijundi Hey I'm trying to repo.. Please delete the api key from above now

**Comment by alijundi** [comment]
@AyushExel I am sure you see my issue now. What do you think?

**Comment by AyushExel** [comment]
Okay, I was able to repro this. I think the problem is with the artifact upload. can you share the colab from which you uploaded the dataset?

**Comment by alijundi** [comment]
I uploaded it from my local computer! how can I assist?

**Comment by AyushExel** [comment]
reupload it with the latest version of wandb.
`pip install --upgrade wandb`
and then upload it again maybe to a different project. Then please share the new _wandb.yaml file

**Comment by alijundi** [comment]
under windows wandb 0.12.9 does not work. Issue with temp files:

```
Scanning 'M:\AI\Feedback\CLASSIFIER\train' images and labels...90 found, 0 missing, 6 empty, 0 corrupt: 100%|█| 90/90 [
New cache created: M:\AI\Feedback\CLASSIFIER\train.cache
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]wandb: Adding directory to artifact (M:\AI\Feedback\CLASSIFIER\train)... Done. 0.3s
wandb: Adding directory to artifact (M:\AI\Feedback\CLASSIFIER\train)... Done. 0.3s
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.71it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 90/90 [01:20<00:00,  1.11it/s]
Traceback (most recent call last):
  File "C:\Work\Python\yolov5-master\utils\loggers\wandb\log_dataset.py", line 27, in <module>
    create_dataset_artifact(opt)
  File "C:\Work\Python\yolov5-master\utils\loggers\wandb\log_dataset.py", line 11, in create_dataset_artifact
    logger = WandbLogger(opt, None, job_type='Dataset Creation')  # TODO: return value unused
  File "C:\Work\Python\yolov5-master\utils\loggers\wandb\wandb_utils.py", line 190, in __init__
    self.data_dict = self.check_and_upload_dataset(opt)
  File "C:\Work\Python\yolov5-master\utils\loggers\wandb\wandb_utils.py", line 203, in check_and_upload_dataset
    config_path = self.log_dataset_artifact(opt.data,
  File "C:\Work\Python\yolov5-master\utils\loggers\wandb\wandb_utils.py", line 345, in log_dataset_artifact
    self.train_artifact = self.create_dataset_table(LoadImagesAndLabels(
  File "C:\Work\Python\yolov5-master\utils\loggers\wandb\wandb_utils.py", line 428, in create_dataset_table
    artifact.add(table, name)
  File "C:\Users\alijundi.TECOGRP\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_artifacts.py", line 500, in add
    val = obj.to_json(self)
  File "C:\Users\alijundi.TECOGRP\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\data_types.py", line 610, in to_json
    mapped_row.append(_json_helper(v, artifact))
  File "C:\Users\alijundi.TECOGRP\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\data_types.py", line 105, in _json_helper
    return val.to_json(artifact)
  File "C:\Users\alijundi.TECOGRP\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\data_types.py", line 2303, in to_json
    classes_entry = artifact.add(self._classes, class_name)
  File "C:\Users\alijundi.TECOGRP\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_artifacts.py", line 520, in add
    with self.new_file(name) as f:
  File "C:\Users\alijundi.TECOGRP\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "C:\Users\alijundi.TECOGRP\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_artifacts.py", line 359, in new_file
    raise ValueError(
ValueError: File with name "media\classes\9a0abffd2e2a2ca886e5654250e055d0_cls.classes.json" already exists at "C:\Users\ALIJUN~1.TEC\AppData\Local\Temp\tmp4i3zjdwy\media\classes\9a0abffd2e2a2ca886e5654250e055d0_cls.classes.json"

wandb: Waiting for W&B process to finish, PID 9644... (failed 1). Press ctrl-c to abort syncing.
wandb:
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Synced log dataset: https://wandb.ai/alijundi2/CLASSIFIER_FB/runs/yjsvgqzl
wandb: Find logs at: .\wandb\run-20220121_135808-yjsvgqzl\logs\debug.log
wandb:

C:\Work\Python\yolov5-master>
```

I use the latest version from github 0.12.10-dev

**Comment by alijundi** [comment]
version 0.12.10-dev uploads just fine. Issue resolved there!

**Comment by AyushExel** [comment]
@alijundi this issue will be fixed in the upcoming version as you've already seen.
Does training from artifact also works with the latest version of wandb? Is the issue completely resolved?

**Comment by alijundi** [comment]
@AyushExel 
I tried using the version 0.12.10-dev in colab as you have seen in the notebook. Same issue. I cannot start the training!

**Comment by AyushExel** [comment]
@alijundi Okay. I think this is an artifact issue. I'll try to find the cause of this and get it fixed. Thanks for your support

**Comment by alijundi** [comment]
@AyushExel. Thank you for your support!

**Comment by AyushExel** [comment]
@alijundi Okay so I tried this with the latest 0.12.10-dev:
1. Uploaded the dataset 
2. Started training on a colab
So, I think yet again this is a windows specific issue. I'll try to repro on windows later and forward to someone to fix

**Comment by alijundi** [comment]
@AyushExel Thank you for your efforts. Is there any way I can change some lines in the .py files to bypass the issue for now. I am in need to proceed with training for some models.

Thank you again for your attention.

**Comment by AyushExel** [comment]
@alijundi Download the dataset artifact manually on the colab using the artifact api.
Then train normally using the dataset instead of the wandb-artifact:// links

**Comment by alijundi** [comment]
@AyushExel Thank you for the suggestion I have begun training and saving my weights to google drive. I just miss the trends and tables of wandb. Hoping this would get resolved ASAP.

Thanks.

**Comment by alijundi** [comment]
Hi @AyushExel Can you please let me know if you had any success fixing this bug? Also can you label this issue as bug. Thanks.
