### ISSUE TITLE
where is my local model after downloading?

### ISSUE THREAD

**Issue by ZQQRYE** [ultralytics/yolov5#6373]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

thanks for your great work! i wanna ask a tiny question.After i load the model from torch.hub like this:
`model = torch.hub.load(r'E:\personal\OW\yolov5\yolov5', 'yolov5m', source='local')`
the terminal show this:
`Downloading https://github.com/ultralytics/yolov5/releases/download/v6.0/yolov5m.pt to yolov5m.pt...`
i wanna know where is the downloaded model?is the model in my computer?because i use the search function of windows the result is NONE.However the code works perfectly without downloading.
thanks for your patience.

**Comment by glenn-jocher** [comment]
@SHURYE I don't understand your question. The console output clearly states the download location:
```bash
Downloading https://github.com/ultralytics/yolov5/releases/download/v6.0/yolov5m.pt to yolov5m.pt
```
