### ISSUE TITLE
Console to GUI conversion

### ISSUE THREAD

**Issue by ITIZ78** [ultralytics/yolov5#6375]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi. is anybody know how to change the detect.py to run on GUI mode. I try tkinter, however, it shows difficulty because it has a command like"python detect.py --weights weights/best.pt --img 640 --conf 0.40 -- source" and it should be run on console only. How about to run it in GUI version. Is anybody has experienced do the project like this?

**Comment by glenn-jocher** [comment]
@ITIZ78 you might be thinking of a YOLOv5 REST API?

https://ultralytics.com/yolov5
<img width="1247" alt="Screen Shot 2022-01-20 at 2 50 55 PM" src="https://user-images.githubusercontent.com/26833433/150445714-1e1efb2d-55c4-4706-b8f6-4362c023b4b1.png">

**Comment by ITIZ78** [comment]
I think this one is for apps at phone right? Actually, mine is different.  The process is like this, after the camera detect/track the object , I need to make some process on it, for example if the false object is detected, the buzzer will on.

**Comment by ITIZ78** [comment]
> I think this one is for apps at phone right? Actually, mine is different. The process is like this, after the camera detect/track the object , I need to make some process on it, for example if the false object is detected, the buzzer will on.

**Comment by ITIZ78** [comment]
I think this one is for apps at phone right? Actually, mine is different. The process is like this, after the camera detect/track the object , I need to make some process on it, for example if the false object is detected, the buzzer will on.

**Comment by ITIZ78** [comment]
I want to reopen this issue, i wrongly click the close issue button

**Comment by ithmz** [comment]
@ITIZ78 you can reference to this [competition](https://github.com/ultralytics/yolov5/discussions/3213) and look up any platform you want to deploy your app on then 

> ### Question
> Hi. is anybody know how to change the detect.py to run on GUI mode. I try tkinter, however, it shows difficulty because it has a command like"python detect.py --weights weights/best.pt --img 640 --conf 0.40 -- source" and it should be run on console only. How about to run it in GUI version. Is anybody has experienced do the project like this?

Yes this is the CLI, if you want to inference you might want to look at the source code of detect.py
https://github.com/ultralytics/yolov5/blob/bd815d48df18a23e2bb08d88e430183bfb48eb78/detect.py#L51
