### ISSUE TITLE
it appeared “c10error” when VS2019  load the “yolov5s.torchscript.pt”

### ISSUE THREAD

**Issue by MrRe0** [ultralytics/yolov5#638]
when I load the “yolov5s.torchscript.pt“”，it has no problem， but when I execute the following statement：
 at::Tensor output = module.forward(inputs).toTensor();
it appeared the flowing error：
There is an unhandled exception at 0x00007FFB159FA799 (located in ConsoleApplication9.exe): Microsoft C++ exception: c10::Error, located at memory location 0x0000003EFB31FB70
but I use the other modes such as resnet_mode.pt , it has no error when run

my pytorch version is torch-1.6.0+cu101-cp36-cp36m-win_amd64
VS is 2019, sdk is10.0.17763.0

**Comment by MrRe0** [comment]
> when I load the “yolov5s.torchscript.pt“”，it has no problem， but when I execute the following statement：
> at::Tensor output = module.forward(inputs).toTensor();
> it appeared the flowing error：
> There is an unhandled exception at 0x00007FFB159FA799 (located in ConsoleApplication9.exe): Microsoft C++ exception: c10::Error, located at memory location 0x0000003EFB31FB70
> but I use the other modes such as resnet_mode.pt , it has no error when run
> 
> my pytorch version is torch-1.6.0+cu101-cp36-cp36m-win_amd64
> VS is 2019, sdk is10.0.17763.0

libtorch version is libtorch-win-shared-with-deps-1.6.0+cu101

**Comment by a328312879** [comment]
yolov5s.torchscript.pt output is not a tensor, but a list. You can use list type to obtain the results, such as: 
auto  output = module.forward(inputs);
 for(int i=0; i<output.size(); i++){at::Tensor result = output.get(i).toTensor();}
If this helps.

**Comment by liushuan** [comment]
same problem.

**Comment by pekinghk** [comment]
我也遇到了一样的问题，有没有大佬帮忙解答一下

**Comment by hongyiliang105598014** [comment]
> 我也遇到了一样的问题，有没有大佬帮忙解答一下

I use Libtorch 1.71 Nightly build and succeeded
