### ISSUE TITLE
Usage of model exported to onnx or tfjs format in JavaScript.

### ISSUE THREAD

**Issue by rtm-1dyakonov** [ultralytics/yolov5#6384]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello everyone!

Right now I want to integrate my YOLOv5n custom trained model into web application.
I've exported it to onnx and tensorflow.js formats. So there are two ways to implement in JavaScript: onnxruntime web or tensorflow.js 

Does anyone know how to do it or maybe even have experience of something related?

**Comment by glenn-jocher** [comment]
@rtm-1dyakonov interesting! Did not know about ORT web. We don't have examples of either yet, but if you find some please let us know.

It might be worth creating a separate tutorial for how to do this.

**Comment by lizozom** [comment]
@rtm-1dyakonov any luck with that?
I'm trying to do this myself atm

**Comment by SkalskiP** [comment]
Hi @rtm-1dyakonov and @lizozom! I recently created an NPM package that you can use to deploy your tensorflow.js on your website.

npm package source code: https://github.com/SkalskiP/yolov5js
deployment example: https://github.com/SkalskiP/yolov5js-example

I hope that my work will be helpful 🤞
