### ISSUE TITLE
Is it possible to stream the inferred content (with drawn bounding boxes etc.) from RTSP to RTSP/UDP multicast?

### ISSUE THREAD

**Issue by Prospekt117** [ultralytics/yolov5#6385]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, congratulations on Yolov5, it's an amazing tool!

I was wondering if it is possible to stream the Yolov5 inference of an RTSP live feed TO RTSP/UDP multicast?

There was a similar question but it talked of multiple sources to infer upon, I have a single RTSP source but I would like to multicast the inferred images (including bounding boxes etc) to multiple RTSP addresses (different from the source of course) but in real time. And where in the code could one work with that / which tools are best for the job? (Flask comes to mind but I don't know how applicable it is to Yolov5)

Thank you!

**Comment by glenn-jocher** [comment]
@Prospekt117 I'm not a web developer so I'm not sure exactly what this would look like, but you might start here with the results video writing. I assume that rather than write results frames to a video you might send/stream them somewhere else:

https://github.com/ultralytics/yolov5/blob/bd815d48df18a23e2bb08d88e430183bfb48eb78/detect.py#L187-L205

**Comment by tesorrells** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.
> 
> ### Question
> Hi, congratulations on Yolov5, it's an amazing tool!
> 
> I was wondering if it is possible to stream the Yolov5 inference of an RTSP live feed TO RTSP/UDP multicast?
> 
> There was a similar question but it talked of multiple sources to infer upon, I have a single RTSP source but I would like to multicast the inferred images (including bounding boxes etc) to multiple RTSP addresses (different from the source of course) but in real time. And where in the code could one work with that / which tools are best for the job? (Flask comes to mind but I don't know how applicable it is to Yolov5)
> 
> Thank you!
> 
> ### Additional
> _No response_

Did you ever figure this out? I'm trying to do something similar, I've considered saving the video as an .avi files and using ffmpeg to broadcast, but not sure how to handle the live write.

**Comment by glenn-jocher** [comment]
@tesorrells i haven't explored this myself, but your approach sounds reasonable. The `detect.py` script saves results to a video using `cv2.VideoWriter(...)`. Perhaps you could modify it to instead stream to an RTSP/UDP address using a similar process. Good luck, and please share your solution with the community if you find one!
