### ISSUE TITLE
wandb upload/syncing very slow

### ISSUE THREAD

**Issue by DavidBaldsiefen** [ultralytics/yolov5#6389]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I recently noticed that for me, wandb syncing at the end of a training is always extremely slow. Often, it takes around 10 minutes to upload less than 5mb of data. It will stay at "0.00MB" for most of the time and then jump to the max, where it will stay for another 1-2 minutes.

This has become especially problematic as I am trying to use hyperparameter evolution, where data is synced once after every run. Right now when training 10 epochs per generation, syncing takes longer than training itself.

I already checked my internet connection through manual uploads and saw significantly faster speeds.

My questions are as follows:

1. Is there any known reason why syncing would be so slow?
2. Is it possible to make wandb only sync once *after* the 300 evolutions have been performed, as opposed to syncing once per evolution?

![image](https://user-images.githubusercontent.com/4655486/150621834-380643aa-08ea-4521-b421-eeac33da77f1.png)

**Comment by glenn-jocher** [comment]
@DavidBaldsiefen thanks for the feedback! @AyushExel are there any network issues recently on the wandb side that might be causing delays?

**Comment by AyushExel** [comment]
@glenn-jocher There are no known network issues. Probably it has something to do with the users' networks. Nevertheless, there are some things that we can do to reduce the size of load.
* First, do you like the idea of disabling media logging in evolve?
* Second, Should we use just one wandb run for all runs in an evolve?

**Comment by glenn-jocher** [comment]
@AyushExel I think disabling media logging is a good idea during evolve. I don't produce any of the normal imagery like confusion matrices and validation batch images etc. when evolve is on. Let's start with that. Thanks!

**Comment by glenn-jocher** [comment]
@DavidBaldsiefen good news 😃! Your original issue may now be fixed ✅ in PR #6617 by @AyushExel. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
