### ISSUE TITLE
How architecture Lighter methode ??

### ISSUE THREAD

**Issue by ONNONS** [ultralytics/yolov5#6390]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

What are some ways to make the YOLOv 5 NANO version lighter?

**Comment by glenn-jocher** [comment]
@ONNONS you could try reducing the compound scaling constants here:
https://github.com/ultralytics/yolov5/blob/bd815d48df18a23e2bb08d88e430183bfb48eb78/models/yolov5n.yaml#L5-L6

And you could also eliminate the P5 output layer in the head leaving only P3 and P4, i.e.
https://github.com/ultralytics/yolov5/blob/bd815d48df18a23e2bb08d88e430183bfb48eb78/models/hub/yolov5-p34.yaml#L3-L41

**Comment by seungyong0313** [comment]
I ran your code but got the following error: And can you explain why the weight is reduced by removing the head layer?

Traceback (most recent call last):
  File "train.py", line 636, in <module>
    main(opt)
  File "train.py", line 533, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 124, in train
    model = Model(cfg or ckpt['model'].yaml, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)  # create
  File "/content/yolov5/models/yolo.py", line 103, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=[ch])  # model, savelist
  File "/content/yolov5/models/yolo.py", line 274, in parse_model
    args.append([ch[x] for x in f])
  File "/content/yolov5/models/yolo.py", line 274, in <listcomp>
    args.append([ch[x] for x in f])
IndexError: list index out of range

**Comment by seungyong0313** [comment]
Can you explain why the weight is reduced by adjusting the head layer and depth and width?

Other than what you said, are there any other ways to reduce weight? And I am very grateful to you thank you

**Comment by glenn-jocher** [comment]
@seungyong0313 I designed the YOLOv5 compound scaling constants on the EfficientDet paper: https://arxiv.org/abs/1911.09070
