### ISSUE TITLE
no module named models when I change filename

### ISSUE THREAD

**Issue by futureflsl** [ultralytics/yolov5#6396]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

for some reseason.I have to change yolov5-6.0\models\yolo.py to yolov5-6.0\models_2022\yolo.py.When I detect my weights.I find that error occured.just like No module named 'models'.I found issue https://github.com/ultralytics/yolov5/issues/1680.that seem to be like my problem.He deleted models directory and made modesl_all.py.and it has the same problem.So How to change folder name and make weights work well?

**Comment by anurag-pushpak** [comment]
Did you change the imports everywhere? 

You have to change it from -> `from models.yolo` to from `models.models_2022.yolo`

You can find it in train.py, export.py, tf.py, hubconf.py and exprimental.py.

**Comment by 4nuragk** [comment]
Did you change the imports everywhere?

You have to change it from -> from models.yolo to from models.models_2022.yolo

You can find it in train.py, export.py, tf.py, hubconf.py and exprimental.py.

**Comment by futureflsl** [comment]
> Did you change the imports everywhere?
> 
> You have to change it from -> `from models.yolo` to `from models.models_2022.yolo`
> 
> You can find it in train.py, export.py, tf.py, hubconf.py and exprimental.py.

you did not get my problem.I changed models directory,and modified all relative py files.but weights will does not work
