### ISSUE TITLE
I have Tello drone and have trained Yolo5 to identify a custom class, my robot.  I want to use the video from the tello drone instead of the web cam.  For the Tello drone I use me = tello.Tello() then frame = me.get_frame_read().frame.  How would I get this fram into detect.py?  Thanks

### ISSUE THREAD

**Issue by jerryjavelin** [ultralytics/yolov5#6397]
### Discussed in https://github.com/ultralytics/yolov5/discussions/2457

<div type='discussions-op-text'>

<sup>Originally posted by **Samuel-Bachorik** March 13, 2021</sup>
Hi, I'm currently working with yolo and webcam, so source is equal to "0". The problem is I need to access the webcam frames that is your Yolo going to process. I'm running detect.py. My goal is to get that frame process it for road detection and then I want to sent this frame to Yolo so I am asking you if you can show me the line of code where I can get webcam frames before they go to Yolo so I can process them first. 

THANK YOU FOR ALL OF YOUR HELP :) </div>

**Comment by glenn-jocher** [comment]
@jerryjavelin detect.py dataloader returns frames here:
https://github.com/ultralytics/yolov5/blob/8efe97719c9b3b77c9db9b5c8592e051b7f0c9a7/detect.py#L115

**Comment by glenn-jocher** [comment]
Resized frame is `im` and original frame is `im0s`.

**Comment by jerryjavelin** [comment]
Thank you very much.  I am not sure exactly what you are trying to tell me, I am not the most fluent python programmer, BUT you pointed me in the right direction, I think.  I am away from my drone so I cannot try the following until this weekend.  I will modify LoadStreams in datasets.py and change cap = cv2.VideoCapture(s) to cap = me.get_frame_read().frame I will also put source = 0 so detect.py knows the source is a video stream.  I will let you know if it works next week.  I am sure you were trying to tell me a more elegant method but my skill isn't at that level.  I will try this and let you know if my brute force method works.  Thanks again, very much.  Jerry

**Comment by Loqmane007** [comment]
I'm on the exact same project as you.
Did you finally found a working solution?
cap = me.get_frame_read() did work ?

**Comment by glenn-jocher** [comment]
@Loqmane007 @jerryjavelin 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, etc.
# model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')  # custom trained model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)  # or a batch of images [im1, im2, ...]

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by mchtenes** [comment]
Hi Glenn,
i just started with YOLOv5 and copy-pasted the above code example to pycharm but it doesnt detect as example. Also i tried the run "detect.py" with same picture then it works.  What am I doing wrong ?

**Comment by jerryjavelin** [comment]
Loqmane007, 
Did you have success at what you were trying to do?  Sorry I have been out of pocket for a while.   I have had some success by "hacking" the detect.py code.  I put it in a loop where  "if__name__ == "__ main__" :"  I put the Tello commands for the stream on etc. Then in def main I saved each Tello drone frame in the loop by executing me.get_frame_read and store every image captured with cv.imwrite as kang0. After modifying the detect.py code as I just described then I run dtect.py that now uses each saved tello drone image that is saved and then overwritten as kang0.jpg  with:  
python detect.py --source kang0.jpg --weights runs/train/yolo_Fast_Bot_det5/weights/best.pt --conf 0.1 --name yolo_web_cam_detect   The downside of this hack is that each result is saved in a separate folder.  Then separately I wrote code to open each folder and save the image that is in each folder to a new folder.  Thus, the new folder contains all the images.  Then I use a program that takes all these images in that folder and makes a movie.   Another unfortunate issue is the movie does not necessarily preserve the order of all the images.  I admit, I am not a good programmer.  My next plan is to go into detect.py and have it display the annotated images as it runs and add that it stores all these images into one folder so I don't have to run my other program to do that gathering.   Let me know if this helps and if you have other questions or comments.

**Comment by Loqmane007** [comment]
I did not completely understand "I put the Tello commands for the stream on etc".

I tried your method but it didn't work for me. I am a beginner and I find some difficulties

> Loqmane007, Did you have success at what you were trying to do? Sorry I have been out of pocket for a while. I have had some success by "hacking" the detect.py code. I put it in a loop where "if__name__ == "__ main__" :" I put the Tello commands for the stream on etc. Then in def main I saved each Tello drone frame in the loop by executing me.get_frame_read and store every image captured with cv.imwrite as kang0. After modifying the detect.py code as I just described then I run dtect.py that now uses each saved tello drone image that is saved and then overwritten as kang0.jpg with: python detect.py --source kang0.jpg --weights runs/train/yolo_Fast_Bot_det5/weights/best.pt --conf 0.1 --name yolo_web_cam_detect The downside of this hack is that each result is saved in a separate folder. Then separately I wrote code to open each folder and save the image that is in each folder to a new folder. Thus, the new folder contains all the images. Then I use a program that takes all these images in that folder and makes a movie. Another unfortunate issue is the movie does not necessarily preserve the order of all the images. I admit, I am not a good programmer. My next plan is to go into detect.py and have it display the annotated images as it runs and add that it stores all these images into one folder so I don't have to run my other program to do that gathering. Let me know if this helps and if you have other questions or comments.

Thank you for your answer,
I did not completely understand "I put the Tello commands for the stream on etc".
I tried your method but it didn't work for me. I am a beginner and I find some difficulties

**Comment by jerryjavelin** [comment]
Here is the code I mentioned for detect.py

def main(opt):
    check_requirements(exclude=('tensorboard','thop'))
    #$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
    while True:  # for drone
        # while (cap.isOpened()):
        # ret, frame = cap.read()
        frame = me.get_frame_read().frame
        # ret, frame = cap.read()
        cv.imwrite('kang0.jpg', frame)
        img = cv.imread('kang0.jpg', 0)
        cv2.imshow("Iamge", img)
        #$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
        run(**vars(opt))
        #$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
        #$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$


if __name__ == "__main__":
    opt = parse_opt()
    #$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
    me = tello.Tello()
    me.connect()
    me.get_battery()
    print(me.get_battery())
    me.streamoff()
    me.streamon()
    #$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
    main(opt)

 

 

and use:

 

for single image I named:
kang0.jpg 
that I used in the above code:
python detect.py --source kang0.jpg --weightsruns/train/yolo_Fast_Bot_det5/weights/best.pt --conf 0.1 --nameyolo_web_cam_detect

The screen will appear due to 

        cv2.imshow("Iamge", img)

 

but this is only theraw image.  The image with the detectwill be stored in the folders as I previously  described


    On Sunday, February 20, 2022, 06:14:59 AM EST, Loqmane007 ***@***.***> wrote:  
 
 


I did not completely understand "I put the Tello commands for the stream on etc".

I tried your method but it didn't work for me. I am a beginner and I find some difficulties


Loqmane007, Did you have success at what you were trying to do? Sorry I have been out of pocket for a while. I have had some success by "hacking" the detect.py code. I put it in a loop where "if__name__ == "__ main__" :" I put the Tello commands for the stream on etc. Then in def main I saved each Tello drone frame in the loop by executing me.get_frame_read and store every image captured with cv.imwrite as kang0. After modifying the detect.py code as I just described then I run dtect.py that now uses each saved tello drone image that is saved and then overwritten as kang0.jpg with: python detect.py --source kang0.jpg --weights runs/train/yolo_Fast_Bot_det5/weights/best.pt --conf 0.1 --name yolo_web_cam_detect The downside of this hack is that each result is saved in a separate folder. Then separately I wrote code to open each folder and save the image that is in each folder to a new folder. Thus, the new folder contains all the images. Then I use a program that takes all these images in that folder and makes a movie. Another unfortunate issue is the movie does not necessarily preserve the order of all the images. I admit, I am not a good programmer. My next plan is to go into detect.py and have it display the annotated images as it runs and add that it stores all these images into one folder so I don't have to run my other program to do that gathering. Let me know if this helps and if you have other questions or comments.


Thank you for your answer,
I did not completely understand "I put the Tello commands for the stream on etc".
I tried your method but it didn't work for me. I am a beginner and I find some difficulties

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jerryjavelin** [comment]
Let me know if you got this, also let me know if it worked.
    On Sunday, February 20, 2022, 05:16:24 PM EST, Gerard Barone ***@***.***> wrote:  
 
  Here is the code I mentioned for detect.py

def main(opt):
    check_requirements(exclude=('tensorboard','thop'))
    #$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
    while True:  # for drone
        # while (cap.isOpened()):
        # ret, frame = cap.read()
        frame = me.get_frame_read().frame
        # ret, frame = cap.read()
        cv.imwrite('kang0.jpg', frame)
        img = cv.imread('kang0.jpg', 0)
        cv2.imshow("Iamge", img)
        #$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
        run(**vars(opt))
        #$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
        #$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$


if __name__ == "__main__":
    opt = parse_opt()
    #$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
    me = tello.Tello()
    me.connect()
    me.get_battery()
    print(me.get_battery())
    me.streamoff()
    me.streamon()
    #$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
    main(opt)

 

 

and use:

 

for single image I named:
kang0.jpg 
that I used in the above code:
python detect.py --source kang0.jpg --weightsruns/train/yolo_Fast_Bot_det5/weights/best.pt --conf 0.1 --nameyolo_web_cam_detect

The screen will appear due to 

        cv2.imshow("Iamge", img)

 

but this is only theraw image.  The image with the detectwill be stored in the folders as I previously  described


    On Sunday, February 20, 2022, 06:14:59 AM EST, Loqmane007 ***@***.***> wrote:  
 
 


I did not completely understand "I put the Tello commands for the stream on etc".

I tried your method but it didn't work for me. I am a beginner and I find some difficulties


Loqmane007, Did you have success at what you were trying to do? Sorry I have been out of pocket for a while. I have had some success by "hacking" the detect.py code. I put it in a loop where "if__name__ == "__ main__" :" I put the Tello commands for the stream on etc. Then in def main I saved each Tello drone frame in the loop by executing me.get_frame_read and store every image captured with cv.imwrite as kang0. After modifying the detect.py code as I just described then I run dtect.py that now uses each saved tello drone image that is saved and then overwritten as kang0.jpg with: python detect.py --source kang0.jpg --weights runs/train/yolo_Fast_Bot_det5/weights/best.pt --conf 0.1 --name yolo_web_cam_detect The downside of this hack is that each result is saved in a separate folder. Then separately I wrote code to open each folder and save the image that is in each folder to a new folder. Thus, the new folder contains all the images. Then I use a program that takes all these images in that folder and makes a movie. Another unfortunate issue is the movie does not necessarily preserve the order of all the images. I admit, I am not a good programmer. My next plan is to go into detect.py and have it display the annotated images as it runs and add that it stores all these images into one folder so I don't have to run my other program to do that gathering. Let me know if this helps and if you have other questions or comments.


Thank you for your answer,
I did not completely understand "I put the Tello commands for the stream on etc".
I tried your method but it didn't work for me. I am a beginner and I find some difficulties

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Loqmane007** [comment]
> Let me know if you got this, also let me know if it worked. On Sunday, February 20, 2022, 05:16:24 PM EST, Gerard Barone ***@***.***> wrote: Here is the code I mentioned for detect.py def main(opt):     check_requirements(exclude=('tensorboard','thop'))     #$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$     while True:  # for drone         # while (cap.isOpened()):         # ret, frame = cap.read()         frame = me.get_frame_read().frame         # ret, frame = cap.read()         cv.imwrite('kang0.jpg', frame)         img = cv.imread('kang0.jpg', 0)         cv2.imshow("Iamge", img)         #$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$         run(**vars(opt))         #$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$         if cv2.waitKey(1) & 0xFF == ord('q'):             break         #$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ if __name__ == "__main__":     opt = parse_opt()     #$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$     me = tello.Tello()     me.connect()     me.get_battery()     print(me.get_battery())     me.streamoff()     me.streamon()     #$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$     main(opt)     and use:   for single image I named: kang0.jpg that I used in the above code: python detect.py --source kang0.jpg --weightsruns/train/yolo_Fast_Bot_det5/weights/best.pt --conf 0.1 --nameyolo_web_cam_detect The screen will appear due to         cv2.imshow("Iamge", img)   but this is only theraw image.  The image with the detectwill be stored in the folders as I previously  described On Sunday, February 20, 2022, 06:14:59 AM EST, Loqmane007 ***@***.***> wrote: I did not completely understand "I put the Tello commands for the stream on etc". I tried your method but it didn't work for me. I am a beginner and I find some difficulties Loqmane007, Did you have success at what you were trying to do? Sorry I have been out of pocket for a while. I have had some success by "hacking" the detect.py code. I put it in a loop where "if__name__ == "__ main__" :" I put the Tello commands for the stream on etc. Then in def main I saved each Tello drone frame in the loop by executing me.get_frame_read and store every image captured with cv.imwrite as kang0. After modifying the detect.py code as I just described then I run dtect.py that now uses each saved tello drone image that is saved and then overwritten as kang0.jpg with: python detect.py --source kang0.jpg --weights runs/train/yolo_Fast_Bot_det5/weights/best.pt --conf 0.1 --name yolo_web_cam_detect The downside of this hack is that each result is saved in a separate folder. Then separately I wrote code to open each folder and save the image that is in each folder to a new folder. Thus, the new folder contains all the images. Then I use a program that takes all these images in that folder and makes a movie. Another unfortunate issue is the movie does not necessarily preserve the order of all the images. I admit, I am not a good programmer. My next plan is to go into detect.py and have it display the annotated images as it runs and add that it stores all these images into one folder so I don't have to run my other program to do that gathering. Let me know if this helps and if you have other questions or comments. Thank you for your answer, I did not completely understand "I put the Tello commands for the stream on etc". I tried your method but it didn't work for me. I am a beginner and I find some difficulties — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.Message ID: ***@***.***>

Hello,
no, I haven't succeeded yet.
And you, were you able to use yolov5 with the drone?
