### ISSUE TITLE
apply dIOU replace gIOU

### ISSUE THREAD

**Issue by lucasjinreal** [ultralytics/yolov5#64]
Will dIOU obtain a better result then gIOU?

**Comment by glenn-jocher** [comment]
I don't know. You can use g/d/ciou in the loss function by specifying it here. To use DIoU you would pass `DIoU=True` in place of the current GIoU on L413.

https://github.com/ultralytics/yolov5/blob/111994956ede6964433e02bc3f64deb04b9916ac/utils/utils.py#L409-L413

**Comment by aktiver** [comment]
Update for Yolov5: This is now in[` loss.py `](https://github.com/ultralytics/yolov5/blob/master/utils/loss.py#L141)on line `141`:

**Default (CIoU):** [_Paper_](https://arxiv.org/pdf/2005.03572.pdf)
`iou = bbox_iou(pbox, tbox[i], CIoU=True).squeeze()  # iou(prediction, target)`
 
 **GIoU:** [_Paper_](https://arxiv.org/abs/1902.09630)
`iou = bbox_iou(pbox, tbox[i], GIoU=True).squeeze()  # iou(prediction, target)`

**DIoU:** [_Paper_](https://arxiv.org/pdf/1911.08287.pdf)
`iou = bbox_iou(pbox, tbox[i], DIoU=True).squeeze()  # iou(prediction, target)`

The definition of `bbox_iou` is on line 216 in [`metrics.py`](https://github.com/ultralytics/yolov5/blob/master/utils/metrics.py#L216).

**Comment by glenn-jocher** [comment]
@aktiver thanks for your update! The implementation of DIoU, GIoU, and CIoU are all available in the `loss.py` file, and the `bbox_iou` definition can be found in the `metrics.py` file. You can now easily choose and use the desired IoU metric in your YOLOv5 implementation. If you have further questions or need assistance, feel free to reach out.
