### ISSUE TITLE
Easy way to save checkpoints for Colab user

### ISSUE THREAD

**Issue by TaoXieSZ** [ultralytics/yolov5#640]
## 🚀 Feature

It will be more convenient for Colab user to save checkpoints in Google Drive than in yolov5/runs.

## My idea

Just change in nearly line 458 to 464 (in my current version):
```python
if not opt.evolve:
        tb_writer = None
        if opt.local_rank in [-1, 0]:
            print('Start Tensorboard with "tensorboard --logdir=runs", view at http://localhost:6006/')
           # Change the path here
            tb_writer = SummaryWriter(log_dir=increment_dir('/content/drive/My Drive/yolov5-checkpoints/exp', opt.name))

        train(hyp, opt, device, tb_writer)

```

**Comment by glenn-jocher** [comment]
@ChristopherSTAN can you point tensorboard to a google drive folder like you have? That would be really cool, then all of your work is saved and you can keep track of experiments this way.

**Comment by glenn-jocher** [comment]
This is a really good pro tip for Colab users! Maybe we should add a `--log-dir` argument to train.py to enable this?

**Comment by TaoXieSZ** [comment]
@glenn-jocher You remind me about that.

However, I have long time no looking the tensorBoard. I just try and it can only point to the data inside yolov5's folder.

For the argument problem, that's up to you, LOL. And I think it is more convenient for colab users if you do. There is `--work-dir` argument in mmdetection. It ignites my idea about this and I find it can save checkpoints in larger google drive.
![image](https://user-images.githubusercontent.com/7379039/89607656-0cf3ce80-d841-11ea-81d0-c2a1148dd632.png)

BTW, in my experience, using tensorboard often slows notebooks and raises disconnection (maybe Google try to avoid over-usage), so I ignore that.

**Comment by glenn-jocher** [comment]
It does work! Wow, so this is a backdoor to permanence with Colab. You can actually log all of your experiments straight to drive, and then pick up where you left off the next day without having to move any files. This is a real game changer for colab dev work. I'll add a PR for the argparser --logdir argument.

<img width="1177" alt="Screen Shot 2020-08-06 at 9 36 34 PM" src="https://user-images.githubusercontent.com/26833433/89609506-eb88e780-d82c-11ea-8be7-4fffe20f2c9d.png">

**Comment by TaoXieSZ** [comment]
@glenn-jocher It is really amazing!

**Comment by glenn-jocher** [comment]
All done. Thanks for the great idea @ChristopherSTAN!

**Comment by TaoXieSZ** [comment]
@glenn-jocher It is just kind of feedback from a deep-user. Expecting for better yolov5 in the future.

BTW, I noticed the default bbox loss is now CIoU, maybe you should update the logging entry. It may raise some confusion.

**Comment by ChristopherSTAN** [comment]
@glenn-jocher Another potential little advice.
I find if use `--resume`:
https://github.com/ultralytics/yolov5/blob/916d4aad9a154587dc5914f9b04be575a0990529/train.py#L418-L422
I seem the default searching path is '/run/':
https://github.com/ultralytics/yolov5/blob/916d4aad9a154587dc5914f9b04be575a0990529/utils/general.py#L61-L64

I wonder if we can change like this to get custom latest run :
```python
last = get_latest_run(opt.logdir) if opt.resume == 'get_last' else opt.resume
```

**Comment by glenn-jocher** [comment]
@ChristopherSTAN yes, you are correct, it's now CIoU. Yes I need to update the comment to a criterion-agnostic term like 'box' or 'regression'.

**Comment by glenn-jocher** [comment]
TODO: Update GIoU labels to criteria-agnostic terms.

**Comment by maheeeetaaa** [comment]
@glenn-jocher  Hello, I have been trying to train yolov5_v4 it seems that the train arguments have changed, before i used to use logdir and then when the training would stop ( because i work on colab) i would run it and it would have picked up from where it started but now, it doesnt! i even set the new weights but the training starts as if there has been no training before, the epoch number doesnt reset but all the map graphs show that the training has started from the beginning. What should I do? 



here are my arguments :

!python train.py --img 320 --batch 128 --epochs 200 \
  --data /content/YoloV5Data/data.yaml \
  --cfg ./models/yolov5s.yaml \
  --weights  /content/drive/Yolov5S_320/exp5/weights/last.pt\  

  --project /content/drive/Yolov5S_320/

**Comment by glenn-jocher** [comment]
@maheeetaaa yes local directly logging structure was unified in https://github.com/ultralytics/yolov5/pull/1377. Training results are saved to runs/train/exp.

You may resume an interrupted training run very simply:
```bash
python train.py --resume  # automatically select most recent run
python train.py --resume path/to/last.pt  # manually specify run to resume
```

**Comment by Leprechault** [comment]
> ## 🚀 Feature
> It will be more convenient for Colab user to save checkpoints in Google Drive than in yolov5/runs.
> 
> ## My idea
> Just change in nearly line 458 to 464 (in my current version):
> 
> ```python
> if not opt.evolve:
>         tb_writer = None
>         if opt.local_rank in [-1, 0]:
>             print('Start Tensorboard with "tensorboard --logdir=runs", view at http://localhost:6006/')
>            # Change the path here
>             tb_writer = SummaryWriter(log_dir=increment_dir('/content/drive/My Drive/yolov5-checkpoints/exp', opt.name))
> 
>         train(hyp, opt, device, tb_writer)
> ```

@TaoXieSZ for me as fresh in the subject, I don't understand if your proposed change in lines 458 to 464 is inside model yaml file or another file? Could you please help me?

**Comment by glenn-jocher** [comment]
@Leprechault runs can be logged anywhere now, so @TaoXieSZ comment is no longer applicable. To long a run to any directory use the --project argument along with the --name argument:
`python train.py --project runs/train --name exp`

**Comment by Leprechault** [comment]
Thanks very much @glenn-jocher !!!!
