### ISSUE TITLE
WARNING: The shape inference of prim::Constant type is missing

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#6401]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

The command 
```
CUDA_VISIBLE_DEVICES=2 python export.py --batch 1 --train --simplify --img 640 640 --weights 123.pt
```

```
ONNX: starting export with onnx 1.8.204...
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
```
What is the warning ?

**Comment by zhiqwang** [comment]
I guess you can just ignore this warning, as warning is not error.

**Comment by alicera** [comment]
Thanks for your reply.
Do you know what is that?

**Comment by mszuyx** [comment]
I also got tons of these when trying to convert a pytorch model to onnx. But as I compare the converted model with the original, they are pretty much identical, so I don't think it is don't actual harm besides annoying. Let me know if you find out more about it.

**Comment by glenn-jocher** [comment]
@alicera @zhiqwang @mszuyx I've opened PR #7404 to filter these warnings (so they won't appear) on ONNX opset >= 13 export. For some reason my fix is not working though. If you have any ideas let me know!

**Comment by mszuyx** [comment]
@glenn-jocher Sounds good! So you are saying they don't mean any harm besides annoying?

**Comment by glenn-jocher** [comment]
@mszuyx yes the Warnings can be ignored. I tried to suppress them in #7404 but it's not working, not sure why. If you could help on the PR that would be great!

**Comment by ganler** [comment]
@glenn-jocher I think it might be a PyTorch bug that the developers simply print stuff to STDERR in C++ binary... I reported here: https://github.com/pytorch/pytorch/issues/77494 Hope it can get fixed soon.

**Comment by glenn-jocher** [comment]
@ganler Thanks for reporting this to PyTorch! Hopefully, they'll address it soon. If you have any more insights, feel free to share them on the PR or here. Appreciate the collaboration!
