### ISSUE TITLE
Alternative video Library for opencv

### ISSUE THREAD

**Issue by balaji-skoruz** [ultralytics/yolov5#6402]
is there any video library other than opencv ?
opencv took considerable amount of time to read the frame. and I need production grade video reading library

**Comment by zhiqwang** [comment]
I guess you can try pyav https://github.com/PyAV-Org/PyAV

**Comment by balaji-skoruz** [comment]
> I guess you can try pyav https://github.com/PyAV-Org/PyAV
I need a production grade library

**Comment by zhiqwang** [comment]
actually pyav is a wrapper of ffmpeg, you can try ffmpeg instead.

**Comment by balaji-skoruz** [comment]
I need to take only 1 frame from 30 frames (30 fps video). opencv nearly took 0.1 seconds to read a frame from a video which means I need to read and skip 29 frames . so 29 * 0.1 = 2.9 seconds delay for 1 sec video.
