### ISSUE TITLE
IOU threshold for true positive / precision?

### ISSUE THREAD

**Issue by KristofferK** [ultralytics/yolov5#6409]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

What is the IOU threshold for a detection/prediction to be determined a true positive in regards of calculating the precision (not AP@0.5, or AP@[0.5:0.95] where it is specified), but the "normal" precision metric. In val.py I only see a IOU threshold for NMS, but not for when a prediction is a true positive to the ground truth.

**Comment by KristofferK** [comment]
From what I can see, then true positive is calculated in process_batch and determined by if iou >= iouv[0]. iouv[0] seems to be 0.5. So the iou threshold for a single detection to be a true positive must be 0.5. Is this correct?

**Comment by glenn-jocher** [comment]
@KristofferK TPs and FPs are use a confidence threshold determined by the max F1 confidence.
https://github.com/ultralytics/yolov5/blob/8efe97719c9b3b77c9db9b5c8592e051b7f0c9a7/utils/metrics.py#L82-L86

**Comment by JanErikDoornweerd** [comment]
@glenn-jocher 
Just for my understanding, and for future reference.

True positive if:
- Confidence > Confidence threshold [Determined by max F1 confidence] 
- Class matches ground truth class
- IOU > 0.5 [As per  iou >= iouv[0]]

False positive if:
- Class does not match ground truth class
- IOU <= 0.5 [As per  iou >= iouv[0]]

False negative if:
- Confidence <= Confidence threshold [Determined by max F1 confidence]
