### ISSUE TITLE
Saving output data from detect.py run

### ISSUE THREAD

**Issue by sssphysss** [ultralytics/yolov5#6413]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,
Has anyone ever experienced  extracting output data of detect.py runs? 
I am interested in finding the number of detected objects at every single img or img order so I can analyse them later for other purposes.
However, whenever I try saving results and output, I end up only with class and coordinate values which are out of my interest in this case. 
Is there any way to extract those output? as I can see them clearly when the code start running just like in the image below, but how can I save them?

<img width="989" alt="Screenshot 2022-01-24 at 22 45 27" src="https://user-images.githubusercontent.com/98362387/150880582-461d34a5-2a18-440c-a3c6-450689e15f23.png">

**Comment by glenn-jocher** [comment]
@sssphysss 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, etc.
# model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')  # custom trained model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by sssphysss** [comment]
Thank you so much that was of a great help!
Here is how I managed to extract the data I wanted out of the results
 ```
import numpy as np

re = results.pandas().xyxy
total = np.shape(re)[0]    # total number of images
print('total images =', total)

unf = np.array([])     # number of unfrozen droplets 
sl = np.array([])     # slices / #images 

c = 1
while c <= total:
    
    for i in re:
            
        n = np.shape(i)[0]   # number of detected objects in each slice/image 
        
        if n > 0:
            
            unf = np.append(unf,n)
            sl = np.append(sl,c)
            
        c += 1
                                       
print(unf) 
print (sl)  
```

**Comment by russskiykorablidinah** [comment]
> Thank you so much that was of a great help! Here is how I managed to extract the data I wanted out of the results
> 
> ```
> import numpy as np
> 
> re = results.pandas().xyxy
> total = np.shape(re)[0]    # total number of images
> print('total images =', total)
> 
> unf = np.array([])     # number of unfrozen droplets 
> sl = np.array([])     # slices / #images 
> 
> c = 1
> while c <= total:
>    
>    for i in re:
>            
>        n = np.shape(i)[0]   # number of detected objects in each slice/image 
>        
>        if n > 0:
>            
>            unf = np.append(unf,n)
>            sl = np.append(sl,c)
>            
>        c += 1
>                                       
> print(unf) 
> print (sl)  
> ```

Hello, can you please tell me where you put this code?

**Comment by sssphysss** [comment]
@russskiykorablidinah , Here is an example of where I put the code.

```
import torch
import glob
from natsort import natsorted
import cv2
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd

model = torch.hub.load('ultralytics/yolov5', 'custom', '/Users/sarah/Desktop/best1.pt')  # custom trained model
model.conf = 0.7  # NMS confidence threshold

Path = '/Users/sarah/Desktop/Run20/'

imgs = [cv2.imread(file) for file in natsorted(glob.glob(Path+"/*.jpg"))]

#print('image_array shape:', np.array(imgs).shape[0])

# Inference
results = model(imgs,size=416)


# Results:

#results.save() # or .print() .show(), .save(), .crop(), .pandas(), etc.
#results.pandas()
results.print()

m = model(imgs[0],size=416)
#m.show()
plt.imshow(np.squeeze(m.render()))
plt.show()

#### Here where the code start to extract the output:

re = results.pandas().xyxy
total = np.shape(re)[0]    # total number of images
print('total images =', total)

unf = np.array([])     # number of unfrozen droplets 
sl = np.array([])     # slices / #images 

c = 1
while c <= total:
    
    for i in re:
            
        n = np.shape(i)[0]   # number of detected objects in each slice/image 
        
        if n > 0:
            if n not in unf:
                
                unf = np.append(unf,n)
                sl = np.append(sl,c)
            
        c += 1
                                       
print(unf) 
print (sl)


```
