### ISSUE TITLE
Unable to open webcam for detecting object in google colab

### ISSUE THREAD

**Issue by lokesh-v** [ultralytics/yolov5#6418]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi..., Unable to open webcam for detecting object in google colab.
When I give source 0 for detecting throwing an error.

File "/content/yolov5/utils/datasets.py", line 310, in __init__
    assert cap.isOpened(), f'{st}Failed to open {s}'
AssertionError: 1/1: 0... Failed to open 0

**Comment by glenn-jocher** [comment]
@lokesh-v Colab does not have access to local system resources, it is run on a Google cloud instance backend.

You can use a local webcam when running YOLOv5 locally.

**Comment by lokesh-v** [comment]
thanks, @glenn-jocher for your quick response! So you mean we can't open the webcam in google colab.

![error](https://user-images.githubusercontent.com/39947547/150973916-6f34465a-ca53-4c60-a38e-a99cf531b139.PNG)

**Comment by aryan51k** [comment]
@lokesh-v you cannot open the webcam in colab

**Comment by Guttappa1238** [comment]
@lokesh-v  You can work around this!!
https://colab.research.google.com/drive/1rGEAztA_FOn3mdb-l9DfZ7OQyb7jpgwQ?usp=sharing

**Comment by lokesh-v** [comment]
Thanks! @Guttappa1238 I will try this [https://colab.research.google.com/drive/1rGEAztA_FOn3mdb-l9DfZ7OQyb7jpgwQ?usp=sharing]
