### ISSUE TITLE
Incremental Learning for Yolo V5 in Object Detection

### ISSUE THREAD

**Issue by ygkrishna** [ultralytics/yolov5#6419]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have trained a custom object detection model with 5 classes. Now I want to re-train my model on a dataset corresponding to 6th class and the new model should detect all the 6 classes. How should I do that?

**Comment by aryan51k** [comment]
@ygkrishna You will have to start the training again you cannot resume the training if you have added the class.

**Comment by ygkrishna** [comment]
> @ygkrishna You will have to start the training again you cannot resume the training if you have added the class.

Then how do we implement Incremental learning in yolov5 by training portion of data each time?

**Comment by aryan51k** [comment]
@ygkrishna According to my knowledge it is not possible. But please refer this thread https://github.com/ultralytics/yolov5/issues/469.

**Comment by glenn-jocher** [comment]
@ygkrishna you would simply train a new model on the updated dataset using your existing model as pretrained weights, i.e.:

```
python train.py --data updated_dataset.yaml --weights path/to/original_dataset/weights/best.pt
```

**Comment by ygkrishna** [comment]
> @ygkrishna you would simply train a new model on the updated dataset using your existing model as pretrained weights, i.e.:
> 
> ```
> python train.py --data updated_dataset.yaml --weights path/to/original_dataset/weights/best.pt
> ```

Hi Glenn,
I tried your approach and the model is able to identify new classes but not the old ones.

***What I have tried***
1. Using transfer learning and Yolo5S.pt I have trained a model with a dataset labeled with Class A and generated weights.
2. I created another dataset labeled only on Class B and re-trained the model using the updated weights from Step1.
3. Now the new weights (best.pt or last.pt) are detecting Class B only on the given test images.

**Comment by aryan51k** [comment]
@ygkrishna Exactly I also required the same functionality for my project but was struck at the same problem. But when you train again using the pre trained weights you should add the images of the additional class to that same dataset and train again. The pre trained weights help you to increase the speed of training. This is just my opinion you should still wait for glenn to reply as he knows better. Hope this helps!!

**Comment by glenn-jocher** [comment]
@ygkrishna @aryan51k you must train on **all** classes you want to detect. Pretrained models gradually forget everything learned in the past as the full model is focus on minimizing loss on the current dataset. There is no such thing as learning new things while not forgetting old things, this concept does not exist. See  https://en.wikipedia.org/wiki/Catastrophic_interference

If you have dataset A and B then you can train on both if they have complementary class indices, i.e. if you want to train on COCO and a custom 5 class dataset you label your custom data with class indices 80-84 (COCO is 0-79) and combine your custom data with the COCO data in one yaml.

See GlobalWheat2020.yaml for an example of training multiple datasets/directories together:
https://github.com/ultralytics/yolov5/blob/d5966c93f1855baec531c3585da247cded72247f/data/GlobalWheat2020.yaml#L10-L27

**Comment by Pankaj901** [comment]
in continuity with this thread, I have one question. let's consider I have a dataset (500) with 5 classes and now I added another 300 data with 10 classes. (500[5] +300[10]). also, the new 5 class is present in some of the old datasets (500) but not labeled. so if I train the whole dataset now how my accuracy will be impacted?? and what will be the possible solution?

**Comment by glenn-jocher** [comment]
@Pankaj901 see https://community.ultralytics.com/t/how-to-combine-weights-to-detect-from-multiple-datasets
