### ISSUE TITLE
Suggestion about mAP

### ISSUE THREAD

**Issue by logic03** [ultralytics/yolov5#642]
Can you also write the mAP test results for large, medium and small objects when the IOU is set to 0.5, just like coco evaluation index? I think it's easier to see how YOLOV5 behaves on different scales.

**Comment by glenn-jocher** [comment]
@logic03 if you'd like to implement this as a PR we can take a look there. This should go under test.py --verbose mode, which also outputs metrics by class (which pycocotools does not offer).
