### ISSUE TITLE
Get an error for --source when i give as a path a variable

### ISSUE THREAD

**Issue by Thanossrs** [ultralytics/yolov5#6420]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How could give the path of an image/video in --source as a variable and NOT like './folder/image1.jpg'??

Thanks

### Additional

![Inkedimage_2022_01_25T00_10_34_523Z_LI](https://user-images.githubusercontent.com/61714623/150957972-58a846b4-2c9a-470f-934e-e17de075dc88.jpg)

**Comment by glenn-jocher** [comment]
@Thanossrs use brackets, i.e.

```python
# VOC
for b, m in zip([64, 64, 32, 16], ['yolov5s', 'yolov5m', 'yolov5l', 'yolov5x']):  # zip(batch_size, model)
  !python train.py --batch {b} --weights {m}.pt --data VOC.yaml --epochs 50 --cache --img 512 --nosave --hyp hyp.finetune.yaml --project VOC --name {m}
```

**Comment by Thanossrs** [comment]
Thank you @glenn-jocher!!! Problem Solved!!!!

**Comment by dhirusha** [comment]
how could you solve the problem

**Comment by glenn-jocher** [comment]
@dhirusha you're welcome! The solution is to use curly braces `{}` to specify the path as a variable in the `--source` parameter. This effectively allows you to use a variable instead of a hard-coded path. Thanks for reaching out!
