### ISSUE TITLE
How to convert the YOLOV5-V3 weights to YOLOV5-V5? 

### ISSUE THREAD

**Issue by adrianosantospb** [ultralytics/yolov5#6426]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, guys. 

Anyone here already converted (or something like this) weights trained from the YOLOV5 V3 to YOLOV5 V5. Is it possible?

Thanks

**Comment by glenn-jocher** [comment]
@adrianosantospb there's no update methods officially implemented. 

I would train new models with current master code for best results.

**Comment by adrianosantospb** [comment]
Hi, @glenn-jocher ... tks a lot for your answer. Well... it's interesting, but I'm getting better results using the old version.

**Comment by shubhambaid** [comment]
Any luck yet @adrianosantospb ??
