### ISSUE TITLE
Yolov5 image detection without segmentation?

### ISSUE THREAD

**Issue by WJos** [ultralytics/yolov5#6429]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have read a number of papers on Yolov5 images detection techniques. But the papers don't refers to any segmentation step done by Yolov5. While I know that it is not possible to do image classification without a segmentation process, I am asking the following question: do Yolov5 do any segmentation step in order to detect images? If yes which segmentation algorithm does it use?

**Comment by glenn-jocher** [comment]
@WJos YOLOv5 is an object detection algorithm, it does not do segmentation.

<img width="2163" alt="Screenshot 2021-11-22 at 18 26 43" src="https://user-images.githubusercontent.com/26833433/151647790-2a9fe07a-8916-4a5d-82de-7b5b07f219d4.png">
