### ISSUE TITLE
How to control video detect fps？

### ISSUE THREAD

**Issue by Zeqing-Wang** [ultralytics/yolov5#6433]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

For example, i need to detect a video just one time in a second，what should i do?
Thanks!

### Additional

I have tried to add a timer in detect.py, but it does not work.

**Comment by glenn-jocher** [comment]
@naptm you can skip frames here on the videoloader:
https://github.com/ultralytics/yolov5/blob/d5966c93f1855baec531c3585da247cded72247f/utils/datasets.py#L199-L212

**Comment by Zeqing-Wang** [comment]
Useful advice, i have done it in this way.
Thanks a lot!
