### ISSUE TITLE
Validation with val.py using torchscript fails

### ISSUE THREAD

**Issue by FriedhelmHamann** [ultralytics/yolov5#6445]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Validation

### Bug

Minimal example to reproduce the error:
1. Export model as torchscript

`python export.py --weights yolov5s.pt --include torchscript`

2. Run validation with

`python val.py --weights yolov5s.torchscript`

Step 2 results in the error:

Traceback (most recent call last):
  File "val.py", line 384, in <module>
    main(opt)
  File "val.py", line 357, in main
    run(**vars(opt))
  File "/home/.../yolov5/env/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "val.py", line 165, in run
    model.warmup(imgsz=(1, 3, imgsz, imgsz), half=half)  # warmup
  File "/home/.../yolov5/models/common.py", line 462, in warmup
    self.forward(im)  # warmup
  File "/home/.../yolov5/models/common.py", line 399, in forward
    y = self.model(im) if self.jit else self.model(im, augment=augment, visualize=visualize)
  File "/home/.../yolov5/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/models/yolo.py", line 59, in forward
    model23 = self.model
    _0 = getattr(model23, "0")
    _25 = (_2).forward((_1).forward((_0).forward(x, ), ), )
                                     ~~~~~~~~~~~ <--- HERE
    _26 = (_4).forward((_3).forward(_25, ), )
    _27 = (_6).forward((_5).forward(_26, ), )
  File "code/__torch__/models/common.py", line 12, in forward
    act = self.act
    conv = self.conv
    _0 = (act).forward((conv).forward(x, ), )
                        ~~~~~~~~~~~~~ <--- HERE
    return _0
class C3(Module):
  File "code/__torch__/torch/nn/modules/conv.py", line 12, in forward
    bias = self.bias
    weight = self.weight
    x0 = torch._convolution(x, weight, bias, [2, 2], [2, 2], [1, 1], False, [0, 0], 1, False, False, True, True)
         ~~~~~~~~~~~~~~~~~~ <--- HERE
    return x0

Traceback of TorchScript, original code (most recent call last):
/home/.../yolov5/env/lib/python3.8/site-packages/torch/nn/modules/conv.py(442): _conv_forward
/home/.../yolov5/env/lib/python3.8/site-packages/torch/nn/modules/conv.py(446): forward
/home/.../yolov5/env/lib/python3.8/site-packages/torch/nn/modules/module.py(1090): _slow_forward
/home/.../yolov5/env/lib/python3.8/site-packages/torch/nn/modules/module.py(1102): _call_impl
/home/.../yolov5/models/common.py(50): forward_fuse
/home/.../yolov5/env/lib/python3.8/site-packages/torch/nn/modules/module.py(1090): _slow_forward
/home/.../yolov5/env/lib/python3.8/site-packages/torch/nn/modules/module.py(1102): _call_impl
/home/.../yolov5/models/yolo.py(149): _forward_once
/home/.../yolov5/models/yolo.py(126): forward
/home/.../yolov5/env/lib/python3.8/site-packages/torch/nn/modules/module.py(1090): _slow_forward
/home/.../yolov5/env/lib/python3.8/site-packages/torch/nn/modules/module.py(1102): _call_impl
/home/.../yolov5/env/lib/python3.8/site-packages/torch/jit/_trace.py(958): trace_module
/home/.../yolov5/env/lib/python3.8/site-packages/torch/jit/_trace.py(741): trace
export.py(76): export_torchscript
export.py(440): run
/home/.../yolov5/env/lib/python3.8/site-packages/torch/autograd/grad_mode.py(28): decorate_context
export.py(512): main
export.py(517): <module>
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

### Environment

- YOLOv5 🚀 v6.0-215-gfe7de6a torch 1.10.1+cu113 CUDA:0 (NVIDIA GeForce RTX 3070, 7974MiB)
- Ubuntu 20.04
- Python 3.8.10

### Minimal Reproducible Example

1. Export model as torchscript

`python export.py --weights yolov5s.pt --include torchscript`

2. Run validation with

`python val.py --weights yolov5s.torchscript`

### Additional

_No response_

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@friedhelm-h 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀.

export.py defaults to --device cpu since not all export formats support GPU.

detect.py defaults to --device 0 if available for fastest inference.

In a multi-device environment you should export and detect on the same device for best results, i.e.
```bash
python export.py --device cpu
python detect.py --device cpu
# or
python export.py --device 0
python detect.py --device 0
```

**Comment by FriedhelmHamann** [comment]
Thank you for the quick reply! Running both scripts with the same device flag solved the issue.
