### ISSUE TITLE
About weights

### ISSUE THREAD

**Issue by iscyy** [ultralytics/yolov5#6446]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

May I ask if there are model pre-training weights in the configuration file in ./models/hub/*? If so, where can I find it, thank you

**Comment by violet2422** [comment]
😁I also want to get the pretrained weights for the configuration files like hub/models/*.yaml. _eg:hub/models/yolov5s-ghost.yaml_
If so, where can I find it, thank you！！！

**Comment by glenn-jocher** [comment]
@Him-wen @violet2422 all available pretrained weights are located in the latest release Assets setion:
https://github.com/ultralytics/yolov5/releases/tag/v6.0

**Comment by glenn-jocher** [comment]
@Him-wen @violet2422 all available pretrained weights are located in the latest release Assets section:
https://github.com/ultralytics/yolov5/releases/tag/v6.0
<img width="1358" alt="Screenshot 2022-01-28 at 06 55 17" src="https://user-images.githubusercontent.com/26833433/151494894-9b51876c-a6e6-4582-96d2-dfddeea0e4d8.png">
