### ISSUE TITLE
About Mixup and Mosaic

### ISSUE THREAD

**Issue by YinengXiong** [ultralytics/yolov5#6447]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

in `dataset.py`  there is:
```Python
if mosaic:
    # Load mosaic
    img, labels = load_mosaic(self, index)
    shapes = None

    # MixUp augmentation
    if random.random() < hyp['mixup']:
        img, labels = mixup(img, labels, *load_mosaic(self, random.randint(0, self.n - 1)))
```
Can I use mixup while don't use mosaic when training?

**Comment by ChinaRush** [comment]
mosaic is a hyperarameter in hyp.yaml  , you can set mosaic to zero

**Comment by YinengXiong** [comment]
> mosaic is a hyperarameter in hyp.yaml , you can set mosaic to zero

It seems that if set mosaic to 0, the data augmentation will not run mixup

**Comment by glenn-jocher** [comment]
@YinengXiong mosaic is recommended for all trainings.

**Comment by tejasri19** [comment]
Is mosaic and mixup included in all variants of yolo now? 
Or do we have to define dataloader on custom dataset? @glenn-jocher
