### ISSUE TITLE
Sudden problems about device 

### ISSUE THREAD

**Issue by b860306** [ultralytics/yolov5#6448]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

It has been used normally for a long time, and today this problem suddenly appeared 。
-------------------------------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "C:\Users\Administrator/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 43, in _create
    device = select_device(('0' if torch.cuda.is_available() else 'cpu') if device is None else device)
  File "C:\Users\Administrator/.cache\torch\hub\ultralytics_yolov5_master\utils\torch_utils.py", line 74, in select_device
    assert nd > int(max(device.split(','))), f'Invalid `--device {device}` request, valid devices are 0 - {nd - 1}'
AssertionError: Invalid `--device 0` request, valid devices are 0 - -1

### Additional

none

**Comment by RossLeeThomas** [comment]
Same error my side. Also running on Windows.
Been running for a few months, only stopped working on the latest pull. If I revert back to an older repo it works again.
Seems to be related to the recent GPU selection fixes on Windows?

Traceback (most recent call last):
  File "c:\Gitlab\yolov5\hubconf.py", line 43, in _create
    device = select_device(('0' if torch.cuda.is_available() else 'cpu') if device is None else device)
  File "c:\Gitlab\yolov5\utils\torch_utils.py", line 74, in select_device
    assert nd > int(max(device.split(','))), f'Invalid `--device {device}` request, valid devices are 0 - {nd - 1}'
AssertionError: Invalid `--device 0` request, valid devices are 0 - -1

**Comment by b860306** [comment]
> Same error my side. Also running on Windows. Been running for a few months, only stopped working on the latest pull. If I revert back to an older repo it works again. Seems to be related to the recent GPU selection fixes on Windows?
> 
> Traceback (most recent call last): File "c:\Gitlab\yolov5\hubconf.py", line 43, in _create device = select_device(('0' if torch.cuda.is_available() else 'cpu') if device is None else device) File "c:\Gitlab\yolov5\utils\torch_utils.py", line 74, in select_device assert nd > int(max(device.split(','))), f'Invalid `--device {device}` request, valid devices are 0 - {nd - 1}' AssertionError: Invalid `--device 0` request, valid devices are 0 - -1

Sorry ,  can i ask you how to revert back to an older repo?

**Comment by RossLeeThomas** [comment]
I changed to another branch on git updated 21 hours ago 'updates/benchmarks'.

**Comment by RossLeeThomas** [comment]
Reverting this commit (https://github.com/ultralytics/yolov5/commit/856d4e5733451c7fe9b12f183b384e986699b1f8) also fixes the issue for me.

**Comment by b860306** [comment]
I followed the steps ([856d4e5](https://github.com/ultralytics/yolov5/commit/856d4e5733451c7fe9b12f183b384e986699b1f8))
Both profiles( torch_utils.py /   datasets.py  )  were updated .

But it's still the same problem

**Comment by b860306** [comment]
> 
I followed the steps ([856d4e5](https://github.com/ultralytics/yolov5/commit/856d4e5733451c7fe9b12f183b384e986699b1f8))
Both profiles( torch_utils.py /   datasets.py  )  were updated .

But it's still the same problem

**Comment by b860306** [comment]
> Reverting this commit ([856d4e5](https://github.com/ultralytics/yolov5/commit/856d4e5733451c7fe9b12f183b384e986699b1f8)) also fixes the issue for me.

I followed the steps ([856d4e5](https://github.com/ultralytics/yolov5/commit/856d4e5733451c7fe9b12f183b384e986699b1f8))
Both profiles( torch_utils.py /   datasets.py  )  were updated .

But it's still the same problem

**Comment by RossLeeThomas** [comment]
created a fork you can try download, same as master branch just with the last commit reverted. https://github.com/RossLeeThomas/yolov5.git

**Comment by b860306** [comment]
> 創建了一個分支，您可以嘗試下載，與主分支相同，只是還原了最後一次提交。 [https://github.com/RossLeeThomas/yolov5.git ](https://github.com/RossLeeThomas/yolov5.git)

Oh ! it works again.
You've saved my life.

**Comment by StevenLi-phoenix** [comment]
Have the same issue with jetson

**Comment by glenn-jocher** [comment]
Sorry guys, it looks like a recent PR https://github.com/ultralytics/yolov5/pull/6434 broke Windows GPU compatibility. I'll work on a fix ASAP.

**Comment by glenn-jocher** [comment]
In the meantime you can checkout the previous commit easily with this code:
```bash
git clone https://github.com/ultralytics/yolov5
cd yolov5
git checkout fe7de6a82da3444d755453f86f40b508f3b99419
```

**Comment by b860306** [comment]
> 

Thanks !

**Comment by StevenLi-phoenix** [comment]
> Sorry guys, it looks like a recent PR #6434 broke Windows GPU compatibility. I'll work on a fix ASAP.

It does not work with jetson tx2 too.

<img width="602" alt="截屏2022-01-28 下午2 35 31" src="https://user-images.githubusercontent.com/75846119/151499250-09fea086-f291-4bd1-b255-3741907e1402.png">

without the option of device It works fine.
But as soon as I select device 0. It became out of range.
how can I select device between 0 and -1. It's impossible.

**Comment by glenn-jocher** [comment]
@b860306 @RossLeeThomas @StevenLi-phoenix good news 😃! Your original issue may now be fixed ✅ in PR #6461. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by RossLeeThomas** [comment]
Working for me. Thanks @glenn-jocher

**Comment by glenn-jocher** [comment]
@RossLeeThomas great! Thanks for the feedback.

**Comment by Gowtham-369** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.
> 
> ### Question
> ## It has been used normally for a long time, and today this problem suddenly appeared 。
> Traceback (most recent call last): File "C:\Users\Administrator/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 43, in _create device = select_device(('0' if torch.cuda.is_available() else 'cpu') if device is None else device) File "C:\Users\Administrator/.cache\torch\hub\ultralytics_yolov5_master\utils\torch_utils.py", line 74, in select_device assert nd > int(max(device.split(','))), f'Invalid `--device {device}` request, valid devices are 0 - {nd - 1}' AssertionError: Invalid `--device 0` request, valid devices are 0 - -1
> 
> ### Additional
> none

Same error I faced today while hosting using flask. Tried all the available suggestions but no solution found
`
Traceback (most recent call last):
  File "/home/ugrdsa/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 43, in _create
    device = select_device(('0' if torch.cuda.is_available() else 'cpu') if device is None else device)
  File "/home/ugrdsa/.cache/torch/hub/ultralytics_yolov5_master/utils/torch_utils.py", line 79, in select_device
    LOGGER.info(s.encode().decode('ascii', 'ignore') if platform.system() == 'Windows' else s)  # emoji-safe
  File "/usr/lib/python3.8/logging/__init__.py", line 1434, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1577, in _log
    self.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1587, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1649, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
`

**Comment by glenn-jocher** [comment]
@Gowtham-369 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
