### ISSUE TITLE
Error when saving period and parameters

### ISSUE THREAD

**Issue by Juanjojr9** [ultralytics/yolov5#6452]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I have searched but have not found a similar question.

I was training a long model, and just in case there was a problem, I set the -save_period parameter, , as you can see in the following picture:

![image](https://user-images.githubusercontent.com/56088039/151265816-37ed59f9-e30b-422f-8043-87404b36a457.png)

I had a problem and wanted to resume blocked execution, since my google colab session expired and I lost all my session data. , but it gave me another problem.

![image](https://user-images.githubusercontent.com/56088039/151265853-ac3d32e5-ff55-481f-84f4-ed55e7712cf4.png)

When I compared it with this tutorial I found: https://colab.research.google.com/github/wandb/examples/blob/master/colabs/yolo/Train_and_Debug_YOLOv5_Models_with_Weights_%26_Biases.ipynb#scrollTo=jwcBfF5OvAHk

In his training it saves the data every epoch and in mine it should do it every 5 epochs, but it doesn't do anything: 

![image](https://user-images.githubusercontent.com/56088039/151266292-53a13554-f5c1-4dc5-a1fd-eba4af5c75d2.png)

![image](https://user-images.githubusercontent.com/56088039/151266378-472dbf70-02c8-473f-bfc7-46c90be0ff9c.png)

It's a real bummer, as the model had been training for several hours.

Does anyone know how to fix this or how can I save the model and the parameters in case I get an error again? Any help is good.

I also wanted to ask if it is possible to download the data locally into a folder instead of using the Weights and Biases website.

Thank you very much for your help.

JJ

**Comment by AyushExel** [comment]
@Juanjojr9 Hey, the command seems correct. can you check the run that you want to resume and see if the artifact is present there? You can even share the run link here and I'll look into this

**Comment by Juanjojr9** [comment]
Hello! First of all, thank you very much for helping me.

If you can tell me how I can verify it, I will try to do it or which is the link you are referring to, I will pass it on without any problem.

![image](https://user-images.githubusercontent.com/56088039/151365745-ceb5c72e-276c-4d56-9767-1031e7bef89f.png)

**Comment by AyushExel** [comment]
@Juanjojr9 in your command, you have `-save-period` set to 10, which means the model will only be saved after 10 epochs. If you click on artifacts or see the charts you'll notice that the experiment didn't run 10 epochs that's why the model is not logged. I suggest reducing the save period

**Comment by Juanjojr9** [comment]
Hi @AyushExel , thank you for your answer

I think I got the wrong example earlier. Anyway, I did a quick test and now it does save, as you can see in the image below:

![image](https://user-images.githubusercontent.com/56088039/151424735-d30ef0a6-74fe-490d-b415-05eeee07a6c9.png)

I cancelled the run to simulate a problem. At first, I thought it was going to work, but it gave me a problem.

![image](https://user-images.githubusercontent.com/56088039/151425414-8f5ee186-8e59-44f5-a65c-5a681d6cfa89.png)

Analysing it, I realised that it changes the parameters I had set before:

![image](https://user-images.githubusercontent.com/56088039/151426689-19b78a2e-6c4a-40f2-8fa4-575c67284530.png)

My question is: when I run !python train.py --resume wandb-artifact://{crashed_run_path} ,I also have to set the above parameters?

Is there another way to save the data locally without losing the information in case the google colab session expires?

Thank you

**Comment by AyushExel** [comment]
@Juanjojr9 your syntax is correct. The problem that you're seeing in the pic above is that you're running out of CUDA memory. Read the last line of the error message.
The same syntax should work on colab or your own system if there is sufficient CUDA memory

**Comment by Juanjojr9** [comment]
@AyushExel I have not explained myself well

El problema por el que se está quedando sin memoria CUDA is that the parameters are being changed.
The batch size, I have it set to 1. But when I run --resume wandb-artifact://{{crashed_run_path}, it changes the batch size and is set to 16.
You can check it by looking at the pictures. Otherwise, I would not have been able to run it the first time.
And besides the batch size, other parameters such as the epochs, imgzs, etc. change as well.

My question is whether I should run the command by setting the parameters as well, i.e. as follows:
![image](https://user-images.githubusercontent.com/56088039/151660530-e6757b0f-50a6-4b1d-abc3-0979c6b5a2c2.png)

If not, I don't understand why it changes the parameters I set when I train the network,  when trying to resume the network run

![image](https://user-images.githubusercontent.com/56088039/151660824-11569b49-f11c-4aaa-9165-a10eef27aed4.png)

**Comment by AyushExel** [comment]
@Juanjojr9 okay understood. This should not happen. I'll fix this coming week. Thanks for reporting

**Comment by Juanjojr9** [comment]
I don't know if it's my problem. I will try to keep doing different tests.

Thanks to you for creating this incredible and majestic tool. 
I am delighted to be learning about this issue

Yours faithfully,
Juanjo

**Comment by AyushExel** [comment]
@Juanjojr9 I've pushed a PR with the fix for this

**Comment by Juanjojr9** [comment]
@AyushExel Thank you very much for the help and the quick solution. I look forward to using it when it is ready

Best regards.

JJ

**Comment by glenn-jocher** [comment]
@Juanjojr9 good news 😃! Your original issue may now be fixed ✅ in PR #6452 by @AyushExel. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by AyushExel** [comment]
@Juanjojr9 Your problem should be fixed in the latest release now the resume command will remember the batch size.. Please verify.. Thanks!

**Comment by Juanjojr9** [comment]
@AyushExel Hi !

I have been doing different tests and I don't think it's working properly yet. Maybe, I could be wrong.
Below, I show you the evidence:

These are my parameters:

![image](https://user-images.githubusercontent.com/56088039/152344603-88fce590-15d3-46c4-886a-d399f26c425e.png)

![image](https://user-images.githubusercontent.com/56088039/152347238-a2bac1bc-8596-46f6-a540-9dfe4808d963.png)

I interrupted the training and then resumed it.

![image](https://user-images.githubusercontent.com/56088039/152344907-02793406-3e2a-40a3-bb25-b37b11dc5a6e.png)

At first I thought it works well, as it starts at the right epoch. But there are some things that don't seem logical to me:

![errores](https://user-images.githubusercontent.com/56088039/152347866-fafe18ef-a0a7-49fe-8a28-ac0943174485.png)


- Marked in pink: the parameters displayed are not correct.
- Marked in red: the size of the images is not correct.
- Marked in blue: The gpu_mem and the run time are totally different.
- Marked in green: a new directory is created. If you look at the opt.yaml files, they don't match at all.

![image](https://user-images.githubusercontent.com/56088039/152349317-a87baeea-cab4-4565-83d3-facc4a297b9c.png)

![image](https://user-images.githubusercontent.com/56088039/152349583-33321eb5-741a-4823-9812-f48d10f2f332.png)


Therefore, the parameters still do not match.

I don't know if I'm wrong.

**Comment by AyushExel** [comment]
@Juanjojr9 You might be right about the image size as we're not restoring that.. But can you please check the batch size from your wandb run config? it should be in the overview tab of your wandb run.. The batch size should match before and after resume

**Comment by Juanjojr9** [comment]
@AyushExel  I'm trying to check the batch size after restarting, but I don't know where to see it.
Can you tell me the steps to see it?

![image](https://user-images.githubusercontent.com/56088039/152392712-dbd2315e-5937-44b4-8527-8f9fea9029ee.png)

**Comment by AyushExel** [comment]
@Juanjojr9 You're on the right screen. Just scroll down a bit further

<img width="760" alt="Screenshot 2022-02-03 at 11 02 39 PM" src="https://user-images.githubusercontent.com/15766192/152396975-b8735491-3878-4df6-82d9-04dc48ca1a20.png">

**Comment by Juanjojr9** [comment]
@AyushExel  But how do I know if that is the setting before cancelling or after resume?

You can see the following:

![image](https://user-images.githubusercontent.com/56088039/152401572-68c8d2a5-6454-4f50-8974-8bd26b3e9ce0.png)


But, you can see this, among other things, that the --imgsz parameter is set to 1280 and --resume is false. Therefore, I believe these configuration parameters are before interrupting the run.

They are not the parameters after resuming.

![image](https://user-images.githubusercontent.com/56088039/152402618-9896918a-5936-4e12-8566-5e471c360b59.png)

![image](https://user-images.githubusercontent.com/56088039/152402753-ff863ec2-5637-4253-a304-f14dbff2a1d0.png)


What is your opinion?

**Comment by AyushExel** [comment]
I think the batch size is being restored but not the img size..You can still pass those params with the resume flag..
The resume isn't perfect, like you pointed out with the batch size, probably we can do a better job at remembering other hyperparameters.

**Comment by Juanjojr9** [comment]
@AyushExel In case you were right, in the images of the parameter settings, besides setting the batch size to 1, the imgz parameter should be 640 and not 1280, as the size of the images is not supposed to be saved. With other parameters it would be the same


From my humble point of view, I think it doesn't save the parameters properly. As you can see in the screenshots above, when it resumes it creates a new opt.yaml file and you can see what parameters are set and they have nothing to do with the ones you set before.

But in case the batch size is saved correctly, it would not be of much use as the other parameters have changed and your original model has not been resumed. Therefore the results would be false and erroneous.

**Comment by AyushExel** [comment]
@Juanjojr9 I think this requires a deeper look. If you look at the PR linked above, you'll see that the hyp dict, batch size and epochs are restored from the run. So if that's not showing up in the experiment, probably it's being overwritten somewhere. I'll take a deeper look again because the cause of the problem seems to be located somewhere else

**Comment by Juanjojr9** [comment]
@AyushExel Ok, thank you very much for your help. I will be waiting for your answer, as it is a very interesting tool.

I also wanted to tell you that the wandb.login() command has been giving me problems in google colab for several days. I don't know if it's my fault. I will keep looking for information.

Thank you again

**Comment by AyushExel** [comment]
@Juanjojr9 thanks for reporting. I'll be working on to verify the resume issue this week again.
What is the issue with wandb.login?

**Comment by Juanjojr9** [comment]
@AyushExel When I run the command, it is as if it is not able to start the session, as it takes too long to think and this causes the gogole colab session to crash and restart.
But even so, I'll keep testing just in case I'm wrong.

**Comment by AyushExel** [comment]
@Juanjojr9 Okay I investigated the resume further. The batch size was being remembered but image size wasn't.. I've made a PR to remember that.. Currently, here are the params that are remembered when resuming.
```opt.weights, opt.save_period, opt.batch_size, opt.bbox_interval, opt.epochs, opt.hyp, opt.imgsz```

If there are any more things that need to be remembered please let me know

**Comment by glenn-jocher** [comment]
@Juanjojr9 good news 😃! Your original issue may now be fixed ✅ in PR #6611 by @AyushExel. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by Juanjojr9** [comment]
@AyushExel Thank you very much for the help. I'll try it out and see how it works.

Best regards.

JJ
