### ISSUE TITLE
fps

### ISSUE THREAD

**Issue by seungyong0313** [ultralytics/yolov5#6454]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I detected the .mp file with yolov5n. How can I check the fps? Can you tell me how to check fps from top of screen or cmd

**Comment by UygarUsta99** [comment]
When you are inferencing via detect.py you will see inference time on your terminal like (0.198s) .You can then use  1/inference time to calculate fps.Note that 1 here is the number of frames you are processing and may change depending on how many frames you are processing at inference time although it is usually 1.
