### ISSUE TITLE
Large dataset and really long training time per epoch in Google Colab

### ISSUE THREAD

**Issue by bszymik** [ultralytics/yolov5#6457]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, first of all kudos for all astonishing work that you are doing.

I'm trying to run a training on data as below:

classes: 647
instances per class: 5000 (for some 3000) objects
train images: about 190k
val images: 90k (when I was running a test trainings using 6 classes and a 1000 instances per class I found that about 70% of train images to 30% of val images worked best for me)
images size in dataset: 800x800 px
total files size about 16 GB

I tried running that in Google Colab (PRO) like below:

`!python train.py --img 800 --batch 16 --epochs 300 --data /content/sample_data/data.yaml --weights yolov5m.pt`

But after all night it went through only 1 epoch and was in a middle of next one

All the data are copied on Collabs local drive
I've tried --cache param but of course I run out of ram at something like 6% of cached data, I've tried --cache disk - but I run out of disk space quickly

I've tried to reduce params like --img to 640 and --batch to 2 - but the training time isn't reduced much (right now I'm running first epoch and it's running for 50 minutes with speed 5.5it/s but it's only 17% so far)

So is that training speed/time normal on Colab PRO and it is as it is? 
Is there any way to get it faster or I just need to reduce the images number?

Or maybe better compression will make it to fit in ram cache? (or it doesn't matter since it pixel in memory will always have same size?)

**Comment by glenn-jocher** [comment]
@bszymik colab is really just meant for small datasets.

For enterprise scale applications you should definitely use AWS or GCP cloud instances.

**Comment by iceisfun** [comment]
If your training larger datasets (>1m samples) you might consider local training if you have the resources, I train on a 3x RTX Titan machine often with datasets of this size and with the amount of time I spend training it has been a good investment.

And if your locally training, storing your input dataset on a SSD is a good idea, much less of a cost than a local GPU.

**Comment by glenn-jocher** [comment]
@bszymik @iceisfun my main guideline here is that if you can --cache your dataset into high-RAM Colab instances then you're all good and your training will be very fast. For example a VOC epoch takes only about 1 minute on Colab++ when with --cache.

<img width="1113" alt="Screenshot 2022-01-30 at 18 28 55" src="https://user-images.githubusercontent.com/26833433/151710320-f2995907-ba90-4218-b698-ad04b9c2abee.png">

If you can't --cache your dataset Colab and Colab+ will be very slow as you're limited to 2 dataloader workers, and even on Colab++ with more workers you are still limited to a slow HDD on the backend, so this is the point where you spin up a GCP/AWS cloud instance with SSD or invest in your own hardware.

**Comment by bszymik** [comment]
@glenn-jocher thanks for all the tips, actually it is not an enterprise project - it is more a hobby project for now (but with potential to become something bigger) - anyway the amount of data might seem as some enterprise data, because I'm rendering synthetic images, and to close sim2real gap I've rendered that much of a data, but I have a lot of control on a shape of those data (I can pack more instances of classes into less number of background images etc.) - so Google Colab+ (or even ++) is a best place to start for me as I don't need to pay thousands $ for VM etc. 

so about caching the data into ram - what is approximate size of needed ram when loading e.g. 1GB of images? Is there some way of estimating it like if it depends on image format or it doesn't matter if it's jpg or png because 1px is always 1 byte in memory or something? Any hint what to expect in case of RAM consumption?

And thanks again for all you help and great job you are doing - I really appreciate that

**Comment by glenn-jocher** [comment]
@bszymik memory usage scales with the square of the --imgsz and number of images. Format does not matter.

**Comment by bszymik** [comment]
ok so I did some tests (all in Google Colab PRO using GPU and high RAM) - I've reduced my dataset so it could fit in RAM cache, also I've did some tests with dataset that wasn't fitting in ram cache - but with mounting a ramdisk and coping the data into ramdisk (as it remains uncompressed), and also did similar run with dataset copied to regular local drive of google colab pro

Surprisingly all the results in case of training speed per epoch was very similar - speed/time differences were marginal which was quite surprising, so to test that I run 2 tests on GlobalWheat2020.yaml dataset using below commands:

`train.py --img 800 --batch 16 --epochs 50 --weights yolov5m.pt --data GlobalWheat2020.yaml --cache`

and

`train.py --img 800 --batch 16 --epochs 50 --weights yolov5m.pt --data GlobalWheat2020.yaml`

in both cases training speed was almost the same, (logs are below)
training time in both cases was about 04:30 per epoch and 1.26s/it

so am I doing something wrong or I misunderstood --cache param? I thought that caching data in a RAM would speed up training time significantly, but it's almost the same

for ram cache:
```
Epoch   gpu_mem       box       obj       cls    labels  img_size
      0/49      9.9G    0.0783    0.3002         0       924       800: 100% 214/214 [04:35<00:00,  1.29s/it]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100% 24/24 [00:20<00:00,  1.17it/s]
                 all        747      49603      0.423      0.729       0.48      0.156
     Epoch   gpu_mem       box       obj       cls    labels  img_size
      1/49     10.4G   0.05678    0.2785         0       711       800: 100% 214/214 [04:30<00:00,  1.26s/it]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100% 24/24 [00:18<00:00,  1.31it/s]
                 all        747      49603      0.624      0.809      0.757       0.23
     Epoch   gpu_mem       box       obj       cls    labels  img_size
      2/49     10.4G   0.05211    0.2808         0       852       800: 100% 214/214 [04:29<00:00,  1.26s/it]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100% 24/24 [00:17<00:00,  1.34it/s]
                 all        747      49603      0.902      0.886      0.941        0.5
     Epoch   gpu_mem       box       obj       cls    labels  img_size
      3/49     10.4G    0.0468    0.2718         0       814       800: 100% 214/214 [04:29<00:00,  1.26s/it]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100% 24/24 [00:19<00:00,  1.24it/s]
                 all        747      49603       0.86      0.846      0.914      0.413
     Epoch   gpu_mem       box       obj       cls    labels  img_size
      4/49     10.4G   0.05406    0.3495         0       764       800: 100% 214/214 [04:29<00:00,  1.26s/it]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100% 24/24 [00:24<00:00,  1.01s/it]
                 all        747      49603      0.855      0.794      0.853      0.411
     Epoch   gpu_mem       box       obj       cls    labels  img_size
      5/49     10.4G   0.04824    0.3122         0       611       800: 100% 214/214 [04:28<00:00,  1.26s/it]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100% 24/24 [00:19<00:00,  1.24it/s]
                 all        747      49603      0.922      0.904      0.952      0.548
     Epoch   gpu_mem       box       obj       cls    labels  img_size
      6/49     10.4G    0.0441    0.2906         0       866       800: 100% 214/214 [04:28<00:00,  1.26s/it]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100% 24/24 [00:18<00:00,  1.33it/s]
                 all        747      49603      0.941      0.899      0.959      0.549
     Epoch   gpu_mem       box       obj       cls    labels  img_size
      7/49     10.4G   0.04263    0.2794         0       604       800: 100% 214/214 [04:28<00:00,  1.26s/it]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100% 24/24 [00:17<00:00,  1.34it/s]
                 all        747      49603      0.944      0.919      0.966      0.561
```

and no cache:

```
Epoch   gpu_mem       box       obj       cls    labels  img_size
      1/49     10.4G   0.05645    0.2785         0       711       800: 100% 214/214 [04:30<00:00,  1.26s/it]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100% 24/24 [00:18<00:00,  1.33it/s]
                 all        747      49603      0.867      0.869      0.915      0.454
     Epoch   gpu_mem       box       obj       cls    labels  img_size
      2/49     10.4G   0.05252    0.2881         0       852       800: 100% 214/214 [04:29<00:00,  1.26s/it]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100% 24/24 [00:18<00:00,  1.31it/s]
                 all        747      49603      0.929      0.898       0.95      0.488
     Epoch   gpu_mem       box       obj       cls    labels  img_size
      3/49     10.4G   0.04707     0.272         0       814       800: 100% 214/214 [04:29<00:00,  1.26s/it]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100% 24/24 [00:19<00:00,  1.25it/s]
                 all        747      49603      0.917      0.905      0.947      0.505
     Epoch   gpu_mem       box       obj       cls    labels  img_size
      4/49     10.4G   0.04676    0.2783         0       764       800: 100% 214/214 [04:29<00:00,  1.26s/it]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100% 24/24 [00:23<00:00,  1.03it/s]
                 all        747      49603      0.924      0.886      0.942      0.514
     Epoch   gpu_mem       box       obj       cls    labels  img_size
      5/49     10.4G   0.04283    0.2746         0       611       800: 100% 214/214 [04:29<00:00,  1.26s/it]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100% 24/24 [00:18<00:00,  1.32it/s]
                 all        747      49603      0.945      0.931      0.971      0.586
     Epoch   gpu_mem       box       obj       cls    labels  img_size
      6/49     10.4G     0.041     0.267         0       866       800: 100% 214/214 [04:29<00:00,  1.26s/it]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100% 24/24 [00:17<00:00,  1.34it/s]
                 all        747      49603       0.95       0.93      0.972      0.588
     Epoch   gpu_mem       box       obj       cls    labels  img_size
      7/49     10.4G   0.03999    0.2609         0       604       800: 100% 214/214 [04:29<00:00,  1.26s/it]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100% 24/24 [00:17<00:00,  1.35it/s]
                 all        747      49603      0.956      0.928      0.973      0.598
```

**Comment by glenn-jocher** [comment]
@bszymik --cache speeds up GlobalWheat2020 training for me. From about 80s/epoch to 20s/epoch. 

### default
<img width="1531" alt="Screenshot 2022-02-09 at 13 53 41" src="https://user-images.githubusercontent.com/26833433/153205427-823c9db1-a5c4-49f2-9ba6-a7afe0f6baf1.png">

### --cache
<img width="1531" alt="Screenshot 2022-02-09 at 13 53 51" src="https://user-images.githubusercontent.com/26833433/153205452-bf6ca2e7-24c2-46dd-8d6d-f23b506fe815.png">

**Comment by bszymik** [comment]
ok so I did some comparison tests based on the same dataset and all the parameters for train.py were the same and I was comparing how long it will take for 1 epoch to run when using cache vs no cache for each model, and it seems that only for yolov5n and yolov5s there is a significant difference between cache and no cache, for all others differences are marginal or there is no difference - so it seems as --cache param improves training speed for yolov5n and yolov5s only? or am I misinterpreting something?

here are the results:

![image](https://user-images.githubusercontent.com/10119183/153434814-72f0e259-f8f8-451c-9fae-c27a4aa3d776.png)

and here are the commands:

```
!python train.py --img 640 --batch 16 --epochs 3 --weights yolov5x.pt --data GlobalWheat2020.yaml --cache
!python train.py --img 640 --batch 16 --epochs 3 --weights yolov5x.pt --data GlobalWheat2020.yaml

!python train.py --img 640 --batch 16 --epochs 3 --weights yolov5l.pt --data GlobalWheat2020.yaml --cache
!python train.py --img 640 --batch 16 --epochs 3 --weights yolov5l.pt --data GlobalWheat2020.yaml

!python train.py --img 640 --batch 16 --epochs 3 --weights yolov5m.pt --data GlobalWheat2020.yaml --cache
!python train.py --img 640 --batch 16 --epochs 3 --weights yolov5m.pt --data GlobalWheat2020.yaml

!python train.py --img 640 --batch 16 --epochs 3 --weights yolov5s.pt --data GlobalWheat2020.yaml --cache
!python train.py --img 640 --batch 16 --epochs 3 --weights yolov5s.pt --data GlobalWheat2020.yaml

!python train.py --img 640 --batch 16 --epochs 3 --weights yolov5n.pt --data GlobalWheat2020.yaml --cache
!python train.py --img 640 --batch 16 --epochs 3 --weights yolov5n.pt --data GlobalWheat2020.yaml
```

**Comment by glenn-jocher** [comment]
@bszymik --cache speeds up training in general by caching your dataset into RAM. Model is irrelevant to the discussion, it has nothing to do with caching a dataset. If you want faster training you can pay for faster resources, i.e. Colab+ or ++, AWS, GCP, Azure, or on premise hardware.

**Comment by glenn-jocher** [comment]
@bszymik 👋 Hello! Thanks for asking about **training speed issues**. YOLOv5 🚀 can be trained on CPU (slowest), [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) (fastest). If you would like to increase your training speed some options are:

- Increase `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s
- Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) DDP at larger `--batch-size`
- Train with a cached dataset: `python train.py --cache`
- Train on faster GPUs, i.e.: P100 -> V100 -> A100
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

Good luck 🍀 and let us know if you have any other questions!

**Comment by bszymik** [comment]
@glenn-jocher I'm using Google Colab+ with GPU and high-ram option and I was surprised that training yolov5m and bigger models has almost no effect on train speed when using --cache and no cache - loading it to RAM should always improve the training time but for bigger models it don't....

anyway thanks for the training speed hints and all your time spent on this issue ;)

**Comment by glenn-jocher** [comment]
@bszymik with Colab++ I see about 90 second epochs with GlobalWheat, even for larger models, so might be worth an upgrade. These notebooks come with 8 vCPUs which allow more dataloader workers.
