### ISSUE TITLE
custom model inference without using detect.py 

### ISSUE THREAD

**Issue by memelvin99** [ultralytics/yolov5#6460]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,
I would like to use a custom inference code other than "detect.py". Here is the code I am trying, but not working.
![yoloerror](https://user-images.githubusercontent.com/56695402/151495085-c31fd9e0-8659-41f0-84dc-78891e48db29.jpg)

**Comment by glenn-jocher** [comment]
@memelvin99 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, etc.
# model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')  # custom trained model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by memelvin99** [comment]
Thanks for the quick reply.

I have trained a custom model and saved best.pt locally.
I have loaded the model using below code:
"model = torch.hub.load('C:/AI_Projects/fan_engine/yolo', 'custom', path='best.pt', source='local')"
But this code is giving me the error:
 "raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>"

Here is the complete code:

`import torch`
`path='/content/drive/MyDrive/Volvo/FANCASE/yolo/best.pt') # or yolov5m, yolov5l, yolov5x, custom`
`model = torch.hub.load('C:/AI_Projects/fan_engine/yolo', 'custom', path='best.pt', source='local')`
`img = 'C:/AI_Projects/fan_engine/yolo/images/data/11110731_wrong.png'  `
`results = model(img)`
`results.print()`

**Comment by glenn-jocher** [comment]
@memelvin99 see Colab notebook for example:
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb#scrollTo=GMusP4OAxFu6&line=2&uniqifier=1

<img width="1019" alt="Screenshot 2022-01-28 at 08 11 57" src="https://user-images.githubusercontent.com/26833433/151503322-bc83261a-fc49-44d6-870e-6077197ad811.png">

**Comment by memelvin99** [comment]
The above colab sample code is working for me. But the issue is when I am loading my custom model locally. I am getting  error:

> Exception: Invalid `--device 0` request, valid devices are 0 - -1. The cache may be out of date, try `force_reload=True` 

I have also tried `model = torch.hub.load('', 'custom', path='best.pt', source='local',force_reload=True)`
Still getting the same error.

**Comment by mx2013713828** [comment]
model = torch.hub.load('../yolov5/','custom',path='Yourpath/best.pt',source='local').
try this.

**Comment by glenn-jocher** [comment]
@memelvin99 your code is out of date

**Comment by wisplite** [comment]
I'm getting the same error with a similar setup. If the code is out of date, what is the correct way to do this? I'm pulling the line of code from the official tutorials for yolov5.

Edit: for additional clarity, I am running locally on Windows 10, and I am using PyTorch with CUDA. Detect.py works perfectly, but for my use case I am going to need to write my own code, and it keeps failing.

**Comment by glenn-jocher** [comment]
@Thebombuknow error has been fixed earlier in https://github.com/ultralytics/yolov5/pull/6461. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by wisplite** [comment]
Thanks! That fixed it! I just got extremely unlucky, as I happened to pull the repo mere hours before the bug was fixed.

**Comment by Symbadian** [comment]
> @memelvin99 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`.
> 
> ### Simple Inference Example
> This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.
> 
> ```python
> import torch
> 
> # Model
> model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, etc.
> # model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')  # custom trained model
> 
> # Images
> im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list
> 
> # Inference
> results = model(im)
> 
> # Results
> results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
> 
> results.xyxy[0]  # im predictions (tensor)
> results.pandas().xyxy[0]  # im predictions (pandas)
> #      xmin    ymin    xmax   ymax  confidence  class    name
> # 0  749.50   43.50  1148.0  704.5    0.874023      0  person
> # 2  114.75  195.75  1095.0  708.0    0.624512      0  person
> # 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
> ```
> 
> <img alt="" width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">
> 
> See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.
> 
> Good luck 🍀 and let us know if you have any other questions!

Hi @glenn-jocher, 

I have been following your instructions above to get the best results for the custom model.
I followed the instructions and git pulled the clone model again but somehow this option is throwing an error and I am not sure how to interpret the meaning of it to move forward.

**Can you help me understand what is happening within the error prompt and how do I proceed to solve this challenge?**
THANK YOU LOADS in advance for all of your guidance and efforts.......


WHEN I: try it this way it works: 
python3 detect.py --weights /Users/symbadian/Desktop/LIRIS_new_dataset/Old_WorkingYOLOv5/yolov5/runs/train/Pre-Trained-weights/WithAUGS_Better_Perfor/exp_yolov5s/weights/best.pt --source /Users/symbadian/Desktop/LIRIS_new_dataset/Old_WorkingYOLOv5/yolov5/data/images  --conf 0.6 

BUT I would like to get the results printed 
#      xmin    ymin    xmax   ymax  confidence  class    name






My code:
```
import torchvision
import torch

# Model
model = torch.hub.load('./new_dataset/yolov5/models/hub/', 'yolov5m6.yaml')

# Images
dir = './new_dataset/yolov5/data/images/'
imgs = [dir + f for f in ('zidane.jpg', 'bus.jpg')]  # batch of images

# Inference
results = model(imgs)
results.print()  # or .show(), .save() 

***ERROR***********

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/hub.py", line 537, in load
    repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, trust_repo, "load",
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/hub.py", line 180, in _get_cache_or_reload
    repo_owner, repo_name, ref = _parse_repo_info(github)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/hub.py", line 126, in _parse_repo_info
    repo_owner, repo_name = repo_info.split('/')
ValueError: too many values to unpack (expected 2)
>>> model = torch.hub.load('ultralytics/yolov5', 'yolov5s')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/hub.py", line 537, in load
    repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, trust_repo, "load",
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/hub.py", line 180, in _get_cache_or_reload
    repo_owner, repo_name, ref = _parse_repo_info(github)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/hub.py", line 133, in _parse_repo_info
    with urlopen(f"https://github.com/{repo_owner}/{repo_name}/tree/main/"):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
``

**Comment by glenn-jocher** [comment]
@Symbadian you don't load yamls, you load models, i.e.

```pythoin
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, etc.
model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')  # custom trained model
```

**Comment by Symbadian** [comment]
> ```python
> model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')
> ```

Hi @glenn-jocher,

I tried that as well and got the same error hence me reaching out to you... 
please assist!? 
Your guidance is crucial at this stage
```
Python 3.10.6 (v3.10.6:9c7b4bd164, Aug  1 2022, 17:13:48) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import torchvision
>>>  model = torch.hub.load('ultralytics/yolov5', 'custom', '/Users/symbadian/Desktop/LIRIS_new_dataset/WITH_BG_WITHAUGs/yolov5b/runs/train/Pre-Trained-weights/exp_yolov5m/weights/best.pt')
  File "<stdin>", line 1
    model = torch.hub.load('ultralytics/yolov5', 'custom', '/Users/symbadian/Desktop/LIRIS_new_dataset/WITH_BG_WITHAUGs/yolov5b/runs/train/Pre-Trained-weights/exp_yolov5m/weights/best.pt')
IndentationError: unexpected indent
>>> model = torch.hub.load('ultralytics/yolov5', 'custom', '/Users/symbadian/Desktop/LIRIS_new_dataset/WITH_BG_WITHAUGs/yolov5b/runs/train/Pre-Trained-weights/exp_yolov5m/weights/best.pt')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/hub.py", line 537, in load
    repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, trust_repo, "load",
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/hub.py", line 180, in _get_cache_or_reload
    repo_owner, repo_name, ref = _parse_repo_info(github)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/hub.py", line 133, in _parse_repo_info
    with urlopen(f"https://github.com/{repo_owner}/{repo_name}/tree/main/"):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997
```

**Comment by glenn-jocher** [comment]
@Symbadian just read your error and fix this yourself. It says unexpected indent. This is user error.

**Comment by Symbadian** [comment]
> model = torch.hub.load('ultralytics/yolov5', 'custom', '/Users/symbadian/Desktop/LIRIS_new_dataset/WITH_BG_WITHAUGs/yolov5b/runs/train/Pre-Trained-weights/exp_yolov5m/weights/best.pt')

Hi @glenn-jocher and thanks so much for your swift response and your time, I really really appreciate this..

I am trying to interpret these errors so I realized that there was an indentation error so I fixed it, but that was not the real issue, please see below

```
(/Users/symbadian/miniforge3/ml) Matthews-MacBook-Pro:yolov5 symbadian$ python3
Python 3.10.6 (v3.10.6:9c7b4bd164, Aug  1 2022, 17:13:48) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import torchvision
>>> model = torch.hub.load('/Users/symbadian/Desktop/LIRIS_new_dataset/WITH_BG_WITHAUGs/yolov5/models/hub/yolov5m6.yaml', '/Users/symbadian/Desktop/LIRIS_new_dataset/WITH_BG_WITHAUGs/yolov5b/runs/train/Pre-Trained-weights/exp_yolov5m/weights/best.pt')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/hub.py", line 537, in load
    repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, trust_repo, "load",
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/hub.py", line 180, in _get_cache_or_reload
    repo_owner, repo_name, ref = _parse_repo_info(github)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/hub.py", line 126, in _parse_repo_info
    repo_owner, repo_name = repo_info.split('/')
ValueError: too many values to unpack (expected 2)
>>> 
```

**Comment by glenn-jocher** [comment]
@Symbadian I've already told you above not to load YAMLs. Please don't waste my time, I'm extremely busy.

**Comment by Symbadian** [comment]
> @Symbadian I've already told you above not to load YAMLs. Please don't waste my time, I'm extremely busy.

forgive my lapse in understanding @glenn-jocher, I am really trying to get this going, please see below:
```

>>> import torch
>>> import torchvision
>>> model = torch.hub.load('/Users/symbadian/Desktop/LIRIS_new_dataset/WITH_BG_NoAUGs/yolov5/', 'yolov5m6.pt')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/hub.py", line 537, in load
    repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, trust_repo, "load",
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/hub.py", line 180, in _get_cache_or_reload
    repo_owner, repo_name, ref = _parse_repo_info(github)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/hub.py", line 126, in _parse_repo_info
    repo_owner, repo_name = repo_info.split('/')
ValueError: too many values to unpack (expected 2)
>>> 
```

**Comment by ashishupadhyaa** [comment]
> @memelvin99 wave Hello! Thanks for asking about **handling inference results**. YOLOv5 rocket [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`.
> 
> ### Simple Inference Example
> This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.
> 
> ```python
> import torch
> 
> # Model
> model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, etc.
> # model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')  # custom trained model
> 
> # Images
> im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list
> 
> # Inference
> results = model(im)
> 
> # Results
> results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
> 
> results.xyxy[0]  # im predictions (tensor)
> results.pandas().xyxy[0]  # im predictions (pandas)
> #      xmin    ymin    xmax   ymax  confidence  class    name
> # 0  749.50   43.50  1148.0  704.5    0.874023      0  person
> # 2  114.75  195.75  1095.0  708.0    0.624512      0  person
> # 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
> ```
> 
> <img alt="" width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">
> 
> See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.
> 
> Good luck four_leaf_clover and let us know if you have any other questions!

It is not working. Can you please look into it.

**Comment by glenn-jocher** [comment]
@ashishupadhyaa hello! Thank you for reaching out and sharing your concern about the YOLOv5 PyTorch Hub model. I apologize for the inconvenience you are facing.

To better assist you, could you please provide more details about the specific issue you are encountering? Are you experiencing any error messages or unexpected behavior?

Once we have more information, we will be able to investigate the issue and provide a solution or further guidance. Looking forward to hearing from you.
