### ISSUE TITLE
Invoke endpoint

### ISSUE THREAD

**Issue by asc7559** [ultralytics/yolov5#6462]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is there any tutorials available for creating Endpoint & infrencing Endpoint using yolov5 model on Sagemaker, I could'nt find much information available on internet

**Comment by glenn-jocher** [comment]
@asc7559 👋 Hello! Thanks for asking about YOLOv5 🚀 **APIs**. For a YOLOv5 Flask REST API example code see https://github.com/ultralytics/yolov5/tree/master/utils/flask_rest_api

For a live example see https://ultralytics.com/yolov5
<img width="1390" alt="Screenshot 2022-01-29 at 05 38 29" src="https://user-images.githubusercontent.com/26833433/151647475-394b05ca-4de7-41d3-92d7-fd8bb9a153d6.png">

Good luck 🍀 and let us know if you have any other questions!

**Comment by ghost** [comment]
Have you found any solutions ?
