### ISSUE TITLE
Allow custom save_dir in evolve parameters

### ISSUE THREAD

**Issue by MattVAD** [ultralytics/yolov5#6463]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Hello everyone and thank you for your work on this project ! 

I was trying to save all the results concerning the evolve parameters in my drive with the "--project" peramater of the train.py script without any success. The results were always saved in the run/evolve directory. 

In order to go beyond this limitation, I comment the line 518 in train.py. That is : 
<img width="958" alt="image" src="https://user-images.githubusercontent.com/48956156/151512394-dd98749f-b6c9-4eee-8f10-94ede1bbb65f.png">

I think in this case of training, that can be very long, it's better to allow the user to custom his save directory. 
Many thanks ! 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@MattVAD sounds like a reasonable use case. Can you submit a PR to use custom --project with evolve? Thanks!

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by glenn-jocher** [comment]
@MattVAD PR #6567 is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐
