### ISSUE TITLE
tensorRT export error！

### ISSUE THREAD

**Issue by WangRongsheng** [ultralytics/yolov5#6467]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Export

### Bug

I'm running：
```python
python export.py --data dataset/data.yaml --weights runs/train/exp4/weights/best.pt --include engine
```

error：
```html
export: data=dataset/data.yaml, weights=['runs/train/exp4/weights/best.pt'], imgsz=[640, 640], batch_size=1, device=cpu, half=False, inplace=False, train=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=12, verbose=False, workspace=4, nms=False, agnostic_nms=False, topk_per_class=100, topk_all=100, iou_thres=0.45, conf_thres=0.25, include=['engine']
YOLOv5  2022-1-7 torch 1.8.0 CPU

Fusing layers...
Model Summary: 290 layers, 20869098 parameters, 0 gradients, 48.0 GFLOPs

PyTorch: starting from runs\train\exp4\weights\best.pt (42.2 MB)

TensorRT: export failure: No module named 'tensorrt'

Export complete (4.33s)
Results saved to C:\Users\60332\Desktop\main-yolov5\runs\train\exp4\weights
Visualize with https://netron.app
```

Then I can't install `tensorrt`，I hope that you can find it in `requirements.txt` provide the installation package required by `tensorrt`

### Environment

- YOLOv5：V6
- OS：win10
- python：3.6.5

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by zhiqwang** [comment]
Hi @WangRongsheng ,

Seems that you didn't install TensorRT . Check this https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing for more details.

The [installation](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing-pip) is easy as below if you are using linux, your CUDA version is greater than 11, and you are only using the python interface :

```bash
pip install nvidia-tensorrt --extra-index-url https://pypi.ngc.nvidia.com
```

**Comment by WangRongsheng** [comment]
@zhiqwang thank you,I've solved the problem.Because I use windows, the current version 8.2 of tensorrt supports the installation of windows tensorrt.If others need it, they can enter: [https://developer.nvidia.com/nvidia-tensorrt-8x-download](https://developer.nvidia.com/nvidia-tensorrt-8x-download)

**Comment by KevenLee** [comment]
> Hi @WangRongsheng ,
> 
> Seems that you didn't install TensorRT . Check this https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing for more details.
> 
> The [installation](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing-pip) is easy as below if you are using linux, your CUDA version is greater than 11, and you are only using the python interface :
> 
> ```shell
> pip install nvidia-tensorrt --extra-index-url https://pypi.ngc.nvidia.com
> ```

How do I install tensorrt 7.2.3 using pip tools

**Comment by samjaylin** [comment]
Hi @KevenLee 
The [installation](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing-pip) is easy as below if you are using linux
`pip install nvidia-tensorrt==7.2.3.4 --index-url https://pypi.ngc.nvidia.com`
