### ISSUE TITLE
Yolov5M or L transformer Yaml

### ISSUE THREAD

**Issue by b3r-prog** [ultralytics/yolov5#6469]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I see the yaml file for Yolov5s transformer here https://github.com/ultralytics/yolov5/blob/master/models/hub/yolov5s-transformer.yaml. Do we have one for medium or large?

Can I convert by just adding in the module `[-1, 3, C3TR, [1024]],  # 9 <--- C3TR() Transformer module` here? Also should one expect a performance improvement or latency gain?

@glenn-jocher @zhiqwang

**Comment by zhiqwang** [comment]
Hi @b3r-prog , I guess there are no trained medium or large checkpoint, but you can change the below to [(0.67, 0.75)](https://github.com/ultralytics/yolov5/blob/7539cd75c3a6c06d00848617f6265f39a765ccea/models/yolov5m.yaml#L5-L6) and [(1.0, 1.0)](https://github.com/ultralytics/yolov5/blob/7539cd75c3a6c06d00848617f6265f39a765ccea/models/yolov5l.yaml#L5-L6) respectively to get the medium or large model if you want to train from scratch

https://github.com/ultralytics/yolov5/blob/7539cd75c3a6c06d00848617f6265f39a765ccea/models/hub/yolov5s-transformer.yaml#L5-L6

**Comment by b3r-prog** [comment]
@zhiqwang @glenn-jocher, thanks for response. Did we see any performance improvement? also any issue with speed during inference?

**Comment by jaideep11061982** [comment]
@glenn-jocher what is benchmark score for s6transformer

**Comment by glenn-jocher** [comment]
@jaideep11061982 we mainly haven't explored larger transformer models because the C3TR() modules use so much memory.
