### ISSUE TITLE
Embed model information

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#6470]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

@glenn-jocher 
I have a question, how to embed personal information into the model of yolov5 and then read it again by python program. I drew a diagram:
![yolov5_model](https://user-images.githubusercontent.com/41098760/151695510-f15c626e-8912-4726-be16-60f3c51c0519.png)

**Comment by glenn-jocher** [comment]
@Zengyf-CVer for YOLOv5 PyTorch models this is very easy because they are just python dictionaries. You just add any extra keys you want, i.e.:

https://github.com/ultralytics/yolov5/blob/7539cd75c3a6c06d00848617f6265f39a765ccea/train.py#L387-L399

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
Thank you very much.
