### ISSUE TITLE
Stack Img size issue

### ISSUE THREAD

**Issue by jaideep11061982** [ultralytics/yolov5#6476]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I get the below error. I know the reason for the error but then i dont understand why should i get error , i was not expecting yolo to do square resize , if yes where is it doing that. I checked all the dataset code, load image does resize with scale factor imgsize/h, imgsize/w .
`RuntimeError: stack expects each tensor to be equal size, but got [3, 1792, 3200] at entry 0 and [3, 3200, 3200] at entry 1`

I use augmentation

```
 A.OneOf([ #A.RandomCrop(width=width, height=crop_height,p=0.5),
                                          A.CenterCrop(width=width, height=crop_height,p=0.0),
                                          A.RandomSizedBBoxSafeCrop(width=width, height=crop_height,p=0.5),

                                          A.RandomResizedCrop (width=width,height=crop_height, scale=(0.15, 1.0), 
                                                               ratio=(0.75, 1.3333333333333333), 
                                                               interpolation=1, always_apply=False, p=0.5)

                                         ], p=0.2),
```

### Additional

I use albumentation

 A.OneOf([ #A.RandomCrop(width=width, height=crop_height,p=0.5),
                                          A.CenterCrop(width=width, height=crop_height,p=0.0),
                                          A.RandomSizedBBoxSafeCrop(width=width, height=crop_height,p=0.5),

                                          A.RandomResizedCrop (width=width,height=crop_height, scale=(0.15, 1.0), 
                                                               ratio=(0.75, 1.3333333333333333), 
                                                               interpolation=1, always_apply=False, p=0.5)

                                         ], p=0.2),

**Comment by jaideep11061982** [comment]
Here is debug 

load image rect (1800, 3200, 3)   720 1280 change 1800 3200
letterbox (1856, 3264, 3)
  0%|          | 0/2444 [00:00<?, ?it/s]                                        load image rect (1800, 3200, 3)   720 1280 change 1800 3200
letterbox (3200, 3200, 3)

As I see the letter box is producing some times square img some times not. Dont understand the behaviour  of letter box utility

**Comment by glenn-jocher** [comment]
@jaideep11061982 any Albumentations operations that change the shape of the image with break the dataloader without additional post-processing after Albumentations to return the new image to the original shape. You must customize the dataloader to do this if you introduce shape-changing Albumentations.

**Comment by jaideep11061982** [comment]
I tried following code before albumentation that diwa  preprocessing  but
couldn't figure out well  ,so i can accordingly restore the img  size post
albumentation .
Can you please for this case
Height  720
Width 1270
Img size 3200.

My expectation as per code was that it would return   ( 3200/1280 ) * (
h,w)
But I get 3200,3200 .

**Comment by glenn-jocher** [comment]
@jaideep11061982 for any shape input if you want say 640x640 letterboxed output then you might just pass:
```python
letterbox(im, new_shape=(640, 640), auto=False, scaleFill=False, scaleup=False)
```

**Comment by SyedHamza0196** [comment]
Any solution found for this issue?

**Comment by SyedHamza0196** [comment]
Is it possible if pad tensors wrt the biggest tensor?
