### ISSUE TITLE
Generate Precision Recall Curve with a custom IoU Threshold i.e., mAP@0.75

### ISSUE THREAD

**Issue by mburges-cvl** [ultralytics/yolov5#6478]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,

how do I gernerate a precision recall curve at a different mAP (i.e. mAP@75)? From what I understand it should be possible in [this](https://github.com/ultralytics/yolov5/blob/7539cd75c3a6c06d00848617f6265f39a765ccea/utils/metrics.py#L21) function, but I am not sure how exactly I would to it.

Thanks,
Marvin

**Comment by glenn-jocher** [comment]
@mburges-cvl you can modify the default values here:
https://github.com/ultralytics/yolov5/blob/7539cd75c3a6c06d00848617f6265f39a765ccea/utils/metrics.py#L117-L119

**Comment by mburges-cvl** [comment]
@glenn-jocher Thank you for you fast answer! I modified the values, but the Precision-Recall-Curve looks the same. It does however influence the confusion matrix (obviously), but as I have only one class anyways this isn't really of value for me. Could you maybe elaborate a bit more?

Thanks!

**Comment by glenn-jocher** [comment]
@mburges-cvl oh yes sorry that's for the confusion matrix. PR curve is evaluated at 0.5 mAP and whatever IoU threshold you pass i.e. `python val.py --iou 0.45`
https://github.com/ultralytics/yolov5/blob/7539cd75c3a6c06d00848617f6265f39a765ccea/utils/metrics.py#L66-L71
