### ISSUE TITLE
Using YOLOv5's detect.py script with other models?

### ISSUE THREAD

**Issue by dariogonle** [ultralytics/yolov5#6479]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I was wondering if it is possible to use detect.py with other models. I mean if I have a SSD TensorRT model, could I use the YOLOv5's detect.py script to run this SSD model?

Thank you in advance.

**Comment by glenn-jocher** [comment]
@dariogonle you can use detect.py with TensorRT models, but they must be YOLOv5 TensorRT models, i.e.:
```bash
python detect.py --weights yolov5s.engine
```

**Comment by ArgoHA** [comment]
Can in work with custom yolov5 tensorrt model?
I trained a net and converted weights to model.plan/model.engine
I tried detect.py and got this issue:
```
Traceback (most recent call last):
  File "detect.py", line 257, in <module>
    main(opt)
  File "detect.py", line 252, in main
    run(**vars(opt))
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 92, in run
    model = DetectMultiBackend(weights, device=device, dnn=dnn, data=data)
  File "/usr/src/app/models/common.py", line 345, in __init__
    for index in range(model.num_bindings):
AttributeError: 'NoneType' object has no attribute 'num_bindings'
```

**Comment by glenn-jocher** [comment]
@ArgoHA for TensorRT workflow example see Colab notebook Appendix section:
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb?hl=en

```python
# TensorRT 
!pip install -U nvidia-tensorrt --index-url https://pypi.ngc.nvidia.com  # install
!python export.py --weights yolov5s.pt --include engine --imgsz 640 640 --device 0  # export
!python detect.py --weights yolov5s.engine --imgsz 640 640 --device 0  # inference
```

**Comment by ArgoHA** [comment]
@glenn-jocher It seems like I did pretty much that (except of export, I got .engine from this conversion

Does export.py converts weights to .engine?

So here is my command and the problem:
```
python detect.py --weights model.engine --source /usr/src/datasets --conf 0.85 --save-txt --save-conf --save-crop --imgsz 640 640
detect: weights=['model.engine'], source=/usr/src/datasets, data=data/coco128.yaml, imgsz=[640, 640], conf_thres=0.85, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=True, save_conf=True, save_crop=True, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False
YOLOv5 🚀 v6.1-11-g63ddb6f torch 1.10.2+cu113 CUDA:0 (NVIDIA RTX A4000, 16116MiB)

Loading model.engine for TensorRT inference...
[TensorRT] INFO: [MemUsageChange] Init CUDA: CPU +532, GPU +0, now: CPU 629, GPU 5320 (MiB)
[TensorRT] INFO: Loaded engine size: 106 MB
[TensorRT] INFO: [MemUsageSnapshot] deserializeCudaEngine begin: CPU 735 MiB, GPU 5320 MiB
[TensorRT] ERROR: 3: getPluginCreator could not find plugin: YoloLayer_TRT version: 1
[TensorRT] ERROR: 1: [pluginV2Runner.cpp::load::291] Error Code 1: Serialization (Serialization assertion creator failed.Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)
[TensorRT] ERROR: 4: [runtime.cpp::deserializeCudaEngine::75] Error Code 4: Internal Error (Engine deserialization failed.)
Traceback (most recent call last):
  File "detect.py", line 257, in <module>
    main(opt)
  File "detect.py", line 252, in main
    run(**vars(opt))
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 92, in run
    model = DetectMultiBackend(weights, device=device, dnn=dnn, data=data)
  File "/usr/src/app/models/common.py", line 345, in __init__
    for index in range(model.num_bindings):
AttributeError: 'NoneType' object has no attribute 'num_bindings'

```
Any help appreciated!

BTW I use yolov5 in docker and I have only 1 class

UPD. I used export.py to get .engine and it worked! So What's the point of this link? https://github.com/wang-xinyu/tensorrtx

**Comment by hoaitran95** [comment]
> @glenn-jocher It seems like I did pretty much that (except of export, I got .engine from this conversion
> 
> Does export.py converts weights to .engine?
> 
> So here is my command and the problem:
> 
> ```
> python detect.py --weights model.engine --source /usr/src/datasets --conf 0.85 --save-txt --save-conf --save-crop --imgsz 640 640
> detect: weights=['model.engine'], source=/usr/src/datasets, data=data/coco128.yaml, imgsz=[640, 640], conf_thres=0.85, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=True, save_conf=True, save_crop=True, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False
> YOLOv5 🚀 v6.1-11-g63ddb6f torch 1.10.2+cu113 CUDA:0 (NVIDIA RTX A4000, 16116MiB)
> 
> Loading model.engine for TensorRT inference...
> [TensorRT] INFO: [MemUsageChange] Init CUDA: CPU +532, GPU +0, now: CPU 629, GPU 5320 (MiB)
> [TensorRT] INFO: Loaded engine size: 106 MB
> [TensorRT] INFO: [MemUsageSnapshot] deserializeCudaEngine begin: CPU 735 MiB, GPU 5320 MiB
> [TensorRT] ERROR: 3: getPluginCreator could not find plugin: YoloLayer_TRT version: 1
> [TensorRT] ERROR: 1: [pluginV2Runner.cpp::load::291] Error Code 1: Serialization (Serialization assertion creator failed.Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)
> [TensorRT] ERROR: 4: [runtime.cpp::deserializeCudaEngine::75] Error Code 4: Internal Error (Engine deserialization failed.)
> Traceback (most recent call last):
>   File "detect.py", line 257, in <module>
>     main(opt)
>   File "detect.py", line 252, in main
>     run(**vars(opt))
>   File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
>     return func(*args, **kwargs)
>   File "detect.py", line 92, in run
>     model = DetectMultiBackend(weights, device=device, dnn=dnn, data=data)
>   File "/usr/src/app/models/common.py", line 345, in __init__
>     for index in range(model.num_bindings):
> AttributeError: 'NoneType' object has no attribute 'num_bindings'
> ```
> 
> Any help appreciated!
> 
> BTW I use yolov5 in docker and I have only 1 class
> 
> UPD. I used export.py to get .engine and it worked! So What's the point of this link? https://github.com/wang-xinyu/tensorrtx

I export on RTX 3080 and run on Xavier have the same problem with you (AttributeError: 'NoneType' object has no attribute 'num_bindings'). But When I export model by Xavier. It run Ok. No problem.

**Comment by glenn-jocher** [comment]
@minhhoai1001 @ArgoHA yes YOLOv5 TensorRT exports must be run directly on the inference device. If you want to detect on Xavier you must export on Xavier.

**Comment by edgarshang** [comment]
@ArgoHA have you solve it? I have the same problem with u

**Comment by hi-one-gg** [comment]
I have the same error.
Export is OK, but not work in `detect.py`

It looks related with TensorRT version. Because TensorRT under 7 is works.

**Comment by glenn-jocher** [comment]
Hi @blackCmd,

Thank you for your message. It seems like you're encountering issues with TensorRT versions when using `detect.py` after exporting your model. Let's address this step-by-step:

1. **Ensure Latest Versions**: First, please make sure you are using the latest versions of `torch` and the YOLOv5 repository. You can update your YOLOv5 repo and dependencies with the following commands:
    ```bash
    git pull
    pip install -U -r requirements.txt
    ```

2. **TensorRT Version Compatibility**: TensorRT version compatibility can indeed be a factor. If TensorRT versions below 7 are working for you, it might be worth sticking to those versions for now. However, if you need to use a newer version, ensure that all dependencies are correctly installed and compatible with your hardware and software environment.

3. **Export on Inference Device**: As mentioned earlier in this thread, exporting the model on the same device where inference will be run can help avoid compatibility issues. For example, if you plan to run inference on a Xavier device, export the model on the Xavier device.

4. **Minimum Reproducible Example**: If the issue persists, please provide a minimum reproducible example of your code and environment setup. This will help us better understand and reproduce the issue. You can find more details on how to create a minimum reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

5. **Example Commands**: Here are the commands to export and run inference using TensorRT:
    ```bash
    # Export model to TensorRT
    python export.py --weights yolov5s.pt --include engine --imgsz 640 640 --device 0

    # Run inference using detect.py
    python detect.py --weights yolov5s.engine --source /usr/src/datasets --conf 0.85 --save-txt --save-conf --save-crop --imgsz 640 640
    ```

If you continue to face issues, please share the specific TensorRT version you are using and any relevant logs or error messages. This will help us diagnose the problem more effectively.

Thank you for your patience and cooperation. The YOLO community and the Ultralytics team are here to help!
