### ISSUE TITLE
Hi All, Please Mind the license!

### ISSUE THREAD

**Issue by wtiandong** [ultralytics/yolov5#648]
## ❔Question
Hi all, 
Please NOTE that the license is GNUv3, which means if you use this model or a modified model based on this project, you need to disclose your source. If you use this model in your commercial product, you need to disclose your project source too.

Actually it is not good because there's no specific limitation in the project of yolo.

**Comment by Ownmarc** [comment]
@glenn-jocher any reason to make Yolov5 GPLv3 licensed and not push it to AGPL ? In other words, why allow SaaS to closely use yolov5 but not allow it to be used in "distributed" software ?

**Comment by glenn-jocher** [comment]
@Ownmarc thanks for the suggestion! I'm not actually knowledgeable about AGPL. I'll do some homework on it!

**Comment by Frank1126lin** [comment]
I got a relationship about all these license:

```
for open_source_software:
if  others_can_choose_to_close_source_code_after_modified:
    if every_file_that_changed_has_to_list_the_license:
        choose Apache license
    else:
        if the_modified_software_can_use_your_name_or_reputation_to_ad:
            choose MIT license
        else:
            choose BSD license
else:
    if the_modified_software_has_to_choose_the_same_license:
        choose GPL license
    else:
        if the_instructions_need_to_offer_for_the_places_that_changed:
            choose Mozilla license
        else:
            choose LGPL license

```
And for GPL, if someone didn't **release** their software, just use it as SaaS, it can use the GPL license and don't have to open_source the modified software. For this , the AGPL add the restrict that if the modified software is used as SaaS, the server should allow the users to download the sourcecode of the modified software.
refer:
http://www.gnu.org/licenses/why-affero-gpl.html
https://choosealicense.com/licenses/
