### ISSUE TITLE
Can't change resolution to 4k because of pixel format

### ISSUE THREAD

**Issue by Inquisiteurr** [ultralytics/yolov5#6480]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I am trying to change the resolution of my detect.py output, but I can't manage to get 4k.

my webcam :
logitech BRIO 4k

Operating system :
Debian 11

so the question is :
Is there a way to change pixel format to MJPG with yolov5 instead of raw video?
I will explain :
when i set my resolution with V4L2, it shows me that i can go to 4k in MJPEG:
v4l2-ctl --set-fmt-video=width=3840,height=2160,pixelformat=1
v4l2-ctl --get-fmt-video

Format Video Capture:
	Width/Height      : 3840/2160
	Pixel Format      : 'MJPG' (Motion-JPEG)
	Field             : None
	Bytes per Line    : 0
	Size Image        : 16588800
	Colorspace        : sRGB
	Transfer Function : Rec. 709
	YCbCr/HSV Encoding: ITU-R 601
	Quantization      : Default (maps to Full Range)
	Flags             : 

But when I run detect.py my pixel format goes to YUYV (raw) and my resolution goes back to full hd :

Format Video Capture:
	Width/Height      : 1920/1080
	Pixel Format      : 'YUYV' (YUYV 4:2:2)
	Field             : None
	Bytes per Line    : 3840
	Size Image        : 4147200
	Colorspace        : sRGB
	Transfer Function : Rec. 709
	YCbCr/HSV Encoding: ITU-R 601
	Quantization      : Default (maps to Limited Range)
	Flags             :

**Comment by glenn-jocher** [comment]
@TriNOEL you can try to customize the streamloader here:
https://github.com/ultralytics/yolov5/blob/7539cd75c3a6c06d00848617f6265f39a765ccea/utils/datasets.py#L283-L370
