### ISSUE TITLE
How to reproduce the mlmodels downloadable in v6.0 (preview not available with export.py)

### ISSUE THREAD

**Issue by AtomScott** [ultralytics/yolov5#6486]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Recently, @glenn-jocher added support for mlmodel inference. 
https://github.com/ultralytics/yolov5/pull/6195#issue-1093896019

This is great and demonstrated an easy way to check mlmodels. The same mlmodel can be opened in xcode with the preview option available. However, I can't reproduce the same mlmodel using export.py. 

The torchhub mlmodel and the mlmodel downloadable from https://github.com/ultralytics/yolov5/releases/tag/v6.0 seem to be the same, but the mlmodel generate from 
```
!python export.py --weights yolov5s.pt --include coreml  # CoreML export
```

is different. 
Are there any other extra options necessary to reproduce the exact same thing? 

It would be extremely helpful to be able to view yolov5 in xcode with the  preview tab available.

### Additional

**Different description and output in when viewed in xcode**
![image](https://user-images.githubusercontent.com/22371492/151907836-edc00aca-209d-454f-bee1-900188037a2a.png)

*  (LEFT) mlmodel downloaded from v6 release page.
* (RIGHT) ml model exported with the following command
```
docker run ultralytics/yolov5 python export.py --weights yolov5n.pt --include coreml
```

I have also noticed that the output in preview tab is sometimes completely wrong depending on the scale and aspect ratio of the image. Should I open an extra issue for this? or is this behaviour expected?

https://user-images.githubusercontent.com/22371492/151907982-a78368bc-7c85-475b-83ab-3b9e61c9984c.mov

**Comment by AtomScott** [comment]
@glenn-jocher Can I get input on this issue?

**Comment by nicolexirakia** [comment]
Hi @glenn-jocher , I am facing the exact same problem.
