### ISSUE TITLE
Detect a video frame by frame with different weights!!!

### ISSUE THREAD

**Issue by Thanossrs** [ultralytics/yolov5#6487]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

If I have a video, is there the possibility to detect frame by frame (without splitting the video into images and saving it in a local hard disk) with different weights???

Thanks

### Additional

I need to run YOLO in a video and after some frames to detect it with different custom weights and vice versa.

**Comment by glenn-jocher** [comment]
@Thanossrs 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, etc.
# model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')  # custom trained model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by Thanossrs** [comment]
@glenn-jocher thank you for your prompt reply.

if I have a video (let's say 40seconds), how I could select to detect with Custom_Weights_1 in the first 20 seconds and last 20 seconds with Custom_Weight_2?

**Comment by glenn-jocher** [comment]
@Thanossrs you can load multiple YOLOv5 models easily:

```python
import torch

# Model
model1 = torch.hub.load('ultralytics/yolov5', 'custom', 'path1/to/best.pt')  # custom trained model 1
model2 = torch.hub.load('ultralytics/yolov5', 'custom', 'path2/to/best.pt')  # custom trained model 2
```

**Comment by Thanossrs** [comment]
@glenn-jocher thank you.

and how I could split the video into frames without saving the frames on my PC as images?
but keep it as a variable the frame temporary until detecting it

**Comment by glenn-jocher** [comment]
@Thanossrs see cv2 video loading examples, this is below the scope of our support.

**Comment by Thanossrs** [comment]
@glenn-jocher thank you for your prompt replies !!
