### ISSUE TITLE
To mix up.

### ISSUE THREAD

**Issue by abatiSon** [ultralytics/yolov5#6492]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

The right and left of an object are very similar to each other, I can even say the same. Sometimes, if there is an apple in the left hand, he can say the right hand. In the same situation, if the right hand is holding a bag, he can say left hand. Even if we feed it with enough data, we can get the same results. Is there any way to avoid this?
Thanks

**Comment by glenn-jocher** [comment]
@abatiSon I don't know what you're asking.

**Comment by abatiSon** [comment]
@glenn-jocher : There are only objects that are very similar to each other with different aspects. If there's something obscuring one of the objects that's blocking its view, it tends to find the opposite direction of where it should be. I'm looking for a way to avoid this.
We decide whether the object in front of us is right or left based on our own position, but I guess Yolo can't seem to do that.

**Comment by glenn-jocher** [comment]
@abatiSon I don't understand what you are saying

**Comment by JanErikDoornweerd** [comment]
@abatiSon There is not much of a difference between an apple and an apple. Yolo does not know its position in relation to the image. You could consider to just call it apple and determine left and right in post-processing.

**Comment by abatiSon** [comment]
![koltuk](https://user-images.githubusercontent.com/95738656/152214529-58743c16-a8d8-42ef-bf31-c4e5f4b9ce71.png)
@glenn-jocher, @TheCraft  
I find the right and left seat. It does not mix the right and left seats when there is nothing on it. But if there is an object on it or the seat is deformed, sometimes it can call the left seat right and the right seat left. Even if I give enough data, it confuses them. This is valid for the right and left headlights.

**Comment by abatiSon** [comment]
It doesn't say 50% right 30% left, it just says 50% left or right.

**Comment by abatiSon** [comment]
If one of the two similar objects with different directions is damaged, the tendency to find the other direction increases.

**Comment by glenn-jocher** [comment]
@abatiSon YOLOv5 is just an object detector, it is not designed really to localize objects of the same class by location.

<img width="2163" alt="Screenshot 2021-11-22 at 18 26 43" src="https://user-images.githubusercontent.com/26833433/152234418-51e842f6-150a-4992-92a3-4c6cf268b452.png">
