### ISSUE TITLE
Can we hide confidence when we use torch.hub.load

### ISSUE THREAD

**Issue by shabieh2** [ultralytics/yolov5#6501]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

when we run using python detect.py  we have an option for hiding the confidence score using flag --hide-conf.

Can we do the same when we use model=torch.hub.load(...) and then do result=model(img)

The pictures are showing confidence scores and I want to hide them.

Thanks! 

### Additional

thanks!

**Comment by glenn-jocher** [comment]
@shabieh2 hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

The relevant section of the code that includes PyTorch Hub model settable attributes is here:
https://github.com/ultralytics/yolov5/blob/4c409332667477560200958b513b958bb8fdef71/models/common.py#L462-L471

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
