### ISSUE TITLE
exporting yolov5m.mlmodel 

### ISSUE THREAD

**Issue by vittorioz** [ultralytics/yolov5#6508]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Export

### Bug

I'am trying to export a yolov5m to .mlmodel format but when I try it with val.py it gives me no result. Also I tried it in my object detection script and it gives me "no detections" 

### Environment

Python 3.8 on apple silicon, conda environment with  pytorch=1.9.1 coremltools=5.1.0

### Minimal Reproducible Example

python3 export.py --weights yolov5m.pt --include coreml 

 python val.py --weights yolov5m.mlmodel  

### Additional

the above lines of codes works perfectly with yolov5s. I tried also to export the yolov5m in onnx format and it works.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@vittorioz good news 😃! Your original issue may now be fixed ✅ in PR #6496. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by vittorioz** [comment]
Nice it works perfectly! Thank you

**Comment by jordibruin** [comment]
@vittorioz would you mind sharing the model you generated with me? I'm unfamiliar with how to convert models to CoreML and would love to try this out. Can you send me a message at jordi@goodsnooze.com or twitter.com/jordibruin? Thanks!

Nevermind, found the page with all the models already 🙂
