### ISSUE TITLE
What adjustments are necessary for single-class detection training?

### ISSUE THREAD

**Issue by nicolas-gervais** [ultralytics/yolov5#6509]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

What are the adjustments required for the training on a custom dataset with a single class?

In the `data/training_parameters.yaml` file, should `nc` be 1? Or should I put 2 to save the first class as background class?

**Comment by gillonba** [comment]
I'm no expert, but I just put 1 and it worked fine

**Comment by glenn-jocher** [comment]
@nicolas-gervais logically if you have 1 class then your number of classes variable `nc=1`.
