### ISSUE TITLE
is early stopping working correctly? 

### ISSUE THREAD

**Issue by hdnh2006** [ultralytics/yolov5#6511]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello Ultralytics team,

I have trained a model and according to the summary wandb does, the best epochs is reached at the 9 epoch:

![image](https://user-images.githubusercontent.com/17271049/152194274-c02ddb56-7a5f-4b92-84dd-3cfef4213d28.png)

However, the model have completed the 300 epochs I assigned:

![image](https://user-images.githubusercontent.com/17271049/152194490-c5be6381-9dfe-461e-9b5d-acdd2917e970.png)

Of course I set the parameter `--patience 100`. I am currently training another model, but this time with `--patience 50` and it seems it is happening the same:

![image](https://user-images.githubusercontent.com/17271049/152194998-cb25a885-0948-4092-ad4b-35dc88c93be8.png)

If the best epoch is reached after 9 epochs, the code should stop at 109 epochs, right? 

Thanks in advance.

**Comment by glenn-jocher** [comment]
@hdnh2006 patience is the number of epochs with no improvement after which training will be stopped.

The best/ field in wandb was contributed by a user and is not related to the EarlyStopping class I implemented here:
https://github.com/ultralytics/yolov5/blob/4c409332667477560200958b513b958bb8fdef71/train.py#L277
