### ISSUE TITLE
Edge TPU Compilation

### ISSUE THREAD

**Issue by achelm15** [ultralytics/yolov5#6513]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have been messing around with customizing the number of CSPBottleNecks layers in the C3 modules in YOLOv5 in order to try to gain some of the performance of the small version while maintaining the size of the nano version. I tried to take the original YOLOv5n and change only the C3 modules in layers 4 and 6 to the number they have in YOLOv5s. My goal is to put this on a Google Coral Devboard so I attempted to put use the Google Edge TPU Compiler, however it always ends in an error:

Edge TPU Compiler version 16.0.384591198
Started a compilation timeout timer of 180 seconds.
Compilation child process completed within timeout period.
Compilation failed! 

Any ideas on how to fix this? Or a more appropriate place to ask this question?

Update: I have found that this occurs with the vanilla version of the YOLOv5s model as well.

**Comment by glenn-jocher** [comment]
@achelm15 code and model customizations are outside the scope of our official support but perhaps a community member has some ideas.
