### ISSUE TITLE
Yolov5 pruning throws error?

### ISSUE THREAD

**Issue by RizwanMunawar** [ultralytics/yolov5#6514]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Other

### Bug

I want to prune yolov5m custom trained. I followed yolov5 [pruning/sparsity tutorial](https://github.com/ultralytics/yolov5/issues/304). When I implemented this, I face below mentioned error,

`"ZeroDivisionError: division by zero"`

![anydesk00001](https://user-images.githubusercontent.com/62513924/152217032-fa42daf5-c626-4dcb-a46e-6a8c4c9fdbe8.png)

### Environment

YOLO : Yolov5
OS : Ubuntu 20.04
Python : python 3.7

### Minimal Reproducible Example

I have called below mentioned code, after model load in val.py.

        if training:  # called by train.py
          device, pt, jit, engine = next(model.parameters()).device, True, False, False  # get model device, PyTorch model
          half &= device.type != 'cpu'  # half precision only supported on CUDA
          model.half() if half else model.float()
        
        
       else:  # called directly
         device = select_device(device, batch_size=batch_size)
  
        `from utils.torch_utils import prune`     ------------------------------> Pruning---------------------
        `prune(model,0.3)`

        # Directories
        save_dir = increment_path(Path(project) / name, exist_ok=exist_ok)  # increment run
        (save_dir / 'labels' if save_txt else save_dir).mkdir(parents=True, exist_ok=True)  # make dir

        # Load model
        model = DetectMultiBackend(weights, device=device, dnn=dnn)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@RizwanMunawar I just re-ran the Pruning/Sparsity tutorial and everything works correctly. I updated it to current master branch and results. See https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity

<img width="1239" alt="Screenshot 2022-02-02 at 22 55 51" src="https://user-images.githubusercontent.com/26833433/152243983-161877e4-4e62-432a-b9a2-7e5ea4f6f7f8.png">

**Comment by glenn-jocher** [comment]
@RizwanMunawar BTW there may be better methods for pruning PyTorch models including QAT that we have not had time to investigate. If you find better implementations please let us know so we can update the tutorial.

**Comment by RizwanMunawar** [comment]
Thanks @glenn-jocher

**Comment by HankYe** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.
> 
> ### YOLOv5 Component
> Other
> 
> ### Bug
> I want to prune yolov5m custom trained. I followed yolov5 [pruning/sparsity tutorial](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity). When I implemented this, I face below mentioned error,
> 
> `"ZeroDivisionError: division by zero"`
> 
> ![anydesk00001](https://user-images.githubusercontent.com/62513924/152217032-fa42daf5-c626-4dcb-a46e-6a8c4c9fdbe8.png)
> 
> ### Environment
> YOLO : Yolov5 OS : Ubuntu 20.04 Python : python 3.7
> 
> ### Minimal Reproducible Example
> I have called below mentioned code, after model load in val.py.
> 
> ```
>     if training:  # called by train.py
>       device, pt, jit, engine = next(model.parameters()).device, True, False, False  # get model device, PyTorch model
>       half &= device.type != 'cpu'  # half precision only supported on CUDA
>       model.half() if half else model.float()
>     
>     
>    else:  # called directly
>      device = select_device(device, batch_size=batch_size)
> 
>     `from utils.torch_utils import prune`     ------------------------------> Pruning---------------------
>     `prune(model,0.3)`
> 
> 
> 
>     # Directories
>     save_dir = increment_path(Path(project) / name, exist_ok=exist_ok)  # increment run
>     (save_dir / 'labels' if save_txt else save_dir).mkdir(parents=True, exist_ok=True)  # make dir
> 
>     # Load model
>     model = DetectMultiBackend(weights, device=device, dnn=dnn)
> ```
> 
> ### Additional
> _No response_
> 
> ### Are you willing to submit a PR?
> * [ ]  Yes I'd like to help by submitting a PR!

Hi @RizwanMunawar, I have successfully pruned YOLOv5 of multiple scales. Maybe you can also refer to https://github.com/HankYe/PAGCP to get more helpful information. Hope my experiences can give you some help.
