### ISSUE TITLE
Exclude some tag or tags during training.

### ISSUE THREAD

**Issue by abatiSon** [ultralytics/yolov5#6520]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I noticed that one or more of the tags in my current dataset is breaking the training. Can I exclude those tags from training while retraining without breaking the existing dataset?

**Comment by glenn-jocher** [comment]
@abatiSon you can create a list of include classes here in your dataloader. Only classes in this list will be trained on, the rest will be ignored:
https://github.com/ultralytics/yolov5/blob/4c409332667477560200958b513b958bb8fdef71/utils/datasets.py#L449-L451

**Comment by abatiSon** [comment]
I said Glenn definitely did something like this :)
Thank you Glenn

**Comment by almgwary** [comment]
I tried it but it is not working
while running detect.py file

```
include_class = [1,2,3,4,6,8,17,18,19,20,21 ]  # filter labels to include only these classes (optional)
include_class_array = np.array(include_class).reshape(1, -1)
```

@glenn-jocher

**Comment by glenn-jocher** [comment]
@almgwary this issue relates to training
