### ISSUE TITLE
got missing from current font warning when train Chinese names images

### ISSUE THREAD

**Issue by gaoyanzeng** [ultralytics/yolov5#6522]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

Got warning as below:
metrics.py:199: UserWarning: Glyph 31888 (\N{CJK UNIFIED IDEOGRAPH-7C90}) missing from current font.
  fig.savefig(Path(save_dir) / 'confusion_matrix.png', dpi=250)

All I changed is in the ./data/coco128.yaml as below:
# Classes
nc: 4  # number of classes
names: ['翘头剪', '直剪', '止血钳', '组织钳']  # class names

### Environment

OS: Windows 11
Python: 3.9.5

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@gaoyanzeng warnings are not errors and can be safely ignored if they do not impact performance. Does this cause any problems in your workflow?

**Comment by glenn-jocher** [comment]
@gaoyanzeng I investigated a bit, seems like Unicode Arial.ttf is not downloading as it should for Chinese fonts usage. I'll add a TODO to investigate further.

**Comment by glenn-jocher** [comment]
<img width="2098" alt="Screenshot 2022-02-03 at 12 31 08" src="https://user-images.githubusercontent.com/26833433/152334972-443639d0-e10b-4147-9545-261a9399a7b0.png">

**Comment by gaoyanzeng** [comment]
thank you very much

**Comment by gaoyanzeng** [comment]
It can't plot chinese correctly when use "fig.savefig(Path(save_dir) / 'confusion_matrix.png', dpi=250)" in the 191 line of utils/metrics.py
![图片](https://user-images.githubusercontent.com/2005046/152355200-c82a676a-9880-441b-8954-8cbab974b44b.png)

**Comment by glenn-jocher** [comment]
@gaoyanzeng yeah I see that. It looks like PIL image plotting with Chinese fonts is working correctly now after some updates in #6526 but matplotlib plotting is separate and needs to specify Arial.Unicode.tty as well. I should have a fix for this soon.

**Comment by glenn-jocher** [comment]
TODO: Fix matplotlib plots for Chinese characters

**Comment by gaoyanzeng** [comment]
Thank you very much, looking forward to your work fix this problem.

**Comment by gaoyanzeng** [comment]
It draw correctly in other *.py file without font settings of matplotlib. But can't savefig correctly with Chinese labels int the metrics.py
![image](https://user-images.githubusercontent.com/2005046/152510487-0839c268-517f-400f-bc9b-ac49a1795eda.png)

**Comment by gaoyanzeng** [comment]
I found that when I set the matplotlib 'font.sans-serif', the font missing warnning disappeared. But the labels still messy in the result images.
![图片](https://user-images.githubusercontent.com/2005046/152517487-645a2d06-75aa-4cd2-ae70-39f10e5d9ced.png)

And the model summary's class name is messy. May be the chinese labels are not encoded correctly
![图片](https://user-images.githubusercontent.com/2005046/152517363-73b8779a-1734-4bfd-a977-eaa0c323324f.png)

**Comment by glenn-jocher** [comment]
@gaoyanzeng can you paste the code for your reproducible matplotlib Chinese plotting example? 

Maybe the YOLOv5 matplotlib settings here are affecting the Chinese characters:
https://github.com/ultralytics/yolov5/blob/079b36d72ba2ef298f7ae4dc283d8c7975eb02f6/utils/plots.py#L24-L28

**Comment by gaoyanzeng** [comment]
I mean when print the result before the matplotlib is not correcttly. As below
![image](https://user-images.githubusercontent.com/2005046/152642257-876fbff8-240c-45db-b796-bfd1a6c918c0.png)

**Comment by glenn-jocher** [comment]
> It draw correctly in other *.py file without font settings of matplotlib. But can't savefig correctly with Chinese labels int the metrics.py ![image](https://user-images.githubusercontent.com/2005046/152510487-0839c268-517f-400f-bc9b-ac49a1795eda.png)

Yes but can you send the the main.py script you show above please? Thanks!

**Comment by glenn-jocher** [comment]
@gaoyanzeng about the indentation issues maybe if we place this data into a pandas dataframe and then print() it pandas might resolve the indentation issues. Right now the printing is done manually here:
https://github.com/ultralytics/yolov5/blob/e1a6a0b10008b91d9970d22c397a0f03533ebca5/val.py#L261-L269

**Comment by gaoyanzeng** [comment]
@glenn-jocher Maybe, It load the *.yaml file imcorrectly when there are chinese characters in the *.yaml file?

**Comment by gaoyanzeng** [comment]
When I set chinese classes names in the coco128.yaml, then load the file should set the encoding tobe UTF-8, 
![image](https://user-images.githubusercontent.com/2005046/152646526-00c02ba6-271b-421f-bfdf-94e279ab35c9.png)
Then,  the chinese classes names be right.
![image](https://user-images.githubusercontent.com/2005046/152646687-5c25965e-4248-4728-94e0-83e7cb3d59f2.png)
Thank you very much. @glenn-jocher

**Comment by glenn-jocher** [comment]
You're welcome, @gaoyanzeng! It's great to hear that setting the encoding to UTF-8 worked for you. Let me know if there's anything else I can assist you with. Have a great day!
