### ISSUE TITLE
Train multi-class data as single-class

### ISSUE THREAD

**Issue by abatiSon** [ultralytics/yolov5#6524]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Here, I think the single class gives the highest result.
If it gives us all the classes it singularizes as a group, can't we go to multi-label here?

**Comment by glenn-jocher** [comment]
@abatiSon obviously single-class and multi-class are mutually exclusive, not sure what you're asking.

**Comment by abatiSon** [comment]
![koltuk](https://user-images.githubusercontent.com/95738656/152335263-9f56e9e0-3c0a-4a02-b83a-906e2b710641.png)
There are nested classes here.
class 1, class 2, class 3.
Can it give us the intersections of different groups as a class group?

**Comment by abatiSon** [comment]
Class grup 1 : class 1, class 2, class 3
Class grup 2: class 1, class5
