### ISSUE TITLE
Train without cached images?

### ISSUE THREAD

**Issue by peijason** [ultralytics/yolov5#653]
Some times, my training is stopped by me intentionally. And it seems there are still some cached images under somewhere. I actually just wanna change another bunch of images for training, instead of using those cached ones. Is there such a argument like `--no-cache`?

Cheers

**Comment by glenn-jocher** [comment]
@peijason no caching is the default. You don't have to do anything.

**Comment by jeffhwang02** [comment]
-- cache false
