### ISSUE TITLE
AttributeError: 'DetectMultiBackend' object has no attribute 'size'

### ISSUE THREAD

**Issue by ThiruRJST** [ultralytics/yolov5#6534]
I tried to get the shapes of the tensors of the `yolov5s` model as it is needed for me. 
I used `torchsummary` package but it gave an error **List object does not have attribute size**

I checked `hubconf.py`, it was returning torch model but when i printed type(model), It provided `DetectMultiBackend`, This model was having all parent torch model functions except the `size` attribute.

Is there a way to know the output shape of tensor of the yolov5 models?

**Comment by glenn-jocher** [comment]
@ThiruRJST the YOLOv5 DetectMultiBackend() class is here:
https://github.com/ultralytics/yolov5/blob/9bc72a3ac2253b96b006baaacf099ca4ace31a61/models/common.py#L278-L294

Generally in inference mode YOLOv5 models will output a shape of (batch-size, 25200, 85). You can use Netron to introspect models.

**Also your error is very generic**, it's just a python message telling you that you tried to get an attribute that doesn't exist on a list:

```bash
[1,2,3].size
Traceback (most recent call last):
  File "/Users/glennjocher/PycharmProjects/yolov5/venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-14-36aab76b828d>", line 1, in <module>
    [1,2,3].size
AttributeError: 'list' object has no attribute 'size'
```
