### ISSUE TITLE
AttributeError: module 'tensorflow._api.v2.lite' has no attribute 'load_delegate'

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/yolov5#6535]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Export

### Bug

@zldrobit I think recent changes to EdgeTPU inference created a bug where `load_delegate` import was attempted from `tensorflow.lite.load_delegate` instead of `tensorflow.lite.experimental.load_delegate` causing this error message:
```
AttributeError: module 'tensorflow._api.v2.lite' has no attribute 'load_delegate'
```
If I attempt a fix in https://github.com/ultralytics/yolov5/pull/6536 I still see a new error message on EdgeTPU inference:
```
AttributeError: 'Delegate' object has no attribute '_library'
```

### Environment

YOLOv5 🚀 v6.0-231-g9bc72a3 torch 1.10.0+cu111 CPU

### Minimal Reproducible Example

In Colab Notebook
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

```python
!python export.py --include edgetpu
!python detect.py --weights yolov5s-int8_edgetpu.tflite
```

### Additional

Will submit PR with fix for original error.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@zldrobit ok I've merged #6536 which I think fixes original issue.

I think the second error is just because I didn't install Edge TPU runtime in Colab. Is it possible to run Edge TPU models without Edge TPU accelerator plugged into the machine? I'm asking because I have a separate branch that I'm working on that is creating a new benchmarks.py to benchmark all of the export formats (currently CPU-only), i.e.:
https://github.com/ultralytics/yolov5/blob/updates/benchmarks/utils/benchmarks.py

```
benchmarks: weights=/usr/src/yolov5/yolov5s.pt, imgsz=640, batch_size=1, data=/usr/src/yolov5/data/coco128.yaml
...

Benchmarks complete (782.19s)
                   Weights  mAP@0.5:0.95  Inference time (ms)
0               yolov5s.pt      0.407554           102.777191
1      yolov5s.torchscript      0.402908           132.848348
2             yolov5s.onnx      0.402908            89.061137
3   yolov5s_openvino_model      0.402908            67.093970
4                   engine           NaN                  NaN
5                   coreml           NaN                  NaN
6      yolov5s_saved_model      0.402908           133.983964
7               yolov5s.pb      0.402908           101.405423
8      yolov5s-fp16.tflite      0.402851           502.289245
9                  edgetpu           NaN                  NaN
10                    tfjs           NaN                  NaN
```

**Comment by Rishav-hub** [comment]
Hello @glenn-jocher I am facing similar issue `ModuleNotFoundError: No module named 'tensorflow.lite.experimental.load_delegate'. `when trying to do this `!python /content/yolov5/detect.py --weights /content/yolov5s-fp16.tflite`.. Any fix?

Tensorflow Version -: 2.7.0
Environment -: colab

**Comment by glenn-jocher** [comment]
@Rishav-hub yes I think we need to follow the official example more closely, which does work in my tests:
https://www.tensorflow.org/api_docs/python/tf/lite/experimental/load_delegate

**Comment by Rishav-hub** [comment]
@glenn-jocher but what is causing this issue do I need to make changes in the common.py in yolov5. Is there any permanent fix you suggest or do I need to make changes in the source code?

**Comment by glenn-jocher** [comment]
@Rishav-hub we need a PR to update the repo with a fix. It's difficult for me to debug since I don't have any Edge TPU devices to test on. The requirements are:

- Prefer Edge TPU Runtime to TF if installed
- Fix load_delegate() issues
- Keep code as concise as possible

The area of the code that needs updating is:
https://github.com/ultralytics/yolov5/blob/cba4303d323352fc6d76730e15459b14498a9e34/models/common.py#L376-L390

**Comment by glenn-jocher** [comment]
@Rishav-hub good news 😃! Your original issue may now be fixed ✅ in PR #6542. This PR fixes TF module loading **only** for **Edge TPU** TFLite exports, i.e. `python detect.py --weights yolov5s-int8_edgetpu.tflite` 

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by zldrobit** [comment]
@glenn-jocher Edge TPU models cannot be run on CPU only, because of the Edge TPU operator.

EDIT: If there is no delegate given when initializing TFLite interpreter, the output message running an Edge TPU model without an accelerator is as follows,
![image](https://user-images.githubusercontent.com/3896992/152904315-9d3203a7-f4ca-40e6-9f27-4c15f08b2b31.png)

**Comment by glenn-jocher** [comment]
@zldrobit ok got it!

**Comment by glenn-jocher** [comment]
> @glenn-jocher Edge TPU models cannot be run on CPU only, because of the Edge TPU operator.
> 
> EDIT: If there is no delegate given when initializing TFLite interpreter, the output message running an Edge TPU model without an accelerator is as follows, ![image](https://user-images.githubusercontent.com/3896992/152904315-9d3203a7-f4ca-40e6-9f27-4c15f08b2b31.png)

Hopefully this won't happen unless a user renames the file and removes the _edgetpu part.
