### ISSUE TITLE
Resizing

### ISSUE THREAD

**Issue by st162053** [ultralytics/yolov5#6537]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, 

I have a question about different image sizes. How exactly does YOLO deal with resizing images? With stretching and keeping the ratio or with drawing/adding grey,.. around the smaller picture?

Thanks!

**Comment by glenn-jocher** [comment]
@st162053 YOLOv5 uses letterboxing (padding) resizing. Aspect ratio is maintained.
