### ISSUE TITLE
YoloV5 with GANs

### ISSUE THREAD

**Issue by aryan51k** [ultralytics/yolov5#6538]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

I was wondering why can't we provide inbuilt GANs in yolov5. I think this will boost accuracy of the model very much 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@aryan51k hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by z1zw** [comment]
I have do it!

**Comment by glenn-jocher** [comment]
@z1zw great job! Thank you for your contribution to YOLOv5! Your efforts are much appreciated. Keep up the good work!
