### ISSUE TITLE
Is YOLOv5 able to detect a specific number of classes according to the project's need, like just 2 or 3 classes?

### ISSUE THREAD

**Issue by HeitorDC** [ultralytics/yolov5#6540]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I'm using YOLOv5 in my project and I have a question. If I use "--classes " it could detect one type of class, but is there anyway that I can detect more than one type, like 2 or 3 different types? I've already tried "-- classes 0 1" or "-- classes [0] [1]" but without success. Thanks for the help!

**Comment by glenn-jocher** [comment]
@HeitorDC use examples are in argparser help:
https://github.com/ultralytics/yolov5/blob/079b36d72ba2ef298f7ae4dc283d8c7975eb02f6/detect.py#L231
```bash
python detect.py --classes 0 27
```

<img width="1357" alt="Screenshot 2022-02-04 at 17 05 01" src="https://user-images.githubusercontent.com/26833433/152561950-d2defca2-f11e-4507-a9ca-cf214792497a.png">

**Comment by HeitorDC** [comment]
Thaks for the help, @glenn-jocher !! It worked!
