### ISSUE TITLE
TensorRT export issue IndexError

### ISSUE THREAD

**Issue by Rishav-hub** [ultralytics/yolov5#6543]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Export

### Bug

When trying this command `!python /content/yolov5/export.py --weights yolov5s.pt --include engine`

Getting this issue -:
`Traceback (most recent call last):
  File "/content/yolov5/export.py", line 531, in <module>
    main(opt)
  File "/content/yolov5/export.py", line 526, in main
    run(**vars(opt))
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/content/yolov5/export.py", line 485, in run
    f"\nResults saved to {colorstr('bold', file.parent.resolve())}"
IndexError: list index out of range`

### Environment

- Tensorflow Version -: 2.7.0
- Colab Environment

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Rishav-hub 👋 Hello! Thanks for asking about YOLOv5 🚀 **TensorRT Export**. [NVIDIA TensorRT](https://developer.nvidia.com/tensorrt) format can accelerate inference by optimizing a `*.engine` model to a specific GPU and hardware backend resulting in up to 5X faster speeds on CUDA devices compared to PyTorch inference.

### Install TensorRT

See our Notebooks Appendix section for examples: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>. For more details see https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing-pip

```python
pip install -U nvidia-tensorrt --index-url https://pypi.ngc.nvidia.com  # install
```

### Export YOLOv5 TensorRT Model

Run `export.py --include engine` to export a TensorRT model
```bash
python export.py --weights yolov5s.pt --include engine --imgsz 640 640 --device 0  # export
```

### Inference

Run `detect.py --weights *.engine` to run a TensorRT model
```bash
python detect.py --weights yolov5s.engine --imgsz 640 640 --device 0  # inference
```

### Profiling Results

Below are profiling results by running `detect.py` with PyTorch CPU, PyTorch GPU, and TensorRT GPU. TensorRT inference speeds should be about 2-5x faster than PyTorch GPU inference.

<img width="1474" alt="Screenshot 2021-12-15 at 14 00 54" src="https://user-images.githubusercontent.com/26833433/146191722-86228a33-04a7-450f-9869-bd5c91baccaa.png">

Good luck 🍀 and let us know if you have any other questions!
