### ISSUE TITLE
Excluding Some Classes from Testing

### ISSUE THREAD

**Issue by Rusab** [ultralytics/yolov5#6545]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is it possible to easily exclude some classes when generating the confusion matrix on a custom test set ? 

For example, I want to show the confusion matrix for only the classes that are present in the test set. In this image I had only 10 of the 26 classes in on my test set so the rest of the blocks came out blank. 

![image](https://user-images.githubusercontent.com/29260943/152650696-8496c17a-435e-4fc1-a288-9fbf5e144675.png)

**Comment by abatiSon** [comment]
https://github.com/ultralytics/yolov5/issues/6520
