### ISSUE TITLE
About number of images/instances to train

### ISSUE THREAD

**Issue by KentaItakura** [ultralytics/yolov5#6549]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I am using this repo for training YOLOv5. This repo is super useful and helpful!! I am really appreciate your work. 

In this wiki, the number of image more than 1500 and number of instances more than 10000 is recommended. Do you have a reference/paper for this value? I am wondering how much I should prepare annotation data for my project. 
https://github.com/ultralytics/yolov5/wiki/Tips-for-Best-Training-Results

**Comment by glenn-jocher** [comment]
@KentaItakura these per-class recommendations are based on the COCO dataset, i.e. 1M instances and 120k images divided by 80 classes.

**Comment by glenn-jocher** [comment]
See https://arxiv.org/abs/1405.0312
