### ISSUE TITLE
The wieghts of backbone in YOLOv5-l

### ISSUE THREAD

**Issue by XuecWu** [ultralytics/yolov5#6550]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I want to know where could I find the weights of backbone in YOLOv5-l？ I have checked all of the releases,but I failed. Thak you.

**Comment by zhiqwang** [comment]
Hi @XuecWu 

There is no backbone defined in YOLOv5, I guess the commonly known backbone corresponds to the down-sampling part in the YOLOv5 design. You can truncate the yolov5 models and treat the part before the following `SPPF` as the backbone.

https://github.com/ultralytics/yolov5/blob/dc7e093071fc75221ca3627ec1e385c79eeaef72/models/yolov5l.yaml#L13-L24

**Comment by XuecWu** [comment]
@zhiqwang  Thank you for your reply! I got it.
