### ISSUE TITLE
Per channel outputs?

### ISSUE THREAD

**Issue by joangog** [ultralytics/yolov5#6551]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have a question regarding the outputs of YOLOv5. First of all I'm training YOLOv5s with 3 classes and img_size = 608. In the model graph we can see the outputs for the 3 different size scales.
![Screenshot from 2022-02-06 18-10-46](https://user-images.githubusercontent.com/45146541/152690204-3c128f97-ddec-4a98-b6d2-feb7dc778de0.png)

For example for the first scale it's 3 x 76 x 76 x 8. I get the N/8 x N/8 x K+4+1 part, where N is the img_size, K is the class probabilities, 4 is the coords and 1 is confidence, but the 3 is supposed to be for the RGB? Does the model predict the outputs of each region for each channel separately?

**Comment by glenn-jocher** [comment]
@joangog dimensions are (batch-size, anchor, x-grid, y-grid, (xywh, confidence, cls_0... cls_n))

**Comment by joangog** [comment]
> @joangog dimensions are (batch-size, anchor, x-grid, y-grid, (xywh, confidence, cls_0... cls_n))

Aah the three anchors for each head as in the yaml file! Now I see... Thanks!
