### ISSUE TITLE
How is training handled for different class numbers?

### ISSUE THREAD

**Issue by ubicray** [ultralytics/yolov5#6558]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

So I just further trained a COCO pretrained yolov5m.pt with a modified Argoverse

Issue is, Argoverse has 8 classes compared to COCO's 80
Afterwards when I tried to validate with COCO I got errors as the index was going out of bounds in regards to the class number

How should the process be in regards to training with different number of classes? Was my training ruined with different class amounts?

Thanks for the help!

**Comment by glenn-jocher** [comment]
@ubicray you just train and val on your custom dataset. No other steps. 

```bash
python train.py --data data.yaml
python val.py --weights path/to/best.pt --data data.yaml
```

**Comment by ubicray** [comment]
> @ubicray you just train and val on your custom dataset. No other steps.
> 
> ```shell
> python train.py --data data.yaml
> python val.py --weights path/to/best.pt --data data.yaml
> ```

Hi @glenn-jocher thanks for the reply and all you do for this project!

What I'm trying to achieve is to train the pretrained yolov5m.pt with Argoverse dataset and then validate it with COCO
I'll write what I did:
`python train.py --data Argoverse.yaml --weights yolov5m.pt `
`python val.py --data coco.yaml --weights yolov5m_rainy.pt --img 640`

And I get this:

> val: Scanning '../datasets/coco/val2017.cache' images and labels... 4952 found, 
>                Class     Images     Labels          P          R     mAP@.5 mAP@Exception in thread Thread-3:
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.9/threading.py", line 910, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/elmar/Desktop/deraining_thesis/transfer_learning_yolov5/yolov5/utils/plots.py", line 205, in plot_images
>     cls = names[cls] if names else cls
> KeyError: 22
>                Class     Images     Labels          P          R     mAP@.5 mAP@Exception in thread Thread-5:
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.9/threading.py", line 910, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/elmar/Desktop/deraining_thesis/transfer_learning_yolov5/yolov5/utils/plots.py", line 205, in plot_images
>     cls = names[cls] if names else cls
> KeyError: 30
>                Class     Images     Labels          P          R     mAP@.5 mAP@Exception in thread Thread-7:
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.9/threading.py", line 910, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/elmar/Desktop/deraining_thesis/transfer_learning_yolov5/yolov5/utils/plots.py", line 205, in plot_images
>     cls = names[cls] if names else cls
> KeyError: 8
>                Class     Images     Labels          P          R     mAP@.5 mAP@
> Traceback (most recent call last):
>   File "/home/elmar/Desktop/deraining_thesis/transfer_learning_yolov5/yolov5/val.py", line 360, in <module>
>     main(opt)
>   File "/home/elmar/Desktop/deraining_thesis/transfer_learning_yolov5/yolov5/val.py", line 334, in main
>     run(**vars(opt))
>   File "/home/elmar/.local/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
>     return func(*args, **kwargs)
>   File "/home/elmar/Desktop/deraining_thesis/transfer_learning_yolov5/yolov5/val.py", line 236, in run
>     p, r, ap, f1, ap_class = ap_per_class(*stats, plot=plots, save_dir=save_dir, names=names)
>   File "/home/elmar/Desktop/deraining_thesis/transfer_learning_yolov5/yolov5/utils/metrics.py", line 76, in ap_per_class
>     plot_mc_curve(px, f1, Path(save_dir) / 'F1_curve.png', names, ylabel='F1')
>   File "/home/elmar/Desktop/deraining_thesis/transfer_learning_yolov5/yolov5/utils/metrics.py", line 321, in plot_mc_curve
>     ax.plot(px, y, linewidth=1, label=f'{names[i]}')  # plot(confidence, metric)
> KeyError: 8

**Comment by glenn-jocher** [comment]
@ubicray train and val must be done on the same data.yaml, otherwise yes the expected result will be an error.

**Comment by ubicray** [comment]
> @ubicray train and val must be done on the same data.yaml, otherwise yes the expected result will be an error.

One last question:
If I'm trying to train based on Argoverse data, do I need to start from scratch (As I see that the class names are not compatible with COCO) or training based on pretrained weights with --data Argoverse.yaml should just work ?

**Comment by glenn-jocher** [comment]
@ubicray start from pretrained weights:
```
python train.py --weights yolov5s.pt --data Argoverse.yaml
```
