### ISSUE TITLE
pt -> engine convert

### ISSUE THREAD

**Issue by ONNONS** [ultralytics/yolov5#6563]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Jetson nano environment
I am trying to change engine from pt
I entered "python3 export.py --weights XXX.pt --include engine"
error has occured

export: data=data/coco128.yaml, weights=['doe3.pt'], imgsz=[640, 640], batch_size=1, device=cpu, half=False, inplace=False, train=False, optimize= False, int8=False, dynamic=False, simplify=False, opset=12, verbose=False, workspace=4, nms=False, agnostic_nms=False, topk_per_class=100, topk_all=100, iou_thres=0.45, conf_thres=0.25, include=['engine']
YOLOv5 🚀 2022-2-5 torch 1.7.0 CPU

Fusing layers...
Model Summary: 190 layers, 5233482 parameters, 0 gradients, 14.4 GFLOPs

PyTorch: starting from doe3.pt with output shape (1, 24000, 7) (10.7 MB)

ONNX: starting export with onnx 1.10.2...
ONNX: export failure: Unsupported ONNX opset version: 13

TensorRT: starting export with TensorRT 8.0.1.6...

TensorRT: export failure: export running on CPU but must be on GPU, i.e. `python export.py --device 0`
Traceback (most recent call last):
  File "export.py", line 526, in <module>
    main(opt)
  File "export.py", line 521, in main
    run(**vars(opt))
  File "/home/.local/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "export.py", line 479, in run
    LOGGER.info(f'\nExport complete ({time.time() - t:.2f}s)'
IndexError: list index out of range

**Comment by zhiqwang** [comment]
Seems that the PyTorch 1.7.0 version is a little outdated, it is better to upgrade the current PyTorch version to 1.9+ or use the intermediate exported ONNX model to convert to the TensorRT engine.

**Comment by glenn-jocher** [comment]
@ONNONS error message you showed is self explanatory:
```
TensorRT: export failure: export running on CPU but must be on GPU, i.e. python export.py --device 0
```

**Comment by glenn-jocher** [comment]
@ONNONS good news 😃! We've improved ✅ error handling for zero-export cases in PR #6569. You should now see a clearer error message on export failure, i.e.:

<img width="1132" alt="Screenshot 2022-02-08 at 12 15 16" src="https://user-images.githubusercontent.com/26833433/152976585-8acd00a7-2afc-4d92-bf6a-8feda8643689.png">

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by njustczr** [comment]
on jetson nano,
![image](https://user-images.githubusercontent.com/30426320/153555741-92e0e8f7-b9f7-4714-91eb-65fbea7d3955.png)
so i can not export *.pt file to *.engine file

**Comment by zhiqwang** [comment]
YOLOv5's default TensorRT inference relies on the CUDA version of PyTorch:
https://github.com/ultralytics/yolov5/blob/cb2ad9f68531e6afe76326d46acf566acf8af4f9/models/common.py#L418

I guess that you can replace the data binding here to `pycuda` to reduce this dependency.

**Comment by ONNONS** [comment]
> YOLOv5's default TensorRT inference relies on the CUDA version of PyTorch:
> 
> https://github.com/ultralytics/yolov5/blob/cb2ad9f68531e6afe76326d46acf566acf8af4f9/models/common.py#L418
> 
> I guess that you can replace the data binding here to `pycuda` to reduce this dependency.

What version should I use? Pytorch ,  cuda, tensorrt, torchvision . . . Etc

**Comment by zhiqwang** [comment]
> What version should I use? Pytorch , cuda, tensorrt, torchvision . . . Etc

Hi @ONNONS , The minimum version requirements for PyTorch and torchvision should be 1.8 and 0.9, check out the official guide to install them on your CUDA device https://pytorch.org/get-started/locally/

For myself, I suggest to install the latest version of TensorRT (8.2.x), the new version of TensorRT will give you a completely different user experience.
