### ISSUE TITLE
Can I get irregular bbox with yolov5, not just rectangle?

### ISSUE THREAD

**Issue by GivanTsai** [ultralytics/yolov5#6564]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I know that we can get a retangle bbox using yolo, like this one,
<img width="300" alt="bbox" src="https://user-images.githubusercontent.com/37231239/152940975-751e6a46-9198-4c80-99d8-7a09e2c1cfb0.png">
But I want to to get a four-points irregular bbox like the following one,  what can I do for that ?
<img width="300" alt="irregular_bbox" src="https://user-images.githubusercontent.com/37231239/152941138-43fe6778-d7a1-4e02-a219-0fba1fed7e95.png">

**Comment by glenn-jocher** [comment]
@GivanTsai see PR https://github.com/ultralytics/yolov5/pull/6506
