### ISSUE TITLE
Mean average precision for images with no labels

### ISSUE THREAD

**Issue by MiladGhorbaniG** [ultralytics/yolov5#6575]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

In a test dataset, I have calculated MAP using val.py. Some images do not have labels. In this code, are these images without labels used in the MAP process or not?

**Comment by glenn-jocher** [comment]
@MiladGhorbaniG yes all images are used by train.py and val.py.
