### ISSUE TITLE
On the method of using secondary classification

### ISSUE THREAD

**Issue by Pocfeis** [ultralytics/yolov5#6585]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to know how I should use the second level classification on the code. I have tried some, but it has no effect. Is there a tutorial?

**Comment by glenn-jocher** [comment]
@Pocfeis this is a bring-your-own-model situation. Some users like the option of having a second stage filter first stage detections to reduce FPs. If you have a classifier trained on the same classes you can specify it there. Any classifier can be used here (EfficientNet, Resnet, etc.), the only requirement is that the classification and detection models are trained on the same classes. 

Also note that the current implementation is just a starting point for this two-stage experimentation, this is not a fully managed or implemented feature. There are also a number of other issues on the same topic also:
https://github.com/ultralytics/yolov5/issues?q=is%3Aissue+resnet101

See TowerScout for a deployed example of YOLOv5 paired with a second stage EfficientNet model.
https://groups.ischool.berkeley.edu/TowerScout/

<img width="1513" alt="Screenshot 2021-06-09 at 15 14 25" src="https://user-images.githubusercontent.com/26833433/121361242-6632ff80-c935-11eb-8e39-3f5e02bc50a0.png">

**Comment by Pocfeis** [comment]
Thank you for the quick reply，I downloaded a rensnet50 PTH, my idea is that the classifer branch written according to yolov5 can run smoothly, and then I will train the model. But now I find that I can't run after downloading the weight. There are the following errors. Can you give me some advice? thank you
![114905850a59514f78f96419a4cf1c7](https://user-images.githubusercontent.com/80813147/153347886-919cf8ec-672d-4236-8637-125714982e5c.jpg)
![aa07071d477d0ef5fd73f526c39eb50](https://user-images.githubusercontent.com/80813147/153347942-9e9c2cf2-5652-4484-8380-5b2106336ed2.jpg)
and device is cuda:0

**Comment by Pocfeis** [comment]
Thank you for the quick reply，I downloaded a rensnet50 PTH, my idea is that the classifer branch written according to yolov5 can run smoothly, and then I will train the model. But now I find that I can't run after downloading the weight. There are the following errors. Can you give me some advice? thank you
![5f3448670778786515ca1ff84dd36ce](https://user-images.githubusercontent.com/80813147/153348306-71faef26-068b-4114-8d92-1f82909dd0a8.jpg)
![aa07071d477d0ef5fd73f526c39eb50](https://user-images.githubusercontent.com/80813147/153348335-823a2f5a-c41c-4094-8ba3-0fb07a06f498.jpg)
and device is cuda:0

**Comment by Pocfeis** [comment]
> Thank you for the quick reply，I downloaded a rensnet50 PTH, my idea is that the classifer branch written according to yolov5 can run smoothly, and then I will train the model. But now I find that I can't run after downloading the weight. There are the following errors. Can you give me some advice? thank you ![5f3448670778786515ca1ff84dd36ce](https://user-images.githubusercontent.com/80813147/153348306-71faef26-068b-4114-8d92-1f82909dd0a8.jpg) ![aa07071d477d0ef5fd73f526c39eb50](https://user-images.githubusercontent.com/80813147/153348335-823a2f5a-c41c-4094-8ba3-0fb07a06f498.jpg) and device is cuda:0
now ,I modify the code:
![efdf372ccce417876814d6502f41106](https://user-images.githubusercontent.com/80813147/153374918-22d0edaf-04b5-41ce-8d31-e67516a52a2f.jpg)
The following error occurred：
![bd87e635f1df73bf842e0170e255d74](https://user-images.githubusercontent.com/80813147/153375134-08a4351f-11d2-41d2-bebe-ec73034fcd39.jpg)
and i set n=1000 can run .can you give me some advice?

**Comment by glenn-jocher** [comment]
@Pocfeis sorry, we don't provide resources for this. Code customizations and flexible workflows are up to users to implement with community support.

**Comment by fayezalhussein** [comment]
[glenn-jocher](https://github.com/glenn-jocher), hey dear, in two stage fashion and accessories detection and classification, can we use YOLOV5 and EfficientNet together ?

**Comment by glenn-jocher** [comment]
@fayezalhussein yes. Some users like the option of having a second stage filter first stage detections to reduce FPs. If you have a classifier trained on the same classes you can specify it there. Any classifier can be used here (EfficientNet, Resnet, etc.), the only requirement is that the classification and detection models are trained on the same classes. 

Also note that the current implementation is just a starting point for this two-stage experimentation, this is not a fully managed or implemented feature. There are also a number of other issues on the same topic also:
https://github.com/ultralytics/yolov5/issues?q=is%3Aissue+resnet101

See TowerScout for a deployed example of YOLOv5 paired with a second stage EfficientNet model.
https://groups.ischool.berkeley.edu/TowerScout/

<img width="1513" alt="Screenshot 2021-06-09 at 15 14 25" src="https://user-images.githubusercontent.com/26833433/121361242-6632ff80-c935-11eb-8e39-3f5e02bc50a0.png">

**Comment by fayezalhussein** [comment]
thank you so much
