### ISSUE TITLE
Batching without Cutting of the Labels

### ISSUE THREAD

**Issue by omidchini** [ultralytics/yolov5#6589]
I have a very specific problem for my model training. In my object detection problem, it is vital that the WHOLE object is present, not a partial cut. Since I am trying to detect "crossed checkboxes", and partial checkboxes are indistinguishable from not checked boxes (see example)
![Screenshot 2022-02-09 131726](https://user-images.githubusercontent.com/12323634/153199549-38b57c0e-9d23-474e-b6c6-2e8fc2a30d10.png)
The left side is invalid for the training, but only the right is valid for training. It is vital that the Boxes do not get cut off while batching. How can I manage that?

**Comment by glenn-jocher** [comment]
@omidchini you can alter label candidate criteria for training here:
https://github.com/ultralytics/yolov5/blob/9c513ca62942ba34306b9f5be3d0f0110b4435ec/utils/augmentations.py#L272-L277
