### ISSUE TITLE
Label error while training with 2017 coco dataset. labels missing

### ISSUE THREAD

**Issue by AlbertMP** [ultralytics/yolov5#659]
I downloaded the `coco2017labels.zip` from google drive and then unzipped it. When I tried to train the model with the entire coco dateset, the code reports error below that some images are missing in both train and val folder.

```
Optimizer groups: 62 .bias, 70 conv.weight, 59 other
Scanning labels ../coco/labels/train2017.cache (117266 found, 0 missing, 1021 empty, 0 duplicate, for 118287 images): 100%|█████████████████████████████████████| 118287/118287 [00:09<00:00, 13110.03it/s]
Scanning labels ../coco/labels/val2017.cache (4952 found, 0 missing, 48 empty, 0 duplicate, for 5000 images): 100%|█████████████████████████████████████████████████| 5000/5000 [00:00<00:00, 13120.22it/s]
```

I checked the `../coco/labels/train2017` and `../coco/labels/val2017` and found they just contain 117266 and  4952 labels.

Is the label files missing?

**Comment by NanoCode012** [comment]
My coco dataset reports the same number of label files. Could you check that you downloaded the entirety of the dataset? Around 20 GB. Did you download using the `get_coco2017.sh` file?

**Comment by AlbertMP** [comment]
> My coco dataset reports the same number of label files. Could you check that you downloaded the entirety of the dataset? Around 20 GB. Did you download using the `get_coco2017.sh` file?

Yes. My `train2017` folder contains 118287 pictures and `val2017` folder contains 5000 pictures. It's the same as the number of dataset. 
But some label files are missing I found when I unzipped the `coco2017labels.zip` file. That's  why causing the problem I think.

You can check the number of label files, is yours equal to the number of pictures in train and val folders?

**Comment by NanoCode012** [comment]
Train labels : 117266 
Valid labels : 4952
Train pic : 118287
Valid pic : 5000

However, I can run the code without any problem. I am not sure if the lack of labels just means that there is nothing to be detected in a picture.

Edit : Do you have problem running the code?

**Comment by glenn-jocher** [comment]
@NanoCode012 @AlbertMP not all images require labels. COCO has over 1000 unlabelled images.
