### ISSUE TITLE
自定义数据集

### ISSUE THREAD

**Issue by shelly-xue** [ultralytics/yolov5#6592]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

您好，我使用的是自己数据集，在run文件夹中生成的best.pt和last.pt是基于epoch=3的，假设我训练的epoch设置为100，请问怎么修改代码可以保存100epoch时的best.pt和last.pt呢？非常感谢

**Comment by lee1221ee** [comment]
你訓練時參數 `--epoch` 設定 100 所儲存的 last.pt，就是第 100 代結束時的 Weights 阿。
