### ISSUE TITLE
Speed and study option in val.py

### ISSUE THREAD

**Issue by DP1701** [ultralytics/yolov5#6593]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, 

what data uses the task options "Speed" and "Study" in val.py? Validation or test data?

I also don't understand the use of the study option. What can it be used for?

**Comment by glenn-jocher** [comment]
@DP1701 `val.py --task study` is what I use to create the README tables, i.e.:

<img width="886" alt="Screenshot 2022-02-09 at 22 58 52" src="https://user-images.githubusercontent.com/26833433/153297244-e6acff0b-7136-4431-ba9b-b06113a2e772.png">
