### ISSUE TITLE
UnboundLocalError: local variable 'half' referenced before assignment

### ISSUE THREAD

**Issue by yasindagasan** [ultralytics/yolov5#66]
I just come across this issue recently. It just appeared to be happening after the changes in the test.pt. It was working well before the last changes.

Traceback (most recent call last):
  File "/home/Yolov5_github/yolov5-master/train.py", line 400, in <module>
    train(hyp)
  File "/home/Yolov5_github/yolov5-master/train.py", line 306, in train
    fast=ni < n_burn)
  File "/home/Yolov5_github/yolov5-master/test.py", line 89, in test
    img = img.half() if half else img.float()  # uint8 to fp16/32
UnboundLocalError: local variable 'half' referenced before assignment

I was just running the below code to train:

python3 train.py \
  --img-size 1280\
  --batch 4 \
  --epochs 2000 \
  --data ./data/custom/test_81.yaml \
  --cfg ./models/custom/yolov5l.yaml \
  --weights '' \
  --name test_81_yolov5l \
  --cache \
  --rect

```

 - OS: Ubuntu 20.04 LTS
 - GPU [RTX 2070 ]

**Comment by RobinhoodKi** [comment]
Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
   345/549     2.61G   0.05453   0.05613   0.02927    0.1399        75       640: 100%|██████████████| 7393/7393 [15:10<00:00,  8.12it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|████| 313/313 [01:07<00:00,  4.60it/s]
                 all       5e+03    3.63e+04       0.504       0.451       0.442       0.247

**Comment by glenn-jocher** [comment]
@yasindagasan thanks for the bug report. Yes, we recently pushed a commit to default testing to FP16. I will try to reproduce your error in colab.

**Comment by glenn-jocher** [comment]
@yasindagasan ok, yes I am able to reproduce. I will push a fix for this shortly.

**Comment by yasindagasan** [comment]
awesome thanks

**Comment by glenn-jocher** [comment]
@yasindagasan you're welcome, you should be all set now!

I suppose I should do a better job of running tests before commits...

**Comment by yasindagasan** [comment]
> @yasindagasan ok, yes I am able to reproduce. I will push a fix for this shortly.

thanks very much!

**Comment by yasindagasan** [comment]
> @yasindagasan you're welcome, you should be all set now!
> 
> I suppose I should do a better job of running tests before commits...

It's all good mate, cheers!

**Comment by tudoupaigu946** [comment]
do you solve this,I have same problem
