### ISSUE TITLE
yolov5 on Intel Iris Xe Max Graphics Card

### ISSUE THREAD

**Issue by samilarinc** [ultralytics/yolov5#6601]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi there, I am trying to train yolov5 algorithm with my custom dataset. I am working on Intel DevCloud platform and it provides me Intel Iris Xe Max graphics cards. However, I did not find any prior trials with yolov5 on Intel graphics cards. Is there a way to achieve it? (like a feature of yolov5 or a community trial) 

Thanks in advance

**Comment by glenn-jocher** [comment]
@samilarinc we support OpenVINO exports which can be run on CPU or Myriad hardware from Intel, i.e. https://www.intel.com/content/www/us/en/products/details/processors/movidius-vpu/movidius-myriad-x.html

On the training side there is only current support for CPU and GPU (CUDA) devices, with experimental support for AMD GPUs.

I think this is the first mention I've seen of Intel Iris graphics cards.

**Comment by samilarinc** [comment]
Thank you for fast reply and informative answer. I will try to use Intel Iris Discrete Graphics as accelerator for my other models. Maybe I can find a way to implement it on Yolo!

**Comment by glenn-jocher** [comment]
@samilarinc if you find a way definitely let us know how!
