### ISSUE TITLE
requirements.txt installation taking too long/not finishing

### ISSUE THREAD

**Issue by isspid** [ultralytics/yolov5#6602]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Export, Other

### Bug

I am trying to install the dependencies using `pip install -r requirements.txt` but the process is taking too long. In fact I have not seen it finish after waiting for almost an hour. 

Screenshot 1
![image](https://user-images.githubusercontent.com/91065022/153404444-0e93a239-362e-4465-b971-a2850cd1eafb.png)

The command I run it with
![image](https://user-images.githubusercontent.com/91065022/153404529-7ca8d618-0876-4094-b330-7f02306cb256.png)

### Environment

Google Colab

### Minimal Reproducible Example

![image](https://user-images.githubusercontent.com/91065022/153404633-886c4b42-7965-4fee-bb08-073135b47c12.png)

### Additional

I uncommented the lines after "#Export" in the requirements file.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@isspid for export dependency installs:
https://github.com/ultralytics/yolov5/blob/364b7c511146a1c68f2477c8f1df9bea71516e7e/export.py#L19-L22
