### ISSUE TITLE
Quantization for torchscript export

### ISSUE THREAD

**Issue by mikel-brostrom** [ultralytics/yolov5#6609]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

According to the deployment workflow in pytorch for mobile devices (https://pytorch.org/mobile/home/) quantization is optional and would of course be nice to add as an option for this specific export method. The proposed change to `export_torchscript` would look like this:

```python
def export_torchscript(model, im, file, quantize, optimize, prefix=colorstr('TorchScript:')):
    # YOLOv5 TorchScript model export
    try:
        LOGGER.info(f'\n{prefix} starting export with torch {torch.__version__}...')
        f = file.with_suffix('.torchscript')

        ts = torch.jit.trace(model, im, strict=False)
        d = {"shape": im.shape, "stride": int(max(model.stride)), "names": model.names}
        extra_files = {'config.txt': json.dumps(d)}  # torch._C.ExtraFilesMap()
        if optimize:  # https://pytorch.org/tutorials/recipes/mobile_interpreter.html

            if quantize:
                torch.backends.quantized.engine = "qnnpack"
                qconfig = torch.quantization.default_qconfig
                model.qconfig = qconfig
                model = torch.quantization.prepare(model)
                model = torch.quantization.convert(model)

            optimize_for_mobile(ts)._save_for_lite_interpreter(str(f), _extra_files=extra_files)
        else:
            ts.save(str(f), _extra_files=extra_files)

        LOGGER.info(f'{prefix} export success, saved as {f} ({file_size(f):.1f} MB)')
        return f
    except Exception as e:
        LOGGER.info(f'{prefix} export failure: {e}')
```

### Use case

Further optimization for mobile devices

### Additional

xnnpack is not an option here due to the following error

```bash
export failure: xnnpack is not a valid value for quantized engine
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@mikel-brostrom hi, thank you for your feature suggestion on how to improve YOLOv5 🚀! Yes this seems like a good idea. We have --half and --int8 arguments that apply to certain exports, but not torchscript.

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
