### ISSUE TITLE
why the model size if saved yolov5s.pt is 55.6MB

### ISSUE THREAD

**Issue by Linranran** [ultralytics/yolov5#661]
why the model size of saved yolov5s.pt is 55.6MB. it should be 14MB?

**Comment by tkianai** [comment]
Usually, your training process is not complete, this would contain not only model parameters, but also optimizer for resume. At the end of training, it will remove the optimizer, more details refered to `strip_optimizer` function.

**Comment by wudashuo** [comment]
The final model size would be smaller. While training the yolov5l.pt file was about 900MB~1GB. When I finished training, the pt file is 450MB. I suppose that yolov5s would be the same.
Translate: 都是国人，用中文说吧，训练过程中模型文件会比较大，估计存储了训练的相关信息，等你训练完成后，最后的权重文件会缩小大约一半

**Comment by Linranran** [comment]
@tkianai ok,thanks

**Comment by Linranran** [comment]
@wudashuo 我去，我以为什么情况呢。我是得到过14mb的模型，后面fineturn  发现模型就变成55mb了，搞得一头雾水的，哈哈

**Comment by NanoCode012** [comment]
See #253 and #124 . In other words, you need to train till its finish or call the `utils.strip_optimizer` function on the model.

**Comment by Linranran** [comment]
Thank you！i know the reason just now



发自我的iPhone


------------------ Original ------------------

**Comment by ZeKunZhang1998** [comment]
老哥yolov5s和x的map大概差多少呀
