### ISSUE TITLE
Filter out and save FP+FN  samples for analysis

### ISSUE THREAD

**Issue by agupt013** [ultralytics/yolov5#6620]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Thanks for the amazing work!
I wanted to ask if there is a way to filter out incorrect results and save those images? 
It will be helpful to analyze where the model is failing.

**Comment by glenn-jocher** [comment]
@agupt013 do you mean on val.py?

**Comment by agupt013** [comment]
Yes, like saving the crops it would be great to have fp and fn images for
each class.

**Comment by glenn-jocher** [comment]
@agupt013 I'm not sure what you mean. Every image has FPs and FNs. When computing mAP --conf is set near zero to capture the entire mAP curve, so every image will have thousands of low confidence FPs (which is normal).

**Comment by glenn-jocher** [comment]
@agupt013 I think what you mean to say is that you'd like to see mAP on a per-image basis as well as the existing per-class basis? Then you could sort images by mAP and view the poorest performing images?

**Comment by agupt013** [comment]
Ohh that makes sense I didn’t consider that the cases where conf will be
low. Sorting by mAP you mentioned would be best then.

Also, will it include FN? I don’t suppose the FN images would have mAP.
