### ISSUE TITLE
Confusion Matrix with weird scale

### ISSUE THREAD

**Issue by llucasreis** [ultralytics/yolov5#6626]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello!

I executed the `val.py` command, and received the following results:

![image](https://user-images.githubusercontent.com/21988400/153726559-9710cd95-4e74-4199-bfae-58c827c22cf0.png)

And when I checked my Confusion Matrix, it's showing some weird results and a weird scale:

![image](https://user-images.githubusercontent.com/21988400/153726640-99a70d05-5566-4cf4-b833-7168cfc7a697.png)

 I don't get it why TP is 1.0 and FP is 1.0, can someone help me how can I interpret these results? And somehow fix the scale?

I tried to use `conf_thres=0.25` and `iou_thres=0.45` to see if my `val.py` results matches somehow the TP, since it's informed here (#1665) as the default values for Confusion Matrix.

### Additional

FYI: my class is ALL (Acute Lymphoblastic Leukemia) 😅

**Comment by llucasreis** [comment]
Ok apparently my Confusion Matrix is right, I checked all predicted images and my model doesn't predicted FNs, only FPs, and since I have only one class, everything went to background FP 🤔 

So I think I only have the problem with the scale in Confusion Matrix now

**Comment by llucasreis** [comment]
This code reproduces this behavior:

```python
import seaborn as sn
import matplotlib.pyplot as plt
import numpy as np
import warnings

matrix = np.array([[112, 34], [0,0]])

normalize = True

array = matrix / ((matrix.sum(0).reshape(1, -1) + 1E-6) if normalize else 1)  # normalize columns
array[array < 0.005] = np.nan  # don't annotate (would appear as 0.00)

names = ['ALL']
nc = 1

fig = plt.figure(figsize=(12, 9), tight_layout=True)
sn.set(font_scale=1.0 if nc < 50 else 0.8)  # for label size
labels = (0 < len(names) < 99) and len(names) == nc  # apply names to ticklabels

with warnings.catch_warnings():
    warnings.simplefilter('ignore')  # suppress empty matrix RuntimeWarning: All-NaN slice encountered
    sn.heatmap(array, annot=nc < 30, annot_kws={"size": 8}, cmap='Blues', fmt='.2f', square=True,
                xticklabels=names + ['background FP'] if labels else "auto",
                yticklabels=names + ['background FN'] if labels else "auto").set_facecolor((1, 1, 1))
fig.axes[0].set_xlabel('True')
fig.axes[0].set_ylabel('Predicted')
fig.savefig('confusion_matrix.png', dpi=250)
plt.close()
```

**Comment by glenn-jocher** [comment]
@llucasreis thanks for the code. I am able to reproduce. Will investigate.

**Comment by glenn-jocher** [comment]
@llucasreis good news 😃! Your original issue may now be fixed ✅ in PR #6638. Nan values were preventing a correct lower threshold for the Seaborn Heatmap colorbar, after update:

![image](https://user-images.githubusercontent.com/26833433/153876835-d5de3a9e-7512-4d85-8843-26c598b51963.png)

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by llucasreis** [comment]
Thank you very much @glenn-jocher ! 😄

**Comment by llucasreis** [comment]
Thank you very much! 😄  @glenn-jocher
