### ISSUE TITLE
Impact of the batch size in the inference time

### ISSUE THREAD

**Issue by Roios** [ultralytics/yolov5#6627]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I ran the val.py and the detect.py in the same data, with the same imgsz, conf_thres and iou_thres in yolov5x model with custom data. The only difference is that the batch size in val is 32 and detect is 1.

I noticed that with val.py the inference time was 33ms and with detect.py was 106ms.

If I change the batch size in val.py to 1, the inference time match.

My question is: why the inference decreases so much with a bigger batch size?

**Comment by glenn-jocher** [comment]
@Roios see Batch Size study here. Larger batches contribute to improved per-image speeds.
https://docs.google.com/spreadsheets/d/1Nm3jofjdgKja0AZHV8Jk_m8TgcF7jenCSA06DuEG2C0/edit?usp=sharing

<img width="878" alt="Screenshot 2022-02-15 at 12 44 10" src="https://user-images.githubusercontent.com/26833433/154055686-138136ab-3e25-44de-aebb-7bdf8fc0073b.png">

<img width="876" alt="Screenshot 2022-02-15 at 12 44 04" src="https://user-images.githubusercontent.com/26833433/154055681-cec935e2-24c9-4744-81e6-28fc706061f2.png">

**Comment by glenn-jocher** [comment]
Created batch size study discussion in https://github.com/ultralytics/yolov5/discussions/6649

**Comment by Roios** [comment]
This is super interesting, thank you.

Do I assume correctly that you used the **val.py** for this study?

**Comment by glenn-jocher** [comment]
@Roios yes I used `val.py --data coco.yaml --task study`, and just updated the code a bit to run the study over batch size instead of image size.

EDIT: so the statistics are evaluated over 5000 images in COCO val each time.
EDIT2: study took several hours to run.

**Comment by Roios** [comment]
Thank you once again!
