### ISSUE TITLE
Unable to set custom save location for downloaded model even after calling torch.hub.set_dir(MODEL_LOCATION)

### ISSUE THREAD

**Issue by sarimmehdi** [ultralytics/yolov5#6628]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

PyTorch Hub

### Bug

```
torch.hub.set_dir(os.path.join(os.getcwd(), 'models'))
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True).to('cuda:0')
```
After executing the above, the downloaded model should be saved to the models folder inside my project directory. However, it ends up being stored inside the base project directory

### Environment

- OS: Ubuntu 20.04
- Python 3.9

### Minimal Reproducible Example

```
torch.hub.set_dir(os.path.join(os.getcwd(), 'models'))
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True).to('cuda:0')
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by sarimmehdi** [comment]
I solved the problem using the following lines:

```
torch.hub.set_dir(os.path.join(os.getcwd(), 'models'))
model = torch.hub.load('ultralytics/yolov5:master', 'custom', 'models/yolov5s').to('cuda:0')
```

**Comment by glenn-jocher** [comment]
@sarimmehdi you can skip all that with YOLOv5, just send a model wherever you want. If the location doesn't exist it will be created on demand:

<img width="1547" alt="Screenshot 2022-02-14 at 15 12 35" src="https://user-images.githubusercontent.com/26833433/153880154-1ee8b7f5-394d-496c-951c-56b61624127e.png">
