### ISSUE TITLE
!python train.py --img 460 --batch 2 --epochs 2 --data xView.yaml --weights yolov5n.pt --cache

### ISSUE THREAD

**Issue by Mishail123** [ultralytics/yolov5#6630]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

No train

### Environment

train: weights=yolov5n.pt, cfg=, data=xView.yaml, hyp=data/hyps/hyp.scratch.yaml, epochs=2, batch_size=2, imgsz=460, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, evolve=None, bucket=, cache=ram, image_weights=False, device=, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=8, project=runs/train, name=exp, exist_ok=False, quad=False, linear_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest
github: up to date with https://github.com/ultralytics/yolov5 ✅
YOLOv5 🚀 v6.0-253-ga45e472 torch 1.10.0+cu111 CUDA:0 (Tesla P100-PCIE-16GB, 16281MiB)

hyperparameters: lr0=0.01, lrf=0.1, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0
Weights & Biases: run 'pip install wandb' to automatically track and visualize YOLOv5 🚀 runs (RECOMMENDED)
TensorBoard: Start with 'tensorboard --logdir runs/train', view at http://localhost:6006/

Dataset not found, missing paths: ['/content/yolov5/datasets/xView/images/autosplit_val.txt']
Traceback (most recent call last):
  File "train.py", line 642, in <module>
    main(opt)
  File "train.py", line 538, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 110, in train
    data_dict = data_dict or check_dataset(data)  # check if None
  File "/content/yolov5/yolov5/utils/general.py", line 442, in check_dataset
    r = exec(s, {'yaml': data})  # return None
  File "<string>", line 63, in <module>
  File "<string>", line 16, in convert_labels
FileNotFoundError: [Errno 2] No such file or directory: '../datasets/xView/xView_train.geojson'

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Mishail123 for xView you must download the data manually and unzip to the xView directory before running 'train.py --data xView.yaml'

https://github.com/ultralytics/yolov5/blob/a45e472358d5051a6cb857483b8fb357b2634db2/data/xView.yaml#L1-L9
