### ISSUE TITLE
YOLOv5 DeepStream

### ISSUE THREAD

**Issue by marcoslucianops** [ultralytics/yolov5#6633]
Repository to use YOLOv5 model on NVIDIA DeepStream SDK

Link: https://github.com/marcoslucianops/DeepStream-Yolo

#### Config

```
board = NVIDIA Tesla V100 (AWS: p3.2xlarge)
batch-size = 1
eval = val2017 (COCO)
sample = 1920x1080 video
```

#### NMS config

- Eval

```
nms-iou-threshold=0.65
pre-cluster-threshold=0.001
topk=300
```

- Test

```
nms-iou-threshold=0.45
pre-cluster-threshold=0.25
topk=300
```

#### Results

| DeepStream         | Precision | Resolution | IoU=0.5:0.95 | IoU=0.5 | IoU=0.75 | FPS<br />(without display) |
|:------------------:|:---------:|:----------:|:------------:|:-------:|:--------:|:--------------------------:|
| YOLOv5x6 6.1       | FP16      | 1280       | 0.508        | 0.683   | 0.554    | 54.88                      |
| YOLOv5l6 6.1       | FP16      | 1280       | 0.494        | 0.668   | 0.540    | 87.86                      |
| YOLOv5m6 6.1       | FP16      | 1280       | 0.469        | 0.644   | 0.514    | 142.68                     |
| YOLOv5s6 6.1       | FP16      | 1280       | 0.399        | 0.581   | 0.438    | 271.19                     |
| YOLOv5n6 6.1       | FP16      | 1280       | 0.317        | 0.487   | 0.344    | 392.20                     |
| YOLOv5x 6.1        | FP16      | 640        | 0.470        | 0.652   | 0.513    | 152.99                     |
| YOLOv5l 6.1        | FP16      | 640        | 0.454        | 0.636   | 0.496    | 247.60                     |
| YOLOv5m 6.1        | FP16      | 640        | 0.421        | 0.604   | 0.458    | 375.06                     |
| YOLOv5s 6.1        | FP16      | 640        | 0.344        | 0.528   | 0.371    | 602.44                     |
| YOLOv5n 6.1        | FP16      | 640        | 0.247        | 0.413   | 0.256    | 629.04                     |

**Comment by glenn-jocher** [comment]
@marcoslucianops very cool, thank you for your contributions!
