### ISSUE TITLE
Add a run function to  yolov5/utils/loggers/wandb/log_dataset.py 

### ISSUE THREAD

**Issue by krishnakanagal** [ultralytics/yolov5#6640]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

In order to call log_dataset through another python script can you add a run function? This will be convenient to call log_dataset script from another program.

### Use case

It will be easier to call log_dataset script through another python script.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@krishnakanagal hey, what do mean by a run function? Can you elaborate please?

**Comment by krishnakanagal** [comment]
Hi Currently this script can only run through command line. I can't call this program through another python program. I want this program to be similar to train.py which can be run the command line or called through program.
