### ISSUE TITLE
Focal loss for yolov5x

### ISSUE THREAD

**Issue by SyedHamza0196** [ultralytics/yolov5#6654]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

In hyps simple, low , med and high focal loss gamma is set to zero by defaults and gives an example for efficientDet. What is a good focal loss value for yolov5x?

**Comment by glenn-jocher** [comment]
zero

**Comment by jiangdizhao** [comment]
> zero

Hi  @glenn-jocher, For very unbalanced datasets, I suggest you trying some loss like  " Class-Balanced Loss Based on Effective Number of Samples" , which shows better result than your BCE !!!

**Comment by jiangdizhao** [comment]
> zero

@glenn-jocher,  Please do not mislead users to use BCE loss in case of unbalanced datasets, maybe because you/your team are too lazy to find a better loss function.
