### ISSUE TITLE
Is it possible to change the training dataset while it is training?

### ISSUE THREAD

**Issue by MasIgor** [ultralytics/yolov5#6656]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello!

I'd like to set up a pc that just keeps training weights all day long. The idea would be that the pc's around the net that work with real images, send over to the central pc every image with a confidence lower than 0.9. (the object is located always in the same spot, so the bounding box can be created automatically.) Ideally the central training pc keeps getting images from the other pcs and adds them to the training dataset while learning. 

Can this be done?

Thank you!

Best regards

**Comment by glenn-jocher** [comment]
@tanzerlana no, you can not modify a dataset once training starts, but you can (should) implement an iterative workflow that accomplishes this for best practices in ML deployments.

![image](https://user-images.githubusercontent.com/26833433/154256731-af2f6883-1c38-44fa-b4d2-2d771d642044.png)

**Comment by MasIgor** [comment]
thank you! are you aware of any project that does what you describe automatically?

**Comment by glenn-jocher** [comment]
@tanzerlana automatically no, but Tesla Autopilot is the best real world example of this philosophy
