### ISSUE TITLE
Recent YOLOv5 version for Python pip

### ISSUE THREAD

**Issue by haimat** [ultralytics/yolov5#6657]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

I know there is a pip-installable verison of [YOLOv5 on pyip](https://pypi.org/project/yolov5/), however, that is more than 2 months old and thus quite outdated in comparison to the original YOLOv5 code here in this official repo. To get all the latest features of YOLOv5 it would really be great to have an official package for Python `pip`.

Any chance you guys could be so kind and provide that?

### Use case

In order to ship a Python application that is using YOLOv5, it is very handy to use a simple `import yolov5` in our code. Without that one must include the YOLOv5 repo in the application's source code - possible, but not as elegant and straight forward as one `import` call.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@haimat yeah you're absolutely right. The repo is not currently pip-compatible, there's a few changes that would need to take place but I agree we need to deploy an official pip package, maybe something like:

```bash
$ pip install ultralytics-yolov5

import yolov5
```
