### ISSUE TITLE
train on cpu

### ISSUE THREAD

**Issue by msadoun** [ultralytics/yolov5#6660]
### Search before asking

How do I train on CPU since I don't have a GPU ?

I am getting the below error and I don't know hoe to solve it

### YOLOv5 Component

Training

### Bug

     Epoch   gpu_mem       box       obj       cls    labels  img_size
  0%|          | 0/8 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\sadoun\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 990, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "C:\Users\sadoun\Anaconda3\lib\multiprocessing\queues.py", line 108, in get
    raise Empty
_queue.Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 642, in <module>
    main(opt)
  File "train.py", line 538, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 304, in train
    for i, (imgs, targets, paths, _) in pbar:  # batch -------------------------------------------------------------
  File "C:\Users\sadoun\Anaconda3\lib\site-packages\tqdm\std.py", line 1185, in __iter__
    for obj in iterable:
  File "C:\Users\sadoun\Desktop\yolov5-master\utils\datasets.py", line 141, in __iter__
    yield next(self.iterator)
  File "C:\Users\sadoun\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "C:\Users\sadoun\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1186, in _next_data
    idx, data = self._get_data()
  File "C:\Users\sadoun\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1152, in _get_data
    success, data = self._try_get_data()
  File "C:\Users\sadoun\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1003, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 6492, 9612, 18528, 2700, 11796, 13184) exited unexpectedly

### Environment

- Windows 10

### Minimal Reproducible Example

python train.py --img 640 --batch 16 --epochs 3 --data coco128.yaml --weights yolov5s.pt

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@msadoun it appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual [Python 3.9](https://www.python.org/) environment, clone the latest repo ([code changes daily](https://github.com/ultralytics/yolov5/commits/master)), and `pip install` [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) again from scratch.

💡 ProTip! Try one of our verified environments below if you are having trouble with your local environment.


## Requirements

[**Python>=3.7.0**](https://www.python.org/) with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) installed including [**PyTorch>=1.7**](https://pytorch.org/get-started/locally/). To get started:
```bash
git clone https://github.com/ultralytics/yolov5  # clone
cd yolov5
pip install -r requirements.txt  # install
```

[Models](https://github.com/ultralytics/yolov5/tree/master/models) and [datasets](https://github.com/ultralytics/yolov5/tree/master/data) download automatically from the latest YOLOv5 [release](https://github.com/ultralytics/yolov5/releases) when first requested.

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), validation ([val.py](https://github.com/ultralytics/yolov5/blob/master/val.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/export.py)) on MacOS, Windows, and Ubuntu every 24 hours and on every commit.

**Comment by msadoun** [comment]
> @msadoun it appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.


I have Python 3.8.8 and PyTorch 1.7 installed I have also installed [requirements.txt] successfully!

**Comment by msadoun** [comment]
I managed to solve it by adding 
```
import os

os.environ['KMP_DUPLICATE_LIB_OK']='True'
```

and now it works fine

**Comment by jasperan** [comment]
> I managed to solve it by adding
> 
> ```
> import os
> 
> os.environ['KMP_DUPLICATE_LIB_OK']='True'
> ```
> 
> and now it works fine

What does that do exactly?

**Comment by camilabbertelli** [comment]
unfortunately, it didn't work for me :(

**Comment by glenn-jocher** [comment]
@camilabbertelli i'm sorry to hear that the solution didn't work for you. Can you please provide more details about the issue you are facing? This will help us understand the problem better and provide you with the appropriate solution. Thank you.

**Comment by camilabbertelli** [comment]
@glenn-jocher thank you for responding but I discovered my machine was the problem here, memory probably went through the roof haha, using yolov8 now on another machine and it works just fine!

Thanks again :)

**Comment by glenn-jocher** [comment]
You're welcome, @camilabbertelli! I'm glad to hear that you found a workaround and that YOLOv8 is working well for you on another machine. If you have any further questions or need assistance in the future, feel free to reach out. Good luck with your YOLOv8 projects!
