### ISSUE TITLE
Evaluating on test data

### ISSUE THREAD

**Issue by st162053** [ultralytics/yolov5#6679]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,
I have trained  Yolo models on a custom dataset and used it for detection. Now I wanted to display some metrics for the test set (unlabeled, raw imaes), to check how good it really performs in the "real-world".
![Screenshot 2022-02-17 173726](https://user-images.githubusercontent.com/94604405/154527657-0c269f77-6d6c-41f5-869c-a6e7c11b1713.jpg)
 Is there a way to display more metrics than just confusion-matrix (which is empty as there are no labels) and the prediction mosaic? 
![image](https://user-images.githubusercontent.com/94604405/154527879-de5f090a-7e1e-46d9-a0e5-d33a2f7b7824.png)

Thanks for help!

**Comment by glenn-jocher** [comment]
@st162053 metrics like P, R, F1, mAP, etc. all require labelled data to compare your predictions to. What sort of metrics are you looking for on unlabelled data?

**Comment by st162053** [comment]
Sorry for the late reply, I was just wondering if there are metrics to evaluate the metrics in the 'real' world. Thanks!

**Comment by glenn-jocher** [comment]
@st162053 not sure what you mean. Metrics require a prediction vs a truth. Where is your truth data coming from in your 'real' world?

You might want to start here:
https://en.wikipedia.org/wiki/Precision_and_recall

**Comment by st162053** [comment]
Yep sorry! I was really confused, because of another article. It stated that you're not allowed to evaluate your model based on the val dataset!
