### ISSUE TITLE
EdgeTPU unassigned variable y running a detection 

### ISSUE THREAD

**Issue by RaffaeleGalliera** [ultralytics/yolov5#6684]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

Detection on _edgetpu_ model returns the following error:
`File "yolov5/models/common.py", line 449, in forward
    y[..., :4] *= [w, h, w, h]  # xywh normalized to pixels
UnboundLocalError: local variable 'y' referenced before assignment
`

I believe that the error from is caused by `self.tflite` not being set in the if/else branches in the forward method  when edgetpu is true (common.py line 438). That should be cause by `tflite &= not edgetpu  # *.tflite` in the `model_type` method.
```python3
@staticmethod
    def model_type(p='path/to/model.pt'):
        # Return model type from model path, i.e. path='path/to/model.onnx' -> type=onnx
        from export import export_formats
        suffixes = list(export_formats().Suffix) + ['.xml']  # export suffixes
        check_suffix(p, suffixes)  # checks
        p = Path(p).name  # eliminate trailing separators
        pt, jit, onnx, xml, engine, coreml, saved_model, pb, tflite, edgetpu, tfjs, xml2 = (s in p for s in suffixes)
        xml |= xml2  # *_openvino_model or *.xml
        tflite &= not edgetpu  # *.tflite
        return pt, jit, onnx, xml, engine, coreml, saved_model, pb, tflite, edgetpu, tfjs
```
`tflite &= not edgetpu` sets `tflite` to true only if `tflite` is true and `edgetpu` is false, it is set to false otherwise.

### Environment

- OS: Ubuntu 20.04
-  Python 3.8.10

### Minimal Reproducible Example

I have exported the YoloV5s model to _edgetpu_ using:
`python export.py  --weights yolov5s.pt --include edgetpu --img 320 --data data/coco128.yaml`

Then run the detection with `python detect.py --weights yolov5s-int8_edgetpu.tflite --img 320 --data data/coco128.yaml`

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@RaffaeleGalliera good news 😃! Your original issue may now be fixed ✅ in PR #6686. I updated your original fix with a few changes and improvements!

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
