### ISSUE TITLE
Head output scales vs Anchor sizes

### ISSUE THREAD

**Issue by myasser63** [ultralytics/yolov5#6695]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am using my own dataset to train YOLOv5. My dataset consits of on large object per image. I used `Anchors : 3` which generated large anchor sizes `501,397, 496,471, 560,448, 541,505, 577,498, 530,559, 615,501, 566,553, 615,566` 

so what is the effect of the head output scales if the model can generate large anchors irrelevant to the head output scales of the model comapred to using bigger head output scales?

**Comment by glenn-jocher** [comment]
@myasser63 varying stride outputs provide observability to objects at different scales.

**Comment by myasser63** [comment]
@glenn-jocher Thanks for your reply. I understand the purspose for different output scales. I am just trying to understand if the model can fit very large objects using large anchors, I dont need to use bigger output scales  as `40x40, 20x20, 10x10` to improve the performance on my dataset, right?

**Comment by glenn-jocher** [comment]
@myasser63 large objects will be detected best by larger stride output layers.

**Comment by myasser63** [comment]
@glenn-jocher Thanks for your repy
