### ISSUE TITLE
Can't train the model from beginning to make Ap50 reach 55.0%

### ISSUE THREAD

**Issue by RobinhoodKi** [ultralytics/yolov5#67]
I strictly follow the instructions to train yolov5-small from scratch. 
I hope to reproduce the AP50 result which is 55.0%.
But I got stuck at 44%, even I train the model for 346 epochs, Is there anything I missing?

**Comment by glenn-jocher** [comment]
@RobinhoodKi see https://github.com/ultralytics/yolov5#reproduce-our-training to reproduce. Nothing else is required.

**Comment by glenn-jocher** [comment]
@RobinhoodKi for v5s though I would use the largest batch-size your GPU allows, i.e. 64 on a V100 or perhaps 32 on a 2080ti.
