### ISSUE TITLE
Black screen during real-time detection(RTSP)

### ISSUE THREAD

**Issue by hlk-1135** [ultralytics/yolov5#6708]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Code version is v5.0. We are using RSTP to transmit real-time camera data. After the program runs for a few minutes, there is a black screen problem, and the console does not display any errors.
Is this related to hardware equipment? Is there any way to improve the software? Thanks!

**Comment by hlk-1135** [comment]
![img1](https://user-images.githubusercontent.com/22735840/154841620-920a7994-a278-4962-93af-7cc42e3c4223.jpeg)
![img2](https://user-images.githubusercontent.com/22735840/154841627-36275537-a3f4-4ce9-9f8f-63229e7d5326.jpeg)

**Comment by glenn-jocher** [comment]
@hlk-1135 you probably have a connection issue. Interrupted connections will return zeros in order to allow other connections to proceed uninterrupted. See L340 warning message:

https://github.com/ultralytics/yolov5/blob/a936f5f219e7697ea059d6fcf5ead3ac7b206687/utils/datasets.py#L328-L344

**Comment by hlk-1135** [comment]
> you probably have a connection issue. Interrupted connections will return zeros in order to allow other connections to proceed uninterrupted

The time to directly access the camera via ip in the browser is 22:43:00,but it is 22:42:45 in cv2.imshow() by run yolov5 code.There is a difference of 15 seconds.Sometimes,the cv2.imshow() is grey,the console print LOGGER.warning('WARNING: Video stream unresponsive, please check your IP camera connection.') .
Q1: Is this a normal phenomenon?
Q2:Is the cause of this problem code or network?
Thanks!
![image](https://user-images.githubusercontent.com/22735840/159169311-905da9da-2acf-4888-909c-5202b26216fe.png)

**Comment by glenn-jocher** [comment]
@hlk-1135 this is likely due to stream/network issues.
