### ISSUE TITLE
Privacy mask in rtsp source

### ISSUE THREAD

**Issue by diegotecrede** [ultralytics/yolov5#6715]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi everyone! I'm trying to apply some modifications in image when using rtsp source (got im0s image during proccess) and its ok, works fine, but after that, when apply classify, it doesn't predict anymore. Someone could help ?

**Comment by hlk-1135** [comment]
You mean it didn't pridict bounding box? rtsp souce is images or viedo?

**Comment by diegotecrede** [comment]
> 

actually, it predict bounding box, but from wrong image. rtsp source is video
