### ISSUE TITLE
Ensembling 

### ISSUE THREAD

**Issue by czczmr** [ultralytics/yolov5#6718]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to integrate yolov5s and yolov5m.
Both of these models are used for single class detection.
But in yolov5s my classname is written as ship
in yolov5m is written as chuan.
When I integrate the detection, the output is ship.
Do I need to retrain my model?

**Comment by zhiqwang** [comment]
I guess not, because we don't use the label name when training, the concrete name is just used for visualization.

**Comment by glenn-jocher** [comment]
@czczmr ensembling is only intended for models trained on the same dataset, i.e. same data.yaml.

**Comment by czczmr** [comment]
> I guess not, because we don't use the label name when training, the concrete name is just used for visualization.

yes,but it did not improve my model
