### ISSUE TITLE
Img-size when detection

### ISSUE THREAD

**Issue by buimanhlinh96** [ultralytics/yolov5#672]
I think the authors should edit a little bit in detect.py same as train.py in order to detect rectangle image size!

**Comment by glenn-jocher** [comment]
@buimanhlinh96 I do not understand, can you explain more?

**Comment by buimanhlinh96** [comment]
So in the latest version, we only can detect square image such as 640x640 but in the rectangle size, it doesnt work! We can modify a little bit in detect.py same as train.py in order to detect at any size we want.

**Comment by glenn-jocher** [comment]
That is not correct. Suggest you start with the Colab tutorial.

**Comment by Stirfry70** [comment]
> @buimanhlinh96 I do not understand, can you explain more?
