### ISSUE TITLE
How to dockerise a custom trained Yolov5? - (Trained with VisDrone)

### ISSUE THREAD

**Issue by Vijay-P1999** [ultralytics/yolov5#6721]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm new to the Docker. I need to create a container with the model i trained in my PC. The model was trained with VisDrone datatset. I tried this line`docker build - < yolov5/Dockerfile` 

I got this output
`mypc@mypc:~/Documents/mypc$ docker build - < yolov5/Dockerfile
Sending build context to Docker daemon  4.096kB
Step 1/11 : FROM nvcr.io/nvidia/pytorch:21.10-py3
21.10-py3: Pulling from nvidia/pytorch
f3ef4ff62e0d: Pulling fs layer 
0a5a58fe9f80: Pulling fs layer 
ffe911d7d638: Pulling fs layer 
b6ca3d91503f: Pulling fs layer 
2153f05ef7a8: Waiting 
960ad9fc339d: Waiting 
423cea99f7d2: Waiting 
ea4474a67b49: Waiting 
b397fb86b3bc: Waiting 
927627363759: Pulling fs layer 
312d920fedcc: Waiting 
7a50c2cfea6b: Waiting 
06daa3d0f46c: Pull complete 
aec116761f98: Pull complete 
2812dcb9b1f1: Pull complete 
0b40e0143bfd: Pull complete 
0617ebfc4a21: Pull complete 
45a7802e347f: Pull complete 
9c3aac051d0f: Pull complete 
c06cf176a9ca: Pull complete 
6790e5e29cc3: Pull complete 
896ac25d66a9: Pull complete 
7dfa990e7e17: Pull complete 
9c0ad29545c4: Pull complete 
10c826feeab7: Pull complete 
7586e32d8197: Pull complete 
4b15b5b33bf7: Pull complete 
57e6549ecb9d: Pull complete 
6ad6cc7591f4: Pull complete 
42f060f227fb: Pull complete 
011b1f6b6400: Pull complete 
9e53e4417963: Pull complete 
ca666d4eaa20: Pull complete 
d1f7400b2d3f: Pull complete 
54369ed1d3f1: Pull complete 
1c729a9c37b3: Pull complete 
e1578f4858a1: Pull complete 
74181d60a1e2: Pull complete 
50ddcf676259: Pull complete 
21bcddf58d24: Pull complete 
2bbd488a8a42: Pull complete 
908ee1b12e54: Pull complete 
b47a76672e02: Pull complete 
75b1c4237463: Pull complete 
b04a25f7a069: Pull complete 
f4b2df38716c: Pull complete 
a0b7791628b2: Pull complete 
ef76ad566004: Pull complete 
afe1fa489351: Pull complete 
d11180edb78f: Pull complete 
8b703351d31b: Pull complete 
ae16429c29b3: Pull complete 
51065c2f605b: Pull complete 
421dd65d1507: Pull complete 
7d08e51a6a51: Pull complete 
Digest: sha256:267948c348eed1604ca180612d6a6ceb7298e4b0ee5900e2aee579edebb19caf
Status: Downloaded newer image for nvcr.io/nvidia/pytorch:21.10-py3
 ---> 030c24bd72ba
Step 2/11 : RUN apt update && apt install -y zip htop screen libgl1-mesa-glx
 ---> Running in 075dd47d3abe

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Get:1 http://archive.ubuntu.com/ubuntu focal InRelease [265 kB]
Get:2 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Err:2 http://security.ubuntu.com/ubuntu focal-security InRelease
  At least one invalid signature was encountered.
Err:1 http://archive.ubuntu.com/ubuntu focal InRelease
  At least one invalid signature was encountered.
Get:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Err:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
  At least one invalid signature was encountered.
Get:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Err:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
  At least one invalid signature was encountered.
Reading package lists...
W: GPG error: http://security.ubuntu.com/ubuntu focal-security InRelease: At least one invalid signature was encountered.
E: The repository 'http://security.ubuntu.com/ubuntu focal-security InRelease' is not signed.
W: GPG error: http://archive.ubuntu.com/ubuntu focal InRelease: At least one invalid signature was encountered.
E: The repository 'http://archive.ubuntu.com/ubuntu focal InRelease' is not signed.
W: GPG error: http://archive.ubuntu.com/ubuntu focal-updates InRelease: At least one invalid signature was encountered.
E: The repository 'http://archive.ubuntu.com/ubuntu focal-updates InRelease' is not signed.
W: GPG error: http://archive.ubuntu.com/ubuntu focal-backports InRelease: At least one invalid signature was encountered.
E: The repository 'http://archive.ubuntu.com/ubuntu focal-backports InRelease' is not signed.
The command '/bin/sh -c apt update && apt install -y zip htop screen libgl1-mesa-glx' returned a non-zero code: 100`

I'll provide additional details if needed. Please provide a solution for Building a image/cointainer from my model. (I dont know about docker. I'm just a noob)

**Comment by glenn-jocher** [comment]
@Vijay-P1999 see Docker Quickstart Guide https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/

**Comment by Vijay-P1999** [comment]
> @Vijay-P1999 see Docker Quickstart Guide https://github.com/ultralytics/yolov5/wiki/Docker-Quickstart

@glenn-jocher I think you didn't get my question. I custom trained the model with VisDrone dataset. Can you explain how to Docker that one?

**Comment by glenn-jocher** [comment]
@Vijay-P1999 docker and YOLOv5 are somewhat unrelated topics. Docker is simply a container service that allows you to run containers on various base environments. For docker tutorials see https://docs.docker.com/get-started/
