### ISSUE TITLE
Versioning Problem

### ISSUE THREAD

**Issue by Phyrokar** [ultralytics/yolov5#6722]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

Hallo!

Hello, I trained my model with the latest YoloV5 and I get the following error: 

> AttributeError: Can't get attribute 'SPPF' on <module 'models.common' from '/home/xx/catkin_ws/src/xx/src/models/common.py'>

I've read on other forums that it's a versioning issue and that I should change utils/google_utils.py line 25 from

`response = requests.get(f'https://api.github.com/repos/{repo}/releases/latest').json()`

to

`response = requests.get(f'https://api.github.com/repos/{repo}/releases/tag/v5.0').json()`

I did that, but the error persists. Does somebody has any idea? 

### Environment

YOLOv5 🚀 v6.0-274-gc43f135 torch 1.10.2+cu102 CUDA:0 (Quadro RTX 3000, 5935MiB)
Ubuntu 20.04
python 3

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Phyrokar your code or your models are out of date. To update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
