### ISSUE TITLE
How to extract the numeric format of the confusion matrix from val.py?

### ISSUE THREAD

**Issue by msadoun** [ultralytics/yolov5#6724]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am running the model and everything is working fine, but my question is :

How do I get the numeric representation (.txt or .csv) of the confusion matrix along with the [confusion_matrix.png] figure that is automatically generated?

I have tried adding `--save-txt` to the usage command but this only gives me a set of text files containing labels!

any ideas on what to do ?

**Comment by glenn-jocher** [comment]
@msadoun you'd have to customize the metrics to output this data:
https://github.com/ultralytics/yolov5/blob/a936f5f219e7697ea059d6fcf5ead3ac7b206687/val.py#L277-L281
