### ISSUE TITLE
I want to post-process the results of the predicted confidence

### ISSUE THREAD

**Issue by sungchi64** [ultralytics/yolov5#6725]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I want to post-process the results of the predicted confidence before calculating the map.

What I want to do is:
After predicting the category (for example, category A has 60% confidence and B has 40%), add some judgments. If category B meets the conditions, increase the confidence of category B, thereby improving the accuracy of category B. .

Since I don't know much about it yet, I would like to ask where do I get the confidence of each category after prediction so that I can add the judgment?

**Comment by glenn-jocher** [comment]
@sungchi64 you can customize your own post-processing on the model predictions `pred` here before NMS:
https://github.com/ultralytics/yolov5/blob/dbbb57cf0b8004dddb7e3bc4506b68b44b60896a/detect.py#L125-L134

**Comment by sungchi64** [comment]
I can get pred (coordinates,confidence,class) after doing NMS.
I would like to ask
**Q1:** 
Before doing NMS, how do I get the "**coordinates**" and "**the confidence of each category**" of each anchor box?
**Q2:**
If I want to add another input (.text) during detection, as a judgment content for adjusting the confidence values in the anchor box, where should I write it?

Thank you very much for your answer, it helped me a lot!
