### ISSUE TITLE
How to use Yolov5 in AMD GPU

### ISSUE THREAD

**Issue by Vijay-P1999** [ultralytics/yolov5#6735]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I need to implement object detection in AMD radeon GPU. 
Provide any solutions like how to change any parameters.
P.S i'm using AMD Ryzen 5 5600U with Radeon graphics. Happy to provide all the necessary details.

**Comment by glenn-jocher** [comment]
@Vijay-P1999 I'm not sure if that's possible. Generally NVIDIA GPUs are utilized for training and deployment. There seems to be some effort in the direction of AMD support, but for now we don't have any official tutorial to devices to test on. See https://pytorch.org/blog/pytorch-for-amd-rocm-platform-now-available-as-python-package/

**Comment by YuaXan** [comment]
> @Vijay-P1999 I'm not sure if that's possible. Generally NVIDIA GPUs are utilized for training and deployment. There seems to be some effort in the direction of AMD support, but for now we don't have any official tutorial to devices to test on. See https://pytorch.org/blog/pytorch-for-amd-rocm-platform-now-available-as-python-package/

The pytorch support for AMD ROCM, I'm not sure if can train running of AMD.

**Comment by rtorrero** [comment]
In case it's still useful: yes, AMD GPUs can be used with ROCm (AMDs CUDA equivalent). Not sure if your GPU in particular is supported, but in case you want to try, the most convenient way is to use this docker image as the packages are still somewhat hard to install on my distro:

If you are familiar with docker and already are using `amdgpu`, just go directly here  ->https://hub.docker.com/r/rocm/pytorch

If you need a bit more background -> https://github.com/RadeonOpenCompute/ROCm-docker/blob/master/quick-start.md

**Comment by rtorrero** [comment]
@glenn-jocher if it's useful I could create a PR to document this somewhere in the repo, just let me know where :+1:

**Comment by Ambarish-Ombrulla** [comment]
Ultralytics YOLOv8.0.152  Python-3.11.4 torch-2.0.1+cpu CPU (AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx)

Didn't have any problem when I was taking image from the webcam but , when I am taking it from web socket its not executing

**Comment by MeatyAri** [comment]
You absolutely **can!** run your model on an AMD GPU. I just answered this in here:
https://github.com/ultralytics/yolov5/issues/2995#issuecomment-1737833987

**Comment by glenn-jocher** [comment]
@MeatyAri you absolutely can run your model on an AMD GPU. PyTorch now supports AMD GPUs through the ROCm platform. You can refer to the ROCm PyTorch Docker image for convenient installation on your system. There is also a guide available on the ROCm-docker repository for further instructions. Please note that I have already answered this question in more detail in the following GitHub issue: 
https://github.com/ultralytics/yolov5/issues/2995#issuecomment-1737833987
