### ISSUE TITLE
how to write tagged letters from left to right?

### ISSUE THREAD

**Issue by ozicmoi** [ultralytics/yolov5#6737]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I trained 2 yolov4-tiny models for my license plate recognition system. The first is the fog plate region label, the second is the char labels (letters and numbers). The Turkish alphabet is read from left to right. That's why I want to sort the tagged letters in the frame according to the x position. When I don't do this, the order is wrong.

I handled it with the code below with yolov5 before. But I couldn't solve my problem because I don't know if there is a function named sorted_values in the yolov4-tiny model.

    results1 = model(frame)
    results1.pandas().xyxy[0].sort_values('xmin')
    plate_num = str(results1.pandas().xyxy[0].sort_values('xmin').name.values)
    clean_text2 = ""
    for char in plate_num:
        if char in "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ":
            clean_text2 += char
    plate_num = clean_text2
    plate_num = plate_num.replace(" ", "").replace("\n", "")

"""import time
import cv2
Opencv DNN klasöründeki Plaka modeli

net = cv2.dnn.readNet("dnn_model/plate-yolov4-tiny.weights", "dnn_model/plate-yolov4-tiny.cfg")
model = cv2.dnn_DetectionModel(net)
model.setInputParams(size=(320, 320), scale=1/255)
Opencv DNN klasöründeki Char modeli

net1 = cv2.dnn.readNet("dnn_model/char-yolov4-tiny.weights", "dnn_model/char-yolov4-tiny.cfg")
model1 = cv2.dnn_DetectionModel(net1)
model1.setInputParams(size=(320, 320), scale=1/255)
Load class lists

classes = []
classes1=[]
with open("dnn_model/plate-classes.txt", "r") as file_object:
for class_name in file_object.readlines():
class_name = class_name.strip() # satır arası boşluklar için
classes.append(class_name)
print(class_name)
with open("dnn_model/char-classes.txt", "r") as file_object1:
for class_name1 in file_object1.readlines():
class_name1 = class_name1.strip() # satır arası boşluklar için
classes1.append(class_name1)
print(class_name1)

cap = cv2.VideoCapture(0)# Initialize camera
while True:
ret, frame = cap.read()# Get frames
# Object Detection
(class_ids, scores, bboxes) = model.detect(frame, confThreshold=0.3, nmsThreshold=.4)
for class_id, score, bbox in zip(class_ids, scores, bboxes):
(x, y, w, h) = bbox
cv2.rectangle(frame, (x, y), (x + w, y + h), (200,0,50), 3)
cropped = frame[y:y+h, x:x+w].copy()
cv2.imshow("cropped",cropped)
class_name = classes[class_id]
cv2.putText(frame, class_name, (x, y - 10), cv2.FONT_HERSHEY_PLAIN, 3, (200,0,50), 2)
(class_ids1, scores1, bboxes1) = model1.detect(cropped, confThreshold=0.3, nmsThreshold=.4)
plate_num=""
for class_id1, score1, bbox1 in zip(class_ids1, scores1, bboxes1):
(x1, y1, w1, h1) = bbox1
cv2.rectangle(cropped, (x1, y1), (x1 + w1, y1 + h1), (200, 0, 50), 3)
class_name1 = classes1[class_id1]
plate_num=plate_num+class_name1
cv2.putText(cropped, class_name1, (x, y - 10), cv2.FONT_HERSHEY_PLAIN, 3, (200, 0, 50), 2)
print(plate_num)

cv2.imshow("Frame", frame)
key = cv2.waitKey(1)
if key == 'q':
    break

cap.release()
cv2.destroyAllWindows()
"""

import cv2
Opencv DNN

net = cv2.dnn.readNet("dnn_model/char-yolov4-tiny.weights", "dnn_model/char-yolov4-tiny.cfg")
model = cv2.dnn_DetectionModel(net)
model.setInputParams(size=(320, 320), scale=1/255)

plate_num=""
Load class lists

classes = []
with open("dnn_model/char-classes.txt", "r") as file_object:
for class_name in file_object.readlines():
#print(class_name)
class_name = class_name.strip() # satır arası boşluklar için

    classes.append(class_name)

Initialize camera

cap = cv2.VideoCapture(0)

while True:

ret, frame = cap.read()   # Get frames
# Object Detection
(class_ids, scores, bboxes) = model.detect(frame, confThreshold=0.3, nmsThreshold=.4)
for class_id, score, bbox in zip(class_ids, scores, bboxes):
    (x, y, w, h) = bbox
    cv2.rectangle(frame, (x, y), (x + w, y + h), (200,0,50), 3)
    class_name = classes[class_id]

    cv2.putText(frame, class_name, (x, y - 10), cv2.FONT_HERSHEY_PLAIN, 3, (200,0,50), 2)

cv2.imshow("Frame", frame)
plate_num+=class_name
print(plate_num)
key = cv2.waitKey(1)

if cv2.waitKey(1) & 0xFF == ord('q'):
    break

cap.release()
cv2.destroyAllWindows()

![Screenshot from 2022-02-22 11-13-42](https://user-images.githubusercontent.com/52746269/155091616-49425543-2162-44c7-92cb-21f563724a45.png)

**Comment by glenn-jocher** [comment]
@ozlematiz sorry, YOLOv4 questions should be raised on the relevant repo. The scope of our support here is YOLOv5 issues.

**Comment by ozicmoi** [comment]
I just wanted to ask if you have any information. I'll post it there. Sorry
