### ISSUE TITLE
Where do you check if the ground_truth value and the predicted value are correct?

### ISSUE THREAD

**Issue by JinYoung00** [ultralytics/yolov5#6738]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Where do you check if the ground_truth(label, correct class...) value and the predicted value(detection, pred... ) are correct?
I would like to output 'TP' and 'FP' values for each image.
I found the code part that makes the matrix value  in yolov5/utils/metrics.py line 125.

One out of 10,000 in test set, It is determined that "TP" despite the difference between "detection class" and "gc" values in "for i, gc in emulator(gt_classes)". I want to know if there is a place to compare the detection class and ground truth.

`        n = matches.shape[0] > 0
        m0, m1, _ = matches.transpose().astype(np.int16)
        for i, gc in enumerate(gt_classes):
            j = m0 == i
            if n and sum(j) == 1:
                self.matrix[detection_classes[m1[j]], gc] += 1  # correct
            else:
                self.matrix[self.nc, gc] += 1  # background FP
`

Thank you in advance

**Comment by glenn-jocher** [comment]
@JinYoung00 see confusion matrices after training in your runs/train/exp directory

## VOC Confusion Matrix
`python val.py --weights last.pt --data voc.yaml --img 512`
![image](https://user-images.githubusercontent.com/26833433/99973176-c39f9e80-2d9f-11eb-99fa-39b25ec14e35.png)

## COCO Confusion Matrix
`python val.py --weights last.pt --data coco.yaml --img 640`
![image](https://user-images.githubusercontent.com/26833433/99971151-188de580-2d9d-11eb-9f2d-fcc1b7c195b8.png)

**Comment by endrol** [comment]
@glenn-jocher I couldn't find the `test.py` file in the repo. Maybe the `val.py`? 🤔 
If so, the generated confusion_matrix shows a little differently. The `FP` and `FN` swapped places. 
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/37173750/155937180-2b9595ab-98b6-4a09-b975-9be8664ef6ae.png">

**Comment by glenn-jocher** [comment]
@endrol yes val.py has replaced test.py and the above results are out of date.

**Comment by endrol** [comment]
> @endrol yes val.py has replaced test.py and the above results are out of date.

@glenn-jocher  Thank you for your reply. I tested a one-class object detection, but don't quite understand the confusion matrix. 
![confusion_matrix](https://user-images.githubusercontent.com/37173750/155951155-674fa270-8caa-436d-92bc-04d126a1f9bb.png)
My thought is `0.28` should be the FP value, instead of the FN value. So if the last row is FP would be more reasonable for me. Please correct me if I'm wrong.

**Comment by glenn-jocher** [comment]
@endrol yes this is a single-class confusion matrix. Columns are normalized.

**Comment by endrol** [comment]
@glenn-jocher I see. Thank you for answering.
