### ISSUE TITLE
Different time with trtexec and the YOLOv5 script

### ISSUE THREAD

**Issue by dariogonle** [ultralytics/yolov5#6743]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,

 I've measured the time of YOLOv5n on a Jetson Nano and I got 24ms (320 img-size) with the YOLOv5 script. Then I measured it with Trtexec and I got 14.70ms. Does anyone know what can cause this difference of time?

Thank you in advance.

**Comment by glenn-jocher** [comment]
@dariogonle correct CUDA profiling requires syncing GPU data before obtaining a time stamp. See https://github.com/ultralytics/yolov5/issues/6600

If you think the current implementation is incorrect though, please submit a PR with your proposed fix, along with before and after results to allow us to quantify the improvement your PR provides. Thank you!

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
