### ISSUE TITLE
Using Yolov5 with 3D cuboid bounding boxes

### ISSUE THREAD

**Issue by pederespen** [ultralytics/yolov5#6748]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, would it be possible to use Yolov5 with cuboid bounding boxes (with a center X,Y,Z, width/height/length) instead of 2D bounding boxes without too much modification?

**Comment by devimauz** [comment]
Same question here. From 2d you can calculate from txt file.

**Comment by devendraappstek** [comment]
@pespen  Did you implemented this? If so, if please share the code here.

**Comment by glenn-jocher** [comment]
@devendraappstek yes, it is possible to use YOLOv5 with 3D cuboid bounding boxes by extending the existing architecture and modifying the dataset annotations. You can calculate the 3D coordinates and dimensions from the 2D bounding box annotations provided in the text file. However, please note that YOLOv5 is primarily designed for 2D object detection and may require additional modifications and training to effectively handle 3D cuboid bounding boxes.
