### ISSUE TITLE
Weighted class training

### ISSUE THREAD

**Issue by melonux** [ultralytics/yolov5#675]
## 🚀 Feature

Give each class a weight.

UPDATE: It seem it has already implemented:

    model.class_weights = labels_to_class_weights(dataset.labels, nc).to(device)  # attach class weights

## Motivation

Some objects are more important than others. If the model makes wrong prediction or poor IoU on objects of that class, it should get more punishment. 

## Pitch

add 'weights' field in  dataset description file.

nc: 26
names: ['dog', 'cat', 'fish', 'bird']
weights: [1.0, 2.0, 1.0, 1.0]   # <- add this field to emphasize 'cat' class.

**Comment by glenn-jocher** [comment]
@melonux class weights are automatically computed already.

**Comment by glenn-jocher** [comment]
@melonux if you want to apply the weights, you have to determine your own strategy for weighing the objectness or classification targets in the respective loss functions in utils.general.compute_loss()

**Comment by melonux** [comment]
> @melonux if you want to apply the weights, you have to determine your own strategy for weighing the objectness or classification targets in the respective loss functions in utils.general.compute_loss()

Thank you very much.

**Comment by ZeKunZhang1998** [comment]
> ## 🚀 Feature
> Give each class a weight.
> 
> UPDATE: It seem it has already implemented:
> 
> ```
> model.class_weights = labels_to_class_weights(dataset.labels, nc).to(device)  # attach class weights
> ```
> 
> ## Motivation
> Some objects are more important than others. If the model makes wrong prediction or poor IoU on objects of that class, it should get more punishment.
> 
> ## Pitch
> add 'weights' field in dataset description file.
> 
> nc: 26
> names: ['dog', 'cat', 'fish', 'bird']
> weights: [1.0, 2.0, 1.0, 1.0] # <- add this field to emphasize 'cat' class.

Is it in coco.yaml?

**Comment by glenn-jocher** [comment]
@ZeKunZhang1998 no. Inverse frequency class weights are automatically defined in train.py. What you do with them is up to you. By default they are not used anywhere.
https://github.com/ultralytics/yolov5/blob/e71fd0ec0bbccb2ea38936a86defb0a31ff1153c/train.py#L176
