### ISSUE TITLE
How to correctly supply input dimensions to train.py and detect.py

### ISSUE THREAD

**Issue by gj-raza** [ultralytics/yolov5#6755]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

i generated my dataset from roboflow from 1080x1920 images and resized to 640x640(letterbox resize), now how do i supply it correctly to train and detect script given that they only take one arguement as dimension. How would the scripts resize images for train and infer if i give just --img  640 ?

thanks in advance

**Comment by kellymore** [comment]
Hi @gj-raza 

I'm the Developer Advocate from Roboflow. As long as you have your dataset and train/test/split images in your YOLOv5-CustomTraining colab notebook, you shouldn't need to change anything when running your train.py except for updating the input size of the model to match what you resized them to.

After you run the cell it should just kick off from there. Here is a [video tutorial ](https://youtu.be/x0ThXHbtqCQ?t=573)starting from where this is explained a bit more in depth.

If there was any confusion as to why you didn't have to give width and height dimensions, and only one dimension
it is because YOLO operates on square images, so providing the one dimension (width) gives the assumption the other dimension (height) matches it.

**Comment by glenn-jocher** [comment]
@gj-raza yes for most commands in YOLOv5 you can supply a single `--img-size`. This is the long side of your image. Short size is handled automatically.

**Comment by gj-raza** [comment]
> 

@glenn-jocher  so this means that if my dataset is 640x640 and i supply --img-size 640,  the script will  resize my images to 640x384 while training?

**Comment by glenn-jocher** [comment]
@gj-raza square mosaics are used during training, val.py and detect.py use rectangular inference for pytorch models and square inference for other backends (TF, ONNX, etc.)

**Comment by gj-raza** [comment]
@glenn-jocher  can you please share the reason for this? like why pytorch models use rectangular inference. and say if the model is trained using training data dimensions mentioned above, how will the script resize an image size of 1080x1920 say coming from a feed at infer time, assuming pytorch inference ?

**Comment by mysteryjeans** [comment]
> @gj-raza square mosaics are used during training, val.py and detect.py use rectangular inference for pytorch models and square inference for other backends (TF, ONNX, etc.)

I am handling short size in preprocessing for MS ONNX runtime, for best results on ONNX I should export square shape instead of rectangular?

**Comment by gj-raza** [comment]
> > @gj-raza square mosaics are used during training, val.py and detect.py use rectangular inference for pytorch models and square inference for other backends (TF, ONNX, etc.)
> 
> I am handling short size in preprocessing for MS ONNX runtime, for best results on ONNX I should export square shape instead of rectangular?

yes.

**Comment by 00kar** [comment]
> @glenn-jocher can you please share the reason for this? like why pytorch models use rectangular inference. and say if the model is trained using training data dimensions mentioned above, how will the script resize an image size of 1080x1920 say coming from a feed at infer time, assuming pytorch inference ?

@glenn-jocher This questions interests me, too.

**Comment by glenn-jocher** [comment]
@00kar pytorch inference resizes image to --imgsz on long side and handles short side automatically for minimum area that meets stride constraints.

**Comment by 00kar** [comment]
> @00kar pytorch inference resizes image to --imgsz on long side and handles short side automatically for minimum area that meets stride constraints.

Thanks for reply.
If model has been trained in square images, how well will it work during inference on rectangular images?

**Comment by glenn-jocher** [comment]
@00kar image size and shape is irrelevant to results. Object size and shape are all that matter.

**Comment by 00kar** [comment]
> @00kar image size and shape is irrelevant to results. Object size and shape are all that matter.

Okay, thanks
