### ISSUE TITLE
error: no disk space in val one image end

### ISSUE THREAD

**Issue by zhjw0927** [ultralytics/yolov5#6756]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

After 13 epochs of training and when  val is starting, report a error: no disk space, which can be tracked as follows:
![Screenshot from 2022-02-23 20-35-25](https://user-images.githubusercontent.com/42128459/155441027-8e2a5b5c-0816-40d7-8214-28a3c711d297.png)
![Screenshot from 2022-02-23 20-35-41](https://user-images.githubusercontent.com/42128459/155441038-90d8e7d4-71fe-401d-97a9-81c25f31c721.png)
I think it is because of the continuous append images into the list, which leads to insufficient memory, but  self.max_imgs_to_log is set to 16, the above problem may not occur, and it is in the middle of training, not at the beginning.
Looking for help, thank you!

**Comment by glenn-jocher** [comment]
@zhjw0927 your computer is simply out of hard drive space.

**Comment by zhjw0927** [comment]
> @zhjw0927 your computer is simply out of hard drive space.

Thank you for reply. I simply think appendint imgs into list is not enough memory space, not hard drive space? Is my understanding wrong?

**Comment by glenn-jocher** [comment]
@zhjw0927 your error is telling you there is no hard drive space left on your device. 

This has nothing to do with YOLOv5
