### ISSUE TITLE
Increase feature size

### ISSUE THREAD

**Issue by guohuanguohuan** [ultralytics/yolov5#6760]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Each of your modules has the number of channels C1 and C2. 
Please add the length and width of the feature map for each module. 
I have an innovation that needs this, but my code ability is really limited. 
If the innovation is successful, the number of parameters will be reduced to half of the original. 
Thank you.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@helloyizhengjun feature maps width and height are not fixed values in any YOLOv5 module, they are functions of the input image width and height.
