### ISSUE TITLE
how to use stream/webcam as input and get results as images?

### ISSUE THREAD

**Issue by bit-scientist** [ultralytics/yolov5#6761]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi everyone, this is my first time posting a question on this repo. I know that it is possible to get images as output, only when images are used. But how to modify the code inside the detect.py so that when you use video or stream/webcam, it writes/saves images along with the video? Thank you.

**Comment by glenn-jocher** [comment]
@bit-scientist you can customize results handling in detect.py here:
https://github.com/ultralytics/yolov5/blob/0f819919adca1eb951376430695d3a790e0b7455/detect.py#L184-L202

**Comment by Guttappa1238** [comment]
Hi @bit-scientist, you can add these line before 185 line in `detect.py` and initialize `d  = 0`in starting
```
cv2.imwrite(os.path.join(save_dir,"frame_%d.jpg"%d), im0)
d+=1
```

**Comment by gustavozantut** [comment]
streaming output frames with gst: https://github.com/gustavozantut/yolov5_live_results

**Comment by donghyck** [comment]
> Hi @bit-scientist, you can add these line before 185 line in `detect.py` and initialize `d = 0`in starting
> 
> ```
> cv2.imwrite(os.path.join(save_dir,"frame_%d.jpg"%d), im0)
> d+=1
> ```

hi, is that possible to save the image also with the bounding box like this?
![image](https://github.com/ultralytics/yolov5/assets/149129283/755f59ca-3db4-40f7-a6b7-7f6a0f7f7d79)

**Comment by donghyck** [comment]
hi @Guttappa1238 is that possible to save the image also with the bounding box like this?
![image](https://github.com/ultralytics/yolov5/assets/149129283/b72875bf-6dc8-4148-98ab-6f6f7a696fed)

**Comment by glenn-jocher** [comment]
@donghyck hi there! Yes, you can save images with bounding boxes. After the predictions are made and the boxes are drawn on the frames (which happens in the `detect.py`), you can save the resulting frame using `cv2.imwrite()`. Make sure to do this after the drawing operations, so the saved images include the annotated boxes.

Here's a snippet you can insert after the boxes are drawn (which is after line 184 in `detect.py`):

```python
for i, det in enumerate(pred):  # detections per image
    ...
    if len(det):
        ...
        # Draw bounding boxes and labels of detections
        for *xyxy, conf, cls in reversed(det):
            ...
            # Add bbox to the image
            label = f'{names[int(cls)]} {conf:.2f}'
            plot_one_box(xyxy, im0, label=label, color=colors[int(cls)], line_thickness=3)

    # Save image with detections
    cv2.imwrite(f'{save_dir}/result_{frame_index}.jpg', im0)
    frame_index += 1
```

Make sure to define `frame_index = 0` before the loop starts, and `save_dir` should be the directory where you want to save the images. This will save each frame with the drawn bounding boxes as a separate image.
