### ISSUE TITLE
Understanding Hyperparameter Evolution in YOLOv5

### ISSUE THREAD

**Issue by DavidBaldsiefen** [ultralytics/yolov5#6762]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have read [similar issues](https://github.com/ultralytics/yolov5/issues/6345) but did not find the full answer to my question, so I want to ask here.

I just want to understand the basic process in YOLOv5s hyperparameter evolution algorithm. From what I took from `train.py` it works as follows:

1. All the hyperparameters of every generation are loaded, together with the fitness of that generation
2. The 5 best performing generations are put into a list
3. From each of the 5 generations, the fitness value is subtracted by the lowest fitness value in the generation, with the lowest generation being assigned a fitness value of 10^-6
4. The 5 generations are now sorted based on a weighted random order, with the weight being defined by the reduced fitness value of step 3
5. The top generation of the list is chosen (most likely, but not always, the one with the highest fitness will be chosen)
6. Mutate: https://github.com/ultralytics/yolov5/blob/66aaf5184d170482c250c3390e18b9c0068b7d5f/train.py#L602-L611
  6.1 For every hyperparameter, **with a 80% chance**, calculate a mutation factor:
  6.2 `gain(parameter) * normal_distribution(variance=1, mean=0) *  random_float(min=0, max=1) * sigma(**==0.2**) + 1`
  6.3 clip this mutation factor to a range of 0.3 to 3 => The resulting number _should_ have a mean of 1 with a variance of +-0.2*0.2=0.04
  6.4 multiply the hyperparamter with its mutation factor
  6.5 make sure to limit the hyperparamter to its range limits
7. Train the new generation with the new set of hyperparamters

This leads to three questions for me:

1. Is aboves explanation correct?
2. Is propability not 80% with a variance of 0.04 as opposed to a propability of 90% as mentioned in https://github.com/ultralytics/yolov5/issues/607 ?
3. Why is the mutation factor multiplied by a random float twice: `npr.randn(ng) * npr.random()`?

Thank you in advance!

**Comment by jerly-hjzhou** [comment]
For 1. I agree with you almost all explanation expect the calculation of variance, because this is multiplication of three random variables. 
For 2. I don't unstand the question. 
3. Maybe there is no reason，just preference or experience

**Comment by DavidBaldsiefen** [comment]
Thanks for the reply!

> For 1. I agree with you almost all explanation expect the calculation of variance, because this is multiplication of three random variables.

What would be the third next to `npr.randn(ng)` and `npr.random()`?

> For 2. I don't unstand the question. 

In the [official hyperparameter evolution guide](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution) it says that evolution happens with "a 90% probability and a 0.04 variance", but the code seems to use a 80% probability instead

**Comment by glenn-jocher** [comment]
@DavidBaldsiefen yes your explanation is basically correct. This is just a GA with elitism, mutation, no crossover.  Steps 1-5 is just parent selection, the rest is mutation subject to constraints (clipping etc.) and then eval of the fitness function.

It looks like the guide needs updating! I'll do that now, all done!

**Comment by myasser63** [comment]
> @DavidBaldsiefen yes your explanation is basically correct. This is just a GA with elitism, mutation, no crossover. Steps 1-5 is just parent selection, the rest is mutation subject to constraints (clipping etc.) and then eval of the fitness function.
> 
> It looks like the guide needs updating! I'll do that now, all done!

@glenn-jocher Can I know what type of mutation used and what are the constraints mentioned

**Comment by glenn-jocher** [comment]
@myasser63 evolution code is here. https://github.com/ultralytics/yolov5/blob/e00d02d78b772d7848689d8947238e4b05986a54/train.py#L572-L611

**Comment by Utsabab** [comment]
I am able to understand the evolution part. Every evolution produces a new mutated hyperparameter and its corresponding fitness value. Does that mean for the first 5 generation cycle, selecting 5 top performing generations == selecting all generation cycles? Is this statement true?

**Comment by glenn-jocher** [comment]
@Utsabab yes, you're correct. In the first cycle, selecting the top 5 performing generations effectively accounts for considering all the generation cycles, as it ensures that the best-performing hyperparameters from the initial generations contribute to the next cycle.
