### ISSUE TITLE
Print timestamp when object is detected in a video

### ISSUE THREAD

**Issue by safal-305** [ultralytics/yolov5#6765]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Hi. Suppose i have a video file and if i train images to detect objects and, use that model to detect objects in the video, can the yolov5 print out the time of the video when it detected the object?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by DavidNavarroSaiz** [comment]
Hi, I would like to work on this, is it ok for you?

**Comment by DavidNavarroSaiz** [comment]
https://github.com/ultralytics/yolov5/pull/7071

**Comment by safal-305** [comment]
> Hi, I would like to work on this, is it ok for you?

Hey. Were you able to pull it off?

**Comment by DavidNavarroSaiz** [comment]
Hey Safal, I'm waiting for a Reviewer :)

**Comment by safal-305** [comment]
> Hey Safal, I'm waiting for a Reviewer :)

Whats a reviewer? Do you mean you want someone to try out you code to checkout whether it works?

**Comment by DavidNavarroSaiz** [comment]
yeah right, i'm waiting for them to review the code and accept the merging, you can follow the process in the following link: https://github.com/ultralytics/yolov5/pull/7071

**Comment by glenn-jocher** [comment]
@DavidNavarroSaiz great work on the pull request! I appreciate your efforts and am grateful for your valuable contribution to YOLOv5. Our team will review and merge the code as soon as possible. In the meantime, feel free to join our developer community for further discussions. If you have any questions or need assistance, don't hesitate to reach out. Thank you!
