### ISSUE TITLE
0 missing, 4082 empty   or , 4082  missing, 0 empty .    what is the correct for background image in training?

### ISSUE THREAD

**Issue by VYRION-Ai** [ultralytics/yolov5#6775]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

i want to add images as background how should i add it as missing or empty? 
```
train: Scanning '/content/New_final_dataset/train/labels.cache' images and labels... 49066 found, 0 missing, 4082 empty, 7 corrupt: 100% 49066/49066 [00:00<?, ?it/s]

train: Scanning '/content/New_final_dataset/train/labels.cache' images and labels... 49066 found, 4082  missing, 0empty, 7 corrupt: 100% 49066/49066 [00:00<?, ?it/s]
```

**Comment by glenn-jocher** [comment]
@totoadel both are fine. Missing just means that no label file was found. Empty means an empty label file was found. Either way the image is added to train/val without any labels and is used as a background image.

**Comment by VYRION-Ai** [comment]
@glenn-jocher thank you
