### ISSUE TITLE
How to run only one YOLOv5 instance and detect object form multiple IP cameras?

### ISSUE THREAD

**Issue by PIjarihd** [ultralytics/yolov5#6776]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

For a single IP camera the comand to run YOLOv5 is like this:
`python detect.py --source rtsp://user:password@IpAddress --weights bestCWNU.pt --conf 0.25  `
For multiple IP Cameras, how should I enter the IP Camera information.
I do not want to use multiple instances of YOLOv5.

Because for multiple IP cameras, the ip and password will be different and I must have to change either command or in program. I do not know what changes do I need to make.

Please provide me a suggestion.

Thanks in advance.

**Comment by glenn-jocher** [comment]
@PIjarihd place all your addresses in a streams.txt file (one per line, no commas), and then:
```
python detect.py --source streams.txt
```

**Comment by PIjarihd** [comment]
> @PIjarihd place all your addresses in a streams.txt file (one per line, no commas), and then:
> 
> ```
> python detect.py --source streams.txt
> ```

This works. Thank You.
Do you know how to do the same in YOLOv4 (Darknet)? If you know, please help me. I using both YOLOv4 and YOLOv5 for my project. Thank You again.

**Comment by PIjarihd** [comment]
> @PIjarihd place all your addresses in a streams.txt file (one per line, no commas), and then:
> 
> ```
> python detect.py --source streams.txt
> ```
This works. The detection result is shown in multiple windows. However, is not it possible to view the result in only one frame? The input from multiple IP cameras need to be in time series I think. However, I am not sure how to do that. If you can, please help.

**Comment by glenn-jocher** [comment]
@PIjarihd our default implementation is multiple views for multiple cameras. You're free to customize the detect.py code to suit your requirements of course. That's the benefit of open-source code :)
