### ISSUE TITLE
YOLOv5 for Face Recognition/Verification

### ISSUE THREAD

**Issue by rtm-1dyakonov** [ultralytics/yolov5#6784]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi there!
I am strongly interested in using YOLOv5 in face verification web app. 

Is it possible though?

**Comment by RoudyES** [comment]
Hello @rtm-1dyakonov, check out [Deepcam's implementation](https://github.com/deepcam-cn/yolov5-face) if you want.
They used Yolov5 to train a very powerful face detector, they've also modified the head a bit to include the 5 face landmarks.
