### ISSUE TITLE
gpu version for windows 10

### ISSUE THREAD

**Issue by zyakubova86** [ultralytics/yolov5#6788]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi
Could you recommend gpu version for small budget? 
Thanks

**Comment by glenn-jocher** [comment]
@zyakubova86 you can use Google Colab. GPU for zero budget.
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb
