### ISSUE TITLE
Cannot find callable yolov5n in hubconf

### ISSUE THREAD

**Issue by ZhiZe-ZG** [ultralytics/yolov5#6789]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

```
model = torch.hub.load('ultralytics/yolov5','yolov5n', pretrained=True)
```

get 

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
C:\Users\ADMINI~1.000\AppData\Local\Temp/ipykernel_11836/521713222.py in <module>
----> 1 model = torch.hub.load('ultralytics/yolov5','yolov5n', pretrained=True)

D:\miniconda3\envs\POD\lib\site-packages\torch\hub.py in load(repo_or_dir, model, source, force_reload, verbose, skip_validation, *args, **kwargs)
    397         repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, verbose, skip_validation)
    398 
--> 399     model = _load_local(repo_or_dir, model, *args, **kwargs)
    400     return model
    401 

D:\miniconda3\envs\POD\lib\site-packages\torch\hub.py in _load_local(hubconf_dir, model, *args, **kwargs)
    425     hub_module = import_module(MODULE_HUBCONF, hubconf_path)
    426 
--> 427     entry = _load_entry_from_hubconf(hub_module, model)
    428     model = entry(*args, **kwargs)
    429 

D:\miniconda3\envs\POD\lib\site-packages\torch\hub.py in _load_entry_from_hubconf(m, model)
    233 
    234     if func is None or not callable(func):
--> 235         raise RuntimeError('Cannot find callable {} in hubconf'.format(model))
    236 
    237     return func

RuntimeError: Cannot find callable yolov5n in hubconf
```

### Environment

- YOLOv5  2021-10-8 torch 1.10.0 CUDA:0 (NVIDIA GeForce GTX 1060 6GB, 6144.0MB)
- Windows 10

### Minimal Reproducible Example

model = torch.hub.load('ultralytics/yolov5','yolov5n', pretrained=True)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ZhiZe-ZG YOLOv5n works correctly with PyTorch Hub:
<img width="938" alt="Screenshot 2022-02-26 at 10 36 30" src="https://user-images.githubusercontent.com/26833433/155838130-9b647bfb-d1b1-4ff8-957f-aab098407e14.png">

Your cache is likely out of date. Update with:

- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`

**Comment by ZhiZe-ZG** [comment]
Thanks, that works.  @ @glenn-jocher
