### ISSUE TITLE
ModuleNotFoundError: No module named 'models.yolo'

### ISSUE THREAD

**Issue by tangxiaochu123230** [ultralytics/yolov5#68]
Traceback (most recent call last):
  File "C:/projects/YOLOV5/yolov5/train.py", line 412, in <module>
    train(hyp)
  File "C:/projects/YOLOV5/yolov5/train.py", line 88, in train
    model.load_state_dict(torch.load(new_weights))
  File "C:\Python36\lib\site-packages\torch\serialization.py", line 368, in load
    return _load(f, map_location, pickle_module)
  File "C:\Python36\lib\site-packages\torch\serialization.py", line 542, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'models.yolo'

**Comment by glenn-jocher** [comment]
@tangxiaochu123230 please provide minimum viable code to reproduce your issue, otherwise we can not help you.

**Comment by tangxiaochu123230** [comment]
I solved the problem by add  __init__.py to models folder

**Comment by glenn-jocher** [comment]
@tangxiaochu123230 perfect. This has already been done in a commit recently. Pleasee update your repo with git pull or reclone.

**Comment by medasuryatej** [comment]
> I solved the problem by add **init**.py to models folder

I have added the __init__.py (empty file) to the models folder, but still I get the error no module named 'models.yolo'

**Comment by iMeleon** [comment]
In my case i have custom folder-module "models" in my working dir. So i rename this folder and solve  this error

**Comment by gribkovmn** [comment]
Is there any other way except renaming the model folder? I'm trying to get yolov5 integrated in a MVC application where `models` directory exists in the working directory, so renaming the `models` directory will ruin its architecture.

**Comment by glenn-jocher** [comment]
@gribkovmn you could try simply loading YOLOv5 models via PyTorch Hub:

## YOLOv5 Tutorials

* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
