### ISSUE TITLE
Training YOLOv5 to detect fire

### ISSUE THREAD

**Issue by spacewalk01** [ultralytics/yolov5#6800]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Created a repo for training yolov5 to predict fire: 
https://github.com/spacewalk01/Yolov5-Fire-Detection

**Comment by glenn-jocher** [comment]
@spacewalk01 awesome!!

**Comment by Guttappa1238** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.
> 
> ### Question
> Created a repo for training yolov5 to predict fire: https://github.com/spacewalk01/Yolov5-Fire-Detection
> 
> ### Additional
> _No response_

@spacewalk01  Nice work!

**Comment by spacewalk01** [comment]
Thanks
