### ISSUE TITLE
Usage of hsv augmentation

### ISSUE THREAD

**Issue by developer0hye** [ultralytics/yolov5#6802]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi @glenn-jocher !

I have just opened my work on object detection.

https://github.com/MarkAny-Vision-AI/CenterNeXt

In this project, I used [the hsv augmentation function](https://github.com/ultralytics/yolov5/blob/master/utils/augmentations.py#L47-L60) implemented in this project.

https://github.com/MarkAny-Vision-AI/CenterNeXt/blob/main/utils/data/transforms.py#L359-L370

Should I cite yolov5?

**Comment by glenn-jocher** [comment]
@developer0hye for a minor function like this I don't think you need to cite anything, but you're free to if you want to!

**Comment by developer0hye** [comment]
@glenn-jocher 
Thanks! I always learn many things from you.
