### ISSUE TITLE
How to load custom model with torchhub?

### ISSUE THREAD

**Issue by RoyCopter** [ultralytics/yolov5#6804]
Hey, I try to load custom model with the next code:

```     
        # # Model
        self.model = torch.hub.load('ultralytics/yolov5', 'custom',path="yolov5l-custom.pt",force_reload=True,autoshape=True)  # or yolov5m, yolov5l, yolov5x, custom

```

but I get the next error:
```    
Exception: Can't get attribute 'CBAM' on <module 'models.common' from 
models/common.py'>. Cache may be out of date, try `force_reload=True` or see https://github.com/ultralytics/yolov5/issues/36 for help.
```

How can I fix that?

**Comment by Guttappa1238** [comment]
Hi @RoyCopter, I think  your code is out of date. Use `git pull` to update your code, or simply git clone `https://github.com/ultralytics/yolov5` to download a new copy.

And If you are running custom models with local repo try this:
`model = torch.hub.load('path/to/yolov5', 'custom', path='path/to/best.pt', source='local')  # local repo`

**Comment by Blankeos** [comment]
Does this still work in Torch 2.2.2?

**Comment by glenn-jocher** [comment]
@Blankeos hi there! 😊 For Torch 2.2.2, you might encounter some compatibility issues with our current YOLOv5 implementation. We generally recommend using the Torch version specified in our [Ultralytics Docs](https://docs.ultralytics.com/yolov5/) for optimal performance and compatibility. Keeping your environment aligned with our recommendations ensures smoother operation and helps avoid unexpected issues. If you've already encountered specific errors, please feel free to share them for more targeted advice. Thanks for reaching out!
