### ISSUE TITLE
Running YOLOv5 with Kubuntu

### ISSUE THREAD

**Issue by edehino** [ultralytics/yolov5#6806]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I tried running yolov5 using Ubuntu 20.04 and it works well. Then I used another device with Kubuntu 18.04 and I am having issues. The first error is
`SyntaxError: Non-ASCII character '\xf0' in file train.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details`

Then I read what was written on the link provided so I added:
`# -*- coding: utf-8 -*-`

at line 1 of train.py.

But now it shows another error:
` File "train.py", line 85
    LOGGER.info(colorstr('hyperparameters: ') + ', '.join(f'{k}={v}' for k, v in hyp.items()))`

I hope someone could help me out with this. Thanks!

**Comment by glenn-jocher** [comment]
@edehino train.py hyperparameter printing is just a console printout of your hyp values. You can safely comment it.
