### ISSUE TITLE
How to use realsense2 in local ?

### ISSUE THREAD

**Issue by sishihara0706** [ultralytics/yolov5#6812]
I tried yolov5 and realsense on jetson xavier.
But, I cannot run.

[Environment]
ubuntu, Jetson Xavier, realsense(model:d435)

I tried this command.
"python3 detect.py --source 0"
the answer is this.
-----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "detect.py", line 257, in <module>
    main(opt)
  File "detect.py", line 252, in main
    run(**vars(opt))
  File "/home/ai/.local/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 105, in run
    dataset = LoadStreams(source, img_size=imgsz, stride=stride, auto=pt)
  File "/home/ai/yolov5/utils/datasets.py", line 309, in __init__
    assert cap.isOpened(), f'{st}Failed to open {s}'
AssertionError: 1/1: 0... Failed to open 0
-----------------------------------------------------------------------------------------------------

When using RealSense, is there an option at runtime in detect.py?
![IMG-8718](https://user-images.githubusercontent.com/49329965/156106697-417cc282-6c3a-493f-9fa1-4f6497ceac7f.JPG)

**Comment by glenn-jocher** [comment]
@sishihara0706 YOLOv5 uses cv2 for webcam detection. If simple cv2 webcam code doesn't work then you should start there. See https://subscription.packtpub.com/book/application-development/9781785283932/3/ch03lvl1sec28/accessing-the-webcam

**Comment by mantues** [comment]
@sishihara0706 
Realsense has a number of usb devices mounted.
In my environment, the IR camera was channel 2 and the RGB camera was channel 4.
Try the following code.
RGBcamera `python detect.py --source 4`
IRcamera `python detect.py --source 2`
