### ISSUE TITLE
How to determine the decay tau value in ModelEMA

### ISSUE THREAD

**Issue by CanyonWind** [ultralytics/yolov5#6815]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, as the title says, I wonder what `tau` means and whether people could share some thoughts on how to determine the `tau` value in `ModelEMA`?  

https://github.com/ultralytics/yolov5/blob/0f819919adca1eb951376430695d3a790e0b7455/utils/torch_utils.py#L297-L311

I'm working on a panoptic segmentation task and implementing EMA there. Since the differences in many ways, I believe `tau` needs to adjust( not `2000` anymore). In my several toy experiments, `tau` influences the performances quite a bit. It would be appreciated if any comments could be shared.

**Comment by glenn-jocher** [comment]
@CanyonWind tau is the exponential function time constant which sets how fast the function decays:
https://en.wikipedia.org/wiki/Exponential_decay

In our case tau simply controls how fast the EMA decay ramps from zero to it's steady state value (default 0.9999). Generally the EMA hurts performance in early training and help performance in later training, so the tau variable allows the decay to gradually ramp it's influence.

The intention is to provide improved results in all stages of training using this system. To get the full EMA benefit you must train sufficient epochs, i.e. verify your val losses are overfitting, or else you are not training long enough.

**Comment by CanyonWind** [comment]
Thanks for these, @glenn-jocher. I was aware how ema works and its benefit. Just not sure how to set the tau value specifically, e.g. for 540k iterations training process, would it still make sense to only ramp the first 2k iters?

I tried several toy models with only 20k total training iters. Set tau from 2k to 5k, 10k, 20k would gradually increase the toy experiment final performance. Since training the full 540k iterations is a quite big commitment, I would love to hear your thoughts on **how did you determine your tau in the first place**?

And btw, man, what `tau` is short for?

**Comment by glenn-jocher** [comment]
@CanyonWind tau is a greek letter, it's not short for anything. Use default settings for best results in most use cases.

**Comment by CanyonWind** [comment]
I guess it works best for the detection task with `τ` set to 2k, as default. 

I'm working on a different task and that's the reason why I wonder how did you determine the `τ` value in the first place. Any thoughts would be appreciated.

**Comment by glenn-jocher** [comment]
@CanyonWind 👋 Hello! Thanks for asking about improving YOLOv5 🚀 training results. 

Most of the time good results can be obtained with no changes to the models or training settings, **provided your dataset is sufficiently large and well labelled**. If at first you don't get good results, there are steps you might be able to take to improve, but we always recommend users **first train with all default settings** before considering any changes. This helps establish a performance baseline and spot areas for improvement.

Once you've done that there about 25 other hyperparameters besides tau that also affect performance significantly, so I'm not sure why the focus on tau, but just like any other hyperparameter optimal values are found through searches or trial and error. ML is an empirical science.

**Comment by CanyonWind** [comment]
I'm working on a paper and plan to squeeze out each trick's boosting performance at the ultimate. EMA is one of them; hence, I care about the details. Thanks anyway though, I might post something here later if/when I have some more concrete conclusions, in case anyone else may find that helpful in the future.

**Comment by glenn-jocher** [comment]
@CanyonWind then just do a grid search, i.e. take the default and if you have an 8 GPU machine evaluate 7 values: default times 1/8, 1/4, 1/2, 1, 2, 4, 8 etc.

EDIT: alternatively you could add tau and the EMA constant to the hyps and then evolve all hyps togethor (better solution but requires more resources and updates to repo).
