### ISSUE TITLE
Process stuck when I train yolov5m and yolov5l

### ISSUE THREAD

**Issue by flysssss** [ultralytics/yolov5#6818]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

When I train yolo5m and yolo5l, and iteratively train for 80-120epoch, there will be a stuck phenomenon, the GPU occupancy rate is 100%, and no error is reported. But it cannot be trained; while yolo5s can complete 300 epoch iteration training. what should I do？
![image](https://user-images.githubusercontent.com/100752067/156308092-ee7c69eb-e69d-471a-a080-0eeabc3a68dc.png)
![image](https://user-images.githubusercontent.com/100752067/156308147-90ad328a-f985-4739-b823-9a92f46a93ad.png)
The log output looks like this：
![image](https://user-images.githubusercontent.com/100752067/156308399-2236d1e2-24b9-4b53-a034-9e2147a7cde3.png)
The progress bar never continues。

### Environment

YOLOv5 🚀 2022-2-25 torch 1.9.0+cu102 CUDA:2 (Tesla K80, 11441MiB)
                                                         CUDA:3 (Tesla K80, 11441MiB)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@flysssss sometimes training fails due to lack of resources. This can be CUDA out of memory, RAM limitations, CPU thread saturation etc., which seems like your case due to the high CUDA utilization. Perhaps cut your batch size down and retry at a lower CUDA memory utilization, i.e. 80% instead of 90%+

**Comment by flysssss** [comment]
@glenn-jocher Now the problem seems to appear again, I am trying to train on my own dataset, about 230,000 images. 
This time it is stuck in the second epoch, and now the GPU utilization is 0
The detailed log is as follows：
![image](https://user-images.githubusercontent.com/100752067/156336561-b549c91c-a862-4cf8-a056-560f11683088.png)
![image](https://user-images.githubusercontent.com/100752067/156336683-c5f5868a-c64d-44c9-a4a1-b9da84a73b9d.png)
![image](https://user-images.githubusercontent.com/100752067/156336773-a1d0a9f2-26ae-4379-92d9-a7a669d78f22.png)
![image](https://user-images.githubusercontent.com/100752067/156336943-91aeb909-ef4f-433f-af34-4aa75fd1f008.png)

**Comment by glenn-jocher** [comment]
@flysssss it appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual [Python 3.9](https://www.python.org/) environment, clone the latest repo ([code changes daily](https://github.com/ultralytics/yolov5/commits/master)), and `pip install` [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) again from scratch.

💡 ProTip! Try one of our verified environments below if you are having trouble with your local environment.


## Requirements

[**Python>=3.7.0**](https://www.python.org/) with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) installed including [**PyTorch>=1.7**](https://pytorch.org/get-started/locally/). To get started:
```bash
git clone https://github.com/ultralytics/yolov5  # clone
cd yolov5
pip install -r requirements.txt  # install
```

[Models](https://github.com/ultralytics/yolov5/tree/master/models) and [datasets](https://github.com/ultralytics/yolov5/tree/master/data) download automatically from the latest YOLOv5 [release](https://github.com/ultralytics/yolov5/releases) when first requested.

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), validation ([val.py](https://github.com/ultralytics/yolov5/blob/master/val.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/export.py)) on MacOS, Windows, and Ubuntu every 24 hours and on every commit.

**Comment by flysssss** [comment]
@glenn-jocher I'm also confused ,because yolov5s works fine for the first time on a small dataset . about 5000 images. The full training 300 epcho, and the inference effect is also great. Next I will try to pull the docker image again.

**Comment by glenn-jocher** [comment]
@flysssss yeah definitely the best way to resolve local environment issues is just to run in Docker. We run all our trainings in Docker, including the official models.
