### ISSUE TITLE
loading model stuck on Autoshape

### ISSUE THREAD

**Issue by amroghoneim** [ultralytics/yolov5#6821]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

After installing yolov5 and the requirements, as well as training my own custom model, I tried to load the custom model as follows:

```

import torch

model= torch.hub.load(('ultralytics/yolov5'),'custom',
                           path=r'models/train_yolov5s/weights/last.pt',
                           force_reload=True)
```
The output is the following:
```
Downloading: "https://github.com/ultralytics/yolov5/archive/master.zip" to /root/.cache/torch/hub/master.zip
[2022-03-02T11:13:46] INFO [yolov5.select_device:95] YOLOv5 🚀 2022-3-2 torch 1.9.1+cu102 CPU

[2022-03-02T11:13:46] INFO [yolov5.fuse:219] Fusing layers...
[2022-03-02T11:13:46] INFO [yolov5.model_info:249] Model Summary: 213 layers, 7015519 parameters, 0 gradients
[2022-03-02T11:13:46] INFO [yolov5.__init__:490] Adding AutoShape...
```
Where the model initialization is stuck in this step.

How do I go about solving this?

### Environment

YOLOv5 🚀 2022-3-2 torch 1.9.1+cu102 CPU
ubuntu environment (WSL for windows) with python version 3.6.9

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@amroghoneim 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem. Also note that while YOLOv5 may work with Python 3.6 the official requirements are python >= 3.7.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by SoroushMaleki** [comment]
Hello, hope all is well.
@amroghoneim
@jkocherhans 
Have you been able to find the solution to this issue?

I have the very exact same problem, where after setting the "force_reload=True" parameter, torch is not able to continue loading the YOLOv5 structure and it gets stuck at the adding autoshape stage.

**Comment by gstvschlz** [comment]
> Hello, hope all is well. @amroghoneim @jkocherhans Have you been able to find the solution to this issue?
> 
> I have the very exact same problem, where after setting the "force_reload=True" parameter, torch is not able to continue loading the YOLOv5 structure and it gets stuck at the adding autoshape stage.

It also happened to me while running the YOLOv5 model in a Docker container, after a few minutes the service was up and running as expected. Try to refresh the log screen.

**Comment by fangyuan468** [comment]
```python
model = torch.hub.load('./code/python/yolov5', 'custom',
                       path='./best.pt', source='local', force_reload=True)
```

```cmd
Python 3.7.0 required by YOLOv5, but Python 3.6.5 is currently installed
YOLOv5  v6.1-295-gf8722b4 Python-3.6.5 torch-1.7.1+cu110 CUDA:0 (NVIDIA GeForce RTX 3060, 12288MiB)

Fusing layers...
YOLOv5s summary: 213 layers, 7012822 parameters, 0 gradients, 15.8 GFLOPs
Adding AutoShape...
```
I've been waiting for 3 hours, and I'm still stuck here

**Comment by fangyuan468** [comment]
> 



> ```python
> model = torch.hub.load('./code/python/yolov5', 'custom',
>                        path='./best.pt', source='local', force_reload=True)
> ```
> 
> ```batchfile
> Python 3.7.0 required by YOLOv5, but Python 3.6.5 is currently installed
> YOLOv5  v6.1-295-gf8722b4 Python-3.6.5 torch-1.7.1+cu110 CUDA:0 (NVIDIA GeForce RTX 3060, 12288MiB)
> 
> Fusing layers...
> YOLOv5s summary: 213 layers, 7012822 parameters, 0 gradients, 15.8 GFLOPs
> Adding AutoShape...
> ```
> 
> 我已经等了3个小时了，我仍然被困在这里

I solved my problem by uninstalling the pip installation of opencv-python and re-downloading the opencv source code to compile and install it.

That's it, it works perfectly!

**Comment by glenn-jocher** [comment]
@767829413 oh strange. The AutoShape wrapper should take < 1s

**Comment by fangyuan468** [comment]
> > 
> 
> > ```python
> > model = torch.hub.load('./code/python/yolov5', 'custom',
> >                        path='./best.pt', source='local', force_reload=True)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```batchfile
> > Python 3.7.0 required by YOLOv5, but Python 3.6.5 is currently installed
> > YOLOv5  v6.1-295-gf8722b4 Python-3.6.5 torch-1.7.1+cu110 CUDA:0 (NVIDIA GeForce RTX 3060, 12288MiB)
> > 
> > Fusing layers...
> > YOLOv5s summary: 213 layers, 7012822 parameters, 0 gradients, 15.8 GFLOPs
> > Adding AutoShape...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我已经等了3个小时了，我仍然被困在这里
> 
> I solved my problem by uninstalling the pip installation of opencv-python and re-downloading the opencv source code to compile and install it.
> 
> That's it, it works perfectly!

Well, my problem has come up again, stuck in the same position.

```python
import torch

model = torch.hub.load(('ultralytics/yolov5'), 'custom',
                       path=r'C:/Users/76782/Downloads/best.pt',
                       force_reload=False)
```

```cmd
Using cache found in C:\Users\76782/.cache\torch\hub\ultralytics_yolov5_master
Python 3.7.0 required by YOLOv5, but Python 3.6.5 is currently installed
YOLOv5  2022-7-21 Python-3.6.5 torch-1.7.1+cu110 CUDA:0 (NVIDIA GeForce RTX 3060, 12288MiB)

Fusing layers...
YOLOv5s summary: 213 layers, 7012822 parameters, 0 gradients, 15.8 GFLOPs
Adding AutoShape...

```

My computer can be used to train the data.

```cmd
(base) C:\Users\76782\Documents\code\python\yolov5>python train.py --img 600 --batch 16 --epochs 3000 --data ./mydata/data.yaml --cfg ./models/yolov5s.yaml --weights "" --workers 0 --name cfhd  --cache
train: weights=, cfg=./models/yolov5s.yaml, data=./mydata/data.yaml, hyp=data\hyps\hyp.scratch-low.yaml, epochs=3000, batch_size=16, imgsz=600, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, noplots=False, evolve=None, bucket=, cache=ram, image_weights=False, device=, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=0, project=runs\train, name=cfhd, exist_ok=False, quad=False, cos_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, seed=0, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest
github: skipping check (offline), for updates see https://github.com/ultralytics/yolov5
Python 3.7.0 required by YOLOv5, but Python 3.6.5 is currently installed
YOLOv5  v6.1-307-g92e47b8 Python-3.6.5 torch-1.7.1+cu110 CUDA:0 (NVIDIA GeForce RTX 3060, 12288MiB)

hyperparameters: lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0
Weights & Biases: run 'pip install wandb' to automatically track and visualize YOLOv5  runs (RECOMMENDED)
TensorBoard: Start with 'tensorboard --logdir runs\train', view at http://localhost:6006/
2022-07-21 23:12:49.743821: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll

                 from  n    params  module                                  arguments
  0                -1  1      3520  models.common.Conv                      [3, 32, 6, 2, 2]
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]
  2                -1  1     18816  models.common.C3                        [64, 64, 1]
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]
  4                -1  2    115712  models.common.C3                        [128, 128, 2]
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]
  6                -1  3    625152  models.common.C3                        [256, 256, 3]
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]
  8                -1  1   1182720  models.common.C3                        [512, 512, 1]
  9                -1  1    656896  models.common.SPPF                      [512, 512, 5]
 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 12           [-1, 6]  1         0  models.common.Concat                    [1]
 13                -1  1    361984  models.common.C3                        [512, 256, 1, False]
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 16           [-1, 4]  1         0  models.common.Concat                    [1]
 17                -1  1     90880  models.common.C3                        [256, 128, 1, False]
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]
 19          [-1, 14]  1         0  models.common.Concat                    [1]
 20                -1  1    296448  models.common.C3                        [256, 256, 1, False]
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]
 22          [-1, 10]  1         0  models.common.Concat                    [1]
 23                -1  1   1182720  models.common.C3                        [512, 512, 1, False]
 24      [17, 20, 23]  1     16182  models.yolo.Detect                      [1, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
YOLOv5s summary: 270 layers, 7022326 parameters, 7022326 gradients, 15.9 GFLOPs

AMP: checks passed
WARNING: --img-size 600 must be multiple of max stride 32, updating to 608
Scaled weight_decay = 0.0005
optimizer: SGD with parameter groups 57 weight (no decay), 60 weight, 60 bias
train: Scanning 'C:\Users\76782\Documents\code\python\yolov5\mydata\train\labels.cache' images and labels... 768 found,
train: Caching images (0.9GB ram): 100%|██████████| 768/768 [00:00<00:00, 1600.01it/s]
val: Scanning 'C:\Users\76782\Documents\code\python\yolov5\mydata\valid\labels.cache' images and labels... 321 found, 0
val: Caching images (0.4GB ram): 100%|██████████| 321/321 [00:00<00:00, 738.78it/s]
Plotting labels to runs\train\cfhd\labels.jpg...

AutoAnchor: 3.81 anchors/target, 0.992 Best Possible Recall (BPR). Current anchors are a good fit to dataset
Image sizes 608 train, 608 val
Using 0 dataloader workers
Logging results to runs\train\cfhd
Starting training for 3000 epochs...

     Epoch   gpu_mem       box       obj       cls    labels  img_size
    0/2999     3.28G    0.1059   0.02041         0        26       608: 100%|██████████| 48/48 [00:24<00:00,  1.97it/s]

```

**Comment by fangyuan468** [comment]
> > > 
> > 
> > 
> > > ```python
> > > model = torch.hub.load('./code/python/yolov5', 'custom',
> > >                        path='./best.pt', source='local', force_reload=True)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```batchfile
> > > Python 3.7.0 required by YOLOv5, but Python 3.6.5 is currently installed
> > > YOLOv5  v6.1-295-gf8722b4 Python-3.6.5 torch-1.7.1+cu110 CUDA:0 (NVIDIA GeForce RTX 3060, 12288MiB)
> > > 
> > > Fusing layers...
> > > YOLOv5s summary: 213 layers, 7012822 parameters, 0 gradients, 15.8 GFLOPs
> > > Adding AutoShape...
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 我已经等了3个小时了，我仍然被困在这里
> > 
> > 
> > I solved my problem by uninstalling the pip installation of opencv-python and re-downloading the opencv source code to compile and install it.
> > That's it, it works perfectly!
> 
> Well, my problem has come up again, stuck in the same position.
> 
> ```python
> import torch
> 
> model = torch.hub.load(('ultralytics/yolov5'), 'custom',
>                        path=r'C:/Users/76782/Downloads/best.pt',
>                        force_reload=False)
> ```
> 
> ```batchfile
> Using cache found in C:\Users\76782/.cache\torch\hub\ultralytics_yolov5_master
> Python 3.7.0 required by YOLOv5, but Python 3.6.5 is currently installed
> YOLOv5  2022-7-21 Python-3.6.5 torch-1.7.1+cu110 CUDA:0 (NVIDIA GeForce RTX 3060, 12288MiB)
> 
> Fusing layers...
> YOLOv5s summary: 213 layers, 7012822 parameters, 0 gradients, 15.8 GFLOPs
> Adding AutoShape...
> ```
> 
> My computer can be used to train the data.
> 
> ```batchfile
> (base) C:\Users\76782\Documents\code\python\yolov5>python train.py --img 600 --batch 16 --epochs 3000 --data ./mydata/data.yaml --cfg ./models/yolov5s.yaml --weights "" --workers 0 --name cfhd  --cache
> train: weights=, cfg=./models/yolov5s.yaml, data=./mydata/data.yaml, hyp=data\hyps\hyp.scratch-low.yaml, epochs=3000, batch_size=16, imgsz=600, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, noplots=False, evolve=None, bucket=, cache=ram, image_weights=False, device=, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=0, project=runs\train, name=cfhd, exist_ok=False, quad=False, cos_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, seed=0, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest
> github: skipping check (offline), for updates see https://github.com/ultralytics/yolov5
> Python 3.7.0 required by YOLOv5, but Python 3.6.5 is currently installed
> YOLOv5  v6.1-307-g92e47b8 Python-3.6.5 torch-1.7.1+cu110 CUDA:0 (NVIDIA GeForce RTX 3060, 12288MiB)
> 
> hyperparameters: lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0
> Weights & Biases: run 'pip install wandb' to automatically track and visualize YOLOv5  runs (RECOMMENDED)
> TensorBoard: Start with 'tensorboard --logdir runs\train', view at http://localhost:6006/
> 2022-07-21 23:12:49.743821: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
> 
>                  from  n    params  module                                  arguments
>   0                -1  1      3520  models.common.Conv                      [3, 32, 6, 2, 2]
>   1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]
>   2                -1  1     18816  models.common.C3                        [64, 64, 1]
>   3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]
>   4                -1  2    115712  models.common.C3                        [128, 128, 2]
>   5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]
>   6                -1  3    625152  models.common.C3                        [256, 256, 3]
>   7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]
>   8                -1  1   1182720  models.common.C3                        [512, 512, 1]
>   9                -1  1    656896  models.common.SPPF                      [512, 512, 5]
>  10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]
>  11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
>  12           [-1, 6]  1         0  models.common.Concat                    [1]
>  13                -1  1    361984  models.common.C3                        [512, 256, 1, False]
>  14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]
>  15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
>  16           [-1, 4]  1         0  models.common.Concat                    [1]
>  17                -1  1     90880  models.common.C3                        [256, 128, 1, False]
>  18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]
>  19          [-1, 14]  1         0  models.common.Concat                    [1]
>  20                -1  1    296448  models.common.C3                        [256, 256, 1, False]
>  21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]
>  22          [-1, 10]  1         0  models.common.Concat                    [1]
>  23                -1  1   1182720  models.common.C3                        [512, 512, 1, False]
>  24      [17, 20, 23]  1     16182  models.yolo.Detect                      [1, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
> YOLOv5s summary: 270 layers, 7022326 parameters, 7022326 gradients, 15.9 GFLOPs
> 
> AMP: checks passed
> WARNING: --img-size 600 must be multiple of max stride 32, updating to 608
> Scaled weight_decay = 0.0005
> optimizer: SGD with parameter groups 57 weight (no decay), 60 weight, 60 bias
> train: Scanning 'C:\Users\76782\Documents\code\python\yolov5\mydata\train\labels.cache' images and labels... 768 found,
> train: Caching images (0.9GB ram): 100%|██████████| 768/768 [00:00<00:00, 1600.01it/s]
> val: Scanning 'C:\Users\76782\Documents\code\python\yolov5\mydata\valid\labels.cache' images and labels... 321 found, 0
> val: Caching images (0.4GB ram): 100%|██████████| 321/321 [00:00<00:00, 738.78it/s]
> Plotting labels to runs\train\cfhd\labels.jpg...
> 
> AutoAnchor: 3.81 anchors/target, 0.992 Best Possible Recall (BPR). Current anchors are a good fit to dataset
> Image sizes 608 train, 608 val
> Using 0 dataloader workers
> Logging results to runs\train\cfhd
> Starting training for 3000 epochs...
> 
>      Epoch   gpu_mem       box       obj       cls    labels  img_size
>     0/2999     3.28G    0.1059   0.02041         0        26       608: 100%|██████████| 48/48 [00:24<00:00,  1.97it/s]
> ```

Well, I deleted all the files in the C:\Users\76782\.cache\torch\hub folder, and then tried again. my system is Windows 11. 

```cmd
Using cache found in C:\Users\76782/.cache\torch\hub\ultralytics_yolov5_master
Python 3.7.0 required by YOLOv5, but Python 3.6.5 is currently installed
YOLOv5  2022-7-21 Python-3.6.5 torch-1.7.1+cu110 CUDA:0 (NVIDIA GeForce RTX 3060, 12288MiB)

Fusing layers...
YOLOv5s summary: 213 layers, 7012822 parameters, 0 gradients, 15.8 GFLOPs
Adding AutoShape...
Model loaded successfully
image 1/1: 600x600 (no detections)
Speed: 4.0ms pre-process, 11.5ms inference, 0.5ms NMS per image at shape (1, 3, 608, 608)

image 1/1: 600x600 (no detections)
Speed: 5.0ms pre-process, 8.5ms inference, 0.5ms NMS per image at shape (1, 3, 608, 608)
```

**Comment by davidsasso** [comment]
I'm running into the same issue, does anyone made an improvement on this? I'm thinking on disable this image saving into runs's folder but I was not able to find where to make that configuration.

![image](https://user-images.githubusercontent.com/38566385/189411290-260aad88-301a-40c6-aa14-e33dcf1f59ba.png)

**Comment by glenn-jocher** [comment]
@davidsasso 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by davidsasso** [comment]
This is an example code:
   
```
 import torch

    YOLOv5_PATH = 'open_source/repos/yolov5'
    custom_model_path = f'models/model.pt'

    model = torch.hub.load(YOLOv5_PATH, 'custom', path=custom_model_path, force_reload=False, source='local')

    detections = model(frame)
```

where "frame" is an image adquired by a webcam using opencv.

It worked just fine, but suddenly it gets stuck on Adding AutoShape step and I do not know why. I 've already take a look at the hub.load function but I woul not be able to make an improvement on this.

**Comment by glenn-jocher** [comment]
@davidsasso I'm unable to reproduce any issue using your code. PyTorch Hub inference with AutoShape works correctly:
<img width="1293" alt="Screenshot 2022-09-16 at 00 36 04" src="https://user-images.githubusercontent.com/26833433/190520536-f9ac0d7b-7afa-4b9c-9326-c3383827499c.png">

**Comment by sidhjeya** [comment]
i have this problem .Any solution?

**Comment by glenn-jocher** [comment]
@sidhjeya hi there! Thanks for reaching out about the issue you're experiencing. In order to assist you better, could you please provide some more details about the problem you're facing with YOLOv5? Specifically, it would be helpful if you can provide the following information:

1. A description of the problem you're encountering.
2. Steps to reproduce the issue.
3. Any error messages or stack traces you've received.
4. Any relevant code snippets or configurations you're using.
5. The version of YOLOv5 you're using.

With this information, we'll be able to better understand the issue and provide you with appropriate guidance or solutions. Looking forward to your response!

**Comment by razi-tm** [comment]
vpn solved this (freezing at adding autoshape) for me.
@sidhjeya
