### ISSUE TITLE
One-cycle with cosine和one-cycle linear

### ISSUE THREAD

**Issue by Wanghe1997** [ultralytics/yolov5#6827]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

作者您好，在v6.1版本的Release中，您提到了：One-cycle with cosine replace with one-cycle linear for improved results
请问cos-lr和linear-lr哪个对模型的训练结果更好呢？如果是使用cos-lr，训练时需要键入--cos-lr；如果是使用linear-lr，训练时需要键入--liner-lr。我这么理解对吗？如果都不指定，程序默认使用哪种lr？谢谢

**Comment by zlj-ky** [comment]
@Wanghe1997 我的理解：默认值是 cos-lr，只有你指定 --liner-lr 时，才会使用 linear-lr 
![图片](https://user-images.githubusercontent.com/74093297/156463067-5c81324f-ae66-47c4-8ed8-20ccd38221f9.png)
