### ISSUE TITLE
Is there any way to force YoloV5 to use only images with annotations? 

### ISSUE THREAD

**Issue by dazzle-me** [ultralytics/yolov5#6829]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I labeled part of the images in my dataset (let's say 250/3000) and I placed all of them inside "images" folder, and I placed labels in "labels" folder (empty ones too).

Is there a way to force YoloV5 to use only labeled images during training, because in practice the amount of unlabeled images should be about 10% of all training data, however in my case it's ~90% :D 

Because of that, my model doesn't train.

What I want to ask is if there is any way how I can pass some argument to train.py script to force it to use only images with annotations? Or any other way?

The thing is that markup process is still not finished, but I want to start to train my model, and I don't want to change "images" dir and rather than that I want to change "labels" dir (also, deleting all of the emtpy label files doesn't help)

Maybe it's too specific, but it seems like a good feature.

**Comment by dazzle-me** [comment]
![image](https://user-images.githubusercontent.com/57013219/156411632-0c496fcd-77b3-48cf-8c7e-30aec35bf58a.png)

Found my answer here, instead of specifying whole directories I can specify file with images to use

**Comment by glenn-jocher** [comment]
@dazzle-me yes you can point to a *.txt file with a list of images to train from. This is how coco.yaml works:

https://github.com/ultralytics/yolov5/blob/63ddb6f0d06f6309aa42bababd08c859197a27af/data/coco.yaml#L2-L15

**Comment by Mohammed-Elias** [comment]
@glenn-jocher  but How to change the yaml file from `train.py`, because I have the dataset on the cloud, `ClearML` for my MLOps, so I couldn't find a way to use path, train or val as a variable in `train.py`, any suggestions ?
