### ISSUE TITLE
YOLOv5-v6.1训练结束后，exp文件夹中没有生成labels.jpg和labels_correlogram.jpg两个文件

### ISSUE THREAD

**Issue by Wanghe1997** [ultralytics/yolov5#6833]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

作者您好，我的运行指令是python train.py --img-size 640 --epochs 300 --batch-size 16 --data data/garbage.yaml --cfg models/yolov5s-garbage.yaml --weights '' --project runs/train/yolov5s/devide/noautoanchor --patience 500 --noautoanchor --cos-lr
最终训练结束后exp文件夹的内容为：
![image](https://user-images.githubusercontent.com/45507837/156491621-5fa8f40b-c3f5-4626-98f3-9e75c52f6886.png)

因为我想做--noautoanchor为true和false时的实验对比，是不是因为开启了--noautoanchor导致了train.py没有调用plots.py/plot_labels函数？所以没有生成labels.jpg和labels_correlogram.jpg两个文件？您能不能检查一下程序的逻辑，改成无论--noautoanchor为True或者False，都能生成上述两个jpg文件？或者是因为别的原因？你能否检查下train.py的逻辑呢？谢谢您

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by 0Kirby** [comment]
### I also encountered this problem. 
After I commented "**Timeout(30)**" to "**#Timeout(30)**" , labels.jpg and labels_correlogram.jpg will be generated.
![image](https://user-images.githubusercontent.com/26472465/156585452-25f0d682-50c3-481c-8cb7-eb6aae3a8186.png)
