### ISSUE TITLE
what is the best hardware to run yolov5 in real time  projects?

### ISSUE THREAD

**Issue by VYRION-Ai** [ultralytics/yolov5#6834]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I will download my network to hardware devices for using in real time  projects(using camera)  ,
 I want to know which is the best which is hard to work with
Is it justin nano or raspberry pi or something else i have one shot. please help

**Comment by glenn-jocher** [comment]
@totoadel our intention is to make YOLOv5 run on any hardware in the world. The choice of edge hardware is determined by your own budget, domain, constraints and requirements, etc
