### ISSUE TITLE
AttributeError: 'Conv2d' object has no attribute 'accumulate_params'

### ISSUE THREAD

**Issue by USWUW** [ultralytics/yolov5#6836]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

# strip optimizers  have wrong    AttributeError: 'Conv2d' object has no attribute  #'accumulate_params'

### Additional

AttributeError: 'Conv2d' object has no attribute 'accumulate_params'

**Comment by USWUW** [comment]
> wave Hello @USWUW, thank you for your interest in YOLOv5 rocket! Please visit our star [Tutorials](https://docs.ultralytics.com/yolov5) to get started, where you can find quickstart guides for simple tasks like [Custom Data Training](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data) all the way to advanced concepts like [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution).
> 
> If this is a bug Bug Report, please provide screenshots and **minimum viable code to reproduce your issue**, otherwise we can not help you.
> 
> If this is a custom training question Question, please provide as much information as possible, including dataset images, training logs, screenshots, and a public link to online [W&B logging](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data#visualize) if available.
> 
> For business inquiries or professional support requests please visit https://ultralytics.com or email [support@ultralytics.com](mailto:support@ultralytics.com).
> ## Requirements
> 
> [**Python>=3.7.0**](https://www.python.org/) with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) installed including [**PyTorch>=1.7**](https://pytorch.org/get-started/locally/). To get started:
> 
> ```shell
> git clone https://github.com/ultralytics/yolov5  # clone
> cd yolov5
> pip install -r requirements.txt  # install
> ```
> 
> ## Environments
> 
> YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):
> 
>     * **Google Colab and Kaggle** notebooks with free GPU: [![Open In Colab](https://camo.githubusercontent.com/84f0493939e0c4de4e6dbe113251b4bfb5353e57134ffd9fcab6b8714514d4d1/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb) [![Open In Kaggle](https://camo.githubusercontent.com/a08ca511178e691ace596a95d334f73cf4ce06e83a5c4a5169b8bb68cac27bef/68747470733a2f2f6b6167676c652e636f6d2f7374617469632f696d616765732f6f70656e2d696e2d6b6167676c652e737667)](https://www.kaggle.com/models/ultralytics/yolov5)
> 
>     * **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
> 
>     * **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
> 
>     * **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) [![Docker Pulls](https://camo.githubusercontent.com/280faedaf431e4c0c24fdb30ec00a66d627404e5c4c498210d3f014dd58c2c7e/68747470733a2f2f696d672e736869656c64732e696f2f646f636b65722f70756c6c732f756c7472616c79746963732f796f6c6f76353f6c6f676f3d646f636b6572)](https://hub.docker.com/r/ultralytics/yolov5)
> 
> 
> ## Status
> 
> [![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)](https://github.com/ultralytics/yolov5/actions)
> 
> If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), validation ([val.py](https://github.com/ultralytics/yolov5/blob/master/val.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/export.py)) on MacOS, Windows, and Ubuntu every 24 hours and on every commit.

Traceback (most recent call last):
  File "/home/wu/yolov5_pruning-master/train.py", line 774, in <module>
    main(opt)
  File "/home/wu/yolov5_pruning-master/train.py", line 672, in main
    train(opt.hyp, opt, device)
  File "/home/wu/yolov5_pruning-master/train.py", line 568, in train
    strip_optimizer(f)  # strip optimizers
  File "/home/wu/yolov5_pruning-master/utils/general.py", line 569, in strip_optimizer
    x = torch.load(f, map_location=torch.device('cpu'))
  File "/home/wu/anaconda3/envs/py3.9/lib/python3.9/site-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/wu/anaconda3/envs/py3.9/lib/python3.9/site-packages/torch/serialization.py", line 882, in _load
    result = unpickler.load()
  File "/home/wu/anaconda3/envs/py3.9/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Conv2d' object has no attribute 'accumulate_params'

**Comment by USWUW** [comment]
this is my wrong

**Comment by USWUW** [comment]
The optimizer cannot remove the code, and there is an error in the code when removing

**Comment by daothanh2011** [comment]
Hello, I have  the same problem. Did you find the way to solve it?
thank you

**Comment by puyiwen** [comment]
> Hello, I have the same problem. Did you find the way to solve it?
> thank you

Hi, I also have the same problem.Do you solved it? Thank you very much!

**Comment by glenn-jocher** [comment]
@puyiwen hello, I appreciate your interest in YOLOv5 and apologize for the trouble you're experiencing. We're constantly working to improve YOLOv5, and I'll do my best to help you resolve this issue efficiently. Thank you for your patience and understanding.
