### ISSUE TITLE
onnx interence speed

### ISSUE THREAD

**Issue by never-to-never** [ultralytics/yolov5#6837]
Why is the inference speed much slower after converting to an onnx model?
![Screenshot from 2022-03-02 17-03-09](https://user-images.githubusercontent.com/27321035/156526002-bc0912cc-9b23-4f49-aa8a-bbcc467f8054.png)

**Comment by ShubhamNagarkar** [comment]
Faced a similar issue. After using --dynamic, I got better speed as compared to .pt model.

**Comment by data-ant** [comment]
> 
@ShubhamNagarkar hi,I'm sorry.when i export onnx when fix with --dynamic, it failed.
ONNX: export failure: Input, output and indices must be on the current device
how can u get the dynamic - onnx model

**Comment by yangwenwu92** [comment]
@data-ant Hi, guys.  have u fixed the problem?  can u share the solution for me. very very thanks!!!

**Comment by data-ant** [comment]
我已收到，谢谢。
                      祝您诸事顺利!

**Comment by glenn-jocher** [comment]
@data-ant hi there! We are constantly working on improving inference speeds, and your feedback is valuable in helping us optimize the model. The `--dynamic` flag does indeed offer better speed compared to the .pt model for certain setups, although it may not work in all cases.

In regards to your specific error message about input, output, and indices needing to be on the current device, it appears that the error is related to the device placement of tensors. If you are encountering this issue when exporting to ONNX, I recommend checking the device placement of tensors in your code and ensuring that they are on the same device. This should help resolve the problem.

Your patience and understanding are greatly appreciated! If you have any further questions or need additional assistance, we're here to help. Wishing you all the best!

**Comment by data-ant** [comment]
我已收到，谢谢。
                      祝您诸事顺利!

**Comment by glenn-jocher** [comment]
@data-ant 不客气，如果您有任何其他问题，请随时向我寻求帮助。祝您一切顺利！
