### ISSUE TITLE
scaling augmentation shall have min and max scale 

### ISSUE THREAD

**Issue by ShaharSarShalom** [ultralytics/yolov5#6839]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

I'm training a small objects dataset, The current implementation support multi scale and scaling augmentation however since my objects are small I'd like to scale down by up to 90% and scale up by 150% 

current implementation doesn't support such option  I had to change the code by myself 

### Use case

used for small objects dataset 

### Additional

I may be able to  submit a PR

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ShaharSarShalom yes as you mentioned we only support symmetrics scaling for simplicity and meanpoint-maintenance. If you implement non-symmetric scaling augmentation then your average object size will no longer be at scale 1 but at some other scale value (<1 in your case). I doubt this is preferable but I could be wrong.

You can customize the scale augmentation implementation here:
https://github.com/ultralytics/yolov5/blob/63ddb6f0d06f6309aa42bababd08c859197a27af/utils/augmentations.py#L142-L149

**Comment by ShaharSarShalom** [comment]
Thank you 

:+1:
