### ISSUE TITLE
Precision goes up but recall goes down

### ISSUE THREAD

**Issue by kaito-albert** [ultralytics/yolov5#684]
## ❔Question
Precision goes up but recall goes down. Any idea why this happened?
       0/4     10.6G   0.05558  0.002995   0.02315   0.08173         1      1152    **0.5574**    **0.3096**     0.425    0.2182   0.01862  0.002803  0.006562
       1/4       14G   0.05298  0.002417   0.01849   0.07389         0      1152    **0.5872**    **0.1902**     0.429    0.2189   0.01965  0.002829  0.006542
       2/4       14G   0.05086  0.002339   0.01735   0.07055         0      1152    **0.6547**   **0.07787**    0.4101    0.2047   0.02124  0.003137  0.006829

**Comment by glenn-jocher** [comment]
@kaito-albert there is absolutely no point in running 3 epochs and pondering your results.

**Comment by glenn-jocher** [comment]
I would recommend you train with all default settings, i.e. to 300 epochs, and then examine your results.png plots rather than trying to decrypt the the text results.

**Comment by kaito-albert** [comment]
Thanks. I will try the smallest model for 300 epochs.
