### ISSUE TITLE
Undertand the model

### ISSUE THREAD

**Issue by aiTrainee** [ultralytics/yolov5#6841]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,
I converted my trained tiny_yolo_v3.pt into onnx file. And I'm trying to understand the model.
![tiny_yolov3_onnx](https://user-images.githubusercontent.com/97884256/156536900-09a94f47-6486-44a5-84bd-9a93403ecb41.png)

I have a problem understand the constantOfShape part. Can you please explain it's source and impact on the model.
Thanks!

**Comment by glenn-jocher** [comment]
@aiTrainee this is just an ONNX module terminology for a constant. You should probably start with the YOLOv3 paper by Redmon:
https://arxiv.org/abs/1804.02767

**Comment by aiTrainee** [comment]
Thanks for your quick response. I have already looked at YOLOv3 paper and I understand the architecture quite good.
But this part (the constant):
![tiny_yolov3_onnx2](https://user-images.githubusercontent.com/97884256/156543445-28710f3d-f112-47e6-b146-67331a1d9f3c.png)
Isn't included in the original architecture of a tiny yolo v3. I'm not used to onnx. So merging this constant to the model doesn't impact it?

**Comment by glenn-jocher** [comment]
@aiTrainee oh, yes our YOLOv3-tiny architecture should be exactly identical to the original YOLOve paper. 

As I said ONNX and other providers create their own translations from the PyTorch modules we create, but the end result is mathematically identical. We have benchmarking scripts that compare speed and mAP of all exported models against their PyTorch originals and you can observe identical mAP to numerical precision, i.e.: PR https://github.com/ultralytics/yolov5/pull/6613

### Colab++ V100 High-RAM CPU Results
```
benchmarks: weights=/content/yolov5/yolov5s.pt, imgsz=640, batch_size=1, data=/content/yolov5/data/coco128.yaml
Checking setup...
YOLOv5 🚀 v6.0-282-g8310a17 torch 1.10.0+cu111 CPU
Setup complete ✅ (8 CPUs, 51.0 GB RAM, 44.7/166.8 GB disk)

Benchmarks complete (637.94s)
                   Format  mAP@0.5:0.95  Inference time (ms)
0                 PyTorch      0.402908           111.652056
1             TorchScript      0.402908           142.402692
2                    ONNX      0.402908            64.537143
3                OpenVINO      0.402908            69.528472
4                TensorRT           NaN                  NaN
5                  CoreML           NaN                  NaN
6   TensorFlow SavedModel      0.402908           150.990861
7     TensorFlow GraphDef      0.402908           123.970838
8         TensorFlow Lite      0.402851           229.984051
9     TensorFlow Edge TPU           NaN                  NaN
10          TensorFlow.js           NaN                  NaN
```
