### ISSUE TITLE
Question about recall caculate

### ISSUE THREAD

**Issue by root12321** [ultralytics/yolov5#6842]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

i have a question ,when i use  trained model  to calculate  the rec/pre score, the recall is 0.861 :
![image](https://user-images.githubusercontent.com/28287748/156540087-093dc576-98ca-4339-83c7-633771e6e7c2.png)
but when i add Additional data(no labels) to my test dataset, the recall is 0.655
![image](https://user-images.githubusercontent.com/28287748/156540446-6326e8ae-a3b0-40c9-9848-8f186e854532.png)

The two groups of data have same labels ,and same trained model to test,but recall score is not same .why ? please help me,thank you 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@root12321 P and R are computed over 1000 confidence thresholds and presented in the console at the maximum F1 confidence threshold. The introduction of additional data will naturally vary the best F1 confidence threshold. See metrics.py for implementation and to access underlying results:
https://github.com/ultralytics/yolov5/blob/63ddb6f0d06f6309aa42bababd08c859197a27af/utils/metrics.py#L72-L87
