### ISSUE TITLE
How to sample backgound images each batch, to guarantee that in each mosaic，there must contain at least one positive img when we have many background images.

### ISSUE THREAD

**Issue by Edwardmark** [ultralytics/yolov5#6843]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to sample backgound images each batch, to guarantee that in each mosaic，there must contain at least one positive img when we have many background images.

For eaxmples, we have 90% backgound images, but only 10% positive images with bounding box, can we sample some background images each epoch , so that in each epoch, different background samples are trained to decrease FP.

Thanks.

**Comment by glenn-jocher** [comment]
@Edwardmark training images are shuffled randomly inside a mosaic and inside a batch by default. All images are guaranteed to be used each epoch. You can customize the dataloader implementation here to meet your custom requirements:
https://github.com/ultralytics/yolov5/blob/63ddb6f0d06f6309aa42bababd08c859197a27af/utils/datasets.py#L378-L381

**Comment by Edwardmark** [comment]
@glenn-jocher Thanks, I will have a try.
