### ISSUE TITLE
Use Yolov5 to predict using only numpy

### ISSUE THREAD

**Issue by carlosedubarreto** [ultralytics/yolov5#6848]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I wanted to create some tools for Blender (the 3d software), so I dont have much option of python packages to use.
Could someone point me on the right direction so I could study how to be able to use yolov5 to predict images using basically only numpy?

thanks a lot.

**Comment by glenn-jocher** [comment]
@carlosedubarreto 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, etc.
# model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')  # custom trained model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by carlosedubarreto** [comment]
Thanks a lot for the response @glenn-jocher , btw, you are doing an amazing job ....

I saw about the yolov5 hub.
The problem is that I'm trying to do some implementation using only numpy, because I cant use pytorch, tensorflow or even opencv. (im also looking on some alternative to get the image converted in numpy array using other methods)

I'm trying to do it all inside the python that blender has (I know I can add pytorch in blender, for example, and I already did that, and it works great, but that was just a test to see how it would work, now I have to go without those tools)

I know it will be extremely difficult to do what I want to do, but I already started it months ago, and I guess I'll take years to finish it.

What I was expecting was not the answer to apply, but direction where to learn more about the yolov5 implementation.
I already took Andrews NG course some years ago (The machine learning using Octave) and few months ago I did the deep learning specialization course on coursera using python.)

Now I would like to dive deeper to be able to do all the passes needed to implement a CNN (RCNN or something similar) using just numpy.

I already now I will suffer a lot to do that 😊.


Can you point me ins some direction? Thank you a lot.

**Comment by glenn-jocher** [comment]
@carlosedubarreto it's possible of course, but you'd have to write your own inference architecture, which is extremely time consuming.

If you'd like to run YOLOv5 with the fewest dependencies possible I would recommend one of our export formats like ONNX etc. You'd have to implement the pre and post processing yourself (i.e. in numpy), but the actual inference no longer needs PyTorch. Additional benefits of this are that many formats are heavily optimized for speed, i.e. ONNX and OpenVINO are much faster on CPU than PyTorch.

See https://github.com/ultralytics/yolov5/pull/6613 for details:

Format                      | `export.py --include`         | Model
---                         | ---                           | ---
PyTorch                     | -                             | yolov5s.pt
TorchScript                 | `torchscript`                 | yolov5s.torchscript
ONNX                        | `onnx`                        | yolov5s.onnx
OpenVINO                    | `openvino`                    | yolov5s_openvino_model/
TensorRT                    | `engine`                      | yolov5s.engine
CoreML                      | `coreml`                      | yolov5s.mlmodel
TensorFlow SavedModel       | `saved_model`                 | yolov5s_saved_model/
TensorFlow GraphDef         | `pb`                          | yolov5s.pb
TensorFlow Lite             | `tflite`                      | yolov5s.tflite
TensorFlow Edge TPU         | `edgetpu`                     | yolov5s_edgetpu.tflite
TensorFlow.js               | `tfjs`                        | yolov5s_web_model/

```
"""
Requirements:
    $ pip install -r requirements.txt coremltools onnx onnx-simplifier onnxruntime openvino-dev tensorflow-cpu  # CPU
    $ pip install -r requirements.txt coremltools onnx onnx-simplifier onnxruntime-gpu openvino-dev tensorflow  # GPU

Usage:
    $ python utils/benchmarks.py --weights yolov5s.pt --img 640
"""
```

### Colab++ V100 High-RAM CPU Results
```
benchmarks: weights=/content/yolov5/yolov5s.pt, imgsz=640, batch_size=1, data=/content/yolov5/data/coco128.yaml
Checking setup...
YOLOv5 🚀 v6.0-282-g8310a17 torch 1.10.0+cu111 CPU
Setup complete ✅ (8 CPUs, 51.0 GB RAM, 44.7/166.8 GB disk)

Benchmarks complete (637.94s)
                   Format  mAP@0.5:0.95  Inference time (ms)
0                 PyTorch      0.402908           111.652056
1             TorchScript      0.402908           142.402692
2                    ONNX      0.402908            64.537143
3                OpenVINO      0.402908            69.528472
4                TensorRT           NaN                  NaN
5                  CoreML           NaN                  NaN
6   TensorFlow SavedModel      0.402908           150.990861
7     TensorFlow GraphDef      0.402908           123.970838
8         TensorFlow Lite      0.402851           229.984051
9     TensorFlow Edge TPU           NaN                  NaN
10          TensorFlow.js           NaN                  NaN
```

**Comment by carlosedubarreto** [comment]
Thanks a lot for the infor. I'm going to give it some study 🥳
