### ISSUE TITLE
Running train.py causes error because there's no hyp.scratch.yaml on  yolov5/data/hyps

### ISSUE THREAD

**Issue by edehino** [ultralytics/yolov5#6849]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

Here's the error:
```
Traceback (most recent call last):
  File "train.py", line 648, in <module>
    main(opt)
  File "train.py", line 525, in main
    check_file(opt.data), check_yaml(opt.cfg), check_yaml(opt.hyp), str(opt.weights), str(opt.project)  # checks
  File "/home/pinky/architectures/yolov5/utils/general.py", line 359, in check_yaml
    return check_file(file, suffix)
  File "/home/pinky/architectures/yolov5/utils/general.py", line 382, in check_file
    assert len(files), f'File not found: {file}'  # assert file was found
AssertionError: File not found: data/hyps/hyp.scratch.yaml
```

I looked into yolov5/data/hyps but hyp.scratch.yaml does not exist.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@edehino your code is out of date, as hyp.scratch.yaml has been renamed to hyp.scratch-low.yaml To update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>
