### ISSUE TITLE
Changing YOLOv5 labels to another language

### ISSUE THREAD

**Issue by HunarAA** [ultralytics/yolov5#6851]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm wondering if it's possible to change the labels on Yolov5 to another language. For example, Arabic. I have tried changing them in the '.yaml' file, but when I test the trained model, all the characters become weird symbols.

**Comment by glenn-jocher** [comment]
@HunarAA we've tried to implement support for Chinese characters using Arial Unicode, but have not tested arabic characters. Can you upload your yaml here or paste your `names` array so we can test? Thanks!

**Comment by HunarAA** [comment]
Of course I will. But the language that I want to try is not Arabic exactly, it's Persian and Arabic like language. This is the array of names: ["ڕوبەڕوو", "چۆنی", "لەبەردەم", "خۆشەویستی"]. I appreciate your help.

**Comment by glenn-jocher** [comment]
@HunarAA got it, thanks for the sample! I'll try it out.

**Comment by HunarAA** [comment]
Please find me a way to do it. Thank you.

**Comment by glenn-jocher** [comment]
@HunarAA what's your problem exactly? Your names operate correctly in my tests:

```yaml
# Classes
nc: 80  # number of classes
names: ["ڕوبەڕوو", "چۆنی", "لەبەردەم", "خۆشەویستی", 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light',
        'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow',
        'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee',
        'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard',
        'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple',
        'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch',
        'potted plant', 'bed', 'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone',
        'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear',
        'hair drier', 'toothbrush']  # class names
```

![confusion_matrix](https://user-images.githubusercontent.com/26833433/156777680-11b3b8e6-6c20-43ae-9578-555934a312bd.png)

![val_batch0_labels](https://user-images.githubusercontent.com/26833433/156777666-4e96d1f6-2c7f-4b6c-8cf0-fa5c37f703ee.jpg)

**Comment by HunarAA** [comment]
On my test, the letters become unrecognizable characters but in your tests it's better than mine. Hence, there is a problem with your test which is the whole is split into litters for example "چۆنی" is showed like "چ ۆ ن ی" each as s separate characters not a word. Do you think this can be solved? 
And how did you done that? because on my tests the laptop webcam showed unrecognizable characters as I said.

**Comment by glenn-jocher** [comment]
@HunarAA I just updated the coco128.yaml names array in a new Colab notebook and trained normally to get the above results, i.e. no additional action is required on your part to get the above results.
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb?hl=en

I don't know about the spacing though, not sure if there's any solution to that. This is just PIL printing text using the YOLOv5 Annotator class:
https://github.com/ultralytics/yolov5/blob/8a66ebad44e8ecf90c7d27757c832579398d4baf/utils/plots.py#L65-L81

**Comment by HunarAA** [comment]
Thank you for your answer. I will try it again and see

**Comment by glenn-jocher** [comment]
@HunarAA then just do a grid search basically, i.e. take the default and if you have an 8 GPU machine run 8 cases: default times 1/8, 1/4, 1/2, 1, 2, 4, 8 etc.

**Comment by ghaithAlMasri** [comment]
@HunarAA Hello, did you figure out a way to solve the separate letters?

**Comment by HunarAA** [comment]
As I understood, there is no way to solve this problem because they use OpenCV **puttext** method to add the text to the bounding boxes and OpenCV only supports English languages.

**Comment by glenn-jocher** [comment]
@Crypro-Coder @HunarAA YOLOv5 will automatically switch to PIL plotting for non-latin typographies, so we support labels in all alphabets, i.e. Chinese, Arabic, Cyrillic etc.
https://github.com/ultralytics/yolov5/blob/526e650553819dbff67897b9c752c4072e989823/utils/plots.py#L72-L80

**Comment by HunarAA** [comment]
Is it new addition? because when I asked the question there wasn't such thing.

**Comment by glenn-jocher** [comment]
@HunarAA we've had this for a while but made some major improvements a few months ago. Haven't seen any alphabet-related issues raised since then. I think the confusion matrix plots may still not work correctly, but this a matplotlib issue, the image annotations that are done with PIL should be correct.

**Comment by HunarAA** [comment]
Thanks, since then I didn't try it. I will try it again.

**Comment by glenn-jocher** [comment]
You're welcome, @HunarAA! Feel free to give it another shot, and let us know if you encounter any issues. Happy to help if you need further assistance.
