### ISSUE TITLE
How to get the result.csv file when running the val.py?

### ISSUE THREAD

**Issue by ZwNSW** [ultralytics/yolov5#6853]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When running train.py, you can get result.csv file, but there is no result.csv when running the val.py. How do we get the result.csv when running the val.py?

**Comment by ZwNSW** [comment]
@glenn-jocher 
When running train.py, you can get result.csv file, but there is no result.csv when running the val.py. How do we get the result.csv when running the val.py?

**Comment by glenn-jocher** [comment]
@ZwNSW sorry, results.csv is only generated when training.

**Comment by ZwNSW** [comment]
> 

@glenn-jocher Thank your reply.
 How to export PR data when running val.py file?

**Comment by glenn-jocher** [comment]
@ZwNSW you can to insert some code here in the PR plot function to save the data:
https://github.com/ultralytics/yolov5/blob/601dbb83f01b58355211f2565cfa4eecb48b1220/utils/metrics.py#L76-L77
