### ISSUE TITLE
Including YoloV5 in Flutter app

### ISSUE THREAD

**Issue by shaharhn** [ultralytics/yolov5#686]
Hey guys,
I can't understand how do i implement yolov5 to my flutter app, i understand that i need to convert this project to tflite model, which i didn't success to do, any help ?

**Comment by glenn-jocher** [comment]
@shaharhn the export pipeline would be pytorch > onnx > tflite. 

See the export tutorial in https://docs.ultralytics.com/yolov5, which covers the basic steps of pytorch > onnx. Onward to tflite you would have to do on your own.

Do you have a flutter reference app available for object detection?

**Comment by shaharhn** [comment]
Didn't succeeds to do it, if anyone can help it will be much appricated!

**Comment by glenn-jocher** [comment]
@shaharhn see https://github.com/ultralytics/yolov5/pull/1127 for TFLite export.

**Comment by AneeqMalik** [comment]
@shaharhn You can refer to this https://pub.dev/packages/flutter_pytorch package by this you no need to convert your models to tflite you can use it as pytorch model.
You can further refer to this repo: https://github.com/AneeqMalik/flutter_pytorch

**Comment by yassine-kassis** [comment]
> @shaharhn You can refer to this https://pub.dev/packages/flutter_pytorch package by this you no need to convert your models to tflite you can use it as pytorch model. You can further refer to this repo: https://github.com/AneeqMalik/flutter_pytorch

a great package but available only for android
