### ISSUE TITLE
detect.py error handling for corrupt frames in a video file?

### ISSUE THREAD

**Issue by apiszcz** [ultralytics/yolov5#6860]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

The current behavior handling a corrupt from is to stacktrace on a bad frame, when processing multiple video files a directory detect.py omits processing the remaining frames and remaining files.

Testing the following:

detect.py:135
        
```
        try:
            PILimg = Image.fromarray(img)
            PILimg.verify()
        except (IOError, SyntaxError) as e:
            print('Corrupt file',path)
            continue
        t1 = time_sync()
```

### Use case

Processing any video file with 1 or more corrupt frames.

### Additional

Testing.

? https://github.com/ultralytics/yolov5/issues/5791

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@apiszcz yes catching errors might be a good idea as you said. I think this might have to be done at the dataloader level though. LoadStreams does something similar already, where if a frame fails to load a black image is used in its place on L340:
https://github.com/ultralytics/yolov5/blob/8a66ebad44e8ecf90c7d27757c832579398d4baf/utils/datasets.py#L328-L344

But the image/video loader does not have any robust error handling:
https://github.com/ultralytics/yolov5/blob/8a66ebad44e8ecf90c7d27757c832579398d4baf/utils/datasets.py#L199-L215

Can you please submit a PR with your proposed fix? Thanks!

**Comment by apiszcz** [comment]
PR , once I'm sure I can try, I followed the PR steps last time but did something wrong. Change above is working well.  Loader level fix would be good, however detect.py will be loader agnostic.  Does StopIteration in your example allow the remaining frames to be processed, (continue not required?).
