### ISSUE TITLE
About the meaning of VERBOSE in general.py

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#6862]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

@glenn-jocher 
What role does this `VERBOSE` play in the set_logging function?
https://github.com/ultralytics/yolov5/blob/8a66ebad44e8ecf90c7d27757c832579398d4baf/utils/general.py#L40

https://github.com/ultralytics/yolov5/blob/8a66ebad44e8ecf90c7d27757c832579398d4baf/utils/general.py#L76-L83

**Comment by glenn-jocher** [comment]
@Zengyf-CVer if environment variable YOLOv5_VERBOSE=False then no YOLOv5 output will be printed to screen. Default is True. i.e.:
```bash
YOLOv5_VERBOSE=False python detect.py
```

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
Thank you very much.
