### ISSUE TITLE
Learn about build targets

### ISSUE THREAD

**Issue by WZMIAOMIAO** [ultralytics/yolov5#6863]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

First of all, thank you for your great works.

I read and learn the code:
https://github.com/ultralytics/yolov5/blob/8a66ebad44e8ecf90c7d27757c832579398d4baf/utils/loss.py#L169-L222

My guess is that offsets are introduced to get more positive samples. Then, I want to know whether I understand correctly. Here is the diagram I drew:

![image](https://user-images.githubusercontent.com/31005897/156876336-4628a646-b044-4c17-84c9-d16666e5e799.png)

If I don't understand correctly, I hope you can give me some tips. Thank you!

**Comment by glenn-jocher** [comment]
@WZMIAOMIAO yes this is correct!

**Comment by WZMIAOMIAO** [comment]
> @WZMIAOMIAO yes this is correct!

thank you for your reply.

**Comment by WZMIAOMIAO** [comment]
#6998

**Comment by myasser63** [comment]
@WZMIAOMIAO Can you explain this more in your summary?
