### ISSUE TITLE
Video Input skip frames option, detect.py

### ISSUE THREAD

**Issue by apiszcz** [ultralytics/yolov5#6868]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Interested in specifying a command line argument --vid-skip n, n=default=1, so that frames can be skipped from the input video.

Related: https://github.com/ultralytics/yolov5/issues/6433

### Use case

process every 5th video frame

detect.py --vid-skip 5

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@apiszcz hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
