### ISSUE TITLE
YOLOv5 6.0 Model Structure

### ISSUE THREAD

**Issue by WZMIAOMIAO** [ultralytics/yolov5#6885]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

First of all,  thank you for your great works.
I drew the structure of the model according to `yolov5l.yaml` (v6.0).  I'm not sure whether there are any mistakes. And I want to contribute this picture to the community and help other learners.

![yolov5](https://user-images.githubusercontent.com/31005897/157381276-6e8429f3-c759-4aef-aea8-034438919457.png)

**Comment by glenn-jocher** [comment]
@WZMIAOMIAO very nice! Looks all correct.

**Comment by WZMIAOMIAO** [comment]
update bottleneck, because `e=1.0`.
https://github.com/ultralytics/yolov5/blob/e6e36aac109794999f1dafab244b9ec4887a33d1/models/common.py#L127-L139

**Comment by WZMIAOMIAO** [comment]
@glenn-jocher Next week I want to write a technical summary(`markdown`) about YOLOV5(v6.0). Then put it in the YOLOV5 Docs to help people learn yolov5. I don't know if you're interested.  :smile:

**Comment by glenn-jocher** [comment]
@WZMIAOMIAO yes that would be great! v6.0 and v6.1 use the same (current) architecture, so the docs will also apply to the latest models.

**Comment by WZMIAOMIAO** [comment]
> @WZMIAOMIAO yes that would be great! v6.0 and v6.1 use the same (current) architecture, so the docs will also apply to the latest models.

 hi, I briefly summarized yolov5(v6.0). I hope you can take a look at it when you have time. #6998

**Comment by chelsea456** [comment]
> ### Search before asking
> 
> 
> 
> - [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.
> 
> 
> 
> 
> 
> ### Question
> 
> 
> 
> First of all,  thank you for your great works.
> 
> I drew the structure of the model according to `yolov5l.yaml` (v6.0).  I'm not sure whether there are any mistakes. And I want to contribute this picture to the community and help other learners.
> 
> 
> 
> ![yolov5](https://user-images.githubusercontent.com/31005897/157381276-6e8429f3-c759-4aef-aea8-034438919457.png)
> 
> 
> 
> ### Additional
> 
> 
> 
> _No response_

Hi you, what program you use draw this picture. Tks you

**Comment by scraus** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.
> 
> ### Question
> First of all, thank you for your great works. I drew the structure of the model according to `yolov5l.yaml` (v6.0). I'm not sure whether there are any mistakes. And I want to contribute this picture to the community and help other learners.
> 
> ![yolov5](https://user-images.githubusercontent.com/31005897/157381276-6e8429f3-c759-4aef-aea8-034438919457.png)
> 
> ### Additional
> _No response_

Hello @WZMIAOMIAO! What do P1, P2, P3, and so on mean? And what does C3 mean? Thank you for your help! 🙏🙇‍♀️
