### ISSUE TITLE
YOLOv5n6 when exported to ONNX from PyTorch increases model size

### ISSUE THREAD

**Issue by ShubhamNagarkar** [ultralytics/yolov5#6890]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

A custom trained pytorch YOLOv5n6 model has a size of 6.3MB. But when I used the python export.py using the best.pt, the exported onnx model's size is 13.1MB. Is there specific reason for it? Also, if --dynamic flag is not used, the inference speed goes to 224ms as against pytorch model's inference speed which is 28ms. I appreciate any help or suggestion to tackle this issue. Thank you.

**Comment by glenn-jocher** [comment]
@ShubhamNagarkar PyTorch models are saved in FP16, ONNX exports by default are FP32. See export.py argparser for export options.
