### ISSUE TITLE
Inference speed

### ISSUE THREAD

**Issue by marsyaaaaal** [ultralytics/yolov5#6892]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

If I trained a yolov5s model at only 1 class, will the inference speed improve compared to a pretrained yolov5s at 80 classes? Or will it stay the same?

**Comment by DavidBaldsiefen** [comment]
I have done the same recently, and inference speed increased significantly for me on YOLOv5m:

![image](https://user-images.githubusercontent.com/4655486/157159311-1a792231-2b01-447a-95a3-51a9757068b7.png)


However, the biggest gain came from the reduced postprocessing time.

**Comment by marsyaaaaal** [comment]
> I have done the same recently, and inference speed increased significantly for me on YOLOv5m:
> 
> ![image](https://user-images.githubusercontent.com/4655486/157159311-1a792231-2b01-447a-95a3-51a9757068b7.png)
> 
> 
> However, the biggest gain came from the reduced postprocessing time.

Okayy, thank you!

**Comment by HeChengHui** [comment]
> I have done the same recently, and inference speed increased significantly for me on YOLOv5m:
> 
> ![image](https://user-images.githubusercontent.com/4655486/157159311-1a792231-2b01-447a-95a3-51a9757068b7.png)
> 
> However, the biggest gain came from the reduced postprocessing time.

Hello, is there a link to this paper or resource?

**Comment by DavidBaldsiefen** [comment]
> > I have done the same recently, and inference speed increased significantly for me on YOLOv5m:
> > ![image](https://user-images.githubusercontent.com/4655486/157159311-1a792231-2b01-447a-95a3-51a9757068b7.png)
> > However, the biggest gain came from the reduced postprocessing time.
> 
> Hello, is there a link to this paper or resource?

It is part of my thesis. Please note that latency and throughput are related to a full pipeline I have coded, so actual timings may differ; The trend for preprocessing, inference and postprocessing should be true in most cases though. If you are interested I could upload it somewhere

**Comment by HeChengHui** [comment]
@DavidBaldsiefen 
Is it possible to advise on how you got the latency and other timings?

**Comment by DavidBaldsiefen** [comment]
> @DavidBaldsiefen 
> Is it possible to advise on how you got the latency and other timings? 

Yes. I was using two threads, one that "captures" new frames from a video source at a rate of 50fps, and one that receives those frames and processes them (using TensorRT YOLOv5) as fast as it can. When the second thread cannot keep up with the publishing rate, frames start being dropped and average latency starts increasing. Therefore, latency is **not** to be confused with the total inference time! However, the average pre- post and inference timings are also listed in the table, and probably valid independent from the used pipeline.

Everything is implemented in C++ and can be found [here](https://github.com/DavidBaldsiefen/rocket_tracker). However, I suppose that this overall system does not apply to your usecase. I will also upload the thesis soon and can link it here if you are still interested
