### ISSUE TITLE
torch.nn.modules.module.ModuleAttributeError: 'Detect' object has no attribute 'm'

### ISSUE THREAD

**Issue by 2684160504** [ultralytics/yolov5#690]
## ❔Question
pytorch中运行detect和test都出现这个问题，但train正常．请问该如何解决？谢谢

**Comment by 2684160504** [comment]
![Screenshot from 2020-08-10 17-04-02](https://user-images.githubusercontent.com/44891815/89767074-c7c6e980-db2b-11ea-9eae-7224c0fbd485.png)

**Comment by colindecourt** [comment]
Hi, 
You should try to update your code to the latest version of the repository.  Moreover I recommend you to use latest yolo's weights. I fixed this issue like this.

**Comment by 2684160504** [comment]
> Hi,
> You should try to update your code to the latest version of the repository. Moreover I recommend you to use latest yolo's weights. I fixed this issue like this.

Thank you for your help.I fixed this issue like this,too.

**Comment by orayel** [comment]
朋友  请问最后你是怎么解决这个问题的  我也遇到了同样问题  用的最新代码还是不行  麻烦了！

**Comment by 2684160504** [comment]
> 朋友 请问最后你是怎么解决这个问题的 我也遇到了同样问题 用的最新代码还是不行 麻烦了！

I recommend you to use latest yolo's weights.

**Comment by orayel** [comment]
use yolov5x.pt ?  i have try ,but it  doesn't  work!

**Comment by 2684160504** [comment]
> use yolov5x.pt ? i have try ,but it doesn't work!

No.It,s latest yolo's weights  that author has published.

**Comment by orayel** [comment]
> > use yolov5x.pt ? i have try ,but it doesn't work!
> 
> No.It,s latest yolo's weights that author has published.

Do you mean : downloading new weights ?

**Comment by colindecourt** [comment]
Take a look here: https://github.com/ultralytics/yolov5/releases/tag/v2.0 and download the weights you need.

**Comment by orayel** [comment]
> Take a look here: https://github.com/ultralytics/yolov5/releases/tag/v2.0 and download the weights you need.

i get it  !   thank you !

**Comment by orayel** [comment]
> > > use yolov5x.pt ? i have try ,but it doesn't work!
> > 
> > 
> > No.It,s latest yolo's weights that author has published.
> 
> Do you mean : downloading new weights ?

OK  i get it  ! thanks!
