### ISSUE TITLE
Is it possible to have an HD input? 

### ISSUE THREAD

**Issue by civiliangame** [ultralytics/yolov5#6901]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,
I'm trying to modify the YOLO v5 network to accept HD images as inputs. The image downsampling takes away too much of the important small features that I am attempting to detect. 

Do you have any suggestions as to how I would go about this? Would I have to go in and change the entire architecture for every layer? Or, would I just divide up the image into smaller tiles? 

Thank you!

**Comment by glenn-jocher** [comment]
@civiliangame any YOLOv5 model can run at any image size, i.e.:

```
python detect.py --weights yolov5s6.pt --img 1920
```

**Comment by civiliangame** [comment]
@glenn-jocher 
Doesn't this automatically resize the input image to something smaller before actually giving it to the model? 
I'm trying to eliminate the resizing step altogether because the small features (hairline cracks etc.) suffer heavy information loss during it. 

Thanks!

**Comment by glenn-jocher** [comment]
@civiliangame images will only be resized if you pass a different --imgsz than the image long side. i.e. if your images are 1920x1080 then `python detect.py --img 1920` will not resize your image.
