### ISSUE TITLE
Numpy is not available

### ISSUE THREAD

**Issue by astroxyx** [ultralytics/yolov5#6908]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to use yolov5 on raspberry 4B.I installed it by 
`pip install -r requirements.txt  # install`.
But when I run train.py
![c07deb1d1b9bca60a91f87e5cec4753](https://user-images.githubusercontent.com/43833930/157392275-110bba77-fde5-442c-ad38-400e1fa11161.png)
and my numpy has installed
![94fcb8b817db9ce6f544f8bdc269721](https://user-images.githubusercontent.com/43833930/157392332-7cfaecb7-c6a6-4fb8-8758-3a825d2fe26d.png)
.
can you help me?

**Comment by glenn-jocher** [comment]
@astroxyx you may need to install PyTorch CPU specifically, see https://pytorch.org/get-started/locally/

**Comment by astroxyx** [comment]
> 

thanks,I check my Pytorch ,it seems no problem.The cause of this problem seems to be numpy?

**Comment by glenn-jocher** [comment]
@astroxyx yes, seems like a numpy dependency issue. Unfortunately I don't have any raspberry Pi's currently to test though, so I can't reproduce myself.

**Comment by astroxyx** [comment]
thanks,I run 
`pip3 install -U numpy`
and it works!
