### ISSUE TITLE
Serious BUG while Training with Multi-GPU on Windows

### ISSUE THREAD

**Issue by JasonFeng02** [ultralytics/yolov5#6909]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training, Multi-GPU

### Bug

Based on Windows10 system. Python = 3.8
while i'm training coco dataset with Multi-GPU.At first it came out with error said need more memory to allow wandb
to process my data.Then my computer became slow,even cant move my mouse,then after a while with no operating.Computer reboot itself.

### Environment

- YOLO:YOLOv5-6.0 release
- OS: windows 10
- device: Multi-TITAN X(12g)
- pytorch:1.10.2 + cu113

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by JasonFeng02** [comment]
even when i turn down my batch-size to a normal ones,while wandb function started to work,my computer became slow either

**Comment by glenn-jocher** [comment]
@JasonFeng02 thanks for the bug report! We don't have a Multi-GPU Windows system unfortunately, but it would help if you tried to isolate the issue. 

For example if you uninstall wandb does the issue still appear?

**Comment by JasonFeng02** [comment]
> @JasonFeng02 thanks for the bug report! We don't have a Multi-GPU Windows system unfortunately, but it would help if you tried to isolate the issue.
> 
> For example if you uninstall wandb does the issue still appear?

actually at first i didn't install wandb,but tensorboard seen not as good as wandb's data processing.and more weired is while i only run training on one GPU, it's OK

**Comment by JasonFeng02** [comment]
unfortunately not,it became worse ,windows failed to link with other GPUs now,but I'm sure that other GPUs are not in trouble

**Comment by glenn-jocher** [comment]
@JasonFeng02 ok got it. Then it seems unrelated to wandb. 

In general windows Multi-GPU support is not very reliable and may have only been introduced recently. I would try to use Linux if possible. In any case, all Multi-GPU trainings should be done in Docker for best results. All of our official models are trained using our Docker image.

💡 ProTip! Try one of our verified environments below if you are having trouble with your local environment.


## Requirements

[**Python>=3.7.0**](https://www.python.org/) with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) installed including [**PyTorch>=1.7**](https://pytorch.org/get-started/locally/). To get started:
```bash
git clone https://github.com/ultralytics/yolov5  # clone
cd yolov5
pip install -r requirements.txt  # install
```

[Models](https://github.com/ultralytics/yolov5/tree/master/models) and [datasets](https://github.com/ultralytics/yolov5/tree/master/data) download automatically from the latest YOLOv5 [release](https://github.com/ultralytics/yolov5/releases) when first requested.

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), validation ([val.py](https://github.com/ultralytics/yolov5/blob/master/val.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/export.py)) on MacOS, Windows, and Ubuntu every 24 hours and on every commit.

**Comment by JasonFeng02** [comment]
thanks，i would try docker soon on my training computer
