### ISSUE TITLE
how to pass rtsp cameras ID in streams.txt to create urls

### ISSUE THREAD

**Issue by zyakubova86** [ultralytics/yolov5#6910]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, 
I am working on project that renders detected objects on web with multiple rtsp in streams.txt . I could render only 1st rtsp stream. How can I pass id of the rtsp to generate url? I am just stuck there... Where should I adjust the code? Please, help meee

Thanks

**Comment by glenn-jocher** [comment]
@zyakubova86 I don't understand your question. You can place multiple RTSP addresses within a streams.txt file, one per line, and then pass this as your source to run multi-stream inference:
```
python detect.py --source streams.txt
```

**Comment by zyakubova86** [comment]
I need to render multiple streams on browser on flask. There are multiple buttons on home page with the names of camera numbers. On click button camera1 it should open page with 1 st rtsp stream on streams.txt, on click camera2  -  the 2 nd and so on.  I know that in streams.txt index of the rtsp is 0 1 2 3... I could render only 1 rtsp stream on web page. But I don't know how to do it with multiple streams. Please, help me to solve this

**Comment by GianniGi** [comment]
> python detect.py --weights yolov5x.pt --view-img --class 0 1 2 3 4 5 6 7 8 9 --nosave --device 0 --source streams.txt

streams.txt content:
>'https://www.youtube.com/watch?v=7aSkJCUDAes'
>'https://www.youtube.com/watch?v=jhx76shvwDs'

output:

> Traceback (most recent call last):
>   File "D:\sbin\yolov5\detect.py", line 254, in <module>
>     main(opt)
>   File "D:\sbin\yolov5\detect.py", line 249, in main
>     run(**vars(opt))
>   File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
>     return func(*args, **kwargs)
>   File "D:\sbin\yolov5\detect.py", line 101, in run
>     dataset = LoadStreams(source, img_size=imgsz, stride=stride, auto=pt)
> 
>   File "D:\sbin\yolov5\utils\dataloaders.py", line 339, in __init__
>     assert cap.isOpened(), f'{st}Failed to open {s}'
> **AssertionError: 1/2: ï»¿'https://www.youtube.com/watch?v=7aSkJCUDAes'... Failed to open ï»¿'https://www.youtube.com/watch?v=7aSkJCUDAes'**

**Comment by glenn-jocher** [comment]
@GianniGi streaming sources are RTSP, RTMP, etc. A YouTube video is not a streaming source.

**Comment by GianniGi** [comment]
> @GianniGi streaming sources are RTSP, RTMP, etc. A YouTube video is not a streaming source.

thanks for clearing the confusion, since on their website they say that 
"Create a YouTube live stream with an encoder."

Anyway I can't find a list of free streaming sources for testing... anywhere :-)
