### ISSUE TITLE
Is there a way to stop training once a desired mAP is reached?

### ISSUE THREAD

**Issue by kjk-poe** [ultralytics/yolov5#6911]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi ultralytics team,

Is there a way for yolov5 to stop training once a certain mAP is reached(eg. 0.7)? I tried to read through the earlystopping function and change the best_fitness but it did not work.

![image](https://user-images.githubusercontent.com/85408790/157398714-0a753d05-ab98-49fb-a0b8-0b6c1f3072b3.png)

Thanks in advance!

**Comment by glenn-jocher** [comment]
@kjk-poe no, there is no metric threshold you can set. 

Instead you can set a number of epochs after which training will be cancelled if no improvement has been seen. i.e. to set this value to 30 epochs:

```
python train.py --patience 30
```

**Comment by glenn-jocher** [comment]
@kjk-poe of course you could also modify the early stopping function to your custom requirements, i.e. trigger a stop when fitness > 0.7

**Comment by kjk-poe** [comment]
I see. May I ask if fitness correspond to mAP@.5:.95 or mAP@.5 when training?

**Comment by glenn-jocher** [comment]
@kjk-poe fitness is a weighted combination of metrics, but is mostly represented by mAP@0.5:0.95:
https://github.com/ultralytics/yolov5/blob/e6e36aac109794999f1dafab244b9ec4887a33d1/utils/metrics.py#L15-L19

**Comment by kjk-poe** [comment]
That makes sense now. I tried modifying the EarlyStopping() to try and stop training at 0.75 mAP however it always stop around mAP of 0.73.

Thank you very much for the explanation!
![image](https://user-images.githubusercontent.com/85408790/157411293-2f2241d1-97e5-4550-aef6-0af9b7f240ec.png)
![image](https://user-images.githubusercontent.com/85408790/157411671-52980f19-ecfa-466e-9c23-b0228275c0bb.png)
