### ISSUE TITLE
: Cannot copy to a TensorFlowLite tensor (serving_default_input_1:0) with 1769472 bytes from a Java Buffer with 1732800 bytes.

### ISSUE THREAD

**Issue by VYRION-Ai** [ultralytics/yolov5#6912]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

I'm coding yolov5 tflite on android studio, the code is working fine on previous version on yolov5 (befor v6). Now when I use the new trend network and convert it to tflite I get this error
i export with this
`python export.py --weights best_n.pt --include tflite --img 380`
```
ava.lang.IllegalArgumentException: Cannot copy to a TensorFlowLite tensor (serving_default_input_1:0) with 1769472 bytes from a Java Buffer with 1732800 bytes.
        at org.tensorflow.lite.Tensor.throwIfSrcShapeIsIncompatible(Tensor.java:447)
        at org.tensorflow.lite.Tensor.setTo(Tensor.java:189)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:200)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:374)
        at com.android.animal_cam_alert.tflite.YoloV5Classifier.recognizeImage(YoloV5Classifier.java:392)
        at com.android.animal_cam_alert.DetectorActivity$2.run(DetectorActivity.java:254)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by VYRION-Ai** [comment]
sorry i got the errro 
when i export the tflite with img size 380 , it is acutly exported as 384 


i got the solution from this link 
https://discuss.tensorflow.org/t/custom-transfer-learning-tensorflowlite-model-gives-error-in-android-code-for-image-classification/1010/6

https://netron.app/

**Comment by glenn-jocher** [comment]
@totoadel TFLite export works correctly, I'm unable to reproduce any issues using your command:
<img width="1364" alt="Screenshot 2022-03-09 at 11 13 43" src="https://user-images.githubusercontent.com/26833433/157421121-2e58cd4a-fccb-4109-a429-d6601d6fa1e6.png">

**Comment by VYRION-Ai** [comment]
> @totoadel TFLite export works correctly, I'm unable to reproduce any issues using your command: <img alt="Screenshot 2022-03-09 at 11 13 43" width="1364" src="https://user-images.githubusercontent.com/26833433/157421121-2e58cd4a-fccb-4109-a429-d6601d6fa1e6.png">

I am sorry it works well, the problem was with the image size , in export command enter the img size as 380 but the exported size is 384,  i check it with from the site netron.app

**Comment by glenn-jocher** [comment]
@totoadel YOLOv5 input shapes must meet constraints of 32 pixel multiples for P5 models like YOLOv5s and 64 multiples for P6 models like YOLOv5s6.

**Comment by Siddharth1698** [comment]
> @totoadel YOLOv5 input shapes must meet constraints of 32 pixel multiples for P5 models like YOLOv5s and 64 multiples for P6 models like YOLOv5s6.

This actually solves the issue. When training the model, its best to train with image size which is divisible by 32 and 64. The app kept crashing but then I noticed the image size not divisible by 32 and 64. Retrained it and now it isn't crashing.
