### ISSUE TITLE
nvidia jetson xavier nx camera fps is kept to 5

### ISSUE THREAD

**Issue by Kabuc0** [ultralytics/yolov5#6915]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,

I am using yolov5 on a Nvidia Jetson Xavier NX. When I run detect.py it points out, that the camera fps is kept to 5 at a resolution of 1920x1080 `(1/1: 0... Success (inf frames 1920y1080 at 5.00 FPS)).` While running the code, it says that I should have around 20-30 fps, depends on what model I use. But the video output doesnt change at all and doenst really look like 20-30 fps. It looks more like the 5 fps. So I guess the camera fps is kept to 5. 
Do you know, how I can change that?

Thanks

**Comment by glenn-jocher** [comment]
@Kabuc0 streaming source properties are generally not modifiable as they are properties of the source, but you can try to customize in the dataloaders in datasets.py.
