### ISSUE TITLE
Multi GPU training WINDOWS

### ISSUE THREAD

**Issue by ignasiven** [ultralytics/yolov5#6917]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi!
Checking the multi-GPU tutorial (https://docs.ultralytics.com/tutorials/multi-gpu-training/) and other reports; I have not reached any conclusion on which is the best way to train models using multiple GPUs in a WINDOWS system. 

( $ python train.py  --batch-size 64 --data coco.yaml --weights yolov5s.pt --device 0,1 ) What would be an alternative to using this method stated in the tutorial as not recommended. I do not see a lot of improvement with running with only one GPU. The only significant change is that I am able to run bigger batches with more image definition.

I have been digging into torch.distributed with NCCL backend but they do not seem to be supported for windows.

I have two cute GPUs available on my computer and I really feel that I am not taking advantage of them. What would you recommend?

Thank you in advance.

**Comment by glenn-jocher** [comment]
@ignasiven follow https://docs.ultralytics.com/tutorials/multi-gpu-training/ and use our Docker image for all Multi-GPU DDP training.
