### ISSUE TITLE
How to to make a decision after detection?

### ISSUE THREAD

**Issue by hasnatahmed650** [ultralytics/yolov5#6922]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi , I have made a detection of a object through this code. Now I want to make a decision like when the detection happens, a alarm of buzzer should be on. What should I do for this? Should I use Arduino interfacing with this code? What amendments should I do?

**Comment by spacewalk01** [comment]
You can use the predicted bounding boxes and their classes for your task. For example:
```
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, custom

# Images
img = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, PIL, OpenCV, numpy, list

# Inference
results = model(img)

# Results
if 'your class' in results.pandas().xyxy[0]['name'].tolist(): 
    set_alarm() # your function
```

**Comment by hasnatahmed650** [comment]
Should I use arduino with python for this?

**Comment by hasnatahmed650** [comment]
Currently, I am doing my project of locust detection through yolov5! I have first created a dataset of locusts and then trained it through google colab. Then I downloaded the training model and detected a real-time locust. Now, this is where I need help! I want to turn "ON" the alarm/buzzer after the locust detection.

**Comment by 1Yleng** [comment]
> Currently, I am doing my project of locust detection through yolov5! I have first created a dataset of locusts and then trained it through google colab. Then I downloaded the training model and detected a real-time locust. Now, this is where I need help! I want to turn "ON" the alarm/buzzer after the locust detection.

How did you solve it, please?

**Comment by Akbar-Andi98** [comment]
I also faced a similar problem, did you solve it?

**Comment by glenn-jocher** [comment]
@Akbar-Andi98 you can use the predicted bounding boxes and their classes from the YOLOv5 detection results and then trigger an alarm using a GPIO library if you are using a Raspberry Pi, or communicate with an Arduino using a serial port if you are using an Arduino board. Here's a pseudocode example using Python with Raspberry Pi GPIO library:

```python
import RPi.GPIO as GPIO

# set up GPIO
GPIO.setmode(GPIO.BCM)
GPIO.setup(your_pin_number, GPIO.OUT)

# Inference
results = model(img)

# Results
if 'your class' in results.pandas().xyxy[0]['name'].tolist(): 
    GPIO.output(your_pin_number, GPIO.HIGH)  # turn on alarm
```

For more detailed information, I recommend checking the documentation of the GPIO library for Raspberry Pi or the serial library for Arduino.

**Comment by Akbar-Andi98** [comment]
> @Akbar-Andi98 you can use the predicted bounding boxes and their classes from the YOLOv5 detection results and then trigger an alarm using a GPIO library if you are using a Raspberry Pi, or communicate with an Arduino using a serial port if you are using an Arduino board. Here's a pseudocode example using Python with Raspberry Pi GPIO library:
> 
> ```python
> import RPi.GPIO as GPIO
> 
> # set up GPIO
> GPIO.setmode(GPIO.BCM)
> GPIO.setup(your_pin_number, GPIO.OUT)
> 
> # Inference
> results = model(img)
> 
> # Results
> if 'your class' in results.pandas().xyxy[0]['name'].tolist(): 
>     GPIO.output(your_pin_number, GPIO.HIGH)  # turn on alarm
> ```
> 
> For more detailed information, I recommend checking the documentation of the GPIO library for Raspberry Pi or the serial library for Arduino.

Thanks a lot! Currently Im using a pc, do you think it is possible to connect it to arduino or any microcontroller? Thanks in advance!

**Comment by glenn-jocher** [comment]
@Akbar-Andi98 absolutely, you can connect your PC to an Arduino or microcontroller for triggering the alarm. You can use a USB connection and the `pyserial` library in Python to communicate with the Arduino. Here's an example:

```python
import serial

# Connect to Arduino
arduino = serial.Serial('COM3', 9600)  # Replace 'COM3' with the your serial port

# Inference
results = model(img)

# Results
if 'your class' in results.pandas().xyxy[0]['name'].tolist(): 
    arduino.write(b'1')  # send signal to Arduino to turn on alarm
```

Replace `'COM3'` with the correct port for your Arduino. Also, ensure that you have the `pyserial` library installed.

Good luck with your project! Let me know if you need further assistance!
