### ISSUE TITLE
how to delete accuracies numbers beside class names

### ISSUE THREAD

**Issue by besbesmany** [ultralytics/yolov5#6923]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to delete detection accuracies numbers that written beside class names

what should I change in detect.py

![1](https://user-images.githubusercontent.com/35992924/157537857-e27abd3c-9b59-4ef6-99a7-b7e3dd616dea.png)

**Comment by spacewalk01** [comment]
You can use `hide_conf` argument when you run detect.py to hide confidence scores as follows:
`python detect.py --source 0 --hide-conf`

**Comment by spacewalk01** [comment]
python detect.py --source 0  --hide-conf True
