### ISSUE TITLE
Training YOLOv5 to detect face mask

### ISSUE THREAD

**Issue by spacewalk01** [ultralytics/yolov5#6924]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Created a repo for training yolov5 to detect face mask
https://github.com/spacewalk01/face-mask-detection

**Comment by glenn-jocher** [comment]
@spacewalk01 wow super cool! Thank you for your contributions!
