### ISSUE TITLE
`save_json` in val.py leads to error due to hardcoded annotation path

### ISSUE THREAD

**Issue by DavidBaldsiefen** [ultralytics/yolov5#6925]
### Bug

When executing `val.py` on a custom dataset with `--save-json`, the following error occurs:

```
Evaluating pycocotools mAP... saving runs/val/exp16/final-weights_predictions.json...
loading annotations into memory...
pycocotools unable to run: [Errno 2] No such file or directory: '../coco/annotations/instances_val2017.json'
```

This is most likely related to the hardcoded annotation path in `val.py`:

https://github.com/ultralytics/yolov5/blob/6dd82c025298d219a1eb1fe8e486fb99d5324d34/val.py#L289

**Comment by glenn-jocher** [comment]
@DavidBaldsiefen yes you are right. Maybe the annotations JSON should be an input argument with the COCO path as the default? Can you please submit a PR for this if you have time? Thanks!
