### ISSUE TITLE
About v6.0 yolov5-bifpn.yaml

### ISSUE THREAD

**Issue by Wanghe1997** [ultralytics/yolov5#6926]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello author, I have two questions to ask you.
1. Is the yaml file integrated with bifpn in P3, P4 and P5? Or only added bifpn on P4?
2. Can the 5.0 version code use the yaml model configuration file? Or must v6.0 and above be used to support the use of bifpn.yaml?
thanks
[https://github.com/ultralytics/yolov5/blob/v6.0/models/hub/yolov5-bifpn.yaml](url)

**Comment by glenn-jocher** [comment]
@Wanghe1997 our bifpn head is identical to the head proposed in EfficientDet https://arxiv.org/abs/1911.09070, though the differences with the YOLOv5 PANet head are extremely minor, and we were not able to derive performance gains on COCO with it. You can just diff the bifpn yaml with the default model yaml to see the difference, which is just one added skip connection in the head.

<img width="708" alt="Screenshot 2022-03-10 at 11 49 17" src="https://user-images.githubusercontent.com/26833433/157646729-a3b1232b-d629-4416-a931-8fb8b1d8fade.png">

Model yamls are generally supported in the version they are introduced in and later. Backward compatibility is not guaranteed.

**Comment by OhSnapItsNeilStudent** [comment]
> @Wanghe1997 our bifpn head is identical to the head proposed in EfficientDet https://arxiv.org/abs/1911.09070, though the differences with the YOLOv5 PANet head are extremely minor, and we were not able to derive performance gains on COCO with it. You can just diff the bifpn yaml with the default model yaml to see the difference, which is just one added skip connection in the head.
> 
> <img alt="Screenshot 2022-03-10 at 11 49 17" width="708" src="https://user-images.githubusercontent.com/26833433/157646729-a3b1232b-d629-4416-a931-8fb8b1d8fade.png">
> 
> Model yamls are generally supported in the version they are introduced in and later. Backward compatibility is not guaranteed.

Hi Glenn!

Just reviewing how bifpn was implemented on yolov5 for a personal project. Was wondering if you were able to apply the bifpn here as "repeated blocks". I'm looking at the yaml file and it seems that the bifpn section only happens one before the detection.

Thanks in advance!
