### ISSUE TITLE
Running YOLOv5 on a conda environment

### ISSUE THREAD

**Issue by edehino** [ultralytics/yolov5#6927]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am trying to run yolov5 in a conda environment. However, thop and opencv-python packages are not available when I run 
`conda install --file requirements.txt`

There's opencv available under conda forge but I think it cause an error. Error message is as follow:
`ImportError: /home/usr/anaconda3/envs/env2/bin/../lib/libgio-2.0.so.0: undefined symbol: g_unix_get_passwd_entry`

When i try to run train.py,I get the error above. And below is the whole error

`Traceback (most recent call last):
  File "train.py", line 41, in <module>
    import val  # for end-of-epoch mAP
  File "/home/usr/YOLO/yolov5/val.py", line 38, in <module>
    from models.common import DetectMultiBackend
  File "/home/usr/YOLO/yolov5/models/common.py", line 14, in <module>
    import cv2
  File "/home/usr/YOLO/py38/lib/python3.8/site-packages/cv2/__init__.py", line 8, in <module>
    from .cv2 import *
ImportError: /home/usr/anaconda3/envs/env2/bin/../lib/libgio-2.0.so.0: undefined symbol: g_unix_get_passwd_entry
`

1. Is there any way to get thop and opencv using conda command?
2. Does opencv has something to do with libgio-2.0.so.0?

**Comment by spacewalk01** [comment]
Try using `pip install opencv-python`

**Comment by edehino** [comment]
> Try using `pip install opencv-python`

Hi, I want my packages to contain only on my conda environment so I am avoiding to use pip

**Comment by spacewalk01** [comment]
https://github.com/opencv/opencv/issues/7940

**Comment by ralphflat** [comment]
Conda allows PIP to run inside of it.  The following example is something close to what is needed for detect.py (I am not using detect.py directly, so the sample might be missing some dependencies).  Note I am behind a corporate firewall, so needed to add in two trusted hosts for PIP operations (might not be needed by you).

`name: xxxxx
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - attrs=21.2.0=pyhd8ed1ab_0
  - boltons=21.0.0=pyhd8ed1ab_0
  - brotlipy=0.7.0=py38h497a2fe_1001
  - bzip2=1.0.8=h516909a_3
  - ca-certificates=2021.5.30=ha878542_0
  - cairo=1.16.0=h6cf1ce9_1008
  - certifi=2021.5.30=py38h578d9bd_0
  - cffi=1.14.5=py38ha65f79e_0
  - chardet=4.0.0=py38h578d9bd_1
  - click=7.1.2=pyh9f0ad1d_0
  - cryptography=3.4.7=py38ha5dfef3_0
  - cycler=0.10.0=py_2
  - dbus=1.13.6=he372182_0
  - decorator=5.0.7=pyhd8ed1ab_0
  - expat=2.3.0=h9c3ff4c_0
  - face=20.1.1=py_0
  - fastapi=0.63.0=pyhd8ed1ab_0
  - ffmpeg=4.3.1=h3215721_1
  - fontconfig=2.13.1=hba837de_1005
  - freetype=2.10.4=h7ca028e_0
  - future=0.18.2=py38h578d9bd_3
  - gettext=0.19.8.1=h0b5b191_1005
  - glib=2.68.1=h9c3ff4c_0
  - glib-tools=2.68.1=h9c3ff4c_0
  - glom=20.11.0=pyhd3deb0d_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - graphite2=1.3.13=h58526e2_1001
  - gst-plugins-base=1.18.4=h29181c9_0
  - gstreamer=1.18.4=h76c114f_0
  - h11=0.12.0=pyhd8ed1ab_0
  - harfbuzz=2.8.0=h83ec7ef_1
  - hdf5=1.10.6=nompi_h3c11f04_101
  - httptools=0.1.1=py38h497a2fe_2
  - icu=68.1=h58526e2_0
  - idna=2.10=pyh9f0ad1d_0
  - jasper=1.900.1=h07fcdf6_1006
  - jpeg=9d=h36c2ea0_0
  - kafka-python=2.0.2=pyh9f0ad1d_0
  - kiwisolver=1.3.1=py38h1fd1430_1
  - krb5=1.17.2=h926e7f8_0
  - lame=3.100=h14c3975_1001
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.9.0=8_mkl
  - libcblas=3.9.0=8_mkl
  - libclang=11.1.0=default_ha53f305_0
  - libedit=3.1.20191231=he28a2e2_2
  - libevent=2.1.10=hcdb4288_3
  - libffi=3.3=h58526e2_2
  - libgcc-ng=9.3.0=h2828fa1_19
  - libgfortran-ng=7.5.0=h14aa051_19
  - libgfortran4=7.5.0=h14aa051_19
  - libglib=2.68.1=h3e27bee_0
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=8_mkl
  - liblapacke=3.9.0=8_mkl
  - libllvm10=10.0.1=he513fc3_3
  - libllvm11=11.1.0=hf817b99_2
  - libopenblas=0.3.12=pthreads_hb3c22a3_1
  - libopencv=4.5.0=py38_3
  - libpng=1.6.37=h21135ba_2
  - libpq=13.2=hfd2b0eb_2
  - libprotobuf=3.15.8=h780b84a_0
  - libstdcxx-ng=9.3.0=h6de172a_19
  - libtiff=4.1.0=h4f3a223_6
  - libuuid=2.32.1=h14c3975_1000
  - libuv=1.41.0=h7f98852_0
  - libwebp-base=1.1.0=h36c2ea0_3
  - libxcb=1.13=h14c3975_1002
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.10=h72842e0_4
  - llvm-openmp=11.1.0=h4bd325d_1
  - lz4-c=1.9.3=h9c3ff4c_0
  - matplotlib=3.4.1=py38h578d9bd_0
  - matplotlib-base=3.4.1=py38hcc49a3a_0
  - mkl=2020.4=h726a3e6_304
  - mysql-common=8.0.23=ha770c72_1
  - mysql-libs=8.0.23=h935591d_1
  - ncurses=6.2=he6710b0_1
  - nettle=3.6=he412f7d_0
  - ninja=1.10.2=h4bd325d_0
  - nspr=4.30=h9c3ff4c_0
  - nss=3.64=hb5efdd6_0
  - numpy=1.19.4=py38hf0fd68c_1
  - olefile=0.46=pyh9f0ad1d_1
  - opencv=4.5.0=py38_3
  - openh264=2.1.1=h8b12597_0
  - openssl=1.1.1k=h7f98852_0
  - pandas=1.2.4=py38h1abd341_0
  - patsy=0.5.1=py_0
  - pcre=8.44=he1b5a44_0
  - pillow=7.2.0=py38h9776b28_0
  - pip=21.0.1=py38h06a4308_0
  - pixman=0.40.0=h36c2ea0_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - py-opencv=4.5.0=py38h81c977d_3
  - pycparser=2.20=pyh9f0ad1d_2
  - pydantic=1.8.1=py38h497a2fe_1
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py38h578d9bd_7
  - pyqt-impl=5.12.3=py38h7400c14_7
  - pyqt5-sip=4.19.18=py38h709712a_7
  - pyqtchart=5.12=py38h7400c14_7
  - pyqtwebengine=5.12.1=py38h7400c14_7
  - pysocks=1.7.1=py38h578d9bd_3
  - python=3.8.8=hdb3f193_5
  - python-dateutil=2.8.1=py_0
  - python-dotenv=0.17.1=pyhd8ed1ab_0
  - python_abi=3.8=1_cp38
  - pytz=2021.1=pyhd8ed1ab_0
  - pyyaml=5.4.1=py38h497a2fe_0
  - qt=5.12.9=hda022c4_4
  - readline=8.1=h27cfd23_0
  - requests=2.25.1=pyhd3deb0d_0
  - scipy=1.5.3=py38h828c644_0
  - seaborn=0.11.1=hd8ed1ab_1
  - seaborn-base=0.11.1=pyhd8ed1ab_1
  - setuptools=52.0.0=py38h06a4308_0
  - six=1.15.0=pyh9f0ad1d_0
  - sleef=3.5.1=h7f98852_1
  - sqlite=3.35.4=hdfb4753_0
  - starlette-base=0.13.6=py_0
  - statsmodels=0.12.2=py38h5c078b8_0
  - tk=8.6.10=h21135ba_1
  - tornado=6.1=py38h497a2fe_1
  - tqdm=4.60.0=pyhd8ed1ab_0
  - typing-extensions=3.7.4.3=0
  - typing_extensions=3.7.4.3=py_0
  - urllib3=1.26.4=pyhd8ed1ab_0
  - uvicorn=0.13.4=py38h578d9bd_0
  - uvloop=0.15.2=py38h497a2fe_0
  - validators=0.18.2=pyhd3deb0d_0
  - watchgod=0.6=py_0
  - websockets=8.1=py38h497a2fe_3
  - wheel=0.36.2=pyhd3eb1b0_0
  - x264=1!152.20180806=h14c3975_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h516909a_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=ha95c52a_0
  - pip:
    - --trusted-host pypi.org
    - --trusted-host files.pythonhosted.org
    - opencv-python==4.5.2.52
    - torch==1.9.0
    - torchvision==0.10.0
prefix: `

**Comment by edehino** [comment]
> Conda allows PIP to run inside of it. The following example is something close to what is needed for detect.py (I am not using detect.py directly, so the sample might be missing some dependencies). Note I am behind a corporate firewall, so needed to add in two trusted hosts for PIP operations (might not be needed by you).
> 
> `name: xxxxx channels:
> 
>     * conda-forge
> 
>     * defaults
>       dependencies:
> 
>     * _libgcc_mutex=0.1=conda_forge
> 
>     * _openmp_mutex=4.5=1_llvm
> 
>     * attrs=21.2.0=pyhd8ed1ab_0
> 
>     * boltons=21.0.0=pyhd8ed1ab_0
> 
>     * brotlipy=0.7.0=py38h497a2fe_1001
> 
>     * bzip2=1.0.8=h516909a_3
> 
>     * ca-certificates=2021.5.30=ha878542_0
> 
>     * cairo=1.16.0=h6cf1ce9_1008
> 
>     * certifi=2021.5.30=py38h578d9bd_0
> 
>     * cffi=1.14.5=py38ha65f79e_0
> 
>     * chardet=4.0.0=py38h578d9bd_1
> 
>     * click=7.1.2=pyh9f0ad1d_0
> 
>     * cryptography=3.4.7=py38ha5dfef3_0
> 
>     * cycler=0.10.0=py_2
> 
>     * dbus=1.13.6=he372182_0
> 
>     * decorator=5.0.7=pyhd8ed1ab_0
> 
>     * expat=2.3.0=h9c3ff4c_0
> 
>     * face=20.1.1=py_0
> 
>     * fastapi=0.63.0=pyhd8ed1ab_0
> 
>     * ffmpeg=4.3.1=h3215721_1
> 
>     * fontconfig=2.13.1=hba837de_1005
> 
>     * freetype=2.10.4=h7ca028e_0
> 
>     * future=0.18.2=py38h578d9bd_3
> 
>     * gettext=0.19.8.1=h0b5b191_1005
> 
>     * glib=2.68.1=h9c3ff4c_0
> 
>     * glib-tools=2.68.1=h9c3ff4c_0
> 
>     * glom=20.11.0=pyhd3deb0d_0
> 
>     * gmp=6.2.1=h58526e2_0
> 
>     * gnutls=3.6.13=h85f3911_1
> 
>     * graphite2=1.3.13=h58526e2_1001
> 
>     * gst-plugins-base=1.18.4=h29181c9_0
> 
>     * gstreamer=1.18.4=h76c114f_0
> 
>     * h11=0.12.0=pyhd8ed1ab_0
> 
>     * harfbuzz=2.8.0=h83ec7ef_1
> 
>     * hdf5=1.10.6=nompi_h3c11f04_101
> 
>     * httptools=0.1.1=py38h497a2fe_2
> 
>     * icu=68.1=h58526e2_0
> 
>     * idna=2.10=pyh9f0ad1d_0
> 
>     * jasper=1.900.1=h07fcdf6_1006
> 
>     * jpeg=9d=h36c2ea0_0
> 
>     * kafka-python=2.0.2=pyh9f0ad1d_0
> 
>     * kiwisolver=1.3.1=py38h1fd1430_1
> 
>     * krb5=1.17.2=h926e7f8_0
> 
>     * lame=3.100=h14c3975_1001
> 
>     * ld_impl_linux-64=2.33.1=h53a641e_7
> 
>     * libblas=3.9.0=8_mkl
> 
>     * libcblas=3.9.0=8_mkl
> 
>     * libclang=11.1.0=default_ha53f305_0
> 
>     * libedit=3.1.20191231=he28a2e2_2
> 
>     * libevent=2.1.10=hcdb4288_3
> 
>     * libffi=3.3=h58526e2_2
> 
>     * libgcc-ng=9.3.0=h2828fa1_19
> 
>     * libgfortran-ng=7.5.0=h14aa051_19
> 
>     * libgfortran4=7.5.0=h14aa051_19
> 
>     * libglib=2.68.1=h3e27bee_0
> 
>     * libiconv=1.16=h516909a_0
> 
>     * liblapack=3.9.0=8_mkl
> 
>     * liblapacke=3.9.0=8_mkl
> 
>     * libllvm10=10.0.1=he513fc3_3
> 
>     * libllvm11=11.1.0=hf817b99_2
> 
>     * libopenblas=0.3.12=pthreads_hb3c22a3_1
> 
>     * libopencv=4.5.0=py38_3
> 
>     * libpng=1.6.37=h21135ba_2
> 
>     * libpq=13.2=hfd2b0eb_2
> 
>     * libprotobuf=3.15.8=h780b84a_0
> 
>     * libstdcxx-ng=9.3.0=h6de172a_19
> 
>     * libtiff=4.1.0=h4f3a223_6
> 
>     * libuuid=2.32.1=h14c3975_1000
> 
>     * libuv=1.41.0=h7f98852_0
> 
>     * libwebp-base=1.1.0=h36c2ea0_3
> 
>     * libxcb=1.13=h14c3975_1002
> 
>     * libxkbcommon=1.0.3=he3ba5ed_0
> 
>     * libxml2=2.9.10=h72842e0_4
> 
>     * llvm-openmp=11.1.0=h4bd325d_1
> 
>     * lz4-c=1.9.3=h9c3ff4c_0
> 
>     * matplotlib=3.4.1=py38h578d9bd_0
> 
>     * matplotlib-base=3.4.1=py38hcc49a3a_0
> 
>     * mkl=2020.4=h726a3e6_304
> 
>     * mysql-common=8.0.23=ha770c72_1
> 
>     * mysql-libs=8.0.23=h935591d_1
> 
>     * ncurses=6.2=he6710b0_1
> 
>     * nettle=3.6=he412f7d_0
> 
>     * ninja=1.10.2=h4bd325d_0
> 
>     * nspr=4.30=h9c3ff4c_0
> 
>     * nss=3.64=hb5efdd6_0
> 
>     * numpy=1.19.4=py38hf0fd68c_1
> 
>     * olefile=0.46=pyh9f0ad1d_1
> 
>     * opencv=4.5.0=py38_3
> 
>     * openh264=2.1.1=h8b12597_0
> 
>     * openssl=1.1.1k=h7f98852_0
> 
>     * pandas=1.2.4=py38h1abd341_0
> 
>     * patsy=0.5.1=py_0
> 
>     * pcre=8.44=he1b5a44_0
> 
>     * pillow=7.2.0=py38h9776b28_0
> 
>     * pip=21.0.1=py38h06a4308_0
> 
>     * pixman=0.40.0=h36c2ea0_0
> 
>     * pthread-stubs=0.4=h36c2ea0_1001
> 
>     * py-opencv=4.5.0=py38h81c977d_3
> 
>     * pycparser=2.20=pyh9f0ad1d_2
> 
>     * pydantic=1.8.1=py38h497a2fe_1
> 
>     * pyopenssl=20.0.1=pyhd8ed1ab_0
> 
>     * pyparsing=2.4.7=pyh9f0ad1d_0
> 
>     * pyqt=5.12.3=py38h578d9bd_7
> 
>     * pyqt-impl=5.12.3=py38h7400c14_7
> 
>     * pyqt5-sip=4.19.18=py38h709712a_7
> 
>     * pyqtchart=5.12=py38h7400c14_7
> 
>     * pyqtwebengine=5.12.1=py38h7400c14_7
> 
>     * pysocks=1.7.1=py38h578d9bd_3
> 
>     * python=3.8.8=hdb3f193_5
> 
>     * python-dateutil=2.8.1=py_0
> 
>     * python-dotenv=0.17.1=pyhd8ed1ab_0
> 
>     * python_abi=3.8=1_cp38
> 
>     * pytz=2021.1=pyhd8ed1ab_0
> 
>     * pyyaml=5.4.1=py38h497a2fe_0
> 
>     * qt=5.12.9=hda022c4_4
> 
>     * readline=8.1=h27cfd23_0
> 
>     * requests=2.25.1=pyhd3deb0d_0
> 
>     * scipy=1.5.3=py38h828c644_0
> 
>     * seaborn=0.11.1=hd8ed1ab_1
> 
>     * seaborn-base=0.11.1=pyhd8ed1ab_1
> 
>     * setuptools=52.0.0=py38h06a4308_0
> 
>     * six=1.15.0=pyh9f0ad1d_0
> 
>     * sleef=3.5.1=h7f98852_1
> 
>     * sqlite=3.35.4=hdfb4753_0
> 
>     * starlette-base=0.13.6=py_0
> 
>     * statsmodels=0.12.2=py38h5c078b8_0
> 
>     * tk=8.6.10=h21135ba_1
> 
>     * tornado=6.1=py38h497a2fe_1
> 
>     * tqdm=4.60.0=pyhd8ed1ab_0
> 
>     * typing-extensions=3.7.4.3=0
> 
>     * typing_extensions=3.7.4.3=py_0
> 
>     * urllib3=1.26.4=pyhd8ed1ab_0
> 
>     * uvicorn=0.13.4=py38h578d9bd_0
> 
>     * uvloop=0.15.2=py38h497a2fe_0
> 
>     * validators=0.18.2=pyhd3deb0d_0
> 
>     * watchgod=0.6=py_0
> 
>     * websockets=8.1=py38h497a2fe_3
> 
>     * wheel=0.36.2=pyhd3eb1b0_0
> 
>     * x264=1!152.20180806=h14c3975_0
> 
>     * xorg-kbproto=1.0.7=h14c3975_1002
> 
>     * xorg-libice=1.0.10=h516909a_0
> 
>     * xorg-libsm=1.2.3=h84519dc_1000
> 
>     * xorg-libx11=1.6.12=h516909a_0
> 
>     * xorg-libxau=1.0.9=h14c3975_0
> 
>     * xorg-libxdmcp=1.1.3=h516909a_0
> 
>     * xorg-libxext=1.3.4=h516909a_0
> 
>     * xorg-libxrender=0.9.10=h516909a_1002
> 
>     * xorg-renderproto=0.11.1=h14c3975_1002
> 
>     * xorg-xextproto=7.3.0=h14c3975_1002
> 
>     * xorg-xproto=7.0.31=h14c3975_1007
> 
>     * xz=5.2.5=h7b6447c_0
> 
>     * yaml=0.2.5=h516909a_0
> 
>     * zlib=1.2.11=h7b6447c_3
> 
>     * zstd=1.4.9=ha95c52a_0
> 
>     * pip:
>       
>       * --trusted-host pypi.org
>       * --trusted-host files.pythonhosted.org
>       * opencv-python==4.5.2.52
>       * torch==1.9.0
>       * torchvision==0.10.0
>         prefix: `

@ralphflat thank you so much for this I figured out I can use pip inside the conda environment by specifying the full path of my environment (home/usr/anaconda3/envs/env1/bin/ pip install <package_name>)

Now I have issue with the auto update feature of yolov5. I think I'm creating a new question for that. 


Thank you so much for your help @ralphflat @spacewalk01
