### ISSUE TITLE
Can yolov5 detect the 4 vertices of the target object? instead of 2 vertices? Is there any public code?

### ISSUE THREAD

**Issue by daigang896** [ultralytics/yolov5#6929]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello.
Can yolov5 detect the 4 vertices of the target object? instead of 2 vertices? Is there any public code?

**Comment by wudashuo** [comment]
You mean rotated bounding boxes? 
No

**Comment by daigang896** [comment]
Four vertices of a quadrilateral of a general object. I'll look for it again.

**Comment by wudashuo** [comment]
> Four vertices of a quadrilateral of a general object. I'll look for it again.

If you know the two point(left top and right bottom), you know all the four point.
For example, you already knew (x1, y1) and (x2, y2), the other two points are (x2, y1) and (x1, y2)
It doesn't need any code to convert.
