### ISSUE TITLE
ERROR: pycocotools unable to run: list index out of range

### ISSUE THREAD

**Issue by bigcindy** [ultralytics/yolov5#693]
## ❔Question
When i run this command "python test.py --save-json --task test", an error appears:

COCO mAP with pycocotools... saving detections_val2017_yolov5s_results.json...
ERROR: pycocotools unable to run: list index out of range

How can i fix it？ THX

**Comment by glenn-jocher** [comment]
@bigcindy you have your json right. What else are you looking for?
