### ISSUE TITLE
Why e value of Bottleneck in C3 is 1.0 ?

### ISSUE THREAD

**Issue by DoHoNi** [ultralytics/yolov5#6930]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I wonder why the value of e, the bottleneck factor in C3, is 1.0.

https://github.com/ultralytics/yolov5/blob/e6e36aac109794999f1dafab244b9ec4887a33d1/models/common.py#L127-L135
The value of e in **line135 is represented by 1.0.**

The value cause the number of the 1x1 conv and 3x3 conv filters in the bottleneck module to be the same. 
I think that the originally intended function of bottleneck has been distored.
https://github.com/ultralytics/yolov5/blob/e6e36aac109794999f1dafab244b9ec4887a33d1/models/common.py#L95-L105

Any problem with this part?
Or am I misunderstood?

**Comment by glenn-jocher** [comment]
@DoHoNi yes your understanding is correct. The C3 modules are simplified CSP modules first defined by @WongKinYiu in CSPNet and then later used in YOLOv4 and initial versions of YOLOv5. The CSP module design uses an expansion of 0.5 at the input and 1.0 after that in the sequential 1x1 and 3x3 convolutions, so their effective expansion is 1.0 * 0.5 = 0.5 compared to the input channel count. 

The 1x1 and 3x3 convolutions in series share the same channel count as you said.

**Comment by DoHoNi** [comment]
Thank you for your answer.

So, you mean that the number of channels in the input of the bottleneck function is already half of the original number of channels.

I am just curious if the current method is more efficient than reducing the channel at the bottleneck. 
Also, I am curious If when the input of the bottleneck function is reduced by half, it is not good to reduce the number of channels once more inside the bottleneck.

**Comment by glenn-jocher** [comment]
@DoHoNi feel free to modify the architecture and quantify the performance differences of your proposed alterations.

**Comment by DoHoNi** [comment]
@glenn-jocher  okay :) thanks!
