### ISSUE TITLE
Identify clusters within a specific image object class?

### ISSUE THREAD

**Issue by christianepedersen** [ultralytics/yolov5#6937]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have had a lot of success using YOLOv5 for my image object detection application. I have labeled about ~2000 images with 5 distinct object classes and have seen really impressive precision and recall, even on entirely separate images that weren't used for training.

In order to make the manual labeling process easier on myself, I have grouped a number of visually distinct kinds of objects into one umbrella class (analogy: "Animals"). Within this umbrella class, there are several distinct subclasses that I have not specifically labeled (analogy: "Tigers", "Bears", "Kangaroos"). 

It is possible for me to access activations of intermediate layers from YOLO to see the variance of visual features within my umbrella object class? Ideally I would see several distinct clusters by doing this and that could help guide my future labeling to capture the specific subclasses within my umbrella class.

I can try to do this myself with some custom code, but I would love any recommendations from YOLOv5 experts if you have them. Many thanks!

**Comment by glenn-jocher** [comment]
@christianepedersen 👋 Hello! Thanks for asking about **feature visualization**.  

Yes you can group object together arbitrarily and YOLOv5 will still work well. This already happens with many default models, i.e. women and men are grouped into person class, etc.

YOLOv5 🚀 features can be visualized through all stages of the model from input to output. To visualize features from a given source run `detect.py` with the `--visualize` flag:
```bash
python detect.py --weights yolov5s.pt --source data/images/bus.jpg --visualize
```

An example [Notebook](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb) visualizing [bus.jpg](https://github.com/ultralytics/yolov5/blob/master/data/images/bus.jpg) features with YOLOv5s is shown below:

<a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
<img width="1811" alt="Screenshot 2021-08-30 at 16 44 04" src="https://user-images.githubusercontent.com/26833433/131357928-663a120a-3133-4e1a-8995-c812bd732e8a.png">

All stages are visualized by default, each with its own PNG showing the first 32 feature maps **output** from that stage. You can open any PNG for a closer look. For example the first 32 feature maps of the Focus() layer output are shown in `stage0_Focus_features.png`:

![stage0_Focus_features](https://user-images.githubusercontent.com/26833433/131359874-ecc9aef8-1c9b-44f5-ac17-d6b987093554.png)

Feature maps may be customized by updating the `feature_visualization()` function in `utils/plots.py`:
https://github.com/ultralytics/yolov5/blob/bb5ebc290e5d630a081d7cbc5a9725ed8cea0a24/utils/plots.py#L403-L427

Good luck 🍀 and let us know if you have any other questions!
