### ISSUE TITLE
how to get save-txt values yolov5 after train

### ISSUE THREAD

**Issue by samahwaleed** [ultralytics/yolov5#6942]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is it possible to get the coordinates of the bounding box in YOLOV5 from the training process?

from this line:
`!python val.py --weights  last.pt --data coco128.yaml --img 500 `

**Comment by glenn-jocher** [comment]
@samahwaleed I don't understand your question. image labels are inputs to training, not outputs.
