### ISSUE TITLE
Result mismatch in coco metrics

### ISSUE THREAD

**Issue by purvang3** [ultralytics/yolov5#6953]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Validation

### Bug

I see results are not same for mAP@0.50 and mAP@0.50:0.95 during training after each epoch. I have made changes in val.py
accordingly as I am using "xywh" format for bboxes.

I have commented line
#box[:, :2] -= box[:, 2:] / 2  # xy center to top-left corner as my gt in xywh format.

<img width="1652" alt="Screen Shot 2022-03-11 at 12 54 35 PM" src="https://user-images.githubusercontent.com/39809304/157964906-bb894799-ded1-4f4e-bee3-efc7d13d56f9.png">

### Environment

YOLOv5 🚀 v6.0-144-gc9a46a6 torch 1.10.2 CUDA:0 (NVIDIA RTX A4000, 16116MiB)                                                                                      
os : Ubuntu 18.04

### Minimal Reproducible Example

make save_json in val.run=True and start training.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@purvang3 yes mAP mismatch with pycocotools is a known issue, and there's actually an open competition to solve it in https://github.com/ultralytics/yolov5/issues/2258

We also have a few PRs related to mAP updates from users that you could try:

- https://github.com/ultralytics/yolov5/pull/6787
- https://github.com/ultralytics/yolov5/pull/6813

**Comment by dotnet-rs-py** [comment]
I had met the similar bug.
test.py in v4.0、v5.0 is OK.
val.py in v6.0、v6.1 is not OK.

**Comment by coderonion** [comment]
> @purvang3 yes mAP mismatch with pycocotools is a known issue, and there's actually an open competition to solve it in #2258
> 
> We also have a few PRs related to mAP updates from users that you could try:
> 
>     * [Improve mAP0.5-0.95 #6787](https://github.com/ultralytics/yolov5/pull/6787)
> 
>     * [Fix mAP bug at a higher conf #6813](https://github.com/ultralytics/yolov5/pull/6813)

I had the same problem.
test.py in v4.0、v5.0 is OK.
val.py in v6.0、v6.1 is not OK.
Please see blow.
![v5 0](https://user-images.githubusercontent.com/99076655/158179856-8f63fec8-cba3-4f6e-964c-3ad9194233b4.png)
![v6 0](https://user-images.githubusercontent.com/99076655/158179894-6d5b40c4-0dab-41dc-9fe4-912d49ccfeb9.png)

**Comment by glenn-jocher** [comment]
@dotnet-rs-py we have a warning in place to advise users of incorrect settings. mAP should be calculated at --conf 0.0 for best results, we compute at --conf 0.001 for significant speed improvements at near identical results. Anything above that will not allow for a full integration of the PR curve from 0 to 1, which will result in incorrect mAP.

https://github.com/ultralytics/yolov5/blob/99de551f979f6aca1f817504831c821cff64b5fd/val.py#L352-L353
