### ISSUE TITLE
Error: Exception ignored in: <function StorageWeakRef.__del__ ...

### ISSUE THREAD

**Issue by magicsoft75** [ultralytics/yolov5#6962]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Validation

### Bug

Hello.
Error occurs after training:
_Speed: 0.4ms pre-process, 64.8ms inference, 1.0ms NMS per image at shape (32, 3, 640, 640)
Results saved to runs/val/exp3
Exception ignored in: <function StorageWeakRef.__del__ at 0x7f6bb5f141f0>
Traceback (most recent call last):
  File "/home/mm/p38/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/mm/p38/lib/python3.8/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7f6bb5f141f0>
Traceback (most recent call last):
  File "/home/mm/p38/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/mm/p38/lib/python3.8/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7f6bb5f141f0>
Traceback (most recent call last):
  File "/home/mm/p38/lib/python3.8/site-packages/torch/multiprocessing/reductions.py",_
...
Do you have any suggestion?

### Environment

- OS: Ubuntu 18.04
- Python: 3.8
- YOLOv5: after git pull

### Minimal Reproducible Example

!python3 train.py --img 640 --batch 8 --epochs 25 --data ./data.yaml --cfg ./models/yolov5s.yaml --weights yolov5s.pt

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@magicsoft75 I just observed this same error today in our YOLOv5 Ubuntu CPU image when running `python val.py`. I don't know the cause and I don't see it anywhere else (MacOS, Colab etc.)
```
docker pull ultralytics/yolov5:cpu_benchmarks
```
If you have any insights into the problem or find a solution please let us know!

**Comment by magicsoft75** [comment]
Ok, I have solved this problem for now - the newest version of pytorch (1.11) is incompatible (probably) with yolov5 6.0
I changed version to 1.8:
`pip install --upgrade --force-reinstall torch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0`

**Comment by b0unc3** [comment]
That fix the issue for me. Thanks @magicsoft75 !

**Comment by 3gfisch** [comment]
Hi i have just freshly started with PyTorch and was following the [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data) with coco128 and get similar errors.
Is there a fix in progress?

Downgrading doesnt work for me, error:
`ERROR: Could not find a version that satisfies the requirement torch==1.8.0 (from versions: 1.9.0, 1.10.0, 1.10.1, 1.10.2, 1.11.0)
ERROR: No matching distribution found for torch==1.8.0`

my setup:
MacOS 12.2.1, Arm64 / M1, up to date repo and pip packages in miniforge

similar error in validation:
Results saved to runs/train/exp2
Exception ignored in: <function StorageWeakRef.__del__ at 0x10a83b3a0>
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch/lib/python3.8/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x10a83b3a0>
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch/lib/python3.8/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x10a83b3a0>
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch/lib/python3.8/site-packages/torch/storage.py", line 520, in _free_weak_ref
...

**Comment by glenn-jocher** [comment]
@3gfisch @magicsoft75 @b0unc3 this seems to originate in PyTorch. See https://github.com/pytorch/pytorch/issues/74016

**Comment by NeilPandya** [comment]
@b0unc3 @magicsoft75 @glenn-jocher @timstokman @3gfisch 
Hey guys, just wanted to say I ran into the same error after training, and I solved it "temporarily" by downgrading pytorch and torchvision.

`pip uninstall torch torchvision`

`pip install torch==1.10.0+cu113 torch torchvision==0.11.1+cu113`

Current build:
- Ubuntu 20.04.4
- AMD Ryzen 9 3950X
- NVIDIA 2070 Super
- 32GB DDR4 @3600Hz
- Docker

**Comment by kaplansinan** [comment]
Hei guys, I had the same issue after training and solved by downgrading pytorch and torchvision:
`pip install torch==1.10.0+cu113 torchvision==0.11.1+cu113  -f https://download.pytorch.org/whl/cu113/torch_stable.html`

My previous installation was: `pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113  -f https://download.pytorch.org/whl/cu113/torch_stable.html`

**Comment by wzshiwo** [comment]
I also encountered the same problem, in Windows terminal after entering the command given by the above two error：
ERROR: Could not find a version that satisfies the requirement torch==1.10.0+cu113 (from versions: 1.11.0, 1.11.0+cu113)
ERROR: No matching distribution found for torch==1.10.0+cu113
I donot know how to solve it

**Comment by magicsoft75** [comment]
As I wrote- downgrade torch and torchvision.

**Comment by CCRcmcpe** [comment]
Seems it's a already deleted object got referenced to delete again, no actual influence. Could just ignore it and keep using pytorch v1.11.0.

**Comment by wzshiwo** [comment]
Yes brother, the torch version in question no longer needs to be lowered, completed training

**Comment by Anastasia-CS** [comment]
I just observed this same error today when running .

"Stopping training early as no improvement observed in last 100 epochs. Best results observed at epoch 37, best model saved as best.pt. To update EarlyStopping(patience=100) pass a new patience value, i.e. `python train.py --patience 300` or use `--patience 0` to disable EarlyStopping. " is shown before the error. I got the best results and there isn't any error while detecting using the best result.

I guessed the error is caused by the auto interruption.

**Comment by glenn-jocher** [comment]
@Anastasia-CS yes early stopping is a feature that terminates training when your model is no longer improving.

**Comment by 200102200001** [comment]
Maybe there are some problems about  your  labels, one of them maybe none.

**Comment by 200102200001** [comment]
About the free _weak _ref, there may some problems about your labels, one of them maybe none.

**Comment by glenn-jocher** [comment]
@200102200001 it seems to be a PyTorch 1.11.0 issue unrelated to YOLOv5:
https://github.com/pytorch/pytorch/issues/74016

**Comment by jiluojiluo** [comment]
get the same problem on Window 11.please fix the bug.

**Comment by glenn-jocher** [comment]
@jiluojiluo torch team is aware and pushing a fix in https://github.com/pytorch/pytorch/issues/74016

**Comment by medic-lab** [comment]
PyTorch refusing downgrading to and recent PyTorch version doesn't working with YoloV5 what am i supposed to do?

`ERROR: Could not find a version that satisfies the requirement torch==1.10.0+cu113 (from versions: 1.11.0, 1.12.0)
ERROR: No matching distribution found for torch==1.10.0+cu113`

**Comment by glenn-jocher** [comment]
@medic-lab YOLOv5 version constraints resolved in https://github.com/ultralytics/yolov5/pull/8621
