### ISSUE TITLE
use yolov5-transformer's  .pt  to  detect  has a error ' Can't get attribute '_LinearWithBias' on <module 'torch.nn.modules.linear'              '

### ISSUE THREAD

**Issue by 14385423** [ultralytics/yolov5#6967]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

![image](https://user-images.githubusercontent.com/61214936/158052683-6f822827-3078-4520-9a8b-9db4b3cb4e4b.png)

**_use  yolov5s-transformer.yaml to get a best.pt ,use this to detect has a error ._**

### Environment

yolov5-5.0
py37 
cuda 10.2 
torch 1.9

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by 14385423** [comment]
py38 and torch 1.7.1 and cu11.0 can python3.8.10 don't have this error  . 
maybe the torch version    difference  ,it   has some update

**Comment by glenn-jocher** [comment]
@14385423 I can train and detect transformer models correctly in Colab:

```python
# Train YOLOv5s on COCO128 for 3 epochs
!python train.py --epochs 3 --weights yolov5s.pt --cfg yolov5s-transformer.yaml --cache
!python detect.py --weights runs/train/exp/weights/best.pt
```

<img width="1514" alt="Screenshot 2022-03-14 at 12 11 43" src="https://user-images.githubusercontent.com/26833433/158160869-d541b460-e90c-4213-bc26-8d982bb7031a.png">
