### ISSUE TITLE
How could I install tensorRT python api on windows?

### ISSUE THREAD

**Issue by ZZHHogan** [ultralytics/yolov5#6969]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When I export engine in window,but it occur this error:
![image](https://user-images.githubusercontent.com/40531744/158099304-a31e09e3-30e8-4c4d-b512-d7b8128515dd.png)
I can not install tensort python api on windows?So, how could I install tensorRT python api on windows?

**Comment by glenn-jocher** [comment]
@hhhhhhogan TensorRT usage example is shown in Colab notebook:
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

```python
# TensorRT 
# https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing-pip
!pip install -U nvidia-tensorrt --index-url https://pypi.ngc.nvidia.com  # install
!python export.py --weights yolov5s.pt --include engine --imgsz 640 640 --device 0  # export
!python detect.py --weights yolov5s.engine --imgsz 640 640 --device 0  # inference
```
