### ISSUE TITLE
With torchscript model, there is error for fp16(torch::kHalf)

### ISSUE THREAD

**Issue by wonchul-kim** [ultralytics/yolov5#6971]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When I export a model into torchscript, I have no problem to load the model and turn it into torch::kHalf.
However, when I make the model to forward with tensor-image which is turned into torch::kHalf, I got this problem....

if (m_Params.fp16) {
	tensor_img.to(torch::kHalf);
}
std::vector<torch::jit::IValue> inputs;
inputs.emplace_back(tensor_img);

torch::jit::IValue output = module_->forward(inputs);

>> 0x00007FFBCEF9286E(ucrtbase.dll) .............

what is wrong with it?

**Comment by glenn-jocher** [comment]
@wonchul-kim sorry I don't have C implementation experience, but we have run python benchmarks with torchscript models and they work with and without half on GPU.
