### ISSUE TITLE
Images Embeddings

### ISSUE THREAD

**Issue by Venky0892** [ultralytics/yolov5#6973]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to retrieve feature embeddings (activation scores) from the penultimate layer prior to the final output layer, any ideas?

Thanks in advance

**Comment by glenn-jocher** [comment]
@Venky0892 👋 Hello! Thanks for asking about **feature visualization**. YOLOv5 🚀 features can be visualized through all stages of the model from input to output. To visualize features from a given source run `detect.py` with the `--visualize` flag:
```bash
python detect.py --weights yolov5s.pt --source data/images/bus.jpg --visualize
```

An example [Notebook](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb) visualizing [bus.jpg](https://github.com/ultralytics/yolov5/blob/master/data/images/bus.jpg) features with YOLOv5s is shown below:

<a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
<img width="1811" alt="Screenshot 2021-08-30 at 16 44 04" src="https://user-images.githubusercontent.com/26833433/131357928-663a120a-3133-4e1a-8995-c812bd732e8a.png">

All stages are visualized by default, each with its own PNG showing the first 32 feature maps **output** from that stage. You can open any PNG for a closer look. For example the first 32 feature maps of the Focus() layer output are shown in `stage0_Focus_features.png`:

![stage0_Focus_features](https://user-images.githubusercontent.com/26833433/131359874-ecc9aef8-1c9b-44f5-ac17-d6b987093554.png)

Feature maps may be customized by updating the `feature_visualization()` function in `utils/plots.py`:
https://github.com/ultralytics/yolov5/blob/bb5ebc290e5d630a081d7cbc5a9725ed8cea0a24/utils/plots.py#L403-L427

Good luck 🍀 and let us know if you have any other questions!

**Comment by Venky0892** [comment]
Hi, @glenn-jocher thanks for your response. I'm looking to get image embeddings and image similarity. I was able to access the avg_pool_layer in the pre-trained CNN model of resnet18 to get the embeddings of images. Is there a way to do such a thing in yolov5 ? Link of what I'm trying to get - https://colab.research.google.com/drive/1eTtXTb-45Msfh9BZM4y7UUdj8cP-BQCI?usp=sharing#scrollTo=3YJPIGn-D5hm

**Comment by glenn-jocher** [comment]
@Venky0892 sure, you can access everything in the Detect() module. You can just put breakpoints in here when running inference to see what the features look like.
https://github.com/ultralytics/yolov5/blob/99de551f979f6aca1f817504831c821cff64b5fd/models/yolo.py#L33-L82
