### ISSUE TITLE
执行detect文件遇到的问题

### ISSUE THREAD

**Issue by huahuabai** [ultralytics/yolov5#6974]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

您好，按照requirements配置好环境之后，执行detect文件出现如下错误，我想请问这可能是由什么原因导致的？
![image](https://user-images.githubusercontent.com/55180640/158168194-4c08286c-2131-46b6-8eaf-91f546a54993.png)

**Comment by zhiqwang** [comment]
Seems this problem is caused due to a version mismatch between the official YOLOv5 and yolov5-pyqt5 .
