### ISSUE TITLE
After completing training detect part will show that error 

### ISSUE THREAD

**Issue by Ramarjohn** [ultralytics/yolov5#698]
i have to training the own image dataset used training model. but  detect.py file show that error below mentioned 
![Capture](https://user-images.githubusercontent.com/47788261/89798989-8b56b600-db4a-11ea-8a58-8020494038d8.PNG)
please give prepare solution and reason for that error,,

**Comment by NanoCode012** [comment]
Hi, you spelled the model wrong. It is not `yolov5.pt`. You can find the four models on the main page. `yolov5s.pt`, `yolov5m.pt`, `yolov5l.pt`, `yolov5x.pt`.
