### ISSUE TITLE
How to save results in images and json file

### ISSUE THREAD

**Issue by Chuttyboy** [ultralytics/yolov5#6985]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

`python3 detect.py --weights best.pt --img 640 --conf 0.25 --source 0`

To find custom object detection in live video streaming i run above mention command i works very well but i got result in video file but i expected in images file with some below conditions

```
1. How can i save video stream objects results as images and json files
2. How to set threshold values and if detected object is above threshold value save that particular frames into folder
3.  Get log report in json or text files for every seconds
```

How to resolve these issues with yolov5 is that possible to resolve those conditions

**Comment by glenn-jocher** [comment]
@Chuttyboy 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, etc.
# model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')  # custom trained model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by Chuttyboy** [comment]
Thanks for your reply its very usefull for my work .  how can i save detected object in log file for every second .

logfile :

 HH:MM:SS  - 2 person detected along with score , and tv detected , etc...

how to save detected object in logfile or text file for every seconds

**Comment by thomassajot** [comment]
Hi, I would like to generate predictions for a dataset and save the outputs. 
If I run inference sequentially as shown above, it would take 2 hours (78K images, image size 640). The script runs at 10it/s 
I think the script (val.py) runs much faster at 220it/s. 

Is there a way to run inference in parallel, given multiple gpus?

**Comment by glenn-jocher** [comment]
@thomassajot multiple PyTorch Hub models can be deployed to difference devices, etc.
