### ISSUE TITLE
YUV imageset

### ISSUE THREAD

**Issue by anubratabhowmick** [ultralytics/yolov5#6987]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Does YOLOv5 support YUV images as input?

**Comment by glenn-jocher** [comment]
@anubratabhowmick YOLOv5 supports any image encoding that cv2 supports. By default cv2 will load images in BGR format regardless of their original encoding.

**Comment by anubratabhowmick** [comment]
Thanks for the confirmation.
