### ISSUE TITLE
OpenImages Evaluation Metric

### ISSUE THREAD

**Issue by b3r-prog** [ultralytics/yolov5#6989]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Hello,

@glenn-jocher @zhiqwang @timstokman I wonder if anyone has tried implementing the official openimages evaluation metrics with yolov5?

### Use case

It would help with evaluating openimages data

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by b3r-prog** [comment]
https://github.com/tensorflow/models/tree/master/research/object_detection/metrics

**Comment by glenn-jocher** [comment]
@b3r-prog which metrics specifically are asking about?
