### ISSUE TITLE
Name structure of custom data for trainning

### ISSUE THREAD

**Issue by RoyCopter** [ultralytics/yolov5#6992]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hey,
I want to train my own custom data.
Just to be sure, are the image names in my data important for training?
And is it necessary to arrange the names of the pictures in a certain order for example: img0 img1 etc.? or it's ok to have img0.jpg, zidan.jpg, lalala.jpg and to make the same labels (.txt) with the same name as the pictures.

thanks!

### Additional

I think it will be great if you will add explanation about it in the tutorial for training custom data. thanks!

**Comment by glenn-jocher** [comment]
@RoyCopter no, nothing like this is required. Order does not matter.

**Comment by RoyCopter** [comment]
> @RoyCopter no, nothing like this is required. Order does not matter.

thanks! one more question, If I want to add background images (to deal with the false-positive cases), you recommended in another posts about 1%-10% background images (and we not need to create the label.txt for them).

but my question is, should I add the background images to the training data or the val data or both? and if to both, how much to each one? 
@glenn-jocher

**Comment by glenn-jocher** [comment]
@RoyCopter both ideally. train to train on them and val to verify your models performance on them.
