### ISSUE TITLE
What will happen if I want to train a dataset with fewer classes?

### ISSUE THREAD

**Issue by RoyCopter** [ultralytics/yolov5#6993]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hey,

I want to train VisDrone dataset with only 3-4 classes. Although the labels of the images contains all the classes, is it possible to train the model with only 3-4 classes without touching the original labeling files?

**Comment by glenn-jocher** [comment]
@RoyCopter yes, you can filter classes here. Just add the class indices you want to train. All others will be ignored.
https://github.com/ultralytics/yolov5/blob/c09fb2aa95b6ca86c460aa106e2308805649feb9/utils/datasets.py#L451

**Comment by RoyCopter** [comment]
> 
@glenn-jocher 
With the new version, how can I do that again? (you removed the datasets.py)

**Comment by glenn-jocher** [comment]
@RoyCopter datasets.py renamed to dataloaders.py
