### ISSUE TITLE
Can this project be ported to cpp and used commercially?

### ISSUE THREAD

**Issue by leeyunhome** [ultralytics/yolov5#6997]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,

thank you so much for sharing a good project
Can this project be ported to cpp and used commercially?

Thank you.

**Comment by finestnothing** [comment]
Hi leeyunhome, I'm not a maintainer of this project, just a user, but the license is a GNU public license. According to the license file (linked below), it is authorized freely for:
 Commercial use
 Modification
 Distribution
 Patent use
 Private use
So you can essentially use it however you want, just be aware that the project itself comes with no warranty or liability on the part of ultralytics. Essentially you can use the code for anything, but if anything goes wrong, it's not the responsibility of the repo owners/maintainers. 

If you need any specific information, the following license file should be able to help you out.
[https://github.com/ultralytics/yolov5/blob/master/LICENSE](https://github.com/ultralytics/yolov5/blob/master/LICENSE)

Hope this helps!
