### ISSUE TITLE
How to see the detection result only without the detection window?

### ISSUE THREAD

**Issue by PIjarihd** [ultralytics/yolov5#6999]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to make the detection window unvisible. Only the detection results in the command prompt are fine. How should I make that?

**Comment by glenn-jocher** [comment]
@PIjarihd I don't know what 'detection window' you are talking about.

**Comment by blackShine-2** [comment]
> @PIjarihd I don't know what 'detection window' you are talking about.
This window (or video frame). I want it to be hidden. 
![image](https://user-images.githubusercontent.com/95059200/158713368-f58b213c-6b2d-4a82-ab90-ee7a6ede7967.png)
I want the results only in the command prompt (like this and it is already there).
![image](https://user-images.githubusercontent.com/95059200/158713470-133d0f9d-430b-4619-bf6b-703aaa994bab.png)

Can you please help me, how can I hide the video frame window (detection window)?

**Comment by Guttappa1238** [comment]
Hi @PIjarihd, If you dont need detection window just comment out these line in `detect.py` 

```
            if view_img:
                cv2.imshow(str(p), im0)
                cv2.waitKey(1)  # 1 millisecond
```

**Comment by PIjarihd** [comment]
> Hi @PIjarihd, If you dont need detection window just comment out these line in `detect.py`
> 
> ```
>             if view_img:
>                 cv2.imshow(str(p), im0)
>                 cv2.waitKey(1)  # 1 millisecond
> ```

Thank you. That works.
