### ISSUE TITLE
How to remove labels and confidence score from .pt weight file while using torch.hub.load?

### ISSUE THREAD

**Issue by mansi733** [ultralytics/yolov5#7000]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to remove labels and confidence score from .pt weight file while using torch.hub.load? 
Need to plot the bounding box only in the predictions.

**Comment by dhirajneupane** [comment]
Make `defualt = True`  in the below line to hide labels
https://github.com/ultralytics/yolov5/blob/c09fb2aa95b6ca86c460aa106e2308805649feb9/detect.py#L235

Make `default = True` in the below line to hide confidence
https://github.com/ultralytics/yolov5/blob/c09fb2aa95b6ca86c460aa106e2308805649feb9/detect.py#L236

**Comment by mansi733** [comment]
Thanks! I have already tried this solution but I want to hide the labels and confidence score before generating .pt file so that when I load the model using torch.hub.load it will generate output predictions without the labels and confidence score.
