### ISSUE TITLE
hyperparameter evolution on a small dataset

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#7001]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am using YOLOv5s for my thesis. One of the challenges in my thesis is using a very small train set consisting of 119 images and roughly 1500 objects with 5 different classes. I tried hyperparameter evolution using different epoch settings and the "best" result i got was using the recommended setting of 10 epochs. I unfortunately did not document the settings fully and thus I am uncertain how large the batch size was. In the worst case it might have been 1.

I execute a 16 x 16 grid search to find the optimal conf thres and iou thres combination. Then I use those thresholds to evaluate the models. Using bootstrapping the F1 score of the model trained with tuned hyperparameters performs worse than the stock hyperparameters for finetuning with a certainty of 99.995 % a.k.a. it performed worse.
![hypev](https://user-images.githubusercontent.com/30004387/158535991-ca472741-32ad-4730-896d-4cfba7f10614.png)

Did I likely do something wrong or is this typical with such a small dataset? I am aware that at least 1500 images per class and 10000 instances per class are recommended for YOLOv5.

P.S. Is there a way of calculating a confidence interval of the F1 score or bootstrapping the F1 score distribution natively using YOLOv5? This should be best practice imho because a point estimate from a sample (unfortunately most common in literature) has very little meaning for the population. A point estimate also can't be used for hypothesis tests.

**Comment by glenn-jocher** [comment]
@Lumcoin hyperparameter evolution optimizes hyps to a specific base scenario (that you specify) and nothing else. Using the optimized hyps for a different scenario is on you.

See hyp evolution tutorial for details:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TFLite, ONNX, CoreML, TensorRT Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

Good luck 🍀 and let us know if you have any other questions!

**Comment by myasser63** [comment]
@Lumcoin I am doing similar project for my thesis and even smaller dataset. Can you tell me the way you did grid search or you used the hyperparameter evolution by yolov5

**Comment by MattGrouchy** [comment]
@Lumcoin 

Has there been any developments in your findings with hyperparameter evolution?
