### ISSUE TITLE
Tensorrt model size (best.engine) bigger than pytorch model (best.pt) 

### ISSUE THREAD

**Issue by HANK538** [ultralytics/yolov5#7004]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello

Thanks for the hard work.
I have a simple question, after transfer to tensorrt engine.
The file size larger than pt file. (31mb > 14 mb)
Is that normal ?  Although I test it really become faster.
I just want to make sense and reply to professor properly.

Appreciate!

**Comment by glenn-jocher** [comment]
@HANK538 your code is out of date. TRT models default to FP16 export now, same as PyTorch model quantization.

To update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

**Comment by HANK538** [comment]
Hi

After git clone again and export, the situation is still the same.

yolov5 s 14mb  export .engine 32mb

my command line
pyhton export.py --weights runs/train/exp/weights/best.pt --device 0 --include engine

Furthermore, it also output a onnx file with engine model.
This onnx file seems can not run for inference purpose.
You need to export --include onnx again for onnx inference.

Is my understanding correct ?

Please help to guide.
Thanks.

**Comment by glenn-jocher** [comment]
@HANK538 the team is extremely busy, please don't spend our time on non-reproducible issues:

<img width="1523" alt="Screenshot 2022-03-17 at 12 47 05" src="https://user-images.githubusercontent.com/26833433/158802294-ad755291-e99e-4e38-860d-79aa804d937c.png">

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
