### ISSUE TITLE
How to increase the image size limit in yolov5? error: Image size exceeds limit of 178956970 pixels!

### ISSUE THREAD

**Issue by safal-305** [ultralytics/yolov5#7005]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hi. i have some panaromic 360 degree images  and i had annotated it for object detection. but when im trying to train the images , it shows the following error
WARNING: C:\Users\K\yolov5\data\images\blur\images\train\GCC9.jpeg: ignoring corrupt image/label: Image size (324768098 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.

how to mitigate this missue?

**Comment by glenn-jocher** [comment]
@safal-305 your jpeg has issues that are unrelated to YOLOv5. Before training it make sure that you can load it with cv2.imread('im.jpg').

**Comment by safal-305** [comment]
Thank You. The problem appears to be with the image dimensions.(25486 x 12743), and opencv as well as pil was unable to read the image.

**Comment by glenn-jocher** [comment]
@safal-305 oh I see. You might try numpy loading and if that works customize the dataloader.
