### ISSUE TITLE
ONNX inference square input

### ISSUE THREAD

**Issue by emanef13** [ultralytics/yolov5#7006]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,
Is it the case that when doing inference with onnx model the input shape of the image must be squared? And if yes why is that the case?

Thank you!

**Comment by glenn-jocher** [comment]
@emanef13 you specify your own inference shape:
```
python export.py --include onnx --img 640 640
```
