### ISSUE TITLE
Strange train_batch*.jpg Image

### ISSUE THREAD

**Issue by atapley** [ultralytics/yolov5#701]
![train_batch0](https://user-images.githubusercontent.com/23152013/89822586-43219e80-db1e-11ea-8978-c48ee8abbbbb.jpg)

After my first epoch of training, I am met with this image in my batch0.jpg. I am running with --image 640 and --rect, while my images are either 2560x1440 or 640x480. I am not sure why I am only getting two images in these batch*.jpg images as opposed to the 4 I was expecting.

When running without --rect (so with mosaic) I get this image.

![train_batch0 (1)](https://user-images.githubusercontent.com/23152013/89823214-1a4dd900-db1f-11ea-9a8c-ac9d0b2c7c27.jpg)

Could it be due to the fact that I am training with different sized images than specified with my --image flag? Either way, shouldn't I still be getting four images in this output jpg? I'm unusre as to what all the extra white space on the side is for.

**Comment by glenn-jocher** [comment]
@atapley your batch size or your dataset size is 2.
