### ISSUE TITLE
Tensorrt wrong classes with custom pretrained model

### ISSUE THREAD

**Issue by RoyCopter** [ultralytics/yolov5#7018]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

Hey, I am using Tensorrt with pretrained weights on the VisDrone dataset with the next command:
`
python3 export.py --weights best.pt --include engine --imgsz 384 640 --device 0 --half  # export
`

Because the VisDrone dataset has a different name classes and number classes instead of bus and car I get motorcycle and etc.

How can I fix that?

**Comment by glenn-jocher** [comment]
@RoyCopter this isn't a bug. You haven't passed your --data yaml so names from the default value are used:
https://github.com/ultralytics/yolov5/blob/3f634d43c8ecea14aa9037e2fd28ded0433d491d/detect.py#L215

**Comment by RoyCopter** [comment]
> 

Thanks! you are the king! @glenn-jocher

**Comment by glenn-jocher** [comment]
@RoyCopter some models automatically do this because we can attach metadata to them (*.pt, *.torchscript) but with TRT I don't think we can attach the names.
