### ISSUE TITLE
YOLOv5 deployment to AWS sagemaker

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#7019]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello everybody, I've trained yolov5 to detect a custom object, now I have to deploy it on AWS sagemaker, for that I need to create an endpoint for inference, I've seen some tutorials on how to create endpoints on AWS but I don't know how to do it for yolov5 , can someone help me please ?

**Comment by glenn-jocher** [comment]
@sinatimelapse haven't used sagemaker myself. See https://github.com/ultralytics/yolov5/issues/6502 for related request.

**Comment by ghost** [comment]
@glenn-jocher Thank you for your response, I've juste read the discussion, it seems interesting but there's no concrete solution.

**Comment by glenn-jocher** [comment]
@sinatimelapse yes no concrete solution yet. I've reached out to a new team at AWS again today, will post updates here.

**Comment by ghost** [comment]
Ok, thank you very much, I'm looking forward to reading the updates

**Comment by sbhavani** [comment]
@sinatimelapse https://github.com/sbhavani/yolov5-sagemaker-inference/ let me know if this helps. I'll create an official repo example shortly.

**Comment by ghost** [comment]
@sbhavani Thank you very much for your answer, I tested this repo, the endpoint is created, and the inference is done, but when I check the results I get strange values like [[[[[-0.040722042322158813, -0.05041172727942467, -0.12405179440975189, -0.2721632421016693, -10.471428871154785, -0.9401314854621887, -5.573054313659668, -3.5167489051818848, -5.933956146240234, -6.579037189483643, -6.703894138336182, -6.8030548095703125,... 
I think there's a problem with code/inference.py, I tried to modify input_fn and output_fn functions, but I'm juste getting errors, I don't know exactly what I should do !

**Comment by glenn-jocher** [comment]
@sinatimelapse @sbhavani alright guys I'm on this. I travelled from Madrid, Spain to the AWS summit in San Francisco this week, and I'm meeting in person with their Marketplace and Sagemaker teams to get YOLOv5 officially represented and launched on both.

This must be the most personalized service ever for an open-source AI 😂. 

![IMG_1680](https://user-images.githubusercontent.com/26833433/164561360-11472654-b211-4c60-a3a3-4784a53e1b94.jpg)

**Comment by Vijay-P1999** [comment]
@glenn-jocher Very eagerly waiting to hear the updates.

**Comment by Willert98** [comment]
this ref will help us deploy yolov5 on amazon sagemaker,I just successfully deployed
ref：https://sagemaker.readthedocs.io/en/stable/frameworks/pytorch/using_pytorch.html#bring-your-own-model

**Comment by ztyree42** [comment]
> this ref will help us deploy yolov5 on amazon sagemaker,I just successfully deployed ref：https://sagemaker.readthedocs.io/en/stable/frameworks/pytorch/using_pytorch.html#bring-your-own-model

I understand the title of this issue is "deployment" but I hope to be able to actually train yolov5 on sagemaker which would require a training script in addition to an inference script if we take the BYOM approach. In my opinion the training script is going to require more work than the inference script given that for this to be worthwhile for most users the training data will need to be in S3.

Another option is the Bring Your Own Container approach (https://docs.aws.amazon.com/sagemaker/latest/dg/studio-byoi.html) which might be less work?

The best option is that aws supports yolov5 as a first class citizen and there's just a yolov5 model class coming down the pipeline I guess

**Comment by Vijay-P1999** [comment]
> this ref will help us deploy yolov5 on amazon sagemaker,I just successfully deployed ref：https://sagemaker.readthedocs.io/en/stable/frameworks/pytorch/using_pytorch.html#bring-your-own-model

@Willert98 
How did you invoke the endpoint?? I tried all options, i couldn't invoke it to make predictions. 

This is my inference script : 
```
def model_fn(model_dir):
    print("LOADING MODEL....")
    model=common.DetectMultiBackend()
    tar = tarfile.open(model_dir, "r:gz")
    for member in tar.getmembers():
        print(member)
        f = tar.extractfile(member)
        model=model.load_state_dict(torch.load(f),map_location=device)
    model.to(device)
    return model


def input_fn(serialized_input_data, content_type):
    if content_type == 'application/json':
        print(f'input_fn - serialized_input_data: {serialized_input_data}')
        input_data = json.loads(serialized_input_data)
        return input_data
    else:
        raise Exception('Requested unsupported ContentType in Accept: ' + content_type)
        return


def predict_fn(input_data, model):
    print(f'predict_fn - input_data: {input_data}')
    imgs = [input_data]
    results = model(imgs)
    df = results.pandas().xyxy[0]
    return(df.to_json(orient="split"))
```

Do you find something wrong?

**Comment by ianhco** [comment]
@glenn-jocher Any updates on this ? we would like to test out yolov5 on sagemaker as we scale. I think there is demand.

**Comment by glenn-jocher** [comment]
@paaksing please reach out to the sagemaker team with your request. I've had trouble getting a response from them myself regarding YOLOv5 integration.

**Comment by 5starkarma** [comment]
Hey y'all! Seems the team over at AWS has put this out. Great way to deploy models.

https://aws.amazon.com/blogs/machine-learning/scale-yolov5-inference-with-amazon-sagemaker-endpoints-and-aws-lambda/

**Comment by navidroo** [comment]
> Hey y'all! Seems the team over at AWS has put this out. Great way to deploy models.
> 
> https://aws.amazon.com/blogs/machine-learning/scale-yolov5-inference-with-amazon-sagemaker-endpoints-and-aws-lambda/

I tried to use this approach. There is part where it says:

This command creates a new directory called yolov5l_saved_model inside the yolov5 directory. Inside the yolov5l_saved_model directory, we should see the following items:

yolov5l_saved_model
    ├─ assets
    ├─ variables
    │    ├── variables.data-00000-of-00001
    │    └── variables.index
    └── saved_model.pb
    
    
  However, the bash code was not able to recreate the directory and only returned a 'yolov5l.pt' file. I am not even sure about '.pb' file. Is it a typo? were you able to deploy the model to the endpoint?

**Comment by glenn-jocher** [comment]
@navidroo thanks for sharing your experience with the AWS solution. It seems there might be an issue with the directory creation and file generation when following their documentation. To clarify, the '.pb' file is typically associated with TensorFlow models, not PyTorch. However, it's best to reach out to AWS support for assistance, or consider seeking help from the YOLOv5 community. Good luck with the deployment!
