### ISSUE TITLE
Different results when using torch tensor and image path

### ISSUE THREAD

**Issue by MrEarle** [ultralytics/yolov5#7030]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection, PyTorch Hub

### Bug

I have an image in png form. I also have that same image as a tensor (obtained as shown in #36 ).

The problem is that, when I use a tensor as an input, the result is nonsensical, outputting a tensor with a shape of `[18900, 85]`. I suppose one of those dimensions should be 6, for the xyxy confidence and class id.

On the other hand, if I use the path to the image as an input, I get what I would expect.

Both of these cases are shown in the image below:

![image](https://user-images.githubusercontent.com/30664457/158912729-e7833e8c-1ab6-4858-859a-de0563cedb35.png)

### Environment

- YOLOv5 🚀 2022-3-17 torch 1.9.1+cu102 CUDA:0 (NVIDIA GeForce GTX 1080 Ti, 11178MiB)
- OS: Ubuntu 18.04
- Python: 3.6.8

### Minimal Reproducible Example

```py
import torch
from PIL import Image

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5m')

img = Image.open('path_to_image').resize((640, 480), Image.ANTIALIAS).convert('RGB')
img = torch.tensor(np.array(img)).permute((2, 0, 1)).unsqueeze(0).float() / 255
result = model(img)
print(result.shape)

result = model('path_to_image')
print(result.xyxyn)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by MrEarle** [comment]
Update: I just tried it with python >= 3.7.0 and still have the same problem.

Environment:

- YOLOv5 🚀 2022-3-17 torch 1.11.0+cu102 CUDA:0 (NVIDIA GeForce GTX 1080 Ti, 11178MiB)
- Python 3.7.3
- OS: Ubuntu 18.04 LTS


Edit: I also tried using numpy, and I get a completely different result. Using numpy gives no detections on the same data as the used tensor.

![image](https://user-images.githubusercontent.com/30664457/159032674-6daf3fbf-485e-4dd7-bbac-8ac8e91a9d0c.png)

**Comment by glenn-jocher** [comment]
@MrEarle 👋 Hello! Thanks for asking about **handling inference results**. Your workflow is way overly complicated, none of your custom code is needed, just follow example below and pass im.png straight to your model.

YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, etc.
# model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')  # custom trained model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by MrEarle** [comment]
I understand that I can use the path to the image.

The thing is that I don't have images saved on disk (or online). I'm using a simulator to get images, and I get a bumpy array as images.

I need to process thousands of images, so saving them to disk and then loading them for inference is not really useful for me.

**Comment by glenn-jocher** [comment]
@MrEarle as the above example shows you can pass your numpy arrays directly to the model.

**Comment by MrEarle** [comment]
Yes, but I get different results. Unlike the example shown on the issue I
linked.

Saludos!
Benjamin

**Comment by glenn-jocher** [comment]
@MrEarle see [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

**Comment by MrEarle** [comment]
> @MrEarle see [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Yes. The code I included in this issue is a replica of the code shown there. That's why I made this issue. I'm doing the same thing, but with a different image, and I get that nonsensical result.

I'm not getting the bounding boxes, confidence and class as I should. I get this (18900 x 85) dimensional tensor.

**Comment by glenn-jocher** [comment]
@MrEarle don't pass a tensor. Pass anything else from the example. Tensors are for training only.

**Comment by valentin-fngr** [comment]
> @MrEarle don't pass a tensor. Pass anything else from the example. Tensors are for training only.

Interesting, is there a particular reason why we should not use torch tensors during inference ? 
Won't I want to convert my image as a tensor and send it to the GPU to speed up inference ? (this is a noob question)
Thanks

**Comment by valentin-fngr** [comment]
> > @MrEarle don't pass a tensor. Pass anything else from the example. Tensors are for training only.
> 
> Interesting, is there a particular reason why we should not use torch tensors during inference ? Won't I want to convert my image as a tensor and send it to the GPU to speed up inference ? (this is a noob question) Thanks

I have found this answer here : https://github.com/ultralytics/yolov5/issues/2722

**Comment by glenn-jocher** [comment]
@valentin-fngr The post you found in the discussion confirms that tensors are used during training only. During inference, you can pass images directly as opposed to using tensors. The example provided in the documentation on PyTorch Hub model loading provides an easy way of how you can use your numpy array images without the need to save them on disk. These numpy arrays can be passed directly to the tensorflow model without being converted to GPU tensors and you should get the expected results without issues.

**Comment by rahmanole** [comment]
> ```python
> xyxy[0]
> ```

please read the post and then reply.

**Comment by hoxnocha** [comment]
@glenn-jocher , may i ask a question. Since my dataloader only returns tensor describe a batch of images with shape BCHW, how could I use yolov5 to detect the object i need for further training? Should I convert this tensor to some other format.

**Comment by glenn-jocher** [comment]
@hoxnocha You can convert your tensor batch of images to numpy arrays using `tensor.numpy()`, and then pass these numpy arrays to the YOLOv5 model for inference as shown in the provided example. This way, you can use your dataloader to prepare your data for training and then convert the tensor outputs to numpy arrays for inference.
