### ISSUE TITLE
Inconsistent model output format after PR #6292

### ISSUE THREAD

**Issue by MrinalJain17** [ultralytics/yolov5#7031]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Export

### Bug

Based on this return statement in `TFModel`, the output of a TF saved_model was/should be a tensor. https://github.com/ultralytics/yolov5/blob/master/models/tf.py#L368

However, after the changes introduced in #6292, the TF saved_model **returns the said tensor wrapped in a list**.

1. This breaks compatibility across TF saved_models exported before and after the change.
2. Moreover, the output of a saved model is either a tensor (if `keras=True`) or the tensor wrapped in a list `keras=False` (now default).

### Environment

YOLOv5 Latest
OS: Ubuntu, Windows
Python: 3.9
TensorFlow: 2.7

### Additional

#7032 attempts to solve all these issues.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@MrinalJain17 thanks for the PR! I will take a look there.
