### ISSUE TITLE
TensorFlow SavedModel: export failure: name 'TFDWConv' is not defined

### ISSUE THREAD

**Issue by abhishekhingne** [ultralytics/yolov5#7033]
Hi, I am trying to convert custom yolo model (in which I replaced regular Conv blocks with Depthwise Conv blocks) to tensorflow but I am getting following error:
TensorFlow SavedModel: export failure: name 'TFDWConv' is not defined

TensorFlow GraphDef: starting export with tensorflow 2.7.0...

TensorFlow GraphDef: export failure: 'NoneType' object has no attribute 'inputs'

I am using tensorflow=2.7.0 and tensflowjs=3.14 version and tried with latest yolo code.

Can you please help to fix this issue?

**Comment by glenn-jocher** [comment]
@abhishekhingne TF models need to be built from scratch using TF modules that replicate the PyTorch modules in common.py. If you are using DWConv():
https://github.com/ultralytics/yolov5/blob/7c6a33564a84a0e78ec19da66ea6016d51c32e0a/models/common.py#L53-L57

then you need to create a corresponding TFDWConv() in [tf.py](https://github.com/ultralytics/yolov5/blob/master/models/tf.py). The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
