### ISSUE TITLE
How to render only bounding box

### ISSUE THREAD

**Issue by YogiDwiAndrian** [ultralytics/yolov5#7035]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

`results.render()` how to display or render image from torch.hub without name class and confidance score, only bounding box?

Thanks

**Comment by glenn-jocher** [comment]
@YogiDwiAndrian hi, thank you for your feature suggestion on how to improve YOLOv5 🚀! You can modify the Detections() class to accept new arguments for this here:
https://github.com/ultralytics/yolov5/blob/4effd064b169fc049b4a4bca401b120bf2e93c14/models/common.py#L573-L672

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by YogiDwiAndrian** [comment]
thanks for the solution.
