### ISSUE TITLE
about training single channel images

### ISSUE THREAD

**Issue by mzzjuve** [ultralytics/yolov5#7040]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have trained my single channel image dataset  using Unmodified YOLOV5 ，and the training is working.

I want to know the mechanism of yoloV5 for single channel image input，does it triple the single-channel input into a three-channel input?
Thank you for your  excellent work and look forward to your reply！

**Comment by glenn-jocher** [comment]
@mzzjuve yes single channel images are automatically expanded to 3 channel images by the dataloaders. This allows combinations of BW and RGB datasets to train, like COCO.

**Comment by mzzjuve** [comment]
> @mzzjuve yes single channel images are automatically expanded to 3 channel images by the dataloaders. This allows combinations of BW and RGB datasets to train, like COCO.

Thank you for your timely reply. I am glad that my guess is correct, which is of great help to me

**Comment by mzzjuve** [comment]
> @mzzjuve yes single channel images are automatically expanded to 3 channel images by the dataloaders. This allows combinations of BW and RGB datasets to train, like COCO.

I noticed that this was a waste of resources for my single-channel input. In order to speed up the training, I want to change the input channel of the first CONV layer to single channel, but I don't know how to change it, because the input channel is hidden in the .yaml file, may I ask what I should do specifically?
Thank you very much！

**Comment by blingblinstar** [comment]
Have you solve this problem? i want to change the input channel too.

**Comment by mzzjuve** [comment]
> Have you solve this problem? i want to change the input channel too.

sorry,reducing costs was not the focus of my research, and I stopped looking at it

**Comment by glenn-jocher** [comment]
@mzzjuve got it! To modify the input channel of the first CONV layer, you can directly change the `nc` (number of classes) parameter in your YAML file located in `yolov5/models/`. Set `nc` as 1 for single-channel input. Let me know if you need further assistance!
