### ISSUE TITLE
Modify postprocess (NMS) when using model loaded from torch.hub.load?

### ISSUE THREAD

**Issue by rusvagzur** [ultralytics/yolov5#7041]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

So I know this is possible when using the detect.py, similar to #6725 

However, for simplicity I would like to modify the postprocessing, especifically the NMS, when I load the model using `model = torch.hub.load('ultralytics/yolov5', 'yolov5x')
`
Any ideas for this?

**Comment by glenn-jocher** [comment]
@rusvagzur 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. You can point PyTorch Hub to a local repo that has any customizations you want. See [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) tutorial for details.

**Comment by rusvagzur** [comment]
Many thanks @glenn-jocher your answer is on point.
