### ISSUE TITLE
How can I  use image as input for inference?

### ISSUE THREAD

**Issue by GivanTsai** [ultralytics/yolov5#7044]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I see that the `detect.py` script can use xxx.jpg or data folder as source input, if my image has read using opencv or PIL，How can I use this type of input?
`image = cv.imread('image.jpg')`
![image](https://user-images.githubusercontent.com/37231239/159112393-497b0c3a-0d45-4d68-9eda-f14c6ad2ef37.png)

**Comment by glenn-jocher** [comment]
@GivanTsai 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, etc.
# model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')  # custom trained model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by GivanTsai** [comment]
> @GivanTsai 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`.
> 
> ### Simple Inference Example
> This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.
> 
> ```python
> import torch
> 
> # Model
> model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, etc.
> # model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')  # custom trained model
> 
> # Images
> im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list
> 
> # Inference
> results = model(im)
> 
> # Results
> results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
> 
> results.xyxy[0]  # im predictions (tensor)
> results.pandas().xyxy[0]  # im predictions (pandas)
> #      xmin    ymin    xmax   ymax  confidence  class    name
> # 0  749.50   43.50  1148.0  704.5    0.874023      0  person
> # 2  114.75  195.75  1095.0  708.0    0.624512      0  person
> # 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
> ```
> 
> <img alt="" width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">
> 
> See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.
> 
> Good luck 🍀 and let us know if you have any other questions!

@glenn-jocher Thanks for your detailed answer. The question is that I have modified the custom yolov5 model, maybe I can load the model from torch hub as you suggusted.

**Comment by glenn-jocher** [comment]
@GivanTsai yes, my example above shows usage example for loading a custom trained model.

**Comment by GivanTsai** [comment]
> @GivanTsai yes, my example above shows usage example for loading a custom trained model.

Sorry, there is a typo. I mean I have changed the structure of model, so I can not load the model from torch hub directly. How can I deal with this kind of situation.

**Comment by glenn-jocher** [comment]
@GivanTsai 
```python
model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')  # custom trained model
```

**Comment by GivanTsai** [comment]
> @GivanTsai yes, my example above shows usage example for loading a custom trained model.

@glenn-jocher I want to load a model with custom structure, because I have changed some layers of yolov5, not just custom trained weight. How can I do?

**Comment by glenn-jocher** [comment]
@GivanTsai you can train a custom yaml with `python train.py --cfg model.yaml`

**Comment by GivanTsai** [comment]
> @GivanTsai you can train a custom yaml with `python train.py --cfg model.yaml`

Yes, I have finished the training stage. Now I want to do inference using `pred=model(img)` not `python detect.py`. Using image of ndarray type or PIL.Image type as input for inference.

**Comment by glenn-jocher** [comment]
> @GivanTsai
> 
> ```python
> model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')  # custom trained model
> ```

I've already pointed you to how load and run inference with custom trained models several times.
