### ISSUE TITLE
How to solve this problem

### ISSUE THREAD

**Issue by theyoungghost** [ultralytics/yolov5#7045]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Traceback (most recent call last):
  File "train.py", line 643, in <module>
    main(opt)
  File "train.py", line 539, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 124, in train
    model = Model(cfg or ckpt['model'].yaml, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)  # create
  File "/home/lgr123/1HYS/YOLO/yolov5/models/yolo.py", line 103, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=[ch])  # model, savelist
  File "/home/lgr123/1HYS/YOLO/yolov5/models/yolo.py", line 245, in parse_model
    anchors, nc, gd, gw = d['anchors'], d['nc'], d['depth_multiple'], d['width_multiple']
KeyError: 'anchors'
![image](https://user-images.githubusercontent.com/95341128/159116954-98541ee3-5891-4ed5-9e5e-63d6b9bcd908.png)

**Comment by glenn-jocher** [comment]
@theyoungghost your --cfg yaml is incorrectly configured and is missing an anchors field.

**Comment by theyoungghost** [comment]
Thanks！

**Comment by fa00fa** [comment]
> @theyoungghost your --cfg yaml is incorrectly configured and is missing an anchors field.

please tell me how to add this anchors field?

**Comment by fa00fa** [comment]
> @theyoungghost your --cfg yaml is incorrectly configured and is missing an anchors field.

please tell me how to add this anchors field?

**Comment by glenn-jocher** [comment]
@fa00fa just look at the official models

**Comment by tuanlh2k2** [comment]
how to fix bug, please? Given groups=1, weight of size [32, 3, 6, 6], expected input[1, 640, 640, 3] to have 3 channels, but got 640 channels instead
Thanks

**Comment by glenn-jocher** [comment]
@tuanlh2k2 This issue occurs when the output shape of a network does not match the input shape of the subsequent network. A possible cause may be incorrect input shape settings or dimension mismatch in your image dataset. 

- Check your training images have the correct number of channels, which should be consistent with your `--channels` training argument that should be set to three.
- Verify your training command and make sure you have defined the input `--img_size` to match that of the loaded images in your dataset.
 - `defaults.yaml` specifies a shape of `640` so if you want to use that shape, specify `--img-size 640` in your train command.

Please review these settings and try again. Let us know if the issue still persists.
