### ISSUE TITLE
Converting custom dataset best.pt to tflite issue

### ISSUE THREAD

**Issue by HunarAA** [ultralytics/yolov5#7046]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am using this command "python export.py --weights runs\train\exp\weights\best.pt --img 640 --include tflite" to convert the best.pt to tflite and the conversion works just fine. But when I detect the "best-fp16.tflite" with my webcam, every class that I try in my dataset, it recognizes it as cars, motorcycles, trucks while my dataset is completely different and the "best.pt" can recognize every class of my dataset. Is this an issue or whatever?

**Comment by glenn-jocher** [comment]
@HunarAA TFLite models do not carry metadata like class names, you must supply them separately. If you are using detect.py you can pass your --data yaml for this purpose and then it will use your custom class names. Default is to use COCO class names:
https://github.com/ultralytics/yolov5/blob/4effd064b169fc049b4a4bca401b120bf2e93c14/detect.py#L215

**Comment by HunarAA** [comment]
I have put my dataset.yaml which I used for training in data folder and replaced the 'data/coco128.yaml' with 'data/dataset.yaml'. It worked just fine. Thanks.
