### ISSUE TITLE
Low Map0.5 and Map0.5:0.95 results

### ISSUE THREAD

**Issue by vvision0** [ultralytics/yolov5#7051]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

My VOC results is **0.824 Map0.5** and **0.579 Map0.5:0.95** on Windows 11.
The Command is followed:
**python train.py --data VOC.yaml --weights yolov5s.pt --img 640 --epoch 200 --batch-size 128 --device 5 --cfg yolov5s.yaml**
The reason of 200 epochs is that i tried 300 before and the model overfitted after 220 epoch, in that case the map is even lower, the Map0.5 is about 0.818 and Map0.5:0.95 is about 0.570.

Then i tried COLAB, with nothing change.The only thing to be noticed is that the training was completed with five steps because the COLAB would break if you do nothing for a while. So I have to continue the last epoch for five times.
The Command is followed:
**python train.py --data VOC.yaml --weights /content/drive/MyDrive/exp4/weights/last.pt --img 640 --epoch 250 --batch-size 72 --cfg yolov5s.yaml --save-period 20 --project /content/drive/MyDrive**
This time the result is **0.832 Map0.5** and **0.589 Map0.5:0.95**, this result is the best result, the model overfitted and the map was dropped within 250 epoch.

I don't know where the problem occurs, maybe different system cause different results, but i can't reach the official 0.86 Map0.5 so far.

**Comment by glenn-jocher** [comment]
@vvision0 VOC training examples are shown in the Colab [notebook](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb#scrollTo=BSgFCAcMbk1R&line=1&uniqifier=1) Appendix section. 50 epochs from pretrained weights:

```python
# VOC
for b, m in zip([64, 64, 32, 16], ['yolov5s', 'yolov5m', 'yolov5l', 'yolov5x']):  # zip(batch_size, model)
  !python train.py --batch {b} --weights {m}.pt --data VOC.yaml --epochs 50 --cache --img 512 --nosave --hyp hyp.VOC.yaml --project VOC --name {m}
```

**Comment by vvision0** [comment]
Thank you for your indication, I did't see it......  I will try it.

**Comment by JimmyW-11** [comment]
@glenn-jocher hi,thanks for your great job. I am training for VOC dataset and there are some questions. The img-size of training is  512 or 640 for better? And when i use yolov5s-ghost.yaml for training, i find that the map is less than yolov5s.yaml a lot(10%) , but your result is about 2% less than the original model. And other arguments when training  is same.

**Comment by glenn-jocher** [comment]
@JimmyW-11 for official VOC training results see 
https://wandb.ai/glenn-jocher/YOLOv5_VOC_official

Commands to reproduce:
```python
# VOC
for b, m in zip([64, 64, 32, 16], ['yolov5s', 'yolov5m', 'yolov5l', 'yolov5x']):  # zip(batch_size, model)
  !python train.py --batch {b} --weights {m}.pt --data VOC.yaml --epochs 50 --cache --img 512 --hyp hyp.VOC.yaml --project VOC --name {m}
```
