### ISSUE TITLE
why can't I reproduce the mAP provided by README.md（v6.1）？

### ISSUE THREAD

**Issue by wangtao0219** [ultralytics/yolov5#7072]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I used the method recommended by README.md(v6.1) to reproduce the mAP, but I failed. 
'python train.py --data coco.yaml --cfg yolov5s.yaml --weights ' ' --hyp hyp.scratch-low.yaml --img 640 --batch-size 64 --epochs 300' .
All is default value,then I got the best mAP（yolov5s） is 37.057%(the best mAP verified at the end of each epoch, 5000 images), it still has a gap of 0.4% mAP(37.4%). 
Similarly, I reproduced the mAP（yolov5n），27.586%----28.0%，Never get published results.
My GPU is GTX NVIDIA RTX A4000（16116MiB）, and I think it may be enough.

Is this a normal error caused by equipment（GPU) differences, or are there other reasons？

**Comment by glenn-jocher** [comment]
@wangtao0219 all official v6.1 model trainings are logged here, including training commands and results.
https://wandb.ai/glenn-jocher/YOLOv5_v61_official

<img width="1521" alt="Screenshot 2022-03-21 at 08 46 14" src="https://user-images.githubusercontent.com/26833433/159221422-30de0616-cccc-4c31-adf0-c66c49e62579.png">

Note that these are trained with COCO with segmentation labels which help bounding box augmentation. You can get these labels by uncommenting this line in the download script:
https://github.com/ultralytics/yolov5/blob/9cd89b75cca8bb165a3b19c9b8356f7b3bb22b31/data/scripts/get_coco.sh#L13

**Comment by wangtao0219** [comment]
@glenn-jocher Thank you for your prompt attention，but I have another doubt。
Command is  ‘train.py  --data coco.yaml --batch 128 --weights --cfg yolov5n.yaml --epochs 300 --project YOLOv5_v61_official --name YOLOv5n-linear --img 640 --hyp hyp.scratch-low.yaml --device 0 --linear ’
But I didn't find  -- linear（v6.1）,   Only found  --cos-lr  ，Should it be replaced？

**Comment by glenn-jocher** [comment]
@wangtao0219 --linear is the new default, it's not needed anymore.

**Comment by wangtao0219** [comment]
@glenn-jocher  The reproduced result is still slightly different from the original, I am trying to find the reason for the difference.
readme:                    
python train.py --data coco.yaml --cfg yolov5n.yaml --weights '' --batch-size 128
                                                            yolov5s                                                 64
                                                            yolov5m                                                40
                                                            yolov5l                                                  24
                                                            yolov5x                                                 16
https://wandb.ai/glenn-jocher/YOLOv5_v61_official:  
python train.py --data coco.yaml --cfg yolov5n.yaml --weights '' --batch-size 128
                                                             yolov5s                                               128 
                                                             yolov5m                                              128
                                                             yolov5l                                                 128
                                                             yolov5x                                                128
all official v6.1 model trainings are logged here, but all batches are set to 128. My GPU is GTX NVIDIA RTX A4000（16G）,this cannot be set during training.

What should I do to ensure that the training conditions are basically the same？
For example, set the nbs to 128，yolov5n.yaml --weights '' --batch-size 128
                                                      yolov5s                                                 64
                                                      yolov5m                                                40
                                                      yolov5l                                                  24
                                                      yolov5x                                                 16
May I handle it in this way？

**Comment by glenn-jocher** [comment]
@wangtao0219 use maximum batch size your card allows, or pass `--batch -1` for AutoBatch.

**Comment by wangtao0219** [comment]
@glenn-jocher nominal batch size(nbs) remains the same, still set to 64 ?

**Comment by glenn-jocher** [comment]
@wangtao0219 everything remains the same
