### ISSUE TITLE
Incorrect Class IDs while exporting to OpenVINO for NCS2

### ISSUE THREAD

**Issue by Averen19** [ultralytics/yolov5#7076]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I have trained a custom dataset and would like to deploy on the NCS2 using Raspberry Pi. I converted the .pt file to .xml with the python export.py --include openvino code. However, my class_ids name are wrong as it still shows the original class ids like people and bicycle for class ids 0 and 1. Any solution?

**Comment by glenn-jocher** [comment]
@Averen19 if you are using detect.py or val.py with a custom dataset and exported model you can pass your data.yaml as an argument to read your class names from:
https://github.com/ultralytics/yolov5/blob/9b771a3e7112f864cb9c877733eca9240e8fb4a5/detect.py#L215

**Comment by Averen19** [comment]
@glenn-jocher  Thank you, that problem has been solved. Do you know any resources or code that can do the inferencing using the openVINO toolkit with the converted IR files? 
I would like to do detect objects using the NCS 2 on the Raspberry Pi 4.
