### ISSUE TITLE
Weights and Biases resume

### ISSUE THREAD

**Issue by st162053** [ultralytics/yolov5#7077]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, 

I am trying to resume my run from weights and biases, but unfortunately it is not longer possible.  I used wandb==0.12.10 as the new version didn't work.
I get the following error message and cant't really get behind it.
![Screenshot 2022-03-21 122909](https://user-images.githubusercontent.com/94604405/159252953-897a7977-d5c7-4874-8a21-102e3d189f47.jpg)

Thanks!

**Comment by glenn-jocher** [comment]
@st162053 thank you for the bug report! Can you please provide the link to your run?

@AyushExel can you look into this please?

**Comment by st162053** [comment]
This is the link to my Google Colab notebook: 
https://colab.research.google.com/drive/168oIOGdaSHOYHJKEqzajzzlOAjCFnay4#scrollTo=NJppVHvGWJoH

My wandb run is in a private wandb project so I haven't attached it yet . Can you also work with that? Also realised that I am using more storage than 100GB might that be the problem?

**Comment by DanjaStein** [comment]
I am experiencing the same issue and can't resume my training with the Wandb artifacts :/

**Comment by AyushExel** [comment]
Thanks for the report. I'm looking into this

**Comment by AyushExel** [comment]
@st162053 I have made a branch with a fix. I'd love it if you could try it out. The artifact resume feature should work with the latest version of wandb as well. Please let me know if that works for you.
Here's my branch -`git clone https://github.com/AyushExel/yolov5 -b resume_fix`
Can you try the following with the latest wandb version:
* Run and upload dataset / tables
* try to resume a run using artifacts.
Please let me know if you run into any problem. Once verified, I'll make a PR so that this fix is available in yolov5 master branch
Note: The artifacts uploaded from previous branches might not work.

**Comment by st162053** [comment]
Hi :) while training a new model I ran into the following problem. 
![Screenshot 2022-03-24 134000](https://user-images.githubusercontent.com/94604405/159918517-81aaf005-122b-42cf-9474-95f61f12141a.jpg)

**Comment by AyushExel** [comment]
@st162053 whats the problem? I don't see any errors? Did you terminate the process manually? The semaphore tracer is just a verbose warning.

**Comment by st162053** [comment]
No it stopped after showing the warning, but without any further errors. Not sure why, but training works now as long as I use wandb==0.12.10 :) will report if resuming works!

**Comment by AyushExel** [comment]
@st162053 thanks. please let me know if resuming works with the latest version whenever you check it . Thanks!

**Comment by st162053** [comment]
Resuming works with 0.12.10, will check the latest version right after it's finished! Thanks for your help!

**Comment by st162053** [comment]
Hi :) Training (and so Reuming) unfortunatly didn't work with wandb 0.12.11 for me.

**Comment by AyushExel** [comment]
@st162053 yes both training and resuming should work for 0.12.10 ...I'll pin that version and raise a warning if it doesn't match
