### ISSUE TITLE
detect.py of testdata using the autosplit method

### ISSUE THREAD

**Issue by DanjaStein** [ultralytics/yolov5#7078]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, 

ich have a question regarding the detection of my Data. I used the autosplit function to separate my data into train, val and test. The training of the KI worked out fine, but now I can't seem to get the detection to work with the autosplit_test.txt

!python detect.py --weights ../drive/MyDrive/SYN72/weights/best.pt --img 640 --conf 0.25 --source ../drive/MyDrive/autosplit_test.txt

My autosplit_test.txt is in my drive with all the required data and look like this: 
./Datensammlung/1010insekten.jpg
./Datensammlung/10167insekten.jpg
./Datensammlung/1016insekten.jpg
./Datensammlung/1022insekten.jpg
./Datensammlung/1030insekten.jpg
...
the responding folder "Datensammlung" is also in my drive. 

I get the ERROR:

detect: weights=['../drive/MyDrive/SYN72/weights/best.pt'], source=../drive/MyDrive/autosplit_test.txt, data=data/coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False
YOLOv5 🚀 v6.1-52-g9b771a3 torch 1.10.0+cu111 CPU

Fusing layers... 
Model Summary: 213 layers, 7031701 parameters, 0 gradients, 15.9 GFLOPs
WARNING: Environment does not support cv2.imshow() or PIL Image.show() image displays
cv2.imshow() is disabled in Google Colab environments
Traceback (most recent call last):
  File "detect.py", line 252, in <module>
    main(opt)
  File "detect.py", line 247, in main
    run(**vars(opt))
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 100, in run
    dataset = LoadStreams(source, img_size=imgsz, stride=stride, auto=pt)
  File "/content/yolov5/utils/datasets.py", line 311, in __init__
    assert cap.isOpened(), f'{st}Failed to open {s}'
**AssertionError: 1/669: ./Datensammlung/1010insekten.jpg... Failed to open ./Datensammlung/1010insekten.jpg**

As it worked fine whilst training using the autosplit_train.txt and autosplit_val.txt I don't really understand why it is not working.

Hopefully you can help me :) 

Best regards, 
Danja

**Comment by glenn-jocher** [comment]
@DanjaStein detect.py doesn't accept a list of images, but it accepts directories, globs, etc:

<img width="962" alt="Screenshot 2022-03-21 at 14 00 10" src="https://user-images.githubusercontent.com/26833433/159265954-363326c1-cc92-480b-bb40-aeeb87a2ab57.png">

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by DanjaStein** [comment]
@glenn-jocher okay thanks you so much for the quick answer and the Pull Request  reminder :). Then I will use an other way!

**Comment by glenn-jocher** [comment]
@DanjaStein this is actually a feature I've been meaning to add, as you're not the first user that has tried this.
