### ISSUE TITLE
Library seat detection using yolov5

### ISSUE THREAD

**Issue by Aoi-00** [ultralytics/yolov5#7080]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi! I am intending to use yolov5 for one of my projects on library seat detection. I hope to detect if a seat is occupied by: 

- Checking for a human in a bounding box
- Checking for a chair in a bounding box
- If their bounding box overlaps, the seat is occupied

May I ask if this is possible through yolov5 as I have not seen a similar application before?

Thank you in advance for the help and guidance!

**Comment by glenn-jocher** [comment]
@Aoi-00 sounds like the perfect example application!

<img width="2163" alt="Screenshot 2021-11-22 at 18 26 43" src="https://user-images.githubusercontent.com/26833433/159277402-6ff67369-50be-4cf3-a6c9-454ec78d9ac1.png">

**Comment by Aoi-00** [comment]
Pardon me, do you mean there is a example application/ tutorial online that perfectly suits this description?

**Comment by glenn-jocher** [comment]
@Aoi-00 this is a default use case for YOLOv5, nothing special is required. To get started go to https://docs.ultralytics.com/yolov5/tutorials/train_custom_data

**Comment by Aoi-00** [comment]
I see, thanks for such answering in such a prompt manner!

However, I noticed that the chair and human detection on pretrained coco.yaml is sufficient for my project, which is great! But is there a way to add-on separate items for detection, such as books/water bottles etc (items that would appear on a library desk to indicate its occupancy), while still using the pretrained human and chair detection models?

**Comment by glenn-jocher** [comment]
@Aoi-00 books and bottles are already in COCO:
https://github.com/ultralytics/yolov5/blob/cf4f3c3455d14c62e11dcce9f1d30211509da72f/data/coco.yaml#L16-L27

**Comment by Aoi-00** [comment]
Oh that's great!

Is there a way to set a predefined bounding box, eg. Assign some seat bounding boxes in which they will try to detect for humans/chairs?

**Comment by glenn-jocher** [comment]
@Aoi-00 Yes, you can define your own bounding boxes by creating a custom dataset with labeled seat bounding boxes. You can refer to the YOLOv5 documentation for creating custom datasets and annotations.
