### ISSUE TITLE
ZeroDivisionError on Raspberry Pi 4 32-bit Buster OS when testing with Openvino

### ISSUE THREAD

**Issue by vyang2968** [ultralytics/yolov5#7081]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Question

I am trying to run my YOLOv5 model on a Raspberry Pi 4 with 32-bit Buster OS on the Intel Neural Compute Stick 2. I have successfully detected objects on an image with all of these components, but when it comes to video, I get the following error:
 ``` 
File "detect.py", line 202, in <genexpr>
t = tuple(x / seen * 1E3 for x in dt)  # speeds per image
ZeroDivisionError: float division by zero
```

I've traced back to that line a printed each component. I've printed the value of `seen` and the values of `dt`. `dt` comes out as `[0.0, 0.0, 0.0]` and seen comes out as `0`. I'm not sure why the image works but the video does not. Any help would be greatly appreciated; thank you in advance. 

### Environment

-Version: YOLOv5 v6.1-37-g3f63d4 torch 1.8.0a0+56b43f4 CPU
-OS: Raspbian GNU/Linux 10 (buster)
-Python Version: Python 3.7.3

### Minimal Reproducible Example

For detection with image, I ran `python3 detect.py --weights pure_model_openvino_model --source IMG_4880.jpg --data balls.yaml`, printing `Speed: 105.1ms pre-process, 258.5ms inference, 194.1ms NMS per image at shape (1, 3, 640, 640)`.

For detection with video, I ran `python3 detect.py --weights pure_model_openvino_model --source testvideo.mp4 --data balls.yaml`, printing 
```
Traceback (most recent call last):
  File "detect.py", line 252, in <module>
    main(opt)
  File "detect.py", line 247, in main
    run(**vars(opt))
  File "/home/pi/.local/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 202, in run
    t = tuple(x / seen * 1E3 for x in dt)  # speeds per image
  File "detect.py", line 202, in <genexpr>
    t = tuple(x / seen * 1E3 for x in dt)  # speeds per image
ZeroDivisionError: float division by zero
```

### Additional

In models/common.py in DetectMultiBackend, I changed the line `executable_network = core.load_network(network, device_name='CPU', num_requests=1` to `executable_network = core.load_network(network, device_name='MYRIAD', num_requests=1` because I am using the Intel Neural Compute Stick 2 which has the device name "MYRIAD".

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@vyang2968 thanks for the bug report! Your video command points --source to the same image. Can you please provide a correct command to reproduce the issue?

**Comment by vyang2968** [comment]
@glenn-jocher just fixed it
