### ISSUE TITLE
Draw 3D box from 2D bounding box

### ISSUE THREAD

**Issue by devendraswamy** [ultralytics/yolov5#7082]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Please help me , Is their any possibility to  convert the 2D bonding box into 3D bounding box in inference output , Thank you so much in advance.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Zephyr69** [comment]
You need object depth info, which there is none in one single rgb image, to draw 3D boxes. There are some estimation methods but to no usable accuracy.

**Comment by devendraswamy** [comment]
Thank you for your valuable information , could please suggest any
approaches to draw 3D bounding box from 2D bounding box in inference output.

**Comment by glenn-jocher** [comment]
@devendraswamy 3D is a completely separate domain where you would need 3D labelled data, i.e. Lidar point clouds. There are separate image to depth models available that @Zephyr69 is referring to, you might be able to pair these with a YOLOv5 model to get depth estimate for object centers, but not 3D bounding boxes.

**Comment by devendraswamy** [comment]
Thank you @glenn-jocher
