### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'tensor_split'

### ISSUE THREAD

**Issue by 1JAEWOOCHOI1** [ultralytics/yolov5#7085]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

train.py을 사용하는 중 
AttributeError: 'Tensor' object has no attribute 'tensor_split'
문제가 발생했습니다.
하지만 이것을 해결할 실력이 되질 않습니다
![화면 캡처 2022-03-22 004744](https://user-images.githubusercontent.com/95038479/159298591-eb4b4cd7-9c64-48a6-8f0c-8394864d7bd8.png)

**Comment by glenn-jocher** [comment]
@1JAEWOOCHOI1 good news 😃! Your original issue may now be fixed ✅ in PR #7074. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by 1JAEWOOCHOI1** [comment]
다시 시도해보고 있는데 아직 해결을 하지 못했습니다.

**Comment by glenn-jocher** [comment]
@1JAEWOOCHOI1 https://github.com/ultralytics/yolov5/pull/7074 resolves your original issue. You need to update your code per the above instructions.

**Comment by marvision-ai** [comment]
Hi @glenn-jocher 

I have updated the repo with the PR but still run into the same problem.
![image](https://user-images.githubusercontent.com/7716574/159500026-5dd8ff9f-eedd-48df-a5d8-375722de45c2.png)

**Comment by kimkihoon0515** [comment]
<img width="575" alt="image" src="https://user-images.githubusercontent.com/63439911/159513202-ef0fccfa-b105-441f-afd7-33c5cc3cbd86.png">

@glenn-jocher 
Ya same for me. Just updated the repo by using git pull but still problem not fixed

**Comment by glenn-jocher** [comment]
@marvision-ai @kimkihoon0515 oh interesting. This is in the loss function rather than the model itself. Maybe torch.Tensor.tensor_split() was only introduced recently. What version of `torch` are you guys using?

**Comment by kimkihoon0515** [comment]
@glenn-jocher  I'm using 1.7.1 
<img width="287" alt="image" src="https://user-images.githubusercontent.com/63439911/159519177-dd3d22a3-948d-4d3d-9e50-4e9b7121c594.png">

**Comment by glenn-jocher** [comment]
@marvision-ai @kimkihoon0515 it looks like `torch.Tensor.tensor_split` was first introduced in torch 1.8.0:
https://pytorch.org/docs/1.8.0/tensors.html?highlight=tensor_split#torch.Tensor.tensor_split

Since our requirements are torch>=1.7.0 we have a problem now... let me think about this

**Comment by kimkihoon0515** [comment]
@glenn-jocher   should i upgrade my torch above to 1.8.0??

**Comment by glenn-jocher** [comment]
@kimkihoon0515 yes if you upgrade the problem will be solved. I need to figure out if I can replace tensor_split with something 1.7.0 compatible though for everyone else, otherwise I'll have to raise the YOLOv5 requirements to 1.8.0, which we probably want to avoid.

**Comment by kimkihoon0515** [comment]
@glenn-jocher which version of torch and cuDNN u use? i just upgraded my torch and seems the cuDNN version doesn't match with my torch ver

**Comment by glenn-jocher** [comment]
@kimkihoon0515 see https://pytorch.org/get-started/previous-versions/

**Comment by glenn-jocher** [comment]
@kimkihoon0515 @marvision-ai good news 😃! Your original issue may now be fixed ✅ in PR #7102. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
