### ISSUE TITLE
weights load after adding layers

### ISSUE THREAD

**Issue by WDDouble** [ultralytics/yolov5#7090]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

So i trained original yolov5 and get the best.pt weights file. And then i added 3 dropout layers before the detection layer to fine tune the model.![20220321220942](https://user-images.githubusercontent.com/98332082/159364315-ee11d28a-cdf5-49eb-aa75-5068bdb90e84.png)
Question is, after changing the cfg file and load the best.pt weights file, the weights of the dection layer cannot be loaded. How could i modify my weight so that all the weight can be loaded(cause the dropout layers do not require parameters)

thank you so much!

**Comment by glenn-jocher** [comment]
@WDDouble you could modify Detect() directly here, or simply train a new model with your new yaml:
https://github.com/ultralytics/yolov5/blob/a2d617ece94dcd8c9bc205ea70f1223c84fdbe3a/models/yolo.py#L33-L82
