### ISSUE TITLE
Is there any way to detect two kinds of objects from an image or video using two seperate trained weight files?

### ISSUE THREAD

**Issue by safal-305** [ultralytics/yolov5#7096]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hey. I had trained a weight file to detect an object and another weight file to detect another specific object. If i want to detect both objects in a single images, can i ,like, use both weight files together? Or is there a way to combine the both trained files into a single one, without training the datasets again together?

**Comment by glenn-jocher** [comment]
@safal-305 yes, you can train one model on multiple datasets. See https://community.ultralytics.com/t/how-to-combine-weights-to-detect-from-multiple-datasets

**Comment by safal-305** [comment]
> @safal-305 yes, you can train one model on multiple datasets. See https://community.ultralytics.com/t/how-to-combine-weights-to-detect-from-multiple-datasets

That means i will have to combine both datasets and train them again , right? 
What i am asking is, can i ,like, combine the both trained weight files to detect the seperate objects?
