### ISSUE TITLE
Who can download the weight file and send me a copy? Many thanks!

### ISSUE THREAD

**Issue by CsnowyLstar** [ultralytics/yolov5#71]
attempt_download('weights/yolov5s.pt');
attempt_download('weights/yolov5m.pt');
attempt_download('weights/yolov5l.pt');
attempt_download('weights/yolov5x.pt')"

**Comment by Small-salted-fish** [comment]
My email is 287998116@qq.com.

**Comment by glenn-jocher** [comment]
@Small-salted-fish if you are in China this may be a possible duplicate of https://github.com/ultralytics/yolov5/issues/60?
