### ISSUE TITLE
from utils import general; plot_results doesn't work 

### ISSUE THREAD

**Issue by ImsuperSH** [ultralytics/yolov5#710]
it's just blank when running plot_results

## To Reproduce (REQUIRED)

Input:
```
from utils import general; plot_result
```

Output:
```
blank plot
```

## Environment

 - OS: [e.g. Ubuntu]
 - GPU [e.g. 2080 Ti]

**Comment by glenn-jocher** [comment]
This command plots results in your root directory. If nothing is plotted you have no results.txt files in yolov5/

**Comment by glenn-jocher** [comment]
@Sean-pure if you are trying to plot results.txt files in subdirectories:
`plot_results(save_dir='path/')`

**Comment by ImsuperSH** [comment]
@glenn-jocher Yean I'm using it, thank you.
