### ISSUE TITLE
Doubts about which graphic to use

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#7100]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello everyone, I have to do a project at the university with Yolo for image analysis. 

Currently I don't have a physical GPU and I would like to buy one, but I don't know if all of them are valid NVIDIA AND AMD, and if they have to have some specific technology, like for example the nvidia if they have to have some CUDA or it is not necessary.
I would be interested in one with a price not higher than 260€ (286$), I don't know if those meet the requirements. 
Sorry for my little knowledge on this subject.

Which graphics cards can be used with YOLOv?

Best regards.

**Comment by glenn-jocher** [comment]
@gineszamorac YOLOv5 and PyTorch are compatible with all NVIDIA GPUs. You can also use notebooks with free GPUs here:

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
