### ISSUE TITLE
Timestamp and Position of the predicted bounding boxes in each frame.

### ISSUE THREAD

**Issue by frangoncab** [ultralytics/yolov5#7106]
It´s a good question, very useful both issues. To get the timesptamp  and the position of the predicted bounding boxes in each frame, in a video or predicting images.

Any help?

Thanks!!

_Originally posted by @frangoncab in https://github.com/ultralytics/yolov5/discussions/6814#discussioncomment-2367958_

**Comment by frangoncab** [comment]
Hello again.

I´ve read and investigated in detail the [Yolov5 Github Doc](https://github.com/frangoncab/yolov5), [YOLOv5 Docs](https://docs.ultralytics.com/), so I know the [Custom Data Training](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data) and this isn´t a hyperparameter nor a W&B issue. Even I´ve been exploring the issues and discussions. Although I recognize that I may be wrong, I haven´t find out the answer to my questions.

I think It´s really easy for you, because I only need to know if it´s possible to customize the ouptut of the Yolov5 aplicaction as published in Github, because it would be very useful for me to get the timestamp of a frame in a video, and the position of the predicted bounding boxes in each frame, in a video or predicting images.

I suppose I can get all these working in Pytorch hub, but I´d like to know if it´s possible directly as the app is published in Github Yolov5 repository.

Thanks for your help.

**Comment by glenn-jocher** [comment]
@frangoncab I'm not sure what you're asking. Custom workflows are what 100% of our users do. If you want one, build it yourself.

**Comment by frangoncab** [comment]
From your reply it seems that I have annoyed you, it was not my intention. 

Thank you in any case.

**Comment by glenn-jocher** [comment]
@frangoncab you can easily build your own custom workflows with PyTorch Hub, i.e. create a for loop with a cv2 video reader and then handle inference results however you want.

YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, etc.
# model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')  # custom trained model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by frangoncab** [comment]
I´ll build my own custom work flow.

**Thanks a lot** for your help @glenn-jocher. Pytorch hub is the solution I need.

**Comment by glenn-jocher** [comment]
You're very welcome, @frangoncab! I'm glad to hear that PyTorch Hub is the solution you need. If you have any further questions or need assistance with anything else, feel free to reach out. Best of luck with your custom workflow, and have a great day!
