### ISSUE TITLE
Meaning of the 3 outputs

### ISSUE THREAD

**Issue by curimeowcat** [ultralytics/yolov5#7109]
Could you also explain why do we have these 3 outputs? If I feed an image of a cat with resolution 640x640, what will be these 3 outputs? Why do we need 3? Do they output different scales of bounding boxes? In the end we have 3 outputs or output the best one or there are some techniques to combine these outputs into a single output? Thanks!

@bretagne-peiqi yes this looks correct, except that with the v2.0 release the 3 output Conv2d() boxes (red in your diagram) are now inside the Detect() stage:
```python
    (24): Detect(
      (m): ModuleList(
        (0): Conv2d(128, 255, kernel_size=(1, 1), stride=(1, 1))
        (1): Conv2d(256, 255, kernel_size=(1, 1), stride=(1, 1))
        (2): Conv2d(512, 255, kernel_size=(1, 1), stride=(1, 1))
      )
```

_Originally posted by @glenn-jocher in https://github.com/ultralytics/yolov5/issues/280#issuecomment-663359677_

**Comment by glenn-jocher** [comment]
@curimeowcat YOLOv5 models detect objects at different scales. Each of the outputs are designed to detect different size objects. The largest convolutions detect the largest objects and vice versa.
