### ISSUE TITLE
dynamic label how to do?

### ISSUE THREAD

**Issue by premananda8** [ultralytics/yolov5#7110]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want dynamic label suppose object is detected as helmet i want to change "With Helmet" in dynamic in code. So how to do?

**Comment by glenn-jocher** [comment]
@premananda8 you can update model `names` array here when using detect.py:
https://github.com/ultralytics/yolov5/blob/c3ae4e4af6f75aff537b876adc11da3de441dd60/detect.py#L93

**Comment by premananda8** [comment]
Ok I will try thank you so much it is nice

**Comment by glenn-jocher** [comment]
@premananda8 you're welcome! I'm glad to help. If you have any more questions, feel free to ask. Good luck with your project!
