### ISSUE TITLE
RTX3070 cuda11.1 training not working

### ISSUE THREAD

**Issue by nullun1998** [ultralytics/yolov5#7112]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,
For some reason, using RTX3070 cuda11.1 training is not working.
It work fine before , however when I expand dataset it show P = 0 , R = 0, mAP = 0.
![image](https://user-images.githubusercontent.com/71395474/159610826-2c9ed0e1-dcfa-43f3-8df4-63651db40f0b.png)

I search for solution, they usually downgrade to cuda10.2 to solve this problem.
But it seem cuda 10.2 can't work on RTX30.
Is there any other way to solve this problem.

**Comment by glenn-jocher** [comment]
@nullun1998 CUDA 11 has some issues with mixed/half precision on certain GPUs. You could try disabling AMP during training, or perhaps try training inside our Docker container. AMP is here:
https://github.com/ultralytics/yolov5/blob/c3ae4e4af6f75aff537b876adc11da3de441dd60/train.py#L329
