### ISSUE TITLE
Why is yolov5s more accurate than yolov5x?

### ISSUE THREAD

**Issue by sarah-muller** [ultralytics/yolov5#7113]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I trained on certain images with model size S and X.
The results of S was more better than X.
The indicators I'm lookig at is cls_loss.
the valid cls_loss of S was 0.0009 but X was 0.002  

- train conditions
   - number of class : 4
   - number of images(train&val) : about 5,000 & 2,000
   - epochs of S : 360 (patience 50)
   - epochs of X : 450 (patience 50) 

- result
  - train cls_loss of S: 0.004
  - train cls_loss of X: 0.003
  - valid cls_loss of S: 0.0009
  - valid cls_loss of X: 0.002

I've trained it many times with different conditions(number of images or data augmentation etc), 
but the results were always better with using S.

What are the possible factors that make S more accurate than X ?

**Comment by glenn-jocher** [comment]
@sarah-muller I can't say on your dataset, but on COCO the range of YOLO models are shown here:
https://wandb.ai/glenn-jocher/YOLOv5_v61_official

The larger models correspond to less loss and higher mAP in most scenarios I'm aware of.

**Comment by sarah-muller** [comment]
Is it because of the small number of classes? I don't know, but OK for now, thanks.

**Comment by glenn-jocher** [comment]
@sarah-muller it's certainly a possibility. The number of classes and the specifics of your dataset can definitely impact the performance of different model sizes. If you have any further questions or need assistance, feel free to ask. Thank you!
