### ISSUE TITLE
Inference images size is not 640x640?

### ISSUE THREAD

**Issue by HANK538** [ultralytics/yolov5#7119]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello

I train model with  --img 640 config that I consider resize 640x640 for training.
Then, I use detect and show up  384x640 log message.
I had no idea why it resize that shape for inference and did it make performance difference ?
Should I resize all image to 640x640 before inference or just do nothing?

Thanks

**Comment by glenn-jocher** [comment]
@HANK538 sizing is handled automatically, no action is required on your part other than passing the --img-size you want for the long side (short side is managed automatically for best results).

**Comment by dsantiago** [comment]
@glenn-jocher This info could be added on ArgumentParser for less confusion, i remember fist time i tried, i passed 240,320 than discovered reading detect.py that it duplicates the dimension if just one was passed.
