### ISSUE TITLE
During finetuning for second time of yolov5s it does not save best.pt

### ISSUE THREAD

**Issue by Manpreetkour95** [ultralytics/yolov5#7121]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

![image](https://user-images.githubusercontent.com/74677887/159844911-ac80682b-b738-4e1d-86d6-5ee18d4d3227.png)

I first trained yolov5 on a 1000 images dataset by using the coco weights and freezing 10 layers, after that I finetuned it on 2000 more images and then 3000 more images. During first two training it was saving both best.pt and last.pt but during fine-tuning it does not save best.pt . I have tried many times but it does not save best.pt. Similar issue has been faced by my friend as well. Now we are saving the model on every epoch and analyzing the results. It would be very if you can fix this.
![image](https://user-images.githubusercontent.com/74677887/159844504-4cd31860-6839-4c76-9daf-6f5fabd421db.png)

### Environment

[yolov5](https://github.com/ultralytics/yolov5)
python

### Minimal Reproducible Example

!python train.py --batch 64 --epochs 400 --data ./models/custome_data.yaml --cfg ./models/yolov5s.yaml --weights ./best3000wt/best3000.pt --name yolov5s_resultsalla --device 0

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Manpreetkour95 saving logic is here if you'd like to debug. best.pt is only saved when a new best fitness epoch is observed:

https://github.com/ultralytics/yolov5/blob/bc3ed957ce0f0990a3cb408e462197b83b0d075f/train.py#L388-L407

**Comment by glenn-jocher** [comment]
@Manpreetkour95 also note you can use the `--save-period` argument, i.e. `python train.py --save-period 10` will save a model every 10 epochs in addition to last.pt and best.pt

**Comment by Manpreetkour95** [comment]
Thanks, I guess I have understood the problem. My model is not performing better after fine-tuning that's why it is not getting saved.

**Comment by glenn-jocher** [comment]
@Manpreetkour95 you're welcome! If you have any more questions or need further assistance, feel free to ask. Good luck with your fine-tuning process!
