### ISSUE TITLE
Inference on ONNX and TensorRT

### ISSUE THREAD

**Issue by fronos** [ultralytics/yolov5#7123]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I'm working with yolo5 (Trained  on a custom dataset) and a little bit confused with output on Onnx and tensorRT. In your script common.py written that default output is [xyxy, conf, cls].  I have only 1 class for prediction. What does mean the last element of array?  Because during inference I get different values here.
Sample of model prediction:
[31.717812    9.168299    4.0388975  39.616806    0.7405945   0.99999857]
[29.397682   10.437282   27.314425   51.067707    0.99360156  0.99999726]

**Comment by glenn-jocher** [comment]
@fronos you already answered your own question, the indices of your outputs are [xyxy, conf, cls]

**Comment by fronos** [comment]
But I tested using your repo and during inference  used custom scripts. In your repo cls - num of class, but in raw output it's a class probability.
