### ISSUE TITLE
?Question. Are background images being used for calculating precision, recall, mAP?

### ISSUE THREAD

**Issue by sangbin-kim** [ultralytics/yolov5#7124]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to reduce False Positive for my trained model. 

I have a tons of background images. And I would like to use them for training in order to minimize FP  .

So, my question is, 

Are background images being used for calculating precision, recall, mAP ?

If I train my model with lots of background images, the model would have better performance in term of FP?

**Comment by glenn-jocher** [comment]
@sangbin-kim yes background images help reduce FPs. And yes background images in your val set are included in mAP calculation.

**Comment by Yaoxingtian** [comment]
> @sangbin-kim yes background images help reduce FPs. And yes background images in your val set are included in mAP calculation.

Hi, could you pls. tell me how backgound image works and reduce FPS? just put background images into train data .
thanks !

**Comment by glenn-jocher** [comment]
@Yaoxingtian 

- **Background images.** Background images are images with no objects that are added to a dataset to reduce False Positives (FP). We recommend about 0-10% background images to help reduce FPs (COCO has 1000 background images for reference, 1% of the total). No labels are required for background images.

**Comment by Yaoxingtian** [comment]
> @Yaoxingtian
> 
>     * **Background images.** Background images are images with no objects that are added to a dataset to reduce False Positives (FP). We recommend about 0-10% background images to help reduce FPs (COCO has 1000 background images for reference, 1% of the total). No labels are required for background images.

Yes, I mean ,any theory support this or how it works better in network ?

**Comment by Yaoxingtian** [comment]
> @Yaoxingtian
> 
>     * **Background images.** Background images are images with no objects that are added to a dataset to reduce False Positives (FP). We recommend about 0-10% background images to help reduce FPs (COCO has 1000 background images for reference, 1% of the total). No labels are required for background images.

Yes, I mean ,any theory support this or how it works better in network ?
