### ISSUE TITLE
Number of coco datasets about the pre-training process

### ISSUE THREAD

**Issue by thx13** [ultralytics/yolov5#7125]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, excuse me,  I'd like to know that all pictures of coco2017-train is used as training set in pre-training weight? I want to refer to the quantity

**Comment by glenn-jocher** [comment]
@thx13 all training images are used for training if that's your question. Details on COCO are here:
https://github.com/ultralytics/yolov5/blob/a0a4adf6de4de3d9d5ac00c23796c844a8e57200/data/coco.yaml#L1-L15

**Comment by thx13** [comment]
Thank you for your answer. Your answer is very helpful to me
