### ISSUE TITLE
New output format

### ISSUE THREAD

**Issue by mikel-brostrom** [ultralytics/yolov5#7130]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When I `print(preds.shape)` before the NMS i get the following

```bash
torch.Size([1, 20160, 17])
```

What are these 17 values?

**Comment by glenn-jocher** [comment]
@mikel-brostrom these are (xywh, obj, cls0, cls1, ..., clsn)

**Comment by mikel-brostrom** [comment]
Thanks!
