### ISSUE TITLE
 questions about model change and val output

### ISSUE THREAD

**Issue by ZhaoCecil** [ultralytics/yolov5#7132]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

i have two question about model change and val output
[1]
i added  ECA after C3 ,Focal Loss and got a  result in train.py
but when i use val.py and detect.py to the yolo_new_best.py, i get a worse result than train.py
![1](https://user-images.githubusercontent.com/51195572/159935269-75fc91a8-08e9-4037-bf0c-e6c17eb0fb96.jpg)
 ![33806f9a58d5589f2e5ad936051e97a](https://user-images.githubusercontent.com/51195572/159934838-46596e07-a315-4a4b-b82c-0abd35251c51.png)

[2]
also ,when i add '--save-txt --save-hybrid --save-conf', it suddenly goes strange

 ![33806f9a58d5589f2e5ad936051e97a](https://user-images.githubusercontent.com/51195572/159934838-46596e07-a315-4a4b-b82c-0abd35251c51.png)
![0c1ec89a58be6a30b19b091673863c7](https://user-images.githubusercontent.com/51195572/159934158-36f12f56-d9da-4a4e-9969-795dafd77662.png)

anyone have any ideas? i have tested it in v6.1

**Comment by glenn-jocher** [comment]
@ZhaoCecil `--save-hybrid` is used for creating hybrid labels (predictions combined with existing labels). If you want hybrid labels, use it. If you want a valid map, do not use it.
