### ISSUE TITLE
Estimation speed of model with input size diverse

### ISSUE THREAD

**Issue by hoangkhoiLE** [ultralytics/yolov5#7134]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,

After analysing your benchmark table, I see that in this case, if we double the resolution of image (x2 times between 1280 and 640), the time of inference with cpu of the same model is between x4~x2^2 times which is directly proportional with the augmentation of  resolution. Can we use this to estimate the speed of the model with each resolution ? 
For example, the 640 is bigger than 256 about x2.5 times.  So the time of inference with cpu (model 640x640) is up to 2.5^2= 6.25 times more than the model with input 256x256.

I would be very glad to hear from you

Thank you in advance.

Best regard
![image](https://user-images.githubusercontent.com/57557628/159981099-a71b2b24-9c9a-4851-8c12-706086e52733.png)

**Comment by glenn-jocher** [comment]
@hoangkhoiLE sure, sounds about right.

**Comment by hoangkhoiLE** [comment]
Thank you !
