### ISSUE TITLE
YoloV5 Onnx Model Output Post Processing For Xamarin Forms

### ISSUE THREAD

**Issue by willsonyee** [ultralytics/yolov5#7144]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am currently trying to integrate YoloV5 Onnx Model into Xamarin Form C# using OnnxRuntime, but I am currently encountering some roadblocks due to lack of experiencing. Can someone advise me on how to post process the output after inferenced?

Netron for my YoloV5 Onnx Model:
There are total of 4 outputs for my models - output, 345, 403, 461. May I know what are the meaning for these 4 outputs? 

![onnx1](https://user-images.githubusercontent.com/98082493/160105205-871d4783-3e00-4206-aaec-17aa46709890.PNG)

I couldn't move forward from here after I get the output tensor, any advises will be much appreciated.

![onnx2](https://user-images.githubusercontent.com/98082493/160105223-f975c10a-862e-482d-8c3b-cf0beecdfce3.PNG)

Please let me know if you require more information to further clarify the question.

Thank you very much.

**Comment by glenn-jocher** [comment]
@willsonyee 'output' is all you need. The other 3 are the outputs at each grid P3-P5, which are already present in 'output'.

The dimension of 'output' are shape(batch,anchors,outputs), where outputs are [xywh, objectness, classes confidences]

**Comment by willsonyee** [comment]
@glenn-jocher I see, thanks for the clarification on the "output" of the onnx model. 

Right now the "var output" in my second pictures have the "output" of the onnx model multiplied (1 x 25200 x 7 = 176400). Pardon my dullness, could you guide me on how to post process this?

I searched around the github issues, do I need to do something called NMS in C#? Thanks alot

**Comment by glenn-jocher** [comment]
@willsonyee see https://pytorch.org/vision/main/generated/torchvision.ops.nms.html

Your 7-length vector is xywh, objectness, class 1, class 2

**Comment by willsonyee** [comment]
@glenn-jocher I am currently using Microsoft.ML.OnnxRuntime to load the YoloV5 model and make prediction. 

But I couldn't postprocess the output from the model to xywh, objectness, class1, class2. 

Do you have an code examples for onnx C#? Thanks

**Comment by glenn-jocher** [comment]
@willsonyee see [YOLOv5 Export Tutorial](https://docs.ultralytics.com/yolov5/tutorials/model_export) for C++ references
