### ISSUE TITLE
Inter-class uncertainty?

### ISSUE THREAD

**Issue by crsegerie** [ultralytics/yolov5#7147]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,

I know that it is possible to have the uncertainties of the presence or not of a bbox.

But I would like to know if we can also get the uncertainties of the choice of classes when there are several classes?
thanks.

**Comment by glenn-jocher** [comment]
@crsegerie there are no uncertainties at all output by YOLOv5 or almost any other AI model these days. You can apply your own experiments directly to the model outputs before NMS here though, i.e.:
https://github.com/ultralytics/yolov5/blob/7a2a11893b56c67903f0dc4e313235e544189601/detect.py#L119-L128
