### ISSUE TITLE
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

### ISSUE THREAD

**Issue by MKOK-BEEP** [ultralytics/yolov5#7150]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

PyTorch Hub

### Bug

i think this is an old problem not sure but none the less i'm a software developer that just started and wanna learn about video/photo detection 

i face a problem that gives me this

![Screenshot 2022-03-26 020418](https://user-images.githubusercontent.com/82530878/160213086-1cca3b6f-327e-4808-b916-05b981b9ca07.png)
 
i tried uninstall and reinstalling the pip files nothing happen
i tried force_reload=True function same error
idk what to do exactly if any one can help me i will be greatful

### Environment

Yolov5 v6.1
VS code
python v3.10.4

### Minimal Reproducible Example

code :
import torch

model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  
img = 'https://ultralytics.com/images/zidane.jpg'  
results = model(img)
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

error :
fatal: not a git repository (or any of the parent directories): .git
YOLOv5  2022-3-26 torch 1.11.0+cu113 CUDA:0 (GeForce GTX 1650 SUPER, 4096MiB)

Traceback (most recent call last):
  File "C:\Users\mkokg/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 46, in _create
    model = DetectMultiBackend(path, device=device)  # download/load FP32 model
  File "C:\Users\mkokg/.cache\torch\hub\ultralytics_yolov5_master\models\common.py", line 297, in __init__
    pt, jit, onnx, xml, engine, coreml, saved_model, pb, tflite, edgetpu, tfjs = self.model_type(w)  # get backend
  File "C:\Users\mkokg/.cache\torch\hub\ultralytics_yolov5_master\models\common.py", line 476, in model_type
    from export import export_formats
  File "C:\Users\mkokg/.cache\torch\hub\ultralytics_yolov5_master\export.py", line 64, in <module>
    ROOT = Path(os.path.relpath(ROOT, Path.cwd()))  # relative
  File "C:\Users\mkokg\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 718, in relpath
    raise ValueError("path is on mount %r, start on mount %r" % (
ValueError: path is on mount 'C:', start on mount 'D:'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "d:\Programing\project\Detector.py", line 4, in <module>
    model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, custom
  File "C:\Users\mkokg\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\hub.py", line 404, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "C:\Users\mkokg\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\hub.py", line 433, in _load_local
    model = entry(*args, **kwargs)
  File "C:\Users\mkokg/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 80, in yolov5s
    return _create('yolov5s', pretrained, channels, classes, autoshape, verbose, device)
  File "C:\Users\mkokg/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 65, in _create
    raise Exception(s) from e
Exception: path is on mount 'C:', start on mount 'D:'. Cache may be out of date, try `force_reload=True` or see https://github.com/ultralytics/yolov5/issues/36 for help.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@MKOK-BEEP seems like relpath will fail when source and destination are on different drives, on windows at least: https://github.com/dmlc/xgboost/issues/3480#issuecomment-406006664

**Comment by glenn-jocher** [comment]
@MKOK-BEEP I have a proposed fix in #7158. Please re-run your command with the following change to test the fix:
```python
model = torch.hub.load('ultralytics/yolov5:fix/relpath', 'yolov5s', force_reload=True)
```

If it works I'll merge the PR, otherwise please paste your new error message. Thanks!

**Comment by MKOK-BEEP** [comment]
it worked i didn't see the ValueError: path is on mount 'C:', start on mount 'D
am very thankful thanks

**Comment by MKOK-BEEP** [comment]
This bug was fixed

**Comment by glenn-jocher** [comment]
@MKOK-BEEP great, thanks for the feedback! PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐
