### ISSUE TITLE
AttributeError: 'Model' object has no attribute 'get'

### ISSUE THREAD

**Issue by falser101** [ultralytics/yolov5#7151]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

when I use test.py to test my model.pt, how to resolve this problem? 
`Traceback (most recent call last):
  File "/workspace/code/test.py", line 314, in <module>
    test(opt.data,
  File "/workspace/code/test.py", line 57, in test
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "/workspace/code/models/experimental.py", line 120, in attempt_load
    print(ckpt['ema' if ckpt.get('ema') else 'model'].float().fuse().eval())
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1177, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Model' object has no attribute 'get'`

**Comment by glenn-jocher** [comment]
@falser101 there is no test.py in the repo. To update your code:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

**Comment by TiagoGouvea** [comment]
This error (and files) are related to [yolov7](https://github.com/WongKinYiu/yolov7), not yolov5 (this one).

**Comment by glenn-jocher** [comment]
@TiagoGouvea apologies for the confusion. This issue is related to YOLOv7, not YOLOv5. YOLOv7 is a separate project developed by a different author. To troubleshoot the error you're encountering with YOLOv7, I recommend reaching out to the YOLOv7 GitHub repository or its community for assistance. Thank you for bringing this to our attention. If you have any questions regarding YOLOv5, feel free to ask.
