### ISSUE TITLE
An error in training with version 2

### ISSUE THREAD

**Issue by snovire** [ultralytics/yolov5#716]
The requirements have been all installed and detect.py could run. But there was an error in training with my own dataset. AttributeError: 'BatchNorm2d' object has no attribute '_non_persistent_buffers_set'. The pytorch and torchvision have been updated and torch has been updated to 1.16.0, so I could not find out the solution.
![Annotation 2020-08-12 092330](https://user-images.githubusercontent.com/49724561/89964840-ca395880-dc7d-11ea-8d3c-fc6ab066c2d4.png)

**Comment by glenn-jocher** [comment]
What's the purpose of blacking out parts of your path in your screenshot?

**Comment by snovire** [comment]
> What's the purpose of blacking out parts of your path in your screenshot?
@glenn-jocher It was used to blur my school ID because I didn't find the mosaic to hide my personal information lol. Do you know how to solve the problem of '_non_persistent_buffers_set'? Could you please tell me the solution?

**Comment by glenn-jocher** [comment]
@snovire your model is old, it is incompatible with pytorch 1.6, you just need to download a new model.

**Comment by snovire** [comment]
> @snovire your model is old, it is incompatible with pytorch 1.6, you just need to download a new model.

@glenn-jocher Thanks for your reply and help. I just downloaded the new models and tried to train with all the .yaml files, but they all still came with the same '_non_persistent_buffers_set' error. I would re-install my environment and have a try then.
