### ISSUE TITLE
download url error

### ISSUE THREAD

**Issue by junbaibai0719** [ultralytics/yolov5#7163]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Other

### Bug

while i use comand `python train.py --img 640 --batch 16 --epochs 3 --data coco128.yaml --weights yolov5s.pt --device 0`, terminal  print `OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'https:\\github.com\\ultralytics\\yolov5\\releases\\download\\v1.0\\coco2017labels.zip'`.
because 
![image](https://user-images.githubusercontent.com/44611975/160270212-0668b4fa-2492-4e24-b28f-8a2b865ee4d8.png)

### Environment

python3.8.8

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@junbaibai0719 the line you are pointing to no longer exists in that format, your code is out of date.

**Comment by junbaibai0719** [comment]
> @junbaibai0719 the line you are pointing to no longer exists in that format, your code is out of date.

I changed it from `Path(url).is_file()` to `os.path.is_file(url)`.

**Comment by glenn-jocher** [comment]
@junbaibai0719 I'm sorry I don't understand. Is your replacement like supposed to be fix? We can't reproduce any error on Windows. See latest Windows CI results here (all tests are passing, including downloading and training COCO128):
https://github.com/ultralytics/yolov5/runs/5706536680?check_suite_focus=true

<img width="1167" alt="Screenshot 2022-03-27 at 20 34 08" src="https://user-images.githubusercontent.com/26833433/160295585-856c1dab-ace2-48e0-a05a-820463a2f483.png">

**Comment by junbaibai0719** [comment]
> @junbaibai0719对不起，我不明白。您的替代品是否应该修复？我们无法在 Windows 上重现任何错误。在此处查看最新的 Windows CI 结果（所有测试均通过，包括下载和训练 COCO128）： [https ://github.com/ultralytics/yolov5/runs/5706536680?check_suite_focus=true](https://github.com/ultralytics/yolov5/runs/5706536680?check_suite_focus=true)
> 
> <img alt="截图 2022-03-27 at 20 34 08" width="1167" src="https://user-images.githubusercontent.com/26833433/160295585-856c1dab-ace2-48e0-a05a-820463a2f483.png">

It may only be reproduced in Python 3.8.8 on Windows. I am sorry.

**Comment by junbaibai0719** [comment]
@glenn-jocher 
It may only be reproduced in Python 3.8.8 on Windows. I am sorry.

**Comment by HERIUN** [comment]
I changed it from `Path(url).is_file()` to `Path(f).is_file()` it works to me.

In general.py `def download_one(url, dir):`
url = '[https://github.com/ultralytics/yolov5/releases/download/v1.0/coco2017labels.zip]()'
f = WindowsPath('D:/datasets/coco2017labels.zip') // my custom setting

so check datafile in url is weired..
```python
if Path(url).is_file():  # any file in 'url'?? is weired..
```

python version : 3.8.8
os : Windows10

**Comment by glenn-jocher** [comment]
@HERIUN what's the training command that was producing the error for you?

**Comment by junbaibai0719** [comment]
@HERIUN In Python3.8.8, pathlib can not recognize the path like "https://xxx/xx/". Upgrade python to 3.8.10 or higher.
