### ISSUE TITLE
AssertionError: (torch.Size([1, 3, 640, 640]), (1, 3, 640, 480))

### ISSUE THREAD

**Issue by Specialized123** [ultralytics/yolov5#7164]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello!
I use Jetson Xavier NX to deploy programs

**Environment：**
Jetpack: 4.6
Tensorrt: 8.0.1.6
Python: 3.6.9
Pytorch: 1.8.0
torchvision: 0.9.0a0+01dfa8e
cuda: 10.2

**I use this statement to export：**
`python export.py --best.pt --include engine --imgsz 640 480 --device 0`
I used to export on the same device

**Run**
I use this statement to run the program：
`python detect.py --weights best.engine --source 0`
I connected a usb camera

**Bug**
AssertionError: (torch.Size([1, 3, 640, 640]), (1, 3, 640, 480))

![c5ebb9e36cb1e84616016a9f71d4c50](https://user-images.githubusercontent.com/53801574/160270832-18a47869-f331-4c3a-9137-bb07aa75e889.jpg)

I hope you can help me solve this problem

Many thanks and best regards！

**Comment by rglkt** [comment]
i meet the problem too, i  think the wrong is on common.py 299 line .when it will set imgsz as 64 stride forcely when your model is 32 stride. the solution is set 299 line stide as 32

**Comment by rglkt** [comment]
https://github.com/ultralytics/yolov5/pull/7342 you can try as my code

**Comment by lifenghong** [comment]
hello , I am missing the same problem
**Run**
I use this statement to run the program：python detect.py --weights best.engine -- images
  **error**:
![image](https://user-images.githubusercontent.com/37218917/220238642-078e1e73-662f-4f74-92b3-c8ad069a90cc.png),I hope you can help me solve this problem

Many thanks and best regards！

**Comment by rglkt** [comment]
> hello , I am missing the same problem **Run** I use this statement to run the program：python detect.py --weights best.engine -- images **error**: ![image](https://user-images.githubusercontent.com/37218917/220238642-078e1e73-662f-4f74-92b3-c8ad069a90cc.png),I hope you can help me solve this problem
> 
> Many thanks and best regards！

It seems that what you encountered is not the same problem, the problem of this issue has been solved in this pr. The problem you encountered seems to be that the channel is wrong, is there no unsqueeze?

https://github.com/ultralytics/yolov5/pull/7342

**Comment by glenn-jocher** [comment]
@rglkt hi there! It seems like the issue you encountered might be different from the one originally reported. It looks like the problem in the image you provided might be related to incorrect channel handling. Have you checked if there is a need for unsqueezing the data? The solution provided in the pull request you mentioned may not directly apply to your case. 

Let me know if you need further assistance with this or if there's anything else I can help you with. Thank you!
