### ISSUE TITLE
Yolov5 P6 model default anchor number

### ISSUE THREAD

**Issue by ingbeeedd** [ultralytics/yolov5#7168]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

HelloThe total number of anchors for the P5 model is n=9, and is n=12 correct for the P6 model?

**Comment by glenn-jocher** [comment]
Yes.

**Comment by yuyang3478** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
