### ISSUE TITLE
What is the indicator related with wattage consumed by Yolo model

### ISSUE THREAD

**Issue by hyeonmin11** [ultralytics/yolov5#7169]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Does FLOPs related with wattage consumed by Yolo model? If not, what else is related with the wattage?

**Comment by glenn-jocher** [comment]
Your hardware
