### ISSUE TITLE
onnx nms

### ISSUE THREAD

**Issue by linhaoqi027** [ultralytics/yolov5#717]
## ❔Question

when convert the model to onnx,do u do nms before the final output?

**Comment by dlawrences** [comment]
NMS is done in the `detect.py` script based on the output of the model.

https://github.com/ultralytics/yolov5/blob/d2da5230533db7a2c76af1dde6d91c7e1631a1b8/detect.py#L72-L75

The last layer in the model is `Detect`, thus the NMS is not included the exported model.

https://github.com/ultralytics/yolov5/blob/d2da5230533db7a2c76af1dde6d91c7e1631a1b8/models/yolo.py#L18-L56

**Comment by linhaoqi027** [comment]
So,as exported model , the last deminsion of output is what？6 in like[1, 3, 20, 20, 6].a specific meaning.

**Comment by linhaoqi027** [comment]
oh,I use my own dataset, Just have 1 class.Soit is 6(4+1+1)

**Comment by cendelian** [comment]
> oh,I use my own dataset, Just have 1 class.Soit is 6(4+1+1)

hi 
do you use onnx output to do nms?
how to do it and get final result?

could you help me?
