### ISSUE TITLE
Why does the source code downloaded directly report an error?

### ISSUE THREAD

**Issue by OBLPlife** [ultralytics/yolov5#7171]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I commented out the first three lines of code because I already had the relevant environment installed. But why is this error reported? I didn't find it online.
![屏幕截图 2022-03-28 052022](https://user-images.githubusercontent.com/63538599/160301515-a3856f0d-c071-47fd-b252-e50cc42a8bac.png)

**Comment by glenn-jocher** [comment]
@OBLPlife you've modified the source code of the notebook and created the error yourself.
