### ISSUE TITLE
Is there any change in the m or m6 model code in v5 -> v6 

### ISSUE THREAD

**Issue by ingbeeedd** [ultralytics/yolov5#7179]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello
I'm curious about the wts tensorrt conversion.
I don't think the yolov5 model architecture has changed much, is it correct?
It's because I want to train using the copy & paste augment technique in v6.
Currently the target environment is only available for v5-trained models.
So I wonder it
Thank you.

### Additional

Or can I apply it immediately if I take the `copy paste` code from the util function? :?

**Comment by glenn-jocher** [comment]
@ingbeeedd yes. Major version changes coincide with architecture changes. See release notes for details:
https://github.com/ultralytics/yolov5/releases

**Comment by ingbeeedd** [comment]
@glenn-jocher 
Or can I apply it immediately if I take the **`copy paste` code** from the util function?

**Comment by glenn-jocher** [comment]
@ingbeeedd I have no idea what you're asking
