### ISSUE TITLE
python version tensorRT on yolov5

### ISSUE THREAD

**Issue by yilawu** [ultralytics/yolov5#718]
## ❔Question
yolov5 behaves better than v4.
Have you ever consider to realize the  tensorRT using the python version
like [this](https://github.com/Tianxiaomo/pytorch-YOLOv4) used in v4 which can speed up 3x-4x?
the repo https://github.com/TrojanXu/yolov5-tensorrt behaves normal just speed up 7.6％ .

**Comment by glenn-jocher** [comment]
@wurongyuan yes, there is a TensorRT Deployment section in https://docs.ultralytics.com/yolov5

**Comment by yilawu** [comment]
> @wurongyuan yes, there is a TensorRT Deployment section in https://docs.ultralytics.com/yolov5

the repo tensorrtx is c++ version which is not friendly to change model based on yolov5.
a python version using tensorrt is better.
https://github.com/Tianxiaomo/pytorch-YOLOv4
