### ISSUE TITLE
Any way to get probabilties for all classes?

### ISSUE THREAD

**Issue by RyanDoesMath** [ultralytics/yolov5#7183]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm using Bayesian inference to try to boost the classification accuracy of my model, is there some way I can configure the torch model to output a probability for all 32 of my classes?  

![output](https://user-images.githubusercontent.com/47860863/160433550-bcc22b84-f316-48f0-b39f-f5fbb8dcfd2a.jpg)
I got this output from calling results.pandas().xyxy[0], but this only contains the confidence for the highest class.

**Comment by glenn-jocher** [comment]
@RyanDoesMath you can customize the AutoShape class to handle outputs to suit your custom requirements:
https://github.com/ultralytics/yolov5/blob/d51f9b2ff6e60b7eaaafc7e8d991f0d6dbb786cd/models/common.py#L486-L571

**Comment by akashlp27** [comment]
Hi, @RyanDoesMath did you figure out how to find the all class probabilities instead of getting only the max value..?
any suggestions would help a lot
