### ISSUE TITLE
Precision and recall from confusion matrix and results.png file?

### ISSUE THREAD

**Issue by choudharynirmal** [ultralytics/yolov5#7186]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Dear Author,

I am using YOLOv5 on custom dataset. There are 4 classes in my dataset. The results calculated during the training of the model are saved in the results.csv file. The precision and recall after training is calculated by taking average of each class precision and recall values. 
Why are you calculating the average at the end and not at each epoch? 

Also, why the precision and recall computed from confusion matrix is different from the one during training process?

**Comment by glenn-jocher** [comment]
@choudharynirmal P and R are output in console at maximum F1 confidence threshold.

Confusion matrices are output at --conf 0.25 by default, settable here:
https://github.com/ultralytics/yolov5/blob/d51f9b2ff6e60b7eaaafc7e8d991f0d6dbb786cd/utils/metrics.py#L117-L119

**Comment by choudharynirmal** [comment]
Thank you for the quick reply.
As precision and recall can also be computed by confusion matrix, these values are same or different?
(I am getting different values)

**Comment by choudharynirmal** [comment]
![image](https://user-images.githubusercontent.com/84863280/160498266-f0130650-5d50-40a3-96f2-e8ecf2bb6a4e.png)

The values of P and R in console are 0.878 and 0.843 respectively.

![image](https://user-images.githubusercontent.com/84863280/160497894-d60debc7-ee8b-4cc3-a3b2-c428e4866942.png)
The maximum F1 score is 0.874 at 137th epoch. The values of P and R are 0.92 and 0.82 respectively (137th epoch).

Why there is a difference. I am using default parameters.

Although the value of mAP in console and results.csv matches (best results at epoch 174). The value of mAP is 0.88

**Comment by choudharynirmal** [comment]
![image](https://user-images.githubusercontent.com/84863280/160498994-2d08f473-9801-44e8-a850-4272014eac62.png)

This is the confusion matrix. P and R calculated from confusion matrix are different.

**Comment by glenn-jocher** [comment]
> @choudharynirmal P and R are output in console at maximum F1 confidence threshold.
> 
> Confusion matrices are output at --conf 0.25 by default, settable here:
> 
> https://github.com/ultralytics/yolov5/blob/d51f9b2ff6e60b7eaaafc7e8d991f0d6dbb786cd/utils/metrics.py#L117-L119

I explained the differences are due to due different confidence thresholds here.

**Comment by beauty-snowman** [comment]
> > @choudharynirmal P and R are output in console at maximum F1 confidence threshold.
> > Confusion matrices are output at --conf 0.25 by default, settable here:
> > https://github.com/ultralytics/yolov5/blob/d51f9b2ff6e60b7eaaafc7e8d991f0d6dbb786cd/utils/metrics.py#L117-L119
> 
> I explained the differences are due to due different confidence thresholds here.

how can i get conf

**Comment by hung-phan-van** [comment]
I get the same problem with the confusion matrix, it is too high compared with the precision and recall on the console

**Comment by RaselAmin** [comment]
Thank you all for this, I also confused abuout this confusion matrix, how calculate the accuracy from it? if Background value add then it more than 1. can we ignore the value of background? thank you

**Comment by RaselAmin** [comment]
@choudharynirmal did you calculate the accuracy from your confusion matrix. specially how did you calculate true negative value from it? thank you

**Comment by glenn-jocher** [comment]
@RaselAmin It is not recommended to calculate the accuracy from the confusion matrix because of the inclusion of the background label. Calculating the accuracy would require the sum of true positives and true negatives, which in the case of object detection, may not be relevant. In the context of object detection, the precision, recall, and F1-score are considered as more appropriate metrics since they account for both true and false positives and negatives and are calculated per class. 

In case you want to ignore the "Background" label, you can simply compute the metrics by only using the non-background label values. Hence, you will only consider TP, FP, and FN for each class other than the Background class. This will allow you to calculate the various metrics as per each class without considering the Background class.

**Comment by K-Durgeshwar** [comment]
> @choudharynirmal P and R are output in console at maximum F1 confidence threshold.
> 
> Confusion matrices are output at --conf 0.25 by default, settable here:
> 
> https://github.com/ultralytics/yolov5/blob/d51f9b2ff6e60b7eaaafc7e8d991f0d6dbb786cd/utils/metrics.py#L117-L119

so if we hard code the maximum F1 confidence threshold to the confidence threshold used to get confusion matrix , will we get the same precision , recall values for both in console and when we calculate it from confusion matrix.

**Comment by glenn-jocher** [comment]
Hey there! 😊

Yes, if you set the confidence threshold for both the console output and the confusion matrix to the same value, you should observe similar precision and recall values. Just ensure that the same threshold is used consistently during evaluation to compare the metrics accurately.

Here's a quick example on how you might adjust the confidence threshold:

```python
# Set your desired confidence threshold
conf_threshold = 0.25  # or any other value that matches your F1 max threshold

# Use this threshold when generating the confusion matrix and during evaluation
```

Just make sure to apply this threshold uniformly to maintain consistency in your evaluations!
