### ISSUE TITLE
About the use of setup.cfg

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#7190]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

@glenn-jocher 
How to use this file? I found that `setup.cfg ` contains `pytest`, `flake8`, `isort`. But I don't know how to use setup.cfg in yolov5 project?

https://github.com/ultralytics/yolov5/blob/d51f9b2ff6e60b7eaaafc7e8d991f0d6dbb786cd/setup.cfg

**Comment by glenn-jocher** [comment]
@Zengyf-CVer setup.cfg contains CI checks from various sources that can be run by pre-commit, i.e. on the last commit to master:
https://results.pre-commit.ci/run/github/264818686/1648541755.0YwlPo1YQ-a2ZJSYsIDD-A

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
Thank you very much.
