### ISSUE TITLE
YOLOv5 with DeepSort

### ISSUE THREAD

**Issue by akbarali2019** [ultralytics/yolov5#7191]
### Search before asking

- [ ] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

![image](https://user-images.githubusercontent.com/52565814/160535590-3ab15d53-8db6-40eb-aa03-98af30f9d465.png)

### Environment

YOLOv5 [https://github.com/ultralytics/yolov5.git]
Python 3.8.6
CPU

### Minimal Reproducible Example

C:\Users\admin\Desktop\deepSort\YoloV5-and-DeepSort-Custom-Dataset> python .\track.py --yolo_weights best.pt --source f1.mp4 --save-vid

### Additional

Hi! I am going to implement yolov5 with deepSort but Here it comes ValueError: too many values to unpack (expected 4)....
when I try to test. I have already pre-trained model best.pt.
I have checked related questions but this kind of error was there while training and some suggested to change batch size. But in my case it's related with testing. For what should I change or consider? Please help!

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@akbarali2019 if your error is generated by a 3rd party tool you should raise your issue directly with the authors of the tool.

**Comment by akbarali2019** [comment]
Thanks, I have fixed the problem
