### ISSUE TITLE
About output shape of prediction

### ISSUE THREAD

**Issue by spacewalk01** [ultralytics/yolov5#7193]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I would like to know the order of output prediction before passing it throught non-max suppression. Suppose we have 80 classes, then yolov5 produces 25200x85 matrix. My understanding is that 85 is a vector of x,y,w,h,object_conf,class1,class2,class3,...,class80? Is it correct?

**Comment by glenn-jocher** [comment]
Yes that's correct.
