### ISSUE TITLE
Questions about multi-GPU training

### ISSUE THREAD

**Issue by weizj0328** [ultralytics/yolov5#7199]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, the size of my custom dataset is 2048*2048, and the training parameters are kept by yolov5s default.

OS: Ubuntu 20.04
Code version：YOLOv5-v6.0
Hardware condition：NVIDIA RTX 2080Ti ×8
Environment: Python3.7，pytorch1.8.1+torchvision0.9.1+Cuda10.1

Screenshot below，When I train in DDP mode, I find that in the output log information of the terminal, at the beginning of the first epoch, "**Reducer buckets have been rebuilt in this iteration**" is output,and the calculation speed dropped from 6.87 to 1.23it/s, it seems to have a great impact on the overall training speed, I don't know if this will affect the performance of the final model.
![0329](https://user-images.githubusercontent.com/73020982/160606179-8bfad9b7-1496-4d84-aab3-b2e2ab43cd09.png)

### Additional

However, I checked the information on the Internet, and it was mentioned that this was because of the torch version. The distributed.py above torch1.7 was changed, resulting in an error, but yolo requires torch>=1.7.0, I don't know how to modify it to improve Training speed without compromising model performance.

**Comment by glenn-jocher** [comment]
@weizj0328 you're misreading the speeds. 1.23it/s is much faster than 6.87s/it

**Comment by weizj0328** [comment]
> Reducer buckets have been rebuilt in this iteration

Thanks for your reply, will "Reducer buckets have been rebuilt in this iteration" affect the model performance, do I need to modify it?

**Comment by jimmyflycv** [comment]
same question here.

**Comment by xarryon** [comment]
> > Reducer buckets have been rebuilt in this iteration
> 
> Thanks for your reply, will "Reducer buckets have been rebuilt in this iteration" affect the model performance, do I need to modify it?

hi, have you found it affects the performance?

**Comment by weizj0328** [comment]
> > > Reducer buckets have been rebuilt in this iteration
> > 
> > 
> > Thanks for your reply, will "Reducer buckets have been rebuilt in this iteration" affect the model performance, do I need to modify it?
> 
> hi, have you found it affects the performance?

This problem appeared throughout my experiment, and no solution was found. As for performance, I don't see a big impact.

**Comment by glenn-jocher** [comment]
@weizj0328 thanks for reporting the issue. The "Reducer buckets have been rebuilt in this iteration" message is related to the PyTorch DDP backend. It's a general informational message and shouldn't directly impact model performance. It's good to hear that you haven't noticed a significant impact on performance. This could be related to the internals of PyTorch's DistributedDataParallel and might not need modification on your end.

If you have further concerns or questions, feel free to let us know. Good luck with your experiments!
