### ISSUE TITLE
training on my data error

### ISSUE THREAD

**Issue by tangxiaochu123230** [ultralytics/yolov5#72]
Traceback (most recent call last):
  File "C:/projects/YOLOV5/yolov5/train.py", line 401, in <module>
    train(hyp)
  File "C:/projects/YOLOV5/yolov5/train.py", line 204, in train
    check_best_possible_recall(dataset, anchors=model.model[-1].anchor_grid, thr=hyp['anchor_t'])
  File "C:\projects\YOLOV5\yolov5\utils\utils.py", line 64, in check_best_possible_recall
    'Compute new anchors with utils.utils.kmeans_anchors() and update model before training.' % bpr
AssertionError: Best possible recall 0.704 (BPR) below 0.9 threshold. Training cancelled. Compute new anchors with utils.utils.kmeans_anchors() and update model before training.

**Comment by glenn-jocher** [comment]
@tangxiaochu123230 yes, exactly as the error message says, your anchors are a bad fit for your data. You need to evolve new anchors, update your model, and then train.

> AssertionError: Best possible recall 0.704 (BPR) below 0.9 threshold. Training cancelled. Compute new anchors with utils.utils.kmeans_anchors() and update model before training.

**Comment by tangxiaochu123230** [comment]
I cal the anchors by run the kmean_acnchors
0.20 iou_thr: 0.994 best possible recall, 6.58 anchors > thr
n=9, img_size=(640, 640), IoU_all=0.363/0.776-mean/best, IoU>thr=0.449-mean: 677,310,  1361,193,  1396,337,  690,939,  1391,608,  695,1730,  1385,1051,  2130,814,  1416,1674
but the probleam still exists

**Comment by glenn-jocher** [comment]
@tangxiaochu123230 perfect! You need to place your calculated anchors in your model yaml, updating the old ones:

https://github.com/ultralytics/yolov5/blob/db2c3acd3ab836ae0bbc9f7391f839d1480a8c1e/models/yolov5s.yaml#L6-L11

**Comment by tangxiaochu123230** [comment]
yeah,I just update the anchors in my yaml file
like this
anchors:
  - [677,310,  1361,193,  1396,337]  # P3/8
  - [690,939,  1391,608,  695,1730]  # P4/16
  - [1385,1051,  2130,814,  1416,1674]  # P5/32

still not work

**Comment by tangxiaochu123230** [comment]
or shall I scal these anchors to 640

**Comment by tangxiaochu123230** [comment]
hall I scale these anchors to 640

**Comment by tangxiaochu123230** [comment]
shall I scal these anchors to 640

**Comment by tangxiaochu123230** [comment]
shall I scale these anchors to 640

**Comment by glenn-jocher** [comment]
Yes I think it’s a scaling issue, perhaps the check is not accounting for training img size, I will look at this later today.

**Comment by tangxiaochu123230** [comment]
could I canceled checking anchors

**Comment by glenn-jocher** [comment]
@tangxiaochu123230 yeah sure, you can just comment out these lines for now!

**Comment by glenn-jocher** [comment]
@tangxiaochu123230 I pushed a fix for this hopefully. Can you try to git pull and start training again with your updated anchors?

You should hopefully see the the AutoAnchor recall value similar to what the kmeans file showed you.

**Comment by glenn-jocher** [comment]
Eventually I want to actually have this generate new anchors automatically, but for now it's simply a check and a warning when the current anchors are a poor match to the data. I think this will help a lot of people.

**Comment by tangxiaochu123230** [comment]
ok，I will pull the code later soon
