### ISSUE TITLE
Support for FUSE v2

### ISSUE THREAD

**Issue by jyrr** [ultralytics/yolov5#7201]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hiya,

I am running YOLOv5 in a Databricks environment. I am writing the results to DBFS (Databricks File System) which uses FUSE v2 under the hood. FUSE v2 does not support direct appends, thus the writes to the results & evolve csv's fail for me:

https://github.com/ultralytics/yolov5/blob/cf4f3c3455d14c62e11dcce9f1d30211509da72f/utils/loggers/__init__.py#L120-L122

https://github.com/ultralytics/yolov5/blob/cf4f3c3455d14c62e11dcce9f1d30211509da72f/utils/general.py#L832-L834

I've worked around this by reading and loading the files via pandas. E.g. for the logger;
```
s = [] if file.exists() else list(['epoch'] + self.keys) # header
results_data = [epoch] + [val.item() if isinstance(val, torch.Tensor) else val for val in vals]
            
if not s:
    results = pd.read_csv(file)
    results.loc[len(results)] = results_data
else:
   results = pd.DataFrame(data=[tuple(results_data)], columns=s)
results.to_csv(file, index=False)
```

Now my question is, is this something I can submit a PR for? I understand there is no 'official' support for Databricks, yet this would help me out and would avoid me having to make any changes to make YOLOv5 compatible on Databricks.

Thanks!

**Comment by glenn-jocher** [comment]
@jyrr hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

Yes please submit a PR so we can test and profile your proposed changes.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
