### ISSUE TITLE
export to saved_model with --nms flag yields incorrect/incomplete results.

### ISSUE THREAD

**Issue by tylertroy** [ultralytics/yolov5#7205]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Export

### Bug

Relates to two issues resulting from exporting exporting to saved_model with the `--nms` flag set.

1. Output from model has no data for classes and scores
2. 100 boxes are returned with `--nms` flag compared to 4 boxes (2 persons, 2 ties) without `--nms` flag 

After exporting with the command
```bash
python export.py --weights yolov5s.pt --include saved_model --nms
```
The output from `saved_model_cli` shows the following inputs/outputs
```bash
signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['x'] tensor_info:
        dtype: DT_FLOAT
        shape: (1, 640, 640, 3)
        name: serving_default_x:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['output_0'] tensor_info:
        dtype: DT_FLOAT
        shape: (1, 100, 4)
        name: PartitionedCall:0
  Method name is: tensorflow/serving/predict
WARNING:absl:Importing a function (__inference_pruned_7064) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
```
This indicates that the output is a tensor of 100 rows of bbox data. Visualization of these output boxes shows:

```bash
python export.py --weights yolov5s.pt --include saved_model --nms
python test_serve.py  # Here test_serve uses the tensroflow serve restful API
```
![image](https://user-images.githubusercontent.com/17804750/160708555-6b6d7e3e-4b82-4a87-980f-a3a48c5bf947.png)

I have confirmed that the export function works perfectly well with no nms when doing inference with `detect.py`

Output from model with no nms using:
```bash
python export.py --weights yolov5s.pt --include saved_model
python detect.py --weights yolov5s_saved_model/ --source data/images/zidane.jpg
```
![image](https://user-images.githubusercontent.com/17804750/160676855-3469bf35-785d-4255-8c83-52f349eafa17.png)

### Environment

- YOLOv5 🚀 v6.1-74-gcf4f3c3 torch 1.11.0+cu113 CPU
- Ubuntu 18.04 LTS
- Python 3.8

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by tylertroy** [comment]
I have found part 2 of my issue was due to operator error whereby input was not normalized to 255. I am now getting sensible output (See rectified output image below) but part 1 whereby no classes or scores are returned still remains an issue. 

![image](https://user-images.githubusercontent.com/17804750/160714796-0c0663ba-04ec-4d8c-aeff-103829eaf86d.png)

Edit: I will note that the ties have not been detected but it's possible that there is a difference in thresholds between detect.py and what is exported.

**Comment by tylertroy** [comment]
I managed to solve the part 1 issue with the following edit to `export.py`

```bash
diff --git a/export.py b/export.py
index 7517dc4..0404b25 100644
--- a/export.py
+++ b/export.py
@@ -276,7 +276,7 @@ def export_saved_model(model, im, file, dynamic,
             m = m.get_concrete_function(spec)
             frozen_func = convert_variables_to_constants_v2(m)
             tfm = tf.Module()
-            tfm.__call__ = tf.function(lambda x: frozen_func(x)[0], [spec])
+            tfm.__call__ = tf.function(lambda x: frozen_func(x)[:4], [spec])
             tfm.__call__(im)
             tf.saved_model.save(
                 tfm,
```
And this results in the following inputs/outputs as visualized with

```bash
$ saved_model_cli show --dir yolov5s_saved_model/ --signature_def serving_default --tag serve
The given SavedModel SignatureDef contains the following input(s):
  inputs['x'] tensor_info:
      dtype: DT_FLOAT
      shape: (1, 640, 640, 3)
      name: serving_default_x:0
The given SavedModel SignatureDef contains the following output(s):
  outputs['output_0'] tensor_info:
      dtype: DT_FLOAT
      shape: (1, 100, 4)
      name: PartitionedCall:0
  outputs['output_1'] tensor_info:
      dtype: DT_FLOAT
      shape: (1, 100)
      name: PartitionedCall:1
  outputs['output_2'] tensor_info:
      dtype: DT_FLOAT
      shape: (1, 100)
      name: PartitionedCall:2
  outputs['output_3'] tensor_info:
      dtype: DT_INT32
      shape: (1)
      name: PartitionedCall:3
Method name is: tensorflow/serving/predict
```

I'm still having an issue whereby output is different between detect.py and results from tfserve but I will raise this in a separate issue if I can't find a solution in the existing issues.

I will leave closing of this issue to the authors in case they would like to  incorporate the fix in `export.py`.

**Comment by glenn-jocher** [comment]
@tylertroy hi, thank you for your feature suggestion on how to improve YOLOv5 🚀! It looks like you've uncovered a bug and implemented and tested a fix. Would you like to submit a PR to receive credit for this?

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
