### ISSUE TITLE
Why flipping is imposed in copy_paste?

### ISSUE THREAD

**Issue by cissoidx** [ultralytics/yolov5#7211]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

In the copy_paste [paper](https://arxiv.org/pdf/2012.07177.pdf), it says:

> We randomly select two images and apply random scale jittering and random horizontal flipping
> on each of them. 

But in the code, https://github.com/ultralytics/yolov5/blob/cf4f3c3455d14c62e11dcce9f1d30211509da72f/utils/augmentations.py#L213

flipping is always performed. Is it a bug or it is done by purpose?

**Comment by glenn-jocher** [comment]
@cissoidx we always flip lr on purpose, as the original segment is already present unflipped.

We do not have scale jitter in place though, this would be a useful addition to our copy-paste implementation if you are looking for a way to contribute to the project.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by cissoidx** [comment]
Thanks for reply. What does `flip lr` mean?

**Comment by glenn-jocher** [comment]
flip left-right

**Comment by cissoidx** [comment]
And moreover, afaik, copy paste is between different images. But in your implementation, the segment is just flipped within the same image and then pasted to the original image. Am I understanding it correctly?

**Comment by glenn-jocher** [comment]
@cissoidx same mosaic, different images.

**Comment by cissoidx** [comment]
Thanks. So copy_paste is binded with mosaic. I mean copy_paste is only applied in the mosaic augmented image. And when it is flipped, the segment goes to the other side of the image, which is a different sub image.

**Comment by glenn-jocher** [comment]
Yes!
