### ISSUE TITLE
Color channels are swapped if it is not BGR while cropping

### ISSUE THREAD

**Issue by caksoy** [ultralytics/yolov5#7213]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

As a result of the forward function of the `AutoShape` class, the `Detections` object is returned.
If `crop` is `True` in the `display` function of the Detections class, the `save_one_box` function is called and the original image is cropped according to the predicted box coordinates.

In the `save_one_box` function, while cropping the image, it is decided whether or not the color channels in the cropped image will be swapped based on the boolean BGR parameter control.

The relevant code snippet is below:
```crop = im[int(xyxy[0, 1]):int(xyxy[0, 3]), int(xyxy[0, 0]):int(xyxy[0, 2]), ::(1 if BGR else -1)]```

If the original image is not BGR (e.g. RGB), the value returned by this function (save_one_box) is BGR even if the rest of the pipeline will work as the original image (RGB). This may cause some side effects. The expected behavior is that the returned value should be RGB if BGR is set to False.

If `save` is True while saving the cropped image as a PIL image, the cropped image which is converted to BGR, is converted back to RGB and then saved.

The relevant code snippet is below:
```
if save:
file.parent.mkdir(parents=True, exist_ok=True)  # make directory
        f = str(increment_path(file).with_suffix('.jpg'))
        # cv2.imwrite(f, crop)  # https://github.com/ultralytics/yolov5/issues/7007 chroma subsampling issue
        Image.fromarray(cv2.cvtColor(crop, cv2.COLOR_BGR2RGB)).save(f, quality=95, subsampling=0)
```

### Environment

- YOLO: YOLOv5 v6.1 (and previous versions)
- CPU and CUDA (NVIDIA Tesla V100)
- MacOS 12.2.1 and Ubuntu 18.04
- Python 3.9
- PyTorch 1.10.1

### Minimal Reproducible Example

```
import torch
import matplotlib.pyplot as plt

model = torch.hub.load(".",
                       model="yolov5s",
                       source="local",
                       device="cpu")
out = model.forward("data/images/zidane.jpg")
crop_out = out.crop(save=False)
plt.imshow(crop_out[1]["im"])
```

<img width="309" alt="image" src="https://user-images.githubusercontent.com/54771201/160816165-7b3a298f-5be9-47a3-bb3a-55c0c9e97253.png">

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Zengyf-CVer** [comment]
@caksoy 

It's not a bug, it's because you didn't do a color mode conversion:
```python
img = cv2.imread('zidane.jpg')[..., ::-1]  # OpenCV image (BGR to RGB)
```
