### ISSUE TITLE
how to use android phone as web cam in detection?

### ISSUE THREAD

**Issue by VYRION-Ai** [ultralytics/yolov5#7214]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

my PC didn't have web cam , i want to use my android phone as web cam and use it in detection ? how to do this
i try different ways but it didn't work?

**Comment by glenn-jocher** [comment]
@totoadel we should an android app released soon! In the meantime we have an iOS app at https://apps.apple.com/us/app/idetection/id1452689527

**Comment by glenn-jocher** [comment]
@SergioSanchezMontesUAM

**Comment by VYRION-Ai** [comment]
> @totoadel we should an android app released soon! In the meantime we have an iOS app at https://apps.apple.com/us/app/idetection/id1452689527

This is a great news,  i am so happy to hear that.
But i need to use phone as webcam just that.
I will use my pc + phone 
Or raspberry + phone

**Comment by Guttappa1238** [comment]
HI @totoadel If want to use phone camera for detection, install  `IP Webcam` android app it will generate IP address use that ip address to run detect.py 

hope it helps!

**Comment by VYRION-Ai** [comment]
@Guttappa1238 thank you,
But i need to use USB not IP address,is there any way to make it work using USB

**Comment by Guttappa1238** [comment]
> @Guttappa1238 thank you, But i need to use USB not IP address,is there any way to make it work using USB

To use USB try like this:
 https://www.reliancedigital.in/solutionbox/how-to-use-your-smartphone-as-a-webcam-using-droidcam/?gclid=CjwKCAjwopWSBhB6EiwAjxmqDTDFFJ6yE_5jSe48KZaGsI7UOr0J-9HOrCh86dLq8Du8_rb0y0tefhoCs-gQAvD_BwE

- Install Droid Cam
- Enable USB Debugging
- Connected camera via USB to your computer
