### ISSUE TITLE
Excel Report

### ISSUE THREAD

**Issue by anusriesto** [ultralytics/yolov5#7223]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hey ! I want to know that how using FLASK and Pytorch  we can create excel report

**Comment by glenn-jocher** [comment]
@anusriesto 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

Pandas outputs might be used for onward export to Excel, I'm not sure but that seems like the easiest route if it's possible. See Pandas docs.

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, etc.
# model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')  # custom trained model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by saktheeswaranswan** [comment]
happy news problem solved  but subscribe to  random neural monk  YouTube channel  this works without showing perrmission 13 error so enjoy to log csv with time stamp class id also made with chat gpt took 6 hours

https://github.com/saktheeswaranswan/yolov5-csv-yolov5excel-crop-needs-yolov5-rasberrypi-GPIO

**Comment by glenn-jocher** [comment]
@saktheeswaranswan i'm glad to hear that your problem has been resolved! If you found a solution on the Random Neural Monk YouTube channel, that's great. However, please note that the YOLOv5 community and the Ultralytics team cannot take responsibility for any errors or issues that may arise from external sources.

If you have any further questions or need assistance with YOLOv5, feel free to ask. We're here to help!

Thank you for your support and for being a part of the YOLOv5 community.

**Comment by saktheeswaranswan** [comment]
Thank you for replying sir the world is being taken over by ChatGPT large
language models but even tough benchmarking is a big deal with some
automation in database connectivity I won't trouble ultralytics team
because this is a seperate code snippet helping the project sir but still
hats of to your time and dedication sir since it's an open source I will
take care of any problem as far as I can from this branch of error code I
made yes autonomous ai system are a big deal now sir I don't have to tell
you more about that since you are already a master on this and the above
codes are to aid help and better ment of open source community sir yolov5
with ultralytics is a game changer

**Comment by glenn-jocher** [comment]
@saktheeswaranswan thank you for your kind words and appreciation. I'm glad to hear that you found the solution helpful and that you are taking care of any issues that may arise from the code snippet you created. We appreciate your dedication to the open-source community and your support for YOLOv5.

If you ever have any further questions or need assistance with YOLOv5, feel free to reach out. We're always here to help.

Thank you for being a part of the YOLOv5 community.
