### ISSUE TITLE
YOLOv5 using RPI Camera and Flask camera live stream

### ISSUE THREAD

**Issue by Averen19** [ultralytics/yolov5#7226]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I'm using a Raspberry Pi and camera to stream using Flask. I would like to do the detection on my PC. The first method that I tried  was to use --source http link as seen below, but it doesn't work as it shows the following message. I assumed that the source webpage could work on any website. The second method I'm trying to do is to screen capture the webpage to do the detection in real time, but I'm not sure what the code for screen capturing is.

I desperately need help, any guidance would be appreciated. Thank you. 
![image_2022-03-31_210514](https://user-images.githubusercontent.com/93975422/161061429-eef2f8be-50b8-4cc9-8ebb-afd8bf63d2d0.png)

**Comment by glenn-jocher** [comment]
@Averen19 stream addresses must be valid.

See PyTorch Hub [tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for screen capture inference example:

<img width="835" alt="Screenshot 2022-03-31 at 15 41 53" src="https://user-images.githubusercontent.com/26833433/161068991-da61620e-9b50-45eb-b353-ff7b32802217.png">

**Comment by Averen19** [comment]
What do you mean by valid? I have tried this tutorial, but I'm not sure where the result is shown.
![image_2022-03-31_214553](https://user-images.githubusercontent.com/93975422/161070183-1d989f3b-797d-4bc8-8812-85881bf3ba2e.png)

**Comment by glenn-jocher** [comment]
@Averen19 a correctly working stream address, i.e.
```python
python detect.py --source 'rtsp://ipcam.stream:8554/bars'
```

Invalid streams are naturally not within the scope of our support.

**Comment by oes5756** [comment]
@Averen19
can you success raspberry pi & camera yolov5 live video to streaming ?
