### ISSUE TITLE
#Android support

### ISSUE THREAD

**Issue by daggarwal01** [ultralytics/yolov5#723]
Does the YoloV5 weights (which are converted to .tflite format) are supported in android, for tensorflow lite implementation.

**Comment by glenn-jocher** [comment]
@daggarwal01 export pipeline is pytorch > onnx > tflite. See the tutorials to get started: https://docs.ultralytics.com/yolov5

**Comment by daggarwal01** [comment]
I tried converting the weights using this pipeline,I succeed in converting it from .pt to .onnx and then to .pb, but while converting it into .tflite using the below mention code ,it showed me error. I looked for all the options but still stuck.

# Convert the model.
converter = tf.lite.TFLiteConverter.from_frozen_graph("./models/model_simple.pb",input_arrays=['main_input'],output_arrays=['main_output'])
tf_lite_model = converter.convert()

# Save the TF Lite model.
open('.models/model_simple.tflite', 'wb').write(tf_lite_model)

with tf.io.gfile.GFile('model.tflite', 'wb') as f:
 f.write(tflite_model)

**Comment by glenn-jocher** [comment]
@daggarwal01 since this error was generated by external packages, the best place to raise an issue and ask questions regarding your error is on the relevant package repo.
