### ISSUE TITLE
To get output video saved every thirty second after detection with rtsp camera input

### ISSUE THREAD

**Issue by kumar665manjeet** [ultralytics/yolov5#7232]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hi 
I need to get output video saved every thirty second till quitting the video stream...

    1. Capture video continuously until 'q; is pressed
    2. Every thirty seconds save the video in specified path
    3. Continue step two until 'q' is pressed

I have tried below code, but not getting, what i need, thanks

### Additional

# Save results (image with detections)
            start = time.time()
            #count = 1
            if save_img:
                #print('11')
                if dataset.mode == 'image':
                    cv2.imwrite(save_path, im0)
                ##################
                       
                else:  # 'video' or 'stream'
                    if vid_path[i] != save_path:  # new video
                        vid_path[i] = save_path
                        start_time = time.time()
                        #print('2')
                        if isinstance(vid_writer[i], cv2.VideoWriter):
                            vid_writer[i].release()  # release previous video writer
                            
                        if vid_cap:  # video
                            if time.time() - start > 10:
                                start = time.time()
                                fps = vid_cap.get(cv2.CAP_PROP_FPS)
                                w = int(vid_cap.get(cv2.CAP_PROP_FRAME_WIDTH))
                                h = int(vid_cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
                            
                            else:  # stream
                                fps, w, h = 30, im0.shape[1], im0.shape[0]
                        
                        save_path = str(Path(save_path).with_suffix('.mp4'))  # force *.mp4 suffix on results videos
                        vid_writer[i] = cv2.VideoWriter(save_path, cv2.VideoWriter_fourcc(*'mp4v'), fps, (w, h))
                        #print("7")
                    vid_writer[i].write(im0)

**Comment by kumar665manjeet** [comment]
> ### Search before asking
> 
>     * [x]  I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.
> 
> 
> ### Question
> 
> hi I need to get output video saved every thirty second till quitting the video stream...
> 
> ```
> 1. Capture video continuously until 'q; is pressed
> 2. Every thirty seconds save the video in specified path
> 3. Continue step two until 'q' is pressed
> ```
> 
> I have tried below code, but not getting, what i need, thanks
> ### Additional
> # Save results (image with detections)
> 
> ```
>         start = time.time()
>         #count = 1
>         if save_img:
>             #print('11')
>             if dataset.mode == 'image':
>                 cv2.imwrite(save_path, im0)
>             ##################
>                    
>             else:  # 'video' or 'stream'
>                 if vid_path[i] != save_path:  # new video
>                     vid_path[i] = save_path
>                     start_time = time.time()
>                     #print('2')
>                     if isinstance(vid_writer[i], cv2.VideoWriter):
>                         vid_writer[i].release()  # release previous video writer
>                         
>                     if vid_cap:  # video
>                         if time.time() - start > 10:
>                             start = time.time()
>                             fps = vid_cap.get(cv2.CAP_PROP_FPS)
>                             w = int(vid_cap.get(cv2.CAP_PROP_FRAME_WIDTH))
>                             h = int(vid_cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
>                         
>                         else:  # stream
>                             fps, w, h = 30, im0.shape[1], im0.shape[0]
>                     
>                     save_path = str(Path(save_path).with_suffix('.mp4'))  # force *.mp4 suffix on results videos
>                     vid_writer[i] = cv2.VideoWriter(save_path, cv2.VideoWriter_fourcc(*'mp4v'), fps, (w, h))
>                     #print("7")
>                 vid_writer[i].write(im0)
> ```

No Reply....

**Comment by kumar665manjeet** [comment]
got the output...

**Comment by IramBashir** [comment]
how? @kumar665manjeet

**Comment by afzixhaikh** [comment]
> got the output...

Can you share your code?

**Comment by glenn-jocher** [comment]
@afzixhaikh glad to hear you got the output you were looking for! If you need any further assistance or want to share your code, feel free to let us know. We're here to help!
