### ISSUE TITLE
val.py when I set argument task to test, KeyError occured.

### ISSUE THREAD

**Issue by MheadHero** [ultralytics/yolov5#7234]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I try to use val.py and set the task to test, so I can see the test batch image but **KeyError: 'test'** occurred
Below is the command I wrote, anyone can notice what error in it?

**!python ./yolov5/val.py --img 320 --batch 64 --data './data/data.yaml' --weights ./yolov5/runs/train/exp/weights/best.pt --task test**

Below is the error I got.
![image](https://user-images.githubusercontent.com/24875124/161176210-4a175e34-99e2-4d6e-a6fc-e90cab2191c8.png)

**Comment by glenn-jocher** [comment]
@MheadHero --task test will run metrics on your test set, if you have one. You do not have a test set defined in your data.yaml, so what exactly are you expecting val.py to do here?
