### ISSUE TITLE
How I edit python.py for always save label(text) after I detection finished by not typing --save-txt. 

### ISSUE THREAD

**Issue by BenzKukkik** [ultralytics/yolov5#7236]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'd like to consult, How I edit python.py for always save label(text) after I detection finished by not typing --save-txt.

Thank you so much. Please supporting me.

**Comment by BenzKukkik** [comment]
Please support me. I have to use this for my work.

**Comment by warpcut** [comment]
Just edit the default argument at line 60 of detect.py (what is python.py?)
https://github.com/ultralytics/yolov5/blob/32661f75ac6eaa8c5dfd0ad36abfaa8d4e4fe700/detect.py#L60
And set it to `True`

**Comment by glenn-jocher** [comment]
@warpcut hi there,

Thanks for reaching out! To always save the text labels after detection without typing --save-txt, you can modify the default argument at line 60 of detect.py. You'll need to set it to `True` to achieve this.

I hope this helps! Let me know if you have further questions or need additional assistance.

Best regards
