### ISSUE TITLE
--svae-txt -> I want to keep saving with the same name.

### ISSUE THREAD

**Issue by jangjh45** [ultralytics/yolov5#7237]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is there a way to keep overwriting the txt output with the same name?

**Comment by glenn-jocher** [comment]
@jangjh45 I'm not sure what you mean, but in general label txt files are created once per image upon inference of the image. You can use --save-hybrid with val.py to combine existing dataset labels with new inference results, i.e. to autolabel a partially labelled dataset.
