### ISSUE TITLE
The effect difference caused by the image size

### ISSUE THREAD

**Issue by adonisyang999** [ultralytics/yolov5#7239]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When I use 1920 x1080 images for training, the corresponding Settings image_size for 768, after the training, I through the same camera, the same scene obtained 1920 x1080, 1280 x720, 640 x360 and 640 x480 tested respectively the four image size, The results showed that 640x360 and 640x480 were generally better than 1920x1080 and 1280x720. What's the reason for this? If the normal situation is when I train with 1920x1080 data, then I get better results by testing consistency with 1920x1080 images.

**Comment by glenn-jocher** [comment]
@adonisyang999 every dataset is different, but on COCO models trained at 1280 perform best at 1280, and a little worse at 640. 

Models can be used for inference at their training size or smaller, but not larger.
