### ISSUE TITLE
Only evolving certain hyperparameters?

### ISSUE THREAD

**Issue by tserdar** [ultralytics/yolov5#7240]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is it possible to subselect certain hyperparameters and only run evolution for them?

**Comment by glenn-jocher** [comment]
@rocketsfallonrocketfalls yes, you can set the mutation scale of any hyp you want to hold constant (not evolve) in the `meta` dict to 0.0 to prevent it from evolving.
https://github.com/ultralytics/yolov5/blob/71621df87589faea19ba4c4098bb68e73201f30c/train.py#L564-L595

**Comment by tserdar** [comment]
Thanks!
