### ISSUE TITLE
Is there a way to get the top 5 categories per bounding box without having to directly download and alter the YOLOv5 code/network?

### ISSUE THREAD

**Issue by isabellepchong** [ultralytics/yolov5#7243]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am trying to implement a feature using YOLOv5 that will allow me to output the top 5 possible classifications of a given bounding box in an image and provide them to a user to choose from. I was wondering if there was a way to do this using YOLO as a black box? Or if not, and I have to change something about the code, what that change would have to be?

Thanks!

**Comment by glenn-jocher** [comment]
@isabellepchong NMS selects the most likely class for each box to know which class to compare a given box against all other boxes for suppression:
https://github.com/ultralytics/yolov5/blob/37675e110f3d2635dbc3acc8794e782c452e4ad5/detect.py#L120-L129

You can access the class probabilities and customize a workflow there in the NMS function:
https://github.com/ultralytics/yolov5/blob/37675e110f3d2635dbc3acc8794e782c452e4ad5/utils/general.py#L715-L728

**Comment by isabellepchong** [comment]
> @isabellepchong NMS selects the most likely class for each box to know which class to compare a given box against all other boxes for suppression:
> 
> https://github.com/ultralytics/yolov5/blob/37675e110f3d2635dbc3acc8794e782c452e4ad5/detect.py#L120-L129
> 
> You can access the class probabilities and customize a workflow there in the NMS function:
> 
> https://github.com/ultralytics/yolov5/blob/37675e110f3d2635dbc3acc8794e782c452e4ad5/utils/general.py#L715-L728

This would mean that, rather than using the torch.hub implementation, I would have to download the yolov5 repository locally, correct? Thanks again!

**Comment by glenn-jocher** [comment]
@isabellepchong yes, you'd want to clone the repo locally to experiment with customizing the code to suit your requirements.

You can always point PyTorch Hub to your local copy of the repo also, i.e.:

<img width="830" alt="Screenshot 2022-04-02 at 00 12 17" src="https://user-images.githubusercontent.com/26833433/161347893-35887355-d46a-41cb-b1c9-1625e7be6ce5.png">

See [PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

**Comment by isabellepchong** [comment]
Thanks, that helps a lot~!

**Comment by yukiakira269** [comment]
@isabellepchong Hello, have you managed to solve this? 
I'm relatively new to YOLO so I don't really know the right direction to take when it comes to modifying the nms function.
