### ISSUE TITLE
Problem about training results

### ISSUE THREAD

**Issue by Miho-an-kou** [ultralytics/yolov5#7244]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Can anyone point out any possible reasons for this bad result？
![confusion_matrix](https://user-images.githubusercontent.com/72844292/161366764-c085217c-1c3e-4a41-8f31-2835df6fc949.png)
![labels](https://user-images.githubusercontent.com/72844292/161366765-c20397ce-1e34-400d-bee2-464710730698.jpg)
![labels_correlogram](https://user-images.githubusercontent.com/72844292/161366766-57d2740c-1343-4e81-8463-7d4da62d0d6e.jpg)
![precision_recall_curve](https://user-images.githubusercontent.com/72844292/161366767-3a6b2fe1-4730-453d-a7de-3623bd350513.png)
![results](https://user-images.githubusercontent.com/72844292/161366769-040e359a-40f8-4d61-a8f5-1deb153a28aa.png)

**Comment by glenn-jocher** [comment]
@Miho-an-kou if your train batch jpgs look correct, then you may have CUDA version incompatibilities that sometimes affect Windows/Conda/CUDA11 environments. Typically downgrading to CUDA 10 resolves the issue. I would do a search of the issues for 'no detections'.

**Comment by glenn-jocher** [comment]
@Miho-an-kou also disabling AMP everywhere may also resolve the CUDA11 issues.

**Comment by Miho-an-kou** [comment]
> @Miho-an-kou also disabling AMP everywhere may also resolve the CUDA11 issues.

I tried training with environment of cuda 10, it works well, thank you very much

**Comment by glenn-jocher** [comment]
@Miho-an-kou great!
