### ISSUE TITLE
save_txt -> Is it possible to save the coordinates of the txt file to the 2nd decimal point?

### ISSUE THREAD

**Issue by jangjh45** [ultralytics/yolov5#7245]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question
Hello, I have an urgent question.
save_txt -> Is it possible to save the coordinates of the txt file to the 2nd decimal point?
I need decimal coordinates of the same length.

0 0.538281 0.29375 0.435937 0.429167  -->  0 0.54 0.29 0.44 0.43

**Comment by glenn-jocher** [comment]
@jangjh45 modify detect.py:
https://github.com/ultralytics/yolov5/blob/37675e110f3d2635dbc3acc8794e782c452e4ad5/detect.py#L158-L165

**Comment by jangjh45** [comment]
thank you. I'll edit it and let you know if I have any questions.

**Comment by glenn-jocher** [comment]
@jangjh45 you're welcome! Feel free to reach out if you have any further questions. Good luck with the editing!
