### ISSUE TITLE
Can we create a mask branch for yolov5?

### ISSUE THREAD

**Issue by DinhTus49** [ultralytics/yolov5#7250]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello I am so sorry to bother if my following question is too silly and impractical,
I would like to ask if it is possible to create a mask branch for yolov5? For example, we can do the same as mask rcnn, but instead of using RoI from RPN we can use bounding boxes detected from yolov5 belonging to feature map to generate RoI for mask branch.

**Comment by glenn-jocher** [comment]
@DinhTus49 hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
