### ISSUE TITLE
Metric graph export

### ISSUE THREAD

**Issue by Gary-Ng** [ultralytics/yolov5#7253]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

If i have a total of 14 classes in my dataset and the default f1 curve and mAP plots for all classes. How can i change it such that it only plot according to the classes that i want.

### Additional

Default
1. bicycle
2. bike
3. boat
4. bus
5. car
6. cng
7. easybike
8. horsecart
9. leguna
10. rickshaw
11. tractor
12. truck
13. van
14. wheelbarrow

I want 

1. car
2. bike
3. bicycle
4. truck
5. bus

**Comment by glenn-jocher** [comment]
@Gary-Ng metrics apply to all classes in your dataset. Feel free to modify metrics to your custom requirements yourself:
https://github.com/ultralytics/yolov5/blob/master/utils/metrics.py

**Comment by Gary-Ng** [comment]
@glenn-jocher thank you but any advice on how to go about doing that? I am thinking the target_cls but am unsure of what data type to provide. Am i supposed to provide the id of the class in my .yaml file?

**Comment by glenn-jocher** [comment]
@Gary-Ng You can filter the metrics using the `names` argument in the `plot` method in `utils/metrics.py`. For instance, to plot only for 'car', 'bike', 'bicycle', 'truck', and 'bus', you can use `plot(names=('car', 'bike', 'bicycle', 'truck', 'bus'))`. The names should match those in your .yaml file.
