### ISSUE TITLE
Extract and work on detected image without saving

### ISSUE THREAD

**Issue by niranjan4r** [ultralytics/yolov5#7260]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hey, 

I am working on a License plate recognition project and am exploring Yolo v5 to detect vehicles. 

In my workflow, I am first detecting vehicles using Yolo v5 and then extracting the detected vehicle images and searching for license plates in them. Currently I am accessing the vehicle images from the runs/detect/ directory after running `results.crop()`.

Therefore, to save computational time and energy, is there a way to use the detected vehicle images directly without first saving them? Is there any method that I can apply on the 'results' variable after running `results = model(frame)` to get the detected vehicle images?

**Comment by glenn-jocher** [comment]
@niranjan4r yes of course:
```python
crops = results.crop(save=False)
```

**Comment by niranjan4r** [comment]
@glenn-jocher Thanks for the reply.

Now, how do I use the original image annotated with bounding boxes? 
That is, if I used the "save" option, I can get the annotated image from runs/detect/exp folder. Similarly say, I want to display the annotated image using cv2.imshow(). How do I do that using the 'crops' variable?

**Comment by glenn-jocher** [comment]
Display annotated image with `results.show()`

**Comment by niranjan4r** [comment]
@glenn-jocher thank you. Unfortunately show() function doesn't work on Google Colab. 
Also, is there a way to get the annotated image as a cv2 image? 
I am reading a video frame by frame using cv2, applying preprocessing and then detecting objects using Yolo. And then trying to write it back as an output video using `cv2.VideoWriter`. However cv2.VideoWriter can only take "cv2 format images".
Is it possible to convert the 'results' to cv2 image.
Thanks

**Comment by glenn-jocher** [comment]
@niranjan4r for fully managed video inference:
```
python detect.py --source video.mp4
```

**Comment by niranjan4r** [comment]
@glenn-jocher Thanks, but I am aware of the fully managed video inference and that's not something I am looking for. 

Let me illustrate my workflow:

1. Read input video frame by frame
2. Detect objects (vehicles in my project) from the current frame.
3. Use another model to detect license plates from the detected vehicles.
4. Recognize the license plate characters.
5. Take the annotated result frame and add a few rows using cv2 to display the recognized license plate and characters.
6. Write this frame from step 5 as the new frame for the output video. 

So, I have a few more details to write over and above the annotated frame using cv2, and hence I am looking for methods to convert the 'result' variable to a cv2 image. Any luck?

**Comment by niranjan4r** [comment]
For visualization, 

Input frame: 
![Screenshot (51)](https://user-images.githubusercontent.com/50557046/161541233-6ded34a5-0fdf-43e0-86fd-7b24bdd5a4ab.png)

Output frame after running my code:

![Screenshot (50)](https://user-images.githubusercontent.com/50557046/161541270-1dd4ff89-3da0-4db3-995c-26cc84586ac1.png)

Currently I am using the input frame and adding a few rows at the bottom to add the license plate details. 
Instead of having to use the input frame, I would love to have the annotated frame so that there would be bounding boxes over the vehicles in the output frame

**Comment by glenn-jocher** [comment]
@niranjan4r annotated images as numpy arrays are available with
```python
results.render()
results.imgs
```

**Comment by niranjan4r** [comment]
Thanks got it.
I used the following to get the annotated image in cv2 format
```
img = cv2.cvtColor(results.imgs[0], cv2.COLOR_RGB2BGR)
cv2_imshow(img)
```

Thanks for the help @glenn-jocher
