### ISSUE TITLE
Using cache in evolving hyp loops need reloading many times

### ISSUE THREAD

**Issue by zaipinai** [ultralytics/yolov5#7267]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

If I use --cache and --evolve for every 10 epochs, it costs lots of time to cache. Can it cache once to reuse it in this loops?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@zaipinai then don't --cache
