### ISSUE TITLE
Integrate TorchMetrics

### ISSUE THREAD

**Issue by aniketmaurya** [ultralytics/yolov5#7271]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues?q=is%3Aissue+is%3Aopen+metrics) and found no similar feature requests.

### Description

Hi @ultralytics @glenn-jocher! Love YoloV5 💜🔥

We are using it in [Lightning-Flash](https://lightning-flash.readthedocs.io/en/latest/) with the Object Detection Task.

I just noticed the metrics module and I think it can be optimised with [TorchMetrics](https://torchmetrics.readthedocs.io/en/latest/) which provides a collection of Machine Learning metrics for distributed, scalable PyTorch models and an easy-to-use API to create custom metrics.

### Use case

- Faster and scalable computation of metrics
- Simplify code base

### Additional

I would be happy to know your thoughts on it. Also, if you want I can help with a PR 🙂 

Thanks

cc: @Borda 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Borda** [comment]
@aniketmaurya that would be great; mind also quick draw here in issue, how the replacement in nat-shell would look like?

**Comment by Borda** [comment]
@glenn-jocher pls let's keep this open...

**Comment by glenn-jocher** [comment]
Reopened

**Comment by Borda** [comment]
@aniketmaurya :rabbit:

**Comment by Borda** [comment]
Let's keep it open =)

**Comment by Borda** [comment]
@glenn-jocher any update here? :)

**Comment by glenn-jocher** [comment]
@Borda sorry, we have a significant backlog between Classification debugging and Segmentation introduction which we are prioritizing.

**Comment by Borda** [comment]
It took me a while but finally exploring the integration in Lightning over here 🦩 https://github.com/Borda/lightning-YOLOs
