### ISSUE TITLE
How to save results as text or json

### ISSUE THREAD

**Issue by Chuttyboy** [ultralytics/yolov5#7273]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I tried to save result in text file using below command

`python3 detect1.py --source stream.txt`

stream.txt file contains

```
0
2
```
After that i tried to save result in text file using some to  
 ```
with open("output.txt", "a") as f:
            now = datetime.datetime.now().strftime("%a, %d %B %I:%M:%S")
            print(f'{s}Done. ({t3 - t2:.3f}s)', now ,file=f)
```
Above code which saves output in output.txt file like this

`0: 480x640 2 persons, 1 tv, 2 clocks, 1: 480x640 2 persons, 1 bottle, 1 tv, 2 laptops, Done. (0.602s) Mon, 04 April 12:23:24`

But  i expected save result with webcam  name like this 

`cam1" 2 persons, 1 tv, 2 clocks : cam2 2 persons, 1 bottle, 1 tv, 2 laptops : date Mon, 04 April `

How to save results in this format. thanks in advance

**Comment by glenn-jocher** [comment]
@Chuttyboy 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`, including easy JSON export.

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, etc.
# model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')  # custom trained model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by Chuttyboy** [comment]
@glenn-jocher 

Thanks for you reply i read the content but i didn't get any answer for my solution can you please tell me how to save result in below shown format 

`0: 480x640 2 persons, 1 tv, 2 clocks, 1: 480x640 2 persons, 1 bottle, 1 tv, 2 laptops, Done. (0.602s) Mon, 04 April 12:23:24`

Into 

`cam1" 2 persons, 1 tv, 2 clocks : cam2 2 persons, 1 bottle, 1 tv, 2 laptops : date Mon, 04 April`

**Comment by glenn-jocher** [comment]
See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for JSON output details.
