### ISSUE TITLE
Train with tensorflow

### ISSUE THREAD

**Issue by joihn** [ultralytics/yolov5#7275]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is there a way to train the model with tensorflow framework ? 
I guess the quickest way would be to export the model as tensorflow (`export.py --include saved_model`), and manually rewrite the whole train loop in tensoflow, right ?

**Comment by glenn-jocher** [comment]
@joihn your idea seems about right.

**Comment by joihn** [comment]
okay thanks
