### ISSUE TITLE
Computer using CPU instead of GPU nvidia with CUDA

### ISSUE THREAD

**Issue by trifasico** [ultralytics/yolov5#7277]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

Hello, 

I ahve been working with yolov5 for quite some time now, and i always used google colab. But since they are implementing limitations, i have decided to buy a egpu and a nvidia 3080ti to train my networks. I sucesfully installed the drivers and can use de GPU for other softwares. I can also use the GPU for running a trained network, using yolo detection.py and even using my own code based on pytorch library.
For some reason, and i can't figure out why, i can't seem to use my gpu for training. When i use the train.py from yolov5 it doesn't use my cuda nvidia GPU. i have tried multiple versions of python, multiple versions of cuda, multiple versions of pytorch (LTS, stable, nightly) and i still can't figure it out.
When i run de train.py file it detects that i have a 3080ti, but when it starts the epochs, my gpu usage is 0% and my cpu usage jumps to 90%, so it is using my cpu.

I getting really frustrated, can someone please help me?

### Environment

- YOLOv5 latest version
- pytorch 1.11.0 + cu113 (this is current, i have tried LTS, stable and preview)
- windows 10
- python 3.9 or 3.10 (i have tried both)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@trifasico it appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual [Python 3.9](https://www.python.org/) environment, clone the latest repo ([code changes daily](https://github.com/ultralytics/yolov5/commits/master)), and `pip install` [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) again from scratch.

💡 ProTip! Try one of our verified environments below if you are having trouble with your local environment.


## Requirements

[**Python>=3.7.0**](https://www.python.org/) with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) installed including [**PyTorch>=1.7**](https://pytorch.org/get-started/locally/). To get started:
```bash
git clone https://github.com/ultralytics/yolov5  # clone
cd yolov5
pip install -r requirements.txt  # install
```

[Models](https://github.com/ultralytics/yolov5/tree/master/models) and [datasets](https://github.com/ultralytics/yolov5/tree/master/data) download automatically from the latest YOLOv5 [release](https://github.com/ultralytics/yolov5/releases) when first requested.

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), validation ([val.py](https://github.com/ultralytics/yolov5/blob/master/val.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/export.py)) on MacOS, Windows, and Ubuntu every 24 hours and on every commit.

**Comment by trifasico** [comment]
Hi, I have tried reinstalling and installing everything multiple times, and i even made new environments to make individual tests. Still nothing, i have tried multiple versions of python (3.8, 3.9, 3.10) and i tried multiple versions of cuda, but my 3080ti only supports Cuda 11.3
I also installed all the requirements of yolov5
I know this is a local environment but i really need this to work, if you could help i would very grateful! Please please help me

**Comment by glenn-jocher** [comment]
@trifasico see https://pytorch.org/get-started/locally/

When you start training YOLOv5 will tell you what hardware it is using, i.e. here it is using CUDA 0, a V100 on Colab. 

<img width="836" alt="Screenshot 2022-04-04 at 23 57 17" src="https://user-images.githubusercontent.com/26833433/161639007-bbd58113-9bfe-47e8-8991-727e460afee8.png">

**Comment by trifasico** [comment]
Hi again, I noticed that, and effectively the yolov5 train and detection shows me the nvidia 3080ti 12Gb but when it starts training the gpu usage is 0 and the cpu usage is about 90%
And training is really slow for the gpu that it is, 2 it/s which is really weird

**Comment by sa404-star** [comment]
Maybe you can stick the error message here

**Comment by glenn-jocher** [comment]
@trifasico then you are already training with GPU and your issues lie elsewhere.

**Comment by trifasico** [comment]
How can i be training with the GPU and my cpu goes to 90% and the gpu stays in 0% usage?
What info can i give you for you to help me fix this? I am a student at the university and sometimes the network goes down, so i really need to use yolo locally
Can you please help me fix this? 
What info or diagnostic can i give you to help me?

**Comment by glenn-jocher** [comment]
@trifasico we don't assist in debugging local environments. 

CPU utilization and proper CUDA installation are two completely separate topics. Your CPU utilization might be high from large images, decompressing JPGs, too many workers, insufficient resources, etc. 

Like I said if your YOLOv5 line is showing your GPU then YOLOv5 and Torch already see it and are using it.

**Comment by trifasico** [comment]
I understand that every case is a case, but i have tried multiple installations and i really need this to work locally, can you please at least try to guide me
Because i have already saw other issues here that talk about the same problem, and we could probably figure it out for everyone

**Comment by trifasico** [comment]
https://user-images.githubusercontent.com/7412891/161820242-a7f5f5cc-05cc-4643-9ef5-5595be1bd595.mp4

After reinstallling everything, clean install of python, clean install of pytorch, clean install of cuda, i got this weird behaviour of my pc.
It uses the CPU for a minute or soo, and uses the GPU for 20secs, and i can't figure out why
Can someone please helpe me?
The video is an example of a training, where you can see the command line and the task manager to see the gpu and cpu usage

**Comment by AlphaSlayer1964** [comment]
Did you install CUDA Toolkit?

**Comment by trifasico** [comment]
I think i did, and i think it is correclty installed
but here it is what i have installed and the versions i have installed
![Cuda](https://user-images.githubusercontent.com/7412891/162625790-d5c092c9-1a6a-4c63-98c3-8a658d37c51e.png)

**Comment by trifasico** [comment]
Do you think this is correclty installed?

**Comment by AlphaSlayer1964** [comment]
Yes it looks like you installed the cuda tool kit. Can you confirm pytorch is recognizing your gpu. First, open a terminal and type `python` to enter a live python environment. Then type the three commands in the python environment. 
```
import torch
torch.cuda.is_available()
torch.cuda.get_device_properties(0).name
``` 
You should see true and the name of your gpu if pytorch is correctly identifying your gpu.

I'd also recommend re installing all requirements in a separate python virtual environment. This can be done by opening a terminal in your yolov5 folder and running the command `python -m venv {environment_name}` and replace `{environment_name}` with your own name. Then to enter the virtual environment, for windows and power shell, run the command `.\{environment_name}\Scripts\activate.ps1`. You will know you are in the virtual environment if the name of your virtual environment is on the left side of your terminal. Once in the virtual environment do your pip installs and they will all be separate from you global modules. I recommend this because you may have conflicts with improper versions of some modules that other scripts also use.

**Comment by trifasico** [comment]
Hi, 
It appears true, and the name of the gpu
>>> True
>>> 'Nvidia RTX 3080ti 12Gb'

I have tried reinstalling the requirements multiple times but i still have the same problem
I normally use the main environment, but even in a separate environment i have the same issue

What more information can i give you? do you want pc specs? another video of testing something?
just tell me and i give all the info and tests you need to fix me this
I really need this to work, and thanks very very much for helping me!
I await you answer with the next instructions to see if we can fix this

**Comment by AlphaSlayer1964** [comment]
From your earlier video it looks like yolo is using the Radeon Pro 555x and not the 3080 ti. Can you disable that since I don't know if you can pass an argument to use a specific GPU.

**Comment by trifasico** [comment]
I will try again with the amd radeon disabled, but, yolo says the gpu being used is the nvidia, and i specificly say --device 0, to use device number 0 of cuda, in this case, RTX 3080ti
But i will try to disable amd radeon and use only nvidia
Also, amd radeon doesnt support cuda, soo i dont know if or how yolo is using radeon
But thank you very much, When i try that i will let you know, thanks

**Comment by trifasico** [comment]
Hi again, I have tried multiple setups, and still nothing... It is not using the AMD GPU, the GPU process is high, but it's because I have multiple screens connected. When I only use one screen, the GPU processing stays low.
Any other ideas? I have thought about using Linux, but I can only test that in July, and I wanted to try to fix this before that, and if windows support CUDA and python for yolov5 it should work.
Any other suggestions?

**Comment by AlphaSlayer1964** [comment]
Try manually setting the device index with one of the arguments for train.py.
`--device` `help: cuda device, i.e. 0 or 0,1,2,3 or cpu` or look into multi GPU training https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training.

**Comment by trifasico** [comment]
Still nothing... Any other suggestion or test that I can do?
https://user-images.githubusercontent.com/7412891/163634075-473739e1-d6c3-4b4b-b3d6-23c148227fd9.mp4

**Comment by trifasico** [comment]
BTW, here is another test using 12 workers, my CPU has 6 cores, and 12 threads. I have read that it could be the CPU not being fast enough, but it's an i7, 12 threads up to 3,5GHz so I don't think that is it...

https://user-images.githubusercontent.com/7412891/163635556-86518574-5084-456b-9a2b-e36d6b7d2543.mp4

.

**Comment by AlphaSlayer1964** [comment]
So looking at how fast you train that seems about right, comparing how fast my 1080ti or i7-12700k can train, I think it is using the GPU. You even get the print out saying you are using the 3080. That being said I would imagine the GPU usage would be higher. sadly I'm out of ideas. You might have better luck asking pytorch for help on this one.

**Comment by trifasico** [comment]
Well, thank you very much for trying, I appreciate it
The thing that bothers me, is that on the detection, it uses more GPU than on training?
That is the thing that bothers me more!

**Comment by trifasico** [comment]
Well, how can it be using the GPU, and it stays with almost 0% usage?! it's bothering me soo much...
I can try whatever you guys need or want, just tell me
In the summer I will try this eGPU on a Linux machine to  see if it helps, but until then I would like to have it working on windows
this low usage doesn't even make the fans spin on the GPU...

**Comment by trifasico** [comment]
Any other ideas?
I need this to work...

**Comment by AlphaSlayer1964** [comment]
Like I said I would try to asking the pytorch devs as pytorch says it is using the GPU when it's not.

**Comment by Smokedhammer** [comment]
pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio===0.9.0 -f https://download.pytorch.org/whl/torch_stable.html

Do this above step. and then try running the train command directly from the command line, this made it work somehow!

![image](https://user-images.githubusercontent.com/95684845/224986683-1e8d5bb8-1f8a-4bbe-9cf0-5f6530893b9a.png)


There should be a prompt on the command line which shows you using the GPU

**Comment by glenn-jocher** [comment]
@Smokedhammer glad to hear you found a solution! Thanks for sharing it here. It will undoubtedly help others who may encounter a similar issue. If you have any further questions or need assistance, feel free to ask.
