### ISSUE TITLE
Increase prediction scacles

### ISSUE THREAD

**Issue by ImsuperSH** [ultralytics/yolov5#728]
## ❔Question

I'd like to increase an additional 104*104 prediction scale (13 * 13, 26 * 26, 52 * 52, 104 * 104 in total). So I modify the yaml file only. The result shows that new mAP decreases a little compared with the original yolov5. Do I need to modify other parts like compute_loss? where should I modify? Appreciate.

**Comment by glenn-jocher** [comment]
@Sean-pure sure. P2 ops like you have there may help in the detection of smaller objects. We have limited resources and can not advise you on model customization ourselves, but we'll leave this issue open for any community feedback. Good luck.
