### ISSUE TITLE
Exporting trained model to coreML missing metadata

### ISSUE THREAD

**Issue by Sic-1** [ultralytics/yolov5#7284]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello

When following the steps of exporting yolov5s.pt to coreML (yolov5s.mlmodel) it is missing labels, correct output and metadata in Xcode, see picture. I have seen previous questions regarding this but no solution and the issue closed. Any solution to this now?

I did the export yesterday so Im using the latest branch of yolov5.

<img width="1165" alt="Skärmavbild 2022-04-05 kl  09 12 09" src="https://user-images.githubusercontent.com/55258842/161698726-d2c11206-6204-40d4-9990-ad9a77f348d0.png">
<img width="1165" alt="Skärmavbild 2022-04-05 kl  09 36 25" src="https://user-images.githubusercontent.com/55258842/161702898-fc9bce9b-c454-4af4-b72f-fa69fae3eda2.png">

For a comparison this is what yolov3 from Apple looks like: 
<img width="1165" alt="Skärmavbild 2022-04-05 kl  09 42 50" src="https://user-images.githubusercontent.com/55258842/161703987-6d68109e-fe6b-4656-987f-1555811fbc30.png">

<img width="1165" alt="Skärmavbild 2022-04-05 kl  09 42 59" src="https://user-images.githubusercontent.com/55258842/161704000-2a8bea44-660c-432e-81e3-d2f43a0b5562.png">

**Comment by pillai-karthik** [comment]
Did you find a solution?

**Comment by PeterSenyszyn** [comment]
Bumping this. It also seems that going from v6.0 -> v6.1 changes the mlmodel architecture (from Netron). It would be nice to have an example of inference using CoreML.

**Comment by glenn-jocher** [comment]
@PeterSenyszyn YOLOv5 CoreML inference Usage examples are displayed after export (requires macOS).

<img width="685" alt="Screenshot 2022-06-24 at 15 06 29" src="https://user-images.githubusercontent.com/26833433/175542215-284df189-7f7a-4163-8005-2d9c68d4d650.png">

**Comment by evercherish** [comment]
I am in the same boat confusing about coreml model conversion. 
The xxx.mlmodel converted by export.py in 6.1 is different with the one downloaded from Apple.
Have you solved it?

**Comment by zjsjayce** [comment]
I also meet this problem.

**Comment by cayorodriguez** [comment]
I have the same problem. My class labels are not exported. Bummer

**Comment by jo32** [comment]
found a post may solve this issue: https://rockyshikoku.medium.com/convert-yolov5-to-coreml-also-add-a-decode-layer-113408b7a848

**Comment by glenn-jocher** [comment]
@jo32 thanks for sharing that link! We appreciate the community effort in resolving challenges with YOLOv5. If you need further assistance, feel free to ask. We're here to help!

**Comment by cayorodriguez** [comment]
Thanks. The post refers to Yolov5. I am using Yolov8, and already exported
to CoreML in the Ultralytics Hub. In order for it to be available for the
Ultralytics App, what needs to be done.

Thanks!
==============
Carlos Rodriguez
==============

**Comment by stev3** [comment]
Exporting to `mlpackage` in Yolov8 works for me after I add `nms=True` to `model.export()`

For example: `model.export(format='coreml', nms=True)`

**Comment by glenn-jocher** [comment]
Hi @stev3 Rodriguez, glad you've successfully exported to CoreML with YOLOv8! To make it available for the Ultralytics App, simply ensure the `.mlmodel` file is properly integrated into your app project. Usually, this involves importing the model into your Xcode project and implementing the necessary code for handling input and output. For detailed guidance on integrating models into iOS apps, you might find Apple's CoreML documentation helpful. Keep experimenting and happy coding! 🚀
