### ISSUE TITLE
Flask Memory Release Error

### ISSUE THREAD

**Issue by NeuroTerm** [ultralytics/yolov5#7288]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection, Integrations, Other

### Bug

When using a flask, the memory is constantly increasing. I add the memory usage in the image below. I am using official Flask example. I see that the memory increases as I use the web service.

![image](https://user-images.githubusercontent.com/13656331/161731051-8b8eaa14-5d50-4a99-a0e6-2bdb5180bf39.png)

### Environment

- OS = Ubuntu
- Pytorch CPU / latest version YoloV5

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@celalettinbilgen thanks for the bug report! I reviewed the code and found an instance of improper file opening without closing. This may be the cause of the memory leak. Can you run your test again using the PR #7289 code? i.e.:

git clone https://github.com/ultralytics/yolov5 yolov5-pr7289 -b fix/flask

**Comment by glenn-jocher** [comment]
@celalettinbilgen good news 😃! Your original issue may now be fixed ✅ in PR #7289. This PR implements context managers when opening files to properly close them after use.

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by NeuroTerm** [comment]
Thank you @glenn-jocher . 

Unfortunately, I see that the problem still persists. The problem is in the restapi.py file, not the request script. Memory keeps increasing as I use it :(

**Comment by glenn-jocher** [comment]
@celalettinbilgen could you try PR #7309 to see if this helps?
```bash
git clone https://github.com/ultralytics/yolov5 -b update/restapi
```

**Comment by glenn-jocher** [comment]
I think this may be related to opening may PIL Images without closing them, per https://pillow.readthedocs.io/en/stable/reference/open_files.html

If the PR doesn't work try the alternative implementations in the PIL docs until something works, and then let us know. Thanks!

**Comment by NeuroTerm** [comment]
@glenn-jocher 

official sample not working :(

![image](https://user-images.githubusercontent.com/13656331/161986552-c8306400-1b54-4769-8cbb-768cd3b7eca5.png)

**Comment by glenn-jocher** [comment]
@celalettinbilgen got it! Please debug this by editing https://github.com/ultralytics/yolov5/pull/7309/files per https://pillow.readthedocs.io/en/stable/reference/open_files.html to see if you can find a suitable solution.

**Comment by NeuroTerm** [comment]
@glenn-jocher I understand you very well. However, when I debug, the error I posted above is present. I pulled 7309.

**Comment by glenn-jocher** [comment]
@celalettinbilgen yes I understand. Please modify the code yourself to see if you can find a suitable solution per https://pillow.readthedocs.io/en/stable/reference/open_files.html, and then please submit a PR.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
