### ISSUE TITLE
why we use  np.mod(dw, 64) in letterbox code?

### ISSUE THREAD

**Issue by bochuanwu** [ultralytics/yolov5#729]
## ❔Question
The code is in datasets.py
        dw, dh = np.mod(dw, 64), np.mod(dh, 64)  # wh padding
for letterbox：
why we use 64 to get the padding parameter?  
for exampele:
origin_image = 800x600x3
resized_image for train = 416x312x3 with padding to 416x416x3 
resized_image for test without letterbox is also 416x416x3, but by using  dw, dh = np.mod(dw, 64), np.mod(dh, 64)  , resized_image for test become 416x352.
why we use 64 to calculate the padding parameter?
in my opinion, the padding parameter should be 416-312 = 104.

**Comment by Laughing-q** [comment]
@bochuanwu the way padding like this is for rectangle inference(or train).

**Comment by bochuanwu** [comment]
> @bochuanwu the way padding like this is for rectangle inference(or train).

yes，i know it is  for inference,but i don't understand why we use this padding method, it will reduce usage of memory and improve speed, but why we not simply resized the test_image to  416x312x3 which is smaller than  416x352x3?
what is the reason we use padding in inference process.

**Comment by Laughing-q** [comment]
@bochuanwu input size needs to be divisible by 32

**Comment by glenn-jocher** [comment]
@bochuanwu the simpler dataloaders do not accept any stride information from the model, so in this case we assume a stride constraint of 64, which is suitable for accommodating all models with up to P6 output layers, which includes the public range of YOLOv5 models as well as some unpublished experimental versions.

**Comment by bochuanwu** [comment]
> @bochuanwu the simpler dataloaders do not accept any stride information from the model, so in this case we assume a stride constraint of 64, which is suitable for accommodating all models with up to P6 output layers, which includes the public range of YOLOv5 models as well as some unpublished experimental versions.

thank you all for answer my question， finally i understand it~
