### ISSUE TITLE
Suggest if copy paste technique is implemented in bbox, the part that needs to be modified

### ISSUE THREAD

**Issue by YoungjaeDev** [ultralytics/yolov5#7290]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello
I am going to implement copy-paste with bbox instead of segment.
Do I just need to modify the part below? Or is there any additional part that needs to be modified?

https://github.com/ultralytics/yolov5/blob/2181ef371e5493eb3cddcfa50b59804cbabce73d/utils/augmentations.py#L220-L241

Thank you!

**Comment by glenn-jocher** [comment]
@youngjae-avikus yes you should just be able to modify the copy_paste() fcn.

**Comment by YoungjaeDev** [comment]
@glenn-jocher 

I wonder if I can label segment coordinates for **copy-paste** when referring to `coco128-segment` and calculate the box coordinates internally to perform object detection?

Thank you

**Comment by glenn-jocher** [comment]
@youngjae-avikus yes that's what already happens when you train on a dataset like `coco128-segment`

**Comment by YoungjaeDev** [comment]
@glenn-jocher 
By what standards do you change segment labels to bbox?
Thank you

**Comment by glenn-jocher** [comment]
@youngjae-avikus enclosing box

**Comment by YoungjaeDev** [comment]
This is about code. Right ? 
```python
def segments2boxes(segments):
    # Convert segment labels to box labels, i.e. (cls, xy1, xy2, ...) to (cls, xywh)
    boxes = []
    for s in segments:
        x, y = s.T  # segment xy
        boxes.append([x.min(), y.min(), x.max(), y.max()])  # cls, xyxy
    return xyxy2xywh(np.array(boxes))  # cls, xywh
```

**Comment by glenn-jocher** [comment]
@youngjae-avikus yes!

**Comment by pocketvision** [comment]
It seems that the copy_paste() fcn only process the image, but the origin segments may have been covered by the copy paste segments, so is there any optimization for such kind of situations, by processing those covered segments at the same time ? @glenn-jocher

**Comment by glenn-jocher** [comment]
@daikankan 30% obscuration of existing labels is allowed. Any more and the existing label is removed:
https://github.com/ultralytics/yolov5/blob/f8722b4429e80f96be04b36e4efd84ce6583bfa1/utils/augmentations.py#L229-L234
