### ISSUE TITLE
What is the role of these two parameters? The meaning of adjustment

### ISSUE THREAD

**Issue by wemindful** [ultralytics/yolov5#73]
depth_multiple: 0.33  # model depth multiple
width_multiple: 0.50  # layer channel multiple

What is the role of these two parameters? The meaning of adjustment

**Comment by glenn-jocher** [comment]
@PEAKWEI they are exactly as noted in the comments next to the variable.

**Comment by peijason** [comment]
> @PEAKWEI they are exactly as noted in the comments next to the variable.

@glenn-jocher Hey, glenn.  I also have the same doubts. 

- The **yolov5.yaml** file seems to be totally different from **yolov4.cfg** .
We have **NO** idea what is the preferred original image size? If **yolov5** starts with a **resize**, some of our concerned objects will disappear right away....

- What's more, it looks to me **depth_multiple** and **width_multiple** are for the network architecture? Can you please let us know: where to find the documentation for these 2 configurations, in more details?

Thank you very much.

**Comment by glenn-jocher** [comment]
@peijason sorry buddy,  documentation is a bit light at the moment. Most often what's in the comments is what there is. Depth multiple and width multiple are just as they sound, they are used for model scaling, and for compound scaling when used jointly. I'd recommend reading the efficientdet paper for more on the topic.

The model architecture is independent of the inference size, save for stride multiple constraints. This is a property of any convolutional network.
