### ISSUE TITLE
result of yolov5_l is strange

### ISSUE THREAD

**Issue by ImsuperSH** [ultralytics/yolov5#730]
## ❔Question
![results (1)](https://user-images.githubusercontent.com/58339357/90107655-ba07a300-dd7b-11ea-8c6e-ad6c389297a2.png)
this is the result of single class training (with pre-trained weights) of yolov5-l, Could anybody explain why the recall decreases and val_obj increases?

**Comment by zy562699033** [comment]
I have the same problem,and my confidences of results are very low(0.1~0.2),did you solve the problem?

**Comment by glenn-jocher** [comment]
@Sean-pure your results show a best mAP at epoch 2 followed by overfitting.
