### ISSUE TITLE
Training with issues at the end -- 'DeformConv2d' object has no attribute 'in_channels'

### ISSUE THREAD

**Issue by hubery1619** [ultralytics/yolov5#7303]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I add the deformable convolution network in yolov5. At the end of the training, it shows as follows:

Optimizer stripped from runs/train/modified_yolov5/weights/last.pt, 98.0MB
Optimizer stripped from runs/train/modified_yolov5/weights/best.pt, 98.0MB

Validating runs/train/modified_yolov5/weights/best.pt...
Fusing layers... 
Traceback (most recent call last):
  File "train.py", line 630, in <module>
    main(opt)
  File "train.py", line 527, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 425, in train
    model=attempt_load(f, device).half(),
  File "/home/ models/experimental.py", line 98, in attempt_load
    model.append(ckpt['ema' if ckpt.get('ema') else 'model'].float().fuse().eval())  # FP32 model
  File "/home/models/yolo.py", line 351, in fuse
    m.conv = fuse_conv_and_bn(m.conv, m.bn)  # update conv
  File "/home/ /utils/torch_utils.py", line 200, in fuse_conv_and_bn
    fusedconv = nn.Conv2d(conv.in_channels,
  File "/home/yolov5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1177, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DeformConv2d' object has no attribute 'in_channels'

### Additional

It could train for all 300 epochs. But at the end of the training, it raises issues.

**Comment by glenn-jocher** [comment]
@hubery1619 it seems it ran into a problem during the `model.fuse()` operation. Fusing combines BN with Conv. You can either eliminate fusing or fix fusing. The code is here:
https://github.com/ultralytics/yolov5/blob/d257c75c848ccab4d9195300a61195cf0dfef1bf/models/yolo.py#L225-L234
