### ISSUE TITLE
Exception encountered when calling layer "sequential" (type Sequential).

### ISSUE THREAD

**Issue by fairywww** [ultralytics/yolov5#7306]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I changed the backbone of yolov5l.yaml,
```
backbone:
  # [from, number, module, args]
-[[-1, 1, Conv, [1, 6, 2, 2]],  # 0-P1/2
+[[-1, 1, Conv, [1, 6, 2, 2]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C3, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 6, C3, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, C3, [512]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 3, C3, [1024]],
   [-1, 1, SPPF, [1024, 5]],  # 9
  ]
```
Then I uesd train.py to get a weight,
```
5 epochs completed in 0.008 hours.
Optimizer stripped from runs/train/exp44/weights/last.pt, 93.6MB
Optimizer stripped from runs/train/exp44/weights/best.pt, 93.6MB

Validating runs/train/exp44/weights/best.pt...
```
And I try to transfer the pt to tflite,
```
python export.py --weights /home/wangfz/wksp/yolov5/runs/train/exp44/weights/best.pt --include tflite
```

but I encountered the error message.
```
TypeError: Exception encountered when calling layer "sequential" (type Sequential).

Eager execution of tf.constant with unsupported shape.
...
has 108 elements, but got `shape` (6, 6, 3, 8) with 864 elements).

Call arguments received:
  • inputs=tf.Tensor(shape=(1, 640, 640, 3), dtype=float32)
  • training=None
  • mask=None
```
How should I do to solve the question?

**Comment by glenn-jocher** [comment]
@fairyw98 sorry, model and code customizations are not part of Ultralytics support, which is limited to reproducible issues in unmodifiable code. Perhaps a community member has an idea.

**Comment by fairyw98** [comment]
> 

Thank you for your reply, that means export.py can only export yolov5s.yaml, yolov5l.yaml and other Ultralytics supported model structure to tflite format, if I change the model structure myself and want to convert to tflite format, I need to write my own script, right?

**Comment by fairywww** [comment]
> @fairyw98 sorry, model and code customizations are not part of Ultralytics support, which is limited to reproducible issues in unmodifiable code. Perhaps a community member has an idea.

Thank you for your reply, that means export.py can only export yolov5s.yaml, yolov5l.yaml and other Ultralytics supported model structure to tflite format, if I change the model structure myself and want to convert to tflite format, I need to write my own script, right?

**Comment by glenn-jocher** [comment]
@fairyw98 ah, I just remembered! If you are exporting to TF with custom modules you need to re-implement your module in TensorFlow here. The name of your TF module would be 'TF' + the name of the PyTorch module.
https://github.com/ultralytics/yolov5/blob/master/models/tf.py

For example models.common.Conv() is implemented as models.tf.TFConv() here:
https://github.com/ultralytics/yolov5/blob/d257c75c848ccab4d9195300a61195cf0dfef1bf/models/tf.py#L62-L95

**Comment by fairywww** [comment]
> @fairyw98 ah, I just remembered! If you are exporting to TF with custom modules you need to re-implement your module in TensorFlow here. The name of your TF module would be 'TF' + the name of the PyTorch module. https://github.com/ultralytics/yolov5/blob/master/models/tf.py
> 
> For example models.common.Conv() is implemented as models.tf.TFConv() here:
> 
> https://github.com/ultralytics/yolov5/blob/d257c75c848ccab4d9195300a61195cf0dfef1bf/models/tf.py#L62-L95

Thank you! That's exactly what I need.
