### ISSUE TITLE
regresion

### ISSUE THREAD

**Issue by Ezra-Yu** [ultralytics/yolov5#731]
## ❔Question
why * 2?
the range of sigmoid is (0, 1),n why you mul 2 the sub 0.5?

## Additional context
![image](https://user-images.githubusercontent.com/18586273/90116161-ab26ed80-dd87-11ea-800a-d82cdeedc645.png)

**Comment by tkianai** [comment]
Generally, the groundtruth bbox would be matched with three grids (contains two neighbor grids), so the regression arange should be -0.5~1.5. More details refer to `build_targets()`
