### ISSUE TITLE
Implement Meta Learning into YoloV5

### ISSUE THREAD

**Issue by mburges-cvl** [ultralytics/yolov5#7310]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,

I am currently attempting to implement different Meta Learning strategies into YoloV5 to compare them. However, I get the following error:

> RuntimeError: Function 'CudnnConvolutionBackward' returned nan values in its 1th output.

What did I change?:

I replaced the "standard" convolutions in YoloV5 with this custom convolution from this [paper](https://www.bmvc2020-conference.com/assets/papers/0042.pdf). The custom convolution is implemented like this:
```
class Conv2dMCL(torch.nn.modules.conv._ConvNd):
    """MCL CONV IMPLEMENTATIOn"""
    def __init__(self,
                 in_channels,
                 out_channels,
                 kernel_size,
                 stride=1,
                 padding=0,
                 dilation=1,
                 groups=1,
                 bias=True,
                 padding_mode='zeros',
                 original_weight=None):
        kernel_size = _pair(kernel_size)
        stride = _pair(stride)
        padding = _pair(padding)
        dilation = _pair(dilation)

        super(Conv2dMCL, self).__init__(in_channels, out_channels, kernel_size,
                                        stride, padding, dilation, False,
                                        _pair(0), groups, bias, padding_mode)
        self.weight = original_weight.weight
        weight = torch.randn(out_channels, in_channels, 1, 1)
        if self.weight.is_cuda:
            weight = weight.cuda()
        self.mcl_weight = torch.nn.Parameter(weight)

    def forward(self, inp):
        new_mcl_weight = self.mcl_weight.expand(self.weight.shape)
        new_weight = self.weight.mul(new_mcl_weight)

        output = F.conv2d(inp, new_weight, self.bias, self.stride,
                          self.padding, self.dilation, self.groups)

        return output

```

and I replaced the convolutions like this:

```
    if "yolov5n" in weights and fewshot:  #(FYI: I am using YoloV5n)
        model.model[0].conv = Conv2dMCL(3,
                                        16,
                                        kernel_size=(6, 6),
                                        stride=(2, 2),
                                        padding=(2, 2),
                                        bias=False,
                                        original_weight=model.model[0].conv)
```

Currently I am only replacing the first convolution in YoloV5n, however, this already results in the error mentioned above. I already tested the custom convolution in a more simplistic network and it worked there without any error. I believe the issue is related to mixed-precision training, though I wasn't able to verify that.

Does somebody have an idea on how to fix this issue?

### Additional

I am training on the COCO128 dataset.

**Comment by glenn-jocher** [comment]
@mburges-cvl I'm sorry, we don't have bandwidth to provide Ultralytics support to users with custom code or custom model implementations, but you can inspect and disable the AMP code in train.py and val.py pretty easy by setting `enabled=False `or by simply just training a few batches on CPU with `python train.py --device cpu`

https://github.com/ultralytics/yolov5/blob/d257c75c848ccab4d9195300a61195cf0dfef1bf/train.py#L342-L345

**Comment by mburges-cvl** [comment]
Okay, still thank you! Training with CPU only confirms my suspicions, that mixed-precision is the "issue".

**Comment by shrinand1996** [comment]
@mburges-cvl did you get meta learning+yolov5 to work?
