### ISSUE TITLE
MAP in results.txt

### ISSUE THREAD

**Issue by adigol** [ultralytics/yolov5#7329]
I tried to understand if the MAP is taking into account the class label in a model with more than one class or just checking if the IOU of the bounding boxes is bigger than a threshold.
The IOU can be a measure of the classes? like accuracy.
Thanks in advance

**Comment by glenn-jocher** [comment]
@adigol mAP is mean AP for all classes. See https://en.wikipedia.org/wiki/Precision_and_recall
