### ISSUE TITLE
Objects365 pretrained model

### ISSUE THREAD

**Issue by jainrahulsethi** [ultralytics/yolov5#7331]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Can anyone provide the pretrained model on the objects365 classes?

**Comment by glenn-jocher** [comment]
@jainrahulsethi we have an Objects 365 pretrained YOLOv5m model here:
https://github.com/ultralytics/yolov5/releases/download/v6.0/yolov5m_Objects365.pt

**Comment by jainrahulsethi** [comment]
Do we have the lighter versions or the heavier versions as well?

**Comment by glenn-jocher** [comment]
@jainrahulsethi the above model is our only pretrained model. See https://github.com/ultralytics/yolov5/pull/5194#issuecomment-948073928 to train your own.

**Comment by andreqwert** [comment]
@glenn-jocher Hello! Can you please provide what metrics yolov5m received on Objects365 dataset?

**Comment by BedIntruder** [comment]
@glenn-jocher I'm trying to train a YOLOv5 model on Objects365, and I'm very curious about something. 
Do you have the original training results files I can use as a reference to see how well I've been doing it? I figured using a reference is much less annoying than having to ask you constantly about my silly issues I found while training the dang thing.
Thanks, and have a great day!

**Comment by kiranbaby14** [comment]
Hey @glenn-jocher, Do you guys have pre-trained weights for Yolo11 for objects365 dataset?

**Comment by kiranbaby14** [comment]
Hey @glenn-jocher, do you guys have pre-trained weights for YOLO11 on the Objects365 dataset?

**Comment by drbilal216** [comment]
Hey @glenn-jocher , same question, do you guys have pre-trained weights for YOLO11-n on the Objects365 dataset?

**Comment by sourabCV** [comment]
I need also pre-trained weights for YOLO11-n on the Objects365 dataset
because in collab facing space issue during dataset all 51 patches download
@glenn-jocher if you share that will be so help full. Thank You
