### ISSUE TITLE
Exporting an INT8 tensorrt engine

### ISSUE THREAD

**Issue by LieceC** [ultralytics/yolov5#7332]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have been trying for a while to modify the yolov5 code in order to export an int8 tensorrt engine on a jetson xavier AGX using tensorrt 8.2.3.0 on python 3.7. However, I am facing an error during the serialization. I'm not sure it has been answered before.
I'm using the latest yolov5n model, that's the command I used for the export:
`python export.py --weights yolov5n_dot_two.pt --include engine --int8 --device 0 --imgsz 5056 > outputs.txt`

When a certain tactic appear for the Conv_3 operation, it seems to provoke an error, here is the last few lines of tensorrt in verbose mode :
`[04/07/2022-14:36:52] [TRT] [V] Conv_3 Set Tactic Name: sm70_xmma_fprop_implicit_gemm_f32f32_f32f32_f32_nhwckrsc_nhwc_tilesize64x256x8_stage1_warpsize1x4x1_g1_ffma Tactic: 929479145088554885
[04/07/2022-14:36:52] [TRT] [V] Deleting timing cache: 341 entries, 964 hits
[04/07/2022-14:36:52] [TRT] [E] 1: Unexpected exception `

One thing to note is that the export for fp32 and fp16 version works without any flaw and only the int8 version seems to have this error. I can attach my calibration.py file if necessary.

**Comment by glenn-jocher** [comment]
@LieceC not all combination of arguments are supported for all export formats. `--int8` is intended for CoreML and TFLite quantization, i.e.
https://github.com/ultralytics/yolov5/blob/b7faeda0f225f909ce87ffe504e829062ac44ca4/export.py#L554

If you'd like to try to extend int8 support to TRT that would be awesome though! 

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by LieceC** [comment]
Hello @glenn-jocher, I know its not supported as of now so I tried modify it by adding a calibration file and slightly modifying the `export_engine` function. I believe I have seen somehow talk about Int8 not having relevant results in one of the issues (Maybe the one that did the engine function ?).

**Comment by glenn-jocher** [comment]
@LieceC I don't know about the feasibility or requirements for INT8 TRT exports.

@imyhxy implemented the baseline export in https://github.com/ultralytics/yolov5/pull/5699 and then export was updated to forced FP16 mode in https://github.com/ultralytics/yolov5/pull/6798 by @DavidBaldsiefen. The current export is fixed at FP16 regardless of arguments, with the model automatically casting FP32 inputs to FP16 if necessary.

**Comment by LieceC** [comment]
I see, I'll look at it and see if I can find where that error come from

**Comment by RoyCopter** [comment]
> ### Search before asking
> 
>     * [x]  I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.
> 
> 
> ### Question
> 
> I have been trying for a while to modify the yolov5 code in order to export an int8 tensorrt engine on a jetson xavier AGX using tensorrt 8.2.3.0 on python 3.7. However, I am facing an error during the serialization. I'm not sure it has been answered before. I'm using the latest yolov5n model, that's the command I used for the export: `python export.py --weights yolov5n_dot_two.pt --include engine --int8 --device 0 --imgsz 5056 > outputs.txt`
> 
> When a certain tactic appear for the Conv_3 operation, it seems to provoke an error, here is the last few lines of tensorrt in verbose mode : `[04/07/2022-14:36:52] [TRT] [V] Conv_3 Set Tactic Name: sm70_xmma_fprop_implicit_gemm_f32f32_f32f32_f32_nhwckrsc_nhwc_tilesize64x256x8_stage1_warpsize1x4x1_g1_ffma Tactic: 929479145088554885 [04/07/2022-14:36:52] [TRT] [V] Deleting timing cache: 341 entries, 964 hits [04/07/2022-14:36:52] [TRT] [E] 1: Unexpected exception `
> 
> One thing to note is that the export for fp32 and fp16 version works without any flaw and only the int8 version seems to have this error. I can attach my calibration.py file if necessary.
> ### Additional
> 
> _No response_

@LieceC how did you manage to install tensorrt/pytorch and everthing with python3.7 on a Jetson platform?

**Comment by LieceC** [comment]
> > ### Search before asking
> > ```
> > * [x]  I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Question
> > I have been trying for a while to modify the yolov5 code in order to export an int8 tensorrt engine on a jetson xavier AGX using tensorrt 8.2.3.0 on python 3.7. However, I am facing an error during the serialization. I'm not sure it has been answered before. I'm using the latest yolov5n model, that's the command I used for the export: `python export.py --weights yolov5n_dot_two.pt --include engine --int8 --device 0 --imgsz 5056 > outputs.txt`
> > When a certain tactic appear for the Conv_3 operation, it seems to provoke an error, here is the last few lines of tensorrt in verbose mode : `[04/07/2022-14:36:52] [TRT] [V] Conv_3 Set Tactic Name: sm70_xmma_fprop_implicit_gemm_f32f32_f32f32_f32_nhwckrsc_nhwc_tilesize64x256x8_stage1_warpsize1x4x1_g1_ffma Tactic: 929479145088554885 [04/07/2022-14:36:52] [TRT] [V] Deleting timing cache: 341 entries, 964 hits [04/07/2022-14:36:52] [TRT] [E] 1: Unexpected exception `
> > One thing to note is that the export for fp32 and fp16 version works without any flaw and only the int8 version seems to have this error. I can attach my calibration.py file if necessary.
> > ### Additional
> > _No response_
> 
> @LieceC how did you manage to install tensorrt/pytorch and everthing with python3.7 on a Jetson platform?

I compiled them from source

**Comment by LieceC** [comment]
I suspect the problem comes from the TensorRT python bindings, generating an int8 file from the trtexec command seems to work without any issue.
