### ISSUE TITLE
i want to know how to resume before train!

### ISSUE THREAD

**Issue by orayel** [ultralytics/yolov5#734]
wo can tell me how to resume before train?
i use : python train.py --data data/config.yaml --cfg models/yolov5s.yaml --resume  
but it start training from 0 epochs rather than training before epoch!

**Comment by glenn-jocher** [comment]
@Lionalsocat you don't need to supply a cfg yaml if you are resuming.

**Comment by orayel** [comment]
> @Lionalsocat you don't need to supply a cfg yaml if you are resuming.

excuse , i try without cfg yaml  ,  but it still training from zero epoch. can you tell me what format should i input?
i use : python train.py --data data/config.data --resume 
it still training from zero epoch
thank you for your time
