### ISSUE TITLE
Is there also mAP 0.5,0.95 in val.py?

### ISSUE THREAD

**Issue by st162053** [ultralytics/yolov5#7352]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, 

is it possible to get the mAP 0.5,0.95 when using val.py (task test) on an annotated test dataset? Because I found the mAP 0.5 on the generated PR-plot, but I'd also like to compare the mAP 0.5,0.95. 

Thanks!

**Comment by glenn-jocher** [comment]
@st162053 yes:
```
python val.py --task test
```

**Comment by st162053** [comment]
Overlooked it! My bad
