### ISSUE TITLE
Prediction from backbone 

### ISSUE THREAD

**Issue by goo-goo-goo-joob** [ultralytics/yolov5#7354]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,

How can I get the prediction from backbone layer from already trained model?

Thank you!

**Comment by glenn-jocher** [comment]
@goo-goo-goo-joob the 'backbone' of YOLOv5 models don't produce any predictions, they run convolutions and sequentially downsample the image to larger strides. They have output feature grids (like all layers). Detections (at each of the different scales, i.e. P3, P4, P5 etc) are only produced in the final `Detect()` layer at the end of the model. You can see the model architectures in each model yaml, i.e.:

https://github.com/ultralytics/yolov5/blob/3bb233a7fb5b23e8128855eba1aaf347b1e86f49/models/yolov5s.yaml#L12-L48

**Comment by goo-goo-goo-joob** [comment]
@glenn-jocher Is there a possibility to get raw output vector (feature grids) from backbone?

**Comment by glenn-jocher** [comment]
@goo-goo-goo-joob there's a possibility to do anything you want if you put the work in.

**Comment by glenn-jocher** [comment]
@goo-goo-goo-joob you can visualize these feature grids by the way with detect.py --visualize. If you follow the visualize code you can see where to access the feature grids. See https://github.com/ultralytics/yolov5/pull/3920 for example.
