### ISSUE TITLE
Train and Google_utils error

### ISSUE THREAD

**Issue by Reolki** [ultralytics/yolov5#7355]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

When i try to train on a dataset，some error message from train.py, and google_utils.py.  This problem is similar to Custom Weight Training error #355, but I can't solve the problem.  here is it:

Apex recommended for faster mixed precision training: https://github.com/NVIDIA/apex
{'lr0': 0.01, 'momentum': 0.937, 'weight_decay': 0.0005, 'giou': 0.05, 'cls': 0.58, 'cls_pw': 1.0, 'obj': 1.0, 'obj_pw': 1.0, 'iou_t': 0.2, 'anchor_t': 4.0, 'fl_gamma': 0.0, 'hsv_h': 0.014, 'hsv_s': 0.68, 'hsv_v': 0.36, 'degrees': 0.
0, 'translate': 0.0, 'scale': 0.5, 'shear': 0.0}
Namespace(epochs=1000, batch_size=3, cfg='models/yolov5x.yaml', data='data/coco128.yaml', img_size=[1024, 1024], rect=False, resume=False, nosave=False, notest=False, noautoanchor=False, evolve=False, bucket='', cache_images=False, w
eights='weights/best.pt', name='', device='', adam=False, multi_scale=False, single_cls=False)
Using CPU

Start Tensorboard with "tensorboard --logdir=runs", view at http://localhost:6006/
Overriding models/yolov5x.yaml nc=1 with nc=15

                 from  n    params  module                                  arguments
  0                -1  1      8800  models.common.Focus                     [3, 80, 3]
  1                -1  1    115520  models.common.Conv                      [80, 160, 3, 2]
  2                -1  1    315680  models.common.BottleneckCSP             [160, 160, 4]
  3                -1  1    461440  models.common.Conv                      [160, 320, 3, 2]
  4                -1  1   3311680  models.common.BottleneckCSP             [320, 320, 12]                
  5                -1  1   1844480  models.common.Conv                      [320, 640, 3, 2]              
  6                -1  1  13228160  models.common.BottleneckCSP             [640, 640, 12]                
  7                -1  1   7375360  models.common.Conv                      [640, 1280, 3, 2]             
  8                -1  1   4099840  models.common.SPP                       [1280, 1280, [5, 9, 13]]      
  9                -1  1  20087040  models.common.BottleneckCSP             [1280, 1280, 4, False]        
 10                -1  1    820480  models.common.Conv                      [1280, 640, 1, 1]
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 12           [-1, 6]  1         0  models.common.Concat                    [1]
 13                -1  1   5435520  models.common.BottleneckCSP             [1280, 640, 4, False]         
 14                -1  1    205440  models.common.Conv                      [640, 320, 1, 1]
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 16           [-1, 4]  1         0  models.common.Concat                    [1]
 17                -1  1   1360960  models.common.BottleneckCSP             [640, 320, 4, False]          
 18                -1  1     19260  torch.nn.modules.conv.Conv2d            [320, 60, 1, 1]
 19                -2  1    922240  models.common.Conv                      [320, 320, 3, 2]
 20          [-1, 14]  1         0  models.common.Concat                    [1]
 21                -1  1   5025920  models.common.BottleneckCSP             [640, 640, 4, False]          
 22                -1  1     38460  torch.nn.modules.conv.Conv2d            [640, 60, 1, 1]
 23                -2  1   3687680  models.common.Conv                      [640, 640, 3, 2]              
 24          [-1, 10]  1         0  models.common.Concat                    [1]
 25                -1  1  20087040  models.common.BottleneckCSP             [1280, 1280, 4, False]        
 26                -1  1     76860  torch.nn.modules.conv.Conv2d            [1280, 60, 1, 1]
 27      [-1, 22, 18]  1         0  models.yolo.Detect                      [15, [[116, 90, 156, 198, 373, 326], [30, 61, 62, 45, 59, 119], [10, 13, 16, 30, 33, 23]]]
Model Summary: 407 layers, 8.85279e+07 parameters, 8.85279e+07 gradients

Optimizer groups: 134 .bias, 142 conv.weight, 131 other
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: 'storage.googleapis.com
Traceback (most recent call last):
  File "E:\yo\DefectDetection\train.py", line 395, in <module>
    train(hyp)
  File "E:\yo\DefectDetection\train.py", line 112, in train
    google_utils.attempt_download(weights)
  File "E:\yo\DefectDetection\utils\google_utils.py", line 36, in attempt_download
    raise Exception(msg)
Exception: weights/best.pt missing, try downloading from https://drive.google.com/drive/folders/1Drs_Aiu7xx6S-ix95f9kNsA6ueKRpN2J

I don't know how to fix. Any help would be appreciated, thanks
I tried using https://github.com/ultralytics/yolov5/commit/d3e786ed934d6b1652cf19ee986ca75f4a36461e to solve the problem, but the results did not change

**Comment by glenn-jocher** [comment]
@Reolki your code is extremely old. Use current master.

**Comment by Aarush-Aggarwal** [comment]
@Reolki Hi, I don't think yolov5.utils has google_utils now. I have seen a lot many users complain about issues related to google_utils, importing, etc. It seems the code that you are using is somewhat obsolete compared to the one currently in yolov5 master. Check out the source code [here](https://github.com/ultralytics/yolov5).
