### ISSUE TITLE
questions about the feature map visualize

### ISSUE THREAD

**Issue by mcjqwer** [ultralytics/yolov5#7356]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Firstly, after doing the visualisation of the feature maps, I see that a feature map for each layer is generated and that each image has several rows and columns of sub-maps, what does this mean for each sub-map?
Secondly, I encountered the error that there was no gradient backpropagation when I used Grad-Cam for visualisation and used the visualisation provided by the author, which is very convenient, so what is the difference between this and grad-cam and how did you do your visualisation?
![stage6_C3_features](https://user-images.githubusercontent.com/59089548/162580270-59575919-15ff-4cda-af84-e00d4eab2fd6.png)

**Comment by glenn-jocher** [comment]
@mcjqwer first 32 channels of any grid. YOLOv5 layers each output hundreds or thousands of channels. There is no gradient here, these are features.
