### ISSUE TITLE
how to set learning rate?

### ISSUE THREAD

**Issue by wenjiett** [ultralytics/yolov5#7357]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello! I have a question about how to set the learning rate?
I want to know  whether the default learning rate is applicable to running on multiple GPU. If I use a single GPU, how to set the learning rate?

**Comment by glenn-jocher** [comment]
@HelloAI-twj use default hyps and settings. No changes are required for Multi-GPU.

**Comment by wenjiett** [comment]
> @HelloAI-twj use default hyps and settings. No changes are required for Multi-GPU.

If I use single GPU, do I need to adjust the default learning rate?

**Comment by glenn-jocher** [comment]
@HelloAI-twj use default hyps and settings
