### ISSUE TITLE
Trying to plot TP, TN, FP, FN against detection threshold in val.py

### ISSUE THREAD

**Issue by JosepBC** [ultralytics/yolov5#7358]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Hello, I'm trying to plot TP, TN, FP, FN against the detection threshold after validation is performed.

To do so I tried saving detections and labels passed to procecess batch function from ConfusionMatrix class
https://github.com/ultralytics/yolov5/blob/aa542ce6a65658ff931fee9bbab77c0145c152f0/utils/metrics.py#L125
and then in a jupyter notebook I'm trying to do the plots.

I implemented this little function inside the ConfusionMatrix class to obtain all the values
```python    
def metrics(self, normalize=True):
    tp = self.matrix.diagonal()
    fp = self.matrix.sum(axis=1) - tp
    fn = self.matrix.sum(axis=0) - tp
    tn = self.matrix.sum() - (tp + fp + fn)

    if normalize:
        gtPositives = self.matrix.sum(axis=0)
        gtNegatives = gtPositives.sum() - gtPositives
        tp = tp / gtPositives
        fn = fn / gtPositives
        tn = tn / gtNegatives
        fp = fp / gtNegatives
    return tp[:-1], fp[:-1], fn[:-1], tn[:-1] # remove background class
```

that basically is an extension of this function
https://github.com/ultralytics/yolov5/blob/aa542ce6a65658ff931fee9bbab77c0145c152f0/utils/metrics.py#L168

And then just created a new object on the ConfusionMatrix per threshold, obtained this metrics and ploted one plot per class with all the metrics using matplotlib.

The problem is that this plots have no sense at all. For example, true positives for detection threshold=0 should be 1 and the value should be lower as threshold increases, but it's not. In some classes it increases a little bit with a higher threshold, and as I far as I understand, this shouldn't happen

Am I doing something wrong? I can't use the detections and labels from process_batch for this purpose?

I'm saving and loading the variables with pickle, tried plotting the confusion matrix for detection threshold=0.25 and is the same plot as the one that is saved while running val.py so I assume that the save/load process is ok.

Thank you!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@JosepBC TP, FP values are already available in val.py:
https://github.com/ultralytics/yolov5/blob/aa542ce6a65658ff931fee9bbab77c0145c152f0/val.py#L270

**Comment by JosepBC** [comment]
Yes but just for one threshold, you sugest making n (number of dessired thresholds) calls to this function to obtain TP and FP for each threshold and from there calculate FN an and TN using the recall and tp, fn?

**Comment by glenn-jocher** [comment]
Well, if you want the confusion matrix at different conf then you could just run it at a few different values by setting conf=0.1, 0.5, 0.9 etc. here:
https://github.com/ultralytics/yolov5/blob/aa542ce6a65658ff931fee9bbab77c0145c152f0/utils/metrics.py#L117-L119

The P-R curve that mAP is based on is already evaluated at 100 different confidences BTW. The main point of the metric is to establish a value that includes all possible confidence thresholds.
