### ISSUE TITLE
Model performing much worse when not using detect.py for inference

### ISSUE THREAD

**Issue by Powercube7** [ultralytics/yolov5#7367]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

Hi! I recently trained a model on ~270 images for training and ~50 for validation and one thing I remarked is that the model performs much worse when not using the official detect.py file. When using detect.py my model would have an accuracy around 85% while not using it leads to less than 10% in certain classes (even if well-represented). Is there anything I can do to get my results similar to the detect.py file?

### Environment

-OS: Windows 10
-Python: 3.8.0

### Minimal Reproducible Example

code for detect.py inference: python detect.py (pretty obvious)
without detect.py: using the model(img) function

### Additional

Samples of each of the 2 options: https://we.tl/t-azCCFVdhNK

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Powercube7 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, etc.
# model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')  # custom trained model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by Powercube7** [comment]
@glenn-jocher do you think that the warm up that detect.py has makes it better? if so, is there anything I can do to add it to my script?

**Comment by syedwaleedhyder** [comment]
@Powercube7 Can you share the code snippet here to reproduce the problem?

**Comment by Powercube7** [comment]
@syedwaleedhyder here it is, nothing special about it
https://gist.github.com/Powercube7/c93fed855d7c05553f9d0c3181dea366

**Comment by syedwaleedhyder** [comment]
@Powercube7 Try rescaling the input image from 0-255 to 0.0 - 1.0 before passing it to the model.
`frame /= 255`

**Comment by Powercube7** [comment]
@syedwaleedhyder dividing the frame by 255 leads to me getting a black image

**Comment by syedwaleedhyder** [comment]
You need to convert the data type of image to float and scale it to 0-1.  
Here is the way this repository uses for inference. 

`im = torch.from_numpy(im).to(device) `
` im = im.float()  # uint8 to fp16/32 `
` im /= 255  # 0 - 255 to 0.0 - 1.0 `

**Comment by Powercube7** [comment]
b, ch, h, w = im.shape  # batch, channel, height, width
ValueError: not enough values to unpack (expected 4, got 3)
![image](https://user-images.githubusercontent.com/80365192/162703219-864c542b-8baa-461a-a262-67f1e0ccc47a.png)
here is what i changed

**Comment by Powercube7** [comment]
@syedwaleedhyder trying to use only these gives me an error due to lack of batches. Passing in frame = frame[None] like the repository does says the following:

RuntimeError: Given groups=1, weight of size [32, 3, 6, 6], expected input[1, 360, 640, 3] to have 3 channels, but got 360 channels instead

Image size: torch.Size([1, 360, 640, 3])

**Comment by glenn-jocher** [comment]
@syedwaleedhyder zero preprocessing is required with YOLOv5 PyTorch Hub models, none of the steps you mentioned are mentioned anywhere in our documentation.

@syedwaleedhyder your cv2 usage is incorrect. See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details as https://github.com/ultralytics/yolov5/issues/7367#issuecomment-1094364687 states

**Comment by syedwaleedhyder** [comment]
@Powercube7 As @glenn-jocher pointed out in the documentation, you need to convert BGR images to RGB if you use cv2 to read the image.
`im2 = cv2.imread('bus.jpg')[..., ::-1]  # OpenCV image (BGR to RGB)`

**Comment by Powercube7** [comment]
@glenn-jocher thanks for the intervertion. Do you know if there is anything different between the model() function and detect.py? If so, could you tell me what it is so I can integrate it inside my script?

**Comment by glenn-jocher** [comment]
@Powercube7 hub inference is very simple, there's nothing to overthink. Just follow the correct cv2 usage example as in https://github.com/ultralytics/yolov5/issues/7367#issuecomment-1094834397

**Comment by Powercube7** [comment]
@glenn-jocher I am using the hub inference and it works. My issue is that it works worse than the detect.py inference. I left some video samples at the top. The differences are huge

**Comment by glenn-jocher** [comment]
@Powercube7 detect.py and pytorch hub inference produce identical results. 

As I've repeated multiple times, your cv2 usage is incorrect. Incorrect usage will logically produce incorrect results.

**Comment by glenn-jocher** [comment]
Bug report closed, error is due to user error.

**Comment by Powercube7** [comment]
@glenn-jocher is there any resource about inference on videos? I am only finding images in the linked tutorial, and cap.read() basically is cv2.imread for every frame

**Comment by glenn-jocher** [comment]
@Powercube7 https://github.com/ultralytics/yolov5/issues/7367#issuecomment-1094834397

**Comment by Powercube7** [comment]
OHHHHHHHH!! I finally got it, thank you for your patience dealing with my dumb brain @glenn-jocher @syedwaleedhyder
