### ISSUE TITLE
Is there a way different than Pandas to read bounding box data?

### ISSUE THREAD

**Issue by RRighart** [ultralytics/yolov5#7368]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am using Yolov5 for training and torch.hub.load for loading the trained model.
Using Pandas, I am able to get a nice table with boundary box information. 

    results = model(img, size=640)
    df = results.pandas().xyxy[0]

As Pandas can become memory intense, I was wondering if there is a different way of loading the same data, using for example Numpy. I would be very grateful for any useful reference on this topic!

**Comment by glenn-jocher** [comment]
@RRighart see PyTorch Hub Tutorial for readout options.


## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️  RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Roboflow for Datasets, Labeling, and Active Learning](https://docs.ultralytics.com/yolov5/tutorials/roboflow_datasets_integration)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TFLite, ONNX, CoreML, TensorRT Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [Architecture Summary](https://docs.ultralytics.com/yolov5/tutorials/architecture_description)&nbsp; ⭐ NEW

Good luck 🍀 and let us know if you have any other questions!

**Comment by RRighart** [comment]
Thank you ! I have seen the PyTorch Hub Tutorial.
Actually I realise that the Numpy solution depends on counting and selecting the right columns manually, which can be dangerous if other columns are inserted at some point. For ex. if I need confidence scores, I need to put 4:

```
arr = results.xyxy[0].cpu().numpy()
arr[:,4]  

```
You also present the json method. I was wondering, is there a way to avoid using pandas in the middle? 

`d = results.pandas().xyxy[0].to_json(orient='records')`

**Comment by glenn-jocher** [comment]
@RRighart the standard outputs are tensors. You're free to do anything you want with them.
