### ISSUE TITLE
How to use soft-nms?

### ISSUE THREAD

**Issue by c464851257** [ultralytics/yolov5#737]

**Comment by glenn-jocher** [comment]
@c464851257 see https://arxiv.org/abs/1704.04503

**Comment by shenyi0220** [comment]
A better box clustering framework is proposed here(https://github.com/shenyi0220/CP-Cluster), as shows better accuracy compared NMS/Soft-NMS. All Yolo5(v4,v6) models can be improved by this brandnew post-processing method.

**Comment by glenn-jocher** [comment]
@shenyi0220 very interesting, thanks for the link!

**Comment by smsver2** [comment]
@glenn-jocher I was wondering if Soft-NMS or CP-Cluster has been integrated into the current version of the codebase(or in yolov8 version). I understand that CP-Cluster may have licensing restrictions, so I'm not particularly optimistic about its availability in a CUDA-supported version. However, any information you could provide would be greatly appreciated.

I am particularly interested in person detection under high occlusion scenarios. After some research, it appears that Soft-NMS could significantly reduce the number of discarded high-occlusion boxes. However, if you have any insights or recommendations for handling high occlusion cases, I would greatly appreciate your expertise.

**Comment by glenn-jocher** [comment]
@smsver2 soft-NMS and CP-Cluster have not been integrated into the current version of the YOLOv5 codebase or in the yolov8 version. While Soft-NMS can be effective in reducing the number of discarded high-occlusion boxes, it may not be the optimal solution for handling such scenarios. 

For person detection under high occlusion scenarios, I recommend exploring other techniques such as data augmentation, using higher-resolution images, or applying object tracking algorithms to track and maintain the identity of occluded objects. These techniques can help improve detection performance in challenging scenarios. 

However, please note that YOLOv5 is a general-purpose object detection framework, and it may not have specific optimizations or techniques specifically tailored for high occlusion scenarios out-of-the-box. You may need to experiment with different approaches and customize the model and post-processing steps based on your specific requirements.

Thank you for your interest in YOLOv5, and I hope this information helps you in handling high occlusion cases effectively.
