### ISSUE TITLE
ValueError: optimizer got an empty parameter list when using group normalization instead of batch normalization in yolov5

### ISSUE THREAD

**Issue by vardanagarwal** [ultralytics/yolov5#7375]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am trying to use group normalization as the batch size I can use is small due to memory constraints. To do that I am changing the code in [common.py][1].

    class Conv(nn.Module):
        # Standard convolution
        def __init__(self, c1, c2, k=1, s=1, p=None, g=1, act=True):  # ch_in, ch_out, kernel, stride, padding, groups
            super().__init__()
            self.conv = nn.Conv2d(c1, c2, k, s, autopad(k, p), groups=g, bias=False)
            self.bn = nn.BatchNorm2d(c2)
            self.act = nn.SiLU() if act is True else (act if isinstance(act, nn.Module) else nn.Identity())
    
        def forward(self, x):
            return self.act(self.bn(self.conv(x)))
    
        def forward_fuse(self, x):
            return self.act(self.conv(x))

In this code, the only change done is `self.bn = nn.BatchNorm2d(c2)` to `self.bn = nn.GroupNorm(8, c2)`

Now, when trying to run with the command: `python3 train.py --data data/coco128.yaml --weights '' --cfg models/yolov5s.yaml --hyp data/hyps/hyp.scratch-low.yaml --epochs 300 --batch 16 --img 640`, I get this error.

    Traceback (most recent call last):
      File "train.py", line 643, in <module>
        main(opt)
      File "train.py", line 539, in main
        train(opt.hyp, opt, device, callbacks)
      File "train.py", line 170, in train
        optimizer = SGD(g0, lr=hyp['lr0'], momentum=hyp['momentum'], nesterov=True)
      File "/home/dori/env3.8/lib/python3.8/site-packages/torch/optim/sgd.py", line 101, in __init__
        super(SGD, self).__init__(params, defaults)
      File "/home/dori/env3.8/lib/python3.8/site-packages/torch/optim/optimizer.py", line 49, in __init__
        raise ValueError("optimizer got an empty parameter list")
    ValueError: optimizer got an empty parameter list

  [1]: https://github.com/ultralytics/yolov5/blob/master/models/common.py

**Comment by glenn-jocher** [comment]
@vardanagarwal if you're going to try new layers you should probably read the docs first so you understand them:

<img width="1432" alt="Screenshot 2022-04-11 at 12 09 38" src="https://user-images.githubusercontent.com/26833433/162717040-3cb3215e-0299-46f4-8bf9-c5d784cf6db9.png">

**Comment by glenn-jocher** [comment]
@vardanagarwal might want to try debugging at a smaller level before running a full model
https://pytorch.org/docs/stable/generated/torch.nn.GroupNorm.html

**Comment by glenn-jocher** [comment]
@vardanagarwal seems like this is due to LR assignment groups here:
https://github.com/ultralytics/yolov5/blob/71685cbf91a9f60eb2f9c46ced8fa7becf6813d9/train.py#L153-L161

**Comment by glenn-jocher** [comment]
@vardanagarwal good news 😃! Your original issue may now be fixed ✅ in PR #7376. This PR reorganizes optimizer parameter group inits for robustness to missing BatchNorm2d layers in a model. Your use-case trains correctly now, but note that your normalization layer weights will now see weight decay, which is probably contrary to best practices. You can update train.py to include any custom normalization layers in group 0, which is excluded from weight decay.

<img width="2174" alt="Screenshot 2022-04-11 at 12 31 59" src="https://user-images.githubusercontent.com/26833433/162722582-22703f69-acc0-497e-badd-7caa1a500547.png">



To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by vardanagarwal** [comment]
@glenn-jocher thanks for the help, I am able to fix it by adding the group normalization layer.
`if isinstance(v, nn.BatchNorm2d) or isinstance(v, nn.GroupNorm):`

**Comment by glenn-jocher** [comment]
@vardanagarwal ah yes, this is a good solution also. Can you please submit a PR to include GroupNorm and any other applicable normalization layer on this line? 

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by vardanagarwal** [comment]
Sure, I'll do that.
