### ISSUE TITLE
True positive (TP), False positive (FP), False Negative (FN)

### ISSUE THREAD

**Issue by JanErikDoornweerd** [ultralytics/yolov5#7378]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Read multiple papers and questions on this repository but was unable to find an answer that satisfied me. 

Code below is referenced with regards to determining TP, FP and FN

https://github.com/ultralytics/yolov5/blob/8efe97719c9b3b77c9db9b5c8592e051b7f0c9a7/utils/metrics.py#L82-L86

ap_per_class gets its input from

https://github.com/ultralytics/yolov5/blob/4c7b2bdc30657354afcbc255385a163662e66c8b/val.py#L59-L80

Which gives IoU above threshold and classes match

Determines confidence threshold on max F1 confidence.

https://github.com/ultralytics/yolov5/blob/8efe97719c9b3b77c9db9b5c8592e051b7f0c9a7/utils/metrics.py#L82

Thus, i * 0.001001 = confidence threshold.

Just for my understanding, and for future reference with everything in one place. 
Would someone be able to confirm or disconfirm the below?

True positive if:

    Confidence > Confidence threshold [Determined by max F1 confidence]
    Class matches ground truth class
    IOU > 0.5 [As per iou >= iouv[0]]

False positive if:

    Class does not match ground truth class
    IOU <= 0.5 [As per iou >= iouv[0]]

False negative if:

    Confidence <= Confidence threshold [Determined by max F1 confidence]

**Comment by glenn-jocher** [comment]
@TheCrafft basically a TP has the correct class predicted and meets both IoU and confidence thresholds, FP is the same with an incorrect class predicted, and FN does not meet the requirements for a TP. See https://en.wikipedia.org/wiki/Precision_and_recall for a good chart explaining how these all relate to Precision and Recall.

**Comment by JanErikDoornweerd** [comment]
@glenn-jocher Thanks!
So it is correct, except for FP which should be confidence > confidence threshold but either class does not match or IOU <= 0.5.

**Comment by Zephyr69** [comment]
Kind of off-topic but I have a somewhat related question.

In many applications we don't care if the classification is correct as much as if a target has been detected. For example, when doing vehicle detections with some road cam, whether the predicted object is actually a vehicle may be much more important than whether its classification (car, bus, bike, etc.) is correct; though the classification still matters to some degree.

Seeing that currently a correct object localization with wrong classification wouldn't be counted as a true positive, I wonder if it makes sense to have an additional set of metrics that takes the weighted combination between correct localizations with correct classification and with wrong classification as the "true positives".

**Comment by glenn-jocher** [comment]
@Zephyr69 you can train and val any dataset in `--single-cls` mode
