### ISSUE TITLE
Pretrained Weights: ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group

### ISSUE THREAD

**Issue by CarlChaaya** [ultralytics/yolov5#7379]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

I started training my custom Yolov5 model, and after around 250 epochs, I saved my best.pt weights. I am now trying to continue the training with the same saved weights, but I get the following error:

"""
train: weights=/content/best_mAP_0.606_ep_203.pt, cfg=, data=/content/datasets/AgriDocDetection-2/data.yaml, hyp=data/hyps/hyp.scratch-low.yaml, epochs=10, batch_size=16, imgsz=416, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, evolve=None, bucket=, cache=ram, image_weights=False, device=, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=8, project=runs/train, name=exp, exist_ok=False, quad=False, cos_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest
github: up to date with https://github.com/ultralytics/yolov5 ✅
YOLOv5 🚀 v6.1-127-gfa569cd torch 1.10.0+cu111 CUDA:0 (Tesla K80, 11441MiB)

hyperparameters: lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0
Weights & Biases: run 'pip install wandb' to automatically track and visualize YOLOv5 🚀 runs (RECOMMENDED)
TensorBoard: Start with 'tensorboard --logdir runs/train', view at http://localhost:6006/

                 from  n    params  module                                  arguments                     
  0                -1  1      3520  models.common.Conv                      [3, 32, 6, 2, 2]              
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]                
  2                -1  1     18816  models.common.C3                        [64, 64, 1]                   
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]               
  4                -1  2    115712  models.common.C3                        [128, 128, 2]                 
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]              
  6                -1  3    625152  models.common.C3                        [256, 256, 3]                 
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]              
  8                -1  1   1182720  models.common.C3                        [512, 512, 1]                 
  9                -1  1    656896  models.common.SPPF                      [512, 512, 5]                 
 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]              
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 12           [-1, 6]  1         0  models.common.Concat                    [1]                           
 13                -1  1    361984  models.common.C3                        [512, 256, 1, False]          
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]              
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 16           [-1, 4]  1         0  models.common.Concat                    [1]                           
 17                -1  1     90880  models.common.C3                        [256, 128, 1, False]          
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]              
 19          [-1, 14]  1         0  models.common.Concat                    [1]                           
 20                -1  1    296448  models.common.C3                        [256, 256, 1, False]          
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]              
 22          [-1, 10]  1         0  models.common.Concat                    [1]                           
 23                -1  1   1182720  models.common.C3                        [512, 512, 1, False]          
 24      [17, 20, 23]  1    124062  models.yolo.Detect                      [41, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
Model summary: 270 layers, 7130206 parameters, 7130206 gradients, 16.2 GFLOPs

Transferred 349/349 items from /content/best_mAP_0.606_ep_203.pt
Scaled weight_decay = 0.0005
optimizer: SGD with parameter groups 57 weight (no decay), 60 weight, 60 bias
Traceback (most recent call last):
  File "train.py", line 667, in <module>
    main(opt)
  File "train.py", line 562, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 191, in train
    optimizer.load_state_dict(ckpt['optimizer'])
  File "/usr/local/lib/python3.7/dist-packages/torch/optim/optimizer.py", line 146, in load_state_dict
    raise ValueError("loaded state dict contains a parameter group "
ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group
"""

I have tried to update yolov5 (I used git pull) and am still getting the same error.

Please help.

### Minimal Reproducible Example

The following is the code run that lead to the error:

"""
python train.py --img 416 --batch 16 --epochs 100 --data {dataset.location}/data.yaml --weights /content/best.pt --cache
"""

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CarlChaaya** [comment]
Found the solution:

Run:
"""
python -c "from utils.general import *; strip_optimizer('path/to/best.pt')"
"""
And then retrain.

This is the case when you continue training with models that have not finished training first.

**Comment by glenn-jocher** [comment]
@CarlChaaya 👋 Hello! Thanks for asking about **resuming training**. YOLOv5 🚀 Learning Rate (LR) [schedulers](https://github.com/ultralytics/yolov5/blob/aa542ce6a65658ff931fee9bbab77c0145c152f0/train.py#L175-L181) follow predefined LR curves for the fixed number of `--epochs` defined at training start (`default=300`), and are designed to fall to a minimum LR on the final epoch for best training results. For this reason you can not modify the number of epochs once training has started.

<img width="850" alt="Screenshot 2022-04-10 at 11 11 51" src="https://user-images.githubusercontent.com/26833433/162611202-4e0b611f-6cca-4e43-94fc-bbc44e6447f8.png">

If your training was **interrupted** for any reason you may continue where you left off using the `--resume` argument. If your training fully completed, you can start a **new** training from any model using the `--weights` argument. Examples:

## Resume Single-GPU

You may not change settings when resuming, and **no additional arguments** other than `--resume` should be passed, with an optional path to the checkpoint you'd like to resume from. If no checkpoint is passed the most recently updated `last.pt` in your `yolov5/` directory is automatically found and used:
```bash
python train.py --resume  # automatically find latest checkpoint (searches yolov5/ directory)
python train.py --resume path/to/last.pt  # specify resume checkpoint
```

## Resume Multi-GPU

[Multi-GPU DDP trainings](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) must be resumed with the same GPUs and DDP command, i.e. assuming 8 GPUs:
```bash
python -m torch.distributed.run --nproc_per_node 8 train.py --resume  # resume latest checkpoint
python -m torch.distributed.run --nproc_per_node 8 train.py --resume path/to/last.pt  # specify resume checkpoint
```

## Start from Pretrained

If you would like to **start training** from a fully trained model, use the `--weights` argument, not the `--resume` argument:
```bash
python train.py --weights path/to/best.pt  # start from pretrained model
```

Good luck 🍀 and let us know if you have any other questions!

**Comment by Kerwinooooo** [comment]
> Found the solution:
> 
> Run: """ python -c "from utils.general import *; strip_optimizer('path/to/best.pt')" """ And then retrain.
> 
> This is the case when you continue training with models that have not finished training first.

It is helpful, but it reset the epoch of pt to -1.

**Comment by yolor2** [comment]
Hello,  i am new to this field and could you @glenn-jocher please explain me difference between lr0, lr1 and lr2.

**Comment by glenn-jocher** [comment]
@yolor2 the YOLOv5 weights and biases are divided up into 3 groups that are optimized differently, lr0 through lr2. This is to exempt biases from weight decay mostly.

**Comment by yolor2** [comment]
@glenn-jocher  could you please explain me the significance of it. Just in short.

**Comment by glenn-jocher** [comment]
weight decay should not be applied to biases. The learning rate groups implement this.

**Comment by Ahwar** [comment]
> @CarlChaaya 
> 
> ## Start from Pretrained
> If you would like to **start training** from a fully trained model, use the `--weights` argument, not the `--resume` argument:
> 
> ```shell
> python train.py --weights path/to/best.pt  # start from pretrained model
> ```
> 
> Good luck 🍀 and let us know if you have any other questions!  

I was working on another project with two options, load only `--weights` and `--resume,` thanks to your answer; shifting from `resume` to `weights` resolved the issue.  
Thanks again

**Comment by glenn-jocher** [comment]
@Ahwar glad to hear that shifting from `--resume` to `--weights` resolved the issue for you. Using the `--weights` argument allows you to start training from a fully trained model. If you have any other questions or need further assistance, feel free to ask. Good luck with your project!

**Comment by nguyenthekhoig7** [comment]
> Found the solution:
> 
> Run: """ python -c "from utils.general import *; strip_optimizer('path/to/best.pt')" """ And then retrain.

Hi @CarlChaaya, I tried your solution but got an error `ModuleNotFoundError: No module named 'utils'`. 

**So my question is:** Where is the utils file above locate, does it belongs to the installed ultalytics folder?
Please help me, thank you!
