### ISSUE TITLE
When I training my own dataset, I find the train_batch0.jpg in ./runs folder is incorrect. 

### ISSUE THREAD

**Issue by learncrazy** [ultralytics/yolov5#738]
## ❔Question

I want to ask some questions. What is the the train_batch.jpg in ./run ? Is this picture before or after the prediction? **I found that the box in this picture doesn't match the object I marked.** I heard that this picture is the result of enhanced data. If the frame does not correspond to the object, it means there is a problem with the data. So I checked the data label again and found no problem.  So is my situation normal? If it is not normal, what is the problem?

**Comment by glenn-jocher** [comment]
@learncrazy if objects are not labelled correctly in your train and test jpgs, your labels are not correct.

**Comment by learncrazy** [comment]
Thank you for your answer. 

0 0.452381 0.160549 0.161210 0.140542
This is the number 10 label.

![10](https://user-images.githubusercontent.com/50286586/90221416-c3a50f80-de3c-11ea-92c7-1e2363f028e4.jpg)
This is the number 10 image.

![train_batch2](https://user-images.githubusercontent.com/50286586/90222220-395dab00-de3e-11ea-995a-10ff8db892ca.jpg)
This is train_batch2.jpg.

I checked and found that there is no problem with the standard.
The strange thing is that only a very small part of the tags in train.jpg are wrong. 
I will try to relabel or check again.

**Comment by glenn-jocher** [comment]
@learncrazy seems like the 109.jpg label might be wrong?

**Comment by learncrazy** [comment]
Yes, but the 10.jpg also is wrong. It may be that there was a problem in the production of my dataset. Let me try it with the coco128 data set first. Thank you so much for your help.

**Comment by Lishumuzixin** [comment]
> Yes, but the 10.jpg also is wrong. It may be that there was a problem in the production of my dataset. Let me try it with the coco128 data set first. Thank you so much for your help.
Hello,I have the same problem. Have you solved it?

**Comment by Lishumuzixin** [comment]
> Yes, but the 10.jpg also is wrong. It may be that there was a problem in the production of my dataset. Let me try it with the coco128 data set first. Thank you so much for your help.

Hello,I have the same problem. Have you solved it?

**Comment by glenn-jocher** [comment]
@Lishumuzixin hello, thank you for reaching out. If you are encountering wrong labels in your dataset, it is likely that there is an issue with the data preparation or labelling process. Double-checking the labels and making sure they correspond accurately to the objects in the images is crucial. Additionally, it might be helpful to try training with a publicly available dataset like coco128 to see if the issue persists. If you continue to experience problems, please provide more details and we'll be glad to assist you further.
