### ISSUE TITLE
LazyInstanceNorm2d need torch>=1.10

### ISSUE THREAD

**Issue by Beb007** [ultralytics/yolov5#7381]
Hello,

Fantastic work !
I faced an issue with my latest run:

```
Traceback (most recent call last):
  File "train.py", line 667, in <module>
    main(opt)
  File "train.py", line 562, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 154, in train
    bn = nn.BatchNorm2d, nn.LazyBatchNorm2d, nn.GroupNorm, nn.InstanceNorm2d, nn.LazyInstanceNorm2d, nn.LayerNorm
AttributeError: module 'torch.nn' has no attribute 'LazyInstanceNorm2d'

```
LazyInstanceNorm2d seems to be included from torch version 1.10, and not present in 1.9.1 usually used from Kaggle 

I tried pip install torch==1.11 (latest) but got packages conflicts
With torch=1.10, no conficts, but faced another issue with protobuf. 
My first though was to suggest a change in requirements, but, as theses packages conflicts can become really awkward...  I leave it for now and just report it...

Best regards

PS: my bad, I should had put this in issue section

_Originally posted by @Beb007 in https://github.com/ultralytics/yolov5/discussions/7380_

**Comment by Beb007** [comment]
Temporary, I use 'classifier' branch and it's working fine. 
> git clone --branch classifier https://github.com/ultralytics/yolov5

**Comment by rohitrrg** [comment]
Yes, I have the same issue with training the custom model.
few days ago, it was working fine with the same code and configurations.

**Comment by glenn-jocher** [comment]
@Beb007 @rohitrrg good news 😃! Your original issue may now be fixed ✅ in PR #https://github.com/ultralytics/yolov5/pull/7392. This PR dynamically allocates a tuple of normalization layers based on the current torch version, so should be compatible with any torch release past or future.

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
