### ISSUE TITLE
Getting wrong output Dimension

### ISSUE THREAD

**Issue by heigex** [ultralytics/yolov5#7383]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm trying to build an object detection model using the [Hard Hat dataset](https://public.roboflow.com/object-detection/hard-hat-workers). It has three classes:
- head 
- helmet
- person

I have used YOLOv5 as the base model. After training. I'm converting this model to `tflite`. I'm getting `[1, 25200, 85]` as the output dimension, but I'm expecting `[1, 25200, 8 (x, y, w, h, conf + 3 classes)]`. 

You can look for the output dimension by uploading the `yolov5s-fp16.tflite` model to [netron.app](netron.app)

### Additional

Link to Colab Notebook: https://colab.research.google.com/drive/1N-NwgmsBTuKQiApXQ2_dk4Cd3CUr8Nrt?usp=sharing

**Comment by glenn-jocher** [comment]
@Mohit0928 you need to point export.py to your trained weights, i.e.
```
python export.py --weights path/to/best.pt
```

**Comment by heigex** [comment]
Yeah, I had figured it out. :) Thank you so much for your reply. I am closing the issue.
