### ISSUE TITLE
Bounding box color

### ISSUE THREAD

**Issue by Akotkar23** [ultralytics/yolov5#7386]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to change bounding box color when uploading model using torch.hub.load. Can we do some changes in render() to modify the color for different class. @glenn-jocher is it possible to do such changes.

**Comment by glenn-jocher** [comment]
@Akotkar23 you can modify the default Ultralytics color palette here:
https://github.com/ultralytics/yolov5/blob/4bb7eb8b849fc8a90823a60e2b7a8ec9e38926bf/utils/plots.py#L31-L47

**Comment by Akotkar23** [comment]
> values

Actually I am loading the model using torch.hub.load
Sample code:
import torch
model = torch.hub.load('ultralytics/yolov5', 'custom', path='best.pt')  
img = 'C:/Users/admin/Images/1.jpg' 
results = model(img)
results.render()

Can I do the changes here ?
