### ISSUE TITLE
Add --view-img and not add, the speed is very different.

### ISSUE THREAD

**Issue by liang-jingyi** [ultralytics/yolov5#7388]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Run python detect. py
Add --view-img and not add, the speed is very different.
I suspect cv2_imshow() is causing the slowdown
How to solve this problem?

**Comment by glenn-jocher** [comment]
If you don't like the effect of adding an argument, don't add it.
