### ISSUE TITLE
tensorrtx yolov5 v1.0 v2.0 v3.0

### ISSUE THREAD

**Issue by wang-xinyu** [ultralytics/yolov5#739]
Hi @glenn-jocher,

Just to let you know, we have updated our implementation to your v3.0 release.

Now we support your yolov5 v1.0(yolov5s only) v2.0 and v3.0. Refer to https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5

And the speed of v3.0 is nearly the same as v2.0.

**Comment by glenn-jocher** [comment]
@wang-xinyu oh, that's great, I'm glad to hear that! I haven't tested speed effects on the nn.Hardswish() activations other than in PyTorch, and I have not checked out export results either other than to see that export CI tests are passing.

We're trying to strike the right compromise between mAP improvements and speed improvements. It's a tricky balancing act.

**Comment by wang-xinyu** [comment]
@glenn-jocher I think hard swish is good, as least it should be faster than mish in yolov4.~~
