### ISSUE TITLE
unusefull code in function non_max_suppression at general.py

### ISSUE THREAD

**Issue by hoangkhoiLE** [ultralytics/yolov5#7391]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Hello, 

I found that in function non_max_suppression, we have argument "multi_label" would not be used by end user (image example in detect.py https://github.com/ultralytics/yolov5/blob/master/detect.py)
![image](https://user-images.githubusercontent.com/57557628/162910265-1da60e16-391c-4557-9c03-3ba84eac6b8b.png)

So by default, the "multi_label &= nc > 1 " would always return False, so the part "if multi_label:" would not be used in all cases.
![image](https://user-images.githubusercontent.com/57557628/162910608-b43d5f5a-7b00-4d3b-b205-3d42d8ef5c9f.png)

I wonder if we need to keep the multi_label argument ? If yes, what is the case ?
I would be glad to hear from you! 

Best regard

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@hoangkhoiLE

https://github.com/ultralytics/yolov5/blob/4bb7eb8b849fc8a90823a60e2b7a8ec9e38926bf/val.py#L213-L219

**Comment by hoangkhoiLE** [comment]
@glenn-jocher  Can you explain to me why in inference (detect.py) we don't use multi-label but in validation (val.py) ? Thanks in advance !

**Comment by glenn-jocher** [comment]
@hoangkhoiLE you're free to add it to detect.py
