### ISSUE TITLE
Error when resuming a training

### ISSUE THREAD

**Issue by Pharaun85** [ultralytics/yolov5#7394]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

Due to GPU time restrictions, I train until it cuts off and then relaunch the training with the --resume option. 
Until yesterday it worked perfectly, but today I get this error whatever the checkpoint with which I relaunch the training. I have tried with some old ones that I know worked, and the error is the same. Has anything changed in the optimizer structure?

### Environment

Using torch 1.10.0+cu111 (Tesla K80)

Google Colab

### Minimal Reproducible Example

!python train.py --img 1280 --batch 16 --epochs 50 --data /content/drive/MyDrive/OIv6/dataset.yaml --project /content/drive/MyDrive/OIv6/runs/train  --weights yolov5s6.pt --hyp hyp.VOC.yaml --optimizer AdamW --device 0

!python train.py --resume /content/drive/MyDrive/OIv6/runs/train/exp/weights/last.pt --device 0

Traceback (most recent call last):
  File "train.py", line 667, in <module>
    main(opt)
  File "train.py", line 562, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 191, in train
    optimizer.load_state_dict(ckpt['optimizer'])
  File "/usr/local/lib/python3.7/dist-packages/torch/optim/optimizer.py", line 146, in load_state_dict
    raise ValueError("loaded state dict contains a parameter group "
ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Pharaun85 👋 Hello! Thanks for asking about **resuming training**. YOLOv5 🚀 Learning Rate (LR) [schedulers](https://github.com/ultralytics/yolov5/blob/aa542ce6a65658ff931fee9bbab77c0145c152f0/train.py#L175-L181) follow predefined LR curves for the fixed number of `--epochs` defined at training start (`default=300`), and are designed to fall to a minimum LR on the final epoch for best training results. For this reason you can not modify the number of epochs once training has started.

<img width="850" alt="Screenshot 2022-04-10 at 11 11 51" src="https://user-images.githubusercontent.com/26833433/162611202-4e0b611f-6cca-4e43-94fc-bbc44e6447f8.png">

If your training was **interrupted** for any reason you may continue where you left off using the `--resume` argument. If your training fully completed, you can start a **new** training from any model using the `--weights` argument. Examples:

## Resume Single-GPU

You may not change settings when resuming, and **no additional arguments** other than `--resume` should be passed, with an optional path to the checkpoint you'd like to resume from. If no checkpoint is passed the most recently updated `last.pt` in your `yolov5/` directory is automatically found and used:
```bash
python train.py --resume  # automatically find latest checkpoint (searches yolov5/ directory)
python train.py --resume path/to/last.pt  # specify resume checkpoint
```

## Resume Multi-GPU

[Multi-GPU DDP trainings](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) must be resumed with the same GPUs and DDP command, i.e. assuming 8 GPUs:
```bash
python -m torch.distributed.run --nproc_per_node 8 train.py --resume  # resume latest checkpoint
python -m torch.distributed.run --nproc_per_node 8 train.py --resume path/to/last.pt  # specify resume checkpoint
```

## Start from Pretrained

If you would like to **start training** from a fully trained model, use the `--weights` argument, not the `--resume` argument:
```bash
python train.py --weights path/to/best.pt  # start from pretrained model
```

Good luck 🍀 and let us know if you have any other questions!

**Comment by Pharaun85** [comment]
Thanks for your response @glenn-jocher . For resuming the training im using the code you posted:

```
python train.py --resume  # automatically find latest checkpoint (searches yolov5/ directory)
python train.py --resume path/to/last.pt  # specify resume checkpoint
```

The thing is that yesterday worked, and today raises this error:

```
Traceback (most recent call last):
  File "train.py", line 667, in <module>
    main(opt)
  File "train.py", line 562, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 191, in train
    optimizer.load_state_dict(ckpt['optimizer'])
  File "/usr/local/lib/python3.7/dist-packages/torch/optim/optimizer.py", line 146, in load_state_dict
    raise ValueError("loaded state dict contains a parameter group "
ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group
```

Is there any changes in the resume options to load the optimizer?

**Comment by glenn-jocher** [comment]
@Pharaun85 compatibility for resuming runs is not guaranteed across commits. If you are resuming a run you should always try to do it with the same commit that you started training with. In your case it looks like this PR is the root cause: https://github.com/ultralytics/yolov5/pull/7376

**Comment by Pharaun85** [comment]
Thank you very much for your reply!
The truth is that yes, that seems to have been the problem. 
I'll have to get a real graphics card XD
