### ISSUE TITLE
How to sort detected object with priority 

### ISSUE THREAD

**Issue by Chuttyboy** [ultralytics/yolov5#7395]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Detecting object using `detect.py` and its working fine. After that i decide to save results in seperate text file so altered few line in detect.py

```
        # Print time (inference-only)
       
        with open("output.txt", "a") as f:
            now = datetime.datetime.now().strftime("%a, %d %B %I:%M:%S")
            print(f'{s}Done. date ({t3 - t2:.3f}s)', now ,file=f)
       
       # LOGGER.info(f'{s}Done. ({t3 - t2:.3f}s)') #0: 480x640 Done. (0.532s) output of this line 

```

After this modification results are saved in `output.txt file`. result are in output.txt file in this format

```
0: 480x640 2 persons, 1 tv, 1 laptop, 1 clock, 1: 480x640 5 persons, 1 bottle, 3 chairs, 2 tvs, 1 cell phone, 1 oven, Done. (0.759s) Mon, 04 April 11:39:48
0: 480x640 2 persons, 1 tv, 1 laptop, 2 clocks, 1: 480x640 4 persons, 1 car, 3 chairs, 2 tvs, 1 laptop, 1 oven, Done. (0.763s) Mon, 04 April 11:39:50
```

With this data i want to give priority to detected object like` High , Medium , Low` . If `person` and `tv` detected give status `High` to that , if `person` and `laptop` detected give `medium` status , How can i do the same way to give priority to detected object.

Thanks in advance

**Comment by glenn-jocher** [comment]
@Chuttyboy 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. This should give you the most flexibility to sort the result Tensor or Pandas dataframe however you want.

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, etc.
# model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')  # custom trained model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by Chuttyboy** [comment]
@glenn-jocher The above reference didn't resolve my query . can you please say some another way to resolve my issue with yolov5 resuts???
