### ISSUE TITLE
For classes 50+ with val.py, not getting individual metrics (mAP, P, R)

### ISSUE THREAD

**Issue by sarmientoj24** [ultralytics/yolov5#7396]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Using `val.py` only gives results for ALL classes and not individual.

**Comment by sarmientoj24** [comment]
Okay. Seems like I need to add `--verbose`

**Comment by sarmientoj24** [comment]
My bad. It doesn't show all of the classes. Or does it only show those which appear in the validation set?

**Comment by glenn-jocher** [comment]
@sarmientoj24 only classes that appear in your validation set are displayed. All others would be NaN for lack of statistics.
