### ISSUE TITLE
How to change the number of classes?

### ISSUE THREAD

**Issue by JunFang-NWPU** [ultralytics/yolov5#74]
I want to train my own data which has 10 classes, I have modify the data/*.yaml file, how to change the  yolov5s network since currently nc=80 classes.

Thanks.

**Comment by glenn-jocher** [comment]
See https://docs.ultralytics.com/yolov5/tutorials/train_custom_data

**Comment by Jacobsolawetz** [comment]
In sum, you need to replace nc=80 with the nc=10 at the top of your chosen model's .yaml file.

**Comment by glenn-jocher** [comment]
@Jacobsolawetz @JunFang-NWPU yes this should work, but make sure that your dataset and model both have the same number of classes:

Dataset:
https://github.com/ultralytics/yolov5/blob/ad71d2d513dd1cce71b87b72af6c2685709549ad/data/coco128.yaml#L14-L15

Model:
https://github.com/ultralytics/yolov5/blob/ad71d2d513dd1cce71b87b72af6c2685709549ad/models/yolov5s.yaml#L1-L2

**Comment by vnt1537** [comment]
> See https://docs.ultralytics.com/yolov5/tutorials/train_custom_data

Hello, if I want to train the model on only one class (person) from the coco dataset so how can I do that?

**Comment by glenn-jocher** [comment]
@vnt1537 copy coco, remove labels you don't want, train.

**Comment by vnt1537** [comment]
Thanks a lot for quick reply :) 
I tried that and even changed the nc in both coco and yolo5s yaml files.
![Screenshot from 2020-06-17 15-48-37](https://user-images.githubusercontent.com/44675070/84906642-81688780-b0b2-11ea-986b-1a2d3fdb7943.png)

![Screenshot from 2020-06-17 15-50-27](https://user-images.githubusercontent.com/44675070/84906697-91806700-b0b2-11ea-9e47-bb7384adff13.png)


And I train by the command : 
python train.py --batch 16 --epochs 50 --data ./data/coco.yaml --cfg ./models/yolov5s.yaml

I also had a doubt that unlike yolov3 we dont have to give some pre trained weights here?

**Comment by glenn-jocher** [comment]
@vnt1537 the error message is self explanatory and very clear.

Your labels show class numbers up to 79, but you've passed nc=1 in your model or your data.yaml. It explains this right in the error message.

**Comment by glenn-jocher** [comment]
@vnt1537 what do you expect the training to do with the extra 79 classes that you've supplied it?

**Comment by vnt1537** [comment]
The thing is I download coco with get_coco2017.sh provided by you. How can I download a single class data (label and image) from coco dataset?

**Comment by vnt1537** [comment]
> @vnt1537 what do you expect the training to do with the extra 79 classes that you've supplied it?

I want to detect human in a frame and get the bounding box as cropped image which I can feed to my another model. Can I use any of your pre trained to do so? If not then I would like to train it but the wiki page (https://docs.ultralytics.com/yolov5/tutorials/train_custom_data) does not tell how can I download the subset dataset of coco to do so. Can you please help me with this!! Thanking you again.

**Comment by glenn-jocher** [comment]
@vnt1537 coco is coco, there is no 'subset dataset' as you describe.

To detect humans just use the pretrained checkpoints. https://github.com/ultralytics/yolov5#inference

**Comment by vnt1537** [comment]
@glenn-jocher But I want to detect only humans and no other classes and also want to extract the Co ordinates of the bounding box. How can I do so?

**Comment by glenn-jocher** [comment]
@vnt1537 before raising issues you should try looking at the actual file, all of your questions are answerd in the argparser comments.
https://github.com/ultralytics/yolov5/blob/fc171e2678ce303527eb2cffa000f6cd72ce5319/detect.py#L138-L158

**Comment by vnt1537** [comment]
@glenn-jocher I am sorry but I'm new to this but my main concern is detecting only humans and not the other classes with your pre trained model.

**Comment by glenn-jocher** [comment]
@vnt1537 to filter inference by class `python detect.py --classes 0`, for multiple classes `python detect.py --classes 0,5,10`

**Comment by dkl78167816** [comment]
> @vnt1537 to filter inference by class `python detect.py --classes 0`, for multiple classes `python detect.py --classes 0,5,10`

Great of patience, thank you!

**Comment by Ashish110110** [comment]
> @vnt1537 to filter inference by class `python detect.py --classes 0`, for multiple classes `python detect.py --classes 0,5,10`

Hi, I am working on similar problem, where I need to detect only cats and no other class in images. The problem is, the class label of output .txt file is displayed as 15(since index of cats is 15 out of the 80 classes). I want the class label to be displayed as 0 instead of 15. Is it possible? If yes, then what changes do I need to make? I made changes in coco.yaml, coco128.yaml, yolov5s.yaml by changing nc and removing other classes but still the same output. I am running inference directly, am not training it.
![Capture](https://user-images.githubusercontent.com/37297441/126301919-01128716-2a95-4497-8ff1-6478c6d0d1fb.PNG)

**Comment by vnt1537** [comment]
If you are only detecting cats and want to hard code the output.txt file to write the class label as 0, you can change the line no.  142 of file detect.py

from --> line = (cls, *xywh, conf) if save_conf else (cls, *xywh)  # label format  (original code)

to --> line = (0, *xywh, conf) if save_conf else (cls, *xywh)  # label format (edited code)

##Note##
This would always output class label as 0, so please take care when using this code for multiple classes!

> > @vnt1537 to filter inference by class `python detect.py --classes 0`, for multiple classes `python detect.py --classes 0,5,10`
> 
> Hi, I am working on similar problem, where I need to detect only cats and no other class in images. The problem is, the class label of output .txt file is displayed as 15(since index of cats is 15 out of the 80 classes). I want the class label to be displayed as 0 instead of 15. Is it possible? If yes, then what changes do I need to make? I made changes in coco.yaml, coco128.yaml, yolov5s.yaml by changing nc and removing other classes but still the same output. I am running inference directly, am not training it.
> ![Capture](https://user-images.githubusercontent.com/37297441/126301919-01128716-2a95-4497-8ff1-6478c6d0d1fb.PNG)

**Comment by Ashish110110** [comment]
@vnt1537 Thank you for your response! Much appreciated! However, I did exactly as you said, but it didn't work :( I even reloaded colab multiple times to make sure changes are updated but the output was still the same. Is there any other way to do it?  


> If you are only detecting cats and want to hard code the output.txt file to write the class label as 0, you can change the line no. 142 of file detect.py
> 
> from --> line = (cls, *xywh, conf) if save_conf else (cls, *xywh) # label format (original code)
> 
> to --> line = (0, *xywh, conf) if save_conf else (cls, *xywh) # label format (edited code)
> 
> ##Note##
> This would always output class label as 0, so please take care when using this code for multiple classes!
> 
> > > @vnt1537 to filter inference by class `python detect.py --classes 0`, for multiple classes `python detect.py --classes 0,5,10`
> > 
> > 
> > Hi, I am working on similar problem, where I need to detect only cats and no other class in images. The problem is, the class label of output .txt file is displayed as 15(since index of cats is 15 out of the 80 classes). I want the class label to be displayed as 0 instead of 15. Is it possible? If yes, then what changes do I need to make? I made changes in coco.yaml, coco128.yaml, yolov5s.yaml by changing nc and removing other classes but still the same output. I am running inference directly, am not training it.
> > ![Capture](https://user-images.githubusercontent.com/37297441/126301919-01128716-2a95-4497-8ff1-6478c6d0d1fb.PNG)

**Comment by vnt1537** [comment]
> @vnt1537 Thank you for your response! Much appreciated! However, I did exactly as you said, but it didn't work :( I even reloaded colab multiple times to make sure changes are updated but the output was still the same. Is there any other way to do it?
> 
> > If you are only detecting cats and want to hard code the output.txt file to write the class label as 0, you can change the line no. 142 of file detect.py
> > from --> line = (cls, *xywh, conf) if save_conf else (cls, *xywh) # label format (original code)
> > to --> line = (0, *xywh, conf) if save_conf else (cls, *xywh) # label format (edited code)
> > ##Note##
> > This would always output class label as 0, so please take care when using this code for multiple classes!
> > > > @vnt1537 to filter inference by class `python detect.py --classes 0`, for multiple classes `python detect.py --classes 0,5,10`
> > > 
> > > 
> > > Hi, I am working on similar problem, where I need to detect only cats and no other class in images. The problem is, the class label of output .txt file is displayed as 15(since index of cats is 15 out of the 80 classes). I want the class label to be displayed as 0 instead of 15. Is it possible? If yes, then what changes do I need to make? I made changes in coco.yaml, coco128.yaml, yolov5s.yaml by changing nc and removing other classes but still the same output. I am running inference directly, am not training it.
> > > ![Capture](https://user-images.githubusercontent.com/37297441/126301919-01128716-2a95-4497-8ff1-6478c6d0d1fb.PNG)

Could share the screenshot of that part you changed?

**Comment by Ashish110110** [comment]
> > @vnt1537 Thank you for your response! Much appreciated! However, I did exactly as you said, but it didn't work :( I even reloaded colab multiple times to make sure changes are updated but the output was still the same. Is there any other way to do it?
> > > If you are only detecting cats and want to hard code the output.txt file to write the class label as 0, you can change the line no. 142 of file detect.py
> > > from --> line = (cls, *xywh, conf) if save_conf else (cls, *xywh) # label format (original code)
> > > to --> line = (0, *xywh, conf) if save_conf else (cls, *xywh) # label format (edited code)
> > > ##Note##
> > > This would always output class label as 0, so please take care when using this code for multiple classes!
> > > > > @vnt1537 to filter inference by class `python detect.py --classes 0`, for multiple classes `python detect.py --classes 0,5,10`
> > > > 
> > > > 
> > > > Hi, I am working on similar problem, where I need to detect only cats and no other class in images. The problem is, the class label of output .txt file is displayed as 15(since index of cats is 15 out of the 80 classes). I want the class label to be displayed as 0 instead of 15. Is it possible? If yes, then what changes do I need to make? I made changes in coco.yaml, coco128.yaml, yolov5s.yaml by changing nc and removing other classes but still the same output. I am running inference directly, am not training it.
> > > > ![Capture](https://user-images.githubusercontent.com/37297441/126301919-01128716-2a95-4497-8ff1-6478c6d0d1fb.PNG)
> 
> Could share the screenshot of that part you changed?

Sure, here : 
![detect](https://user-images.githubusercontent.com/37297441/126587861-3a720b17-0bbd-4247-bff3-1d23aa8dc3bd.PNG)

And the output : 
![1549](https://user-images.githubusercontent.com/37297441/126587891-f2fddb40-096d-41a3-93ff-1f96ca58786a.PNG)

**Comment by vnt1537** [comment]
> > > @vnt1537 Thank you for your response! Much appreciated! However, I did exactly as you said, but it didn't work :( I even reloaded colab multiple times to make sure changes are updated but the output was still the same. Is there any other way to do it?
> > > > If you are only detecting cats and want to hard code the output.txt file to write the class label as 0, you can change the line no. 142 of file detect.py
> > > > from --> line = (cls, *xywh, conf) if save_conf else (cls, *xywh) # label format (original code)
> > > > to --> line = (0, *xywh, conf) if save_conf else (cls, *xywh) # label format (edited code)
> > > > ##Note##
> > > > This would always output class label as 0, so please take care when using this code for multiple classes!
> > > > > > @vnt1537 to filter inference by class `python detect.py --classes 0`, for multiple classes `python detect.py --classes 0,5,10`
> > > > > 
> > > > > 
> > > > > Hi, I am working on similar problem, where I need to detect only cats and no other class in images. The problem is, the class label of output .txt file is displayed as 15(since index of cats is 15 out of the 80 classes). I want the class label to be displayed as 0 instead of 15. Is it possible? If yes, then what changes do I need to make? I made changes in coco.yaml, coco128.yaml, yolov5s.yaml by changing nc and removing other classes but still the same output. I am running inference directly, am not training it.
> > > > > ![Capture](https://user-images.githubusercontent.com/37297441/126301919-01128716-2a95-4497-8ff1-6478c6d0d1fb.PNG)
> > 
> > 
> > Could share the screenshot of that part you changed?
> 
> Sure, here :
> ![detect](https://user-images.githubusercontent.com/37297441/126587861-3a720b17-0bbd-4247-bff3-1d23aa8dc3bd.PNG)
> 
> And the output :
> ![1549](https://user-images.githubusercontent.com/37297441/126587891-f2fddb40-096d-41a3-93ff-1f96ca58786a.PNG)

Change the line to

line = (0, *xywh, conf) if save_conf else (0, *xywh) # label format (edited code)

**Comment by Ashish110110** [comment]
> > > > @vnt1537 Thank you for your response! Much appreciated! However, I did exactly as you said, but it didn't work :( I even reloaded colab multiple times to make sure changes are updated but the output was still the same. Is there any other way to do it?
> > > > > If you are only detecting cats and want to hard code the output.txt file to write the class label as 0, you can change the line no. 142 of file detect.py
> > > > > from --> line = (cls, *xywh, conf) if save_conf else (cls, *xywh) # label format (original code)
> > > > > to --> line = (0, *xywh, conf) if save_conf else (cls, *xywh) # label format (edited code)
> > > > > ##Note##
> > > > > This would always output class label as 0, so please take care when using this code for multiple classes!
> > > > > > > @vnt1537 to filter inference by class `python detect.py --classes 0`, for multiple classes `python detect.py --classes 0,5,10`
> > > > > > 
> > > > > > 
> > > > > > Hi, I am working on similar problem, where I need to detect only cats and no other class in images. The problem is, the class label of output .txt file is displayed as 15(since index of cats is 15 out of the 80 classes). I want the class label to be displayed as 0 instead of 15. Is it possible? If yes, then what changes do I need to make? I made changes in coco.yaml, coco128.yaml, yolov5s.yaml by changing nc and removing other classes but still the same output. I am running inference directly, am not training it.
> > > > > > ![Capture](https://user-images.githubusercontent.com/37297441/126301919-01128716-2a95-4497-8ff1-6478c6d0d1fb.PNG)
> > > 
> > > 
> > > Could share the screenshot of that part you changed?
> > 
> > 
> > Sure, here :
> > ![detect](https://user-images.githubusercontent.com/37297441/126587861-3a720b17-0bbd-4247-bff3-1d23aa8dc3bd.PNG)
> > And the output :
> > ![1549](https://user-images.githubusercontent.com/37297441/126587891-f2fddb40-096d-41a3-93ff-1f96ca58786a.PNG)
> 
> Change the line to
> 
> line = (0, *xywh, conf) if save_conf else (0, *xywh) # label format (edited code)

WOAH it worked!! Thank you so much man! Much appreciated! Will have to be careful with multiple classes though. Thank you once again!! :D

**Comment by Symbadian** [comment]
> > > > @vnt1537 Thank you for your response! Much appreciated! However, I did exactly as you said, but it didn't work :( I even reloaded colab multiple times to make sure changes are updated but the output was still the same. Is there any other way to do it?
> > > > > If you are only detecting cats and want to hard code the output.txt file to write the class label as 0, you can change the line no. 142 of file detect.py
> > > > > from --> line = (cls, *xywh, conf) if save_conf else (cls, *xywh) # label format (original code)
> > > > > to --> line = (0, *xywh, conf) if save_conf else (cls, *xywh) # label format (edited code)
> > > > > ##Note##
> > > > > This would always output class label as 0, so please take care when using this code for multiple classes!
> > > > > > > @vnt1537 to filter inference by class `python detect.py --classes 0`, for multiple classes `python detect.py --classes 0,5,10`
> > > > > > 
> > > > > > 
> > > > > > Hi, I am working on similar problem, where I need to detect only cats and no other class in images. The problem is, the class label of output .txt file is displayed as 15(since index of cats is 15 out of the 80 classes). I want the class label to be displayed as 0 instead of 15. Is it possible? If yes, then what changes do I need to make? I made changes in coco.yaml, coco128.yaml, yolov5s.yaml by changing nc and removing other classes but still the same output. I am running inference directly, am not training it.
> > > > > > ![Capture](https://user-images.githubusercontent.com/37297441/126301919-01128716-2a95-4497-8ff1-6478c6d0d1fb.PNG)
> > > 
> > > 
> > > Could share the screenshot of that part you changed?
> > 
> > 
> > Sure, here :
> > ![detect](https://user-images.githubusercontent.com/37297441/126587861-3a720b17-0bbd-4247-bff3-1d23aa8dc3bd.PNG)
> > And the output :
> > ![1549](https://user-images.githubusercontent.com/37297441/126587891-f2fddb40-096d-41a3-93ff-1f96ca58786a.PNG)
> 
> Change the line to
> 
> line = (0, *xywh, conf) if save_conf else (0, *xywh) # label format (edited code)

Hi @vnt1537 I am Sym, working on the same issue BUT my challenge is that I have multiple classes. Do you have a solution to alter multi classes on a file?

I am using coco128 and my classes should continue from 80 and there are multiple label.txt files per image.
I tried this manually but that was insane and futile. Can you guide me here, please?

I got the understanding of the altering one class per the index of the lable.txt file but in my case there are many classes that I would like to apply and the solution thus far is not helping.

THIS IS MY CODE FOR MY SOLUTION: (but this generates another file cpython-39.pyc without the indices in front of the yolov5 cordinates)

`import os, fnmatch

def findReplace(directory, find, replace, filePattern):
    for path, dirs, files in os.walk(os.path.abspath(directory)):
        for filename in fnmatch.filter(files, filePattern):
            filepath = os.path.join(path, filename)
            with open(filepath) as f:
                s = f.read()
                print('This is with open s',s)
            s = s.replace(find, replace)
            print('This is replacing the data in s',s)
            with open(filepath, "w") as f:
                f.write(s)
                save(f)

#findReplace('<path to label>','<Find this>','<Replace This>',"*.txt")
print(findReplace('</Users/symbadian/Desktop/LIRIS_new_dataset/ADNew/AllData_Index_Changed/Beating/train/labels>','<2 0.5877403846153846 0.53125 0.11177884615384616 0.3641826923076923>','<0 0.5877403846153846 0.53125 0.11177884615384616 0.3641826923076923>',"*.txt"))
findReplace('</Users/symbadian/Desktop/LIRIS_new_dataset/ADNew/AllData_Index_Changed/Beating/train/labels>','<2 0.4387019230769231 0.6538461538461539 0.125 0.49038461538461536>','<0 0.4387019230769231 0.6538461538461539 0.125 0.49038461538461536>',"*.txt")
findReplace('</Users/symbadian/Desktop/LIRIS_new_dataset/ADNew/AllData_Index_Changed/Beating/train/labels>','<1 0.5336538461538461 0.5853365384615384 0.08774038461538461 0.1814903846153846>','<81 0.5336538461538461 0.5853365384615384 0.08774038461538461 0.1814903846153846>',"*.txt")
findReplace('</Users/symbadian/Desktop/LIRIS_new_dataset/ADNew/AllData_Index_Changed/Beating/train/labels>','<0 0.5276442307692307 0.6225961538461539 0.32091346153846156 0.5661057692307693>','<80 0.5276442307692307 0.6225961538461539 0.32091346153846156 0.5661057692307693>',"*.txt")
findReplace('/Users/symbadian/Desktop/LIRIS_new_dataset/ADNew/AllData_Index_Changed/Beating/valid/labels','<1 0.4483173076923077 0.4411057692307692 0.07451923076923077 0.06971153846153846>','<81 0.4483173076923077 0.4411057692307692 0.07451923076923077 0.06971153846153846>',"*.txt")
findReplace('/Users/symbadian/Desktop/LIRIS_new_dataset/ADNew/AllData_Index_Changed/Beating/valid/labels','<2 0.5420673076923077 0.578125 0.13942307692307693 0.33413461538461536>','<0 0.5420673076923077 0.578125 0.13942307692307693 0.33413461538461536>',"*.txt")
findReplace('/Users/symbadian/Desktop/LIRIS_new_dataset/ADNew/AllData_Index_Changed/Beating/valid/labels','<0 0.4987980769230769 0.5961538461538461 0.20072115384615385 0.39783653846153844>','<81 0.4987980769230769 0.5961538461538461 0.20072115384615385 0.39783653846153844>',"*.txt")
findReplace('/Users/symbadian/Desktop/LIRIS_new_dataset/ADNew/AllData_Index_Changed/Beating/valid/labels','<2 0.4963942307692308 0.6057692307692307 0.17307692307692307 0.35096153846153844>','<0 0.4963942307692308 0.6057692307692307 0.17307692307692307 0.35096153846153844>',"*.txt")`


![](https://user-images.githubusercontent.com/50293021/174812414-0217bf50-3024-4d7c-a485-9a59683a1ead.png)

**Comment by Symbadian** [comment]
> yolov5/models/yolov5s.yaml

Hi @glenn-jocher,
is it possible to train using multiple custom yaml files simultaneously instead of modifying one?
for example:
A.yaml
B.yaml
C.yaml

rather than modifying just one for example modifying coco128.yaml to reflect all three files?

**Comment by vnt1537** [comment]
@Symbadian What is your task? And why would you want to continue your Index from 80?
How many classes do you have?

And I do not think you can train using multiple yaml files!

**Comment by Symbadian** [comment]
> @Symbadian What is your task? And why would you want to continue your Index from 80? How many classes do you have?
> 
> And I do not think you can train using multiple yaml files!

This is so confusing but I am determined to learn.

I wanted to train using all of the classes via coco128, but then I realized that I could use just my classes but I am still faced with the same challenge. How do I convert the index location configurations of all of the files in the label.txt format?

The Operations:
1. I have 55 folders of varying classes
2. Each folder was created using roboflow https://app.roboflow.com/
3. Each folder generated its own yaml file = data.yaml (Which I now have 55 yaml files that display the class amount and labels names)
4. Each folder's label.txt files have at least 4 classes per image (seen in the image above)
5. The labels indices for each folder per file start from 0 to 3

What I am trying to do(outstanding and in progress):
7. Either find a solution to convert all of the label indices as per their location starting after 'Hand' or find a way to call all of the 55 data.yaml files separately (now that you mentioned that this is not possible then I'm back to latter)
(for this current example I am using this which works but the classes are in the wrong location-see image) 

I am trying to add the 'BEATING' folder but this needs an index conversion: 
(This is not in the script below as I haven't converted the data index yet-see image)

`path: ../datasets/coco128  # dataset root dir
train:  
   - images/train/Knife_Deploy
 
val: 
   - images/val/Knife_Deploy
 

test:  # test images (optional)

# Classes
nc: 3  # number of classes
names: ['Knife_Deploy', 'Knife_Weapon', 'Hand']`

*************************************************************************************
BUT:
how do I get the other label.txt files to correspond to the continuation of the sequencing of this format?
for example:
In folder Knife_Deploy: 
I have 3 class names: ['Knife_Deploy', 'Knife_Weapon', 'Hand']

NOW: I WOULD LIKE TO ADD folder 2 which begins **AT INDEX 4**

CURRENT TASK:
HOW do I convert the rest of the folders and their relevant label indices to correspond to this index position starting a position 04:
![Screenshot 2022-06-22 at 12 21 21](https://user-images.githubusercontent.com/50293021/175017749-c463218b-09bf-4dd8-a538-29082058383e.png)

**Comment by vnt1537** [comment]
Do you want the 80 classes of COCO or just want to train an object detection model to detect this 3 classes of 'Knife_Deploy', 'Knife_WEapon' and 'Hand'?

ANd I never have used Roboflow, but you should have only one folder with all images and not 55. What you must have done is used Roboflow 55 times. 

Also the starting position should always be from 0 for training a custom model.

And I think while labelling data you should use add all the images at once and then label all the images for all different class such that you generate only one xaml file

**Comment by Symbadian** [comment]
> Do you want the 80 classes of COCO or just want to train an object detection model to detect this 3 classes of 'Knife_Deploy', 'Knife_WEapon' and 'Hand'?
> 
> ANd I never have used Roboflow, but you should have only one folder with all images and not 55. What you must have done is used Roboflow 55 times.
> 
> Also the starting position should always be from 0 for training a custom model.
> 
> And I think while labelling data you should use add all the images at once and then label all the images for all different class such that you generate only one xaml file

I see.... 

No I don't want it after realizing that I can get my classes to work on it's own.
What I would like is some guidance on how to convert the labels as per my demonstrations above..

I would have one folder of images:
How would I differentiate what the different classes are in the folders? 
For example, the code below shows multiple datasets 
Please, may I see a demonstration of an example of how you placed all of your images of various classes in one folder for annotations?
Maybe I missed a step here... and thanx in advance for your guidance...

`# YOLOv5 🚀 by Ultralytics, GPL-3.0 license
# Global Wheat 2020 dataset http://www.global-wheat.com/ by University of Saskatchewan
# Example usage: python train.py --data GlobalWheat2020.yaml
# parent
# ├── yolov5
# └── datasets
#     └── GlobalWheat2020  ← downloads here (7.0 GB)


# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: ../datasets/GlobalWheat2020  # dataset root dir
train: # train images (relative to 'path') 3422 images
  - images/arvalis_1
  - images/arvalis_2
  - images/arvalis_3
  - images/ethz_1
  - images/rres_1
  - images/inrae_1
  - images/usask_1
val: # val images (relative to 'path') 748 images (WARNING: train set contains ethz_1)
  - images/ethz_1
test: # test images (optional) 1276 images
  - images/utokyo_1
  - images/utokyo_2
  - images/nau_1
  - images/uq_1

# Classes
nc: 1  # number of classes
names: ['wheat_head']  # class names`

**Comment by Symbadian** [comment]
@vnt1537 got it to work, used the merged feature from roboflow, then regenerated the datasets and that created the solution for the label.txt challenges. Thanx for your guidance, your efforts were appreciated highly!

**Comment by jehan88** [comment]
> @Jacobsolawetz @JunFang-NWPU yes this should work, but make sure that your dataset and model both have the same number of classes:
> 
> Dataset:
> 
> https://github.com/ultralytics/yolov5/blob/ad71d2d513dd1cce71b87b72af6c2685709549ad/data/coco128.yaml#L14-L15
> 
> Model:
> 
> https://github.com/ultralytics/yolov5/blob/ad71d2d513dd1cce71b87b72af6c2685709549ad/models/yolov5s.yaml#L1-L2

this is work with methane you so much
