### ISSUE TITLE
clsiou

### ISSUE THREAD

**Issue by buxihuo** [ultralytics/yolov5#7400]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I found that you are doing relevant experiments on clsiou. I have also done relevant experiments on yolov5 before. It has a higher map on the S model, but it will lead to the decrease of ap50 on the X model. This phenomenon also exists on the VOC dataset. I found that you have solved this problem and look forward to the release of v7. Yolov5 is my favorite project on GitHub.

**Comment by glenn-jocher** [comment]
@buxihuo hi there! What do you mean by clsiou?

**Comment by buxihuo** [comment]
> @buxihuo hi there! What do you mean by clsiou?

@glenn-jocher I replaced the label of the positive sample from 1 to IOU when calculating the classification loss in yolov5-6.0. The map of the S model exceeds 38. I call it clsiou, but the ap50 of the X model will decrease. Then I found that you have the same name in the V7 experiment.

**Comment by glenn-jocher** [comment]
@buxihuo oh yes that's right! Yes it seems like a simple update that helps small model performance especially :)

**Comment by glenn-jocher** [comment]
That's a funny coincidence!

**Comment by buxihuo** [comment]
@glenn-jocher I'm now doing an experiment to let Yolo detect unknown classes. Its effect is not very good. Surprisingly, it can slightly improve the map, but I'm not sure what the effect will be after using clsiou, so I'm looking forward to the release of V7 and try the experiment of unknown classes based on it.

**Comment by MrinalJain17** [comment]
@buxihuo @glenn-jocher Is this experiment similar to the Varifocal Loss (https://arxiv.org/abs/2008.13367)? The idea is quite interesting where they introduced an IOU-aware classification loss.

**Comment by buxihuo** [comment]
@MrinalJain17 Hello, I've read this paper before, but I only made the simplest changes because my computing resources are limited.

**Comment by glenn-jocher** [comment]
@MrinalJain17 I don't know. They have a few hyperparameters for the loss, but the one I came up with and that @buxihuo apparently also came up with has no hyperparameters, it just involves assigning the iou value to the classification positive target (instead of 1.0 as it is usually). This seems to help smaller models in particular.

**Comment by MrinalJain17** [comment]
Ah, got it. Thanks for the info @glenn-jocher @buxihuo .

Looking forward to the updates!

**Comment by glenn-jocher** [comment]
@MrinalJain17 you're welcome! We're looking forward to it as well 😊
