### ISSUE TITLE
How to extract last layer features and gradients from trained yolov5

### ISSUE THREAD

**Issue by alifarooq93** [ultralytics/yolov5#7405]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I am new with Yolo and try to perform active learning methods on it.
I am having a problem getting image features and gradients from last layer of Yolo. I want a feature/gradient vector for all trained images.
I already looked into feature_visualization funtion() in foward_once() but its not same as the size of input batch. It mostly depend on the image size 8,16,32. 
How can I get those vectors because without that I cant do anything. I really appreciate for your help. Thanks

**Comment by glenn-jocher** [comment]
@alifarooq93 see Detec() layer inputs x:
https://github.com/ultralytics/yolov5/blob/014acde79daee83e1f1801412cc7a48293e6e1f2/models/yolo.py#L54-L57

**Comment by alifarooq93** [comment]
> 

Thank you for your response. I checked that function it has four detection layers and I print the size of x[i] which varried in every iteration. I think its depend on the number on neurons in each layer? Are those image features for each layer? Also this function runs for each epoch hundred times and for each layer. So should I get the features from last layer hundred iteration of last epoch?

**Comment by alifarooq93** [comment]
Hi @glenn-jocher , I tried to save the features from detect forward method but its overflowing my memory because its a lot of features for each iteration and epoch. Is it any way to directly access the image features of last layer for every image in batch after training. I really appreciate if you can guide. Thanks

**Comment by glenn-jocher** [comment]
@alifarooq93 save the model and use inference to forward pass images to obtain features from the last layer. Review our documentation for detailed guidance and examples. You may also consider downsampling or summarizing the features to reduce memory usage. Thank you!
