### ISSUE TITLE
How to load all data into memory during training

### ISSUE THREAD

**Issue by Songpenglei123** [ultralytics/yolov5#7406]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When I'm training, it's slow to load the data every time. Since my training machine has 256g of memory, is it possible to put all the data in memory to speed up the training?

**Comment by glenn-jocher** [comment]
@Songpenglei123 yes:
```
python train.py --cache
```
or if you run out of RAM or are training Multi-GPU you can try
```
python train.py --cache disk
```
