### ISSUE TITLE
ModuleNotFoundError in loading efficientNet model as a 2nd-classifier

### ISSUE THREAD

**Issue by KazuhideMimura** [ultralytics/yolov5#7408]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection, Other

### Bug

I tested training EfficientNet-B0 model as a second-stage classifier using classifier.py.
Although the training went well, module geffnet was required for loading the trained model.
Would you consider adding geffnet to installing modules (requirements.txt).

> ----> model = torch.load('runs/train/exp/weights/best.pt', map_location=torch.device('cpu'))['model'].float()
> ModuleNotFoundError: No module named 'geffnet'

### Minimal Reproducible Example

```
# https://colab.research.google.com/drive/11d8E6Oo_u5gVU6nu8FTPJw-CE3_rwJQl?usp=sharing

# Setup
!git clone https://github.com/ultralytics/yolov5 -b classifier  # clone
%cd yolov5
%pip install -qr requirements.txt

# train
!python classifier.py --model efficientnet_b0 --data mnist --epochs 1 --img 224

# Inference
import torch
from pathlib import Path
from classifier import classify
model = torch.load('runs/train/exp/weights/best.pt', map_location=torch.device('cpu'))['model'].float()
```

### Additional

For local environment and Google Colab, just `pip install geffnet` may solve this problem.
I use YOLOv5 via docker and I don't know how to edit virtual environment.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@KazuhideMimura thanks for the bug report! You should be able to install anything you need in Docker the same as any other environment, i.e. `pip install ...`

**Comment by KazuhideMimura** [comment]
@glenn-jocher In my case, I had some troubles with permissions in installing modules, and solved by mounting local directory of yolov5-related modules (`~anaconda3/envs/yolov5/lib/python3.8/site-packages`) when starting docker.
Thanks for your response anyway!
