### ISSUE TITLE
I suggest we can add accuracy and add the result of wrong prediction in val.py

### ISSUE THREAD

**Issue by WangxuP** [ultralytics/yolov5#7409]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

I suggest we can add accuracy and add the result of wrong prediction in val.py

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@WangxuP hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by WangxuP** [comment]
> 

Sorry, at present, I can only use the project code and cannot accurately modify the project, so I can't put forward the corresponding PR for the time being。
If we can add the calculation of accuracy and the output of prediction error, I think it will be very perfect.

**Comment by glenn-jocher** [comment]
@WangxuP i completely understand. Thank you for sharing your thoughts on enhancing YOLOv5. We greatly appreciate community suggestions like yours that help improve the project. Your input helps us understand how we can better serve our users. We'll definitely keep your idea in mind for future improvements. Thanks again!
