### ISSUE TITLE
How to determine the balance of object loss if I increase a 104*104 prediction scale?

### ISSUE THREAD

**Issue by ImsuperSH** [ultralytics/yolov5#741]
https://github.com/ultralytics/yolov5/blob/5991d144c1439ab360953c59d774d00af51e8de7/utils/general.py#L494

**Comment by glenn-jocher** [comment]
@Sean-pure set it to whatever works best for you. Its intention is to balance losses across outputs.

**Comment by ImsuperSH** [comment]
@glenn-jocher Thank you so much.
