### ISSUE TITLE
Getting Keyerror 'model' while trying to export darknet trained .pt file to .tflite file

### ISSUE THREAD

**Issue by patrickkkim** [ultralytics/yolov5#7411]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I want to convert a custom .pt file into a .tflite file using export.py module.

I've trained some data in darknet Yolov3-tiny and got a .weights file as a result.
I wanted to convert this into a .tflite file, so I converted the .weights file to .pt file using other custom converting module.
Then, I tried to convert that .pt file into a .tflite file and it gave me a Keyerror.

Here's what I typed in the bash:
```bash
py export.py --weights ../yolov3-tiny_last.pt --include pb --img 640
```

And here's what I got as a result:
```bash
export: data=data\coco128.yaml, weights=['../yolov3-tiny_last.pt'], imgsz=[640], batch_size=1, device=cpu, half=False, inplace=False, train=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=12, verbose=False, workspace=4, nms=False, agnostic_nms=False, topk_per_class=100, topk_all=100, iou_thres=0.45, conf_thres=0.25, include=['pb']
YOLOv5  v6.0-217-gd8b5beb torch 1.10.2+cu113 CPU

Traceback (most recent call last):
  File "C:\#yolo\yolov5\export.py", line 517, in <module>
    main(opt)
  File "C:\#yolo\yolov5\export.py", line 512, in main
    run(**vars(opt))
  File "C:\#yolo\env\lib\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "C:\#yolo\yolov5\export.py", line 411, in run
    model = attempt_load(weights, map_location=device, inplace=True, fuse=True)  # load FP32 model
  File "C:\#yolo\yolov5\models\experimental.py", line 98, in attempt_load
    model.append(ckpt['ema' if ckpt.get('ema') else 'model'].float().fuse().eval())  # FP32 model
KeyError: 'model'
```

Thanks.

**Comment by glenn-jocher** [comment]
@patrickkkim darknet is deprecated. Train YOLOv3 pytorch models directly (i.e. see https://github.com/ultralytics/yolov3), and then export to any destination you want in one step:

```
python train.py --weights yolov3-tiny.pt
python export.py --weights path/to/best.pt --include tflite
```
