### ISSUE TITLE
Yolov5 cannot detection a video (tfjs)

### ISSUE THREAD

**Issue by gshoanganh** [ultralytics/yolov5#7416]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

i feel that yolov5 cannot detect a video (or a camera live). 
I tried running my log, but it didn't detect it. but it can detect still image.
```

import React from "react";
import ReactDOM from "react-dom";
import * as tf from '@tensorflow/tfjs';
import { loadGraphModel } from '@tensorflow/tfjs-converter';
import "./style-cam.css";
tf.setBackend('webgl');

const weights = '/web_model/model.json';
const threshold = 0.75;


class App extends React.Component {
  videoRef = React.createRef();
  canvasRef = React.createRef();
  
  load_model = async () => {  
    const model = await loadGraphModel(weights);   
    return model;
  }

  componentDidMount() {
    if (navigator.mediaDevices && navigator.mediaDevices.getUserMedia) {
      const webCamPromise = navigator.mediaDevices
        .getUserMedia({
          audio: false,
          video: {
            facingMode: "user"
          }
        })
        .then(stream => {
          window.stream = stream;
          this.videoRef.current.srcObject = stream;
          return new Promise((resolve, reject) => {
            this.videoRef.current.onloadedmetadata = () => {
              resolve();
            };
          });
        });

        this.beginDetect(webCamPromise)
    }
  }

  beginDetect = async (webCamPromise)=>{
    const modelPromise = await this.load_model();
    console.log('modelPromise: ', modelPromise)

    Promise.all([modelPromise, webCamPromise])
      .then(values => {
        this.detectFrame(this.videoRef.current, values[0]);
      })
      .catch(error => {
        console.error(error);
      });
  }

  detectFrame = (video, model) => {
    tf.engine().startScope();
    model.executeAsync(this.process_input(video)).then(predictions => {
      this.renderPredictions(predictions, video);
      requestAnimationFrame(() => {
        this.detectFrame(video, model);
      });
      tf.engine().endScope();
    });
  };

  process_input(video_frame) {
    const input = tf.tidy(() => {
      return tf.image.resizeBilinear(tf.browser.fromPixels(video_frame), [640, 640])
        .div(255.0).expandDims(0);
    });

    this.preview = input
    console.log('input: ', this.preview)
    this.setState({ loading: false })
    return input
  };

  buildDetectedObjects(scores, threshold, boxes, classes, classesDir) {
    const detectionObjects = []
    var video_frame = document.getElementById('frame');

    scores[0].forEach((score, i) => {
      if (score > threshold) {
        const bbox = [];
        const minY = boxes[0][i][0] * video_frame.offsetHeight;
        const minX = boxes[0][i][1] * video_frame.offsetWidth;
        const maxY = boxes[0][i][2] * video_frame.offsetHeight;
        const maxX = boxes[0][i][3] * video_frame.offsetWidth;
        bbox[0] = minX;
        bbox[1] = minY;
        bbox[2] = maxX - minX;
        bbox[3] = maxY - minY;
        detectionObjects.push({
          class: classes[i],
          label: classesDir[classes[i]].name,
          score: score.toFixed(4),
          bbox: bbox
        })
      }
    })
    return detectionObjects
  }

  renderPredictions = predictions => {
    const ctx = this.canvasRef.current.getContext("2d");
    ctx.clearRect(0, 0, ctx.canvas.width, ctx.canvas.height);

    // Font options.
    const font = "16px sans-serif";
    ctx.font = font;
    ctx.textBaseline = "top";

    const [boxes, scores, classes, valid_detections] = predictions;
    const boxes_data = boxes.dataSync();
    const scores_data = scores.dataSync();
    const classes_data = classes.dataSync();
    const valid_detections_data = valid_detections.dataSync()[0];
    console.log('detect: ',scores_data, classes_data)

    //Getting predictions
    // const boxes = predictions[4].arraySync();
    // const scores = predictions[5].arraySync();
    // const classes = predictions[6].dataSync();

    // const detections = this.buildDetectedObjects(scores, threshold,
    //   boxes, classes, classesDir);

    // detections.forEach(item => {
    //   const x = item['bbox'][0];
    //   const y = item['bbox'][1];
    //   const width = item['bbox'][2];
    //   const height = item['bbox'][3];

    //   // Draw the bounding box.
    //   ctx.strokeStyle = "#00FFFF";
    //   ctx.lineWidth = 4;
    //   ctx.strokeRect(x, y, width, height);

    //   // Draw the label background.
    //   ctx.fillStyle = "#00FFFF";
    //   const textWidth = ctx.measureText(item["label"] + " " + (100 * item["score"]).toFixed(2) + "%").width;
    //   const textHeight = parseInt(font, 10); // base 10
    //   ctx.fillRect(x, y, textWidth + 4, textHeight + 4);
    // });

    // detections.forEach(item => {
    //   const x = item['bbox'][0];
    //   const y = item['bbox'][1];

    //   // Draw the text last to ensure it's on top.
    //   ctx.fillStyle = "#000000";
    //   ctx.fillText(item["label"] + " " + (100 * item["score"]).toFixed(2) + "%", x, y);
    // });
  };

  render() {
    return (
      <div> 
        <h3>Yolo - V5</h3>
        <video
          style={{ height: '600px', width: "500px" }}
          className="size"
          autoPlay
          playsInline
          muted
          ref={this.videoRef}
          width="600"
          height="500"
          id="frame"
        />
        <canvas
          className="size"
          ref={this.canvasRef}
          width="600"
          height="500"
        />
      </div>
    );
  }
}

export default App
```

### Environment

- Yolo: V5
- Python: 3.8.7
- Tensorflow 2

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by vancuonghoang** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.
> 
> ### YOLOv5 Component
> _No response_
> 
> ### Bug
> i feel that yolov5 cannot detect a video (or a camera live). I tried running my log, but it didn't detect it. but it can detect still image.
> 
> ```
> 
> import React from "react";
> import ReactDOM from "react-dom";
> import * as tf from '@tensorflow/tfjs';
> import { loadGraphModel } from '@tensorflow/tfjs-converter';
> import "./style-cam.css";
> tf.setBackend('webgl');
> 
> const weights = '/web_model/model.json';
> const threshold = 0.75;
> 
> 
> class App extends React.Component {
>   videoRef = React.createRef();
>   canvasRef = React.createRef();
>   
>   load_model = async () => {  
>     const model = await loadGraphModel(weights);   
>     return model;
>   }
> 
>   componentDidMount() {
>     if (navigator.mediaDevices && navigator.mediaDevices.getUserMedia) {
>       const webCamPromise = navigator.mediaDevices
>         .getUserMedia({
>           audio: false,
>           video: {
>             facingMode: "user"
>           }
>         })
>         .then(stream => {
>           window.stream = stream;
>           this.videoRef.current.srcObject = stream;
>           return new Promise((resolve, reject) => {
>             this.videoRef.current.onloadedmetadata = () => {
>               resolve();
>             };
>           });
>         });
> 
>         this.beginDetect(webCamPromise)
>     }
>   }
> 
>   beginDetect = async (webCamPromise)=>{
>     const modelPromise = await this.load_model();
>     console.log('modelPromise: ', modelPromise)
> 
>     Promise.all([modelPromise, webCamPromise])
>       .then(values => {
>         this.detectFrame(this.videoRef.current, values[0]);
>       })
>       .catch(error => {
>         console.error(error);
>       });
>   }
> 
>   detectFrame = (video, model) => {
>     tf.engine().startScope();
>     model.executeAsync(this.process_input(video)).then(predictions => {
>       this.renderPredictions(predictions, video);
>       requestAnimationFrame(() => {
>         this.detectFrame(video, model);
>       });
>       tf.engine().endScope();
>     });
>   };
> 
>   process_input(video_frame) {
>     const input = tf.tidy(() => {
>       return tf.image.resizeBilinear(tf.browser.fromPixels(video_frame), [640, 640])
>         .div(255.0).expandDims(0);
>     });
> 
>     this.preview = input
>     console.log('input: ', this.preview)
>     this.setState({ loading: false })
>     return input
>   };
> 
>   buildDetectedObjects(scores, threshold, boxes, classes, classesDir) {
>     const detectionObjects = []
>     var video_frame = document.getElementById('frame');
> 
>     scores[0].forEach((score, i) => {
>       if (score > threshold) {
>         const bbox = [];
>         const minY = boxes[0][i][0] * video_frame.offsetHeight;
>         const minX = boxes[0][i][1] * video_frame.offsetWidth;
>         const maxY = boxes[0][i][2] * video_frame.offsetHeight;
>         const maxX = boxes[0][i][3] * video_frame.offsetWidth;
>         bbox[0] = minX;
>         bbox[1] = minY;
>         bbox[2] = maxX - minX;
>         bbox[3] = maxY - minY;
>         detectionObjects.push({
>           class: classes[i],
>           label: classesDir[classes[i]].name,
>           score: score.toFixed(4),
>           bbox: bbox
>         })
>       }
>     })
>     return detectionObjects
>   }
> 
>   renderPredictions = predictions => {
>     const ctx = this.canvasRef.current.getContext("2d");
>     ctx.clearRect(0, 0, ctx.canvas.width, ctx.canvas.height);
> 
>     // Font options.
>     const font = "16px sans-serif";
>     ctx.font = font;
>     ctx.textBaseline = "top";
> 
>     const [boxes, scores, classes, valid_detections] = predictions;
>     const boxes_data = boxes.dataSync();
>     const scores_data = scores.dataSync();
>     const classes_data = classes.dataSync();
>     const valid_detections_data = valid_detections.dataSync()[0];
>     console.log('detect: ',scores_data, classes_data)
> 
>     //Getting predictions
>     // const boxes = predictions[4].arraySync();
>     // const scores = predictions[5].arraySync();
>     // const classes = predictions[6].dataSync();
> 
>     // const detections = this.buildDetectedObjects(scores, threshold,
>     //   boxes, classes, classesDir);
> 
>     // detections.forEach(item => {
>     //   const x = item['bbox'][0];
>     //   const y = item['bbox'][1];
>     //   const width = item['bbox'][2];
>     //   const height = item['bbox'][3];
> 
>     //   // Draw the bounding box.
>     //   ctx.strokeStyle = "#00FFFF";
>     //   ctx.lineWidth = 4;
>     //   ctx.strokeRect(x, y, width, height);
> 
>     //   // Draw the label background.
>     //   ctx.fillStyle = "#00FFFF";
>     //   const textWidth = ctx.measureText(item["label"] + " " + (100 * item["score"]).toFixed(2) + "%").width;
>     //   const textHeight = parseInt(font, 10); // base 10
>     //   ctx.fillRect(x, y, textWidth + 4, textHeight + 4);
>     // });
> 
>     // detections.forEach(item => {
>     //   const x = item['bbox'][0];
>     //   const y = item['bbox'][1];
> 
>     //   // Draw the text last to ensure it's on top.
>     //   ctx.fillStyle = "#000000";
>     //   ctx.fillText(item["label"] + " " + (100 * item["score"]).toFixed(2) + "%", x, y);
>     // });
>   };
> 
>   render() {
>     return (
>       <div> 
>         <h3>Yolo - V5</h3>
>         <video
>           style={{ height: '600px', width: "500px" }}
>           className="size"
>           autoPlay
>           playsInline
>           muted
>           ref={this.videoRef}
>           width="600"
>           height="500"
>           id="frame"
>         />
>         <canvas
>           className="size"
>           ref={this.canvasRef}
>           width="600"
>           height="500"
>         />
>       </div>
>     );
>   }
> }
> 
> export default App
> ```
> 
> ### Environment
> * Yolo: V5
> * Python: 3.8.7
> * Tensorflow 2
> 
> ### Minimal Reproducible Example
> _No response_
> 
> ### Additional
> _No response_
> 
> ### Are you willing to submit a PR?
> * [x]  Yes I'd like to help by submitting a PR!

How can you fix this issue? I am dealing with this.
I have the object in the 10 frames, but I missed it in the first 4,

**Comment by glenn-jocher** [comment]
@vancuonghoang if YOLOv5 is working on some frames then it is working. If you would like to improve your inference results, make sure you are training and running inference at the same image size, and of course to improve your training results see Tips for best results in tutorials below.

## Tutorials

- [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)  🚀 RECOMMENDED
- [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)  ☘️ RECOMMENDED
- [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
- [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) 🌟 NEW
- [TFLite, ONNX, CoreML, TensorRT Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
- [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
- [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
- [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
- [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
- [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)
- [Architecture Summary](https://docs.ultralytics.com/yolov5/tutorials/architecture_description) 🌟 NEW
- [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)
- [Roboflow for Datasets, Labeling, and Active Learning](https://docs.ultralytics.com/yolov5/tutorials/roboflow_datasets_integration)  🌟 NEW
- [ClearML Logging](https://docs.ultralytics.com/yolov5/tutorials/clearml_logging_integration) 🌟 NEW
- [Deci Platform](https://github.com/ultralytics/yolov5/wiki/Deci-Platform) 🌟 NEW
- [Comet Logging](https://docs.ultralytics.com/yolov5/tutorials/comet_logging_integration) 🌟 NEW

Good luck 🍀 and let us know if you have any other questions!
