### ISSUE TITLE
iDetection question

### ISSUE THREAD

**Issue by hiiksu** [ultralytics/yolov5#7417]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I'm going to use iDetection on my iPhone, so can I detect it using the weight I learned and the slightly modified 'detect.py'? I'm looking for the data, but it doesn't come out well.

**Comment by glenn-jocher** [comment]
@hiiksu you can train and deploy YOLOv5 models to your iPhone with Ultralytics HUB at https://hub.ultralytics.com/

**Comment by hiiksu** [comment]
@glenn-jocher Thank you very much. I think I'll have to go in and train again, so I'd like you to let me know if I can use in my IPhone the best.pt I've already trained and the modified detect.py. I'll do something about it after that. Thank you again.

**Comment by glenn-jocher** [comment]
@hiiksu you're welcome! Yes, you can use the best.pt file you've trained and the modified detect.py on your iPhone. Ensure that your modified detect.py includes the necessary code for deployment on iOS. If you encounter any issues during deployment, be sure to check our documentation at https://docs.ultralytics.com/yolov5/ for guidance. Good luck with your project and feel free to reach out if you need further assistance!
