### ISSUE TITLE
Model structure: Where is Focus layer used?

### ISSUE THREAD

**Issue by sduan1** [ultralytics/yolov5#7420]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi:
I am reading models and trying to understand a detailed structure of the internet. From what I see from the internet, input image goes through a Focus layer first. However, running the code I found that the input image goes to a Conv layer directly. More specifically, an input image of dim(1,3,640,640) goes through a Conv and becomes (1, 32, 320, 320). Could someone points out where Focus layer is used?

**Comment by sduan1** [comment]
I found the answer to my problem so I am closing this. For people with the same question, YOLOv5 removed Focus layer with a 6*6 Conv layer in version 6.

**Comment by glenn-jocher** [comment]
@sduan1 yes that's correct. See https://github.com/ultralytics/yolov5/releases/tag/v6.0
