### ISSUE TITLE
Can anyone help me on how to show the non-detection class?

### ISSUE THREAD

**Issue by HeitorDC** [ultralytics/yolov5#7421]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, guys!

When we run the "detect.py" script, how can we show every time that the algorithm doesn't identify the specific class with the "--class 0" arg, per example? Like, if we run the algorithm and there isn't a person in front of the camera, how can I print that information of non-detect class?

Thanks a lot!

**Comment by glenn-jocher** [comment]
👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, etc.
# model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')  # custom trained model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by HeitorDC** [comment]
Hi, @glenn-jocher, thanks for your answer! But what you said is when you have the class in front of the camera or in pics or videos, but I'm talking about when you don't have the specific class, like the "--class 0", and how can I print that on the output? That's my concern and doubt.

**Comment by glenn-jocher** [comment]
@HeitorDC got it! When running YOLOv5 inference with the `--class` flag, the absence of a specific class in the output is not explicitly displayed. As a workaround, you can inspect the resulting class indices and their corresponding confidence scores from the output tensors. If the desired class is not detected, no entries corresponding to that class will be present in the output.

You can then add custom logic to handle cases where the desired class is not detected based on your specific application needs.

Let me know if you need further assistance with this approach!
