### ISSUE TITLE
C3 Dense Block explaination

### ISSUE THREAD

**Issue by MirkoLegnini** [ultralytics/yolov5#7423]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am trying to understand a part of the architecture. Looking on papers and on previous discussions here I understood the general C3 structure and the two convolutions used instead of splitting the tensor. However, I have an issue in understanding what the current implementation of the Sequential bottlenecks with e=1 is in relation to the paper (the line below).
`self.m = nn.Sequential(*(Bottleneck(c_, c_, shortcut, g, e=1.0) for _ in range(n)))`
It looks to me as a sequence of Res blocks, however in the paper the dense block is described differently as a series of copies and concatenations of tensors as in the image below. Is this an optimization for efficiency or is there something I am missing?   

![image](https://user-images.githubusercontent.com/62476194/163417170-07eb5183-2b6a-4e8b-a58c-b35aec6f43c0.png)

**Comment by glenn-jocher** [comment]
@MirkoLegnini I created C3 as a simplified CSP bottleneck block.

**Comment by MirkoLegnini** [comment]
Thank you! So the internal architecture of that block does not match the one discussed in the CSP paper. Is it right to say the same for the m module in the BottleneckCSP layer in common.py? Otherwise I don't think I have fully understood. Thank you again for your attention.

**Comment by glenn-jocher** [comment]
@MirkoLegnini that's correct. Our implementation of the C3 block differs from the one described in the CSP paper. The "m" module in the BottleneckCSP layer in common.py also follows a different internal architecture. If you have further questions, feel free to ask. We're here to help!
