### ISSUE TITLE
I got an incredible result based on YOLOv5l model in my dataset(one classes, 2000 image), mAP@0.5 is 99.4%, mAP@0.5-0.9 is 93%.

### ISSUE THREAD

**Issue by hu-luoye** [ultralytics/yolov5#7425]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I got an incredible result based on YOLOv5l model in my dataset(one classes, 2000 image), mAP@0.5 is 99.4%, mAP@0.5-0.9 is 93%. I use Faster RCNN get mAP@0.5 is 95%.

### Additional

I got an incredible result based on YOLOv5l model in my dataset(one classes, 2000 image), mAP@0.5 is 99.4%, mAP@0.5-0.9 is 93%. I use Faster RCNN get mAP@0.5 is 95%.

**Comment by zhiqwang** [comment]
Hahaha, that's the super power of YOLOv5!

**Comment by hu-luoye** [comment]
The mAP is too high, is this normal? There is only one class, is it overfitting?

**Comment by hu-luoye** [comment]
> Hahaha, that's the super power of YOLOv5!

The mAP is too high, is this normal? There is only one classess in my dataset, is it overfitting?

**Comment by zhiqwang** [comment]
Overfitting is not defined as a high mAP in the test dataset, it is up to you to trust your test dataset here.

**Comment by hu-luoye** [comment]
> Overfitting is not defined as a high mAP in the test dataset, it is up to you to trust your test dataset here.
I get it, thank you!

**Comment by glenn-jocher** [comment]
@hu-luoye you're welcome! If you have any further questions, feel free to ask.
