### ISSUE TITLE
Why do the parameters of the yolov5s.yaml in the code do not match the model output?The model output of SPPF is 512 does not match the number of channels in yaml 1024

### ISSUE THREAD

**Issue by myylo** [ultralytics/yolov5#7426]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

![image](https://user-images.githubusercontent.com/97141707/163505239-cccbd732-0b85-48ea-a93a-e7a22e59b9a1.png)
![874daec3beab121e59910ff7293b487](https://user-images.githubusercontent.com/97141707/163505283-212ddd63-eccd-4b9e-849b-3230160df2e4.png)

**Comment by glenn-jocher** [comment]
@myylo models are compound scaled:
https://github.com/ultralytics/yolov5/blob/014acde79daee83e1f1801412cc7a48293e6e1f2/models/yolov5s.yaml#L5-L6
