### ISSUE TITLE
TensorRT bindings version

### ISSUE THREAD

**Issue by Tailwhip** [ultralytics/yolov5#7431]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

A snippet from export.py:
```
def export_engine(model, im, file, train, half, simplify, workspace=4, verbose=False, prefix=colorstr('TensorRT:')):
    try:
        check_requirements(('tensorrt',))
        import tensorrt as trt
    ...
```
The check requirements function downloads some weird package called: tensorrt-0.0.1 which is that one I belive: https://pypi.org/project/tensorrt/
Unfortunately I can't find any information about real TensorRT version used for this package.
So my questions are:
What is REAL version of TensorRT used for tensorrt-0.0.1 package (because obviously 0.0.1 is not the one)?
Why don't use nvidia-tensorrt instead?

Btw I commented that "check_requirements" line and used manually preinstalled nvidia-tensorrt 8.0.1.6 package instead to create float16 engine and it worked.

Thank you in advance.

**Comment by glenn-jocher** [comment]
@Tailwhip good news 😃! Your original issue may now be fixed ✅ in PR #7439. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
