### ISSUE TITLE
Error loading torch\lib\cublas64_11.dll 

### ISSUE THREAD

**Issue by zyakubova86** [ultralytics/yolov5#7433]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

I am trying to train my custom object detection model. But  Error loading "C:\Python38\lib\site-packages\torch\lib\cublas64_11.dll" or one of its dependencies. this error occuring. Running on windows server 20222. How can I fix this?

### Minimal Reproducible Example

![image](https://user-images.githubusercontent.com/74640447/163563420-21ef6e47-3b8c-4d11-aae1-25fe234974ae.png)

### Additional

![image](https://user-images.githubusercontent.com/74640447/163563489-f04d9a84-2cbb-45cf-bdc6-278e63462150.png)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@zyakubova86 it appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual [Python 3.9](https://www.python.org/) environment, clone the latest repo ([code changes daily](https://github.com/ultralytics/yolov5/commits/master)), and `pip install` [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) again from scratch.

💡 ProTip! Try one of our verified environments below if you are having trouble with your local environment.


## Requirements

[**Python>=3.7.0**](https://www.python.org/) with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) installed including [**PyTorch>=1.7**](https://pytorch.org/get-started/locally/). To get started:
```bash
git clone https://github.com/ultralytics/yolov5  # clone
cd yolov5
pip install -r requirements.txt  # install
```

[Models](https://github.com/ultralytics/yolov5/tree/master/models) and [datasets](https://github.com/ultralytics/yolov5/tree/master/data) download automatically from the latest YOLOv5 [release](https://github.com/ultralytics/yolov5/releases) when first requested.

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), validation ([val.py](https://github.com/ultralytics/yolov5/blob/master/val.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/export.py)) on MacOS, Windows, and Ubuntu every 24 hours and on every commit.

**Comment by zyakubova86** [comment]
Thanks for your reply! I am training  custom dataset on windows server 2022 with python 3.8.8. I cloned the latest yolov5 repo. 
![image](https://user-images.githubusercontent.com/74640447/163661869-fd2b0463-4d5a-42d0-82d8-b857f0e51f47.png)

![image](https://user-images.githubusercontent.com/74640447/163661898-44ce10bc-e94c-4522-943b-4b65153ee081.png)

![image](https://user-images.githubusercontent.com/74640447/163661910-68a57214-1a88-489d-97d9-fb449fc0b93e.png)


What can u advise for better performance?

**Comment by glenn-jocher** [comment]
@zyakubova86 Great! It looks like you have everything set up correctly. For better performance during training, you can consider the following tips:

1. Use a powerful GPU if available, as it significantly speeds up training.
2. Utilize mixed precision training with `--precision 16` flag for faster training on [GPU](https://pytorch.org/docs/stable/amp.html#torch.cuda.amp.GradScaler).
3. Increase batch size and input image size if your GPU memory allows it. Larger batch sizes can speed up training.
4. Preprocess your dataset to remove any unnecessary or low-quality images.

You can also refer to our [training tutorial](https://docs.ultralytics.com/yolov5/training) in the documentation for more detailed guidance on optimizing your training process.

Don't hesitate to reach out if you have any other questions or need further assistance!
