### ISSUE TITLE
Tensor shape 

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#7434]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm deploying yolov5, when I run the inference I got strange results, tensor shape is [3, 80, 80, 85],
when I try to see what's inside I have endless floats [[[[[0.02177705615758896, -0.016108281910419464, -0.09557366371154785, -0.23833107948303223, -10.553'..........

I need to use weights.pth for that I have done this : 
image = torch.zeros([1, 3, 640, 640], dtype=torch.float32)
model.train()
model_trace = torch.jit.trace(model, image) 
model_trace.save('model.pth')

The image shape before inference is : torch.Size([1, 3, 640, 640]) since we need batch inference.
So my question how can I interpret this result's shape, how can I know which classes has been detected ? 
tensor shape is [3, 80, 80, 85],

**Comment by glenn-jocher** [comment]
@sinatimelapse 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, etc.
# model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')  # custom trained model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by ghost** [comment]
Hello, thank you for your answer, I've read the tutoriel several times, but I can't find how to interpret this tensor shape [3, 80, 80, 85], how can I know what was actually detected ?

**Comment by glenn-jocher** [comment]
@ghost 👋 No worries, happy to help! The tensor shape `[3, 80, 80, 85]` represents the model's output, specifically `batch size`, `grid size`, `number of bounding boxes per grid cell`, and `attributes per bounding box`. To infer the classes detected from this tensor, you can use the following code snippet:
```python
import torch
from pathlib import Path

# Load the model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Load a test image
img = Path('path_to_image.jpg')

# Perform inference
results = model(img)

# Access detected classes from the results
detected_classes = results.names

# Iterate through detected objects and their details
for det in results.pandas().xyxy[0].iterrows():
    print(f"Detected {detected_classes[det[1]['class']]} with confidence {det[1]['confidence']}")
```
This code uses the YOLOv5 PyTorch Hub model to perform inference on an image and retrieves the detected classes with their respective confidence scores.

I hope this helps! Let me know if you need further assistance.
