### ISSUE TITLE
the value of confusion matrix is different from the one in terminal

### ISSUE THREAD

**Issue by shenhaibb** [ultralytics/yolov5#7442]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

![confusion_matrix](https://user-images.githubusercontent.com/64736467/163657712-8e1278ff-b77b-4ae8-80a5-9e29311717b7.png)
<img width="955" alt="image" src="https://user-images.githubusercontent.com/64736467/163657716-d72a1f20-c6de-4ab8-9b0b-c8fbddd146c9.png">
i know the value of confusion matrix is computed by max iou
and the value of terminal is computed by max f1
what i want to ask is how to computed by the same way and output the same result
can u give me a guide? thank u very much

**Comment by shenhaibb** [comment]
take 'small-vehicle' as an example:
32(32+66)=0.3265
32/(32+1)=0.9696
0.3265 and 0.9696 of the confusion matrix is different from 0.651 and 0.7273 of the terminal

**Comment by beauty-snowman** [comment]
hi, i have the same question. Do you have any idea?

**Comment by glenn-jocher** [comment]
@shenhaibb @beauty-snowman confusion matrix is plotted at conf=0.25. Console metrics that are a function of confidence (P, R) are calculated at 1000 different confidences and then displayed at max-F1 confidence.
https://github.com/ultralytics/yolov5/blob/6ea81bb3a9bb1701bc0aa9ccca546368ce1fa400/utils/metrics.py#L117-L119

**Comment by shenhaibb** [comment]
> @shenhaibb @beauty-snowman confusion matrix is plotted at conf=0.25. Console metrics that are a function of confidence (P, R) are calculated at 1000 different confidences and then displayed at max-F1 confidence.
> 
> https://github.com/ultralytics/yolov5/blob/6ea81bb3a9bb1701bc0aa9ccca546368ce1fa400/utils/metrics.py#L117-L119

Sorry, I still don't quite understand. What do you mean by ‘1000 different confidences‘? Does conf = 1 count to conf = 0.001? 
I also try to set the confidence threshold and iou threshold in val.py, the same as those in the confusion function class, but it doesn't work. So how can I set them to make their values the same?
![image](https://user-images.githubusercontent.com/64736467/164576388-584a2d85-3094-4427-8b28-42e53d47bf70.png)
![image](https://user-images.githubusercontent.com/64736467/164576317-1abf0e59-16a4-4c6d-b3b8-50a85959da0f.png)

**Comment by yesid-acm** [comment]
> @shenhaibb @beauty-snowman confusion matrix is plotted at conf=0.25. Console metrics that are a function of confidence (P, R) are calculated at 1000 different confidences and then displayed at max-F1 confidence.
> 
> https://github.com/ultralytics/yolov5/blob/6ea81bb3a9bb1701bc0aa9ccca546368ce1fa400/utils/metrics.py#L117-L119

@glenn-jocher Please, could you be clearer in your answers or cite the links where they give clarity? I see in several posts that people end up with doubt after your answers. The issue of the IOU and Trust thresholds in the different train, val and detect Scripts are doubtful even after several hours of reviewing your Post and browsing the code.

@glenn-jocher In this link:  https://github.com/ultralytics/yolov5/issues/1665#issuecomment-966166895  I understand that if I use F1's max confi, then I would expect to get values ​​similar to what the console prints? OK? It explains well how we could obtain those same values ​​(P,R) that are printed on the console and visualize them in the confusion matrix (it would be expected that the recalls are the same values ​​of the diagonal of the matrix, yes??? thanksss

**Comment by glenn-jocher** [comment]
@yesid-acm @beauty-snowman The console metrics are calculated based on a range of confidence thresholds to obtain precision and recall, and then displayed at the maximum F1 score confidence. The confusion matrix, on the other hand, is plotted at a fixed confidence threshold of 0.25. Therefore, the values may not directly match due to this difference in computation.

Regarding setting the confidence threshold and IOU threshold, it seems like you've tried adjusting them in the val.py script, but without success. The max F1 confidence is not the same as the 0.25 confidence threshold for the confusion matrix. To obtain comparable values, you may want to consider adjusting the confidence thresholds or calculating the precision and recall at the fixed 0.25 confidence for direct comparison with the confusion matrix diagonal values.

Thank you for your patience as we work through this together.
