### ISSUE TITLE
The performance of Yolov5 on UAVDT is over 99%?  

### ISSUE THREAD

**Issue by yuexiemail** [ultralytics/yolov5#7443]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I train standard Yolov5s on UAVDT, the training image size is 640 × 640. The ap is more than 99%, as shown in Figure below.
![图片](https://user-images.githubusercontent.com/87051995/163657743-17ae58cf-a2e4-4b0d-9bdb-a25faf430bc9.png)
Based many exited papers reported, the AP of the existing detector, including Faster RCNN,  is less than 30%.
Anyone could help me deal with the problem?

### Additional

Nothing

**Comment by glenn-jocher** [comment]
@yuexiemail that's an impressive result! YOLOv5 is known for its strong performance in detection tasks. The high AP on UAVDT is a testament to the hard work of the YOLO community and the dedication of the Ultralytics team to develop and maintain a robust detector. If you need further assistance, feel free to consult the Ultralytics Docs for detailed guidance. Keep up the great work!
