### ISSUE TITLE
Will the changes of structure affect the pretrained model?

### ISSUE THREAD

**Issue by vvision0** [ultralytics/yolov5#7448]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I tried different attention modules including SE layer, CBAM and coordinate attention recently, all of which are added between the last C3 layer and SPPF respectively. 
The pretrained model was used and a new training need much more epochs to reach convergence while the original model only need 50. The Map is even lower than orinal after 200epochs training. 
Then i tried to replace C3 layer with C3Ghost in yolov5s.yaml, and 50 epochs are also not enough to converge when using yolov5s.pt.
If the new backbone is different with the backbone in pretrained model, should i train from scratch or train after pretrained model?

**Comment by glenn-jocher** [comment]
@vvision0 if you want valid comparisons between different architectures obviously you train from scratch.

**Comment by vvision0** [comment]
Thank you very much
