### ISSUE TITLE
open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1

### ISSUE THREAD

**Issue by Mashaakim** [ultralytics/yolov5#7449]
Hello!

I'm using yolov5 for object detection on Jetson Nano via ssh connection. 
I ran `sudo python3 detect.py --weights my_weights.pt --source 0 --device 0`
I want it to open the window with real-time object detection, but I got the error:

```
> Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.25, device='0', exist_ok=False, img_size=640, iou_thres=0.45, name='exp', project='runs/detect', save_conf=False, save_txt=False, source='0', update=False, view_img=False, weights=['yolov5/weights/best.pt'])
> YOLOv5 v4.0-126-g886f1c0 torch 1.10.0a0+git36449ea CUDA:0 (NVIDIA Tegra X1, 3964.15625MB)
> 
> Fusing layers... 
> Model Summary: 232 layers, 7249215 parameters, 0 gradients
> No protocol specified
> Unable to init server: Could not connect: Connection refused
> WARNING: Environment does not support cv2.imshow() or PIL Image.show() image displays
> OpenCV(4.5.1) /home/maria/opencv/modules/highgui/src/window_gtk.cpp:624: error: (-2:Unspecified error) Can't initialize GTK backend in function 'cvInitSystem'
> 
> [ WARN:0] global /home/maria/opencv/modules/videoio/src/cap_gstreamer.cpp (961) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
> 1/1: 0...  success (2560x1472 at 2.00 FPS).
> 
> /usr/local/lib/python3.6/dist-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
>   return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
```

After that is started to detect something, but I can't see the image.
```
0: 384x640 Done. (1.154s)
0: 384x640 Done. (0.117s)
0: 384x640 Done. (0.117s)
0: 384x640 Done. (0.117s)
0: 384x640 Done. (0.118s)
```

Thank you very much for any help!

**Comment by glenn-jocher** [comment]
@Mashaakim it's running inference on your source and printing results to screen. If no objects are detected you will see output like yours.

Not all environments support showing results live. 

Also note that your YOLOv5 is very out of date, you should update to the latest version for best results.  To update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>
