### ISSUE TITLE
How to print the epochs details while training is happening?

### ISSUE THREAD

**Issue by wajhh** [ultralytics/yolov5#7450]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to print the epochs details while the training is running so I know where the situation is and how long would it take. Any leads please ?

!python train.py --img 416 --batch 32 --epochs 1 --data coco128.yaml --weights yolov5s.pt --cache

^ I am using this line to print. Any help would be appreciated big time please.Thanks

### Additional

Please help

**Comment by glenn-jocher** [comment]
@wajhh training details are printed to screen automatically, as well as logged by CSV, TensorBoard and W&B loggers.

**Comment by RANA-ATI** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.
> 
> ### Question
> I want to print the epochs details while the training is running so I know where the situation is and how long would it take. Any leads please ?
> 
> !python train.py --img 416 --batch 32 --epochs 1 --data coco128.yaml --weights yolov5s.pt --cache
> 
> ^ I am using this line to print. Any help would be appreciated big time please.Thanks
> 
> ### Additional
> Please help

I am facing the same issue. It shows only model summary and total MAP50 information at the end of training.

**Comment by RANA-ATI** [comment]
@glenn-jocher Yes you are right, basically I was at VS Code where I think it update the output cell and that was the reason I couldn't see the epochs. I ran it in the terminal and it showed the expected information.

**Comment by glenn-jocher** [comment]
Glad to hear that running it in the terminal worked for you, @RANA-ATI! Feel free to reach out if you have any more questions or need further assistance. Good luck with your training!
