### ISSUE TITLE
Different train time on different GPU

### ISSUE THREAD

**Issue by O2andsAnoxia** [ultralytics/yolov5#7452]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I found something strange.
I trained my custom datasets(about 6000 imgs) on three differen GPU:GTX2060S,Tesla V100,GTX TITAN X
I found the train time per epoch decreased with the epochs  and it cost 10 hours on 100 epochs. 
But the train time of V100 is same per epoch, needing 16 hours on 100 epochs, the TITAN X is similar with V100.

I‘m so curious what happened. Maybe different architecture? GTX2060S:Turing, Tesla V100: Vlota, GTX TITAN X: Pascal

**Comment by glenn-jocher** [comment]
@O2andsAnoxia 👋 Hello! Thanks for asking about **training speed issues**. YOLOv5 🚀 can be trained on CPU (slowest), [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) (fastest). GPU training times will vary by software, hardware and drivers. We recommend our Docker image for most consistent training results.

If you would like to increase your training speed some options are:

- Increase `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s
- Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) DDP at larger `--batch-size`
- Train with a cached dataset: `python train.py --cache`
- Train on faster GPUs, i.e.: P100 -> V100 -> A100
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

Good luck 🍀 and let us know if you have any other questions!
