### ISSUE TITLE
tensorrt infer code

### ISSUE THREAD

**Issue by lyc728** [ultralytics/yolov5#7464]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, do you have the TRT inference code

**Comment by glenn-jocher** [comment]
@lyc728 it's very simple:

```bash
python export.py --weights yolov5s.pt --include engine
python detect.py --weights yolov5s.engine
```

**Comment by lyc728** [comment]
> @lyc728 it's very simple:
> 
> ```shell
> python export.py --weights yolov5s.pt --include engine
> python detect.py --weights yolov5s.engine
> ```
Switching to TRT is time-consuming and unsuccessful

**Comment by lyc728** [comment]
> @[glenn-jocher](https://github.com/glenn-jocher) it's very simple:
> 
> ```shell
> python export.py --weights yolov5s.pt --include engine
> python detect.py --weights yolov5s.engine
> ```
Switching to TRT is time-consuming and unsuccessful

**Comment by glenn-jocher** [comment]
@lyc728 what seems to be the problem?
