### ISSUE TITLE
Yolov5 finetune on custom data

### ISSUE THREAD

**Issue by MikeMACintosh** [ultralytics/yolov5#7465]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, thanking you for your model, she is learning and working very fast. 
I have a task: I need to train yolov5 to be able to detect 3 more classes that are not in coco, while classes from Coco should also be detected. I'm doing as it says in your guide, I collected a dataset and trained it only on my three categories, but the model stopped detecting objects from coco (cars, bus etc.). 
I tried freezing the layers, but it didn't help. Could you explain how I can achieve what I want? Perhaps the answer lies in the freezing of the head? I have an idea to teach again in my three classes + coco, but it seems wrong to me.

**Comment by glenn-jocher** [comment]
@MikeMACintosh see https://community.ultralytics.com/t/how-to-combine-weights-to-detect-from-multiple-datasets
