### ISSUE TITLE
Does the size of batch-size affect the results?

### ISSUE THREAD

**Issue by NingYuanLin** [ultralytics/yolov5#7466]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, Thanks for your works.  
I set `--batch-size -1` in training. The program make `--batch-size 14` when `--imgsz 640` and `--batch-size 3` when `--imgsz 1280`. My GPU only have 12G memory. I have two questions:
1. Is YOLOv5 susceptible to batch-size? Has anyone tested it?
2. Someone say `--batch-size` should be a even number, such as 2,4,8... . Does batch-size of 14 or 3 have the adverse effect on results?

**Comment by AlphaSlayer1964** [comment]
Look at #2377 and #2452

**Comment by NingYuanLin** [comment]
> Look at #2377 and #2452

Thank you~

**Comment by glenn-jocher** [comment]
@NingYuanLin batch size does not have to be an even number, that's some ML myth. It does have to be evenly divisible by your GPU count obviously if you are training multi-GPU.

**Comment by NingYuanLin** [comment]
> @NingYuanLin batch size does not have to be an even number, that's some ML myth. It does have to be evenly divisible by your GPU count obviously if you are training multi-GPU.

thank you. I get it.~
