### ISSUE TITLE
Best iou,confidence threshold for train and inference

### ISSUE THREAD

**Issue by Miho-an-kou** [ultralytics/yolov5#7469]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

1. How to find the best IOU threshold of custom dataset?
2. How to calculate the most appropriate confidence threshold under the condition of good precision and recall for inference?
Thanks for advice!

**Comment by glenn-jocher** [comment]
@Miho-an-kou select max F1 curve confidence from the val.py plots, i.e. about 0.35 here following YOLOv5s VOC training:

![image](https://user-images.githubusercontent.com/26833433/164110255-4228829f-cda0-4ab9-ba4b-00c5f99989f5.png)

**Comment by Miho-an-kou** [comment]
> @Miho-an-kou select max F1 curve confidence from the val.py plots, i.e. about 0.35 here following YOLOv5s VOC training:
> 
> ![image](https://user-images.githubusercontent.com/26833433/164110255-4228829f-cda0-4ab9-ba4b-00c5f99989f5.png)

Thanks

Similarly, is the best IOU in the following PR_curve generated by val.py is 0.5?
<img width="1125" alt="PR_curve" src="https://user-images.githubusercontent.com/72844292/164127637-142e8c00-dab9-4e39-a944-b829a3870ffb.png">
