### ISSUE TITLE
What are the default value and type of opt.classes and opt.agnostic-nms and opt.iou_thres?

### ISSUE THREAD

**Issue by peijason** [ultralytics/yolov5#747]
## ❔Question

What are the default value and type of **opt.classes** and **opt.agnostic-nms** ?

## Additional context

In file `detect.py`, `pred = non_max_suppression(pred, opt.conf_thres, opt.iou_thres, classes=opt.classes, agnostic=opt.agnostic_nms)` seems to be **ALWAYS** called. However, it looks `opt.iou_thres` has **NEVER** been pre-assigned any value, while `opt.classes` has **NO** default value in argument, same as `opt.agnostic_nms`.

So, can anybody explain a bit what are these parameters for? And why without **pre-assignment**, this `detect.py` still works?

Cheers

**Comment by glenn-jocher** [comment]
@peijason the default values of all argparser arguments are self evident in the relevant file. For detect.py:
https://github.com/ultralytics/yolov5/blob/f5da528d280af5d106e80eceddefd427cf9aed32/detect.py#L150-L166

NMS is always called, it is a fundamental step in detection following inference.

**Comment by peijason** [comment]
@glenn-jocher 
But, where is **opt.iou_thres**?

**Comment by glenn-jocher** [comment]
@peijason opt.iou_thres is part of the argparser arguments in detect.py:
https://github.com/ultralytics/yolov5/blob/f5da528d280af5d106e80eceddefd427cf9aed32/detect.py#L156

**Comment by peijason** [comment]
Thank you @glenn-jocher
