### ISSUE TITLE
Train too slow on yolov5-6.1 compared with yolov5-5.0

### ISSUE THREAD

**Issue by Etern213** [ultralytics/yolov5#7470]
`###` Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

In the past few month, I use yolov5-5.0 to train models. Use gpu 1660ti to train my own datasets, train speed is 1.5-1.9 it/s, about 10min each epoch.

And today I update my project to yolov5-6.1, use almost the same arguments, same datasets and same gpu, but train speed is 2-2.5 s/it, about 25min each epoch. It's too slow compared to yolov5-5.0, I tried many ways to solve it but none of it works.

My pytorch version was 1.9.0+cuda102 when I use yolov5-5.0, and I update it to 1.11.0+cuda113, but it doesn't change train speed, still 2-2.5 s/it.

**Here are the arguments I use in 6.1:**
```
    parser.add_argument('--weights', type=str, default='', help='initial weights path')   # ROOT / 'yolov5s.pt'
    parser.add_argument('--cfg', type=str, default=ROOT / 'models/yolov5m.yaml', help='model.yaml path')
    parser.add_argument('--data', type=str, default=ROOT / 'cardata2/cardata2.yaml', help='dataset.yaml path')
    parser.add_argument('--hyp', type=str, default=ROOT / 'data/hyps/hyp.scratch-low.yaml', help='hyperparameters path')
    parser.add_argument('--epochs', type=int, default=90)
    parser.add_argument('--batch-size', type=int, default=20, help='total batch size for all GPUs, -1 for autobatch')
    parser.add_argument('--imgsz', '--img', '--img-size', type=int, default=640, help='train, val image size (pixels)')
    parser.add_argument('--rect', action='store_true', help='rectangular training')
    parser.add_argument('--resume', nargs='?', const=True, default=False, help='resume most recent training')
    parser.add_argument('--nosave', action='store_true', help='only save final checkpoint')
    parser.add_argument('--noval', action='store_true', help='only validate final epoch')
    parser.add_argument('--noautoanchor', action='store_true', help='disable AutoAnchor')
    parser.add_argument('--evolve', type=int, nargs='?', const=300, help='evolve hyperparameters for x generations')
    parser.add_argument('--bucket', type=str, default='', help='gsutil bucket')
    parser.add_argument('--cache', type=str, nargs='?', const='ram', help='--cache images in "ram" (default) or "disk"')
    parser.add_argument('--image-weights', action='store_true', help='use weighted image selection for training')
    parser.add_argument('--device', default='', help='cuda device, i.e. 0 or 0,1,2,3 or cpu')
    parser.add_argument('--multi-scale', action='store_true', help='vary img-size +/- 50%%')
    parser.add_argument('--single-cls', action='store_true', help='train multi-class data as single-class')
    parser.add_argument('--optimizer', type=str, choices=['SGD', 'Adam', 'AdamW'], default='SGD', help='optimizer')
    parser.add_argument('--sync-bn', action='store_true', help='use SyncBatchNorm, only available in DDP mode')
    parser.add_argument('--workers', type=int, default=1, help='max dataloader workers (per RANK in DDP mode)')
    parser.add_argument('--project', default=ROOT / 'runs/train', help='save to project/name')
    parser.add_argument('--name', default='exp', help='save to project/name')
    parser.add_argument('--exist-ok', action='store_true', help='existing project/name ok, do not increment')
    parser.add_argument('--quad', action='store_true', help='quad dataloader')
    parser.add_argument('--cos-lr', action='store_true', help='cosine LR scheduler')
    parser.add_argument('--label-smoothing', type=float, default=0.0, help='Label smoothing epsilon')
    parser.add_argument('--patience', type=int, default=100, help='EarlyStopping patience (epochs without improvement)')
    parser.add_argument('--freeze', nargs='+', type=int, default=[0], help='Freeze layers: backbone=10, first3=0 1 2')
    parser.add_argument('--save-period', type=int, default=-1, help='Save checkpoint every x epochs (disabled if < 1)')
    parser.add_argument('--local_rank', type=int, default=-1, help='DDP parameter, do not modify')

    # Weights & Biases arguments
    parser.add_argument('--entity', default=None, help='W&B: Entity')
    parser.add_argument('--upload_dataset', nargs='?', const=True, default=False, help='W&B: Upload data, "val" option')
    parser.add_argument('--bbox_interval', type=int, default=-1, help='W&B: Set bounding-box image logging interval')
    parser.add_argument('--artifact_alias', type=str, default='latest', help='W&B: Version of dataset artifact to use')

>D:/Anaconda3/envs/YoloV5/python.exe D:\Code\Python\code\yolov5-6.1\train.py --rect
```

**Here are the arguments I use in 5.0:**
```
    parser.add_argument('--weights', type=str, default='', help='')
    parser.add_argument('--cfg', type=str, default='models/yolov5m.yaml', help='')
    parser.add_argument('--data', type=str, default='cardata2/cardata2.yaml', help='')
    parser.add_argument('--hyp', type=str, default='data/hyp.scratch.yaml', help='')
    parser.add_argument('--epochs', type=int, default=90, help='')
    parser.add_argument('--batch-size', type=int, default=20, help='')
    parser.add_argument('--img-size', nargs='+', type=int, default=[640, 640], help='')
    parser.add_argument('--rect', action='store_true', help='')
    parser.add_argument('--resume', nargs='?', const=True, default=False, help='')
    parser.add_argument('--nosave', action='store_true', help='')
    parser.add_argument('--notest', action='store_true', help='')
    parser.add_argument('--noautoanchor', action='store_true', help='')
    parser.add_argument('--evolve', action='store_true', help='')
    parser.add_argument('--bucket', type=str, default='', help='')
    parser.add_argument('--cache-images', action='store_true', help='')
    parser.add_argument('--image-weights', action='store_true', help='')
    parser.add_argument('--device', default='', help='')
    parser.add_argument('--multi-scale', action='store_true', help='')
    parser.add_argument('--single-cls', action='store_true', help='')
    parser.add_argument('--adam', action='store_true', help='')
    parser.add_argument('--sync-bn', action='store_true', help='')
    parser.add_argument('--local_rank', type=int, default=-1, help='DDP parameter, do not modify')
    parser.add_argument('--workers', type=int, default=1, help='')
    parser.add_argument('--project', default='runs/train', help='')
    parser.add_argument('--entity', default=None, help='')
    parser.add_argument('--name', default='exp', help='')
    parser.add_argument('--exist-ok', action='store_true', help='')
    parser.add_argument('--quad', action='store_true', help='')
    parser.add_argument('--linear-lr', action='store_true', help='')
    parser.add_argument('--label-smoothing', type=float, default=0.0, help='')
    parser.add_argument('--upload_dataset', action='store_true', help='Upload dataset as W&B artifact table')
    parser.add_argument('--bbox_interval', type=int, default=-1, help='Set bounding-box image logging interval for W&B')
    parser.add_argument('--save_period', type=int, default=-1, help='Log model after every "save_period" epoch')
    parser.add_argument('--artifact_alias', type=str, default="latest", help='version of dataset artifact to be used')

>D:/Anaconda3/envs/YoloV5/python.exe D:/Code/Python/code/YOLOv5/train.py --rect
```

My English is poor, so sorry about it. 
But I have to use this project to finish my paper, so its urgent. Can you figure out some possible reason? Thank you very much!@glenn-jocher

**Comment by Etern213** [comment]
"nvidia-smi" shows that yolov5-5.0 can use 80W power for my 1660ti (1660ti has 80W tdp), But yolov5-6.0 can only use 50W. 
Maybe this is the reason? But how to solve it?

yolov5-5.0      66/754 [00:58<08:26,  1.36it/s]           GPU power is about 80W
yolov5-6.0      29/603[02:10<43:10,  4.51s/it]            GPU power is about 50W

@glenn-jocher

**Comment by Etern213** [comment]
#5466  and #5808 have the same problem, But their solution did not solve my problem.
I have tried many pytorch version. 1.8.0+cu102, 1.9.0+cu102, 1.10.0+cu102, 1.10.1+cu102, none of them work. I also tried pytorch 1.11.0+cu113, still nothing.

It is interesting that with YoloV5-5.0, my 1660ti can run on 80W tdp, But with YoloV5-6.0and6.1, my 1660ti can only run on 50w, 48W,49W,52W,54W,48W,etc.

Since that I must use YoloV5 to finish my college paper, so its important, really hope you can help me. Sincerely thanks.

@glenn-jocher

**Comment by glenn-jocher** [comment]
@Etern213 it appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual [Python 3.9](https://www.python.org/) environment, clone the latest repo ([code changes daily](https://github.com/ultralytics/yolov5/commits/master)), and `pip install` [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) again from scratch.

💡 ProTip! Try one of our verified environments below if you are having trouble with your local environment.


## Requirements

[**Python>=3.7.0**](https://www.python.org/) with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) installed including [**PyTorch>=1.7**](https://pytorch.org/get-started/locally/). To get started:
```bash
git clone https://github.com/ultralytics/yolov5  # clone
cd yolov5
pip install -r requirements.txt  # install
```

[Models](https://github.com/ultralytics/yolov5/tree/master/models) and [datasets](https://github.com/ultralytics/yolov5/tree/master/data) download automatically from the latest YOLOv5 [release](https://github.com/ultralytics/yolov5/releases) when first requested.

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), validation ([val.py](https://github.com/ultralytics/yolov5/blob/master/val.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/export.py)) on MacOS, Windows, and Ubuntu every 24 hours and on every commit.

**Comment by Etern213** [comment]
> 

Thanks for your reply. I also think it is a environment problem at first. But I tried python3.7/3.8/3.9, and pytorch 1.8.0+cu102, 1.9.0+cu102, 1.10.0+cu102, 1.10.1+cu102, 1.11.0+cu113. None of them works.

Is it possible that this problem is not a environment problem? I guess what cause this problem is that YoloV5-6.0/6.1 is not compatible with windows11 or GTX1660ti, because YoloV5-5.0 train.py works well on my computer whatever environment it is. But for YoloV5-6.0/6.1, I tried all environment that possible, all of them can not solve my problem. 

What's more, since that there are many difference between 6.0 and 5.0. Can I train my own datasets on 5.0-train.py and use best.pt to detect on 6.0? What will happen if I do this.

**Comment by Etern213** [comment]
> Thanks for your reply. I also think it is a environment problem at first. But I tried python3.7/3.8/3.9, and pytorch 1.8.0+cu102, 1.9.0+cu102, 1.10.0+cu102, 1.10.1+cu102, 1.11.0+cu113. None of them works.
> 
> Is it possible that this problem is not a environment problem? I guess what cause this problem is that YoloV5-6.0/6.1 is not compatible with windows11 or GTX1660ti, because YoloV5-5.0 train.py works well on my computer whatever environment it is. But for YoloV5-6.0/6.1, I tried all environment that possible, all of them can not solve my problem.
> 
> What's more, since that there are many difference between 6.0 and 5.0. Can I train my own datasets on 5.0-train.py and use best.pt to detect on 6.0? What will happen if I do this.

Thanks for your reply. I also think it is a environment problem at first. But I tried python3.7/3.8/3.9, and pytorch 1.8.0+cu102, 1.9.0+cu102, 1.10.0+cu102, 1.10.1+cu102, 1.11.0+cu113. None of them works.

Is it possible that this problem is not a environment problem? I guess what cause this problem is that YoloV5-6.0/6.1 is not compatible with windows11 or GTX1660ti, because YoloV5-5.0 train.py works well on my computer whatever environment it is. But for YoloV5-6.0/6.1, I tried all environment that possible, all of them can not solve my problem.

What's more, since that there are many difference between 6.0 and 5.0. Can I train my own datasets on 5.0-train.py and use best.pt to detect on 6.0? What will happen if I do this.

**Comment by Etern213** [comment]
> @Etern213 it appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally. If in doubt, create a new virtual [Python 3.9](https://www.python.org/) environment, clone the latest repo ([code changes daily](https://github.com/ultralytics/yolov5/commits/master)), and `pip install` [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) again from scratch.
> 
> 💡 ProTip! Try one of our verified environments below if you are having trouble with your local environment.
> 
> ## Requirements
> [**Python>=3.7.0**](https://www.python.org/) with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) installed including [**PyTorch>=1.7**](https://pytorch.org/get-started/locally/). To get started:
> 
> ```shell
> git clone https://github.com/ultralytics/yolov5  # clone
> cd yolov5
> pip install -r requirements.txt  # install
> ```
> 
> [Models](https://github.com/ultralytics/yolov5/tree/master/models) and [datasets](https://github.com/ultralytics/yolov5/tree/master/data) download automatically from the latest YOLOv5 [release](https://github.com/ultralytics/yolov5/releases) when first requested.
> 
> ## Environments
> YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):
> 
> * **Google Colab and Kaggle** notebooks with free GPU: [![Open In Colab](https://camo.githubusercontent.com/84f0493939e0c4de4e6dbe113251b4bfb5353e57134ffd9fcab6b8714514d4d1/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb) [![Open In Kaggle](https://camo.githubusercontent.com/a08ca511178e691ace596a95d334f73cf4ce06e83a5c4a5169b8bb68cac27bef/68747470733a2f2f6b6167676c652e636f6d2f7374617469632f696d616765732f6f70656e2d696e2d6b6167676c652e737667)](https://www.kaggle.com/models/ultralytics/yolov5)
> * **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
> * **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
> * **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) [![Docker Pulls](https://camo.githubusercontent.com/280faedaf431e4c0c24fdb30ec00a66d627404e5c4c498210d3f014dd58c2c7e/68747470733a2f2f696d672e736869656c64732e696f2f646f636b65722f70756c6c732f756c7472616c79746963732f796f6c6f76353f6c6f676f3d646f636b6572)](https://hub.docker.com/r/ultralytics/yolov5)
> 
> ## Status
> ![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)
> 
> If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), validation ([val.py](https://github.com/ultralytics/yolov5/blob/master/val.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/export.py)) on MacOS, Windows, and Ubuntu every 24 hours and on every commit.

Thanks for your reply. I also think it is a environment problem at first. But I tried python3.7/3.8/3.9, and pytorch 1.8.0+cu102, 1.9.0+cu102, 1.10.0+cu102, 1.10.1+cu102, 1.11.0+cu113. None of them works.

Is it possible that this problem is not a environment problem? I guess what cause this problem is that YoloV5-6.0/6.1 is not compatible with windows11 or GTX1660ti, because YoloV5-5.0 train.py works well on my computer whatever environment it is. But for YoloV5-6.0/6.1, I tried all environment that possible, all of them can not solve my problem.

What's more, since that there are many difference between 6.0 and 5.0. Can I train my own datasets on 5.0-train.py and use best.pt to detect on 6.0? What will happen if I do this.

My English is poor, so sorry about it.

**Comment by glenn-jocher** [comment]
@Etern213 yes older models are forward compatible with newer code.

**Comment by Etern213** [comment]
> @Etern213 yes older models are forward compatible with newer code.

Thank you for your reply.
It means that, I can train my own datasets with yolov5-5.0-train.py, and use it to detect on 6.0-detect.py?
It saves my life, Now I am going to train datasets on 5.0, thank you.

After one day finding reason, I think the reason 6.0 train speed slower than 5.0 is that yolov5-6.0/6.1 is not compatible with windows11 or GTX1660ti, because I reinstall windows and pytorch environment and nothing solve my problem.

**Comment by songtf525** [comment]
I tried training and found that during the training process, the speed in the training phase did not change significantly, but in the validation phase, it was very slow, causing the overall training speed to slow down. I don't know what the reason is, it's like the GPU is not called when verifying.

**Comment by Etern213** [comment]
> I tried training and found that during the training process, the speed in the training phase did not change significantly, but in the validation phase, it was very slow, causing the overall training speed to slow down. I don't know what the reason is, it's like the GPU is not called when verifying.

what is your YoloV5 version, 5.0 or 6.0/6.1?

I only have train speed problem on version 6.0/6.1, when I use yolov5-5.0 to train, all thing run normal. After one day finding reason, I think the reason 6.0 train speed slower than 5.0 is that yolov5-6.0/6.1 is not compatible with windows11 or GTX1660ti.

Do you have similar environment with mine?

**Comment by Etern213** [comment]
@glenn-jocher Sorry to bother you again. Since that my computer can train normally with yolov5-5.0 but have problem with 6.0 and 6.1. And my GPU run on 80W with yolov5-5.0 but only run on 50W with 6.0 and 6.1

So I want to try every version between 5.0 and 6.0, try every change you have made between 5.0 and 6.0 one by one, to find exactly the problem is.

Any ideas about how to find all version between 5.0 and 6.0?

**Comment by glenn-jocher** [comment]
@Etern213 yes, you can see the full changelog between releases in the Changelog section of each release:
https://github.com/ultralytics/yolov5/releases/tag/v6.1

In general there are hundreds of commits that go into a release. I would instead focus on simply using an up to date correct environment and use the latest code.

<img width="1068" alt="Screen Shot 2022-04-24 at 11 47 26 AM" src="https://user-images.githubusercontent.com/26833433/164991703-a7299a67-6d87-4868-a9c0-457ae6928349.png">

**Comment by Etern213** [comment]
> @Etern213 yes, you can see the full changelog between releases in the Changelog section of each release: https://github.com/ultralytics/yolov5/releases/tag/v6.1
> 
> In general there are hundreds of commits that go into a release. I would instead focus on simply using an up to date correct environment and use the latest code.
> 
> <img alt="Screen Shot 2022-04-24 at 11 47 26 AM" width="1068" src="https://user-images.githubusercontent.com/26833433/164991703-a7299a67-6d87-4868-a9c0-457ae6928349.png">

The thing is, its not the environment that cause this problem, I already tried almost all python version(python3.7/3.8/3.9) and almost all pytorch version(pytorch 1.8.0+cu102, 1.9.0+cu102, 1.10.0+cu102, 1.10.1+cu102, 1.11.0+cu113), nothing works. And I can make sure that all package in requirement.txt is installed.

If just use an up-to-date environment can solve my problem, I won't spend so much time on it. Now I can make sure that it is something changes between 5.0 and 6.0 that cause this problem on my computer, but I don't know the exactly changes that cause this problem.

I have no choice but to train on 5.0 and detect on 6.1, I don't want to do this forever. Sad :(  :(  :(

**Comment by glenn-jocher** [comment]
@Etern213 in the **common** environments we use, i.e. Google Colab notebook, Docker Image, there is little performance difference, or perhaps a slight improvement when training v5.0 vs v6.1 models. If you can provide a **reproducible** command in a **common** environment that shows a problem then we can start looking into it. Otherwise there is nothing for us to do.

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by Etern213** [comment]
@glenn-jocher Yeah, I know. This only shown on my own computer, I tried google colab and it works well. So it's not your problem.

Do you remember issue #4839 ? This issue shows that 16XX GPU will encounter a very strange problem during training.  We all know its environment problem, but no one knows exactly why.
It took half a month before somebody find out that this problem is to blame Nvidia. See 11th floor in #4839

And I tried a few days before, 1660ti GPU use cuda > 11(i.e. pytorch1.11.0+cu113) still cause this NAN problem in training like #4839.
So I think maybe the problem I encounter depends on GPU. Google Colab use Tesla GPU like V100, A100 and will not show this problem. In 1660ti the problem shows, some changes between 5.0 and 6.0 cause this. If possible, I want to speed time to tried it one by one

The fact is that 1660ti do not have Tensor core, do you think this maybe one of the reason? If so, why training speed on 5.0 is normal?

**Comment by Etern213** [comment]
@glenn-jocher By reading other issue, I noticed that you said train.py are using mixed precision (AMP) inference, which seems to have problem in certain environments, disable AMP or downgrade CUDA will solve. 

But how to disable mixed precision (AMP) in train.py, val.py and pytorch hub?

**Comment by glenn-jocher** [comment]
@Etern213 just set enabled=False on amp calls:
https://github.com/ultralytics/yolov5/blob/bff6e51bc4894ffc4da8b202718023f80d8bdc44/train.py#L347-L355

**Comment by Etern213** [comment]
@glenn-jocher Thank you very much for your reply. Finally, I found the exact reason of this problem. Just as I guessed, AMP is the reason that cause train speed too slow on yolov5-6.0/6.1.

NVIDIA said 16 GPU(such as 1650, 1660, 1650ti, 1660ti) don't have tensor core, which Mixed precision(AMP) need to use. However, My GPU is 1660ti, so I tried to disable AMP and try again.

The fact is that I change `with amp.autocast(enabled=cuda):` to `with amp.autocast(enabled=False):`, and all problems solved. Here I make a brief summary of all I have tried, hope these can help you find the bug:

My GPU is **NVIDIA GeForce GTX 1660 Ti**, **6144MiB**, with **80W** maximum power. **Batch-size** are set to **8** in these tests. And dataset is **COCO2017**, model is **yolov5m.yaml**. All other arguments are same in these tests.

1) case `with amp.autocast(enabled=cuda):`   **(YoloV5-6.0 and YoloV5-6.1)**
**result:**
GPU average power use: 50W **(too low:rotating_light:)**
train speed: about 3-4 s/it **(too slow:rotating_light:)**
GPU memory use: about 3-4 G **(normal✅)**

2) case `with amp.autocast(enabled=False):`   **(YoloV5-6.0 and YoloV5-6.1)**
**result:**
GPU average power use: 80W **(normal✅)**
train speed: about 1.5-2 it/s **(normal✅)**
GPU memory use: about 5.5 G **(too high:rotating_light:)**

3) case `with amp.autocast(enabled=cuda):`   **(YoloV5-5.0)**
**result:**
GPU average power use: 80W **(normal✅)**
train speed: about 1.8-2.2 it/s **(normal✅)**
GPU memory use: about 3-3.2 G **(normal✅)**

According to these information, training speed in case 2 is almost same as case 3, so it seems that the problem is **YoloV5-6.0/6.1 is not compatible with GPU that has no tensor core.** Just as you said, train speed on YoloV5-6.0/6.1 is normal with Tesla GPU in Google Colab, because Tesla GPU have tensor core, but other GPU may not have.

However, I checked the code in YoloV5-5.0, it set AMP to true, `with amp.autocast(enabled=cuda)`, why YoloV5-5.0 can trained normally on GPU with no tensor core when AMP is set to true, but YoloV5-6.0/6.1 can't? Just like case 2 compared with case 3, YoloV5-5.0 have quicker training speed and lower memory usage than YoloV5-6.0/6.1.

Should I close this issue and raised a new one with 'Bug Report'?

**Comment by ice-tall-cold** [comment]
> @glenn-jocher Thank you very much for your reply. Finally, I found the exact reason of this problem. Just as I guessed, AMP is the reason that cause train speed too slow on yolov5-6.0/6.1.
> 
> NVIDIA said 16 GPU(such as 1650, 1660, 1650ti, 1660ti) don't have tensor core, which Mixed precision(AMP) need to use. However, My GPU is 1660ti, so I tried to disable AMP and try again.
> 
> The fact is that I change `with amp.autocast(enabled=cuda):` to `with amp.autocast(enabled=False):`, and all problems solved. Here I make a brief summary of all I have tried, hope these can help you find the bug:
> 
> My GPU is **NVIDIA GeForce GTX 1660 Ti**, **6144MiB**, with **80W** maximum power. **Batch-size** are set to **8** in these tests. And dataset is **COCO2017**, model is **yolov5m.yaml**. All other arguments are same in these tests.
> 
> 1. case `with amp.autocast(enabled=cuda):`   **(YoloV5-6.0 and YoloV5-6.1)**
>    **result:**
>    GPU average power use: 50W **(too low🚨)**
>    train speed: about 3-4 s/it **(too slow🚨)**
>    GPU memory use: about 3-4 G **(normal✅)**
> 2. case `with amp.autocast(enabled=False):`   **(YoloV5-6.0 and YoloV5-6.1)**
>    **result:**
>    GPU average power use: 80W **(normal✅)**
>    train speed: about 1.5-2 it/s **(normal✅)**
>    GPU memory use: about 5.5 G **(too high🚨)**
> 3. case `with amp.autocast(enabled=cuda):`   **(YoloV5-5.0)**
>    **result:**
>    GPU average power use: 80W **(normal✅)**
>    train speed: about 1.8-2.2 it/s **(normal✅)**
>    GPU memory use: about 3-3.2 G **(normal✅)**
> 
> According to these information, training speed in case 2 is almost same as case 3, so it seems that the problem is **YoloV5-6.0/6.1 is not compatible with GPU that has no tensor core.** Just as you said, train speed on YoloV5-6.0/6.1 is normal with Tesla GPU in Google Colab, because Tesla GPU have tensor core, but other GPU may not have.
> 
> However, I checked the code in YoloV5-5.0, it set AMP to true, `with amp.autocast(enabled=cuda)`, why YoloV5-5.0 can trained normally on GPU with no tensor core when AMP is set to true, but YoloV5-6.0/6.1 can't? Just like case 2 compared with case 3, YoloV5-5.0 have quicker training speed and lower memory usage than YoloV5-6.0/6.1.
> 
> Should I close this issue and raised a new one with 'Bug Report'?

Hi, I'm encountering the same issue as your report. And I'm very impressed by your work. I want to know if you have fixed this on version 6.1 or 6.2. I appreciate it a lot if you could share the following steps.

**Comment by Etern213** [comment]
> 

You can see this issue [#7687](https://github.com/ultralytics/yolov5/issues/7687).
What you mentioned is just my test and guess. I just found the problem is related to Pytorch AMP but didn't solve it.

In comment [#7687](https://github.com/ultralytics/yolov5/issues/7687#issuecomment-1172232925) I show a way to solve this problem, but I don't have time, maybe I'll do it a few month later.

**Comment by ice-tall-cold** [comment]
> 
Thank you for your quick reply. The weird thing to me is that I have the same slow speed when I'm using the v5.0. The GPU utilization is lower than that when I train on COCO128. I will continue working on that. Hope we can keep in touch if one of us solves it first!

**Comment by Etern213** [comment]
@ice-tall-cold 
If you have slow speed using v5.0, maybe it's not the same problem.

You can try this:
1) Try to create a new conda environment
    try some different version of Pytorch(such as 1.9.0, 1.8.0, 1.10.0 etc.)
    try some different version of Cuda(10 series and 11 series)
2) if you use pip to install Pytorch, you can try to install it through conda.

**Comment by ice-tall-cold** [comment]
@Etern213 Thank you for your advice. I will try that!
