### ISSUE TITLE
Yolov5 flutter app problem

### ISSUE THREAD

**Issue by HunarAA** [ultralytics/yolov5#7471]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have followed this tutorial https://medium.com/mlearning-ai/training-yolov5-custom-dataset-with-ease-e4f6272148ad for training and converting the trained model into tflite through using this command "python export.py --weights yolov5n.pt --img 640 --include tflite". The model works well when testing it using my webcam.
I have followed another YouTube tutorial for imbedding the model into flutter app, the app works just fine with the provide model within the video but when I replace it with my model and opening the app. The app closes automatically. I tried more than one tutorial but in all of them the same issue occurs. I think the problem is withing the way that I convert the model into tflite.
Any suggestions for solving my problem?

**Comment by Alqama-Rao** [comment]
Did you find the solution?

**Comment by fsyahfalaq** [comment]
Maybe we can refer this repo. I have implement what he did and it is works
https://github.com/syu-kwsk/flutter_yolov5_app

**Comment by AntoineChauviere** [comment]
Ok thank you. 

Otherwise, I feel that it is no longer possible to use the tflite package... do you have any info on this?

**Comment by fsyahfalaq** [comment]
I assumed what you mean tflite package is tflite by shaqian. If you have checked the repo i gave, he used tflite_flutter by am15h instead tflite by shaqian.. I have checked both package repositories and i think tflite_flutter by am15h is more maintained

**Comment by AntoineChauviere** [comment]
Yes I have tested this, but I can't get it to work.

I have this error:

uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [:camera_android] ./build/camera_android/intermediates/merged_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 16

So I put minSdkVersion = 21.

And after that I get this error:

sdks/flutter/.pub-cache/hosted/pub.dartlang.org/tflite_flutter-0.9.0/android/src/main/java/com/tfliteflutter/tflite_flutter_plugin/TfliteFlutterPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

I don't understand ...

**Comment by AntoineChauviere** [comment]
Hello @fsyahfalaq, I believe the NMS is not made with yolov5 tflite. How did you manage the bouding boxes?

**Comment by AneeqMalik** [comment]
@HunarAA You can directly use your trained pt models in flutter by this package on pub dev https://pub.dev/packages/flutter_pytorch
The repo is maintained and easy to understand.
