### ISSUE TITLE
Why did you use reversed iterate in detect.py?

### ISSUE THREAD

**Issue by YoungjaeDev** [ultralytics/yolov5#7476]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

https://github.com/ultralytics/yolov5/blob/7926afccde1a95a4c8dbeb9d2b8a901d9f220ca7/detect.py#L159-L171

Thank you!

**Comment by glenn-jocher** [comment]
@youngjae-avikus this plots the lowest confidence bounding boxes first, so the highest confidence boxes over-write the earlier boxes on saving/showing image results.

**Comment by youngjae-avikus** [comment]
@glenn-jocher 
If two boxes are plotted overlappingly, is it correct to draw the first (the one with the highest confidence) drawn forward?

**Comment by hi-one-gg** [comment]
> @youngjae-avikus this plots the lowest confidence bounding boxes first, so the highest confidence boxes over-write the earlier boxes on saving/showing image results.

Thanks. You're a genius!☺
