### ISSUE TITLE
Disable printing information when loading models from PyTorch Hub

### ISSUE THREAD

**Issue by Powercube7** [ultralytics/yolov5#7480]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hey! I have been wanting to ask this for a long time: is there any way to suppress the console output when loading a model? I know torch.hub.load has a verbose=False option but it only deletes the message about loading the model from the cache. Thank you in advance for the answer

**Comment by glenn-jocher** [comment]
Set environment variable `YOLOv5_VERBOSE=False`, i.e.:

<img width="632" alt="Screen Shot 2022-04-19 at 3 45 28 PM" src="https://user-images.githubusercontent.com/26833433/164113585-021aca63-6490-46e2-905f-51ecef2806ac.png">

**Comment by Powercube7** [comment]
@glenn-jocher how can I set this when using torch.hub.load? sorry, I'm a little bit confused.
