### ISSUE TITLE
YOLOv3 add four detection layer 

### ISSUE THREAD

**Issue by summeryumyee** [ultralytics/yolov5#7483]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, my idol, I want to add the four detection layer in yolov3.yaml, please check whether this modification is correct and do you have better opinions?  Thank you very much!  
![image](https://user-images.githubusercontent.com/16797879/164045239-e4b7c240-5525-4f52-b7fe-c67baca62c96.png)

**Comment by glenn-jocher** [comment]
@summeryumyee you can find existing YOLOv5 4-output models here. The default models are 3-output models: P3, P4, P5. These models add a P2 (for small objects) or a P6 (for large objects) output to the base YOLOv5l models:

https://github.com/ultralytics/yolov5/blob/master/models/hub/yolov5-p2.yaml
https://github.com/ultralytics/yolov5/blob/master/models/hub/yolov5-p6.yaml
