### ISSUE TITLE
Testing platform

### ISSUE THREAD

**Issue by ddzhangjie** [ultralytics/yolov5#749]
## ❔Question
Is possible to show your GPU testing platform, since I would like to know how can you get 145FPS for yolo5x.

**Comment by glenn-jocher** [comment]
@ddzhangjie we test all of our models on GCP V100 instances with our docker image:
<img width="1017" alt="Screen Shot 2020-08-15 at 9 32 32 AM" src="https://user-images.githubusercontent.com/26833433/90316997-251bbb80-dedb-11ea-8887-6f5df0a1b133.png">

The command to reproduce our speeds is displayed directly in the comments below the table. This command evaluates YOLOv5x over the 5000 COCO val2017 images. We see 5.8 ms inference time per image, and 1.1 ms NMS time per image, 6.9 ms total. 1000 ms / 6.9 ms = 145 FPS.

Anyone can reproduce these results for YOLOv5x, or any other model, by following the same steps

<img width="1183" alt="Screen Shot 2020-08-15 at 9 44 33 AM" src="https://user-images.githubusercontent.com/26833433/90317145-33b6a280-dedc-11ea-993b-6c001f9fb589.png">

**Comment by JiaLim98** [comment]
Hi @glenn-jocher,

How do you show the 6 APs and 6 ARs? I tested my weights but it just stop at speed (see Fig. below).
![image](https://user-images.githubusercontent.com/66768413/92300104-db2e6e80-ef8a-11ea-8672-856d39219fd0.png)

Regards,
JiaLim98

**Comment by glenn-jocher** [comment]
pycocotools runs when coco.yaml is used. It is only intended for COCO data.
