### ISSUE TITLE
Converting .pt or .onnx to .pb and .tflite

### ISSUE THREAD

**Issue by wiky231** [ultralytics/yolov5#7491]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I trained a YOLOv5s on a custom dataset on Google Colab. Now I'm trying to convert the trained weights from .pt and .onnx format to .pb and .tflite format as I want to make an Android app for my model. Does anyone know the solution? Thanks

**Comment by glenn-jocher** [comment]
@axlecky see TFLite, ONNX, CoreML, TensorRT Export tutorial.


## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️  RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Roboflow for Datasets, Labeling, and Active Learning](https://docs.ultralytics.com/yolov5/tutorials/roboflow_datasets_integration)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TFLite, ONNX, CoreML, TensorRT Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [Architecture Summary](https://docs.ultralytics.com/yolov5/tutorials/architecture_description)&nbsp; ⭐ NEW

Good luck 🍀 and let us know if you have any other questions!

**Comment by Shashi42** [comment]
Hi @axlecky , I'm trying to do the exact same thing that you are doing. I have already trained a **yolov5m** model. I wish to see realtime detection in an Android app.

I'm currently using this repo for realtime object detection. [App](https://github.com/lp6m/yolov5s_android). Maybe if by chance you too are using this repo for reference, we could help each other

I have already followed the [export tutorial](https://docs.ultralytics.com/yolov5/tutorials/model_export) to generate .tflite weights from .pt weights but I'm facing an issue when loading the .tflite model.

**Comment by wiky231** [comment]
Hi @Shashi42, I managed to build a simple app using this repo: https://github.com/zldrobit/tfjs-yolov5-example.git.
However, I'm trying to add more functions such as inference for gallery images etc. I will also try the repo that you mentioned in the next few days. 
Do you mind leaving your email/discord for easier communication?

**Comment by Shashi42** [comment]
Sure. This is my discord username `Shashi#2907`.

**Comment by glenn-jocher** [comment]
Hey @Shashi42, glad to hear you've made progress with the Android app! When it comes to adding more functions like gallery image inference, the YOLOv5 repo at https://github.com/ultralytics/yolov5 has extensive documentation on model export and integration for different platforms, including Android.

For loading the .tflite model, could you provide more details on the specific issue you're encountering? This can help us troubleshoot the problem and find a solution.

Thanks and keep up the great work!
