### ISSUE TITLE
Check if the object is same in different frame

### ISSUE THREAD

**Issue by brianw0924** [ultralytics/yolov5#7493]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, since yolov5 is not a sequence model; is there anyway to compare if the object is same in different frame? ( maybe within x sec)

I want ot detect some objects and save it, and I don't want to save the same object; but the inference is frame-level.

I only come up with 2 solution:

0. inference every X frame
1. cluster the embedding vector before output

Is there any better way to do this?

**Comment by glenn-jocher** [comment]
@brianw0924 👋 Hello! Thanks for asking about object **tracking** in computer vision. YOLOv5 🚀 is an object **detector** that detect, localizes and classifies objects in a single image. It does not connect objects across multiple images, for this you need a tracking solution. A few possible tracking solutions are:

- **Extended Kalman Filter (EKF)**: https://en.wikipedia.org/wiki/Kalman_filter
- **KLT tracker**: https://en.wikipedia.org/wiki/Kanade%E2%80%93Lucas%E2%80%93Tomasi_feature_tracker
- **YOLOv5 DeepSort tracker**: https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch

Good luck 🍀 and let us know if you have any other questions!

**Comment by brianw0924** [comment]
Thank you, it helps a lot!

**Comment by glenn-jocher** [comment]
@brianw0924 you're welcome! I'm glad I could help. If you have any more questions or need further assistance, feel free to ask. Good luck with your project! 🚀
