### ISSUE TITLE
How to obtain the center coordinates of detected object?

### ISSUE THREAD

**Issue by joneswilliam1** [ultralytics/yolov5#7497]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello everyone,

I would really like to obtain and draw the center coordinates of the detected object on the screen during inference using cv2 like this: 

```cv2.circle(img, (xc, yc), 4, color, -1)```

Looking at the ```plot.py``` file, I see the ```box_label``` function where I believe bb is being drawn, can anyone assist with the center coordinates drawing? Thanks a bunch!

### Additional

Have tried this but was not successful:

```
    def box_label(self, box, label='', color=(128, 128, 128), txt_color=(255, 255, 255)):
        # Add one xyxy box to image with label
        if self.pil or not is_ascii(label):
            self.draw.rectangle(box, width=self.lw, outline=color)  # box
            if label:
                w, h = self.font.getsize(label)  # text width, height
                outside = box[1] - h >= 0  # label fits outside box
                self.draw.rectangle((box[0],
                                     box[1] - h if outside else box[1],
                                     box[0] + w + 1,
                                     box[1] + 1 if outside else box[1] + h + 1), fill=color)
                # self.draw.text((box[0], box[1]), label, fill=txt_color, font=self.font, anchor='ls')  # for PIL>8.0
                self.draw.text((box[0], box[1] - h if outside else box[1]), label, fill=txt_color, font=self.font)
                cv2.circle(self.im, (box[2] + box[0] / 2), (box[3] + box[1] / 2), 4, color, -1)
```

_No response_

**Comment by PajariPy** [comment]
Assuming that `box` contains `[xmin, ymin, xmax, ymax]` you can use the following code to draw a circle:
```
xc = box[0] + (box[2] - box[0]) / 2
yc = box[1] + (box[3] - box[1]) / 2

xc = int(xc)
yc = int(yc)

cv2.circle(self.im, (xc, yc), 4, color, -1)
```

**Comment by joneswilliam1** [comment]
Hi @PajariPy,

Thank you very much, I just tried it out and it works!  🙏
