### ISSUE TITLE
What is the more correct way to train the model with the following data?

### ISSUE THREAD

**Issue by RoyCopter** [ultralytics/yolov5#7498]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

So I got the VisDrone (Videos) dataset with some ignored regions labels. (when the objects are too small or it was too hard to label that parts)

For Example:
![image](https://user-images.githubusercontent.com/98327877/164243181-98bb0542-3029-4abb-95d5-b0f8d484d29e.png)

But I can process that labeling and remove the ignore parts like that: (Same as you did in your VisDrone config)
![image](https://user-images.githubusercontent.com/98327877/164241828-caa4959e-4844-4e56-90ae-ffc36bea3df5.png)

In practice, when I do inference, I do want the model to detect objects (even small ones) in that ignore regions (like people,cars and so on).

How it effect the model when there are people in that regions, but there are no labels as you did?

Labeling the ignore-regions is not an option right now. 

Thanks!

**Comment by glenn-jocher** [comment]
@RoyCopter your model simply learns your labels. If you do not label objects they will not be detected in deployment.
<img width="2029" alt="dataset" src="https://user-images.githubusercontent.com/26833433/164256783-8c514383-8252-41d1-8c0b-91a2ad81ba02.png">
