### ISSUE TITLE
Problem exporting to onnx with the latest update

### ISSUE THREAD

**Issue by batrlatom** [ultralytics/yolov5#750]
Before submitting a bug report, please be aware that your issue **must be reproducible** with all of the following, otherwise it is non-actionable, and we can not help you:
 - **Current repo**: run `git fetch && git status -uno` to check and `git pull` to update repo
 - **Common dataset**: coco.yaml or coco128.yaml
 - **Common environment**: Colab, Google Cloud, or Docker image. See https://github.com/ultralytics/yolov5#environments
 
If this is a custom dataset/training question you **must include** your `train*.jpg`, `test*.jpg` and `results.png` figures, or we can not help you. You can generate these with `utils.plot_results()`.

## 🐛 Bug
Onnx export do not work now

## To Reproduce (REQUIRED)
run export.py in yolov5  docker 

Input:
```
python models/export.py
```

Output:
```
ONNX export failure: Exporting the operator hardswish to ONNX opset version 12 is not supported. Please open a bug to request ONNX export support for the missing operator.

```

## Expected behavior
Correctly exported onnx file

## Environment
Official docker

**Comment by glenn-jocher** [comment]
@batrlatom yes you are correct. Export currently requires `torch==1.5.1` to function properly.

**Comment by batrlatom** [comment]
It looks like I was able to export it now. 

`Starting TorchScript export with torch 1.6.0...
...
ONNX export success, saved as weights/yolov5s.onnx
`

Thanks

**Comment by ShreshthSaxena** [comment]
@batrlatom how did you get it to work?

**Comment by batrlatom** [comment]
@ShreshthSaxena it should be already resolved. See last commits
