### ISSUE TITLE
 I want to know the meaning of this data

### ISSUE THREAD

**Issue by ONNONS** [ultralytics/yolov5#7500]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to know the meaning of this data

![image](https://user-images.githubusercontent.com/65228677/164248875-cb869105-e32e-4db2-b575-48c8266ea3b4.png)

### Additional

g)

**Comment by glenn-jocher** [comment]
training label plots
