### ISSUE TITLE
yolov5, raspberry pi and intel computer stick 2

### ISSUE THREAD

**Issue by jafar0892** [ultralytics/yolov5#7509]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, i have two quetions:
1. how to train a yolov5 model with large datasets? i have tried google colab but i getting problem with GPU and i tried to buy google colab pro but i can't becuase it is available only for a few countries. 
2. how to use best.pt in raspberry pi to detect, track and count object in real time with intel computer sticks 2 ? i will appricate to get some help!!

**Comment by glenn-jocher** [comment]
@jafar0892 NCS requires OpenVINO models. After your model is trained you can export to OpenVINO with:
```
python export.py --weights path/to/best.pt --include openvino
```

**Comment by jafar0892** [comment]
@glenn-jocher Thanks!

**Comment by AykeeSalazar** [comment]
> @jafar0892 NCS requires OpenVINO models. After your model is trained you can export to OpenVINO with:
> 
> ```
> python export.py --weights path/to/best.pt --include openvino
> ```

how can u load the model and use openvino in raspberry pi?

**Comment by jafar0892** [comment]
@AykeeSalazar i have not done it yet.
