### ISSUE TITLE
Can the pre-training model of yolov5 be replaced by other models?

### ISSUE THREAD

**Issue by carptainhao** [ultralytics/yolov5#7512]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, if I have already trained a model with other networks. At this time, I want to use this model as the pre-training model of yolov5, because the structure is different, will yolov5 learn the knowledge of the pre-training model during the training process?

**Comment by glenn-jocher** [comment]
@carptainhao you can pass any YOLOv5 model as a pretrained --weights with a different --cfg yaml. All layers with matching shapes and names will be transferred to the new model being trained.

**Comment by carptainhao** [comment]
@glenn-jocher thanks for your reply, I know how to do.

**Comment by glenn-jocher** [comment]
You're welcome, @carptainhao. If you have any other questions or need further assistance, feel free to ask. Good luck with your project!
