### ISSUE TITLE
onnx outputs

### ISSUE THREAD

**Issue by Naughty-Galileo** [ultralytics/yolov5#7513]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Thank you for your excellent work！When I export my model, the onnx model has four outputs(output, 339, 392 , 445). **I just want the 'output' as the outpus of the model**, what should I do? 
![image](https://user-images.githubusercontent.com/55594771/164376476-6ec2d2d8-d3ff-4d35-b877-9de775fc54b4.png)

**Comment by glenn-jocher** [comment]
@Naughty-Galileo update your code and re-export.

**Comment by Naughty-Galileo** [comment]
> @Naughty-Galileo update your code and re-export.

Thanks, and do I need to retrain the model？

**Comment by glenn-jocher** [comment]
@Naughty-Galileo no
