### ISSUE TITLE
Training on Coco and SKU110K 

### ISSUE THREAD

**Issue by MartinPedersenpp** [ultralytics/yolov5#7514]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello

I am trying to get YoloV5 to act as a generalized object detector.

So I've taken the Coco2017 and SKU110K datasets and converted them to Yolo format with all the Coco annotations being changed to object instead of their respective classes.
I am training on VM GPU Instances with 16GB VRam using all 8 cores as workers, batch size 16 and img size 640 using the yolov5s.pt as base weights
I am currently at epoch 14 and it is detecting half of the objects on my test image.
Edit: My MaP50 is improving by 0.01ish each epoch
I looked at the training section in the readme and it states that a day was used for training yolov5s on a V100
I am just wondering if I have missed something in my dataset.yml file or something since it has taken a day just to get to epoch 14.
How many epochs was the coco models trained for?

Any input on how to achieve a generalized object detector effect or changing settings for my training would be greatly appreciated.

### Additional
I have seen these values used in the yolov5.yaml datafiles, do these have any relevance to training on custom datasets?

```depth_multiple: 0.33   model depth multiple
width_multiple: 0.50   layer channel multiple
anchors:
  - [10,13, 16,30, 33,23]   P3/8
  - [30,61, 62,45, 59,119]   P4/16
  - [116,90, 156,198, 373,326]   P5/32

YOLOv5 v6.0 backbone
backbone:
  [from, number, module, args]
  [[-1, 1, Conv, [64, 6, 2, 2]],   0-P1/2
   [-1, 1, Conv, [128, 3, 2]],   1-P2/4
   [-1, 3, C3, [128]],
   [-1, 1, Conv, [256, 3, 2]],   3-P3/8
   [-1, 6, C3, [256]],
   [-1, 1, Conv, [512, 3, 2]],   5-P4/16
   [-1, 9, C3, [512]],
   [-1, 1, Conv, [1024, 3, 2]],   7-P5/32
   [-1, 3, C3, [1024]],
   [-1, 1, SPPF, [1024, 5]],   9
  ]

YOLOv5 v6.0 head
head:
  [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],   cat backbone P4
   [-1, 3, C3, [512, False]],   13

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  cat backbone P3
   [-1, 3, C3, [256, False]],   17 (P3/8-small)

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 14], 1, Concat, [1]],   cat head P4
   [-1, 3, C3, [512, False]],   20 (P4/16-medium)

   [-1, 1, Conv, [512, 3, 2]],
   [[-1, 10], 1, Concat, [1]],   cat head P5
   [-1, 3, C3, [1024, False]],   23 (P5/32-large)

   [[17, 20, 23], 1, Detect, [nc, anchors]],   Detect(P3, P4, P5)
  ]```

_No response_

**Comment by glenn-jocher** [comment]
@MartinPedersenpp 👋 Hello! Thanks for asking about **training speed issues**. YOLOv5 🚀 can be trained on CPU (slowest), [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) (fastest). If you would like to increase your training speed some options are:

- Increase `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s
- Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) DDP at larger `--batch-size`
- Train with a cached dataset: `python train.py --cache`
- Train on faster GPUs, i.e.: P100 -> V100 -> A100
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

Good luck 🍀 and let us know if you have any other questions!

**Comment by MartinPedersenpp** [comment]
Hello @glenn-jocher 
As mentioned I am already using batch size 16 which uses 90-95% of my 16GB GPU
The image size is 640 which was also used for training the official models on coco?
I am already training on YOLOv5s
I don't have multi GPUs available in my GPU backend.
As far as I've read, to cache the coco dataset one would need about 128GBs of ram

So there is not much I Can do.
How many epochs did you train the original models on coco?
I get that training on 128.000 images is going to take a while, but I would just like to know where the finish line is 😊

**Comment by glenn-jocher** [comment]
@MartinPedersenpp all official models are trained to 300 epochs from scratch. Commands to reproduce are in README training section.

**Comment by MartinPedersenpp** [comment]
Alright, 300 epochs, thanks, I guess I'll just have to wait. 
Thanks!
