### ISSUE TITLE
Some questions abount ConfusionMatrix

### ISSUE THREAD

**Issue by beauty-snowman** [ultralytics/yolov5#7516]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hi, i have know that the p and r is based on the max F1 score on console. but i want to get the same p and r with console in  ConfusionMatrix. how can i get the conf. thanks

**Comment by glenn-jocher** [comment]
@beauty-snowman see F1 curve, i.e.:
![image](https://user-images.githubusercontent.com/26833433/164487899-72d21006-1d3a-43b0-9d88-535f483cf298.png)

**Comment by beauty-snowman** [comment]
> @beauty-snowman see F1 curve, i.e.: ![image](https://user-images.githubusercontent.com/26833433/164487899-72d21006-1d3a-43b0-9d88-535f483cf298.png)

oh~~! thank you, i have changed the conf, but the p and r in confusion matrix is still different from console. Should I change iou_thres? Where can i get. Default is 0.45.

**Comment by glenn-jocher** [comment]
@beauty-snowman what's happening here is that the confusion matrix is created using typical deployment settings for conf and iou_thres, while the console metrics are optimized for mAP and use different conf and iou. 

The confusion matrix settings are static and here, they are not a function of val.py arguments:
https://github.com/ultralytics/yolov5/blob/404b4fefbe9db5d6c748f518880bdf7bff5cdaf7/utils/metrics.py#L117-L119
