### ISSUE TITLE
  Hope to improve map in my dataset

### ISSUE THREAD

**Issue by wenjunx** [ultralytics/yolov5#7517]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have read this article [https://github.com/ultralytics/yolov5/wiki/Tips-for-Best-Training-Results].Follow the instructions inside.
This is train result.
![results](https://user-images.githubusercontent.com/83592255/164433578-72886868-8379-44e1-b714-9ef1db094601.png)
confusion_matrix
![confusion_matrix](https://user-images.githubusercontent.com/83592255/164433754-48aa2fd0-204e-4309-bee4-5cfbf113aa13.png)
F1
![F1_curve](https://user-images.githubusercontent.com/83592255/164433784-c3df7f65-4df2-464d-aa72-683573e65b2b.png)
labels
![labels](https://user-images.githubusercontent.com/83592255/164433816-51a15ef7-dff1-41f3-9f90-3bf7e9b7e082.jpg)
labels_correlogram
![labels_correlogram](https://user-images.githubusercontent.com/83592255/164433876-6dbf67ae-a19f-4122-91ed-6879f5cf767a.jpg)
P_curve
![P_curve](https://user-images.githubusercontent.com/83592255/164433955-992a3dae-e190-417a-8fbf-68eb54701901.png)
R_curve
![R_curve](https://user-images.githubusercontent.com/83592255/164433970-4bc6c5e0-94e8-42c0-8701-5972bdf0b48c.png)
PR_curve
![PR_curve](https://user-images.githubusercontent.com/83592255/164434006-472cd0ed-b6ac-4a34-98d6-dc50d9523d20.png)

[results.txt](https://github.com/ultralytics/yolov5/files/8530064/results.txt)
opt
![2022-04-21 18-29-46 的屏幕截图](https://user-images.githubusercontent.com/83592255/164439688-ca5249f7-8495-479a-b473-c236d1f07209.png)
hyp. I don't need to fliplr because my dataset has been fliplr
![2022-04-21 18-31-37 的屏幕截图](https://user-images.githubusercontent.com/83592255/164439917-76b8e7de-79ab-496a-8c20-03f33c07cbdd.png)
I use hyp.finetune.yaml, because if  I use hyp.scratch.yaml ，the effect will be worse

test_batch0_labels
![test_batch0_labels](https://user-images.githubusercontent.com/83592255/164434446-b5c31438-5618-417d-a094-b916a1565aa9.jpg)
test_batch0_pred
![test_batch0_pred](https://user-images.githubusercontent.com/83592255/164434465-55ee93dd-98f3-411a-8d53-bed275a29973.jpg)
test_batch1_labels
![test_batch1_labels](https://user-images.githubusercontent.com/83592255/164434487-734b1508-74bf-4f51-9ea7-507b02e498f8.jpg)
test_batch1_pred
![test_batch1_pred](https://user-images.githubusercontent.com/83592255/164434528-bba06eb0-89ef-4339-9c7c-39a50ece39c7.jpg)
test_batch2_labels
![test_batch2_labels](https://user-images.githubusercontent.com/83592255/164434555-88deffa3-6855-4c21-bcd2-25f9be9abdd4.jpg)
test_batch2_pred
![test_batch2_pred](https://user-images.githubusercontent.com/83592255/164434578-a4e035d7-54fc-4ac5-8617-e921848a17c2.jpg)
train_batch0----train_batch2
![train_batch0](https://user-images.githubusercontent.com/83592255/164434657-80708e8a-6833-452b-8d5c-180e61faa9f7.jpg)
![train_batch1](https://user-images.githubusercontent.com/83592255/164434685-ddad2f33-68f2-49d9-b817-01029bfb35be.jpg)
![train_batch2](https://user-images.githubusercontent.com/83592255/164434703-5117e6c3-6bd5-4767-9e1d-96dbf4840d92.jpg)

I found that after 50 epoch, it was a little over fitting, so I stopped training.

Here are some pictures after inference.
![01901](https://user-images.githubusercontent.com/83592255/164436139-f6b21b46-56b5-45e1-a85a-b0a192c5dc64.jpg)
![01902](https://user-images.githubusercontent.com/83592255/164436439-c43ce370-85f4-4c90-9b97-8d8586baf8c1.jpg)
![01944](https://user-images.githubusercontent.com/83592255/164436657-61e5f8bc-e528-4545-99df-2198121befe6.jpg)
![01915](https://user-images.githubusercontent.com/83592255/164436913-fe48026e-cf19-4aa7-8add-f7ea6c621721.jpg)
![01930](https://user-images.githubusercontent.com/83592255/164437013-1eb166a2-00d7-4d1f-b43a-e97789f643fb.jpg)

Please tell me how to do it. Thank you very much！！！

**Comment by wenjunx** [comment]
@jkocherhans

**Comment by wenjunx** [comment]
@[Glenn Jocher](https://github.com/glenn-jocher)  Could you possibly help me? thank you!!!

**Comment by glenn-jocher** [comment]
@wenjunx Ultralytics doesn't provide custom training feedback. You can see all of our best practice recommendations here: https://docs.ultralytics.com/guides/model-training-tips/%5D.Follow
