### ISSUE TITLE
Out-of-distribution?

### ISSUE THREAD

**Issue by recycie** [ultralytics/yolov5#7519]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,
The yolov5 model working for Out-of-distribution?
I try code objectdetect ood with odin code it not working, return inputs "None type",

Thanks.

**Comment by MartinPedersenpp** [comment]
I'm no expert and might not completely understand your question.
Do you mean objects outside of the training dataset?

**Comment by recycie** [comment]
> I'm no expert and might not completely understand your question. Do you mean objects outside of the training dataset?

Yes.

**Comment by MartinPedersenpp** [comment]
I am currently working with torch to train a generalized 1 class detector(find any object, doesn't matter what it is).
I am training on the coco and sku110k datasets and after 14 epochs of training I was able to detect all objects in my testing image(small cropped image with eight objects), these are all top view and "local" products, so I am fairly sure nothing like it has been in the training datasets.
Again, I am not sure if this answers your question, but yes you can train YoloV5 to detect objects, even though it is not in your dataset images. This is done by creating a class and training it with various images containing a mix of objects labeled as your OOD class

**Comment by recycie** [comment]
> I am currently working with torch to train a generalized 1 class detector(find any object, doesn't matter what it is). I am training on the coco and sku110k datasets and after 14 epochs of training I was able to detect all objects in my testing image(small cropped image with eight objects), these are all top view and "local" products, so I am fairly sure nothing like it has been in the training datasets. Again, I am not sure if this answers your question, but yes you can train YoloV5 to detect objects, even though it is not in your dataset images. This is done by creating a class and training it with various images containing a mix of objects labeled as your OOD class

Thanks for the answer.
But i mean like this
![image](https://user-images.githubusercontent.com/46786536/164475389-8a1b959a-031b-40b9-8325-373d74e5c186.png)

**Comment by glenn-jocher** [comment]
@recycie 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, etc.
# model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')  # custom trained model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!
