### ISSUE TITLE
Why do you use 3 anchor box in yolov5

### ISSUE THREAD

**Issue by minjong92** [ultralytics/yolov5#7523]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

if i use 9 anchor box in yolov5.  I expected performance improvements
Rather, the performance has been reduced.

**Comment by glenn-jocher** [comment]
Sure

**Comment by minjong92** [comment]
> Sure

Why?????

**Comment by glenn-jocher** [comment]
@minjong92 in YOLOv5, the default three anchor boxes were empirically determined for good all-around performance on a wide variety of datasets. Using nine anchor boxes may not lead to improved performance as the network is optimized for three. If you'd like to customize anchor box sizes, you can investigate the `--augment` flag and review the documentation at https://docs.ultralytics.com/yolov5/ for more information.
