### ISSUE TITLE
Can yolov5 use multi-images inference?

### ISSUE THREAD

**Issue by Etern213** [ultralytics/yolov5#7526]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, thanks for your work on yolov5 project. @g

Now, I encountered a situation that I should detect many small item on difference images

For example, I have four picture with car inside. I want to detect license on these images, each images has one car and each car has one license. How can I mosaic them and inference them with one inference rather than four.(just like mosaic images in train)

I think do one inference is far quicker than inference them one by one.

Can yolov5's detect.py do it? If can, how to modify detect.py?

My English is poor, so sorry about it.

**Comment by glenn-jocher** [comment]
@Etern213 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. You can also batch images togethor easily, i.e. `batch = [im1, im2, im3, ...]` and then `results = model(batch)`

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, etc.
# model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')  # custom trained model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by Etern213** [comment]
> @Etern213 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. You can also batch images togethor easily, i.e. `batch = [im1, im2, im3, ...]`
> 
> ### Simple Inference Example
> This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.
> 
> ```python
> import torch
> 
> # Model
> model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, etc.
> # model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')  # custom trained model
> 
> # Images
> im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list
> 
> # Inference
> results = model(im)
> 
> # Results
> results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
> 
> results.xyxy[0]  # im predictions (tensor)
> results.pandas().xyxy[0]  # im predictions (pandas)
> #      xmin    ymin    xmax   ymax  confidence  class    name
> # 0  749.50   43.50  1148.0  704.5    0.874023      0  person
> # 2  114.75  195.75  1095.0  708.0    0.624512      0  person
> # 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
> ```
> 
> <img alt="" width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">
> 
> See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.
> 
> Good luck 🍀 and let us know if you have any other questions!

Thank you very much for your reply, it works.
I have another problem about 'result.print()', it can show me inference time, but how to save it(inference time) to a variable?
`Speed: 34.9ms pre-process, 12.0ms inference, 6.0ms NMS per image at shape (1, 3, 384, 640)`

**Comment by Etern213** [comment]
> > @Etern213 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. You can also batch images togethor easily, i.e. `batch = [im1, im2, im3, ...]`
> > ### Simple Inference Example
> > This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.
> > ```python
> > import torch
> > 
> > # Model
> > model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, etc.
> > # model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')  # custom trained model
> > 
> > # Images
> > im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list
> > 
> > # Inference
> > results = model(im)
> > 
> > # Results
> > results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
> > 
> > results.xyxy[0]  # im predictions (tensor)
> > results.pandas().xyxy[0]  # im predictions (pandas)
> > #      xmin    ymin    xmax   ymax  confidence  class    name
> > # 0  749.50   43.50  1148.0  704.5    0.874023      0  person
> > # 2  114.75  195.75  1095.0  708.0    0.624512      0  person
> > # 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="" width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">
> > See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.
> > Good luck 🍀 and let us know if you have any other questions!
> 
> Thank you very much for your reply, it works. I have another problem about 'result.print()', it can show me inference time, but how to save it(inference time) to a variable? `Speed: 34.9ms pre-process, 12.0ms inference, 6.0ms NMS per image at shape (1, 3, 384, 640)`

I already find a way to get inference time, the problem solved, thank you very much.

But, emmmm, why detect.py inference image one by one, why don't use 'batch detect'?

**Comment by glenn-jocher** [comment]
@Etern213 detect.py uses batched inference only under certain circumstances right now, i.e. streaming sources.

**Comment by Etern213** [comment]
> @Etern213 detect.py uses batched inference only under certain circumstances right now, i.e. streaming sources.

Okey, understand.
Now, I am learning knowadge about deep learning, and hope I can contribute to yolov5 project in the future!
