### ISSUE TITLE
Test Bounding box in Custom Data is shifted!

### ISSUE THREAD

**Issue by chokyungjin** [ultralytics/yolov5#753]
Hi. I'm sooo glad to meet your repo! But I have a issue,I trained with My custom data. 
And now I'm trying to test it and I found a problem.
My Test Result All Bounding Boxes are shifted! I don't know why this is happening!

I look forward to a answer. Thank you!

**Comment by Ownmarc** [comment]
Your labels are probably wrong.. Start by checking the images created in runs/expN/ to confirm your labels are correct. If they are all shifted there too, it means that your ground truth labels are all shifted or you have a problem in you label conversion script.

**Comment by chokyungjin** [comment]
Thank you!! One more Question..
How Can i Check my annotation data in my Image? 
I don't know how to check the annotations after adjusting them to the 0-1 scale coordinates.

**Comment by Ownmarc** [comment]
After starting a training, look in the folder that gets created "runs/exp1/ " there will be 4 images that show the batches with their labels on it. Make sure they are correct

**Comment by chokyungjin** [comment]
Thank you again!

**Comment by glenn-jocher** [comment]
Yes, like @Ownmarc said you want to check your train and test jpgs here for proper labels. If the boxes are incorrect here it means your labels are not correct.
<img width="393" alt="Screen Shot 2020-08-16 at 11 34 03 PM" src="https://user-images.githubusercontent.com/26833433/90364278-fe639f00-e018-11ea-8b3b-babb1c8b7485.png">
