### ISSUE TITLE
Compute AP base on two lists of labels

### ISSUE THREAD

**Issue by trangtnt0311** [ultralytics/yolov5#7530]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello! I have two lists of labels, `labels` and `predictions` as txt files.
For example:
`labels/1.txt - 1 0.69 0.44 0.15 0.25`
`predictions/1.txt - 1 0.68 0.42 0.15 0.25`
... and so on
How do I compute AP base on these files? Thanks

**Comment by glenn-jocher** [comment]
@gggaugau val.py computes metrics on labelled data:

```
python val.py --data coco128.yaml --weights yolov5s.pt
```
