### ISSUE TITLE
Getting an error: Dataset not found

### ISSUE THREAD

**Issue by heigex** [ultralytics/yolov5#7532]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm building an object detection model to detect if a person is wearing a helmet. I have arranged the data in YOLOv5 format: [data link](https://drive.google.com/file/d/108TCyzpF8YsrAEu9lrcqbzvl68ekRHXE/view?usp=sharing)

I have added the data in the `helm` directory next to the `yolo`.
<img width="219" alt="Screenshot 2022-04-22 at 4 13 25 PM" src="https://user-images.githubusercontent.com/50593567/164699863-86d27bb7-7650-463a-97d2-cbe64c44cc4e.png">

When I'm running the `python train.py --img 640 --batch 16 --epochs 1 --data /content/helm/helm.yaml --weights yolov5s.pt --cache`. It's resulting in below error:
```
Dataset not found ⚠️, missing paths ['/content/yolov5/images/test/images']
Traceback (most recent call last):
  File "train.py", line 669, in <module>
    main(opt)
  File "train.py", line 564, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 107, in train
    data_dict = data_dict or check_dataset(data)  # check if None
  File "/content/yolov5/utils/general.py", line 491, in check_dataset
    raise Exception(emojis('Dataset not found ❌'))
Exception: Dataset not found ❌
```
The data is present in the folder, but still, it's giving this error.

**Comment by Etern213** [comment]
Check your path in file '/content/helm/helm.yaml'

train.py only set the path to the yaml file, you should set the path to the datasets in .yaml files

**Comment by heigex** [comment]
@Etern213, It's correct. I have set it right. Here is the screenshot of the `helm.yaml` file.

<img width="281" alt="Screenshot 2022-04-22 at 8 30 41 PM" src="https://user-images.githubusercontent.com/50593567/164741004-4060b9af-87c3-4c53-841a-832364492b1b.png">

**Comment by Etern213** [comment]
```
Dataset not found ⚠️, missing paths ['/content/yolov5/images/test/images']
Traceback (most recent call last):
  File "train.py", line 669, in <module>
    main(opt)
  File "train.py", line 564, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 107, in train
    data_dict = data_dict or check_dataset(data)  # check if None
  File "/content/yolov5/utils/general.py", line 491, in check_dataset
    raise Exception(emojis('Dataset not found ❌'))
Exception: Dataset not found ❌
```
Check the first line of your error code, the path of the dataset is '/content/yolov5/images/test/images'. Obviously it is not the correct path.
I don't use google colab to train datasets, so I don't know how to modify 'helm.yaml' either.

I think doing like this might help:
1) move folder 'helm' to folder 'yolov5' like 'yolov5/helm'
2) change the path in 'helm.yaml' like below:
```
train: helm/images/train/images
val: helm/images/test/images
```
3) And don't forgot to change your running command, change
`--data /content/helm/helm.yaml`
to
`--data /content/yolov5/helm/helm.yaml`

**Comment by heigex** [comment]
Nice catch. I didn't realize this. Thanks @Etern213

**Comment by KetakiSarode** [comment]
Hello, I experienced this same problem, but i have done all the steps correctly i think....
This is my yaml file 
train:  ../content/yolov5/drugs/train/
val:  ../content/yolov5/drugs/val/ 


nc: 6

names: ['C6', 'C5', 'G4', 'H3', 'F2', 'S1']

nd my folders look like this 
![Screenshot (321)](https://github.com/ultralytics/yolov5/assets/101462176/88a6a114-75a2-4882-8e8c-43ad1754c857)

I still get an error saying 
Dataset not found ⚠️, missing paths ['/content/yolov5/content/yolov5/drugs/val']

**Comment by glenn-jocher** [comment]
@KetakiSarode hey there! 👋 It looks like you might have a small path configuration issue in your YAML file. Based on the error, it appears the path is doubling up: `'/content/yolov5/content/yolov5/drugs/val'`.

Given your YAML file settings, you might want to adjust your paths to be relative from the location where you're running the `train.py` script. If your script is located in the `/content/yolov5/` directory, the paths in your YAML should not start with `../content/yolov5/`, since this would navigate up and then back down to the same directory, potentially causing the doubling issue.

Try updating your YAML file to:
```yaml
train: drugs/train/
val: drugs/val/
```

Make sure your working directory is `/content/yolov5/` when you run the `train.py` script. This adjustment should help resolve the 'Dataset not found' error by correctly pointing to your dataset paths. 😊

Let us know if this helps or if you have more questions!
