### ISSUE TITLE
Delete cached images on disk

### ISSUE THREAD

**Issue by khoinguyen19k8** [ultralytics/yolov5#7533]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I just started training on my data(~25GB) with this configuration
`python train.py --img 768 --batch 64 --epochs 300 --data scratch_holdout_1.yaml --weights '' --cfg yolov5s.yaml --hyp 'data/hyps/hyp.scratch-med.yaml' --patience 20 --cache disk`
Then here is the size of data that got cached.
`train: Caching images (85.4GB disk): 100%|██████████| 48274/48274 [12:39<00:00, 63.56it/s]`
The training process then got terminated because of not enough disk space. However, my dataset directory is now bigger than it was before (~120 GB). I want to start fresh and delete all cached/augmented images created by Yolov5. Do you know how to do it?

### Additional

Cached files are saved in .npy format, so I just need to delete all .npy files.

**Comment by isspid** [comment]
Can you provide a comment on how you solved this, if you did?

**Comment by khoinguyen19k8** [comment]
When `--cache disk` is set Yolov5 would create a .npy file for each image in the dataset. If there are 10000 images in the dataset then 10000 .npy files will be created. These files in total can take a lot of space and will persist after program termination. I found them in the same folder as my dataset and deleted them by using a command as follow:
`rm images/*.npy`

**Comment by MuShanZihahaha** [comment]
Excuse me, which path is the cache picture in?

**Comment by khoinguyen19k8** [comment]
It is in the same folder of your images. If you have this path `train/images/zebra.png` then the cache file path is `train/images/zebra.npy`. This is the same with validation folder as well.

**Comment by songtf525** [comment]
The disk space occupied by the cache is too large. The 750G space is full (~150G data).  Is there a better way to reduce the cache space?

**Comment by glenn-jocher** [comment]
@songtf525 --cache is an option, if your resources don't allow it don't use it. --cache disk will cache to disk, --cache ram with use your RAM.
