### ISSUE TITLE
Results on training or validation set?

### ISSUE THREAD

**Issue by bryanbocao** [ultralytics/yolov5#7538]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Apologize if it exists but I still haven't found the solution.

In the ```runs/exp*/results.csv``` file, I see
```
epoch | train/box_loss | train/obj_loss | train/cls_loss | metrics/precision | metrics/recall | metrics/mAP_0.5 | metrics/mAP_0.5:0.95 | val/box_loss | val/obj_loss | val/cls_loss | x/lr0 | x/lr1 | x/lr2
```
Also, after training a model, I can see the scores
```
 P          R     mAP@.5 mAP@.5:.95
```

Are these ```metrics/precision | metrics/recall | metrics/mAP_0.5 | metrics/mAP_0.5:0.95```, ``` P R mAP@.5 mAP@.5:.95``` computed on the **training** or **validation** set?

**Comment by glenn-jocher** [comment]
@bryanbo-cao metrics are all computed on validation set.
