### ISSUE TITLE
mAP and AP

### ISSUE THREAD

**Issue by Mounthazeer** [ultralytics/yolov5#7546]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hi,
i want to know if the mAP that we get for only one class is the same as AP
as mAP is the average of the different classes's AP

can someone help me i am new

### Additional
i just wanted to confirm if this is right
so the mAP of a single class would be AP/1 which would give the same result
therefore, is it right to say that the mAP of a class is the AP itself?

**Comment by Etern213** [comment]
I think it is right, mAP = AP for only one class

**Comment by glenn-jocher** [comment]
@Etern213 yes that is correct. AP for each class is displayed after training as well as mAP for all classes (mean AP).

<img width="1258" alt="Screen Shot 2022-04-23 at 9 34 22 AM" src="https://user-images.githubusercontent.com/26833433/164914999-0002acda-7fbd-4d9d-9cfc-5efca4939cec.png">
