### ISSUE TITLE
Yolov5 ONNX model is twice larger than Yolov5 Pytorch model

### ISSUE THREAD

**Issue by mohdsaqibhbi** [ultralytics/yolov5#7547]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have exported custom trained yolov5 pytorch model into onnx and the model size of onnx is increased twice of the yolov5 pytorch model. 
Size of yolov5 pytorch model: 173.1 MB
Size of onnx model (after exporting): 345.2 MB
Is it reasonable or Am I doing something wrong here? Because as per my understanding onnx size should be lesser. Below is the snippet.
![Screenshot from 2022-04-23 13-54-57](https://user-images.githubusercontent.com/25509810/164886824-221f3282-4d0f-4081-8c55-aebca470917e.png)

Also, I have seen the same thing in export guide of yolov5
![Screenshot from 2022-04-23 13-58-46](https://user-images.githubusercontent.com/25509810/164886914-3f98dc5b-e570-476e-85d9-bb05985e9060.png)

**Comment by glenn-jocher** [comment]
@mohdsaqibhbi PyTorch models are saved in FP16 by default. ONNX models export at FP32 by default. If you want an FP16 ONNX model you can export with `--half` flag.
