### ISSUE TITLE
multi gpus not working on test.py

### ISSUE THREAD

**Issue by marsO11O** [ultralytics/yolov5#755]
## ❔Question
I'm using --device  argument on test.py tring to get fps.
from below seem it can got two gpu devices, but it actually still using single gpu on testing.
the speed is same on using single and multi gpus
Speed: 1.4/1.1/2.6 ms inference/NMS/total per 672x672 image at batch-size 32

And here is my instruction :
python test.py --weights yolov5s.pt --data coco.yaml --img 672 --device 0,1

Thank you!
## Additional context
Using CUDA device0 _CudaDeviceProperties(name='GeForce RTX 2080 Ti', total_memory=11016MB)
           device1 _CudaDeviceProperties(name='GeForce RTX 2080 Ti', total_memory=11019MB)

**Comment by NanoCode012** [comment]
Only multi-gpu training is supported. Testing uses one gpu. There was a closed PR #514  on this if you want to check it out

**Comment by marsO11O** [comment]
ok,thanks!

**Comment by marsO11O** [comment]
so..can train.py
