### ISSUE TITLE
question about the image size during the inference

### ISSUE THREAD

**Issue by YoungjaeDev** [ultralytics/yolov5#7554]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello
For the FPS margin, 640x640 letterbox is good, but without padding, I can infer a lot even if I input it in 384x640 form, but isn't there a difference in performance?

Thank you!

**Comment by glenn-jocher** [comment]
@youngjae-avikus yes, generally rectangular inference reduces FLOPs and may lead to faster inference.
