### ISSUE TITLE
_verbose not working

### ISSUE THREAD

**Issue by Powercube7** [ultralytics/yolov5#7556]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

PyTorch Hub

### Bug

Glenn, _verbose is back at it again haunting us
![image](https://user-images.githubusercontent.com/80365192/164975448-23b687d8-ff06-4682-9e04-00106b4834e2.png)

### Environment

- YOLO: v6.1
- Windows 10
- PyTorch 1.8.2 LTS
- Python 3.8.0

### Minimal Reproducible Example

model = torch.hub.load('ultralytics/yolov5', 'yolov5s', _verbose=False)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Powercube7 torch hub uses the same old cache unless you manually request an update, i.e.:

### Force Reload
Setting `force_reload=True` may help by discarding the existing cache and force a fresh download of the latest YOLOv5 version from PyTorch Hub.
```python
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)  # force reload
```

**Comment by Powercube7** [comment]
That worked, thanks

**Comment by glenn-jocher** [comment]
@Powercube7 you're welcome! Happy to hear that it worked for you. If you have any other questions or need further assistance, feel free to ask.
