### ISSUE TITLE
Unknown category identification

### ISSUE THREAD

**Issue by WangRongsheng** [ultralytics/yolov5#7563]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

For the data of known categories, yolov5 can predict it. If I want the model to predict unknown categories, is there a good method?

**Comment by glenn-jocher** [comment]
@WangRongsheng you must label all classes you want the model to predict.

**Comment by WangRongsheng** [comment]
Thank you. I hope that in the future yolov5 I can incorporate the prediction of unknown categories, such as ：[https://github.com/JosephKJ/OWOD](https://github.com/JosephKJ/OWOD)

**Comment by glenn-jocher** [comment]
Thanks for the suggestion, @WangRongsheng! We are continually exploring ways to enhance YOLOv5, and your input is appreciated. We'll discuss this with the team and consider it for future developments.
