### ISSUE TITLE
Anyone manage to get TensorRT YoloV5 to work with batch size > 1?

### ISSUE THREAD

**Issue by timothylimyl** [ultralytics/yolov5#7565]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Command used:

```
python3 export.py --weights yolov5s_640.pt --include engine --batch-size 9 --verbose --device 0
```

Error given during inference:

```
[TensorRT] ERROR: Parameter check failed at: engine.cpp::enqueue::445, condition: batchSize > 0 && batchSize <= mEngine.getMaxBatchSize(). Note: Batch size was: 9, but engine max batch size was: 1

```

**Comment by glenn-jocher** [comment]
@timothylimyl batched TRT export and inference is very easy, i.e. `python export.py --include engine --batch 2`

<img width="969" alt="Screen Shot 2022-04-25 at 12 28 15 PM" src="https://user-images.githubusercontent.com/26833433/165160212-a81bf3c6-2f23-4b23-bc3d-0ba47689c0c1.png">

**Comment by timothylimyl** [comment]
@glenn-jocher  thanks for the prompt reply, what is the different with my command:

```
python3 export.py --weights yolov5s_640.pt --include engine --batch-size 9 --verbose --device 0
```

**Comment by glenn-jocher** [comment]
@timothylimyl seems fine. But remember this TRT model will only ever be able to process inputs of shape (9,3,640,640). Any other input shape will cause errors.

**Comment by timothylimyl** [comment]
@glenn-jocher noted with thanks regarding the input shape.

Since I have you here, I just want to confirm the best method to train and run inference for a (640, 360) image size for yolov5s.  It seems that we cannot fix the height of the image (no custom arguments), if we put `--rect`, I am not too sure what size will it come to be.  Would you recommend to train at (640,640) size and then change the TensorRT input shape to (640,360)?  Currently, I will have to pad the input height from 360 to 640 to fit the square images requirement of YoloV5  but extra resolution increase network memory requirement, will be best for rectangle inference unless square improves performance.

**Comment by glenn-jocher** [comment]
@timothylimyl well to get started just focus on training at --img 640 and then exporting and deploying at --img 640 (square inference). Once that works well you can try to export and deploy at rectangular sizes. 

You don't need to retrain to deploy at any other shape/size.

**Comment by timothylimyl** [comment]
Okay thank you.

**Comment by 315386775** [comment]
@timothylimyl hello，multibatch and fp16half cannot use togeter? 

File "export.py", line 312, in run
    assert not dynamic, '--half not compatible with --dynamic, i.e. use either --half or --dynamic but not both'
AssertionError: --half not compatible with --dynamic, i.e. use either --half or --dynamic but not both

**Comment by glenn-jocher** [comment]
@timothylimyl you're welcome! If you have any more questions, feel free to ask. Good luck with your YOLOv5 project!
