### ISSUE TITLE
Input size of detect layer

### ISSUE THREAD

**Issue by alifarooq93** [ultralytics/yolov5#7574]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,
I wanted to ask that I got the extracted feature vector in yolov5 from detect layer input. I tried to print the size of the vector and it shows
len(x) = 4
which I can assume that the size is depend on the no. of times detect layer being called Is it true?

I also print the size of each index of x and it prints:
x[0] = torch.Size([27, 192, 136, 168])
x[1] = torch.Size([27, 384, 68, 84])
x[2] = torch.Size([27, 576, 34, 42])
x[3] = torch.Size([27, 768, 17, 21])

Now the main question is I don't understand the what are those dimensions represent.
27 is the number of images or features?
192, 384, 576, 768 are the size of layer who called detect layer?
and the last two index values I am not sure.
also how can I differentiate the batches in this output x?

My batch size is 16, 3 epochs and 3 batches.

It would be really great if someone help me out becasue I am new and its confusing for me.

**Comment by glenn-jocher** [comment]
@alifarooq93 like any PyTorch 2d convolution these are BCHW https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html

**Comment by gboeer** [comment]
As I understand it, the batch size of 16 used here doesn't add up to the size 27 of the input vector's first dimension. Indeed, I am also wondering where this comes from.

**Comment by glenn-jocher** [comment]
@Legor you might want to export to ONNX like this and then visualize layer shapes in Netron viewer:
```
python export.py --weights yolov5s.pt --include onnx --simplify
```
<img width="950" alt="Screen Shot 2022-04-27 at 11 13 39 AM" src="https://user-images.githubusercontent.com/26833433/165594559-f7879a9e-2319-493b-86e5-5623dd5c3098.png">
