### ISSUE TITLE
export yolov5 custom trained model to openvino

### ISSUE THREAD

**Issue by arduinitavares** [ultralytics/yolov5#7575]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

My ultimate goal is to use a model that I have trained on custom data in the Openvino framework.

To be more specific, I would also like to have the output similar to when I use the detect.py script.

![](https://i.stack.imgur.com/CDL68.png)

What I am getting (regardless of whether I export to .onnx or .xml and .bin) is a model that produces a tensor with the following shape: **(1, 25200, 7)**.

After some time searching for an answer, I could understand where this shape came from.
- batch_size = 1
-  25200 is equal to 1x3x80x80 + 1x3x40x40 + 1x3x20x20;
- 7 = 2 classes + 4 (x,y,w,h) + 1 (score);

I also found some threads that say that post-processing still needs to be developed after exporting a model to another framework, but I am still getting strange results after performing post-processing.
- [https://github.com/ultralytics/yolov5/issues/5736](url)

Given the context, my questions are:
1. I have noticed that we have some options while exporting the model (--nms, --simplify) but I can't get it right. Does the current version of the “export.py" script export the model with in a way that I can already get result of the inference as mentioned before?
2. If not, how should I proceed? I tried drawing the resulting bounding boxes of the tensor with shape (1, 25200, 7) and got really strange results (negative values, almost all with confidence 0, etc...). 

Some additional information:

- I first exported the best version of the model to the appropriate Openvino format, using the following command: 
- - `python export.py --weights runs/train/yolov5s24/weights/best.pt --include openvino  --simplify`;

Thanks in advance.

**Comment by glenn-jocher** [comment]
@arduinitavares 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, etc.
# model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')  # custom trained model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by arduinitavares** [comment]
> @arduinitavares 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`.
> 
> ### Simple Inference Example
> This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.
> 
> ```python
> import torch
> 
> # Model
> model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, etc.
> # model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')  # custom trained model
> 
> # Images
> im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list
> 
> # Inference
> results = model(im)
> 
> # Results
> results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
> 
> results.xyxy[0]  # im predictions (tensor)
> results.pandas().xyxy[0]  # im predictions (pandas)
> #      xmin    ymin    xmax   ymax  confidence  class    name
> # 0  749.50   43.50  1148.0  704.5    0.874023      0  person
> # 2  114.75  195.75  1095.0  708.0    0.624512      0  person
> # 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
> ```
> 
> <img alt="" width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">
> 
> See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.
> 
> Good luck 🍀 and let us know if you have any other questions!

Is this an automatic response? Because it doesn't solve my problem at all.

**Comment by glenn-jocher** [comment]
@arduinitavares OpenVINO usage examples are clearly displayed after export. Suggest you start there.

**Comment by arduinitavares** [comment]
> @arduinitavares OpenVINO usage examples are clearly displayed after export. Suggest you start there.

How can I get the detect layers (including nms, anchor frame calculations, etc.) when exporting it?

**Comment by ArgoHA** [comment]
@arduinitavares Hi! I have pretty much the same question. Did you manage to make it work?

I need to get  `xmin,    ymin,    xmax,   ymax,  confidence,  class` or  `center_x, center_y, w, h, confidence,  class` then use nms and get final bboxes with classes and conferences levels

But now I get pretty strange stings like this `6.50,4.82,13.65,11.75,0.00,1.00`

**Comment by arduinitavares** [comment]
Hey @ArgoHA,

No, I haven't done it until now. I was reverse engineering it step by step because the inference works perfectly with "detect.py", but it was too time consuming, so I eventually gave up using yolov5 + openvino.
