### ISSUE TITLE
Import statement about yolov5

### ISSUE THREAD

**Issue by Jack24658735** [ultralytics/yolov5#7579]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Other

### Bug

Hi,
I ran the tutorial.ipynb in the repo. Then, I found the original import statement from yolov5 import utils could report error message ModuleNotFoundError: No module named 'yolov5'. So, I think it should be revised to import utils to work properly.
Please check whether it's a bug, thanks!

### Environment

- YOLOv5  v6.1-161-ge54e758 torch 1.11.0+cpu CPU
- OS: Windows 10
- Python: 3.8.5

### Minimal Reproducible Example

#!git clone https://github.com/ultralytics/yolov5  # clone
#%cd yolov5
#%pip install -qr requirements.txt  # install

import torch
import sys
from yolov5 import utils
display = utils.notebook_init()  # checks

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Jack24658735 it depends. If the cell is run in a single click the current implementation needs to stay as it's the only one that works correctly. If you place the import into another cell then yes you just import utils directly.
