### ISSUE TITLE
Inference Error

### ISSUE THREAD

**Issue by codeHorasan** [ultralytics/yolov5#7581]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

C:\Users\ugur_\.conda\envs\for_yolo\pythonw.exe "C:/Users/ugur_/PycharmProjects/Human Detection and Tracking/yolov5_human.py"
Using cache found in C:\Users\ugur_/.cache\torch\hub\ultralytics_yolov5_master
YOLOv5  2022-1-22 torch 1.11.0+cpu CPU

Fusing layers... 
Model Summary: 213 layers, 7225885 parameters, 0 gradients
Adding AutoShape... 
False
C:\Users\ugur_\.conda\envs\for_yolo\lib\site-packages\torch\autocast_mode.py:162: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
Traceback (most recent call last):
  File "C:/Users/ugur_/PycharmProjects/Human Detection and Tracking/yolov5_human.py", line 42, in <module>
    results = model(frame)
  File "C:\Users\ugur_\.conda\envs\for_yolo\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\ugur_\.conda\envs\for_yolo\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\ugur_/.cache\torch\hub\ultralytics_yolov5_master\models\common.py", line 539, in forward
    y = self.model(x, augment, profile)  # forward
  File "C:\Users\ugur_\.conda\envs\for_yolo\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\ugur_/.cache\torch\hub\ultralytics_yolov5_master\models\common.py", line 397, in forward
    y = self.model(im) if self.jit else self.model(im, augment=augment, visualize=visualize)
  File "C:\Users\ugur_\.conda\envs\for_yolo\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\ugur_/.cache\torch\hub\ultralytics_yolov5_master\models\yolo.py", line 126, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "C:\Users\ugur_/.cache\torch\hub\ultralytics_yolov5_master\models\yolo.py", line 149, in _forward_once
    x = m(x)  # run
  File "C:\Users\ugur_\.conda\envs\for_yolo\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\ugur_/.cache\torch\hub\ultralytics_yolov5_master\models\common.py", line 50, in forward_fuse
    return self.act(self.conv(x))
  File "C:\Users\ugur_\.conda\envs\for_yolo\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\ugur_\.conda\envs\for_yolo\lib\site-packages\torch\nn\modules\conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\ugur_\.conda\envs\for_yolo\lib\site-packages\torch\nn\modules\conv.py", line 444, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: expected scalar type Double but found Float

Process finished with exit code 1

![log_Ss](https://user-images.githubusercontent.com/58119113/165182916-04f3fe49-6ba7-4f17-bcc7-fd863b51defb.PNG)

### Environment

Python 3.7

### Minimal Reproducible Example

![ss](https://user-images.githubusercontent.com/58119113/165183177-405604d6-1ecc-4952-bcd8-d5989599a15d.PNG)

### Additional

I am getting this error despite I created a new conda environment in Python3.7 and used the requirements.txt for the packages.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@codeHorasan 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, etc.
# model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')  # custom trained model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by codeHorasan** [comment]
Hello, thanks for responding. I used to run Yolov5 inference without any problem and I've been trying to handle this "RuntimeError: expected scalar type Double but found Float" error for days but somehow it has been handled by itself after I reshaped the frame and specified the shape on the model object. I don't need to keep these changes strangely as the original code works without any errors at the moment.

I don't understand what the issue was and how it was solved but I'm happy now it isn't a problem anymore.

**Comment by glenn-jocher** [comment]
@codeHorasan glad to hear that the issue resolved itself! These kinds of intermittent issues can be quite puzzling, but I'm glad everything is working smoothly for you now. If you encounter any other issues or have further questions in the future, feel free to reach out. Good luck with your YOLOv5 project!
