### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by liyuyuan6969** [ultralytics/yolov5#7587]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

# describe
hi,guys,i am convert yolov5 model to TorchScript,but i have an error above.so i don't understand `y` is a empty list.why could index from it,and i check github source code,i find code is same.and how can i solve it?thanks!
# error info image
![image](https://user-images.githubusercontent.com/53716679/165244197-720cb17d-59f3-4f7e-a907-a84418d45b10.png)
# my code img
![image](https://user-images.githubusercontent.com/53716679/165244427-3382bd16-7151-42a0-b629-af989b23c8bb.png)

# source code img
![image](https://user-images.githubusercontent.com/53716679/165244511-13a4792e-4e0f-4e5b-a886-a8cf79ecd709.png)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by liyuyuan6969** [comment]
sorry,it is my problem.i  annotate my next `y.append` code

**Comment by glenn-jocher** [comment]
@liyuyuan6969 no problem at all! It happens to the best of us. Glad to hear you figured it out. If you have any more questions or run into any other issues, feel free to ask. Good luck with your project!
