### ISSUE TITLE
What does this number represent？

### ISSUE THREAD

**Issue by hjw-0909** [ultralytics/yolov5#7589]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Does the number in the upper left corner of the graph represent **the probability of being predicted to be a certain category,** or what?
And **how is this number obtained**?

![image](https://user-images.githubusercontent.com/56182057/165260010-a0153839-8351-4a88-9de8-39eb4a83d47d.png)

**Comment by MartinPedersenpp** [comment]
That is the confidence score returned by the model, So it means that the model thinks that it is 75% guaranteed to be a monkey

**Comment by hjw-0909** [comment]
@MartinPedersenpp  it means probability？

**Comment by MartinPedersenpp** [comment]
Yes

**Comment by hjw-0909** [comment]
@MartinPedersenpp  Is the probability shown on faster_rcnn also?
faster_rcnn has many 1,so i don't believe it....

**Comment by MartinPedersenpp** [comment]
@hjw-0909 I don't know, since this is Yolo and not faster_rcnn but normally the rating next to the bounding box is the probability/confidence

**Comment by hjw-0909** [comment]
@MartinPedersenpp  ok, thank you very much~
