### ISSUE TITLE
How can I run Detect.py all videos in directory. by only type python detect.py -- ... 1 time

### ISSUE THREAD

**Issue by BenzKukkik** [ultralytics/yolov5#7592]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'd like to detect all videos file in directory (100-200 video, 30sec per video). 
I know you have "python detect.py --source path/to/**/*.jpg". 
I'd like to know, Do you have like a "python detect.py --source path/to/**/*.mp4"

If cannot, Do you have script pipeline for run all videos in directory.

Please supporting me.

**Comment by glenn-jocher** [comment]
@BenzKukkik sure, any glob command is supported.
