### ISSUE TITLE
How to test results?

### ISSUE THREAD

**Issue by Mashaakim** [ultralytics/yolov5#7598]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello! 

I haven't used YOLOv5 for a while, and now I can't find file test.py

For example, I used 
`python test.py --weights weights/best.pt --data data.yaml --name exp4 --task test` 
and it worked perfectly fine for me.

How to do the same now? 

Thank you!

**Comment by glenn-jocher** [comment]
@Mashaakim welcome back. test.py has been renamed to val.py.

**Comment by Ashlesha1995** [comment]
Hi **@Mashaakm**  
`python path/to/val.py --weights yolov5s.pt --data coco128.yaml --img 640`
