### ISSUE TITLE
Passing save-txt flag changes validation results

### ISSUE THREAD

**Issue by kymillev** [ultralytics/yolov5#760]
I am running the latest version as of today (08/17/2020).

## 🐛 Bug
When running python test.py on a custom dataset the results with and without the save-txt flag are different.

## To Reproduce (REQUIRED)

Without save-txt:
```
!python test.py --weights best_run7.pt --data routeyou.yaml --img 1024

 Class      Images     Targets           P           R      mAP@.5
 all         128          71       0.934       0.958        0.99       0.909
```
With save-txt:
```
!python test.py --weights best_run7.pt --data routeyou.yaml --img 1024 --save-txt

Class      Images     Targets           P           R      mAP@.5
all         128          71       0.907        0.93       0.958       0.569
```

## Expected behavior
The validation results should be the same (except for the last one regarding the speed)

**Comment by glenn-jocher** [comment]
@kymillev thanks for the bug report! If you are seeing different results then that is not correct, perhaps there is an inplace operation happening or a variable reassignment. I'll add it to the TODO list to look at.

**Comment by glenn-jocher** [comment]
@kymillev this bug was reproduced, fixed, validated and merged. See PR #763 for further details.

To receive this fix simply `git pull` to update your existing repo or `git clone` a fresh copy (preferred).

Thank you for your contributions.

**Comment by mina-pvn** [comment]
Hi, I have similar issue. I have the latest version of the repo. I get different results when running val.py with/ without --save-hybrid

**Comment by glenn-jocher** [comment]
@mina-pvn hi there! Thanks for reaching out. It seems there might be a bug causing the discrepancy. We'll look into it and get back to you soon. Appreciate your patience!
