### ISSUE TITLE
Why does using the SPPF module reduce the number of layers of the model compared to using the SPP module? !

### ISSUE THREAD

**Issue by PeterSmith1** [ultralytics/yolov5#7601]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hi, I want to know why I use the sppf reduce the number of layers of the model compared to using the spp?

**Comment by glenn-jocher** [comment]
@PeterSmith1 for SPPF details see https://github.com/ultralytics/yolov5/pull/4420

**Comment by PeterSmith1** [comment]
> SPPF 详细信息的@PeterSmith1请参见 #4420

thank you!
