### ISSUE TITLE
I use the converted TensorRT model, but no result output

### ISSUE THREAD

**Issue by LovMone5** [ultralytics/yolov5#7602]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I convert .pt to .engine via export.py
But the detection ends directly and there is no result output
![image](https://user-images.githubusercontent.com/62175202/165453169-7dda3b6e-34ec-4da0-b7fa-2c0bfc462a80.png)
![image](https://user-images.githubusercontent.com/62175202/165453237-2a707227-183d-443d-abb7-9933ce7993e4.png)

**Comment by LovMone5** [comment]
I downgraded the CUDA version to 11.3 (previously 11.6) and it worked fine, I guess it doesn't support 11.6 well enough?

**Comment by PICOPON** [comment]
Same issue.   I also convert .pt to .engine, the ONNX model **best.onnx** works well (it can predict the target) but **best.engine** cannot predict the target. 

![image](https://user-images.githubusercontent.com/49949166/165541851-9218ba43-ff1f-4cb2-8bb8-14f6b679e74c.png)

**Comment by LovMone5** [comment]
I solved it by reinstalling lower version of CUDA and cudnn

**Comment by PICOPON** [comment]
My  version of CUDA and cudnn:
CUDA: 11.3.0
cudnn: 8.2.1
pytorch: 1.10.2
python: 3.9.7
OS: win10
TensorRT 8.2.1.8
**.onnx successfully predicts target but .engine no result output (test by detect.py)** I also doubt if it's a version issue.
Could I see your relevant version? 
Thanks.

**Comment by mx2013713828** [comment]
您好，请问您用的是什么版本的tensorrt呢？在win10上安装和部署的教程有参考吗？网上找了好多版本不一致，我想用v6版本的yolov5。

**Comment by zhangyongming97** [comment]
> My version of CUDA and cudnn: CUDA: 11.3.0 cudnn: 8.2.1 pytorch: 1.10.2 python: 3.9.7 OS: win10 TensorRT 8.2.1.8 **.onnx successfully predicts target but .engine no result output (test by detect.py)** I also doubt if it's a version issue. Could I see your relevant version? Thanks.

I have the same problem

**Comment by PICOPON** [comment]
> My version of CUDA and cudnn: CUDA: 11.3.0 cudnn: 8.2.1 pytorch: 1.10.2 python: 3.9.7 OS: win10 TensorRT 8.2.1.8 **.onnx successfully predicts target but .engine no result output (test by detect.py)** I also doubt if it's a version issue. Could I see your relevant version? Thanks.

Sorry, Actually these versions work well. I solved it.

**Comment by glenn-jocher** [comment]
@PICOPON great to hear that you were able to resolve the issue! If you have any other questions or need further assistance, feel free to ask. It's always helpful to share solutions with the community.
