### ISSUE TITLE
yaml question

### ISSUE THREAD

**Issue by Wfast** [ultralytics/yolov5#7605]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

[[-1, 1, Conv, [64, 6, 2, 2]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C3, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 6, C3, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, C3, [512]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 3, C3, [1024]],
   [-1, 1, SPPF, [1024, 5]],  # 9
  ]
i want to know whether ',' in '#9  [-1, 1, SPPF, [1024, 5]],'  can be removed?

**Comment by glenn-jocher** [comment]
@Wfast you can remove anything you want, but removing earlier layer requires updating the later layers that depend on those inputs as well.
