### ISSUE TITLE
Loading a custom trained model with PyTorch Hub does not work. Error: invalid load key, 'v'.. Cache may be out of date

### ISSUE THREAD

**Issue by pasmai** [ultralytics/yolov5#7606]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

PyTorch Hub

### Bug

When I try to load a custom trained model with PyTorch Hub, I receive an error that there is an invalid load key 'v'.

The exception appears when loading both `force_reload` set to `True` and `False`.
Can anybody offer some help?

## Exception log:
```sh
Startin server...
Loading model:  yolov5m.pt
Downloading: "https://github.com/ultralytics/yolov5/archive/master.zip" to /home/pmaillard/.cache/torch/hub/master.zip
YOLOv5 🚀 2022-4-27 torch 1.10.0+cu113 CUDA:0 (NVIDIA TITAN RTX, 24220MiB)

Fusing layers...
Model summary: 378 layers, 35254692 parameters, 0 gradients, 49.0 GFLOPs
Adding AutoShape...
Downloading: "https://github.com/ultralytics/yolov5/archive/master.zip" to /home/pmaillard/.cache/torch/hub/master.zip
YOLOv5 🚀 2022-4-27 torch 1.10.0+cu113 CUDA:0 (NVIDIA TITAN RTX, 24220MiB)

Traceback (most recent call last):
  File "/home/pmaillard/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 47, in _create
    model = DetectMultiBackend(path, device=device)  # download/load FP32 model
  File "/home/pmaillard/.cache/torch/hub/ultralytics_yolov5_master/models/common.py", line 307, in __init__
    model = attempt_load(weights if isinstance(weights, list) else w, map_location=device)
  File "/home/pmaillard/.cache/torch/hub/ultralytics_yolov5_master/models/experimental.py", line 96, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location=map_location)  # load
  File "/home/pmaillard/github/student-object-classification/Source/Server/.venv/lib/python3.8/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/pmaillard/github/student-object-classification/Source/Server/.venv/lib/python3.8/site-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "server.py", line 174, in <module>
    models = load_models()
  File "server.py", line 132, in load_models
    torch.hub.load('ultralytics/yolov5',
  File "/home/pmaillard/github/student-object-classification/Source/Server/.venv/lib/python3.8/site-packages/torch/hub.py", line 399, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/home/pmaillard/github/student-object-classification/Source/Server/.venv/lib/python3.8/site-packages/torch/hub.py", line 428, in _load_local
    model = entry(*args, **kwargs)
  File "/home/pmaillard/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 71, in custom
    return _create(path, autoshape=autoshape, verbose=_verbose, device=device)
  File "/home/pmaillard/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 66, in _create
    raise Exception(s) from e
Exception: invalid load key, 'v'.. Cache may be out of date, try `force_reload=True` or see https://github.com/ultralytics/yolov5/issues/36 for help.
```

## Loading model in server:
```py
    for r, d, f in os.walk(MODELS_DIRECTORY):
        for file in f:
            if ".pt" not in file:
                continue

            name = os.path.splitext(file)[0]
            print("Loading model: ", name)
            dict_of_models[name] = \
                torch.hub.load('ultralytics/yolov5',
                               'custom',
                               path=os.path.join(r, file),
                               force_reload=True,
                               autoshape=True)
```

### Environment

- Python 3.8.10
- Ubuntu 20.04.3 LTS

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pasmai** [comment]
The issue was that the models were stored in Git LFS.

Fix by downloading them manually with `git pull lfs`.

**Comment by nqa112** [comment]
> The issue was that the models were stored in Git LFS.
> 
> Fix by downloading them manually with `git pull lfs`.

Thanks a lot !
To anyone who also faces this error, on Google Colab, I have a LFS yolo weights file in my repo, just do this to get all LFS file in repo:
```
!git clone [repo name you want to clone]
!git lfs pull
```
The output, in my case, should be this:
```
Git LFS: (1 of 1 files) 160.20 MB / 160.20 MB
```

**Comment by glenn-jocher** [comment]
@nqa112 you're welcome! Thanks for sharing your solution for downloading LFS files in your repo. It will be helpful for others encountering a similar issue. If you have any more questions or need further assistance, feel free to ask!

**Comment by JZ-mcovision** [comment]
I'm facing the same problem on colab, but it still doesn't work after git pull fls.

!python detect.py --weights {HOME}/best.pt --img 1280 --conf 0.25 --source {HOME}/test_soccer.mp4 --name custom
_pickle.UnpicklingError: invalid load key, '<'.

**Comment by glenn-jocher** [comment]
@JonasZaoui2 it seems like the model weights file (`best.pt`) might be corrupted or not properly downloaded. This can happen if the file is not fully checked out with Git LFS before attempting to load it with YOLOv5.

Here's what you can try:

1. Ensure that Git LFS is installed in your Colab environment. If it's not installed, you can install it using:
   ```sh
   !apt-get install git-lfs
   ```

2. Clone your repository and pull the LFS files as you've mentioned:
   ```sh
   !git clone [your-repo-url]
   %cd [your-repo-directory]
   !git lfs pull
   ```

3. Verify that the `best.pt` file has been correctly downloaded. You can check the file size to make sure it's not just a placeholder file created by Git LFS.

4. If the file is correctly downloaded and you still face the issue, try clearing the cache in Colab and re-downloading the file.

5. If the problem persists, you may want to re-upload the `best.pt` file to ensure it's not corrupted.

Remember to replace `[your-repo-url]` and `[your-repo-directory]` with your actual repository URL and directory name. If you continue to have issues, please provide more details or consider opening an issue on the YOLOv5 repository for further assistance.

**Comment by JZ-mcovision** [comment]
@glenn-jocher Hello, thanks for your help ! It's working now ! I had already try git lfs but no resuts, but i redownloaded the file directly from the doc and it's working now :)

**Comment by glenn-jocher** [comment]
@JonasZaoui2 That's great to hear! I'm glad downloading the file directly worked out for you. If you encounter any more issues or have further questions, don't hesitate to reach out. Happy detecting! 😊🚀

**Comment by batubb** [comment]
@JonasZaoui2 are you working on this notebook: https://colab.research.google.com/github/roboflow/notebooks/blob/main/notebooks/how-to-track-football-players.ipynb

I have the same issue and I can't seem to fix best.pt. Any tips?

**Comment by aamirali13** [comment]
> @JonasZaoui2 are you working on this notebook: https://colab.research.google.com/github/roboflow/notebooks/blob/main/notebooks/how-to-track-football-players.ipynb
> 
> I have the same issue and I can't seem to fix best.pt. Any tips?

I am also facing the same error and tried lot of solution from online. Request if anyone can help out please.

**Comment by KLL535** [comment]
**(venv) C:\python2\JoyCaption>git pull lfs**
error: cannot spawn sh: No such file or directory
fatal: unable to fork

**(venv) C:\python2\JoyCaption>git lfs pull**
git: 'lfs' is not a git command. See 'git --help'.

**apt-get install git-lfs**
Not work in Windows!

**Comment by pderrenger** [comment]
It seems like Git LFS is not installed or properly configured on your Windows system. You can download and install Git LFS for Windows from [https://git-lfs.com/](https://git-lfs.com/). After installation, run the following commands in your terminal to initialize and pull the files:

```bash
git lfs install
git lfs pull
```

Make sure you are in the correct directory where your repository is cloned. If the issue persists, verify your Git installation and try again. Let me know if you need further assistance!

**Comment by KLL535** [comment]
> It seems like Git LFS is not installed or properly configured on your Windows system. You can download and install Git LFS for Windows from https://git-lfs.com/. After installation, run the following commands in your terminal to initialize and pull the files:
> 
> ```shell
> git lfs install
> git lfs pull
> ```
> 
> Make sure you are in the correct directory where your repository is cloned. If the issue persists, verify your Git installation and try again. Let me know if you need further assistance!

Thank you, it worked

**Comment by pderrenger** [comment]
You're welcome! Glad to hear it worked. If you have any other questions or run into issues, feel free to ask. Happy coding!
