### ISSUE TITLE
Use lable smoothing

### ISSUE THREAD

**Issue by WangRongsheng** [ultralytics/yolov5#7607]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Hello，Whether to consider adding label smoothing？

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@WangRongsheng you can use label smoothing like this:
```
python train.py --label-smoothing 0.01
```
