### ISSUE TITLE
ImportError: cannot import name 'MobileOptimizerType'

### ISSUE THREAD

**Issue by ZDLLLL** [ultralytics/yolov5#7610]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

在运行export.py文件时，报错，内容如下：
![image](https://user-images.githubusercontent.com/44689801/165541080-0fe6d311-2540-46b9-9f85-2857a6c904a4.png)

**Comment by glenn-jocher** [comment]
@ZDLLLL your PyTorch is likely out of date. To update see:
https://pytorch.org/get-started
