### ISSUE TITLE
Need some help with CUDA error and compatibility issue

### ISSUE THREAD

**Issue by Jeromedebruyn** [ultralytics/yolov5#7613]
### Search before asking

- [ ] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am running into a similar problem as Issue #2855
 
I am trying to simply run the detect (Zidane) line and run into the following error. 

*RuntimeError: CUDA error: no kernel image is available for execution on the device*

If I am not mistaken it is a compatibility issue with sm_80 but I have no idea how to resolve it as I've tried (almost) every version of pytorch and cuda.  Thank you in advance for anyone's support!!

I am currently on:

  added / updated specs:
    - cudatoolkit=11.3
    - pytorch==1.8.1
    - torchaudio==0.8.1
    - torchvision==0.9.1

![help](https://user-images.githubusercontent.com/56159204/165626850-a6164a75-b067-4691-b197-1013b18d0ca7.PNG)

**Comment by glenn-jocher** [comment]
@Jeromedebruyn it appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual [Python 3.9](https://www.python.org/) environment, clone the latest repo ([code changes daily](https://github.com/ultralytics/yolov5/commits/master)), and `pip install` [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) again from scratch.

💡 ProTip! Try one of our verified environments below if you are having trouble with your local environment.


## Requirements

[**Python>=3.7.0**](https://www.python.org/) with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) installed including [**PyTorch>=1.7**](https://pytorch.org/get-started/locally/). To get started:
```bash
git clone https://github.com/ultralytics/yolov5  # clone
cd yolov5
pip install -r requirements.txt  # install
```

[Models](https://github.com/ultralytics/yolov5/tree/master/models) and [datasets](https://github.com/ultralytics/yolov5/tree/master/data) download automatically from the latest YOLOv5 [release](https://github.com/ultralytics/yolov5/releases) when first requested.

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), validation ([val.py](https://github.com/ultralytics/yolov5/blob/master/val.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/export.py)) on MacOS, Windows, and Ubuntu every 24 hours and on every commit.

**Comment by Jeromedebruyn** [comment]
Hi @glenn-jocher, 
Thank you for your quick answer, it is much appreciated! I gave it a shot with a new virtual environment on miniconda with python 3.9 and pytorch1.10+cuda11.3 and ran into the same error.  Do you have an idea on any other ways to resolve this problem or simply to know more about the exact issue? For information: I am connected to ssh to run on external NVIDIA A100 gpu.

**Comment by glenn-jocher** [comment]
@Jeromedebruyn the problem is your pytorch installation. Your original screenshot directs you to pytorch to install correct version, not sure why you're not doing that. 

You can also use Docker image, that's what it's there for.

**Comment by Jeromedebruyn** [comment]
@glenn-jocher The thing is I do download pytorch following the link, and it should technically be compatible. I also believe I am using docker image, but am not too familiar with it. I am guessing it is an issue connecting the environment to the server maybe?

![help2](https://user-images.githubusercontent.com/56159204/165721978-1092cac5-57f0-4508-adf7-481cb119e4a5.PNG)

**Comment by glenn-jocher** [comment]
Use Docker Image
