### ISSUE TITLE
Any Tips Training For many labels?

### ISSUE THREAD

**Issue by bellhyeon** [ultralytics/yolov5#7616]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, There!
I'm new in object detection, starting from yolov5.

I'm trying to train yolov5m / yolov5m6 model from scratch with this commands (default configs)

**train.py --local_rank=0 --batch 15 --data kfood.yaml --weights --img 1280 --device 1,2,3 --cfg yolov5m6.yaml**

I have about 640K foods images with 400 labels, each class have about 1.5K images that sizes each over 4mb.

Due to storage problem, i resized original image before training, to 1280.

I trained yolov5m6 model with RTX 3090 x 3EA for 5 days (about 45 epochs / seems to be convergenced), but when testing, can't detect well. 

I tried to reduce conf-thres and iou-thres, but can't detect well. I think there are too many labels, so can't detect well.

Can you give me some tips?

Thanks.

![image](https://user-images.githubusercontent.com/60704551/165669604-2a05d6d8-d3c0-4efc-a2f9-7364cef3b4c5.png)
![image](https://user-images.githubusercontent.com/60704551/165670060-71d09601-c5fa-40a8-8d8c-6320719579f9.png)

![image](https://user-images.githubusercontent.com/60704551/165669245-92c32c52-b7c6-4bdf-b953-1fa43a031311.png)
![image](https://user-images.githubusercontent.com/60704551/165669845-b5f97bf8-ac35-4d27-bf8d-fa3263b6cfce.png)

**Comment by glenn-jocher** [comment]
@bellhyeon your mAP is about 0.9. If your deployed space matches your validation space you're all good.

**Comment by bellhyeon** [comment]
> @bellhyeon your mAP is about 0.9. If your deployed space matches your validation space you're all good.

Train / Valid images are annotated for one label.

But i want to test (detect) pic which have various label.

My mAP seems to be fitted to single label pics.

Does it effects to testing?

**Comment by glenn-jocher** [comment]
Your training and deployed spaces must match for best results:
<img width="2029" alt="dataset" src="https://user-images.githubusercontent.com/26833433/166044230-a201c12d-a32a-4327-9780-c322bebe4b3c.png">

**Comment by zhangyongming97** [comment]
How was this image made? Is it automatically generated during training
![捕获1](https://user-images.githubusercontent.com/47034617/166647596-f09168bb-7a9a-44a0-8fcf-de8d834090ea.PNG)
?

**Comment by glenn-jocher** [comment]
@zhangyongming97 automatic YOLOv5 image on train start
