### ISSUE TITLE
the result on visdrone

### ISSUE THREAD

**Issue by ZWBdoudou** [ultralytics/yolov5#7620]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi! I want to know what is the map result of YOLOv5_6.0 on Visdrone2019

**Comment by glenn-jocher** [comment]
@ZWBdoudou train it and find out:
```
python train.py --data VisDrone.yaml
```
