### ISSUE TITLE
Expo eas build issues

### ISSUE THREAD

**Issue by tibor-mach** [ultralytics/yolov5#7621]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When trying to build an android APK using a TF.JS-converted model,  react-native and expo eas (expo sdk 42) we are running into the following issues:

Training the model in PyTorch (using  yolov5 6.0 ) work fine
building a testing react web app with the model works fine as well (using https://github.com/zldrobit/tfjs-yolov5-example.git )
Using eas, the model built as a development client also works
Using eas to built as an APK does not work. It can be built but the APK but in the APK, model loading is stuck at the `loadGraphModel` method (i.e. the model cannot be loaded when running on a mobile phone) with the following error:
`[RangeError: ArrayBuffer length minus the byteOffset is not a multiple of the element size]`

Any idea why this might be? (Looking up the error in this context does not lead to any relevant results). thanks a lot!

**Comment by glenn-jocher** [comment]
@tibor-mach hi there! 🌟 It sounds like you've put a lot of work into this project! The error you're encountering during APK building is likely related to the model loading on a mobile device. Have you checked if there are any specific compatibility issues with TF.JS-converted models and the Expo eas build process? Sometimes certain configurations can cause unexpected errors. 

If the web app and development client work as expected, it might be worth double-checking any mobile-specific requirements or limitations. Other than that, the YOLOv5 community and the Ultralytics team are always available to support you through any challenges you encounter. I hope this helps!
