### ISSUE TITLE
The purpose of 'n = 1'

### ISSUE THREAD

**Issue by Ashionnal** [ultralytics/yolov5#7622]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

In the parse_model method in the file 'yolo.py', if the C3 module is repeated twice, the code will put 'n=1', which will not cause 'nn.Sequential(*(m(*args) for _ in range(n))) if n > 1 else m(*args)' this line of code is one less C3?So,the purpose of 'n = 1' is what?
![微信截图_20220428173518](https://user-images.githubusercontent.com/23193694/165724671-f699d409-4153-426e-85c9-faa79005ddc0.png)

**Comment by glenn-jocher** [comment]
@Ashionnal C3 repeats are handled internally. n=1 sets the external count to prevent multiple C3s in series.
