### ISSUE TITLE
How to save results to my own folder? 

### ISSUE THREAD

**Issue by Fajerfica** [ultralytics/yolov5#7626]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi. I`m writing web app for using YOLOv5 and I need to save results to my own folder. Because I need to manipulate them. And I can`t work with detect.py.

How can I do this?

**Comment by glenn-jocher** [comment]
@Fajerfica use `--project` and `--name` arguments:
https://github.com/ultralytics/yolov5/blob/177da7f348181abdf4820ad26707eb8b3dd4fdc9/detect.py#L231-L233

**Comment by Ashlesha1995** [comment]
cv2.imwrite(save_path, im0)

**Comment by glenn-jocher** [comment]
@Ashlesha1995 that's correct! After detecting with YOLOv5, you can use `cv2.imwrite(save_path, im0)` to save the results to your own folder. For more details, you can refer to the Ultralytics Docs at https://docs.ultralytics.com/yolov5/.
