### ISSUE TITLE
Run inference offline/raspberry

### ISSUE THREAD

**Issue by AykeeSalazar** [ultralytics/yolov5#7635]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

We are developing a system where it will automatically detect some violations. In line with this, the inference available is through Pytorch Hub, which is not efficient in our case as we want the model to detect the violation without the internet. Is there any way to do that without importing the model from pytorch hub? thank you

**Comment by MartinPedersenpp** [comment]
You need to transfer the repo to your raspberry and load the model like this:
`torch.hub.load('PATH_TO_REPO', 'custom', path='weights.pt', source="local")`
Explanation: torch.hub.load's "source" parameter can be github by default or set to "local" which will load the repo from your device.
I hope this helps

**Comment by Kodp** [comment]
> You need to transfer the repo to your raspberry and load the model like this: `torch.hub.load('PATH_TO_REPO', 'custom', path='weights.pt', source="local")` Explanation: torch.hub.load's "source" parameter can be github by default or set to "local" which will load the repo from your device. I hope this helps

But this will cause‘ No module named 'models'’  I've had this problem for a long time

**Comment by MartinPedersenpp** [comment]
You need to have the yolo folder as your active directory when you run the inference I think.
In anyway, this is not a yolo problem but a python problem regarding the importing of modules

**Comment by Kodp** [comment]
> You need to have the yolo folder as your active directory when you run the inference I think. In anyway, this is not a yolo problem but a python problem regarding the importing of modules
Yes you are right。 I succeeded by putting the yolov5 folder in my working directory.  
 but i dont understand why it works😶

**Comment by MartinPedersenpp** [comment]
I am not a 100% sure, but look at hubconf.py
This is the library getting loaded by torch.hub.load()
So when hubconf.py tries to import from models the path is relative and therefore python will be searching in your CWD and if there is no folder named models it will throw the no module found error.
Anyone should feel free to confirm this since I am no data scientist / Yolo / torch expert

**Comment by glenn-jocher** [comment]
@MartinPedersenpp noted! 🙌 The behavior you experienced is likely due to Python's module importing searching relative to the current working directory (CWD). Placing the YOLOv5 folder in your working directory enabled successful module import.

Great work troubleshooting! 🎉 Always feel free to reach out with any further questions.

**Comment by flaviogheri** [comment]
I also wanted to run the yolov5 offline on my raspberry pi, but didnt want to have to import the entire yolo repository with it, what are the essential files I need to run it locally without the entire repository @glenn-jocher ?

**Comment by glenn-jocher** [comment]
To run YOLOv5 offline on your Raspberry Pi without importing the entire repository, you'll need a few essential files:

1. **Model Weights**: Your trained model weights file (e.g., `best.pt`).
2. **YOLOv5 Model Definition**: The model architecture and configuration files.
3. **Inference Script**: A script to load the model and run inference.

Here's a minimal setup:

1. **Download the Model Weights**:
    ```bash
    wget https://path/to/your/best.pt -O best.pt
    ```

2. **Create an Inference Script**:
    ```python
    import torch
    from pathlib import Path

    # Load model
    model = torch.hub.load('ultralytics/yolov5', 'custom', path='best.pt', source='local')

    # Inference
    img = 'path/to/your/image.jpg'
    results = model(img)

    # Print results
    results.print()
    ```

3. **Ensure Dependencies**: Make sure you have the necessary dependencies installed, such as PyTorch and other required libraries.

This setup should allow you to run YOLOv5 locally without needing the entire repository. If you encounter any issues or need further assistance, feel free to ask! 😊

For more detailed guidance, you can refer to the [Ultralytics documentation](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading/).
