### ISSUE TITLE
scipy and numpy version dependency

### ISSUE THREAD

**Issue by fei4xu** [ultralytics/yolov5#7638]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,

I noticed that in the requirement.txt 
https://github.com/ultralytics/yolov5/blob/master/requirements.txt#L5-L10
```python
numpy>=1.18.5
scipy>=1.4.1
```
and also in the scipy & numpy version compatible table at https://docs.scipy.org/doc/scipy/dev/toolchain.html#numpy

<html>
<body>

SciPy version | Python versions | NumPy versions
-- | -- | --
1.2 | 2.7, >=3.4, <=3.7 | >=1.8.2, <= 1.16.x
1.4 | >=3.5, <=3.8 | >=1.13.3, <= 1.17.3
1.5 | >=3.6, <=3.9 | >=1.14.5, <= 1.19.3

</body>
</html>

if `numpy>1.18`, scipy should be at least `1.5`, so the current version of `>=1.4.1` should be change to at lease 1.5, am I right?
(I'm new to scipy and numpy)

**Comment by glenn-jocher** [comment]
@fei4xu yes I think you are right! I'll make a PR.

**Comment by glenn-jocher** [comment]
@fei4xu good news 😃! Your original issue may now be fixed ✅ in PR #7646. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
