### ISSUE TITLE
The calculation method of map@0.5 is belong to voc2007 or voc2012？

### ISSUE THREAD

**Issue by Isaiah1013** [ultralytics/yolov5#7640]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

There are 101 points used in the calculation method of map@0.5, it is similar to the map@0.5 of voc2007 metrics, i want confirm that map@0.5 in yolov5 is  belong to voc2007 or voc2012?

**Comment by glenn-jocher** [comment]
@Isaiah1013 AP function is here:
https://github.com/ultralytics/yolov5/blob/488fb0a36a852b7a40680e863ca317d3d2bb6a1c/utils/metrics.py#L89-L115

VOC results are here:
https://wandb.ai/glenn-jocher/YOLOv5_VOC_official

**Comment by Isaiah1013** [comment]
> @Isaiah1013 AP function is here:
> 
> https://github.com/ultralytics/yolov5/blob/488fb0a36a852b7a40680e863ca317d3d2bb6a1c/utils/metrics.py#L89-L115
> 
> VOC results are here: https://wandb.ai/glenn-jocher/YOLOv5_VOC_official

thank you very much, I have understood the map in yolov5.

**Comment by glenn-jocher** [comment]
@Isaiah1013 you're welcome! If any more questions come up, feel free to ask. Also, the YOLOv5 community and the Ultralytics team have been instrumental in this work.
