### ISSUE TITLE
DirectML Support possibility

### ISSUE THREAD

**Issue by Denizzje** [ultralytics/yolov5#7642]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Hello Ultralytics team,

Microsoft has been building steadily on DirectML. This is particulary interesting for AMD GPU users as ML applications are generally out of reach due to being Nvidia CUDA only.

Quite recently Microsoft released an update to their PyTorch implementation with DML support. During that update they also actually branched the older YoloV3 Ultralytics repo and made it compatiable with DML GPU acceleration: https://github.com/microsoft/DirectML/tree/master/PyTorch/yolov3 as an example.

It would be nice if you can assess making some "official" support for YoloV5 at some point. Hence my request if you can look at this at it some time :).

### Use case

To enable GPU acceleration for AMD cards and probably Intel GPUs when they come as well.

### Additional

I do not know much about the inner workings of PyTorch and the likes, so I am unable to help with this. I am just opening this request to ask for the possibility of it happening. 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Denizzje thanks for raising this issue! I wasn't previously aware of DirectML. 

Can you raise this same exact issue directly on their repo? Reference this one and tell them I'm available if they have any questions. Thanks!
