### ISSUE TITLE
Training results capped to one class

### ISSUE THREAD

**Issue by earstormer** [ultralytics/yolov5#7643]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I've been training using all default parameters (as suggested for starters). I have ensured my dataset was balanced all across the board, so that looks good. However my trained model seems to only detect the first instance in the class list. Number of classes is set and listed correctly. Am I missing something here?

![image](https://user-images.githubusercontent.com/58913750/165973115-9a88d097-4f75-4861-a52c-976921f4336c.png)

**Comment by glenn-jocher** [comment]
@earstormer your dataset contains only examples of class 0

**Comment by earstormer** [comment]
Ah stupid mistake! Thank you, I went back and re-checked where my dataset was pointed which had an error in it.

**Comment by glenn-jocher** [comment]
@earstormer no problem at all! These things happen, and it's great to hear that you found the issue. If you have any more questions, feel free to ask. Good luck with your training!
