### ISSUE TITLE
C3_2 study

### ISSUE THREAD

**Issue by vanhau201** [ultralytics/yolov5#7644]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I slightly changed the architecture of C3 according to the article and I named it C3_2 then I trained with no problem. But when I evaluate val.py I get the following error. I don't know how to fix it?
![image](https://user-images.githubusercontent.com/86721832/165979963-8e61c17d-eced-4574-9f0f-aaef3d241a4c.png)

### Code C3_2

```
    class C3_2(nn.Module):
       # CSP Bottleneck with 3 convolutions

      def __init__(self, c1, c2, n=1, shortcut=True, g=1, e=0.5):  # ch_in, ch_out, number, shortcut, groups, expansion
          super().__init__()
          c_ = int(c2 * e)  # hidden channels
          self.conv = nn.Conv2d(c1, c_, 1, 1, autopad(1, None), groups=g, bias=False)
          self.bn = nn.BatchNorm2d(c_)
          self.act = nn.SiLU() 
          self.cv1 = Conv_3(2 * c_, c2, 1) 
          self.m = nn.Sequential(*(Bottleneck(c_, c_, shortcut, g, e=1.0) for _ in range(n)))
          # self.m = nn.Sequential(*[CrossConv(c_, c_, 3, 1, g, 1.0, shortcut) for _ in range(n)])
  
      def forward(self, x):
          return self.cv1(torch.cat((self.m(self.act(self.bn(self.conv(x)))), self.conv(x)), dim=1))
```

### yolo.py
![image](https://user-images.githubusercontent.com/86721832/165980419-4e0a3b19-d45f-439b-b849-833e2529ae97.png)

###  Architecture c3_2
![image](https://user-images.githubusercontent.com/86721832/165981145-e3f9b096-4764-403d-8182-f36fca77d6c4.png)

### Link paper
https://www.nature.com/articles/s41598-022-07527-3.pdf

### Additional

paper https://www.nature.com/articles/s41598-022-07527-3.pdf

**Comment by glenn-jocher** [comment]
@vanhau201 if you modify modules or introduce new ones then you need to run your trained models using the same modified yolov5/ that you trained with. Are you doing this?

**Comment by glenn-jocher** [comment]
@vanhau201 your module implementation is a very bad idea, mostly because conv(x) is repeated twice. This will double your FLOPs with zero benefit. I've created a better implementation of the paper module here:

```python
class C3_2(nn.Module):
    # CSP Bottleneck with 3 convolutions

    def __init__(self, c1, c2, n=1, shortcut=True, g=1, e=0.5):  # ch_in, ch_out, number, shortcut, groups, expansion
        super().__init__()
        c_ = int(c2 * e)  # hidden channels
        self.conv = nn.Conv2d(c1, c_, 1, 1, autopad(1, None), groups=g, bias=False)
        self.bn = nn.BatchNorm2d(c_)
        self.act = nn.SiLU()
        self.cv1 = Conv(2 * c_, c2, 1, act=nn.Mish())
        self.m = nn.Sequential(*(Bottleneck(c_, c_, shortcut, g, e=1.0) for _ in range(n)))
        # self.m = nn.Sequential(*[CrossConv(c_, c_, 3, 1, g, 1.0, shortcut) for _ in range(n)])

    def forward(self, x):
        y = self.conv(x)
        return self.cv1(torch.cat((self.m(self.act(self.bn(y))), y), dim=1))
```

**Comment by glenn-jocher** [comment]
@vanhau201 created a new branch with updated YOLOv5n and s models:
https://github.com/ultralytics/yolov5/tree/test/nature

**Comment by vanhau201** [comment]
@glenn-jocher Thanks

**Comment by glenn-jocher** [comment]
@vanhau201 see worse results with the new modules. This is YOLOv5n, drop of about 1% mAP on COCO: 26.7 mAP vs 28.2 official.
https://wandb.ai/glenn-jocher/v7_convtranspose/runs/295wa0zf?workspace=user-glenn-jocher

**Comment by glenn-jocher** [comment]
@vanhau201 ok my results are in. YOLOv5n COCO 300 epochs all default settings. 

Best results I saw were 5x5 groups=1 and 4x4 groups=1. I don't think these are viable candidates for the official models due to the large parameter count and FLOPs increase, but the good news is their depthwise versions are only slightly under them in mAP. Either way these 4 combinations seem to be the main four candidates to consider.

https://wandb.ai/glenn-jocher/v7_convtranspose
<img width="952" alt="Screen Shot 2022-05-03 at 5 13 14 PM" src="https://user-images.githubusercontent.com/26833433/166605741-7a818d75-1e63-4461-811f-78e259fd1565.png">
