### ISSUE TITLE
Replace `forward` with `forward_export` at export.py, Why discard?

### ISSUE THREAD

**Issue by flystarhe** [ultralytics/yolov5#7647]
the main:

https://github.com/ultralytics/yolov5/blob/488fb0a36a852b7a40680e863ca317d3d2bb6a1c/export.py#L497

v6.1:

https://github.com/ultralytics/yolov5/blob/3752807c0b8af03d42de478fbcbf338ec4546a6c/export.py#L463

code from v6.1
```python
        elif isinstance(m, Detect):
            m.inplace = inplace
            m.onnx_dynamic = dynamic
            if hasattr(m, 'forward_export'):
                m.forward = m.forward_export  # assign custom forward (optional)
```

I think it's a very friendly and functional design!

**Comment by glenn-jocher** [comment]
@flystarhe thank you for your input! The change from `m.forward_export` to `m.forward` in `export.py` on v6.1 was done to enhance flexibility and maintain compatibility. The `forward_export` approach was discarded in favor of a more general solution that improves the overall functionality of the codebase. Your feedback is appreciated, and we're continuously refining YOLOv5 to serve the community's needs. If you have any other suggestions or questions, feel free to let us know.
