### ISSUE TITLE
Is it possibile to convert a yolov5 model like yolov5s.pt to a yolov5s.etlt model?

### ISSUE THREAD

**Issue by yao-zheng-yi** [ultralytics/yolov5#7649]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi!
Is it possibile to convert a yolov5 model like **yolov5s.pt** to a **yolov5s.etlt** model? I didn't find a solution to this problem.

I found that .tlt model can be converted to .etlt model, or is it possibile to convert yolov5s.pt to yolov5s.tlt model?

We can use export.py to convert yolov5s.pt to yolov5s.engine, but there doesn't seem to be a way to convert .engine model to .etle model.

**Comment by glenn-jocher** [comment]
@yao-zheng-yi sorry I don't recognize that format. Can you provide some links/docs about it? The 11 supported model formats are here:

## Formats

YOLOv5 inference is officially supported in 11 formats:

Format                      | `export.py --include`         | Model
:---                        | --:                           | :--
[PyTorch](https://pytorch.org/)                     | -                             | `yolov5s.pt`
[TorchScript](https://pytorch.org/docs/stable/jit.html)                 | `torchscript`                 | `yolov5s.torchscript`
[ONNX](https://onnx.ai/)                        | `onnx`                        | `yolov5s.onnx`
[OpenVINO](https://docs.openvino.ai/latest/index.html)                    | `openvino`                    | `yolov5s_openvino_model/`
[TensorRT](https://developer.nvidia.com/tensorrt)                    | `engine`                      | `yolov5s.engine`
[CoreML](https://github.com/apple/coremltools)                      | `coreml`                      | `yolov5s.mlmodel`
[TensorFlow SavedModel](https://www.tensorflow.org/guide/saved_model)       | `saved_model`                 | `yolov5s_saved_model/`
[TensorFlow GraphDef](https://www.tensorflow.org/api_docs/python/tf/Graph)         | `pb`                          | `yolov5s.pb`
[TensorFlow Lite](https://www.tensorflow.org/lite)             | `tflite`                      | `yolov5s.tflite`
[TensorFlow Edge TPU](https://coral.ai/docs/edgetpu/models-intro/)         | `edgetpu`                     | `yolov5s_edgetpu.tflite`
[TensorFlow.js](https://www.tensorflow.org/js)               | `tfjs`                        | `yolov5s_web_model/`

**Comment by yao-zheng-yi** [comment]
use NVIDIA Transfer Learning Toolkit to train a model with our own dataset can get a tlt model, and the .etlt file is an encrypted tlt file, and  use tlt-export can convert a .etlt file to a .;engine file.

here is the docs about tlt.
https://docs.nvidia.com/tao/tao-toolkit/text/overview.html
NVIDIA TAO Toolkit was previously named NVIDIA Transfer Learning Toolkit.

**Comment by glenn-jocher** [comment]
@yao-zheng-yi got it. For questions on 3rd party tools you probably want to raise these directly with their respective authors, i.e. NVIDIA.

**Comment by yao-zheng-yi** [comment]
OK, many thanks

**Comment by glenn-jocher** [comment]
@yao-zheng-yi you're welcome! If you have any more YOLOv5-related questions, feel free to ask. Good luck with your project!

**Comment by Kanan99** [comment]
Hi @yao-zheng-yi 

Could you let me know if you found any solution?
I came up with a similar situation.

I am trying to use deepstream-preprocess-test  with my custom yolov5 model however it seems to me that I have to convert it into .etlt 

I'd be happy to discuss any findings.
