### ISSUE TITLE
When generating results.png, bug happened with disorder on Y-axis of val/box_loss, val/obj_loss and val/cls_loss

### ISSUE THREAD

**Issue by sylvanding** [ultralytics/yolov5#7650]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

When I set the batch size to 16 and tried to generate `results.png` by calling `plot_results()` in `plots.py`, something wrong happened. As the image shows below, there are disorders on the Y-axis of val/box_loss, val/obj_loss and val/cls_loss. And matplotlib output the following warning: 
```
Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.
```
However, when I set batch size to 8 and 4, the problem disappeared. 
Then I added a line of code after `y = data.values[:, j]` in `plot_results()` like this:
```python
for i, j in enumerate([1, 2, 3, 4, 5, 8, 9, 10, 6, 7]):
  y = data.values[:, j]
  y = y.astype('float') # added code
```
the problem was solved. 
![A07i7.png](https://s1.328888.xyz/2022/04/30/A07i7.png)

### Environment

the latest version cloned from GitHub

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@sylvanding hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by 12moli** [comment]
Hello, I added the above code but the problem is still not solved. I am using yolov5 where the backbone part has been modified by me and the result is as follows.![Snipaste_2022-11-02_19-55-31](https://user-images.githubusercontent.com/102312535/199484587-95454dea-4bf7-4731-aa22-790cb610b0d8.png)
But if I use the original yolov5 weights and network structure, there is no problem at all.What should I do to solve the problem that appears in the picture?

**Comment by glenn-jocher** [comment]
Hi @12moli, thanks for the update. It's great that you have narrowed down the issue to your modified backbone. The problem you are experiencing seems to be related to the modifications you made. To further investigate and solve the problem, I recommend carefully reviewing the changes you made to the backbone and comparing them with the original YOLOv5 implementation. This will help identify any discrepancies that might be causing the issue.

You may also want to verify that the data inputs and outputs in the modified backbone are consistent with the original YOLOv5 implementation. Ensuring compatibility with the rest of the YOLOv5 architecture is crucial for proper functioning.

Let me know if you need any further assistance in resolving this issue!
