### ISSUE TITLE
Is there a way to get the coordinates of anchor on the feature map?

### ISSUE THREAD

**Issue by alexHxun** [ultralytics/yolov5#7651]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to get the detected object`s feature rather than image feature. .

I think there are 2 ways to do it: 1) get the crop image using '--save-crop', and run the 'detect.py' again, but it will  cost too much time; 2) The anchor after nms  is obtained from the mapping of feature map to the original picture, is there a way to map from the original picture to the feature picture so as to calculate the coordinates of anchor in the feature map? So i can crop the feature map to get the object`s feature.

I would appreciate it if someone could help me  !

### Additional

no

**Comment by glenn-jocher** [comment]
@2597miles 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, etc.
# model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')  # custom trained model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by mh-ih** [comment]
Very good question!
Really how to crop predicted object from feature maps?
Which layer of the architecture has the best semantic features to compare multiple patches?
How to flatten the multiple channels of a layer to a feature vector?
Flatten()?
AdaptiveAvgPool2d()??

**Comment by glenn-jocher** [comment]
@mh-ih great questions! 🙌 YOLOv5 maintains a **feature-based architecture** that offers a range of options for working with detections and extracting valuable semantic features.

### Predicted Object Cropping
For **cropping detections from feature maps**, consider `model(model, augment=False)[0].pred` which outputs model activations on a given image. For example:
```python
# Retrieve activations
pred = model(im, augment=False)[0].pred

# Crop detections
crops = pred[:, 0]  # obtain topmost detection map
```

### Semantic Feature Comparison
The method for comparing **semantic features across patches** largely depends on specific use cases, but the penultimate layer typically houses rich semantic information. Referencing `Semantic Feature Comparison` from this [GitHub issue thread](https://github.com/ultralytics/yolov5/issues/3157) may also provide valuable insights.

### Flattening Feature Vectors
Flattening multiple channels to a **feature vector** often benefits from `AdaptiveAvgPool2d`. Here's an example:
```python
import torch.nn.functional as F

# Features
x = torch.rand(1, 256, 50, 50)  # sample feature map
x = F.adaptive_avg_pool2d(x, (1, 1)).flatten(1)  # adaptive global pooling
```

For a more concise understanding, kindly visit the official [YOLOv5 Documentation](https://docs.ultralytics.com/yolov5/). Please feel free to reach out with any further questions!

**Comment by mh-ih** [comment]
Thank you very much for your informative reply.
I tested several layers and found that the `SPPF` layer alone gives very good results for comparing detected patches to a template.

**Comment by glenn-jocher** [comment]
@mh-ih you're welcome! 🌟 That's great to hear about your findings with the `SPPF` layer - it's known for capturing rich semantic information. If you have any more questions or need further assistance, feel free to ask. Good luck with your YOLOv5 experiments!
