### ISSUE TITLE
How to use "download_from_url_to_file"?

### ISSUE THREAD

**Issue by Fajerfica** [ultralytics/yolov5#7653]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I need to put yolov5 model+API to Docker and if I download with torch.hub.load, Docker can`t save it, so I need to use torch.hub.download_from_url_to_file. From what url can I download model?

**Comment by glenn-jocher** [comment]
@Fajerfica model URLs are located in release assets section:
https://github.com/ultralytics/yolov5/releases/tag/v6.1
