### ISSUE TITLE
train without validation data

### ISSUE THREAD

**Issue by valleyboytoo** [ultralytics/yolov5#7655]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I wonder how to train without validation data. I got an error like below.

KeyError: 'val' (When I delete the validation path in the yaml file)
Dataset not found ⚠️, missing paths ['/kaggle/input/ts-detection-0430/valid/images'](When I just leave the path in the yaml file) ==>Of course, there is no 'valid' folder.

- only train/test dataset(no validation)
- 39,000 images => it's not working at Roboflow(max 10,000)
- I had to split the dataset manually using codes
- I tried sample data at Roboflow => Roboflow made validation path in yaml file.(I don't understand why) I set 0 validation in Roboflow.
- I guess there must be a way to block the process of searching validation path when executing train.py
- I was searching for hours about this, but I don't know what to do
- If my dataset is not big, it must be easy with Roboflow. I manually split the dataset and want to train without validation. That's it. Thank you in advance.

**Comment by glenn-jocher** [comment]
@valleyboytoo validation set is required to train.

**Comment by valleyboytoo** [comment]
I got it. Thank you Glenn. I thought it an option.

**Comment by glenn-jocher** [comment]
@valleyboytoo you're welcome! The YOLOv5 training process relies on a validation set for optimal performance. If you have any other questions or need further assistance, feel free to ask.

**Comment by mpperez3** [comment]
@glenn-jocher  Yolo 8 (via python) works correctly if you do not set a set of evaluation images in the data.yaml file and only specify the training images (i.e. using same path to train and eval )... But how does yolo work when only the training set is set from data.yaml and no images are set for val? What is the methodology behind it? Is a random set of eval chosen and maintained every epoch? What percentages are used? In addition, are the evaluation images added to the final model knowledge?  I have tried to search information about the training methodology but have not found any information on this.

**Comment by glenn-jocher** [comment]
@mpperez3 hello! When you specify only a training set without a validation set in YOLOv5's `data.yaml`, the system doesn't automatically allocate a portion of your training data for validation. For optimal training and model performance evaluation, it's crucial to manually divide your dataset into separate training and validation sets before training. YOLOv5 does not internally split or choose a random subset for validation if a validation set isn't designated. The methodology behind using a validation set is to assess the model's performance on unseen data during training, without impacting the final model directly. It's essential for detecting overfitting and making informed adjustments to your model.

To configure your dataset with both training and validation paths, your `data.yaml` should look something like this:

```yaml
train: /path/to/train/images
val: /path/to/val/images
```

If you haven't split your dataset yet, it's advisable to do so. A common split ratio is 80% for training and 20% for validation, but this can vary based on your dataset size and diversity.

Remember, the evaluation images (validation set) are not directly used to train the model but to evaluate its performance during the training process. This practice ensures your model is capable of generalizing well to new, unseen data.

**Comment by SprigganCS** [comment]
@glenn-jocher In my project, I am working with two datasets. Initially, I trained YOLOv8 using the entire dataset A and 80% of dataset B, keeping the remaining 20% of dataset B separate from training. After performing validations, I now need to provide a trained model using both datasets in their entirety. Is there a way to achieve this using YOLOv8 from Ultralytics? In this case, the model will not have a validation set, as I need to use the full content of both datasets exclusively for training.
