### ISSUE TITLE
low mAP with pycocotools

### ISSUE THREAD

**Issue by shenhaibb** [ultralytics/yolov5#7658]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

i use my own custom dataset but only get low results like below

               Class     Images     Labels          P          R   F1-score     mAP@.5 mAP@.5:.95: 100%|██████████| 13/13 [00:11<00:00,  1.09it/s]                          
               AP@[.5:.95]:[[    0.72858     0.69841     0.66968     0.63106      0.5772     0.49648     0.40591      0.2899     0.11522   0.0067517]]
                 all        399       1081     0.8271      0.642     0.7229     0.7286     0.4619
Speed: 0.1ms pre-process, 2.1ms inference, 0.6ms NMS per image at shape (32, 3, 640, 640)

Evaluating pycocotools mAP... saving runs/val/yolov5s17/yolov5s_predictions.json...
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loading and preparing results...
DONE (t=0.01s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=0.42s).
Accumulating evaluation results...
DONE (t=0.05s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.001
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.002
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.001
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.003
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.010
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.012
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.009
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.013
Results saved to runs/val/yolov5s17

how can i get right results?

here is my instances_val.json
[instances_val2017.txt](https://github.com/ultralytics/yolov5/files/8598827/instances_val2017.txt)

here is my yolov5_prediction.json
[yolov5s_predictions.txt](https://github.com/ultralytics/yolov5/files/8598828/yolov5s_predictions.txt)

my image_id is set from 0.jpg 1.jpg...

is_coco flag in val.py is set True

`if is_coco:`
`eval.params.imgIds = [int(Path(x).stem) for x in dataloader.dataset.img_files]  # image IDs to evaluate`
comment these codes, i had ever tried but not works.

plz help me, it puzzles me for many days

### Additional

noting

**Comment by shenhaibb** [comment]
i have searched the issues and discussions before, but no works on my problem

**Comment by shenhaibb** [comment]
i also tried set is_coco False but no works either

**Comment by glenn-jocher** [comment]
@shenhaibb pycocotools evaluation is meant for use with the COCO dataset.

**Comment by SamSamhuns** [comment]
So does this mean, the pycocotools evaluator cannot be used for custom datasets even after the required modifications of the annotations.

I get similar results where the yolov5 evaluation gives mAP(iou=0.5) of 0.5 but for pycocoevaluation the mAP(iou=0.5) is very low at 0.1
![Screenshot 2023-01-12 at 11 51 15 AM](https://user-images.githubusercontent.com/13418507/212009043-9c46e39a-fd52-4843-8338-4a175d409680.png)

*Edit: Solved it. THe problem was the converted coco annotations had 1-indexed class ids while val.py generates 0 indexed class ids in the json file.

Created my own converter to help anyone in the future https://github.com/SamSamhuns/ml_data_processing/tree/master/annotation_format_conv

**Comment by Hezey** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.
> 
> ### Question
> i use my own custom dataset but only get low results like below
> 
> ```
>            Class     Images     Labels          P          R   F1-score     mAP@.5 mAP@.5:.95: 100%|██████████| 13/13 [00:11<00:00,  1.09it/s]                          
>            AP@[.5:.95]:[[    0.72858     0.69841     0.66968     0.63106      0.5772     0.49648     0.40591      0.2899     0.11522   0.0067517]]
>              all        399       1081     0.8271      0.642     0.7229     0.7286     0.4619
> ```
> 
> Speed: 0.1ms pre-process, 2.1ms inference, 0.6ms NMS per image at shape (32, 3, 640, 640)
> 
> Evaluating pycocotools mAP... saving runs/val/yolov5s17/yolov5s_predictions.json... loading annotations into memory... Done (t=0.00s) creating index... index created! Loading and preparing results... DONE (t=0.01s) creating index... index created! Running per image evaluation... Evaluate annotation type _bbox_ DONE (t=0.42s). Accumulating evaluation results... DONE (t=0.05s). Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.001 Average Precision (AP) @[ IoU=0.50 | area= all | maxDets=100 ] = 0.002 Average Precision (AP) @[ IoU=0.75 | area= all | maxDets=100 ] = 0.000 Average Precision (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000 Average Precision (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000 Average Precision (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.001 Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 1 ] = 0.003 Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 10 ] = 0.010 Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.012 Average Recall (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000 Average Recall (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.009 Average Recall (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.013 Results saved to runs/val/yolov5s17
> 
> how can i get right results?
> 
> here is my instances_val.json [instances_val2017.txt](https://github.com/ultralytics/yolov5/files/8598827/instances_val2017.txt)
> 
> here is my yolov5_prediction.json [yolov5s_predictions.txt](https://github.com/ultralytics/yolov5/files/8598828/yolov5s_predictions.txt)
> 
> my image_id is set from 0.jpg 1.jpg...
> 
> is_coco flag in val.py is set True
> 
> `if is_coco:` `eval.params.imgIds = [int(Path(x).stem) for x in dataloader.dataset.img_files] # image IDs to evaluate` comment these codes, i had ever tried but not works.
> 
> plz help me, it puzzles me for many days
> 
> ### Additional
> noting

Hello, have you solved this problem？
