### ISSUE TITLE
what's the  ''--multi-scale', action='store_true', help='vary img-size +/- 50%%'' mean?

### ISSUE THREAD

**Issue by Jad-Goh** [ultralytics/yolov5#7659]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hello, I have a question.
I don't know what's the mean of ''--multi-scale', action='store_true', help='vary img-size +/- 50%%''.
As my inputs size is 640*640, if I choose the '--multi-scale' to train ,my input change to [640×（1+/- 50%%)] × [640×（1+/- 50%%)]？
Thanks for your answer！

**Comment by glenn-jocher** [comment]
@Jad-Goh trains at various scales about your default --img-size. Not recommended.

**Comment by Jad-Goh** [comment]
thanks for your answer！

**Comment by glenn-jocher** [comment]
@Jad-Goh you're welcome! If you have any more questions, feel free to ask. Good luck with your training!

**Comment by github-yizhang** [comment]
> @Jad-Goh trains at various scales about your default --img-size. Not recommended.

hello, i want ask why it's not recommend to use multi_scale when set default --img-size. I use multi_scale in my training and mAP
drops a lot, can you please explain why not recommend. Thanks very much!
