### ISSUE TITLE
My forecast data is divided into multiple folders, how can I predict all of them at one time

### ISSUE THREAD

**Issue by clxa** [ultralytics/yolov5#766]
## ❔Question
My forecast data is divided into multiple folders, how can I predict all of them at one time

## Additional context
for i in os.listdir(img_path)[:2]:
  if i[0] == '0':
    !python detect.py --source f"./content/amap_traffic_test_0712/amap_traffic_test_0712/{i}" --weights weights/yolov5x.pt --save-txt

**Comment by clxa** [comment]
Exception: ERROR: /content/drive/My Drive/yolov5-master/f./content/amap_traffic_test_0712/amap_traffic_test_0712/000197 does not exist

**Comment by glenn-jocher** [comment]
@clxa your error message shows that you are passing a directory for inference that does not exist.

**Comment by glenn-jocher** [comment]
@clxa you can request inference on any combination of files or folders you want simply by using a regular python `glob` command. See https://github.com/ultralytics/yolov5#inference

**Comment by jurvanwijk** [comment]
I do not see how you can use the `glob` command. When trying to run separate directories with:
`--source 'inputpath/*/*.jpg'`, where the second star is the directory with all the different directories, the model is not able to loop through the directories. Any solution for this or tips on what I do wrong?

**Comment by glenn-jocher** [comment]
@jurvanwijk To predict on images in multiple subdirectories, you can use the following command:
```bash
python detect.py --source 'inputpath/**/*.jpg' --weights weights/yolov5x.pt --save-txt
```
This will recursively search for all `jpg` images in all subdirectories under `inputpath` and predict on them.
