### ISSUE TITLE
Exporting to Tensorflow

### ISSUE THREAD

**Issue by scott-lam** [ultralytics/yolov5#7663]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Trying to export my best.pt weights file to a tensorflow saved_model. When this is done, there is no keras_metadata.pb file, meaning I am unable to make predictions via the model
Luckily though, I have an older version of the YOLOv5 Repo cloned on my machine. When using this to export the model, it creates a keras_metadata.pb file for the saved_model. Why is this not being created when the most up-to-date repo? 

### Environment

Google Colab

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@scott-lam Keras export was deprecated due to file size limitations with the format in https://github.com/ultralytics/yolov5/pull/6292

**Comment by scott-lam** [comment]
@glenn-jocher how would I use the tensorflow model in my application? It's a bit late to rewrite all my code to use pytorch, is there another way that I can use it for inference via tensorflow?

**Comment by glenn-jocher** [comment]
@scott-lam TF export and inference is pretty simple. Usage examples are displayed automatically after export:

```bash
python export.py --weights yolov5s.pt --include saved_model
python detect.py --weights yolov5s_saved_model
```
