### ISSUE TITLE
Why don't you publish the paper about Yolov5?

### ISSUE THREAD

**Issue by star4s** [ultralytics/yolov5#7664]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Why don't you publish the paper about Yolov5?
I Think result of the Yolov5 is STATE-OF-THE-ART for object Detection.

**Comment by glenn-jocher** [comment]
@star4s thanks for your interest! YOLOv5 benefits hugely from the wider YOLO community and we are grateful for everyone's contributions. The YOLOv5 model is developed and maintained by Ultralytics, not as part of academic research, so no paper is planned. Have you had a chance to view our documentation for more information on YOLOv5?
