### ISSUE TITLE
mosaic ratio or stop mosaic epochs 

### ISSUE THREAD

**Issue by Jad-Goh** [ultralytics/yolov5#7667]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to set up mosaic ratio .
For  example ,I train 300 epochs ,the first 270 epochs I want to train with mosaic , and the last 30 epochs I don't want to train with mosaic .
How should I do.
I have experienced on other models ,the results shows that this way could improve the mAP.

**Comment by glenn-jocher** [comment]
@Jad-Goh there is no hyperparameter scheduling in place currently, but you might be able to use the same method here on L309 to update dataset properties:

https://github.com/ultralytics/yolov5/blob/1994ad93e431b5b0f7b66cc231511067032732cb/train.py#L305-L310

**Comment by Jad-Goh** [comment]
Although I don't understand ,thanks a lot！I have a stupid method .

**Comment by Jad-Goh** [comment]
> @Jad-Goh there is no hyperparameter scheduling in place currently, but you might be able to use the same method here on L309 to update dataset properties:
> 
> https://github.com/ultralytics/yolov5/blob/1994ad93e431b5b0f7b66cc231511067032732cb/train.py#L305-L310

Although I don't understand ,thanks a lot！I have a stupid method .

**Comment by wenjunx** [comment]
> > @Jad-Goh there is no hyperparameter scheduling in place currently, but you might be able to use the same method here on L309 to update dataset properties:
> > https://github.com/ultralytics/yolov5/blob/1994ad93e431b5b0f7b66cc231511067032732cb/train.py#L305-L310
> 
> Although I don't understand ,thanks a lot！I have a stupid method .

how do you do? I want to learn,thank you!

**Comment by wenjunx** [comment]
@Jad-Goh

**Comment by Jad-Goh** [comment]
> > > @Jad-Goh there is no hyperparameter scheduling in place currently, but you might be able to use the same method here on L309 to update dataset properties:
> > > https://github.com/ultralytics/yolov5/blob/1994ad93e431b5b0f7b66cc231511067032732cb/train.py#L305-L310
> > 
> > 
> > Although I don't understand ,thanks a lot！I have a stupid method .
> 
> how do you do? I want to learn,thank you!

很笨的一个办法，这个办法我还没有具体操作，想法是这样的：假如我要训练300个epoch，我自己手动看着，到了290个epoch的时候，我手动停止，然后手动更改run文件夹里面的opt.yaml文件的hyp路径（或者直接改这个文件的mosaic参数），然后继续训练剩下的10个epoch。

**Comment by wenjunx** [comment]
好的，谢谢你



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月6日(星期一) 下午5:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ultralytics/yolov5] mosaic ratio or stop mosaic epochs  (Issue #7667)





    
@Jad-Goh there is no hyperparameter scheduling in place currently, but you might be able to use the same method here on L309 to update dataset properties:
 https://github.com/ultralytics/yolov5/blob/1994ad93e431b5b0f7b66cc231511067032732cb/train.py#L305-L310
  
Although I don't understand ,thanks a lot！I have a stupid method .
  
how do you do? I want to learn,thank you!
  
很笨的一个办法，这个办法我还没有具体操作，想法是这样的：假如我要训练300个epoch，我自己手动看着，到了290个epoch的时候，我手动停止，然后手动更改run文件夹里面的opt.yaml文件的hyp路径（或者直接改这个文件的mosaic参数），然后继续训练剩下的10个epoch。
