### ISSUE TITLE
迁移学习时，加载自己训练的主干网络的权重文件报了NotImplementedError的错误会是什么原因

### ISSUE THREAD

**Issue by billfjj** [ultralytics/yolov5#7668]
### Search before asking

- [ ] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

(yolov5) E:\PycharmProjects\yolov5-master>python train.py --data fewshotlogodetection.yaml --weights pretrained/model.pt --freeze 10 --cfg yolov5x6.yaml
--epoch 100 --batch-size 16
train: weights=pretrained/model.pt, cfg=yolov5x6.yaml, data=fewshotlogodetection.yaml, hyp=data\hyps\hyp.scratch-low.yaml, epochs=100, batch_size=16, img
sz=640, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, evolve=None, bucket=, cache=None, image_weights=False, device=, multi_sc
ale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=8, project=runs\train, name=exp, exist_ok=False, quad=False, cos_lr=False, label_smoot
hing=0.0, patience=100, freeze=[10], save_period=-1, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest
github: skipping check (not a git repository), for updates see https://github.com/ultralytics/yolov5
fatal: not a git repository (or any of the parent directories): .git
YOLOv5  2022-4-10 torch 1.11.0 CUDA:0 (NVIDIA GeForce RTX 3080 Ti, 12288MiB)

hyperparameters: lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5,
cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0
.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0
Weights & Biases: run 'pip install wandb' to automatically track and visualize YOLOv5  runs (RECOMMENDED)
TensorBoard: Start with 'tensorboard --logdir runs\train', view at http://localhost:6006/
E:\Python\Miniconda3\envs\yolov5\lib\site-packages\torch\serialization.py:707: UserWarning: 'torch.load' received a zip file that looks like a TorchScrip
t archive dispatching to 'torch.jit.load' (call 'torch.jit.load' directly to silence this warning)
  warnings.warn("'torch.load' received a zip file that looks like a TorchScript archive"

                 from  n    params  module                                  arguments
  0                -1  1      8800  models.common.Conv                      [3, 80, 6, 2, 2]
  1                -1  1    115520  models.common.Conv                      [80, 160, 3, 2]
  2                -1  4    309120  models.common.C3                        [160, 160, 4]
  3                -1  1    461440  models.common.Conv                      [160, 320, 3, 2]
  4                -1  8   2259200  models.common.C3                        [320, 320, 8]
  5                -1  1   1844480  models.common.Conv                      [320, 640, 3, 2]
  6                -1 12  13125120  models.common.C3                        [640, 640, 12]
  7                -1  1   5531520  models.common.Conv                      [640, 960, 3, 2]
  8                -1  4  11070720  models.common.C3                        [960, 960, 4]
  9                -1  1  11061760  models.common.Conv                      [960, 1280, 3, 2]
 10                -1  4  19676160  models.common.C3                        [1280, 1280, 4]
 11                -1  1   4099840  models.common.SPPF                      [1280, 1280, 5]
 12                -1  1   1230720  models.common.Conv                      [1280, 960, 1, 1]
 13                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 14           [-1, 8]  1         0  models.common.Concat                    [1]
 15                -1  4  11992320  models.common.C3                        [1920, 960, 4, False]
 16                -1  1    615680  models.common.Conv                      [960, 640, 1, 1]
 17                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 18           [-1, 6]  1         0  models.common.Concat                    [1]
 19                -1  4   5332480  models.common.C3                        [1280, 640, 4, False]
 20                -1  1    205440  models.common.Conv                      [640, 320, 1, 1]
 21                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 22           [-1, 4]  1         0  models.common.Concat                    [1]
 23                -1  4   1335040  models.common.C3                        [640, 320, 4, False]
 24                -1  1    922240  models.common.Conv                      [320, 320, 3, 2]
 25          [-1, 20]  1         0  models.common.Concat                    [1]
 26                -1  4   4922880  models.common.C3                        [640, 640, 4, False]
 27                -1  1   3687680  models.common.Conv                      [640, 640, 3, 2]
 28          [-1, 16]  1         0  models.common.Concat                    [1]
 29                -1  4  11377920  models.common.C3                        [1280, 960, 4, False]
 30                -1  1   8296320  models.common.Conv                      [960, 960, 3, 2]
 31          [-1, 12]  1         0  models.common.Concat                    [1]
 32                -1  4  20495360  models.common.C3                        [1920, 1280, 4, False]
nl 4
 33  [23, 26, 29, 32]  1    528660  models.yolo.Detect                      [50, [[19, 27, 44, 40, 38, 94], [96, 68, 86, 152, 180, 137], [140, 301, 303,
264, 238, 542], [436, 615, 739, 380, 925, 792]], [320, 640, 960, 1280]]
YOLOv5x6 summary: 733 layers, 140506420 parameters, 140506420 gradients, 209.4 GFLOPs

freezing model.0.conv.weight
freezing model.0.bn.weight
freezing model.0.bn.bias
freezing model.1.conv.weight
freezing model.1.bn.weight
freezing model.1.bn.bias
freezing model.2.cv1.conv.weight
freezing model.2.cv1.bn.weight
freezing model.2.cv1.bn.bias
freezing model.2.cv2.conv.weight
freezing model.2.cv2.bn.weight
freezing model.2.cv2.bn.bias
freezing model.2.cv3.conv.weight
freezing model.2.cv3.bn.weight
freezing model.2.cv3.bn.bias
freezing model.2.m.0.cv1.conv.weight
freezing model.2.m.0.cv1.bn.weight
freezing model.2.m.0.cv1.bn.bias
freezing model.2.m.0.cv2.conv.weight
freezing model.2.m.0.cv2.bn.weight
freezing model.2.m.0.cv2.bn.bias
freezing model.2.m.1.cv1.conv.weight
freezing model.2.m.1.cv1.bn.weight
freezing model.2.m.1.cv1.bn.bias
freezing model.2.m.1.cv2.conv.weight
freezing model.2.m.1.cv2.bn.weight
freezing model.2.m.1.cv2.bn.bias
freezing model.2.m.2.cv1.conv.weight
freezing model.2.m.2.cv1.bn.weight
freezing model.2.m.2.cv1.bn.bias
freezing model.2.m.2.cv2.conv.weight
freezing model.2.m.2.cv2.bn.weight
freezing model.2.m.2.cv2.bn.bias
freezing model.2.m.3.cv1.conv.weight
freezing model.2.m.3.cv1.bn.weight
freezing model.2.m.3.cv1.bn.bias
freezing model.2.m.3.cv2.conv.weight
freezing model.2.m.3.cv2.bn.weight
freezing model.2.m.3.cv2.bn.bias
freezing model.3.conv.weight
freezing model.3.bn.weight
freezing model.3.bn.bias
freezing model.4.cv1.conv.weight
freezing model.4.cv1.bn.weight
freezing model.4.cv1.bn.bias
freezing model.4.cv2.conv.weight
freezing model.4.cv2.bn.weight
freezing model.4.cv2.bn.bias
freezing model.4.cv3.conv.weight
freezing model.4.cv3.bn.weight
freezing model.4.cv3.bn.bias
freezing model.4.m.0.cv1.conv.weight
freezing model.4.m.0.cv1.bn.weight
freezing model.4.m.0.cv1.bn.bias
freezing model.4.m.0.cv2.conv.weight
freezing model.4.m.0.cv2.bn.weight
freezing model.4.m.0.cv2.bn.bias
freezing model.4.m.1.cv1.conv.weight
freezing model.4.m.1.cv1.bn.weight
freezing model.4.m.1.cv1.bn.bias
freezing model.4.m.1.cv2.conv.weight
freezing model.4.m.1.cv2.bn.weight
freezing model.4.m.1.cv2.bn.bias
freezing model.4.m.2.cv1.conv.weight
freezing model.4.m.2.cv1.bn.weight
freezing model.4.m.2.cv1.bn.bias
freezing model.4.m.2.cv2.conv.weight
freezing model.4.m.2.cv2.bn.weight
freezing model.4.m.2.cv2.bn.bias
freezing model.4.m.3.cv1.conv.weight
freezing model.4.m.3.cv1.bn.weight
freezing model.4.m.3.cv1.bn.bias
freezing model.4.m.3.cv2.conv.weight
freezing model.4.m.3.cv2.bn.weight
freezing model.4.m.3.cv2.bn.bias
freezing model.4.m.4.cv1.conv.weight
freezing model.4.m.4.cv1.bn.weight
freezing model.4.m.4.cv1.bn.bias
freezing model.4.m.4.cv2.conv.weight
freezing model.4.m.4.cv2.bn.weight
freezing model.4.m.4.cv2.bn.bias
freezing model.4.m.5.cv1.conv.weight
freezing model.4.m.5.cv1.bn.weight
freezing model.4.m.5.cv1.bn.bias
freezing model.4.m.5.cv2.conv.weight
freezing model.4.m.5.cv2.bn.weight
freezing model.4.m.5.cv2.bn.bias
freezing model.4.m.6.cv1.conv.weight
freezing model.4.m.6.cv1.bn.weight
freezing model.4.m.6.cv1.bn.bias
freezing model.4.m.6.cv2.conv.weight
freezing model.4.m.6.cv2.bn.weight
freezing model.4.m.6.cv2.bn.bias
freezing model.4.m.7.cv1.conv.weight
freezing model.4.m.7.cv1.bn.weight
freezing model.4.m.7.cv1.bn.bias
freezing model.4.m.7.cv2.conv.weight
freezing model.4.m.7.cv2.bn.weight
freezing model.4.m.7.cv2.bn.bias
freezing model.5.conv.weight
freezing model.5.bn.weight
freezing model.5.bn.bias
freezing model.6.cv1.conv.weight
freezing model.6.cv1.bn.weight
freezing model.6.cv1.bn.bias
freezing model.6.cv2.conv.weight
freezing model.6.cv2.bn.weight
freezing model.6.cv2.bn.bias
freezing model.6.cv3.conv.weight
freezing model.6.cv3.bn.weight
freezing model.6.cv3.bn.bias
freezing model.6.m.0.cv1.conv.weight
freezing model.6.m.0.cv1.bn.weight
freezing model.6.m.0.cv1.bn.bias
freezing model.6.m.0.cv2.conv.weight
freezing model.6.m.0.cv2.bn.weight
freezing model.6.m.0.cv2.bn.bias
freezing model.6.m.1.cv1.conv.weight
freezing model.6.m.1.cv1.bn.weight
freezing model.6.m.1.cv1.bn.bias
freezing model.6.m.1.cv2.conv.weight
freezing model.6.m.1.cv2.bn.weight
freezing model.6.m.1.cv2.bn.bias
freezing model.6.m.2.cv1.conv.weight
freezing model.6.m.2.cv1.bn.weight
freezing model.6.m.2.cv1.bn.bias
freezing model.6.m.2.cv2.conv.weight
freezing model.6.m.2.cv2.bn.weight
freezing model.6.m.2.cv2.bn.bias
freezing model.6.m.3.cv1.conv.weight
freezing model.6.m.3.cv1.bn.weight
freezing model.6.m.3.cv1.bn.bias
freezing model.6.m.3.cv2.conv.weight
freezing model.6.m.3.cv2.bn.weight
freezing model.6.m.3.cv2.bn.bias
freezing model.6.m.4.cv1.conv.weight
freezing model.6.m.4.cv1.bn.weight
freezing model.6.m.4.cv1.bn.bias
freezing model.6.m.4.cv2.conv.weight
freezing model.6.m.4.cv2.bn.weight
freezing model.6.m.4.cv2.bn.bias
freezing model.6.m.5.cv1.conv.weight
freezing model.6.m.5.cv1.bn.weight
freezing model.6.m.5.cv1.bn.bias
freezing model.6.m.5.cv2.conv.weight
freezing model.6.m.5.cv2.bn.weight
freezing model.6.m.5.cv2.bn.bias
freezing model.6.m.6.cv1.conv.weight
freezing model.6.m.6.cv1.bn.weight
freezing model.6.m.6.cv1.bn.bias
freezing model.6.m.6.cv2.conv.weight
freezing model.6.m.6.cv2.bn.weight
freezing model.6.m.6.cv2.bn.bias
freezing model.6.m.7.cv1.conv.weight
freezing model.6.m.7.cv1.bn.weight
freezing model.6.m.7.cv1.bn.bias
freezing model.6.m.7.cv2.conv.weight
freezing model.6.m.7.cv2.bn.weight
freezing model.6.m.7.cv2.bn.bias
freezing model.6.m.8.cv1.conv.weight
freezing model.6.m.8.cv1.bn.weight
freezing model.6.m.8.cv1.bn.bias
freezing model.6.m.8.cv2.conv.weight
freezing model.6.m.8.cv2.bn.weight
freezing model.6.m.8.cv2.bn.bias
freezing model.6.m.9.cv1.conv.weight
freezing model.6.m.9.cv1.bn.weight
freezing model.6.m.9.cv1.bn.bias
freezing model.6.m.9.cv2.conv.weight
freezing model.6.m.9.cv2.bn.weight
freezing model.6.m.9.cv2.bn.bias
freezing model.6.m.10.cv1.conv.weight
freezing model.6.m.10.cv1.bn.weight
freezing model.6.m.10.cv1.bn.bias
freezing model.6.m.10.cv2.conv.weight
freezing model.6.m.10.cv2.bn.weight
freezing model.6.m.10.cv2.bn.bias
freezing model.6.m.11.cv1.conv.weight
freezing model.6.m.11.cv1.bn.weight
freezing model.6.m.11.cv1.bn.bias
freezing model.6.m.11.cv2.conv.weight
freezing model.6.m.11.cv2.bn.weight
freezing model.6.m.11.cv2.bn.bias
freezing model.7.conv.weight
freezing model.7.bn.weight
freezing model.7.bn.bias
freezing model.8.cv1.conv.weight
freezing model.8.cv1.bn.weight
freezing model.8.cv1.bn.bias
freezing model.8.cv2.conv.weight
freezing model.8.cv2.bn.weight
freezing model.8.cv2.bn.bias
freezing model.8.cv3.conv.weight
freezing model.8.cv3.bn.weight
freezing model.8.cv3.bn.bias
freezing model.8.m.0.cv1.conv.weight
freezing model.8.m.0.cv1.bn.weight
freezing model.8.m.0.cv1.bn.bias
freezing model.8.m.0.cv2.conv.weight
freezing model.8.m.0.cv2.bn.weight
freezing model.8.m.0.cv2.bn.bias
freezing model.8.m.1.cv1.conv.weight
freezing model.8.m.1.cv1.bn.weight
freezing model.8.m.1.cv1.bn.bias
freezing model.8.m.1.cv2.conv.weight
freezing model.8.m.1.cv2.bn.weight
freezing model.8.m.1.cv2.bn.bias
freezing model.8.m.2.cv1.conv.weight
freezing model.8.m.2.cv1.bn.weight
freezing model.8.m.2.cv1.bn.bias
freezing model.8.m.2.cv2.conv.weight
freezing model.8.m.2.cv2.bn.weight
freezing model.8.m.2.cv2.bn.bias
freezing model.8.m.3.cv1.conv.weight
freezing model.8.m.3.cv1.bn.weight
freezing model.8.m.3.cv1.bn.bias
freezing model.8.m.3.cv2.conv.weight
freezing model.8.m.3.cv2.bn.weight
freezing model.8.m.3.cv2.bn.bias
freezing model.9.conv.weight
freezing model.9.bn.weight
freezing model.9.bn.bias
Scaled weight_decay = 0.0005
optimizer: SGD with parameter groups 159 weight (no decay), 163 weight, 163 bias
Traceback (most recent call last):
  File "train.py", line 643, in <module>
    main(opt)
  File "train.py", line 536, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 189, in train
    if ckpt['optimizer'] is not None:
  File "E:\Python\Miniconda3\envs\yolov5\lib\site-packages\torch\jit\_script.py", line 817, in __getitem__
    return self.forward_magic_method("__getitem__", idx)
  File "E:\Python\Miniconda3\envs\yolov5\lib\site-packages\torch\jit\_script.py", line 810, in forward_magic_method
    raise NotImplementedError()
NotImplementedError

**Comment by glenn-jocher** [comment]
@billfjj 你好！感谢你的提问。根据你的描述，加载自己训练的主干网络权重文件时出现了NotImplementedError错误。在我看来，这个错误可能是由于训练配置或代码中的一些问题导致的。我建议你确保您的训练配置和代码没有任何问题，并且确认你的训练数据、模型配置和预训练权重文件是兼容的。此外，你也可以参考[官方文档](https://docs.ultralytics.com/yolov5/)，查找关于迁移学习的更多信息。希望这能对你有所帮助！🚀
