### ISSUE TITLE
How to increase Bounding box thickness, Label text size in output?

### ISSUE THREAD

**Issue by shiv-acharii** [ultralytics/yolov5#7670]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How do we increase the Bounding box thickness and the Label text size in the output?

- I have trained my model on 640*640.
- But testing on the image of size 1540*1540

the detection is accurate, **_but the thickness and font size of the label text is very small, how do I increase it?_**

**Comment by glenn-jocher** [comment]
@shivprasad94 you can modify the Annotator class properties here. You might get better looking labels with PIL=True also.
https://github.com/ultralytics/yolov5/blob/bff6e51bc4894ffc4da8b202718023f80d8bdc44/detect.py#L148
