### ISSUE TITLE
How to save metric per class as a file when training?

### ISSUE THREAD

**Issue by changduckGO** [ultralytics/yolov5#7671]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

![figure](https://user-images.githubusercontent.com/62056652/166216375-8c2eba4e-6a39-4f35-ba4d-94fd24959b6d.jpg)

How Can I save metric(precision, recall, mAP etc.) per class as a file when training? 
I couldn't find code that calculate the metric per class in this repository.

Thank you for reading.

**Comment by glenn-jocher** [comment]
@changduckGO per-class metrics are not logged, but they are available here:
https://github.com/ultralytics/yolov5/blob/bff6e51bc4894ffc4da8b202718023f80d8bdc44/val.py#L279-L283

**Comment by changduckGO** [comment]
Thank you for your prompt response !!
Have a good day 😄😄

**Comment by glenn-jocher** [comment]
@changduckGO you're welcome! Have a great day too! 😄😄 If you have any more questions, feel free to ask.
