### ISSUE TITLE
AttributeError: Can't get attribute 'StemBlock' on <module 'models.common' from '/yolov5/models/common.py'>

### ISSUE THREAD

**Issue by imohammadhossein** [ultralytics/yolov5#7672]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

I get this error ever once I wanna load the model. tested on both (yolo5s, yolo5m).

AttributeError: Can't get attribute 'StemBlock' on <module 'models.common' from '/yolov5/models/common.py'>

### Minimal Reproducible Example

python3 export.py --weights ../test_models/yolov5s-face.pt --include onnx

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by imohammadhossein** [comment]
I have completely installed yolov5 successfully.
sample running scripts:
```
python3 export.py --weights yolov5s-face.pt --include onnx
python3 yolov5/detect.py --weights yolov5m-face.pt 
```

**Comment by imohammadhossein** [comment]
fixed. you need to use yolo5-face repo.

**Comment by btlam87** [comment]
> fixed. you need to use yolo5-face repo.

Hi, i got this error. Can you give me detail (a link ) about yolo5-face repo.Thanks

**Comment by imohammadhossein** [comment]
> > fixed. you need to use yolo5-face repo.
> 
> Hi, i got this error. Can you give me detail (a link ) about yolo5-face repo.Thanks

Sure. [yolo-face](https://github.com/deepcam-cn/yolov5-face.git)

**Comment by glenn-jocher** [comment]
@imohammadhossein you are correct, you need to use the yolo5-face repository if you are working with face-specific YOLOv5 models. You can find the repository at https://github.com/deepcam-cn/yolov5-face.git. Let me know if you need further assistance!
