### ISSUE TITLE
Memory consumption is very high during inference

### ISSUE THREAD

**Issue by Piyushak** [ultralytics/yolov5#7676]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I have two computers having different configurations which are following:
**Computer 1:**
OS - Ubuntu 20.04
GPU- NVIDIA GeForce GTX 1050 Ti
RAM- 4GB

**Computer 2:**
OS - Ubuntu 20.04
GPU- NVIDIA GeForce RTX 3090
RAM- 24GB

I'm running yolov5x6 on both computers having the same files and setup and the source is youtube live streaming (same streaming in both). But in **computer 1 (4GB RAM)** the memory consumption is **3169MiB** during inference while in **computer 2 (24GB RAM)** the memory consumption is **15809MiB** during inference which is quite high. Is it due to a different GPU configuration or something else? How to reduce or optimize the memory consumption during inference since the memory cost is too much? I am ready to compromise with the frame rate. In this case, can we control the input frame rate, if yes, then how and will it be impact on the memory consumption during detection?

**Comment by glenn-jocher** [comment]
@Piyushak resource utilization may vary among hardware, software, drivers, background tasks running, etc. I can't provide much more information than that.

**Comment by Piyushak** [comment]
Is there any possible way to minimize/optimize resource utilization in yolov5? Can we slow the inference speed for minimizing resource utilization?

**Comment by glenn-jocher** [comment]
@Piyushak YOLOv5 is obviously designed to maximize resource utilization where possible for the fastest possible results, like all AI models. If you want to constrain resources you can launch a Docker image with reduced resource constraints and run YOLO there.

**Comment by Vijay-P1999** [comment]
@glenn-jocher Quick question, 
I noticed there are more for loops in `detect.py`. Is there any way to optimize/refactor that?

**Comment by glenn-jocher** [comment]
@Vijay-P1999 hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
