### ISSUE TITLE
How to use GPU on Windows 10?

### ISSUE THREAD

**Issue by jeannotdamoiseaux** [ultralytics/yolov5#7681]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm running the latest YOLOv5 on Windows 10 Enterprise, but it utilizes my CPU (Intel) instead of the GPU (NVIDIA Quadro). I'm executing the training process from the Windows PowerShell with the following packages and versions:

Python 3.10.2
CUDA 11.2
CUDNN 8.1
All packages in requirements.txt are "already satisfied"

What should I do to enable training via the GPU?

**Comment by jeannotdamoiseaux** [comment]
In my case, the training was executed on the CPU instead of GPU due to versioning issue with PyTorch. My existing PyTorch (1.11.0+cpu) cannot utilize the CPU. Therefore I used the line underneath to uninstall PyTorch. 
`pip uninstall torch`
Thereafter, I installed a newer version of CUDA (11.3), which facilitates PyTorch to utilize the GPU.
Then, I used the following line to install a GPU capable version of PyTorch (based on https://pytorch.org/).
`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113`

**Comment by glenn-jocher** [comment]
@jeannot-github great to hear that you resolved the issue! PyTorch version compatibility is indeed crucial for GPU utilization with YOLOv5. Your successful installation of a GPU-capable PyTorch version and updated CUDA is the correct approach. Thank you for sharing your solution! If you encounter any more issues, feel free to ask. Good luck with your YOLOv5 training!
