### ISSUE TITLE
Train too slow on yolov5-6.1 with no Tensor Core GPU

### ISSUE THREAD

**Issue by Etern213** [ultralytics/yolov5#7687]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

@glenn-jocher Finally, I found a problem that will cause train too slow on yolov5-6.1 with no Tensor Core GPU. Just as I guessed, AMP is the reason.

NVIDIA said 16 GPU(such as 1650, 1660, 1650ti, 1660ti) don't have tensor core, which Mixed precision(AMP) need to use. However, My GPU is 1660ti, so I tried to disable AMP and try again.

The fact is that I change `with amp.autocast(enabled=cuda):` to `with amp.autocast(enabled=False):`, and all problems solved. Here I make a brief summary of all I have tried, hope these can help you find the bug:

My GPU is **NVIDIA GeForce GTX 1660 Ti**, **6144MiB**, with **80W** maximum power. **Batch-size** are set to **8** in these tests. And dataset is **COCO2017**, model is **yolov5m.yaml**. All other arguments are same in these tests.

1) case `with amp.autocast(enabled=cuda):`   **(YoloV5-6.0 and YoloV5-6.1)**
**result:**
GPU average power use: 50W **(too low:rotating_light:)**
train speed: about 3-4 s/it **(too slow:rotating_light:)**
GPU memory use: about 3-4 G **(normal✅)**

2) case `with amp.autocast(enabled=False):`   **(YoloV5-6.0 and YoloV5-6.1)**
**result:**
GPU average power use: 80W **(normal✅)**
train speed: about 1.5-2 it/s **(normal✅)**
GPU memory use: about 5.5 G **(too high:rotating_light:)**

3) case `with amp.autocast(enabled=cuda):`   **(YoloV5-5.0)**
**result:**
GPU average power use: 80W **(normal✅)**
train speed: about 1.8-2.2 it/s **(normal✅)**
GPU memory use: about 3-3.2 G **(normal✅)**

According to these information, training speed in case 2 is almost same as case 3, so it seems that the problem is **YoloV5-6.0/6.1 is not compatible with GPU that has no tensor core.** Just as you said, train speed on YoloV5-6.0/6.1 is normal with Tesla GPU in Google Colab, because Tesla GPU have tensor core, but other GPU may not have.

However, I checked the code in YoloV5-5.0, it set AMP to true, `with amp.autocast(enabled=cuda)`, why YoloV5-5.0 can trained normally on GPU with no tensor core when AMP is set to true, but YoloV5-6.0/6.1 can't? Just like case 2 compared with case 3, YoloV5-5.0 have quicker training speed and lower memory usage than YoloV5-6.0/6.1.

### Environment

OS: Windows 11
Yolo version: YoloV5-5.0, YoloV5-6.0, YoloV5-6.1
Pytorch: 1.10.0+cu102
GPU: **NVIDIA GeForce GTX 1660 Ti**, **6144MiB**, with **80W** maximum power.

### Minimal Reproducible Example

Just set `with amp.autocast(enabled=cuda):` in train.py, and train a datasets on a no tensor core GPU, and this bug reproduce.

Disable AMP and train again, problem solved.

Enable AMP and train on YoloV5-5.0, problem did not occurred

further information are above.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Etern213** [comment]
@glenn-jocher So, Ultralytics do not solve problem that occurred on own private GPU?

**Comment by glenn-jocher** [comment]
@Etern213 I'm sorry I don't know what we can do. We don't control AMP, if the problem originates there then this is an issue for pytorch. We already supply official environments and images, i.e. our Docker image if you want to train locally in a verified environment.

**Comment by Etern213** [comment]
@glenn-jocher 
Both YoloV5-5.0 and 6.0 use AMP like below, But YoloV5-5.0 don't have train speed problem, So I don't think it is an issue for pytorch.
```
 # Forward 
 with amp.autocast(enabled=cuda): 
     pred = model(imgs)  # forward 
     loss, loss_items = compute_loss(pred, targets.to(device))  # loss scaled by batch_size 
     if RANK != -1: 
         loss *= WORLD_SIZE  # gradient averaged between devices in DDP mode 
     if opt.quad: 
         loss *= 4. 
```
There must be some other changes about AMP between 5.0 and 6.0 cause this problem.

I think, If YoloV5 wants to be a full-fledged algorithm, private GPU must be considered.

**Comment by glenn-jocher** [comment]
@Etern213 ok. The first step then is to reproduce this bug in a common environment, i.e. the Docker image since you want to use local hardware. If you can reproduce there then there must be a problem. Otherwise we can't tell if the issue is your environment. The Docker quickstart guide is here: https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/

**Comment by songtf525** [comment]
Do you have a better conclusion now? for this latest sourcecode, the training is 3s/iter, but which used to be 3iter/s. I have tried many version of cuda and pytorch, but this problem still exists.
GPU: 3090
Torch:1.11
cuda:11.3

**Comment by glenn-jocher** [comment]
@songtf525 👋 Hello! Thanks for asking about **training speed issues**. YOLOv5 🚀 can be trained on CPU (slowest), [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) (fastest). If you would like to increase your training speed some options are:

- Increase `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s
- Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) DDP at larger `--batch-size`
- Train on cached data: `python train.py --cache` (RAM caching) or `--cache disk` (disk caching)
- Train on faster GPUs, i.e.: P100 -> V100 -> A100
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

Good luck 🍀 and let us know if you have any other questions!

**Comment by Etern213** [comment]
> Do you have a better conclusion now? for this latest sourcecode, the training is 3s/iter, but which used to be 3iter/s. I have tried many version of cuda and pytorch, but this problem still exists. GPU: 3090 Torch:1.11 cuda:11.3

Sorry, I don't have a better conclusion for this problem. Since that I am preparing for my Postgraduate entrance examination, so I don't have time for this.
What I already know is that people with graphic cards other than Tesla GPU might have this question, and disable "pytorch AMP" can make training speed normal. But pytorch will use more momery when AMP disabled.

What makes me confused is that yolov5-5.0 also use pytorch AMP, but version 5.0 don't have training speed problem. So, if you want to solve this problem, there is a way: try every commit between yolov5-5.0 and yolov5-6.0, there must be a commit that cause this problem.

Maybe I'll do it later, when I have time!💯

**Comment by glenn-jocher** [comment]
@Etern213 to add to this you can use the midpoint method, i.e. pick the midpoint commit and test it, then if it works pick the midpoint between that and master, etc. to find the cause. You can get a comparison here:
https://github.com/ultralytics/yolov5/compare/v5.0...master
