### ISSUE TITLE
TF conversion of future candidate YOLOv5 layers

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/yolov5#7689]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

@zldrobit we have a few potential updates to YOLOv5 that are based on different types of convolutions not currently supported in tf.py (export to all other formats works well, just TF is missing). I started trying to create new modules in tf.py to support these upcoming layers, and on closer inspection it appears this may not be very simple.

In particular the three new operators that the future layers may need are depthwise-ConvTranspose2d, Conv2d with rectangular kernels i.e. (1,3) and (3,1), and just normal depthwise Conv2d.

It looks like they are all exportable as tf.keras layers here https://www.tensorflow.org/api_docs/python/tf/keras/layers except for the depthwise-ConvTranspose2d? If so could you help create versions of these in tf.py?

The depthwsie-ConvTranspose2d would replace the nn.Upsample() layers, i.e. in model.yaml to upsample from P3 to P4 (same input/output shape as current Upsample):

```diff
-   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
+   [-1, 1, nn.ConvTranspose2d, [512, 4, 2, 1, 0, 512]],
```

### Additional

- ConvTranspose2d experiments (depthwise and groups=1): https://github.com/ultralytics/yolov5/issues/7520
- CrossConv2d experiments: C3 module with CrossConv in https://github.com/ultralytics/yolov5/blob/d4d688ce2b468f72e9c4b31fc899c371590fea23/models/common.py#L316-L329 CrossConv() with rectangular kernels in https://github.com/ultralytics/yolov5/blob/d4d688ce2b468f72e9c4b31fc899c371590fea23/models/experimental.py#L15-L27
- DWConv in https://github.com/ultralytics/yolov5/blob/c4cb7c684ad6baf4081eb59ee1c27aa97bed4ebe/models/common.py#L53-L57

**Comment by zldrobit** [comment]
@glenn-jocher Thanks for letting me know the new change. I have done some experiments with depthwise convolutions in TF exports. They don't seem to be export-friendly. I'll try to do some experiments with the newer version of TensorFlow and update this issue once I get progress.

**Comment by glenn-jocher** [comment]
@zldrobit thanks for looking into this! The only possible implementation I found for a TF DWConvTranspose2D() is here:
https://github.com/tensorflow/tensorflow/issues/12001#issuecomment-822746500

**Comment by glenn-jocher** [comment]
@zldrobit do you think the PyTorch > ONNX > TF route might make sense here? The PyTorch Depthwise Conv2dTranspose() modules export well to ONNX:
<img width="1418" alt="Screen Shot 2022-05-07 at 12 47 51 AM" src="https://user-images.githubusercontent.com/26833433/167244610-51afcfac-f0b2-4680-a1d8-5a1db46dddcf.png">

**Comment by zldrobit** [comment]
@glenn-jocher I could confirm that the YOLOv5l dw-deconv can be exported to an ONNX model. After converting the ONNX model to a TensorFlow/TFLite model, two extra transpose ops are introduced before and after every convolution.

<img src="https://user-images.githubusercontent.com/3896992/167462350-4894556e-916c-4a43-a44d-45b9742bc297.gif" height="600">

It seems that onnx-tensorflow (TensorFlow/TFLite) doesn't optimize dw-deconv ops, and it generates a huge amount of TransposeConv ops. I am worried about the inference performance, but I don't have an Android phone at hand. Once I get an Android phone, I will test the performance with the YOLOv5l dw-deconv model.

![image](https://user-images.githubusercontent.com/3896992/167464252-89aed9ff-9d4a-4124-96ac-8cc3314f6431.png)

**Comment by glenn-jocher** [comment]
@zldrobit that's interesting. This seems to show that a DWConv2dTranspose can be reproduced by the 4 ops shown: (pad > transpose > Conv2d > transpose). I didn't realize that was the case. 

But I'm confused, how did you create the first good model and how did you create the second bad one?

EDIT: Oh nevermind, I understand the problem now. The 4 ops in the first picture replace the 1 normal Conv2d. That's very bad, and the second image shows the same model with one TransposeConv per channel to make it depthwise. Yeah this model is unusable. Ok we'll have to think more about this.

**Comment by glenn-jocher** [comment]
@zldrobit I got it, I thought of a solution!!! Here it is:

1. I include the DWTransposeConv2d() layers in the v7.0 release PyTorch models.
2. We use the tf.py ops to build the TF models, creating a custom TFTransposeConv2d() layer that accepts the PyTorch DWTransposeConv2d() weights and **tiles them along the channel dimension** to produce the **same mathematical result**!! This way we use the existing https://www.tensorflow.org/api_docs/python/tf/keras/layers/Conv2DTranspose module and it acts as if groups=1. There will be some model size increase for the TF variants, but the exported models will work nearly as well as the PyTorch versions.

EDIT: we probably want to use `.expand()`
https://pytorch.org/docs/stable/generated/torch.Tensor.expand.html#torch.Tensor.expand, i.e. `weight.expand(-1, num_channels, -1, -1)`

**Comment by zldrobit** [comment]
@glenn-jocher Thanks for sharing the new progress about YOLOv5.  I am sure that the solution in 2 is mathematically correct, though it introduce lots of Conv2DTranpose ops, one for each input channel. So, we may have to examine the converted TF models  for speed and size. Moreover,  we may have to examine the TFLite/Edge TPU/tf.js compatibility with  Conv2DTranpose ops as well.

**Comment by glenn-jocher** [comment]
@zldrobit oh but I thought we could build the TF model from scratch using tf.py with a new module from https://www.tensorflow.org/api_docs/python/tf/keras/layers/Conv2DTranspose. The main idea is to expand the PyTorch weights so they are no longer depthwise when they go into the TF model. i.e. if the PyTorch weights are 1,4,4 we expand them to match the channel count, i.e. 128,4,4. Then weights are suitable for the keras Conv2DTranspose module. No more depthwise on the TF side.

**Comment by zldrobit** [comment]
@glenn-jocher Ah, I see. This method simulates a depth-wise Conv2DTranpose using a Conv2DTranpose with groups=1. E.g. Each convolution in Conv2DTranpose has 127-channel zero weights and only one-channel non-zero weights. There exists only one Conv2DTranpose op for each PyTorch DWTransposeConv2d().

**Comment by glenn-jocher** [comment]
@zldrobit yes, but none of the weights are zero, each of the 128 groups just uses the same weights as the 1 DWConv group. I think this is mathematically equal. I'll try to come up with a reproducible example in PyTorch to show what I'm talking about.

**Comment by glenn-jocher** [comment]
@zldrobit nevermind, it looks like it may not be possible. I thought these two convolutions would match, but they don't, they are different.

```python
import torch
import torch.nn as nn


m = nn.Conv2d(128, 128, 3, 2, groups=1)
m_dw = nn.Conv2d(128, 128, 3, 2, groups=128)
print(m.weight.shape, m_dw.weight.shape)

m.bias = torch.nn.Parameter(m_dw.bias)
weight = torch.zeros_like(m.weight)
weight[:,0:1] = m_dw.weight
m.weight = torch.nn.Parameter(weight)

x = torch.rand(16,128,40,40)
print((m(x) - m_dw(x)))  # non-zero result
```
