### ISSUE TITLE
How to get "results.csv"?

### ISSUE THREAD

**Issue by ccm516** [ultralytics/yolov5#7690]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When I run val.py, I want to get results.csv.
As results.csv comes out when you run train.py

i guess it seems #6488, #6853 question....i don't know how to solve

how to export results.csv? when val.py is run. or **how to export PR raw data?**

**Comment by glenn-jocher** [comment]
@ccm516 train.py creates results.csv, adding a row after each epoch.
