### ISSUE TITLE
AssertionError: Label class 79 exceeds nc=16 in flir.yaml. 

### ISSUE THREAD

**Issue by sjinch** [ultralytics/yolov5#7692]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm trying to train my own datasets of which classs number is 16 as below.
![Screenshot from 2022-05-04 15-32-39](https://user-images.githubusercontent.com/103193477/166632884-d089106e-2441-448d-a82d-dc48afa366b2.png)
And also I changed models/yolov5x.yaml from nc=80 to nc=16
![Screenshot from 2022-05-04 15-33-00](https://user-images.githubusercontent.com/103193477/166632938-f9e59eca-b6a7-4b9d-bb7c-8abb478e0eff.png)
But even if changed the number of nc in both my data yaml file and model yaml file,
It causes this error.
![Screenshot from 2022-05-04 15-32-18](https://user-images.githubusercontent.com/103193477/166633025-fdef3c14-99b2-4cbf-b23a-b50053426333.png)
How can I solve it?

**Comment by glenn-jocher** [comment]
@sjinch your txt label files contain classes as high as 79

**Comment by sjinch** [comment]
> 

But I made my own .txt file using Python so there wouldn't be any mistake. What's weird is that error message keeps saying that number of classes is 80 which is default value of yolov5x.yaml even though I changed it...

**Comment by glenn-jocher** [comment]
@sjinch user error. Your dataset contains labels up to index 79, max you can have is 15 as the error message states.

**Comment by sjinch** [comment]
> @sjinch user error. Your dataset contains labels up to index 79, max you can have is 15 as the error message states.

When I looked into the train.py code, you are right. It gets 79 from my data txt file. Thanks!
