### ISSUE TITLE
How to use a past version of yolov5 

### ISSUE THREAD

**Issue by KTBE** [ultralytics/yolov5#7693]
Hi

I am trying to use an older version of yolov5 (release 4 or 5 instead of 6.1). 
Is there any way to do that?

**Comment by MarvinZhong** [comment]
you can just download the past model from [here](https://github.com/ultralytics/yolov5/releases), 
and load the model as custom,
`model = torch.hub.load('ultralytics/yolov5', 'custom', path='path/model.pt', force_reload=True)`

**Comment by KTBE** [comment]
Thanks for your reply. 

I wanted to train my own model with a previous version of yolov5 (release 4).
What I finally did :
-Download the release 4 and store it locally (google drive in order to use colab for training).
-Then I add the SPPF to common.py
-And I trained my model.

Let me know if my procedure is not good. Thanks.

**Comment by glenn-jocher** [comment]
@KTBE that's a great approach! Training a custom model with a previous release of YOLOv5 involves downloading the desired release, modifying the code if necessary, and training your model. Your method is correct, and it's fantastic to see the YOLO community adapting YOLOv5 to their specific needs. If you encounter any issues or need further assistance, feel free to ask. Good luck with your training!

**Comment by DrukSonam** [comment]
How do I download yolov8 source code? I was using yolov8.1.34. Please help.

**Comment by pderrenger** [comment]
@DrukSonam you can download YOLOv8 source code from the [Ultralytics repository](https://github.com/ultralytics/ultralytics) - either clone the repo or download a specific release from the releases page, then install with `pip install -e .` for development mode.
