### ISSUE TITLE
How to reduce predicted label font size.

### ISSUE THREAD

**Issue by shashankrajput-iitk** [ultralytics/yolov5#7695]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How do i reduce the size of the predicted label and confidence score. I have tried the potential solutions provided but couldn't do it. Can anyone help what changes do I make to make the font size=3
![val_batch0_pred](https://user-images.githubusercontent.com/72705901/166671816-0c539f88-1159-4a65-82b9-01b7a7576e22.jpg)

**Comment by glenn-jocher** [comment]
@Shanky71 Annotator class responsible for box plotting is here:
https://github.com/ultralytics/yolov5/blob/c4cb7c684ad6baf4081eb59ee1c27aa97bed4ebe/utils/plots.py#L68-L126

**Comment by shashankrajput-iitk** [comment]
@glenn-jocher  Hey I am actually a bit new to it. Can you help me in modifying the above code snippet. I tried modifying it from my end but ended up getting the same label font size. 
Tried modifying the annotator class but couldn't decrease the size yet. Can someone suggest why it's happening?

**Comment by glenn-jocher** [comment]
Hey @Shanky71! Happy to help. You can modify the font size for the predicted label and confidence score directly in the `plots.py` file in the YOLOv5 repository. You can find these parameters in the `plot_one_box` function within the `Annotator` class. Look for the `font` parameter in the `plot_one_box` function and modify the font size there to achieve the desired label font size. Let me know if you need any further assistance!

**Comment by wrss2** [comment]
I dont see plot_one_box  function in plots.py or any where else

**Comment by glenn-jocher** [comment]
@wrss2 apologies for the confusion. To adjust the font size, you should look for the `cv2.putText()` function calls within the `Annotator` class in `utils/plots.py`. The font size is controlled by the `fontScale` parameter in `cv2.putText()`. To change the font size to 3, you would set `fontScale=3` in the relevant `cv2.putText()` calls.

If you're having trouble, please ensure you're editing the correct `cv2.putText()` calls that are responsible for drawing the labels and confidence scores on the image. If you've made changes and are not seeing any effect, make sure to clear any .pyc files and restart your script or notebook to ensure your changes are being used.
