### ISSUE TITLE
Using W&B sweep with k-fold cross validation

### ISSUE THREAD

**Issue by hoangkhoiLE** [ultralytics/yolov5#7697]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,

I would like to ask @AyushExel how to use k-fold cross validation in this example
https://github.com/wandb/examples/blob/master/examples/wandb-sweeps/sweeps-cross-validation/train-cross-validation.py
and  adapt it to our file https://github.com/ultralytics/yolov5/blob/v6.1/utils/loggers/wandb/sweep.py. I think that cross validation would give us a good vision for the way we choose our hyperparameters.

Do you have some experience with it ? Please share with me !

Best regard !

**Comment by AyushExel** [comment]
Thanks for the feature request. I'll take a look and get back to you

**Comment by ChristopherMarais** [comment]
I am also interested in this feature. There is some information in the link, but not a real parameter called num_folds  as far as I can tell.

https://github.com/wandb/examples/tree/master/examples/wandb-sweeps/sweeps-cross-validation

**Comment by glenn-jocher** [comment]
@ChristopherMarais the wandb sweep with k-fold cross-validation can be achieved by integrating wandb sweeps with a k-fold cross-validation implementation in your training script. For a practical example, you can refer to existing k-fold cross-validation implementations in the YOLOv5 community. Let me know if you need further guidance!
