### ISSUE TITLE
Torch script NNAPI

### ISSUE THREAD

**Issue by abdelaziz-mahdy** [ultralytics/yolov5#7698]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Allowing torch script models to work on GPU using NNAPI

### Use case

Improve detection speed on mobile phones to allow higher fps on video detection 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@zezo357 thanks for reaching out! Currently, YOLOv5 does not support running torch script models using NNAPI. However, we appreciate your interest in improving detection speed on mobile devices and we'll consider this feature for future development. In the meantime, feel free to explore the existing options for optimizing model performance on mobile platforms. If you have any other questions or feature requests, don't hesitate to ask!

**Comment by abdelaziz-mahdy** [comment]
> @zezo357 thanks for reaching out! Currently, YOLOv5 does not support running torch script models using NNAPI. However, we appreciate your interest in improving detection speed on mobile devices and we'll consider this feature for future development. In the meantime, feel free to explore the existing options for optimizing model performance on mobile platforms. If you have any other questions or feature requests, don't hesitate to ask!

The best option I know for now is using tflite, can you let me know if there is a faster option?

**Comment by glenn-jocher** [comment]
@zezo357, indeed, using TFLite is one of the best options for deploying on mobile devices due to its optimization for ARM architectures. Another option could be to use ONNX with an inference engine optimized for mobile, like ONNX Runtime Mobile. However, the performance gain will depend on the specific use case and hardware. For the fastest inference, it's generally recommended to profile different deployment options on your target device. Keep an eye on our updates for any future enhancements in this area! 🚀

**Comment by abdelaziz-mahdy** [comment]
> @zezo357, indeed, using TFLite is one of the best options for deploying on mobile devices due to its optimization for ARM architectures. Another option could be to use ONNX with an inference engine optimized for mobile, like ONNX Runtime Mobile. However, the performance gain will depend on the specific use case and hardware. For the fastest inference, it's generally recommended to profile different deployment options on your target device. Keep an eye on our updates for any future enhancements in this area! 🚀

Thank you very much, I will wait for it.

**Comment by glenn-jocher** [comment]
You're welcome, @zezo357! If you have any more questions or need further assistance in the future, don't hesitate to reach out. Best of luck with your mobile deployment, and we're looking forward to any contributions or feedback you might have. Happy coding! 😊👍
