### ISSUE TITLE
getting an error while training on custom dataset

### ISSUE THREAD

**Issue by SV-18** [ultralytics/yolov5#77]
I am getting this error when i train on my custom dataset can anyone help me on this..?

{'lr0': 0.01, 'momentum': 0.937, 'weight_decay': 0.0005, 'giou': 0.05, 'cls': 0.58, 'cls_pw': 1.0, 'obj': 1.0, 'obj_pw': 1.0, 'iou_t': 0.2, 'anchor_t': 4.0, 'fl_gamma': 0.0, 'hsv_h': 0.014, 'hsv_s': 0.68, 'hsv_v': 0.36, 'degrees': 0.0, 'translate': 0.0, 'scale': 0.5, 'shear': 0.0}
Traceback (most recent call last):
  File "train.py", line 387, in <module>
    opt.cfg = glob.glob('./**/' + opt.cfg, recursive=True)[0]  # find file
IndexError: list index out of range

**Comment by glenn-jocher** [comment]
@AVSLAB please provide **minimum viable code to reproduce your issue**, otherwise we can not help you.

**Comment by glenn-jocher** [comment]
@AVSLAB this issue should be resolved in our latest commit. Please `git pull` or reclone and try again. Thank you.
