### ISSUE TITLE
Inference time on CPU using Libtorch

### ISSUE THREAD

**Issue by dongb5** [ultralytics/yolov5#770]
## ❔Question
Hi guys. I tried to use a yolo5s model on cpu by Libtorch C++ API, and found it took about 2 seconds for inferencing one image. Is this normal?

I just exported an official yolo5s.pt to torchscript, including the detect layer. Then load it in a simple c++ script for inferencing.

**Comment by hal-314** [comment]
Depends on the cpu. For reference, in my macAir from 2017 (2,2 GHz Intel Core i7), Pytorch 1.6, it takes 0.6s to make the prediction for default bus image (it's in inference/images/bus.jpg) resized to 640x640.

In an old Moto G4 from 2016 with custom NMS function (as torchvision.ops.nms isn't supported) takes 4s for a 640x640 (optimized with [this recipe](https://pytorch.org/tutorials/recipes/mobile_perf.html?highlight=mobile) without applying quantization). Not optimized takes 12s. 

So, if you want realtime detection, you need a GPU. There are some guy that ported yolov5 to TensorRT.

**Comment by dreamhighchina** [comment]
> Depends on the cpu. For reference, in my macAir from 2017 (2,2 GHz Intel Core i7), Pytorch 1.6, it takes 0.6s to make the prediction for default bus image (it's in inference/images/bus.jpg) resized to 640x640.
> 
> In an old Moto G4 from 2016 with custom NMS function (as torchvision.ops.nms isn't supported) takes 4s for a 640x640 (optimized with [this recipe](https://pytorch.org/tutorials/recipes/mobile_perf.html?highlight=mobile) without applying quantization). Not optimized takes 12s.
> 
> So, if you want realtime detection, you need a GPU. There are some guy that ported yolov5 to TensorRT.

which model do you use?? YOLOv5s or YOLOv5m???

**Comment by dreamhighchina** [comment]
> ## ❔Question
> Hi guys. I tried to use a yolo5s model on cpu by Libtorch C++ API, and found it took about 2 seconds for inferencing one image. Is this normal?
> 
> I just exported an official yolo5s.pt to torchscript, including the detect layer. Then load it in a simple c++ script for inferencing.

你的libtorch库的版本是多少？？1.5.0版本还是？

**Comment by hal-314** [comment]
I use yolov5s, version 2.0. I didn't try yolov5 m.
EDIT: I use Pytorch 1.6

**Comment by dongb5** [comment]
> Depends on the cpu. For reference, in my macAir from 2017 (2,2 GHz Intel Core i7), Pytorch 1.6, it takes 0.6s to make the prediction for default bus image (it's in inference/images/bus.jpg) resized to 640x640.
> 
> In an old Moto G4 from 2016 with custom NMS function (as torchvision.ops.nms isn't supported) takes 4s for a 640x640 (optimized with [this recipe](https://pytorch.org/tutorials/recipes/mobile_perf.html?highlight=mobile) without applying quantization). Not optimized takes 12s.
> 
> So, if you want realtime detection, you need a GPU. There are some guy that ported yolov5 to TensorRT.

Thanks! Seems that my CPU is kind of weak.

**Comment by dongb5** [comment]
> > ## grey_questionQuestion
> > Hi guys. I tried to use a yolo5s model on cpu by Libtorch C++ API, and found it took about 2 seconds for inferencing one image. Is this normal?
> > I just exported an official yolo5s.pt to torchscript, including the detect layer. Then load it in a simple c++ script for inferencing.
> 
> 你的libtorch库的版本是多少？？1.5.0版本还是？

1.5.0

**Comment by lucasjinreal** [comment]
I have a more faster version of yolov5 with mobielnetv3 backbone. It's almost same mAP while CPU is **realtime**, model size is only 2.2M.

**Comment by glenn-jocher** [comment]
@jinfagang that's interesting! Can you train on COCO to compare to current models?
