### ISSUE TITLE
EdgeTpu inference 

### ISSUE THREAD

**Issue by dhunjoshi** [ultralytics/yolov5#7700]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have exported custom model to EdgeTpu tflite format. How can i perform inference i have google coral usb accelerator using windows machine.

**Comment by dhunjoshi** [comment]
Is my question wrong? Is it not possible?

**Comment by glenn-jocher** [comment]
@dhunjoshi see https://github.com/ultralytics/yolov5/discussions/3428 for a few ideas
