### ISSUE TITLE
Model conversion

### ISSUE THREAD

**Issue by iscyy** [ultralytics/yolov5#7704]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hi, is the official yolov5m.mlmodel conversion script provided by the yolov5_v6.0 version open source? The size of yolov5m.mlmodel converted using export.py is n times larger than the officially provided file

**Comment by glenn-jocher** [comment]
See export.py argparser for quantization options.

https://github.com/ultralytics/yolov5/blob/c4cb7c684ad6baf4081eb59ee1c27aa97bed4ebe/export.py#L562-L592
