### ISSUE TITLE
How to output all classes

### ISSUE THREAD

**Issue by west1021** [ultralytics/yolov5#7705]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

In Yolov5, only the detected classes are output.
But I want to output all classes, the result as 0 for the undetected class.
I think I should modify detecy.py, 
Pls instructl me where to modify it.

**Comment by glenn-jocher** [comment]
@west1021 hi there! To output all classes with the result as 0 for undetected classes, you can modify the detect.py file by editing the output format. Specifically, you can adjust the code to include all classes even if they are not detected and to assign a value of 0 for those undetected classes. You can find detailed instructions on how to modify the output format in the Ultralytics YOLOv5 documentation at https://docs.ultralytics.com/yolov5/. Let me know if you need further assistance!
