### ISSUE TITLE
F1-score error

### ISSUE THREAD

**Issue by ShJacub** [ultralytics/yolov5#7706]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Validation

### Bug

I run val.py with not changed conf-thres equal 0.001, and then run with higher conf-thres equal 0.42. In the second case I had higher max f1-score. This is invalid behaviour. With the higher conf-thres having equal or less f1 score is correct. I have linked my [screenshots.
![githubbug](https://user-images.githubusercontent.com/104581788/166904185-4571ea96-c420-48b5-be1e-b6279dfaae19.png)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by ShJacub** [comment]
There is the same problem with mAP@.5 and mAP@.5:.95. Correctly it have to be -  The more conf-thres, the less these metrics.

**Comment by glenn-jocher** [comment]
Removed bug label as this is user error. Warning message is very clear on modifying --conf:
https://github.com/ultralytics/yolov5/blob/c4cb7c684ad6baf4081eb59ee1c27aa97bed4ebe/val.py#L366-L370
