### ISSUE TITLE
wrong implementation of CIoU EDIT: implementation is correct

### ISSUE THREAD

**Issue by gitunit** [ultralytics/yolov5#7709]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

looking at this [paper](https://arxiv.org/pdf/2005.03572.pdf) and comparing the implementation of CIoU, there is a minor but impactful difference.
instead of doing (like in the paper): CIoU = S **+** D + aV
you are doing: CIoU = S **-** D + aV

this minor but impactful sign change results yolov5 outputting negative values (i know they are clamped to 0 later) but it's not ideal because the loss will be too high in this case than it should actually be.

is this by design or is that a bug?

btw. i also compared to other implementations and i think this is really a bug.

i did some experiments simulating two boxes diverging in location (bbox format i used is coco style x1y1wh for better follow the experiment, x1y1 is the left-top-corner):

```
A: [ 0.  0. 10. 10.] vs. B: [ 0.  0. 10. 10.]

iou         0.9999999790000006
ciou yolo   0.9999999790000006
ciou other  0.9999999998000001
---------------
A: [ 0.  0. 10. 10.] vs. B: [ 1.  1. 10. 10.]

iou         0.6806722568956998
ciou yolo   0.6724077940891975
ciou other  0.6889367316030818
---------------
A: [ 0.  0. 10. 10.] vs. B: [ 5.  0. 10. 10.]

iou         0.33333332866666676
ciou yolo   0.2564102517672585
ciou other  0.4102564102119658
---------------
A: [ 0.  0. 10. 10.] vs. B: [ 5.  5. 10. 10.]

iou         0.14285714114285716
ciou yolo   0.03174603005643742
ciou other  0.25396825395192746
---------------
A: [ 0.  0. 10. 10.] vs. B: [ 5.  6. 10. 10.]

iou         0.11111110981481484
ciou yolo   -0.015708016977946243
ciou other  0.23793023791789225
---------------
A: [ 0.  0. 10. 10.] vs. B: [ 5.  8. 10. 10.]

iou         0.05263157836565098
ciou yolo   -0.10948135420955614
ciou other  0.21474451154656415
---------------
A: [ 0.  0. 10. 10.] vs. B: [ 5.  9. 10. 10.]

iou         0.025641025364891525
ciou yolo   -0.15524634661789222
ciou other  0.20652839765204767
---------------
A: [ 0.  0. 10. 10.] vs. B: [ 9.  9. 10. 10.]

iou         0.00502512557511174
ciou yolo   -0.21935160569575024
ciou other  0.2294018569295747
---------------
A: [ 0.  0. 10. 10.] vs. B: [ 9. 10. 10. 10.]

iou         0.0
ciou yolo   -0.23784494083602564
ciou other  0.2378449408672799
---------------
A: [ 0.  0. 10. 10.] vs. B: [10. 10. 10. 10.]

iou         0.0
ciou yolo   -0.24999999996875
ciou other  0.25
---------------
A: [ 0.  0. 10. 10.] vs. B: [ 5. 10. 10. 10.]

iou         0.0
ciou yolo   -0.199999999968
ciou other  0.2
---------------
A: [ 0.  0. 10. 10.] vs. B: [ 0. 10. 10. 10.]

iou         0.0
ciou yolo   -0.19999999995999998
ciou other  0.2
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@gitunit wow, this seems like a significant bug! Can you please submit a PR with your proposed fix? I will run some trainings on the PR branch to compare to current model trainings.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by glenn-jocher** [comment]
@gitunit is DIoU implementation likewise affected? Relevant code is
https://github.com/ultralytics/yolov5/blob/c4cb7c684ad6baf4081eb59ee1c27aa97bed4ebe/utils/metrics.py#L231-L248

**Comment by gitunit** [comment]
@glenn-jocher true, DIoU seems also to be affected and so is GIoU as well. will create a PR with proposed fix. :+1:

**Comment by gitunit** [comment]
all good

**Comment by glenn-jocher** [comment]
@gitunit thank you! Looking forward to your PR. Let us know if you need any assistance along the way.
