### ISSUE TITLE
resume training error,RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by dapsjj** [ultralytics/yolov5#771]
I use this command to resume training: `python train.py --img-size 640 --batch-size 8 --epochs 300  --workers 2 --data ./data/garbage.yaml --cfg ./models/yolov5m.yaml --weights E:/test_opencv/yolov5-master/runs/exp15/weights/best.pt --resume`  

But the error message is:

Using CUDA device0 _CudaDeviceProperties(name='GeForce GTX 1050', total_memory=4096MB)

Namespace(adam=False, batch_size=8, bucket='', cache_images=False, cfg='./models/yolov5m.yaml', data='./data/garbage.yaml', device='', epochs=300, evolve=False, global_rank=-1, hyp='data/
hyp.finetune.yaml', img_size=[640, 640], local_rank=-1, logdir='runs/', multi_scale=False, name='', noautoanchor=False, nosave=False, notest=False, rect=False, resume='get_last', single_c
ls=False, sync_bn=False, total_batch_size=8, weights='E:/test_opencv/yolov5-master/runs/exp15/weights/best.pt', workers=2, world_size=1)
Start Tensorboard with "tensorboard --logdir runs/", view at http://localhost:6006/
Hyperparameters {'lr0': 0.01, 'momentum': 0.937, 'weight_decay': 0.0005, 'giou': 0.05, 'cls': 0.5, 'cls_pw': 1.0, 'obj': 1.0, 'obj_pw': 1.0, 'iou_t': 0.2, 'anchor_t': 4.0, 'fl_gamma': 0.0
, 'hsv_h': 0.015, 'hsv_s': 0.7, 'hsv_v': 0.4, 'degrees': 0.0, 'translate': 0.1, 'scale': 0.5, 'shear': 0.0, 'perspective': 0.0, 'flipud': 0.0, 'fliplr': 0.5, 'mixup': 0.0}
Overriding ./models/yolov5m.yaml nc=80 with nc=13

                 from  n    params  module                                  arguments
  0                -1  1      5280  models.common.Focus                     [3, 48, 3]
  1                -1  1     41664  models.common.Conv                      [48, 96, 3, 2]
  2                -1  1     67680  models.common.BottleneckCSP             [96, 96, 2]
  3                -1  1    166272  models.common.Conv                      [96, 192, 3, 2]
  4                -1  1    639168  models.common.BottleneckCSP             [192, 192, 6]
  5                -1  1    664320  models.common.Conv                      [192, 384, 3, 2]
  6                -1  1   2550144  models.common.BottleneckCSP             [384, 384, 6]
  7                -1  1   2655744  models.common.Conv                      [384, 768, 3, 2]
  8                -1  1   1476864  models.common.SPP                       [768, 768, [5, 9, 13]]
  9                -1  1   4283136  models.common.BottleneckCSP             [768, 768, 2, False]
 10                -1  1    295680  models.common.Conv                      [768, 384, 1, 1]
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 12           [-1, 6]  1         0  models.common.Concat                    [1]
 13                -1  1   1219968  models.common.BottleneckCSP             [768, 384, 2, False]
 14                -1  1     74112  models.common.Conv                      [384, 192, 1, 1]
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 16           [-1, 4]  1         0  models.common.Concat                    [1]
 17                -1  1    305856  models.common.BottleneckCSP             [384, 192, 2, False]
 18                -1  1    332160  models.common.Conv                      [192, 192, 3, 2]
 19          [-1, 14]  1         0  models.common.Concat                    [1]
 20                -1  1   1072512  models.common.BottleneckCSP             [384, 384, 2, False]
 21                -1  1   1327872  models.common.Conv                      [384, 384, 3, 2]
 22          [-1, 10]  1         0  models.common.Concat                    [1]
 23                -1  1   4283136  models.common.BottleneckCSP             [768, 768, 2, False]
 24      [17, 20, 23]  1     72738  models.yolo.Detect                      [13, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [192, 384, 768]]
Model Summary: 263 layers, 2.15343e+07 parameters, 2.15343e+07 gradients

Transferred 512/514 items from E:/test_opencv/yolov5-master/runs/exp15/weights/best.pt
Optimizer groups: 86 .bias, 94 conv.weight, 83 other
Scanning labels E:\test_opencv\yolov5-master\dataset\labels\train_small_image.cache (12752 found, 0 missing, 0 empty, 0 duplicate, for 12752 images): 12752it [00:00, 26040.99it/s]
Scanning labels E:\test_opencv\yolov5-master\dataset\labels\test_small_image.cache (3443 found, 0 missing, 0 empty, 134 duplicate, for 3443 images): 3443it [00:00, 25759.42it/s]

Analyzing anchors... anchors/target = 4.15, Best Possible Recall (BPR) = 1.0000
Image sizes 640 train, 640 test
Using 2 dataloader workers
Starting training for 300 epochs...
You have uninstalled pretty_errors but it is still present in your python startup.  Please remove its section from file:
 E:\Anaconda3\sitecustomize.py

You have uninstalled pretty_errors but it is still present in your python startup.  Please remove its section from file:
 E:\Anaconda3\sitecustomize.py

     Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
  0%|                                                                                                                                                            | 0/1594 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 453, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 268, in train
    pred = model(imgs)
  File "E:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\test_opencv\yolov5-master\models\yolo.py", line 113, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "E:\test_opencv\yolov5-master\models\yolo.py", line 133, in forward_once
    x = m(x)  # run
  File "E:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\test_opencv\yolov5-master\models\common.py", line 88, in forward
    return self.conv(torch.cat([x[..., ::2, ::2], x[..., 1::2, ::2], x[..., ::2, 1::2], x[..., 1::2, 1::2]], 1))
  File "E:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\test_opencv\yolov5-master\models\common.py", line 29, in forward
    return self.act(self.bn(self.conv(x)))
  File "E:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\Anaconda3\lib\site-packages\torch\nn\modules\conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "E:\Anaconda3\lib\site-packages\torch\nn\modules\conv.py", line 416, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
 
**Where is wrong,how to resume training?**
Is this resume training command right?

**Comment by glenn-jocher** [comment]
@dapsjj in the latest code, --resume does not accept any other options. See https://github.com/ultralytics/yolov5/pull/756
