### ISSUE TITLE
download script does not download training annotations

### ISSUE THREAD

**Issue by nahidalam** [ultralytics/yolov5#7711]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Other

### Bug

I used [this](https://github.com/ultralytics/yolov5/blob/master/data/scripts/get_coco.sh) script to download the coco dataset. Everything works fine except it does not download the `instances_train2017.json` in `annotation` directory. It only downloads `instances_val2017.json`

### Environment

- YOLOv5
- MacOS
- Python 3.9

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@nahidalam train json is not used anywhere, as the script downloads labels in YOLOv5 format already. val json is supplied for pycocotools mAP with val.py.
