### ISSUE TITLE
How to deploy YOLOv5 model in GCP's App_Engine

### ISSUE THREAD

**Issue by medinikb** [ultralytics/yolov5#7717]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am trying to deploy an app (with flask) in Google Cloud Platform (GCP) via App-Engine.

![image](https://user-images.githubusercontent.com/68976735/167065861-8fc9aaa2-a1f8-4b02-aef6-8a8508a3afce.png)

All my code is available in the GitHub link:
https://github.com/medinikb/deploy-yolov5-gcp 

I could run my code in my laptop, however I am not able to predict any image after deploying in GCP.

Grateful, if any one can guide me to debug my code.

Regards,
Medini Kr. Bora

**Comment by glenn-jocher** [comment]
@medinikb we have a Google App Engine example here:
https://github.com/ultralytics/yolov5/tree/master/utils/google_app_engine

**Comment by medinikb** [comment]
Thank you sir for your prompt response.

This is my First Web-App trying to build with yolov5. I am at a beginner level.
I can run the code successfully in my Laptop. Code is available at the below link:
https://github.com/medinikb/deploy-yolov5-gcp

Grateful, if you would guide me to correct/modify my above code.

**Comment by glenn-jocher** [comment]
@medinikb I'm sorry, I don't have availability to help with custom code, but perhaps you can get some community feedback to help.
