### ISSUE TITLE
pytorch hub and detect.py gives different results

### ISSUE THREAD

**Issue by kzyadaking** [ultralytics/yolov5#7721]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

im using win32 instead of pill or mss for screengrab because this way its way faster than those two.
but the problem is sometimes it doesnt detect well compared to using detect.py. i have no idea where to look at.
does anyone have an idea?

    import torch
    import numpy as np
    import win32gui
    import win32ui
    import win32con

    w = 800 # set this
    h = 600 # set this
    bmpfilenamename = "color.bmp" #set this
    windowname = 'put windowname'

    def screenshot():
        hwnd = win32gui.FindWindow(None, windowname)
        wDC = win32gui.GetWindowDC(hwnd)
        dcObj=win32ui.CreateDCFromHandle(wDC)
        cDC=dcObj.CreateCompatibleDC()
        dataBitMap = win32ui.CreateBitmap()
        dataBitMap.CreateCompatibleBitmap(dcObj, w, h)
        cDC.SelectObject(dataBitMap)
        cDC.BitBlt((0,0),(w, h) , dcObj, (0,0), win32con.SRCCOPY)

    #save the screenshot
    #dataBitMap.SaveBitmapFile(cDC, bmpfilenamename)
    
    signedIntsArray = dataBitMap.GetBitmapBits(True)
    img = np.frombuffer(signedIntsArray, dtype='uint8')
    img.shape = (h,w,4)

    # Free Resources
    dcObj.DeleteDC()
    cDC.DeleteDC()
    win32gui.ReleaseDC(hwnd, wDC)
    win32gui.DeleteObject(dataBitMap.GetHandle())

    #img = img[..., ::-1]
    #img = np.ascontiguousarray(img)
    
    return img

    #load
    model = torch.hub.load('./', 'custom', path='yolov5s.pt', source='local')

    #inference
    test = screenshot()
    results = model(test)
    boxes = results.pandas().xyxy[0]
    print (boxes)

**Comment by glenn-jocher** [comment]
@kzyadaking we don't assist in debugging custom code, but obviously I'd recommend you compare whatever the image your code is producing with the official screenshot inference example in our PyTorch Hub tutorial:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️  RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Roboflow for Datasets, Labeling, and Active Learning](https://docs.ultralytics.com/yolov5/tutorials/roboflow_datasets_integration)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TFLite, ONNX, CoreML, TensorRT Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [Architecture Summary](https://docs.ultralytics.com/yolov5/tutorials/architecture_description)&nbsp; ⭐ NEW

Good luck 🍀 and let us know if you have any other questions!

**Comment by kzyadaking** [comment]
@glenn-jocher thanx for the reply. i found a solution! for those who might be interested,

    #change this 
    results = model(test) 

    #to this
    results = model(cv.cvtColor(test, cv.COLOR_BGR2RGB))

**Comment by glenn-jocher** [comment]
Glad to hear you found a solution, @kzyadaking! Thanks for sharing it with the community. Your contribution is valuable 💪. Let us know if you need further assistance or have any more tips to share!
