### ISSUE TITLE
How to fix the input imgsize (h and w) of one network layer is what I want？for example conv or c3 layer of yaml。

### ISSUE THREAD

**Issue by nit-chick** [ultralytics/yolov5#7723]
How to how  define the network structure for each layer of h and w of each layer input ？I want to fix input  the shape of input x for one layer and get this (h,w) in the class's def__init__ argument, but I find it difficult. I tried to fix the value (h,w). However, I found that there was an error in train, so I modified s（256） of the train_Warm up , but there was another error in val after running a epoch. Could you please give me some suggestions for modification?
![pic](https://user-images.githubusercontent.com/101462914/167242429-f4de2b70-c4b8-40c4-8e3d-8c63ad3ae626.png)

**Comment by glenn-jocher** [comment]
@nit-chick feature shapes anywhere in YOLOv5 are not fixed, they're dynamic based upon the input image shape.

**Comment by nit-chick** [comment]
Got it,thanks.but how to get the dynamic  input image shape in the yolov5-pytorch?
![pic](https://user-images.githubusercontent.com/101462914/167243289-f02abcfb-28e8-4c33-b3b5-e31f3e886671.png)

**Comment by glenn-jocher** [comment]
`x.shape`

**Comment by nit-chick** [comment]
When I debug my problem on GPU CUDA，i found  half is True(fp16) in val after trainning a epoch,but when I execute the val.py alone， i found half is False,so it makes a difference。May I ask why you set it like this？
![1](https://user-images.githubusercontent.com/101462914/168240521-6262651d-a16d-421b-a130-a5fba16ec927.png)
![2](https://user-images.githubusercontent.com/101462914/168240611-42bbf2da-97e7-49ce-a572-038eab5f0808.png)

**Comment by glenn-jocher** [comment]
@nit-chick yes that's correct. We used to use --half as default for all inference, but some configurations (Conda/Windows/CUDA11) suffered from zero-mAP bugs, so we unfortunately had to revert val.py and detect.py to FP32 default.

Training using AMP and an FP16 EMA which is passed to val.py for inference.
