### ISSUE TITLE
Training on deep color images (32 bit)

### ISSUE THREAD

**Issue by cyber-sys** [ultralytics/yolov5#7726]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hey! My dataset represents tiff images grayscale uint32 и float32.
When reading a tiff uint32 or float32 I run into this error:
`opencv-python\opencv-python\opencv\modules\imgcodecs\src\grfmt_tiff.cpp (462) cv::TiffDecoder::readData OpenCV TIFF: TIFFRGBAImageOK: Sorry, can not handle images with 32-bit samples`

Please advise how to get around this limitation.

### Additional

I tried replacing `utils/general.py`
`961 def imread(path, flags=cv2.IMREAD_COLOR):`
 `962    return cv2.imdecode(np.fromfile(path, np.uint8), flags)`
with
`961 def imread(path, flags=cv2.IMREAD_GRAYSCALE):`
 `962    return cv2.imdecode(np.fromfile(path, np.float32), flags)`
but could not successfully launch the training.

**Comment by glenn-jocher** [comment]
@cyber-sys your images must be loadable by the default cv2/numpy image reader function that YOLOv5 uses, or else if you want to customize the code then the function you found is the right place.
