### ISSUE TITLE
A warning appears when running "pip install -r requirements.txt"

### ISSUE THREAD

**Issue by shisenglin** [ultralytics/yolov5#7728]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

![0d67f3701c3f178c07b2374907b2d43](https://user-images.githubusercontent.com/101716952/167260236-7e207f89-3136-444b-a013-bb9a0cc91459.png)
I created a "luoge" virtual environment in anaconda and then ran "pip install -r requirements.txt" and got the warning in the picture, how can I solve this problem?

### Environment

python=3.8.13

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@shisenglin these just seem to be warnings. Warnings can be ignored here probably.

**Comment by shisenglin** [comment]
> @shisenglin这些似乎只是警告。警告在这里可能可以忽略。

It was because of this warning that I was unable to install anything from requirements.txt.I can't use yolov5 for training because I can't install what's in "pip install-r requirements.txt".Can you give me a solution to solve the problem?Thank you very much.

**Comment by glenn-jocher** [comment]
@shisenglin it appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual [Python 3.9](https://www.python.org/) environment, clone the latest repo ([code changes daily](https://github.com/ultralytics/yolov5/commits/master)), and `pip install` [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) again from scratch.

💡 ProTip! Try one of our verified environments below if you are having trouble with your local environment.


## Requirements

[**Python>=3.7.0**](https://www.python.org/) with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) installed including [**PyTorch>=1.7**](https://pytorch.org/get-started/locally/). To get started:
```bash
git clone https://github.com/ultralytics/yolov5  # clone
cd yolov5
pip install -r requirements.txt  # install
```

[Models](https://github.com/ultralytics/yolov5/tree/master/models) and [datasets](https://github.com/ultralytics/yolov5/tree/master/data) download automatically from the latest YOLOv5 [release](https://github.com/ultralytics/yolov5/releases) when first requested.

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), validation ([val.py](https://github.com/ultralytics/yolov5/blob/master/val.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/export.py)) on MacOS, Windows, and Ubuntu every 24 hours and on every commit.

**Comment by shisenglin** [comment]
![image](https://user-images.githubusercontent.com/101716952/167400398-38a7b04a-1101-492d-8ee4-c47029915f80.png)

**Comment by shisenglin** [comment]
![image](https://user-images.githubusercontent.com/101716952/167403891-e0eae0f2-b2a5-4295-9931-41e1a627083c.png)

**Comment by shisenglin** [comment]
![5C 86T98848YOYK}U7HUHLH](https://user-images.githubusercontent.com/101716952/167407602-87f8a1bf-2e0f-4e82-8e43-427c8fa9dadf.png)

**Comment by shisenglin** [comment]
It is still because of this warning that things in "pip install-r requirements.txt" cannot be installed.

**Comment by glenn-jocher** [comment]
@shisenglin like I said earlier unless this causes some other issue you can ignore it, it's just a warning.
