### ISSUE TITLE
Jeton Nano Inference: CUDNN_STATUS_MAPPING_ERROR)

### ISSUE THREAD

**Issue by salidw** [ultralytics/yolov5#7733]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello there,

  I created ONNX file on my host Ubuntu 20.04 computer. Then I created TRT Engine file on JETSON NANO device instead.
The process was all smooth.

>> Command to build TRT Engine file: 
    $ /usr/src/tensorrt/bin/trtexec --onnx=/home/jp/myonnx.onnx --saveEngine=/home/jp/trt.engine --fp16
But there was error when I did inference on Jetson Nano like this
>> [TensorRT] ERROR: 1: [hardwareContext.cpp::configure::92] Error Code 1: Cudnn (CUDNN_STATUS_MAPPING_ERROR)

>> Inference command was: 
    $python3 detect.py --weights trt.engine --source 0

Note: My Jetson environment
> TensorRT: 8.0.1.6
> Cuda: 10.2.300
> cuDNN: 8.2.1.32
> Compiled CUDA: No

Please advice... how to resolve this problem. I am new for Pytorch and ML.

**Comment by glenn-jocher** [comment]
@salidw see **TFLite, ONNX, CoreML, TensorRT Export** tutorial for YOLOv5 TensorRT export, inference and validation instructions.

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️  RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Roboflow for Datasets, Labeling, and Active Learning](https://docs.ultralytics.com/yolov5/tutorials/roboflow_datasets_integration)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TFLite, ONNX, CoreML, TensorRT Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [Architecture Summary](https://docs.ultralytics.com/yolov5/tutorials/architecture_description)&nbsp; ⭐ NEW

Good luck 🍀 and let us know if you have any other questions!
