### ISSUE TITLE
How to implement yolov4 on this repo?

### ISSUE THREAD

**Issue by faster-faster** [ultralytics/yolov5#7734]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Ease of use of this repo impress me, and I want to implement baseline of YOLOv4 on this repo. 
But I can't write a yaml that correctly implements yolov4.
Can you share any available yaml of yolov4 or suggestions to implement it?

**Comment by glenn-jocher** [comment]
@faster-faster thanks for the kind words! YOLOv5 is currently focused on YOLOv5 models, but YOLOv4 can be implemented using a custom model definition in the `models` directory. You can refer to the YOLOv5 documentation for custom model implementation details. If you have any specific questions while implementing YOLOv4, feel free to ask. Good luck!
