### ISSUE TITLE
Bug : Unable to use gdrive link for weights

### ISSUE THREAD

**Issue by Vijay-P1999** [ultralytics/yolov5#7735]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

Hello,
When i tried using google drive link for auto downloading the weights. I faced some issues. I guess that probably might be an bug.

`python3 detect.py --weights https://drive.google.com/file/d/1Ti6RuptngpFugNNmKeGFOP/view?usp=sharing --data data/VisDrone.yaml --img 40`
I get this error

> YOLOv5 🚀 6fa5745 torch 1.7.1 CUDA:0 (NVIDIA GeForce MX130, 2004MiB)
(False, False, False, False, False, False, False, False, False, False, False)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1642    0  1642    0     0   2118      0 --:--:-- --:--:-- --:--:--     0
Downloading https://drive.google.com/uc?export=download&id=https://drive.google.com/file/d/1Ti6RuptngpFugNNmKeGFOP/view?usp=sharing as weight.pt... Done (1.6s)
WARNING: --img-size (640, 640) must be multiple of max stride 64, updating to [640, 640]
Traceback (most recent call last):
  File "/home/vijay/UMT-CV/umt-skyeye-remote/detect.py", line 296, in <module>
    run()
  File "/home/vijay/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/home/vijay/UMT-CV/umt-skyeye-remote/detect.py", line 136, in run
    pred = model(im, augment=augment, visualize=visualize)
  File "/home/vijay/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/vijay/UMT-CV/umt-skyeye-remote/models/common.py", line 450, in forward
    y[..., :4] *= [w, h, w, h]  # xywh normalized to pixels
UnboundLocalError: local variable 'y' referenced before assignment

And when i tried to debug this error, I found out that `w` is the weights link(gdrive link) that we provide in the cmd.(Refer line 297 in `common.py`) not the name of weight with `.pt` or other extensions. 
SO it couldn't classify the model of any type,

> print(self.model_type(w))
(False, False, False, False, False, False, False, False, False, False, False)

https://github.com/ultralytics/yolov5/blob/d059d1da03aee9a3c0059895aa4c7c14b7f25a9e/models/common.py#L297-L300

**Solution:**
The `w=attempt_download(w)`(line 300) happens after `self.model_type()`, which is what causing the error.

I fixed this issue in my fork. Should i open a PR for this?

And also, i faced one more error after fixing this, which is 

> YOLOv5 🚀 6fa5745 torch 1.7.1 CUDA:0 (NVIDIA GeForce MX130, 2004MiB)
Found https://drive.google.com/file/d/1Ti6RuptngpFugNNmKeGFOP/view?usp=sharing locally at umt-weight.pt
(True, False, False, False, False, False, False, False, False, False, False)
Traceback (most recent call last):
  File "/home/vijay/UMT-CV/umt-skyeye-remote/detect.py", line 296, in <module>
    run()
  File "/home/vijay/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/home/vijay/UMT-CV/umt-skyeye-remote/detect.py", line 96, in run
    model = DetectMultiBackend(weights, device=device, dnn=dnn, data=data)
  File "/home/vijay/UMT-CV/umt-skyeye-remote/models/common.py", line 307, in __init__
    model = attempt_load(weights if isinstance(weights, list) else w, map_location=device)
  File "/home/vijay/UMT-CV/umt-skyeye-remote/models/experimental.py", line 96, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location=map_location)  # load
  File "/home/vijay/.local/lib/python3.8/site-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/vijay/.local/lib/python3.8/site-packages/torch/serialization.py", line 764, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.

Extra info:

I found that i'm facing this `UnpicklingError` only if i download the weights using G drive link. When i use the downloaded weights instead of link, it it working fine.

Any idea why this is happening???

### Environment

Ubuntu 20.04 LTS
Python 3.8

### Minimal Reproducible Example

```
python3 detect.py --weights any/google-drive/link/with/weights --data data/yolov5s.yaml --img 640
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Vijay-P1999 user error. First, —source is the source of images for inference. Second, Google drive weights are not supported.
