### ISSUE TITLE
how to extact boxes, scores and labels?

### ISSUE THREAD

**Issue by myasser63** [ultralytics/yolov5#7737]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am tryin to use different emsembling techniques as soft-nms, wbf but I have a problem fiquring out how to extract boxes, score and labels. @glenn-jocher  Could you please advice?

**Comment by glenn-jocher** [comment]
@myasser63 sure! To extract boxes, scores, and labels from YOLOv5, you can use the `xyxy`-formatted bounding boxes returned by the detector. They are `N x 4` arrays, where `N` is the number of predicted bounding boxes. To access the boxes, scores, and labels separately, you can use array indexing.

For example, if you have predictions `pred` returned by YOLOv5, you can access the bounding boxes, their confidence scores, and predicted class labels using `pred[:, :4]`, `pred[:, 4]`, and `pred[:, 5]` respectively.

You can then apply the desired ensembling techniques using these arrays.

For more details, you can also refer to the Ultralytics Docs at https://docs.ultralytics.com/yolov5/.

Let me know if you need any further assistance!
