### ISSUE TITLE
How to get accuracy/precision for test set with YOLOv5?

### ISSUE THREAD

**Issue by GianNuzzarello** [ultralytics/yolov5#7741]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I train my model on custom dataset with train.py and I use val.py on my validation set. My dataset is, as usual, splitted into train/validation/test set. My question is, how can I measure model performance just in test set?
Thank you.

p.s. In old discussions I saw the function test.py but, according the last YOLOv5 repo, it's no more available.

**Comment by barathsku** [comment]
You can use detect.py to run the inference using your trained model on your test set: 

`python detect.py --weights your_model.pt --img 640 --source your/test/set/image/directory`

There's more arguments for detect.py that you can look into like confidence/IoU threshold values, it can be found in the [source code](https://github.com/ultralytics/yolov5/blob/master/detect.py).

**Comment by glenn-jocher** [comment]
@GianNuzzarello `python val.py --task test` will validate metrics on a test set. See val.py argparser for details.

**Comment by Aanchal157** [comment]
How to plot curves for test set such as PR curve,F1 CURVE etc. and also, how to draw number of epochs v/s Map curve in yolov5 particularly for test set only????

**Comment by glenn-jocher** [comment]
@Aanchal157 val.py automatically saves all plots to runs/val/exp

To evaluate on test set:
```
python val.py --task test
````

**Comment by Aanchal157** [comment]
is PANET in yolov5 a head or neck?

**Comment by glenn-jocher** [comment]
PANet is a head

**Comment by Aanchal157** [comment]
what if validation map value is less than the testing map value in yolov5?
is it due to train val test split random seed value???

**Comment by glenn-jocher** [comment]
@Aanchal157 if you have a test set defined in your data.yaml (with labels), then you can just pass --task test to val.py:
```
python val.py --data data.yaml --task test
```

https://github.com/ultralytics/yolov5/blob/36f64a981d08c1fc34c50ae2ff8a15769ee6b49b/val.py#L338

EDIT: To answer your other question there is zero randomness in val.py, seeds do not factor into the result.

**Comment by alrightkami** [comment]
Hey there. I was trying to evaluate the custom trained model with the test set and run the following cell:
`!python val.py --data pictogram_layer1.yaml --task test`
and got this error:
```
Fusing layers... 
Model summary: 213 layers, 7020913 parameters, 0 gradients
Traceback (most recent call last):
  File "/home/jovyan/data/kamila/yolov5_mlflow/yolov5/val.py", line 396, in <module>
    main(opt)
  File "/home/jovyan/data/kamila/yolov5_mlflow/yolov5/val.py", line 369, in main
    run(**vars(opt))
  File "/opt/conda/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/jovyan/data/kamila/yolov5_mlflow/yolov5/val.py", line 173, in run
    dataloader = create_dataloader(data[task],
KeyError: 'test'
```
my data.yaml looks as follows:
```
train: /home/jovyan/data/db_regio/pictogram/layer_1/pictogram_set_1_360/train.txt  # has path to images
val: /home/jovyan/data/db_regio/pictogram/layer_1/pictogram_set_1_360/validate.txt
test: /home/jovyan/data/backups/sbm_ase_pictogram/test_data  # has both labels & images in the format img1.jpg and img1.txt

nc: 4
names: ['d', 'w', 'iw', 'cd']
```

I would really appreciate your help on this; what am I doing wrong?

**Comment by glenn-jocher** [comment]
@alrightkami you can pass --task test to val.py to evaluate a test set. Default is --task val.

**Comment by alrightkami** [comment]
> @alrightkami you can pass --task test to val.py to evaluate a test set. Default is --task val.

Maybe I am misunderstanding you here. Isn't it what I did?

**Comment by glenn-jocher** [comment]
@alrightkami oh yes you did. The error indicates your data.yaml has no test field. You need a test split if you want to evaluate your test split...

**Comment by glenn-jocher** [comment]
@alrightkami https://github.com/ultralytics/yolov5/blob/d7bc5d77730c625e8b7039e8680714602f5b321f/data/coco128.yaml#L10-L15

**Comment by alrightkami** [comment]
> @alrightkami oh yes you did. The error indicates your data.yaml has no test field. You need a test split if you want to evaluate your test split...

I attached my data.yaml before and I actually had a test set there, however in a different format (it was a path to the folder with images in .jpg format and .txt file for each image with the same name).  

> my data.yaml looks as follows:
> 
> ```
> train: /home/jovyan/data/db_regio/pictogram/layer_1/pictogram_set_1_360/train.txt  # has path to images
> val: /home/jovyan/data/db_regio/pictogram/layer_1/pictogram_set_1_360/validate.txt
> test: /home/jovyan/data/backups/sbm_ase_pictogram/test_data  # has both labels & images in the format img1.jpg and img1.txt
> 
> nc: 4
> names: ['d', 'w', 'iw', 'cd']
> ```

Now I changed it to the same format my train & val data is in (I passed a .txt file that has in its every line a path to the .jpg file; labels are in the same folder) and I am still getting the exact same error as before.

I am still not getting what am I doing wrong at this point and would appreciate your help.

**Comment by Sary666** [comment]
> 

the result(precision and recall) generated from **python val.py --data data.yaml --task test** is much less than that from **detect.py**, what;s the reason?

**Comment by glenn-jocher** [comment]
@Sary666 👋 Hello, thanks for asking about the differences between [train.py](https://github.com/ultralytics/yolov5/blob/master/train.py), [detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py) and [val.py](https://github.com/ultralytics/yolov5/blob/master/val.py) in YOLOv5 🚀.

These 3 files are designed for different purposes and utilize different dataloaders with different settings. train.py dataloaders are designed for a speed-accuracy compromise, val.py is designed to obtain the best mAP on a validation dataset, and detect.py is designed for best real-world inference results. A few important aspects of each:


## train.py

- **trainloader** LoadImagesAndLabels(): designed to load train dataset images and labels. Augmentation capable and enabled. https://github.com/ultralytics/yolov5/blob/7ee5aed0b3fa6a805afb0a820c40bbcbf29960de/train.py#L210-L213 **val_loader** LoadImagesAndLabels(): designed to load val dataset images and labels. Augmentation capable but disabled. https://github.com/ultralytics/yolov5/blob/7ee5aed0b3fa6a805afb0a820c40bbcbf29960de/train.py#L220-L223
- image size: `640`
- rectangular inference: `False`
- [confidence threshold](https://github.com/ultralytics/yolov5/blob/16206692f245e713a5beb380de6dc4bed944986c/test.py#L291): `0.001`
- [iou threshold](https://github.com/ultralytics/yolov5/blob/16206692f245e713a5beb380de6dc4bed944986c/test.py#L292): `0.6`
- [multi-label](https://github.com/ultralytics/yolov5/blob/16206692f245e713a5beb380de6dc4bed944986c/test.py#L120): `True`
- [padding](https://github.com/ultralytics/yolov5/blob/16206692f245e713a5beb380de6dc4bed944986c/test.py#L83-L90): `None`

## val.py

- **dataloader** LoadImagesAndLabels(): designed to load train, val, test dataset images and labels. Augmentation capable but disabled. 
- https://github.com/ultralytics/yolov5/blob/7ee5aed0b3fa6a805afb0a820c40bbcbf29960de/val.py#L152-L153
- image size: `640`
- rectangular inference: `True`
- [confidence threshold](https://github.com/ultralytics/yolov5/blob/16206692f245e713a5beb380de6dc4bed944986c/test.py#L291): `0.001`
- [iou threshold](https://github.com/ultralytics/yolov5/blob/16206692f245e713a5beb380de6dc4bed944986c/test.py#L292): `0.6`
- [multi-label](https://github.com/ultralytics/yolov5/blob/16206692f245e713a5beb380de6dc4bed944986c/test.py#L120): `True`
- [padding](https://github.com/ultralytics/yolov5/blob/16206692f245e713a5beb380de6dc4bed944986c/test.py#L83-L90): `0.5 * maximum stride`


## detect.py

- **dataloaders** (multiple): designed for loading multiple types of media (images, videos, globs, directories, streams). https://github.com/ultralytics/yolov5/blob/7ee5aed0b3fa6a805afb0a820c40bbcbf29960de/detect.py#L120-L128
- image size: `640`
- rectangular inference: `True`
- [confidence threshold](https://github.com/ultralytics/yolov5/blob/16206692f245e713a5beb380de6dc4bed944986c/detect.py#L152): `0.25` 
- [iou threshold](https://github.com/ultralytics/yolov5/blob/16206692f245e713a5beb380de6dc4bed944986c/detect.py#L153): `0.45`
- [multi-label](https://github.com/ultralytics/yolov5/blob/16206692f245e713a5beb380de6dc4bed944986c/utils/general.py#L415): `False`
- [padding](https://github.com/ultralytics/yolov5/blob/16206692f245e713a5beb380de6dc4bed944986c/detect.py#L45-L54): `None`


## YOLOv5 PyTorch Hub Inference

YOLOv5 PyTorch Hub models are`AutoShape()` instances used for image loading, preprocessing, inference and NMS. For more info see [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)
https://github.com/ultralytics/yolov5/blob/7ee5aed0b3fa6a805afb0a820c40bbcbf29960de/models/common.py#L276-L282

- image size: `640`
- rectangular inference: `True`
- [confidence threshold](https://github.com/ultralytics/yolov5/blob/abfcf9eb79877971acd238cafe6149711c5056ad/models/common.py#L226-L230): `0.25 `
- [iou threshold](https://github.com/ultralytics/yolov5/blob/abfcf9eb79877971acd238cafe6149711c5056ad/models/common.py#L226-L230): `0.45`
- [multi-label](https://github.com/ultralytics/yolov5/blob/abfcf9eb79877971acd238cafe6149711c5056ad/models/common.py#L288): `False`
- [padding](https://github.com/ultralytics/yolov5/blob/abfcf9eb79877971acd238cafe6149711c5056ad/models/common.py#L226-L230): `None`

Good luck 🍀 and let us know if you have any other questions!

**Comment by Jojo942004** [comment]
@glenn-jocher hey, I do have a question similar to the one @alrightkami asked. 
I want to validate a custom yolov5 model with a custom dataset exported from Roboflow, so when using this:

`python yolov5-master-new/classify/val.py --weights yolov5-master-new/models/yolov5l.pt --data archiv\datasetv8 --img 416
`
I get:
`FileNotFoundError: Found no valid file for the classes labels. Supported extensions are: .jpg, .jpeg, .png, .ppm, .bmp, .pgm, .tif, .tiff, .webp`

The exported data has a folder structure like this:
train
test
val(id) 

all of which have again two subfolders called _images_ and _labels_, labels contains text documents containing the labels. 
My Question being, why is, according to the error, a valid file containg class labels a .jpg ?
Thank you for helping me out, sorry for my ignorance :)

**Comment by glenn-jocher** [comment]
👋 Hello! Thanks for asking about YOLOv5 🚀 **dataset formatting**. To train correctly your data must be in YOLOv5 format. Please see our [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) tutorial for full documentation on dataset setup and all steps required to start training your first model. A few excerpts from the tutorial:

### 1.1 Create dataset.yaml

[COCO128](https://www.kaggle.com/datasets/ultralytics/coco128) is an example small tutorial dataset composed of the first 128 images in [COCO](http://cocodataset.org/#home) train2017. These same 128 images are used for both training and validation to verify our training pipeline is capable of overfitting. [data/coco128.yaml](https://github.com/ultralytics/yolov5/blob/master/data/coco128.yaml), shown below, is the dataset config file that defines 1) the dataset root directory `path` and relative paths to `train` / `val` / `test` image directories (or *.txt files with image paths) and 2) a class `names` dictionary:
```yaml
# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: ../datasets/coco128  # dataset root dir
train: images/train2017  # train images (relative to 'path') 128 images
val: images/train2017  # val images (relative to 'path') 128 images
test:  # test images (optional)

# Classes (80 COCO classes)
names:
  0: person
  1: bicycle
  2: car
  ...
  77: teddy bear
  78: hair drier
  79: toothbrush

```


### 1.2 Create Labels

After using a tool like [Roboflow Annotate](https://roboflow.com/annotate?ref=ultralytics) to label your images, export your labels to **YOLO format**, with one `*.txt` file per image (if no objects in image, no `*.txt` file is required). The `*.txt` file specifications are:

- One row per object
- Each row is `class x_center y_center width height` format.
- Box coordinates must be in **normalized xywh** format (from 0 - 1). If your boxes are in pixels, divide `x_center` and `width` by image width, and `y_center` and `height` by image height.
- Class numbers are zero-indexed (start from 0).

<p align="center"><img width="750" src="https://user-images.githubusercontent.com/26833433/91506361-c7965000-e886-11ea-8291-c72b98c25eec.jpg"></p>

The label file corresponding to the above image contains 2 persons (class `0`) and a tie (class `27`):

<p align="center"><img width="428" src="https://user-images.githubusercontent.com/26833433/112467037-d2568c00-8d66-11eb-8796-55402ac0d62f.png"></p>


### 1.3 Organize Directories

Organize your train and val images and labels according to the example below. YOLOv5 assumes  `/coco128` is inside a `/datasets` directory **next to** the `/yolov5` directory. **YOLOv5 locates labels automatically for each image** by replacing the last instance of `/images/` in each image path with `/labels/`. For example:
```bash
../datasets/coco128/images/im0.jpg  # image
../datasets/coco128/labels/im0.txt  # label
```

<p align="center"><img width="700" src="https://user-images.githubusercontent.com/26833433/134436012-65111ad1-9541-4853-81a6-f19a3468b75f.png"></p>
</details>

Good luck 🍀 and let us know if you have any other questions!

**Comment by lipingliulp** [comment]
Is it normal to see test performance (mAP_0.5) much higher than validation performance in the training log? I get test performance mAP_0.5 =~ 1.0 even though I test the trained model on the validation set (by setting 'test=validation_folder').

**Comment by Wageningenn** [comment]
@glenn-jocher 

Hi, I tried your suggestion to use val.py file for calculating metrics on a test set. 
I got a precision of 0.699 which is different from the precision directly calculated from the confusion matrix (0.745). 
Could you tell me the reason? Precision calculation via val.py is not TP / (TP+FP) ?
Thanks
Here are the screenshots:
<img width="1020" alt="teston2018" src="https://user-images.githubusercontent.com/47896584/226651000-0bf04abf-d615-4d57-a5df-16c09eadd33a.png">

![confusion_matrix number on 2018](https://user-images.githubusercontent.com/47896584/226651026-b8670056-31e1-4afa-af71-5242a6ee57b8.png)

**Comment by glenn-jocher** [comment]
@Wageningenn the precision outputted can be derived from the `labels` and `predictions` arrays. It could be unsynchronized with the confusion matrix if there's a difference in `labels` or `predictions` generation inside val.py compared to your confusion matrix, like bounding box matching algorithm differences. Make sure that your `labels` and `predictions` are correctly aligned, and according to YOLOv5 standard bounding box format: `class x_center y_center width height`.

```python
from sklearn.metrics import classification_report
import numpy as np

labels = np.array([0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1])  # Example ground truth
predictions = np.array([0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1])  # Example predictions

print(classification_report(labels, predictions))
```

Also, the `conf` threshold used in val.py might mismatches your evaluation. Experiment with this threshold and compare results.

Good luck and let us know if you have any other questions!
