### ISSUE TITLE
How do I change the bounding box color in pytorch 

### ISSUE THREAD

**Issue by adelchellabi** [ultralytics/yolov5#7747]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm using pytorch to detect my object , please how can i change the color of the bounding box  ?

**Comment by glenn-jocher** [comment]
@adelchellabi boxes are plotted using the Ultralytics color palette here:

https://github.com/ultralytics/yolov5/blob/d059d1da03aee9a3c0059895aa4c7c14b7f25a9e/utils/plots.py#L31-L47

**Comment by adelchellabi** [comment]
thank you for reply 
but how can i access to the colors , for example if i want to access to my classes i do model.names  ,how i can set  the color

**Comment by glenn-jocher** [comment]
The index 0-9 are repeated until your class count, i.e. you can see in L41 `c = self.palette[int(i) % self.n]`
