### ISSUE TITLE
Classes mixed up if exporting to onnx

### ISSUE THREAD

**Issue by MasIgor** [ultralytics/yolov5#7749]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

NOTE: resubmitting with sample data as reqeusted.
---------------------------------------------------

Hello!

I trained my network and then converted the pt file (s model) to onnx using yolo's export script like this:

python export.py --weights EPS_ALL.pt --data EPS_ALL.yaml --include onnx

then I run inference using the onnx file instead of the pt file, as on my pc without GPU its almost 3 times faster. (90 ms instead of 230 ms) The detection works, and the confidence is as high as it was with the pt file, but the classes are all mixed up.

In both cases I pass in the same yaml file as data, ans as seen above it has also been used for the conversion. but If I run inference with the onnx then the output result does not match the listing in the yaml file.
Given that it only outputs a single class on any given location, and with a really high score, I am sure that its a problem related to the order of the classes. so class 5 in the onnx file does not match the class 5 in the yaml file.

What am I doing wrong?

### Minimal Reproducible Example

download this file: www.igormasin.it/fileuploads/onnx.zip

it contains one image, one .pt file, and one yaml file.

convert the .pt file to onnx with this code:

python export.py --weights EPS_ALL.pt --data EPS_ALL.yaml --include onnx

run inference of the provided image with the .pt file and with the .onnx file and compare the results.

python detect.py --source image.png --weights EPS_ALL.pt--data EPS_ALL.yaml
python detect.py --source image.png --weights EPS_ALL.onnx --data EPS_ALL.yaml

The .pt file returns a class name of "136" (correct)
the .onnx file returns a class name of "13604" (incorrect)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@tanzerlana before you do anything else, --data is an optional argument only used for TFLite exports. There's no reason to use it in your export workflow.

**Comment by MasIgor** [comment]
@glenn-jocher oh thank you.. I just tried exporting again without the --data but the result is the same.

**Comment by glenn-jocher** [comment]
@tanzerlana ok I'll take a look

**Comment by glenn-jocher** [comment]
![image](https://user-images.githubusercontent.com/26833433/167625654-8b5689ef-4774-4c3f-8134-bcdfdb67f0bd.png)

**Comment by glenn-jocher** [comment]
<img width="770" alt="Screenshot 2022-05-10 at 14 14 25" src="https://user-images.githubusercontent.com/26833433/167625750-ed9539f1-d886-42db-b94b-bff29b48fe32.png">

**Comment by MasIgor** [comment]
thats odd... could you please share your onnx file?

**Comment by glenn-jocher** [comment]
@tanzerlana your issue is not reproducible.

**Comment by MasIgor** [comment]
@glenn-jocher not entirely sure that I understand your screenshot:

you run it with the onnx file, and with the coco128.yaml file. the result says 136 as detected class.. but 136 is not present as class in the coco128.yaml file.

what am I missing here?
 
EDIT: I reuploaded the zip file, this time including also my onnx file exported with the command above. same Url as before

**Comment by MasIgor** [comment]
![image](https://user-images.githubusercontent.com/67956327/167629259-219e94a3-77b5-499a-9d14-9c85858cb20b.png)

![image](https://user-images.githubusercontent.com/67956327/167629409-d0fea6f6-b629-4925-ac68-1116c753a33c.png)

**Comment by MasIgor** [comment]
The problem has been fixed by updating yolo to the latest version. The version i had was from beginning of march.

**Comment by glenn-jocher** [comment]
@MasIgor i'm glad to hear that updating to the latest version resolved the issue. If you encounter any further questions or concerns, feel free to ask for assistance.
