### ISSUE TITLE
question on testing

### ISSUE THREAD

**Issue by Mounthazeer** [ultralytics/yolov5#7750]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

how to calculate the precision recall and map for a video instead of an image test set?

i want to be able to perform testing on video to get those values

**Comment by glenn-jocher** [comment]
@Mounthazeer do you have ground truth labels for your video?

**Comment by Mounthazeer** [comment]
no i dont have any labels for the video
do you think it is a good idea if i extract each frame from the video and then create a test set with the extracted frames and use val.py on this test set 

if not please suggest how can i derive the precision recall and map from a video

**Comment by glenn-jocher** [comment]
@Mounthazeer metrics evaluate the difference between labels and predictions. What do you expect to do with no labels?

**Comment by Mounthazeer** [comment]
if after extracting the frames i create a test set where i manually label the images

this is just a though, how do you suggest i should test a video?

**Comment by Mounthazeer** [comment]
to clarify:
to test a video, i extract each frame from the video and create a test set which is labeled manually and then use this test set with val.py
is this ok?

**Comment by glenn-jocher** [comment]
Yes that's right!

**Comment by Mounthazeer** [comment]
ok thanks

**Comment by glenn-jocher** [comment]
@Mounthazeer you're welcome! If you have any more questions, feel free to ask. Good luck with your testing!
