### ISSUE TITLE
sequence of val.py

### ISSUE THREAD

**Issue by johnjunior5** [ultralytics/yolov5#7751]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hello,
when using val.py, is the images tested in sequence like the test is performed on the first image then second... till last
or is testing performed at random for a test set of images?

**Comment by glenn-jocher** [comment]
@johnjunior5 all images are validated in whatever set you select (train, val, test).

**Comment by johnjunior5** [comment]
thanks but i want to know in which sequence in a set
lets say the test set
is it using the first image and then the second then third .... and so on
or is it testing on random images in the set

**Comment by glenn-jocher** [comment]
@johnjunior5 sorted by aspect ratio for speed, but irrelevant for mAP considerations.
