### ISSUE TITLE
Save image features with Image name

### ISSUE THREAD

**Issue by alifarooq93** [ultralytics/yolov5#7752]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,

I am trying to save image features of detect layer with respect to image names.

I tried to pass image paths from train.py to yolo.py like
pred = model(imgs, paths)  # forward
but it cause a problem with callbacks and initial running. 
Is there any way to access current batch image names in yolo.py file without passing the additional argument.

I saw features_visualization function but it saving features with respect to stage and module name. I want to have those features with image names to perform clustering.

Does anyone know how can I access it. Thank you

**Comment by glenn-jocher** [comment]
@alifarooq93 👋 Hello! Thanks for asking about **feature visualization**. YOLOv5 🚀 features can be visualized through all stages of the model from input to output. To visualize features from a given source run `detect.py` with the `--visualize` flag:
```bash
python detect.py --weights yolov5s.pt --source data/images/bus.jpg --visualize
```

An example [Notebook](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb) visualizing [bus.jpg](https://github.com/ultralytics/yolov5/blob/master/data/images/bus.jpg) features with YOLOv5s is shown below:

<a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
<img width="1811" alt="Screenshot 2021-08-30 at 16 44 04" src="https://user-images.githubusercontent.com/26833433/131357928-663a120a-3133-4e1a-8995-c812bd732e8a.png">

All stages are visualized by default, each with its own PNG showing the first 32 feature maps **output** from that stage. You can open any PNG for a closer look. For example the first 32 feature maps of the Focus() layer output are shown in `stage0_Focus_features.png`:

![stage0_Focus_features](https://user-images.githubusercontent.com/26833433/131359874-ecc9aef8-1c9b-44f5-ac17-d6b987093554.png)

Feature maps may be customized by updating the `feature_visualization()` function in `utils/plots.py`:
https://github.com/ultralytics/yolov5/blob/bb5ebc290e5d630a081d7cbc5a9725ed8cea0a24/utils/plots.py#L403-L427

Good luck 🍀 and let us know if you have any other questions!

**Comment by alifarooq93** [comment]
Thank you for your response. As I understand your answer it is only possible on already trained model but basically I am trying to extract features during mu custom data training. I already got the features from detect model as you suggest me before during training but to save those features in tensor or numpy I need a file name to distinguish the features.

**Comment by glenn-jocher** [comment]
@alifarooq93 Got it! If you want to extract features during your custom data training, you can access the batch image names in `yolo.py` using the `img_names` attribute. This can be used to distinguish the features and save them in a tensor or numpy array. For example, you can modify the `forward` function in `yolo.py` to save the features along with the corresponding image names.

You can access the image names in `yolo.py` by using `self.img_names` within the `forward` function. This attribute stores the names of the images in the current batch, which you can use to create a mapping between the image names and their respective features.

Remember to handle the features and image names appropriately to save them in a way that allows you to perform clustering later. Let me know if you need further assistance with this!
