### ISSUE TITLE
difference between precision and average precision

### ISSUE THREAD

**Issue by Mounthazeer** [ultralytics/yolov5#7753]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

lets say we have only one class
can someone tell me the difference between precision and average precision for that class

when testing we get precision and mAP (which is AP if there is only one class)
can someone explain the difference between precision and the average precision that we get for a class when we are testing?

### Additional

i was reading a paper it made no distinction between average precision and precision considering there is one class only
it considered average precision 0.5 and precision to be the same, it that wrong?

**Comment by glenn-jocher** [comment]
@Mounthazeer average precision across the P-R curve
