### ISSUE TITLE
The yolov5x6.pt model seems to perform better in the 640 image size than the 1280

### ISSUE THREAD

**Issue by hi-one-gg** [ultralytics/yolov5#7758]
I've downloaded this repo(version 6.1).

The yolov5x6.pt model seems to perform better in the 640 image size than the 1280.

Is the yolov5x6.pt model trained in 640 image size?

I understood that yolov5x6.pt model was trained in size 1280 by looking at the table below, but did I misunderstand it?

![image](https://user-images.githubusercontent.com/13531174/167775401-db53d529-74c0-4203-af53-faed020f5fc7.png)

**Comment by infrontofme** [comment]
1, P6 models are trained with image-size 1280.
2. How did you come to the conclusion that the yolov5x6 with 640 is better than that with 1280.

**Comment by glenn-jocher** [comment]
@infrontofme p6 models are indeed trained with an image size of 1280, as indicated in the repository documentation. I'd be interested in understanding your specific observations and any insights you might have to help investigate this further. Any additional information you can provide would be greatly appreciated. Thank you!
