### ISSUE TITLE
How can i get frames from video in detect.py? 

### ISSUE THREAD

**Issue by LimJihu** [ultralytics/yolov5#7760]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hello. i'm sytuding object detection. i want to get detected frames from video. this mean i want to input(source) = video,and wanna get output(runs_detect) = detected frames . i don,t how how to change this code. 
![image](https://user-images.githubusercontent.com/89961242/167781690-d730db68-0d60-4071-a112-580961a316b5.png)

i think i should change if vid_cap, but i don't know how to... 

please help me

**Comment by glenn-jocher** [comment]
@LimJihu detect.py runs inference on videos:
```
python detect.py --source video.mp4
```

**Comment by LimJihu** [comment]
i already typed like python detect.py --source video.mp4. 
and then i can find a detected-video file in runs_detect_exp 
but i want to get the detected-frames(images) from source video. not detected video TT 

thanks for your comment

**Comment by glenn-jocher** [comment]
@LimJihu breaking a video into its component frames is an elementary cv2 task and beyond the scope of YOLOv5 support.

**Comment by LimJihu** [comment]
> 
ah ha. i see. i'ii try for it

**Comment by glenn-jocher** [comment]
@LimJihu good luck with your project! If you need any further assistance with YOLOv5, feel free to reach out.
