### ISSUE TITLE
Is it Possible to Automatically Rename Yolo Labels?

### ISSUE THREAD

**Issue by joneswilliam1** [ultralytics/yolov5#7762]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi everyone,

My apologies as this question may not directly be related to this yolov5 repo, but I've tried searching all over the internet and could not find this answer. I have recently annotated over thousands of images with the following label map:
```
Car
Motorcycle
Bus
Truck
```
I have just come to notice that my team have been using the following label map with the last 2 classes swapped:
```
Car
Motorcycle
Truck
Bus
````
We are planning to combine our data and I have been looking for solutions to resolve this issue automatically instead of needing to do it manually one by one, therefore any advice would be highly appreciated.

Thanks and Best Regards,
William

**Comment by Zephyr69** [comment]
You can write a script that parses through .txt files and just swaps the relavent class numbers (in this case,  3 to 2 or 2 to 3) for either your dataset or theirs. It's the first number in each line.

**Comment by joneswilliam1** [comment]
@Zephyr69

Noted on that, thank you very much, if you could also re-direct me to an available open source codes that I could maybe refer to to accomplish this task that would also be really appreciated. Thanks again!

**Comment by explain116** [comment]
> @Zephyr69
> 
> Noted on that, thank you very much, if you could also re-direct me to an available open source codes that I could maybe refer to to accomplish this task that would also be really appreciated. Thanks again!

In fact, it's not complex. Just believe in your team. A simple python script may work.

**Comment by joneswilliam1** [comment]
@explain116 @Zephyr69 Thanks for the advice guys, I'm quite new to Python but nevertheless I did manage to write the python script for this and achieved my objectives. Thanks again!
