### ISSUE TITLE
evolve reports an OSError: cannot allocate  memory

### ISSUE THREAD

**Issue by infrontofme** [ultralytics/yolov5#7763]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Evolution

### Bug

(yolov5-th) [wang@gpu2 yolov5]$ python train.py --epochs 10 --data data/hw10cls2.yaml --weights pretrained_weights/v61_yolov5x6.pt --evolve --cache
train: weights=pretrained_weights/v61_yolov5x6.pt, cfg=, data=data/hw10cls2.yaml, hyp=data/hyps/hyp.scratch.yaml, epochs=10, batch_size=16, imgsz=640, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, evolve=300, bucket=, cache=ram, image_weights=False, device=, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=8, project=runs/train, name=exp, exist_ok=False, quad=False, linear_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest
github: skipping check (offline), for updates see https://github.com/ultralytics/yolov5
YOLOv5 🚀 2022-4-29 torch 1.10.1 CUDA:0 (NVIDIA GeForce RTX 3090, 24268MiB)

hyperparameters: lr0=0.01, lrf=0.1, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, anchors=3
Weights & Biases: run 'pip install wandb' to automatically track and visualize YOLOv5 🚀 runs (RECOMMENDED)
Overriding model.yaml nc=80 with nc=10
Overriding model.yaml anchors with anchors=3

                 from  n    params  module                                  arguments                     
  0                -1  1      8800  models.common.Conv                      [3, 80, 6, 2, 2]              
  1                -1  1    115520  models.common.Conv                      [80, 160, 3, 2]               
  2                -1  4    309120  models.common.C3                        [160, 160, 4]                 
  3                -1  1    461440  models.common.Conv                      [160, 320, 3, 2]              
  4                -1  8   2259200  models.common.C3                        [320, 320, 8]                 
  5                -1  1   1844480  models.common.Conv                      [320, 640, 3, 2]              
  6                -1 12  13125120  models.common.C3                        [640, 640, 12]                
  7                -1  1   5531520  models.common.Conv                      [640, 960, 3, 2]              
  8                -1  4  11070720  models.common.C3                        [960, 960, 4]                 
  9                -1  1  11061760  models.common.Conv                      [960, 1280, 3, 2]             
 10                -1  4  19676160  models.common.C3                        [1280, 1280, 4]               
 11                -1  1   4099840  models.common.SPPF                      [1280, 1280, 5]               
 12                -1  1   1230720  models.common.Conv                      [1280, 960, 1, 1]             
 13                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 14           [-1, 8]  1         0  models.common.Concat                    [1]                           
 15                -1  4  11992320  models.common.C3                        [1920, 960, 4, False]         
 16                -1  1    615680  models.common.Conv                      [960, 640, 1, 1]              
 17                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 18           [-1, 6]  1         0  models.common.Concat                    [1]                           
 19                -1  4   5332480  models.common.C3                        [1280, 640, 4, False]         
 20                -1  1    205440  models.common.Conv                      [640, 320, 1, 1]              
 21                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 22           [-1, 4]  1         0  models.common.Concat                    [1]                           
 23                -1  4   1335040  models.common.C3                        [640, 320, 4, False]          
 24                -1  1    922240  models.common.Conv                      [320, 320, 3, 2]              
 25          [-1, 20]  1         0  models.common.Concat                    [1]                           
 26                -1  4   4922880  models.common.C3                        [640, 640, 4, False]          
 27                -1  1   3687680  models.common.Conv                      [640, 640, 3, 2]              
 28          [-1, 16]  1         0  models.common.Concat                    [1]                           
 29                -1  4  11377920  models.common.C3                        [1280, 960, 4, False]         
 30                -1  1   8296320  models.common.Conv                      [960, 960, 3, 2]              
 31          [-1, 12]  1         0  models.common.Concat                    [1]                           
 32                -1  4  20495360  models.common.C3                        [1920, 1280, 4, False]        
 33  [23, 26, 29, 32]  1    144180  models.yolo.Detect                      [10, [[0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5]], [320, 640, 960, 1280]]
Model Summary: 733 layers, 140121940 parameters, 140121940 gradients, 208.5 GFLOPs

Transferred 954/963 items from pretrained_weights/v61_yolov5x6.pt
Scaled weight_decay = 0.0005
optimizer: SGD with parameter groups 159 weight (no decay), 163 weight, 163 bias
WARNING: DP not recommended, use torch.distributed.run for best DDP Multi-GPU results.
See Multi-GPU Tutorial at https://github.com/ultralytics/yolov5/issues/475 to get started.
train: Scanning '/public/home/wang/workspace/datasets/HWData/src-aug/train-02/train.cache' images and labels... 5163 found,
train: Caching images (4.8GB ram): 100%|██████████████████████████████████████████████| 5163/5163 [00:07<00:00, 697.33it/s]
val: Scanning '/public/home/wang/workspace/datasets/HWData/src-aug/val/val.cache' images and labels... 573 found, 0 missing

AutoAnchor: 0.26 anchors/target, 0.056 Best Possible Recall (BPR). Anchors are a poor fit to dataset ⚠️, attempting to improve...
AutoAnchor: WARNING: Extremely small objects found. 4 of 7580 labels are < 3 pixels in size.
AutoAnchor: Running kmeans for 12 anchors on 7580 points...
AutoAnchor: Evolving anchors with Genetic Algorithm: fitness = 0.7516: 100%|█████████| 1000/1000 [00:00<00:00, 1097.21it/s]
AutoAnchor: thr=0.25: 0.9963 best possible recall, 6.73 anchors past thr
AutoAnchor: n=12, img_size=640, metric_all=0.328/0.752-mean/best, past_thr=0.490-mean: 18,20, 63,58, 175,84, 98,167, 330,124, 141,364, 283,216, 532,141, 259,423, 530,210, 521,291, 509,450
AutoAnchor: New anchors saved to model. Update model *.yaml to use these anchors in the future.
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to runs/evolve/exp
Starting training for 10 epochs...

     Epoch   gpu_mem       box       obj       cls    labels  img_size
       0/9     5.98G   0.06368   0.02637   0.04951        44       640: 100%|██████████| 323/323 [03:42<00:00,  1.45it/s]  

     Epoch   gpu_mem       box       obj       cls    labels  img_size
       1/9     5.98G   0.04913   0.01986   0.02679        36       640: 100%|██████████| 323/323 [03:10<00:00,  1.69it/s]  

     Epoch   gpu_mem       box       obj       cls    labels  img_size
       2/9     5.98G   0.04436   0.01967   0.02302        34       640: 100%|██████████| 323/323 [03:09<00:00,  1.70it/s]  

     Epoch   gpu_mem       box       obj       cls    labels  img_size
       3/9     5.98G   0.04121   0.02036   0.02201        21       640: 100%|██████████| 323/323 [03:08<00:00,  1.71it/s]  

     Epoch   gpu_mem       box       obj       cls    labels  img_size
       4/9     5.98G   0.03838   0.02031   0.02027        30       640: 100%|██████████| 323/323 [03:11<00:00,  1.69it/s]  

     Epoch   gpu_mem       box       obj       cls    labels  img_size
       5/9     5.98G   0.03564   0.01953   0.01708        64       640: 100%|██████████| 323/323 [03:10<00:00,  1.69it/s]  

     Epoch   gpu_mem       box       obj       cls    labels  img_size
       6/9     5.98G    0.0332   0.01905   0.01482        32       640: 100%|██████████| 323/323 [03:11<00:00,  1.69it/s]  

     Epoch   gpu_mem       box       obj       cls    labels  img_size
       7/9     5.98G   0.03121   0.01863   0.01366        42       640: 100%|██████████| 323/323 [03:10<00:00,  1.70it/s]  

     Epoch   gpu_mem       box       obj       cls    labels  img_size
       8/9     5.98G   0.02919   0.01798   0.01115        26       640: 100%|██████████| 323/323 [03:10<00:00,  1.69it/s]  

     Epoch   gpu_mem       box       obj       cls    labels  img_size
       9/9     5.98G   0.02791   0.01773   0.01014        26       640: 100%|██████████| 323/323 [03:10<00:00,  1.70it/s]  
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 18/18 [00:06<00:00
                 all        573        839      0.805      0.743      0.819      0.504

10 epochs completed in 0.540 hours.
Results saved to runs/evolve/exp
evolve: 1 generations finished, current result:
evolve:    metrics/precision,       metrics/recall,      metrics/mAP_0.5, metrics/mAP_0.5:0.95,         val/box_loss,         val/obj_loss,         val/cls_loss,                  lr0,                  lrf,             momentum,         weight_decay,        warmup_epochs,      warmup_momentum,       warmup_bias_lr,                  box,                  cls,               cls_pw,                  obj,               obj_pw,                iou_t,             anchor_t,             fl_gamma,                hsv_h,                hsv_s,                hsv_v,              degrees,            translate,                scale,                shear,          perspective,               flipud,               fliplr,               mosaic,                mixup,           copy_paste,              anchors
evolve:              0.80545,              0.74312,              0.81943,              0.50413,             0.028348,            0.0092005,            0.0096469,                 0.01,                  0.1,                0.937,               0.0005,                    3,                  0.8,                  0.1,                 0.05,                  0.5,                    1,                    1,                    1,                  0.2,                    4,                    0,                0.015,                  0.7,                  0.4,                    0,                  0.1,                  0.5,                    0,                    0,                    0,                  0.5,                    1,                    0,                    0,                    3

hyperparameters: lr0=0.01045, lrf=0.09885, momentum=0.91671, weight_decay=0.00057, warmup_epochs=2.98679, warmup_momentum=0.80775, warmup_bias_lr=0.1, box=0.05, cls=0.54336, cls_pw=0.95189, obj=1.13926, obj_pw=1.0, iou_t=0.2, anchor_t=3.47304, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.66387, hsv_v=0.36894, degrees=0.0, translate=0.1, scale=0.51162, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, anchors=3.0
Weights & Biases: run 'pip install wandb' to automatically track and visualize YOLOv5 🚀 runs (RECOMMENDED)
Overriding model.yaml nc=80 with nc=10
Overriding model.yaml anchors with anchors=3.0

                 from  n    params  module                                  arguments                     
  0                -1  1      8800  models.common.Conv                      [3, 80, 6, 2, 2]              
  1                -1  1    115520  models.common.Conv                      [80, 160, 3, 2]               
  2                -1  4    309120  models.common.C3                        [160, 160, 4]                 
  3                -1  1    461440  models.common.Conv                      [160, 320, 3, 2]              
  4                -1  8   2259200  models.common.C3                        [320, 320, 8]                 
  5                -1  1   1844480  models.common.Conv                      [320, 640, 3, 2]              
  6                -1 12  13125120  models.common.C3                        [640, 640, 12]                
  7                -1  1   5531520  models.common.Conv                      [640, 960, 3, 2]              
  8                -1  4  11070720  models.common.C3                        [960, 960, 4]                 
  9                -1  1  11061760  models.common.Conv                      [960, 1280, 3, 2]             
 10                -1  4  19676160  models.common.C3                        [1280, 1280, 4]               
 11                -1  1   4099840  models.common.SPPF                      [1280, 1280, 5]               
 12                -1  1   1230720  models.common.Conv                      [1280, 960, 1, 1]             
 13                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 14           [-1, 8]  1         0  models.common.Concat                    [1]                           
 15                -1  4  11992320  models.common.C3                        [1920, 960, 4, False]         
 16                -1  1    615680  models.common.Conv                      [960, 640, 1, 1]              
 17                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 18           [-1, 6]  1         0  models.common.Concat                    [1]                           
 19                -1  4   5332480  models.common.C3                        [1280, 640, 4, False]         
 20                -1  1    205440  models.common.Conv                      [640, 320, 1, 1]              
 21                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 22           [-1, 4]  1         0  models.common.Concat                    [1]                           
 23                -1  4   1335040  models.common.C3                        [640, 320, 4, False]          
 24                -1  1    922240  models.common.Conv                      [320, 320, 3, 2]              
 25          [-1, 20]  1         0  models.common.Concat                    [1]                           
 26                -1  4   4922880  models.common.C3                        [640, 640, 4, False]          
 27                -1  1   3687680  models.common.Conv                      [640, 640, 3, 2]              
 28          [-1, 16]  1         0  models.common.Concat                    [1]                           
 29                -1  4  11377920  models.common.C3                        [1280, 960, 4, False]         
 30                -1  1   8296320  models.common.Conv                      [960, 960, 3, 2]              
 31          [-1, 12]  1         0  models.common.Concat                    [1]                           
 32                -1  4  20495360  models.common.C3                        [1920, 1280, 4, False]        
 33  [23, 26, 29, 32]  1    144180  models.yolo.Detect                      [10, [[0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5]], [320, 640, 960, 1280]]
Model Summary: 733 layers, 140121940 parameters, 140121940 gradients, 208.5 GFLOPs

Transferred 954/963 items from pretrained_weights/v61_yolov5x6.pt
Scaled weight_decay = 0.00057
optimizer: SGD with parameter groups 159 weight (no decay), 163 weight, 163 bias
WARNING: DP not recommended, use torch.distributed.run for best DDP Multi-GPU results.
See Multi-GPU Tutorial at https://github.com/ultralytics/yolov5/issues/475 to get started.
train: Scanning '/public/home/wang/workspace/datasets/HWData/src-aug/train-02/train.cache' images and labels... 5163 found,
train: Caching images (4.8GB ram): 100%|██████████████████████████████████████████████| 5163/5163 [00:06<00:00, 834.07it/s]
val: Scanning '/public/home/wang/workspace/datasets/HWData/src-aug/val/val.cache' images and labels... 573 found, 0 missing
Traceback (most recent call last):
  File "train.py", line 643, in <module>
    main(opt)
  File "train.py", line 620, in main
    results = train(hyp.copy(), opt, device, callbacks)
  File "train.py", line 237, in train
    prefix=colorstr('val: '))[0]
  File "/public/home/wang/workspace/yolov5/utils/datasets.py", line 122, in create_dataloader
    collate_fn=LoadImagesAndLabels.collate_fn4 if quad else LoadImagesAndLabels.collate_fn), dataset
  File "/public/home/wang/workspace/yolov5/utils/datasets.py", line 134, in __init__
    self.iterator = super().__iter__()
  File "/public/software/apps/anaconda3/2021.05/envs/yolov5-th/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "/public/software/apps/anaconda3/2021.05/envs/yolov5-th/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/public/software/apps/anaconda3/2021.05/envs/yolov5-th/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 918, in __init__
    w.start()
  File "/public/software/apps/anaconda3/2021.05/envs/yolov5-th/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/public/software/apps/anaconda3/2021.05/envs/yolov5-th/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/public/software/apps/anaconda3/2021.05/envs/yolov5-th/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/public/software/apps/anaconda3/2021.05/envs/yolov5-th/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/public/software/apps/anaconda3/2021.05/envs/yolov5-th/lib/python3.7/multiprocessing/popen_fork.py", line 70, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

### Environment

YOLOv5 🚀 2022-4-29 torch 1.10.1 CUDA:0 (NVIDIA GeForce RTX 3090, 24268MiB)
OS: CentOS Linux release 7.6.1810(Core)
Python: 3.7.11

### Minimal Reproducible Example

python train.py --epochs 10 --data data/hw10cls2.yaml --weights pretrained_weights/v61_yolov5x6.pt --evolve --cache

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@infrontofme your system is out of resources
```
OSError: [Errno 12] Cannot allocate memory
```

**Comment by infrontofme** [comment]
I check the consumption of memory resources by `free -m`, it is enough to allocate.
free -m
              total        used        free      shared  buff/cache   available
Mem:         257411        4962      212492         361       39957      250754
Swap:         65531           0       65531。

CUDA memory is also enough.

But it reported this error. How can I debug？

**Comment by glenn-jocher** [comment]
@infrontofme there's nothing to debug. Get a system with more resources or issue a command that requires less resources.

**Comment by sarpx** [comment]
batch_size=12 or batch_size=8 or batch_size=6 or batch_size=4
:)

**Comment by LUO77123** [comment]
I have the same problem（OSError: [Errno 12] Cannot allocate memory）. I use A100-40G single card to train 32 images at a time, but using ddp-8 card to train 128 images will report such an error. I don't know the reason.  Finally, I set （num_workers=nw） to （num_workers=0） in dataset.py, and I can run, but the speed of 8 cards is the same as that of one card, , and I don't understand the reason.
nvidia-smi
11.6
Pytorch version:
1.10.1+cu113
CUDA version:
11.3
cuDNN version is :
8200

**Comment by glenn-jocher** [comment]
@LUO77123 you've saturated your resources, i.e. RAM, CPUs etc. Reduce resource usage.

**Comment by LUO77123** [comment]
> @LUO77123 you've saturated your resources, i.e. RAM, CPUs etc. Reduce resource usage.

dataset.py
nw = min([os.cpu_count() // max(nd, 1), batch_size if batch_size > 1 else 0, workers])
num_workers=nw,
(os.cpu_count()=56,batch_size=32,workers=8,nd=4or8),
When I set num_workers=0 or num_workers=8 ,and I can run,
