### ISSUE TITLE
Having trouble understanding the code for this part.

### ISSUE THREAD

**Issue by d5423197** [ultralytics/yolov5#7765]
https://github.com/ultralytics/yolov5/blob/d059d1da03aee9a3c0059895aa4c7c14b7f25a9e/utils/loss.py#L211-L217

Hello there,

I am having trouble understanding the build_targets function, especially for this part. Is there any resource/doc that explains it well?

Was trying to look for YOLO v5 paper for a better explanation but failed.

Any help will be appreciated!

Thanks,

ZD

**Comment by glenn-jocher** [comment]
@d5423197 there's no docs for build_targets(), but it's main function is simply to pair labels to their target anchors so we know which pairs to compute losses for.

**Comment by d5423197** [comment]
I hope there is a paper/article/blog/etc for YOLO V5 which can help some of us understand the concept behind it.

**Comment by glenn-jocher** [comment]
@d5423197 there's no official paper, but the Ultralytics Docs, available at https://docs.ultralytics.com/yolov5/, offer extensive details on YOLOv5's concepts and implementation, which could help clarify any confusion.
