### ISSUE TITLE
Pre-defined bounding box

### ISSUE THREAD

**Issue by Aoi-00** [ultralytics/yolov5#7766]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I wanted to set a pre-defined bounding box at the start for chairs. It will update itself gradually over time (based on the bounding boxes of 'chairs' found).

If there is a human detected within this defined bounding box for chairs, it will return chair occupied as True. May I ask how do I do this?

**Comment by glenn-jocher** [comment]
@Aoi-00 hi there! To set a predefined bounding box for chairs and update it over time based on the detected chairs, you can use a simple tracker to maintain the bounding box coordinates. Then, you can check if a human is within the defined bounding box using the detected human's bounding box coordinates. You can find more details on tracking in the YOLOv5 documentation under the "Tracking" section at https://docs.ultralytics.com/yolov5/. Let me know if you have any further questions!
