### ISSUE TITLE
is yolov5 have those improvments 

### ISSUE THREAD

**Issue by VYRION-Ai** [ultralytics/yolov5#7768]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

i saw this paper from twitter 
[link](https://twitter.com/FireTechnology/status/1523952231699132417)
and this is the paper link 
[link](https://link.springer.com/article/10.1007/s10694-022-01260-z)
 the paper say :

**Abstract. Accidental fire outbreak threatens people’s life and property safety, and it
is of great significance to study fire detection and alarm early. The detection range of
traditional fire detectors is limited, and the conventional detection algorithm has the
problems of low precision and long detection time. Aiming at these problems, a video
fire detection method based on improved YOLOv5 is proposed in this paper. To
improve the ability of feature extraction and small-scale target detection, the dilated
convolution module is introduced into the SPP module of YOLOv5, the activation
function GELU and the prediction bounding box suppression DIoU-NMS are
employed in the structure of the improved YOLOv5. The experimental results show
that the algorithm has fast detection speed and high detection accuracy. It can accu-
rately detect not only large-scale flame but also small-scale flame in the early stage of
fire. The precision and recall of the improved small YOLOv5 are 0.983 and 0.992, the
mAP@.5 is as high as 0.993, and the detection speed reaches 125 FPS. The proposed
method can well suppress false detection and missed detection in complex lighting
environments and improve the robustness and reliability of fire detection, meet the
performance requirements of the video fire detection task.**

now dose  yolov5 have this or how i can add it . thank you

**Comment by glenn-jocher** [comment]
@totoadel if the publication is talking about modifications to YOLOv5 then obviously the base YOLOv5 does not include the modifications. Contact the authors directly for details as this is a 3rd party work outside the scope of our support.

**Comment by VYRION-Ai** [comment]
DIoU-NMS
GELU
@glenn-jocher 
Does YOLO V5 have any of those?

**Comment by glenn-jocher** [comment]
@VYRION-Ai Both DIoU-NMS and GELU are included in YOLOv5. DIoU-NMS (Distance-IoU NMS) is a bounding box suppression technique employed in the structure of YOLOv5, and GELU (Gaussian Error Linear Units) is used as an activation function in the YOLOv5 network. For more details on how they are utilized in YOLOv5, you can refer to the Ultralytics Docs at https://docs.ultralytics.com/yolov5/. Let me know if you need any further assistance!
