### ISSUE TITLE
 Having trouble understanding the code for this part. 

### ISSUE THREAD

**Issue by suzijun** [ultralytics/yolov5#7769]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

 # Convert
        img = img.transpose((2, 0, 1))[::-1]  # HWC to CHW, BGR to RGB
I tried it with an image, the latter part [::-1] is about inverting the image rather than converting BGR to RGB. I'm trying to figure out what this part means.

**Comment by glenn-jocher** [comment]
BGR to RGB. `x[::-1]` reverses the order of a dimension
