### ISSUE TITLE
Export with `--dynamic` flag interferes with CoreML

### ISSUE THREAD

**Issue by addisonklinke** [ultralytics/yolov5#7770]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Export

### Bug

Adding `--dynamic` flag to the export script works for ONNX, but causes CoreML to fail as a side effect

### Environment

- YOLO: YoloV5 v6.1-d059d1da  
- OS: Ubuntu 20.04
- Python: 3.9.5
- PyTorch: 1.11.0+cu113
- CoreML: 5.2.0

### Minimal Reproducible Example

Run a training on COCO following the instructions in the readme. Then attempt the following export command

```
python export.py --include onnx coreml --weights runs/train/exp/weights/best.pt --dynamic
```

This will fail on CoreML with 

```
CoreML: export failure: 'list' object has no attribute 'val'
```

### Additional

I resolved the bug by adding the following to the start of [`export.py:export_coreml()`](https://github.com/ultralytics/yolov5/blob/v6.1/export.py#L174)

```python
detector = model.model[-1]
if isinstance(detector, Detect):
    detector.onnx_dynamic = False
```

This reverts the change made globally inside [`run()`](https://github.com/ultralytics/yolov5/blob/v6.1/export.py#L469) just for the CoreML format while leaving ONNX and others unchanged

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@addisonklinke oh interesting, thanks for investigating a fix! Can you please submit a PR with your fix?
