### ISSUE TITLE
Raw prediction

### ISSUE THREAD

**Issue by myasser63** [ultralytics/yolov5#7775]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How can I use yolov5 in inference to get the results without post preprocessing by NMS?

**Comment by glenn-jocher** [comment]
@myasser63 obviously access the predictions before they pass to NMS:
https://github.com/ultralytics/yolov5/blob/4870064629e76d9d387578c562a292cc680fa05f/detect.py#L120-L129
