### ISSUE TITLE
How can i detect just person in Yolov5? 

### ISSUE THREAD

**Issue by LimJihu** [ultralytics/yolov5#7776]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hi. i'm strudying about AI-CCTV research. and i want to detect just person class. i don't want to detect other class. 

but i don't know how... i changed coco128.yaml. 
![image](https://user-images.githubusercontent.com/89961242/168008186-3cdd6ca7-8c0f-430f-80c7-4b6a4ce7cf44.png)

like this. but when i check the detect result, it still detects all kind of class. 
can anybody help me??

**Comment by shashankrajput-iitk** [comment]
@LimJihu Have u only labelled the data for the person only? Please check your labelling once.

**Comment by glenn-jocher** [comment]
@LimJihu `python detect.py --weights yolov5s.pt --classes 0`

**Comment by LimJihu** [comment]
> @LimJihu `python detect.py --weights yolov5s.pt --classes 0`

i found it! thanks!!!

**Comment by LimJihu** [comment]
@Shanky71 i wannt detect just only person. the data is non_labelled image
