### ISSUE TITLE
How to add map0.5:0.95 curve to the final line graph

### ISSUE THREAD

**Issue by fynlmq** [ultralytics/yolov5#7778]
### Search before asking

- [ ] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

![PR_V5S](https://user-images.githubusercontent.com/63281973/168013721-a30097e9-63cb-474f-941a-156865328a56.png)

**Comment by glenn-jocher** [comment]
@fynlmq you don't understand mAP. There is no such thing as a mAP curve, mAP is the area under a PR curve.

**Comment by fynlmq** [comment]
> 



> @fynlmq you don't understand mAP. There is no such thing as a mAP curve, mAP is the area under a PR curve.

Thanks for correcting! The PR curve of MAP0.75 and MAP0.95 can be drawn, but there is no PR curve for MAP0.5:0.95. Is that okay with me?

**Comment by fynlmq** [comment]
> @fynlmq you don't understand mAP. There is no such thing as a mAP curve, mAP is the area under a PR curve.

Thanks for correcting! The PR curve of MAP0.75 and MAP0.95 can be drawn, but there is no PR curve for MAP0.5:0.95.Can I understand in this way?

**Comment by fynlmq** [comment]
Sorry, I have a problem with my expression. If I want to draw Map0 5: 0.95 PR curve, and print the optimal result in the figure. How should I modify the code?

**Comment by fynlmq** [comment]
Thanks for your correction! I have a problem with my expression. If I want to draw Map0 5: 0.95 PR curve, and print the optimal result in the figure. How should I modify the code?
