### ISSUE TITLE
Generate output file of detected objectes for each image

### ISSUE THREAD

**Issue by vkramdev** [ultralytics/yolov5#778]
## ❔Question
Does the current model generate any output file containing the objects detected for each image in inference.

## Additional context
I want to pass my model inference to some downstream systems . I would like to send the inference as some kind of files.

**Comment by NanoCode012** [comment]
By default, it generates output img to a folder.

If you want to get the class number and bb in txt file, the below may be what you are looking for.

https://github.com/ultralytics/yolov5/blob/da35727c683dd38547ceebf697c25648a92b625c/detect.py#L159

**Comment by vkramdev** [comment]
@NanoCode012  Yes this is what i was looking for. Thanks
