### ISSUE TITLE
Porting model to EDGE, error on "ResizeNearestNeighborOptions"

### ISSUE THREAD

**Issue by 0chandansharma** [ultralytics/yolov5#7782]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,

after exporting the model to int POST-quantization, my Edge is not supporting ResizeNearestNeighborOptions layer form yolov5s,
I want to replace this layer with "ResizeBilinear" what could be the possibility, and how/where I can do it.

IS IT, "nearest"????
from yolo5s.yaml??

head:
  [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, C3, [512, False]],  # 13

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, C3, [256, False]],  # 17 (P3/8-small)

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 14], 1, Concat, [1]],  # cat head P4
   [-1, 3, C3, [512, False]],  # 20 (P4/16-medium)

   [-1, 1, Conv, [512, 3, 2]],
   [[-1, 10], 1, Concat, [1]],  # cat head P5
   [-1, 3, C3, [1024, False]],  # 23 (P5/32-large)

   [[17, 20, 23], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
  ]

Thanks

**Comment by 0chandansharma** [comment]
got it 
torch.nn.Upsample(size=None, scale_factor=None, mode='nearest', align_corners=None, recompute_scale_factor=None)

i can replace with 
mode ([str](https://docs.python.org/3/library/stdtypes.html#str), optional) – the upsampling algorithm: one of 'nearest', 'linear', 'bilinear', 'bicubic' and 'trilinear'. Default: 'nearest'

IS IT POSSIBLE TO REPLACE THE SAME IN THE ALREADY  TRAINED MODEL?

**Comment by glenn-jocher** [comment]
@0chandansharma train a new model

**Comment by 0chandansharma** [comment]
Got it, Thanks

**Comment by glenn-jocher** [comment]
@0chandansharma you're welcome! If you have any more questions, feel free to ask. Happy to help!
