### ISSUE TITLE
Replacing standard convolution in backbone network with DCN, but error

### ISSUE THREAD

**Issue by FairyHan** [ultralytics/yolov5#7785]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

作者您好！我想在全景数据集上利用yolov5进行目标检测，所以利用DCNv2替换了Backbone中的3×3网络，包括Bottleneck中的3×3。
我的改动如下：
1、在common.py中，from utils.dcn import DeformableConv2d（我使用的DCNv2代码链接如下：[DCNv2](https://github.com/developer0hye/PyTorch-Deformable-Convolution-v2)），接着仿照Conv模块增加了DBS模块，并在Bottleneck中的shortcut为True时，将其中的cv2替换为DCNv2。

```
class DBS(nn.Module):
    # Deformable Conv2
    def __init__(self, c1, c2, k=1, s=1, p=None, g=1, act=True):  # ch_in, ch_out, kernel, stride, padding, groups
        super().__init__()
        # self.conv = nn.Conv2d(c1, c2, k, s, autopad(k, p), groups=g, bias=False)
        # self.conv = DeformableConv2d(in_channels=32, out_channels=32, kernel_size=3, stride=1, padding=1)
        self.conv = DeformableConv2d(in_channels=c1, out_channels=c2, kernel_size=k, stride=s, padding=autopad(k, p))
        self.bn = nn.BatchNorm2d(c2)
        self.act = nn.SiLU() if act is True else (act if isinstance(act, nn.Module) else nn.Identity())

    def forward(self, x):
        return self.act(self.bn(self.conv(x)))

    def forward_fuse(self, x):
        return self.act(self.conv(x))

class Bottleneck(nn.Module):
    # Standard bottleneck
    def __init__(self, c1, c2, shortcut=True, g=1, e=0.5):  # ch_in, ch_out, shortcut, groups, expansion
        super().__init__()
        c_ = int(c2 * e)  # hidden channels
        self.cv1 = Conv(c1, c_, 1, 1)
        if shortcut==True:
         self.cv2 = Conv(c_, c2, 3, 1, g=g)
        else:
         self.cv2 = DeformableConv2d(in_channels=c_, out_channels=c2, kernel_size=3, stride=1, padding=0)
        self.add = shortcut and c1 == c2

    def forward(self, x):
        return x + self.cv2(self.cv1(x)) if self.add else self.cv2(self.cv1(x))

```

2、改写yolov5n.yaml中的backbone部分
```
backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [64, 6, 2, 2]],  # 0-P1/2
   [-1, 1, DBS, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C3, [128]],
   [-1, 1, DBS, [256, 3, 2]],  # 3-P3/8
   [-1, 6, C3, [256]],
   [-1, 1, DBS, [512, 3, 2]],  # 5-P4/16
   [-1, 9, C3, [512]],
   [-1, 1, DBS, [1024, 3, 2]],  # 7-P5/32
   [-1, 3, C3, [1024]],
   [-1, 1, SPPF, [1024, 5]],  # 9
  ]
```
3、在yolo.py中添加DBS的判断语句

但在训练过程中，却出现了张量错误，报错如下：

> train: weights=yolov5s.pt, cfg=models/yolov5n.yaml, data=coco128.yaml, hyp=data/hyps/hyp.scratch-low.yaml, epochs=3, batch_size=16, imgsz=640, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, noplots=False, evolve=None, bucket=, cache=ram, image_weights=False, device=, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=8, project=runs/train, name=exp, exist_ok=False, quad=False, cos_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest
> github: up to date with https://github.com/ultralytics/yolov5 ✅
> YOLOv5 🚀 v6.1-178-g4870064 torch 1.11.0+cu113 CUDA:0 (Tesla T4, 15110MiB)
> 
> hyperparameters: lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0
> Weights & Biases: run 'pip install wandb' to automatically track and visualize YOLOv5 🚀 runs (RECOMMENDED)
> TensorBoard: Start with 'tensorboard --logdir runs/train', view at http://localhost:6006/
> 
> Dataset not found ⚠, missing paths ['/content/datasets/coco128/images/train2017']
> Downloading https://ultralytics.com/assets/coco128.zip to coco128.zip...
> 100% 6.66M/6.66M [00:00<00:00, 278MB/s]
> Dataset download success ✅ (0.4s), saved to /content/datasets
> Downloading https://ultralytics.com/assets/Arial.ttf to /root/.config/Ultralytics/Arial.ttf...
> 100% 755k/755k [00:00<00:00, 137MB/s]
> Downloading https://github.com/ultralytics/yolov5/releases/download/v6.1/yolov5s.pt to yolov5s.pt...
> 100% 14.1M/14.1M [00:00<00:00, 275MB/s]
> 
> 
>                  from  n    params  module                                  arguments                     
>   0                -1  1      1760  models.common.Conv                      [3, 16, 6, 2, 2]              
>   1                -1  1      8587  models.common.DBS                       [16, 32, 3, 2]                
>   2                -1  1      4800  models.common.C3                        [32, 32, 1]                   
>   3                -1  1     26363  models.common.DBS                       [32, 64, 3, 2]                
>   4                -1  2     29184  models.common.C3                        [64, 64, 2]                   
>   5                -1  1     89563  models.common.DBS                       [64, 128, 3, 2]               
>   6                -1  3    156928  models.common.C3                        [128, 128, 3]                 
>   7                -1  1    326555  models.common.DBS                       [128, 256, 3, 2]              
>   8                -1  1    296448  models.common.C3                        [256, 256, 1]                 
>   9                -1  1    164608  models.common.SPPF                      [256, 256, 5]                 
>  10                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]              
>  11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
>  12           [-1, 6]  1         0  models.common.Concat                    [1]                           
>  13                -1  1    106331  models.common.C3                        [256, 128, 1, False]          
>  14                -1  1      8320  models.common.Conv                      [128, 64, 1, 1]               
>  15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
>  16           [-1, 4]  1         0  models.common.Concat                    [1]                           
>  17                -1  1     30651  models.common.C3                        [128, 64, 1, False]           
>  18                -1  1     36992  models.common.Conv                      [64, 64, 3, 2]                
>  19          [-1, 14]  1         0  models.common.Concat                    [1]                           
>  20                -1  1     89947  models.common.C3                        [128, 128, 1, False]          
>  21                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]              
>  22          [-1, 10]  1         0  models.common.Concat                    [1]                           
>  23                -1  1    327323  models.common.C3                        [256, 256, 1, False]          
>  24      [17, 20, 23]  1    115005  models.yolo.Detect                      [80, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [64, 128, 256]]
> Traceback (most recent call last):
>   File "train.py", line 667, in <module>
>     main(opt)
>   File "train.py", line 562, in main
>     train(opt.hyp, opt, device, callbacks)
>   File "train.py", line 121, in train
>     model = Model(cfg or ckpt['model'].yaml, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)  # create
>   File "/content/yolov5/models/yolo.py", line 112, in __init__
>     m.stride = torch.tensor([s / x.shape[-2] for x in self.forward(torch.zeros(1, ch, s, s))])  # forward
>   File "/content/yolov5/models/yolo.py", line 126, in forward
>     return self._forward_once(x, profile, visualize)  # single-scale inference, train
>   File "/content/yolov5/models/yolo.py", line 149, in _forward_once
>     x = m(x)  # run
>   File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/content/yolov5/models/common.py", line 158, in forward
>     return self.cv3(torch.cat((self.m(self.cv1(x)), self.cv2(x)), dim=1))
> RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 14 but got size 16 for tensor number 1 in the list.

请问我该如何处理这一问题？Sizes of tensors must match except in dimension 1. Expected size 14 but got size 16 for tensor number 1 in the list.
期待您的早日答复！

**Comment by glenn-jocher** [comment]
@FairyHan it's hard to tell without a reproducible example, but it seems like you might have incorrect padding if the output is of size 16 but expected to be 14.

**Comment by FairyHan** [comment]
确实是padding的问题，感谢您的回复！

**Comment by Zephyr69** [comment]
Did you get any usable result? Mine did not converge at all after introducing DCNv2.

**Comment by glenn-jocher** [comment]
@Zephyr69 the introduction of DCNv2 requires careful padding and kernel size adjustments. Without a reproducible example, it's hard to diagnose the issue, but it's possible that the non-convergence is related to the padding or kernel size mismatch. If you're able to share more details or provide a reproducible example, I'd be happy to assist further.

**Comment by Git376364743** [comment]
你好，请问一下你这个问题解决了吗? 如何解决的能说一下不，谢谢

**Comment by glenn-jocher** [comment]
@Git376364743 你好！👋 如果你遇到了特定的问题，请提供一些详细信息，例如你所遇到的错误和你尝试过的解决方法。这样我可以更准确地帮助你。谢谢！
