### ISSUE TITLE
How to display the source life cam video  and the detected , in a GUi ?

### ISSUE THREAD

**Issue by VYRION-Ai** [ultralytics/yolov5#7786]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to display the webcam input and the detected output in Gui?
where i can do that in the code ?

**Comment by glenn-jocher** [comment]
@totoadel not sure about the GUI part, perhaps try streamlit. 

Webcam streaming is really easy though:
```
python detect.py --source 0
```

**Comment by totoadel** [comment]
@glenn-jocher no i want to add both to one gui

**Comment by VYRION-Ai** [comment]
@glenn-jocher i want to make it local

**Comment by glenn-jocher** [comment]
@VYRION-Ai You can display the webcam input and the detected output in a local GUI using the `detect.py` script by specifying the `--source` flag with the path to your local video or webcam device index. YOLOv5 includes a simple plotting function for visualization that you can customize according to your GUI requirements. You may also consider using libraries like OpenCV or PyQT for building a custom GUI. For more details, refer to the Ultralytics YOLOv5 documentation at https://docs.ultralytics.com/yolov5/.
