### ISSUE TITLE
Getting model version from PyTorch hub model

### ISSUE THREAD

**Issue by mfoglio** [ultralytics/yolov5#7788]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When I load the model doing `model = torch.hub.load('ultralytics/yolov5', 'yolov5s')` is there a way I can get the model version (e.g. `6.1`)?

**Comment by glenn-jocher** [comment]
@mfoglio PyTorch Hub always downloads the latest models, but you can download older models manually from the release assets and then point PyTorch Hub to the local model:
```python
model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/model.pt')
```

All official YOLOv5 🚀 pretrained models including P6 models are available to download directly under the latest release in the 'Assets' section, i.e.:
https://github.com/ultralytics/yolov5/releases/tag/v6.1

<img width="1038" alt="Screen Shot 2022-05-01 at 11 48 44 AM" src="https://user-images.githubusercontent.com/26833433/166160148-45f4fba2-998f-40d0-abe1-a57c93a55fda.png">
Good luck 🍀 and let us know if you have any other questions!

**Comment by mfoglio** [comment]
Are the weights for version 6 and 6.1 the same? Because I don't see different links

**Comment by glenn-jocher** [comment]
@mfoglio no two releases use the same weights.
