### ISSUE TITLE
Resume training Assertion error but 300 epochs not complete

### ISSUE THREAD

**Issue by tylertroy** [ultralytics/yolov5#7789]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

I started training with.

```bash
python train.py --img 640 --batch 16 --data /path/to/data/dataset.yaml --weights yolov5l.pt --project /path/to/project --name model_1 --device 0
```
I expected training to take ~3 days but found today, about half way through, that training had stopped seemingly without error (except those WeakRef erros that pytorch raises). Inspection of the `results.csv` file logged 114 epochs and so I decided to use the `--resume` functionality with the following.

```bash
python train.py --resume /path/to/project/model_1/weights/last.pt
```
But the following Assertion error was raised

```bash
AssertionError: /path/to/project/model_1/weights/last.pt training to 300 epochs is finished, nothing to resume.
```

I'm not sure if it's relevant but I'll note that I had not trained with the yolov5l.pt starting weights before so they were downloaded afresh.

### Environment

- YOLOv5 🚀 v6.1-178-g4870064 torch 1.11.0+cu113 CUDA:0 (GeForce RTX 3090, 24268MiB)
- Ubuntu 18.04 LTS
- python3.8

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@tylertroy training will only be stopped prematurely by the EarlyStopper():

https://github.com/ultralytics/yolov5/blob/4870064629e76d9d387578c562a292cc680fa05f/train.py#L505

**Comment by tylertroy** [comment]
That makes sense, thanks @glenn-jocher !

**Comment by glenn-jocher** [comment]
@tylertroy you're welcome! If you have any more questions or need further assistance, feel free to ask. Good luck with your training!
