### ISSUE TITLE
WARNING: NMS time limit 1.060s exceeded

### ISSUE THREAD

**Issue by Vijay-P1999** [ultralytics/yolov5#7796]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When i validate my dataset and custom trained model, i get this warning

> **user@my-pc:~/umt-cv/umt-skeye$** python3 val.py --weights custom_weights/best.pt --data data/VisDrone.yaml 

![image](https://user-images.githubusercontent.com/96561146/168271397-0397c559-4b3e-4373-9314-18237454f234.png)

**WARNING: NMS time limit 1.060s exceeded**

Is this is a problem that i should be worried of? Also FYI, I'm going to deploy this model for real-time inference in live video stream  on aws.

**Comment by glenn-jocher** [comment]
@Vijay-P1999 NMS time limits are set here: 
https://github.com/ultralytics/yolov5/blob/8a4175cde0702285a9ba2fea4fb94aa8bd745754/utils/general.py#L759-L767
