### ISSUE TITLE
Train and the valid curve in one plot window

### ISSUE THREAD

**Issue by DP1701** [ultralytics/yolov5#7801]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello all,

Is there an option to show the train and the valid curve in one plot window in Tensorboard?
Or does a function have to be implemented for this?

Currently, these are displayed in two separate windows during and after the training.

**Comment by glenn-jocher** [comment]
@DP1701 there is no option for that. I'm not sure if TensorBoard allows multiple lines per plot, but you could try to customize the YOLOv5 TensorBoard logger here:
https://github.com/ultralytics/yolov5/blob/master/utils/loggers/__init__.py

https://github.com/ultralytics/yolov5/blob/9d8ed37df77e4e06a1b63cbf51785ec91557bf3d/utils/loggers/__init__.py#L133-L154

**Comment by DP1701** [comment]
I will take a look at this. If I have anything, I'll get back to you.

**Comment by glenn-jocher** [comment]
@DP1701 we do have a feature planned for Ultralytics HUB that will automatically overlay train/val losses when looking at a single model run. This should be released in a few weeks.
