### ISSUE TITLE
How to turn off the confidence display on the image box so that only categories are displayed on the image box

### ISSUE THREAD

**Issue by woderenpinzeihao** [ultralytics/yolov5#7805]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to turn off the confidence display on the image box so that only categories are displayed on the image box

**Comment by glenn-jocher** [comment]
@woderenpinzeihao `python detect.py --hide-conf`
