### ISSUE TITLE
Oriented Object Detection

### ISSUE THREAD

**Issue by Garvit-32** [ultralytics/yolov5#7806]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

References 
https://github.com/hukaixuan19970627/yolov5_obb

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Garvit-32 very cool, thanks for sharing!
