### ISSUE TITLE
PyTorch Slow GPU Inferencing with Yolov5 Model

### ISSUE THREAD

**Issue by BradyMeighan** [ultralytics/yolov5#7807]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

So basically I have this reasoning code below that loads a yolov5s PyTorch model, runs an inference on an image, and then saves the modified image.

``` 
from utils.general import check_img_size, non_max_suppression, scale_coords
from models.experimental import attempt_load
from utils.plots import plot_one_box
import numpy as np
import torch
import cv2

img_size = 416
model = attempt_load("yolov5n.pt")
stride = int(model.stride.max())
names = model.names

img_size = check_img_size(img_size, s=stride)


# ROI

X1 = 0
Y1 = 0
X2 = 1920
Y2 = 1080

ROI = {"X1":X1, "Y1":Y1, "X2":X2, "Y2":Y2}

def letterbox(img, new_shape=(640, 640), color=(114, 114, 114), auto=True, scaleFill=False, scaleup=True, stride=32):
	# Resize and pad image while meeting stride-multiple constraints
	shape = img.shape[:2]  # current shape [height, width]
	if isinstance(new_shape, int):
		new_shape = (new_shape, new_shape)

	# Scale ratio (new / old)
	r = min(new_shape[0] / shape[0], new_shape[1] / shape[1])
	if not scaleup:  # only scale down, do not scale up (for better test mAP)
		r = min(r, 1.0)

	# Compute padding
	ratio = r, r  # width, height ratios
	new_unpad = int(round(shape[1] * r)), int(round(shape[0] * r))
	dw, dh = new_shape[1] - new_unpad[0], new_shape[0] - new_unpad[1]  # wh padding
	if auto:  # minimum rectangle
		dw, dh = np.mod(dw, stride), np.mod(dh, stride)  # wh padding
	elif scaleFill:  # stretch
		dw, dh = 0.0, 0.0
		new_unpad = (new_shape[1], new_shape[0])
		ratio = new_shape[1] / shape[1], new_shape[0] / shape[0]  # width, height ratios

	dw /= 2  # divide padding into 2 sides
	dh /= 2

	if shape[::-1] != new_unpad:  # resize
		img = cv2.resize(img, new_unpad, interpolation=cv2.INTER_LINEAR)
	top, bottom = int(round(dh - 0.1)), int(round(dh + 0.1))
	left, right = int(round(dw - 0.1)), int(round(dw + 0.1))
	img = cv2.copyMakeBorder(img, top, bottom, left, right, cv2.BORDER_CONSTANT, value=color)  # add border
	return img, ratio, (dw, dh)

def predict(img_path):
	global model, stride, img_size, ROI

	conf_thres=0.25
	iou_thres=0.45
	classes=None
	agnostic_nms=True
	
	img = cv2.imread(img_path)
	img0 = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

	img_original = img0.copy()

	img0 = img_original[ROI["Y1"]:ROI["Y2"], ROI["X1"]:ROI["X2"], :]
	img = letterbox(img0, img_size, stride=stride)[0]

	img = img[:, :, ::-1].transpose(2, 0, 1)
	img = np.ascontiguousarray(img)

	img = torch.from_numpy(img)
	img = img/255.0

	if img.ndimension() == 3:
		img = img.unsqueeze(0)


	pred = model(img, augment=True)[0]

	pred = non_max_suppression(pred, conf_thres, iou_thres, classes=classes, agnostic=agnostic_nms)

	im0 = img0
	for i, det in enumerate(pred):  # detections per image
		gn = torch.tensor(im0.shape)[[1, 0, 1, 0]]  # normalization gain whwh
		if len(det):
			det[:, :4] = scale_coords(img.shape[2:], det[:, :4], im0.shape).round()
			x1, y1, x2, y2, conf = int(det[0,0]), int(det[0,1]), int(det[0,2]), int(det[0,3]), det[0,4]

			for *xyxy, conf, cls in reversed(det):
				label = f'{names[int(cls)]} : {conf:.2f}'
				plot_one_box(xyxy, im0, label=label, color=(255, 0, 0), line_thickness=3)

	cv2.imshow("Frame", img_original)
	cv2.imwrite("frame.jpg", img_original)
	k = cv2.waitKey(0) 

predict("images/data1_1248.jpg")
```

I'm trying to modify this code so that I can pass at least 60 fps through it and I should be able to do that with a yolov5s model on my GTX 1070. So I made the following adjustments to the code.
```
SEED = 42

def seed_everything(seed):
	random.seed(seed)
	os.environ["PYTHONHASHSEED"] = str(seed)
	np.random.seed(seed)
	torch.manual_seed(seed)
	torch.cuda.manual_seed(seed)
	torch.backends.cudnn.deterministic = True
	torch.backends.cudnn.benchmark = True
	torch.backends.cudnn.enabled = False

seed_everything(SEED)

cudnn.benchmark = True

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

#Moving the processing over to the GPU with these two lines had the biggest effect on performance. Went from 8 fps to 40 fps.
#From Line 76
img = torch.from_numpy(img).float().to(device)
#From Line 89
gn = torch.cuda.FloatTensor(im0.shape)[[1, 0, 1, 0]].to(device)

```
So here's the problem. I'm only getting around 46-49 fps with this code and task manager only shows around 60% GPU utilization and 14% CPU utilization so I believe there is a bottleneck somewhere. Furthermore, I tested the same code on an RTX 3090 which has 4x as many cuda cores and I still only get around 50 fps. If anyone could help it would be greatly appreciated!

### Additional

By the way, It's not the cv2.imwrite function because it performs the same without it.
Here is an image of my task manager: https://gyazo.com/8552eb80a369136238b19212524226c2

**Comment by glenn-jocher** [comment]
@BradyMeighan 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, etc.
# model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')  # custom trained model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by hlydecker** [comment]
That's reasonable speed with that hardware and predicting on one image at a time. You could speed things up if you batched images together.

Your main performance bottleneck is input and output speed to and from your GPU. If you batch your images together, prediction will be faster (see this [closed issue](https://github.com/ultralytics/yolov5/issues/1806)).

**Comment by glenn-jocher** [comment]
@hlydecker you're absolutely right! **Batching** can significantly enhance performance by decreasing data transfer overhead. Implementing batch inference is a powerful strategy to accelerate GPU utilization. Our team is continuously improving YOLOv5 and looks forward to hearing about your insights and experiences. Thank you for your valuable input!
