### ISSUE TITLE
slow speed when using torch.hub with tensorrt

### ISSUE THREAD

**Issue by kzyadaking** [ultralytics/yolov5#7819]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

i've sucessfully exported .pt to .engine and it runs fine when using detect.py 
    `detect.py --weights best1.engine --source bus.jpg`
image 1/1 C:\yolov5\bus.jpg: 640x640 Done. (0.002s)
Speed: 1.0ms pre-process, 2.0ms inference, 1.0ms NMS per image at shape (1, 3, 640, 640)

but when i run it on torch.hub , pre-process time is way slower 

    model = torch.hub.load('./', 'custom', path='best1.engine', source='local') 
    imgmap = 'bus.jpg
    if __name__ == "__main__":

    results = model(imgmap).print()

Speed: 15.0ms pre-process, 3.0ms inference, 1.0ms NMS per image at shape (1, 3, 640, 640)
image 1/1: 1080x810 (no detections)

why is it so and how can i make it fast? 
(windows10, rtx2060, cuda 11.3 cudnn 8.21, tensorrt 8.2)

**Comment by glenn-jocher** [comment]
@kzyadaking dataloader times are not present in detect.py profiling but are included in PyTorch hub profiling, i.e. hub results are showing you the true times.

**Comment by glenn-jocher** [comment]
If you want to speed up PyTorch Hub dataloading the obvious methods are to load your image outside of the model, i.e. using the cv2 loading example in the tutorial.

**Comment by kzyadaking** [comment]
@glenn-jocher once again thank you! can i ask you one more thing?  in the same code, when using torchhub, engine model is not able to find any detections while pt file is working fine. (detect.py works though) do you have any idea?

**Comment by glenn-jocher** [comment]
detect.py and PyTorch Hub return identical results under identical conditions for all formats including TRT. If you have a minimum reproducible example showing otherwise please submit a bug report with complete code to reproduce, thank you!

**Comment by kzyadaking** [comment]
@glenn-jocher im not sure wether this is a bug but ok. would appreciate it if you could take a look. #7822

**Comment by glenn-jocher** [comment]
@kzyadaking i will take a look at the issue you've submitted. Thank you for reporting it!
