### ISSUE TITLE
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

### ISSUE THREAD

**Issue by TitansWhale** [ultralytics/yolov5#7820]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,
    after train my model, I just wan to use hub to load model.but...

---

Adding AutoShape... 
Traceback (most recent call last):
  File "C:/Users/liux/Desktop/kinect/temp.py", line 10, in <module>
    result = model([img1])
  File "C:\Users\liux\anaconda3\envs\jumpwork_kinect\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\liux\anaconda3\envs\jumpwork_kinect\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\liux/.cache\torch\hub\ultralytics_yolov5_master\models\common.py", line 567, in forward
    y = self.model(x, augment, profile)  # forward
  File "C:\Users\liux\anaconda3\envs\jumpwork_kinect\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\liux/.cache\torch\hub\ultralytics_yolov5_master\models\common.py", line 416, in forward
    y = self.model(im)[0]
  File "C:\Users\liux\anaconda3\envs\jumpwork_kinect\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/models/yolo.py", line 33, in forward
    _22 = getattr(self.model, "2")
    _23 = getattr(self.model, "1")
    _24 = (getattr(self.model, "0")).forward(input, )
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    _25 = (_22).forward((_23).forward(_24, ), )
    _26 = (_20).forward((_21).forward(_25, ), )
  File "code/__torch__/models/common.py", line 10, in forward
  def forward(self: __torch__.models.common.Conv,
    input: Tensor) -> Tensor:
    _0 = (self.act).forward((self.conv).forward(input, ), )
                             ~~~~~~~~~~~~~~~~~~ <--- HERE
    return _0
class C3(Module):
  File "code/__torch__/torch/nn/modules/conv.py", line 11, in forward
    input: Tensor) -> Tensor:
    _0 = self.bias
    x = torch._convolution(input, self.weight, _0, [2, 2], [2, 2], [1, 1], False, [0, 0], 1, False, False, True, True)
        ~~~~~~~~~~~~~~~~~~ <--- HERE
    return x

Traceback of TorchScript, original code (most recent call last):
/home/liux/anaconda3/envs/yolo/lib/python3.9/site-packages/torch/nn/modules/conv.py(395): _conv_forward
/home/liux/anaconda3/envs/yolo/lib/python3.9/site-packages/torch/nn/modules/conv.py(399): forward
/home/liux/anaconda3/envs/yolo/lib/python3.9/site-packages/torch/nn/modules/module.py(860): _slow_forward
/home/liux/anaconda3/envs/yolo/lib/python3.9/site-packages/torch/nn/modules/module.py(887): _call_impl
/home/liux/Desktop/project/yolov5/models/common.py(50): forward_fuse
/home/liux/anaconda3/envs/yolo/lib/python3.9/site-packages/torch/nn/modules/module.py(860): _slow_forward
/home/liux/anaconda3/envs/yolo/lib/python3.9/site-packages/torch/nn/modules/module.py(887): _call_impl
/home/liux/Desktop/project/yolov5/models/yolo.py(152): _forward_once
/home/liux/Desktop/project/yolov5/models/yolo.py(129): forward
/home/liux/anaconda3/envs/yolo/lib/python3.9/site-packages/torch/nn/modules/module.py(860): _slow_forward
/home/liux/anaconda3/envs/yolo/lib/python3.9/site-packages/torch/nn/modules/module.py(887): _call_impl
/home/liux/anaconda3/envs/yolo/lib/python3.9/site-packages/torch/jit/_trace.py(934): trace_module
/home/liux/anaconda3/envs/yolo/lib/python3.9/site-packages/torch/jit/_trace.py(733): trace
/home/liux/Desktop/project/yolov5/export.py(99): export_torchscript
/home/liux/Desktop/project/yolov5/export.py(483): run
/home/liux/anaconda3/envs/yolo/lib/python3.9/site-packages/torch/autograd/grad_mode.py(27): decorate_context
/home/liux/Desktop/project/yolov5/export.py(555): main
/home/liux/Desktop/project/yolov5/export.py(560): <module>
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same


### Additional

my code 
--


import torch
import cv2

model_path = "model/yolo/yolo_Caibration.torchscript"

img = cv2.imread("temp_img.jpeg")
img1 = cv2.imread("temp_img.jpeg")

model = torch.hub.load('ultralytics/yolov5', 'custom', model_path)
result = model([img1])

**Comment by glenn-jocher** [comment]
@TitansWhale thanks for the bug report! I'm able to reproduce this using the following command. I will see what's going wrong.

```python
!python train.py --img 640 --batch 16 --epochs 3 --data coco128.yaml --weights yolov5s.pt --cache
!python export.py --weights runs/train/exp/weights/best.pt --include torchscript

import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'custom', 'runs/train/exp/weights/best.torchscript')

# Inference
results = model('https://ultralytics.com/images/zidane.jpg')
results.print()  # or .show(), .save()
```

**Comment by glenn-jocher** [comment]
@TitansWhale identified as user error. There is no bug. Default export device is CPU. You must export models on their intended destination devices:
```
python export.py --weights runs/train/exp/weights/best.pt --include torchscript --device 0
```

**Comment by TitansWhale** [comment]
> @TitansWhale identified as user error. There is no bug. Default export device is CPU. You must export models on their intended destination devices:
> 
> ```
> python export.py --weights runs/train/exp/weights/best.pt --include torchscript --device 0
> ```

thanks ,
