### ISSUE TITLE
inference with tensorrt on torch.hub doesnt work properly

### ISSUE THREAD

**Issue by kzyadaking** [ultralytics/yolov5#7822]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

PyTorch Hub

### Bug

    export.py --weights yolov5s.pt --include engine --device 0 --half --workspace 8 #
    detect.py --weight yolov5s.engine --source bus.jpg (bus.jpg from data/images)

    #result - detect.py 
    image 1/2 C:\yolov5\data\images\bus.jpg: 640x640 4 persons, 1 bus, Done. (0.002s)
    Speed: 0.5ms pre-process, 2.5ms inference, 3.5ms NMS per image at shape (1, 3, 640, 640)

so after converting .pt to .engine, you can inference with detect.py without any problem but when using torch.hub it seems that its not able to find any objects

    model = torch.hub.load('./', 'custom', path='yolov5s.engine', source='local')
    img = 'bus.jpg'

    results = model(img).print()

    #result - torch.hub 
    Speed: 13.0ms pre-process, 3.0ms inference, 1.0ms NMS per image at shape (1, 3, 640, 640)
    image 1/1: 1080x810 (no detections)

### Environment

 -yolo v5 6.1
 -windows 10
 -cuda 11.3, cudnn 8.2.1, TensorRT-8.2.5.1, pytorch 1.11.0

### Minimal Reproducible Example

    export.py --weights yolov5s.pt --include engine --device 0 --half --workspace 8 

    model = torch.hub.load('./', 'custom', path='yolov5s.engine', source='local')
    img = 'bus.jpg'

    results = model(img).print()

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@kzyadaking I'm not able to reproduce any issues using your commands in Colab:
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb?hl=en

<img width="1369" alt="Screenshot 2022-05-16 at 00 27 48" src="https://user-images.githubusercontent.com/26833433/168496561-a07f69b2-7ef8-4236-9b9f-d56be10c83e8.png">

**Comment by kzyadaking** [comment]
@glenn-jocher just figured it works when its converted as fp32 but doesnt work when its fp16.

**Comment by glenn-jocher** [comment]
@kzyadaking all YOLOv5 TensorRT exports are fixed at FP16.

**Comment by kzyadaking** [comment]
@glenn-jocher does that mean you dont really need --half when exporting? also if you export using trtexec (which is from official tensorrt bin) and put fp16 there. it wouldnt still work. (detect.py still works but only from toch.hub). same goes to export.py. if you put --half it wont work with torch.hub even though you dont really need --half since its fixed at fp16 like you said. so there must be a bug i guess

**Comment by glenn-jocher** [comment]
@kzyadaking TRT exports are fixed at FP16. TensorRT inference with detect.py and PyTorch Hub both work correctly. If you have evidence to the contrary please submit a bug report with exact code to reproduce the problem.

**Comment by mic2112** [comment]
@kzyadaking I can confirm that I am facing the same issue.

@glenn-jocher To replicate it please export the engine of yolov5x6.pt model with --half enabled using export.py, and then use the generated engine file for inference with torch.hub. You won't get any detections.
You can run the notebook below to replicate the issue. 
(https://colab.research.google.com/drive/1YP2qiDBI4qXgZ-Iypq_-F2TCOx7IWKdY?usp=sharing)

> @glenn-jocher does that mean you dont really need --half when exporting? also if you export using trtexec (which is from official tensorrt bin) and put fp16 there. it wouldnt still work. (detect.py still works but only from toch.hub). same goes to export.py. if you put --half it wont work with torch.hub even though you dont really need --half since its fixed at fp16 like you said. so there must be a bug i guess

**Comment by glenn-jocher** [comment]
@mic2112 thanks for letting us know about the problem. I am able to reproduce with this code. Added a TODO to investigate.

TODO: TRT --half export with PyTorch Hub inference bug

<img width="843" alt="Screenshot 2022-06-30 at 23 09 46" src="https://user-images.githubusercontent.com/26833433/176778798-0f6be99d-c593-4254-94b2-378560c6995d.png">

**Comment by glenn-jocher** [comment]
@mic2112 until this is resolved please export TRT models at FP32 precision (the default), which does work correctly with PyTorch Hub.

**Comment by glenn-jocher** [comment]
@mic2112 @kzyadaking good news 😃! Your original issue may now be fixed ✅ in PR #8435. This PR adds automatic casting to FP16 in the DetectMultiBackend class. I tested TRT FP16 models with PyTorch Hub and they work correctly in my test:

<img width="825" alt="Screen Shot 2022-07-01 at 3 40 35 PM" src="https://user-images.githubusercontent.com/26833433/176906139-8e16cca0-eeee-445f-bca7-d84c0801d85e.png">

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by mic2112** [comment]
@glenn-jocher Thank you so much, this was proving to be a showstopper for us. Thanks a bunch for fixing it so fast. You rock!

**Comment by glenn-jocher** [comment]
@mic2112 you're very welcome! 😊 We're delighted to be of assistance. However, the real accolades go to the YOLO community, as well as the diligent folks on the Ultralytics team who helped to resolve the issue. If you encounter any other challenges, please don't hesitate to reach out. We're always here to help!
