### ISSUE TITLE
Yolo with any number of channels

### ISSUE THREAD

**Issue by wouterio** [ultralytics/yolov5#7825]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Yolo now works with the three RGB color channels. Is it possible to make Yolo work with any number of channels?

### Use case

For example, adding a 4th channel for pixel depth would enable Yolo to work with stereo vision. My guess is that this depth channel may contain a ton of information valuable for object detection (and perhaps also segmentation), because sudden differences in depth may indicate separate objects.

Another use case would be adding channels for hyperspectral data.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by wouterio** [comment]
Had a better look at yolo.py and it seems that you can already choose the number of channels? Is that correct? If so, sorry for bothering... :)

**Comment by glenn-jocher** [comment]
@wouterio yes you can build YOLOv5 models with any number of input channels you want. 

The dataloaders are not adapted for arbitrary channel dataloading currently though, so these would have to be modified, as well as some augmentations disabled (i.e. HSV) and plotting functions modified that display augmentations etc.

**Comment by wouterio** [comment]
Hi Glenn,
Thanks for your response. How feasible is it to refactor the data loaders, augmentations, and plotting functions for any number of channels?

Let's take HSV augmentation as an example. I provide an ndarray image (width x height x channels) with channels Infrared, Red, Green, Blue, Ultraviolet, and Depth. And I provide a dict mapping the channels with the ndarray channel indices like {'IR':0, 'R':1, 'G':2, 'B':3, 'UV':4, 'D':5}. Then the HSV augmentation knows where to find the R, G, B channels in the ndarray. With such a mapping the HSV augmentation can be used on any number and order of channels, making it much more flexible.

My guess is that 3D will have quite an impact on object detection, because depth info makes it easier to distinguish objects from each other. Refactoring the yolo framework to allow any number of channels, would make working with 3D and other channels much easier. And that of course helps Ultralytics to stay ahead of the game.

**Comment by glenn-jocher** [comment]
@wouterio anything is possible with enough time and resources. 

HSV augmentation would be skipped entirely if channels!=3. There are domains that simply don't correspond to RGB, i.e. CMYK, hyperspectral, infrared or other datasets.

**Comment by wouterio** [comment]
Haha yes time and resources always seem to make a difference in programming. 😆 

Yes I understand HSV augmentation is not applicable to all domains. But if you have a set of channels containing at least R and G and B, then you can perform HSV augmentation on those 3 channels and leave the other channels as they were.

The HSV augmentation was just an example anyway. It's more that this mapping between channels and ndarray channel indices would make your framework super flexible.

With some smart design it's even possible to keep the framework's public interface backwards compatible:

DEFAULT_CHANNEL_MAPPING = {'R':0, 'G':1, 'B':2}

def some_fun(arr, ... other args ..., channel_mapping = None):
    channel_mapping = channel_mapping or DEFAULT_CHANNEL_MAPPING
    # do stuff

For RGB all functions remain the same, for other channels you need to specify the mapping. But yeah, it's all up to you whether you find this interesting or not.

**Comment by glenn-jocher** [comment]
@wouterio I appreciate your thoughtful insights. Our team will take your input into consideration as we continue to evolve and improve the YOLOv5 framework. We are committed to making our framework as versatile and user-friendly as possible. Thank you for taking the time to share your ideas with us.
