### ISSUE TITLE
Poor results training YOLOv5 on coco128 dataset using the random weight initialization

### ISSUE THREAD

**Issue by qingfengtommy** [ultralytics/yolov5#7829]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi sir.
I trained the coco128 using the coco128 weights and achieved good results.
However, when I started training YOLOv5 model using random weights initialization on the coco128, I got poor results.
Here are the training details:
![results](https://user-images.githubusercontent.com/52116238/168511877-60958812-9b00-4c37-aa71-506874900682.png)

### Additional

Thank you in advance!

**Comment by glenn-jocher** [comment]
@qingfengtommy everything is correct, this is expected behavior.
