### ISSUE TITLE
Can we combine YOLOv5 object detection model with anomaly detection?

### ISSUE THREAD

**Issue by mansi733** [ultralytics/yolov5#7830]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am working on a helmet detection model using yolov5, I need to detect only safety helmets as helmet class and other helmets(bike helmets, cricket helmets, no helmets) as no helmet class. So Is there any way to perform object detection on no helmet class without labeling the data? Can we perform anomaly detection on such kind of dataset?
![000920](https://user-images.githubusercontent.com/82514056/168518243-c0e1c080-be7a-4fe4-817b-31a95cbb6c80.jpg)

**Comment by glenn-jocher** [comment]
@mansi733 use case is very standard, simply requires a dataset of labelled safety helmets.
