### ISSUE TITLE
what is the meaning of P in P3, P4 and P5

### ISSUE THREAD

**Issue by yustaub** [ultralytics/yolov5#7833]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, sir. I wonder what the P means in  P3, P4 and P5 in yaml file, and I know the number is the power of 2 of the Downsampling

**Comment by glenn-jocher** [comment]
@yustaub nomenclature inherited from Google's EfficientDet paper

![image](https://user-images.githubusercontent.com/26833433/168556060-addc6709-5515-4735-98c8-21ef421a21d6.png)

**Comment by yustaub** [comment]
@glenn-jocher thanks for ur reply, appreciate!

**Comment by glenn-jocher** [comment]
@yustaub you're very welcome! I'm glad I could help. If you have any more questions, feel free to ask. Thank you!
