### ISSUE TITLE
How to train yolov5 with rectangular train?

### ISSUE THREAD

**Issue by lvxuanxuan123** [ultralytics/yolov5#7834]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I set the --rect while training. Do I need to set the --img-size to [640,384]?

**Comment by glenn-jocher** [comment]
@lvxuanxuan123 --rect is not recommended for training, but if you use it you only need to specify the long side size, i.e. `python train.py --rect 640`
