### ISSUE TITLE
Suggestions to prevent CPU bottlenecking training

### ISSUE THREAD

**Issue by tdhooghe** [ultralytics/yolov5#7838]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Dear Glenn and other contributors,

First of all, many thanks for this fantastic family of object detection architectures.

**Claim**
Unfortunately, when training on the default coco dataset, I suspect that my CPU is bottlenecking the training process a lot. Please see the task manager screenshots below that support this claim.

**Context**
I am running the following command on the cloned repository without any code adjustments. 
`python train.py --data coco.yaml --weights ' ' --cfg yolov5n.yaml --img-size 512 --batch-size -1
`
Running `python train.py --data coco.yaml --weights ' ' --cfg yolov5n.yaml --img-size 640--batch-size 128` leads to the same behavior.

My guess is that preprocessing the images is happening on the CPU, which is taking more time than doing the forward pass and backpropagation on the GPU. 

**Question**
_Do you have any suggestions to remove this CPU bottleneck, besides upgrading the rig itself?_ 

I am myself thinking about for example preprocessing all COCO images to (512, 512) format with the letterbox function, and storing those seperately on disk with their own dataset YAML, but I wonder if you think this would help anything at all?

![cpu_bottleneck](https://user-images.githubusercontent.com/61279337/168577852-56389635-4913-43a4-a104-1281acdb940f.png)

![gpu_performance](https://user-images.githubusercontent.com/61279337/168577870-00844915-861e-4698-be1f-7aa4226f3bc0.png)

**Comment by glenn-jocher** [comment]
@tdhooghe 👋 Hello! Thanks for asking about **training speed issues**. YOLOv5 🚀 can be trained on CPU (slowest), [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) (fastest). Caching with --cache should reduce CPU utilization.

If you would like to increase your training speed some other options are:

- Increase `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s
- Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) DDP at larger `--batch-size`
- Train on cached data: `python train.py --cache` (RAM caching) or `--cache disk` (disk caching)
- Train on faster GPUs, i.e.: P100 -> V100 -> A100
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

Good luck 🍀 and let us know if you have any other questions!
