### ISSUE TITLE
Caching images Stops Halfway in Training Images

### ISSUE THREAD

**Issue by joneswilliam1** [ultralytics/yolov5#7839]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Hi, when training YOLOv5 model on Google Colab using following command:
```
python train.py --img 640 --batch 8 --epochs 50 --data '/content/gdrive/MyDrive/YOLOv5/Vehicles/data.yaml' --weights yolov5s.pt --name yolov5s_100epochs_colab --cache --workers 1
```

During Caching of the training images, it automatically stops in 77% as shown in snippet below:

![image](https://user-images.githubusercontent.com/83490495/168582956-28641d26-30bf-43b5-8413-d97ebf8860d0.png)

It displays a '^C' in the snippet above, however Ctrl+C was not used and it had stopped on its own. 

### Environment

Google Colab

### Minimal Reproducible Example

Using Google Colab template provided by Roboflow.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@joneswilliam1 user error as you've run out of resources. If you don't have sufficient resources then don't --cache.
