### ISSUE TITLE
How to judge the effect of the model？How to know the accuracy and loss of the model?

### ISSUE THREAD

**Issue by dapsjj** [ultralytics/yolov5#784]
How to judge the effect of the model？How to know the accuracy and loss of the model?

**Comment by learncrazy** [comment]
There are training results in the file ./runs/expN.  It seems that running test.py is also OK.

**Comment by dapsjj** [comment]
> There are training results in the file ./runs/expN. It seems that running test.py is also OK.

I can see results.txt in  ./runs/expN.But I don't know the 15 columns  data in results.txt, what does each column mean?

**Comment by learncrazy** [comment]
@dapsjj  When you train, the parameters that appear on the console will be saved to result.txt. So you can compare with the parameters on the console during training.

**Comment by dapsjj** [comment]
> @dapsjj When you train, the parameters that appear on the console will be saved to result.txt. So you can compare with the parameters on the console during training.

I can see 8 columns in console,there are `Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size`,but there are 15 columns in results.txt.

**Comment by learncrazy** [comment]
@dapsjj You only read the first line, and there is also the second line.They are   class    image    targets    P    R     mAP@0.5  mAP.5:.95.

**Comment by glenn-jocher** [comment]
@dapsjj results.txt is plotted as results.png when training finishes. You can also use tensorboard to view your results live during training. See the notebook for examples:
- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>

**Comment by dapsjj** [comment]
> @dapsjj results.txt is plotted as results.png when training finishes. You can also use tensorboard to view your results live during training. See the notebook for examples:
> 
> * **Google Colab Notebook** with free GPU: [![Open In Colab](https://camo.githubusercontent.com/52feade06f2fecbf006889a904d221e6a730c194/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb)

Thanks!As you said,I use tensorboard to view  results live during training.

```
Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size  Class      Images      Targets      P         R          mAP@0.5      mAP.5:.95.
  5/19     1.26G   0.01996   0.02698   0.01887    0.0658      7       640    0.4194     0.7139      0.6098       0.3933    0.01284    0.01777      0.008861
```
