### ISSUE TITLE
There are 15 columns data in results.txt, what does each column mean?

### ISSUE THREAD

**Issue by dapsjj** [ultralytics/yolov5#785]
There are 15 columns of data in results.txt, what does each column mean?
The content of results.txt:
       0/2     1.22G   0.03148   0.03316   0.03681    0.1014         4       640    0.2596    0.4713    0.3695    0.2559   0.01213   0.01619   0.01569
       1/2     1.21G   0.02188   0.02779   0.02615   0.07583         1       640    0.3211     0.671    0.5224    0.3605   0.01141   0.01619   0.01204
      2/19     1.29G   0.02395   0.02961   0.02442   0.07798        10       640    0.4444    0.5254    0.4731    0.2763   0.01625   0.01936   0.01174
      3/19     1.26G   0.02261   0.02868   0.02314   0.07443         5       640    0.3715    0.7089    0.5907    0.3687   0.01411   0.01874    0.0102

**Comment by wudashuo** [comment]
https://github.com/ultralytics/yolov5/blob/fb4fc8cd0215443696a75dffbf56351266ccdfb0/train.py#L328
https://github.com/ultralytics/yolov5/blob/fb4fc8cd0215443696a75dffbf56351266ccdfb0/train.py#L127
you can simply read the code to find out the meaning

**Comment by dapsjj** [comment]
> https://github.com/ultralytics/yolov5/blob/fb4fc8cd0215443696a75dffbf56351266ccdfb0/train.py#L328
> 
> 
> https://github.com/ultralytics/yolov5/blob/fb4fc8cd0215443696a75dffbf56351266ccdfb0/train.py#L127
> 
> 
> you can simply read the code to find out the meaning

Thanks！

**Comment by scamianbas** [comment]
Hi, this is still not clear for me, could someone elaborate ?
Thanks!

**Comment by glenn-jocher** [comment]
Columns are the screen output along with 7 additional columns:
https://github.com/ultralytics/yolov5/blob/fb4fc8cd0215443696a75dffbf56351266ccdfb0/train.py#L327-L329
