### ISSUE TITLE
React-native TF.JS converted model (error with expo eas build)

### ISSUE THREAD

**Issue by tibor-mach** [ultralytics/yolov5#7853]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Export

### Bug

When trying to build an android APK using a TF.JS-converted model, react-native and expo eas (expo sdk 42) we are running into the following issues:

Training the model in PyTorch (using yolov5 6.0 ) work fine
building a testing react web app with the model works fine as well (using https://github.com/zldrobit/tfjs-yolov5-example.git )
Using eas, the model built as a development client also works
Using eas to built as an APK does not work. It can be built but the APK but in the APK, model loading is stuck at the loadGraphModel method (i.e. the model cannot be loaded when running on a mobile phone) with the following error:
`[RangeError: ArrayBuffer length minus the byteOffset is not a multiple of the element size]`

Any idea why this might be? (Looking up the error in this context does not lead to any relevant results). thanks a lot!

### Environment

Pytorch model built and converted using:
- YOLOv5 v.6.0
- OS: Ubuntu 20.04
- Python 3.9.

Other depedencies used for the react-native app build are listed in the minimal reproducible example repository below.

### Minimal Reproducible Example

Here is a link to a [repository](https://github.com/DataSentics/personal-shelf-inspector-min) where the issue can be reproduced (the [Readme](https://github.com/DataSentics/personal-shelf-inspector-min#readme) lists all the dependencies and steps needed to reproduce the error)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@tibor-mach hi there! Thanks for reaching out. It sounds like a challenging issue. The error you're encountering, `[RangeError: ArrayBuffer length minus the byteOffset is not a multiple of the element size]`, seems related to the model loading on mobile. While I'm not familiar with this specific issue, I think it may be related to the TensorFlow.js conversion or mobile environment. Unfortunately, I don't have an immediate solution, but I'd recommend checking the TensorFlow.js documentation, community forums, or rephrasing your search query to include TensorFlow.js, Expo, and the specific error for more targeted results.

If you have any other questions or need further assistance, feel free to ask! Thank you for your understanding and patience.
