### ISSUE TITLE
How to apply it to the new data format.

### ISSUE THREAD

**Issue by shubudao** [ultralytics/yolov5#7859]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

yolov5 is an amazing work, but I want to apply it to grasp detection. Here are my images and labels (x, y, w, h, sin(θ)), where should I start modifying.
![pcd0175r](https://user-images.githubusercontent.com/50509401/168827462-356c6cf8-4f41-41a1-b803-cd64c4487fab.png)

![my_label](https://user-images.githubusercontent.com/50509401/168828303-9ff7d1f0-615c-42e7-876a-8e410cc42bbc.png)

**Comment by glenn-jocher** [comment]
@shubudao this might work: https://github.com/hukaixuan19970627/yolov5_obb

**Comment by shubudao** [comment]
The label is(cls, x, y, w, h, sin(θ)), while i don't need to detect it's class, so i set all of them be 0.

**Comment by shubudao** [comment]
@glenn-jocher  Thank you very much! I will learn about that.

**Comment by glenn-jocher** [comment]
@shubudao you're very welcome! Happy to help. If you have any more questions while working with YOLOv5, feel free to ask. Good luck with your project!
