### ISSUE TITLE
Can yolov5 be migrated to the embedded device STM32 ?

### ISSUE THREAD

**Issue by learncrazy** [ultralytics/yolov5#786]
## ❔Question
Hello !!! I have a question. Can yolov5 be migrated to the embedded device STM32 ? 
At present, our control programs are all developed on stm32, so I want to port yolov5 to stm32 to add system vision functions. 
If you can, how can you do it? Thanks.

**Comment by glenn-jocher** [comment]
@learncrazy that's a good question, I don't know! I don't have experience with this particular hardware. The most common export routes are first to torchscript or ONNX, and then from those two onward to other formats like coreml, protobuf, tflite, tensorrt etc. 

Unfortunately export of the latest release does not work correctly, but export of v2.0 release models with torch 1.5.1 is working correctly. You can use the export tutorial to get started. See https://docs.ultralytics.com/yolov5
