### ISSUE TITLE
Yolov5 c++ openvino implementation

### ISSUE THREAD

**Issue by dwight-foster** [ultralytics/yolov5#7861]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello I was wondering if anyone knows of a c++ openvino implementation. I know of [this](https://github.com/fb029ed/yolov5_cpp_openvino) one but it uses version 3.1 of this repo and I need some features of the later versions and cannot get it to work with the later ones. I am not great at c++ so I cannot build my own. Any help would be greatly appreciated.

**Comment by glenn-jocher** [comment]
@dwight-foster we have a few ONNX (not OpenVINO) examples here. If you find any good OpenVINO repos please let us know and we will add them as references the Export [tutorial](https://docs.ultralytics.com/yolov5/tutorials/model_export):

## OpenCV DNN C++

Examples of YOLOv5 OpenCV DNN C++ inference on exported ONNX models can be found at
- https://github.com/Hexmagic/ONNX-yolov5/blob/master/src/test.cpp
- https://github.com/doleron/yolov5-opencv-cpp-python
