### ISSUE TITLE
DW model in Assets

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#7863]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

@glenn-jocher 
I would like to ask, what model does `best-dw.pt` and `best-c3x-dw.pt` represent?

**Comment by glenn-jocher** [comment]
@Zengyf-CVer these are YOLOv5 models with depthwise layers that we are experimenting with for v7.0 release next month. Sometimes we place models in the release assets to make it easy to access them anywhere for further testing, i.e. if you run `python detect.py --weights best-dw.pt` these will autodownload for you.

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
Thank you very much.

**Comment by glenn-jocher** [comment]
@Zengyf-CVer you're welcome! 😊 If you have any other questions or need further assistance, feel free to ask. I'm here to help!
