### ISSUE TITLE
conf_thres increased and then  recall increases, data problem or others ?

### ISSUE THREAD

**Issue by carptainhao** [ultralytics/yolov5#7864]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, when I use val.py to test badcase data, I increase conf_thres and recall increases. I have not encountered such a problem on the original divided test set. Is this a data problem?

**Comment by glenn-jocher** [comment]
@carptainhao val.py is invalid for any confidence threshold higher than the default. This is displayed to users here:
https://github.com/ultralytics/yolov5/blob/9a7f289eedb489fa598dc7d3e1756c5b82b77e99/val.py#L364-L365

**Comment by carptainhao** [comment]
> But if i increase the confidence threshold, the result of recall is also invalid?



> @carptainhao val.py is invalid for any confidence threshold higher than the default. This is displayed to users here:
> 
> https://github.com/ultralytics/yolov5/blob/9a7f289eedb489fa598dc7d3e1756c5b82b77e99/val.py#L364-L365

**Comment by glenn-jocher** [comment]
@carptainhao I don't know. In any case P and R are computed for all confidences and plotted as curves by val.py, i.e.:
![image](https://user-images.githubusercontent.com/26833433/169075725-3f52aa0c-a4a9-4e55-bb0a-01e1ec344b15.png)
![image](https://user-images.githubusercontent.com/26833433/169075749-9a8af9c4-5abe-4f2d-abf5-2992838d25df.png)
