### ISSUE TITLE
combine yolov5 model with another model

### ISSUE THREAD

**Issue by alexandercesarr** [ultralytics/yolov5#7865]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I trained a yolov5 model on a dataset that consists pics from drones and now I want to use it in dronet learning to fly (https://github.com/uzh-rpg/rpg_public_dronet) --> in cnn.py.
How can I combine these two? I mean I wanna combine dronet model and yolo model.
and now I don't know how can I add it to dronet.
Can anyone help me?

**Comment by glenn-jocher** [comment]
@alexandercesarr see https://community.ultralytics.com/t/how-to-combine-weights-to-detect-from-multiple-datasets

**Comment by alexandercesarr** [comment]
Thank you @glenn-jocher. But I wanna use the yolo model that I got in dronet. I put the link in my previous comment. In that repository a file named cnn.py exists. I don't know how can I use the yolo model in that code and train a new model. I wanna know that is it possible or not?

**Comment by glenn-jocher** [comment]
@alexandercesarr 3rd party works are outside the scope of our support, I would recommend asking your question directly to the authors of those works.
