### ISSUE TITLE
Mean Average Precision [.5:.095]

### ISSUE THREAD

**Issue by kXborg** [ultralytics/yolov5#7866]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

The test results provided in the ReadMe says mAP[0.5:0.95] is it different from mAP[0.5:.05:0.95]?

**Comment by glenn-jocher** [comment]
@kXborg they're the same
