### ISSUE TITLE
Adding Tests for CI / CD

### ISSUE THREAD

**Issue by JWLee89** [ultralytics/yolov5#7868]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

From checking the past issues, it seemed like this was already proposed, but has been closed: 
https://github.com/ultralytics/yolov5/issues/407

### Description

I was wondering if there will be any plans in the future to develop tests for CI / CD. 
Although this will likely take a long time, I think it will also save as much time if not more in the future if implemented effectively. 

Are there any plans in the future to write tests and add github workflows so that the testing phase is well-automated?

### Use case

Run pytest on CI / CD phase using github workflows to receive timely error reports when features are broken or not working as expected.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
See https://github.com/ultralytics/yolov5/actions/workflows/ci-testing.yml
