### ISSUE TITLE
How to get the specific number of labels in the training set in labels.jpg?

### ISSUE THREAD

**Issue by hjw-0909** [ultralytics/yolov5#7869]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I only know the approximate amount but not the exact amount，so how to get the specific number of labels in the training set in labels.jpg?

![image](https://user-images.githubusercontent.com/56182057/168975767-9c6f1175-8692-4a2e-a12a-06c490af52c5.png)

**Comment by glenn-jocher** [comment]
@hjw-0909 `python val.py --task train` will produce per class stats and metrics on train set.

**Comment by hjw-0909** [comment]
@glenn-jocher  thank you very much.

**Comment by glenn-jocher** [comment]
@hjw-0909 you're welcome! Feel free to reach out if you have any other questions. Good luck with your training! 😊
