### ISSUE TITLE
What is evolve param?

### ISSUE THREAD

**Issue by chokyungjin** [ultralytics/yolov5#787]
I'm sooooo happy to use your YOLOv5. 
I'm training my custom data using YOLOv5 And I applied evolve parameter, 
but it is not over for seven hours. 
When I turned this param off, it was over in three hours. 
And Model is not saving pt.

What is evolve param? Thanks again!!!!

**Comment by glenn-jocher** [comment]
@chokyungjin evolving hyperparameters is seperate from training, and takes much longer (can take weeks or months on a single GPU). See evolution tutorial: https://docs.ultralytics.com/yolov5

**Comment by chokyungjin** [comment]
@glenn-jocher  Thanks again. 
But I have a another issue. My Train curve is weird in results.jpg. 
I don't know why I'm getting the results like this, except I changed my custom data.

my opt is batch 80 img 416 epochs 300 weights '' augmentation default.

![image](https://user-images.githubusercontent.com/46750574/90947969-0ab28680-e475-11ea-8319-d4c1cf52fd3d.png)

**Comment by glenn-jocher** [comment]
@chokyungjin your val data may not have been found correctly. Make sure your paths appear, and make sure your test_batch0_gt.jpg appears correct.

**Comment by chokyungjin** [comment]
@glenn-jocher My test_batch0_gt.jpg appears correct. 
So what am I supposed to do now? 
I only revise  augmentation meta code and iOU threshold value.

Thanks.

**Comment by maloyan** [comment]
@chokyungjin Did you manage to resolve that problem?

**Comment by glenn-jocher** [comment]
@maloyan see YOLOv5 **Hyperparameter Evolution** tutorial:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TFLite, ONNX, CoreML, TensorRT Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

Good luck 🍀 and let us know if you have any other questions!

**Comment by MLDavies** [comment]
Is it possible to evolve on a subset of hyperparameters? If so, how would this been done?

**Comment by glenn-jocher** [comment]
@MLDavies update `meta` dict here by setting mutation scale to zero for any hyperparams you want to fix in place:

https://github.com/ultralytics/yolov5/blob/014acde79daee83e1f1801412cc7a48293e6e1f2/train.py#L569-L600

**Comment by MLDavies** [comment]
Ah. Perfect. Thank you.
