### ISSUE TITLE
iou-thres doesn't work correctly??

### ISSUE THREAD

**Issue by GianNuzzarello** [ultralytics/yolov5#7872]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Validation, Detection, Export, Evolution

### Bug

I want to consider an object correctly classified even if IoU is very very low (ideally even 0.0001 o lower).
I run:
`!python val.py --task test --conf 0.9 --img 1280 --data "../data_manual annotations.yaml" --weights 'runs/train/yolov5s_results/weights/best.pt' --iou-thres 0.00000000000000001`
but I get the same result when I set IoU-thres to 0.6

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by MartinPedersenpp** [comment]
Have you tried running detect.py with lower iou_thresh?

**Comment by GianNuzzarello** [comment]
> Have you tried running detect.py with lower iou_thresh?

Is there a way to get Precision/Recall for detect.py? I need performance in terms of P/R and this is the reason why I run val.py instead of detect.py

**Comment by MartinPedersenpp** [comment]
detect.py only gives you the output, but if you need the metrics for the model I guess val is the way to go, but you can verify that the model detects correctly even with low iou_thresh and then that would mean that the iou_thresh does not have an impact on your validation results.
That is as far as I can go with what I know.

I guess you will have to wait for an official to get back to you, sorry I could not be of more help.

**Comment by GianNuzzarello** [comment]
Can anyone help me?

**Comment by nidetaoge** [comment]
I have also met the same problem, here the NMS cannot correctly delete the objects with the iou_thresh.

**Comment by glenn-jocher** [comment]
@GianNuzzarello hello! 🌟 Sure, I can help! To clarify, for measuring Precision/Recall, you should indeed use val.py for validation. If you've already tested lower `iou-thres` values and it's not impacting your validation results, then there might be something else affecting the detection process. 

You can verify the model's detection performance using detect.py with a lower `iou-thres` and compare the results with val.py. Also, be sure to check if your dataset and annotations are in order. If everything looks correct, then I'd recommend waiting for an official response for further assistance.

Let me know if there's anything else I can do to assist you further!
