### ISSUE TITLE
the orders of .txt in labels

### ISSUE THREAD

**Issue by Wfast** [ultralytics/yolov5#7873]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Whether the order of the txt files in the labels folder should be the same as the order of the jpg files in the images folder. 
like [A.txt, B.txt, C.txt] and [A.jpg, B.jpg, C.jpg].
Or as long as their names can be matched one by one, like [A.txt, B,txt, C.txt] and [B.jpg, C.jpg, A.jpg]
thanks a lot!

**Comment by glenn-jocher** [comment]
@Wfast order is simply a concept for human consumption. Files are not ordered on a storage medium.
