### ISSUE TITLE
how does image size work in this case?

### ISSUE THREAD

**Issue by kzyadaking** [ultralytics/yolov5#7874]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

im trying to find a object that is 40x40 (fixed size). im training on 640x640 with the objects in it and my question is
since it will always be 40x40, can i just crop the rest of the part (mostly just background) and make it like 320x320 or even smaller and train on 320x320? will this have the same model quality as 640?

**Comment by MartinPedersenpp** [comment]
As far as i understand, the model does not only train on what it is told to look at, your annotations, it also looks at everything else.
So the more background you have, the easier the model will learn what is not your object class and will easier be able to distinguish between the classes.
So if you crop your 640x640 images you might see a longer training period before you reach the same results as with 640x640.

**Comment by glenn-jocher** [comment]
@MartinPedersenpp exactly! The background in the training data helps the model distinguish between classes. Training on smaller cropped images may require longer training to achieve the quality of a 640x640 model. The Ultra-blog has an article on this exact topic at https://docs.ultralytics.com/yolov5/. Check it out!
