### ISSUE TITLE
can you provide the official mAP on the pascal voc dataset?

### ISSUE THREAD

**Issue by GaoQidi** [ultralytics/yolov5#7876]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

there are mAPs on COCO dataset, but I didn't find the official mAPs on Pascal Voc dataset, where can I find the mAPs?
 thank you

**Comment by glenn-jocher** [comment]
@GaoQidi most recent VOC trainings are here:
https://wandb.ai/glenn-jocher/YOLOv5_VOC_official

Highest mAP@0.5 is 0.92 for YOLOv5x6
