### ISSUE TITLE
Training a model to process images with crowded objects 

### ISSUE THREAD

**Issue by CallMeDek** [ultralytics/yolov5#7882]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,

I am trying to train a model with my custom data. 
The problem is objects in a image are crowded and even occluded.
Data is like below.
![image](https://user-images.githubusercontent.com/22671339/169181688-8968eb45-cfa4-49e2-939c-5dc4689ec82f.png)

I want to make my model detect almost all of them.
So,
(1) How to change maximum object count threshold in the NMS function? I can't find the related code.
I read [yolov5/issues/1779](https://github.com/ultralytics/yolov5/issues/1779)
(2) Can I change the number of boxes in a grid cell?
(3) Any tips for it?

Thanks

**Comment by glenn-jocher** [comment]
@CallMeDek val.py uses default max detections of 300, detect.py uses default 1000 objects per image.
https://github.com/ultralytics/yolov5/blob/fe1b503cbb089a8c4740847aeac97b66cc1ccf4f/detect.py#L219

My recommendation is to train normally, your example shows a default YOLOv5 use case. See Tips for Best Training Results below.

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️  RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Roboflow for Datasets, Labeling, and Active Learning](https://docs.ultralytics.com/yolov5/tutorials/roboflow_datasets_integration)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TFLite, ONNX, CoreML, TensorRT Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [Architecture Summary](https://docs.ultralytics.com/yolov5/tutorials/architecture_description)&nbsp; ⭐ NEW

Good luck 🍀 and let us know if you have any other questions!

**Comment by CallMeDek** [comment]
Thank you for your help.

**Comment by glenn-jocher** [comment]
@CallMeDek you're welcome! If you have any more questions or need further assistance, feel free to ask. Good luck with your model training! 🚀
