### ISSUE TITLE
how to change the number of images while training?

### ISSUE THREAD

**Issue by shashankrajput-iitk** [ultralytics/yolov5#7884]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hey yolov5 was not able to change the number of images I have to feed to the model. How can I change the number of images in the model? Can you suggest me the filename?

![Screenshot (14)](https://user-images.githubusercontent.com/72705901/169224276-df86c8b2-8659-4f45-a563-740d0006022f.png)

**Comment by glenn-jocher** [comment]
@Shanky71 YOLOv5 uses all images in your val set for validation. You have 5 images in your val set. You can add new images (with labels.txt files if the images have objects) to your dataset anytime and retrain.

**Comment by shashankrajput-iitk** [comment]
@glenn-jocher Thanks. Then what about the set of training images I have feed to the network? Where will I get to see the number of training images yolov5 is using .
What split between the train/val should I use for better detection?

**Comment by glenn-jocher** [comment]
@Shanky71 YOLOv5 uses all images in your train set for training. The default split between train/val is 0.8, meaning 80% of your dataset is used for training and 20% for validation. You can modify the split ratio in your data.yaml file. Typically, larger train sets are better for detection performance.
