### ISSUE TITLE
Support for Mac M1 GPU

### ISSUE THREAD

**Issue by Zumbalamambo** [ultralytics/yolov5#7885]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Add support for [Mac](https://pytorch.org/blog/introducing-accelerated-pytorch-training-on-mac/) m1 GPU training

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by zhiqwang** [comment]
Seems that we should wait torchvision land the M1 GPU support first https://github.com/pytorch/vision/issues/6050

**Comment by glenn-jocher** [comment]
@Zumbalamambo M1 training is already possible on arm64 python>=3.9.1 distributions, but MPS support (which should speed this up significantly) is still being debugged in https://github.com/ultralytics/yolov5/pull/7878

**Comment by DP1701** [comment]
@glenn-jocher How did you output the [environment information](https://github.com/pytorch/pytorch/issues/77748#issue-1240166271)? Did you write a script for this or do you use a special command in the terminal?

**Comment by GerardWalsh** [comment]
@DP1701 https://github.com/pytorch/pytorch/blob/master/torch/utils/collect_env.py
