### ISSUE TITLE
Creating confidence, precision and recall csv files on utils/metrics.py

### ISSUE THREAD

**Issue by carlok** [ultralytics/yolov5#7888]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

I wrote a very small patch which creates confidence, precision and recall csv files on `utils/metrics.py`.
I needed it so that's it.
I also added a "grid" on the ROC diagram.
I'm going to submit a Pull Request

### Use case

I use this patch within `val.py`

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by carlok** [comment]
The Pull Request is [7889](https://github.com/ultralytics/yolov5/pull/7889)

**Comment by glenn-jocher** [comment]
@carlok thanks for your willingness to contribute! We greatly appreciate your initiative and look forward to reviewing your PR. If you need any guidance during the process, feel free to reach out, and thank you for your support!
