### ISSUE TITLE
IOU threshold for Non-max suppression

### ISSUE THREAD

**Issue by AJ-RR** [ultralytics/yolov5#789]
## ❔Question
Hi,
The default IOU threshold for NMS is 0.65 in the test.py file. However, why does it show map@0.5IOU in the results? Shouldn't it be the IOU threshold that is set?

**Comment by glenn-jocher** [comment]
No. These are completely separate. NMS IoU is used to reject or merge predictions. mAP thresholds compare predictions to labels.

**Comment by AJ-RR** [comment]
Thank you!

**Comment by ControllableGeneration** [comment]
mAP also uses IoU threshold. mAP@0.5 is when True Positiveness is those with IoU bigger than 0.5
