### ISSUE TITLE
25/5000  How to view the best precision and highest MAP after training my dataset?

### ISSUE THREAD

**Issue by MaYaNan97** [ultralytics/yolov5#7890]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

The training result file only contains images without specific data.（results.txt）

**Comment by glenn-jocher** [comment]
@MaYaNan97 validation runs every epoch and after training completes to display all metrics to you. You can also run it manually, i.e.
```
python val.py --data DATA.yaml --weights path/to/best.pt
```

**Comment by MaYaNan97** [comment]
> @MaYaNan97在每个运行完成后，并在训练后向您显示所有指标。也可以在此期间手动运行验证，即
> 
> ```
> python val.py --data DATA.yaml --weights path/to/best.pt
> ```
Thank you, I will try the program.
