### ISSUE TITLE
C++ inference pipeline for TensorRT

### ISSUE THREAD

**Issue by pk-cb** [ultralytics/yolov5#7892]
Hi, Is there a inference pipeline written in C++ as well similar to `detect.py` in python3. 
I am running the model on a jetson nano, and wanted to use C++ tensorrt api for inference and pre/post processing.

Thanks

**Comment by JWLee89** [comment]
If you want an inference pipeline written in C++, I recommend checking out Nvidia's DeepStream: https://developer.nvidia.com/deepstream-sdk
Nvidia DeepStream is designed to run on edge devices such as Jetson Nano or Xavier. It can also run on a standard dGPU server.

The inference pipeline is based off Gstreamer ( https://gstreamer.freedesktop.org/ ) and once you serialize your model into TensorRT format, you can run the object detection model on the pipeline, provided that you write the bounding box parsing algorithm. 

Some open-source work that you can take a look at for bounding box parsing is DeepStream-yolo: https://github.com/marcoslucianops/DeepStream-Yolo

For DeepStream Application references in C++, take a look at: 
https://github.com/NVIDIA-AI-IOT/deepstream_reference_apps 

If you are more used to Python, DeepStream also supports python bindings. Examples can be found here: 
https://github.com/NVIDIA-AI-IOT/deepstream_python_apps

**Comment by JWLee89** [comment]
If you just want the model outputs, but want to do the inference via the TensorRT API, you can simply use `torch2trt` (link: https://github.com/NVIDIA-AI-IOT/torch2trt) which will run the model on TensorRT. That will allow you to do your own pre / post-processing

**Comment by zhiqwang** [comment]
FYI @pk-cb and @JWLee89 , cc @glenn-jocher ,

Just for the post-processing, you can use the `EfficientNMS_TRT` plugin provided by TensorRT, see #6430 for more details. And you can rewrite the OpenCV Python interface to C++ like [here](https://github.com/zhiqwang/yolov5-rt-stack/blob/006f3f69f635e03f8e47e10b4a575439a1c0ebec/deployment/tensorrt/main.cpp#L80-L123) for the pre-processing. (It would be better if we could do the pre-processing on [deepstream-sdk](https://developer.nvidia.com/deepstream-sdk).)

And there is a PR for registering the `EfficientNMS_TRT` plugin to YOLOv5 at #7736 , I guess you can do C++ inference on TensorRT with totally following example https://github.com/zhiqwang/yolov5-rt-stack/tree/main/deployment/tensorrt after #7736 is merged.

**Comment by glenn-jocher** [comment]
@zhiqwang thanks for the suggestion! We've recently added torch2trt, a handy tool for seamless inference via the TensorRT API, perfect for custom pre/post-processing work. Stay tuned for EfficientNMS_TRT plugin integration with yolo5 for streamlined inference. For further assistance, feel free to check the Ultralytics Docs (https://docs.ultralytics.com/yolov5/) or reach out here!
