### ISSUE TITLE
I can't train the same map on yolov5_v6.1 

### ISSUE THREAD

**Issue by jedi007** [ultralytics/yolov5#7893]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I trained several times on voc dataset.
But my map is always a little lower than master.

And I found some strange phenomena.
![1](https://user-images.githubusercontent.com/32835610/169431546-054a7930-e030-4f72-b13e-d961d926f9ff.png)
![2](https://user-images.githubusercontent.com/32835610/169431555-8318847d-06ae-40b1-911a-7aa3bdb0f5ad.png)

My map growth is significantly slower in the first five epochs.
Master map_0.5 is 0.1799 at epoch 1 , 0.3573 at epoch 2. ( values from [https://wandb.ai/glenn-jocher/YOLOv5_VOC_official/runs/3m8isrzq](url) )
Master map grew much faster in the first five epochs.

I cloned the code without making any changes.
The details of my training are here: [https://wandb.ai/jedi007/YOLOv5_v61_VOC_master](url)

Why is there such a big difference?

**Comment by jedi007** [comment]
Master map_0.5 is  [0.04954 at epoch 0,  0.1799 at epoch 1, 0.3573 at epoch 2].
The growth rate is simply too fast.

**Comment by glenn-jocher** [comment]
@jedi007 obviously if you want to reproduce the results in the experiments shown checkout the exact commit rather than use master

**Comment by jedi007** [comment]
![图片](https://user-images.githubusercontent.com/32835610/169731153-dd15bcb8-155e-4114-907a-dc642eb37091.png)

I checkout the same version(d51f9b2ff6e60b7eaaafc7e8d991f0d6dbb786cd) as you,and got the same map.

Thank you very much for your guidance.

**Comment by glenn-jocher** [comment]
@jedi007 great to hear you were able to replicate the results! If you have any further questions or need assistance with anything else, feel free to ask. Happy to help!
