### ISSUE TITLE
Why did the last epoch map grow so much?

### ISSUE THREAD

**Issue by jedi007** [ultralytics/yolov5#7894]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

![3](https://user-images.githubusercontent.com/32835610/169434451-98198771-a58d-458e-8d0f-c7cbcd66e02a.png)
I found the results on [https://wandb.ai/glenn-jocher/YOLOv5_v61_official](url)
Why did the last epoch map grow so much?

**Comment by glenn-jocher** [comment]
pycocotools is used to evaluate final mAP, results in slightly higher results than YOLOv5 mAP code.

**Comment by jedi007** [comment]
HOHO~Thank you very much for your guidance.

**Comment by glenn-jocher** [comment]
@jedi007 BTW this should be largely resolved after a recent PR. Now the pycocotools difference is much smaller.

**Comment by jedi007** [comment]
OK, I will continue to pay attention to the update of yolov5.
At the same time, I will do some tests on mosaic augmentation.

**Comment by cissoidx** [comment]
> @jedi007 BTW this should be largely resolved after a recent PR. Now the pycocotools difference is much smaller.

@glenn-jocher Hi, can you please point me to the specific PR?  I need to cherry-pick it to my own version.

**Comment by glenn-jocher** [comment]
@cissoidx search PR's for val/mAP changes
