### ISSUE TITLE
Internal error in function fgOpenWindow

### ISSUE THREAD

**Issue by Yousef-Alhattab** [ultralytics/yolov5#7895]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

![Screenshot from 2022-05-20 10-47-24](https://user-images.githubusercontent.com/56126016/169439172-57bf8837-694f-45b4-8db1-d52c82e11167.png)

could you help please? 

![Screenshot from 2022-05-20 11-12-39](https://user-images.githubusercontent.com/56126016/169443103-644765e1-386d-4b7d-ba8a-55e131534caf.png)

### Additional

I believe it is torch problem!

**Comment by glenn-jocher** [comment]
@urbansound8K it appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual [Python 3.9](https://www.python.org/) environment, clone the latest repo ([code changes daily](https://github.com/ultralytics/yolov5/commits/master)), and `pip install` [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) again from scratch.

💡 ProTip! Try one of our verified environments below if you are having trouble with your local environment.


## Requirements

[**Python>=3.7.0**](https://www.python.org/) with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) installed including [**PyTorch>=1.7**](https://pytorch.org/get-started/locally/). To get started:
```bash
git clone https://github.com/ultralytics/yolov5  # clone
cd yolov5
pip install -r requirements.txt  # install
```

[Models](https://github.com/ultralytics/yolov5/tree/master/models) and [datasets](https://github.com/ultralytics/yolov5/tree/master/data) download automatically from the latest YOLOv5 [release](https://github.com/ultralytics/yolov5/releases) when first requested.

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), validation ([val.py](https://github.com/ultralytics/yolov5/blob/master/val.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/export.py)) on MacOS, Windows, and Ubuntu every 24 hours and on every commit.

**Comment by Yousef-Alhattab** [comment]
thanks a lot

I am wondering now if I can print out the output of the objects detection in terminal?   what I mean is that how to print the height width distance and etc in the terminal? where is that in the code?

**Comment by glenn-jocher** [comment]
@urbansound8K 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, etc.
# model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')  # custom trained model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by Yousef-Alhattab** [comment]
thank you again 
you are really doing well!

honestly, what I am asking is about the detector of zed 2i cam? [here](https://github.com/stereolabs/zed-examples/blob/master/object%20detection/custom%20detector/python/pytorch_yolov5/detector.py) 

I cloud not find where in  the code the sting of output is?

could you please have a look and give me a hint? 

let me before that show you what I have done 

here I cound find the number of objects 

![Screenshot from 2022-05-24 11-24-45](https://user-images.githubusercontent.com/56126016/169947293-b1d9e37e-4144-4ce7-967b-49d6c248e188.png)


I added these lines here for that
![Screenshot from 2022-05-24 11-25-49](https://user-images.githubusercontent.com/56126016/169947579-d7759d9c-8ec0-4a89-8329-2fa97c23a1c8.png)





now I am looking how to make the same for distance and classID, please?

**Comment by Yousef-Alhattab** [comment]
I could get all the information I want printed out in the terminal, expect the distance?
where in code [here](https://github.com/stereolabs/zed-examples/blob/master/object%20detection/custom%20detector/python/pytorch_yolov5/detector.py) is the distance ? 


could you please how ur detector works with zed 2i? where did u measure the distance ?
to sum up? I just want to print the distacne out on the terminal ?

what I am planing to do is that; i want to send the final output string format via UDP

please help

**Comment by glenn-jocher** [comment]
@urbansound8K Thanks for sharing your progress and what you're aiming to achieve. The distance calculation is typically performed using the stereo vision capabilities of the ZED 2i camera, which allows for depth estimation. In the provided detector.py file, the distance calculation based on the output of the YOLOv5 model will likely be located in the sections responsible for post-processing the model's predictions.

However, as the file you've referenced is not part of the YOLOv5 repository, it's difficult for me to pinpoint the exact location for the distance calculation. I recommend reviewing the ZED 2i documentation or leveraging the ZED SDK to integrate depth estimation with object detection. Once you have the distance information, you can incorporate it into the output string and proceed with sending the formatted output via UDP as planned.

Feel free to reach out if you have any more questions or need further assistance!
