### ISSUE TITLE
How to skip one video from a dataset?

### ISSUE THREAD

**Issue by szcarr** [ultralytics/yolov5#7898]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Let's say i would run detect.py on a directory with lots of videos in it:

> detect.py --weights "some/model.pt" --source "some/dir/with/lots/of/videofiles"

How would i skip one video in dataset, instead of skipping indvidual frames in a video?

### Additional

I have tried skipping individual frames in a video. But since it loads the images as well, it takes a long time to skip.

![Screenshot from 2022-05-20 10-07-00](https://user-images.githubusercontent.com/67342876/169483642-23760fd7-412f-43fc-a3e6-5bff3a52cfae.png)

What i have tried so far.

**Comment by glenn-jocher** [comment]
@szcarr to skip a specific video from a directory when using `detect.py`, you can achieve this by moving the video file you want to skip to a different directory before running the detection. Then, you can move it back afterwards. This way, it won't be included in the detection process.

Let me know if this solution works for you or if you need further assistance!
