### ISSUE TITLE
Settings of optimizer parameters in different versions

### ISSUE THREAD

**Issue by LUO77123** [ultralytics/yolov5#7899]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Settings of optimizer parameters in yolov5-6.0 train.py:
 optimizer = Adam(g0, lr=hyp['lr0'], betas=(hyp['momentum'], 0.999))
g0:   nn.BatchNorm2d.weight
Settings of optimizer parameters in yolov5-6.1 train.py:
optimizer = AdamW(g[2], lr=hyp['lr0'], betas=(hyp['momentum'], 0.999))
g[2]:(nn.Parameter .bias)
I wonder why yolov5-6.1 changed the settings. Thanks!

### Additional

![image](https://user-images.githubusercontent.com/87272337/169486432-fb6c5690-a83a-4eab-885a-e8958e802a54.png)
![image](https://user-images.githubusercontent.com/87272337/169491767-4c19ff1c-cf4f-4059-a6cc-da1f6e92773d.png)

**Comment by glenn-jocher** [comment]
its called improving the code

**Comment by LUO77123** [comment]
Thank you for your busy schedule to answer my question

**Comment by LUO77123** [comment]
> its called improving the code

And I want to know Multi-GPU Training in train.sh
![image](https://user-images.githubusercontent.com/87272337/169516531-4a813692-a58f-4858-836d-6b9cdb0a19f3.png)
Is this setting the recommended DDP model？If not, how to modify it? Is that right ？
![image](https://user-images.githubusercontent.com/87272337/169517208-718be365-36a5-46e2-b2d7-1e582312138a.png)

**Comment by glenn-jocher** [comment]
@LUO77123 see Multi-GPU Training tutorial:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️  RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Roboflow for Datasets, Labeling, and Active Learning](https://docs.ultralytics.com/yolov5/tutorials/roboflow_datasets_integration)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TFLite, ONNX, CoreML, TensorRT Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [Architecture Summary](https://docs.ultralytics.com/yolov5/tutorials/architecture_description)&nbsp; ⭐ NEW

Good luck 🍀 and let us know if you have any other questions!

**Comment by LUO77123** [comment]
> @LUO77123 see Multi-GPU Training tutorial:
> 
> ## YOLOv5 Tutorials
> * [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)  🚀 RECOMMENDED
> * [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)  ☘️  RECOMMENDED
> * [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)  🌟 NEW
> * [Roboflow for Datasets, Labeling, and Active Learning](https://docs.ultralytics.com/yolov5/tutorials/roboflow_datasets_integration)  🌟 NEW
> * [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
> * [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)  ⭐ NEW
> * [TFLite, ONNX, CoreML, TensorRT Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
> * [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
> * [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
> * [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
> * [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
> * [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)  ⭐ NEW
> * [Architecture Summary](https://docs.ultralytics.com/yolov5/tutorials/architecture_description)  ⭐ NEW
> 
> Good luck 🍀 and let us know if you have any other questions!

Thanks! I know the command statement in Multi-GPU Training is:
$ python -m torch.distributed.launch --nproc_per_node 2 train.py --batch 64 --data coco.yaml --cfg yolov5s.yaml --weights '' --sync-bn
but I don't know how to use it in train.sh file，So I want to know if the above command is right to use nohup in train.sh file.
![image](https://user-images.githubusercontent.com/87272337/169526557-dbd80730-5573-403a-a9f7-e6b5c1ee5b70.png)

**Comment by LUO77123** [comment]
> @LUO77123 see Multi-GPU Training tutorial:
> 
> ## YOLOv5 Tutorials
> * [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)  🚀 RECOMMENDED
> * [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)  ☘️  RECOMMENDED
> * [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)  🌟 NEW
> * [Roboflow for Datasets, Labeling, and Active Learning](https://docs.ultralytics.com/yolov5/tutorials/roboflow_datasets_integration)  🌟 NEW
> * [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
> * [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)  ⭐ NEW
> * [TFLite, ONNX, CoreML, TensorRT Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
> * [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
> * [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
> * [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
> * [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
> * [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)  ⭐ NEW
> * [Architecture Summary](https://docs.ultralytics.com/yolov5/tutorials/architecture_description)  ⭐ NEW
> 
> Good luck 🍀 and let us know if you have any other questions!



> its called improving the code

In addition, I modified the backbone network of yolov5 to Swin, CSwin and ConvNext. when I modified it, the input picture is 1120 * 1120. The original training in yolov5 is fast, the modified network training is slow, and the video memory occupation is large. Is it yolov5 who optimized the program and destroyed the structure after the change, resulting in the modified network is very bloated.

**Comment by glenn-jocher** [comment]
@LUO77123 YOLOv5 has no train.sh file

If your modifications produce undesirable results those are due to your modifications and beyond the scope of Ultralytics support.

**Comment by LUO77123** [comment]
> @LUO77123 YOLOv5 has no train.sh file
> 
> If your modifications produce undesirable results those are due to your modifications and beyond the scope of Ultralytics support.

When I use "python -m torch.distributed.launch --nproc_per_node 4 train.py --batch-size 8 --device 4,5,6,7 --sync-bn",report errors：
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed
raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/home/zhuyu/anaconda3/envs/yolo5obb/bin/python', '-u', 'train.py', '--local_rank=3', '--batch-size', '8', '--device', '4,5,6,7', '--sync-bn']' returned non-zero exit status 1.

**Comment by pderrenger** [comment]
@LUO77123 the error suggests an issue with the distributed training setup. Ensure your environment is correctly configured for multi-GPU training. You might need to adjust `OMP_NUM_THREADS` or check for compatibility issues with your setup. For detailed guidance, refer to the [Multi-GPU Training tutorial](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training/).
