### ISSUE TITLE
training with specific image size.

### ISSUE THREAD

**Issue by kzyadaking** [ultralytics/yolov5#7907]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

i have images that have 288 width, 512 height. 
i looked for a solution and it looks like i could do it by using --rect but im not really sure since last time i tried it gave me way less map than without it. so im wondering if im doing something wrong.
in this case should i train by using --img 512 --rect?

**Comment by glenn-jocher** [comment]
@kzyadaking if you don't like results of an argument I'd suggest not using it.
