### ISSUE TITLE
I can't understand the process of warmup

### ISSUE THREAD

**Issue by SISTMrL** [ultralytics/yolov5#791]
## ❔Question

Due to the lack of knowledge, I can't understand the meaning of warmup, could you give me some breif explanations or some references, thanks very much!
![Screenshot from 2020-08-19 22-42-08](https://user-images.githubusercontent.com/47938053/90649664-8cd05e80-e26d-11ea-9f0e-7a636c6fef12.png)

**Comment by glenn-jocher** [comment]
Reduces instabilities in early training.
