### ISSUE TITLE
ignoring corrupt image/label: module 'PIL.TiffTags' has no attribute 'LONG8'

### ISSUE THREAD

**Issue by cgotschlich** [ultralytics/yolov5#7910]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

All my training images were skipped, with the following messages:
`ignoring corrupt image/label: module 'PIL.TiffTags' has no attribute 'LONG8'`
finally throwing
`AssertionError: [34m[1mtrain: [0mNo labels in /datadrive/Git/koi/data/thesis/100-img-baseline/0fold/labels/train.cache. Can not train without labels. See https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data`

### Environment

- YOLO: YOLOv5 v6.1-206-ga9a92ae
- torch: 1.10.0
- no CUDA
- OS: Ubuntu 20.04.4 LTS
- Python: 3.9.5
- Pillow: 9.1.1

### Minimal Reproducible Example

`python /datadrive/Git/koi/src/yolov5/train.py --img 640 --batch 25 --epochs 100 --data /datadrive/Git/koi/data/thesis/100-img-baseline/0fold/dataset.yaml --weights yolov5m.pt`

### Additional

I was able to work around this when debugging. I had a breakpoint at this line (below) and deleted the train.cache file #https://github.com/ultralytics/yolov5/blob/5774a1514de193c74ecc5203281da8de3c13f9af/utils/dataloaders.py#L445

My best guess is that there is an issue with Pillow. According to a comment [here](https://stackoverflow.com/questions/71858606/attributeerror-module-pil-tifftags-has-no-attribute-long8) Pillow supports 'LONG8' since 9.1, suggesting an earlier version is being used. 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@currychris I've not seen this before. If the images load correctly you might also bypass some of the checks here. If you see fit to make any modifications that might contribute to master please submit a PR:
https://github.com/ultralytics/yolov5/blob/5774a1514de193c74ecc5203281da8de3c13f9af/utils/dataloaders.py#L925-L937

**Comment by cgotschlich** [comment]
@glenn-jocher thank you for answering so quickly.
I just re-ran train.py on a different dataset and I cannot reproduce the issue. My best guess is that the train.cache file was left there from an earlier aborted run.

**Comment by glenn-jocher** [comment]
You're welcome, @currychris! That's great to hear. It's possible that the old train.cache file might have caused the issue. Let me know if you encounter any further issues. Good luck with your training!

**Comment by jiahengqi** [comment]
I encountered a similar problem and eventually found out that my hard drive was full and the train.cache file could not be saved. After deleting some other data, it could run normally

**Comment by pderrenger** [comment]
@jiahengqi Thanks for sharing that insight! Insufficient disk space preventing proper cache file creation is definitely another potential cause for training issues like this. For anyone experiencing similar cache-related errors, checking available disk space and clearing the cache files (train.cache, val.cache) should be among the first troubleshooting steps.
