### ISSUE TITLE
Converting the Tensorflow saved_model in to a keras model '_UserObject' object has no attribute 'summary' 

### ISSUE THREAD

**Issue by Matteo-Castrignano** [ultralytics/yolov5#7911]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

hi, i need to convert the yolo model in a keras model in order to change the tensor type to rum some experiment using a posit160 library. But i have this error "'_UserObject' object has no attribute 'summary' ". i have not idea how to chance the model in order to manage the weights, the input and the output type

### Use case

model_path = "yolov5/yolov5s_saved_model"
imported = tf.saved_model.load(model_path)
imported.summary()

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by RoudyES** [comment]
Yolov5 exports the model to a TensorFlow savedModel rather than a Keras model. TensorFlow models don't have the High-Level calls such as `fit()` and `summary()`. You need to look into ways to convert from TF models to Keras models or maybe export Yolov5 to ONNX and try to convert that back to Keras.

**Comment by glenn-jocher** [comment]
@Matteo-Castrignano @RoudyES set `keras=True` on SavedModel export.

https://github.com/ultralytics/yolov5/blob/5774a1514de193c74ecc5203281da8de3c13f9af/export.py#L275-L286

**Comment by Matteo-Castrignano** [comment]
> @Matteo-Castrignano @RoudyES set `keras=True` on SavedModel export.
> 
> https://github.com/ultralytics/yolov5/blob/5774a1514de193c74ecc5203281da8de3c13f9af/export.py#L275-L286

Do you know how to do it from linux terminal?
So, i mean how can i specify the parameters Keras = true in the export command? I have already tried it but i have found the command to do this

**Comment by RoudyES** [comment]
> @Matteo-Castrignano @RoudyES set `keras=True` on SavedModel export.
> 
> https://github.com/ultralytics/yolov5/blob/5774a1514de193c74ecc5203281da8de3c13f9af/export.py#L275-L286

Oh I didn't know that's a thing! Thank you for pointing it out!

**Comment by glenn-jocher** [comment]
@Matteo-Castrignano good news 😃! Your original issue may now be fixed ✅ in PR #7921. Now you can use the `--keras` flag when exporting TF models:

```bash
python export.py --include saved_model --keras
```

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
