### ISSUE TITLE
the C3-GC weight file

### ISSUE THREAD

**Issue by yxx-byte** [ultralytics/yolov5#7914]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, please use C3-GC to train the weight file of the backbone network, preferably the weight file trained under the COCO dataset.

**Comment by glenn-jocher** [comment]
@yxx-byte I'm not familiar with a C3-GC module. What module are you referring to?
