### ISSUE TITLE
results.pandas().xyxy[0] in table

### ISSUE THREAD

**Issue by vortexModding** [ultralytics/yolov5#7918]
hello, after searching for quite some time I come to ask you for help about results.pandas().xyxy[0]

I can't break it down and put it in a table like this

possition = ([number , Xmin , Xmax , Ymin , Ymax , classe])

I manage to see them in the console without problem but put them in the table I can't do it

thank you in advance for your help

**Comment by glenn-jocher** [comment]
@vortexModding I don't know what you mean by 'put in table' but you can export to pretty much any format from a pandas dataframe. See their docs: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html

**Comment by vortexModding** [comment]
Example
result in console
                xmin,            ymin,              xmax,           ymax,              confidence,     class,    name
0 ,             537.057434,  219.105545,   850.471680,  242.622894,    0.277357  ,    1,       allier

transfer to an array
position = ([0 , 537.057434 ,  219.105545 ,  850.471680  ,  242.622894 , 0.277357, 1)

I'll try to look at what you give me, if you have a little idea of ​​code to do that I'm a taker :)

**Comment by glenn-jocher** [comment]
@vortexModding got it, you can convert the dataframe to a 2D array using `values` attribute of pandas DataFrame. Here's how you can do it:

```python
import pandas as pd

# Assuming your dataframe is called 'result'
position = result.iloc[0][['xmin', 'ymin', 'xmax', 'ymax', 'confidence', 'class']].values
```

This will give you the array `position` containing the values you are looking for. Let me know if you need further assistance!
