### ISSUE TITLE
doesn't show any info about P, R, and mAP after the a_front label

### ISSUE THREAD

**Issue by mohammad69h94** [ultralytics/yolov5#7922]
I have trained about 15000 images with 95 classes. with this config: 
models: yolov5s.YAML
batch = 32
epochs: 50
weights: yolov5s.pt

doesn't show any info about P, R, and mAP after the a_front label
and after training result is as follows:
The result
![Screenshot from 2022-05-22 16-14-04](https://user-images.githubusercontent.com/38998372/169693484-8ffc1d08-d990-4f79-b230-08a6ac229672.png)
 was uploaded as an image too.

YOLOv5s summary: 213 layers, 7266340 parameters, 0 gradients, 16.6 GFLOPs
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 14/14 [00:28<00:00,  2.03s/it]                                                                            
                 all        842      14522      0.374      0.292      0.311      0.243
           lic_plate        842        597      0.894      0.992      0.961      0.873
            int_code        842        597      0.924      0.811      0.925      0.608
                   0        842       1355       0.76     0.0537      0.576      0.215
                   1        842       1197      0.896      0.511      0.864      0.536
                   2        842       1023      0.918      0.741      0.906      0.676
                   3        842        906      0.894      0.819      0.904      0.708
                   4        842        998      0.887      0.805      0.881      0.667
                   5        842        936      0.889      0.843      0.917      0.734
                   6        842        862      0.887        0.8      0.869      0.672
                   7        842       1039      0.914      0.831      0.924      0.723
                   8        842        878       0.91      0.818      0.917      0.712
                   9        842        958      0.922      0.834      0.933      0.702
                   b        842         37      0.825          1      0.928      0.763
                   j        842         35      0.775      0.971      0.973      0.761
                   d        842         56      0.765      0.964      0.903      0.714
                   s        842         51      0.663      0.961      0.898      0.788
                 sad        842         42      0.611      0.952      0.863      0.756
                  ta        842         42      0.759      0.952      0.958      0.807
                  gh        842         44      0.794      0.977      0.972      0.809
                   l        842         37      0.812      0.973      0.878      0.714
                   m        842         50      0.961      0.984      0.968        0.8
                   n        842         32      0.907      0.913      0.902      0.719
                   v        842         48       0.92       0.96      0.916      0.682
                   h        842         48      0.937       0.93      0.964      0.793
                   y        842         36      0.893      0.925      0.957      0.774
                None        842         36          1          0     0.0115    0.00787
             a_front        842         30          1          0          0          0
              a_back        842         27          0          0          0          0
          a_motor_no        842         27          0          0          0          0
        a_chassis_no        842         26          1          0          0          0
               a_vin        842         26          0          0          0          0
             b_front        842         29          0          0          0          0
              b_back        842         26          0          0          0          0
          b_motor_no        842         26          0          0          0          0
        b_chassis_no        842         27          0          0          0          0
               b_vin        842         30          0          0          0          0
                 a_v        842         25          0          0          0          0
                 b_v        842          8          0          0          0          0
                 c_v        842        114          0          0          0          0
                 d_v        842         22          0          0          0          0
                 e_v        842         15          0          0          0          0
                 f_v        842         75          0          0          0          0
                 g_v        842         14          1          0          0          0
                 h_v        842         11          0          0          0          0
                 i_v        842        118          0          0          0          0
                 j_v        842         21          0          0          0          0
                 k_v        842         15          0          0          0          0
                 l_v        842         22          0          0          0          0
                 m_v        842          4          0          0          0          0
                 n_v        842         15          0          0          0          0
                 o_v        842         14          0          0          0          0
                 p_v        842         41          0          0          0          0
                 q_v        842          7          0          0          0          0
                 r_v        842        140          0          0          0          0
                 s_v        842         25          0          0          0          0
                 t_v        842         18          0          0          0          0
                 u_v        842          6          0          0          0          0
                 v_v        842        110          0          0          0          0
                 w_v        842         22          0          0          0          0
                 x_v        842         17          0          0          0          0
                 y_v        842          6          1          0          0          0
                 z_v        842          4          0          0          0          0
                 0_v        842        152          0          0          0          0
                 1_v        842        281          0          0          0          0
                 2_v        842        150          0          0          0          0
                 3_v        842        103          0          0          0          0
                 4_v        842         83          0          0          0          0
                 5_v        842         97          0          0          0          0
                 6_v        842         84          0          0          0          0
                 7_v        842         80          0          0          0          0
                 8_v        842        114          0          0          0          0
                 9_v        842        145          0          0          0          0
               v_vin        842        130          1          0          0          0

**Comment by glenn-jocher** [comment]
@mohammad69h94 val.py shows information for all your classes. Zero is a value.

**Comment by mohammad69h94** [comment]
> @mohammad69h94 val.py shows information for all your classes. Zero is a value.

After apply val.py I get error:

python3 val.py --weights yolov5m.pt --data mergeAllModelsProject/allMergedData.yaml --img 640

assert ncm == nc, f'{weights[0]} ({ncm} classes) trained on different --data than what you passed ({nc} ' \
AssertionError: yolov5m.pt (80 classes) trained on different --data than what you passed (95 classes). Pass correct combination of --weights and --data that are trained together.

**Comment by glenn-jocher** [comment]
@mohammad69h94 the error message is self explanatory:

> yolov5m.pt (80 classes) trained on different --data than what you passed (95 classes). Pass correct combination of --weights and --data that are trained together.
