### ISSUE TITLE
Can I automatically determine the  depthmutiple [dm] and widthmutiple [wm] to get a model for my dataset（by accuracy and speed balance）？

### ISSUE THREAD

**Issue by AllenZYJ** [ultralytics/yolov5#7924]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hi ,thankyou for your helpful work,it is great~ 
but i have some questions for ask...like title，
I found the larger model parameter [dm] and [wm]  is not always better , often the model is small, but the ap dont have big disparity between small model and larger model, I don't know if it's a coincidence.
and ,the dm and wm determine the model size and speed, so, when i can train the model from 0.1 to 1.0, i can determine the model parameter to balance speed and map. I don't know if I'm right or not ,
**please give me some advice, thank you very much~.**

**Comment by glenn-jocher** [comment]
@AllenZYJ yes modifying the depth and width multiples is the easiest way to scale YOLOv5 models from nano to xlarge. This technique was first popularized by EfficientDet, and this is what we do for the official models. 

You can use your own values to further customize a model to your particular use case.

**Comment by AllenZYJ** [comment]
> @AllenZYJ yes modifying the depth and width multiples is the easiest way to scale YOLOv5 models from nano to xlarge. This technique was first popularized by EfficientDet, and this is what we do for the official models.
> 
> You can use your own values to further customize a model to your particular use case.
thank you very much ~ now I try to run a task automatic，design the dm and wm from 0 to 1.5 to scale yolov5 model ，It work
