### ISSUE TITLE
Display fps on frame

### ISSUE THREAD

**Issue by sainsaji** [ultralytics/yolov5#7927]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How do i display fps on the display frame on the webcam detection frame?
![image](https://user-images.githubusercontent.com/95070425/169747819-c7af6f57-0bbe-424e-b8bf-3d05b2860cf6.png)

### Additional

I've tried printing to the console but I'm getting inaccurate fps

**Comment by neo133** [comment]
Hi,
You can directly use cv2 inbuilt function to write the FPS value on each frame of the camera.
Use **cv2.putText()** method to do so. Something like:
**image = cv2.putText(image, '---text---', org, font, fontScale, color, thickness, cv2.LINE_AA)**

_Reference: [https://docs.opencv.org/4.x/dc/da5/tutorial_py_drawing_functions.html]_

**Comment by glenn-jocher** [comment]
@neo133 hi there,

You can use the OpenCV `putText` function to display the FPS on the frame. Here's an example of how to do it:

```python
import cv2

# Inside the loop where you process frames
fps = 1.0 / elapsed  # Calculate the frames per second (elapsed is the time taken to process the frame)
image = cv2.putText(image, f'FPS: {fps:.2f}', (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2, cv2.LINE_AA)
```

This will display the FPS at the top-left corner of the frame. You can adjust the position, font size, and color as per your preference.

For more details, you can refer to the OpenCV documentation: [OpenCV Drawing Functions](https://docs.opencv.org/4.x/dc/da5/tutorial_py_drawing_functions.html)

I hope this helps! Let me know if you have any more questions.
