### ISSUE TITLE
yolov5 model inference freeze when --view-img is used 

### ISSUE THREAD

**Issue by st186** [ultralytics/yolov5#7928]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

Whenever I am running the model inference without --view-img it is giving out predictions -

python3 yolov5/detect.py --source 2022040715130520220407154305.mp4 --weights best.pt 
detect: weights=['best.pt'], source=2022040715130520220407154305.mp4, data=yolov5/data/coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=yolov5/runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False
YOLOv5 🚀 v6.1-211-gcee5959 Python-3.8.10 torch-1.10.0+cu111 CUDA:0 (NVIDIA GeForce RTX 3050, 7974MiB)

Fusing layers... 
YOLOv5s summary: 232 layers, 7246518 parameters, 0 gradients
video 1/1 (1/36067) /media/subham/hdd/object_detector_workstation/2022040715130520220407154305.mp4: 384x640 2 products, Done. (0.442s)
video 1/1 (2/36067) /media/subham/hdd/object_detector_workstation/2022040715130520220407154305.mp4: 384x640 2 products, Done. (0.005s)
video 1/1 (3/36067) /media/subham/hdd/object_detector_workstation/2022040715130520220407154305.mp4: 384x640 2 products, Done. (0.006s)
video 1/1 (4/36067) /media/subham/hdd/object_detector_workstation/2022040715130520220407154305.mp4: 384x640 1 product, Done. (0.006s)
video 1/1 (5/36067) /media/subham/hdd/object_detector_workstation/2022040715130520220407154305.mp4: 384x640 1 product, Done. (0.005s)
video 1/1 (6/36067) /media/subham/hdd/object_detector_workstation/2022040715130520220407154305.mp4: 384x640 1 product, Done. (0.005s)
video 1/1 (7/36067) /media/subham/hdd/object_detector_workstation/2022040715130520220407154305.mp4: 384x640 1 product, Done. (0.007s)
video 1/1 (8/36067) /media/subham/hdd/object_detector_workstation/2022040715130520220407154305.mp4: 384x640 1 product, Done. (0.005s)
video 1/1 (9/36067) /media/subham/hdd/object_detector_workstation/2022040715130520220407154305.mp4: 384x640 1 product, Done. (0.005s)

But when I am using --view-img as an argument to visualize the results the model inference freezes -

python3 yolov5/detect.py --source 2022040715130520220407154305.mp4 --weights best.pt --view-img
detect: weights=['best.pt'], source=2022040715130520220407154305.mp4, data=yolov5/data/coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=True, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=yolov5/runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False
YOLOv5 🚀 v6.1-211-gcee5959 Python-3.8.10 torch-1.10.0+cu111 CUDA:0 (NVIDIA GeForce RTX 3050, 7974MiB)

Fusing layers... 
YOLOv5s summary: 232 layers, 7246518 parameters, 0 gradients

After this nothing happens. 

Can someone help fixing this bug

### Environment

YOLOv5 🚀 v6.1-211-gcee5959 Python-3.8.10 torch-1.10.0+cu111 CUDA:0 (NVIDIA GeForce RTX 3050, 7974MiB)
OS - ubuntu 20.04

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@st186 I'm not able to reproduce any issues with --view-img myself, but instead of viewing you could just play the annotated images back that are saved in your runs/detect/exp directory.
