### ISSUE TITLE
feature extraction to pass it to a neural network

### ISSUE THREAD

**Issue by alexandercesarr** [ultralytics/yolov5#7929]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I trained a model on my custom dataset. now I wanna use my model and pass each entrance image features to a new layer of another neural network. I read that you added feature visualization. But I don't want its visualization part. I just want its features to pass to another network.
yolov5 is before my neural network and just want to extract image features and give it to my neural network to train

**Comment by glenn-jocher** [comment]
@alexandercesarr sure, you can extract anything you want by customizing your model. We don't assist with code customization, but you can go to yolo.py and Detect() module to get started.

**Comment by alexandercesarr** [comment]
Thanks @glenn-jocher. But my goal is to use the trained model. In other words, normally we give a photo to the model and it gives us the labels in the photo that we gave it during the training. But now I only need the features I extracted from the image and nothing else. How can I get this? I have seen in the questions that you said that this feature has been added to the code that we can have a visualization of these features extracted from images, but I just want the values. Can you please help me?

**Comment by glenn-jocher** [comment]
@alexandercesarr as I said you can extract anything you want anywhere in the model in models/yolo.py or any other module in models/common.py. Just put breakpoints in the model forward method to introspect variable values.
