### ISSUE TITLE
Keras model, get_weights() does not working

### ISSUE THREAD

**Issue by Matteo-Castrignano** [ultralytics/yolov5#7930]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

WARNING:absl:Importing a function (__inference_tf_c3_7_layer_call_and_return_conditional_losses_8593) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_4_layer_call_and_return_conditional_losses_17886) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_layer_call_and_return_conditional_losses_19821) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_1_layer_call_and_return_conditional_losses_15076) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_5_layer_call_and_return_conditional_losses_20105) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_2_layer_call_and_return_conditional_losses_9475) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_51_layer_call_and_return_conditional_losses_8656) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_10_layer_call_and_return_conditional_losses_6574) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_14_layer_call_and_return_conditional_losses_19674) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_8_layer_call_and_return_conditional_losses_18792) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_14_layer_call_and_return_conditional_losses_19644) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_layer_call_and_return_conditional_losses_9864) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_8_layer_call_and_return_conditional_losses_5966) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_5_layer_call_and_return_conditional_losses_7609) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_5_layer_call_and_return_conditional_losses_16371) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_layer_call_and_return_conditional_losses_6830) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_layer_call_and_return_conditional_losses_14867) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_3_layer_call_and_return_conditional_losses_20017) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_layer_call_and_return_conditional_losses_9962) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_33_layer_call_and_return_conditional_losses_15954) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_2_layer_call_and_return_conditional_losses_7161) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_6_layer_call_and_return_conditional_losses_18375) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_45_layer_call_and_return_conditional_losses_16440) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_layer_call_and_return_conditional_losses_14622) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_7_layer_call_and_return_conditional_losses_7867) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_7_layer_call_and_return_conditional_losses_9755) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_6_layer_call_and_return_conditional_losses_20181) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_51_layer_call_and_return_conditional_losses_16705) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_15_layer_call_and_return_conditional_losses_15260) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_1_layer_call_and_return_conditional_losses_14701) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_1_layer_call_and_return_conditional_losses_6750) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_2_layer_call_and_return_conditional_losses_17506) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_3_layer_call_and_return_conditional_losses_15767) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_7_layer_call_and_return_conditional_losses_16830) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_6_layer_call_and_return_conditional_losses_16636) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_5_layer_call_and_return_conditional_losses_16300) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_1_layer_call_and_return_conditional_losses_9691) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_2_layer_call_and_return_conditional_losses_17475) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_layer_call_and_return_conditional_losses_14641) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_7_layer_call_and_return_conditional_losses_6871) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_14_layer_call_and_return_conditional_losses_19614) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_25_layer_call_and_return_conditional_losses_9296) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_2_layer_call_and_return_conditional_losses_17568) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_2_layer_call_and_return_conditional_losses_19941) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_4_layer_call_and_return_conditional_losses_17828) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference__wrapped_model_4006) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_layer_call_and_return_conditional_losses_4330) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_4_layer_call_and_return_conditional_losses_17770) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_12_layer_call_and_return_conditional_losses_19410) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_3_layer_call_and_return_conditional_losses_15839) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_model_layer_call_and_return_conditional_losses_14065) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_51_layer_call_and_return_conditional_losses_16724) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_12_layer_call_and_return_conditional_losses_19380) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_1_layer_call_and_return_conditional_losses_6978) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_33_layer_call_and_return_conditional_losses_7382) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_3_layer_call_and_return_conditional_losses_5065) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_3_layer_call_and_return_conditional_losses_7298) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_7_layer_call_and_return_conditional_losses_5804) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_9_layer_call_and_return_conditional_losses_18974) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_4_layer_call_and_return_conditional_losses_20061) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_10_layer_call_and_return_conditional_losses_19116) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_2_layer_call_and_return_conditional_losses_17537) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_8_layer_call_and_return_conditional_losses_18761) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_6_layer_call_and_return_conditional_losses_16565) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_9_layer_call_and_return_conditional_losses_18884) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_8_layer_call_and_return_conditional_losses_18730) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_4_layer_call_and_return_conditional_losses_5108) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_10_layer_call_and_return_conditional_losses_19056) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_25_layer_call_and_return_conditional_losses_15673) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_15_layer_call_and_return_conditional_losses_15279) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_9_layer_call_and_return_conditional_losses_20342) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_1_layer_call_and_return_conditional_losses_19897) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_15_layer_call_and_return_conditional_losses_7027) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_9_layer_call_and_return_conditional_losses_18914) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_45_layer_call_and_return_conditional_losses_16459) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_6_layer_call_and_return_conditional_losses_18460) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_7_layer_call_and_return_conditional_losses_16901) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_6_layer_call_and_return_conditional_losses_5620) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_39_layer_call_and_return_conditional_losses_7515) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_3_layer_call_and_return_conditional_losses_9240) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_2_layer_call_and_return_conditional_losses_4678) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_7_layer_call_and_return_conditional_losses_14936) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_10_layer_call_and_return_conditional_losses_20417) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_45_layer_call_and_return_conditional_losses_7650) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_5_layer_call_and_return_conditional_losses_8935) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tfsppf_layer_call_and_return_conditional_losses_7355) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_15_layer_call_and_return_conditional_losses_9547) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_layer_call_and_return_conditional_losses_6723) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_1_layer_call_and_return_conditional_losses_14682) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_39_layer_call_and_return_conditional_losses_16196) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_25_layer_call_and_return_conditional_losses_15654) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_1_layer_call_and_return_conditional_losses_4635) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_6_layer_call_and_return_conditional_losses_7738) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_1_layer_call_and_return_conditional_losses_15175) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_4_layer_call_and_return_conditional_losses_16058) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_2_layer_call_and_return_conditional_losses_15427) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_12_layer_call_and_return_conditional_losses_19320) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_4_layer_call_and_return_conditional_losses_9080) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_9_layer_call_and_return_conditional_losses_18944) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_6_layer_call_and_return_conditional_losses_18290) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_8_layer_call_and_return_conditional_losses_18699) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_7_layer_call_and_return_conditional_losses_20224) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_9_layer_call_and_return_conditional_losses_6270) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_51_layer_call_and_return_conditional_losses_7779) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_10_layer_call_and_return_conditional_losses_19086) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_14_layer_call_and_return_conditional_losses_19584) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_model_layer_call_and_return_conditional_losses_13001) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_4_layer_call_and_return_conditional_losses_16129) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_6_layer_call_and_return_conditional_losses_8764) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_2_layer_call_and_return_conditional_losses_15553) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_layer_call_and_return_conditional_losses_14795) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_7_layer_call_and_return_conditional_losses_14955) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_25_layer_call_and_return_conditional_losses_7218) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tfsppf_layer_call_and_return_conditional_losses_15924) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_6_layer_call_and_return_conditional_losses_18205) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_45_layer_call_and_return_conditional_losses_8827) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_4_layer_call_and_return_conditional_losses_17944) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_10_layer_call_and_return_conditional_losses_19146) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_4_layer_call_and_return_conditional_losses_7476) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_1_layer_call_and_return_conditional_losses_9920) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_8_layer_call_and_return_conditional_losses_20267) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_12_layer_call_and_return_conditional_losses_19350) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_5_layer_call_and_return_conditional_losses_5151) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.
WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.

### Minimal Reproducible Example

model = keras.models.load_model(model_path, experimental_custom_gradients=True)
model.get_weights()

### Additional

Hi ! i have export the model with the option "--keras" and i need to change the dtype of the layer's weights, but first i would obtain the current weights with "model.get_weights()". I have some warning but the predict and the summary are working, instead i can not manage the weights. Do some one have an idea? 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Matteo-Castrignano I'd raise this issue directly on keras as this is outside of our control.
