### ISSUE TITLE
Hi, I want to decorate the output image/video. Who wants to know how?

### ISSUE THREAD

**Issue by ghzmwhdk777** [ultralytics/yolov5#7933]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to apply a red border to the final output image. So the way I did it is as follows.

1. The cv2.copyMakeBorder was applied to im0 located at detect.py but failed.

2. In the results of the Annotator class at utils/plots.py, 

    def result(self,danger_result):
        Return annotated image as array
        if danger_result==True:
            self.im = cv2.copyMakeBorder(self.im, 100, 100, 100, 100, cv2.BORDER_CONSTANT, value=[0, 0, 255])
            print("Check!")
        return np.asarray(self.im)

I tried editing it like this, but it failed.

I checked with print, but the "Check!" here is printed well. I don't know what the problem is.

Does anyone know how?

**Comment by glenn-jocher** [comment]
@ghzmwhdk777 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # yolov5n - yolov5x6 official model
#                                            'custom', 'path/to/best.pt')  # custom model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by ghzmwhdk777** [comment]
@glenn-jocher Thank you for your reply.
But I need a video editing method from the detect.py code or another configuration code.
I think it is possible for me to edit each image. But I don't know how to edit the frame.

**Comment by glenn-jocher** [comment]
@ghzmwhdk777 Understood! To edit the output of video frames, one approach is to modify `detect.py`'s `write` method at `utils/plots.py`. With this method, you could apply a border to each frame using OpenCV.

Here's a basic example to modify the `write` method:

```python
# In utils/plots.py

    def write(self, img, path, names, results):
        # ... (existing code)
        if results.pred[0]:
            img = cv2.copyMakeBorder(img, 100, 100, 100, 100, cv2.BORDER_CONSTANT, value=[0, 0, 255])  # Add red border
        # ... (existing code)
```

This would apply a red border to an image if any predictions are made.

After the modification, running `python detect.py --source path/to/video.mp4` should apply a red border to each frame with detections.

Does this help? Let me know if you have further questions!
