### ISSUE TITLE
yolov5, can not change the dtype in the keras model

### ISSUE THREAD

**Issue by Matteo-Castrignano** [ultralytics/yolov5#7935]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

hi, i'm try to change the dtype of each layer in order to perform some test with different types of this. But i obtain this error:
AttributeError: Can't set the attribute "dtype", likely because it conflicts with an existing read-only @property of the object. Please choose a different name.
First i have retrived the weights and i have change their type and than i have put they again in the network with the set_weights(), but the type does not change because i can not change the layers. Do someone know how to resolve it?

### Minimal Reproducible Example

for w, layer in zip(model.layers, model_quant.layers):
    y = w.get_weights()
    y = [e.astype(keras.backend.floatx()) for e in y]
    layer.trainable = True
    layer.dtype = 'float64'
    layer.set_weights(y)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Matteo-Castrignano is errors are caused by other tools on custom code I'd post on those tools, i.e. Keras/TF repo.
