### ISSUE TITLE
Fine tuning on old and new classes!

### ISSUE THREAD

**Issue by danik7** [ultralytics/yolov5#7939]
Hey!
I didn’t find any question about that, so I would like to get any help. 

I want to create a model which can detect (box +class) few (not all) classes which exist in COCO and two more *new* classes. 

I have a dataset consisting of images with just the two new object tagged. 

If I will take a pretrained model and do fine tuning on the two new object, I will loss the other “old” classes which exist. 

What is the best way to create a model like I want? (which includes the few classes of COCO and two more new classes, when I have just 1500 tagged images with only the two new objects tagged). 

Thank you!

**Comment by glenn-jocher** [comment]
@danik7 https://community.ultralytics.com/t/how-to-combine-weights-to-detect-from-multiple-datasets
