### ISSUE TITLE
Yolov5 tflite uint8 export

### ISSUE THREAD

**Issue by WiFiHan** [ultralytics/yolov5#7942]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Yolov5 tflite model export with uint8 input doesn't work.
I work in google colab. I want to export tflite-uint8 model.

The model is exported to tflite fp-16 when not adding `--uint8`, but when adding `--uint8`, no tflite model found in the export path. Instead, there's only 'saved_model.pb' file.

I checked #5707, and downgraded my flatbuffer library to 1.12.

### Environment

-Google colab
-Python 3.7.13

### Minimal Reproducible Example

My code is:

`%cd /content/drive/MyDrive/yolov5/
!python export.py --img 640 --conf 0.25 --weights /content/drive/MyDrive/new_yolov5/runs/train/20220523_1945003/weights/best.pt/ --int8 --include saved_model tflite`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by WiFiHan** [comment]
I've found that the code below works:

`!python export.py --weights /content/drive/MyDrive/yolov5/runs/train/fine_tuning2/weights/best.pt --include saved_model tflite --int8`

When data path is not specified, the code above worked. But still the code below doesn't export tflite model:

`!python export.py --img 640 --data /content/drive/MyDrive/test5_mk_od/data/dataset.yaml --weights /content/drive/MyDrive/yolov5/runs/train/fine_tuning2/weights/best.pt --include saved_model tflite --int8`

**Comment by glenn-jocher** [comment]
@WiFiHan --data is just used for quantization. Default --data is COCO128. You can pass your own if you want the same way as coco128.yaml.

**Comment by WiFiHan** [comment]
> @WiFiHan --data is just used for quantization. Default --data is COCO128. You can pass your own if you want the same way as coco128.yaml.

But the problem is that when I pass my own data then quantization and tflite export aren't done. Do you mean there's no problem when I pass '--data 'default with my own custom weights(.pt file)?

**Comment by glenn-jocher** [comment]
@WiFiHan a dataset is always passed:
https://github.com/ultralytics/yolov5/blob/27911dc824b28f6d805dc88360a3313ce0c9cae5/export.py#L569

If you have a reproducible bug please submit a bug report with exact code to reproduce (including a commonly available dataset, not your custom dataset).

**Comment by WiFiHan** [comment]
Thanks for your kind help! With more research, I'll submit a bug report with exact code.

**Comment by WiFiHan** [comment]
I found that if I pass my own custom dataset `--data /content/drive/MyDrive/test5_mk_od/data/dataset.yaml` , then the train data of `dataset.yaml` file must not be `.txt`; it worked when it was written in the form of directory.

```
names: [Book, Calculator, Mobile phone, Pencil case, Postit]
nc: 5
train: /content/drive/MyDrive/test5_mk_od/data/images/train #worked when directory was passed
val: /content/drive/MyDrive/test5_mk_od/data/images/val
```

```
names: [Book, Calculator, Mobile phone, Pencil case, Postit]
nc: 5
train: /content/drive/MyDrive/test5_mk_od/data/train.txt #not worked when txt file was passed
val: /content/drive/MyDrive/test5_mk_od/data/val.txt
```

**Comment by glenn-jocher** [comment]
@WiFiHan, great job on identifying the issue! Feel free to include this observation in your bug report. It will surely help the developers in resolving the issue promptly. If you have any further questions or need assistance with anything else, don't hesitate to ask!
