### ISSUE TITLE
How should I set up training just using another GPU hardware？Cause there is another training in another GPU hardware.  

### ISSUE THREAD

**Issue by frank60229** [ultralytics/yolov5#7945]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How should I set up training just using another GPU hardware？ Cause there is another training in another GPU hardware. 
I try to use the second GPU hardware **individually**, which the GPU id is **1**.
Here is the platform I used:
![image](https://user-images.githubusercontent.com/99239158/169937808-fe2525cc-2aa2-4f13-8990-2352d48865e2.png)

How should I set the parameters?
I tried the command which is following, but it does not work:
![image](https://user-images.githubusercontent.com/99239158/169938044-b76ed017-2369-4f43-9ff8-6ad64d30bc3a.png)
And I tried another method, but it still doesn't work:
![image](https://user-images.githubusercontent.com/99239158/169938145-724cefac-5683-4ce4-aaa7-3b206c8f5995.png)

And I try to figure it out, here are the properties for the devices:
![image](https://user-images.githubusercontent.com/99239158/169938582-120021cf-823a-49b0-9b8a-9153fa325405.png)

Are any suggestions to train a model within another GPU hardware **individually**.

**Comment by glenn-jocher** [comment]
@frank60229 I don't understand the question. You set whatever device index you want, i.e. `python train.py --device 3`
