### ISSUE TITLE
YOLOv5 custom state dict from Azure automl

### ISSUE THREAD

**Issue by RasmusLars** [ultralytics/yolov5#7949]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,

I have a custom state dict for a yolov5 model with:
- 2 classes
- model size = Medium
- Image size = 640,640
- batch size = 8
- model: yolov5 (medium), # layers: 263, # param: 21489855

The model has been generated by azure automl and has 263 layers. According to Azure, they are using a pre-trained model sourced from: /root/.cache/torch/hub/checkpoints/yolov5.3.0m-a04eea56.pth. 

I have extracted the model.pt file and now I am trying to load it using the following code: 

`model = torch.hub.load('ultralytics/yolov5', 'yolov5m', classes=2, force_reload=True, pretrained=True)
state_dict = torch.load('model_yolov_file.pt/model.pt') # custom state dict
model.load_state_dict(state_dict['model_state'])
`

I get the following error:
`RuntimeError: Error(s) in loading state_dict for AutoShape:
	Missing key(s) in state_dict: "model.model.0.conv.weight", "model.model.0.bn.weight",.........`

if I look in my custom state dict my first layer is called "0.conv.conv.weight" which is != "model.model.0.conv.weight". 

So it seems like I don't have "model.model" but I do have an extra "conv".

How can I solve this and what is going on here?

**Comment by glenn-jocher** [comment]
@RasmusLars your example is outdated, use current models and code. 

YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # yolov5n - yolov5x6 official model
#                                            'custom', 'path/to/best.pt')  # custom model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by RasmusLars** [comment]
Thanks!

I might need the rephrase my question.

How about loading a custom state dict i.e. I only have the weights for the various layers. 

So I trained my model using Azure and now I only have the state dict, nothing else.

Would that mean that in order to load my custom weight I need to:

`model = torch.hub.load('ultralytics/yolov5', 'custom', path = 'file.pt', force_reload=True) ` ? 

I tried this and it generated another error:

Exception: 'model'. Cache may be out of date, try `force_reload=True`

**Comment by glenn-jocher** [comment]
@RasmusLars that doesn't make any sense, one of my main motivations with YOLO was to abandon the concept of loading state dicts in favor of simply loading a model, i.e. yolov5s.pt is self contained with everything needed for 
```python
model = torch.load('yolov5s.pt')
```

**Comment by RasmusLars** [comment]
That makes sense, so I imagine that Azure is doing something special in the backend. Because the state dict that I get only contains the weights and not the model itself. 

If I would do:
`model = torch.load("yolov.pt") `

I would simply get an error because my file is a dict containing among other things the model state.

**Comment by glenn-jocher** [comment]
@RasmusLars if Azure if simply a hardware backend (like Colab) you should be able to just train YOLOv5 normally without using their outdated formatting (and outdated 5.x models) for YOLOv5, i.e.:

```bash
git clone https://github.com/ultralytics/yolov5
cd yolov5
pip install -r requirements.txt

python train.py ...
```
