### ISSUE TITLE
point regression

### ISSUE THREAD

**Issue by Light--** [ultralytics/yolov5#7950]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

i want to regress some points in the bbox, not only bbox and cls. May i ask how can i modify the code to do that?
how can i predict the points coordinates based on anchors?

**Comment by glenn-jocher** [comment]
@Light-- hi there! Thank you for reaching out. YOLOv5 does support point regression within the bounding boxes. You can adapt the code in the `detect.py` file to predict the point coordinates based on the anchors. You may refer to our documentation at https://docs.ultralytics.com/yolov5/ for more details on implementing point regression. If you have any specific questions while modifying the code, feel free to ask!
