### ISSUE TITLE
How to get pred box coordinates in loss.py?

### ISSUE THREAD

**Issue by HongYg** [ultralytics/yolov5#7953]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi! 
I want to get pred box coordinates in loss.py (x1,y1,y2,y2)

I'm having trouble analyzing it.
What's the solution?

thanks!

**Comment by glenn-jocher** [comment]
@HongYg box coordinates are not constructed in loss.py, only the minimum deltas (pred-truth) in gridspace are used there. The closest is this:
https://github.com/ultralytics/yolov5/blob/27911dc824b28f6d805dc88360a3313ce0c9cae5/utils/loss.py#L137-L143

**Comment by mullenba** [comment]
> @HongYg box coordinates are not constructed in loss.py, only the minimum deltas (pred-truth) in gridspace are used there. The closest is this:
> 
> https://github.com/ultralytics/yolov5/blob/27911dc824b28f6d805dc88360a3313ce0c9cae5/utils/loss.py#L137-L143

To answer the original question, you should be able to pull the values from the regression section shown above, and apply the offsets explained in section 4.3 of https://docs.ultralytics.com/yolov5/tutorials/architecture_description#44
