### ISSUE TITLE
pseudo labeling

### ISSUE THREAD

**Issue by SISTMrL** [ultralytics/yolov5#796]
## ❔Question
Do you have the plan to add pseudo labeling in this repo, thanks very much!

**Comment by glenn-jocher** [comment]
@SISTMrL see https://www.kaggle.com/nvnnghia/yolov5-pseudo-labeling

You can label any dataset you want with `test.py --save-txt` or `detect.py --save-txt`.

**Comment by ZeKunZhang1998** [comment]
> @SISTMrL see https://www.kaggle.com/nvnnghia/yolov5-pseudo-labeling
> 
> You can label any dataset you want with `test.py --save-txt` or `detect.py --save-txt`.

Is the fomat same with the label txt?

**Comment by glenn-jocher** [comment]
yes
