### ISSUE TITLE
WAND sweeps problem

### ISSUE THREAD

**Issue by yolor2** [ultralytics/yolov5#7961]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Other

### Bug

Can not see graphs and all the ap50 and different validation scores in the table while doing wandb sweeps.

### Additional

I am not able to see the graphs of all the metrics and could you please help locate the summary writer of wandb in code as in wandb there is empty space in summary. could you please help?

@wandb could you please help in finding error for ruuning sweeps in YOLOR

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by morganmcg1** [comment]
Hey @yolor2 , I work at Weights & Biases, can you provide more details and some reproducible code please?

**Comment by yolor2** [comment]
Could you please help me to add some arguments like img size, batch size etc while passing the agent  after running wandb sweep sweeps.yaml.
Like if i want to pass some arguments as shown in train.py like img size, weights etc , while doing hyper parameter optimization.
So could you please help me adding some commands in sweeps.yaml or is there any different approach.
Or could you please guide me how to successfully run the sweeps with passing arguments.
Moreover i am getting error like None type object for wandb.

**Comment by AyushExel** [comment]
@yolor2 all the default sweep configurations are in this file https://github.com/ultralytics/yolov5/blob/master/utils/loggers/wandb/sweep.yaml
Here you can change the batch size of any parameter according to your needs and all the training metrics/ configs will be tracked as usual. All the metrics that are logged for a single training job will also be logged for sweeps. 
P.S. This is only for yolov5 and not for YOLOR. YOLOR probably doesn't have this sweeps integration

**Comment by GunjanPatel1108** [comment]
Hello @AyushExel i already done sweeps integration in YOLOR.
