### ISSUE TITLE
Using the coordinates for each object

### ISSUE THREAD

**Issue by engineermechat** [ultralytics/yolov5#7964]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, i need your help on using the coordinates for my project. I trained my own custom dataset which contains 16 classes with yolov5s. It is detecting the objects almost perfectly on videos and real-time. Detecting is ok but i need to use the coordinates for
calculating the positions and distance between objects in same class or in two different classes. I used two ways to  access the coordinates.

First one is 'pred' ,when i print it on console with print(pred) i get the all coordinates of each object on the frame:
          
 tensor([[747.00000, 401.00000, 114.00000, 712.00000, 0.87, 16],
             [117.00000, 196.00000, 100.00000, 711.00000, 0.89, 15],
             [423.00000, 430.00000, 516.00000, 720.00000, 0.78, 15],
             [981.00000, 310.00000, 103.00000, 419.00000, 0.92, 15]])

Also i tried print(pred[0][0][5]) , print(pred[0][0][4]) , print(pred[0][0][0])......
They printed smoothly the correct values.

Second one is this code :
   
x1 = int(xyxy[0].item())
y1 = int(xyxy[1].item())
x2 = int(xyxy[2].item())
y2 = int(xyxy[3].item())
bbox_points=[x1, y1, x2, y2]
confidence_score = conf
class_index = cls
object_name = names[int(cls)]

print('bounding box is ', x1, y1, x2, y2)
#print('class index is ', class_index)
#print('detected object name is ', object_name)

It prints like this on the console :

bounding box is  747 401 114 712
bounding box is  117 196 100 711
bounding box is  423 430 516 720
bounding box is  981 310 103 419

Problem: I can observe the coordinates of each frame while processing but can't use it properly. I tried to filter with class numbers:

if(c==15):
print(pred)
#or my second way
But it prints the all coordinates of all detected objects not only 15 and it doesn't print when the frame has two or more 15 class objects. I want to seperate the coordinates values of each bbox to use for disered object. My project is similar with social distance projects , therefore i searched a lot on social distance projects with yolov5 to find an understandable example for my project but i couldn't find. They just explain how to calculate the distance or how to write a function but i need to parse and use the coordinates first.
 
To make my need clear, i want to give an example project.
Example: Picture a robotic arm, it detecs the 16 different types objects on a table and calculate of positions and grip them in a order which you determine in program(' first: take class 13 objects , second: take class 8 objects......')

My own project is different but i think the example points out the need, "parsing the coordinates for each object".

I am at the beginning with python so it will be perfect if you share an example on detect.py for solving my problem.
 
English is not my native language , i am sorry for my bad english.

Note: I modified detect.py file and working with it on my local computer.

**Comment by glenn-jocher** [comment]
@engineermechat 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # yolov5n - yolov5x6 official model
#                                            'custom', 'path/to/best.pt')  # custom model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by engineermechat** [comment]
Thanks for your attention glenn, it works nice and it is working without detect.py but my problem is not about handling the coordinates. My main problem is " i can't use it as i want". I want to choose, filter and take the coordinates values like any other variables. Let me give an example, I am getting the values like yours:

#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0   person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie

However i want to use only 'person' or 'tie' coordinates to calculates distance between person and tie , between Zinedine Zidane and Carlo Ancelotti , between any other objects...
I can also handle the coordinates in detect.py like i said in my first message but i dont know how to use them because of my limited knowledge on python and pytorch.

**Comment by glenn-jocher** [comment]
@engineermechat you probably want to return results in xywh format and then just take the distance between centers, i.e.
```python
distance = ((results.xywh[0][0:2] - results.xywh[1][0:2]) ** 2).sum()
```

**Comment by engineermechat** [comment]
Yes, one of my need is taking the distance, but it is not enough for me. I must indentify the coordinates for classes like distance between class 15 object and class 9 object.

**Comment by engineermechat** [comment]
I solved my problem in my way, and i am sharing the code for helping someone who have the problem like me. You can modify the example code for your need, the example shows how can you calculate the distance between bonding box of objects in same or different classes. I prepared the example for only two different classes(15th and 16th), but you can use for more, i just wanted to show the logic.



                    class_name ='xball'    # name of 16 th class
                    lx=s[1:s.find(class_name)].split()[-1] #number of 16 th class objects on the frame
                    class_name_count ='sball'  # name of 15 th class  
                    l=s[1:s.find(class_name)].split()[-1] # number of 15th class objects on the frame
                    b=np.array(pred[0]) # tensor to array
                     
                    first=(b[0]) #coordinates of 16 th class object 
                    second=(b[len(b)-2]) # coordinates of 15 th class object
                    third=(b[len(b)-1]) #coordinates of other 15 th class object
                      
                    if(c==15 and l>='2'): # if there are two 15 th class objects on the frame
                     print(third-second)  # calculate the distance between bounding boxes
                    if(c==16 and l=='2' and lx=='1'): # if there is 16 th class object and 2 15th class objects on same frame 
                     print(second-first)    # calculate the distance between second 15th and 16th
                     print(third-first)  #calculate the distance between first 15th and 16th
                     # or do something more ....

**Comment by MarGraco** [comment]
Hello @glenn-jocher, I am at the same problem of @engineermechat 
I want to measure the distance for a custom model (custom dataset too), so I write this way: 

import torch
model = '/content/yolov5/runs/train/exp4/weights/best.pt')  
im = '/content/yolov5/runs/detect/exp3/3.jpg'  
results = model(im)
results.print()  
results.xyxy[0]  
results.pandas().xyxy[0]

**The Error:**

TypeError                                 Traceback (most recent call last)
[<ipython-input-57-86e29322e7f1>](https://localhost:8080/#) in <module>()
      5 im = '/content/yolov5/runs/detect/exp3/3.jpg'
      6 
----> 7 results = model(im)
      8 
      9 results.print()

TypeError: 'str' object is not callable

**Comment by MarGraco** [comment]
I have already pre trained my model and test my dataset, so it works. But the only problem I have right now is to calculate those distances.

Best regards, guys!

**Comment by glenn-jocher** [comment]
@MarGraco 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # yolov5n - yolov5x6 official model
#                                            'custom', 'path/to/best.pt')  # custom model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by MarGraco** [comment]
Hello, thanks for the quickly answer. I look throught and I think this cannot help me, because I want to detect from my own model pretrained. There is a git repo which can I used for detect from my object and measure the distance between boxes? 

Thanks man, best regards!
