### ISSUE TITLE
What is difference between yolov5x.pt and YOLOv5x-7.pt (YOLOv5x-7-k3.pt & YOLOv5x-7-k5.pt) on the page of releases?

### ISSUE THREAD

**Issue by star4s** [ultralytics/yolov5#7967]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

What is difference between yolov5x.pt and YOLOv5x-7.pt (YOLOv5x-7-k3.pt & YOLOv5x-7-k5.pt) on the page of releases?
Could you give me information about YOLOv5x-7.pt / YOLOv5x-7-k3.pt / YOLOv5x-7-k5.pt ?

Thank you for your attention.

**Comment by glenn-jocher** [comment]
@star4s these are recent experimental models not part of the v6.1 release.
