### ISSUE TITLE
When I apply back ground image for train, how can I make annotation (label)?

### ISSUE THREAD

**Issue by star4s** [ultralytics/yolov5#7970]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When I apply back ground image for train, how can I make annotation (label)?

If I edit the label for back ground image (No object), 

The label File name: back ground image name
In the label File, there is no information, just empty?

Thank you for your help.

**Comment by glenn-jocher** [comment]
@star4s background images do not need label files, just add images to your train and val folders and they will be used as backgrounds (but of course make sure they don't contain any classes you are training on).
