### ISSUE TITLE
label-smoothing

### ISSUE THREAD

**Issue by guods** [ultralytics/yolov5#7971]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to adjust label_ Smoothing parameter？

**Comment by glenn-jocher** [comment]
@guods see train.py argparser:
https://github.com/ultralytics/yolov5/blob/1dcb77499869d64e5dea7c5bd38357c92f5eff29/train.py#L507
