### ISSUE TITLE
Process stucked at searching in the data.yaml file for labelmaps

### ISSUE THREAD

**Issue by EmiliyanGospodinov** [ultralytics/yolov5#7976]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Other

### Bug

Hi everyone, basically what I've done until now is the following: I've uploaded many images and annotated each one using roboflow, then I've exported my data in order to split it into train, validation and test parts, because I've noticed that the splitting option in roboflow does not shuffle the data in any way, that's why I've exported the dataset and made this on my pc. After that I've uploaded again only the training part because I want to apply some data-augmentation. For this purpose I've uploaded a directory that contains two folders: images(where all of my images are saved) and labels(where a .txt file with the labels in YOLO Darknet format are saved, one for each image) and one .yaml file that describes specifications like how many classes and class name, it looks like that:
names:
- stop sign
- vehicle
- yield sign
nc: 3
train: ./images 

I've tried to change the names to be saved in a list names: ['stop sign', 'vehicle', 'yield sign'] but nothing changes.
My problem is that as soon as I upload the directory where the two folders and the .yaml file are saved roboflow stucks and does not make any progress showing the whole time a message: 
"Processing files...
Searching for labelmaps in data.yaml"
I've waited for 1-2 hours and I think it would not change. 

Any suggestions how I can solve this ? 
Thank you in advance! 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Emiliyan192** [comment]
Nevermind, I solved the problem by removing the .yaml file and then changing the name of the labels such that it is the same like the image name, e.g. : image1.jpg and the corresponding label name: image1.txt. After that I can see the images and its annotations without a problem !
I'm not sure what exactly cased the problem

**Comment by yeldarby** [comment]
Hi @Emiliyan192; Roboflow does not currently support importing YOLOv5 Pytorch YAML files, only exporting. You can find our list of supported formats for import and export here so that's why your labels aren't getting mapped: https://roboflow.com/formats

We do support importing a normal Darknet [`labelmap` file](https://blog.roboflow.com/label-map/) though, which consists of a txt file with each label on one line corresponding to its label ID. So you could construct that & drop it in to re-map the labels.
