### ISSUE TITLE
objectness for non-object grid cells

### ISSUE THREAD

**Issue by AlexofNTU** [ultralytics/yolov5#7978]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I recently tried to modify the loss function YOLOv5.
Based on my previous experiences on other YOLO detectors, I assumed there should be a loss term for non-object grid cells.
However, after carefully going through ComputeLoss() in loss.py, I can only find the objectness loss for object grid cells.
Was I missing something?

**Comment by glenn-jocher** [comment]
@AlexofNTU objectness loss applies to all grid cells regardless of what they contain.
