### ISSUE TITLE
Option to view performance on validation / test set while training>

### ISSUE THREAD

**Issue by theahmedmustafa** [ultralytics/yolov5#7979]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

The current setup only allows for saving the _test_batch0_pred_ results after all the epochs are complete. I could not find any option to save these results after a specific set of epochs to evaluate the performance of the model over time more visually.

Kindly add this option for ease of usage.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@theahmedmustafa thank you for your feedback!
