### ISSUE TITLE
loss is nan

### ISSUE THREAD

**Issue by mcmingchang** [ultralytics/yolov5#798]
![results](https://user-images.githubusercontent.com/37234299/90748382-b5576780-e304-11ea-8fa2-fdf0d837eefa.png)
## ❔Question

i only changed adam to adamw

**Comment by mcmingchang** [comment]
multi-scale  train

**Comment by glenn-jocher** [comment]
@mcmingchang if you made a change to the optimizer, and now you have nan loss, then the cause should be clear.

**Comment by glenn-jocher** [comment]
BTW your dataset shows no validation images, you should verify your paths etc.
