### ISSUE TITLE
PseudoLabeling in YoloV5

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#7980]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have worked on the model with 600 images, and when I start to run it with similar images but in different environments, it takes several objects as the object to point to.

I have executed it with the --save-txt option, and I wanted to know how I can retrain the already trained model by passing these images with the appropriate bounding boxes.

What would be the procedure for once the images and their txt with the labels have been obtained, tell them which are correct and which are not, and retrain the model?
Is there a way to tell it that what it has detected as the wanted object is actually wrong and it isn't?
Any way to do active learning?

**Comment by glenn-jocher** [comment]
@gineszamorac you clean up the labels to remove false positives and then simply add your new data to your old dataset and retrain. The best way to clean up the autolabels is a good question though. Perhaps you could start by uploading to roboflow and then correcting the annotations.

**Comment by ghost** [comment]
@glenn-jocher yes, but how can I retrain my model? 

Or it's necessary lunch the yolo again with the new labels and images?

**Comment by glenn-jocher** [comment]
@gineszamorac you retrain with `python train.py ...`

**Comment by ghost** [comment]
@glenn-jocher I know, but with that I retrain the model from scratch, with the hours that it took me, the idea is to know if I can add those images with their labels somehow without having to retrain it with all the others.

**Comment by glenn-jocher** [comment]
@gineszamorac Yes, you can resume training from where you left off using the `--resume` flag with `python train.py --resume ...`. This will start training from your last checkpoint and continue with the new images and labels added.
