### ISSUE TITLE
tp parameter in ap_per_class function

### ISSUE THREAD

**Issue by karl-gardner** [ultralytics/yolov5#7984]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello Glenn,

I have read through the code for the ap_per_class function multiple times and still cannot figure out what the dimensions of the tp parameter mean. You say: "tp:  True positives (nparray, nx1 or nx10)." I am assuming n is the number of true positive predictions and do not know what the column dimension 1 or 10 means.

Thanks,

Karl

**Comment by Pabligme** [comment]
The first row is the first prediction evaluated on IoU function with iou threshold [0.5, 0.55, 0.6, 0.65, .... , 0.9, 0.95] (10 different thresholds).

The first row and other rows of TP are ten boolean values.

**Comment by glenn-jocher** [comment]
@Pabligme hello Karl,

The tp parameter in the ap_per_class function represents true positives for each threshold. Each row of the tp nparray contains ten boolean values, with each value corresponding to a specific IoU threshold from 0.5 to 0.95. This allows for the evaluation of true positive predictions across different IoU thresholds.

Hope this clarifies things for you! If you have any more questions, feel free to ask.
