### ISSUE TITLE
Abnormal exit during training

### ISSUE THREAD

**Issue by bingo789** [ultralytics/yolov5#7986]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

it quit when i run train.py in pycharm
<img width="974" alt="截屏2022-05-26 下午2 54 33" src="https://user-images.githubusercontent.com/40812718/170434865-497f7335-f07d-4409-a277-9a28f158c34c.png">

I found it quit in here:
utils/loggers/__init__.py:75   ==> self.tb = SummaryWriter(str(s))

How to solve this problem？

### Environment

- YOLOv5 🚀 v6.1-204-gf43cd53 Python-3.7.11 torch-1.8.0 CPU
- os: macos bigsur (apple m1)
- python:3.7.11

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@bingo789 it appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual [Python 3.9](https://www.python.org/) environment, clone the latest repo ([code changes daily](https://github.com/ultralytics/yolov5/commits/master)), and `pip install` [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) again from scratch.

💡 ProTip! Try one of our verified environments below if you are having trouble with your local environment.


## Requirements

[**Python>=3.7.0**](https://www.python.org/) with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) installed including [**PyTorch>=1.7**](https://pytorch.org/get-started/locally/). To get started:
```bash
git clone https://github.com/ultralytics/yolov5  # clone
cd yolov5
pip install -r requirements.txt  # install
```

[Models](https://github.com/ultralytics/yolov5/tree/master/models) and [datasets](https://github.com/ultralytics/yolov5/tree/master/data) download automatically from the latest YOLOv5 [release](https://github.com/ultralytics/yolov5/releases) when first requested.

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), validation ([val.py](https://github.com/ultralytics/yolov5/blob/master/val.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/export.py)) on MacOS, Windows, and Ubuntu every 24 hours and on every commit.

**Comment by bingo789** [comment]
@glenn-jocher i have run `pip install requirements.txt`, and idea does not prompt errors, I think the package(torch.utils.tensorboard) may be incompatible with my system(apple m1), so i try to run below code in another py file, the same error occurred

```
from torch.utils.tensorboard import SummaryWriter

writer = SummaryWriter('runs/train/exp')
```

**Comment by glenn-jocher** [comment]
@bingo789 It's possible that the `torch.utils.tensorboard` package may be incompatible with your system architecture. The issue might be related to running YOLOv5 in the Apple M1 environment. You could consider utilizing a different machine with a different architecture for running YOLOv5 or reaching out to the PyTorch community for Apple M1 support.

To further investigate and resolve this issue, I recommend posting on the [PyTorch forums](https://discuss.pytorch.org/) or reaching out to their [GitHub repository](https://github.com/pytorch/pytorch) for assistance. They may have more specialized knowledge about compatibility with Apple M1.

I apologize for any inconvenience and appreciate your understanding and patience while the issue is being addressed.
