### ISSUE TITLE
Why can't the map@.5:map@.95 I trained from scratch reach the given 37.4%?

### ISSUE THREAD

**Issue by myylo** [ultralytics/yolov5#7988]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Training MSCOCO from scratch for 300 epoch map@.0.5 can reach 57%, map@.5:map@.95 can only reach 36.8%, is this a normal range?

**Comment by glenn-jocher** [comment]
@myylo the last bit of difference is probably due to segment labels that are not downloaded by default. You can uncomment them here and autodownload COCO again with segment labels for improved augmentation results:
https://github.com/ultralytics/yolov5/blob/1dcb77499869d64e5dea7c5bd38357c92f5eff29/data/scripts/get_coco.sh#L13

**Comment by myylo** [comment]
Thank you for your reply, but the download segment labels link you provided is invalid. Is it convenient to send another valid download link? Thank you very much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ultralytics/yolov5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月26日(星期四) 晚上6:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ultralytics/yolov5] Why can't the ***@***.******@***.*** I trained from scratch reach the given 37.4%? (Issue #7988)





 
@myylo the last bit of difference is probably due to segment labels that are not downloaded by default. You can uncomment them here and autodownload COCO again with segment labels for improved augmentation results:
 https://github.com/ultralytics/yolov5/blob/1dcb77499869d64e5dea7c5bd38357c92f5eff29/data/scripts/get_coco.sh#L13

**Comment by glenn-jocher** [comment]
I didn't send a link, you set f = the commented part and let COCO autodownload

**Comment by myylo** [comment]
Yes, I want to download automatically from get_coco.sh, but the path of the download segment label in the code is invalid. url=https://github.com/ultralytics/yolov5/releases/download/v1.0/ is invalid




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ultralytics/yolov5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月26日(星期四) 晚上8:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ultralytics/yolov5] Why can't the ***@***.******@***.*** I trained from scratch reach the given 37.4%? (Issue #7988)





 
I didn't send a link, you set f = the commented part and let COCO autodownload

**Comment by glenn-jocher** [comment]
I already explained how to do this in https://github.com/ultralytics/yolov5/issues/7988#issuecomment-1138519218

URL is concatenated

**Comment by myylo** [comment]
Thanks for your reply, I will try it.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ultralytics/yolov5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月26日(星期四) 晚上9:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ultralytics/yolov5] Why can't the ***@***.******@***.*** I trained from scratch reach the given 37.4%? (Issue #7988)





 
I already explained how to do this in #7988 (comment)
 
URL is concatenated

**Comment by myylo** [comment]
Excuse me, after using segment labels, coco ***@***.*** reach 57.2%, but ***@***.******@***.*** can only reach 37% and still can’t reach 57.4%. I haven’t found the reason for the error, and I look forward to your reply.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ultralytics/yolov5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月26日(星期四) 晚上6:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ultralytics/yolov5] Why can't the ***@***.******@***.*** I trained from scratch reach the given 37.4%? (Issue #7988)





 
@myylo the last bit of difference is probably due to segment labels that are not downloaded by default. You can uncomment them here and autodownload COCO again with segment labels for improved augmentation results:
 https://github.com/ultralytics/yolov5/blob/1dcb77499869d64e5dea7c5bd38357c92f5eff29/data/scripts/get_coco.sh#L13

**Comment by glenn-jocher** [comment]
@myylo I don't understand your question, can you explain and provide supporting results?

**Comment by myylo** [comment]
Thank you for your reply,&nbsp;I use autodownload COCO with segment labels to improve augmentation results.

 

Training MSCOCO from scratch for 300 epoch ***@***.*** can reach 57.2%, ***@***.******@***.*** can only reach 37%,The training result.csv is in the attachment.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ultralytics/yolov5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月12日(星期二) 晚上7:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ultralytics/yolov5] Why can't the ***@***.******@***.*** I trained from scratch reach the given 37.4%? (Issue #7988)





 
@myylo I don't understand your question, can you explain and provide supporting results?

**Comment by glenn-jocher** [comment]
@myylo ok got it. Do you have the commands you used to produce your results?

**Comment by myylo** [comment]
&nbsp;Use the command ' time python train.py --img 640 --batch 64 --epochs 300 --data ./data/coco.yaml --cfg ./models/yolov5s.yaml --device="0,1" ' to train





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ultralytics/yolov5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月12日(星期二) 晚上7:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ultralytics/yolov5] Why can't the ***@***.******@***.*** I trained from scratch reach the given 37.4%? (Issue #7988)





 
@myylo ok got it. Do you have the commands you used to produce your results?

**Comment by glenn-jocher** [comment]
@myylo I recently started two YOLOv5s trainings, one with COCO-box and one with COCO-segments, and it looks like segments is actually underperforming. There may be a bug as it should outperform a bit. Current results here (not done training segments):

<img width="1217" alt="Screen Shot 2022-07-12 at 4 31 28 PM" src="https://user-images.githubusercontent.com/26833433/178515044-a87c7e41-83dd-423f-8a2d-98b2905b0409.png">

@AyushExel FYI

**Comment by AyushExel** [comment]
@glenn-jocher Do you have a guess what exactly the problem could be -- the labels or the segment augmentations?

**Comment by glenn-jocher** [comment]
@AyushExel I don't know. Let's wait for the result but it might be a recent augmentations labels PR I merged a month or so ago.

**Comment by myylo** [comment]
Thanks for your reply, I will try training again.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ultralytics/yolov5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月12日(星期二) 晚上10:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ultralytics/yolov5] Why can't the ***@***.******@***.*** I trained from scratch reach the given 37.4%? (Issue #7988)





 
@myylo I recently started two YOLOv5s trainings, one with COCO-box and one with COCO-segments, and it looks like segments is actually underperforming. There may be a bug as it should outperform a bit. Current results here (not done training segments):
 

 
@AyushExel FYI
