### ISSUE TITLE
how to using vision transformer in yolov5?

### ISSUE THREAD

**Issue by Dang-Tu-lang** [ultralytics/yolov5#7989]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

i have the image and small object, i want to use vision transformer for training the image. how to use vision transformer in yolov5 ?

**Comment by glenn-jocher** [comment]
@dangyuuki123 
```
python train.py --cfg yolov5s-transformer.yaml
```

**Comment by isJunCheng** [comment]
> @dangyuuki123
> 
> ```
> python train.py --cfg yolov5s-transformer.yaml
> ```

Now, before inputting the model, it is more and more popular to use normalizer. Why yolov5 not use it yet？

**Comment by glenn-jocher** [comment]
@isJunCheng hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by Dang-Tu-lang** [comment]
@glenn-jocher  thank you to answer my question.

**Comment by mx2013713828** [comment]
> @glenn-jocher thank you to answer my question.

Hi, can you advice some normalizer before input?I am very interested in this aspect.
thanks!

**Comment by glenn-jocher** [comment]
@mx2013713828 sure, you can normalize inputs if you want. You could do this in the dataloader or in the model itself, but you have to remember to deploy with the same preprocessing whatever you do.

**Comment by mx2013713828** [comment]
> @mx2013713828 sure, you can normalize inputs if you want. You could do this in the dataloader or in the model itself, but you have to remember to deploy with the same preprocessing whatever you do.

Thanks for your reply.I really learned a lot from yolov5 even though I didn't know deeplearning before.
