### ISSUE TITLE
What is the location of the saved model architecture  for inference

### ISSUE THREAD

**Issue by vkramdev** [ultralytics/yolov5#799]
## ❔Question
Where can i find the location or directory in which the model is saved .

## Additional context
I can find from the documentation the weights of the trained model being saved in yolov5/runs/your_experiment/weights. I need to know the location for saved the model architecture.

**Comment by vkramdev** [comment]
I can find the model config in /models. I want to look in the code where it is being saved.

**Comment by glenn-jocher** [comment]
@vkramdev all training data is saved to runs/exp.
