### ISSUE TITLE
delete gather in onnx

### ISSUE THREAD

**Issue by cena001plus** [ultralytics/yolov5#7990]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

After the trained yolov5m model generates the pt model, the onnx model is generated through export.py, but I found that there is an extra gather module in the output header, and this part did not exist before. I want to know how to remove this module. In addition, it How is it generated?
![gather](https://user-images.githubusercontent.com/37894345/170467371-b0009e17-c03d-4968-b901-4b25e1dcb7d2.png)

**Comment by glenn-jocher** [comment]
Your export is either incorrect or out of date. 

![image](https://user-images.githubusercontent.com/26833433/170471607-0b044059-a26d-4b6b-aa29-07e103235c4c.png)

**Comment by cena001plus** [comment]
> Your export is either incorrect or out of date.
> 
> ![image](https://user-images.githubusercontent.com/26833433/170471607-0b044059-a26d-4b6b-aa29-07e103235c4c.png)

Just cloned the latest code, export should also be the latest, import the pt model and use the command

`python export.py --weights /runs/tarain/exp/weights/best.py --include onnx`

But the problem still exists

**Comment by glenn-jocher** [comment]
@cena001plus then your model is out of date.

**Comment by cena001plus** [comment]
> @cena001plus then your model is out of date.
Thank you very much for your answer. I successfully converted in a virtual environment for testing, but I still can't solve the problem in another virtual environment for training, the exact same engineering code, and finally compared the two conda environments It is found that there are differences. The touch version in the training environment is modified from 1.8.1 to 1.10.1, and the touchvision is modified from 0.9.1 to 0.11.2, and the problem is solved.
