### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'python_exit_status'

### ISSUE THREAD

**Issue by claudio9russo7** [ultralytics/yolov5#7995]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

I did a training, it went well, but in the end it gives me this error. I don't think it impacts the training
![Yolov5_Error](https://user-images.githubusercontent.com/99536010/170523431-891a28dd-30b9-46f9-9bcb-e2c1e88cc627.png)

### Environment

YOLOv5 🚀 v6.1-224-g9455796 Python-3.7.12 torch-1.9.1 CUDA:0 (Tesla P100-PCIE-16GB, 16281MiB)
Kaggle

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@claudio9russo7 this is probably known PyTorch issue that you can ignore. See https://github.com/pytorch/pytorch/issues/74016 for similar.

Duplicate of https://github.com/ultralytics/yolov5/issues/7995, https://github.com/ultralytics/yolov5/issues/6133, https://github.com/ultralytics/yolov5/issues/5913, https://github.com/ultralytics/yolov5/issues/5762

**Comment by claudio9russo7** [comment]
@glenn-jocher Thanks a lot.

**Comment by glenn-jocher** [comment]
@claudio9russo7 you're welcome! If you have any more questions or run into any other issues, feel free to ask. Thank you for using YOLOv5!
