### ISSUE TITLE
training actually can not work

### ISSUE THREAD

**Issue by lucasjinreal** [ultralytics/yolov5#8]
After trained on several epochs, I found the mAP is still very low. Does the training really works?

```
    Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
    14/299      6.4G   0.02273  0.002925 0.0003764   0.02603        11       640: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6960/6960 [54:20<00:00,  2.13it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6960/6960 [13:37<00:00,  8.51it/s]
                 all    5.57e+04    1.74e+05    0.000332     0.00039     2.4e-06    8.59e-07

     Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
    15/299      6.4G   0.02232  0.002874  0.000371   0.02556         7       640: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6960/6960 [54:36<00:00,  2.12it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6960/6960 [14:23<00:00,  8.06it/s]
                 all    5.57e+04    1.74e+05    0.000342    0.000401    2.44e-06    8.66e-07

```

**Comment by glenn-jocher** [comment]
@jinfagang training operates correctly. See https://github.com/ultralytics/yolov5#reproduce-our-training

**Comment by lucasjinreal** [comment]
@glenn-jocher  Why am I training so low AP

**Comment by glenn-jocher** [comment]
@jinfagang we've completed writing a custom data training tutorial here that may help. Make sure you check your labels by looking at train*.jpg after training starts.
https://docs.ultralytics.com/yolov5/tutorials/train_custom_data

**Comment by tangxiaochu123230** [comment]
could you find the problem,I have a similar situation

**Comment by annie7777** [comment]
had similar problem and just found that I forgot to change the number of class in yolov5s.yaml when following the tutoiral.
https://github.com/ultralytics/yolov5/blob/bf6f41567ae4e2953bca7a7042d8ae78db82a3bc/models/yolov5s.yaml#L2

**Comment by glenn-jocher** [comment]
@annie7777 thanks for the comment! Recent updates have actually removed this requirement. Class counts for training are now inherited from the dataset.yaml `nc` in case of a difference. 

The code changes often, so if anyone runs into a similar bug `git pull` to update your code to simply clone a fresh copy of the repo!
