### ISSUE TITLE
NO

### ISSUE THREAD

**Issue by zhouhing** [ultralytics/yolov5#80]
class Focus(nn.Module):
    # Focus wh information into c-space
    def __init__(self, c1, c2, k=1):
        super(Focus, self).__init__()
        self.conv = Conv(c1 * 4, c2, k, 1)

    def forward(self, x):  # x(b,c,w,h) -> y(b,4c,w/2,h/2)
        return self.conv(torch.cat([x[..., ::2, ::2], x[..., 1::2, ::2], x[..., ::2, 1::2], x[..., 1::2, 1::2]], 1))
请问这个Focus对输入的W和H进行压缩，不会破坏原来的空间特征吗？

**Comment by Libaishun** [comment]
@zhouhing I think the Focus op is just a rearrangement of features, doesnot destroy any information

**Comment by zhouhing** [comment]
> @zhouhing I think the Focus op is just a rearrangement of features, doesnot destroy any information

谢谢您的回答，还有一个问题，请问，为什么需要这么压缩呢，增加通道，减少H*W，这种操作是为加强特征吗？，这和用1*1卷积+下采样进行压缩的区别大吗？

**Comment by Libaishun** [comment]
@zhouhing 不是“压缩”，是focus，这样做既不减弱也不加强特征，直接下采样才损失特征，你可以把conv 3X3, stride2 和 focus + conv 3X3, stride=1比较下， 我猜可能是在不下采样的情况下达到同样增大感受野的效果，这样计算量是否也会节省很多需要具体算下。不过这只是我的理解，不一定对，我其实也挺奇怪这种操作的。可以@下作者求正确解释

**Comment by Libaishun** [comment]
@glenn-jocher Hi, I'm also wonder what's the benefits of the focus module compare to ordinary downsample module as conv 3X3, stride=2, just for saving computation? or can be viewed as a new type of pool: focus pool?

**Comment by wwdok** [comment]
其他国家的人都没用自家语言在github上提问，就中国人这么做。。。

**Comment by zhouhing** [comment]
> 其他国家的人都没用自家语言在github上提问，就中国人这么做。。。

优越感这么高的老哥，这种引战的言论就别发出来了，别破坏这里的学习交流氛围。

**Comment by wwdok** [comment]
> > 其他国家的人都没用自家语言在github上提问，就中国人这么做。。。
> 
> 优越感这么高的老哥，这种引战的言论就别发出来了，别破坏这里的学习交流氛围。

你哪里看出我的优越感了，我觉得你才有优越感，你想着外国人看懂你的中文来给你回答？我没有想引战，这个词你自己提出的，我觉得是你想引战。我也没有想破坏学习交流氛围，倒觉得是你在破坏学习交流氛围，世界各国的人在这里都用英语交流，yolov5作者是西班牙人用英语在交流，yolov4作者俄罗斯人也用英语在交流。我发表评论只是觉得你不太礼貌。

**Comment by zhouhing** [comment]
> > > 其他国家的人都没用自家语言在github上提问，就中国人这么做。。。
> > 
> > 
> > 优越感这么高的老哥，这种引战的言论就别发出来了，别破坏这里的学习交流氛围。
> 
> 你哪里看出我的优越感了，我觉得你才有优越感，你想着外国人看懂你的中文来给你回答？我没有想引战，这个词你自己提出的，我觉得是你想引战。我也没有想破坏学习交流氛围，倒觉得是你在破坏学习交流氛围，世界各国的人在这里都用英语交流，yolov5作者是西班牙人用英语在交流，yolov4作者俄罗斯人也用英语在交流。我发表评论只是觉得你不太礼貌。（我在本贴的评论十分钟后删除）

goodboy
