### ISSUE TITLE
Question about prob of mosaic?

### ISSUE THREAD

**Issue by sky-fly97** [ultralytics/yolov5#800]
Hello, I have a question. Why is mosaic **always used in training,**  instead of **setting a probability** to use it like the **usual online  augmentation**? Would it be better?

**Comment by glenn-jocher** [comment]
@sky-fly97 that is a good question. We treat mixup in this way, passing a simple probability for it, but you are right, not mosaic. 

Mosaic could be treated the same way, but it is a bit unique in that it benefits from a larger square shaped 'window', so without mosaic training will progress much faster with rectangular windows, i.e. using --rect.

We could dissociate mosaic from the window shape though, and add it to the hyps as a probability term. I don't know if the dataloader is robust to rectangular mosaic though right now, it might need a few tweaks.

**Comment by sky-fly97** [comment]
> @sky-fly97 that is a good question. We treat mixup in this way, passing a simple probability for it, but you are right, not mosaic.
> 
> Mosaic could be treated the same way, but it is a bit unique in that it benefits from a larger square shaped 'window', so without mosaic training will progress much faster with rectangular windows, i.e. using --rect.
> 
> We could dissociate mosaic from the window shape though, and add it to the hyps as a probability term. I don't know if the dataloader is robust to rectangular mosaic though right now, it might need a few tweaks.

Yes, I've also considered rectangular mosaic instead of square mosaic before, and I keep the aspect ratio of these images, like this. But it feels like it wastes too much image space
![image](https://user-images.githubusercontent.com/55578436/90853663-58fc5280-e3ad-11ea-94a9-62ae93e9129a.png)

**Comment by ZeKunZhang1998** [comment]
复赛

**Comment by sky-fly97** [comment]
Maybe it's better to change the background to white！
![image](https://user-images.githubusercontent.com/55578436/90891529-6f76ce00-e3ee-11ea-915b-41bf97960843.png)

**Comment by sky-fly97** [comment]
> 复赛

是的，小白正在学习~

**Comment by glenn-jocher** [comment]
@sky-fly97 background should be your dataset mean. We use imagenet mean, update as appropriate for your situation.

**Comment by ZeKunZhang1998** [comment]
> > 复赛
> 
> 是的，小白正在学习~

tql
