### ISSUE TITLE
Background fn

### ISSUE THREAD

**Issue by adelchellabi** [ultralytics/yolov5#8000]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello 
  I don't understand what is background fn and background fp in confusion matrix  (in the last row )
Please can you explain to me the meaning of this two things  and thank you 😊 
![IMG-20220417-WA0048](https://user-images.githubusercontent.com/40125292/170561635-c68471ab-3801-4ee1-94c5-de00733593d1.jpg)

**Comment by glenn-jocher** [comment]
@adelchellabi these are no different than TPs and FPs for any other class in the matrix.

**Comment by hotohoto** [comment]
@glenn-jocher 

So, you're saying background is another class? Then I believe the codes here are correct.

https://github.com/ultralytics/yolov5/blob/v6.2/utils/metrics.py#L171-L176

For each ground truth label, if there is no match, the model **predicted it as background**, so it's **a false positive**.

For each detection class, if there is no object hit, the model predicted it as non-background, so it's a false negative. 

However, the visualization seems wrong.

![image](https://user-images.githubusercontent.com/5404902/185517508-85ea87f9-d3e5-4f51-ad2e-ef46c16cd15d.png)

**Comment by glenn-jocher** [comment]
@hotohoto True object (column) predicted as background (last row) is a FN, so labels are correct.

**Comment by hotohoto** [comment]
@glenn-jocher
Isn't line 171 for the same case when True object `gc` is predicted as background? But the comment at the line says "background FP". As far as I understand the case will be visualized in the bottom row. So I feel like something is wrong. Then do you think the comments in lines 171 (and 176) should be fixed?

But if we say the background is a class, then we might be able to say the model predicted the area as positive as for the background class, then we would call it False Positive like the comment says.

Anyway, if I understand the code correctly, there seems to be a conflict between the comment and the visualization. Still, it's possible I misunderstood the code though. 🤔

**Comment by glenn-jocher** [comment]
@hotohoto hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
