### ISSUE TITLE
Model Inference speed for reporting

### ISSUE THREAD

**Issue by Elizbellou** [ultralytics/yolov5#8003]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, which time do we report as detection speed? 
Either for val.py or for detect.py. Inference time alone or we sum up pre process MS, inference MS and nms per image MS? In the image example do I report 87.5 MS or 96,7 MS? 
![IMG_20220527_093056](https://user-images.githubusercontent.com/80814107/170643906-ca671005-319b-4235-b606-a0d21923832b.jpg)

**Comment by glenn-jocher** [comment]
@Elizbellou you report whatever meets your reporting requirements

**Comment by Elizbellou** [comment]
Of course I do. Maybe I placed the question in a wrong way. What is the inference time of this model in the pic? But I figured it out. Thank u

**Comment by glenn-jocher** [comment]
@Elizbellou you're welcome! If you have any more questions or need further assistance in the future, feel free to ask. Good luck with your work!

**Comment by Elizbellou** [comment]
@glenn-jocher Thanks a lot, it went good actually, and worked real-time on a quadcopter with Jetson nano onboard. If you have some time you can see our results in our recently published conference paper. It is thanks to your work, you unlocked real-time object detection into the real world applications! I have also worked on yolov8 which went better in terms of accuracy. I will keep you updated 
👇
Bellou, E., Pisica, I., & Banitsas, K. (2023, August). Real-time object detection on high-voltage powerlines using an Unmanned Aerial Vehicle (UAV). In 2023 58th International Universities Power Engineering Conference (UPEC) (pp. 1-6). IEEE.

**Comment by glenn-jocher** [comment]
That sounds fantastic, @Elizbellou! I'm thrilled to hear that YOLOv5 has been so impactful for your project. Your conference paper on real-time object detection using UAVs sounds incredibly interesting. Keep up the great work, and I'm looking forward to seeing your updates. Good luck with your future research endeavors!
