### ISSUE TITLE
finding out the distance using zed 2i

### ISSUE THREAD

**Issue by Yousef-Alhattab** [ultralytics/yolov5#8007]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

where the distance is been calculating [here](https://github.com/stereolabs/zed-examples/blob/master/object%20detection/custom%20detector/python/pytorch_yolov5/detector.py), please?
and how to print it out in terminal 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@urbansound8K questions regarding 3rd party tools are best directed to their authors.
