### ISSUE TITLE
Solution to a minor issue

### ISSUE THREAD

**Issue by ghavidelsahar** [ultralytics/yolov5#801]
Hello,

I had the same issue which stems from bool * float
Simply change it to: **weights = iou.float() * scores[None]** 

Thanks for the great repo. 

https://github.com/ultralytics/yolov5/blob/fb4fc8cd0215443696a75dffbf56351266ccdfb0/utils/general.py#L662

**Comment by glenn-jocher** [comment]
@ghavidelsahar thanks for raising this issue! Can you provide some steps to reproduce this? 

This may be a function of your python and pytorch versions also. Can you verify you are using 3.7 or higher and torch 1.6?

**Comment by ghavidelsahar** [comment]
I wanted to evaluate the effect of merge on performance while the confidence threshold is higher that 0.001. However, it raised the exception. In my case the issue was dtype not cuda. 

You are right it might be related to version difference as I am using 3.6 and 1.4.

**Comment by glenn-jocher** [comment]
@ghavidelsahar can you try to reproduce this in 3.7 or 3.8 with torch 1.6? If you see the error there then yes we can get started on updating the code. Thanks!

You can do this most easily with the colab notebook <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>

**Comment by ghavidelsahar** [comment]
I used colab and passed merge=true to non_max_suppression, and everything works fine. It was my mistake :) 
I am closing the issue then.

**Comment by glenn-jocher** [comment]
@ghavidelsahar ok got it, thanks for confirming!
