### ISSUE TITLE
Cant start training: TypeError: Descriptors cannot not be created directly.

### ISSUE THREAD

**Issue by UnglvKitDe** [ultralytics/yolov5#8012]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Hi,
first of all: Thx for your great work! This repo looks really interesting. But unfortunately I can not start the training.
I use RedHat 4 with conda. I created the conda env and then installed the packages with pip install -r requirements.txt. 
`python3 train.py --img 640 --batch 16 --data coco128.yaml --weights yolov5m6.pt`
```
Traceback (most recent call last):
  File "train.py", line 52, in <module>
    from utils.loggers import Loggers
  File "[...]/yolov5/utils/loggers/__init__.py", line 11, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "[...]/yolov5/lib/python3.8/site-packages/torch/utils/tensorboard/__init__.py", line 10, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "[...]/yolov5/lib/python3.8/site-packages/torch/utils/tensorboard/writer.py", line 9, in <module>
    from tensorboard.compat.proto.event_pb2 import SessionLog
  File "[...]/yolov5/lib/python3.8/site-packages/tensorboard/compat/proto/event_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import summary_pb2 as tensorboard_dot_compat_dot_proto_dot_summary__pb2
  File "[...]/yolov5/lib/python3.8/site-packages/tensorboard/compat/proto/summary_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import tensor_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__pb2
  File "[...]/yolov5/lib/python3.8/site-packages/tensorboard/compat/proto/tensor_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import resource_handle_pb2 as tensorboard_dot_compat_dot_proto_dot_resource__handle__pb2
  File "[...]/yolov5/lib/python3.8/site-packages/tensorboard/compat/proto/resource_handle_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import tensor_shape_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__shape__pb2
  File "[...]/yolov5/lib/python3.8/site-packages/tensorboard/compat/proto/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "[...]/yolov5/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

```

### Environment

YOLOv5 + pytorch 1.11 cuda 11.6
OS: Red Hat 4
python 3.8

### Minimal Reproducible Example

`python3 train.py --img 640 --batch 16 --data coco128.yaml --weights yolov5m6.pt`

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by jcluo1994** [comment]
hello, thanks for great work.but, i try to train my code,there some error is coming,
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
the env is following the repo.pip -r install requirment.txt

**Comment by ar2di2-75** [comment]
Hi, i have same problem like [yichanshiwoa]. Detection is working but train not.

I'am using Windows 10.
YOLOv5  2022-5-27 Python-3.10.4 torch-1.11.0+cu113 CUDA:0 (NVIDIA RTX A5000, 24563MiB)

Same error when start 
 !cd yolov5 && python train.py --img 640 --batch 16 --epochs 5 --data dataset.yml --weights yolov5s.pt   
or 
!cd yolov5 && python train.py  (i want to show me other error but always the same error)
------
Traceback (most recent call last):
  File "train.py", line 52, in <module>
    from utils.loggers import Loggers
  File "__init__.py", line 11, in <module>
    from torch.utils.tensorboard import SummaryWriter

ypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

**Comment by glenn-jocher** [comment]
@UnglvKitDe @ar2di2-75 @yichanshiwoa good news 😃! Your original issue may now be fixed ✅ in PR #8017. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by ar2di2-75** [comment]
Thanks @glenn-jocher, now is working.

**Comment by jcluo1994** [comment]
i have solve this problem by using following way:
pip uninstall protobuf
pip install protobuf==3.20.1

**Comment by jcluo1994** [comment]
> Thanks @glenn-jocher, now is working.

pip uninstall protobuf
pip install protobuf==3.20.1
 the way can work.

**Comment by kwassholm** [comment]
Seems like this is broken again due to the dependabot updating protobuf's version in https://github.com/ultralytics/yolov5/pull/8346

**Comment by glenn-jocher** [comment]
@kwassholm thanks for confirming, I was wondering about this. Looks like we need to revert the dependabot PR #8346

**Comment by DonaldMOUAFO** [comment]
Thanks @glenn-jocher,
I work on Ubuntu 20.04.4 LTS Oracle virtual machine, and i got the same issue as @UnglvKitDe

pip uninstall protobuf
pip install protobuf==3.20.1

Everything work well

**Comment by glenn-jocher** [comment]
@kwassholm @The-Quantum good news 😃! Your original issue may now be fixed ✅ in PR #8741. This update reverts dependabot changes and sets protobuf<=3.20.1 in requirements.txt.

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by vishwakaria** [comment]
I am still running into this issue even with protobuf version 3.20.1.

Verified that I have the latest code pulled from the repo.

**Comment by glenn-jocher** [comment]
@vishwakaria can you send us your `pip list` output? You can always use our Docker image also to train in a verified environment while utilizing local hardware.

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>
