### ISSUE TITLE
what is needed to modify in yolov5 code to get detection results when rtsp link of ipcamera is used?

### ISSUE THREAD

**Issue by afrahthahir** [ultralytics/yolov5#8013]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

https://user-images.githubusercontent.com/55926806/170809006-99b54440-857a-4da3-842d-815550ccfed8.png

### Additional

Does yolov5 support rtsp link from a live cctv feed? Please let me know.

**Comment by glenn-jocher** [comment]
@afrahthahir Usage instructions for RTSP are displayed in README.

**Comment by sumis2140** [comment]
> @afrahthahir  Did you get any answers or ideas I have the same issue can you please help me to resolve this issue 

Thanks
