### ISSUE TITLE
How to use best.pt weight for inferencing without downloading it from Pytorch Hub? 

### ISSUE THREAD

**Issue by duttashi** [ultralytics/yolov5#8018]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I trained model on custom dataset. I'm unable to determine how to use `best.pt` without downloading it through PyTorch Hub.
I followed this [issue](https://github.com/ultralytics/yolov5/issues/36) and it recommends the PyTorch Hub route as,

`custom_model = torch.hub.load('ultralytics/yolov5', 'custom', path = model_path, force_reload=True)`

I do not want to use `torch.hub.load()` because for my use-case **inferencing time is a critical component**. I've noticed, often using the `torch.hub.load()` method either takes more than a minute to execute or it simply throws some random connectivity error.

**Comment by glenn-jocher** [comment]
@duttashi PyTorch Hub inference speed is the same as any other endpoint we expose, i.e. detect.py and val.py.

<img width="1155" alt="Screenshot 2022-05-30 at 10 50 27" src="https://user-images.githubusercontent.com/26833433/170955261-1be0728d-c155-4fb1-a3c8-981652fdb876.png">

**Comment by duttashi** [comment]
@glenn-jocher many thanks for taking the time to provide a response. As your the principal developer of this project, I'll take your word for it. However, for the sake of a discussion, please advise how may I use `best.pt` in `detect.py` and/or `val.py` and execute it from a python script.

**Comment by glenn-jocher** [comment]
@duttashi you can use the `--weights` argument in `detect.py` and `val.py` to specify a `.pt` file for the YOLO model. For executing it from a Python script, you can use the `torch.load` function to load the weights and then directly pass it to the YOLOv5 model. Refer to the Ultralytics Docs for more details on using custom weights in YOLOv5.
