### ISSUE TITLE
build targets function

### ISSUE THREAD

**Issue by SISTMrL** [ultralytics/yolov5#802]
## ❔Question
I'm confused about the build_targets function even if I search lots of information in Google, could you write some tech report or turtorial on this function to explain the meaning of this function? Thanks very much!

**Comment by glenn-jocher** [comment]
@SISTMrL this issue discusses the target building a bit:
https://www.kaggle.com/c/global-wheat-detection/discussion/172436

We are trying to get our own short paper out to arxiv around the end of this year.

**Comment by SISTMrL** [comment]
I work my project on medical image field using your repo, if I write paper before you submit the paper to arxiv, how can I quote your work due to lack of yolov5 paper, and I also concern about if I write paper may be I'll make some error in some technique because the only reference is Yolov4 and your code in this repo

**Comment by glenn-jocher** [comment]
@SISTMrL you can cite the YOLOv5 repository directly:
https://zenodo.org/record/3983579#.Xz8mLpNKg5g

DOI is 10.5281/zenodo.3908559

<img width="367" alt="Screen Shot 2020-08-20 at 6 45 21 PM" src="https://user-images.githubusercontent.com/26833433/90842971-636b0d80-e315-11ea-8e56-1b9bbcd24751.png">

**Comment by thanhnguyentung95** [comment]
> @SISTMrL this issue discusses the target building a bit:
> https://www.kaggle.com/c/global-wheat-detection/discussion/172436
> 
> We are trying to get our own short paper out to arxiv around the end of this year.

Is the paper released? How can I find it?

**Comment by xonobo** [comment]
Any explanation to **build_targets** function would be great.

I understand that objectness loss is calculated over all anchors according to their IoU score with their target match (assigned in build_targets function). However other losses like box regression and classification are not filtered out to be evaluated only on anchors with a objectness score above some threshold. Is it right? I must be missing something because in that case the box regression and classification should widely depend on the irrelevant background information.

**Comment by glenn-jocher** [comment]
@xonobo cls and regression losses apply only to matched anchors.

**Comment by xonobo** [comment]
I understand that build_targets function returns the indices of the matched anchors but I can not see any IoU calculation in build_targets function. What is the magic in build_targets? Is there any threshold mechanism or all anchors with a positive overlap are matched with a target?

**Comment by glenn-jocher** [comment]
@xonobo matching thresholds are hyperparameters:
https://github.com/ultralytics/yolov5/blob/f2d97ebb251e689f55879709179248d4acf8e2a3/data/hyps/hyp.scratch.yaml#L18-L19

**Comment by xonobo** [comment]
To clear my mind:
https://github.com/ultralytics/yolov5/issues/2373#issuecomment-791607441

**Comment by bot66** [comment]
me too confused.

**Comment by bot66** [comment]
> @SISTMrL this issue discusses the target building a bit:
> https://www.kaggle.com/c/global-wheat-detection/discussion/172436
> 
> We are trying to get our own short paper out to arxiv around the end of this year.

Is the paper released?

**Comment by bot66** [comment]
Ok, I think i understand why duplicate anchor generated bboxes, probably for high Recall, duplicate bboxes by add offset according to (x_center, y_center) coordinates decimal, then not just one grid cell response for  GT, multiple grid cell response for same GT, it should increase the Recall.
