### ISSUE TITLE
yolov5n-7-k5.pt and yolov5n-7.pt 

### ISSUE THREAD

**Issue by XiaoJiNu** [ultralytics/yolov5#8025]
what  yolov5n-7-k5.pt and yolov5n-7.pt are and where are their configuration file?

**Comment by glenn-jocher** [comment]
@XiaoJiNu these are experimental models for an upcoming release which will be deleted soon. We place models here sometimes to have easy access to them using autodownload, i.e. `python val.py --weights yolov5n-7.pt`

All YOLOv5 models have their yaml information embedded inside them, i.e. once loaded you can see this info as `model.yaml`

**Comment by XiaoJiNu** [comment]
@glenn-jocher Thank you
