### ISSUE TITLE
Hello can I plot or print the precision and recall in the detect.py?

### ISSUE THREAD

**Issue by jingab** [ultralytics/yolov5#8026]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello I am new here in yolov5 and would like to ask how to print the precision and recall of the video I read in the detect.py. and for specific class. Thank you

**Comment by glenn-jocher** [comment]
@jingab metrics are only computed on **labelled** data.
