### ISSUE TITLE
Class names from Prediction vector when inference by torch.hub

### ISSUE THREAD

**Issue by salidw** [ultralytics/yolov5#8028]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,
    I had made inference with 2 methods below. Method# 1 returned the predicted class names as I want.
How can I config. for Method# 2 to get the corrected class names. Now it returns Class0,Class1, ...Class999

**Method# 1**: model = torch.hub.load('ultralytics/yolov5', 'custom', path='../best.pt', force_reload=True) # pred = Mobile phone, Mouse
**Method# 2**: model = torch.hub.load('ultralytics/yolov5', 'custom', path='../trt.engine', force_reload=True) # pred = class0,class1,...class999

**Comment by glenn-jocher** [comment]
@salidw TensorRT models do not have class names as attached metadata, so the default names are used, i.e. class0. You can load a TRT model and then assign it class names, i.e.:

```python
model = ...
model.names = ['person', 'bus', ...
```

**Comment by salidw** [comment]
@glenn-jocher Thanks,sir

**Comment by glenn-jocher** [comment]
@salidw you're welcome! Feel free to reach out if you have any more questions. Our team is here to help!
