### ISSUE TITLE
Cropping bounding box in separate image

### ISSUE THREAD

**Issue by kriskris1973** [ultralytics/yolov5#803]
Hello,
I need help to edit detect.py for crop bounding boxes (detected object) as separate image. and save them in specific directory.
My idea will be something below what does not work , off course.

# Write results
                for *xyxy, conf, cls in det:
                    if save_txt:  # Write to file
                        xywh = (xyxy2xywh(torch.tensor(xyxy).view(1, 4)) / gn).view(-1).tolist()  # normalized xywh
                        with open(txt_path + '.txt', 'a') as f:
                            f.write(('%g ' * 5 + '\n') % (cls, *xywh))  # label format
                    
                    if save_img or view_img:  # Add bbox to image
                        label = '%s %.2f' % (names[int(cls)], conf)
                        plot_one_box(xyxy, im0, label=label, color=colors[int(cls)], line_thickness=3)
                        
                    if save_obj:
                        x,y,w,h = int(xywh[0]), int(xywh[1]), int(xywh[2]), int(xywh[3])
                        img_=np.transpose(xyxy, (2, 1, 0))
                        crop_img=img_[y:y+ h, x:x + w] 
                        cv2.imwrite(names[int(cls)]+ '{:}.jpg'.format(i+1), crop_img)

**Comment by glenn-jocher** [comment]
@kriskris1973 what's the use case exactly? For passing to a classifier training set? You should be aware that classifiers tend to benefit from added contextual space around the object they are classifying, which the default boxes will not provide, as they are optimized to perfectly enclose the object of interest.

**Comment by kriskris1973** [comment]
> @kriskris1973 what's the use case exactly? For passing to a classifier training set? You should be aware that classifiers tend to benefit from added contextual space around the object they are classifying, which the default boxes will not provide, as they are optimized to perfectly enclose the object of interest.

The use case is comparing detected object with something ( recommendation systems), so the default boxes will be prefect for that  aim

**Comment by glenn-jocher** [comment]
@kriskris1973 hmm ok. Then the best way to do this would be to develop and test a PR, and then submit to us for review. The code you showed looks like the perfect place to implement it, and it can go along with a new argparser argument, i..e --save-boxes

**Comment by AKHILzz12345** [comment]
Hello @kriskris1973 , can you give me the code for cropping the boxes and saving them?

**Comment by kriskris1973** [comment]
Hello ,
@glenn-jocher , this is adds to detect.py file for cropping and saving detected object which works very well for me
@AKHILzz12345 , sorry for late answer

[forum_detect.txt](https://github.com/ultralytics/yolov5/files/5252413/forum_detect.txt)

**Comment by sourangshupal** [comment]
@AKHILzz12345 Thanks for the code for cropping the bounding box..It is working fine

**Comment by Xyonia** [comment]
@AKHILzz12345 , @sourangshupal  
Hello. Where you add this forum_detect.txt code exatly to use. On detect.py? and from where you added and what you have changed? Can you help me? Thanks in advance.

**Comment by gregrutkowski13** [comment]
Update  -  For those that want to implement forum_detect.txt above into detect.py, this is how I did it. Every time I call detect.py I want individual .jpgs for each bounding box. Probably not the best solution for everyone but it works for my purpose. So I just manually made a separate output folder for all of the bboxes and added 

save_obj = True     #right above "if save_obj:"

**Comment by Xyonia** [comment]
where you add forum_detect.txt exactly on detect.py or can you share your detect.py please? @gregrutkowski13 ? Mine is always stopped working.
I always get 

    for *xyxy, conf, cls in det:
TypeError: 'NoneType' object is not iterable

Error

**Comment by gregrutkowski13** [comment]
> where you add forum_detect.txt exactly on detect.py or can you share your detect.py please? @gregrutkowski13 ? Mine is always stopped working.

there is a #Write Results portion of the detect.py. you can replace this entire section with the forum_detect script and make sure save_obj = True above #write results if you would like individual bboxes every time you call detect.py. Make sure you change the write path for the individual bbox jpgs as well. This should be the bare minimum to generate cropped bboxes. 

For me, I found the loop under "if save_obj:" was also iterating unnecessarily and causing new bboxes to overwrite others. Also you will have to change how the code indexes and assigns names to your individual bbox jpgs based on your classes/data.

**Comment by glenn-jocher** [comment]
All, if you want to extract boxes, you might want to just see the apply_classifier() function in detect.py. It extracts boxes for second stage classifier inference, but you can simply comment that part and replace it with a cv2.imwrite for the box.

https://github.com/ultralytics/yolov5/blob/83deec133d62021b496ba6cc475c38e717098053/detect.py#L79-L82

**Comment by Xyonia** [comment]
I am an  idiot or something but i cannot achieve with that way. I tried to comment 
     pred = apply_classifier(pred, modelc, img, im0s) 
then add cv2.imwrite() but i dont know the image name is it img,im0 or im0s or something else. I tried to comment out 
#        modelc = load_classifier(name='resnet101', n=2)  # initialize
#        modelc.load_state_dict(torch.load('weights/resnet101.pt', map_location=device)['model'])  # load weights
#        modelc.to(device).eval()

these lines and add cv2.imwrite there and i cannot make it done.
Somehow cv2. iwrite dows not work or i cannot place it to the right place.
Please if anyone see that help me that such an easy task turns out a nightmare for.
Thanks in advance.

**Comment by shiv-acharii** [comment]
> Hello ,
> @glenn-jocher , this is adds to detect.py file for cropping and saving detected object which works very well for me
> @AKHILzz12345 , sorry for late answer
> 
> [forum_detect.txt](https://github.com/ultralytics/yolov5/files/5252413/forum_detect.txt)

worked well for me. thanks @kriskris1973

**Comment by shiv-acharii** [comment]
https://github.com/ultralytics/yolov5/issues/2608#issuecomment-809094537

here is the complete code changes link

**Comment by glenn-jocher** [comment]
@gregrutkowski13 @AKHILzz12345 @Xyonia @sourangshupal Prediction box cropping is now available in YOLOv5 via PR https://github.com/ultralytics/yolov5/pull/2827! PyTorch Hub models can use `results.crop()` or detect.py can be called with the `--save-crop` argument. Example usage:
```
python detect.py --save-crop
```
<img width="1121" alt="Screenshot 2021-04-20 at 23 50 51" src="https://user-images.githubusercontent.com/26833433/115468484-70892500-a233-11eb-89e8-717bef0fa45b.png">

**Comment by manojkk1234** [comment]
you can use --save-crop to  save the cropped images. Cropped images will be saved in yolov5/runs/detect/exp/crop

**Comment by jmiller-dr** [comment]
For those who use Python code (rather than the `detect.py` script), how do you save an image with `results.crop()`?

**Comment by glenn-jocher** [comment]
@jmiller-dr `results.crop(save=True)`, or to specify save directory manually `results.crop(save=True, save_dir='path/to/dir')`

**Comment by glenn-jocher** [comment]
👋 Hello! Thanks for asking about **cropping results** with YOLOv5 🚀.  Cropping bounding box detections can be useful for training classification models on box contents for example. This feature was added in PR https://github.com/ultralytics/yolov5/pull/2827. You can crop detections using either detect.py or YOLOv5 PyTorch Hub:

## detect.py
Crops will be saved under `runs/detect/exp/crops`, with a directory for each class detected.
```bash
python detect.py --save-crop
```
<img width="450" alt="Original" src="https://user-images.githubusercontent.com/26833433/139577918-65cc8f5d-741d-4a88-8753-0154013c624d.jpg">

<img width="1067" alt="Crop" src="https://user-images.githubusercontent.com/26833433/139577896-aa26b07c-466d-4057-9bfe-b01b56007587.png">

## YOLOv5 PyTorch Hub
Crops will be saved under `runs/detect/exp/crops` if `save=True`, and also returned as a dictionary with crops as numpy arrays.
```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, custom

# Images
img = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, PIL, OpenCV, numpy, list

# Inference
results = model(img)

# Results
crops = results.crop(save=True)  # or .show(), .save(), .print(), .pandas(), etc.
```

Good luck 🍀 and let us know if you have any other questions!

**Comment by jmiller-dr** [comment]
Oh perfect! Thank you, that’s what I needed.
