### ISSUE TITLE
The performance of two models (3 vs 82)

### ISSUE THREAD

**Issue by bit-scientist** [ultralytics/yolov5#8032]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I would like to know how the performance of models differ in terms of speed and accuracy.
Let's say I have 2 new classes (`tree`, `scooter`), and would like to do a custom training that includes `person` class from COCO. I have two ways of addressing it.
1. Just add 2 classes in to the training pipeline (82 classes) and train with yolov5. For inference, I would just use `classes` arg for filtering out not important classes and detect/show `person`, `tree` and `scooter`.
2. download all images of a person class from COCO dataset and prepare dataset for 3 classes, then train with yolov5. For inference, I would directly detect/show `person`, `tree` and `scooter`.

Which way is more promising? Will the second model be lighter if it is trained for less classes? 
I would appreciate if any material is provided for in-depth analysis for such hypothetical concerns. Thank you.

**Comment by glenn-jocher** [comment]
@bit-scientist see https://community.ultralytics.com/t/how-to-combine-weights-to-detect-from-multiple-datasets

You can evaluate speed/FLOPs of any custom model with
```
python models/yolo.py --cfg model.yaml
```

You can introduce an nc: 80 parameter in your yaml to construct a model with nc classes.
