### ISSUE TITLE
How to get the frame id when use LoadStream class to load multiple videos?

### ISSUE THREAD

**Issue by alexHxun** [ultralytics/yolov5#8034]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

when i use LoadStream class to load frames of multiple videos to inference, i found i cant get the frame id of video.

I am not very know about multi-thread , i try to add self.frame_id to LoadStream class , and output in below in detect.py :
`for path, im, im0s, vid_cap, s in dataset:`
         `print(dataset.frame_id)`

but it doesn`t work , because i don`t know where the 'self.frame_id+=1' to insert......

so how can i get the frame_id in for loops 'for path, im, im0s, vid_cap, s in dataset:' ?

**Comment by glenn-jocher** [comment]
@alexHxun hi there!

You can access the frame id in the `for path, im, im0s, vid_cap, s in dataset:` loop by including an increment statement (`self.frame_id += 1`) within the `__next__` method of the `LoadStream` class.

This line should be added just before the `return path, im, im0, vid_cap, s` statement in the `__next__` method.

Feel free to reach out if you have any further questions!
