### ISSUE TITLE
If I want to print only the name and number of objects it detects

### ISSUE THREAD

**Issue by Kingjulien55** [ultralytics/yolov5#8036]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

If I want to print only the name and number of objects it detects how do i do or sample
I'm just getting started with yolov5 and opencv, thanks for the help and advice.

### Additional

![image](https://user-images.githubusercontent.com/99008316/170915085-fc21a1d2-5ceb-4025-bb57-af236b84c2ee.png)

**Comment by glenn-jocher** [comment]
@Kingjulien55 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # yolov5n - yolov5x6 official model
#                                            'custom', 'path/to/best.pt')  # custom model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by DiogoFerreira77** [comment]
I also have the same question. How can i count the number of times an object is present?

**Comment by AnubhavDixit** [comment]
Sorry, but the answer is not clear.

**Comment by DiogoFerreira77** [comment]
> Sorry, but the answer is not clear.

For example, while the webcam is on, i want to detect the object cellphone and how many times it was detected

**Comment by Kingjulien55** [comment]
> > Sorry, but the answer is not clear.
> 
> For example, while the webcam is on, i want to detect the object cellphone and how many times it was detected

i use .pandas().xyxy[0] After that, follow with your desired conditions.

**Comment by Kingjulien55** [comment]
![image](https://user-images.githubusercontent.com/99008316/173337491-9ccce248-97e3-47aa-9170-ef43a4556a47.png)
example

**Comment by DiogoFerreira77** [comment]
> ![image](https://user-images.githubusercontent.com/99008316/173337491-9ccce248-97e3-47aa-9170-ef43a4556a47.png) example

Thank you kingjulien55.

**Comment by glenn-jocher** [comment]
@DiogoFerreira77 thank you for the example! 🙌

You can achieve this by applying a condition to filter and count the occurrences of the object you are interested in. In the given Python example, `results.pandas().xyxy[0]` returns a pandas DataFrame, allowing you to easily count the occurrences of the 'cellphone' object.

Here's a general approach to count the occurrences of the 'cellphone' object:

```python
# Assuming results is the output of your YOLOv5 detection
cellphone_count = (results.pandas().xyxy[0]['class'] == 'cellphone').sum()
print(f'Number of cellphones detected: {cellphone_count}')
```

The above code snippet filters the DataFrame to rows where the object class is 'cellphone', then uses `.sum()` to count the occurrences.

Give it a try and let me know if you have any issues or further questions!
