### ISSUE TITLE
incremental training issue

### ISSUE THREAD

**Issue by Pankaj901** [ultralytics/yolov5#8037]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

in continuity with this thread #6419 , I have one question. let's consider I have a dataset (500) with 5 classes and now I added another 300 data with 10 classes. (500[5] +300[10]). also, the new 5 class is present in some of the old datasets (500) but not labeled. so if I train the whole dataset now how my accuracy will be impacted?? and what will be the possible solution?

**Comment by glenn-jocher** [comment]
@Pankaj901 all instances of all classes you are training must be labelled in both datasets. One option is to autolabel classes if you have models trained on those classes.

For training on multiple datasets see https://community.ultralytics.com/t/how-to-combine-weights-to-detect-from-multiple-datasets
