### ISSUE TITLE
Being able to work with multiple gpu and different ram sizes?

### ISSUE THREAD

**Issue by sarpx** [ultralytics/yolov5#8038]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

1 gpu  -> 11GB GDDR6       batch-size max 4
2 gpu  -> 24GB GDDR6       batch-size max 8

I couldn't work these two together before and preferred to use only one. But one machine is not enough anymore.. Can I use two GPUs with technically different features for training together?
Is the problem in the settings or is it technically impossible?

**Comment by glenn-jocher** [comment]
@sarpx Multi-GPU training is only recommended on identical GPUs.
