### ISSUE TITLE
Difference between Precision and mAP50:95?

### ISSUE THREAD

**Issue by yolor2** [ultralytics/yolov5#8039]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Could you please tell me the difference between prececision and mAP50:95 as while running sweeps, for some sweeps i am getting more precision like 84% and mAP50:95 around 54, while for some sweeeps both are relatively same. SO what could be the reason for that?

**Comment by glenn-jocher** [comment]
See https://en.wikipedia.org/wiki/Precision_and_recall

**Comment by yolor2** [comment]
@glenn-jocher what do you infer if the precision is around 80% and the mAP50_95 is around 70 and mAP50 around 90

**Comment by glenn-jocher** [comment]
@yolor2 you can ignore P and R, they are relative metrics which depend on a confidence threshold. mAP is an absolute metrics that is not a function of confidence threshold.

**Comment by yolor2** [comment]
> @yolor2 you can ignore P and R, they are relative metrics which depend on a confidence threshold. mAP is an absolute metrics that is not a function of confidence threshold.

@glenn-jocher  If mAP is an absolute metrics then why change in confidence threshold changes the values of mAP? could you please help me this dilemma

**Comment by glenn-jocher** [comment]
@yolor2 mAP is not valid at any other value than the default confidence threshold or lower. Ideally it is only ever computed at 0.0 confidence by definition.

There is no correct mAP calculation at any other confidence.

**Comment by yolor2** [comment]
@glenn-jocher hello, what do you think is the best for object detection task : mAP50 or mAP50:95 and why? because i got mAP50 around 90% and mAP50:95 around 60%. So i am trying to find the justification of this gap.
Could you please help.

**Comment by glenn-jocher** [comment]
@yolor2 mAP@0.5 is the official VOC metric and mAP@0.5:0.95 is the official COCO metric. There is no 'best' metric, but mAP@0.5:0.95 is the most widely recognized object detection metric.

**Comment by Sridharanraja** [comment]
I want to know about these..
box_loss,obj_loss,cls_loss,Instances,Instances,P,R,mAP50,mAP50-95
