### ISSUE TITLE
The role of the Focus layer

### ISSUE THREAD

**Issue by EvaneSnow** [ultralytics/yolov5#804]
Hi, I'm a little confused about the focus layer. Can you tell me what the focus layer does

**Comment by DacDinh147** [comment]
`Focus` layer acts like a transformation from space to depth. In normal backbone likes ResNet you have a `stem layer` from the bottom with `Conv2d kernel_size=7x7, stride=2` to reduce the space (resolution) and increase the depth (number of channels). So, in YOLOv5 the author wants to reduce the cost of `Conv2d` computation and actually using tensor reshaping to reduce space (resolution) and increase the depth (number of channels). 

Input will be transformed likes this `[b, c, h, w] -> [b, c*2, h//2, w//2]` 

`Focus` layer act likes a `DepthToSpace` layer in TResNet, but the result is a bit different. You can do a small experiment like this: 

Create a toy tensor `x`
```
tensor([[[[11, 12, 13, 14], 
		 [21, 22, 23, 24], 
		 [31, 32, 33, 34], 
		 [41, 42, 43, 44]]]])
```
Pass `x` to `Focus` layer and the result is 
```
tensor([[[[11, 13], 
		  [31, 33]], 
			 
		 [[21, 23], 
		  [41, 43]], 
		 
		 [[12, 14], 
		  [32, 34]], 
		 
		 [[22, 24], 
		  [42, 44]]]])

```

`DepthToSpace` transformation in TResNet
```
N, C, H, W = x.size()
t = x.view(N, C, H // 2, 2, W // 2, 2)
t = t.permute(0, 3, 5, 1, 2, 4).contiguous()
t = t.view(N, C * (2 ** 2), H // 2, W // 2)
```
`t` is:

```
tensor([[[[11, 13], 
		  [31, 33]],
		   
		 [[12, 14], 
		  [32, 34]], 
		
		 [[21, 23], 
		  [41, 43]], 
		 
		 [[22, 24], 
		  [42, 44]]]])
```

**Comment by youreternity1997** [comment]
Hello @DacDinh147 !!  In YOLOv5,  it is x(b,c,w,h) -> y(b,4c,w/2,h/2), not the y(b,2*c,w/2,h/2). Is this my fault or yours?
```
class Focus(nn.Module):
    # Focus wh information into c-space
    def __init__(self, c1, c2, k=1, s=1, p=None, g=1, act=True):  # ch_in, ch_out, kernel, stride, padding, groups
        super(Focus, self).__init__()
        self.conv = Conv(c1 * 4, c2, k, s, p, g, act)
        # self.contract = Contract(gain=2)

    def forward(self, x):  # x(b,c,w,h) -> y(b,4c,w/2,h/2)
        return self.conv(torch.cat([x[..., ::2, ::2], x[..., 1::2, ::2], x[..., ::2, 1::2], x[..., 1::2, 1::2]], 1))
```

**Comment by glenn-jocher** [comment]
4c is correct
