### ISSUE TITLE
Number labels is not same when i set different confidence

### ISSUE THREAD

**Issue by root12321** [ultralytics/yolov5#8040]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Validation

### Bug

i test a dataset where have 10 images and 10 labels, one class.
in code yolov5-6.0 , i run the code val.py and result is :
![image](https://user-images.githubusercontent.com/28287748/170964521-4e83d82c-ee60-49b5-8998-a21bd401bff0.png)

in code yolov5-6.1 , i run the code val.py and result is :
![image](https://user-images.githubusercontent.com/28287748/170964564-42e1b706-af71-49c0-a66c-e7e78e2a86fe.png)
you can see the difference. in code yolov5-6.0,number of labels is 10,and it is right,but in yolov5-6.1,number of labels is 9, it is wrong , i dont know what happen in the new code of yolov5-6.1 , can you explain it , thank you !

### Environment

-YOLO: YOLOV5-6.1
-OS: Ubuntu16.04
-PYTHON:python3.6

### Minimal Reproducible Example

you can run val.py with different confidence, then you can  reproduce the problem
for example ,you can run :
`python val.py --conf-thres 0.001`
then, set different confidence, run again:
`python val.py --conf-thres 0.2`
then you can see the number of labels is not same. this problem is only happen in the code of yolov5-6.1 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@root12321 thanks for the bug report! I'm able to reproduce. I will add a TODO to investigate.

<img width="1229" alt="Screenshot 2022-05-30 at 12 45 10" src="https://user-images.githubusercontent.com/26833433/170976412-bf834f62-5b03-489e-9ba6-bb7f84aac07d.png">

**Comment by victor1cea** [comment]
Should `Labels` be the actually the count of all labels? I actually like the current way of only showing labels that are taken in consideration in computing the metrics i.e. the labels above the confidence threshold. Maybe having two outputs e.g `Total Labels` and `(Accounted) Labels` would make the output less ambiguous?

I am also willing to contribute to this issue with a PR.

**Comment by glenn-jocher** [comment]
@victor1cea yes that's a good point. In theory mAP should be calculated at --conf 0.0, and we have a warning that any increases above --conf 0.001 will produce invalid results, so I think current implementation is correct.

**Comment by jianganghuang** [comment]
Does it have been solved? I met the problem too

**Comment by glenn-jocher** [comment]
@hjg12345 Yes, the issue is still open and under investigation. I'll keep you updated on any progress. Thank you for your patience!
