### ISSUE TITLE
detector is slow on Xavier NX

### ISSUE THREAD

**Issue by Yousef-Alhattab** [ultralytics/yolov5#8041]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

hi there!
why the detector is slow on xavier nx 

![Screenshot from 2022-05-30 17-48-46](https://user-images.githubusercontent.com/56126016/170966527-eae03d00-ff30-45a4-bde2-51b4a8b6ebf0.png)

 there is a lag of 2 secand compare to running it on 2080??

and I am getting like this no cuda is there::
 YOLOv5 🚀 v6.1-211-gcee5959 Python-3.9.12 torch-1.11.0 CPU
![Screenshot from 2022-05-30 17-53-47](https://user-images.githubusercontent.com/56126016/170967539-8f5b843e-2839-47f5-b750-f8958290b34a.png)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Yousef-Alhattab** [comment]
I got it
cuda is not compiled with the environment 

any help to make it please?
![Screenshot from 2022-05-30 18-38-59](https://user-images.githubusercontent.com/56126016/170975479-2de0581b-0c66-4acb-a2cc-dc75bdb78709.png)

**Comment by glenn-jocher** [comment]
@urbansound8K it looks like the CUDA support is not enabled in your environment. To enable CUDA, you will need to install PyTorch with the appropriate CUDA version for your Xavier NX. You can refer to the Ultralytics Docs for detailed instructions on setting up YOLOv5 with CUDA support. Let me know if you need further assistance!
