### ISSUE TITLE
Yolov5 weights aren't available

### ISSUE THREAD

**Issue by Devissha** [ultralytics/yolov5#8043]
I've been trying to install yolov5 in google colab but then I realized that the weights of yolov5 aren't available here 
" https://github.com/ultralytics/yolov5" anymore. I'm not sure if that's the issue for eveyone. Are there any other ways to obtain the weights?
![image](https://user-images.githubusercontent.com/106422080/170989690-5be24c7e-7bd2-4ef4-9d0e-85d2e7bbe428.png)

**Comment by glenn-jocher** [comment]
@Devissha 👋 Hello! Thanks for asking about **downloading weights**. All official YOLOv5 🚀 pretrained models including P6 models are available to download directly under the latest release in the 'Assets' section, i.e.:
https://github.com/ultralytics/yolov5/releases/tag/v6.1

<img width="1038" alt="Screen Shot 2022-05-01 at 11 48 44 AM" src="https://user-images.githubusercontent.com/26833433/166160148-45f4fba2-998f-40d0-abe1-a57c93a55fda.png">
Good luck 🍀 and let us know if you have any other questions!

**Comment by Devissha** [comment]
> @Devissha 👋 Hello! Thanks for asking about **downloading weights**. All official YOLOv5 🚀 pretrained models including P6 models are available to download directly under the latest release in the 'Assets' section, i.e.: https://github.com/ultralytics/yolov5/releases/tag/v6.1
> 
> <img alt="Screen Shot 2022-05-01 at 11 48 44 AM" width="1038" src="https://user-images.githubusercontent.com/26833433/166160148-45f4fba2-998f-40d0-abe1-a57c93a55fda.png">
> 
> Good luck 🍀 and let us know if you have any other questions!

That worked! Thank you so much, really appreciate your help :)
