### ISSUE TITLE
Skip frames in Loadstreams?

### ISSUE THREAD

**Issue by VyasVedant** [ultralytics/yolov5#8050]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How can we skipframes for youtube url and not go by each frame so that process become less time consuming as I have made changes for LoadImages and it works fine  but Loadstream in little complicated , So kindly help @glenn-jocher . Thank you

**Comment by glenn-jocher** [comment]
@VyasVedant its not complicated at all, there's a simple parameter here called `read`:
https://github.com/ultralytics/yolov5/blob/dcf8073881d60e3ac6f14cce561d06fa114d9fc9/utils/dataloaders.py#L346

**Comment by VyasVedant** [comment]
> @VyasVedant its not complicated at all, there's a simple parameter here called `read`:
> 
> https://github.com/ultralytics/yolov5/blob/dcf8073881d60e3ac6f14cce561d06fa114d9fc9/utils/dataloaders.py#L346

So what do we need to do to read parameter?? @glenn-jocher

**Comment by VyasVedant** [comment]
> @VyasVedant its not complicated at all, there's a simple parameter here called `read`:
> 
> https://github.com/ultralytics/yolov5/blob/dcf8073881d60e3ac6f14cce561d06fa114d9fc9/utils/dataloaders.py#L346

Got it like if I want to skip 30 frames I need to set read=30 ,Am I right??

**Comment by glenn-jocher** [comment]
@VyasVedant yes

**Comment by glenn-jocher** [comment]
`n, f, read = 0, self.frames[i], 30`

**Comment by VyasVedant** [comment]
> `n, f, read = 0, self.frames[i], 30`

okay so in place of 1 there should be 30.
Thank you so much @glenn-jocher  for helping. I am trying this solution if it doesn't work I will let you know

**Comment by VyasVedant** [comment]
@glenn-jocher it is not skipping frames now also . Any other suggestion ??

**Comment by VyasVedant** [comment]
![Capture](https://user-images.githubusercontent.com/95400485/171149139-106ff737-4502-4fe2-a728-3678304453a7.JPG)
Have a Look

**Comment by jasminepak** [comment]
> @VyasVedant its not complicated at all, there's a simple parameter here called `read`:
> 
> https://github.com/ultralytics/yolov5/blob/dcf8073881d60e3ac6f14cce561d06fa114d9fc9/utils/dataloaders.py#L346

The way can only skip the stream display frames. May I ask how to skip the save frame per second? For example, my live stream is 25/fps, but I only want to save 1 frame per second. How can I do that?
