### ISSUE TITLE
Fine Tuning with very small dataset

### ISSUE THREAD

**Issue by Basti110** [ultralytics/yolov5#8052]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, 

I have not found any answer in the issues for my question. 
With the given COCO trained models, i have some problems with persons lying on the floor. For example, when they do pushups or  planks. I did the inference on some videos. Yolo can predict the persons most of the time but for few milliseconds (arround 200-1000ms) the scores are really bad. In my option, a small dataset arround 30-50 images for lying persons should solve the problem. 

Now Im looking for the best way to add this data to the pretrained model without worsening the predictions for persons in other poses. I also dont want to influence the predictions of other classes. With the least amount of effort, of course.

1. I can add the 30-50 images to the coco dataset and do a fine tune training with the whole dataset.
2. I can do a transfer learning only with these 30-50 images. 
3. I can add the 30-50 images to coco and train from scratch.  

Which of these solution is the best for my problem?

**Comment by glenn-jocher** [comment]
@Basti110 1 or 3 are the correct methods. 2 will lead to forgetting all other classes.

3 will probably deliver the best results, 1 will deliver the fastest results.

**Comment by glenn-jocher** [comment]
@Basti110 also see https://community.ultralytics.com/t/how-to-combine-weights-to-detect-from-multiple-datasets

**Comment by Basti110** [comment]
@glenn-jocher Thank you very much for this link! Then I will try method 1. Hopefully that will be sufficient.

**Comment by cold-blue** [comment]
> @glenn-jocher Thank you very much for this link! Then I will try method 1. Hopefully that will be sufficient.

Hi, have you tried the method 1? how was it going?

**Comment by glenn-jocher** [comment]
@cold-blue hi there, thanks for choosing YOLOv5! I'm glad the link was helpful to you. If you have tried method 1, could you please share how it went? We're always interested in hearing about users' experiences and any insights you may have gained. Thanks again and happy experimenting!
