### ISSUE TITLE
 I found error while  using yolov5  

### ISSUE THREAD

**Issue by shikhakalinga1** [ultralytics/yolov5#8056]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

[yolo5.docx](https://github.com/ultralytics/yolov5/files/8804375/yolo5.docx)

**Comment by glenn-jocher** [comment]
@shikhakalinga1 inline any comments or questions rather than attaching files.

**Comment by Guttappa1238** [comment]
Hi @shikhakalinga1 , Its just file not found error. Just give the full path or check whether file exist in the folder
