### ISSUE TITLE
error loading model

### ISSUE THREAD

**Issue by billson16** [ultralytics/yolov5#8058]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection, PyTorch Hub

### Bug

Hello, Ultralytics. I'm glad I have this opportunity to ask you. I am handling a project related to fire detection using AI, I have seen your project and development related to object detection using YOLOV5 which is referred to this link (https://github.com/ultralytics/yolov5). I have tried to implement it in my project and it worked really well. But sometimes I just encountered some error in loading your model which is shown in the image below. I don't really understand why this error sometimes can occur and sometimes not, do you have any idea on how to solve this problem?
![error ](https://user-images.githubusercontent.com/103013105/171168542-b15fe0ed-aa65-47e2-a433-3eee093259c5.jpg)

### Environment

-Yolo: YOLOV5
-OS: Windows 10
-Python: Python 3.9.12 

### Minimal Reproducible Example

model = torch.hub.load('ultralytics','yolov5','yolov5s')

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@billson16 we can only investigate bugs that we can reproduce, and your usage does not produce any errors for us.

**Comment by billson16** [comment]
Thank you for your reply @glenn-jocher. 
So, what is the possible problem that I couldn't run the model smoothly sometimes? 
Is it because of my machine?

**Comment by glenn-jocher** [comment]
@billson16 seems like an internet connection issue on your machine

**Comment by billson16** [comment]
Thank you for your response, Glenn Jocher.
I think there Is a possibility of an internet connection issue on my
machine. I will try to run model in more stable internet connection, Thank
you so much Glenn Jocher.
