### ISSUE TITLE
Default YOLOv5 Learning Rate Decay

### ISSUE THREAD

**Issue by wiky231** [ultralytics/yolov5#8064]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have searched the discussions and discovered that the base LR is 0.01. However, which learning rate scheduler is currently the default for YOLOv5s? I found some stating cosine and some linear.

**Comment by glenn-jocher** [comment]
linear
