### ISSUE TITLE
TensorRT export Failure

### ISSUE THREAD

**Issue by dasdristanta13** [ultralytics/yolov5#8069]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

``` TensorRT: export failure: 'tensorrt.tensorrt.OnnxParser' object has no attribute 'parse_from_file' ``` this error is showing whenever I am trying to convert my trained .pth model to TensorRT

### Environment

-YOLO: YOLO v6.1-21-ge6e36aa torch 1.8.1+cu102 CUDA:0 (NVIDIA GeForce GTX 1050 Ti, 4037MiB)
-OS: Ubuntu 20.10

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@dasdristanta13 update TRT and try again, or use our Docker image for export.
