### ISSUE TITLE
Custom data set which contain unlabelled objects

### ISSUE THREAD

**Issue by danik7** [ultralytics/yolov5#8071]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, 
I have a data set with tagged object which are not included inside the 80 COCO classes. 
I would like to add this class to be the 81 class by train a YOLOv5 with all the data sets (my data and COCO), but in my data set, I have a lot of *untagged* objects which are included in the 80 COCO class. 

What can I do?
I thought maybe to use YOLOv5 to tag my data set (by inference), and then use the results for training with all two data sets (when my data set has my labels and the YOLOv5 tags). 

Thank you!

**Comment by glenn-jocher** [comment]
@danik7 you can autolabel your dataset for COCO and then append your own labels (starting at index 80) afterwards, i.e.:
```
python val.py --weights yolov5x.pt --data YOUR_DATA.yaml --save-hybrid
```

--save-hybrid is like --save-txt except it will add new labels to any existing labels.
