### ISSUE TITLE
It is possible to adjust different conf threshold values for different classes?

### ISSUE THREAD

**Issue by pydoni** [ultralytics/yolov5#8073]
I want to know if it is possible for me to adjust the threshold confidence level to a value of one class, while a different value is assigned to the rest of the classes.

**Comment by glenn-jocher** [comment]
@pydoni officially no, but you can always create your own confidence vector and apply thresholds individually in the NMS function:
https://github.com/ultralytics/yolov5/blob/7cef03dddd6fba26fff6748ed1cfdd18208c193e/utils/general.py#L829-L836

**Comment by pydoni** [comment]
Thank you Glenn! I will try to create my version of this, if it ends up any good I will do a pull here.

**Comment by glenn-jocher** [comment]
@pydoni you're welcome! That sounds like a great approach. If you have any questions along the way, feel free to ask. Your contribution is appreciated by the YOLO community.
