### ISSUE TITLE
.

### ISSUE THREAD

**Issue by LimJihu** [ultralytics/yolov5#8074]

**Comment by glenn-jocher** [comment]
@LimJihu 👋 Hello! Thanks for asking about object **tracking** in computer vision. YOLOv5 🚀 is an object **detector** that detect, localizes and classifies objects in a single image. It does not connect objects across multiple images, for this you need a tracking solution. A few possible tracking solutions are:

- **Extended Kalman Filter (EKF)**: https://en.wikipedia.org/wiki/Kalman_filter
- **KLT tracker**: https://en.wikipedia.org/wiki/Kanade%E2%80%93Lucas%E2%80%93Tomasi_feature_tracker
- **YOLOv5 DeepSort tracker**: https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch

Good luck 🍀 and let us know if you have any other questions!
