### ISSUE TITLE
i want detect juset 1frames in 6frames in video 

### ISSUE THREAD

**Issue by LimJihu** [ultralytics/yolov5#8079]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hello.

i want to detect 1frames per 6frames. so, if my video have 12000frames in video, i just detect 2000frames only. 

so i wrote my code like 
![image](https://user-images.githubusercontent.com/89961242/171629181-6aa72b6f-330c-4a0b-868b-1c0a6cf15b0b.png)
(this is detect.py)

but the result is 
![image](https://user-images.githubusercontent.com/89961242/171629241-1822958a-9f50-4578-87a5-d59956daa347.png)

i have no idea about this.. i just returned 1 framed-video ( the output video have just one frame)

can anybody help me?

**Comment by glenn-jocher** [comment]
@LimJihu you can skip frames in the video dataloader here:
https://github.com/ultralytics/yolov5/blob/7cef03dddd6fba26fff6748ed1cfdd18208c193e/utils/dataloaders.py#L216-L228

**Comment by LimJihu** [comment]
@glenn-jocher 
thanks a lot, but i don't know how to operate this code. 
i want detect 2000frames and left (not delete) 10000frames left. 
my goal is detect 1 frame in every 6frames, and track left 5frames in every 6 frames.

any help?

**Comment by glenn-jocher** [comment]
@LimJihu I understand. You can achieve this by modifying the code in detect.py to skip frames in the video. You can use the frame index to determine when to skip frames. For example, you can modify your while loop to skip frames using the frame index. Additionally, for tracking the left frames, you can use a tracker like SORT or DeepSORT. For further assistance, you can refer to the Ultralytics Docs at https://docs.ultralytics.com/yolov5/ or ask for help in the YOLOv5 Discussions.
