### ISSUE TITLE
AssertionError: Failed to open 0

### ISSUE THREAD

**Issue by sytom8** [ultralytics/yolov5#8080]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

    assert cap.isOpened(), f'Failed to open {s}'
AssertionError: Failed to open 0

**Comment by glenn-jocher** [comment]
@sytom8 it looks like you tried to use a webcam on your computer but OpenCV can't find or open your webcam.
