### ISSUE TITLE
Is there a builtin method to train YOLOv5 to only detect one box per class in a multi-class detection?

### ISSUE THREAD

**Issue by sarmientoj24** [ultralytics/yolov5#8087]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Say I have four classes - A, B, C, D.

Is there a way to train the model that it only predicts / outputs a class, say A, **maximum** of one instance (min of 0) per image?

**Comment by glenn-jocher** [comment]
@sarmientoj24 see PyTorch Hub tutorial for inference settings.

<img width="946" alt="Screenshot 2022-06-03 at 11 35 04" src="https://user-images.githubusercontent.com/26833433/171829412-3014881d-7546-4d69-9710-e5f3b998be28.png">

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️  RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Roboflow for Datasets, Labeling, and Active Learning](https://docs.ultralytics.com/yolov5/tutorials/roboflow_datasets_integration)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TFLite, ONNX, CoreML, TensorRT Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [Architecture Summary](https://docs.ultralytics.com/yolov5/tutorials/architecture_description)&nbsp; ⭐ NEW

Good luck 🍀 and let us know if you have any other questions!

**Comment by sarmientoj24** [comment]
@glenn-jocher yeah but i am a bit confused on what to set there. I know `agnostic` is for NMS across classes that overlap boxes. I am not sure what `multi_label` is. But I am pretty sure it is not the `agnostic` parameter that I am looking for.

**Comment by Im-JimmyHu** [comment]
maybe you focus too much to the original code.i think you can just define a function,which analyses the result from nms,then sum the number of boxes for every class, and print the class with max number

**Comment by glenn-jocher** [comment]
@Im-JimmyHu yes, you're correct that an approach could be to analyze the NMS results and then implement custom logic based on the number of boxes for each class. You can achieve this by writing a custom post-processing function that analyzes the NMS output for each class and selects the class with the maximum number of boxes.

You can find more information about post-processing and analysis of the model's output in the Ultralytics YOLOv5 documentation at https://docs.ultralytics.com/yolov5/. Let me know if you need further assistance with this approach or have any other questions!
