### ISSUE TITLE
Some question about the autoanchor metrics (ratio and IOU)

### ISSUE THREAD

**Issue by wilile26811249** [ultralytics/yolov5#8088]
Search before asking
 I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

**Question**
Have you tested the difference in performance (AP) between using ratio and IOU metrics in autoanchor?
And, Why do you prefer to use ratio instead of iou metrics in autoanchor? 

https://github.com/ultralytics/yolov5/blob/7cef03dddd6fba26fff6748ed1cfdd18208c193e/utils/autoanchor.py#L90~L94

**Thank you**

Additional
No response

**Comment by glenn-jocher** [comment]
@wilile26811249 current implementation was found to produce best results.

The fastest and easiest way to propose changes to the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by wilile26811249** [comment]
Thank you for your reply.
I will try it.

**Comment by glenn-jocher** [comment]
@wilile26811249 you're welcome! If you have any further questions or need assistance while working on your Pull Request, feel free to ask. Good luck with your contribution!
