### ISSUE TITLE
Can you tell me about anchor and compare to retinanet?

### ISSUE THREAD

**Issue by goldlee** [ultralytics/yolov5#809]
## ❔Question
I'm a little confused about anchor width/height pre-setting, your training size is 640, does the pre-setting width/heigh [10,13, 16,30, 33,23] for training size 416?

second, have you compare to retinanet? resnet34 or resnet50 as backbone?

Thank you for your reply!

**Comment by glenn-jocher** [comment]
@goldlee YOLOv5 uses Autoanchor. If your anchors need modification this will be done for you automatically, there is no action for you to take.

**Comment by goldlee** [comment]
> @goldlee YOLOv5 uses Autoanchor. If your anchors need modification this will be done for you automatically, there is no action for you to take.

thank you very much for your reply
