### ISSUE TITLE
How to change class name after converted TensorRT.

### ISSUE THREAD

**Issue by ryotaro137** [ultralytics/yolov5#8093]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I tried to make the model TensorRT.
However, I am having trouble changing the label names after converting to TensorRT.

If anyone has a solution, please let me know.

Thank you in advance.

**Comment by glenn-jocher** [comment]
@ryotaro137 TensorRT models don't have class names, but you can assign them if you load a TRT PyTorch Hub YOLOv5 model, i.e. 
```
model = torch.hub.load(...
model.names = ['abc', 'def', ...]
```

**Comment by ryotaro137** [comment]
Thank you teaching me usefuil tips!

However, I encounted under error.
Probably because input size of my model is 416, not 640.
So,  I try to reproduce my TensorRT model of 640.
After this attempt, the model worked without error!
Thank you!

By the way, I'll use the torchhub model to infer the video.
Is it possible to infer the video using the torchhub model?

Thank you very much.

**Comment by glenn-jocher** [comment]
@ryotaro137 yes you can create your own cv2 video loader and pass images one by one, or batched, to the model for pytorch hub inference.

**Comment by ryotaro137** [comment]
Thank you for your comments !
I try to create my cv2 video loader.

**Comment by EvelinaAleksiutenko** [comment]
I found the solution, If you pass in the data argument file with your class labels In the same format as coco128.yaml you will get the right class labels in the result. As an example:
```
names:
  0: <your_class_label_0>
  1: <your_class_label_1>
```

**Comment by glenn-jocher** [comment]
@EvelinaAlexiutenko great to hear that you found a solution to your issue! Thank you for sharing it with the community. This approach of passing in the data argument file with your class labels in the same format as coco128.yaml is indeed a good way to get the right class labels in the result. Your example demonstrates it perfectly. Keep up the good work, and feel free to reach out if you have any further questions or issues.
