### ISSUE TITLE
Yolov5 tflite model 

### ISSUE THREAD

**Issue by ashutoshbk** [ultralytics/yolov5#8099]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I train and deploy yolov5 tflite model in Android studio. It detecting only half screen and only in portrait mode. Why it is not detecting full screen and why it's not detecting properly in landscape mode in Android studio app?

### Additional

Portrait mode detection
![Screenshot_20220604-110440](https://user-images.githubusercontent.com/49612207/171989437-d70e8304-282f-4b5a-831d-1588571712f5.jpg)
Landscape mode detection
![Screenshot_20220604-095314](https://user-images.githubusercontent.com/49612207/171989459-b40ac080-f758-44af-a2ac-fd103fafd83d.jpg)
You can see in landscape mode it's not detecting properly.

**Comment by kingmacth** [comment]
Hi. What are you inferring to size and speed?
Can you use NNAPI?
Could you please share your code to android, I am also trying to use yolov5 on android.
Thanks!

**Comment by ashutoshbk** [comment]
I follow this material and train model using img size 416.
https://github.com/AarohiSingla/TFLite-Object-Detection-Android-App-Tutorial-Using-YOLOv5

**Comment by glenn-jocher** [comment]
@ashutoshbk hi there! 👋🏼 Thanks for sharing the details and the tutorial link. It's great that you've got your YOLOv5 TFLite model integrated into an Android app! As for the detection issues in portrait and landscape modes, the YOLOv5 model may require some adjustments in the deployment code to handle different screen orientations and sizes effectively. Here are a few things you might consider to address your detection concerns:

1. Verify that the YOLOv5 model's input sizes and aspect ratios are compatible with the Android app's layout and screen dimensions. You might need to adjust the model input size and anchor box priors to better suit the landscape mode.

2. Implement logic to dynamically adapt the model's input dimensions and anchor box priors based on the device's orientation and screen resolution.

The provided tutorial is a great starting point, and you might find additional suggestions in the YOLOv5 Android deployment documentation at https://docs.ultralytics.com/yolov5/android.

Feel free to share more details about your implementation, and we can work together to troubleshoot the detection issues. Looking forward to helping you get the YOLOv5 TFLite model working flawlessly on Android!
