### ISSUE TITLE
Getting error while training : NotImplementedError: Got <class 'NoneType'>, but numpy array, torch tensor, or caffe2 blob name are expected.

### ISSUE THREAD

**Issue by HuyenPhamX** [ultralytics/yolov5#81]
I cannot fix this bug.  Thanks for your help.
.....
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|█| 1/1 [0
                 all           3          13           0           0      0.0739     0.00842

     Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
  0%|                                                                                 | 0/1 [00:00<?, ?it/s]Apex recommended for faster mixed precision training: https://github.com/NVIDIA/apex
{'lr0': 0.01, 'momentum': 0.937, 'weight_decay': 0.0005, 'giou': 0.05, 'cls': 0.58, 'cls_pw': 1.0, 'obj': 1.0, 'obj_pw': 1.0, 'iou_t': 0.2, 'anchor_t': 4.0, 'fl_gamma': 0.0, 'hsv_h': 0.014, 'hsv_s': 0.68, 'hsv_v': 0.36, 'degrees': 0.0, 'translate': 0.0, 'scale': 0.5, 'shear': 0.0}
Apex recommended for faster mixed precision training: https://github.com/NVIDIA/apex
{'lr0': 0.01, 'momentum': 0.937, 'weight_decay': 0.0005, 'giou': 0.05, 'cls': 0.58, 'cls_pw': 1.0, 'obj': 1.0, 'obj_pw': 1.0, 'iou_t': 0.2, 'anchor_t': 4.0, 'fl_gamma': 0.0, 'hsv_h': 0.014, 'hsv_s': 0.68, 'hsv_v': 0.36, 'degrees': 0.0, 'translate': 0.0, 'scale': 0.5, 'shear': 0.0}
Apex recommended for faster mixed precision training: https://github.com/NVIDIA/apex

Traceback (most recent call last):
  File "G:\cnn\yolo\yolov5-master\train.py", line 401, in <module>
    train(hyp)
  File "G:\cnn\yolo\yolov5-master\train.py", line 287, in train
    tb_writer.add_image(f, res, dataformats='HWC', global_step=epoch)
  File "G:\python\lib\site-packages\torch\utils\tensorboard\writer.py", line 540, in add_image
    image(tag, img_tensor, dataformats=dataformats), global_step, walltime)
  File "G:\python\lib\site-packages\torch\utils\tensorboard\summary.py", line 301, in image
    tensor = make_np(tensor)
  File "G:\python\lib\site-packages\torch\utils\tensorboard\_convert_np.py", line 29, in make_np
    raise NotImplementedError(
NotImplementedError: Got <class 'NoneType'>, but numpy array, torch tensor, or caffe2 blob name are expected.

**Comment by HuyenPhamX** [comment]
Thanks for your help. 
I only use this command :

- train.py --img 416 --batch 16 --epochs 100 --data data.yaml --cfg custom_yolov5s.yaml  --name yolov5_bsx --nosave 

and do not change anything in train.py and other files

**Comment by glenn-jocher** [comment]
@HuyenPhamX your environment is not correct. You need to fix yours or you can use of ours:

## Reproduce Our Environment

To access an up-to-date working environment (with all dependencies including CUDA/CUDNN, Python and PyTorch preinstalled), consider a:

- **GCP** Deep Learning VM with $300 free credit offer: See our [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Google Colab Notebook** with 12 hours of free GPU time. <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/)

**Comment by wuzhenxin1989** [comment]
解决了嘛
