### ISSUE TITLE
No output can be seen in the output folder when using test.py

### ISSUE THREAD

**Issue by dapsjj** [ultralytics/yolov5#810]
I use this command to run test.py,`python test.py  --batch-size 1  --data ./data/myModel.yaml  --weights weights/20200819best.pt `,I set `verbose=True`.

I can't see any output in folder `inference/output`,I think that when running test.py, the images under the `val` path in `myModel.yaml `will be predicted once, but there is no output in `inference/output`. Why?

After using this command `python test.py  --batch-size 1  --data ./data/myModel.yaml  --weights weights/20200819best.pt `, I can only see this information in the console:
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|████████████████████████████████████████████
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|████████████████████████████████████████████
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|████████████████████████████████████████████
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|████████████████████████████████████████████
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|████████████████████████████████████████████
███████| 3443/3443 [04:24<00:00, 13.03it/s]
                 all    3.44e+03    7.52e+03       0.321       0.698       0.541       0.378

I want to get the `AP` of each class.Where is wrong?

**Comment by dapsjj** [comment]
I use `parser.add_argument('--verbose', action='store_true', default=True, help='report mAP by class')`,use `default=True`,then I can see AP.

**Comment by wudashuo** [comment]
use `--task test`

**Comment by glenn-jocher** [comment]
@dapsjj` python test.py --verbose`
