### ISSUE TITLE
Datasets.py

### ISSUE THREAD

**Issue by Mounthazeer** [ultralytics/yolov5#8100]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hi, i was using datasets.py to split my dataset but it is not available anymore what can i do now?
why has it been removed?
are there any problem with it?

edit: i actually just found out that the name changed to dataloaders.py

_No response_

**Comment by glenn-jocher** [comment]
@Mounthazeer renamed as dataloaders.py
