### ISSUE TITLE
cannot import name '_registerMatType' from 'cv2.cv2'

### ISSUE THREAD

**Issue by livan3li** [ultralytics/yolov5#8103]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

hi there.

when i install albumentations by command `!pip install -U albumentations` on colab. and try to start training I'm getting the following error:

Traceback (most recent call last):
  File "train.py", line 41, in <module>
    import val  # for end-of-epoch mAP
  File "/content/yolov5/val.py", line 37, in <module>
    from models.common import DetectMultiBackend
  File "/content/yolov5/models/common.py", line 14, in <module>
    import cv2
  File "/usr/local/lib/python3.7/dist-packages/cv2/__init__.py", line 9, in <module>
    from .cv2 import _registerMatType
ImportError: cannot import name '_registerMatType' from 'cv2.cv2' (/usr/local/lib/python3.7/dist-packages/cv2/cv2.cpython-37m-x86_64-linux-gnu.so)

**AND** 
it works If i dont install albumentations.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@livan3li This issua usually occurs when your `opencv-python` and `opencv-python-headless` versions don't match.
Here's how you can verify and fix this as mentioned in a stackoverflow answer:
> I've had the same issue and the problem was with opencv versioning:
> `C:\Windows\system32>pip list |findstr opencv`
>` opencv-python                 4.5.2.52`
> `opencv-python-headless        4.5.5.62`
> As you can see the versions are not the same, so first uninstall headless:
> `pip uninstall opencv-python==4.5.2.52`
> And then reinstall opencv-python 4.5.5.62 with opencv-python package:
> `pip install opencv-python-headless==4.5.5.62`

Source - https://stackoverflow.com/questions/70537488/cannot-import-name-registermattype-from-cv2-cv2
