### ISSUE TITLE
Finding the right ratio of an object from two different angles of the picture?

### ISSUE THREAD

**Issue by sarpx** [ultralytics/yolov5#8104]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

We are trying to detect diseases of trees in nature. We have multiple pictures of some trees. In some pictures, some trees look more sick according to the angle, while from other angles they look less sick. This affects us to give the right amount of medicine. Is there a way to understand the less sick and very sick pictures of the same tree and give the correct ratio?
![b](https://user-images.githubusercontent.com/73984193/172044894-429843cc-1116-48c9-810e-6ef6de260367.jpeg)
![a](https://user-images.githubusercontent.com/73984193/172044895-8b2ff468-5133-431d-9092-bc466b98e941.jpg)

**Comment by glenn-jocher** [comment]
@sarpx this is object detection, anything can be learned if you have labelled data and a domain expert human being can also learn it.

**Comment by sarpx** [comment]
@glenn-jocher  thank you for your return.
Here's the problem: figuring out the extent of the damage. If the damage is in more than one area, it is common. Our goal here is to see if the disease continues or spreads in these pictures taken at different times. We can only do this by tagging each tree, but when this is a huge forest, it is very difficult. We want to somehow recognize the sick trees and compare them with their previous state.

**Comment by glenn-jocher** [comment]
@sarpx not sure buddy, not a domain expert here. Seems to me as a layman that most of the effort is going back and finding individual trees rather than comparing them to past images.

**Comment by sarpx** [comment]
@glenn-jocher WE LOVE YOU :)

**Comment by glenn-jocher** [comment]
@sarpx thank you for your kind words! It's the YOLO community and the Ultralytics team that make it all possible. Always happy to help!
