### ISSUE TITLE
How confidence score is calculated?

### ISSUE THREAD

**Issue by doooooori** [ultralytics/yolov5#8105]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How can YOLO compute the confidence score at test time? They say they compute it as P (object) *IOU. But, during test time, you don't have the ground truth boxes. How is it possible?

**Comment by oakkyoakoak** [comment]
Hi, i am same situation like you, i am wondering whether you can figure it out yet.

**Comment by glenn-jocher** [comment]
@oakkyoakoak hi there! The confidence score in YOLOv5 is calculated as the product of the objectness score (P(object)) and the Intersection over Union (IOU) between the predicted bounding box and the ground truth box. The objectness score represents the probability that the bounding box contains an object. During inference, the model generates bounding boxes and applies the confidence score calculation without requiring ground truth boxes. The confidence score is used to determine the likelihood of the object being present in the bounding box. Let me know if you need further assistance!
