### ISSUE TITLE
ERROR: YOLOv5 TF.js inference is not supported

### ISSUE THREAD

**Issue by x4080** [ultralytics/yolov5#8108]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I tried to export the yolo5 model to tf js, using yolov5 colab (https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb) and its finished with this output :
```
...
Export complete (21.02s)
Results saved to /content/yolov5/yolov5
Detect:          python detect.py --weights yolov5s_web_model
```

Then I tried to detect using command specified above :
```
!python detect.py --weights yolov5s_web_model
```

but it wont run :
```
detect: weights=['yolov5s_web_model'], source=data/images, data=data/coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False
YOLOv5 🚀 v6.1-244-g47233e1 Python-3.7.13 torch-1.11.0+cu113 CUDA:0 (Tesla T4, 15110MiB)

Traceback (most recent call last):
  File "detect.py", line 252, in <module>
    main(opt)
  File "detect.py", line 247, in main
    run(**vars(opt))
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 92, in run
    model = DetectMultiBackend(weights, device=device, dnn=dnn, data=data, fp16=half)
  File "/content/yolov5/yolov5/models/common.py", line 438, in __init__
    raise Exception('ERROR: YOLOv5 TF.js inference is not supported')
Exception: ERROR: YOLOv5 TF.js inference is not supported
```

Is it because of colab ? or inferencing tf.js in python is not possible ?

Thanks

**Comment by AyushExel** [comment]
TF.js requires a javascript runtime to run inference. You need to run the model in your browser. Checkout this project using yolov5 tfjs export https://github.com/zldrobit/tfjs-yolov5-example

**Comment by glenn-jocher** [comment]
@x4080 see web model Usage example in export.py:
https://github.com/ultralytics/yolov5/blob/47233e1698b89fc437a4fb9463c815e9171be955/export.py#L38-L42

**Comment by x4080** [comment]
@glenn-jocher Yes tf js works, sorry for not clear before, it's in the colab version of yolo, I tried to do inference on, I wondered if I can do tf js inference in colab/regular tf

BTW, I tested in tf js and after sometime (using webcam feed into tf.tidy

```
const input = tf.tidy(() => {
			return tf.image
				.resizeBilinear(tf.browser.fromPixels(video), [modelWidth, modelHeight])
				.div(255.0)
				.expandDims(0);
		});
```

the chrome notice me that webgl is using too much memory, maybe a leak. Is this the behaviour we expected ? I tried using cocossd on tf js and waited for the webgl message, and it seems not happening

Thanks and sorry for misunderstanding

Edit:
here's the gpu message :
```
High memory usage in GPU: 660.26 MB, most likely due to a memory leak
```

**Comment by glenn-jocher** [comment]
@x4080 I'm sorry, my expertise doesn't extend to javascript unfortunately. But yes perhaps we should not display the incorrect usage example in export.py. This is printed here by default for all formats, but TF.js is the only one not supported by detect.py:
https://github.com/ultralytics/yolov5/blob/18674e2f037953001f007e4cd5ab176048093e88/export.py#L557-L563

Maybe printing separate instructions for TF.js would be better. Can you please submit a PR with this update to help future users? Thanks!

**Comment by x4080** [comment]
@glenn-jocher Sorry, I dont understand what PR should I create ?

**Comment by glenn-jocher** [comment]
@x4080 to print out correct TF.js Usage example on export of tfjs models.

**Comment by SkalskiP** [comment]
Hi, @x4080! You can also use NPM [package](https://github.com/SkalskiP/yolov5js) to deploy YOLOv5 model, exported to `tfjs` format.
