### ISSUE TITLE
Yolov5/Ultralytics

### ISSUE THREAD

**Issue by bilal697** [ultralytics/yolov5#8109]
Hello Hi, I have successfully trained the custom object detection for my project. For the next step, I want to perform certain actions on each detected class. E.g, When class 1 object is detected action 1 will happen, when class 2 object is detected action 2 will happen and similarly for other classes too. Anyone assist me how to perform this I will be thankful any little hint how to code this.

**Comment by AyushExel** [comment]
@bilal697 You can access the classes of detections by modifying `detect.py` according to your needs. [This line](https://github.com/ultralytics/yolov5/blob/master/detect.py#L134) loops through all predictions saved in the variable `pred`.
```
        for i, det in enumerate(pred):  # per image
```
The last element in each detection list denotes its class. You can see how it's accessed [here](https://github.com/ultralytics/yolov5/blob/master/detect.py#L154)
```
        for c in det[:, -1].unique():
              n = (det[:, -1] == c).sum()  # detections per class
```

**Comment by bilal697** [comment]
> @bilal697 You can access the classes of detections by modifying `detect.py` according to your needs. [This line](https://github.com/ultralytics/yolov5/blob/master/detect.py#L134) loops through all predictions saved in the variable `pred`.
> 
> ```
>         for i, det in enumerate(pred):  # per image
> ```
> 
> The last element in each detection list denotes its class. You can see how it's accessed [here](https://github.com/ultralytics/yolov5/blob/master/detect.py#L154)
> 
> ```
>         for c in det[:, -1].unique():
>               n = (det[:, -1] == c).sum()  # detections per class
> ```

Thanks alot, How to use this loop for getting the prediction:  for i, det in enumerate(pred):  # per image

the other loop
for c in det[:, -1].unique():
>               n = (det[:, -1] == c).sum()  # detections per class
is storing and giving the result of detecting class well by printing c or n. It gives the desire output for doing certain action.

**Comment by Im-JimmyHu** [comment]
not difficult ,you just refer the data.yaml,get the number c accoring the classnames list,then remove the loop.
for example:
you would like the detections of person from coco:
![image](https://user-images.githubusercontent.com/89967988/172339790-5849f12b-7cde-4c34-b57e-98db8eb0b664.png)
and then 
```python
        #for c in det[:, -1].unique():
        c=0
        n = (det[:, -1] == c).sum()  # detections per class
        s += f"{n} {names[int(c)]}{'s' * (n > 1)}, "  # add to string
```
i think maybe satisfy your need

**Comment by glenn-jocher** [comment]
@Im-JimmyHu You appear to be on the right track! It seems like you've correctly identified how to map the class index `c` to the class name using the `names` list from `data.yaml`. This should allow you to perform specific actions based on the detected classes. Keep up the good work, and feel free to reach out if you have more questions!
