### ISSUE TITLE
Confusion Matrix

### ISSUE THREAD

**Issue by Mounthazeer** [ultralytics/yolov5#8110]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

![confusion_matrix (1)](https://user-images.githubusercontent.com/58270012/172094802-f8ab0eb5-50d5-4dd0-bead-627328e7d255.png)

Can someone please explain this to me
why is false positive 1 and nothing in TN

**Comment by glenn-jocher** [comment]
This is simply True vs Predicated objects
