### ISSUE TITLE
How to run 2 models parallely??

### ISSUE THREAD

**Issue by VyasVedant** [ultralytics/yolov5#8112]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Actually I am using 2-3 different model that detect different objects like alcohol ,smoking ,etc . Currently I am running them sequentially but can anyone help how can I run them parallely??

**Comment by glenn-jocher** [comment]
@VyasVedant use python multithreading?
