### ISSUE TITLE
About EMA included parameters

### ISSUE THREAD

**Issue by cissoidx** [ultralytics/yolov5#8114]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,why these parameters are updated every epoch? I think that only hyp could be changed from epoch to epoch. The other parameters should stay exactly the same during training, right?

https://github.com/ultralytics/yolov5/blob/47233e1698b89fc437a4fb9463c815e9171be955/train.py#L389

**Comment by glenn-jocher** [comment]
@cissoidx these probably only need to be updated on training init or on train resume. If you want please test to see if this line is necessary, perhaps EMA is initialized with all needed params.

**Comment by cissoidx** [comment]
Obviously, `nc` should not be changing from epoch to epoch

**Comment by cissoidx** [comment]
So do `names`, `stride` and `class_weights`

**Comment by glenn-jocher** [comment]
@cissoidx You are correct, those parameters should ideally remain constant throughout training. It's possible that the current implementation allows for unnecessary updates. I recommend testing to ensure that the mentioned parameters are only updated when needed and not every epoch. Thank you for bringing this to our attention!
