### ISSUE TITLE
"non_max_suppression()" in Javascript

### ISSUE THREAD

**Issue by chen2mg** [ultralytics/yolov5#8117]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Hi guys,

I trained a yolo model and exported to onnx for web inference.

Does anybody know is there a Javascript version "non_max_suppression" I can use for onnx output [1, 25200, 7] ?

Thank you.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@chen2mg hi there,

You can find a JavaScript implementation of non-maximum suppression for YOLOv5 ONNX output at the following link: https://docs.ultralytics.com/yolov5/. Once you have the non-maximum suppression function, you should be able to apply it to your ONNX output with dimensions [1, 25200, 7]. 

Let me know if you have any further questions or need additional assistance.

Best regards
