### ISSUE TITLE
Get all predicted class for a particulat BB instead of max conf. class

### ISSUE THREAD

**Issue by NarenZen** [ultralytics/yolov5#8118]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I set a threshold of **0.25**, 

For a particular bounding box, 
dog is detected at  70% confidence
cat is detected at  45% confidence
horse is detected at  30% confidence
lion is detected at  10% confidence

The output I will get for that particular bounding box is **dog** because that's the class with max confidence.

Instead what I need is **dog, cat and horse** because all these 3 classes meets the threshold of 25%

**Comment by glenn-jocher** [comment]
@NarenZen you can customize the NMS function to return these here but these are not available by default:
https://github.com/ultralytics/yolov5/blob/47233e1698b89fc437a4fb9463c815e9171be955/utils/general.py#L775-L874

**Comment by NarenZen** [comment]
Should I set `multi_label = True`

**Comment by glenn-jocher** [comment]
@NarenZen this will create a detection for every class above --conf
