### ISSUE TITLE
Which parameter is better for resume training?

### ISSUE THREAD

**Issue by dapsjj** [ultralytics/yolov5#812]
I have 10 class data, I used this parameter to train for 30 epochs,:
`python train.py --img-size 640 --batch-size 8 --epochs 300  --workers 4 --data ./data/myModel.yaml --cfg ./models/yolov5m.yaml --weights weights/yolov5m.pt`
Then I interrupted the training, and then I want to resume training.

Which parameter is better for resume training?
Command 1 doesn't use `--resume` parameter, use `weights` parameter with `last.pt`:
`python train.py --img-size 640 --batch-size 8 --epochs 300  --workers 4 --data ./data/myModel.yaml --cfg ./models/yolov5m.yaml --weights weights/20200821best.pt`

Command 2 use `--resume` parameter and use `weights` parameter with `last.pt`:
`python train.py --img-size 640 --batch-size 8 --epochs 300  --workers 4 --data ./data/myModel.yaml --cfg ./models/yolov5m.yaml --weights weights/last.pt --resume`

Command 3 `--weights` parameter  use pretrained checkpoint of coco dataset:
`python train.py --img-size 640 --batch-size 8 --epochs 300  --workers 4 --data ./data/myModel.yaml --cfg ./models/yolov5m.yaml --weights weights/yolov5m.pt --resume`

Which command is better for resume training?

**Comment by glenn-jocher** [comment]
@dapsjj --resume is only used to complete interrupted trainings. Nothing is modifiable.

--weights allows you to specify a starting checkpoint for finetuning or training from scratch, and allows you to set any other argument you want.
