### ISSUE TITLE
Is it possible to use other models in Yolov5 's project?

### ISSUE THREAD

**Issue by wyctorfogos** [ultralytics/yolov5#8129]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi everyone. I'm new here and i was trying to use another models as Faster RCNN, EfficientNet  and others. 

Is it possible to use other models in Yolov5 's project? Even if it's necessary to convert them.

Thanks!

**Comment by glenn-jocher** [comment]
@wyctorfogos hi there! Welcome to the YOLOv5 community. YOLOv5 focuses specifically on the YOLO family of models, and currently does not support other detection architectures like Faster RCNN or classification models like EfficientNet. However, there are countless tools and libraries available for using those models, and interesting projects often involve combining multiple models.

Best of luck with your project! Let me know if you have any other questions.
