### ISSUE TITLE
NMS

### ISSUE THREAD

**Issue by SISTMrL** [ultralytics/yolov5#813]
## ❔Question
Hello, I read the code of NMS and find that's just NMS, do you have a try to use other nms, such as:soft nms, DIOU nms etc.

**Comment by glenn-jocher** [comment]
@SISTMrL we don't have soft-nms, but if you'd like to submit a PR please do!

**Comment by abhiagwl4262** [comment]
hey @glenn-jocher, You had a long discussion [here](https://github.com/Zzh-tju/ultralytics-YOLOv3-Cluster-NMS/issues/2). Did you try any of the soft-NMS or DIOU-ClusterNMS ?

**Comment by glenn-jocher** [comment]
@abhiagwl4262 a detailed analysis of various NMS techniques with YOLOv5 by the DIoU and ClusterNMS author is here:
https://github.com/Zzh-tju/yolov5

**Comment by shenyi0220** [comment]
A better option of bounding box fusion is provided here(https://github.com/shenyi0220/CP-Cluster)

**Comment by Ankit12bhatt** [comment]
@shenyi0220 I want to apply it to yolov5, and I have no idea how to do it.
