### ISSUE TITLE
Documentation and Proposals for Recall & Precision Output

### ISSUE THREAD

**Issue by victor1cea** [ultralytics/yolov5#8143]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

I have a few suggestions regarding the documentation and the calculation of the recall & precision:

1. Currently a detection is considered a true positive (TP), if the IoU between the ground truth and the detection is >=0.5 and this value of 0.5 is fixed. The `iou-thresh` parameter used in `val.py` is used for only NMS. I think that we should document this behavior a bit more explicit. I also propose to be able to define an own IoU threshold for evaluating a detection as TP. 

2. The recall and precision values that are seen in the output of `val.py` are actually the recall and the precision obtained after maximizing the F1-score. I don't have nothing against this thing, but maybe documenting this will be very helpful in understanding where this values actually come from. I was thinking that it will be nice to be able to have the precision and recall calculated based on the confidence threshold like `recall = TP/(TP+FN) for all labels with confidence > conf-thresh`

### Use case

My proposal are relevant for projects/use cases in which the recall and precision are the 'central metrics' instead of mAP@0.5 and mAP@0.5:0.95. 

### Additional

I think that having the proposed documentation will always be handy.
I was able to locally integrate an own IoU threshold for the validation of the detections and change the outputed recall & precision values based on the confidence threshold (instead of the F1 score).
So what do you think?

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@victor1cea P and R are oft requested metrics but in reality they form an incomplete picture and should never be used as an absolute metrics for model performance since they are a function of confidence as you say. You can achieve 100% recall or precision whenever you want simply by playing with the confidence threshold.

mAP is an absolute metrics that is not a function of confidence threshold, so for this reason it is the default metrics for comparison of detection/segmentation models.

max F1 confidence is used to establish the best balance between P and R in this work, but the only possible change would be to set the P and R confidence to a fixed inference default of 0.25, not the val.py argument of 0.001, which would of course never produce high precision.

**Comment by victor1cea** [comment]
@glenn-jocher thanks for the elaborated answer! I was not looking into "hacking" my way into a high recall/precision by playing with the confidence and IOU :smile:  My goal is to see what recall I would get if I set a minimum IOU detection threshold of 60%-65% with a confidence > 0.55, so I would be able to see what recall I can guarantee for a stricter metric.
Having a high mAP@0.5 and F1 score is obviously a great thing, but they do treat precision and recall equally and in my case recall is a bit more important. 
Is there a better way to evaluate the results of my yolov5 model in my case, in which recall is more important than precision?

**Comment by glenn-jocher** [comment]
@victor1cea Understood, and that's a completely valid concern. You might want to consider using the Precision-Recall curve to evaluate your model. It plots precision and recall for different confidence thresholds, enabling you to select a threshold that best suits your needs. 

You can calculate the Precision-Recall curve using the validation set predictions and ground truth, and visualize the curve to make an informed decision on the best threshold for your specific use case. If you need further assistance with this approach, feel free to ask.
