### ISSUE TITLE
Android demo

### ISSUE THREAD

**Issue by kingmacth** [ultralytics/yolov5#8144]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

https://play.google.com/store/apps/details?id=com.ultralytics.ultralytics_app

Where can I find the demo of this app?

**Comment by glenn-jocher** [comment]
@kingmacth you can train and demo your own models on the app using Ultralytics HUB: https://ultralytics.com/hub

**Comment by kingmacth** [comment]
@glenn-jocher Hi!
I need to test CPU and other resources to occupancy. When will this demo use NNAPI, GPU or CPU?
I want to be able to integrate inference functionality into my program, so source code is required.

**Comment by kingmacth** [comment]
@glenn-jocher 
I tested all 3rd party yolov5 Android demos on github. Their fastest speed on the yolov5s model is 150ms, and the demo you provide can do it within 30ms. I need this kind of reasoning speed, I hope to know how you achieve it, it is of great significance to the promotion of yolov5 on the Android side!

**Comment by glenn-jocher** [comment]
@kingmacth @SergioSanchezMontesUAM yes the Ultralytics app (https://ultralytics.com/app) is using TFlite on GPU on Android, ANE with CoreML on iOS. It's not running on NNAPI on Android yet due to implementation issues, but it's an improvement we'd like to make in the future.

**Comment by kingmacth** [comment]
> @kingmacth @SergioSanchezMontesUAM yes the Ultralytics app (https://ultralytics.com/app) is using TFlite on GPU on Android, ANE with CoreML on iOS. It's not running on NNAPI on Android yet due to implementation issues, but it's an improvement we'd like to make in the future.

@glenn-jocher @SergioSanchezMontesUAM  The inference part of this app is implemented in a way that hopefully can be shared. I have also seen other issues in the issues that require efficient reasoning on Android to the point where a friend finally gave up on yolov5 because he couldn't solve this problem, and was forced to use mobelnet's network. This problem has been bothering me for a few days too. I would be very grateful if I could get your help. I can also continue to use yolov5 in my projects.

**Comment by kingmacth** [comment]
@glenn-jocher @SergioSanchezMontesUAM 
Hello!
If you can't provide the code, can you provide a solution to the problem?
Why are you so much faster to the app than other people's yolov5s reasoning?
If the problem of inference speed cannot be solved, there is no choice but to give up yolov5 in Android application. My boss gave me time to run out.
Thank you both for your support!

**Comment by adityasihag1804** [comment]
Hey @kingmacth ,
Here's how you can use GpuDelegate in android for tflite model.
https://www.tensorflow.org/lite/performance/gpu

Follow [this repo](https://github.com/lp6m/yolov5s_android.git) to see how to implement yolov5 in the best possible way. The repo doesn't use GpuDelegate, make sure you add that and remove NnAPI, it doesn't support Yolo yet.

Also, ultralytics APK is fast because the input image size they use in the APK is [256, 320], for yolov5n, leading to massive latency boosts.
I hope this was useful.

**Comment by kingmacth** [comment]
> Hey @kingmacth , Here's how you can use GpuDelegate in android for tflite model. https://www.tensorflow.org/lite/performance/gpu
> 
> Follow [this repo](https://github.com/lp6m/yolov5s_android.git) to see how to implement yolov5 in the best possible way. The repo doesn't use GpuDelegate, make sure you add that and remove NnAPI, it doesn't support Yolo yet.
> 
> Also, ultralytics APK is fast because the input image size they use in the APK is [256, 320], for yolov5n, leading to massive latency boosts. I hope this was useful.

Thank you for your reply!
I also saw the reasoning speed of the ultralytics APK on Android before I wanted to use yolov5 in the project team. But no APK inference speed of all third-party implementations was found to be too slow. But your ultralytics APK is not open source, nor does it provide detailed implementation methods.
I know about the direction of improvement, but unfortunately I am not an Android engineer, so I can't achieve such a large amount of work to modify. So I can only temporarily give up yolov5.

**Comment by mikel-brostrom** [comment]
I tried this app (https://github.com/lp6m/yolov5s_android) with my custom models @kingmacth, you have a bunch of option to try out such as: img input size, inference precision and delegate on the fly. It works great. However, I don't see any inference speedup by using NNAPI. I achieve ~0.5seconds inference time with 640x640 imgsz, FP32 inference precision on Samsung Galaxy S10e. ~0.120seconds inference time with 320x320 imgsz, FP32 inference precision on Samsung Galaxy S10e

**Comment by kingmacth** [comment]
> I tried this app (https://github.com/lp6m/yolov5s_android) with my custom models @kingmacth, you have a bunch of option to try out such as: img input size, inference precision and delegate on the fly. It works great. However, I don't see any inference speedup by using NNAPI. I achieve ~0.5seconds inference time with 640x640 imgsz, FP32 inference precision on Samsung Galaxy S10e. ~0.120seconds inference time with 320x320 imgsz, FP32 inference precision on Samsung Galaxy S10e

thank you!
I have tested this project, it can only use CPU inference, and its inference speed is not fast enough. So I hope to get the official reasoning demo to achieve the same fast reasoning.

**Comment by MaddyThakker** [comment]
@kingmacth were you able to run your YOLO model on android GPU?

**Comment by glenn-jocher** [comment]
@MaddyThakker yes, I was able to successfully run my YOLO model on the Android GPU using the implementation provided in the [lp6m/yolov5s_android](https://github.com/lp6m/yolov5s_android) repository. It offers various options such as image input size, inference precision, and delegate settings that can be adjusted to optimize inference speed. However, I didn't observe any significant speedup when using NNAPI. I achieved around 0.5 seconds inference time with 640x640 image size and FP32 precision on a Samsung Galaxy S10e. With 320x320 image size and FP32 precision, the inference time improved to approximately 0.120 seconds.

**Comment by MaddyThakker** [comment]
@glenn-jocher thanks for your answer! 

Is this performance comparable to the Ultralytics Hub Play Store app inference speed? 

I ran the Ultralytics Hub YOLOv8 on One Plus 7T and got 20FPS for the small model, which is quite faster than your comment. 

Would this difference be coming from the different device types alone? Or maybe some implementation as well?

**Comment by glenn-jocher** [comment]
@MaddyThakker the performance achieved on different devices can vary due to hardware capabilities and optimizations specific to each implementation. The inference speed of the Ultralytics Hub Play Store app may be different based on various factors such as device type, model size, and settings. It's worth noting that the Ultralytics team has put significant effort into optimizing their app for inference speed. Different implementations may have different levels of optimization.
