### ISSUE TITLE
How to move a label name/id rectangle to the center of the detected bounding box considering box size increasing or decreasing.

### ISSUE THREAD

**Issue by SajjadIqbal-git** [ultralytics/yolov5#8145]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

As shown in the attached images the id number is not displayed at the center of the detected boxes, it's varying the position with the bounding box size. I want to put the id number always at the center of the bounding box for all size-types of detected bounding boxes. 

![Screenshot (77)](https://user-images.githubusercontent.com/78899239/172597221-cbd3167d-60d7-4a2b-ad02-4f9eff76d11b.png)
shown
![Screenshot (78)](https://user-images.githubusercontent.com/78899239/172597238-67bca8a8-6b10-4385-92ce-811c1d70d8cc.png)

### Additional

  def box_label(self, box, label='', color=(128, 128, 128), txt_color=(255, 255, 255)):
        # Add one xyxy box to image with label
        if self.pil or not is_ascii(label):
            self.draw.rectangle(box, width=self.lw, outline=color)  # box
            if label:
                w, h = self.font.getsize(label)  # text width, height
                outside = box[1] - h >= 0  # label fits outside box
                self.draw.rectangle(
                    (box[0], box[1] - h if outside else box[1], box[0] + w + 1,
                     box[1] + 1 if outside else box[1] + h + 1),
                    fill=color,
                )
                # self.draw.text((box[0], box[1]), label, fill=txt_color, font=self.font, anchor='ls')  # for PIL>8.0
                self.draw.text((box[0], box[1] - h if outside else box[1]), label, fill=txt_color, font=self.font)
        else:  # cv2
            p1, p2 = (int(box[0]), int(box[1])), (int(box[2]), int(box[3]))
            cv2.rectangle(self.im, p1, p2, color, thickness=self.lw, lineType=cv2.LINE_AA)
            if label:
                pnew =  int((box[2] + box[0])/2)
                tf = max(self.lw - 1, 1)  # font thickness
                w, h = cv2.getTextSize(str(label), 0, fontScale=self.lw / 3, thickness=tf)[0]  # text width, height
                outside = p1[1] - h >= 3
                p2 = pnew + w, p1[1] - h - 3 if outside else p1[1] + h + 3
                cv2.rectangle(self.im, (pnew , int(box[1])), p2, color, -1, cv2.LINE_AA)  # filled
                cv2.putText(self.im,
                            str(label), (pnew, p1[1] - 2 if outside else p1[1] + h + 2),
                            0,
                            self.lw / 3,
                            txt_color,
                            thickness=tf,
                            lineType=cv2.LINE_AA)

**Comment by mansi733** [comment]
@SajjadIqbal-git Did you find any solution?
Do you know how to print labels inside the bounding box using plot.py?
