### ISSUE TITLE
EdgeTPU HIB error / stability

### ISSUE THREAD

**Issue by keesschollaart81** [ultralytics/yolov5#8147]
### Bug

It seems that a YoloV5 exported EdgeTPU suffers from stability issues, at least on their Coral dev boards. After some time, the driver reports an 'HIB' error and then hangs without 'our code' being able to recover.

There is already an open issue on their repo: https://github.com/google-coral/pycoral/issues/65

Their support engineer states the following in my support request thread:

> As per feedback from the internal team there is no tweak we can do here to bypass HIB error. Only solution here is either to reduce the model input size or switch to different model to run on Dev Board. HIB error is mostly related to stress and heat due to extensive i/o operations.

This makes me sad as the exported model seems to adhere to all technical requirements. My question is if others also run into this? And/or if you have suggestions for a solution (other than lowering the input resolution, as proposed by Google). 

### Environment

- YoloV5v6.1
- Any Google Coral Dev board (and also the CRL-G18U-P3DF)
- Vanilla mendel 20211117215217

### Minimal Reproducible Example

- Brand new Coral board 1gb or 4gb
- Proper adapter with 5v/3a
- Flashed with enterprise-eagle-flashcard-20211117215217.zip
- Configure it to connect to wifi via MDT shell and connect via SSH
- `sudo apt-get update && sudo apt-get dist-upgrade`
- Reboot

Export YoloV5s to 640x480
`export.py --weights "yolov5s.pt" --imgsz 480 640 --batch 1 --include edgetpu`

Use Python test script as provided by Google support engineer:
https://github.com/hjonnala/snippets/blob/main/hib_test.py

This will consistently yield in this error after a few 100s or sometimes 1000s of inferences:

```
E driver/mmio_driver.cc:254] HIB Error. hib_error_status = 0000000000000008, hib_first_error_status = 0000000000000008
E driver/mmio_driver.cc:254] HIB Error. hib_error_status = 0000000000000008, hib_first_error_status = 0000000000000008
```

### Additional

Feel free to close this right away as I don't expect a(n immediate) solution from your side. I though it make sense to document my findings here, maybe for others/reference.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@keesschollaart81 most small devices like iPhones use thermal throttling to reduce energy usage on high intensity tasks like continuous inference over many minutes. If Google can't solve the problem themselves you may be able to mitigate by waiting between inferences or using a smaller model at a smaller image size, i.e. YOLOv5n at 320

**Comment by keesschollaart81** [comment]
Reducing model size indeed seems to help. Still sad to see the device is able to run this model but, -due to some driver IO/heat handling- the process hangs (instead of it being a transient error). 

I'm also curious to hear if others experience this as well as I see in quite some people reporting in this repo that they are exporting the S model with a ~512 input-size for EdgeTPU. Running continuously is for a few minutes is something I expect most people will do..!?

**Comment by glenn-jocher** [comment]
@keesschollaart81 it's unfortunate that the driver IO/heat handling leads to this issue. Regarding others' experiences, I'd recommend checking the GitHub discussions and perhaps starting a thread on the topic to gather community insights. Understanding others' experiences can often shed light on potential workarounds or ways to optimize the setup for stability. Thank you for your diligence in reporting and documenting your findings!
