### ISSUE TITLE
How to print label inside the bounding box?

### ISSUE THREAD

**Issue by mansi733** [ultralytics/yolov5#8148]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to print labels inside the bounding box, how can I achieve that using detect.py or plot.py?

**Comment by glenn-jocher** [comment]
@mansi733 to print labels inside the bounding box, you can use the --hide-labels argument in detect.py or plot.py. This will display the labels within the bounding boxes. You can find more details in the documentation at https://docs.ultralytics.com/yolov5/. Let me know if you need further assistance!
