### ISSUE TITLE
_pickle.UnpicklingError: could not find MARK

### ISSUE THREAD

**Issue by Lee6285** [ultralytics/yolov5#8150]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

![image](https://user-images.githubusercontent.com/105197889/172612849-361f15d6-99cf-47d8-9d82-8b02f7a09ceb.png)
![image](https://user-images.githubusercontent.com/105197889/172612937-87a90792-5acc-4042-a0a7-825efe558738.png)

### Environment

-YOLOv5
-OS: windows
-Python:3.8.0

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@hljulmf your folder says YOLOv5-5.0. Can you check if you're on the latest version and also provide the command to reproduce this bug?
