### ISSUE TITLE
Tools for cropping training data/whats your favorite ancillary toolchains for yolo data sets?

### ISSUE THREAD

**Issue by rlewkowicz** [ultralytics/yolov5#8152]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm just a hobbyist, and I played a lot with yolov3 a couple years ago, and I'm getting back into the space now. Unfortunately, over time, the search results for many things related to yolo have become extremely polluted. Making it difficult to find valid toolchains.

I used to have a toolchain that would among other things crop images and adjust the bounding boxes BEFORE training (plenty of answered questions and repos for cropping post training). I cannot find that anymore. 

Maybe it's google tailoring search results, but the majority of yolo searches these days will bring you to this project. I think this is a good place to ask. What's your favorite tool chains for yolo datasets?

**Comment by glenn-jocher** [comment]
@rlewkowicz typically might be something like upload data and annotate with Roboflow, train/val/[export](https://docs.ultralytics.com/yolov5/tutorials/model_export) with YOLOv5, log training with W&B/TensorBoard, Deploy is a bit more open and depends on your use case, but there are many tools there also like deci.ai, neural magic, triton server etc.
