### ISSUE TITLE
Running iDetection over captured screen

### ISSUE THREAD

**Issue by AlexandrIotko3Shape** [ultralytics/yolov5#8153]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,

I have a custom app without source code showing adds and would like to run my own yolov5 model using iDetection (or modified version of it) over a "captured" screen while the application is running.

Could you please advice the best way how to do?

**Comment by glenn-jocher** [comment]
@AlexandrIotko3Shape yes, you can train and deploy custom YOLOv5 models to iOS and Android using Ultralytics HUB https://ultralytics.com/hub
