### ISSUE TITLE
YOLOv5 Real Time Detection With OpenVINO

### ISSUE THREAD

**Issue by ConorHackett98** [ultralytics/yolov5#8154]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, 

I've recently started using YOLOv5 and I have been trying to perform real time object detection using OpenVINO on a Movidius Neural Compute Stick 2.

For practice I've used the YOLOv5 tutorial.ipynb to train a custom dataset on the coco128 dataset.  I've tried running this model on the YOLOv5 detect.py program and it seems to work perfectly.

I then export the model to OpenVINO format which succeeds.  The main issue appears when I try and run real time object detection with OpenVINO.  I am using a sample OpenVINO program to initiate the detection (https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/401-object-detection-webcam).  The sample program used the ssdlite_mobilenet_v2 model which has an input of (B, H, W, C) and an output of (1, 1, 100, 7).  The custom model I have trained using the YOLOv5 tutorial.ipynb has an input of (B, C, H, W) and an output of (1, 25200, 85).

I was wondering if there is any way for me to edit the trained model produced by YOLOv5 to produce a similar input and output as to what is expected by the OpenVINO real time detection program.

Thank you.

**Comment by glenn-jocher** [comment]
@ConorHackett98 we don't have an official NCS2 demo, but you can use exported OpenVINO models with YOLOv5 using the provided Usage examples shown upon export completion:

<img width="713" alt="Screenshot 2022-06-09 at 09 50 38" src="https://user-images.githubusercontent.com/26833433/172794166-b6dc659e-f9a7-45ac-965e-fa2e64fdae0b.png">

**Comment by ConorHackett98** [comment]
Thank you for your quick response.  

I think to run detection with a NCS2 I must use the OpenVINO Runtime Core to import a model, so the runtime device can be set to the NCS2.

The provided detect.py program runs perfectly with my computer's CPU and GPU, but I don't think I can set the runtime device to be a NCS2 using detect.py.

**Comment by glenn-jocher** [comment]
@ConorHackett98 maybe you can customize the code then when loading the OpenVINO model here:
https://github.com/ultralytics/yolov5/blob/6adc53ba5fd7e87002ef80603f3fcf1c6ace72f5/models/common.py#L361-L373

**Comment by ConorHackett98** [comment]
That looks very promising, thank you very much.  I'll check it out as soon as I can get my hands on the NCS2 again and I'll let you know what the results are.  Thank you again!

**Comment by ConorHackett98** [comment]
> @ConorHackett98 maybe you can customize the code then when loading the OpenVINO model here:
> 
> https://github.com/ultralytics/yolov5/blob/6adc53ba5fd7e87002ef80603f3fcf1c6ace72f5/models/common.py#L361-L373

Sorry for taking so long to respond but I've finally been able to use the NCS2 again, and setting the device name to 'MYRIAD' seems to do the trick perfectly.  Thank you very much!  

Altered Line 369 of common.py:
```Python
executable_network = ie.compile_model(model=network, device_name="MYRIAD") 
```
