### ISSUE TITLE
about training size and test size

### ISSUE THREAD

**Issue by SISTMrL** [ultralytics/yolov5#816]
## ❔Question
In the training process, I use the mosaic, the input size is 640*640. But in test process, it rectangular test, and I read the letterbox function, I find the test input size is:  the longer size is 640, and the shorter side is padded to minimal multiply of 32. So if the test size is 640*320 or 640*352 or 640*384, they have a huge difference compared to training input size, and I don't use multisize traing. 

So whether the test part will be affected? Thanks very much

**Comment by buimanhlinh96** [comment]
Due to the repo, you can use --rect, but actually i dont still control this parameter
