### ISSUE TITLE
Latency when using a http or rtsp Stream as input

### ISSUE THREAD

**Issue by Kabuc0** [ultralytics/yolov5#8160]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,
I have a video stream which is "saved" to an http page via the mjpg streamer. On the http side the video runs almost without delay. Also when I open the video via opencv the delay is almost non-existent. 
But when I open the "http video" in yolov5, I suddenly have about 5 seconds delay and slight jerks. 
When I connect the webcam directly, both lag and judder are gone. 
I have already tested different models (much smaller) without improvement. I have also tested the measures mentioned in this thread (https://github.com/ultralytics/yolov5/issues/4465). Also without improvement.
Does anyone have an idea what else I can test, or is it just always with videos over http with such a strong delay to expect?

**Comment by glenn-jocher** [comment]
@Kabuc0 StreamLoader is here, you might start by taking a look and debugging:
https://github.com/ultralytics/yolov5/blob/6e4661773e08aee5e9673f68aacc1817b8a6fca9/utils/dataloaders.py#L299-L386

**Comment by Kabuc0** [comment]
So I have changed/adjusted some variables but unfortunately have not been able to achieve any improvement. Do you have any other idea what can be adjusted? 
Or does an http stream simply have more delay?

**Comment by glenn-jocher** [comment]
@Kabuc0 stream shouldn't have any delay as far as I know. If you can create a minimum reproducible example we could take a look.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by Kabuc0** [comment]
I am running following code to start the http stream with mjpg streamer:
user@faps:~/mjpg-streamer-master/mjpg-streamer-experimental$ **./mjpg_streamer -i "input_uvc.so -d /dev/video2 -r 1920x1080"**
The stream itself is running fine with no delay. 
And than I run the newest yolov5 with no weights defined. Just the normal model. Also tried out my own models with no difference.
user@faps:/yolov5-org$ **python detect.py --source http://**

user@faps:~/yolov5-org$ python detect.py --source http://192.168/?action=stream_0
detect: weights=yolov5s.pt, source=http://192.168/?action=stream_0, data=data/coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False
YOLOv5 🚀 v6.1-246-g2dd3db0 Python-3.8.10 torch-1.11.0+cu113 CUDA:0 (GeForce GTX 1050 Ti, 4040MiB)

Fusing layers... 
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients
1/1: http://192.168/?action=stream_0...  Success (inf frames 1920x1080 at 25.00 FPS)

**Comment by glenn-jocher** [comment]
@Kabuc0 I'm unable to reproduce with your command:
<img width="963" alt="Screen Shot 2022-06-10 at 2 55 02 PM" src="https://user-images.githubusercontent.com/26833433/173068874-699a521b-d0aa-4178-91d2-c1c255ef433b.png">

**Comment by Kabuc0** [comment]
ohso yes, have not written the complete ip address in, because I did not want that all possible people then have access to the stream. Sorry, I should have written in. But you have to be in the same network to access the stream. 
Have you ever open a rtsp or http stream and tested yolov5 on it?

**Comment by Kabuc0** [comment]
But there is a quick way to generate your own mjpg http stream:

1. sudo apt-get install cmake libjpeg8-dev
2. wget https://github.com/jacksonliam/mjpg-streamer/archive/master.zip
3. unzip master.zip
4. cd mjpg-streamer-master
5. cd mjpg-streamer-experimental
6. make
7. sudo make isntall
8. and then just type in the mjpg-experimental directory: mjpg_streamer -i "input_uvc.so -d /dev/video0 (your webcam) -r 1920x1080 (your res.)
9. you see your stream at: http://your_ip_adresse:8080/?action=stream

**Comment by Kabuc0** [comment]
I now also tested it with FFMPEG- Streamer (https://trac.ffmpeg.org/wiki/StreamingGuide) and this rtsp-simple-server (https://github.com/aler9/rtsp-simple-server#from-a-webcam).
I ran yolov5 with both the http stream from mjpg streamer and the rtsp stream from ffmpeg streamer at the same time and noticed, while the delay of the mjpeg streamer stayed the same at around 3 sec. the delay of the ffmpeg streamer went higher the longer the stream played.

**Comment by glenn-jocher** [comment]
@Kabuc0 thanks for the update. If you'd like to see fixes or features in YOLOv5 the easiest way is to submit a PR with your improvement, and then supply before and after results to quantify the effect of your changes. Thank you!

**Comment by Kabuc0** [comment]
I thought you normally shouldn't have any delay or just a bit delay. Isn't that why a PR would be the wrong thing to do?

**Comment by glenn-jocher** [comment]
@Kabuc0 since this isn't a domain I specialize in I can't really help too much here, but if you think something is incorrect and want to implementa a fix please submit a PR to help future users in the same position, thank you!

**Comment by abuzahid** [comment]
https://github.com/ultralytics/yolov5/blob/6e4661773e08aee5e9673f68aacc1817b8a6fca9/utils/dataloaders.py#L359
Comment this line.

**Comment by glenn-jocher** [comment]
@abuzahid thanks for the suggestion! The YOLOv5 community greatly benefits from user feedback and contributions. If you feel this change could benefit the project, we encourage you to submit a pull request with your proposed modification. Thank you for your support!
