### ISSUE TITLE
The meaning of "number" in <model>.yaml

### ISSUE THREAD

**Issue by bryanbocao** [ultralytics/yolov5#8166]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I tried to understand the meaning of number,

https://github.com/ultralytics/yolov5/blob/6e4661773e08aee5e9673f68aacc1817b8a6fca9/models/yolo.py#L267

In the yolov5 backbone example
https://github.com/ultralytics/yolov5/blob/master/models/yolov5n.yaml#L15

```
# YOLOv5 v6.0 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [64, 6, 2, 2]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C3, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 6, C3, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, C3, [512]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 3, C3, [1024]],
   [-1, 1, SPPF, [1024, 5]],  # 9
  ]
```

If I change [-1, 1, Conv, [64, 6, 2, 2]] to [-1, 3, Conv, [64, 6, 2, 2]], will it create 3 convolutinal layers?
Does [-1, 6, C3, [256]] mean that C3 is repeated for 6 times?

Thanks!

**Comment by glenn-jocher** [comment]
@bryanbo-cao number of times a layer is repeated
