### ISSUE TITLE
Wandb sweeps problem

### ISSUE THREAD

**Issue by yolor2** [ultralytics/yolov5#8169]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

i am running the code with the agent after initialzing the sweeps.yaml but i am geeting an error:
sweep.py: error: unrecognized arguments: --cls=0.22966661689425488 --cls_pw=1.8666581388046093 --degrees=0 --fl_gamma=0 --fliplr=0.047653403328209464 --flipud=0 --giou=0.0890054158230999 --hsv_h=0.01490101123080308 --hsv_s=0.33098286881564587 --hsv_v=0.43957982147719454 --iou_t=0.14376667610237656 --lr0=0.02633093674120037 --mixup=0.2637779690656522 --momentum=0.9487642921230668 --mosaic=1 --obj=0.7566136527038402 --obj_pw=0.754483359425184 --perspective=0 --scale=0.521571743441418 --shear=0 --translate=0.3139249656258278 --warmup_epochs=4 --weight_decay=0.0005422626635021583
so what could be the error? and how to avoid it. please let me know.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@yolor2 are you using the default sweeps.yaml file provided in the repo?
