### ISSUE TITLE
Return only one element, but the one with the highest score.

### ISSUE THREAD

**Issue by MasIgor** [ultralytics/yolov5#8171]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello!

For my custom application, I would need Yolo to return only one element per picture. that is easily done by setting `max_det=1,  # maximum detections per image`

It turns out tough, that it is returning the first it finds, or something along those lines. I would need it to return the one with the highest score of all the found classes.

Can this be done?
If yes, how?

Thank you!

**Comment by glenn-jocher** [comment]
@tanzerlana detections are sorted by confidence before being clipped by max_det, so it will return maximum confidence detections first
