### ISSUE TITLE
Error when running detect.py cv2.error: OpenCV(4.5.5) 

### ISSUE THREAD

**Issue by edehino** [ultralytics/yolov5#8176]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

```
File "D:\path\yolov5\utils\general.py", line 1012, in imshow
    imshow_(path.encode('unicode_escape').decode(), im)
cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1268: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'
```

### Environment

- YOLO: YOLOv5
- OS: Windows 10
-Python: 3.9

### Minimal Reproducible Example

Just clone the new repository or use git pull and try to detect any image/video. Tried both but I am getting the same error

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by edehino** [comment]
pip uninstall opencv-python-headless -y 

pip install opencv-python --upgrade

worked for me btw

**Comment by glenn-jocher** [comment]
@edehino thanks for the tip! I'll try this in the docker image to see if it can resolve the cv2 4.6 errors I've been seeing

**Comment by glenn-jocher** [comment]
@edehino doesn't affect Docker image as if I try to uninstall I get:
```
WARNING: Skipping opencv-python-headless as it is not installed.
```

**Comment by Manpreeth3126** [comment]
same problem

**Comment by glenn-jocher** [comment]
Hello! It looks like you're experiencing a similar issue. Could you please try the solution provided by @Manpreeth3126? 

```bash
pip uninstall opencv-python-headless -y 
pip install opencv-python --upgrade
```

This has helped others with the same problem. If the issue persists after trying this, please let us know. 😊
