### ISSUE TITLE
AssertionError: 1/1: 0... Failed to open 0

### ISSUE THREAD

**Issue by deb-cod** [ultralytics/yolov5#8180]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Fusing layers... 
YOLOv5x summary: 444 layers, 86173414 parameters, 0 gradients
WARNING: Environment does not support cv2.imshow() or PIL Image.show() image displays
cv2.imshow() is disabled in Google Colab environments
[ WARN:0] global /io/opencv/modules/videoio/src/cap_v4l.cpp (802) open VIDEOIO ERROR: V4L: can't open camera by index 0
Traceback (most recent call last):
  File "/content/yolov5/detect.py", line 252, in <module>
    main(opt)
  File "/content/yolov5/detect.py", line 247, in main
    run(**vars(opt))
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/content/yolov5/detect.py", line 100, in run
    dataset = LoadStreams(source, img_size=imgsz, stride=stride, auto=pt)
  File "/content/yolov5/utils/dataloaders.py", line 325, in __init__
    assert cap.isOpened(), f'{st}Failed to open {s}'
AssertionError: 1/1: 0... Failed to open 0

### Environment

detect: weights=['/content/yolov5/best.pt'], source=0, data=/content/yolov5/data/fire.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=yolov5/runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False
YOLOv5 🚀 v6.1-251-gc23a441 Python-3.7.13 torch-1.11.0+cu113 CUDA:0 (Tesla P100-PCIE-16GB, 16281MiB)

I ran in terminal in Colab... still getting the same problem

### Minimal Reproducible Example

I ran in terminal in Colab... still getting the same problem

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@deb-cod webcam inference is only supported on local devices. I’ll add a TODO to improve error reporting on this to make it clearer for users

**Comment by glenn-jocher** [comment]
@deb-cod good news 😃! Your original issue may now be fixed ✅ in PR #8209. This PR adds improved error reporting to help users understand that webcam inference with --source 0 must be run in a local environment with access to a webcam, not on remote environments like Colab/Kaggle.

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by banana7778** [comment]
same question..didU solved it？

**Comment by sloika** [comment]
I try to use it locally on my machine and it still has the same bug. Already up to date repo.

**Comment by glenn-jocher** [comment]
Webcam inference works correctly:

<img width="1416" alt="Screenshot 2022-08-29 at 19 32 40" src="https://user-images.githubusercontent.com/26833433/187262838-4436428a-d7b7-4a1e-9891-b225ac1e15a7.png">
