### ISSUE TITLE
onnx converted model throws error during detection

### ISSUE THREAD

**Issue by lizozom** [ultralytics/yolov5#8181]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

I have followed the `YOLOv5-Custom-Training` tutorial and trained a model to detect some custom objects.
The object works properly detecting objects.

I then exported the model to `onnx` using the following command:
`python export.py --include onnx --weight ./runs/train/exp/weights/best.pt --data {dataset.location}/data.yaml --img 640`

The exported `onnx` model also properly detects objects.

I then took the [`onnxruntime-nextjs-template`](https://github.com/microsoft/onnxruntime-nextjs-template) and I am trying to adjust it to run my YOLO model.

I adjusted the model name and the image size in `utils/predict.ts`, and I'm getting the following error:

```
Uncaught (in promise) Error: resize (packed) does not support mode: 'nearest'
    at l (ort-web.min.js?f1d4:formatted:18144:282536)
    at Object.get (ort-web.min.js?f1d4:formatted:18144:281666)
    at t.WebGLInferenceHandler.executeProgram (ort-web.min.js?f1d4:formatted:18144:209391)
    at t.WebGLInferenceHandler.run (ort-web.min.js?f1d4:formatted:18144:209690)
    at Object.t.resize [as impl] (ort-web.min.js?f1d4:formatted:18144:281598)
    at eval (ort-web.min.js?f1d4:formatted:18144:350066)
    at t.Profiler.event (ort-web.min.js?f1d4:formatted:18144:365260)
    at eval (ort-web.min.js?f1d4:formatted:18144:350026)
```

Am I exporting the model incorrectly?

### Environment

YOLOv5, Ubuntu 20.04, Javscript

### Minimal Reproducible Example

https://github.com/lizozom/onnxruntime-nextjs-template

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@lizozom yes if detect.py runs your ONNX model correctly then it's exported and running correctly.

For errors generated by 3rd party runtimes/tools please raise these directly with their respective authors.

Benchmarks are part of our daily CI BTW, the latest validation results including ONNX are here:
https://github.com/ultralytics/yolov5/runs/6853482428?check_suite_focus=true
<img width="897" alt="Screenshot 2022-06-13 at 13 32 43" src="https://user-images.githubusercontent.com/26833433/173344741-1798470a-f3b0-45f4-ad53-98af2671dc04.png">
