### ISSUE TITLE
Overlapping boxes in detect.py

### ISSUE THREAD

**Issue by Nahrain1** [ultralytics/yolov5#8182]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Dear community members, 
when trying to get the total used area for bounding boxes in my image I tried subtracting the intersecting boxes so that I have my wanted result without duplicate areas. When testing it does not seem to work. I have some offset value of  3584 when my boxes do obviously not intersect. Here are the code lines that I added to detect.py file.
Do kindly correct me if you see the problem in my code.
 
![intersection_detect](https://user-images.githubusercontent.com/95288759/173248727-7902a5e7-e528-4449-a004-bcd28b7064e3.PNG)

**Comment by glenn-jocher** [comment]
@Nahrain1 NMS function offsets boxes by class as well to allow passing all boxes to torch NMS function togethor.
