### ISSUE TITLE
Yolov5 breaks after training 'NoteType' object has no attribute '_free_weak_ref'

### ISSUE THREAD

**Issue by jfarjona** [ultralytics/yolov5#8183]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Validation

### Bug

Validating runs\train\exp2\weights\best.pt...
Fusing layers...
custom_YOLOv5s summary: 213 layers, 7055974 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 241/241 [00:12<00:00, 20.05it/s]
                 all        482        919      0.794      0.465      0.536      0.397
         fairycircle        482        919      0.794      0.465      0.536      0.397
Results saved to runs\train\exp2
Exception ignored in: <function StorageWeakRef.__del__ at 0x000002251A5BD2D0>
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\torch\multiprocessing\reductions.py", line 36, in __del__
  File "C:\Python310\lib\site-packages\torch\storage.py", line 520, in _free_weak_ref
Exception ignored in: <function StorageWeakRef.__del__ at 0x00000187B0CBD2D0>
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\torch\multiprocessing\reductions.py", line 36, in __del__
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
  File "C:\Python310\lib\site-packages\torch\storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x000002251A5BD2D0>
Exception ignored in: <function StorageWeakRef.__del__ at 0x00000187B0CBD2D0>
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\torch\multiprocessing\reductions.py", line 36, in __del__
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\torch\storage.py", line 520, in _free_weak_ref
  File "C:\Python310\lib\site-packages\torch\multiprocessing\reductions.py", line 36, in __del__
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
  File "C:\Python310\lib\site-packages\torch\storage.py", line 520, in _free_weak_ref
Exception ignored in: <function StorageWeakRef.__del__ at 0x00000187B0CBD2D0>
... (idem by 100s of times) ...
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\torch\multiprocessing\reductions.py", line 36, in __del__
  File "C:\Python310\lib\site-packages\torch\storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'

### Environment

YOLOv5  v6.1-251-gc23a441 Python-3.10.2 torch-1.11.0+cu113 CUDA:0 (NVIDIA GeForce GTX 950, 2048MiB)
Package                 Version
----------------------- --------------------
absl-py                 1.1.0
asttokens               2.0.5
backcall                0.2.0
cachetools              5.2.0
certifi                 2022.5.18.1
charset-normalizer      2.0.12
colorama                0.4.4
cycler                  0.11.0
decorator               5.1.1
executing               0.8.3
fonttools               4.33.3
google-auth             2.7.0
google-auth-oauthlib    0.4.6
grpcio                  1.46.3
idna                    3.3
ipython                 8.4.0
jedi                    0.18.1
kiwisolver              1.4.2
Markdown                3.3.7
matplotlib              3.5.2
matplotlib-inline       0.1.3
numpy                   1.22.4
oauthlib                3.2.0
opencv-python           4.6.0.66
packaging               21.3
pandas                  1.4.2
parso                   0.8.3
pickleshare             0.7.5
Pillow                  9.1.1
pip                     22.1.2
prompt-toolkit          3.0.29
protobuf                3.19.4
psutil                  5.9.1
pure-eval               0.2.2
pyasn1                  0.4.8
pyasn1-modules          0.2.8
Pygments                2.12.0
pyparsing               3.0.9
python-dateutil         2.8.2
pytz                    2022.1
PyYAML                  6.0
requests                2.28.0
requests-oauthlib       1.3.1
rsa                     4.8
scipy                   1.8.1
seaborn                 0.11.2
setuptools              58.1.0
six                     1.16.0
stack-data              0.2.0
tensorboard             2.9.1
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.1
thop                    0.1.0.post2206102148
torch                   1.11.0+cu113
torchaudio              0.11.0+cu113
torchvision             0.12.0+cu113
tqdm                    4.64.0
traitlets               5.2.2.post1
typing_extensions       4.2.0
urllib3                 1.26.9
wcwidth                 0.2.5
Werkzeug                2.1.2
wheel                   0.37.1

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 516.01       Driver Version: 516.01       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0  On |                  N/A |
|  0%   46C    P8    13W /  99W |    658MiB /  2048MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

### Minimal Reproducible Example

python train.py --img 512 --batch 1 --epochs 150 --data ../data.yaml --cfg ../custom_yolov5s.yaml --weights yolov5s.pt

train: weights=yolov5s.pt, cfg=../custom_yolov5s.yaml, data=../data.yaml, hyp=data\hyps\hyp.scratch-low.yaml, epochs=150, batch_size=1, imgsz=512, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, noplots=False, evolve=None, bucket=, cache=None, image_weights=False, device=, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=8, project=runs\train, name=exp, exist_ok=False, quad=False, cos_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest

I have 1646 images, all 512x512 px.  17 labels.

### Additional

hyperparameters: lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0
Weights & Biases: run 'pip install wandb' to automatically track and visualize YOLOv5  runs (RECOMMENDED)
TensorBoard: Start with 'tensorboard --logdir runs\train', view at http://localhost:6006/

                 from  n    params  module                                  arguments
  0                -1  1      3520  models.common.Conv                      [3, 32, 6, 2, 2]
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]
  2                -1  1     18816  models.common.C3                        [64, 64, 1]
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]
  4                -1  2    115712  models.common.C3                        [128, 128, 2]
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]
  6                -1  3    625152  models.common.C3                        [256, 256, 3]
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]
  8                -1  1   1182720  models.common.C3                        [512, 512, 1]
  9                -1  1    656896  models.common.SPPF                      [512, 512, 5]
 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 12           [-1, 6]  1         0  models.common.Concat                    [1]
 13                -1  1    361984  models.common.C3                        [512, 256, 1, False]
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 16           [-1, 4]  1         0  models.common.Concat                    [1]
 17                -1  1     90880  models.common.C3                        [256, 128, 1, False]
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]
 19          [-1, 14]  1         0  models.common.Concat                    [1]
 20                -1  1    296448  models.common.C3                        [256, 256, 1, False]
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]
 22          [-1, 10]  1         0  models.common.Concat                    [1]
 23                -1  1   1182720  models.common.C3                        [512, 512, 1, False]
 24      [17, 20, 23]  1     59334  models.yolo.Detect                      [17, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
custom_YOLOv5s summary: 270 layers, 7065478 parameters, 7065478 gradients

Transferred 342/349 items from yolov5s.pt
AMP: checks passed
Scaled weight_decay = 0.0005
optimizer: SGD with parameter groups 57 weight (no decay), 60 weight, 60 bias

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@jfarjona This is a Pytorch problem. The fix has been merged in pytorch release branch here -> https://github.com/pytorch/pytorch/pull/79315 This should be available in the next stable release.
But this should not cause errors during the training. As you can see in your traceback this happens after training successfully finishes.

**Comment by jfarjona** [comment]
Thank you very much @AyushExel for your quick answer!

**Comment by QuarTerll** [comment]
> @jfarjona This is a Pytorch problem. The fix has been merged in pytorch release branch here -> [pytorch/pytorch#79315](https://github.com/pytorch/pytorch/pull/79315) This should be available in the next stable release. But this should not cause errors during the training. As you can see in your traceback this happens after training successfully finishes.

@AyushExel 
So, it has no influence on any results? 

As for yolov5 users for now, 
1. We just need to ignore it and wait for the new pytorch release.
2. Or, if we can not ignore it, we just downgrade the pytorch version.

Do I understand it correctly? :）

**Comment by glenn-jocher** [comment]
@QuarTerll ignore it, no effect of results.
