### ISSUE TITLE
running default yolov5 on jetson nano, but the fps is just under 1 fps

### ISSUE THREAD

**Issue by HuumbleBee** [ultralytics/yolov5#8184]
Helo, i have jetson nano 2gb, i try to run default yolov5 but the fps is just under 1 fps on it. what i should do to improve it?  i also plan to use custom dataset in the future, can you give me some advice to gain best result when train dataset? thanks

**Comment by AyushExel** [comment]
@HuumbleBee You need to export the model to tensorRT format for running inference on it. Here's the command in for converting yolov5s model to TRT:
`python export.py --weights yolov5s.pt --include engine`
You can then use the exported model for inference. Let me know if you have any questions.

**Comment by HuumbleBee** [comment]
Thanks, i will try it asap

**Comment by SkalskiP** [comment]
Hi, @AyushExel sorry to interrupt the conversation here, but:
1. Do you maybe have some benchmarks comparing YOLOv5 performance between Torch and TRT?
2. Do I still need to have torch and torch vision installed in my Python environment if I infer using TRT?

**Comment by glenn-jocher** [comment]
@SkalskiP yes GPU benchmarks on a few systems are available here:
https://github.com/ultralytics/yolov5/pull/6963

TRT inference with YOLOv5 detect.py/val.py/hub uses torch but there is a torch-free export PR open here you might be able to use:
https://github.com/ultralytics/yolov5/pull/7736

**Comment by SkalskiP** [comment]
Hi, @glenn-jocher thanks for the response! So it seems to me that we are getting a consistent 3-5x boost across all tested platforms. Shame tho... that there are no benchmarks for Jetson Xavier / Nano. 

1. So as it is right now, the inference is done by TRT, but NMS and other post-processing are done using torch?
2. Does the pip package support TRT inference?

**Comment by glenn-jocher** [comment]
@SkalskiP no we don't have any edge device benchmarks other than the iOS/Android app, but this is just because we don't have any edge devices to test on nor anyone in place to manage/verify/benchmark edge devices, i.e. Edge TPU, NCS2, RPi, Jetson etc. For Xavier/Nano specifically I think you need to export and benchmark on the same device too.

Yes torch is mainly just used for NMS on TRT models. The pip package is not maintained adequately unfortunately so I think it may be a bit behind master in terms of features. I don't know if supports TRT, but we do have plans to launch a more official and maintained pip package soon.

**Comment by SkalskiP** [comment]
@glenn-jocher I could do some benchmarking on Jetson Xavier, I'd just need some instructions on how to do it.

**Comment by glenn-jocher** [comment]
@SkalskiP I've never done it myself, but I think that the jetson docker images are the best way to get started quickly:
https://developer.nvidia.com/embedded/learn/tutorials/jetson-container

**Comment by SkalskiP** [comment]
@glenn-jocher aaa you misunderstood my question. 😊 I'm not asking about the Jetson Xavier instructions. I have that already figured out, I actually managed to set it up with python 3.8 which I guess used to be a problem? I remember that only 3.6 was supported. 

I meant instructions for benchmarking. 😉

**Comment by glenn-jocher** [comment]
@SkalskiP oh the benchmarking is simple, just run python utils/benchmarks.py to benchmark all formats. 

Try to install all dependencies before running. Some will auto install, others like TF will not.

**Comment by redhair-vibing** [comment]
> Helo, i have jetson nano 2gb, i try to run default yolov5 but the fps is just under 1 fps on it. what i should do to improve it? i also plan to use custom dataset in the future, can you give me some advice to gain best result when train dataset? thanks

which jetpack version do you installed on jetson nano ? I tried complied from source and docker run ,both failed .

**Comment by glenn-jocher** [comment]
@chunxiao365 hi there! For Jetson Nano, optimizing YOLOv5 performance involves ensuring you have the correct JetPack version, using the latest YOLOv5 version, and exploring torch/tensorRT model export options for improved inference speeds. For custom dataset training, refer to the Ultralytics Docs for guidance, and ensure your dataset is diverse and well-labeled. Good luck!
