### ISSUE TITLE
Must the yolov5 input_width == input_height? 

### ISSUE THREAD

**Issue by sean-wade** [ultralytics/yolov5#8194]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

My dataset's ratio is 1:2, and I think padding value is a waste of time in training and inference.

So is there any way to set the model input_size like (960, 480)?

**Comment by glenn-jocher** [comment]
@sean-wade YOLOv5 already uses rectangular inference automatically. If you want 960x480 you just pass the long side:
```
python detect.py --img 960
```
