### ISSUE TITLE
 Orientation detection

### ISSUE THREAD

**Issue by Arnaud-Saunier** [ultralytics/yolov5#8196]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,

I am currently using yolov5s to detect simple shapes (triangle, tube, square) and I use this program to test my model in real time.

    model = torch.hub.load('ultralytics/yolov5', 'custom', path='yolov5/runs/train/exp74/weights/last.pt',
                           force_reload=True)   
    cap = cv2.VideoCapture(0)                   
    while cap.isOpened():
        ret, frame = cap.read()                 

        results = model(frame)                  

        cv2.imshow('YOLO', np.squeeze(results.render()))     

        if cv2.waitKey(10) & 0xFF == ord('q'):
            break
    cap.release()
    cv2.destroyAllWindows()

I would like to be able to add the orientation(degree) of the object in relation to the image. 

Does yolov5 have a function to do this?

**Comment by glenn-jocher** [comment]
@Arnaud-Saunier see https://github.com/hukaixuan19970627/yolov5_obb for an example of oriented box YOLOv5

**Comment by Arnaud-Saunier** [comment]
Thank you !

**Comment by glenn-jocher** [comment]
@Arnaud-Saunier you're welcome! If you have any more questions, feel free to ask. Good luck with your project!
