### ISSUE TITLE
Alternative to implement linear layer with a variable input paramter 

### ISSUE THREAD

**Issue by Zakaria1405** [ultralytics/yolov5#8198]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi guys, 
I want to implement some linear layers in each output layer after each convulitonal layer in yolov5. The problem I'm facing is that the input image passed to my linear layer changes each image, due to the fact that yolo localization grid passes each image with a new width and height. Also, I want to train everything with my GPU, which means I need to intialize my linearity layers in the init function of my class:
[https://forums.pytorchlightning.ai/t/runtimeerror-but-found-at-least-two-devices-cpu-and-cuda-0/1634](url)

           ` class STN_8_8(nn.Module):
              def __init__(self, c1):
                  super(STN_8_8, self).__init__()
                  self.Linearity = nn.Sequential(
                      nn.Linear(c1*16*16, 256),
                      nn.ReLU(), 
                      nn.Linear(256, 128),
                      nn.ReLU(),
                      nn.Linear(128, 64),
                      nn.ReLU(),
                      nn.Linear(64, 32),
                      nn.ReLU(), 
                      nn.Linear(32, 6)
           
                                 )
            
            # Spatial transformer network forward function
            def forward(self, x):
                print(f'Shape just focus {x.shape}')
                
                xs = x.view(-1, x.shape[1] * x.shape[2] * x.shape[3])
                theta = self.Linearity(xs)
                x = theta.view(-1, 2, 3)
        
                return x`

The first image works fine and I have no problems. The burner size of the first image is [100, 512, 16, 16].
As soon as my model starts with the next image torch.size[100, 512, 8, 8], I get this error:
` "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\zacco\\Desktop\\Master\\Project_2022\\Project_gamma\\Ultralytics\\yolov5\\train.py\", line 677, in <module>\n",
      "    main(opt)\n",
      "  File \"C:\\Users\\zacco\\Desktop\\Master\\Project_2022\\Project_gamma\\Ultralytics\\yolov5\\train.py\", line 571, in main\n",
      "    train(opt.hyp, opt, device, callbacks)\n",
      "  File \"C:\\Users\\zacco\\Desktop\\Master\\Project_2022\\Project_gamma\\Ultralytics\\yolov5\\train.py\", line 352, in train\n",
      "    pred = model(imgs)  # forward\n",
      "  File \"c:\\Users\\zacco\\anaconda3\\envs\\pytorch\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1110, in _call_impl\n",
      "    return forward_call(*input, **kwargs)\n",
      "  File \"C:\\Users\\zacco\\Desktop\\Master\\Project_2022\\Project_gamma\\Ultralytics\\yolov5\\models\\yolo.py\", line 155, in forward\n",
      "    return self._forward_once(x, profile, visualize)  # single-scale inference, train\n",
      "  File \"C:\\Users\\zacco\\Desktop\\Master\\Project_2022\\Project_gamma\\Ultralytics\\yolov5\\models\\yolo.py\", line 179, in _forward_once\n",
      "    x = m(x)  # run\n",
      "  File \"c:\\Users\\zacco\\anaconda3\\envs\\pytorch\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1110, in _call_impl\n",
      "    return forward_call(*input, **kwargs)\n",
      "  File \"C:\\Users\\zacco\\Desktop\\Master\\Project_2022\\Project_gamma\\Ultralytics\\yolov5\\models\\common.py\", line 60, in forward\n",
      "    theta = self.Linearity(xs)\n",
      "  File \"c:\\Users\\zacco\\anaconda3\\envs\\pytorch\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1110, in _call_impl\n",
      "    return forward_call(*input, **kwargs)\n",
      "  File \"c:\\Users\\zacco\\anaconda3\\envs\\pytorch\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 141, in forward\n",
      "    input = module(input)\n",
      "  File \"c:\\Users\\zacco\\anaconda3\\envs\\pytorch\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1110, in _call_impl\n",
      "    return forward_call(*input, **kwargs)\n",
      "  File \"c:\\Users\\zacco\\anaconda3\\envs\\pytorch\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 103, in forward\n",
      "    return F.linear(input, self.weight, self.bias)\n",
      "RuntimeError: mat1 and mat2 shapes cannot be multiplied (60x86528 and 32768x256)\n"`

I was able to understand the error, but I was not able to find an idea on how to fulfill my goals with adding a linear layers and using the GPU simulstaniously. This means that I have to implement a variable input for my first linear layer

**Comment by glenn-jocher** [comment]
@Zakaria1405 it looks like the issue you're facing is due to the changing input dimensions at each image. To address this, you can dynamically calculate the input size of your linear layers based on the input dimensions at runtime. This can be achieved by computing the input size in the forward pass and updating the linear layers accordingly.

You might find the `in_features` parameter of the first linear layer helpful, as it typically represents the size of the input tensor. You can modify this value during the forward pass to match the dimensions of the input tensor.

For an example of how to achieve this, you can refer to the PyTorch documentation or some public repositories for dynamic architecture modification based on input size.

Hope this helps! If you have further questions or need more guidance, feel free to ask.
