### ISSUE TITLE
Multi-label detection on ONE bounding box

### ISSUE THREAD

**Issue by kai3316** [ultralytics/yolov5#8200]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I need to detect more than two classes in the same detection box in my project. Can I put all the information (with the same box) directly into the annotation file as follows? And Will NMS have any effect on the results?

3 0.5990566037735848 0.45 0.04009433962264151 0.07083333333333333
7 0.5990566037735848 0.45 0.04009433962264151 0.07083333333333333

Many thanks!!!

**Comment by glenn-jocher** [comment]
@kai3316 yes you can create multiple labels like this. In master there is a bug that these labels will have reduced confidence as they will each suppress the other equally but there is a PR open to address this here:
https://github.com/ultralytics/yolov5/pull/5593

**Comment by kai3316** [comment]
> @kai3316 yes you can create multiple labels like this. In master there is a bug that these labels will have reduced confidence as they will each suppress the other equally but there is a PR open to address this here: #5593

OK, Thank you for your quick reply.
