### ISSUE TITLE
Yolov5 , Internet connection

### ISSUE THREAD

**Issue by Abderrahmen33** [ultralytics/yolov5#8201]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Guys do you know how I can use Yolov5 without an internet connection?

**Comment by glenn-jocher** [comment]
@Abderrahmen33 YOLOv5 operates normally with no internet
