### ISSUE TITLE
Confusion in result after training in your linl

### ISSUE THREAD

**Issue by PraveenMNaik** [ultralytics/yolov5#8202]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Referring to the link [https://github.com/ultralytics/yolov5]
Referring to the table **Pretrained Checkpoints** for COCO dataset
Why mAP values are not going beyond 55.8 in **mAPval 0.5:0.95**
 and 72.7 in **mAPval 0.5**. But, where as  journal papers which use yolov5 able to get more of these values above 90%. Please suggest, is it possible.

**Comment by glenn-jocher** [comment]
@PraveenMNaik I would recommend you direct questions about 3rd party works to their respective authors

**Comment by PraveenMNaik** [comment]
Do you mean, with coco dataset that's the only possible result,   how abt
the precision and recall ... why was it jot considered in your page

**Comment by glenn-jocher** [comment]
mAP is an absolute metric, P and R are relative  metrics and vary with confidence level so are not used to compare different models on common datasets.
