### ISSUE TITLE
Retrieval of P, R, mAP 

### ISSUE THREAD

**Issue by cyndyNKCM** [ultralytics/yolov5#8205]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello @glenn-jocher 

Please can i retrieve the parameters P, R and mAP after the training process?

**Comment by glenn-jocher** [comment]
@cyndyNKCM val.py validates a trained model on your dataset:

python val.py —data data.yaml —weights model.pt
