### ISSUE TITLE
Use WandB with Detect.py

### ISSUE THREAD

**Issue by Vaevin** [ultralytics/yolov5#8212]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Currently, the _train.py_ script automatically starts the WandB process, and uploads useful metrics to WandB during training. Currently, there is no easy way to incorporate YOLOv5's WandB interface with it's _detect.py_ script.

### Use case

I believe it would be very useful to have access to WandB metric logging when running the _detect.py_ script to evaluate model performance (such as inference time for a single image).

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Vaevin thanks for reaching out with this feature request. It's definitely a valuable suggestion to integrate WandB metric logging with YOLOv5's _detect.py_ script for evaluating model performance. Your willingness to contribute by submitting a PR is appreciated and would be a great help in implementing this feature. We will take this into consideration for future updates. In the meantime, you may find the Ultralytics Docs helpful for any further assistance. Thank you for your support and understanding!
