### ISSUE TITLE
yolov5s to tensorrt "unable to load library: nvinfer_builder_resource.dll)

### ISSUE THREAD

**Issue by ericyaosl** [ultralytics/yolov5#8215]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Export

### Bug

I tried to export the tensorrt with windows system and this happened. I tested on different version of tensorrt and the bugs are the same show as following. Is there anything I can do to fix this?
![image](https://user-images.githubusercontent.com/27351334/173659983-5b7634e8-411a-4cff-8b7a-1ba2393f686c.png)

### Environment

Environment: Yolov5, Windows 10, python

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ericyaosl my experience with TRT on Windows is limited unfortunately and we do not have GPU CI in place but TRT export is validated manually and is working correctly on Linux environments like Google Colab. 

TRT autoinstalls are only supported on Linux so it's up to you to install TRT correctly in Windows environments and verify functionality before exporting. 

You might also try exporting in our Docker image which already includes a working environment including TRT.

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>
