### ISSUE TITLE
Can i do changes in the database befor resume traning ?

### ISSUE THREAD

**Issue by VYRION-Ai** [ultralytics/yolov5#8216]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

i Start traning and save checkpoint , and stop it.
can i do changes on the dataset befor resume traning again?

**Comment by AyushExel** [comment]
@totoadel theoretically it should be possible to resume from a different/updated dataset but you might run into some undesired results. Traditionally speaking for supervised learning tasks, in a complete training job the dataset remains constant. What you are proposing is closer to a transfer learning setting, where you first pre-train a model on some dataset and then fine-tune it on a different or updated dataset.
I think in most cases the transfer learning approach would be much better as the official models are already trained on coco.
It also depends on what exactly you're trying to accomplish.

**Comment by VYRION-Ai** [comment]
@AyushExel thank you very much
What I do is, I'm doing a Collab and Collab session finished before the training ends, but I save a checkpoint in google drive so I can resume the incomplete training, before I resume the incomplete training I had the 2000 image and it's annotation, I want to add it to dataset so that I can resume the training with new dateset .
now is this correct
