### ISSUE TITLE
about multi_scale

### ISSUE THREAD

**Issue by konioy** [ultralytics/yolov5#8217]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

If my testing inputs are fixed at 736*416, is it necessary to use multi_scale training? or only downsample？
eg: random.randrange(imgsz * 0.5, imgsz * 1 + gs) // gs * gs
Could you give some advice？

**Comment by glenn-jocher** [comment]
@konioy the size of your images is irrelevant since CNNs are translationally invariant. What matters is the size of the objects.
