### ISSUE TITLE
Using the trained weights

### ISSUE THREAD

**Issue by AbinJilson** [ultralytics/yolov5#8218]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have created a custom model using yolo in colab and saved the weights  . I want to use the same model in my pc using cpu to predict the result so that I can create an api for the model. Thanks in advance !

**Comment by barney2074** [comment]
I think there are 2 options:

- In COLAB, after training- download /content/yolov5/runs/train/expX/weights/best.pt, or
- in Ultralytics HUB, export in Pytorch format (you could also use other formats) to yourmodel.pt

Then point detect.py on your local PC to this weights (.pt) file
I found using Docker the easiest with the -v option for local file access

Andrew

**Comment by glenn-jocher** [comment]
@barney2074 hi Andrew! 👋

You're on the right track. Once you've trained your custom YOLOv5 model in Colab, you can download the best.pt file and run predictions on your local PC using the provided detect.py script. If you wish to create an API for your model, you can integrate the detection logic into your desired API framework.

Feel free to refer to the Ultralytics Docs for detailed guidance on running inference and deploying models. Let me know if you need any further assistance. Good luck!
