### ISSUE TITLE
Evolve from scratch with random

### ISSUE THREAD

**Issue by danik7** [ultralytics/yolov5#8219]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hey,
I would like to train my model on COCO and my custom dataset. 
For that, I want to do evolve. I don’t want to start my evolve process with pretrained weights. How can I do it?

**Comment by AyushExel** [comment]
@danik7 to start training from scratch, you can pass model definition using `--cfg` flag and set the `--weights` to be empty.
In your case the command would be:
`python train.py --cfg yolov5s.yaml --weights '' --evolve`
