### ISSUE TITLE
utils.general.init_seeds() raises RecursionError

### ISSUE THREAD

**Issue by WillieMaddox** [ultralytics/yolov5#822]
## 🐛 Bug
`utils.general.init_seeds()` raises `RecursionError`

## To Reproduce

Input:
```
from utils.general import init_seeds

init_seeds()
```

Output:
```
RecursionError                            Traceback (most recent call last)
<ipython-input-2-f6caabb30a03> in <module>
----> 1 init_seeds()

~/git/yolov5/utils/general.py in init_seeds(seed)
     57     random.seed(seed)
     58     np.random.seed(seed)
---> 59     init_seeds(seed=seed)
     60 
     61 

... last 1 frames repeated, from the frame below ...

~/git/yolov5/utils/general.py in init_seeds(seed)
     57     random.seed(seed)
     58     np.random.seed(seed)
---> 59     init_seeds(seed=seed)
     60 
     61 

RecursionError: maximum recursion depth exceeded while calling a Python object
```

## Environment
 - OS: Ubuntu 16.04
 - GPU: 1080 Ti

**Comment by Flock1** [comment]
Hi,

I am trying to use YOLO on an image and this is what I get:
```
---------------------------------------------------------------------------
RecursionError                            Traceback (most recent call last)
<ipython-input-5-e3d664f42aad> in <module>
----> 1 result = model(img)
      2 # torchvision.ops.nms
      3 # torchvision.ops.nms

~/.local/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

~/.cache/torch/hub/ultralytics_yolov5_master/models/common.py in forward(self, imgs, size, augment, profile)
    220         with torch.no_grad():
    221             y = self.model(x, augment, profile)[0]  # forward
--> 222         y = non_max_suppression(y, conf_thres=self.conf, iou_thres=self.iou, classes=self.classes)  # NMS
    223 
    224         # Post-process

~/.cache/torch/hub/ultralytics_yolov5_master/utils/general.py in non_max_suppression(prediction, conf_thres, iou_thres, classes, agnostic, labels)
    462         c = x[:, 5:6] * (0 if agnostic else max_wh)  # classes
    463         boxes, scores = x[:, :4] + c, x[:, 4]  # boxes (offset by class), scores
--> 464         i = torchvision.ops.nms(boxes, scores, iou_thres)  # NMS
    465         if i.shape[0] > max_det:  # limit detections
    466             i = i[:max_det]

~/anaconda3/envs/fastai/lib/python3.8/site-packages/torchvision/ops/boxes.py in nms(boxes, scores, iou_threshold)
     38         by NMS, sorted in decreasing order of scores
     39     """
---> 40     return torchvision.ops.nms(boxes, scores, iou_threshold)
     41 
     42 

... last 1 frames repeated, from the frame below ...

~/anaconda3/envs/fastai/lib/python3.8/site-packages/torchvision/ops/boxes.py in nms(boxes, scores, iou_threshold)
     38         by NMS, sorted in decreasing order of scores
     39     """
---> 40     return torchvision.ops.nms(boxes, scores, iou_threshold)
     41 
     42 

RecursionError: maximum recursion depth exceeded
```
I am using a conda environment and I downloaded the updated version. So can you suggest what I should do?

**Comment by glenn-jocher** [comment]
@Flock1 it appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below. 


## Requirements

**Python 3.8** or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including **`torch>=1.7`**. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by Flock1** [comment]
Thanks a lot. I honestly have no idea how I forgot this step.
