### ISSUE TITLE
Bounding Box features during training

### ISSUE THREAD

**Issue by alifarooq93** [ultralytics/yolov5#8222]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,
I have a problem with extracting bounding box image or features from yolov5 during training on custom data. In Yolo.py the detect method is creating bounding boxes but I didn't find any information about the features, image part or detected class.
In train.py model is returning the predictions of those bounding boxes. I tried to see the model output and it was like:
[4, [16, [3, 160, 160, 9]]] which explain that 4 is number of detection layers, 16 is my batch size, 3 is the number of anchors, and 9 is the no.of outputs for each anchor. the part [160, 160] is confusing is it the detected bounding box features or part of image from each batch image? and where is the predicted class id for those bounding boxes?
Train.py
                pred = model(imgs)  # forward
I want to extract bounding box specific features to perform active learning.
if anyone knows kindly let me know. It would be really grateful of you. Thanks

**Comment by glenn-jocher** [comment]
@alifarooq93 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # yolov5n - yolov5x6 official model
#                                            'custom', 'path/to/best.pt')  # custom model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by alifarooq93** [comment]
@glenn-jocher Thank you for your response but as I understand it will work with pretrained yolo model or custom model.
In my case I am training a model on custom data batches to predict underwater objects and I want to extract bounding box feature information of those images during training the model. 
Your solution will be helpful for testing but I need that information when I am running batches for multiple epochs during training the model. Do you have any idea?

**Comment by glenn-jocher** [comment]
@alifarooq93 all YOLOv5 methods run on training checkpoints as well as finalized models. You can detect/val/hub last.pt while training is ongoing.

**Comment by boukir** [comment]
Hello, @alifarooq93 
Did u find a response for ur question ? let's me know in case 

Best Regards
