### ISSUE TITLE
Can I activate the --evolve feature later?

### ISSUE THREAD

**Issue by sarpx** [ultralytics/yolov5#8223]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

There is a long training. I realized that I need to enable the --evolve feature. Can I do this in the middle of training?
Thx :)

**Comment by AyushExel** [comment]
@sarpx I don't think you can change the sequential flow of python program mid execution or change the argparse value without re-running the script. So, you'll have to run a fresh task
