### ISSUE TITLE
Exception: ERROR: /content/yolov5/../test/images does not exist

### ISSUE THREAD

**Issue by 96068chandra** [ultralytics/yolov5#8224]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hey,
I'm unable to find the test /images
How to resolve this issue???

![Screenshot (22)](https://user-images.githubusercontent.com/87321782/173890762-d82f15e4-ede5-4f0e-8bd1-c2f07c9a1e6d.png)

**Comment by AyushExel** [comment]
@96068chandra in the screenshot, the yolov5 folder doesn't have any `test/` directory which you are trying to access. Make sure you upload the correct folder and re-run the cell

**Comment by 96068chandra** [comment]
All three folders train,test,valid exist inside "Fish-Counting-1" folder

**Comment by AyushExel** [comment]
@96068chandra then you'll have to pass the relative path in source. `--source Fish-Counting-1/test/images`

**Comment by AyushExel** [comment]
@96068chandra were you able to solve the problem? Feel free to close the issue if you did. thanks!

**Comment by 96068chandra** [comment]
> @96068chandra were you able to solve the problem? Feel free to close the issue if you did. thanks!

Thankyou so much @AyushExel
