### ISSUE TITLE
I can't find histograms 

### ISSUE THREAD

**Issue by beauty-snowman** [ultralytics/yolov5#8225]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

i can't find histogram about bn_weight。Where can i get it
![OD%I@W K5BZ8$%DWQ(9F9QQ](https://user-images.githubusercontent.com/68273599/173897866-dcf2b558-6909-4b38-ac60-a1817e947cf4.png)
?

**Comment by glenn-jocher** [comment]
@beauty-snowman not sure what histograms are you referring to.
