### ISSUE TITLE
Why there is no 'model.24.anchor_grid' in trained model with yolov5-6.0?

### ISSUE THREAD

**Issue by Wangwang99999** [ultralytics/yolov5#8228]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Why there is no 'model.24.anchor_grid' in trained model? But it do exist in pretrained models!

**Comment by zhiqwang** [comment]
I guess you can try the following:

```sh
git clone git@github.com:ultralytics/yolov5.git
cd yolov5
git checkout v6.0
```

**Comment by Wangwang99999** [comment]
> I guess you can try the following:
> 
> ```shell
> git clone git@github.com:ultralytics/yolov5.git
> cd yolov5
> git checkout v6.0
> ```

I am using the latest code of v6.0.

**Comment by glenn-jocher** [comment]
@Wangwang99999 model architectures are updated over time
