### ISSUE TITLE
multiple objects assigned to a single anchor box？

### ISSUE THREAD

**Issue by firrice** [ultralytics/yolov5#8230]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have seen several similar issues, but i still can't understand the problem. For yolov5, in some case, where a single anchor is assigned with multi ground truth boxes，it means the anchor has several different supervised info during training, wouldn't there be some competition in loss and get bad result easily? But In terms of results, yolov5 does well. It comfuse me for a while.

**Comment by glenn-jocher** [comment]
@firrice all multi-task ML models like YOLO have multiple losses

**Comment by firrice** [comment]
@glenn-jocher thanks so much, but it seems a little different with multi-task model. In my question above, "anchor has several different supervised info" means one anchor has multi groundtruth bboxes label in regression task more specifically. In this way, which groundtruth bbox label will the anchor know to study?

**Comment by glenn-jocher** [comment]
Multiple anchors are assigned to each target in YOLOv5
