### ISSUE TITLE
Size mismatch error when inference with pytorch hub.

### ISSUE THREAD

**Issue by realgump** [ultralytics/yolov5#8231]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I am trying to use yolov5 as a preprocess in my own project, and chose to load yolov5 model with pytorch hub. However, size mismatch error occurs when I perform batched inference. 

The inputs of yolov5 is a tensor of [b, c, h, w], and I load the model by 
```
model = torch.hub.load('path/to/yolov5', 'custom', path='path/to/yolov5m.pt', source='local') 
```

The stdlog is:
```
YOLOv5 🚀 2022-6-14 Python-3.9.6 torch-1.11.0 CUDA:0 (Tesla V100-SXM2-32GB, 32510MiB)

Fusing layers... 
YOLOv5m summary: 290 layers, 21172173 parameters, 0 gradients
Adding AutoShape... 
iteration: 1    total 11 iterations
Traceback (most recent call last):
  File "/path/to/main.py", line 126, in <module>
    res = yolo_model(data['ori'], size=640)
  File "/path/to/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/path/to/conda/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/path/to/yolov5/models/common.py", line 573, in forward
    return self.model(imgs.to(p.device).type_as(p), augment, profile)  # inference
  File "/path/to/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/path/to/yolov5/models/common.py", line 445, in forward
    y = self.model(im, augment=augment, visualize=visualize)[0]
  File "/path/to/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/path/to/yolov5/models/yolo.py", line 135, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "/path/to/yolov5/models/yolo.py", line 158, in _forward_once
    x = m(x)  # run
  File "/path/to/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/path/to/yolov5/models/common.py", line 303, in forward
    return torch.cat(x, self.d)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 136 but got size 135 for tensor number 1 in the list.
```

Are there any mistakes I made when inference?

#### To Reproduce
```python
import torch
model = torch.hub.load('/path/to/yolov5', 'custom', path='/path/to/yolov5m.pt', source='local')
img = torch.rand(16, 3, 1920, 1080)
res = model(img)
```

**Comment by glenn-jocher** [comment]
@realgump 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # yolov5n - yolov5x6 official model
#                                            'custom', 'path/to/best.pt')  # custom model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by rbavery** [comment]
I'm also getting the error described above with a fine tuned model, is there some other step that is missing that is necessary to run inference with a traced model?

```
import torch
import skimage.io as skio
impath="test.png"
im = torch.from_numpy(skio.imread(impath))
im = torch.moveaxis(im,2,0).to("cpu").float()[None,...]
model = torch.jit.load('../models/megadetectorv5/md_v5a.0.0.torchscript')
model(im)
```
results in

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [24], in <module>
----> 1 model(torch.moveaxis(im,2,0).to("cpu").float()[None,...])

File ~/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py:1102, in Module._call_impl(self, *input, **kwargs)
   1098 # If we don't have any hooks, we want to skip the rest of the logic in
   1099 # this function, and just call forward.
   1100 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1101         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1102     return forward_call(*input, **kwargs)
   1103 # Do not call functions when jit is used
   1104 full_backward_hooks, non_full_backward_hooks = [], []

RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/models/yolo.py", line 83, in forward
    _38 = (_10).forward((_9).forward(_37, ), )
    _39 = (_12).forward((_11).forward(_38, ), )
    _40 = (_14).forward((_13).forward(_39, ), _37, )
           ~~~~~~~~~~~~ <--- HERE
    _41 = (_16).forward((_15).forward(_40, ), )
    _42 = (_18).forward((_17).forward(_41, ), _36, )
  File "code/__torch__/models/common.py", line 71, in forward
    argument_1: Tensor,
    argument_2: Tensor) -> Tensor:
    input = torch.cat([argument_1, argument_2], 1)
            ~~~~~~~~~ <--- HERE
    return input

Traceback of TorchScript, original code (most recent call last):
/home/rave/animl/yolov5/models/common.py(303): forward
/home/rave/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py(1090): _slow_forward
/home/rave/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py(1102): _call_impl
/home/rave/animl/yolov5/models/yolo.py(158): _forward_once
/home/rave/animl/yolov5/models/yolo.py(135): forward
/home/rave/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py(1090): _slow_forward
/home/rave/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py(1102): _call_impl
/home/rave/miniconda3/lib/python3.8/site-packages/torch/jit/_trace.py(958): trace_module
/home/rave/miniconda3/lib/python3.8/site-packages/torch/jit/_trace.py(741): trace
../../../yolov5/export.py(98): export_torchscript
../../../yolov5/export.py(520): run
/home/rave/miniconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py(28): decorate_context
../../../yolov5/export.py(602): main
../../../yolov5/export.py(607): <module>
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 46 but got size 45 for tensor number 1 in the list.
```

the shape of the preprocessed image ( I had to add a batch dimension and convert to float) is

```
im.shape
```
```
torch.Size([1, 3, 1440, 2560])
```
and I created the traced model with export.py as follows

```python
python export.py --weights ../animl-ml/models/megadetectorv5/md_v5a.0.0.pt --img 2560 2560 --batch 1
```

My expectation is that the traced model would be able to handle the image with size 1440, 2560. I'm not sure where this shape error comes from or why it doesn't occur with torch hub models.

**Comment by realgump** [comment]
> I'm also getting the error described above with a fine tuned model, is there some other step that is missing that is necessary to run inference with a traced model?
> 
> ```
> import torch
> import skimage.io as skio
> impath="test.png"
> im = torch.from_numpy(skio.imread(impath))
> im = torch.moveaxis(im,2,0).to("cpu").float()[None,...]
> model = torch.jit.load('../models/megadetectorv5/md_v5a.0.0.torchscript')
> model(im)
> ```
> 
> results in
> 
> ```
> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> Input In [24], in <module>
> ----> 1 model(torch.moveaxis(im,2,0).to("cpu").float()[None,...])
> 
> File ~/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py:1102, in Module._call_impl(self, *input, **kwargs)
>    1098 # If we don't have any hooks, we want to skip the rest of the logic in
>    1099 # this function, and just call forward.
>    1100 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
>    1101         or _global_forward_hooks or _global_forward_pre_hooks):
> -> 1102     return forward_call(*input, **kwargs)
>    1103 # Do not call functions when jit is used
>    1104 full_backward_hooks, non_full_backward_hooks = [], []
> 
> RuntimeError: The following operation failed in the TorchScript interpreter.
> Traceback of TorchScript, serialized code (most recent call last):
>   File "code/__torch__/models/yolo.py", line 83, in forward
>     _38 = (_10).forward((_9).forward(_37, ), )
>     _39 = (_12).forward((_11).forward(_38, ), )
>     _40 = (_14).forward((_13).forward(_39, ), _37, )
>            ~~~~~~~~~~~~ <--- HERE
>     _41 = (_16).forward((_15).forward(_40, ), )
>     _42 = (_18).forward((_17).forward(_41, ), _36, )
>   File "code/__torch__/models/common.py", line 71, in forward
>     argument_1: Tensor,
>     argument_2: Tensor) -> Tensor:
>     input = torch.cat([argument_1, argument_2], 1)
>             ~~~~~~~~~ <--- HERE
>     return input
> 
> Traceback of TorchScript, original code (most recent call last):
> /home/rave/animl/yolov5/models/common.py(303): forward
> /home/rave/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py(1090): _slow_forward
> /home/rave/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py(1102): _call_impl
> /home/rave/animl/yolov5/models/yolo.py(158): _forward_once
> /home/rave/animl/yolov5/models/yolo.py(135): forward
> /home/rave/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py(1090): _slow_forward
> /home/rave/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py(1102): _call_impl
> /home/rave/miniconda3/lib/python3.8/site-packages/torch/jit/_trace.py(958): trace_module
> /home/rave/miniconda3/lib/python3.8/site-packages/torch/jit/_trace.py(741): trace
> ../../../yolov5/export.py(98): export_torchscript
> ../../../yolov5/export.py(520): run
> /home/rave/miniconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py(28): decorate_context
> ../../../yolov5/export.py(602): main
> ../../../yolov5/export.py(607): <module>
> RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 46 but got size 45 for tensor number 1 in the list.
> ```
> 
> the shape of the preprocessed image ( I had to add a batch dimension and convert to float) is
> 
> ```
> im.shape
> ```
> 
> ```
> torch.Size([1, 3, 1440, 2560])
> ```
> 
> and I created the traced model with export.py as follows
> 
> ```python
> python export.py --weights ../animl-ml/models/megadetectorv5/md_v5a.0.0.pt --img 2560 2560 --batch 1
> ```
> 
> My expectation is that the traced model would be able to handle the image with size 1440, 2560. I'm not sure where this shape error comes from or why it doesn't occur with torch hub models.

The possible reason is that _yolov5_ doesn't support arbitrary shape of torch.tensor, but support autoshape of numpy, opencv and others. You might need to manual adjust the strides. Please refer to #3626. I have now solved the problem by using lists of URL to inference. However, I am puzzled by this feature, which might lead to unnecessary cost of type conversion, and I don't know is there any simple solution for this issue.

**Comment by glenn-jocher** [comment]
@realgump Thanks for reaching out. It looks like you've encountered an issue with using a traced YOLOv5 model for inference. One possible reason for this error is that YOLOv5 doesn't currently support arbitrary shapes of torch.tensor, but it does support autoshaping for numpy, OpenCV, and other libraries. 

You may need to manually adjust the strides as mentioned in Github issue #3626. While you've found a workaround by using lists of URLs for inference, you rightly point out the potential cost of type conversion. 

For now, the current workaround you've found may be the best solution for this issue. Keep an eye on the YOLOv5 repository for any updates that may address this in the future. If you have any other questions or need further assistance, feel free to ask!

Best regards 🚀

**Comment by Mary14-design** [comment]
@glenn-jocher Hello, I am running into the same issue. Could you elaborate on the recent workaround solution you provided recently? Thanks

**Comment by glenn-jocher** [comment]
@Mary14-design Hello! The workaround solution I mentioned involves using lists of URLs for inference. Essentially, rather than passing an image tensor directly to the model, you would first convert the images to URLs and then perform inference on the list of URLs. This can help avoid unnecessary type conversion costs associated with using torch.tensor directly.

For example, you can use a list of image URLs like this:
```python
image_urls = ['https://example.com/image1.jpg', 'https://example.com/image2.jpg']
results = model(image_urls)  # Perform inference on the list of image URLs
```

This approach can help bypass the issue of tensor shapes and strides when using a traced model for inference. If you have any further questions or need additional assistance, feel free to ask!
