### ISSUE TITLE
Add Torch-TensorRT option for torchscript exporting

### ISSUE THREAD

**Issue by henry-zwart** [ultralytics/yolov5#8235]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

The [PyTorch Torch-TensorRT](https://pytorch.org/TensorRT/) integration seems to provide int8 and fp16 GPU-optimised export functionalities for PyTorch torchscript models. This could be an awesome addition to the torchscript export.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@glenn-jocher Want to do this is the short term?

**Comment by glenn-jocher** [comment]
@henry-zwart hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

Could you please submit a PR with the torchscript-TRT export/inference proposal so we can see how this might work in practice and profile the proposal vs the current master TRT exports?

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by glenn-jocher** [comment]
@AyushExel I'm not too familiar with this export method, but it doesn't seem to be a priority from what I see in the torch docs.

The fastest export formats are TRT on GPU and ONNX/OpenVino on CPU. On TRT FP32 and FP16 inference both display the same in our benchmarks.
