### ISSUE TITLE
 yolov5-v6.1 

### ISSUE THREAD

**Issue by leishenzhupi** [ultralytics/yolov5#8236]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I downloaded yolov5-v6.1 and when I run detect.py I get the error 'Upsample' object has no attribute 'recompute_scale_factor', I need to modify the source code of the torch to work, I am using the torch version 1.11, and in other The error is not reported in other versions of yolov5.

**Comment by AyushExel** [comment]
I couldn't reproduce this error. Can you try to pull latest version of the repo from the mast and make sure you run `pip install -r requirements.txt` to install the correct versions of all dependencies?

**Comment by leishenzhupi** [comment]
> 我无法重现此错误。您可以尝试从桅杆中提取最新版本的 repo 并确保您运行`pip install -r requirements.txt`以安装所有依赖项的正确版本吗？

Thank you, the reason for this problem is the torch>=1.7.0 in the requirements.txt file, the default will download the latest version of the torch, now the latest version is 1.11.0, the version is too high, install a lower version of the torch can be solved, such as torch=1.9.0.

**Comment by leishenzhupi** [comment]
Thank you, the reason for this problem is the torch>=1.7.0 in the requirements.txt file, the default will download the latest version of the torch, now the latest version is 1.11.0, the version is too high, install a lower version of the torch can be solved, such as torch=1.9.0.






> 我无法修复此错误。您可以尝试从杆中提取最新版本的回购并确保您运行`pip install -r requirements.txt`以安装依赖项的正确版本吗？

Thank you, the reason for this problem is the torch>=1.7.0 in the requirements.txt file, the default will download the latest version of the torch, now the latest version is 1.11.0, the version is too high, install a lower version of the torch can be solved, such as torch=1.9.0.

**Comment by leishenzhupi** [comment]
> I couldn't reproduce this error. Can you try to pull latest version of the repo from the mast and make sure you run `pip install -r requirements.txt` to install the correct versions of all dependencies?

Thank you, the reason for this problem is the torch>=1.7.0 in the requirements.txt file, the default will download the latest version of the torch, now the latest version is 1.11.0, the version is too high, install a lower version of the torch can be solved, such as torch=1.9.0.

**Comment by AyushExel** [comment]
great!
