### ISSUE TITLE
How to train your own weights file

### ISSUE THREAD

**Issue by jungyin** [ultralytics/yolov5#8238]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I hope I can train a weights file from scratch, because when I first used Yolo, I was asked to download a weights file first and then train. Now I want to train a weights file from scratch. What should I do

**Comment by jungyin** [comment]
I found a lot of tutorials. They just let me download weights, but never taught me how to train weights by myself

**Comment by AyushExel** [comment]
@jungyin you can train from scratch by passing the config of the model and setting the weight parameter as empty.
Here's the syntax `python train.py --cfg yolov5s.yaml --weights ''`

**Comment by Ashlesha1995** [comment]
hai @jungyin  you can follow the yolov5  train custom data, there while traing pass weights as empty.
Here is the syntax   python train.py --img 640 --batch 16 --epochs 3 --data coco128.yaml --weights yolov5s.pt.
instead of passing pre-trained weight, pass it as empty.

**Comment by bryanbocao** [comment]
Comment out this line?
https://github.com/ultralytics/yolov5/blob/1156a323f8fc221d5c1a36c700e72e129419d187/train.py#L124

**Comment by glenn-jocher** [comment]
@bryanbocao To train from scratch, comment out line 124 in train.py as you suggested and then execute `python train.py --img 640 --batch 16 --epochs 3 --data coco128.yaml --weights ''`
