### ISSUE TITLE
misdetection and omission

### ISSUE THREAD

**Issue by Mengyao-Zhang** [ultralytics/yolov5#8241]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Hello  @glenn-jocher 
Guys do you know how to detect more performance metric, such as misdetection and omission？

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@18846169373 val.py reports all standard object detection metrics: mAP, P, R, F1, TP, FP.

**Comment by Mengyao-Zhang** [comment]
> @18846169373 val.py reports all standard object detection metrics: mAP, P, R, F1, TP, FP.

Thanks for your explanation, I already know that the omission rate is 1-recall. Also know that TP and FP are given in the confusion matrix. Can the misdetection  rate be calculated according to a formula?

**Comment by Yousef-Alhattab** [comment]
@18846169373 

did you find **Can the misdetection rate be calculated according to a formula?** out, please?
