### ISSUE TITLE
Programatically retrieving anchors

### ISSUE THREAD

**Issue by PeterSenyszyn** [ultralytics/yolov5#8242]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi there,

I'm trying to find the anchors and strides for a custom YOLOv5 model. I found this thread from a year ago: https://github.com/ultralytics/yolov5/issues/2585 and referenced this code:

```
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', autoshape=False)  # hub model
# -- or --
model = torch.load('yolov5s.pt')['model']  # local model

# Anchors
m = model.model[-1]  # Detect() layer
print(m.anchor_grid.squeeze())  # print anchors
```
but this does not work on v6.0 or v6.1. With the previous code I get:
`TypeError: 'Model' object is not subscriptable`

Is there a new way to programatically get anchors then strides? Thanks.

**Comment by glenn-jocher** [comment]
@PeterSenyszyn YOLOv5 🚀 anchors are saved as [Detect()](https://github.com/ultralytics/yolov5/blob/f17c86b7f0d2038288d7292cb82dec2433cc91e5/models/yolo.py#L33-L70) layer attributes on model creation, and updated as necessary by AutoAnchor before training starts. Their exact location is here:
https://github.com/ultralytics/yolov5/blob/f17c86b7f0d2038288d7292cb82dec2433cc91e5/models/yolo.py#L45

You can examine the anchors of any trained YOLOv5 model like this:

### Input
```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', autoshape=False)  # official model
model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt',  autoshape=False)  # custom model

# Anchors
m = model.model.model[-1]  # Detect() layer
print(m.anchors * m.stride.view(-1, 1, 1))  # print anchors
```

### Output
```python
YOLOv5 🚀 2021-11-22 torch 1.10.0+cu111 CUDA:0 (Tesla V100-SXM2-16GB, 16160MiB)
#           x     y
tensor([[[ 10.,  13.],
         [ 16.,  30.],
         [ 33.,  23.]],  # P3/8-small

        [[ 30.,  61.],
         [ 62.,  45.],
         [ 59., 119.]],  # P4/16-medium

        [[116.,  90.],
         [156., 198.],
         [373., 326.]]], dtype=torch.float16)  # P5/32-large
```

### Example

<img width="1767" alt="Screenshot 2022-03-14 at 10 37 19" src="https://user-images.githubusercontent.com/26833433/158145762-a46fe3c0-5a5b-4879-a446-4bb822827bed.png">

Good luck 🍀 and let us know if you have any other questions!
