### ISSUE TITLE
Extremely slow training 

### ISSUE THREAD

**Issue by Nourhan27** [ultralytics/yolov5#8244]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I followed the guide of custom data training and multi gpu training, and i am using your official docker image.

Training data size : 147 k images
Validation data size : 18 k images
I train on 4 GPUs 11 GB 1080 Ti, training 1 epoch is horrible taking about 17 hours. 

Training epoch takes 17 hours on 147000 samples.
validation epoch takes 20 min on 18000 samples.

Training command 
python -m torch.distributed.run --nproc_per_node 4 train.py --img 640 --batch 128 --epochs 100 --data custom_dataset.yaml  --weights yolov5s.pt --device 0,1,2,3

Please any help !

**Comment by glenn-jocher** [comment]
@Nourhan27 👋 Hello! Thanks for asking about **training speed issues**. YOLOv5 🚀 can be trained on CPU (slowest), [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) (fastest). If you would like to increase your training speed some options are:

- Increase `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s
- Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) DDP at larger `--batch-size`
- Train on cached data: `python train.py --cache` (RAM caching) or `--cache disk` (disk caching)
- Train on faster GPUs, i.e.: P100 -> V100 -> A100
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

Good luck 🍀 and let us know if you have any other questions!

**Comment by Nourhan27** [comment]
I found very strange behavior also the validation precision and recall at first epoch using pretrained yolov5s.pt is very high 0.88 0.9

so probably the problem is with data ? And if yes i have alot of data well labeled so what kind of tests i can do to reassure the data?

**Comment by glenn-jocher** [comment]
@Nourhan27 good metrics are a good thing, not a problem.

**Comment by RainyMoring** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.
> 
> ### Question
> I followed the guide of custom data training and multi gpu training, and i am using your official docker image.
> 
> Training data size : 147 k images Validation data size : 18 k images I train on 4 GPUs 11 GB 1080 Ti, training 1 epoch is horrible taking about 17 hours.
> 
> Training epoch takes 17 hours on 147000 samples. validation epoch takes 20 min on 18000 samples.
> 
> Training command python -m torch.distributed.run --nproc_per_node 4 train.py --img 640 --batch 128 --epochs 100 --data custom_dataset.yaml --weights yolov5s.pt --device 0,1,2,3
> 
> Please any help !
> 
> ### Additional
> _No response_

Do you deal with it? I have the same questions when training large datasets, about 120K images with 640*384, with 504G Mem and 8*3080Ti.
But in my test, speed is normal in first 5 epoches and slower when cached fill the memory, do you obverse of mem?(you can apt install htop and do it)

**Comment by Nourhan27** [comment]
Another question please @glenn-jocher 

My image  is 640 x 480 , when i set the --img to 640 in the training command line, do this pad the smaller side "480" to construct a square image ???


 **Is it normal to get these results at first epoch**
epoch,      train/box_loss,      train/obj_loss,      train/cls_loss,   metrics/precision,      metrics/recall,   metrics/mAP_0.5,metrics/mAP_0.5:0.95,        val/box_loss,        val/obj_loss,        val/cls_loss,     x/lr0,     x/lr1,     x/lr2

    0,            0.042128,            0.016422,            0.019087,             0.97129,             0.79612,             0.85129,             0.66127,            0.019724,           0.0059618,           0.0032383,           0.0033304,           0.0033304,            0.070026

- I started the training using yolov5 small model as starting point.
- I am training with multiple gpus following the tutorial ->  4 gpus 1080 Ti11 GB
- The epoch takes 17 hours, extremely slow, i checked gpus utilization and its ok.
- I need a guidance about the part that may cause this slow training to be bale to complete at least 100 epochs.




@RainyMoring I will check it.

**Comment by glenn-jocher** [comment]
@Nourhan27 training is done with square mosaics. Inference functions will pad minimum rectangles on --img long side specified.

I have no idea what's normal for your custom data, that's up to you to determine.

All of our training speed recommendations are already shown in my above comment https://github.com/ultralytics/yolov5/issues/8244#issuecomment-1159062273
