### ISSUE TITLE
How to tell if YOLOv5 is utilizing my GPU when training?

### ISSUE THREAD

**Issue by EricJi150** [ultralytics/yolov5#8247]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

For some reason today when I was training, the times for epoch were noticeably slower. Previously training with 100 epochs took a few minutes but now it is taking close to an hour. I have a 3070 GPU and a Ryzen 5 5600x processor. I read that it is slowest when only using the processor. How can I check if the training process is utilizing my GPU? When I try to train it doesn't mention my GPU at all like how it used to. I've tried installing an older version of PyTorch and reinstalling Cuda, but nothing seems to be working.

**Comment by glenn-jocher** [comment]
@EricJi150 device used is indicated here:
<img width="858" alt="Screenshot 2022-06-17 at 23 33 41" src="https://user-images.githubusercontent.com/26833433/174403962-137d7f83-9172-4f7b-aee4-d42632344282.png">

**Comment by EricJi150** [comment]
Yeah looks like my GPU is no longer being used. Do you happen to have any idea on how to solve this issue?

**Comment by glenn-jocher** [comment]
@EricJi150 see https://pytorch.org/get-started/locally/

You can also run `nvidia-smi` to ensure that CUDA is installed correctly

**Comment by bryanbocao** [comment]
@glenn-jocher
And here as well:
![Capture18](https://user-images.githubusercontent.com/14010288/174417721-05770e71-9808-47e9-b0a0-eb7db3f1476e.PNG)

Or try it in docker?
https://hub.docker.com/r/ultralytics/yolov5

**Comment by EricJi150** [comment]
@glenn-jocher @bryanbo-cao what version of PyTorch and Cuda do you guys use?

**Comment by bryanbocao** [comment]
@EricJi150 I just tried it reinstalling the packages by ```pip install -r requirements.txt``` the day before yesterday:
```
Python 3.8.13
PyTorch 1.7.1
NVIDIA-SMI 470.103.01   Driver Version: 470.103.01   CUDA Version: 11.4
```

**Comment by bryanbocao** [comment]
Even when specifying GPU (```0``` in the following example)?
```
CUDA_VISIBLE_DEVICES=0 python train ...
```

**Comment by AnhPC03** [comment]
@bryanbo-cao try to modify 
`parser.add_argument('--device', default='', help='cuda device, i.e. 0 or 0,1,2,3 or cpu')`
to
`parser.add_argument('--device', default='0', help='cuda device, i.e. 0 or 0,1,2,3 or cpu')` 
in `train.py` file.
And then run with `CUDA_VISIBLE_DEVICES=0 python train ...`
