### ISSUE TITLE
Speed Question

### ISSUE THREAD

**Issue by mfaizan-ai** [ultralytics/yolov5#8253]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi Glenn, I trained the custom yolov5 model by changing depth multiple and layer channels multiple for speed improvement. I want to know, does speed stays the same if we train our model for 2 epochs and then if we train it for 300 epochs? I want to first run the model on random weights to check for speed without training for long. I think it just updates weights for more training, it should not essentially impact the speed. We tested the on-axis camera by converting the pt file to tflite format. With 2 epoch optimization, it was giving 7-8 FPS, after training for 50 epochs it was giving 1 FPS. I don't what's wrong? I have no idea if it is a problem with the tflite format or training model for longer or the hardware? Glenn, please shed some light on it. :)

**Comment by glenn-jocher** [comment]
@faizan1234567 architecture is fixed, training does not change the architecture.

**Comment by mfaizan-ai** [comment]
@glenn-jocher You mean the speed should roughly stay the same? It's because weights values are being changed during training

**Comment by bryanbocao** [comment]
> @faizan1234567 architecture is fixed, training does not change the architecture.

Same here, don't see how it can change the inference speed.
For 7-8 FPS and 1 FPS, (1) are they all in the same format of pt or tflite(one of them), or (2) one is in pt while the other is in tflite?

**Comment by mfaizan-ai** [comment]
@bryanbo-cao both in tflite format. I converted them to tflite format from pt file. The strange thing is that yolov5n trained on 300 epochs on my custom dataset does not work as well. It also gives 1 FPS while yolov5n.pt download from the ultralytics yolov5 repository gives 7 FPS. I don't know why?

**Comment by mfaizan-ai** [comment]
Both files have been converted to tflite format with the same code. The only difference is a number of classes in both the weight files. I have 3 classes in my dataset mainly person, head, and car.

**Comment by glenn-jocher** [comment]
@faizan1234567 The number of classes should not significantly impact inference speed. Can you share the conversion script or the exact steps you followed to convert the weights to tflite format?
