### ISSUE TITLE
resize the train_image into (a,b), which a does not equal b. 

### ISSUE THREAD

**Issue by caiduoduo12138** [ultralytics/yolov5#826]
Due to  large resolution of  my custom dataset, I want to resize the train_img_size to be(1120,960).  It seems that I can change the image_size in command, like this:
python train.py --img-size 640 
But it seems to Make the height equal to the width. What should I do？

**Comment by NanoCode012** [comment]
I think you can use `--img-size 1120` and the image would be padded. You could try it then view the gt_images created within run directory.

**Comment by glenn-jocher** [comment]
@caiduoduo12138 try `python train.py --img 1120 --rect`
