### ISSUE TITLE
Map doesnt increase 

### ISSUE THREAD

**Issue by moahaimen** [ultralytics/yolov5#8260]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hi,  I made now 5000 images about 1000 for each class, and the map increased from 0.22 to 0.59
58.7% mAP 80.8% precision 48.8% recall
i made  the 

!python train.py --img 416 --batch 16 --epochs 1200 --data 
but the mAP doesn't increase more than  0.58 ever 
/content/yolov5/w_detection-16/data.yaml --weights  yolov5n.pt --cache
but I need to make it reach 0.97 I did label all the images I did everything you mentioned also Roboflow helped me a lot, but I need to understand how to make the background in the dataset and how will it affect and for Weapon detection which type of YOLOV5 model in better I am using Yolov5s, Yolov5n

thank you

**Comment by VYRION-Ai** [comment]
@moahaimen 
The first distribution of images between the training and  val folder is very important
Second, how many classes?
Third, yolov5x is the best but slow 
if you need help just tell me

**Comment by moahaimen** [comment]
> 

hi
first I need help, if you can, I appreciate that to you
second I am working on roboflow it makes the distribution 
third, I have 13 classes o made them at the beginning but now its only 6 classes

**Comment by moahaimen** [comment]
> @moahaimen The first distribution of images between the training and val folder is very important Second, how many classes? Third, yolov5x is the best but slow if you need help just tell me

hi again, i wish to contact you, I really  need your help 
please if you can respond
thank you

**Comment by hoangkhoiLE** [comment]
Can you show me your dataset ? Maybe I can help you to have good distribution of your dataset to train better because I already have face same problem !

**Comment by glenn-jocher** [comment]
@hoangkhoiLE It's great to see you helping out! It's essential to have a good distribution of images between the training and validation sets for successful training. Additionally, your dataset's diversity and how well it generalizes to unseen data are significant factors.

For further insights, please refer to the Ultralytics Docs at https://docs.ultralytics.com/yolov5/ and feel free to reach out if you need additional assistance. Good luck with your training!

**Comment by mochaab** [comment]
Hi Please, I need your help. 

I am detecting guidewire tips in fluoroscopic images. When I use detect.py on my test dataset, the result is impressive. It correctly detects most of the tips in all frames. However, when I validate or assess my custom-trained model, it returns around 0.4 for both precision and recall and 0.3 value for mAP, which does not justify the output of detect.py on same dataset. Can you please help me figure out why? 


I have another dataset taken from the lab, it is not fluoroscopic images, but only taken by web camera, but I used it in my initial experiments. I did same process than I described earlier, and for mAP I got around 0.8

Why is that?

**Comment by glenn-jocher** [comment]
@mochaab Thanks for reaching out! It's great to hear about the impressive detection results on your test dataset. The discrepancy you're observing during validation could be due to differences in the dataset distribution or the characteristics of the images in your test and validation sets. I recommend carefully evaluating the diversity and representativeness of your validation data. 

As for the dataset from the lab, various factors such as lighting conditions, camera perspectives, or object appearances could contribute to the difference in mAP. It's essential to ensure that the validation dataset accurately reflects the test-time conditions for optimal performance evaluation.

Remember to consult the Ultralytics Docs at https://docs.ultralytics.com/yolov5/ for further support. Good luck, and feel free to reach out if you have more questions!

**Comment by mochaab** [comment]
Thank you for your response. I'v been looking at the dataset I used fot evaluation. Thanks for the idea.

One more question, I am using yolov5s, and in other forums I see that result.png contains IoU of some kind and box, and objectness. 

Why did not I have those in my result.png? Does it suffice to only have mAP50 as a metric for object detection (particularly, guidewire tip, the only class I have in the dataset).

How is IoU computed in yolov5 or how is it related to mAP50. I searched already why IoU does not exist in result.png of yolov5, but I could not find answers.

I would appreciate so much if you can give me some insight about this. Thanks

**Comment by glenn-jocher** [comment]
@mochaab The `result.png` file in YOLOv5 doesn't contain the IoU, bounding boxes, or objectness score. YOLOv5 calculates the IoU during training and utilizes it to compute the mAP, which provides a comprehensive evaluation of detection performance. The mAP metric considers both precision and recall across varying IoU thresholds, offering a holistic assessment of detection accuracy.

To delve deeper into the IoU and mAP computation within YOLOv5, I recommend referring to the Ultralytics Docs at https://docs.ultralytics.com/yolov5/. These resources can provide you with a better understanding of the evaluation process and how to interpret mAP50 results for your specific use case.

Should you have further questions, feel free to ask. Best of luck with your project!

**Comment by mochaab** [comment]
Hi @glenn-jocher , I appreciate you responding. I did what you suggested to look closely to my dataset. However, I still have some issues even after I tested some combinations. In this comment, you can find more details. It would be so helpful if you could give me some more insights and clarification.

**My issue:** Results for validation on my test data is misleading. While val.py returns very low mAP, recall and precision, the labels generated by val.py and the detections using detect.py are almost perfect when manually checked.

**• Context:** I am working on guidewire/catheter “tip” detection. So far, the images, videos and real-time simulations look promising (for dataset 1).
**• I have two datasets:**
◦ _Dataset1:_ Images taken from the lab (with web-camera, phantom vessel and guidewire). Image resolutions (640x480 or vice versa)
Example: The first image is a sample of a background image, and the second one is an example of an image with a guidewire tip
![BG_CTGW_p3_bg_hf_vf_randrot_87](https://github.com/ultralytics/yolov5/assets/129426468/ab980004-25b4-42be-87be-d867d6576286)
![GWS_p4_colch_3](https://github.com/ultralytics/yolov5/assets/129426468/90b5a0bb-79ec-4036-b88c-13f6f232819f)

Overall I have 1663 images for validation, 9117 for training and 668 for testing
◦ _Dataset2:_ Images taken from the clinic (obtained from x-ray, phantom vessel and guidewire). Image resolution (480x410 or vice versa)
Example: 1st image (background), 2nd image (with tip)
![BG_SR_p1_crop_hf_104](https://github.com/ultralytics/yolov5/assets/129426468/d6abf090-3a5f-4468-9158-12434a4b0960)
![SR_p2_og_colch_40](https://github.com/ultralytics/yolov5/assets/129426468/97d0a143-de97-429f-86ff-3cdb081d2a6f)

Overall I have 1023 on validation, 6991 on training and 1056 for testing (but I modified this into 100: 30 background and 70 with images to simplify data for validation)
**• Validation Result and Tests**
◦ Validation on Test Dataset 1 shows promising results with **mAP50 0.76, recall 0.764 and precision 0.854** . The tests I did using detect.py shows good results as well, which backs up the scores and numbers that I just mentioned:
![GW_p2_hf_28](https://github.com/ultralytics/yolov5/assets/129426468/482aeff9-f5ef-41e9-a965-fd5ed0da1800)
![GW_p2_hf_colorch_32](https://github.com/ultralytics/yolov5/assets/129426468/011fe987-e221-47e4-b6c7-44a0961ecd44)

◦ Validation on Test Dataset 2 (clinical xray images) after I minimized the amount of data and validate only on images with similar guidewire model, I got this these values:  0.224 (Precision)      0.225 (Recall)     0.161 (mAP50). However, when I use detect.py to do detections on similar dataset and I checked it manually (100 images in total), 100% of background images were correctly classified as background and 100% of the images with tips, were correctly detected (tip enclosed by bounding box, with good confidence scores):
![GW_p2_og_8](https://github.com/ultralytics/yolov5/assets/129426468/b2f27f4e-905a-4998-aa28-b30e52f0838a)
![GW_p2_og_6](https://github.com/ultralytics/yolov5/assets/129426468/287a2294-ea31-4763-9411-b5f5c8533914)
![GW_p2_og_12](https://github.com/ultralytics/yolov5/assets/129426468/b3bd9273-7a61-40fb-a8e4-3cb660d52f67)

Similar with validation, I use conf_thres=0.3 and iou_thres=0.45 for detection.

I also compared the ground truth bounding box to the prediction (in detect.py), as well as ground truth to the validated image and the results are not that bad for the scores:
![image](https://github.com/ultralytics/yolov5/assets/129426468/b175a799-531a-4b63-bc11-bc623d59431b)

My question is, what are the reasons that my validation scores for dataset 2 is low, while the detection is really good? Does it has something to do with xray feature of the images? but how can I explain it, or where can I refer?
Also,most of the preparation steps for both dataset are similar... I wonder why the accuracy is so low for the second dataset while the first one has high accuracy, recall and precision.

I am hoping that you could help me. 

Thanks a lot, @glenn-jocher!

**Comment by mochaab** [comment]
> Hi @glenn-jocher , I appreciate you responding. I did what you suggested to look closely to my dataset. However, I still have some issues even after I tested some combinations. In this comment, you can find more details. It would be so helpful if you could give me some more insights and clarification.
> 
> **My issue:** Results for validation on my test data is misleading. While val.py returns very low mAP, recall and precision, the labels generated by val.py and the detections using detect.py are almost perfect when manually checked.
> 
> **• Context:** I am working on guidewire/catheter “tip” detection. So far, the images, videos and real-time simulations look promising (for dataset 1). **• I have two datasets:** ◦ _Dataset1:_ Images taken from the lab (with web-camera, phantom vessel and guidewire). Image resolutions (640x480 or vice versa) Example: The first image is a sample of a background image, and the second one is an example of an image with a guidewire tip ![BG_CTGW_p3_bg_hf_vf_randrot_87](https://private-user-images.githubusercontent.com/129426468/294059313-ab980004-25b4-42be-87be-d867d6576286.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzOTg2MzMsIm5iZiI6MTcwNDM5ODMzMywicGF0aCI6Ii8xMjk0MjY0NjgvMjk0MDU5MzEzLWFiOTgwMDA0LTI1YjQtNDJiZS04N2JlLWQ4NjdkNjU3NjI4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQxOTU4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MWVhOTQzNTRjNGQ3MjBmOTE4ZWQ4ZWM3ZGIwZTc2NWZmODgzMmI5ZmRlMDBjMWEzODc0ZjhhNmZlMzQyOTBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tB0KTKF3p2jbIyM4T6pLwOQ1uY_NaJqb5C8QPfsnhJQ) ![GWS_p4_colch_3](https://private-user-images.githubusercontent.com/129426468/294059316-90b5a0bb-79ec-4036-b88c-13f6f232819f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzOTg2MzMsIm5iZiI6MTcwNDM5ODMzMywicGF0aCI6Ii8xMjk0MjY0NjgvMjk0MDU5MzE2LTkwYjVhMGJiLTc5ZWMtNDAzNi1iODhjLTEzZjZmMjMyODE5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQxOTU4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMDM5MjE5YWNkOWI3NGI3ODQxYjBiZDNiMmZmZTA1ODVjMTc5NzYyMjA4Yjk0OGRiNmIyZWY2NDAxMWRjNDE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.N1bIFQYoRurgkSH0mhQX3veKX6o7rPkdNlSCJDVXuXE)
> 
> Overall I have 1663 images for validation, 9117 for training and 668 for testing ◦ _Dataset2:_ Images taken from the clinic (obtained from x-ray, phantom vessel and guidewire). Image resolution (480x410 or vice versa) Example: 1st image (background), 2nd image (with tip) ![BG_SR_p1_crop_hf_104](https://private-user-images.githubusercontent.com/129426468/294059800-d6abf090-3a5f-4468-9158-12434a4b0960.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzOTg2MzMsIm5iZiI6MTcwNDM5ODMzMywicGF0aCI6Ii8xMjk0MjY0NjgvMjk0MDU5ODAwLWQ2YWJmMDkwLTNhNWYtNDQ2OC05MTU4LTEyNDM0YTRiMDk2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQxOTU4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZmQ3NzMyYjU5YTE4ODgyOGI4NjUyYjI2YWI1MTg0NmE0MDUzOGI0ZGQyZDExYTc3NGMyNDdmNWUwYTI3YWJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3Mh6CkbKYQkKpg49twb3KpJe7paweLO6Uvwn7APWsqc) ![SR_p2_og_colch_40](https://private-user-images.githubusercontent.com/129426468/294059803-97d0a143-de97-429f-86ff-3cdb081d2a6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzOTg2MzMsIm5iZiI6MTcwNDM5ODMzMywicGF0aCI6Ii8xMjk0MjY0NjgvMjk0MDU5ODAzLTk3ZDBhMTQzLWRlOTctNDI5Zi04NmZmLTNjZGIwODFkMmE2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQxOTU4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNzZiYzJmMDgyNjBiYTFjZDIwZDQyZTJkMzg1OGQyZjgxMmEzMTAyMmRjMzUwOTVjZmZhYmEyMGUwNjEwNDQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jI9k7EGdc-RTFVNeTVLDKPqUfhSVxt2aLUfB2qpFjeE)
> 
> Overall I have 1023 on validation, 6991 on training and 1056 for testing (but I modified this into 100: 30 background and 70 with images to simplify data for validation) **• Validation Result and Tests** ◦ Validation on Test Dataset 1 shows promising results with **mAP50 0.76, recall 0.764 and precision 0.854** . The tests I did using detect.py shows good results as well, which backs up the scores and numbers that I just mentioned: ![GW_p2_hf_28](https://private-user-images.githubusercontent.com/129426468/294060115-482aeff9-f5ef-41e9-a965-fd5ed0da1800.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzOTg2MzMsIm5iZiI6MTcwNDM5ODMzMywicGF0aCI6Ii8xMjk0MjY0NjgvMjk0MDYwMTE1LTQ4MmFlZmY5LWY1ZWYtNDFlOS1hOTY1LWZkNWVkMGRhMTgwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQxOTU4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDRmNjZmMmZmYWU1ZTFmOTg5Mzg1ZGRjZmFlYjJjMzY3ODUzZmYwNjM2MmZmZjExZDMzMzQxYzk3YTQ0N2Q2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BsgzuO3u7NlAP1jIu4-7g6_MTui-JLgN9AMgRjXO2bc) ![GW_p2_hf_colorch_32](https://private-user-images.githubusercontent.com/129426468/294060131-011fe987-e221-47e4-b6c7-44a0961ecd44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzOTg2MzMsIm5iZiI6MTcwNDM5ODMzMywicGF0aCI6Ii8xMjk0MjY0NjgvMjk0MDYwMTMxLTAxMWZlOTg3LWUyMjEtNDdlNC1iNmM3LTQ0YTA5NjFlY2Q0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQxOTU4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDNiYzI4YzRmZDI3NzE4Y2Y0OTI5MzQzMzMzZTg0Mzc4YzBiOTkzMDNmMTZmYWM5ZmZlNDhlMmU3YjVkZTRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7hpEFbADLmKQlkAL3O_fp_LzV6pLYRVgESsdx_kHKXw)
> 
> ◦ Validation on Test Dataset 2 (clinical xray images) after I minimized the amount of data and validate only on images with similar guidewire model, I got this these values: 0.224 (Precision) 0.225 (Recall) 0.161 (mAP50). However, when I use detect.py to do detections on similar dataset and I checked it manually (100 images in total), 100% of background images were correctly classified as background and 100% of the images with tips, were correctly detected (tip enclosed by bounding box, with good confidence scores): ![GW_p2_og_8](https://private-user-images.githubusercontent.com/129426468/294060833-b2f27f4e-905a-4998-aa28-b30e52f0838a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzOTg2MzMsIm5iZiI6MTcwNDM5ODMzMywicGF0aCI6Ii8xMjk0MjY0NjgvMjk0MDYwODMzLWIyZjI3ZjRlLTkwNWEtNDk5OC1hYTI4LWIzMGU1MmYwODM4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQxOTU4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzhiNzA1NWY1ZDM1ZTEwMmQyZTk1ZmFkOTA3YjdhMTMzZTVkZGViMWNmNmU2YjFiMDk2M2Q2NjZlM2UxZGZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1zT3Tflc-ugvq8q1FuDsRFoPpL8h3_jI4PgCfq4USMM) ![GW_p2_og_6](https://private-user-images.githubusercontent.com/129426468/294060888-287a2294-ea31-4763-9411-b5f5c8533914.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzOTg2MzMsIm5iZiI6MTcwNDM5ODMzMywicGF0aCI6Ii8xMjk0MjY0NjgvMjk0MDYwODg4LTI4N2EyMjk0LWVhMzEtNDc2My05NDExLWI1ZjVjODUzMzkxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQxOTU4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZGU0MWU5Zjg2OTgzZmFhM2VhZDM0MjRkZGFiYjlhYWIyNzRiODcwMjYyYzRkNzkyOGVhYmRjYjQ4NWZiMzNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aCse-mU0zeUL27R6IVx8M_FGX_cw_6SFgDUOPkCv4cA) ![GW_p2_og_12](https://private-user-images.githubusercontent.com/129426468/294060904-b3bd9273-7a61-40fb-a8e4-3cb660d52f67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzOTg2MzMsIm5iZiI6MTcwNDM5ODMzMywicGF0aCI6Ii8xMjk0MjY0NjgvMjk0MDYwOTA0LWIzYmQ5MjczLTdhNjEtNDBmYi1hOGU0LTNjYjY2MGQ1MmY2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQxOTU4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTllMzYxNzJiYzAzMmMzMzcwOThjN2NmOWYwYWI0YmM4YzE4MDkxZjIxM2RiNGY2NjM4MzllNzFiZmY2MmEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pw0Gu6-9X7UJNg376wwl8AdLwOyckRl7xMjUM_PByZs)
> 
> Similar with validation, I use conf_thres=0.3 and iou_thres=0.45 for detection.
> 
> I also compared the ground truth bounding box to the prediction (in detect.py), as well as ground truth to the validated image and the results are not that bad for the scores: ![image](https://private-user-images.githubusercontent.com/129426468/294061204-b175a799-531a-4b63-bc11-bc623d59431b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzOTg2MzMsIm5iZiI6MTcwNDM5ODMzMywicGF0aCI6Ii8xMjk0MjY0NjgvMjk0MDYxMjA0LWIxNzVhNzk5LTUzMWEtNGI2My1iYzExLWJjNjIzZDU5NDMxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQxOTU4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDk3NzA3OTkwODE4NDdhMWVhNGI5ZjExOGQxOWQwMDkzMWZmZDAyOTZlODNmNGY3Zjc3YWE5ZWRjMjUxYzZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZvigQcrQj1wWjS89-CIuNyBxfjyJhEPIzUml8khxSzc)
> 
> My question is, what are the reasons that my validation scores for dataset 2 is low, while the detection is really good? Does it has something to do with xray feature of the images? but how can I explain it, or where can I refer? Also,most of the preparation steps for both dataset are similar... I wonder why the accuracy is so low for the second dataset while the first one has high accuracy, recall and precision.
> 
> I am hoping that you could help me.
> 
> Thanks a lot, @glenn-jocher!

Just an update. I looked closely to the predicted bounding box and ground truth and it looks like most of the tips in the predicted ones are in the corner of the bounding box while tips in the labels are really in the middle. So I decreased the iouv in val.py from 0.5 to 0.2 and I got good scores. Now my question is, what is the relationship of --iou-thres and iou in mAP50 (iou=50), cause even when I decrease the value in --iou-thres, I do not get a high mAP, but if I decrease the value in iouv (hardcoded in val.py) then mAP increases.

**Comment by glenn-jocher** [comment]
Hello @mochaab, I'm glad to hear you've made some progress by adjusting the IoU threshold. The `--iou-thres` parameter in `val.py` sets the IoU threshold for considering a detection as a true positive during validation. A lower `--iou-thres` means that detections with a lower overlap with ground truth will still be considered correct, which can increase precision and recall but may not necessarily reflect the actual performance of the model at a standard IoU threshold (e.g., 0.5).

On the other hand, mAP50 refers to the mean Average Precision at an IoU threshold of 0.5. Changing the `iouv` parameter directly affects the computation of mAP at different IoU thresholds. If you lower the `iouv` value, you're effectively evaluating the model at a less strict IoU threshold, which can artificially inflate the mAP score.

It's important to maintain a balance between achieving high mAP scores and ensuring that the model performs well at standard IoU thresholds, as this is a more realistic measure of performance. If your model requires a lower IoU threshold to achieve good performance, it might indicate that the model is not predicting the bounding boxes as accurately as it should, and further tuning or dataset adjustments may be necessary.

For a more detailed explanation of these concepts, please refer to the Ultralytics Docs at https://docs.ultralytics.com/yolov5/. Keep experimenting with the thresholds and the dataset, and best of luck with your project!
