### ISSUE TITLE
Training models on coco-minitrain

### ISSUE THREAD

**Issue by bryanbocao** [ultralytics/yolov5#8263]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Training YOLO models on the original coco dataset takes days. Do you have prepared or plan to prepare <dada>.yaml to train on https://github.com/giddyyupp/coco-minitrain to reduce the cost of hyperparameter searching?

Thanks!

**Comment by glenn-jocher** [comment]
@bryanbo-cao hi, thank you for your feature suggestion on how to improve YOLOv5 🚀! Yes you are right COCO training requires significant resources unfortunately and it would be great to have a smaller version that's still representative of the larger set. In the past I've used VOC for quick experiments but it's not quite the same and results there may not correlate well with COCO results.

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by bryanbocao** [comment]
@glenn-jocher sounds good. Will work on that later.

**Comment by bryanbocao** [comment]
@glenn-jocher Created a pull request https://github.com/ultralytics/yolov5/pull/8368. Thanks!

**Comment by glenn-jocher** [comment]
Appreciate the proactive contribution, @bryanbocao! I've reviewed it and left some comments on the pull request. Let's keep the discussion going there to further improve the feature before merging. Keep up the great work!
