### ISSUE TITLE
when applying the model.fuse(), the processing of torchscript export fail. (how to accelerate the model inference when using torchscript depend on libtorch in c++ language？)

### ISSUE THREAD

**Issue by silicon2006** [ultralytics/yolov5#827]

**Comment by glenn-jocher** [comment]
@silicon2006 thank you for raising this issue. commit https://github.com/ultralytics/yolov5/commit/a8751e50de94b207c1323c3eda493952cced1d72 should fix this. Model fusing during export is now enabled and takes effect for all export destinations: torchscript, onnx, and coreml.

Please git pull and try again.

**Comment by glenn-jocher** [comment]
@silicon2006 also FYI, you can use Netron viewer to verify that the exported models are fused.

**Comment by silicon2006** [comment]
That's great,  I solved this problem yesterday ,but your's solution is much better. thanks!
