### ISSUE TITLE
Cannot read boxes with tflite correctly

### ISSUE THREAD

**Issue by maximereder** [ultralytics/yolov5#8270]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I trained a model allowing the detection of '+' characters on an image thanks to Yolov5. I want to use this model in TFLITE. However, when I infer an image in the model, I have trouble interpreting the output.

Here is how I infer in my model :

```
interpreter = tf.lite.Interpreter("/Users/maximereder/Desktop/best-fp16.tflite")

interpreter.allocate_tensors()

IMAGE_PATH = "/ML/dataset/plus- 
1000x750/train/IMG_1492B2.jpg"

img = cv2.resize(cv2.imread(IMAGE_PATH), (640, 640))
features = img.copy()
np_features = np.array(features, dtype=np.float32)
np_features = np.expand_dims(np_features, axis=0)

input_details = interpreter.get_input_details()

output_details = interpreter.get_output_details()

interpreter.set_tensor(input_details[0]['index'], np_features)
interpreter.invoke()
```

output details : 

`[{'name': 'Identity',
'index': 422,
'shape': array([    1, 25200,    85], dtype=int32),
'shape_signature': array([    1, 25200,    85], dtype=int32),
'dtype': numpy.float32,
'quantization': (0.0, 0),
'quantization_parameters': {'scales': array([], dtype=float32),
'zero_points': array([], dtype=int32),
'quantized_dimension': 0},
'sparsity_parameters': {}}]`

When I want to interpret the output of my model:

`pred = interpreter.get_tensor(output_details[0]['index'])`

pred : 

`array([[[ -0.0036954,    0.014147,    0.056896,    0.043846,  0.00043562,           1],
        [ -0.0021566,    0.016882,    0.076684,    0.029069,   0.0014714,           1],
        [ -0.0026859,    0.016034,    0.066541,    0.028921,   0.0094091,           1],
        ...,
        [    0.92495,     0.92842,     0.72325,     0.56177,  1.2151e-13,           1],
        [    0.92489,     0.92734,     0.95695,      1.0872,  4.4961e-08,           1],
        [     1.0236,     0.98474,      2.2639,    0.001837,  8.0375e-07,           1]]], dtype=float32)`

I think [1-4] columns are boxes, 5 confidence and 6 the label (here '+')

But when I sort these boxes according to their confidence with a threshold at 0.9 : 

```import cv2
import matplotlib.pyplot as plt

IMAGE_PATH = "ML/dataset/plus-1000x750/train/IMG_1492B2.jpg"
image = cv2.resize(cv2.imread(IMAGE_PATH), (640, 640))

for i in range(len(scores)):
    if(scores[i] > 0.9 and scores[i] < 1.0):
        boxe = np.multiply(boxes[i], [640, 640, 640, 640])
        cv2.rectangle(image, (int(boxe[0]),int(boxe[1])), (int(boxe[2]),int(boxe[3])), (10, 255, 0), 2)

plt.figure(figsize=(19, 16))
plt.imshow(image[:, :, ::-1])
plt.axis('off')
[plt.show()`]```

**I have abnormally too many : 9532 boxes and there are false (no '+' detected...)**

How can we fixe that? Did I read the output correctly ?

Thank you.

**Comment by glenn-jocher** [comment]
@maximereder after exporting a TFLite model with export.py simply apply the usage examples shown to validate and detect:
<img width="751" alt="Screen Shot 2022-06-21 at 3 48 56 PM" src="https://user-images.githubusercontent.com/26833433/174815597-d71deb3a-2d36-4d12-8ae1-f0483b24a321.png">
