### ISSUE TITLE
1d signal on/off set detection

### ISSUE THREAD

**Issue by karim-moon** [ultralytics/yolov5#8271]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Currently, I'm trying to detect on/off set from 1d signal like voice or body signal and also trying to translate yolov5 from 2d to 1d signal.

I think the easiest way is stack 1d signal like 2d image. But it's not worth to use this repo.
other way is just unsqueeze the signal looks like 2d image.

Is there other way to translate?
If someone has Idea, please let me know

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@moon-jong for the best community response I would include as many figures, images, plots, references etc to your custom use case, otherwise it's hard for anyone to understand your question.
