### ISSUE TITLE
where can I find yolov5n-7.yaml?

### ISSUE THREAD

**Issue by Yaifan** [ultralytics/yolov5#8276]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

where can I find yolov5n-7.yaml?

**Comment by glenn-jocher** [comment]
@Yaifan these are temporary research models that we continually test in research branches, there is no yaml available on master branch.
