### ISSUE TITLE
state_dict positional arguments deprecation warning 

### ISSUE THREAD

**Issue by Rusteam** [ultralytics/yolov5#8278]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I can't find the piece of code that causes this [state_dict() deprecation warning](https://pytorch.org/docs/master/generated/torch.nn.Module.html#torch.nn.Module.state_dict) and if someone can point me to that, I'm willing to fix it and submit a PR.

Currently my training logs look like this:
![Screen Shot 2022-06-21 at 11 03 17 AM](https://user-images.githubusercontent.com/22130831/174737474-d92cb95e-f029-458a-af65-795bce1bce1f.png)
and it is annoying to see this warning every step.

I'm training in a docker with nvidia runtime and `pytorch==1.11.0`

**Comment by glenn-jocher** [comment]
@Rusteam that's strange, we train in our Docker image every day and I don't see these messages. Perhaps you've installed alternative torch versions? When did you last pull a new Docker image?

**Comment by Rusteam** [comment]
I use an nvidia image `nvidia/cuda:11.3-devel-ubuntu20.04` [from docker hub](https://hub.docker.com/r/nvidia/cuda) which I upgrade to py39, torch==1.11 and torchvision==0.12. 

What version of torch do you run? 

What's weird is that I'm not able to find the usage of `state_dict()` with positional arguments.
![Screen Shot 2022-06-22 at 9 04 53 AM](https://user-images.githubusercontent.com/22130831/174947870-a4a06bcc-eebf-4e13-8a24-99105bbd3936.png)

**Comment by glenn-jocher** [comment]
@Rusteam we don't control 3rd party images, I would recommend the official YOLOv5 image which does not have this issue.

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

**Comment by Rusteam** [comment]
Thanks. I've tried the same base nvidia/pytorch:22.04[5] image and haven't seen that warning.

**Comment by glenn-jocher** [comment]
@Rusteam glad to hear that the official Nvidia/PyTorch image did not yield a warning for you. Please let us know if you encounter any further issues or questions during your YOLOv5 implementation. Thank you for your support!
