### ISSUE TITLE
Where do code change the image size? torch to tensorRT

### ISSUE THREAD

**Issue by soohwanlim** [ultralytics/yolov5#8280]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Where do code change the image size? 
when i play yolov5s.pt by webcam(source 0) its imgsize is 480x640
but in yolov5s.engine(tensorRT) its imgsize is 640x640

I'm asking because I don't know where to change imgsize in the code.

**Comment by glenn-jocher** [comment]
@OSMasterSoohwan all CLI executable files have argparses that define their arguments:
https://github.com/ultralytics/yolov5/blob/a2a1ed201d150343a4f9912d644be2b210206984/detect.py#L211-L243
