### ISSUE TITLE
Onnx conversion increases model size by more than factor of two

### ISSUE THREAD

**Issue by seba-eng** [ultralytics/yolov5#8282]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I trained a nano model and the final checkpoint has a size of 3.8 Mb. After converting it to the onnx format the file size increases to 7.3 Mb. Enabling the simplify option increases the size even more to 11.2 Mb. 

Is this behavior expected? My model sizes usually went down when I converted a classification CNN to onnx.

**Comment by glenn-jocher** [comment]
@seba-eng PyTorch models are FP16. Exports default to FP32. You can use the --half flag if you want FP models.

**Comment by seba-eng** [comment]
that makes sense, thanks

**Comment by glenn-jocher** [comment]
@seba-eng you're welcome! Let me know if you have any other questions.
