### ISSUE TITLE
Can't train  with multi gpus 

### ISSUE THREAD

**Issue by donaldlee2008** [ultralytics/yolov5#8288]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

os:WINDOWS 10 
two GPU 3090TI
（pytorch) D:\deeplearning\majiang\yolov561>python -m torch.distributed.run --nproc_per_node 2 train.py --batch 64  --data data/majiangVOC.yaml  --cfg models/majiangv5s.yaml --weights weights/yolov5s.pt  --device 0,1
NOTE: Redirects are currently not supported in Windows or MacOs.
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
train: weights=weights/yolov5s.pt, cfg=models/majiangv5s.yaml, data=data/majiangVOC.yaml, hyp=data\hyps\hyp.scratch-low.yaml, epochs=300, batch_size=64, imgsz=640, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, evolve=None, bucket=, cache=None, image_weights=False, device=0,1, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=8, project=runs\train, name=exp, exist_ok=False, quad=False, cos_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest
github: skipping check (not a git repository), for updates see https://github.com/ultralytics/yolov5
YOLOv5  2022-2-22 torch 1.10.2 CUDA:0 (NVIDIA GeForce RTX 3090 Ti, 24564MiB)
                                 CUDA:1 (NVIDIA GeForce RTX 3090 Ti, 24564MiB)

Added key: store_based_barrier_key:1 to store for rank: 0
Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 2 nodes.
hyperparameters: lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0
Traceback (most recent call last):
  File "train.py", line 643, in <module>
    main(opt)
  File "train.py", line 539, in main
Weights & Biases:     train(opt.hyp, opt, device, callbacks)run 'pip install wandb' to automatically track and visualize YOLOv5  runs (RECOMMENDED)

  File "train.py", line 109, in train
TensorBoard:     with torch_distributed_zero_first(LOCAL_RANK):Start with 'tensorboard --logdir runs\train', view at http://localhost:6006/

  File "C:\Users\MH\.conda\envs\pytorch\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "D:\deeplearning\majiang\yolov561\utils\torch_utils.py", line 39, in torch_distributed_zero_first
    dist.barrier(device_ids=[local_rank])
  File "C:\Users\MH\.conda\envs\pytorch\lib\site-packages\torch\distributed\distributed_c10d.py", line 2698, in barrier
    "for the selected backend {}".format(get_backend(group))
RuntimeError: Function argument device_ids not supported for the selected backend gloo
Traceback (most recent call last):
  File "train.py", line 643, in <module>
    main(opt)
  File "train.py", line 539, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 110, in train
    data_dict = data_dict or check_dataset(data)  # check if None
  File "C:\Users\MH\.conda\envs\pytorch\lib\contextlib.py", line 88, in __exit__
    next(self.gen)
  File "D:\deeplearning\majiang\yolov561\utils\torch_utils.py", line 42, in torch_distributed_zero_first
    dist.barrier(device_ids=[0])
  File "C:\Users\MH\.conda\envs\pytorch\lib\site-packages\torch\distributed\distributed_c10d.py", line 2698, in barrier
    "for the selected backend {}".format(get_backend(group))
RuntimeError: Function argument device_ids not supported for the selected backend gloo
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 4352) of binary: C:\Users\MH\.conda\envs\pytorch\python.exe
Traceback (most recent call last):
  File "C:\Users\MH\.conda\envs\pytorch\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\MH\.conda\envs\pytorch\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\MH\.conda\envs\pytorch\lib\site-packages\torch\distributed\run.py", line 723, in <module>
    main()
  File "C:\Users\MH\.conda\envs\pytorch\lib\site-packages\torch\distributed\elastic\multiprocessing\errors\__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\MH\.conda\envs\pytorch\lib\site-packages\torch\distributed\run.py", line 719, in main
    run(args)
  File "C:\Users\MH\.conda\envs\pytorch\lib\site-packages\torch\distributed\run.py", line 713, in run
    )(*cmd_args)
  File "C:\Users\MH\.conda\envs\pytorch\lib\site-packages\torch\distributed\launcher\api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "C:\Users\MH\.conda\envs\pytorch\lib\site-packages\torch\distributed\launcher\api.py", line 261, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2022-06-21_16:01:53
  host      : MH-Image
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 17752)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-06-21_16:01:53
  host      : MH-Image
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 4352)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by glenn-jocher** [comment]
@donaldlee2008 all DDP trainings should be run in Docker.


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

**Comment by Eliana-23** [comment]
> ### 询问前先搜索
> * [x] 我搜索了 YOLOv5 [的问题](https://github.com/ultralytics/yolov5/issues)和[讨论](https://github.com/ultralytics/yolov5/discussions)，没有找到类似的问题。
> 
> ### 问题
> 作系统：WINDOWS 10 双 GPU 3090TI （pytorch） D：\deeplearning\majiang\yolov561>python -m torch.distributed.run --nproc_per_node 2 train.py --batch 64 --data data/majiangVOC.yaml --cfg models/majiangv5s.yaml --weights weights/yolov5s.pt --device 0,1 注意：Windows 或 macOS 目前不支持重定向。警告：**main**：
> 
> 将每个进程OMP_NUM_THREADS环境变量默认设置为 1，为避免系统过载，请根据需要进一步调整变量以获得应用程序的最佳性能。
> 
> train： weights=weights/yolov5s.pt， cfg=models/majiangv5s.yaml， data=data/majiangVOC.yaml， hyp=data\hyps\hyp.scratch-low.yaml， epochs=300， batch_size=64， imgsz=640， rect=False， resume=False， nosave=False， noval=False， noautoanchor=False， evolve=None， bucket=， cache=None， image_weights=False， device=0,1， multi_scale=False， single_cls=False， optimizer=SGD， sync_bn=False， workers=8， project=runs\train， name=exp， exist_ok=False， quad=False， cos_lr=False， label_smoothing=0.0， 耐心=100， 冻结=[0]， save_period=-1， local_rank=-1， entity=None， upload_dataset=False， bbox_interval=-1， artifact_alias=latest github： 跳过检查（不是 git 存储库），有关更新，请参阅 https://github.com/ultralytics/yolov5 YOLOv5 2022-2-22 torch 1.10.2 CUDA：0（NVIDIA GeForce RTX 3090 Ti， 24564MiB） CUDA：1 （NVIDIA GeForce RTX 3090 Ti， 24564MiB）
> 
> 添加了 key： store_based_barrier_key：1 到 store for rank： 0 Rank 0：完成了 key：store_based_barrier_key：1 的基于 store 的屏障，有 2 个节点。超参数：LR0=0.01、LRF=0.01、动量=0.937、weight_decay=0.0005、warmup_epochs=3.0、warmup_momentum=0.8、warmup_bias_lr=0.1、box=0.05、CLS=0.5、cls_pw=1.0、OBJ=1.0、obj_pw=1.0、iou_t=0.2、anchor_t=4.0、fl_gamma=0.0、hsv_h=0.015、hsv_s=0.7、hsv_v=0.4、度=0.0、平移=0.1、刻度=0.5、 剪切=0.0，透视=0.0，翻转=0.0，翻转lr=0.5，马赛克=1.0，混淆=0.0，copy_paste=0.0 回溯（最后一次调用）：文件“train.py”，行643，在主（选项）文件“train.py”，行539，在主权重和偏差中：train（opt.hyp， opt， device， callbacks）运行'pip install wandb'以自动跟踪和可视化YOLOv5运行（推荐）
> 
> 文件 “train.py”，第 109 行，在训练 TensorBoard 中：使用 torch_distributed_zero_first（LOCAL_RANK）：以 'tensorboard --logdir runs\train' 开头，在 http://localhost:6006/ 处查看
> 
> # 文件 “C：\Users\MH.conda\envs\pytorch\lib\contextlib.py”，第 81 行，回**车**
> 返回 next（self.gen）
> 文件 “D：\deeplearning\majiang\yolov561\utils\torch_utils.py”，第 39 行，torch_distributed_zero_first
> dist.barrier（device_ids=[local_rank]）
> 文件 “C：\Users\MH.conda\envs\pytorch\lib\site-packages\torch\distributed\distributed_c10d.py”，第 2698 行，在 barrier
> “for selected backend {}”.format（get_backend（group））
> RuntimeError： 所选后端 gloo
> 不支持函数参数 device_ids Traceback（最近调用最后一次）：
> 文件 “train.py”， 第 643 行， 在
> main（opt）
> 文件中 “train.py”， 第 539 行， 在 main
> train（opt.hyp， opt， device， callbacks）
> 文件 “train.py”， line 110， in train
> data_dict = data_dict or check_dataset（data） # 检查是否为 None
> 文件 “C：\Users\MH.conda\envs\pytorch\lib\contextlib.py”，第 88 行，**在 exit**
> next（self.gen）
> 文件中 文件“D：\deeplearning\majiang\yolov561\utils\torch_utils.py”，第 42 行，torch_distributed_zero_first
> dist.barrier（device_ids=[0]）
> 文件 “C：\Users\MH.conda\envs\pytorch\lib\site-packages\torch\distributed\distributed_c10d.py”，第 2698 行，在 barrier
> 中 “for the selected backend {}”.format（get_backend（group））
> RuntimeError：所选后端 gloo
> 不支持函数device_ids参数 错误：torch.distributed.elastic.multiprocessing.api：失败（退出代码：1）local_rank：0（pid：4352）的二进制文件：C：\Users\MH.conda\envs\pytorch\python.exe
> 回溯（最近调用最后一次）：
> 文件“C：\Users\MH.conda\envs\pytorch\lib\runpy.py”，第 193 行，_run_module_as_main
> “**main**”，mod_spec）
> 文件“C：\Users\MH.conda\envs\pytorch\lib\runpy.py”，第 85 行，_run_code exec（code， run_globals）文件“C：\Users\MH.conda\envs\pytorch\lib\site-packages\torch\distributed\run.py”，第 723 行，在 main（） 文件中文件“C：\Users\MH.conda\envs\pytorch\lib\site-packages\torch\distributed\elastic\multiprocessing\errors__init__.py”，第 345 行，包装器
> 返回 f（*args， **kwargs）
> 文件“C：\Users\MH.conda\envs\pytorch\lib\site-packages\torch\distributed\run.py”，第 719 行，在主
> 运行中（args）文件
> “C：\Users\MH.conda\envs\pytorch\lib\site-packages\torch\distributed\run.py”，第 713 行，运行中
> ）（*cmd_args）
> 文件“C：\Users\MH.conda\envs\pytorch\lib\site-packages\torch\distributed\launcher\api.py”，第 131 行，在**调用**
> 返回launch_agent（self._config，self._entrypoint， list（args））
> 文件 “C：\Users\MH.conda\envs\pytorch\lib\site-packages\torch\distributed\launcher\api.py”，第 261 行，launch_agent
> failures=result.failures，torch.distributed.elastic.multiprocessing.errors.ChildFailedError
> ：
> ## train.py FAILED
> ## Failures:
> [1]:
> time : 2022-06-21_16:01:53
> host : MH-Image
> rank : 1 (local_rank: 1)
> exitcode : 1 (pid: 17752)
> error_file: <N/A>
> traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> # Root Cause (first observed failure):
> [0]:
> time : 2022-06-21_16:01:53
> host : MH-Image
> rank : 0 (local_rank: 0)
> exitcode : 1 (pid: 4352)
> error_file: <N/A>
> traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> ### Additional
> _No response_

Hello, I would like to ask you. Finally, have you implemented distributed training on Windows with dual graphics cards? How do you do that?

**Comment by pderrenger** [comment]
@Eliana-23 Distributed training with multiple GPUs on Windows is challenging due to limitations with the 'gloo' backend that PyTorch uses on Windows by default (as seen in the error message). As Glenn mentioned, the recommended approach is to use Docker which provides a Linux environment where distributed training works properly with the NCCL backend.

You can follow the [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) to set up a containerized environment for multi-GPU training. If Docker isn't an option, alternatives include:

1. Using WSL2 (Windows Subsystem for Linux) with GPU passthrough
2. Single-GPU training with a larger batch size
3. Using Colab Pro or another cloud platform with multi-GPU support

The simplest reliable solution is to use the official Ultralytics Docker image where multi-GPU training is fully supported and tested.
