### ISSUE TITLE
input size 

### ISSUE THREAD

**Issue by WSTao** [ultralytics/yolov5#829]
## ❔Question
The size of my input image is 640*360, but the input width and height of the network are the same. I set the img-size to 480*480, the width and height ratio are not the same, will it affect the accuracy?

**Comment by glenn-jocher** [comment]
@WSTao I don't understand your question. In any case, I highly recommend training normally with default settings before thinking of modifying anything.

**Comment by Aktcob** [comment]
@WSTao it's ok training ur own datasets with 480*480. The imgsize of my datasets is not sqaure.
