### ISSUE TITLE
Add MobileOne backbone to YOLOv5

### ISSUE THREAD

**Issue by zhiqwang** [ultralytics/yolov5#8295]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Hi @glenn-jocher , [MobileOne](https://arxiv.org/abs/2206.04040) introduced by Apple is interesting, the mobile-vision team implement it at https://github.com/facebookresearch/mobile-vision/pull/91 , is there any plan to support it there? 

### Use case

![image](https://user-images.githubusercontent.com/4210061/174939870-29d4acf1-edb0-43c3-823a-dea863392c48.png)

### Additional

![image](https://user-images.githubusercontent.com/4210061/174940048-f301df15-8006-40f1-9b64-410d74bc2674.png)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by xinyiamazing** [comment]
hxd,我也想改mobileOne,但是这个mobileoneBlock的结构应该怎么设计阿，可以交流下吗

**Comment by zhiqwang** [comment]
The mobile-vision team have already implement this `MobileOneBlock` at belows:

https://github.com/facebookresearch/mobile-vision/blob/4d5207c/mobile_cv/arch/fbnet_v2/mobileone_block.py#L15

**Comment by xinyiamazing** [comment]
太感谢了！！！

**Comment by lucasjinreal** [comment]
<img width="610" alt="image" src="https://user-images.githubusercontent.com/21303438/175971583-52b0d21c-ab2f-4b94-9b05-cf6ecfdbfc92.png">

**Comment by zhiqwang** [comment]
Just FYI

 apple has released their pre-trained model at https://github.com/apple/ml-mobileone

**Comment by glenn-jocher** [comment]
@zhiqwang thanks for sharing! The pre-trained model from Apple looks impressive. We will keep an eye on related developments in the field. If you have further suggestions or questions about YOLOv5, feel free to let me know.
