### ISSUE TITLE
prioritize precision

### ISSUE THREAD

**Issue by MasIgor** [ultralytics/yolov5#8297]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello!

Is there a way to prioritize precision over recall? I have a situation where i rather miss one element than recognizing the wrong class... my goal would be to have precision 1, and recall whatever it can reach..

thank you

**Comment by glenn-jocher** [comment]
Set confidence to 1.0 then.

**Comment by MasIgor** [comment]
Thanks for the answer.. 

so far i have never seen on any image a result with confidence 1.. that would most likely end in no results at all, right? or am I misunderstanding?

Thank you

Best regards

Igor

**Comment by glenn-jocher** [comment]
@tanzerlana yes that's correct. Your precision will be 1.0 and your recall with be 0.0.
