### ISSUE TITLE
about non_max_suppression bug

### ISSUE THREAD

**Issue by konioy** [ultralytics/yolov5#8298]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

in non_max_suppression, after the second box screening, the screening results are not deduplicated。
`i, j = (x[:, 5:] > conf_thres).nonzero(as_tuple=False).T`
It is possible for a box to be predicted into multiple categories, because the category prediction uses sigmoid. 
Although the probability is low, it is still possible.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@konioy not a bug. This is the entire purpose of multilabel detection.

https://github.com/ultralytics/yolov5/blob/a2a1ed201d150343a4f9912d644be2b210206984/utils/general.py#L834-L836

**Comment by konioy** [comment]
ok，thank you!

**Comment by glenn-jocher** [comment]
@konioy you're welcome! If you have any more questions or need further assistance, feel free to ask. Keep up the great work!
