### ISSUE TITLE
为什么同一个模型参数连续训练4个完整的300轮，每一次map都不一样

### ISSUE THREAD

**Issue by lixiangyussss** [ultralytics/yolov5#8299]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

为什么同一个模型参数连续训练4个完整的300轮，每一次map都不一样,如何复现结果，是否可以设置随机种子

**Comment by Zephyr69** [comment]
I guess it's due to the randomness in dataset shuffling as well as in the heavy augmentations; you can check the code yourself. 
I don't know if there is a convenient way to make the whole process deterministic.

**Comment by glenn-jocher** [comment]
@Zephyr69 thanks for your input! The variation in mAP could indeed be the result of randomized dataset shuffling and augmentations. Achieving full determinism in training can be complex, but setting random seeds for both PyTorch and NumPy may help increase reproducibility. For more details on this, check out the Ultralytics Docs at https://docs.ultralytics.com/yolov5/. Let us know if there's anything else we can help you with.
