### ISSUE TITLE
Has anyone installed apex on windows10 successfully ?

### ISSUE THREAD

**Issue by Libaishun** [ultralytics/yolov5#83]
I train yolov5s on windows10, 2080Ti, it costs above one hour per epoch, I tried install apex to boost training speed, but failed.

**Comment by glenn-jocher** [comment]
@Libaishun training times are shown here for V100, 2080Ti is maybe 80% as fast, so you should see 15-20min per coco epoch.
https://github.com/ultralytics/yolov5#reproduce-our-training

Windows is a terrible environment in general for ML. You should probably train within our docker image instead.

## Reproduce Our Environment

To access an up-to-date working environment (with all dependencies including CUDA/CUDNN, Python and PyTorch preinstalled), consider a:

- **GCP** Deep Learning VM with $300 free credit offer: See our [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Google Colab Notebook** with 12 hours of free GPU time. <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/)
