### ISSUE TITLE
why is loss multipled by world_size during ddp training?

### ISSUE THREAD

**Issue by LukeCho-8810** [ultralytics/yolov5#8301]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hi, thanks for your great work.
why is loss multipled by world_size during ddp training?
https://github.com/ultralytics/yolov5/blob/a2a1ed201d150343a4f9912d644be2b210206984/train.py#L355

**Comment by glenn-jocher** [comment]
@LukeCho-8810 compensates for multigpu loss

**Comment by neesetifa** [comment]
> @LukeCho-8810 compensates for multigpu loss

Could you please explain more about this? I wasn't able to find any theory or official document about this, I thought ddp has done everything.
