### ISSUE TITLE
about conf_thres issues

### ISSUE THREAD

**Issue by konioy** [ultralytics/yolov5#8302]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

In the post-processing, the prediction box is filtered three times, the first time is based on the obj confidence, the second is based on the cls confidence (obj*cls), and the third is NMS. 
How should this threshold be set for the first two times for different models? 
In the current project, the first and second confidences use the same value, can different values be set? 
Will this improve recall or improve precision?

**Comment by devendraswamy** [comment]
Same Question here , Did you find the solution for this ?

**Comment by glenn-jocher** [comment]
@konioy confidence is very simple. Higher confidence always improves precision and reduces recall.
