### ISSUE TITLE
YOLO5 : ModuleNotFoundError: No module named 'utils.datasets'

### ISSUE THREAD

**Issue by aliaminibagh** [ultralytics/yolov5#8304]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am running a Yolo5 docker and want to import the `train.py` file in the yolov5 repository to my code. The structure of my files is as follows:
![Screenshot from 2022-06-22 15-54-38](https://user-images.githubusercontent.com/59368585/175020052-551399c0-c7d1-4b98-9a7d-830bda2a9e17.png)

when I create the docker image and run `main_train.py `as follows :

main_train.py:

`from yolov5 import train`

I get this error message.

```
Traceback (most recent call last):
File "main_train.py", line 1, in <module>
from yolov5 import train
File "/code/yolov5/train.py", line 40, in <module>
import val  # for end-of-epoch mAP
File "/code/yolov5/val.py", line 37, in <module>
from models.common import DetectMultiBackend
File "/code/yolov5/models/common.py", line 24, in <module>
from utils.dataloaders import exif_transpose, letterbox
ModuleNotFoundError: No module named 'utils.dataloaders'
yolov5-train exited with code 1
```

Help to fix it.

**Comment by SuperbTUM** [comment]
@aliaminibagh How did you solve this problem? Thanks!

**Comment by dchaplinsky** [comment]
@aliaminibagh @SuperbTUM I think you need to import it from utils.augmentations
