### ISSUE TITLE
Multiple classes detecting for single object

### ISSUE THREAD

**Issue by Roshan75** [ultralytics/yolov5#8305]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have created a custom model using ultralytics-yolov5. I'm facing a problem is sometimes multiple classes detects for a single object. How to get rid of this? Whether any inbuilt solution there for this?
[x1, y1, x2, y2, class, conf] - list format
([89.50, 138.12, 141.11, 200.74, 9, '0.89'], [89.99, 137.28, 143.58, 203.37, 6, '0.60']) - overlapped classes details

**Comment by barney2074** [comment]
in detect.py, you have a few parameters- I'd try different combinations of these
I'd assume if you set --max-det = 1, it just shows the best one

```
parser.add_argument('--conf-thres', type=float, default=0.25, help='confidence threshold')
parser.add_argument('--iou-thres', type=float, default=0.45, help='NMS IoU threshold')
parser.add_argument('--max-det', type=int, default=1000, help='maximum detections per image')
```

**Comment by sezer-muhammed** [comment]
there is agnostic nms option which allow you to filter classes together. If you use it the code will filter all multiple classes.

**Comment by glenn-jocher** [comment]
@sezer-muhammed you're correct! Using the `--agnostic-nms` option in YOLOv5 will perform nms (non-maximum suppression) independently for each class, eliminating multiple detections of the same object across different classes. This can be a helpful approach to filter out the multiple class detections issue you've encountered.
