### ISSUE TITLE
AttributeError: Can't get attribute 'StemBlock' on <module 'models.common' from '/yolov5/models/common.py'>

### ISSUE THREAD

**Issue by Raymon360** [ultralytics/yolov5#8307]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

I am trying to train yolov5 model for face dataset but getting problem as stated in problem title. I used the pre-training model yolov5s face "https://drive.google.com/file/d/1zxaHeLDyID9YU4-hqK7KNepXIwbTkRIO/view?usp=sharing" in the training, but it caused a problem that I don't understand. Can anyone help to solve this problem and why it occurs?

### Environment

YOLOv5 🚀 v6.1-259-ga2a1ed2 Python-3.7.13 torch-1.11.0+cu113 CUDA:0 (Tesla T4, 15110MiB)
Python 3

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
Your pre-trained serialised model is trying to load a block called `StemBlock` which is not a part of official YOLOv5. See the file [models/common.py](https://github.com/ultralytics/yolov5/blob/master/models/common.py).
You're probably using a model trained on a modified fork of this repo.

**Comment by Raymon360** [comment]
> Model serial Anda yang telah dilatih sebelumnya mencoba memuat blok bernama `StemBlock`yang bukan merupakan bagian dari YOLOv5 resmi. Lihat file [model/common.py](https://github.com/ultralytics/yolov5/blob/master/models/common.py) . Anda mungkin menggunakan model yang dilatih pada garpu yang dimodifikasi dari repo ini.

Thanks for the explanation

**Comment by glenn-jocher** [comment]
@Raymon360 you're welcome! If you need further assistance, feel free to ask. Good luck with your YOLOv5 project!

**Comment by URS1023** [comment]
> 您的预训练序列化模型正在尝试加载一个名为的块，该块不是官方 YOLOv5 的一部分。请参阅文件 [models/common.py](https://github.com/ultralytics/yolov5/blob/master/models/common.py)。你可能正在使用在此存储库的修改分支上训练的模型。`StemBlock`

Thank you for your help

**Comment by glenn-jocher** [comment]
You're welcome, @URS1023! If you have any more questions or need further assistance, feel free to ask. Wishing you success with your YOLOv5 project!
