### ISSUE TITLE
BN and Activation before CONCAT or after CONCAT

### ISSUE THREAD

**Issue by sdreamforchen** [ultralytics/yolov5#8309]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

    Hello, I have a question about the position of BN 、Activation and Concat: BN and Activation before CONCAT or after CONCAT,which is better, do you test this?
   Thanks!

**Comment by glenn-jocher** [comment]
@sdreamforchen hi there,

Great question! Our YOLOv5 default architecture places batch normalization (BN) and activation before concatenation. Our testing has shown this to work effectively for object detection purposes. 

Feel free to refer to our [Ultralytics Docs](https://docs.ultralytics.com/yolov5/) for more detailed information on YOLOv5 architecture and best practices.

Let us know if you have further questions or need assistance with anything else. Cheers!
