### ISSUE TITLE
How to crop-save more than 1 image file?

### ISSUE THREAD

**Issue by Raymon360** [ultralytics/yolov5#8310]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to crop-save more than 1 image file in multiple folders with size according to trained detection model bounding box?

**Comment by barney2074** [comment]
In detect.py- you have the --save-crop option

**Comment by glenn-jocher** [comment]
@Raymon360 👋 Hello! Thanks for asking about **cropping results** with YOLOv5 🚀.  Cropping bounding box detections can be useful for training classification models on box contents for example. This feature was added in PR https://github.com/ultralytics/yolov5/pull/2827. You can crop detections using either detect.py or YOLOv5 PyTorch Hub:

## detect.py
Crops will be saved under `runs/detect/exp/crops`, with a directory for each class detected.
```bash
python detect.py --save-crop
```
<img width="450" alt="Original" src="https://user-images.githubusercontent.com/26833433/139577918-65cc8f5d-741d-4a88-8753-0154013c624d.jpg">

<img width="1067" alt="Crop" src="https://user-images.githubusercontent.com/26833433/139577896-aa26b07c-466d-4057-9bfe-b01b56007587.png">

## YOLOv5 PyTorch Hub
Crops will be saved under `runs/detect/exp/crops` if `save=True`, and also returned as a dictionary with crops as numpy arrays.
```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, custom

# Images
img = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, PIL, OpenCV, numpy, list

# Inference
results = model(img)

# Results
crops = results.crop(save=True)  # or .show(), .save(), .print(), .pandas(), etc.
```

Good luck 🍀 and let us know if you have any other questions!

**Comment by Raymon360** [comment]
> @Raymon360 👋Halo! Terima kasih telah bertanya tentang **hasil cropping** dengan YOLOv5🚀. Memotong deteksi kotak pembatas dapat berguna untuk melatih model klasifikasi pada isi kotak misalnya. Fitur ini ditambahkan di PR #2827 . Anda dapat memotong deteksi menggunakan detect.py atau YOLOv5 PyTorch Hub:
> 
> ## deteksi.py
> Tanaman akan disimpan di bawah `runs/detect/exp/crops`, dengan direktori untuk setiap kelas terdeteksi.
> 
> ```shell
> python detect.py --save-crop
> ```
> 
> <img alt="Asli" width="450" src="https://user-images.githubusercontent.com/26833433/139577918-65cc8f5d-741d-4a88-8753-0154013c624d.jpg">
> 
> <img alt="Tanaman" width="1067" src="https://user-images.githubusercontent.com/26833433/139577896-aa26b07c-466d-4057-9bfe-b01b56007587.png">
> 
> ## Pusat PyTorch YOLOv5
> Tanaman akan disimpan di bawah `runs/detect/exp/crops`if `save=True`, dan juga dikembalikan sebagai kamus dengan tanaman sebagai array numpy.
> 
> ```python
> import torch
> 
> # Model
> model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, custom
> 
> # Images
> img = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, PIL, OpenCV, numpy, list
> 
> # Inference
> results = model(img)
> 
> # Results
> crops = results.crop(save=True)  # or .show(), .save(), .print(), .pandas(), etc.
> ```
> 
> Semoga beruntung🍀dan beri tahu kami jika Anda memiliki pertanyaan lain!

Thanks for the response, but can cut save detection be used to detect more than (say 10 images per class) at once?

**Comment by Raymon360** [comment]
> @Raymon360 👋Halo! Terima kasih telah bertanya tentang **hasil cropping** dengan YOLOv5🚀. Memotong deteksi kotak pembatas dapat berguna untuk melatih model klasifikasi pada isi kotak misalnya. Fitur ini ditambahkan di PR #2827 . Anda dapat memotong deteksi menggunakan detect.py atau YOLOv5 PyTorch Hub:
> 
> ## deteksi.py
> Tanaman akan disimpan di bawah `runs/detect/exp/crops`, dengan direktori untuk setiap kelas terdeteksi.
> 
> ```shell
> python detect.py --save-crop
> ```
> 
> <img alt="Asli" width="450" src="https://user-images.githubusercontent.com/26833433/139577918-65cc8f5d-741d-4a88-8753-0154013c624d.jpg">
> 
> <img alt="Tanaman" width="1067" src="https://user-images.githubusercontent.com/26833433/139577896-aa26b07c-466d-4057-9bfe-b01b56007587.png">
> 
> ## Pusat PyTorch YOLOv5
> Tanaman akan disimpan di bawah `runs/detect/exp/crops`if `save=True`, dan juga dikembalikan sebagai kamus dengan tanaman sebagai array numpy.
> 
> ```python
> import torch
> 
> # Model
> model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, custom
> 
> # Images
> img = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, PIL, OpenCV, numpy, list
> 
> # Inference
> results = model(img)
> 
> # Results
> crops = results.crop(save=True)  # or .show(), .save(), .print(), .pandas(), etc.
> ```
> 
> Semoga beruntung🍀dan beri tahu kami jika Anda memiliki pertanyaan lain!

Thanks for the response, but can cut save detection be used to detect multiple image files at once?

e.g. 10 images from each subfolder

**Comment by Raymon360** [comment]
Thanks for the response, but can cut save detection be used to detect multiple image files at once?

e.g. 10 images from each subfolder

**Comment by barney2074** [comment]
@Raymon360 
you might need to provide more info- sample, screenshot etc, or at least describe what you are doing
It sounds like you are feeding in a single image to detect.py. If you input multiple images (a folder, or glob path)- then you'll get multiple cropped outputs

**Comment by Raymon360** [comment]
> you might need to provide more info- sample, screenshot etc, or at least describe what you are doing
> It sounds like you are feeding in a single image to detect.py. If you input multiple images (a folder, or glob path)- then you'll get multiple cropped outputs

can you provide a code example of what you are describing?

**Comment by barney2074** [comment]
Yolov5/Ultralytics documentation is pretty good- I'd start by reading it
![image](https://user-images.githubusercontent.com/25944617/175483869-8c142642-0c4c-4477-b929-bc8c80ecb735.png)

**Comment by Raymon360** [comment]
oh I just got it, thanks for helping me @barney2074 and @glenn-jocher

**Comment by Raymon360** [comment]
> Yolov5/Ultralytics documentation is pretty good- I'd start by reading it ![image](https://user-images.githubusercontent.com/25944617/175483869-8c142642-0c4c-4477-b929-bc8c80ecb735.png)

![image](https://user-images.githubusercontent.com/77184835/175518138-c89b9c52-e581-475d-8a14-fe882263081c.png)

When I try it, the system can only work on 1 folder. How to make the system work if you have a lot of subfolders?
For example: "folders/subfolders/files"

**Comment by glenn-jocher** [comment]
@Raymon360 google glob documentation if you're not familiar with it

**Comment by Raymon360** [comment]
> @Raymon360 google glob documentation if you're not familiar with it

![image](https://user-images.githubusercontent.com/77184835/175612700-0886e8be-80fe-433e-bc5b-215e7a0824b4.png)
I ran into an error while running this. Is there something wrong with writing my code?
