### ISSUE TITLE
RuntimeError: result type Float can't be cast to the desired output type long int

### ISSUE THREAD

**Issue by IncubatorShokuhou** [ultralytics/yolov5#8314]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

Traceback (most recent call last):
  File "/mnt/data/yolov5/train.py", line 667, in <module>
    main(opt)
  File "/mnt/data/yolov5/train.py", line 562, in main
    train(opt.hyp, opt, device, callbacks)
  File "/mnt/data/yolov5/train.py", line 350, in train
    loss, loss_items = compute_loss(pred, targets.to(device))  # loss scaled by batch_size
  File "/mnt/data/yolov5/utils/loss.py", line 125, in __call__
    tcls, tbox, indices, anchors = self.build_targets(p, targets)  # targets
  File "/mnt/data/yolov5/utils/loss.py", line 229, in build_targets
    indices.append((b, a, gj.clamp_(0, gain[3] - 1), gi.clamp_(0, gain[2] - 1)))  # image, anchor, grid indices
RuntimeError: result type Float can't be cast to the desired output type long int

### Environment

 - YOLO:YOLOv5 🚀 v6.1-177-gd059d1d torch 1.13.0.dev20220606 CUDA:0 (NVIDIA A100-PCIE-40GB, 40354MiB)
 - OS: ubuntu20.04
 - Python: 3.9.13

### Minimal Reproducible Example

python train.py --data coco128.yaml --cfg yolov5x.yaml --weights '' --batch-size -1

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by IncubatorShokuhou** [comment]
The cause of the error found. Close this issue.

**Comment by glenn-jocher** [comment]
@IncubatorShokuhou code is out of date, please update as line has been changed to fix this:
https://github.com/ultralytics/yolov5/blob/a2a1ed201d150343a4f9912d644be2b210206984/utils/loss.py#L229

**Comment by funnyguagua** [comment]
> @IncubatorShokuhou代码已过期，请更新行已更改以解决此问题：
> 
> https://github.com/ultralytics/yolov5/blob/a2a1ed201d150343a4f9912d644be2b210206984/utils/loss.py#L229

![SMP`7O2LCRU9MYOY4`XSG2O](https://user-images.githubusercontent.com/59008643/176911284-4cd67167-862f-4bf6-9486-7fbcef809ba7.png)

After modifying that line, this problem arises, how to solve it?

**Comment by funnyguagua** [comment]
> @IncubatorShokuhou code is out of date, please update as line has been changed to fix this:
> 
> https://github.com/ultralytics/yolov5/blob/a2a1ed201d150343a4f9912d644be2b210206984/utils/loss.py#L229
![(TN)8I2 S02(Q@3XXE2_FOA](https://user-images.githubusercontent.com/59008643/176932944-cb265e30-d354-4629-9213-8195ccb6cf15.png)

After modifying this code, this problem arises, how to solve it?

**Comment by glenn-jocher** [comment]
@funnyguagua to update your code:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

**Comment by funnyguagua** [comment]
> @funnyguagua to update your code:
> 
> * **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
> * **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
> * **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  [![Open In Colab](https://camo.githubusercontent.com/84f0493939e0c4de4e6dbe113251b4bfb5353e57134ffd9fcab6b8714514d4d1/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb) [![Open In Kaggle](https://camo.githubusercontent.com/a08ca511178e691ace596a95d334f73cf4ce06e83a5c4a5169b8bb68cac27bef/68747470733a2f2f6b6167676c652e636f6d2f7374617469632f696d616765732f6f70656e2d696e2d6b6167676c652e737667)](https://www.kaggle.com/models/ultralytics/yolov5)
> * **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image [![Docker Pulls](https://camo.githubusercontent.com/280faedaf431e4c0c24fdb30ec00a66d627404e5c4c498210d3f014dd58c2c7e/68747470733a2f2f696d672e736869656c64732e696f2f646f636b65722f70756c6c732f756c7472616c79746963732f796f6c6f76353f6c6f676f3d646f636b6572)](https://hub.docker.com/r/ultralytics/yolov5)

Thanks.

**Comment by pderrenger** [comment]
You're welcome! If you encounter any further issues, please ensure you're using the latest version of YOLOv5. If the problem persists, feel free to provide more details.
