### ISSUE TITLE
What does this mean and how can we set it?

### ISSUE THREAD

**Issue by aktiver** [ultralytics/yolov5#8320]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

_Upon training I get a warning that says:_
```
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
```
1. How do we know what NUM of THREADS we have?
2. How can we set it?

**Comment by glenn-jocher** [comment]
@aktiver this is a variable to control multithreading in some packages. You can define any environment variables easily, i.e.
```
$ OMP_NUM_THREADS=8
```

**Comment by aktiver** [comment]
@glenn-jocher yes, but what im asking is how can we find out what number (int) we can add to that variable? i'm assuming its a linux cmd that gets cores/threads

**Comment by glenn-jocher** [comment]
@aktiver htop shows general system info in linux
