### ISSUE TITLE
Have you used 640*640 resolution to train yolov5l6?

### ISSUE THREAD

**Issue by 2605759123** [ultralytics/yolov5#8321]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,Thank you for yor great works.
Have you used 640*640 resolution to train yolov5l6?
If yes, then you can tell me the result？It can also be a rough result.

**Comment by glenn-jocher** [comment]
@2605759123 P6 models are trained at --img 1280. You can validate at any size, i.e.:

```
python val.py --img 640 --weights yolov5l6.pt --data coco.yaml
```

**Comment by 2605759123** [comment]
> @2605759123 P6 models are trained at --img 1280. You can validate at any size, i.e.:
> 
> ```
> python val.py --img 640 --weights yolov5l6.pt --data coco.yaml
> ```
Thank you for your reply. 
Yeah. I know that P6 models are trained at --img 1280 and can be validated at any size.
Actually, I make some modification for yolov5l6. But due to hardware performance, it is hard for me to retrain modified model with --img 1280, so I retrain it with --img 640. The result of the modified model(640) are between yolov5l(640) and yolov5l6(1280). My model are based on yolov5l6 so I want know the rough result of yolov5l6 with --img 640.

**Comment by glenn-jocher** [comment]
@2605759123 run this command to answer your question:
```
python val.py --img 640 --weights yolov5l6.pt --data coco.yaml
```

**Comment by 2605759123** [comment]
> @2605759123 run this command to answer your question:
> 
> ```
> python val.py --img 640 --weights yolov5l6.pt --data coco.yaml
> ```

Yeah. But I think it have a bit difference. It validate with --img 640 but the weight also be trained with --img 1280.
