### ISSUE TITLE
How to set imgsize 1280*720 for training in YOLOv5??

### ISSUE THREAD

**Issue by gjgjos** [ultralytics/yolov5#8322]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

For training on YOLOv5, in train.py, images size is square. For example, default images size is 640X640. 
I saw that, the best thing to detect(test) is that, it is best to train images with the same resolution of test images. 
Unfortunately, my final detected image is 1280X720 which is CCTV. Therefore, I want to train images with 1280X720. I set my dataset images with 1280X720, but I don't find the way to set (1280,720) for training in YOLOv5.
Belows are train.py. There is only one number on '--imgsz' for square, not (width,height). 
![image](https://user-images.githubusercontent.com/76835329/175462398-4be8ee7b-2bcf-4de8-9c52-6bc8bbf25800.png)

This is detect.py. In def run, we can set retangular shape of imgsz. But, in def parse_opt, it's also only one number on '--imgsz' for square.
![image](https://user-images.githubusercontent.com/76835329/175462516-54fd98bb-6115-4116-9404-0a5af2da8945.png)
![image](https://user-images.githubusercontent.com/76835329/175462479-ba357120-876d-4894-8d73-c2b0346ddfd5.png)

**Is there no way to set imgsize 1280*720 for training in YOLOv5??**

**Comment by glenn-jocher** [comment]
@gjgjos `python train.py --img 1280 --rect`

**Comment by gjgjos** [comment]
> @gjgjos `python train.py --img 1280 --rect`

Thank you! Then, how to set vertical length of rectangular, 720 ??

**Comment by glenn-jocher** [comment]
@gjgjos --img specifies long side. Short side is solved for automatically.

**Comment by gjgjos** [comment]
> @gjgjos --img specifies long side. Short side is solved for automatically.

Thank you very much!! I solved the problem thanks to you. Amazing haha!!
