### ISSUE TITLE
Dataloader: Why shuffle=False if --rect is used?

### ISSUE THREAD

**Issue by UnglvKitDe** [ultralytics/yolov5#8328]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello all,
first, thanks for all the work on yolov5! The network works very well for me. One point I don't understand is why shuffle is set to false when using --rect?

**Comment by glenn-jocher** [comment]
@UnglvKitDe --rect sorts dataset by aspect ratio to present minimum viable size batches. Shuffling is incompatible with this.

**Comment by UnglvKitDe** [comment]
@glenn-jocher ah ok, thank you for the clarification! :)

**Comment by glenn-jocher** [comment]
You're welcome, @UnglvKitDe! If you have any more questions, feel free to ask. Your support is appreciated in making YOLOv5 better for everyone!
