### ISSUE TITLE
Image segmentation update

### ISSUE THREAD

**Issue by arponitis** [ultralytics/yolov5#8334]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

is there any update with the image segmentation using yolov5 @glenn-jocher ?

**Comment by glenn-jocher** [comment]
@arponitis thanks for asking about segmentation! Segmentation is under development and on our roadmap in https://github.com/orgs/ultralytics/projects/6
