### ISSUE TITLE
Yolov5 on video 

### ISSUE THREAD

**Issue by MACHMR2010** [ultralytics/yolov5#8337]
I want to create demo gradio for yolov5 detection on video....
I have this error ... How Can I use it on video using gradio interface 
I try to modify the code of images but it doesn't work 
![errrooor.PNG](https://user-images.githubusercontent.com/106706409/175766494-d51a7eee-abea-4c6b-a121-decb9cc75f47.PNG)
Please give me a solution for that

**Comment by barney2074** [comment]
I'm not familiar with gradio- but it looks like you would be able to use Yolov5 detect.py, which takes a video as an argument ??

![image](https://user-images.githubusercontent.com/25944617/175799895-d7b858a1-22a9-42e0-b55c-c47b2890a2f6.png)

**Comment by Guttappa1238** [comment]
> I want to create demo gradio for yolov5 detection on video.... I have this error ... How Can I use it on video using gradio interface I try to modify the code of images but it doesn't work ![errrooor.PNG](https://user-images.githubusercontent.com/106706409/175766494-d51a7eee-abea-4c6b-a121-decb9cc75f47.PNG) Please give me a solution for that

Hi @MACHMR2010, Are you running the same code as shown in image? and what is the error?
and in code there is indentation you need to give inside the function `fn` .

**Comment by MACHMR2010** [comment]
@Guttappa1238  


I just want to help me identify the fn function to do the detection on a video used yolov5 ... I don't know which instruction I should use
