### ISSUE TITLE
How Can I create a gradio demo for yolov5 detection on video

### ISSUE THREAD

**Issue by MACHMR2010** [ultralytics/yolov5#8340]
I try modify the exemple of gradio demo yolov5 to detect on video but it doesn't work ... Please tell me how Can I use Yolov5 in gradio demo to detect objects on video

**Comment by glenn-jocher** [comment]
@MACHMR2010 YOLOv5 video inference is extremely simple:
```
python detect.py --source video.mp4
```

**Comment by MACHMR2010** [comment]
@glenn-jocher  want to use it in demo gradio please like the exemple of images

**Comment by glenn-jocher** [comment]
@MACHMR2010 questions regarding 3rd party tools are probably best addressed by their authors

**Comment by MACHMR2010** [comment]
@glenn-jocher  

No one gives me an answer for this question
 ![Screenshot_2022-06-26-15-05-41-97_320a9a695de7cdce83ed5281148d6f19.jpg](https://user-images.githubusercontent.com/106706409/175818212-ca053831-1940-4098-bf9e-b0fac03fbdb5.jpg)
  I must find a solution because it is my end of study project

**Comment by glenn-jocher** [comment]
@MACHMR2010 i understand the importance of your project. For YOLOv5 video inferencing you could try out the code I mentioned and then integrate it with gradio's video input and output functionality. You can find more info in the Gradio documentation. Good luck!
