### ISSUE TITLE
Yolov5 as university course

### ISSUE THREAD

**Issue by sezer-muhammed** [ultralytics/yolov5#8342]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I want to understand and learn all of the yolov5 work done. That includes data loader, model, model training, augmentation, saver, logger, and all other functions.

This repo contains more information than all AI lessons.

I just saw there are some schematics for some operations such as augmentation and model architecture, but there are not well organized.

So I just wonder if is there any documentation that I can understand, learn, and read all the code?

I am reading and understanding the code from their .py files but I want to also understand and read it like documentation like opencv's docs.

nevertheless, yolov5 is the best repo I have ever seen, and thanks for this huge repo!!

**Comment by glenn-jocher** [comment]
@sezer-muhammed thank you for your feedback! Documentation is a weak point we'd like to improve. We currently have some light docs at https://docs.ultralytics.com/ that need improvement. Most content can be found at our wiki here, including all the main tutorials:
https://github.com/ultralytics/yolov5/wiki

## Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️  RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Roboflow for Datasets, Labeling, and Active Learning](https://docs.ultralytics.com/yolov5/tutorials/roboflow_datasets_integration)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)
