### ISSUE TITLE
What does box loss mean during training?

### ISSUE THREAD

**Issue by udnqv** [ultralytics/yolov5#8353]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,
I'm training a model. During the training there are three values displayed: box, obj and cls. Could someone explain to me what exactly these three describe? On the last two values I can imagine what I means, but i have absolutely no clue what 'box' means. Help would be highly appreciated. Thank you in advance!

**Comment by glenn-jocher** [comment]
@udnqv box regression loss
