### ISSUE TITLE
AttributeError: 'DetectMultiBackend' object has no attribute 'input_details'

### ISSUE THREAD

**Issue by Zrmikstri** [ultralytics/yolov5#8354]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Validation

### Bug

I just got this error which I have not met before. Yesterday val.py still working, but for some reason i got this error this evening. I have used git pull to update the repo and still got this error. 
Hope somebody can explain to me. Thank you very much.
![image](https://user-images.githubusercontent.com/86789105/175933657-9a14a48c-299b-467a-8980-b2e156e6061d.png)

### Environment

Using colab free with Tesla T4 gpu. 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Zrmikstri** [comment]
Turns out, i forgot to include the weight. Sorry for the trouble.

**Comment by glenn-jocher** [comment]
@Zrmikstri no problem at all! It happens to the best of us. I'm glad you were able to identify the issue. If you have any more questions or run into any problems, feel free to ask. Good luck with your project!
