### ISSUE TITLE
How do I select a different camera?

### ISSUE THREAD

**Issue by jinzishuai** [ultralytics/yolov5#836]
## ❔Question

I know I can use `python detect.py --source 0` to use my webcam and it works well.  My problem is that I don't know how to switch to other cameras if I have multiple ones.

I thought I could just use `--source 1` but it didn't work and I got this:
```
$ python detect.py --source 1
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.4, device='', img_size=640, iou_thres=0.5, output='inference/output', save_txt=False, source='1', update=False, view_img=False, weights='yolov5s.pt')
Using CPU

Fusing layers... 
Model Summary: 140 layers, 7.45958e+06 parameters, 6.61683e+06 gradients
Traceback (most recent call last):
  File "detect.py", line 173, in <module>
    detect()
  File "detect.py", line 55, in detect
    dataset = LoadImages(source, img_size=imgsz)
  File "/home/zerobox/Documents/yolov5/utils/datasets.py", line 86, in __init__
    raise Exception('ERROR: %s does not exist' % p)
Exception: ERROR: /home/zerobox/Documents/yolov5/1 does not exist
```

I briefly looked at the code and it seems that `source==0` is a special condition to trigger camera but I don't see any optiton to switch between cameras.   

May I please get some advice? Thank you in advance.

## Additional context

I have 4 cameras in this case:
```
$ v4l2-ctl --list-devices
HD Pro Webcam C920 (usb-0000:00:14.0-1):
	/dev/video0
	/dev/video1

HD Pro Webcam C920 (usb-0000:00:14.0-2):
	/dev/video2
	/dev/video3

HD Pro Webcam C920 (usb-0000:00:14.0-4):
	/dev/video4
	/dev/video5

HD Pro Webcam C920 (usb-0000:00:14.0-5):
	/dev/video6
	/dev/video7
```

**Comment by glenn-jocher** [comment]
@jinzishuai this is simply a pass through for the main opencv commands. You should google the proper commands for opening alternate cameras in opencv in your OS, for example:
https://answers.opencv.org/question/190710/how-do-i-choose-which-camera-i-am-accessing/

Once you can access these with opencv directly using the python cv2 package, them post an update and we might be able to work on a PR to allow secondary local camera access.

**Comment by jinzishuai** [comment]
Hi @glenn-jocher thank you for the insight.

I think you are right. I had another machine where the `/dev/video0` does not work and the real usb camera is at `/dev/video14`.

I got an error using `python detect.py --source 0`
```
seki@seki-Surface-Book:~/src/yolov5$ python detect.py --source 0
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.4, device='', img_size=640, iou_thres=0.5, output='inference/output', save_txt=False, source='0', update=False, view_img=False, weights='yolov5s.pt')
Using CPU

Fusing layers... 
Model Summary: 140 layers, 7.45958e+06 parameters, 6.61683e+06 gradients
[ WARN:0] global /tmp/pip-req-build-6179nsls/opencv/modules/videoio/src/cap_v4l.cpp (893) open VIDEOIO(V4L2:/dev/video0): can't open camera by index
1/1: 0... Traceback (most recent call last):
  File "detect.py", line 173, in <module>
    detect()
  File "detect.py", line 52, in detect
    dataset = LoadStreams(source, img_size=imgsz)
  File "/home/seki/src/yolov5/utils/datasets.py", line 239, in __init__
    assert cap.isOpened(), 'Failed to open %s' % s
AssertionError: Failed to open 0
seki@seki-Surface-Book:~/src/yolov5$ 
```

It seems that OpenCV only opens /dev/video0 by default. 

I haven't looked deep into the code yet but I have figured out a workaround.

## Workaround  by using http streaming via VLC

* First, set up streaming using VLC
```
cvlc -vvv v4l2:///dev/video14 --sout '#standard{access=http,mux=ogg,dst=localhost:8080}'
```
* then we can use YOLOv5 to take the http stream as input
```
python3 detect.py --source http://localhost:8080
```

**Comment by glenn-jocher** [comment]
@jinzishuai just pushed a webcam selection fix that may allow you to select alternate local cams in https://github.com/ultralytics/yolov5/commit/82ed33a052081f122df7cc8b94e7009d7ec35c2d.

This generalizes for any numeric source, i.e. `python detect.py --source 5` will try to load a cv2 webcam as  `cap = cv2.VideoCapture(5)`

**Comment by glenn-jocher** [comment]
@jinzishuai the http source idea is creative btw, good idea. You can also run realtime multi-stream inference by passing a txtfile of stream addresses: python detect.py --source streams.txt

**Comment by jinzishuai** [comment]
@glenn-jocher  you are amazing!

I can confirm that the new feature is working and even better, I got
```
yolov5$ cat 4cams.txt 
0
2
4
6
```
and as you mentioned, I am now able to detect all four cameras at the same time with `python detect.py --source 4cams.txt `.

Very impressive! Thank you very much.

**Comment by glenn-jocher** [comment]
Great!

**Comment by Chuttyboy** [comment]
> Great!

@glenn-jocher  I used 2 webcam for object detection and it work very well. but i wanna store crop results in 2 seperate folder. how can i save result in different folder

Thanks

**Comment by glenn-jocher** [comment]
@Chuttyboy every run is already saved in a different folder by default, i.e. runs/detect/exp1, exp2, etc.

**Comment by Chuttyboy** [comment]
> . runs/detect/

Thanks for you quick reply 

![data](https://user-images.githubusercontent.com/79959547/159120971-c5cdec0e-6e93-4127-8011-90fa328164b8.png)

See this  ` python3 detect.py --source stream.txt --save-crop` i run this command but output saved in same folder

```
stream.txt file :
0
3
```

**Comment by Chuttyboy** [comment]
> @Chuttyboy every run is already saved in a different folder by default, i.e. runs/detect/exp1, exp2, etc.

@glenn-jocher 

actually my query is save result of every camera into different folder. 

ex : cam 1 and cam 2 

```
run 
   - detect
        - exp 
            - cam 1
            - cam 2
```

I  expected results like this how i can do this???
