### ISSUE TITLE
QUES: best.pt, last.pt or...

### ISSUE THREAD

**Issue by daddydrac** [ultralytics/yolov5#8360]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

The cli hangs once training is completed with:
```
Results saved to runs/train/exp
Destroying process group... 

```
This does appear to be harmless, as it saves the files and models. My question is this:

- Was the intent to store the 2 models (best.pt, last.pt), or combine them into one at the end?

- If there is a way to clear up this (what seems to be) harmless error?

### Additional

Similar issue for "launch" cmd listed here, however, I am using "run" cmd.
https://github.com/ultralytics/yolov5/issues/4414

**Comment by glenn-jocher** [comment]
@salinaaaaaa all DDP trainings should be run in our Docker image below.


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>
