### ISSUE TITLE
What could be causing this error?

### ISSUE THREAD

**Issue by daddydrac** [ultralytics/yolov5#8361]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

The output shows I am running  ```Python-3.8.13 torch-1.11.0+cu102```, however I have installed...```

**Torch and CUDA arch:**
```
 import torch
 torch.__version__
'1.9.1'

torch.cuda.get_arch_list()
['sm_52', 'sm_60', 'sm_61', 'sm_70', 'sm_75', 'sm_80', 'sm_86', 'compute_86']
```

**CUDA Version:**
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0
```

**Docker image:**
```nvidia/cuda:11.4.2-runtime-ubuntu18.04```

**CLI error output:**
```
python -m torch.distributed.run --nproc_per_node 8 train.py --batch-size 256 --data coco128.yaml --weights [yolov5s.pt](http://yolov5s.pt/) --device 0,1,2,3,4,5,6,7 --epochs 3 

UserWarning:
NVIDIA RTX A6000 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA RTX A6000 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
YOLOv5 🚀 2022-6-27 Python-3.8.13 torch-1.11.0+cu102 CUDA:0 (NVIDIA RTX A6000, 48685MiB)
                                                     CUDA:1 (NVIDIA RTX A6000, 48685MiB)
                                                     CUDA:2 (NVIDIA RTX A6000, 48685MiB)
                                                     CUDA:3 (NVIDIA RTX A6000, 48685MiB)
                                                     CUDA:4 (NVIDIA RTX A6000, 48685MiB)
                                                     CUDA:5 (NVIDIA RTX A6000, 48685MiB)
                                                     CUDA:6 (NVIDIA RTX A6000, 48685MiB)
                                                     CUDA:7 (NVIDIA RTX A6000, 48685MiB)  

Added key: store_based_barrier_key:1 to store for rank: 0
/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py:145: UserWarning:
NVIDIA RTX A6000 with CUDA capability sm_86 is not compatible with the current PyTorch installation.

WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1014 closing signal SIGTERM

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 4 (pid: 1018) of binary: /usr/local/bin/python
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 728, 
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@salinaaaaaa you should run all DDP trainings in our Docker image for maximum compatibility

**Comment by glenn-jocher** [comment]
## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>
