### ISSUE TITLE
Recommended GPU for training yolov5 under 1 hour

### ISSUE THREAD

**Issue by Pedro-Leitek** [ultralytics/yolov5#8363]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, 

Weeks ago I trained yolov5 on a custom dataset. The thing is, it took 2 and a half days to train 100 epochs on a batch of 32 images with image size 160. I used my GTX 1660 super to train it. If I try to use a bigger image size the gpu gets a out of memory error. More epochs would extend the training time.
So, is there any graphic card on the market that through Microsoft Azure, I can train my model under 1 hour (300 epochs, batch 64, image size 640)?

Thanks

**Comment by Denizzje** [comment]
There are various factors at play, such as number of classes, amount of images, and the Yolo size you are using for instance. But I do not think with the model you are training, if you have 2,5 days on a GTX 1660 now, that it is possible to have under an hour with a GPU from Azure. I am assuming here you have a (very) large dataset. 

I think you should start with the Standard_NC6s_v3 with Tesla V100 GPU and see how it goes. You can probably crank up the batch size quite a bit with the 16GB of VRAM but if you increase it too much it will take longer for your model to converge. Then there is the new ND A100 v4 with A100 GPUs which are now in preview. You can easily sign up for that. I use those, in my case the model is finished in 8-12 hours . The  Standard_NC6s_v3 with V100 is very servicable but has some issues like an outdated CPU. 

I would try with the Standard_NC6s_v3 V100 GPU first, then see if you actually hit a wall with the batch size and request access to the new A100 VMs.

**Comment by glenn-jocher** [comment]
@Pedro-Leitek 👋 Hello! Thanks for asking about **training speed issues**. YOLOv5 🚀 can be trained on CPU (slowest), [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) (fastest). If you would like to increase your training speed some options are:

- Increase `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s
- Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) DDP at larger `--batch-size`
- Train on cached data: `python train.py --cache` (RAM caching) or `--cache disk` (disk caching)
- Train on faster GPUs, i.e.: P100 -> V100 -> A100
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

Good luck 🍀 and let us know if you have any other questions!

**Comment by guillermo-gabrielli-fer** [comment]
1660 shouldn't be so slow, I can certainly do a good amount of training in a 3060 (which is faster but not by orders of magnitude), overnight at high resolution. I would suggest you make sure your CUDA drivers are up to date and reinstall your environment with the latest Pytorch version following the instructions on their website. You can get a cheap GPU at vast.ai or another similar service if you are not dealing with sensitive data or code, or you can do for free in Colab/Kaggle if you keep the tab active.

**Comment by barney2074** [comment]
I find I get similar training times with a local 3060 to the GPU you get with the Pro (not Pro+) version of COLAB
It suits me to let it run overnight or while I am doing something else

Good news is that with the crypto meltdown, the price of GPUs seems to be dropping

**Comment by Denizzje** [comment]
Sorry I made a very nasty mistake in my previous post... I meant to say:  if you have 2,5 days on a GTX 1660 now **it is likely not possible** to have training time under an hour. Hope you didnt run out to buy Azure VMs already... my bad.

Also I am writing that in the assumption that you have a very large dataset and because of that long training times. But if you just have a small dataset, check your enviornment  first as above.

**Comment by glenn-jocher** [comment]
@barney2074 absolutely, GPUs like the 3060 definitely offer a significant performance boost, and leveraging platforms such as Colab or Kaggle can also aid in accelerating the training process. Keeping an eye on GPU prices during market fluctuations is a practical approach. 

Thank you for sharing your insights, and if you have any more questions or need further assistance, feel free to ask!
