### ISSUE TITLE
Meaning of args in P* (P3, P4, P5, etc.)

### ISSUE THREAD

**Issue by bryanbocao** [ultralytics/yolov5#8367]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Dear author,

I am trying to understand P* layers and the corresponding args.

In the following example:
https://github.com/ultralytics/yolov5/blob/master/models/hub/yolov5-p2.yaml

```
backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [64, 6, 2, 2]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C3, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 6, C3, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, C3, [512]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 3, C3, [1024]],
   [-1, 1, SPPF, [1024, 5]],  # 9
  ]
```
**Q1:** what does each number mean in ```[128, 3, 2]``` for ```P2/4```? I notice that ```128 = 32 * 4```. From a high level perspective, each ```P``` layer represents one scale of Feature Pyramid Network (FPN) (correct me if I am wrong).
**Q2:** I am trying to map these numbers in a more concrete way -- ```P2``` represents small scale objects but how small in terms of size of bounding box sizes and # pixels.

In the following figure from [YOLOv4](https://arxiv.org/pdf/2004.10934.pdf), we see three scales of P layer.
**Q3:** If I only need one scale, say only P4, how should I modify the ```<model>.yaml``` file?
![Capture36](https://user-images.githubusercontent.com/14010288/176023573-45d10759-ee6f-4e89-bc54-a51032410090.PNG)

Thanks!

**Comment by glenn-jocher** [comment]
@bryanbo-cao I adopted the P notation from EfficientDet:
![image](https://user-images.githubusercontent.com/26833433/176050841-8671c691-5012-402e-847a-af1d1dcefb3d.png)

**Comment by chelsea456** [comment]
[[-1, 1, Conv, [64, 6, 2, 2]],  # 0-P1/2 
you can explain  [64, 6, 2, 2] . tks u very much @glenn-jocher

**Comment by glenn-jocher** [comment]
@chelsea456 arguments into Conv() module

**Comment by chelsea456** [comment]
[64, 6, 2, 2]: ch_in, ch_out, kernel, stride is this correct sir ? @glenn-jocher

**Comment by glenn-jocher** [comment]
@chelsea456 no.

ch_in is inherited from the previous layer's ch_out, so these argument start at ch_out=64, etc.

**Comment by chelsea456** [comment]
ok tks sir !!!! @glenn-jocher

**Comment by bryanbocao** [comment]
To further clarify, do ```6, 2, 2]``` stand for ```kernel, stride, padding```? @glenn-jocher 
https://github.com/ultralytics/yolov5/blob/master/models/common.py#L40

**Comment by glenn-jocher** [comment]
@bryanbo-cao yes

**Comment by chelsea456** [comment]
anchors:

[10,13, 16,30, 33,23] # P3/8
You can explain me @glenn-jocher

**Comment by glenn-jocher** [comment]
@chelsea456 These are anchor box sizes in pixels for the P3/8 FPN level.
