### ISSUE TITLE
How to print/put text FPS on video using detect.py

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#8370]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello everyone, I hope you are doing well. I want to to print/put text of FPS on Video while detecting .
How can i  do that?

**Comment by QZ-cmd** [comment]
excuse me？have you found a solution

**Comment by glenn-jocher** [comment]
@QZ-cmd hello! Yes, you can display the FPS on the saved video using the `--project` flag in `detect.py`. Just run `python detect.py --source source_video.mp4 --project` and the FPS will be displayed on the video output. Let me know if you have any other questions! 😊
