### ISSUE TITLE
Deploying 2 YOLOv5 models successively

### ISSUE THREAD

**Issue by Nimisha-Pabbichetty** [ultralytics/yolov5#8371]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have trained 2 models for a certain application. This is what I want to do:
1) Get the bounding box predictions from model A
2) Have model B search for objects only in the areas of the image we receive as an output from model A

Is it possible to do this? I have been going through the code in detect.py and yolo.py but I'm not sure how to restrict the search area.

**Comment by glenn-jocher** [comment]
@Nimisha-Pabbichetty 👋 Hello! Thanks for asking about **cropping results** with YOLOv5 🚀.  Cropping bounding box detections can be useful for training classification models on box contents for example. This feature was added in PR https://github.com/ultralytics/yolov5/pull/2827. You can crop detections using either detect.py or YOLOv5 PyTorch Hub:

## detect.py
Crops will be saved under `runs/detect/exp/crops`, with a directory for each class detected.
```bash
python detect.py --save-crop
```
<img width="450" alt="Original" src="https://user-images.githubusercontent.com/26833433/139577918-65cc8f5d-741d-4a88-8753-0154013c624d.jpg">

<img width="1067" alt="Crop" src="https://user-images.githubusercontent.com/26833433/139577896-aa26b07c-466d-4057-9bfe-b01b56007587.png">

## YOLOv5 PyTorch Hub
Crops will be saved under `runs/detect/exp/crops` if `save=True`, and also returned as a dictionary with crops as numpy arrays.
```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, custom

# Images
img = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, PIL, OpenCV, numpy, list

# Inference
results = model(img)

# Results
crops = results.crop(save=True)  # or .show(), .save(), .print(), .pandas(), etc.
```

Good luck 🍀 and let us know if you have any other questions!

**Comment by Nimisha-Pabbichetty** [comment]
> @Nimisha-Pabbichetty 👋 Hello! Thanks for asking about **cropping results** with YOLOv5 🚀. Cropping bounding box detections can be useful for training classification models on box contents for example. This feature was added in PR #2827. You can crop detections using either detect.py or YOLOv5 PyTorch Hub:
> 
> ## detect.py
> Crops will be saved under `runs/detect/exp/crops`, with a directory for each class detected.
> 
> ```shell
> python detect.py --save-crop
> ```
> 
> <img alt="Original" width="450" src="https://user-images.githubusercontent.com/26833433/139577918-65cc8f5d-741d-4a88-8753-0154013c624d.jpg">
> 
> <img alt="Crop" width="1067" src="https://user-images.githubusercontent.com/26833433/139577896-aa26b07c-466d-4057-9bfe-b01b56007587.png">
> 
> ## YOLOv5 PyTorch Hub
> Crops will be saved under `runs/detect/exp/crops` if `save=True`, and also returned as a dictionary with crops as numpy arrays.
> 
> ```python
> import torch
> 
> # Model
> model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, custom
> 
> # Images
> img = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, PIL, OpenCV, numpy, list
> 
> # Inference
> results = model(img)
> 
> # Results
> crops = results.crop(save=True)  # or .show(), .save(), .print(), .pandas(), etc.
> ```
> 
> Good luck 🍀 and let us know if you have any other questions!

@glenn-jocher I need this to happen real-time in a video feed so cropping is unfortunately not an option. Do let me know if it is possible for me to limit the search area for the 2nd model?

**Comment by Etern213** [comment]
> @glenn-jocher I need this to happen real-time in a video feed so cropping is unfortunately not an option. Do let me know if it is possible for me to limit the search area for the 2nd model?

Yes, it is possible. But it's not that simple. What you need to do is to understand each line of code in `detect.py`, and change it. 

Fortunately,  ["YOLOv5 PyTorch Hub"](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) is an easy way to do this. But you still need to have some knowledge of python.

**Comment by Nimisha-Pabbichetty** [comment]
> > @glenn-jocher I need this to happen real-time in a video feed so cropping is unfortunately not an option. Do let me know if it is possible for me to limit the search area for the 2nd model?
> 
> Yes, it is possible. But it's not that simple. What you need to do is to understand each line of code in `detect.py`, and change it.
> 
> Fortunately, ["YOLOv5 PyTorch Hub"](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) is an easy way to do this. But you still need to have some knowledge of python.

@Etern213 Thanks for responding, could you clarify how I can use the link you've given to do this?

**Comment by glenn-jocher** [comment]
@Nimisha-Pabbichetty 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # yolov5n - yolov5x6 official model
#                                            'custom', 'path/to/best.pt')  # custom model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
results.xyxy[0]  # im predictions (tensor)

results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie

results.pandas().xyxy[0].value_counts('name')  # class counts (pandas)
# person    2
# tie       1
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!
