### ISSUE TITLE
mean:  anchors:   - [10,13, 16,30, 33,23]  # P3/8

### ISSUE THREAD

**Issue by chelsea456** [ultralytics/yolov5#8373]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32
in yolov5s.yaml . I can't understand number in  [10,13, 16,30, 33,23]. you can explain for me @glenn-jocher

**Comment by lzh1998-jansen** [comment]
this is prior-box 's size,obtained by using k-menas .

**Comment by agjignesh** [comment]
> this is prior-box 's size,obtained by using k-menas .

Can you please tell me how to reproduce these results and exactly how these anchor boxes are found?
I am new to Yolo so a detailed description might help. 

Thanks

**Comment by glenn-jocher** [comment]
@agjignesh hello! The anchor boxes represent prior knowledge about objects' shapes and sizes in an image, and those in the YOLOv5 configuration files at the GitHub repo have been obtained with k-means clustering on the dataset. 

To reproduce the results, you should provide your own custom dataset or use an existing dataset, such as COCO, and update the configuration file anchors according to the selected dataset. You can use the script provided by Ultralytics repository `kmeans.py` to obtain your own anchors. The `kmeans.py` script is located in the root folder of the YOLOv5 repository. 

Once you have gathered the annotations for your data, you can include them in the YOLOv5 configuration files and then run the script `kmeans.py` with your own configuration. The output will be the anchor boxes, which you can replace in the configuration file to customize the model training. 

If you need additional assistance, please refer to the documentation at https://docs.ultralytics.com/yolov5/training-with-custom-data. I hope this helps!
