### ISSUE TITLE
val.py seems to not evaluate correctly

### ISSUE THREAD

**Issue by kpagels** [ultralytics/yolov5#8374]
Hi,

I have now spend some days to understand the [val.py](https://github.com/ultralytics/yolov5/blob/master/val.py) and I am pretty sure I am using it correctly. However, the evaluation metrics does not show the correct performance.

I am using it in the following way:

`python yolov5/val.py --data data.yaml --weights yolov5/runs/train/{RES_DIR}/weights/best.pt --imgsz 736 
--conf-thres 0.60 --save-conf --batch-size 32 --iou-thres 0.00001 --save-txt`

Which gives an result like the following:

Class     Images     Labels          P          R     mAP@.5 mAP@
  all      12625      10581     0.0562     0.0201     0.0187    0.00549
Dog     12625       9475      0.112     0.0401     0.0359     0.0106
Cat      12625       1106          0          0    0.00142   0.000344

When I look at the result which is stored inside yolov5/runs/val/ the result I get is more accurate then what is shown above. The model almost predicts all the dogs and cats in the validation dataset. 

It seems like the evaluation shown is taking before the confidence threshold is applied? Is that true? How come the labels saved inside yolov5/runs/val not corresponding to the evaluation metric above?

I know there is a bug when conf-thres is above 0.001. But as I understand it, this is not the problem.

Thanks in advance.

**Comment by glenn-jocher** [comment]
@kpagels val.py can not be run at --conf > 0.001

**Comment by kpagels** [comment]
> @kpagels val.py can not be run at --conf > 0.001

Thanks for your quick reply.
