### ISSUE TITLE
about batch size issues

### ISSUE THREAD

**Issue by konioy** [ultralytics/yolov5#8375]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When increasing BatchSize, does the initial LR increase proportionally?

**Comment by glenn-jocher** [comment]
No

**Comment by konioy** [comment]
Is it not recommended for the first training? Or, the effect is worse due to the proportional amplification of lr？

**Comment by glenn-jocher** [comment]
@konioy loss already scales with batch size, lr should not be modified.

**Comment by konioy** [comment]
thank you，very much！

**Comment by glenn-jocher** [comment]
@konioy you're welcome! 😊 Our YOLOv5 community and Ultralytics team are always here to help.
