### ISSUE TITLE
About export

### ISSUE THREAD

**Issue by sdreamforchen** [ultralytics/yolov5#8376]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How can I export tflite with int8、 No preprocessing and No NMS?
Thanks very much!

**Comment by glenn-jocher** [comment]
@sdreamforchen 
```
python export.py --weights yolov5s.pt --include tflite --int8
```

**Comment by sdreamforchen** [comment]
> @sdreamforchen
> 
> ```
> python export.py --weights yolov5s.pt --include tflite --int8
> ```

TensorFlow Lite: export failure: EndVector() takes 1 positional argument but 2 were given

**Comment by sdreamforchen** [comment]
> @sdreamforchen
> 
> ```
> python export.py --weights yolov5s.pt --include tflite --int8
> ```

TensorFlow Lite: export failure: EndVector() takes 1 positional argument but 2 were given
And I use    python export.py --weights yolov5s.pt --include tflite --int8 True
get the same “export failure”

**Comment by Z-Jian** [comment]
@sdreamforchen The issue you face is similar to this closed issue #5707. Please check it out

**Comment by CharlesMod** [comment]
Greetings from the future! I believe there may be another issue with this behavior, forcing v1.12 of EndVector (flatbuffers) now causes a new error with pytorch v1.13:

![image](https://user-images.githubusercontent.com/11051814/218901601-83c906fb-b07c-43d3-9592-808e88dc70a8.png)

Reinstalling the latest flatbuffers (v21) seems to fix the issue.

**Comment by glenn-jocher** [comment]
@CharlesMod thanks for flagging this, and great detective work on identifying the cause and resolution! The YOLOv5 team will take a closer look at this new issue and seek a solution. Your insights are invaluable to the community, so thank you for sharing them.
