### ISSUE TITLE
Unrecognized argument in detect.py (Source Folder in google drive)

### ISSUE THREAD

**Issue by Raymon360** [ultralytics/yolov5#8381]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

When I run detect.py, I get an error like the following:

![image](https://user-images.githubusercontent.com/77184835/176245044-142ebc19-2973-44e5-82ec-f9bd1412ac20.png)

how do i solve this problem?

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Raymon360 user error. Supply correct arguments.
