### ISSUE TITLE
你好，请问detect.py如何同时推理多张呢？

### ISSUE THREAD

**Issue by ylc2580** [ultralytics/yolov5#8390]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

你好，请问detect.py如何同时推理多张呢？

**Comment by mm0806son** [comment]
See the usage of `detect.py`, you can use the method of "directory" or "glob"
```
Usage - sources:
    $ python path/to/detect.py --weights yolov5s.pt --source 0              # webcam
                                                             img.jpg        # image
                                                             vid.mp4        # video
                                                             path/          # directory
                                                             path/*.jpg     # glob
                                                             'https://youtu.be/LNwODJXcvt4'  # YouTube
                                                             'rtsp://example.com/media.mp4'  # RTSP, RTMP, HTTP stream
```

**Comment by ylc2580** [comment]
> See the usage of `detect.py`, you can use the method of "directory" or "glob"
> 
> ```
> Usage - sources:
>     $ python path/to/detect.py --weights yolov5s.pt --source 0              # webcam
>                                                              img.jpg        # image
>                                                              vid.mp4        # video
>                                                              path/          # directory
>                                                              path/*.jpg     # glob
>                                                              'https://youtu.be/LNwODJXcvt4'  # YouTube
>                                                              'rtsp://example.com/media.mp4'  # RTSP, RTMP, HTTP stream
> ```

你好，咱们这个一般

**Comment by ylc2580** [comment]
你好，咱们这个一般只能一次推理一张吧？

**Comment by ylc2580** [comment]
你好，咱们的detect.py中，有个bc=1，将其设置为其他数值后并没有一次性处理多张。是不是咱们这个对不同分辨率的图片不能多张同时处理呢？


--原始邮件---
发件人: "Zijie ***@***.***&gt;
发送时间: 2022年6月29日(周三) 下午5:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ultralytics/yolov5] 你好，请问detect.py如何同时推理多张呢？ (Issue #8390)




 
See the usage of detect.py, you can use the method of "directory" or "glob"
 Usage - sources:     $ python path/to/detect.py --weights yolov5s.pt --source 0              # webcam                                                              img.jpg        # image                                                              vid.mp4        # video                                                              path/          # directory                                                              path/*.jpg     # glob                                                              'https://youtu.be/LNwODJXcvt4'  # YouTube                                                              'rtsp://example.com/media.mp4'  # RTSP, RTMP, HTTP stream

**Comment by pderrenger** [comment]
@ylc2580 你好，`detect.py` 可以通过目录或通配符批量处理多张图片，但不同分辨率的图片可能需要单独处理。建议确保所有图片的分辨率一致以提高批处理效率。
