### ISSUE TITLE
How do i get the mAP.5 after the validation step ?

### ISSUE THREAD

**Issue by cyndyNKCM** [ultralytics/yolov5#8393]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello @glenn-jocher 

After the validation step it is mentioned : Results saved to runs/val/exp2 but when i follow this path i don't see a file results.csv like the one obtained after the training step.
How can i get the mAP after the validation step?

**Comment by glenn-jocher** [comment]
@cyndyNKCM results.csv is produced by train.py

**Comment by cyndyNKCM** [comment]
how can i retrieve the mAP.5 after the validation step please?

**Comment by glenn-jocher** [comment]
@cyndyNKCM printed to console

**Comment by cyndyNKCM** [comment]
![Capture d’écran (76)](https://user-images.githubusercontent.com/65983769/176456325-cbd941cd-24b7-4933-a6f5-9d2a388d0419.png)
 
is there a way to get these P, R, mAP values after the validation not in the console like this?

**Comment by glenn-jocher** [comment]
@cyndyNKCM they're returned at the end of the function:
https://github.com/ultralytics/yolov5/blob/6935a54e603d634f6b0a9026604dc5875d1ca990/val.py#L319-L328

**Comment by cyndyNKCM** [comment]
In fact i want to compare these values with those obtained after a sequence of actions but i don't know how to get them. In my knowledge they are only printed in the console.

**Comment by cyndyNKCM** [comment]
> @cyndyNKCM they're at the end of the function:
> 
> https://github.com/ultralytics/yolov5/blob/6935a54e603d634f6b0a9026604dc5875d1ca990/val.py#L319-L328

Thank you i will check it.
