### ISSUE TITLE
 During the execution of model training train Py encountered the following problems(在执行模型训练train.py时，遇到如下问题 )

### ISSUE THREAD

**Issue by ZiDuNet** [ultralytics/yolov5#8394]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

AutoAnchor: 5.00 anchors/target, 1.000 Best Possible Recall (BPR). Current anchors are a good fit to dataset 
Image sizes 640 train, 640 val
Using 0 dataloader workers
Logging results to runs\train\exp14
Starting training for 300 epochs...

     Epoch   gpu_mem       box       obj       cls    labels  img_size
  0%|          | 0/8 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 634, in <module>
    main(opt)
  File "train.py", line 525, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 320, in train
    loss, loss_items = compute_loss(pred, targets.to(device))  # loss scaled by batch_size
  File "G:\CF-self-aiming-master\yolo-v5-self-aiming-plug-in-master\utils\loss.py", line 120, in __call__
    tcls, tbox, indices, anchors = self.build_targets(p, targets)  # targets
  File "G:\CF-self-aiming-master\yolo-v5-self-aiming-plug-in-master\utils\loss.py", line 217, in build_targets
    indices.append((b, a, gj.clamp_(0, gain[3] - 1), gi.clamp_(0, gain[2] - 1)))  # image, anchor, grid indices
**RuntimeError: result type Float can't be cast to the desired output type __int64**

**Comment by glenn-jocher** [comment]
@ZiDuNet your code is out of date. To update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

**Comment by zhyyeah** [comment]
我也遇到一样的问题，请问解决了嘛？

**Comment by hcl013** [comment]
> 我也遇到一样的问题，请问解决了嘛？

我之前也遇到一样的问题，我把pytorch降级到1.11解决了

**Comment by glenn-jocher** [comment]
@hcl013 感谢您的说明。降级PyTorch可能会解决这个问题，但我建议您将Yolov5更新到最新版本，以确保获得最佳的性能和修复的bug。如果问题仍然存在，请尝试搜索一下Yolov5的GitHub issue看看有没有相关的解决方案。如果您需要进一步的帮助，请告诉我。
