### ISSUE TITLE
GPU Usage

### ISSUE THREAD

**Issue by paulaceccon** [ultralytics/yolov5#8397]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

Running yolov5 with a sample of my dataset I get a pretty good usage of GPU (above 90%, with 50% of the time the GPU is accessing memory -- these metrics are displayed in wandb). This sample has 21497 images, and I get a batch-size "107 for CUDA:0 6.69G/7.80G (86%)". Training happens pretty smoothly.

```python3 train.py --img 256 --batch -1 --data eyecue.yaml --weights weights/yolov5m.pt --workers 32```

```
          Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 12/12 [00:09<00:00,  1.30it/s]
                 all       2528       6293      0.708      0.189      0.211      0.134
     Epoch   gpu_mem       box       obj       cls    labels  img_size
     6/299     6.18G   0.03416   0.00845  0.002274       477       256:   3%|▎         | 7/201 [00:02<01:09,  2.78it/s]
     6/299     6.18G   0.03447  0.008491  0.002231       387       256:   6%|▋         | 13/201 [00:04<01:09,  2.70it/s]
     6/299     6.18G   0.03473  0.008626  0.002301       507       256:   9%|▉         | 18/201 [00:06<01:08,  2.67it/s]
     6/299     6.18G   0.03473  0.008695  0.002419       504       256:  11%|█▏        | 23/201 [00:08<01:07,  2.65it/s]
     6/299     6.18G   0.03474  0.008655  0.002346       456       256:  14%|█▍        | 29/201 [00:10<01:05,  2.63it/s]
     6/299     6.18G   0.03472  0.008764  0.002301       501       256:  17%|█▋        | 34/201 [00:12<01:03,  2.64it/s]
     6/299     6.18G   0.03465  0.008752  0.002294       412       256:  19%|█▉        | 39/201 [00:14<01:03,  2.53it/s]
     6/299     6.18G   0.03457   0.00877  0.002272       521       256:  22%|██▏       | 44/201 [00:16<01:00,  2.58it/s]
     6/299     6.18G   0.03463  0.008794  0.002282       513       256:  24%|██▍       | 49/201 [00:18<01:00,  2.53it/s]
     6/299     6.18G   0.03465  0.008791  0.002345       472       256:  27%|██▋       | 54/201 [00:20<00:59,  2.49it/s]
     6/299     6.18G   0.03557  0.009086  0.003958       452       256:  29%|██▉       | 59/201 [00:22<00:55,  2.54it/s]
     6/299     6.18G   0.04017  0.009997  0.004716       428       256:  32%|███▏      | 64/201 [00:24<00:53,  2.55it/s]
     6/299     6.18G    0.0436   0.01058  0.004708       535       256:  34%|███▍      | 69/201 [00:26<00:53,  2.48it/s]
     6/299     6.18G   0.04665   0.01109  0.004591       407       256:  37%|███▋      | 75/201 [00:28<00:49,  2.55it/s]
     6/299     6.18G    0.0483   0.01139  0.004725       646       256:  39%|███▉      | 79/201 [00:30<00:48,  2.49it/s]
     6/299     6.18G   0.05048   0.01174  0.004586       517       256:  42%|████▏     | 85/201 [00:32<00:45,  2.56it/s]
     6/299     6.18G   0.05193   0.01196  0.004483       461       256:  45%|████▍     | 90/201 [00:34<00:43,  2.55it/s]
     6/299     6.18G   0.05301   0.01218   0.00439       442       256:  47%|████▋     | 95/201 [00:36<00:41,  2.53it/s]
     6/299     6.18G   0.05398    0.0124  0.004288       424       256:  50%|████▉     | 100/201 [00:38<00:39,  2.55it/s]
     6/299     6.18G   0.05473   0.01257  0.004229       602       256:  52%|█████▏    | 105/201 [00:40<00:37,  2.55it/s]
```
When I try to train in the same way with the whole (1773799 images) dataset, it becomes impracticable. The batch has the same size, as expected, but I barely get 30% of GPU utilization, this "GPU Time Spent Accessing Memory" is below 20%, CPU utilization is also below 20%, so I'm not sure why it's not using more GPU or accessing data. Training then becomes impossible:

```
Using 16 dataloader workers

     Epoch   gpu_mem       box       obj       cls    labels  img_size
     0/299     6.36G    0.0933   0.02242   0.03065       488       256:   1%|          | 144/16437 [16:01<4:01:55,  1.12it/s]                                  
     0/299     6.36G    0.0732   0.02007   0.01737       394       256:   2%|▏         | 344/16437 [47:17<16:58:02,  3.80s/it] 
```

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.73.05    Driver Version: 510.73.05    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro RTX 4000     Off  | 00000000:01:00.0 Off |                  N/A |
| 30%   49C    P8     5W / 125W |   7184MiB /  8192MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

I can't cache to disk as my data doesn't fit:

```
Filesystem                       Size  Used Avail Use% Mounted on
udev                              16G     0   16G   0% /dev
tmpfs                            3.2G  1.5M  3.2G   1% /run
/dev/mapper/fm--server--vg-root  233G   62G  160G  28% /
tmpfs                             16G  476K   16G   1% /dev/shm
tmpfs                            5.0M     0  5.0M   0% /run/lock
tmpfs                             16G     0   16G   0% /sys/fs/cgroup
/dev/loop0                       220M  220M     0 100% /snap/microk8s/3272
/dev/loop1                        47M   47M     0 100% /snap/snapd/16010
/dev/loop2                        45M   45M     0 100% /snap/snapd/15904
/dev/loop3                        56M   56M     0 100% /snap/core18/2409
/dev/sda                         458G  3.2G  431G   1% /media/fm/storage-ssd
**/dev/sdb                         916G  622G  248G  72% /media/fm/storage** <<<<< data
/dev/nvme0n1p1                   511M  7.3M  504M   2% /boot/efi
tmpfs                            3.2G     0  3.2G   0% /run/user/1000
``` 

Furthermore, in the middle of it (not really in the middle, as it barely goes), it suddenly crashes:

```    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/fm/yolov5/utils/dataloaders.py", line 591, in __getitem__
    img, labels = self.load_mosaic(index)
  File "/home/fm/yolov5/utils/dataloaders.py", line 691, in load_mosaic
    img, _, (h, w) = self.load_image(index)
  File "/home/fm/yolov5/utils/dataloaders.py", line 663, in load_image
    im = np.load(fn)
  File "/home/fm/yolov5/yolov5/lib/python3.6/site-packages/numpy/lib/npyio.py", line 440, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/fm/yolov5/yolov5/lib/python3.6/site-packages/numpy/lib/format.py", line 771, in read_array
    array.shape = shape
ValueError: cannot reshape array of size 1966080 into shape (608,1080,3)```


### Environment

- Python 3.9
- NVIDIA-SMI 510.73.05    Driver Version: 510.73.05    CUDA Version: 11.6
- Ubuntu 18.06
- venv created using `pip install -r requirements.txt`

### Additional

![Captura de tela de 2022-06-29 17-47-39](https://user-images.githubusercontent.com/4854694/176541791-16997fa5-6702-4f19-94fa-8e55c9a63591.png)
![Captura de tela de 2022-06-29 17-48-40](https://user-images.githubusercontent.com/4854694/176541951-1d053831-285a-4cfa-8a93-addea7bb6516.png)

Any help would be appreciated.

**Comment by glenn-jocher** [comment]
@paulaceccon 👋 Hello! Thanks for asking about **training speed issues**. YOLOv5 🚀 can be trained on CPU (slowest), [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) (fastest). If you would like to increase your training speed some options are:

- Increase `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s
- Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) DDP at larger `--batch-size`
- Train on cached data: `python train.py --cache` (RAM caching) or `--cache disk` (disk caching)
- Train on faster GPUs, i.e.: P100 -> V100 -> A100
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

Good luck 🍀 and let us know if you have any other questions!

**Comment by uefall** [comment]
same issue, quite slow trainning speed with low gpu util

**Comment by glenn-jocher** [comment]
@uefall 👋 Hello! Thanks for asking about **training speed issues**. YOLOv5 🚀 can be trained on CPU (slowest), [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) (fastest). If you would like to increase your training speed some options are:

- Increase `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s
- Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) DDP at larger `--batch-size`
- Train on cached data: `python train.py --cache` (RAM caching) or `--cache disk` (disk caching)
- Train on faster GPUs, i.e.: P100 -> V100 -> A100
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

Good luck 🍀 and let us know if you have any other questions!

**Comment by ujsyehao** [comment]
> 

hello, 你解决了这个问题了吗？我遇到了这个问题，gpu usage < 10% , 我使用8 x a100训练

**Comment by leandervaneekelen** [comment]
@paulaceccon Hi Paula, sorry for the necropost, but could you maybe share the CPU/GPU specs that you were doing these runs with? I'm impressed by a 40 second training epoch with 21497 patches, since I have ~5 minute training epochs for only 10.000 patches and a batch size of 32 (more or less the largest I can manage using `yolov5m.pt` pre-trained weights without going OOM). 

I myself am using a 2080TI and seeing the same gpu utilization issues. (which I presume is causing my slow epochs).

**Comment by nadinator** [comment]
Hi there, I'm running into a similar issue. I have an NVIDIA A100 with 40gb of ram, but when I train my model it only uses 10gb. Is there any way to increase the utilization without changing the batch/image sizes?

**Comment by glenn-jocher** [comment]
@nadinator you can try a few things to increase GPU utilization without changing the batch or image sizes:

1. Reduce the number of worker processes: By default, YOLOv5 uses multiple worker processes for data loading. However, this can sometimes result in lower GPU utilization. You can try reducing the number of worker processes by setting the `--workers` argument to a lower value, such as `--workers 0`.

2. Use `amp_opt_level='O1'`: YOLOv5 supports mixed precision training, which can improve GPU utilization. You can enable mixed precision training by adding the `--fp16` flag to the command line. Additionally, you can specify the optimization level by setting `--amp_opt_level` to `'O1'`.

3. Check for I/O bottlenecks: If the GPU utilization is low, it could be due to I/O bottlenecks. Make sure that your training data is stored on a fast storage device, such as an SSD. You can also try using the `--cache` flag to enable data caching, which can improve training speed.

4. Monitor CPU utilization: In some cases, low GPU utilization can be caused by CPU limitations. Monitor the CPU utilization during training to see if it is reaching its maximum capacity. If the CPU utilization is high, consider upgrading your CPU or using a machine with more CPU cores.

Please note that these suggestions may or may not improve the GPU utilization, as it can be influenced by various factors. It is also important to experiment and find the best configuration that suits your specific training setup.

**Comment by nadinator** [comment]
Thanks, GPT3 :)

**Comment by glenn-jocher** [comment]
@nadinator hi there,

Thank you for bringing up this issue. GPU utilization can sometimes be lower than expected during YOLOv5 training. There are a few potential solutions you can try:

1. Verify that your GPU is being recognized properly by the system and there are no conflicting processes or configurations affecting its utilization.
2. Ensure that your GPU drivers are up to date. Outdated drivers can sometimes cause performance issues.
3. Check if there are any CPU bottlenecks that might be limiting the GPU utilization. If the CPU is not able to feed data to the GPU quickly enough, it can result in lower GPU usage.
4. Consider optimizing your code and data-loading pipeline to maximize GPU utilization. This could involve reducing the number of worker processes, enabling mixed precision training, or using data caching.
5. If none of the above steps help, you may need to adjust your batch size or image size to find a balance between GPU utilization and training speed.

I hope these suggestions help. Feel free to reach out if you have any further questions or if there's anything else we can assist you with.

Best, GPT3
