### ISSUE TITLE
Label caching fails after 30 minutes of reading

### ISSUE THREAD

**Issue by RyanHir** [ultralytics/yolov5#8399]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

After thirty minutes of parsing label files for label caching, train.py fails with an error similar to what is attached. 
![image](https://user-images.githubusercontent.com/4690732/176556679-58dc8f51-6342-4222-92f9-a2e2d7f687c1.png)

### Environment

- YOLO: YOLOv5 🚀 v6.1-270-g6935a54 torch-1.11.0+cu102
   - CUDA:0 (NVIDIA GeForce GTX 1080 Ti, 11178MiB)
   - CUDA:1 (NVIDIA GeForce GTX 1080 Ti, 11178MiB)
- Python: 3.8.10
- OS: Ubuntu 20.04

### Minimal Reproducible Example

Due to the size of the dataset and the fact that no other dataset can hold up the disk, I am unable to give instructions to reproduce outside of having more labels.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by RyanHir** [comment]
This appears to be a duplicate of #7481. From what I read, it appears I just need to start off with one GPU to build the cache, unless I am misinterpreting what is being said. I am away from my station currently, so I cannot test using only one GPU.

**Comment by glenn-jocher** [comment]
@RyanHir your system just appears to be out of resources. Also it appears your HDD is extremely slow or you are reading a network drive, both of which are not recommended.

**Comment by RyanHir** [comment]
I was able to get past the 30 minute timeout by running with one GPU.
![image](https://user-images.githubusercontent.com/4690732/176705439-37152dca-ec06-43b0-a689-be42c1861b9b.png)

**Comment by RyanHir** [comment]
@glenn-jocher Thank you, we may move the dataset to an NVMe but size is a factor in why we have it on another drive.

**Comment by glenn-jocher** [comment]
@RyanHir probably just network drive issues then. It's highly recommended to only train on locally stored data.

**Comment by RyanHir** [comment]
@glenn-jocher We are not operating on a network drive, this is an internal spinning disk.

**Comment by glenn-jocher** [comment]
@RyanHir might be cloud resource read/IOPs limitations then, i.e. GCP here but all providers limit ops https://cloud.google.com/compute/docs/disks/performance

**Comment by RyanHir** [comment]
@glenn-jocher this is a local machine

**Comment by glenn-jocher** [comment]
@RyanHir not sure then. Just monitor resource utilization with htop to make sure you're not maxim your system out. Also obviously use the fastest HDD you can, i.e. NVMe drive as 2GB/s are recommended for best result, especially if not caching images with --cache disk or --cache ram

**Comment by RyanHir** [comment]
@glenn-jocher Sounds good! I have found a workaround that is good for me at the moment. I believe this issue can be closed now unless you believe that this issue needs to be watched further.

**Comment by glenn-jocher** [comment]
@RyanHir got it, closing issue. Only 290 left!
