### ISSUE TITLE
有人知道怎么样在多类训练后输出单类的PR和Ap么？After multiclass training how to output Single Class Ap and P、R

### ISSUE THREAD

**Issue by xiaoazhou** [ultralytics/yolov5#84]

**Comment by glenn-jocher** [comment]
@xiaoazhou to display mAP by class:

`python test.py --verbose`

**Comment by xiaoazhou** [comment]
> @xiaoazhou to display mAP by class:
> 
> `python test.py --verbose`

It didn't work，and also display allclass

**Comment by xiaoazhou** [comment]
> @xiaoazhou to display mAP by class:
> 
> `python test.py --verbose`
i resolve it  ----verbose  didn't work  but i Modify the default verbose=True can work      Thanks

**Comment by glenn-jocher** [comment]
@xiaoazhou thanks for the bug report. I can reproduce. I will push a fix shortly so that --verbose works correctly.

**Comment by glenn-jocher** [comment]
Issue should be fixed now. Please git pull and try again.

<img width="1027" alt="Screen Shot 2020-06-16 at 10 23 03 AM" src="https://user-images.githubusercontent.com/26833433/84806970-6109d180-afbb-11ea-929a-06992617b325.png">
