### ISSUE TITLE
what's the model.fuse() definition?

### ISSUE THREAD

**Issue by lucasjinreal** [ultralytics/yolov5#840]
## ❔Question

what's the model.fuse() definition? How's the fuse method compare to pytorch native way?

**Comment by glenn-jocher** [comment]
@jinfagang oh, what's the pytorch native way? 

YOLOv5 fuse() is a model class method:
https://github.com/ultralytics/yolov5/blob/4fb8cb353f7d1945e3e1b270980c883c82297d2f/models/yolo.py#L160-L169

**Comment by Aktcob** [comment]
@jinfagang u can refer to https://bbs.cvmart.net/topics/2032
