### ISSUE TITLE
SPPF and SPP

### ISSUE THREAD

**Issue by sdreamforchen** [ultralytics/yolov5#8400]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, sorry, I can't find the Comparison of test results between SPPF and SPP about latency and accuracy.
Can you introduce again?

**Comment by glenn-jocher** [comment]
@sdreamforchen SPPF PR here provides all the comparison details: https://github.com/ultralytics/yolov5/pull/4420#issuecomment-899042581

**Comment by sdreamforchen** [comment]
> @sdreamforchen SPPF PR here provides all the comparison details: [#4420 (comment)](https://github.com/ultralytics/yolov5/pull/4420#issuecomment-899042581)

Another question, if I don't set the hidden channels, and remove the first conv, do those ops influence the accuracy?
Keep the same input and output channel with the original net
