### ISSUE TITLE
CUDA-torch did not work On Windows 10 CUDA 11.4 / CUDNN 8.2.4

### ISSUE THREAD

**Issue by star4s** [ultralytics/yolov5#8403]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

In fact, I used Nvidia V100-32G.
In the GPU, I can work Yolov5 on cuda 9.0, cudnn 7.1.2, torch 1.10.1, torchvision 0.11.2, tensorboard 2.8.0, well.

However, I have New GPU Nvidia A40-48Q.

CUDA-torch for yolov5 did not work On Windows 10 CUDA 11.4 / CUDNN 8.2.4.
My setting is cudatoolkit 11.3.1, cudnn 0.11.0, torch 1.10.2, torchvision 0.11.3, tensorboard 2.9.1.

How can I work yolov5 on new GPU?

Thank you for your attention.

**Comment by ghost** [comment]
Hi, i also use Windows 10 with CUDA 11/CUDNN 8 installed.

I was able to get my RTX 2060 12 GB graphics card to work only with PyTorch LTS (1.8.2)

pip3 install torch==1.8.2 torchvision==0.9.2 torchaudio===0.8.2 --extra-index-url https://download.pytorch.org/whl/lts/1.8/cu111

**Comment by glenn-jocher** [comment]
@star4s you might also try our Docker image for best compatibility on Windows systems:

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

**Comment by star4s** [comment]
@DonkeySmall
I Solved the problem by your suggestion.
In my case, I used the commend line:
pip3 install torch==1.10.0+cu113 torchvision==0.11.1+cu113 torchaudio===0.10.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html

Thank you for your help.
