### ISSUE TITLE
RuntimeError: result type Float can't be cast to the desired output type long int

### ISSUE THREAD

**Issue by happylulu666** [ultralytics/yolov5#8405]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Today, it threw an error while running train.py as follows. Before this, I successfully completed the training process. I have not made any changes to the document.

Traceback (most recent call last):
  File "train.py", line 650, in <module>
    main(opt)
  File "train.py", line 546, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 337, in train
    loss, loss_items = compute_loss(pred, targets.to(device))  # loss scaled by batch_size
  File "/yolov5/utils/loss.py", line 121, in __call__
    tcls, tbox, indices, anchors = self.build_targets(p, targets)  # targets
  File "yolov5/utils/loss.py", line 220, in build_targets
    indices.append((b, a, gj.clamp_(0, gain[3] - 1), gi.clamp_(0, gain[2] - 1)))  # image, anchor, grid indices
RuntimeError: result type Float can't be cast to the desired output type long int

### Environment

YOLOv5 🚀 v6.1-11-g63ddb6f0 torch 1.12.0+cu102 GPU

colab

Python:3.8

GPU:Tesla P100 16280MiB

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@happylulu666 this is an incompatibility of older versions of YOLOv5 with torch 1.12. Updating YOLOv5 will resolve this.

To update YOLOv5:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

**Comment by YuWhale** [comment]
thank you

**Comment by yuhe0925** [comment]
git pull from within your yolov5/ directory or git clone https://github.com/ultralytics/yolov5

this does not solve the problem, still getting same error

been using the same script in Colab, and this issue only start from yesterday

**Comment by glenn-jocher** [comment]
@yuhe0925 this issue has been resolved in master, please update your code and make sure you are using the latest compatible version of torch==1.11.0. If this doesn't resolve your issue then please submit a minimum reproducible example to help us investigate.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by hoseinhamzei** [comment]
I had the same issue and since I have made a lot of changes to the base code I couldn't pull master branch, thanks to glenn's comment I solved this error by editing the requirements.txt file and setting torch version to == 1.7.0 and it solved the issue

**Comment by oki-aryawan** [comment]
> I had the same issue and since I have made a lot of changes to the base code I couldn't pull master branch, thanks to glenn's comment I solved this error by editing the requirements.txt file and setting torch version to == 1.7.0 and it solved the issue

I got the same issue and setup torch to version 1.7.0 solved it. Thanks dude....

**Comment by mishi-sarfraz** [comment]
> My same issue was resolved by changing requirement.txt file . Torch version >1.7.0 when changed to ==1.7.0 resolved the issue.

**Comment by molua** [comment]
> > My same issue was resolved by changing requirement.txt file . Torch version >1.7.0 when changed to ==1.7.0 resolved the issue.

I tried this method, but it showed that  No matching distribution found for torch==1.7.0

**Comment by mishi-sarfraz** [comment]
Did u check it in Requirement.txt?

**Comment by glenn-jocher** [comment]
@happylulu666 @yuhe0925 @hoseinhamzei @happylulu666 @oki-aryawan @molua @mishi-sarfraz good news 😃! This issue should now be fixed ✅ in PR #8067 from June 1st. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by happylulu666** [comment]
Thanks for Glenn's kind reply and useful advice! I would also like to thank the friends who have the same problems as me for discussing this.

**Comment by bit-scientist** [comment]
I have the same issue on Windows, so I uninstalled torch (1.12) and tried installing 1.7.0, but that doesn't match with my CUDA 11.3. I then safely moved to Linux , where I have torch 1.12 and CUDA 10.2.

**Comment by plastic-waste-database** [comment]
> I have the same issue on Windows, so I uninstalled torch (1.12) and tried installing 1.7.0, but that doesn't match with my CUDA 11.3. I then safely moved to Linux , where I have torch 1.12 and CUDA 10.2.

I'm having the same issue as well. Torch version 1.7.0 is not compatible with CUDA 11.3.

**Comment by plastic-waste-database** [comment]
**Bug**
File "train.py", line 642, in <module>
    main(opt)
  File "train.py", line 538, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 330, in train
    loss, loss_items = compute_loss(pred, targets.to(device))  # loss scaled by batch_size
  File "C:\Users\owent\Desktop\yolov5 (latest)\utils\loss.py", line 120, in __call__
    tcls, tbox, indices, anchors = self.build_targets(p, targets)  # targets
  File "C:\Users\owent\Desktop\yolov5 (latest)\utils\loss.py", line 217, in build_targets
    indices.append((b, a, gj.clamp_(0, gain[3] - 1), gi.clamp_(0, gain[2] - 1)))  # image, anchor, grid indices
RuntimeError: result type Float can't be cast to the desired output type __int64

**Environment**
Python: 3.8
CUDA: 11.3
Torch version: 1.12.1
Windows: 11

**Note**
I'm running the code in Jupyter and also have updated YOLOv5. But still facing the bug errors as shown above. Really need help with these issues :(

**Comment by glenn-jocher** [comment]
@owentamin1996 update your YOLOv5 code, it's out of date. To update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

**Comment by Benjamin2506** [comment]
Simply use,
install torch==1.11,
torchvision==0.12,
torchtext==0.12,
torchaudio==0.11
Compatible versions for torch 1.11
No error will be reflected.

**Comment by plastic-waste-database** [comment]
I have solved the issue by downgrading Torch version to 1.10.1. However, another problem arise in which the value for P,R and other relevant metrics are all zero. I’m using CUDA 11.3 for running the code.

![6A2505B1-8B38-4DA3-851A-F4EE63014831](https://user-images.githubusercontent.com/100338254/184605348-73160606-4c05-49ab-a56d-180eabd0700f.png)

**Comment by lucysumi** [comment]
> @happylulu666 this is an incompatibility of older versions of YOLOv5 with torch 1.12. Updating YOLOv5 will resolve this.
> 
> To update YOLOv5:
> 
> * **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
> * **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
> * **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  [![Open In Colab](https://camo.githubusercontent.com/84f0493939e0c4de4e6dbe113251b4bfb5353e57134ffd9fcab6b8714514d4d1/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb) [![Open In Kaggle](https://camo.githubusercontent.com/a08ca511178e691ace596a95d334f73cf4ce06e83a5c4a5169b8bb68cac27bef/68747470733a2f2f6b6167676c652e636f6d2f7374617469632f696d616765732f6f70656e2d696e2d6b6167676c652e737667)](https://www.kaggle.com/models/ultralytics/yolov5)
> * **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image [![Docker Pulls](https://camo.githubusercontent.com/280faedaf431e4c0c24fdb30ec00a66d627404e5c4c498210d3f014dd58c2c7e/68747470733a2f2f696d672e736869656c64732e696f2f646f636b65722f70756c6c732f756c7472616c79746963732f796f6c6f76353f6c6f676f3d646f636b6572)](https://hub.docker.com/r/ultralytics/yolov5)

I have done this but still getting the same error "[RuntimeError: result type Float can't be cast to the desired output type long int](https://github.com/ultralytics/yolov5/issues/8405#top)"

**Comment by glenn-jocher** [comment]
@lucysumi 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by apiszcz** [comment]
Seeing same error, here are my versions


```
Type "help", "copyright", "credits" or "license" for more information.
>>> import yolov5
>>> yolov5.__version__
'6.1.8'


>>> import torch
>>> torch.__version__
'1.12.1+cu116'

```

**Comment by glenn-jocher** [comment]
@apiszcz yolov5 pip package has nothing to do with Ultralytics. To use correct code install using git clone commands in readme.

**Comment by apiszcz** [comment]
will do/try next, thank you.

**Comment by tinason-yang** [comment]
This may also have something to do with the version of O=onnxruntime, which was resolved when I went back to onnxruntime1.10.0

**Comment by Tefor** [comment]
In loss.py (line 173 ), gain = torch.ones(7, device=targets.device) → gain = **torch.ones(7, device=targets.device).long()**

**Comment by glenn-jocher** [comment]
@Tefor @liyanluo is this a change that we should apply to master, or are you applying this as a patch to older code?

**Comment by Zafar343** [comment]
'gain = torch.ones(7, device=targets.device).long()' worked for me.
Thank you @Tefor

**Comment by Tefor** [comment]
> @Tefor @liyanluo is this a change that we should apply to master, or are you applying this as a patch to older code?
Hi glenn, thanks for asking! I made the changes to the code in yolov5 version 6.1, you can choose where to change it yourself.  ：）

**Comment by robmarkcole** [comment]
Currently having this issue on colab with `torch 1.13`

**Comment by glenn-jocher** [comment]
@robmarkcole can you please provide a reproducible notebook or code block I can run in Colab to view the error? Thanks!

**Comment by robmarkcole** [comment]
@glenn-jocher the issue was the notebook was old and downloading an old version of the yolov5 repository. On pulling latest there is no issue, thanks!

**Comment by Jervx** [comment]
Update on Dec 12, 2022

torch 1.7.0 can't be found anymore. 

I use this instead

torch==1.7.1
torchvision==0.8.2

and it works

**Comment by rokopi-byte** [comment]
> Update on Dec 12, 2022
> 
> torch 1.7.0 can't be found anymore.
> 
> I use this instead
> 
> torch==1.7.1 torchvision==0.8.2
> 
> and it works

It's not necessary, simply use latest release of YOLO

**Comment by glenn-jocher** [comment]
@rokopi-byte thank you for the update! Using the latest release of YOLOv5 should indeed ensure compatibility with the latest versions of Torch and torchvision. Let me know if you need any further assistance.
