### ISSUE TITLE
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__

### ISSUE THREAD

**Issue by wonchul-kim** [ultralytics/yolov5#8406]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi! 

Trying to cusomize yolov5 for efficiency, I rebuild yolov5Detection class and just simply relocate the original code into some functions such as __init__(self), set_args(self), set_model(self), set_datasets(self), start_training(self), .....

Then, when I change `train_loader` or `val_loader` as `self.train_loader` or `self.val_loader` and I got this below error at the end of training:

Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f4972feac10>
Traceback (most recent call last):
  File "/home/wonchul/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
  File "/home/wonchul/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1262, in _shutdown_workers
AttributeError: 'NoneType' object has no attribute 'python_exit_status'

I did some experiments:
* the above error is caused because of using `InfiniteDataLoader`. when I used `torch.utils.data.DataLoader`, it does not appear.

* workers = 0 could solve the above problem.

Is there way to solve this problem when I keep changing 'train_loader` or `val_loader` as `self.train_loader` or `self.val_loader` ?

**Comment by glenn-jocher** [comment]
@wonchul-kim I'm sorry, we don't have resources to assist in debugging custom code, but I would not advise you to use --workers 0 since this will slow down your dataloading and thus your training. Swapping out the InfiniteDataLoader is probably a better idea.
