### ISSUE TITLE
Predict with high process time in low rate

### ISSUE THREAD

**Issue by sergiopinto16** [ultralytics/yolov5#8407]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I try to use detect.py to my application. 

If i disable drawing results and saved images, I get excelent results if I do a cycle through all the images. 

If I run the images at a low rate the time to process the image is high in some interations.

It's a gpu problem? (I'm using an rtx2060)

**Comment by glenn-jocher** [comment]
@sergiopinto16 drawing annotations on images and saving images are both expensive operations so yes detect.py will run faster if it does not do those. This is not a GPU bottleneck but a CPU bottleneck.

**Comment by sergiopinto16** [comment]
No, that is not my question.

If i change the for loop in detect.py to execute the next image when i press the "N" key (low frame rate), the process time is high .

(when i execute predict in for loop, read all saved images and execute, the process time is slow)

![image](https://user-images.githubusercontent.com/29043246/176885744-9fec4304-73af-4d9c-bb73-16b740d4dfad.png)




When i say process time i'm referring to dt[1]   (inference time)

![image](https://user-images.githubusercontent.com/29043246/176886073-9591bf49-ab52-4a75-947e-8a8f725246c0.png)

**Comment by glenn-jocher** [comment]
@sergiopinto16 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # yolov5n - yolov5x6 official model
#                                            'custom', 'path/to/best.pt')  # custom model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
results.xyxy[0]  # im predictions (tensor)

results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie

results.pandas().xyxy[0].value_counts('name')  # class counts (pandas)
# person    2
# tie       1
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by sergiopinto16** [comment]
I applied your recommendation.

If I create a loop for in image I get 2.0 / 3.0 ms:

```
import torch
import datetime


# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)

# Images
imgs = ['https://ultralytics.com/images/zidane.jpg']  # batch of images



for x in range(1, 100):
     # Inference
     results = model(imgs)
     print(datetime.datetime.now())
     results.print()
#     input("Press Enter to continue...")



# Results
results.print()
results.save()  # or .show()

results.xyxy[0]  # img1 predictions (tensor)
results.pandas().xyxy[0]  # img1 predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 1  433.50  433.50   517.5  714.5    0.687988     27     tie
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```


![image](https://user-images.githubusercontent.com/29043246/176908957-d3b21a80-8260-4c38-98c8-cd03018964f1.png)



If I stop the process (waiting for a key), I take high inference time values. 

```
import torch
import datetime


# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)

# Images
imgs = ['https://ultralytics.com/images/zidane.jpg']  # batch of images



for x in range(1, 100):
     # Inference
     results = model(imgs)
     print(datetime.datetime.now())
     results.print()
     input("Press Enter to continue...")



# Results
results.print()
results.save()  # or .show()

results.xyxy[0]  # img1 predictions (tensor)
results.pandas().xyxy[0]  # img1 predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 1  433.50  433.50   517.5  714.5    0.687988     27     tie
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```

![image](https://user-images.githubusercontent.com/29043246/176909160-ea7e83f6-c0a5-491a-abd2-0042e42f1f80.png)

**Comment by glenn-jocher** [comment]
@sergiopinto16 Thanks for sharing your results.

When you pause the process, the model is likely being reloaded with each iteration that could slow down the inference time due to initialization overhead. This might explain the high inference times when waiting for a key press.

One solution could be to load the model outside the loop, and then infer images iteratively inside the loop. This way, the model is only loaded once, helping maintain consistent inference times.

```python
import torch
import datetime

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)

# Images
imgs = ['https://ultralytics.com/images/zidane.jpg']  # batch of images

# Inference
for x in range(1, 100):
     # Inference
     results = model(imgs)
     print(datetime.datetime.now())
     results.print()
     input("Press Enter to continue...")  # Remove this line when not debugging

# Results
results.save()  # or .show()
```

This way, the model is loaded once, and the inference is performed iteratively. Let me know how it works for you!
