### ISSUE TITLE
about build_targets question

### ISSUE THREAD

**Issue by konioy** [ultralytics/yolov5#8408]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

In build_targets, the GT box is extended, plus neighboring 2 pixels, can it be understood as an augmentation of the gtbox, up, or down, or right, or left to translate strid*0.5 pixels？
What was your original intention for this design?

**Comment by glenn-jocher** [comment]
@konioy redundancy in detections for improved recall

**Comment by konioy** [comment]
can it be understood as an augmentation of the GT box, up, or down, or right, or left to translate strid*0.5 pixels？

**Comment by glenn-jocher** [comment]
@konioy no, this is simply multiple cells detecting an object to increase recall, especially at cell boundaries where recall may drop.
