### ISSUE TITLE
About weighted boxes fusion

### ISSUE THREAD

**Issue by SISTMrL** [ultralytics/yolov5#841]
## ❔Question
Hello, Ultra! I find the better method of post process in detection, it's different from nms and soft nms, it's called weighted boxes fusion(WBF) : [https://github.com/ZFTurbo/Weighted-Boxes-Fusion](url). And this repo mention using WBF in yolov5 in benchmark.py line338: [https://github.com/ZFTurbo/Weighted-Boxes-Fusion/blob/master/benchmark/run_benchmark.py](url)

and the input in WBF is csv, so the question I want to consult is how to generate the .csv file of detection result

**Comment by glenn-jocher** [comment]
@SISTMrL oh, really interesting! It seems they show a significant improvement ensembling with their WBF method. I've tried a similar Merge NMS method, but saw better results with YOLOv3 when bounding boxes were not as accurate as we have now. I observed that as box accuracy increases, potential improvments from merging methods decrease.

**Comment by SISTMrL** [comment]
yes, I also think when detection result is better, the improvement of WBF wil decrease. When I applied yolov5 to my ultrasound image, the initial map@0.5 is 0.884, and due to my goal, I need to detect more accuracy. So I use pseudo label, TTA, and model ensemble, finally, I improve the map@0.5 from to 0.884 to 0.917,  but i'm not sure when I apply WBF to my work, whether the map is improved

**Comment by SISTMrL** [comment]
just now I tried merge nms, and I found the map@0.5 fall down

**Comment by glenn-jocher** [comment]
@SISTMrL yes, this is what I see now also, either equal or slightly lower Merge NMS mAP. It's possible merging is better when ensembling is used, as in WBF, not sure. Merge NMS merges boxes using a weighted mean, weighted by their confidences/CIoU predictions.

In any case, these methods are really competition methods, as they all drastically slow down inference results. We are interested in competition results of course, but also need to balance this with real time use cases, exporting to the edge on iOS, etc., which some of these more extreme architectures (detectorrs, wbf, efficientdet) are not concerned with.

**Comment by SISTMrL** [comment]
Yes, WBF will dramatically slow down the inference speed and not compatible with the goal of real time

**Comment by viethoang303** [comment]
Where are wbf code used in yolov5 ?? I want to know it

**Comment by glenn-jocher** [comment]
@viethoang303 WBF is not currently integrated into YOLOv5. While it's an interesting method, it's not widely applicable due to its significant impact on inference speed, making it incompatible with real-time applications. Therefore, we have not prioritized its integration into the YOLOv5 repository. Thank you for your understanding.
