### ISSUE TITLE
confusion matrix does not consider empty ground truth annotations?

### ISSUE THREAD

**Issue by kpagels** [ultralytics/yolov5#8410]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I noticed something I thought was strange and therefore I tried to reproduce it with a simple example. I made a new simple dataset containing only 3 images with their respective txt files. These are the annotated frames with their respective label and bounding box: (label, x1, x2, width, height). As you can see frame_000000.txt does not contain any ground truth annotations.

- frame_000000.txt
- frame_000001.txt
0 0.423444 0.494158 0.029778 0.033906
- frame_000002.txt
0 0.424625 0.494063 0.029778 0.033924

Then I run the following script: 

`python yolov5/val.py --data data.yaml --weights yolov5/runs/train/results_1/weights/best.pt --imgsz 736 \
--conf-thres 0.001 --save-conf --batch-size 1 --iou-thres 0.00001 --save-txt
`

And I updated [L184](https://github.com/ultralytics/yolov5/blob/master/val.py#L184) with:

``` 
confusion_matrix = ConfusionMatrix(nc=nc, conf=0.6, iou_thres=0.001)
```

When I then try to print the `confusion_matrix.matrix` output I get the following output:

```
>> confusion_matrix.matrix
[[          4           0           7]
 [          0           0           4]
 [          0           0           0]]
```

However, when I look inside the runs/val/exp1/labels/frame_000000.txt there are 1 misprediction, but it is not considered in the confusion_matrix calculations. Here are the file content:
```
1 0.920076 0.0882719 0.0242104 0.0181235 0.657665

```

I tried to insert a print statement here [L246](https://github.com/ultralytics/yolov5/blob/master/val.py#L246)  `print(paths)`
```
...
if plots:
    print(paths)
    confusion_matrix.process_batch(predn, labelsn)
...
```

 and since frame_000000.txt is empty it does not even consider this file. Shouldn't all the mispredictions be added to the confusion matrix as background mispredictions? Or is there something I am missing?

**Comment by glenn-jocher** [comment]
@kpagels hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
