### ISSUE TITLE
training_classes arg

### ISSUE THREAD

**Issue by lolpa1n** [ultralytics/yolov5#8412]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

in older versions of yolov5 there was a training_classes argument for training for a specific class, how now to train for a specific class from all available?

**Comment by glenn-jocher** [comment]
@lolpa1n you can filter classes to train here:
https://github.com/ultralytics/yolov5/blob/898332433a71b8846b15daa276a8ac45c9efa98b/utils/dataloaders.py#L480-L481

It's not a heavily used feature so we leave it up to the users to modify the source code there if they need to filter classes. You pass class indices, i.e. include_class = [0, 3, 5]
