### ISSUE TITLE
How to know what epoch relates to best.pt?

### ISSUE THREAD

**Issue by rusvagzur** [ultralytics/yolov5#8413]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

The title pretty much says it all. I have found a similar issue: 

https://github.com/ultralytics/yolov5/issues/582 

There, it is explained how the metrics are computed in the "fitness" function to obtain the best.pt. However, how can we know at what epoch number this happened?

Thanks

**Comment by glenn-jocher** [comment]
@rusvagzur fitness function is here, heavily weighted towards mAP@0.5:95:
https://github.com/ultralytics/yolov5/blob/898332433a71b8846b15daa276a8ac45c9efa98b/utils/metrics.py#L15-L19

best.pt is saved on every maximum fitness epoch. You can view logging results in TensorBoard, W&B, CSV etc to see your metrics and pinpoint the highest mAP@0.5:0.95

![image](https://user-images.githubusercontent.com/26833433/176710333-85b70978-7453-44b9-9e72-4f3b500b23fb.png)
