### ISSUE TITLE
Why do all eval metrics jump in the the final epoch?

### ISSUE THREAD

**Issue by wiseyoungbuck** [ultralytics/yolov5#8419]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When I train yolo, the final epoch of my training process has an outsized impact on my accuracy metrics. 

What explains this behavior?
Here is an example of what I mean?
![image](https://user-images.githubusercontent.com/14169315/176768671-854ccf04-13cb-4669-8881-975d28701f96.png)

Validation loss also drops dramatically.
![image](https://user-images.githubusercontent.com/14169315/176768734-43868993-2ccf-494d-ae2c-26ba0477e72e.png)

**Comment by AyushExel** [comment]
@wiseyoungbuck the final metric logged represent the best metrics throughout the training (best.pt). See this line
https://github.com/ultralytics/yolov5/blob/master/train.py#L448
