### ISSUE TITLE
Torchscript runtime increases linearly with the batchsize

### ISSUE THREAD

**Issue by zhaozhiming37** [ultralytics/yolov5#8422]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When I export the torchscript model, the runtime of the model increases linearly with the batchsize.The command is `python export.py --weights <best.pt> --device 0 --batch-size 8 --img 640 --include torchscript`

**Comment by glenn-jocher** [comment]
@zhaozhiming37 we don't have torchscript batch size benchmarks but we have a YOLOv5 PyTorch batch size study here: https://community.ultralytics.com/t/yolov5-study-batch-size-vs-speed

**Comment by zhaozhiming37** [comment]
> 



> @zhaozhiming37 we don't have torchscript batch size benchmarks but we have a YOLOv5 PyTorch batch size study here: https://community.ultralytics.com/t/yolov5-study-batch-size-vs-speed

thanks for your help
