### ISSUE TITLE
One or two classes for different objects?

### ISSUE THREAD

**Issue by MasIgor** [ultralytics/yolov5#8423]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello all!

out of curiosity: lets say I have 3 objects, all the same color, but with slightly different shapes: 

green apples,
green tomatoes,
green oranges. 

yeah, i know, those all tase crappy.. If i want to separate fruits from vegetables, would it be better to have 3 classes, with two having the same name (so apples = class 1 = fruits, oranges = class 2 = fruits, tomatoes = class 3 = vegetables) or would it be better to have just two classes and label the apples and oranges the same way?

what would bring more stable results?

Thank you!

**Comment by glenn-jocher** [comment]
@tanzerlana the less tasks that are required the better the model will perform, so ideally you should group your classes to the absolute minimum to accomplish your use case, i.e. just 0-fruit and 1-vegetable

**Comment by MasIgor** [comment]
Thank you for your answer @glenn-jocher . 

To extend the qeustion further, lets say I have a network that recognizes all sorts of balls. Soccer, baseball, basket, volley etc... a huge number, lets say 50 different classes for example. But my network also needs to detect those that are not inflated, for example not perfectly round. would I then have 1 class for each type of ball, + one class that contains all type of balls uninflated? or would each class have a inflated and a uninflated version?

**Comment by glenn-jocher** [comment]
@tanzerlana 1-ball, 2-damaged_ball

**Comment by MasIgor** [comment]
yeah in case I want to know if it is a good or a bad ball.. but what if in case of a good ball I need to know the type too?

1 - soccer,
2 - basket
...
51 - damaged

or 

1 - soccer
2 - soccer damaged
3 - basket
4 - basket damaged

**Comment by glenn-jocher** [comment]
@tanzerlana you can experiment with different problem statements to see what works best.
