### ISSUE TITLE
I accidentally deleted it.

### ISSUE THREAD

**Issue by sarpx** [ultralytics/yolov5#8426]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I accidentally deleted these graphics, is there a way to create them again?

### Additional

![results](https://user-images.githubusercontent.com/73984193/176852007-3367731d-e35a-4034-95e7-ce550ae6a1c5.png)
![confusion_matrix](https://user-images.githubusercontent.com/73984193/176852013-41147421-3f0e-4f6f-b117-0eb5c4e00adc.png)
![F1_curve](https://user-images.githubusercontent.com/73984193/176852014-5179c662-d24b-4aed-b380-d726c4462c01.png)
![P_curve](https://user-images.githubusercontent.com/73984193/176852016-e92a617e-40d5-430c-8cfc-45ba10eec9d2.png)
![PR_curve](https://user-images.githubusercontent.com/73984193/176852020-1fb90492-a5ce-49f4-83df-b0c4730c83b0.png)
![R_curve](https://user-images.githubusercontent.com/73984193/176852023-8d964f5f-5502-4a22-aa93-f0ef9c5d0bc1.png)

**Comment by glenn-jocher** [comment]
@sarpx results.png is plotted from results.csv:
https://github.com/ultralytics/yolov5/blob/898332433a71b8846b15daa276a8ac45c9efa98b/utils/plots.py#L417-L441

All the rest are produced by val.py:
```
python val.py --data DATA --weights WEIGHTS
```
