### ISSUE TITLE
how to make preprocess for images in c++

### ISSUE THREAD

**Issue by fatejzz** [ultralytics/yolov5#8427]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

At present, I am trying to deploy my Yolo model in ros. And I use c++ for my Yolo model to make predictions. However, it doesn't work well. Given the same image, when I use detect.py it can make correct predictions. But when I use my code it can't predict well for the existing wrong box.
I think it is because of the image preprocessing process, I imitate the letterbox in detect.py, but it will meet a problem.

   File "code/__torch__/models/yolo.py", line 71, in forward
    _35 = (_20).forward(_34, )
    _36 = (_22).forward((_21).forward(_35, ), _29, )
    _37 = (_24).forward(_33, _35, (_23).forward(_36, ), )
           ~~~~~~~~~~~~ <--- HERE
    return (_37,)
class Detect(Module):
  File "code/__torch__/models/yolo.py", line 101, in forward
    _19 = torch.split_with_sizes(torch.sigmoid(_18), [2, 2, 6], 4)
    xy, wh, conf, = _19
    _20 = torch.add(torch.mul(xy, CONSTANTS.c0), CONSTANTS.c1)
          ~~~~~~~~~ <--- HERE
    xy0 = torch.mul(_20, torch.select(CONSTANTS.c2, 0, 0))
    _21 = torch.pow(torch.mul(wh, CONSTANTS.c0), 2)

Traceback of TorchScript, original code (most recent call last):
/home/jzz/yolov5/models/yolo.py(71): forward
/data/jzz/envs/jzz/lib/python3.7/site-packages/torch/nn/modules/module.py(1098): _slow_forward
/data/jzz/envs/jzz/lib/python3.7/site-packages/torch/nn/modules/module.py(1110): _call_impl
/home/jzz/yolov5/models/yolo.py(158): _forward_once
/home/jzz/yolov5/models/yolo.py(135): forward
/data/jzz/envs/jzz/lib/python3.7/site-packages/torch/nn/modules/module.py(1098): _slow_forward
/data/jzz/envs/jzz/lib/python3.7/site-packages/torch/nn/modules/module.py(1110): _call_impl
/data/jzz/envs/jzz/lib/python3.7/site-packages/torch/jit/_trace.py(965): trace_module
/data/jzz/envs/jzz/lib/python3.7/site-packages/torch/jit/_trace.py(750): trace
export.py(98): export_torchscript
export.py(520): run
/data/jzz/envs/jzz/lib/python3.7/site-packages/torch/autograd/grad_mode.py(27): decorate_context
export.py(602): main
export.py(607): <module>
RuntimeError: The size of tensor a (48) must match the size of tensor b (80) at non-singleton dimension 2

> cv::Mat resized_frame = letterbox(frame);
>   cvtColor(resized_frame,resized_frame,CV_BGR2RGB);
>   torch::Tensor in_tensor = torch::from_blob(resized_frame.data, {resized_frame.rows,resized_frame.cols, 3}, torch::kByte);
but if the code in the third line wrote as        
>  torch::Tensor in_tensor = torch::from_blob(resized_frame.data, {640,640, 3}, torch::kByte);
it could work but there are some problems. On the one hand, it will predict wrong box which doesn't occur in python detect.py.
On the other hand, sometimes it will predict different boxes given the same image.

### Additional

here is my code of letter box
    cv::Mat letterbox(const cv::Mat& src)
    {
        int in_w = src.cols;
        int in_h = src.rows;
        int tar_w = kIMAGE_W_;
        int tar_h = kIMAGE_H_;
        float r = min(float(tar_h) / in_h, float(tar_w) / in_w);
        r=min(r,float(1));
        int inside_w = round(in_w * r);
        int inside_h = round(in_h * r);
        int padd_w = tar_w - inside_w;
        int padd_h = tar_h - inside_h;
        padd_w=padd_w%64;   
        padd_h=padd_h%64;  
        cv::Mat resize_img;
        cv::resize(src, resize_img, cv::Size(inside_w, inside_h));
        //cvtColor(resize_img, resize_img, COLOR_BGR2RGB);

        padd_w = padd_w / 2;
        padd_h = padd_h / 2;
        // // std::cout<<"padd_w"<<padd_w<<"padd_h"<<padd_h<<std::endl;
        int top = int(round(padd_h - 0.1));
        int bottom = int(round(padd_h + 0.1));
        int left = int(round(padd_w - 0.1));
        int right = int(round(padd_w + 0.1));
        cv::copyMakeBorder(resize_img, resize_img, top, bottom, left, right, cv::BORDER_CONSTANT, cv::Scalar(114, 114, 114));
        return resize_img;
    }

**Comment by glenn-jocher** [comment]
@fatejzz I'm sorry, we don't have resources to review custom code, but we have a few YOLOv5 C++ Inference examples on ONNX and OpenVINO exported models here:

## C++ Inference

YOLOv5 OpenCV DNN C++ inference on exported ONNX model examples:
- https://github.com/Hexmagic/ONNX-yolov5/blob/master/src/test.cpp
- https://github.com/doleron/yolov5-opencv-cpp-python

YOLOv5 OpenVINO C++ inference examples:
- https://github.com/dacquaviva/yolov5-openvino-cpp-python

See Export tutorial for details:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️  RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Roboflow for Datasets, Labeling, and Active Learning](https://docs.ultralytics.com/yolov5/tutorials/roboflow_datasets_integration)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TFLite, ONNX, CoreML, TensorRT Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [Architecture Summary](https://docs.ultralytics.com/yolov5/tutorials/architecture_description)&nbsp; ⭐ NEW

Good luck 🍀 and let us know if you have any other questions!

**Comment by zhiqwang** [comment]
Hi @fatejzz , you can also refer following implementation, we rewrite it with OpenCV's C++ API .

https://github.com/zhiqwang/yolov5-rt-stack/blob/293b378fa2c7d1bc76fac75309b62a951680ac35/deployment/tensorrt/main.cpp#L80-L123

```cpp
float letterbox(
    const cv::Mat& image,
    cv::Mat& out_image,
    const cv::Size& new_shape = cv::Size(640, 640),
    int stride = 32,
    const cv::Scalar& color = cv::Scalar(114, 114, 114),
    bool fixed_shape = false,
    bool scale_up = true) {
  cv::Size shape = image.size();
  float r = std::min(
      (float)new_shape.height / (float)shape.height, (float)new_shape.width / (float)shape.width);
  if (!scale_up) {
    r = std::min(r, 1.0f);
  }

  int newUnpad[2]{
      (int)std::round((float)shape.width * r), (int)std::round((float)shape.height * r)};

  cv::Mat tmp;
  if (shape.width != newUnpad[0] || shape.height != newUnpad[1]) {
    cv::resize(image, tmp, cv::Size(newUnpad[0], newUnpad[1]));
  } else {
    tmp = image.clone();
  }

  float dw = new_shape.width - newUnpad[0];
  float dh = new_shape.height - newUnpad[1];

  if (!fixed_shape) {
    dw = (float)((int)dw % stride);
    dh = (float)((int)dh % stride);
  }

  dw /= 2.0f;
  dh /= 2.0f;

  int top = int(std::round(dh - 0.1f));
  int bottom = int(std::round(dh + 0.1f));
  int left = int(std::round(dw - 0.1f));
  int right = int(std::round(dw + 0.1f));
  cv::copyMakeBorder(tmp, out_image, top, bottom, left, right, cv::BORDER_CONSTANT, color);

  return 1.0f / r;
}
```

**Comment by fatejzz** [comment]
@zhiqwang @glenn-jocher 
when I convert the input image into the tensor according to the image shape and input it into the model, there will be some errors like the above. But when I created the 640x640x3 tensor, the model could run.

**Comment by fatejzz** [comment]
I just quote the two codes, and it can work well until now. but the 'letterbox'  has some differences in mechanisms from others.
`padd_w=padd_w%64;
padd_h=padd_h%64;`

**Comment by fatejzz** [comment]
@glenn-jocher 
After discussing it with others, I am wondering whether it is because when I use torchscript to export the model, the model's input size has been limited like [640,640].

**Comment by glenn-jocher** [comment]
@fatejzz yes, most exports require fixed input sizes. I think only PyTorch and ONNX --dynamic support dynamic input sizes.
