### ISSUE TITLE
About the weights.

### ISSUE THREAD

**Issue by ZeKunZhang1998** [ultralytics/yolov5#843]
## ❔Question

Hello! The pretrained weights of yolov5x.pt I got on the net is 170.14MB.But after training on my datasets the weights is much bigger than it,is about 670MB.Why?
## Additional context

**Comment by glenn-jocher** [comment]
EMA and optimizer are in your checkpoint. These are stripped once training finished. Ergo, your training is not finished or you stopped it prematurely.

**Comment by ZeKunZhang1998** [comment]
> EMA and optimizer are in your checkpoint. These are stripped once training finished. Ergo, your training is not finished or you stopped it prematurely.

Oh,do you mean that the 'model_dict' is more less than 670MB?I think I can set the dictionary 
                ckpt = {'epoch': epoch,
                        'best_fitness': best_fitness,
                        'training_results': f.read(),
                        'model': ema.ema.module if hasattr(model, 'module') else ema.ema,
                        'optimizer': None if final_epoch else optimizer.state_dict()}
------------->                 ckpt = {
                        'model': ema.ema.module if hasattr(model, 'module') else ema.ema,
                        }

**Comment by glenn-jocher** [comment]
@ZeKunZhang1998 if you have a partially trained checkpoint, and you want to finalize it (so it behaves like the official pretrained weights), you can use strip_optimizer():

https://github.com/ultralytics/yolov5/blob/a21bd0687ccccd2f7291b7ac41daca77d3cb8c12/utils/general.py#L675-L676

**Comment by ZeKunZhang1998** [comment]
Thanks, after this operation, the weights is 177MB.

**Comment by glenn-jocher** [comment]
Great! 😃
