### ISSUE TITLE
what type of exported network can used on fpga 

### ISSUE THREAD

**Issue by VYRION-Ai** [ultralytics/yolov5#8432]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

i need to transfer working from rasparry to fpga , and really i am lost
i donnot know the start point , the road map ,
now what is kind of net can work on fpga ( onnx or pt or       what)
can any one here me

**Comment by glenn-jocher** [comment]
@totoadel not sure, but the best CPU benchmarks are on ONNX and OpenVINO, so you could start there.
