### ISSUE TITLE
Train Data

### ISSUE THREAD

**Issue by almaxfirab** [ultralytics/yolov5#8433]
!python train.py --img 1024 --batch 16 --epochs 100 --data '../data.yaml'

according to the code, the image size is 1024x1024.
does anyone know how to train data whose size is 2048x1024?
thanks

**Comment by glenn-jocher** [comment]
@almaxfirab you can pass any size you want for training:
```
python train.py --imgsz ANYTHING
```

**Comment by UnglvKitDe** [comment]
@almaxfirab For training with rectangular images, there is the flag --rect. This will resize all the images along the longest edge (height or width). so in your case `--imgsz 2048 --rect`
