### ISSUE TITLE
Validation Image Size

### ISSUE THREAD

**Issue by UnglvKitDe** [ultralytics/yolov5#8434]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,
I have a question regarding the image size during validation. I've seen that next to the time specification during validation is printed that you would use the image size 768x768 (so squared).
https://github.com/ultralytics/yolov5/blob/898332433a71b8846b15daa276a8ac45c9efa98b/val.py#L285-L286
But if you print out the image size before the model() you get the 832x512.
https://github.com/ultralytics/yolov5/blob/898332433a71b8846b15daa276a8ac45c9efa98b/val.py#L206
So a rectangular input is used. Am I doing something wrong, or is this wanted? If not, then you could just take imgsz out of the output, I think that confuses more.
(I understand that you padded and that's where the difference of 768 to 832 comes from).

![image](https://user-images.githubusercontent.com/100289696/176894316-d6cbb04c-10e4-4a77-bd00-97935f037151.png)

**Comment by glenn-jocher** [comment]
@UnglvKitDe Speed line reports mean/max size of batches, batch size may vary as rectangular inference is used.

**Comment by UnglvKitDe** [comment]
@glenn-jocher ok, so I understand it correctly that rectangular images are **not** changed to a square image? Thx for your time :)

**Comment by UnglvKitDe** [comment]
@glenn-jocher here is the same output for coco128. i think the problem is that you take (batch_size, channels, imgsz, imgsz) and not (batch_size, channels, average_height, average_width) over the actual ones used
`python val.py --data coco128.yaml --weights yolov5n6.pt`
![image](https://user-images.githubusercontent.com/100289696/176901871-fd90bb2e-161e-45d2-a827-148a7f15e606.png)

**Comment by glenn-jocher** [comment]
@UnglvKitDe yes, that's correct. The val dataloader sorts images by aspect ratio for minimum overall inference FLOPs, so most batches will be rectangular if the dataset contains varied size images.

**Comment by UnglvKitDe** [comment]
@glenn-jocher All right, I got it. Thank you!

**Comment by glenn-jocher** [comment]
@UnglvKitDe you're welcome! If you have any more questions or need further assistance, feel free to ask. Good luck with your project!
