### ISSUE TITLE
Error loading ONNX model in opencv

### ISSUE THREAD

**Issue by Neskelogth** [ultralytics/yolov5#8439]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

I tried to load the onnx model yolov5s.onnx on opencv after exporting it from the .pt file found in the release. 
The command I used to export it is 
`python export.py --weights yolov5s.pt --include onnx`
as seen in the instructions of the release. The problem is that if I try to load the model in opencv I get this error
`[ERROR:0@14.876] global D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp (1021) cv::dnn::dnn4_v20220524::ONNXImporter::handleNode DNN/ONNX: ERROR during processing node with 1 inputs and 1 outputs: [Identity]:(onnx_node!Identity_0) from domain='ai.onnx'
Traceback (most recent call last):
  File "D:\Unitn\Corsi\Computer vision\project\synopsis\main.py", line 24, in <module>
    bg_frames = find_bg_frames(video, duration, fps)
  File "D:\Unitn\Corsi\Computer vision\project\synopsis\utils.py", line 152, in find_bg_frames
    people_found = find_people_with_yolo(frame)
  File "D:\Unitn\Corsi\Computer vision\project\synopsis\utils.py", line 102, in find_people_with_yolo
    net = cv2.dnn.readNet(weights)
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:1040: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20220524::ONNXImporter::handleNode'
Node [Identity@ai.onnx]:(onnx_node!Identity_0) parse error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\layer.cpp:246: error: (-215:Assertion failed) inputs.size() in function 'cv::dnn::dnn4_v20220524::Layer::getMemoryShapes'`
While downloading a onnx file from [this link](https://github.com/doleron/yolov5-opencv-cpp-python/raw/main/config_files/yolov5s.onnx) the problem does not appear. I hope it's clear enough

### Environment

-YOLO: YOLOv5s 
-OS: Windows 10
-Python: 3.10.0
-OpenCV: 4.6.0

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Neskelogth see Export tutorial for OpenCV DNN and C++ details.

## OpenCV DNN inference

OpenCV inference with ONNX models:
```bash
python export.py --weights yolov5s.pt --include onnx

python detect.py --weights yolov5s.onnx --dnn  # detect
python val.py --weights yolov5s.onnx --dnn  # validate
```

## C++ Inference

YOLOv5 OpenCV DNN C++ inference on exported ONNX model examples:
- https://github.com/Hexmagic/ONNX-yolov5/blob/master/src/test.cpp
- https://github.com/doleron/yolov5-opencv-cpp-python

YOLOv5 OpenVINO C++ inference examples:
- https://github.com/dacquaviva/yolov5-openvino-cpp-python


## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️  RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Roboflow for Datasets, Labeling, and Active Learning](https://docs.ultralytics.com/yolov5/tutorials/roboflow_datasets_integration)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TFLite, ONNX, CoreML, TensorRT Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [Architecture Summary](https://docs.ultralytics.com/yolov5/tutorials/architecture_description)&nbsp; ⭐ NEW

Good luck 🍀 and let us know if you have any other questions!

**Comment by zouzhen** [comment]
I had the same problem.
**Environment**
-YOLO: YOLOv5s
-OS: Windows 10
-Python: 3.10.0
-OpenCV: 4.5.5.64

**Comment by msly** [comment]
use pytorch 1.11 solved (before is 1.12 has same error)

**Comment by zouzhen** [comment]
@msly Thanks, I'm ready to run like you said,

**Comment by YK-1340** [comment]
solved my problem

**Comment by Damix48** [comment]
> use pytorch 1.11 solved (before is 1.12 has same error)

Before exporting or before training?

**Comment by niniack** [comment]
before exporting. 

I tried exporting with 1.12, found this issue, downgraded, and tried detecting/training with 1.11 but it failed. 

Then did exporting and detecting both with 1.11 and it worked!

**Comment by Shubham-Zope** [comment]
How do you export onnx with 1.11.0

**Comment by Shubham-Zope** [comment]
> before exporting.
> 
> I tried exporting with 1.12, found this issue, downgraded, and tried detecting/training with 1.11 but it failed.
> 
> Then did exporting and detecting both with 1.11 and it worked!

How did you exported onnx with 1.11.0

**Comment by tsvetiko** [comment]
Using `opencv-python==4.6.0.66` solved the issue for me!

**Comment by wvalcke** [comment]
Which pytorch version ? 1.11 or 1.12, or ... 1.13 or ...?
What is now the recommended pytorch version for yolov5 which supports all features for export/train/detect....
thanks !

**Comment by wvalcke** [comment]
I just tested with opencv-python 4.6.0.66: this does NOT work, the error is the same as with the C++ test i've done.
I did an export of a yolo5s model to onnx using pytorch 1.12.1.
It is said this works with pytorch 1.11, but than it has problems with training, (see above the discussion), is this correct?
Does anyone actually knows which versions work an all situations?

**Comment by 0xBYTESHIFT** [comment]
I got "handleNode DNN/ONNX: ERROR during processing node with 1 inputs and 1 outputs" after exporting using a colab, provided in a readme. This is a mess...

**Comment by glenn-jocher** [comment]
https://github.com/ultralytics/yolov5/pull/10368

**Comment by vlarobbyk** [comment]
Hello. To fix the error you must to export the PyTorch model to ONNX adding the paramter --opset 12. The complete command will look like as following:

`python export.py --weights models/yolov5n.pt --opset 12 --simplify --include onnx`

**Comment by glenn-jocher** [comment]
@vlarobbyk thanks for sharing this solution! We appreciate your contribution to the community. 🙌 If you encounter any additional issues or have further insights, feel free to share them.
