### ISSUE TITLE
check_requirements can't handle nested requirements

### ISSUE THREAD

**Issue by xstast24** [ultralytics/yolov5#8448]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Other

### Bug

Method `utils.general.check_requirements()` can't handle nested requirements.
#### Example:
- create _dev.txt_ file with custom requirements, e.g.:
```
coloredlogs==15.0.1
```
- add that file to the default yolo _requirements.txt_, e.g. as the first line:
```
-r dev.txt

~the rest of the requirements file remains untouched~
```

Run `check_requirements()` to check the _requirements.txt_ file -> error is displayed, requirements are not checked:
`Parse error at "'-r dev.t'": Expected W:(abcd...)`
The error is thrown on line [344](https://github.com/ultralytics/yolov5/blob/29d79a6360d8c7da8875284246847db3312e270a/utils/general.py#L344) by `pkg.parse_requirements(f)`, which can't handle nested requirements.

### Minimal Reproducible Example

Add a line with nested requirements file `-r dev.txt` into _requirements.txt_ (you don't even need to create the dev.txt file, cos the error is thrown before it would be loaded).

Run python script:
```
from utils.general import check_requirements
check_requirements()  # tries to check requirements.txt, but fails with Parse error at "'-r dev.t'": Expected W:(abcd...)
```

### Additional info
I searched some more and found that package _safety_ has this functionality implemented https://github.com/pyupio/safety/blob/ab49cb1beb758d006c10a934c700f489995b759a/safety/util.py#L37

### Environment

YOLOv5 v6.1
Python 3.9

**Comment by AyushExel** [comment]
Thanks for raising the issue. This seems more like a feature request and looks very doable. I'll take a look.
Meanwhile, Can't you just pass your custom requirements file to `check_requirements("dev.txt")` ?

**Comment by xstast24** [comment]
Hi @AyushExel , thanks for handling this. To answer your comment:
1) Yes, in the current state (single requirements file) it is a feature request, not a bug report - I didn't find a correct tag for that :-) 
2) Yes, in the context of this example, a single (flat) requirements file can be passed as a param - that works.

**Comment by glenn-jocher** [comment]
@xstast24 this is a good point. We don't use nested requirements currently but it might be useful to make `check_requirements()` more robust to this edge case to offer that option in the future. Can you please submit a PR with this change? The relevant code is fully contained in check_requirements() here. 

https://github.com/ultralytics/yolov5/blob/c7689198bc66023378f71aa80c0829a763a928bd/utils/general.py#L335-L370
