### ISSUE TITLE
Vanishing Gradient YOLOv5x in small object detection

### ISSUE THREAD

**Issue by dokeefemain** [ultralytics/yolov5#8449]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

I was training YOLOv5x for traffic sign detection and after like 10 epoch I believe the gradient just went to 0. Traffic sign detection is a notoriously difficult problem for most object detection models because of their poor preformance in small object detection so I figure that might be what's happening here. I wish there was a paper on these models so I could try to get to the bottom of it but as we all know that's not the case. I would say that I might be doing something wrong but I don't think this is the case because I'm currently training YOLOv5m and it's working perfectly.

### Additional

Here's a link to the training data I used if anyone wants to give it a shot
https://drive.google.com/drive/folders/18lHZqIttqHXkNFIMiZUxdddf-TqqLIW4?usp=sharing

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by dokeefemain** [comment]
NVM I just realized that I did some miscalculations when I created my training data :(

**Comment by glenn-jocher** [comment]
@dokeefemain no worries! Mistakes happen to the best of us. If you have any more questions in the future, feel free to ask. Good luck with your training!
