### ISSUE TITLE
Huge difference between MAP of training and testing

### ISSUE THREAD

**Issue by gaopinghai** [ultralytics/yolov5#845]
When training yolov5s model with my own data, the training result is as below:
![results](https://user-images.githubusercontent.com/19465753/91378646-8769aa00-e853-11ea-8c34-c1c29191b497.png)
As we can see the precision is 0.89, Recall is 0.98 and map.5 is 0.84.
But when I test the `best.pt` using test.py, the output is very poor as below:
```
Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 13/13 [00:02<00:00,  4.35it/s]
all         200         200        0.34        0.37       0.159      0.0506
```
I am using the exactly same val data and the best weights obtained when training, why?
Please help! Thanks guys!

**Comment by glenn-jocher** [comment]
@PingHGao a picture is worth a thousand words. Would suggest you simply load your results.png file (in runs/exp#) instead of all these numbers.

Your test differences are interesting, however. This may be connected to autoanchor. Can you reproduce this in a Google Colab notebook for us, so we can just click the cells and see the same result?

**Comment by gaopinghai** [comment]
> @PingHGao a picture is worth a thousand words. Would suggest you simply load your results.png file (in runs/exp#) instead of all these numbers.
> 
> Your test differences are interesting, however. This may be connected to autoanchor. Can you reproduce this in a Google Colab notebook for us, so we can just click the cells and see the same result?

I have update the question. What dose autoanchor means sir? I write mine own test.py to calculate P and R which are reasonable. Note that my data is single calss.

**Comment by glenn-jocher** [comment]
@PingHGao please provide a google colab notebook that reconstructs your steps to reproduce your error message.

**Comment by buimanhlinh96** [comment]
@PingHGao Did you find out the reason? I meet the same problem with you!

**Comment by gaopinghai** [comment]
> @PingHGao Did you find out the reason? I meet the same problem with you!

I write mine own test.py to calculate P and R. Thus I didnot spend too much time on it.
