### ISSUE TITLE
Augmentation translate and fliplr !

### ISSUE THREAD

**Issue by sarpx** [ultralytics/yolov5#8453]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,
What is the difference between augmentation translate and fliplr in Yolov5?

**Comment by sarpx** [comment]
I guess the ratio of this object to be approximated left and right, front and back, or sectioned?

**Comment by AyushExel** [comment]
In flip, an image is flipped in a given direction to a certain degree.
In translation, an image is moved  either along the x-axis or y-axis.

**Comment by sarpx** [comment]
Yes great..
I knew this could happen, but it just sat better in my head when you wrote it. I understood what was what. Thank you

**Comment by glenn-jocher** [comment]
@sarpx you're very welcome! It's great to hear that the explanation was helpful for you. If you have any more questions, feel free to ask!
