### ISSUE TITLE
About fp32 benchmark result

### ISSUE THREAD

**Issue by spacewalk01** [ultralytics/yolov5#8454]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I would like to ask if YOLOv5 result `Speed V100 b32 (ms)` shown on the table uses fp16 precision (--half) as default? 

`python val.py --data coco.yaml --img 640 --task speed --batch 1`
![image](https://user-images.githubusercontent.com/6389915/177087184-80ca28df-d682-46b8-912d-27bd882cfeae.png)

**Comment by glenn-jocher** [comment]
@spacewalk01 these are FP16 torch inference times, but you can achieve much faster inference with TensorRT:

- See https://docs.ultralytics.com/yolov5/tutorials/model_export to export to ONNX or OpenVINO for up to 3x CPU speedup (https://github.com/ultralytics/yolov5/pull/6613)
- See https://docs.ultralytics.com/yolov5/tutorials/model_export to export to TensorRT for up to 5x GPU speedup (https://github.com/ultralytics/yolov5/pull/6963)

### Colab Pro+ V100 High-RAM Results

```
benchmarks: weights=/content/yolov5/yolov5s.pt, imgsz=640, batch_size=1, data=/content/yolov5/data/coco128.yaml, device=0, half=False, test=False
Checking setup...
YOLOv5 🚀 v6.1-135-g7926afc torch 1.10.0+cu111 CUDA:0 (Tesla V100-SXM2-16GB, 16160MiB)
Setup complete ✅ (8 CPUs, 51.0 GB RAM, 46.7/166.8 GB disk)

Benchmarks complete (458.07s)
                   Format  mAP@0.5:0.95  Inference time (ms)
0                 PyTorch        0.4623                10.19
1             TorchScript        0.4623                 6.85
2                    ONNX        0.4623                14.63
3                OpenVINO           NaN                  NaN
4                TensorRT        0.4617                 1.89
5                  CoreML           NaN                  NaN
6   TensorFlow SavedModel        0.4623                21.28
7     TensorFlow GraphDef        0.4623                21.22
8         TensorFlow Lite           NaN                  NaN
9     TensorFlow Edge TPU           NaN                  NaN
10          TensorFlow.js           NaN                  NaN
```
