### ISSUE TITLE
Get the mAP in val.py

### ISSUE THREAD

**Issue by cyndyNKCM** [ultralytics/yolov5#8456]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello @glenn-jocher 

Please how can i modify the val.py code to get the map ?
I want to use this value as a metric in order to choose the best metric after a set of actions.

**Comment by cyndyNKCM** [comment]
I want that the val.py code does not only print the differents informations (P, R, map,...) but also return the map.
I will use this map in the following steps of my project.

**Comment by AyushExel** [comment]
@cyndyNKCM val.py already does both the things. It prints out the scores and also returns them. Here's val.py executing on a colab
<img width="1380" alt="Screenshot 2022-07-04 at 12 41 39 PM" src="https://user-images.githubusercontent.com/15766192/177101335-f7daf09e-b558-4934-97ea-49440b2093b4.png">


And here you can see that it returns those results https://github.com/ultralytics/yolov5/blob/master/val.py#L327

**Comment by cyndyNKCM** [comment]
Yes i know it but i want that the !python val.py returns the map. 
I have integrated the line !python val.py in a function because i want also the map not only the values printed in the console. 
I don't know if it is possible to get the map.

**Comment by cyndyNKCM** [comment]
> 
Thank you for your answer @AyushExel 

Can i just return the map in the line 327 ?

**Comment by cyndyNKCM** [comment]
i want to have the map value in a variable. So how can i modify the val.py code in order to have this?
![Capture d’écran (78)](https://user-images.githubusercontent.com/65983769/177106920-4ca03091-7681-4dab-bda7-17a552673431.png)

**Comment by AyushExel** [comment]
@cyndyNKCM yes that line returns maps already. I think you're trying to import the functionality in a custom module. Maybe you should try something like this.
```
import val
metrics = val.run(...)
return metrics
```
Improving programmatic interface is something that we're thinking about, you can expect improvements in the future

**Comment by cyndyNKCM** [comment]
@AyushExel Thank you i am testing it now and will come back to you.

**Comment by cyndyNKCM** [comment]
> @cyndyNKCM yes that line returns maps already. I think you're trying to import the functionality in a custom module. Maybe you should try something like this.
> 
> ```
> import val
> metrics = val.run(...)
> return metrics
> ```
> 
> Improving programmatic interface is something that we're thinking about, you can expect improvements in the future

metrics = val.run(!python val.py ....) ?

**Comment by cyndyNKCM** [comment]
@AyushExel  This is what is printed after executing the def yolo() function previously written.



![Capture d’écran (80)](https://user-images.githubusercontent.com/65983769/177115730-c0d9b599-1555-471b-877d-fa3748c34bb2.png)

**Comment by AyushExel** [comment]
Can you share the colab?

**Comment by cyndyNKCM** [comment]
![Capture d’écran (83)](https://user-images.githubusercontent.com/65983769/177118633-8437e54f-b1c0-48e2-a024-cdec93b82471.png)

**Comment by cyndyNKCM** [comment]
Please don't care about the "pipeline".
I introduce the val.py function in the pipeline function and i want that the pipeline function returns the mAP after a set of actions.

**Comment by cyndyNKCM** [comment]
> ![Capture d’écran (83)](https://user-images.githubusercontent.com/65983769/177118633-8437e54f-b1c0-48e2-a024-cdec93b82471.png)

![Capture d’écran (78)](https://user-images.githubusercontent.com/65983769/177119227-29653fb5-4d24-4a59-a1a9-bb384c8edf4a.png)

**Comment by cyndyNKCM** [comment]
I don't modify anything in the val.py code. Do you think i should modify something here? If so which line?

**Comment by cyndyNKCM** [comment]
In the line 327 i modify the return and i put only "return map50".
When i print map50[ 110], i have this.
The value that i want is 0.533 which corresponds to the map.5

![Capture d’écran (85)](https://user-images.githubusercontent.com/65983769/177121157-e427df93-c8f8-4c10-9158-fcefcbcf4112.png)

**Comment by AyushExel** [comment]
@cyndyNKCM you're not using the snippet that I shared..Please use that. I've used it like this before:
```
import val
metrics = val.run(...)
return metrics
```
Maybe what you're doing might work but I have no idea

**Comment by cyndyNKCM** [comment]
My session crashes when i use this snippet.

**Comment by cyndyNKCM** [comment]
@AyushExel It works well now. Thank you

**Comment by zaghdoud2019** [comment]
> @AyushExel It works well now. Thank you

please how did you do it i need this snippet;I use this:
def yolo():
 import val
 metrics = val.run()
 return metrics

but any think it output
