### ISSUE TITLE
loss of focus!

### ISSUE THREAD

**Issue by sarpx** [ultralytics/yolov5#8458]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

My success rate differs in close-up and distance-shooting pictures. While success increases in distant pictures, success and confusion (cat, dog) increase in close-up pictures. Is this a loss of focus? Is there any way I can solve this?

**Comment by glenn-jocher** [comment]
@sarpx you might try increasing scale hyperparameter from 0.5 to 0.9. This will add more scale augmentation to your training to be able to detect the same objects smaller and larger.
https://github.com/ultralytics/yolov5/blob/c7689198bc66023378f71aa80c0829a763a928bd/data/hyps/hyp.scratch-low.yaml#L27

**Comment by sarpx** [comment]
@glenn-jocher  Thank you for the answer.
Do you think I should use scale and --multi-scale together or separately?

**Comment by glenn-jocher** [comment]
@sarpx --multi-scale is not recommended
