### ISSUE TITLE
cls scaling with evolved hyperparameter

### ISSUE THREAD

**Issue by lorenzomammana** [ultralytics/yolov5#846]
## ❔Question

In train.py there's at line 179 this piece of code

```
    hyp['cls'] *= nc / 80.  # scale coco-tuned hyp['cls'] to current dataset
```

I was wondering if it's correct to use it even after the hyperparameter evolution done on my dataset that has a lot less classes.
(Or just every time we don't use the coco default hyperparams)

**Comment by glenn-jocher** [comment]
@lorenzomammana this line scales cls by class count. It's independent of the hyp cls value and should not be modified.

**Comment by lorenzomammana** [comment]
Ok, thanks!
