### ISSUE TITLE
I want to provide GUIs

### ISSUE THREAD

**Issue by Thames1997** [ultralytics/yolov5#8462]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello everyone

Is there any way to provide GUIs to count real time human detection using Yolo5 with OpenCV?

I need this for my Masters Degree 

Thank you in advance

**Comment by glenn-jocher** [comment]
@Thames1997 maybe try streamlit for web GUIs, i.e. here's an example https://discuss.streamlit.io/t/integrate-streamlit-with-yolov5-object-detection/16764

**Comment by VYRION-Ai** [comment]
@Thames1997 
use this 
https://github.com/cnyvfang/YOLOv5-GUI
 or this search ( https://github.com/search?q=gui+yolov5)
