### ISSUE TITLE
In which line of code is results.csv generated/updated

### ISSUE THREAD

**Issue by cnavarrete** [ultralytics/yolov5#8467]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Greetings, I've been trying to find where **results.csv** is generated and updated, but so far I've had no luck. I'm working on a proyect where I need to update **results.csv** with some custom metrics, so I really need to know this-

**Comment by glenn-jocher** [comment]
@cnavarrete CSV logger is here, runs `on_fit_epoch_end()` callback:
https://github.com/ultralytics/yolov5/blob/c7689198bc66023378f71aa80c0829a763a928bd/utils/loggers/__init__.py#L132-L141

**Comment by cnavarrete** [comment]
@glenn-jocher Wow that was really fast, thank you!

**Comment by glenn-jocher** [comment]
@cnavarrete you're welcome! If you have any more questions or need further assistance, feel free to ask. Our YOLOv5 community and the Ultralytics team are always here to help.
