### ISSUE TITLE
Focus

### ISSUE THREAD

**Issue by ycdhqzhiai** [ultralytics/yolov5#847]
## ❔Question
I'd like to know how much effect the removal of Focus structure will have on map. Has anyone tried it

**Comment by Aktcob** [comment]
+1

**Comment by glenn-jocher** [comment]
Focus() module is designed for FLOPS reduction and speed increase, not mAP increase.

**Comment by glenn-jocher** [comment]
Also designed for layer count reduction. 1 Focus module replaces 3 yolov3/4 layers.

**Comment by captainst** [comment]
I have a question concerning the focus layer: while it reduces the computation cost, does the "stride" sampling mess the coordinates of the ground truth bounding box ?

**Comment by glenn-jocher** [comment]
@captainst Focus (and it's new v6.0 replacement) stack spatial information into channel space, so it's possible 1 pixel's worth of regression information may be reduced, though for most use cases regression accuracies will never approach 1 pixel anyway.

**Comment by captainst** [comment]
@glenn-jocher Many thanks. Now I appreciate why the focus layer is appied only once on the raw input image in the very beginning of the pipeline.

**Comment by glenn-jocher** [comment]
@captainst yes, for classification models it might be more usable later on in the backbone, but probably not for detection models without losing mAP@0.5:0.95 (mAP@0.5 would be less affected).
