### ISSUE TITLE
Train & inference on different image resolutions

### ISSUE THREAD

**Issue by TalBarami** [ultralytics/yolov5#8471]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, and thank you for this excellent repository.
I am trying to train a YOLOv5 model on my custom dataset. However, I have a lot of images (sampled from annotated video clips) with a relatively large set of image resolutions-
(1072, 1920), (1080, 1920), (1280, 1024), (1280, 720), (1920, 1080), (2688, 1520), (720, 1280)

I wonder if YOLOv5 scales the input somehow during training & inference to the size expected by the model or if I should do it manually as part of my data preprocessing.

I appreciate any help you can provide.
Tal

**Comment by UnglvKitDe** [comment]
@TalBarami  Hi, Yolov5 has several options. You can train a square input e.g. 640x640. For this you have to use --imsz 640. If you want to use a rectangular size, then use --rect. How --rect works is explained in numerous other issues e.g. [here](https://github.com/ultralytics/yolov5/issues/8433#issuecomment-1172342525). The images will always be resized to this size automatically. You only need the data. A tip: Have a look at the docs, there is a good step by step guide.

**Comment by TalBarami** [comment]
Hey @UnglvKitDe, thank you for your kind reply.
So just to make sure, I'll train with --img 640 and --rect the same way I did previously with the CustomDataset tutorial, with pre-trained weights of the 640 model. This is what I'm about to execute
`python -m torch.distributed.run --nproc_per_node 2 train.py --batch 32 --img 640 --rect --data child_detection.yaml --weights yolov5m.pt --device 0,1`
Does that make sense for that type of input shape I mentioned?
Where can I find the docs relevant to the input size? Unfortunately, I couldn't find any.

Again, thanks a lot!

**Comment by UnglvKitDe** [comment]
Hi @TalBarami , the required image size depends primarily on how large the objects you want to detect are. If you have many very small objects, you can try higher resolutions. yolov5m6 was trained with 1280x1280. If the results are too bad, then try this :)
