### ISSUE TITLE
Train yolov5 with yolov5v2.0 architecture

### ISSUE THREAD

**Issue by sdimantsd** [ultralytics/yolov5#8479]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, 
Is it possible to train yolov5 with yolov5v2.0 architecture?
For example:

v2 architecture:
![image](https://user-images.githubusercontent.com/29533264/177331770-d196ee0f-f406-400f-ad95-9f3b323dda9c.png)

current architecture:
![image](https://user-images.githubusercontent.com/29533264/177331864-b6f251ba-8a24-46a8-bd58-44088475c083.png)

**Comment by glenn-jocher** [comment]
@sdimantsd I would recommend the newest models (v6.1) for the best results.

**Comment by sdimantsd** [comment]
@glenn-jocher 
You right of curse, but I used HAILO device, and it cann't optimize the v6.1
It can optimize only the v2.0

**Comment by glenn-jocher** [comment]
@sdimantsd whats a HAILO device?

**Comment by sdimantsd** [comment]
@glenn-jocher 
It's a gpu edge device. it's cost about 150$ and it's run yolov5 v2.0 in about 160 FPS.
In V6.1 I get 90 FPS.
This is the link to their website: https://hailo.ai/

**Comment by glenn-jocher** [comment]
@sdimantsd oh, really strange. Well you should be able to train v2.0 models without issue, just checkout the v2.0 release and pip install those requirements.

**Comment by sdimantsd** [comment]
You are right.
But I want to use all the others benefits in the new releases (like using wandb for logging and compute best anchors).

**Comment by glenn-jocher** [comment]
@sdimantsd just pick whatever's most important to you then.

**Comment by sdimantsd** [comment]
OK, Thanks

**Comment by glenn-jocher** [comment]
@sdimantsd you're welcome, happy to help!
