### ISSUE TITLE
Convert pytorch model to ncnn format

### ISSUE THREAD

**Issue by zxj11838** [ultralytics/yolov5#848]
## ❔Question
I try to convert pytorch model to ncnn format，the conversion to onnx format is successful.  When converting from onnx to ncnn, the following prompt appears：
Unsupported slice step !
Unsupported slice step !
Has anyone encountered this problem？

**Comment by pfeatherstone** [comment]
@zxj11838 I am rarely able to convert an onnx model to ncnn, even when using onnx-simplifier first. It just never works

**Comment by sabo-gu** [comment]
> ## ❔Question
> I try to convert pytorch model to ncnn format，the conversion to onnx format is successful. When converting from onnx to ncnn, the following prompt appears：
> Unsupported slice step !
> Unsupported slice step !
> Has anyone encountered this problem？

the ncnn does not support slice operation，you can change the code in the commom.py like this, delete the slice operation
![image](https://user-images.githubusercontent.com/39322760/91424791-d8e25b00-e88c-11ea-8044-2f81e365b789.png)

**Comment by zxj11838** [comment]
Thank you for your answer, I would like to know whether it will affect the effect of the model？

**Comment by zxj11838** [comment]
According to your method, I successfully converted the ncnn model. When testing in the Android project, many boxes appeared, and the accuracy rate was very low. Does anyone know how to solve it?

**Comment by 307509256** [comment]
see here：https://zhuanlan.zhihu.com/p/275989233
