### ISSUE TITLE
How to train 16bit grayscale images?

### ISSUE THREAD

**Issue by pourmand1376** [ultralytics/yolov5#8481]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Issues I've read:
- [How to use dicom images for training? ](https://github.com/ultralytics/yolov5/issues/1440)
- [how to train grayscale images (sigle channel) on yolov5](https://github.com/ultralytics/yolov5/issues/6288)
- [Training & Inference on greyscale images](https://github.com/ultralytics/yolov5/issues/634)

I have 16-bit grayscale images. Until now, I've converted all images to `grayscale png` with 16-bit depth. YOLOv5 works but it doesn't give good results. One of my assumptions is that since a lot of information is lost, training results is not good. The images were original `dcm` format and I converted them to `png` to be able to read it. 

I read source code and I understood that YOLO convert png image to 8bit. To be specific, whenever I see `cv2.imread` it is like this:
```python
cv2.imread(path_to_file)
# it should be like this to read 16bit depth (as is)
cv2.imread(path_to_file, -1)
```

I changed every `imread` function and also changed every scaling from 255 to 65535, but I am not able to get any results. I get some weird error which I can not trace back.
```
libpng error: PNG input buffer is incomplete
```
There is also a [stackoverflow post](https://stackoverflow.com/questions/21616627/libpng-errors-not-being-caught-by-try-catch-block) about this but it doesn't help. 

I try to get my image to work with YOLOv5, but it appears hopeless. Could you please give me a starting point?

**Comment by glenn-jocher** [comment]
@pourmand1376 I don't think you want to try using 16 bit imagery. uint8 is the standard across all ML, and the 255 value is hard coded in multiple places throughout the repository, as well as the assumption built into many functions, not to mention your model will be unable to deploy using any standard workflows.

If you have greyscale imagery I would simply convert these to normal greyscale PNGs like you did and let YOLO train on them directly without any modifications. You might disable HSV augmentation or visit the Tips for Best Training Tutorial for training best practices.

**Comment by pourmand1376** [comment]
Thank you. 

As each patient in my case has 200 images and they are totally related, do you recommend creating a 16 channel image (each image is gray-scale) which consists 16 random samples from the same patient and make model learn that thing? (Something like #1741)

Currently it seems that I am not using all information which a patient has, I am just using a 1% of information.

**Comment by glenn-jocher** [comment]
@pourmand1376 oh I see. Well if you have 200 channels you could just submit all 200.

But you are confusing topics. 8 bits or 16 bits is just the color depth of a channel. 3ch vs 1ch is about RGB vs greyscale. You can have RGB images at 8, 16, 32, 64 bits and they still only have 3 channels.

**Comment by pourmand1376** [comment]
Well.Thanks for explanation. 

I should have created another issue for this one. Mixing issues is not a good idea. 

My question is resolved so I think it is best to close this issue. 

Thank you again🙏

**Comment by glenn-jocher** [comment]
@pourmand1376 you're welcome! 🙏 I'm glad I could help clarify things for you. If you have any more questions in the future, please feel free to open a new issue. Have a great day!
