### ISSUE TITLE
@glenn-jocher sir does, --evolve used for tuning hyperparameter....if so... why dont we use said method first ...based on the result update the hyperparameter file and then go for training.. is it better approach

### ISSUE THREAD

**Issue by PraveenMNaik** [ultralytics/yolov5#8488]
@glenn-jocher sir does, --evolve used for tuning hyperparameter....if so... why dont we use said method first ...based on the result update the hyperparameter file and then go for training.. is it better approach

_Originally posted by @PraveenMNaik in https://github.com/ultralytics/yolov5/issues/990#issuecomment-1168327901_

**Comment by glenn-jocher** [comment]
@PraveenMNaik yes that's the correct workflow:

1. evolve hyperparameters on your scenario
2. train a new model on your scenario using the evolved hyps from (1)
