### ISSUE TITLE
How to set name to experimentation to W&B

### ISSUE THREAD

**Issue by JNaranjo-Alcazar** [ultralytics/yolov5#8489]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I would like to name muy training procedure so I have the same name locally and in W&B platform. By default, W&B creates a random name each time I train. How can I set a name to the run for W&B?

**Comment by AyushExel** [comment]
Pass the name you want in the `--name` flag, like:
```
python train.py ... --name NAME
```
