### ISSUE TITLE
Epochs are not displayed

### ISSUE THREAD

**Issue by EdouardEPFL** [ultralytics/yolov5#8490]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I'm currently running and training a model from scratch on a huge dataset ~25K pictures.
I'm doing it through Spyder installed on anaconda.
My problem is that once I runned the training I have 0 informations, I don't see any epochs achivied as in the tutorial. Hence I just can't know if my training will run for 10 minutes or 10days. 

Is there anyway to solve this ? Even if it's imply to use another IDE than Spyder.

Thank you in advance for any kind of help. 

### Additional
I even tried to load my project with google colab on local environnement (through Jupyter), and still the same thing. Why am I the only one with nothing displayed about epochs ?

_No response_

**Comment by glenn-jocher** [comment]
@EdouardEPFL not sure why you're not seeing any console output, but you can also log training to W&B, TensorBoard and CSV. results.csv is automatically logged locally at runs/train/exp. 

For W&B and TensorBoard logging examples see our Colab notebook Train section:
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb?hl=en

**Comment by Aanchal157** [comment]
Q1. How to calculate Average Precision(AP) specifically for each class in YOLOv5? ( although i have already obtained mean average precision values)
Q2. How to perform real-time detection(Live camera feed) in Google Colab?

**Comment by glenn-jocher** [comment]
@Aanchal157 AP is displayed for each class by val.py. mAP is mean AP for all classes.

**Comment by EdouardEPFL** [comment]
> @EdouardEPFL not sure why you're not seeing any console output, but you can also log training to W&B, TensorBoard and CSV. results.csv is automatically logged locally at runs/train/exp.
> 
> For W&B and TensorBoard logging examples see our Colab notebook Train section: https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb?hl=en

As you said you were wright, it works fine using the results.csv however I don't know why it's not displayed directly on my console. Maybe something is missing to allow the visualisation, idk.
