### ISSUE TITLE
Error in .pb model output from detect.py when exported with --nms

### ISSUE THREAD

**Issue by git-hamza** [ultralytics/yolov5#8492]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I exported the model to .pb keeping --nms flag true using the following command.
`python export.py --weights checkpoints/yolov5n.pt --device 0 --include pb --nms`

When I run the exported model in detect.py, it give me error in https://github.com/ultralytics/yolov5/blob/fdc9d9198e0dea90d0536f63b6408b97b1399cc1/detect.py#L127

Is there any flag or something with the help of which I can run the detect.py script successfully for --nms exported models.
It is pertinent to mention that output of https://github.com/ultralytics/yolov5/blob/fdc9d9198e0dea90d0536f63b6408b97b1399cc1/detect.py#L122
from the exported .pb model with --nms flag is of shape (1,100,4). Now I get that we have 4 co-ordinates of bounding box, but where is the class name or where can I get that?

### Additional

  P.S. Error

  File "detect.py", line 127, in run
    pred = non_max_suppression(pred, conf_thres, iou_thres, classes, agnostic_nms, max_det=max_det)
  File "/yolov5/utils/general.py", line 792, in non_max_suppression
    xc = prediction[..., 4] > conf_thres  # candidates
IndexError: index 4 is out of bounds for dimension 1 with size 4

**Comment by glenn-jocher** [comment]
@git-hamza all the YOLOv5 inference methods are intended for models without NMS as they utilize torch NMS for postprocessing, i.e. for *.pb just export without the --nms flag and then you can use it with detect.py.

**Comment by git-hamza** [comment]
@glenn-jocher then what is the use of exporting the model with --nms flag if we are unable to use it? I know I can convert the model without --nms flag and then I can use it with detect.py script.
However when I export the model with --nms flag, its prediction only gives me the bounding box, it would be better to provde the classes names and probability information as well. 

P.S. I use my custom script for when trying to infer the model with --nms flag exported model. When I print the pred output from model(image), it only has bounding box information.

**Comment by glenn-jocher** [comment]
@git-hamza --nms exports are experimental and are intended for custom use cases. If you'd like to see additional features in the output then please submit a PR to add confidence and class. The NMS function used by the TF models is here:
https://github.com/ultralytics/yolov5/blob/39d7a93619083cb8e37f5ef7708cf50b34e20ee1/models/tf.py#L438-L462
