### ISSUE TITLE
Vertical video detection flipped upside-down

### ISSUE THREAD

**Issue by chmjelek** [ultralytics/yolov5#8493]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

I have two `.mp4` videos:

- first one is recorded vertically, frame width is 1920, height 1080 (from exiftool)
- second one is recorded horizontally, frame width is also 1920, height 1080 (from exiftool)

For detection I'm using:

`python detect.py --weights runs/train/my_modelweights/best.pt --source video1.mp4 --data data/custom.yaml --imgsz 1280`

For the first video I'm getting:

`video 1/1 (1/1774) video1.mp4: 1280x768 Done. (0.012s)`

For the second one:

`video 1/1 (1/1182) video2.mp4: 768x1280 Done. (0.013s)`

The problem is that detection for the first video is is flipped upside-down (180 degrees compared to the original video).

Why is that, how to fix it?

### Environment

- Ubuntu: 18.04

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@chmjelek it's possible certain EXIF info may not be read correctly from all formats, especially for manually rotated videos. We use two 4k iPhone-captured videos to verify video inference, one portrait, one landscape, and both of these work correctly in our tests:

https://github.com/ultralytics/yolov5/releases/download/v1.0/decelera_landscape.mov
https://github.com/ultralytics/yolov5/releases/download/v1.0/decelera_portrait.mov

**Comment by DoAlone** [comment]
Hello, I think the above problems do exist. My detection results is  shown in the figure. I used the video taken by iPhone 12 Pro Max, and there was a result of flipping up and down.
![123](https://user-images.githubusercontent.com/37893030/187659578-0f1efaf5-f8dc-4b0f-ab7c-c200c1a30460.png)

**Comment by glenn-jocher** [comment]
@DoAlone we use two reference iPhone videos for testing, both work correctly for us.

```
python detect.py --source https://github.com/ultralytics/yolov5/releases/download/v1.0/decelera_landscape.mov
python detect.py --source https://github.com/ultralytics/yolov5/releases/download/v1.0/decelera_portrait.mov
```

<img width="1710" alt="Screenshot 2022-08-31 at 17 38 27" src="https://user-images.githubusercontent.com/26833433/187720144-1d3829ed-e6cf-4f51-aeed-489db7846648.png">

**Comment by glenn-jocher** [comment]
@DoAlone if these work correctly for you then please try to provide us a reproducible workflow to create your inverted videos on our side. If we can reproduce we can try to debug.

**Comment by DoAlone** [comment]
I am very glad to receive your reply. Thanks！
I have tried many times and found that the video I shot with the iPhone 12 ProMax in 2021 will be upside down. There is no similar problem in current videos. 
My hardware: The GPU is NVIDIA RTX2060. The CPU is Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz   3.70 GHz. 
My software: Windows 10, CUDA 11.1, Pytorch 1.8.1, Python 3.9.7. I use YOLOv5 version 6.0.  
The video with problems should not be published on social networks, so I take the liberty of sending it to you by email.

**Comment by glenn-jocher** [comment]
@DoAlone I'm able to reproduce this now on iPhone 12 videos (4k 30 FPS) recorded today and airdropped to my Macbook in *.mov format. It seems that cv2.CAP_PROP_ORIENTATION_AUTO is failing to auto detect rotation. 

The only fix I can think of is to set AUTO to False and then manually rotate ourselves after returning the image based on int(self.cap.get(cv2.CAP_PROP_ORIENTATION_META)), which does appear to return the correct rotation.

**Comment by glenn-jocher** [comment]
@DoAlone since this seems like a flaw in the cv2 video capure code I'd comment directly on https://github.com/opencv/opencv/issues/15499

It doesn't make sense for us to patch a solution upstream when cv2 should be doing this correctly themselves.

**Comment by DoAlone** [comment]
> @DoAlone I'm able to reproduce this now on iPhone 12 videos (4k 30 FPS) recorded today and airdropped to my Macbook in *.mov format. It seems that cv2.CAP_PROP_ORIENTATION_AUTO is failing to auto detect rotation.
> 
> The only fix I can think of is to set AUTO to False and then manually rotate ourselves after returning the image based on int(self.cap.get(cv2.CAP_PROP_ORIENTATION_META)), which does appear to return the correct rotation.

Thanks. At your prompt, I tried to modify the version of opencv-python to solve this problem, and found that opencv-python 4.5.1.48 can work normally. 
![image](https://user-images.githubusercontent.com/37893030/188034393-72bab03f-00ae-4660-8650-e5ab37918d60.png)

**Comment by DoAlone** [comment]
> @DoAlone since this seems like a flaw in the cv2 video capure code I'd comment directly on [opencv/opencv#15499](https://github.com/opencv/opencv/issues/15499)
> 
> It doesn't make sense for us to patch a solution upstream when cv2 should be doing this correctly themselves.



> @DoAlone I'm able to reproduce this now on iPhone 12 videos (4k 30 FPS) recorded today and airdropped to my Macbook in *.mov format. It seems that cv2.CAP_PROP_ORIENTATION_AUTO is failing to auto detect rotation.
> 
> The only fix I can think of is to set AUTO to False and then manually rotate ourselves after returning the image based on int(self.cap.get(cv2.CAP_PROP_ORIENTATION_META)), which does appear to return the correct rotation.

![image](https://user-images.githubusercontent.com/37893030/188034469-0dc65173-8008-4515-affa-0baa1190e5ca.png)


> @DoAlone I'm able to reproduce this now on iPhone 12 videos (4k 30 FPS) recorded today and airdropped to my Macbook in *.mov format. It seems that cv2.CAP_PROP_ORIENTATION_AUTO is failing to auto detect rotation.
> 
> The only fix I can think of is to set AUTO to False and then manually rotate ourselves after returning the image based on int(self.cap.get(cv2.CAP_PROP_ORIENTATION_META)), which does appear to return the correct rotation.

Thanks. At your prompt, I tried to modify the version of opencv-python to solve this problem, and found that opencv-python 4.5.1.48 can work normally.
![4ed5396a77ecb63422ebe88bf3e4634](https://user-images.githubusercontent.com/37893030/188034588-87ac8416-9207-4bdf-92d0-1693fafcb624.jpg)

**Comment by DoAlone** [comment]
@glenn-jocher Thanks. At your prompt, I tried to modify the version of opencv-python to solve this problem, and found that opencv-python 4.5.1.48 can work normally. 
![4ed5396a77ecb63422ebe88bf3e4634](https://user-images.githubusercontent.com/37893030/188034668-c578acf9-1b89-411d-81c1-d56a306bd5a2.jpg)

**Comment by glenn-jocher** [comment]
@DoAlone got it. Since it seems like a cv2 bug it's probably worth raising issue on the cv2 repo.

**Comment by jeff-j-chen** [comment]
I can confirm it's an issue with OpenCV, but has already been solved on their end.
Output is flipped with `opencv-python-4.6.0.66` but fine with `opencv-python-4.7.0.68`.

**Comment by glenn-jocher** [comment]
Thanks for confirming, @4a454646. It's great to hear that the issue has been resolved in the newer version of OpenCV. This information will be helpful for others experiencing similar problems. If you need further assistance, feel free to reach out.
