### ISSUE TITLE
How to run YOLOv5 in real time with an infrared camera

### ISSUE THREAD

**Issue by Jongjae-Lee** [ultralytics/yolov5#8495]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I'm trying to run YOLOv5 in real time with an infrared camera(16-bit grayscale camera). 

When I type "python detect.py --source 0", it makes " MFVideoFormat_RGB32(codec not found) ", " AttributeError: 'NoneType' object has no attribute 'shape' "  error.

![KakaoTalk_20220706_232139011](https://user-images.githubusercontent.com/98441645/177573995-7230cb98-8749-4b12-98b9-5150388ce406.jpg)

If I run with a normal webcam, it works well. What is the problem?

**Comment by Jongjae-Lee** [comment]
It works with an infrared images like this

![capture 31](https://user-images.githubusercontent.com/98441645/177580196-1a544f1e-f9c9-4bc9-9d8e-4cca085bfd4b.png)

but it doesn't work in real-time

**Comment by bit-scientist** [comment]
@Jongjae-Lee , does your IR camera provide a 4-channel stream? In that case you may need to split RGB and IR into two, and only provide RGB to `cv2.VideoCapture` method in `line 324` of detect.py.

**Comment by glenn-jocher** [comment]
@Jongjae-Lee n-channel training and deployment are not officially supported yet, but you could make modifications yourself throughout the dataloaders to support this.

**Comment by Jongjae-Lee** [comment]
@glenn-jocher  Is there no official support for 1-channel training and deployment?

**Comment by Jongjae-Lee** [comment]
@bit-scientist Thank you for the comment. Unfortunately, my camera only provides 1-channel stream. OTL

**Comment by glenn-jocher** [comment]
@Jongjae-Lee yes, 1ch datasets and mixed 1ch/3ch datasets (like COCO) are handled automatically. The dataloaders will upscale 1ch images to 3ch by default.
