### ISSUE TITLE
Yolov5 s and n model Block diagram

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#8499]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello Everyone, I hope you are doing well. 
I want to download the yolov5 n and s model block diagram 
Please share if anyone has

**Comment by glenn-jocher** [comment]
@hammadyounas2008 👋 Hello! Thanks for asking about YOLOv5 🚀 **architecture visualization**. We've made visualizing YOLOv5 🚀 architectures super easy. There are 3 main ways:

## `model.yaml`

Each model has a corresponding yaml file that displays the model architecture. Here is YOLOv5s, defined by `yolov5s.yaml`:
https://github.com/ultralytics/yolov5/blob/1a3ecb8b386115fd22129eaf0760157b161efac7/models/yolov5s.yaml#L12-L48

## TensorBoard Graph

Simply start training a model, and then view the TensorBoard Graph for an interactive view of the model architecture. This example shows YOLOv5s viewed in our [Notebook](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb) –  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

```python
# Tensorboard
%load_ext tensorboard
%tensorboard --logdir runs/train

# Train YOLOv5s on COCO128 for 3 epochs
python train.py --weights yolov5s.pt --epochs 3
```

<img width="893" alt="Screenshot 2021-04-11 at 01 10 09" src="https://user-images.githubusercontent.com/26833433/114286928-349bd600-9a63-11eb-941f-7139ee6cd602.png">

## Netron viewer

Use [https://netron.app](https://netron.app/) to view exported ONNX models:

```
python export.py --weights yolov5s.pt --include onnx --simplify
```

<img width="890" alt="Screen Shot 2022-04-29 at 11 09 23 AM" src="https://user-images.githubusercontent.com/26833433/165999628-0d6095ce-58dd-49b7-a04e-25d0995e5493.png">


Good luck 🍀 and let us know if you have any other questions!

**Comment by ghost** [comment]
@glenn-jocher  Thanks What is C3 in the first picture and the last white three button

**Comment by glenn-jocher** [comment]
@hammadyounas2008 C3() is a module defined in models/common.py:
https://github.com/ultralytics/yolov5/blob/c215e87393977cc5dd5381a82c63fddb6a8d0428/models/common.py#L147-L159

**Comment by HeitorDC** [comment]
Hi, guys! 
 Mr. @glenn-jocher it'll be awesome if you could explain the steps of the first and the second pictures so that they can be used in works, researches and articles. Thanks!

**Comment by glenn-jocher** [comment]
@HeitorDC for details see https://docs.ultralytics.com/yolov5/tutorials/architecture_description
