### ISSUE TITLE
Counter

### ISSUE THREAD

**Issue by jomdolalas** [ultralytics/yolov5#850]
## ❔Question
Hi! I'm currently doing human detection using my webcam. I noticed there is a person counter in the terminal, was wondering if there is a way to add the same line in my output window? 
Like in the upper left part of the window there is a line saying "People: [# of people webcam is seeing]" 

## Additional context
I'm new to yolo and object detection, I'm sorry.

**Comment by glenn-jocher** [comment]
@jomdolalas you can add any burnin info onto the images you want, that's simply between you and whatever plotting solution you use (i.e. PIL, opencv). Everything you need to do this is in detect.py.
