### ISSUE TITLE
Continuous use of training weights

### ISSUE THREAD

**Issue by hiiksu** [ultralytics/yolov5#8502]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I am a student who is researching with yolov5. You can't detect with the weights that I trained in the local environment without training in the colab environment? I want to detect without training anywhere with my weight I looked it up, but I couldn't check it out, so I'd appreciate it if you could help me

**Comment by glenn-jocher** [comment]
@hiiksu yes you can deploy a YOLOv5 model trained anywhere to any other export destination.

## Formats

YOLOv5 🚀 inference is officially supported in 11 formats:

💡 ProTip: Export to ONNX or OpenVINO for up to 3x CPU speedup. See [CPU Benchmarks](https://github.com/ultralytics/yolov5/pull/6613).
💡 ProTip: Export to TensorRT for up to 5x GPU speedup. See [GPU Benchmarks](https://github.com/ultralytics/yolov5/pull/6963).

Format                      | `export.py --include`         | Model
:---                        | --:                           | :--
[PyTorch](https://pytorch.org/)                     | -                             | `yolov5s.pt`
[TorchScript](https://pytorch.org/docs/stable/jit.html)                 | `torchscript`                 | `yolov5s.torchscript`
[ONNX](https://onnx.ai/)                        | `onnx`                        | `yolov5s.onnx`
[OpenVINO](https://docs.openvino.ai/latest/index.html)                    | `openvino`                    | `yolov5s_openvino_model/`
[TensorRT](https://developer.nvidia.com/tensorrt)                    | `engine`                      | `yolov5s.engine`
[CoreML](https://github.com/apple/coremltools)                      | `coreml`                      | `yolov5s.mlmodel`
[TensorFlow SavedModel](https://www.tensorflow.org/guide/saved_model)       | `saved_model`                 | `yolov5s_saved_model/`
[TensorFlow GraphDef](https://www.tensorflow.org/api_docs/python/tf/Graph)         | `pb`                          | `yolov5s.pb`
[TensorFlow Lite](https://www.tensorflow.org/lite)             | `tflite`                      | `yolov5s.tflite`
[TensorFlow Edge TPU](https://coral.ai/docs/edgetpu/models-intro/)         | `edgetpu`                     | `yolov5s_edgetpu.tflite`
[TensorFlow.js](https://www.tensorflow.org/js)               | `tfjs`                        | `yolov5s_web_model/`


## Benchmarks

Benchmarks below run on a Colab Pro with the YOLOv5 tutorial notebook <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>. To reproduce:
```bash
python utils/benchmarks.py --weights yolov5s.pt --imgsz 640 --device 0
```

### Colab Pro V100 GPU

```
benchmarks: weights=/content/yolov5/yolov5s.pt, imgsz=640, batch_size=1, data=/content/yolov5/data/coco128.yaml, device=0, half=False, test=False
Checking setup...
YOLOv5 🚀 v6.1-135-g7926afc torch 1.10.0+cu111 CUDA:0 (Tesla V100-SXM2-16GB, 16160MiB)
Setup complete ✅ (8 CPUs, 51.0 GB RAM, 46.7/166.8 GB disk)

Benchmarks complete (458.07s)
                   Format  mAP@0.5:0.95  Inference time (ms)
0                 PyTorch        0.4623                10.19
1             TorchScript        0.4623                 6.85
2                    ONNX        0.4623                14.63
3                OpenVINO           NaN                  NaN
4                TensorRT        0.4617                 1.89
5                  CoreML           NaN                  NaN
6   TensorFlow SavedModel        0.4623                21.28
7     TensorFlow GraphDef        0.4623                21.22
8         TensorFlow Lite           NaN                  NaN
9     TensorFlow Edge TPU           NaN                  NaN
10          TensorFlow.js           NaN                  NaN
```

### Colab Pro CPU

```
benchmarks: weights=/content/yolov5/yolov5s.pt, imgsz=640, batch_size=1, data=/content/yolov5/data/coco128.yaml, device=cpu, half=False, test=False
Checking setup...
YOLOv5 🚀 v6.1-135-g7926afc torch 1.10.0+cu111 CPU
Setup complete ✅ (8 CPUs, 51.0 GB RAM, 41.5/166.8 GB disk)

Benchmarks complete (241.20s)
                   Format  mAP@0.5:0.95  Inference time (ms)
0                 PyTorch        0.4623               127.61
1             TorchScript        0.4623               131.23
2                    ONNX        0.4623                69.34
3                OpenVINO        0.4623                66.52
4                TensorRT           NaN                  NaN
5                  CoreML           NaN                  NaN
6   TensorFlow SavedModel        0.4623               123.79
7     TensorFlow GraphDef        0.4623               121.57
8         TensorFlow Lite        0.4623               316.61
9     TensorFlow Edge TPU           NaN                  NaN
10          TensorFlow.js           NaN                  NaN
```

Good luck 🍀 and let us know if you have any other questions!

**Comment by hiiksu** [comment]
![image](https://user-images.githubusercontent.com/85096196/177821960-c8191f8a-664a-4b44-a6fe-ec6106439f0e.png)

First of all, thank you for your answer. I tried it as informed by colab, but the modulenot found error came out of the line, so I put it in one by one, but there was no end. I think it will be difficult to put in all the YOLOv5 files I have. Is there a solution?

**Comment by glenn-jocher** [comment]
@hiiksu you are showing incorrect usage. See YOLOv5 notebook for correct detect.py usage:
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

<img width="955" alt="Screenshot 2022-07-07 at 18 29 43" src="https://user-images.githubusercontent.com/26833433/177824222-5cfa0fd0-dbf8-498b-8cbc-df9e79799032.png">

**Comment by hiiksu** [comment]
@glenn-jocher  If you do as you say, I will detect the pre-trained model, and I want to detect the weights I trained(defect detect). And I modified detect.py a little bit. I want to detect to detect.py that I modified with the weights I trained, how can I do it? You must be frustrated because I'm not good enough, but help me. I'm working on a really important project.

**Comment by glenn-jocher** [comment]
@hiiksu just follow Colab Detect example and everything will work correctly. You substitute your own weights for the official weights, i.e. `python detect.py --weights path/to/best.pt`

**Comment by hiiksu** [comment]
@glenn-jocher Thank you. I solved it somehow, So you can't use my webcam in colab yet?

**Comment by glenn-jocher** [comment]
@hiiksu no, unfortunately it's complicated to use a local webcam with Colab so we don't support it automatically yet.
