### ISSUE TITLE
export .pt model to .pb using tensorflow v1.15

### ISSUE THREAD

**Issue by git-hamza** [ultralytics/yolov5#8505]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am trying to infer the model with tensorflow v1.15. When I export the model with tf2 and try to infer it in tf1.15, it gives me error of " Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.".
I tried to export the model with tf1.15 but I think it doesn't export due toa missing activation function i.e. silu.
https://github.com/ultralytics/yolov5/blob/1ab23fc67f52d44d5f8ce67a895e73c7cbd7aec5/models/tf.py#L514

**Comment by glenn-jocher** [comment]
@git-hamza I'd recommend using the same TF version for export and inference.

**Comment by git-hamza** [comment]
@glenn-jocher I tried exporting with TF v1.15, It failed to export the model in TFv1.15. It give error on this line https://github.com/ultralytics/yolov5/blob/39d7a93619083cb8e37f5ef7708cf50b34e20ee1/models/tf.py#L515.
May be tf1.15 doesnt have that activation function. Can you please look into this and try the exporting and inference on tf1.15

**Comment by glenn-jocher** [comment]
@git-hamza export requirements are listed in requirements.txt, i.e. 
https://github.com/ultralytics/yolov5/blob/39d7a93619083cb8e37f5ef7708cf50b34e20ee1/requirements.txt#L30
