### ISSUE TITLE
Unable to resume training when using DDP

### ISSUE THREAD

**Issue by bsugerman** [ultralytics/yolov5#851]
I'm running training on 2 GPUs without any problems as follows:

     python -m torch.distributed.launch --nproc_per_node 2 --master_port 1111  train.py --cfg yolov5s.yaml --weights '' --epochs 3 --batch-size 12 --workers 64 --device 0,1 --data data/coco128.yaml

However, if I have to kill the job (so someone else can use the processors for a bit), I can not restart the training. I've tried

    python -m torch.distributed.launch --nproc_per_node 2 --master_port 1111  train.py --cfg yolov5s.yaml --weights '' --epochs 3 --batch-size 12 --workers 64 --device 0,1 --data data/coco128.yaml --resume 

and a number of variants by leaving out different arguments related to multi-processors. The training gets to:

```
Transferred 370/370 items from ./runs/exp1/weights/last.pt
Using DDP
```
sits for a few seconds, then issues the second
```
Using DDP
```
and then just hangs. On the GPU, 3 processors are started. Two on processor 0, each using 2250Mb, and one on processor 1 using 965Mb. 

Any ideas?

**Comment by bsugerman** [comment]
I should note that resumption works fine when just using 1 gpu.

**Comment by glenn-jocher** [comment]
@bsugerman I have not tested --resume on multi-gpu, but a problem above I see is that --resume is incapable of modifying original arguments. The only supported use cases are 
`python train.py --resume` or 
`python train.py --resume path/to/last.pt`

You might want to try this with your DDP command.

**Comment by ljmiao** [comment]
I also meet the problem when I try to resume training with ddp, can you fix the bug? @glenn-jocher

**Comment by bsugerman** [comment]
I have tried these, and it doesn't work. I have isolated the problem to the line in `train.py` that converts the model to DDP:

        # DDP mode
        if cuda and rank != -1:
             model = DDP(model, device_ids=[opt.local_rank], output_device=opt.local_rank)

This is where the program seems to hang, for me at least. 

> 
> 
> @bsugerman I have not tested --resume on multi-gpu, but a problem above I see is that --resume is incapable of modifying original arguments. The only supported use cases are
> `python train.py --resume` or
> `python train.py --resume path/to/last.pt`
> 
> You might want to try this with your DDP command.

**Comment by tyomj** [comment]
A simple workaround, for now, is to comment the lines with opt replacement in train.py:
https://github.com/ultralytics/yolov5/blob/master/train.py#L422-L423
 because every time you read this config you get local_rank = 0.
Then run training as follows:
`
python -m torch.distributed.launch --nproc_per_node 8 train.py  --%your opt params% --resume
`

**Comment by chongkuiqi** [comment]
> A simple workaround, for now, is to comment the lines with opt replacement in train.py:
> https://github.com/ultralytics/yolov5/blob/master/train.py#L422-L423
> because every time you read this config you get local_rank = 0.
> Then run training as follows:
> `python -m torch.distributed.launch --nproc_per_node 8 train.py --%your opt params% --resume`

Thanks! But sorry i'm a little confused about your method to solve the problem, which line should i comment ? And how to configure "--%your opt params%" ? Thank you!

**Comment by tyomj** [comment]
@chongkuiqi 
Sorry, I should have provided the link to a specific version since the line positions are unstable.
Here are the lines to comment: https://github.com/ultralytics/yolov5/blob/685d601308da887e246f95aae9d0847172a56a74/train.py#L475-L476

**Comment by tyomj** [comment]
@ how to configure "--%your opt params%" 
Since you will no longer override these params with the cached opt.yaml, just make sure you are using the same params manually.

**Comment by chongkuiqi** [comment]
> @ how to configure "--%your opt params%"
> Since you will no longer override these params with the cached opt.yaml, just make sure you are using the same params manually.

Thank you !  It works !  And now i understand what caused the problem. Thanks  for your quick reply !

**Comment by glenn-jocher** [comment]
@chongkuiqi @tyomj hi guys, I'm glad to hear there is a workaround. Is this something that might be codeable into a PR to help future people? 

Also might there be a workaround to include opt.yaml? opt.yaml carries all the previous argparser arguments that need to be applied the same way on --resume.

**Comment by glenn-jocher** [comment]
TODO: multi-gpu --resume workaround/fix

**Comment by glenn-jocher** [comment]
@tyomj do you think `local_rank` is the only variable that needs to be preserved here with DDP --resume?

**Comment by glenn-jocher** [comment]
@tyomj what do you think of this proposed solution? This preserves the apriori keys from being replaced in the opt dictionary:
```python
        apriori = opt.global_rank, opt.local_rank
        with open(Path(ckpt).parent.parent / 'opt.yaml') as f:
            opt = argparse.Namespace(**yaml.load(f, Loader=yaml.FullLoader))  # replace
        opt.cfg, opt.weights, opt.resume, opt.global_rank, opt.local_rank = '', ckpt, True, *apriori
```

**Comment by glenn-jocher** [comment]
@tyomj @bsugerman @ljmiao @chongkuiqi I've opened up a PR #1810 with an attempted DDP --resume fix. Please review and test and comment on the PR. I'll be doing internal testing as well.

**Comment by glenn-jocher** [comment]
PR #1810 is merged after successful testing results. Test on 2x T4 GCP VM. Test scenario:
```bash
# 1. Start DDP training
python -m torch.distributed.launch --nproc_per_node 2 train.py --batch-size 80 --data coco128.yaml --epochs 50 --weights yolov5s.pt

# 2. sudo reboot after about 25 epochs

# 3. Resume DDP training
python -m torch.distributed.launch --nproc_per_node 2 train.py --resume
```

Test results as expected, training resumed properly from epoch 25 after forced reboot. nvidia-smi check confirmed multi-GPUs in use. Everything seems to work. Note not tested with W&B enabled.

![results](https://user-images.githubusercontent.com/26833433/103379812-c9258e00-4a9b-11eb-9175-ad9e6d5b697f.png)

## To --resume with DDP (2 GPUs)

ONLY add --resume or --resume path/to/last.pt. --resume accepts no other arguments.
```bash
python -m torch.distributed.launch --nproc_per_node 2 train.py --resume
```
