### ISSUE TITLE
Ignore anomaly

### ISSUE THREAD

**Issue by AchiadChenzi** [ultralytics/yolov5#8512]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

I train Yolov5 in Google Colab and want to ignore anomaly.
For instance, lets assume that anomaly is until 5 frames.
So I need that the result will ignore those 5 frames and label them as the rest of the frames.
for example:
the program labels: 1,1,1,1,1,1,1,2,2,1,1,1,1,1,1,1.
will ignore those '2' label and label them as '1'. 

### Use case

In my validation I've got only 80% and I want that the program will ignore those anomaly.
I cant improve the training because those 2 labels in my train are very close to each other(look almost the same).

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@AchiadChenzi there's no official method to merge classes, but you could restructure your dataset to label those as a single class. 

You can also train and validate in single class mode, which will merge all classes into one class.
https://github.com/ultralytics/yolov5/blob/39d7a93619083cb8e37f5ef7708cf50b34e20ee1/val.py#L341

**Comment by AchiadChenzi** [comment]
Export the labeling, go over the labels and ignore anomalies.
I use high conf rate to get rid most of the wrong labels.

**Comment by glenn-jocher** [comment]
@AchiadChenzi understood! You can export labeled data from YOLOv5 to analyze and manually correct any anomalies. High confidence thresholds can also help filter out erroneous labels. 

Feel free to refer to the Ultralytics Docs for specifics on exporting labels and adjusting confidence thresholds: https://docs.ultralytics.com/yolov5/

Let me know if you need further assistance!
