### ISSUE TITLE
Why does Loss need weights？

### ISSUE THREAD

**Issue by swjtulinxi** [ultralytics/yolov5#8518]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Why does Loss need weights？ Other YOLO code doesn't seem to have been adopted
 
lbox *= self.hyp['box']
        lobj *= self.hyp['obj']
        lcls *= self.hyp['cls']

**Comment by glenn-jocher** [comment]
@swjtulinxi the loss doesn't 'need' anything, but we use these hyperparameter gains to balance loss contributions from each component in proportion to what we believe their importance is to the final solution. 

The values are defined in the hyperparameter yaml here:
https://github.com/ultralytics/yolov5/blob/c215e87393977cc5dd5381a82c63fddb6a8d0428/data/hyps/hyp.scratch-low.yaml#L13-L17
