### ISSUE TITLE
Export .pt to .onnx with half precision failure.

### ISSUE THREAD

**Issue by 1chimaruGin** [ultralytics/yolov5#8519]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Command used to export:
`python export.py --weights yolov5s.pt --include openvino --half`

Error
```
export: data=data/coco128.yaml, weights=['yolov5s.pt'], imgsz=[640, 640], batch_size=1, device=cpu, half=True, inplace=False, train=False, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=12, verbose=False, workspace=4, nms=False, agnostic_nms=False, topk_per_class=100, topk_all=100, iou_thres=0.45, conf_thres=0.25, include=['openvino']
YOLOv5 🚀 v6.1-287-g63ba0cb Python-3.9.12 torch-1.10.0 CPU

Fusing layers... 
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients, 16.5 GFLOPs

PyTorch: starting from yolov5s.pt with output shape (1, 25200, 85) (14.1 MB)

ONNX: starting export with onnx 1.11.0...
ONNX: export failure: "unfolded2d_copy" not implemented for 'Half'

OpenVINO: starting export with openvino 2022.1.0-7019-cdb9bec7210-releases/2022/1...
[ ERROR ]  The "yolov5s.onnx" is not existing file or directory

OpenVINO: export failure: Command '['mo', '--input_model', 'yolov5s.onnx', '--output_dir', 'yolov5s_openvino_model/', '--data_type', 'FP16']' returned non-zero exit status 1.
```

### Environment

```
OS: ubuntu 20.04
Python: 3.9
Pytorch: 1.10
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@1chimaruGin --half exports usually require a GPU, i.e. --half --device 0:
```python
!python export.py --weights yolov5s.pt --include openvino --half --device 0
```
<img width="876" alt="Screen Shot 2022-07-08 at 1 21 46 PM" src="https://user-images.githubusercontent.com/26833433/177982990-5907202a-6dd7-42cd-94ab-8aebc549dab1.png">

But be aware that OpenVINO inference is only supported on CPU currently, and I'm not sure if --half inference will work there. Let me know what happens!

**Comment by glenn-jocher** [comment]
@1chimaruGin I've improved error reporting for this use case in https://github.com/ultralytics/yolov5/pull/8522 so users will now get a message to repeat --half exports on a GPU, i.e. with --device 0
