### ISSUE TITLE
Determining hyperparameters for data augmentation

### ISSUE THREAD

**Issue by klock18** [ultralytics/yolov5#852]
## ❔Question
Hi!

Just wondering if someone could please point me towards code/resources to find out where/how YOLOv5 determines the following parameters for data augmentation:

![image](https://user-images.githubusercontent.com/43727102/91372586-5db28200-e857-11ea-99f8-3b8886fa7211.png)

**Comment by glenn-jocher** [comment]
https://github.com/ultralytics/yolov5/blob/0c01afc390da079047633e142b6718629e0f7ea4/data/hyp.finetune.yaml#L1-L27

**Comment by klock18** [comment]
Thanks for your quick reply, found this which is a great read for anyone going down a similar line of inquiry https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution
