### ISSUE TITLE
Connect YOLOv5 to webcam by url

### ISSUE THREAD

**Issue by Michael-Amar-95** [ultralytics/yolov5#8520]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to connect YOLOv5 to a webcam that I place on field. There is any way to do it? 
I trained a model to detect an object, and now I want to detect the object in real-time by using a camera that I placed on street (for example).

### Additional

By the way, I am using google colab interface.

**Comment by glenn-jocher** [comment]
@MichaelDanAmar yes you can do that. See RTSP, RTMP, HTTP etc example in Colab notebook Detect section:

<img width="1067" alt="Screen Shot 2022-07-08 at 1 03 43 PM" src="https://user-images.githubusercontent.com/26833433/177980385-ada868d5-af8a-4c19-beaa-c2eacd35cd81.png">
