### ISSUE TITLE
Download all pretrained weight files for yolo v5 v6.1

### ISSUE THREAD

**Issue by apiszcz** [ultralytics/yolov5#8521]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Where do I find the weight files to download (ftp) for all models for yolo v5 v6.1?
Is there a recommended approach to download them with hub?
Automated downloading during run is not an option.
Thank you.

**Comment by apiszcz** [comment]
data\download_weights.sh

**Comment by glenn-jocher** [comment]
@apiszcz 👋 Hello! Thanks for asking about **downloading weights**. YOLOv5 🚀 official weights are available to download 3 ways:

## Download Script

Run bash script: `python data\download_weights.sh`

## Release Asssets

Download weights manually from the latest release assets at https://github.com/ultralytics/yolov5/releases
<img width="1047" alt="Screen Shot 2022-07-08 at 12 52 48 PM" src="https://user-images.githubusercontent.com/26833433/177978806-adc3dfd1-5ec2-473c-aaea-bbe29c08841b.png">

## Ultralytics HUB

Download weights in any format from Ultralytics HUB (https://hub.ultralytics.com)
<img width="1277" alt="Screen Shot 2022-07-08 at 12 55 05 PM" src="https://user-images.githubusercontent.com/26833433/177979124-cc4bffc4-6dea-43d2-97b8-5f7742c98eb0.png">

Good luck 🍀 and let us know if you have any other questions!
