### ISSUE TITLE
detect.py, output Coordiantes

### ISSUE THREAD

**Issue by dazzafact** [ultralytics/yolov5#8523]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Does anyone know what these Coordinates exacly are, yolov  are store?

### Additional

3 0.479688 0.782812 0.734375 0.35 0.544758
0 0.230469 0.79375 0.279687 0.315625 0.588195
2 0.5125 0.227344 0.5625 0.442187 0.710074

**Comment by glenn-jocher** [comment]
@biblekiss the `*.txt` file specifications are:

- One row per object
- Each row is `class x_center y_center width height` format.
- Box coordinates must be in **normalized xywh** format (from 0 - 1). If your boxes are in pixels, divide `x_center` and `width` by image width, and `y_center` and `height` by image height.
- Class numbers are zero-indexed (start from 0).

<img width="800" alt="Image Labels" src="https://user-images.githubusercontent.com/26833433/91506361-c7965000-e886-11ea-8291-c72b98c25eec.jpg">

The label file corresponding to the above image contains 2 persons (class `0`) and a tie (class `27`):

<p align="center"><img width="428" src="https://user-images.githubusercontent.com/26833433/112467037-d2568c00-8d66-11eb-8796-55402ac0d62f.png"></p>

Good luck 🍀 and let us know if you have any other questions!

**Comment by dazzafact** [comment]
🤦🏼‍♂️I should have known
Thanks alot.

**Comment by glenn-jocher** [comment]
@dazzafact no worries! Happy to help. If you have any more questions, feel free to ask. Good luck with your project!
