### ISSUE TITLE
How to use transfer learning when changing number of input channels?

### ISSUE THREAD

**Issue by pourmand1376** [ultralytics/yolov5#8524]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I have trained a full YOLOv5 model with grayscale images (1 channel). Now I want to use that model and train another model which gets 5 images in a row (5 channels) and predicts the output. This is easy with yolov5 `ch` parameters. 

However, I want to use the learned features from `1 channel` version. How can I achieve that? (Actually this is related to a previous issue discussed [here](https://github.com/ultralytics/yolov5/issues/8481#issuecomment-1177445774)).

**Comment by glenn-jocher** [comment]
@pourmand1376 transfer learning is easy, you can start from any pretrained model even if it doesn't match the architecture 100%. What you do is define the `--cfg` of the model you want to train and the pretrained `--weights` you want to start from. All layers with matching names and shapes will transfer, the rest will be initialized randomly. You'll see a report in the console telling you how many layers were trasnferred, i.e. 'successfully transferred 190/272 layers`:
```
python train.py --cfg yolov5s.yaml --weights pretrained_model.pt
```

**Comment by pourmand1376** [comment]
That's pretty amazing! I didn't know YOLOv5 does this automatically.

**Comment by wangfurong123** [comment]
@pourmand1376 Hello, how did you implement the training of grayscale images (one channel) based on the yolov5 model? Can you provide code? This question is bothering me, I hope you can answer it, thank you.
