### ISSUE TITLE
Training on multiple datasets with some datasets not fully annotated

### ISSUE THREAD

**Issue by michaelmohamed** [ultralytics/yolov5#8529]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,

If I am training on multiple datasets, 

one containing cars and people fully annotated

the second containing only cars fully annotated (but may have people, but not annotated).

is this ok, or do I need to fully annotate the people in the second dataset?

Thanks!

### Additional

I think [this](https://github.com/ultralytics/yolov5/issues/3096) answers the question but I want to be certain

**Comment by glenn-jocher** [comment]
@mm-fsai for training a single model on multiple datasets see https://community.ultralytics.com/t/how-to-combine-weights-to-detect-from-multiple-datasets

All instances should be labelled in all datasets.
