### ISSUE TITLE
computing precision and recall

### ISSUE THREAD

**Issue by Nocoffeeanymore** [ultralytics/yolov5#853]
## ❔Question
Why does author set a pr_score=0.1 and utilize "np.interp(-pr_score, -conf[i], precision[:, 0])" to compute precision as well as recall?
Could anyone give me some help? Thanks.

**Comment by glenn-jocher** [comment]
@Nocoffeeanymore you can set it to any value you want.

**Comment by Nocoffeeanymore** [comment]
Thank you very much.
` # Sort by objectness`
`  i = np.argsort(-conf)`
`tp, conf, pred_cls = tp[i], conf[i], pred_cls[i]`
` r[ci] = np.interp(-pr_score, -conf[i], recall[:, 0])  # r at pr_score, negative x, xp because xp decreases `
Maybe the second conf[i] is not monotonically decreasing. Then it becomes difficult to understand.

**Comment by glenn-jocher** [comment]
@Nocoffeeanymore conf is already sorted here.

**Comment by diego0718** [comment]
Hi all,

How can i  modify the train script to compute the precision vs recall curve and graph it ?

**Comment by glenn-jocher** [comment]
@diego0718 that's a good question. This should really be a training output. 

All the required plotting code is here, you simply uncomment this to produce a PR curve:
https://github.com/ultralytics/yolov5/blob/9eae82e3a30404e533948675fa3ca09fdd601708/utils/general.py#L295-L304

TODO: autogenerate PR curve on final test.py run.

**Comment by glenn-jocher** [comment]
@diego0718 PR has been submitted for this feature addition, please review and comment at https://github.com/ultralytics/yolov5/pull/1107

**Comment by diego0718** [comment]
> @diego0718 that's a good question. This should really be a training output.
> 
> All the required plotting code is here, you simply uncomment this to produce a PR curve:
> https://github.com/ultralytics/yolov5/blob/9eae82e3a30404e533948675fa3ca09fdd601708/utils/general.py#L295-L304
> 
> TODO: autogenerate PR curve on final test.py run.

Thank u Glen for rapid response. Good work!
