### ISSUE TITLE
Input node with name onnx: not found

### ISSUE THREAD

**Issue by slience-ops** [ultralytics/yolov5#8532]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

OpenCV(4.3.0-dev) Error: Parsing error (Input node with name onnx: not found) in cv::dnn::Subgraph::getInputNodeId, file D:\opencv4.2\opencv-master\modules\dnn\src\graph_simplifier.cpp, line 79

use opencv dnn load model not success!

**Comment by glenn-jocher** [comment]
@slience-ops DNN inference is very simple:

```bash
python export.py --weights yolvo5s.pt --include onnx
python detect.py --weights yolvo5s.onnx --dnn
```

See Export tutorial for details:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️  RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Roboflow for Datasets, Labeling, and Active Learning](https://docs.ultralytics.com/yolov5/tutorials/roboflow_datasets_integration)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TFLite, ONNX, CoreML, TensorRT Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [Architecture Summary](https://docs.ultralytics.com/yolov5/tutorials/architecture_description)&nbsp; ⭐ NEW

Good luck 🍀 and let us know if you have any other questions!

**Comment by Zephyr69** [comment]
Try to change that name to "images" in c++ code, or change the input node name to "onnx" when exporting in here (Some additional name changes are probably needed but I can't remember):
https://github.com/ultralytics/yolov5/blob/526e650553819dbff67897b9c752c4072e989823/export.py#L129

I'm not 100% sure if this is the problem. I encounted a very similar problem in tensorrt deployment and fixed it this way.

**Comment by glenn-jocher** [comment]
@Zephyr69 thanks for sharing your solution! We appreciate your contribution to the YOLOv5 community. 🙌
To address the issue in C++, you can change the input node name to "images" directly in your C++ code. If you encounter any other issues, feel free to reach out for further assistance. Good luck with your project!
