### ISSUE TITLE
In the training process:  why do all class Images shows the number of val Image?

### ISSUE THREAD

**Issue by Sheen23** [ultralytics/yolov5#8536]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When training my dataset, I found that what I trained in the training process was to verify the data in the val. Did I understand it wrong, or was it set incorrectly? I hope someone can help me solve my doubts. 

![image](https://user-images.githubusercontent.com/95073029/178129976-caf38b97-5abb-4cf5-a36e-dabb56e0970e.png)
![image](https://user-images.githubusercontent.com/95073029/178130077-787edb31-a22d-4ba4-9d44-a119fc8d5e7d.png)

**Comment by glenn-jocher** [comment]
@Sheen23 training is done on train set, validation on val set. Metrics are on val set.

**Comment by Sheen23** [comment]
> @Sheen23 training is done on train set, validation on val set. Metrics are on val set.
it is honored  to receive your reply,i think i know what is it.

**Comment by Sheen23** [comment]
> @Sheen23 training is done on train set, validation on val set. Metrics are on val set.

it is honored  to reveive your reply, i think i know how is it.
