### ISSUE TITLE
Differences between export image size and training image size

### ISSUE THREAD

**Issue by poo-pee-poo** [ultralytics/yolov5#8537]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

## Training
I have some images that are 1920x1080 in size. I understand that YoloV5 gives the ability to input rectangular images, like this:
```
python train.py --img 1920 --rect
```

If my understanding is correct this specifies that the longest side of a training image will be 1920 pixels, and the other side will be calculated for automatically.

**However, is it correct to assume that YoloV5 will still pad this image with black pixels into a square shape before feeding into the neural net during training? (A step which I believe is called `letterboxing`)**

And if my understanding is correct, this means that if you **do not** specify `--img 1920 --rect` to `train.py`, then that means YoloV5 will just **stretch** input training images into say a size of 640x640 before feeding into the neural net?

Also, how does specifying `--img 1920 --rect` affect the input size of the resulting model? Does specifying those flags change the input size of the neural network from 640x640 into a 1920x1920 square? (i.e. change the shape of the model) Because if I understand correctly, the core YoloV5 model doesn't accept a rectangular image size, right?

## Export

I also see that YoloV5 gives the option to specify **both** the height and the width of the model during export, like so:
```
python export.py --imgsz [1080,1920]
```
I believe this is what `iDetection` does (with 192 width 320 height).

What does exporting a model specifying an explicit height and width really do? Like how does it take a model that was trained on square images (say 640x640), with an input shape of 640x640, and turn it into a model that accepts an image with dimensions 192x320?
Does it effectively "prune" the neurons that are unused in this smaller model? If so, how does it find out which ones are unused?

And how is this different from specifying `--img 1920 --rect` during training?

I really apologize if these are dumb questions, I am a machine learning noob. I read through a lot of posts and am trying to get a more clear understanding of YoloV5.

### Additional

I really appreciate any time you spend answering my questions.
Thank you for building this awesome machine learning project, I really love it!

**Comment by glenn-jocher** [comment]
@poo-pee-poo images are never 'stretched', aspect ratio of objects is preserved at all times. --rect means rectangular training, it does not produce square batches.

**Comment by poo-pee-poo** [comment]
@glenn-jocher I see. If I pass in `--img 1920 --rect` to `train.py`, what would the input size of the resulting model be during inference? Would it be 1920x1920?

Also I'm curious as to how `export.py` while specifying `--imgsz` changes the input size of the neural network. Like how does it change a neural network which takes in an input image shape of `w,h` to `w2,h2`, without retraining?

**Comment by glenn-jocher** [comment]
@poo-pee-poo pytorch model are dynamic, they have no set input size, you can run inference on a model at any size irrespective of the size it was trained at. You will get the best results running inference at a similar imgsz during deployment as was used during training.

Most export formats rely on fixed size inference defined by --imgsz

**Comment by ZhouBay-TF** [comment]
> @poo-pee-poopytorch 模型是动态的，它们没有设定的输入大小，您可以在任何大小的模型上运行推理，而不管它被训练的大小。在部署期间以与训练期间使用的相似的 imgsz 运行推理，您将获得最佳结果。
> 
> 大多数导出格式依赖于 --imgsz 定义的固定大小推断

How to set 3840*2160, or scale the size according to this scale？Thank you。

**Comment by poo-pee-poo** [comment]
@glenn-jocher I see, this clears everything up! Thank you so much for your ongoing support!

**Comment by poo-pee-poo** [comment]
@xinkangzhou  I would first try to add `--img 3840 --rect` to `train.py`, and see how that works out. I believe the `2160` side is calculated for automatically. I hope this helps!

**Comment by ZhouBay-TF** [comment]
Thanks for your help. I think I understand the code. This is not a simple resize

**Comment by bit-scientist** [comment]
@xinkangzhou how was your training results? When I trained with `--rect 3840`, I got zeros all over recall, precison and mAPs. Did you come across this too?
