### ISSUE TITLE
multigpu training becomes slower

### ISSUE THREAD

**Issue by bxhandhxb** [ultralytics/yolov5#854]
## ❔Question
Hi  
when I train my model with multiple gpu, its training speed is very fast at first but becomes very slow afterwards. And after one day, the training epochs is less than the single gpu.
I watched the nvidia-smi. When the speed is slow,  there exists always one gpu's utilization rate close to 0% and the others are close to 100%.  I also watched 'docker stats containerid'. Its cpu is ~4200%  during fast training and ~2800% during slow training.
My command is similar to this.

> python -m torch.distributed.launch --nproc_per_node 4 train.py --img-size 1920 --batch-size 32 --data ./data/mydata.yaml --cfg ./models/yolov5s.yaml --weights '' --device 0,4,5,7

My dataset are big pictures. Their sizes are  1600* 1200,  1920* 1080, 2700*2000. I set the --img-size to 1920 for small object. 
## Additional context
Something like this
<img width="1291" alt="截屏2020-08-24 下午1 57 09" src="https://user-images.githubusercontent.com/26036453/91390731-0cf95400-e86c-11ea-8eeb-19ad919ed7ae.png">
<img width="1291" alt="截屏2020-08-24 下午1 39 49" src="https://user-images.githubusercontent.com/26036453/91390791-108cdb00-e86c-11ea-80dc-69cfbf4d5157.png">

when i use single gpu to train, it takes about 3 hours for one epoch.

what should I do to find the answer?   I train my model in docker and have set --ipc=host.

**Comment by NanoCode012** [comment]
Hi @bxhandhxb , would it be possible to see the results in Tensorboard and find out when/why that happened (just scroll through each epoch and see diff in relative time)? 

![image](https://user-images.githubusercontent.com/9899957/91410010-72e7da80-e870-11ea-95c9-02f9f945e5d7.png)


I just did a full 2gpu ddp COCO training on 5s and the time taken was constant throughout. (Although I had some bottleneck due to running multiple trainings at once)

Could there be another process running that is using the same GPU?

**Comment by bxhandhxb** [comment]
@NanoCode012  thanks. I'll try the tensorboard
I notice that the speed also can be slow to fast.  So whether this is related to my images order ?  
<img width="1310" alt="截屏2020-08-27 下午4 03 48" src="https://user-images.githubusercontent.com/26036453/91414580-5a32f100-e87f-11ea-8d5c-faaa4af46fee.png">

**Comment by bxhandhxb** [comment]
I'm sure there is no other process using the same gpu

**Comment by bxhandhxb** [comment]
@NanoCode012  I find the data processing time varies enormously. I print time in the __getitem__ of LoadImageandLabels, and  the time can be 0.3s~20s for the same img size. I set the scale in random_perspective to 1. So I think the whole calculation is similar.

**Comment by NanoCode012** [comment]
Could you try to train with COCO 2017? If the issue doesn’t exist in COCO, then we can close in the problem.

**Comment by bxhandhxb** [comment]
ok   thanks

**Comment by glenn-jocher** [comment]
@NanoCode012 @bxhandhxb loading of images in the dataloader can often be a speed bottleneck. You can cache images during training if you have sufficient system RAM to support this using `python train.py --cache`

You can also store your images in uncompressed formats such as bmp, which will take up more storage space, but will also result in faster cv2 loading times.

**Comment by NanoCode012** [comment]
Good to know! But I was confused why @bxhandhxb only had this issue with multi-gpu and only after a certain number of epochs? That was the confusing part.

**Comment by bxhandhxb** [comment]
@NanoCode012  @glenn-jocher   thanks for your time. I close the issue because I find maybe my container or server has some problems. 

> import time
import numpy as np
if \_\_name__ == '\_\_main\_\_':
&emsp;    ss = [2700]
&emsp;     for i in range(100):
&emsp; &emsp;         for s in ss:
&emsp;   &emsp; &emsp;           t1 = time.time()
&emsp;  &emsp; &emsp;            img4 = np.full((s * 2, s * 2, 3), 114, dtype=np.uint8)
&emsp; &emsp; &emsp;             del img4
&emsp; &emsp; &emsp;             print(time.time()-t1)

when I run the above code in my container, the time is weird. 😠 Maybe something wrong with my docker configuration.  

![image](https://user-images.githubusercontent.com/26036453/91625009-76957180-e9d6-11ea-9723-03017f63b481.png)

I will check the problem. 

Thanks again. 👍

**Comment by glenn-jocher** [comment]
@NanoCode012 maybe there's 3rd party resource usage on the machine at random times?

I saw a random set of devices (0, 4, 5, 7) requested, so perhaps the remaining are free or in use at alternate times.

**Comment by bxhandhxb** [comment]
@NanoCode012  @glenn-jocher  
I think it's because of the THP mode for numpy. when I use echo "never > /sys/kernel/mm/transparent_hugepage/enabled" to disable THP, the code is ok!!
you can refer to more details in https://github.com/numpy/numpy/issues/17206

**Comment by glenn-jocher** [comment]
@bxhandhxb ah interesting! Did you try upgrading to numpy 1.19 also to fix the problem as they suggested?

Perhaps requirements.txt should be updated?
https://github.com/ultralytics/yolov5/blob/d3f9bf2bb7932bcd696d3e062031c20ec0adda6c/requirements.txt#L6

**Comment by bxhandhxb** [comment]
@glenn-jocher  No, I haven't,  because my server is offline.  I need to download and upload the docker image to the server. I will see the answer in several hours. when the docker is ok, I'll check it.

**Comment by glenn-jocher** [comment]
Ok. Colab is on 1.18.5, just checked, but if 1.19 fixes the bug then we should update requirements.

**Comment by bxhandhxb** [comment]
maybe the speed problem only happens for big memory usage.  when no big memory usage and disable THP, the np.full speed is slower. Anyway, I'll disable it for my training.

**Comment by bxhandhxb** [comment]
here is my memory usage.
<img width="864" alt="截屏2020-09-02 上午10 33 09" src="https://user-images.githubusercontent.com/26036453/91926083-09048080-ed09-11ea-88b4-06a67b2e9341.png">

**Comment by bxhandhxb** [comment]
@glenn-jocher  numpy1.19.0 also need to set NUMPY_MADVISE_HUGEPAGE. If not, it's also very slow in my environment while I'm training single-gpu yolov5 in another 3 containers.
<img width="925" alt="截屏2020-09-02 下午2 27 40" src="https://user-images.githubusercontent.com/26036453/91940529-2dbd2000-ed2a-11ea-9017-ad63f21025e6.png">
<img width="929" alt="截屏2020-09-02 下午2 27 57" src="https://user-images.githubusercontent.com/26036453/91940535-2eee4d00-ed2a-11ea-8e63-226f3e8a9097.png">

meanwhile,  I'm not sure if this problem can be reproductive in other machine cause @NanoCode012 never met the problem. 
So I don't think it's time to update requirement.txt.

**Comment by NanoCode012** [comment]
@bxhandhxb , I ran your code on np.full above.

I didn’t get any abnormal results. They were all around 0.035 .

I ran on a notebook inside my yolov5 JupyterLab docker. https://github.com/NanoCode012/yolov5-jupyterlab

**Comment by bxhandhxb** [comment]
@NanoCode012  yes, when my server isn't running some computation tasks, the results is normal too. But if I train models in other containers at the same time, the results is like the above.

**Comment by Borda** [comment]
I was training on costume dataset of couple thousands images and the training with `--device 0` and `--device 0,1` was almost the same, no speedup and checking resources both RTX 2080Ti was fully used, any suggestion?
Also it seems that two gpus does not allow increase the batch size (I would expect double)

**Comment by bxhandhxb** [comment]
@Borda  you can double the batch size by ''--batch-size ''

**Comment by NanoCode012** [comment]
Hi @Borda , for multi gpu training, we have to use `torch.distributed.launch`. Right now, `multiprocessing.spawn` has not been implemented. You are actually using DataParallel when you pass `--device 0,1` which weirdly gives the same speed as single GPU (from my tests).

See multi-gpu for more details: https://docs.ultralytics.com/yolov5

Regarding batch size, maybe you can increase it further when you use DDP, but `test.py` only supports Single GPU, so you might not get double the batch-size. Please do tell me how much you increased batch-size by. It's been a while since I've done multi-gpu.

**Comment by alicera** [comment]
$ python -m torch.distributed.launch --nproc_per_node 4 train.py --batch-size 64 --data coco.yaml --cfg yolov5s.yaml --weights ''

I already train it for two day , so cost 1 day every 10 epoch ?
![image](https://user-images.githubusercontent.com/59388989/95704946-135d5700-0c85-11eb-94b0-3b6a659ad387.png)

**Comment by NanoCode012** [comment]
Hi, @alicera , batch size is now Total batch size. You could consider increasing your batch size to a higher number. Right now, the batch size on Each GPU is only 16 per your command, that’s why it’s taking long for you. Maybe increase it to 128 or 256 if memory allows.

**Comment by alicera** [comment]
I increase it to 120, it is the same problem.
It is slow.
