### ISSUE TITLE
Yolov5 training time in a Nvidia gtx 1660 super very slow

### ISSUE THREAD

**Issue by Pedro-Leitek** [ultralytics/yolov5#8547]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,

I would like to know if I'm doing something wrong. I have between 30000 and 40000 images for training and validation. I'm using a batch size of 16, img size of 640 and num workers 1.
Each epoch is taking 3 hours to complete. If I want to train the model for 100 epochs, it would take 300 hours to complete (12,5 days). This is not sustainable. If I increase batch size, it gives me an error saying that it couldn't find a cuddn algorithm AKA Out of memory as I found on other forums. I also want to mention that for the training mentioned above, the GPU takes 5.89 GB of Vram.
But this is not entirely the problem, as other person I know was able to train with the same parameters but with an epoch taking 45-50 minutes for a little bigger dataset. He was using a RTX 2070 super. The difference in terms of hardware is not terribly different, that would make my graphics card processing take 4 times more than the other graphics card. Maybe I'm doing something wrong. Help is appreciated.

Thanks

**Comment by glenn-jocher** [comment]
@Pedro-Leitek 👋 Hello! Thanks for asking about **training speed issues**. YOLOv5 🚀 can be trained on CPU (slowest), [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) (fastest). If you would like to increase your training speed some options are:

- Increase `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s
- Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) DDP at larger `--batch-size`
- Train on cached data: `python train.py --cache` (RAM caching) or `--cache disk` (disk caching)
- Train on faster GPUs, i.e.: P100 -> V100 -> A100
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

Good luck 🍀 and let us know if you have any other questions!

**Comment by barney2074** [comment]
I believe (but I'm no expert) that the GTX 1600 GPUs do not have tensor cores, which are good at matrix calcs needed for ML training.
For a training job of this size, I'd invest in a better GPU, or use one of the cloud services like Colab.
Good news is that the price of GPUs is dropping

**Comment by Pedro-Leitek** [comment]
@barney2074 Thank you very much! According with Nvidia website this series don't have tensor cores as you said. I tried using a RTX 2070 on my workplace and the times for epoch reduced MASSIVELY! From ~3 hours to ~15 minutes.
This was very helpful. Once again, thanks!
