### ISSUE TITLE
Bug in Metrics.py: Division by 0

### ISSUE THREAD

**Issue by UnglvKitDe** [ultralytics/yolov5#8549]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training, Validation

### Bug

@glenn-jocher Maybe similar to #8539, divisions with 0 may occur in methods box_iou(...) and wh_iou(...).
https://github.com/ultralytics/yolov5/blob/a84cd02387d70fb5a6287682a221e8cd46dca87a/utils/metrics.py#L279-L280
https://github.com/ultralytics/yolov5/blob/a84cd02387d70fb5a6287682a221e8cd46dca87a/utils/metrics.py#L310

### Environment

YOLOv5 torch 1.11 (cuda 11.3) and 1.12 (cuda 11.6)

### Minimal Reproducible Example

By using torch.zeros(...) for both arguments (extreme case)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@UnglvKitDe good news 😃! Your original issue may now be fixed ✅ in PR #8550. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by UnglvKitDe** [comment]
@glenn-jocher Thank you :)

**Comment by glenn-jocher** [comment]
@UnglvKitDe you're welcome! 😊 I'm glad I could help. If you have any more questions or need further assistance, feel free to reach out. Good luck with your YOLOv5 projects!
