### ISSUE TITLE
img-size in detect.py,what does this parameter affect?

### ISSUE THREAD

**Issue by dapsjj** [ultralytics/yolov5#855]
The parameter `img-size` in detect.py is 640 by default.

When actually predicting, the resolution of my image is 1920X1080. Do I need to change the `img-size`? If I need to modify it, how much should I modify it to, and what does this parameter `img-size` affect?

**Comment by Aktcob** [comment]
U can use the default image size. Usually, the result of  bigger image size is better than small img size.

If there are many small objects in your datasets, u should use bigger image size like 640+. But the inference speed will be slower. U need do trade-off.

**Comment by dapsjj** [comment]
> U can use the default image size. Usually, the result of bigger image size is better than small img size.
> 
> If there are many small objects in your datasets, u should use bigger image size like 640+. But the inference speed will be slower. U need do trade-off.

Thanks!Very helpful.
