### ISSUE TITLE
Model output behaving oddly.

### ISSUE THREAD

**Issue by mburges-cvl** [ultralytics/yolov5#8554]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,

I would like to implement custom post-processing into YoloV5. However, the network output is of a weird shape. According to my understanding, if I have an image of size 960 x 960 x 3 and 80 classes, the network output should be [Batch_size, 56700, 85], and using torchinfo I can confirm that. The issue is, that instead I get three matrixes with sizes: [Batch_size, 3, 120, 120, 85], [Batch_size, 3, 60, 60, 85], [Batch_size, 3, 30, 30, 85], which reshaped would be [Batch_size, 56700, 85]. 

Am I correct in the assumption, that I can just reshape these individual outputs to shape [Batch_size, n, 85] and concatenate them (or use them as individual detections at the three different scale levels)? And if yes, could someone explain to me, where the "3" (in [Batch_size, **_3_**, x, x, 85]) comes from?

Thanks!

Code for reproduction:

```
import numpy as np
import torch
from torchinfo import summary

from hubconf import _create

model = _create(name='yolov5s', pretrained=False, channels=3, classes=80, autoshape=False, verbose=True)

summary(model, input_size=(1, 3, 960, 960))
img = np.random.rand(960, 960, 3)

img = img[np.newaxis, ::].astype(dtype=np.float32)
img = np.ascontiguousarray(img.transpose((0, 3, 1, 2)))  # BHWC to BCHW
img = torch.from_numpy(img).to(0) / 255  # uint8 to fp16/32

results = model(img)

print(results[0].shape)
print(results[1].shape)
print(results[2].shape)
```

**Comment by glenn-jocher** [comment]
@mburges-cvl thanks for the question! For torch inputs the AutoShape module acts as a passthrough, these go straight to the model and the output is returned directly. This mode is suitable for training, validation etc.

If you have a numpy array just pass it directly, none of the preprocessings steps you have are required.

```python
img = np.random.rand(960, 960, 3)
results = model(img)
```

EDIT: I see you passed AutoShape=False. Then you are receiving raw outputs, your result is expected.

**Comment by glenn-jocher** [comment]
👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # yolov5n - yolov5x6 official model
#                                            'custom', 'path/to/best.pt')  # custom model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
results.xyxy[0]  # im predictions (tensor)

results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie

results.pandas().xyxy[0].value_counts('name')  # class counts (pandas)
# person    2
# tie       1
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by mburges-cvl** [comment]
Hello,

> EDIT: I see you passed AutoShape=False. Then you are receiving raw outputs, your result is expected.

Yes, I would like to utilize the raw output of the network for my "new" post-processing!

> Am I correct in the assumption, that I can just reshape these individual outputs to shape [Batch_size, n, 85] and concatenate them (or use them as individual detections at the three different scale levels)?

So my assumption is correct? But why is there a 3 then?

**Comment by glenn-jocher** [comment]
@mburges-cvl YOLOv5 P5 models have 3 output layers at different scales and P6 models have 4 outputs.

We've made visualizing YOLOv5 🚀 architectures super easy. There are 3 main ways:

## `model.yaml`

Each model has a corresponding yaml file that displays the model architecture. Here is YOLOv5s, defined by `yolov5s.yaml`:
https://github.com/ultralytics/yolov5/blob/1a3ecb8b386115fd22129eaf0760157b161efac7/models/yolov5s.yaml#L12-L48

## TensorBoard Graph

Simply start training a model, and then view the TensorBoard Graph for an interactive view of the model architecture. This example shows YOLOv5s viewed in our [Notebook](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb) –  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

```python
# Tensorboard
%load_ext tensorboard
%tensorboard --logdir runs/train

# Train YOLOv5s on COCO128 for 3 epochs
python train.py --weights yolov5s.pt --epochs 3
```

<img width="893" alt="Screenshot 2021-04-11 at 01 10 09" src="https://user-images.githubusercontent.com/26833433/114286928-349bd600-9a63-11eb-941f-7139ee6cd602.png">

## Netron viewer

Use [https://netron.app](https://netron.app/) to view exported ONNX models:

```
python export.py --weights yolov5s.pt --include onnx --simplify
```

<img width="890" alt="Screen Shot 2022-04-29 at 11 09 23 AM" src="https://user-images.githubusercontent.com/26833433/165999628-0d6095ce-58dd-49b7-a04e-25d0995e5493.png">


Good luck 🍀 and let us know if you have any other questions!

**Comment by mburges-cvl** [comment]
Understood, thank you!

**Comment by mburges-cvl** [comment]
Hello, sorry, but I do have another question in this regard. Can you tell me where the final reshape and concat is happening in the code? I can't seem to find it..

I.E. from the 1 x 3 x 80 x 80 x 85 --> Reshape (shape {3}) --> 1 x 19200 x 85 --> Concat --> 1 x 25200 x 85 --> output

Thanks again. 😃

**Comment by glenn-jocher** [comment]
@mburges-cvl see Detect() module:
https://github.com/ultralytics/yolov5/blob/f8722b4429e80f96be04b36e4efd84ce6583bfa1/models/yolo.py#L37-L77
