### ISSUE TITLE
How can I get the true predicted box in compute_loss

### ISSUE THREAD

**Issue by ldt17** [ultralytics/yolov5#8560]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I try to learn the loss calculation method of yolov5. But I can't understand the calculation function of IOU. I try to print out the pbox but I can't understand the variables that should represent the prediction box. How can I get the absolute coordinates of the prediction box
![image](https://user-images.githubusercontent.com/58940649/178542235-5f2ea54e-f3c7-434d-b064-3a933c6236dc.png)

**Comment by ldt17** [comment]
Further, I also want to know what the variables in the function compute_loss mean. Such as pi ps gj gi pxy pwh
![image](https://user-images.githubusercontent.com/58940649/178543144-ad6b3526-eabd-4ee5-bed8-2c3b16be4663.png)

**Comment by glenn-jocher** [comment]
`tbox` is the true box

comments in your screenshot above describe the variables you are asking about, i.e. gj is gridy index

**Comment by ldt17** [comment]
@glenn-jocher 
Thank you for your reply. Maybe I didn't make it clear. I mean, how can I get the absolute coordinates of the prediction box relative to the whole image

**Comment by glenn-jocher** [comment]
@ldt17 oh, the absolute coordinates are not available in the loss function. The true and predicted boxes are computed relative to each cell in grid space, i.e. 0-1, and then you'd need to add the grid index, i.e. grid 10, and then multiply the stride, i.e. 8, 16 or 32.

The absolute values are only output during normal inference.

**Comment by ldt17** [comment]
@glenn-jocher Can I get the absolute coordinates according to the formula by using the variables in the loss function？

**Comment by glenn-jocher** [comment]
@ldt17 yeah I think it should be possible.

**Comment by ldt17** [comment]
@glenn-jocher I wrote the code according to my own understanding. Is this correct？

abbox represents the normalized value of absolute coordinates.

![image](https://user-images.githubusercontent.com/58940649/178708121-00a3ef29-7f38-4116-8289-961adb106f7a.png)

![image](https://user-images.githubusercontent.com/58940649/178708435-8c5e9b32-190a-49bf-9060-ea4e3af9cc60.png)

**Comment by glenn-jocher** [comment]
@ldt17 yeah, your understanding looks correct to me. Great work!
