### ISSUE TITLE
Is there any YOLOv5 GUI (pyqt preffered) for detecting from IP Cameras?

### ISSUE THREAD

**Issue by blackShine-2** [ultralytics/yolov5#8563]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to use GUI for yolov5 using IP Cameras. I searched for the GUIs using pyqt. Found some. However, I am having some issues. Is there anyu GUI which works fine for IP Cameras?

**Comment by Ashlesha1995** [comment]
Hi @blackShine-2 , please look into this link
https://community.ultralytics.com/t/yolov5-backed-web-gui/65
