### ISSUE TITLE
I need hierarchical structure.

### ISSUE THREAD

**Issue by sarpx** [ultralytics/yolov5#8566]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to teach many geographical areas and extract the plant structure within this area. For example, there are 3 A trees and 5 B plants in the wet river region.
When there are hundreds of geographical areas and plants... things get difficult. If I can give ground as a parent and get the plant offspring of that ground, it will be great..

**Comment by glenn-jocher** [comment]
@sarpx thanks for reaching out! 😊 YOLOv5 does not currently support hierarchical structure or nested object detection. While this is an interesting suggestion, it's something that would require substantial changes to the architecture and may not align with the real-time nature of YOLO. Feel free to share any other thoughts or questions you may have. You might also be interested in exploring our documentation for more information on using YOLOv5.
