### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by JIRRRR77** [ultralytics/yolov5#8568]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Validation

### Bug

I have met a problem with GPU while run val.py, i did not change any code. Anyone know what is going on here? Thx a lot.
![11](https://user-images.githubusercontent.com/65073931/178781413-cdb3560f-b194-4320-8760-0bc8c9d1b6cb.png)
![12](https://user-images.githubusercontent.com/65073931/178781420-bbf2c6dd-5449-44ce-a463-985e61628b2e.png)

### Environment

Python-3.9.12 torch-1.11.0 CUDA:0 (NVIDIA GeForce GTX 1650, 3912MiB)

### Minimal Reproducible Example

Traceback (most recent call last):
  File "/home/jireh/DCAITI/yolov5/val.py", line 394, in <module>
    main(opt)
  File "/home/jireh/DCAITI/yolov5/val.py", line 367, in main
    run(**vars(opt))
  File "/home/jireh/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/jireh/DCAITI/yolov5/val.py", line 169, in run
    model.warmup(imgsz=(1 if pt else batch_size, 3, imgsz, imgsz))  # warmup
  File "/home/jireh/DCAITI/yolov5/models/common.py", line 515, in warmup
    self.forward(im)  # warmup
  File "/home/jireh/DCAITI/yolov5/models/common.py", line 455, in forward
    y = self.model(im, augment=augment, visualize=visualize)[0]
  File "/home/jireh/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jireh/DCAITI/yolov5/models/yolo.py", line 135, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "/home/jireh/DCAITI/yolov5/models/yolo.py", line 158, in _forward_once
    x = m(x)  # run
  File "/home/jireh/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jireh/DCAITI/yolov5/models/yolo.py", line 68, in forward
    y[..., 2:4] = (y[..., 2:4] * 2) ** 2 * self.anchor_grid[i]  # wh
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@JIRRRR77 val.py works correctly in our tests, we are unable to reproduce any issues:
<img width="745" alt="Screen Shot 2022-07-13 at 9 04 09 PM" src="https://user-images.githubusercontent.com/26833433/178811643-1ffdbbc0-518a-4ece-9681-5fe96266af66.png">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by UnglvKitDe** [comment]
@JIRRRR77 Try to specify a device with `--device`.

**Comment by JIRRRR77** [comment]
> @JIRRRR77 Try to specify a device with `--device`.

Already tried, but it work only on CPU. In GPU it still show the error that i have mentioned.Thx for your answer anyway~

**Comment by UnglvKitDe** [comment]
@JIRRRR77 I remember that I once had this error as well. For me the problem was with a CUDA reinstallation. Try to set up a new Conda env and then try it again.

**Comment by JIRRRR77** [comment]
> @JIRRRR77 I remember that I once had this error as well. For me the problem was with a CUDA reinstallation. Try to set up a new Conda env and then try it again.

okay i will try thank a lot~

**Comment by glenn-jocher** [comment]
@JIRRRR77 also make sure your YOLOv5 is up to date. We had an issue like this several months ago that's since been resolved.

**Comment by Abdulazizbek** [comment]
> > @JIRRRR77 I remember that I once had this error as well. For me the problem was with a CUDA reinstallation. Try to set up a new Conda env and then try it again.
> 
> okay i will try thank a lot~

Good day @JIRRRR77, did you solve the issue. I have also still the same problem. 

I'm also working on road defect detection. If you successfully train and get weights, could you share your weights for time saving, please. Thank you beforehand

**Comment by xie-pixel** [comment]
![image](https://user-images.githubusercontent.com/101094151/192425130-4d95513a-5b06-44dc-9076-aaddc39b9bb9.png)

**Comment by xie-pixel** [comment]
@JIRRRR77 ，@Abdulaziz 
Hello, I also encountered this problem when training my own training set. Have you solved it? Can you share the method? I really look forward to your help

**Comment by glenn-jocher** [comment]
@xie-pixel it appears you may have environment problems. I'm able to train correctly with device 0.

Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual [Python 3.9](https://www.python.org/) environment, clone the latest repo ([code changes daily](https://github.com/ultralytics/yolov5/commits/master)), and `pip install` [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) again from scratch.

💡 ProTip! Try one of our verified environments below if you are having trouble with your local environment.


## Requirements

[**Python>=3.7.0**](https://www.python.org/) with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) installed including [**PyTorch>=1.7**](https://pytorch.org/get-started/locally/). To get started:
```bash
git clone https://github.com/ultralytics/yolov5  # clone
cd yolov5
pip install -r requirements.txt  # install
```

[Models](https://github.com/ultralytics/yolov5/tree/master/models) and [datasets](https://github.com/ultralytics/yolov5/tree/master/data) download automatically from the latest YOLOv5 [release](https://github.com/ultralytics/yolov5/releases) when first requested.

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Notebooks** with free GPU: <a href="https://bit.ly/yolov5-paperspace-notebook"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

<a href="https://github.com/ultralytics/yolov5/actions/workflows/ci-testing.yml"><img src="https://github.com/ultralytics/yolov5/actions/workflows/ci-testing.yml/badge.svg" alt="YOLOv5 CI"></a>

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 [training](https://github.com/ultralytics/yolov5/blob/master/train.py), [validation](https://github.com/ultralytics/yolov5/blob/master/val.py), [inference](https://github.com/ultralytics/yolov5/blob/master/detect.py), [export](https://github.com/ultralytics/yolov5/blob/master/export.py) and [benchmarks](https://github.com/ultralytics/yolov5/blob/master/benchmarks.py) on MacOS, Windows, and Ubuntu every 24 hours and on every commit.

**Comment by JNaranjo-Alcazar** [comment]
Hi everybody,
I am trying to convert to TensorRT the small model of yolov5. I am using an Orin Jetson.

These are my steps:
1. I am using a L4T Pytorch container: nvcr.io/nvidia/l4t-pytorch:r34.1.1-pth1.12-py3
2. When I launch: `python3 export.py --weights yolov5s.pt --include onnx engine --img 640 --device 0`

I get:

```
ONNX: starting export with onnx 1.13.0...
ONNX: export failure ❌ 2.5s: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument other in method wrapper__equal)

TensorRT: starting export with TensorRT 8.4.0.11...
TensorRT: export failure ❌ 2.6s: failed to export ONNX file: yolov5s.onnx
``` 
Repo is updated.
GPU is available in the container as I get this message before starting exporting:

`YOLOv5 🚀 v7.0-46-g96a71b1 Python-3.8.10 torch-1.12.0a0+2c916ef.nv22.3 CUDA:0 (Orin, 30623MiB)`

I hope this may help to find the bug

**Comment by glenn-jocher** [comment]
@JNaranjo-Alcazar 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. Your command works correctly in Colab, I'm unable to reproduce any issue:

<img width="1424" alt="Screenshot 2022-12-22 at 12 16 40" src="https://user-images.githubusercontent.com/26833433/209122969-fdbacdbd-ef00-4d2e-962f-a1731e83486a.png">




We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by emmanuelCN** [comment]
> Hi everybody, I am trying to convert to TensorRT the small model of yolov5. I am using an Orin Jetson.
> 
> These are my steps:
> 
> 1. I am using a L4T Pytorch container: nvcr.io/nvidia/l4t-pytorch:r34.1.1-pth1.12-py3
> 2. When I launch: `python3 export.py --weights yolov5s.pt --include onnx engine --img 640 --device 0`
> 
> I get:
> 
> ```
> ONNX: starting export with onnx 1.13.0...
> ONNX: export failure ❌ 2.5s: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument other in method wrapper__equal)
> 
> TensorRT: starting export with TensorRT 8.4.0.11...
> TensorRT: export failure ❌ 2.6s: failed to export ONNX file: yolov5s.onnx
> ```
> 
> Repo is updated. GPU is available in the container as I get this message before starting exporting:
> 
> `YOLOv5 🚀 v7.0-46-g96a71b1 Python-3.8.10 torch-1.12.0a0+2c916ef.nv22.3 CUDA:0 (Orin, 30623MiB)`
> 
> I hope this may help to find the bug

Hi! Were you able to resolve this issue? I had the same problem on Jetson Orin.

**Comment by abdelrahmanseed** [comment]
Same Problem! Have any one found a solution? I am running the command on the Orin Jetson device

**Comment by glenn-jocher** [comment]
@ABDELRAHMAN123491 hi there! To address the issue of varying device locations, ensure that the model and input are consistently placed on the same device using `model.to('cuda')` or `input.to('cuda')` as needed. This should help resolve the error you're encountering. Let me know if you have more questions or need further assistance!

**Comment by chairman-lu** [comment]
I got the same problem in such a simple code:

```
import torch
from models.experimental import attempt_load

device = torch.device('cuda:0')
model = attempt_load('yolov5n.pt', map_location=device)
dummy_input = torch.randn(1, 3, 224, 224).to(device)
input_names = ["input"]
output_names = ["output"]
print(next(model.parameters()).device)
print(dummy_input.device)

torch.onnx.export(model, dummy_input, "yolov5n.onnx", verbose=True, input_names=input_names, output_names=output_names)
```
got the error as follows:
`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper__index_select)`
and the output of the two print function are as follows:
```
cuda:0
cuda:0
```
Then I check the tensor of the yolov5n model in debug:
<img width="298" alt="image" src="https://github.com/ultralytics/yolov5/assets/105423236/4e47f348-4c02-4872-8777-36658e1665c9">
Totally two tensors, class_weights and stride, and both of them are on cuda:0
So have you @JIRRRR77 sovled the problem? I really want to know how to solve it. Thank you

**Comment by xie-pixel** [comment]
I didn't solve the problem either




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ultralytics/yolov5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月22日(星期五) 中午11:46
***@***.***&gt;;
抄送:&nbsp;"谢吉雄 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [ultralytics/yolov5] RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (Issue #8568)





 
I got the same problem in such a simple code:
 import torch from models.experimental import attempt_load device = torch.device('cuda:0') model = attempt_load('yolov5n.pt', map_location=device) dummy_input = torch.randn(1, 3, 224, 224).to(device) input_names = ["input"] output_names = ["output"] print(next(model.parameters()).device) print(dummy_input.device) torch.onnx.export(model, dummy_input, "yolov5n.onnx", verbose=True, input_names=input_names, output_names=output_names)  
got the error as follows:
 RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper__index_select)
 and the output of the two print function are as follows:
 cuda:0 cuda:0  
Then I check the tensor of the yolov5n model in debug:
 image.png (view on web)
 Totally two tensors, class_weights and stride, and both of them are on cuda:0
 So have you @JIRRRR77 sovled the problem? I really want to know how to solve it. Thank you

**Comment by chairman-lu** [comment]
It's ok using cpu to export the yolov5n.pt to yolov5n.onnx, by
`device = torch.device('cpu')`
So the reason must be when using cuda, some tensors are not got to gpu.

**Comment by xie-pixel** [comment]
thankyou




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ultralytics/yolov5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月22日(星期五) 中午12:08
***@***.***&gt;;
抄送:&nbsp;"谢吉雄 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [ultralytics/yolov5] RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (Issue #8568)





 
It's ok using cpu to export the yolov5n.pt to yolov5n.onnx, by
 device = torch.device('cpu')
 So the reason must be when using cuda, some tensors are not got to gpu.

**Comment by chairman-lu** [comment]
you are welcome

**Comment by xie-pixel** [comment]
我已经很久没搞深度学习了换方向了，兄弟还在搞吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ultralytics/yolov5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月22日(星期五) 中午12:11
***@***.***&gt;;
抄送:&nbsp;"谢吉雄 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [ultralytics/yolov5] RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (Issue #8568)





 
you are welcome

**Comment by chairman-lu** [comment]
哈哈哈结果咱还塑料英语聊半天，搞模型轻量化，也不会天天炼丹了

**Comment by glenn-jocher** [comment]
@chairman-lu 哈哈，是的，方向各不同。祝一切顺利！

**Comment by xie-pixel** [comment]
加油吧兄弟，我看好你，未来AI大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ultralytics/yolov5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月22日(星期五) 中午12:52
***@***.***&gt;;
抄送:&nbsp;"谢吉雄 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [ultralytics/yolov5] RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (Issue #8568)





 
哈哈哈结果咱还塑料英语聊半天，搞模型轻量化，也不会天天炼丹了

**Comment by glenn-jocher** [comment]
@xie-pixel 谢谢！不过 YOLO 社区和 Ultralytics 团队才是真正的大佬！祝一切顺利！

**Comment by xie-pixel** [comment]
一切顺利，起床加油干




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ultralytics/yolov5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月22日(星期五) 晚上6:00
***@***.***&gt;;
抄送:&nbsp;"谢吉雄 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [ultralytics/yolov5] RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (Issue #8568)





 
@xie-pixel 谢谢！不过 YOLO 社区和 Ultralytics 团队才是真正的大佬！祝一切顺利！

**Comment by glenn-jocher** [comment]
@xie-pixel i'm glad I could help! 
Remember to refer to the [Ultralytics Docs](https://docs.ultralytics.com/yolov5/) for any further assistance.

**Comment by chairman-lu** [comment]
突然解决了，只需要在转化为onnx前加上两句：
```
for _ in range(1):
    y = model(dummy_input)  # dry runs
```
整体代码如下：
```
import torch
from models.experimental import attempt_load
from torchvision.models import resnet18

device = torch.device('cuda:0')
model = attempt_load('yolov5l.pt', map_location=device).to(device)
# model = resnet18().to(device)
dummy_input = torch.randn(1, 3, 640, 640).to(device)
input_names = ["input"]
output_names = ["output"]
print(next(model.parameters()).device)
print(dummy_input.device)
for _ in range(1):
    y = model(dummy_input)  # dry runs
torch.onnx.export(model, dummy_input, "yolov5l.onnx", verbose=False, input_names=input_names, output_names=output_names)
```
此时可以用gpu完成onnx转化且不报如下错误：
`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!`
至于为什么，有没有大佬解释一下

**Comment by glenn-jocher** [comment]
@chairman-lu 很高兴听到你的问题解决了！🎉

你添加的这两行代码实际上是在进行模型的预热（warm-up）。在某些情况下，模型的权重或者某些操作可能会在第一次前向传播时被初始化或者转移到正确的设备上。通过执行至少一次前向传播，你确保了所有的权重和缓存操作都在预期的设备上（在这个例子中是 GPU），这样在后续的操作中就不会出现设备不匹配的错误了。

这个预热步骤在某些模型转换或者部署场景中是很常见的，尤其是在涉及到设备特定操作（如 CUDA 操作）时。希望这能帮助你更好地理解发生了什么。如果你需要更多帮助，请查阅我们的 [Ultralytics Docs](https://docs.ultralytics.com/yolov5/)。祝你编码愉快！
