### ISSUE TITLE
AssertionError: negative labels:

### ISSUE THREAD

**Issue by shliang0603** [ultralytics/yolov5#857]
@glenn-jocher when I train my custom dataset in yolov5 v3.0, The following error occurred：

![image](https://user-images.githubusercontent.com/37186266/91418024-2dcda380-e884-11ea-81dc-e8e36d9dc816.png)

Can you give me some advice ？

**Comment by Aktcob** [comment]
This repo doesn't support ignore(negative label -1 means ignore) labels right now.

**Comment by shliang0603** [comment]
@Aktcob Thanks for your reply, I don't quite understand what you mean by negative label. I annotate the data set using the Labelimg tool, but the other previously annotated data sets have no problem in training

010854.txt label info:
```python
22 0.4216666666666667 0.33 -0.7366666666666667 0.35333333333333333
22 0.415 0.6283333333333333 -0.6966666666666667 0.33666666666666667
```

And the annotation image 010854.jpg is as follows:
![image](https://user-images.githubusercontent.com/37186266/91423344-01695580-e88b-11ea-8a30-08432bd2f9e3.png)

**Comment by Aktcob** [comment]
Sorry. I made a mistake. 

The reason is -0.7366666666666667<0, the x1y1x2y2 should be in 0~1

**Comment by ChBrockmann** [comment]
@Aktcob You are basically correct, but I just want to tell you, that those are not x1y1x2y2 values. Those are numbers in the normalized xywh format.
Meaning: `x_center y_center width height`
For more Information you should check out: #12

**Comment by Aktcob** [comment]
@ChBrockmann thks

**Comment by Aktcob** [comment]
@ChBrockmann Danke～

**Comment by glenn-jocher** [comment]
@Aktcob I made a new graphic to explain the normalized xywh labels. All classes must be >=0, and all box coordinates must also be 1 >= x >= 0. Does this explain it better?

I'll update the custom training tutorials with this so it's less confusing.

![zidane_anotated](https://user-images.githubusercontent.com/26833433/91500142-ba259980-e877-11ea-8e6f-1b2e99555bc1.jpg)

**Comment by shliang0603** [comment]
@Aktcob @glenn-jocher Thanks for your reply, I've got the problem.

**Comment by sp7414** [comment]
你好，我也遇到了和您一样的问题，同样报错AssertionError: negative labels: data/coco/labels/train2017/000016_4.txt，检查发现确实存在负值，请问您解决了这个问题吗？可以分享一下吗，谢谢
