### ISSUE TITLE
mAP0.75 for custom detector

### ISSUE THREAD

**Issue by wiky231** [ultralytics/yolov5#8570]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have a custom YOLOv5s detector, how do I get the mAP0.75 using val.py on the test dataset? I tried the following which only gave me mAP0.5:
`!python val.py --task test --iou-thres 0.75 --data {dataset.location}/datawithtestset.yaml --weights /content/yolov5/YOLOv5s_Coding/FINAL.pt `

**Comment by glenn-jocher** [comment]
@axlecky the iou vector is here, you could just change the first index to 0.75 which will then update the mAP@0.5 output in the console:
https://github.com/ultralytics/yolov5/blob/f8722b4429e80f96be04b36e4efd84ce6583bfa1/val.py#L160
