### ISSUE TITLE
Use a trained yolov5 model.

### ISSUE THREAD

**Issue by Raymon360** [ultralytics/yolov5#8572]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

is it possible to train a yolov5n model with a trained yolov5m?

**Comment by glenn-jocher** [comment]
@Raymon360 yes you can try, but I doubt if many layers will transfer. You'll see the transfer info printed to the console:
```
python train.py --cfg yolov5n.yaml --weights yolov5m.pt
```
