### ISSUE TITLE
Is there an example of running yolov5s.engine (tensorrt engine) with cpp on jetson nano?

### ISSUE THREAD

**Issue by leeyunhome** [ultralytics/yolov5#8574]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I ran an example of running yolov5s.engine as a parameter in detect.py.

Is there an example of running yolov5s.engine (tensorrt engine) with cpp on jetson nano?

Thank you.

**Comment by glenn-jocher** [comment]
@leeyunhome hi there! Thanks for reaching out. Running YOLOv5's TensorRT engine with C++ on Jetson Nano is a popular request. While we don't have a specific example for this, you may find our Ultralytics Docs helpful in implementing YOLOv5 with TensorRT in a C++ project. If you have any further questions, feel free to ask!
