### ISSUE TITLE
Not predicting bounding boxes after custom training 

### ISSUE THREAD

**Issue by nicholasguimaraes** [ultralytics/yolov5#8579]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I have finetuned the yolov5s model on my dataset of 60 images (40 train, 20 val) and 7 classes.

After training I run the detect.py script for my custom model but the network does not predict any bounding box.

Is my dataset to small?

**Comment by UnglvKitDe** [comment]
@nicholasguimaraes It depends on the task. If there are such or similar objects in the coco dataset, then that might be enough. But if you want to distinguish something completely different e.g. apples and cherries, then that could be too few, yes. But it always depends on the task. Take a look at the wiki, there are recommendations for training with your own dataset.

**Comment by sunaixiadashuaibi** [comment]
data.yaml
class: 
- name1
- name2

**Comment by glenn-jocher** [comment]
@sunaixiadashuaibi your dataset is likely far too small, or you haven't trained enough epochs, i.e. try --epochs 1000 with such a tiny dataset.

**Comment by mx2013713828** [comment]
I think your data yaml is not correct.

**Comment by glenn-jocher** [comment]
@mx2013713828 Your comment is valid. It’s crucial to ensure that the data.yaml file is accurately defined to include the correct class names. Double-check and ensure that the class names are properly listed in the data.yaml file to match your actual class names. You can refer to the documentation for detailed instructions on configuring the data.yaml file at the Ultralytics Docs: https://docs.ultralytics.com/yolov5/
