### ISSUE TITLE
Maybe something wrong with the arg "--save-txt" in test.py?

### ISSUE THREAD

**Issue by intellisense-team** [ultralytics/yolov5#858]
## ❔Question
When I finished the traning, I used the test.py to reproduce the validation results. It seems good as the picture shown. The mAP@0.5 is 67.4.
![image](https://user-images.githubusercontent.com/65592911/91418940-65891b00-e885-11ea-8e17-464c0124d4af.png)

But when I add the arg "--save-txt" in the command, I got the confusing result. The mAPs seems irregular.
![image](https://user-images.githubusercontent.com/65592911/91419068-8ea9ab80-e885-11ea-803f-08ed3432a74d.png)

I have check the test.py but couldn't find the reason.

## Additional context
It seems that the best weight was chosen by the best f1 rather than mAP@0.5.

**Comment by intellisense-team** [comment]
found the bug fix in the lastest version, closed.

**Comment by glenn-jocher** [comment]
@intellisense-team yes, someone else beat you to this bug a few days ago, fixed now :)
