### ISSUE TITLE
How to properly give credit or cite Ultralytics/YOLOv5 in a paper

### ISSUE THREAD

**Issue by MLDavies** [ultralytics/yolov5#8580]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How do I properly give credit to Ultralytics (and others) in a paper for school?

I heavily leveraged the docs and github forum to do a project for school. It won't be published, but will be on my github (a requirement for the class). 

My current rough draft (still writing it):
https://nbviewer.org/github/MLDavies/yolov5_object_detection_russian_vehicles/blob/main/YOLOv5_russian_military_vehicles_writeup.ipynb

My github:
https://github.com/MLDavies/yolov5_object_detection_russian_vehicles

**Comment by glenn-jocher** [comment]
@MLDavies I'm glad you found YOLOv5 useful! See <a href="https://zenodo.org/badge/latestdoi/264818686"><img src="https://zenodo.org/badge/264818686.svg" alt="YOLOv5 Citation"></a> for the latest YOLOv5 release citation information including bibtex etc formats.
