### ISSUE TITLE
About pyotrch version

### ISSUE THREAD

**Issue by WesternTrail** [ultralytics/yolov5#8581]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

There will be errors when the previous version runs. The individual reason is that torch version 1.12.0. I noticed that the torch version is required in the requirement for this update != 1.12.0 to avoid errors during program operation. Actually, I'm running train Py file, the program will automatically check my torch Version (requirements: torch! =1.12.0, >=1.7.0 not found and is required by yolov5, attempting auto update...) And update the torch version. But this update directly installed my torch into the torch1.11.0-CPU version, resulting in a slow training speed. I think you should optimize the code itself rather than limit the torch version, because it will cause a lot of trouble

**Comment by zhiqwang** [comment]
In favor of not ruling out PyTorch 1.12.0, seems that PyTorch 1.12.0 only have problem for cuda10.2 and some other scenarios, but there are also a lot of people don't use cuda10.2 or don't meet this scenarios today.

- https://github.com/ultralytics/yolov5/issues/8395
- https://github.com/ultralytics/yolov5/pull/8497

**Comment by glenn-jocher** [comment]
@WesternTrail the torch 1.12 incompatibilities are mainly observed in DDP trainings, but we have introduced this change in requirements.txt and are waiting for 1.12.1 to come out which should hopefully resolve these issues. 

If you are not using DDP or cuda 10.2 you should be fine to simply comment out this line in requirements.txt

**Comment by glenn-jocher** [comment]
@zhiqwang @WesternTrail alternatively we could also introduce an assert torch!=1.12.0 in DDP training with a message to the user to explain the problem.

**Comment by zhiqwang** [comment]
> alternatively we could also introduce an assert torch!=1.12.0 in DDP training with a message to the user to explain the problem.

@glenn-jocher Agreed on this option!

**Comment by glenn-jocher** [comment]
@zhiqwang good news 😃! Your original issue may now be fixed ✅ in PR #8621. torch==1.12.0 installs are now allowed, and an assert torch!=1.12.0 has been inserted into a new smart_DDP() function. The Docker image is using torch nightly and trains DDP correctly.

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
