### ISSUE TITLE
No metrics output when using --noautoanchor flag

### ISSUE THREAD

**Issue by MannyGozzi** [ultralytics/yolov5#8582]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is there a reason that all metrics output are 0 when using the --noautoanchor flag? Here's an image demonstrating the problem I'm seeing. 
![image](https://user-images.githubusercontent.com/38353934/179158253-63d13916-1144-4151-9a70-2ebff4d21737.png)
The problem goes away when not using the --noautoanchor flag. 
I've hard set the anchors in the yolov5s.yaml file which I'm using to train as the following:
![image](https://user-images.githubusercontent.com/38353934/179158364-43ca5da8-450b-409a-8903-6a85fee9f5bd.png)
Is there any reason for the total elimination of the metrics? Am I using the wrong number of anchors or something?

### Additional

Here's the command I'm using:
```
# Change the contents of the deeosea-yolov5/opt/ml/input/data/hyp.scratch-low.yaml 
# to utilize the best found hyperparameters from the evolutions performed above. 
!export WANDB_RUN_GROUP="hyperparam_const_seed" && python ./deepsea-yolov5/yolov5/train.py \
--img=640 \
--data=./deepsea-yolov5/opt/ml/custom_config.yaml  \
--batch=2 \
--weights=yolov5s.pt \
--cfg=./deepsea-yolov5/yolov5/models/yolov5s.yaml \
--hyp=./deepsea-yolov5/opt/ml/input/data/hyp.scratch-low.yaml \
--project="902005-vaa"\
--cache \
--noautoanchor \
--epochs=50
```

Here's the yolov5s.yaml file: 
```
# YOLOv5 🚀 by Ultralytics, GPL-3.0 license

# Parameters
nc: 80  # number of classes
depth_multiple: 0.33  # model depth multiple
width_multiple: 0.50  # layer channel multiple
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

# YOLOv5 v6.0 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [64, 6, 2, 2]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C3, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 6, C3, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, C3, [512]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 3, C3, [1024]],
   [-1, 1, SPPF, [1024, 5]],  # 9
  ]

# YOLOv5 v6.0 head
head:
  [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, C3, [512, False]],  # 13

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, C3, [256, False]],  # 17 (P3/8-small)

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 14], 1, Concat, [1]],  # cat head P4
   [-1, 3, C3, [512, False]],  # 20 (P4/16-medium)

   [-1, 1, Conv, [512, 3, 2]],
   [[-1, 10], 1, Concat, [1]],  # cat head P5
   [-1, 3, C3, [1024, False]],  # 23 (P5/32-large)

   [[17, 20, 23], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
  ]
```

**Comment by glenn-jocher** [comment]
@MannyGozzi I think you've misunderstood. Metrics are not removed, they are right there, their value is zero.

Also you can see you have zero labels in your validation set, therefore there is nothing to compute metrics on.

**Comment by MannyGozzi** [comment]
I'm not sure if I'm mistaken. When I run without the flag I get metrics as shown below:
![image](https://user-images.githubusercontent.com/38353934/179295280-53a97241-0ff4-458a-98ec-a999ec434419.png)
This is the command I'm using:
```
# Change the contents of the deeosea-yolov5/opt/ml/input/data/hyp.scratch-low.yaml 
# to utilize the best found hyperparameters from the evolutions performed above. 
!export WANDB_RUN_GROUP="hyperparam_const_seed" && python ./deepsea-yolov5/yolov5/train.py \
--img=640 \
--data=./deepsea-yolov5/opt/ml/custom_config.yaml  \
--batch=2 \
--weights=yolov5s.pt \
--cfg=./deepsea-yolov5/yolov5/models/yolov5s.yaml \
--hyp=./deepsea-yolov5/opt/ml/input/data/hyp.scratch-low.yaml \
--project="902005-vaa"\
--cache \
--epochs=50
```
If I add the --noautoanchor flag it just sets the metrics to 0.

**Comment by glenn-jocher** [comment]
@MannyGozzi then your default anchors are not very suitable for your dataset

**Comment by MannyGozzi** [comment]
But I copied them directly from when I ran my code with the --evolve flag. Let me know if you'd like a screenshot. Thanks for your help this far!

**Comment by MannyGozzi** [comment]
> @MannyGozzi then your default anchors are not very suitable for your dataset

These are not default anchors though. I grabbed them from the evolution run which should mean they are optimal.

Since I'm receiving no response, I'll close this issue as unsolved and link to the new more precise issue [https://github.com/ultralytics/yolov5/issues/8625](https://github.com/ultralytics/yolov5/issues/8625) I'm dealing with:
