### ISSUE TITLE
Exclude NMS from custom model

### ISSUE THREAD

**Issue by michelebechini** [ultralytics/yolov5#8583]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi everyone!

I trained a yolov5 model for custom single object detection and for my project I would like to skip the NMS part and make the model to output all the predictions, to subsequently filter them with a custom algorithm that I am developing.

Could you please help me to find where I need to modify the source code to exclude NMS and get all the predictions as output?

Thanks in advance!!!

**Comment by glenn-jocher** [comment]
@michelebechini YOLOv5 models don't include NMS. It's processed separately, i.e. see detect.py:
https://github.com/ultralytics/yolov5/blob/f8722b4429e80f96be04b36e4efd84ce6583bfa1/detect.py#L120-L129

**Comment by michelebechini** [comment]
@glenn-jocher so basically if I comment out line 127 the model will return directly all the predictions, is it correct?

**Comment by glenn-jocher** [comment]
@michelebechini well there's nothing really to comment.

pred on L122 returns what you want I think. You can load one of these base models with PyTorch Hub also by setting `autoshape=False`.
```python
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', autoshape=False)  # or yolov5n - yolov5x6, custom
```
