### ISSUE TITLE
Dependencies 

### ISSUE THREAD

**Issue by DoSquared** [ultralytics/yolov5#8585]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Good morning, 

I have all these dependencies errors while running the code! I hope there is a quick fix 

![image](https://user-images.githubusercontent.com/4492013/179178085-9c8f7334-13ae-4e1a-ad70-58d43c09277c.png)

### Environment

I am running YOLOv5 on Google collab 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@DaliaMahdy hi thanks for submitting a bug report! This seems like a roboflow dependency issue. Please raise this with the roboflow team and they should be able to help you there.
