### ISSUE TITLE
How to find the mAP of a new video during the detection?

### ISSUE THREAD

**Issue by Ala1412** [ultralytics/yolov5#8586]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I am working on a object detection project for some videos. I have already trained a yolov5 model by my custom data. Now, I have a new video for the detection and I want to find out the mAP for the model on the new video. Are yolov5 provide such approach? Or how can I do it. Thanks.

**Comment by glenn-jocher** [comment]
@Ala1412 metrics like mAP can only be computed on labelled data, i.e. if you want mAP on a new video you need to label all the objects and then compare the predictions to your labels. 

val.py does this for labelled validation or test sets.
