### ISSUE TITLE
About Design Pattern

### ISSUE THREAD

**Issue by QuarTerll** [ultralytics/yolov5#8587]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Recently, I am studying **Design Pattern** which can help you to improve code structure.

I am a beginner of the desing pattern. 

Meanwhile, the code of yolov5 is kinda beautiful and elegant.

So, I wander that if there are some patterns designed in these code?

Where and why choose this pattern?

Thanks~

**Comment by glenn-jocher** [comment]
@QuarTerll thanks for the feedback! I don't have any official coding education, I just try to keep it as simple and concise as possible. 

I think the best PR's and updates to the code are actually eliminations and reductions to the codebase, not additions.
