### ISSUE TITLE
Save Crop Images Into Custom Folder

### ISSUE THREAD

**Issue by Gozgur** [ultralytics/yolov5#8588]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am using yolov5 without cloning. There is a solution when cloning but I could not figure out how can I save my results (results.crop()) into folder that I choose. 

### Additional

how to specify result images folder path without cloning yolov5 repo

**Comment by glenn-jocher** [comment]
@Gozgur this is pretty simple:
https://github.com/ultralytics/yolov5/blob/f8722b4429e80f96be04b36e4efd84ce6583bfa1/models/common.py#L703-L706
```python
results.crop(save_dir='path/to/dir')
```
