### ISSUE TITLE
Should use Imagenet data for pretrain?

### ISSUE THREAD

**Issue by gzroy** [ultralytics/yolov5#859]
## ❔Question
Should use imagenet data fro pretrain

## Additional context
Hi, I want to train yolov5 from scratch for COCO, but not sure if I need to use the yolov5 backbone to train the imagenet first, and then base on it to train on COCO?
If I need to pretrain first on imagenet, how to modify the backbone, add a full connect dense layer or add a convolution layer to transfer the backbone output to 1000 dimension size vector?
Thanks

**Comment by glenn-jocher** [comment]
@gzroy that's a good question. We train COCO from scratch:
`python train.py --weights '' --cfg yolov5s.yaml`

but other architectures tend to train from some pretrained weights. For smaller custom datasets I always recommend starting from COCO pretrained weights:
`python train.py --weights yolov5s.pt  # no --cfg needed`

For larger datasets you could try it both ways and see what works better for you. Note that each uses a different hyperparameters file in yolov5/data.

**Comment by gzroy** [comment]
@glenn-jocher  Thanks your reply, and awesome work!

**Comment by Dongjiuqing** [comment]
Emm..So，Did you clear how to train the Yolov5 on imagenet for a pretraining? For example, I want to train COCO dataset, and using Imagenet as pretrained dataset.

**Comment by zhiqwang** [comment]
Hi @Dongjiuqing , I guess you can refer to this ticket #2001 .

**Comment by Dongjiuqing** [comment]
> Hi @Dongjiuqing , I guess you can refer to this ticket #2001 .
Thank you for your help.

As you mentioned, I can see the official method. They provide Classify.py. 
And meanwhihe, another researcher said: he set the bbox to the whole image : (class ,0.5 ,0.5 ,1 ,1), then train the dataset.
Actually,  my thinking is same as hims, before you giving me that link. How do you think that method, is it working?
You can type the Chinese characters if convenient.

Happy Chinese New Year.

**Comment by zhiqwang** [comment]
Hi @Dongjiuqing , Happy Chinese New Year!

> You can type the Chinese characters if convenient.

I think this will likely bother others people here, you can concat me via email as an alternative.

**Comment by foemre** [comment]
@zhiqwang @Dongjiuqing 

Would there be any benefit to pre-training the backbone with a large dataset e.g. Objects365, and freezing the backbone and finetuning the head with a custom dataset?

**Comment by zhiqwang** [comment]
This should be determined by the magnitude of your custom data. If your dataset is much smaller than COCO, then pre-training the model from COCO should be sufficient, whereas if your dataset size is between COCO and Object365, then Object365 is a better choice I guess.

**Comment by glenn-jocher** [comment]
@zhiqwang, you've highlighted a crucial consideration. The size and diversity of your custom dataset should guide your pre-training decision. Utilizing COCO pre-training should suffice for smaller datasets, while datasets falling between COCO and Objects365 could benefit from the latter.
