### ISSUE TITLE
Is "Wandb" available for offline...

### ISSUE THREAD

**Issue by PraveenMNaik** [ultralytics/yolov5#8594]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is "wandb" can be installed in offline environment... if so... pls suggest...

**Comment by alicewish** [comment]
I think you can modify the code to use "wandb = None" or uninstall wandb.

**Comment by mx2013713828** [comment]
yes，wandb would create local files when  offline.

**Comment by zgzhengSEU** [comment]
so how to use wandb offine? when i set wandb offline, yolov5 will not use wandb
     Weights & Biases: run 'pip install wandb' to automatically track and visualize YOLOv5  runs in Weights & Biases
but i want to use wandb offline, after i get internet, i want to use wandb online and sync local runs

**Comment by glenn-jocher** [comment]
@zgzhengSEU you can use Wandb in offline mode by setting the environment variable `WANDB_MODE=offline`. When you have internet access, set `WANDB_MODE=online` to sync local runs. You can find more information about Wandb usage in the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/.
