### ISSUE TITLE
Decreasing mAP 

### ISSUE THREAD

**Issue by yasindagasan** [ultralytics/yolov5#86]
Hi,

Map does not start to increase when I am trying to train my custom dataset which is of a single class. 

This happened with the latest repo that I downloaded 2 hours ago. 
Code:
```
python3 train.py \
  --img-size 1280\
  --batch 4 \
  --epochs 2000 \
  --data ./data/custom/horizontal_only_s.yaml \
  --cfg ./models/custom/horizontal_s.yaml \
  --weights weights/yolov5s.pt \
  --name horizontal_s \
  --cache 
```

## Expected behavior
This is the tensorboard output that I have experienced:

![image](https://user-images.githubusercontent.com/20746470/84732251-852ada00-afde-11ea-8c0e-dd920bb3376d.png)

When I am running the training with the very initial release of the repo I have the following tensorboard result:

![image](https://user-images.githubusercontent.com/20746470/84732481-2f0a6680-afdf-11ea-9902-bbaf40444bce.png)

## System
 - OS: [Ubuntu 20.04]
 - GPU [RTX 2070]

**Comment by glenn-jocher** [comment]
@yasindagasan unless you can reproduce this on coco128.yaml, the problem is your custom data.

**Comment by glenn-jocher** [comment]
<img width="1300" alt="Screen Shot 2020-06-15 at 11 12 40 PM" src="https://user-images.githubusercontent.com/26833433/84737963-d777e680-af5d-11ea-97a3-a3845ea9fc6b.png">

**Comment by yasindagasan** [comment]
thanks @glenn-jocher. I got similar results when I ran it on google colab. 

But when I do the training with my computer with the latest version of the repo, I still get the same problem with the coco128 dataset. Now I am running the training with an old version of the repository (downloaded 2 days ago-before the fp16 changes, it works fine). Not sure of the cause. Maybe related to versions of the packages in my computer.

**Comment by glenn-jocher** [comment]
@yasindagasan the notebook is working correctly using the current repo. I just trained the default tutorial to 300 epochs, starting about one hour ago from a new git clone:

```
!python train.py --data coco128.yaml --weights yolov5s.pt --cfg yolov5s.yaml --epochs 300 --img 640 --nosave --device 0
```

<img width="1848" alt="Screen Shot 2020-06-16 at 12 18 24 AM" src="https://user-images.githubusercontent.com/26833433/84743621-0f375c00-af67-11ea-8069-170d6491dad6.png">
