### ISSUE TITLE
Reproducibility in multi-process data loading

### ISSUE THREAD

**Issue by UnglvKitDe** [ultralytics/yolov5#8601]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

[In the official documentation](https://pytorch.org/docs/stable/notes/randomness.html#dataloader) it is recommended to set the rseed for the worker to ensure reproducibility even for multi-process dataloaders.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@UnglvKitDe I'm seeing fully reproducible results now with master and torch>=1.12.0. Is this not the case for you?
<img width="1252" alt="Screen Shot 2022-07-19 at 6 21 53 PM" src="https://user-images.githubusercontent.com/26833433/179815409-e0f1c406-ebf8-46c1-a5a4-fddd45f86810.png">
