### ISSUE TITLE
How to plot classes distribution?

### ISSUE THREAD

**Issue by amieruddin** [ultralytics/yolov5#8611]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, 
I'm training my custom datasets and it has hundred thousand of data. I need to see the class distribution like the image below.
Default yolov5 training don't extract the label.png.

Anyone please help me how to do extract label.png with class name. TQ.

### Additional

ref from : [#22](https://github.com/ultralytics/yolov5/issues/2265)

![image](https://user-images.githubusercontent.com/58421336/179433576-63d4146b-2924-4882-9cce-d07eb4acaf5b.png)

**Comment by glenn-jocher** [comment]
@amieruddin the above chart is part of labels.png which is created automatically in your runs/train/exp directory on train start.
