### ISSUE TITLE
too large different ratio 

### ISSUE THREAD

**Issue by trungpham2606** [ultralytics/yolov5#8613]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hi @glenn-jocher,
I found a problem that when training a custom dataset where the ratio of width and height of the bounding box is too large, the model cant regress the correct bounding box's coordinates.
Do you have any ideas to deal with this situation ?
![image](https://user-images.githubusercontent.com/35657426/179445771-bd37f687-28cb-402c-8377-c562d627594c.png)

**Comment by glenn-jocher** [comment]
@trungpham2606 the current max aspect ratio in box_candidates() is 100:
https://github.com/ultralytics/yolov5/blob/51fb467b63191b5f0ff8391608bb96b5deb8c3ea/utils/augmentations.py#L279-L284

Regardless very long and thin objects may be harder to detect.

**Comment by trungpham2606** [comment]
hi @glenn-jocher 
I did change that ar_thr but seems no luck, the model still cannot detect well.

**Comment by glenn-jocher** [comment]
@trungpham2606 If changing the aspect ratio threshold didn't yield the desired results, you might want to try augmenting the data with various techniques such as random rotations, flipping, or adjusting the aspect ratio to provide the model with a diverse set of examples to learn from. Also, ensure that your training set encompasses a wide range of aspect ratios to help the model generalize better.
