### ISSUE TITLE
Caching is stopped for larger dataset while using --cache flag

### ISSUE THREAD

**Issue by Sanath1998** [ultralytics/yolov5#8614]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,
Is there any way on how to continue on the training with --cache flag which uses RAM to its fullest. For me while I have "--cache ram" for nearly 25 lakh data points it is stopping after some time. Could you please help me in this.

Command:
python train.py --img 256  --batch 128 --epochs 100 --cache ram --workers 3 --device 0

**Comment by glenn-jocher** [comment]
@Sanath1998 your system is out of RAM. You could try --cache disk.

**Comment by Sanath1998** [comment]
Hi @glenn-jocher ,
What is the white box behind caching (--cache ram) flag and its direct purposes related to yolov5 training? Can you please brief it out so that I can use --cache flag effectively in training the custom models.

Command:
python train.py --img 256 --batch 128 --epochs 100 --cache ram --workers 3 --device 0

**Comment by glenn-jocher** [comment]
@Sanath1998 👋 Hello! Thanks for asking about **training speed issues**. YOLOv5 🚀 can be trained on CPU (slowest), [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) (fastest). If you would like to increase your training speed some options are:

- Increase `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s
- Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) DDP at larger `--batch-size`
- Train on cached data: `python train.py --cache` (RAM caching) or `--cache disk` (disk caching)
- Train on faster GPUs, i.e.: P100 -> V100 -> A100
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

Good luck 🍀 and let us know if you have any other questions!

**Comment by Sanath1998** [comment]
Hi @glenn-jocher , 
Thanks for your valuable suggestions but what's the reason behind using 
**Train on cached data: python train.py --cache (RAM caching) or --cache disk (disk caching)** as you have mentioned above? What actually --cache does with respect to datapoints for training?

**Comment by glenn-jocher** [comment]
--cache caches the dataset for faster load times

**Comment by SakshiPradyumnAsurion** [comment]
> --cache caches the dataset for faster load times

@glenn-jocher in the scenario where training is done multiple times and --cache is used as well
Is it possible to use the previously cached images from first run for the second training run directly **instead** of caching the images again? The dataset is significantly large and caching is resource-intensive

**Comment by glenn-jocher** [comment]
@SakshiPradyumnAsurion the --cache flag does not currently support reusing cached data between training runs.
