### ISSUE TITLE
Specify an ID for the same object detected 

### ISSUE THREAD

**Issue by Abderrahmen33** [ultralytics/yolov5#8617]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi all, I was able to detect the custom objects and count them but I need to specify an ID for each one in his bounding box,
I was not able to do that, can anyone know how to do that? could you please help? and thank you

**Comment by glenn-jocher** [comment]
@Abderrahmen33 👋 Hello! Thanks for asking about object **tracking** in computer vision. YOLOv5 🚀 is an object **detector** that detect, localizes and classifies objects in a single image. It does not connect objects across multiple images, for this you need a tracking solution. A few possible tracking solutions are:

- [Extended Kalman Filter (EKF)](https://en.wikipedia.org/wiki/Kalman_filter)
- [Kanade-Lukas-Tomasi (KLT) Feature Tracker](https://en.wikipedia.org/wiki/Kanade%E2%80%93Lucas%E2%80%93Tomasi_feature_tracker): 
- [YOLOv5 DeepSort Tracker](https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch) 
- [Apple iOS VNTrackObjectRequest](https://developer.apple.com/documentation/vision/tracking_multiple_objects_or_rectangles_in_video)

Good luck 🍀 and let us know if you have any other questions!
