### ISSUE TITLE
No labels found in Train.cache - YOLOv5 custom dataset training 

### ISSUE THREAD

**Issue by shamayemkhan** [ultralytics/yolov5#8618]

**Comment by glenn-jocher** [comment]
@shamayemkhan hi there! It seems like the labels might not be present in your training cache. Double-check that your dataset is formatted correctly with corresponding labels. Also, ensure that the paths in your data.yaml file are accurate. For further guidance, you can refer to our documentation at https://docs.ultralytics.com/yolov5/. Keep up the great work!
