### ISSUE TITLE
parsing input for detect.py

### ISSUE THREAD

**Issue by edeyejedi** [ultralytics/yolov5#862]
Im not too python savy, so be kind. 
The general format is to provide detect.py with space separated pairs of arguments  (e.g. !python detect.py --img 640)
Is it possible to parse an opt namespace variable to detect?
Or, alternatively, something like detect(img=604,conf 0.4,weights=......etc etc.)
This may be really obvious but I'm going round in circles. 
Cheers

**Comment by Frank1126lin** [comment]
> Im not too python savy, so be kind.
> The general format is to provide detect.py with space separated pairs of arguments (e.g. !python detect.py --img 640)
> Is it possible to parse an opt namespace variable to detect?
> Or, alternatively, something like detect(img=604,conf 0.4,weights=......etc etc.)
> This may be really obvious but I'm going round in circles.
> Cheers

I believe you can read the source code and rewrite it in your way.

**Comment by edeyejedi** [comment]
Certainly can, been tearing up scripts and def parts for the last 12 hours.
