### ISSUE TITLE
Model Ensembling With PyTorch Hub

### ISSUE THREAD

**Issue by ertugrul-dmr** [ultralytics/yolov5#8622]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I know it's possible to ensemble multiple models with detect.py, but is it possible to do ensemble or do TTA with PyTorch Hub interface?

Let's say:

```python
import torch

# Model
model_a = torch.hub.load('path/to/yolov5', 'custom', path='path/to/model_1.pt', source='local')
model_b = torch.hub.load('path/to/yolov5', 'custom', path='path/to/model_2.pt', source='local')

# Image
im = 'https://ultralytics.com/images/zidane.jpg'

# Inference
results = ???

results.pandas().xyxy[0]
```

How could I get results in a standardized way with this setting?

**Comment by glenn-jocher** [comment]
@ertugrul-dmr YOLOv5 PyTorch Hub models can use TTA with the augment argument:
```python
results = model(im, augment=True)
```

You could customize some sort of Ensemble() using the Ensemble() module on your own, i.e. Ensemble two models and then wrap them in AutoShape:
https://github.com/ultralytics/yolov5/blob/92e47b85d952274480c8c5efa5900e686241a96b/models/experimental.py#L61-L72

**Comment by kaamlaS** [comment]
@ertugrul-dmr 
Hi, did you find a way to ensemble with torch.hub?

**Comment by ertugrul-dmr** [comment]
@kaamlaS yeah, wasn't an optimal solution but I kept results for every single image and then applied Weighted boxes fusion over them.

Ref: [Weighted boxes fusion](https://arxiv.org/abs/1910.13302)

**Comment by kaamlaS** [comment]
okay, cool. im going to give this a look. thank you!

**Comment by Sarveshsh8** [comment]
did you find any location for ensembling using torch.hub.load?

**Comment by glenn-jocher** [comment]
@Sarveshsh8 Weighted boxes fusion seems like a solid approach for ensembling. Thanks for sharing! Let me know if there's anything else I can help with.
