### ISSUE TITLE
PermissionError: [WinError 5] 拒绝访问。

### ISSUE THREAD

**Issue by xxyClass** [ultralytics/yolov5#8626]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

yolov5> python train.py --img 640 --data data/coco128.yaml --cfg models/yolov5s.yaml --weights weights/yolov5s.pt --batch-size 8 --epochs 50
train: weights=weights/yolov5s.pt, cfg=models/yolov5s.yaml, data=data/coco128.yaml, hyp=data\hyps\hyp.scratch-low.yaml, epochs=50, batch_size=8, imgsz=640, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, noplots=False, evolve=None, bucket=, cache=None, image_weights=False, device=, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=8, project=runs\train, name=exp, exist_ok=False, quad=False, cos_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, seed=0, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest
'git' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Command 'git fetch && git config --get remote.origin.url' returned non-zero exit status 1.
'git' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
YOLOv5  2022-7-8 Python-3.9.12 torch-1.11.0+cpu CPU

hyperparameters: lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0
Weights & Biases: run 'pip install wandb' to automatically track and visualize YOLOv5  runs (RECOMMENDED)
TensorBoard: Start with 'tensorboard --logdir runs\train', view at http://localhost:6006/

                 from  n    params  module                                  arguments
  0                -1  1      3520  models.common.Conv                      [3, 32, 6, 2, 2]
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]
  2                -1  1     18816  models.common.C3                        [64, 64, 1]
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]
  4                -1  2    115712  models.common.C3                        [128, 128, 2]
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]
  6                -1  3    625152  models.common.C3                        [256, 256, 3]
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]
  8                -1  1   1182720  models.common.C3                        [512, 512, 1]
  9                -1  1    656896  models.common.SPPF                      [512, 512, 5]
 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 12           [-1, 6]  1         0  models.common.Concat                    [1]
 13                -1  1    361984  models.common.C3                        [512, 256, 1, False]
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 16           [-1, 4]  1         0  models.common.Concat                    [1]
 17                -1  1     90880  models.common.C3                        [256, 128, 1, False]
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]
 19          [-1, 14]  1         0  models.common.Concat                    [1]
 20                -1  1    296448  models.common.C3                        [256, 256, 1, False]
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]
 22          [-1, 10]  1         0  models.common.Concat                    [1]
 23                -1  1   1182720  models.common.C3                        [512, 512, 1, False]
 24      [17, 20, 23]  1     18879  models.yolo.Detect                      [2, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
YOLOv5s summary: 270 layers, 7025023 parameters, 7025023 gradients, 16.0 GFLOPs

Transferred 342/349 items from weights\yolov5s.pt
Scaled weight_decay = 0.0005
optimizer: SGD with parameter groups 57 weight (no decay), 60 weight, 60 bias
train: Scanning 'D:\xxy\work\cv\yolov5\data\pw\labels\train.cache' images and labels... 5 found, 0 missing, 0 empty, 0 corrupt: 100%|██████████| 5/5 [00:00<?, ?it/s]
val: Scanning 'D:\xxy\work\cv\yolov5\data\pw\labels\test.cache' images and labels... 5 found, 0 missing, 0 empty, 0 corrupt: 100%|██████████| 5/5 [00:00<?, ?it/s]
Plotting labels to runs\train\exp14\labels.jpg... 
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
PS D:\xxy\work\cv\yolov5> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\soft\Anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\soft\Anaconda3\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "D:\soft\Anaconda3\lib\multiprocessing\connection.py", line 967, in rebuild_pipe_connection
    handle = dh.detach()
  File "D:\soft\Anaconda3\lib\multiprocessing\reduction.py", line 131, in detach
    return _winapi.DuplicateHandle(
PermissionError: [WinError 5] 拒绝访问。
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\soft\Anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\soft\Anaconda3\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "D:\soft\Anaconda3\lib\multiprocessing\connection.py", line 967, in rebuild_pipe_connection
    handle = dh.detach()
  File "D:\soft\Anaconda3\lib\multiprocessing\reduction.py", line 131, in detach
    return _winapi.DuplicateHandle(
PermissionError: [WinError 5] 拒绝访问。
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\soft\Anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\soft\Anaconda3\lib\multiprocessing\spawn.py", line 126, in _main
    Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\soft\Anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\soft\Anaconda3\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "D:\soft\Anaconda3\lib\multiprocessing\connection.py", line 967, in rebuild_pipe_connection
    handle = dh.detach()
  File "D:\soft\Anaconda3\lib\multiprocessing\reduction.py", line 131, in detach
    return _winapi.DuplicateHandle(
PermissionError: [WinError 5] 拒绝访问。
self = reduction.pickle.load(from_parent)
  File "D:\soft\Anaconda3\lib\multiprocessing\connection.py", line 967, in rebuild_pipe_connection
    handle = dh.detach()
  File "D:\soft\Anaconda3\lib\multiprocessing\reduction.py", line 131, in detach
    return _winapi.DuplicateHandle(
PermissionError: [WinError 5] 拒绝访问。
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\soft\Anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\soft\Anaconda3\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "D:\soft\Anaconda3\lib\multiprocessing\connection.py", line 967, in rebuild_pipe_connection
    handle = dh.detach()
  File "D:\soft\Anaconda3\lib\multiprocessing\reduction.py", line 131, in detach
    return _winapi.DuplicateHandle(
PermissionError: [WinError 5] 拒绝访问。
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\soft\Anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\soft\Anaconda3\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "D:\soft\Anaconda3\lib\multiprocessing\connection.py", line 967, in rebuild_pipe_connection
    handle = dh.detach()
  File "D:\soft\Anaconda3\lib\multiprocessing\reduction.py", line 131, in detach
    return _winapi.DuplicateHandle(
PermissionError: [WinError 5] 拒绝访问。
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\soft\Anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\soft\Anaconda3\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "D:\soft\Anaconda3\lib\multiprocessing\connection.py", line 967, in rebuild_pipe_connection
  File "<string>", line 1, in <module>
  File "D:\soft\Anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\soft\Anaconda3\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "D:\soft\Anaconda3\lib\multiprocessing\connection.py", line 967, in rebuild_pipe_connection
    handle = dh.detach()
  File "D:\soft\Anaconda3\lib\multiprocessing\reduction.py", line 131, in detach
    return _winapi.DuplicateHandle(
PermissionError: [WinError 5] 拒绝访问。
  File "<string>", line 1, in <module>
  File "D:\soft\Anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\soft\Anaconda3\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "D:\soft\Anaconda3\lib\multiprocessing\connection.py", line 967, in rebuild_pipe_connection
    handle = dh.detach()
  File "D:\soft\Anaconda3\lib\multiprocessing\reduction.py", line 131, in detach
    return _winapi.DuplicateHandle(
PermissionError: [WinError 5] 拒绝访问。
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\soft\Anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\soft\Anaconda3\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "D:\soft\Anaconda3\lib\multiprocessing\connection.py", line 967, in rebuild_pipe_connection
    handle = dh.detach()
  File "D:\soft\Anaconda3\lib\multiprocessing\reduction.py", line 131, in detach
    return _winapi.DuplicateHandle(
PermissionError: [WinError 5] 拒绝访问。
    handle = dh.detach()
  File "D:\soft\Anaconda3\lib\multiprocessing\reduction.py", line 131, in detach
    return _winapi.DuplicateHandle(
PermissionError: [WinError 5] 拒绝访问。

**Comment by xxyClass** [comment]
Running environment windows11 and Anaconda3

**Comment by xxyClass** [comment]
训练自己的模型出错，跟着教程一步一步做，步骤应该没错，应该和系统有关系，后来我又重装了系统，还是报相同的错误，难道 yolov5 在windows11 上不能训练么？
我在 windows11 上直接运行 python detect.py --source 0 --weights=“weights/yolov5s.pt” 是可以的。
实在不知道怎么处理这个错误。

**Comment by 1246ashit** [comment]
i have same quetion.
i had been  open all of authority to anaconda  but it's still not works .

**Comment by 1246ashit** [comment]
ok, i got a solution 
just insert following sentence
**********************************************
import os  
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"
****************************************************
it's for fix that 

OMP: Error https://github.com/ultralytics/yolov5/issues/15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.

**Comment by hongyanaa** [comment]
> 训练自己的模型出错，跟着教程一步一步做，步骤应该没错，应该和系统有关系，后来我又重装了系统，还是报相同的错误，难道 yolov5 在windows11 上不能训练么？ 我在 Windows11 上直接运行 Python detect.py --source 0 --weights=“weights/yolov5s.pt” 是可以的。 实在不知道怎么处理这个错误。

我也是这个问题，解决了吗？

**Comment by shengxi-rise** [comment]
> 

I have the same problem. I want to know where are you add this sentences? On train.py?

**Comment by glenn-jocher** [comment]
@shengxi-rise in order to fix the `OMP: Error` issue, you can add the following code snippet at the top of your `train.py` file:

```python
import os  
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"
```

This code sets the environment variable `KMP_DUPLICATE_LIB_OK` to `"TRUE"`, which resolves the issue related to the initialization of `libiomp5md.dll`.

Make sure to save the changes and then try running the training script again. This should resolve the problem. Let me know if you encounter any further issues.

**Comment by shengxi-rise** [comment]
> @shengxi-rise in order to fix the `OMP: Error` issue, you can add the following code snippet at the top of your `train.py` file:
> 
> ```python
> import os  
> os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"
> ```
> 
> This code sets the environment variable `KMP_DUPLICATE_LIB_OK` to `"TRUE"`, which resolves the issue related to the initialization of `libiomp5md.dll`.
> 
> Make sure to save the changes and then try running the training script again. This should resolve the problem. Let me know if you encounter any further issues.

Thanks, I had fix this error and trained my model successfully.

**Comment by glenn-jocher** [comment]
@shengxi-rise glad to hear that the solution worked for you! If you have any further questions or encounter any other issues, feel free to ask. Happy training!

**Comment by annyugen** [comment]
I want to update that @glenn-jocher solution above still works for anyone running into this problem!

**Comment by glenn-jocher** [comment]
@nguyenAn1201 it's great to hear that the solution is still effective! If anyone else encounters similar issues or has any more questions, don't hesitate to reach out. The community and I are here to help. Happy coding! 🚀

**Comment by hotpotlover-yang** [comment]
> 训练自己的模型出错，跟着教程一步一步做，步骤应该没错，应该和系统有关系，后来我又重装了系统，还是报相同的错误，难道 yolov5 在windows11 上不能训练么？ 我在 windows11 上直接运行 python detect.py --source 0 --weights=“weights/yolov5s.pt” 是可以的。 实在不知道怎么处理这个错误。

我也是同样的问题，win10系统， 请问解决了吗

**Comment by glenn-jocher** [comment]
Hello @hotpotlover-yang and @nguyenAn1201,

Thank you for reaching out and for providing details about the issue you're encountering. To help us investigate this further, could you please provide a minimum reproducible code example? This will allow us to better understand the problem and work towards a solution. You can find more information on how to create a minimum reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example). It's crucial for us to be able to reproduce the bug before we can investigate a solution.

Additionally, please ensure that you are using the latest versions of `torch` and the YOLOv5 repository from [GitHub](https://github.com/ultralytics/yolov5). Sometimes, issues are resolved in newer releases, and updating might fix the problem you're experiencing.

For the specific issue related to `OMP: Error`, you can add the following code snippet at the top of your `train.py` file:

```python
import os  
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"
```

This should help resolve the issue related to the initialization of `libiomp5md.dll`.

If you continue to face issues, please share any error messages or logs that you receive. This will help us diagnose the problem more effectively.

Looking forward to your response and happy training! 😊
