### ISSUE TITLE
Inference only in commercial product using torch.hub.load(), license GPL v3? 

### ISSUE THREAD

**Issue by creativesalam** [ultralytics/yolov5#8628]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

E.g. if I used in python environment model = torch.hub.load('ultralytics/yolov5', 'yolov5s') 
It downloaded the yolov5 code to .cache (on windows machine). I am not explicitly cloning the yolov5 repo.   
I will be deploying my custom model in commercial environment. 
I am not cloning the repo directly or modifying the yolov5 code. I just need to use the inference code.  Do I need to opensource my project because of GPL v3 requirement? To be more specific I will train a custom model with yolov5. In our distribution I will be using it only for inference on custom model. We are not redistributing it for training etc.  

What are possible ways to deploy custom model in commercial product (only inference) without having problems with the license? 

Thanks!

**Comment by glenn-jocher** [comment]
@creativesalam sounds fine to me, but I am not an attorney and not qualified to provide legal advice, so I would find one to ask.

**Comment by antran89** [comment]
Hi @glenn-jocher, I would also have the same question. We trained a custom model with slight modifications on our own dataset, and want to deploy in a commercial product. I am wondering if you advise on us for it. After that, we just use the model's weight (not inference code) in our app. We don't want to open source our applications also.

**Comment by glenn-jocher** [comment]
@antran89 sounds fine to me, but as I mentioned before I'm not an attorney and am not qualified to provide legal advice.
