### ISSUE TITLE
How to save recognized images to different folders in different categories

### ISSUE THREAD

**Issue by chen136942027** [ultralytics/yolov5#8629]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have identified the classes person, car and cat.
how can I save the images containing these three classes in separate folders named person, car and cat?

### Additional

。

**Comment by glenn-jocher** [comment]
@chen136942027 `python detect.py --save-crop` saves crops to directories by class name
