### ISSUE TITLE
Exception for torch.hub.load, __init__() got an unexpected keyword argument 'fuse' 

### ISSUE THREAD

**Issue by ptoyip** [ultralytics/yolov5#8635]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

OS: macOS BigSur 11.6.5 and Win10

My colleague(win10) got this problem when he want to load the model from the torch hub. He follows what the tutorial write using ```model = torch.hub.load('ultralytics/yolov5', 'yolov5x')``` and the kernel return an exception. 
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File ~/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py:46, in _create(name, pretrained, channels, classes, autoshape, verbose, device)
     45 if pretrained and channels == 3 and classes == 80:
---> 46     model = DetectMultiBackend(path, device=device, fuse = autoshape)  # download/load FP32 model
     47     # model = models.experimental.attempt_load(path, map_location=device)  # download/load FP32 model
     48 else:

TypeError: __init__() got an unexpected keyword argument 'fuse'

The above exception was the direct cause of the following exception:

Exception                                 Traceback (most recent call last)
/Users/ipynb_file_im_running.ipynb Cell 20 in <cell line: 42>()
     39         finally:
     40             sys.stdout = old_stdout
---> 42 model = torch.hub.load('ultralytics/yolov5', 'yolov5x')
     44 # %%
     45 class Document:

File ~/opt/anaconda3/lib/python3.9/site-packages/torch/hub.py:404, in load(repo_or_dir, model, source, force_reload, verbose, skip_validation, *args, **kwargs)
    401 if source == 'github':
    402     repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, verbose, skip_validation)
--> 404 model = _load_local(repo_or_dir, model, *args, **kwargs)
    405 return model

File ~/opt/anaconda3/lib/python3.9/site-packages/torch/hub.py:433, in _load_local(hubconf_dir, model, *args, **kwargs)
    430 hub_module = _import_module(MODULE_HUBCONF, hubconf_path)
    432 entry = _load_entry_from_hubconf(hub_module, model)
--> 433 model = entry(*args, **kwargs)
    435 sys.path.remove(hubconf_dir)
    437 return model

File ~/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py:95, in yolov5x(pretrained, channels, classes, autoshape, _verbose, device)
     93 def yolov5x(pretrained=True, channels=3, classes=80, autoshape=True, _verbose=True, device=None):
     94     # YOLOv5-xlarge model https://github.com/ultralytics/yolov5
---> 95     return _create('yolov5x', pretrained, channels, classes, autoshape, _verbose, device)

File ~/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py:65, in _create(name, pretrained, channels, classes, autoshape, verbose, device)
     63 help_url = 'https://github.com/ultralytics/yolov5/issues/36'
     64 s = f'{e}. Cache may be out of date, try `force_reload=True` or see {help_url} for help.'
---> 65 raise Exception(s) from e

Exception: __init__() got an unexpected keyword argument 'fuse'. Cache may be out of date, try `force_reload=True` or see https://github.com/ultralytics/yolov5/issues/36 for help.
```

I've tried on my laptop(macOS) and initially works fine, then I realise I'm using local cache where I download the model last week, therefore I run ```model = torch.hub.load('ultralytics/yolov5', 'yolov5x')``` instead and the same problem occurs.

I've checked the pull request and I found there's a update for ```hubconf.py``` 2 days ago where 
```model = DetectMultiBackend(path, device=device) ``` 
became
 ```model = DetectMultiBackend(path, device=device, fuse = autoshape) ```

To be honest, I'm a beginner programmer, so I've tried 
```model = torch.hub.load('ultralytics/yolov5', 'yolov5x', autoshape = True)```
and 
```model = torch.hub.load('ultralytics/yolov5', 'yolov5x', autoshape = False)```
and these two methods don't works.

At the end I've come up two ways to bypass this problem, 
- modify the ```hubconf.py``` back to ```model = DetectMultiBackend(path, device=device)```
- add an extra condition ```model = torch.hub.load('ultralytics/yolov5', 'yolov5x', classes = n)``` where n != 80

Obviously these two are not a good solution. May I ask what's the correct way to load the hub model ?

**Comment by glenn-jocher** [comment]
@ptoyip your YOLOv5 code is out of date, simply git pull or reclone the repo to update. 

This will only occur if a YOLOv5 Hub model is loaded in an old cloned YOLOv5 repo directory.
