### ISSUE TITLE
The performance difference between Focus Module and Conv Module

### ISSUE THREAD

**Issue by Coobiw** [ultralytics/yolov5#8637]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,It's my honor to push this issue here! After read the yolov5*(whatever the model scale).yaml. I find that the Focus Module is replaced by a Conv Module whose in_channels is 3 ,out_channels is 64 and stride is 2. I think this is similar to YOLOv4. So I want to know what this change bring us i.e. the difference between them. Thanks for your reply!

### Additional

(0): Conv(
    (conv): Conv2d(3, 32, kernel_size=(6, 6), stride=(2, 2), padding=(2, 2), bias=False)
……

but not Focus Module

**Comment by zhiqwang** [comment]
It's equivalent, see https://github.com/ultralytics/yolov5/issues/4825 for more details.

**Comment by Coobiw** [comment]
Thanks for your answer！

**Comment by glenn-jocher** [comment]
@Coobiw you're welcome! If you have any more questions or need further assistance, feel free to ask. We're here to help!
