### ISSUE TITLE
AttributeError: 'Detect' object has no attribute 'export'

### ISSUE THREAD

**Issue by RAMBOCJ1** [ultralytics/yolov5#8640]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection, Export

### Bug

This error occurred after I replaced the trained best.pt file with the yolov5s.pt file in detect after training my own dataset using yolov5
![2022-07-19 22-38-23 的屏幕截图](https://user-images.githubusercontent.com/105996500/179853090-a8f58f14-4c9d-4a0c-8dc7-d43d88ed4c2b.png)
![2022-07-19 22-40-09 的屏幕截图](https://user-images.githubusercontent.com/105996500/179853554-facbcfa7-5f4e-4829-a08c-6bc4152717c7.png)
![2022-07-19 22-40-57 的屏幕截图](https://user-images.githubusercontent.com/105996500/179853566-27feda00-d35d-42bb-86d9-de11700284a1.png)
.

### Environment

![2022-07-19 22-32-56 的屏幕截图](https://user-images.githubusercontent.com/105996500/179852506-07900a8c-554b-4228-ae15-aece9dad57b0.png)
![2022-07-19 22-33-16 的屏幕截图](https://user-images.githubusercontent.com/105996500/179852510-1aa43c4d-0c0b-4ba1-a442-26ddc3cff299.png)
![2022-07-19 22-33-25 的屏幕截图](https://user-images.githubus
![2022-07-19 22-33-32 的屏幕截图](https://user-images.githubusercontent.com/105996500/179852539-56b364d3-0978-4c8d-a51f-a679d0932a25.png)
ercontent.com/105996500/179852530-8650816f-af99-4be3-b7e1-a3fbbc7e9296.png)
![2022-07-19 22-33-50 的屏幕截图](https://user-images.githubusercontent.com/105996500/179852555-a4615929-5968-42b2-8bb4-6f6a7597872e.png)

### Additional

我训练的数据集中包含两个人后面视角的步态，并分类为两个人的ID。

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by RAMBOCJ1** [comment]
The dataset I trained contains the gait of the back view of two people and classified as the ID of both people.

**Comment by glenn-jocher** [comment]
@RAMBOCJ1 export is pretty simple, and does not require any code modifications. See TFLite, ONNX, CoreML, TensorRT Export tutorial below for details.


## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️  RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Roboflow for Datasets, Labeling, and Active Learning](https://docs.ultralytics.com/yolov5/tutorials/roboflow_datasets_integration)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TFLite, ONNX, CoreML, TensorRT Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [Architecture Summary](https://docs.ultralytics.com/yolov5/tutorials/architecture_description)&nbsp; ⭐ NEW

Good luck 🍀 and let us know if you have any other questions!
