### ISSUE TITLE
Albumentations-Pipeline is applied to BGR not to RGB

### ISSUE THREAD

**Issue by UnglvKitDe** [ultralytics/yolov5#8641]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

As written [here ](https://albumentations.ai/docs/getting_started/image_augmentation/) in step 3, Albumentations internally uses the RGB format and not the BGR format of opencv.  However, the data is currently passed internally as BGR:
https://github.com/ultralytics/yolov5/blob/92e47b85d952274480c8c5efa5900e686241a96b/utils/dataloaders.py#L626-L628
https://github.com/ultralytics/yolov5/blob/92e47b85d952274480c8c5efa5900e686241a96b/utils/dataloaders.py#L654
 Or am I missing something?

### Environment

YOLOv5 torch 1.11 (cuda 11.3) and 1.12 (cuda 11.6)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by seonho** [comment]
YOLOv5 uses the following augmentation transforms
https://github.com/ultralytics/yolov5/blob/92e47b85d952274480c8c5efa5900e686241a96b/utils/augmentations.py#L28

AFAIK, all other transforms except CLAHE are channel order independent.
But, CLAHE considers channel order if image has 3 dimensions.
https://github.com/albumentations-team/albumentations/blob/a8dc46ee29f9573c8569213f0d243254980b02f1/albumentations/augmentations/functional.py#L673

**Comment by UnglvKitDe** [comment]
@seonho According to the current state YOLOv5 also uses Gray. There it depends on the implementation of cv2.cvtCOLOR() how the RGB image is transformed to a Gray image (I couldn't find the OpenCV implementation). But either way, it is confusing if you want to adjust e.g. the default pipline for your dataset.

**Comment by seonho** [comment]
@UnglvKitDe Yes, I missed `ToGray`. According to OpenCV's [Color conversion document](https://docs.opencv.org/4.6.0/de/d25/imgproc_color_conversions.html),  `RGB2GRAY` also affected by channel order.

So, at least two (ToGray, CLAHE) transforms are channel order dependent.

**Comment by glenn-jocher** [comment]
@UnglvKitDe yes you are correct, there is an inconsistency there is Albumentations is used. The best solution I can think of is to immediately convert to RGB after cv2 imread (and update where required like augment_hsv()). Then we can safely assume RGB-order images throughout all dataloaders.

I think this might be slightly slower than the current implementation which reverses BGR-RGB in the first dimension (CHW) rather than the last (HWC), resulting in a faster BGR-RGB conversion. I'll add a TODO here so I don't forget.

TODO: Fix bug that Albumentations inputs BGR images but expects RGB images.

**Comment by UnglvKitDe** [comment]
@glenn-jocher I have pushed a first idea.

**Comment by glenn-jocher** [comment]
@UnglvKitDe thanks! I will take a look at the PR. For reference some BGR to RGB speeds:
<img width="839" alt="Screen Shot 2022-07-23 at 11 20 14 PM" src="https://user-images.githubusercontent.com/26833433/180623212-ca65ee85-4fa3-432c-a2a8-f1f741571696.png">


```python
import numpy as np
import cv2
import time

im = np.random.rand(640,640,3).astype(np.uint8)

t = time.time()
for _ in range(10000):
  x = im[...,::-1]
print(time.time() - t)

t = time.time()
for _ in range(10000):
  np.flip(im,2)
print(time.time() - t)

t = time.time()
for _ in range(10000):
  cv2.cvtColor(im, cv2.COLOR_BGR2RGB)
print(time.time() - t)

```

<img width="462" alt="Screen Shot 2022-07-23 at 11 21 59 PM" src="https://user-images.githubusercontent.com/26833433/180623249-08de8ac6-2e2d-4bed-958d-b9e25b0e36b3.png">

**Comment by UnglvKitDe** [comment]
@glenn-jocher Oh thats a good point. I thought opencv do something like that. But it looks very slow. Thx!

**Comment by glenn-jocher** [comment]
@UnglvKitDe you're welcome! Thank you for your understanding. Let me know if you have any questions or need further assistance with the PR.
