### ISSUE TITLE
There was a problem using detect.py

### ISSUE THREAD

**Issue by SSTato** [ultralytics/yolov5#8642]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

![image](https://user-images.githubusercontent.com/93987794/179882664-1eb02719-ff50-467b-9ad1-24f089f95ac1.png)

When I detect the video, there are two display boxes, one of which is the box that does not display any information. I don't want it, but it will appear every time. How can I solve it? I use the windows system, and everything else is normal.

**Comment by glenn-jocher** [comment]
@SSTato I'm not sure what the second box is. On MacOS I never see that, and don't have a Windows machine to test unfortunately. If you find a solution please submit a PR to help other windows uses, thank you!

**Comment by SSTato** [comment]
> @SSTato我不确定第二个盒子是什么。在 MacOS 上我从来没有看到过，而且很遗憾没有要测试的 Windows 机器。如果您找到解决方案请提交 PR 以帮助其他 windows 使用，谢谢！

![image](https://user-images.githubusercontent.com/93987794/180695425-ce594c46-2740-43ca-baec-093213f8a955.png)
If the code in the red box is deleted, the problem will disappear. I output the list windows and find that its initial state is empty. Is this the reason.
![image](https://user-images.githubusercontent.com/93987794/180695666-95ba270b-66f1-40d1-93e8-58848de823e4.png)

**Comment by glenn-jocher** [comment]
@SSTato got it, thanks for the debugging! This code is meant for window resizing issues in Linux, so we can make it linux-specific to resolve your Windows problem.

**Comment by glenn-jocher** [comment]
@SSTato good news 😃! Your original issue may now be fixed ✅ in PR #8712. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
