### ISSUE TITLE
Two-stage NMS

### ISSUE THREAD

**Issue by andreweryan** [ultralytics/yolov5#8643]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

From what I understand, YOLOv5’s NMS implementation gets applied per image at the tensor level. Is it possible to reapply this NMS after the results are produced? The use case is applying a second stage of NMS when there is overlap between two images and objects exist within the overlap. Those would be separate images with independent detections that wouldn’t have NMS applied. I’m sure it’s able to be accomplished but I’m trying to understand if the implementation you use can be used or if this will have to be a custom implementation. Thanks!

**Comment by glenn-jocher** [comment]
@andreweryan I don't quite understand your proposed method, but you can customize the NMS function to suit your custom requirements here:
https://github.com/ultralytics/yolov5/blob/b510957650c890dee876146c43dcda1fdfc279d6/utils/general.py#L784-L884

**Comment by andreweryan** [comment]
I was curious if it were possible to apply NMS again after the detections are returned (to DF, json, etc.) but it looks that NMS is being applied on a tensor so I would have to customize it. I'm working with overlapping tiles of very large images so there are multiple detections on the same objects when I stitch everything back together.

**Comment by andreweryan** [comment]
I was curious if it were possible to apply NMS again after the detections are returned (to DF, json, etc.) but it looks that NMS is being applied on a tensor so I would have to customize it. I'm working with overlapping tiles of very large images so there are multiple detections on the same objects when I stitch everything back together.

**Comment by isspid** [comment]
@andreweryan Take a look at this [repo](https://github.com/obss/sahi).
