### ISSUE TITLE
RuntimeError: result type Float can't be cast to the desired output type long int

### ISSUE THREAD

**Issue by lucysumi** [ultralytics/yolov5#8644]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I tried to run this on **Monash dataset** [https://github.com/MarcusLimJunYi/Monash-Guns-Dataset]
and i get this error:

`File "/content/yolov5/utils/loss.py", line 211, in build_targets`
   ` indices.append((b, a, gj.clamp_(0, gain[3] - 1), gi.clamp_(0, gain[2] - 1)))  # image, anchor, grid indices`

`RuntimeError: result type Float can't be cast to the desired output type long int`

Where do I need to do the changes ?

**Comment by lucysumi** [comment]
![Screenshot (305)](https://user-images.githubusercontent.com/34506425/180131888-771a5e1a-dfb4-40ac-9998-027cb7a38eb7.png)

**Comment by lucysumi** [comment]
![Screenshot (306)](https://user-images.githubusercontent.com/34506425/180132049-d65056c5-a120-4baf-a901-ebee0d493d88.png)

**Comment by lucysumi** [comment]
That's the error I get when I tried to train it on a custom dataset from roboflow.

**Comment by glenn-jocher** [comment]
@lucysumi your YOLOv5 code is out of date. To update and resolve this issue:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

**Comment by lucysumi** [comment]
It worked perfectly in solving my problem. Thank you @glenn-jocher

**Comment by dinarkino** [comment]
If someone is wondering what change will fix the problem, here is the commit: https://github.com/ultralytics/yolov5/pull/8067/files

**Comment by keepgoing365** [comment]
> If someone is wondering what change will fix the problem, here is the commit: https://github.com/ultralytics/yolov5/pull/8067/files

it works,thank you.

**Comment by glenn-jocher** [comment]
@keepgoing365 glad to hear it's working! 🚀 Remember that the YOLOv5 community and the Ultralytics team are here to help with any issues you encounter. If you have any more questions, feel free to ask.
