### ISSUE TITLE
Understanding F1 Curve over Confidence values

### ISSUE THREAD

**Issue by rahuja23** [ultralytics/yolov5#8646]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

![F1](https://user-images.githubusercontent.com/51020974/179958845-862378d6-5b26-4041-86d2-4fb6ae96f500.png)
 I have a question regarding the F1 curve that is being plotted. The X-Axis used for the curve is Confidence I am assuming that the F1 scores are being evaluated on different confidence values and the plotted. Can someone please point me out towards the code where this evaluation is happening?

**Comment by pourmand1376** [comment]
Take a look here:
https://github.com/ultralytics/yolov5/blob/4c1784bd158d3215aa7170b33578e1032442a160/utils/metrics.py#L29-L93

**Comment by glenn-jocher** [comment]
@pourmand1376 thanks for your inquiry! You can check the F1 curve evaluation code starting from line 29 in `utils/metrics.py` in the YOLOv5 repository. Feel free to take a look and let us know if you have any further questions. Your interest and enthusiasm for understanding the F1 curve are greatly appreciated!
