### ISSUE TITLE
WARNING: --rect is incompatible with DataLoader shuffle, setting shuffle=False

### ISSUE THREAD

**Issue by PasaImage** [ultralytics/yolov5#8648]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Why --rect is incompatible with DataLoader shuffle ?

**Comment by glenn-jocher** [comment]
@PasaImage --rect sorts the dataset by aspect ratio for maximum efficiency, which is naturally incompatible with shuffling.
