### ISSUE TITLE
traincustom  cropped licence plate characters using yolo5

### ISSUE THREAD

**Issue by fadsamo** [ultralytics/yolov5#8651]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I need help implementing my own license plate recognition system.

### Additional

for plate recognition(charcter recognition), my dataset includes characters separated from the license plate. That is, for each example of the numbers 0 to 9, I have about 1000 data, so I don't have the entire license plate.
In order to be able to implement this application, how should I label and use these codes to implement the plate recognition part?
![H (1)](https://user-images.githubusercontent.com/31373251/179976994-282e23e4-0500-4bb6-8c75-004f7615ec07.jpg)
![6 (1)](https://user-images.githubusercontent.com/31373251/179977022-5237f249-f1f2-4dce-b9b6-dbb749a11c75.jpg)

**Comment by glenn-jocher** [comment]
@fadsamo you can train a classifier on these crops (i.e. with 10+26 classes for alphanumeric characters), and a detection model to locate license plates or digits within a license plate.
