### ISSUE TITLE
Detection wanted on wide, narrow image

### ISSUE THREAD

**Issue by Russ76** [ultralytics/yolov5#8659]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

What is the best way to train for wide, narrow images? These will be 1920 x 300 images. Can Yolov5 train on such images? Would I use the image size to instruct the train routine? How is this done?

### Additional

This model will be loaded into the Oak-D camera, and needs to be fairly fast, like 100 ms.

**Comment by barney2074** [comment]
that's an unusual aspect ratio- but I think you'd just specify the long side
`python train.py --img 1920 --rect`

**Comment by barney2074** [comment]
I think the inference time is just a case of try it & see.
I've got an Oak and it generally seems to perform pretty well- but probably depends on the pathway to get it onto the device

Assuming:
YoloV5-->Pytorch weights (.pt)-->https://tools.luxonis.com/ --> blob
you'd probably need to adjust the height to be divisible by 32 (i.e not 300)

![image](https://user-images.githubusercontent.com/25944617/180166839-9baf5de5-4156-4043-af73-62868455388d.png)

**Comment by Russ76** [comment]
Thanks for good info. Will try it!

**Comment by Russ76** [comment]
The combination of Roboflow for working with images and Yolov5 training on Google Colab works GREAT! We are making progress...

**Comment by Russ76** [comment]
It worked well, thanks!

**Comment by glenn-jocher** [comment]
@Russ76 great to hear that! If you have any more questions or need further assistance, feel free to ask. Good luck with your project, and kudos to the YOLO community and the Ultralytics team for their great work!
