### ISSUE TITLE
one question about the code of yolov5

### ISSUE THREAD

**Issue by silly-chen** [ultralytics/yolov5#8661]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello! Excuse me, but when I ran the detect.py , the image I actually entered the model had a resolution of 384 * 640. However, I set the resolution in the test is clearly 640 * 640, why the actual input model only 384 * 640?

**Comment by silly-chen** [comment]
yes, it's a common dataset. 
![2](https://user-images.githubusercontent.com/84671687/180172429-0f9ac276-898a-42e1-ae66-db0895e5c6ce.PNG)
![4](https://user-images.githubusercontent.com/84671687/180172463-34cff3ed-21a0-4e13-af08-fcc2cf9914bd.PNG)

**Comment by silly-chen** [comment]
I set the test resolution to 640*640, but when testing according to the loaded image in the code, only 380*640

**Comment by silly-chen** [comment]
When training the model, there is no such situation. The resolution of the image fed to the model during training is 640*640

**Comment by silly-chen** [comment]
I don't know the reason, the training and testing use the same data loading method, and the parameters are also set to 640*640

**Comment by glenn-jocher** [comment]
@silly-chen YOLOv5 pytorch models use rectangular inference for reduced processing and faster speeds.
