### ISSUE TITLE
Why am I getting extra detections?

### ISSUE THREAD

**Issue by nadimra** [ultralytics/yolov5#8663]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi!

I'm working on an application for sports ball tracking. When using the yolov5 detector (and trying to draw a line to represent the trail of the sports ball via the detections), I get this output:

![image](https://user-images.githubusercontent.com/36157933/180207081-3fc8871c-7056-476c-80ff-fe526563989f.png)

However, the last ball detection was on this frame:
![image](https://user-images.githubusercontent.com/36157933/180207585-f614a1c5-56f2-4120-a963-a91b9646c3aa.png)

so I'm not sure why an extra point was added in between the two frames. 

Here's the some of the code adjustments made:
![image](https://user-images.githubusercontent.com/36157933/180207869-e03e1c1e-1774-4718-b27b-48a05e304551.png)

Do you know of any reason why this has happened? ps. `ball_locations.append` only occurs in the above code snippet

**Comment by glenn-jocher** [comment]
@nadimra looks interesting but the question is outside of the scope of our support and we don't have resources to help debug custom code. Good luck though, perhaps a community member can help.
