### ISSUE TITLE
Class loss, object loss, box loss equation

### ISSUE THREAD

**Issue by Fel26** [ultralytics/yolov5#8666]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, i want to ask about yolov5 loss function
can you guys explain to me where can i find out the equation of class loss, object loss and box loss YOLOv5?
thanks

**Comment by glenn-jocher** [comment]
@Fel26 see utils/loss.py:
https://github.com/ultralytics/yolov5/blob/b510957650c890dee876146c43dcda1fdfc279d6/utils/loss.py#L91-L176
