### ISSUE TITLE
Impressive Results when changing `conf-thres` and `iou-thres`

### ISSUE THREAD

**Issue by pourmand1376** [ultralytics/yolov5#8669]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have actually searched yolov5 and read theses related issues:
- #7864 
- #8615
- #8302
- #6953
- #8646

Still, with my dataset (which is medical image) I get impressive results when increasing `conf-thres`. I am not sure if my model is doing good or actually changing `conf-thres` is basically wrong? 

Also, PR curves for each `conf-thres` is different. Is this normal?
I am worried about the results because of warning that you issue when `conf-thres` is more than 0.001.

## [Default] Conf-thres = 0.001
![image](https://user-images.githubusercontent.com/32064808/180317431-b04f9304-245b-44ac-a8f5-45eeaa9483c5.png)

## Conf-thres = 0.5
![image](https://user-images.githubusercontent.com/32064808/180315856-ca983ae2-91b8-4abf-9bae-514f82e454f9.png)

## Conf-thres = 0.7
![image](https://user-images.githubusercontent.com/32064808/180317504-d26eed00-da7d-436e-bef4-6087e74ce4b8.png)

## Conf-thres = 0.8
![image](https://user-images.githubusercontent.com/32064808/180315968-b1e78135-55e9-44cd-8d02-2661a3515c0e.png)

## Conf-thres = 0.85
![image](https://user-images.githubusercontent.com/32064808/180318850-6cf848a8-596e-4333-ab72-a6a3bb30c78f.png)

## Conf-thres = 0.86
![image](https://user-images.githubusercontent.com/32064808/180320846-4ba4bc72-a8b5-4f09-bfa8-3a86270d1d70.png)

## Conf-thres = 0.88
![image](https://user-images.githubusercontent.com/32064808/180320905-ed418cad-bd74-40e1-b2f4-db38de64956c.png)

## Conf-thres = 0.9
![image](https://user-images.githubusercontent.com/32064808/180318786-b83ccc97-a604-42bb-a790-e23c272cdd48.png)

**Comment by Zephyr69** [comment]
If you mean the conf-thres in val.py, yes it's wrong to change that. The reason is exactly what was said by the warning.

**Comment by pourmand1376** [comment]
In my specific application, I only care about precision/recall. 
Is that also wrong? If yes, why would that be the case? 

Also, see [this comment](https://github.com/ultralytics/yolov5/issues/6953#issuecomment-1066779018) which says that changing mAP would produce inaccurate mAP but nothing about other metrics.

**Comment by pourmand1376** [comment]
As I can see, this is the only place where `conf-thres` is used in `val.py`. 
https://github.com/ultralytics/yolov5/blob/4c1784bd158d3215aa7170b33578e1032442a160/val.py#L217

So, this is basically filtering out the results. Results which have lower `conf-thres` than defined are just ignored. This is fine by any standard. 

This is where AP for each class is calculated. 
https://github.com/ultralytics/yolov5/blob/4c1784bd158d3215aa7170b33578e1032442a160/val.py#L263-L271

And this is the actual code for calculating average precision.
https://github.com/ultralytics/yolov5/blob/4c1784bd158d3215aa7170b33578e1032442a160/utils/metrics.py#L29-L93

which calls this function:
https://github.com/ultralytics/yolov5/blob/4c1784bd158d3215aa7170b33578e1032442a160/utils/metrics.py#L96-L121

Just the first stage is affected by `conf-thres`, so after changing this hyperparameter, the results of all metrics should be OK.

> Note that `ap_per_class` function doesn't depend on any external thresholds. So, PR curve would not combine results for all confidence thresholds but just for one conf-threshold. This is what is see from code. 

Am I missing something?

**Comment by GavinYang5** [comment]
i have the same question

**Comment by pourmand1376** [comment]
I think this may be a bug. I checked that results for `recall`, `precision` and `mAP` are actually wrong! 

Recall should decrease as we increase `conf-thres` value.

**Comment by pourmand1376** [comment]
I think the bug is here. In line 217, we are filtering out based on non_max_suppression. Then we enumerate on filtered result and use filtered targets to calculate mAP. This should not be the case. We should always return unfiltered targets. 

https://github.com/ultralytics/yolov5/blob/1c5e92aba11f0dd007716821e7cd151d532342a8/val.py#L214-L247

I've also printed `target_cls.shape` when passing the input to `ap_per_class` function like this:
```python
def ap_per_class(tp, conf, pred_cls, target_cls, plot=False, save_dir='.', names=(), eps=1e-16):
    """ Compute the average precision, given the recall and precision curves.
    Source: https://github.com/rafaelpadilla/Object-Detection-Metrics.
    # Arguments
        tp:  True positives (nparray, nx1 or nx10).
        conf:  Objectness value from 0-1 (nparray).
        pred_cls:  Predicted object classes (nparray).
        target_cls:  True object classes (nparray).
        plot:  Plot precision-recall curve at mAP@0.5
        save_dir:  Plot save directory
    # Returns
        The average precision as computed in py-faster-rcnn.
    """
    print(f"TP Shape: {tp.shape}")
    print(f"Conf Shape : {conf.shape}")
    print(f"predicted_cls: {pred_cls.shape}")
    print(f"target_cls: {target_cls.shape}")
```

```bash
## using conf-thres 0.85
TP Shape: (33, 10)
Conf Shape : (33,)
predicted_cls: (33,)
target_cls: (30,)
#  -------------
# using conf-thres 0.001
TP Shape: (25239, 10)
Conf Shape : (25239,)
predicted_cls: (25239,)
target_cls: (281,)
# -------------
# using conf-thres 0.001
TP Shape: (24777, 10)
Conf Shape : (24777,)
predicted_cls: (24777,)
target_cls: (266,)
# --------------
```
Even when having same conf-thres as recommended, we end up calculating the result wrong! Target_cls should always be the same, no matter what conf-thres is, this is because number of target labels per class is always the same. 

This way, even setting conf-thres to 0.001 gives wrong results. 

**If you look at labels count column in every threshold above, you understand that this is wrong. Labels count shouldn't change for each run!** 

I will do a PR soon.

**Comment by pourmand1376** [comment]
Now with PR #8686, my results are consistent and everything is fine. You can also see that label's count is persistent in each run and it is equal to actual labels that I have. 

However, my model is not doing any good, so I can not **publish** the results! Before that, I was actually happy about the result. 

Here's the results after fixing the bug:
## Conf-thres = 0.001
![image](https://user-images.githubusercontent.com/32064808/180602512-9a8ef007-9f02-4be7-adde-4fa632744b51.png)

## Conf-thres = 0.2
![image](https://user-images.githubusercontent.com/32064808/180602109-ee389176-b2dc-46ec-bc9c-69e56af61bc7.png)

## Conf-thres = 0.5
![image](https://user-images.githubusercontent.com/32064808/180603174-0866cef6-1a36-4b47-868a-df67b43b93b7.png)

## Conf-thres = 0.7
![image](https://user-images.githubusercontent.com/32064808/180603164-3c7fc02c-b033-4cc1-8079-b10cd0d348da.png)

## Conf-thres = 0.85
![image](https://user-images.githubusercontent.com/32064808/180603201-437cf4df-bafa-492f-b068-ee517096bfbc.png)

## Conf-thres = 0.9
![image](https://user-images.githubusercontent.com/32064808/180603460-8db91d82-b968-4629-a6ce-effdfa65a769.png)

**Comment by pourmand1376** [comment]
We can not just say that changing `conf-thres` is wrong.

See this paper which has demonstrated the importance of confidence threshold. It is interesting that it has actually done some experiments using Yolov5. 

[Confidence Score: The Forgotten Dimension of Object Detection Performance Evaluation](https://www.mdpi.com/1424-8220/21/13/4350)

Page 15 of the paper:
![image](https://user-images.githubusercontent.com/32064808/180606392-deb85cae-114b-4251-9ddd-9b3a69a80754.png)

**Comment by pourmand1376** [comment]
This PR is not required actually. If you have this problem, you should just update your forked repo to latest version. This has been fixed a little earlier.

**Comment by glenn-jocher** [comment]
@kaminetzky you're welcome! It's great to hear that your issues have been addressed. Feel free to reach out if you need further assistance. Good luck with your work!
