### ISSUE TITLE
hello， Can NVIDIA GPU be used with docker in windows10？？

### ISSUE THREAD

**Issue by zhuya1996** [ultralytics/yolov5#8670]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Can NVIDIA GPU be used with docker in windows10
？？

**Comment by glenn-jocher** [comment]
@zhuya1996 hello! Yes, you can use NVIDIA GPU with Docker on Windows 10 by installing the appropriate NVIDIA GPU drivers, Docker, and the NVIDIA Container Toolkit. You can find detailed guidance in our documentation at https://docs.ultralytics.com/yolov5/. If you encounter any issues, feel free to ask for further assistance.

**Comment by zhuya1996** [comment]
thansk
&nbsp;


莫失莫忘0212
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Glenn ***@***.***&gt;; 
发送时间: 2023年11月15日(星期三) 下午5:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ultralytics/yolov5] hello， Can NVIDIA GPU be used with docker in windows10？？ (Issue #8670)






@朱亚1996你们好！可以，您可以通过安装相应的NVIDIA GPU驱动程序、Docker和NVIDIA容器工具包，在Windows 10上将NVIDIA GPU与Docker配合使用。您可以在我们的文档中找到详细的指导，网址是https://docs.ultralytics.com/yolov5/.如果您遇到任何问题，请随时寻求进一步的帮助。

-
直接回复这封邮件，在GitHub上查看，或取消订阅.
你收到这个是因为你被提到了。消息ID:<超解析/约洛夫 5 /问题/ 8670 / ***@***.***和&gt;

**Comment by glenn-jocher** [comment]
@zhuya1996 you're welcome! If you have any more questions or need further assistance, feel free to ask. Have a great day!
