### ISSUE TITLE
i am getting an error at the time of training , yolov5 classification--------> TypeError: yolov5s() got an unexpected keyword argument 'trust_repo'

### ISSUE THREAD

**Issue by bahadurthakur** [ultralytics/yolov5#8671]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

i am getting an error at the time of training , yolov5 classification--------> TypeError: yolov5s() got an unexpected keyword argument 'trust_repo'

root@9ee4f8b1bb80:/work/yolov5# python classifier.py --model yolov5s --data cifar100 --epochs 5 --img 224 --batch 8
classifier: model=yolov5s, data=cifar100, hyp=data/hyps/hyp.scratch-low.yaml, epochs=5, batch_size=8, imgsz=224, nosave=False, evolve=False, cache=None, device=, workers=1, project=runs/train, name=exp, exist_ok=False, pretrained=True, local_rank=-1, optimizer=Adam, lr0=0.0015, label_smoothing=0.15, cutoff=None, dropout=None, verbose=False
github: skipping check (Docker image), for updates see https://github.com/ultralytics/yolov5
YOLOv5 🚀 v6.1-532-g0a5a0ab Python-3.8.8 torch-1.9.0+cu102 CUDA:0 (GeForce RTX 2080 Ti, 11019MiB)

TensorBoard: Start with 'tensorboard --logdir runs/train', view at http://localhost:6006/
Downloading https://github.com/ultralytics/yolov5/releases/download/v1.0/cifar100.zip to /work/datasets/cifar100.zip...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 174M/174M [02:35<00:00, 1.17MB/s]
Unzipping /work/datasets/cifar100.zip...
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
Training yolov5s on cifar100 dataset with 100 classes...
Downloading: "https://github.com/ultralytics/yolov5/archive/master.zip" to /usr/src/app/.cache/torch/hub/master.zip
Traceback (most recent call last):
  File "classifier.py", line 111, in train
    model = hub.load(repo1, opt.model, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/hub.py", line 364, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/hub.py", line 393, in _load_local
    model = entry(*args, **kwargs)
TypeError: yolov5s() got an unexpected keyword argument 'trust_repo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "classifier.py", line 394, in <module>
    train()
  File "classifier.py", line 113, in train
    model = hub.load(repo1, opt.model, force_reload=True, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/hub.py", line 364, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/hub.py", line 393, in _load_local
    model = entry(*args, **kwargs)
TypeError: yolov5s() got an unexpected keyword argument 'trust_repo'

**Comment by glenn-jocher** [comment]
@bahadurthakur thanks for the bug report! trust_repo is a new argument that PyTorch Hub is starting to require, but is not recognized by older versions of torch. I'll see if I can push a fix for this. What version of torch are you using?

EDIT: nevermind, see torch-1.9.0

**Comment by glenn-jocher** [comment]
@bahadurthakur good news 😃! Your original issue may now be fixed ✅ in https://github.com/ultralytics/yolov5/commit/e53521354e73c31aca842787957f0e5e0f959fc1. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
