### ISSUE TITLE
Not forking

### ISSUE THREAD

**Issue by huangqi111** [ultralytics/yolov5#8672]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When I run the test.py file, spawn_main(pipe_handle=3836, parent_pid=37096) always reports an exception: AssertionError Not forking, how can I solve it

At the same time, File "<string>", line 1
    import sys; sys.path.insert(0, r'c:\Users\huang'qi\.vscode\extensions\ms-python.python-2022.10.1\pythonFiles\lib\python\debugpy\_vendored\pydevd') ; import pydevd; pydevd.PydevdCustomization.DEFAULT_PROTOCOL='http_json'; pydevd.settrace(host='127.0.0.1', port=62193, suspend=False, trace_only_current_thread=False, patch_multiprocessing=True, access_token=None, client_access_token='e2111e3e7f0075609a9bc9c9ae49425070a8552b5ad28b1b55ff6c5663afdfb8 ', __setup_holder__={'client': '127.0.0.1', 'client-access-token': 'e2111e3e7f0075609a9bc9c9ae49425070a8552b5ad28b1b55ff6c5663afdfb8', 'json-dap-http': True, 'multiprocess3': True ' 'port' ppid': 48152, 'server': False, 'skip-notify-stdin': True}); from multiprocessing.spawn import spawn_main; spawn_main(parent_pid=48152, pipe_handle=2540), 
the file has SyntaxError: invalid syntax, but I file not found

**Comment by glenn-jocher** [comment]
@huangqi111 YOLOv5 current version has no test.py file.

**Comment by huangqi111** [comment]
I am using yolov5 v5.0

**Comment by glenn-jocher** [comment]
@huangqi111 I'd recommend updating to the latest. To update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>
