### ISSUE TITLE
potential bug after mosaic operation

### ISSUE THREAD

**Issue by wangren97** [ultralytics/yolov5#8673]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training, Other

### Bug

Hi,
I found a potential bug in [https://github.com/ultralytics/yolov5/blob/master/utils/dataloaders.py](url) for mosaic operation. 
In the lines 723-724, a clip operation is performed to reshape the bounding boxes whose corners are out of the mosaic image.
In detail, xmin < 0 or xmax > 2 * image_size or ymin < 0 or ymax > 2 * image_size. However, there exists a case that both xmin, xmax (or ymin, ymax) are equal to zero, which maybe a potential bug. If display these boxes on the mosaic image, a line rather than a box will be shown since its width or height is 0. 
I run a basic test for this case on 2007 trainval (5011 images). The total number of bounding boxes after mosaic is around 50k, and the number of bounding boxes which have the aforementioned issue is around 1k.  The frequency of this potential bug is 2%, I am not sure whether 2% problematic bounding boxes would harm the performance. Maybe removing them is better. Could u please check it?

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@wangren97 thanks for the bug report! 2% problematic boxes is a serious problem, but I believe zero-width boxes are removed by the box_candidates() function here applied at the end of the perspective transform function in the mosaic loader:
https://github.com/ultralytics/yolov5/blob/b367860196a2590a5f44c9b18401dedfc0543077/utils/augmentations.py#L212-L213

The argument wh_thr=2 is saying that all boxes with width or height < 2 pixels will be eliminated as label candidates.
https://github.com/ultralytics/yolov5/blob/b367860196a2590a5f44c9b18401dedfc0543077/utils/augmentations.py#L279-L284

So there should be no zero-width or zero-height labels in labels4 here:
https://github.com/ultralytics/yolov5/blob/b367860196a2590a5f44c9b18401dedfc0543077/utils/dataloaders.py#L735-L747

Can you confirm that you are not seeing any problem boxes in labels4 on mosaic loader return?

**Comment by wangren97** [comment]
@glenn-jocher Thanks for your detailed explanation. Now I understand the augmentation scheme in this repo and there is no problem about this issue. 
I have two more questions about the data augmentation part. 
[1] For mosaic operation, using random crop or random perspective makes the image size equal to the predefined one, ex: 640. when visualizing some samples, I find there exists a case that the bounding box box may not represent the object well. Consider a person object, the cropped result only remains the arm part, now the width of the box is fine but the height actually shows the whole person rather arm part. It is quite difficult to estimate the percentage of this case (not filtered by the box_candidates() function), this issue seems similar to the random crop issue in the general image classification task that may cause inconsistency with the given label. I am wondering whether it is possible to crop the image with an area that can preserve full boxes of the objects in the cropped area instead of pure random.
[2] For mosaic + mixup, I check the previous issues [https://github.com/ultralytics/yolov5/issues/6447
](url) and [https://github.com/ultralytics/yolov5/issues/991
](url). mixup can be used separated from mosaic, but in the rectangular training case, it seems that random.randint(0, self.n - 1) cannot be used directly. Only the image has the same shape can be combined together, the image index may come from the same batch or neighboring batches.
Please correct me if my understanding is wrong.
Thanks

**Comment by glenn-jocher** [comment]
@wangren97 box_candidates() also provides for filters based on area before and after augmentation that can be tuned to reject boxes that are largely cropped away due to augmentations:
https://github.com/ultralytics/yolov5/blob/b367860196a2590a5f44c9b18401dedfc0543077/utils/augmentations.py#L279-L284

Also segmentation labels, if available, should resolve the issue of the person's arm you describe as well.
