### ISSUE TITLE
Show time of epoch

### ISSUE THREAD

**Issue by MasIgor** [ultralytics/yolov5#8677]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello!

when I run the training on google collab, i see the number of batches, the elapsed time, and the remaining time for each epoch. 

Running it locally on our server tough, does not display the data above. I only see this:

![image](https://user-images.githubusercontent.com/67956327/180440191-b1562d24-7820-484a-a93b-30ec35b7607b.png)

Is there a way to show this info on our server too?

thank you

Best regards

**Comment by glenn-jocher** [comment]
@tanzerlana tqdm may not work properly in all environments, but in Colab and Docker everything seems correct like you said. You might use Docker locally. If you have a reproducible issue in a common environment please let us know with steps to reproduce, thank you!

**Comment by MasIgor** [comment]
@glenn-jocher  thanks for your answer. I installed ubuntu lts 20.04 on a machine, installed anaconda, and jupyter. Run the latest yolov5 from jupyter and this was the output. I am also using wandb... Not sure if that makes a difference..

**Comment by MasIgor** [comment]
@glenn-jocher was this information enough? do you need more info? thank you!

**Comment by glenn-jocher** [comment]
@tanzerlana if the issue is reproducible in a common environment, i.e. Docker, Colab, Kaggle, etc. we could get started debugging it.
