### ISSUE TITLE
Openvino Bounding Box

### ISSUE THREAD

**Issue by Liquid72** [ultralytics/yolov5#8679]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I have been training the Yolov5 with custom data and exporting it into Openvino format, And the problem is I could understand the array output. My goal is to draw the bounding box and get the detected classes, this is make me confused.

<img width="967" alt="image" src="https://user-images.githubusercontent.com/42716120/180479195-a72d6b0c-131a-436d-8a30-58937069b28e.png">
<img width="505" alt="image" src="https://user-images.githubusercontent.com/42716120/180479441-6e520b13-17be-4ebf-bb8c-35961cd728ed.png">

**Comment by glenn-jocher** [comment]
@Liquid72 OpenVINO usage examples are displayed directly after OpenVINO export, i.e. run `python export.py --include openvino` and then:
<img width="653" alt="Screen Shot 2022-07-23 at 7 31 48 PM" src="https://user-images.githubusercontent.com/26833433/180616330-892bef4d-acf2-40a2-856a-f6048e1434ab.png">
