### ISSUE TITLE
Dataset download failure on Windows

### ISSUE THREAD

**Issue by NanoCode012** [ultralytics/yolov5#868]
## 🐛 Bug

Windows does not support unzip.
https://github.com/ultralytics/yolov5/blob/9776e7098880903e0549376a7b62cfdc66b4ec12/utils/general.py#L153

## To Reproduce (REQUIRED)

Input:
```bash
python test.py
```

Output:
Download file success
![image](https://user-images.githubusercontent.com/9899957/91599417-74102900-e990-11ea-8149-3ed154c3fd54.png)

but, does not unzip and remove it

```
WARNING: Dataset not found, nonexistant paths: ['coco128\\images\\train2017']    
Downloading https://github.com/ultralytics/yolov5/releases/download/v1.0/coco128.zip ...
100%|█████████████████████████████████████████████████████████████████████████████████████████████| 21.1M/21.1M [00:48<00:00, 452kB/s] 
'unzip' is not recognized as an internal or external command,
operable program or batch file.
Dataset autodownload failure

Traceback (most recent call last):
  File "yolov5\utils\datasets.py", line 309, in __init__
    raise Exception('%s does not exist' % p)
Exception: ..\coco128\images\train2017 does not exist
```

## Expected behavior
Unzip and remove

## Environment

- OS: Windows 10
- Env: Conda py37
- Shell: `cmd`

## Additional context
I looked around for solutions on Windows. The closest one is [this link on SO](https://stackoverflow.com/a/12886818/8293176) , but a new function has to be added which I understand is not a clean solution. I was hoping others would have a solution

**Comment by glenn-jocher** [comment]
@NanoCode012 thanks for spotting this! I don't have access to a windows machine, so I'll modify the CI checks in a new PR to see what's going on there. The current checks force a dataset download before everything else, but this also uses the unzip command. Perhaps a simple `pip install unzip` would fix this?

**Comment by glenn-jocher** [comment]
Current manual download step in CI checks:
https://github.com/ultralytics/yolov5/blob/9776e7098880903e0549376a7b62cfdc66b4ec12/.github/workflows/ci-testing.yml#L54-L59

**Comment by NanoCode012** [comment]
Hi @glenn-jocher , I thought `unzip` was a Unix package only! 

I've tried,

`pip install zip` : got error due to dependency uses py < 3. See here for open Issue https://github.com/kdheepak/zip/issues/3#issue-462598301

`pip install unzip`: does not exist

`conda install -c conda-forge unzip`: looking at [site](https://anaconda.org/conda-forge/unzip), it only supports unix (PackageNotFound Error)

`python test.py` (on Anaconda shell): same error

However, I know using `git` bash (MinGW) could use `unzip` because it uses unix commands. Maybe it is what the CI checks uses? (Fyi, my conda does not seem to play well with it)

**Comment by glenn-jocher** [comment]
@NanoCode012 I'm not sure exactly, not too familiar with windows. I see that the Windows autodownload process did succeed though:

https://github.com/ultralytics/yolov5/pull/869/checks?check_run_id=1043171610
<img width="1341" alt="Screen Shot 2020-08-28 at 6 14 54 PM" src="https://user-images.githubusercontent.com/26833433/91625228-6770de00-e95a-11ea-81c7-7cb724d158dd.png">

The CI environment must then have a zip utility installed as part of its dependencies.

**Comment by NanoCode012** [comment]
Hi @glenn-jocher , Yes, I saw that too.. I’m actually surprised no one else got this issue as V3 has been out for a while.. I was using Unix this entire time, so I did not notice till yesterday.

Could you try to add `ls` as one of the commands? It is not a recognized function in Windows. We can see whether it’s using windows cmd or Unix..

Also, a system call, `unzip file` could not be a python file/lib..

Edit: This isn’t a breaking problem as a user could just extract it themselves using Windows built in zip. But it would be nice to be given a warning or message.

**Comment by NanoCode012** [comment]
Hi @glenn-jocher , some findings:

It uses Windows Powershell

![image](https://user-images.githubusercontent.com/9899957/91626129-99278a80-e9d6-11ea-8ed6-8be23a35ae6c.png)

Test `ls` follows same output format as my powershell.

![image](https://user-images.githubusercontent.com/9899957/91626144-ad6b8780-e9d6-11ea-8752-c6a0863959b9.png)

I don't use Powershell because I had to add `conda` to `PATH`, which I don't want, but maybe the below could help others. 

Test unzip on Powershell:
```bash
> unzip coco128.zip
unzip : The term 'unzip' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ unzip coco128.zip
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (unzip:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

After some digging on Powershell, the below worked for me
```powershell
Expand-Archive -LiteralPath coco128.zip -DestinationPath ..
```

Really  inconvenient 😆

**Comment by glenn-jocher** [comment]
@NanoCode012 strange! Hey I have a random question. I was experimenting with DDP and found that 4x T4 GPUs are now faster than 1 V100, at about 2/3 the price on GCP (yay!). When I run DDP though I see a warning msg saying something like OMP_THREAD_NUMBER set to 1 to keep system from being overloaded. 

Do you think this means that each node then only has 1 cpu worker available to it?

**Comment by NanoCode012** [comment]
@glenn-jocher , Wow! That's great! More performance with less cost! I recall that you had a breakdown of the costs on GCP but can't find it anymore..

Regarding OMP, I'm not sure how it's related to number of cpu workers. I referred to a few threads and chose to keep it to its default value because it has different effects on different systems. For ex, 
https://github.com/pytorch/pytorch/issues/22451#issuecomment-507887210

Edit: Maybe I will test diff values of that env variable and will post my results. But right now, I'm testing diff batch sizes for 5m on coco and testing 1 fine tuning of 5s.

**Comment by glenn-jocher** [comment]
@NanoCode012 hmm ok! I would think if the worker count were restricted it would show up in the logging statement, i.e. 'Using 8 dataloader workers...' is what we see for single GPU. I can't check right now either as my multi-gpu vm is evolving finetuning hyps. The evolution is a huge success, it's raised YOLOv5m VOC mAP from 86.5 to 89.1 now after about 100 generations. I'm assuming this means that the larger models will produce VOC mAPs over 0.90, which I think is pretty good.
