### ISSUE TITLE
question about labels_correlogram.jpg

### ISSUE THREAD

**Issue by Wooks-git** [ultralytics/yolov5#8682]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, i'm question about labels_correlogram.
i understood that the image explain about bounding box's distribution.
But what are the benefits of that image?

**Comment by glenn-jocher** [comment]
@Wooks-git a correlogram simply plots multidimensional data against itself. The benefits are introspection into your label statistics.

**Comment by Wooks-git** [comment]
@glenn-jocher thanks to reply my question.

**Comment by glenn-jocher** [comment]
@Wooks-git you're welcome! Feel free to reach out if you have any more questions.
