### ISSUE TITLE
Building  considered as an object Detection using Yolo

### ISSUE THREAD

**Issue by shvamabps** [ultralytics/yolov5#8683]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Can yolo be used to detect buildings (object)?

**Comment by glenn-jocher** [comment]
@shvamabps anything can be detected

**Comment by shvamabps** [comment]
Actually, the issue I am facing is the generate the label for yolo. How to make yolo understand different types of labels.

**Comment by glenn-jocher** [comment]
@shvamabps you can train YOLO to detect different types of objects by creating a custom dataset with labels for those objects. You'll need to ensure that your dataset includes annotations for each object you want to detect, and that the annotations are in YOLO format. For detailed instructions, you can refer to the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/. If you encounter any specific issues during this process, feel free to ask for help!
