### ISSUE TITLE
Yolov5 with attention model 

### ISSUE THREAD

**Issue by ratom** [ultralytics/yolov5#8684]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

I have not found any repo or implementation about transformer and yolov5. Can anyone suggest me the repo and trained weights if any. Most of the information I found were partial not a running or complete repo. Thanks

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ratom we have a YOLOv5 transformer model here you can use. It's not very popular because the CUDA requirements and training time are super high compared to the baseline models. You can train with i.e.
```bash
python train.py --weights yolov5s.pt --cfg yolov5s-transformer.yaml
```

For details see:
https://github.com/ultralytics/yolov5/blob/master/models/hub/yolov5s-transformer.yaml

**Comment by Zephyr69** [comment]
I have tested various versions of transformer/attention modules for yolov5. Some did raise a bit of metrics performance in certain types of dataset, but none of them justified the inevitable additional computation and vram cost.

I don't think vision transformers are the next thing to go for. I'd look more forward to ConvNeXt.

**Comment by glenn-jocher** [comment]
@Zephyr69 yes this is the impression I have currently also. I think a big part of the excitement originated from NLP but the transfer of benefits to vision is less clear to me. 

While there is always a market for the absolute best accuracy, in the real world the product with the most positive impact will be the one with the best balance in terms of speed/size/performance.

I think Elon Musk mentioned something similar regarding range in electric vehicles, longest isn't necessarily best when all factors are considered.

**Comment by konioy** [comment]
Is there a model for yolov5s-transform ？

**Comment by glenn-jocher** [comment]
@konioy https://github.com/ultralytics/yolov5/blob/master/models/hub/yolov5s-transformer.yaml

**Comment by ratom** [comment]
what is the architecture of transformer with yolov5. is this used in backbone in topup with existing backbone or replacing with transformer,  or in detection head. Can you make a bit clear.

**Comment by glenn-jocher** [comment]
@ratom you can just do a diff between yolov5s-transformer.yaml above and yolov5s.yaml

**Comment by konioy** [comment]
Is there a pretrained model for yolov5s-transformer?

**Comment by glenn-jocher** [comment]
@konioy no, sorry. You can train one on COCO yourself though:
```
python train.py --weights yolov5s.pt --cfg yolov5s-transformer.yaml
```
