### ISSUE TITLE
Maybe a little mistake in Dockerfile

### ISSUE THREAD

**Issue by xiaoyuan0203** [ultralytics/yolov5#8685]
https://github.com/ultralytics/yolov5/blob/1c5e92aba11f0dd007716821e7cd151d532342a8/utils/docker/Dockerfile-cpu#L29

It seem all files and dirs in `.`(meaning project root `yolov5`, right?) will be copied to `/usr/src/app`. Is it expected? The .dockerignore file doesn't work here.

**Comment by glenn-jocher** [comment]
@xiaoyuan0203 yes I think you are right. We need to move .dockerignore to yolov5/

**Comment by glenn-jocher** [comment]
@xiaoyuan0203 good news 😃! Your original issue may now be fixed ✅ in PR #8690. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
