### ISSUE TITLE
I can run the detect.py but can't  run the train.py

### ISSUE THREAD

**Issue by Sspacegray** [ultralytics/yolov5#8687]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

- Because of the  limit of hardware,i must use yolov5 1.0 to apply my machine, after many hard work,i can run the detect.py, but can't train my data,also i use the official model,but the feedback to my is:`AttributeError: 'Detect' object has no attribute 'm'` , i use conda to create the environment,pytorch==1.4.0,cuda=10.0,python=3.6.8, the full errors as follows:
`Traceback (most recent call last):
  File "/home/wu/yolov5-1.0/yolov5-1.0/train.py", line 406, in <module>
    train(hyp)
  File "/home/wu/yolov5-1.0/yolov5-1.0/train.py", line 80, in train
    model = Model(opt.cfg).to(device)
  File "/home/wu/yolov5-1.0/yolov5-1.0/models/yolo.py", line 69, in __init__
    self._initialize_biases()  # only run once
  File "/home/wu/yolov5-1.0/yolov5-1.0/models/yolo.py", line 129, in _initialize_biases
    for mi, s in zip(m.m, m.stride):  # from
  File "/home/wu/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 576, in __getattr__
    type(self).__name__, name))
AttributeError: 'Detect' object has no attribute 'm'`

**Comment by glenn-jocher** [comment]
@Sspacegray I'd recommend using the latest version of YOLOv5. If you need a suitable environment you can use Colab or Kaggle with free GPUs:

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>
