### ISSUE TITLE
Classifier always use image_size=224

### ISSUE THREAD

**Issue by AI-Passionner** [ultralytics/yolov5#8689]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

I am interested in the classifier at high resolutions and found it always runs the training on imgsz=224 (default one) if `argumentations` not installed. But it always runs the test at `224`. 
Then I traced back the code and found that `self.torch_transforms = classify_transforms() `.  seems missing `imgsz`. 

Then tried to print the image size in the `trainloader` and it was (3, 224, 224). But the default logger still shows `Image sizes 4000 train, 4000 test`. They are consistent only if I added `imgsz` to `classify_transforms()`
. 
![yolov5-classification-debug-2](https://user-images.githubusercontent.com/65562616/180607101-670b8266-de5a-4753-931e-3c335767c5fa.PNG)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@AI-Passionner thanks for the bug report! I've been making a lot of changes to classification to prepare it for a new release next week. You're right I forgot to pass imgsz to classify_transforms(). I've fixed this in https://github.com/ultralytics/yolov5/commit/e1fb3e6f411cd1de5a20119b37d81e2d2f8d7baa. Please git pull and try again, and let me know if you find any other issues, thanks!

**Comment by AI-Passionner** [comment]
Thank you very much. YOLOV5 is such a beautiful object detection system.

**Comment by glenn-jocher** [comment]
@AI-Passionner now classification system too! :)
