### ISSUE TITLE
Changing class texts after training?

### ISSUE THREAD

**Issue by HunarAA** [ultralytics/yolov5#8691]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Can I change the class texts after training? I mean while detecting using webcam? Where I can change them? I have tried to put my dataset.yaml file inside data directory with new texts but it does not affect the detection process. It uses older texts.

**Comment by glenn-jocher** [comment]
@HunarAA if you are using detect.py you can try to point to an updated data.yam with new class names, i.e.
```bash
python detect.py --data path/to/data.yaml
```

If that doesn't work you can just redefine the names list here:
https://github.com/ultralytics/yolov5/blob/b510957650c890dee876146c43dcda1fdfc279d6/detect.py#L93

**Comment by HunarAA** [comment]
Thanks, the second method worked. But the problem with support for Arabic like languages still exist.

**Comment by glenn-jocher** [comment]
@HunarAA all alphabets are supported by YOLOv5 including asian, arabic, cyrillic, etc. If you have a bug please submit a bug report with exact commands to reproduce, thank you.
