### ISSUE TITLE
How is training so fast?

### ISSUE THREAD

**Issue by mkutu** [ultralytics/yolov5#8697]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

The YoloV5 training pipeline is fast!  After working with other model implementation for various tasks and after spending considerable amount of time trying to improve the speed of my own pipeline from scratch, I've still never been able to replicate the speed of yolov5. How do you do it?

What is most striking is the data parsing and continuous flow of processing. 
I know there's a lot of variability between models, tasks, and image processing tasks, but nothing I do seems to come close to the speed of yolov5. 
I'm running on multiple GPUs and would like to learn more about some of the techniques used to speed up the training pipeline. I'm currently reviewing the code but getting lost.  
How have you all avoided bottle necking so well? Does this have something do to with the image caching? 
Any insight would be greatly appreciated and forgive the question if this has already been covered.

Thanks for all the work you all do and for making this tool so accessible.

**Comment by glenn-jocher** [comment]
@mkutu thanks! 👋 Hello! Thanks for asking about **training speed issues**. YOLOv5 🚀 can be trained on CPU (slowest), [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) (fastest). If you would like to increase your training speed some options are:

- Increase `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s
- Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) DDP at larger `--batch-size`
- Train on cached data: `python train.py --cache` (RAM caching) or `--cache disk` (disk caching)
- Train on faster GPUs, i.e.: P100 -> V100 -> A100
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

Good luck 🍀 and let us know if you have any other questions!

**Comment by mkutu** [comment]
@glenn-jocher thanks for the info. My questions wasn't really about how I can train faster on YOLOv5, yalls documentation is excellent so I haven't had any trouble with that. My question had more to do with some of the system design principles that you all are using to really speed up training, particularly data loading. Have you ever thought of writing some type of white paper on this? Or does one already exist?

**Comment by glenn-jocher** [comment]
@mkutu it's really many small improvements all over the place rather than one specific thing. 

I'd write a papers if I had any time to do so, but YOLOv5 maintenance and improvement never ends so it uses up all my time.
