### ISSUE TITLE
Does `--rect` conflict with DDP training？

### ISSUE THREAD

**Issue by leo-q8** [ultralytics/yolov5#8698]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training, Multi-GPU

### Bug

My train command (with my own costume dataset):
python -m torch.distributed.launch  --nproc_per_node 4 train.py --datata/test.yaml --cfg yolov5x.yaml --batch-size 16 --img-size 1024 --device 0,1,2,3 --sync-bn --workers 16 --weights --epochs 2 --rect 
And got error:
![image](https://user-images.githubusercontent.com/64625668/180633679-791db938-1980-4cca-8070-9ee3f1f9b970.png)

Then, I turned to use one gpu for `--rect` train. It works successfully. So, I debug into the dataloaders and find the `self.shapes` and `self.batch_shapes` are as follows:
![image](https://user-images.githubusercontent.com/64625668/180633764-ca854c01-64db-4c3b-893f-1fe3a587ae1e.png)

![image](https://user-images.githubusercontent.com/64625668/180633772-5fcedf93-8160-4950-84a3-9aa351159e44.png)

I guess this problem may caused by `DistributedSampler`. It splits the ordered samples to different ranks, which makes the `batch_shapes` no longer applicable to batch samples in the local rank.

### Environment

-YOLOv5 🚀 v6.1-316-g916bdb1 Python-3.8.13 torch-1.11.0+cu102 CUDA:0 (NVIDIA GeForce RTX 2080 Ti, 11020MiB) 
-OS Ubuntu 18.04

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@avril-wang1214 yes this makes sense. If you can confirm that DDP training is incompatible with --rect we should add an assert here to better explain this to users:
https://github.com/ultralytics/yolov5/blob/b367860196a2590a5f44c9b18401dedfc0543077/train.py#L522-L534

**Comment by wudashuo** [comment]
DDP training is compatible with `--rect` only if all your images are the same aspect ratio. 
For example, your dataset images contain following resulotion: 1920 * 1080, 960 * 540 and 640 * 360(all the same aspect ratio),  you can run DDP training normally with `--rect`.

**Comment by glenn-jocher** [comment]
@wudashuo ah yes good point!
