### ISSUE TITLE
from utils.datasets import LoadStreams, LoadImages ModuleNotFoundError: No module named 'utils.datasets'

### ISSUE THREAD

**Issue by 96068chandra** [ultralytics/yolov5#8702]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

**Traceback (most recent call last):**
  File "detect_fish.py", line 11, in <module>
    from utils.datasets import LoadStreams, LoadImages
**ModuleNotFoundError: No module named 'utils.datasets'**

### Additional

![Screenshot (79)](https://user-images.githubusercontent.com/87321782/180645530-7f8fa2ad-e543-49f6-bf3f-ae8dc0aa18c6.png)
![WhatsApp Image 2022-07-24 at 4 52 38 PM](https://user-images.githubusercontent.com/87321782/180645543-c36ebae9-842c-4994-a6a0-ef2882328ab0.jpeg)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@96068chandra utils/datasets.py has been renamed to utils/dataloaders.py.

It looks like your code is out of date. To update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>
