### ISSUE TITLE
Significance of --half?

### ISSUE THREAD

**Issue by PraveenMNaik** [ultralytics/yolov5#8708]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Can you please let me know the significance of --half during training process....

**Comment by glenn-jocher** [comment]
@PraveenMNaik there is no --half flag in train.py

**Comment by PraveenMNaik** [comment]
I mean in the val.py... what is the significance of --half flag

**Comment by glenn-jocher** [comment]
@PraveenMNaik you can simply read the argument help:
https://github.com/ultralytics/yolov5/blob/0b5ac224aef287ac3ac9ebf70ade60159450a0b1/val.py#L351

**Comment by bit-scientist** [comment]
@glenn-jocher when I enabled `--half` with `val.py` on V100 GPU, the `mAP@.5` increased by 0.7 and `mAP@.5:.95` decreased by 1.4. Is it something expected to observe? Does `--half` focuses on improving  `mAP0.5` at the expense of reducing `mAP0.5:0.95` (if that makes sense)?

**Comment by PraveenMNaik** [comment]
is it possible to make model run for various inferences?

**Comment by glenn-jocher** [comment]
@PraveenMNaik yes, you can use --float or --half for different inference precision.
