### ISSUE TITLE
Different results after converting weights to tensorflow js

### ISSUE THREAD

**Issue by Gystre** [ultralytics/yolov5#8718]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

After training and converting my model to tensorflow js, I am noticing very different results compared to when I am using the model locally. I couldn't figure out if tensorflow was doing something to the image or if there was some setting that I missed that could be causing it. Below are some screenshots of what I mean.

cpu: ryzen 7 5800x
gpu: rtx 3070 

To load the model on tensorflow js I am doing the following:
```
const gridPromise = tf.loadGraphModel(`model.json`, ...);

Promise.all([gridPromise]).then(
    async ([grid]) => {
        setGridModel(grid);
    }
);
```

And to detect with the model I am doing the following:
```
gridModel.executeAsync(croppedInput).then((res) => {
  const [gBoxes, gScores, gClasses, gValidDetections] = res as tf.Tensor<tf.Rank>[];

  // draw to canvas code...
});
```

Tensorflow js
![s1](https://user-images.githubusercontent.com/37854809/180889949-259e1bb1-700a-4c33-9ee1-8d2c2a892669.png)

Local
![20220617-1pnt3-91CpEoJifxL_search_21_10176993](https://user-images.githubusercontent.com/37854809/180890974-4af17993-aeac-4c04-b585-3bcc110b2bfd.png)

Tensorflow js
![s2](https://user-images.githubusercontent.com/37854809/180890010-15180f45-4dcf-4156-997c-76c7f4f75cac.png)

Local
![20220617-0fpes-CloudsWordSearchSolved_search_20_10176993](https://user-images.githubusercontent.com/37854809/180890954-348e4b39-b71a-4939-b582-e0e59995cfc9.png)

**Comment by glenn-jocher** [comment]
@Gystre I'm not a super JS expert but make sure you are passing images in RGB order (not BGR), and follow the TF.js inference Usage example here:
https://github.com/ultralytics/yolov5/blob/b367860196a2590a5f44c9b18401dedfc0543077/export.py#L38-L42

**Comment by Gystre** [comment]
I've loaded my models into the example mentioned in export.py but I am getting identical results, so I think the images are being passed in the right way.

![s1ex](https://user-images.githubusercontent.com/37854809/180896270-692ef979-c7b8-4886-bd46-a19e2a295ab1.png)
![s2ex](https://user-images.githubusercontent.com/37854809/180896277-d0c01e53-029b-43a1-bd83-07a7f27b805d.png)

**Comment by glenn-jocher** [comment]
@Gystre could be due to pre or post processing differences then. All exports (except Edge TPU and TF.js) are benchmarked daily on CPU to verify identical performance. From 11 hours ago:
https://github.com/ultralytics/yolov5/runs/7511246547?check_suite_focus=true

<img width="641" alt="Screen Shot 2022-07-26 at 1 22 12 PM" src="https://user-images.githubusercontent.com/26833433/180994443-72bf4966-8fea-4b78-a639-59e22b3c0f95.png">

**Comment by Gystre** [comment]
Took me a while to figure out what was wrong but I finally got it. Passing in a higher value to these two lines let my model detect everything else.

https://github.com/ultralytics/yolov5/blob/3e858633b283767f038b4cab910a95e40fe8577b/export.py#L589-L590

**Comment by glenn-jocher** [comment]
@Gystre do you have more than 100 objects per image?

**Comment by Gystre** [comment]
Yeah, the grids that I'm running yolo through can range from 5x5 to 30x30 which means I need to detect 25-900 objects.

Most of them aren't so bad like this one (225 objects)
![225](https://user-images.githubusercontent.com/37854809/181798492-c1edba58-456c-4caf-9f17-43d1df277a41.png)

But sometimes the grid will be really big like this one (400 objects)
![400](https://user-images.githubusercontent.com/37854809/181798550-36254b24-1e09-4977-b692-8459c8d67e29.png)

**Comment by glenn-jocher** [comment]
@Gystre oh got it. Yes that makes sense then.
