### ISSUE TITLE
I keep getting Wandb login pop up while trying to do training.

### ISSUE THREAD

**Issue by lucysumi** [ultralytics/yolov5#8720]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

 I'm trying to train my custom dataset on yolov5 in my workstation using anaconda, then this Wandb login option keeps popping up and it won't even let me log in to my existing account (option 2) nor let me avoid it by choosing option 3. How do I get rid of this? Can't I just use tensorboard? Can't I just move ahead with training without using Wandb? Its annoying me.  
I am not able to complete my training process. 

Any assistance would be appreciated. 

### Environment

-

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by lucysumi** [comment]
![Screenshot (307)](https://user-images.githubusercontent.com/34506425/180949665-7f5ed4b0-8ab3-4530-96f8-efa9e70088d6.png)

**Comment by lucysumi** [comment]
Thats the error I'm getting.

**Comment by glenn-jocher** [comment]
@lucysumi yes you can run `pip uninstall wandb` to uninstall or `wandb disabled` to disable

**Comment by glenn-jocher** [comment]
@lucysumi yes you can run `pip uninstall wandb` or `wandb disabled`

**Comment by lucysumi** [comment]
Yes, I just figured it out. `wandb disabled` solved my problem. Thank you very much, Sir!

**Comment by glenn-jocher** [comment]
@lucysumi you're welcome, but all credit goes to the YOLO community and the Ultralytics team! If you have any more questions, feel free to ask. Good luck with your training!
