### ISSUE TITLE
#8641 regressing bug

### ISSUE THREAD

**Issue by arun-gautham** [ultralytics/yolov5#8724]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

I thing there is a regression bug on #8641 

iam getting this now from past some hour. when i start my training.

Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/yolov5/utils/dataloaders.py", line 640, in __getitem__
    augment_hsv(img, hgain=hyp['hsv_h'], sgain=hyp['hsv_s'], vgain=hyp['hsv_v'])
  File "/content/yolov5/utils/augmentations.py", line 61, in augment_hsv
    cv2.cvtColor(im_hsv, cv2.COLOR_HSV2BGR, dst=im)  # no return needed
TypeError: Expected Ptr<cv::UMat> for argument 'dst'

### Environment

Google colab
torch 1.12.0+cu113 (Tesla P100-PCIE-16GB)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by arun-gautham** [comment]
im = cv2.cvtColor(im, cv2.COLOR_BGR2RGB) on line 61 before
cv2.cvtColor(im_hsv, cv2.COLOR_HSV2BGR, dst=im)**

seems to solve the issue , or i guess we can change to
cv2.cvtColor(im_hsv, cv2.COLOR_HSV2RGB, dst=im)

**Comment by glenn-jocher** [comment]
@arun-gautham got it, thanks! Debugging now.

**Comment by glenn-jocher** [comment]
@arun-gautham good news 😃! Your original issue may now be fixed ✅ in PR #8727. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by arun-gautham** [comment]
Thanks a lot

**Comment by glenn-jocher** [comment]
@arun-gautham you're welcome! If you need any further assistance, feel free to ask. Happy to help!
