### ISSUE TITLE
Confusion Matrix Missing False Negatives

### ISSUE THREAD

**Issue by jbutle55** [ultralytics/yolov5#8729]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Validation

### Bug

In val.py, during the "Evaluate" stage, a single batch worth of metrics for the confusion matrix is computed using:
```               
                if plots:
                    confusion_matrix.process_batch(predn, labelsn)
```

However, if the length of predictions for the image in question is zero, this portion of code is skipped over due to:
```
            if len(pred) == 0:
                if nl:
                    stats.append((torch.zeros(0, niou, dtype=torch.bool), torch.Tensor(), torch.Tensor(), tcls))
                continue
```

If this continue statement is called then this batch is not processed for the confusion matrix, but if the relevant image had ground truth objects, meaning these were missed detections since `len(pred)` was 0, then these FNs won't be accounted for in the confusion matrix.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@jbutle55 hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by jbutle55** [comment]
This got merged, closing the issue.

**Comment by glenn-jocher** [comment]
Thank you for your contribution, @jbutle55! Your assistance is greatly appreciated. 🎉 We're grateful for your help in enhancing YOLOv5, and we look forward to any future contributions you may make. If you have any more ideas or feedback, feel free to share them!
