### ISSUE TITLE
About Cutout

### ISSUE THREAD

**Issue by ZeKunZhang1998** [ultralytics/yolov5#873]
## ❔Question

 if random.random() < 0.9:
        labels = cutout(img, labels)
## Additional context
Hello，why this function doesnot return 'image',but the cutout appear in the image?

**Comment by glenn-jocher** [comment]
@ZeKunZhang1998 python functions can update variables without returning them as arguments, like C.

**Comment by ZeKunZhang1998** [comment]
> @ZeKunZhang1998 python functions can update variables without returning them as arguments, like C.

Thanks
