### ISSUE TITLE
Cannot use NMS with edgetpu export

### ISSUE THREAD

**Issue by democat3457** [ultralytics/yolov5#8730]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Export

### Bug

Trying to export a PyTorch model as an edgetpu tflite model with the NMS flag enabled results in this error when exporting:

```
Edge TPU: starting export with Edge TPU compiler 16.0.384591198...
Edge TPU Compiler version 16.0.384591198
Started a compilation timeout timer of 180 seconds.
ERROR: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.
ERROR: Node number 270 (FlexCombinedNonMaxSuppression) failed to prepare.

Compilation failed: Model failed in Tflite interpreter. Please ensure model can be loaded/run in Tflite interpreter.
Compilation child process completed within timeout period.
Compilation failed! 

Edge TPU: export failure: Command '['edgetpu_compiler', '-s', '-o', '/path/to/weights', '/path/to/weights/best-int8.tflite']' returned non-zero exit status 1.
```

Everything before the Edge TPU export step, including the Tensorflow Lite export, succeeds just fine.

This seems similar to #6799

### Environment

- YOLOv5 🚀 v6.1-336-gd7411ad Python-3.8.10 torch-1.11.0+cu102 CPU
- OS: Ubuntu 20.04
- Python 3.8.10

### Minimal Reproducible Example

```
python export.py --include edgetpu --nms
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@democat3457 as the error says the NMS TF ops are not supported for Edge TPU delegates. 
<img width="914" alt="Screen Shot 2022-07-27 at 4 24 48 PM" src="https://user-images.githubusercontent.com/26833433/181272325-7725b1a1-3886-4028-8433-18f53c5e93cb.png">

You can export Edge TPU models using the standard arguments and then follow the Usage instructions after export:
```
Detect:          python detect.py --weights yolov5s-int8.tflite 
Validate:        python val.py --weights yolov5s-int8.tflite 
PyTorch Hub:     model = torch.hub.load('ultralytics/yolov5', 'custom', 'yolov5s-int8.tflite')
```

**Comment by democat3457** [comment]
Ah rip, ok.

**Comment by mhaghighat** [comment]
@democat3457 Did you find a workaround for this?

**Comment by democat3457** [comment]
> @democat3457 Did you find a workaround for this?

No, I just ended up implementing my own NMS using pytorch's.
