### ISSUE TITLE
Why does my trained model detect nothing when tested in detect.py(yolov5s)

### ISSUE THREAD

**Issue by tian123-zxc** [ultralytics/yolov5#8732]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training, Detection

### Bug

The following is my training configuration and training result：
![9HXQX3PS (W~AG~JT067(TU](https://user-images.githubusercontent.com/83101407/181157065-79c059e2-b33d-4389-b0ee-5651daea332d.png)
![results](https://user-images.githubusercontent.com/83101407/181157218-a574b4ca-0355-4064-b7f2-121250f4e473.png)

### Environment

yolov5s 
cuda:11.6
win11

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by tian123-zxc** [comment]
I am using the coco128 dataset

**Comment by glenn-jocher** [comment]
@tian123-zxc probably because your trained mAP is 0.03

**Comment by tian123-zxc** [comment]
> 

How can I solve this, I also tried changing the dataset, but it didn't work

**Comment by glenn-jocher** [comment]
If you train to 0.03 mAP then you should not expect your model to detect anything.
