### ISSUE TITLE
Loading a pretrained model in opencv C++

### ISSUE THREAD

**Issue by Interrupt101** [ultralytics/yolov5#8735]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,

I'm trying to read a pretrained model using C++ and opencv. <br>
I converted a yolov5s.pt to .onnx <br>
and I tried to read it as follows :

```
// Load model.
Net net;
net = readNet("yolo5s.onnx");
```

But I got the following error :

Unhandled exception at 0x00007FFAB2A44FD9 in YOLO_CPP.exe: Microsoft C++ exception: cv::Exception at memory location 0x000000DBD256EA80.

I'm using last version of opencv(4.6), I think this might happend because there are some layers that are unsupported yet by opencv, ,but I'm not sure, do you knwo how can I load my model in my C++ code without using opencv?
Thanks

**Comment by glenn-jocher** [comment]
@Helyousfi see Export [tutorial](https://docs.ultralytics.com/yolov5/tutorials/model_export) for full details on DNN or C++ inference:


## OpenCV DNN inference

OpenCV inference with ONNX models:
```bash
python export.py --weights yolov5s.pt --include onnx

python detect.py --weights yolov5s.onnx --dnn  # detect
python val.py --weights yolov5s.onnx --dnn  # validate
```

## C++ Inference

YOLOv5 OpenCV DNN C++ inference on exported ONNX model examples:
- https://github.com/Hexmagic/ONNX-yolov5/blob/master/src/test.cpp
- https://github.com/doleron/yolov5-opencv-cpp-python

YOLOv5 OpenVINO C++ inference examples:
- https://github.com/dacquaviva/yolov5-openvino-cpp-python
