### ISSUE TITLE
Increasing Inference and Training Time

### ISSUE THREAD

**Issue by abrek-er0** [ultralytics/yolov5#8736]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training, Validation, Detection

### Bug

My training and inference times gradually increase between the epochs and samples. 

For example, my inference time is 0.054s initially but after 400 samples it increases to 0.1s then it becomes 0.54s and finally stabilizes at 2.1s. Same thing is happening during the training and validations too. Batches gets longer to train&validate. 

### Environment

YOLO: YOLOv5 V6.1, Python -3.9.9, torch 1-.10.2+cu113 CUDA:0 (NVIDIA GeForce RTX 2070, 8192MiB)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@abrek-er0 sounds like thermal throttling on your local GPUs. You might try a remote environment like Google Colab or Kaggle with free GPUs to resolve this issue or work on better cooling solutions.

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

**Comment by abrek-er0** [comment]
@glenn-jocher  My performance is increased with better cooling settings, thank you!

**Comment by glenn-jocher** [comment]
@abrek-er0 glad to hear the improved performance! The YOLO community and the Ultralytics team are always happy to help. If you have any more questions or need further assistance, feel free to reach out anytime.
