### ISSUE TITLE
No Bounding Boxes

### ISSUE THREAD

**Issue by rexayyy** [ultralytics/yolov5#8738]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

Hello there, Glenn. I have trained the model following your custom dataset training tutorial using a roboflow notebook in colab and prepared the dataset using roboflow. The model was successfully trained using Colab Pro but while validating it, it is not showing any bounding boxes around the images.

### Additional

<img width="850" alt="Annotation 2022-07-27 143048" src="https://user-images.githubusercontent.com/97718899/181213808-f77d13a5-cb7a-48c8-978c-168396eccbc6.png">
<img width="1321" alt="Annotation 2022-07-27 143215" src="https://user-images.githubusercontent.com/97718899/181214170-ef77d46e-e25c-4cb8-b66b-451642d4f678.png">

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by rexayyy** [comment]
#clone YOLOv5 and 
!git clone https://github.com/ultralytics/yolov5  # clone repo
%cd yolov5
%pip install -qr requirements.txt # install dependencies
%pip install -q roboflow

import torch
import os
from IPython.display import Image, clear_output  # to display images

print(f"Setup complete. Using torch {torch.__version__} ({torch.cuda.get_device_properties(0).name if torch.cuda.is_available() else 'CPU'})")


from roboflow import Roboflow
rf = Roboflow(model_format="yolov5", notebook="ultralytics")


os.environ["DATASET_DIRECTORY"] = "/content/datasets"

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="HGjETJgXAvDQOgCOfvBk")
project = rf.workspace("xyz").project("fyp-wmjjh") // the personal-key is set to xyz for privacy reasons
dataset = project.version(1).download("yolov5")


!python train.py --img 416 --batch 16 --epochs 200 --data /content/datasets/FYP-1/data.yaml --weights yolov5s.pt --cache

!python detect.py --weights runs/train/exp/weights/best.pt --img 416 --conf 0.9 --source {dataset.location}/test/images


import glob
from IPython.display import Image, display

for imageName in glob.glob('/content/datasets/FYP-1/valid/images/*.jpg'): #assuming JPG
    display(Image(filename=imageName))
    print("\n")

/////That is the code////

but when i run the last cell of the code it have no bounding boxes

<img width="404" alt="Annotation 2022-07-27 145303" src="https://user-images.githubusercontent.com/97718899/181218879-cb86433a-299f-4777-8249-a1950b18a586.png">

**Comment by glenn-jocher** [comment]
@rexayyy you're just visualizing empty images. Annotated images are saved to runs/detect/exp

**Comment by Rohan-Python** [comment]
I am facing same issue of not getting bounding boxes while inferencing on System GPU. I have trained this model on google colab and got the best.pt file. Used that file in detect.py for inferencing and I am not getting any bounding boxes.

**Comment by MVVENTO** [comment]
I am getting a similar issue, whereas before the bounding boxes would show and now they are showing up empty. Is this a more recent bug since YOLOv8 is getting updated? or am I missing something?

**Comment by codingzebra333** [comment]
I have the same issue with YOLOv7 on GPU. No bounding box on images using yolov7 weights that are provided on github.

**Comment by Rohan-Python** [comment]
> I have the same issue with YOLOv7 on GPU. No bounding box on images using yolov7 weights that are provided on github.

Which version of pytorch, cuda and tensorflow are you using?

**Comment by codingzebra333** [comment]
I changed the value to half = False in line 31 of detect.py and it fixed the issue. 
I have Pytorch version 1.11  and Cuda version 11.3.

**Comment by EmmaOoremmie** [comment]
> I am facing same issue of not getting bounding boxes while inferencing on System GPU. I have trained this model on google colab and got the best.pt file. Used that file in detect.py for inferencing and I am not getting any bounding boxes.

**Comment by glenn-jocher** [comment]
@codingzebra333 Glad to hear that you found a solution! Feel free to open a Pull Request with your fix, and we'll take a look at it. Thanks for sharing your workaround!

**Comment by 7eng7** [comment]
@codingzebra333  Thank you very much for your response. I encountered this issue when running the YOLOv5 5.0 official demo. I was able to detect images correctly on CPU, but I couldn't get any detections on GPU. This has been bothering me for a long time until I saw your comment. Thank you so much!!!
