### ISSUE TITLE
Which visualizer should I choose

### ISSUE THREAD

**Issue by nuonuofenfen** [ultralytics/yolov5#8739]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

1、Is your visualization that the selection is tensorboard running on the CPU and the wandb selected on the GPU? If I want to use tensorboard and don't want to use wandb, how do I make changes in the code or pycharm terminal?
2、At the same time, I don't know what causes me to always show failures when downloading weights. Could it be that I used wandb before? Or is it a problem with the configuration of my own environment

### Additional

Graphics and version：YOLOv5  2022-7-27 Python-3.8.12 torch-1.10.2 CUDA:0 (NVIDIA GeForce RTX 3090, 24576MiB)

**Comment by nuonuofenfen** [comment]
D:\Anaconda\envs\cyb\python.exe D:/wc/gpu/yolov5-master/train.py
<frozen importlib._bootstrap>:219: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
wandb: Currently logged in as: nuonuofenfen. Use `wandb login --relogin` to force relogin
github: skipping check (not a git repository), for updates see https://github.com/ultralytics/yolov5
train: weights=yolov5s.pt, cfg=, data=data\coco128.yaml, hyp=data\hyps\hyp.scratch-low.yaml, epochs=300, batch_size=16, imgsz=640, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, noplots=False, evolve=None, bucket=, cache=None, image_weights=False, device=, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=8, project=runs\train, name=exp, exist_ok=False, quad=False, cos_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, seed=0, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest
YOLOv5  2022-7-27 Python-3.8.12 torch-1.10.2 CUDA:0 (NVIDIA GeForce RTX 3090, 24576MiB)

hyperparameters: lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0
TensorBoard: Start with 'tensorboard --logdir runs\train', view at http://localhost:6006/
wandb: Tracking run with wandb version 0.12.21
wandb: Run data is saved locally in D:\wc\gpu\yolov5-master\wandb\run-20220727_180835-260rbwdp
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run woven-terrain-13
wandb:  View project at https://wandb.ai/nuonuofenfen/train
wandb:  View run at https://wandb.ai/nuonuofenfen/train/runs/260rbwdp
YOLOv5 temporarily requires wandb version 0.12.10 or below. Some features may not work as expected.
Downloading https://github.com/ultralytics/yolov5/releases/download/v6.1/yolov5s.pt to yolov5s.pt...
 51%|█████▏    | 7.27M/14.1M [15:24<14:31, 8.24kB/s]

Traceback (most recent call last):
  File "D:/wc/gpu/yolov5-master/train.py", line 642, in <module>
    main(opt)
  File "D:/wc/gpu/yolov5-master/train.py", line 537, in main
    train(opt.hyp, opt, device, callbacks)
  File "D:/wc/gpu/yolov5-master/train.py", line 119, in train
    ckpt = torch.load(weights, map_location='cpu')  # load checkpoint to CPU to avoid CUDA memory leak
  File "D:\Anaconda\envs\cyb\lib\site-packages\torch\serialization.py", line 600, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "D:\Anaconda\envs\cyb\lib\site-packages\torch\serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
wandb: Waiting for W&B process to finish... (failed 1). Press Ctrl-C to abort syncing.
wandb:                                                                                
wandb: Synced woven-terrain-13: https://wandb.ai/nuonuofenfen/train/runs/260rbwdp
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: .\wandb\run-20220727_180835-260rbwdp\logs

Process finished with exit code 1

**Comment by glenn-jocher** [comment]
@nuonuofenfen you can disable or delete wandb with `wandb disabled` or `pip uninstall wandb`

Partial downloads would be due to network connectivity issues on your end.
