### ISSUE TITLE
yolov5x summary

### ISSUE THREAD

**Issue by davidcg96** [ultralytics/yolov5#8740]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

i loaded yolov5x model and when i check this summary and compare whit yolov5x.yaml is different. 
first conv2d layer is  Conv2d(3, 80, kernel_size=(6, 6), stride=(2, 2), padding=(2, 2)) and in yaml file is 
Backbone:
  #[from, number, module, args]
  [[-1, 1, Conv, [64, 6, 2, 2]],  # 0-P1/2

check this picture:
![Captura de pantalla (106)](https://user-images.githubusercontent.com/49916234/181224027-3eba5e27-ab6e-463c-b2cd-6967f093cf4e.png)

what is correct?

**Comment by glenn-jocher** [comment]
@davidcg96 depth and width multiples are applied to all channels and repeatable modules like C3 etc:
https://github.com/ultralytics/yolov5/blob/0b5ac224aef287ac3ac9ebf70ade60159450a0b1/models/yolov5x.yaml#L5-L6
