### ISSUE TITLE
ONNX DNN inference bug: (-215:Assertion failed) inputs.size() in function 'getMemoryShapes'

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/yolov5#8744]
I followed the tutorial to OpenCV inference with ONNX models， but it has some problems.
![1658932624846](https://user-images.githubusercontent.com/50489319/181275265-46d1e5f1-4ded-412a-9c35-8b5ea88b3322.png)

_Originally posted by @longtimenoseeyou in https://github.com/ultralytics/yolov5/issues/251#issuecomment-1196846396_

Reproduce:
```python
!python export.py --include onnx
!python detect.py --weights yolov5s.onnx --dnn
```

**Comment by glenn-jocher** [comment]
@longtimenoseeyou I would raise this issue directly on the opencv repository as the error originates in cv2.

**Comment by glenn-jocher** [comment]
@longtimenoseeyou in #8439 it looks like this issue is related to torch==1.12 and downgrading to torch<=1.11.0 will resolve the bug.

**Comment by longtimenoseeyou** [comment]
Thank you, Glenn, I solve the problem

**Comment by knoppmyth** [comment]
@longtimenoseeyou How did you solve this? Was it downgrading to 1.11? While that works, I cannot then train with 1.11 as it errors. At this point, I'd have to train w/ 1.12 then have another environment w/ 1.11 to export.

**Comment by longtimenoseeyou** [comment]
@knoppmyth Yeah, I downgraded to torch ==1.11. Now I train datasets normally and do not see any other problem

**Comment by longtimenoseeyou** [comment]
At the end of training with torch=1.11 , I get the error:
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'

**Comment by knoppmyth** [comment]
@longtimenoseeyou I went back to an older container and notes... The error you get at the end of training w/ 1.11.0 is non-fatal.

**Comment by elw1ng** [comment]
> @longtimenoseeyou in #8439 it looks like this issue is related to torch==1.12 and downgrading to torch<=1.11.0 will resolve the bug.
![image](https://user-images.githubusercontent.com/57170052/210369746-c8516d88-4c97-4695-b1f0-74726cf78141.png)
i got this error ONNX: export failure  0.0s: Unsupported ONNX opset version: 17
when tried to export onnx model from pt after downgraded to torch==1.11.0
on default version i got this error, even on colab 
![image](https://user-images.githubusercontent.com/57170052/210360740-20cf714e-9a96-41d8-9260-05eb2a26e26f.png)

**Comment by fangfap** [comment]
python export.py --weights models/yolov5n.pt --opset 11 --include onnx
downgrade opset to 11 work for me :))

**Comment by glenn-jocher** [comment]
@fangfap great to hear that downgrading the ONNX opset version to 11 resolved the issue for you! Thank you for sharing your solution.
