### ISSUE TITLE
yolov5 training with dataset

### ISSUE THREAD

**Issue by talttt** [ultralytics/yolov5#875]
## ❔Question
i have 3 classes in my dataset. if some of the images consists unlabeled class, does it harm the training?

## Additional context
when the net trying to learn the dataset does it get images of tagged blocks or the whole image?

**Comment by glenn-jocher** [comment]
Whole image. Recommend you start from the custom training tutorial.

**Comment by talttt** [comment]
the question is if i dont label an object in some images of the dataset would it harm the training?
for example if im trying to classify cats and dogs and some images have dogs that i didnt labal, would it harm the training or it has no effect?
(i have read the tutorial but did not find that answer).
thanks

**Comment by glenn-jocher** [comment]
@talttt of course it harms training. You're training the network that there is no dog there.

**Comment by talttt** [comment]
thank you very much
