### ISSUE TITLE
cv2.imshow() is disabled in Docker environments

### ISSUE THREAD

**Issue by Heartful-echo** [ultralytics/yolov5#8752]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I ran YOLO v5 from a docker container.

It worked fine a week ago, but when I try it today, I don't see the GUI.

A warning is output as shown below.
WARNING: Environment does not support cv2.imshow() or PIL Image.show() image displays
cv2.imshow() is disabled in Docker environments

I used the following command when creating a container
![p1](https://user-images.githubusercontent.com/56055010/181414858-46f4bda8-c595-4437-8c6b-5ffd8f5ee8f5.PNG)
.
sudo docker run -it --rm --runtime nvidia --network host --device=/dev/video0:/dev/video0:rwm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix/:/tmp/.X11-unix: -v /home/users/Desktop/work/yolov5:/yolov5 nvcr.io/nvidia/l4t-pytorch:r32.7.1-pth1.9-py3 bin/bash

I have also pre-run "xhost + local :" command.

How do I get the GUI to appear?

**Comment by barney2074** [comment]
Are you sure it worked before?
It never has for me- I thought it was just a limitation of Docker/OpenCV

**Comment by Heartful-echo** [comment]
Yes, YOLO v5 worked from the Docker container in the first half of July.
by the way,
I'm using Raspberry Pi 4 to run YOLO v5 from Docker. So opencv is available on Docker.

**Comment by Heartful-echo** [comment]
It worked when I changed to v6.1 of YOLO v5.
If the master version of  YOLOv5 is Jetson's NGC container, the GUI will not work.

![p2](https://user-images.githubusercontent.com/56055010/181658141-66c36be2-7974-4e89-a09f-6b58e0ccf2df.PNG)

**Comment by glenn-jocher** [comment]
@kazuya-uchida did you resolve this successfully? Are there any changes we could make to detect.py or the dockerfile to improve this?

**Comment by Heartful-echo** [comment]
@glenn-jocher 
I don't understand the YOLOv5 code, so I can't change it....
But...
I would like to try it someday.

**Comment by MOXHAN** [comment]
Has this been solved or is there an easy solution I could use in my docker run command or add to the Dockerfile? Im having the same problem, when using dusty-nv's Hello AI World container

**Comment by Heartful-echo** [comment]
@MOXHAN 

I was able to do it by copying the steps from the website below.
https://note.com/echo_device/n/nab1356831c10

**Comment by glenn-jocher** [comment]
@MOXHAN,

Thank you for reaching out. To enable GUI support in your Docker container, you can follow the steps mentioned in the website you provided: https://note.com/echo_device/n/nab1356831c10.

Please note that enabling GUI support in Docker containers can be a bit complex, and it may not work with all containers. However, the steps mentioned in the website seem to have worked for some users.

If you have any further questions or issues, please feel free to ask.

**Comment by Shinechaote** [comment]
Does someone still know the solution from the website? As far as I can tell the post on the website has been put behind a paywall.

**Comment by pderrenger** [comment]
I recommend checking the YOLOv5 Docker tutorial for guidance: https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/. It may offer alternative solutions for GUI support in Docker.
