### ISSUE TITLE
yolov5 position value automatically calculate

### ISSUE THREAD

**Issue by oes5756** [ultralytics/yolov5#8754]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

demand "--save-txt"
First, set the reference coordinates after that
Based on the coordinates that are detected with the bounding box,
Is it possible to automatically calculate a value that is the same as the reference coordinate when it is different from the reference coordinate?
For example, if the reference coordinate 'x' is 0.5 'y' is 0.5
For the coordinates of the image detected by the bounding box, is 'x' is 0.2 'y' is 02 automatic calculation operation possible on the system when x+0.3 y+0.3?

**Comment by glenn-jocher** [comment]
@oes5756 hello! You can achieve the automatic calculation of the detected bounding box coordinates relative to a reference coordinate by post-processing the inference results with custom code. After obtaining the bounding box coordinates, you can perform the necessary calculations to adjust them based on the reference coordinate. Check out the Ultralytics Docs for guidance on post-processing inference results. Let us know if you need further assistance!
