### ISSUE TITLE
Source-Free compression training on YOLOv5s

### ISSUE THREAD

**Issue by leiqing1** [ultralytics/yolov5#8755]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Hello, we have done a Source-Free compression training function, and the benefits of YOLOv5s are as follows. I want to submit a PR, is it ok?
| model | method | input size | mAPval 0.5:0.95 | prediction delay FP32 (ms) | prediction delay FP16 (ms) | prediction delay INT8 (ms) | 
 | -- | -- | -- | -- | -- | -- | -- | 
 | YOLOv5s | Base | 640*640 | 37.4 | 5.95ms | 2.44ms | - | 
 | YOLOv5s | KL Offline quantification | 640*640 | 36.0 | - | - | 1.87ms | 
 | YOLOv5s | Quantitative distillation training | 640*640 | 36.9 | - | - | 1.87ms | 

We use the training knowledge technology and PACT quantization technology to improve the compression efficiency of YOLOv5s.Knowledge distillation techniques can automatically add training logic to AI models. First, it loads the inference model file specified by the user, and copies the AI model in memory as the teacher model in knowledge distillation, and the original model as the student model. Then, the model structure is automatically analyzed to find a layer suitable for adding distillation loss, usually the last layer with trainable parameters. Finally, the teacher model supervises the sparse training or quantized training of the original model through the distillation loss. The process is shown in the figure below.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@leiqing1 very interesting! Thanks for sharing your results!
