### ISSUE TITLE
Transfer learning on first two layers keeping remaining layers' weights fixed

### ISSUE THREAD

**Issue by spaul13** [ultralytics/yolov5#8757]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is there any way to train weights for the first two layers while keeping remaining layers' weights at frozen state.

**Comment by glenn-jocher** [comment]
@spaul13 that's pretty funny, yes you can customize freezing code here. The default code does the opposite of what you ask for, it freezes earlier layers up to a point, i.e. python train.py --freeze 10 will freeze the first 10 layers and allow the head to learn a new dataset with transfer learning.

https://github.com/ultralytics/yolov5/blob/e309a855860bc3f618c3541909c515a65ffc35b0/train.py#L130-L137
