### ISSUE TITLE
scale_coords

### ISSUE THREAD

**Issue by Mumm77** [ultralytics/yolov5#8758]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

these are the two functions in question:
they can be found in the
[yolov5-github-repository](https://github.com/ultralytics/yolov5/blob/master/utils/general.py)
(https://github.com/ultralytics/yolov5/blob/master/utils/general.py)

```
def scale_coords(img1_shape, coords, img0_shape, ratio_pad=None):
    # Rescale coords (xyxy) from img1_shape to img0_shape
    if ratio_pad is None:  # calculate from img0_shape
        gain = min(img1_shape[0] / img0_shape[0], img1_shape[1] / img0_shape[1])  # gain  = old / new
        pad = (img1_shape[1] - img0_shape[1] * gain) / 2, (img1_shape[0] - img0_shape[0] * gain) / 2  # wh padding
    else:
        gain = ratio_pad[0][0]
        pad = ratio_pad[1]

    coords[:, [0, 2]] -= pad[0]  # x padding
    coords[:, [1, 3]] -= pad[1]  # y padding
    coords[:, :4] /= gain
    clip_coords(coords, img0_shape)
    return coords
```

```
def clip_coords(boxes, shape):
    # Clip bounding xyxy bounding boxes to image shape (height, width)
    if isinstance(boxes, torch.Tensor):  # faster individually
        boxes[:, 0].clamp_(0, shape[1])  # x1
        boxes[:, 1].clamp_(0, shape[0])  # y1
        boxes[:, 2].clamp_(0, shape[1])  # x2
        boxes[:, 3].clamp_(0, shape[0])  # y2
    else:  # np.array (faster grouped)
        boxes[:, [0, 2]] = boxes[:, [0, 2]].clip(0, shape[1])  # x1, x2
        boxes[:, [1, 3]] = boxes[:, [1, 3]].clip(0, shape[0])  # y1, y2
```

################################
In the yolov5 github repository, there are these two functions which i dont completely understand, but as far as I understood them the first one doesnt fulfill its job and the second one doesnt even return anything.
Im mainly asking about the first one, and the second one is just included in the first one, so maybe there is a important connection i didnt see.

So here my questions:
Is the first one actually rescaling xyxy to xyxy from old image_shape1 to new image_shape0 ?
to rescale, wouldnt something like this do the job ?

```
def scale_coords_new(img1_shape, coords, img0_shape):
    # Rescale coords (xyxy) from img1_shape to img0_shape
    gain_y, gain_x = (img0_shape[0] / img1_shape[0], img0_shape[1] / img1_shape[1])  # gain  = old / new
    coords[:, [0, 2]] *= gain_x  # x padding
    coords[:, [1, 3]] *= gain_y  # y padding
    return coords
```

**Comment by glenn-jocher** [comment]
@Mumm77 these functions scale and clip images and labels. Some python ops modify variables in place rather than returning values.

If you spot any bugs please submit a bug report to reproduce, or if you spot any areas for speed or code improvements please submit a PR with before and after results. Thank you!

**Comment by Mumm77** [comment]
thanks for the answer

**Comment by newacronym** [comment]
the above function is removed? why?

**Comment by glenn-jocher** [comment]
@newacronym renamed to scale_boxes, scale_segments introduced.

**Comment by Maioy97** [comment]
I think it was renamed to scale_box

**Comment by glenn-jocher** [comment]
@Maioy97 yes, you are correct. The function has been renamed to `scale_box`. Thank you for pointing that out!

**Comment by ZubairKhan001** [comment]
yes scale_boxes

**Comment by glenn-jocher** [comment]
Thank you for confirming. If you have any further questions or need assistance with `scale_box`, feel free to ask!
