### ISSUE TITLE
about the yolov5 

### ISSUE THREAD

**Issue by pokaryosy** [ultralytics/yolov5#8759]
Hello,

I would like to ask about the yolov5 source.
I would like to detect objects on my computer screen in realtime. 
Is that possible?
I'm using mac and running at local.

I don't want to detect only a single screenshot, I want to detect what is continuously on the screen, like object detection with a webcam.

_Originally posted by @pokaryosy in https://github.com/ultralytics/yolov5/discussions/8239_

It seems that the information he shared is not enough to solve the problem, but can anyone else come up with a solution?

**Comment by DavidLandup0** [comment]
A quick google yields the answer, and could be modified to something along the lines of:

```python
import numpy as np
import cv2
from mss import mss
from PIL import Image

bounding_box = {'top': 100, 'left': 0, 'width': 400, 'height': 300}

sct = mss()

while True:
    sct_img = sct.grab(bounding_box)
    # run inference on sct_img
    results = model(sct_img)
    cv2.imshow('YOLO',  np.squeeze(results.render()))

    if (cv2.waitKey(1) & 0xFF) == ord('q'):
        cv2.destroyAllWindows()
        break
```

**Comment by glenn-jocher** [comment]
@DavidLandup0 hey there! 👋 

To achieve real-time object detection on your Mac screen, you can use YOLOv5 in combination with Python libraries such as OpenCV and MSS. Here's a basic outline to get you started:

```python
import numpy as np
import cv2
from mss import mss

bounding_box = {'top': 100, 'left': 0, 'width': 400, 'height': 300}

sct = mss()

while True:
    sct_img = sct.grab(bounding_box)
    # run YOLOv5 inference on sct_img
    results = model(sct_img)
    cv2.imshow('YOLO',  np.squeeze(results.render()))

    if (cv2.waitKey(1) & 0xFF) == ord('q'):
        cv2.destroyAllWindows()
        break
```

This code captures a portion of the screen using MSS, runs YOLOv5 inference on the captured image, and displays the results using OpenCV. You can modify the `bounding_box` to define the area of the screen you want to monitor.

Hope this helps! If you need further assistance, feel free to ask. Good luck!
