### ISSUE TITLE
'Model' has no attribute 'copy'

### ISSUE THREAD

**Issue by parthmalpathak** [ultralytics/yolov5#8768]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,

I am trying to implement YOLOv5 as a detector to ByteTrack. But when I load YOLOv5, I am getting an attribute error saying there is no attribute called 'copy'.

Any suggestions for this issue?

**Comment by parthmalpathak** [comment]
Update: Solved.

**Comment by glenn-jocher** [comment]
@parthmalpathak great to hear that you were able to resolve the issue! If you have any further questions or need assistance, feel free to ask. Good luck with your implementation!

**Comment by JoelC-02** [comment]
@parthmalpathak I got same error, can u explain how you solved it
