### ISSUE TITLE
Resize Video stream

### ISSUE THREAD

**Issue by daynial132** [ultralytics/yolov5#877]
Hello

I loved the work you did. and it is very better in speed and accuracy then all before yolo models
I just need to ask that I have run the detect.py with my home IP camera that have stream size 1980*1280
which makes system slow. I want to resize the stream through code how is it possible?

Thank you

**Comment by glenn-jocher** [comment]
@daynial132 someone else asked this before also. The actual streaming commands I think are customizable to a certain point, depending on the stream source, but this is solely a cv2 issue, unrelated to YOLOv5. The cv2 commands that you would want to modify are here:
https://github.com/ultralytics/yolov5/blob/08e97a2f884a9090abb890298dd1d47611a3e249/utils/datasets.py#L235-L246

The actual inference size is set by detect.py, and is independent of the stream size:
https://github.com/ultralytics/yolov5/blob/08e97a2f884a9090abb890298dd1d47611a3e249/detect.py#L154

**Comment by daynial132** [comment]
thank you for reply. 
I have tries cv2.resize command after cap.read command but there is no difference on system

Also I have tried to change the --img-size to minimum but still there is no effect on image size

**Comment by glenn-jocher** [comment]
@daynial132 you want to raise an issue on the cv2 repo then.

**Comment by daynial132** [comment]
I have solved the issue by adding the line 
" self.imgs[index]  =  cv2.resize(self.imgs[index], (0, 0), fx=0.5, fy=0.5)" to dataset.py file  under the line 
_, self.imgs[index] = cap.retrieve() in  function def update(self, index, cap):

**Comment by itsjustrafli** [comment]
Hello, @daynial132! On what script did you put those line of code into? dataset.py? Apparently I ran the same problem and I wanted to know, can you explain it?

Thanks in advance!

**Comment by glenn-jocher** [comment]
@itsjustrafli glad to hear that you were able to solve the issue! Thank you for sharing your solution with us. Your approach of adding the line "self.imgs[index] = cv2.resize(self.imgs[index], (0, 0), fx=0.5, fy=0.5)" to the dataset.py file under the line "_, self.imgs[index] = cap.retrieve()" in the `update` function seems to have worked for you. This will resize the image to half of its original size. Let us know if you have any further questions or issues.

**Comment by b4u365** [comment]
this command has helped to resize the cv2 video stream to full screen                                                                                             
 im = letterbox(im0, [640,640], stride=32, auto=1)[0], 
you can change 640,640  to size the pop up video stream, but it will zoom the image.
you can import letter box from augmentations 
from utils.augmentations import letterbox

**Comment by glenn-jocher** [comment]
@b4u365 hi there,

Thank you for sharing your solution with us. The command you mentioned, `im = letterbox(im0, [640,640], stride=32, auto=1)[0]`, is indeed useful for resizing the cv2 video stream to full screen. By changing the values `[640, 640]`, you can adjust the size of the pop-up video stream. However, it's important to note that changing these values will result in zooming the image. To use the `letterbox` function, you can import it from the `utils.augmentations` module. 

If you have any further questions or need assistance, feel free to ask.

Best regards.
