### ISSUE TITLE
Confusion Matrix for Detect.py

### ISSUE THREAD

**Issue by pjborad** [ultralytics/yolov5#8770]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am trying to calculate the confusion matrix after getting the output from detect.py (text files). I also have the actual label files (in .txt format).

**Comment by glenn-jocher** [comment]
@pjborad val.py creates confusion matrices automatically, I'd use that.

**Comment by pjborad** [comment]
I did try but I want to use agnostic NMS while detecting the bounding boxes. The results are not same when I provided Agnostic = True in val.py.

**Comment by glenn-jocher** [comment]
@pjborad Agnostic NMS can affect the results. Confusion matrices typically use standard NMS for evaluation. However, you can modify val.py to include agnostic NMS and then calculate your confusion matrix.
