### ISSUE TITLE
Anchors excluded if using --weight and --cfg 

### ISSUE THREAD

**Issue by UnglvKitDe** [ultralytics/yolov5#8771]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hey,
why are the anchors excluded when loading the weights and cfg even if they have identical shapes?

https://github.com/ultralytics/yolov5/blob/master/train.py#L121

### Additional

`python train.py --weights yolov5n.pt --cfg yolov5n.yaml`

**Comment by glenn-jocher** [comment]
@UnglvKitDe if a cfg is passed anchors are selected from the cfg.

**Comment by UnglvKitDe** [comment]
@glenn-jocher Exactly, but if they do have the same shape, why not load the weights? Or do you mean that they could be different types of classes as in the weights?

**Comment by glenn-jocher** [comment]
@UnglvKitDe yeah the --weights and --cfg could be substantially different, i.e. different class counts and even different sizes or architectures, in which case only matching layers with same names and shapes will transfer. If you want to use the same anchors with --eights just pass --weights with no --cfg.
```
python train.py --weights yolov5s.pt
```

**Comment by UnglvKitDe** [comment]
@glenn-jocher Thx :)

**Comment by glenn-jocher** [comment]
@UnglvKitDe you're welcome! If you have any more questions, feel free to ask. Good luck with your project!
