### ISSUE TITLE
Img-size Rectangular

### ISSUE THREAD

**Issue by buimanhlinh96** [ultralytics/yolov5#878]
Hi,
Thanks for your enthusiasm support.
I have a question. My original image size is 1920x1080. How can i train with rectangular size with the ratio of W/H not changed (16/9). Initially, my commands like that: --img-size 800 448. But when i read all the issues related to img-sized, it is wrong.
Can you explain it to me?
Thanks

**Comment by glenn-jocher** [comment]
`python train.py --rect`

**Comment by buimanhlinh96** [comment]
@glenn-jocher: For example if i command python train.py --img-size 800 --rect then the first step is resizing 1920 to 800 (W), and the second step is resizing 1080 (W) to a value which keep the W/H ratio constistently (16/9). Is that right?

**Comment by zhayanli** [comment]
Hello buimanhlinh96, you run with --rect for single gpu or multiple gpus?

**Comment by buimanhlinh96** [comment]
@zhayanli i run with multiple gpus (parralel mode)

**Comment by zhayanli** [comment]
OK, you run with --rect got better result then without --rect?

**Comment by buimanhlinh96** [comment]
@zhayanli as my new issue you can check, while training i look at the log then the mAP when use --rect is better than without --rect (about 6%). But when infrence, run with --rect lost 5% compare to without --rect. I dont know the reason.
