### ISSUE TITLE
How do I run CSI camera on YOLOV5?

### ISSUE THREAD

**Issue by medic-lab** [ultralytics/yolov5#8786]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,
I can run CSI camera on Jetson Xavier NX without a specific purpose but when i trying to run the camera with YoloV5. I'm having issues because the camera is not defined in YoloV5.

**Comment by glenn-jocher** [comment]
@medic-lab connected webcams are generally accessed via their indices, i.e.

```
python detect.py --source 0
python detect.py --source 1
python detect.py --source 2
...
```

**Comment by medic-lab** [comment]
Well, my camera is not considered as a webcam. It's not connected via USB so `--source 0` or above doesn't work for me. CSI cameras have different port but i don't know how to define it on YoloV5. 

I can only run the camera with the code below on terminal:
`gst-launch-1.0 nvarguscamerasrc sensor_id=0 ! 'video/x-raw(memory:NVMM),width=3820, height=2464, framerate=21/1, format=NV12' ! nvvidconv flip-method=0 ! 'video/x-raw,width=960, height=616' ! nvvidconv ! nvegltransform ! nveglglessink -e` 

![WhatsApp Image 2022-07-30 at 16 36 38](https://user-images.githubusercontent.com/84999910/181916871-5fd4a996-62a4-4e33-a53d-dbcc543c1710.jpeg)

**Comment by glenn-jocher** [comment]
I'm sorry, I don't have experience with those cameras.

**Comment by ToshiNandanReddy** [comment]
Any information on how to use ip cameras as source?

**Comment by sriramreddyM** [comment]
> Well, my camera is not considered as a webcam. It's not connected via USB so `--source 0` or above doesn't work for me. CSI cameras have different port but i don't know how to define it on YoloV5.
> 
> I can only run the camera with the code below on terminal: `gst-launch-1.0 nvarguscamerasrc sensor_id=0 ! 'video/x-raw(memory:NVMM),width=3820, height=2464, framerate=21/1, format=NV12' ! nvvidconv flip-method=0 ! 'video/x-raw,width=960, height=616' ! nvvidconv ! nvegltransform ! nveglglessink -e`
> 
> ![WhatsApp Image 2022-07-30 at 16 36 38](https://user-images.githubusercontent.com/84999910/181916871-5fd4a996-62a4-4e33-a53d-dbcc543c1710.jpeg)

@medic-lab To use CSI camera on jetson, follow [it.](https://github.com/JetsonHacksNano/CSI-Camera/blob/23229353bb06af995202fed311e9886066fbce05/simple_camera.py#L17) I tested it on jetson nano 4GB and its working smooth.

**Comment by sriramreddyM** [comment]
> Any information on how to use ip cameras as source?

@ToshiNandanReddy  It accepts url as source with any of the protocol from the four mentioned [here.](https://github.com/ultralytics/yolov5/blob/2e10909905b1e0e7eb7bac086600fe7ee2c0e6a5/detect.py#L82)

**Comment by ToshiNandanReddy** [comment]
> @sriramreddyM 

I have an IP address not a url...

**Comment by sriramreddyM** [comment]
> > @sriramreddyM
> 
> I have an IP address not a url...

and what is the streaming protocol? just use ip address as url, it should work if the streaming protocol is correctly mentioned .

**Comment by ToshiNandanReddy** [comment]
> > > @sriramreddyM
> > 
> > 
> > I have an IP address not a url...
> 
> and what is the streaming protocol? just use ip address as url, it should work if the streaming protocol is correctly mentioned .

it has both http and rtsp...

**Comment by sriramreddyM** [comment]
> > > > @sriramreddyM
> > > 
> > > 
> > > I have an IP address not a url...
> > 
> > 
> > and what is the streaming protocol? just use ip address as url, it should work if the streaming protocol is correctly mentioned .
> 
> it has both http and rtsp...

Did you try using ip as uri, if so isn't it working? and are you using Gstreamer on jetson for streaming over ip?

**Comment by SIeep-coder** [comment]
> Hello, I would like to ask if you have ever tried to use yolov5 to call the csi camera

**Comment by medic-lab** [comment]
> > Well, my camera is not considered as a webcam. It's not connected via USB so `--source 0` or above doesn't work for me. CSI cameras have different port but i don't know how to define it on YoloV5.
> > I can only run the camera with the code below on terminal: `gst-launch-1.0 nvarguscamerasrc sensor_id=0 ! 'video/x-raw(memory:NVMM),width=3820, height=2464, framerate=21/1, format=NV12' ! nvvidconv flip-method=0 ! 'video/x-raw,width=960, height=616' ! nvvidconv ! nvegltransform ! nveglglessink -e`
> > ![WhatsApp Image 2022-07-30 at 16 36 38](https://user-images.githubusercontent.com/84999910/181916871-5fd4a996-62a4-4e33-a53d-dbcc543c1710.jpeg)
> 
> @medic-lab To use CSI camera on jetson, follow [it.](https://github.com/JetsonHacksNano/CSI-Camera/blob/23229353bb06af995202fed311e9886066fbce05/simple_camera.py#L17) I tested it on jetson nano 4GB and its working smooth.

I can use CSI camera but i can't use it on Yolov5 as a source

**Comment by Rusali28** [comment]
@medic-lab Hey, I am facing a similar difficulty, were you able to integrate the csi camera into the yolov5? If yes, then please help me understand how we can do it
@sriramreddyM I did follow the jetson-hack-csi-camera module that you had linked in the previous comments, but I am unable to figure out how to insert the code in the yolov5 detect file, if you have done it, can you kindly explain how?

Thank you!

**Comment by sriramreddyM** [comment]
@Rusali28 if you have to use "detect.py" file you have write a custom method in dataloaders to read frames from CSI camera.
Instead I wrote own method for detection, following the same method as "jetson-hack-csi-camera" to read frames from CSI camera using opencv. Please find the [sample code](https://github.com/gicait/pLitter/blob/main/plitter/stationCam.py) for your reference.

**Comment by Rusali28** [comment]
@sriramreddyM Thank you for sharing the sample code! I went through it and tried to understand. 
However, since I am using a custom made dataset, I need to use the detect.py file to perform the accurate yolov5 predictions. I figured that we have to change the dataloaders file to read frames from the CSI camera, but I am unable to figure out how to do it. Can you please help me understand how we can make the custom method in dataloaders to read the csi-camera?
Are there any sample references for those?
Or can we modify the current LoadStreams class in the dataloaders file so that it can read the frames from csi-camera?
Please do let me know, thank you for your help!

**Comment by sriramreddyM** [comment]
yolov5 detections will remain the same if you write your own inference script, as long as you use the same weights and follow the same pre-processing steps as in the dataloaders. This approach is easier and allows for more customization with the detection results.

If you insist to use the detect.py file, you will need to modify the LoadStreams function to add support for CSI cameras. In LoadStreams, the usual case for web cameras is to use the sensor ID from arguments will be used at [cv2.VideoCapture(s)](https://github.com/ultralytics/yolov5/blob/3e55763d45f9c5f8217e4dad5ba1e6c1f42e3bf8/utils/dataloaders.py#L366), but for CSI cameras, you should use a string as shown [here](https://github.com/gicait/pLitter/blob/ad1685668c313e88d67210a15a2f163382599789/plitter/stationCam.py#L26). You may also need to add an argument (--csi_cam) to detect.py to pass to LoadStreams to distinguish between usb-cam and csi-cam.

Please note that OpenCV must be built with gStreamer support to use the CSI camera. I have tested using CSI camera and yolov5 together, only with the Nvidia Jetson Nano.

**Comment by Rusali28** [comment]
@sriramreddyM I understand your suggestion on writing our own inference script, however since I am relatively new to computer vision, I am a little unsure of how to write an inference script for yolov5 on my own. Can you help me understand if there are ways or resources to do it?

Also, since I am nearing a deadline, I was trying to use the detect.py as I have already modified it a bit to print results. But I do want to try both the ways (using current detect.py and the inference script). As of now, I am trying to modify the LoadStreams function - I made the changes you suggested, but the detect file doesnt seem to run. Can you please have a look at the changes I made? Am I missing something here?


Yes, I am also trying to test the CSI Camera and yolov5 together, on my Nvidia Jetson Nano (4 GB). But I have been stuck on this problem for a few days now, can you please help me understand if I should try any other approach?
[I also tried running NVIDIA deepstream for the code, but that failed due to system constraints]

Thankyou!
[files.zip](https://github.com/ultralytics/yolov5/files/11029910/files.zip)

**Comment by Rusali28** [comment]
@sriramreddyM Can you please have a look and help me figure this out?

**Comment by sriramreddyM** [comment]
@Rusali28 Can you provide error log when running "detect.py". Did you check if the openCV is built with gStreamer support?  run `print(cv2.getBuildInformation())`

**Comment by sriramreddyM** [comment]
Here are the steps you can follow to use the CSI camera with OpenCV for yolov5 detection:

1. First, check if the camera is detected and working by running nvgstcapture-1.0. This should capture from the camera and preview the output on the display.

2. Next, make sure OpenCV is built with gStreamer support. If it isn't, you'll need to uninstall OpenCV and rebuild it with gStreamer support. You can follow [these](https://yunusmuhammad007.medium.com/build-and-install-opencv-4-5-3-on-jetson-nano-with-cuda-opencl-opengl-and-gstreamer-enable-6dc7141be272) instructions to do this.

3. Once OpenCV is set up correctly, you can use the following example code to test the CSI camera and perform detection with a loaded model:

```python3
import cv2
import torch

model = torch.hub.load('ultralytics/yolov5', 'yolo5s')
#To load a model from a local path, use the following line instead:
#model = torch.hub.load('path_to_/yolov5', 'custom', 'path_to_weights/yolov5s.pt', source='local', force_reload=True)

cap = cv2.VideoCapture("nvarguscamerasrc ! video/x-raw(memory:NVMM), width=(int)1280, height=(int)720, format=(string)NV12, framerate=(fraction)30/1 ! nvvidconv flip-method=2 ! video/x-raw, width=(int)1280, height=(int)720, format=(string)BGRx ! videoconvert ! video/x-raw, format=(string)BGR ! appsink", cv2.CAP_GSTREAMER)

while True:
    ret, frame = cap.read()
    if ret:
        results = model(frame, size=640)
        results.print()
    else:
        print("No frame")
        break

cap.release()
```

Edit: in case of error Illegal instruction(core dumped), add `export OPENBLAS_CORETYPE=ARMV8` to bashrc file or start python with ` OPENBLAS_CORETYPE=ARMV8 python3`. If you are facing any other errors, follow [these](https://github.com/gicait/pLitter/blob/cctv/docs/Jetson-Nano-Preparation-Material.md#part-2-install-cuda-and-pytorch) to prepare your jetson and install dependencies.

**Comment by Rusali28** [comment]
Hello @sriramreddyM ,
As suggested I ran the print statement on python3.9 and this is what it prints
`Python 3.9.16 (main, Dec  7 2022, 01:11:58) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> print(cv2.getBuildInformation())

General configuration for OpenCV 4.7.0 =====================================
  Version control:               4.7.0-dirty

  Platform:
    Timestamp:                   2022-12-29T19:13:29Z
    Host:                        Linux 5.3.0-28-generic aarch64
    CMake:                       3.25.0
    CMake generator:             Unix Makefiles
    CMake build tool:            /bin/gmake
    Configuration:               Release

  CPU/HW features:
    Baseline:                    NEON FP16

  C/C++:
    Built as dynamic libs?:      NO
    C++ standard:                11
    C++ Compiler:                /opt/rh/devtoolset-10/root/usr/bin/c++  (ver 10.2.1)
    C++ flags (Release):         -Wl,-strip-all   -fsigned-char -W -Wall -Wreturn-type -Wnon-virtual-dtor -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Wsuggest-override -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections    -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
    C++ flags (Debug):           -Wl,-strip-all   -fsigned-char -W -Wall -Wreturn-type -Wnon-virtual-dtor -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Wsuggest-override -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections    -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
    C Compiler:                  /opt/rh/devtoolset-10/root/usr/bin/cc
    C flags (Release):           -Wl,-strip-all   -fsigned-char -W -Wall -Wreturn-type -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections    -fvisibility=hidden -O3 -DNDEBUG  -DNDEBUG
    C flags (Debug):             -Wl,-strip-all   -fsigned-char -W -Wall -Wreturn-type -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections    -fvisibility=hidden -g  -O0 -DDEBUG -D_DEBUG
    Linker flags (Release):      -L/ffmpeg_build/lib  -Wl,--gc-sections -Wl,--as-needed -Wl,--no-undefined  
    Linker flags (Debug):        -L/ffmpeg_build/lib  -Wl,--gc-sections -Wl,--as-needed -Wl,--no-undefined  
    ccache:                      YES
    Precompiled headers:         NO
    Extra dependencies:          /lib64/libopenblas.so Qt5::Core Qt5::Gui Qt5::Widgets Qt5::Test Qt5::Concurrent /usr/local/lib/libpng.so /usr/local/lib/libz.so dl m pthread rt
    3rdparty dependencies:       libprotobuf ade ittnotify libjpeg-turbo libwebp libtiff libopenjp2 IlmImf quirc tegra_hal

  OpenCV modules:
    To be built:                 calib3d core dnn features2d flann gapi highgui imgcodecs imgproc ml objdetect photo python3 stitching video videoio
    Disabled:                    world
    Disabled by dependency:      -
    Unavailable:                 java python2 ts
    Applications:                -
    Documentation:               NO
    Non-free algorithms:         NO

  GUI:                           QT5
    QT:                          YES (ver 5.15.0 )
      QT OpenGL support:         NO
    GTK+:                        NO
    VTK support:                 NO

  Media I/O: 
    ZLib:                        /usr/local/lib/libz.so (ver 1.2.13)
    JPEG:                        libjpeg-turbo (ver 2.1.3-62)
    WEBP:                        build (ver encoder: 0x020f)
    PNG:                         /usr/local/lib/libpng.so (ver 1.6.37)
    TIFF:                        build (ver 42 - 4.2.0)
    JPEG 2000:                   build (ver 2.4.0)
    OpenEXR:                     build (ver 2.3.0)
    HDR:                         YES
    SUNRASTER:                   YES
    PXM:                         YES
    PFM:                         YES

  Video I/O:
    DC1394:                      NO
    FFMPEG:                      YES
      avcodec:                   YES (59.37.100)
      avformat:                  YES (59.27.100)
      avutil:                    YES (57.28.100)
      swscale:                   YES (6.7.100)
      avresample:                NO
    GStreamer:                   NO
    v4l/v4l2:                    YES (linux/videodev2.h)

  Parallel framework:            pthreads

  Trace:                         YES (with Intel ITT)

  Other third-party libraries:
    Lapack:                      YES (/lib64/libopenblas.so)
    Eigen:                       NO
    Custom HAL:                  YES (carotene (ver 0.0.1))
    Protobuf:                    build (3.19.1)

  OpenCL:                        YES (no extra features)
    Include path:                /io/opencv/3rdparty/include/opencl/1.2
    Link libraries:              Dynamic load

  Python 3:
    Interpreter:                 /opt/python/cp37-cp37m/bin/python3.7 (ver 3.7.16)
    Libraries:                   libpython3.7m.a (ver 3.7.16)
    numpy:                       /home/ci/.local/lib/python3.7/site-packages/numpy/core/include (ver 1.19.3)
    install path:                python/cv2/python-3

  Python (for build):            /bin/python2.7

  Java:                          
    ant:                         NO
    JNI:                         NO
    Java wrappers:               NO
    Java tests:                  NO

  Install to:                    /io/_skbuild/linux-aarch64-3.7/cmake-install

`

So I think gstreamer is not built in this python3.9 version and opencv. Due to this I am unable to open the camera on python3.9. However, when I run the simple_camera.py file from the jetson-hacks repo, on python3.6 version it works fine. 
But my issue is that my yolov5 copydetect.py code has a few modifications in the --save-txt section that I want to print when the predictions are made. So it is necessary for me to run the copydetect.py file which only runs on python3.9 due to various dependency issues. I will try to install opencv with gstreamer support like you suggested in step2, but I am afraid it might again lead to a version dependency problem and then my copydetect.py file may fail to run.

Also can you suggest if we can make customised changes to the results printed by torch.hub.load?

Currently, this is the error log I face when I run copydetect.py on python3.9

`nvidia@nvidia-desktop:~/camrusali/yolov5$ python3.9 copydetect.py --weights best.pt --source csi-cam
/home/nvidia/.local/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 
  warn(f"Failed to load image Python extension: {e}")
copydetect: csi_cam=False, weights=['best.pt'], source=csi-cam, data=data/coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
Traceback (most recent call last):
  File "/home/nvidia/camrusali/yolov5/copydetect.py", line 285, in <module>
    main(opt)
  File "/home/nvidia/camrusali/yolov5/copydetect.py", line 280, in main
    run(**vars(opt))
  File "/home/nvidia/.local/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
TypeError: run() got an unexpected keyword argument 'csi_cam'
`


Thank you very much!

**Comment by sriramreddyM** [comment]
@Rusali28, if you're able to run the code I suggested without any errors using Python 3.6, then I recommend using it or modifying it to fit your requirements. You can use the following (example) commands to work with the detection results:

```
results.print()
results.show()
results.save()
results.xyxy[0]
```

If you still prefer to use detect.py, you'll need to work on fixing the dependencies. However, the error you copied doesn't seem to be related to YOLOv5 or the CSI camera. It's likely caused by an issue with the way you're passing arguments to the script.

**Comment by Rusali28** [comment]
@sriramreddyM I managed to resolve a few dependencies and ran the file you suggested on Python3.6, however, after running it shows a `No frame` error.
Could you please help me identify the reason for this? 
![Screenshot from 2023-03-24 12-13-44](https://user-images.githubusercontent.com/65704283/227472304-c70791af-440d-4635-91aa-d0d7d24bca9a.png)
I am also attaching the code below for your kind reference-
`import cv2
import torch

model = torch.hub.load('.', 'custom', 'best.pt', force_reload=True, source='local')

print("DONE\n")

cap = cv2.VideoCapture("nvarguscamerasrc ! video/x-raw(memory:NVMM), width=(int)1280, height=(int)720, format=(string)NV12, framerate=(fraction)30/1 ! nvvidconv flip-method=2 ! video/x-raw, width=(int)1280, height=(int)720, format=(string)BGRx ! videoconvert ! video/x-raw, format=(string)BGR ! appsink", cv2.CAP_GSTREAMER)

print("DONE22\n")

# if video_capture.isOpened():
#         try:
#             window_handle = cv2.namedWindow(window_title, cv2.WINDOW_AUTOSIZE)
#             while True:
#                 ret_val, frame = video_capture.read()
#                 # Check to see if the user closed the window
#                 # Under GTK+ (Jetson Default), WND_PROP_VISIBLE does not work correctly. Under Qt it does
#                 # GTK - Substitute WND_PROP_AUTOSIZE to detect if window has been closed by user
#                 if cv2.getWindowProperty(window_title, cv2.WND_PROP_AUTOSIZE) >= 0:
#                     cv2.imshow(window_title, frame)
#                 else:
#                     break 
#                 keyCode = cv2.waitKey(10) & 0xFF
#                 # Stop the program on the ESC key or 'q'
#                 if keyCode == 27 or keyCode == ord('q'):
#                     break
#         finally:
#             video_capture.release()
#             cv2.destroyAllWindows()
# else:
#     print("Error: Unable to open camera")

while True:
    ret, frame = cap.read()
    if ret:
        results = model(frame, size=416)
        results.print()
    else:
        print("No frame")
        break

cap.release()`

**Comment by Rusali28** [comment]
@sriramreddyM I tried the steps you suggested, and after a bunch of issues and errors, I am finally able to run my model using the camera successfully! Thank you so much for your support and help! I am very grateful!

**Comment by General-kirby** [comment]
> Here are the steps you can follow to use the CSI camera with OpenCV for yolov5 detection:
> 
> 1. First, check if the camera is detected and working by running nvgstcapture-1.0. This should capture from the camera and preview the output on the display.
> 2. Next, make sure OpenCV is built with gStreamer support. If it isn't, you'll need to uninstall OpenCV and rebuild it with gStreamer support. You can follow [these](https://yunusmuhammad007.medium.com/build-and-install-opencv-4-5-3-on-jetson-nano-with-cuda-opencl-opengl-and-gstreamer-enable-6dc7141be272) instructions to do this.
> 3. Once OpenCV is set up correctly, you can use the following example code to test the CSI camera and perform detection with a loaded model:
> 
> ```python
> import cv2
> import torch
> 
> model = torch.hub.load('ultralytics/yolov5', 'yolo5s')
> #To load a model from a local path, use the following line instead:
> #model = torch.hub.load('path_to_/yolov5', 'custom', 'path_to_weights/yolov5s.pt', source='local', force_reload=True)
> 
> cap = cv2.VideoCapture("nvarguscamerasrc ! video/x-raw(memory:NVMM), width=(int)1280, height=(int)720, format=(string)NV12, framerate=(fraction)30/1 ! nvvidconv flip-method=2 ! video/x-raw, width=(int)1280, height=(int)720, format=(string)BGRx ! videoconvert ! video/x-raw, format=(string)BGR ! appsink", cv2.CAP_GSTREAMER)
> 
> while True:
>     ret, frame = cap.read()
>     if ret:
>         results = model(frame, size=640)
>         results.print()
>     else:
>         print("No frame")
>         break
> 
> cap.release()
> ```
> 
> Edit: in case of error Illegal instruction(core dumped), add `export OPENBLAS_CORETYPE=ARMV8` to bashrc file or start python with ` OPENBLAS_CORETYPE=ARMV8 python3`. If you are facing any other errors, follow [these](https://github.com/gicait/pLitter/blob/cctv/docs/Jetson-Nano-Preparation-Material.md#part-2-install-cuda-and-pytorch) to prepare your jetson and install dependencies.

I just registered an account to say thanks, for those who want to use CSI as input, you can replace "cap = cv2.VideoCapture(s)" into cap = cv2.VideoCapture("nvarguscamerasrc ! video/x-raw(memory:NVMM), width=(int)1280, height=(int)720, format=(string)NV12, framerate=(fraction)30/1 ! nvvidconv flip-method=2 ! video/x-raw, width=(int)1280, height=(int)720, format=(string)BGRx ! videoconvert ! video/x-raw, format=(string)BGR ! appsink", cv2.CAP_GSTREAMER) in dataloader.py then it works.

**Comment by glenn-jocher** [comment]
@General-kirby thank you for sharing your experience and solution with us! It's great to hear that the suggested steps worked for you. Your suggestion to replace the `cap` line in dataloader.py will be helpful for others who want to use CSI as input. We appreciate your contribution to the YOLOv5 community. If you have any further questions or feedback, feel free to share it with us.

**Comment by zijeon** [comment]
@sriramreddyM
@Rusali28 
@General-kirby 

At first, I am not friendly with english, plz understand me if my english grammar was too bad

Anyway, I also tried to use CSI-Cam on yolov5
It's okay when I use CSI-Cam only without yolov5.
I wanna use IMX219-200 Camera, 200 FOV Applicable for Jetson Nano

My GStreamer was always "No" whether I installed GStreamer or not on python3.9
I tried to install Opencv again and again, It was always "No"
And I tried to change code from "cap = cv2.VideoCapture(s)" to cap = "cv2.VideoCapture(~~~~"

Eventhough I saw your saying and tried to follow them, but I failed :(

So, could you give me some advice for me?

My environments are 

JetsonNano
Ubuntu 18.04
Opencv 4.5.3
Pytorch  2.0.1
pip 21.3.1
Cuda 10.2.300
Cudnn 8.2.1.32

**Comment by sriramreddyM** [comment]
@zijeon 

You have to compile opencv from source to enable gstreamer. Follow these [steps](https://qengineering.eu/install-opencv-on-jetson-nano.html) to install opencv with streamer support.

**Comment by glenn-jocher** [comment]
@sriramreddyM

To enable GStreamer support in OpenCV, you will need to compile OpenCV from source. You can follow the steps mentioned in this documentation to install OpenCV with GStreamer support on your Jetson Nano: [Link: steps-to-install-opencv-with-gstreamer-support].

Once you have successfully compiled and installed OpenCV with GStreamer support, you should be able to use the CSI camera with YOLOv5.

Let me know if you have any further questions or issues.

**Comment by caijixiangxuec** [comment]
> > Here are the steps you can follow to use the CSI camera with OpenCV for yolov5 detection:
> > 
> > 1. First, check if the camera is detected and working by running nvgstcapture-1.0. This should capture from the camera and preview the output on the display.
> > 2. Next, make sure OpenCV is built with gStreamer support. If it isn't, you'll need to uninstall OpenCV and rebuild it with gStreamer support. You can follow [these](https://yunusmuhammad007.medium.com/build-and-install-opencv-4-5-3-on-jetson-nano-with-cuda-opencl-opengl-and-gstreamer-enable-6dc7141be272) instructions to do this.
> > 3. Once OpenCV is set up correctly, you can use the following example code to test the CSI camera and perform detection with a loaded model:
> > 
> > ```python
> > import cv2
> > import torch
> > 
> > model = torch.hub.load('ultralytics/yolov5', 'yolo5s')
> > #To load a model from a local path, use the following line instead:
> > #model = torch.hub.load('path_to_/yolov5', 'custom', 'path_to_weights/yolov5s.pt', source='local', force_reload=True)
> > 
> > cap = cv2.VideoCapture("nvarguscamerasrc ! video/x-raw(memory:NVMM), width=(int)1280, height=(int)720, format=(string)NV12, framerate=(fraction)30/1 ! nvvidconv flip-method=2 ! video/x-raw, width=(int)1280, height=(int)720, format=(string)BGRx ! videoconvert ! video/x-raw, format=(string)BGR ! appsink", cv2.CAP_GSTREAMER)
> > 
> > while True:
> >     ret, frame = cap.read()
> >     if ret:
> >         results = model(frame, size=640)
> >         results.print()
> >     else:
> >         print("No frame")
> >         break
> > 
> > cap.release()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Edit: in case of error Illegal instruction(core dumped), add `export OPENBLAS_CORETYPE=ARMV8` to bashrc file or start python with ` OPENBLAS_CORETYPE=ARMV8 python3`. If you are facing any other errors, follow [these](https://github.com/gicait/pLitter/blob/cctv/docs/Jetson-Nano-Preparation-Material.md#part-2-install-cuda-and-pytorch) to prepare your jetson and install dependencies.
> 
> I just registered an account to say thanks, for those who want to use CSI as input, you can replace "cap = cv2.VideoCapture(s)" into cap = cv2.VideoCapture("nvarguscamerasrc ! video/x-raw(memory:NVMM), width=(int)1280, height=(int)720, format=(string)NV12, framerate=(fraction)30/1 ! nvvidconv flip-method=2 ! video/x-raw, width=(int)1280, height=(int)720, format=(string)BGRx ! videoconvert ! video/x-raw, format=(string)BGR ! appsink", cv2.CAP_GSTREAMER) in dataloader.py then it works.

I was able to use the CSI camera normally when using GStreamer, but on YOLOv5 I took your advice, modified the code, but unfortunately I still failed during the runtime. The following error message is displayed:
(python3:3033): GStreamer-WARNING **: 11:39:44.890: Failed to load plugin '/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvarguscamerasrc.so': /lib/aarch64-linux-gnu/libGLdispatch.so.0: cannot allocate memory in static TLS block

(python3:3033): GStreamer-WARNING **: 11:39:44.894: Failed to load plugin '/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvvidconv.so': /lib/aarch64-linux-gnu/libGLdispatch.so.0: cannot allocate memory in static TLS block

![csi](https://github.com/user-attachments/assets/fb7b7f16-865a-4e00-9668-8ade5f628f37)

**Comment by pderrenger** [comment]
The error indicates a memory allocation issue related to the `libGLdispatch.so.0` library, which is likely caused by a conflict between GStreamer plugins and the OpenGL libraries. This issue commonly arises in Jetson environments due to compatibility mismatches.

To resolve this:
1. **Check Environment Variables**: Ensure that `LD_PRELOAD` is configured to load `libGLdispatch.so.0` correctly. Run:
   ```bash
   export LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libGLdispatch.so.0
   ```
   Add this line to your `.bashrc` file to make it persistent.

2. **Rebuild OpenCV with GStreamer Support**: Ensure your OpenCV is compiled with proper GStreamer support. Follow this guide for Jetson-specific instructions: [Install OpenCV with GStreamer Support](https://qengineering.eu/install-opencv-on-jetson-nano.html).

3. **Verify GStreamer Plugins**: Confirm that the required GStreamer plugins are correctly installed and not corrupted. Run:
   ```bash
   gst-inspect-1.0 nvarguscamerasrc
   ```
   If this fails, reinstall the `gstreamer1.0-plugins-bad` package:
   ```bash
   sudo apt-get install gstreamer1.0-plugins-bad
   ```

4. **Update Jetson Software**: Ensure your Jetson system firmware, including JetPack, is up-to-date. You can update it using the NVIDIA SDK Manager.

If the issue persists, consider switching to a different environment or using DeepStream SDK for optimized performance with CSI cameras and YOLOv5. Let me know if you need further assistance!

**Comment by caijixiangxuec** [comment]
> The error indicates a memory allocation issue related to the `libGLdispatch.so.0` library, which is likely caused by a conflict between GStreamer plugins and the OpenGL libraries. This issue commonly arises in Jetson environments due to compatibility mismatches.
> 
> To resolve this:
> 
> 1. **Check Environment Variables**: Ensure that `LD_PRELOAD` is configured to load `libGLdispatch.so.0` correctly. Run:
>    ```shell
>    export LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libGLdispatch.so.0
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    Add this line to your `.bashrc` file to make it persistent.
> 2. **Rebuild OpenCV with GStreamer Support**: Ensure your OpenCV is compiled with proper GStreamer support. Follow this guide for Jetson-specific instructions: [Install OpenCV with GStreamer Support](https://qengineering.eu/install-opencv-on-jetson-nano.html).
> 3. **Verify GStreamer Plugins**: Confirm that the required GStreamer plugins are correctly installed and not corrupted. Run:
>    ```shell
>    gst-inspect-1.0 nvarguscamerasrc
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    If this fails, reinstall the `gstreamer1.0-plugins-bad` package:
>    ```shell
>    sudo apt-get install gstreamer1.0-plugins-bad
>    ```
> 4. **Update Jetson Software**: Ensure your Jetson system firmware, including JetPack, is up-to-date. You can update it using the NVIDIA SDK Manager.
> 
> If the issue persists, consider switching to a different environment or using DeepStream SDK for optimized performance with CSI cameras and YOLOv5. Let me know if you need further assistance!

Thank you very much for your advice. After using suggestion 1, I can use it smoothly.
Although I didn't find libGLdispatch.so.0 in my directory (/usr/lib/aarch64-linux-gnu/libGLdispatch.so.0), could you explain the reason in more detail, if possible?
Sincerely, thank you again for answering my questions and wish you a good day.

**Comment by pderrenger** [comment]
You're very welcome! I'm glad the suggestion worked for you. The `libGLdispatch.so.0` issue relates to how OpenGL dispatch libraries manage thread-local storage (TLS) for graphics processes. In some Jetson setups, mismatched or incomplete installations of OpenGL or GStreamer plugins can cause TLS allocation conflicts. By preloading the library via `LD_PRELOAD`, you ensure that it is loaded correctly in memory, resolving such conflicts.

If `libGLdispatch.so.0` wasn't found in your directory, it's possible your system uses a different OpenGL configuration or the library resides in a non-standard location. You can locate it using:
```shell
find /usr -name libGLdispatch.so.0
```

Feel free to reach out if you have more questions, and thank you for your kind words!
