### ISSUE TITLE
Why does mosaic comes before albumentations augment?

### ISSUE THREAD

**Issue by sarmientoj24** [ultralytics/yolov5#8787]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Running through the code, it seems like that the mosaic augmentation comes before the albumentations augmentations here.

https://github.com/ultralytics/yolov5/blob/52d3a9aee1016604652898fed679e55783e264ed/utils/dataloaders.py#L634

It seems counter-intuitive to me. As I understand, mosaic basically creates like a collage of the a subset of the batch of images.  

If that is the case, applying mosaic before some of the albumentations augmentations seem weird. The `ShiftScaleRotate` instead applies to the whole mosaic or some other augmentations. Why is this so?

**Comment by glenn-jocher** [comment]
@sarmientoj24 if we reversed the order then only the index 0 image in the mosaic (i.e. top left image) would undergo Albumentations transforms.

**Comment by sarmientoj24** [comment]
I see. I wonder why is it designed that way. I was under the impression that everytime there is a mosaic, individual pieces get augmented. Thank you

**Comment by glenn-jocher** [comment]
@sarmientoj24 well logically augmenting 4 things will be slower than augmenting 1 thing.
