### ISSUE TITLE
How can I move and run the classification model out of YOLOV5 codebase? 

### ISSUE THREAD

**Issue by AI-Passionner** [ultralytics/yolov5#8790]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

It seems that loading the classification model can't leave out of the YOLOV5-Classifier code base. When loading the model, 
`model = torch.load('path/to/best.pt', map_location=torch.device('cpu'))['model'].float()`, it throws error like this 
"""
 module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'models'
"""
Once the folders of `models` and `utils` are copied to a new project directory, the loading works. 

I am asking if there is a way I can load the classification model and use it as a stand-alone and for example, converting to TensorFlow like the object detection codebase.  
As I know, the YOLOV5 object detection doesn't have this problem. 

Thanks.

**Comment by glenn-jocher** [comment]
@AI-Passionner this is a good question. In general for any pytorch model you'll need to have the modules available in the workspace prior to loading. PyTorch Hub accomplishes this in the background by downloading and caching the repo in a separate directory.

To point PyTorch Hub to a specific branch in a repo, i.e. the classifier branch in the YOLOv5 repo you can try this, though the classifier should be merged into master as part of the upcoming v6.2 release in the next few weeks.

```python
model = torch.hub.load('ultralytics/yolov5:classifier', 'custom', path='path/to/model.pt')  # local model
```

**Comment by AI-Passionner** [comment]
@glenn-jocher Thank you. Let me try. I bet this is what I am looking for. Really appreciate your help. 
Tiger

**Comment by AI-Passionner** [comment]
The classification model was trained as  `yolov5s`. I copied the model file to the new project and. But it didn't work when loading the new model as your suggested scripts. 
`model = torch.hub.load('ultralytics/yolov5:classifier', 'custom', path='weights/yolov5s_exp30/weights/best.pt') ` 

I threw the error message like this. Adding `force_reload=True` didn't work.  Deleting the Cache didn't work.  Any suggestion?  
Do I need to specify the `custom` in the script?

""""
Fusing layers... 
YOLOv5s summary: 117 layers, 4169250 parameters, 0 gradients, 10.4 GFLOPs
Adding AutoShape... 
Traceback (most recent call last):
  File "C:\Users\tiger.cao/.cache\torch\hub\ultralytics_yolov5_classifier\hubconf.py", line 62, in _create
    return model.to(device)
  File "C:\Users\tiger.cao\anaconda3\envs\Yolov5\lib\site-packages\torch\nn\modules\module.py", line 927, in to
    return self._apply(convert)
  File "C:\Users\tiger.cao/.cache\torch\hub\ultralytics_yolov5_classifier\models\common.py", line 571, in _apply
    m.stride = fn(m.stride)
  File "C:\Users\tiger.cao\anaconda3\envs\Yolov5\lib\site-packages\torch\nn\modules\module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Classify' object has no attribute 'stride'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "C:\Users\tiger.cao\anaconda3\envs\Yolov5\lib\site-packages\IPython\core\interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-8c7e755631ce>", line 1, in <cell line: 1>
    model = torch.hub.load('ultralytics/yolov5:classifier', 'custom', force_reload=True, path='weights/yolov5s_exp30/weights/best.pt')  # local model
  File "C:\Users\tiger.cao\anaconda3\envs\Yolov5\lib\site-packages\torch\hub.py", line 540, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "C:\Users\tiger.cao\anaconda3\envs\Yolov5\lib\site-packages\torch\hub.py", line 569, in _load_local
    model = entry(*args, **kwargs)
  File "C:\Users\tiger.cao/.cache\torch\hub\ultralytics_yolov5_classifier\hubconf.py", line 72, in custom
    return _create(path, autoshape=autoshape, verbose=_verbose, device=device)
  File "C:\Users\tiger.cao/.cache\torch\hub\ultralytics_yolov5_classifier\hubconf.py", line 67, in _create
    raise Exception(s) from e
Exception: 'Classify' object has no attribute 'stride'. Cache may be out of date, try `force_reload=True` or see https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading for help.
""""

**Comment by glenn-jocher** [comment]
@AI-Passionner got it. It looks like we need to add some classifier-specific code to hubconf.py to handle these models differently, which makes sense. I'll add a TODO for this.

**Comment by AI-Passionner** [comment]
@glenn-jocher Thank you. 
Currently, I copied the folders `models/` and `utils/` with a little bit of cleaning to the new project. It works.

**Comment by glenn-jocher** [comment]
@AI-Passionner I think this should work now for newly trained models of type models.yolo.ClassificationModel, (but not for older models of type models.yolo.Model).

I'll run some tests to verify today.

**Comment by AI-Passionner** [comment]
@glenn-jocher Thank you. I will run the train again and have a try. 
Tiger

**Comment by glenn-jocher** [comment]
@AI-Passionner I've confirmed PyTorch Hub loading works in a test just now on Google Colab. I uploaded a recent ImageNet trained YOLOv5m-cls model (about 75 top-1 accuracy after 90 epochs) and then requested it like this. This does **not** need a local git clone of YOLOv5.
https://github.com/ultralytics/yolov5/releases/download/v6.1/yolov5m-cls.pt

```python
import torch

model = torch.hub.load('ultralytics/yolov5:classifier', 'custom', 'yolov5m-cls.pt')  # or use local cls model
print(type(model))
```

<img width="870" alt="Screen Shot 2022-08-04 at 9 11 47 PM" src="https://user-images.githubusercontent.com/26833433/182934265-44f12de2-1289-4d0a-b638-2b00b5d5d886.png">

EDIT: Once we release 6.2 with built-in classification support then you no longer need to point torch.hub.load() to the `classifier` branch, i.e. you can use torch.hub.load('ultralytics/yolov5', ...)

**Comment by AI-Passionner** [comment]
Great. Really appreciate your effort. YOLOV5 is the best for our object detection project so far, no matter its accuracy and speed.

**Comment by UygarUsta** [comment]
I am getting the same issue trying to inference using hub with classification models.  ```Exception: 'Classify' object has no attribute 'stride'. Cache may be out of date, try force_reload=True or see https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading for help.```  classify/predict.py works fine though.

**Comment by glenn-jocher** [comment]
@UygarUsta can you please submit a minimum reproducible example?

**Comment by glenn-jocher** [comment]
@UygarUsta works for me.

<img width="1056" alt="Screenshot 2022-08-18 at 20 57 13" src="https://user-images.githubusercontent.com/26833433/185472925-fa94e6e1-d997-4cf8-9284-21952bf2eb4b.png">

**Comment by UygarUsta** [comment]
> @UygarUsta can you please submit a minimum reproducible example?

![image](https://user-images.githubusercontent.com/34573541/185473864-476d786c-c459-4f50-9f36-31211cedfe7a.png)

**Comment by UygarUsta** [comment]
I also tried it with ultralytics cache.No luck.

![image](https://user-images.githubusercontent.com/34573541/185475200-4d80ff83-69e1-4784-9f68-616a50ed96a7.png)

**Comment by glenn-jocher** [comment]
@UygarUsta added a CI check for this use case and can now reproduce in https://github.com/ultralytics/yolov5/runs/7905622621?check_suite_focus=true, I'll investigate.

**Comment by glenn-jocher** [comment]
@UygarUsta good news 😃! Your original issue may now be fixed ✅ in PR #9027. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by UygarUsta** [comment]
> @UygarUsta good news 😃! Your original issue may now be fixed ✅ in PR #9027. To receive this update:
> 
> * **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
> * **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
> * **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  [![Open In Colab](https://camo.githubusercontent.com/84f0493939e0c4de4e6dbe113251b4bfb5353e57134ffd9fcab6b8714514d4d1/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb) [![Open In Kaggle](https://camo.githubusercontent.com/a08ca511178e691ace596a95d334f73cf4ce06e83a5c4a5169b8bb68cac27bef/68747470733a2f2f6b6167676c652e636f6d2f7374617469632f696d616765732f6f70656e2d696e2d6b6167676c652e737667)](https://www.kaggle.com/models/ultralytics/yolov5)
> * **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image [![Docker Pulls](https://camo.githubusercontent.com/280faedaf431e4c0c24fdb30ec00a66d627404e5c4c498210d3f014dd58c2c7e/68747470733a2f2f696d672e736869656c64732e696f2f646f636b65722f70756c6c732f756c7472616c79746963732f796f6c6f76353f6c6f676f3d646f636b6572)](https://hub.docker.com/r/ultralytics/yolov5)
> 
> Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

Unfortunately another error arises.

![image](https://user-images.githubusercontent.com/34573541/185483177-18a4b3cd-301b-44e1-a018-3c97980ac304.png)

I also tried my luck with ultralytics cache.As always thank you for your hard work .
![image](https://user-images.githubusercontent.com/34573541/185483347-d3f15be2-3d72-4d97-9e9c-860521a122e8.png)

**Comment by aiakash** [comment]
its not working
```
import torch

model = torch.hub.load('ultralytics/yolov5:classifier', 'custom', 'yolov5m-cls.pt')  # or use local cls model
print(type(model))
```

ValueError: Cannot find classifier in https://github.com/ultralytics/yolov5. If it's a commit from a forked repo, please call hub.load() with forked repo directly.

**Comment by glenn-jocher** [comment]
Understood, @aiakash. The error may be due to the `ultralytics/yolov5:classifier` hub identifier not yet being available. This is now under investigation. Thank you for your patience.
