### ISSUE TITLE
Augmentation is applied based on image or label based.

### ISSUE THREAD

**Issue by sarpx** [ultralytics/yolov5#8796]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I see that left-right blending is image-based. My example is when blending left and right of multiple objects within an image. I see that there is no such mixing in similar images of the same picture. This makes me think that he remembers the picture with recollection and mixes the left and right of the objects in the whole picture. If it was label based, I would expect some objects in the picture to give more consistent results.

**Comment by glenn-jocher** [comment]
@sarpx thanks for the info. I'm not sure exactly what you mean, can you provide an example image or mosaic you are describing?

**Comment by sarpx** [comment]
![34](https://user-images.githubusercontent.com/73984193/181934858-6ff0f9db-fc45-4dad-93d7-76c24caa6b05.jpg)
![e1](https://user-images.githubusercontent.com/73984193/181934859-ecf771b5-98ff-451e-ba20-1ed362dcf080.jpg)
![e2](https://user-images.githubusercontent.com/73984193/181934860-a26d7f20-8e77-4940-92bf-401bba28a97b.jpg)
![e3](https://user-images.githubusercontent.com/73984193/181934861-a7284e72-055c-417d-87df-0d2769dac8c0.jpg)
![e5](https://user-images.githubusercontent.com/73984193/181934862-988ec5c5-651c-4ce6-a39b-fe3774ec44e6.jpg)
![problem](https://user-images.githubusercontent.com/73984193/181934863-4cd2c17b-52be-4fca-a119-67d47875c0b6.jpg)
@glenn-jocher Images are copyrighted and private property so I can't share them. I created the pictures that can best explain the subject.
Here are the cups and their handles. The direction of the handles is very important to us.
Now he guesses more than 80% correctly. But sometimes the cup directions of all the cups in the picture are left or right. Even if there are different cups, they still give left or right directions in common. Sometimes he gives the directions left or right in all the different cups, while giving the right and wrong directions together. But he usually tends to find the opposite of the direction he should always be excessive. I think it might have something to do with remembering. Because how can he find the reverse direction of all the cups in the picture.. I couldn't find a control method to test the accuracy of this. I think this will be asked a lot in the future. What is the direction of the object he finds? If the object approaching you is on the left, you may want to behave differently if it is on the right.

**Comment by glenn-jocher** [comment]
@sarpx I don't quite understand the question but you should be aware of left-right flips during augmentation. This is set to 50% by default meaning half of all training images are flipped left-right. You can disable or update this value in your hyp yaml file:
https://github.com/ultralytics/yolov5/blob/39ce8ca19a1b97e36c73d86ecc70c2c3e42ac5c0/data/hyps/hyp.scratch-low.yaml#L31

**Comment by sarpx** [comment]
@glenn-jocher  I've changed almost all of the parameters here in countless combinations.
Especially in the fliplr parameter. But it doesn't work. In general, I always get the right-left mixing in all of the different-looking parts in the same image. It doesn't happen in other pictures, the tube in the same picture always says left or right. This makes me think that the augmentation is based on the image, not the label, and remembers this. If the label were a base, he would have to know correctly some of the different parts in the picture.
Am I thinking wrong.

**Comment by glenn-jocher** [comment]
@sarpx augmentations are applied to images and labels identically

**Comment by sarpx** [comment]
@glenn-jocher I adore Yolo. It will be remembered as a touchstone for years to come. If a road comes in front of us on the road soon, it will catch the road 99% of the time, but does the road turn left or right? If you teach him to find a machine, 99% will find it, but is it the front or the back of the machine you are looking at, right or left? It will find a car for sure, but is the look in the picture right or left of the car? You are checking a part from a production line, is it the right or wrong left of the part? I think this issue is very important, but I couldn't explain my problem.

**Comment by glenn-jocher** [comment]
@sarpx got it. For orientation you might require something more complex like volumetric/3d reconstruction etc.

Also remember for any supervised training to occur you need labelled data, so if you want to know what side you are looking at the model must be structured in such a way as to output that information and must be presented data labelled with that information.

**Comment by sarpx** [comment]
@glenn-jocher I understand, but none of them are as successful and fast as Yolo :(

**Comment by glenn-jocher** [comment]
@sarpx i appreciate the compliment, but I must defer the credit to the talented YOLO community and the hardworking team at Ultralytics. Please continue to explore how YOLOv5 can best meet your requirements.
