### ISSUE TITLE
Can’t use gpu mac m1 

### ISSUE THREAD

**Issue by chelsea456** [ultralytics/yolov5#8805]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

![7E01CA6A-745F-4EEA-B489-6EE7596CC5F0](https://user-images.githubusercontent.com/104009307/182022697-f22919a0-c9dd-48f2-9d0a-63f075a07691.jpeg)
I run the code python detect.py - - device mps but in the process i print(device) program use cpu not use mps. I don’t know how to fix it.

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@chelsea456 if your environment doesn't support MPS then CPU will be used instead. Perhaps you haven't installed the ARM version of python 3.9?

Even if you did have the correct environment though MPS support is still in progress. The PyTorch team is working on unsupported ops.

<img width="1246" alt="Screen Shot 2022-07-31 at 2 36 44 PM" src="https://user-images.githubusercontent.com/26833433/182026773-a1d3337a-cc05-44fc-99d7-684b93a79cb0.png">

**Comment by glenn-jocher** [comment]
You want to make sure you use the 'universal2' installer on M1/M2 machines:
https://www.python.org/downloads/release/python-3105/

**Comment by chelsea456** [comment]
> @chelsea456 if your environment doesn't support MPS then CPU will be used instead. Perhaps you haven't installed the ARM version of python 3.9?
> 
> 
> 
> Even if you did have the correct environment though MPS support is still in progress. The PyTorch team is working on unsupported ops.
> 
> 
> 
> <img width="1246" alt="Screen Shot 2022-07-31 at 2 36 44 PM" src="https://user-images.githubusercontent.com/26833433/182026773-a1d3337a-cc05-44fc-99d7-684b93a79cb0.png">
> 
> 
> 
> 

I using the python 3.9 anh i have error is the your image, you can teach me how to fix. Tks sir very much

**Comment by glenn-jocher** [comment]
@chelsea456 see https://github.com/pytorch/pytorch/issues/82034 and https://github.com/pytorch/pytorch/issues/77764

**Comment by chelsea456** [comment]
> You want to make sure you use the 'universal2' installer on M1/M2 machines:
> 
> https://www.python.org/downloads/release/python-3105/
> 
> 
> 
> 

I just install python 3.10.5 but the error not fix :(((

**Comment by glenn-jocher** [comment]
@chelsea456 i'm sorry to hear that the issue persists. This issue is related to PyTorch support on Apple M1 and may not be specific to YOLOv5. We recommend keeping an eye on the PyTorch GitHub repository for updates on M1 support. Thank you for your understanding!
