### ISSUE TITLE
Contributors section has a broken image 

### ISSUE THREAD

**Issue by AyushExel** [ultralytics/yolov5#8817]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Here's how the contributors section looks like for me. Not sure if its broken for everyone or it's a regional thing. Please take a look!
<img width="886" alt="Screenshot 2022-08-01 at 11 27 41 AM" src="https://user-images.githubusercontent.com/15766192/182081803-5f65c497-36fb-4618-b534-5c783eb509df.png">

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@AyushExel I noticed this also. The opencollective svg we use seems to be spotty due to some issues at opencollective, i.e.
https://github.com/opencollective/opencollective-api/issues/1164

An alternative mentioned is here:
https://contrib.rocks/preview?repo=ultralytics%2Fyolov5

**Comment by glenn-jocher** [comment]
@AyushExel I saw the empty image a few minutes ago, now see the full image, but I agree let's keep an eye on this and if it doesn't consistently show we should switch to the alternative above

<img width="1431" alt="Screen Shot 2022-08-01 at 11 36 30 AM" src="https://user-images.githubusercontent.com/26833433/182119959-42d3bc8a-867a-4a4b-b711-110402be7c7a.png">

**Comment by glenn-jocher** [comment]
@AyushExel alternatively I exported the svg (2MB) to a fixed PNG (400kB). Should be faster to load and still transparent for dark mode, we can host as a v1.0 release asset, should permanently resolve problems.

![68747470733a2f2f6f70656e636f6c6c6563746976652e636f6d2f756c7472616c79746963732f636f6e7472696275746f72732e7376673f77696474683d393930](https://user-images.githubusercontent.com/26833433/182121539-134d7acb-1b15-4963-8f19-c7fa5213c2d2.png)

**Comment by glenn-jocher** [comment]
@AyushExel master is updated. Let me know if you see any more broken links here.
