### ISSUE TITLE
Question about yolov5's metrics

### ISSUE THREAD

**Issue by cyndyNKCM** [ultralytics/yolov5#8819]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello @glenn-jocher 

I want to know if with yolov5 we can get the precision or the recall of each image.
If not is there a metric that can do this work?

**Comment by glenn-jocher** [comment]
@cyndyNKCM metrics such as P and R are computed per class and per IoU threshold but not per image (yet).
