### ISSUE TITLE
Training with evolved hyper parameters

### ISSUE THREAD

**Issue by MartinPedersenpp** [ultralytics/yolov5#8822]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello

After training my model for 340 epochs, I have evolved my hyper parameters and gotten the hyp_evolve.yaml file.

I have added, some more images to my dataset and added the path to my hyp_evolve file and want to continue training.
I use: train.py --hyp runs/evolve/exp/hyp_evolve.yaml --img 640 --batch 48 --epochs 1000 --data dataset.yml --weights runs/train/exp12/weights/last.pt --workers 8
But this continues the training from the 340th epoch with a slightly lower mAp than the final epoch before evolving.
Is this the correct way to do it or should I start from scratch with the yolov5s.pt?
Is there a correct way to do it or has this been tested in any way?

Best regards
Martin

**Comment by glenn-jocher** [comment]
@MartinPedersenpp it's pretty simple, evolution optimizes a set of hyperparameters on your base scenario. 

You should use the evolved hyps on your base scenario.

```
python train.py [BASE_SCENARIO] --evolve
python train.py [BASE_SCENARIO] --hyp hyp_evolved.yaml
```

**Comment by MartinPedersenpp** [comment]
@glenn-jocher Alright that makes sense.
Thanks!

**Comment by glenn-jocher** [comment]
@MartinPedersenpp you're welcome! If you have any more questions, feel free to ask. Good luck with your training!
