### ISSUE TITLE
How to set the txt generated by yolov5 --save-txt to be overwritten instead of appended to the txt?

### ISSUE THREAD

**Issue by 123lzz** [ultralytics/yolov5#8824]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

  When using yolov5 detect.py for training data, it is necessary to train the incoming pictures of the same name in real time.
  
Excuse me, when the --save-txt parameter is True, if the photo names are the same, each new coordinate data is appended to the original generated txt
  
As a result, when reading this text, there is old data from the last training.
   
I set --exist-ok to True, the recognized image will be overwritten each time, but the label's txt file will not be overwritten,

How can I set the txt generated each time to overwrite the original one?

**Comment by glenn-jocher** [comment]
@123lzz 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # yolov5n - yolov5x6 official model
#                                            'custom', 'path/to/best.pt')  # custom model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
results.xyxy[0]  # im predictions (tensor)

results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie

results.pandas().xyxy[0].value_counts('name')  # class counts (pandas)
# person    2
# tie       1
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by 123lzz** [comment]
> @123lzz 👋你好！感谢您询问有关**处理推理结果**的问题。YOLOv5🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)模型允许在纯 Python 环境中进行简单的模型加载和推理，而无需使用`detect.py`.
> 
> ### 简单推理示例
> 此示例从 PyTorch Hub 加载预训练的 YOLOv5s 模型，`model`并传递图像进行推理。`'yolov5s'`是 YOLOv5 'small' 模型。有关所有可用模型的详细信息，请参阅[自述](https://github.com/ultralytics/yolov5#pretrained-checkpoints)文件。还可以加载自定义模型，包括自定义训练的 PyTorch 模型及其[导出](https://docs.ultralytics.com/yolov5/tutorials/model_export)的变体，即 ONNX、TensorRT、TensorFlow、OpenVINO YOLOv5 模型。
> 
> ```python
> import torch
> 
> # Model
> model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # yolov5n - yolov5x6 official model
> #                                            'custom', 'path/to/best.pt')  # custom model
> 
> # Images
> im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list
> 
> # Inference
> results = model(im)
> 
> # Results
> results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
> results.xyxy[0]  # im predictions (tensor)
> 
> results.pandas().xyxy[0]  # im predictions (pandas)
> #      xmin    ymin    xmax   ymax  confidence  class    name
> # 0  749.50   43.50  1148.0  704.5    0.874023      0  person
> # 2  114.75  195.75  1095.0  708.0    0.624512      0  person
> # 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
> 
> results.pandas().xyxy[0].value_counts('name')  # class counts (pandas)
> # person    2
> # tie       1
> ```
> 
> <img alt="" width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">
> 
> 有关详细信息，请参阅[YOLOv5 PyTorch Hub 教程](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)。
> 
> 祝你好运🍀如果您还有其他问题，请告诉我们！

Thank you for your help, I have tried using PyTorch, it faster and easier than detect.py, but I want to know what is the reason for using the same trained model to infer different results in detect.py and in PyTorch?
I use the same conf and iou. Is it because of the different sizes of the images?
In detect.py:
`    parser.add_argument('--imgsz', '--img', '--img-size', nargs='+', type=int, default=[1824, 2880])
`
but In PyTorch:
`results = model('a.png', size=[1824, 2880])
`
It seems that it can't pass in two parameters:TypeError: unsupported operand type(s) for /: 'list' and 'int'
What can I do to pass the width and height of the image into the model？

**Comment by glenn-jocher** [comment]
@123lzz pytorch is more flexible, i.e. once you have results you can convert to pandas dataframe and then from there handle however you want, i.e. to JSON, to CSV, to numpy etc.
