### ISSUE TITLE
about mosaic augmentation

### ISSUE THREAD

**Issue by spacewalk01** [ultralytics/yolov5#8832]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Would you please explain the reason why you set up mosaic augmentation prob to 1.0. For each sample, it is going to perform mosaic augmentation which will reduce the object resolution(pixels) as two or more images are mixed together, but test images can be much higher and objects are larger. Isn't it going to negatively affect the test performance if you have images with low-resolution? Thanks

### Additional

Also,  why not add mixcut augmentation feature (not mixup) or albumentation crop augmentation?

**Comment by glenn-jocher** [comment]
@spacewalk01 hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by Zephyr69** [comment]
@spacewalk01 What changes would be needed to retain the image scale while keeping mosaic enabled?
