### ISSUE TITLE
Windows Docker-Nvidia Installation

### ISSUE THREAD

**Issue by spacewalk01** [ultralytics/yolov5#8834]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is there any detailed guide to install docker-nvidia on windows and train yolov5 on multi-gpus inside docker? Thanks

**Comment by barney2074** [comment]
good question- I'd also be interested to find out the answer to this

My reading of articles like this https://www.docker.com/blog/wsl-2-gpu-support-for-docker-desktop-on-nvidia-gpus/ or this https://docs.nvidia.com/cuda/wsl-user-guide/index.html
suggest that it should work on Windows11, but not Windows10 ?

I haven't spent any time jumping thought the hoops, plus the machine I'd use apparently isn't compatible with W11
For now I'll stick with my trusty Linux machine which works fine


Andrew

**Comment by zhuya1996** [comment]
Only a single GPU has been used

**Comment by spacewalk01** [comment]
@barney2074 thanks for the recommendation I will look into it. @zhuya1996 I don't remember exactly where but somewhere(in the issues) I read that for multi-gpu training on windows, it was recommended to deploy docker.
