### ISSUE TITLE
Remove certain classes from trained weights.

### ISSUE THREAD

**Issue by SanjayGhanagiri** [ultralytics/yolov5#8837]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I need to remove some of the classes from trained weights and convert them to tflite format.

I can pass required classes as `python detect.py --classes 0` and detect from beat.pt file. 
But while the model runs on android device we need to provide all the classes for detection which I don't want to do. 
Model ends up detecting all the classes. Also I dont want to retrain the model by removing the classes.

Is there any way we can remove the classes from the trained pt weights or while converting to tflite?

### Additional

I have gone through below links as well. They help in detection of required classes from trained weights.

 https://github.com/ultralytics/yolov5/issues/1025
 https://github.com/ultralytics/yolov5/discussions/2463

**Comment by glenn-jocher** [comment]
@SanjayGhanagiri remove classes and retrain. You can use this line if you don't want to modify your dataset:
https://github.com/ultralytics/yolov5/blob/08c8c3e00a1b0fc7f03a7e76ca3cbf7a0d8542ae/utils/dataloaders.py#L491-L492

**Comment by SanjayGhanagiri** [comment]
@glenn-jocher But this requires retraining of the complete model right. 
There are some false positives in my trained model. I need to remove detection of such classes. 
Instead of retraining the model by ignoring these classes , is there a way to remove certain classes in the already trained model weights ? either on best.pt or exported tflite weights?

**Comment by glenn-jocher** [comment]
@SanjayGhanagiri You can remove the classes from the detection post processing steps in your inference code. In the `detect.py` script, you can filter out the unwanted classes after the model prediction step before displaying or using the predictions in your Android app. I understand your request, however, as of now we don't support directly removing classes from the trained model weights. Good luck with your project!
