### ISSUE TITLE
Besy way to add images to a trainning process

### ISSUE THREAD

**Issue by FlorianRuen** [ultralytics/yolov5#884]
Hello there,

I'm using the Yolo V5 (which is pretty good !), and I got a general question on the trainning process.
I've done a trainning for 300 epochs in 40 hours using 13k images and now I want to add new images to get more precision.

What I'm doing is to add my images and labels to my existing dataset, and add the paths to test and train.txt (which is used in .yml file), and run the training again for few epochs, using the parameter --weights which is the last best.pt (to not running a full training again for few images)

But when the process scan all files, my new folder seems not to be listed.

Which is the best way to achieve this correctly ? Maybe my method is not the best one.

Thanks for your help,

Kind regard,
Florian

**Comment by glenn-jocher** [comment]
@FlorianRuen you can specify multiple datasets for simultaneous training in your dataset.yaml file, just make sure they share the same classes:
https://github.com/ultralytics/yolov5/blob/901243c7806be07b31073440cf721e73532a0734/data/coco128.yaml#L12-L15

**Comment by FlorianRuen** [comment]
@glenn-jocher I'm doing the same, but in another way, I got test.txt and train.txt with all my images path (from many datasets with same classes), and I specify the path:

```
# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/] 
train: /home/..../train.txt
val:  /home/..../test.txt
```

So all my dataset should be take into account. In train command I take my last batch (which is 299/300 epochs weights and I use the same .yaml, add the --resume and --epochs 350), it train, but my news images doesn't appear on tensorboard for example
