### ISSUE TITLE
Can not export to edgetpu model

### ISSUE THREAD

**Issue by walterwangimagr** [ultralytics/yolov5#8842]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Export

### Bug

I was following the tutorial to train a model and export to edgetpu model. 
When I use the coco128.yaml as dataset, it was fine I can train and export 
But when I use a custom dataset with only one class, it fail on the step tflite -> edgetpu 
I also try with the similar dataset GlobalWheat2020.yaml, same issue. Is there an extra step I need to do or it is a bug?
I use the docker image provided and install tensorflow 2.9.1 for export
Training script 
`python train.py --img 640 --batch 16 --epochs 3 --data coco128.yaml --weights yolov5s.pt --name coco128`
Export script 
`python export.py --img 640 --data data/coco128.yaml --weights runs/train/coco128/weights/best.pt --include edgetpu`
And this work fine 

Training script 
`python train.py --img 640 --batch 16 --epochs 3 --data GlobalWheat2020.yaml --weights yolov5s.pt`
Export script
`python export.py --img 640 --data data/GlobalWheat2020.yaml --weights runs/train/exp19/weights/best.pt --include edgetpu`
Run into error 
![image](https://user-images.githubusercontent.com/105331780/182506334-41a31d17-f219-49a1-9e5f-cb974212a3fc.png)

### Environment

-Docker images provided 
-install tensorflow 2.9.1

### Minimal Reproducible Example

```
# start docker 
sudo docker run -it --gpus '"device=1,2,3"' -v `pwd`:/workspace --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 ultralytics/yolov5 /bin/bash

# install tensorflow 
pip install tensorflow 

# train 
python train.py --img 640 --batch 16 --epochs 3 --data data/GlobalWheat2020.yaml --weights yolov5s.pt

# export 
python export.py --img 640 --data data/GlobalWheat2020.yaml --weights runs/train/exp17/weights/best.pt --include edgetpu
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@walterwangimagr thanks for the bug report! I'll try to reproduce using your commands.

**Comment by glenn-jocher** [comment]
@walterwangimagr yes I'm able to reproduce. Very strange, not sure what the problem might be.
```
!python train.py --img 640 --batch 16 --epochs 3 --data GlobalWheat2020.yaml --weights yolov5s.pt
!python export.py --img 640 --weights runs/train/exp2/weights/best.pt --include edgetpu
```

VOC (20cls) also fails. Edge TPU seems to be failing for all non-80 class datasets. Perhaps 80 is hardcoded somewhere in the conversion process. I'll investigate tomorrow.

```
!python train.py --img 640 --batch 16 --epochs 3 --data VOC.yaml --weights yolov5s.pt
!python export.py --img 640 --data VOC.yaml --weights runs/train/exp3/weights/best.pt --include edgetpu
```

**Comment by glenn-jocher** [comment]
@zldrobit I might need some advice here. Edge TPU export is failing for non-COCO models. I'm not sure what the cause is. Export works for coco128 but fails for VOC and GlobalWheat2020 trained models (see above).

TFLite int-8 export works correctly for both prior to Edge TPU failure. What do you think?

<img width="1435" alt="Screen Shot 2022-08-04 at 2 32 37 AM" src="https://user-images.githubusercontent.com/26833433/182738085-ceb37c9f-c09b-499a-a2c2-f4f38990567c.png">

**Comment by zldrobit** [comment]
@glenn-jocher I could confirm that using the default setting (`edgetpu_compiler -s -o`) cannot export an EdgeTPU model for VOC (20 classes) or globalwheat (1 class). I searched through the export architecture with `edgetpu_compiler -s -d` (as suggested in https://github.com/google-coral/edgetpu/issues/450#issuecomment-905480561), and the best model I could get has almost 130 ops running on CPU:
![image](https://user-images.githubusercontent.com/3896992/183385288-18fa34d5-4a17-490b-9ff5-17ff556b9aa8.png)
You could reproduce this result immediately with `edgetpu_compiler -s -i "model/tf_detect/Reshape_1,model/tf_detect/Reshape_3,model/tf_conv_33/mul_1,model/tf_conv_51/mul_1" globalwheat-int8.tflite` or search the export architecture from scratch with `edgetpu_compiler -s -d globalwheat-int8.tflite`. The VOC model could be exported to EdgeTPU format in the same way.

**Comment by walterwangimagr** [comment]
I had look at some posts on 
https://github.com/google-coral/edgetpu/issues/449 and https://github.com/google-coral/edgetpu/issues/405 looks like it could because the resolution limitation. But the weird thing is coco128 is able to use img 640 with 80 classes and any other num of classes will fail. I will try to train some model with lower img size to confirm

**Comment by walterwangimagr** [comment]
I had experience another weird behaviour, If I change the class name in the coco128.yaml
![image](https://user-images.githubusercontent.com/105331780/183399440-da0a4fc5-57c0-448a-a46b-353438c0a0ac.png)
After training and export to edgetpu.tflite, when I use the edgetpu model to run detect.py, it will still predict as 'person'
![image](https://user-images.githubusercontent.com/105331780/183399732-fb1be866-31eb-4d00-a212-59386aa35823.png)

**Comment by glenn-jocher** [comment]
@walterwangimagr class names are embedded as model attributes after training finishes, i.e. `model.names`. 

@zldrobit ok thanks for the results! Do you think we should update Edge TPU export to `edgetpu_compiler -s -i` or `edgetpu_compiler -s -d`? Let me know what the best option is and I will create a PR to resolve this.

**Comment by glenn-jocher** [comment]
@zldrobit I don't think we can use the -i argument as we don't know the output layer names ahead of time for the different sized models. I tested `edgetpu_compiler -s -d` with COCO128 and VOC. The COCO128 results are the same (in the same time), the VOC results work while taking a lot longer, but the important thing is they work, so I'll create a PR to add the `-d` argument to all Edge TPU exports.

**Comment by glenn-jocher** [comment]
@walterwangimagr good news 😃! Your original issue may now be fixed ✅ in PR #8902 by adding a --search-delegate argument to Edge TPU model compilation per @zldrobit's solution above.

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by walterwangimagr** [comment]
Thank you very much

**Comment by glenn-jocher** [comment]
@walterwangimagr you're welcome! If you need further assistance or have other questions, feel free to ask. Happy to help!
