### ISSUE TITLE
tensorflow yolov5s model flops calculation

### ISSUE THREAD

**Issue by jungae-park** [ultralytics/yolov5#8844]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Can the model converted to tensorflow framework also calculate flops with profile(thop) in torch_utils code?

**Comment by glenn-jocher** [comment]
@jungae18 exported models are identical, FLOPs are identical
