### ISSUE TITLE
AssertionError: Invalid CUDA '--device 0' requested, use '--device cpu' or pass valid CUDA device(s)

### ISSUE THREAD

**Issue by shubhambagwari** [ultralytics/yolov5#8848]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I was trying to train yolov5 on the custom dataset.
I was following this documentation [https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data](https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data)

When I was compiling the code, it worked fine on the CPU but not with GPU (ex: --device 0,1). While accessing the GPU, I am getting errors.

```
 f"Invalid CUDA '--device {device}' requested, use '--device cpu' or pass valid CUDA device(s)"
AssertionError: Invalid CUDA '--device 0' requested, use '--device cpu' or pass valid CUDA device(s)
``` 

I saw some previous issues and discussions that are not working for me. 
i) [https://github.com/ultralytics/yolov5/issues/7277](https://github.com/ultralytics/yolov5/issues/7277)
ii) [https://github.com/ultralytics/yolov5/issues/474](https://github.com/ultralytics/yolov5/issues/474)
iii) [https://docs.ultralytics.com/tutorials/multi-gpu-training/](https://docs.ultralytics.com/tutorials/multi-gpu-training/)

Still, I am searching for a solution.  
How can I train the model on a custom dataset with the help of GPU?

 

### Additional
When I run code normally, it takes CPU by default.
![yv5_3](https://user-images.githubusercontent.com/25363312/182595102-f4459ffc-cd17-49cf-ad55-b8faff52079d.JPG)

**Comment by glenn-jocher** [comment]
@shubhambagwari it appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual [Python 3.9](https://www.python.org/) environment, clone the latest repo ([code changes daily](https://github.com/ultralytics/yolov5/commits/master)), and `pip install` [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) again from scratch.

💡 ProTip! Try one of our verified environments below if you are having trouble with your local environment.


## Requirements

[**Python>=3.7.0**](https://www.python.org/) with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) installed including [**PyTorch>=1.7**](https://pytorch.org/get-started/locally/). To get started:
```bash
git clone https://github.com/ultralytics/yolov5  # clone
cd yolov5
pip install -r requirements.txt  # install
```

[Models](https://github.com/ultralytics/yolov5/tree/master/models) and [datasets](https://github.com/ultralytics/yolov5/tree/master/data) download automatically from the latest YOLOv5 [release](https://github.com/ultralytics/yolov5/releases) when first requested.

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), validation ([val.py](https://github.com/ultralytics/yolov5/blob/master/val.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/export.py)) on MacOS, Windows, and Ubuntu every 24 hours and on every commit.

**Comment by shubhambagwari** [comment]
@glenn-jocher Yeah, I have created a new virtual environment in Python 3.9. Still, the problem is the same.
![image](https://user-images.githubusercontent.com/25363312/182838035-be2faa59-f221-4d10-bcde-f734bac7a5b2.png)

**Comment by shubhambagwari** [comment]
@glenn-jocher Yeah, I have created a new virtual environment in Python 3.9. Still, the problem is the same.
![image](https://user-images.githubusercontent.com/25363312/182838216-fc8953a8-7459-4b2c-a226-479a9b8e4657.png)

**Comment by shubhambagwari** [comment]
`pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio===0.9.0 -f https://download.pytorch.org/whl/torch_stable.html`

**Comment by yangboz** [comment]
also it happens at referencing while defining  yolov5 = YOLOv5(model_path, device)

**Comment by Smokedhammer** [comment]
> pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio===0.9.0 -f https://download.pytorch.org/whl/torch_stable.html

Thanks so much! Spent hours trying to find the solution. Also, after this, instead of using my jupyter notebook, I ran the train command directly from the command line, this made it work somehow!

**Comment by glenn-jocher** [comment]
@Smokedhammer great to hear that the issue is resolved! Running the train command from the command line can indeed bypass potential issues related to Jupyter notebooks. If you encounter any further difficulties or have more questions, feel free to reach out. Happy coding!
