### ISSUE TITLE
Roadmap: instance segmentation & next version (v6.2, v7.0)

### ISSUE THREAD

**Issue by jamjamjon** [ultralytics/yolov5#8854]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, how's going with instance segmentation project?  And when will release next version(v6.2, v7.0)? Thanks.

**Comment by AyushExel** [comment]
@jamjamjon We're working on the instance segmentation and classification support and you'll hear from us very soon. We're making sure that every task we add it easy to understand and use, like the detection task.

cc @Laughing-q @glenn-jocher

**Comment by jamjamjon** [comment]
That's great! Thanks for your great job!

**Comment by Zephyr69** [comment]
> @jamjamjon We're working on the instance segmentation and classification support and you'll hear from us very soon. We're making sure that every task we add it easy to understand and use, like the detection task.
> 

Would the segmentation head be able to run in parallel (in a multi-task fashion) with the detection head, with different sets of classes (like YOLOP or this repo did https://github.com/midasklr/yolov5ds)?
It would be convenient for some robotic applications.

**Comment by AyushExel** [comment]
@Zephyr69  If by parallel multi-task you mean detection and segmentation simultaneously, then yes.. You'll see the bboxes and masks at the same time. And you can train your models on as many classes as you'd like
