### ISSUE TITLE
wandb sweep

### ISSUE THREAD

**Issue by junghyun-avikus** [ultralytics/yolov5#8855]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

In case of using multiple gpus, running torch.distributed.run with -m torch.distributed.run --nproc_per_node 4 argument added to it  seems to be recommended .

Then is there a way to run this module when I use wandb sweep? What modification am I supposed to make?

Also, when I utilize my 4 rtx 3090, they don't seem to be running at high efficiency. Their usage frequently dropped to 0 - 10% during the training. Also while 3 gpus are 100% used, the last gpu is used 0%. What might be possible causes for this type of issues? (All of my data are stored in a single SSD. The cpu is highest-end in i9 series, not xeon)

**Comment by glenn-jocher** [comment]
@junghyun-avikus 👋 Hello! Thanks for asking about **training speed issues**. YOLOv5 🚀 can be trained on CPU (slowest), [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) (fastest). If you would like to increase your training speed some options are:

- Increase `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s
- Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) DDP at larger `--batch-size`
- Train on cached data: `python train.py --cache` (RAM caching) or `--cache disk` (disk caching)
- Train on faster GPUs, i.e.: P100 -> V100 -> A100
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

Good luck 🍀 and let us know if you have any other questions!
