### ISSUE TITLE
model cannot be unloaded unless program is terminated

### ISSUE THREAD

**Issue by tai-nguyenh-tpv-otsv** [ultralytics/yolov5#8856]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to unloading the first Yolov5 model to free vRAM for loading the second Yolov5 model. But i not found unload model function in Yolov5 Repo. Please help me !

**Comment by glenn-jocher** [comment]
@tai-nguyenh-tpv-otsv in python you can delete any variable you want with del:
```
del model
```
