### ISSUE TITLE
init_seeds

### ISSUE THREAD

**Issue by 851624623** [ultralytics/yolov5#8858]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

In the judgment statement of the init_seeds function, which Settings require Torch version 1.12.0 and above？I can't find it

**Comment by glenn-jocher** [comment]
@851624623 https://github.com/ultralytics/yolov5/blob/628c05ca6ff1d7f79d1fc63c298008a1341ba99c/utils/general.py#L198-L214
