### ISSUE TITLE
can't use cuda

### ISSUE THREAD

**Issue by liguoyu666** [ultralytics/yolov5#886]
I create a conda env as your requirements:
cuda: 10.1
python 3.8.0
pytorch 1.6.0
torchvision: 0.7.0
but I can't use the cuda.
`import torch
print(torch.cuda.is_available())   # False `

**Comment by liguoyu666** [comment]
My previous cuda version was 10.0，today I install cuda 10.1,  conda environments are OK such as yolov4, except yolov5. 

![image](https://user-images.githubusercontent.com/47743761/91709657-a2228280-ebb5-11ea-9716-51510633ff9d.png)

docker pull ultralytics/yolov5,  In the docker environment，the cuda can't be used either.

![image](https://user-images.githubusercontent.com/47743761/91710644-3214fc00-ebb7-11ea-8cff-8a12b8f37213.png)

**Comment by learncrazy** [comment]
You can check whether the configuration path of cuda is correct?  I remember that you need to add the path of the new version of cuda10.1 to    .bashrc      (in fact, you only need to modify the original cuda10.0 to 10.1).

**Comment by liguoyu666** [comment]
In fact, I installed cuda 10.0 and cuda10.1, and I modify the original cuda 10.0 to 10.1.
yolov3 and yolov4 can use cuda in their environment. 
This seems to be caused by a mismatch between the cuda version and the pytorch version.
![image](https://user-images.githubusercontent.com/47743761/91783931-27e51300-ec34-11ea-9c22-048fe671ebaa.png)

**Comment by liguoyu666** [comment]
> You can check whether the configuration path of cuda is correct? I remember that you need to add the path of the new version of cuda10.1 to .bashrc (in fact, you only need to modify the original cuda10.0 to 10.1).

In fact, I installed cuda 10.0 and cuda10.1, and I modify the original cuda 10.0 to 10.1.
yolov3 and yolov4 can use cuda in their environment. 
This seems to be caused by a mismatch between the cuda version and the pytorch version.
![image](https://user-images.githubusercontent.com/47743761/91783931-27e51300-ec34-11ea-9c22-048fe671ebaa.png)

**Comment by liguoyu666** [comment]
In the yolov5 environment, I change pytorch 1.6.0 to 1.4.0,  torch.cuda.is_available() is True.
I uninstall cuda 10.0 and 10.1, then reinstall cuda 10.1, the same problem remains: in pytorch 1.6.0, torch.cuda.is_available() is False; in pytorch 1.2.0 and 1.4.0, torch.cuda.is_available() is True.
My driver version is 430.40.

**Comment by learncrazy** [comment]
You can try it and download torch again. Use the command pip install torch==1.6.0+cu101, which may be useful.

**Comment by liguoyu666** [comment]
> You can try it and download torch again. Use the command pip install torch==1.6.0+cu101, which may be useful.

Because I changed the source of pip, using pip install torch==1.6.0+cu101 can't install, so I installed it according to the official Python installation:
`pip install torch==1.6.0+cu101 torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html`,
the cuda can be cused. Thank you!
