### ISSUE TITLE
Subclasses and superclasses training

### ISSUE THREAD

**Issue by mfaizan-ai** [ultralytics/yolov5#8864]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi Glenn, I would like to ask I am detecting head and person. These are super classes, in head, I would like to make male, female, and unknown subclasses. I want my detector to detect person and head, but it should give classification output of male, female, and unknown (person with no clear view) classes. I want to count male, female, and unknown during each frame detection. Is possible to label data like that? or how to approach this problem with yolov5?

**Comment by glenn-jocher** [comment]
@faizan1234567 YOLOv2 aka YOLO9000 did some good work in this area, you might want to read that paper:
https://arxiv.org/abs/1612.08242

![image](https://user-images.githubusercontent.com/26833433/182876498-2953010b-603e-4b2d-9180-2424669116a5.png)

**Comment by mfaizan-ai** [comment]
Thanks Glenn, I have read the paper. However, there is no such thing they mentioned for joint training for classification and detection in their repository implementation. Can't we play with yolov5 model to take labels such as following
super class sub class x y h w?
1                      0         - - - -   
and then at the output we return something like: nc= [super classes, sub classes] and detection ? I have 2 parent classes person and head. And, I have 3 child classes of class head and no child class for person class. Generally, I would like to detect parent classes with bounding boxes, however, I need number of child classes in an given image. For instance, in an given image there are 10 person and 10 heads, I want to detect 10 persons and 10 heads as normal detection. Further, the model should tell that there are 10 child classes. Let's suppose in 10 of those child classes, there are 4 females, 4 males, and 2 unknown. I need to count this. I have done it by changing code in detect.py but I want my model to return prediction in the form of child classes probability and parent class provability, so that i can get meaningful results from that. 


I will be grateful for your insight on this issue.

**Comment by farhadulh98** [comment]
@faizan1234567 any succes in that regard? Refereeing to detecting and counting of male and females.

**Comment by mfaizan-ai** [comment]
Yes, I have trained detectors on male and female head classes, which gave reasonably good results.

**Comment by glenn-jocher** [comment]
@faizan1234567 nice work! Those are interesting use cases. YOLOv5 can indeed handle this task. 

To train on parent and child classes, you can modify the dataset labels to include superclass and subclass information, and then use the modifications during the training process. For counting the child classes during inference, you can customize the model's output to include subclass probabilities and parent class probabilities.

For detailed guidance on modifying dataset labels and customizing the model's output, refer to the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/. Additionally, you can explore the YOLOv5 codebase to see how you can make these customizations effectively.

Let me know if you have additional questions or need further assistance!
