### ISSUE TITLE
Is there a local application that I can use other than Weights & Biases arguments?

### ISSUE THREAD

**Issue by sarpx** [ultralytics/yolov5#8867]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is there a local application that I can use other than Weights & Biases arguments? Or how can I see if the tags on only some images are included in the training and how it affects the training results.

**Comment by glenn-jocher** [comment]
@sarpx I don't understand your question. You can view CSV or TensorBoard logging results instead of W&B. See Colab notebook for examples in Visualize section.
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb?hl=en

**Comment by sarpx** [comment]
@glenn-jocher  runs/train/exp2, runs/train/exp3
folders
It doesn't occur in my tutorials. I thought it was because I turned off Weights & Biases arguments.
Thank you for your attention.
Am I tiring you too much?

**Comment by glenn-jocher** [comment]
@sarpx local logging always occurs. Your console will print out where your training results are logged to, typically runs/train/exp etc, unless you've specified a --name and --project, in which case it will log to yolov5/project/name

https://github.com/ultralytics/yolov5/blob/84e7748564f83ba04601770f17a38cc55e6be661/train.py#L459-L461

![image](https://user-images.githubusercontent.com/26833433/182928077-2f1ce27f-e4f5-477c-b0d8-6f24566b1199.png)

**Comment by sarpx** [comment]
@glenn-jocher Yes, I understand them. Yes there are these. But here's the thing. When I look at the mosaics, I see that some of the labels are not included in the training. Mosaic image has picture but no label. But there are labels in the label.txt file. This made me suspicious. What goes into training? The W&B plugin is sending information to the outside. This is against our contract. The pictures we have are not our property, but the company that gave us permission shared them under limited conditions, we cannot go beyond this. If these pictures come out tomorrow, they may say that you have made the pictures public. But I need to follow my tutorial picture picture tag tag. The results.csv file only shows average values.

The 0-index label in the A picture entered the training, the effect is something like this.

**Comment by glenn-jocher** [comment]
@sarpx if your mosaic has incorrect labels then your dataset may be incorrectly labelled. You can use TensorBoard locally.

**Comment by sarpx** [comment]
@glenn-jocher glenn jocher you are definitely my idol and inspirational. I think even 100 years later there will be a man named Glenn Jocher.

confusion_matrix.png is a great invention. Of course, you may not have found it, but yolov5 it's great that you integrated it. It's not a question, I wish I had it, I would publish confusion_matrix.png after every 100 training cycles. This way we could see how the mixing changed over time. Also, maybe we could decide to teach more or less.

**Comment by glenn-jocher** [comment]
@sarpx thanks! Yes, lots of work to be done everywhere. I'd like to make the plots interactive too, and like you said update dynamically during training.

**Comment by sarpx** [comment]
@glenn-jocher I don't know if there is such a thing, but tag-based training cycle adjustment may be necessary in the future. Because getting the best results of different objects in a single training cycle is a bit like generalizing. But training the tags separately reduces consistency. Then all tags will enter training together, but some will leave training early. I think about such things, but I hope my ignorance has not been exposed.

**Comment by glenn-jocher** [comment]
@sarpx Interesting idea! It's called curriculum learning actually, and is a great research area for future work. Thanks for sharing!
