### ISSUE TITLE
How to read R_curve

### ISSUE THREAD

**Issue by FranciosoDonato** [ultralytics/yolov5#8868]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I'd like to know how read the R_curve. Precision is okay, i have at least 0.905 confidence to have 100% of precision, but i can't understand recall. I have, for example, 0.8 confidence to have 80% of recall according to my recall results?

![R_curve](https://user-images.githubusercontent.com/110238121/182912199-fbff6c5a-7c90-44de-bf44-4f00e283ad9a.png)

![P_curve](https://user-images.githubusercontent.com/110238121/182912482-3d38dea1-60e1-4e12-b124-d343e746d530.png)

**Comment by glenn-jocher** [comment]
@FranciosoDonato the higher the confidence the less Recall and the higher the Precision. Your Best Possible Recall is around 0.95.

**Comment by FranciosoDonato** [comment]
> @FranciosoDonato the higher the confidence the less Recall and the higher the Precision. Your Best Possible Recall is around 0.95.

Little question, confidence mean confidence threshold right?

**Comment by glenn-jocher** [comment]
@FranciosoDonato yes confidence threshold
