### ISSUE TITLE
Is it possible to save the results of the val.py file to the 4th decimal point?

### ISSUE THREAD

**Issue by wch243294382** [ultralytics/yolov5#8872]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is it possible to save the results of the val.py file to the 4th decimal point?
now it only have the 3th decimal point。
Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 703/703 [10:27
                 all      44933     490000      0.942      0.808      0.892      0.618

**Comment by glenn-jocher** [comment]
@wch243294382 you can modify val.py yourself:
https://github.com/ultralytics/yolov5/blob/2794483e091d50416289614a1a35f158fd25bee2/val.py#L273-L283
