### ISSUE TITLE
@glenn-jocher Yeah, I have created a new virtual environment in Python 3.9. Still, the problem is the same.

### ISSUE THREAD

**Issue by shubhambagwari** [ultralytics/yolov5#8875]
@glenn-jocher Yeah, I have created a new virtual environment in Python 3.9. Still, the problem is the same.
![image](https://user-images.githubusercontent.com/25363312/182838216-fc8953a8-7459-4b2c-a226-479a9b8e4657.png)

_Originally posted by @shubhambagwari in https://github.com/ultralytics/yolov5/issues/8848#issuecomment-1205140316_

**Comment by glenn-jocher** [comment]
@shubhambagwari this is a pytorch issue unrelated to YOLOv5. See https://pytorch.org/get-started/locally/ to install correctly

**Comment by shubhambagwari** [comment]
@glenn-jocher, which version of Cuda and python will work fine?
Can you help while being specific version?

**Comment by glenn-jocher** [comment]
See https://pytorch.org/get-started/locally/

**Comment by shubhambagwari** [comment]
@glenn-jocher same error. 
I tried. Any recommendation?

1) 
![image](https://user-images.githubusercontent.com/25363312/183573604-db00ee01-3f57-4676-9431-35b954b2d7f5.png)

2) 
![image](https://user-images.githubusercontent.com/25363312/183573683-2ab858b8-7623-4dd8-b8f4-acdeb4f3742b.png)

**Comment by shubhambagwari** [comment]
`pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio===0.9.0 -f https://download.pytorch.org/whl/torch_stable.html`

**Comment by glenn-jocher** [comment]
@shubhambagwari you should install PyTorch with CUDA 11.1 as specified in their installation guide. The command is: 

```
pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html
```

This should help resolve the issue.
