### ISSUE TITLE
Yolo V7

### ISSUE THREAD

**Issue by apiszcz** [ultralytics/yolov5#8878]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Yolo V7 variants are emerging, however they lag the features and capabilities of Yolo V5.
Is there any effort to consider V7 improvements in the future roadmap?
Thanks.

**Comment by glenn-jocher** [comment]
@apiszcz yes, we have ongoing R&D efforts in a few areas. We are currently working on YOLOv5 classification support in https://github.com/orgs/ultralytics/projects/4 scheduled for a v6.2 release this month and then YOLOv5 segmentation support in https://github.com/orgs/ultralytics/projects/6 scheduled for release v6.3 next month, to be followed by a new major v7.0 release afterward incorporating new community improvements to YOLO architectures.

@AyushExel

**Comment by apiszcz** [comment]
Great news, thank you for the continued efforts on this platform.

**Comment by glenn-jocher** [comment]
@apiszcz you're welcome! The YOLOv5 platform is a collaborative effort involving the entire YOLO community, and we're excited to continue pushing the boundaries of object detection together. If you have any other questions or suggestions, feel free to share them. Happy detecting!
