### ISSUE TITLE
Caching images failed in v6.1 DDP training using --cache 'disk'

### ISSUE THREAD

**Issue by dao027** [ultralytics/yolov5#8879]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

it's strange my **yolov5s_v6.1** training goes wrong during Caching images while using --cache 'disk':

![7de08f0be463515acfe2f7b0259609d](https://user-images.githubusercontent.com/35993172/183065807-3ec60e61-a2ae-4415-b33a-cc26d088a877.png)

training command:
`python -m torch.distributed.run --nproc_per_node 4 train.py --epochs 300 --batch-size 128 --data data/base_trainset_v1.2_20220607.yaml --weights weights/yolov5s_p5_v6.1.pt --device 0,1,2,3 --img 640 --cache 'disk'`

which confuses me mostly , **training was all good while using v6.0 (params and hyps, commands are just the same)** 

PS: **HDD space is sufficient** (>10T)
NVIDIA GeForce RTX 3090 * 4
RAM 128G

**Comment by glenn-jocher** [comment]
@dao027 it looks like there might be a compatibility issue with caching images in v6.1. Thank you for providing all the necessary details. We will investigate this further and work on resolving the issue as soon as possible.

In the meantime, you might consider using v6.0 for your training as it was working fine previously with the same parameters. We appreciate your patience and understanding.
