### ISSUE TITLE
The framework

### ISSUE THREAD

**Issue by Ichalfians** [ultralytics/yolov5#8886]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

can i use darknet framework as backbone in YOLO V5?

**Comment by glenn-jocher** [comment]
@Ichalfians you can do anything you want if you're willing to put in the work
