### ISSUE TITLE
General question about time/it, memory usage and training performance

### ISSUE THREAD

**Issue by rlewkowicz** [ultralytics/yolov5#8890]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Sorry if this has been asked, it's difficult to search for "it". What is this? Does this indicate training performance speed? On a single GPU, lets say 3090ti on linux with images ram cached. Image size is dynamic, nothing greater than 900x900. Whats a good it/s? Excuse my ignorance, I don't know know what the first and second passes represent. I think it's training and validation. On that first pass, I'm seeing 1-3its/s. Second pass I see 1-1.5s/it I feel like this speeds up in later passes? I feel like sometimes validation cranks and training is slow. 

With that 3090ti alone, I've got 24gb of ram. I feel like I can't use more than 12 of it if I'm lucky. I've actually got a 2080ti and the 3090ti. Overall I should have something like 36 gigs to play with. gpu_mem is always under 11, and I get oom errors pass anything more. Even just trying to use the 3090ti.

**Comment by yuyang3478** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by MartinPedersenpp** [comment]
The it/s is from the progress bar library called tqdm
It is iterating over the dataloader with x iterations per second.
So depending on your hardware and dataset size + batch size, the it/s will vary.
I am training on 200K images with an A6000 GPU and I get like 2-3 it/s
I hope this helps

Edit:
Regarding the last part of your question. If you increase your batch size, the training will consume more of your GPU. You can pass -1 batch size for auto batch sizing. You just need to make sure you have enough RAM and Disk capacity to carry the biggest batch size.

**Comment by rlewkowicz** [comment]
I'm going to close this, but just a little extra info. With multi GPU training, I think what happens is pytorch allocates a pretty big chunk of memory and additionally, given the card imbalance, it still tries an even spit. I still find the cards in parallel to be marginally faster than the 3090ti alone.

**Comment by glenn-jocher** [comment]
@rlewkowicz thanks for sharing your insights! It's great to learn from the community's experiences. Also, if you ever need more information, feel free to check out our Ultralytics Docs at https://docs.ultralytics.com/yolov5/. Happy coding!
