### ISSUE TITLE
loss question

### ISSUE THREAD

**Issue by DezeZhao** [ultralytics/yolov5#8892]
https://github.com/ultralytics/yolov5/blob/8f28ea4945495199ea236264ba36bf8f0a62c732/train.py#L313
hello, I have a question about this line, in DDP mode, when backward() is called, it will auto average gradient overall gpus, why here loss multiply wordsize? Besides, when computing loss in loss.py, why loss multiply batch_size ?

**Comment by glenn-jocher** [comment]
@DezeZhao both implementations are to allow loss to scale with batch size for SGD optimizers and produce repeatable results between DDP and Single-GPU.
