### ISSUE TITLE
runing train.py  error

### ISSUE THREAD

**Issue by seenthestars** [ultralytics/yolov5#8899]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Traceback (most recent call last):
  File "train.py", line 672, in <module>
    opt = parse_opt()
  File "train.py", line 518, in parse_opt
    parser.add_argumengt('--upload_dataset', nargs='?', const=True, default=False, help='W&B: Upload data, "val" option')
AttributeError: 'ArgumentParser' object has no attribute 'add_argumengt'

**Comment by AyushExel** [comment]
@seenthestars looks like you've edited the file. There's a typo in your code.
`parser.add_argumengt` should be `parser.add_argument`. Make this change and the code should work fine

**Comment by seenthestars** [comment]
Thank you very much!
