### ISSUE TITLE
utils.utils removed for v5?

### ISSUE THREAD

**Issue by jaqueline-lu** [ultralytics/yolov5#890]
## 🚀 Feature

Hi there, I am glad to see this new version coming out! 
One question is, I noticed that the "utils.py" file is missing in YOLOv5/utils. Is this on purpose? I tried to use the same command that I have used for v3:
```
from utils.utils import plot_results; plot_results()
``` 
but get an error saying there is not utils.utils. Will this feature be added to v5? 
Thank you so much!

**Comment by glenn-jocher** [comment]
@jaqueline-lu utils/utils.py has been renamed to utils/general.py
