### ISSUE TITLE
Add attention menchanism on yolov5

### ISSUE THREAD

**Issue by Pu-Zhengpeng** [ultralytics/yolov5#8901]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello author, many papers say that the attention mechanism can rise on yolov5.,such as SE,CBAM,ECA...  Has the author ever done this experiment? If i want to add it, where is the best place on the network? Can you give me some suggestions?Thanks for your reading.

**Comment by glenn-jocher** [comment]
@dapiaoGe I'd refer your questions to the authors of the papers you mentioned if you have questions about them
