### ISSUE TITLE
How to keep the class weight for coco 2017 when pre-train model

### ISSUE THREAD

**Issue by bzha5848** [ultralytics/yolov5#8904]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Hi there,

I'm currently doing fine-tuning with coco2017 as you used for weight, just wondering if there's any method or code to keep the coco class as the same weight while tran the novel class?

Thanks so much!!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by MartinPedersenpp** [comment]
The easiest way would be to add the coco2017 dataset to your novel dataset and train the model. This way you keep all the 80 coco classes and add your novel classes.
I am pretty sure that no matter what you do, the weights of the layers will get skewed away from the classes in coco2017, if the images and annotations are not in your training data.

**Comment by glenn-jocher** [comment]
@bzha5848 see https://community.ultralytics.com/t/how-to-combine-weights-to-detect-from-multiple-datasets/38/55
