### ISSUE TITLE
--save-crop

### ISSUE THREAD

**Issue by PriyamDalwadii** [ultralytics/yolov5#8905]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am working on project on object detection and saving the crop image of detection. I am using --save-crop flag but it creates duplicates of same image. How to just save one crop image instead of multiple crop images?

**Comment by glenn-jocher** [comment]
@PriyamDalwadii 👋 Hello! Thanks for asking about **cropping results** with YOLOv5 🚀.  Cropping bounding box detections can be useful for training classification models on box contents for example. This feature was added in PR https://github.com/ultralytics/yolov5/pull/2827. You can crop detections using either detect.py or YOLOv5 PyTorch Hub:

## detect.py
Crops will be saved under `runs/detect/exp/crops`, with a directory for each class detected.
```bash
python detect.py --save-crop
```
<img width="450" alt="Original" src="https://user-images.githubusercontent.com/26833433/139577918-65cc8f5d-741d-4a88-8753-0154013c624d.jpg">

<img width="1067" alt="Crop" src="https://user-images.githubusercontent.com/26833433/139577896-aa26b07c-466d-4057-9bfe-b01b56007587.png">

## YOLOv5 PyTorch Hub
Crops will be saved under `runs/detect/exp/crops` if `save=True`, and also returned as a dictionary with crops as numpy arrays.
```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, custom

# Images
img = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, PIL, OpenCV, numpy, list

# Inference
results = model(img)

# Results
crops = results.crop(save=True)  # or .show(), .save(), .print(), .pandas(), etc.
```

Good luck 🍀 and let us know if you have any other questions!

**Comment by PriyamDalwadii** [comment]
@glenn-jocher Hey! I am using python detect.py --source 1 --save-crop.
It is creating multiple  crop images of same detection. Any suggestion to store only 2-3 crop images of detected class? It is single detection. Thank you in advance

**Comment by glenn-jocher** [comment]
@PriyamDalwadii only one crop is produced per detection. If you have multiple crops you have multiple detections.

**Comment by PriyamDalwadii** [comment]
![Capture2](https://user-images.githubusercontent.com/108300073/183728606-9cd50d6e-e00f-4a42-84f1-e9c52152f9f8.PNG)
I have run inference using webcam. It has one detection in the frame.

following is the directory created by --save-crop.
![Capture](https://user-images.githubusercontent.com/108300073/183728959-51ed53d2-042e-4897-b69d-3c2edaaed979.PNG)

It creates tens of images in one or two seconds!

Is there something wrong with my code or it supposed to be like this?

**Comment by glenn-jocher** [comment]
@PriyamDalwadii this is probably just one image per frame as intended.

**Comment by PriyamDalwadii** [comment]
@glenn-jocher Absolutely, I don't know if i quite got it, but I don't know why it keeps cropping same image for multiple time? I hope you get my point. Any fix to just crop one image per 1 detection

**Comment by glenn-jocher** [comment]
@PriyamDalwadii I think you're not understanding. If your webcam is running at 30FPS you'll have 30 images processed in 1 second. If the object is in each image you'll have 30 crops in 1 second. Everything is working as intended.

**Comment by PriyamDalwadii** [comment]
oh! Great Thanks! @glenn-jocher

**Comment by sourabmaity** [comment]
After collecting all images you can remove them by checking the similarity search method from images.

**Comment by PriyamDalwadii** [comment]
> After collecting all images you can remove them by checking the similarity search method from images.

@sourabmaity  Thanks for the idea, do have any good resource that I can refer?

**Comment by sourabmaity** [comment]
you can check fastdup @PriyamDalwadii 
[https://github.com/visualdatabase/fastdup](fastdup)

**Comment by PriyamDalwadii** [comment]
> you can check fastdup @PriyamDalwadii [https://github.com/visualdatabase/fastdup](fastdup)

Thanks! This might help :D
