### ISSUE TITLE
I am making UI by QT for Yolov5 training. Where is making the result image (results.png) after training?  

### ISSUE THREAD

**Issue by star4s** [ultralytics/yolov5#8907]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am making UI by QT for Yolov5 training. Where is making the result image (results.png) after training?  

I would like to draw the graph for (train/box_loss), (metrics/precision), and (metrics/recall) per each an epoch every time an epoch of the train is finished.

 Where is making the result image (results.png) after training?  

Thank you for your help.

**Comment by MartinPedersenpp** [comment]
If you are in the Yolov5 directory then use:

```python
from utils.plots import plot_results
plot_results('PATHTO/results.csv')
```

**Comment by star4s** [comment]
@MartinPedersenpp 
Thank you for your help. I got It~

**Comment by MartinPedersenpp** [comment]
@star4s
You are welcome, please don't forget to close the issue if your problem has been solved 😉
