### ISSUE TITLE
Traininng Yolov5 by NHWC format to accelerate speed

### ISSUE THREAD

**Issue by Haoyanlong** [ultralytics/yolov5#8913]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to accelerate the training speed by NHWC of yolov5s, but I find the speed descend as follows.
Could you give me some advice?Thank you very much!
![image](https://user-images.githubusercontent.com/23288056/183643920-b549ba49-06db-421e-8ffc-b4695bacf69a.png)

codes as follows:
```python3
momory_format = torch.channels_last
model = model.to(device).to(memory_format=memory_format)
imgs = imgs.to(device, memory_format=torch.channels_last)

outs = model(imgs)
```

**Comment by glenn-jocher** [comment]
@Haoyanlong very interesting! Do you have the full benchmarking script? I wonder if you need to make the images and model parameters contiguous after the change?
https://pytorch.org/docs/stable/generated/torch.Tensor.contiguous.html
