### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

### ISSUE THREAD

**Issue by Chenzkun** [ultralytics/yolov5#8914]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello，@glenn-jocher 
When I run train.py with yolov5, after running the epoch, I get this problem。

Transferred 522/675 items from D:\Workspace\yolov5-master\weights\yolov5m6.pt
Scaled weight_decay = 0.00036
optimizer: SGD with parameter groups 103 weight, 155 weight (no decay), 107 bias
albumentations: CLAHE(always_apply=False, p=1, clip_limit=(1, 40), tile_grid_size=(8, 8))
train: Scanning 'data\coco128\labels\train2017.cache' images and labels... 1269 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 1269/1269 [00:00<?, ?it/s]
train: Caching images (3.7GB disk): 100%|██████████| 1269/1269 [00:00<00:00, 1432.19it/s]
val: Scanning 'data\coco128\labels\val2017.cache' images and labels... 155 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 155/155 [00:00<?, ?it/s]
val: Caching images (0.4GB disk): 100%|██████████| 155/155 [00:00<00:00, 1386.27it/s]
module 'signal' has no attribute 'SIGALRM'

AutoAnchor: 0.00 anchors/target, 0.000 Best Possible Recall (BPR). Anchors are a poor fit to dataset , attempting to improve...
AutoAnchor: Running kmeans for 8 anchors on 1348 points...
AutoAnchor: Evolving anchors with Genetic Algorithm: fitness = 0.8832: 100%|██████████| 1000/1000 [00:00<00:00, 2816.04it/s]
AutoAnchor: thr=0.23: 1.0000 best possible recall, 7.83 anchors past thr
AutoAnchor: n=8, img_size=640, metric_all=0.601/0.883-mean/best, past_thr=0.609-mean: 25,25, 33,33, 41,39, 46,48, 56,53, 66,65, 88,83, 110,115
AutoAnchor: Reversing anchor order
AutoAnchor: New anchors saved to model. Update model *.yaml to use these anchors in the future.
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to runs\m6-c3cbam\exp7
Starting training for 1 epochs...

     Epoch   gpu_mem       box       obj       cls    labels  img_size
       0/0     3.55G   0.06092   0.02275   0.02627         8       640: 100%|██████████| 159/159 [00:48<00:00,  3.31it/s]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 10/10 [00:01<00:00,  5.27it/s]
                 all        155        171    0.00426    0.00526   0.000231   4.22e-05

1 epochs completed in 0.014 hours.
Optimizer stripped from runs\m6-c3cbam\exp7\weights\last.pt, 64.0MB
Optimizer stripped from runs\m6-c3cbam\exp7\weights\best.pt, 64.0MB

Validating runs\m6-c3cbam\exp7\weights\best.pt...
Fusing layers... 
Traceback (most recent call last):
  File "D:/Workspace/yolov5-master/train.py", line 632, in <module>
    main(opt)
  File "D:/Workspace/yolov5-master/train.py", line 529, in main
    train(opt.hyp, opt, device, callbacks)
  File "D:/Workspace/yolov5-master/train.py", line 422, in train
    model=attempt_load(f, device).half(),
  File "D:\Workspace\yolov5-master\models\experimental.py", line 98, in attempt_load
    model.append(ckpt['ema' if ckpt.get('ema') else 'model'].float().fuse().eval())  # FP32 model
  File "D:\Workspace\yolov5-master\models\yolo.py", line 226, in fuse
    m.conv = fuse_conv_and_bn(m.conv, m.bn)  # update conv
  File "D:\Workspace\yolov5-master\utils\torch_utils.py", line 205, in fuse_conv_and_bn
    fusedconv.weight.copy_(torch.mm(w_bn, w_conv).view(fusedconv.weight.shape))
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

 my batch-szie=8，What should I do？

**Comment by glenn-jocher** [comment]
@Chenzkun this could be caused by simply running out of CUDA memory, I'd try reducing the batch size to 6 or 4. If the error still occurs you might try running training in our Docker image for the most reliable environment.

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

**Comment by Chenzkun** [comment]
> @Chenzkun this could be caused by simply running out of CUDA memory, I'd try reducing the batch size to 6 or 4. If the error still occurs you might try running training in our Docker image for the most reliable environment.
> 
> ## Environments
> YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):
> 
> * **Google Colab and Kaggle** notebooks with free GPU: [![Open In Colab](https://camo.githubusercontent.com/84f0493939e0c4de4e6dbe113251b4bfb5353e57134ffd9fcab6b8714514d4d1/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb) [![Open In Kaggle](https://camo.githubusercontent.com/a08ca511178e691ace596a95d334f73cf4ce06e83a5c4a5169b8bb68cac27bef/68747470733a2f2f6b6167676c652e636f6d2f7374617469632f696d616765732f6f70656e2d696e2d6b6167676c652e737667)](https://www.kaggle.com/ultralytics/yolov5)
> * **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/GCP-Quickstart)
> * **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/AWS-Quickstart)
> * **Docker Image**. See [Docker Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/Docker-Quickstart) [![Docker Pulls](https://camo.githubusercontent.com/280faedaf431e4c0c24fdb30ec00a66d627404e5c4c498210d3f014dd58c2c7e/68747470733a2f2f696d672e736869656c64732e696f2f646f636b65722f70756c6c732f756c7472616c79746963732f796f6c6f76353f6c6f676f3d646f636b6572)](https://hub.docker.com/r/ultralytics/yolov5)

But when I set batch-szie to -1, this problem occurs，
AutoBatch: Using batch-size 3 for CUDA:0 5.40G/6.00G (90%)
Scaled weight_decay = 0.00035437500000000004
optimizer: SGD with parameter groups 103 weight, 155 weight (no decay), 107 bias
albumentations: CLAHE(always_apply=False, p=1, clip_limit=(1, 40), tile_grid_size=(8, 8))
train: Scanning 'data\coco128\labels\train2017.cache' images and labels... 1269 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 1269/1269 [00:00<?, ?it/s]
train: Caching images (3.7GB disk): 100%|██████████| 1269/1269 [00:01<00:00, 798.35it/s]
val: Scanning 'data\coco128\labels\val2017.cache' images and labels... 155 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 155/155 [00:00<?, ?it/s]
val: Caching images (0.4GB disk): 100%|██████████| 155/155 [00:00<00:00, 752.53it/s]
module 'signal' has no attribute 'SIGALRM'

AutoAnchor: 0.00 anchors/target, 0.000 Best Possible Recall (BPR). Anchors are a poor fit to dataset , attempting to improve...
AutoAnchor: Running kmeans for 8 anchors on 1348 points...
AutoAnchor: Evolving anchors with Genetic Algorithm: fitness = 0.8832: 100%|██████████| 1000/1000 [00:00<00:00, 2919.17it/s]
AutoAnchor: thr=0.23: 1.0000 best possible recall, 7.83 anchors past thr
AutoAnchor: n=8, img_size=1280, metric_all=0.601/0.883-mean/best, past_thr=0.609-mean: 51,49, 67,65, 83,78, 91,95, 111,107, 131,130, 175,166, 221,230
AutoAnchor: Reversing anchor order
AutoAnchor: New anchors saved to model. Update model *.yaml to use these anchors in the future.
Image sizes 1280 train, 1280 val
Using 2 dataloader workers
Logging results to runs\m6-c3cbam\exp2
Starting training for 1 epochs...

     Epoch   gpu_mem       box       obj       cls    labels  img_size
  0%|          | 0/423 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "D:/Workspace/yolov5-master/train.py", line 632, in <module>
    main(opt)
  File "D:/Workspace/yolov5-master/train.py", line 529, in main
    train(opt.hyp, opt, device, callbacks)
  File "D:/Workspace/yolov5-master/train.py", line 328, in train
    scaler.scale(loss).backward()
  File "D:\anaconda\envs\yolov5-ssh\lib\site-packages\torch\_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "D:\anaconda\envs\yolov5-ssh\lib\site-packages\torch\autograd\__init__.py", line 156, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: :0: cudaGetLastError(): out of memory

What should I do？

**Comment by Chenzkun** [comment]
@glenn-jocher，But when I set batch-szie to -1, this problem occurs，
AutoBatch: Using batch-size 3 for CUDA:0 5.40G/6.00G (90%)
Scaled weight_decay = 0.00035437500000000004
optimizer: SGD with parameter groups 103 weight, 155 weight (no decay), 107 bias
albumentations: CLAHE(always_apply=False, p=1, clip_limit=(1, 40), tile_grid_size=(8, 8))
train: Scanning 'data\coco128\labels\train2017.cache' images and labels... 1269 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 1269/1269 [00:00<?, ?it/s]
train: Caching images (3.7GB disk): 100%|██████████| 1269/1269 [00:01<00:00, 798.35it/s]
val: Scanning 'data\coco128\labels\val2017.cache' images and labels... 155 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 155/155 [00:00<?, ?it/s]
val: Caching images (0.4GB disk): 100%|██████████| 155/155 [00:00<00:00, 752.53it/s]
module 'signal' has no attribute 'SIGALRM'

AutoAnchor: 0.00 anchors/target, 0.000 Best Possible Recall (BPR). Anchors are a poor fit to dataset , attempting to improve...
AutoAnchor: Running kmeans for 8 anchors on 1348 points...
AutoAnchor: Evolving anchors with Genetic Algorithm: fitness = 0.8832: 100%|██████████| 1000/1000 [00:00<00:00, 2919.17it/s]
AutoAnchor: thr=0.23: 1.0000 best possible recall, 7.83 anchors past thr
AutoAnchor: n=8, img_size=1280, metric_all=0.601/0.883-mean/best, past_thr=0.609-mean: 51,49, 67,65, 83,78, 91,95, 111,107, 131,130, 175,166, 221,230
AutoAnchor: Reversing anchor order
AutoAnchor: New anchors saved to model. Update model *.yaml to use these anchors in the future.
Image sizes 1280 train, 1280 val
Using 2 dataloader workers
Logging results to runs\m6-c3cbam\exp2
Starting training for 1 epochs...

 Epoch   gpu_mem       box       obj       cls    labels  img_size
0%| | 0/423 [00:01<?, ?it/s]
Traceback (most recent call last):
File "D:/Workspace/yolov5-master/train.py", line 632, in
main(opt)
File "D:/Workspace/yolov5-master/train.py", line 529, in main
train(opt.hyp, opt, device, callbacks)
File "D:/Workspace/yolov5-master/train.py", line 328, in train
scaler.scale(loss).backward()
File "D:\anaconda\envs\yolov5-ssh\lib\site-packages\torch_tensor.py", line 307, in backward
torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
File "D:\anaconda\envs\yolov5-ssh\lib\site-packages\torch\autograd_init_.py", line 156, in backward
allow_unreachable=True, accumulate_grad=True) # allow_unreachable flag
RuntimeError: :0: cudaGetLastError(): out of memory

What should I do？

**Comment by glenn-jocher** [comment]
@Chenzkun thanks for the bug report! It looks like AutoBatch pushed the ceiling too close in your case, and `--batch-size 2` rather than `--batch-size 3` would be the best option for you.

**Comment by Chenzkun** [comment]
@glenn-jocher，
Yes, I tried again to set the batch-size to 2, but again I had this problem
Image sizes 1280 train, 1280 val
Using 2 dataloader workers
Logging results to runs\m6\exp3
Starting training for 1 epochs...

     Epoch   gpu_mem       box       obj       cls    labels  img_size
       0/0     3.53G   0.04769   0.04115   0.02353         1      1280: 100%|██████████| 635/635 [02:23<00:00,  4.41it/s]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 39/39 [00:03<00:00, 11.12it/s]
                 all        155        171    0.00324     0.0526   0.000936   0.000234

1 epochs completed in 0.041 hours.
Optimizer stripped from runs\m6\exp3\weights\last.pt, 71.2MB
Optimizer stripped from runs\m6\exp3\weights\best.pt, 71.2MB

Validating runs\m6\exp3\weights\best.pt...
Fusing layers... 
Traceback (most recent call last):
  File "D:/Workspace/yolov5-master/train.py", line 639, in <module>
    main(opt)
  File "D:/Workspace/yolov5-master/train.py", line 536, in main
    train(opt.hyp, opt, device, callbacks)
  File "D:/Workspace/yolov5-master/train.py", line 422, in train
    model=attempt_load(f, device).half(),
  File "D:\Workspace\yolov5-master\models\experimental.py", line 98, in attempt_load
    model.append(ckpt['ema' if ckpt.get('ema') else 'model'].float().fuse().eval())  # FP32 model
  File "D:\Workspace\yolov5-master\models\yolo.py", line 226, in fuse
    m.conv = fuse_conv_and_bn(m.conv, m.bn)  # update conv
  File "D:\Workspace\yolov5-master\utils\torch_utils.py", line 205, in fuse_conv_and_bn
    fusedconv.weight.copy_(torch.mm(w_bn, w_conv).view(fusedconv.weight.shape))
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

Now I don't know what to do to solve the problem

> @Chenzkun感谢您的错误报告！看起来 AutoBatch 在您的情况下将天花板推得太近，`--batch-size 2`而不是`--batch-size 3`您的最佳选择。

**Comment by glenn-jocher** [comment]
@Chenzkun 👋 Hello! Thanks for asking about **CUDA memory issues**. YOLOv5 🚀 can be trained on CPU, [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training). When training on GPU it is important to keep your batch-size small enough that you do not use all of your GPU memory, otherwise you will see a CUDA Out Of Memory (OOM) Error and your training will crash. You can observe your CUDA memory utilization using either the `nvidia-smi` command or by viewing your console output:

<img width="800" alt="Screenshot 2021-05-28 at 12 19 51" src="https://user-images.githubusercontent.com/26833433/131122318-8141d1ce-13de-44bf-bbdc-487bad442ff0.png">

### CUDA Out of Memory Solutions

If you encounter a CUDA OOM error, the steps you can take to reduce your memory usage are:

- Reduce `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s > YOLOv5n
- Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) at the same `--batch-size`
- Upgrade your hardware to a larger GPU
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

Good luck 🍀 and let us know if you have any other questions!
