### ISSUE TITLE
Is the reason why the cpu usage is different for each data yaml (e.g coco, visdrone) related to the loss calculation?

### ISSUE THREAD

**Issue by YoungjaeDev** [ultralytics/yolov5#8921]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello. I used the command below to make the yaml different, but the cpu usage is twice as different (visdrone > coco) Is it because the amount of backward varies a lot depending on the number of objs that are predicated?
If I run using 4 gpu, there is a phenomenon that one gpu is continuously (taking turns) going down to 0% gpu-util, is it because there is a big difference in the loss calculation and the load of cpu increases?
Could you check it out?

```bash
train.py --data VisDrone.yaml --project gpu --weights yolov5m6.pt --epochs 60 --batch-size 60 --imgsz 960 --device 0,1,2 --noautoanchor
```

```bash
train.py --data coco.yaml --project gpu --weights yolov5m6.pt --epochs 60 --batch-size 60 --imgsz 960 --device 0,1,2 --noautoanchor
```

**Comment by glenn-jocher** [comment]
@youngjae-avikus 👋 Hello! Thanks for asking about **training speed issues**. YOLOv5 🚀 can be trained on CPU (slowest), [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) (fastest). If you would like to increase your training speed some options are:

- Increase `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s
- Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) DDP at larger `--batch-size`
- Train on cached data: `python train.py --cache` (RAM caching) or `--cache disk` (disk caching)
- Train on faster GPUs, i.e.: P100 -> V100 -> A100
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

Good luck 🍀 and let us know if you have any other questions!

**Comment by YoungjaeDev** [comment]
@glenn-jocher 

Yes, what I'm curious about is whether the amount of loss calculations can vary widely because the number of predictions varies from batch to batch if the data changes even with the same option. Thank you.

**Comment by glenn-jocher** [comment]
@youngjae-avikus Thanks for the clarification! The loss calculations do indeed vary based on the number of predictions in each batch. As the number of objects predicted differs between datasets, so do the loss calculations. This can lead to varying CPU usage. It's a known behavior, and it's one of the reasons behind the differences in CPU usage when training with different datasets. If you have any more questions or need further assistance, feel free to ask!
