### ISSUE TITLE
Limit the size of the input target

### ISSUE THREAD

**Issue by Zachary-ZCH** [ultralytics/yolov5#893]
If I only want to train the network that detects large targets and try to filter the training targets by limiting the area of the input boxes during the data loading process, how can I modify it?

**Comment by Aktcob** [comment]
https://github.com/ultralytics/yolov5/blob/master/utils/general.py#L592

To remove out the small object, u can add the code like:

        # Compute conf
        x[:, 5:] *= x[:, 4:5]  # conf = obj_conf * cls_conf
        mask = (x[:, 2]*x[:, 3]>size_threshold)        # (width * height)
        x = x*mask. # mask out the small obj
        # Box (center x, center y, width, height) to (x1, y1, x2, y2)
        box = xywh2xyxy(x[:, :4])
