### ISSUE TITLE
Use bounding box regression to create a class agnostic model 

### ISSUE THREAD

**Issue by Akhp888** [ultralytics/yolov5#8930]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi Guys ,

I was wondering if I can just use the bounding box regression in yolov5 to achieve a class agnostic detection ?

**Comment by glenn-jocher** [comment]
@Akhp888 you can train any dataset in single-class mode:
```bash
python train.py --single-cls
```

https://github.com/ultralytics/yolov5/blob/2e57b8418db137baafd38e71f885632badae4138/train.py#L456

**Comment by Akhp888** [comment]
> @Akhp888 you can train any dataset in single-class mode:
> 
> ```shell
> python train.py --single-cls
> ```
> 
> https://github.com/ultralytics/yolov5/blob/2e57b8418db137baafd38e71f885632badae4138/train.py#L456

Thanks Glenn.
Will check it out .
