### ISSUE TITLE
Background remove in Yolo ?

### ISSUE THREAD

**Issue by dazzafact** [ultralytics/yolov5#8932]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is there a way in Yolo not just to Annotate , but also to remove Background ? Where i can find?

### Additional

https://www.youtube.com/watch?v=_6B13tGHFvw

**Comment by AyushExel** [comment]
@biblekiss The creator in the linked video has used opencv background removal method. You can find those methods on opencv docs
