### ISSUE TITLE
Is the mean and standard deviation used in image normalization?

### ISSUE THREAD

**Issue by montmejat** [ultralytics/yolov5#8934]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,

I'm aware that models from `torchvision` (RetinaNet and FCOS for example) normalize the images before processing them using a mean and a standard deviation (not just `im /= 255`). I didn't find this practice to be used in YoloV5, I'm I wrong? Is there no point in doing this?

Here's what's done in FCOS for example: https://github.com/pytorch/vision/blob/main/torchvision/models/detection/fcos.py#L412-L415. I couldn't find any resources on how this kind of normalization can affect the performance, I'd be interested to know if anyone knows anything about this.

Thanks!

**Comment by glenn-jocher** [comment]
@aurelien-m hello,

The YOLOv5 model normalizes images using only `im /= 255` and does not employ mean and standard deviation normalization. This approach conforms to YOLOv5's design and has been extensively tested. Feel free to reach out if you have further questions, and thank you for your interest in YOLOv5.

Best regards
