### ISSUE TITLE
The results in the training process are different from those in the verification

### ISSUE THREAD

**Issue by SSF101** [ultralytics/yolov5#8938]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Why is the maximum value of map recorded in the CSV file during training different from the result obtained by best in Val?

### Additional

It is not the final result after the training, but the result recorded in the CSV during the training. Is it mainly because the model used in the training process is ema.ema, and the model. half() is used in the verification process？

**Comment by glenn-jocher** [comment]
@SSF101 they may be slightly different but they should be very close, essentially the same. Any differences would be due to argument differences when called natively.
