### ISSUE TITLE
What causes predictions to vary greatly with small difference in image?

### ISSUE THREAD

**Issue by Y-T-G** [ultralytics/yolov5#8939]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

The following are two consecutive frames from a video doing inference using YOLOv5m. You can see that the classes change between the frames, even though there's very little difference in how they look.

![download](https://user-images.githubusercontent.com/32206511/185440535-d7fc8ff3-a646-4ca2-a5ab-c6fcc5da31e9.gif)

Is there any explanation as to why this happens and is there any way to mitigate this perhaps through certain augmentations?

Thanks.

**Comment by isspid** [comment]
Can you elaborate on the solution, please?

**Comment by Y-T-G** [comment]
@isspid Issue was with my custom inference code. I was filtering the bounding boxes based on whether it was inside the blue region. But I did not filter the classes and scores, which resulted in the bounding boxes matching with wrong classes. But I will probably open this again as I have seen this issue genuinely in another case even with the YOLOv5 detect.py script.
