### ISSUE TITLE
training stuck when loading dataset

### ISSUE THREAD

**Issue by ljmiao** [ultralytics/yolov5#894]
## ❔Question
I follow the instructions to run coco128, 
```
python train.py --img 640 --batch 16 --epochs 5 --data ./data/coco128.yaml --cfg ./models/yolov5s.yaml --weights '',
```
the ouput is 
```
Image sizes 640 train, 640 test
Using 8 dataloader workers
Starting training for 5 epochs...

     Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
  0%|                                                                                                    | 0/8 [00:00<?, ?it/s
```
then it is stuck, I found that it is stucking at loading the dataset, 
in https://github.com/ultralytics/yolov5/blob/master/train.py#L244,  
```
for i, (imgs, targets, paths, _) in pbar:
```
it just stops here, could you help me ?

**Comment by NanoCode012** [comment]
Hi @ljmiao , could you try using another Environment listed above? 

I just ran your command in a new Docker, and there were no issues.

**Comment by ljmiao** [comment]
Thank you, I will try it

**Comment by jjfrog** [comment]
Set "--workers 0" works for me.
like this:
python train.py --img 640 --batch 16 --epochs 5 --data ./data/coco128.yaml --cfg ./models/yolov5s.yaml --weights '' --workers 0

**Comment by glenn-jocher** [comment]
@jjfrog --workers 0 will lead to very slow training. Recommend using one of our verified environments.

It appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below. 


## Requirements

**Python 3.8** or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including **`torch>=1.6`**. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by abuelgasimsaadeldin** [comment]
## Env

- OS: Windows
- Cuda version **10.2**
- GPU: RTX 2070 with Max-Q

Hi @glenn-jocher @ljmiao I am currently facing this issue. I have created several virtual conda environments, cloned the latest yolov5 repo and installed the ```requirements.txt``` dependencies but still this error is persistent:

## Command

```
python train.py --img 640 --batch 8 --epochs 300 --data data.yaml --weights yolov5s.pt
```

## Error
```
Transferred 356/362 items from yolov5s.pt
Scaled weight_decay = 0.0005
Optimizer groups: 62 .bias, 62 conv.weight, 59 other
train: Scanning 'train\labels.cache' images and labels... 3382 found, 0 missing, 4 empty, 0 corrupted: 100%|████████████████████████████████████████████████████████████| 3382/3382 [00:00<?, ?it/s]
val: Scanning 'valid\labels.cache' images and labels... 488 found, 0 missing, 1 empty, 0 corrupted: 100%|█████████████████████████████████████████████████████████████████| 488/488 [00:00<?, ?it/s]
Plotting labels...

autoanchor: Analyzing anchors... anchors/target = 3.68, Best Possible Recall (BPR) = 1.0000
Image sizes 640 train, 640 test
Using 0 dataloader workers
Logging results to runs\train\yolov5s_rotate_640_batch84
Starting training for 300 epochs...

     Epoch   gpu_mem       box       obj       cls     total    labels  img_size
  0%|                                                                                                                                                                       | 0/423 [00:00<?, ?it/s]
```

It is just stuck over here. Any help or suggestions would be highly appreciated.

Edit: I tested using a different dataset (little smaller) and it works fine but when switching back to my original dataset (3000+ training images) it gets stuck again. Very weird.

**Comment by glenn-jocher** [comment]
@abuelgasimsaadeldin it appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below. 


## Requirements

**Python 3.8** or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including **`torch>=1.7`**. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by abuelgasimsaadeldin** [comment]
Hi @glenn-jocher, thank you for the reply, it worked after reducing image size to 416 from 640. Thank you.

**Comment by ghost** [comment]
Hi @abuelgasimsaadeldin, when I run with the given(default) image size 640, It shows error. Then I changed it to 416, it started running? What is the reason? Explain in detail

**Comment by glenn-jocher** [comment]
Hi there! Reducing the image size to 416 from 640 can help alleviate memory constraints on your GPU, which might be causing the error at the larger size. Smaller images require less VRAM, which allows the model to train without exceeding the GPU's memory limit. If you want to use larger images but are limited by GPU memory, consider reducing the batch size or using a simpler model. Happy training! 😊

**Comment by jjfrog** [comment]
I think I've found the reason. I was training on Windows 10 and I only had about 30GB of space left on my C drive, which left the system with not enough virtual memory to work with. At this point my program would sometimes show that python had stopped responding and other times it would just get stuck. So I configured the other drives to be used as virtual memory and the problem was solved!

**Comment by pderrenger** [comment]
@jjfrog great troubleshooting! 🛠️ For future training runs, you might also consider monitoring your system's virtual memory usage in Task Manager during initial batches. If you encounter similar resource constraints, reducing batch size or image size can help manage memory demands. For more tips on optimizing training parameters, check out our [Machine Learning Best Practices and Tips for Model Training](https://docs.ultralytics.com/guides/model-training-tips/). Thanks for sharing your solution with the community!
