### ISSUE TITLE
Which hyperparameter should I use to train the objects365 dataset ?

### ISSUE THREAD

**Issue by buxihuo** [ultralytics/yolov5#8942]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Dear author, I found in https://github.com/ultralytics/yolov5/pull/5194#issuecomment-948073928 that the hyperparameter you used to train the objects365 dataset is hyp.scratch-low.yaml, but I found hyp.objects365.yaml in the hyps folder. I want to ask if I should train the objects365 dataset with the command in https://github.com/ultralytics/yolov5/pull/5194#issuecomment-948073928.

**Comment by glenn-jocher** [comment]
@buxihuo use Objects365 hyps:
```
python train.py --weights yolov5m.pt --data Objects365.yaml --hyp hyp.Objects365.yaml
```
