### ISSUE TITLE
Load custom model offline.

### ISSUE THREAD

**Issue by dfwteinos** [ultralytics/yolov5#8944]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello everyone.

I have this issue: 

I've trained a custom model and I've saved it's weights, with the name: 'best.pt'.
I use this piece of code to load my model: 

`model_name = 'best.pt' `
`model = torch.hub.load('ultralytics/yolov5', 'custom', path=model_name, force_reload=True)`.

The first line of message I'm getting as an output when I'm loading this model is: 
`Downloading: "https://github.com/ultralytics/yolov5/zipball/master" to /home/dimitris/.cache/torch/hub/master.zip`

When I'm online and my internet connection is open, my model works just fine! No problem at all.

But, because I wanna do an **offline** real-time detection, I'm closing my WiFi connection, and suddendly, I have this error: 

*urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>*

Obviously, I can't download 'ultralytics/yolov5' model when I'm offline.

So I'm asking, is there a way that can I load my pre-trained custom weights of my model offline?

Thanks in advance.

**Comment by dfwteinos** [comment]
Problem solved.

For anyone having the same issue as me, here's how I solved it:

I simply changed the `ultralytics/yolov5` parameter and I've replaced it with my local directory where I had the yolov5 directory.

**Comment by glenn-jocher** [comment]
@dfwteinos or just don't request force_reload.
