### ISSUE TITLE
train1 class dataset, cls_loss is 0, how the parameters update?

### ISSUE THREAD

**Issue by ZuyongWu** [ultralytics/yolov5#8947]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

HELP, HELP!!!!!!

![image](https://user-images.githubusercontent.com/43801775/184464080-6d1e0f49-04fe-426b-8def-0c9c297a0b8f.png)
![image](https://user-images.githubusercontent.com/43801775/184464102-a3939668-d420-4831-a8e7-d4f26ef0f91d.png)

When I train 1 class dataset, I found the cls_loss is equal 0, is that means the parameters influencing the cls won't be updated?
If so, when inferencing, how it insure score=conf*cls approximate 1.0?

I don't understand how the parameters update when cls_loss=0?

**Comment by glenn-jocher** [comment]
@ZuyongWu single class output neurons are initialized with very high bias that never gets updated since there is no cls loss for single-class datasets. This ensures they always output 1.0.

**Comment by ZuyongWu** [comment]
> @ZuyongWu single class output neurons are initialized with very high bias that never gets updated since there is no cls loss for single-class datasets. This ensures they always output 1.0.

Thanks a lot. I got it.
