### ISSUE TITLE
Dead Kernel due to matplotlib

### ISSUE THREAD

**Issue by rexayyy** [ultralytics/yolov5#8950]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

![image](https://user-images.githubusercontent.com/97718899/184472995-1d0eab86-d483-4043-9d5e-01fa02501884.png)

I am getting this dead kernel error as i try to run the last cell of my code that has to display the image. I am using windows 10 and i have tried both matplotlib 3.4.0 and version 3.2.2 but i am unable to fix the issue. i have tried updating and reinstalling all the dependencies and everything. 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by rexayyy** [comment]
i have figured it out. It is related to my GPU running out of memory

**Comment by glenn-jocher** [comment]
@rexayyy glad to hear that you've narrowed it down! Running out of GPU memory can indeed cause issues with displaying images. If you have any other questions or need further assistance, feel free to ask. Your contributions are appreciated!
