### ISSUE TITLE
Change evaluation

### ISSUE THREAD

**Issue by bzha5848** [ultralytics/yolov5#8955]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Hi there,

I'm looking for a method that could generate best.pt based on mAP0.5 instead of mAP0.5:0.95, just wondering how to do that?

Thanks so much!!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@bzha5848 you can modify the fitness function to more heavily weight another metric here:
https://github.com/ultralytics/yolov5/blob/d7bc5d77730c625e8b7039e8680714602f5b321f/utils/metrics.py#L15-L19
