### ISSUE TITLE
What is the main difference and advantages of yolov5 with other yolo version v3,v4 

### ISSUE THREAD

**Issue by hammad2008** [ultralytics/yolov5#8960]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello I hope you are doing well.
I wanted to know 
What is the main difference and advantages of yolov5 with other yolo version v3,v4 with respect to network ,speed ,size, parameters.
Also i would like to know diference with other object detection algorithm

**Comment by MartinPedersenpp** [comment]
https://machinelearningknowledge.ai/a-brief-history-of-yolo-object-detection-models/
Is this useful to you?

**Comment by glenn-jocher** [comment]
@MartinPedersenpp thank you for sharing the article! The history of YOLO models is definitely interesting, and it's great to see the progress made by the YOLO community and Ultralytics team. If you have specific questions about YOLOv5, feel free to ask!
