### ISSUE TITLE
RuntimeError: adaptive_max_pool2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True)'

### ISSUE THREAD

**Issue by bzha5848** [ultralytics/yolov5#8961]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Hi there,

I found a bug when I add cbam in head of yolov5m and tried to fine-tuning the model. How can I solve it?

![image](https://user-images.githubusercontent.com/49177682/184539799-a343e5e3-1890-46d1-b024-2fd0155cfe39.png)

Thanks so much!!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@bzha5848 you can set deterministic False here:
https://github.com/ultralytics/yolov5/blob/d7bc5d77730c625e8b7039e8680714602f5b321f/train.py#L107

**Comment by bzha5848** [comment]
Can I ask why this error happens? Is there any method that I can avoid that issue?

**Comment by glenn-jocher** [comment]
@bzha5848 yes you can set deterministic False here:
https://github.com/ultralytics/yolov5/blob/d7bc5d77730c625e8b7039e8680714602f5b321f/train.py#L107
