### ISSUE TITLE
How to save the results of the test to a table file to see the learning status of each category label.

### ISSUE THREAD

**Issue by 050603** [ultralytics/yolov5#8965]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to save the results of the test to a table file to see the learning status of each category label.

### Additional

How to save the results of the test to a table file to see the learning status of each category label.

**Comment by MartinPedersenpp** [comment]
You could run inference using Torch Hub and iteratively add the results to a pandas dataframe. After the testing is done, you can sort the dataframe by the classes detected and calculate the average of each class and save that to a table file like excell or whichever you prefer.

**Comment by glenn-jocher** [comment]
@MartinPedersenpp thanks for reaching out! To save the test results to a table file for per-category analysis, you can use the following workflow:

1. Run inference using Torch Hub and gather the results.
2. Iterate through the results to create a pandas dataframe.
3. After testing, sort the dataframe by detected classes.
4. Calculate the average for each class and save the results to a table file of your choice, such as Excel.

Feel free to refer to the [Ultralytics Docs](https://docs.ultralytics.com/yolov5/) for detailed examples and additional resources. Let me know if you need further assistance!
