### ISSUE TITLE
Lot of background false positives for three classes in the confusion matrix

### ISSUE THREAD

**Issue by Nuwan1654** [ultralytics/yolov5#8967]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi all,

I have two questions.

1. I trained a yolov5 medium model with 3 classes, but when I checked the confusion matrix it shows a large number of false positives for two classes.  even though the class-wise precision is high. any idea on this behavior?

2. even though the class-wise recall and precision are higher the model performance is poor, Is this due to a large number of background false positives?

here is the confusion [matrix](https://drive.google.com/file/d/1XPfxrf3jhG1_a_OoV3j9MhObONG_hR0e/view?usp=sharing)

**Comment by glenn-jocher** [comment]
@Nuwan1654 columns are normalized in this view. You can plot actual numbers by setting normalize=False here:
https://github.com/ultralytics/yolov5/blob/d7bc5d77730c625e8b7039e8680714602f5b321f/utils/metrics.py#L187

**Comment by Nuwan1654** [comment]
@glenn-jocher Thank you for the information, after generating the confusion matrix without normalization. it seems like there are few background false positives. 

with [normalization==True](https://drive.google.com/file/d/1EVrNCLDTSkiAhefXHSn9wslSmpTcMn71/view?usp=sharing)
[without normalization ](https://drive.google.com/file/d/1XPfxrf3jhG1_a_OoV3j9MhObONG_hR0e/view?usp=sharing)

**Comment by glenn-jocher** [comment]
Looks pretty good!
