### ISSUE TITLE
feasibility for the use of yolov5 in the resolution of captchas

### ISSUE THREAD

**Issue by MauroLondon** [ultralytics/yolov5#8969]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I am taking a look at yolov5 and it seems great, however, before I venture to try it, I would like to know if it is possible to use it to solve the captcha of the attached images. It's 33 characters between letters and numbers and I was thinking of an approach where I create 33 classes that correspond to each character and use roboflow to tag the 6 characters found in each captchas. Is that a correct approach? or suggest me some more efficient way to use yolov5 for this case.

![bg4b5v](https://user-images.githubusercontent.com/75399405/184633444-644159a9-5014-49e0-b495-7f704efd56ce.png)
![j4ln1i](https://user-images.githubusercontent.com/75399405/184633448-1dd214a3-acaa-4ab6-a7c3-38e2c51cebe4.png)
![q7uhx7](https://user-images.githubusercontent.com/75399405/184633449-5c220c31-bed9-41cb-a49f-e899d657268a.png)
![b3aoca](https://user-images.githubusercontent.com/75399405/184633452-4877b544-7ece-4384-a8e8-b2eeb8172dba.png)
![44ium1](https://user-images.githubusercontent.com/75399405/184633453-62359fc3-bb81-451a-a5ae-cf30f61cb47f.png)

### Additional

Thank you in advance for any advice you can give me in this regard.

**Comment by glenn-jocher** [comment]
@MauroLondon seems like an interesting approach. With domain-specific tasks there's no one that knows better than the domain expert in this case (you). To find out if an approach works you have to try it out.
