### ISSUE TITLE
About ATSS on YOLOv5

### ISSUE THREAD

**Issue by LitChi-bit** [ultralytics/yolov5#8970]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,
 I have recently been trying to research running ATSS on Yolov5, but there is no progress so far. 
First of all, which part of the code should this be modified in? 
At last,May I ask what the author thinks will be the result, or do you have any suggestions? 
thanks

### Additional

Thank you in advance for any advice you can give me in this regard.

**Comment by glenn-jocher** [comment]
@sakkios you can introduce new modules in models/common.py and then use them in a custom model yaml. 

I don't experience with ATSS, I would ask the ATSS author for his thoughts.

**Comment by sakkios** [comment]
Oh, thank you so much for your answer, I'll continue to look into how to customize the ATSS module as well.

**Comment by glenn-jocher** [comment]
@LitChi-bit you're welcome! Feel free to reach out if you have any more questions while customizing the ATSS module. Good luck with your research!
