### ISSUE TITLE
source distribution of yolov5 on pypi is missing a file: requirements.txt

### ISSUE THREAD

**Issue by gitartpiano** [ultralytics/yolov5#8971]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

source distribution on pypi is missing a file: requirements.txt

### Minimal Reproducible Example

1. Go to: https://pypi.org/project/yolov5/#files
2. Download source distribution: https://files.pythonhosted.org/packages/e9/45/50e668448f1fffb5e5c7ae20d120a28a6ea4ee2908000a3ca4917a56dd5b/yolov5-6.1.8.tar.gz (The problem exists not only in this latest release, but in older releases too).
3. extract
4. `requirements.txt` is not there, but `setup.py` refers to this file and broken by the file missing.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@gitartpiano please raise an issue with the maintainer at https://github.com/fcakyon/yolov5-pip

**Comment by gitartpiano** [comment]
I agree, this issue belong to that pip-er. Thanks.

**Comment by glenn-jocher** [comment]
@gitartpiano you're welcome! If you need any further assistance with YOLOv5, feel free to ask. Good luck with the issue!
