### ISSUE TITLE
How can I find source code for specific releases?

### ISSUE THREAD

**Issue by gitartpiano** [ultralytics/yolov5#8972]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I was able to find tags in
https://github.com/ultralytics/yolov5/tags
such as v6.0 and v6.1, but I cannot find tags for every release to pypi at https://pypi.org/project/yolov5/#history 
such as v6.0.1 .. v6.0.7, v6.1.0 .. v6.1.8 .
How can I checkout from github the source code that belongs to v6.1.7 release for example?

**Comment by glenn-jocher** [comment]
@gitartpiano you can checkout a specific tag like this:
```bash
git clone https://github.com/ultralytics/yolov5
cd yolov5
git checkout tags/v6.1
```

**Comment by glenn-jocher** [comment]
@gitartpiano also FYI the pip package is unofficially maintained by a 3rd party, we don't have control over the versioning there.

**Comment by gitartpiano** [comment]
```
yolov5$ git checkout tags/v6.1.7
error: pathspec 'tags/v6.1.7' did not match any file(s) known to git
```

Who is that 3rd party controlling the pip packaging?

**Comment by glenn-jocher** [comment]
https://github.com/fcakyon/yolov5-pip

**Comment by gitartpiano** [comment]
There it is: https://github.com/fcakyon/yolov5-pip/tags , what I was looking for. Thanks.

**Comment by glenn-jocher** [comment]
@gitartpiano you're welcome! If you have any more questions or need further assistance, feel free to ask. Good luck with your project!
