### ISSUE TITLE
Why does AP decrease as ms/img increases?

### ISSUE THREAD

**Issue by DL-investigator** [ultralytics/yolov5#8975]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I draw a ms/img vs COCO AP (val) figure based on the results of the following command in README. 
`python val.py --task study --data coco.yaml --iou 0.7 --weights yolov5n6.pt yolov5s6.pt yolov5m6.pt yolov5l6.pt yolov5x6.pt`
The figure is as follows. 
<img width="412" alt="fig 2" src="https://user-images.githubusercontent.com/111326242/184780475-97de1e49-5c1f-4b96-b1b3-32d864bb0324.png">
Why does the AP decrease as ms/img increases? Normally the AP should increase as ms/img increases.

**Comment by glenn-jocher** [comment]
@DL-investigator when inference is run at --imgsz larger than used during training mAP will decrease.
