### ISSUE TITLE
resume training

### ISSUE THREAD

**Issue by karl-gardner** [ultralytics/yolov5#8976]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello Glenn @glenn-jocher 

I need to pause training in google colab and then resume training with yolov3 or yolov5 but with keeping early stopping and the same patience level saved with the model. Will this be possible? I see the --resume in train.py 

https://github.com/ultralytics/yolov5/blob/master/train.py#L445

Can i use the following line of code:

!python train.py --img 544 --batch 32 --epochs 1000 --data 'path to .yaml file' --weights 'path to .pt file'  --cache --resume

but is this only for the most recent training with colab instance still running? Will this .pt file actually contain early stopping information from previous epochs?

Thanks,

Karl Gardner

**Comment by glenn-jocher** [comment]
@karl-gardner you should be able to --resume on completely different hardware, but patience is currently reset from the resume epoch.

If you are unable to resume on different hardware/colab instances please submit a bug report with steps to reproduce.
