### ISSUE TITLE
AutoAnchor on Augmented data

### ISSUE THREAD

**Issue by myasser63** [ultralytics/yolov5#8978]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am using AutoAnchor on my own dataset where each image contain one image. Using auto anchor while applying mosaic augmentation through `hyp.yaml` calculates the anchors size based on the orignal dataset not on the dataset after augmentation. Shouldn't the anchor be calculated based on the augmented dataset in this case on after the mosaic is applied to training dataset?

**Comment by glenn-jocher** [comment]
@myasser63 AutoAnchor is computed on training data labels not including augmentation.

**Comment by myasser63** [comment]
@glenn-jocher thanks for your help. Could you tell me which lines of code to change to allow calculation of auto anchor on augmentined dataset?

**Comment by glenn-jocher** [comment]
@myasser63 see https://github.com/ultralytics/yolov5/blob/master/utils/autoanchor.py
