### ISSUE TITLE
EMA has actually done nothing

### ISSUE THREAD

**Issue by cissoidx** [ultralytics/yolov5#8979]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Hello,

EMA is to collect the moving average of the real model with the decay factor ramping from 0 to 0.9999. However, in the code, the ema is neither helping to improve validation nor training. Every batch, the ema.update is called, the ema model updates itself using a decay factor to mixup with the real model, and saves the resulting weights in itself. And every epoch, the ema.update_attr is called, the real model gets copied to the ema model, and the accumulated ema weights are overwritten. So every time before validation and model saving, the ema has actually the real model weights in it. It is as if the ema weights never existed.
I think that this is a bug, can we please just remove ema out of the code or fix it somehow?

Thanks,

**Comment by cissoidx** [comment]
@glenn-jocher Can you please check if this is true? and is there a way to fix it?

**Comment by glenn-jocher** [comment]
@cissoidx EMA works correctly, there is no bug. Model weights are not attributes.

You can disable EMA by setting decay factor to 0.0.
