### ISSUE TITLE
ValueError: source code string cannot contain null bytes

### ISSUE THREAD

**Issue by wanghuaiji** [ultralytics/yolov5#8980]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

After installing the yolov5 development environment, run python detect.py or python train.py error: valueerror: source code string cannot contain null bytes

**Comment by wanghuaiji** [comment]
I found that I did not download yolov5 directly from Ubuntu, but downloaded it from win10, so I reported an error.

**Comment by glenn-jocher** [comment]
@wanghuaiji hey there! It looks like the error you're encountering might be related to how you downloaded YOLOv5. One thing you can try is to ensure that you're using a clean download of YOLOv5 specifically for Ubuntu.

You can also check if there are any null bytes in the source code files as the error suggests.

If the issue persists, feel free to refer to the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/ or ask for further help here. Thank you!
