### ISSUE TITLE
RFB module in yolov5 with ASFF

### ISSUE THREAD

**Issue by bzha5848** [ultralytics/yolov5#8986]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Hi there,

I'm wondering how to add RFB module in yolov5, I found a paper that uses yolov5 with ASFF combined with RFB module, and I wanna implement it in the code to enhance the performance of ASFF. I follow come code in https://github.com/positive666/yolov5_research
to add ASFF into current yolov5, but for RFB module I don't know how it can aded on ASFF. This code does not have any feature for RFB.

Here's the paper that I'm talking about for ASFF+RFB:
https://www.mdpi.com/2072-4292/14/14/3498/htm

Currently ASFF is so bad for my dataset that it even drops a bit compared to using yolov5 directly, I'm forced by my supervisor to make some code for ASFF with yolov5 within 2 weeks but I can't see any hope for improving it. I really doubt the feasibility of using ASFF to enhance the accuracy. Even using CBAM module it still drops some with the origional yolov5. I can't see any hope to improve yolov5 with attention mechanism.

Thanks so much!!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@bzha5848 I experimented a bit with ASFF in the past but wasn't able to generate a good accuracy - complexity tradeoff with it, i.e. it didn't seem like a great addition.
