### ISSUE TITLE
Installing a full requirement set in 2022 for 20/30 series Nvidia cards on linux

### ISSUE THREAD

**Issue by rlewkowicz** [ultralytics/yolov5#8988]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Other

### Bug

Idk if this is a bug, but I wanted to put this here because dependency resolution is always a pia. On linux, even with all the cuda and nvidia stuff installed, I feel like the gpu assets never work or you run into esoteric issues. The light version pins end up putting you all over the place chasing your tail. I don't think a pr would be appropriate, because Ive done this very specific to my set up, but it might be helpful to others. 

Ubuntu 22.04

Create a fresh env using conda (or venv or whatever)

```
conda create -y -n yolo python=3.7
conda activate yolo
```
This will be your requirements.txt: 
```
ipython==7.34.0
ipython-genutils 
matplotlib==3.5.3
matplotlib-inline==0.1.3
numpy==1.21.6
numpydoc 
onnx==1.9.0
onnxruntime==1.12.1
opencv-python==4.6.0.66
pandas==1.3.5
protobuf==3.19.4
psutil==5.9.1
pycocotools 
scikit-learn 
scikit-learn-intelex
scipy==1.7.3
seaborn==0.11.2
tensorboard==2.10.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
thop==0.1.1.post2207130030
torch==1.12.1+cu116
torchaudio==0.12.1+cu116
torchvision==0.13.1+cu116
tqdm==4.64.0
nvidia-tensorrt==8.4.1.5
```
Then you run:
```
pip install -r requirements.txt --extra-index-url https://pypi.ngc.nvidia.com --extra-index-url https://download.pytorch.org/whl/cu116
```
Now mind you, this is for all the latest and greatest cards, and may not work for everyone.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by rlewkowicz** [comment]
I just made this to help others, im closing it now.

**Comment by glenn-jocher** [comment]
@rlewkowicz thank you for your proactive approach! Though your setup might not work for everyone, this kind of guidance can be helpful. If you have any additional questions or suggestions, feel free to share them. We appreciate your input and willingness to help the community!
