### ISSUE TITLE
onnx export break

### ISSUE THREAD

**Issue by lucasjinreal** [ultralytics/yolov5#899]
I can export onnx with previous code, but after pulled updates, when export got this error:

```
Traceback (most recent call last):
  File "models/onnx_export.py", line 63, in <module>
    output_names=['output'])  # output_names=['output']
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/__init__.py", line 208, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 92, in export
    use_external_data_format=use_external_data_format)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 530, in _export
    fixed_batch_size=fixed_batch_size)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 409, in _model_to_graph
    _export_onnx_opset_version)
RuntimeError: Expected object of device type cuda but got device type cpu for argument #3 'index' in call to _th_index_select

```

Any idea?

**Comment by glenn-jocher** [comment]
@jinfagang ONNX export shows success in the latest CI tests. Do you have ONNX 1.7 and PyTorch 1.6?

<img width="1340" alt="Screen Shot 2020-09-01 at 10 23 00 PM" src="https://user-images.githubusercontent.com/26833433/91935084-b774db00-eca1-11ea-8374-74faeddc713a.png">

**Comment by lucasjinreal** [comment]
@glenn-jocher  OK,. I rechecked, I am using torch.device('cuda') for exporting while you using cpu default.

 The error got because there is an node using cpu.

I can export onnx out using cpu, but **problem is** the exported onnx model seems not same as using cuda device.

When I call `python3 -m onnxsim a.onnx a_sim.onnx` I got error:

```
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Concat node. Name:'Concat_672' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/concat.cc:64 onnxruntime::common::Status onnxruntime::ConcatBase::PrepareForCompute(onnxruntime::OpKernelContext*, const std::vector<const onnxruntime::Tensor*>&, onnxruntime::Prepare&) const inputs_n_rank == inputs_0_rank was false. Ranks of input data are different, cannot concatenate them. expected rank: 5 got: 6

```

Have u ever tried this? Well also, I export using 

```
return (torch.cat(z, 1), x)
```

not return x.

**Comment by lucasjinreal** [comment]
The 'cuda' device problem is weird since I can get pytorch output, which means it can be forward on pytorch side in cuda mode:

```
output shape: torch.Size([1, 50400, 18])

```

It got this error right in onnx.export

**Comment by glenn-jocher** [comment]
@jinfagang always export in CPU mode.

**Comment by lucasjinreal** [comment]
@glenn-jocher question is, cpu exported model not right

**Comment by tigerdhl** [comment]
> @glenn-jocher OK,. I rechecked, I am using torch.device('cuda') for exporting while you using cpu default.
> 
> The error got because there is an node using cpu.
> 
> I can export onnx out using cpu, but **problem is** the exported onnx model seems not same as using cuda device.
> 
> When I call `python3 -m onnxsim a.onnx a_sim.onnx` I got error:
> 
> ```
> onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Concat node. Name:'Concat_672' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/concat.cc:64 onnxruntime::common::Status onnxruntime::ConcatBase::PrepareForCompute(onnxruntime::OpKernelContext*, const std::vector<const onnxruntime::Tensor*>&, onnxruntime::Prepare&) const inputs_n_rank == inputs_0_rank was false. Ranks of input data are different, cannot concatenate them. expected rank: 5 got: 6
> ```
> 
> Have u ever tried this? Well also, I export using
> 
> ```
> return (torch.cat(z, 1), x)
> ```
> 
> not return x.

hi， did u solve this problem?
