### ISSUE TITLE
confusion matrix explanation

### ISSUE THREAD

**Issue by Yousef-Alhattab** [ultralytics/yolov5#8991]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

![github](https://user-images.githubusercontent.com/56126016/185040496-3146f2f1-cc53-431a-b62e-9eaf87f9c9fd.png)

we trained 300 epochs with correct labeling and everything is fine!
this dataset has 6 classes and the training was fine on them
then we rename all the classes with a same single name for all and 0 refers to their labeling, for example:
2 0.982969 0.501103 0.026657 0.021774
3 0.375260 0.478689 0.076369 0.081972
1 0.801413 0.492778 0.055476 0.058918
into 
0 0.982969 0.501103 0.026657 0.021774
0 0.375260 0.478689 0.076369 0.081972
0 0.801413 0.492778 0.055476 0.058918

now I am just asking how to get the misdetection and omission.
as you can see that I can not break the matrix down cuz in my case I just have a class?
any help please!

**Comment by glenn-jocher** [comment]
@urbansound8K confusion matrices don't apply to single-class datasets.

**Comment by urbansound8K** [comment]
is there any way to get the misdetection and omission for a single-class dataset, please?

**Comment by glenn-jocher** [comment]
@urbansound8K For single-class datasets, you can use precision, recall, and mAP (mean average precision) metrics for evaluation. As for your validation question, when using the same class names and number of classes in different datasets, you can use the same validation command as the one you mentioned. The YAML file should be identical in this case. Good luck!
