### ISSUE TITLE
Question about yolov5-bifpn

### ISSUE THREAD

**Issue by bzha5848** [ultralytics/yolov5#8992]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi there,

I've got some question about the yolov5-bifpn in hub, I'm wondering how did you actually apply bifpn into Concat in # cat P4? And is that possible for us to apply bifpn with the same method in other concat layer?

Thanks so much!!

**Comment by glenn-jocher** [comment]
@bzha5848 I just followed the BiFPN architecture shown in the EfficientDet paper https://arxiv.org/abs/1911.09070
