### ISSUE TITLE
How can I change dataset while training with PyTorch Hub code?

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#8994]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

you already mentioned that below 2 examples are PyTorch Hub training codes.

model = torch.hub.load('ultralytics/yolov5', 'yolov5s', autoshape=False)  # load pretrained
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', autoshape=False, pretrained=False)  # load scratch

further, how can I change dataset using above codes? must I only use coco128.yaml dataset? I want to use other dataset while using PyTorch Hub codes.

**Comment by MartinPedersenpp** [comment]
> To load a YOLOv5 model for training rather than inference, set autoshape=False. To load a model with randomly initialized weights (to train from scratch) use pretrained=False. **You must provide your own training script in this case. Alternatively see our YOLOv5 [Train Custom Data Tutorial](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data) for model training.**

**Comment by glenn-jocher** [comment]
@MartinPedersenpp to load a YOLOv5 model with a different dataset, you can use the PyTorch Hub code for inference. However, for training with a custom dataset, you should provide your own training script. We recommend checking out our YOLOv5 Train Custom Data Tutorial for detailed instructions on training with a custom dataset. Thank you for your interest!
