### ISSUE TITLE
Do we need a tutorial notebook for classification?

### ISSUE THREAD

**Issue by AyushExel** [ultralytics/yolov5#8999]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

@glenn-jocher 
As we add more tasks, we will need to provide executable examples for each. Adding these tasks in the main detection colab will make it too long. My suggestion is that we add a `tutorial.ipynb` inside `classify/`. This way we can provide a dedicated classification tutorial without messing with the existing files.

What do folks think?

**Comment by glenn-jocher** [comment]
@AyushExel yes that's not a bad idea even though our maintenance requirements will increase. I'll add a TODO.

**Comment by paulguerrie** [comment]
Hi @glenn-jocher!  I've been working with Joseph Nelson to create this over the past couple of days. What is the best way for me to contribute this file to the repo? Do I need contributor permissions to submit a new branch?

**Comment by glenn-jocher** [comment]
@paulguerrie great! Submitting a PR is easy, see https://docs.ultralytics.com/help/contributing/

**Comment by glenn-jocher** [comment]
Removing TODO as completed.
