### ISSUE TITLE
yolov5__Bottlenck  VS   yolov3__Bottlenck??

### ISSUE THREAD

**Issue by MichaelCong** [ultralytics/yolov5#9]
yolov5__Bottlenck  VS   yolov3__Bottlenck??
this isnot differences?

**yolov3__Bottlenck**
[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

**yolov5__Bottlenck**
class Bottleneck(nn.Module):
    def __init__(self, c1, c2, shortcut=True, g=1, e=0.5):  # ch_in, ch_out, shortcut, groups, expansion
        super(Bottleneck, self).__init__()
        c_ = int(c2 * e)  # hidden channels
        self.cv1 = Conv(c1, c_, 1, 1)
        self.cv2 = Conv(c_, c2, 3, 1, g=g)
        self.add = shortcut and c1 == c2

    def forward(self, x):
        return x + self.cv2(self.cv1(x)) if self.add else self.cv2(self.cv1(x))

**Comment by glenn-jocher** [comment]
@MichaelCong models have been updated to feature CSP bottlenecks now.
