### ISSUE TITLE
'DistributedDataParallel' object has no attribute 'model'

### ISSUE THREAD

**Issue by aixin200005** [ultralytics/yolov5#90]
## 🐛 Bug
Hello, I have trained 7 classes of data according to the requirements of Train Custom Data.However, the following errors occurred:
Traceback (most recent call last):
  File "train.py", line 400, in <module>
    train(hyp)
  File "train.py", line 203, in train
    check_best_possible_recall(dataset, anchors=model.model[-1].anchor_grid, thr=hyp['anchor_t'])
  File "/home/aixin/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 539, in __getattr__
    type(self).__name__, name))
AttributeError: 'DistributedDataParallel' object has no attribute 'model'

## Environment
 - OS: [Ubuntu18.04]
 - GPU [NVIDIA TITAN Xp * 4]

**Comment by ChenYingpeng** [comment]
@aixin200005 You can change below code in `train.py`.

`

    if device.type != 'cpu' and torch.cuda.device_count() > 1 and torch.distributed.is_available():
        check_best_possible_recall(dataset, anchors=model.module.model[-1].anchor_grid, thr=hyp['anchor_t'])
    else:
        check_best_possible_recall(dataset, anchors=model.model[-1].anchor_grid, thr=hyp['anchor_t'])
`

**Comment by aixin200005** [comment]
@ChenYingpeng 
Thank you for your suggestion, but I still report an error after revising according to your suggestion
Traceback (most recent call last):
  File "train_aixin.py", line 400, in <module>
    train(hyp)
  File "train_aixin.py", line 195, in train
    check_best_possible_recall(dataset, anchors=model.module.model[-1].anchor_grid, thr=hyp['anchor_t'])
  File "/home/aixin/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 539, in __getattr__
    type(self).__name__, name))
AttributeError: 'Model' object has no attribute 'module'

**Comment by glenn-jocher** [comment]
@ChenYingpeng @aixin200005 yes I see, this is caused by the anchor checking trying to pull anchors from a single-gpu model training. I'll see what I can do to fix this, thank you for the suggestion @ChenYingpeng .

**Comment by glenn-jocher** [comment]
This should be resolved now in the latest commit, please git pull and try again.
