### ISSUE TITLE
Error when running demo

### ISSUE THREAD

**Issue by niuwenju** [ultralytics/yolov5#900]
## 🐛 Bug
when i running the demo by `python detect.py --source test.mp4` , got some errors as follows

_Fusing layers...
Model Summary: 68 layers, 6.98694e+06 parameters, 6.98694e+06 gradients
video 1/1 (1/720) D:\Desktop\hegui\111.mp4: Traceback (most recent call last):
  File "detect.py", line 173, in <module>
    detect()
  File "detect.py", line 74, in detect
    pred = model(img, augment=opt.augment)[0]
  File "C:\Users\niuwj\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Desktop\test\yolov5\models\yolo.py", line 113, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "D:\Desktop\test\yolov5\models\yolo.py", line 133, in forward_once
    x = m(x)  # run
  File "C:\Users\niuwj\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Desktop\test\yolov5\models\yolo.py", line 40, in forward
    x[i] = self.m[i](x[i])  # conv
  File "C:\Users\niuwj\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 594, in __getattr__
    type(self).__name__, name))
AttributeError: 'Detect' object has no attribute 'm'_
 
## Environment

 - OS: Windows10
 - CPU
 - python :3.6.8
 - python packages

Package                   Version
------------------------- ---------
absl-py                   0.10.0
altgraph                  0.17
astor                     0.8.1
astunparse                1.6.3
cachetools                4.1.1
certifi                   2020.6.20
chardet                   3.0.4
click                     7.1.2
cycler                    0.10.0
Cython                    0.29.21
decorator                 4.4.2
defusedxml                0.6.0
Flask                     1.1.2
future                    0.18.2
gast                      0.2.2
google-auth               1.20.1
google-auth-oauthlib      0.4.1
google-pasta              0.2.0
graphviz                  0.8.4
grpcio                    1.31.0
h5py                      2.10.0
idna                      2.6
importlib-metadata        1.7.0
itsdangerous              1.1.0
Jinja2                    2.11.2
Keras-Applications        1.0.8
Keras-Preprocessing       1.1.2
kiwisolver                1.2.0
Markdown                  3.2.2
MarkupSafe                1.1.1
matplotlib                3.3.1
mxnet                     1.3.1
networkx                  2.5
numpy                     1.19.1
oauthlib                  3.1.0
onnx                      1.7.0
opencv-python             4.4.0.42
opt-einsum                3.3.0
pefile                    2019.4.18
Pillow                    7.2.0
pip                       18.1
protobuf                  3.6.1
pyasn1                    0.4.8
pyasn1-modules            0.2.8
pyinstaller               4.0
pyinstaller-hooks-contrib 2020.7
pyparsing                 2.4.7
pypiwin32                 223
python-dateutil           2.8.1
pywin32                   228
pywin32-ctypes            0.2.0
PyYAML                    5.3.1
redis                     3.5.3
requests                  2.24.0
requests-oauthlib         1.3.0
rsa                       4.6
scipy                     1.4.1
setuptools                50.0.0
six                       1.15.0
tensorboard               2.2.0
tensorboard-plugin-wit    1.7.0
tensorflow                1.15.3
tensorflow-estimator      1.15.1
termcolor                 1.1.0
test-generator            0.1.1
torch                     1.5.1+cpu
torchvision               0.6.1+cpu
tqdm                      4.48.2
typing-extensions         3.7.4.3
urllib3                   1.22
Werkzeug                  1.0.1
wheel                     0.35.1
wrapt                     1.12.1
zipp                      3.1.0

**Comment by Shakesbeer333** [comment]
I don't know if it fixes it, but you need Python 3.8 or later

**Comment by NanoCode012** [comment]
Make sure you satisfy the requirements (py > 3.8 and torch >1.6 + requirements.txt). Then please check https://github.com/ultralytics/yolov5/issues/577 .

**Comment by liuchangji** [comment]
I met the same bug,you need to download suitable weight.pt,or you might let program auto download weight.pt for itself then bug gone.
