### ISSUE TITLE
Feed detect.py file with cv2 window.

### ISSUE THREAD

**Issue by dfwteinos** [ultralytics/yolov5#9002]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello everyone!

So, I'm having a problem with the --source in detect.py file.

I want to feed the detect.py file with a cv2 window.

More specifically, I open a cv2 window from tello's camera, and I want to feed the detect.py file with this window.

Thus, I want to do detections at my drone's camera.

How's that possible?

Thanks in advance.

**Comment by glenn-jocher** [comment]
@dfwteinos 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # yolov5n - yolov5x6 official model
#                                            'custom', 'path/to/best.pt')  # custom model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
results.xyxy[0]  # im predictions (tensor)

results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie

results.pandas().xyxy[0].value_counts('name')  # class counts (pandas)
# person    2
# tie       1
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by MartinPedersenpp** [comment]
Is it possible for you to grab the frame of the cv2.window to a variable and then feed it to detect.py?

As @glenn-jocher suggested, using Torch hub is probably easier.
1. Load your model with torch hub
2. Open your cv2 camera feed.
3. Use your for or while loop to iterate the frames from the video feed.
4. Depending on your framerate / processing power feed every nth frame into your yolo model
5. Do whatever you want to do with the output 😀

**Comment by glenn-jocher** [comment]
@MartinPedersenpp yes, it is indeed possible to grab frames from a `cv2` window and feed them to your YOLOv5 model using Torch Hub. 

You can achieve this by following the steps you mentioned:
1. Load your YOLOv5 model using Torch Hub.
2. Open the `cv2` camera feed using a for or while loop.
3. Grab frames from the video feed and pass them to your YOLO model for inference.
4. Do whatever processing you want with the model output.

This approach provides a flexible and efficient way to integrate YOLOv5 detection with your `cv2` camera feed. If you encounter any specific issues while implementing this, feel free to ask for further assistance. Good luck with your project! 😊
