### ISSUE TITLE
model_proc genrate by YOLOv5 or YOLOv3 for dlstreamer openvino

### ISSUE THREAD

**Issue by MohammadsAdrA-AI** [ultralytics/yolov5#9004]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

For using our custom model by openvino after converting to openvino IR, I need a model-proc.json file. I tried to use their docs to create that, but still not able to do the post processing on YOLOv5. 
https://dlstreamer.github.io/dev_guide/how_to_create_model_proc_file.html

### Use case

Open vino dlstreamer

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@MohammadsAdrA-AI not sure, but you can load an OpenVINO model directly with PyTorch Hub and run inference on any streams/sources you want that way:
```python
model = torch.hub.load('ultralytics/yolov5', 'custom', 'yolov5s_openvino_model/')
```

YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # yolov5n - yolov5x6 official model
#                                            'custom', 'path/to/best.pt')  # custom model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
results.xyxy[0]  # im predictions (tensor)

results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie

results.pandas().xyxy[0].value_counts('name')  # class counts (pandas)
# person    2
# tie       1
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by MohammadsAdrA-AI** [comment]
the issue isopenvino dlstreamer needs an xml file which I can convert the pytorch to openvino and have the xml file and a json file called model-proc for post-processing. I don't know how to create this file!

**Comment by glenn-jocher** [comment]
@MohammadsAdrA-AI i understand your concern. The `model-proc.json` file is specific to the DL Streamer and is used for post-processing of the model outputs. However, as YOLOv5 author and maintainer, I do not have specific expertise on the DL Streamer tool.

For creating the `model-proc.json` file for post-processing, I recommend referring to the DL Streamer documentation or contacting their support for guidance specific to their tool.

If you have any further questions regarding YOLOv5 model usage or conversion to OpenVINO, feel free to ask. Good luck with your project!
