### ISSUE TITLE
how to add Background images to training

### ISSUE THREAD

**Issue by HonestyBrave** [ultralytics/yolov5#9008]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hi , glenn-jocher
     i''m  in  your fans, when i read this,:  https://github.com/ultralytics/yolov3/wiki/Tips-for-Best-Training-Results
     i have  a question, is how to add Background images to training, normal i training custom data is add label and image, like this image,:
normal training image:
![one label](https://user-images.githubusercontent.com/16200506/185266183-ab3109c6-4f8a-4740-9446-b7d9e8cb1879.jpg)

but i don't konw how to add background image to training, and if i training one class, but the custom.yaml how to modify?
### like this: **nc: 1 ?**
yaml image:
![customyaml](https://user-images.githubusercontent.com/16200506/185266444-773300c7-40e2-492e-8afe-82af035bfaf2.jpg)

background image:
![background](https://user-images.githubusercontent.com/16200506/185266204-72571e73-f3c5-47e0-bd77-03c2d4df4eac.jpg)

**Comment by glenn-jocher** [comment]
@HonestyBrave background images are super easy, you just put them in your train and val directories, that's it.

Yes for 1 class your yaml looks fine.

**Comment by HonestyBrave** [comment]
thankyou @glenn-jocher for your answer，and i also find answer in your post, thankyou
[[glenn-joche](https://github.com/glenn-jocher)](https://github.com/ultralytics/yolov5/issues/7970)

**Comment by glenn-jocher** [comment]
You're welcome, @HonestyBrave! I'm glad you found the answer you were looking for. If you have any more questions or need further assistance, feel free to ask. Good luck with your training!
