### ISSUE TITLE
Why out of memory after one epoch？When I use [fl_gamma] = 1.5 .

### ISSUE THREAD

**Issue by ZeKunZhang1998** [ultralytics/yolov5#901]
Before submitting a bug report, please be aware that your issue **must be reproducible** with all of the following, otherwise it is non-actionable, and we can not help you:
 - **Current repo**: run `git fetch && git status -uno` to check and `git pull` to update repo
 - **Common dataset**: coco.yaml or coco128.yaml
 - **Common environment**: Colab, Google Cloud, or Docker image. See https://github.com/ultralytics/yolov5#environments
 
If this is a custom dataset/training question you **must include** your `train*.jpg`, `test*.jpg` and `results.png` figures, or we can not help you. You can generate these with `utils.plot_results()`.

## To Reproduce (REQUIRED)

Input:
```
import torch

a = torch.tensor([5])
c = a / 0
```

Output:
```
Traceback (most recent call last):
  File "/Users/glennjocher/opt/anaconda3/envs/env1/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-be04c762b799>", line 5, in <module>
    c = a / 0
RuntimeError: ZeroDivisionError
```

## Environment

 - OS: [e.g. Ubuntu]
 - GPU [e.g. 2080 Ti]

**Comment by glenn-jocher** [comment]
@ZeKunZhang1998 your options are:

1. Use a GPU with more memory
2. Use the default hyps from either hyps.scratch.yaml or hyps.finetune.yaml
3. Set `multi_label=False` in NMS function, which may or may not help.
https://github.com/ultralytics/yolov5/blob/d68179953dff5c371f2d25030f2d1f344643b5fa/utils/general.py#L607

**Comment by glenn-jocher** [comment]
Also, do not use a bug label when you run out of memory.

**Comment by ZeKunZhang1998** [comment]
> Also, do not use a bug label when you run out of memory.

      1/36     13.4G   0.06491  0.006471  0.007181   0.07856        34      1024
               Class      Images     Targets           P           R      mAP@.5
Traceback (most recent call last):
  File "train.py", line 413, in <module>
    train(hyp)
  File "train.py", line 316, in train
    dataloader=testloader)
  File "/kaggle/working/yolov5/test.py", line 114, in test
    output = non_max_suppression(inf_out, conf_thres=conf_thres, iou_thres=iou_thres, merge=merge)
  File "/kaggle/working/yolov5/utils/utils.py", line 606, in non_max_suppression
    i = torchvision.ops.boxes.nms(boxes, scores, iou_thres)
  File "/opt/conda/lib/python3.7/site-packages/torchvision/ops/boxes.py", line 35, in nms
    return torch.ops.torchvision.nms(boxes, scores, iou_threshold)
RuntimeError: CUDA out of memory. Tried to allocate 3.38 GiB (GPU 0; 15.90 GiB total capacity; 1.46 GiB already allocated; 2.63 GiB free; 12.52 GiB reserved in total by PyTorch)



Thanks!I found the log before one epoch is normal.

**Comment by Kongsea** [comment]
It seems there is too many classes in your dataset, so OOM occured when nms in testing.
I also encountered this error when trained on a dataset with more than 200 classes. Could anyone help to fix it? @glenn-jocher @ZeKunZhang1998

**Comment by Kongsea** [comment]
I fixed the error temporarily by changing `conf_thres` of `results, maps, times = test.test(` in `train.py` from default 0.001 to 0.01.
