### ISSUE TITLE
shuffle

### ISSUE THREAD

**Issue by 77serendipity** [ultralytics/yolov5#9010]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

v5中是否默认关闭了shuffle，训练时感觉是没有随机的

**Comment by glenn-jocher** [comment]
@77serendipity shuffle is enabled by default in YOLOv5 on train.py L198:
https://github.com/ultralytics/yolov5/blob/529aafd737053264cf8676b29c37f5d5300460eb/train.py#L183-L198

**Comment by 77serendipity** [comment]
该从哪里开启shuffle呢？感谢


| |
a19142666077
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 9/28/2022 08:33 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [ultralytics/yolov5] shuffle (Issue #9010) |

Closed #9010 as not planned.
