### ISSUE TITLE
Fail to run torchscript after exporting

### ISSUE THREAD

**Issue by Andy824** [ultralytics/yolov5#9011]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I run my yolov5 model through colab. It works successfully. However, after exporting my yolov5m best.pt to torchscript format. The error occurs. The error message is as shown below. Does anyone know the reason? Thank you
![dawdawd](https://user-images.githubusercontent.com/37765645/185287888-54735fc9-7cd4-4779-b5b4-1b0acd529687.png)
!
![螢幕擷取畫面 2022-08-18 112104](https://user-images.githubusercontent.com/37765645/185287936-7f9652df-d7d8-4962-8651-4669a612ee7c.png)

**Comment by Andy824** [comment]
![sucess](https://user-images.githubusercontent.com/37765645/185289278-f264d95c-2e27-4d86-bf36-29eedc851c00.png)

**Comment by Andy824** [comment]
I retrained my model again, but after exporting to torchscript, I got the same error. Does anyone encounter the same problem?

**Comment by glenn-jocher** [comment]
@Andy824 I'm not able to reproduce any errors using the pretrained YOLOv5s model exported to torchscript. Are you sure you are using the latest code?
<img width="1121" alt="Screenshot 2022-08-18 at 11 06 56" src="https://user-images.githubusercontent.com/26833433/185356798-d33b8e32-7d9d-4911-b1cb-84259637fb6f.png">

**Comment by glenn-jocher** [comment]
@Andy824 EDIT: able to reproduce on custom trained model. Will investigate.

<img width="1118" alt="Screenshot 2022-08-18 at 11 10 17" src="https://user-images.githubusercontent.com/26833433/185357550-526f79d8-e553-4a53-a2a0-c0101d677eff.png">

**Comment by glenn-jocher** [comment]
Traced to JSON dumps converting int keys to strings during export, i.e.
https://stackoverflow.com/questions/1450957/pythons-json-module-converts-int-dictionary-keys-to-strings

**Comment by Andy824** [comment]
Thank you for your reply~  ^ ^

**Comment by glenn-jocher** [comment]
@Andy824 good news 😃! Your original issue may now be fixed ✅ in PR #9015. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by Andy824** [comment]
Think you very much.

**Comment by glenn-jocher** [comment]
@Andy824 you're very welcome! I'm here anytime if you have more questions, feature requests or bug reports. Happy to help!
