### ISSUE TITLE
How to use features of the detected output from yolov5?

### ISSUE THREAD

**Issue by noreenanwar** [ultralytics/yolov5#9023]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to use features of the detected object, for instance if I define only one class (car) n yolov5 only detect car in my case so I want to use the detected car result features.

**Comment by glenn-jocher** [comment]
@noreenanwar you can access the full YOLOv5 output before entering NMS, i.e. in detect.py here:
https://github.com/ultralytics/yolov5/blob/c0e7a776cd55e8c01b63714f6f7fea3d53f6bf5b/detect.py#L121-L130

**Comment by noreenanwar** [comment]
Thank you so much for your reply.

**Comment by glenn-jocher** [comment]
@noreenanwar you're welcome! If you have any more questions feel free to ask. The YOLOv5 community and the Ultralytics team are always here to help.
