### ISSUE TITLE
Fail to run torchscript after exporting

### ISSUE THREAD

**Issue by Andy824** [ultralytics/yolov5#9031]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

I run my yolov5 model through colab. It works successfully. However, after exporting my yolov5m best.pt to torchscript format. The error occurs. The error message is as shown below.
![1](https://user-images.githubusercontent.com/37765645/185571132-3058871c-3e44-4950-8b3e-4d0924feea21.png)
![2](https://user-images.githubusercontent.com/37765645/185571143-fb820548-b20c-4569-b469-1c65e4f671e8.png)
![3](https://user-images.githubusercontent.com/37765645/185571149-1b0b8c26-721e-4aa3-a0c1-3135900d7b2e.png)
![4](https://user-images.githubusercontent.com/37765645/185571159-ae676092-f38a-4fe2-add8-321a655cf2c2.png)

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Andy824 this is user error. Torchscript models must run on the same --device they were exported on.
