### ISSUE TITLE
Precision and recall values returns 0 for every epochs

### ISSUE THREAD

**Issue by swaminathanayyappan190799** [ultralytics/yolov5#9032]
hi , with the latest code of yolov5. Whenever I did the training for a custom dataset it returns the precision and recall values as 0

![image](https://user-images.githubusercontent.com/47708135/185583903-5fcdb9f6-caf2-4bd8-8537-baac3ed2c845.png)

**Comment by pourmand1376** [comment]
How is the distribution of your classes? Is your dataset imbalanced?

**Comment by swaminathanayyappan190799** [comment]
@pourmand1376,  there is a slight imbalance in the classes but eventhough the previous releases of yolov5l have handled these issues perfectly with the current dataset. The problem is actually with the latest build

**Comment by swaminathanayyappan190799** [comment]
@pourmand1376,  there is a slight imbalance in the classes but eventhough the previous releases of yolov5l have handled these issues perfectly with the current dataset. The problem is actually with the latest build

**Comment by pourmand1376** [comment]
Hmm. So you can easily switch to the release that you want and use it. 

This is very easy with git. Just use git switch.

**Comment by arun-gautham** [comment]
!git checkout d1dfcab60493e80441cb00be33cfd23aabc26f6b 

did the job

**Comment by swaminathanayyappan190799** [comment]
@pourmand1376 , it worked thanks for your suggestion

**Comment by glenn-jocher** [comment]
@swaminathanayyappan190799 I've reproduced this issue and am working on it now.

**Comment by glenn-jocher** [comment]
First commit producing zero output seems to be this, which is really strange as it doesn't affect Detection training.
https://github.com/ultralytics/yolov5/commit/840b7232dbaff6296e6e2519895c3065e937fdcf

**Comment by glenn-jocher** [comment]
@pourmand1376 @swaminathanayyappan190799 @arun-gautham good news 😃! Your original issue may now be fixed ✅ in PR #9037. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by swaminathanayyappan190799** [comment]
Thank you @glenn-jocher, it was resolved with the latest committed code we have checked it

**Comment by robotwhispering** [comment]
Ohhh, whewww...no cause for alarm, it was just the boss diddling with the production code again. :P 
Sorry for the laugh, @glenn-jocher but this was classic.
