### ISSUE TITLE
Precision Recall Curve has different value than Validition(val.py) results

### ISSUE THREAD

**Issue by BiponD97** [ultralytics/yolov5#9035]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Validation

### Bug

In our Yolov5 experiment to get tha validation results using [val.py] we used 1397 segmented word images and 10415 labels respectively, which runs successfully and shows Precision 0.865 , Recall  0.774   and mAP  0.834. The results stored in the yolov5\runs\val\exp2 where Precision, Recall etc. all Curves are produced. But here on, the Precision Curve showed 0.97 and the Recall Curve showed 0.79 which is different than the actual result, which I mentioned earlier. Only mAP Curve remained same as 0.834.

 Why it's happening and how to fix this? How can I get same curve value as actual result?

image 1: Curve(Precision Value)
image 1: Curve(Recall Value)
image 2: Our Results Value

![P_curve](https://user-images.githubusercontent.com/100799060/185628767-67eb957f-bfd4-4fff-b806-0b3919fda337.png)
![R_curve](https://user-images.githubusercontent.com/100799060/185628780-70255321-b66d-4073-a704-d2b9f7622464.png)
![image](https://user-images.githubusercontent.com/100799060/185628862-ff9125b6-7aaf-480e-a059-9ea7e688ad25.png)

### Environment

-YOLO: YOLOv5 v6.1-376-g48a8531 torch-1.12.1+cpu CPU
-OS: Windows 10
-Python-3.9.12 

### Minimal Reproducible Example

val: data=dataset_for_word_segmentation/word_data.yaml, weights=['word_model/best.pt'], batch_size=32, imgsz=640, conf_thres=0.4, iou_thres=0.8, task=val, device=, workers=8, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=yolov5\runs\val, name=exp, exist_ok=False, half=False, dnn=False

Fusing layers... 
Model summary: 444 layers, 86173414 parameters, 0 gradients, 203.8 GFLOPs
images and labels... 1397 found, 0 missing, 0 empty, 0 corrupt: 100%|##########| 1397/1397 [00:00<?, ?it/s]

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@BiponD97 theres no bug. Curves show values over all confidences and legend displays maximum value.
