### ISSUE TITLE
Hubconf won't process different height and width image size using exported models (detect.py works, pt models work)

### ISSUE THREAD

**Issue by dmccorm2** [ultralytics/yolov5#9039]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection, PyTorch Hub

### Bug

When exporting a model with different height and width for imgsz, for example, 2560 x 1440 (which becomes 1472):

`python export.py --weights yolov5m6.pt --include coreml --device=cpu --imgsz 1440 2560 `

I can run detect.py without issue: `python3 detect.py --imgsz 1472 2560 --weights=./yolov5m6.mlmodel --source=./myvideo.mp4 --classes 0`

However if I load the model from Pytorch Hub:

Using v6.2
`model = torch.hub.load('ultralytics/yolov5:v6.2', 'custom', '~/yolov5/yolov5m6.mlmodel', force_reload=False)`

Then load the video using OpenCV:

```python
cap = cv.VideoCapture('./myvideo.mp4')
while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        print("Can't receive frame (stream end?). Exiting ...")
        break
    scaled_bgr_frame = cv.resize(frame, (2560, 1472), interpolation=cv.INTER_AREA)
    results = model(scaled_bgr_frame)
```

I get the following error, as it defaults to the 640 size:

```shell
RuntimeError: {
    NSLocalizedDescription = "Input image feature image does not match model description";
    NSUnderlyingError = "Error Domain=com.apple.CoreML Code=0 \"Image size 640 x 640 not in allowed set of image sizes\" UserInfo={NSLocalizedDescription=Image size 640 x 640 not in allowed set of image sizes}";
}
```

However, if I use the provided PT model:

```python
model = torch.hub.load('ultralytics/yolov5:v6.2', 'yolov5m6', pretrained=True)
# ...
 results = model(scaled_bgr_frame)
```
Works fine.

If I try specifying size as an array, as you can do in detect.py using the --imgsz flag. I get this trace:

```python
    results = model(scaled_bgr_frame, size=[1472, 2560])
```
```shell
File ~/.cache/torch/hub/ultralytics_yolov5_v6.2/models/common.py:621, in AutoShape.forward(self, imgs, size, augment, profile)
    619 s = im.shape[:2]  # HWC
    620 shape0.append(s)  # image shape
--> 621 g = (size / max(s))  # gain
    622 shape1.append([y * g for y in s])
    623 imgs[i] = im if im.data.contiguous else np.ascontiguousarray(im)  # update
TypeError: unsupported operand type(s) for /: 'list' and 'int'
```

If I specify size as an integer using either `1472` or `2560` in this example, it tries to run the model with a scaled size x size image which fails the exported model check

```shell
RuntimeError: {
    NSLocalizedDescription = "Input image feature image does not match model description";
    NSUnderlyingError = "Error Domain=com.apple.CoreML Code=0 \"Image size 1472 x 1472 not in allowed set of image sizes\" UserInfo={NSLocalizedDescription=Image size 1472 x 1472 not in allowed set of image sizes}";
```

I'm expecting to omit size or provide an array to run a different height and width source on the exported model via pytorch hub successfully as detect.py does without issue.

### Environment

- YOLOv5:  YOLOv5 🚀 v6.2 (current tag)
- Python: 3.9.13
- OS: macOS 12.4 (M1)

### Minimal Reproducible Example

1. Create exported model to use on the zidane jpg sample

`python export.py --weights yolov5m6.pt --include coreml --device=cpu --imgsz 720 1280`

2. Verify detect.py works (768 to match the max stride calculated from the export)
`python3 detect.py --imgsz 768 1280 --weights=./yolov5m6.mlmodel --source=./data/images/zidane.jpg`
`image 1/1 ~/yolov5/data/images/zidane.jpg: 768x1280 2 persons, 1 tie, 73.3ms`

3. In python shell
```python
import torch
import cv2
im = cv2.imread('./data/images/zidane.jpg')
model = torch.hub.load('ultralytics/yolov5:v6.2', 'custom', './yolov5m6.mlmodel')
results = model(im) # will fail here
results.print()
```
4. 
Expect to see
```shell
RuntimeError: {
    NSLocalizedDescription = "Input image feature image does not match model description";
    NSUnderlyingError = "Error Domain=com.apple.CoreML Code=0 \"Image size 640 x 640 not in allowed set of image sizes\" UserInfo={NSLocalizedDescription=Image size 640 x 640 not in allowed set of image sizes}";
}
```
5. Can then try
`results = model(im, size=[768, 1280])`
Error:
```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/path/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "~/.cache/torch/hub/ultralytics_yolov5_v6.2/models/common.py", line 621, in forward
    g = (size / max(s))  # gain
TypeError: unsupported operand type(s) for /: 'list' and 'int'
```

6. Can also try `results = model(im, size=768)`

```shell
RuntimeError: {
    NSLocalizedDescription = "Input image feature image does not match model description";
    NSUnderlyingError = "Error Domain=com.apple.CoreML Code=0 \"Image size 768 x 768 not in allowed set of image sizes\" UserInfo={NSLocalizedDescription=Image size 768 x 768 not in allowed set of image sizes}";
}
```
7. Remove size and revert to the provided model
`model = torch.hub.load('ultralytics/yolov5:v6.2', 'yolov5m6')`

8. `results = model(im)` now works  with results.print()

```shell
image 1/1: 720x1280 2 persons, 1 tie
Speed: 6.1ms pre-process, 353.2ms inference, 5.7ms NMS per image at shape (1, 3, 384, 640)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@dmccorm2 CoreML models are only capable of inference at a fixed size, PyTorch models are capable of dynamic input sizes. 

We don't have CI in place for CoreML export and PyTorch Hub inference at various sizes so this feature may not exist. 

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by glenn-jocher** [comment]
@dmccorm2 the preprocess step in the AutoShape forward method would be the place to debug and modify for your use case:
https://github.com/ultralytics/yolov5/blob/f258cf8b37aeb3062230d43e1e9a4bf3b9874588/models/common.py#L609-L632

**Comment by glenn-jocher** [comment]
@dmccorm2 test #9072 to see if this works for your use case:

```python
model = torch.hub.load('ultralytics/yolov5:update/autoshape_hw_size', 'yolov5m6', pretrained=True)

results = model(im, size=(h,w))
```

**Comment by dmccorm2** [comment]
@glenn-jocher  This worked great for me - am able to leverage Autoshape with a specified different w,h tuple and works on CoreML export (as long as it matches the same model w,h obviously)

**Comment by glenn-jocher** [comment]
@dmccorm2 great, PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐
