### ISSUE TITLE
how to disable saving weights in fp16 default

### ISSUE THREAD

**Issue by lucasjinreal** [ultralytics/yolov5#904]
AFAIK, pytorch actually does all calculation in fp32 even save in fp16 mode. 

How to disable it ? Since I found fp16 weights this data type not supported in onnx export

**Comment by glenn-jocher** [comment]
.float() any model or tensor to convert it to FP32.

**Comment by LuTaoChen** [comment]
Searching "x['model'].half()  # to FP16" in general.py
