### ISSUE TITLE
Confusion matrix missing background false positives

### ISSUE THREAD

**Issue by wico-silva** [ultralytics/yolov5#9040]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

I have noticed that the `ConfusionMatrix` under certain circumstances doesn't take into account all background false positives. I built two small unit tests to demonstrate the issue:

```python
import unittest
import torch
import numpy as np


from utils.metrics import ConfusionMatrix, box_iou


class TestConfusionMatrix(unittest.TestCase):
    def test_zero_targets_one_prediction(self):
        # One prediction - confidence above threshold
        # [x1, y1, x2, y2, conf, class]
        prediction = torch.tensor([[0, 0, 100, 100, 0.9, 0]], dtype=torch.float)

        # Zero targets
        # [class, x1, y1, x2, y2]
        target = torch.empty((0, 5), dtype=torch.float32)

        conf_matrix = ConfusionMatrix(2)
        conf_matrix.process_batch(prediction, target)

        expect = np.zeros((3, 3))
        expect[0, -1] = 1
        np.testing.assert_equal(conf_matrix.matrix, expect)

    def test_one_target_one_prediction__below_iou(self):
        # One prediction - confidence above threshold
        # [x1, y1, x2, y2, conf, class]
        prediction = torch.tensor([[0, 0, 100, 100, 0.9, 0]], dtype=torch.float)

        # One target - shifted horizontally so that IoU is below the threshold
        # [class, x1, y1, x2, y2]
        target = torch.tensor([[0, 75, 0, 100, 100]], dtype=torch.float)

        # Make sure IoU is below threshold
        iou_thres = 0.45
        assert box_iou(prediction[:, :4], target[:, 1:]) < iou_thres

        conf_matrix = ConfusionMatrix(2, iou_thres=iou_thres)
        conf_matrix.process_batch(prediction, target)

        expect = np.zeros((3, 3))
        expect[0, -1] = 1
        expect[-1, 0] = 1
        np.testing.assert_equal(conf_matrix.matrix, expect)


if __name__ == "__main__":
    unittest.main()
```

Here's the output of the first test:
```
AssertionError: 
Arrays are not equal

Mismatched elements: 1 / 9 (11.1%)
Max absolute difference: 1.
Max relative difference: 1.
 x: array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])
 y: array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])
```
and the generated plot:
![test_zero_targets_one_prediction](https://user-images.githubusercontent.com/91887911/185655426-b20126fd-2a11-4686-9850-7a6e684c52d9.png)

The output of the second test:
```
AssertionError: 
Arrays are not equal

Mismatched elements: 1 / 9 (11.1%)
Max absolute difference: 1.
Max relative difference: 1.
 x: array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.]])
 y: array([[0., 0., 1.],
       [0., 0., 0.],
       [1., 0., 0.]])
```
and the generated plot:
![test_one_target_one_prediction__below_iou](https://user-images.githubusercontent.com/91887911/185655614-b1eb6442-d8df-42d9-992d-87c5b0de6481.png)

In  both tests the confusion matrix didn't account for the prediction at indices [0, -1] (class 0 background FP).

### Environment

- YOLOv5 master

### Additional

Another issue I found while writing the tests is that the class attribute [`matrix`](https://github.com/ultralytics/yolov5/blob/4a8ab3bc42d32f3e2e9c026b87dc29fba6143064/utils/metrics.py#L127) shadows the method [`matrix()`](https://github.com/ultralytics/yolov5/blob/4a8ab3bc42d32f3e2e9c026b87dc29fba6143064/utils/metrics.py#L178).
That is, `conf_matrix.matrix` works but `conf_matrix.matrix()` will result in: `TypeError: 'numpy.ndarray' object is not callable`

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@wico-silva hi, thank you for your feature suggestion on how to improve YOLOv5 🚀! I don't have time independently verify this, but if you think there is a flaw then please submit a PR with a fix, thank you!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
