### ISSUE TITLE
--save-crop

### ISSUE THREAD

**Issue by smamraee** [ultralytics/yolov5#9042]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I am using Yolo 5 on Google Colab. I want to save cropped images using --save-crop in detect.py as below. 
!python detect.py --weights yolov5s.pt --img 640  --conf 0.30 --classes 0 --source frames --save-txt --save-conf --save-crop

Cropped images are saved in the "crops" folder, but they are not named in order, and it is impossible to distinguish which frame each cropped image belongs to. Is there a way to name the cropped images according to their original frames? My dataset is a 2-person dance. There are one girl and one boy in each frame.

**Comment by glenn-jocher** [comment]
@smamraee hi there! The `--save-crop` option in `detect.py` currently saves cropped images with unique IDs, making it difficult to correlate them with original frames. While specifying a custom naming convention isn't supported natively, an additional script could be used to map the cropped images back to their original frames. I'd recommend leveraging the Ultralytics Docs for this or ask the community for specific advice. Good luck with your dance dataset!
