### ISSUE TITLE
Frame Labelling

### ISSUE THREAD

**Issue by semihahishali** [ultralytics/yolov5#9043]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,
I'm working on object detection on custom objects. I have to detect frames but not the pictures in it. There are different types of frames and I have to detect the type of each frame by machine learning, object detection, no matter what the picture is in it. But I have to draw a rectangular for all types of objects for labelling before training. Is there a way to draw these types of objects other then rectangular to train with Yolo5/Pytorch better, like free form drawing around object?

![image](https://user-images.githubusercontent.com/110197447/185677519-ccd49df9-da31-4e80-85da-80620103528f.png)

**Comment by glenn-jocher** [comment]
@semihahishali you might want to simply train a classifier, no object labelling needed. See https://github.com/ultralytics/yolov5/releases/tag/v6.2
