### ISSUE TITLE
Follow up Question RuntimeError: adaptive_max_pool2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True)

### ISSUE THREAD

**Issue by bzha5848** [ultralytics/yolov5#9047]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi there,

This is a follow up question of 
https://github.com/ultralytics/yolov5/issues/8961

Just wondering why this happens and if there's any method to avoid it?

Thanks so much!!

**Comment by glenn-jocher** [comment]
@bzha5848 you can set deterministic False here to avoid this:
https://github.com/ultralytics/yolov5/blob/d7bc5d77730c625e8b7039e8680714602f5b321f/train.py#L107

**Comment by bzha5848** [comment]
Yeah I did, but can I ask why it happens? And is there any method to avoid this issue while modify the config file for model?

**Comment by glenn-jocher** [comment]
See https://pytorch.org/docs/stable/generated/torch.use_deterministic_algorithms.html

**Comment by bzha5848** [comment]
For this issue, is that related to the number of classes I used to train? Coz when I use the dataset with few classes on the same modified model config it ddoesn't happen, but on the dataset over 20 classes it does

**Comment by glenn-jocher** [comment]
@bzha5848 the issue might be related to the number of classes you are training on. The larger dataset with over 20 classes may be triggering the problem. It's a known issue with PyTorch that can occur when using deterministic algorithms. As for methods to avoid it, you may want to consider using a smaller batch size or adjusting other training parameters.
