### ISSUE TITLE
About augmentation: is the number of training images after augmentation equal to the training set size?

### ISSUE THREAD

**Issue by tazu786** [ultralytics/yolov5#905]
## ❔Question
Hi to the whole ultralytics team and thank you for your great repos!
I went through the dataset.py file and if my understanding is correct, all the data augmentation techniques are only implemented on the run without increasing the size of the training set. 

If this is correct, how do you suggest to increase the physical number of training samples, such that the model is trained with both un-augmented and augmented version of the dataset (with augmented version including N*size(training_set) images, and N = number of augmentation techniques applied.) ?

Thank you

**Comment by glenn-jocher** [comment]
@tazu786 increase epochs.

You can modify hyp augmentation probabilities in the hyp yamls.

**Comment by tazu786** [comment]
Thank you. But if I increase augmentation probabilities to 1 and double the epochs for instance, I will apply them both times excluding the original version of the dataset. Am I correct?

**Comment by glenn-jocher** [comment]
@tazu786 you can modify augmentation hyps as you see fit for your situation in hyp yamls.

**Comment by zhang295498** [comment]
> Thank you. But if I increase augmentation probabilities to 1 and double the epochs for instance, I will apply them both times excluding the original version of the dataset. Am I correct?

I have the same question，Did you solve it?
