### ISSUE TITLE
Trained a model in Colab until complete for 500 epoch but Colab disconnected right after trainingall files gone

### ISSUE THREAD

**Issue by robotaiguy** [ultralytics/yolov5#9069]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

So I trained a model to completion of 500 epochs on Colab, and ju\st before I could get the model copied off to my Google Drive, I got disonnected. Yes, this still happens on the Pro Plus plan for $50/month, so save your money. So the Colab side file system is completely gone. But I had wandb integrated, and I can see the stats on their  site. But I can't figure otu how to get my model. Anbody know how I can do that?

Or it is just....
![joker-its-gone](https://user-images.githubusercontent.com/60989737/185794536-aec68a13-3fd2-46fd-b452-ecab62ba934e.gif)

**Comment by AyushExel** [comment]
@robotwhispering if the training is finished successfully, you should see the model logged as artifact in your wandb dashboard.
<img width="530" alt="Screenshot 2022-08-21 at 7 29 15 PM" src="https://user-images.githubusercontent.com/15766192/185794572-b550d73e-69d1-48b5-aade-1207692a1988.png">

**Comment by robotwhispering** [comment]
Thanks for responding...I figured out that the problem was that I'm just dfumb. :P That wasn't a ..zip file I downloaded from waand, that WAS teh model. Netron sees it fine. The "zip" icon on the package threw me off. :/

![Screenshot from 2022-08-21 09-08-37](https://user-images.githubusercontent.com/60989737/185795147-72f22aa9-e85a-4e20-8edf-30e7ed966a33.png)

**Comment by AyushExel** [comment]
@robotwhispering yeah you need to rename the file to *.pt after downloading form wandb
