### ISSUE TITLE
V 3.0 tag pointing to wrong commit

### ISSUE THREAD

**Issue by lorenzomammana** [ultralytics/yolov5#907]
## 🐛 Bug
The 3.0 release is pointing to commit 1ddf692bf89ac47d5e2dc8333cd0f4f145bb7f61, which is one commit before the actual v3.0 release, so if someone clones the repo from the v3.0 version is actually using the older version.

## To Reproduce (REQUIRED)
Click on the tag commit.

## Expected behavior
It should point towards commit 916d4aad9a154587dc5914f9b04be575a0990529

**Comment by glenn-jocher** [comment]
@lorenzomammana thanks, it looks like you are right. Unfortunately I'm unable to change the commit associated with the release after publishing it, and it seems like I can only issue a new release associated with recent commits (i.e. within the last 10 commits). I'm not sure there's anything I can do about this now.

**Comment by lorenzomammana** [comment]
Something like this?
https://github.community/t/create-releases-for-old-commits/872

**Comment by glenn-jocher** [comment]
I tried it but it was too complicated, will take better care going forward for next release.
