### ISSUE TITLE
Torchscript.ptl problem isTuple()INTERNAL ASSERT FAILED

### ISSUE THREAD

**Issue by Andy824** [ultralytics/yolov5#9077]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am trying to deploy my model to Android, I export it to torchscript and then torchscript.ptl. However, I cannot run it on Android, here is the error. Does anyone know the reason?
![3](https://user-images.githubusercontent.com/37765645/185826403-e0c29a1c-93eb-4094-b128-a0dafe02b993.jpg)
![1](https://user-images.githubusercontent.com/37765645/185826432-ae33d1d5-ba2c-4512-a1c4-974817ce1db0.png)
![2](https://user-images.githubusercontent.com/37765645/185826438-7c525feb-4d53-4bc3-a6f6-aa58fbd3780f.png)

**Comment by Andy824** [comment]
![4](https://user-images.githubusercontent.com/37765645/185826634-cb2da8b0-2b82-4c16-9319-0af22191d027.png)
![螢幕擷取畫面 2022-08-22 102814](https://user-images.githubusercontent.com/37765645/185826752-69a01362-71eb-4ba6-89e0-668edd8bf617.png)
![螢幕擷取畫面 2022-08-22 102840](https://user-images.githubusercontent.com/37765645/185826801-33575ca8-f28f-47f4-bb80-d526266392eb.png)

**Comment by glenn-jocher** [comment]
@Andy824 it looks like there might be an issue with the conversion to TorchScript, resulting in an assertion failure. Would you mind sharing the code snippet where you export the model to TorchScript and the version of YOLOv5 you are using? This information will help in diagnosing the issue. Thank you!
