### ISSUE TITLE
A question about torch.hub.load() and imsize

### ISSUE THREAD

**Issue by flash-barry** [ultralytics/yolov5#9078]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, everyone. I trained yolov5x model with 640*360 images. Now, I use this well-trained model `my_model = torch.hub.load ('ultralytics/yolov5', 
    'custom', 
    path='best.pt', device=7)` and `result = my_model(image, size=640)` to detect objects and achieve satisfactory results. But I have some high resolution (2160*1440) images and set the 'my_model(image, size=640)'. It didn't work. How should I set the imgsize when using ` torch.hub.load `

**Comment by glenn-jocher** [comment]
@flash-barry you can pass any image you want when running inference, but I'd recommend you use a similar size to what you trained the model on. So if you trained at --img 640, then I'd run `model(im, size=640)`

**Comment by flash-barry** [comment]
> @flash-barry you can pass any image you want when running inference, but I'd recommend you use a similar size to what you trained the model on. So if you trained at --img 640, then I'd run `model(im, size=640)`

Thank you for the reply!
