### ISSUE TITLE
What is background image?

### ISSUE THREAD

**Issue by 284nnuS** [ultralytics/yolov5#9080]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I'm just a newbie so I have a question : "What is background image?" in https://github.com/ultralytics/yolov5/wiki/Tips-for-Best-Training-Results . 
I don't understand clearly if I have many class data to train. For example :  I have to train object detection with dog, cat and bird. So the background image here is some image that haven't cat , dog and just have bird? Is that a background images mean right here? Thanks for reading and pls help me!

**Comment by MartinPedersenpp** [comment]
A background image is an unlabeled image that does not contain any of your classes to be trained

**Comment by 284nnuS** [comment]
> A background image is an unlabeled image that does not contain any of your classes to be trained

Thanks, it's very clear with me 👍

**Comment by MartinPedersenpp** [comment]
@284nnuS That is great to hear! 
Good luck training your model and don't forget to mark the issue as solved if your question has been answered 😉
