### ISSUE TITLE
GPU low utilization and fluctuations during training 1 million custom data using yolov5m

### ISSUE THREAD

**Issue by mfaizan-ai** [ultralytics/yolov5#9086]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi Glenn, Thanks for amazing work. I am using RTX3090Ti GPU, and I am training on 1M images. My system GPU utilization is fluctuating and it's not very fast as it should be. We trained with a small dataset with 8k images, the GPU utilization was stable, however, it is not stable when trained with 1M images. It is constantly fluctuating between 0 - 98% and slow. We varied the batch size and number of workers. My system has the following specs:
GPU: RTX3090TI
CUDA: 11.6
pytorch: 1.12.1 stable
YOLOv5: yolov5m
nproc: 16

could you please suggest some promising steps to try to address the issue? We are training on a big dataset.

**Comment by Abu-Affan** [comment]
i have same issue like this

**Comment by AyushExel** [comment]
@faizan1234567 @Abu-Affan If I had to guess, I would test data loading process for bottleneck. This happens usually when large datasets are being transferred back and forth from HDD->CPU/GPU, for example imagenet.
If you have enough disc space, you can try using `--cache disc` to see if it improves performance. Let us know if you make any progress

**Comment by faizan1234567** [comment]
We tried that, but we don't have enough disc space. We ran out of space. Is there any other possible solution like making some changes in code like in preprocessing? The second thing is Nvidia-smi and nvcc --version give different versions of cuda

**Comment by faizan1234567** [comment]
Nvidia-smi gives cuda 11.6 and nvcc --version gives cuda 10.1. Why is that? Is not it supposed to give the same version?

**Comment by faizan1234567** [comment]
our dataset is in SSD, it's not in HDD

**Comment by glenn-jocher** [comment]
@faizan1234567 👋 Hello! Thanks for asking about **training speed issues**. YOLOv5 🚀 can be trained on CPU (slowest), [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) (fastest). If you would like to increase your training speed some options are:

- Increase `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s
- Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) DDP at larger `--batch-size`
- Train on cached data: `python train.py --cache` (RAM caching) or `--cache disk` (disk caching)
- Train on faster GPUs, i.e.: P100 -> V100 -> A100
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

Good luck 🍀 and let us know if you have any other questions!

**Comment by glenn-jocher** [comment]
Sounds good, @faizan1234567! 👍 Looking forward to hearing back from you. If you have any other questions or run into any issues, feel free to ask. Good luck with your training, and I hope the cached dataset improves the performance. Happy training!
