### ISSUE TITLE
About the dataset issue

### ISSUE THREAD

**Issue by OUX-Eulogize** [ultralytics/yolov5#9088]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, thanks for amazing work.  I want to know which dataset are the pre-trained weights (such as yolo5s.pt or yolo5l.pt) based on.

**Comment by AyushExel** [comment]
@OUX-Eulogize pre-trained weights are trained on coco dataset for 300 epochs
