### ISSUE TITLE
How to load a specific version in torch.hub.load

### ISSUE THREAD

**Issue by WendellAtHome** [ultralytics/yolov5#9089]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I am trying to specify a release version when loading yolov5 using "torch.hub.load". However, I cannot find a solution, it's also not listed in the tutorial either.

**Comment by glenn-jocher** [comment]
```python
model = torch.hub.load('ultralytics/yolov5:v6.2', 'yolov5s')  # or yolov5n - yolov5x6, custom
```

**Comment by RealNewNoob** [comment]
> ```python
> model = torch.hub.load('ultralytics/yolov5:v6.2', 'yolov5s')  # or yolov5n - yolov5x6, custom
> ```
Thanks! This fixes my problem!

**Comment by glenn-jocher** [comment]
@RealNewNoob you're welcome! I'm glad to hear that it solved your issue. If you have any more questions or need further assistance, feel free to ask! Keep up the great work! 🚀
