### ISSUE TITLE
Customise seeds

### ISSUE THREAD

**Issue by bzha5848** [ultralytics/yolov5#9094]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Hi there,

Just wondering is there a way to initialise seeds for training?

Thanks so much!!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by TahaSener** [comment]
#1222 please check out the first comment by @glenn-jocher and the second one.

**Comment by glenn-jocher** [comment]
@bzha5848 see argparser for training arguments

```python
python train.py --seed 0
```

https://github.com/ultralytics/yolov5/blob/eab35f66f9104992a448fbd726c6c2dfdfdf240f/train.py#L466
