### ISSUE TITLE
The image I capture from my USB camera is distorted.

### ISSUE THREAD

**Issue by Heartful-echo** [ultralytics/yolov5#9098]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Hi

I was using a USB camera (webcam c270) with YOLOv5.
I prepared a USB camera (ELP-USBFHD05MT-DL36-J) to test YOLOv5 outdoors.
I ran YOLOv5, and with ELP-USBFHD05MT-DL36-J, the YOLOv5 camera image is distorted.
Can't this be solved with YOLOv5 settings? Please someone tell me!

By the way, there is no distortion in the camera image with the cheese app.
I think there is a problem when taking pictures with YOLOv5.

### Environment

OS:Ubuntu 18.04
Python:3.7.3

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@kazuya-uchida YOLOv5 uses cv2 for webcam image loading. See utils.dataloaders.StreamLoader for details.
