### ISSUE TITLE
question about export tflite

### ISSUE THREAD

**Issue by June1124** [ultralytics/yolov5#9099]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

PyTorch: starting from runs\train-cls\exp\weights\best.pt with output shape (1, 2) (2.4 MB)

TensorFlow SavedModel: starting export with tensorflow 2.8.0...

TensorFlow SavedModel: export failure: 'ClassificationModel' object has no attribute 'yaml'

TensorFlow Lite: starting export with tensorflow 2.8.0...

TensorFlow Lite: export failure: 'NoneType' object has no attribute 'call'
 ===================================================================

The above is the error reported after I trained the classification model and exported the tflite format, before I trained the detection model I could successfully export the onnx format, is there any solution?

**Comment by glenn-jocher** [comment]
@June1124 thanks for the bug report! Unfortunately ClassificationModel types are not exportable to TF formats currently. We are working on adding this functionality in the future though.

**Comment by glenn-jocher** [comment]
@June1124 I've added an assert to inform users that ClassificationModel TF export is not yet supported in https://github.com/ultralytics/yolov5/pull/9226. We will add this feature when we can in the future.
