### ISSUE TITLE
suggestions for integration?

### ISSUE THREAD

**Issue by jinzishuai** [ultralytics/yolov5#910]
## ❔Question

I would like to start using yolov5 in my own project. So far, I haven't found a straight forward way and I had to copy and commit the yolov5 source into my own and start hacking it. I want to know if there is some best practices on how to use yolov5 in other projects.

I wonder if the following is possible
* create python package using setuptools
* publish releases in pypi.org so that people could simply do `pip install yolov5` to get this module.

## Additional context

I am also looking for an API that might take an OpenCV image as input and output a list of detected objects. Right now, all I see from the detect.py is the detect() function that takes images/video files or webcam streams. In my application (I would imagine many others as well), we want to handle the video stream ourselves and do other operations and also don't want to save the images to temporary files. It would be super cool if there is an easy to use function to just do that. I am sure if I take the detect() function apart, I could isolate the a few steps output (which is kind of what I have done).  But if this API is offered as part of the python package, then all we might have to do in the future might be 
* `import yolov5`
* call `yolov5.detect(input_image)`

Finally, I truly appreciate this open source effort and would love to contribute if there is some guidance.

**Comment by NanoCode012** [comment]
Hi, I've definitely seen an attempt PR to do so here https://github.com/ultralytics/yolov5/pull/465#issue-454210365 and here https://github.com/ultralytics/yolov5/pull/668 .

> also don't want to save the images to temporary files

I think you just changed the line below, it should not save images anymore. You can pass "--save-txt" to get the predictions.
https://github.com/ultralytics/yolov5/blob/44cdcc7e0bda374b203222098f15dc592f0fe2e2/detect.py#L54

> In my application (I would imagine many others as well), we want to handle the video stream ourselves and do other operations

I think you could write your custom Dataloader and simply replace here.
https://github.com/ultralytics/yolov5/blob/44cdcc7e0bda374b203222098f15dc592f0fe2e2/detect.py#L47-L55

>  and output a list of detected objects

https://github.com/ultralytics/yolov5/blob/44cdcc7e0bda374b203222098f15dc592f0fe2e2/detect.py#L99-L109

**Comment by glenn-jocher** [comment]
@jinzishuai thanks for the suggestions! There is a PR for a pip package as mentioned. We paused work on that at the time but I think the repo is nearing a more mature state that we might look at that again soon, for the convenience perspective as you mentioned. Perhaps you could review the PR and submit any comments you have.

The closest functionality now is torch hub, which only requires torch dependency: https://docs.ultralytics.com/yolov5

```python
import torch

yolov5s = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)
detections = yolov5s(image)
```

**Comment by jinzishuai** [comment]
@glenn-jocher  I'll have to look more into the torch  hub idea. In the same time, I am more than happy to review and test the PR for the pip package. Do you know where it is? I didn't find it.

Thanks a lot.

**Comment by glenn-jocher** [comment]
@jinzishuai pip package PR is here: https://github.com/ultralytics/yolov5/pull/465

Needs to be dusted off and updated.
