### ISSUE TITLE
mosaic result different

### ISSUE THREAD

**Issue by wch243294382** [ultralytics/yolov5#9103]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

My result can't be reproduced. I feel that the result of each mosaic painting is different. How can I fix it？

**Comment by glenn-jocher** [comment]
@wch243294382 YOLOv5 trainings are fully reproducible if you are using torch>=1.12.0.
