### ISSUE TITLE
Issue when training using MPS: unsupported datatype for constant

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#9107]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

I performed an example command that comes with train.py(plus --device mps), but after a few seconds, I got this:
<img width="708" alt="image" src="https://user-images.githubusercontent.com/32949795/186197200-3e627db1-c003-484e-9723-95e6d2b3d709.png">
I searched on the web, but only this place gave me a similar problem:
https://discuss.pytorch.org/t/code-didnt-speed-up-as-expected-when-using-mps/152016

### Environment

- YOLOv5 V6.2 commit 48e56d3c9bede445d49e8f2af458d70955032e91
- MacBook Pro 2021 with Apple M1 Max, 64GB RAM
- macOS Monterey 12.5.1
- PyTorch 1.12.1
- Python 3.10.5 ARM native

### Minimal Reproducible Example

Just open your terminal in yolov5 folder and execute:

python3 train.py --data coco128.yaml --weights '' --cfg yolov5s.yaml --img 640 --device mps

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Leo-Maxwell** [comment]
When I was using the latest nightly version of PyTorch, the issue is gone.

**Comment by glenn-jocher** [comment]
@ghost glad to hear the latest PyTorch nightly version resolved the issue for you! 💫 The YOLOv5 team always recommends using the latest compatible dependencies for optimal performance and support. If you run into further questions or concerns, do not hesitate to reach out. Good luck with your training! 🚀
