### ISSUE TITLE
Cannot run traning on classifcation on my database 

### ISSUE THREAD

**Issue by VYRION-Ai** [ultralytics/yolov5#9108]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

i try to run traning on classifcation on my dataset i got this error
my datset dir is correct

`%cd /content/yolov5/classify/
!python train.py --model resnet50  --data '/content/classify' --epochs 20 --img 128 --batch-size 256 --cache`

`/content/yolov5/classify
classify/train: model=resnet50, data=/content/yolov5/classify/classify, epochs=20, batch_size=256, imgsz=128, nosave=False, cache=ram, device=, workers=8, project=../runs/train-cls, name=exp, exist_ok=False, pretrained=True, optimizer=Adam, lr0=0.001, decay=5e-05, label_smoothing=0.1, cutoff=None, dropout=None, verbose=False, seed=0, local_rank=-1
github: up to date with https://github.com/ultralytics/yolov5 ✅
YOLOv5 🚀 v6.2-49-g48e56d3 Python-3.7.13 torch-1.12.1+cu113 CPU

TensorBoard: Start with 'tensorboard --logdir ../runs/train-cls', view at http://localhost:6006/
Traceback (most recent call last):
  File "train.py", line 331, in <module>
    main(opt)
  File "train.py", line 317, in main
    train(opt, device)
  File "train.py", line 95, in train
    workers=nw)
  File "/content/yolov5/utils/dataloaders.py", line 1141, in create_classification_dataloader
    dataset = ClassificationDataset(root=path, imgsz=imgsz, augment=augment, cache=cache)
  File "/content/yolov5/utils/dataloaders.py", line 1107, in __init__
    super().__init__(root=root)
  File "/usr/local/lib/python3.7/dist-packages/torchvision/datasets/folder.py", line 316, in __init__
    is_valid_file=is_valid_file,
  File "/usr/local/lib/python3.7/dist-packages/torchvision/datasets/folder.py", line 146, in __init__
    samples = self.make_dataset(self.root, class_to_idx, extensions, is_valid_file)
  File "/usr/local/lib/python3.7/dist-packages/torchvision/datasets/folder.py", line 190, in make_dataset
    return make_dataset(directory, class_to_idx, extensions=extensions, is_valid_file=is_valid_file)
  File "/usr/local/lib/python3.7/dist-packages/torchvision/datasets/folder.py", line 103, in make_dataset
    raise FileNotFoundError(msg)
FileNotFoundError: Found no valid file for the classes .ipynb_checkpoints. Supported extensions are: .jpg, .jpeg, .png, .ppm, .bmp, .pgm, .tif, .tiff, .webp`

### Environment

colab

### Minimal Reproducible Example

traning classifcation  

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
The error suggests that the dataset was not found. Please make sure that your dataset exists and it contains supported files formats as listed in the error msg

**Comment by totoadel** [comment]
@AyushExel ,i see , and it is there ,and all images all .jpg formate

**Comment by totoadel** [comment]
https://ibb.co/8Mqdsr4
https://ibb.co/DQpQYvh
@AyushExel this is the images

**Comment by totoadel** [comment]
![1](https://user-images.githubusercontent.com/23275255/186222339-085844a0-a0f1-4178-868f-309af6972d06.png)
![2](https://user-images.githubusercontent.com/23275255/186222395-a09272b1-d409-4017-9a84-cc53df19fbe1.png)

**Comment by AyushExel** [comment]
@totoadel the correct syntax would be:
```
%cd yolov5
!python classify/train.py --model yolov5s-cls.pt --data '../classify'

**Comment by totoadel** [comment]
it gives error, 
```
`TensorBoard: Start with 'tensorboard --logdir runs/train-cls', view at http://localhost:6006/

Dataset not found ⚠️, missing path /yolov5/datasets, attempting download...
Downloading https://github.com/ultralytics/yolov5/releases/download/v1.0//yolov5/datasets.zip to /yolov5/datasets.zip...
Traceback (most recent call last):
  File "classify/train.py", line 331, in <module>
    main(opt)
  File "classify/train.py", line 317, in main
    train(opt, device)
  File "classify/train.py", line 83, in train
    download(url, dir=data_dir.parent)
  File "/content/yolov5/utils/general.py", line 637, in download
    download_one(u, dir)
  File "/content/yolov5/utils/general.py", line 608, in download_one
    torch.hub.download_url_to_file(url, f, progress=threads == 1)  # torch download
  File "/usr/local/lib/python3.7/dist-packages/torch/hub.py", line 593, in download_url_to_file
    u = urlopen(req)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found`
```

**Comment by AyushExel** [comment]
Hmm seems strange. Maybe @glenn-jocher can help here

**Comment by totoadel** [comment]
i use imagenette160 and it run , the i rename it to x 
and run traning it gives error 
`FileNotFoundError: [Errno 2] No such file or directory: 'x/train'`

**Comment by glenn-jocher** [comment]
@totoadel see classify/train.py Usage examples in file docstring:
https://github.com/ultralytics/yolov5/blob/51c9f9229731021f55a9ceb9f9504abfc979a54b/classify/train.py#L1-L15

**Comment by totoadel** [comment]
@glenn-jocher i try it , i try allpossible path to data , always  get error

**Comment by totoadel** [comment]
> i use imagenette160 and it run , then i rename it to x and run traning it gives error `FileNotFoundError: [Errno 2] No such file or directory: 'x/train'`

you can try this

**Comment by totoadel** [comment]
@glenn-jocher i solve the issus by 
`!python classify/train.py --model resnet50  --data 'cifar10' --epochs 100 `
then i remove the folders from cifar10 the traning and test and  then add my folders and run traning . and the traning started

**Comment by akashAD98** [comment]
im also getting exactly same issue for path @AyushExel @glenn-jocher 

```
!python classify/train.py --model resnet50 --data covid5.yaml --epochs 40 --img 224 --cache
```
<img width="238" alt="image" src="https://user-images.githubusercontent.com/62583018/211143493-45ac92ad-2479-42be-ab54-088c65293867.png">



<img width="234" alt="image" src="https://user-images.githubusercontent.com/62583018/211143438-5b5289c0-06d1-4b09-9bb5-1f6c77a2972b.png">


<img width="519" alt="image" src="https://user-images.githubusercontent.com/62583018/211143458-24af8a1e-a4ae-4b1c-a25c-952aa45d99a2.png">

**Comment by AyushExel** [comment]
For classification you don't need to pass dataset as yaml config. Just pass the dataset folder path

**Comment by akashAD98** [comment]
Okay i just replaced Cifar with my data & it worked

**Comment by AyushExel** [comment]
@akashAD98 great!
