### ISSUE TITLE
Couldn't start training when using DDP mode and using cache for training more than 300K data

### ISSUE THREAD

**Issue by lxgyChen** [ultralytics/yolov5#9116]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training, Multi-GPU

### Environment:
- OS: Ubuntu 18.04
- RAM: 1 TB
- GPU: 3090*8
- Python: 3.9.12
- PyTorch: 1.11.0
- yolov5: v6.1, v6.2

###  Description
My dataset is more than 300K，but I couldn't start training when using the following command:
`python -m torch.distributed.launch --nproc_per_node 8  train.py --cache
`
while finished load all data into RAM(it tooks about 90 minutes and 600GB RAM), it stucked at about line#229(model = smart_DDP(model)) in train.py, and couldn't start training.
if I decrease my data to 100K，all things go well.

**Comment by AyushExel** [comment]
`--cache` uses RAM by default. You might be running out of memory. Using `--cache disc` might solve your problem. If you don't have enough disc space, just train without caching

**Comment by lxgyChen** [comment]
> `--cache` uses RAM by default. You might be running out of memory. Using `--cache disc` might solve your problem. If you don't have enough disc space, just train without caching

It has been finished caching all images into ram, and there are still 400GB RAM  available.
if I don't use DDP mode, just use:
```
python train.py --device 0,1,2,3,4,5,6,7 --cache
```
It can start training normally.

**Comment by glenn-jocher** [comment]
@lxgyChen if --cache ram causes issues you can use --cache disk or simply train uncached.
