### ISSUE TITLE
How can i get the raw data of P-R curve or F1 score

### ISSUE THREAD

**Issue by beebrain** [ultralytics/yolov5#9118]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How can I get the raw data of P-R curve or F1 score?
I run val.py. It provided only the P-R image but I would like to have the raw data of P-R curve and F1 score.

**Comment by beebrain** [comment]
I have modified the metrics.py file to write the raw data file.

**Comment by glenn-jocher** [comment]
@beebrain that's great to hear that you were able to modify the metrics.py file to achieve what you needed. Modifying the metrics.py file is a suitable approach for customizing the raw data output. If you have any more questions or need further assistance with YOLOv5, feel free to ask. We're here to help!
