### ISSUE TITLE
Training using different image size

### ISSUE THREAD

**Issue by edehino** [ultralytics/yolov5#9123]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When I train a model using a dataset with 1000x1000 image size, Can I input different image size (e.g train.py --imgsz 640 ...) when training? Or shoud the input value be the same with actual image size?

**Comment by beebrain** [comment]
Yes, you can. YoloV5 will resize your image to 640.

**Comment by edehino** [comment]
> Yes, you can. YoloV5 will resize your image to 640.

And it will also resize the corresponding bounding boxes right?

**Comment by beebrain** [comment]
Yolo will take the original image size and resize it to 640 (depending on the setting). The output image will be resized again to the original size. The bounding box corresponds to your original image size.

**Comment by glenn-jocher** [comment]
@beebrain you're absolutely right! During training, YOLOv5 will resize the input image to the specified size (e.g. 640) and adjust the bounding boxes accordingly. The predictions for the resized image will then be scaled back to the original image size. If you need further details, you can check out the documentation at https://docs.ultralytics.com/yolov5/.
