### ISSUE TITLE
predicted results were not available when i transformed the model into IR for openvino

### ISSUE THREAD

**Issue by Padfoot8472** [ultralytics/yolov5#9124]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I trained a yolov5 model with my own dataset,then transform it to *.onnx model then get *.xml and *.bin format.  But when i try to use it in openvino, the output are totally different with original model.

**Comment by GabrielDornelles** [comment]
What probably happened to you is that you got the yolov5 output tensor (which is  something like shape: [1, 18900, 85]), where 85 is the number of classes, and 18900 is the case for yolov5s. After that you need to apply Non Max Supression
https://github.com/ultralytics/yolov5/blob/5d3d051c9b6bb25c45d254ceabab669c758ed72b/utils/general.py#L805)

 which then will give you the output you're expecting

**Comment by vdministrator** [comment]
> What probably happened to you is that you got the yolov5 output tensor (which is something like shape: [1, 18900, 85]), where 85 is the number of classes, and 18900 is the case for yolov5s. After that you need to apply Non Max Supression
> 
> https://github.com/ultralytics/yolov5/blob/5d3d051c9b6bb25c45d254ceabab669c758ed72b/utils/general.py#L805
> 
> )
> which then will give you the output you're expecting

As described by @Padfoot8472, the AI ​​model was converted and deployed on Raspberry pi, and Intel Neural Compute Stick 2 was used, but the bounding box was not at the target position, but shifted; the unconverted model (.pt) directly There is no problem deploying on the GPU, so I would like to ask how to solve this problem?
legend [https://ibb.co/tXJfwpq](url)

**Comment by GabrielDornelles** [comment]
You took the openvino model and made a new inference yourself is that right?

I just checked using the repo inference it works the same way as the .pt model, as running:
```
python3 detect.py --weights yolov5s_openvino_model/yolov5s.xml --source data/images/bus.jpg --imgsz 640
```

Produces:
![bus](https://user-images.githubusercontent.com/56324869/186955159-0331cfd7-cd66-44f3-b727-b9c43d32e7a6.jpg)

And running with .pt produces:

![bus](https://user-images.githubusercontent.com/56324869/186955360-e46f41bf-6121-4319-a07c-86e081a0ef10.jpg)

You can see a slight change in the prediction probablity, but the bounding boxes are in the same place

**Comment by vdministrator** [comment]
> 

My data source is a live video stream, not a picture. My purpose is just to make an AI edge computing to process the real-time video stream of the farm, identify and track the number of pigs;

**Comment by GabrielDornelles** [comment]
Can you confirm me you're using the repository detect.py inference? If not, can you provide the code you're using as the inference? I believe I've met with that case of bbox shift while writing an inference myself in the past

**Comment by Padfoot8472** [comment]
> 

Thanks for your reply, we did make a new interface for openvino model based on the older version yolov5. And I notice the openvino model can be used with detect.py now. We will update our interface according to  the new version code.
Thank you soooooooooo much.

**Comment by glenn-jocher** [comment]
@Padfoot8472 you're very welcome! I'm glad to be of help. If you come across any further questions or issues while updating your interface, feel free to ask. The YOLO community and our Ultralytics team are here to support you. Good luck with your project!
