### ISSUE TITLE
system RAM is increasing during training 1M dataset on YOLOv5m

### ISSUE THREAD

**Issue by mfaizan-ai** [ultralytics/yolov5#9126]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, we are using 1M images to train and validate. We are using yolov5m, and while training system RAM is increasing and reaches to it's maximum limit. While it's approaching to it's maximum limit, the GPU utilization plummet to a very low value and it fluctuates constantly. When we kill some processes run by python by resuming training, it creates some space in the RAM; then, again GPU utilization gets stable. Please see screenshots for further insight. My question is, what to do to keep RAM in a safe limit, so GPU utilization does not fall down to a low value? Is there any code or change in code that keeps it in an optimal range? if there are any other steps please let me know since we have to resume training again and again to make some space in the RAM by killing processes run by python.  After it starts using swap memory, during the swap memory use, it's gpu usage is still low.
![system_monitor](https://user-images.githubusercontent.com/61932757/186395712-a208edcf-0ab3-4722-9122-9f60dfff2e55.png)
![processes](https://user-images.githubusercontent.com/61932757/186396221-48b4c7e7-5ecc-4724-94d3-eb47da8782cf.png)

**Comment by glenn-jocher** [comment]
@faizan1234567 if you are using --cache then all your training data will be cached to RAM. You can use --cache disk or simply trained normally without any caching.
