### ISSUE TITLE
Choice of batch size with large dataset 

### ISSUE THREAD

**Issue by RihabJdaida** [ultralytics/yolov5#9127]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am doing the training with yolov5 with a training base of 11200 images but my machine accepts only 2 as batch size
is this will influence the precision and performance of the model?

**Comment by glenn-jocher** [comment]
@rihab974 yes. Larger batch sizes are recommended for smoother gradients. Official YOLOv5 models are trained at batch-size 128.

**Comment by rihab974** [comment]
but my pc support only 4 
any solution!

**Comment by glenn-jocher** [comment]
@rihab974 Understood. You can still train with batch size 4, but it may converge slower. You might also consider reducing your input image size to accommodate larger batch sizes. Good luck!
