### ISSUE TITLE
Precision, Recall and Mean Average Precision always equal to 0 during training coco128 dataset

### ISSUE THREAD

**Issue by ChihaoZhang** [ultralytics/yolov5#9130]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I used YOLOv5 for training custom data recently, but I found the precison, recall, and mAP during validation for every epoch always equal to 0 though the images and labels for validation are nonzero. And as a consequence, no objects can be detected.

Since this is my first time deploying YOLOv5, I thought the reason might be the faulty configuration of my dataset. So I turn to the coco128 dataset, but the problem is still unsolved.

Envs: Ubuntu18.04 + cuda10.2 +  Python3.7 + pytorch1.12.1 for py3.7_cuda10.2_cudnn7.6.5_0(created in conda environment)
HW: RTX 2080Ti

Training command: python train.py --data data/coco128.yaml --cfg models/yolov5s.yaml --weights yolov5s.pt --device 0

Screenshots:
![Screenshot from 2022-08-24 20-39-49](https://user-images.githubusercontent.com/39258417/186421208-dba8f598-1468-4d00-a2ad-e130999cbea2.png)
![Screenshot from 2022-08-24 20-16-03](https://user-images.githubusercontent.com/39258417/186421277-d034951e-9381-4526-a6aa-62fa59a8d850.png)

By the way, I once succeeded finishing the training with high P, R and mAP and everything works well, but just occasionally.

**Comment by ChihaoZhang** [comment]
This issue has been fixed in PR #9037, and everything works well when I choose the stable version 6.2.

Sorry for that I did't find the similar questions raised before until I realized may be I should try the release version.

**Comment by glenn-jocher** [comment]
@ChihaoZhang glad to hear that the issue has been fixed for you! It's always a good idea to try the stable release version if you encounter unexpected behavior. Your understanding is appreciated, and thank you for your support! If you have any further questions or concerns, feel free to reach out. Happy coding!
