### ISSUE TITLE
How can i have an empty label while using save-txt ?

### ISSUE THREAD

**Issue by cyndyNKCM** [ultralytics/yolov5#9131]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello @glenn-jocher 

Is there a way to have empty label file while using the attribute save-txt in the detection phase?
In fact i have many images, most of them are empty files but detect.py only display the labels of the image that are not empty.

**Comment by glenn-jocher** [comment]
@cyndyNKCM hi there,

You can create an empty label file by simply saving an empty text file with the same name as the image and a .txt extension in the labels folder. This signals that no objects were found in the corresponding image during detection.

If you need further guidance, you can refer to the documentation at https://docs.ultralytics.com/yolov5/ or feel free to ask for more help.

Best regards
