### ISSUE TITLE
the best.pt weight file

### ISSUE THREAD

**Issue by MZeinab** [ultralytics/yolov5#9132]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hi,
untill 2-3 days a go I have trained my yolov5 model with code in https://colab.research.google.com/github/roboflow-ai/yolov5-custom-training-tutorial/blob/main/yolov5-custom-training.ipynb#scrollTo=TWjjiBcic3Vz
and get best.pt weight file.
then i used it in zero shot object tracking from roboflow without any problem.
but now when I use that weight (the weight that i get 2 days ago) every thing is ok but when i use my today's weight it get me the error: 

![xdgb](https://user-images.githubusercontent.com/109174673/186443828-128fa3f0-af35-4165-9ca7-91268ecf34f4.PNG)

Traceback (most recent call last):
  File "clip_object_tracker.py", line 360, in <module>
    detect()
  File "clip_object_tracker.py", line 104, in detect
    yolov5_engine = Yolov5Engine(opt.weights, device, opt.classes, opt.confidence, opt.overlap, opt.agnostic_nms, opt.augment, half)
  File "/content/zero-shot-object-tracking/utils/yolov5.py", line 6, in __init__
    self.model = attempt_load(weights, map_location=device)
  File "/content/zero-shot-object-tracking/models/experimental.py", line 118, in attempt_load
    model.append(torch.load(w, map_location=map_location)['model'].float().fuse().eval())  # load FP32 model
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 1049, in _load
    result = unpickler.load()
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 1042, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'DetectionModel' on <module 'models.yolo' from '/content/zero-shot-object-tracking/models/yolo.py'>

I understood that you developed to new version yolov5 v6.2 , how can i use the previous version v6.1
could you please help clearly???|

**Comment by glenn-jocher** [comment]
@GabrielDornelles yes, reverting to the YOLOv5 v6.1 release, as ArifAstronaut suggest, is likely the simplest solution. To do so, run `git checkout tags/v6.1`, then proceed with using the best.pt weight file from the previous version. Please note that our Ultralytics Docs at https://docs.ultralytics.com/yolov5/ provide detailed information for using different versions and their associated weight files. Let me know if you need further assistance!
