### ISSUE TITLE
Curves Plotting

### ISSUE THREAD

**Issue by ZahraAnam** [ultralytics/yolov5#9133]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Dear Glen,
Thanks for this amazing model.
I have recently fine-tuned yolo for custom dataset and the plots generated are really cool.
I am trying to generate PR_Curves but seems impossible with cocoEval.stats only.
Was wondering if you can give a bit of insight into the plotting of result curves please.

### Additional

Its probablyy very naive question but am having difficulty, and would be great help if I get some insight.

**Comment by beebrain** [comment]
I am not sure about cocoEval.stats. However, I am trying to export the PR_Curve and F1_score.  I have modified the metics.py to get their data from the p_r curve figure (when I run val.py). The metics.py file has TP FP FN TN scores that might help you.

**Comment by ZahraAnam** [comment]
Thank you! Actually I was thinking to use it for some other models too.

Am doing that through MatlabApi which is not the best way.
