### ISSUE TITLE
How can i use yolov5 detect.py argument in Flask api  to save log result 

### ISSUE THREAD

**Issue by fadimenaps** [ultralytics/yolov5#9134]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello , i want to use detect.py argument for saving my streaming video result log , i create a new argument called --save-log and when i run the command : python run './detect.py' source=0 --save-log it work fine but i try to use all solution i found to make it run through Flask without any good result. 
i notice that flask use the common.py file .
please can someone help me .
Thank you all.

**Comment by glenn-jocher** [comment]
@fadimenaps hi there! Thanks for reaching out. To save the results from detect.py in a Flask API, you can modify common.py to integrate the --save-log argument with the detection process. You can then call the detect function within your Flask route to process the streaming video and save the log results as needed. If you encounter further challenges, I recommend diving into our documentation and the YOLO community for additional support. Good luck!
