### ISSUE TITLE
I am not able to get imgs from prediction output

### ISSUE THREAD

**Issue by balajib363** [ultralytics/yolov5#9135]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

AttributeError: 'Detections' object has no attribute 'imgs'

### Additional

I was using result.imgs for cropping the image as I want to crop with extra pixels I was not using the default crop method from yolo prediction output. From last week with the latest release I am getting errors like this AttributeError: 'Detections' object has no attribute 'imgs'.  Requesting you to help me how can fetch the image from the result as I am not sure in what dimension the images are resized in prediction.
Thanks

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by nanak0k** [comment]
Updated from Detections.imgs to Detections.ims in the new repository.

So, fix the` imgs` to `ims`.

Please refer to line 661.
https://github.com/ultralytics/yolov5/blob/master/models/common.py

**Comment by glenn-jocher** [comment]
@nanak0k thanks for reaching out! The `imgs` attribute has been updated to `ims` in the latest release. You can refer to line 661 in the repository for the fix.

Let me know if you have any more questions or need further assistance.
