### ISSUE TITLE
Commercial Usage of Pre-Trained Models

### ISSUE THREAD

**Issue by nepes-nepesov** [ultralytics/yolov5#9136]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is commercial usage of pre-trained models/checkpoints (such as [YOLOv5n](https://github.com/ultralytics/yolov5/releases/download/v6.2/yolov5n.pt)) allowed? What is their license?

**Comment by robotwhispering** [comment]
See, that's why we can't have nice things...

**Comment by creativesalam** [comment]
I tried a lot to find the answer. They don't give explicit answer, it is always blurry. It is one of the hurdle in our own project as well; although, we are need only the inference code in our application but even the model = torch.hub.load('ultralytics/yolov5', 'yolov5s') downloads the yolov5 repo to the .cache folder. I hope, they will clear this point soon. Whatever you do with the default inference method, the yolov5 code will reside in your source code. However you can do inferencing by writing a small bit of your own code and using custom trained weights. In that scenario, your code base won't contain there code and you will have only trained weights.

**Comment by antoszy** [comment]
I would love to know the answer to this question too. @glenn-jocher can you comment on it?

**Comment by glenn-jocher** [comment]
@antoszy hi there! Thanks for reaching out. The YOLOv5 license is AGPL-3.0, which permits commercial usage of pre-trained models and checkpoints. You can find the license details in the repository or at https://docs.ultralytics.com/yolov5/. If you have further questions, feel free to ask!
