### ISSUE TITLE
How can I use grad-cam version of this repo?I tried the author one but it is not working

### ISSUE THREAD

**Issue by noreenanwar** [ultralytics/yolov5#9139]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How can I use grad-cam version of this repo?I tried the author one but it is not working

**Comment by GabrielDornelles** [comment]
I've checked previous issues and found out that grad-cam was implemented but in an older version of this repository (yolov5.5.0). You can check it here https://github.com/ultralytics/yolov5/issues/5863

For the current version it seems like there's no code for grad-cam, what you can do is to set the visualize flag when running detect.py, and with that you'll have the feature maps for each layer saved.

If you want grad-cam, I found out this branch in the above issue: https://github.com/xiaowk5516/yolov5/tree/grad-cam

Here you can find the code for grad-cam algorithm and visualizations, just clone and checkout to grad-cam branch, then the **visualize** flag will set grad-cam

```
# git checkout grad-cam
python3 detect.py --weights yolov5s.pt --source data/images/bus.jpg --visualize
```
![image](https://user-images.githubusercontent.com/56324869/186934212-33bb28ea-aeda-4776-96ba-2cb15cef6f1a.png)

To prevent errors already, I've seem an error with the current torch versions that were automatically downloaded

```
AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor'
```

To prevent that install
```
pip install torchvision==0.10.1
pip install torch==1.9.1
```

**Comment by noreenanwar** [comment]
> I've checked previous issues and found out that grad-cam was implemented but in an older version of this repository (yolov5.5.0). You can check it here #5863
> 
> For the current version it seems like there's no code for grad-cam, what you can do is to set the visualize flag when running detect.py, and with that you'll have the feature maps for each layer saved.
> 
> If you want grad-cam, I found out this branch in the above issue: https://github.com/xiaowk5516/yolov5/tree/grad-cam
> 
> Here you can find the code for grad-cam algorithm and visualizations, just clone and checkout to grad-cam branch, then the **visualize** flag will set grad-cam
> 
> ```
> # git checkout grad-cam
> python3 detect.py --weights yolov5s.pt --source data/images/bus.jpg --visualize
> ```
> 
> ![image](https://user-images.githubusercontent.com/56324869/186934212-33bb28ea-aeda-4776-96ba-2cb15cef6f1a.png)
> 
> To prevent errors already, I've seem an error with the current torch versions that were automatically downloaded
> 
> ```
> AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor'
> ```
> 
> To prevent that install
> 
> ```
> pip install torchvision==0.10.1
> pip install torch==1.9.1
> ```

Thank you for your reply.Yes I already tried repo for this author but the results are not so good.I want to try to use the information I will get from CAM for the object.Like if its a bus in the image how can I utilize the CAM info for further process.

**Comment by glenn-jocher** [comment]
@noreenanwar thank you for your interest! The grad-cam branch you mentioned is not officially maintained or endorsed, and the current YOLOv5 repo doesn't include a built-in grad-cam capability. 

The `visualize` flag in `detect.py` does save feature maps for each layer, but to use CAM to further process object information, you'd need to implement and fine-tune a separate gradient-based localization method. The classic grad-cam algorithm often requires additional training and image-specific processing, and keep in mind that its results may vary based on the model and dataset.

Feel free to experiment and share your findings with the YOLO community. If you have any further questions, please don't hesitate to ask.
