### ISSUE TITLE
Additional detection step.

### ISSUE THREAD

**Issue by Hamza-Ghnaim** [ultralytics/yolov5#914]
## ❔Question
You guys did a great job right here, I've got a question if you don't mind.
Let's say I managed to brig up a classification model to detect vehicles only,what is the next step is should do so that my model can detect car plates after the detection of vehicles(while maintaining the real-time fps) ,and how to perform it ?

**Comment by glenn-jocher** [comment]
@Hamza-Ghnaim if you want to detect plates just train on plates, vehicles don't matter. If you want to detect both, train both.
