### ISSUE TITLE
ModuleNotFoundError: No module named 'project'

### ISSUE THREAD

**Issue by 6HawkEye6** [ultralytics/yolov5#9140]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Project in C:\Users\Viktoria\Documents\yolov5-flask

(yolov5-flask38) PS C:\Users\Viktoria\Documents\yolov5-flask> python train.py --img-size 640 --batch 64 --epochs 100 --data ../dataset.yml --weights yolov5s.pt 
Traceback (most recent call last):
  File "train.py", line 43, in <module>
    import val as validate  # for end-of-epoch mAP
  File "C:\Users\Viktoria\Documents\yolov5-flask\val.py", line 37, in <module>
    from models.common import DetectMultiBackend
  File "C:\yolov5-flask38\lib\site-packages\models\__init__.py", line 37, in <module>
    import project
ModuleNotFoundError: No module named 'project'

**Comment by glenn-jocher** [comment]
@6HawkEye6 you have a pip package called models installed which is causing conflicts. Uninstall it.
