### ISSUE TITLE
Outputs for Tensorflow js seem to be wrong

### ISSUE THREAD

**Issue by HansLuft778** [ultralytics/yolov5#9141]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hey,

so I have trained a yolov5 on a custom Dataset (detecting cars mostly), and I am quite happy with the results:

<img src="https://user-images.githubusercontent.com/42222525/186531215-46d4e9d8-e661-4eb6-9f25-1d7805342fac.jpg" width="500">

Now, when I tried to export it to tfjs, using this command:
`python yolov5/export.py --weights "yolov5/runs/train/exp21/weights/best.pt" --include tfjs`

I get, as expected, a best_web_model folder containing 7 shards and a model.json.
I uploaded all of them to github and loaded the model in JavaScript (also seems to work):
```
async function load() {
    const model = await tf.loadGraphModel('https://raw.githubusercontent.com/HansLuft778/App204/main/model.json');
    return model;
}
let model = load();
```

The problem starts with the output of the bounding box coordinates.
Here is how I predict:
```
var loadfile = function (event) {
    var image = document.getElementById('output');
    var img = new Image();
    img.src = URL.createObjectURL(event.target.files[0]);
    img.onload = function () {
        image.src = img.src;
        predictNew(img);
    }
}

function predictNew(source) {
    model.then(async function (res) {
        var i = tf.image.resizeBilinear(tf.browser.fromPixels(source), [640, 640]).div(255).expandDims(0);
        let out;
        const predictions = res.executeAsync(i).then(async predictions => {
            out = predictions;

            let boxes = Array.from(await predictions[0].dataSync());
            let classes = Array.from(await predictions[1].data());
            let scores = Array.from(await predictions[2].data());
            console.log('boxes:', boxes);
            console.log('classes:', classes);
            console.log('scores:', scores);
        });
    }, function (err) {
        console.log(err);
    });
}
```

Taking **any** image to test it, the bounding box coordinates are way off.
for example using this image: 
<img src="https://user-images.githubusercontent.com/42222525/186533327-9449cfa7-9642-41cb-9ed7-cb11b0e49a59.jpg" width="500">
the results are `0.21046173572540283, 0.31069302558898926, 0.8006026744842529, 0.7739001512527466`, that is somewhere is the top left corner.
The Label for this exact image is `0 0.503004 0.543282 0.596564 0.468992` for reference.

So is there anything I am doing wrong, or is it maybe a bug?
I though of some kind of error relating the way I load the testimage, but not sure how to do it better or diffrent.

### Additional

using the detect.py on that image I get the following result:

<img src="https://user-images.githubusercontent.com/42222525/186534347-fb14d594-992f-4a03-b6c4-43279550f6c5.jpg" width="500">

**Comment by glenn-jocher** [comment]
@HansLuft778 seems like you might be confusing xywh vs xyxy format labels/predictions

**Comment by HansLuft778** [comment]
> 

This seems to be it.

Out of curiosity, is there a specific reason why annotation labels and output label coordinates are not consistent?

**Comment by glenn-jocher** [comment]
YOLOv5 natively outputs xywh, if TF.js is outputting xyxy it's in the export process somewhere

**Comment by HansLuft778** [comment]
ok, i See. Thanks!

**Comment by glenn-jocher** [comment]
@HansLuft778 you're welcome! If you have any more questions or need further assistance, feel free to ask. Good luck with your project!
