### ISSUE TITLE
Where are you leading camera images?

### ISSUE THREAD

**Issue by Heartful-echo** [ultralytics/yolov5#9143]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi

I'm using a webcam and running YOLO with the commands below.
python3 detect.py --source 0 --weights yolov5s.pt

Are you loading the images from the webcam with the LoadStreams class in dataloaders.py?

I added LOGGER.info('images read!') to the line below "_, self.imgs[i] = cap.read()", but once at startup it shows up on the terminal but is no longer displayed.

Where the hell is cap.read()?

**Comment by glenn-jocher** [comment]
@kazuya-uchida webcams are loaded with utils.dataloaders.LoadStreams
