### ISSUE TITLE
about Translation augment

### ISSUE THREAD

**Issue by konioy** [ultralytics/yolov5#9146]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Why is the parameter of Translation  greater than 0, that is, it only translates to the right or down？
    translate = 0.1
    T = np.eye(3)
    T[0, 2] = random.uniform(0.5 - translate, 0.5 + translate) * width  # x translation (pixels)
    T[1, 2] = random.uniform(0.5 - translate, 0.5 + translate) * height  # y translation (pixels)

**Comment by sarpx** [comment]
That's a pretty good question.. I'm interested in the answer too.

**Comment by sarpx** [comment]
Also, even if we do translate = 0, it seems like we can't get the translate not to be used..

**Comment by glenn-jocher** [comment]
@konioy obviously the translation matrix you show in your question is not only in 1 direction but in any.
