### ISSUE TITLE
classfiy train should be check device support image.half() or not!!!

### ISSUE THREAD

**Issue by moowcharnfu** [ultralytics/yolov5#9148]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

cuda = device.type != 'cpu'

############ bug #################
pred = torch.max(ema.ema((images.half() if cuda else images.float()).to(device)), 1)[1]
################################

### Environment

tesla V-100 + python 3 +  torch1.7.1

### Minimal Reproducible Example

cuda not support half!!

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@moowcharnfu issue has been resolved in latest master. classify/predict has been fully updated.
