### ISSUE TITLE
How can I put webcam into tkinter?

### ISSUE THREAD

**Issue by ikiki1008** [ultralytics/yolov5#9149]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'd like to open tkinter with webcam inside of Tk when detect.py is running.
at first I coded like this 

win = Tk()
win.geometry("700x350")
label = Label(win)
label.grid(row=0, column=0)
cap = cv2.VideoCapture(0)

def show_frames():
    cv2image = cv2.cvtColor(cap.read()[1], cv2.COLOR_BGR2RGB)
    img = Image.fromarray(cv2image)

    imgtk = ImageTk.PhotoImage(image=img)
    label.imgtk = imgtk
    label.configure(image=imgtk)
    label.after(20, show_frames)

with this code I succeed to open tkinter with webcam on, but the yolov5 cannot detect things with this code.
how can I put webcam into tkinter page when detect.py is running?

**Comment by glenn-jocher** [comment]
@ikiki1008 ```python
import tkinter as tk
import cv2
from PIL import Image, ImageTk

win = tk.Tk()
win.geometry("700x350")
label = tk.Label(win)
label.grid(row=0, column=0)
cap = cv2.VideoCapture(0)

def show_frames():
    _, frame = cap.read()
    cv2image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    img = Image.fromarray(cv2image)
    imgtk = ImageTk.PhotoImage(image=img)
    label.imgtk = imgtk
    label.configure(image=imgtk)
    label.after(20, show_frames)

show_frames()  # Start the webcam feed
win.mainloop()
```
