### ISSUE TITLE
I am getting messed up outputs

### ISSUE THREAD

**Issue by amunamun07** [ultralytics/yolov5#9152]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hey, I am taking the yolov5s saved_model. I have made the predictions and I want to have the boxes, confidence and scores with non max suppression from the output. How do i get these results?

**Comment by glenn-jocher** [comment]
@amunamun07 TF usage examples are displayed by export.py upon export, follow those.
