### ISSUE TITLE
My cls_loss is always 0 in my custom dataset!

### ISSUE THREAD

**Issue by LeeChanHyuk** [ultralytics/yolov5#9153]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

**[Problem]**
I trained YOLO V5 with my own dataset.
However, during the training process, I found the cls_loss is always 0!
But, there is normal cls_loss if I try to train with coco128.

**[Settings]**
I didn't change any code in this repo.
And I converted my dataset with the site (https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data)
Also, I already check the dataset path

**[custom yaml file]**

path: ../datasets/biwi/
train: images/train  # 118k images
val: images/valid  # 5k images
test: images/test  # 20k images for submission to https://competitions.codalab.org/competitions/20794

# class names
names:
  0: face

**Folder paths**
##datasets
####coco128
####biwi
######images
########train
########valid
########test
######labels
########train
########valid
########test
##yolov5

![스크린샷, 2022-08-25 20-52-00](https://user-images.githubusercontent.com/47438388/186658648-aec3c170-789b-48d5-afb2-76928bb29b7c.png)
![스크린샷, 2022-08-25 20-52-24](https://user-images.githubusercontent.com/47438388/186658649-9fecafca-60e0-4c98-95ff-32a7fa3f67e5.png)

Thank you for your help!

  

### Environment

- YOLO: YOLO V5
- OS: Ubuntu 18.04
- Python: 3.7

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by LeeChanHyuk** [comment]
I found this problem is related to class numbers.
Since there is only one class in my dataset, of course, the class loss was 0...

**Comment by glenn-jocher** [comment]
@LeeChanHyuk glad to hear you've found the solution! Indeed, with only one class in your dataset, a class loss of 0 is expected. If you have any other questions or need further assistance in the future, feel free to reach out. Thank you for your understanding and contribution to the YOLO community.
