### ISSUE TITLE
About AutoBatch

### ISSUE THREAD

**Issue by z1069614715** [ultralytics/yolov5#9156]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi! I want to use your autobatch function in my code, but have something problem,  Could you please take a look at it for me?
![image](https://user-images.githubusercontent.com/45996119/186685110-7cd421f8-4814-4f13-9609-7e07b8ed8b39.png)
as shown above, You can see my gpu memory is not increasing, but this autobatch function in working order in yolov5 code.
Why?
Wait patiently for your answer!

**Comment by robotwhispering** [comment]
Why does it say "Using batch-size 253731...", but it looks like it suggested batch-size of 16.

**Comment by glenn-jocher** [comment]
@z1069614715 can you confirm you are seeing this issue in master?

AutoBatch is experimental and may not work in all circumstances, so if you are getting unreliable results you should set your batch-size manually.

**Comment by glenn-jocher** [comment]
@z1069614715 I've pushed PR #9209 to protect from super high batch size predictions, but the reality is that CUDA memory utilisation is sometimes hard to reproduce and measure correctly, especially if previous trainings are running, have run or been terminated early.

**Comment by z1069614715** [comment]
> @z1069614715 I've pushed PR #9209 to protect from super high batch size predictions, but the reality is that CUDA memory utilisation is sometimes hard to reproduce and measure correctly, especially if previous trainings are running, have run or been terminated early.

Thanks for your help, I have solved the problem, The reason is that (torch.backends.cudnn.benchmark) I set it to True, if True AutoBatch will lose efficacy.

**Comment by glenn-jocher** [comment]
@z1069614715 got it. Should we set `benchmark(False)` before running AutoBatch? Benchmark(True) during training should only occur on non-zero seeds it seems, though that doesn't make much sense. I've created PR https://github.com/ultralytics/yolov5/pull/9259 to update this.
