### ISSUE TITLE
Understanding the label text file contents of yolov5 inference

### ISSUE THREAD

**Issue by ilmseeker** [ultralytics/yolov5#9160]
[video_frame_3.txt](https://github.com/ultralytics/yolov5/files/9428377/video_frame_3.txt)

 - I have this text file as one of the results for the labels from detect.py. I know that 1st column is related to the class but how can I know which these other columns are relating to. As these values are normalized, it is difficult to understand which columns are for xmin, ymin, xmax, ymax, confidence.

- Is there any method to not include confidence values in the image annotations text file. 

- Also, I am little confused here because yolov5 accepts (xcentre, y centre, width, height) as input values of bounding boxes but as per your reply above, it outputs values in the form of (xmin, ymin, xmax, ymax).

- And, how can I show confidence %age along with the name of the class in the detection images

_Originally posted by @sajjad-haider-khan in https://github.com/ultralytics/yolov5/issues/5426#issuecomment-1227789097_

**Comment by barney2074** [comment]
From detect.py
![Screenshot from 2022-08-26 09-31-40](https://user-images.githubusercontent.com/25944617/186789694-af1a83a0-5ba4-4a61-bb14-6016c289c30e.png)

So the columns are class, xywh, confidence (x & y of the centre)
You could modify this section of detect.py to suit your needs

**Comment by robotwhispering** [comment]
It's very interesting to me that you're experiencing the values of 4 box coordinates to be derived differently between input and output. The reason it's so interesting to me is because I use the models that I train successfully to then semi-auto-label my next batches of training data. And then I train with the txt files created from inferencing. How would you resolve that?

**Comment by sajjad-haider-khan** [comment]
Thanks @barney2074. You made my day :)
