### ISSUE TITLE
Output segmented object after object detection

### ISSUE THREAD

**Issue by danielzhangau** [ultralytics/yolov5#9161]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

My goal is to try to get segmentation results of detected objects.
From my understanding of how Yolo object detection works, it's a pixel-wise technique that involves predicting a label for each pixel in an image. For each segment, or cluster of pixels with the same label, the bounding box is created by predicting the width and height as offsets from the centroid. For each segment, a bounding box is created for all possible places where the object could be located. This is considered a **dense** sample of **regions of interest** (ROI).
Can I output this **dense** sample from which stage？
A more subjective example is the butterfly detected in the picture below. I can get the pixel-wise segmentation output through object detection.
![image](https://user-images.githubusercontent.com/41173132/186828220-0f74927c-63f0-4419-84e6-c24f79baf8a1.png)

### Use case

- Get segmentation result out of object detection result
- Simplify training a segmentation model by labelling a large number of segmented objects.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
Hello. Realtime Instance segmentation will be available in the next update. We haven't prioritized semantic segmentation yet but we plan to work on it later this year.

**Comment by danielzhangau** [comment]
> Hello. Realtime Instance segmentation will be available in the next update. We haven't prioritized semantic segmentation yet but we plan to work on it later this year.

Hello Ayush! thanks for letting me know! But my idea is a bit different than training individual instance segmentation, my ideal solution would be to take the grouped pixels inside the detected bounding box from the object detection result.

**Comment by AyushExel** [comment]
@danielzhangau okay.. Maybe I don't understand properly but isn't that similar to instance segmentation? You can just take the masks and leave out the boxes for object?

**Comment by danielzhangau** [comment]
@AyushExel Yeah, the idea is from instance segmentation. But I am not talking about training another instance segmentation model here. I am trying to see if there is a way to obtain the mask during object detection because the tight bounding box is drawn based on the pixel group.
