### ISSUE TITLE
How to set both width and height of inputs in v6.2?

### ISSUE THREAD

**Issue by realgump** [ultralytics/yolov5#9162]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

In version 5.0, I could set a tuple input of --img to train rectangle inputs. However, I notice that the --img args only support int in version 6.2. So what is the reason for not supporting rectangle inputs anymore? How could I train the model with rectangle inputs?

**Comment by robotwhispering** [comment]
In detect.py, that argument seems to take nargs='+', so --img 480 640 should work. Of course, remembering that in YoloV5, it's parsed H and then W.

**Comment by realgump** [comment]
In version 5.0, the training seems to support nargs='+':
[https://github.com/ultralytics/yolov5/blob/f5b8f7d54c9fa69210da0177fec7ac2d9e4a627c/train.py#L464](https://github.com/ultralytics/yolov5/blob/f5b8f7d54c9fa69210da0177fec7ac2d9e4a627c/train.py#L464)
while in version 6.2 the nargs='+' disappears:
[https://github.com/ultralytics/yolov5/blob/d3ea0df8b9f923685ce5f2555c303b8eddbf83fd/train.py#L442](https://github.com/ultralytics/yolov5/blob/d3ea0df8b9f923685ce5f2555c303b8eddbf83fd/train.py#L442)
So I am really puzzled by this change.

**Comment by robotwhispering** [comment]
Yeah, you're right. The nargs='+' is even still in detect.py and export.py. However, not in train.py, nor val.py (I would imagine both would need to support the second argument).

**Comment by glenn-jocher** [comment]
Rectangular training command is `python train.py --img 640 --rect`

**Comment by robotwhispering** [comment]
Does it clamp one end and set the other side according to that
image's aspect ratio? That's pretty smooth.


Warm regards,

Scott Uneberg
(918) 883-8842

**Comment by glenn-jocher** [comment]
@robotwhispering yes for dynamic models --img-size sets the long side and the short side is handled automatically. Unevenly shaped image batches are also handled automatically for minimum area, with val.py sorting by aspect ratio to group similarly shaped images together for overall dataset FLOPs optimization during validation.
