### ISSUE TITLE
NCLL error when trained on Objects365

### ISSUE THREAD

**Issue by Stephen-Hao** [ultralytics/yolov5#9163]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

train: Scanning '/mnt/mfs2/hao.shen/hao.shen/data/o365_datasets/labels/train' images and labels...113162 found, 0 missing, 0 empty, 0 corrupt:   6%|▋ [E ProcessGroupNCCL.cpp:414] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data. To avoid this inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 7] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1806530 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:737] [Rank 6] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1806610 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:737] [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1806649 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:414] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data. To avoid this inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 4] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1806411 milliseconds before timing out.
train: Scanning '/mnt/mfs2/hao.shen/hao.shen/data/o365_datasets/labels/train' images and labels...113236 found, 0 missing, 0 empty, 0 corrupt:   6%|▋ [E ProcessGroupNCCL.cpp:737] [Rank 5] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1806786 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:737] [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1806826 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:414] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data. To avoid this inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 6] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1806610 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:414] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data. To avoid this inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 5] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1806786 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:414] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data. To avoid this inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1806649 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:414] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data. To avoid this inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1806826 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:414] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data. To avoid this inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1806135 milliseconds before timing out.
train: Scanning '/mnt/mfs2/hao.shen/hao.shen/data/o365_datasets/labels/train' images and labels...114325 found, 0 missing, 0 empty, 0 corrupt:   7%|▋ WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 146509 closing signal SIGTERM
Process ForkPoolWorker-4:
Process ForkPoolWorker-5:
Process ForkPoolWorker-8:
Process ForkPoolWorker-7:
Process ForkPoolWorker-6:
Process ForkPoolWorker-1:
Process ForkPoolWorker-3:
Process ForkPoolWorker-2:
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 1 (pid: 146510) of binary: /home/hao.shen/.conda/envs/yolo/bin/python
Traceback (most recent call last):
  File "/mnt/mfs2/hao.shen/hao.shen/yolov5/utils/dataloaders.py", line 465, in __init__
    assert cache['hash'] == get_hash(self.label_files + self.im_files)  # identical hash
AssertionError

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by firstelfin** [comment]
@Stephen-Hao The amount of data is too large, and the memory access operation exceeds the default 1800000. You can use cache for training, or add timeout to try.

**Comment by Stephen-Hao** [comment]
> @Stephen-Hao The amount of data is too large, and the memory access operation exceeds the default 1800000. You can use cache for training, or add timeout to try.

Thank you very much ! Can you tell me how can I add timeout in Pytorch DDP source code?

**Comment by firstelfin** [comment]
@Stephen-Hao  You can find the timeout setting in
```python
torch.distributed.init_process_group(backend, init_method=None, timeout=datetime.timedelta(seconds=1800), world_size=- 1, rank=- 1, store=None, group_name='', pg_options=None)
```

**Comment by glenn-jocher** [comment]
@Stephen-Hao @firstelfin should we increase the timeout or simply remove it?

**Comment by glenn-jocher** [comment]
@Stephen-Hao @firstelfin from the docs it looks like timeout should not apply to NCCL, only Gloo. Default is already 30 min.

```
timeout (timedelta, optional): Timeout for operations executed against
            the process group. Default value equals 30 minutes.
            This is applicable for the ``gloo`` backend. For ``nccl``, this is
            applicable only if the environment variable ``NCCL_BLOCKING_WAIT``
            or ``NCCL_ASYNC_ERROR_HANDLING`` is set to 1. When
            ``NCCL_BLOCKING_WAIT`` is set, this is the duration for which the
            process will block and wait for collectives to complete before
            throwing an exception. When ``NCCL_ASYNC_ERROR_HANDLING`` is set,
            this is the duration after which collectives will be aborted
            asynchronously and the process will crash. ``NCCL_BLOCKING_WAIT``
            will provide errors to the user which can be caught and handled,
            but due to its blocking nature, it has a performance overhead. On
            the other hand, ``NCCL_ASYNC_ERROR_HANDLING`` has very little
            performance overhead, but crashes the process on errors. This is
            done since CUDA execution is async and it is no longer safe to
            continue executing user code since failed async NCCL operations
            might result in subsequent CUDA operations running on corrupted
            data. Only one of these two environment variables should be set.
            For ``ucc``, blocking wait is supported similar to NCCL. However,
            async error handling is done differently since with UCC we have
            progress thread and not watch-dog thread.
```

**Comment by michaelzhang-ai** [comment]
> @Stephen-Hao You can find the timeout setting in
> 
> ```python
> torch.distributed.init_process_group(backend, init_method=None, timeout=datetime.timedelta(seconds=1800), world_size=- 1, rank=- 1, store=None, group_name='', pg_options=None)
> ```

@glenn-jocher 
Could I ask how should I replace this code or where should I put it? thanks https://github.com/ultralytics/yolov5/blob/ab5b9174940f29a62374bddaf38cd5d2eeb68e25/train.py#L560

**Comment by glenn-jocher** [comment]
@sibozhang The mentioned line of code is typically used to initialize the process group for distributed training. In the YOLOv5 source code, this initialization is handled automatically by the `torch.nn.parallel.DistributedDataParallel` wrapper which you can find in the `train.py` script. There is no need to change the `torch.distributed.init_process_group` call directly. The timeout setting you mentioned is likely not the cause of your current issue. If you are experiencing NCCL timeout errors, it's recommended to review your training setup, network configuration, and system resources. You can also check the environment variables such as `NCCL_BLOCKING_WAIT` and `NCCL_ASYNC_ERROR_HANDLING` as they might affect the behavior of NCCL operations. Let me know if you need further assistance.
