### ISSUE TITLE
How does the eval function associate conv with < class' models. Common. Conv '

### ISSUE THREAD

**Issue by xiaojun-mbed** [ultralytics/yolov5#9164]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How does the eval function associate conv with < class' models. Common. Conv '

I've searched the common.py file, but I can't find the eval() function

### Additional

![image](https://user-images.githubusercontent.com/54529051/186852327-3122d13b-5969-40ab-8d2d-3d7a606d9e07.png)

**Comment by glenn-jocher** [comment]
@xiaojun-mbed the `eval()` function is a built-in Python function that evaluates the specified expression, often used for dynamically evaluating code.

Regarding the association of `conv` with `models.Common.Conv`, the relationship is established through the use of Python class inheritance. The `models.Common.Conv` class inherits from the `torch.nn.Module` class, which is a standard practice in PyTorch for defining neural network modules. This allows `models.Common.Conv` to utilize the properties and methods defined in `torch.nn.Module`, such as those related to convolutional layers (`conv`).

You can find more details about this in the `models/common.py` file. If you have further questions or need specific guidance, feel free to ask. We're here to help!
