### ISSUE TITLE
confusion matrix always uses default inference  conf 0.25 and iou 0.45 why the results are different??

### ISSUE THREAD

**Issue by srn-source** [ultralytics/yolov5#9165]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I used `python val.py --data my_data.yaml --imgsz 1280  --iou-thres 0.45 --conf-thres 0.25 --weights best.pt`
I got Ture Positive class 0 = 84 and class 1 = 85

compared to this command `python val.py --data my_data.yaml --imgsz 1280  --iou-thres 0.5 --conf-thres 0.4 --weights best.pt`
I got Ture Positive class 0 = 83 and class 1 = 84

if you told that confusion matrix always uses default inference  conf 0.25 and iou 0.45 why the results are different?

**Comment by glenn-jocher** [comment]
@srn-source you're not understanding validation. IoU threshold is used by NMS to reject overlapping boxes. This occurs before any metrics are computed.

**Comment by srn-source** [comment]
@glenn-jocher  I knew that points but my question is if we always use iou 0.45 why results are different for 2 different commands?

**Comment by glenn-jocher** [comment]
@srn-source you used two different IoU thresholds in your two commands which are naturally going to produce two different results as I explained in https://github.com/ultralytics/yolov5/issues/9165#issuecomment-1234590095

**Comment by srn-source** [comment]
@glenn-jocher oh thank you for the clear answer, before i opened new issue on github, i try to figure outand by myself and i found some issues told that confusion metric in yolov5 always using fixed number IOU and ignore my commands.

**Comment by glenn-jocher** [comment]
@srn-source glad to be of help! 🙌 Keep up the great work and feel free to ask if you have any more questions. The YOLO community and the Ultralytics team are here to support you.
