### ISSUE TITLE
Problems with python packages

### ISSUE THREAD

**Issue by A-Piccoli** [ultralytics/yolov5#9166]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

When i try to load a local pytorch model, yolo cant'find two modules who are installed and with the correct version, as you can see in the screenshot
![image](https://user-images.githubusercontent.com/95079936/186880849-a1226a19-5732-477d-b7de-54b9ccddf5e5.png)
![image](https://user-images.githubusercontent.com/95079936/186880912-015a2887-3e92-4afe-a485-1625d5089851.png)
I already put `force_reload = True` and every time i try to load a new model this error messages appears, and also i have the latest version of this repo

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by A-Piccoli** [comment]
ok, but why yolov5 try to install packages which are already installed or updated, that's my doubt

**Comment by glenn-jocher** [comment]
@A-Piccoli it doesn't install packages that are already installed when the environment was initialized.
