### ISSUE TITLE
How to get class data?

### ISSUE THREAD

**Issue by gurselturkeri** [ultralytics/yolov5#9167]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I want to know how to  class name publish in detection.py. Which code line?
![1](https://user-images.githubusercontent.com/68682737/186881731-53a0db0a-e139-4ba2-9d24-a5fa4d3ec5a9.png)

**Comment by AyushExel** [comment]
It can be found in the `names` variable. For example this is the call which prints it to the terminal
https://github.com/ultralytics/yolov5/blob/f2b8f3fe3a3ae2b601706e5bea9f25265eb2fcd9/detect.py#L154

**Comment by gurselturkeri** [comment]
> It can be found in the `names` variable. For example this is the call which prints it to the terminal
> 
> https://github.com/ultralytics/yolov5/blob/f2b8f3fe3a3ae2b601706e5bea9f25265eb2fcd9/detect.py#L154

Thanks. `names[int(c)]` give me what i want

**Comment by glenn-jocher** [comment]
@gurselturkeri you're welcome! Glad to hear that `names[int(c)]` worked for you. If you have any more questions, feel free to ask!
