### ISSUE TITLE
Torchscript inference error: RuntimeError: The size of tensor a (100) must match the size of tensor b (80) at non-singleton dimension 3

### ISSUE THREAD

**Issue by himmetozcan** [ultralytics/yolov5#9171]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

```
Loading /home/abdullah/yolov5/runs/train/data_4189_smallmodel_800_64_250/weights/best.torchscript for TorchScript inference...
Traceback (most recent call last):
  File "detect.py", line 254, in <module>
    main(opt)
  File "detect.py", line 249, in main
    run(**vars(opt))
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 109, in run
    model.warmup(imgsz=(1 if pt else bs, 3, *imgsz))  # warmup
  File "/home/abdullah/yolov5/models/common.py", line 536, in warmup
    self.forward(im)  # warmup
  File "/home/abdullah/yolov5/models/common.py", line 472, in forward
    y = self.model(im)[0]
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/models/yolo.py", line 71, in forward
    _35 = (_20).forward(_34, )
    _36 = (_22).forward((_21).forward(_35, ), _29, )
    _37 = (_24).forward(_33, _35, (_23).forward(_36, ), )
           ~~~~~~~~~~~~ <--- HERE
    return (_37,)
class Detect(Module):
  File "code/__torch__/models/yolo.py", line 101, in forward
    _19 = torch.split_with_sizes(torch.sigmoid(_18), [2, 2, 2], 4)
    xy, wh, conf, = _19
    _20 = torch.add(torch.mul(xy, CONSTANTS.c0), CONSTANTS.c1)
          ~~~~~~~~~ <--- HERE
    xy0 = torch.mul(_20, torch.select(CONSTANTS.c2, 0, 0))
    _21 = torch.pow(torch.mul(wh, CONSTANTS.c0), 2)

Traceback of TorchScript, original code (most recent call last):
/home/abdullah/yolov5/models/yolo.py(72): forward
/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py(1090): _slow_forward
/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py(1102): _call_impl
/home/abdullah/yolov5/models/yolo.py(105): _forward_once
/home/abdullah/yolov5/models/yolo.py(192): forward
/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py(1090): _slow_forward
/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py(1102): _call_impl
/opt/conda/lib/python3.7/site-packages/torch/jit/_trace.py(965): trace_module
/opt/conda/lib/python3.7/site-packages/torch/jit/_trace.py(750): trace
export.py(116): export_torchscript
export.py(100): outer_func
export.py(506): run
/opt/conda/lib/python3.7/site-packages/torch/autograd/grad_mode.py(28): decorate_context
export.py(589): main
export.py(594): <module>
RuntimeError: The size of tensor a (100) must match the size of tensor b (80) at non-singleton dimension 3

```

### Environment

- Python 3.7.12
- OS: Debian GNU/Linux 10
- Yolov5

### Minimal Reproducible Example

` python3 detect.py --weights /home/abdullah/yolov5/runs/train/data_4189_smallmodel_800_64_250/weights/best.torchscript --img 800 --conf 0.1 --source ./test_images/test`

### Additional

I can convert my trained model to torchscript. When I try to do the inference, I got this error. Is this a bug?
`RuntimeError: The size of tensor a (100) must match the size of tensor b (80) at non-singleton dimension 3`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@himmetozcan user error. You must export at the size you want to run inference at.

**Comment by Zalways** [comment]
i met the same question with you, did you solved this problem? and how do you solved it?thanks

**Comment by glenn-jocher** [comment]
@Zalways hello! I'm sorry to hear that you're experiencing the same issue. In order to help you, could you please provide a bit more information about the problem you're facing? Specifically, could you share any error messages or traceback information you've encountered? This will allow us to better understand the issue and provide a solution. Thank you!

**Comment by Zalways** [comment]
> @Zalways hello! I'm sorry to hear that you're experiencing the same issue. In order to help you, could you please provide a bit more information about the problem you're facing? Specifically, could you share any error messages or traceback information you've encountered? This will allow us to better understand the issue and provide a solution. Thank you!

thank you for your reply!!! my model is a textspotter model based deformable detr,i want to export the model into torchscript format(tracing), during export model into torchscript, i met a problem, and i fix it,then i get a .ts model file(i use the official code to export my model: 
 https://github.com/facebookresearch/detectron2/blob/main/tools/deploy/export_model.py) ,but this exported model only can infrence the image i used for exporting the model, but for thoese other image or specific shaped tensors,it shows the error message:

/root/miniconda3/envs/deepsolo/lib/python3.8/site-packages/torch/nn/modules/module.py:1051: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return forward_call(*input, **kwargs)
Traceback (most recent call last):
  File "/root/autodl-tmp/project/deploy/export_model.py", line 264, in <module>
    out1 = m(data)
  File "/root/miniconda3/envs/deepsolo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/detectron2/export/flatten.py", line 9, in forward
  def forward(self: __torch__.detectron2.export.flatten.TracingAdapter,
    argument_1: Tensor) -> Tuple[Tensor, Tensor, Tensor, Tensor, Tensor, Tensor, Tensor]:
    _0, _1, _2, _3, _4, _5, _6, = (self.model).forward(argument_1, )
                                   ~~~~~~~~~~~~~~~~~~~ <--- HERE
    return (_0, _1, _2, _3, _4, _5, _6)
  File "code/__torch__/adet/modeling/text_spotter.py", line 23, in forward
    batched_imgs = torch.unsqueeze_(_7, 0)
    x0 = torch.contiguous(batched_imgs)
    _8, _9, _10, _11, = (_0).forward(x0, image_size, )
                         ~~~~~~~~~~~ <--- HERE
    _12 = torch.softmax(_9, -1)
    prob = torch.sigmoid(torch.mean(_8, [-2]))
  File "code/__torch__/adet/modeling/model/detection_transformer.py", line 50, in forward
    _29 = getattr(self.input_proj, "1")
    _30 = getattr(self.input_proj, "0")
    _31 = (self.backbone).forward(x, image_size, )
           ~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46, _47, _48, _49, _50, _51, _52, _53, _54, _55, _56, _57, = _31
    _58 = (_30).forward(_32, )
  File "code/__torch__/adet/modeling/text_spotter.py", line 104, in forward
    image_size: Tensor) -> Tuple[Tensor, Tensor, Tensor, Tensor, Tensor, Tensor, Tensor, Tensor, Tensor, Tensor, Tensor, Tensor, Tensor, Tensor, Tensor, Tensor, Tensor, Tensor, Tensor, Tensor, Tensor, Tensor, Tensor, Tensor, Tensor, Tensor]:
    _61 = getattr(self, "1")
    _62 = (getattr(self, "0")).forward(x, image_size, )
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    _63, _64, _65, _66, _67, _68, _69, = _62
    pos_embed = torch.to((_61).forward(_63, ), 6)
  File "code/__torch__/adet/modeling/text_spotter.py", line 143, in forward
    _92 = torch.slice(torch.slice(_91, 0, 0, 125), 1, 0, 138)
    _93 = torch.view(CONSTANTS.c2, annotate(List[int], []))
    _94 = torch.copy_(_92, torch.expand(_93, [125, 138]))
          ~~~~~~~~~~~ <--- HERE
    masks_per_feature_level0 = torch.ones([_85, _86, _87], dtype=11, layout=None, device=torch.device("cpu"), pin_memory=False)
    _95 = torch.select(masks_per_feature_level0, 0, 0)

Traceback of TorchScript, original code (most recent call last):
/root/autodl-tmp/project/adet/modeling/text_spotter.py(60): mask_out_padding
/root/autodl-tmp/project/adet/modeling/text_spotter.py(43): forward
/root/miniconda3/envs/deepsolo/lib/python3.8/site-packages/torch/nn/modules/module.py(1039): _slow_forward
/root/miniconda3/envs/deepsolo/lib/python3.8/site-packages/torch/nn/modules/module.py(1051): _call_impl
/root/autodl-tmp/project/adet/modeling/text_spotter.py(21): forward
/root/miniconda3/envs/deepsolo/lib/python3.8/site-packages/torch/nn/modules/module.py(1039): _slow_forward
/root/miniconda3/envs/deepsolo/lib/python3.8/site-packages/torch/nn/modules/module.py(1051): _call_impl
/root/autodl-tmp/project/adet/modeling/model/detection_transformer.py(168): forward
/root/miniconda3/envs/deepsolo/lib/python3.8/site-packages/torch/nn/modules/module.py(1039): _slow_forward
/root/miniconda3/envs/deepsolo/lib/python3.8/site-packages/torch/nn/modules/module.py(1051): _call_impl
/root/autodl-tmp/project/adet/modeling/text_spotter.py(220): forward
/root/miniconda3/envs/deepsolo/lib/python3.8/site-packages/torch/nn/modules/module.py(1039): _slow_forward
/root/miniconda3/envs/deepsolo/lib/python3.8/site-packages/torch/nn/modules/module.py(1051): _call_impl
/root/miniconda3/envs/deepsolo/lib/python3.8/site-packages/detectron2/export/flatten.py(259): <lambda>
/root/miniconda3/envs/deepsolo/lib/python3.8/site-packages/detectron2/export/flatten.py(294): forward
/root/miniconda3/envs/deepsolo/lib/python3.8/site-packages/torch/nn/modules/module.py(1039): _slow_forward
/root/miniconda3/envs/deepsolo/lib/python3.8/site-packages/torch/nn/modules/module.py(1051): _call_impl
/root/miniconda3/envs/deepsolo/lib/python3.8/site-packages/torch/jit/_trace.py(952): trace_module
/root/miniconda3/envs/deepsolo/lib/python3.8/site-packages/torch/jit/_trace.py(735): trace
/root/autodl-tmp/project/deploy/export_model.py(125): export_tracing
/root/autodl-tmp/project/deploy/export_model.py(224): <module>
/root/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py(18): execfile
/root/.pycharm_helpers/pydev/pydevd.py(1496): _exec
/root/.pycharm_helpers/pydev/pydevd.py(1489): run
/root/.pycharm_helpers/pydev/pydevd.py(2177): main
/root/.pycharm_helpers/pydev/pydevd.py(2195): <module>
RuntimeError: The size of tensor a (50) must match the size of tensor b (125) at non-singleton dimension 0

**Comment by glenn-jocher** [comment]
@Zalways the error you're encountering seems to be related to a mismatch in tensor sizes during inference with your exported TorchScript model. Specifically, the error message suggests that the size of "tensor a" is 50 while the size of "tensor b" is 125, and they need to match at non-singleton dimension 0.

Here are a few things you can try to resolve this issue:

1. Ensure that the size of your input tensors matches the expected size of the model. Make sure that the dimensions of your input tensors are compatible with the model's input requirements.

2. Double-check the preprocessing steps you're applying to the input data. If you're resizing or transforming the input tensors, ensure that the transformations are applied consistently during both training and inference.

3. Verify that the exported TorchScript model accurately represents the trained model. Ensure that the exported model contains the correct architecture and weights, and that there are no modifications or discrepancies in the exported model code.

By carefully checking these aspects, you should be able to resolve the tensor size mismatch issue and successfully run inference with your exported TorchScript model. Let us know if you have any further questions or issues!

**Comment by Zalways** [comment]
thanks for your advice! i checked the three aspects, but it still doesn't work.
i use a image as the example image for exporting the model, and then the exported model only can inference on the same exsample image, if i change another image,it doesn't work. i  have no idea about it.
[Details of problem I met.docx](https://github.com/ultralytics/yolov5/files/12308113/Details.of.problem.I.met.docx)

all the infomation is in the word file.

**Comment by glenn-jocher** [comment]
@Zalways thank you for your feedback and for providing the details of the problem you're facing. I understand that you have checked the suggested aspects and are still encountering difficulties with your YOLOv5 model.

Considering your description, it seems that the exported model is only able to perform inference on the example image that was used during the export process, and fails to work with different images. This issue is not uncommon and could be caused by various factors.

To help you further, please consider the following:

1. Verify that the input images you are trying to use for inference are properly preprocessed. Ensure that they are resized, normalized, and formatted according to the requirements of the YOLOv5 model.

2. Review the code used for exporting the YOLOv5 model. Pay close attention to any image-specific parameters or preprocessing steps that might be affecting the model's ability to handle different images.

3. Check if there are any specific dependencies or dataset-related configurations that could be affecting the model's performance with different images.

If you have already checked these aspects and the issue persists, it might be beneficial to provide additional information such as the specific steps you followed, code snippets, or any error messages you encountered. This will help the YOLOv5 community to gain a better understanding of your issue and provide more targeted assistance.

I hope this guidance helps you in troubleshooting the problem. Please don't hesitate to reach out with any further information or questions you may have.

**Comment by Zalways** [comment]
@glenn-jocher  thank you very much, by the way,the model i want to export is based deformable detr,not yolo.
all the details is in the 
[Details of problem I met.docx](https://github.com/ultralytics/yolov5/files/12317995/Details.of.problem.I.met.docx)
,and i'm sure all the input image has been processed correctlly,and the code i used for exporting model is official code in [https://github.com/facebookresearch/detectron2/blob/main/tools/deploy/export_model.py](url),and the code can export the demo:maskrcnn correctlly,and can inference on different images, but when it comes to my model,it only works on the image i used for exporting the model. i tried to find help from detectron2,but no one answers me.

**Comment by glenn-jocher** [comment]
@Zalways I appreciate the additional details and apologize for any confusion. Given that your model is based on Deformable DETR and not YOLO, it's important to ensure that the Deformable DETR model is correctly exported and able to handle inference on different images.

Having examined the provided documentation and your insights, it's evident that the issue is specifically related to your Deformable DETR model's export and inference behavior on different images.

Regarding your usage of the official code for exporting the model and the successful inference on the example image but not on other images, I recommend reaching out directly to the Deformable DETR community for support or posting your question on platforms where Deformable DETR developers and users actively engage.

I understand the frustration of not receiving assistance, and I'm here to extend my support as best as I can. If there are any specific ways I can help within the realm of YOLOv5 or general model conversion processes, please feel free to let me know.

I wish you success in resolving the issue with your Deformable DETR model and hope you find the support needed to address this challenge effectively.
