### ISSUE TITLE
Albumentation during training

### ISSUE THREAD

**Issue by myasser63** [ultralytics/yolov5#9175]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is albumentation always used as during training I see this:

`albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))`

in https://github.com/myasser63/yolov5/blob/946a392687780a75f058994023d51902e9a9d27d/train.py#L185
` augment=True` activates `Albumentation()`, is that correct?

**Comment by glenn-jocher** [comment]
@myasser63 albumentations is used when albumentations installation is found.
