### ISSUE TITLE
Does training YOLOV5 with segmentation data(Polygon annotation) improve the accuracy and reduce false positives ?

### ISSUE THREAD

**Issue by SanjayGhanagiri** [ultralytics/yolov5#9182]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I had trained a 10 object model with 10 images per object, as suggested on official Ultralytics and found very good accuracy.

For a larger dataset with 100 classes even after training for 500 Epocs, I have faced lot of false positives.

Recently i wanted to test a smaller model with 5 classes only with segmentation data, and found the model performed poorly even after 100 Epocs.

Does training with segmentation data improve model accuracy and reduce false positives ?

I have trained as suggested here : https://github.com/hukaixuan19970627/yolov5_obb.git

### Additional

https://github.com/hukaixuan19970627/yolov5_obb.git

**Comment by glenn-jocher** [comment]
@SanjayGhanagiri segmentation support is coming with v6.3 scheduled for September. See https://github.com/ultralytics/yolov5/pull/9052

**Comment by SanjayGhanagiri** [comment]
@glenn-jocher Segmentation looks very promising, we are working on using it to solve problems in the retails space.

Closing this ticket as segmentation is now available.

**Comment by glenn-jocher** [comment]
@SanjayGhanagiri great, enjoy! Let us know if you have any issues with it.
