### ISSUE TITLE
Training stops with out of memory with only 3 gb of dataset when caching is enabled.

### ISSUE THREAD

**Issue by SanjayGhanagiri** [ultralytics/yolov5#9183]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Total dataset size for training, valid and test is 3GB with 58 thousand files, but Yolo is caching more than 30gb and runs out of memory and training stops. Does Yolo resize the images and cache ? Is there an option we can use the source images as they are provided ?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by barney2074** [comment]
From train.py
![image](https://user-images.githubusercontent.com/25944617/187108971-b6fa7d43-13eb-4252-9e16-c31a585de30a.png)

**Comment by glenn-jocher** [comment]
@barney2074 thanks for reaching out! 

To conserve memory, YOLOv5 resizes images during training by default. If you'd like to utilize the original images without resizing, you can disable caching in the training script or resize the images beforehand. This can be achieved via the `--nosave` flag in the training script or by resizing the images externally.

Let me know if you have further questions or if there's anything else I can assist you with!
