### ISSUE TITLE
Precision is low,but recall and mAP@.5 and mAP@.5:.95 is high，why?

### ISSUE THREAD

**Issue by dapsjj** [ultralytics/yolov5#919]
I use this command to test my model :
`python test.py  --batch-size 8  --data ./data/mymodel.yaml  --weights weights/my_best.pt `
The output on console is:  
                         

-  Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|███████████████████████████████████████████████████████
- ████████████████████| 470/470 [00:39<00:00, 12.04it/s]
-                  all    3.76e+03    7.87e+03        0.79       0.938       0.939       0.849
-                   C1    3.76e+03         444       0.825       0.921       0.936       0.863
-                   C2    3.76e+03         453       0.801       0.927       0.935       0.851
-                   C3    3.76e+03         684       0.817        0.94       0.948        0.76
-                   C4    3.76e+03         192       0.585       0.885       0.849       0.706
-                   C5    3.76e+03    2.27e+03       0.688       0.957        0.93       0.819
-                   C6    3.76e+03         206       0.798       0.898       0.911       0.831
-                   C7    3.76e+03         536       0.746       0.944       0.941       0.825
-                   C8    3.76e+03         539         0.8       0.954       0.958        0.88
-                   C9    3.76e+03         361        0.84       0.953       0.969       0.897
-                  C10    3.76e+03     1.6e+03       0.774       0.914        0.93       0.798
-                  C11    3.76e+03         361       0.806        0.97       0.965       0.939
-                  C12    3.76e+03         134       0.838       0.948       0.943       0.894
-                  C13    3.76e+03          86        0.95       0.977       0.994       0.973

The precision is low,but recall and mAP@.5 and mAP@.5:.95 is high，why?

Which metrics should I use to judge the model is good or bad?

**Comment by NanoCode012** [comment]
I use mAP as my metric to judge.

**Comment by buimanhlinh96** [comment]
I face a same problem with your question. The precision is low and recall is high, so it predict a lot of false positive case. Can you have any solution? My solution is just analyst error and put these false positive image into dataset but it may cause overfitting

**Comment by buimanhlinh96** [comment]
@NanoCode012 Because yolov5 doesnt have any paper, but compare to yolov4 i see that yolov4 use label smoothing which can imporve precison. 
[https://github.com/OpenNMT/OpenNMT-py/blob/e8622eb5c6117269bb3accd8eb6f66282b5e67d9/onmt/utils/loss.py#L186](url)
