### ISSUE TITLE
number of bounding boxes versus --imgs param

### ISSUE THREAD

**Issue by Ludaman** [ultralytics/yolov5#9190]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Does the number of bounding box predictions change with the --imgs parameter?  ie, if I send in a larger image, then the feature map which reaches the detect nodes will be larger since they are all convolution nodes, hence more predictions.  

I tried to read through the detect class within common.py but was having difficulty understanding that and I was getting confused with all the webpages insisting on 25200 boxes from 13x13 grids without communicating their math or dependency on  image size.

NOTE: I know/expect that there is a trade off for speed and accuracy with increasing the image size and that the increased image size usage on a network trained at a different size will cause the features/anchor boxes to not behave well due to them being restricted to the pixel size they were trained at.

**Comment by glenn-jocher** [comment]
@Ludaman yes anchor count scales with image size
