### ISSUE TITLE
RuntimeError: PytorchStreamReaderfailed readingzip archive: not a ZIP archive

### ISSUE THREAD

**Issue by TDVL** [ultralytics/yolov5#9193]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

![Screenshot from 2022-08-28 23-51-45](https://user-images.githubusercontent.com/47524135/187177905-ffab2eac-901e-4896-b60c-9e0bde39c66f.png)

### Environment

yolov5:
git clone https://github.com/ultralytics/yolov5  # clone
cd yolov5
pip install -r requirements.txt  # install

Python 3.8.10.
Ubuntu 20.04.4 VirtualBox virtual machine

### Minimal Reproducible Example

python3 detect.py --weights best.pt --conf 0.25 --source ../yolov5/data/images/test.png

### Additional

Hello,
First, I need to declare that your yolov5 tutorial and network are great and they are very helpful for research.
However, I have a problem, I hope it is not a major problem at it can be solved easily.

I have trained your yolov5 in Google Colab and I have saved the best.pt file. Also, I have tested the trained network with best.pt weights with my test images according to the directions from the Colab tutorial with detect.py file in section 1 from the website, and it worked great. https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

Yesterday I have cloned and installed the yolov5 on Ubuntu 20.04 VirtualBox virtual machine with all requirements according to the directions from the website https://github.com/ultralytics/yolov5.
It is working great when I use your weights (yolov5s.pt, yolov5m.pt, yolov5l.pt, etc). However, when I put my saved weights best.pt in the yolov5 folder where the other weights are, and I run the detect.py with my test image, I have got an error from the screenshot I have attached to you. I have simply copied my saved weights, after I have saved them from Google Colab.
What could be the problem? The yolov5 works great, I think it would not work with your weights too if there was a problem.
I need to run the detection with detect.py.

All the requirements were installed well according to your tutorial.
git clone https://github.com/ultralytics/yolov5  # clone
cd yolov5
pip install -r requirements.txt  # install

Now, the problem  is with the inference with detect.py, because I have got an RuntimeError from the attached screenshot.
python3 detect.py --weights best.pt --conf 0.25 --source ../yolov5/data/images/test.png

I haven't change the detect.py.

 Also, if you tell me where (an email address), I can send you the best.pt file and some test images for further examination and problem detection. The best.pt file is about 141MB size.

What can be the problem and the solution? If I have understood the tutorials, I only need to copy the saved best.pt weights in yolov5 folder and later I need to name them in the Python call for detection task.

Thank you in advance.

This is the screenshot where the yolov5 works great with your weights.
![test with yolov5 weights from website](https://user-images.githubusercontent.com/47524135/187182594-8e250ad8-f625-462b-a490-b843596dabba.png)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by TDVL** [comment]
I have read this, but still I can't do the detection with my weights best.pt
Please, what is wrong, or  what did I wrong?

**Comment by glenn-jocher** [comment]
@TDVL your *.pt file is corrupt and has not fully downloaded.

**Comment by TDVL** [comment]
Hello Glenn,
Thank you, you are right. I have replaced it with new *.pt file.

**Comment by glenn-jocher** [comment]
You're welcome, @TDVL! Good to hear that you were able to resolve the issue. If you have any more questions or encounter any other issues, feel free to ask. Happy to help!
