### ISSUE TITLE
Why the higher the version, the lower the mAP？

### ISSUE THREAD

**Issue by zhang295498** [ultralytics/yolov5#920]
## ❔Question

Why the higher the version, the lower the mAP？
## Additional context
First，Thx for your share. what I want to ask is why the higher the version, the lower the mAP?
when using the v1.0 for my own datasets, I get 0.923mAP@0.5, 0.523mAP@0.5:0.95, but when I using v3.0, I get 0.88@mAP, 0.512mAP@0.5:0.95. why?   Looking forward to your reply～～～

**Comment by Aktcob** [comment]
maybe some tricks are not useful for ur own datasets. 

U can try every trick one by one to find out the reason.

**Comment by zhang295498** [comment]
THx，I will try！！
