### ISSUE TITLE
YOLOv5 convert to pyqt exe

### ISSUE THREAD

**Issue by gengarai** [ultralytics/yolov5#9201]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I designed an interface with the yolov5 based pyqt program and I want to run this structure with .exe extension. Can you help me?

**Comment by AyushExel** [comment]
@gengarai its a bit out of scope. This is a pyQt question. 
You need to debug/compile you application in release mode to generate OS executable, which in your case would be .exe if you're on windows
