### ISSUE TITLE
Import a custom model errors 

### ISSUE THREAD

**Issue by 195374305** [ultralytics/yolov5#9205]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### **Hello everyone：**

> I'm a rookie and just learning machine learning.
> I'm used your framework.
> 
> Thank you for answering questions, thank you very much！！！！！！！！！！！！！！！！！！！

No problem with the original format：

> model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

but Changed to Import a custom model
Importing a custom model or setting it to a file that has been downloaded locally yolov5s.pt import, both errors occur：
> model = torch.hub.load('.', 'custom','mode\yolov5s.pt', source='local')  

error picture：
![微信图片_20220829215409](https://user-images.githubusercontent.com/49637727/187221505-f5f926f6-2f2a-4464-9df8-01275a58407e.png)

### Additional
error code：
ImportError: cannot import name 'ClassificationModel' from 'models.yolo' (C:\Users\Administrator/.cache\torch\hub\ultralytics_yolov5_master\models\yolo.py)
_No response_

**Comment by glenn-jocher** [comment]
Use force_reload=True to update your Hub cache

**Comment by 195374305** [comment]
> Use force_reload=True to update your Hub cache

Thank you very much for finding the reason. I used the wrong resolution model

**Comment by glenn-jocher** [comment]
@195374305 you're welcome! Glad to hear you found the issue. If you have any more questions or need further assistance, feel free to ask. Good luck with your machine learning journey!
