### ISSUE TITLE
Support accimage

### ISSUE THREAD

**Issue by Cat7373** [ultralytics/yolov5#921]
## Motivation
acctime can greatly improve the loading speed of jpeg images. Specifically, I can reduce the time consumption by about 60% ~ 70%.

but please note that it only supports jpg, so an alternative loading scheme is still needed.

## Pitch
none

## Alternatives
none

## Additional context
none

**Comment by glenn-jocher** [comment]
@Cat7373 thanks for the suggestion. We currently support the following image formats, so any updates would require similar support.
https://github.com/ultralytics/yolov5/blob/cab36f72a852ef00e8b42d3283ba9b2fc757b17f/utils/datasets.py#L20

Note that for small to medium size datasets, you can cache all of your training and testing data to avoid any loading at all during training:
`python train.py --cache`

**Comment by Cat7373** [comment]
Can only support jpg images
--cache-images will take up a lot of memory, my current dataset of 300,000 images will burst 112G of memory

**Comment by Stirfry70** [comment]
can i have more info

 

 

Sent: Monday, September 07, 2020 at 11:05 PM
