### ISSUE TITLE
Poor detection when training on specific class of COCO dataset + custom dataset

### ISSUE THREAD

**Issue by iamdami** [ultralytics/yolov5#9220]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Issue
- Training on **specific classes of COCO dataset** only -> works!
- Training on **custom dataset** -> works!
- Training on **specific classes of COCO dataset + custom dataset** -> poorly detectable

![image](https://user-images.githubusercontent.com/50016477/187382993-ed765cae-b0d7-40df-85d9-7f135fe744bb.png)

---

### About Dataset
- Each classes has image file and label file.
- I removed overlapping images.  
- I matched the number of image files and label files.
- 1 label file per image.  
  (A label file has multiple category labels)
- All data is set to the YOLO format.

### COCO dataset  
- I extracted  5 specific classes of COCO dataset by parsing json file. 
  'person', 'bicycle', 'bus', 'motocycle', 'truck'

### Custom dataset
- Custom dataset consisted of 2 category labels.
  'car', 'plate'

### Merged dataset
- Consisted of 7 category lables.  
- All the category has different label(0, 1, ..., 6) in label file.  

---

Training on specific classes of COCO dataset and Training on custom dataset Each works fine.  
But I got poor detection when training on Merged dataset(specific classes of COCO dataset + custom dataset).

![image](https://user-images.githubusercontent.com/50016477/187385683-3d7b8946-2962-44af-bff2-5f66e1194e78.png)

Just like the image above, 
It detects well for the classes in COCO dataset, but poorly detects the classes in Custom dataset.  

---

### What I did before asking
- Resized for all the images.(set to 640)
- Adjusted the number of image datasets and label datasets to be the same.
- I thought it might be a data imbalance problem, so I trained with a similar amount of data.
=> No better results were obtained.  

It would be appreciated if someone could give me some advice.  
Thanks!

**Comment by iamdami** [comment]
And I also read the tutorials about 'Custom data' and 'Dataset'.

**Comment by glenn-jocher** [comment]
@iamdami see https://community.ultralytics.com/t/how-to-combine-weights-to-detect-from-multiple-datasets/38/55

**Comment by spacewalk01** [comment]
Did you re-label coco dataset as you combine them? You need to relabel coco images to include license plate and also re-label your custom data to include ('person', 'bicycle', 'bus', 'motocycle', 'truck', 'car') these classes:

**Comment by iamdami** [comment]
### What I did again after referencing the [link](https://community.ultralytics.com/t/how-to-combine-weights-to-detect-from-multiple-datasets/38/55)
I trained for 3 labels this time.
- Training on ['person', 'car', 'plate']
- Training on ['truck', 'car', 'plate']

What I've been doing is training with merged image file(specific label of COCO + custom data) path and the same label file(of course I relabeled the COCO label class and the custom label class). 
but I could check in the link training with different image file path(COCO, custom) and label file path.
I think this is the only difference between the way I did and the way in the link.

So I got result on this, data that is less affected by a car or plate, such as a person, can be detected well, but car and plate are not detected well in data that is affected by a car or plate, such as a truck. (It seems to be detected as a truck in many cases because the number of truck data is larger than that of car and plate.)

### Result
I extracted only the data without car and plate labels(which does not affect car and plate labels) Of the COCO person data, and then three labels were detected well When I trained 'person', 'car', and 'plate'.

![image](https://user-images.githubusercontent.com/50016477/187651820-f5456953-9505-4714-823c-6ce4ccea73b6.png)


As a result, it is shown that the data must be configured without affecting each label, or all data that can influence (truck, etc.) should be all labeled in the frame before training.

This is just my opinion, so I may be wrong, or there may be a better way!
Thanks :)

**Comment by glenn-jocher** [comment]
@iamdami thank you for sharing your findings! It seems like you've made significant progress in troubleshooting your issue. Your insights regarding the labeling and impact on detection are valuable. Creating separate datasets for distinct label categories or carefully relabeling the data could potentially improve detection. Your exploration and conclusions are important for the community, and your detailed experience may be beneficial to others facing similar challenges. Keep up the great work!
