### ISSUE TITLE
can this be done YOLOv5?

### ISSUE THREAD

**Issue by Heartful-echo** [ultralytics/yolov5#9221]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi

Can YOLOv5 detect a person in the video taken from the camera on the ceiling of the room?
Imagine that you can only see a person's head and shoulders.

**Comment by glenn-jocher** [comment]
Yes

**Comment by kazuya-uchida** [comment]
@glenn-jocher 

Thank you!
How high above the person is it okay to position the camera on the ceiling?
There is a video taken at about 7m from the ground, but as far as I can see the video, I felt that the person was small. Can this still detect people?

**Comment by barney2074** [comment]
It's impossible to say

It all depends on the quality and quantity of your training data- so while very small objects relative to the image size may be difficult to detect- it is best to give it a try & see what happens

**Comment by kazuya-uchida** [comment]
@barney2074 

Thank you!
I will analyze the video I shot with YOLOv5!
