### ISSUE TITLE
training with .pfm extension 

### ISSUE THREAD

**Issue by Yousef-Alhattab** [ultralytics/yolov5#9222]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

how to train yolov5 with pfm files?

**Comment by spacewalk01** [comment]
I found that opencv [imread](https://docs.opencv.org/4.x/d4/da8/group__imgcodecs.html) supports `pfm` files. 

You may try adding `pfm extention` to `IMG_FORMATS` list.

CODE:
https://github.com/ultralytics/yolov5/blob/5f1000a499dc8de5f9083412796324ebe091ba10/utils/dataloaders.py#L39

**Comment by spacewalk01** [comment]
created a pr : https://github.com/ultralytics/yolov5/pull/9230#issue-1356712166

**Comment by urbansound8K** [comment]
do I need to change the number of channel?
or just train as RGB images no need to change anything while training pfm only????

**Comment by spacewalk01** [comment]
Tested with [this image](http://www.pauldebevec.com/Research/HDR/PFM/), it works like 'jpg' image and you don't need to change number of channels. But in case, check your pfm shape as follows:
![image](https://user-images.githubusercontent.com/6389915/187599238-37adda9e-97f5-4e4d-a72e-b7db02eb9874.png)

**Comment by spacewalk01** [comment]
I think you don't need to change anything beside adding '`pfm`' extension to `dataloaders.py` as I suggested. When you try, let me know if it works or not. Good luck.

**Comment by glenn-jocher** [comment]
@urbansound8K good news 😃! Your original issue may now be fixed ✅ in PR #9230 by @spacewalk01. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by urbansound8K** [comment]
cloud you please open it again?

**Comment by glenn-jocher** [comment]
@spacewalk01 @urbansound8K could you try training again with PFM images after PR https://github.com/ultralytics/yolov5/pull/9230? If it doesn't work please submit another PR with a fix, thank you!
