### ISSUE TITLE
the detect.py file uses torch.backends which doesnt work for me

### ISSUE THREAD

**Issue by The-Ali-Sher** [ultralytics/yolov5#9224]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

It says 'no module named torch.backends'

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@CodingMango 

```
torch.backends
Out[3]: <module 'torch.backends' from '/Users/glennjocher/PycharmProjects/yolov5/venv/lib/python3.10/site-packages/torch/backends/__init__.py'>
```

Your torch is likely not meeting requirements, update it.
