### ISSUE TITLE
Bounding box positional correlation is learned by Yolov5?

### ISSUE THREAD

**Issue by GabrielDornelles** [ultralytics/yolov5#9229]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I've trained yolov5s to detect and classify keyboard keys. Its performance finding the boxes is amazing and it works better than other models I tried, but the problem is:

Its seems like it learned some kind of positional correlation between the keys, as when I change the keys for example Q W E to Q W K, it always predicts the third key as E, no matter which key I put there in the image, it always predicts as in the correct sequence (which of course, all my training data was).

I do plan to simply train a classifier and add it on top, but I wonder why this happens and the nature of it.

**Comment by glenn-jocher** [comment]
@GabrielDornelles this is normal CNN behavior. If you want YOLOv5 to learn keys out of order your training data must contain examples of this.

**Comment by GabrielDornelles** [comment]
So overfitting also happens by showing it the objects on the same order? And that is a classification overfitting with respect to the bounding box (which is always in the same position with the same class assigned)?

**Comment by glenn-jocher** [comment]
No, CNNs are translationally invariant, so it doesn't matter where your objects are in your image, what matters are the surroundings of the object, which are also included in the 'decision making'
