### ISSUE TITLE
Has anyone benchmarked performance on iPhones ?

### ISSUE THREAD

**Issue by ShreshthSaxena** [ultralytics/yolov5#923]
## ❔Question
Has anyone got the CoreML model running on iOS to benchmark performance. If yes please share the speed and accuracy !
If someone can instead provide steps to infer from the raw coreml model outputs, that is also appreciated.

**Comment by glenn-jocher** [comment]
@ShreshthSaxena I'm planning on posting some results soon, as we just recently released a new iDetection v7.6 on iOS featuring YOLOv5s/m/l release v2.0. All 3 models run at up to 30 FPS on an iPhone 11.
https://apps.apple.com/app/id1452689527

<img src="https://user-images.githubusercontent.com/26833433/92411881-814eb580-f0fe-11ea-9bc2-3f4c6e0331fe.jpg" width="400">
<img src="https://user-images.githubusercontent.com/26833433/92411882-81e74c00-f0fe-11ea-8b26-ba9db5ce0d7c.jpg" width="400">
<img src="https://user-images.githubusercontent.com/26833433/92411875-7c8a0180-f0fe-11ea-8293-ecc366015ede.jpg" width="400">

**Comment by ShreshthSaxena** [comment]
that's great! Can you provide guidelines on how to get the coreml model running on iOS ?
Would love to benchmark performance and compare with some other detection models on iPhones but can't find interpretations for the current outputs of exported coreml model.
