### ISSUE TITLE
How to load cfg(yaml) while classifying?

### ISSUE THREAD

**Issue by yuchen02** [ultralytics/yolov5#9235]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I read the source code of the yolov5 classification and found that there are two ways to load the model

```
with torch_distributed_zero_first(LOCAL_RANK), WorkingDirectory(ROOT):
        if Path(opt.model).is_file() or opt.model.endswith('.pt'):
            model = attempt_load(opt.model, device='cpu', fuse=False)
        elif opt.model in torchvision.models.__dict__:  # TorchVision models i.e. resnet50, efficientnet_b0
            model = torchvision.models.__dict__[opt.model](weights='IMAGENET1K_V1' if pretrained else None)
        else:
            m = hub.list('ultralytics/yolov5')  # + hub.list('pytorch/vision')  # models
            raise ModuleNotFoundError(f'--model {opt.model} not found. Available models are: \n' + '\n'.join(m))
        if isinstance(model, DetectionModel):
            LOGGER.warning("WARNING: pass YOLOv5 classifier model with '-cls' suffix, i.e. '--model yolov5s-cls.pt'")
            model = ClassificationModel(model=model, nc=nc, cutoff=opt.cutoff or 10)  # convert to classification model
        reshape_classifier_output(model, nc)  # update class count

```
Now I want to modify part of the structure, for example, I want to replace SiLU with ReLU, or modify the SPP layer. My idea is to modify the yaml file and read the cfg to load the model, but it fails. Can you provide an example of classification by cfg? Or how can I modify the structure in it?
Best wishes for you!

**Comment by glenn-jocher** [comment]
@yuchen02 classification loads models in a simplified way, just by loading existing *.pt models and either resetting them if pretrained=False or using them directly if they are classification models. If they are YOLOv5 detection models it converts them to classifciation models. 

So unfortunately there is no direct load by *.yaml as there is for detection. You could build a detection model with a custom yaml, save it, and then pass that to classify/train.py if you wanted to customize the architecture right now.

**Comment by AyushExel** [comment]
@glenn-jocher This might be another place where we can align all tasks. Yaml files inside `models/classify/*-cls.yaml`

**Comment by yuchen02** [comment]
@glenn-jocher Thank you for your prompt reply. Your idea is excellent. I'll have a try, And something like @AyushExel says might be more useful

**Comment by glenn-jocher** [comment]
@yuchen02 You're welcome! I hope the approach works out for you. And yes, collaborating and aligning tasks can definitely yield more cohesive and effective outcomes. Good luck with your experimentation!
