### ISSUE TITLE
Is there a working ROS Noetic, or ROS Melodic version of this Yolov5?

### ISSUE THREAD

**Issue by TDVL** [ultralytics/yolov5#9236]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is there a working ROS Noetic, or ROS Melodic version of this Yolov5?

I need to include yolov5 in ROS environment, I have been cloned your repository and built a ROS package according to instructuons from github, but the process is always restarting. I don't know what could be the problem. The screenshot is attached.
![Screenshot from 2022-08-31 15-28-48](https://user-images.githubusercontent.com/47524135/187699543-9c5a7d6d-3d37-4ea9-b613-8adb95d0a991.png)
The Yolov5 is working perfectly in Python3, I have tested it.
Is there a suggested working ROS yolov5 package that can I test?
Thank you in advance.

Best regards

**Comment by glenn-jocher** [comment]
@TDVL DetectionModel classes were introduced recently, your error seems to not be able to find it so you might need to update your YOLOv5 or retrain your model using latest code (unlikely) or both.

**Comment by TDVL** [comment]
Hello Glenn,
Thank you. This is the launch file. 
[launch file.docx](https://github.com/ultralytics/yolov5/files/9463855/launch.file.docx)
If the DetectionModel classes were updated, what version is compatible?

**Comment by TDVL** [comment]
Hello,
I have tried the package with an older version, I think. The process is still restarting. This is the new screenshot.
![Screenshot from 2022-08-31 20-10-50](https://user-images.githubusercontent.com/47524135/187750014-d57de258-d975-4f12-999b-04155d50f328.png)
Now, the package was cloned from here: https://github.com/raghavauppuluri13/yolov5_pytorch_ros
Previously I have used your latest yolov5 from your github site.

**Comment by AyushExel** [comment]
@TDVL If your trained weight is from the repo that you linked, it won't work as the last significant update was made in 2021.
You can either use the old fork of the repo with the weights trained on it.. Or use the latest version of yolov5 master branch and train a new model

**Comment by TDVL** [comment]
Hello Ayush,
I have trained my own network with your yolov5 in Colab two days ago, and I have saved the weights as best.pt. Hence, the model was trained with latest yolov5 master branch. Those weights were tested in Colab and on Ubuntu 20.04 with Python and it works great.
Now, I have made a ROS Noetic package according to that link with that repo, and also with your repo too. The package was built without errors both times, but the process is restarting in both versions. I have changed the launch file to, I have added the best.pt in weights path. Still, something is wrong.
Now, I am stucked. I have trained a good model with good weights.
I don't know where could be the problem. Something is not visible, I think.

**Comment by Zephyr69** [comment]
ROS1 is based on python2 and I don't think you can include yolov5 in the package like that without heavy modifications to yolov5. 

You'd better just include a node that subscribe to the camera images, convert the images to some generic format under python2, and serve them to scripts outside of ROS using some common protocol like sockets.  This way you can refrain from modifying code blocks of yolov5 (but some additions are needed for interprocess communications) and utilize all its latest features, at the cost of some negligible latency.

Use the same way to send result signals back to some publisher node in ROS to gain control.

**Comment by TDVL** [comment]
Hello Zephyr,
ROS Melodic uses Python2, but ROS Noetic uses Python3, according to the official documentation.
I have tried to use yolov5 with ROS Noetic. All the builds are OK, without errors (when I tried with Melodic, there were always some errors referring to missing modules, etc.). The screenshots are attached, and I have noted what version of yolov5 was used.
I think here is a minor error, but I cannot find where. If you provide me an email address, I could send you the code with launch files and *.xml files.
Also, can you suggest me the simple proper socket protocol that is verified for this situation with ROS Melodic? What protocol did you use for ROS Melodic?

**Comment by TDVL** [comment]
Hi Zephyr,
Can you suggest me the simple socket repository that is verified for this situation with ROS Melodic? What protocol did you use for ROS Melodic?

**Comment by glenn-jocher** [comment]
@TDVL We haven't specifically tested any socket protocol with ROS Melodic. However, you might find the Python `socket` library helpful, where you can find detailed documentation and tutorials online. It's a standard library that provides easy-to-use functions for creating sockets and communicating over a network. You can take a look at the official Python documentation or various online tutorials for reference. If you have any more questions, feel free to ask.
