### ISSUE TITLE
Adjusting Grid Size YOLOv5

### ISSUE THREAD

**Issue by alecbuetow** [ultralytics/yolov5#9239]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have found how to edit how many grid cells there are on YOLOv3 by checking the forum here, but as there is no longer a yolov3.cfg file, I would like to ask if I am doing it correctly now. My understanding is that the backbone downsizes features from the input, and this is what I should be changing.

I believe that "args", in order, are: ch_out, kernel, stride, padding. To change the output grid size from YOLO's default 7x7, to what I desire (say 13x13), I should change the stride and kernel size accordingly. Is this correct?

backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [64, 6, 2, 2]],  # 0-P1/2   
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C3, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 6, C3, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, C3, [512]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 3, C3, [1024]],
   [-1, 1, SPPF, [1024, 5]],  # 9
  ]

**Comment by glenn-jocher** [comment]
@alecbuetow yes your argument order is correct.

The backbone already has larger grids though. The P/2 for example denotes a native image divided by 2 etc. Min grid size is P5/32, i.e. at stride 32.

**Comment by alecbuetow** [comment]
So the backbone of P1/2 has a stride of size 2, and therefore would divide a 100x100 image into a 50x50 grid? Would this be able to detect 2500 (50x50) objects total if there was one in each grid cell?

**Comment by glenn-jocher** [comment]
@alecbuetow yes, that's correct. The first layer with P1/2 and 2x2 stride will create a 50x50 grid for a 100x100 input image. This means it could theoretically detect 2500 objects if there was one in each grid cell. Keep in mind that in practice, certain objects might be missed due to various factors such as object size, overlap, and detector thresholds.
