### ISSUE TITLE
how can i convert torch to darknet?

### ISSUE THREAD

**Issue by Hwijune** [ultralytics/yolov5#924]
## ❔Question
how can i convert torch to darknet?

## Additional context
hi @glenn-jocher 

The last yolov3 repository used torch to convert.

```
   $ git clone https://github.com/ultralytics/yolov3 && cd yolov3

   # convert cfg/pytorch model to darknet weights 
   $ python3  -c "from models import *; convert('cfg/yolov3-spp.cfg', 'weights/yolov3-spp.pt')"
   Success: converted 'weights/yolov3-spp.pt' to 'weights/yolov3-spp.weights'
```

how can i convert this yolov5??

It was converted to Torch -> Darknet -> caffe -> edge.

i'm always appreciate of your model

**Comment by glenn-jocher** [comment]
@Hwijune we've moved on from darknet in yolov5 to allow us greater freedom in architecture definition, so models here are not darknet compatible unfortunately. For export options please see see https://docs.ultralytics.com/yolov5/tutorials/model_export
