### ISSUE TITLE
How to see the weights of each layer from the pt file

### ISSUE THREAD

**Issue by Akihiwjy** [ultralytics/yolov5#9242]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to see the weights of each layer from the pt file？

**Comment by glenn-jocher** [comment]
@Akihiwjy you can examine the weights of each layer in a PyTorch .pt file by loading the model with `torch.load('model.pt')` and then accessing the model's state_dict with `model.state_dict()`. For more in-depth information on working with YOLOv5 and PyTorch model weights, please refer to the Ultralytics Docs at https://docs.ultralytics.com/yolov5/. Let me know if you need further assistance!
