### ISSUE TITLE
why the export onnx file only support the input tensor shape(1, 3, 640,640), but actually the input shape(1,3,448,672)?

### ISSUE THREAD

**Issue by eezhang123** [ultralytics/yolov5#9253]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

why the export onnx file only support the input tensor shape(1, 3, 640,640), but actually the input shape(1,3,448,672)?

**Comment by eezhang123** [comment]
out, train_out = model(im) if training else model(im, augment=augment, val=True) 
ipdb> im.shape
           torch.Size([32, 3, 448, 672])

**Comment by eezhang123** [comment]
I need onnx for  inference , but the onnx only surpport shape, 1,3,640,640, other shape will fail to export

**Comment by glenn-jocher** [comment]
@eezhang123 pass --dynamic during export for dynamic onnx input shapes.
