### ISSUE TITLE
Request for a paper/reference of fine-tuning

### ISSUE THREAD

**Issue by bzha5848** [ultralytics/yolov5#9254]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi there,

I've noticed that in the previous issue https://github.com/ultralytics/yolov5/issues/1314 you've mentined a graph of the accuray of freezing the layers
![image](https://user-images.githubusercontent.com/49177682/188075342-f17723df-25f8-4e0f-a805-4d864f5c9654.png)
Do you have some paper/ report or even the bibtex for a reference? Coz I might need it in my report.

Thanks so much!!

**Comment by glenn-jocher** [comment]
@bzha5848 the tutorial refers to https://wandb.ai/glenn-jocher/yolov5_tutorial_freeze/reports/Freezing-Layers-in-YOLOv5--VmlldzozMDk3NTg for the data, but if you need a citation you can refer to https://zenodo.org/badge/latestdoi/264818686

**Comment by bzha5848** [comment]
Thank you!!

**Comment by bzha5848** [comment]
> @bzha5848 the tutorial refers to https://wandb.ai/glenn-jocher/yolov5_tutorial_freeze/reports/Freezing-Layers-in-YOLOv5--VmlldzozMDk3NTg for the data, but if you need a citation you can refer to https://zenodo.org/badge/latestdoi/264818686

For the first link you provide, are we able to train the model of resnet and efficientnet using yolov5?

**Comment by glenn-jocher** [comment]
@bzha5848 resnet and efficientnet training for classification is explained in v6.2 release notes:
https://github.com/ultralytics/yolov5/releases/tag/v6.2
