### ISSUE TITLE
test_batch0_pred is not detecting anything?

### ISSUE THREAD

**Issue by amravishah** [ultralytics/yolov5#926]
## ❔Question
i have trained a custom model but test_batch0_pred.jpg keeps on giving me no detection. the original image without bounding box is returned. Can someone please help me

**Comment by iris-technology-inc** [comment]
BUMP

**Comment by glenn-jocher** [comment]
@amravishah @iris-technology-inc test_batch0_pred.jpg only runs once at epoch 0 and then once on final epoch. 

For actual test results you should run test.py directly with your trained weights.
