### ISSUE TITLE
How do i run train.py without using terminal ?

### ISSUE THREAD

**Issue by Arnaud-Saunier** [ultralytics/yolov5#9260]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,

I’m training a model with yolov5s

I want to run this command python train.py --img 640 --batch 40 epochs 100 --data dataset.yml --weights yolov5s.pt -- device 0

But i don't want to use my terminal.

I found the parse_opt, train and run functions in train.py but I don't know how to use it 

i thinks it's somrthing like this :

if __name__ == '__main__':
train(device = 0 , weights = "yolov5s.pt",batch= 40 , data =  "dataset.yml") 

But i'm not sure.

**Comment by glenn-jocher** [comment]
@Arnaud-Saunier if you mean from python then yes any python function is importable and runnable.

**Comment by Arnaud-Saunier** [comment]
Ok thanks you !

**Comment by glenn-jocher** [comment]
@Arnaud-Saunier you're welcome! If you have any more questions or need further assistance, feel free to ask. Good luck with your training!
