### ISSUE TITLE
Detect.py alternatives

### ISSUE THREAD

**Issue by amaheshwari01** [ultralytics/yolov5#9266]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, while trying to run a custom yolov5 model that I have created using the steps I am having issues with the detection of the model. I was able to use the detect.py file to run it on one image, but that is really slow as it loads the weights each time. I have also tried using the torch hub but am unsure how to use that. Could you please help?

**Comment by glenn-jocher** [comment]
@amaheshwari01 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # yolov5n - yolov5x6 official model
#                                            'custom', 'path/to/best.pt')  # custom model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
results.xyxy[0]  # im predictions (tensor)

results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie

results.pandas().xyxy[0].value_counts('name')  # class counts (pandas)
# person    2
# tie       1
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by amaheshwari01** [comment]
Hi thank you so much But i was still having issues and am unsure of what to put in the torch.hub.load line

I have tried doing this
```
import torch
path='/content/gdrive/MyDrive/DeepPlastic/Models/yolov5/yolov5-weights/weights/best.pt'
model = torch.hub.load('ultralytics/yolov5', 'yolov5s',path)  # yolov5n - yolov5x6 official model


```
but that runs the default model and not the custom one that is trained
`
import torch
path='/content/gdrive/MyDrive/DeepPlastic/Models/yolov5/yolov5-weights/weights/best.pt'
model = torch.hub.load('ultralytics/yolov5',path)  
`
if i run the above, then i get the following error
`
RuntimeError: Cannot find callable /content/gdrive/MyDrive/DeepPlastic/Models/yolov5/yolov5-weights/weights/best.pt in hubconf`

Could you please assist me and give an example of how I would do this if i have a best.pt file

**Comment by glenn-jocher** [comment]
@amaheshwari01 YOLOv5 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) tutorial I linked to above already explains this. Suggest you review.

**Comment by bit-scientist** [comment]
@amaheshwari01 , you should include `custom` in the line `model = torch.hub.load('ultralytics/yolov5', 'custom', path='path/to/best.pt')  # local model`, namely:

```
import torch
path='/content/gdrive/MyDrive/DeepPlastic/Models/yolov5/yolov5-weights/weights/best.pt'
model = torch.hub.load('ultralytics/yolov5', 'custom', path)
```
