### ISSUE TITLE
Overriding model.yaml nc=80 with nc=28

### ISSUE THREAD

**Issue by MrRizwansaeed** [ultralytics/yolov5#9267]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When I can build a custom class using pre-trained weight yolov5s, it will replace the existing class 80 by [Overriding model.yaml nc=80 with nc=28]. I'm getting on the train next to class 80. Is anyone able to fix this bug?

**Comment by glenn-jocher** [comment]
@MrRizwansaeed not a bug, it's a feature to update your model to your dataset classes.

**Comment by MrRizwansaeed** [comment]
@glenn-jocher  Basically, i can try to train over one class in yolov5 using the weight of coco dataset. When I can train using weight overriding pervious 80 class and after train model show result 1 class . problem is that I want to show 80+1 class result include pervious weight data and new train data. –

**Comment by glenn-jocher** [comment]
@MrRizwansaeed see https://community.ultralytics.com/t/how-to-combine-weights-to-detect-from-multiple-datasets
