### ISSUE TITLE
Warning: NMS time limit 0.090s exceeded

### ISSUE THREAD

**Issue by neo133** [ultralytics/yolov5#9268]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,
I am getting this warning message when I am testing my model on RTSP streams. It is not frequent but I wanted to understand why does it happen?
Could you please help?
I have trained a model on a custom dataset and have deployed it on RTSP stream.
I want to know the theoretical reason as to why this warning comes.

**Comment by triple-Mu** [comment]
When many of your output detection scores meet the first threshold, it takes a lot of time to enter the NMS algorithm. Therefore, these boxes will not continue to be evaluated after the timeout.

**Comment by neo133** [comment]
I see, thank you very much for the clarification. Could you please give any suggestion as to how I should avoid it?

**Comment by prakhar199** [comment]
@neo133 How to avoid this error NMS time limit 0.090s exceeded? Can you guide me to this ?
