### ISSUE TITLE
Predict Images from separate folders

### ISSUE THREAD

**Issue by yasersakkaf** [ultralytics/yolov5#927]
## ❔Question
When I run detect.py I can either give a folder name or a file name or multiple images from separate directories using the wild card operator "*".

I want to detect only 3 images residing in separate folders.
The problem is, I can't use wild card operators here since there are other images in the same directory too which I don't wanna infer.

Is there a way to send a list of images from various locations to be inferred?

**Comment by NanoCode012** [comment]
If it’s only 3 images, could you copy them to a single folder manually or via script?

**Comment by yasersakkaf** [comment]
@NanoCode012, Thanks for replying.
I just gave an example of 3 images.
There may be THOUSANDS of images and I cannot copy them to a temp folder for prediction since that will increase the execution time of my entire workflow.

I have found another way just now.
In **utils/datasets.py** I added a custom code snippet to pick up **n** comma separated files.
