### ISSUE TITLE
Are feature maps from backbone just three?

### ISSUE THREAD

**Issue by sarmientoj24** [ultralytics/yolov5#9270]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I was trying to implement Vision Transformer as backbone for YOLO one stage detector. However, one thing I noticed is that YOLO architectures uses only three feature maps from its backbone before it passes it to the neck architecture. Howevr, ViT like GCVit and Swin-T have 4 feature maps. How do I properly use these feature maps without loss of vital informations?

**Comment by glenn-jocher** [comment]
@sarmientoj24 use a P6 model? i.e.
https://github.com/ultralytics/yolov5/blob/master/models/hub/yolov5s6.yaml

**Comment by zcswdt** [comment]
> 
Can you configure how to implement it? I want to learn, thank you

**Comment by glenn-jocher** [comment]
@zcswdt sure, you can modify the `yolov5/models/yolo.py` file to accept more than three feature maps as input. You may also need to make changes in the `yolov5/models/common.py` file if the network head expects a corresponding change in the number of input feature maps. Feel free to explore the code and the documentation at https://docs.ultralytics.com/yolov5/ for more detailed information. Good luck with your implementation!
