### ISSUE TITLE
Exception: Can't get attribute. Cache maybe out of date, try force_reload=TRUE    -    yolov5 ROS melodic, problem with own weights best.pt

### ISSUE THREAD

**Issue by TDVL** [ultralytics/yolov5#9277]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Process has died, please see the attached screenshot.
![Screenshot from 2022-09-04 15-05-58](https://user-images.githubusercontent.com/47524135/188322197-7cf2cbeb-a59d-4548-98ef-b7d3f1b44822.png)

### Environment

yolov5
Ubuntu 18,04
Anaconda
ROS Melodic
![Screenshot from 2022-09-04 15-28-43](https://user-images.githubusercontent.com/47524135/188322222-92baae5b-b914-494a-b31f-e287e640bd76.png)

### Additional

Hello,
I have installed a repo with yolov5, Ubuntu 18.04 and ROS Melodic.
Please, see the link: https://github.com/qq44642754a/Yolov5_ros

![Screenshot from 2022-09-04 15-05-58](https://user-images.githubusercontent.com/47524135/188322290-fc9f7d5c-593b-47ff-8313-a68a9d9bbd1f.png)
I have put my weights best.pt in the weights folder, I have changed the weights name in launch filet to "best.pt". When I launch the package, there is an some model error and something related to the path, and something related to yolo.py file.
The screenshot about this error is attached too.

Please, will you check this error? I think the best.pt file is the reason for this.
I have trained the yolov5 and saved the weights few days ago in Google Colab using Ultralytics yolov5, these weights are working great in Colab and on Ubuntu too in Python.

Can the training date of the network and the best.pt file affect to yolov5 in this repo (the repo is 2 months old) and affect the yolov5 model?
I think the best.pt should not effect this, maybe some path problem is here?

Thank you in advance.
Best regards,

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by TDVL** [comment]
Hello,
Basically, does it matter if the weights are obtained with an older or a newer version of the yolov5? I did not make any modifications here to the yolov5 itself. For me, it is important that the yolov5 uses my weights to detect objects that are of interest to me. 
Is it possible that the weight change, the new best.pt file affects the whole model? In the Python version this was not a problem, I have only changed the weights name in the terminal when I have called the yolov5 object detector.
Here, I have changed the weights name in the launch file, however there is a new error (please se the screenshot from yesterday), I have tried to find this error in forums all day, but I didn't find any solution of this problem.
Please, could you suggest a solution for this?

**Comment by glenn-jocher** [comment]
@TDVL hello,

It's great to hear that you've obtained weights for YOLOv5 and are keen to use them for object detection. Typically, as long as the YOLOv5 weights haven't been modified and are compatible with the specific YOLOv5 version, they should work seamlessly.

As for the error message "Exception: Can't get attribute. Cache maybe out of date, try force_reload=TRUE," it is likely related to the caching of weights or models. You could try setting the `force_reload` parameter to `True` as the error message suggests. Also, please ensure that all paths and file references are correct in the launch file.

I encourage you to take a look at the YOLOv5 documentation for more insights on this error and regarding using custom weights: https://docs.ultralytics.com/yolov5/

In any case, if you have any further questions or require assistance with specific details, feel free to ask. We're here to help!
