### ISSUE TITLE
Canceling augmentations altogether.

### ISSUE THREAD

**Issue by sarpx** [ultralytics/yolov5#9278]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'd like to see what results in a simple training with no extra augmentations. Is there a way I can directly turn this off?
I don't want to make the parameters 0 one by one. Because I have some questions in my mind.

**Comment by glenn-jocher** [comment]
Pasa augment=False to the trainloader

**Comment by sarpx** [comment]
I've searched for parameters but I think I need to change the place below.

Thank you

```
train_loader, dataset = create_dataloader(train_path, imgsz, batch_size // WORLD_SIZE, gs, single_cls,
                                              hyp=hyp, **augment=False**, cache=opt.cache, rect=opt.rect, rank=LOCAL_RANK,
                                              workers=workers, image_weights=opt.image_weights, quad=opt.quad,
                                              prefix=colorstr('train: '))
```

**Comment by glenn-jocher** [comment]
@sarpx you can disable augmentations by passing augment=False directly to the trainloader. There's no need to modify the create_dataloader function. 😊
