### ISSUE TITLE
Incorrect extraction of label files paths

### ISSUE THREAD

**Issue by hmoravec** [ultralytics/yolov5#928]
## 🐛 Bug
In [Train Custom Data tutorial](https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data#2-create-labels) there is written:

> Each image's label file should be locatable by simply replacing `/images/*.jpg` with `/labels/*.txt` in its pathname.

However [the implementation](https://github.com/ultralytics/yolov5/blob/master/utils/datasets.py#L365) replaces all `images` substrings in the path with `labels`. Se e.g. label file path for image path `/data/images/dataset_1/images/image_1.png` is extracted as `/data/labels/dataset_1/labels/image_1.txt` instead of  `/data/images/dataset_1/labels/image_1.txt`.

However better and more flexible solution would be, if it was possible to pass the path to the label files as argument. Then it would be possible to have e.g. the label files in the same folder as images which is a common scenario (this is in fact possible now if the paths do not have any `images` substring).

**Comment by glenn-jocher** [comment]
@hmoravec thanks, good point! We've seen in the past that unfortunately the more arguments required, the more problems arise, and the more issues/bug reports that are raised from confused users. So requiring additional arguments for dataset setup ultimately leads to a worse UX in our observations.

You can actually run the tutorial without downloading any dataset, by simply cloning the repo and running `python train.py`. This will autodownload everything you need in the correct format and in the right places, which you can use as an example for how to set up your own custom data.

In your example above, I see that we can probably increase the robustness of the current method by prepending or appending directory separators to the string replacements, i.e. str.replace(os.sep + 'images' + os.sep, os.sep + 'labels' + os.sep). This might partially address this issue.

**Comment by glenn-jocher** [comment]
TODO: update images to labels string replacement to include os separators and possibly only replace last occurrences in paths.

**Comment by glenn-jocher** [comment]
Possible update.
<img width="891" alt="Screen Shot 2020-09-08 at 5 01 22 PM" src="https://user-images.githubusercontent.com/26833433/92538965-fe5c5680-f1f4-11ea-953b-839f1862fd36.png">

**Comment by hmoravec** [comment]
I think the proposed fix will still not work on the example I posted above: if there are `/images/` substrings on two places in the path, it will replace both.

Regarding the UX: if the user has already the training dataset prepared from training of other models like Yolo 3 and the label files are stored e.g. in the same folder as images, it is far easier to change the path argument than to restructure the dataset. Fortunately, with the current implementation it is at least possible to load the labels from the same folder as images if the path does not include `/images/` substring.

**Comment by glenn-jocher** [comment]
@hmoravec ah yes, that's a good trick!

I see the replace function can accept an optional 3rd argument, which replaces on the first n instances of a substring. If we set this to 1, this would only replace the first instance of /images/. This is the extent of the built-in replace() functionality without complicating the code additionally with a custom solution.

**Comment by hmoravec** [comment]
That would replace the first instance which also would not work as expected. There should be replaced the last instance of `/images/`, e.g. like this:
```
labels_substring = f"{os.sep}labels{os.sep}"
images_substring = f"{os.sep}images{os.sep}"
labels_substring.join(image_file_path.rsplit(images_substring, 1))
```

**Comment by glenn-jocher** [comment]
@hmoravec nice solution! I've implemented this fix in https://github.com/ultralytics/yolov5/commit/720645d96a487f427bd430e5a5ddf49d10ab3128

Now the default behavior is to only replace the last instance of /images/ with /labels/. This should increase robustness and help future users avoid problems. Thank you for your contributions.
