### ISSUE TITLE
how to export the classify and segment pt file to onnx？

### ISSUE THREAD

**Issue by xinsuinizhuan** [ultralytics/yolov5#9280]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

how to export the classify and segment pt file to onnx？

**Comment by glenn-jocher** [comment]
@xinsuinizhuan use export.py:
```
python export.py --weights yolov5s-cls.pt --include onnx
```
