### ISSUE TITLE
Segmenation Fault (core dumped on jetson nano)

### ISSUE THREAD

**Issue by amaheshwari01** [ultralytics/yolov5#9281]
HI, I am trying to run the yolov5 model on a jetson nano I have followed all the steps in the quick start guide, but when I run the file wich contains 
```
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5n - yolov5x6, custom

# Images
img = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, PIL, OpenCV, numpy, list

# Inference
results = model(img)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
```
the follwing is printed into the terminal

```
Using cache found in/home/jetson/.cache/torch/hub/ultralytics_yolov5_master
Segmentation fault (core dumped)
```

this occurs when the line 
`model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5n - yolov5x6, custom`
is run

**Comment by glenn-jocher** [comment]
@amaheshwari01 hi there! Thanks for reaching out. 😊 

The "Segmentation fault (core dumped)" error may be related to compatibility or resource issues on your Jetson Nano. Make sure you're using the CV-optimized YOLOv5 models by replacing 'yolov5s' with 'yolov5s6' and try again. If the issue persists, it might be worth checking if your system meets the necessary requirements and if there are any memory constraints causing the crash. Finally, I recommend checking out the YOLOv5 documentation for specific instructions on running the model on Jetson Nano. 

Let me know how it goes!
