### ISSUE TITLE
I found the new model for segmentation on your YOLOv5. How can I use the New YOLOv5 Segmentation Models?

### ISSUE THREAD

**Issue by star4s** [ultralytics/yolov5#9285]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I would like to use the New YOLOv5 Segmentation Models. How can I use the the new model for segmentation on your YOLOv5?
Could you explain the using method for the new model for segmentation on your YOLOv5?

Thank you for your attention.

**Comment by glenn-jocher** [comment]
@star4s segmentation models have been uploaded just for testing purposes, there will be a wider rollout in the future with super easy to use instruction.
