### ISSUE TITLE
Train custom class with out retrain COCO dataset and result embed two class in single weight .

### ISSUE THREAD

**Issue by MrRizwansaeed** [ultralytics/yolov5#9289]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

It is a request to you to add a function. Train a custom class using the yolov5s.pt weight without retraining the COCO dataset. And immediately integrate custom class in yolov5s weight. When a user uses best.pt weight, the results of all classes are embedded in best.pt. Then they can easily recognize the coco data label and custom class label in a single model without ensemble models A and B.
Many thanks for considering my request.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@MrRizwansaeed yes this is a common request, but unfortunately it's not possible to train a model on new data without it forgetting the old data. All available neurons and resources are dedicated to learning the new data, and even without any loss weight decay will ensure that unused connections trend towards zero weight.

For guidelines on training on multiple datasets simultaneously see https://community.ultralytics.com/t/how-to-combine-weights-to-detect-from-multiple-datasets
