### ISSUE TITLE
Is it possible to avoid pytorch hub for inference?

### ISSUE THREAD

**Issue by justlike-prog** [ultralytics/yolov5#9291]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I would like to load a model trained with YOLOv5 directly through torch.load without using pytorch hub. As far as I understand the .pt models are not vanilla pytorch, but are constructed in a certain way. I would like to avoid importing/caching the yolov5 repo. Is there any way to achieve this?

**Comment by glenn-jocher** [comment]
@justlike-prog 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # yolov5n - yolov5x6 official model
#                                            'custom', 'path/to/best.pt')  # custom model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
results.xyxy[0]  # im predictions (tensor)

results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie

results.pandas().xyxy[0].value_counts('name')  # class counts (pandas)
# person    2
# tie       1
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by justlike-prog** [comment]
@glenn-jocher That doesnt answer my question, because you are using pytorch hub in your example.

**Comment by glenn-jocher** [comment]
@justlike-prog My apologies for the confusion. To load a YOLOv5 model directly using `torch.load`, you can download the `.pt` model file from the [YOLOv5 Releases](https://github.com/ultralytics/yolov5/releases) page or export a custom trained model using the instructions [here](https://docs.ultralytics.com/yolov5/tutorials/model_export). Once you have the `.pt` file, you can use `torch.load` to load the model without relying on PyTorch Hub.

Here's an example of loading a YOLOv5 model using `torch.load`:
```python
import torch

# Load model
model = torch.load('path/to/best.pt', map_location='cpu')['model'].float()  # Load with map_location if GPU not available

# Set model to evaluation mode
model.eval()

# Perform inference
output = model(image_data)  # Replace image_data with your input image or tensor
```
Feel free to let me know if you have further questions or concerns!
