### ISSUE TITLE
Unable use various activation functions like HarSwish, Mish, Aconc, MetaAcocnc....

### ISSUE THREAD

**Issue by PraveenMNaik** [ultralytics/yolov5#9299]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Unable use various activation functions like HarSwish, Mish, Aconc, MetaAcocnc.... 
https://github.com/ultralytics/yolov5/blob/1aea74cddbc78e7f79dac07090cb157dfc24dbcc/models/common.py#L38
I have modified the code replacing SiLu
self.act = nn.SiLU() if act is True else (act if isinstance(act, nn.Module) else nn.Identity())
with
self.act = Mish() if act is True else (act if isinstance(act, nn.Module) else nn.Identity()) etc...
gives the error the "NameError: name 'Mish' is not defined....

**Comment by glenn-jocher** [comment]
You might want to start at the beginning if you don't understand imports instead of asking people to fix things that aren't broken: https://realpython.com/python-import/

**Comment by PraveenMNaik** [comment]
@glenn-jocher ...but sir however the code runs for other activation functions like Leaky Rely, ReLu,  but not for others?

**Comment by glenn-jocher** [comment]
`nn` has been imported earlier. Python requires module imports if you want to use the modules.
