### ISSUE TITLE
I use two detect heads and one detect head in yolov5s.yaml for training (without changing other parameters), the best.pt model size is the same?

### ISSUE THREAD

**Issue by fsfing** [ultralytics/yolov5#9300]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello everyone, recently I am doing a training comparison task.
①
anchors:
[10,13, 16,30, 33,23]  # P3/8
head:
  [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, C3, [512, False]],  # 13

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, C3, [256, False]],  # 17 (P3/8-small)

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 14], 1, Concat, [1]],  # cat head P4
   [-1, 3, C3, [512, False]],  # 20 (P4/16-medium)

   [-1, 1, Conv, [512, 3, 2]],
   [[-1, 10], 1, Concat, [1]],  # cat head P5
   [-1, 3, C3, [1024, False]],  # 23 (P5/32-large)

   [[17], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
  ]
②
anchors:
[10,13, 16,30, 33,23]  # P3/8
[116,90, 156,198, 373,326]  # P5/32
head:
  [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, C3, [512, False]],  # 13

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, C3, [256, False]],  # 17 (P3/8-small)

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 14], 1, Concat, [1]],  # cat head P4
   [-1, 3, C3, [512, False]],  # 20 (P4/16-medium)

   [-1, 1, Conv, [512, 3, 2]],
   [[-1, 10], 1, Concat, [1]],  # cat head P5
   [-1, 3, C3, [1024, False]],  # 23 (P5/32-large)

   [[17， 23], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
  ]

I use two detect heads and one detect head in yolov5s.yaml for training (without changing other parameters), the best.pt model size is the same?
Hope to get your help.
![issue](https://user-images.githubusercontent.com/57214227/188602127-37abe472-9afb-40dd-baea-98bbafabf0aa.jpg)

**Comment by glenn-jocher** [comment]
@fsfing hey there! Thanks for reaching out. The model size is expected to remain largely the same regardless of the number of detect heads due to limited parameter changes. Learn more about model optimization at our [Ultralytics Docs](https://docs.ultralytics.com/yolov5/). Happy training!
