### ISSUE TITLE
How to get bounding box coordinates from YOLOv5 onnx inference predictions?

### ISSUE THREAD

**Issue by Bombex** [ultralytics/yolov5#9308]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I convert pt file to onnx and write this inference. How I can get bounding box coordinates? It is return (1, 25200, 85) dimension array.

```
class YOLOv5ONNX:
    def __init__(self, model_file: str, device: str = "cpu"):
        providers = [("CPUExecutionProvider")]

        self.onnx_session = onnxruntime.InferenceSession(
            model_file, providers=providers
        )

    def __preprocess(self, image: np.ndarray):
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        image = cv2.resize(image, (640, 640))
        image = image.astype(np.float32) / 255.0
        image = np.transpose(image, axes=(2, 0, 1))
        image = np.expand_dims(image, 0)
        
        return image

    def __call__(self, image: np.ndarray):
        work_image = self.__preprocess(image)
        result = self.onnx_session.run(
            None, {self.onnx_session.get_inputs()[0].name: work_image}
        )
        return result
```

output:
array([[[4.5261822e+00, 2.7425523e+00, 9.7200718e+00, ...,
         9.5288157e-03, 9.8338723e-04, 5.6156218e-03],
        [1.3254605e+01, 2.5903249e+00, 2.6870312e+01, ...,
         1.1539519e-02, 1.0471046e-03, 6.3659251e-03],
        [1.8767479e+01, 3.1286464e+00, 3.1579760e+01, ...,
         1.2718022e-02, 1.1093318e-03, 7.6564252e-03],
        ...,
        [5.6003070e+02, 6.0706415e+02, 1.6039885e+02, ...,
         2.1209419e-03, 9.0771914e-04, 1.2126863e-03],
        [5.9139417e+02, 6.0587555e+02, 1.2103003e+02, ...,
         2.1493435e-03, 8.9728832e-04, 1.0625124e-03],
        [6.2399573e+02, 6.1412787e+02, 1.5570421e+02, ...,
         2.0709932e-03, 9.1317296e-04, 1.1343360e-03]]], dtype=float32)

**Comment by glenn-jocher** [comment]
@Bombex 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. This can be used with PyTorch, ONNX and any other YOLOv5 format.

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # yolov5n - yolov5x6 official model
#                                            'custom', 'path/to/best.pt')  # custom model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
results.xyxy[0]  # im predictions (tensor)

results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie

results.pandas().xyxy[0].value_counts('name')  # class counts (pandas)
# person    2
# tie       1
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by Bombex** [comment]
> @Bombex 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. This can be used with PyTorch, ONNX and any other YOLOv5 format.
> 
> ### Simple Inference Example
> This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.
> 
> ```python
> import =
> 
> # Model
> model = torch.hub.load('ultralytics/yolov5', 'yolov5s') # yolov5n - yolov5x6 official model
> # 'custom', 'path/to/best.pt') # custom model
> 
> # Images
> im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list
> 
> # Inference
>   = model (im)
> 
> # Results
> results.print() # or .show(), .save(), .crop(), .pandas(), etc.
> results.xyxy [0] # im predictions (tensor)
> 
> results.pandas().xyxy [0] # im predictions (pandas)
> # xmin ymin xmax ymax confidence class name
> # 0 749.50 43.50 1148.0 704.5 0.874023 0 person
> # 2 114.75 195.75 1095.0 708.0 0.624512 0 person
> # 3 986.00 304.00 1028.0 420.0 0.286865 27 tie
> 
> results.pandas().xyxy[0].value_counts('name') # class counts (pandas)
> # person 2
> # tie 1
> ```
> 
> <img alt="" width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">
> 
> See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.
> 
> Good luck 🍀 and let us know if you have any other questions!

Can I inference without torch.hub?

**Comment by Mahdi-Maaref** [comment]
> > @Bombex wave Hello! Thanks for asking about **handling inference results**. YOLOv5 rocket [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. This can be used with PyTorch, ONNX and any other YOLOv5 format.
> > ### Simple Inference Example
> > This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.
> > ```python
> > import =
> > 
> > # Model
> > model = torch.hub.load('ultralytics/yolov5', 'yolov5s') # yolov5n - yolov5x6 official model
> > # 'custom', 'path/to/best.pt') # custom model
> > 
> > # Images
> > im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list
> > 
> > # Inference
> >   = model (im)
> > 
> > # Results
> > results.print() # or .show(), .save(), .crop(), .pandas(), etc.
> > results.xyxy [0] # im predictions (tensor)
> > 
> > results.pandas().xyxy [0] # im predictions (pandas)
> > # xmin ymin xmax ymax confidence class name
> > # 0 749.50 43.50 1148.0 704.5 0.874023 0 person
> > # 2 114.75 195.75 1095.0 708.0 0.624512 0 person
> > # 3 986.00 304.00 1028.0 420.0 0.286865 27 tie
> > 
> > results.pandas().xyxy[0].value_counts('name') # class counts (pandas)
> > # person 2
> > # tie 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="" width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">
> > See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.
> > Good luck four_leaf_clover and let us know if you have any other questions!
> 
> Can I inference without torch.hub?

bro did you do that ? i have same problem as you and stiil cant solve it

**Comment by glenn-jocher** [comment]
@2022Mahdi yes, you can perform inference without using `torch.hub`. YOLOv5 provides options to load models using different methods such as directly loading a saved PyTorch model, loading an ONNX model, or using other YOLOv5 formats like TensorRT, TensorFlow, or OpenVINO. 

Here is an example of how to perform inference using a saved PyTorch model:

```python
import torch
from models.common import load_model

# Load the model
model = load_model('path/to/your/model.pt')

# Set the model to evaluation mode
model.eval()

# Load and preprocess the image
image = torch.randn(1, 3, 640, 640)  # Replace with your own image

# Perform inference
with torch.no_grad():
    output = model(image)

# Process the output as per your requirement
...
```

Make sure to replace `'path/to/your/model.pt'` with the actual path to your saved PyTorch model file.

I hope this helps! Let me know if you have any other questions.
