### ISSUE TITLE
val.py exists a bug.

### ISSUE THREAD

**Issue by wfs123456** [ultralytics/yolov5#9314]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Validation

### Bug

parser.add_argument('--conf-thres', type=float, default=0.3, help='confidence threshold')
out = non_max_suppression(out, conf_thres, iou_thres, labels=lb, multi_label=True, agnostic=single_cls)

In validation,  for one image, i set --conf-thres 0.01 and 0.3, the shape of out after non_max_suppression corresponds to 1 x35 x 6 (containing some error bboxes) and 1x7x6 (expected results). This demenstrates the non_max_suppression is efficial, but the ap0.5 and ap_ave in console is qual. That is why.

![x86_val_conf0 3](https://user-images.githubusercontent.com/52421834/188778988-4b8717cc-4981-4f8f-ab62-046cfcddf72d.png)
![x86_val_conf0 01_](https://user-images.githubusercontent.com/52421834/188779974-4e923d83-0350-4f9c-be5b-ff1e101f0f69.jpg)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@wfs123456 hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by FYM1209** [comment]
你好 我想问下 为什么我运行完val.py 只显示  “all class”，不像您一样 每个类别都显示
![3c946c676558dd26d2cc60a39e92a11](https://user-images.githubusercontent.com/93715148/189305076-9298ebc6-5444-49d1-94a8-a15338e3fdd1.png)
还有这样子
![2288ba7b763f772204aa855ba6ab69f](https://user-images.githubusercontent.com/93715148/189305234-bef54e0a-49f3-4c49-9f05-ce1cf7e3a456.png)
@wfs123456
