### ISSUE TITLE
reducing confidence threshold improves accuracy on VisDrone 

### ISSUE THREAD

**Issue by twangnh** [ultralytics/yolov5#9322]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi I have tried training and evaluating on the VisDrone dataset, I did not modify any of the code, just use the default settings and config, but after training a model, when doing evaluation, I find incresing the conf-thres could improve the evaluation result signficantly, e.g., with the default 0.001 confidence threshold, the mAP is 21.9, when the confidence threshold is increased to 0.05, mAP is 23.7, then when conf is 0.25, mAP is 29.7, then when conf is 0.35, mAP is 31.1.

**Comment by glenn-jocher** [comment]
Invalid

https://github.com/ultralytics/yolov5/blob/5a134e06530a8c24fdb9774c2c4ab0b513b08260/val.py#L366-L367
