### ISSUE TITLE
Whether segment uses labelme conversion

### ISSUE THREAD

**Issue by monkeycc** [ultralytics/yolov5#9324]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

YOLOv5n-seg.pt and COCO128-seg dataset

COCO128-seg
https://github.com/ultralytics/COCO2YOLO
`https://github.com/ultralytics/JSON2YOLO/blob/master/labelbox_json2yolo.py
`
It fails to work well

Whether segment uses labelme conversion
```
1.jpg
1.json
2.jpg
2.json

```
`labelme_segment2yolo.py`
`python labelme_segment2yolo.py--input D:\xxxx  --output D:\xxxx_yolo`

**Comment by glenn-jocher** [comment]
@monkeycc you can validate segment mAP easily with segmentation PR, usage instructions in segment/val.py
