### ISSUE TITLE
how to merge or add LSTM or Pose Detector to Yolov5

### ISSUE THREAD

**Issue by moahaimen** [ultralytics/yolov5#9327]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hi
@glenn-jocher 
I am terribly sorry for too many questions but I need urgent help 
I asked before 2 months and I ask again because I failed in doing that I wish really to get any help, please it is so difficult for me, I am almost only 4 months working in deep learning and python and object detection and Yolov5
I did the following
A- I trained LSTM with a lot of short videos for certain human actions it was good and I got very good results 
B- I made a human pose detection with a media pipe 

I need to merge LSTM and pose Detector with Yolo so it does the following 
1- detect objects
2- recognize human action
3- take a certain human pose and gives an alarm to do that

if possible i need to make  a single model to do that or please give me any ideas to make a pipeline to do that 

so please if you can help me I would appreciate that
what I need is to merge Yolov5 with LSTM to make both human Action Recognition and mediapipe 
to give me better results

**Comment by glenn-jocher** [comment]
@moahaimen thank you for your feedback. We have pose, keypoint detection and tracking in our roadmap over the next few months. If you require solutions now then you'd have to build something custom yourself.

**Comment by moahaimen** [comment]
> @moahaimen thank you for your feedback. We have pose, keypoint detection and tracking in our roadmap over the next few months. If you require solutions now then you'd have to build something custom yourself.

How please advise me how to do that which human pose model is better and how to do it with yolo
