### ISSUE TITLE
Autoanchor leads to box in box for one single target

### ISSUE THREAD

**Issue by liuchangji** [ultralytics/yolov5#933]
## Additional context
When I used autoanchor to train yolov5s in VisdroneDatasets then I detect , I met a problem of box in box in one target.
Did I do something wrong?Then I close autoanchor ,this problem solved...

![Screenshot from 2020-09-09 10-28-31](https://user-images.githubusercontent.com/43487003/92548030-97887d00-f288-11ea-97cd-864d038a184a.png)
![Screenshot from 2020-09-09 10-28-38](https://user-images.githubusercontent.com/43487003/92548049-a1aa7b80-f288-11ea-870f-f23cdd84ffc0.png)

**Comment by glenn-jocher** [comment]
@liuchangji ah yes, other users have seen this before as well. This is caused by autoanchor evenly distributing the evolved anchors among the 3 output layers without regard for the grid cell receptive field size. In the visdrone dataset this is probably caused by the large output layer P5 being assigned small bounding boxes by autoanchor.

For visdrone you may want to eliminate the P5 output layer alltogethor, coupled with autoanchor, or simply use the default anchors, by preventing autoanchor from running: python train.py --noautoanchor. 

For the long term though, it looks like we need to introduce additional constraints on the autoanchor evolution so that it respects the receptive field sizes of the output layers.

**Comment by liuchangji** [comment]
@glenn-jocher Thanks for all your help!

**Comment by liuchangji** [comment]
@glenn-jocher Thanks for all your help!But I meet another problem.I delete P5 output like this 
`backbone:
  [from, number, module, args]
  [[-1, 1, Focus, [64, 3]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, BottleneckCSP, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 9, BottleneckCSP, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, BottleneckCSP, [512]],
   [-1, 1, Conv, [1024, 3, 2]], # 7-P5/32
   [-1, 1, SPP, [1024, [5, 9, 13]]],
  ]

YOLOv5 head
head:
  [[-1, 3, BottleneckCSP, [1024, False]],  # 9

   [-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, BottleneckCSP, [512, False]],  # 13

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, BottleneckCSP, [256, False]],
   [-1, 1, nn.Conv2d, [na * (nc + 5), 1, 1]],  # 18 (P3/8-small)

   [-2, 1, Conv, [256, 3, 2]],
   [[-1, 14], 1, Concat, [1]],  # cat head P4
   [-1, 3, BottleneckCSP, [512, False]],
   [-1, 1, nn.Conv2d, [na * (nc + 5), 1, 1]],  # 22 (P4/16-medium)

   [[], 1, Detect, [nc, anchors]],  # Detect(P5, P4, P3)
  ]`

It can be trained but when test bug reported

RuntimeError: Sizes of tensors must match except in dimension 2. Got 23 and 24

How can I solved it ?

**Comment by glenn-jocher** [comment]
@liuchangji your yaml shows out of date syntax. You need to update to the very latest code before doing anything else. git clone again.

In current yamls, out layers can be added or removed at will simply by changing the Detect() module inputs (and associated anchors)
https://github.com/ultralytics/yolov5/blob/720645d96a487f427bd430e5a5ddf49d10ab3128/models/yolov5s.yaml#L47

**Comment by fcakyon** [comment]
@glenn-jocher is this autoanchor behaviour handled in the latest version or should we still disable autoanchor while training on datasets like visdrone?

**Comment by glenn-jocher** [comment]
@fcakyon I would leave autoanchor to do it's thing under all circumstances. If it acts oddly or you get strange results you can always disable it with the --noautoanchor flag.
```
python train.py --noautoanchor
```
