### ISSUE TITLE
Training without category names

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#9333]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Training without category names
![image](https://user-images.githubusercontent.com/105439021/189084127-bb09757c-904d-4453-a6a3-b7bcb88c75b6.png)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Luxiangxianghy hi there! Thank you for reaching out. It looks like you are trying to train YOLOv5 without category names. To do this, you can simply remove the `class` label from your dataset as YOLOv5 does not use category names during training. Feel free to check out the Ultralytics Docs for more detailed guidance on training YOLOv5. If you have any further questions or need assistance, please feel free to ask. Happy training!
