### ISSUE TITLE
Mosaic augmentation influence on custom dataset

### ISSUE THREAD

**Issue by kbegiedza** [ultralytics/yolov5#9334]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm trying to train yolov5 on custom dataset with very similar classes: person in jacket / person in shirt.
Due to nature of mosaic, sometimes only person's legs are visible on image - therefore we're unable to categorize person correctly (jacket / shirt).

Can I tweak it with some hyper params to achieve best results for my case?

**Comment by glenn-jocher** [comment]
@kbegiedza yes of course, you can modify all hyperparameters including mosaic probability in your hyp file:
https://github.com/ultralytics/yolov5/blob/8aa196ce08007aa1033b0e42931c247e1e491321/data/hyps/hyp.scratch-low.yaml#L1-L34
