### ISSUE TITLE
Why parameters in 4 yaml models are totally same ?

### ISSUE THREAD

**Issue by michaelnguyen11** [ultralytics/yolov5#934]
Hi Authors,

Thank you for your great work.

I'm wondering why parameters in 4 yaml files under models directory are totally same ? I believe that probably layers could be same, but hyperparameters should be different on each model.

Is there anything wrong here ?

Please correct me if I'm wrong. Many thanks in advance.

Regards,
Michael

**Comment by Aktcob** [comment]
depth_multiple: 0.67  # model depth multiple
width_multiple: 0.75  # layer channel multiple

～～～～～

**Comment by michaelnguyen11** [comment]
Oh I see, thank for pointing this out.
