### ISSUE TITLE
about a result after running val.py,umm.....i do not know 

### ISSUE THREAD

**Issue by FYM1209** [ultralytics/yolov5#9343]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

i run val.py and use default parameters，but the result is this
![b385bbb8e07e086c961909f21e45463](https://user-images.githubusercontent.com/93715148/189297350-4a6b21d6-e970-46c1-b1c0-56721fce39cc.jpg)
![image](https://user-images.githubusercontent.com/93715148/189297511-2b0eb6fd-942e-4e69-bbfe-7e9e01ff7cba.png)
only have "all class"
and 
![image](https://user-images.githubusercontent.com/93715148/189297789-ec47c40c-0182-4b74-bdc0-15c2e32553f6.png)

**Comment by glenn-jocher** [comment]
You can use --verbose to display val results for all classes.

**Comment by FYM1209** [comment]
thanks a lot for your answer，is work.  umm but The F1.png in the exp folder still only shows "all class" like thisi
![image](https://user-images.githubusercontent.com/93715148/189464522-c2818b74-c518-40eb-ba8a-5aaf020b580d.png)
inlude other .png，Do I need to use other --xxxxx?

**Comment by FYM1209** [comment]
sorry to bother you again，I modified the code in some places ，like:
![image](https://user-images.githubusercontent.com/93715148/189467638-dae844bb-70a9-4793-ab33-11f934e81a92.png)
and result:
![image](https://user-images.githubusercontent.com/93715148/189467659-3c3f93a2-6982-4da3-a581-098af7651806.png)
Part of the legend is occluded，what can i do

**Comment by FYM1209** [comment]
i solved it

**Comment by glenn-jocher** [comment]
@FYM1209 glad to hear you were able to resolve the issue! If you have any other questions or encounter further challenges, feel free to reach out. Good luck with your project!
