### ISSUE TITLE
AssertionError: File not found: share/bigdata/yolov5-6.2/data/mydataset.yaml

### ISSUE THREAD

**Issue by seenthestars** [ultralytics/yolov5#9345]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

在云端jupyterlab上运行train.py报错如下：
Traceback (most recent call last):
  File "train.py", line 635, in <module>
    main(opt)
  File "train.py", line 506, in main
    check_file(opt.data), check_yaml(opt.cfg), check_yaml(opt.hyp), str(opt.weights), str(opt.project)  # checks
  File "/root/share/bigdata/yolov5-6.2/utils/general.py", line 453, in check_file
    assert len(files), f'File not found: {file}'  # assert file was found
AssertionError: File not found: share/bigdata/yolov5-6.2/data/mydataset.yaml

**Comment by glenn-jocher** [comment]
@seenthestars you've supplied an incorrect path to your dataset yaml

**Comment by Sabreen-a** [comment]
i faced this issue and i solved it by remove cache files for train and val

**Comment by glenn-jocher** [comment]
@Sabreen-a that's great to hear that you were able to find a solution to the problem you were facing. Clearing the cache files for the train and val sets is a common solution to many errors experienced during training. If you have any other questions or face any other issues, feel free to ask for help.

**Comment by Sabreen-a** [comment]
I faced issues and I cannot know how can I solve it my code is as following
MLContext mlContext = new MLContext();
var schema = SchemaDefinition.Create<ImageInputData>();
schema
    .AddColumn(nameof(ImageInputData.Image),
               ImagePixelExtractingTransformer.ColumnInfo
                  // Define the pixel extraction column info
                  .FromColumns(nameof(ImageInputData.Image)),
               // Specify the input image size
               new
ImagePixelExtractorTransform.ImagePixelExtractorColumnOptions(
                  ImageSettings.imageWidth, ImageSettings.imageHeight,
                  nameof(ImageInputData.Image)))
    .AddColumn(nameof(ImageInputData.Label),
               // Specify the output column type
               schema.GetColumnType(nameof(ImageInputData.Label)));

var dataView = mlContext.Data.LoadFromEnumerable(new
List<ImageInputData>(), schema);

var pipeline = mlContext.Transforms.ResizeImages(resizing:
ImageResizingEstimator.ResizingKind.Fill,
                                                 outputColumnName:
"output",
                                                 imageWidth:
ImageSettings.imageWidth,
                                                 imageHeight:
ImageSettings.imageHeight,
                                                 inputColumnName:
nameof(ImageInputData.Image))

.Append(mlContext.Transforms.ExtractPixels(outputColumnName: "output"))
                .Append(mlContext.Transforms.ApplyOnnxModel(modelFile:
onnxFile,

outputColumnName: "output",

inputColumnName: "images"));

var model = pipeline.Fit(dataView);

Every time I run my wpf app itis through error for idataview not registered
and I cannot know how can I solve that I try to register my type to
Idataview but I cannot

في السبت، ٨ أبريل ٢٠٢٣, ٦:٠٩ ص Glenn Jocher ***@***.***> كتب:

**Comment by glenn-jocher** [comment]
@Sabreen-a, the `IDataView` interface is defined in the `Microsoft.ML` namespace, so you should make sure that you import this namespace at the top of your file. If you have already done this, you may want to check your dependencies and make sure they are up to date. If you are still experiencing issues, please provide more details about the specific error message you are receiving and any other relevant context. I hope this helps!
