### ISSUE TITLE
Change the name of the classes of an already trained model

### ISSUE THREAD

**Issue by maximereder** [ultralytics/yolov5#9348]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, 
However I made a mistake when assigning names in data.yaml during training. 

The model makes good predictions, I just want to change the id names. 

So I changed the name of the classes in data.yaml. 

When I run the command : python detect.py --weights best.pt --img 640 --conf 0.25 --source image.jpeg --data data.yaml

The names remain unchanged, while I do specify the new --data data.yaml.

How to change the names without dragging the model again?

My data.yaml

```train: /data/train/images
val: /data/valid/images

nc: 6
names:
 0: Car
 1: Person
 2: Tank
 3: Truck
 4: Weapon
 5: Military
```

**Comment by glenn-jocher** [comment]
@maximereder data yaml names are only used if a model lacks names. Since your model has names the data yaml is ignored. 

You can define model.names = ['a', 'b', ...] manually inside detect.py if you want to.
