### ISSUE TITLE
pretrained checkpoints of v1.0

### ISSUE THREAD

**Issue by zhangkui669** [ultralytics/yolov5#935]
checkpoints on google drive have been updated to v3.0，so where can i found pretrained weights to match source code of v1.0?

**Comment by glenn-jocher** [comment]
Each release includes associated weights:
https://github.com/ultralytics/yolov5/releases/tag/v1.0

I would recommend using the latest weights with the latest master code.

**Comment by zhangkui669** [comment]
> Each release includes associated weights:
> https://github.com/ultralytics/yolov5/releases/tag/v1.0
> 
> I would recommend using the latest weights with the latest master code.

the associated weights linked to same download url..

**Comment by glenn-jocher** [comment]
<img width="668" alt="Screen Shot 2020-09-09 at 12 57 21 AM" src="https://user-images.githubusercontent.com/26833433/92571174-a266f180-f237-11ea-8963-9e02366396df.png">

**Comment by zhangkui669** [comment]
I saw it, when I use my own data, I found the performance of v2.0 is worse than v1.0, so I still use v1.0
