### ISSUE TITLE
config for resnet and mobilenet

### ISSUE THREAD

**Issue by bzha5848** [ultralytics/yolov5#9350]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Hi there,

Just wondering is that possible to create config model for resnet and mobilenet like the way we have for yolov5? And we can use the new pre-trained model to fine-tuning?

Thanks so much!!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@bzha5848 you can start training from resnet and efficientnet pretrained classificaiton models easily. See README Classification section for details.
https://github.com/ultralytics/yolov5#classification--new

**Comment by bzha5848** [comment]
Yeah, but I wanna keep the backbone of resnet and efficient and fine-tuning them with the head of yolov5, will that be possible?

**Comment by glenn-jocher** [comment]
@bzha5848 yes, you can create any model by customizing a model yaml for it.

**Comment by bakikocabasa** [comment]
Dear @bzha5848 ,

did you prepare the model for the efficientnet? if yes, would you share it with me as well?

Thank you

**Comment by bakikocabasa** [comment]
Dear @glenn-jocher ,

we have weight-anymodel.yaml connections between yolov5n-s-m-l-x,pt and their yaml files. However, when I want to use efficientnet.pt in train, it returns an error.

Traceback (most recent call last):
  File "train.py", line 630, in <module>
    main(opt)
  File "train.py", line 526, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 123, in train
    model = Model(cfg or ckpt['model'].yaml, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)  # create
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1208, in _getattr_
    type(self)._name_, name))
AttributeError: 'EfficientNet' object has no attribute 'yaml'

How can I overcome this issue?

**Comment by glenn-jocher** [comment]
@bakikocabasa for torchvision models we just load them directly from torchvision, so we don't have model yaml's available unfortunately:
https://github.com/ultralytics/yolov5/blob/6a9fffd19a96799c683c94d2d4da8c453e819116/classify/train.py#L111-L112
