### ISSUE TITLE
Training the datasets with VOC datasets

### ISSUE THREAD

**Issue by HaddysRosserrier** [ultralytics/yolov5#9359]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

I've ran the training sequence to see the performance of the model on my hardware. I was able get the training result with coco128 datasets. 
However, when I tried to run with VOC, I received this error:- 

python train.py --data voc.yaml --cfg yolov5s.yaml --weight '' --batch-size 1

![image](https://user-images.githubusercontent.com/36948544/189482459-25abc808-e813-464f-a43c-87000c66e341.png)

It seems like it was unable to download the VOC datasets at all. So I've tried to manually download the datasets from host.robots but it is still missing the necessary file train.txt. 

Is there any changes to the naming convention? 

Will changing it affects the benchmark? 

Looking into the forums, I've found that someone has reported this issue before, but it was replied with some other tester claiming that it works on their side. Seems like the issue still persists. 

Thank you in advance. 

### Minimal Reproducible Example

python train.py --data voc.yaml --cfg yolov5s.yaml --weight '' --batch-size 1

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@HaddysRosserrier thanks for the bug report! 

Is this problem reproducible in Google Colab? VOC training is working for me with the dataset automatically downloaded if missing:


python train.py —data VOC.yaml

**Comment by HaddysRosserrier** [comment]
> @HaddysRosserrier thanks for the bug report!
> 
> Is this problem reproducible in Google Colab? VOC training is working for me with the dataset automatically downloaded if missing:
> 
> python train.py —data VOC.yaml

Yes. The same dataset is missing in the Google Colab environment. 
However, the Google Colab's scripts actually performs the download (several times), which is in contrast to my own environment. 

Apparently if I run it in Google Colab it performs the download 2x, but it still runs with the missing datasets. 

Figure 1 shows missing train.txt file 

Figure 1
![Google_Colab_Yolov5_voc_run_20220911_1](https://user-images.githubusercontent.com/36948544/189507592-e61f3283-1724-46fb-9770-84787dfedf07.PNG)

Figure 2 shows it performs a 2nd download

Figure 2
![Google_Colab_Yolov5_voc_run_20220911_2](https://user-images.githubusercontent.com/36948544/189507596-e2a7f544-605f-4c1c-b235-07a1153aa9f2.PNG)


Figure 3 shows it performs the training with 7 items missing 

Figure 3 
![Google_Colab_Yolov5_voc_run_20220911_3](https://user-images.githubusercontent.com/36948544/189507610-00b0b177-111a-4b28-a989-cb06d4468445.PNG)


Thanks for the quick response~

**Comment by glenn-jocher** [comment]
@HaddysRosserrier looks like you just have internet issues. I just trained VOC correctly right now on Colab:

<img width="1503" alt="Screenshot 2022-09-11 at 19 26 07" src="https://user-images.githubusercontent.com/26833433/189538427-ae20783e-257f-473f-abf3-f5b34d225327.png">

**Comment by HaddysRosserrier** [comment]
Kinda doubt so, it seems to be looking for a non existing txt file, even if you look at the original datasets. Also it downloads the zip file and has to extract it prior to process. Unless there's an async issues, I doubt internet connection is an issue.

**Comment by glenn-jocher** [comment]
@HaddysRosserrier as you can see in my screenshot VOC training in Colab works correctly for me. 

If I’m unable to reproduce issues then there is no action for us to take.

if you can provide a reproducible issue please let us know.
