### ISSUE TITLE
Yolov5m reproduce lower mAP than yours

### ISSUE THREAD

**Issue by jingyuxin412** [ultralytics/yolov5#9364]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I used the newest docker image and try to train a Yolov5m on 4 A10 GPUs using this cmd:
`python -m torch.distributed.run --nproc_per_node 4 train.py --batch 240 --data coco.yaml --cfg yolov5m.yaml --weights '' --device 0,1,2,3`
But only got
``` 
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.41971
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.60835
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.45952
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.26193
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.47124
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.53394
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.33450
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.55372
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.60948
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.42415
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.66802
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.74968
```

I wondering what cmd can fully reproduce your results? thank you

**Comment by glenn-jocher** [comment]
@jingyuxin412 you can see training logs and commands to reproduce at https://wandb.ai/glenn-jocher/YOLOv5_v61_official

For YOLOv5m:
https://wandb.ai/glenn-jocher/YOLOv5_v61_official/runs/7zwcq3ww/overview?workspace=user-glenn-jocher

**Comment by glenn-jocher** [comment]
@jingyuxin412 for W&B commands you need to put a '' for the weights, i.e.:
```
train.py --data coco.yaml --batch 128 --weights '' --cfg yolov5m.yaml --epochs 300 --project YOLOv5_v61_official --name YOLOv5m-linear --img 640 --hyp hyp.scratch-med.yaml --linear --device 2
```

**Comment by jingyuxin412** [comment]
> 

Thank you for your reply. I will have a try

**Comment by jingyuxin412** [comment]
> @jingyuxin412 you can see training logs and commands to reproduce at https://wandb.ai/glenn-jocher/YOLOv5_v61_official
> 
> For YOLOv5m: https://wandb.ai/glenn-jocher/YOLOv5_v61_official/runs/7zwcq3ww/overview?workspace=user-glenn-jocher

Thank you for your reply. I will have a try

**Comment by glenn-jocher** [comment]
@jingyuxin412 you're welcome! If you have any other questions or need further assistance, feel free to ask. Good luck with your training!
