### ISSUE TITLE
My yolov5 can't detect video

### ISSUE THREAD

**Issue by jienow** [ultralytics/yolov5#9368]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

```
ubuntu@ubuntu:~/yolov5$ sudo python3 detect.py --source 0

/usr/local/lib/python3.8/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 
  warn(f"Failed to load image Python extension: {e}")
detect: weights=yolov5s.pt, source=0, data=data/coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False
YOLOv5 🚀 v6.2-90-g63ecce6 Python-3.8.10 torch-1.12.1 CPU

Fusing layers... 
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/usr/local/lib/python3.8/dist-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

Aborted
```

#-----------------------------------------------------------------------------------------------------------------------------

The above is my writing command, which is used to detect video using yolov5, but it is not successful. But if you want to detect pictures, he can be successful.
Also, I have used `pip install -r requirements.txt` to install the environment. I think they are the latest version.
My system is ubuntu system on Raspberry Pi 4B. I'm using ssh to connect to a raspberry pi remotely over wifi.
I have removed python2.7 and his pip, and pip is the latest version.

I think this problem is because there is no way for the machine to send the detected image to the terminal in real time, but I don't know what the command is to stop sending the detected video and save it.

#------------------------------------------------------------------------------------------------------------------------------

Please let me know if additional information is needed to solve this problem.

### Additional

I'm a non-native English speaking sophomore and have been blocked by this issue for almost a week and I'm going crazy.

**Comment by glenn-jocher** [comment]
@jienow source 0 is intended for local webcams, ie a MacBook with a built in camera. Remote terminals will not work.

**Comment by jienow** [comment]
> @jienowsource 0 用于本地网络摄像头，即带有内置摄像头的 MacBook。远程终端将无法工作。

oh oh i see. Then I want to call the camera plugged into the Raspberry Pi for video detection. Which file should I modify or which command should I call for video detection? My webcam has been detected and is ready to use.

**Comment by glenn-jocher** [comment]
@jienow --source 0 should work for connected webcams

**Comment by glenn-jocher** [comment]
detect.py uses cv2 for webcam detection, so to debug you should just try to run a simple cv2 webcam loop and verify this works first:

https://www.geeksforgeeks.org/python-opencv-capture-video-from-camera/
```python
# import the opencv library
import cv2


# define a video capture object
vid = cv2.VideoCapture(0)

while(True):
	
	# Capture the video frame
	# by frame
	ret, frame = vid.read()

	# Display the resulting frame
	cv2.imshow('frame', frame)
	
	# the 'q' button is set as the
	# quitting button you may use any
	# desired button of your choice
	if cv2.waitKey(1) & 0xFF == ord('q'):
		break

# After the loop release the cap object
vid.release()
# Destroy all the windows
cv2.destroyAllWindows()

```

**Comment by barney2074** [comment]
I think the PI will struggle to run Yolov5- the frame rate may be so low that it is unusable
I suggest either:

1. Use the PI and camera as just an RTSP server, and run the Yolv5 inferencing on a machine with more processing power
So in other words, the PI is just capturing & sending the video stream. The Yolov5 command would be:
`python detect.py --source 'rtsp://your_pi/stream'`

2. Export your Yolov5 model to tflite format, and run the inferencing on the PI- there are various tutorials on how to do this.
Depending on your model- this should perform reasonably

**Comment by jienow** [comment]
@barney2074 @glenn-jocher 

Thank you for your replies, I have found the solution to my problem, thank you for your replies

**Comment by glenn-jocher** [comment]
@jienow you're welcome! I'm glad you were able to find a solution. If you have any more questions or need further assistance in the future, feel free to ask. Good luck with your project!
