### ISSUE TITLE
The model became larger after the transfer of torchscript export

### ISSUE THREAD

**Issue by TDIT-haha** [ultralytics/yolov5#937]
## ❔Question
The original model of yolov5s was 14M, but the model changed to 29M after transformation
Shouldn't the model be the same before and after the transformation?

**Comment by zhangkui669** [comment]
> ## ❔Question
> The original model of yolov5s was 14M, but the model changed to 29M after transformation
> Shouldn't the model be the same before and after the transformation?
> 
> ## Additional context

it seems like the weights data type convert from fp32 to double

**Comment by TDIT-haha** [comment]
However, the conversion of double type is not seen in the model transformation
