### ISSUE TITLE
[Resolve] ELP Camera module doesn't work

### ISSUE THREAD

**Issue by NBarile** [ultralytics/yolov5#9370]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Hi everyone

I tried to use an ELD Camera Module (this one : https://www.amazon.fr/gp/product/B07KMZ9GHZ/ref=ask_ql_qh_dp_hza?th=1) for my custom training dataset, and it dosen't work when i try to use it with "detect.py".
I have this error :

![image](https://user-images.githubusercontent.com/48790575/189529715-d8c66529-c200-45e4-a69c-f2cd509a27a2.png)

(I use --source 1, because --source 0 is my normal webcam. )

I try to change se default imgsz setting, but it doesn't work.

So, if someone know how to resolve this problem, pls help me :D

Thanks !

And if you need more informations, please ask me ^^

### Environment

- Software : Anaconda 3.2.0
- OS : Windows 10
- Python : 3.9.7

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@NBarile detect.py uses cv2 for webcam detection, so to debug you should just try to run a simple cv2 webcam loop and verify this works first:

https://www.geeksforgeeks.org/python-opencv-capture-video-from-camera/
```python
# import the opencv library
import cv2


# define a video capture object
vid = cv2.VideoCapture(0)

while(True):
	
	# Capture the video frame
	# by frame
	ret, frame = vid.read()

	# Display the resulting frame
	cv2.imshow('frame', frame)
	
	# the 'q' button is set as the
	# quitting button you may use any
	# desired button of your choice
	if cv2.waitKey(1) & 0xFF == ord('q'):
		break

# After the loop release the cap object
vid.release()
# Destroy all the windows
cv2.destroyAllWindows()

```

**Comment by NBarile** [comment]
this doesn't work :(
![image](https://user-images.githubusercontent.com/48790575/189551466-43d5a326-05c7-49cb-a731-cf8134d7c8af.png)

**Comment by NBarile** [comment]
SO OK

It works when I set the correct FPS ... 
![image](https://user-images.githubusercontent.com/48790575/189551712-c354ded8-241a-4177-927b-065ed6f0ee73.png)

I think I probably need to change my detect.py, I'll change it later, and i will give my solution if I found.
(If you know before me how to change the code, please feel free to show me ^^)

**Comment by glenn-jocher** [comment]
@NBarile glad to hear you were able to resolve the issue by setting the correct FPS! When modifying detect.py, you can adjust the `VideoCapture` FPS parameter to match the requirements of your camera. Here's the relevant line of code:

```python
self.cap = cv2.VideoCapture(source)  # Video capture object
self.cap.set(cv2.CAP_PROP_FPS, your_desired_fps)
```

Let me know if you need further assistance. Good luck!
