### ISSUE TITLE
How long will yolov5s take for an epoch on COCO2017 dataset ?

### ISSUE THREAD

**Issue by Guo-Stone** [ultralytics/yolov5#9373]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How long will yolov5s take for an epoch on coco 2017 dataset ?

### Additional

I use 4 GPU (3090 24GB) and DDP mode to train my yolov5s on COCO2017 dataset. But it takes about 24 hours for an epoch.
On yolov5 Readme.md file, it is said that 'Training times for YOLOv5n/s/m/l/x are 1/2/4/6/8 days on a V100 GPU'. My training time is too long. Is there something wrong with me ?

**Comment by Guo-Stone** [comment]
Maybe I have changed  the source code too much. When I use the unchanged source code, it takes about 20 min / epoch on 4 NVIDIA 3090

**Comment by glenn-jocher** [comment]
@Guo-Stone yes seems correct for master code.
