### ISSUE TITLE
Should it be 'study' instead of 'benchmark' on val.py line 171 - 172 ?

### ISSUE THREAD

**Issue by Xu-Justin** [ultralytics/yolov5#9378]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

According to the description and logic of the main function, the task should be either `train`, `val`, `test`, `speed` or `study`.

- https://github.com/ultralytics/yolov5/blob/23701eac7a7b160e478ba4bbef966d0af9348251/val.py#L105
- https://github.com/ultralytics/yolov5/blob/23701eac7a7b160e478ba4bbef966d0af9348251/val.py#L340
- https://github.com/ultralytics/yolov5/blob/23701eac7a7b160e478ba4bbef966d0af9348251/val.py#L366-L393

However, on line 171 - 172, somehow the task is compared to `benchmark`. I suspect it should be `study` instead of `benchmark`.

- https://github.com/ultralytics/yolov5/blob/23701eac7a7b160e478ba4bbef966d0af9348251/val.py#L171-L172

**Comment by Xu-Justin** [comment]
[This issue has been answered here](https://github.com/ultralytics/yolov5/pull/9379#issuecomment-1248367014)

**Comment by glenn-jocher** [comment]
@Xu-Justin thanks for reaching out! You're absolutely right. The term `benchmark` should indeed be replaced with `study` at val.py line 171-172. The correction will be made in the next release. Thanks for bringing this to our attention and contributing to YOLOv5! If you have any more questions or suggestions, feel free to ask.
