### ISSUE TITLE
yolov5 on inteliij ide

### ISSUE THREAD

**Issue by sam-va** [ultralytics/yolov5#9381]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi!I have been using yolo and its quite impressive.I have been trying to move the code to intelliJ ide so that i dont need to open colab everytime.When I try executing the following code,
`import utils
import torch
model =  torch.hub.load('ultralytics/yolov5', 'custom', path=r'C:\Users\lenovo\OneDrive\Desktop\best.pt')
im = r'C:\Users\lenovo\OneDrive\Desktop\3.png'`
I get an error:

ModuleNotFoundError: No module named 'utils.dataloaders'

![image](https://user-images.githubusercontent.com/81673432/189693969-f6e16126-39fc-4496-b199-cd502a3113b3.png)

I tried uninstalling utils and reinstalling it.Nothing seems to work. Anybody got any idea on how to solve this?

**Comment by glenn-jocher** [comment]
@sam-va PyCharm works correctly for me. I'm unable to reproduce any issues:

```python
import torch

# PyTorch Hub Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5n - yolov5x6, custom

# Images
img = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, PIL, OpenCV, numpy, list

# Inference
results = model(img)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
```

<img width="1772" alt="Screenshot 2022-09-16 at 14 33 02" src="https://user-images.githubusercontent.com/26833433/190639660-0655806f-8f57-47e0-aab2-8f70f163c6cf.png">
