### ISSUE TITLE
RuntimeError: result type Float can't be cast to the desired output type long int

### ISSUE THREAD

**Issue by Swimlim** [ultralytics/yolov5#9383]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

![image](https://user-images.githubusercontent.com/105340288/189729578-927ba831-ad51-4672-817e-f47805285dad.png)
[Roboflow-Train-YOLOv5-기와테스트 카운팅테스트0913 - Colaboratory.pdf](https://github.com/ultralytics/yolov5/files/9550882/Roboflow-Train-YOLOv5-.0913.-.Colaboratory.pdf)

there was no error, but now I can't learn, and there is an error like an image.
and I tried updatd the YOLOv5, and pytorch but it doesn't work.
I don't know how to fix it. 
I am attaching the pdf file as well. Please find the problem..

**Comment by glenn-jocher** [comment]
@Swimlim this has been resolved a couple months ago, update your code.
