### ISSUE TITLE
TypeError when training with custom data

### ISSUE THREAD

**Issue by grantrosario** [ultralytics/yolov5#9384]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

Commit #9347 caused my Colab runs to start failing. They're unable to begin training due to the below type error. Conv2d is now expecting a different set of args.

![image](https://user-images.githubusercontent.com/14910481/189734811-b3298a8e-b20a-44f5-a888-167e99448b13.png)

### Environment

Google colab

YOLOv5 🚀 v6.2-109-g23701ea Python-3.7.13 torch-1.12.1+cu113 CUDA:0 (Tesla P100-PCIE-16GB, 16281MiB)

### Minimal Reproducible Example

!git clone https://github.com/ultralytics/yolov5/

%cd yolov5/

!pip install -r requirements.txt
!pip install gdown -q
!pip install ipython-autotime
!pip install ipyplot

import torch
import utils
import gdown
import yaml
import glob
import ipyplot

from utils.plots import plot_results  

display = utils.notebook_init()

%load_ext autotime
!python train.py --imgsz 416 --image-weights --device 0 --batch-size 16 --epochs 1 --data /content/data.yaml --cfg /content/data.yaml --weights /content/yolov5/models/yolov5.pt --name s400_1

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@grantrosario thanks for the bug report! 

I'm unable to reproduce an issue. I tried a related command with COCO128 training in Colab and everything works correctly with current master. 

If you use Conv() modules directly in a custom model yaml you may need to update to the new arguments however.

<img width="1335" alt="Screenshot 2022-09-16 at 00 33 03" src="https://user-images.githubusercontent.com/26833433/190520182-9ed68da7-f9da-4738-a85b-60b427763ea6.png">

**Comment by glenn-jocher** [comment]
@River-Cold thanks for the code to reproduce. I see the same error. I'll add a TODO to resolve.

**Comment by glenn-jocher** [comment]
@grantrosario good news 😃! Your original issue may now be fixed ✅ in PR #9466. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
