### ISSUE TITLE
Resizing the input images

### ISSUE THREAD

**Issue by NemioLipi** [ultralytics/yolov5#9385]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,
Thanks for sharing the code for your interesting work. I see that the size of the input images is passed as an argument to train a model (--img default value of 640). Do I have to resize all input images to a predefine size? Isn't is possible for training images to have different sizes?
Thanks

**Comment by barney2074** [comment]
No, you don't need to resize the images, YoloV5 will do this for you (based on the longest edge of the image)
As I understand it- it works with different sized images- but you probably don't want to upscale images

The choice of image size is a balance of performance vs accuracy, plus you should train and detect at the same size.
i.e don't train at 640 and detect at 3840- refer 'Tips for Best Training results'

**Comment by glenn-jocher** [comment]
@barney2074 thanks for reaching out and for your interest in our work! YOLOv5 actually handles resizing of input images for you, based on the longest edge of the image. It indeed works with different sizes, but upscaling images is typically not recommended.

The choice of image size is a trade-off between performance and accuracy. It's important to train and detect at the same size, so avoid training at one size and detecting at a drastically different size. For more detailed tips on achieving the best training results, I recommend checking out the "Tips for Best Training results" section in our documentation.

Let me know if there's anything else I can help with!
