### ISSUE TITLE
Understanding Confusion Matrix

### ISSUE THREAD

**Issue by RahaviSelvarajan** [ultralytics/yolov5#9389]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am doing a binary classification problem using YOLOv5 and the model generated a confusion matrix like the following. There is only one label throughout the dataset and I did not use any negatives in the dataset. I am not quite sure why the False Positive is 1.00. Could you please explain this?
![confusion_matrix_FT](https://user-images.githubusercontent.com/73741341/189791613-2c3ff058-7573-4e8a-9adf-895231cfeefa.png)

**Comment by glenn-jocher** [comment]
@RahaviSelvarajan columns are normalized. You can display actual number of instances by setting normalize=False here:
https://github.com/ultralytics/yolov5/blob/f9869f7ffdbce757f260d28a6b799c5fa50263ee/utils/metrics.py#L190
