### ISSUE TITLE
About the labeling of the COCO2017 data set

### ISSUE THREAD

**Issue by zhangkuncsdn** [ultralytics/yolov5#939]
## ❔Question
Hi，bro
The maximum tag id of the COCO2017 dataset is 91, but COCO2017 has only 80 targets in total. How did you correspond to them and train the COCO2017 data set? Currently I cannot train the coco2017 dataset using the coco.yaml file you provided.
Looking forward to your reply！

**Comment by NanoCode012** [comment]
Hi @zhangkuncsdn, you can download coco2017 via this command.

https://github.com/ultralytics/yolov5/blob/bb8872ea5f2afb7b6b2c81034b1d399d61d5157a/data/scripts/get_coco.sh#L3

**Comment by smiles724** [comment]
I can train the model successfully using the provided code.
