### ISSUE TITLE
TypeError: tuple indices must be integers or slices, not tuple

### ISSUE THREAD

**Issue by yangboz** [ultralytics/yolov5#9390]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

Traceback (most recent call last):
  File "/home/xibaoda/yolov5_ws/train.py", line 664, in <module>
    main(opt)
  File "/home/xibaoda/yolov5_ws/train.py", line 559, in main
    train(opt.hyp, opt, device, callbacks)
  File "/home/xibaoda/yolov5_ws/train.py", line 347, in train
    loss, loss_items = compute_loss(pred, targets.to(device))  # loss scaled by batch_size
  File "/home/xibaoda/yolov5_ws/utils/loss.py", line 125, in __call__
    tcls, tbox, indices, anchors = self.build_targets(p, targets)  # targets
  File "/home/xibaoda/yolov5_ws/utils/loss.py", line 205, in build_targets
    r = t[..., 4:6] / anchors[:, None]  # wh ratio
TypeError: tuple indices must be integers or slices, not tuple

### Minimal Reproducible Example

```
CUDA_VISIBLE_DEVICES=0 python train.py --weight=yolov5s.pt --data=dataset4xyz.yaml --img=480
```

### Additional

[loss.py](https://github.com/ultralytics/yolov5/blob/master/utils/loss.py)

dataset4xyz.yaml copy from default  [dataset.yaml]
python 3.9
torch                   1.12.1
torchvision             0.13.1

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@yangboz there might be something wrong with your model yaml or dataset format. See Train Custom Data tutorial to get started:

## Tutorials

- [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)  🚀 RECOMMENDED
- [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)  ☘️
  RECOMMENDED
- [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
- [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) 🌟 NEW
- [TFLite, ONNX, CoreML, TensorRT Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
- [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
- [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
- [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
- [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
- [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)
- [Architecture Summary](https://docs.ultralytics.com/yolov5/tutorials/architecture_description) 🌟 NEW
- [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)
- [Roboflow for Datasets, Labeling, and Active Learning](https://docs.ultralytics.com/yolov5/tutorials/roboflow_datasets_integration)  🌟 NEW
- [ClearML Logging](https://docs.ultralytics.com/yolov5/tutorials/clearml_logging_integration) 🌟 NEW
- [Deci Platform](https://github.com/ultralytics/yolov5/wiki/Deci-Platform) 🌟 NEW
- [Comet Logging](https://docs.ultralytics.com/yolov5/tutorials/comet_logging_integration) 🌟 NEW

Good luck 🍀 and let us know if you have any other questions!

**Comment by AetherLiu** [comment]
你好，请问解决了这个问题吗

**Comment by glenn-jocher** [comment]
@HaHalr 你好！看起来你是在寻找有关之前讨论的问题的解决方案。如果你遇到的是特定的错误消息或问题，我建议首先检查你的代码是否最新，并确认你遵循了所有的数据准备和训练步骤。如果问题仍然存在，请提供更具体的错误描述和代码上下文，这样我们可以更准确地帮助你。感谢你对YOLOv5的支持！🌟

**Comment by HaHalr** [comment]
@glenn-jocher Hello, author.   I followed the data preparation and training steps, but found that the problem still exists，Executing the train.py file gives me the following error：
Traceback (most recent call last):
  File "train.py", line 635, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 365, in train
    loss, loss_items = compute_loss(pred[0], targets.to(device))  # loss scaled by batch_size
  File "/media/liu/Liu/code/multiyolov5/utils/loss.py", line 118, in __call__
    tcls, tbox, indices, anchors = self.build_targets(p, targets)  # targets
  File "/media/liu/Liu/code/multiyolov5/utils/loss.py", line 186, in build_targets
    r = t[:, :, 4:6] / anchors[:, None]  # 元
TypeError: tuple indices must be integers or slices, not tuple
---------------------------------------------------------------------------------------------------------------------------------


I don't know if there is something wrong with my loss.py program or something else, I hope you can give me some directions or suggestions to solve the problem, I will be grateful, here is the content of my loss.py
：
# Loss functions

import torch
import torch.nn as nn
import torch.nn.functional as F
from utils.general import bbox_iou
from utils.torch_utils import is_parallel
from torch.autograd import Variable


def smooth_BCE(eps=0.1):  # https://github.com/ultralytics/yolov3/issues/238#issuecomment-598028441
    # return positive, negative label smoothing BCE targets
    return 1.0 - 0.5 * eps, 0.5 * eps


class BCEBlurWithLogitsLoss(nn.Module):
    # BCEwithLogitLoss() with reduced missing label effects.
    def __init__(self, alpha=0.05):
        super(BCEBlurWithLogitsLoss, self).__init__()
        self.loss_fcn = nn.BCEWithLogitsLoss(reduction='none')  # must be nn.BCEWithLogitsLoss()
        self.alpha = alpha

    def forward(self, pred, true):
        loss = self.loss_fcn(pred, true)
        pred = torch.sigmoid(pred)  # prob from logits
        dx = pred - true  # reduce only missing label effects
        # dx = (pred - true).abs()  # reduce missing label and false label effects
        alpha_factor = 1 - torch.exp((dx - 1) / (self.alpha + 1e-4))
        loss *= alpha_factor
        return loss.mean()


class FocalLoss(nn.Module):
    # Wraps focal loss around existing loss_fcn(), i.e. criteria = FocalLoss(nn.BCEWithLogitsLoss(), gamma=1.5)
    def __init__(self, loss_fcn, gamma=1.5, alpha=0.25):
        super(FocalLoss, self).__init__()
        self.loss_fcn = loss_fcn  # must be nn.BCEWithLogitsLoss()
        self.gamma = gamma
        self.alpha = alpha
        self.reduction = loss_fcn.reduction
        self.loss_fcn.reduction = 'none'  # required to apply FL to each element

    def forward(self, pred, true):
        loss = self.loss_fcn(pred, true)
        # p_t = torch.exp(-loss)
        # loss *= self.alpha * (1.000001 - p_t) ** self.gamma  # non-zero power for gradient stability

        # TF implementation https://github.com/tensorflow/addons/blob/v0.7.1/tensorflow_addons/losses/focal_loss.py
        pred_prob = torch.sigmoid(pred)  # prob from logits
        p_t = true * pred_prob + (1 - true) * (1 - pred_prob)
        alpha_factor = true * self.alpha + (1 - true) * (1 - self.alpha)
        modulating_factor = (1.0 - p_t) ** self.gamma
        loss *= alpha_factor * modulating_factor

        if self.reduction == 'mean':
            return loss.mean()
        elif self.reduction == 'sum':
            return loss.sum()
        else:  # 'none'
            return loss


class QFocalLoss(nn.Module):
    # Wraps Quality focal loss around existing loss_fcn(), i.e. criteria = FocalLoss(nn.BCEWithLogitsLoss(), gamma=1.5)
    def __init__(self, loss_fcn, gamma=1.5, alpha=0.25):
        super(QFocalLoss, self).__init__()
        self.loss_fcn = loss_fcn  # must be nn.BCEWithLogitsLoss()
        self.gamma = gamma
        self.alpha = alpha
        self.reduction = loss_fcn.reduction
        self.loss_fcn.reduction = 'none'  # required to apply FL to each element

    def forward(self, pred, true):
        loss = self.loss_fcn(pred, true)

        pred_prob = torch.sigmoid(pred)  # prob from logits
        alpha_factor = true * self.alpha + (1 - true) * (1 - self.alpha)
        modulating_factor = torch.abs(true - pred_prob) ** self.gamma
        loss *= alpha_factor * modulating_factor

        if self.reduction == 'mean':
            return loss.mean()
        elif self.reduction == 'sum':
            return loss.sum()
        else:  # 'none'
            return loss


class ComputeLoss:
    # Compute losses
    def __init__(self, model, autobalance=False):
        super(ComputeLoss, self).__init__()
        device = next(model.parameters()).device  # get model device
        h = model.hyp  # hyperparameters

        # Define criteria
        BCEcls = nn.BCEWithLogitsLoss(pos_weight=torch.tensor([h['cls_pw']], device=device))  # cls BCE yolov3后传统, BCE而不是CE
        BCEobj = nn.BCEWithLogitsLoss(pos_weight=torch.tensor([h['obj_pw']], device=device))  # obj BCE

        # Class label smoothing https://arxiv.org/pdf/1902.04103.pdf eqn 3
        self.cp, self.cn = smooth_BCE(eps=h.get('label_smoothing', 0.0))  # positive, negative BCE targets # 标签label smoothing后正样本和负样本的概率

        # Focal loss 是否focal loss以及γ的大小, 看超参数配置文件, 默认不用focal loss
        g = h['fl_gamma']  # focal loss gamma
        if g > 0:
            BCEcls, BCEobj = FocalLoss(BCEcls, g), FocalLoss(BCEobj, g)

        det = model.module.model[-1] if is_parallel(model) else model.model[-1]  # Detect() module # 若DDP外面又包了一层所有形式不一样
        self.balance = {3: [4.0, 1.0, 0.4]}.get(det.nl, [4.0, 1.0, 0.25, 0.06, .02])  # P3-P7
        self.ssi = list(det.stride).index(16) if autobalance else 0  # stride 16 index
        self.BCEcls, self.BCEobj, self.gr, self.hyp, self.autobalance = BCEcls, BCEobj, model.gr, h, autobalance
        for k in 'na', 'nc', 'nl', 'anchors':
            setattr(self, k, getattr(det, k))

    def __call__(self, p, targets):  # predictions, targets, model
        device = targets.device
        lcls, lbox, lobj = torch.zeros(1, device=device), torch.zeros(1, device=device), torch.zeros(1, device=device)
        tcls, tbox, indices, anchors = self.build_targets(p, targets)  # targets

        # Losses
        for i, pi in enumerate(p):  # layer index, layer predictions
            b, a, gj, gi = indices[i]  # image, anchor, gridy, gridx
            tobj = torch.zeros_like(pi[..., 0], device=device)  # target obj

            n = b.shape[0]  # number of targets
            if n:
                ps = pi[b, a, gj, gi]  # prediction subset corresponding to targets

                # Regression
                pxy = ps[:, :2].sigmoid() * 2. - 0.5
                pwh = (ps[:, 2:4].sigmoid() * 2) ** 2 * anchors[i]
                pbox = torch.cat((pxy, pwh), 1)  # predicted box 上两行按推理的box放缩偏移
                iou = bbox_iou(pbox.T, tbox[i], x1y1x2y2=False, CIoU=True)  # iou(prediction, target) 用CIoU loss
                lbox += (1.0 - iou).mean()  # iou loss

                # Objectness
                tobj[b, a, gj, gi] = (1.0 - self.gr) + self.gr * iou.detach().clamp(0).type(tobj.dtype)  # iou ratio

                # Classification
                if self.nc > 1:  # cls loss (only if multiple classes) 多类别才有cls loss
                    t = torch.full_like(ps[:, 5:], self.cn, device=device)  # targets
                    t[range(n), tcls[i]] = self.cp
                    lcls += self.BCEcls(ps[:, 5:], t)  # BCE

                # Append targets to text file
                # with open('targets.txt', 'a') as file:
                #     [file.write('%11.5g ' * 4 % tuple(x) + '\n') for x in torch.cat((txy[i], twh[i]), 1)]

            obji = self.BCEobj(pi[..., 4], tobj)
            lobj += obji * self.balance[i]  # obj loss
            if self.autobalance:
                self.balance[i] = self.balance[i] * 0.9999 + 0.0001 / obji.detach().item()

        if self.autobalance:
            self.balance = [x / self.balance[self.ssi] for x in self.balance]
        lbox *= self.hyp['box']  # 三部分loss乘以其超参数配置文件中的增益
        lobj *= self.hyp['obj']
        lcls *= self.hyp['cls']
        bs = tobj.shape[0]  # batch size

        loss = lbox + lobj + lcls
        return loss * bs, torch.cat((lbox, lobj, lcls, loss)).detach()  # BCE自动平均故乘batchsize, detach()从计算图中除去防止梯度泄露

    def build_targets(self, p, targets):
        # Build targets for compute_loss(), input targets(image,class,x,y,w,h)
        na, nt = self.na, targets.shape[0]  # number of anchors, targets
        tcls, tbox, indices, anch = [], [], [], []
        gain = torch.ones(7, device=targets.device)  # normalized to gridspace gain
        ai = torch.arange(na, device=targets.device).float().view(na, 1).repeat(1, nt)  # same as .repeat_interleave(nt)
        targets = torch.cat((targets.repeat(na, 1, 1), ai[:, :, None]), 2)  # append anchor indices

        g = 0.5  # bias
        off = torch.tensor([[0, 0],
                            [1, 0], [0, 1], [-1, 0], [0, -1],  # j,k,l,m
                            # [1, 1], [1, -1], [-1, 1], [-1, -1],  # jk,jm,lk,lm
                            ], device=targets.device).float() * g  # offsets

        for i in range(self.nl):
            anchors , = self.anchors[i], p[i].shape
            gain[2:6] = torch.tensor(p[i].shape)[[3, 2, 3, 2]]  # xyxy gain

            # Match targets to anchors
            t = targets * gain
            if nt:
                # Matches
                r = t[:, :, 4:6] / anchors[:, None]  # 元
                j = torch.max(r, 1. / r).max(2)[0] < self.hyp['anchor_t']  # compare
                # j = wh_iou(anchors, t[:, 4:6]) > model.hyp['iou_t']  # iou(3,n)=wh_iou(anchors(3,2), gwh(n,2))
                t = t[j]  # filter

                # Offsets
                gxy = t[:, 2:4]  # grid xy
                gxi = gain[[2, 3]] - gxy  # inverse
                j, k = ((gxy % 1. < g) & (gxy > 1.)).T
                l, m = ((gxi % 1. < g) & (gxi > 1.)).T
                j = torch.stack((torch.ones_like(j), j, k, l, m))
                t = t.repeat((5, 1, 1))[j]
                offsets = (torch.zeros_like(gxy)[None] + off[:, None])[j]
            else:
                t = targets[0]
                offsets = 0

            # Define
            b, c = t[:, :2].long().T  # image, class
            gxy = t[:, 2:4]  # grid xy
            gwh = t[:, 4:6]  # grid wh
            gij = (gxy - offsets).long()
            gi, gj = gij.T  # grid xy indices

            # Append
            a = t[:, 6].long()  # anchor indices
            indices.append((b, a, gj.clamp_(0, gain[3] - 1), gi.clamp_(0, gain[2] - 1)))  # image, anchor, grid indices
            tbox.append(torch.cat((gxy - gij, gwh), 1))  # box
            anch.append(anchors[a])  # anchors
            tcls.append(c)  # class

        return tcls, tbox, indices, anch


# 语义分割损失函数  带不带aux，带几个aux内外部接口本应该保持一致，但我没时间改了
class SegmentationLosses(nn.CrossEntropyLoss):
    """2D Cross Entropy Loss with Auxilary Loss"""
    def __init__(self, se_loss=False, se_weight=0.2, nclass=-1, aux_num=2,
                 aux=False, aux_weight=0.1, weight=None,
                 ignore_index=-1):
        super(SegmentationLosses, self).__init__(weight, None, ignore_index)
        self.se_loss = se_loss
        self.aux = aux
        self.nclass = nclass
        self.se_weight = se_weight
        self.aux_weight = aux_weight
        self.bceloss = nn.BCELoss(weight)
        self.aux_num = aux_num

    def forward(self, *inputs):  # 这里接口写的很丑,没时间重构了,直接点就是无aux不用[],有aux几个结果输出用[]包装
        if not self.se_loss and not self.aux:  # 无aux, Base,PSP和Lab用这个
            return super(SegmentationLosses, self).forward(*inputs)
        elif not self.se_loss:      
            if self.aux_num == 2:  # 两个aux，BiSe用这个
                pred1, pred2, pred3, target = tuple(inputs)
                loss1 = super(SegmentationLosses, self).forward(pred1, target)
                loss2 = super(SegmentationLosses, self).forward(pred2, target)
                loss3 = super(SegmentationLosses, self).forward(pred3, target)
                return loss1 + self.aux_weight*1.5 * loss2 + self.aux_weight/2.0 * loss3
            else:  # 一个aux, 目前没有用这个
                assert self.aux_num == 1
                pred1, pred2, target = tuple(inputs)
                loss1 = super(SegmentationLosses, self).forward(pred1, target)
                loss2 = super(SegmentationLosses, self).forward(pred2, target)
                return loss1 + self.aux_weight * loss2
        elif not self.aux:   # 目前仅支持以上三种配置(无aux，一个，两个)，以下两种情况目前未使用，所以bug未修改
            pred, se_pred, target = tuple(inputs)
            se_target = self._get_batch_label_vector(target, nclass=self.nclass).type_as(pred)
            loss1 = super(SegmentationLosses, self).forward(pred, target)
            loss2 = self.bceloss(torch.sigmoid(se_pred), se_target)
            return loss1 + self.se_weight * loss2
        else:
            pred1, se_pred, pred2, target = tuple(inputs)
            se_target = self._get_batch_label_vector(target, nclass=self.nclass).type_as(pred1)
            loss1 = super(SegmentationLosses, self).forward(pred1, target)
            loss2 = super(SegmentationLosses, self).forward(pred2, target)
            loss3 = self.bceloss(torch.sigmoid(se_pred), se_target)
            return loss1 + self.aux_weight * loss2 + self.se_weight * loss3

    # @staticmethod
    # def _get_batch_label_vector(target, nclass):
    #     # target is a 3D Variable BxHxW, output is 2D BxnClass
    #     batch = target.size(0)
    #     tvect = Variable(torch.zeros(batch, nclass))
    #     for i in range(batch):
    #         hist = torch.histc(target[i].cpu().data.float(),
    #                            bins=nclass, min=0,
    #                            max=nclass-1)
    #         vect = hist>0
    #         tvect[i] = vect
    #     return tvect


class SegFocalLoss(nn.CrossEntropyLoss):
    ''' Focal loss for classification tasks on imbalanced datasets '''

    def __init__(self, gamma=2, alpha=None, ignore_index=-100, reduction='mean'):
        super().__init__(weight=alpha, ignore_index=ignore_index, reduction='mean')
        self.reduction = reduction
        self.gamma = gamma

    def forward(self, input_, target):
        cross_entropy = super().forward(input_, target)
        # Temporarily mask out ignore index to '0' for valid gather-indices input.
        # This won't contribute final loss as the cross_entropy contribution
        # for these would be zero.
        target = target * (target != self.ignore_index).long()
        input_prob = torch.gather(F.softmax(input_, 1), 1, target.unsqueeze(1))
        loss = torch.pow(1 - input_prob, self.gamma) * cross_entropy
        if self.reduction == 'mean': return torch.mean(loss)
        elif self.reduction == 'sum': return torch.sum(loss)
        else: return loss


# 以下有两种OHEM实现略有不同，分别是根据两个bisenet实现修改的，aux使用接口一致, 第一种实现更快(batchsize＝12时候一轮比第二种快22s)
# bisenet的aux和main loss是同权重的[1.0, 1.0]但我的实验同权重非常不好，我认为辅助权重应该低于主权重，很多其他网络实现也是辅助权重低的
# 第一种
class OhemCELoss(nn.Module):  # 带ohem和aux的CE，0.7是根据bisenet原作者和复现者参数确定的
    def __init__(self, thresh=0.5, ignore_index=-1, aux=False, aux_weight=[0.15, 0.05]):  # 辅助损失可以设小，但bisenet里辅助损失系数为1(同权)，pytorch encoding项目默认0.2
        super(OhemCELoss, self).__init__()
        self.thresh = -torch.log(torch.tensor(thresh, requires_grad=False, dtype=torch.float)).cuda()
        self.ignore_index = ignore_index
        self.criteria = nn.CrossEntropyLoss(ignore_index=ignore_index, reduction='none')
        self.aux = aux
        self.aux_weight = aux_weight

    def forward(self, preds, labels):
        if not self.aux:  # 此时preds应该为单个输出
            return self.forward_once(preds, labels)
        else:  # 此时preds应该为三个输出并用[]包裹起来，preds[0]永远是主输出
            mainloss = self.forward_once(preds[0], labels)  # 若采用resize标签到来节约显存参考下两行注释替换labels，并且去除yolo.py分割head的aux部分的上采样(不推荐resize标签)
            auxloss1 = self.forward_once(preds[1], labels)  #  (preds[1].shape[2], preds[1].shape[3]), mode='nearest')[0].long())
            auxloss2 = self.forward_once(preds[2], labels)  #  (preds[2].shape[2], preds[2].shape[3]), mode='nearest')[0].long())
            return mainloss + self.aux_weight[0] * auxloss1 + self.aux_weight[1] * auxloss2

    def forward_once(self, preds, labels):
        n_min = int(labels[labels != self.ignore_index].numel() // 16)  # 1/16=(1/4)^2即不计ignore的1/4张图  #(16*8**2)  # 最少样本公式是按bisenet原作者表达式写的(这个实现少除以8**2) 原式int(config.batch_size // len(engine.devices) * config.image_height * config.image_width //(16 * config.gt_down_sampling ** 2))
        # print(n_min)
        loss = self.criteria(preds, labels).view(-1)
        loss_hard = loss[loss > self.thresh]
        if loss_hard.numel() < n_min:
            loss_hard, _ = loss.topk(n_min)
        return torch.mean(loss_hard)


# 第二种
class ProbOhemCrossEntropy2d(nn.Module):
    def __init__(self, ignore_index, reduction='mean', thresh=0.5, min_kept=256, aux=False, aux_weight=[0.4, 0.4], use_weight=False):
        super(ProbOhemCrossEntropy2d, self).__init__()
        self.ignore_index = ignore_index
        self.thresh = float(thresh)
        self.min_kept = int(min_kept)
        if use_weight:
            weight = torch.FloatTensor(
                [1.4297, 1.4805, 1.4363, 3.365, 2.6635, 1.4311, 2.1943, 1.4817,
                 1.4513, 2.1984, 1.5295, 1.6892, 3.2224, 1.4727, 7.5978, 9.4117,
                 15.2588, 5.6818, 2.2067])
            self.criterion = torch.nn.CrossEntropyLoss(reduction=reduction,
                                                       weight=weight,
                                                       ignore_index=ignore_index)
        else:
            self.criterion = torch.nn.CrossEntropyLoss(reduction=reduction,
                                                       ignore_index=ignore_index)
        self.aux = aux
        self.aux_weight = aux_weight

    def forward(self, preds, target):
        if not self.aux:  # 此时preds应该为单个输出
            return forward_once(preds, target)
        else:  # 此时preds应该为三个输出并用[]包裹起来，preds[0]永远是主输出
            mainloss = self.forward_once(preds[0], target)  # 若采用resize标签到来节约显存参考下两行注释替换labels，并且去除yolo.py分割head的aux部分的上采样
            auxloss1 = self.forward_once(preds[1], target)  # F.interpolate(target.float().unsqueeze(0), (preds[1].shape[2], preds[1].shape[3]), mode='nearest')[0].long())
            auxloss2 = self.forward_once(preds[2], target)  # F.interpolate(target.float().unsqueeze(0), (preds[2].shape[2], preds[2].shape[3]), mode='nearest')[0].long())
            return mainloss + self.aux_weight[0] * auxloss1 + self.aux_weight[1] * auxloss2            

    def forward_once(self, pred, target):
        b, c, h, w = pred.size()
        target = target.view(-1)
        valid_mask = target.ne(self.ignore_index)
        target = target * valid_mask.long()
        num_valid = valid_mask.sum()

        prob = F.softmax(pred, dim=1)
        prob = (prob.transpose(0, 1)).reshape(c, -1)

        if self.min_kept > num_valid:
            logger.info('Labels: {}'.format(num_valid))
        elif num_valid > 0:
            prob = prob.masked_fill_(~valid_mask, 1)  # 注：pytorch1.2后bool tensor不支持１ - , use the `~` or `logical_not()` operator instead
            mask_prob = prob[
                target, torch.arange(len(target), dtype=torch.long)]
            threshold = self.thresh
            if self.min_kept > 0:
                _, index = torch.sort(mask_prob)
                threshold_index = index[min(len(index), self.min_kept) - 1]
                if mask_prob[threshold_index] > self.thresh:
                    threshold = mask_prob[threshold_index]
                kept_mask = mask_prob.le(threshold)
                target = target * kept_mask.long()
                valid_mask = valid_mask * kept_mask
                # logger.info('Valid Mask: {}'.format(valid_mask.sum()))

        target = target.masked_fill_(~valid_mask, self.ignore_index)  # 注：pytorch1.2后bool tensor不支持１ - , use the `~` or `logical_not()` operator instead
        target = target.view(b, h, w)

        return self.criterion(pred, target)

**Comment by AetherLiu** [comment]
@glenn-jocher   Hello Author, I have followed the data preparation and training steps, but I still find that the problem exists. I am at a loss on how to deal with it and have not found any relevant solutions, so I am seeking help. Below is the error information prompted after I executed train.py: 

home/liu/anaconda3/yes/envs/myolov5/lib/python3.7/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3190.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Model Summary: 363 layers, 7760090 parameters, 7760090 gradients, 23.9 GFLOPS

Transferred 354/450 items from ./yolov5s.pt
Scaled weight_decay = 0.0005625000000000001
Optimizer groups: 77 .bias, 79 conv.weight, 73 other
train: Scanning 'data/citys/detdata/labels/train.cache' images and labels... 2975 found, 0 missing, 1 empty, 118 corrupt
val: Scanning 'data/citys/detdata/labels/val.cache' images and labels... 500 found, 0 missing, 3 empty, 11 corrupted: 10
Plotting labels... 
Found 500 images in the folder ./data/citys/leftImg8bit/val
BaseDataset: base_size 1024, crop_size (832, 416)
Random scale low: 0.65, high: 3, sample_std: 25
Found 2975 images in the folder ./data/citys/leftImg8bit/train
Image sizes 832 train, 832 test
Using 8 dataloader workers
Logging results to runs/train/exp54
Starting training for 200 epochs...
accumulate: 4

     Epoch   gpu_mem       box       obj       cls     total       seg    labels  img_size
  0%|                                                                                           | 0/159 [00:12<?, ?it/s]
  0%|                                                                                           | 0/159 [00:12<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 635, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 365, in train
    loss, loss_items = compute_loss(pred[0], targets.to(device))  # loss scaled by batch_size
  File "/media/liu/Liu/code/multiyolov5/utils/loss.py", line 118, in __call__
    tcls, tbox, indices, anchors = self.build_targets(p, targets)  # targets
  File "/media/liu/Liu/code/multiyolov5/utils/loss.py", line 186, in build_targets
    r = t[:, :, 4:6] / anchors[:, None]  # 元
TypeError: tuple indices must be integers or slices, not tuple

. I hope you can give me some direction or method to solve this problem. I would be very grateful.

**Comment by glenn-jocher** [comment]
@HaHalr Hi there! It looks like the issue is related to improper indexing or data types when handling the `anchors` in your `loss.py`. This type of error usually happens when the expected object structure is different from what is actually provided. 

Please ensure that `anchors` is a tensor. If it's being loaded as a different datatype (e.g., a list or a numpy array), you might need to convert it to a PyTorch tensor before performing operations on it. You can convert `anchors` to a tensor using:

```python
anchors = torch.tensor(anchors).float().to(device)  # Assuming you have a device defined
```

Also, double-check the shape and type of `t` and `anchors` just before the line causing the error to ensure they are compatible for the operations you're trying to perform.

If the problem persists, it might be helpful to print out the types and shapes of variables involved in the operation causing the error right before it occurs. This can give you more insight into why the type error is happening.

Keep going, debugging issues like this can be tricky but you're on the right path! 🚀

**Comment by AetherLiu** [comment]
@glenn-jocher Dear author, thank you for your valuable suggestions. After repeatedly checking the loss.py file, I found two errors and have corrected them. I am very grateful for your recent responses. I would like to share the joy of solving the problem with you. Thank you once again!
![OEZ(V9VU@~7OD1091VZXDBC_tmb](https://github.com/ultralytics/yolov5/assets/131743306/d57b5a9d-b754-463e-a178-ed2a376ab7f3)

**Comment by glenn-jocher** [comment]
@HaHalr That's fantastic news! 🎉 I'm glad to hear you were able to solve the issues by making those corrections in the `loss.py` file. Thanks for sharing your success - it's always rewarding to see problems being solved, and your perseverance is commendable. Keep up the great work, and don't hesitate to reach out if you run into further questions or need assistance down the road. Happy coding! 😊

**Comment by Unlicensed-driver-ljx** [comment]
@HaHalr 麻烦能告知改了那个地方吗

**Comment by daidairong** [comment]
> 尊敬的作者，感谢您的宝贵建议。在反复检查 loss.py 文件后，我发现了两个错误并已进行了纠正。我非常感谢你最近的答复。我想与您分享解决问题的喜悦。再次感谢你们！ ![OEZ（V9VU@~7OD1091VZXDBC_tmb](https://private-user-images.githubusercontent.com/131743306/315311690-d57b5a9d-b754-463e-a178-ed2a376ab7f3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNDAzNjgsIm5iZiI6MTcyMjE0MDA2OCwicGF0aCI6Ii8xMzE3NDMzMDYvMzE1MzExNjkwLWQ1N2I1YTlkLWI3NTQtNDYzZS1hMTc4LWVkMmEzNzZhYjdmMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOFQwNDE0MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMmFhMjRjM2M1ZWNiNWY5ODM5MDU0MjAwZTY1MzAwODFmNTQ0NWE2MzA2NTY5MWEzZjc5NWRiODkwYjAxN2MyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xqhh5L4RPl2nCY1_rS9dDMxh3jOcaZ-yHHR4h0zYYCw)

想知道改了哪里求求了

**Comment by AetherLiu** [comment]
错误原因好像出才数据集上，有点忘了，你可以先试试用200张或者更少的数据集试试，因为我后续用了yolo 其他版本，所以可能有点忘了在 2024年7月28日，12:15，daidairong ***@***.***> 写道：﻿

尊敬的作者，感谢您的宝贵建议。在反复检查 loss.py 文件后，我发现了两个错误并已进行了纠正。我非常感谢你最近的答复。我想与您分享解决问题的喜悦。再次感谢你们！ 

想知道改了哪里求求了

**Comment by glenn-jocher** [comment]
@HaHalr 你好！很高兴听到你已经解决了问题并且愿意分享你的解决方案。对于@HaHalr 提到的错误，可能确实与数据集有关。为了帮助其他遇到类似问题的用户，能否请你详细描述一下你在 `loss.py` 文件中所做的具体修改？

如果你不太记得具体的修改内容，可以尝试以下步骤来帮助其他用户排查问题：
1. **数据集检查**：确保你的数据集没有损坏的文件或标签。你可以先用一个较小的数据集（例如200张图片）进行测试，看看问题是否依然存在。
2. **代码调试**：在 `loss.py` 文件中，添加一些调试信息来打印出变量的类型和形状，以确保它们符合预期。例如：
    ```python
    print(f"Type of anchors: {type(anchors)}, Shape of anchors: {anchors.shape}")
    print(f"Type of t: {type(t)}, Shape of t: {t.shape}")
    ```
3. **最新版本**：确保你使用的是 YOLOv5 的最新版本，因为一些已知问题可能在新版本中已经修复。

希望这些建议对你有所帮助。如果你有更多的细节可以分享，欢迎随时更新！感谢你对 YOLOv5 社区的支持！😊
