### ISSUE TITLE
How to Save Pruned Model

### ISSUE THREAD

**Issue by jobsjiang** [ultralytics/yolov5#9392]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

![image](https://user-images.githubusercontent.com/3956821/189864034-ef30ba7d-d2df-4169-a13f-48c1ea96c041.png)
Follow the above instruction and add the code:
`torch.save({'model': deepcopy(de_parallel(model)).half(), }, "./tmp/pruned_model.pt")`
but run：
`python detect.py --weights ./tmp/pruned_model.pt --source ./datasets/images/test/`
get the error:
```
Traceback (most recent call last):
  File "detect.py", line 254, in <module>
    main(opt)
  File "detect.py", line 249, in main
    run(**vars(opt))
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 93, in run
    model = DetectMultiBackend(weights, device=device, dnn=dnn, data=data, fp16=half)
  File "/home/jianghaitao/yolov5/models/common.py", line 331, in __init__
    model = attempt_load(weights if isinstance(weights, list) else w, device=device, inplace=True, fuse=fuse)
  File "/home/jianghaitao/yolov5/models/experimental.py", line 88, in attempt_load
    model.append(ckpt.fuse().eval() if fuse and hasattr(ckpt, 'fuse') else ckpt.eval())  # model in eval mode
TypeError: 'bool' object is not callable
```

**Comment by glenn-jocher** [comment]
@jobsjiang hi there! It looks like you're encountering an issue when trying to save and load a pruned model. The error you're seeing is related to a bool object not being callable. Have you verified that the `--weights` argument you're passing in `detect.py` is correctly pointing to the pruned model file? Additionally, ensure that the model architecture and checkpoint versions are compatible. If you have any further details to share or need more assistance, feel free to let me know!
