### ISSUE TITLE
Validation images not visible in WANDB

### ISSUE THREAD

**Issue by nikogamulin** [ultralytics/yolov5#9393]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Integrations, Other

### Bug

Hi,

In the past, I have successfully trained and visualized the results in WANDB. Yesterday, I have cloned the yolov5 repo again, configured everything required for training as before (mostly related to dataset - haven't touched anything related to wandb). After the training, I wanted to visualize the Validation panel (images overlayed with bounding box prediction), but the panel is not available. Neither is available confusion matrix.

Does anyone know what might be the cause of not logging the validation and how to fix it?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@nikogamulin these should log automatically on training completion. If that is not the case then please raise an issue on the wandb repo, thank you!
