### ISSUE TITLE
detect.py only save zidane.jpg and bus.jpg detection and ignores any other images in my mounted drive !

### ISSUE THREAD

**Issue by Nayr0uz** [ultralytics/yolov5#9396]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

Ran Yolov5, and mounted my google drive to run yolo on some images there
after finishing detection, when i come to execute `!python detect.py --save-crop ` it saves categories crops to **runs/detect/exp/crops** 
i go to check to find it ONLY cropped categories from **Zidane.jpg** and **bus.jpg** 
and totally ignored my images from my mounted Gdrive

it crops it right but only when i upload the images to **/content/yolov5/data/images** but not when at Gdrive
anyone know how to fix this??

### Environment

yolov5
google colab

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Nayrouzzz you might want to review detect.py Usage:
https://github.com/ultralytics/yolov5/blob/03f2ca8eff8918b98169256d055353a1f15b8e32/detect.py#L5-L13

**Comment by glenn-jocher** [comment]
Also don't raise bug reports for simple questions.
