### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)：————out, train_out = model(im) if compute_loss else (model(im, augment=augment), None) 

### ISSUE THREAD

**Issue by JiannBai** [ultralytics/yolov5#9397]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

     When I was training my own dataset using train.py scripts, this error occurred during the validation phase：out, train_out = model(im) if compute_loss else (model(im, augment=augment), None) ；ValueError: not enough values to unpack (expected 2, got 1)。
    This is the code of the val.py that reported the error：
` # Inference
        with dt[1]:
            out, train_out = model(im) if compute_loss else (model(im, augment=augment), None)`

Why return one less value?

**Comment by glenn-jocher** [comment]
@jianbaiwuqing I've removed the --train argument from export.py to avoid confusion in https://github.com/ultralytics/yolov5/pull/9429

In general all exports are intended for inference-only deployments, so I think this will make things simpler for users.
