### ISSUE TITLE
Change Classifier

### ISSUE THREAD

**Issue by bzha5848** [ultralytics/yolov5#9398]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Hi there,

Just wondering for classifier in yolov5, is that possible to modify it as linear classifier? If so, where should it put?

Thanks so much!!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@bzha5848 YOLOv5 Classify() head already uses an nn.Linear() layer if that's what you are asking about.
https://github.com/ultralytics/yolov5/blob/36cb05b7b211d4c5d99586dd49d3195de16e4485/models/common.py#L789-L802

**Comment by bzha5848** [comment]
Ohh thank!! As I was using old version v6.1, I didn't see it. Thanks so much!!

**Comment by bzha5848** [comment]
Would you appreciate to share the classifier using non-linear as well?

**Comment by glenn-jocher** [comment]
@bzha5848 we only have one Classify() head that I shared above, there's no other version.
