### ISSUE TITLE
Visualization of detection 

### ISSUE THREAD

**Issue by DoSquared** [ultralytics/yolov5#9399]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello

I used the argument "--visualize" with detect.py and got output feature maps from YOLOv5. 

I was wondering how can I visualize other outputs from the detection like for example class prediction maps or whatever there is to visualize from the detection!

**Comment by DaliaMahdy** [comment]
How to get outputs from detection visualization similar to the image below. 

![image](https://user-images.githubusercontent.com/4492013/190139244-e52fafac-9bae-4619-892f-efebd0cccc8f.png)

**Comment by glenn-jocher** [comment]
@DoSquared hi there,

Glad to see you're interested in visualizing YOLOv5 detection outputs! You can visualize various detection outputs using `--visual`. This will generate images with bounding boxes, but if you'd like more detailed visualizations such as class prediction maps, you can consider post-processing the detection outputs and creating custom visualizations using the provided bounding box coordinates and confidence scores. 

For more specific visualizations, you may need to leverage external libraries like OpenCV or Matplotlib to render custom visualizations using the bounding boxes and class predictions from the YOLOv5 detections.

Hope this helps! If you have further questions, feel free to ask.
