### ISSUE TITLE
The center of annotated bound box change position 

### ISSUE THREAD

**Issue by frabob2017** [ultralytics/yolov5#9404]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I found that annotation position is not what I expect. 

For example, This data is  image 601_151, its coordinate system is  [0 0.40795277343749997 0.37763712890625 0.0997937890625 0.0438759765625].  The coordinate system I use is left top is 0,0 ; right bottom is 1,1;

![601_151](https://user-images.githubusercontent.com/57141860/190045650-9304ab52-3f7e-46c5-846a-fb75ba7a77ee.jpg)

 This is the correct bounding box. I use python to read coordinate information and overlap it to image confirm its correction position. 

But after I upload data to YoloV5, its label image created by YoloV5 (left side )  vs I use python to overlap bounding box (right side, correct position )
 
![comparison](https://user-images.githubusercontent.com/57141860/190046440-75e8599f-c07b-429b-a0b1-e8d8f6e5db88.jpg)

[601_151.txt](https://github.com/ultralytics/yolov5/files/9562152/601_151.txt)

any clues? 

import PIL
import matplotlib.pyplot as plt
import matplotlib.patches as patches

fig, axs = plt.subplots(nrows, ncols, figsize=(24,15))
axs = axs.flatten()

ds = PIL.Image.open('601_151.jpg')
axs[0].imshow(ds, cmap="bone")
axs[0].axis("off")

normalized_cordinate = [0.40795277343749997, 0.37763712890625, 0.0997937890625, 0.0438759765625]
x = 512*normalized_cordinate[0]
y = 512*normalized_cordinate[1]
width = 512*normalized_cordinate[2]
height = 512*normalized_cordinate[3]

rect = patches.Rectangle((x, y), width, height, fill=False, edgecolor="red", linewidth=1.0)
axs[0].add_patch(rect)

**Comment by MartinPedersenpp** [comment]
> But after I upload data to YoloV5, its label image created by YoloV5 (left side ) 

By this, do you mean the train_batch_01, 02, 03.jpgs created when training is started?

**Comment by frabob2017** [comment]
Hello Martin, 

Yes, it is the val_batch1_labels.jpg, val_batch2_labels.jpg; val_batch3_labels.jpg. It is the labels program read from the ground truth labels. The position of bounding box shift.  Frank

**Comment by frabob2017** [comment]
Hello Martin,

Thank you for your testing. You see, right side one is correct. It covers the fracture area. The left side one is NOT correct. 
I used Yolo format. [class x y width height] format.  Radiologists I worked with draw ROI in CSV format.  I convert their coordinate system to Yolo format.   I tested it using Python. The position is correct.  But I run in YoloV5, it is not correct, shifting a little bit. 

I find the same issue when I upload the data to RoboFlow.  Do you need the data, I can send you sample data for your testing. 

Thank you.

**Comment by frabob2017** [comment]
Their coordinate system is not normalized.  What I did is normalized them.  The image size is 512, 512; what I did is just normalized by 512.

**Comment by MartinPedersenpp** [comment]
> Hello Martin,
> 
> Thank you for your testing. You see, right side one is correct. It covers the fracture area. The left side one is NOT correct. I used Yolo format. [class x y width height] format. Radiologists I worked with draw ROI in CSV format. I convert their coordinate system to Yolo format. I tested it using Python. The position is correct. But I run in YoloV5, it is not correct, shifting a little bit.
> 
> I find the same issue when I upload the data to RoboFlow. Do you need the data, I can send you sample data for your testing.
> 
> Thank you.

The one on the left is the one I drew from the coordinates you provided, so again, I think that your annotation might be wrong. Perhaps it is class x1 y1 width height where it should be class center_x center_y width height.

**Comment by frabob2017** [comment]
Hello Martin, Thank you so much for help.  I double check again PIL.rectangle(x,y),  x,y  is left bottom corner. I make a mistake and think it is center point.

**Comment by MartinPedersenpp** [comment]
👍🏼 glad to be of help. Please don't forget to mark the issue as solved if your problem has been solved.

**Comment by frabob2017** [comment]
this problem is solved. thank you so much.

**Comment by glenn-jocher** [comment]
@frabob2017 you're welcome! If you have any more questions or need further assistance, feel free to ask. Happy coding!
