### ISSUE TITLE
--img is not accepting any 'int' variable

### ISSUE THREAD

**Issue by Mrinh212375** [ultralytics/yolov5#9405]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

I need to detect what is the lowest resolution of an image that can be detected reliably, So I'll be going to use a for loop using a variable but --img doesn't accept 'int' variable, only accepts 'int' number. like --img res, where res is an int value, it's giving me the error like - invalid int value: 'res'. Is there any way to do this.

### Use case

res = 416
for res in range(416,0,-50):
     !python detect .......  --img res...........

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by MartinPedersenpp** [comment]
You could try something like the python subprocess module

````
import subprocess

for res in range(416,0,-50):
    subprocess.run(f'python detect.py --img {res}')
````

**Comment by Mrinh212375** [comment]
> You could try something like the python subprocess module
> 
> ```
> import subprocess
> 
> for res in range(416,0,-50):
>     subprocess.run(f'python detect.py --img {res}')
> ```
thanks

**Comment by MartinPedersenpp** [comment]
You are welcome, please close the issue if it has been solved 👍🏼

**Comment by glenn-jocher** [comment]
@Mrinh212375 i currently don't have any relevant information about the issue. Feel free to post your question there, and someone from the team might be able to assist you.
