### ISSUE TITLE
Will NMS solve doble detection?

### ISSUE THREAD

**Issue by jjjonathan14** [ultralytics/yolov5#9406]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

we are using YOLOv5m pretrained 80 classes model to detect human. When inference we got some double detection for one person. How to solve that

**Comment by MartinPedersenpp** [comment]
If both the bounding boxes are labeled "person", reducing the IOU will eliminate overlapping bboxes with the same label

**Comment by glenn-jocher** [comment]
@MartinPedersenpp reducing the IOU threshold during non-maximum suppression (NMS) will indeed help eliminate overlapping detections with the same label. You can adjust the IOU threshold in the yolo5/models/yolo.py file. You'll find the nms threshold variable inside the NMS function. If you have further questions, feel free to ask.
