### ISSUE TITLE
save detection to same folder but with different filename(as windows explorer)

### ISSUE THREAD

**Issue by Mrinh212375** [ultralytics/yolov5#9408]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

I'm using --project ' ' and --exists-ok which causes all the detection result have to be saved in same folder, I don't want different folder containing only same images. I'm using this detect command under a decreasing for loop which is decreasing the resolution size, as I've to find out lowest resolution that can be detected accurately. 

Problem - everytime the detection result is overwritten by the next iteration. I want the detection result will be saved after each iteration automatically with different name so that it won't be overwritten.
Is there any way that on that same folder after every iteration files will be saved like filename1, filename2, filename3, filename4........

### Use case

res = 640
for res in range(640,0,-50):
  !python .............--source image.jpg............... --img {res}  --project /content/drive/MyDrive/yolov5/runs/detect/exp11 --name 1 --exist-ok 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by MartinPedersenpp** [comment]
https://github.com/ultralytics/yolov5/blob/a4ed9888938a090631ca4dba5be6363f8b66575c/detect.py#L180-L190

You could add something like:
```
if save_img: 
     if dataset.mode == 'image': 
         counter = 0
         save_path_inc = save_path
         while true:
             if counter == 0:
                 if os.path.exists(save_path):
                     counter += 1
                     save_path_inc = save_path + str(counter)
                 else:
                     cv2.imwrite(save_path, im0)
                     break
             else:
                if os.path.exists(save_path_inc)
                    counter += 1
                    save_path_inc = save_path + str(counter)
                else:
                    cv2.imwrite(save_path, im0)
                    break
```
I know it is messy and can probably be solved in an easier way, but this is to make up for the fact that you run detect multiple times, so you can't have a variable to hold the incrementer. Alternatively, you can save the counter in a txt file, but again it is going to get messy.
Good luck

**Comment by glenn-jocher** [comment]
@MartinPedersenpp thanks for sharing this code snippet! While your solution could work, implementing it directly within the YOLOv5 repo might affect the code's overall readability and maintainability. 

A more flexible approach could be to modify the save_path within your for loop, appending a counter or other unique identifier to the filename each time you save a detection. This way, you can control the naming convention at a higher level without modifying the YOLOv5 detect script. 

You might also consider creating a new issue at the YOLOv5 repo to discuss the possibility of adding this feature in a more streamlined way. 

Let me know if you need further assistance!
