### ISSUE TITLE
Optimize ONNX model to speed un TensorRT inference

### ISSUE THREAD

**Issue by JNaranjo-Alcazar** [ultralytics/yolov5#9410]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, community,
right now I have the model deployed on a Jetson TX2. The small (640, 640) image size model has an inference time of about 30 ms. I have seen that before converting to .engine, an ONNX model is generated, is there any option to optimize that ONNX model (pruning or other technique) before converting to TensorRT?

Thank you very much!

**Comment by glenn-jocher** [comment]
@JNaranjo-Alcazar you could add `--simplify` to simplify the ONNX model
