### ISSUE TITLE
Wrong Labels

### ISSUE THREAD

**Issue by MohammedZayn** [ultralytics/yolov5#9416]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Every time I convert the .pt file to .tflite the labels gets messed up 

when converted to tflite
![tflitemodel](https://user-images.githubusercontent.com/80457183/190164783-6f56a2b2-6ae8-4533-ad98-7dcfcc927735.jpg)

original yolo v5 labels
![yolo model](https://user-images.githubusercontent.com/80457183/190164793-16dbb84c-814f-4106-b2fc-b3a51a5d7399.jpg)

### Minimal Reproducible Example

!python3 export.py --weights runs/train/yolov5s_results2/weights/best.pt --img 416 --include tflite

^ I used the following to export my model

!python detect.py --weights /content/yolov5/runs/train/yolov5s_results2/weights/best-fp16.tflite --img 416 --conf 0.25 --source /content/testimages
^used the following to test my converted model 
![output](https://user-images.githubusercontent.com/80457183/190165614-d9562767-cc55-444b-82ee-ff5d377b5f47.jpg)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@MohammedZayn tflite models do not contain class names, so you have to pass --data yaml to detect.py

**Comment by MohammedZayn** [comment]
@glenn-jocher  thankyou! this worked; ive this other question, what if I deploy my model to an app,. do I need to download the data.yaml file ?

**Comment by glenn-jocher** [comment]
@MohammedZayn glad to hear that it worked! Yes, you will indeed need the data.yaml file along with your tflite model for deployment in an app. The data.yaml file provides the class names required for the model's predictions. For more details, you can refer to the Ultralytics YOLOv5 documentation at https://docs.ultralytics.com/yolov5/. Good luck with your deployment!
