### ISSUE TITLE
Reduce the number of classes while detecting to 4 classes

### ISSUE THREAD

**Issue by uberlumi** [ultralytics/yolov5#9420]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Good day,
When I run the code for multiple classes python detect.py --classes 0,2,5,7
I does detect these classes but it seems to detect others.
I try to play with the coco dataset + the yolo packages.. no chance.

Goal:
I need to set them as default, for Yolov5 and Deep Sort to limit CPU usage.

I did try to set default values for classes but I'm limited to 3...
Any solutions?
Thanks for your help guys
O

**Comment by barney2074** [comment]
remove commas i.e
`python detect.py --classes 0 2 5 7`

**Comment by Elumicate** [comment]
I did, Thanks @barney2074 still can't setup 4 classes as default, max is 3, any clue?
