### ISSUE TITLE
Success filter classes by models.classes = [0, ..., ..., ..] but wrong show img with bbox (for im in results.ims:)

### ISSUE THREAD

**Issue by hanifizzudinrahman** [ultralytics/yolov5#9421]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

Success filter classes by models.classes = [0, ..., ..., ..] but wrong show img with bbox (for im in results.ims:)

```
model_yolov5s_filter.classes = [0]

results = model_yolov5s(img, size=640)

results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results.ims
results.render()  # updates results.imgs with boxes and labels
for im in results.ims:
        print(im.shape)
        cv2.imshow("Results", im)
        cv2.waitKey(0)
```

It show the bbox but without filtering

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@hanifizzudinrahman works correctly for me, am unable to reproduce any issues here.
