### ISSUE TITLE
glob(str(p / '**' / '*.*'), recursive=True) in dataset init

### ISSUE THREAD

**Issue by wwwei1997** [ultralytics/yolov5#9426]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

I organized my custom dataset(around 70k images) directories [as recomended](https://docs.ultralytics.com/tutorials/train-custom-datasets/#3-organize-directories), and I found that the training process stucked in dataset init for nearly one hour, which was caused by `glob(str(p / '**' / '*.*'), recursive=True)` . All my images are under `p /`，no image under `p / **/`, so I rewrite the code: `glob(str(p / '*.*'))`, and the problem solved.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@wwwei1997 that's strange, not sure why it would hang. The current code allows for recursive searchers for datasets with nested directory structures.
