### ISSUE TITLE
the segment exported onnx model, can’t parse by tensorrt (C++) api

### ISSUE THREAD

**Issue by xinsuinizhuan** [ultralytics/yolov5#9434]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

I exporte the yolov5l-seg.pt, with command:
python export.py --weights ./models/segment/yolov5l-seg.pt --include onnx
and parse with the tensorrt api, but it break,with errors:
Failed to parse ONNX model from file

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@xinsuinizhuan YOLOv5l-seg export to ONNX works correctly for me, I'm unable to reproduce any issues:
<img width="1282" alt="Screenshot 2022-09-16 at 12 10 13" src="https://user-images.githubusercontent.com/26833433/190615911-b7b1da91-7114-4cd1-b949-3220ef6d6a73.png">

**Comment by glenn-jocher** [comment]
@xinsuinizhuan exporting YOLOv5l-seg to TensorRT also works for me:

<img width="1282" alt="Screenshot 2022-09-16 at 12 13 20" src="https://user-images.githubusercontent.com/26833433/190616452-6e370051-528e-42d2-a214-36c7b4444b41.png">

**Comment by xinsuinizhuan** [comment]
The newest code, it works. exporte the onnx model to tensorrt, is ok, by c++ tensorrt api.
![图片](https://user-images.githubusercontent.com/40679769/190940260-b31eae87-3b53-4293-8cee-f9bc2817eb54.png)

**Comment by sctrueew** [comment]
@xinsuinizhuan Hi, Did you run segmentation successfully in C++?

**Comment by xinsuinizhuan** [comment]
> @xinsuinizhuan Hi, Did you run segmentation successfully in C++?
no. the part of mask could not write with c++ for me, the part of detection is ok.

**Comment by xinsuinizhuan** [comment]
> @xinsuinizhuan Hi, Did you run segmentation successfully in C++?

how about you, could write it with c++?

**Comment by sctrueew** [comment]
> > @xinsuinizhuan Hi, Did you run segmentation successfully in C++?
> 
> how about you, could write it with c++?

You can use [Seg](https://github.com/UNeedCryDear/yolov5-seg-opencv-dnn-cpp) it.
