### ISSUE TITLE
How to detect objects in a very large image (10000 pixcel) effectively?

### ISSUE THREAD

**Issue by harrytrinh96** [ultralytics/yolov5#9435]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to detect objects in a very large image (10000 pixcel) effectively?

**Comment by glenn-jocher** [comment]
@harrytrinh96 you can pass any --imgsz your device can handle.

**Comment by barney2074** [comment]
I think you'd have to look at a tiled approach
Although not relevant to Yolov5, this is a good explanation:
https://www.ccoderun.ca/darkhelp/api/Tiling.html

**Comment by glenn-jocher** [comment]
One good tiled approach is SAHI, but unless your objects are very small I would simply try to run at the largest image size you can with batch-size 1
