### ISSUE TITLE
can we split dataset using python if there are some background images inside the dataset ? 

### ISSUE THREAD

**Issue by yjackboo** [ultralytics/yolov5#9437]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi Thank you so much for this great repository. 

I am a very beginner to coding and yolo algorithm. I know we can add some background images for our dataset in yolov5 without adding any annotation text file.  I know we can divide our dataset manually for train and validation. but I have a problem how to divide a dataset using python script if there are some images they don't have any annotation txt files. is it ok to create empty text files for those images and split the dataset ?. 
or how can we do that ? 

Thank you so much for any help.

**Comment by glenn-jocher** [comment]
@yjackboo background images do not need any txt label files. You can also autosplit datasets:

https://github.com/ultralytics/yolov5/blob/c7a2d6bcf4f7e88db53f3d09a8484391dac7bc89/utils/dataloaders.py#L878-L902

**Comment by yjackboo** [comment]
>

**Comment by yjackboo** [comment]
@glenn-jocher thank you so much sir. I will try above

**Comment by glenn-jocher** [comment]
@yjackboo you're welcome! If you have any more questions, feel free to ask. Good luck with your project!
