### ISSUE TITLE
yolov5 live stream

### ISSUE THREAD

**Issue by oes5756** [ultralytics/yolov5#9438]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Using yolov5 to recognize objects through the camera
It's working.
I want to stream the camera screen, but I want to know how.

This code does not work.
"python detect_test.py  --source http://112.50.243.8/PLTV/88888888/224/3221225900/1.m3u8"

**Comment by glenn-jocher** [comment]
@oes5756 for URLs you may need to enclose them with quotations as the examples show:
```
python detect.py --source "https://..."
```

**Comment by oes5756** [comment]
> 

AssertionError: 1/1: http://112.50.243.8/PLTV/88888888/224/3221225900/1.m3u8... Failed to open http://112.50.243.8/PLTV/88888888/224/3221225900/1.m3u8

it's my error

**Comment by oes5756** [comment]
> @oes5756 for URLs you may need to enclose them with quotations as the examples show:
> 
> ```
> python detect.py --source "https://..."
> ```

What address should be in https://?

**Comment by oes5756** [comment]
@glenn-jocher 

AssertionError: 1/1: http://112.50.243.8/PLTV/88888888/224/3221225900/1.m3u8... Failed to open http://112.50.243.8/PLTV/88888888/224/3221225900/1.m3u8

it's my error

What address should be in
"https://?????"

**Comment by glenn-jocher** [comment]
How am I supposed to tell you what address you should use?

**Comment by oes5756** [comment]
> How am I supposed to tell you what address you should use?

@glenn-jocher 
The code you told me is as follows
python detect_test.py --source "http://112.50.243.8/PLTV/88888888/224/3221225900/1.m3u8"

Where did this url address come from?
If you have to give a different url to each user,
I don't know how to find it and give it to you.

**Comment by glenn-jocher** [comment]
@oes5756 you provided the URL above in your original comment.

**Comment by oes5756** [comment]
> @oes5756 you provided the URL above in your original comment.

@glenn-jocher 
If you use the url you provided, the error will appear
AssertionError: 1/1: http://112.50.243.8/PLTV/88888888/224/3221225900/1.m3u8... Failed to open http://112.50.243.8/PLTV/88888888/224/3221225900/1.m3u8

**Comment by glenn-jocher** [comment]
@oes5756 then you should provide a valid URL
