### ISSUE TITLE
YOLOv5 test_batch0_pred.jpg is not throwing BB Boxes

### ISSUE THREAD

**Issue by iris-technology-inc** [ultralytics/yolov5#944]
## ❔Question
I am training an object detector using YOLOv5 and the test_batch0_pred.jpg is now showing bounding boxes. Is this normal, in my experience it should be showing a prediction? 

Maybe I am not doing enough epochs.
![test_batch0_pred](https://user-images.githubusercontent.com/60715661/92791601-cc74fc80-f37a-11ea-9059-96a59da45859.jpg)

You can see the training image for batch 0 is correct. 

![train_batch0](https://user-images.githubusercontent.com/60715661/92791690-df87cc80-f37a-11ea-90f1-a9d39dec4f34.jpg)

**Comment by wudashuo** [comment]
> test_batch0_pred.jpg is now showing bounding boxes

Do you mean `is not showing`
Your model didn't predict anything, have you completed your training? Maybe it's not enough.
What's the mAP of your model? you can see mAP during training.
Also, you can run `python detect.py --weights your_weights.pt --source your_image.jpg --view-img ` to see what's going on.

**Comment by iris-technology-inc** [comment]
Thanks @wudashuo for the advice! The model is still not outputting detections/ bounding boxes post training. 

Here is my my tensor board metrics post training: 

![Screen Shot 2020-09-11 at 11 03 07 AM](https://user-images.githubusercontent.com/60715661/92941773-cafd1000-f41e-11ea-9703-e9c08b69501d.png)

**Comment by iris-technology-inc** [comment]
I have opened the model in Xcode to review the outputs and they are not confidence outputs like I need, they are multi array outputs. Why is this? 

Do I need to configure the training differently? 


![Screen Shot 2020-09-11 at 11 18 00 AM](https://user-images.githubusercontent.com/60715661/92943378-b0c43180-f420-11ea-8949-b8984e602d2e.png)

**Comment by yassinethr** [comment]
Do you still have this issue ? I'm having it too ...
