### ISSUE TITLE
Typo in BaseModel._forward_once

### ISSUE THREAD

**Issue by fcakyon** [ultralytics/yolov5#9442]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

save_dir is assigned with bool value which raises an error (it should be Path)

https://github.com/ultralytics/yolov5/blob/03f2ca8eff8918b98169256d055353a1f15b8e32/models/yolo.py#L124

### Environment

YOLOv5 6.2 (commit: 03f2ca8eff8918b98169256d055353a1f15b8e32)
Ubuntu 18.04
Python 3.8

### Minimal Reproducible Example

```python
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

result = model(Image.open('data/images/bus.jpg'), size=1344, augment=False, profile=True)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@fcakyon good news 😃! Your original issue may now be fixed ✅ in PR #9443. This PR restricts PyTorch Hub models to simply using augment option. 

You can visualize models with `python detect.py --visualize` and you can profile model yamls with `python models/yolo.py --profile` or `--line-profile`

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
